### ISSUE TITLE
Rename Loader { CSV | JSON | Rows } Step.fieldsFromSource() to fieldsCorresponding()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10010]
In jOOQ 3.13, we've added `fieldsFromSource()` to these three types (see #8755). At first, there seems to be no obvious reason why we shouldn't also add `fieldsFromTarget()` methods that work the same way, but take the target table as a field source.

But in fact, the problem is simply that the name was ill chosen. What we really need here is a `fieldsCorresponding()` method name, where `CORRESPONDING` works like `UNION CORRESPONDING`, i.e. we match by corresponding field names in source and target.

**Comment by perceptron8** [comment]
@lukaseder I presume you meant `fieldsFromSource()` and `fieldsFromTarget()`?

**Comment by lukaseder** [comment]
Yes, thanks

**Comment by lukaseder** [comment]
Calling this:

```java
ctx.loadInto(T)
   .loadRecords(r1, r2)
   .fieldsFromTarget()
   .execute();
```

Is just convenience for:

```java
ctx.loadInto(T)
   .loadRecords(r1, r2)
   .fields(T.fields())
   .execute();
```

The value of this method is merely to be added for consistency and discoverability reasons. It isn't really necessary.

**Comment by perceptron8** [comment]
Sure! +1 for consistency.

**Comment by lukaseder** [comment]
Hmm, no, it's not the same thing. If this should be consistent with `fieldsFromSource()` (given its name), then we should still try to find matches between source and target.

Regrettable that we named the method `fieldsFromSource()` instead of using `matching` in the method name.

**Comment by lukaseder** [comment]
Or, the SQL term for "matching by column name" is `CORRESPONDING`

**Comment by lukaseder** [comment]
Which makes me think if we really need the distinction source / target. If the existing method was named `fieldsCorresponding()`, then things might be more clear. I'll rename the existing method to `fieldsCorresponding()`
