### ISSUE TITLE
Add support for PostgreSQL's JSON/JSONB -> and ->> operators

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10018]
PostgreSQL supports a variety of non-standard JSON navigational operators, which we should support as well. There are standard operators that do the same thing, but sometimes, the PostgreSQL ones are more concise. Given that a standard version exists, we can probably emulate most of them wherever `JSON_VALUE()` or `JSON_QUERY` is supported.

We'll support (always for `JSON` and `JSONB` where available):

### json element/attribute access

- [x] `json -> int` / `DSL.jsonGetElement(Field<JSON>, int)`: Get an array element as `JSON`
- [x] `json -> String` / `DSL.jsonGetAttribute(Field<JSON>, String)`: Get an object attribute as `JSON`
- [x] `json ->> int` / `DSL.jsonGetElementAsText(Field<JSON>, int)`: Get an array element as `TEXT`
- [x] `json ->> String` / `DSL.jsonGetAttributeAsText(Field<JSON>, String)`: Get an object attribute as `TEXT`

Emulations for `x->a` or `x->>a` can be done as follows:

- [x] CockraochDB: Native support
- [x] Db2: `JSON_QUERY(x, '$.' || a)` or `JSON_VALUE(x, '$.' || a)` (`JSON_QUERY` is not yet available as API: https://github.com/jOOQ/jOOQ/issues/13945). This stuff never works reliably. I'll wait for customer feedback to tweak the generated SQL.
- [x] MariaDB, MySQL: `JSON_EXTRACT(x, CONCAT('$.', a))` or `JSON_EXTRACT(x, CONCAT('$[', a, ']'))`
- [x] Oracle: `JSON_QUERY(x, '$.' || a)` or `JSON_QUERY(x, '$[' || a || ']')` (path literals can't be dynamic, though)
- [x] PostgreSQL: Native support
- [x] YugabyteDB: Native support
- [x] SQLite: Native support only starting with 3.38, before: like MySQL
- [x] SQLServer: `COALESCE(JSON_QUERY(x, '$.' || a), JSON_VALUE(x, '$.' || a))` (in "lax" mode, both of these functions return `null` in case the path doesn't return the expected type (object/array in the former case, scalar in the latter case). jOOQ can't know the type)

### Previously listed here, now moved to separate tasks:

- https://github.com/jOOQ/jOOQ/issues/13949
- https://github.com/jOOQ/jOOQ/issues/13950
- `json_to_recordset()`: No task yet (see https://github.com/jOOQ/jOOQ/issues/10486#issuecomment-673329514)

Other operators, functions from MySQL could also be considered, such as for example:

- https://github.com/jOOQ/jOOQ/issues/13951

Some additional operators might or might not be added to this list

----
See: https://github.com/t9t/jooq-postgresql-json

**Comment by sharpau** [comment]
Hey Lukas, not sure if this is the best place, but I didn't want to clutter another issue and couldn't find anywhere better.

When using DSL.field to use Postgres JSON operators, I discovered that by default, empty arrays in Postgres are cast to `int[]`:
https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/impl/Array.java#L106

This doesn't work for functions like the multiple keys variant of `-` that expect a `text[]` array:
https://www.postgresql.org/docs/12/functions-json.html

So as a result I have to do something awkward like this, to ensure I get a `text[]` even if my input is empty:
```
Field<?> keysToDelete = i.getDeletedProperties().isEmpty()
                        ? DSL.val("array[]::text[]")
                        : DSL.array(i.getDeletedProperties().toArray(String[]::new));
```

Maybe it would make sense to have an array override that allows specifying a type?

Anyway, let me know if I should file a separate issue. Thanks for all your work on jOOQ.

**Comment by lukaseder** [comment]
> Anyway, let me know if I should file a separate issue. Thanks for all your work on jOOQ.

Yes, please. It seems quite unrelated, apart from the fact that this is about PostgreSQL 😁

**Comment by mkurz** [comment]
Please add Postgres' `json_populate_record` and `json_populate_recordset` to this list  :wink:

**Comment by mkurz** [comment]
One more thing:

> * [ ]  `json || json` / `DSL.concat()`: Concatenate json documents

Any chance to add this `concat` method soon?

**Comment by j-martin** [comment]
Came here to ask for  `jsonb || jsonb` also. https://github.com/jOOQ/jOOQ/issues/10018#issuecomment-736625723

**Comment by Fynnyan** [comment]
Hello

Any news on this topic?

I came from #12360 , got the the same issue, the parser fails when parsing indexes that access json columns and it generates a lot of error noise and I didn't found a way to explicitly exclude only the indexes from the code gen.

The json / jsonb support would be helpful.

**Comment by lukaseder** [comment]
Thanks for the ping, @Fynnyan. Maybe about time, indeed. You can exclude indexes with this flag, for now: `<includeIndexes>false</includeIndexes>`
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-include-object-types

Of course, we'll never be able to parse *all* the operators, so there will always be some noise. Though, those arrow operators would be very useful also outside of parsing DDL, so let's do those ones first.

**Comment by lukaseder** [comment]
Most of those `->` arrow operators can be implemented with existing `JSON_VALUE` support. We'll just generate a JSON path that does the job. But because the arrow operators are simpler, it still makes sense to:

- Support them in the `QOM` (query object model)
- Parse them, of course

**Comment by Fynnyan** [comment]
> Thanks for the ping, @Fynnyan. Maybe about time, indeed. You can exclude indexes with this flag, for now: `<includeIndexes>false</includeIndexes>` https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-include-object-types
> 
> Of course, we'll never be able to parse _all_ the operators, so there will always be some noise. Though, those arrow operators would be very useful also outside of parsing DDL, so let's do those ones first.

Thank you for the reply, I did overlook that flag.

**Comment by lukaseder** [comment]
I've implemented support for `->` and `->>` for jOOQ 3.17, as well as emulations using `JSON_QUERY`, `JSON_VALUE`, and `JSON_EXTRACT`, respectively.

I've updated the issue description to reflect what's being done. I've also moved other tasks out of this issue to be able to close it. Most importantly, there are:

- https://github.com/jOOQ/jOOQ/issues/13949
- https://github.com/jOOQ/jOOQ/issues/13950

More functionality will be added and emulated as well in the near future.

**Comment by lukaseder** [comment]
The MySQL functionality will be added via:

- https://github.com/jOOQ/jOOQ/issues/13951

**Comment by lukaseder** [comment]
Reopening this. The various emulations aren't mimicking PostgreSQL perfectly yet. E.g. a `'"x"'` String-in-JSON is not the same thing as `'x'`

**Comment by lukaseder** [comment]
In summary, as per the SQLite documentation (https://www.sqlite.org/json1.html#jex):

<img width="861" alt="image" src="https://user-images.githubusercontent.com/734593/194823833-1e04bc20-349c-4599-a6a9-6f27cebdcde7.png">

One dialect can emulate `->` whereas the other dialect can emulate `->>`

**Comment by lukaseder** [comment]
The SQL Server implementation wasn't integration tested, because it's using `JSON_VALUE`, which hasn't been supported yet: https://github.com/jOOQ/jOOQ/issues/14064

**Comment by lukaseder** [comment]
I can't think of a way to correctly implement the non-`AsText` version of these functions in SQL Server. Only `AsText` will be supported

**Comment by lukaseder** [comment]
The MySQL implementation won't work on MariaDB because of this bug: https://jira.mariadb.org/browse/MDEV-29751

**Comment by lukaseder** [comment]
@victornoel Yes, please create a new issue. This one is no longer being tracked

**Comment by victornoel** [comment]
thx @lukaseder, here it is: https://github.com/jOOQ/jOOQ/issues/14324

**Comment by lukaseder** [comment]
We can probably add some kotlin sugar, too, similar to the convenience methods that map to `arrayGet()`:

```kotlin
@Support
operator fun <T> Field<Array<T>>.get(index: Int) = arrayGet(this, index)

@Support
operator fun <T> Field<Array<T>>.get(index: Field<Int>) = arrayGet(this, index)
```

This is magical!

```kotlin
    @Test
    fun testJSONFields() {
        assertEquals(jsonGetAttribute(json, "x"), json["x"])
        assertEquals(jsonGetAttribute(jsonObject("a", value("b")), "x"), jsonObject("a", value("b"))["x"])
        assertEquals(jsonGetElement(json, 1), json[1])
        assertEquals(jsonGetElement(jsonArray(value("a"), value("b")), 1), jsonArray(value("a"), value("b"))[1])

        assertEquals(jsonbGetAttribute(jsonb, "x"), jsonb["x"])
        assertEquals(jsonbGetAttribute(jsonbObject("a", value("b")), "x"), jsonbObject("a", value("b"))["x"])
        assertEquals(jsonbGetElement(jsonb, 1), jsonb[1])
        assertEquals(jsonbGetElement(jsonbArray(value("a"), value("b")), 1), jsonbArray(value("a"), value("b"))[1])
    }
```

All that's needed is this:

```kotlin

@Support(AURORA_POSTGRES, COCKROACHDB, DB2_11, MARIADB_10_2, MYSQL_5_7, ORACLE12C, POSTGRES, SNOWFLAKE, SQLITE_3_38, YUGABYTEDB)
@JvmName("jsonGetElement")
operator fun Field<JSON?>.get(index: Int) = jsonGetElement(this, index)

@Support(AURORA_POSTGRES, COCKROACHDB, DB2_11, MARIADB_10_2, MYSQL_5_7, ORACLE12C, POSTGRES, SNOWFLAKE, SQLITE_3_38, YUGABYTEDB)
@JvmName("jsonGetElement")
operator fun Field<JSON?>.get(index: Field<Int?>) = jsonGetElement(this, index)

@Support(AURORA_POSTGRES, COCKROACHDB, DB2_11, MARIADB_10_2, MYSQL_5_7, ORACLE12C, POSTGRES, SNOWFLAKE, SQLITE_3_38, YUGABYTEDB)
@JvmName("jsonGetAttribute")
operator fun Field<JSON?>.get(name: String) = jsonGetAttribute(this, name)

@Support(AURORA_POSTGRES, COCKROACHDB, DB2_11, MARIADB_10_2, MYSQL_5_7, ORACLE12C, POSTGRES, SNOWFLAKE, SQLITE_3_38, YUGABYTEDB)
@JvmName("jsonGetAttribute")
operator fun Field<JSON?>.get(name: Field<String?>) = jsonGetAttribute(this, name)

@Support(AURORA_POSTGRES, COCKROACHDB, DB2_11, MARIADB_10_2, MYSQL_5_7, ORACLE12C, POSTGRES, SNOWFLAKE, SQLITE_3_38, YUGABYTEDB)
@JvmName("jsonbGetElement")
operator fun Field<JSONB?>.get(index: Int) = jsonbGetElement(this, index)

@Support(AURORA_POSTGRES, COCKROACHDB, DB2_11, MARIADB_10_2, MYSQL_5_7, ORACLE12C, POSTGRES, SNOWFLAKE, SQLITE_3_38, YUGABYTEDB)
@JvmName("jsonbGetElement")
operator fun Field<JSONB?>.get(index: Field<Int?>) = jsonbGetElement(this, index)

@Support(AURORA_POSTGRES, COCKROACHDB, DB2_11, MARIADB_10_2, MYSQL_5_7, ORACLE12C, POSTGRES, SNOWFLAKE, SQLITE_3_38, YUGABYTEDB)
@JvmName("jsonbGetAttribute")
operator fun Field<JSONB?>.get(name: String) = jsonbGetAttribute(this, name)

@Support(AURORA_POSTGRES, COCKROACHDB, DB2_11, MARIADB_10_2, MYSQL_5_7, ORACLE12C, POSTGRES, SNOWFLAKE, SQLITE_3_38, YUGABYTEDB)
@JvmName("jsonbGetAttribute")
operator fun Field<JSONB?>.get(name: Field<String?>) = jsonbGetAttribute(this, name)
```

The `@JvmName` is required as otherwise, the methods would have the same signature
