### ISSUE TITLE
Why is Loader almost not using Table's fields metadata?

### ISSUE THREAD

**Issue by perceptron8** [jOOQ/jOOQ#10012]
This is going to be a continuation of #9992, which was not only about errors caused by casting, but also included question about `Loader`'s API.

Let's assume that parameter casts are inevitable for now (#1749). Currently, casts are based on actual parameter's value (including it's length in case of strings). What I was really asking in #9992 was: why isn't target table metadata being used to determine cast's target types? All we need should be available because of `.loadInto(Table)` call. Even if one passes plain fields to `LoaderXYZStep.fields(...)` later (i mean just names created with `DSL.field("NAME")`), that's not a problem. `LoaderImpl.fields[i]` still appears to contain all we need.

I believe that if `Loader` was using target fields metadata, there would be no #9992 and `java.sql.DataTruncation` exception, as `DataType` part of `Field` knows `N` of `VARCHAR(N)`.

Of course I can be terribly wrong. Sorry for wasting your time if my question is naive or stupid. I'm just curious.

Thank you for all your help so far!

**Comment by lukaseder** [comment]
Thanks for your question.

This code is quite old, there may have been a reason at the time that is no longer valid. I'll have to investigate this first. It does look like your suggestion could help work around #9992, but perhaps new issues would arise.

**Comment by lukaseder** [comment]
I've had a look at your example here (from #9992): https://github.com/perceptron8/jooq-9992/blob/master/src/test/java/perceptron8/LoaderTest.java

The entire issue has nothing to do with the `Loader` API, which is only distracting here. The `Loader` API does use the correct `Field` references from the target table. It uses the source fields only to find out the column names to use from the target table.

So, to answer your question here, we do everything correctly. The problem has to do with batching, which I'll explain in #9992

**Comment by perceptron8** [comment]
I agree, it uses correct `Field` references. That's why I wrote about `LoaderImpl.fields[i]`.

The question was not "Why is Loader almost not using Table's fields " but "Why is Loader almost not using Table's fields **metadata**?". I'll ask one more time then: "why isn't target table metadata being used to determine cast's target types?"

Why this issue has anything to do with Loader API? "if Loader was using target fields metadata, there would be no #9992 and java.sql.DataTruncation exception, as DataType part of Field knows N of VARCHAR(N)."

**Comment by perceptron8** [comment]
Ok, just saw https://github.com/jOOQ/jOOQ/issues/9992#issuecomment-608442301. That's exactly what I meant. Thanks!

**Comment by lukaseder** [comment]
> "Why is Loader almost not using Table's fields **metadata**?"

We *are* using the metadata in the `Loader`. But we are *not* passing it along when binding variables and producing the cast. The entire issue has nothing to do with `Loader` or even `Batch`, but it manifests in these areas because the truncation happens there due to the fact that batch statements generate SQL from the first set of bind values.
