### ISSUE TITLE
How to check if a column is "not null" or "null"

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#10028]
### Your question:

Given a `DSLContext`, is there a way to find out whether a table's column has the "not null" or "null" constraints on it (as in, `create table t1(v1 integer not null)`)? I see the `Field` type has an "isNull" or "isNotNull", but that seems to be something else. 

I also tried `dbCtx.ddl(table)` to get a `Query` type, and the debugger tells me the underlying object is of type `CreateTableImpl` that seems to have the information I need, but that class is package-private and not part of the public API.

### Versions:

- jOOQ: 3.12.1
- Java: 12.0.1
- Database (include vendor): H2
- OS: OSX
- JDBC Driver (include name if inofficial driver):

**Comment by lalithsuresh** [comment]
My bad, found it shortly after. `Field.getDataType().nullable()` does the trick.

**Comment by lukaseder** [comment]
Perfect, thanks for documenting your solution here. Yes, that's the way to query this information from jOOQ meta data.

Notice that if you get a hold of a `CreateTableImpl` query, you can interpret it using `dbCtx.meta(query)`, which will produce an `org.jooq.Meta` instance containing your table and its fields, and by consequence its data types and the nullable information.
