### ISSUE TITLE
Possibility to skip overwriting of packages with maven plugin.

### ISSUE THREAD

**Issue by rtrinker** [jOOQ/jOOQ#10021]
Hi there,

Is there a possibility when you use the maven plugin to generate the code, to not overwrite the existing packages? Couldn't find anything in the manual to that. Similar to the skip property you can set.

Thank you.

**Comment by lukaseder** [comment]
Thank you very much for your message. There currently is no such option. Why would you want it?

**Comment by rtrinker** [comment]
We have multiple people generating objects in one project, so if people generate objects for a new package, they either generate objects which are not needed in this package or delete existing ones that other people need.

**Comment by lukaseder** [comment]
Hmm, that doesn't sound like a problem that should appear in the first place. I'm not quite sure how the flag you're requesting would solve this problem thoroughly. It sounds like everyone would then be quite busy setting various flags which prevent some problems partially, but not fully.

The way I generally recommend using jOOQ and its code generator is this:

- Use a database change management tool like Flyway or Liquibase, or even jOOQ directly
- Put all database change management under version control
- Check in generated sources and/or the generated code as a library along with the versioned database change management code
- Require everyone to be diligent when merging their feature branches such that the master branch always contains consistent database change management code and generated jOOQ code

That way, you will be able to minimise the problems you've illustrated *and* improve the quality of your database change management and development process.

I hope this helps.

**Comment by lukaseder** [comment]
I'm rejecting this feature request mainly because it doesn't solve the problem you're having, but makes working with generated code even harder.

For example, if someone adds a column to table A, that column is added in a file `A.java`. Someone else wants to add a column to table B and prevent the change in `A.java`. Skipping overwriting of packages wouldn't solve this problem.
