### ISSUE TITLE
When using Codegen on mysql throws invalid sql error

### ISSUE THREAD

**Issue by gpor0** [jOOQ/jOOQ#10035]
Tried to execute codegen 3.13.0 on mysql 5.7 and received exception on generated sql by JOOQ:

`select 1 as one
where exists (
  select 1 as one
  from information_schema.TABLES
  where (
    information_schema.TABLES.TABLE_NAME = 'proc'
    and information_schema.TABLES.TABLE_SCHEMA = 'mysql'
  )
)`

`Error running jOOQ code generation tool: Error generating code for catalog: org.jooq.exception.DataAccessException: SQL [select 1 as one where exists (select 1 as one from information_schema.TABLES where (information_schema.TABLES.TABLE_NAME = ? and information_schema.TABLES.TABLE_SCHEMA = ?))]; You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where exists (select 1 as one from information_schema.TABLES where (information_' at line 1 -> [Help 1]
 `

**Comment by gpor0** [comment]
Looks like its fixed in latest release 3.13.1.

**Comment by lukaseder** [comment]
Thanks for the report and the update.

This is a duplicate of https://github.com/jOOQ/jOOQ/issues/9832. Backport to 3.13.1 with https://github.com/jOOQ/jOOQ/issues/9860
