### ISSUE TITLE
Deprecate the H2 style MERGE statement

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10045]
H2 (and HANA, see #10044) supports SQL standard `MERGE` now:
http://h2database.com/html/commands.html#merge_using

The H2 specific `MERGE` statement is no longer necessary. We can deprecate it. Removing it will remove quite some API (46 interfaces).

**Comment by lukaseder** [comment]
If this turns out to be a popular feature, I had rather add a synthetic `ON DUPLICATE KEY UPDATE` clause to the `INSERT` statement, which re-implements H2's `MERGE` semantics.

**Comment by theodiefenthal** [comment]
After I migrated to JOOQ 3.14, I'm now removing some deprecated warnings with regards to merges right now. 

From the previous:
```java
ctx
                        .mergeInto(MYDATA, MYDATA.ID, MYDATA.BODY)
                        .key(MYDATA.ID)
                        .values(data.getId(), data.getBody())
                        .execute()
```

I now need to be a bit more verbose, effectively double specifying my variables:
```java
ctx
                        .mergeInto(MYDATA)
                        .using(ctx.selectOne())
                        .on(MYDATA.ID.eq(data.getId()))
                        .whenMatchedThenUpdate().set(MYDATA.BODY, data.getBody())
                        .whenNotMatchedThenInsert(MYDATA.BODY).values(data.getBody())
                        .execute();
```

If I'd go for INSERT .. ON DUPLICATE KEY UPDATE, I think, I'd still need to repeat myself (not tested):
```java
ctx
                    .insertInto(MYDATA, MYDATA.ID, MYDATA.BODY)
                    .values(data.getId(), data.getBody())
                    .onDuplicateKeyUpdate()
                    .set(MYDATA.BODY, data.getBody())
                    .execute()
```

I wonder if it would be a good idea to add some syntactic sugar for the standard case of "add a new line or replace the existing one" in the merge syntax by instead of specifyig "whenMatchenThen" and "whenNotmatchedThen" just specify a "set" like so:
```java
ctx
                        .mergeInto(MYDATA)
                        .using(ctx.selectOne())
                        .on(MYDATA.ID.eq(data.getId()))
                        .set(MYDATA.BODY, data.getBody())
                        .execute();
```

It should be easy for JOOQ to formulate the corresponding MERGE statement in the background, shouldn't it?

**Comment by lukaseder** [comment]
How about the new `UpdatableRecord.merge()` method?

```java
ctx.newRecord(MYDATA, data).merge();
```

Look sugary enough? :)

**Comment by theodiefenthal** [comment]
That's really cool. I wasn't aware about that :+1:

**Comment by theodiefenthal** [comment]
One more mention: 

With your posted record-variant, the prepared SQL looks like so:
```sql
merge into "MYSCHEMA"."MYDATA" 
     using (select 1 "one" from dual) 
	    on ((("MYSCHEMA"."MYDATA"."ID", 1) = ((?, 1)) or 1 = 0)) 
	  when matched then update set "MYSCHEMA"."MYDATA"."ID" = ?, 
	                               "MYSCHEMA"."MYDATA"."BODY" = ?,  
						     where "MYSCHEMA"."MYDATA"."ID" = ? 
	  when not matched then insert ("ID", "BODY") 
	                        values (?, ?)
```
From my understanding, this would transmit "body" two times over the wire? Is that correct?
With the h2 variant, the rendered sql looked like this:
```sql
merge into "MYSCHEMA"."MYDATA" 
     using ((select ? "s1", ? "s2" from dual)) "src" 
	    on ("MYSCHEMA"."MYDATA"."ID" = "src"."s1") 
      when matched then update set "MYSCHEMA"."MYDATA"."BODY" = "src"."s2" 
	  when not matched then insert ("ID", "BODY") 
	                        values ("src"."s1", "src"."s2")
```
Might it be worth to change that or could that cause some issues?

**Comment by lukaseder** [comment]
@theodiefenthal Yes, that could be done in some cases. If you look at the logic behind `UpdatableRecordImpl::merge`, you'll see that a lot needs to be taken into consideration, so it's not a simple change, but I can see how this could be useful in some cases. Currently, for simplicity of our internals, we just go through the usual `INSERT .. ON DUPLICATE KEY UPDATE` API, because that's most widely supported, so we achieve best code reuse and thus correctness.

If you're interested in this improvement, feel free to create a new feature request.

**Comment by paolodedios** [comment]
The new integration with Apache Ignite in jOOQ 3.15 only supports the SQL-99 version of MERGE INTO.  There does not seem to be any plans yet to support the MERGE USING statement in future versions of Ignite.  Will this affect the deprecation status or timeline of the mergeInto(Table, Field...) API?

**Comment by lukaseder** [comment]
Thanks for your comment, @paolodedios. At first, I was thinking the same thing - someone copied H2's syntax making it more useful again.  But then, after closer investigation, the conclusion was that:

1. Ignite's SQL implementation is far from stable / reliable
2. Ignite may change their dependency and syntax support from H2 style to anything other in the future

See:

- https://github.com/jOOQ/jOOQ/issues/10551#issuecomment-763807282
- http://apache-ignite-users.70518.x6.nabble.com/SQL-strategy-for-Apache-Ignite-3-0-td35255.html

It's a bit of a moving target, hence re-establishing support for this H2 specific MERGE syntax doesn't seem useful in the long run.

**Comment by paolodedios** [comment]
Thank you for the explanation, @lukaseder.  Hopefully when Ignite 3.0 migrates to the Apache Calcite SQL engine, then more of the standard SQL features would be supported.

**Comment by lukaseder** [comment]
Yes, that seems very promising indeed. Quite the breaking change, but much better than the status quo. Let me add Ignite 3.0 it to the list: https://github.com/jOOQ/jOOQ/issues/12107

**Comment by lukaseder** [comment]
Another option instead of using this H2 style `MERGE` is the new `EXCLUDED` support: https://github.com/jOOQ/jOOQ/issues/7912

I do wonder if this deprecation was premature, though. Given the user needs, it seems that it was quite a useful statement after all...
