### ISSUE TITLE
Add support for optimistic locking with UpdatableRecord.merge()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10050]
The `UpdatableRecord.merge()` operation should behave just like `store()` when optimistic locking is active.

- When we have a version/timestamp value ready means that we can run an `UPDATE` statement.
- When we don't have such a value ready, it means that we will run an `INSERT` statement.

The `MERGE` statement is executed only when optimistic locking is turned off, or when a given table doesn't have version/timestamp fields.

**Comment by lukaseder** [comment]
The new feature is now ready: https://github.com/jOOQ/jOOQ/issues/7291. We should be able to fix the H2 implementation here

**Comment by lukaseder** [comment]
The original thinking here is wrong in fact. The `UpdatableRecord.merge()` operation should behave just like `store()` when optimistic locking is active.

- When we have a version/timestamp value ready means that we can run an `UPDATE` statement.
- When we don't have such a value ready, it means that we will run an `INSERT` statement.

The `MERGE` statement is executed only when optimistic locking is turned off, or when a given table doesn't have version/timestamp fields. As simple as that.

**Comment by ghilainm** [comment]
Hello @lukaseder , I think the documentation for the method `onDuplicateKeyUpdate` should be somehow updated to explain the behavior in case of optimistic locking. Indeed, when this mode is enabled this is not true anymore `Add an ON DUPLICATE KEY UPDATE clause to this INSERT statement.`.

**Comment by lukaseder** [comment]
@ghilainm Can you please create a new issue and add more details?

**Comment by Mr-EmPee** [comment]
@lukaseder Shouldn't the behavior change only if BOTH optimistic locking is activated and the table has a column for it?

> The MERGE statement is executed only when optimistic locking is turned off, or when a given table doesn't have version/timestamp fields. As simple as that. I've updated the issue description to reflect that.

Is this statement still valid or is there a bug on my end?
If I have a global setting with optimistic locking set to true and execute some batchMerges, the batches on the table with timestamp fields works but the ones that runs on the table without the timestamp field try to do an insert even if the primary key is set and this cause a conflict.

Instead if I apply the settings of the optimistic locking only where is needed it works.
```java
    if (optimisticLocking) {
      jooq = jooq.configuration()
                 .deriveSettings(s -> {
                   s.setExecuteWithOptimisticLocking(true);
                   return s;
                 }).dsl();
    }
```

**Comment by lukaseder** [comment]
@Mr-EmPee: You too, can you please create a new issue and add all the requested details.
