### ISSUE TITLE
Emulate JSON_ARRAYAGG() in older MariaDB versions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10060]
MariaDB has introduced `JSON_ARRAYAGG()` in the most recent version 10.5. In older versions, we can emulate it using something like:

```sql
SELECT CONCAT('[', GROUP_CONCAT(json_object(...)), ']') FROM ...
```

Some other dialects may profit from this as well (e.g. Db2)

----
See also: https://twitter.com/simas_ch/status/1249002050597400578?s=20

**Comment by Igneaalis** [comment]
Well, it helped me, thanks!
