### ISSUE TITLE
Add XMLMapperProvider and JSONMapperProvider SPIs

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10065]
With the newly introduced ability to project XML and JSON using standard SQL APIs for that purpose, it becomes evident that being able to bind (marshal/unmarshal or map/unmap) XML/JSON content to POJOs is a necessity. For example, users may want to do something like this:

```java
ctx.select(
  jsonObject(
    jsonEntry("a", T.A),
    jsonEntry("b", T.B),
    jsonEntry("c", jsonObject("d", T.D))
  )
).from(T).fetchInto(Outer.class);

class Outer {
  String a;
  String b;
  Nested c;
}

class Nested {
  String d;
}
```

With appropriate SPIs, users could write a single, Jackson based (for example) implementation for all these mapping algorithms

**Comment by lukaseder** [comment]
A related idea was the `ConverterProvider`, which was an SPI suggestion for arbitrary pairs of `<T, U> ` types: https://github.com/jOOQ/jOOQ/issues/3896. It doesn't work well because the type pairs don't fully describe all the possible conversion paths between two types (e.g. `<byte[], String>` or even `<String, String>`). It is different with JSON and XML bindings, where the `U` type is expected to be a POJO, and the binding is always non ambiguous.

In this context, it may be reasonable to offer bindings specifically for JSON and XML, instead of reviving the generic `ConverterProvider` SPI.

**Comment by lukaseder** [comment]
What's more, these new `BindingProviders` do not adhere well to the `Converter` SPI, because the `<U>` type would be `Object`, the bindings are generic, not POJO type specific.

**Comment by lukaseder** [comment]
A different name than `BindingProvider` should be chosen, to prevent confusion with `org.jooq.Binding`, which is about bind variables. `XMLMappingProvider` and `JSONMappingProvider` seem better.

**Comment by baev** [comment]
BTW It looks like this particular feature request can be applied not only to XML or JSON DataTypes. Imagine having a possibility to register a single mapping from `Timestamp` type to `SomeCustomDateTimeDto` which allows you to use `SomeCustomDateTimeDto` in dtos in addition to default supported types

**Comment by lukaseder** [comment]
You're back at discussing #3896, which I'm currently reviewing once more.

**Comment by lukaseder** [comment]
Personally, I think your particular case...

> Imagine having a possibility to register a single mapping from `Timestamp` type to `SomeCustomDateTimeDto` which allows you to use `SomeCustomDateTimeDto` in dtos in addition to default supported types

... Should mostly be covered by using data type bindings on generated code. That's almost always the best approach. The benefit here would be additional type safety, because you get a free `Field<SomeCustomDateTimeDto>` expressions, which can only be compared with other  `Field<SomeCustomDateTimeDto>` expressions.

**Comment by lukaseder** [comment]
... But I admit the idea of being able to provide an SPI that can say "I know how to convert between types `<T>` and `<U>`, overriding the default" can be useful.

**Comment by baev** [comment]
> ... Should mostly be covered by using data type bindings on generated code. That's almost always the best approach

yep, but not every resultset is represented by fields from table. For example, we are using stuff like `from generate_series(now() - '3 hours'::interval, now(), '1 minute'::interval) dates` a lot

**Comment by lukaseder** [comment]
> yep, but not every resultset is represented by fields from table. For example, we are using stuff like `from generate_series(now() - '3 hours'::interval, now(), '1 minute'::interval) dates` a lot

There is always a price you're paying for using plain SQL. In your example, there *is* a table, and it *has* fields. You just don't know them at compile time. But it would be possible to generate a table valued function from it, attach bindings to it, and then have the desired data type attached to the expression in a type safe way.

Anyway. I always want to recommend using data type bindings, because they're the most *thorough* and far sighted approach. Ad-hoc and unsafe data type mapping can still be useful.

**Comment by lukaseder** [comment]
Reviving the `ConverterProvider` from #3896 would make this quite easy to achieve

**Comment by lukaseder** [comment]
I'll implement this via `ConverterProvider`: #3896

**Comment by baev** [comment]
Maybe I'm missing something, thats an example of code that we are using:

```java
final Name periods = name("periods");
final Field<Timestamp> periodDate = field(name(periods, date), Timestamp.class);
...

//query
dsl
.with(periods)
    .as(
        select(
            dateTrunc(truncBy, periodsField).as(date)
        )
     .from(generateSeries(
        from,
        to,
        interval
    ).as(periods))
)
.select(
    periodDate,
    ...//some aggregation from joined tables
)
```

where `generateSeries` defined as in common utils module as

```java
public static Table<?> generateSeries(final Field<Timestamp> start,
                                          final Field<Timestamp> stop,
                                          final String step) {
    return table("generate_series({0}, {1}, {2}::interval)", start, stop, step);
}
```

At this point I'm ok with having `periodDate` as Timestamp field as it can be used in other functions during joining / aggregation. The code is simple and type-safe. In some particular cases it may require to read periodDate as Timestamp, in some - like other data type, it's mostly depends on context. How applying data type bindings may help in this case?

**Comment by lukaseder** [comment]
Either, you use the code generator to produce the `generateSeries()` function (there's a bug, which you'd have to work around: https://github.com/jOOQ/jOOQ/issues/4055), or you supply a converter / data type binding with your `periodDate` definition:

```java
final Field<Timestamp> periodDate = field(name(periods, date), SQLDataType.TIMESTAMP.asConvertedDataType(new MyConverter())`;
```
