### ISSUE TITLE
trueCondition() and falseCondition() should generate TRUE and FALSE, where BOOLEAN types are supported

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10064]
`DSL.trueCondition()` and `DSL.falseCondition()` currently produce predicates `1 = 1` and `1 = 0`, always, in all dialects. This is obviously correct, but it would be nicer if we generated `TRUE` and `FALSE` in dialects that have native `BOOLEAN` type support.

The affected dialects are:

- [x] CockroachDB
- [x] ~DB2~ (not supported yet, see #10063)
- [x] Derby
- [x] H2
- [x] HSQLDB
- [x] MariaDB
- [x] MySQL
- [x] PostgreSQL

More will be listed here, if necessary

**Comment by verdi8** [comment]
Hi,

The behaviour of the code change is not what's described in the issue. What has been done :
trueCondition(), .... generates 1=1 ... where BOOLEAN types are NOT supported for known dialects.

It's not only a matter of words ;-) There had been a breaking change.

When using a non listed dialect that doesn't support Booleans (eg Oracle or an older version of the supporting ones) it defaultly  generates an TRUE (or FALSE) condition instead of a was-working-everywhere-since-sql-86 1=1 (or 1=0).

Is this another issue to open ?

Many thanks

**Comment by lukaseder** [comment]
> Is this another issue to open ?

yes, please, because I don't see the breaking change yet

**Comment by devjava65** [comment]
Hello, 
Additionnel infos : 

for org.jooq:jooq:3.14.13 for exemple, the 2 dialects SQLITE and FIREBIRD are not supporting true condition (where true) then the query should be converted to (where 1=1), 

It can be done with using custom sqlDialect : 
DSLContext dsl = using(connectionProvider, SQLDialect.SQLITE, settings);

This will results (where 1=1) condition, so it works for Oracle too.

**Comment by devjava65** [comment]
Hello,
Additionnel infos :

for org.jooq:jooq:3.14.13 for exemple, the 2 dialects SQLITE and FIREBIRD are not supporting true condition (where true) then the query should be converted to (where 1=1),

It can be done with using custom sqlDialect :
DSLContext dsl = using(connectionProvider, SQLDialect.SQLITE, settings);

This will results (where 1=1) condition, so it works for Oracle too.

**Comment by lukaseder** [comment]
> for org.jooq:jooq:3.14.13 for exemple, the 2 dialects SQLITE and FIREBIRD are not supporting true condition (where true) then the query should be converted to (where 1=1),

I'm trying these:

```sql
select sqlite_version() where true
```

Output:

```
3.34.0
```

Or

```sql
select rdb$get_context('SYSTEM', 'ENGINE_VERSION')
from rdb$database
where true;
```

Output:

```
3.0.7
```

Were you using other RDBMS versions (which we still support)?

In Oracle, we generate `where 1 = 1` if you're using `SQLDialect.ORACLE`. Regarding @verdi8's claim:

> When using a non listed dialect that doesn't support Booleans (eg Oracle or an older version of the supporting ones) it defaultly generates an TRUE (or FALSE) condition instead of a was-working-everywhere-since-sql-86 1=1 (or 1=0).

We don't "support" anything unsupported out of the box. How could we even integration test that? What were you using, `SQLDialect.DEFAULT`? The behaviour of that is not strictly specified. It is useful for debugging purposes only (e.g. when printing out some SQL, independently of the actual dialect). It tries to most closely resemble what you're calling in the jOOQ API. There is no guarantee of this behaviour to be set in stone. If you're using Oracle, please use `SQLDialect.ORACLE`, which we formally integration test against various Oracle versions.
