### ISSUE TITLE
Sequences are generated with inconsistent types

### ISSUE THREAD

**Issue by egemenvardar** [jOOQ/jOOQ#10077]
### Your question:

Some sequences are generated with `Long` type, whereas some others are with `Integer` type, although all sequences in the database are for integer columns. As an example for generated sequences:

```
public static final Sequence<Integer> CREDIT_ID_SEQ = new SequenceImpl<Integer>("credit_id_seq", MySchema.MYSCHEMA, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
```
```
public static final Sequence<Long> COUNTRY_ID_SEQ = new SequenceImpl<Long>("country_id_seq", MySchema.MYSCHEMA, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
```
PK of both `credit` and `country` tables are `integer`. I am generating the models directly by executing  `jooq-codegen:generate` from IntelliJ.

My colleagues do not have this problem. Sequences are always generated with `Long` type for them. I am not sure whether this is a bug in the generator or if I am doing something wrong/different:

- My colleagues are on macOS. Besides that, we use the same jOOQ, Java and PostgreSQL versions. Could this behavior be due to different OS and drivers?
- Shouldn't the sequences be always generated with `Integer` type in our case, since the corresponding columns in database are `integer`?

Thanks in advance for your support!

### Versions:

- jOOQ: 3.12.3
- Java: 11
- Database (include vendor): PostgreSQL 10
- OS: Windows 10 Pro (Version 1903)
- JDBC Driver (include name if inofficial driver): PostgreSQL v42.2.5

**Comment by lukaseder** [comment]
Thanks a lot for your message. The code generator uses this information to decide what data type a sequence is using (simplified query):

```sql
select sequence_name, data_type
from information_schema.sequences
```

Now, try this:

```sql
create sequence s1;
create sequence s2 as int;
create table t (i serial);
```

Run this query:

```sql
select sequence_name, data_type
from information_schema.sequences
where sequence_name in ('s1', 's2', 't_i_seq');
```

It yields:

```
sequence_name|data_type|
-------------|---------|
s1           |bigint   |
s2           |integer  |
t_i_seq      |integer  |
```

It depends on how you create the sequence. If you cannot change how sequences are created, then you can force the data type of any generated object, including sequences, to your preferred type:

https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types

I hope this helps

**Comment by lukaseder** [comment]
Regarding your specific questions

> * My colleagues are on macOS. Besides that, we use the same jOOQ, Java and PostgreSQL versions. Could this behavior be due to different OS and drivers?

I don't know. There might be an environment specific default. The PostgreSQL manual specifies `BIGINT` to be the default: https://www.postgresql.org/docs/current/sql-createsequence.html

> * Shouldn't the sequences be always generated with `Integer` type in our case, since the corresponding columns in database are `integer`?

Yes, but perhaps, they are re-created using some generated `CREATE SEQUENCE` script instead of the `CREATE TABLE` script?

**Comment by egemenvardar** [comment]
Thanks a lot for your detailed answer. I checked the old flyway migration files, and found out that some sequences were created as
```
CREATE SEQUENCE some_seq
    AS INTEGER
    START WITH 1
	...
```
and some others as
```
CREATE SEQUENCE some_other_seq
    START WITH 1	
	...
```
which resulted in having some sequences with data type `BIGINT` (since this is the PostgreSQL default as you wrote), and some others with type `INTEGER`.

So it looks like my generated code looks correct. Not sure why my colleagues end up with generating `Sequence<Long>` for all the sequences. Nevertheless, we should be able to change our sequence types and make them consistent. Thanks again for your support!
