### ISSUE TITLE
How to remove @Generated annotation 

### ISSUE THREAD

**Issue by amin3mej** [jOOQ/jOOQ#10088]
In the beginning, Thank you for your helpful library. As i'm newbie in java and we're using jOOQ for connecting to database, I have a problem with jOOQ. 
I generated my classes with jOOQ and it put this annotation before every generated class:
```
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1",
        "catalog version:_1585834583",
        "schema version:app_1585834583"
    },
    date = "2020-04-19T18:46:25.292Z",
    comments = "This class is generated by jOOQ"
)
```

I putted generated folder in the src directory and everytime I rebuild jOOQ, a lot of files changed. So, It's hard to review the code. 
I want to disabled it but i wasn't successful.

Also, I add `generatedAnnotation = false` to my build.gradle but nothing changed.
This is my configuration: 

Build.gradle:
```
jooq {
    version = '3.13.1'
    edition = 'OSS'
    generateSchemaSourceOnCompilation = true
    main(sourceSets.main) {
        jdbc {
            driver = 'com.mysql.cj.jdbc.Driver'
            url = buildDbUrl
            user = buildDbUser
            password = buildDbPassword
        }
        generator {
            name = 'org.jooq.codegen.JavaGenerator'
            strategy {
                name = null
                matchers {
                    tables {
                        table {
                            pojoClass {
                                transform = 'PASCAL'
                                expression = '\$0_POJO'
                            }
                            tableClass {
                                transform = 'PASCAL'
                                expression = '\$0_Table'
                            }
                        }
                    }
                }
            }
            database {
                name = 'org.jooq.meta.mysql.MySQLDatabase'

                inputSchema = buildDbSchema
                outputSchema = ''
                forcedTypes {
                    forcedType {
                        name = 'BOOLEAN'
                        includeTypes = '(?i:TINYINT\\(1\\))'
                    }
                 }
                catalogVersionProvider = 'SELECT CONCAT(:catalog_name, \'_\', MAX(`apply_time`)) FROM `migration`'
                schemaVersionProvider = 'SELECT CONCAT(:schema_name, \'_\', MAX(`apply_time`)) FROM `migration`'
            }
            generate {
                relations = true
                deprecated = false
                records = true
                immutablePojos = true
                fluentSetters = true
                daos = true
                pojos = true
                pojosEqualsAndHashCode = true
                generatedAnnotation = false
            }
            target {
                packageName = 'com.website.db.generated'
                directory = 'src/main/generated'
            }
        }
    }
}
```
### Versions:

- jOOQ: 3.13.1
- Java: 11
- Database (include vendor): mysql:mysql-connector-java:8.0.19
- OS: Gnu/Linux (Ubuntu 19.10)
- JDBC Driver (include name if inofficial driver): com.mysql.cj.jdbc.Driver

Thanks.

**Comment by lukaseder** [comment]
Thanks a lot for your message.

You're using `catalogVersionProvider` and `schemaVersionProvider`, which require a `@Generated` annotation so the version can be annotated on your generated schema. This is why your `generatedAnnotation` setting is being ignored.

There should be a message in your log output:

```
(forced to true because of <schemaVersionProvider/> or <catalogVersionProvider/>)
```

I hope this helps.

**Comment by lukaseder** [comment]
Notice that no code should be re-generated if you provide a `schemaVersionProvider` and the version ID matches. Is your ``MAX(`apply_time`)`` expression stable for identical versions of your schema?

As a workaround, we'll offer turning off the generation of the date information, which can get in the way of incremental builds, otherwise: https://github.com/jOOQ/jOOQ/issues/10090. In your case, with the version providers, that shouldn't happen, though.

**Comment by amin3mej** [comment]
@lukaseder Thank you very much for your response.

About `(forced to true because ...)` , You are right. I didn't see that before. 
The annotation have gone after removing Version Providers.

Yes, `MAX(`apply_time`)` is an unixtimestamp for the latest migration that has executed.
Apart from date, `serialVersionUID` got changed too. Maybe, It's not a bad idea to keep serialVersionUID steady in regenerations.

**Comment by lukaseder** [comment]
> Apart from date, `serialVersionUID` got changed too. Maybe, It's not a bad idea to keep serialVersionUID steady in regenerations.

The version is calculated from the string content, so when the date changes, the version changes as well.

But the check whether a *version* should be regenerated happens before all that. I suspect that maybe, your version number isn't as stable as it seems? Since you're using a timestamp, does that mean that even if you apply a migration that doesn't change anything, will that timestamp be updated? Because if it is being updated, then we have to re-generate.

**Comment by amin3mej** [comment]
You are right but in this case, anything does not changed in the db. I just added a forcedType and regenarated files.

**Comment by lukaseder** [comment]
> You are right but in this case, anything does not changed in the db

Well, I cannot reproduce this easily. Our integration tests suggest that all is fine. The tests use this:

```xml
<catalogVersionProvider>1</catalogVersionProvider>
<schemaVersionProvider>1</schemaVersionProvider>
```

However, I don't know what the third party Gradle plugin you're using is doing behind the scenes. It may well be that they're doing stuff that forces jOOQ's code generator to re-generate things nonetheless.

**Comment by amin3mej** [comment]
I use `etiennestuder/gradle-jooq-plugin`.

Anyway, I got my answer. Thank you for your fast and helpful answer.
God bless you and jOOQ.
