### ISSUE TITLE
Unknown columns in code generator queries for Firebird 2.5

### ISSUE THREAD

**Issue by dustyman145** [jOOQ/jOOQ#10139]
Since #9442 [Sequence flags code generation support for Firebird] code generation for my Firebird 2.5 database will fail because Firebird 2.5 doesn't have `RDB$GENERATORS.RDB$INITIAL_VALUE` column.

`Caused by: java.lang.RuntimeException: org.jooq.exception.DataAccessException: SQL [select trim(RDB$GENERATORS.RDB$GENERATOR_NAME) RDB$GENERATOR_NAME, nullif(RDB$GENERATORS.RDB$INITIAL_VALUE,0) RDB$INITIAL_VALUE, nullif(RDB$GENERATORS.RDB$GENERATOR_INCREMENT,1) RDB$GENERATOR_INCREMENT from RDB$GENERATORS order by 1]; Dynamic SQL Error; SQL error code = -206; Column unknown; RDB$GENERATORS.RDB$INITIAL_VALUE; At line 1, column 90 [SQLState:42S22, ISC error code:335544578]`

**Comment by lukaseder** [comment]
Thanks a lot for your report. We'll look into this soon.

**Comment by sugihartolim** [comment]
I tried using an older version of jooq-codegen until this is resolved.  Looks fine so far. 
  `<plugin>`
    `<groupId>org.jooq</groupId>`
    `<artifactId>jooq-codegen-maven</artifactId>`
    `<version>3.12.4</version>`
    `...`
  `</plugin>`

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.14.0. Backport scheduled for 3.13.3 (#10332)
