### ISSUE TITLE
Remove reference to ADBA from docs

### ISSUE THREAD

**Issue by benmccann** [jOOQ/jOOQ#10130]
https://www.jooq.org/doc/3.13/manual/sql-execution/fetching/reactive-fetching/ mentions that Oracle's ADBA might be supported in the future

Oracle as stopped work on ADBA, so I'm guessing this won't be worth supporting:
https://mail.openjdk.java.net/pipermail/jdbc-spec-discuss/2019-September/000529.html

**Comment by lukaseder** [comment]
Thanks a lot for pointing this out. Agreed, it shouldn't be mentioned from the docs anymore.

**Comment by lukaseder** [comment]
Manual will be updated soon
