### ISSUE TITLE
Generate an xml schema with a table that has only the columns that are needed

### ISSUE THREAD

**Issue by Erebonk** [jOOQ/jOOQ#10140]
Hi! 
So, my question is how can I create a xml schema with a table that will only have the columns I need?
Generate with Gradle and I've just used "includes" param for settings:

```
...
includes = '=someTable|secondTable'
...
```

But, my tables have plenty of columns, I only want to use two or three columns at all.
How I can use it and there's a decision for my case?

I've done some research but without success.
Thank you!

Versions:
- jooq version 3.12.3
- java: open jdk 11
- postgres 
- Gradle

**Comment by Erebonk** [comment]
This way doesn't work fo me:

outputSchema = 'schema'
includes = '. schema\\.table\\.(id|sid)'
includeExcludeColumns = true

And this one:
outputSchema = 'schema'
includes = '. schema\\.(table\\.(id|sid))'
includeExcludeColumns = true

**Comment by lukaseder** [comment]
Thanks for your message.

What is the reason why you used `. ` (period and whitespace) at the beginning of your regular expression?

Note that you still have to include your table as well, not just its columns. So, try this:

```
includes = 'schema\\.table(\\.(id|sid))?'
```

I hope this helps

**Comment by Erebonk** [comment]
> Thanks for your message.
> 
> What is the reason why you used `. ` (period and whitespace) at the beginning of your regular expression?

Sorry, my mistakes.

> Note that you still have to include your table as well, not just its columns. So, try this:
> 
> ```
> includes = 'schema\\.table(\\.(id|sid))?'
> ```
> 
> I hope this helps

It works for me.
Thank you!
