### ISSUE TITLE
createIndexIfNotExists().on does not correctly qualify aliased table

### ISSUE THREAD

**Issue by chilliger** [jOOQ/jOOQ#10147]
```
table = table(name("testi")).as("t");
field = field(name(table.getName(), "f1"));
ctx.createIndexIfNotExists("new_index").on(table, field).execute();
```

The above renders:
`create index if not exists "new_index" on "t"("f1"))`

Whereas
`ctx.fetchExists(selectOne().from(table))`
renders:
```
select 1 "one"
from "testi" "t"
```

I'am not really sure if this is intented.

- jOOQ: 3.11.11
- Java: 8
- Database (include vendor): POSTGRES 9.6
- OS: Linux
- JDBC Driver (include name if inofficial driver): Hikari

**Comment by lukaseder** [comment]
Thanks for your report. Yes, that's the intention here. You are creating an aliased table reference. It can either produce its declaration (only in `FROM` clauses), or its reference (anywhere else). This is explained here: https://github.com/jOOQ/jOOQ/issues/10119
