### ISSUE TITLE
JOOQ 3.9.4 with PostgreSQL 10.1

### ISSUE THREAD

**Issue by zxymd5** [jOOQ/jOOQ#10142]
[WARNING] SQL exception            : Exception while executing meta query: An I/O error occurred while sending to the backend.

I use spring cloud 1.5.6 and apache maven 3.5.0, PostgreSQL 10.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit
It occurs on windows 10. But never happens on ubuntu linux.

**Comment by lukaseder** [comment]
Thanky ou very much for your report. I'm not aware of any such problem. There could be many reasons including:

- Wrong server setup
- Wrong JDBC connection
- Wrong JDBC driver version
- etc.

We might be able to help, but we'd need more information first.

**Comment by zxymd5** [comment]
> Thanky ou very much for your report. I'm not aware of any such problem. There could be many reasons including:
> 
> * Wrong server setup
> * Wrong JDBC connection
> * Wrong JDBC driver version
> * etc.
> 
> We might be able to help, but we'd need more information first.

It's the network problem. I have tested on Windows 8.1，Windows 7, Windows 8, Windows 10. Error occurs when I use the wifi network. When I connect my computer and the router with a cable, it's works normal. So it's not your problem.

**Comment by lukaseder** [comment]
Thanks for confirming that.
