### ISSUE TITLE
Add support for H2 and PostgreSQL array functions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10175]
H2 and PostgreSQL have some useful array functions, which could be supported by jOOQ:

These include:

**Standard SQL**

- [x] `CARDINALITY(array)`
  - H2: ~`ARRAY_LENGTH()`~ Starting from 201: `CARDINALITY(array)`
  - HSQLDB: `CARDINALITY(array)`
  - PostgreSQL: `CARDINALITY(array)`
- [x] `ARRAY_GET(array, index)`
  - H2: ~`ARRAY_GET(array, index)`~ Starting from 201: `array[index]`
  - HSQLDB: `CASE WHEN CARDINALITY(array) >= index THEN array[index] END`
  - PostgreSQL: `array[index]`

**Vendor specific**

- [ ] `ARRAY_CAT(x, y)` (where x and y can be of type `T` or `T[]`)
  - H2: ~`ARRAY_CAT(x, y)` or `ARRAY_APPEND(x, y)`~ Starting from 201: `x || y`
  - PostgreSQL: `x || y`
- [ ] `ARRAY_CONTAINS(array, value)`
  - H2 `ARRAY_CONTAINS(array, value)`
  - PostgreSQL: `array @> array[value]`

More functions might be added to the list. Further tasks:

- [ ] Deprecate existing `PostgresDSL` methods (i.e. "pull them up")
- [x] Add parser support for these functions
- [ ] Add a new documentation section for these functions

----
See:
- http://h2database.com/html/functions.html#array_contains
- https://www.postgresql.org/docs/current/functions-array.html
- #10155

**Comment by katzyn** [comment]
`ARRAY_GET()` exists in H2 only for compatibility with its old versions, standard `[]` should be used instead.

In the next version of H2 (201) `ARRAY_CAT()` an `ARRAY_APPEND()` will be deprecated in favor of `||` and `ARRAY_LENGTH()` will be deprecated in favor of `CARDINALITY()`.

**Comment by lukaseder** [comment]
Great to know, thanks! We'll implement things accordingly, supporting these features only starting from H2 201 then.

**Comment by katzyn** [comment]
`[]` is supported since 1.4.198, so you can use it right now.

`||` with arrays is supported since 1.4.200, perhaps you can use it too.

`CARDINALITY()` will be supported only by the next version.

**Comment by lukaseder** [comment]
I'll wait until 201 to prevent too many moving targets. By the time jOOQ 3.14 will be released, 201 might be ready...

**Comment by katzyn** [comment]
You will be also required to change data type generations for 201, `ARRAY` is not a valid data type in H2 any more, only `INT ARRAY`, `BOOLEAN ARRAY[2]` etc. are.

**Comment by lukaseder** [comment]
Thanks for the heads up

**Comment by katzyn** [comment]
All these methods will continue to work in the next version, but I guess you can simplify your code by usage of standard grammar in all databases that support it instead of branches with different legacy vendor-specific constructions.

`array[index]` is a part of the Standard too, see `<array element reference>`.

**Comment by lukaseder** [comment]
To be continued in jOOQ 3.16: https://github.com/jOOQ/jOOQ/issues/11981
