### ISSUE TITLE
Wrong Javadoc: There are also DSLContext.fetchSingle() methods that return null

### ISSUE THREAD

**Issue by jazdw** [jOOQ/jOOQ#10172]
### Expected behavior and actual behavior:
The Javadoc for `org.jooq.ResultQuery.fetchSingle(int, Class<? extends T>)` says 
> `@return The resulting value. This is never <code>null</code>.`

However I am getting a null result from the following query:
`create.select(DSL.max(COL)).from(TABLE).fetchSingle(0, Integer.class);`
where TABLE has 0 records. Internally the query returns a record but then the value in the column is null. If this is the intended behavior then the Javadoc should be updated.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

- Create an empty table with one column
- Run above query

### Versions:

- jOOQ: 3.13.2
- Java: OpenJDK 11
- Database (include vendor): MySQL 5.7
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): 8.0.19

**Comment by lukaseder** [comment]
Thanks for your report.

The intention here is that `fetchSingle()` will never produce a `null` record, but of course, the individual values of a record can still be `null`. You don't even need a `null` producing aggregate function, you could also write:

```java
create.select(inline(null)).fetchSingle(0, Integer.class);
```

So, this is a documentation bug.

**Comment by lukaseder** [comment]
... which of course begs the question if these methods are really needed. They were added for consistency reasons, but in these cases, they are no different from their `fetchOne` counterparts. I tend to think that we'll keep things as they are for consistency reasons, for now.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.14.0. Backport scheduled for 3.13.3 (#10173) and 3.12.5 (#10174)

**Comment by jazdw** [comment]
Thanks Lucas, I figured this was the case 👍
