### ISSUE TITLE
Boolean field emulation should be NOT NULL aware

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10179]
Some expressions can never be `NULL`, for example:

- [x] The result of various `IS` predicates, such as
  - [x] `IS [ NOT ] NULL`
  - [x] `IS [ NOT ] JSON`
  - [x] `IS [ NOT ] DOCUMENT`
  - [x] `IS [ NOT ] DISTINCT FROM`
- [x] `EXISTS (...)`
- [x] `UNIQUE (...)`
- [x] `AND`, `OR`, `NOT` on expressions that are themselves never `NULL` (e.g. `NOT(x IS NULL)` or `a IS NULL AND b IS NULL`)
- [x] `TRUE` (`trueCondition()`)
- [x] `FALSE` (`falseCondition()`)
- [x] `noCondition()`

Some expressions that appear to be `NOT NULL` can be `NULL` e.g. in the error case:

- `JSON_EXISTS`
- `XMLEXISTS`

There are probably others. In #3206, we've introduced an improvement to `DSL.field(Condition)`, which correctly implements three valued logic, leading to the following emulation e.g. in Oracle:

```sql
-- PostgreSQL
select a is not distinct from b from t

-- Oracle
select case
  when exists (
    select a x
    from dual
    intersect
    select b x
    from dual
  ) then 1
  when not(exists (
    select a x
    from dual
    intersect
    select b x
    from dual
  )) then 0
  else null
end
from t
```

A better emulation would be the same one that we get when we place the `Condition` in the `WHERE` clause, where it does not have to be wrapped by `DSL.field(Condition)`:

```sql
select case
  when exists (
    select a x
    from dual
    intersect
    select b x
    from dual
  ) then 1
  else 0
end
from t
```

On a side note, this particular predicate could also be emulated with `DECODE` in Oracle: #7997

**Comment by lukaseder** [comment]
It may be tempting to think that in the presence of `NOT NULL` meta information, e.g. on generated columns, we could conclude the same thing for e.g.

```sql
SELECT a = b -- Both "a" and "b" are NOT NULL
FROM t
```

But it's not so simple. What if we did:

```sql
SELECT u.a = u.b
FROM t
LEFT JOIN u ON ...
```

Now, while `u.a` and `u.b` are `NOT NULL` in their table definition, they might *become* `NULL` because of the `LEFT JOIN`, and suddenly, the boolean expression is nullable again. If we wanted to prevent handling `NULL` in cases where we *could* prove that the expression is `NOT NULL`, we'd have to introspect quite a bit of the query, which seems excessive at this point. Users can easily write their own `CASE` expressions explicitly.

**Comment by lukaseder** [comment]
We can do even better. Currently, I've added a marker interface to those conditions that are *never* `NULL`, but there are e.g. `CombinedCondition` or `NotCondition` that can be known to be *never* `NULL` if all its children are *never* `NULL`, e.g.

```sql
NOT (x IS NULL)
a IS NULL AND b IS NOT NULL
```

**Comment by katzyn** [comment]
`<boolean test>` (`a IS [ NOT ] { TRUE | FALSE | UNKNOWN }`) is also null-safe.

**Comment by lukaseder** [comment]
Yes, but we don't support that predicate (yet). I have actually never run into a case where I would have needed it.

**Comment by katzyn** [comment]
@lukaseder
In H2, `IS [ NOT ] JSON …` returns `UNKNOWN` if object is SQL `NULL`. It can be a bug of H2, but I can't find in ISO/IEC TR 19075-6, First edition 2017-03, Part SQL Notation 6: SQL support for JavaScript Object (JSON) anything about the required result in this situation.

**Comment by lukaseder** [comment]
You're right. The same is true for `IS [ NOT ] DOCUMENT`. Too bad

**Comment by lukaseder** [comment]
An oversight will be fixed now: https://github.com/jOOQ/jOOQ/issues/13952
