### ISSUE TITLE
Parse a few known syntaxes and throw an exception about them not being supported

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10171]
We currently support parsing only a limited amount of PL/SQL and other procedural logic or statements. It would be great if the parser could parse a few additional syntaxes, or at least recognise them, and throw an explicit exception about them not being supported yet, including a link to either this ticket here, or an explicit ticket that requests the feature. This way, we can collect votes from users both of the programmatic parser from the library, and the website: https://www.jooq.org/translate, to get some telemetry

These syntaxes include (This list will be enhanced as we discover more such syntaxes):

**Procedural logic** (see also #8450)

- [x] `TYPE` declarations in PL/SQL
- [x] ~Associative arrays and their assignments, and other operations on them~ (might be difficult to recognise)
- [x] Local functions and procedures

**Statements**

- [x] `CALL`
- [x] `COMMIT`
- [x] `CONNECT`
- [x] `CREATE`, `ALTER`, `DROP`
  - [x] `DATABASE` (see #3272)
  - [x] `EXTENSION`
  - [x] `FUNCTION` (see #9190)
  - [x] `PACKAGE` (see #9190)
  - [x] `PROCEDURE` (see #9190)
  - [x] `ROLE` (see #10167)
  - [x] `SYNONYM` (see #9574)
  - [x] `TABLESPACE`
  - [x] `TRIGGER` (see #6956)
  - [x] `USER` (see #10167)
- [x] `LOAD`
- [x] `REPLACE`
- [x] `ROLLBACK`
- [x] `SAVEPOINT`
- [x] `UPSERT`

**Comment by wisnesky** [comment]
I vote for UPSERT

**Comment by lukaseder** [comment]
Thanks for your comment, @wisnesky. I'm assuming you vote for supporting to parse some `UPSERT` syntax? Which dialect? What parsing (or other) use-case are you interested in?

**Comment by wisnesky** [comment]
Correct, translation of UPSERT from SAP to Snowflake is most immediately on my mind.  But also support for LAST_DAY function would be helpful too (GitHub request #11680).

**Comment by lukaseder** [comment]
Thanks for your feedback. I've created a new issue for HANA `UPSERT`: https://github.com/jOOQ/jOOQ/issues/16467

Please note that you can add support for `LAST_DAY()` already now to the parser, using the `ParseListener` SPI:
https://www.jooq.org/doc/latest/manual/sql-building/sql-parser/sql-parser-listener/
