### ISSUE TITLE
Remove CONNECT BY support from OSS Edition

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10187]
With `CUBRID` having been deprecated in 3.13 (#9403), `CONNECT BY` is no longer supported by any dialect in the jOOQ Open Source Edition, only by Informix and Oracle.

We should remove the API and the implementation from the jOOQ Open Source Edition, which will also reduce the API surface and bytecode size.

Related syntax include:

- `CONNECT BY`
- `START WITH`
- `ORDER SIBLINGS BY`
- `LEVEL`
- `CONNECT_BY_ROOT`
- `CONNECT_BY_ISCYCLE`
- `CONNECT_BY_ISLEAF`
- `SYS_CONNECT_BY_PATH`
- `PRIOR`
- `ROWNUM` (not `CONNECT BY` specific, but also only supported by Oracle and CUBRID))

**Comment by katzyn** [comment]
H2 also historically has `ROWNUM` expression:
https://h2database.com/html/functions.html#rownum
(Parentheses are actually optional.)

**Comment by lukaseder** [comment]
That column is already so obscure in Oracle, I don't really want to support that anymore, at all. Given that Oracle 12c introduced `OFFSET .. FETCH`, I think it has gone out of fashion even in Oracle.
