### ISSUE TITLE
Add native support for DECODE where it is supported

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10180]
Some dialects also support Oracle's `DECODE` function, including:

- [x] Db2:
https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0052622.html?pos=2
- [x] H2: 
http://h2database.com/html/functions.html#decode

More dialects might be added.

We currently emulate it using `CASE` expressions, when we should generate a native implementation

**Comment by katzyn** [comment]
BTW, current H2 (from the sources) also replaces `DECODE` with `CASE` internally, like many other non-standard things with standard alternatives, and H2 generates more optimal expression for it. Simple case is used instead of searched one, and distinct predicate is used only when necessary.
```SQL
-- source
SELECT DECODE(A + B, C, 1, 3, 2, 3)
FROM (VALUES (0, 1, 1), (1, 1, 1), (1, 2, 1)) T(A, B, C);
-- H2:
SELECT CASE (A + B)
    WHEN IS NOT DISTINCT FROM C THEN 1
    WHEN 3 THEN 2
    ELSE 3 END
FROM (VALUES (0, 1, 1), (1, 1, 1), (1, 2, 1)) T(A, B, C);
-- jOOQ
SELECT CASE
    WHEN (A + B) IS NOT DISTINCT FROM C THEN 1
    WHEN (A + B) IS NOT DISTINCT FROM 3 THEN 2
    ELSE 3 END
FROM (VALUES (0, 1, 1), (1, 1, 1), (1, 2, 1)) AS T(A, B, C);
```

**Comment by lukaseder** [comment]
Thanks for the hint, @katzyn. That's a very good idea. We'll keep this in mind when we implement support for this syntax: https://github.com/jOOQ/jOOQ/issues/3223
