### ISSUE TITLE
GeneratorWriter should auto-indent generated code

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10196]
After the `ScalaGenerator`, we now also have a `KotlinGenerator` (#6248). The three code generation styles are subtly different. For example, the `Tables.java` class will produce a set of top level / package functions in Kotlin, which means they're not indented, whereas they were in Java and Scala.

The current hard wiring of indentations does not scale well for such cases. We'll introduce `GeneratorWriter.indent()` (in addition to the existing `GeneratorWriter.tab()`), which sets the indentation level for all generated lines of code. `tab()` only affects the current line.

Also, instead of managing this explicitly all the time, we can auto-detect when to increase / decrease the indentation in almost all cases.

- Indent decrease: When a line starts with `}`, `]`, or `)`
- Indent increases: When a line ends with `{`, `[`, or `(`
- Tab increases: When a line starts with `if`, `else`, `for`, `while` and does not end with `{`, `[`, or `(` (this can be done several times)

The last case might not always work. It's still possible to specify `indent()` and `tab()` manually in such cases.

**There is little risk of regressions for the out of the box experience. If users override the default `JavaGenerator` logic, however, they might get wrong indentations in their own generated code.**

**Comment by lukaseder** [comment]
Thanks for your message, @mwashburn2. You probably have a bug in `DBModelGenerator`, where you didn't correctly indent your code, or have mismatching opening/closing brackets.

I'm happy to help with specifics but I'd have to see your generator code.

**Comment by mwashburn2** [comment]
Sorry I should of been more clear, while this link was helpful to understand what to fix, it would be helpful if this exception included the file name to track down what is angering the generator. 

For others that find their way here, for me 3 cases were confusing the generator, all of which just required breaking the brackets out into different lines. 

`catch (Exception bla) {`

`try {`

`public void someSuperSimpleMethod() { return "bla; }`

**Comment by lukaseder** [comment]
Ah yes, I agree. Will improve the error message right away:

- https://github.com/jOOQ/jOOQ/issues/17236
