### ISSUE TITLE
Why is there no connection to the remote database at all ?

### ISSUE THREAD

**Issue by Chance2017** [jOOQ/jOOQ#10200]
### Your question:

Before asking your question, please check out the FAQ too: https://www.jooq.org/faq

### Versions:

- jOOQ: 3.13.2
- Java:8
- Database (include vendor):Ignite(H2)
- OS: Win10
- JDBC Driver (include name if inofficial driver): org.apache.igntie.IgniteJdbcThinDriver

Today, I want use jooq to generate java code for access ignite database by connecting to the remote database. But I find that it is not connected to the remote database at all. So the correct schema cannot be queried. Who can tell me the reason ???

**Comment by lukaseder** [comment]
Thank you very much for your message.

We are very happy to help you with your problem if you are willing to provide some additional information related to what you did, and what errors / log messages you were seeing.

Do note that we do not officially support Apache Ignite, though, so chances are, this just simply doesn't work.

**Comment by lukaseder** [comment]
I'm assuming that the problem was resolved, or given that we do not support Apache Ignite, the problem cannot be resolved.

Please feel free to reopen this should you find any additional issues.
