### ISSUE TITLE
Missing some generated indexes starting with 3.13?

### ISSUE THREAD

**Issue by plum117** [jOOQ/jOOQ#10225]
### Expected behavior and actual behavior:

When generating java classes from mysql database using jooq 3.13 we expect to have the same number of indexes generated then when we use jooq 3.12.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
- Generate java class using jooq 3.12
- See that 16 indexes are included

> Thank you for using jOOQ 3.12.4
> Tables fetched           : 9 (7 included, 2 excluded)
> Indexes fetched          : 19 (19 included, 0 excluded)

- Generate java class using jooq 3.12
- See that only 2 indexes are included

> Thank you for using jOOQ 3.13.1
> Tables fetched           : 9 (7 included, 2 excluded)
> Indexes fetched          : 2 (2 included, 0 excluded)

### Versions:

- jOOQ: 3.13.1 and above

- Java: AdopJdk 14
> openjdk 14.0.1 2020-04-14
> OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
> OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)
> 

- Database (include vendor): mysql docker (mysql:5.7)

- OS: Ubuntu 20.04 LTS
- JDBC Driver (include name if inofficial driver):
```
  <groupId>mysql</groupId>
  <artifactId>mysql-connector-java</artifactId>
  <version>8.0.20</version>
```

**Comment by lukaseder** [comment]
Thanks for your report. jOOQ 3.13 implemented a new `<includeSystemIndexes>` flag. Does this explain it? https://github.com/jOOQ/jOOQ/issues/9601

**Comment by lukaseder** [comment]
Well, `<includeSystemIndexes/>` is the only explanation I have. Feel free to reopen this issue if you think there's a bug somewhere.

**Comment by plum117** [comment]
Sorry did not see your reply, will test and see. 

@lukaseder could you point me to the documentation where this `includeSystemIndexes` is explained? This [page](https://www.jooq.org/doc/3.13/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-include-object-types/) seems to be the more appropriate since I also see `includeIndexes` but I see nothing on `includeSystemIndexes`

**Comment by lukaseder** [comment]
The documentation is missing indeed (outside of the XSD: https://www.jooq.org/xsd/jooq-codegen-3.13.0.xsd)

**Comment by lukaseder** [comment]
Will add documentation via a separate issue: https://github.com/jOOQ/jOOQ/issues/10246
