### ISSUE TITLE
DayToSecond#getTotalSeconds() in jOOQ grammar

### ISSUE THREAD

**Issue by borcsokj** [jOOQ/jOOQ#10233]
### Your question:

I have an Interval value calculated by DATEDIFF(end, start)/TIMESTAMPDIFF(end, start). Can I get numeric value of the interval in a given temporal unit in jOOQ grammar as described in https://www.jooq.org/javadoc/3.13.x/org.jooq/org/jooq/types/DayToSecond.html#getTotalSeconds()? Is there any other syntax in grammar to get difference of the dates/timestamps in a given unit?

### Versions:

- jOOQ: 3.13.1
- Java: 1.8
- Database (include vendor): PostgreSQL 10.1
- OS: Ubuntu 19.10
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.12

**Comment by robertcsakany** [comment]
Hi @lukaseder,

I think it's related to https://github.com/jOOQ/jOOQ/issues/10217 . 
I know we are using JOOQ in the edge case and I can accept that handling it in general way in different SQL dialect sometimes almost impossible.
Please give us some insight is there any plan it will be fixed, or we have to make some workaround in our side to make our own timestamp handling which depends on the dialect. We can accept the answer it will be not fixed soon, but we have to know how to handle this issue in our side. We purchased professional licences, please help us.

**Comment by lukaseder** [comment]
Thank you very much for your ping, @robertcsakany. The was a national holiday here in Switzerland. I will look into this issue as soon as possible today to see if there's something in jOOQ out of the box that could help you in this area. I think we don't have this yet, but it would definitely be very useful (e.g. we support `EXTRACT()` or `SECONDS()`, but that corresponds to the seconds part, e.g. `53` in `01:53`, not the total seconds, e.g. `113` in `01:53`)

The workaround, as always, if jOOQ can't do something vendor specific, is to resort to using plain SQL templating: https://www.jooq.org/doc/3.13/manual/sql-building/plain-sql-templating

You can also create a `CustomField` that helps abstract over SQL dialects: https://www.jooq.org/doc/3.13/manual/sql-building/queryparts/custom-queryparts/

**Comment by robertcsakany** [comment]
Thank you for your response! I've understand your workaround,  is there any way to combine the solution with the ParsingConnection?

**Comment by lukaseder** [comment]
@robertcsakany Could you make an example of how you're using `ParsingConnection`?

**Comment by lukaseder** [comment]
Following up on my comment from yesterday, I don't think we have such an out of the box feature in jOOQ. The feature you were looking for was this: https://github.com/jOOQ/jOOQ/issues/7900 (like in SQL Server). HANA has useful functions, like these:

- `YEARS_BETWEEN`: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.02/en-US/7c0d2c161ea34def86de3f5eadd6a0af.html
- `MONTHS_BETWEEN`: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.02/en-US/9f9eb73468b04bbc9d6014d22d2bfb90.html
- `DAYS_BETWEEN`: https://help.sap.com/viewer/4fe29514fd584807ac9f2a04f6754767/2.0.02/en-US/20e16ca5751910148da4fc7ec69bae03.html

Definitely worth reprioritising #7900 for jOOQ 3.14.

**Comment by lukaseder** [comment]
I think I understand what you're looking for. You want to use the parser to have a vendor agnostic way to calculate things like this temporal difference (#7900), without using the jOOQ API directly, but only the parser.

I'm afraid, I cannot think of a way to do this short of patching jOOQ, currently. We will eventually support plain SQL fragments in the parser: https://github.com/jOOQ/jOOQ/issues/9447, but they do not solve the problem of implementing some vendor agnostic syntax. What you'd need for this is a parser plugin that allows for enhancing the parser in arbitrary ways. I've created a separate feature request for this: https://github.com/jOOQ/jOOQ/issues/10243, but I cannot guarantee its implementation, see discussion there.

However, in this particular case, #7900 is definitely a very desireable feature. I'll look into implementing it right away for 3.14.

**Comment by lukaseder** [comment]
One additional workaround I can think of is to use `Settings.parseUnknownFunctions` to support parsing an arbitrary function expression (e.g. `X_DIFF(a, b)`), and then using a `VisitListener` to transform it to something vendor specific of your choice.

Does that help?

**Comment by lukaseder** [comment]
@borcsokj @robertcsakany What SQL dialects, other than PostgreSQL, will you need this for?

**Comment by blackbelt-oss** [comment]
@lukaseder Thank you very much for your helpful responses, It helps for us. We will check the parseUnknownFuctions you mentioned, I think it can work for us that our semantic is expressed in a custom function in the JOOQ level. (We only just would like to avoid the using of SQL dialect specific codes on our statement builder). In the first release of our product we would like to support officially PostgreSQL (also YugabyteDB), HSQLDB, SQL Server, OracleDB and CockroachDB. But in 2021 we would like to extend support almost all of the JOOQ supported DB's (we have to make some extensive testing) - that was the main reason we using JOOQ Parsing connection as our SQL Dialect abstraction layer.

**Comment by lukaseder** [comment]
Thanks for the feedback, @blackbelt-oss. I'll see that at least those dialects will have support for `DATEDIFF(part, d1, d2)` and an additional `TIMESTAMPDIFF(part, d1, d2)` in jOOQ 3.14. An implementation is already under way, and you can soon (starting tomorrow) test it in the latest 3.14.0-SNAPSHOT distributions: https://www.jooq.org/download/versions

I've noticed that there are two types of behaviours in these functions:

- H2, HSQLDB, SQL Server style behaviour where the result describes a 0-based number of "date part" periods that overlap with the argument dates, e.g. `DATEDIFF(YEAR, '2000-03-01', '2002-01-01') = 2`
- HANA, PostgreSQL style behaviour where the result describes a truncated, 0-based number of complete "date part" periods that are included, e.g. `YEARS_BETWEEN('2000-03-01', '2002-01-01') = 1`

Both behaviours are justified. We'll support both.

**Comment by robertcsakany** [comment]
@lukaseder Thanks for this very fast fix. We will check it in the next week.
