### ISSUE TITLE
Fetching select t1.*, (select count(*) from t2 where t2.t1_id = t1.id) from t1 into POJO fails during mapping

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#10232]
### Expected behavior and actual behavior:

The following statement
```java
jooq.select(RACE.asterisk(),
            jooq.selectCount().from(PARTICIPANT).where(PARTICIPANT.RACE_ID.eq(RACE.ID))
                    .asField<Int>("participants_count"))
.from(RACE)
.where(RACE.ORGANIZER_USER_ID.eq(organizerUserId))
.fetchInto(output)
```

should fetch all columns of the race table PLUS the new additional `participants_count` column into the POJO `output` which contains fields matching all these columns.

Unfortunately this fails as behind the scenes the `fetchInto` method first tries to fetch into a `RaceRecord` and then maps everything onto the constructor of `output`, failing at runtime due to the missing value for the `participants_count` field.

### Versions:

- jOOQ: 3.13.2
- Java: 14
- Database (include vendor): H2 1.4.200

**Comment by lukaseder** [comment]
Thanks a lot for your report. I've tried reproducing this, unsuccessfully:

```java

        List<Language> r2 = create()
            .select(TLanguage().asterisk(), inline("x").as("extra"))
            .from(TLanguage())
            .orderBy(TLanguage_ID())
            .fetchInto(Language.class);

        assertEquals(4, r2.size());
        assertEquals(LANGUAGE_IDS, seq(r2).map(l -> l.id).toList());
        assertEquals(LANGUAGE_CDS, seq(r2).map(l -> l.cd).toList());
        assertEquals(nCopies(4, "x"), seq(r2).map(l -> l.extra).toList());
```

The above test passes as expected. Are you sure you passed a POJO type `output`, and not the `RACE` table reference to `fetchInto()` (in case of which the behaviour would be the one you've observed)?

If possible, an MCVE would be very helpful to help reproduce this: https://github.com/jOOQ/jOOQ-mcve

**Comment by axelfontaine** [comment]
Thanks for looking into this. I am 100% positive I passed in the POJO. Unfortunately, I lost the exact code and DB structure that let to this (refactored away). I'll just close this for now and reopen should I once again face the issue.
