### ISSUE TITLE
Make LocalDateTime the default type for Oracle DATE columns before removing dateAsTimestamp

### ISSUE THREAD

**Issue by mnisius** [jOOQ/jOOQ#10241]
### Use case:
The oracle DATE Datatype stores date and time. However by default jOOQ generates LocalDate fields for columns with that type. So it is not possible to set a time. That is why I think LocalDateTime would be a better fit as a default type. 

### Possible solution you'd like to see:
Change the default type from LocalDate to LocaleDateTime if dateAsTimestamp option is removed or some different approach to configure this in a parent pom.xml. 

### Possible workarounds:

Set dateAsTimestamp to true. 
But this is deprecated and will be removed for jooq 4.x.x

### Versions:

- jOOQ: > 3.13
- Java: 8 & 11
- Database (include vendor): Oracle 18
- OS: Windows & Linux
- JDBC Driver (include name if inofficial driver): ojdbc8

**Comment by lukaseder** [comment]
Thank you very much for your request.

The reason why we want to remove this flag is because it is redundant with the forced type feature (and predates it): https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types

You should be able to just force all `DATE` columns to behave like `TIMESTAMP` as follows:

```xml
<forcedType>
  <name>TIMESTAMP</name>
  <includeTypes>DATE</includeTypes>
</forcedType>
```

Does this help?

**Comment by mnisius** [comment]
Yes this will work as well. Thanks for the tip. 
But just out of curiosity why keep LocalDate as the default? Is it because the type works different on other vendors?

**Comment by lukaseder** [comment]
It is always difficult to change something like this, as existing customers might run into situations where they would not detect subtle regressions. Imagine comparing a `DATE` column to the current timestamp. Right now, they would compare it to e.g. `2020-06-03`, when all of a sudden, they would compare it to `2020-06-03 18:04:00`.

The rationale is that despite Oracle's `DATE` type not following the SQL standard, a lot of systems may use `DATE` columns as if they were of the standard SQL `DATE` type. And, yes indeed, if someone works with Oracle *and* PostgreSQL, for example, then they will use Oracle `DATE` in places where they also use PostgreSQL `DATE`.

This may or may not be seen as the right choice for the default behaviour in jOOQ, but it has been this way for many years, and changing it now is probably not worth it.
