### ISSUE TITLE
JPADatabase always generates H2 dialect

### ISSUE THREAD

**Issue by cemremengu** [jOOQ/jOOQ#10260]
As it says on the tin, is there a way to generate for Oracle? Whatever I do, I always get:

```
[INFO] Database parameters
[INFO] ----------------------------------------------------------
[INFO]   dialect                : H2 // I am trying to make this oracle
[INFO]   URL                    :
[INFO]   target dir             : target\generated-sources\jooq
[INFO]   target package         : org.jooq.generated
[INFO]   includes               : [.*]
[INFO]   excludes               : []
[INFO]   includeExcludeColumns  : false
```

Here is my config:

```
<plugin>
	<groupId>org.jooq.trial</groupId>
	<artifactId>jooq-codegen-maven</artifactId>
	<version>${jooq.version}</version>
	<executions>
		<execution>
			<goals>
				<goal>generate</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<generator>
			<database>
				<name>org.jooq.meta.extensions.jpa.JPADatabase</name>
				<properties>
					<property>
						<key>packages</key>
						<value>com.myproject.entity</value>
					</property>
					<property>
						<key>useAttributeConverters</key>
						<value>true</value>
					</property>
					<property>
						<key>unqualifiedSchema</key>
						<value>none</value>
					</property>
				</properties>
			</database>
		</generator>
	</configuration>
</plugin>
```

### Versions:
- jOOQ: 3.13.2
- Java: 11
- Database (include vendor): Oracle
- OS: Windows

**Comment by lukaseder** [comment]
Thanks for the clarifications.

Our generated code is mostly vendor agnostic, just like Hibernate's / JPA's entities. There are some limitations:

- Usage of vendor specific data types may be limited (e.g. if you're using some GIS types)
- You might not get the optimal data type definition in generated code, which can cause problems when trying to re-create the DDL scripts from jOOQ generated code. This is unlikely when you're using the JPADatabase

Both of these limitations should not affect your querying.
