### ISSUE TITLE
Tutorial documentation - Incorrectly suggests installing XAMPP to get MySQL

### ISSUE THREAD

**Issue by pluresideas** [jOOQ/jOOQ#10289]
### Expected behavior and actual behavior:

The tutorial should not suggest installing XAMPP to get MySQL because since XAMPP 5.5.30 and 5.6.14, XAMPP ships MariaDB instead of MySQL:

https://www.apachefriends.org/faq_osx.html
https://www.apachefriends.org/faq_windows.html

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

- Follow the tutorial at https://www.jooq.org/learn/
- Got to the **Step 1: Preparation**: https://www.jooq.org/doc/3.13/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step1/ 
- Notice on the bottom of the page:
`
If you don't have a MySQL instance up and running yet, get XAMPP now! XAMPP is a simple installation bundle for Apache, MySQL, PHP and Perl
`

### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for pointing this out. Hah, that suggestion is as old as jOOQ itself. Of course it shouldn't be there anymore.
