### ISSUE TITLE
Kotlin support: generate immutable interfaces containing properties instead of getters

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#10290]
### Use case:

jOOQ can generate immutable Java interfaces containing only getters. Unfortunately Kotlin data classes cannot implement those as the compiler complains that the getters and properties resolve to the same methods on the JVM.

### Possible solution you'd like to see:

Having the KotlinGenerator emit interfaces containing abstract properties instead of getters would allow Kotlin data classes to cleanly implement these interfaces (with the necessary `override val` declarations). This in turn would allow custom Kotlin POJOs to gain some compile-time safety as renaming a database column would then cause a compile error.

**Comment by lukaseder** [comment]
Thanks. This is already addressed via https://github.com/jOOQ/jOOQ/issues/6248

**Comment by lukaseder** [comment]
E.g. some examples from the integration tests:

```kotlin
// Interface
interface IImmutableInterfaces : Serializable {
    val i: Int?
}

// "Pojo"
class ImmutableInterfaces(
      override var i: Int? = null
): IImmutableInterfaces {
...
}

// Record
class ImmutableInterfacesRecord() : TableRecordImpl<ImmutableInterfacesRecord>(ImmutableInterfaces.IMMUTABLE_INTERFACES), IImmutableInterfaces {

    override var i: Int?
        get() = get(0) as Int?
        set(value) = set(0, value)
}
```
```
