### ISSUE TITLE
Add support for CITEXT and VARCHAR_IGNORECASE types in parser

### ISSUE THREAD

**Issue by fluxroot** [jOOQ/jOOQ#10291]
### Expected behavior and actual behavior:
Generating code with DDLDatabase from an H2 SQL script in which the H2 type VARCHAR_IGNORECASE is being used, gives the following error:
```
Caused by: org.jooq.impl.ParserException: Token ')' expected: [513:41] ...NOT NULL,
    value             VARCHAR_IGNORECASE[*](200) NOT NULL,
```

I guess the SQL Parser doesn't know about this H2 specific type. Shouldn't it least ignore it and maybe use VARCHAR instead?

### Versions:

- jOOQ: 3.13.2
- Java: 11
- Database (include vendor): H2
- OS: MacOS
- JDBC Driver (include name if inofficial driver): n/a

**Comment by lukaseder** [comment]
Thanks for your report. It would be interesting to support vendor specific case insensitive types (see also PostgreSQL's `citext`: https://github.com/jOOQ/jOOQ/issues/5934).

For the time being, I agree that the `DDLDatabase` (and the parser in general) could ignore the case insensitivity and pretend the type is a `VARCHAR` (or `TEXT` in case of PostgreSQL)

**Comment by fluxroot** [comment]
Woot! Thanks for the workaround.
