### ISSUE TITLE
Javadoc of SQLDataType.INTERVAL is incorrect

### ISSUE THREAD

**Issue by katzyn** [jOOQ/jOOQ#10311]
https://github.com/jOOQ/jOOQ/blob/ca3fcb8570706266dbe749d03bbddf5a1707393d/jOOQ/src/main/java/org/jooq/impl/SQLDataType.java#L410-L413

Actually there is no `INTERVAL YEAR TO SECOND` data type in the SQL Standard. Raw `INTERVAL` data type exists in PostgreSQL, but even in this DBMS in can't be declared as `INTERVAL YEAR TO SECOND`, so it should be documented as vendor-specific `INTERVAL` data type instead.

**Comment by lukaseder** [comment]
Thanks a lot. Fixed in 3.14.0. Backport scheduled for 3.13.3 (#10314)
