### ISSUE TITLE
Missing class "javax/persistence/PersistenceException" error with JPADatabase generator in latest Jooq versions

### ISSUE THREAD

**Issue by MetroMarv** [jOOQ/jOOQ#10327]
### Expected behavior and actual behavior:

Expected to generate classes according to my @Entity annotated classes.

Actually I get the following error, when running `mvn clean package`:

> [ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.13.2:generate (default) on project jooq: Execution default of goal org.jooq:jooq-codegen-maven:3.13.2:generate failed: A required class was missing while executing org.jooq:jooq-codegen-maven:3.13.2:generate: javax/persistence/PersistenceException

### Steps to reproduce the problem:

Create a multi module Maven project with the modules "model" and "jooq".

The model module contains a single class defined as follows:

    @Entity
    @Table(name = "author")
    public class Author {
    
      @Column(name="name")
      private String name;
    }

The jooq module just contains a pom file with the following generation configuration:

    <plugin>
        <groupId>org.jooq</groupId>
        <artifactId>jooq-codegen-maven</artifactId>
        <version>${jooq.version}</version>

        <executions>
            <execution>
                <goals>
                    <goal>generate</goal>
                </goals>
            </execution>
        </executions>

        <dependencies>
            <dependency>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-meta-extensions</artifactId>
                <version>${jooq.version}</version>
            </dependency>
        </dependencies>

        <configuration>
            <generator>
                <database>
                    <name>org.jooq.meta.extensions.jpa.JPADatabase</name>
                    <properties>
                        <property>
                            <key>packages</key>
                            <value>org.example.model</value>
                        </property>
                    </properties>
                    <includes>.*</includes>
                </database>
                <target>
                    <packageName>org.example.db</packageName>
                </target>
            </generator>
        </configuration>
    </plugin>

MVCE can be found here: https://github.com/MetroMarv/jooq-missing-class-persistenceexception

### Versions:

- jOOQ:  3.13.2/3.12.4
- Java: 11 and 8
- Database (include vendor): not relevant
- OS: Linux Kernel 5.6.16
- JDBC Driver (include name if inofficial driver): not relevant

### Details

The error occurs with Java 8 and Java 11. I tried to downgrade the Jooq version. Version 3.12.4 fails with the same error but version 3.11.12 works fine.

Full error log:

    [ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.13.2:generate (default) on project jooq: Execution default of goal org.jooq:jooq-codegen-maven:3.13.2:generate failed: A required class was missing while executing org.jooq:jooq-codegen-maven:3.13.2:generate: javax/persistence/PersistenceException
    [ERROR] -----------------------------------------------------
    [ERROR] realm =    plugin>org.jooq:jooq-codegen-maven:3.13.2
    [ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
    [ERROR] urls[0] = file:/home/example/.m2/repository/org/jooq/jooq-codegen-maven/3.13.2/jooq-codegen-maven-3.13.2.jar
    [ERROR] urls[1] = file:/home/example/.m2/repository/org/jooq/jooq-meta-extensions/3.13.2/jooq-meta-extensions-3.13.2.jar
    [ERROR] urls[2] = file:/home/example/.m2/repository/org/jooq/jooq-meta/3.13.2/jooq-meta-3.13.2.jar
    [ERROR] urls[3] = file:/home/example/.m2/repository/com/h2database/h2/1.4.200/h2-1.4.200.jar
    [ERROR] urls[4] = file:/home/example/.m2/repository/org/hibernate/hibernate-core/5.4.9.Final/hibernate-core-5.4.9.Final.jar
    [ERROR] urls[5] = file:/home/example/.m2/repository/org/jboss/logging/jboss-logging/3.3.2.Final/jboss-logging-3.3.2.Final.jar
    [ERROR] urls[6] = file:/home/example/.m2/repository/org/javassist/javassist/3.24.0-GA/javassist-3.24.0-GA.jar
    [ERROR] urls[7] = file:/home/example/.m2/repository/net/bytebuddy/byte-buddy/1.10.2/byte-buddy-1.10.2.jar
    [ERROR] urls[8] = file:/home/example/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar
    [ERROR] urls[9] = file:/home/example/.m2/repository/org/jboss/spec/javax/transaction/jboss-transaction-api_1.2_spec/1.1.1.Final/jboss-transaction-api_1.2_spec-1.1.1.Final.jar
    [ERROR] urls[10] = file:/home/example/.m2/repository/org/jboss/jandex/2.1.1.Final/jandex-2.1.1.Final.jar
    [ERROR] urls[11] = file:/home/example/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar
    [ERROR] urls[12] = file:/home/example/.m2/repository/javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.jar
    [ERROR] urls[13] = file:/home/example/.m2/repository/org/dom4j/dom4j/2.1.1/dom4j-2.1.1.jar
    [ERROR] urls[14] = file:/home/example/.m2/repository/org/hibernate/common/hibernate-commons-annotations/5.1.0.Final/hibernate-commons-annotations-5.1.0.Final.jar
    [ERROR] urls[15] = file:/home/example/.m2/repository/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar
    [ERROR] urls[16] = file:/home/example/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.1/jaxb-runtime-2.3.1.jar
    [ERROR] urls[17] = file:/home/example/.m2/repository/org/glassfish/jaxb/txw2/2.3.1/txw2-2.3.1.jar
    [ERROR] urls[18] = file:/home/example/.m2/repository/com/sun/istack/istack-commons-runtime/3.0.7/istack-commons-runtime-3.0.7.jar
    [ERROR] urls[19] = file:/home/example/.m2/repository/org/jvnet/staxex/stax-ex/1.8/stax-ex-1.8.jar
    [ERROR] urls[20] = file:/home/example/.m2/repository/com/sun/xml/fastinfoset/FastInfoset/1.2.15/FastInfoset-1.2.15.jar
    [ERROR] urls[21] = file:/home/example/.m2/repository/org/springframework/spring-context/5.1.9.RELEASE/spring-context-5.1.9.RELEASE.jar
    [ERROR] urls[22] = file:/home/example/.m2/repository/org/springframework/spring-aop/5.1.9.RELEASE/spring-aop-5.1.9.RELEASE.jar
    [ERROR] urls[23] = file:/home/example/.m2/repository/org/springframework/spring-beans/5.1.9.RELEASE/spring-beans-5.1.9.RELEASE.jar
    [ERROR] urls[24] = file:/home/example/.m2/repository/org/springframework/spring-core/5.1.9.RELEASE/spring-core-5.1.9.RELEASE.jar
    [ERROR] urls[25] = file:/home/example/.m2/repository/org/springframework/spring-jcl/5.1.9.RELEASE/spring-jcl-5.1.9.RELEASE.jar
    [ERROR] urls[26] = file:/home/example/.m2/repository/org/springframework/spring-expression/5.1.9.RELEASE/spring-expression-5.1.9.RELEASE.jar
    [ERROR] urls[27] = file:/home/example/.m2/repository/org/liquibase/liquibase-core/3.8.0/liquibase-core-3.8.0.jar
    [ERROR] urls[28] = file:/home/example/.m2/repository/org/yaml/snakeyaml/1.23/snakeyaml-1.23.jar
    [ERROR] urls[29] = file:/home/example/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar
    [ERROR] urls[30] = file:/home/example/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar
    [ERROR] urls[31] = file:/home/example/.m2/repository/org/jooq/jooq-codegen/3.13.2/jooq-codegen-3.13.2.jar
    [ERROR] urls[32] = file:/home/example/.m2/repository/org/jooq/jooq/3.13.2/jooq-3.13.2.jar
    [ERROR] urls[33] = file:/home/example/.m2/repository/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar
    [ERROR] urls[34] = file:/home/example/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
    [ERROR] urls[35] = file:/home/example/.m2/repository/org/codehaus/plexus/plexus-utils/3.2.1/plexus-utils-3.2.1.jar
    [ERROR] urls[36] = file:/home/example/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.jar
    [ERROR] urls[37] = file:/home/example/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
    [ERROR] urls[38] = file:/home/example/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
    [ERROR] urls[39] = file:/home/example/.m2/repository/org/apache/maven/maven-builder-support/3.6.2/maven-builder-support-3.6.2.jar
    [ERROR] urls[40] = file:/home/example/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.4.1/maven-resolver-util-1.4.1.jar
    [ERROR] urls[41] = file:/home/example/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.2.1/maven-shared-utils-3.2.1.jar
    [ERROR] urls[42] = file:/home/example/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar
    [ERROR] urls[43] = file:/home/example/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.3/org.eclipse.sisu.inject-0.3.3.jar
    [ERROR] urls[44] = file:/home/example/.m2/repository/com/google/inject/guice/4.2.1/guice-4.2.1-no_aop.jar
    [ERROR] urls[45] = file:/home/example/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
    [ERROR] urls[46] = file:/home/example/.m2/repository/com/google/guava/guava/25.1-android/guava-25.1-android.jar
    [ERROR] urls[47] = file:/home/example/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
    [ERROR] urls[48] = file:/home/example/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar
    [ERROR] urls[49] = file:/home/example/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar
    [ERROR] urls[50] = file:/home/example/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
    [ERROR] urls[51] = file:/home/example/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
    [ERROR] urls[52] = file:/home/example/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.0.0/plexus-component-annotations-2.0.0.jar
    [ERROR] urls[53] = file:/home/example/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
    [ERROR] Number of foreign imports: 1
    [ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
    [ERROR] 
    [ERROR] -----------------------------------------------------
    [ERROR] : javax.persistence.PersistenceException
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <args> -rf :jooq

**Comment by MetroMarv** [comment]
I could fix the problem by adding the persistence-api dependency to the plugin config in the pom.xml file:

<plugin>
        <groupId>org.jooq</groupId>
        <artifactId>jooq-codegen-maven</artifactId>
        <version>${jooq.version}</version>

        <executions>
            <execution>
                <goals>
                    <goal>generate</goal>
                </goals>
            </execution>
        </executions>

        <dependencies>
            <dependency>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-meta-extensions</artifactId>
                <version>${jooq.version}</version>
            </dependency>
            
            <dependency>
                <groupId>javax.persistence</groupId>
                <artifactId>javax.persistence-api</artifactId>
                <version>2.2</version>
            </dependency>
        </dependencies>

        <configuration>
            <generator>
                <database>
                    <name>org.jooq.meta.extensions.jpa.JPADatabase</name>
                    <properties>
                        <property>
                            <key>packages</key>
                            <value>org.example.model</value>
                        </property>
                    </properties>
                    <includes>.*</includes>
                </database>
                <target>
                    <packageName>org.example.db</packageName>
                </target>
            </generator>
        </configuration>
    </plugin>

**Comment by lukaseder** [comment]
Thanks a lot for your report and your MCVE. I can reproduce this. Will investigate right away.

**Comment by lukaseder** [comment]
Interesting, the `jooq-codegen-maven` plugin tampers with class loaders to get access to the module dependencies, for convenience, so you don't actually have to provide the `jooq-meta-extensions` dependency again to the plugin. See: https://github.com/jOOQ/jOOQ/issues/2886. This works:

```xml
<plugin>
    <groupId>org.jooq</groupId>
    <artifactId>jooq-codegen-maven</artifactId>
    <version>${jooq.version}</version>

    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>

    <configuration>
        <generator>
            <database>
                <name>org.jooq.meta.extensions.jpa.JPADatabase</name>
                <properties>
                    <property>
                        <key>packages</key>
                        <value>org.example.model</value>
                    </property>
                </properties>
                <includes>.*</includes>
            </database>
            <target>
                <packageName>org.example.db</packageName>
            </target>
        </generator>
    </configuration>
</plugin>
```

I'll check what may have caused the change of behaviour between 3.11 and 3.12

**Comment by lukaseder** [comment]
The difference is in the hibernate dependency. We've upgraded it in the meantime. Here's the output of `mvn dependency:tree` when using jOOQ 3.11:

```
11:24:17,355 [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ jooq ---
11:24:17,373 [INFO] org.example:jooq:jar:1.0-SNAPSHOT
11:24:17,376 [INFO] +- org.example:model:jar:1.0-SNAPSHOT:compile
11:24:17,379 [INFO] |  \- javax.persistence:javax.persistence-api:jar:2.2:compile
11:24:17,382 [INFO] +- org.jooq:jooq:jar:3.11.12:compile
11:24:17,384 [INFO] |  \- javax.xml.bind:jaxb-api:jar:2.2.12:compile
11:24:17,388 [INFO] +- org.jooq:jooq-meta:jar:3.11.12:compile
11:24:17,390 [INFO] +- org.jooq:jooq-codegen:jar:3.11.12:compile
11:24:17,392 [INFO] \- org.jooq:jooq-meta-extensions:jar:3.11.12:compile
11:24:17,395 [INFO]    +- com.h2database:h2:jar:1.4.197:compile
11:24:17,398 [INFO]    +- org.hibernate:hibernate-core:jar:5.2.13.Final:compile
11:24:17,401 [INFO]    |  +- org.jboss.logging:jboss-logging:jar:3.3.1.Final:compile
11:24:17,408 [INFO]    |  +- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile
11:24:17,412 [INFO]    |  +- org.javassist:javassist:jar:3.22.0-GA:compile
11:24:17,417 [INFO]    |  +- antlr:antlr:jar:2.7.7:compile
11:24:17,419 [INFO]    |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.0.1.Final:compile
11:24:17,423 [INFO]    |  +- org.jboss:jandex:jar:2.0.3.Final:compile
11:24:17,426 [INFO]    |  +- com.fasterxml:classmate:jar:1.3.0:compile
11:24:17,429 [INFO]    |  +- dom4j:dom4j:jar:1.6.1:compile
11:24:17,431 [INFO]    |  \- org.hibernate.common:hibernate-commons-annotations:jar:5.0.1.Final:compile
11:24:17,435 [INFO]    \- org.springframework:spring-context:jar:4.1.5.RELEASE:compile
11:24:17,438 [INFO]       +- org.springframework:spring-aop:jar:4.1.5.RELEASE:compile
11:24:17,442 [INFO]       |  \- aopalliance:aopalliance:jar:1.0:compile
11:24:17,445 [INFO]       +- org.springframework:spring-beans:jar:4.1.5.RELEASE:compile
11:24:17,448 [INFO]       +- org.springframework:spring-core:jar:4.1.5.RELEASE:compile
11:24:17,452 [INFO]       |  \- commons-logging:commons-logging:jar:1.2:compile
11:24:17,455 [INFO]       \- org.springframework:spring-expression:jar:4.1.5.RELEASE:compile
```

And when using jOOQ 3.14:

```
11:24:59,181 [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ jooq ---
11:24:59,200 [INFO] org.example:jooq:jar:1.0-SNAPSHOT
11:24:59,204 [INFO] +- org.example:model:jar:1.0-SNAPSHOT:compile
11:24:59,206 [INFO] |  \- javax.persistence:javax.persistence-api:jar:2.2:compile
11:24:59,209 [INFO] +- org.jooq:jooq:jar:3.13.2:compile
11:24:59,211 [INFO] |  +- org.reactivestreams:reactive-streams:jar:1.0.2:compile
11:24:59,214 [INFO] |  \- javax.xml.bind:jaxb-api:jar:2.3.1:compile
11:24:59,217 [INFO] |     \- javax.activation:javax.activation-api:jar:1.2.0:compile
11:24:59,220 [INFO] +- org.jooq:jooq-meta:jar:3.13.2:compile
11:24:59,222 [INFO] +- org.jooq:jooq-codegen:jar:3.13.2:compile
11:24:59,225 [INFO] \- org.jooq:jooq-meta-extensions:jar:3.13.2:compile
11:24:59,228 [INFO]    +- com.h2database:h2:jar:1.4.200:compile
11:24:59,234 [INFO]    +- org.hibernate:hibernate-core:jar:5.4.9.Final:compile
11:24:59,237 [INFO]    |  +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
11:24:59,241 [INFO]    |  +- org.javassist:javassist:jar:3.24.0-GA:compile
11:24:59,244 [INFO]    |  +- net.bytebuddy:byte-buddy:jar:1.10.2:compile
11:24:59,247 [INFO]    |  +- antlr:antlr:jar:2.7.7:compile
11:24:59,249 [INFO]    |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.1.1.Final:compile
11:24:59,253 [INFO]    |  +- org.jboss:jandex:jar:2.1.1.Final:compile
11:24:59,256 [INFO]    |  +- com.fasterxml:classmate:jar:1.5.1:compile
11:24:59,259 [INFO]    |  +- org.dom4j:dom4j:jar:2.1.1:compile
11:24:59,261 [INFO]    |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.0.Final:compile
11:24:59,265 [INFO]    |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.1:compile
11:24:59,268 [INFO]    |     +- org.glassfish.jaxb:txw2:jar:2.3.1:compile
11:24:59,271 [INFO]    |     +- com.sun.istack:istack-commons-runtime:jar:3.0.7:compile
11:24:59,275 [INFO]    |     +- org.jvnet.staxex:stax-ex:jar:1.8:compile
11:24:59,277 [INFO]    |     \- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.15:compile
11:24:59,281 [INFO]    +- org.springframework:spring-context:jar:5.1.9.RELEASE:compile
11:24:59,285 [INFO]    |  +- org.springframework:spring-aop:jar:5.1.9.RELEASE:compile
11:24:59,288 [INFO]    |  +- org.springframework:spring-beans:jar:5.1.9.RELEASE:compile
11:24:59,292 [INFO]    |  +- org.springframework:spring-core:jar:5.1.9.RELEASE:compile
11:24:59,295 [INFO]    |  |  \- org.springframework:spring-jcl:jar:5.1.9.RELEASE:compile
11:24:59,299 [INFO]    |  \- org.springframework:spring-expression:jar:5.1.9.RELEASE:compile
11:24:59,303 [INFO]    \- org.liquibase:liquibase-core:jar:3.8.0:compile
11:24:59,305 [INFO]       +- org.yaml:snakeyaml:jar:1.23:compile
11:24:59,308 [INFO]       +- org.slf4j:slf4j-api:jar:1.7.25:compile
11:24:59,311 [INFO]       \- ch.qos.logback:logback-classic:jar:1.2.3:compile
11:24:59,322 [INFO]          \- ch.qos.logback:logback-core:jar:1.2.3:compile
```

Hibernate used to bring its own JPA API dependency that used a different groupId and artifactId:

```
11:24:17,408 [INFO]    |  +- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile
```

Now that both jOOQ and Hibernate use the same one, it seems that something is missing from the transitive dependencies.

I'm not sure how this could be fixed on the jOOQ side. The workaround is to not add any dependencies to the plugin, but to the project only.

**Comment by MetroMarv** [comment]
Thanks for the fast response and analysis. Looks like it's not a problem with jOOQ, but the class loader. However I'm not an export on dynamic class loading ;).

I was about to say, that you should remove the snippet from your docs which made me add this dependency for the plugin. But I couldn't find that snippet anymore. Did you already remove it or where did I get that snippet from? :D

**Comment by lukaseder** [comment]
> I was about to say, that you should remove the snippet from your docs which made me add this dependency for the plugin. But I couldn't find that snippet anymore. Did you already remove it or where did I get that snippet from? :D

There are various places in the manual that document the `jooq-meta-extensions` dependency, but none of them suggest putting it in the plugin (or *not* in the plugin for that matter).

I want to keep this issue open and possibly fix this problem, should it become clear how to fix it, rather than documenting this "limitation". I'd say the limitation is now sufficiently documented via this issue.

**Comment by lukaseder** [comment]
This problem didn't arise again in the meantime, and I still can't think of anything we could fix here. Closing this as "answered". Future visitors might still be helpful, or comment on any additional related issues they may find.

**Comment by shihan-iqbal** [comment]
im getting the same issue with =  org.jooq:jooq-codegen-maven:3.14.16

forceIntegerTypesOnZeroScaleDecimals><logSlowQueriesAfterSeconds>5</logSlowQueriesAfterSeconds><logSlowResultsAfterSeconds>5</logSlowResultsAfterSeconds><properties><property><key>packages</key><value>com.ec.core.model</value></property><property><key>use-attribute-converters</key><value>true</value></property></properties><schemata><schema><inputSchema></inputSchema><outputSchema>beta</outputSchema><outputSchemaToDefault>false</outputSchemaToDefault></schema></schemata></database><target><packageName>com.ec.core.jooq</packageName><directory>src/main/java</directory><encoding>UTF-8</encoding><clean>true</clean></target></generator><basedir>/home/shihan/Xiam/repo/easy-claim</basedir>
[INFO] No <inputCatalog/> was provided. Generating ALL available catalogs instead.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.14.16:generate (default-cli) on project easy-claim: Execution default-cli of goal org.jooq:jooq-codegen-maven:3.14.16:generate failed: A required class was missing while executing org.jooq:jooq-codegen-maven:3.14.16:generate: javax/persistence/PersistenceException
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.jooq:jooq-codegen-maven:3.14.16
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/shihan/.m2/repository/org/jooq/jooq-codegen-maven/3.14.16/jooq-codegen-maven-3.14.16.jar
[ERROR] urls[1] = file:/home/shihan/.m2/repository/org/jooq/jooq-meta/3.14.16/jooq-meta-3.14.16.jar
[ERROR] urls[2] = file:/home/shihan/.m2/repository/org/jooq/jooq-meta-extensions-hibernate/3.14.16/jooq-meta-extensions-hibernate-3.14.16.jar
[ERROR] urls[3] = file:/home/shihan/.m2/repository/org/jooq/jooq-meta-extensions/3.14.16/jooq-meta-extensions-3.14.16.jar
[ERROR] urls[4] = file:/home/shihan/.m2/repository/com/h2database/h2/1.4.200/h2-1.4.200.jar
[ERROR] urls[5] = file:/home/shihan/.m2/repository/org/hibernate/hibernate-core/5.4.31.Final/hibernate-core-5.4.31.Final.jar
[ERROR] urls[6] = file:/home/shihan/.m2/repository/org/jboss/logging/jboss-logging/3.4.1.Final/jboss-logging-3.4.1.Final.jar
[ERROR] urls[7] = file:/home/shihan/.m2/repository/org/javassist/javassist/3.27.0-GA/javassist-3.27.0-GA.jar
[ERROR] urls[8] = file:/home/shihan/.m2/repository/net/bytebuddy/byte-buddy/1.10.21/byte-buddy-1.10.21.jar
[ERROR] urls[9] = file:/home/shihan/.m2/repository/antlr/antlr/2.7.7/antlr-2.7.7.jar
[ERROR] urls[10] = file:/home/shihan/.m2/repository/org/jboss/spec/javax/transaction/jboss-transaction-api_1.2_spec/1.1.1.Final/jboss-transaction-api_1.2_spec-1.1.1.Final.jar
[ERROR] urls[11] = file:/home/shihan/.m2/repository/org/jboss/jandex/2.2.3.Final/jandex-2.2.3.Final.jar
[ERROR] urls[12] = file:/home/shihan/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar
[ERROR] urls[13] = file:/home/shihan/.m2/repository/javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.jar
[ERROR] urls[14] = file:/home/shihan/.m2/repository/org/dom4j/dom4j/2.1.3/dom4j-2.1.3.jar
[ERROR] urls[15] = file:/home/shihan/.m2/repository/org/hibernate/common/hibernate-commons-annotations/5.1.2.Final/hibernate-commons-annotations-5.1.2.Final.jar
[ERROR] urls[16] = file:/home/shihan/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.1/jaxb-runtime-2.3.1.jar
[ERROR] urls[17] = file:/home/shihan/.m2/repository/org/glassfish/jaxb/txw2/2.3.1/txw2-2.3.1.jar
[ERROR] urls[18] = file:/home/shihan/.m2/repository/com/sun/istack/istack-commons-runtime/3.0.7/istack-commons-runtime-3.0.7.jar
[ERROR] urls[19] = file:/home/shihan/.m2/repository/org/jvnet/staxex/stax-ex/1.8/stax-ex-1.8.jar
[ERROR] urls[20] = file:/home/shihan/.m2/repository/com/sun/xml/fastinfoset/FastInfoset/1.2.15/FastInfoset-1.2.15.jar
[ERROR] urls[21] = file:/home/shihan/.m2/repository/org/springframework/spring-context/5.3.7/spring-context-5.3.7.jar
[ERROR] urls[22] = file:/home/shihan/.m2/repository/org/springframework/spring-aop/5.3.7/spring-aop-5.3.7.jar
[ERROR] urls[23] = file:/home/shihan/.m2/repository/org/springframework/spring-beans/5.3.7/spring-beans-5.3.7.jar
[ERROR] urls[24] = file:/home/shihan/.m2/repository/org/springframework/spring-core/5.3.7/spring-core-5.3.7.jar
[ERROR] urls[25] = file:/home/shihan/.m2/repository/org/springframework/spring-jcl/5.3.7/spring-jcl-5.3.7.jar
[ERROR] urls[26] = file:/home/shihan/.m2/repository/org/springframework/spring-expression/5.3.7/spring-expression-5.3.7.jar
[ERROR] urls[27] = file:/home/shihan/.m2/repository/org/jooq/jooq/3.14.16/jooq-3.14.16.jar
[ERROR] urls[28] = file:/home/shihan/.m2/repository/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar
[ERROR] urls[29] = file:/home/shihan/.m2/repository/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar
[ERROR] urls[30] = file:/home/shihan/.m2/repository/org/jooq/jooq-codegen/3.14.16/jooq-codegen-3.14.16.jar
[ERROR] urls[31] = file:/home/shihan/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[32] = file:/home/shihan/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[33] = file:/home/shihan/.m2/repository/org/codehaus/plexus/plexus-utils/3.2.1/plexus-utils-3.2.1.jar
[ERROR] urls[34] = file:/home/shihan/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.25/plexus-interpolation-1.25.jar
[ERROR] urls[35] = file:/home/shihan/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.4/plexus-sec-dispatcher-1.4.jar
[ERROR] urls[36] = file:/home/shihan/.m2/repository/org/apache/maven/maven-builder-support/3.8.2/maven-builder-support-3.8.2.jar
[ERROR] urls[37] = file:/home/shihan/.m2/repository/org/apache/maven/resolver/maven-resolver-util/1.6.3/maven-resolver-util-1.6.3.jar
[ERROR] urls[38] = file:/home/shihan/.m2/repository/org/apache/maven/shared/maven-shared-utils/3.3.4/maven-shared-utils-3.3.4.jar
[ERROR] urls[39] = file:/home/shihan/.m2/repository/commons-io/commons-io/2.6/commons-io-2.6.jar
[ERROR] urls[40] = file:/home/shihan/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.4/org.eclipse.sisu.inject-0.3.4.jar
[ERROR] urls[41] = file:/home/shihan/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2-no_aop.jar
[ERROR] urls[42] = file:/home/shihan/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[43] = file:/home/shihan/.m2/repository/com/google/guava/guava/25.1-android/guava-25.1-android.jar
[ERROR] urls[44] = file:/home/shihan/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
[ERROR] urls[45] = file:/home/shihan/.m2/repository/org/checkerframework/checker-compat-qual/2.0.0/checker-compat-qual-2.0.0.jar
[ERROR] urls[46] = file:/home/shihan/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar
[ERROR] urls[47] = file:/home/shihan/.m2/repository/com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar
[ERROR] urls[48] = file:/home/shihan/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar
[ERROR] urls[49] = file:/home/shihan/.m2/repository/org/codehaus/plexus/plexus-component-annotations/2.1.0/plexus-component-annotations-2.1.0.jar
[ERROR] urls[50] = file:/home/shihan/.m2/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : javax.persistence.PersistenceException
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jooq:jooq-codegen-maven:3.14.16:generate (default-cli) on project easy-claim: Execution default-cli of goal org.jooq:jooq-codegen-maven:3.14.16:generate failed: A required class was missing while executing org.jooq:jooq-codegen-maven:3.14.16:generate: javax/persistence/PersistenceException
-----------------------------------------------------
realm =    plugin>org.jooq:jooq-codegen-maven:3.14.16
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/home/shihan/.m2/repository/org/jooq/jooq-codegen-maven/3.14.16/jooq-codegen-maven-3.14.16.jar
urls[1] = file:/home/shihan/.m

**Comment by lukaseder** [comment]
Thanks for your message, @shihan-iqbal. This question here already has an answer. Did the answer help you? If not, what have you checked already? How can it be reproduced? Just from your comment, it won't be possible to help you any further.
