### ISSUE TITLE
Jooq timestamp precision issue

### ISSUE THREAD

**Issue by Nhoutain** [jOOQ/jOOQ#10329]
Hi, I have some trouble with date time in JOOQ.

### Expected behavior and actual behavior:
Giving a date filter like 
```
LocalDateTime value = LocalDate.now().atTime(LocalTime.MAX); // 2020-06-29 23:59:59.999999999
Timestamp dbValue = Timestamp.valueOf(value);
field.greaterOrEquals(dbValue);
```

I have as JOOQ debug log:
```
column <= timestamp '2020-06-29 23:59:59.999999999'
```

but the final query executed in SQL is: 
```
column <= timestamp '2020-06-30 00:00:00.000000000'
```

---

I suspect a kind of "rounding" somewhere when JOOQ convert the date to the database because if I use the millisecond precision, it work.
```
LocalDateTime value = LocalDate.now().atTime(23, 59, 59, 999999000); // 2020-06-29 23:59:59.999999000
Timestamp dbValue = Timestamp.valueOf(value);
field.greaterOrEquals(dbValue);
```

Is there any good reason that I can't imagine that need a round instead of a truncate?

Thanks in advance for the support!

Note: As you can't see, I found a workaround, so nothing it critical on my side :) 

### Versions:

- jOOQ: 3.12.3
- Java: 8
- Database (include vendor): PostgreSQL
- OS: linux
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your report. I?m not aware of such a rounding issue. How can it be reproduced, exactly? This works as expected:

```java
LocalDateTime v1 = LocalDate.now().atTime(LocalTime.MAX);
Timestamp v2 = Timestamp.valueOf(v1);
System.out.println(v2);
System.out.println(field("x", SQLDataType.TIMESTAMP).le(v2));
System.out.println(DSL.using(POSTGRES).renderInlined(field("x", SQLDataType.TIMESTAMP).le(v2)));
```

Printing:

```
2020-07-02 23:59:59.999999999
x <= timestamp '2020-07-02 23:59:59.999999999'
x <= timestamp '2020-07-02 23:59:59.999999999'
```

**Comment by lukaseder** [comment]
I've tried jOOQ 3.14.0, 3.13.3, 3.12.5 for reproduction, without success

**Comment by katzyn** [comment]
@lukaseder
That's how PostgreSQL works by itself.
```SQL
create table test(id int, t timestamp);
insert into test values
    (1, timestamp '2020-06-29 23:59:59.999999'),
    (2, timestamp '2020-06-30 00:00:00');
select * from test where t <= timestamp '2020-06-29 23:59:59.999999999';
>  id |             t              
> ----+----------------------------
>   1 | 2020-06-29 23:59:59.999999
>   2 | 2020-06-30 00:00:00
```
PostgreSQL supports only up to 6 fractional digits, all additional digits are rounded (the SQL Standard allows implementation-defined rounding or truncation for datetime values, so it isn't a bug). `timestamp '2020-06-29 23:59:59.999999999'` is actually a `timestamp '2020-06-30 00:00:00'` in PostgreSQL.

**Comment by lukaseder** [comment]
Thanks for the pointer, @katzyn - good to know.

While it is understandable that when users use `LocalTime.MAX`, the precision seems irrelevant, jOOQ shouldn't tamper with these values, I think. A less error prone approach would be to query with `<` rather than `<=`, if precision is unknown. So:

```sql
-- This
select * from test where t < timestamp '2020-06-30 00:00:00';

-- Rather than this:
select * from test where t <= timestamp '2020-06-29 23:59:59.999999999';
```
