### ISSUE TITLE
Add support for JSON / JSONB types in H2

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10321]
#7242 introduced support for `JSON` / `JSONB` data types in MySQL, Oracle, PostgreSQL, SQL Server (the most popular RDBMS).

This issue tracks adding support for H2:
https://h2database.com/html/datatypes.html#json_type

This is a prerequisite for support of `JSON` types in the H2 backed `DDLDatabase`: https://github.com/jOOQ/jOOQ/issues/9337

----
See also https://github.com/jOOQ/jOOQ/issues/8948

**Comment by katzyn** [comment]
You can set JSON values by using `PreparedStatement.setBytes()` in H2 without any workarounds. `? FORMAT JSON` is only needed for `PreparedStatement.setString()`.

**Comment by lukaseder** [comment]
Interesting, thanks. Why was that distinction made? Also, what encoding would we choose to extract the `byte[]` from a JSON string?

**Comment by lukaseder** [comment]
We'll support a `CharsetProvider` SPI in the future: https://github.com/jOOQ/jOOQ/issues/8949. By default, we would be taking the system default charset...

**Comment by katzyn** [comment]
Conversion from character string to JSON produces a JSON string value. Conversions from boolean to JSON produces JSON boolean value. Conversion from numeric to JSON produces JSON numeric value. Conversion from null to JSON produces JSON value. There are no other scalar types in JSON. So there is no native conversion from `byte[]` to JSON and we were free to implement such conversion in any way (or not implement it at all). JSON text was chosen as the most useful variant.

H2 accepts UTF-8 and big-endian and little-endian versions of UTF-16 and UTF-32.
H2 returns JSON values in UTF-8 as required by [RFC 8259](https://tools.ietf.org/html/rfc8259):
> 8.1.  Character Encoding
>
>   JSON text exchanged between systems that are not part of a closed
>   ecosystem MUST be encoded using UTF-8 [RFC3629].

Also it's better to generate JSON literals for H2 when you want to inline some known value, it will be parsed in more efficient way than character (or binary) string literal with format clause or cast specification:
https://h2database.com/html/grammar.html#json

**Comment by lukaseder** [comment]
Thank you very much for the explanations. For now, I think I'd like to stick with the string version, which works better for the general use-cases of jOOQ, including e.g. the https://www.jooq.org/translate feature. Otherwise, we'd get binary data all over the place, which I think most people using inline JSON values in SQL would find annoying. The binding can still be changed in the future, in case there's a compelling reason to do so.
