### ISSUE TITLE
Make JSON::data, JSONB::data, and XML::data NotNull

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10343]
These two statements do the same thing in PostgreSQL:

```java
insertInto(t, i, a, b).values(1, json(null), jsonb(null)).execute();
insertInto(t, i, a, b).values(2, json("null"), jsonb("null")).execute();
```

Both produce a `'null'::json` or a `'null'::jsonb` value, not a `null` value, which can be produced like this:

```java
insertInto(t, i, a, b).values(3, null, null).execute();
```

However, the `JSON::data` or `JSONB::data` value is currently `@Nullable`, which has been confusing already, in the past, see https://github.com/jOOQ/jOOQ/issues/9607 and https://github.com/jOOQ/jOOQ/issues/9612.

We should make the `::data` methods `@NotNull` and convert a `null` constructor argument to the `"null"` string.

This is a backwards incompatible change. While unlikely, some users may have come to depend on the distinction for a reason I cannot think of.

**Comment by kamilgregorczyk** [comment]
@lukaseder is it intended that after this change calling `record.getValue(TABLE.FIELD)` returns `"null"` and not a `null` on JSONB fields?

**Comment by lukaseder** [comment]
@kamilgregorczyk Yes, as explained in the issue, there's a distinction between SQL `null` and JSON `null`:

```sql
select null::jsonb, 'null'::jsonb
```

I don't know if this applies to your particular query, because I don't see it, but I'm assuming that's what this is about.
