### ISSUE TITLE
Change JavaGenerator.printClassAnnotations() to (JavaWriter, Definition, Mode)

### ISSUE THREAD

**Issue by jklingsporn** [jOOQ/jOOQ#10355]
### Use case:

I want to add an annotation to my generated POJOs. The right place to do so I guess is by overwriting `printClassAnnotations`-method in `JavaGenerator`. However this method is invoked by many other methods too (e.g. `generateDao`). We should also consider changing the second parameter from `SchemaDefinition` to `Definition` as it provides more information for generators and the schema definition can be derived from it too (e.g. when generating a POJO from a table pass the `TableDefinition`). 

### Possible solution you'd like to see:

Change method signature to `printClassAnnotations(JavaWriter,Definition,GeneratorStrategy.Mode)`

### Possible workarounds:

Copy code from `generatePojo0` to my Generator and overwrite `generatePojo` with the contents (and obviously change the line where the annotation should be generated).

### Versions:

- jOOQ: 3.12.2

**Comment by lukaseder** [comment]
Thanks for your suggestions. I agree that we should use `Definition` to help implementors decide whether they should do anything at all.

What's the point of a new `GeneratorStrategy.MODE` constant?

**Comment by jklingsporn** [comment]
I was refering to `org.jooq.codegen.GeneratorStrategy.Mode`-enum.

**Comment by lukaseder** [comment]
I see, my bad. That makes sense

**Comment by lukaseder** [comment]
I guess we should have a new `Mode` eventually to distinguish between the various schema level convenience access objects, such as `Tables.java`, `Keys.java`, `Indexes.java`, because currently, they all get the same `SchemaDefinition` and `Mode.DEFAULT` arguments.

But that's another story. I'll wait until someone needs this.

**Comment by lukaseder** [comment]
The workaround right now is to reverse engineer the missing information from the call stack, I guess...?
