### ISSUE TITLE
[PostgreSQL] Add support for on conflict with predicates

### ISSUE THREAD

**Issue by eduardo-bueno-ifood** [jOOQ/jOOQ#10356]
As per the documentation: "_If an index_predicate is specified, it must, as a further requirement for inference, satisfy arbiter indexes._"
https://www.postgresql.org/docs/12/sql-insert.html#SQL-ON-CONFLICT

This means that if I have an index like this:
```
CREATE UNIQUE INDEX uniq_idx_company_personnel
  ON person(company_id, personnel_no) WHERE company_id > 0;
```
I must specify the WHERE condition in my on conflict clause, which is currently not supported by the API.

**Comment by lukaseder** [comment]
Thank you for your suggestion. This will ship in jOOQ 3.14: https://github.com/jOOQ/jOOQ/issues/6736
