### ISSUE TITLE
Mistake in the "FOR clause" documentation

### ISSUE THREAD

**Issue by mkurz** [jOOQ/jOOQ#10364]
Here: https://www.jooq.org/doc/3.14/manual-single-page/#for-clause

On the right: Instead of `actors`/`actor` shouldn't it be `books`/`book`?

![image](https://user-images.githubusercontent.com/644927/86761240-1c1b0d00-c046-11ea-94d5-f98ce799fdaa.png)

**Comment by lukaseder** [comment]
Yes, of course! Thanks a lot
