### ISSUE TITLE
Adding a join increases query time by 200ms

### ISSUE THREAD

**Issue by olivermt** [jOOQ/jOOQ#10367]
First off, thanks for all the small hints on twitter, we're now operational! :)

### Expected behavior and actual behavior:
Adding join should not increase by so much.
query.toString() and copy pasting to psql console executes against same db in 0.5ms.

Query that is fast (about 7ms spent inside Jooq):
```
// just a simple pool, I have put logging in place right after datasource aquiring
// and aquiring the datasource (prior to DSL.using) is sub-milliseconds
HikariCP
                .getDSLContext()
                .selectFrom(SAFARI_USER)
                .where(SAFARI_USER.ID.eq(id))
                .fetchOne()
```

Query that takes 200ms extra (takes 0.5ms if toString()'d and pasted in psql):
```
 HikariCP
                .getDSLContext()
                .select(SAFARI_USER.asterisk(), COMPANY.asterisk())
                .from(SAFARI_USER)
                .join(COMPANY)
                .on(SAFARI_USER.COMPANY_ID.eq(COMPANY.ID))
                .where(SAFARI_USER.USERNAME.eq(username))
                .fetchOne()
```

For brevitys sake, this is how you get a context:
```
fun getDSLContext() : DSLContext {
        val ds = dataSource() // Grabs a datasource from the hikari pool
        logger.debug("Aquired datasource")
        return DSL.using(ds,SQLDialect.POSTGRES)
    }
```
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
Proprietary database, if you really want a reproducement I can try to recreate against sample data.
I figure you might have profiling instructions for me that I can run for you?
### Versions:

- jOOQ: 3.12.4
- Java: 1.11
- Database (include vendor): postgresql 10.12
- OS: windows 10 (1903)
- JDBC Driver (include name if inofficial driver): org.postgresql 42.2.14

**Comment by olivermt** [comment]
I write this down as a heisenbug. 
Profiled it through visualvm and it stopped exhibiting the long extra ms..

Will reopen if I get the same issue again.

**Comment by lukaseder** [comment]
Thank you very much for your report.

I'm not aware of anything related to this particular syntax that would warrant for such excessive performance penalties in jOOQ itself. If measured in isolation, the extra effort could be attributed to additional classloading, or to caches in the database that weren't warm yet to execute the join?
