### ISSUE TITLE
SQL Server 2017 CU21 installation error

### ISSUE THREAD

**Issue by gabster12** [jOOQ/jOOQ#10366]
### Expected behavior and actual behavior:
SQL Server 2017 CU 21 apply patch from sql server 2017 CU20 fails with error: The operation failed because an index or statistics with name 'IX_EventMessageContext_EventMessageId' already exists on table 'internal.event_message_context'

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
Apply patch SQLServer2017-KB4557397-x64.exe over sql server 2017 Developer CU20 

### Versions:
Microsoft SQL Server 2017 (RTM-CU20) (KB4541283) - 14.0.3294.2 (X64)   Mar 13 2020 14:53:45   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

- jOOQ:
- Java:
- Database (include vendor): SQL Server 2017 CU20
- OS: Windows Server 2019 Standard 10.0
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report. May I ask you how this is related to jOOQ?

**Comment by gabster12** [comment]
Hi, it's not related to jOOQ. Sorry, i missed placed my comment.

**Comment by lukaseder** [comment]
No worries, thanks for the feedback!
