### ISSUE TITLE
H2 Support for returning primary key from inserts when using DSL

### ISSUE THREAD

**Issue by tkram01** [jOOQ/jOOQ#10396]
It looks like it is impossible to get the auto-increment key back from an insert.returning when using H2 and DSL instead of a generated table. In AbstractDMLQuery line 1189 it checks if table.getIdentity() is null. If you are not using a generated table and instead creating Table objects using DSL.table there is no way to have the Table object not return null for getIdentity().

**Comment by lukaseder** [comment]
Thank you very much for your report. Indeed, there's currently no convenient way to return identities in some dialects, without using the code generator. You can define your table as your own `TableImpl` subclass (using internal API), just like the code generator would do.

We'll address this issue soon, via #2943.

**Comment by lukaseder** [comment]
See also https://github.com/jOOQ/jOOQ/issues/10400, which has been implemented for jOOQ 3.14.
