### ISSUE TITLE
Gradle task in 3.13 stopped producing files (records, tables, ...)

### ISSUE THREAD

**Issue by hemju** [jOOQ/jOOQ#10427]
### Expected behavior and actual behavior:

JOOQ Generator worked without problems in 3.12, but with 3.13 no files are generated.

We are using a Gradle Task to generate our Records:

1. Gradle
```
task jooq() {
  doLast {
    java.nio.file.Path fileName = java.nio.file.Path.of("jooq_config.xml");
    org.jooq.codegen.GenerationTool.generate(java.nio.file.Files.readString(fileName));
  }
}
```

After upgrading to Spring Boot 2.3 (from 2.2), the generator stopped creating the files. Note: the output between 3.12 and 3.13 is the same. Further, log/debug statements don't indicate any error or warning. Creating the files through a Java main:

2. Java

```
public class JooqTest {

  public static void main(String[] args) throws Exception {
    Path fileName = Path.of("jooq_config.xml");
    GenerationTool.generate(Files.readString(fileName));
  }

}
```

works. The files are correctly created. The weird thing is that again 1. and 2. produce the same output. To summarize, everything between 3.12 and 3.13 looks the same, except that the files are not written (to the disk).

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

I am happy to provide the `build.gradle` and the `jooq-config.xml`, but if possible not here in the public thread.

### Versions:

- jOOQ: 3.13 (spring-boot-starter-jooq 2.3.1.RELEASE)
- Java: 13
- Database (include vendor): PostgreSQL
- OS: MacOS
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.14

**Comment by lukaseder** [comment]
Thanks for your report.

I'm not aware of any such show stopper regression in jOOQ itself, between 3.12 and 3.13, which would entirely prevent the generation of files. You seem to have upgraded a few things in one go, including Spring Boot. This means that the source of the problem might as well be outside of jOOQ?

I might be able to help, but I would need an MCVE of some form, as suggested by the linked template, to help me reproduce the case you're having.

**Comment by hemju** [comment]
@lukaseder I don't think it is a JOOQ problem. I had a second look at it, we have this in the config file:

```
    <target>
      <directory>src/main/java</directory>
      <packageName>com.lingohub.backend.db.jooq.models</packageName>
    </target>
```

It used to generate the files to

`WORKING_DIR/src/main/java/...`

and now the files are written to

`~/.gradle/...`

I don't know what caused the change. Thanks for looking into it though.

**Comment by hemju** [comment]
Hi Lukas,

I reopened the issue. I think it is related to https://github.com/jOOQ/jOOQ/issues/9727

What is the correct way to set the basedir in a Gradle build script?

**Comment by lukaseder** [comment]
@hemju, I think I'd really need to see a full example that shows what didn't work for you. For example, you're apparently not using the recommended 3rd party gradle plugin: https://github.com/etiennestuder/gradle-jooq-plugin, but rolled your own integration. There could be many things that went wrong in your own integration, I can't say what the "correct way to do X" is, without all the context.

I'll be happy to help, but I think I do need a way to reproduce your problems (e.g. via an MCVE), for that.

**Comment by hemju** [comment]
True, we don't use that plugin (I actually didn't know it is recommended). This is the way we solved it:

```
task jooq() {
  doLast {
    java.nio.file.Path fileName = java.nio.file.Path.of("jooq_config.xml");
    String config = java.nio.file.Files.readString(fileName)
    config = config.replace('${baseDir}', projectDir.toString())
    org.jooq.codegen.GenerationTool.generate(config);
  }
}
```

and

```
    <target>
      <directory>${baseDir}/src/main/java</directory>
    </target>
```

As mentioned, it is a regression (we also found the code) from 3.12 to 3.13, so maybe it is useful for someone else as well.

Btw. thanks for JooQ, we are big fans.
