### ISSUE TITLE
Use standard SQL for identity columns in H2

### ISSUE THREAD

**Issue by katzyn** [jOOQ/jOOQ#10426]
jOOQ produces MySQL-style `AUTO_INCREMENT` clause for identity columns in H2. It is usually good enough, but it can lead to loss of their optional clauses (when they will be really supported), for example Translate tool simply removes them:
```SQL
CREATE TABLE TEST(
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY(MINVALUE 10 MAXVALUE 100) PRIMARY KEY,
    V INT
);
-->
create table TEST (
  ID bigint not null auto_increment,
  V int null,
  primary key (ID)
)
```
jOOQ should use standard `GENERATED BY DEFAULT AS IDENTITY [(options)]` and `GENERATED ALWAYS AS IDENTITY [(options)]` clauses instead for H2 1.4.198 and later versions. In H2 201 `AUTO_INCREMENT` will be documented as compatibility-only. In 201 `GENERATED ALWAYS AS IDENTITY` columns can't be assigned by user code, in 1.4.200 and older versions they work like `GENERATED BY DEFAULT AS IDENTITY`.

H2 1.4.197 and older versions accept only some standard definitions, for example, `GENERATED BY DEFAULT AS IDENTITY(START WITH 10 INCREMENT BY 1)` works, but `GENERATED BY DEFAULT AS IDENTITY(MINVALUE 10 MAXVALUE 100)` doesn't, so, in general, optional clauses are not very usable in those old versions.

It looks like Translate tool ignores these optional clauses for any target dialect, without their real support this issue has a relatively low meaning, but I think jOOQ should not produce legacy clauses for recent releases of H2.

**Comment by lukaseder** [comment]
Thanks for your suggestion. We currently don't have a meta model for the various optional `IDENTITY` flags, although we support them in sequences. But we can definitely generate the option-less standard syntax for H2, instead.
