### ISSUE TITLE
What is the snapshots repository?

### ISSUE THREAD

**Issue by bjuretic** [jOOQ/jOOQ#10441]
How to get Jooq snapshot builds from Gradle, e.g. for 3.14 snapshots? I see snapshots are published on your website to download, but don't see reference to an actual maven repository for easy adding as dependency to Gradle.

**Comment by lukaseder** [comment]
Thank you very much for your message. We offer snapshot builds from our website to commercially licensed customers:
https://www.jooq.org/download/versions

We do not have a repository yet (see https://github.com/jOOQ/jOOQ/issues/9906), so there's only the ZIP download.

I hope this helps

**Comment by lukaseder** [comment]
With https://github.com/jOOQ/jOOQ/issues/9906 implemented, there are now snapshots available from here for paying customers:

https://repo.jooq.org/snapshots
