### ISSUE TITLE
PostgreSQL code generation is incorrect when two tables share check constraint name

### ISSUE THREAD

**Issue by oshai** [jOOQ/jOOQ#10444]
### Expected behavior and actual behavior:
should create
```
Internal.createCheck(
            this, DSL.name("enforce_srid_the_geom"), "((st_srid(the_geom) = 4326))", true),
```
but actual is
```
Internal.createCheck(
            this, DSL.name("enforce_srid_the_geom"), "((st_srid(the_geom) = '-1'::integer))", true),
```

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

The table definition has the value '-1'::integer as default of in_city_id:
```
CREATE TABLE test (
	id serial NOT NULL,
	...
	in_city_id int4 NOT NULL DEFAULT '-1'::integer,
	simplify_geom geometry NULL,
        ...
        CONSTRAINT enforce_srid_simplify_geom CHECK ((st_srid(simplify_geom) = 4326)),
        ...
)
```
### Versions:

- jOOQ: 3.13.3
- Java: 8
- Database (include vendor): postgresql
- OS: mac
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:9.4-1201-jdbc4
- gradle plugin: 4.2
- also use geometric extension: net.dmitry.jooq.postgis.spatial:jooq-postgis-spatial:1.0

BTW - I wanted to reproduce it with snapshot, but couldn't find how to get those artifacts other than building myself?

**Comment by lukaseder** [comment]
Thank you very much for your report.

The query we use to reverse engineer check constraint definitions can be seen here:

https://github.com/jOOQ/jOOQ/blob/61f9818/jOOQ-meta/src/main/java/org/jooq/meta/postgres/PostgresDatabase.java#L350-L392

I.e. we read `information_schema.check_constraint.check_clause`. This is what PostgreSQL reports here, so I'm not sure if we can do anything about it.

> BTW - I wanted to reproduce it with snapshot, but couldn't find how to get those artifacts other than building myself?

Snapshots are available to commercially licensed customers from our website here:
https://www.jooq.org/download/versions

Without a license, building them from github is an option, but this issue is probably independent of the jOOQ version. I'll try to confirm, soon.

**Comment by oshai** [comment]
Thanks! I tried to run the query mentioned [here in SO](https://dba.stackexchange.com/a/214877/213082) on the table, and it seems to produce valid result. If you can translate the jooq expression to an sql statement I can try to run it on my db as well.

**Comment by lukaseder** [comment]
> Thanks! I tried to run the query mentioned [here in SO](https://dba.stackexchange.com/a/214877/213082) on the table, and it seems to produce valid result.

Interesting, so there seems to be a bug in the `information_schema.check_constraint` view? Might be worth reporting to PostgreSQL. We can evaluate using the `pg_catalog`, instead. We have, several times, in the past, because of similar limitations of the `information_schema` views.

> If you can translate the jooq expression to an sql statement I can try to run it on my db as well.

If you want the exact query, you could set a breakpoint in `jOOQ-meta` and extract it from the debugger, or turn on debug logging in your code generation.

But I mean, in this case, there really isn't too much magic 😉

```sql
select * 
from information_schema.check_constraint
where table_name = 'test'
```

**Comment by oshai** [comment]
I probably miss something but:
```
select * from information_schema.check_constraint where table_name = 'test';
```
Returns the following error:
```
SQL Error [42P01]: ERROR: relation "information_schema.check_constraint" does not exist
  Position: 15
```

**Comment by lukaseder** [comment]
Yes, there was a typo. I've updated all my comments. It's called `check_constraints` (as in the linked code from `jOOQ-meta`)

**Comment by oshai** [comment]
Thanks, I tried to run it again, but there is no such col as `table_name`. Only constraint_name and check_clause. So I guess it comes from the join somehow.
Anyway like this it is executed: `select * from information_schema.check_constraints;` but it's hard to correlate the constraint to the table itself.

When executing  
```sql
select * from information_schema.check_constraints where constraint_name like 'enforce_srid_simplify_geom';
```  
it returns the correct check: `((st_srid(simplify_geom) = 4326))`.

**Comment by lukaseder** [comment]
My bad. I was on the run, there was a join that I've overlooked... I'll try to reproduce this.

**Comment by lukaseder** [comment]
OK, so I installed postgis, created the postgis extension, created your table as follows:

```sql
CREATE TABLE test (
  id serial NOT NULL,
  in_city_id int4 NOT NULL DEFAULT '-1'::integer,
  simplify_geom geometry NULL,
  CONSTRAINT enforce_srid_simplify_geom CHECK ((st_srid(simplify_geom) = 4326))
);
```

Found the expected check constraint in the `information_schema`:

```sql
select *
from information_schema.check_constraints cc 
join information_schema.table_constraints tc using (constraint_schema, constraint_name)
where tc.table_name = 'test'
```

And got the expected generated code:

```java
    @Override
    public List<Check<TestRecord>> getChecks() {
        return Arrays.<Check<TestRecord>>asList(
              Internal.createCheck(this, DSL.name("enforce_srid_simplify_geom"), "((st_srid(simplify_geom) = 4326))", true)
        );
    }
```

jOOQ doesn't do anything magic here, it just reads the `information_schema` and generates whatever that produces. The reason why you had a wrong check constraint must have been somewhere else.

I hope this helps.

**Comment by oshai** [comment]
@lukaseder I think the join has a bug. When I run it on my table (which have more definitions) I three matches constraint name rows:
```
public	enforce_srid_the_geom	...	((st_srid(the_geom) = 4326))
public	enforce_srid_the_geom	...	((st_srid(the_geom) = 4269))
public	enforce_srid_the_geom	...	((st_srid(the_geom) = '-1'::integer))
```
I will try to find the exact schema to reproduce it.

**Comment by lukaseder** [comment]
Interesting, some stale meta data that has not been cleaned up in some way, perhaps?

**Comment by oshai** [comment]
ok, here is some more info. I run the following queries:
```sql
//1
select * from information_schema.check_constraints where constraint_name like 'enforce_srid_the_geom';
//2
select * from information_schema.table_constraints where constraint_name like 'enforce_srid_the_geom';
//3
select * from information_schema.table_constraints where constraint_name like 'enforce_srid_the_geom' and table_name  like 'test';
```
First query returned 3 rows like we can see in my comment above.
Second query returned 43 rows from various tables (by it doesn't have the check info itself).
Third query returned one result (ie: the constraint for the table).

As you can see the results are ambiguous and it can't match the right constraint check.

When I run the query from [StackOverflow](https://dba.stackexchange.com/questions/214863/how-to-list-all-constraints-of-a-table-in-postgresql/214877#214877) the results seems correct:
```sql
SELECT con.*
       FROM pg_catalog.pg_constraint con
            INNER JOIN pg_catalog.pg_class rel
                       ON rel.oid = con.conrelid
            INNER JOIN pg_catalog.pg_namespace nsp
                       ON nsp.oid = connamespace
       WHERE nsp.nspname = 'public'
             AND rel.relname = 'test' and conname = 'enforce_srid_the_geom';
```
It only returns one row with the correct check.
@lukaseder In order to reproduce it you probably just need to create another table with the same constraint name. I don't think the table name filter actually works in that query.

So I think the right thing to do here is change the code to use that query.

@lukaseder What do you think?

**Comment by lukaseder** [comment]
Oh, indeed - it does appear that the check constraint namespace is per table, not per schema (unlike primary, unique and foreign key constraints!)

So, a `pg_catalog` query it will be, then.

**Comment by lukaseder** [comment]
`pg_catalog.pg_constraint.consrc` is no longer available in PostgreSQL 12. This produces the correct result:

```sql
create table t_10444_a (
  id int,
  constraint chk_10444 check (id > 0)
);

create table t_10444_b (
  id int,
  constraint chk_10444 check (id < 0)
);

select
  nsp.nspname,
  rel.relname,
  con.conname,
  pg_get_constraintdef(con.oid)
from pg_constraint con
join pg_class rel on rel.oid = con.conrelid
join pg_namespace nsp on nsp.oid = rel.relnamespace 
where nsp.nspname = 'public' and con.conname = 'chk_10444';
```

The result being:

```
nspname|relname  |conname  |pg_get_constraintdef|
-------|---------|---------|--------------------|
public |t_10444_a|chk_10444|CHECK ((id > 0))    |
public |t_10444_b|chk_10444|CHECK ((id < 0))    |
```

**Comment by lukaseder** [comment]
In order to maintain `<includeSystemCheckConstraints/>` functionality, we'll have to continue querying `information_schema.check_constraints`, but we'll concatenate those results in a union

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.14. Thanks again for your report.

**Comment by oshai** [comment]
Thanks! If there is a way for me to validate it (before the release) let me know.

**Comment by lukaseder** [comment]
Thanks for your offer. You could build 3.14.0-SNAPSHOT from github, if you want.

**Comment by oshai** [comment]
@lukaseder is this fix part of 3.13.4 that was released?

**Comment by lukaseder** [comment]
@oshai It was not. I'm usually reluctant to backport such code generator query changes because there's always a regression risk, e.g. an overlooked privilege requirement, an overlooked join predicate for edge cases, etc.

What's the use-case for which you need check constraints being generated?

**Comment by oshai** [comment]
@lukaseder it's not something production critical for us, I don't think we actually use those methods. It's just that each time we generate the files and commit them it creates different check and clutter our generated changesets with false (and incorrect) change diff.

**Comment by lukaseder** [comment]
I see, well you could turn off the generation of check constraints by using `<includeCheckConstraints>false</includeCheckConstraints>`, then
