### ISSUE TITLE
Custom records extending JOOQ records.

### ISSUE THREAD

**Issue by hemju** [jOOQ/jOOQ#10477]
### Your question:

In other frameworks, it is possible to overwrite/extend records. And I was wondering if the same is possible in JOOQ (spoiler, I don't think currently it is). Assume the following structure:

```
table users {
  first_name varchar,
  last_name varchar
}
```

This would generate the JOOQ classes

```
class Users<UsersRecord> {... }

class UsersRecord { ... }
```

If I want to get the users full name, I currently have to do this

```
class UsersUtil {
  String fullName(UsersRecord user) { ... }
}
```

however, what I actually want to do is this `user.fullName()` on the Record. The way I tried this is:

```
public class MyUser extends UsersRecord

public String fullName() { ... }
```

But since UsersRecord is used in the Table definition etc. also corresponding methods like `fetch`, etc. still return the UsersRecord. And if I add the method `fullName` in UsersRecord it gets overwritten when autogenerated.

### Possible question:

Splitting the record into 2 classes:

```
class BaseUsersRecord { ... } // this is what currently UsersRecord is
class UsersRecord extends BaseUsersRecord { ... } // this is a new class that gets generated, but not overwritten
class Users<UsersRecord> { ... } // the table class
```

Since `UsersRecord` only gets created but never overwritten (maybe a setting?), we could write our custom methods, behavior, etc. in `UsersRecord` without interfering with JOOQ's generated classes. The `BaseUsersRecord` gets generated and overwritten when there are DB changes (as it is the default behavior with Records right now).

**Comment by lukaseder** [comment]
Thanks for your message. It's currently not possible like that, see: https://github.com/jOOQ/jOOQ/issues/9844

You can let the record implement interfaces with default methods, though.
