### ISSUE TITLE
Update from CTE with batch values

### ISSUE THREAD

**Issue by MikePryadko** [jOOQ/jOOQ#10487]
SQL example (PostgreSQL):
```sql
-- CREATE TABLE test (id INT, val TEXT);

-- INSERT INTO test VALUES
--     (1, 'aaa'),
--     (2, 'bbb'),
--     (3, 'ccc');

WITH src AS (
    SELECT t.* FROM (VALUES 
    (1, 'xxx'),
    (3, 'yyy'),
    (5, 'zzz')) AS t(id, val)
)
UPDATE test
SET val = src.val
FROM src
WHERE test.id = src.id;
```
How to perform batch insert `values()` into select into CTE?
P.S. Global task: I need to batch update values in table (I have a big list of pairs ID<->DATA)

**Comment by lukaseder** [comment]
Thanks for your message. I'm not sure what your question is here, is it about the "batch insert" (i.e. the commented out `INSERT` statement) as you asked, or about the `UPDATE` statement?

In both cases, the SQL translates pretty directly to jOOQ, but of course, the devil is in the details. What are you struggling with, specifically?

**Comment by MikePryadko** [comment]
My question is about "bulk update"
I want collapse this:
```sql
UPDATE table SET field1 = value_1 WHERE field2 = value_2;
...
UPDATE table SET field1 = value_n WHERE field2 = value_n;
```
into one single query like:
```sql
UPDATE table SET field1 = ? WHERE field2 = ?;
```
My first decision was to use CTE (insert data into "temp" table and get data from it), but may be exists "better" way?

**Comment by lukaseder** [comment]
jOOQ supports PostgreSQL's `UPDATE .. FROM` syntax, which allows you to join two tables in an `UPDATE` statement. See: https://www.postgresql.org/docs/current/sql-update.html

Or you could batch a set of update statements using `DSLContext.batch()`, similar to the examples here:
https://www.jooq.org/doc/latest/manual/sql-execution/batch-execution

The CTE approach works as well. I'm not sure what approach is really "better" in PostgreSQL, or in your case.

I hope this helps...
