### ISSUE TITLE
ON CONFLICT for Postgresql not implemented completly

### ISSUE THREAD

**Issue by mschirmacher** [jOOQ/jOOQ#10484]
### Expected behavior and actual behavior:
In PG the `ON CONFLICT` clause allows to to specify the conflicting columns to consider.
Yet it also allowed to omit them completely. But doing so results in JOOQ always generating a query containing the primary as single conflict target which might behave wrong if there are more unique constraints in play
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
Against postgresql create a query with `onConflict()` not giving any arguments.
### Versions:

- jOOQ: 3.13.4

**Comment by mschirmacher** [comment]
I was too stupid to read correctly, sorry for the noise

**Comment by lukaseder** [comment]
Thanks for the feedback, @mschirmacher
