### ISSUE TITLE
Define function which returns 'recordset'

### ISSUE THREAD

**Issue by MikePryadko** [jOOQ/jOOQ#10486]
Hi there!
**SQL example (PostgreSQL 9.4 and higher):**
```sql
CREATE TABLE test_table (id INT, DATA JSONB);
INSERT INTO test_table VALUES (1, '[{"a":1,"b":"A"},{"a":2,"b":"B"},{"a":3,"b":"C"}]');
SELECT json_data.*
FROM test_table, jsonb_to_recordset(data) AS json_data(a INT, b TEXT)
WHERE id = 1;
```
**Result:**
![tmp](https://user-images.githubusercontent.com/31248040/90063370-f5f62600-dcf1-11ea-9ef5-95412f1e7015.png)
**Question:** How to do it with jooq API?

I need to specify two tables in FROM-clause, so I have to create something in jooq what would describe my "metatable"...
@lukaseder offered to use `.from("jsonb_array_elements_text()")`, but I need TWO tables and jooq did not allow combining TableLike<> and String args, and multiple `from()` impossibly too :neutral_face: 

P.S. I tried create separate classes for record and table, but it crushed my brain :disappointed:

**Comment by lukaseder** [comment]
Thanks for your message. Does this work for you?

```java
.from(TEST_TABLE, table("jsonb_to_recordset({0}) as json_data(a int, b text)", TEST_TABLE.DATA))
```

**Comment by MikePryadko** [comment]
Thanks, it works! But... is it possible to use more "jooq-style"? I mean, for example, define `json_data(a int, b text)` like table with fields and use it in `select` and in `fetch`?

**Comment by lukaseder** [comment]
We'd need to support the rather esoteric PostgreSQL extension to the derived column list syntax, first, i.e. the possibility to supply data types with the column names in `Table.as(String...)` or `Table.as(Name...)` to support exactly what you're doing here.

In jOOQ 3.14, `DSL.jsonTable()` will be supported, which translates to PostgreSQL `jsonb_path_query` and similar function calls: https://www.jooq.org/doc/3.14/manual/sql-building/table-expressions/json-table-function/

There's also room for looking into supporting functions like `jsonb_to_recordset` specifically, from PostgreSQL: https://github.com/jOOQ/jOOQ/issues/10018

Until th, plain SQL templating is as good as it gets.

**Comment by lukaseder** [comment]
> We'd need to support the rather esoteric PostgreSQL extension to the derived column list syntax, first, i.e. the possibility to supply data types with the column names in `Table.as(String...)` or `Table.as(Name...)` to support exactly what you're doing here.

Found the issue: https://github.com/jOOQ/jOOQ/issues/5926
