### ISSUE TITLE
There is no boolean operators for TableField< ... , Boolean>

### ISSUE THREAD

**Issue by MikePryadko** [jOOQ/jOOQ#10490]
I want to make:
```java
// var t = MyTable.MY_TABLE;
.set(t.BOOL_FIELD, t.BOOL_FIELD.or(myBoolVariableFromMethodParams))
```
, but there is no method `or()` :neutral_face: I've tried `.bitOr()`, but got this:
```
org.postgresql.util.PSQLException: ERROR: operator does not exist: boolean | boolean
```
Expected SQL should be like:
```sql
UPDATE my_table
SET bool_field = bool_field OR ?;
```
I've tried even:
```java
.set(t.BOOL_FIELD, t.BOOL_FIELD.eq(true).or(val(myBoolVariableFromMethodParams).eq(true)))
```
, but without success:
```
Cannot resolve method 'set(org.jooq.TableField< ... , java.lang.Boolean>, org.jooq.Condition)'
```
### Versions:

- jOOQ: 3.13.1
- Java: 11
- Database (include vendor): PostgreSQL 12

**Comment by MikePryadko** [comment]
Sorry!(( I've found answer [in blog:](https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/update-statement/#comment-3177850866)

**Comment by lukaseder** [comment]
Thanks for the message. For the record, you should use `DSL.condition(Field<Boolean>)`

**Comment by lukaseder** [comment]
We'll add a section to the manual about boolean columns: https://github.com/jOOQ/jOOQ/issues/10491

**Comment by MikePryadko** [comment]
So, I decide to use custom function:
```java
private static Field<Boolean> boolOr(Field<Boolean> a, boolean b) {
	return field("{0} OR {1}", Boolean.class, a, val(b));
}
```
and use it that way:
```java
.set(t.BOOL_FIELD, boolOr(t.BOOL_FIELD, myBoolVariableFromMethodParams))
```

**Comment by lukaseder** [comment]
Sure, you can always resort to plain SQL templating, but you don't really have to in this case. You could write:

```java
.set(t.BOOL_FIELD, field(condition(t.BOOL_FIELD).or(val(myBoolVariableFromMethodParams))))
```
