### ISSUE TITLE
Deprecate <interfaces/> in code generator

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10509]
The generated `<interfaces/>` and `<immutableInterfaces/>` feature is a big source of trouble and yak shaving in the code generator logic, and also a source of still unresolved problems. Just a few examples:

- https://github.com/jOOQ/jOOQ/issues/2834 
- https://github.com/jOOQ/jOOQ/issues/2934 
- https://github.com/jOOQ/jOOQ/issues/3868 
- https://github.com/jOOQ/jOOQ/issues/6199 
- https://github.com/jOOQ/jOOQ/issues/8209 
- https://github.com/jOOQ/jOOQ/issues/10639 
- https://github.com/jOOQ/jOOQ/issues/10904 
- https://github.com/jOOQ/jOOQ/issues/10908 
- https://github.com/jOOQ/jOOQ/issues/14727

More examples can be expected once embeddable types will ship (#2530).

Interfaces are generated to allow for abstracting over the generated records and POJOs. If we could get rid of generated interfaces, which are a more esoteric feature, then code generation logic could be greatly simplified.

This issue will introduce a new deprecation warning in code generation output with a call for feedback on this issue, to help gather user feedback about usage use-cases before the feature might be removed. It does not yet mean the feature will be removed.

**Comment by axelfontaine** [comment]
Most of the trouble with this feature comes from Records implementing the interface. Perhaps a middle ground could be found where only that part of this feature gets deprecated, leaving the interface to be implemented by manually written or auto-generated POJOs.

**Comment by lukaseder** [comment]
The point of the interfaces is to abstract over records and POJOs. What would be the benefit of keeping the interfaces only on POJOs?

**Comment by axelfontaine** [comment]
This allows you to bring your own POJOs and still have the guarantee that their interface is compatible with the current structure of the database.

**Comment by lukaseder** [comment]
And what's the benefit of doing that?

**Comment by axelfontaine** [comment]
The jOOQ generated POJOs don't always encapsulate all desired logic. I currently work around this with Kotlin extension methods, but this isn't possible in Java.

This would basically mean I could for example define my own Kotlin data classes and still have the guarantee that they stay in sync with the DB structure.

**Comment by lukaseder** [comment]
I see, so you're profiting from the fact that you have an API for the POJO type, but you don't rely on this API to be also implemented by the record types...

I think that most problems these interfaces are causing is because they try to abstract over the records and POJOs.

**Comment by axelfontaine** [comment]
Correct. Records stay confined to the implementation of my data access layer, while POJOs find their way in interfaces and the domain model.

**Comment by axelfontaine** [comment]
> I see, so you're profiting from the fact that you have an API for the POJO type, but you don't rely on this API to be also implemented by the record types...

Just to amend, this can also be multiple POJO types, where a generated `IThing` interface is implemented by both `ManualThing` and `ComputedThing` concrete classes.

**Comment by lukaseder** [comment]
Sure

**Comment by lukaseder** [comment]
I won't deprecate this feature. It's mildly useful, despite all the historic bugs and edge cases.

The code generation integration tests have come a long way since this issue was created. We now have *much* more coverage in all supported languages (Java, Kotlin, Scala), so I'm more confident to be able to fix any remaining issues.
