### ISSUE TITLE
Script Runner

### ISSUE THREAD

**Issue by nbrugger-tgm** [jOOQ/jOOQ#10515]
### Use case:
Sometimes i have a SQL schema and i would like my application to be able to connect to any Database and apply it to the server. So my application is able to use any database
### Possible solution you'd like to see:
An jOOQ'ified version of https://github.com/BenoitDuffez/ScriptRunner/blob/master/ScriptRunner.java (Originaly from iBatis)
```
create.scrip(<File/Reader/Stream/whatever>).execute()
```

### Possible workarounds:

Not me but some iBatis dupe (https://github.com/BenoitDuffez/ScriptRunner/blob/master/ScriptRunner.java)

**Comment by lukaseder** [comment]
Thanks for your feature request.

From what I can tell, we have all the operations that you require here, mostly:

```java
// If you're working with generated code
ctx.meta(generatedSchema).ddl().executeBatch();

// If you're working with SQL scripts
ctx.meta(Source.of(file/reader/whatever)).ddl().executeBatch();

// Or even just parse the thing
ctx.parser().parse(Source.of(file/reader/whatver)).executeBatch();
```

I hope this helps

**Comment by nbrugger-tgm** [comment]
Sadly this does not work with procedures or triggers which it does with the script runner.

At least it didn't worked the last time I tried it. I think it might be because of the DELMITTER Thinf

**Comment by lukaseder** [comment]
Procedure and trigger support are on the roadmap: https://github.com/jOOQ/jOOQ/issues/6956, https://github.com/jOOQ/jOOQ/issues/9190,  but that's probably not what you had in mind - you'd like jOOQ to be Flyway? I.e. to "semi-parse" scripts to detect and interpret things like `DELIMITER` commands, `SET` commands, but none of the others?

**Comment by lukaseder** [comment]
I think this may make sense, I've created a separate feature request to look into the option of turning the parser into a SQL statement agnostic one, interpreting only preprocessing commands, like `DELIMITER`: https://github.com/jOOQ/jOOQ/issues/10519
