### ISSUE TITLE
ForcedType not applied to members of PostgreSQL composite type

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#10516]
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

Schema:

```sql
CREATE TYPE route_point AS
(
    longitude INT,
    latitude  INT,
    altitude  INT
);

CREATE TABLE route
(
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    route       route_point[] NOT NULL
);
```

ForcedTypes:

```java
org.jooq.meta.jaxb.ForcedType()
    .withIncludeExpression(".*\\..*\\.longitude")
    .withIncludeTypes("int")
    .withUserType("com.veturanto.server.Longitude")
    .withConverter("com.veturanto.server.database.LongitudeConverter"),
org.jooq.meta.jaxb.ForcedType()
    .withIncludeExpression(".*\\..*\\.latitude")
    .withIncludeTypes("int")
    .withUserType("com.veturanto.server.Latitude")
    .withConverter("com.veturanto.server.database.LatitudeConverter"),
org.jooq.meta.jaxb.ForcedType()
    .withIncludeExpression(".*\\..*\\.altitude")
    .withIncludeTypes("int")
    .withUserType("com.veturanto.server.Altitude")
    .withConverter("com.veturanto.server.database.LongitudeConverter")
```

Generated code:
```java
public class RoutePoint implements Serializable {

    private static final long serialVersionUID = 2052293106;

    // Should have had the types Longitude, Latitude and Altitude
    private final Integer longitude;
    private final Integer latitude;
    private final Integer altitude;

    public RoutePoint(RoutePoint value) {
        this.longitude = value.longitude;
        this.latitude = value.latitude;
        this.altitude = value.altitude;
    }

    ...
}
```

### Versions:

- jOOQ: 3.13.4
- Java: 14
- Database (include vendor): PostgreSQL 12

**Comment by lukaseder** [comment]
Thanks a lot for your report. For the record, the issue you referred to is this one: https://github.com/jOOQ/jOOQ/issues/10231

I can see how this is really annoying, *especially* for the `integer` / `int` type, both of which are accepted as type names in many dialects. Also, names like `varchar` / `character varying`, and a lot more. In your case, I think that matching the type shouldn't be necessary, no? Specifically, if you're using a `DOMAIN` type for things like latitude / longitude / etc., then this jOOQ 3.14 feature might be very useful to you: https://github.com/jOOQ/jOOQ/issues/10511, https://www.jooq.org/doc/3.14/manual/code-generation/codegen-embeddable-types/codegen-embedded-domains/

I will give #10231 another thought. The status quo is very annoying for `int` / `integer`
