### ISSUE TITLE
Parse match full, match partial, and match simple info in foreign keys

### ISSUE THREAD

**Issue by wisnesky** [jOOQ/jOOQ#10531]
### Use case:

Several SQL dialects allow a number of foreign key semantics to simultaneously occur in the same SQL program - the so-called full, partial, and simple match semantics.  I'd like access to this information to perform semantics analysis.

### Possible solution you'd like to see:

ForeignKey should have a getMatchType() method that can be one of full or partial or simple.

### Possible workarounds:

Simple semantics is the usual default, but the only workaround I can see otherwise is to do one's own parsing.

### Versions:

- jOOQ: java 3.13

**Comment by lukaseder** [comment]
Thanks a lot for your suggestion. See also: #10430
