### ISSUE TITLE
Calling "renderNamedParams" returns different count of parameters than "extractParams"

### ISSUE THREAD

**Issue by foxylion** [jOOQ/jOOQ#10544]
### Expected behavior and actual behavior:
When calling `ctx.renderNamedParameters(query)` it returns a Query with a different count of named parameters than what is returned by `ctx.extractParams(query)`.

### Steps to reproduce the problem:
See https://github.com/foxylion-playground/jOOQ-mcve/tree/mcve/1
There are two test cases, one for named parameters, one for bind values.
The named parameters case returns an inconsistent count of parameters for the given query.

### Versions:

- jOOQ: 3.13.4 (also 3.13.2)
- Java: 11
- Database (include vendor): PostgreSQL (but not relevant)
- OS: not relevant
- JDBC Driver (include name if inofficial driver): not relevant

**Comment by lukaseder** [comment]
I'm sorry about the delay with this issue. I've had a look at your MCVE now. There's simply a misunderstanding of what is a "named parameter.". The `isTrue()` method generates an *inline* value, which is also a `Param`, but not a bind value (named or not, doesn't matter). Check this out in your MCVE:

```java
System.out.println(ctx.extractParams(query).get("1").isInline());
```

It prints:

```
true
```
