### ISSUE TITLE
Type parameterized classes use raw types in generated code

### ISSUE THREAD

**Issue by pschichtel** [jOOQ/jOOQ#10547]
### Expected behavior and actual behavior:

We are using Kotlin in a project and we have a simple ADT likes this:

```kotlin
sealed class ADT<T>() {
    object Value1 : ADT<Int>()
    object Value2 : ADT<String>()
}
```

For that we have written a converter like this:

```kotlin
class ADTConverter : AbstractConverter<String, ADT<*>>(String::class.java, ADT::class.java) {
    // ...
}
```

jOOQ then generates the field definitions with this ADT type as follows:

```java
public final TableField<SomeRecord, ADT> Field = createField(DSL.name("field"), type, this, "", new ADTConverter())
```

The problem with this is, that the converters target type (`ADT<*>`) does not match the field type (`ADT`) and in kotlin we can't use rawtypes.

The expected code would be this:
```java
public final TableField<SomeRecord, ADT<?>> Field = createField(DSL.name("field"), type, this, "", new ADTConverter())
```

In general I think jOOQ should use wildcards instead of raw types.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

I think the above section contains all the information. If you need more please tell me.

### Versions:

- jOOQ: 3.13.4
- Java: 13
- Database (include vendor): Postgres 11
- OS: Linux
- JDBC Driver (include name if inofficial driver): 42.2.5

**Comment by lukaseder** [comment]
Did you declare `<userType>com.example.ADT&lt;?&gt;</userType>` ?

> In general I think jOOQ should use wildcards instead of raw types.

jOOQ doesn't know anything about your `userType`. It doesn't class-load it, nor introspect it. It just uses the type you provide it with.

**Comment by lukaseder** [comment]
This is a good reminder, though, to make sure such a use-case also works in the jOOQ 3.14 `KotlinGenerator`

**Comment by pschichtel** [comment]
> Did you declare `<userType>com.example.ADT&lt;?&gt;</userType>` ?

We did, but the generator swallows the `<` and `>`. Forgot to mention that. So `ADT<?>` becomes `ADT?` in the code.

**Comment by lukaseder** [comment]
It shouldn't and it works for me. How can I reproduce this? Can you please share your code generator configuration?

**Comment by pschichtel** [comment]
It actually does work, we tried it again. Not sure what went wrong the first time. Sorry for the confusion!

**Comment by lukaseder** [comment]
No worries. Perhaps you didn't xml-escape the `&gt; entities and placed `<?>` directly?

**Comment by pschichtel** [comment]
We did encode it correctly. Our assumption is, that the editor just didn't update the open files or so.
