### ISSUE TITLE
Add support for Apache Ignite

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10551]
We could add support for Apache Ignite:
https://ignite.apache.org/docs/latest

### Remarks:

- The initial support will include Ignite 2.x. Ignite 3.x will be rewritten to use calcite internally. This might lead to changes in SQL syntax, which we can discover when Ignite 3.x is ready. Some feedback here: http://apache-ignite-users.70518.x6.nabble.com/SQL-strategy-for-Apache-Ignite-3-0-td35255.html

**Comment by ascertrobw** [comment]
Would be a great addition, and something I could use to pitch to the firm I work to take our an Enterprise license seat or two.

**Comment by lukaseder** [comment]
Sounds interesting, @ascertrobw. Can I take your word for this "letter of intent"? :)

**Comment by ascertrobw** [comment]
> 
> 
> Sounds interesting, @ascertrobw. Can I take your word for this "letter of intent"? :)

Very much so. We love jOOQ. At present, the only thing missing from it being a "1 stop shop" for our DB support needs is Ignite. With that included, we have all the OSS and commercial DBs that we wish to support covered. Which make it an easy justification to get a one or two of our key DB devs proper Enterprise licenses both to support them and you guys.

**Comment by lukaseder** [comment]
Excellent. I'll see if this can be done easily and will hopefully report within the next week

**Comment by ascertrobw** [comment]
Great stuff, thanks Lukas

FWIW – I think the current Ignite JDBC/SQL flavour is very H2-like (that is what is used under the hood).

You might want to take a look at the notes in their version 3.x roadmap<https://cwiki.apache.org/confluence/display/IGNITE/Apache+Ignite+3.0> to get a heads up on where they are taking the implementation, as I believe they have big plans for a more schema centric model. Although that may just be in their internal mapping and optimisation handling, and not affect the JDBC side of things too much. It’s also very unclear when a 3.x would surface – it’s very early days judging by the threads I read. My guess would be it may be more than a year out, and further before it gets real live use (we’d certainly not be aiming to move from 2.x until a successor were well established)

-Rob

**Comment by lukaseder** [comment]
Let's look into supporting the current versions first. If 3.0 is very different from the current versions, we can use our existing versioned dialect infrastructure to support 3.0 and 2.x...

**Comment by lukaseder** [comment]
OK, so, let's go... https://issues.apache.org/jira/browse/IGNITE-14024 😀

**Comment by ascertrobw** [comment]
Oops .... :)

**Comment by lukaseder** [comment]
Some feedback on the differences between Ignite 2.x and 3.x here: http://apache-ignite-users.70518.x6.nabble.com/SQL-strategy-for-Apache-Ignite-3-0-td35255.html

**Comment by ascertrobw** [comment]
> 
> 
> Some feedback on the differences between Ignite 2.x and 3.x here: http://apache-ignite-users.70518.x6.nabble.com/SQL-strategy-for-Apache-Ignite-3-0-td35255.html

This is very interesting - thanks for the feedback Lukas.

**Comment by lukaseder** [comment]
OK, I think the set of Ignite bugs discovered with this integration is impressive enough (https://github.com/jOOQ/jOOQ/issues/10551#issuecomment-763807282)

A lot of our integration tests still fail, likely due to more Ignite bugs, but a majority of them also pass. We'll ship the integration as it is now with jOOQ 3.15 and fix more issues as we gather community feedback and wait for Ignite to fix theirs.

**Comment by ascertrobw** [comment]
> 
> 
> OK, I think the set of Ignite bugs discovered with this integration is impressive enough ([#10551 (comment)](https://github.com/jOOQ/jOOQ/issues/10551#issuecomment-763807282))
> 
> A lot of our integration tests still fail, likely due to more Ignite bugs, but a majority of them also pass. We'll ship the integration as it is now with jOOQ 3.15 and fix more issues as we gather community feedback and wait for Ignite to fix theirs.

That is an impressive set of bugs - and obviously impressive piece of work your side too! Will look forward to grabbing a 3.15 copy when ready and giving it a whirl.

**Comment by lukaseder** [comment]
It has to be said that some of the integration tests would not have passed/failed consistently without this little gem:

```java
@Before
public void slowDown() {

    // This database product is quite unstable. If tests run "full speed", it throws random exceptions, including:

    // java.sql.SQLException: Failed to complete exchange process.
    // java.sql.SQLException: Failed to execute map query on remote node
    // java.sql.SQLException: Concurrent access to JDBC connection is not allowed
    sleep(100L);
}
```

**Comment by ascertrobw** [comment]
> 
> 
> It has to be said that some of the integration tests would not have passed/failed consistently without this little gem:
> 
> ```java
> @Before
> public void slowDown() {
> 
>     // This database product is quite unstable. If tests run "full speed", it throws random exceptions, including:
> 
>     // java.sql.SQLException: Failed to complete exchange process.
>     // java.sql.SQLException: Failed to execute map query on remote node
>     // java.sql.SQLException: Concurrent access to JDBC connection is not allowed
>     sleep(100L);
> }
> ```

Ah yes - the old "do it slower" kludge. Good catch!

**Comment by lukaseder** [comment]
> Ah yes - the old "do it slower" kludge. Good catch!

Right. "good" 😁 How do you handle these things in production?

**Comment by lukaseder** [comment]
Anyway. So, the regression tests are now set up on our Jenkins, so we're good to go with Apache Ignite in jOOQ 3.15. Early feedback would be greatly appreciated, of course!

**Comment by ascertrobw** [comment]
> 
> 
> Anyway. So, the regression tests are now set up on our Jenkins, so we're good to go with Apache Ignite in jOOQ 3.15. Early feedback would be greatly appreciated, of course!

Sounds good - will stick it on my list to look at. Thanks for the time you've taken on this.

**Comment by lukaseder** [comment]
Regressions discovered when upgrading from Ignite 2.9.1 to 2.10.0:

- https://issues.apache.org/jira/browse/IGNITE-14354 Regression when using `SELECT (EXISTS (...))`
- https://issues.apache.org/jira/browse/IGNITE-14356 Regression when using derived table in `LEFT JOIN`
- https://issues.apache.org/jira/browse/IGNITE-14358 Regression when referencing aliased constant from derived table

Proving again that running integration tests in our nightly builds is premature.

**Comment by lukaseder** [comment]
Half a year later, and none of the issues I reported (not a single one!) got traction let alone got fixed. The regressions also seem very significant and didn't get any replies.

While I understand I don't have any support contract, I don't think I reported trivial issues. A severe regression like this: https://issues.apache.org/jira/browse/IGNITE-14356 just shows that this product is hardly tested, nor production ready. This is unprecedented.

Being part of the jOOQ Open Source Edition, my investment here is hard to monetise, which makes matters worse. I'm contemplating removing the dialect again in the future, as I'm not convinced this will ever improve. What is everyone's take here, among the upvoters, including @ascertrobw, @balazskreith, @sammyvimes, @yassinhajaj, @d3vel0per ?

**Comment by ascertrobw** [comment]
Yep - have to say, based on our experiences also I couldn't disagree with your feelings here. It's a great shame, but I'd have to agree with your conclusion.

**Comment by lukaseder** [comment]
So, you've stopped using Ignite, @ascertrobw ?

**Comment by lukaseder** [comment]
Deprecation task here: https://github.com/jOOQ/jOOQ/issues/12465

**Comment by ascertrobw** [comment]
> So, you've stopped using Ignite, @ascertrobw ?

Rather painfully, yes, it was a key part of our strategy but the issues you've found also plagued us - we're back on a strict/straight SQL model. We've been hoping it'd be a temporary shift, but I doubt it given the current state of play.

**Comment by lukaseder** [comment]
Thanks a lot for the insight. Sorry to hear that - must have been quite the tricky migration...

**Comment by ascertrobw** [comment]
> Thanks a lot for the insight. Sorry to hear that - must have been quite the tricky migration...

Certainly not easy - but we're developers, so it's given us some nice challenges to work on!

**Comment by lukaseder** [comment]
> but we're developers, so it's given us some nice challenges to work on!

Well, it's good that you can see it this way.

I don't (as far as jOOQ is concerned). If I can't find a way to monetise this dialect, I've wasted time and money on it. A good reminder to stop adding more dialects that aren't sponsored, in the future - especially to the jOOQ Open Source Edition. All *popular* dialects are supported, so anything new needs sponsoring from users or DBMS vendors.

**Comment by paolodedios** [comment]
@lukaseder Would charging for the Apache Ignite dialect integration as part of the Professional version tier or higher alleviate your concerns? While it is an open source project, it is not dissimilar to CockroachDB or Yugabyte, with an open source component and singular company funding its development.  

The current Ignite software occupies a weird space, sitting in the nexus of a cache, distributed compute engine, and datastore.  It's a lot like how SQL is used as an integration interface for Apache Spark and Delta Lake from Databricks.  The SQL implementation is a convenience interface for developers but full conformance does not seem like a hard requirement. I just recently got on the JOOQ bandwagon and would definitely hate to see this integration go because its SQL conformance is not on par with a true RDBMS.  

JOOQ is definitely a productivity booster and has been valuable for integrating with such systems by abstracting away the SQL feature gaps.  With more backend architectures relying on polygot persistence and SQL to simplify how it is all glued together, JOOQ's ability to work the spectrum of conformance has been more valuable to me than any singular DB it supports.  The cost of maintenance and support is real though, and I get where you're coming from.

**Comment by lukaseder** [comment]
> Would charging for the Apache Ignite dialect integration as part of the Professional version tier or higher alleviate your concerns?

Before the deprecation turns into removal, we could certainly consider moving the dialect to the commercial editions first, similar as old JDK version support is phased out via first moving this support to the commercial editions.

But I don't think there's any significant revenue to be expected from this integration. Especially in the case of Ignite, which is not a very sophisticated SQL engine (SQL not being its primary purpose), I personally doubt that a commercial jOOQ dialect would cover for the efforts of re-enabling the integration tests as I've laid out here: https://github.com/jOOQ/jOOQ/issues/12465#issuecomment-1009675233

Not just that, but the commercial edition provides warranties, and I'm not too keen on maintaining such a warranty on the jOOQ/Ignite dialect for the price of a few jOOQ Professional Edition licenses.

However, as we've done with other dialects, we do accept sponsoring projects, which in themselves offer guaranteed mid-term support for a dialect. We've done this with:

- CockroachDB (vendor paid)
- Exasol (end user paid)
- Yugabyte (vendor paid)

And I'm currently discussing similar sponsorships for a few other dialects. Sponsoring may tip the balance of cost/benefit in favour of continued maintenance, so if this is something of interest to you, please do get in touch at sales@datageekery.com

> The current Ignite software occupies a weird space, sitting in the nexus of a cache, distributed compute engine, and datastore. It's a lot like how SQL is used as an integration interface for Apache Spark and Delta Lake from Databricks. The SQL implementation is a convenience interface for developers but full conformance does not seem like a hard requirement. I just recently got on the JOOQ bandwagon and would definitely hate to see this integration go because its SQL conformance is not on par with a true RDBMS.

Just to be sure: This isn't about SQL conformance (it wasn't too bad with the H2 based dialect, and it will also be reasonable with the Calcite based dialect). This is about QA. We can't spend our time investigating super weird RDBMS bugs and regressions like the ones encountered. I didn't document / report everything, but if I remember correctly, the server crashed randomly but regularly with several different reasons, which I can really not spend time investigating.

Without running integration tests, there's no way of knowing whether the jOOQ/Ignite dialect is sound, and I don't want to ship this kind of poor quality (not knowing if jOOQ itself has regressions in the Ignite dialect).

> JOOQ is definitely a productivity booster and has been valuable for integrating with such systems by abstracting away the SQL feature gaps. With more backend architectures relying on polygot persistence and SQL to simplify how it is all glued together, JOOQ's ability to work the spectrum of conformance has been more valuable to me than any singular DB it supports. The cost of maintenance and support is real though, and I get where you're coming from.

Well, no ship has sailed yet. This is just a discussion about what this dialect *should be*, in case we do keep supporting it. A decision can be made once we investigate Calcite based dialect support. In that case, the `IGNITE_2_10` dialect will move to the commercial editions anyway (as any historic dialect support today), and the `IGNITE_3_0` dialect might be maintained in the jOOQ Open Source Edition.

**Comment by paolodedios** [comment]
Thanks for clarifying the various paths forward for this version of the dialect.  Perhaps Apache Ignite users can lobby GridGrain to commercially sponsor their particular H2 or Calcite dialect.

**Comment by lukaseder** [comment]
> Perhaps Apache Ignite users can lobby GridGrain to commercially sponsor their particular H2 or Calcite dialect.

That would be great! If you have contacts there, let me know.
