### ISSUE TITLE
Plugin 'org.jooq:jooq-codegen-maven:' not found

### ISSUE THREAD

**Issue by paulschmitz82** [jOOQ/jOOQ#10577]
I'm trying to implement jooq codegen into my spring boot application, the problem is that jooq-codegen-maven artifactId can't be found when adding the codegen plugin to my pom plugins.

![error](https://user-images.githubusercontent.com/32984714/91981742-9061ec00-ed29-11ea-9556-bd714859066c.PNG)

**Comment by lukaseder** [comment]
Thank you very much for your message.

It seems that you have configured your `<pluginManagement/>` to pull a not yet existing version `4.0.0` of the plugin.

I hope this helps

**Comment by paulschmitz82** [comment]
I actually don't even access the pluginmanagement and if i try to define a version it doesnt find it either
![error2](https://user-images.githubusercontent.com/32984714/91987211-0ec08d00-ed2e-11ea-9d12-4bf6308141a0.PNG)

**Comment by lukaseder** [comment]
Well, it's right there: https://search.maven.org/artifact/org.jooq/jooq-codegen-maven/3.13.4/maven-plugin. Perhaps you have a different repository than Maven Central configured?

**Comment by paulschmitz82** [comment]
My jooq-codegen-maven-3.13.4.pom looks exactly like the one you posted, i only added the dependencies to my project to implement jooq, is that correctly done? in my repository there is under jooq-codegen-maven another directory ${org.jooq.version}
could this cause the problem? 
![image](https://user-images.githubusercontent.com/32984714/91990996-ae801a00-ed32-11ea-8069-cf423c4f6556.png)

**Comment by lukaseder** [comment]
I don't know :) When these kinds of things happen, I usually just delete the entire local Maven cache under `~/.m2`...
