### ISSUE TITLE
IN predicate on Field.java accepts Collection<?> but other overloads are bound to T

### ISSUE THREAD

**Issue by joellundell** [jOOQ/jOOQ#10599]
### Your question:

Noticed a discrepancy in the documentation of the [IN predicate](https://www.jooq.org/doc/3.10/manual/sql-building/conditional-expressions/in-predicate/) and the actual implementation in [jOOQ 3.13.4 Field.java](https://github.com/jOOQ/jOOQ/blob/version-3.13.4/jOOQ/src/main/java/org/jooq/Field.java).

Is there any reason why the overload taking a collection isn't bound by `Collection<? extends T>` or just `Collection<T>` like in the documentation?

Here's an example of how wrong it can become when the collection isn't bound (made up tables etc).

We had two enums, `UserStatus` and `PageStatus`, with one overlapping value `UserStatus.OK` and `PageStatus.OK`. We then had a method that was incorrectly coded to take a `Set<PageStatus>`: `getUsersWithStatus(Set<PageStatus> statuses)`. 

When querying for users using `USER.USER_STATUS.in(statuses)` it worked as long as the set only contains the `PageStatus.OK` enum because both enums translated in to "OK" in MySql enum column. 

If the query had been written as `USER.USER_STATUS.in(PageStatus.OK)` the compiler would've caught this since that `IN` predicate overload is defined as `in(T... values)`.

Thank you,
Joel

### Versions:

- jOOQ: 3.13.4
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your question.

This had been changed in jOOQ 3.4.0 (#2973). `Collection<T>` or `Collection<? extends T>` would be the wrong type bound for the `Collection` argument. A better one would be `Collection<? extends Field<T>>`. The best one would be `Collection<? extends T|Field<T>>`, but regrettably, Java doesn't support union types.

Type safety is a compromise in a language like Java. In this case, the possibility of being able to pass either `T` or `Field<T>` types to the `IN` predicate (with the risk of accidentally accepting something wrong) was judged more important than the type safety of requiring `Field<T>` while forbidding `T` types.

**Comment by joellundell** [comment]
Thanks for the response @lukaseder.

Sounds like a fair trade-off to me. I'm a big fan of what you guys have done in terms of type safety and writing queries!

Since it's a conscious decision the confusion could be avoided with an update to the documentation https://www.jooq.org/doc/3.13/manual/sql-building/conditional-expressions/in-predicate/ where it says 
`in(Collection<T>)                   // Construct an IN predicate from a collection of bind values` but shouldn't it really be
`in(Collection<?>)                   // Construct an IN predicate from a collection of bind values`?

**Comment by lukaseder** [comment]
@joellundell Thanks for pointing this out. Yes of course, we should fix this.
