### ISSUE TITLE
Ambiguous match found when using complex implicit join graphs

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10603]
At some point, implicit join graphs inevitably produce an `Ambiguous match found` warning in the logs, because internally, the implicit join produces its left joins using `onKey(ForeignKey)` using the generated `ForeignKey` meta data, which lacks proper qualification of the join path alias (see also: #5050)

```
15:54:00,134  INFO [org.jooq.impl.Fields                              ] - Ambiguous match found for A. Both "alias_43932461"."A" and "alias_7888650"."A" match.
java.sql.SQLWarning: null
	at org.jooq.impl.Fields.field0(Fields.java:148) [classes/:?]
	at org.jooq.impl.Fields.field(Fields.java:87) [classes/:?]
	at org.jooq.impl.AbstractRow.field(AbstractRow.java:126) [classes/:?]
	at org.jooq.impl.AbstractTable.field(AbstractTable.java:229) [classes/:?]
	at org.jooq.impl.JoinTable.onKey(JoinTable.java:737) [classes/:?]
	at org.jooq.impl.JoinTable.onKey(JoinTable.java:695) [classes/:?]
	at org.jooq.impl.JoinTable.onKey(JoinTable.java:1) [classes/:?]
	at org.jooq.impl.AbstractContext$JoinNode.joinTree(AbstractContext.java:788) [classes/:?]
	at org.jooq.impl.DefaultRenderContext.scopeEnd0(DefaultRenderContext.java:287) [classes/:?]
	at org.jooq.impl.AbstractContext.scopeEnd(AbstractContext.java:582) [classes/:?]
	at org.jooq.impl.SelectQueryImpl.accept0(SelectQueryImpl.java:1216) [classes/:?]
	at org.jooq.impl.SelectQueryImpl.accept(SelectQueryImpl.java:911) [classes/:?]
	at org.jooq.impl.DefaultRenderContext.visit0(DefaultRenderContext.java:609) [classes/:?]
	at org.jooq.impl.AbstractContext.visit(AbstractContext.java:265) [classes/:?]
	at org.jooq.impl.DefaultRenderContext.render(DefaultRenderContext.java:338) [classes/:?]
	at org.jooq.test.all.listeners.PrettyPrinter.renderEnd(PrettyPrinter.java:105) [classes/:?]
	at org.jooq.impl.ExecuteListeners.renderEnd(ExecuteListeners.java:165) [classes/:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:328) [classes/:?]
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:333) [classes/:?]
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2880) [classes/:?]
	at org.jooq.test.all.testcases.ImplicitJoinTests.testImplicitJoinCompleteGraphTraversal(ImplicitJoinTests.java:274) [test-classes/:?]
	at org.jooq.test.jOOQAbstractTest.testImplicitJoinCompleteGraphTraversal(jOOQAbstractTest.java:7024) [test-classes/:?]
```

There are three ways to solve this:

1. Avoid `onKey()` calls
2. Fix #5050 
3. Rewrite the `ForeignKey` instance on the fly prior to calling `onKey()`

Avoiding the `onKey()` call is probably the easiest.

**Comment by ThoSap** [comment]
Will this be backported for an upcoming 3.13.X release by any chance?

If not I will eagerly await 3.14.X and all the new cool features.

Thank you Lukas for this divine project🙏🏼😁

**Comment by lukaseder** [comment]
Thanks for your nice words.

There has been a lot of improvements around implicit join in the context of embedded types in jOOQ 3.14. I don't think the backport can be achieved very easily, in isolation of all the other improvements. I prefer not to.

Regarding 3.14, all that's left to do is polish a few embedded types caveats that I don't want to ship the way they are right now. Then, we're ready.

**Comment by lukaseder** [comment]
Of course, you could use an integration tested nightly build from here, for jOOQ 3.14, already now!
https://www.jooq.org/download/versions

**Comment by ThoSap** [comment]
Then I'll happily wait for 3.14😋
I will maybe try a nightly build as we do have a perpetual jOOQ Professional license in our company.

**Comment by james-deee** [comment]
@lukaseder we have upgraded to 3.14.0 and we are still seeing a "Ambiguous match found for <col_name>" for one of our complex queries. I can attempt to get an example set of tables + joins setup if need be, just wanted to call out that we are still seeing it.

Thanks.

**Comment by lukaseder** [comment]
@james-deee Thanks a lot. Can you please report this as a new issue with instructions on how to reproduce it? The warning message can happen for a variety of reasons, it doesn't have to be the same issue.

**Comment by DanielHaughton** [comment]
@lukaseder we are encountering this on an old version and cant upgrade right now for reasons I wont go into here.

We dont seem to have this issue occur all the time, but its happening when do do table1 left outerjoin table2, table2  left outerjoin table3.


We map the Records into jooq entities like this

```
      Table1Entity table1Entity =
              record.into(TABLE_1).into(Table1Entity.class);
      Table2Entity table2Entity =
              record.into(TABLE_2).into(Table2Entity.class);
      Table3Entity table3Entity =
              record.into(TABLE_3).into(Table3Entity.class);```


Our data seems to map correctly mapping this way in the place this is occurring, could this bug cause the data being mapped to be incorrect other times? As in put the id of table1 into the table2 Entity class?

**Comment by lukaseder** [comment]
@DanielHaughton Thanks for your message. Like what I told @james-deee, this could be the same bug, or it might not be. I'd appreciate if you could create a complete report with help for reproducing this. This issue here is about implicit joins, not ordinary left joins.

However, we're constantly improving things in jOOQ, and I remember improving things with these `into()` methods, recently. So, please do try to report a bug against the latest jOOQ version. If your version is e.g. 3.9.x, I don't think we can do much about a potential bug report.

**Comment by tom22ger** [comment]
Hi @lukaseder!

We've been continuing to have the `Ambiguous match found` error for a while on **version 3.14.15** (we can't do 3.15 bc we're still on Java 8) and we think maybe we've finally found a solution!

Here's a base reproducible scenario: we have 2 tables `dogs` and `owners` where `dogs` has a foreign key to `owners`. **Both** `dogs` and `owners`  have a column called `name`

when we make a query like this for a joined result:

```java
class DogsResult {
  private DogsRecord dogsRecord;
  private OwnersRecord ownersRecord;

  public DogsResult(DogsRecord dogsRecord, OwnersRecord ownersRecord) {
    this.dogsRecord = dogsRecord;
    this.ownersRecord = ownersRecord;
  }
}

DSL
.select()
.from(DOGS)
.leftJoin(OWNERS).on(OWNERS.ID.eq(DOGS.OWNER_ID))
.fetch(record -> new DogsResult(record.into(DOGS), record.into(OWNERS)))
```
This `record.into(DOGS)` will produce an error will produce a warning like: `Ambiguous match found for name both "dogs"."name" and "owners"."name" match.`

We've tried aliasing the tables and other solutions, but what seemed to finally fix it was very manually going through the record fields with a function that does this:

```java
   <R extends Record> R intoQualifiedTableRecord(Record record, Table<R> table) {
        return record.into(Arrays.stream(record.fields())
                .filter(field -> table.getQualifiedName().equalsIgnoreCase(field.getQualifiedName().qualifier()))
                .toArray(Field[]::new))
                .into(table);
    }
```
so in our use case:
```java
DSL
.select()
.from(DOGS)
.leftJoin(OWNERS).on(OWNERS.ID.eq(DOGS.OWNER_ID))
.fetch(record -> new DogsResult(intoQualifiedTableRecord(record, DOGS), intoQualifiedTableRecord(record, OWNERS)))
```
This way it actually uses the qualified name of the fetched record fields and matches it with the Table we're trying to do a `record.into` with, so no warning is produced!

So I guess my question is, should the `record.into(Table table)` method already do a match on the qualified table name inherently or is that specifically _not_ intended behavior? Or is this functionality already included somewhere in the package and we just don't know about it 😆 Basically, would you recommend this little helper function for our usage and others who have a similar problem, or is there another built-in system that would do this for us?

Thanks so much for taking a look!

**Comment by lukaseder** [comment]
Thanks for your message, @tom22ger. I'll look into this soon. Just a short note:

> we can't do 3.15 bc we're still on Java 8

jOOQ 3.15 still supports Java 8, only Java 6-7 support has been dropped, see the version support matrix here:
https://www.jooq.org/download/versions

**Comment by james-deee** [comment]
> Thanks for your message, @tom22ger. I'll look into this soon. Just a short note:
> 
> > we can't do 3.15 bc we're still on Java 8
> 
> jOOQ 3.15 still supports Java 8, only Java 6-7 support has been dropped, see the version support matrix here: https://www.jooq.org/download/versions

Hey @lukaseder I was wondering if you had any more insight here for us. Thanks! And yes, 3.15 does support java 8, but not for the Open Source version, which is what we are currently using.

**Comment by lukaseder** [comment]
> Hey @lukaseder I was wondering if you had any more insight here for us.

Thanks for your patience. It's on my radar, but many other issues are, too. I'll get to this one eventually.

> Thanks! And yes, 3.15 does support java 8, but not for the Open Source version, which is what we are currently using.

Why not upgrade?

**Comment by lukaseder** [comment]
Thanks again for your patience. I've had a look at your example now. In all of jOOQ 3.14 - 3.16, I couldn't reproduce such a warning. In any case, it's not related to this issue here, which is about implicit join graphs. Feel free to create a new issue with more details to reproduce (ideally an MCVE from our template: https://github.com/jOOQ/jOOQ-mcve)
