### ISSUE TITLE
Gradle example in the manual should not use MarkupBuilder to avoid issues with name

### ISSUE THREAD

**Issue by doctorpangloss** [jOOQ/jOOQ#10600]
### Use case:

JOOQ has many valuable third-party generators that rely on the `name` field in the configuration builder pattern. Setting name is idiosyncratic and error prone in Gradle as per your 3 issues.

This is a suggestion to change the examples to build the Configuration object directly.

### Possible solution you'd like to see:

Here is a third party generator example:

```
buildscript {
    ext {
        vertx_jooq_version = '5.2.0'
        postgresql_version = '42.2.16'
    }
    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath "io.github.jklingsporn:vertx-jooq-generate:$vertx_jooq_version"
        classpath "org.postgresql:postgresql:$postgresql_version"
    }
}

import org.jooq.codegen.GenerationTool
import org.jooq.meta.jaxb.*

def configuration = new Configuration()
        configuration
                .withJdbc(new Jdbc()
                        .withDriver('org.postgresql.Driver')
                        .withUrl('jdbc:postgresql://host:5432/databasename')
                        .withUser('username')
                        .withPassword('password'))
                .withGenerator(new Generator()
                        .withName('io.github.jklingsporn.vertx.jooq.generate.classic.ClassicReactiveVertxGenerator')
                        .withDatabase(new Database()
                                .withName('org.jooq.meta.postgres.PostgresDatabase')
                                .withInputSchema('public')
                                .withIncludeTables(true)
                                .withIncludeRoutines(true)
                                .withIncludePackages(false)
                                .withIncludeUDTs(true)
                                .withIncludeSequences(true)
                                .withExcludes('schema_version')
                                .withIncludes('.*'))
                        .withGenerate(new Generate()
                                .withDeprecated(false)
                                .withRecords(false)
                                .withInterfaces(true)
                                .withFluentSetters(true)
                                .withPojos(true)
                                .withDaos(true))
                        .withTarget(new Target()
                                .withPackageName('package.name')
                                .withDirectory("$projectDir/src/generated/java"))
                        .withStrategy(new Strategy()
                                .withName('io.github.jklingsporn.vertx.jooq.generate.VertxGeneratorStrategy')))

        GenerationTool.generate(configuration)
```

Observe I just create a `Configuration` object directly and there are no issues setting `name`.

It also illuminates all the steps you really need, like what to import in your buildscript.

I can probably author a more complete example, including source code generation, how to bootstrap a Postgres instance (instead of H2), Flyway, etc. which is only really possible in Gradle and shows off JOOQ a lot better than Maven does, in my opinion.

### Versions:

- jOOQ: 3.13.+
- Java: 11+
- Database (include vendor): Postgres
- OS: macOS
- JDBC Driver: org.postgresql.Driver (reactive)

**Comment by lukaseder** [comment]
Thank you very much for your request. I'm assuming you're discussing this section of the manual, and its usage of the `MarkupBuilder`:
https://www.jooq.org/doc/3.13/manual/code-generation/codegen-gradle/

Indeed, using the `MarkupBuilder` is unnecessary in this case, and adds complexity that distracts from the task at hand. I like your idea of building the `Configuration` directly using jOOQ API.

> I can probably author a more complete example, including source code generation, how to bootstrap a Postgres instance (instead of H2), Flyway, etc. which is only really possible in Gradle and shows off JOOQ a lot better than Maven does, in my opinion.

This would be great for a blog post on your own blog, not really for the jOOQ manual. Sure, we can document a few of these integration steps, but where would we even stop, and how do we make up our minds about the various opinionated choices of third party tooling? I think that's out of scope for the manual, including how to set up that vertx integration.

**Comment by lukaseder** [comment]
Fixed. Thanks again for your suggestion
