### ISSUE TITLE
offset(0) is ignored

### ISSUE THREAD

**Issue by jmcp** [jOOQ/jOOQ#10605]
I have a complex query which looks similar to this:

```sql
    WITH subq AS 
        (SELECT columnname FROM table 
          WHERE conditions)
    SELECT othercolumns,
        count(*) FROM subq
    FROM table
         WHERE conditions;
```

This was taking a while to complete (we have millions of rows), so I followed the suggestion in http://www.2ndquadrant.com/en/blog/hinting_at_postgresql/ to add `OFFSET 0` to the subquery in the CTE. In DBeaver, this form produced a 20x speedup compared to no `OFFSET 0`:

```sql
    WITH subq AS 
        (SELECT columnname FROM table 
          WHERE conditions
           OFFSET 0)
    SELECT othercolumns,
        count(*) FROM subq
    FROM table
         WHERE conditions;
```

### Expected behavior and actual behavior:

Expected: The `OFFSET 0` is included in the SQL which jOOQ generates
Actual behaviour: there is no `OFFSET 0` in the generated SQL (confirmed first with single-stepping through intelliJ, and secondly by enabling jOOQ debug logging).

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

```java
   CommonTableExpression<Record1<Integer>> withClause = DSL.name(withClauseName)
                .fields(withClauseField)
                .as(select(tableName.columnName)
                .from(tableName)
                .where(conditions)
                .offset(0)
        );

        Field<Integer> totalResults = DSL.field(context.select(count(asterisk()))
            .from(withClause)
            .limit(1)
        ).as("total_result");

        List<Entity> result = context.with(withClause)
            .select(fields)
            .from(tableName)
            .innerJoin(withClause)
                .on(withClause.field(withClauseField, Integer.class).eq(tableName.columnName))
            .groupBy(tableName.columnName)
            .orderBy(createOrderFields(Parameters))
            .limit(pageable.getSize())
            .offset(offset)
            .fetchInto(Entity.class);
```

then enable logging (we're using logback with spring-boot), run the application and send a query.

### Versions:

- jOOQ: 3.11.10
- Java: Java 8
- Database (include vendor): PostgreSQL 9.6
- OS: Linux (Centos 7.6)
- JDBC Driver (include name if inofficial driver):  org.postgresql.postgresql 42.2.5

**Comment by lukaseder** [comment]
Thank you very much for your report. That's a weird, historic "optimisation". Our stance is to (by default) always generate whatever users pass to the API, assuming it may have been intentional, as it is in your case.

I can reproduce this with a simple query:

```sql
System.out.println(using(POSTGRES).renderInlined(selectOne().offset(0)));
```

A workaround seems to be to use `DSL.inline(0)`:

```sql
System.out.println(using(POSTGRES).renderInlined(selectOne().offset(inline(0))));
```

**Comment by lukaseder** [comment]
The optimisation has been introduced with https://github.com/jOOQ/jOOQ/issues/1129 in jOOQ 2.0.4, almost a decade ago, without any comments regarding why. There probably isn't a good reason for it.

**Comment by lukaseder** [comment]
There's a slight chance of someone depending on the current behaviour (it would be better not to call `offset` instead), which is why I won't backport this fix to 3.13.5.

**Comment by lukaseder** [comment]
Fixed for 3.14.0. Thanks again for your report!

**Comment by McBofh** [comment]
Thankyou so very very much for the workaround, I've been incredibly frustrated by it.

**Comment by jmcp** [comment]
Thankyou so very, very much for this workaround, I've been really frustrated by the behaviour. Looking forward to 3.14!

**Comment by lukaseder** [comment]
Note that you can always patch generated SQL using the [`ExecuteListener` SPI](https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-execute-listeners/) and a regex quite easily, or use [plain SQL templating](https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/), which is especially useful in such edge cases like this one here, also when a SQL feature isn't supported by jOOQ.

**Comment by jmcp** [comment]
Quick followup to close the loop: we deployed this app with the .offset(inline(0)) to our environment yesterday and QE is reporting a speedup of between 19 and 58x across a range of queries that were previously taking 10s of seconds to minutes. Thankyou again!

**Comment by lukaseder** [comment]
Great to hear, thanks for following up, @jmcp

**Comment by lukaseder** [comment]
Some additional background info: The optimisation was part of a feature where `OFFSET 0 LIMIT :x FOR UPDATE` was still possible when using an emulation e.g. in Db2, and possibly some others, via `ROW_NUMBER()` filtering (in Db2, `OFFSET` needs to be emulated, whereas `LIMIT` is supported natively via standard SQL `FETCH FIRST`).

I don't remember why this optimisation was made, it must have been some very early jOOQ 1.x versions.
