### ISSUE TITLE
Add support for CockroachDB CREATE SCHEMA et. al

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10626]
CockroachDB has introduced support for user-defined schemas (other than `public`): https://github.com/cockroachdb/cockroach/issues/26443#issuecomment-687874862

We should add support throughout the jOOQ API as well, including (to be investigated):

- [x] `CREATE SCHEMA`
- [x] `ALTER SCHEMA`
- [x] `DROP SCHEMA`

**Comment by lukaseder** [comment]
`cockroachdb/cockroach:latest-v20.2` is available from Docker Hub, so we can ship this.

**Comment by lukaseder** [comment]
Nope that tag doesn't work on my machine. I'll wait...

**Comment by vy-ton** [comment]
@lukaseder The `cockroachdb/cockroach:v20.2.2` tag should work

**Comment by lukaseder** [comment]
Thanks for the ping @vy-ton. I think my mistake was to use `start` instead of `start-single-node`. It appears things have changed in the meantime...
