### ISSUE TITLE
Backticks aren't used for for field names in "CREATE TABLE" queries (MySQL)

### ISSUE THREAD

**Issue by Perzan** [jOOQ/jOOQ#10620]
### Expected behavior and actual behavior:
It is supposed to surround the column field names ins the query with a `back-tick`.
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
```java
Class.forName("com.mysql.cj.jdbc.Driver");
Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306", "root", "password");
		
DSLContext dsl = DSL.using(connection, SQLDialect.MYSQL);
		
Field<String> keyField = DSL.field("key", SQLDataType.VARCHAR.length(700).nullable(false));
		
String query = dsl.createTable(DSL.name("testdb", "MyTable"))
.column(keyField)
.constraint(DSL.constraint("pk_key").primaryKey(keyField))
.getSQL();
		
System.out.println(query);
	
dsl.execute(query);
```
For it to work, I have to specify back-ticks around "key". It's not a huge deal, but I think something like this should be automated with the DSL.

### Versions:

- jOOQ: 3.13.4
- Java: 14.0.1
- Database (include vendor):
- OS: Windows 10 Pro (1909)
- JDBC Driver (include name if no official driver): com.mysql.cj.jdbc.Driver

**Comment by lukaseder** [comment]
Thank you very much for your request.

`DSL.field(String)` gives access to the plain SQL templating API (https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/), not to quoted identifiers. Please use `DSL.field(Name)`, instead:

```java
Field<String> keyField = DSL.field(DSL.name("key"), SQLDataType.VARCHAR.length(700).nullable(false));
```
