### ISSUE TITLE
Postgres predicate "IN" optimization

### ISSUE THREAD

**Issue by demichej** [jOOQ/jOOQ#10629]
### Your question:

Hello, I was wondering if there existed something already where I can tell jOOQ to use a Postgres trick with optimizing a large "IN" in the where clause. We've found that when we do large IN queries they can be slow, and that there's a trick that can be utilized to make it very fast (I think Postgres creates a temp table under the covers): https://postgres.cz/wiki/PostgreSQL_SQL_Tricks_I#Predicate_IN_optimalization

Is this something that is provided in jOOQ at all? Do you foresee this being useful? If not, would you be able to point in a place that I might be able to override this behavior on our end for IN queries at all? Thanks!

### Versions:

- jOOQ: 3.13.1
- Java: 8
- Database (include vendor): Postgres open source 10
- OS: Linux

**Comment by lukaseder** [comment]
Thank you very much for your message.

That is a fun and weird "optimisation", that definitely needs some commenting. There obviously shouldn't be any significant performance difference between the two approaches. Alas, there often is.

Coincidentally, I've just been asked yesterday about a similar optimisation using array binds:
https://twitter.com/dmitrygusev/status/1305541817136488450

... which I can confirm (in a benchmark, please reproduce this first on your system to confirm as well) works once IN lists reach a certain size:
https://blog.jooq.org/2018/04/13/when-using-bind-variables-is-not-enough-dynamic-in-lists/

You can explicitly use this optimisation in jOOQ by using `Field.eq(any(array))`

You can implement a workaround for your `IN` queries. I've seen customers do that for Oracle (which suffers from entirely different problems, namely cursor cache contention issues), when using large `IN` lists. For example, you can write a utility like this:

```java
public static <T> Condition in(Field<T> field, T... values) {
    return values.length > 64
        ? field.eq(any(values))
        : field.in(values);
}
```

But please, again, do confirm that this makes a significant enough difference on your systems, first. Also, there are always other, more laborious approaches using temporary tables, for example. Just batch-insert all the values in that temp-table, and then semi-join it as such:

```sql
SELECT *
FROM t
WHERE col IN (SELECT value FROM temp_table);
```

I've seen this outperform both of the above approaches if the list gets very large.

**Comment by lukaseder** [comment]
I keep forgetting. The *best* solution is not to pass around large lists, if your logic allows for doing that. In many cases, you had a query producing this list in the first place, like:

```sql
SELECT value FROM t2 WHERE some_predicate
```

That list is sent to the client and back to the server. Instead of sending the list of values, why not just re-use the above `SELECT`?

```sql
SELECT *
FROM t1
WHERE col IN (SELECT value FROM t2 WHERE some_predicate)
```

If that's possible, it's always the best solution.

**Comment by lukaseder** [comment]
I forgot about the `VALUES(...)` approach. You currently cannot do this with jOOQ out of the box. You'd have to resort to using plain SQL templating to get the `VALUES()` constructor in that predicate:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

We support `VALUES`, but not as a `Select` subtype (required for usage in `IN`, see https://github.com/jOOQ/jOOQ/issues/5871), only as a `Table` subtype (required for usage in `FROM`). You could use

```java
in(selectFrom(values(...)))
```

Not sure if the same optimisation can be leveraged this way. Try it.

**Comment by demichej** [comment]
> I keep forgetting. The _best_ solution is not to pass around large lists, if your logic allows for doing that. In many cases, you had a query producing this list in the first place, like:
> 
> ```sql
> SELECT value FROM t2 WHERE some_predicate
> ```
> 
> That list is sent to the client and back to the server. Instead of sending the list of values, why not just re-use the above `SELE
> 
> ```sql
> SELECT *
> FROM t1
> WHERE col IN (SELECT value FROM t2 WHERE some_predicate)
> ```
> 
> If that's possible, it's always the best solution.

Thanks for all the replies, Lukas. It's not very easy in our current model, but that's something that maybe we'll start switching to. I think we'd probably have to return both a result and the select used in a wrapper class of some kind in our world. But certainly something to consider. Thanks again!

**Comment by lukaseder** [comment]
@demichej I think I've once seen someone generate the SQL string using jOOQ, store that in some session table in the database, and later load it again to use it in the `IN` predicate :)

Constructive solution!
