### ISSUE TITLE
Failing constraint exclusion with partitioned tables in Postgres 12.4 - 10.2

### ISSUE THREAD

**Issue by monosoul** [jOOQ/jOOQ#10624]
#### Given:
A table in PG12 partitioned by timestamp with tz.

#### When:
Executing a prepared statement having the timestamp condition ([to apply constraint exclusion](https://www.postgresql.org/docs/12/ddl-partitioning.html#DDL-PARTITIONING-CONSTRAINT-EXCLUSION)).

#### Expected behavior:
Jooq passes timestamp parameters to the prepared statement as timestamp and **constraint exclusion works**.

#### Actual behavior:
Jooq passes timestamp parameters to the prepared statement as string and **constraint exclusion doesn't work**.

### Steps to reproduce the problem:

- Create a table in PG12 partitioned by timestamp with tz;
- Run an update query against this table with Jooq, including primary key condition and timestamp conditions (to apply constraint exclusion).

### [MCVE Repository:](https://github.com/monosoul/jooq-postgres-jdbc-timestamp-wrong-type)
There are 2 branches in the repository:

- [`master`](https://github.com/monosoul/jooq-postgres-jdbc-timestamp-wrong-type/tree/master) - contains the issue example with a failing test:
  * [execution plan](https://github.com/monosoul/jooq-postgres-jdbc-timestamp-wrong-type/runs/1103356936#step:5:934) showing that constraint exclusion is not applied;
  * [JDBC log line](https://github.com/monosoul/jooq-postgres-jdbc-timestamp-wrong-type/runs/1103356936#step:5:1055) showing that the parameters are passed as strings;
- [`workaround`](https://github.com/monosoul/jooq-postgres-jdbc-timestamp-wrong-type/tree/workaround) - contains workaround for the issue (a very ugly one):
  * [execution plan](https://github.com/monosoul/jooq-postgres-jdbc-timestamp-wrong-type/runs/1103361373#step:5:940) showing that constraint exclusion is applied;
  * [JDBC log line](https://github.com/monosoul/jooq-postgres-jdbc-timestamp-wrong-type/runs/1103361373#step:5:1053) showing that the parameters are passed as unspecified.

### Versions:

- jOOQ: 3.13.4
- Java: 11
- Database: PostgreSQL 12.4 (also 11, 10)
- OS: Ubuntu Linux 20.04
- JDBC Driver: org.postgresql.Driver (`org.postgresql:postgresql:42.2.14`)

**Comment by lukaseder** [comment]
Thank you very much for your report. This will probably be solved with #9902. I'll look into prioritising this fix for jOOQ 3.14, still. The workaround for the time being is to implement a custom data type binding for these types, which you did.

**Comment by lukaseder** [comment]
https://github.com/jOOQ/jOOQ/issues/9902 is implemented for 3.14 as an opt in feature. I'd be curious to see if this fixes your issue here

**Comment by monosoul** [comment]
yeah, I'll give it a try once 3.14 is available at maven central

**Comment by lukaseder** [comment]
Alright. I'm assuming this is fixed. Feel free to reopen if not.
