### ISSUE TITLE
Types mismatching at view code-generation

### ISSUE THREAD

**Issue by vendelieu** [jOOQ/jOOQ#10639]
### Expected behavior and actual behavior:
that part of sql code with using `array_agg` on custom composite type
![изображение](https://user-images.githubusercontent.com/3987067/93404368-b394ab80-f892-11ea-92e5-d75732bfdfcd.png)
generates wrong code
![изображение](https://user-images.githubusercontent.com/3987067/93404292-7c25ff00-f892-11ea-93e4-5fc20d70f30b.png)

types doesn't match Record trying to override Interface
![изображение](https://user-images.githubusercontent.com/3987067/93404516-0f5f3480-f893-11ea-8d42-ea38226d43c3.png)
![изображение](https://user-images.githubusercontent.com/3987067/93404532-1b4af680-f893-11ea-840a-4c46a8be83f3.png)

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
- create composite type
- create view which uses it with `array_agg`, thats how i get it

### Versions:

- jOOQ: 3.13.4
- Java: 12
- Kotlin: 1.4.10
- Database (include vendor): Postgres 12
- OS: ubuntu
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.9

**Comment by lukaseder** [comment]
Thank you very much for your report. Can you please post your code generation configuration? I'm assuming you turned on quite a few features. I'm guessing that the `<interfaces/>` flag doesn't play well with UDT arrays. Do you need `<interfaces/>` to be generated?

Related issue: https://github.com/jOOQ/jOOQ/issues/8209

**Comment by Vendelieu** [comment]
yep, I turn off interfaces generating then it goes to work, but is it posible to work with turned on?

**Comment by lukaseder** [comment]
You'd probably have to patch `JavaGenerator` to make it work.

We've had numerous issues with subtype polymorphism edge cases related to these interfaces in the past, to the point of where I think that a deprecation might not be a bad idea: https://github.com/jOOQ/jOOQ/issues/10509. The feature is of relatively limited usefulness but causes a lot of headaches and complexity in the code generator.

Why do you need `<interfaces/>` on your side?

**Comment by Vendelieu** [comment]
to make result not modifiable in some cases

**Comment by lukaseder** [comment]
This has been fixed in jOOQ 3.20 via:

- https://github.com/jOOQ/jOOQ/issues/17760
- https://github.com/jOOQ/jOOQ/issues/8209
- https://github.com/jOOQ/jOOQ/issues/644

The fix relied on #644 which was quite a big change to the code generator, which is why this won't be backported.

**Comment by Nthalk** [comment]
> You'd probably have to patch `JavaGenerator` to make it work.
> 
> We've had numerous issues with subtype polymorphism edge cases related to these interfaces in the past, to the point of where I think that a deprecation might not be a bad idea: #10509. The feature is of relatively limited usefulness but causes a lot of headaches and complexity in the code generator.
> 
> Why do you need `<interfaces/>` on your side?

When developing services, you sometimes have a record, and sometimes have a pojo (if you get an object from a service that is trying to hide it's db connection, like a remote bean). 

It's easier to just use the interface on the parameters and returns to capture both cases, without having lots of pojo untypedish maps everywhere.

This could be resolved by having the TableRecordImpl extend the pojo if pojo's were generated.

If that' snot possible, then if the TableRecordImpl also implemented a WithPojo<Pojo> interface that had a `toPojo` method, we wouldn't  have the chance to mess up the class name when tables names look distressingly similar.

**Comment by lukaseder** [comment]
> This could be resolved by having the TableRecordImpl extend the pojo if pojo's were generated.

That really wouldn't work very well. Just check out the `Record` type hierarchy to see what I mean.

> If that' snot possible, then if the TableRecordImpl also implemented a WithPojo interface that had a `toPojo` method, we wouldn't have the chance to mess up the class name when tables names look distressingly similar.

What's missing from the `from()` and `into()` methods?

**Comment by Nthalk** [comment]
> What's missing from the from() and into() methods?

What's missing from them is unchecked type mapping. I get nervous when I see `from()` and `into()` being used, because it's only faith that holds the contract together, and there's no way I have found to write a typed extension function on `TableRecordImpl` that can get a typed access to whatever Pojo was generated.

Having that `TableRecordImpl` also include a `toPojo()` method when `pojos` are enabled and maybe a member method `fromPojo(pojo)` that would enforce such types would be possible.

As it is, I have a post-generation step that I use for my generation, and I figured it would be useful to others to not have to do this, as there is limited support in the GeneratorStrategies


```
Path("db/src/main/gen").toFile().walkTopDown().forEach { pojoFile ->
      if (pojoFile.isFile) {
        var pojoContent = pojoFile.readText()
        var changed = false
        if (!pojoContent.startsWith("// @formatter:off")) {
          pojoContent = "// @formatter:off\n$pojoContent"
          changed = true
        }
        // If we are in the tables/pojos directory
        val pojoDir = pojoFile.parentFile
        if (pojoDir.name == "pojos") {
          val recordDir = File(pojoDir.parent, "records")
          val recordName = pojoFile.nameWithoutExtension + "Record"
          val recordFile = File(recordDir, "$recordName.java")
          var recordText = recordFile.readText()
          val pojoPackageName = pojoContent.substringAfter("package ").substringBefore(";")
          val pojoFullyQualified = pojoPackageName +"."+ pojoFile.nameWithoutExtension
          val generatedContent = """
              // START_GENERATE_POJO_METHODS
              public $recordName fromPojo($pojoFullyQualified pojo) {
                from(pojo);
                return this;
              }
              public $pojoFullyQualified toPojo() {
                $pojoFullyQualified pojo = new $pojoFullyQualified();
                into(pojo);
                return pojo;
              }
              // END_GENERATE_POJO_METHODS
            """.replaceIndent("    ")
          if (!recordText.contains(generatedContent)) {
            // If we have a START_GENERATE_POJO_METHODS comment, delete it first
            if(recordText.contains("// START_GENERATE_POJO_METHODS")) {
              val start = recordText.indexOf("// START_GENERATE_POJO_METHODS")
              val end = recordText.indexOf("// END_GENERATE_POJO_METHODS") + "// END_GENERATE_POJO_METHODS".length
              recordText = recordText.substring(0, start) + recordText.substring(end)
            }
            val insertIndex = recordText.indexOf("private static final long serialVersionUID ").let { index ->
              recordText.indexOf("\n", index) + 1
            }
            val newRecordText = recordText.substring(0, insertIndex) + generatedContent + recordText.substring(insertIndex)
            recordFile.writeText(newRecordText)
          }
        }
```

Generates:
```
// START_GENERATE_POJO_METHODS
    public UserRecord fromPojo(com.iodesystems.db.models.tables.pojos.User pojo) {
      from(pojo);
      return this;
    }
    public com.iodesystems.db.models.tables.pojos.User toPojo() {
      com.iodesystems.db.models.tables.pojos.User pojo = new com.iodesystems.db.models.tables.pojos.User();
      into(pojo);
      return pojo;
    }
    // END_GENERATE_POJO_METHODS
```

**Comment by lukaseder** [comment]
> > What's missing from the from() and into() methods?
> 
> What's missing from them is unchecked type mapping. I get nervous when I see `from()` and `into()` being used, because it's only faith that holds the contract together

I meant the generated ones. I just realised, they're being generated only if you activate interfaces.
