### ISSUE TITLE
ForcedType on BIGINT column makes it impossible to use DSL.sum()

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#10649]
### Expected behavior

When using a forced type on a BIGINT (or any other numeric) column, I would expect the have a sum function that would be able to accept `TABLE.FIELD.as("abc")` for such a column.

### Actual behavior

Unfortunately this breaks as DSL.sum() is defined as `public static AggregateFunction<BigDecimal> sum(Field<? extends Number> field)` which assumes a class inheriting from `Number`.

### Possible solutions

- Relax the restrictions on the parameter type
- Generate a custom sum function as part of the code generation phase

### Versions

- jOOQ: 3.13.4

**Comment by lukaseder** [comment]
All of the numeric column types produce a `java.lang.Number` subtype, so you can always pass them to `DSL.sum()`...

What are you doing that this doesn't work for you?

**Comment by axelfontaine** [comment]
The ForcedType I use doesn't inherit from `java.lang.Number`.

**Comment by axelfontaine** [comment]
Also current calling `.fetchOne().value1()` on this query returns a `BigDecimal`, which also isn't what I want. I want my forcedType instead.

**Comment by lukaseder** [comment]
Looking at this more thoroughly, for the record, this is *much* more significant than just finding a quick solution for `DSL.sum()`. A big amount of jOOQ API hard-codes the `Number`, `Date`, `Temporal`, and `String` types. We'd first have to identify in what cases a forced type (e.g. from a domain, or jOOQ 3.14 embeddable type) could still be expected to represent the underlying technical type in things like arithmetic, string manipulation, etc.

For example, a lot of forced types don't actually lend themselves to further processing within the database. Examples are:

- Key values (which can be turned into embeddable keys starting from jOOQ 3.14: https://github.com/jOOQ/jOOQ/issues/6124)
- Other types of embeddable types (https://github.com/jOOQ/jOOQ/issues/2530)
- Encrypted data

Some forced types, however, still represent the underlying numeric value. From your previous issues, I'm assuming you have things in mind like `distance`, `weight`, etc., which are good candidates for standard SQL `DOMAIN` types, in case of which arithmetic is really useful.

What specific domain types / forced types did you have in mind?

**Comment by axelfontaine** [comment]
Yes, those indeed. Distance, Heart rate, ... Things that can either be summed, averaged or min/maxed in the database.
