### ISSUE TITLE
Support empty INSERT .. VALUES() clause via DEFAULT VALUES

### ISSUE THREAD

**Issue by the-kenny** [jOOQ/jOOQ#10655]
### Expected behavior

```sql
create table foo(id integer primary key, value string);
```

```scala
dsl.insertInto(table("foo"))
    .columns()
    .values()
    .returning(field("id"))
    .fetchOne()
```

should insert an empty row (`id` generated by db, `value` being `NULL`) and return a record containing the generated `id`.

### Actual behavior

No insert is executed. I have to add `.defaultValues()` for correct execution.

I can imagine that this *might* be expected behavior, but I find it very confusing. I'm working on a fairly complex project that auto-generates SQL INSERT statements and this behavior was caught by my test-suite. 

I can easily work around the issue in various ways, so closing this issue with "It's expected behavior" is fine for me :-)

### Steps to reproduce the problem

I'm sorry for the Scala MCVE. If you prefer one in Java, please let me know.

```scala
import org.jooq.DSLContext
import org.jooq.impl.DSL
import DSL._
object SqliteTestApp extends App {
  val db = DSL.using("jdbc:sqlite::memory:")
  db.execute("create table foo(id integer primary key, value string);")

  val record = db.insertInto(table("foo"))
    .columns()
    .values()
    .returningResult(field("id"))
    .fetchOne()

  println(record) // wrong: null
  println(db.select(count()).from(table("foo")).fetchOne()) // count() is 0

  val record2 = db.insertInto(table("foo"))
    .columns(field("value"))
    .values("foo")
    .returningResult(field("id"))
    .fetchOne()

  println(record2) // correct 'id: 1'

  val record3 = db.insertInto(table("foo"))
    .defaultValues()
    .returningResult(field("id"))
    .fetchOne()

  println(record3) // correct 'id: 1'
}

```

### Versions

- jOOQ: 3.13.4
- Java: openjdk version "14.0.2" 2020-07-14
- Database (include vendor): sqlite-jdbc 3.32.3.2
- OS: macOS 10.15.6
- JDBC Driver (include name if inofficial driver): `org.xerial/sqlite-jdbc:3.32.3.2`

**Comment by lukaseder** [comment]
Thanks a lot for your feedback. The Scala MCVE is fine :)

Curiously, we've already fixed this in the parser: https://github.com/jOOQ/jOOQ/issues/6936, when it should have been fixed in the SQL generation logic, instead. Will look into this soon.

**Comment by lukaseder** [comment]
Nice, so we can remove parts of the logic from the parser that was introduced in #6936. Thanks again for the suggestion.
