### ISSUE TITLE
Add WITH RECURSIVE emulations for GENERATE_SERIES, where available

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10660]
We currently support `GENERATE_SERIES`:

- Natively on PostgreSQL category dialects
- Emulated using `CONNECT BY` on Oracle and CUBRID (and Informix, soon: #10659)

On those other dialects that support `WITH RECURSIVE`, we should use that to emulate `GENERATE_SERIES`. If `WITH` cannot appear in derived tables, we can emit a top level CTE using the mechanism introduced in #3607

**Comment by lukaseder** [comment]
H2 seems to support `GENERATE_SERIES`, but doesn't document it.

**Comment by lukaseder** [comment]
See also #10661, where the emulating derived tables can enforce an alias.

**Comment by katzyn** [comment]
> H2 seems to support GENERATE_SERIES, but doesn't document it.

I think jOOQ should generate documented `SYSTEM_RANGE(startBigint, endBigint [, stepBigint])` for H2 instead:
https://h2database.com/html/systemtables.html#range_table

`system_range` may be restricted to PostgreSQL compatibility mode in the future.

**Comment by lukaseder** [comment]
Thanks a lot for the hint, @katzyn. That makes sense. We'll generate `SYSTEM_RANGE` instead of `GENERATE_SERIES`
