### ISSUE TITLE
getName upper/lower case preference mismatch with renderNameCase

### ISSUE THREAD

**Issue by wisnesky** [jOOQ/jOOQ#10681]
### Expected behavior

I would expect getName() to return a lower case string for any JOOQ artifact created from a DSL context where RenderNameCase was set to LOWER in the associated Settings.

### Actual behavior

Table names are being upper-cased by JOOQ somewhere along the getName() pathway; this behavior happens even on lower case input files.

### Steps to reproduce the problem

```java
Settings set = new Settings().withRenderNameCase(RenderNameCase.LOWER); 
DSLContext sd = DSL.using(SQLDialect.H2, set);
Meta sm = sd.meta( "create table foo(id integer);" ); 
System.out.println(sm); //foo is lower case
System.out.println(sm.getTables().get(0).getName()); //foo is upper case
```

### Versions

- jOOQ: 3.13
- Java: 14
- Database (include vendor): H2
- OS: mac
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your message. The `RenderNameCase` property is about the generated names when you generate SQL. You can see this when you call `sm.toString()`, which you did. But it doesn't affect the case of the meta data when we parse the SQL. For that, please use `Settings.parseNameCase`
