### ISSUE TITLE
Translator should ignore unknown functions

### ISSUE THREAD

**Issue by UCFKnights83** [jOOQ/jOOQ#10680]
Receiving "Unknown function: [4:13]" when the query contains a custom function. Would be good to have converter not fail on an unknown function but rather convert everything it can. It would then return the query with all the conversions it was able to make and let the user fix any custom functions manually.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. We support this in jOOQ, but haven't activated the flag in the translator website yet. In case you are using jOOQ directly, please use `Settings.parseUnknownFunctions = ParseUnknownFunctions.IGNORE`.

**Comment by lukaseder** [comment]
I fixed this in the translator.  Thanks again for your report.
