### ISSUE TITLE
Add support for multiple MERGE .. WHEN NOT MATCHED AND { condition }

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10715]
jOOQ 3.14 introduced support for multiple `WHEN MATCHED AND` clauses to the `MERGE` statement (#7291). It's also possible to supply multiple `WHEN NOT MATCHED AND` clauses in some dialects, which we should support and emulate. More investigations will follow

**Comment by kaijiezhang0319** [comment]
@lukaseder   Hello Lukas, is there any update about that feature support ?  i meet exactly same issue with you, and hope jooq community can support that.   Thanks

**Comment by lukaseder** [comment]
Thanks for your feedback, @kaijiezhang0319. It hasn't been the most urgent feature, with little community feedback yet. You can speed this up if you could explain, in depth, what specific use-cases this clause would satisfy?

**Comment by lukaseder** [comment]
This will be done in jOOQ 3.20 along with:

- https://github.com/jOOQ/jOOQ/issues/10059

**Comment by lukaseder** [comment]
The `AND` clause can be emulated just like the `AND` clause of the `WHEN MATCHED` clause, by translating the multiple `WHEN NOT MATCHED` clauses into a big `CASE` expression.

**Comment by lukaseder** [comment]
Emulation tasks:

- https://github.com/jOOQ/jOOQ/issues/17776
- https://github.com/jOOQ/jOOQ/issues/17777

**Comment by lukaseder** [comment]
Implemented in version 3.20.0
