### ISSUE TITLE
DDLDatabase Error when update constraint

### ISSUE THREAD

**Issue by iz8wok** [jOOQ/jOOQ#10739]
hi everyone,

I have a folder where it contains all the initialization and modification sql files V1__init.sql etc V2_addColumnsUser.sql
I created the file V3_update_costraint_user.sql to update the costraint, the file contains:
ALTER TABLE dc1. "Accepted_values" DROP CONSTRAINT "accepted_values_created_by_fkey", ADD CONSTRAINT "accepted_values_created_by_fkey" FOREIGN KEY (created_by) REFERENCES main_schema. "User" (user_id) ON DELETE CASCADE ON; UPDATE CASCADE ON;

when I restart the server it generates this error:
[ERROR] DDLDatabase Error: Your SQL string could not be parsed or simulated. This may have a variety of reasons, including:
- The jOOQ parser doesn't understand your SQL
- The jOOQ DDL simulation logic (translating to H2) cannot simulate your SQL
If you think this is a bug or a feature worth requesting, please report it here: https://github.com/jOOQ/jOOQ/issues/new/choose
As a workaround, you can use the Settings.parseIgnoreComments syntax documented here:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-parser/
[ERROR] An exception occurred while parsing script source: src / main / resources / db / migration / *. Please report this error to https://github.com/jOOQ/jOOQ/issues/new
org.jooq.impl.ParserException: Unexpected token or missing query delimiter: [1:85] ... DROP CONSTRAINT "accepted_values_created_by_fkey" [*], ADD CONSTRAINT "accepted_values_created_by_fkey" FOREIGN KEY (created_by) REFE ...

do I need to change the path <value> src / main / resources / db / migration / * </value> ?

### Versions:
- jOOQ: 3.12.2
- Java:13.0.1
- Database (include vendor): postgresql
- OS: Mac os

Thanks

**Comment by lukaseder** [comment]
Thanks a lot for your report. This is a limitation in our parser and query object model: https://github.com/jOOQ/jOOQ/issues/8846.

We currently don't support `ALTER TABLE` statements that modify multiple objects in one go. In order to use the `DDLDatabase`, you have to rewrite your statement to multiple equivalent statements:

```sql
ALTER TABLE dc1. "Accepted_values" DROP CONSTRAINT "accepted_values_created_by_fkey";
ALTER TABLE dc1. "Accepted_values" ADD CONSTRAINT "accepted_values_created_by_fkey" FOREIGN KEY (created_by) REFERENCES main_schema. "User" (user_id) ON DELETE CASCADE ON UPDATE CASCADE;
```

**Comment by lukaseder** [comment]
We'll support the feature in the parser and add an error message hinting at #8846

**Comment by iz8wok** [comment]
Thanks

Il giorno mer 14 ott 2020 alle ore 11:45 Lukas Eder <
notifications@github.com> ha scritto:

**Comment by iz8wok** [comment]
Another problem
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.12.2:generate (default) on project sample-manager: Error running jOOQ code generation tool: Error while exporting schema: SQL [alter table "dc1"."views_columns" drop constraint "views_columns_id_fkey"]; Constraint "views_columns_id_fkey" not found; SQL statement:
[ERROR] alter table "dc1"."views_columns" drop constraint "views_columns_id_fkey" [90057-200]

**Comment by lukaseder** [comment]
Thank you very much for your message, @iz8wok. Can you please open up a new issue with a full example on how to reproduce this issue? Specifically, why was the constraint not found? In your script, it would have to have been created before that section
