### ISSUE TITLE
getting "type does not exist" when calling a procedure with a view record as an input parameter

### ISSUE THREAD

**Issue by jaromor** [jOOQ/jOOQ#10755]
This is the header of my procedure:
```
CREATE FUNCTION web.update_personal_data(personal_data view_personal_data) RETURNS boolean
    LANGUAGE plpgsql
AS $$
DECLARE
...
```

First I tried making the call via the generated class UpdatePersonalData and got following:
_`org.postgresql.util.PSQLException: ERROR: type "view_personal_data" does not exist
  Position: 110`_

So I tried if maybe qualifying the input parameter type in the procedure declaration would help:
```
CREATE FUNCTION web.update_personal_data(personal_data "web"."view_personal_data") RETURNS boolean
    LANGUAGE plpgsql
AS $$
DECLARE
...
```
...no difference.

The procedure works though when called from within an UPDATE-trigger I have on the view:
```
CREATE FUNCTION web.update_user_personal_data() RETURNS trigger
    LANGUAGE plpgsql
AS
$$
BEGIN
    PERFORM web.update_personal_data(NEW);
    RETURN NEW;
END;
$$;

CREATE TRIGGER update_user_personal_data
    INSTEAD OF UPDATE ON web.view_personal_data
    FOR EACH ROW
EXECUTE PROCEDURE web.update_user_personal_data();
```

So I tried to execute the call using the query I see during the debug, attempting to "enforce" the schema qualifier like this":

`getWriteDsl().query("select \"update_personal_data\" from \"web\".\"update_personal_data\"(\"personal_data\" := ?::\"web\".\"view_personal_data\")", record).execute()`

Not surprisingly, my qualified cast to "web"."view_personal_data" got _pre-casted_ with an unqualified reference again:
_`SQL [select "update_personal_data" from "web"."update_personal_data"("personal_data" := ?::"view_personal_data"::"web"."view_personal_data")]; ERROR: type "view_personal_data" does not exist
  Position: 88`_

Of course, I am not sure the lack of schema reference in the actual query is the issue.

### Versions

- jOOQ: 3.13.5
- Java: OpenJDK 14.0.2
- Database (include vendor): Postgres 11-alpine
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.6

**Comment by lukaseder** [comment]
Thanks for your report. We'll look into this soon.

As a workaround, you might be able to patch the generated SQL string using an `ExecuteListener`, e.g. by using a regular expression in the `ExecuteListener::renderEnd` event.

**Comment by lukaseder** [comment]
Finally got around to testing this, with this schema:

```sql
CREATE VIEW v_10755 (a, b) AS SELECT 1, 2;
CREATE FUNCTION f_10755 (v v_10755) RETURNS boolean
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN TRUE;
END $$;
```

And then this code:

```java

    @Test
    public void testPostgresFunctionAcceptingView() throws Exception {
        assertTrue(Routines.f_10755(configuration(), new V_10755Record(1, 2)));
    }
```

This is being executed:

```sql
select "f_10755"
from "public"."f_10755"("v" := cast(row(1, 2) as "public"."v_10755"))
```

I vaguely remember such issues having been fixed recently. Closing as works for me.
