### ISSUE TITLE
Compilation errors in KotlinGenerator generated classes when tables have array types

### ISSUE THREAD

**Issue by gregopet** [jOOQ/jOOQ#10768]
### Expected behavior

Model classes should compile

### Actual behavior

Model classes don't compile

### Steps to reproduce the problem

Run codegen against a database that contains a column of type `int[]`. Generated Kotlin code will not compile. The error is:

```
Type mismatch: inferred type is Array<(out) Int!>! but Array<Integer?>? was expected
Type mismatch: inferred type is Array<Integer?>? but Array<(out) Int!>! was expected
Type mismatch: inferred type is TableField<HamburgerRecord!, Array<(out) Int!>!>! but TableField<HamburgerRecord, Array<Integer?>?> was expected
```

..and they all refer to this line:

```kotlin
val CHEESE_WIDTH: TableField<HamburgerRecord, Array<java.lang.Integer?>?> = createField(DSL.name("cheese_width"), SQLDataType.INTEGER.getArrayDataType(), this, "")
```

If I change the `java.lang.Integer` into `Int`, the code compiles.

My generator config is:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.13.0.xsd">
    <jdbc>
    <driver>org.postgresql.Driver</driver>
    <url>jdbc:postgresql://$dbHost:$dbPort/$dbName</url>
    <user>$dbUser</user>
    </jdbc>

    <generator>
    <name>org.jooq.codegen.KotlinGenerator</name>
    <database>
        <name>org.jooq.meta.postgres.PostgresDatabase</name>
        <inputSchema>public</inputSchema>

        <!-- All elements that are generated from your schema (A Java regular expression.
            Use the pipe to separate several expressions) Watch out for
            case-sensitivity. Depending on your database, this might be
            important!
            
            You can create case-insensitive regular expressions using this syntax: (?i:expr)
            
            Whitespace is ignored and comments are possible.
            -->
        <includes>.*</includes>

        <!-- All elements that are excluded from your schema (A Java regular expression.
            Use the pipe to separate several expressions). Excludes match before
            includes, i.e. excludes have a higher priority -->
        <excludes>flyway_schema_history</excludes>
    </database>

    <generate>
        <!-- Generation flags: See advanced configuration properties -->
    </generate>

    <target>
        <packageName>dev.gregopet.blabla</packageName>
        <directory>${projectDir}/src/main/kotlin</directory>
    </target>
    </generator>
</configuration>
```

Whole project (including generated code) can be [found here](https://github.com/gregopet/jooq-kotlin-codegen-array-bug-report).

### Versions

- jOOQ: 3.14.0
- Java: 11.0.2-open
- Kotlin: 1.4.0
- Database (include vendor): Postgres 13
- OS: Linux

**Comment by lukaseder** [comment]
Thanks a lot for your report, @gregopet. I'll look into this soon

**Comment by lukaseder** [comment]
I can reproduce this. Will look into the fix now

**Comment by lukaseder** [comment]
Another array related issue has surfaced: https://github.com/jOOQ/jOOQ/issues/10787

**Comment by gregopet** [comment]
Somehow I had a feeling this won't be straightforward :fearful: Anyway, I'm using Java classes so I'm in no hurry for this fix; hell, if nobody else come around to it I can see if I can create a PR.. just as soon as I'm not so damn busy :exploding_head:

**Comment by lukaseder** [comment]
Not sure what you mean, it's already fixed. :) The other issue is not related...

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0. Backport scheduled for 3.14.1 (#10789)

**Comment by lukaseder** [comment]
Thanks again for reporting!

**Comment by gregopet** [comment]
Thank you for fixing it so fast... and of course most of all for jOOQ! I had to participate in an JVM vs. Node.js debate recently and jOOQ was one of the things I would miss most in not-really-java script land :)

**Comment by lukaseder** [comment]
Hah, yes. I've heard the same things from people going to Go or Rust or whatever :)
