### ISSUE TITLE
Wrong XSD schema in org.jooq.Constants#XSD_CODEGEN in version 3.14.0

### ISSUE THREAD

**Issue by svilenivanovsmule** [jOOQ/jOOQ#10762]
### Expected behavior
`org.jooq.Constants#XSD_CODEGEN` should contain `jooq-codegen-3.14.0.xsd` shipped in the `jooq-meta.jar`

### Actual behavior
`org.jooq.Constants#XSD_CODEGEN` is the old 3.13 `jooq-codegen-3.13.0.xsd`, not available in the 3.14 version of the library

### Steps to reproduce the problem

This breaks the [Kotlin DSL Gradle plugin](https://github.com/rohanprabhu/kotlin-dsl-gradle-jooq-plugin)
### Versions

- jOOQ: 3.14.0
- Java: 11.0.6
- Database (include vendor): MySQL 8
- OS: Linux 
- JDBC Driver (include name if inofficial driver): 8.0.21

**Comment by lukaseder** [comment]
Thanks a lot for your report. Fixed for 3.15.0 and 3.14.1 (#10764)
