### ISSUE TITLE
Remove @Nullable annotation from methods affected by RecordMapper behaviour

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#10777]
### Expected behavior

Kotlin code:

```kotlin
val r = jooq.newRecord(MY_TABLE)
r.store()
val p: MyPojo = r.into(MyPojo::class.java)
```

Compiles correctly.

### Actual behavior

Fails to compile due to nullability.

### Versions

- jOOQ: 3.14.0 
- Java: 14
- Kotlin 1.4.10

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/10774
