### ISSUE TITLE
Add Rows.collecting() and Rows.collectingArray() methods to create Row[N] arrays and lists

### ISSUE THREAD

**Issue by baev** [jOOQ/jOOQ#10775]
### Use case:

As `DSL#values` method only accepts RowN arrays, dealing with multi-row updates and inserts is requires to write many boilerplate code to construct RowN<A, B, ...> arrays for collection of business objects.

For us it starts with methods like this:

```java

@SuppressWarnings("unchecked")
public static <T> Row1<T>[] asRows(final Collection<T> values) {
    return values.stream()
            .map(DSL::row)
            .toArray(Row1[]::new);
}

@SuppressWarnings("unchecked")
public static <T, S> Row2<T, S>[] asRows2(final Collection<Pair<T, S>> values) {
    return values
            .stream()
            .map(entry -> row(entry.getKey(), entry.getValue()))
            .toArray(Row2[]::new);
}

@SuppressWarnings("unchecked")
public static <T, S, U> Row3<T, S, U>[] asRows3(final Collection<Triple<T, S, U>> values) {
    return values
            .stream()
            .map(entry -> row(entry.getLeft(), entry.getMiddle(), entry.getRight()))
            .toArray(Row3[]::new);
}
```

and then we ended up with implementing Java Collector API for building rows:

```java
@SuppressWarnings("unchecked")
public static <T, F1> Collector<T, Collection<Row1<F1>>, Row1<F1>[]> toRowsArray(
        Function<T, F1> f1Func) {
    return Collector.of(
            ArrayList::new,
            (list, item) -> list.add(DSL.row(f1Func.apply(item))),
            (left, right) -> {
                left.addAll(right);
                return left;
            },
            list -> list.toArray(Row1[]::new)
    );
}

@SuppressWarnings("unchecked")
public static <T, F1, F2> Collector<T, Collection<Row2<F1, F2>>, Row2<F1, F2>[]> toRowsArray(
        Function<T, F1> f1Func, Function<T, F2> f2Func) {
    return Collector.of(
            ArrayList::new,
            (list, item) -> list.add(DSL.row(f1Func.apply(item), f2Func.apply(item))),
            (left, right) -> {
                left.addAll(right);
                return left;
            },
            list -> list.toArray(Row2[]::new)
    );
}

public static <T> Collector<T, Collection<RowN>, RowN[]> toRowsArray(
        Function<T, ?>... func) {
    return Collector.of(
            ArrayList::new,
            (list, item) -> {
                final Object[] objects = Stream.of(func).map(f -> f.apply(item)).toArray(Object[]::new);
                list.add(DSL.row(objects));
            },
            (left, right) -> {
                left.addAll(right);
                return left;
            },
            list -> list.toArray(RowN[]::new)
    );
}
```

### Possible solution you'd like to see:

It would be nice to include such Java Collectors for RowN types, or provide some other utility to simplify creation of RowN arrays. 

### Versions:

- jOOQ: 3.14.0
- Java: 11.0.2
- Database (include vendor): PostgreSQL 12
- OS: macos
- JDBC Driver (include name if inofficial driver):

Additional links: https://github.com/jOOQ/jOOQ/issues/6604

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. This is actually a very good idea. We could have static methods on the various `Row[N]` interfaces, such as on `Row2<T1, T2>`:

```java
    @SuppressWarnings("unchecked")
    public static <T, T1, T2> Collector<? super T, ?, Row2<T1, T2>[]> collectingArray(
        Function<? super T, ? extends T1> f1,
        Function<? super T, ? extends T2> f2
    ) {
        return Collectors.collectingAndThen(collecting(f1, f2), l -> l.toArray(Row2[]::new));
    }

    public static <T, T1, T2> Collector<? super T, ?, List<Row2<T1, T2>>> collecting(
        Function<? super T, ? extends T1> f1,
        Function<? super T, ? extends T2> f2
    ) {
        return Collector.of(
                ArrayList::new,
                (l, t) -> l.add(DSL.row(f1.apply(t), f2.apply(t))),
                (t1, t2) -> {
                    t1.addAll(t2);
                    return t1;
                }
        );
    }
```

The naming would follow the `java.util.stream.Collectors` convention of using `collecting`. Usage could then look like this:

```java
    public static void main(String[] args) {
        System.out.println(Stream.of(1, 2, 3).collect(collecting(i -> i, i -> -i)));
        System.out.println(Arrays.asList(Stream.of(1, 2, 3).collect(collectingArray(i -> i, i -> -i))));
    }
```

... producing:

```
[(1, -1), (2, -2), (3, -3)]
```

Alternatively, instead of putting these on the `Row[N]` interfaces, we could put them on the `Row` interface, or introduce a new auxiliary class `Rows`

**Comment by lukaseder** [comment]
There you go. Keep those great ideas coming! 😁

**Comment by baev** [comment]
~~What about adding `JooqCollectors` utility class that contains all the required static methods? Single static import for all the RowN classes would be much more comfy to use...~~

Also, not sure about `collecting` naming. Actually naming in `java.util.stream.Collectors` is a mess, `toList`, `toMap` but `minBy`, `mapping`, `grouping` etc. Having in mind that usually people use static imports for collectors, it would be much more readable to name it `toRows` and `toRowsArray` instead (and from IDE suggests side easier to find these methods as well)

**Comment by lukaseder** [comment]
> What about adding `JooqCollectors` utility class that contains all the required static methods? Single static import for all the RowN classes would be much more comfy to use...

You already deleted this comment, but in case this wasn't obvious, there might be other collectors in the future that have nothing to do with `Row[N]` types. E.g. for `Record[N]` types.

> Also, not sure about `collecting` naming.

I'm not very opinionated. Having said so, it doesn't make sense to have `toRows()` on a `Rows` class. Maybe on a `Collectors` class, in case of which the previous problem would disappear. But `org.jooq.Collectors` would conflict with `java.util.stream.Collectors`, and you'd either have to static import the collectors, or fully qualify one or the other, when mixing.

The question is: Where does one look for such utilities...?

**Comment by lukaseder** [comment]
I'll reopen this. The status quo is acceptable, with room for improvement. Perhaps a better name will come as there might be new collectors in jOOQ 3.15

**Comment by baev** [comment]
> The question is: Where does one look for such utilities...?

I'm not very good in naming, but for me it is much more easier to type `toRows` and IDE suggest the import. And having a single class for all the collectors works in same way - type Collectors in class search and IDE shows all the classes with Collectors in the name.

**Comment by baev** [comment]
BTW `T1` is unused https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/Rows.java#L73

**Comment by lukaseder** [comment]
Yes of course, thank you.

**Comment by baev** [comment]
any ideas how we can deal with nulls (https://github.com/jOOQ/jOOQ/issues/5851) while using those methods? So far I can't even change my extracting function to return `val(null, SQLDataType)` instead of TN

**Comment by lukaseder** [comment]
The functions would have to produce `Field<T[N]>`, not `T[N]`...

**Comment by lukaseder** [comment]
So, for example:

```java
public static <T, T1, T2> Collector<T, ?, List<Row2<T1, T2>>> collecting(
    Function<? super T, ? extends Field<T1>> f1,
    Function<? super T, ? extends Field<T2>> f2
) {
    return Collector.of(
        ArrayList::new,
        (l, t) -> l.add(DSL.row(f1.apply(t), f2.apply(t))),
        (t1, t2) -> {
            t1.addAll(t2);
            return t1;
        }
    );
}
```

There will be more open questions like these. We can't apply the usual `x(T)` / `x(Field<T>)` convenience overloads here, or lambda expressions cannot be disambiguated anymore.

I think a clearer picture will emerge once there are other types of these collectors.

**Comment by baev** [comment]
yep, the other option would be to add additional methods with DataType's specified:


```java
public static <T, T1, T2, T3, T4, T5> Collector<T, ?, List<Row5<T1, T2, T3, T4, T5>>> collecting(
            final Function<? super T, ? extends T1> f1, final DataType<T1> t1,
            final Function<? super T, ? extends T2> f2, final DataType<T2> t2,
            final Function<? super T, ? extends T3> f3, final DataType<T3> t3,
            final Function<? super T, ? extends T4> f4, final DataType<T4> t4,
            final Function<? super T, ? extends T5> f5, final DataType<T5> t5
    ) {
        return Collector.of(
                ArrayList::new,
                (l, t) -> l.add(DSL.row(
                        DSL.val(f1.apply(t), t1),
                        DSL.val(f2.apply(t), t2),
                        DSL.val(f3.apply(t), t3),
                        DSL.val(f4.apply(t), t4),
                        DSL.val(f5.apply(t), t5)
                )),
                (r1, r2) -> {
                    r1.addAll(r2);
                    return r1;
                }
        );
    }
```

Or adding possibility to pass DataType to `DSL.values`: `DSL.values(rows, SQLDataType.VARCHAR, SQLDataType.BIGINT)`

**Comment by lukaseder** [comment]
I don't think that offering additional methods with a `DataType` parameter will scale well. I mean, the thing you will want here is really a `Field<T[N]>`, which might be anything as fancy as a scalar subquery: `field(select(val(1)))` (more complex, of course).

`DSL.values()` should offer any such hacks. It should be able to safely assume that it's possible to provide it with a set of rows that are already correct.

**Comment by lukaseder** [comment]
Note that if this issue and the current discussion shows anything at all, it's that publishing this new collector auxiliary API is premature, currently. It needs a lot more thought and more use-cases to see what other typical collection cases will arise.

I'm not denying that it will be a useful addition, but it's important not to be too clever, or focused on individual issues like #5851, because we'll have to support and maintain this new API for a long time, once it is released.

**Comment by baev** [comment]
yeah, I agree. From my side I just giving feedback while going all-in with JOOQ for our huge codebase. So far this utility works very well in all the places except some of huge bulk inserts with nullable columns of type bigint.

Having functions that return Field<T> instead of T denies possibility to use method references and increases complexity a lot for simple cases

**Comment by lukaseder** [comment]
> yeah, I agree. From my side I just giving feedback while going all-in with JOOQ for our huge codebase

Sure, I appreciate it! Even if some ideas may not be viable, showing them offers insight into what might be common pitfalls. We now know that a set of utilities are needed to transform between user types and different representations of `Row[N]`, `Record[N]`, and other things. Designing such an API is an iterative process. We'll get there! 😊

> So far this utility works very well in all the places except some of huge bulk inserts with nullable columns of type bigint.

Understood. #5851 is a problem, but it's a bug, not really an API design problem...

> Having functions that return Field instead of T denies possibility to use method references and increases complexity a lot for simple cases

Sure, but not having it denies the possibility of being maximally flexible. This new utility could also offer convenient way of wrapping `T` in `Field<T>` in a functional, composable way. The primitive operation must be using `Field<T>`, though (like with the entirety of the jOOQ API), or we'll never get this right in the long run.

**Comment by lukaseder** [comment]
I'm looking into finalising this for jOOQ 3.15 now. Reviewing the discussion, I agree:

- `Rows.collecting()` is not a good name. A better name for the current methods is indeed as you suggested: `toRowList()` and `toRowArray()`
- Until now, no other types of collectors have surfaced from feature requests. I can't think of any right now that are worth the effort. Maybe `Record[N]` types, eventually. As such, I don't want to rename the `Rows` class to `Collectors`, because of the name clash with JDK `Collectors`. Instead, we'll keep it as it is, as a `Row` type specific utility class, just like `Converters` is there to offer `Converter` utilities.
- A particular use-case for these collectors is going to be offered via #6604 for `INSERT` statements, also offered in jOOQ 3.15:

    ```java
    @Test
    public void testInsert() throws Exception {
        Table<Record> t = table(unquotedName("t"));
        Field<Integer> a = field(unquotedName("a"), INTEGER);
        Field<String> b = field(unquotedName("b"), VARCHAR);

        assertEquals(
            "insert into t (a, b) values (1, '1'), (2, '2'), (3, '3')",
            DSL.insertInto(t).columns(a, b).valuesOfRows(
                Stream.of(1, 2, 3).collect(toRowArray(i -> val(i), i -> val("" + i)))
            ).getSQL(INLINED)
        );
    }
    ```
- There will be references from Javadoc to this new utility in:
  - [ ] The various `InsertValuesStep[N].valuesOfRows(Row[N]...)` methods
  - [ ] `Row[N].in(Row[N]...)` and `notIn()` methods
  - [ ] `DSL.values(Row[N]...)` constructors

**Comment by lukaseder** [comment]
I'm still thinking about the special case (that will be the most popular case):

```java
    public static final <T, T1, T2> Collector<T, ?, Row2<T1, T2>[]> toRowArrayX(
        Function<? super T, ? extends T1> f1,
        Function<? super T, ? extends T2> f2
    ) {
        return toRowArray(t -> DSL.val(f1.apply(t)), t -> DSL.val(f2.apply(t)));
    }
```

I.e. where we offer functions returning `T` types, not `Field<T>` types. We obviously can't overload because of generic erasure, but perhaps a good name can be found?

**Comment by lukaseder** [comment]
I can't think of a name. It can still be found later...

**Comment by lukaseder** [comment]
A related new utility to facilitate type safe, reflection free, FP style record mapping will be offered in jOOQ 3.15.0 as well:
https://github.com/jOOQ/jOOQ/issues/11804
