### ISSUE TITLE
DSL.jsonbArray() generates json_build_array() call in PostgreSQL, instead of jsonb_build_array()

### ISSUE THREAD

**Issue by johann-sonntagbauer** [jOOQ/jOOQ#10788]
### Expected behavior

`DSL.jsonbArray()` should use the PostgreSQL `jsonb_build_array `

https://www.postgresql.org/docs/11/functions-json.html

### Actual behavior

`DSL.jsonbArray()` uses the PostgreSQL `json_build_array `   (no b)

### Steps to reproduce the problem

Following DSL construct results in wrong json function being used.

```java
dsl.select(jsonbArray()).fetchOne();
```

The resulting query 

```
select json_build_array()
```

### Versions

- jOOQ: 3.14.0
- Java: adopt-openjdk-11.0.7
- Database (include vendor): postgresql 11.4
- OS: linux
- JDBC Driver (include name if inofficial driver): postgresql-42.2.11

**Comment by johann-sonntagbauer** [comment]
Seems like there is a check for `SQLDataType.JSONB` missing here:
https://github.com/jOOQ/jOOQ/blob/477df78c1305f564f81c9c65c363626d007d795e/jOOQ/src/main/java/org/jooq/impl/JSONArray.java#L116

**Comment by lukaseder** [comment]
Thanks a lot for the report.

I can confirm, this isn't correct. Likewise, that emulation when the `nullType == ABSENT_ON_NULL` only uses `jsonArrayAgg()`, not `jsonbArrayagg()`

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.15.0. Backport scheduled for 3.14.1 (#10791)

**Comment by lukaseder** [comment]
Thanks again for your report! I hope you keep testing this functionality :) If you have ideas for further improvements, you know where to put them!

**Comment by johann-sonntagbauer** [comment]
Thank you for the fast fix! Very impressive!
