### ISSUE TITLE
Insert statement fails on new version of Jooq and older mariadb

### ISSUE THREAD

**Issue by gpor0** [jOOQ/jOOQ#10799]
### Expected behavior
Row should be persisted.
### Actual behavior

```
org.jooq.exception.DataAccessException: SQL [insert into `user` (`id`, `tenant_id`, ... `uc`, `um`, `dc`, `dm`, `version`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) returning `id`]; (conn=419265) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'returning `id`' at line 1
        at org.jooq_3.14.0.MARIADB.debug(Unknown Source)
        at org.jooq.impl.Tools.translate(Tools.java:2898)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:389)
        at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:218)
        at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:183)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:131)
        at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:179)
        at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:167)
        at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:162)
```

### Steps to reproduce the problem

SQL above passes when using 3.13.5 towards mariadb 10.3.13.
Also passes when using 3.14.0 towards 10.5.6.
Fails on 3.14.0 towards 10.3.13.

### Versions

- jOOQ:
3.14.0
- Java:
11.0.9
- Database (include vendor):
Mariadb 10.3.13 AWS
- OS:
Amazon EC2  Linux AMI
- JDBC Driver (include name if inofficial driver):
does not matter, (tried 2.7.0 and 2.5.4)

**Comment by lukaseder** [comment]
Thanks a lot for your request.

In order to have continued MariaDB 10.3 support, please use the [`SQLDialect.MARIADB_10_3`](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/SQLDialect.html#MARIADB_10_3) dialect, which continues to maintain the less efficient and powerful logic using JDBC `Statement.getGeneratedKeys()` in the jOOQ Professional and jOOQ Enterprise Editions.

I hope this helps.

**Comment by lukaseder** [comment]
We have now added a version support matrix to our website, to better document which jOOQ versions and editions work with what RDBMS versions: https://www.jooq.org/download/support-matrix

**Comment by gpor0** [comment]
As stated in support matrix there should be no differences in OSS edition between 3.13 and 3.14.


jOOQ version | Dialect versions (commercial editions) | Dialect version (OSS edition)

3.14 (latest) | 10.0, 10.1, 10.2, 10.3, 10.4, 10.5 | 10.5
3.13              | 10.0, 10.1, 10.2, 10.3, 10.4, 10.5 | 10.5

**Comment by lukaseder** [comment]
> As stated in support matrix there should be no differences in OSS edition between 3.13 and 3.14.

Yes, indeed. Both versions require MariaDB 10.5.

That doesn't mean there isn't any difference in behaviour, but both versions are expected to work on MariaDB 10.5+.
