### ISSUE TITLE
Known issues of the new Clickhouse integration

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10792]
This issue will collect "known issues" for the new Clickhouse integration (see https://github.com/jOOQ/jOOQ/issues/7539), which will be addressed later.

### SQL features

**Syntax**

- [ ] Case sensitivity seems to be a slippery slope. While e.g. both `int` and `INT` types are possible, `UInt8` is case sensitive, and so are unquoted table names.

**DDL**

- [ ] Clickhouse doesn't support PK/UK/FK constraints. Our integration tests will use the synthetic constraints features to pretend these are supported.
  - [ ] DDL statements will just silently ignore the constraint specification
  - [ ] It seems that the `ENGINE` might implicitly create a "primary key", akin to a clustered index in other RDBMS
- [ ] `CREATE TABLE` has a mandatory `ENGINE = engine` clause. There's no default. Options:
  - Assume a default, e.g. `ENGINE = Log` (and add API to override it. It would seem compatible with MySQL, it seems)
  - Don't add an `ENGINE` specification and let users use the `storage()` clause. Integration tests would use an `ExecuteListener` to append the `ENGINE = Log` clause
- [ ] Unnamed `CHECK` constraints are not possible
- [ ] The MySQL `COMMENT` syntax is parsed (and ignored?) for columns, but rejected for tables

**DML**

- [ ] There is no `DELETE` or `UPDATE` statement!
  - [ ] `DELETE` without a `WHERE` clause (or `ORDER BY .. LIMIT`) can be emulated with `TRUNCATE`. This at least works in integration tests, which reset the data between tests...

**Data types**

- [ ] Clickhouse supports 128 and 256 bit integers (see also Firebird: https://github.com/jOOQ/jOOQ/issues/10328)

**Comment by mleonhard** [comment]
Clickhouse now has a [DELETE Statement](https://clickhouse.com/docs/en/sql-reference/statements/delete), supported by the MergeTree engine family.

**Comment by lukaseder** [comment]
This issue is outdated. I'll comment about further findings directly in the original issue: https://github.com/jOOQ/jOOQ/issues/7539
