### ISSUE TITLE
Meta does not recognize PostgreSQL identity columns as being of type identity

### ISSUE THREAD

**Issue by kyle-mallah** [jOOQ/jOOQ#10798]
### Expected behavior
Through Jooq's DDL I create a table. An "id" field is marked as being of type `SQLDataType.BIGINT.nullable(false).identity(true)`. Later, I attempt to load this table's meta. Observing the `TableFieldImpl`'s type, I expect the table field to have, among other things, type bigint, NOT_NULL, and identity = true

### Actual behavior
the TableFieldImpl's type is correctly bigint and NOT_NULL, but identiy is set to false.

### Steps to reproduce the problem

```java
String url = "jdbc:postgresql://12.34.56.78?currentSchema=client_14";
String user = "username";
String pass = "password";
Configuration configuration = new DefaultConfiguration();
DSLContext create = null;
try (Connection conn = DriverManager.getConnection(url, user, pass)) {
	create = DSL.using(
		conn,
		SQLDialect.POSTGRES);

	Field<Long> idField = DSL.field(name("id"), SQLDataType.BIGINT.nullable(false).identity(true));

	create.createTable("sad_table")
		.column(idField)
		.execute();

	Table<?> table = create.meta().getTables("sad_table").stream()
		.filter(t -> t.getSchema().getName().equals("client_14"))
		.collect(Collectors.toList())
		.get(0);
	Field<?> idFieldMeta = table.fieldStream()
		.filter(field -> field.getName().equals("id"))
		.collect(Collectors.toList()).get(0);

	System.out.println(idField.getDataType().identity()); // true (original field -- correct)
	System.out.println(idFieldMeta.getDataType().identity()); // false (meta field -- incorrect)

} catch (Exception e) {
	// For the sake of this tutorial, let's keep exception handling simple
	e.printStackTrace();
	throw new RuntimeException(e);
}
```

### Versions

- jOOQ: 3.14.0
- Java: 11
- Database (include vendor): PostgreSQL 10.5
- OS: Ubuntu 18.04.4
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Your program prints the expected output with JDBC driver `org.postgresql:postgresql:42.2.16`

**Comment by lukaseder** [comment]
... I'll try again on PostgreSQL 10.5, which didn't support `IDENTITY` columns yet. Probably, the JDBC driver doesn't recognise the serial type.

**Comment by lukaseder** [comment]
Nope, works correctly on PostgreSQL 10.5 as well, with the indicated JDBC driver version.
