### ISSUE TITLE
Treat `timestamp` as `Instant = LocalDateTime.atOffset(ZoneOffset.UTC)`

### ISSUE THREAD

**Issue by nedtwigg** [jOOQ/jOOQ#10802]
### Use case:

All of the `timestamp` fields in our database are really modeling a `java.time.Instant`, but since jooq gives `LocalDateTime` instead, we pretend that `now()` is `LocalDateTime.now(Clock.systemUTC())`.

It becomes a bigger deal when we try to do timezone-specific displays or logic.  Some variables are type "UTC", others are type "local timezone", but the typesystem can't help with that.  If the "UTC" variables were all `Instant`, it would be much more clear.

### Possible solution you'd like to see:

```java
generate.javaTimeTypes = true
generate.timestampAsInstantUTC = true
```

### Possible workarounds:

We have functions that take `Instant`, so that inside the function we can distinguish between UTC and local timezone types, but it adds a lot of boilerplate for us.

### Versions:

- jOOQ: 3.13.1
- Java: 8
- Database (include vendor): Postgres
- OS: Linux
- JDBC Driver (include name if inofficial driver): 42.2.18

**Comment by lukaseder** [comment]
Thank you very much for your message.

Why aren't you using PostgreSQL ` TIMESTAMP WITH TIME ZONE` data types instead, which are a better match for `java.time.Instant`? As per the JDBC and standard SQL specification, we map that type to `java.time.OffsetDateTime`, despite PostgreSQL not storing the offset.

You can, of course, use data type rewriting, or custom converters to bind all of your types to `SQLDataType.INSTANT` in jOOQ, see:

- https://www.jooq.org/doc/latest/manual/code-generation/data-type-rewrites/
- https://www.jooq.org/doc/latest/manual/code-generation/custom-data-types/

But I really recommend using the right data type in the database, first, or you'll depend on server *and* client time zone settings. The correct client data type for PostgreSQL `TIMESTAMP (WITHOUT TIME ZONE)` is `java.sql.Timestamp` or `java.time.LocalDateTime`, which are equivalents.

**Comment by nedtwigg** [comment]
If I was recording user actions and the timezone they were in, then I would record their meaningful timezone.  That would allow me to ask a question like "what actions are users doing in (their) morning".

But the events I am recording don't have meaningful timezones, they are just, as the `Instant` javadoc states:

> An instantaneous point on the time-line.

If a piece of data doesn't have a meaningful timezone, I think it's a smell to pretend like it does.  If I have servers at cloud-abstracted points around the globe, I shouldn't be able to ask "what are they doing in the morning".  They don't have a "morning".  That, imo, is what is so elegant about the hard divide between `Instant` vs `LocalDateTime` in `java.time`.  And if you are recording events without a meaningful timezone, I also think it's a smell to use anything besides UTC, and if you're always storing in UTC, I think it's a smell to not declare that at the schema level, rather than stuff the exact same piece of data into every single entry.  It's like storing angles as `[float angle, enum {Radians, Degrees}]` and then always using `Radians` - you're adding an unnecessary DOF which can only hurt you, and has no chance of ever being helpful.

Thanks very much for the workarounds (I'll post back whichever I use in case it's helpful to others), but imo there is still a case for builtin support.

**Comment by lukaseder** [comment]
And the PostgreSQL documentation about [`TIMESTAMP WITH TIME ZONE`](https://www.postgresql.org/docs/current/datatype-datetime.html) reads:

> For timestamp with time zone, the internally stored value is always in UTC

The name is misleading. PostgreSQL didn't implement the standard SQL `TIMESTAMP WITH TIME ZONE` data type. They implemented something better instead, but unfortunately, recycled the standard type name.

> That, imo, is what is so elegant about the hard divide between `Instant` vs `LocalDateTime` in `java.time`.

Yes, and in PostgreSQL, these two data types correspond to `TIMESTAMP WITH TIME ZONE` and `TIMESTAMP WITHOUT TIME ZONE`, despite the misleading names.

**Comment by alex-lx** [comment]
How about `timestamp` in mysql, it's like `TIMESTAMP WITH TIME ZONE` in PostgreSQL, why still map it to `LocalDateTime`?

No intention to bother.

**Comment by lukaseder** [comment]
See discussion here, for example: https://github.com/jOOQ/jOOQ/issues/14517#issuecomment-2259967635
