### ISSUE TITLE
Transaction propagation with transactionAsync

### ISSUE THREAD

**Issue by anushreegupta44** [jOOQ/jOOQ#10818]
### Your question:
I am trying to do a parent transactions within which I want to run multiple nested transactions that run in async, but if anyone of the child transactions fails, I want to roll back all transactions within the parent transaction. So basically I want to call async transactions within a parent transaction and also propagate the parent transaction.

Currently, if an error would occur in any of the child transactions, only that would be rolled back, not the rest.

```java
   //_Create a parent transaction to insert all Foos to db_
    public List<Foo> bulkCreate(List<FooCreateRequest> fooCreateRequests) {
        List<Foo> foos = new ArrayList<>();
        dslContext.transaction(configuration -> {
            List<CompletableFuture<Foo>> fooFutures = new ArrayList<>();
            for (FooCreateRequest fooCreateRequest : fooCreateRequests) {
                //for each Foo, call a nested transaction
                fooFutures.add(saveFoo(fooCreateRequest));
            }
            fooFutures.stream().map(fooFuture -> fooFuture.join()).collect(Collectors.toList());
        });
        return foos;
    }

   // _Call this child transaction for each foo_
    private CompletableFuture<Foo> saveFoo(FooCreateRequest fooCreateRequest) {
        //_run this asynchronously but if anything fails here, roll back the above parent transaction_
        return dslContext.transactionResultAsync(configuration -> {
            //_first. db call_
            Long createdFooId = fooRepository.createFoo(fooCreateRequest);
            //_second db call_
            fooChildRepository.createFooChild(createdFooId);
            return foo;
        }).toCompletableFuture();
    }
```

### Versions:

- jOOQ: 3.13.4
- Java: 11
- Database (include vendor): psql (PostgreSQL) 11.2 (Debian 11.2-1.pgdg90+1) - mdillon/postgis image - Postgresql with postgis extension
- OS: Linux
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.12

**Comment by lukaseder** [comment]
You seem to be using Spring (`fooRepository`)? Does Spring manage transactions for you? If so, I would recommend you use only spring for transaction management, and don't mix Spring usage with jOOQ API usage.

Otherwise, please make sure that you're actually using that `Configuration` handle from within the transactional runnable or callable, not the globally avilable `DSLContext`, which is not in a transactional state. For example:

```java
ctx1.transactionAsync(conf2 -> {
  conf2.dsl().transactionAsync(conf3 -> {
    conf3.dsl().doStuff();
  });
});
```

**Comment by anushreegupta44** [comment]
No I am not using JPA.

I changed my implementation to use the `configuration` handle from within my transaction. It. still does not roll back the parent transaction. 

However, if I use the transaction method instead of the transactionResultAsync, it does roll back the parent transaction.

My configuration is using the org.springframework.boot.autoconfigure.jooq.SpringTransactionProvider.java.

I debugged to find the cause, and with the below code, it goes to the PgConnection.java (postgresql 42.2.14) and finds the queryExecutor.getTransactionState() = TransactionState.IDLE and logs `Rollback requested but no transaction in progress
`
```
ctx1.transactionResult(conf2 -> {
  conf2.dsl().transactionResultAsync(conf3 -> {
    conf3.dsl().doStuff();
  });
});

```
whereas with the below it's state is not idle and actually rolls back the parent.

```
ctx1.transactionResult(conf2 -> {
  conf2.dsl().transactionResult(conf3 -> {
    conf3.dsl().doStuff();
  });
});

```

**Comment by lukaseder** [comment]
Can you pleas show a complete example of what you're doing? Ideally starting from here: https://github.com/jOOQ/jOOQ-mcve

With just the snippets I've seen, it's difficult to understand what you're doing. E.g. you're saying

> No I am not using JPA.

But I asked you about Spring, and indeed, you're using Spring

> My configuration is using the org.springframework.boot.autoconfigure.jooq.SpringTransactionProvider.java.

But then, what does all of your Spring code look like? What's that repository doing? Etc.
