### ISSUE TITLE
Review our Nullable and NotNull annotation usage

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10832]
Adding `@Nullable` and `@NotNull` annotations to an existing API can cause false positives or inconveniences.

This issue will critically review our annotation usage, and possibly adapt things where the annotation causes more trouble than it helps. This includes:

- [x] https://github.com/jOOQ/jOOQ/issues/10774 `ResultQuery.fetchSingleInto(Class)` and `Record.into(Class)`, where the nullability almost never applies in `DefaultRecordMapper`. 3.15.0 and 3.14.1 removed the `@Nullable` annotation
- [x] https://github.com/jOOQ/jOOQ/issues/10831 `fetchOne(int, Class)` and similar, where the nullability very rarely doesn't apply.
- [x] A lot of internal things will be fixed, which won't necessarily be documented in this issue other than through commits

**Comment by rkraneis** [comment]
`@NotNull` will also be removed from `Record.into(Table)`, is that right?

**Comment by oxygenecore** [comment]
Another fact is that for Records `NOT NULL` fields can still return nulls if these were not selected in the select clause. I've seen this burned some builds after enabling null/non-null annotations.

**Comment by lukaseder** [comment]
> @rkraneis `@NotNull` will also be removed from `Record.into(Table)`, is that right?

Why would it be removed?

> @oxygenecore Another fact is that for Records `NOT NULL` fields can still return nulls if these were not selected in the select clause. I've seen this burned some builds after enabling null/non-null annotations for generators.

This isn't related to the discussion here. You probably turned on the generation of annotations by the code generator? I've discussed how they're treacherous numerous times. Just look at this bike shed here :) https://github.com/jOOQ/jOOQ/issues/10212

See: https://blog.jooq.org/2017/07/25/5-things-you-may-not-have-known-about-jooq/#thing1

**Comment by rkraneis** [comment]
> Why would it be removed?
Sorry, I was looking at the wrong overload apparently (the one using `RecordMapper.map`, which is `@Nullable`, and rightly has the comment “This is `@Nullable` in rare cases”).

**Comment by lukaseder** [comment]
All documented issues so far have been addressed. I'm closing this issue here. New issues can be created in the future.
