### ISSUE TITLE
KotlinGenerator should produce open classes

### ISSUE THREAD

**Issue by BorisOsipov** [jOOQ/jOOQ#10835]
### Expected behavior
Generated code:
```
open class UserDao(configuration: Configuration?) : DAOImpl<UserRecord, com.example.User, UUID>(User.USER, com.example.User::class.java, configuration) {...}
```

### Actual behavior
Generated code:
```
class UserDao(configuration: Configuration?) : DAOImpl<UserRecord, com.example.User, UUID>(User.USER, com.example.User::class.java, configuration) {...}
```

### Steps to reproduce the problem
Enable DAO generation with `org.jooq.codegen.KotlinGenerator` generator.

### Details

By default, Kotlin classes are final. To allow inheritance classes must have `open` modifier. See [official doc ](https://kotlinlang.org/docs/reference/classes.html#inheritance)
We actively use approach `class UserRepository(configuration: Configuration): UserDao(configuration: Configuration)` and this kind of blocker for us.

Can we make generated DAO classes `open` by default?

### Versions
- jOOQ: 3.14.1
- Java: 11
- Database (include vendor): PostgreSQL 10.7
- OS: Windows
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.9

**Comment by lukaseder** [comment]
Thanks a lot for your suggestion. I don't think this is restricted to DAOs, we should offer this for all classes, including records. As a workaround, you can probably hack your way around the current limitation and add the `"open"` "annotation" to all DAOs by overriding the `JavaGenerator.printClassAnnotations()` method.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.15.0. Backport scheduled for 3.14.2 (#10836)

**Comment by HaydenMeloche** [comment]
@lukaseder hey! is there any chance this could be extended to allow fields to be `open` as well? Some libraries such as ModelMapper don't work with JOOQ records in some cases since the fields are not `open`.

**Comment by lukaseder** [comment]
Can you create a new issue @HaydenMeloche
