### ISSUE TITLE
Rename column foreign key

### ISSUE THREAD

**Issue by iz8wok** [jOOQ/jOOQ#10847]
hi everyone,
I have a folder where it contains all the initialization and modification sql files V1__init.sql etc  
I created the file V5_rename_column_view_id.sql for rename column “id” TO “view_id”, field id is a foreign key
, the file contains: 

```
ALTER TABLE dc1."views_columns" DROP CONSTRAINT "views_columns_id_fkey";
ALTER TABLE dc1."views_columns" RENAME COLUMN id TO view_id;
ALTER TABLE dc1."views_columns" ADD CONSTRAINT "views_columns_id_fkey" FOREIGN KEY (view_id) REFERENCES dc1."views"(id) ON UPDATE NO ACTION ON DELETE CASCADE;
```

when I restart the server it generates this error:

[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.12.2:generate (default) on project sample-manager: Error running jOOQ code generation tool: Error while exporting schema: SQL [alter table "dc1"."views_columns" drop constraint "views_columns_id_fkey"]; Constraint "views_columns_id_fkey" not found; SQL statement:

[ERROR] alter table "dc1"."views_columns" drop constraint "views_columns_id_fkey" [90057-200]
How can I solve this problem?

Versions:
* jOOQ: 3.12.2
* Java:13.0.1
* Database (include vendor): postgresql
* OS: Mac os
Thanks

**Comment by lukaseder** [comment]
Thank you very much for your report. Just to be sure, those aren't typos and your files are really named `V1__init.sql` (2 underscores) and `V5_rename_column_view_id.sql` (1 underscore)?

**Comment by iz8wok** [comment]
Yes i used underscore

Il mar 3 nov 2020, 15:14 Lukas Eder <notifications@github.com> ha scritto:

**Comment by lukaseder** [comment]
OK, thanks for the confirmation. Anyway, that's not it. The files are sorted correctly. I'm trying to reproduce this. This works:

```sql
CREATE TABLE dc1."views" (id INT PRIMARY KEY);
CREATE TABLE dc1."views_columns" (id INT, CONSTRAINT "views_columns_id_fkey" FOREIGN KEY (id) REFERENCES dc1."views"(id));

ALTER TABLE dc1."views_columns" DROP CONSTRAINT "views_columns_id_fkey";
ALTER TABLE dc1."views_columns" RENAME COLUMN id TO view_id;
ALTER TABLE dc1."views_columns" ADD CONSTRAINT "views_columns_id_fkey" FOREIGN KEY (view_id) REFERENCES dc1."views"(id) ON UPDATE NO ACTION ON DELETE CASCADE;
```

I'm assuming you have a valid set of SQL scripts before running `V5_rename_column_view_id.sql` including a script that creates the key. Can you please provide all the necessary information to reproduce this issue, i.e. all the relevant content of your various SQL scripts that are run before `V5_rename_column_view_id.sql`?

**Comment by lukaseder** [comment]
I couldn't reproduce this issue at the time. If it persists, please reopen with the required additional information to reproduce, ideally in form of an MCVE (template here: https://github.com/jOOQ/jOOQ-mcve)
