### ISSUE TITLE
KotlinGenerator always generate nullable types for POJOs

### ISSUE THREAD

**Issue by BorisOsipov** [jOOQ/jOOQ#10842]
### Your question:

Hello! I am quite new in jooq generator and maybe miss some generator options.

I have DDL
```
CREATE TABLE app.payment
(
    some_id       uuid NOT NULL,
    some_contract_id uuid NOT NULL,
    payment_number   int4,
    PRIMARY KEY (some_id)
);
```

KotlinGenerator produces following data class:
```
data class Payment(
         var someId: UUID? = null
        , var someContractId: UUID? = null
        , var paymentNumber: Int? = null
): Serializable
```

I expected that for `NOT NULL` SQL fields generator will produce not nullable types like this:
```
data class Payment(
         var someId: UUID
        , var someContractId: UUID
        , var paymentNumber: Int? = null
): Serializable
```

I use default generator options. I see there some options like `Generate().withNullableAnnotation(..)` for java generator to add nullability annotation.

Are there some options to generate Kotlin data clasess for not null\null SQL fields?

Thanks in advance.

### Versions
- jOOQ: 3.14.1
- Java: 11
- Database (include vendor): PostgreSQL 10.7
- OS: Windows
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.9

**Comment by lukaseder** [comment]
Thanks for your message.

See also: 
- https://github.com/jOOQ/jOOQ/issues/10212
- https://groups.google.com/g/jooq-user/c/vwKYEK1CFDI/m/TPe2C5etBAAJ

I'll be happy to answer any remaining questions that you may have after the above

**Comment by BorisOsipov** [comment]
@lukaseder Thank you for quick extremely quick answers. I appreciate it.

**Comment by rainmanhhh** [comment]
what about provide null-safe pojos for daos? sql in them are not written manually so we can trust the "NOT NULL" definitions from database schema

**Comment by lukaseder** [comment]
@rainmanhhh I understand your rationale but I don't see why we should make a special case for "POJOs for DAOs." While I appreciate that a lot of folks use jOOQ as a DAO-utility for simple CRUD applications that just happens to have a huge set of unused, yet incredibly awesome SQL features, making an exception for "DAO POJOs" that behave differently from "non-DAO POJOs" would just unnecessarily complicate things, including maintenance of the code generator, documentation, subtle bugs, accidental complexity between features, the expected feature request of being able to generate *both* DAO-POJOs and non-DAO-POJOS (what would that even mean?), etc. etc.

Even if the rationale would be correct *in your case*, it won't be for anyone who extends the code generator to generate additional DAO methods (and people do that all the time).

In any case, as I have stated quite a few times, the need for overriding nullability in generated Kotlin code has been recognised in #10212, which will ship soon. Once #10212 is implemented, DAO-only users don't have to work with a brittle special case "just for DAOs", they can work with the real thing, and use only DAOs just the same. So, you'll get what you wanted, without jOOQ adding 7 layers of additional complexity.
