### ISSUE TITLE
Add <visibilityModifier/> to allow for generating explicit / implicit public visibility, as well as internal in KotlinGenerator

### ISSUE THREAD

**Issue by pauliusrum** [jOOQ/jOOQ#10851]
### Use case:

Kotlin 1.4 has an explicit api mode https://kotlinlang.org/docs/reference/whatsnew14.html#explicit-api-mode-for-library-authors. When this mode is enabled all declarations must contain a visibility modifier (with some exceptions listed in the docs). Currently kotlin generator generates the classes with implicit `public` modifier so it is impossible to enable this mode.

### Possible solution you'd like to see:

Add an explicit `public` modifier to the declarations. It would be nice if we could specify if `public` or `internal` modifier should be used since we would like to use an `internal` modifier but if it would be hard to implement such a feature `public` modifier would be enough. Public API should also specify the return type explicitly.

### Possible workarounds:

The only workaround that we can think of is to move the generation into a separate module that has explicit api mode turned off.

### Versions:

- jOOQ: 3.14.1
- Java: 8
- Database (include vendor): MySQL 8

**Comment by lukaseder** [comment]
Thank you very much for your suggestions. That's an interesting idea - I wasn't aware of this Kotlin feature. One might almost think that the default visibility should not have been public 🤔

Will look into it. Making everything `public` explicitly is not a big deal. It seems we can add `-Xexplicit-api=strict` to our integration tests to make sure the modifier isn't forgotten.

**Comment by lukaseder** [comment]
It seems that IntelliJ doesn't pick up this maven plugin configuration flag? Would be great to get compilation errors...

**Comment by lukaseder** [comment]
There are a few other things that need to be done to make this compiler mode work, e.g. explicit type declarations for all `public val`, which makes sense...

**Comment by lukaseder** [comment]
This turns into quite the change. I don't think that backporting it is a good idea given the regression risk.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.15.0. Thanks again for your suggestion.

**Comment by lukaseder** [comment]
I'll review this implementation again. Perhaps, making everything `public` is not the right approach for an idiomatic experience for most kotlin users. A `<visibilityModifier/>` configuration that allows for these values might be better:

- `DEFAULT` (the way it was until now)
- `PUBLIC` (what you're requesting)
- `INTERNAL` (seems useful as well)

Once we have that, it's not unlikely that users will want to be able to make jOOQ API (tables, records, etc.) `INTERNAL` but the data classes `PUBLIC`. We can still do that later.

**Comment by pauliusrum** [comment]
I agree with you. We would like to have record classes `INTERNAL` in your projects.

**Comment by lukaseder** [comment]
Only records?

**Comment by pauliusrum** [comment]
We do not generate data classes so everything (records, table definitions, tables, keys, etc..) could be internal. I will try to explain why internal modifier would be useful for us. We have a core library that contains generic functionality for other projects for example User management. So we create a basic table for users in core library that contains: id, username, password fields. The core library generates a record class with these three fields. Now when we use this core library in a specific project we want to add additional fields to the user table since usually for most real projects three field for user is not enough. We add extra fields in the project and the project generated its own UserRecords with additional fields. So the project is only interested in its own generated UserRecord class or any other database generated classes that is why it would be nice that core libraries generated classes would be internal.

**Comment by lukaseder** [comment]
Thanks for your explanations, @pauliusrum

**Comment by lukaseder** [comment]
Haha, oh my god. After a ton of yak shaving, now come the edge cases. E.g. "Modifier 'internal' is not applicable inside 'interface'", and thus, if a POJO and/or record implement a generated interface, the `internal` modifiers must again be made public.

These interfaces are a gift that keep on giving...

**Comment by lukaseder** [comment]
Correction. The interface can be declared `internal`, but not its properties / methods

**Comment by lukaseder** [comment]
If you have time to test the 3.15.0 code generator before it ships to help detect issues early, that would be very useful!

**Comment by pauliusrum** [comment]
Is jooq 3.15.0 published anywhere?

**Comment by lukaseder** [comment]
You can build it from github. If you're licensed, snapshot builds are available from here: https://www.jooq.org/download/versions

**Comment by pauliusrum** [comment]
I tried with main-snapshot version and I get the following error: 
`public override fun getUniqueKeys(): List<UniqueKey<PermissionGroupRecord>> = listOf(KEYPermissionGroupUNIQBB4729B65E237E06)`

The method does not override anything.

**Comment by lukaseder** [comment]
Thanks for the feedback. This method has been added in jOOQ 3.15.0-SNAPSHOT. If you're using the 3.15.0-SNAPSHOT code generator you'll have to use the 3.15.0-SNAPSHOT runtime as well to compile your generated code...

**Comment by pauliusrum** [comment]
I updated the runtime classes. Now it looks like everything is working. I tried with `visibilityModifier` set to `INTERNAL` and `explicitApi` mode enabled.

**Comment by lukaseder** [comment]
Great to hear, thanks for the feedback! I think this will be a very valuable addition for Kotlin users.
