### ISSUE TITLE
JOOQ generates an invalid underscore "_" enum

### ISSUE THREAD

**Issue by nyoungac** [jOOQ/jOOQ#10865]
Using the 3.14.1 code generator on a MySQL database with an enum field defined as:

  `t_offset_o` enum('-','+') NOT NULL DEFAULT '+',
OR
  `ref` enum('', <...>) NOT NULL DEFAULT '',

produce an invalid underscore "_" enum:

    _(""),

expected: Have some placeholder or random name.

**Comment by lukaseder** [comment]
Thank you very much for your report. Could you resolve the issue?

**Comment by lukaseder** [comment]
I see, it's a duplicate of https://github.com/jOOQ/jOOQ/issues/10866

**Comment by nyoungac** [comment]
@lukaseder Yeah, Github showed an error page when i submitted it the first time, so I ended up re-submitting
