### ISSUE TITLE
Don't create a diff between DECIMAL and NUMERIC types, where they are just aliases

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10864]
In some dialects, `DECIMAL` and `NUMERIC` types are just aliases, not distinct types. In those dialects (e.g. PostgreSQL), we shouldn't create a diff between two table definitions like these:

```sql
create table t (i decimal);
create table t (i numeric);
```

For example, in PostgreSQL:

```sql
create table x (d decimal, n numeric);

select column_name, data_type 
from information_schema.columns 
where table_name = 'x';
```

This produces:

```
column_name|data_type|
-----------|---------|
d          |numeric  |
n          |numeric  |
```

**Comment by lukaseder** [comment]
If precision or scale changes, we'll still "change" the data type name along with the precision or scale

**Comment by lukaseder** [comment]
All dialects I've tried so far treat `DECIMAL` and `NUMERIC` as aliases. We'll do so as well. If integration tests fail, we can exclude dialects from this new rule, rather than including all dialects explicitly.

**Comment by katzyn** [comment]
@lukaseder
Some DBMS (DB2, upcoming H2 2.0, possibly others) use `BigDecimal` for `DECFLOAT` too, it looks like jOOQ doesn't support this data type yet, but conditions like `type1.getType() == BigDecimal.class && type2.getType() == BigDecimal.class` may create a problem in the future.

**Comment by lukaseder** [comment]
Right, thanks for the pointer.

**Comment by lukaseder** [comment]
For now, it's correct. We'll support `DECFLOAT` eventually: https://github.com/jOOQ/jOOQ/issues/10880. When that happens, we'll review *all* of our internal usage of `BigDecimal.class`. There are many more such references.
