### ISSUE TITLE
Eliminate transitive dependencies

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#10875]
### Expected behavior

No non-optional runtime transitive dependencies

### Actual behavior

jOOQ pulls in `org.reactivestreams:reactive-streams:1.0.2` and `javax.xml.bind:jaxb-api:2.3.1`

### Versions

- jOOQ: 3.14.1
- Java: 14

**Comment by lukaseder** [comment]
Thanks, Axel.

These two dependencies are currently not optional, nor are they transitive. We use them directly in our code.

What problem are you trying to address here?

**Comment by axelfontaine** [comment]
Arrgh I just noticed they both found their way into the public interface of various classes. That probably makes this a much bigger task to ever make them optional again. As I am just trying to keep the dependency tree clean, but have no direct conflict or issues at this point, let's just close this for now.

**Comment by lukaseder** [comment]
Thanks for the update.

Some background:

jOOQ has been using JAXB from day 1. It used to be part of the JDK. The fact that it's a dependency now is historic and inevitable, unfortunately. Recent versions of jOOQ can live without an actual JAXB implementation (see the `MiniJAXB` class, which covers what we need internally), but the API (annotations) is still required.

Reactive Streams is a necessary interoperability dependency if we want to offer a solution for reactive execution models. In the future, the JDK 9 `Flow` API might be used, but most third parties (e.g. RxJava, Reactor, etc.) still support Java 8, so they haven't transitioned to `Flow` yet...

**Comment by axelfontaine** [comment]
This section of the manual may be in need of an update to reflect the current reality: https://www.jooq.org/doc/3.14/manual/getting-started/dependencies/

**Comment by lukaseder** [comment]
You're right, thanks for the pointer. This looks like something that will always be outdated, perhaps it's best to just remove it: #11002
