### ISSUE TITLE
Enum literals should be defined by generator strategies

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#10881]
Enum literals are currently not defined by generator strategies, but by jOOQ-codegen internals, so users cannot override the logic.

**Tasks:**

- [x] Add `GeneratorStrategy::getJavaEnumLiteral` for programmatic overrides
- [x] Add `MatchersEnumType::enumLiteral` for configurative overrides

**Comment by joca-bt** [comment]
Any update on this feature? We would like for enum values to follow Java naming convention instead of wtv is on the database.

**Comment by lukaseder** [comment]
Thanks for your ping, @joca-bt. Sure, the use-case is understood, but it hasn't been a high priority feature request. Are you licensed? Maybe we can do something to change priorities. Otherwise, you can easily map generated enums to your own custom enums via the usual converters.

**Comment by joca-bt** [comment]
We're not licensed. I'll try via custom converter.
