### ISSUE TITLE
ALTER TABLE code examples shows wrong multi column addition syntax

### ISSUE THREAD

**Issue by ahrytsiuk** [jOOQ/jOOQ#10887]
### Expected behavior
In the [ALTER TABLE](https://www.jooq.org/doc/latest/manual/sql-building/ddl-statements/alter-statement/alter-table-statement/) documentation, I can find an example of how to add multiple columns to a table in one go
```java
create.alterTable("table").add("column1", INTEGER).add("column2", INTEGER).execute();
```
According to doc, this code should work starting from `3.11.x` version.

I expect this code example to compile and execute successfully.

### Actual behavior
Compilation error
```bash
java: cannot find symbol
  symbol:   method add(java.lang.String,org.jooq.DataType<java.lang.Integer>)
  location: interface org.jooq.AlterTableFinalStep
```

### Steps to reproduce the problem

- Use the aforementioned code snippet 

### Versions

- jOOQ: 3.11.x - 3.14.x
- Java: 8, 11, 15
- Database (include vendor): N/A
- OS: N/A
- JDBC Driver (include name if inofficial driver): N/A

**Comment by lukaseder** [comment]
Thanks a lot for your report. That syntax is wrong indeed, it should be:

```java
create.alterTable("table").add(field(name("column1"), INTEGER), field(name("column2"), INTEGER)).execute();
```

**Comment by lukaseder** [comment]
We actually have a mechanism that attempts to compile all Java code snippets, but it's not active for most of them, yet. Perhaps time to activate it!
