### ISSUE TITLE
scalagenerator should not import java.lang.  which make type mismatch error

### ISSUE THREAD

**Issue by quanduoling** [jOOQ/jOOQ#10885]
### Expected behavior
scala generator should not import java.lang.
### Actual behavior
import java.lang.Class
import java.lang.Integer
import java.lang.Long

error msg:
 type mismatch;
found   : org.jooq.DataType[java.lang.Long]
 required: org.jooq.DataType[scala.Long]
### Steps to reproduce the problem
just generate

- If the problem relates to code generation, please post your code generation configuration
- A complete set of DDL statements can help re-create the setup you're having
- An MCVE can be helpful to provide a complete reproduction case: https://github.com/jOOQ/jOOQ-mcve

### Versions

- jOOQ:3.14.1
- scala:2.13 
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your report.

We're not aware of any such problems, and you've closed your issue yourself. I'm assuming everything is OK with generated code?
