### ISSUE TITLE
Incorrect generation of serialVersionUID in immutable POJO with immutable interface

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#10908]
With the following generator configuration

```
isDeprecated = false
isImmutablePojos = true
isSerializablePojos = false
isImmutableInterfaces = true
isPrimaryKeyTypes = true
isPojosEqualsAndHashCode = true
```

### Expected behavior

jOOQ shouldn't generate `serialVersionUID` fields in the POJOs

### Actual behavior

yet it does.

Note that setting `isImmutableInterfaces` to `false` fixes the issue.

### Versions

- jOOQ: 3.14.3
- Java: 14

**Comment by lukaseder** [comment]
I can't seem to reproduce this. Is this about the `JavaGenerator` or `KotlinGenerator`? Did you specify `isSerializableInterfaces` as well?

In any case, another hint that these generated interfaces don't seem to have a very favourable cost/benefit ratio, see https://github.com/jOOQ/jOOQ/issues/10509

**Comment by axelfontaine** [comment]
I was using the DefaultGenerator. The configuration I posted was the complete config as present in my `build.gradle.kts` file. Either way this is just a cosmetic detail, probably not worth spending too much time on. Feel free to close.

**Comment by lukaseder** [comment]
OK, so `DefaultGenerator = JavaGenerator`. Cosmetic or not, it's good to have yet another reminder of how much effort it is to maintain interface generation.

Since you discovered this, and are thus working (or thinking about working) with interfaces, what benefit do you see in them?

**Comment by axelfontaine** [comment]
> Since you discovered this, and are thus working (or thinking about working) with interfaces, what benefit do you see in them?

See https://github.com/jOOQ/jOOQ/issues/10509#issuecomment-725290087

**Comment by axelfontaine** [comment]
OK, I think I finally got to the bottom of this:

```
isImmutableInterfaces = true
isImmutablePojos = true
isSerializablePojos = false
```
triggers the behavior described.

Changing the config to:
```
isImmutableInterfaces = true
isImmutablePojos = true
isSerializableInterfaces = false
isSerializablePojos = false
```
fixes it.

Let's close this. It confused me, but the current behavior is probably correct.

**Comment by lukaseder** [comment]
I see, tricky indeed. POJOs can't really opt out of serialisability when they implement serialisable interfaces... Thanks for documenting your findings here!
