### ISSUE TITLE
Keys class is no longer generated in 3.14.2

### ISSUE THREAD

**Issue by eduramiba** [jOOQ/jOOQ#10902]
### Expected behavior

`Keys` class containing the catalog constraint is generated.
We used it in `InsertOnDuplicateStep::onConflictOnConstraint`

### Actual behavior

After update from 3.14.1 to 3.14.2 this class is no longer generated.

### Steps to reproduce the problem

Update to 3.14.2 and keys is no longer generated.

### Versions

- jOOQ: 3.14.2
- Java: 15.0.1
- Database (include vendor): PostgreSQL 13
- OS: Ubuntu 18.04
- JDBC Driver: PostgreSQL 42.2.18

Should I enable some new option? Or are we using the `Keys` class wrong?

Thank you!

**Comment by eduramiba** [comment]
I also noticed DAOs are not generated either.

**Comment by lukaseder** [comment]
Confirmed. A regression in the backport of this issue here: https://github.com/jOOQ/jOOQ/issues/10824

**Comment by lukaseder** [comment]
This seems not to affect 3.15.0-SNAPSHOT, a pure backport regression

**Comment by lukaseder** [comment]
Yes, the relevant integration test didn't trigger a re-generation of the generated code.

**Comment by lukaseder** [comment]
Fixed for 3.14.3. I'll release this immediately

**Comment by eduramiba** [comment]
Awesome, thanks for your work!

**Comment by lukaseder** [comment]
Version 3.14.3 has been released and is available from here: https://www.jooq.org/download/versions. As usual, the Maven Central sync will take a few hours. When ready, I'll announce the release on the user group.

Thanks again for your report.

**Comment by mkurz** [comment]
@lukaseder it's ready:
![image](https://user-images.githubusercontent.com/644927/98689600-600f7d00-236c-11eb-9a37-b96518247457.png)
