### ISSUE TITLE
Unsigned numbers are not working for MySQL queries

### ISSUE THREAD

**Issue by nyoungac** [jOOQ/jOOQ#10919]
### Your question:

Having trouble with the representation of unsigned values being sent in the a request to MySQL not working. When viewed through ProxyDataSourceBuilder logQueryBySlf4j shows the values as ([B@###### and aren't able to match. This appears to be the case for UINTEGER, ULONG, and UBYTE at least. Is there some setting that I may need?

```
Query:["SELECT foo.id FROM foo WHERE EXISTS (SELECT 1 FROM bar WHERE ((bar.foodid = foo.id AND bar.status = ?) OR EXISTS (SELECT 1 FROM baz, bar WHERE (baz.subscriberid = foo.id AND baz.d_id = bar.id AND bar.status = ?)))) ORDER BY foo.id limit ?"], Params:[([B@56116d7d,[B@4b81be61,100)]
```

Generator configured field:
```
public final TableField<DealRecord, UByte> STATUS = createField(DSL.name("status"), SQLDataType.TINYINTUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINTUNSIGNED)), this, "");

```

### Versions:

- jOOQ: 3.15
- Java: 11
- Database (include vendor): MySQL 5.7
- OS: MacOS
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your request. I'm not aware of any bugs/regressions in this area.

Can you please show a complete example to help reproduce the issue? I'm missing:

- DDL for your table
- The jOOQ code that you wrote

**Comment by nyoungac** [comment]
we're creating a trimmed down example to share

One thing that i forgot to mention is that we generate a jpa query based on select.getSQL() from jooq and set the parameters based on getBindValues, so that may be (probably is) the source of the issue

**Comment by lukaseder** [comment]
Yes, JPA doesn't know how to bind these jOOQ types out of the box. You could create a Hibernate user type for those, or tell jOOQ not to generate them on the jOOQ generated code by using a data type rewrite from `TINYINTUNSIGNED` to `TINYINT`:
https://www.jooq.org/doc/latest/manual/code-generation/data-type-rewrites
