### ISSUE TITLE
Converter for int column in UDT causes UnsupportedOperationException("Class int is not supported") at DefaultBinding.java:3442

### ISSUE THREAD

**Issue by mel4tonin4** [jOOQ/jOOQ#10928]
### Expected behavior

It should work without throwing an exception, just like when it's used to convert a column of table row, instead of a component of a compound UDT.

### Actual behavior

It throws:

```java.lang.UnsupportedOperationException: Class int is not supported```

at `DefaultBinding.java:3442`

### Steps to reproduce the problem

Build and run the following MCVE: [https://github.com/mel4tonin4/jOOQ-mcve-int-converter-failure-in-udt](https://github.com/mel4tonin4/jOOQ-mcve-int-converter-failure-in-udt)

### Versions

- jOOQ: 3.13.5
- Java: runtime 11, jvmTarget = '1.8'
- Database (include vendor): Postgresql 10.9 (Ubuntu 10.9-0ubuntu0.18.10.1)
- OS: Ubuntu 20.04.1 LTS
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.14

### Notes:

The MCVE is modeled after the official jOOQ-mcve project but is built with gradle with groovy scripts and jOOQ is configured via the nu.studer.jooq plugin. Flyway is used to handle the generation of the reference database.

Is this format of MCVE acceptable?

**Comment by lukaseder** [comment]
Thank you very much for your report, and for the MCVE! That looks similar to https://github.com/jOOQ/jOOQ/issues/10808. Great to have a head start to reproduce this. Will revert with feedback, soon.

**Comment by lukaseder** [comment]
Yes, confirmed, it's the same issue as #10808

**Comment by lukaseder** [comment]
As suspected in the other issue, a part of the problem is your usage of `Int` (Java `int`) instead of `Int?` (Java `Integer`). This converter would have worked:

```kotlin
package com.github.mel4tonin4.mcve

import org.jooq.Converter
import org.jooq.impl.SQLDataType

class IntMyValueConverter : Converter<Int?, MyValue> {
    override fun from(databaseObject: Int?): MyValue? =
        databaseObject?.let { MyValue(it) }

    override fun to(obj: MyValue?): Int? =
        obj?.value

    override fun fromType(): Class<Int?> =
        SQLDataType.INTEGER.type

    override fun toType(): Class<MyValue> =
        MyValue::class.java
}
```

The second test still doesn't work though, might be an unrelated bug.

**Comment by mel4tonin4** [comment]
There are two query in the main function. Both are working correctly with your converter using `Int?` and `SQLDataType.INTEGER.type` on my system.

And thanks!

**Comment by lukaseder** [comment]
> The MCVE is modeled after the official jOOQ-mcve project but is built with gradle with groovy scripts and jOOQ is configured via the nu.studer.jooq plugin. Flyway is used to handle the generation of the reference database.
> 
> Is this format of MCVE acceptable?

Sure it is, I appreciate the effort.

At some point, there might be an MCVE template using that third party gradle plugin.

Since you're asking, in general, if the issue isn't really related to Gradle or that plugin, I would definitely save a lot of time if the Maven configuration were used. I sunk another hour on this now...

**Comment by mel4tonin4** [comment]
>  Both are working correctly

Previously the first (converting a column of a table) worked, while the second failed.

**Comment by lukaseder** [comment]
E.g. there's something in IntelliJ that prevents correctly switching between jOOQ versions in your MCVE without restarting IntelliJ :( I can confirm that with my version of the converter, and after restarting IntelliJ a few times, both queries now work fine.

**Comment by lukaseder** [comment]
> > Both are working correctly
> 
> Previously the first (converting a column of a table) worked, while the second failed.


OK, since you can confirm this erratic behaviour, I'd say, I'll blame it on gradle and some weird cache

**Comment by lukaseder** [comment]
Anyway, I know how to reproduce https://github.com/jOOQ/jOOQ/issues/10808. I'll just fix that directly with the usual integration test setup. I currently won't chase the other issue.

Thanks again!
