### ISSUE TITLE
LIMIT without OFFSET is emulated using window functions when value is not a bind variable

### ISSUE THREAD

**Issue by pauljohn32** [jOOQ/jOOQ#10931]
Here is my input:

```sql
SELECT FRED, Bill, rodger FROM A LIMIT 1;
```

Look what your gives back for DB2:

```sql
SELECT
  "v0" fred,
  "v1" bill,
  "v2" rodger
FROM (
  SELECT
    fred "v0",
    bill "v1",
    rodger "v2",
    row_number() OVER (ORDER BY 1 ASC) "rn"
  FROM a
) "x"
WHERE "rn" > 0
AND "rn" <= 1
```

I think correct DB2 code is

```sql
SELECT  FRED, Bill, rodger FROM A
  FROM A
  FETCH FIRST 1 ROWS ONLY;
```

or possibly

```sql
SELECT  FRED, Bill, rodger FROM A
  FROM A
  OPTIMIZE FOR 1 ROWS;
```

**Comment by lukaseder** [comment]
Thanks a lot for your report. Indeed, we generate the wrong SQL when you're using an inline `LIMIT 1` value as opposed to a bind value `LIMIT ?`. By default, jOOQ uses bind values everywhere, including the `LIMIT` clause, which is probably why this has gone unnoticed as most people use jOOQ with the DSL API.

But when parsing / translating queries on https://www.jooq.org/translate, then bind values are usually not being used.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.15.0. We'll publish a new snapshot version to https://www.jooq.org/translate today. Thanks again for your report!

**Comment by lukaseder** [comment]
Related issue: https://github.com/jOOQ/jOOQ/issues/7335

**Comment by lukaseder** [comment]
Deployed. It's correct now:

![image](https://user-images.githubusercontent.com/734593/99058277-443eed80-259d-11eb-809a-f0762a426d29.png)
