### ISSUE TITLE
Support ARRAY_AGG in H2

### ISSUE THREAD

**Issue by SebastianS90** [jOOQ/jOOQ#10974]
### Expected behavior
The `@Support` annotation on `DSL.arrayAgg` should contain `H2`.
H2 supports `array_agg` since version 1.4.197 (2018-03-18).
See the [H2 documentation](https://www.h2database.com/html/functions-aggregate.html#array_agg), the [PR implementing it](https://github.com/h2database/h2database/pull/967), and the [changelog](https://www.h2database.com/html/changelog.html).

### Actual behavior
The `@Support` annotation on `DSL.arrayAgg` does not contain `H2`.
However, according to `git blame`, it was never touched since it was initially introduced by 759daa2a on 2015-01-20 (the implementation in H2 was later).

`DSL.array_agg` is actually working with H2, expect for `jooq-checker` complaining because of the missing `@Support` entry.

### Versions

- jOOQ: 3.14.3
- Database: H2  >= 1.4.198 (2019-02-22)

**Comment by lukaseder** [comment]
Thanks a lot for your report. That's great news!

I'll fix this immediately.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.4 (#10975)
