### ISSUE TITLE
LocalDateTime (jsr310) and fasterxml

### ISSUE THREAD

**Issue by iceback** [jOOQ/jOOQ#10981]
### Your question:
How to make jsr310 (java.time) work with jOOQ and fasterxml? Or is this really a jackson issue?

I incorporated the jsr310 types in the generator as follows:
```
        generator {
	  name = 'edu.utah.camplab.jooq.JxonAnnotationGenerator'
	  database {
	    forcedTypes {
	      forcedType {
		userType = 'java.util.LocalDateTime'
		converter = 'edu.utah.camplab.jooq.DateTimeConverter'
		includeExpression = '.*timestamp.*'
	      }
	    }
	    name = 'org.jooq.meta.postgres.PostgresDatabase'
``` 
The generated classes use LocalDateTime as expected.  The error I get when deserializing is

```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Expected array or string.
at [Source: (org.apache.catalina.connector.CoyoteInputStream); line: 1, column: 182] 
(through reference chain: 
edu.utah.camplab.jx.PayloadFromMux["processBlock"]->
edu.utah.camplab.jx.ProcessBlock["process"]->
edu.utah.camplab.db.generated.default_schema.tables.pojos.Process["pit"])
```

### Versions:
- jOOQ:3.13
- Java: OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
- Database (include vendor): postgres 12
- OS: ubuntu 20.04
- JDBC Driver (include name if inofficial driver): postgresql/42.2.18 (org.postgresql.Driver)

Gradle 6/ with  plugin "nu.studer.jooq" version "5.0.1"

**Comment by iceback** [comment]
I left off, from my Discus attempt,that I created a Converter based on the manual page,but am not clear how to apply it (when/where)?  Can't register it with ObjectMapper.

**Comment by lukaseder** [comment]
Thanks for your message.

I don't think there's anything that wouldn't work out of the box in this area, but it's hard to tell from your example. How can this be reproduced? We have a template to help provide examples that make sure reproduction is possible, see: https://github.com/jOOQ/jOOQ-mcve

**Comment by iceback** [comment]
I’m waiting on the next pot of coffee and a couple more checks here. 1. Remove timestamp column 2. Review diffs of usage of ts. Then I’ll clone the mvce . Or not. 

Will there someday be a way to use gradle in mvce
?

**Comment by lukaseder** [comment]
Yes, some day there will be.

You don't have to use the MCVE. Any information / example code that can help reproduce the issue will be good.

**Comment by iceback** [comment]
Progress.  I've eliminated jOOQ from the stacktrace.  Only jackson and 
myself left to blame.

I think we can close this.  I'll have to work on the fasterxml side of 
things.

15:44:11.299 [main] INFO edu.utah.camplab.app.LoadCrashpadJson - 
Crashpad import commencing.
15:44:11.477 [main] ERROR edu.utah.camplab.app.LoadCrashpadJson - file 
handling issues:
Cannot construct instance of `java.time.LocalDateTime` (no Creators, 
like default constructor, exist):
cannot deserialize from Object value (no delegate- or property-based 
Creator)
  at [Source: (BufferedReader); line: 1, column: 183] (through reference 
chain:
edu.utah.camplab.jx.PayloadFromMux["processBlock"]
->edu.utah.camplab.jx.ProcessBlock["process"]
->edu.utah.camplab.db.generated.default_schema.tables.pojos.Process["pit"])

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot 
construct instance of `java.time.LocalDateTime` (no Creators, like 
default constructor, exist): cannot deserialize from Object value (no 
delegate- or property-based Creator)

  at [Source: (BufferedReader); line: 1, column: 183] (through reference 
chain: 
edu.utah.camplab.jx.PayloadFromMux["processBlock"]->edu.utah.camplab.jx.ProcessBlock["process"]->edu.utah.camplab.db.generated.default_schema.tables.pojos.Process["pit"])
