### ISSUE TITLE
Feedback about manual section seek-clause

### ISSUE THREAD

**Issue by lasjen** [jOOQ/jOOQ#10987]
In your documentation you mention the following SQL:

```sql
SELECT id, value
FROM t
WHERE (value, id) > (2, 533)
ORDER BY value, id
LIMIT 5
```

The ORDER BY is done after the WHERE clause, and I would question the correctness of this query.

**Comment by lukaseder** [comment]
The query looks correct to me. Why do you think it's wrong?

**Comment by lukaseder** [comment]
I think the query is correct. That's what jOOQ generates for the corresponding `SEEK` clause. Let me know if you still think there's anything is worth addressing.
