### ISSUE TITLE
Compilation error in KotlinGenerator generated code when enum literals conflict with modifier keywords

### ISSUE THREAD

**Issue by ethanttbui** [jOOQ/jOOQ#10997]
In my schema, I have an enum field that accepts an "open" literal value.
jOOQ, therefore, generated this code: 
```
    open("open"),
    preparing("preparing");
```
But in Kotlin, we have a global `open` method https://kotlinlang.org/api/latest/jvm/stdlib/org.w3c.dom/-window/open.html
As a result, this const is misunderstood by the Kotlin compiler.

Can we make sure that enums are all upper cases? Or use a different syntax to specify them.

##Versions
version: 3.14.3
java: JDK 1.8
kotlin: 1.4.10
spring boot: 2.4.0

**Comment by lukaseder** [comment]
Thanks for your report. I think that's because of the `open` soft keyword? https://kotlinlang.org/docs/reference/keyword-reference.html

In any case, it's certainly not a bad idea to update our keyword list in the code generator.

**Comment by lukaseder** [comment]
A fix has been committed as part of another issue:
https://github.com/jOOQ/jOOQ/commit/c4d3644872735293768e585bff9faef496d3eb26#diff-f9de5d0bee8707996cb0adb68894c54ffcbd8740058a28619413fae94e429bd9

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.4 (#11004). Thanks again for your report!

**Comment by ethanttbui** [comment]
Thank you for your clarification and quick action!
