### ISSUE TITLE
Postgres also requires unqualified relation names in a FOR UPDATE OF statement

### ISSUE THREAD

**Issue by doctorpangloss** [jOOQ/jOOQ#11006]
Reopens #4151 for Postgres in 3.14.3 and later.

Also seeing `relation X in FOR UPDATE clause not found in FROM clause`. Not 100% sure what's going on there, I can only seem to work around it by removing the field in the `OF` clause.

See https://github.com/sqlalchemy/sqlalchemy/issues/3573 

Anything that requires row-level locking in Postgres requires unqualified relation names, see https://github.com/postgres/postgres/blob/c71f9a094b32770dcd34b9ba4909435e34583747/src/backend/parser/analyze.c#L2788

CockroachDB is already fixed, see results from https://grep.app/search?q=unqualified%20relation%20names

Example from production code that produces error:

```
// gather tickets
// this will lock the rows that this matchmaker might match using the transaction, allowing other matchmakers
// to skip these easily naturally.
var records = await(transaction.findManyRow(dsl ->
		dsl.select(asterisk()).from(MATCHMAKING_TICKETS)
				.join(MATCHMAKING_QUEUES)
				.on(MATCHMAKING_TICKETS.QUEUE_ID.eq(MATCHMAKING_QUEUES.ID))
				// find only tickets that haven't been assigned
				.where(MATCHMAKING_TICKETS.GAME_ID.isNull())
				// retrieve the oldest tickets in a queue
				.orderBy(MATCHMAKING_TICKETS.QUEUE_ID.asc(), MATCHMAKING_TICKETS.CREATED_AT.asc())
				// only retrieve maxTickets at a time
				.limit(maxTickets)
				// lock, prevent others from grabbing these tickets during iteration
				.forUpdate().of(MATCHMAKING_TICKETS.GAME_ID).skipLocked()).onFailure(Throwable::printStackTrace))
		.stream().collect(groupingBy(r -> r.getString(MATCHMAKING_TICKETS.QUEUE_ID.getName())));
```

produces the error

```
io.vertx.pgclient.PgException: { "message": "FOR UPDATE must specify unqualified relation names", "severity": "ERROR", "code": "42601", "position": "380", "file": "analyze.c", "line": "2829", "routine": "transformLockingClause" }
```

Replacing `.of(MATCHMAKING_TICKETS.GAME_ID)` with `MATCHMAKING_TICKETS` resolves the issue, as does removing the `of` statement. I believe both are different meaning though, so that's not saying much.

**Comment by lukaseder** [comment]
Thanks for your report.

We already produce unqualified table names in PostgreSQL:
https://github.com/jOOQ/jOOQ/blob/version-3.14.3/jOOQ/src/main/java/org/jooq/impl/ForLock.java#L174-L176

Maybe you can share some code that helps reproduce this issue?

**Comment by doctorpangloss** [comment]
I'll try it again soon, I simply removed the `TABLE.FIELD` I was passing in.

**Comment by doctorpangloss** [comment]
@lukaseder updated with code

**Comment by lukaseder** [comment]
I see, you're using the `of(Field<?>...)` overload, but that isn't supported by PostgreSQL. See also the `@Support` annotation on the method:
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/SelectForUpdateOfStep.html#of(org.jooq.Field...)

Which is:

```java
@Support({DB2,DERBY,FIREBIRD,H2,HANA,HSQLDB,INFORMIX,INGRES,ORACLE,SYBASE})
```

You want to lock the table, call:

```java
.forUpdate().of(MATCHMAKING_TICKETS)
```

I hope this helps

**Comment by lukaseder** [comment]
I see you already said so:

> Replacing `.of(MATCHMAKING_TICKETS.GAME_ID)` with `MATCHMAKING_TICKETS` resolves the issue, as does removing the `of` statement. I believe both are different meaning though, so that's not saying much.

But if you already found the solution, what was your expectation here?

**Comment by lukaseder** [comment]
See also *"table_name"*:
https://www.postgresql.org/docs/current/sql-select.html

```
[ FOR { UPDATE | NO KEY UPDATE | SHARE | KEY SHARE } [ OF table_name [, ...] ] [ NOWAIT | SKIP LOCKED ] [...] ]
```
