### ISSUE TITLE
JSON_TABLE emulation in PostgreSQL broken

### ISSUE THREAD

**Issue by mkurz** [jOOQ/jOOQ#11014]
jOOQ 3.14.3
openjdk version "11.0.8" 2020-07-14
Postgres 13

Using **_exactly_** the example from https://www.jooq.org/doc/3.14/manual/sql-building/table-expressions/json-table-function/:

```java
// For more information on imports and data types, click on the "Help" icon
// These imports, and possibly others, are implied:
import static org.jooq.impl.DSL.*;
import static org.jooq.impl.SQLDataType.*;
import org.jooq.*;
import org.jooq.impl.*;

// The "create" reference is an instance of DSLContext

create.select()
      .from(jsonTable(
          JSON.valueOf("[{\"a\":5,\"b\":{\"x\":10}},"
                      + "{\"a\":7,\"b\":{\"y\":20}}]"),
          "$.[*]"
        )
        .column("id").forOrdinality()
        .column("a", INTEGER)
        .column("x", INTEGER).path("$.b.x")
        .column("y", INTEGER).path("$.b.y"))
      .fetch();
```

fails with following error:

```
ERROR:  subquery in FROM must have an alias at character 33
HINT:  For example, FROM (SELECT ...) [AS] foo.
STATEMENT:  select "id", "a", "x", "y" from (select o as "id", (jsonb_path_query_first(j, '$.a'::jsonpath)->>0)::int as "a", (jsonb_path_query_first(j, $1::jsonpath)->>0)::int as "x", (jsonb_path_query_first(j, $2::jsonpath)->>0)::int as "y" from jsonb_path_query(cast($3 as jsonb), $4::jsonpath) with ordinality as t(j, o))
```

BTW: The imports in the example are also not correct. The following two imports have a conflict:
```java
import static org.jooq.impl.SQLDataType.*;
import org.jooq.*;
```
both provide `JSON` as a datatype and as class. The fix is to either just import
```java
import static org.jooq.impl.SQLDataType.INTEGER;
```
because only `INTEGER` is used in the concret example, or to use
```java
...
          org.jooq.JSON.valueOf("[{\"a\":5,\"b\":{\"x\":10}},"
...
```
in the example.

**Comment by lukaseder** [comment]
Thanks for your report.

This is probably due to a bug: https://github.com/jOOQ/jOOQ/issues/11020. We should be able to generate synthetic aliases for `JSON_TABLE` when users don't specify one explicitly. In the meantime, I'll fix the manual to have an explicit alias.

> BTW: The imports in the example are also not correct. The following two imports have a conflict:

Hah, how unfortunate :) The imports are generated automatically based on content. There's also `JSON.json()` which could be static imported for these examples...

**Comment by lukaseder** [comment]
Fixed.  The manual will be updated in ~1h. Thanks again.
