### ISSUE TITLE
KotlinGenerator should generate equals(other: Any?), not equals(obj: Any?) on pojos

### ISSUE THREAD

**Issue by svilenivanovsmule** [jOOQ/jOOQ#11017]
### Expected behavior
No warning during compilation

### Actual behavior
Kotlin compiler (1.4.20) produces the following warning
> The corresponding parameter in the supertype 'Serializable' is named 'other'. This may cause problems when calling this function with named arguments.

The culprit seems to be that argument name `obj` of the `equals(...)` method. The supertype's argument name is `other`:
```kotlin
public open operator fun equals(other: Any?): Boolean
```

### Steps to reproduce the problem
Enable `KotlinGenerator` along with `pojosEqualsAndHashCode`

### Versions

- jOOQ: 3.14.3
- Java: 11
- Database (include vendor): MySQL 8
- OS: Linux
- JDBC Driver (include name if inofficial driver): ConnectorJ/8.0.22

**Comment by lukaseder** [comment]
Thanks for your report. That's unfortunate. The `Object.equals()` method in Java calls the parameter `obj`. If Java ever introduces named parameters, there will be a problem in kotlin...

Anyway, we can change this for kotlin only, of course.

**Comment by lukaseder** [comment]
The warning seems to be misleading. This is because of `kotlin.Any`, not because of `Serializable`

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.4 (#11019)
