### ISSUE TITLE
Is it possible to generate named parameters rather than index based parameters for insert statement?

### ISSUE THREAD

**Issue by araknafobia** [jOOQ/jOOQ#11034]
I am using JOOQ to generate SQL statements to use with R2DBC.

I am trying to create an insert statement and I would like to stay away from index based parameters as much as possible but I could not make it working so far. I tried to following code;

```
  val dslContext = DSL.using(SQLDialect.POSTGRES, Settings().withRenderNameCase(RenderNameCase.LOWER))
  val sql = dslContext.insertInto(User.USER)
             .set(User.USER.EMAIL, "")
             .set(User.USER.USERNAME, "")
             .set(User.USER.PASSWORD, "")
             .getSQL(ParamType.NAMED)
  println(sql) // insert into "user" ("email", "username", "password") values (:1, :2, :3)
```

Is there a way to make generated SQL to use named parameters like `:email, :username, :password`?

- jOOQ: 3.14.0

**Comment by lukaseder** [comment]
Yes, you can provide the name yourself:

```kotlin
val sql = dslContext.insertInto(User.USER)
             .set(User.USER.EMAIL, param("email", ""))
             .set(User.USER.USERNAME, param("username", ""))
             .set(User.USER.PASSWORD, param("password", ""))
             .getSQL(ParamType.NAMED)
```

See: https://www.jooq.org/doc/latest/manual/sql-building/bind-values/named-parameters/
