### ISSUE TITLE
Query parameters are rendered when a query is used in CREATE VIEW statement

### ISSUE THREAD

**Issue by joseahr** [jOOQ/jOOQ#11048]
### Expected behavior
Calling `DSL.createOrReplaceView("my_view").as(query).getSQL();`
Should produce `CREATE OR REPLACE VIEW my_view AS SELECT ... WHERE (a, b) IN ((?, ?), (?, ?), ...)`

### Actual behavior
Calling `DSL.createOrReplaceView("my_view").as(query).getSQL();`
produces `CREATE OR REPLACE VIEW my_view AS SELECT ... WHERE (a, b) IN (('a', 'b'), ('c', 'd'), ...)`

### Steps to reproduce the problem
Create a `CreateViewFinalStep` with a `Select<?>` as the "as" parameter and get the rendered SQL.

### Versions

- jOOQ: 3.14.3
- Java: 1.8.0_251
- Database (include vendor): Using Postgres dialect without data source nor connection

**Comment by lukaseder** [comment]
What does it mean for a view to contain bind parameter markers? What would you expect the behaviour would be when you fetch data from this view?

I don't think any RDBMS supports bind variables in views, and if they did, they would have to do the same thing as jOOQ does: Inline them at definition time. You can try this in PostgreSQL, it doesn't work:

```java
try (PreparedStatement s = c.prepareStatement("create view v as select ?::int as a")) {
    s.setInt(1, 1);
    s.executeUpdate();
}
```

**Comment by joseahr** [comment]
Well, the use case is: 
- We define views for domain objects with its own filters, so that each user has its own views that define its privileges. (Assuming Row-Level Policies can not be used).

You're right, it seems this is not supported by the driver. Surprisingly executing the query throught `DSLContext#execute` with a valid connection seems to work for:

```java
DSL.query("CREATE OR REPLACE VIEW {0} AS {1}", DSL.quotedName(view), query);
```

Calling `getSQL` in the above query produces `?` wildcards for bind values. Maybe, JOOQ is rendering the bind values in the end? Anyway, as a workaround, we can easily create a stored procedure to handle this situation.

Thanks for the help, Lukas!

**Comment by lukaseder** [comment]
> Calling `getSQL` in the above query produces `?` wildcards for bind values

Yes, because in that case, jOOQ doesn't know you're creating a view and thus generates invalid SQL.

> Anyway, as a workaround, we can easily create a stored procedure to handle this situation.

Indeed. Views are static and don't allow for parameters. Table valued functions do, and jOOQ can generate nice code for those as well!
