### ISSUE TITLE
Bug in documentation for JSON_TABLE

### ISSUE THREAD

**Issue by mkurz** [jOOQ/jOOQ#11041]
See https://www.jooq.org/doc/3.14/manual/sql-building/table-expressions/json-table-function/

The SQL on the left side and the jOOQ example on the right side are not synced.
Left the json path is: `$[*]` (which is correct)
Left the json path is: `$.[*]` (which is NOT correct, needs to be fixed)

**Comment by lukaseder** [comment]
Thank you very much for your report
