### ISSUE TITLE
Pull up PostgresDSL.array() to DSL.array()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11053]
PostgreSQL can aggregate subquery results into arrays using:

```sql
select
  array(
    select c
    from t
    order by o
  ) as c
```

This is currently supported as `PostgresDSL.array()`. It would be useful to pull up this function and emulate it in other dialects as:

```sql
select 
  (
    select array_agg(c)
    from (
      select c
      from t
      order by o
    ) t
  ) as c
```

Of course, the usual restrictions regarding correlating subqueries over 2 levels of scope will apply, e.g. in H2

**Comment by lukaseder** [comment]
This will be a binary incompatible change, as the static method will be removed from `PostgresDSL`

**Comment by katzyn** [comment]
It looks like non-standard select without `FROM` with standard `<array value constructor by query>` in its list.

HSQLDB needs standard-compliant
```SQL
values
  array(
    select c
    from t
    order by o
  );
```
Current H2 supports both standard and non-standard variants.

**Comment by lukaseder** [comment]
As you know, jOOQ generates the `FROM` clause when it's needed. But this isn't about `SELECT` without `FROM`, only about the array constructor.

Interesting, I haven't found any reference to it in the docs:

- http://h2database.com/html/grammar.html?highlight=array&search=array#firstFound
- http://h2database.com/html/functions.html?highlight=array&search=array#firstFound
- http://h2database.com/html/functions-aggregate.html?highlight=ARRAY_AGG&search=array#firstFound

Is it not documented?

**Comment by lukaseder** [comment]
Or do you mean the next unreleased version by "current H2"?

**Comment by lukaseder** [comment]
I don't get this syntax to work on HSQLDB 2.5.1, either...

**Comment by katzyn** [comment]
Yes, I meant H2 built from current sources, will be released as 2.0.202. For the latest released 1.4.200 you need emulation with `ARRAY_AGG`. Hypothetically emulation can be flattened to `select array_agg(c) from t order by o`, but it requires transformation of inner query and it isn't applicable to every query, only to simple ones.

With HSQLDB 2.5.1
```SQL
create table test(v int);
insert into test values 1, 2;
values array(select v from test order by v);
```
works well and returns the expected `ARRAY[1,2]. Am I missing something?

**Comment by lukaseder** [comment]
> Hypothetically emulation can be flattened to `select array_agg(c) from t order by o`, but it requires transformation of inner query and it isn't applicable to every query, only to simple ones.

I will forever regret simplifying examples in my issues ;-)

> With HSQLDB 2.5.1 [...]

You're right. I made a mistake...

**Comment by lukaseder** [comment]
In fact, the emulation might be more complicated in the presence of `ORDER BY`. For example:

```sql
select
  array(
    select c
    from t
    order by o
  ) as c
```

Would actually be:

```sql
select 
  (
    select array_agg(c order by o) -- Order by moved from subquery to array_agg
    from (
      select c, o -- Adapted projection
      from t
    ) t
  ) as c
```

**Comment by lukaseder** [comment]
The `ORDER BY` part will not be implemented now. It might be implemented later. On the other hand, given that the emulation is currently applied to H2 only, and H2 will support the standard syntax soon, we might not need the correct emulation.
