### ISSUE TITLE
Retrieve lazy iterator 

### ISSUE THREAD

**Issue by Nhoutain** [jOOQ/jOOQ#11065]
### Your question:

Hi,

I observe some strange behavior when using the JOOQ library. I'm not sure that there is issue, may be I'm using it in a wrong way..

I currently fetch data like
```
Cursor cursor = dsl
   .select()
   .from()
   .fetchSize(500)
   .fetchLazy();
```

After that, I need iterator for my business requirement (instead of stream). I try two solution:
```
cursor.iterator()
```
-> Here I don't see the fetch by the given size applied. I only see a global fetch query 

```
Iterator iterator = cursor.iterator()
while(iterator.hasNext()) {
   iterator.fetchNext()
}
```
-> Here I see the fetch one by one. 

---

* I'm surprising that the `.iterator()` don't work lazily
* I'm surprising that the `.fetchNext()` is not based on the fetchSize. I expect something that fetch on the fetchSize and give me the next record (without fetch them one by one)

Where is my mistake here?

Thanks a lot!

### Versions:

- jOOQ: 3.13.14
- Java: 8
- Database (include vendor): Postgresql (aurora AWS)

**Comment by Nhoutain** [comment]
I write a little bit early.

Indeed, I make deep search and I found in my sql log the query on the cursor for the `iterator()`


My bad

**Comment by lukaseder** [comment]
Thanks for your message

> * I'm surprising that the `.iterator()` don't work lazily

I'm not sure what you mean by this. `Cursor::iterator` doesn't do anything with the underlying `ResultSet`. It just gives you a handle that you can iterate upon. Your two examples aren't really different, both call `cursor.iterator()`, so I'm not sure why you'd observe a difference.

> * I'm surprising that the `.fetchNext()` is not based on the fetchSize. I expect something that fetch on the fetchSize and give me the next record (without fetch them one by one)

The `ResultQuery::fetchSize` call is passed on to JDBC `Statement::setFetchSize`. It tells the JDBC driver how many rows it should buffer. This is not related to how many rows *you* request from the `Cursor` in one go. `Cursor::fetchNext` fetches a number of rows per call. The default being 1. Think of it as equivalent to `ResultSet::next`, with the added convenience of being able to specify how many rows you want to fetch from JDBC in one go.

**Comment by Nhoutain** [comment]
My bad, I make some error in my comment.

The difference appear between
```
Iterator iterator = cursor.iterator()
while(iterator.hasNext()) {
   iterator.fetchNext()
}
```
and 
```
cursor.fetchNext();
```

**Comment by lukaseder** [comment]
I'm sorry, I'm not sure if there's anything left to look at from my side? Calling `cursor.fetchNext()` or `iterator.next()` should have the same effect...

**Comment by Nhoutain** [comment]
Hi, 
Thanks for all quick answer. To answer to your question, there is no need for me.

But, when I perform some test, I see two distinct effect.
* (A) `cursor.fetchNext()` fetch directly a row in DB. If I use that in an iterator, I will fetch all row from the DB one by one (completely inefficient, of course). Without taking care of the fetch size.
* (B) `cursor.iterator()` and then `iterator.next()` will use the cursor to fetch data by the given fetch size.

Given a fetch size of 10 and a table with 23 rows, when I use (A), I see 23 fetch of one row in DB, when use (B) I see 3 fetch of the fetch size in DB.

If you expect that both side should have the same effect, I guess there is some issue on (A).

**Comment by lukaseder** [comment]
Yes, I expect there to be no difference. `cursor.fetchNext()` internally calls `iterator().hasNext()` and `iterator().next()`. See `CursorImpl.fetchNext(int)`: https://github.com/jOOQ/jOOQ/blob/version-3.14.4/jOOQ/src/main/java/org/jooq/impl/CursorImpl.java#L340-L358

I've looked at various code snippets you've provided so far, some of which don't compile (e.g. there's no `iterator.fetchNext()` method). You haven't indicated how you discovered the difference (using a profiler? Using server side logs? Using a JDBC proxy?) Ideally, for me to reproduce this, may I ask you to provide an MCVE, e.g. following this template? https://github.com/jOOQ/jOOQ-mcve

**Comment by Nhoutain** [comment]
I will have a look at this :)
