### ISSUE TITLE
AbstractRecord get(xxx) performance for ad-hoc RecordImpl classes

### ISSUE THREAD

**Issue by arlampin** [jOOQ/jOOQ#11064]
It seems that currently `AbstractRecord.get(Field<T> field)` and lots of other `get(xxx)` variants call `fieldsRow()` just to get index of given field. This seems wasteful, since for RecordImpl1 ... RecordImpl22 `fieldsRow()` constructs not only one but two new objects (`RowImplXxx` and `Fields`).
This seems especially wasteful since AbstractRecord has `fields` instance field available and that is already used directly by `set(Field<T> field, T value)` method, and is actually the source for `fieldsRow()` data in the first place.

**Comment by lukaseder** [comment]
Thanks a lot for your report. This is currently being fixed in #11058.

**Comment by lukaseder** [comment]
The switch to produce different types of `RecordImpl[N]` and `RowImpl[N]` has been introduced with https://github.com/jOOQ/jOOQ/issues/4695 in jOOQ 3.14.

**Comment by lukaseder** [comment]
The topics are related nonetheless. The issues mentioned here will be addressed in #11058
