### ISSUE TITLE
Default Value in mysql  innodb 5.6

### ISSUE THREAD

**Issue by adam-fu** [jOOQ/jOOQ#11069]
Jooq throws an exception when inserting or updating fields with null value.

I have a mysql table with non-null default value:
```
CREATE TABLE `cars` (
  `model` varchar(100) DEFAULT NULL,
  `km_driven` int(11) NOT NULL DEFAULT '0',
  UNIQUE KEY `u_car_driven` (`model`, `km_driven`)
) ENGINE=MyISAM DEFAULT CHARSET=UTF8
```

When inserting
```
insert into `cars` (
  `model`, 
  `km_driven`
)
values (
  'Fiat',
  null
)
```
I get the following error:
```java.sql.SQLIntegrityConstraintViolationException: Column 'km_driven' cannot be null```

I expected that the record will be inserted with the default value for the second field.

Jooq generated the right code:
```
createField(DSL.name("km_driven"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "");
```
But it seams to have a problem with inserting and updating the records for MySQL innodb version 5.6.31.

Tested with jooq version 3.13.1 and 3.14.4

**Comment by lukaseder** [comment]
Thanks a lot for your suggestion. We could add support for MySQL 5.6, we currently don't. I've created an issue for this: https://github.com/jOOQ/jOOQ/issues/11076. Will check how much work that is.

May I ask, what's the reason for sticking with such an old version (and even with 5.6, the latest patch release is 5.6.50)?

**Comment by lukaseder** [comment]
This isn't really a version problem. The problem is that if you specify an explicit `NULL` value in an `INSERT` statement, then the `DEFAULT` doesn't apply. How are you constructing this `INSERT` statement? Can you show your jOOQ code?

**Comment by adam-fu** [comment]
Hi @lukaseder ,
thanks for your support. The version was an old testing db. 
To stick with the above example our code looks like this:
```
     DSLContext query = DSL.using(dataSource, SQLDialect.MYSQL);
        // ..
        return query
                .insertInto(T_CAR)
                .set(CAR.KM_DRIVEN, car.getKmDriven()) // can be null
                .set(CAR.MODEL, car.getModel())
```
The update query is very similar.  So we insert all attributes explicitly, some of them can be null. The same code does not cause any issues on a h2 database and I guess no issue for modern mysql versions 8 and above.

So even with explicit null values as parameters mysql should then insert default ones.
On the same server the generated query causes an error with Jooq while works with a sql client (sequel pro).

**Comment by lukaseder** [comment]
> The same code does not cause any issues on a h2 database and I guess no issue for modern mysql versions 8 and above.

Are you sure about this? I'm trying this on H2 1.4.200 (or any dialect, really, including MySQL 8), and it fails as expected:

```sql
CREATE TABLE cars (
  model varchar(100) DEFAULT NULL,
  km_driven int(11) NOT NULL DEFAULT '0',
  UNIQUE u_car_driven (model, km_driven)
);

insert into cars (
  model, 
  km_driven
)
values (
  'Fiat',
  null
);
```

MySQL 8:

> SQL-Fehler [1048] [23000]: Column 'km_driven' cannot be null

H2:

> SQL-Fehler [23502] [23502]: NULL nicht zulässig für Feld "KM_DRIVEN" NULL not allowed for column "KM_DRIVEN"; SQL statement:

You must be doing something differently between your dialects.

This works as designed. You have several options:

1. Don't set the `null` value on the `insert` statement
2. Use `set(CAR.KM_DRIVEN, car.getKmDriven() == null ? DSL.default_(CAR.KM_DRIVEN) : car.getKmDriven())` (this produces a `DEFAULT` keyword in your `INSERT` statement)
3. Use `set(CAR.KM_DRIVEN, car.getKmDriven() == null ? CAR.KM_DRIVEN.getDataType().default_() : DSL.val(car.getKmDriven()))` (this will repeat the table definition's default expression explicitly)

**Comment by adam-fu** [comment]
Hi @lukaseder , thanks for the analysis. I will use the method you suggested. I did not had a problem on h2 1.4.200. I see the generated query did had the explicit null value. But I see it only works by chance. So will stick to the suggested solution.
