### ISSUE TITLE
Update set does not work for timestamp

### ISSUE THREAD

**Issue by ethanttbui** [jOOQ/jOOQ#11084]
I am tried to run this simple query:
```
dsl.update(table)
    .set(TABLE.DELETED_AT, DSL.currentTimestamp())
    .where(conditions)
    .execute()
```
And got this from the compiler:
```
None of the following functions can be called with the arguments supplied: 
public abstract fun <T : Any!> set(p0: Field<TypeVariable(T)!>!, p1: TypeVariable(T)!): UpdateSetMoreStep<out Record!> defined in org.jooq.UpdateSetFirstStep
public abstract fun <T : Any!> set(p0: Field<TypeVariable(T)!>!, p1: Field<TypeVariable(T)!>!): UpdateSetMoreStep<out Record!> defined in org.jooq.UpdateSetFirstStep
public abstract fun <T : Any!> set(p0: Field<TypeVariable(T)!>!, p1: Select<out Record1<TypeVariable(T)!>!>!): UpdateSetMoreStep<out Record!> defined in org.jooq.UpdateSetFirstStep
public abstract operator fun <T1 : Any!, T2 : Any!, T3 : Any!, T4 : Any!, T5 : Any!, T6 : Any!, T7 : Any!, T8 : Any!, T9 : Any!, T10 : Any!> set(p0: Row10<TypeVariable(T1)!, TypeVariable(T2)!, TypeVariable(T3)!, TypeVariable(T4)!, TypeVariable(T5)!, TypeVariable(T6)!, TypeVariable(T7)!, TypeVariable(T8)!, TypeVariable(T9)!, TypeVariable(T10)!>!, p1: Row10<TypeVariable(T1)!, TypeVariable(T2)!, TypeVariable(T3)!, TypeVariable(T4)!, TypeVariable(T5)!, TypeVariable(T6)!, TypeVariable(T7)!, TypeVariable(T8)!, TypeVariable(T9)!, TypeVariable(T10)!>!): UpdateFromStep<out Record!> defined in org.jooq.UpdateSetFirstStep
public abstract operator fun <T1 : Any!, T2 : Any!, T3 : Any!, T4 : Any!, T5 : Any!, T6 : Any!, T7 : Any!, T8 : Any!, T9 : Any!, T10 : Any!> set(p0: Row10<TypeVariable(T1)!, TypeVariable(T2)!, TypeVariable(T3)!, TypeVariable(T4)!, TypeVariable(T5)!, TypeVariable(T6)!, TypeVariable(T7)!, TypeVariable(T8)!, TypeVariable(T9)!, TypeVariable(T10)!>!, p1: Select<out Record10<TypeVariable(T1)!, TypeVariable(T2)!, TypeVariable(T3)!, TypeVariable(T4)!, TypeVariable(T5)!, TypeVariable(T6)!, TypeVariable(T7)!, TypeVariable(T8)!, TypeVariable(T9)!, TypeVariable(T10)!>!>!): UpdateFromStep<out Record!> defined in org.jooq.UpdateSetFirstStep
public abstract operator fun <T1 : Any!, T2 : Any!, T3 : Any!, T4 : Any!, T5 : Any!, T6 : Any!, T7 : Any!, T8 : Any!, T9 : Any!, T10 : Any!, T11 : Any!> set(p0: Row11<TypeVariable(T1)!, TypeVariable(T2)!, TypeVariable(T3)!, TypeVariable(T4)!, TypeVariable(T5)!, TypeVariable(T6)!, TypeVariable(T7)!, TypeVariable(T8)!, TypeVariable(T9)!, TypeVariable(T10)!, TypeVariable(T11)!>!, p1: Row11<TypeVariable(T1)!, TypeVariable(T2)!, TypeVariable(T3)!, TypeVariable(T4)!, TypeVariable(T5)!, TypeVariable(T6)!, TypeVariable(T7)!, TypeVariable(T8)!, TypeVariable(T9)!, TypeVariable(T10)!, TypeVariable(T11)!>!): UpdateFromStep<out Record!> defined in org.jooq.UpdateSetFirstStep
public abstract operator fun <T1 : Any!, T2 : Any!, T3 : Any!, T4 : Any!, T5 : Any!, T6 : Any!, T7 : Any!, T8 : Any!, T9 : Any!, T10 : Any!, T11 : Any!> set(p0: Row11<TypeVariable(T1)!, TypeVariable(T2)!, TypeVariable(T3)!, TypeVariable(T4)!, TypeVariable(T5)!, TypeVariable(T6)!, TypeVariable(T7)!, TypeVariable(T8)!, TypeVariable(T9)!, TypeVariable(T10)!, TypeVariable(T11)!>!, p1: Select<out Record11<TypeVariable(T1)!, TypeVariable(T2)!, TypeVariable(T3)!, TypeVariable(T4)!, TypeVariable(T5)!, TypeVariable(T6)!, TypeVariable(T7)!, TypeVariable(T8)!, TypeVariable(T9)!, TypeVariable(T10)!, TypeVariable(T11)!>!>!): UpdateFromStep<out Record!> defined in org.jooq.UpdateSetFirstStep
...
```
I expect that it would match the first one, no?

Currently, I'm using this workaround as a temporary solution:
```
dsl.update(table)
    .set(
        mutableMapOf(
            deleteFlag.name to DSL.currentTimestamp()
        )
    )
    .where(conditions)
    .execute()
```

### Versions

- jOOQ: 3.14.1
- Java: JDK 1.8
- Kotlin: 1.4
- Database: MySQL, InnoDB
- OS: Mac
- IDE: IntelliJ 2020.1.2 (Ultimate)

**Comment by ethanttbui** [comment]
Ah, I just found out that MySQL's timestamp is actually translated to LocalDateTime in Java by jOOQ, so using `DSL.currentLocalDateTime()` will work.
I was confused mainly by this [StackOverflow thread](https://stackoverflow.com/questions/45704389/how-to-set-cuurent-db-time-in-jooq-record-object), which seems to have been outdated.

I will close the issue. Sorry for the trouble.

**Comment by lukaseder** [comment]
> Ah, I just found out that MySQL's timestamp is actually translated to LocalDateTime in Java by jOOQ

That would depend on your code generation setting for `<javaTimeTypes/>`

> I was confused mainly by this [StackOverflow thread](https://stackoverflow.com/questions/45704389/how-to-set-cuurent-db-time-in-jooq-record-object), which seems to have been outdated.

I can see how this can be confusing, given that we've changed the default value for `<javaTimeTypes/>`. Could we have made this easier for you to discover, e.g. with documentation, etc.?

**Comment by ethanttbui** [comment]
I personally find the document a bit hard to navigate. Relevant content sometimes is scattered over multiple sections. For example, these 2 sections might better be together:
https://www.jooq.org/doc/3.14/manual/code-generation/codegen-configuration/
https://www.jooq.org/doc/3.14/manual/code-generation/codegen-gradle/

Currently, I am mainly relying on Google search to navigate the doc, which is not reliable of course. Maybe a search function would help. The UI can be a bit more user-friendly too, something like the [Laravel doc](https://laravel.com/docs/8.x) would be beautiful. Right now there is just a long list of sections, which is a bit overwhelming to get started with.

I understand that some of these changes can be time-consuming. If it's not of high priority, the time is still better spent on improving the framework ;)

**Comment by lukaseder** [comment]
While I agree that things that belong together should be documented together, I still think that things that don't belong together (this issue about `UPDATE .. SET` and the quite unrelated issue about code generation configuration) should remain separate 😉.

> For example, these 2 sections might better be together:

I see what you mean. I'll think about this specific case. The first section you've mentioned is very old and hasn't  been retrofitted. For example, the whole Eclipse setup part could be extracted in its own section as well, for those who actually want to do that (most don't). Let's discuss this in a separate issue: https://github.com/jOOQ/jOOQ/issues/11090

> Currently, I am mainly relying on Google search to navigate the doc, which is not reliable of course

Can you please create a new feature request for this?

**Comment by lukaseder** [comment]
@ethanttbui In fact, the search feature request already has an issue: https://github.com/jOOQ/jOOQ/issues/2309

**Comment by ethanttbui** [comment]
> I still think that things that don't belong together (this issue about `UPDATE .. SET` and the quite unrelated issue about code generation configuration) should remain separate
Yes, the point I made above was not directly related to this case. It's just a general impression actually. Sorry about the confusion.

> Let's discuss this in a separate issue: #11090
Got it!

> In fact, the search feature request already has an issue: #2309
Ohh, good to know. I'll be looking forward to it. :D
