### ISSUE TITLE
Ability to define a custom user type with a generic signature

### ISSUE THREAD

**Issue by robfletcher** [jOOQ/jOOQ#11112]
### Use case:

I have several places where I use `JSON` columns. In one case the associated class property is a `Map<String, Any?>` and in another it's a `List<SomeDomainType>`. I'd like to use `forcedTypes` to register a converter that will parse the JSON object. However, it doesn't seem possible to have a user type with a generic signature.

### Possible solution you'd like to see:

Use syntax such as 
```xml
<userType>java.util.Map\<java.lang.String, java.lang.Object\></userType>
```

### Possible workarounds:

Currently I just parse the column data at the use site. 

### Versions:

- jOOQ: 3.13.4
- Java: 11.0.9.1
- Database (include vendor): MySQL 5.7.32
- OS: macOS 11.0.1
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
The correct way to quote angle brackets in XML is:

```xml
<userType>java.util.Map&lt;java.lang.String, java.lang.Object&gt;</userType>
```

Or, alternatively, use CDATA:


```xml
<userType><![CDATA[java.util.Map<java.lang.String, java.lang.Object>]]></userType>
```
