### ISSUE TITLE
Nested records produced by DefaultRecordMapper do not pass through RecordListener lifecycle

### ISSUE THREAD

**Issue by vkuzel** [jOOQ/jOOQ#11118]
### Current behaviour

Configuration (if there is any) of a parent record should be attached to a nested record created in the `DefaultRecordMapper`

* Location of the problem No 1: https://github.com/jOOQ/jOOQ/blob/824e689f19b712802cbf5e44928696ce574795d5/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java#L825
* Location of the problem No 2: https://github.com/jOOQ/jOOQ/blob/824e689f19b712802cbf5e44928696ce574795d5/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java#L1010

### Actual behaviour

Configuration is not attached, so for example configured custom converter provider won't be used in mapping of nested records.

### Steps to reproduce the problem

Following test should convert `CustomType`, but it doesn't.
```java
public static class CustomType {
    public String msg;
}

public static class NestedEntity {
    public CustomType customMessage;
}

public static class Entity {
    private NestedEntity nestedEntity;
}

public static class CustomConverterProvider implements ConverterProvider {
    @Override
    public @Nullable <T, U> Converter<T, U> provide(Class<T> tType, Class<U> uType) {
        if (tType == String.class && uType == CustomType.class) {
            return Converter.of(
                    tType, uType,
                    t -> {
                        CustomType customType = new CustomType();
                        customType.msg = (String) t;
                        return (U) customType;
                    },
                    u -> (T) ((CustomType) u).msg
            );
        } else {
            return null;
        }
    }
}

@Test
public void nestedMappingTest() {
    Entity entity = dslContext
            .configuration().set(new CustomConverterProvider())
            .dsl()
            .select(DSL.val("Hello World!").as("nestedEntity.customMessage"))
            .fetchOneInto(Entity.class);

    Assertions.assertEquals("Hello World!", entity.nestedEntity.customMessage.msg);
}
```

### Versions

- jOOQ: > 3.14.0 introduced by #6598

**Thank you for looking into this issue.**

**Comment by lukaseder** [comment]
Thanks a lot for your thorough bug report. I can reproduce the problem. Agreed, the nested records should be attached, if `Settings.isAttachRecords() == true`.

I'll check your PR.

**Comment by lukaseder** [comment]
As mentioned on the PR:

> I think a more thorough solution wouldn't just take care of attaching the nested records, but to run through the entire `RecordListener` lifecycle, which in turn takes care of attaching the record, see `RecordDelegate::operate`.

I wonder if `DefaultRecordMapper::attach` is really necessary. It may have been added when `RecordToRecordMapper` did not yet produce attached records, but it should be doing so, now, given that its record-to-record mapping passes through `RecordDelegate`, which takes care of attaching among other things.

**Comment by lukaseder** [comment]
I've created a separate issue about that latter point, which can be fixed independently: https://github.com/jOOQ/jOOQ/issues/11121

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.5 (#11122). Thanks again for your report!

**Comment by vkuzel** [comment]
As you mentioned, `DefaultRecordMapper::attach` wasn't probably necessary. First of all, parent record from which configuration was copied, was already processed by the method so additional check for `Settings.isAttachRecords() == true` wasn't needed. Anyway your current solution which does not involve creating new "nested" record seems to be even better than creating a temporary record and passing it through lifecycle, not only performance wise. I am not that familiar with jOOQ's internals so I just went for a simplest solution.

Anyway, thank you for the quick fix. I just tested it in my application and it works flawlessly. Looking forward 3.15.0 in Spring Boot.

**Comment by lukaseder** [comment]
> Anyway your current solution which does not involve creating new "nested" record seems to be even better than creating a temporary record and passing it through lifecycle, not only performance wise.

Not sure what made you think so?. `RecordDelegate` does precisely that, it passes through this lifecycle. In fact, the fact that this wasn't being done before (but `RecordImplN::new` was called) was a bug. Performance wise, the current implementation might be a bit slower than the previous one. We currently *have to* go through the entire `RecordListener` lifecycle to map nested records.

We can fix this in the future by allowing to bypass the `RecordListener` lifecycle globally, but this must be done carefully, not just locally for these nested records:

- https://github.com/jOOQ/jOOQ/issues/6737
- https://github.com/jOOQ/jOOQ/issues/6544

> Looking forward 3.15.0 in Spring Boot.

No need to wait. I'll release 3.14.5 this week :)
