### ISSUE TITLE
Inline all bind values in the ON CONFLICT clause

### ISSUE THREAD

**Issue by tdelacour** [jOOQ/jOOQ#11149]
### Expected behavior
Successful execution of `UPSERT` query with `COALESCE` expression in the `ON CONFLICT` clause.

### Actual behavior
Non-deterministic failure, typically after several back-to-back queries.

Specifically:
`ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification`

### Steps to reproduce the problem

I did not build a self-contained repro program, but the query looks like:

```
dslContext
        .insertInto(
            MY_TABLE,
            MY_TABLE.A,
            MY_TABLE.B,
            MY_TABLE.C,
            MY_TABLE.D,
            MY_TABLE.E,
            MY_TABLE.F)
        .values(a, b, c, d, e, f)
        .onConflict(
            MY_TABLE.A,
            MY_TABLE.B,
            DSL.coalesce(MY_TABLE.C, ""),
            DSL.coalesce(MY_TABLE.D, ""),
            DSL.coalesce(MY_TABLE.E, ""))
        .doUpdate()
        .set(MY_TABLE.F, f)
        .execute();
```

The application runs this query in a tight loop some number of times (N > 10), with a variety of values for a, b, c, etc. Typically, after executing the loop 1-2 times, I start hitting the no-unique-constraint errors, somewhere mid-execution of the loop. If I put a long enough sleep between loop iterations, this error seems to stop (and, of course, if I pause via a debugger before execution, they also tend to go through).

I tried to repro this with a raw script executing on `psql` and could not. I believe something funny must be happening in JOOQ that is causing the executed query to not match my uniqueness constraint defined in postgres.

In addition, I seem to have found a workaround by replacing the `DSL.coalesce` function calls with `DSL.field("COALESCE(<MY_TABLE.C>, '')")`.

### Versions

- jOOQ: 3.12.4
- Java: 11
- Database (include vendor): Postgres 11.10
- OS: OSX 10.14.6 (Mojave)
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver 42.2.9

**Comment by lukaseder** [comment]
Thank you very much for your report.

I'm assuming you're trying to match an index of the form:

```sql
CREATE INDEX i ON my_table (a, b, coalesce(c, ''), coalesce(d, ''), coalesce(e, ''));
```

Is that it?

I suspect that we could inline all bind values inside of the `ON CONFLICT` clause, because bind variables don't really make sense there. For the time being, inline them explicitly using `coalesce(MY_TABLE.C, inline(""))`, etc.

**Comment by lukaseder** [comment]
I can reproduce it like this:

```sql
create table t_11149 (a text, b text);
create index i_11149 on t_11149 (a, coalesce(b, ''));
```

And then:

```java
@Test
public void testPostgresOnConflictWithBindValues() {
    clean(T_11149);

    assertEquals(1, create().insertInto(T_11149)
        .columns(T_11149.A, T_11149.B)
        .values("a", null)
        .onConflict(T_11149.A, coalesce(T_11149.B, ""))
        .doNothing()
        .execute());

    assertEquals(0, create().insertInto(T_11149)
        .columns(T_11149.A, T_11149.B)
        .values("a", null)
        .onConflict(T_11149.A, coalesce(T_11149.B, ""))
        .doNothing()
        .execute());
}
```

The error being:

```
org.jooq.exception.DataAccessException: SQL [insert into "public"."t_11149" ("a", "b") values (?, ?) on conflict ("a", coalesce("b", ?)) do nothing]; ERROR: there is no unique or exclusion constraint matching the ON CONFLICT specification
	at org.jooq_3.15.0-SNAPSHOT.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2846)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:388)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:119)
	at org.jooq.test.PostgresTest.testPostgresOnConflictWithBindValues(PostgresTest.java:3649)
```

**Comment by lukaseder** [comment]
My mistake, I didn't make this a `unique` index. When I do, the version using bind variables works again (on PostgreSQL 12).

Can you please share your table definition and full error message?

**Comment by lukaseder** [comment]
Can't reproduce this on PostgreSQL 11 either, using JDBC driver version 42.2.18

**Comment by lukaseder** [comment]
I cannot seem to reproduce this. Will close for now. Will be happy to look into this again with further reproduction instructions.

**Comment by tdelacour** [comment]
@lukaseder ah, sorry for not replying! Yes, feel free to close for now - I wasn't very hopeful about getting a standalone repro of this issue. I will let you know if I get a chance to try and write up a standalone program that is able to reproduce. Thanks for the help!

And to answer your question, yes the table contains a unique index on `(a, b, coalesce(c, ''), coalesce(d, ''), coalesce(e, ''))`
