### ISSUE TITLE
Regression calling Record1<JSON>.into(OtherTableRecord)

### ISSUE THREAD

**Issue by gofabian** [jOOQ/jOOQ#11148]
### Expected behavior

I expect a Record1<JSON> to be able to convert into another Record type. 

### Actual behavior

    Caused by: org.jooq.exception.DataTypeException: Cannot convert from {"key": "value"} (class org.jooq.JSON) to class example.OtherTableRecord. Check your classpath to see if Jackson or Gson is available to jOOQ.
	at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1289)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:1192)
	at org.jooq.tools.Convert.convert0(Convert.java:392)
	at org.jooq.tools.Convert.convert(Convert.java:384)
	at org.jooq.tools.Convert.convert(Convert.java:458)
	at org.jooq.impl.DefaultConverterProvider$1.from(DefaultConverterProvider.java:126)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:282)
	at org.jooq.impl.DefaultRecordMapper$ValueTypeMapper.map(DefaultRecordMapper.java:601)
	at org.jooq.impl.DefaultRecordMapper.map(DefaultRecordMapper.java:544)
	... 67 more

### Steps to reproduce the problem

`OtherTableRecord` is a table record and has a field like `JSON_FIELD`.

```java
        DSLContext dslContext = DSL.using(SQLDialect.POSTGRES);
        Field<JSON> JSON_FIELD = field(name("json"), SQLDataType.JSON);
        Object[] values = new Object[]{JSON.valueOf("{}")};

        Record record = dslContext.newRecord(JSON_FIELD);
        record.from(values);
        record.into(OtherTableRecord.class); // throws exception
```

The issue will only occur if the source record contains only one field (the json field). For example the issue does not occur here:

```java
        DSLContext dslContext = DSL.using(SQLDialect.POSTGRES);
        Field<Long> ID_FIELD = field(name("id"), SQLDataType.BIGINT.identity(true));
        Field<JSON> JSON_FIELD = field(name("json"), SQLDataType.JSON);
        Object[] values = new Object[]{42L, JSON.valueOf("{}")};

        Record record = dslContext.newRecord(ID_FIELD, JSON_FIELD);
        record.from(values);
        record.into(OtherTableRecord.class); // works
        System.out.println(record);
        // +----+----+
        // |  id|json|
        // +----+----+
        // | *42|*{} |
        // +----+----+
```
### Versions

- jOOQ: 3.14+, the issue did not occour before 3.14.0
- Java: 8
- Database (include vendor): Postgres dialect
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): X

**Comment by jazdw** [comment]
I don't know if this is related but I just got
`java.lang.ClassCastException: class org.jooq.JSON cannot be cast to class java.lang.String`
when trying to read a field defined as type String from an code generated table
`public final TableField<DataSourcesRecord, String> jsonData = createField(DSL.name("jsonData"), SQLDataType.CLOB, this, "");`
using
`String jsonData = record.get(table.jsonData);`

The code generated table was generated from a H2 database where the column has type `CLOB` but I was executing against MySQL where the column has type `JSON`.

**Comment by lukaseder** [comment]
Thanks a lot for your report and sorry for the delay. jOOQ 3.14 introduced a new `ConverterProvider` SPI which applies to record mappings of `Record1` types, see https://github.com/jOOQ/jOOQ/issues/10071. This created the observed regression. You could work around this regression by implementing a `ConverterProvider` that prevents this mapping, or of course, use a different mapping method, or produce a `Record2` type as you've stated.

I'll look into fixing this right away.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.12 (#11995). Thanks again for your report!

**Comment by lukaseder** [comment]
@jazdw: I don't think that's related. If your problem still persists, can you please create a new issue? https://github.com/jOOQ/jOOQ/issues/new/choose

**Comment by sheinbergon** [comment]
@lukaseder Maybe I'm missing something but, when Using 3.14.12 against PgSQL 12.x with a `ConvertorProvider` implementation, things work as expected and I can utilize custom conversion logic. However, when upgrade to 3.14.13 or 3.14.14, queries fail as the `ConvertorProvider` logic is never reached. Is this functionality usable beyond this fix?

10x

**Comment by lukaseder** [comment]
> @lukaseder Maybe I'm missing something but, when Using 3.14.11 against PgSQL 12.x with a `ConverterProvider` implementation, things work as expected and I can utilize custom conversion logic. However, when upgrade to 3.14.12 and beyond, queries fail as the `ConverterProvider` logic is never reached. Is this functionality usable beyond this fix?

Thanks, @sheinbergon. Can you please create a new issue with the usual details (ideally an MCVE from our template https://github.com/jOOQ/jOOQ-mcve).

**Comment by sheinbergon** [comment]
> > @lukaseder Maybe I'm missing something but, when Using 3.14.11 against PgSQL 12.x with a `ConverterProvider` implementation, things work as expected and I can utilize custom conversion logic. However, when upgrade to 3.14.12 and beyond, queries fail as the `ConverterProvider` logic is never reached. Is this functionality usable beyond this fix?
> 
> Thanks, @sheinbergon. Can you please create a new issue with the usual details (ideally an MCVE from our template https://github.com/jOOQ/jOOQ-mcve).

I've tracked the issue, it relates directly to this bugfix and #10071. WIll open a new issue
