### ISSUE TITLE
Liquibase yaml files

### ISSUE THREAD

**Issue by ceyhunn** [jOOQ/jOOQ#11152]
### Your question:

Can you support  code generation from Liquibase yaml files? I can't find anything in docs.

### Versions:

- jOOQ: 3.13.2
- Java: openjdk- 8
- Database (include vendor): postgres 12
- OS: Linux
- JDBC Driver (include name if inofficial driver): postgres 42.2.12

**Comment by lukaseder** [comment]
There's no reason why it shouldn't work. We're not doing anything XML specific. But it would be worth documenting this, of course: https://github.com/jOOQ/jOOQ/issues/11155

Have you tried whether it works for you?

**Comment by ceyhunn** [comment]
Hi @lukaseder , No I didn't test it. just I asked before I start. Thanks you so much for answer.
