### ISSUE TITLE
How to get default value of field?

### ISSUE THREAD

**Issue by Ari-Zerner** [jOOQ/jOOQ#11169]
### Your question:

Given a Meta, how can I determine the default value for a field? For example, if I have a Meta based on the schema `create table t(x integer default 42)`, I'd like to be able to get the value `42`.

### Versions:

- jOOQ: 3.14.4
- Java: 1.15

**Comment by lukaseder** [comment]
Thanks for your message.

If it's supported by the backing JDBC `DatabaseMetaData`, you can read it from e.g.

```java
Field<?> defaultValue = meta.getTables("t").get(0).field("x").getDataType().defaultValue();
```

Note that in jOOQ 3.14, the resulting value is just a plain SQL template, as if you wrote `DSL.field("42")`. Starting from jOOQ 3.15 and https://github.com/jOOQ/jOOQ/issues/8469, jOOQ will attempt to parse the expression to produce a more meaningful expression tree element, in this case the same as `DSL.inline(42)`.

You currently cannot reliably get the value 42 without to resorting to any of:

- Parsing strings yourself
- Accessing internal API via reflection

But this may be acceptable to you.
