### ISSUE TITLE
Can the org.jooq.Parser being extended for custom, SQL-like languages?

### ISSUE THREAD

**Issue by luca91** [jOOQ/jOOQ#11162]
We have an SQL-like language that we want to parse to extract some information from the query and execute some action. Is there a way to include the non-official SQL syntax to the parser process?

- jOOQ: 3.13.5
- Java: 11
- Database (include vendor): PostgreSQL
- OS: Ubuntu 20.04
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your message. We might investigate such functionality in the (not so near) future: https://github.com/jOOQ/jOOQ/issues/10243

Currently, there is no such feature. You can obviously fork jOOQ and maintain your own version of it. Chances are, you'll get quite far with this approach, with the usual drawback of a fork...

**Comment by luca91** [comment]
Ok, got it. Thanks for your explanation!
