### ISSUE TITLE
Generated classes as shared lib

### ISSUE THREAD

**Issue by ceyhunn** [jOOQ/jOOQ#11174]
### Use case:
I have one schema, two or more apps connects to this schema. In all these apps, I have to configure and then generate jooq  schema table classes. This makes duplicate codes, more db connections in the apps. 

### Possible solution you'd like to see:
Both maven and gradle support to build specific package to separated jar in app. It would be very useful to jooq codegen automatically generate, package and upload jar to user custom maven repo with specified url, credential, version properties after liquibase or flyway db changes. Then in other applications simply import and use generated classes from uploaded lib.

### Versions:

- jOOQ: 3.13.2
- Java: openjdk- 8
- Database (include vendor): postgres 12
- OS: Linux
- JDBC Driver (include name if inofficial driver): postgres 42.2.12

**Comment by lukaseder** [comment]
I'm curious, what exactly is missing from Maven and/or Gradle to do exactly that, out of the box, in a very robust way?

People are creating shared libraries from jOOQ generated classes all the time. All you have to do is make sure:

- The code is generated in the right moment of your build
- The code is generated to the right location for it to be packaged as a shared library

jOOQ is a SQL library, not a build tool. You make this sound very easy, yet this would be an endeavour where we'd re-invent so many wheels, and extremely complex ones at that. Imagine if every silly library out there that generates code (e.g. XJC, but also things like xtend) would implement their own version and vision of how to package and upload jars to dozens of different repository layout styles with dozens of different ways to authenticate, version things, etc. etc.
