### ISSUE TITLE
Feedback about manual section codegen-generate-fluent-setters

### ISSUE THREAD

**Issue by alfanse** [jOOQ/jOOQ#11173]
I need a code example of what a fluent setter looks like, esp with kotlin

**Comment by lukaseder** [comment]
The `KotlinGenerator` generates (data) classes with properties to be able to profit from kotlin property access syntax. Fluent setters aren't really idiomatic in this case.

Why would you want to do this?

**Comment by alfanse** [comment]
Sorry for the noob question, I'm an old java hack, getting used to kotlin. hence need for an example... here is a Player generated by jooq
```
data class Players(
      val id: String? = null
    , val name: String? = null
    , val email: String? = null
    , val created: String? = null
): Serializable {}
```
when my test instantiates it, the id and created field can be null, as the database creates them, but the only constructor doesn't let me ignore them, so test looks like: ```Players(null, "test", "email", null)```
its ok, but left me wondering how to create with only name and email?

**Comment by lukaseder** [comment]
The syntax for passing named arguments is the same as that for functions:
https://kotlinlang.org/docs/reference/functions.html#named-arguments

See also:
https://www.baeldung.com/kotlin/default-named-arguments
