### ISSUE TITLE
Wrong timestamp cast for generated Postgresql function call and hidding it in query output of LoggerListener (with bind values)

### ISSUE THREAD

**Issue by andbed** [jOOQ/jOOQ#11195]
### Expected behavior
```
    /**
     * Call this table-valued function
     */
    public GetDetails call(
          Timestamp startDateTime
        , Timestamp endDateTime
    ) {
        GetDetails result = new GetDetails(DSL.name("get_details"), null, new Field[] {
              DSL.val(startDateTime, SQLDataType.TIMESTAMP)
            , DSL.val(endDateTime, SQLDataType.TIMESTAMP)
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
```
### Actual behavior
```
    /**
     * Call this table-valued function
     */
    public GetDetails call(
          Timestamp startDateTime
        , Timestamp endDateTime
    ) {
        GetDetails result = new GetDetails(DSL.name("get_details"), null, new Field[] {
              DSL.val(startDateTime, SQLDataType.TIMESTAMP(0))
            , DSL.val(endDateTime, SQLDataType.TIMESTAMP(0))
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
```
### Steps to reproduce the problem
I just run `./gradlew generateReportingJooqSchemaSource` and I have as above wrong precision in Postgresql function call TIMESTAMP(0). 

Please note that: 
`cast('2019-12-16 23:59:59.999' as timestamp(0))` is `2019-12-17 00:00:00`
which is terribly wrong because `cast('2019-12-16 23:59:59.999' as timestamp)` is `2019-12-16 23:59:59.999000` and as a result all calculations on daily-basis are wrong. 

This issue has appeared once we upgraded from 3.13.5 to 3.14.4

What is more, the query logger hides the issue and outputs untrue info. It prints:
```
DEBUG org.jooq.tools.LoggerListener - -> with bind values      : select col1 
from "get_details"(timestamp '2019-12-16 00:00:00.0', timestamp '2019-12-17 23:59:59.999')
```
instead of:
```
DEBUG org.jooq.tools.LoggerListener - -> with bind values      : select col1 
from "get_details"(cast('2019-12-16 00:00:00.0' as timestamp(0)), cast('2019-12-17 23:59:59.999' as timestamp(0)))
```
which makes it much harder to debug (because printed query with bindings gives correct results when directly executed on DB, this logger lies about executed query, you cannot trust it). 

My function uses that passed timestamp params to perform some calculations, I believe details don't matter much. The function looks like:
```
create function get_details(start_date_time timestamp without time zone, end_date_time timestamp without time zone) returns TABLE(col1 integer)
        AS $$ SELECT 1 $$
    LANGUAGE SQL;
```

### Versions

- jOOQ:
3.14.4
- Java:
11.0.9.hs-adpt
- Database (include vendor)
Postgresql 11
- OS:
MacOS 11.1
- JDBC Driver (include name if inofficial driver):
postgresql-42.2.18

**Comment by lukaseder** [comment]
Thanks a lot for your report. I believe this is the same issue as https://github.com/jOOQ/jOOQ/issues/11191 ?
