### ISSUE TITLE
MetaTable::getReferences and MetaUniqueKey::getReferences do not take into account inverseSchemaCatalog

### ISSUE THREAD

**Issue by mmatz-ccri** [jOOQ/jOOQ#11201]
### Expected behavior
Only the references for the table, within the schema, should be returned.

### Actual behavior
All references for all tables with the same name, unrestricted by schema, are returned.

### Versions

- jOOQ: 3.10.6 (the current version appears to be affected as well, looking at the source)
- MySQL Connector/J: 8.0.15

### Notes

MetaTable.getReferences does not check the `inverseSchemaCatalog` flag.

**Comment by lukaseder** [comment]
Thanks a lot for your report. Indeed, this looks wrong.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.5 (#11204). Thanks again for your report!

**Comment by mmatz-ccri** [comment]
Thanks for the quick fix.
