### ISSUE TITLE
Shouldn't "Not Null Column with Default" get @NotNull annotation

### ISSUE THREAD

**Issue by eiswind** [jOOQ/jOOQ#11210]
### Your question:

Before asking your question, please check out the FAQ too: https://www.jooq.org/faq

### Versions:

- jOOQ:
3.14.4

- Java:
11
- Database (include vendor):
-Postgres 13

- OS:
-linux

When I create a table like
```
CREATE TABLE master_user
(
    email              TEXT               NOT NULL PRIMARY KEY,
    tenant_schema_name TEXT               NOT NULL REFERENCES tenant_definition (schema_name),
    version            BIGINT             NOT NULL DEFAULT 0,
    password           TEXT               NOT NULL,
    firstname          TEXT               NOT NULL DEFAULT '',
    lastname           TEXT               NOT NULL DEFAULT '',
    permissions        VARCHAR(100) ARRAY NOT NULL DEFAULT array []::varchar[]
);
```

The resulting data class is somehow missing some @NotNull annotations on the fields with default values:

```
data class MasterUser(
    @get:NotNull
    val email: String? = null, 
    @get:NotNull
    val tenantSchemaName: String? = null, 
    val version: Long? = null, 
    @get:NotNull
    val password: String? = null, 
    val firstname: String? = null, 
    val lastname: String? = null, 
    val permissions: Array<String?>? = null
): Serializable {
}
```

The generator settings are as follows
```
generate.apply {
                        isPojosToString = false
                        isImmutablePojos = true
                        isGeneratedAnnotation = true
                        isValidationAnnotations = true
                        isJavaTimeTypes = true
                        isRecords = true
                    }
```

is there a reason for this behaviour? I would expect the annotations to be present on all not null columns.

**Comment by lukaseder** [comment]
Thanks a lot for your message. See this issue for rationale of status quo and future improvements: https://github.com/jOOQ/jOOQ/issues/10212

**Comment by eiswind** [comment]
thanks @lukaseder 

I'm not sure if I get this right. It's not about member nullability. I just found that not null columns do get the @NotNull annotation, but as soon as  i set a default value for the not null column the annotation is not beeing generated anymore.

**Comment by lukaseder** [comment]
I'm sorry, my bad. I'll have another, closer look soon.

**Comment by lukaseder** [comment]
OK, after some research, this is the rationale: https://github.com/jOOQ/jOOQ/issues/5128

The validation annotations don't reflect what the RDBMS will do with the value. They reflect what *you* are allowed to do. If you're actually running the validation, when there's a default value, you're allowed to have it set to null, because the RDBMS will override that value.

I hope that makes sense?

**Comment by eiswind** [comment]
I see...
Thanks a lot for clearing that up!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Am Mittwoch, 13. Januar 2021 16:48 schrieb Lukas Eder <notifications@github.com>:
