### ISSUE TITLE
Add support for SET CONSTRAINTS ALL DEFERRED

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#11211]
### Use case:

This allows deferring deferrable constraints (foreign keys, but also others like exclude constraints)

### Possible solution you'd like to see:

Support for this statement in the DSL.

### Possible workarounds:

Execute it as plain SQL.

### Versions:

- jOOQ: 3.14.4
- Java: 14
- Database (include vendor): PG 13

----
See also:
- #8105
- #9508
- #9780
- #10363

**Comment by lukaseder** [comment]
Thank you for your suggestion. Also related: https://github.com/jOOQ/jOOQ/issues/10363

**Comment by lukaseder** [comment]
I guess there are hundreds of these `SET` or `ALTER SYSTEM`, `ALTER SESSION` commands that could be occasionally useful, but:

- They're all very specific to a single dialect
- We won't cover them all, so users will always run into a limitation

Better use plain SQL from the beginning on these. It's just `ctx.execute("SET CONSTRAINTS ALL DEFERRED")`.

I'm closing this as won't fix.

**Comment by lukaseder** [comment]
I'm looking into this again in the context of the implementation of https://github.com/jOOQ/jOOQ/issues/10363

The syntax isn't PostgreSQL specific, but specified as ISO/IEC 9075-2:2023(E)
17.4 &lt;set constraints mode statement>. It's available in multiple dialects.

I've created a new issue to implement this:

- https://github.com/jOOQ/jOOQ/issues/20047
