### ISSUE TITLE
Error mapping a jsonObject field: Cannot convert from LinkedHashMap

### ISSUE THREAD

**Issue by eriklumme** [jOOQ/jOOQ#11213]
When using an approach as suggested [on StackOverflow](https://stackoverflow.com/questions/33845239/jooq-single-query-with-one-to-many-relationship) under _Nesting collections using SQL/XML or SQL/JSON_, an error is thrown:

> Caused by: org.jooq.exception.DataTypeException: Cannot convert from {foo=bar} (class java.util.LinkedHashMap) to class com.foo.BarDTO

This appears to me to be the same issue as [this StackOverflow](https://stackoverflow.com/questions/65457523/jooq-fetchinto-cant-convert-java-util-linkedhashmap-to-class) question, although I'm not using Kotlin in my case.

Consider the test cases under _Steps to reproduce the problem_. The first one fails with the above error, while the second one succeeds, the difference being that in the second test case, everything is selected into a JSON object.

In the failing first test case, Jackson is invoked. However, it is only instructed to map `JSON` to a generic `List` for the `options` field in the example. The result is an `ArrayList` of `LinkedHashMap`, but when the `LinkedHashMap` instances are then mapped to `FieldOptionDTO` instances, the error occurs.

Perhaps it's a limitation of the framework, but some examples indicate that it should work.  

### Expected behavior

The JSON object is mapped to a list of `FieldOptionDTO` instances.

### Actual behavior

An exception is thrown

> Caused by: org.jooq.exception.DataTypeException: Cannot convert from {foo=bar} (class java.util.LinkedHashMap) to class com.fooBarDTO

### Steps to reproduce the problem

- Run the first test case below.

The `@Transactional` and `configuration` are due to the environment I run the tests in, but I do not believe they are relevant for the issue.

```
@Test
@Transactional
void testJsonArrayAgg1() {
  List<FieldDTO> dtos = DSL.using(configuration)
      .select(
          FIELD.ID,
          jsonArrayAgg(jsonObject(FIELD_OPTION.ID)).as("options")
      )
      .from(FIELD)
      .join(FIELD_OPTION).on(FIELD_OPTION.FIELD_ID.eq(FIELD.ID))
      .groupBy(FIELD.ID)
      .fetchInto(FieldDTO.class);
  System.out.println("Found " + dtos.size() + " DTOs");
}

@Test
@Transactional
void testJsonArrayAgg2() {
  List<FieldDTO> dtos = DSL.using(configuration)
      .select(jsonObject(
          jsonEntry("id", FIELD.ID),
          jsonEntry("options", jsonArrayAgg(jsonObject(FIELD_OPTION.ID)))
      ))
      .from(FIELD)
      .join(FIELD_OPTION).on(FIELD_OPTION.FIELD_ID.eq(FIELD.ID))
      .groupBy(FIELD.ID)
      .fetchInto(FieldDTO.class);
  System.out.println("Found " + dtos.size() + " DTOs");
}

public static class FieldDTO {
  public Long id;
  public List<FieldOptionDTO> options;
}

public static class FieldOptionDTO {
  public Long id;
}
```
  
### Versions

- jOOQ: 3.14.4
- Java: openjdk version "1.8.0_201-1-ojdkbuild"
- Database (include vendor): PostgreSQL 10.14, compiled by Visual C++ build 1800, 64-bit
- OS: Windows Server
- JDBC Driver (include name if inofficial driver): Postgres

**Comment by eriklumme** [comment]
It seems to me that the issue is that the generic type information is lost during conversion.

In this case, the `List<FieldOptionDTO>` type is passed to `Convert` as just a `List`, as the `Convert` class simply converts between classes. With only that to go by, Jackson converts it to a `ArrayList<LinkedHashMap>`.

I believe that if Jackson's `ObjectMapper#readValue(String, TypeReference<T>)` was used instead, and was passed the generic type of the list, it would work. I haven't tested it, though, and I assume it'd require a fair bit of changes in the code.

**Comment by shimikano** [comment]
I ran into the same problem.

Here's a modified example from [this blog post](https://blog.jooq.org/2020/10/09/nesting-collections-with-jooq-3-14s-sql-xml-or-sql-json-support/) (section "But that's not all!") that triggers the error:

```java
@Test
void issue11213() {
  for (Table t :
    db.select(
      COLUMNS.TABLE_SCHEMA,
      COLUMNS.TABLE_NAME,
      DSL.field(
        DSL.select(
          DSL.jsonArrayAgg(
            DSL.jsonObject(
              DSL.key("columnName").value(COLUMNS.COLUMN_NAME),
              DSL.key("type").value(DSL.jsonObject(
                "name", COLUMNS.DATA_TYPE)
              )
            )
          ).orderBy(COLUMNS.ORDINAL_POSITION)
        )
      ).as("columns")
    )
    .from(COLUMNS)
    .where(COLUMNS.TABLE_NAME.in("t_author", "t_book"))
    .groupBy(COLUMNS.TABLE_SCHEMA, COLUMNS.TABLE_NAME)
    .orderBy(COLUMNS.TABLE_SCHEMA, COLUMNS.TABLE_NAME)
    .fetchInto(Table.class)) {
  
    System.out.println(t.tableName + ":\n" + t.columns
      .stream()
      .map(c -> c.columnName + " (" + c.type.name + ")")
      .collect(Collectors.joining("\n  ")));
  }
}
```
This uses the Postgres Information Schema and the same pojos as given in the blog post.

The error is:

> org.jooq.exception.DataTypeException: Cannot convert from {columnName=id, type={name=uuid}} (class java.util.LinkedHashMap) to class xyz.JooqTest$Column

It seems that the underlying problem of missing generic type information is the same as in #11008 .

**Comment by matt-snider** [comment]
I ran into this too, thanks for opening this issue - it saved me from a lot of time debugging!

One (hacky) workaround, is to modify your class as follows:

```java
public static class FieldDTO { 
  private final ObjectMapper objectMapper = new ObjectMapper();

  public Long id;
  public List<FieldOptionDTO> options;

  public void setRawOptions(String rawOptions) {
      try {
          options = objectMapper.readValue(rawOptions, new TypeReference<List<FieldOptionDTO>>(){});
      } catch (JsonProcessingException e) {
          // Handle error
          options = new ArrayList<>();
      }
  }
}
```

Then, change the query slightly with `cast(String.class).as("rawOptions")`:

```java
  // ...
  jsonArrayAgg(jsonObject(FIELD_OPTION.ID)).cast(String.class).as("rawOptions")
  // ...
```

This seems to work, but if there's a better way to accomplish this, please let me know.

**Comment by eriklumme** [comment]
@matt-snider that looks sensible to me.

I did something similar, I created a converter `class JacksonConverter<T> implements Converter<JSONB, T>` that takes a class or `CollectionType` as a constructor parameter, and then converts the field to that type using an `ObjectMapper`.

Then in the query you have to do something like this, which I made an utility method for:

```
DataType<FooDTO> dataType = SQLDataType.JSONB.asConvertedDataType(new JacksonConverter<>(FooDTO.class));
Field<FooDTO> field = DSL.field("?", dataType, BAR.MY_JSONB_COLUMN);

// ...
    .select(BAR.ID, BAR.NAME, field)
// ...
```

**Comment by abrcdf1023** [comment]
Face the same issue.
I try the stackoverflow answer([here](https://stackoverflow.com/questions/63207665/jooq-nested-object-with-many-to-many-relationship)) to mapping many to many relations but be stuck.

Error message:
`org.jooq.exception.DataTypeException: Cannot convert from {interventionId=3cff10f5da974e82ad7e8310e09ef554} (class java.util.LinkedHashMap) to class com.moneytrainer.webapp.rds.entity.Intervention`

**Comment by lukaseder** [comment]
Thanks for all your feedback folks. Indeed, there's a subtle difference between

- Aggregating all data into a single JSON value and then mapping *everything* with Jackson/Gson, nothing with jOOQ's internal conversion utilities (shouldn't cause any trouble)
- Producing an "ordinary" resultset that happens to have some JSON values in some but not necessarily all columns, and thus using jOOQ's internal conversion utilities on the "first mapping level", and Jackson/Gson only for the JSON values

jOOQ's internal conversion utilities aren't capable of reflecting on generic types as we only have `Class` instance references, not `Type` references from e.g. `Member::getGenericType`, so this won't be easy to fix in jOOQ, outside of this JSON/Jackson usage.

However, that `LinkedHashmap` is something that's being produced by Jackson when we pass the `List.class` (erased generics) to it. Jackson will produce a generic `ArrayList<LinkedHashMap>`, and can't map that again to the `List<SomeType>` generic type anymore. It should be possible to prevent doing two Jackson round trips.

I'll investigate this now.

**Comment by lukaseder** [comment]
Well, we could write back the data structures to JSON using `new ObjectMapper().writeValueAsString(...)`, and then re-read them agian using the generic list element type that `DefaultRecordMapper` has figured out. At least, that would fix the issue for now, which many people are running into.

It's a waste of resources, sure, but at least it works, until something better can be implemented.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.10 (https://github.com/jOOQ/jOOQ/issues/11887). Thanks again for all your feedback, folks.

**Comment by lukaseder** [comment]
Note that starting from jOOQ 3.15, there will be a better way to map collections than using the SQL/JSON approach, at least in dialects that support this natively (at least PostgreSQL, maybe Oracle), and it doesn't use reflection:

```java
void testJsonArrayAgg1() {
  List<FieldDTO> dtos = DSL.using(configuration)
      .select(
          FIELD.ID,
          array(
              select(row(FIELD_OPTION.ID).mapping(FieldOptionDTO::new))
              .from(FIELD_OPTION)
              .where(FIELD_OPTION.FIELD_ID.eq(FIELD.ID))
          ).convertFrom(Arrays::asList)
          jsonArrayAgg(jsonObject(FIELD_OPTION.ID)).as("options")
      )
      .from(FIELD)
      .fetch(Records.mapping(FieldDTO::new));
}

// Using Java 16 records for simplicity, but ordinary classes work, too
public static record FieldDTO(Long id, List<FieldOptionDTO>) {}
public static record FieldOptionDTO (Long id) {}
```

The API isn't fixed yet (e.g. `mapping()` and `convertFrom()` methods), but the ideas are there, see related issues:

- https://github.com/jOOQ/jOOQ/issues/6080
- https://github.com/jOOQ/jOOQ/issues/7100
- https://github.com/jOOQ/jOOQ/issues/11804
- https://github.com/jOOQ/jOOQ/issues/11810
- https://github.com/jOOQ/jOOQ/issues/11812

**Comment by morki** [comment]
Hi, maybe it is only too late or I miss something, but I think this line does not belong to the snipped above:

```java
jsonArrayAgg(jsonObject(FIELD_OPTION.ID)).as("options")
```

**Comment by lukaseder** [comment]
Yes, thanks @morki

**Comment by wussup** [comment]
If you have older version of JOOQ, then you can use _FieldOptionDTO[]_ instead of _List<FieldOptionDTO>_
