### ISSUE TITLE
Tables should be represented as object's in Kotlin, rather than a class and single instance

### ISSUE THREAD

**Issue by bsimon36** [jOOQ/jOOQ#11230]
### Use case:

Kotlin has first-class support for singletons via `object`, but the generated Kotlin code still makes each table a class, e.g. `open class FakeTable`, with a single instance `FAKE_TABLE`.

Making the table an `object` is the idiomatic Kotlin treatment and it also allows for importing individual columns, e.g. `import com.fake.FakeTable.FAKE_COLUMN` or even `import com.fake.FakeTable.*`. This is not possible when FakeTable is a `class` instead of an `object`.

### Possible solution you'd like to see:

We actually hand-edited the scala code from 3.9 to generate Kotlin instead and have been using that in production for years. Our edit uses this design so we know that it works. Here's a sample file from our current project:

```
/*
 * This file is generated by jOOQ.
*/
package com.downdogapp.jooq.tables


import com.downdogapp.jooq.Keys.PROPERTIES_PKEY
import com.downdogapp.jooq.Public
import com.downdogapp.jooq.tables.records.PropertiesRecord

import org.jooq.Schema
import org.jooq.TableField
import org.jooq.UniqueKey
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
object Properties: TableImpl<PropertiesRecord>("properties", Public, null, null, "") {

  /**
   * The class holding records for this type
   */
  override fun getRecordType() : Class<PropertiesRecord> {
    return PropertiesRecord::class.java
  }

  /**
   * The column <code>public.properties.key</code>.
   */
  val KEY : TableField<PropertiesRecord, String> = createField("key", org.jooq.impl.SQLDataType.VARCHAR.nullable(false), "")

  /**
   * The column <code>public.properties.value</code>.
   */
  val VALUE : TableField<PropertiesRecord, String> = createField("value", org.jooq.impl.SQLDataType.VARCHAR, "")


  override fun getSchema() : Schema = Public

  override fun getPrimaryKey() : UniqueKey<PropertiesRecord> {
    return PROPERTIES_PKEY
  }

  override fun getKeys() : MutableList<UniqueKey<PropertiesRecord>> {
    return mutableListOf<UniqueKey<PropertiesRecord>>(PROPERTIES_PKEY)
  }
}
```

### Possible workarounds:

The only actual functionality lost with the current behavior is the ability to import columns. Instead, one has to import the table and then call `TABLE.COLUMN` or use `with(TABLE)` or `TABLE.apply`.

### Versions:

- jOOQ: 3.14.4
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by bsimon36** [comment]
Sorry, Kotlin does not support global import for `object` `val`'s, so `import com.fake.FakeTable.*` still won't work, but `import com.fake.FakeTable.FAKE_COLUMN` does.

**Comment by lukaseder** [comment]
Thanks for your suggestion. jOOQ 1.x used to do that for Java as well. You can still enable the old behaviour by specifying `<instanceFields>false</instanceFields>`. The flag has been deprecated in jOOQ 3.3 and will be removed in jOOQ 4.0. Hence, the decision was made not to support it in `KotlinGenerator` (or `ScalaGenerator` for that matter).

There are a few reasons why it's a bad idea to use singleton tables and/or static column members:

- Aliasing is *much* more elegant the way it is right now. Try it. `FAKE_TABLE.`as`("t").FAKE_COLUMN` is possible today and wouldn't be possible with your suggestion
- Users can subtype generated classes for whatever reason
- Using unqualified columns is generally not seen as good style in SQL, so jOOQ follows suit. As soon as you join tables, the ambiguities make static importing columns prohibitive.

Having said so, you can easily generate package objects for your columns if you're sure you won't have ambiguities. That way, you can import-on-demand everything from the package and get all the columns without qualification.
