### ISSUE TITLE
Behavior of MockResultSet.close() differs from ResultSet.close() javadoc

### ISSUE THREAD

**Issue by jeffhowie** [jOOQ/jOOQ#11273]
### Expected behavior
Calling close() on an already closed MockResultSet instance is a no-op, like this quote from Java's ResultSet.close() javadoc indicates:
"Calling the method close on a ResultSet object that is already closed is a no-op."

### Actual behavior
A new SQLException("ResultSet is already closed") is thrown when closing an already closed MockResultSet, from its call to MockResultSet.checkNotClosed().

### Steps to reproduce the problem
Call close on the mock twice. 
This was seen in our unit tests because the result set is first closed automatically by jOOQ when it isn't able to read anymore rows, and then a second time by our production code that wraps its use of a ResultSet in a try-with-resources block to automatically close it. That second close is what triggers the exception.

### Versions

- jOOQ: 3.13.1
- Java: 11
- Database (include vendor): Postgres 12.1
- OS: Mac
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for the report.

I don't think there's a reasons for the status quo, other than every method doing the same thing. And the Javadoc is clear indeed. So, I don't think we'll break anything if we change this.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.6 (#11274)
