### ISSUE TITLE
Feedback about manual section codegen-maven

### ISSUE THREAD

**Issue by belu** [jOOQ/jOOQ#11297]
It seems the `<configuration>` section should be below the `<executions>` and not inside.

This is also documented here: https://www.jooq.org/doc/latest/manual/code-generation/codegen-configuration/

**Comment by lukaseder** [comment]
Thanks for your message.

Maven allows for configuring a plugin for all executions, or on a per-execution basis:

```xml
<plugin>
  <groupId>org.jooq</groupId>
  <artifactId>jooq-codegen-maven</artifactId>

  <!-- Configuration common to all executions -->
  <configuration>...</configuration>
  <executions>
    <execution>
      <id>...</id>
      <phase>...</phase>
      <goals>...</goals>

      <!-- Per execution configuration -->
      <configuration>...</configuration>
    </execution>
  </executions>
</plugin>
```

See also: https://maven.apache.org/guides/mini/guide-configuring-plugins.html

If you have multiple `<configuration>` tags (including those originating from `<pluginManagement/>` tags), you can merge them according to some rules:
https://blog.sonatype.com/2011/01/maven-how-to-merging-plugin-configuration-in-complex-projects/

I hope this helps

**Comment by belu** [comment]
@lukaseder 

Yes, according to the Maven guide this should work. However, in the example project below if the `<configuration>` section is moved to the end of the `<execution>` section, the code-generator fails with the following error:

```
[ERROR] Incorrect configuration of jOOQ code generation tool
[ERROR] 
The jOOQ-codegen-maven module's generator configuration is not set up correctly.
This can have a variety of reasons, among which:
- Your pom.xml's <configuration> contains invalid XML according to jooq-codegen-3.14.0.xsd
- There is a version or artifact mismatch between your pom.xml and your commandline
```

Example POM: https://github.com/belu/quarkus-kotlin-jooq-demo/blob/main/pom.xml

**Comment by lukaseder** [comment]
I don't think the order matters. Check your own `kotlin-maven-plugin`, where you placed `<configuration>` after `<executions>`.

The error appears when the `<generator>` tag couldn't be loaded. Is there anything else in your log output that you could show? Your sample project works for me out of the box (once I remove the `<skip.jooq.generation>true</skip.jooq.generation>` config, of course)

**Comment by belu** [comment]
@lukaseder 

Yes, the sample project works. You would have to move the `<configuration>` section manually to make it fail.

Please check the following branch where the `<configuration>` is inside the `<execution>`. Furthermore code generation is activated. This fails for me out-of-the-box with the error message above.

Maven version: 3.6.3

**Comment by lukaseder** [comment]
I'm assuming you mean this branch: https://github.com/belu/quarkus-kotlin-jooq-demo/blob/pom-configuration-inside-execution/pom.xml

This works for me.

**Comment by belu** [comment]
@lukaseder 

Yes, this branch. Sorry, forgot to paste the URL above.

Strange that it works for you. When I clone the repo and checkout the branch, then a `mvn jooq-codegen:generate` leads to the error. As I don't know where the error comes from maybe it is specific to my environment/platform.

Thanks for your support!

**Comment by lukaseder** [comment]
Ah, I see. I just called `mvn generate-sources`, i.e. ran the entire build not just the plugin. This is how maven works, unfortunately. I don't fully recall the rationale behind these things, but maybe, this resource helps? https://stackoverflow.com/q/3779369/521799
