### ISSUE TITLE
ORACLE CONVERT function into where clause

### ISSUE THREAD

**Issue by lefebvrecharlie** [jOOQ/jOOQ#11308]
Hi,

How can I write this into my oracle jooq condition please :

```sql
convert(upper(_MY_TABLE.FIELD_), 'US7ASCII'))
```

Thanks in advance

### Versions:

- jOOQ: 3.10.5
- Java: Open JDK 11
- JDBC Driver (include name if inofficial driver): oracle.jdbc.driver.OracleDriver

**Comment by lukaseder** [comment]
Thank you very much for your message.

We currently don't support Oracle's `CONVERT()` function out of the box, but you can easily use it via our plain SQL templating feature:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

Just write a utility like this:

```java
public static Field<String> convert(Field<String> field, String charset) {
    return DSL.field("convert({0}, {1})", field.getDataType(), field, DSL.inline(charset));
}
```

And now, call it like this:

```java
convert(upper(_MY_TABLE.FIELD_), "US7ASCII");
```
