### ISSUE TITLE
Wrong documentation of RenderQuotedNames.EXPLICIT_DEFAULT_UNQUOTED

### ISSUE THREAD

**Issue by bwajtr** [jOOQ/jOOQ#11317]
The EXPLICIT_DEFAULT_UNQUOTED description in RenderQuotedNames part is either incorrect or something is eluding me there. The original text is:

> ALWAYS: This will quote all identifiers.
> EXPLICIT_DEFAULT_QUOTED: This will quote all identifiers, which are not explicitly unquoted using DSL.unquotedName().
> EXPLICIT_DEFAULT_UNQUOTED: This will quote all identifiers, which are not explicitly quoted using DSL.quotedName().
> NEVER: This will not quote any identifiers.

I think that EXPLICIT_DEFAULT_UNQUOTED should say:

EXPLICIT_DEFAULT_UNQUOTED:  This will not quote any identifier unless explicitly quoted using DSL.quotedName()

At least the behaviour in jOOQ 3.14.4 seems to be like that...

**Comment by lukaseder** [comment]
Yes, you're right. Thanks a lot for your report.
