### ISSUE TITLE
PostgreSQL routines with long names are excluded by code generator

### ISSUE THREAD

**Issue by yarihate** [jOOQ/jOOQ#11325]
### Expected behavior
Routines with long names (>60 chars) successfully generated 

### Actual behavior
Code generator doesn`t generate routines with long names 

### Steps to reproduce the problem
Code generation configuration
```
jooq {
    version = '3.11.10'
    edition = 'OSS'
    sample(sourceSets.main) {
        jdbc {
            driver   = 'org.postgresql.Driver'
            url      = url
            user     = user     
            password = password
        }
        generator {
            name = 'org.jooq.codegen.DefaultGenerator'
            strategy {
                name = 'org.jooq.codegen.DefaultGeneratorStrategy'
            }
            database {
                name = 'org.jooq.meta.postgres.PostgresDatabase'
                inputSchema = 'my_schema'
            }
            generate {
                daos = true
                sequences = true
                relations = true
                deprecated = false
                records = true
                immutablePojos = false
                fluentSetters = true
            }
            target {
                packageName = 'com.my.package'
            }
        }
    }
}
```

Results of executing meta query missing routines with names longer than 60 chars:
https://github.com/jOOQ/jOOQ/blob/222d2b49616741b00b5e1bef444cf05413596ede/jOOQ-meta/src/main/java/org/jooq/meta/postgres/PostgresDatabase.java#L884-L930

E.g. "calc_excluded_for_interchangeability_ref_price_combo_details" (61 char) in "information_schema"."routines"."specific_name" has value "calc_excluded_for_interchangeability_ref_price_combo_deta_16558"

### Versions

- jOOQ: 3.11.10
- Java: 8
- Database (include vendor): PostgreSQL
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.5

**Comment by lukaseder** [comment]
Thanks for your report.

Interesting, I wasn't aware of PostgreSQL's hacks in this area. Creating this function:

```sql
CREATE OR REPLACE FUNCTION f11325_000123456789012345678901234567890123456789012345678901234567890()
RETURNS INT AS
$$
  SELECT 1
$$ LANGUAGE SQL;
```

It can now be called like this. I.e. the last letters don't actually matter:

```sql
select f11325_00012345678901234567890123456789012345678901234567890123xxxxxxxxxxxxxx();
```

When you try to restore its sources:

```sql
select pg_get_functiondef(oid)
from pg_catalog.pg_proc 
where proname like 'f11325%'
```

You'll be getting (notice the truncated function name):

```sql
CREATE OR REPLACE FUNCTION public.f11325_00012345678901234567890123456789012345678901234567890123()
 RETURNS integer
 LANGUAGE sql
AS $function$

  SELECT 1

$function$
```

Both the `information_schema.routines` and `pg_catalog.pg_proc` tables report the shortened value, and our query doesn't take this into account. Should be an easy fix (although, we can't restore the name)

**Comment by lukaseder** [comment]
A quick look at https://github.com/postgres/postgres/blob/master/src/backend/catalog/information_schema.sql reveals that we should use `nameconcatoid(pg_catalog.pg_proc.proname, pg_catalog.pg_proc.oid)` to calculate the `specific_name` for that join between `information_schema.routines` and `pg_proc`.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.7 (#11339). Thanks again for your report!

**Comment by lukaseder** [comment]
The function has been added only in PostgreSQL 12. Earlier versions must use the previous implementation, which was the same as ours:

```sql
CREATE VIEW routines AS
    SELECT CAST(current_database() AS sql_identifier) AS specific_catalog,
           CAST(n.nspname AS sql_identifier) AS specific_schema,
           CAST(p.proname || '_' || CAST(p.oid AS text) AS sql_identifier) AS specific_name,
```

**Comment by lukaseder** [comment]
See also: https://github.com/postgres/postgres/blob/REL_11_STABLE/src/backend/catalog/information_schema.sql
