### ISSUE TITLE
JSON.json: object to string to JSON?

### ISSUE THREAD

**Issue by 2x2xplz** [jOOQ/jOOQ#11324]
### Your question:

Am I saving JSON data correctly?

### Versions:

- jOOQ: 3.14
- Java: 11 (Kotlin 1.4)
- Database (include vendor): H2, Postgres
- OS: Windows, Debian
- JDBC Driver (include name if inofficial driver): Hikari CP
- JSON Library: Kotlinx.serialization

Thanks for including native JSON data type for H2 DB in the latest JOOQ! So now I am trying to save objects in the db and as far as I can tell, I need to perform this somewhat inefficient (and strange-looking, due to 3x `json`) code:

```
myjooq.insertInto(mydb.MYTABLE).columns(MYCOL).values(
  JSON.json(Json.encodeToString(mydataclass.serializer(), mydataclass))
)
```

To break it down, I'm turning my object or data class into a string (via kotlinx.serialization's `encodeToString` function) then back into Json via jooq's `JSON.json()` function.

Just wondering if this is the correct approach or if I can go directly object->DB or somehow skip the string writing/reading in the object->string->JSON chain. But I don't see any other way to create a JSON except from a string: https://www.jooq.org/javadoc/3.14.x/org.jooq/org/jooq/JSON.html

I recognize that kotlinx.serialization is only recently out of beta... would it be different if I was using Jackson or Moshi? Thank you.

**Comment by lukaseder** [comment]
Thanks for your message.

We currently serialise all JSON data in string form, but to be able to add type safety to these strings, they have to be wrapped as `org.jooq.JSON`.

I don't think there's anything inefficient about this. You can certainly achieve better readability by writing your own utilities. For example, why not add an extension function to `org.jooq.JSON` that does all you need?

```kotlin
fun JSON.json(t: T) = JSON.json(Json.encodeToString(t.serializer(), t))
```

Whatever that `T` type needs to be to get access to that `serializer()` method...

I hope this helps.
