### ISSUE TITLE
intoXML() throws NPE exception

### ISSUE THREAD

**Issue by AnghelLeonard** [jOOQ/jOOQ#11341]
### Expected behavior
A `Document` instance.

### Actual behavior
Outputs:

```Java
java.lang.NullPointerException: null
	at org.jooq.impl.AbstractCursor.intoXML(AbstractCursor.java:1170) ~[jooq-3.14.6.jar:na]
	at org.jooq.impl.AbstractFormattable.intoXML(AbstractFormattable.java:345) ~[jooq-3.14.6.jar:na]
        ...
```

### Steps to reproduce the problem
I tried this code:

```Java
Document result = ctx.select(xmlelement("customerName", CUSTOMER.CUSTOMER_NAME))
                .from(CUSTOMER)
                .fetch()
                .intoXML();
```

And, this:

```Java
Document result = ctx.selectFrom(OFFICE).fetch().intoXML();
```

### Versions

- jOOQ:3.14.6
- Java:14
- Database (include vendor):PostgreSQL
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): postgresql-42.2.18

**Comment by lukaseder** [comment]
Thanks a lot for your report. Interesting combination of features :) While I don't think a lot of folks want wrap SQL generated XML documents in the `Result.formatXML()` format (which adds useless wrapping around what is already XML), it definitely shouldn't throw a NPE.

**Comment by AnghelLeonard** [comment]
Just courious. The road to `intoXML()` passes through `Result.formatXML()` ?

**Comment by lukaseder** [comment]
Well, it has nothing to do with your content being XML. It happens with any type of content when calling `intoXML()` without an `XMLFormat` 😐.

**Comment by lukaseder** [comment]
> Just courious. The road to `intoXML()` passes through `Result.formatXML()` ?

No, they're separate implementations for performance reasons. Rather than formatting the result into a potentially large string only to parse it again, `intoXML()` directly generates a new DOM document.

**Comment by lukaseder** [comment]
I've just found an issue where the two are different: https://github.com/jOOQ/jOOQ/issues/11634

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.9 (#11636). Thanks again for your report!

**Comment by lukaseder** [comment]
Agh, I think I even found yet another bug in jOOQ (`Result.formatXML()` produces nested redundant `xmlns` declarations) and in jOOX (Parsing and re-generating the XML string for `<result><fields><field name="xmlelement" type="XML"/></fields><records><record><value field="xmlelement"><x>test</x></value></record></records></result>` produces wrong output).

Time to call it a weekend 😅

**Comment by lukaseder** [comment]
The `formatXML()`'s nested `xmlns` declaration has been fixed as https://github.com/jOOQ/jOOQ/issues/12026
