### ISSUE TITLE
Code Generation  is not consistent

### ISSUE THREAD

**Issue by cemo** [jOOQ/jOOQ#11411]
### Expected behavior

JPA PK Annotations  must be created consistent

### Actual behavior

JPA Annotations such as ` @Id` is generated not always. It is included in some runs but not in all runs. When I debug, I see that PK columns are not always filled. 

### Steps to reproduce the problem

https://github.com/cemo/jooq-11411

### Versions

- jOOQ: 3.14.7
- Java: 15
- Database (include vendor: MySQL
- OS: MacOS
- JDBC Driver (include name if inofficial driver):

**Comment by cemo** [comment]
I added a sample project to demonstrate problem. If you can run `mvn clean generate-sources` it creates Product entity without JPA ID annotation.

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll look into your demo project right away.

**Comment by lukaseder** [comment]
Interesting. I can reproduce this as soon as I toggle the `<tables>` flag.

**Comment by lukaseder** [comment]
Egh, it's right there, you turned it off: `<relations>false</relations>`. That flag is auto-turned on when it is needed (e.g. when generating tables or daos)

**Comment by lukaseder** [comment]
We can probably improve the `INFO` log output and explain why some flags are forced to a different value than the configured one: https://github.com/jOOQ/jOOQ/issues/11413

**Comment by cemo** [comment]
Sorry @lukaseder :/ The problem was that when debugging it was generating these ID's. That is why I thought it is a bug. Sorry again.

**Comment by lukaseder** [comment]
Hey, no worries! Could've been a bug, and it helped uncover a UX flaw!
