### ISSUE TITLE
BCE dates are off by one year

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#11438]
### Expected behavior
Ability to query BCE dates

### Actual behavior
JOOQ converts BCE dates off by one year

### Steps to reproduce the problem

Database schema:
```
CREATE SEQUENCE foo_sequence;
CREATE TABLE foo_state
(
    id        BIGINT DEFAULT NEXTVAL('foo_sequence') PRIMARY KEY,
    time      TIMESTAMP WITH TIME ZONE NOT NULL,
);
ALTER SEQUENCE foo_sequence OWNED BY fooid;
```

Code snippet:
```
OffsetDateTime MINIMUM_TIME = OffsetDateTime.of(LocalDate.of(-4713, Month.JANUARY, 1), LocalTime.of(0, 0, 0), ZoneOffset.UTC);

Foo foo = Foo.FOO;
var row = transaction.select(foo.ID, foo.TIME).
	from(foo).
	where(foo.TIME.greaterThan(MINIMUM_TIME)).fetchOne();
```

Results in the following JDBC query: `select "public"."foo"."id", "public"."foo"."time", from "public"."foo" where ("public"."foo"."time" > cast(? as timestamp(6) with time zone))`

and PostgreSQL fails with: `ERROR: timestamp out of range: "4714-01-01 00:00:00.000000000Z BC"`

### Versions

- jOOQ: 3.14.7
- Java: 15.0.1
- Database (include vendor): PostgreSQL 13.0.1
- OS: Windows Version 10.0.19042.804
- JDBC Driver (include name if inofficial driver): 
```
<groupId>org.postgresql</groupId>
<artifactId>postgresql</artifactId>
<version>42.2.18</version>
```

**Comment by cowwoc** [comment]
The fix is to replace `yyyy` by `YYYY` at https://github.com/jOOQ/jOOQ/blob/b526e86bb117ae3c7b29404b4079fd1f0f2134cd/jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java#L2996

**Comment by cowwoc** [comment]
This is caused by user error. I incorrectly assumed that `LocalDate.of(-4713, Month.JANUARY, 1)` denoted 4713 BCE but year 0 actually denotes 1 BCE so I was off by one.

**Comment by lukaseder** [comment]
> but year 0 actually denotes 1 BCE so I was off by one.

Oh boy, I'm always glad when I don't have to touch these things :)
