### ISSUE TITLE
jooq 3.4.17 and android sdk 22

### ISSUE THREAD

**Issue by StormGoth** [jOOQ/jOOQ#11439]
### Your question:

Hello, I love jOOQ, since it allowes us to use much of our server stuff in the offline-first androit client, but I have a problem: I have to support devices with android 5.1 (these are 1k+€ barcode scanners). When I set the minSdkVersion to 22 I get the following error:

```
com.android.tools.r8.internal.D7: One or more instruction is preventing default interface method from being desugared: 
void org.jooq.ResultQuery.forEach(java.util.function.Consumer)
```

The usual suspects are set:

```
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
```

Is there any way to get it to work? If not: what was the last version of jOOQ to support JDK 1.6?

### Versions:

- jOOQ: 3.4.17
- Java: Android 5.1, so mostly JRE 1.6
- Database (include vendor): SQLite
- OS: Android 5.1
- JDBC Driver (include name if inofficial driver): SQLDroid

**Comment by lukaseder** [comment]
Thanks for your message, @StormGoth. You can find all of our jOOQ versions and the various editions / distributions listed on this page here:
https://www.jooq.org/download/versions

- jOOQ 3.0 - 3.6 had Java 6-7 support in the Open Source, Express, Professional, and Enterprise Editions
- jOOQ 3.7 - 3.11 had Java 6-7 support in the Express, Professional, and Enterprise Editions
- jOOQ 3.12 - 3.14 had Java 6-7 support only in the Enterprise Edition
- jOOQ 3.15 will drop Java 6-7 support for all editions

We'll be happy to continue supporting Java 6 for you in the jOOQ 3.14 Enterprise Edition for a few more patch releases, which include bug fixes and minor, non API changing features.

I hope this helps. Please let me know if you have any additional questions, and I'll be very happy to assist you.
