### ISSUE TITLE
Using Common table expressions in Incremental query building (a.k.a. the model API)

### ISSUE THREAD

**Issue by darshan-sj** [jOOQ/jOOQ#11469]
### Your question:

Is there any way we can use With clause (Common table expressions) along with the incremental query building (a.k.a. the model API) ?

I'm not able to find anything in the documentation regarding this. 

I went through the JOOQ open source code and I see that there is a constructor in `SelectQueryImpl` class which takes in `WithImpl` if this constructor is exposed through the DSLContext.selectQuery interface it will be very helpful. Please let me know if this approach is okay, I can raise a PR for this.

Before asking your question, please check out the FAQ too: https://www.jooq.org/faq

### Versions:

- jOOQ: 3.13.4
- Java: 11
- Database (include vendor): Postgres
- OS: Mac OS
- JDBC Driver (include name if inofficial driver):

**Comment by darshan-sj** [comment]
@lukaseder please help for solving this problem.

**Comment by lukaseder** [comment]
No it's not possible, see this Q&A here for an explanation why we won't add this feature: https://stackoverflow.com/q/65909646/521799

**Comment by darshan-sj** [comment]
Understood. Thank you so much for your prompt response.
