### ISSUE TITLE
LoaderOptionsStep.commitAfter() is not implemented correctly

### ISSUE THREAD

**Issue by AnghelLeonard** [jOOQ/jOOQ#11462]
### Expected behavior
Example 3 from below to commit after 2 batches.
Example 5 from below to commit after 3 batches.

### Actual behavior
Examples 3 and 5 commit unexpected after 1 batch.

### Steps to reproduce the problem

Example 1:
```Java
// commit correctly after 6 rows (after 1 batch)
ctx.loadInto(SALE).bulkAfter(2).batchAfter(3).commitEach() .loadCSV(...)
```

Example 2:
```Java
// commit correctly after 6 rows (after 1 batch)
ctx.loadInto(SALE).bulkAfter(2).batchAfter(3).commitAfter(1) .loadCSV(...)
```
**Example 3:**
```Java
// commit unexpected after 6 rows (after 1 batch)
ctx.loadInto(SALE).bulkAfter(2).batchAfter(3).commitAfter(2) .loadCSV(...)
```
Example 4:
```Java
// commit correctly after 18 rows (after 3 batches)
ctx.loadInto(SALE).bulkAfter(2).batchAfter(3).commitAfter(3) .loadCSV(...)
```
**Example 5:**
```Java
// commit unepected after 12 rows (after 1 batch)
ctx.loadInto(SALE).bulkAfter(3).batchAfter(4).commitAfter(3) .loadCSV(...)
```
Roughly, looks like a bug that happens when the number of "after bulk" is equal to the number of "after commit". 

### Versions

- jOOQ:3.14.7
- Java:14
- Database (include vendor):MySQL
- OS:Windows 10
- JDBC Driver (include name if inofficial driver):-

**Comment by lukaseder** [comment]
Huh, very curious bug, thanks for the detailed report!
