### ISSUE TITLE
Document immutability of CSVFormat and related types

### ISSUE THREAD

**Issue by AnghelLeonard** [jOOQ/jOOQ#11472]
### Expected behavior
Fluent and non-fluent `CSVFormat` to act the same.

### Actual behavior
Fluent works, non-fluent doesn't work.

### Steps to reproduce the problem

Having a jOOQ `Result` then:

```Java
// this format work as expected
CSVFormat csvFormat = new CSVFormat()
                .delimiter("|")
                .nullString("{null}");
```

While this one seems to have no effect:

```Java
CSVFormat csvFormat = new CSVFormat();
csvFormat.delimiter("|");
csvFormat.nullString("{null}");
```

I've just printed like this:

```Java
System.out.println(result.formatCSV(csvFormat));
```
### Versions

- jOOQ:3.14.7
- Java:14
- Database (include vendor):-
- OS:-
- JDBC Driver (include name if inofficial driver):-

**Comment by lukaseder** [comment]
Yes, the type is immutable, which probably deserves some Javadoc mention. We're on a slop path towards immutability of the jOOQ API. You'll find that all (most?) of these configuration types are immutable already.

**Comment by lukaseder** [comment]
Added some Javadoc to 3.15
