### ISSUE TITLE
Feedback about manual section codegen-database-includes-excludes

### ISSUE THREAD

**Issue by vagelis-savvas** [jOOQ/jOOQ#11476]
Hello,
it would be useful to have Includes and Excludes also work the other way around,
i.e. exclude all and include only what is specified in Include.
Or is this possible already and I've missed it somehow?
Danke!

**Comment by lukaseder** [comment]
Thanks a lot for your message.

It already works this way, no? Just leave `<exclude/>` empty and include only the things you're interested in, e.g.

```xml
<include>TABLE1|TABLE2|TABLE3</include>
```

This won't generate anything but these 3 tables. What would be an example that doesn't work for you, yet?

**Comment by vagelis-savvas** [comment]
Oh of course, I didn't read correctly the docs, thank you!
