### ISSUE TITLE
Support for Trino DB

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11485]
Formerly known as Presto (https://github.com/jOOQ/jOOQ/issues/5414), now Trino:
https://trino.io/blog/2020/12/27/announcing-trino.html

## Database features / missing features

- No constraints
- No indexes
- No `NOT NULL` constraints (??): https://github.com/trinodb/trino/issues/4070
- No `DEFAULT`
- No identities
- No batches: https://github.com/jOOQ/jOOQ/issues/14784

## Some bugs found:

- https://github.com/trinodb/trino/issues/14199 (found by @GavinRay97)
- https://github.com/trinodb/trino/issues/16464
- https://github.com/trinodb/trino/issues/16489
- https://github.com/trinodb/trino/issues/16516
- https://github.com/trinodb/trino/issues/16522
- https://github.com/trinodb/trino/issues/16523
- https://github.com/trinodb/trino/issues/16525
- https://github.com/trinodb/trino/issues/16981
- https://github.com/trinodb/trino/issues/16982
- https://github.com/trinodb/trino/issues/16984
- https://github.com/trinodb/trino/issues/18726
- https://github.com/trinodb/trino/issues/18727
- https://github.com/trinodb/trino/issues/18731

## Missing features to work around:

- https://github.com/trinodb/trino/issues/6299
- https://github.com/trinodb/trino/issues/16470
- https://github.com/trinodb/trino/issues/16479
- https://github.com/trinodb/trino/issues/16540
- https://github.com/trinodb/trino/issues/16579
- https://github.com/jOOQ/jOOQ/issues/14803
- https://github.com/trinodb/trino/issues/18733

Also, existing PrestoDB limitations:

- https://github.com/prestodb/presto/issues/8200

----
See also:
- https://github.com/jOOQ/jOOQ/discussions/14059
- https://hub.docker.com/r/trinodb/trino
- https://trino.io/blog/2020/12/27/announcing-trino.html

**Comment by bannmann** [comment]
Hint: Depending on the SQL queries one uses, people may have success using jOOQ's PostgreSQL dialects to connect to Trino. We have been using this workaround for more than 4 years now without any trouble.

**Comment by HasanAmmori** [comment]
@bannmann 
I wonder how you connect PostgreSQL dialect to Trino since two dialects are vastly different. I assume, you could write a SQL query, that would work on both engines, but I don't think this is a jOOQ's core idea

**Comment by bannmann** [comment]
@HasanAmmori I don't know what exactly is affected by the choice of dialects, so I can only guess: maybe the reason is that the product in question does not use jOOQ's query builder or code generation. It merely uses jOOQ to execute user-defined SQL queries and to read result sets. I imagine that is a rather unusual scenario, so if that is the only reason it works, then my hint above is useless to most people :-/

**Comment by lukaseder** [comment]
A dialect consists of:

- A set of existing feature toggles scattered throughout the API (e.g. is `AS` a supported keyword for aliasing columns, tables)
- A set of not yet discovered feature toggles (e.g. there might be an alternative aliasing syntax that should be preferred)
- A set of ad-hoc dialect switches and if-elses (this is the biggest part, because a lot of switches are very dialect specific. Just look at the mess that is SQL date time arithmetic)

By now, it takes me about 2 person weeks to fully support a new dialect initially, discounting all the efforts that appear after going live, maintaining the dialect for years. For example, I've already spent almost 2 days getting the Vertica dialect up to date with more recent jOOQ developments, given that a customer had a feature request, and the investment was justified: https://github.com/jOOQ/jOOQ/issues/11650

Other ORMs which do not offer nearly as much SQL functionality as jOOQ, may find tweaking their internals for new dialects simpler. Their generated SQL is trivial SQL-92 - sometimes not even supporting unions, which are hard enough to get right on their own with all the possible cases of required/optional/forbidden parentheses!

So, the rule of thumb is this: You can get jOOQ to work with an existing dialect on a new database product to some extent. It will never be really as good as you're used to from supported dialects, and you will constantly run into issues, in case of which patching jOOQ or running plain SQL are the only options. We generally do not recommend using jOOQ with an unsupported dialect, but it may still work, and may still be better than any alternative.

Having said so, I'm very open to a sponsored integration project. The financial effort of paying me for a Trino integration is likely less than the effort of patching jOOQ all the time when it doesn't work with Trino, and it will pay off in the long run, after years of Trino support.

**Comment by lukaseder** [comment]
Looking into this for possible inclusion in jOOQ 3.19

First "fun" roadblock:

> SQL Error [13]: Query failed (#20230308_161807_00031_btv7d): line 1:17: Catalog 'memory' does not support non-null column for column name 'i'

Not sure what I should think of this 😅 No support for `NOT NULL` constraints?

**Comment by lukaseder** [comment]
Also: 

> This connector does not support modifying table rows

Gee. Which connector should I use for integration testing, to avoid most quirks / get access to most features? Obviously, I don't want to test them all.

**Comment by ThoSap** [comment]
> Also: 
> 
> > This connector does not support modifying table rows
> 
> Gee. Which connector should I use for integration testing, to avoid most quirks / get access to most features? Obviously, I don't want to test them all.

@lukaseder which connector does not support this, I did not find it in the docs:
https://github.com/search?q=repo%3Atrinodb%2Fdocs.trino.io+This+connector+does+not+support+modifying+table+rows&type=code


I can only chime in by saying that at our company we never used the memory connector once, we use the following (of many supported by Trino):
- [https://trino.io/docs/current/connector/delta-lake.html](Delta Lake)
- [https://trino.io/docs/current/connector/elasticsearch.html](Elasticsearch)
- [https://trino.io/docs/current/connector/kafka.html](Kafka)
- [https://trino.io/docs/current/connector/mongodb.html](MongoDB)
- [https://trino.io/docs/current/connector/oracle.html](Oracle)
- [https://trino.io/docs/current/connector/postgresql.html](PostgreSQL)
- [https://trino.io/docs/current/connector/redis.html](Redis)

Just the **fact** that it is possible for example to query Elasticsearch, Kafka, MongoDB and Redis using standard SQL, even joining different DBs (that are not RDBMS) in the same query, makes Trino soooo powerful!

Also many Fortune 100 companies now use Delta Lake in combination with Trino to store, fetch and analyze large-scale data.

If jOOQ supports Trino starting with 3.19.0 would make a huge difference and would also be a major selling point compared to other ORMs.

**Comment by richardfearn** [comment]
See https://trino.io/docs/current/connector/memory.html - when using the Memory connector the tables are effectively append-only. You can create a table, you can insert rows into it, and read them back; but you can't modify existing rows or delete them.

**Comment by findepi** [comment]
Modifying existing rows, deletes, NOT NULL constraints are supported by Iceberg and Delta Lake connectors.
Adding fully fledged features to the memory connector was not a priority so far, but  I understand how it would fit well the jOOQ testing.

**Comment by lukaseder** [comment]
Thanks for looking that up, @ThoSap, @richardfearn 

> Just the **fact** that it is possible for (crazy) example to query Elasticsearch, Kafka, MongoDB, Redis and Oracle using standard SQL, even joining tables/documents from different DBs (that are not RDBMS with RDBMS) in the same query, makes Trino soooo powerful!

No doubt, it is compelling for users. For me, I just need the path of least resistance to access *the most* features that are possibly available. I would have expected the memory (or file based) connector to be complete, because it does not "suffer" from any third party limitations, but obviously, that would mean that all transactional and other constraints would have to be implemented by trino itself.

I guess trino is more about "distributing compute" rather than implementing stuff itself? Makes sense for end users, of course.

> jOOQ supporting Trino starting with 3.19.0 would make a huge difference and would also be a major selling point compared to other ORMs.

Yeah 😅 I guess once you use one of those more rare RDBMS from the bottom of the list here https://db-engines.com/en/ranking, then support for that RDBMS does become a "selling point." I don't think it will make a key difference for the jOOQ community, but anyway, the number of upvotes on the issue has helped the issue bubble up in this list:
https://github.com/jOOQ/jOOQ/issues?page=1&q=is%3Aissue+sort%3Areactions-%2B1-desc+is%3Aopen

A contender is Clickhouse, but there, I think the vendor cheated with the upvotes.

Anyway. I was planning on adding support for 2-3 new dialects in 3.19, and this has been requested a few times by existing paying customers as well, so that justifies the effort without trying to find separate budget.

> @findepi Modifying existing rows, deletes, NOT NULL constraints are supported by Iceberg and Delta Lake connectors.
> Adding fully fledged features to the memory connector was not a priority so far, but I understand how it would fit well the jOOQ testing.

I don't even know what those things are 😅 (Iceberg and Delta Lake). I don't really want to spend time setting them up in a test environment.

How do *you* test these things? I mean, you have to have a complete test suite for all of the SQL features somewhere. Do you just test them indirectly via the connector that makes them available?

Is there a support matrix somewhere that shows which SQL features are supported by which connector? (I'm aware that each connector lists things in prose, but a matrix would be cool)

**Comment by lukaseder** [comment]
Anyway, the lack of `DELETE` support is just a problem for the setup of integration tests, which have a `reset.sql` script that deletes data again prior to resetting. It's probably possible to work around this limitation by simply resetting the entire schema instead of just the test delta, to get this started.

**Comment by findepi** [comment]
> How do _you_ test these things? I mean, you have to have a complete test suite for all of the SQL features somewhere. Do you just test them indirectly via the connector that makes them available?

Trino Engine cannot do anything without a connector. Besides testing with real connectors, we test with connectors that generate data on the fly (eg `tpch`) and with mocks/stubs for unit level tests.

> Is there a support matrix somewhere that shows which SQL features are supported by which connector? (I'm aware that each connector lists things in prose, but a matrix would be cool)

I am not aware of such a matrix. @bitsondatadev?

>  It's probably possible to work around this limitation by simply resetting the entire schema instead of just the test delta, to get this started.

That makes sense.

**Comment by lukaseder** [comment]
Random musing. Some connectors don't support `DELETE` or `NOT NULL`, but hey, [`MATCH_RECOGNIZE`](https://trino.io/docs/current/sql/match-recognize.html), that's a piece of cake to implement 😅

**Comment by GavinRay97** [comment]
As a side-tangent, supporting Trino would effectively give you Presto and Athena support as well, since they use (more or less) the same engines. When we developed jOOQ for Athena, we often used Trino as a secondary testing database because it was faster to test with.

Trino is the most up to date and featureful but I'd expect 95% of the Trino stuff to work with the others.

**Comment by lukaseder** [comment]
Thanks, @GavinRay97. I had a similar feeling.

**Comment by bitsondatadev** [comment]
> I guess trino is more about "distributing compute" rather than implementing stuff itself?
Mostly correct, Trino implements a distributed query engine layer and then has a connector framework to multiple databases. Depending on the database will dictate if Trino implements more or less "stuff" lol. So the Iceberg/Delta Lake things that Piotr mentioned are just metadata models on top of object storage. Trino implements the most stuff with these connectors because it's not pushing queries down but running the entire execution in it's query layer.

So likely the most test coverage would come from these systems which unfortunately require more test setup. It's a pretty linear cost to benefit function. I think a happy medium would be using something like PostgreSQL which uses a JDBC connection to connect to Postgres. Perhaps you already have some testing infrastructure in JOOQ that sets up Postgres?

> > Is there a support matrix somewhere that shows which SQL features are supported by which connector? (I'm aware that each connector lists things in prose, but a matrix would be cool)
> 
> I am not aware of such a matrix. @bitsondatadev?

Nothing today but this is on the roadmap.

**Comment by bitsondatadev** [comment]
> Random musing. Some connectors don't support `DELETE` or `NOT NULL`, but hey, [`MATCH_RECOGNIZE`](https://trino.io/docs/current/sql/match-recognize.html), that's a piece of cake to implement 😅

LOL! `MATCH_RECOGNIZE` lives in the query engine where `DELETE` differs depending on the connector. Most do though but this made me chuckle! You'll see that Trino's use cases up until the last couple years have been OLAP-focused so that's why there's more fancy reading capabilities and less support for updates/deletes.

**Comment by lukaseder** [comment]
Btw, thanks for your help, @bitsondatadev, @findepi: I really appreciate it!

**Comment by bitsondatadev** [comment]
I like that plan! 😀 once you do the bulk of the work are contributions for testing encouraged? I'd be happy to help with building out a test container.

**Comment by findepi** [comment]
> I'd have to think about how to nest a PostgreSQL instance in a docker container containing Trino, and run all that in testcontainers, or alternatively, bridge two containers and let them communicate

That should be possible with a `org.testcontainers.containers.Network`, if you're already using testcontainers.

**Comment by lukaseder** [comment]
> I like that plan! 😀 once you do the bulk of the work are contributions for testing encouraged?

Probably not? See https://github.com/jOOQ/jOOQ/blob/main/CONTRIBUTING.md
I'd rather reach out with specific questions.

> I'd be happy to help with building out a test container.

From experience, that won't be too hard. But I'll be happy to reach out if I run into troubles. First steps are always manual so I'm not at the TC stage yet.

**Comment by bitsondatadev** [comment]
I see. Thanks for the clear clarification. Please tag me if you think I can be instrumental in any way!

**Comment by lukaseder** [comment]
A first draft has been pushed to 3.19.0-SNAPSHOT last week. Now, the yak shaving begins

**Comment by lukaseder** [comment]
For those of you keen on using `MULTISET` with Trino, perhaps give these issues a bit of love:


- https://github.com/trinodb/trino/issues/16489
- https://github.com/trinodb/trino/issues/16522
- https://github.com/trinodb/trino/issues/16523
- https://github.com/trinodb/trino/issues/16525

I'll be reporting more in the near future. Seems like there's still some rough edges when working with non-trivial JSON queries... I'm going to be listing more bugs that I find in the issue description. It might as well be that `MULTISET` won't be ready for jOOQ 3.19.

**Comment by GavinRay97** [comment]
The above was found out first by taking the answer provided by this amazing SO person:
- https://stackoverflow.com/questions/73738969/athena-presto-sql-for-producing-array-of-nested-maps-structs-from-flat-rows

And realizing that it breaks after some levels of nesting, there's a bug in the decorrelator:
- https://stackoverflow.com/questions/73778276/trino-presto-athena-given-correlated-subquery-is-supported-trino-v371-athen

And then coworker explained you can use joins with group-by to emulate correlated subquery
- https://github.com/trinodb/trino/issues/14199

![image](https://user-images.githubusercontent.com/26604994/224742296-93fa83c1-cd19-47d7-8d49-b28bd8580f1f.png)

**Comment by lukaseder** [comment]
> To get around these issues @lukaseder, we actually use the `map_from_entries()` function along with `cast() as json` and row number aggregations

Yeah, I've found that one as well, and documented it in the issue: https://github.com/trinodb/trino/issues/16525#issue-1621586184

> We spent months on this

Well, there is always a way to expedite SQL dialect support in native jOOQ, for the next dialect... 😅

Anyway, I may have posted this a bit early (the part about `MULTISET` maybe not being ready for 3.19). I'll definitely spend more time with casting stuff around this week. Perhaps, the default in Trino should be `NestedCollectionEmulation.ARRAY` after all, given that this is the thing that works (though I ran into some `ROW` projection bugs as well, which I haven't investigated yet)

> And realizing that it breaks after some levels of nesting, there's a bug in the decorrelator:

I'll probably run into this one as well soon, once the yak is shaved a bit more. Thanks for the heads up!

**Comment by lukaseder** [comment]
> (though I ran into some `ROW` projection bugs as well, which I haven't investigated yet)

Ah no, I remember now. It's not a bug, just missing JDBC support: https://github.com/trinodb/trino/issues/16479

**Comment by lukaseder** [comment]
Alright, so using `CAST(MAP AS JSON)` instead of `JSON_OBJECT` and `CAST(ARRAY AS JSON)` instead of `JSON_ARRAY` seems to work around most of the limitations I've found so far.

**Comment by lukaseder** [comment]
Development status quo of 3.19.0-SNAPSHOT is already available online at https://www.jooq.org/translate

![image](https://user-images.githubusercontent.com/734593/225286578-44d85da5-a99e-41fb-a8df-7738e2677ed0.png)

**Comment by lukaseder** [comment]
Integrated for jOOQ 3.19.

The implementation is far from complete. The fact that the in-memory backend lacks a ton of functionality (yet it is the simplest to test without excessive test setup) means that jOOQ probably doesn't cover some stuff users might be using, e.g. `DELETE` or `UPDATE` syntax.

This can be addressed in future releases, still.

**Comment by lukaseder** [comment]
To anyone interested in this dialect, please note that early feedback is very appreciated! You can build the jOOQ Open Source Edition off github, or work with a 3.19.0-SNAPSHOT build, if you're licensed:
https://www.jooq.org/download/versions
