### ISSUE TITLE
SQL null in JSONB type column not represented as null JSONB class reference

### ISSUE THREAD

**Issue by alesbukovsky** [jOOQ/jOOQ#11497]
I am upgrading from JOOQ 3.13 to 3.14.

I have a custom biding / converter to translate JOOQ's `JSONB` objects to Jackson's `JsonNode`. The application works with generic `JsonNode` objects, it does not use further mapping of JSON to/from POJO. For nulls I assume the column value to be SQL `null`, not JSON/B representation of a null node.  

Writing nulls works with the same code in both 3.13 and 3.14. In the converter both `null` and `NullNode` are taken care of:
```
public JSONB to(JsonNode o) {
    ...
    return (o != null && !o.isNull()) ? JSONB.valueOf(mapper.writeValueAsString(o)) : null;
}
```

However reading nulls works in 3.13, but breaks in 3.14. The respective converter code:
```
public JsonNode from(JSONB o) {
    ...
    return (o != null && o.data() != null) ? mapper.readTree(o.toString()) : null;
}
```

Further testing revealed that the `o.data()` in this case returns the string `"null"`. It seems directly related to #10343. However the `JSONB` Javadoc still states that `CAST(NULL AS JSONB)` should return a null `JSONB` reference.

I can certainly modify the converter to handle the `"null"` String use case as well. But I would like to verify this is actually an intended consequence of the #10343. It still seems more logical to me to get `null` JSONB reference if the actual column contents is SQL `null`.

**Comment by lukaseder** [comment]
There's a difference between `o == null` (the result of `CAST(NULL AS JSONB)`) and `"null".equals(o.data())` (the result of `CAST('NULL' AS JSONB)`. Try it in plain SQL:

```sql
select cast(null as jsonb), cast('null' as jsonb)
```

#10343 fixed a mistake where `o.data() == null` could have been returned. That encoding has no meaning in SQL.

- Either the `JSONB` value is SQL `NULL`, and thus as explained in #10343, for consistency with all the other data types, a jOOQ record will contain a Java `null` value.
- Or the `JSONB` value is not SQL `NULL`, and there is thus a non-Java `null` String representation for it.

> It still seems more logical to me to get `null` JSONB reference if the actual column contents is SQL `null`.

Yes, and that's exactly what's happening. But the string `"null"` is not the SQL `NULL` value, it's a non-SQL `NULL` JSON `null` value.

**Comment by alesbukovsky** [comment]
Thanks for the answer. Unfortunately it is inconsistent with my observations.

I am running PostgreSQL 9.6. I have a simple table with `JSONB` type column. I have inserted an SQL `null` into it directly via a CLI database client (`pgcli`). I am 100% sure it is SQL `null`, because the client shows these is a distinct way.

Puzzled by the inconsistency of your logical description and my observation, I have started all over again from the basics. I have generated JOOQ artifacts without any conversion at all, simply using the provided `JSONB` representation. This actually works as described. Upon running JOOQ `SELECT` I've got Java `null` for the `JSONB` column data, i.e. null `JSONB` object reference. The JOOQ debug output shows the value as:

```
+-----------+
|survey_data|
+-----------+
|{null}     |
+-----------+
```

So far so good. 

I continued by putting back the converter. And **now it doesn't work** - the converter doesn't get the null `JSONB` reference. Instead it gets an actual JSONB instance reference with `data` set to String `null`. So it appears that the underlying query result parsing result is different, for one reason or another, when a converter is involved.

Also the debug output of the same JOOQ `SELECT` in this case is this (no curly brackets, so it is not considered SQL `null`, I am guessing):

```
+-----------+
|survey_data|
+-----------+
|null       |
+-----------+
```

The generated code for the affected column seems correct:
```
public final TableField<Record, JsonNode> SURVEY_DATA = createField(DSL.name("survey_data"), SQLDataType.JSONB, this, "", new JsonbJacksonConverter());
```


Here is my converter code:
```
public class JsonbJacksonConverter implements Converter<JSONB, JsonNode> {

    static ObjectMapper mapper = new ObjectMapper();

    @Override
    public JsonNode from(JSONB o) {
        try {
            return (o != null && o.data() != null) ? mapper.readTree(o.toString()) : null;
        } catch(Throwable ex) {
            throw new BindingException("Failed to convert JSONB to JsonNode", ex);
        }
    }

    @Override
    public JSONB to(JsonNode o) {
        try {
            return (o != null && !o.isNull()) ? JSONB.valueOf(mapper.writeValueAsString(o)) : null;
        } catch(Throwable ex) {
            throw new BindingException("Failed to convert JsonNode to JSONB", ex);
        }
    }

    @Override
    public Class<JSONB> fromType() {
        return JSONB.class;
    }

    @Override
    public Class<JsonNode> toType() {
        return JsonNode.class;
    }
}
```

And here is my code generation configuration from Gradle:
```
jooq {
    version = jooqVersion
    configurations {
        main {
            generationTool {
                jdbc {
                    driver = 'org.postgresql.Driver'
                    url = dbUrl
                    user = dbUser
                    password = dbPswd
                    schema = 'public'
                }
                generator {
                    name = 'org.jooq.codegen.DefaultGenerator'
                    strategy {
                        name = 'org.jooq.codegen.DefaultGeneratorStrategy'
                    }
                    database {
                        name = 'org.jooq.meta.postgres.PostgresDatabase'
                        inputSchema = 'public'
                        outputSchemaToDefault = true
                        forcedTypes {
                            forcedType {
                                userType = 'com.fasterxml.jackson.databind.JsonNode'
                                converter = 'com.abu.jooq.JsonbJacksonConverter'
                                includeExpression = '.*'
                                includeTypes = 'JSONB'
                            }
                        }
                    }
                    generate {
                        relations = true
                        deprecated = false
                        records = false
                        immutablePojos = false
                        fluentSetters = true
                        javaTimeTypes = false
                    }
                    target {
                        packageName = 'com.abu.db'
                        directory = 'src/main/generated'
                    }
                }
            }
        }
    }
}
```
