### ISSUE TITLE
Add jbang example to the manual

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11492]
Apparently, running the jOOQ code generator with jbang is super easy:
https://twitter.com/maxandersen/status/1363803581397278721

We should document this in the manual/tutorial.

### Tasks

- [ ] Document this in the manual / tutorial
- [x] Add a "jbang-catalog" (see tweet) to further simplify this

**Comment by maxandersen** [comment]
if you create a jbang-catalog repo I can submit PR with how I think this should/could work ;)

**Comment by lukaseder** [comment]
That sounds great, though is a repo the right place for this? Usually, I prefer modules or example projects, not a top level repo. Is there a reason why a repo is better, except to simplify the PR?

**Comment by maxandersen** [comment]
its just that if you put it in lets say `jooq/jooq` then it would be `jbang codegen@jooq/jooq` instead of just `jbang codegen@jooq`.

I can definitely start with a pr on `jooq/jooq` if you want that.

**Comment by maxandersen** [comment]
Made a PR against jooq/jooq to show what I'm talking about. Details in #11492

I do recommend using `jooq/jbang-catalog`, but up to you.

**Comment by maxandersen** [comment]
btw. I used the word `codegen` as that seem to be the word used in docs; but maybe `gentool` is more apropriate.

And we could also add most common jdbc drivers as direct `//DEPS` but I thought nice to have explicit control using `--deps`.

**Comment by maxandersen** [comment]
I meant https://github.com/jOOQ/jOOQ/pull/11499 - copy/paste error

**Comment by lukaseder** [comment]
> its just that if you put it in lets say `jooq/jooq` then it would be `jbang codegen@jooq/jooq` instead of just `jbang codegen@jooq`.

Oh, so these coordinates are github based? I'll have to do some reading first, but given that `jOOQ/jOOX` and other libraries exist, I guess it wouldn't be correct to assume a `jOOQ/jbang-catalog` github project is jOOQ's only, as opposed to any other's.

On the other hand, currently, there's no conflict in our namespace with respect to `codegen`, so this might still be changed later on if some other library ever does introduce code generation...

> btw. I used the word `codegen` as that seem to be the word used in docs; but maybe `gentool` is more apropriate.

The module is called `jooq-codegen`, so I think it's a good idea to reuse that term.

**Comment by maxandersen** [comment]
You can also always introduce a repo specific jbang catalog or just prefix them to avoid conflicts in future.

**Comment by lukaseder** [comment]
Here's a working example: https://github.com/jOOQ/jbang-example/blob/main/README.md. I'll add that also to the manual, and I think we're all set!

Really nice work with jbang, @maxandersen !
