### ISSUE TITLE
Problem Implicit casting with Jooq

### ISSUE THREAD

**Issue by OualidShayeb** [jOOQ/jOOQ#11490]
### Your question:

Hi, thanks for this great tool.
We are migration our project from oracle database to postgresql, everything went well with jooq except implicit casting which  oracle did, so we are facing problems with the oracle requests that we have when we do the join fro example "ERROR: the operator does not exist : character varying = bigint", we had also problems with the casting of the bind parameters.
I am wondering if there's a way to avoid manually casting by scanning all the requests and adding either "to_date" or "::date" for example which will be a taugh mission ! 
### Versions:

- jOOQ: 3.14
- Java: Java 8
- Database (include vendor): input : oracle 11, output postgresql 12
- OS: Linux
- JDBC Driver (include name if inofficial driver): 4.1

**Comment by lukaseder** [comment]
Thanks a lot for your message.

I *think* that you're running into a case where we cast bind variables in the absence of knowledge of the data type. This is historic behaviour that we should definitely address in the very near future, as other customers have run into this as well: https://github.com/jOOQ/jOOQ/issues/11475

In most cases, you can work around the wrong casts by providing jOOQ with meta information (`CREATE TABLE`, etc.). I would have to see some code that helps reproduce the specific problem that you ran into to help you further here.

**Comment by OualidShayeb** [comment]
Hi lukas, 
i don't think that will be a good solution, because we are using jdbc and the database exists we don't need to create table;

for example :
This is the Jooq Connection : 
public static Connection getJooqConnection() throws Exception {
		ExecuteListener jooqListener = new DefaultExecuteListener() {
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			@Override
			public void executeStart(ExecuteContext ctx) {

				// Create a new DSLContext for logging rendering purposes
				// This DSLContext doesn't need a connection, only the SQLDialect...
				DSLContext create = DSL.using(ctx.dialect(),

						// ... and the flag for pretty-printing
						new Settings().withRenderFormatted(true));

				// If we're executing a query
				if (ctx.query() != null) {
					TbsLog.info("jooq : " + create.renderInlined(ctx.query()));
				}

				// If we're executing a routine
				else if (ctx.routine() != null) {
					TbsLog.info("jooq : " + create.renderInlined(ctx.routine()));
				}
			}

			@Override
			public void start(ExecuteContext ctx) {

				// Register the start time to the current context
				ctx.data("jooq : time", System.nanoTime());
			}

			@Override
			public void end(ExecuteContext ctx) {

				// Extract the start time from the current context
				Long time = (Long) ctx.data("time");
				TbsLog.info("jooq : Execution time : " + ((System.nanoTime() - time) / 1000 / 1000.0) + "ms. Query : "
						+ ctx.sql());
			}
		};
		Settings settings = new Settings()
				.withTransformRownum(true)
				.withParseUnknownFunctions(ParseUnknownFunctions.IGNORE)
				.withParamCastMode(ParamCastMode.ALWAYS)
				.withTransformTableListsToAnsiJoin(true)
				.withParseDialect(SQLDialect.ORACLE)
				.withParamType(ParamType.NAMED);
		Configuration jooqConfig = new DefaultConfiguration().set(getConnection()).set(SQLDialect.POSTGRES_12)
				.set(settings).set(jooqListener);

		DSLContext ctx = DSL.using(jooqConfig);

		return ctx.parsingConnection();

	}
Execution of a prepared statement :
Connection connJooq =  ConnectionHelper.getJooqConnection();
PreparedStatement st = connJooq.prepareStatement("select * from (
 select lmr.id_media, lmr.content_type, lmr.bin_data, 'PARTNER' logo_orig, '1' tri
 from personne p
 inner join connper cpmr on cpmr.id_per = p.id_per and cpmr.cd_con = 'MARQUE'
 inner join multimedia lmr on lmr.cd_serv = 'LOGO_PERS'  and lmr.idtab_media = cpmr.id_conp
 where p.id_per = null
 union all
 select lsoc.id_media, lsoc.content_type, lsoc.bin_data, 'SOC' logo_orig, '2' tri
 from personne p
 inner join multimedia lsoc on lsoc.cd_serv = 'LOGO_PERS'  and lsoc.idtab_media = p.id_per
 where p.id_per = null and p.id_per = null
 union all
 select def.id_media, def.content_type, def.bin_data, 'SOC' logo_orig, '3' tri
 from multimedia def
 where def.cd_serv = 'LOGO_DEF'
 union all
 select def.id_media, def.content_type, def.bin_data, 'DEF' logo_orig, '4' tri
 from multimedia def
 where def.cd_serv = 'LOGO_DEF'
)
 order by 5");	
ResultSet rs = st.executeQuery();

This generates a exception : 
Execution StackTrace:
org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying = bigint
  Hint: No operator matches the given name and argument types.
You must add explicit type conversions.
  Position: 272
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse (QueryExecutorImpl.java:2553)
at org.postgresql.core.v3.QueryExecutorImpl.processResults (QueryExecutorImpl.java:2285)
at org.postgresql.core.v3.QueryExecutorImpl.execute (QueryExecutorImpl.java:323)
at org.postgresql.jdbc.PgStatement.executeInternal (PgStatement.java:473)
at org.postgresql.jdbc.PgStatement.execute (PgStatement.java:393)
at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags (PgPreparedStatement.java:164)
at org.postgresql.jdbc.PgPreparedStatement.execute (PgPreparedStatement.java:153)
at org.jooq.tools.jdbc.DefaultPreparedStatement.execute (DefaultPreparedStatement.java:214)
at com.tbs.db.TestJooqFromDatabase.test (TestJooqFromDatabase.java:138)
at com.tbs.db.TestPostgreSQL.main (TestPostgreSQL.java:67)
***

**Comment by lukaseder** [comment]
Thanks a lot for the additional feedback. That does look a lot like the issues we've been having recently. We'll fix this with high priority, for sure - probably this week.

As a workaround, you can avoid bind variables for now using the `Settings.statementType` configuration, by setting it to `StatementType.STATIC_STATEMENT`. While in Oracle, bind variables help with execution plan caching, the cache in PostgreSQL is not as sophisticated, and as such, bind values aren't as useful in PostgreSQL from a performance perspective.

Of course, in the long run, you'll still want to use bind variables, but for your evaluation, this might already do the trick.

I'll keep you posted on progress of the other issues. If you discover any additional problems, please just let me know, and I'll be very happy to assist.

**Comment by OualidShayeb** [comment]
Thank you so much Lukas, i will look forward for the fix !
