### ISSUE TITLE
Log deprecation warning when Serialization of jOOQ API is triggered

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11506]
I'd like to eventually remove our dependency of jOOQ API being `Serializable` (see https://github.com/jOOQ/jOOQ/issues/2359).

Before we move ahead and remove this feature, let's add some methods to `AbstractQueryPart`, which will log a warning if someone uses the feature. They should get in touch on this issue here and explain their use-case:

```java
private static class SerializationDeprecation {}
private static final JooqLogger    log       = JooqLogger.getLogger(SerializationDeprecation.class);
private static final AtomicInteger warnCount = new AtomicInteger(0);
private static final int           maxWarnings = 100;

private void readObject(ObjectInputStream ois) throws IOException, ClassNotFoundException {
    ois.defaultReadObject();

    if (log.isWarnEnabled() && warnCount.getAndUpdate(i -> Math.min(i + 1, maxWarnings)) < maxWarnings)
        log.warn("DEPRECATION", "A QueryPart of type " + getClass() + " has been deserialised. Serialization support is deprecated in jOOQ. Please contact https://github.com/jOOQ/jOOQ/issues/11506 and state your use-case to see if it can be implemented otherwise.");
}

private void writeObject(ObjectOutputStream oos) throws IOException {
    oos.defaultWriteObject();

    if (log.isWarnEnabled() && warnCount.getAndUpdate(i -> Math.min(i + 1, maxWarnings)) < maxWarnings)
        log.warn("DEPRECATION", "A QueryPart of type " + getClass() + " has been serialised. Serialization support is deprecated in jOOQ. Please contact https://github.com/jOOQ/jOOQ/issues/11506 and state your use-case to see if it can be implemented otherwise.");
}
```

If we don't get enough feedback, or not enough compelling reasons to keep serializability, which cannot be implemented through any better way, then we can drop the feature in the near future.

**Comment by noobymatze** [comment]
Hi, first of all, thank you so much for JOOQ! I've worked with a few languages by now and in my opinion, there is no library for working with SQL, that comes even close to JOOQ in ergonomics, simplicity and just pure awesomeness. Using ORMs or building Strings (even if type safe in some languages) feels just pale and painful in comparison. So, thank you!

Secondly, concerning this issue (please let me know, whether this is the right place to post this): I would be very happy, if `Record`s, `Field`s and `Table`s could keep their `Serializable` interface, but I completely understand that this may not be possible or desirable. I just thought, I'd share my use case.

The reason for wanting to keep the `Serializable` interface, is that using JOOQ in combination with the web framework [Apache Wicket][1] will become much less convenient. Wicket relies heavily on [serialization][2], as it serializes nearly every web page (which is just a class) to disk to make the browsers back button work. 

Using `Record`s, `Table`s and `Field`s allows one to build some nice generic components. Take a look at the following example for a paginated sortable table, taken from a personal [project][3] of mine (feel free to poke around the repository).

```kotlin
val provider = DSLContextDataProvider(CLUBS_VIEW, this) {
    DSL.trueCondition()
}

add(RecordTable<ClubsView, ClubsViewRecord>("table", provider, {
    property("Name", { CLUB_NAME }) { it.clubName }
    property("Verband", { ASSOCIATION_NAME }) { it.associationName }
}))
```

At first a [data provider][4] is created by using JOOQs generated `CLUBS_VIEW` and a way to access a `DSLContext` (`this`). The data provider is responsible for providing access to pageable data.

<details>
    <summary>If you are interested, open this to see the full implementation of the DSLContextDataProvider</summary>

```kotlin
class DSLContextDataProvider<T: Table<R>, R: Record> constructor(
    internal val table: T,
    private val provider: DSLProvider,
    private val defaultSort: (T.() -> Pair<TableField<R, *>, Boolean>)? = null,
    private val filter: RecordTable.Filter<T, R> = RecordTable.Filter<T, R> {
        DSL.trueCondition()
    }
): SortableDataProvider<R, Field<*>>() {

    override fun iterator(first: Long, count: Long): MutableIterator<R> {
        val dsl = provider.dslContext()
        if (sort == null && defaultSort != null) {
            val s = defaultSort.invoke(table)
            @Suppress("UNCHECKED_CAST")
            setSort(SortParam(s.first, s.second))
        }

        val primaryKeys = table.primaryKey?.fields ?: emptyList()
        return dsl.selectFrom(table)
            .where(with (filter) { table.condition() })
            .let { q ->
                sort
                    ?.let {
                        if (it.isAscending)
                            it.property.asc()
                        else
                            it.property.desc()
                    }
                    ?.let { q.orderBy(listOf(it) + primaryKeys.map { c -> c.asc() }) }
                    ?: q.orderBy(primaryKeys.map { c -> c.asc() })
            }
            .offset(first)
            .limit(count)
            .fetch()
            .iterator()
    }

    override fun size(): Long =
        provider.dslContext()
            .selectCount()
            .from(table)
            .where(with (filter) { table.condition() })
            .fetchOneInto(Long::class.java)
            ?.toLong() ?: 0L

}
```
</details>

Using the provider, a UI table is created by using `Field`s for sorting and using properties of `ClubViewRecord`s to fill the columns of a row.

Without `Serializable`, `Record`s, `Field`s and/or reflection, I am not sure, whether one could build this as easily or even at all. I believe one could use POJOs to still build [forms][5] nearly as conveniently as with `Record`s, though we might need to tweak code generation a bit to let POJOs implement `Serializable`, but I am pretty sure, I have seen this kind of option somewhere before, so probably all doable. But I am not so sure about this table, especially considering the usage of `Field`s for sortable columns.

I hope, this provides the kind of use case you were looking for and I have not been wasting your time. But I can completely understand, if you'd prefer throwing out `Serialization`, just maybe a small anecdotal data point. 

Cheers!

[1]: https://wicket.apache.org
[2]: https://ci.apache.org/projects/wicket/guide/9.x/single.html#_page_versioning_and_caching
[3]: https://gitlab.noobymatze.io/noobymatze/ref/-/blob/master/src/main/kotlin/io/noobymatze/web/pages/clubs_view/ClubsViewPage.kt#L26
[4]: https://ci.apache.org/projects/wicket/apidocs/9.x/org/apache/wicket/extensions/markup/html/repeater/util/SortableDataProvider.html
[5]: https://gitlab.noobymatze.io/noobymatze/ref/-/blob/master/src/main/kotlin/io/noobymatze/web/pages/clubs/ClubsEditPage.kt#L55

**Comment by lukaseder** [comment]
Thanks a lot for your feedback, @noobymatze, and for your nice words. Very appreciated. In case you have twitter, I'd love to retweet such a tweet :)

> I've worked with a few languages by now and in my opinion, there is no library for working with SQL, that comes even close to JOOQ in ergonomics, simplicity and just pure awesomeness.

This is the perfect place to provide feedback, I'm glad you did. The final decision has not yet been made regarding the dropping of `Serializable` support. It may as well stay, if enough use-cases like yours are provided.

Note, the flag you were looking for in the code generator was `<serializablePojos/>`

**Comment by noobymatze** [comment]
Thank you so much for your kind response @lukaseder!

> Note, the flag you were looking for in the code generator was <serializablePojos/>

Noted, thank you so much! 

If there is anything else I can do, just mention it. Happy coding!

**Comment by jankoh** [comment]
Hi,

we are using jOOQ with Spring Boot and Kotlin and define the internal User model using jOOQ-provided Records:
```kotlin
data class UserInternal(
    val user: UserRecord,
    val groups: Collection<UserGroupRecord>
) : UserDetails { 
    // ...
}
```

Unfortunately `UserDetails` is specified to be serializable, so we get a bunch of warnings in our logs. As far as I've seen, we could switch (back) to POJOs in the model but we're on our way to (mostly) drop the POJOs, except for test classes since Records seem way more comfortable to use in production code. 

Since the warnings we get specify this issue: How to get rid of those warnings? Would we need to implement the serialization on our own? Or switch back to POJOs? 

Thanks and best regards, Jan

**Comment by lukaseder** [comment]
@jankoh What's the use-case of serialising jOOQ records?

You can turn off the warnings in your logger by specifying a log level for jOOQ's logger

**Comment by jankoh** [comment]
@lukaseder thanks for your reply! :smile: 

We're not actually deserializing the Records ourselfs, it happens when Spring Session stores the user session (in the database). Spring Session then deserializes the UserDetails-Object which in our case happens to consist of jOOQ Records.

While debugging, I figured, Spring Session is serializing the whole stuff again when committing the session. 

I'm not quite sure how to work around this: Maybe there's a way to control (de)serializng within spring Session, I need to check that. Otherwise our only option beides turing of logging would be to switch back to POJOs, I guess...

**Comment by lukaseder** [comment]
@jankoh Why do you put records in the session? Do you need to restore their dirty flags on a subsequent request? Have you benchmarked the costs of this? A record has a reference to the generated schema, so depending on how Spring Session implements this, each serialisation might be very costly, and when deserialising, I'm not convinced that Spring Session will restore jOOQ's static initialised schema's semantics...

This sounds like something I wouldn't do, and it is part of the reason why `Serialization` has been deprecated. It's too easy to get *something* to work, but that will unlikely be the optimal way of implementing it.

**Comment by jankoh** [comment]
@lukaseder I wasn't even aware of how the UserDetails model is handeled internally when storing a session before the log-messages popped up. So I guess, this indeed is a case to use POJOs, then?

**Comment by ksi-patrick-kainz** [comment]
Hi, we channel our database requests from tests through the server via a remote method invocation implementation. If queries ceased to be serializable, we would no longer be able to do that. Thanks!

**Comment by lukaseder** [comment]
Thanks for sharing your use-case, @ksi-patrick-kainz. You say you're doing this "from tests." So, this isn't production code? Would there be an alternative way to implement this on your side?

**Comment by ksi-patrick-kainz** [comment]
@lukaseder Well yes for the most part this is used for integration tests, we have a Java Enterprise application running in a Wildfly application server. During integration tests the tests tunnel their database access through the application server, so they do not need to know where the database is and how to access it. This is used mostly for data preparation and verification. 
There have however been rare cases, when the testframework was used to fix a production system that managed to get into such a bad state that rescuing it required high automation and close collaboration with the running software in the application server. 

Right now I do have a workaround, but I am not happy with it: The application server shares the database access data with the tests and the tests then establish their own connection to the database. This works for most cases, however in some cases (for example if the server and database were to be running in a container environment, which is where we want to go in the future), this wouldn't work, since the networks of the server and test client would be different and the client would either need to use a different ip and port, or not be able to access the database at all.

In a perfect world there would be another solution to this problem: Jooq already supports different execution methods for queries (you can get both the SQL and Bind variables and then execute those yourself), but result mapping to records is not possible for those as far as I can see. I assume that this is the case because Jooq needs to be able to "stream" results from a resultset and hence the result mapping needs to be tightly integrated with the database connection. If this were to be refactored so that the resultmapping interacts with some kind of simple interface, we could develop our own SQL execution layer.

**Comment by lukaseder** [comment]
> During integration tests the tests tunnel their database access through the application server, so they do not need to know where the database is and how to access it.

Why not do this at the JDBC layer, with connection pools and data sources? You still get the benefit you require (not knowing where the database is and how to access it), without the complexity.

> There have however been rare cases, when the testframework was used to fix a production system that managed to get into such a bad state that rescuing it required high automation and close collaboration with the running software in the application server.

Of course, you've already set up a query execution API that can accept jOOQ objects, so why not occasionally use it for such purposes, I can see that.

But you could also just connect to the production database using a SQL client and run a quick ad-hoc query to patch your data, no? It seems simpler to me. If you need jOOQ objects and API for such quick fixes, you could still go the JDBC route, where your JDBC URL connects to the production database, so I don't see much benefit of having the production application server being involved in receiving jOOQ objects.

> Jooq already supports different execution methods for queries (you can get both the SQL and Bind variables and then execute those yourself), but result mapping to records is not possible for those as far as I can see.

It's possible, of course, but you're throwing away 50% of jOOQ's value proposition. People have often tried to execute SQL elsewhere (e.g. on JPA) and use jOOQ *only* as a SQL builder. Then they keep running into tons of limitations because they have to re-implement the binding and mapping logic, which is a lot of work... Just look at the `MULTISET` serialisation logic, which is far from trivial. If there was an obvious gain with such approaches, I'd understand, but there is none, as far as I can tell - other than slightly simpler architecture diagrams (*every* DB interaction goes through JPA).

Hence, I always link to this article here:
https://blog.jooq.org/why-you-should-execute-jooq-queries-with-jooq

Of course, it's still a good thing to be able to extract SQL strings and bind values from jOOQ queries for various reasons, including debug logging, or even occasional execution elsewhere. But I don't think it's a good idea to build an entire application based on such an approach.

> If this were to be refactored so that the resultmapping interacts with some kind of simple interface, we could develop our own SQL execution layer.

This sounds like a very complex abstraction for almost no gain to me. To give you some perspective: 

Look at the messy experiment that is jOOQ's R2DBC integration, which is a comparable thing to what you're asking for. Our integration is perhaps at 50% ("good enough"), not supporting tons of useful things like arrays, UDTs, stored procedures, tons of exotic data types, various forms of batch, etc. etc. It's mediocre, and will be deprecated eventually, once JDK's project loom proves that the reactive model isn't really necessary to better distribute load across CPUs. The fact that there are only so few drivers doesn't help. It hasn't been adopted well.

But at least R2DBC (and the reactive model) were a hype 5-10 years ago, with a lot of folks willing to jump on this train and "testing" it in production. Adding another execution abstraction in the middle of jOOQ will generate no such buzz, and will be used only by 1-2 power users (and probably abandoned halfway, for better alternatives, including you when you go down the container route), thus my reservation in terms of cost/benefit.

I can see decoupling of client/server stuff at the service layer (REST, RMI, etc. etc.), where you're in full control, where there's hardly any complexity in terms of protocol design, where you don't depend on third parties. I can see it at the network layer (JDBC), where a lot of folks have already been doing this for ages. I can't see this inside of jOOQ. It just seems to be the wrong layer to do any decoupling, to me.

Related to this, note that abstraction of the driver (JDBC / R2DBC) was a feature request at some point:

- https://github.com/jOOQ/jOOQ/issues/6298

With such an abstraction, even more drivers could have been supported, including e.g. Vert.x drivers. But I already predicted that R2DBC was going to be a fad that will fade again, so I preferred the direct integration, which was far more easy, as it allowed to hide many R2DBC parts behind a JDBC proxy API to jOOQ's internals (e.g. your `Converter` and `Binding` implementations still work on R2DBC, despite them interacting only with the JDBC API).

Today, I'm really glad I didn't add such a complex abstraction. JDBC is a very sound API, one of Java's best APIs, in fact! And even with JDBC, integration of all the hundreds of edge cases is such a mess. Look at how jOOQ binds and reads JDBC arrays or UDTs to the various drivers. Now imagine having to define another abstraction for all of those edge-cases.

### Back to serialisation

The above use-case discussion is a very interesting one, and clearly shows that we're not ready for *removing* this feature yet. This is why it makes sense to re-introduce test coverage and fix things like this related issue of yours:

- https://github.com/jOOQ/jOOQ/issues/16965

But the deprecation will remain in place. Java's serialisation has serious flaws, even if it appears to be very convenient at first.

In jOOQ's case, while it seems useful to serialise queries and results, the generated code is not designed for this use-case *at all*. A generated `Table` references its `Schema`, which again references all the other generated objects, leading to a huge overhead, when the schema is large.

Of course, we could address such issues and spend more time optimising them, but again, the cost/benefit ratio seems off here.

I've taken this opportunity to make a quick, non-representative poll on Twitter:

- https://x.com/lukaseder/status/1811381199039758352

Only very few people still use RMI style APIs with serialisation involved. The chance that those few people serialise jOOQ objects isn't very high, so I still believe that this "power user feature" doesn't have to be maintained forever.

**Comment by lukaseder** [comment]
> To be honest I don't quite understand what you mean, I may lack the understanding for the background in JDBC, do you propose we provide a JDBC Driver that tunnels the statements to our server?

Depending on your execution mode, you can inject several different JDBC `DataSource` instances. That way, you'll transparently execute all your statements on the configured database...

> To be honest since our RMI mechanism actually uses SOAP in the background I didn't even think we were using Java serialization, but it turns out we are, we are just wrapping it in a SOAP request, so that surely is something we could work on. But I think I remember other serialization mechanisms also requiring the Serializable annotation.

Hmm, how do you serialise jOOQ queries in SOAP?

**Comment by ksi-patrick-kainz** [comment]
> Depending on your execution mode, you can inject several different JDBC DataSource instances. That way, you'll transparently execute all your statements on the configured database...

I think I am still missunderstanding, as far as I can see any datasource still requires a driver in the background, so somewhere in the client i would still need to figure out how to connect to the database directly. The server can't just tunnel its datasource to the client, it can just provide it with the access data, as mentioned above. 

> Hmm, how do you serialise jOOQ queries in SOAP?
Well per default it can of course not do it, SOAP expects JAXB annotated classes for serialization i think. Now that I think about it, one of course would need to serialize with some generic mechanism and then plug the serialized data into the soap request, which is probably why we did what we did. 


Anyway, I think we are getting of topic, for now we will try to live with the client connecting to the database directly, if that yields any problems (due to the database being inaccessiable from the client), we will have to do this without using the java serialization mechanism somehow.

Thanks :)

**Comment by lukaseder** [comment]
Over the past years, there has been multiple occasions of user feedback where users used jOOQ's out of the box serialisation support for RPC purposes, which makes sense.

I've decided to revert the deprecation going forward:

- https://github.com/jOOQ/jOOQ/issues/17208
