### ISSUE TITLE
DataType.convert() returns null instead of throwing exception

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#11510]
### Expected behavior
Per the Javadoc, `DataType.convert(Object)` is supposed to throw `DataTypeException` if the conversion fails.

### Actual behavior
The `DataType` for an `OffsetDateTime` field returns `null` when `DataType.convert("0")` is invoked. This is because this code block from Convert.java:

```
else if (fromClass == String.class && toClass == OffsetDateTime.class) {

                    // Try "local" ISO date formats first
                    try {
                        return (U) java.sql.Timestamp.valueOf((String) from).toLocalDateTime().atOffset(OffsetDateTime.now().getOffset());
                    }
                    catch (IllegalArgumentException e1) {
                        try {
                            return (U) OffsetDateTime.parse((String) from);
                        }
                        catch (DateTimeParseException e2) {
                            return null;  <---- guilty party
                        }
                    }
                }
```

- jOOQ: 3.14.7

**Comment by lukaseder** [comment]
Maybe, some time in the distant future, we can break compatibility and throw instead of returning `null`: https://github.com/jOOQ/jOOQ/issues/4681

The Javadoc says:

> Throws:DataTypeException - If conversion fails.

But it doesn't fail. It works as designed. Failures mostly happen when specific data types are not supported at all, not when values are not convertible to a specific data type.

**Comment by cowwoc** [comment]
@lukaseder 

>  Failures mostly happen when specific data types are not supported at all, not when values are not convertible to a specific data type.

Please update the Javadoc accordingly. Currently there is no mention of returning `null` in this case.

I saw `See {@link Convert#convert(Object, Class)} for details about conversion rules.` but when I read the rules there is still no mention of returning `null` in this case.

**Comment by lukaseder** [comment]
I prefer not to set this in stone, or it will complicate the (backwards incompatible) change in the future.
