### ISSUE TITLE
WITH clause AS update

### ISSUE THREAD

**Issue by anewton1998** [jOOQ/jOOQ#11527]
### Your question:

The documentation on the WITH clause alludes to the usage with databases that support it DML other than `select`.

Am I simply reading too much into this, or is there a way to do `WITH updated AS (UPDATE...`? The DSL seems to limit this to select.

### Versions:

- jOOQ: 3.14
- Java: 11 / Kotlin 1.4
- Database (include vendor): Postgres 13
- OS: Ubuntu 20.04
- JDBC Driver (include name if inofficial driver):  42.2.2

**Comment by lukaseder** [comment]
Thanks for your message. That's currently not possible, but we've recognised this is a much requested feature and will hopefully be able to offer it soon: https://github.com/jOOQ/jOOQ/issues/4474

**Comment by lukaseder** [comment]
Plain SQL templating workarounds also documented in #4474
