### ISSUE TITLE
Annotate SQL templating paramters with @Language("SQL")

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#11533]
### Use case:

I am using jOOQ's SQL templating features in IntelliJ IDEA. IDEA supports [language injection](https://www.jetbrains.com/help/idea/using-language-injections.html) and already has some support for jOOQ. There are however also many SQL templating methods in jOOQ which IDEA is unaware of and doesn't do any syntax highlighting (or code completion) for.

AFAICT the language injection appears to work fine for methods which only declare a `String sql` parameter. For those which in addition also declare a `QueryPart... parts` parameter the syntax highlighting doesn't work. Whilte the SQL isn't 100% correct, due to the placeholders of the templating mechanism, the IDEA SQL parser still does a very good job at recovering and in fact doesn't even show any syntax errors:

![image](https://user-images.githubusercontent.com/408765/109269050-393a6100-780c-11eb-9ac1-c61d137bdf42.png)

### Possible solution you'd like to see:

Since jOOQ now already uses the `org.jetbrains:annotations` library for nullness annotations, it would be nice if jOOQ could also add an `@Language("SQL")` annotation to all `String sql` parameters in question. This way jOOQ can add new SQL templating methods and it will work straight away in IDEA.

### Possible workarounds:

- Report to JetBrains and wait for an update.
- As a user I can add a `/* language=sql */` comment preceding the SQL template (see screenshot above)

### Versions:

- jOOQ: 3.14.6
- Java: 15
- Database (include vendor): PostgreSQL
- OS: Windows 10
- IDEA: 2021.1 EAP (Build #IU-211.6085.26)

**Comment by knutwannheden** [comment]
There are of course also cases when the SQL templating causes parsing errors which do get reported in IDEA (see red squiggly line after `exists` keyword in screenshot):

![image](https://user-images.githubusercontent.com/408765/109272240-e0b99280-7810-11eb-9d9a-068fe4125752.png)

**Comment by lukaseder** [comment]
Thanks for your message.

That sounds like an interesting idea. I'm currently working on an "epic" task of annotating all sorts of `String` accepting API with a new `Stringly.XYZ` annotation to document what a String is in each context (`org.jooq.Name`, `org.jooq.SQL`, `org.jooq.Param`, `org.jooq.Keyword`, `org.jooq.Comment`). For those that are `Stringly.SQL`, we could add the JetBrains annotation.

On the other hand, this omission has been a conscious decision by JetBrains:
https://youtrack.jetbrains.com/issue/IDEA-230412#focus=Comments-27-3895189.0-0

Perhaps you ask them about this, first? Given that this `@Language` annotation has `CLASS` retention, I'm not convinced yet we should add more memory overhead to our library for this convenience. (This is already annoying with the JetBrains `Nullable` and `NotNull` annotations!)

**Comment by knutwannheden** [comment]
> On the other hand, this omission has been a conscious decision by JetBrains:
> https://youtrack.jetbrains.com/issue/IDEA-230412#focus=Comments-27-3895189.0-0

I see. It did look deliberate and I understand the reasoning. Personally I still like the highlighting. I suppose I have to live with my call site comments.

> Given that this `@Language` annotation has `CLASS` retention, I'm not convinced yet we should add more memory overhead to our library for this convenience. (This is already annoying with the JetBrains `Nullable` and `NotNull` annotations!)

Hmm, I thought the purpose of `CLASS` was that it shouldn't add any runtime overhead (from https://docs.oracle.com/javase/7/docs/api/java/lang/annotation/RetentionPolicy.html#CLASS):

> Annotations are to be recorded in the class file by the compiler but need not be retained by the VM at run time. This is the default behavior.

**Comment by lukaseder** [comment]
> I suppose I have to live with my call site comments.

For now, yes. Or, perhaps there's a global setting in IntelliJ, where you can add method signatures?

> Hmm, I thought the purpose of `CLASS` was that it shouldn't add any runtime overhead

This doesn't necessarily translate to "no overhead". The meta data is not contained in the reflection APIs, but it is there in byte code. 

Here's some criticism of the JetBrains choice of making these annotations have `CLASS` retention:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=565463

I don't have much of a stake, but I prefer not to add unnecessary annotations that do not have `SOURCE` retention. Our own annotations generate enough overhead already...

**Comment by knutwannheden** [comment]
> This doesn't necessarily translate to "no overhead". The meta data is not contained in the reflection APIs, but it is there in byte code.

Yes. I was assuming the corresponding data in the byte code would be "discarded" when the class is defined and thus "only" bloat the jar file.

In any case, this issue can probably be closed again, unless you decide to add some `@Language("SQL")` to the methods without actual templating parameters :-)

FYI: I tested to add a `/* language=sql */` comment in front of a method parameter declaration instead of the `@Language("SQL")` annotation. Unfortunately it doesn't work.

**Comment by lukaseder** [comment]
> Yes. I was assuming the corresponding data in the byte code would be "discarded" when the class is defined and thus "only" bloat the jar file.

I'm not sure how it works in detail, and how libraries like ASM make these annotations available...

> In any case, this issue can probably be closed again, unless you decide to add some `@Language("SQL")` to the methods without actual templating parameters :-)

There seems to be no need for that, given that JetBrains already has jOOQ on the radar.
