### ISSUE TITLE
Typo in AbstractDMLQuery

### ISSUE THREAD

**Issue by TheDIM47** [jOOQ/jOOQ#11546]
When I set SQLDialect to MARIADB, I'm getting "SQLException: Can not issue data manipulation statements with executeQuery()" on INSERT ... RETURNING execution.

Need `if (nativeSupportReturning(ctx))` (without "!") here ?
https://github.com/jOOQ/jOOQ/blob/515e2902d15a7cd3cb518b230df3b40913b6de24/jOOQ/src/main/java/org/jooq/impl/AbstractDMLQuery.java#L1019

probably, related to #9212

- jOOQ: 3.14.8
- Database (include vendor): MARIADB 10.3.16-MariaDB-log

**Comment by lukaseder** [comment]
Thanks a lot for your message.

Please use the `SQLDialect.MARIADB_10_3` for continued MariaDB 10.3 support from the jOOQ Professional Edition, or alternatively, if licensing jOOQ is not possible (though we highly recommend it if you plan to stay on older RDBMS versions), consider the database version support matrix:
https://www.jooq.org/download/support-matrix

The latest jOOQ minor release that supported MariaDB 10.3 was jOOQ 3.12. The latest version that did not yet produce this new `RETURNING` clause was 3.13, see https://github.com/jOOQ/jOOQ/issues/9212

See also: https://github.com/jOOQ/jOOQ/issues/10892 and other similar issues.
