### ISSUE TITLE
Can I get returning field from Query object

### ISSUE THREAD

**Issue by zero88** [jOOQ/jOOQ#11554]
### Your question:

Currently, I'm developing a library [vertx-jooq-dsl](https://github.com/zero88/vertx-jooq-dsl) then I'm stuck with  https://github.com/zero88/vertx-jooq-dsl/issues/4.

Does `jOOQ` support to get `returning field` in `Query` then I can make my functionality seamlessly

### Versions:

- jOOQ: Any

**Comment by lukaseder** [comment]
Thanks a lot for your message. Any reason you're not using this extension here, which is quite popular? https://github.com/jklingsporn/vertx-jooq

Regarding your specific question, please use `returningResult()` instead, see https://github.com/jOOQ/jOOQ/issues/7475

**Comment by zero88** [comment]
Hi man, thank you for your answer.
But it doesn't resolve my question. I want to get `returning field name` in `query` before execution, mean in declaration time. Your method is only able to get field name after execution in runtime
Since my lib will use SQL client connection in Vertx to execute query, not jOOQ then I want to retrieve "almost everything" in query definition(I think this is only one remaining) to convert SQL result set from Vertx to jOOQ record.

>  Any reason you're not using this extension here, which is quite popular? https://github.com/jklingsporn/vertx-jooq

I already used it before, but I don't like it because it is not jOOQ. 
This lib is depends heavily on DAO but if like that, I think use Hibernate or any ORM for better. Furthermore, `transaction`, `batch`, `join` and `ad-hoc` query is not easy to extend from this base.

I dont want
>  hiding the beauty and simplicity of relational data
and minimize a scope of jOOQ.

Then I created this library to leverage power between async SQL in Vertx and of course the DSL strength in jOOQ, it is a most powerful database query that I've used. 
Also it will be integrated with my previous lib seamlessly: [rql-jooq](https://github.com/zero88/universal-rsql/blob/master/rql-jooq/src/test/java/io/github/zero88/rql/jooq/JooqRqlQueryTest.java) that makes complete ecosystem to access SQL from REST API service

**Comment by lukaseder** [comment]
> But it doesn't resolve my question. I want to get `returning field name` in `query` before execution, mean in declaration time.

We don't support that in the API, currently. You can extract the field with a `VisitListener` if there's no other way (or using reflection, of course), but I would assume you can remember what fields you put in the clause and store that as a local variable somewhere?

> I already used it before, but I don't like it because it is not jOOQ.
> This lib is depending heavily on DAO but if like that, I think use Hibernate or any ORM for better. Furthermore, `transaction`, `batch`, `join` and `ad-hoc` query is not easy to extend from this base.

I see. Have you considered contributing there? Anyway, it's not important to your question.

**Comment by zero88** [comment]
Ya, thank @lukaseder 
Sorry, I just back to develop my lib today then checkout your message.

> `VisitListener` if there's no other way (or using reflection, of course)

It is overkill for my need.
> but I would assume you can remember what fields you put in the clause and store that as a local variable somewhere?

I want to make easy API for developer to avoid re-declare one in same time for refine query result.
Actually, as latest my API, I provide it is as optional. However, in default mode for generating `Vertx JsonObject`, this minor issue still have due to `jOOQ API` limitation. Anyway, just mark it as known-issues until someday, you resolve it. :))

```java
final InsertResultStep<BooksRecord> insert = executor.dsl()
                                                             .insertInto(table, table.ID, table.TITLE)
                                                             .values(Arrays.asList(DSL.defaultValue(table.ID), "abc"))
                                                             .returning(table.ID);
executor.execute(insert, VertxReactiveDSL.instance().fetchVertxRecord(table), ar -> {});
// OR
executor.execute(insert, VertxReactiveDSL.instance().fetchOne(table, Collections.singletonList(table.ID)), ar -> {});
// OR
executor.execute(insert, VertxReactiveDSL.instance().fetchOne(table, Books.class), ar -> {});
// And some several methods based on Record#into
```

> I see. Have you considered contributing there? Anyway, it's not important to your question.

Ya, I thought about it. because I already developed a dynamic SQL service based on `vertx-jooq` in my work but when I look it again, only one some simple commands like update/delete/create one record that I used DAO. other queries, I used DSL as core but get DSL in `vertx-jooq` context is annoy to me.

That's why I created my lib for making `DSL` as first citizen rather than `DAO`. Coz, I think `DSL` is `jOOQ` DNA, then I follow it.
I'm trying to finish my lib and release soon in this month. Maybe, if you have spare time, hope you can review it to avoid any drawback in case using jOOQ API

**Comment by lukaseder** [comment]
Thanks a lot for the clarifications.

> Anyway, just mark it as known-issues until someday, you resolve it. :))

Yes. I certainly recognise the need. It's just that this has to be resolved globally, not locally just for the `RETURNING` clause, so it's a big strategic project.

> Maybe, if you have spare time, hope you can review it to avoid any drawback in case using jOOQ API

I cannot promise this, but I think that community feedback will be much more valuable to you than mine, anyway.
