### ISSUE TITLE
JOOQ Generator - Despite forcing the type of Integer, I get BigInteger instead

### ISSUE THREAD

**Issue by remo-vonarx** [jOOQ/jOOQ#11555]
### Your question:

Hi there
I am having a Oracle DB with a table DATASET having a field called STATUS, DDL is the following: 	"STATUS" NUMBER(1,0), no PK or any constraints on it. The value of this field can range from 0 to 5, no decimals. The database holds only records with STATUS = 1. It is really just a Status code, nothing more. The JOOQ Generator uses Byte when generating the code, but I would like it to have mapped to Integer instead. 

In my pom.xml, I defined a forced Typing as the following:
```xml
                        <database>
                            <name>org.jooq.meta.oracle.OracleDatabase</name>
                            <includes>.*</includes>
                            <inputSchema>XY</inputSchema>
                            <includeIndexes>false</includeIndexes>
                            <forcedTypes>
                                <forcedType>
                                    <name>BIGINT</name>
                                    <includeExpression>.*_?ID|.*_?FK</includeExpression>
                                </forcedType>
                                <forcedType>
                                    <name>INTEGER</name>
                                    <includeExpression>STATUS</includeExpression>
                                </forcedType>
                            </forcedTypes>
                        </database>
```

With this, I expect the field STATUS being forced to an Integer, instead I get BigInteger. 

`/**
     * The column <code>XY.DATASETS.STATUS</code>.
     */
    public final TableField<DatasetsRecord, BigInteger> STATUS = createField(DSL.name("STATUS"), SQLDataType.DECIMAL_INTEGER, this, "");
`

Did the mapping according to SQLDataType and the documentation. Even https://www.jooq.org/doc/3.14/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-zero-scale-decimals/ didn't help.

Is there an error in the generator? Or do I oversee something here?
Many thanks for any input!

### Versions:

- jOOQ: 3.14
- Java: Adopt Open JDK 11
- Database (include vendor): Oracle Database 19c
- OS: macOS Catalina 10.15.7 (19H2)
- JDBC Driver (include name if inofficial driver): com.oracle.database.jdbc.ojdbc10 19.9.0.0

**Comment by lukaseder** [comment]
Thanks a lot for your report. That's unfortunate but works as "designed". Oracle has a documented `INTEGER` ANSI type alias, which corresponds to `NUMBER(38)`:
https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/Data-Types.html#GUID-0BC16006-32F1-42B1-B45E-F27A494963FF

You can try it like this:

```sql
CREATE TABLE t (i integer);
SELECT data_type, data_precision, data_scale
FROM all_tab_cols
WHERE table_name = 'T';
```

You'll get:

```
|DATA_TYPE|DATA_PRECISION|DATA_SCALE|
|---------|--------------|----------|
|NUMBER   |              |0         |
```

So, the precision is `*` and the scale is `0`. The subtlety can be seen in the documentation:

> Specify any data type that is supported in your database, **or if unsupported**, a type from org.jooq.impl.SQLDataType

So, the vendor specific type names take precedence (just like in the code generator, otherwise) over the standard `SQLDataType` names.

You can work around this limitation by using this, instead:

```xml
<forcedType>
  <name>NUMBER(9)</name>
  <includeExpression>STATUS</includeExpression>
</forcedType>
```
