### ISSUE TITLE
When does JOOQ adds the schema and table names to column?

### ISSUE THREAD

**Issue by sanatik** [jOOQ/jOOQ#11565]
### Your question:
Hey peeps,
I have one very weird case with JOOQ queries on production.
After the rollout of the new version of the application to production, the database queries started failing with
```
threw exception; nested exception is org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [update "public"."balances" set "public"."balances"."current_balance" = ?, "public"."balances"."available_balance" = ?, "public"."balances"."timestamp" = ?, "public"."balances"."last_balance_event" = ?, "public"."balances"."jooq_version" = ? where ("public"."balances"."user_id_balance_type_currency_code_hash" = ? and "public"."balances"."jooq_version" = ?)]; nested exception is org.postgresql.util.PSQLException: ERROR: column "public" of relation "balances" does not exist
```
I want to empathize that **no changes** regarding JOOQ or Database changes have been introduced, the previous version of the application had the same version of JOOQ as well as the DB, all tables were the same.
After rolling back to the previous version of the application, the error was gone.

Digging through the Postgres logs, I found the failed query
```
update "public"."balances" set 
"public"."balances"."current_balance" = $1, "public"."balances"."available_balance" = $2, "public"."balances"."timestamp" = $3, "public"."balances"."last_balance_event" = $4, "public"."balances"."jooq_version" = $5 where ("public"."balances"."user_id_balance_type_currency_code_hash" = $6 and "public"."balances"."jooq_version" = $7)
```
And the query, that did not fail
```
update "public"."balances" set 
"current_balance" = $1, "available_balance" = $2, "timestamp" = cast($3 as timestamp with time zone), "last_balance_event" = cast($4 as jsonb), "jooq_version" = $5 where ("public"."balances"."user_id_balance_type_currency_code_hash" = $6 and "public"."balances"."jooq_version" = $7)
```
The difference is that the schema and table names were used in front of columns and the `timestamp` column being cast.

The JOOQ configuration we have is the following
```
SettingsTools.defaultSettings()
        .withExecuteWithOptimisticLocking(true)
        .withExecuteWithOptimisticLockingExcludeUnversioned(false)
        .withUpdateRecordVersion(true)
        .withUpdateRecordTimestamp(true)
```

Question: **in what cases JOOQ attaches the schema and table names to columns when the query is rendered**? 
I was not able to reproduce the behavior on my local, unfortunately.

Thanks!

PS: even though it looks like a mystery, I am sure there must be a good explanation of this behavior. 

UPD: The query is constructed as the following
```
public BalancesRecord update(final BalancesRecord balance) {
    balance.store();
    return balance;
  }
```

### Versions:

- jOOQ: `3.13.5`
- Java: `11`
- Database (include vendor): `Postgres 11.10`
- OS: `Ubuntu`, running in the Docker container `openjdk:11`
- JDBC Driver (include name if inofficial driver): `org.postgresql.Driver:42.2.18`

**Comment by lukaseder** [comment]
You probably didn't set the correct `SQLDialect`. We don't qualify column names in `UPDATE .. SET` for the PostgreSQL dialect, but we do it for some others, including `SQLDialect.DEFAULT`. The stack trace should give you a hint what dialect was being used as there's a synthetic stack trace element indicating dialect and jOOQ version in all jOOQ stack traces.
