### ISSUE TITLE
Include a way to control the Liquibase log level from jooq generator

### ISSUE THREAD

**Issue by ascertrobw** [jOOQ/jOOQ#11569]
### Use case:

Possibly I'm missing this, but I can't see a way to change the Liquibase log level when used as the jooq generator model. It seems permanently stuck in the verbose DEBUG mode.

### Possible solution you'd like to see:

Couple of options seem possible:

- Use the jooq generator logging level to also set Liquibase to the same logging. Would be seamless, but then prevent separate control
- Extend the changeLogParameters set to include logLevel as well as contexts.

### Possible workarounds:

n/a

### Versions:

- jOOQ: 3.14
- Database (include vendor): Liquibase generator

**Comment by lukaseder** [comment]
Thanks for your suggestion.

Do you think there's anything that should be done on our side, really? It seems that Liquibase is using `java.util.logging`, so perhaps, the usual JUL mechanisms work out of the box? Regarding your specific suggestions:

> Use the jooq generator logging level to also set Liquibase to the same logging. Would be seamless, but then prevent separate control

Might be possible. Liquibase seems to offer a single `logLevel` property in their properties file, see e.g.
https://github.com/liquibase/liquibase/blob/ec4c46df04ee03792adb9d8e786869ae7e85ad2f/liquibase-dist/src/main/archive/examples/sql/liquibase.properties

But how to set that programmatically? There doesn't seem to be any API, though reverse engineering their code:
https://github.com/liquibase/liquibase/blob/ec4c46df04ee03792adb9d8e786869ae7e85ad2f/liquibase-core/src/main/java/liquibase/integration/commandline/Main.java

it seems to be sufficient to just set the log level for:

```
java.util.logging.Logger.getLogger("liquibase")
```

But I don't really like the idea of forcing our level onto theirs. I like the fact that these things can be controlled individually and externally.

> Extend the changeLogParameters set to include logLevel as well as contexts.

`changeLogParameters` is an actual Liquibase object `liquibase.changelog.ChangeLogParameters`. It has nothing to do with console logging.

Before we move on, can you try to set the JUL log level?

**Comment by ascertrobw** [comment]
> Before we move on, can you try to set the JUL log level?

Will try this now - handn't thought of that!

**Comment by ascertrobw** [comment]
I'm sure this is me being dense - but I can't seem to find a way to pass a JUL config down from Gradle through to jooq generator and Liquibase to achieve this. Have tried a few approaches, from the usual -Djava.util.logging.config.file=<file> on the gradle command line, down to hijacking the JavaExec task for generateJooq and trying to force set the JUL config file there. So far not luck getting Liquibase to take notice of it.

Just for info, there's a couple of pre-amble lines, that suggest one of the jooq tool classes may also not following the jooq gen log level. The majority we're seeing are Liquibase ones though (they end up as about 4,000 lines of DEBUG log in our CI build, for a relatively small schema) 

```
> Task :proj:ds:sql:generateJooq
14:25:50.715 [main] DEBUG org.jooq.tools.Convert - Jackson not available    : com.fasterxml.jackson.databind.ObjectMapper
14:25:50.717 [main] DEBUG org.jooq.tools.Convert - Gson not available       : com.google.gson.Gson
14:25:50.847 [main] DEBUG org.jooq.tools.Convert - JAXB is available        
14:25:51.271 [main] DEBUG liquibase.resource.ClassLoaderResourceAccessor - Opening jar:file:/C:/Users/robw/.gradle/caches/modules-2/files-2.1/org.jooq/jooq-codegen/3.14.7/982bafbd5edf574bed4aab98ca7176c7e84d729/jooq-codegen-3.14.7.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
14:25:51.272 [main] DEBUG liquibase.resource.ClassLoaderResourceAccessor - Opening 


```

**Comment by lukaseder** [comment]
> Just for info, there's a couple of pre-amble lines

Those are from jOOQ not the jOOQ code generator. I wonder how those got in first. We set the global threshold for jOOQ's logging via https://github.com/jOOQ/jOOQ/issues/10463

Would you mind reporting a new issue for that, with a reproducer, if you'd like me to look at it?

In any case, since I'm not much acquainted with Gradle, how does it handle logging in general? There must be a "gradle way" to do this. In Maven, you'd be passing `-Dorg.slf4j.simpleLogger` args to the `mvn` command.

Also, there must be a way to get Liquibase to log correctly, e.g. look at this question that gets it to log using slf4j: https://stackoverflow.com/q/20880783/521799

On the jOOQ side, we can't do much, unless there's a programmatic API to set the level like we're offering in jOOQ, but I haven't found one, so far.

**Comment by ascertrobw** [comment]
Cool - thx. Will dig further next week when I get a chance and report back/update here.

**Comment by ascertrobw** [comment]
Managed to get this working - seems like Logback is now the way to go for Liquibase logging control.

Don't know if there is a KB or somewhere this kind of thing is recorded, so I'll add the steps here. Feel free to include in the jOOQ Liquibase/Gradle notes if of use.

The gradle.build file needs to inject the logging config as a system property e.g.

```
tasks.named('generateJooq').configure {
    // Logback file is needed to allow control of Liquibase logging level
    javaExecSpec = { JavaExecSpec s ->
        s.systemProperties = [
                "logback.configurationFile": "logback.xml"
        ]    
 
        // Just to show logback config file was set
        println s.systemProperties
    }
}

The logback.xml file then supplies the required logging level e.g.

```

<configuration>

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
    </appender>

    
    
    <root level="error">
        <appender-ref ref="STDOUT"/>
    </root>

</configuration>
```

With these in place I no longer see the stray jOOQ log messages (#10463) either.

So I think we're all good here.

**Comment by lukaseder** [comment]
Thanks a lot. I'm sure this will be useful for others

**Comment by MisteliEvooq** [comment]
Ok maybe I'm just an idiot but it actually took me a while to figure out how to get this running using the Gradle Kotlin DSL, so I thought I'd share:
```
tasks.named<nu.studer.gradle.jooq.JooqGenerate>("generateJooq").configure {
    setJavaExecSpec {
        systemProperty("logback.configurationFile", "gradle/logback.xml")
    }
}
```
_NOTE: I put the logback config file in the gradle folder instead of `src/main/resources`, so it's separate from whatever log config I have for the runtime._

Used Versions:
Gradle: 8.5
Jooq: 3.15.12
Liquibase: 3.8.8
H2: 1.4.200
