### ISSUE TITLE
DB2_10 and Boolean Types are notcompatible

### ISSUE THREAD

**Issue by marco135** [jOOQ/jOOQ#11570]
### Expected behavior
`DSL.trueCondition()` generates `1 = 1` and `DSL.falseCondition()` generates `1 = 0` with `SQLDialect.DB2_10`
### Actual behavior
`DSL.trueCondition()` generates `true` and `DSL.falseCondition()` generates `false` with `SQLDialect.DB2_10`
SQL-Exception: 
`An unexpected token "LIMIT" was found following "OLUMNS" c WHERE true".  Expected tokens may include:  "<interval_qualifier>".. SQLCODE=-104, SQLSTATE=42601`
### Steps to reproduce the problem
In out local development environment, we use an old DB2. 
It seems, that this version do not supports BOOLEAN-Types.
This Query is not executable:
`SELECT * FROM "SYSIBM"."COLUMNS" c WHERE TRUE LIMIT 5`.

### Versions

- jOOQ: 3.14.7
- Java: 8
- Database (include vendor): IBM DB2 v10.5.0.7
- OS: -
- JDBC Driver (include name if inofficial driver): -

**Comment by lukaseder** [comment]
Thanks a lot for your report. How can this be reproduced? Running this code:

```java
System.out.println(DSL.using(SQLDialect.DB2_10).render(trueCondition()));
System.out.println(DSL.using(SQLDialect.DB2_10).render(selectOne().where(trueCondition())));
```

Prints the expected output:

```sql
1 = 1
select 1 "one" from SYSIBM.DUAL where 1 = 1
```

**Comment by marco135** [comment]
Sorry, you're right. It's not a bug. We had a place in the code where the config was not set correctly. So sorry for the confusion.

**Comment by lukaseder** [comment]
No worries! I'm glad that you could find the source of the problem
