### ISSUE TITLE
fetchParent() doesn't work properly with foreign key referencing just a part from a composed primary key

### ISSUE THREAD

**Issue by AnghelLeonard** [jOOQ/jOOQ#11580]
### Expected behavior
A correct query.

### Actual behavior
An error of type: `Operand should contain 2 column(s)`.

### Steps to reproduce the problem

I was trying `fetchParent()` in this scenario.

Table `PRODUCTLINE` has a composed primary key as `('productline', 'code')`. Its child, the `PRODUCT` table has a foreign key that contains only `'productline'`, so not `'code'`. jOOQ generates a foreign key in `Keys` as:

```Java
public static final ForeignKey<ProductRecord, ProductlineRecord> PRODUCTS_IBFK_1 =
  Internal.createForeignKey(Product.PRODUCT, DSL.name("products_ibfk_1"), new TableField[] {
  Product.PRODUCT.PRODUCT_LINE }, Keys.KEY_PRODUCTLINE_PRIMARY, new TableField[] {
  Productline.PRODUCTLINE.PRODUCT_LINE }, true);
```

While this looks good, if I have a `ProductRecord (pr)` and call this:

```Java
pr.fetchParent(Keys.PRODUCTS_IBFK_1);
```

In MySQL, I get this generated SQL:

```sql
select 
  `classicmodels`.`productline`.`product_line`, 
  `classicmodels`.`productline`.`code`, 
  `classicmodels`.`productline`.`text_description`, 
  `classicmodels`.`productline`.`html_description`, 
  `classicmodels`.`productline`.`image`, 
  `classicmodels`.`productline`.`created_on` 
from 
  `classicmodels`.`productline` 
where 
  (
    `classicmodels`.`productline`.`product_line`, 
    `classicmodels`.`productline`.`code`
  ) in (
    (?)
  )
```

So, in `WHERE` there are the primary key fields of `PRODUCTLINE`, not just `'prouductline'`. In addition, there is only one `?` placeholder, so I get `Operand should contain 2 column(s)`.

### Versions

- jOOQ:3.14.8
- Java:14
- Database (include vendor):MySQL
- OS:-
- JDBC Driver (include name if inofficial driver):-

**Comment by lukaseder** [comment]
Thanks for your report. That's curious, can you post the `CREATE TABLE` of the two tables involved here, including all constraint definitions? It looks like you defined your tables like this (simplified):

```sql
create table t (i int, j int, primary key (i, j));
create table u (i int references t);
```

I'm surprised this works on MySQL. What does it even mean? `t(i)` is not unique, so how can a foreign key reference `t(i)`? Nevertheless, if MySQL users decide to design their schema this way (I highly recommend not to), we can still try to forge "correct-ish" queries. The intention here is obviously to join using only the matching parts of the column lists...

I think I've seen this before, but cannot seem to find the releavant issue. A related issue is this: https://github.com/jOOQ/jOOQ/issues/8553.

**Comment by lukaseder** [comment]
So, the "workaround" should be to do any of these:

```sql
-- Add a unique key on i
create table t (i int, j int, primary key (i, j), unique (i));
create table u (i int references t (i));

-- Switch unique and primary keys
create table t (i int, j int, unique (i, j), primary key (i));
create table u (i int references t);

-- Correctly normalise by referencing code as well
create table t (i int, j int, primary key (i, j));
create table u (i int, j int foreign key (i, j) references t);
```

**Comment by lukaseder** [comment]
Hah, nice. While investigating this, I discovered a "bug":
https://bugs.mysql.com/bug.php?id=102904&thanks=4

MySQL doesn't actually implement the inline `references` clause, only explicit foreign key specifications 😁

**Comment by lukaseder** [comment]
There might be other things failing in such a schema. I'll have to check. Candidates:

- `onKey()`
- implicit joins

**Comment by AnghelLeonard** [comment]
The tables that I used are like this:

```sql
CREATE TABLE `product` (
  `product_id` bigint NOT NULL AUTO_INCREMENT,
  `product_name` varchar(70) DEFAULT NULL,
  ...
PRIMARY KEY (`product_id`),
CONSTRAINT `products_ibfk_1` FOREIGN KEY (`product_line`) 
                                                   REFERENCES `productline` (`product_line`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

And:

```sql
CREATE TABLE `productline` (
  `product_line` varchar(50) NOT NULL,
  `code` bigint NOT NULL,  
  ...
PRIMARY KEY (`product_line`,`code`),
  CONSTRAINT unique_product_line UNIQUE(product_line)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

**Comment by lukaseder** [comment]
Thanks for the clarification. So indeed, the same as my simplified example. What's the rationale of omitting parts of the primary key in the `products_ibfk_1` key?

**Comment by AnghelLeonard** [comment]
Is like in your "-- Add a unique key on i". Notice, "CONSTRAINT unique_product_line UNIQUE(product_line)". But, I guess it works without that as well. The rationale in my case was to test such cases :)

I read in MySQL doc something like this (http://mysql.babo.ist/#/en/innodb-foreign-key-constraints.html):
"InnoDB allows a foreign key constraint to reference a non-unique key. This is an InnoDB extension to standard SQL."

Whether this design makes sense or not depends is something that probably depends on the underlying business rules. I don't know a useful example.

**Comment by lukaseder** [comment]
> The rationale in my case was to test such cases :)

Usually, I'm the one to break things others made 😁 Excellent find, anyway, thanks again!

> This is an InnoDB extension to standard SQL

I call that a bug 🤷‍♂️

> I don't know a useful example.

OK, I see. It doesn't really matter in the context of this bug, though. If it's possible for users to create such schemas, then they will, and jOOQ obviously mustn't produce syntax errors like the one you reported.

**Comment by lukaseder** [comment]
It looks like `onKey()` and implicit joins work well in MySQL for such tables. However, it seems that at least in H2, we're not generating the correct code in this case: https://github.com/jOOQ/jOOQ/issues/11609
