### ISSUE TITLE
No ForeignKey information generated in H2 when FK has less columns than the referenced PK

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11609]
Related to this MySQL issue: #11580.

H2 also supports foreign keys referencing only parts of a primary key:

```sql
create table t (i int, j int, constraint pk_t primary key (i, j));
create table u (i int, constraint fk_u foreign key (i) references t (i));
```

It seems we're currently not generating any foreign key information, meaning that things like `fetchParent()`, `onKey()`, or implicit joins don't work.

**Comment by lukaseder** [comment]
The problem is that our query to find foreign keys in `CROSS_REFERENCES` joins that table directly to `CONSTRAINTS`, not via `INDEXES`, see also: https://github.com/h2database/h2database/issues/466. Let's see if an additional join will help here

**Comment by lukaseder** [comment]
I can't seem to wrap my head around the messy `CROSS_REFERENCES` semantics. I think this would need to be fixed in H2 first, before I do any further work in this area.

**Comment by katzyn** [comment]
H2 actually can't reference a key with different set of columns. But H2 is able to create a new one automatically.

H2 1.4.* and older versions create only a unique index on the referenced columns. Not yet released due to unresolved regressions H2 2.0 creates a unique constraint instead and provides information about it as expected.

**Comment by katzyn** [comment]
The subset of unique columns is not guaranteed to be unique, so hypothetically every DBMS need an additional unique constraint or index on them.

**Comment by lukaseder** [comment]
> H2 2.0 creates a unique constraint instead and provides information about it as expected.

Oh, that will be great, thanks for the heads-up! Though, I wonder about the motivation of doing this automatically. I think a fail-fast approach would be better, unless you explicitly want to mimick MySQL behaviour?

> The subset of unique columns is not guaranteed to be unique, so hypothetically every DBMS need an additional unique constraint or index on them.

Well, my expectation would be for column set mismatches to produce failures, because the most likely reason for such declarations is a bug / schema design flaw...

**Comment by katzyn** [comment]
> I wonder about the motivation of doing this automatically

Some limited backward compatibility. Unfortunately, this weird feature of H2 was used in various projects.

Actually this is strongly needed only during import from H2 1.4. With new databases such referential constraints may be rejected, unless MySQL compatibility mode is enabled.

**Comment by katzyn** [comment]
BTW, MariaDB rejects this. Maybe it's about a time to add a separate compatibility mode for MariaDB to H2.

**Comment by lukaseder** [comment]
> BTW, MariaDB rejects this. Maybe it's about a time to add a separate compatibility mode for MariaDB to H2.

Yeah, MariaDB and MySQL have diverged quite a bit in various areas...

**Comment by katzyn** [comment]
H2 2.0 will not accept creation of referential constraint without a primary key or unique index on the referenced columns with exactly the same set of columns in any order, unless MySQL compatibility mode is enabled or a quirks mode (not related to compatibility modes) is enabled. If either of them is enabled, H2 will create a unique constraint (not the index) on them.

All information is available in standard-compliant `INFORMATION_SCHEMA.TABLE_CONSTRAINTS`, `INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS`, and `INFORMATION_SCHEMA.KEY_COLUMN_USAGE`.

**Comment by lukaseder** [comment]
Perfect, thanks again for the heads up!

**Comment by lukaseder** [comment]
As mentioned by @katzyn, the input schema is now rejected by H2 2.0.202, so there's no need to address this issue.
