### ISSUE TITLE
In MySQL, withReturnAllOnUpdatableRecord(true) causes two SELECT statements

### ISSUE THREAD

**Issue by AnghelLeonard** [jOOQ/jOOQ#11620]
### Expected behavior
One `SELECT` statement.

### Actual behavior
Two `SELECT` statements.

### Steps to reproduce the problem
I tried this code (MySQL):

```Java
TokenRecord tr = new TokenRecord();
tr.setSaleId(1L);
tr.setAmount(340.43);
        
DSLContext derivedCtx = ctx.configuration().derive(new Settings()
                .withReturnAllOnUpdatableRecord(true)).dsl();
derivedCtx.attach(tr);

tr.insert();
```

Besides the expected `INSERT` I got 2 `SELECT`s as follows:

```sql
select 
  `classicmodels`.`token`.`token_id`, 
  `classicmodels`.`token`.`sale_id`, 
  `classicmodels`.`token`.`amount`, 
  `classicmodels`.`token`.`created_on` 
from 
  `classicmodels`.`token` 
where 
  `classicmodels`.`token`.`token_id` in (10)
```

```sql
select 
  `classicmodels`.`token`.`token_id`, 
  `classicmodels`.`token`.`sale_id`, 
  `classicmodels`.`token`.`amount`, 
  `classicmodels`.`token`.`created_on` 
from 
  `classicmodels`.`token` 
where 
  `classicmodels`.`token`.`token_id` = 10
```

### Versions

- jOOQ: 3.14.8
- Java:14
- Database (include vendor):MySQL
- OS:-
- JDBC Driver (include name if inofficial driver):-

**Comment by lukaseder** [comment]
Thanks a lot for your report.

The first query is generated by the internal `INSERT .. RETURNING` statement, the second one by an `UpdatableRecord.refresh()` call, which obviously isn't necessary anymore, in this case.

**Comment by lukaseder** [comment]
Looking into this now. The problem appears only with tables that have an identity column. If the table has an non-identity primary key (e.g. a natural key, or a client generated UUID), then the first `SELECT` from the `RETURNING` statement isn't generated, only the second one from the `REFRESH` statement.

**Comment by lukaseder** [comment]
This also affects:

- Derby
- H2
- MariaDB
- MemSQL
- MySQL
- SQL Server

Specifically H2 (with `FINAL TABLE`) and SQL Server (with `OUTPUT`) can fetch the generated keys in a single query, so not even 1  `SELECT` is required

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0, 3.17.6 (https://github.com/jOOQ/jOOQ/issues/14304), and 3.16.12 (https://github.com/jOOQ/jOOQ/issues/14305)

**Comment by lukaseder** [comment]
Related: https://github.com/jOOQ/jOOQ/issues/14328

**Comment by lukaseder** [comment]
HANA is also affected:

- https://github.com/jOOQ/jOOQ/issues/16651
