### ISSUE TITLE
GeneratorStrategy references package-private AbstractGenerator.Language class

### ISSUE THREAD

**Issue by jklingsporn** [jOOQ/jOOQ#11625]
### Expected behavior
I should be able to implement the `GeneratorStrategy` either fully or by extending `AbstractGeneratorStrategy`. 

### Actual behavior
The resulting class won't compile due to reference to package private `AbstractGenerator.Language` in `GeneratorStrategy#getLanguage`. This must have been changed somewhere between 3.13.6 and 3.14.8.

### Versions

- jOOQ: 3.14.8
- Java: 8

**Comment by lukaseder** [comment]
Oh wow, yes that is quite the API design flaw! As a workaround, you can extend `DefaultGeneratorStrategy`.

**Comment by lukaseder** [comment]
I'm surprised (again) that javac compiles this. It shouldn't be possible to leak internal types in public APIs...

**Comment by lukaseder** [comment]
Fixed this for jOOQ 3.15.0 by moving `org.jooq.codegen.AbstractGenerator.Language` to `org.jooq.codegen.Language` and making it public. Thanks again for your report!
