### ISSUE TITLE
PostgresDatabase doesn't produce CHAR type length for CHAR(n)[] array types

### ISSUE THREAD

**Issue by stellingsimon** [jOOQ/jOOQ#11658]
### Expected behavior

Given this PostgreSQL schema:

```sql
DROP SCHEMA IF EXISTS "MCVE" CASCADE;
CREATE SCHEMA "MCVE";
CREATE TABLE "MCVE"."TEST"
(
    "ID"    INT PRIMARY KEY,
    "VALUE" char(2)[] check (array_to_string("VALUE", ',', '*') != 'A ' )
);
```

and this INSERT-Statement:
```kotlin
        ctx.settings().withStatementType(StatementType.PREPARED_STATEMENT)
        ctx.truncate(TEST).execute()
        ctx
                .insertInto(TEST)
                .columns(TEST.ID, TEST.VALUE)
                .values(1, arrayOf("AB")) // rejected by check constraint, because we'd write "A "!
                .execute()
```

I expect the statement to succeed, with a row `(1, {AB})`  in the DB.

### Actual behavior

Instead, the check constraint fails as `A ` is apparently placed in the `VALUE` column:

```
org.jooq.exception.DataAccessException: SQL [insert into "MCVE"."TEST" ("ID", "VALUE") values (?, ?::char[])]; ERROR: new row for relation "TEST" violates check constraint "TEST_VALUE_check"
  Detail: Failing row contains (2, {"A "}).
	at org.jooq_3.14.8.POSTGRES.debug(Unknown Source) ~[?:?]
	at org.jooq.impl.Tools.translate(Tools.java:2903) ~[jooq-3.14.8.jar:?]
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757) ~[jooq-3.14.8.jar:?]
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:389) [jooq-3.14.8.jar:?]
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:119) [jooq-3.14.8.jar:?]
	at org.jooq.mcve.test.kotlin.KotlinTest.mcveTestFailing(KotlinTest.kt:29) [test-classes/:?]
```

### Steps to reproduce the problem

Here's an [executable MVCE](https://github.com/stellingsimon/mvce-jooq-issue-11658). **Important:** You'll need to execute the flyway script manually on a Postgres instance before running the **KotlinTest**.
Note that the same statement works fine if we use `StatementType.STATIC_STATEMENT`, as demonstrated in the MVCE.

### Versions

- jOOQ: 3.14.8
- Java: as in MVCE
- Database (include vendor): Postgres 13.5
- OS: Linux
- JDBC Driver (include name if inofficial driver):  42.2.19

**Comment by stellingsimon** [comment]
In case it helps to narrow down the source of the error:

I can reproduce this bug with jOOQ 3.14.8 and 3.14.0, but not jOOQ 3.12.4 and 3.13.4 or 3.13.5.

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll investigate this shortly. I think the cast looks wrong, as can be verified easily:

```sql
select 
  array['AB']::char[],
  array['AB']::char(2)[]
```

Resulting in:

```
|array|array|
|-----|-----|
|{A}  |{AB} |
```

**Comment by lukaseder** [comment]
This test works in both 3.15.0-SNAPSHOT and 3.14.9-SNAPSHOT:

```java
public void testArrayStringLength() throws Exception {
    assumeSupportsArrayLiterals();

    DataType<String[]> vc2 = VARCHAR(2).getArrayDataType();
    DataType<String[]> c2 = CHAR(2).getArrayDataType();

    bindAndInline(ctx -> {
        String[] a1 = null;
        String[] a2 = {};
        String[] a3 = { "ab" };
        String[] a4 = { "ab", "cd" };

        Record4<String[],String[],String[],String[]> r1 =
            ctx.fetchOne(select(val(a1, vc2).as("a"), val(a2, vc2).as("b"), val(a3, vc2).as("c"), val(a4, vc2).as("d")));

        Record4<String[],String[],String[],String[]> r2 =
            ctx.fetchOne(select(val(a1, c2).as("a"), val(a2, c2).as("b"), val(a3, c2).as("c"), val(a4, c2).as("d")));

        assertArrayEquals(a1, r1.value1());
        assertArrayEquals(a2, r1.value2());
        assertArrayEquals(a3, r1.value3());
        assertArrayEquals(a4, r1.value4());
        assertArrayEquals(a1, r2.value1());
        assertArrayEquals(a2, r2.value2());
        assertArrayEquals(a3, r2.value3());
        assertArrayEquals(a4, r2.value4());
    });
}
```

Will now try with your MCVE

**Comment by lukaseder** [comment]
OK, but that doesn't help, because that's not what seems to be generated. The `KotlinGenerator` produces this:

```kotlin
val VALUE: TableField<TestRecord, Array<String?>?> = createField(DSL.name("VALUE"), SQLDataType.CHAR.getArrayDataType(), this, "")
```

So, the `CHAR` length is not there.

**Comment by lukaseder** [comment]
The code generation integration tests (which use HSQLDB for array tests) show that this isn't a problem of the `KotlinGenerator`. Looking into the jOOQ-meta `PostgresDatabase` now

**Comment by lukaseder** [comment]
Same issue as https://github.com/jOOQ/jOOQ/issues/8067, which got fixed for `VARCHAR` only, not for `CHAR` or `BPCHAR` (see https://stackoverflow.com/a/51421513/521799)

**Comment by lukaseder** [comment]
This may have worked in earlier releases by accident (?), e.g. because the cast was done with `varchar[]` or `text[]`, or because no cast was done at all? Anyway. This will be an easy fix for 3.15.0 and 3.14.9

**Comment by lukaseder** [comment]
Fixed for 3.15.0 and 3.14.9 (#11676)

**Comment by lukaseder** [comment]
The MCVE tests now pass with 3.14.9-SNAPSHOT. Thanks again for your report!

**Comment by stellingsimon** [comment]
Well, thanks again for the super fast fix. Sorry I sent you on the wrong track with the non-generated model. I didn't find a way to have the generator in the MVCE target an external DB, so I manually rebuilt the relevant portion of the model.

**Comment by lukaseder** [comment]
Yeah, no worries. It did look like a code gen issue at first.

> I didn't find a way to have the generator in the MVCE target an external DB

A great reminder to finally implement https://github.com/jOOQ/jOOQ/issues/6551 ! 😁

**Comment by lukaseder** [comment]
Same problem with `timestamp(p)[]` types: https://github.com/jOOQ/jOOQ/issues/13919
