### ISSUE TITLE
Provide a way to disallow transactions on JOOQ

### ISSUE THREAD

**Issue by gamliela** [jOOQ/jOOQ#11686]
### Use case:

Sometimes, when working with legacy applications, the code is already running in the context of a transaction.

In this case, we would like this code to fail with an error:
```java
record = ...
configuration = new DefaultConfiguration().set((TransactionProvider) null)
// or:
// configuration = new DefaultConfiguration().set(new NoTransactionProvider())

using(configuration)
   .transaction(configuration -> {
      insert(record);
   }
);
```

As far as I understand, there is no way to tell JOOQ to disallow opening a new transaction.
In the example above, JOOQ will create a new `DefaultTransactionProvider`.

### Possible solution you'd like to see:

When the user explicitly set the configuration with `NoTransactionProvider`, it should be respected and not be replaced with `DefaultTransactionProvider`.

### Possible workarounds:

Clone the `NoTransactionProvider` class, and pass an instance to the configuration object.

### Versions:

- jOOQ: 3.13
- Database: Postgres, but probably all

**Comment by lukaseder** [comment]
Looks like something that can be achieved by using a `TransactionListener`:

```java
new DefaultConfiguration(new DefaultTransactionListener() { 
    @Override
    public void beginStart(TransactionContext ctx) {
        throw new MyException();
    }
});
```
