### ISSUE TITLE
Support parsing "! =" and "< >" and other operators containing white space in Oracle

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11695]
Apparently, this is valid SQL in Oracle:

```sql
select * from dual where 4! = 24;
```

But it's not the factorial operator 😉, it's just an excess whitespace between `!` and `=`. It seems that a lot of white space in Oracle is optional. I won't fix all of them, but this one might be relatively easy to fix.

**Comment by wal1dcha1b** [comment]
I encountered that problem a lot. I had to delete the whitespaces with a regex

**Comment by lukaseder** [comment]
THanks for the ping. I forgot to close this. It's already fixed and pushed to 3.15.0-SNAPSHOT
