### ISSUE TITLE
Support floating point NaN and (-)Infinity values in other dialects

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11704]
We've recently fixed support for `NaN` and `Infinity` / `-Infinity` floating point values in PostgreSQL (#5249, #6252). Let's fix this for others as well, if supported:

- [x] BigQuery: Like PostgreSQL https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions
- [x] CockroachDB: like PostgreSQL
- [x] Firebird: `log(1, 1)`, `log(1, 0.5)`, `log(1, 1.5)`: https://firebirdsql.org/refdocs/langrefupd25-intfunc-log.html (only for doubles, not real. Let's see if it's possible for `REAL`: https://stackoverflow.com/q/66763171/521799)
- [x] H2: `sqrt(-1)`, `power(0, -1)`, `-power(0, -1)`
- [x] HSQLDB: `sqrt(-1)`, `1.0e0/0.0e0`, `-1.0e0/0.0e0`: https://stackoverflow.com/a/5141822/521799 (we'll assume users specify `SET DATABASE SQL DOUBLE NAN FALSE`)
- [x] Redshift: Like PostgreSQL
- [x] Vertica: Like PostgreSQL

More dialects in a future release: 

- #11706

Also:

- [x] Make sure the various syntaxes are understood by the parser

Seemingly unsupported:

- Derby
- Exasol (`NaN` and `NULL` are the same thing, which isn't correct. Infinity isn't supported, see https://docs.exasol.com/sql_references/data_types/datatypedetails.htm)
- HANA
- Ignite (?)
- MariaDB
- MySQL
- SQLite
- SQL Server

This hasn't been reported yet by users, so let's not backport the fix.

**Comment by katzyn** [comment]
For H2 `CAST('NaN' AS dataType)`, `CAST('Infinity' AS dataType)`, and `CAST('-Infinity' AS dataType)` should normally be used, where `dataType` is `REAL`, `DOUBLE PRECISION`, or `DECFLOAT` (`DECFLOAT` is supported by not yet released H2 2.0 only).

These obscure functions suggested by documentation of 1.4.200 and sometimes printed by H2 1.X in the generated SQL aren't a good practice.

**Comment by lukaseder** [comment]
Thanks a lot for your hint, as always, @katzyn. Indeed, I went by the documentation :) I found those hacks quite cunning. Almost as cunning as Firebird's hacks 😁 https://firebirdsql.org/refdocs/langrefupd25-intfunc-log.html

Will use the approach you suggested, which is the same as in PostgreSQL and many others. I suppose the documentation will be updated?

**Comment by katzyn** [comment]
Documentation template on GitHub was updated after release of 1.4.200 together with fixes for generated SQL, so the documentation for the next release will suggest these constants too. H2 was always able to parse them.
