### ISSUE TITLE
Add support for TO_DATE() in SQL Server

### ISSUE THREAD

**Issue by ISSTJ** [jOOQ/jOOQ#11719]
Transforming ORACLE to_date to SQL Server CONVERT does not work:

- INPUT: select to_date('01.01.2021', 'DD.MM.YYYY') FROM DUAL;
  Style: ORACLE
  
- OUTPUT: select to_date('01.01.2021', 'DD.MM.YYYY')
   Style: SQL Server 

FIX: use CONVERT instead of to_date

**Comment by lukaseder** [comment]
Thanks a lot for your suggestion.

We correctly parse `TO_DATE()`, but don't translate it yet to other dialects that don't support Oracle's syntax. We could, of course, especially when the format string is a string literal (as opposed to a dynamic expression). We're already doing the inverse, going from T-SQL `CONVERT` to Oracle `TO_DATE`.

As a workaround, in the upcoming jOOQ 3.15, you will be able to use the `ParseListener` SPI to implement such custom function support: https://www.jooq.org/doc/dev/manual/sql-building/sql-parser/sql-parser-listener/

**Comment by lukaseder** [comment]
Implemented for jOOQ 3.15.0.
