### ISSUE TITLE
Using embedded domains with POJO generation results in duplicate getters 

### ISSUE THREAD

**Issue by AnghelLeonard** [jOOQ/jOOQ#11716]
### Expected behavior
Working generated code for embedded domains and POJOs.

### Actual behavior
Generated code with errors.

### Steps to reproduce the problem

I tried to do the following (in PostgreSQL):
   
```sql
CREATE DOMAIN postal_code AS varchar(15)
CHECK(
        VALUE ~ '^\d{5}$'
        OR VALUE ~ '^[A-Z]{2}[0-9]{3}[A-Z]{2}$'
); 
```

And, the DDL of the table:

```sql
CREATE TABLE office (
  ...
  postal_code postal_code NOT NULL,
);
```

As long as I don't generate POJOs (`<pojos>false</pojos>`) everything is ok. But, if I generate POJOs then I get two  `getPostalCode()` methods in the same POJO (`Office.java`) as here:

```java
public PostalCode getPostalCode() {
        return new PostalCode(
              getPostalCode()
        );
}

@Size(max = 15)
    public String getPostalCode() {
        return this.postalCode;
}
```

Obviously, this leads to an error. I also tried to use different names for the column and domain but the same thing happens.

### Versions

- jOOQ:3.14.8
- Java:14
- Database (include vendor):PostgreSQL
- OS:-
- JDBC Driver (include name if inofficial driver):-

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can reproduce this. Our integration tests didn't enable the `<pojos>` flag yet for embeddable domains

**Comment by lukaseder** [comment]
Looking into this now. I didn't realise this was affecting all POJOs, not just the ones where the column name conflicts with the domain name!

**Comment by lukaseder** [comment]
The fix will simply omit the getter for the embeddable value. The generation of embeddable returning/accepting getters/setters has been implemented with:

- #8353

But there are still too many problems like this one here, so for now, getting code to compile is the first priority. The second priority is to replace fields by their embeddables also in generated POJOs, interfaces, DAOs, etc.

- #17165

**Comment by lukaseder** [comment]
I'll fix a few other, related issues, including issues that are specific to the `KotlinGenerator` or `ScalaGenerator`.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17166)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17167)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17168)
