### ISSUE TITLE
Exceptions for unique constraint, foreign key, etc...

### ISSUE THREAD

**Issue by 0248991** [jOOQ/jOOQ#11724]
### Use case:

Catch and handle the most common database exceptions.
These can be used in e.g. @ControllerAdvice to return different HTTP responses.

### Possible solution you'd like to see:

Add exceptions for the most common database errors, like a unique constraint and foreign key,...

### Possible workarounds:

Handle errors manually via DataAccessException. This includes ugly stuff like checking SQL state or full-text error codes,...
Eventually, run as stored procedure and handle exceptions inside it manually.

### Versions:

- jOOQ: latest
- Java: 11
- Database (include vendor): any, but I use Postgres 12
- OS: windows 10
- JDBC Driver (include name if inofficial driver): any, but I use Postgres

**Comment by lukaseder** [comment]
Thanks a lot for your feature request. We might add more exception subtypes in the future, though this hasn't been a feature request in many years.

For the time being, if you're using Spring, you can use their `org.springframework.jdbc.support.SQLStateSQLExceptionTranslator`. With Spring Boot, that should be automatically configured. Even without using Spring, that particular translator class can be wired to jOOQ using a custom `ExecuteListener` easily.

**Comment by 0248991** [comment]
Thank you, this seems to be the thing, but what is the minimal implementation?
When you say that SQLStateSQLExceptionTranslator is already registered in Spring Boot, how can I actually handle the specific codes and other useful stuff, like column and table names,...?

Also, is there some clean way to easily handle and convert such errors to user-friendly messages (e.g for frontend)?

Maybe JOOQ could include some default `@ExceptionHandler` for `DataAccessException` which would send HTTP 400 and an array of predefined messages (same as e.g. Laravel)?
Texts of such messages could be possibly overridden via a custom YML file placed in the `resources` folder.
(Spring already does this with validation and I believe that the file is called `ValidationMessages.ym`l)

**Comment by lukaseder** [comment]
> how can I actually handle the specific codes 

Those are managed by said translator, used to translate from codes to exception subtypes.

> and other useful stuff, like names of tables, rows, foreign keys, constraints,...?

What do you want to do?

> Also, is there some clean way to easily handle and convert such errors to user-friendly messages (e.g for frontend)?

I can almost not imagine an obvious, universal, 1-1 mapping between very technical error messages such as constraint violations, and user oriented errors, to an extent where jOOQ and/or Spring would be able to solve this once and for all and for all possible domains.

Besides, exposing your schema to the end user in such a way sounds like a security nightmare, but I may just not have worked with Laravel (see your below comment) to see the benefits of such automation.

> Maybe JOOQ could include some default `@ExceptionHandler` for `DataAccessException` which would send HTTP 400 and an array of predefined messages (same as e.g. Laravel)?

But why would jOOQ worry about HTTP? Are you sure you're on the correct layer of your application? What next? Should jOOQ worry about UDP? And RMI? And SOAP? What about REST?

Maybe, you could try to find something "magic" in Spring, but most definitely not in jOOQ. jOOQ is a SQL library and it will luckily never deal with anything related to HTTP.

> Texts of such messages could be possibly overridden via a custom YML file placed in the `resources` folder.
> (Spring already does this with validation and I believe that the file is called `ValidationMessages.yml`)

Exactly. And I would look for more such things in Spring, not in jOOQ.

Now, I agree that exception subtypes could be useful, as opposed to enums. Though that's just a matter of style and not really solving your problem, as it's still very low level.

I don't think you really want a solution in jOOQ.

**Comment by 0248991** [comment]
I see, I guess that I just didn't get you.

So I checked the source of the translator, see: [(https://github.com/spring-projects/spring-framework/blob/master/spring-jdbc/src/main/java/org/springframework/jdbc/support/SQLStateSQLExceptionTranslator.java)]

and as you mentioned, it literally translates the codes to concrete exceptions.
That's somewhat helpful, though once again, not really satisfactory.

Consider the following simple use-case:
- when a user sends a request to create a new account, I want to properly handle e.g. unique constraint error on a username - if already taken - and be able to provide at least what and where went wrong
- So for unique constraint error, I would want at least to retrieve colliding row names (e.g. as `String[]`, or in JOOQ's case rather `Field[]`)

The problem with the translator is that for e.g. unique constraint it throws generic `DataIntegrityViolationException`, which holds no information about the integrity problem - it holds only `String` message, which I believe is supplied by the parent class `AbstractFallbackSQLExceptionTranslator`, which constructs it like this:
```
protected String buildMessage(String task, @Nullable String sql, SQLException ex) {
		return task + "; " + (sql != null ? ("SQL [" + sql + "]; ") : "") + ex.getMessage();
	}
```
This is of course completely unusable. To point it formally
- the translator translates only to 5 types of generic (high-level) exceptions, which cannot be further processed and evaluated (if you don't want to go for a full-text search)
- this means that you can't really (simply) get the real cause and so handle it properly (`DataIntegrityViolationException` represents 6 different database errors)
- this means that in this state you are not able to validate the result at all and basically need to configure a custom implementation of the translator (which makes the codebase unnecessarily "fat")

Also, I see, that JOOQ's and Springs' `DataAccessException`s are actually completely independent, meaning that JOOQ's won't be processed by the translator at all, making it available to be subclassed and handled in Spring without any issues.

So that's that, thank you for the insight and time :)

**Comment by lukaseder** [comment]
I completely understand your point here. But what should jOOQ do here, in your opinion? Make some heuristics based on a formatted string? Use machine learning to process it? I mean, this stuff can change between any version of a JDBC driver, and is not usually specified. Also, internationalisation can get in the way, and some RDBMS don't log anything useful at all. (not even the `SQLState`)

Yes, it's a mess. But there isn't anything robust that could be implemented on the jOOQ side, or the Spring side. If there were, Spring would have it!

If you're fine with regex matching, you can easily implement that yourself, either using the Spring Boot (not the Spring one:) https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jooq/JooqExceptionTranslator.java, or your own. It's not 1000s of lines of code, or rocket science.

But on the jOOQ side, I really wouldn't want to maintain any such sloppy formatted-string-based exception translation that will break with every patch release of every JDBC driver out there. After all, end user applications will start relying on this information, and they will break all the time, producing busywork and frustration on the jOOQ side.

I would be the first one to want to offer the result you've described (clear indication what database object caused the constraint violation). But I only want to offer such a thing if it is robust.

**Comment by 0248991** [comment]
One weird solution comes to my mind:
- what about running every SQL command as a (non-stored?!) procedure with as much exception handling(`catch `or something) as possible?

It could look like this (pseudo-code):
```
START PROCEDURE
// the actual SQL code provided by jooq
update user set name = "Amadeus" where id=1;
update user set name = "Voldemort" where id=2;
//milion catches
catch unique_constraint(name) raise with message "User already exists", code=420
catch unique_constraint(my_custom_name_prefix_constraint) raise with message "User name cannot start with V", code=69
END
```

At least Postgres seems to have some sort of error handling, see:
[postgres 12 error handling](https://www.postgresql.org/docs/current/plpgsql-errors-and-messages.html)

**Comment by lukaseder** [comment]
> * what about running every SQL command as a (non-stored?!) procedure with as much exception handling(`catch `or something) as possible?

Well for starters, we can help with that: https://www.jooq.org/doc/latest/manual/sql-building/procedural-statements, though `RAISE` and `SQLSTATE HANDLER` clauses (standard SQL) or `EXCEPTION` clauses (PL/pgSQL) are not yet supported. We'll get there. But I doubt this is the solution you want.

> * (without any performance issues)

I wouldn't bet on it. The procedural block is interpreted, and PG's execution plan cache is already relatively weak. If you're wrapping statements in such blocks *every time*, I'd expect overhead. Also, this approach would complicate batching and bulk operations, but yes, it would work with `UpdatableRecord` methods, such as `store()`, `insert()`, `update()`

> catch unique_constraint(name)

Yes, it's possible to some extent to do switches on constraint names or table names:
https://www.postgresql.org/docs/current/plpgsql-control-structures.html#PLPGSQL-ERROR-TRAPPING

> SQLSTATE seems to be a standard, as described here:

We already offer access to the standard SQL state via `DataAccessException::sqlState` and `::sqlStateClass`, and so does JDBC's `SQLException::getSQLState`. But seem to have found that too cumbersome to use earlier.

> Is JOOq implemented for non-standard or NoSql databases as well?

jOOQ only supports SQL databases.

> Are there really databases that do not implement this?

Most RDBMS support SQL states, but we're going in circles here. You already rejected using SQL state earlier. Anyway. It seems you can achieve most of what you want with OOTB features already, at least in PostgreSQL. Check this out:

```java
try {
    DSL.using(connection).insertInto(T_AUTHOR).columns(T_AUTHOR.ID).values(1).execute();
}
catch (DataAccessException e) {
    ServerErrorMessage error = ((PSQLException) e.getCause()).getServerErrorMessage();
    System.out.println(error.getTable());
    System.out.println(error.getColumn());
    System.out.println(error.getConstraint());
}

try {
    DSL.using(connection).insertInto(T_AUTHOR).columns(T_AUTHOR.ID, T_AUTHOR.LAST_NAME).values(1, "X").execute();
}
catch (DataAccessException e) {
    ServerErrorMessage error = ((PSQLException) e.getCause()).getServerErrorMessage();
    System.out.println(error.getTable());
    System.out.println(error.getColumn());
    System.out.println(error.getConstraint());
}
```

The two exceptions are:

```
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "last_name" of relation "t_author" violates not-null constraint
  Detail: Failing row contains (1, null, null, null, null, null).
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pk_t_author"
  Detail: Key (id)=(1) already exists.
```

And the two outputs of `System.out.println` are:

```
t_author
last_name
null

t_author
null
pk_t_author
```

So, everything you need is there. You can now implement your `ExecuteListener` that translates the jOOQ `DataAccessException` into your own custom exception that is configured by a YAML file, and you're all set.

**Comment by OndraZizka** [comment]
Good elaboration on the topic.
If I understand it correctly, then in short:

There's no plan for JOOQ to support determining the common "business" reasons of a statement failure, not even for the databases that may have a reliable way to do so. Correct?

As you describe above with `PSQLException`, that's one way to determine a constraint violation. Which `would` actually make sense to do in JOOQ, because:

1) It is directly at the data base layer which JOOQ is supposed to abstract from.
2) JOOQ has the most important information: The name of the constraint, the column name, the kind of constraint.
3) JOOQ already does invest time into supporting the changing implementation of the database, including the JDBC driver.
4) For some databases and their drivers, the way of translating the violation into an exception doesn't really change, and is documented, therefore not a subject of random changes to the JDBC driver.
5) Specifically the UNIQUE constraint is more about the business logic than data integrity, and is often used to prevent the user to enter the same value multiple times; so the support for this case would be quite useful.

@lukaseder is that a firm resolution not to determine unique constraint validation, at least for the DBs that allow to do that reliably?
Thanks a lot for your patient and very informative answers.

**Comment by lukaseder** [comment]
@OndraZizka: I don't think you're raising any new points here, so there won't be any new answers, or changes of strategy.

I don't think this is an area where cost/benefit are good. You can write your own `ExecuteListener` to do exactly what you want.
