### ISSUE TITLE
Create a Java 17 distribution

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11729]
Oracle is getting ready to distribute the next LTS after Java 11. While we've integration tested jOOQ with most releases between 11 and 17, we will also support 17 explicitly for a long time. The Java 17 distribution will include a few features, such as record code generation and others that might be listed here.

**Comment by lukaseder** [comment]
At the beginning, like the JDK 11 distribution, the JDK 17 distribution will be commercial only.

**Comment by lukaseder** [comment]
With Java 17 being the new source language level of the development build (trial and pro edition), backporting to Java 11 and 8, we can now introduce a few new features to our code base:

- [x] Text blocks (they're relatively easy to regex-replace)
- [x] Record types (a bit more tricky but not impossible)
- [ ] Sealed types (if they do ship with 17)
- [ ] Other features?

**Comment by lukaseder** [comment]
There seems to be a blocker as the `maven-plugin-plugin` isn't ready:

- https://stackoverflow.com/q/67113170/521799
- https://issues.apache.org/jira/browse/MPLUGIN-371

**Comment by lukaseder** [comment]
A workaround for xtend needs to be applied: https://bugs.eclipse.org/bugs/show_bug.cgi?id=572909

**Comment by mkurz** [comment]
> * [x]  ~Sealed types (if they do ship with 17)~ We can re-consider this later. For now, let's build for Java 16

**Newsflash**
Sealed Classes (JEP 409) was just merged into the Java 17 dev repo like 30 minutes ago:
* https://github.com/openjdk/jdk/pull/3526
  * Commit: https://github.com/openjdk/jdk/commit/0fa9223f34bc33635079763362f42f0a5c53759b
* https://github.com/openjdk/jdk/pull/3528
  * Commit: https://github.com/openjdk/jdk/commit/31b98e129e6d3051c01775519792b2ba5745b275
* https://github.com/openjdk/jdk/pull/3613
  * Commit: https://github.com/openjdk/jdk/commit/7dcb9fda89ee17a5eadc83999de21e4542f37133

Also see https://openjdk.java.net/projects/jdk/17/

**Comment by lukaseder** [comment]
Thanks for the ping. Yes, indeed, but IDEs won't be ready by the time jOOQ 3.15 is released, so I don't think the new jOOQ JDK 17 distribution will profit from this yet.

**Comment by mkurz** [comment]
:+1: How would you make use of sealed classes in generated code actually?

**Comment by lukaseder** [comment]
This isn't about generated code, this is about jOOQ internals. It would be interesting to evaluate whether the `QueryPart` hierarchy could be closed using sealed types, profiting here and there from some pattern matching. E.g. look at this method:

https://github.com/jOOQ/jOOQ/blob/4efb78ac204ae2713fd1e3e41f8c4deb44b39c8c/jOOQ/src/main/java/org/jooq/impl/SelectQueryImpl.java#L3679-L3718

It's not the only one that has to "switch" over subtypes of `SelectFieldOrAsterisk`. Now, recently, `Row` became a new subtype of `SelectField`: https://github.com/jOOQ/jOOQ/issues/11812. Wouldn't it be great if all of these switches stopped compiling until the new case is handled correctly?

I don't know what's possible yet, but I'm looking forward to playing around with this.

Backporting the sealed type declarations should be simple - just remove the sealedness syntax. Backporting the pattern matching (in the future) might be more laborious, but let's see...

**Comment by mkurz** [comment]
Definitely interesting, thanks for sharing!
