### ISSUE TITLE
Wrong precision for H2 timestamp when using domains

### ISSUE THREAD

**Issue by muued** [jOOQ/jOOQ#11721]
### Expected behavior
Using a timestamp in H2 as a domain is consistent with using it directly, i.e. it should by default have a precision of 6.
SQLDataType.TIMESTAMPWITHTIMEZONE(6)

### Actual behavior
Creating a domain in H2 as a timestamp and generating sources for the schema public (domains cant be created in other schemas) gives the wrong precision in Domains.java.
Instead of precision 6, it generates precision 32.
SQLDataType.TIMESTAMPWITHTIMEZONE(32)

### Steps to reproduce the problem

- If the problem relates to code generation, please post your code generation configuration
see MCVE, important part is including the PUBLIC schema to have Domains.java generated

- A complete set of DDL statements can help re-create the setup you're having
see MCVE, but the core line is
CREATE DOMAIN domaints AS TIMESTAMP WITH TIME ZONE;

- An MCVE can be helpful to provide a complete reproduction case
Can be found here: https://github.com/muued/jOOQ-mcve/tree/issue11721

### Versions

- jOOQ: 3.14.8
- Java: 15
- Database (include vendor): H2 1.4.200
- OS: macOS 10.15.7
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can reproduce this. Will fix immediately

**Comment by lukaseder** [comment]
It looks like H2 stores the timestamp precision in the `INFORMATION_SCHEMA.DOMAINS.SCALE` column.

**Comment by lukaseder** [comment]
The same thing was fixed for `INFORMATION_SCHEMA.COLUMNS` in jOOQ 3.12: https://github.com/jOOQ/jOOQ/issues/7644

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.15.0 and 3.14.9 (#11728)
