### ISSUE TITLE
PostgreSQL ON CONFLICT .. WHERE <index_predicate> generates not valid SQL

### ISSUE THREAD

**Issue by Captain1653** [jOOQ/jOOQ#11732]
The issue relates to #6736
 I have some strange behavior. Can you help me? Let me explain:

1. I have some table 
```
create table course_enroll
(
	id bigint not null
		constraint course_enroll_pk
			primary key,
	token text not null,
	user_id bigint not null,
	course_id bigint not null,
	attempts_limit integer default 1,
	attempts_used integer,
	deleted_ts timestamp,
	ac_host_id bigint,
	created_ts timestamp,
	updated_ts timestamp
);

create unique index "course-enroll-one-active-uidx"
	on course_enroll (user_id, course_id)
	where (deleted_ts IS NULL);

```
2. I have some jooq insert-code and onConflict:
``` 
multiUpsert.onConflict(COURSE_ENROLL.USER_ID, COURSE_ENROLL.COURSE_ID)
                .where(COURSE_ENROLL.DELETED_TS.isNull())
                .doUpdate()
                .set(COURSE_ENROLL.UPDATED_TS, now())
                .returning(COURSE_ENROLL.fields());
```
3. But the onConflict generated not valid SQL:
```sql
insert into "public"."course_enroll" ("id", "token", "user_id", "course_id", "attempts_limit", "attempts_used",
                                      "deleted_ts", "ac_host_id", "created_ts", "updated_ts")
values (nextval('"public"."course_enroll_seq"'), 'E6jFiIyC2NClZpMmj-87X0u9Zft7tNNtlhQ6kZ3g8N0FFLtU3uDfleJUOqq', 1,
        1, 1, 0, null, 50, timestamp '2021-03-19 13:39:25.62', timestamp '2021-03-19 13:39:25.62')
on conflict ("user_id", "course_id")
-- Problematic part here
where "public"."course_enroll"."deleted_ts" is null do   
update
set "updated_ts" = timestamp '2021-03-19 13:39:25.62';
``` 
my IDE show me error:

**[42P01] ERROR: invalid reference to FROM-clause entry for table "course_enroll"  There is an entry for table "course_enroll", but it cannot be referenced from this part of the query. Position: 469**

The SQL works with `where deleted_ts is null do update` (just use simple name `deleted_ts`).  

Did I make some mistake?  Is it really important to use simple name? Can you help me to  generate the correct SQL-query?  
 I use:
-  postgres 12.5 
- liquibase
- jooq 3.14.8. 

Please, let me know if you have any questions.

Kind regards

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can reproduce this. That's clearly a bug, we mustn't fully qualify the columns. Our integration tests just added a dummy `"1 = 0"` predicate here, which is why we haven't noticed.

Youc an easily work around this problem by specifying this instead:

```java
.where(field(COURSE_ENROLL.DELETED_TS.getUnqualifiedName()).isNull())
```

**Comment by lukaseder** [comment]
N.B: This was considered a bug in PostgreSQL that has been fixed just now:

- https://www.postgresql.org/message-id/16958-963f638020de271c%40postgresql.org
- https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=6c0373ab77359c94b279c4e67c91aa623841af65

See also discussion on Twitter, here:

- https://twitter.com/pg_xocolatl/status/1382099254341144583

Nevertheless, jOOQ will continue to avoid qualification of column references in this `WHERE` clause.
