### ISSUE TITLE
Validate That Identifier Names Are Less Than Max NAMEDATALEN

### ISSUE THREAD

**Issue by clarkwalcott** [jOOQ/jOOQ#11730]
### Expected behavior
Throws an exception when an identifier (table name, column name, constraint name, etc)  is created that has a length greater than the language-specific limit (63 in Postgres).
### Actual behavior
Allows the identifier to be created where it is then truncated when it is loaded into Postgres. Trying to reference the original identifier shows that it isn't found because that it only exists in its truncated form.
### Steps to reproduce the problem

1. Create a table: 
Table<Record> table = DSL.table(DSL.name("tableNameThatIsJustOverTheAllowedAmountOfCharactersForPostgresql");
2. Get the field references for that table: 
List<Table<?>> tableList = dslContext.meta().getTables(table.getName());
3. tableList.isEmpty() == true

### Versions

- jOOQ: spring-boot-starter-jooq with spring-boot-gradle-plugin version 2.2.0.RELEASE
- Java: 11
- Database (include vendor): PostgreSQL Version 11
- OS: MacOS
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver

**Comment by lukaseder** [comment]
Thanks for your suggestion. We could do that for DDL API, though I wouldn't want to spend too much time on this quirk. In the meantime:

1. The right place to address this bug report would be PG itself. This is an absolute non-feature (I ran into it myself in the past), and it should be removed. It would be *very* easy for PG to replace the truncation logic by an exception throwing logic, like in all other RDBMS.
2. You could implement a `VisitListener` that throws your exception?
3. You could implement a job that keeps querying the information_schema for identifiers of length 63 and sends a report whenever it finds one

**Comment by clarkwalcott** [comment]
Okay, thank you for your input! I'll look into PG!
