### ISSUE TITLE
Filter not working properly for numeric datatype

### ISSUE THREAD

**Issue by gowtham3** [jOOQ/jOOQ#11736]
```
create table test (
    amount numeric(22,0),
    account_id int
);

select * from test;

insert into test values (56000, 1);

select amount/10000, account_id from test where amount/10000=5.6;
```
The above select query returns the row that is inserted.

But, when the same is written using JOOQ, the condition `Test.TEST.AMOUNT.div(10000).equal(5.6)` becomes `where amount/10000=5`.
### Expected behavior
Properly generated SQL with condition where amount/10000=5.6

### Actual behavior
Query generated is `where amount/10000=5`

### Versions

- jOOQ: 3.14.8
- Java:11
- Database (include vendor):POSTGRES
- OS:Mac
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report

How exactly did you construct your jOOQ query? Using the code generator? But that shouldn't compile:

```java
Field<BigDecimal> f = DSL.field("f", SQLDataType.NUMERIC);
System.out.println(f.div(10000).eq(5.6));
```

I'm getting:

> The method eq(BigDecimal) in the type Field&lt;BigDecimal> is not applicable for the arguments (double)

This compiles:

```java
Field<BigDecimal> f = DSL.field("f", SQLDataType.NUMERIC);
System.out.println(f.div(10000).eq(new BigDecimal("5.6")));
```

And produces the desired output:

```sql
(f / 10000) = 5.6
```

**Comment by lukaseder** [comment]
Oh, I see, the type is probably `SQLDataType.DECIMAL_INTEGER` because of your zero scale? In that case, workarounds would include:

- Using a forced type in your code generation to remove the zero scale
- Coercing the field expression to `SQLDataType.NUMERIC` prior to the operation

I'm still curious how you managed to compile this expression. There seems to be some missing information.

**Comment by gowtham3** [comment]
Yeah, the type that is getting generated is SQLDataType.DECIMAL_INTEGER, which in turn is BigInteger in java.
```    
public final TableField<TestRecord, BigInteger> AMOUNT = createField(DSL.name("amount"), org.jooq.impl.SQLDataType.DECIMAL_INTEGER.precision(22), this, "");
```

Coercing the field expression to `SQLDataType.NUMERIC` worked. Thanks.

But, when we do some operation on a field (divide by 10000 in this case), the type of the value changes right, shouldn't the type conversion happen to the new field type and not to the old one?


And by the way, it compiled because we're not supplying the type in generics
```        
Field f = Test.TEST.AMOUNT.div(10000);
System.out.println(f.eq(5.6));
```

**Comment by lukaseder** [comment]
> But, when we do some operation on a field (divide by 10000 in this case), the type of the value changes right, 

No, jOOQ cannot maintain type promotions and the likes in a type safe manner. In binary expressions, the data type of the expression (as known to jOOQ) is always that of the left operand, so if you do `A / B`, the type of the expression will be that of `A`. That isn't correct in all SQL dialects, but I don't see how else we could model that in the API.

> shouldn't the type conversion happen to the new field type and not to the old one?

I'm not sure what you mean by that. Which is the "new" type and which is the "old" one?

> And by the way, it compiled because we're not supplying the type in generics

I see. Well, no I don't :) Why are you not using the types? You're losing on half of jOOQ's type safety this way. E.g. would have prevented this mistake (though you would not have helped discover the deeper problem of comparing `DECIMAL_INTEGER` and `DECIMAL` types).

If you find declaring all the types too noisy, why not just use `var`?

```java
var f = Test.TEST.AMOUNT.div(10000);
System.out.println(f.eq(5.6)); // Compilation error
```

**Comment by lukaseder** [comment]
I'm closing this as "won't fix". The inferred bind value type is `BigInteger`, and as such, the auto-conversion truncates the double's decimal part. This is how jOOQ works throughout the API. We can't introduce a special case for this kind of API usage, where a rawtype prevents type safety.
