### ISSUE TITLE
Extract AttachableQueryPart from Query

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11755]
Some methods from the `Query` interface should also be present on the `Queries` interface. These include:

- [x] `getBindValues()`
- [x] `getParam(String)`
- [x] `getParams()`
- [x] `getSQL()`
- [x] `getSQL(ParamType)`

We'll extract a new common interface that is shared between `Query` and `Queries`. The methods make sense wherever a type is a subtype of `QueryPart & Attachable`, so perhaps the type could be called `AttachableQueryPart` (a `QueryPart` with an attached `Configuration`). This is required because some attachables are not `QueryPart`, e.g. `Record`, `Result`

**Comment by lukaseder** [comment]
It may also be useful to pull up the `bind()` methods in the future, once their mutability discussion has been settled.

**Comment by marceloverdijk** [comment]
Thx for this improvement to solve https://stackoverflow.com/questions/66959490/how-to-add-a-semi-colon-automatically-to-each-generated-sql-statement-using-jo
Keeping my eye on the next release.
