### ISSUE TITLE
How to get stored procedure select resultset

### ISSUE THREAD

**Issue by kortemik** [jOOQ/jOOQ#11756]
### Your question:

I have defined a stored procedure as:
```sql
DROP PROCEDURE IF EXISTS getResults;
  
DELIMITER $$
CREATE PROCEDURE `getResults`(
    IN p_get_by_id BIGINT UNSIGNED
)
COMMENT 'getResults provides something for given id
    * id, id used to get data for
'
READS SQL DATA
BEGIN
  
    CREATE TEMPORARY TABLE tmp_Results
    (UNIQUE KEY (l_id))
  
    AS SELECT
       lf.id AS l_id
    FROM otherdb.linefeed AS lf
    WHERE
      (lf.id = p_get_by_id OR p_get_by_id IS NULL)
    ORDER BY lf.id
    LIMIT 5;
  
    SELECT
           l_id
    FROM tmp_Results;
  
    DROP TEMPORARY TABLE tmp_Results;
END $$
DELIMITER ;
```

I couldn't find my way through the JOOQ inteface, every example seems to be using OUT parameters with stored procedures but this here is a resultset, one could actually have many resultsets for a stored procedure by having multiple selects within it.

### Versions:

- jOOQ: 3.12.4
- Java: 1.8
- Database (include vendor): MariaDB 10.3
- OS: RHEL 7
- JDBC Driver (include name if inofficial driver): org.mariadb.jdbc:mariadb-java-client:2.7.2

**Comment by lukaseder** [comment]
You can retrieve the results like this. if you're using the code generator:

```java
Getresults r = new Getresults();
r.setPGetById(1L);
r.execute(configuration);
Results results = r.getResults();
```

Alternatively, using plain SQL templating:

```java
DSLContext ctx = ...
Results results = ctx.fetchMany("call getResults(?)", 1L);
```

Though, we haven't integration tested this with MariaDB yet, so there might be bugs. I'll update our tests and report back with potential findings.

**Comment by kortemik** [comment]
Calling .execute() without argument gives:
```
Exception in thread "main" java.lang.NullPointerException
        at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:355)
        at tld.domain.test_jooq.TestingTesting.exec(TestingTesting.java:93)
        at tld.domain.test_jooq.Main.main(Main.java:9)
```

which was confusing me.

Using 
r.execute(ctx.configuration()); works just fine. I think the api might be improved by requiring an argument for the execute?

**Comment by lukaseder** [comment]
Thanks for your feedback.

`Routine` implements `Attachable`, so it is possible for a `Routine` instance to already have a `Configuration`. Of course, the NPE is the problem here. It should be a `DetachedException` hinting at the routine not being "attached". I'll fix this right away: https://github.com/jOOQ/jOOQ/issues/11760

**Comment by lukaseder** [comment]
> Though, we haven't integration tested this with MariaDB yet, so there might be bugs

My bad, we're already integration testing this for MariaDB as well.
