### ISSUE TITLE
Add `InsertSetStep` `values(Record record)` method

### ISSUE THREAD

**Issue by marceloverdijk** [jOOQ/jOOQ#11758]
### Use case:

I would like to call `insertInto` `values` with `Record` instances like:

```
def insert = dsl.insertInto(table).columns(table.fields())
records.each { record -> insert.values(record) }
println insert.SQL
```

### Possible solution you'd like to see:

Add `InsertSetStep` `values(Record record)` method (see above example).
Similar as there is already a `set(Record record)` method.

### Possible workarounds:

```
def insert = dsl.insertInto(table).columns(table.fields())
records.each { record ->
    def values = []
    for (int i = 0; i < record.size(); i++) {
        values << record.get(i)
    }
    insert.values(values) 
}
println insert.SQL
```

### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your suggestion. I think this will already be covered by this jOOQ 3.15 feature: https://github.com/jOOQ/jOOQ/issues/6604

**Comment by lukaseder** [comment]
I.e.:

```
println dsl.insertInto(table).columns(table.fields()).valuesOfRecords(records).SQL
```

**Comment by TheBestPessimist** [comment]
The suggestion above doesn't look very nice because `table.fields()` returns an array, while `.colums` expects a list. So i need to change my array to a list instead:

```kotlin
        ctx.dsl().insertInto(SUBSCRIPTION)
            .columns(SUBSCRIPTION.fields().asList())
            .valuesOfRecords()
            .execute()
```

Is this something that should/could be improved?

**Comment by lukaseder** [comment]
@TheBestPessimist Thanks for your feedback. There's an overload `.columns()` that accepts a `Field<?>...` which is an array, so I'm not sure what limitation you're running into.

But anyway, this isn't really related to this issue here, so if you think there's a problem, can you please open a new issue so we can track the problem?
