### ISSUE TITLE
DefaultRecordMapper should reflect on Class.getRecordComponents()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11778]
jOOQ 3.15 will introduce a Java 17 build to the commercial distributions with https://github.com/jOOQ/jOOQ/issues/11729. That build will be able to refer to `Class.getRecordComponents()` to reflect on record types and their constructor arguments, similar to using `ConstructorProperties` or some other means.

**Comment by lukaseder** [comment]
A simple experiment:

```java
record X (int i, String j) {}
for (RecordComponent c : X.class.getRecordComponents())
    System.out.println(c.getName() + ": " + c.getType());
```

Producing:

```
i: int
j: class java.lang.String
```

**Comment by lukaseder** [comment]
A record can have multiple constructors:

```java
record X(int i, int j) {
    X(int i) {
        this(i, 0);
    }
    X() {
        this(0, 0);
    }
    X(String i, String j) {
        this(Integer.parseInt(i), Integer.parseInt(j));
    }
}
```

One way to find the "correct" constructor (the one created from the `RecordHeader`) is this:

```java
List<?> componentTypes = Stream
    .of(X.class.getRecordComponents())
    .map(RecordComponent::getType)
    .toList();

for (Constructor<?> c : X.class.getDeclaredConstructors())
    if (Arrays.asList(c.getParameterTypes()).equals(componentTypes))
        System.out.println(c);
```

See also:
https://stackoverflow.com/q/67126109/521799

**Comment by lukaseder** [comment]
Let's add some more tests to make sure nested records also map correctly

**Comment by lukaseder** [comment]
Also, perhaps the flag should be turned off by default?

**Comment by lukaseder** [comment]
The flag should be turned off by default, indeed, just like the `Settings.isMapConstructorParameterNames()` flag, because otherwise, the different distributions would behave differently:

- Java 11 distribution would map to records by parameter index by default
- Java 17 distribution would map to records by parameter name by default

In many cases, the two mapping algorithms produce the same behaviour as users will shape their SQL accordingly, but sometimes, they won't, and the subtle difference will be very hard to debug.

**Comment by lukaseder** [comment]
An example where we'd introduce a breaking change if we changed the default behaviour is this:
https://72.services/java-16-records-with-jpa-and-jooq/

The author (@simasch) uses this statement to map columns based on their positions into a DTO that has been refactored from a class to a record. We mustn't implicitly change the behaviour here in the new Java 17 distribution:

```java
List<EmployeeDTO> employees = dsl
   .select(EMPLOYEE.NAME, DEPARTMENT.NAME)
   .from(EMPLOYEE).join(DEPARTMENT).on(EMPLOYEE.DEPARTMENT_ID.eq(DEPARTMENT.ID))
   .fetchInto(EmployeeDTO.class);
```

**Comment by simasch** [comment]
I wasn't aware of name based constructor mapping. 
Having a constructor I always assume an index based behavior.

**Comment by lukaseder** [comment]
We support name based mapping for those that want it. It can be opted in via `Settings`, or via `@ConstructorProperties` annotations (the presence of that annotation hints at users wanting name based mapping).

There are pros and cons to both mapping algorithms, but the default should always be index based
