### ISSUE TITLE
Include identity-generated system sequences in PostgreSQL generated code

### ISSUE THREAD

**Issue by ergonben** [jOOQ/jOOQ#11780]
**Question**

jOOQ generates a `Sequences` class with entries for DB sequences. For example, defining a table like

```sql
CREATE TABLE serial_author (
  id serial not null,
  PRIMARY KEY (id)
);
```

automatically introduces a sequence `serial_author_id_seq` in PostgreSQL, which jOOQ wraps in an entry `Sequences.SERIAL_AUTHOR_ID_SEQ`, as expected.

However, no wrapper seems to be generated for a table like

```sql
CREATE TABLE identity_author (
  id bigint generated by default as identity not null,
  PRIMARY KEY (id)
);
```

How come? We'd like to access any kind of sequences via wrappers.

Minimal complete example to reproduce this: [sequences-example.zip](https://github.com/jOOQ/jOOQ/files/6325423/sequences-example.zip)

Any help is appreciated. Thanks.

**Context**

Naturally, we could switch from `bigint generated by default as identity` to `serial8` in our migrations.

However, prior to jOOQ code generation, we use the generic jOOQ API with `DSL.field("id", SQLDataType.BIGINT.identity(true))` to define such `id` columns in our migrations. Up to jOOQ 3.12.4, such a field seems to result in `id serial8 not null` when used with a `DSLContext.createTable`, but in jOOQ 3.13.0 and 3.14.8, it results in `id bigint generated by default as identity not null`.

As we'd like to keep our migrations in jOOQ with this upgrade, our problem above would be solved if we could still specify `serial8` fields.

**Side note**

Not sure if related, but the query

```sql
SELECT relname FROM pg_class WHERE relkind = 'S'
```

returns any sequences behind `serial` and `generated as identity`, whereas

```sql
SELECT sequence_name FROM information_schema.sequences
```

only returns sequences behind `serial` but not `generated as identity` (see attached example for details).

**Versions**

- jOOQ: 3.14.8
- Java: OpenJDK 1.8.0_282
- Database: PostgreSQL 13.2 (via Docker image `postgres:13.2`)
- OS: Ubuntu 20.04.2 LTS
- JDBC Driver: `org.postgresql.Driver`

**Comment by lukaseder** [comment]
Thanks a lot for your request. As can be seen here:
https://github.com/postgres/postgres/blob/REL_13_STABLE/src/backend/catalog/information_schema.sql

The source of the `information_schema.sequences` view is (I removed casts and added some qualification for convenience):

```sql
SELECT current_database() AS sequence_catalog,
       nc.nspname AS sequence_schema,
       c.relname AS sequence_name,
       format_type(s.seqtypid, null) AS data_type,
       information_schema._pg_numeric_precision(s.seqtypid, -1) AS numeric_precision,
       2 AS numeric_precision_radix,
       0 AS numeric_scale,
       s.seqstart AS start_value,
       s.seqmin AS minimum_value,
       s.seqmax AS maximum_value,
       s.seqincrement AS increment,
       CASE WHEN s.seqcycle THEN 'YES' ELSE 'NO' END AS cycle_option
FROM pg_namespace nc, pg_class c, pg_sequence s
WHERE c.relnamespace = nc.oid
      AND c.relkind = 'S'
      AND NOT EXISTS (SELECT 1 FROM pg_depend WHERE classid = 'pg_class'::regclass AND objid = c.oid AND deptype = 'i')
      AND (NOT pg_is_other_temp_schema(nc.oid))
      AND c.oid = s.seqrelid
      AND (pg_has_role(c.relowner, 'USAGE')
           OR has_sequence_privilege(c.oid, 'SELECT, UPDATE, USAGE') );
```

The difference is in the usage of `pg_depend`. Without this predicate, the identity based sequences are included:

```sql
      AND NOT EXISTS (SELECT 1 FROM pg_depend WHERE classid = 'pg_class'::regclass AND objid = c.oid AND deptype = 'i')
```

We could obviously query the `pg_catalog` directly rather than the `information_schema`. I don't see a good reason to omit the identity based sequences, but not the serial based ones.

Related: jOOQ 3.15 introduces a new `<includeSystemSequences/>` flag to remove the generation of these sequences: https://github.com/jOOQ/jOOQ/issues/10899, because they're usually not required.

**Comment by lukaseder** [comment]
As a workaround, you can of course extend `PostgresDatabase` and override the `getSequences0()` method to run your own query...

**Comment by lukaseder** [comment]
I suspect we must continue using the old query for backwards compatibility as `pg_sequence` was introduced only in PostgreSQL 10

**Comment by lukaseder** [comment]
This is implemented for jOOQ 3.15.0. Still due:

- [ ] Wait for regression tests on older PG versions
- [ ] Wait for regression tests on Aurora, CockroachDB, Redshift
- [ ] Make sure `Meta.getSequences()` picks this up correctly

Will finish next week.

**Comment by ergonben** [comment]
Thanks a lot, that's really fast. We might just manually wrap our couple of sequences for now, then upgrade to 3.15.0 once it's released.

**Comment by lukaseder** [comment]
This can't be easily made available to `Meta.getSequences()` as implemented in https://github.com/jOOQ/jOOQ/issues/10844. I've created a new issue for this, as it isn't code generation specific: https://github.com/jOOQ/jOOQ/issues/11808
