### ISSUE TITLE
Function "GEN_RANDOM_UUID" not found

### ISSUE THREAD

**Issue by Sineaggi** [jOOQ/jOOQ#11805]
### Expected behavior

Trying to use the DDLDatabase to generate jooq files base off of postgres syntax (same issue ran into [here](https://github.com/jOOQ/jOOQ/issues/8324#issuecomment-463747733), couldn't find an issue created for it).

### Actual behavior

```
Caused by: org.jooq.exception.DataAccessException: SQL [create table EXAMPLE (UNIQUE_ID uuid null default GEN_RANDOM_UUID(), primary key (UNIQUE_ID))]; Function "GEN_RANDOM_UUID" not found; SQL statement:
create table EXAMPLE (UNIQUE_ID uuid null default GEN_RANDOM_UUID(), primary key (UNIQUE_ID)) [90022-200]
```

### Steps to reproduce the problem

Example sql
```
CREATE TABLE example
(
    unique_id uuid PRIMARY KEY
        DEFAULT gen_random_uuid()
);
```
mcve [here](https://github.com/Sineaggi/jOOQ-mcve/compare/master...ddldatabase)
i'd recommend having a branch or soemthing for using ddlgenerator available by default in the future.

### Versions

- jOOQ: 3.14.7
- Java: `openjdk 16.0.1 2021-04-20`
- Database (include vendor): h2? postgres syntax otherwise
- OS: macOS Big Sur 11.3
- JDBC Driver (include name if inofficial driver): h2 under jooq, postgres https://jdbc.postgresql.org/

**Comment by Sineaggi** [comment]
Workaround so far has been to do this
```sql
CREATE TABLE mcve.uuid_example
(
    unique_id uuid PRIMARY KEY
        -- [jooq ignore start]
        DEFAULT gen_random_uuid()
    -- [jooq ignore stop]
);
```
which is unfortunate in a project with a lot of tables/default uuids.

**Comment by lukaseder** [comment]
Thanks a lot for your suggestion. We're tracking this feature already as https://github.com/jOOQ/jOOQ/issues/9472. This could definitely add value to the different dialects. Will look into this soon.
