### ISSUE TITLE
Add support for SQL Server data types timestamp and rowversion

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1181]
Note that SQL Server suggests using "rowversion" as a synonym instead of timestamp, because of potential future developments:

http://msdn.microsoft.com/en-us/library/aa260631%28v=sql.80%29.aspx

**Comment by Kaleidoscoper** [comment]
Hi,I'm using jooq to connect to sql server and there is a timestamp column. It also seems to go wrong when fetching, is this caused by the issue?
