### ISSUE TITLE
TABLE.fields() not compatible with DSLContext.select(fields) when using Kotlin

### ISSUE THREAD

**Issue by ChristofferKarlsson** [jOOQ/jOOQ#11859]
In Kotlin, the `TABLE.fields()` method returns an `Array` of fields and the `DSLContext.select()` expects a `Collection` of fields. They are therefor not compatible with each other.

### Expected behavior
This (code that works in Java) I believe should also work in Kotlin:
```
dsl.select(MY_TABLE.fields())
```

### Actual behavior
The code will not compile, with the following error:
```
Kotlin: None of the following functions can be called with the arguments supplied: 
public abstract fun select(p0: (MutableCollection<out SelectFieldOrAsterisk!>..Collection<SelectFieldOrAsterisk!>?)): SelectSelectStep<Record!> defined in org.jooq.DSLContext
public abstract fun select(vararg p0: SelectFieldOrAsterisk!): SelectSelectStep<Record!> defined in org.jooq.DSLContext
public abstract fun <T1 : Any!> select(p0: SelectField<TypeVariable(T1)!>!): SelectSelectStep<Record1<TypeVariable(T1)!>!> defined in org.jooq.DSLContext
```

Unless I manually use the `toList()` extension function:
```
dsl.select(MY_TABLE.fields().toList())
```

### Steps to reproduce the problem
Generate code for a table and try the following code, using Kotlin:
```
dsl.select(MY_TABLE.fields())
```

### Versions

- jOOQ: 3.14.8
- Java: 11
- Kotlin 1.4.32
- Database (include vendor): PostgreSQL 12
- OS: Fedora 32
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report.

Please use the spread operator in kotlin:

```kotlin
dsl.select(*MY_TABLE.fields())
```

See:

- https://kotlinlang.org/docs/functions.html#variable-number-of-arguments-varargs
- https://www.baeldung.com/kotlin/varargs-spread-operator
