### ISSUE TITLE
Static statement invalid rendering

### ISSUE THREAD

**Issue by cdalexndr** [jOOQ/jOOQ#11868]
### Expected behavior
Render query with placeholders `?`.

### Actual behavior
Query is rendered with inlined params.

### Steps to reproduce the problem

Query is rendered the same using any `ParamType` value:
```
        DefaultConfiguration configuration = new DefaultConfiguration();
        configuration.settings().setStatementType( StatementType.STATIC_STATEMENT );
        DefaultDSLContext ctx = new DefaultDSLContext( configuration );
        SelectConditionStep<Record1<Integer>> query = ctx.select( DSL.one() )
                .from( DSL.name( "table" ) )
                .where( DSL.field( "id", Integer.class ).eq( 1 ) );
        String sql1 = query.getSQL( ParamType.INDEXED ); //select 1 from "table" where id = 1
        String sql2 = query.getSQL( ParamType.FORCE_INDEXED ); //select 1 from "table" where id = 1
        String sql3 = query.getSQL( ParamType.NAMED_OR_INLINED ); //select 1 from "table" where id = 1
        String sql4 = query.getSQL( ParamType.NAMED ); //select 1 from "table" where id = 1
        String sql5 = query.getSQL( ParamType.INLINED ); //select 1 from "table" where id = 1
```
Without static statement, the query is rendered correctly.
```
        DefaultConfiguration configuration = new DefaultConfiguration();
//        configuration.settings().setStatementType( StatementType.STATIC_STATEMENT );
        DefaultDSLContext ctx = new DefaultDSLContext( configuration );
        SelectConditionStep<Record1<Integer>> query = ctx.select( DSL.one() )
                .from( DSL.name( "table" ) )
                .where( DSL.field( "id", Integer.class ).eq( 1 ) );
        String sql1 = query.getSQL( ParamType.INDEXED ); //select 1 from "table" where id = ?
        String sql2 = query.getSQL( ParamType.FORCE_INDEXED ); //select 1 from "table" where id = ?
        String sql3 = query.getSQL( ParamType.NAMED_OR_INLINED ); //select 1 from "table" where id = 1
        String sql4 = query.getSQL( ParamType.NAMED ); //select 1 from "table" where id = :1
        String sql5 = query.getSQL( ParamType.INLINED ); //select 1 from "table" where id = 1
```

### Versions

- jOOQ: 3.14.8
- Java: 11
- Database (include vendor): Postgres 12
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.20

**Comment by lukaseder** [comment]
The terminology here is taken from JDBC, which distinguishes between "static" `java.sql.Statement` (no bind variables) and "prepared" `java.sql.PreparedStatement` (with bind variables).

Why would you want a "static statement" to contain bind parameter markers, when the execution environment won't allow it?

**Comment by cdalexndr** [comment]
> Why would you want a "static statement" to contain bind parameter markers, when the execution environment won't allow it?

I need to use static statement to prevent generating `PreparedStatement` that can use a slower generic database query plan. 
But I also need to transform a DML jooq query into a native jpa query to add entity cache region synchronization to clear 2nd level cache after transaction. I transform it by rendering sql using placeholder params and binding them from the original jooq query (with conversion if necesary).
