### ISSUE TITLE
MiniJAXB cannot read code generation's regexFlags content (an xs:list type)

### ISSUE THREAD

**Issue by mqeefqfn** [jOOQ/jOOQ#11870]
I followed the instructions on https://www.jooq.org/doc/3.14/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-regex-flags/  
to override the value of regexFlags, because I need case sensitive for rule expression
### Expected behavior
run the code generator by
mvn -P jooq jooq-codegen:generate@myservice
and get the generated code
### Actual behavior
throw an ConfigurationException "generate failed: org.jooq.exception.ConfigurationException: Error while reading xml"
the root cause is:
"Cannot convert from COMMENTS (class java.lang.String) to interface java.util.List"

### Versions

- jOOQ: from 3.12.1 to 3.14.latest
- Java: 1.8
- Database (include vendor): mysql 5.7
- OS: Arch Linux

**Comment by lukaseder** [comment]
You can use markdown: https://guides.github.com/features/mastering-markdown/

**Comment by lukaseder** [comment]
Fixed for 3.15.0 and 3.14.10 (https://github.com/jOOQ/jOOQ/issues/11872). Thanks again for your report

**Comment by lukaseder** [comment]
It should, yes
