### ISSUE TITLE
Offer a way to run left join aware fetchGroups() 

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11888]
Users often assume that in some cases, `fetchGroups()` be "left join aware", e.g.:

```java
Map<ParentRecord, List<ChildRecord>> result =
create.select(Parent.asterisk(), Child.asterisk())
    .from(PARENT)
    .leftJoin(CHILD)
    .onKey()
    .where(myCondition)
    .fetchGroups(ParentRecord.class, ChildRecord.class);
```

It can be resonably expected that the result will contain empty child lists for parents that do not have any children. After all, the primary key being null can mean only one thing.

However, this is not the case, and a single item child list with a `NULL` child record is present.

We should offer a way to remove such child items in certain `fetchGroups()` overloads. The workaround is to use collectors:

```java
List<ParentRecord, List<ChildRecord>> result =
create.select(PARENT.asterisk(), CHILD.asterisk())
    .from(PARENT)
    .leftJoin(CHILD).onKey()
    .where(myCondition)
    .collect(groupingBy(
        r -> r.into(PARENT), filtering(
            r -> r.get(CHILD.ID) != null, mapping(
                r -> r.into(CHILD), toList()
            )
        )
    ));
```

The exact behaviour is to be defined. See also:
https://stackoverflow.com/q/67523332/521799

**Comment by lukaseder** [comment]
Blogged about this topic again here:
https://blog.jooq.org/using-jdk-collectors-to-de-duplicate-parent-child-nested-collections/

Given that the move is away from these highly overloaded `fetchMap()`, `fetchGroups()`, etc. methods towards:

- collector based methods
- `MULTISET` based queries

I'm not sure if we should really offer more `fetchGroups()` functionality.

**Comment by jasonab** [comment]
Lukas, as much as I appreciate the power that jOOQ provides, I have to say the API tends to fail the "make easy things easy" test. If I have a parent object with two child collections (my very first jOOQ use case_, it's non-trivial to figure out how to fetch those objects in a single query in jOOQ, something that Hibernate makes extremely easy (or at least hides all the complexity).

As such, I'd like to suggest a couple of options:
1. More syntactic sugar in jOOQ to expose functionality like you describe in your blog post, and surface that more directly in the documentation.
2. Have a separate, official project like Jolo whose entire purpose is to act as an ORM-ish wrapper around jOOQ's fundamentals
3. Just tell people to use Hibernate, and focus jOOQ on query generation for non-domain entities, with instructions on how to interoperate the two.

As always, appreciate all of your efforts on this project - I use it as a Hibernate replacement where possible.

**Comment by lukaseder** [comment]
It's actually trivial to do if you're using multiset, and that's much better than anything Hibernate emulates behind the scenes (at least before Hibernate 6 - I'll have to play around with their own planend multiset implementation). Did you read the post to the end? The article mentions multiset very early on as a teaser, and then again several times.

> 1. More syntactic sugar in jOOQ to expose functionality like you describe in your blog post, and surface that more directly in the documentation.

Can you be specific? In my opinion, everything is already there. What's missing for you?

> 2\. Have a separate, official project like Jolo whose entire purpose is to act as an ORM-ish wrapper around jOOQ's fundamentals

As far as I can tell, Jolo got obsolete by multiset. In fact, I should contact the authors (met them personally too, in the past, great folks!) to hear their opinion about this.

> 3\. Just tell people to use Hibernate, and focus jOOQ on query generation for non-domain entities, with instructions on how to interoperate the two.

There's almost no reason to use Hibernate rather than jOOQ, except if you need complex entity graph persistence (i.e. load the graph, mutate it, and persist it again).

**Comment by lukaseder** [comment]
Request for feedback here: https://github.com/PicnicSupermarket/jolo/issues/15

**Comment by jasonab** [comment]
I guess I'll just leave this at, it would be great if the jOOQ docs (which are _very_ thorough) had a section titled "How to use jOOQ instead of Hibernate," and went through the multiset example in small steps. Right now, a lot of this information is spread out across various blog posts and Stackoverflow questions, and it would be nice to have a canonical answer.

**Comment by lukaseder** [comment]
Well, have you seen this? https://www.jooq.org/doc/latest/manual/getting-started/jooq-and-jpa

**Comment by lukaseder** [comment]
For the record, here's a user who found the right answers directly via search for "jOOQ many to many": https://twitter.com/Jotschi/status/1469268398110564353

The information being spread out is kinda inevitable for a popular library like jOOQ. People keep asking similar questions, and it's a lot of work to keep everything up to date. For example, I've just updated this answer here, which talks about exactly this: https://stackoverflow.com/a/32374760/521799

All the information you needed was available *somewhere*, and so was the "canonical answer" in the very section that I would have hoped you'd find if you care about a jOOQ / JPA comparison. Well, it compared jOOQ with JPA, not with Hibernate specifially, and it wasn't all about `MULTISET`.

*You* might have cared about `MULTISET`, mostly (in hindsight), but others certainly don't. And you might not have, either, after your journey through the internet, offering you only seemingly fuzzy answers. Others care about second level caching, object graph persistence, JPQL, etc. etc. etc. So, what would this "canonical answer" section of "How to use jOOQ instead of Hibernate" look like? Wouldn't it be overwhelming by itself?

I don't think a single "canonical answer" is really the thing anyone needs, because it will always be 98% off topic, depending what *actual answer* someone might be looking for.

In any case, you now know about `MULTISET`, and get to enjoy it just as much! 😅

**Comment by lukaseder** [comment]
This idea of a left join aware fetch groups is obsolete. The solution is to either use the `Collector` API, or multisets.
