### ISSUE TITLE
Feedback about manual section count-function

### ISSUE THREAD

**Issue by mddorfli** [jOOQ/jOOQ#11900]
In the Java example, it would help if you could indicate which class you are statically referencing.  I have to search.

e.g. `count()` doesn't say which class the function is defined in. It might be obvious to you, but it's not to me. :)

**Comment by lukaseder** [comment]
Have you tried any of these buttons?

![image](https://user-images.githubusercontent.com/734593/118611192-dcbc6180-b7bc-11eb-836d-c648fcf6991c.png)

How could we have improved those buttons to make it clearer for you?

**Comment by mddorfli** [comment]
Ahhh... you guys are so clever. Sorry, my fault. I should of looked closer. This seriously happened three or four times to me in your docs pages. Now I know.

If you really want to lower the bar down to my level, you could make the static functions link to the javadoc. Or even just to trigger the 'show imports' code. It's a thought.

Thanks for the quick response and for caring.

**Comment by lukaseder** [comment]
> you could make the static functions link to the javadoc. Or even just to trigger the 'show imports' code. It's a thought.

Yes, that's a very good idea, see: https://github.com/jOOQ/jOOQ/issues/3504. It's just also quite hard to do in general, but when we figure out how to do it reliably, there will definitely be Javadoc links all over the code sections.

**Comment by lukaseder** [comment]
I'll try moving that `+ show imports` button to the top left rather than the top right. It's probably more discoverable this way.
