### ISSUE TITLE
SqlServer 2016 optimistic locking with datetime columns and newer mssql drivers

### ISSUE THREAD

**Issue by pacham7** [jOOQ/jOOQ#11916]
Hello,

We've been using Jooq in production for some time, but have had some issue with optimistic locking with recent Microsoft java SQL drivers because our chosen optimistic locking columns are datetime columns. There is an issue in the driver:
https://github.com/microsoft/mssql-jdbc/issues/443
Which effectively means that columns that are datetime, get written by the driver as datetime2, which is then converted to datetime when it reaches the server side, this results in optimistic locking not working properly in jooq, and many other systems (hibernate, and entity framework 6 are two I've heard mention of). Bizarrely this only happens when milliseconds are ending 1,2,4,5,6,8,9 bizarrely, 0,3,7 all work. The really old drivers we currently use send the value as datetime, which avoids this issue entirely, I believe jTDS also does this.
Because this bug doesn't seem to be likely to be fixed any time soon in the java driver (it has existed since 2017, and doesn't seem to have been worked on since then), I've been looking into alternative approaches to solving it. When looking into the Jooq code I noticed it is using a clock to get the datetime, and found the related issue last night https://github.com/jOOQ/jOOQ/issues/6447.
I'm wondering if you think it might be a valid approach to solving this issue, to make our own clock that just avoids (truncates or otherwise rounds to nearest working value) problematic millisecond values, and set it in the configuration?
Do you foresee any issues with such an approach?
The 6447 issue mentions that the clock could be used for other parts of the driver, I'm wondering if that is actually only used in the optimistic locking case, or if it is used elsewhere, and this approach could be problematic for that reason?
All feedback is welcome. Best regards,

Peter

### Versions:

- jOOQ: 3.10.8
- Java: 8.x
- Database (include vendor): Microsoft SqlServer 2016  (Compat 130)
- OS: Windows and Linux
- JDBC Driver (include name if inofficial driver): Microsoft very old and recent versions (4.x, 6.x and newer)

**Comment by lukaseder** [comment]
Thanks a lot for your request. That's a very curious issue, indeed. I've noticed similar problems recently with `VARCHAR` vs `NVARCHAR` types, where the official driver sends the wrong type information, see : https://github.com/jOOQ/jOOQ/issues/11537

Perhaps a similar flag exists for `DATETIME` vs `DATETIME2`?

You could work around these things with a `Clock` but even better than that, you could use a custom data type `Binding` and attach that to all of your `DATETIME` or `DATETIME2` columns:
https://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings/

The `Binding` SPI allows you to get in between jOOQ and JDBC, and patch every bind variable with the appropriate measure, including even to generate a `CAST(? AS DATETIME)` expression if that better solves the problem for you.

Please let me know if you need any additional help with the `Binding` and I'll be very happy to assist you.

**Comment by pacham7** [comment]
Thanks, that is very helpful. We'll do some testing on the binding cast suggestion and reply with the results.

**Comment by pacham7** [comment]
The binding cast suggestion worked well. Thanks Lukas. For the benefit of others who may have the same issue, there is the binding class I've tested it with:

import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultBinding;

import java.sql.SQLException;
import java.sql.Timestamp;

// based on DateAsTimestampBinding
public class DateTimeCastBinding implements Binding<Timestamp, Timestamp> {
	private final Converter<Timestamp, Timestamp> converter = Converters.identity(Timestamp.class);
	private final DefaultBinding<Timestamp, Timestamp> delegate;
	
	public DateTimeCastBinding() {
		this.delegate = new DefaultBinding<>(this.converter);
	}
	
	public final Converter<Timestamp, Timestamp> converter() {
		return this.converter;
	}
	
	// This does all the work
	public final void sql(BindingSQLContext<Timestamp> ctx) throws SQLException {
		ctx.render().visit(DSL.keyword("CAST")).sql('(').visit(
				DSL.val(ctx.value())).sql(' ').visit(DSL.keyword("AS")).sql(' ').visit(DSL.keyword("DATETIME"))
				.sql(')');
	}
	
	public final void register(BindingRegisterContext<Timestamp> ctx) throws SQLException {
		this.delegate.register(ctx);
	}
	public final void set(BindingSetStatementContext<Timestamp> ctx) throws SQLException {
		this.delegate.set(ctx);
	}
	public final void set(BindingSetSQLOutputContext<Timestamp> ctx) throws SQLException {
		this.delegate.set(ctx);
	}
	public final void get(BindingGetResultSetContext<Timestamp> ctx) throws SQLException {
		this.delegate.get(ctx);
	}
	public final void get(BindingGetStatementContext<Timestamp> ctx) throws SQLException {
		this.delegate.get(ctx);
	}
	public final void get(BindingGetSQLInputContext<Timestamp> ctx) throws SQLException {
		this.delegate.get(ctx);
	}
}

And the force type I've tested with:

<forcedType>
	<userType>java.sql.Timestamp</userType>
	<binding>[your.package.here].DateTimeCastBinding</binding>
	<expression>.*</expression>
	<types>DATETIME</types>
</forcedType>

Note that this is jooq 3.10.x format, newer versions have different expression and types keys.

**Comment by lukaseder** [comment]
Thanks a lot for documenting this here, @pacham7. I'm sure that will be very useful for others.
