### ISSUE TITLE
Feedback about manual section sqrt-function

### ISSUE THREAD

**Issue by tamaro-skaljic** [jOOQ/jOOQ#11930]
https://www.jooq.org/doc/3.14/manual/sql-building/column-expressions/numeric-functions/sqrt-function/
![image](https://user-images.githubusercontent.com/49238587/119998678-37ca3180-bfd1-11eb-900f-711e003e0d1e.png)

The  square root of 4 is not 4, it's 2.

**Comment by lukaseder** [comment]
Thanks a lot for your report! The fix will be released with the next nightly build.
