### ISSUE TITLE
Support translating DATEADD from Snowflake to BigQuery

### ISSUE THREAD

**Issue by PedrogFigueiredo** [jOOQ/jOOQ#11931]
### 

The ParserCli doesn’t work for dateadd from snowflake to bq, like that :
![image](https://user-images.githubusercontent.com/35741303/120254312-eedbdc80-c25f-11eb-8d9b-5756d7c67075.png)
and INTERVAL works but the results doesn’t  run on bq :
![image](https://user-images.githubusercontent.com/35741303/120254493-627de980-c260-11eb-9697-75b4bc6cf5d6.png)

### Versions:

- jOOQ:3.15 - snapshot
- Database (include vendor): SNOWFLAKE TO BQ

**Comment by lukaseder** [comment]
Thanks a lot for your report. These two should be an easy fix

**Comment by lukaseder** [comment]
The snowflake / parser part is fixed for the next nightly build of jOOQ 3.15.0-SNAPSHOT: https://github.com/jOOQ/jOOQ/issues/11938

**Comment by lukaseder** [comment]
The status quo of the ParserCLI shows that the examples given in the issue now work:

![image](https://user-images.githubusercontent.com/734593/120329363-11b3d280-c2ec-11eb-886b-4b76bd002eda.png)

(The unnecessary `interval 0 month` case stems from the input interval being a `YearToSecond` interval, something that will be improved independently of these two dialects).

I'm closing this issue

**Comment by lukaseder** [comment]
That `interval 0 month` case will be tracked separately, as https://github.com/jOOQ/jOOQ/issues/11939

**Comment by lukaseder** [comment]
Thanks again for your report. If you find any additional specific issues, please let us know and we can prioritise things accordingly.

**Comment by PedrogFigueiredo** [comment]
Amazing @lukaseder , thanks for your fast assistance. I'm working in a project using ParserCli. Anything I saw there I will let you know that.

**Comment by PedrogFigueiredo** [comment]
> The snowflake / parser part is fixed for the next nightly build of jOOQ 3.15.0-SNAPSHOT: #11938

So @lukaseder  Am I able to download this new version?

**Comment by lukaseder** [comment]
Yes, your extended trial license is still valid

**Comment by PedrogFigueiredo** [comment]
> Yes, your extended trial license is still valid

I mean with dateadd working, because on jOOQ-3.15.0-SNAPSHOT-20210530005129 is not yet right?

**Comment by lukaseder** [comment]
It's June 1, 2021 and the timestamp you referred to reads May 30, 2021, so no, that's not tomorrow's nightly build yet :)

**Comment by lukaseder** [comment]
A new build is available now, from https://www.jooq.org/download/versions.

In the meantime, have you had a chance to try the new `ParseListener` SPI that was added to jOOQ 3.15?
https://www.jooq.org/doc/dev/manual/sql-building/sql-parser/sql-parser-listener/

It will be very useful to quickly work around all of these issues in the future, too, where jOOQ currently lacks support for vendor-specific functions.
