### ISSUE TITLE
Manual section using-jooq-with-jdbctemplate shouldn't use deprecated JdbcTemplate method

### ISSUE THREAD

**Issue by ltsallas** [jOOQ/jOOQ#11936]
The jdbcTemplate query method in this example is deprecated in Spring v5.x in favor of its varargs equivelant. .

See https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#data-access-and-transactions

It can be replaced with the new one(switch second and third arguments). It won't make a big difference other than not seeing the deprecated strike-through fonts after coping the example code into your IDE which is a little bit confusing.

**Comment by lukaseder** [comment]
Thanks a lot for letting us know!

**Comment by lukaseder** [comment]
It relates to this change here: https://github.com/spring-projects/spring-framework/issues/25272. I can't say I approve of those changes in terms of API design. The `JdbcTemplate` methods are now rather inconsistent with respect to parameter ordering, the problem being, of course, that preparing a query and executing it should have been 2 different "steps" in the `JdbcTemplate` API, similar to jOOQ, which would greatly reduce the number of methods.

I'll suggest that to them.

**Comment by lukaseder** [comment]
Suggestion here: https://github.com/spring-projects/spring-framework/issues/25272#issuecomment-851905627

**Comment by lukaseder** [comment]
The new method call in the manual is now:

```java
JdbcTemplate template = new JdbcTemplate(dataSource);
List<AuthorAndBooks> result = template.query(
    query.getSQL(),
    (r, i) -> new AuthorAndBooks(
        r.getString(1),
        r.getString(2),
        r.getInt(3)
    ),
    query.getBindValues().toArray()
);
```

I really don't think this is an improvement by Spring. The two logically connected parameters (SQL string and binds) are now separated by a large, unrelated lambda. This is very unsettling...

**Comment by lukaseder** [comment]
Fixed in all manual versions. The fix will be deployed with the next build of the manual. Thanks again for your report!

**Comment by ltsallas** [comment]
Thanks for your actions and all the feedback!
