### ISSUE TITLE
100% CPU usage when using fetchStream()

### ISSUE THREAD

**Issue by ameti** [jOOQ/jOOQ#11946]
Hi,
I was wondering if 100% usage of CPU was normal when using fetchStream().
After the operation is done the CPU goes back to normal. I am using version 3.14.8

**Comment by lukaseder** [comment]
> I was wondering if 100% usage of CPU was normal when using fetchStream().

What's "normal" 😀

I'll be happy to look at a bug report with a profiling session attached (e.g. VisualVM export, etc.) and steps to reproduce.
