### ISSUE TITLE
BIGSERIAL column is no longer generates with default value

### ISSUE THREAD

**Issue by SButterfly** [jOOQ/jOOQ#11940]
### Expected behavior
```
create table schema.jooq_test_entity (
    id          bigserial primary key,
    description text,
    modified_date timestamp
);
```

Should generate code:
```
    public final TableField<JooqTestEntityRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('schema.jooq_test_entity_id_seq'::regclass)", org.jooq.impl.SQLDataType.BIGINT)), this, "");
```

### Actual behavior
Generates code
```
    public final TableField<JooqTestEntityRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");
```
Previously at version 3.13.2 it generated with default value.
My [jooq.txt](https://github.com/jOOQ/jOOQ/files/6577235/jooq.txt) you can find in attachments.

### Versions

- jOOQ: 3.14.11
- Java: 11
- Database (include vendor): postgres
- OS: macos
- JDBC Driver (include name if inofficial driver): postgresql-42.2.8.fix1

**Comment by lukaseder** [comment]
Thanks a lot for your message. This was improved as part of https://github.com/jOOQ/jOOQ/issues/10399, and in general the more recent PostgreSQL IDENTITY column support from 3.13: https://github.com/jOOQ/jOOQ/issues/6659.

In general, the specific implementation of PostgreSQL's `SERIAL` and `BIGSERIAL` types should be irrelevant and transparent to jOOQ. It was just a historic way of saying "this column is an identity". Why do you need that information present in the generated code? I.e. what made you assume this was a bug, not a feature? If you rely on the underlying sequence being documented, why not create one explicitly, of which you're in control?

**Comment by SButterfly** [comment]
Thanks for quick answer.
The goal of our code is to insert new rows and get new ids already filled in records:

If we insert values like this
```java
int[] result = dslContext.batchInsert(records).execute();
```
id wouldn't be set in records. So our team wrote hack code like this:
```java
fillIds(records);
int[] result = dslContext.batchInsert(records).execute();

protected void fillIds(List<TRecord> records) {
        List<Id> ids = generateIds(newRecordsNoIds.size());
        fillIds(records, ids);
    }

    protected List<Id> generateIds(int count) {
        return generateIds(count, idField, idField.getType());
    }

    protected <T> List<T> generateIds(int count, Field<T> field, Class<T> cls) {
        DataType<T> dataType = field.getDataType();
//        if (!dataType.defaulted()) { THIS IS NOT WORKING ANYMORE. defaulted RETURN FALSE
//            throw new IllegalStateException("id is not defaulted");
//        }

        // Not very honest, but still, select
       return trackSelect(dslContext.select(dataType.defaultValue())
            .from("generate_series(1, " + count + ")")
            .fetchInto(cls));
    }
```

After updating from 3.13.2 to 3.14.11 it stop working.

It would be much much better, if `batchInsert` also set generated ids directly into records. So we could remove our hack code.

**Comment by lukaseder** [comment]
I see, well, since you depended on the serial's underlying sequence, you might as well hard-wire the generated sequence name to your select from generate series (we have native support for that, btw, via `DSL.generateSeries()`!) Just change your `dataType.defaulted()` check by a `dataType.identity()` check and use some sequence expression. Alternatively, you can cache your default expression by looking at:

```sql
select column_default
from information_schema.columns
where ...
```

In any case, the issue that you would like to be fixed is this one here: https://github.com/jOOQ/jOOQ/issues/3327.

**Comment by SButterfly** [comment]
Is there any way I can get default value (in my case it's 'nextval('schema.jooq_test_entity_id_seq'::regclass)') without realtime requesting `information_schema.columns`?
I found `Sequences.JOOQ_TEST_ENTITY_ID_SEQ`, but there is no connection between `Table.JOOQ_TEST_ENTITY.ID` and that sequence.

**Comment by lukaseder** [comment]
> without realtime requesting `information_schema.columns`?

I mean, you can run this query once for all of your application and cache the results?

```sql
select table_schema, table_name, column_name, column_default
from information_schema.columns
where column_default = 'nextval(''' || table_name || '_' || column_name || '_seq''::regclass)' 
```

Or, again, you just hard-wire the serial default expression as above, as it can be reasonably expected that serial sequences follow this naming pattern.
