### ISSUE TITLE
Add Firebird 4.0 native support for DELETE .. ORDER BY and UPDATE .. ORDER BY

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#11944]
A recent version of Firebird seems to have added native support for `DELETE .. ORDER BY` and `UPDATE .. ORDER BY`. See e.g.
https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-dml-delete

**Comment by lukaseder** [comment]
Looking into this now. Will do this only for Firebird 4+

**Comment by mrotteveel** [comment]
Small note, ORDER BY on UPDATE/DELETE has been available since Firebird 2.0 (see the [Firebird 2.0.7 Release Notes](https://firebirdsql.org/file/documentation/release_notes/html/rlsnotes207.html#dml-dsql-extensions))

**Comment by lukaseder** [comment]
Thanks for your comment, @mrotteveel.

That may be the case, but I'm not adding more features for the old Firebird dialect support anymore, especially given how much better the documentation is for 4.0 and how few paying customers I'm aware of who are using the old dialects.
