### ISSUE TITLE
Missing brackets around subquery when using sqlTable

### ISSUE THREAD

**Issue by hylkevds** [jOOQ/jOOQ#11976]
When creating a "table" using `DSL.table(String sql);` and using this table as parameter to `from()` in a new query, there are no brackets around the subquery. See example below. Or am I misunderstanding how to use `DSL.table()`?

### Expected behavior
Correct brackets around a subquery when using DSL.table(String sql);
`select * from (select * from users where active = 1) "subQuery"`

### Actual behavior
No brackets:
`select * from select id,name from users where active=1 "subQuery"`

### Steps to reproduce the problem

```
    final String subQuery = "select id,name from users where active=1";
    Table<Record> sqlTable = DSL.table(subQuery);
    query = DSL.select(DSL.asterisk()).from(sqlTable.as("subQuery")).getSQL();
    LOGGER.info("Query: {}", query);
    // Query: select * from select id,name from users where active=1 "subQuery"
```

### Versions

- jOOQ: 3.14.8
- Java: 11
- Database (include vendor): None
- OS: Linux
- JDBC Driver (include name if inofficial driver): None

**Comment by lukaseder** [comment]
Thanks a lot for your report.

Unfortunately, we can't add those brackets to plain SQL `Table` instances, because the likelihood of that producing invalid syntax is quite high. A simple example in PostgreSQL:

```sql
-- Correct
select * from unnest(array[1])

-- Incorrect
select * from (unnest(array[1]))
```

Since you know what you're doing (and jOOQ doesn't), you'll have to add the brackets yourself.

**Comment by hylkevds** [comment]
Ok, it would be helpful if that was documented in the javadoc of DSL.table(String sql), since the exact example given there doesn't actually work.

**Comment by lukaseder** [comment]
Hah, yes. The example should have brackets, indeed. Thanks for pointing that out.
