### ISSUE TITLE
Generated enum from another module

### ISSUE THREAD

**Issue by sasq7** [jOOQ/jOOQ#12009]
### Your question:

Hi,
I have two Maven modules for two schemas(A and B).
Module A has a JOOQ generated enum.
Module B generates table that uses enum from module A.

How do I force JOOQ to generate column definition referencing enum from module A the same way as it would do for enum generated in module B?
`public final TableField<SomeRecordB, SomeEnumA> COLUMN_NAME_B = createField(DSL.name("column_name_b"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(SomeEnumA.class), this, "")`

### Versions:

- jOOQ: 3.14.4
- Java: 15
- Database (include vendor): PostgreSQL
- OS: Linux
- JDBC Driver (include name if inofficial driver): postgres

**Comment by lukaseder** [comment]
Ideally, you will not run two code generation runs but only one that generates code for both schemas. You could extract code generation to a third module S (for schema) and let both A and B depend on S.

Alternatively, you could define an auxiliary schema S in your database, where your enums reside, and generate A,S and B,S in each module.

I hope this helps
