### ISSUE TITLE
Support parsing HSQLDB post-fix IF EXISTS in DROP statements

### ISSUE THREAD

**Issue by jdsada30** [jOOQ/jOOQ#12013]
### SQL translator incorrectly translates this query:

```sql
DROP TABLE Tweet IF EXISTS; 
```
The above query fails to translate even though it is supported by [HSQLDB dialect](http://www.hsqldb.org/doc/1.8/guide/ch09.html#drop_table-section). This specific query comes from Github project [database-rider.](https://github.com/database-rider/database-rider)

**Comment by lukaseder** [comment]
Thanks a lot for your report. Makes sense. This legacy post-fix `IF EXISTS` syntax isn't just supported for `DROP TABLE` but for pretty much every statement:
http://hsqldb.org/doc/guide/databaseobjects-chapt.html#dbc_schema_def_statements

> This specific query comes from Github project [database-rider.](https://github.com/database-rider/database-rider)

A quick question about that. You seem to be testing the translator with a variety of products. What's your use-case here? Is there anything specific we can do to help you with your work?

**Comment by lukaseder** [comment]
Other statement types that support this "post-fix notation":

- [ ] `DROP SCHEMA`
- [ ] `DROP TABLE`
- [ ] `DROP VIEW`
- [ ] `DROP SEQUENCE`
- [ ] `DROP INDEX`

**Comment by lukaseder** [comment]
For consistency reasons, I'll also implement it for non-HSQLDB supported statements, like

- [ ] `DROP DATABASE`
- [ ] `DROP DOMAIN`
- [ ] `DROP TYPE`

And for these ones, where I can't seem to find the appropriate HSQLDB doc, or where the syntax isn't supported:

- [ ] `DROP FUNCTION`
- [ ] `DROP PROCEDURE`
- [ ] `DROP TRIGGER`

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0

**Comment by jdsada30** [comment]
> A quick question about that. You seem to be testing the translator with a variety of products. What's your use-case here? Is there anything specific we can do to help you with your work?

I'm a student at ETH Zürich and I'm currently working on extracting SQL test cases by recording SQL execution traces from GitHub projects for my Master's thesis (with @mrigger). I aim to evaluate the usefulness of this test suite by executing it with various tools, including jOOQ. Do you think these feature requests (and the test suite) are useful, or should I stop reporting these unsupported features?

**Comment by lukaseder** [comment]
> with @mrigger

Say hi to him! 😀

> Do you think these feature requests (and the test suite) are useful, or should I stop reporting these unsupported features?

They are *very useful*, thank you very much. Is that test suite going to be published as open source? If not, is it for sale?

**Comment by jdsada30** [comment]
> They are _very useful_, thank you very much. Is that test suite going to be published as open source? If not, is it for sale?

That's great to hear! Yes, we plan to make it available as open source soon.

**Comment by lukaseder** [comment]
> Yes, we plan to make it available as open source soon.

Excellent! Anywhere I can subscribe to to get the news?

**Comment by jdsada30** [comment]
> Excellent! Anywhere I can subscribe to to get the news?
I'll make a note to let you know as soon as we release it.
