### ISSUE TITLE
JSONB equals, hashCode, toString() should be formatting agnostic

### ISSUE THREAD

**Issue by pennstatephil** [jOOQ/jOOQ#12023]
### Use case:
Sometimes, I am comparing JSONB objects that can look `{"like":"this"}` or `{"like": "this"}` -- I want these to be "equal" since the space after the colon does not matter functionally.

### Possible solution you'd like to see:
JSONB's "equals" method should account for this, maybe by replacing `\": ` with `\":`

### Possible workarounds:
Make sure all JSONB objects are formatted the same

**Comment by lukaseder** [comment]
Thanks a lot for your feature request. I agree that this could be interesting for some use-cases, but it's a slippery slope.

1. If we do this for `JSONB` objects, then we should do it for `JSON` and `XML` objects as well
2. It's far more than just replacing simple string tokens, such as `": ` by `":`. The lexical order of attributes is also irrelevant, e.g. these are equal (in PostgreSQL): `{"a": 1, "b": 1}` and `{"b":1,"a":1}`
3. What does "equal XML" mean? Should we be namespace aware and treat differing namespace prefixes as equal if they point to the same URI?
4. What about whitespace in XML? Document oriented XML is whitespace sensitive. Data oriented XML is usually whitespace agnostic

Meaning, we would have to parse the strings and cache an object representation of the `JSONB` / `JSON` / `XML` content for usage in `equals()` and `hashCode()`. For good measure, the `toString()` representation should also produce the "normalised", parsed version of `JSONB` content, such that `jsonb("[1]").toString().equals(jsonb("[ 1 ]").toString())`

Nothing impossible, but I'd love to understand use-cases first, here. Why is it important to you?

**Comment by liununu** [comment]
We also have the same use case, and find one workaround. Maybe it could help you @pennstatephil 

1. Call  `JSONB`’s `data()` method to get the JSON String
2. Since we use `Jackson`, we read the above JSON String as `JsonNode`
3. Use the comparison method of `JsonNode`

**Comment by lukaseder** [comment]
Thanks, @liununu. That would be one option. We have our own parser in `org.jooq.tools.json`, so that's definitely doable. But I'd still love to better understand the use-case of using `JSONB` comparisons like that.

**Comment by liununu** [comment]
> Thanks, @liununu. That would be one option. We have our own parser in `org.jooq.tools.json`, so that's definitely doable. But I'd still love to better understand the use-case of using `JSONB` comparisons like that.

In our usage scenario, we need to compare the two `JSONB`s to determine that if we need to do the `update` operation on the table.

**Comment by lukaseder** [comment]
Oh, I see. To prevent a server roundtrip, then. Makes sense.

**Comment by pennstatephil** [comment]
Wow, thank you for all the activity on this. My primary use case is integration testing-- I make sure the object containing the json field returned from the server matches my expectation. I use either `equals` or `containsAll` for collections, which invokes `equals`. 

Googling around a bit, a good implementation may be to use Jackson to read the json strings and test them for equality, which not only solves the "space after colon" issue, but also the ordering issue. This solution would also work for plain old JSON, but probably need something similar for XML. Again, a quick search suggests XMLUnit might be the tool for that job.

**Comment by lukaseder** [comment]
Thanks again for your feedback about use-cases, also @pennstatephil. That makes a lot of sense. The workarounds are documented now, it's easy to delegate this to some other tooling, but I agree it would be very convenient if jOOQ's `JSONB` type could handle these common API methods more like PostgreSQL.

Giving this some additional thought, I don't think that the `org.jooq.JSON` or `org.jooq.XML` types need to be adapted. They are white space and order sensitive, unlike `JSONB`, so they should really continue to compare the string values.

**Comment by lukaseder** [comment]
This improvement has produced an important regression when storing `jsonb("\"abc\"")`

**Comment by lukaseder** [comment]
Will add more Javadoc documentation about this:

- https://github.com/jOOQ/jOOQ/issues/14953

Possibly also worth implementing a new normalisation algorithm:

- https://github.com/jOOQ/jOOQ/issues/14954

**Comment by lukaseder** [comment]
More regressions:

- https://github.com/jOOQ/jOOQ/issues/15751
- https://github.com/jOOQ/jOOQ/issues/15752

Most of these were caused by making `toString()` formatting agnostic as well. This wasn't requested at the time, only for `equals()` and `hashCode()` to be formatting agnostic.

I suspect that we can revert the `toString()` part
