### ISSUE TITLE
Wrong comment in manual meta section about the manual

### ISSUE THREAD

**Issue by loelindstrom** [jOOQ/jOOQ#12054]
![typo](https://user-images.githubusercontent.com/61005422/123227277-b92fb980-d4d4-11eb-8b29-41fe272e35e1.png)

In the second code block below the header "Code block contents" I think the second "com.example.generated.Tables.BOOK.TITLE" should be "com.example.generated.Tables.AUTHOR.LAST_NAME"

[https://www.jooq.org/doc/3.15/manual/getting-started/the-manual/](https://www.jooq.org/doc/3.15/manual/getting-started/the-manual/)

**Comment by lukaseder** [comment]
Yes of course, thank you very much!

**Comment by lukaseder** [comment]
Fixed. The manual will be re-published with the fix later today.
