### ISSUE TITLE
Improve XML path notation in section jooq-in-7-steps-step3

### ISSUE THREAD

**Issue by loelindstrom** [jOOQ/jOOQ#12061]
![manual section jooq-in-7-steps-step3](https://user-images.githubusercontent.com/61005422/123253657-fbb1c000-d4ed-11eb-825e-9be5cc87bfe5.png)

> Replace the username with whatever user has the appropriate privileges to query the database meta data. You'll also want to look at the other values and replace as necessary. Here are the two interesting properties:
> 
> `generator.target.package` - set this to the parent package you want to create for the generated classes. The setting of `test.generated` will cause the `test.generated.Author` and `test.generated.AuthorRecord` to be created
> 
> `generator.target.directory` - the directory to output to.
> 
> Once you have the JAR files and library.xml in your temp directory, type this on a Windows machine:
[https://www.jooq.org/doc/3.15/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step3/](https://www.jooq.org/doc/3.15/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step3/)

### Feedback
I, as a first time, user was a little confused by this part in relation to the code block. (One of the elements is "packageName" in code block but "package" in text (if i understood it all correctly).)
Perhaps re-word it to the following (changes in bold) or perhaps pick out the code blocks that are necessary and highlight:

> Replace the username (**`<user>`**) with whatever user has the appropriate privileges to query the database meta data. You'll also want to look at the other values and replace as necessary. Here are the two interesting properties:
> 
> **`<generator>.<target>.<packageName>`**  
>- set this to the parent package you want to create for the generated classes. **Setting the value to** `test.generated` will cause the `test.generated.Author` and `test.generated.AuthorRecord` **classes to be created**.
> 
> **`<generator>.<target>.<directory>`**
> - the directory to output **the generated classes to**.
> 
> Once you have the JAR files and library.xml in your temp directory, type this on a Windows machine:

**Comment by lukaseder** [comment]
Thanks a lot for the feedback. There are a few things here:

- Yes, it should clearly be `packageName` not `package`
- The "dot notation" is a bit weird. Perhaps a "path notation" (as would be done with XPath) would be better?, i.e. `configuration/generator/target/packageName
- I agree with your improved wording highlighted in bold

**Comment by lukaseder** [comment]
Fixed. The improvement will be deployed in a few hours.

Thanks again for your feedback. If you find any other things that you think are confusing for first time users, please do create new issues. I'd love to hear them!
