### ISSUE TITLE
Type character varying(255) in non-recursive term but type character varying overall

### ISSUE THREAD

**Issue by esfomeado** [jOOQ/jOOQ#12067]
### Expected behavior

Should work as stated on example.

### Actual behavior

ERROR: recursive query "t" column 3 has type character varying(255) in non-recursive term but type character varying overall

### Steps to reproduce the problem

- Instead of VARCHAR(50) use character varying(255) for the  label data type.
- Run the example located here: https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/with-recursive-clause/

### Versions

- jOOQ: 3.14.11
- Java: 1.8.0_292
- Database (include vendor): Postgres 10.6
- OS: Windows 10
- JDBC Driver (include name if unofficial driver): https://mvnrepository.com/artifact/org.postgresql/postgresql/42.2.22

**Comment by lukaseder** [comment]
Thanks for your report. That's quite the silly limitation of PostgreSQL, it seems. There's no reason for this not to work as the `varchar` type should be widened automatically.

The workaround is to cast columns explicitly. E.g. this could be done:

```java
CommonTableExpression<?> cte = name("t").fields(
  "id",
  "name",
  "path"
).as(
  select(
    DIRECTORY.ID,
    DIRECTORY.LABEL,
    DIRECTORY.LABEL.cast(VARCHAR(255)) // ... cast here (!)
  .from(DIRECTORY)
  .where(DIRECTORY.PARENT_ID.isNull())
  .unionAll(
  select(
    DIRECTORY.ID,
    DIRECTORY.LABEL,
    field(name("t", "path"), VARCHAR)
      .concat("\\")
      .concat(DIRECTORY.LABEL).cast(VARCHAR(255)) // ... and here
  .from(table(name("t")))
  .join(DIRECTORY)
  .on(field(name("t", "id"), INTEGER)
    .eq(DIRECTORY.PARENT_ID)))
);

System.out.println(
    create().withRecursive(cte)
            .selectFrom(cte)
            .fetch()
);
```

**Comment by lukaseder** [comment]
Alternatively, use `TEXT` instead of `VARCHAR` in the table declaration.

jOOQ could auto-cast things here to "make it work", but that's always risky as well, especially if casting results in truncation of data. I think I'll just add a comment to the example to hint at using the `TEXT` type in PostgreSQL for the sake of the example.

I don't think jOOQ can do much else here.

**Comment by lukaseder** [comment]
I've updated the manual. The improvement will be deployed soon, today. Thanks again for your report!
