### ISSUE TITLE
PostgreSQL index expression

### ISSUE THREAD

**Issue by sasq7** [jOOQ/jOOQ#12060]
Hello, 

Is it possible to create index expression eg. `(column IS NULL)` from JOOQ dsl that would return Field type?
I need to fill in:
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/InsertQuery.html#onConflict(org.jooq.Field...)

**Comment by lukaseder** [comment]
Sure, just wrap your `Condition` in a `Field<Boolean>` by using `DSL.field(Condition)`. If that doesn't work, you can always resort to using plain SQL templating: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

I hope this helps.
