### ISSUE TITLE
Support translating MySQL boolean as integer comparisons

### ISSUE THREAD

**Issue by OmarBello** [jOOQ/jOOQ#12077]
### SQL translator incorrectly translates this query:

```sql
case
    when payment_type = (cavfy - capfym) > 0 then 'constant' else 'linear'
end as payment_type_omar
```

### Parser output:

```sql
Keyword 'THEN' expected: [2:42] case
    when payment_type = (cavfy - capfym) [*]> 0 then 'constant' else 'linear'
end as payment_type_omar
```

**Comment by lukaseder** [comment]
Thanks a lot for your report. What's the input dialect for your SQL? Also, what's the purpose of this `> 0` predicate? I'm assuming the input dialect is MySQL, which treats booleans like integers, in case of which the `> 0` seems superfluous

**Comment by lukaseder** [comment]
Emulating MySQL's boolean as integer semantics is not trivial. We might eventually tackle this problem but for now, I'll reject this issue as I'm afraid this will evolve into quite the can of worms with tons of edge cases.

The assumption being that most SQL queries that jOOQ is asked to translate don't make use of this dubious MySQL feature.
