### ISSUE TITLE
MySQL queries running GROUP_CONCAT() or JSON_ARRAYAGG() should auto-increase the default group_concat_max_len

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12092]
MySQL has a default value for `group_concat_max_len` of `1024`, which isn't all that much, especially when emulating `MULTISET` using JSON. We should increase the value to something much bigger, e.g.

```sql
set @t = @@group_concat_max_len;
set @@group_concat_max_len = 4294967295;
select (
  select coalesce(
    json_merge_preserve('[]', concat(
      '[',
      group_concat(json_object(
        'f1', `t`.`f1`,
        'f2', `t`.`f2`,
        'f3', `t`.`f3`,
        'f4', `t`.`f4`,
        'f5', `t`.`f5`,
        'f6', `t`.`f6`,
        'f7', `t`.`f7`
      ) separator ','),
      ']'
    )),
    json_array()
  )
  from (
    select
      `b1`.`ID` as `f1`,
      `b2`.`ID` as `f2`,
      `b3`.`ID` as `f3`,
      `b4`.`ID` as `f4`,
      `b5`.`ID` as `f5`,
      `b6`.`ID` as `f6`,
      `b7`.`ID` as `f7`
    from `test`.`t_book` as `b1`, `test`.`t_book` as `b2`, `test`.`t_book` as `b3`, `test`.`t_book` as `b4`, `test`.`t_book` as `b5`, `test`.`t_book` as `b6`, `test`.`t_book` as `b7`
  ) as `t`
);
set @@group_concat_max_len = @t;
```

This should be done whenever we run a `GROUP_CONCAT` query. Given that the aggregated value is silently truncated (as opposed to Oracle/DB2, which raise an error), the result is simply wrong.

**Comment by lukaseder** [comment]
A new `Settings.renderGroupConcatMaxLenSessionVariable` flag will allow for opting out of this

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.15.0

**Comment by lukaseder** [comment]
The current implementation produces 3 such `SET` calls *per `GROUP_CONCAT`* function call! We must generate these things only once.

**Comment by lukaseder** [comment]
This feature depends on `allowMultiQueries=true`, which may not be activated. We'll work around this somehow: https://github.com/jOOQ/jOOQ/issues/12119

**Comment by lukaseder** [comment]
This emulation relies on `allowMultiQueries=true`, see this blog post here: https://blog.jooq.org/mysqls-allowmultiqueries-flag-with-jdbc-and-jooq

I currently don't see any other way to work around this (short of using native `JSON_ARRAYAGG()`, of course)

**Comment by lukaseder** [comment]
> It seems this feature has broken the use of `MockFileDatabase` with queries containing `group_concat()`.

Every feature will always break the use of `MockFileDatabase`

> Do you have any suggestions or workarounds?

That would very much depend on your usage of `MockFileDatabase` and expectations, etc. You can turn off the feature with the flat documented here:
https://github.com/jOOQ/jOOQ/issues/12092#issuecomment-872194210

**Comment by norrisjeremy** [comment]
> > It seems this feature has broken the use of `MockFileDatabase` with queries containing `group_concat()`.
> 
> Every feature will always break the use of `MockFileDatabase`
> 
> > Do you have any suggestions or workarounds?
> 
> That would very much depend on your usage of `MockFileDatabase` and expectations, etc. You can turn off the feature with the flat documented here:
> [#12092 (comment)](https://github.com/jOOQ/jOOQ/issues/12092#issuecomment-872194210)

Arrgh, my apologies, I did not catch that there was a Settings flag to disable this.

**Comment by lukaseder** [comment]
No worries :)

**Comment by lukaseder** [comment]
The flag isn't documented yet, see: https://github.com/jOOQ/jOOQ/issues/14511
