### ISSUE TITLE
Batch requests intermittently cause ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by royaldark** [jOOQ/jOOQ#12112]
### Expected behavior

Batch requests created using `context.batch(List<Query>).execute()` execute successfully.

### Actual behavior

While executing a large number of batch queries, an ArrayIndexOutOfBoundsException is sometimes thrown. Certain batch requests always cause the exception, even though all queries within the batch requests are of the same form and each query can be executed individually (non-batched) without error.

Using a different batch size causes the exception to occur with different requests -- it is not a single specific query that causes the exception. For example, when I group the queries in batches of 20, the error always occurs on batch #287 (queries #5720-5739). But if I group the queries in batches of 19, it always happens on batch #513 (queries #9728-9746). With batch size 21, it always happens on batch #537 (queries #11256-11276).

All queries within the batches are generated with Jooq, using codegen'd records:

```kt
context.insertInto(table)
    .set(record)
    .onDuplicateKeyUpdate()
    .set(record)
```

Not sure if relevant, but one of the fields in the record is a geometry function, not a literal:

```kt
return MyCodegenRecord().apply {
    id = featureId
    geom = DSL.field("ST_GeomFromGeoJson(?)", featureGeoJson)
}
```

And each batch requests is executed using `context.batch(queries).execute()`.

Stack trace (with example batch size 20):

```
java.lang.ArrayIndexOutOfBoundsException: 20
	at org.jooq_3.12.3.MYSQL.debug(Unknown Source)
	at com.mysql.cj.jdbc.StatementImpl.processMultiCountsAndKeys(StatementImpl.java:1089)
	at com.mysql.cj.jdbc.StatementImpl.executeBatchUsingMultiQueries(StatementImpl.java:1042)
	at com.mysql.cj.jdbc.StatementImpl.executeBatchInternal(StatementImpl.java:859)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:814)
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:112)
	at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:112)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:104)
	at org.jooq.impl.BatchMultiple.execute(BatchMultiple.java:75)
```

### Steps to reproduce the problem

- If the problem relates to code generation, please post your code generation configuration
- If the problem relates to upgrades, please check if your RDBMS version is still supported by jOOQ: https://www.jooq.org/download/support-matrix
- A complete set of DDL statements can help re-create the setup you're having
- An MCVE can be helpful to provide a complete reproduction case: https://github.com/jOOQ/jOOQ-mcve

I'm not sure how to create a consistent reproduction that I can publish since the data in the queries is under licensing restrictions. 

### Versions

- jOOQ: 3.12.3
- Java: 8
- Database (include vendor): MySQL 5.7
- OS: OS X
- JDBC Driver (include name if inofficial driver): mysql-connector-java 8.0.16

**Comment by lukaseder** [comment]
Thanks for your report.

This looks like https://bugs.mysql.com/bug.php?id=101054. Can you please confirm? I doubt that this issue is a jOOQ bug, given the AIOOBE originates from within the JDBC driver.

**Comment by royaldark** [comment]
Yep, that looks like the real issue - increasing `max_allowed_packet` fixed it.

Thanks for the help!
