### ISSUE TITLE
Regression when binding JSONB value containing a JSONB string in PostgreSQL

### ISSUE THREAD

**Issue by schmist** [jOOQ/jOOQ#12144]
### Expected behavior

The **content** of a string should be preserved when using it as jsonb value, including double quotes.

### Actual behavior

Given a string with the following **content**: `"foo"` (double quotes are also part of the string). This is also valid json, but only if the double quotes are part of the string.

Generating a query that contains such a string as jsonb value leads to the following output (partial):

`... cast('foo' as jsonb)) ...`

Since the double quotes are now missing, this is not valid json anymore and will lead to a database error.

This issue appeared with version `3.15.0`, with previous versions, the query was generated correctly:

`... cast('"foo"' as jsonb)) ...`

### Steps to reproduce the problem

Generate a query (default generator) with a simple string wrapped in double quotes as a jsonb value using e.g. `JSONB.valueOf(...)`.

### Versions

- jOOQ: 3.15.0
- Java: AdoptOpenJDK-11.0.11+9
- Database (include vendor): Postgres 11.10
- OS: Linux
- JDBC Driver: org.postgresql:postgresql: 42.2.23

**Comment by lukaseder** [comment]
Thanks for your report.

> Generate a query (default generator) with a simple string wrapped in double quotes as a jsonb value using e.g. `JSONB.valueOf(...)`.

Can you please show the actual code you wrote

**Comment by schmist** [comment]
Here a minimal example that leads to the same issue:

Kotlin Code:

```
fun main() {
    val query: Query = DefaultDSLContext(SQLDialect.POSTGRES)
        .insertInto(DATA)
        .set(DATA.newRecord().apply { entry = JSONB.valueOf("\"foo\"") })
    println(query.getSQL(ParamType.INLINED))
}
```

Schema:

```
CREATE TABLE data (
	id SERIAL PRIMARY KEY,
	entry JSONB
);
```

**Comment by lukaseder** [comment]
Thanks. Might be a regression introduced by https://github.com/jOOQ/jOOQ/issues/12023

**Comment by lukaseder** [comment]
I can reproduce this. Will look into fixing this and patching to 3.15.1 immediately. The issue affects only `JSONB`, not `JSON`. As a workaround, `JSON` could be used and cast to `JSONB`...

**Comment by lukaseder** [comment]
OK, there are two problems:

- There's a wrong implementation in the `JSONB.toString()` method. We just call `object.toString()` on the parsed object, rather than serialising it again
- We shouldn't bind `JSONB.toString()`, but `JSONB.data()` instead

I'll fix both of these issues

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.1 (https://github.com/jOOQ/jOOQ/issues/12145). 3.15.1 will ship early next week. Thanks again for your report!

**Comment by lukaseder** [comment]
It appears that this fix only addressed the bind variables bound to JDBC, not the inlined rendering, which I'll fix now as well:

https://github.com/jOOQ/jOOQ/issues/15752

**Comment by lukaseder** [comment]
Related problem:

- https://github.com/jOOQ/jOOQ/issues/17579
