### ISSUE TITLE
Using bulk insert or `values` with record classes

### ISSUE THREAD

**Issue by devslash-paul** [jOOQ/jOOQ#12175]
### How can you use `values` to insert multiple code-generated records without manual translation?

When writing statements of the form

```sql
INSERT INTO x(a,b,c)
VALUES (1,2,3),
               (4,5,6),
                (7,8,9);
```

It's often ergonomic to be able to handle the auto generated Records on the repository method that calls it.

The [DSLContext.batchInsert](https://www.jooq.org/javadoc/dev/org.jooq/org/jooq/DSLContext.html#batchInsert(java.util.Collection)) method works for the base case, but in a more complex case such as the following, the `Batch` object returned by `batchInsert` does not allow for extension.

```sql
INSERT INTO x(a,b,c)
VALUES (1,2,3),
               (4,5,6),
                (7,8,9)
ON DUPLICATE KEY ....
```

To work around this, one can do something like 

```java
private Object[] getValues(ExampleTableRecord record) {
    var fields = Tables.EXAMPLE_TABLE.fields();
    int fieldLength = fields.length;
    var insertValues = new Object[fieldLength];
    for (var i = 0; i < fieldLength; i++) {
      insertValues[i] = record.changed(fields[i]) ? record.get(fields[i]) : defaultValue(fields[i]);
    }
    return insertValues;
}

public void insertBatchComplex(List<ExampleTableRecord> records) {
   var inserts = txn.ctx().insertInto(Tables.EXAMPLE_TABLE);
   InsertValuesStepN<ExampleTableRecord> intermediate = null;
   for(var record: records) {
     intermediate = inserts.values(getValues(record));
   }
  
  intermediate.onDuplicateKeyUpdate()
     .set(....)
    .execute()
}
```

This feels odd, yet setting I cannot locate a way to use the ExampleTableRecord in the `values` step without the field conversions done in `getValues()`. If there is one, it would be a very useful example to place on [this doc page]?(https://www.jooq.org/doc/3.2/manual/sql-building/sql-statements/insert-statement/insert-values/#N93554)

### Versions:

- jOOQ: 3.14.12
- Java: 11
- Database (include vendor): MySQL 8 (RDS)

**Comment by lukaseder** [comment]
Starting from jOOQ 3.15, please use `insertInto(...).columns(...).valuesOfRecords(...)`, see also https://github.com/jOOQ/jOOQ/issues/6604. Agreed, that deserves an example in the docs!

**Comment by pault-t-canva** [comment]
Amazing. Thanks! 🏗️
