### ISSUE TITLE
Consider removing DefaultCloseableConnectionProvider::finalize override

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12178]
`Object.finalize()` has been deprecated in Java 9. It might be better to just delete the logic entirely. Users should use the `DefaultCloseableDSLContext` as an `AutoCloseable` resource:

```java
try (CloseableDSLContext ctx = DSL.using(url, username, password)) {
  ...
}
```

**Comment by o-shevchenko** [comment]
What is the recommended way of creating CloseableDSLContext in Kotlin? Is it supported? I see only examples for Java for try-with-resources
