### ISSUE TITLE
Mono/Flux Manual Transaction Control

### ISSUE THREAD

**Issue by driverpt** [jOOQ/jOOQ#12219]
### Your question:

Is it possible to do manual Transaction Commit and Rollback for Reactive Approach?

e.g.:

```
public Flux<SomeClass> process(final List<SomeClass> items) {
    Mono<Transaction> transactionMono = Mono.fromCompletionStage(context.startTransaction()).cache();
    
    return Flux.fromIterable(elements)
      .zipWith(transactionMono.repeat())
      .flatMap((element, transaction) ->
        /* Persist */
      )
      .collectList()
      .zipWith(transactionMono.repeat())
      .flatMap((elements, transaction) -> {
        transaction.commit();
        return elements
      })
      .flatMapIterable(Function.identity())
      .onErrorResume(throwable ->
        transactionMono
           .map(transaction -> transaction.rollback())
           .flatMap(Mono.error(new TransactionRollbackException()))
        );
}
```

Caveat: The Persist Methods (Update, Delete and Insert) all use `Mono<? extends UpdatableRecord>`, this way it would allow us to manually control the transaction via declarative API.

Thanks

### Versions:

- jOOQ: 3.14.11 (Spring Boot)
- Java: 11
- Database (include vendor): Postgres 10+
- OS: N/A
- JDBC Driver (include name if inofficial driver): Postgres Official Driver

**Comment by lukaseder** [comment]
Thanks a lot for your message. Yes, it's possible to use R2DBC's transaction API if that's what you mean by "manual commit and rollback". But I fear this isn't your actual question...? Would you mind clarifying?

**Comment by driverpt** [comment]
Thanks for the quick response. What we wanted was fine-grained control over the transaction, since we use Spring Boot but do not rely on annotations to control the transaction.

Our code is fully reactive on all layers, so the CRUD methods return Mono/Flux. From what i've understood if we return a `Mono` inside a transaction but subscribe after the transaction has ended, it will end up in Exception, right ?

**Comment by lukaseder** [comment]
> Our code is fully reactive on all layers, so the CRUD methods return Mono/Flux. From what i've understood if we return a `Mono` inside a transaction but subscribe after the transaction has ended, it will end up in Exception, right ?

Sorry, I haven't investigated how Spring's reactive transactions work yet.

> P.S.: We do not use R2DBC yet

How can your code be fully reactive if you're not using R2DBC yet? You're still blocking on the database calls?

I recommend you do use it, though, and use R2DBC's programmatic transaction API if you don't want to use Spring's annotations. That way, you're in full control, and the previous question will resolve itself, because the transaction demarcation happens within a Mono/Flux at a precise moment in the stream.

**Comment by lukaseder** [comment]
I'm closing this for now as an "answered support request". There may be room for improvement in the future, but I don't see how jOOQ and Spring could integrate any better at this point. We'll first offer our own explicit, reactive transaction API that works on R2DBC directly, not on Spring. It will have an SPI to override the defaults, but that's out of scope for now.

**Comment by driverpt** [comment]
Ok, if it's not implemented yet. Can you please transform this into a feature request of returning some sort of `TransactionHandler` when you start a transaction, so you can have fine-grained transaction control?

Similar to what's being done by RDS Data Api: https://docs.aws.amazon.com/rdsdataservice/latest/APIReference/API_BeginTransaction.html

**Comment by lukaseder** [comment]
> Can you please transform this into a feature request of returning some sort of `TransactionHandler` when you start a transaction, so you can have fine-grained transaction control?

I could, but it wouldn't really be useful, because without doing the exercise of thinking very thoroughly about how all of this should work in jOOQ, this issue here won't be of much help...
