### ISSUE TITLE
Is there a way to perform conversion at db side?

### ISSUE THREAD

**Issue by Nhoutain** [jOOQ/jOOQ#12213]
### Your question:

Hi,

I try to perform some column conversion at DB side, but I can't find something that match my requirement.

Firstly, I see the `Converter` interface which allow to perform conversion between the DB type and a java type - meaning that we can't perform conversion when fetch the data.

Currently, I have some expression which are converted to DB expression - in order to be computed at DB side and enjoy some optimization out of the box. My issue is that, I want to have an expression (let say `select (a::integer + b::integer) from table` where `a` is a column of text.

When I have a `Field<String>`, I don't find a way to ask conversion to the DB through JOOQ - I can perform a `cast` but it's really not a DB conversion.

So, as an ultimate try, I ask you if you see any way to achieve this..
The backup solution is to move the expression computation at java side and avoid a conversion.. but I can't enjoy the DB API benefit

Before asking your question, please check out the FAQ too: https://www.jooq.org/faq

### Versions:

- jOOQ: 3.13.6
- Java: 8
- Database (include vendor): Postgresql
- OS: UNIX
- JDBC Driver (include name if inofficial driver): 5.2.15

**Comment by lukaseder** [comment]
A more far fetched SPI than the `Converter` is the `Binding` as documented here: https://www.jooq.org/doc/latest/manual/sql-building/queryparts/custom-bindings/

It will allow you to influence how your bind variable is generated (e.g. to add casts or function calls, such as `cast(? as type)` or `f(?)`), which affects the way you write to the database, as well as specify how jOOQ binds your variable to a JDBC `PreparedStatement` or reads it from a JDBC `ResultSet`.

There's no true "server side converter" yet (see https://github.com/jOOQ/jOOQ/issues/8842), though maybe, if you can show your *actual* requirement (instead of a simplified one), there might be a solution I could provide you with, or the above data type binding feature suffices.

**Comment by Nhoutain** [comment]
Firstly, thanks to be so reactive :) 

As I say, the binding is perform between the db object and the user object, which is not what I search.

I can show more in detail my actual requirement with a quite simple example. 
Firstly, I have a field like
```
Field field = DSL.field(DSL.name("textColumn"), JSQLDataType.VARCHAR(10000))
```

I know that these column contains values like "1", "2", "3".

So, I want to multiply this column by itself with a jooq API like 
```
Field multiplyField = field.multiply(field)
```

But, before perform this operation, I need to perform a DB side conversion of `field` to convert it to a `SQLDataType.NUMERIC(19, 5)`, otherwise we can't multiply varchar.

---

Of course, I have some more complexe example in a more complexe expression engine, but that's the idea.

* I can't use the `Binding` idea, because I need to have conversion inside the DB expression
* An alternative way is to perform the expression computation AFTER fetch the data, but it's more elegant, easy and efficient to delegate the computation to the DB server.

**Comment by lukaseder** [comment]
> As I say, the binding is perform between the db object and the user object, which is not what I search.

Not necessarily. The binding can affect the generated SQL string, which can at least perform conversions on the server side when writing to the database, though not when reading.

Anyway. jOOQ supports SQL `CAST`: https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/cast-expressions/, and if you need some vendor specific functionality, just write a plain SQL template: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

E.g.

```java
// Not cast
public static <T> Field<T> convert(Field<?> field, DataType<T> type) {
    // Possibly write your own way to render type, rather than using
    // the out-of-the-box SQL generation of DataType
    return DSL.field("my_convert({0}, {1})", type, field, type);
}
```
