### ISSUE TITLE
Leverage Parser to add a qualifier inside an expression

### ISSUE THREAD

**Issue by jdimeo** [jOOQ/jOOQ#12215]
### Your question:

I'm writing a SQL view code generator and using JOOQ to help! If someone tells me that a column should be defined as an expression but I know that, because I'm generating a view that requires a join and ambiguous columns, I need to go qualify all column references, can the JOOQ parser help me do that?

For example, I want a function that takes:
`CASE WHEN LASTMODIFIEDDATE > SYSTEMMODTIMETSAMP THEN LASTMODIFIEDDATE ELSE SYSTEMMODTIMETSAMP END` and an alias "a" as input and returns
`CASE WHEN a.LASTMODIFIEDDATE > a.SYSTEMMODTIMETSAMP THEN a.LASTMODIFIEDDATE ELSE a.SYSTEMMODTIMETSAMP END` 

or even
`CASE WHEN b.LASTMODIFIEDDATE > SYSTEMMODTIMETSAMP THEN b.LASTMODIFIEDDATE ELSE SYSTEMMODTIMETSAMP END`  with alias for "a" when otherwise unqualified returns
`CASE WHEN b.LASTMODIFIEDDATE > a.SYSTEMMODTIMETSAMP THEN b.LASTMODIFIEDDATE ELSE a.SYSTEMMODTIMETSAMP END` 

This is as far as I got:
```
val select = DSL.using(SQLDialect.DEFAULT).parser().parseSelect("SELECT " + column + " FROM " + alias);
val f = select.field(0);
```
to "trick" JOOQ into parsing it as a select query, but the field's name is just "case". 

Another option would be to leverage a listener mechanism to `Parser` so that I can provide some callback each time the parser hits a column reference while parsing the expression.

Is this possible?

### Versions:

- jOOQ: 3.14.11
- Java:
- Database (include vendor): General/default dialect
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
We can do that out of the box for you. You can try it online: https://www.jooq.org/translate. Using this schema:

```sql
create table t (a int);
create table u (b int);
```

And parsing this query:

```sql
select a, b from t, u
```

You'll get only qualified identifiers:

```sql
select
  T.A,
  U.B
from T, U
```

See 

![image](https://user-images.githubusercontent.com/734593/126283624-e0e62692-c77e-4f1c-889e-97378399beb2.png)

Programmatically, you will want to enable `Settings.parseWithMetaLookups` and then use a `MetaProvider` of your choice.

Does this answer your question?

**Comment by jdimeo** [comment]
Sorry for not following up sooner. It kinda does and kinda doesn't. The problem is that I don't necessarily know the schema of the tables a priori. I was hoping the JOOQ parser, just from parsing the SQL, would be able to identify variables that are candidates for qualification vs. functions/expressions vs. SQL keywords ... apart from any concrete schema. I found a workaround for my needs in the meantime. I'll remember the `MetaProvider` hook for the future though thank you!
