### ISSUE TITLE
Unnecessary generic type parameter in localDateAdd and other date time arithmetic functions

### ISSUE THREAD

**Issue by tho-graf** [jOOQ/jOOQ#12212]
### Your question:
While migrating from 3.13.2 to 3.15.1 I had to add a generic to localDateAdd. But the generic isn't used at all? Should the generic be removed?

Cheers!

```
 @NotNull
    @Support
    public static <T> Field<LocalDate> localDateAdd(LocalDate date, Number interval, DatePart datePart) {
        return new DateAdd(Tools.field(date), Tools.field(interval), datePart);
    }
```

Before asking your question, please check out the FAQ too: https://www.jooq.org/faq

### Versions:

- jOOQ: 3.15.1
- kotlin: 1.5.0

**Comment by lukaseder** [comment]
Thanks a lot for your report. That does seem like an artefact produced by our new DSL API generator, which makes no sense in this case, because the `T` type variable form the `DateAdd<T>` implementation is bound to `LocalDate`, so it's no longer a free variable...

**Comment by lukaseder** [comment]
The fix will be source-incompatible in rare cases where users might provide type witnesses (for whatever reason). But given the annoyance it might cause, I'll backport this nonetheless to 3.15.2 if possible.

**Comment by lukaseder** [comment]
I'll revert my take about the backport. This isn't worth an exception. Fixing this for jOOQ 3.16.0 only.

**Comment by lukaseder** [comment]
Related: https://github.com/jOOQ/jOOQ/issues/12768. It does seem to cause problems in kotlin, but not in Java
