### ISSUE TITLE
Add support for CREATE TYPE .. AS OBJECT

### ISSUE THREAD

**Issue by kuchma19** [jOOQ/jOOQ#12229]
### SQL translator incorrectly translates this query:

Oracle input:

```sql
create type abc as object(
a clob
)
```

### Parser output:

```sql
Keyword 'AS ENUM' expected: [1:17] create type abc [*]as object(
a clob
)
```

**Comment by lukaseder** [comment]
Thanks for your suggestion. We don't support creating UDTs in our parser or API yet.

**Comment by lukaseder** [comment]
Let's keep this open as a reminder to implement the feature
