### ISSUE TITLE
Avoid reflection with ParserImpl.IGNORE

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12222]
The `ParserImpl` has two references called `IGNORE` and `IGNORE_NO_DELIMITER`, which are dummy `DDLQuery` and `Query` instances created using reflection (via a proxy) to implement the necessary internal API, so they can be passed around by the parser as "special tokens" that can be identity-compared.

This reflection usage causes trouble in reflection-phobic environments such as quarkus, see https://github.com/quarkiverse/quarkus-jooq/issues/27

Perhaps we can get rid of the reflection by creating a dummy type, instead?

**Comment by lenalebt** [comment]
I'm really impressed by your reaction time to all the things I see happening - besides that I really like the product. I know this may not be the right place to mention it, but I wanted to direct some "thanks" to where it belongs imho :).

**Comment by lukaseder** [comment]
@lenalebt Cheers :)

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0, 3.15.2 (https://github.com/jOOQ/jOOQ/issues/12223), and 3.14.14 (https://github.com/jOOQ/jOOQ/issues/12224)
