### ISSUE TITLE
Can I auto make pagination?

### ISSUE THREAD

**Issue by zuigucheng** [jOOQ/jOOQ#12268]
### Your question:

I want make a function to make pagination without write it in every sql. It need me to get the data count by current sql. can I do that in `DefaultExecuteListener`?

### Versions 3.13:

**Comment by lukaseder** [comment]
Thank you very much for your message. You could patch your queries and append a `COUNT(*) OVER ()` field. It won't be very clean (e.g. much better do this programmatically somehow), but an execute listener is certainly an option, yes.
