### ISSUE TITLE
Feedback about translation tool

### ISSUE THREAD

**Issue by m-m-saternus** [jOOQ/jOOQ#12266]
Hi is the code that accepts the input from this page available anywhere in github? I'm using a DSLContext.parser() to do the same thing. The issue is the dialects available via the SQLDialect enum don't match the ones from the dropdown on the page. The one I specifically want to translate to is SQL Server 2017. 

Also (if possible) could you point out how one can set the default date format please ?

```
Parser parser = ctx.parser();
ctx.configuration().settings().setInterpreterDialect(SQLDialect.XXXX);
Query query = parser.parseQuery("YYYY")
```

**Comment by lukaseder** [comment]
Thank you very much for your interest in the translator library.

The interpreter dialect is used to interpret DDL statements to create a schema, e.g. for creating a schema diff, such as https://www.jooq.org/diff

You're looking for the parser dialect (input dialect), or the `Configuration.dialect()` (output dialect)

Commercial dialects are available from the jOOQ Professional and Enterprise Edition, a free trial for which is available from here:

- https://www.jooq.org/download

See the full dialect support listing here:

- https://www.jooq.org/download/#databases

> Also (if possible) could you point out how one can set the default date format please ?

That would be done via `Settings.parseDateFormat` and `Settings.parseTimestampFormat`
