### ISSUE TITLE
Document error of "custom-data-type-bindings"

### ISSUE THREAD

**Issue by babyfish-ct** [jOOQ/jOOQ#12265]
This is not code bug, but document error.

In the document "https://www.jooq.org/doc/3.15/manual/code-generation/custom-data-type-bindings/"

![image](https://user-images.githubusercontent.com/15168900/127196240-27d8ed19-c604-4ce5-8100-212ac3258d45.png)

The sql "?::json" can only work for JDBC, not OK for R2DBC.

please change it to 

`ctx.render().sql(ctx.variable()).sql("::json");`

**Comment by lukaseder** [comment]
Thanks a lot for your report. Great observation! I agree that would be a better way to do it. There are other alternatives to achieve the same effect, including using `DSL.val(ctx.convert(converter()).value())` as in the inlined case.

**Comment by lukaseder** [comment]
Fixing this now as you suggested, to `ctx.render().sql(ctx.variable()).sql("::json");`
