### ISSUE TITLE
jOOQ 3.15.0 XSD is not published?

### ISSUE THREAD

**Issue by robbytx** [jOOQ/jOOQ#12267]
### Your question:

https://www.jooq.org/xsd/jooq-codegen-3.15.0.xsd returns a 404 error, while [earlier versions](https://www.jooq.org/xsd/jooq-codegen-3.14.0.xsd) are accessible.  

Q: Is this something that you expect to publish eventually?  Was it simply a step that was overlooked in the release process?

Fortunately, Maven codegen is working with new elements from 3.15 (like `<enumsAsScalaSealedTraits>`), even though they don't match the namespace/XSD.  Still, it would be nice for the XML to validate.

### Versions:

- jOOQ: 3.15.1
- Java: 11.0.11
- Database (include vendor): MySQL
- OS: macOS
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your hint. This was omission was not by design. It's available from the website now.
