### ISSUE TITLE
Limitation in FOR ... LOOP implementation

### ISSUE THREAD

**Issue by glr72** [jOOQ/jOOQ#12274]
FOR ... LOOP is implemented only as:

for X in 1 .... N LOOP

while SQL usually supports also:

for X in (  SUBQUERY ) LOOP ...

**Comment by lukaseder** [comment]
Thanks a lot for your report. Numerous procedural language features are not yet supported. A comprehensive list can be found here:
https://github.com/jOOQ/jOOQ/issues/11878

Your particular suggestion can be found here:
https://github.com/jOOQ/jOOQ/issues/8177

We'll definitely support this syntax in the near future.
