### ISSUE TITLE
CONNECT BY wrongly translated

### ISSUE THREAD

**Issue by glr72** [jOOQ/jOOQ#12272]
Connect-by statements are not correctly translated in Oracle/Postgres use case. 

See here how it should be https://www.2ndquadrant.com/en/blog/oracle-to-postgresql-start-with-connect-by/

**Comment by lukaseder** [comment]
Thank you very much for your report. We currently support a few special cases of `CONNECT BY` (https://github.com/jOOQ/jOOQ/issues/11660), not the general case (https://github.com/jOOQ/jOOQ/issues/668).

I'm closing this as a duplicate of #668
