### ISSUE TITLE
Add Javadoc hints about Record.changed() values to InsertValuesStep[N].valuesOfRecords(...)

### ISSUE THREAD

**Issue by mortensimon** [jOOQ/jOOQ#12270]
I am trying to insert multiple rows AND then retrieve all generated IDs using JOOQ 3.15. I have tried to combine the lessons here:

https://www.jooq.org/doc/3.1/manual/sql-building/sql-statements/insert-statement/insert-values/
https://www.jooq.org/doc/3.1/manual/sql-building/sql-statements/insert-statement/insert-returning/

...into something like this:

```java
List<Record3<Integer, String, String>> records = ...
Result<?> result =
create.insertInto(AUTHOR, AUTHOR.FIRST_NAME, AUTHOR.LAST_NAME)
      valuesOfRecords(records).
      .returningResult(AUTHOR.ID, AUTHOR.CREATION_DATE)
      .fetch();
```

However, I don't think I can use the create.newRecord(AUTHOR, authorObject) to easily create the List<Record3> because it will contain the AUTHOR.ID which I want to read out in the result (not send in) and besides be of size Record4 or 5.

Therefore I had to create Record3 "manually":

```java
Record3 r = create.newRecord(AUTHOR.FIRST_NAME, AUTHOR.LAST_NAME)
r.setValue(AUTHOR.FIRST_NAME, "Helmut");
r.setValue(AUTHOR.LAST_NAME, "Kohl");
```

It took awhile for me to get this. So perhaps can documentation examples be expanded upon (since I believe my case is not too special) or maybe there is some obvious trick I don't know or see. Thanks in advance!

**Comment by lukaseder** [comment]
Thank you very much for your message.

There are numerous places in the manual that could profit from cross links, side notes, etc. regarding not strictly related topics. The sections about the `INSERT` statement quickly show how to use a `Record`, but there are many other types of API that also use `Record`. Ultimately, it's always the same thing with records. They have an internal set of "changed" flags, and only the "changed" values are taken into consideration for any operation.

I understand that the path you took through the manual has produced confusion with respect to this particular set of features interacting. I'll think about whether this could have been prevented, but it's much more work than just adding a quick hint about this to the manual. The hint would have been useful for you, but noise for someone else, who might have appreciated a different type of hint, instead.

I do think that this information should go to the `valuesOfRecords()` Javadoc, however. I'll also check if any other `Record` receiving Javadoc could profit from additional hints.

**Comment by lukaseder** [comment]
Another instance of this confusion:

- https://github.com/jOOQ/jOOQ/issues/15436

I will finally document the behaviour of this particular method.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.6 (https://github.com/jOOQ/jOOQ/issues/15449)
- 3.17.15 (https://github.com/jOOQ/jOOQ/issues/15450)
- 3.16.21 (https://github.com/jOOQ/jOOQ/issues/15451)
