### ISSUE TITLE
EXCEPTION CLAUSE not supported

### ISSUE THREAD

**Issue by glr72** [jOOQ/jOOQ#12273]
Oracle supports an "exception clause" that is not supported by SQOOP.

CREATE OR REPLACE PROCEDURE PROC1
AS
BEGIN
       INSERT INTO MYTABLE ('myvalues');
       commit;

EXCEPTION
      WHEN OTHERS THEN
      ROLLBACK;
END;
/

returns:

Unsupported query type: [8:1] ...NSERT INTO MYTABLE ('myvalues');
       commit;

[*]EXCEPTION
      WHEN OTHERS THEN
      ROLLBACK;
END;
/

**Comment by lukaseder** [comment]
Thanks a lot for your report. Numerous procedural language features are not yet supported. A comprehensive list can be found here:
https://github.com/jOOQ/jOOQ/issues/11878

Your particular suggestion can be found here:
https://github.com/jOOQ/jOOQ/issues/8229

We'll definitely support this syntax in the near future.
