### ISSUE TITLE
Multiset include JSON field cause Ad-hoc Converter failed

### ISSUE THREAD

**Issue by leeaee** [jOOQ/jOOQ#12276]
Record class
```java
    /**
     * Setter for <code>houmart.admin_role.permissions</code>.
     */
    public void setPermissions(JSON value) {
        set(4, value);
    }

    /**
     * Getter for <code>houmart.admin_role.permissions</code>.
     */
    public JSON getPermissions() {
        return (JSON) get(4);
    }
```
Pojo class
```java
    private List<String> permissions;
```

### Expected behavior

JSON field will transform to List<String> correctly.

### Actual behavior

1. JSON field will transform to List<String> correctly with normal operation.
2. JSON field will transform to List<String> failed when call with multiset.

when normal operation, the JSON field return 
`"["admin:retrieve", "admin:create", "admin:update"]"`

when using multiset, the JSON field return
`"[admin:retrieve, admin:create, admin:update]"`

### Steps to reproduce the problem
1. define the json field in database.
2. generate the record codes.
3. define a pojo with json field as List.

### Versions

- jOOQ: 3.15.1
- Java: 11
- Database (include vendor): MySQL8
- OS: OSX
- JDBC Driver (include name if inofficial driver): mysql

**Comment by lukaseder** [comment]
Thanks a lot for your report. Indeed, nesting XML/JSON in JSON/XML has not been integration tested yet, so bugs are not improbable, see also: https://github.com/jOOQ/jOOQ/issues/12021

Will look into this soon

**Comment by leeaee** [comment]
OK, thank you for your feedback. 
I think the root cause is the JSON field will return string object nor the JSON formart object when using `multiset` command.

**Comment by lukaseder** [comment]
After having added a few integration tests in this area, I cannot reproduce this exact behaviour, though it might as well have been fixed already as part of another issue. Please re-open if you think this issue still persists. A minimal reproducer would be greatly appreciated in that case.
