### ISSUE TITLE
SelectQuery add CTE

### ISSUE THREAD

**Issue by cdalexndr** [jOOQ/jOOQ#12284]
### Use case:

I'm dynamically building a select query that uses CTE.

### Possible solution you'd like to see:

`SelectQuery.addWith(CommonTableExpression<?>... ctes)`

### Possible workarounds:

Messy code with chain API requiring if/else's.

### Versions:

- jOOQ: 3.14.8
- Java: 11
- Database (include vendor): Postgres
- OS: win10
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your feature request. Yes, there's much room for improvement when creating dynamic CTEs: https://github.com/jOOQ/jOOQ/issues/9895
