### ISSUE TITLE
Replace calls to System.currentTimeMillis() by Clock usage

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12287]
We should never use `System.currentTimeMillis()` in jOOQ's internals, but use `Configuration::clock` instead. The SPI was introduced in jOOQ 3.10 (https://github.com/jOOQ/jOOQ/issues/6447). We now have again some references to `currentTimeMillis()`:

![image](https://user-images.githubusercontent.com/734593/128710651-f8478a36-b31f-4a7f-99f8-a0c8139ceafa.png)

These should be replaced, and a test established that fails whenever these hard-wired clock API calls are added to the jOOQ code, including:

- [ ] `System.currentTimeMillis()`
- [ ] `LocalDate.now()`
- [ ] `LocalDateTime.now()` (etc.)
- [ ] Others?

**Comment by A248** [comment]
> Others?

In case you are wondering – Instant, LocalTime, ZonedDateTime, OffsetDateTime, and OffsetTime all have similar `now()` methods.

`new Date()` also uses System.currentTimeMillis(), but that's legacy API which should be avoided regardless.

**Comment by lukaseder** [comment]
So, while the usage in `BlockImpl` isn't relevant (it generates a random name), the one in the (still) experimental `MigrationImpl` seems to be the only instance that should be fixed.
