### ISSUE TITLE
In manual section jooq-in-7-steps-step3, fix multi line shell syntax and explain JDBC URL

### ISSUE THREAD

**Issue by jrojer** [jOOQ/jOOQ#12289]
Hi guys!

### 1. Please remove the spaces before backslashes, except the last one.

The code should be like that:
```
java -classpath jooq-3.15.1.jar:\
jooq-meta-3.15.1.jar:\
jooq-codegen-3.15.1.jar:\
reactive-streams-1.0.3.jar:\
r2dbc-spi-0.9.0.M1.jar:\
mysql-connector-java-5.1.18-bin.jar:. \
org.jooq.codegen.GenerationTool library.xml
```
### 2. Please add explanation about the `<url>`.

I spent 2+ hours figuring out what should I put into `<url>` section of the `library.xml` 
  I tried: 
```
1. <url>rogue.db.elephantsql.com</url>
2. <url>rogue.db.elephantsql.com/duiijqsk</url>
3. <url>jdbc:postgres://rogue.db.elephantsql.com/duiijqsk</url>
```
  The error was `Cannot execute query. No JDBC Connection configured`.
  And finally I put
```
<url>jdbc:postgresql://rogue.db.elephantsql.com/duiijqsk</url>
```
and it worked. 
Other manual section do not explain it either. What is this first part of an url? How does it work?

Thank you.

**Comment by lukaseder** [comment]
Thanks a lot for your report:

> 1. Please remove the spaces before backslashes, except the last one.

Yes of course! Thanks for pointing this out

> 2. Please add explanation about the <url>

It's a JDBC URL. I take you're not familiar with JDBC? How could we have explained that to you so it would have made sense, without creating too much noise for everyone who is familiar with JDBC?

**Comment by lukaseder** [comment]
The first issue is fixed and will be published with the next manual build

**Comment by jrojer** [comment]
> It's a JDBC URL. I take you're not familiar with JDBC? How could we have explained that to you so it would have made sense, without creating too much noise for everyone who is familiar with JDBC?

Something like: The `<url>` section contains a JDBC url. To learn what is JDBC follow the link (link here).

**Comment by lukaseder** [comment]
But is it really necessary? The configuration elements already refer to the term JDBC:

![image](https://user-images.githubusercontent.com/734593/128836603-74a950cd-6757-4f2f-83d5-7ac60551887e.png)

As in `/jdbc/url`. I would like to avoid adding too much noise like this to the manual. You found the documentation `jooq-in-7-steps-step3`. But for any JDBC backed API, the JDBC URL being ubiquitous, we'd have to repeat this explanation and the link every time to be consistent. I'm currently counting 16 references to `jdbc:` in the manual.

I'll keep this in mind. I can see that this is a distraction to readers who aren't too familiar with JDBC. But it's a slippery slope when adding such details to documentation, as other, more significant information (for most readers) might be harder to find the more details are added...
