### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema when running examples from manual tutorial

### ISSUE THREAD

**Issue by carl1121** [jOOQ/jOOQ#12286]
When going through step three, I get the following exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at org.jooq.util.jaxb.tools.MiniJAXB.getNamespace(MiniJAXB.java:401)
	at org.jooq.util.jaxb.tools.MiniJAXB.addDefaultNamespace(MiniJAXB.java:189)
	at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal0(MiniJAXB.java:176)
	at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal(MiniJAXB.java:162)
	at org.jooq.codegen.GenerationTool.load(GenerationTool.java:1118)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:197)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

**Comment by jrojer** [comment]
Hi!
I was studying this manual section yesterday.

The solution is:
You can find the jar you need here https://www.findjar.com/class/javax/xml/bind/annotation/XmlSchema.html.
Then put the jar where your `xml` file is, and mention it in the classpath.

**Comment by lukaseder** [comment]
Thanks a lot for your feedback, folks, and for your workaround @jrojer. This shouldn't be necessary. jOOQ should be able to run with or without JAXB on the classpath, on any JDK version. I'll look into what went wrong in this case.

**Comment by lukaseder** [comment]
Ah yes, of course. While we don't require a JAXB implementation anymore, the JAXB API is still required, and our tutorial doesn't document how to get it, nor does our ZIP file ship the JAXB API. The general assumption of the tutorial is that people use Maven or Gradle to resolve dependencies, but of course, this may not be the case.

Note that this is a problem only with JDK 11+, as previously, JAXB still shipped with the JDK.

We'll fix the tutorial accordingly.

**Comment by carl1121** [comment]
Thank you so much for the response.

We did use maven to recompile all the the GenerationTool, so maybe we’re missing something.



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lukaseder** [comment]
> We did use maven to recompile all the the GenerationTool, so maybe we’re missing something.

What do you mean by "recompile"? In any case, JAXB is declared as a compile time dependency in the `jooq` artifact, so ideally, this problem here should not appear when *running* the `GenerationTool` with Maven (via the `jooq-codegen-maven` plugin).

**Comment by carl1121** [comment]
Sorry, meant by compile:

Then used the example:


... or type this on a UNIX / Linux / Mac system (colons instead of semi-colons):

java -classpath jooq-3.15.1.jar:\
jooq-meta-3.15.1.jar:\
jooq-codegen-3.15.1.jar:\
reactive-streams-1.0.3.jar:\
r2dbc-spi-0.9.0.M1.jar:\
mysql-connector-java-5.1.18-bin.jar:. \
org.jooq.codegen.GenerationTool library.xml


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by lukaseder** [comment]
Yes, when you run the standalone generator (`java -classpath ... GenerationTool`), then you're not really using Maven, and this issue here appears.

**Comment by carl1121** [comment]
Thanks again for the fast response.

Just as you said I was able to get the GenerationTool to work by adding the maven dependency for mysql in and then running the tool straight out of intellij Now I can proceed to step 4 🙂👎


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by carl1121** [comment]
Good afternoon,

So as mentioned, I was able to get the tool to run successfully.  However, a couple of items to note for the tutorial:

https://www.jooq.org/doc/latest/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step3/
[https://www.jooq.org/img/jooq-logo-white-750x750-padded.png]<https://www.jooq.org/doc/latest/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step3/>
Step 3: Code generation - jOOQ<https://www.jooq.org/doc/latest/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step3/>
Replace the username (<username/> or <user/>) with whatever user has the appropriate privileges to query the database meta data.You'll also want to look at the other values and replace as necessary. Here are the two interesting properties: <packageName/> - set this to the parent package you want to create for the generated classes. Setting the value to test.generated will cause the test ...
www.jooq.org

Although the java subdirectory is created there are no files created.  Also, no test/generated directory was created on the file system.

So we're not sure what's missing.  We did test that the user ID and password are good in another java program to connect to the library database in MySQL and populate the author table.




Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by carl1121** [comment]
The first issue I see is:
Aug 11, 2021 11:15:28 AM org.jooq.tools.JooqLogger info
INFO: Initialising properties  : library.xml
Aug 11, 2021 11:15:29 AM org.jooq.tools.JooqLogger info
INFO: No <inputCatalog/> was provided. Generating ALL available catalogs instead.
Aug 11, 2021 11:15:29 AM org.jooq.tools.JooqLogger info
INFO: License parameters
Aug 11, 2021 11:15:29 AM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by lukaseder** [comment]
Thanks, @carl1121. This does not seem to be related to the original `NoClassDefFoundError`? May I ask you to create a new support request: https://github.com/jOOQ/jOOQ/issues/new/choose

It helps us better track open issues and not forget if anything is missing for you. When creating a new issue, please provide all information that you currently have that you might think is necessary to reproduce the problem. For example, providing your complete code generation configuration would be helpful, and the complete log output, etc.

**Comment by lukaseder** [comment]
Looking into solving this now. The JAXB API is licensed like most of Oracle/Java's work, see:
https://search.maven.org/artifact/javax.xml.bind/jaxb-api/2.3.1/jar

Namely 
https://oss.oracle.com/licenses/CDDL+GPL-1.1

The library includes the "GPL Classpath Exception", so we can safely distribute it with jOOQ in the ZIP file. It will be mentioned here:
https://www.jooq.org/legal/licensing

**Comment by lukaseder** [comment]
This is now fixed for 3.16.0 and 3.15.2 (the ZIP file will be re-deployed, shortly). Thanks again everyone for your feedback.

**Comment by jehrlich** [comment]
```
$ java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)
$ java -classpath jooq-3.16.3.jar:\
> jooq-meta-3.16.3.jar:\
> jooq-codegen-3.16.3.jar:\
> reactive-streams-1.0.3.jar:\
> r2dbc-spi-0.9.0.RELEASE.jar:\
> jaxb-api-3.0.0.jar:\
> mysql-connector-java.jar:. \
> org.jooq.codegen.GenerationTool library.xml
Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/xml/bind/annotation/XmlSchema
	at org.jooq.util.jaxb.tools.MiniJAXB.getNamespace(MiniJAXB.java:400)
	at org.jooq.util.jaxb.tools.MiniJAXB.addDefaultNamespace(MiniJAXB.java:188)
	at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal0(MiniJAXB.java:175)
	at org.jooq.util.jaxb.tools.MiniJAXB.unmarshal(MiniJAXB.java:161)
	at org.jooq.codegen.GenerationTool.load(GenerationTool.java:1180)
	at org.jooq.codegen.GenerationTool.main(GenerationTool.java:203)
Caused by: java.lang.ClassNotFoundException: jakarta.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

**Comment by lukaseder** [comment]
Thanks for your comment, @jehrlich. That's a different issue than the one documented here, though it has a similar result. I'll fix the manual right away: https://github.com/jOOQ/jOOQ/issues/12983
