### ISSUE TITLE
In MySQL, createOrReplaceFunction/Procedure() leads to an error: " You have an error in your SQL syntax ..."

### ISSUE THREAD

**Issue by AnghelLeonard** [jOOQ/jOOQ#12297]
### Expected behavior
No errors.

### Actual behavior
In MySQL, `createOrReplaceFunction/Procedure()` leads to an error: "_You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create function `foo`() returns int deterministic begin return 0; end' at line 1_".

### Steps to reproduce the problem
I tried this code:

```Java
ctx.createOrReplaceFunction("foo") 
    .returns(INTEGER)
    .deterministic()
    .as(return_(0))
    .execute();
```
The rendered code that produces the error is:

```sql
drop function if exists `foo`; 
create function `foo`() returns int 
  deterministic 
begin 
  return 0; 
end;
```

The code that works uses a MySQL explicit delimiter as:

```sql
drop function if exists `foo`; 
DELIMITER $$
create function `foo`() returns int 
  deterministic 
begin 
  return 0; 
end$$
DELIMITER ;
```

I am not sure, but I think that the same issue may occur in other scenarios like here:

```java
create.begin(call(name("foo"))).execute();
```

Note: If I replace `createOrReplaceFunction/Procedure()` with the combo `dropFunctionProcedureIfExists()` and `createFunction/Procedure()` then it work as expected.

### Versions

- jOOQ: 3.15.0
- Java: 14
- Database (include vendor): MySQL
- OS: -
- JDBC Driver (include name if inofficial driver): -

**Comment by lukaseder** [comment]
Thank you very much for your report. This works in our integration tests using:

- MySQL version 8.0.22
- JDBC driver version `mysql:mysql-connector-java:8.0.25`
- JDBC url `jdbc:mysql://127.0.0.1/test?characterEncoding=UTF-8&characterSetResults=utf8&connectionCollation=utf8_general_ci&allowMultiQueries=true&serverTimezone=Europe/Zurich&allowPublicKeyRetrieval=true`

Specifically, `allowMultiQueries=true` might be relevant. When I remove it, I can reproduce your issue. There are other issues like this, specifically: https://github.com/jOOQ/jOOQ/issues/12119

Your `DELIMITER` hint is an interesting one. It shows that the `allowMultiQueries` flag is a rather "sloppy" security precaution, that can be worked around easily... (perhaps, luckily for jOOQ)

**Comment by lukaseder** [comment]
Ideally, this should be solved with a new `Settings` flag describing how to generate this SQL. While `Block` types that are delimited with `BEGIN .. END` (created with `DSL.begin()`) will continue to render a semi colon `;`, `Block` types that don't generate an anonymous block (created with `DSL.statements()`) will use the configured delimiter, and set/restore the delimiter around the statement batch.

I prefer not to backport this new feature to jOOQ 3.16, so let's establish:

- It's a "feature" not a "bug" (I know)
- In jOOQ 3.15 `allowMultiQueries=true` may be required for jOOQ queries to work
- In jOOQ 3.16, we'll generate `DELIMITER ...` statements to work around the `allowMultiQueries=false` default in MySQL's JDBC connector and allow for reverting to the jOOQ 3.15 behaviour if users prefer that.

**Comment by lukaseder** [comment]
The documentation of this `allowMultiQueries` flag explicitly talks about the semi-colon:

> Allow the use of ';' to delimit multiple queries during one statement (true/false). Default is 'false', and it does not affect the addBatch() and executeBatch() methods, which rely on rewriteBatchStatements instead.

Other delimiters are not affected. This is reasonable, because the semi colon is the default delimiter, and the point here is to prevent SQLi vulnerabilities in default setups. Attackers won't guess all possible alternative delimiters, and a jOOQ generated query is not vulnerable as much as a plain JDBC query, so the flag doesn't cover all types of delimiters.

We can probably rely on this not changing any time soon.

----
See:
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-security.html

**Comment by lukaseder** [comment]
We already have `Settings.delimiter`, which isn't being used yet: https://github.com/jOOQ/jOOQ/issues/5826. We should use that flag where appropriate: https://github.com/jOOQ/jOOQ/issues/12323

**Comment by lukaseder** [comment]
I'll let this rest a bit. I can't seem to think of the best way to configure this in a consistent way for all use-cases.

**Comment by lukaseder** [comment]
Egh. Silly me. `DELIMITER` isn't actually a statement. It's some sort of directive implemented by the `mysql` client program (similar to SQL*Plus directives), not understood by the server. As such, it cannot be sent over JDBC. DBeaver and other editors emulate the same syntax for convenience. And so does jOOQ's parser.

There's no workaround here to be made. When `allowMultiQueries=false` is set, certain jOOQ features simply won't work. If there's another possible workaround, I'll be happy to reconsider. Until then, I suspect this works as designed.

**Comment by lukaseder** [comment]
I'll schedule a blog post documenting the various things jOOQ requires the `allowMultiQueries=true` flag for, so people can better debug these kinds of errors. With jOOQ, the security concern this flag is addressing isn't an issue, so it can be safely turned back on.

**Comment by lukaseder** [comment]
Here is the blog post: https://blog.jooq.org/mysqls-allowmultiqueries-flag-with-jdbc-and-jooq
