### ISSUE TITLE
Unable to Generate Code using tutorial step 3

### ISSUE THREAD

**Issue by carl1121** [jOOQ/jOOQ#12299]
### Your question:  Using this tutorial:  https://www.jooq.org/doc/latest/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step3/ 

We are unable to have our system generated the code as expected.  The output is not as described in the tutorial.  Instead of the expected output:

Nov 1, 2011 7:25:06 PM org.jooq.impl.JooqLogger info
INFO: Initialising properties  : /library.xml
Nov 1, 2011 7:25:07 PM org.jooq.impl.JooqLogger info
INFO: Database parameters
Nov 1, 2011 7:25:07 PM org.jooq.impl.JooqLogger info
INFO: ----------------------------------------------------------
Nov 1, 2011 7:25:07 PM org.jooq.impl.JooqLogger info
INFO:   dialect                : MYSQL
Nov 1, 2011 7:25:07 PM org.jooq.impl.JooqLogger info
INFO:   schema                 : library
Nov 1, 2011 7:25:07 PM org.jooq.impl.JooqLogger info
INFO:   target dir             : C:/workspace/MySQLTest/src
Nov 1, 2011 7:25:07 PM org.jooq.impl.JooqLogger info
INFO:   target package         : test.generated
Nov 1, 2011 7:25:07 PM org.jooq.impl.JooqLogger info
INFO: ----------------------------------------------------------

We receive the following output:

Aug 12, 2021 10:46:19 AM org.jooq.tools.JooqLogger info
INFO: Initialising properties  : library.xml
Aug 12, 2021 10:46:20 AM org.jooq.tools.JooqLogger info
INFO: No <inputCatalog/> was provided. Generating ALL available catalogs instead.
Aug 12, 2021 10:46:20 AM org.jooq.tools.JooqLogger info
INFO: License parameters       
Aug 12, 2021 10:46:20 AM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Aug 12, 2021 10:46:20 AM org.jooq.tools.JooqLogger info
INFO:   Thank you for using jOOQ and jOOQ's code generator
Aug 12, 2021 10:46:20 AM org.jooq.tools.JooqLogger info
INFO:                          
Aug 12, 2021 10:46:20 AM org.jooq.tools.JooqLogger info
INFO: Database parameters      
Aug 12, 2021 10:46:20 AM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------

### Versions:

- jOOQ: 3.15
- Java: 11.0.22
- Database (include vendor): MySQL 14.14
- OS: Centos 7
- JDBC Driver (include name if inofficial driver): mysql-connector-java-8.0.26.jar

**Comment by lukaseder** [comment]
Thanks for your report. Can you please provide the contents of your `library.xml` file?

**Comment by carl1121** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.7.0.xsd">
  
  <jdbc>
    <driver>com.mysql.cj.jdbc.Driver</driver>
    <url>jdbc:mysql://localhost:3306/library</url>
    <user>sqladmin</user>
    <password>secret</password>
  </jdbc>

  <generator>
    
    <name>org.jooq.codegen.JavaGenerator</name>

    <database>
      
      <name>org.jooq.meta.mysql.MySQLDatabase</name>

      
      <inputSchema>library</inputSchema>

      
      <includes>.*</includes>

      
      <excludes></excludes>
    </database>

    <target>
      
      <packageName>test.generated</packageName>

      
      <directory>./workspace/MySQLTest/src/main/java</directory>
    </target>
  </generator>
</configuration>


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by carl1121** [comment]
Please forgive and close this question.

I was able to make this working by changing the destination directory to where my Idea Projects, (JetBrains Intellij), live.  So, to fix this and get the import to work in the code I made the following modification:

<directory>/home/carl/IdeaProjects/jooqtest01/src/main/java</directory>

and now the import for "Tables" is finding them and working!

Thanks,
Carl

[cid:efbbac26-0ba7-44a9-aedf-129f3967a7d4]

Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by lukaseder** [comment]
It happens to the best :) Glad you could resolve the issue!
