### ISSUE TITLE
How to replace `Clause`?

### ISSUE THREAD

**Issue by zuigucheng** [jOOQ/jOOQ#12301]
### Your question:

When `Clause` be Deprecated, how do I replace it?

link case #12264
### Versions:
- jOOQ: 3.15.1

**Comment by lukaseder** [comment]
Thank you very much for your message. There is currently no replacement for it. We won't remove it before it can be replaced, via our efforts of creating a new query object model, see: https://github.com/jOOQ/jOOQ/projects/2
