### ISSUE TITLE
Table Meta getPrimaryKeys() does not contain data for getReferences()

### ISSUE THREAD

**Issue by austinarbor** [jOOQ/jOOQ#12312]
### Expected behavior
I would expect the keys returned from `getPrimaryKeys()` when using the meta api to contain the same data when calling `getReferences()` as when calling `Keys.Key.getReferences()`
### Actual behavior
`getReferences()` is empty when using the meta api
### Steps to reproduce the problem
```sql
create table a (
  id BIGINT NOT NULL,
PRIMARY KEY (id)
);

create table b(
  id BIGINT NOT NULL,
 a_id BIGINT REFERENCES a(id),
PRIMARY KEY (id)
)
```

```java
Keys.A_PKEY.getReferences(); // contains the FK reference
dsl.meta(A.A).getPrimaryKeys().get(0).getReferences(); // does not contain the reference
```

Code gen configuration:
```groovy
jooq {
    version = dependencyManagement.importedProperties['jooq.version']
    configurations {
        main {
            generateSchemaSourceOnCompilation = false
            generationTool {
                jdbc {
                    driver = 'org.postgresql.Driver'
                    url = 'jdbc:postgresql://localhost:5432/dev'
                    user = 'user'
                }
                generator {
                    database {
                        inputSchema = 'public'
                        excludes = 'flyway_schema_history'
                    }
                    generate {
                        javaTimeTypes = true
                        fluentSetters = true
                        daos = false
                        pojos = false
                    }
                    target {
                        packageName = 'com.example.api.generated.jooq'
                        directory = 'src/generated/java'
                    }
                }
            }
        }
    }
}
```

### Versions

- jOOQ: 3.14.13
- Java: 11.0.11
- Database (include vendor): Postgres 12
- JDBC Driver (include name if inofficial driver): postgresql 42.2.23

**Comment by lukaseder** [comment]
Thanks a lot for your message.

Your schema `dsl.meta(A.A)` is not the same as your schema written in DDL. What you meant to do is `dsl.meta(A.A, A.B)`. If you exclude table `B` from your meta data, then its foreign key (and the inverse relationship) won't be produced from the `Meta` object.

I hope this makes sense?

**Comment by austinarbor** [comment]
Hi @lukaseder thanks for your response. When trying 
```java
dsl.meta(A.A, B.B).getPrimaryKeys()
```
The references are still missing.

I also tried 
```java
dsl.meta().getPrimaryKeys().get(0).getReferences() // 0 is index of A's PK
```
and the result is the same
