### ISSUE TITLE
Disabling Schema(Database) to be included in the jooq Codegen

### ISSUE THREAD

**Issue by Karthikeyashastry** [jOOQ/jOOQ#12320]
### Your question:

On generating the classes using jooq codegen, the fields of a table gets resolved as "database"."table"."field".
Is it possible to disable the "database" being resolved, as the database is provided in the jdbc driver url, and dont want it conflicting.

### Versions:

- jOOQ: 3.14.12
- Java: 11
- Database (include vendor): mysql
- OS:
- JDBC Driver (include name if inofficial driver): mysql-connector-java

**Comment by lukaseder** [comment]
Thank you very much for your message. Please use either:

- Code generation schema mapping: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-catalog-and-schema-mapping/
- Runtime schema mapping: https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-render-mapping/

**Comment by Karthikeyashastry** [comment]
Thanks @lukaseder for the very quick response as always. 👍
