### ISSUE TITLE
Add support for UNNEST() to be used directly in IN predicates

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#12330]
I'm trying to migrate some code to work across H2, HSQLDB and another SQL-based engine. As part of that, I'm trying to find a least common denominator of SQL that would work well with arrays. My queries are currently written to work with H2 (array features I currently use are array column types, H2's `array_contains()` and `array_agg()`). 

I was hoping I could use JOOQ to accept SQL in one dialect and render/emulate the SQL to other dialects if needed. So I thought I'd give the JOOQ parser a spin (please correct me if I'm off on this expectation).

Here's a test case with H2 and HSQLDB that represents some code that both DBs accept but JOOQ's parser does not parse:

```java
    @Test
    public void testJooqH2() {
        var t1 = "CREATE TABLE T1(x integer)";
        var t2 = "CREATE TABLE T2(y array)";
        var t3 = "CREATE VIEW V AS SELECT * FROM t1 JOIN t2 ON t1.x IN (unnest(t2.y))";
        var conn = using("jdbc:h2:mem:");
        conn.execute(t1);
        conn.execute(t2);
        conn.execute(t3);
        conn.fetch("SELECT * FROM V");
        System.out.println(conn.parser().parse(t3));
    }

    @Test
    public void testJooqHsqlDB() {
        var t1 = "CREATE TABLE T1(x integer)";
        var t2 = "CREATE TABLE T2(y integer array)";
        var t3 = "CREATE VIEW V AS SELECT * FROM t1 JOIN t2 ON t1.x IN (unnest(t2.y))";
        var conn = using("jdbc:hsqldb:mem:test");
        conn.execute(t1);
        conn.execute(t2);
        conn.execute(t3);
        conn.fetch("SELECT * FROM V");
        System.out.println(conn.parser().parse(t3));
    }
```

I'm using `IN (UNNEST())` because H2's `array_contains()` isn't standard syntax and I've been trying to migrate away from it (I'm also aware that JOOQ's parser doesn't yet support `array_contains()`).

### Expected behavior

No exceptions are thrown

### Actual behavior

`conn.parser().parse(t3)` in both tests throws the following exception:

```java
org.jooq.impl.ParserException: Unknown function: [1:62] ... V AS SELECT * FROM t1 JOIN t2 ON t1.x IN (unnest([*]t2.y))

	at org.jooq.impl.ParserContext.exception(ParserImpl.java:11045)
	at org.jooq.impl.ParserImpl.parseUnaryOps(ParserImpl.java:5736)
	at org.jooq.impl.ParserImpl.parseExp(ParserImpl.java:5703)
	at org.jooq.impl.ParserImpl.parseFactor(ParserImpl.java:5680)
	at org.jooq.impl.ParserImpl.parseSum(ParserImpl.java:5632)
	at org.jooq.impl.ParserImpl.parseNumericOp(ParserImpl.java:5617)
	at org.jooq.impl.ParserImpl.parseCollated(ParserImpl.java:5598)
```

### Steps to reproduce the problem

The above self-contained test cases

### Versions

- jOOQ: 3.15.1
- Java: 12.0.1
- Database (include vendor): H2, HSQLDB
- OS: macOS 11.5.1
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your report

I'm surprised H2 accepts this syntax. I mean, it's useful, but I don't think it's documented? `UNNEST` is a table expression
https://h2database.com/html/grammar.html#table_expression

And the `IN` predicate doesn't seem to accept arbitrary table expressions:
https://h2database.com/html/grammar.html#condition_right_hand_side

Perhaps, @katzyn can shed some light? In any case, from what I understand, H2's arrays are quite the moving target. In 1.4.200, they're still using the old implementation and syntax. But with the upcoming release (whenever that is), from what I've seen, they will work in a much more standardised way. So, chances are, your design might not work in the exact same way.

> I was hoping I could use JOOQ to accept SQL in one dialect and render/emulate the SQL to other dialects if needed. So I thought I'd give the JOOQ parser a spin (please correct me if I'm off on this expectation).

That expectation is correct. Whenever you need to extend parser behaviour, you can maybe get your custom syntax to work via the `ParseListener` SPI: https://www.jooq.org/doc/latest/manual/sql-building/sql-parser/sql-parser-listener/

Curiously, I can't get this to work in HSQLDB:

```sql
select 1 in (unnest(1)) from (values(1)) t(a);
```

I wonder if it's documented, there?

In any case, I'll keep this in mind and look into supporting `UNNEST()` in `IN` predicates like that.

**Comment by lalithsuresh** [comment]
Thanks for the quick response Lukas. Yes, H2's 1.4.200 array syntax is quite non-standard (the lack of array types in particular is an issue for us in migrating).

> they will work in a much more standardised way.

May I know what a more standard and/or jooq-friendly way to check for membership inside an array field is (not array literal)? I've been struggling to find this info, but the most shared syntax I've seen among some DBs thus far was the `IN UNNEST()` (H2, HSQLDB, BigTable).

**Comment by lalithsuresh** [comment]
Hi @lukaseder. I see that H2 finally has a new release and is more aligned with the standard on arrays. I also see that UNNEST is now better documented.

In any case, may I know what the jooq-friendly way to check for membership inside an array field is (not array literal)?

**Comment by lukaseder** [comment]
Thanks, @lalithsuresh. I don't think it fits in 3.16 anymore. Getting H2 up to date is already a challenging enough task, with all the backwards incompatibilities, see https://github.com/jOOQ/jOOQ/issues/9609

You can always use plain SQL templating, see also this question here:
https://stackoverflow.com/a/70182941/521799

**Comment by lukaseder** [comment]
Looking into this again, in the context of recent `UNNEST` improvements. Trying this on H2 2.1.214:

```sql
create table t1(x integer);
create table t2(y integer array);
create view v as select * from t1 join t2 on t1.x in (unnest(t2.y));
```

I'm now getting:

```
SQL Error [90022] [90022]: Function "UNNEST" not found; SQL statement:
create view v as select * from t1 join t2 on t1.x in (unnest(t2.y)) [90022-214]
```

It seems that H2 has removed a non-standard feature. In standard SQL, you'd write this instead:

```sql
create view v as select * from t1 join t2 on t1.x in (select * from unnest(t2.y));
```

The above parses in jOOQ's parser. And it works in PostgreSQL but not in H2, which seems to have a limitation here: https://github.com/h2database/h2database/issues/1815

Given that the syntax is no longer supported in H2, and given that it was a bit esoteric in the first place, I'll reject this feature request.
