### ISSUE TITLE
Error with Parser and TSQL Declare statements

### ISSUE THREAD

**Issue by cstrass-sbi** [jOOQ/jOOQ#12343]
I am able to parse any set of complex TSQL sql. However the moment I add a Declare statement an error is produced. Even reducing the SQL to a simple declare statement produces an error (via JOOQ api).

Best to explain with following simple code snippet that is failing with latest JOOQ:

        Settings settings2 = new Settings().withParseDialect(SQLDialect.SQLSERVER);
        Queries outputQueries = DSL.using(SQLDialect.POSTGRES, settings2).parser()
            .parse("declare @value_dt as DATETIME;");

I noticed in the _translate_ page this simple Declare statement is working fine.
Are we missing a configuration setting?
Any help would be appreciated. Thank you.

**Comment by lukaseder** [comment]
Thanks a lot for your message. The method you should call instead of `Parser.parse` is `Parser.parseStatements`, so this will work:

```java
Settings settings2 = new Settings().withParseDialect(SQLDialect.SQLSERVER);
Block outputQueries = DSL.using(SQLDialect.POSTGRES, settings2).parser()
        .parseStatements("declare @value_dt as DATETIME;");
```

I think we have an issue somewhere to improve this, and allow for T-SQL procedural statements to be parsed as `Queries` even if they're not wrapped in `begin .. end`

I hope this helps

**Comment by cstrass-sbi** [comment]
> Thanks a lot for your message. The method you should call instead of `Parser.parse` is `Parser.parseStatements`, so this will work:
> 
> ```java
> Settings settings2 = new Settings().withParseDialect(SQLDialect.SQLSERVER);
> Block outputQueries = DSL.using(SQLDialect.POSTGRES, settings2).parser()
>         .parseStatements("declare @value_dt as DATETIME;");
> ```
> 
> I think we have an issue somewhere to improve this, and allow for T-SQL procedural statements to be parsed as `Queries` even if they're not wrapped in `begin .. end`
> 
> I hope this helps

Thank you Lukas for the quick reply. This did get us going.  
Much appreciated.  Cheers, Cliff.
