### ISSUE TITLE
[JOOQ 3.9.1][PostgreSQL] Nested select queries are moved to stale state when using Indexed parameters

### ISSUE THREAD

**Issue by svatada** [jOOQ/jOOQ#12359]
In my project, I am having a nested SELECT statement which uses indexed parameters for WHERE clause. When I execute this SELECT statement (provided in sample code), Java threads are moving to stale state forever. The same query works fine using  JDBC. 

In workbench, executing one select statement took 1.1 seconds but using Jooq, it is bit slow and hangs forever at 6 or 10th consecutive execution of the query with indexed parameters (refer attached sample code).

I have lookup the pg_stat_activity view in PostgreSQL and found that, the queries are lying for long time and no trace for reason. Following are details to reproduce the issue.

DDL:
```sql
CREATE TABLE public.aqtmf_binder_section (
    serial_num integer,
    binder_serial_num integer,
    binder_section_id character varying(50),
    parent_section_id character varying(50),
    binder_name character varying(50),
    index_id character varying(50),
    parent_index_id character varying(50),
    status character varying(50),
    creation_time timestamp without time zone,
    parent_index_name character varying(500),
    index_name character varying(500)
);
```

This issue can be reproduced using  this sample Java code:
[PostgresTest.zip](https://github.com/jOOQ/jOOQ/files/7052486/PostgresTest.zip)

### Versions

- jOOQ: 3.9.1
- Java: 11
- Database (include vendor): PostgreSQL [psql (12.7 (Ubuntu 12.7-0ubuntu0.20.04.1), server 10.16 (Ubuntu 10.16-0ubuntu0.18.04.1))]
- OS: Ubuntu 20.4
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver

**Comment by svatada** [comment]
MCVE  https://github.com/jOOQ/jOOQ-mcve/pull/11

**Comment by lukaseder** [comment]
Thanks. After fixing some compilation errors (see https://github.com/svatada/jOOQ-mcve/commits/master), I can reproduce an issue.

**Comment by lukaseder** [comment]
A quick ckeck in:

```sql
select *
from pg_catalog.pg_stat_activity 
```

Yields that the query is still running, it's just the client that got disconnected. See also activity of my docker container:

![image](https://user-images.githubusercontent.com/734593/131526674-9462cbff-ab21-45c7-8e50-399c3a49e0bc.png)

**Comment by lukaseder** [comment]
Well, you're setting the query timeout to 1 second, that would explain why you're losing the connection:

```java
ctx.settings().setQueryTimeout(1000);
```

**Comment by lukaseder** [comment]
Setting this:

```java
ctx.settings().setStatementType(StatementType.STATIC_STATEMENT);
```

Produces static statements (no prepared statements / bind values), so it seems the optimiser can handle this better. There's an assertion failure, which I'm not going to investigate, probably a wrong test setup.

I think this is just a slow query caused by the numerous amounts of self-joins. Since you only have 20k rows in this table, perhaps you could try running a recursive query instead, or assemble your tree in the client?

In any case, this doesn't seem like a jOOQ problem. The problem seems to be caused by using bind values (which is the default in jOOQ), and how PostgreSQL handles that for this particular query.

**Comment by svatada** [comment]
I am suspecting its an issue with jOOQ because,  I have added a test using plain JDBC in the MCVE. The same test is passing where as using jOOQ, its moving to stale/lock state.

**Comment by lukaseder** [comment]
> The same test is passing

Well :) You're not executing your JDBC query:

```java
ResultSet resultSet = preparedStatement.getResultSet();
```

**Comment by svatada** [comment]
my bad, thanks for pointing it.
