### ISSUE TITLE
Wrong type documented in INSERT .. RETURNING section of the manual

### ISSUE THREAD

**Issue by jrojer** [jOOQ/jOOQ#12379]
It seems like it should be just `Record`.
```
error: type Record does not take parameters
            Record<?> record 
```
The build environment:
```
$ java --version
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```
```
implementation 'org.jooq:jooq:3.15.1'
implementation 'org.jooq:jooq-meta:3.15.1'
implementation 'org.jooq:jooq-codegen:3.15.1'
```
----
See: https://www.jooq.org/doc/3.1/manual/sql-building/sql-statements/insert-statement/insert-returning/

**Comment by lukaseder** [comment]
Ah yes, thanks a lot. That's just a copy paste error when the `Result<?>` example was copy pasted, I suspect. Fixed. The fix should be visible with 1-2 hours
