### ISSUE TITLE
List<String> Mapped to Json  error: (ParameterizedType) method.getGenericParameterTypes()[0]

### ISSUE THREAD

**Issue by zhangjiayi1** [jOOQ/jOOQ#12393]
### Problem Description
  
![image](https://user-images.githubusercontent.com/43409488/131997913-b17e6b9f-4f98-4ec2-b55e-20b785442083.png)

  
  ![image](https://user-images.githubusercontent.com/43409488/131988887-687e79f7-feff-4c57-8c83-dc08bde5f40f.png)
  
  images corresponds to the json field of mysql
  
  ![image](https://user-images.githubusercontent.com/43409488/131993312-2f3368fb-1eee-484d-a432-10747d9ae6cb.png)
  
  The interface has an abstract method with the same method name and parameters but different return values
  
  ![image](https://user-images.githubusercontent.com/43409488/131989241-63af29e0-d7ae-4743-a66c-349bc115b01e.png)
  
  May appear here  IActivity 的 setImages(List<String> value)   covered ActivityPOJO 的 setImages(List<String> images)
  
  ![image](https://user-images.githubusercontent.com/43409488/131993930-4e0b8955-e527-4425-bef1-4975e5dc67a7.png)
  
  Forced to (ParameterizedType) will report an error
  
  ### Suggest
   
  
  ### Steps to reproduce the problem
  
  - The entity class implements an interface
  - The entity class contains the List<String> field mapped to the Json field of mysql
  - Configuration  JsonListStringBinding implements Binding<JSON, List<String>>
  - The set method defined in the interface is the same as the entity class parameter. The method name is the same but the return value is different.
  - Deposit Set<SourceMethod> ,  There will be a set method coverage problem
  
  ### Versions
  
  - jOOQ: 3.12.4
  - Java:  1.8
  - Database (include vendor):mysql 5.7.29
  - OS:
  - JDBC Driver (include name if inofficial driver): hikari

**Comment by zhangjiayi1** [comment]
![ddd](https://user-images.githubusercontent.com/43409488/132034404-61158147-373d-4942-b035-323c85572bef.PNG)

I think this sort of Method puts subclass methods at the end of Set<Method>  


![dddd](https://user-images.githubusercontent.com/43409488/132034734-573df6e6-0b79-4a3c-b285-a6302f1e20bc.PNG)


In this way, methods with the same method name and parameters will not be overridden by parent methods

**Comment by lukaseder** [comment]
Thanks a lot for your report. This may take some time to reproduce. Before I try to reproduce this:

- Do you have time to reduce your examples to an MCVE (we have a template here: https://github.com/jOOQ/jOOQ-mcve)
- Does the problem still exist in jOOQ 3.15.2?
- Can you show some jOOQ code that helps reproduce this (in an MCVE or here on the issue), as well as the DDL definition of your table?

**Comment by zhangjiayi1** [comment]
> Thanks a lot for your report. This may take some time to reproduce. Before I try to reproduce this:
> 
> * Do you have time to reduce your examples to an MCVE (we have a template here: https://github.com/jOOQ/jOOQ-mcve)
> * Does the problem still exist in jOOQ 3.15.2?
> * Can you show some jOOQ code that helps reproduce this (in an MCVE or here on the issue), as well as the DDL definition of your table?

经过多次测试 3.15.2 确实修复了这个问题👍

**Comment by lukaseder** [comment]
> After many tests, 3.15.2 did fix this problem👍

Thanks for the confirmation. There had been a few fixes in this area, so I was hoping this is a duplicate
