### ISSUE TITLE
Make the OSGi imports for jackson and gson modules optional

### ISSUE THREAD

**Issue by ascertrobw** [jOOQ/jOOQ#12408]
Under 3.15.1, the OSGi imports for the Jackson kotlin module mean that this module and the full kotlin stack need to be loaded into the OSGi framework even if not used. Marking this as an optional import would workaround the issue for those not needing/using kotlin e.g.

com.fasterxml.jackson.module.kotlin;resolution:=optional

As a related side-note, the published r2dbc-spi JARS do not have OSGi headers, which adds an extra complication for using jOOQ in an OSGi environment. Again, we've done a local build workaround to adjust the headers - but also logged a feature request with the r2dbc-spi project.

**Comment by lukaseder** [comment]
Thanks a lot for your report. Looking at that manifest, I wonder how that dependency has sneaked in. Does Apache Felix look at byte code to detect reflective dependencies?? The only place where this package appears is in `org.jooq.impl.Convert`:

```java
Class<?> kotlin = Class.forName("com.fasterxml.jackson.module.kotlin.ExtensionsKt");
```

Can't Apache Felix look at `module-info` and make everything optional that isn't listed in `module-info` explicitly?

> but also logged a feature request with the r2dbc-spi project.

Yes, I've seen it: https://github.com/r2dbc/r2dbc-spi/issues/242. What can jOOQ do to improve things in the meantime? This dependency isn't optional...

**Comment by lukaseder** [comment]
jOOQ 3.15.2 OSS Edition lists these imports:

```
Import-Package: javax.persistence;resolution:=optional;version="[2.2,3)"
 ,org.slf4j;resolution:=optional;version="[1.7,2)",com.fasterxml.jackson
 .databind,com.fasterxml.jackson.module.kotlin,com.google.gson,io.r2dbc.
 spi,javax.annotation.processing,javax.sql,javax.tools,javax.xml.bind;ve
 rsion="[2.3,3)",javax.xml.bind.annotation;version="[2.3,3)",javax.xml.b
 ind.annotation.adapters;version="[2.3,3)",javax.xml.namespace,javax.xml
 .parsers,javax.xml.transform,javax.xml.transform.dom,javax.xml.transfor
 m.stream,javax.xml.validation,org.jooq,org.jooq.conf,org.jooq.exception
 ,org.jooq.impl,org.jooq.migrations.xml,org.jooq.migrations.xml.jaxb,org
 .jooq.tools,org.jooq.tools.csv,org.jooq.tools.jdbc,org.jooq.tools.json,
 org.jooq.tools.reflect,org.jooq.types,org.jooq.util.cubrid,org.jooq.uti
 l.derby,org.jooq.util.firebird,org.jooq.util.h2,org.jooq.util.hsqldb,or
 g.jooq.util.ignite,org.jooq.util.jaxb.tools,org.jooq.util.mariadb,org.j
 ooq.util.mysql,org.jooq.util.postgres,org.jooq.util.sqlite,org.jooq.uti
 l.xml.jaxb,org.postgresql.util;version="[42.2,43)";resolution:=optional
 ,org.reactivestreams;version="[1.0,2)",org.w3c.dom,org.xml.sax,org.xml.
 sax.helpers
```

Commerical editions list these ones:

```
Import-Package: javax.persistence;resolution:=optional;version="[2.2,3)"
 ,org.slf4j;resolution:=optional;version="[1.7,2)",com.amazon.redshift.u
 til;resolution:=optional,com.fasterxml.jackson.databind,com.fasterxml.j
 ackson.module.kotlin,com.google.gson,com.microsoft.sqlserver.jdbc;versi
 on="[9.2,10)";resolution:=optional,io.r2dbc.spi,javax.annotation.proces
 sing,javax.sql,javax.tools,javax.xml.bind;version="[2.3,3)",javax.xml.b
 ind.annotation;version="[2.3,3)",javax.xml.bind.annotation.adapters;ver
 sion="[2.3,3)",javax.xml.namespace,javax.xml.parsers,javax.xml.transfor
 m,javax.xml.transform.dom,javax.xml.transform.stream,javax.xml.validati
 on,oracle.jdbc;resolution:=optional,oracle.sql;resolution:=optional,org
 .jooq,org.jooq.conf,org.jooq.exception,org.jooq.impl,org.jooq.migration
 s.xml,org.jooq.migrations.xml.jaxb,org.jooq.tools,org.jooq.tools.csv,or
 g.jooq.tools.jdbc,org.jooq.tools.json,org.jooq.tools.reflect,org.jooq.t
 ypes,org.jooq.util.access,org.jooq.util.ase,org.jooq.util.auroramysql,o
 rg.jooq.util.aurorapostgres,org.jooq.util.bigquery,org.jooq.util.cockro
 achdb,org.jooq.util.cubrid,org.jooq.util.db2,org.jooq.util.derby,org.jo
 oq.util.exasol,org.jooq.util.firebird,org.jooq.util.h2,org.jooq.util.ha
 na,org.jooq.util.hsqldb,org.jooq.util.ignite,org.jooq.util.informix,org
 .jooq.util.ingres,org.jooq.util.jaxb.tools,org.jooq.util.mariadb,org.jo
 oq.util.memsql,org.jooq.util.mysql,org.jooq.util.oracle,org.jooq.util.p
 ostgres,org.jooq.util.redshift,org.jooq.util.snowflake,org.jooq.util.sq
 ldatawarehouse,org.jooq.util.sqlite,org.jooq.util.sqlserver,org.jooq.ut
 il.sybase,org.jooq.util.teradata,org.jooq.util.vertica,org.jooq.util.xm
 l.jaxb,org.postgresql.util;version="[42.2,43)";resolution:=optional,org
 .reactivestreams;version="[1.0,2)",org.w3c.dom,org.xml.sax,org.xml.sax.
 helpers
```

Among those, at least the following should be marked as optional:

- `com.fasterxml.jackson.databind`
- `com.fasterxml.jackson.module.kotlin`
- `com.google.gson`
- `org.postgresql.util`
- `com.microsoft.sqlserver.jdbc` (commercial editions only)
- `com.amazon.redshift.util` (commercial editions only)
- `oracle.sql` (commercial editions only)

The ones that are declared in the `pom.xml` as optional (e.g. `org.postgresql.util` are already optional, so Apache Felix picks those up correctly.

**Comment by ascertrobw** [comment]
So it's not so much Apache Felix here as the OSGi rules for dependency resolution - which implementing frameworks must enforce.

Any package marked in the Import-Package header has to be resolvable at bundle-install time, or the framework will throw an exception. So there's no byte inspection going on, Felix is just following what it sees in the Manifest headers. As you note above, marking those optional (assuming they are) does resolve the specific issue of the jackson kotlin module

**Comment by ascertrobw** [comment]
> 
> 
> Thanks a lot for your report. Looking at that manifest, I wonder how that dependency has sneaked in. Does Apache Felix look at byte code to detect reflective dependencies?? The only place where this package appears is in `org.jooq.impl.Convert`:
> 
> ```java
> Class<?> kotlin = Class.forName("com.fasterxml.jackson.module.kotlin.ExtensionsKt");
> ```
> 
> Can't Apache Felix look at `module-info` and make everything optional that isn't listed in `module-info` explicitly?
> 
> > but also logged a feature request with the r2dbc-spi project.
> 
> Yes, I've seen it: [r2dbc/r2dbc-spi#242](https://github.com/r2dbc/r2dbc-spi/issues/242). What can jOOQ do to improve things in the meantime? This dependency isn't optional...

That's a tough one - I did log an example Manifest in the hope the maintainers would use it. It's actually a very simple manifest which is handy - in fact one of the simplest I've seen.  The ideal would be that the project take this onboard. 

Locally, the way we get around it is with a custom "librarian" which we used to modify Manifests and add/change headers where needed - this is a pretty bloated and intensive process, and quite specific to the non OSGi compliant JAR set we use. An alternative would be to fork the main project and create a parallel build with the required manifest present - less than ideal, but our firm does have Maven Central publisher access, so we could potentially push out a variation on the JAR which includes the headers for others to use.

**Comment by lukaseder** [comment]
> So there's no byte inspection going on, Felix is just following what it sees in the Manifest headers

Are you sure about that? This is what jOOQ's `pom.xml` declares:

```xml
<plugin>
    <groupId>org.apache.felix</groupId>
    <artifactId>maven-bundle-plugin</artifactId>
    <extensions>true</extensions>
    <executions>
        <execution>
            <id>bundle-manifest</id>
            <phase>process-classes</phase>
            <goals>
                <goal>manifest</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <supportedProjectTypes>
            <supportedProjectType>jar</supportedProjectType>
        </supportedProjectTypes>
        <instructions>
            <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
            <Export-Package>*</Export-Package>
            <Import-Package>
                javax.persistence;resolution:=optional,
                org.slf4j;resolution:=optional;version="[1.7,2)",
                *
            </Import-Package>
            <_versionpolicy>[$(version;==;$(@)),$(version;+;$(@)))</_versionpolicy>
        </instructions>
    </configuration>
</plugin>
```

I'm really surprised about all this content showing up in the `MANIFEST.MF`. There must be *some* lookup from byte code in addition to the `pom.xml` classpath. Given the ASM troubles we've had in the past: https://github.com/jOOQ/jOOQ/issues/10150, I'm assuming that Apache Felix must be doing *something*

> less than ideal, but our firm does have Maven Central publisher access, so we could potentially push out a variation on the JAR which includes the headers for others to use.

It would be much better if you could help the r2dbc-spi maintainers maintain this.

**Comment by ascertrobw** [comment]
Sorry - I should have been clearer. There is no byte inspection by the OSGi runtime. Quite a few OSGi projects use various MVN plugins to scan their class &  package stack to generate the headers. In fact under the hood, most use a tool called BND for this, which is the same one we use to fix JARs that have no headers. We're a Gradle site not a MVN one, so I'm no expert - but looking at the above, that <instructions> tag looks very like the BND command to scan the JAR and generate the manifest headers. The ones explicitly listed under <Import-Package> will get included as-is. The * at the end will include everything else scanned from the classes in the JAR. BND has a syntax to suppress some too e.g. to use an example Gradle equivalent we use 

`        instruction 'Import-Package', "!com.sun.*, !sun.misc, *"
`


So yes, there is definitely no runtime inspection going on when Felix loads the JARS - that just follows the strict OSGi rules. But the maven bundle plugin is doing build time inspection to generate the headers.

**Comment by ascertrobw** [comment]
> 
> It would be much better if you could help the r2dbc-spi maintainers maintain this.

Agreed - just add an offer on that to the issue.

**Comment by lukaseder** [comment]
> that instructions tag looks very like the BND command to scan the JAR and generate the manifest headers.

Right, so it's BND not Felix doing it, but still, someone will have to have found that single `Class.forName()` call, because there aren't any other references to that `com.fasterxml.jackson.module.kotlin` package in jOOQ code.

Anyway, what will be the least effortful way for jOOQ to make sure this doesn't happen again in the future? I won't mind new issues each time an OSGi user upgrades to a new version that has a new problem, but if there's an easy way to test things, I'm all ears.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0, 3.15.3 (https://github.com/jOOQ/jOOQ/issues/12411), and 3.14.15 (https://github.com/jOOQ/jOOQ/issues/12412).

**Comment by lukaseder** [comment]
Any early feedback you can provide on these fixed versions would be greatly appreciated!

**Comment by ascertrobw** [comment]
> Anyway, what will be the least effortful way for jOOQ to make sure this doesn't happen again in the future? I won't mind new issues each time an OSGi user upgrades to a new version that has a new problem, but if there's an easy way to test things, I'm all ears.

Yeah, the immediate fix part as you say is fairly easy - add that list of truly optional packages you included above to the exisitng set explicitly fixed in the Import-Package tag in the pom.xml.

Testing/prevention is fiddlier without hand checking the generated manifests for clearly errant cases (like junit, com.sun etc). At a quick scan though, the headers you listed above don't look too bad. There's nothing obvious I'd immediately say to exclude for future proofing.

Assuming the DB variant of our product line gets finalised and approved for release (we're within a month or two of that now), then we'll likely be a test site for quite some time (until/if we ever move away from OSGi, which is not imminent). So we'll be one source of catching issues on updates as happened this time.

**Comment by ascertrobw** [comment]
> 
> 
> Any early feedback you can provide on these fixed versions would be greatly appreciated!

Will do!

**Comment by lukaseder** [comment]
> Testing/prevention is fiddlier without hand checking the generated manifests for clearly errant cases (like junit, com.sun etc). At a quick scan though, the headers you listed above don't look too bad. There's nothing obvious I'd immediately say to exclude for future proofing.

I'm fine with being able to detect changes between jOOQ versions. If there's a library to load the jar file (e.g. after having installed it), and then check the imports against an expected set of imports, fail if something unexpected but not optional is added, then I can at least detect a change, and manually validate if it's a valid change.

> So we'll be one source of catching issues on updates as happened this time.

Thanks for the offer :)

**Comment by ascertrobw** [comment]
> 
> 
> > Any early feedback you can provide on these fixed versions would be greatly appreciated!
> 
> Will do!

Do you have anything like a JitPack URL for pulling commits/branches as if they were a release? Was going to give the fix a spin, but our build system typically wants to pull from one of the Maven repos. My usual workaround for testing commits/patches is via JitPack, but I'm not having much luck getting it to auto build me jooq.jar artefact on the version-3.15.0 branch.

All good if not, I can hang on for the proper 3.15.3 release to test.

**Comment by lukaseder** [comment]
> Do you have anything like a JitPack URL for pulling commits/branches as if they were a release?

```
git clone https://github.com/jOOQ/jOOQ
mvn install
```

**Comment by ascertrobw** [comment]
That was my next port of call - thx

**Comment by ascertrobw** [comment]
> 
> 
> > Any early feedback you can provide on these fixed versions would be greatly appreciated!

Fix looks good. 

Just about to submit a PR to the r2dbc guys for their OSGi headers also.

**Comment by lukaseder** [comment]
Excellent, thanks for the feedback.

**Comment by ascertrobw** [comment]
> 
> 
> > It would be much better if you could help the r2dbc-spi maintainers maintain this.
> 
> Agreed - just added an offer on that to the issue.

Just to close this out the last loose end on this

As an interim - until the r2dbc-spi project accept the PR, or do a fuller version, anyone wanting to use 3.15 under OSGi and needing a published artefact rather than a local MVN build can pull a customised r2dbc-spi with using JitPack for the forked branch where I created the PR:

- URL and info: https://jitpack.io/#ascertrobw/r2dbc-spi/242-osgi-headers-SNAPSHOT
- MVN coords: com.github.ascertrobw.r2dbc-spi:r2dbc-spi:242-osgi-headers-SNAPSHOT

**Comment by lukaseder** [comment]
So, how do I go about writing a test? Assuming I have already installed the `jooq.jar` file in the local repository using `mvn install`, how do I load it as a bundle and check its headers using `biz.aQute.bndlib` or some other library?

I mean, I can figure this out with trial and error, but any help would be appreciated...

**Comment by lukaseder** [comment]
OK, so this hackish test helps find any changes to the `Import-Package` and `Export-Package` manifest entries:

```java
package org.jooq.test;

import java.net.URL;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.Map.Entry;
import java.util.jar.Manifest;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

/**
 * Tests related to our OSGi headers
 *
 * @author Lukas Eder
 */
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class OSGiTest extends AbstractTest {

    @Test
    public void testHeaders() throws Exception {
        boolean manifestFound = false;
        String urlFound = null;
        boolean exportPackageFound = false;
        boolean importPackageFound = false;

        List<URL> urls = new ArrayList<>();
        Enumeration<URL> resources = getClass().getClassLoader().getResources("META-INF/MANIFEST.MF");
        while (resources.hasMoreElements())
            urls.add(resources.nextElement());

        urlLoop:
        for (URL url : urls) {
            String s = url.toString();

            if (s.contains("/jOOQ/") || s.matches(".*jooq-[^/]+\\.jar!")) {
                urlFound = s;
                manifestFound = true;
                exportPackageFound = true;

                Manifest manifest = new Manifest(url.openStream());

                for (Entry<Object, Object> e : manifest.getMainAttributes().entrySet()) {
                    if ("Export-Package".equals(e.getKey().toString())) {
                        exportPackageFound = true;

                        assertEquals("""
                            migrations;version="3.16.0",org.jooq;uses:="io.r2dbc.spi
                             ,javax.sql,org.jooq.conf,org.jooq.exception,org.jooq.impl,org.jooq.migr
                             ations.xml.jaxb,org.jooq.tools.jdbc,org.jooq.util.xml.jaxb,org.reactive
                             streams,org.w3c.dom,org.xml.sax";version="3.16.0",org.jooq.conf;uses:="
                             javax.xml.bind,javax.xml.bind.annotation,javax.xml.bind.annotation.adap
                             ters,org.jooq,org.jooq.util.jaxb.tools";version="3.16.0",org.jooq.excep
                             tion;version="3.16.0",org.jooq.impl;uses:="io.r2dbc.spi,javax.persisten
                             ce,javax.sql,javax.xml.parsers,org.jooq,org.jooq.conf,org.jooq.exceptio
                             n,org.jooq.migrations.xml.jaxb,org.jooq.tools.jdbc,org.jooq.types,org.j
                             ooq.util.oracle,org.jooq.util.xml.jaxb,org.reactivestreams,org.w3c.dom,
                             org.xml.sax";version="3.16.0",org.jooq.migrations.xml;uses:="javax.xml.
                             bind.annotation.adapters,org.jooq";version="3.16.0",org.jooq.migrations
                             .xml.jaxb;uses:="javax.xml.bind,javax.xml.bind.annotation,javax.xml.bin
                             d.annotation.adapters,org.jooq,org.jooq.migrations.xml,org.jooq.util.ja
                             xb.tools";version="3.16.0",org.jooq.tools;uses:="org.jooq,org.jooq.exce
                             ption,org.jooq.impl";version="3.16.0",org.jooq.tools.csv;version="3.16.
                             0",org.jooq.tools.jdbc;uses:="io.r2dbc.spi,javax.sql,org.jooq,org.jooq.
                             conf,org.jooq.impl";version="3.16.0",org.jooq.tools.json;version="3.16.
                             0",org.jooq.tools.reflect;uses:="javax.annotation.processing";version="
                             3.16.0",org.jooq.types;version="3.16.0",org.jooq.util.access;uses:="org
                             .jooq,org.jooq.impl,org.jooq.types";version="3.16.0",org.jooq.util.ase;
                             uses:="org.jooq,org.jooq.impl";version="3.16.0",org.jooq.util.auroramys
                             ql;uses:="org.jooq,org.jooq.types";version="3.16.0",org.jooq.util.auror
                             apostgres;uses:="org.jooq,org.jooq.types";version="3.16.0",org.jooq.uti
                             l.bigquery;uses:="org.jooq";version="3.16.0",org.jooq.util.cockroachdb;
                             uses:="org.jooq,org.jooq.types";version="3.16.0",org.jooq.util.cubrid;u
                             ses:="org.jooq,org.jooq.impl,org.jooq.types";version="3.16.0",org.jooq.
                             util.db2;uses:="org.jooq,org.jooq.impl";version="3.16.0",org.jooq.util.
                             derby;uses:="org.jooq,org.jooq.impl,org.jooq.types";version="3.16.0",or
                             g.jooq.util.exasol;uses:="org.jooq,org.jooq.types";version="3.16.0",org
                             .jooq.util.firebird;uses:="org.jooq,org.jooq.impl,org.jooq.types";versi
                             on="3.16.0",org.jooq.util.h2;uses:="org.jooq,org.jooq.impl,org.jooq.typ
                             es";version="3.16.0",org.jooq.util.hana;uses:="org.jooq,org.jooq.impl,o
                             rg.jooq.types";version="3.16.0",org.jooq.util.hsqldb;uses:="org.jooq,or
                             g.jooq.impl,org.jooq.types";version="3.16.0",org.jooq.util.ignite;uses:
                             ="org.jooq,org.jooq.types";version="3.16.0",org.jooq.util.informix;uses
                             :="org.jooq,org.jooq.impl";version="3.16.0",org.jooq.util.ingres;uses:=
                             "org.jooq,org.jooq.impl,org.jooq.types";version="3.16.0",org.jooq.util.
                             jaxb.tools;uses:="javax.xml.bind.annotation.adapters";version="3.16.0",
                             org.jooq.util.mariadb;uses:="org.jooq,org.jooq.impl,org.jooq.types";ver
                             sion="3.16.0",org.jooq.util.memsql;uses:="org.jooq,org.jooq.types";vers
                             ion="3.16.0",org.jooq.util.mysql;uses:="org.jooq,org.jooq.impl,org.jooq
                             .types";version="3.16.0",org.jooq.util.oracle;uses:="org.jooq,org.jooq.
                             impl,org.jooq.types";version="3.16.0",org.jooq.util.postgres;uses:="org
                             .jooq,org.jooq.impl,org.jooq.types";version="3.16.0",org.jooq.util.reds
                             hift;uses:="org.jooq,org.jooq.impl,org.jooq.types";version="3.16.0",org
                             .jooq.util.snowflake;uses:="org.jooq,org.jooq.types";version="3.16.0",o
                             rg.jooq.util.sqldatawarehouse;uses:="org.jooq,org.jooq.types";version="
                             3.16.0",org.jooq.util.sqlite;uses:="org.jooq,org.jooq.impl,org.jooq.typ
                             es";version="3.16.0",org.jooq.util.sqlserver;uses:="org.jooq,org.jooq.i
                             mpl,org.jooq.types";version="3.16.0",org.jooq.util.sybase;uses:="org.jo
                             oq,org.jooq.impl,org.jooq.types";version="3.16.0",org.jooq.util.teradat
                             a;uses:="org.jooq,org.jooq.types";version="3.16.0",org.jooq.util.vertic
                             a;uses:="org.jooq,org.jooq.impl,org.jooq.types";version="3.16.0",org.jo
                             oq.util.xml.jaxb;uses:="javax.xml.bind.annotation,javax.xml.bind.annota
                             tion.adapters,org.jooq.util.jaxb.tools";version="3.16.0",org.jooq.util.
                             yugabyte;uses:="org.jooq,org.jooq.types";version="3.16.0",xsd;version="
                             3.16.0"
                            """.trim().replace("\n ", "").replace(",", ",\n"), e.getValue().toString().replace(",", ",\n"));
                    }
                    else if ("Import-Package".equals(e.getKey().toString())) {
                        importPackageFound = true;

                        assertEquals("""
                            javax.persistence;resolution:=optional;version="[2.2,3)"
                             ,org.slf4j;resolution:=optional;version="[1.7,2)",com.fasterxml.jackson
                             .databind;resolution:=optional,com.fasterxml.jackson.module.kotlin;reso
                             lution:=optional,com.google.gson;resolution:=optional,com.amazon.redshi
                             ft.util;resolution:=optional,com.microsoft.sqlserver.jdbc;version="[9.2
                             ,10)";resolution:=optional,io.r2dbc.spi,javax.annotation.processing,jav
                             ax.sql,javax.tools,javax.xml.bind;version="[2.3,3)",javax.xml.bind.anno
                             tation;version="[2.3,3)",javax.xml.bind.annotation.adapters;version="[2
                             .3,3)",javax.xml.namespace,javax.xml.parsers,javax.xml.transform,javax.
                             xml.transform.dom,javax.xml.transform.stream,javax.xml.validation,oracl
                             e.jdbc;resolution:=optional,oracle.sql;resolution:=optional,org.jooq,or
                             g.jooq.conf,org.jooq.exception,org.jooq.impl,org.jooq.migrations.xml,or
                             g.jooq.migrations.xml.jaxb,org.jooq.tools,org.jooq.tools.csv,org.jooq.t
                             ools.jdbc,org.jooq.tools.json,org.jooq.tools.reflect,org.jooq.types,org
                             .jooq.util.access,org.jooq.util.ase,org.jooq.util.auroramysql,org.jooq.
                             util.aurorapostgres,org.jooq.util.bigquery,org.jooq.util.cockroachdb,or
                             g.jooq.util.cubrid,org.jooq.util.db2,org.jooq.util.derby,org.jooq.util.
                             exasol,org.jooq.util.firebird,org.jooq.util.h2,org.jooq.util.hana,org.j
                             ooq.util.hsqldb,org.jooq.util.ignite,org.jooq.util.informix,org.jooq.ut
                             il.ingres,org.jooq.util.jaxb.tools,org.jooq.util.mariadb,org.jooq.util.
                             memsql,org.jooq.util.mysql,org.jooq.util.oracle,org.jooq.util.postgres,
                             org.jooq.util.redshift,org.jooq.util.snowflake,org.jooq.util.sqldatawar
                             ehouse,org.jooq.util.sqlite,org.jooq.util.sqlserver,org.jooq.util.sybas
                             e,org.jooq.util.teradata,org.jooq.util.vertica,org.jooq.util.xml.jaxb,o
                             rg.jooq.util.yugabyte,org.postgresql.util;version="[42.2,43)";resolutio
                             n:=optional,org.reactivestreams;version="[1.0,2)",org.w3c.dom,org.xml.s
                             ax,org.xml.sax.helpers
                            """.trim().replace("\n ", "").replace(",", ",\n"), e.getValue().toString().replace(",", ",\n"));
                    }
                }

                break urlLoop;
            }
        }

        assertTrue("Manifest was found in " + urls, manifestFound);
        assertTrue("Export-Package was found in manifest of " + urlFound, exportPackageFound);
        assertTrue("Import-Package was found in manifest of " + urlFound, importPackageFound);
    }
}
```

A test failure isn't necessarily a problem, but at least it helps not to forget anything that requires adaptation in the future.

**Comment by ascertrobw** [comment]
Sorry - missed the earlier post. Yep, that'll act as a safety check at least. I guess the problem with a text comparison is that version strings will move on over time, but as you say as a backstop check, a failure at least indicates something has changed.

Just for info, manually, I tend to run BND from the command line to sanity check stuff e.g. for the recent r2dbc-spi bundle:

```
c:\mnt\Data\gladys\osgi\r2dbc-spi>bnd print gradleBuild\plugins\com.ascert.repackaged.r2dbc-spi_0.8.5.jar
[MANIFEST com.ascert.repackaged.r2dbc-spi_0.8.5]
Bundle-Category                          bundle
Bundle-ContactAddress                    support@ascert.com
Bundle-Description                       r2dbc-spi packaged for OSGi
Bundle-ManifestVersion                   2
Bundle-Name                              r2dbc-spi
Bundle-SymbolicName                      com.ascert.repackaged.r2dbc-spi
Bundle-Vendor                            Ascert, LLC
Bundle-Version                           0.8.5
Export-Package                           io.r2dbc.spi;version="0.8.5"
Import-Package                           javax.annotation.meta;resolution:=optional,javax.annotation
Manifest-Version                         1.0
Require-Capability                       osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))",osgi.extender;resolution:=optional;filter:="(osgi.extender=osgi.serviceloader.processor)",osgi.serviceloader;resolution:=optional;filter:="(osgi.serviceloader=io.r2dbc.spi.ConnectionFactoryProvider)";cardinality:=multiple

[IMPEXP]
Import-Package
  javax.annotation
  javax.annotation.meta                  {resolution:=optional}
Export-Package
  io.r2dbc.spi                           {version=0.8.5}

```

The one thing this is doing (I believe) is also checking the validity. 

We don't do an explicit automated check of this in our env, because the test stages of our CI chain will launch an OSGi framework anyway, and any syntax errors in the headers, or missing packages immediately become apparent there anyway. Would be  a bit of work to setup a clean dummy one to use as a test for jOOQ, but not impossible if of sufficient benefit.

**Comment by lukaseder** [comment]
> that version strings will move on over time

Yeah, the committed version removes the version strings from comparisons, as they're not relevant. Also, I've sorted the contents alphanumerically, just in case.

> but not impossible if of sufficient benefit.

Let's see if the text-based approach prevents further issues. For me, it's good enough. The imports/exports don't change a lot, so there might be 1-2 test failures per minor release.

**Comment by ascertrobw** [comment]
> 
> > but not impossible if of sufficient benefit.
> 
> Let's see if the text-based approach prevents further issues. For me, it's good enough. The imports/exports don't change a lot, so there might be 1-2 test failures per minor release.

Sounds good - it's nice and simple to understand and as you say, covers the immediate bases. The moment I started to think of something more comprehensive, I realised it could potentially be quite a lot of work!

**Comment by lukaseder** [comment]
> I realised it could potentially be quite a lot of work!

Yeah, even discovering the API is a lot of work, and I haven't found any meaningful tutorials in 10 minutes of googling 😅

**Comment by ascertrobw** [comment]
> > I realised it could potentially be quite a lot of work!
> 
> Yeah, even discovering the API is a lot of work, and I haven't found any meaningful tutorials in 10 minutes of googling 😅

Definitely a learning curve - we've been using it probably 20 years. In fact, I was one of the early/original committers with Richard Hall to Oscar, which was what became contributed to Apache Felix. So a lot of it I know well (although some of the latest spec additions not so much). The fiddly bits for me would be MVN - which I just don't know and never use, and how to use it to "invert" the CI test model we use here. We have a set of fixed bundle JARs that we use, which we feed into Gradle as our dependencies. In the jOOQ case, to be as automated as possible, I suspect an automated OSGi startup should be created by using the test/runtime JAR dependencies which MVN calculates for jOOQ. 

Although a sledgehammer approach could just be to have MVN dump all the dependent JARs in a common dir and load the lot. This approach would have caught the recent r2dbc-spi case, since it was an invalid bundle. But it probably wouldn't have caught the "optional kotlin" case though - because MVN would have simply expanded out the full dependency tree and tried to load it (unless MVN has a concept of optional that could also be interrogated).

**Comment by lukaseder** [comment]
> unless MVN has a concept of optional that could also be interrogated

It does, and it's being used already (e.g. `org.postgresql.util` is already declared optional for OSGi), but as I said before, *someone* is reverse engineering jOOQ's reflective `Class.forName("com.fasterxml.jackson.module.kotlin.ExtensionsKt");` statement to figure out the dependency on that kotlin module (or to jackson or gson). We don't declare that reflection-only dependency in Maven.

Maybe this is a sign that using reflection here isn't clean in the first place, but it was a low hanging fruit in jOOQ 3.14.

Anyway. A cost/benefit assessment prohibits excessive investments in setting up an OSGi test infrastructure here, given of how little community interest OSGi has been to jOOQ users so far. I can't investigate this any further at this moment, unless you're interested in sponsoring this?

**Comment by ascertrobw** [comment]
> 
> as I said before, _someone_ is reverse engineering jOOQ's reflective `Class.forName("com.fasterxml.jackson.module.kotlin.ExtensionsKt");` statement 

Yep - that'll be the embedded BND tool in the MVN plugin. 

> Maybe this is a sign that using reflection here isn't clean in the first place, but it was a low hanging fruit in jOOQ 3.14.

Most OSGi sites use a reflection based model - but with the essential exclusions, adapations added manually as you've done. It just gets unmanageable without. 

> 
> Anyway. A cost/benefit assessment prohibits excessive investments in setting up an OSGi test infrastructure here, given of how little community interest OSGi has been to jOOQ users so far. I can't investigate this any further at this moment, unless you're interested in sponsoring this?

Agreed. We're good at this point. I'm not sure sponsorship would be an option, but I'm happy to pitch in and help should a need arise down the line to craft something more elegant.
