### ISSUE TITLE
Concurrency issue when obtaining insert id after store()

### ISSUE THREAD

**Issue by mikymigs** [jOOQ/jOOQ#12401]
Hello,

I'm executing a query like so:
```
MyRecord mRecord = dsl.newRecord(Tables.MY_TABLE);
mRecord.setName("a name");
myRecord.store();
```
and later on I retrieve the insert id like so:
`int insertId = myRecord.getId()`

This code runs fine in single threaded environment but in a highly concurrent execution mode (30-50 threads) I start having issue where the returned ID becomes obsolete. For example:
- returned ID is = 142
- In the database no record exists with ID 142
- I usually find my record a few rows after (e.g ID = 147) 

This is causing issues because I use the ID in queries later on as foreign key and a get foreign key constraint exception because the row does not exist with the specified ID.

Here is the details of my executing environment:
- Java jdk1.8.0_251
- Jooq 3.11.11
- Spring boot 2.1.2.RELEASE
- MariaDB 10.4.10
- mysql-connector-java 8.0.16 
- Hikari connection pool

Any help appreciated!

**Comment by lukaseder** [comment]
Thanks for your message. Does the problem persist with MariaDB 10.5+ and jOOQ 3.14+? I would imagine the native `INSERT .. RETURNING` support could help prevent this issue, see:

- https://mariadb.com/kb/en/insertreturning/
- https://github.com/jOOQ/jOOQ/issues/9212

If upgrading is not an option, make sure you're running the `store()` call in a transaction. If that still doesn't resolve your problem, then you could pre-generate your ID on the client side, instead of the server?

**Comment by mikymigs** [comment]
Thanks a lot for your detailed reply!

Upgrading MariaDB and jOOQ is feasible but complicated. Unfortunately I couldn't afford spending time trying this option without being 100% it would solve the issue.

I had already thought about using transactions but having to pass the configuration object to all sub-queries had discouraged me. But since I didn't have any other option I tried it anyways. It turns out that not only it solved my issue but also helped a great deal on the performance side! The code has become a lot more scalable (adding even more threads improves speed).

Thanks a lot for the help,

**Comment by lukaseder** [comment]
> I had already thought about using transactions but having to pass the configuration object to all sub-queries had discouraged me. But since I didn't have any other option I tried it anyways. It turns out that not only it solved my issue but also helped a great deal on the performance side! The code has become a lot more scalable (adding even more threads improves speed).

Great to hear that this solved the problem. If you're using Spring, you could solve this declaratively without passing around configurations...
