### ISSUE TITLE
ERROR TYPE :Oid.TIMESTAMPTZ, Types.TIMESTAMP 

### ISSUE THREAD

**Issue by inspiredyu** [jOOQ/jOOQ#12419]
in source file: org.postgresql.jdbc.TypeInfoCache
i see 
{"timestamptz", Oid.TIMESTAMPTZ, Types.TIMESTAMP, "java.sql.Timestamp",
          Oid.TIMESTAMPTZ_ARRAY},

mapped Types.TIMESTAMP is not correct, should be Types.TIMESTAMP_WITH_TIMEZONE.
Is there any reason, or it is a bug?

**Comment by lukaseder** [comment]
Thanks for your report. I'm assuming you meant to report this to the pgjdbc driver?
