### ISSUE TITLE
About mysql's lock in share mode statement

### ISSUE THREAD

**Issue by KevinBlandy** [jOOQ/jOOQ#12410]
### Your question:

I want to use the `lock in share mode` statement. So I wrote the following code.

```java
public class SpringCloudApplicationTest {

	@Resource
	private DSLContext dslContext;

	@Test
	@Rollback(value = false)
	@Transactional()
	public void test() throws Exception {
		
		boolean exists = dslContext.select(
					field(
						exists(
							selectOne().from(ADMIN).where(ADMIN.ID.eq(UInteger.valueOf(1))).forShare()
						)
					).as("exists"))
				.fetchOneInto(boolean.class);
	
		System.out.println(exists);
	}
}
```

Generated SQL statement executed with exception in mysql (not `lock in share mode`)

```sql
-- Generated statements that cannot be executed
select (exists (select 1 as `one` from `springcloud.io`.`admin` where `springcloud.io`.`admin`.`id` = 1 for share)) as `exists` from dual

-- The SQL I want
select (exists (select 1 as `one` from `springcloud.io`.`admin` where `springcloud.io`.`admin`.`id` = 1 lock in share mode)) as `exists` from dual
```

But when I look at this method comment, it seems that MYSQL is supported.

```java
@NotNull
@Support({ MARIADB, MYSQL, POSTGRES })
SelectForUpdateOfStep<R> forShare();
```

> `SelectForUpdateOfStep<R> forUpdate();` generates the `lock for update` statement normally.

I've only just started learning JOOQ, a great ORM framework, is there something wrong with my understanding of the methods? How can I solve this problem.

Thank you.

### Versions:

- jOOQ: `3.14.13`
- Java:`11`
- Database (include vendor):`MYSQL 5.7.21`
- OS:`Windos10`
- JDBC Driver (include name if inofficial driver):`com.mysql.cj.jdbc.Driver 8.0.26`

**Comment by lukaseder** [comment]
The correct SQL is being generated for `SQLDialect.MYSQL_5_7` as can be seen here: https://www.jooq.org/translate

![image](https://user-images.githubusercontent.com/734593/132517098-378d53e4-dd12-494e-a86c-b22163ce53c9.png)

Please refer to the dialect version support matrix to see which jOOQ version and edition supports which server version:
https://www.jooq.org/download/support-matrix
