### ISSUE TITLE
I want to query the associated object data together in a query. What should I do?

### ISSUE THREAD

**Issue by bigfacewo** [jOOQ/jOOQ#12429]
### Your question:

I have two tables "grouping" and "user". The "grouping" table has a foreign key "owner_id" associated with the "id" of the "user" table. In fact, I did not create a foreign key in the database. I hope to query the user information associated with "owner_id" when using "jooq". I know that I can query the "grouping" list first, and then traverse to query the "user" information, but this will produce a lot of queries. I hope to query all the information in one query and use the sub query method. I'm new in jooq and i don't know how to solve this problem. Thank you.

### Versions:

- jOOQ: 3.13.6
- Java: 8
- Database (include vendor): mysql5.7.24
- OS: windows
- JDBC Driver (include name if inofficial driver): mysql-connector-java-8

**Comment by lukaseder** [comment]
Thank you very much for your message. What you're looking for is called a `JOIN` see:
https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/join-clause/

**Comment by bigfacewo** [comment]
I know "join", but there are still some differences, which means that I need to query the data association and encapsulate it into an entity, rather than automatically encapsulating the data associated with foreign keys into an entity object.

**Comment by lukaseder** [comment]
Can you be specific about what *exactly* you want to do? It's always good to provide code examples...
