### ISSUE TITLE
Feedback about manual section "create-index-statement"

### ISSUE THREAD

**Issue by ShwetaSrivas** [jOOQ/jOOQ#12426]
I am looking for migrating the sql code that has a syntax "CREATE NONCLUSTERED INDEX..", not sure if it is possible to parse this statement in Jooq.

Thanks,
Shweta
----
See: https://www.jooq.org/doc/latest/manual/sql-building/ddl-statements/create-statement/create-index-statement/

**Comment by lukaseder** [comment]
Thanks a lot for your message. We don't support this syntax yet in our DSL API: https://github.com/jOOQ/jOOQ/issues/9561.

In the meantime, please resort to using plain SQL:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/
