### ISSUE TITLE
DDL export no longer exports INDEX WHERE clause

### ISSUE THREAD

**Issue by juriad** [jOOQ/jOOQ#12428]
### Expected behavior

I extend `TableImpl` manually and declare a partial index (but I can also simulate the same with `CustomTable`). Because the constructor of `IndexImpl` which takes `where` is package private and is almost never called, I created a custom implementation of `Index` interface (or I can hack it with reflection).

Anyway, I have a `Table` which implements `getIndexes()`; one of returned indexes has `where` condition. Then calling:
```
getDsl().ddl(table).queries()
```
creates a `CREATE INDEX` query without `where` condition.

I tracked this to `org.jooq.impl.DDL#createIndex` where the `where` clause is not added and `org.jooq.impl.CreateIndexImpl#CreateIndexImpl` constructor which is 3.14 used to handle `where` specially (vanished in 3.15, see https://github.com/jOOQ/jOOQ/commit/853dca158bfe43b9bbf1e3b7d7621a74601ce1a2#diff-6acb658fda6fac17e4ae1d386d5002e9095f5d2be319f4d0d6689494861be763:
```
        if (index != null) {
            this.table = index.getTable();
            this.sortFields = index.getFields().toArray(EMPTY_SORTFIELD);
            this.where = index.getWhere();
        }
```

The generated SQL contained `where` clause in 3.14, so I consider it bug (I actually find it during upgrade of jOOQ)

Speaking of Indices, it would be cool if `org.jooq.impl.Internal` allowed creation of partial indices without nasty hacks.
Also, is calling `Internal` methods the way to construct keys and indices on `CustomTable`?

### Actual behavior

The generated SQL ignores `where` clause in 3.15

### Steps to reproduce the problem

I can provide mcve but I hope that the description is good enough.

### Versions

- jOOQ: 3.14.8 -> 3.15.2
- Java: 11
- Database (include vendor): postgres
- OS: linux
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your report

> I can provide mcve but I hope that the description is good enough.

Well, since you were using internal API, but didn't disclose how you did that, I'd love to see an MCVE indeed

> Speaking of Indices, it would be cool if `org.jooq.impl.Internal` allowed creation of partial indices without nasty hacks.
> Also, is calling `Internal` methods the way to construct keys and indices on `CustomTable`?

And that would be a feature request, not strictly related to this here. If you'd like this to be tracked, can you please create a new issue? Otherwise, it will be forgotten. Be sure to indicate why you need this, and why you're using internal API.

**Comment by juriad** [comment]
A working MCVE is here: https://github.com/juriad/jOOQ-mcve/blob/1c03a5847153c08785eb73ddd327d60221ee199d/jOOQ-mcve-java/src/test/java/org/jooq/mcve/test/java/JavaTest.java

I'll create a feature request on creation of keys and indices in `CustomTable`. (I don't know any other API except for `Internal` and `AbstractKeys`.

Also in the MCVE I played a bit with `Meta.migrateTo` which does not work ideally for me. I am not sure if they are bugs or I am missing something.

**Comment by juriad** [comment]
I just compiled jOOQ (1.16.0-SNAPSHOT) myself with this patch:
```
diff --git a/jOOQ/src/main/java/org/jooq/impl/DDL.java b/jOOQ/src/main/java/org/jooq/impl/DDL.java
index 7883eaeb3e..bbee995db1 100644
--- a/jOOQ/src/main/java/org/jooq/impl/DDL.java
+++ b/jOOQ/src/main/java/org/jooq/impl/DDL.java
@@ -240,6 +240,7 @@ final class DDL {
                             ? ctx.createUniqueIndex(i)
                             : ctx.createIndex(i))
                     .on(i.getTable(), i.getFields())
+                    .where(i.getWhere())
                 );
 
         return result;
```
And confirmed that then the partial index is then created correctly.

**Comment by lukaseder** [comment]
Thanks a lot for your report and for your patience. I can confirm the `WHERE` clause isn't exported correctly. Will look into this right away.

**Comment by lukaseder** [comment]
A related bug, the interpreter (used e.g. when calling `DSLContext.meta(sql)`) doesn't correctly interpret the `WHERE` clause: https://github.com/jOOQ/jOOQ/issues/13013

**Comment by lukaseder** [comment]
I've planned to release those two versions this afternoon, so the fix will be available soon.
