### ISSUE TITLE
Make Java 17 the baseline for the jOOQ Open Source Edition

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12430]
Java 17 has introduced lots of exciting language features which we can start using in jOOQ's internals and the API, most importantly:

- Sealed types: https://openjdk.java.net/jeps/409
- Records: https://openjdk.java.net/jeps/395

We're already using those features in the Java 17 distribution of jOOQ 3.15 (records, that is), and backport the syntax to Java 11 for the current OSS edition. E.g.

```java
static final record Expr<Q>(Q lhs, QueryPart op, Q rhs) {}
```

Becomes

```
static final /* record */ class Expr<Q> { private final Q lhs; private final QueryPart op; private final Q rhs; public Expr(Q lhs, QueryPart op, Q rhs) { this.lhs = lhs; this.op = op; this.rhs = rhs; } public Q lhs() { return lhs; } public QueryPart op() { return op; } public Q rhs() { return rhs; } @Override public boolean equals(Object o) { if (!(o instanceof Expr)) return false; Expr other = (Expr) o; if (!java.util.Objects.equals(this.lhs, other.lhs)) return false; if (!java.util.Objects.equals(this.op, other.op)) return false; if (!java.util.Objects.equals(this.rhs, other.rhs)) return false; return true; } @Override public int hashCode() { return java.util.Objects.hash(this.lhs, this.op, this.rhs); } @Override public String toString() { return new StringBuilder("Expr[").append("lhs=").append(this.lhs).append(", op=").append(this.op).append(", rhs=").append(this.rhs).append("]").toString(); } }
```

Oracle has announced they will publish LTS releases even more frequently:
https://mreinhold.org/blog/forward-even-faster

Spring 6 will use Java 17 as a baseline in Q4 2022:
https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6

Since our commercial distributions will still support older LTS such as Java 8 or 11, we can push forward with a jOOQ Open Source Edition baseline of Java 17, soon - probably not for jOOQ 3.16 anymore, but 3.17?

**Comment by lukaseder** [comment]
This is really very tempting:

1. It will encourage users to upgrade to Java 17 as well, getting all the benefits
2. Spring Boot 3 might be released before this jOOQ release, depending on the progress of some high effort jOOQ features
3. Maintaining Java 11 support is more and more effort, including because of Java 16's JEP 395 (https://openjdk.java.net/jeps/395) and the new, relaxed rules on local classes, nested classes, etc. (the backports lead to frequent compilation errors...). More effort on the maintenance side => more justification for paid work.

**Comment by lukaseder** [comment]
OK, it is decided. I haven't heard anything negative about this change either here or on twitter, after tempting the community several times with the change:
https://twitter.com/lukaseder/status/1527668954709344258

At the same time, there was positive feedback, including folks having an argument to finally upgrade to Java 17 themselves:
https://twitter.com/eNinjaPL/status/1527673959294160896

**Comment by Menoita99** [comment]
As a follow up to this thread, please update the website to reflect this information: https://www.jooq.org/download/versions

**Comment by lukaseder** [comment]
What's missing?

![image](https://github.com/jOOQ/jOOQ/assets/734593/12fe8987-3b74-4dfa-8d9b-4f2216c4b257)
