### ISSUE TITLE
How to transport data from different Listener

### ISSUE THREAD

**Issue by Alex07221** [jOOQ/jOOQ#12436]
Is there a way to transport some data from different kind of listener  (e.g. from `ExecuteListener ` to `VisitListener` ), so that make some enhancement in jooq? If there have, is it Multithreading safety?

- jOOQ: 3.15.1
- Java: 11

**Comment by lukaseder** [comment]
There currently isn't such a mechanism. You can add a `ThreadLocal` to your `ExecuteListener` though, manage its lifecycle between `ExecuteListener::renderStart` and `ExecuteListener::renderEnd` events, and make it available somehow to your `VisitListener`
