### ISSUE TITLE
Do we need to reset the autocommit of a connection to the original value if we use JDBC connection

### ISSUE THREAD

**Issue by chuanhhoang** [jOOQ/jOOQ#12433]
In the issue #5376, you have this example:
```
// Begin a transaction
ctx.connection(c -> {
    DSLContext ctx2 = ctx.configuration().derive(c);

    // Begin transaction
    c.setAutoCommit(false);
    ctx2.insert()...
    ctx2.update()...
    Savepoint savepoint = c.setSavepoint();
    ctx2.delete()...
    c.commit();
});
```
My question is, you setAutoCommit(false). After the transaction is committed, I don't see if reset the autocommit to the original value of the connection. Is resetting autocommit necessary here? I am using HikariCP with autocommit=true on default.

**Comment by lukaseder** [comment]
It was just a (flawed) example. If you're using JDBC, use JDBC as you're always do, irrespective if you're using it with jOOQ. I've fixed the example:

```java
// Begin a transaction
ctx.connection(c -> {
    DSLContext ctx2 = ctx.configuration().derive(c);

    // Begin transaction
    boolean autoCommit = c.getAutoCommit();

    try {
        c.setAutoCommit(false);
        ctx2.insert()...
        ctx2.update()...
        Savepoint savepoint = c.setSavepoint();
        ctx2.delete()...
        c.commit();
    }
    finally {
        c.setAutoCommit(autoCommit);
    }
});
```

But again, it was just an example. E.g. the savepoint is also useless in the example, but you can imagine a more real-world use-case where it wouldn't be useless...

I hope this helps
