### ISSUE TITLE
Deprecate IGNITE dialect again

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12465]
Support for Apache Ignite was added in jOOQ 3.15 upon popular request. The integration seemed promising at first, but the database product is full of bugs, see:

- Bugs discovered during implementation https://github.com/jOOQ/jOOQ/issues/10551#issuecomment-763807282
- Regressions discovered upon an attempted upgrade from Ignite 2.9.1 to 2.10.0 https://github.com/jOOQ/jOOQ/issues/10551#issuecomment-802845244

A regression like this https://issues.apache.org/jira/browse/IGNITE-14356 seems hard to accept from an RDBMS. It hints at the product being poorly tested. Furthermore, despite having reported many significant bugs (not just edge cases), there had been little feedback, let alone fixes from the Ignite team. I had encountered many more bugs which I hadn't reported, because of the lack of feedback so far, concluding that their SQL integration isn't really production ready.

At Ignite, there is talk about moving from the current H2 based implementation to a Calcite based one, see:

- https://github.com/jOOQ/jOOQ/issues/12107
- https://cwiki.apache.org/confluence/display/IGNITE/Apache+Calcite-powered+SQL+Engine+Roadmap

This certainly makes sense for them, but will likely produce a much different dialect on our side, and thus more work.

With this status quo, we're currently not integration testing our own Ignite integration, meaning that we could break things even on our side without noticing. This is far below our usual QA standards, meaning that we don't really support this dialect, currently.

The solution here is to deprecate the dialect for eventual removal. If the situation improves at Ignite, we can re-consider undeprecating it again. If it doesn't the dialect gets removed after 10 minor releases. At least, with the deprecation, our stance here is documented.

**Comment by paolodedios** [comment]
The regressions you pointed out were eventually fixed by the Ignite team by November 2021.  Slow to respond on their end for sure, but they did address them.  While their SQL conformance is not great, it is widely used and the schema first DDL and DML approach via SQL is the future of their product. 

Regardless, my concern here is to see if there is a way to maintain this integration as a community supported, out-of-tree plugin or extension. I would hate to have to do a rewrite of all my JOOQ queries to use their query native interface right after literally just migrating over to JOOQ.

**Comment by lukaseder** [comment]
Thanks for your feedback, @paolodedios. jOOQ now supports ~30 RDBMS, and covers a vast amount of RDBMS functionality (queries, DML, DDL, procedural logic, etc. etc.). This makes for quite a large integration test matrix. Probably much bigger than any other ORM out there (in both test matrix dimensions).

Things have gotten (much) better since testcontainers, but the integration tests are still time consuming, both when running them, as well as when investigating issues. If an RDBMS itself produces such significant regressions, that means we get a lot of effort to investigate whether it's our fault, or theirs, time *much* better invested elsewhere.

> The regressions you pointed out were eventually fixed by the Ignite team by November 2021. Slow to respond on their end for sure, but they did address them.

Yes, I've noticed. And I don't think it was a coincidence. It happened not too long after I made a clear stance in this issue here.

Though, I don't think it matters. The H2 based SQL implementation doesn't seem robust enough to me, so there's no guarantee we won't have similar regressions again in Ignite 2.11, for example.

3.x certainly looks different, because it's Calcite based: https://ignite.apache.org/docs/3.0.0-alpha/sql/calcite-based-sql-engine, and we're definitely going to explore that again, soon, for all Calcite based dialects: https://github.com/jOOQ/jOOQ/issues/12107

Knowing that a number of SQL engines use a common query engine implementation, and a common base grammar seems more promising, perhaps similar to the existing MySQL dialect category (Aurora, MariaDB, MySQL, SingleStore), or PostgreSQL dialect category (Aurora, CockroachDB, PostgreSQL, Redshift, Yugabyte, Vertica)

> While their SQL conformance is not great, it is widely used and the schema first DDL and DML approach is the future of Ignite.

It is the future, yes. The current dialect is based on H2, which itself breaks compatibility and generates regressions here and there. But H2 adds a lot of value to our own tests, because it has become very standards compliant, is very fast, and allows for integration testing a lot of stuff very quickly, which doesn't necessarily depend on actual dialects. Also, it's immensely popular.

Ignite doesn't check any of those boxes for us, so it's only about end user convenience, and there aren't too many jOOQ/Ignite end users so far, as far as I can tell. This deprecation here in part aims at getting your kind of feedback. Perhaps it's really wrong to remove the dialect again, so the decision hasn't been made yet. So, thanks again for your feedback!

> Regardless, my concern here is to see if there is a way to maintain this integration as a community supported, out-of-tree plugin or extension. 

Everyone can fork jOOQ, there's no problem with that. But who is going to maintain such a fork?

Already now, the quality of the jOOQ Ignite dialect is lacking, compared to other dialects, because we're not integration testing it right now (see rationales above). So, what would a "community driven" fork of this dialect look like? I certainly wouldn't want to build my own application on such a 2-fold brittle basis.

> I would hate to have to do a rewrite of all my JOOQ queries to use their query native interface right after literally just migrating over to JOOQ.

I understand that point of view, and I appreciate you also understand jOOQ's. Rest assured, the deprecation doesn't mean immediate removal. It will take 5 years at least until this dialect is removed. Until then, the new Calcite based dialect will certainly be evaluated, and a final decision can be made. But it also means that until then, it's difficult to make any progress with the dialect, because re-enabling the integration tests is too effortful.

I've seen your comment here as well, regarding making the dialect part of the commercial distributions: https://github.com/jOOQ/jOOQ/issues/10551#issuecomment-1009413180. Will reply there, directly.

**Comment by paolodedios** [comment]
A fork would definitely be hard to keep current with the upstream version.  I was wondering if there was a plugin or extension architecture to make the dialect easier to maintain, but a cursory look of the repository indicates that is not how these integrations work.

Thank your for your thoughtful response on the matter and for giving clarity on the time horizon for any removal action.

**Comment by lukaseder** [comment]
> A fork would definitely be hard to keep current with the upstream version

Yes, and forking a version and sticking with it is always an option for individual users, but not too valuable for the community.

> I was wondering if there was a plugin or extension architecture to make the dialect easier to maintain, but a cursory look of the repository indicates that is not how these integrations work.

I think you underestimate the complexity of maintaining a dialect in jOOQ. Other ORMs avoid this problem by removing 95% of SQL functionality and offering only the bare minimum, which is quite standard compliant everywhere.

But even something seemingly simple as a `UNION` operator, possibly combined with `OFFSET .. FETCH` has produced so many headaches throughout the history of jOOQ, and it doesn't get better as we add support for new features (e.g. SQL/XML or SQL/JSON, which are also very different in each dialect).

There had been ideas like this before, to extract the current SQL generation logic into a templating language, which can be configured in external files. Today, I'm very glad that these ideas were always rejected.
