### ISSUE TITLE
MockFileDatabase example doesn't compile

### ISSUE THREAD

**Issue by nyoung** [jOOQ/jOOQ#12468]
In the examples where you have `MockFileDatabase db =`, i think you should either change that to `MockFileDatabase provider =` or change `new MockConnection(provider)` to `new MockConnection(db)`

```
MockFileDatabase db = new MockFileDatabase(new MockFileDatabaseConfiguration()
    .source(new File("/path/to/db.txt"))
    .patterns(true) // Turn on regular expressions here
);
MockConnection connection = new MockConnection(provider);
```
----
See: https://www.jooq.org/doc/latest/manual/sql-execution/mock-file-database/

**Comment by lukaseder** [comment]
Thanks a lot for your feedback. You're right of course. Fixed. The manual will be re-published in a few hours with the fix.
