### ISSUE TITLE
A bug in which the precision of localdatetime is not parsed properly during update query

### ISSUE THREAD

**Issue by jaehyunup** [jOOQ/jOOQ#12475]
### Expected behavior. 

It seems that precision parsing of Localdatetime is not working properly when updating columns through update query.

### Actual behavior

I want to store localdatetime up to millis. But the precision that actually goes into the database is 3. The code of the table generated through the jooq generator also confirmed that the decision was 6.

But when I insert Java's Localdatetime.now() as a table value, the precision is still 3. or sometimes 4

### Steps to reproduce the problem
1. table class generate with JOOQ Generator

2. example part of generated table class column with jooq codegen(kotlin).
`val UPDATED: TableField<YOUR_TABLE_RECORD, LocalDateTime?> = createField(DSL.name("updated"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "update time")`

3. and Excute update query with dslContext and table class
`dslContext.update(USER_TABLE)
            .set(USER_TABLE.UPDATED, java.time.LocalDateTime.now())
            .where(BLAHBLAH)`

4. As a result of checking the update field entered in the database (postgreSQL)
`2021-09-30T13:58:00.222` or `2021-09-30T13:58:00.2224`

5. [My Solution] 
It was solved by using the DSL.currentLocalDateTime() java class. When localDatetime is injected in this way, millis datetime with precision of 6, the way I wanted, is entered into the database.

However. it's unnatural I think this behavior is some kind of bug

- jOOQ: jooq-kotlin-3.14.8 , jooq-codegen-3.14.8
- Java: Not java, Kotlin 1.5.21-Release
- Database (include vendor): PostgreSQL (AWS)
- OS: MAC Catalina
- JDBC Driver (include name if inofficial driver): r2dbc-0.8.7.RELEASE

**Comment by lukaseder** [comment]
Thanks a lot for your report. This very similar issue was fixed in jOOQ 3.16.0, 3.15.2 (#12226), and 3.14.14 (#12227):
https://github.com/jOOQ/jOOQ/issues/12225

Can you please check if upgrading jOOQ to 3.14.14 fixes the issue for you?
