### ISSUE TITLE
PostgreSQL Translation Error

### ISSUE THREAD

**Issue by arvindnitharwal** [jOOQ/jOOQ#12478]
### translator not able to translates this query:

```sql
SELECT * FROM public.notifications where reference_object ->> 'questionId' ='0e75ce19-d124-4d86-84e8-10362c38c972'


```error
Identifier expected: [1:60] ...FROM public.notifications where reference_object -[*]>> 'questionId' ='0e75ce19-d124-4d86-84e8-10362c38c972';

**Comment by lukaseder** [comment]
Thanks a lot for your report. This has been a frequent feature request, see also: https://github.com/jOOQ/jOOQ/issues/10018. We'll add support for this syntax, soon.

Closing as duplicate of https://github.com/jOOQ/jOOQ/issues/10018
