### ISSUE TITLE
ParsingConnection's PreparedStatement.getMetaData should be able to produce ResultSetMetaData prior to execution

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12481]
The Javadoc of `PreparedStatement::getMetaData` reads:

> Because a PreparedStatement object is precompiled, it is possible to know about the ResultSet object that it will return without having to execute it. Consequently, it is possible to invoke the method getMetaData on a PreparedStatement object rather than waiting to execute it and then invoking the ResultSet.getMetaData method on the ResultSet object that is returned.

We currently expect the statement to have been executed already (and thus the underlying statement to have been prepared). If not, we throw a `SQLException` with message *"No PreparedStatement is available yet"*. We do this to be able to use bind value types from actual bind values (see #11512).

However, it would be useful for this particular method to be better than the status quo. We can make an attempt at parsing the statement without (or with incomplete) bind value type information and create a `ResultSetMetaData` object ourselves, if there's none available by the driver. Alternatively, we could prepare a dummy statement for this action (which can be thrown away, should the *actual* prepare statement call produce a different SQL string)

Caveats:

- The behaviour might be different from that of the driver, producing different meta data than expected.
- This needs to be governed (as always) by a `Settings` flag

**Comment by lukaseder** [comment]
The status quo can be annoying, as it breaks existing JDBC code where the `ParsingConnection` is used as a proxy.

**Comment by wal1dcha1b** [comment]
Can this issue be included in a 3.16 version early fix ?

**Comment by lukaseder** [comment]
Thanks for the ping @wal1dcha1b. I was going to include this in 3.16, don't know why it got off my radar. I'll check it out today and backport to 3.16.2 if possible. I don't see any regression risk as it's a single method that's affected, and the current behaviour is just throwing an exception.

**Comment by wal1dcha1b** [comment]
Thanks

**Comment by lukaseder** [comment]
From the issue description:

> Alternatively, we could prepare a dummy statement for this action (which can be thrown away, should the _actual_ prepare statement call produce a different SQL string)

This is the solution I'll implement. Emulating the prepared statement completely, without connecting to the backing database, risks producing subtly different behaviour (e.g. upper case / lower case column names, labels, etc.). The drawback is that if the SQL string depends on the bind values, then the prepared statement will be prepared twice just for that purpose. I guess that's acceptable for now. If it will ever prove to be a performance issue, this could still be addressed, but I doubt it.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0 and 3.16.2 (https://github.com/jOOQ/jOOQ/issues/12856). You can access the fix after tonight's nightly build via the next 3.16.2-SNAPSHOT version from here: https://www.jooq.org/download/versions

I'm planning a 3.16.2 release soon, probably next week. Your early feedback about potential issues that may remain would be greatly appreciated!

**Comment by lukaseder** [comment]
For early access, you can patch your distribution using https://github.com/jOOQ/jOOQ/commit/eacfbee5405231f8b3f20e4541ac0c2e4d85deb9.patch

**Comment by wal1dcha1b** [comment]
Thank you so much for your speedy intervention.

**Comment by lukaseder** [comment]
The integration tests suites implemented here have helped find a regression in the `sqlite-jdbc` driver: https://github.com/xerial/sqlite-jdbc/issues/811

Not strictly relevant to your work, but definitely a good thing for others.
