### ISSUE TITLE
Clarify whether .offset(..) starts from 0 or 1

### ISSUE THREAD

**Issue by adrianmsmith** [jOOQ/jOOQ#12492]
On https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/limit-clause/ it states:

> `create.select().from(BOOK).limit(1).offset(2).fetch();`
> .... starting with the 2nd book (starting at offset 0!). 

I feel this wording of the explanation is confusing. 

* "Starting at offset 0" implies 0-based,
* yet `.offset(2)` fetching the 2nd book implies it uses 1-based numbering. It is normal in language to refer to "the first thing", "the second thing" etc. (i.e. 1-based)

Perhaps consider something like: 

> ... starting with the 3rd book (offset uses 0-based numbering)

In addition, I would suggest adding this to the .offset method Javadoc so it's right there in the IDE when you're writing the code.

You may wonder why anyone would think that offset might used 1-based numbering. Unfortunately I've often found a lot of DB stuff starts with 1 e.g. substr in oracle. So I'm always uncertain and like to check.

**Comment by lukaseder** [comment]
Thanks a lot for your feedback. I agree, that wording is confusing. Will think about a fix.

The general rule of thumb in SQL is:

- "Indexes" are 1-based
- "Offsets" are 0-based (unlike the word index, the word offset really implies 0-based ness)

**Comment by lukaseder** [comment]
So, as far as the manual is concerned, it will suffice to change the wording to:

> This will limit the result to 1 books skipping the first 2 books (offset 2)

I think that translating the word "offset" to "skipping" explains it better than doing some 0-based to 1-based arithmetic. Humans are terrible at these things 😅

For good measure, I'll add an `ORDER BY` clause to make it more clear, too. The manual will be adapted for all jOOQ versions. The Javadoc only for the latest one, 3.16.0

**Comment by lukaseder** [comment]
The Javadoc omission is probably just an oversight from https://github.com/jOOQ/jOOQ/issues/8775, and look who created that issue! :)
