### ISSUE TITLE
Add new Functions.nullOnAllNull(FunctionN) and nullOnAnyNull(FunctionN)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12513]
Our newly introduced `FunctionN` types could profit from some additional ergonomics in case they need to deal with null values. A new class `Functions` could be introduced, with:

```java
public class Functions {
    // ...
    public static final <T1, T2, T3, R> Function3<T1, T2, T3, R> nullOnAllNull(
        Function3<? super T1, ? super T2, ? super T3, ? extends R> function
    ) {
        return (t1, t2, t3) -> t1 == null && t2 == null && t3 == null ? null : function.apply(t1, t2, t3);
    }

    public static final <T1, T2, T3, R> Function3<T1, T2, T3, R> nullOnAnyNull(
        Function3<? super T1, ? super T2, ? super T3, ? extends R> function
    ) {
        return (t1, t2, t3) -> t1 == null || t2 == null || t3 == null ? null : function.apply(t1, t2, t3);
    }
}
```

This would allow for using null-safe method references like this, which is a use-case when a table is left-joined:

```java
row(
    EMPLOYEES.ID,
    EMPLOYEE.NAME,
    EMPLOYEE.TITLE
).mapping(nullOnAllNull(Employee::new))
```

----
See also:
- https://github.com/jOOQ/jOOQ/issues/12512

**Comment by lukaseder** [comment]
Created an additional issue for this: https://github.com/jOOQ/jOOQ/issues/12530

**Comment by matt-snider** [comment]
@lukaseder Thank you for your help and being so responsive. Of course you're right, and it makes way more sense to have `Function1` extends `Function`, I didn't think of that somehow.

**Comment by matt-snider** [comment]
I realized that in many cases what I really need is `nullOnFirstNull()` and neither `nullOnAnyNull()` nor `nullOnAllNull()` will work.

When a table contains optional columns that are sometimes null, we can't use `nullOnAnyNull()`. When a left-joined table is combined with data from the right table to form a nested row, we can't use `nullOnAllNull()`.

This is an example of such a scenario

```java
// USERS gets left joined with EMPLOYEES. Not every user is an employee.
row(
  // If this is null, there is no employee, i.e. nullOnFirstNull()
  EMPLOYEES.ID,                           
  EMPLOYEES.NAME,
  EMPLOYEES.AGE,
  EMPLOYEES.START_DATE,
  // This is null unless an employee has quit. so nullOnAnyNull() won't work here
  EMPLOYEES.END_DATE, 
  // The employee might have a work email, otherwise use their personal user email.
  // Since this will always be set even when there is no EMPLOYEES record,
  // nullOnAllNull() won't work either.
  coalesce(EMPLOYEES.EMAIL, USERS.EMAIL).as("email")
);
```

Do you think it makes sense to also include `nullOnFirstNull()` in JOOQ? The ID is very often the first column, so this could be useful for many use cases (i.e. left-joins). But I also understand if you think it's too specific.
