### ISSUE TITLE
Parser should support PERCENTILE_CONT / PERCENTILE_DISC with expressions as percentiles

### ISSUE THREAD

**Issue by victornoel** [jOOQ/jOOQ#12520]
### Expected behavior

I think this should be correctly parsed by jooq (at least with postgresql dialect):
```sql
SELECT PERCENTILE_DISC(T.percentile) WITHIN GROUP(ORDER BY T.value)
FROM T
```

### Actual behavior

I get this error (demonstrable on https://www.jooq.org/translate/):
```
Unsigned numeric literal expected: [1:24] SELECT PERCENTILE_DISC([*]percentile) WITHIN GROUP(ORDER BY value)
FROM T
```

### Versions

- jOOQ: at least 3.15.3
- Java: Java 11
- Database (include vendor): postgresql

**Comment by victornoel** [comment]
I may have oversimplified the query to show the problem, so maybe my example is not semantically correct, but I found another semantically correct query that fails the same way from https://leafo.net/guides/postgresql-calculating-percentile.html:
```sql
select k, percentile_disc(k) within group (order by things.value)
from things, generate_series(0.01, 1, 0.01) as k
group by k
```

**Comment by lukaseder** [comment]
However, we won't be able to translate it to other dialects yet, if they don't support expressions as arguments.
