### ISSUE TITLE
TruncDate support QUARTER and WEEK 

### ISSUE THREAD

**Issue by fangniude** [jOOQ/jOOQ#12534]
### Use case:

In PostgreSQL, group by date_trunc field 
``` sql
select date_trunc('year', birth_date) y, date_trunc('quarter', birth_date) q
from student
group by y, q
```

### Possible solution you'd like to see:
``` java
DSL.trunc(field, DatePart.QUARTER) 
DSL.trunc(field, DatePart.WEEK)
```

**Comment by lukaseder** [comment]
Thank you very much for your suggestion.

This is a duplicate of https://github.com/jOOQ/jOOQ/issues/8418
