### ISSUE TITLE
How to convert data into Result<Record> data type?

### ISSUE THREAD

**Issue by themechanicalcoder** [jOOQ/jOOQ#12552]
I  am working on a large project in which the functions I want to use, accept data in the form of `List<Result<Record>>` and then send it to frontend or convert to csv. 

I am receiving data in the form of `List<Object>` and I want to convert data from `List<Object>` to `List<Result<Record>>`. How to do it? 

```java
public class Object {
  int x;
  string str;
  float f; 
}
```

**Comment by themechanicalcoder** [comment]
Hi, I am querying data from athena using jdbc, is there a way to convert Resultset that I receive from athena to List<Result<Record>>.

**Comment by lukaseder** [comment]
What's not working with the examples from that link?

**Comment by themechanicalcoder** [comment]
> What's not working with the examples from that link?

`Result<Record> result = DSL.using(connection).fetch(rs);`
Can I use athena connection here.

**Comment by themechanicalcoder** [comment]
`Field<Integer> x = ...;
`
Also can you please tell me how to instantiate this.

**Comment by lukaseder** [comment]
> Also can you please tell me how to instantiate this.

Check this out: https://github.com/jOOQ/jOOQ/issues/12552#issuecomment-950896425

**Comment by themechanicalcoder** [comment]
> > Also can you please tell me how to instantiate this.
> 
> Check this out: [#12552 (comment)](https://github.com/jOOQ/jOOQ/issues/12552#issuecomment-950896425)

what is the difference between these two
Field<String> field2 = field(name("table name", "column name"), String.class);
Field<String> field = DSL.val("Hello World"); 

Also, from which package is name coming in the first example.
