### ISSUE TITLE
Connection leak when ExecuteListener::fetchEnd throws an exception

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12568]
When an `ExecuteListener::fetchEnd` method throws an exception (because of a bug or to abort further processing), then we have a connection leak, because `CursorImpl.CursorResultSet::close` doesn't call `Tools::safeClose`, which returns the `Connection` to the `ConnectionProvider`.

This already broke in the past, but for different reasons, see #3234. Best write some integration tests that check if any exception can produce a connection leak (which must never happen).

See also https://github.com/jOOQ/jOOQ/issues/12564, which helped discover this flaw.

**Comment by alf** [comment]
When can we expect 3.15.5? This leak is a bit annoying.

**Comment by lukaseder** [comment]
The plan was to release 3.15.5 this afternoon

**Comment by lukaseder** [comment]
Just in case, for next time, you're aware of the nightly snapshot builds available from here? https://www.jooq.org/download/versions

**Comment by lukaseder** [comment]
jOOQ 3.15.5 has been released with this fix. Thanks again for your report.
