### ISSUE TITLE
ParamType.INLINED produces wrong behaviour for cacheParsingConnection

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12596]
The `Settings.cacheParsingConnection` behaviour is broken whenever we inline input bind values for two reasons:

- [x] Users specify `ParamType.INLINED` or `StatementType.STATIC_STATEMENT`. This should be easy to fix
- [ ] There is a special type of output syntax where bind values aren't permitted by the output dialect, and we thus choose to inline. This could be quite tricky to fix

Depending on the feasibility of each fix, I might split this issue into two, later.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.5 (https://github.com/jOOQ/jOOQ/issues/12597).

**Comment by lukaseder** [comment]
This fix is for global flags, which are easy to get right. Internally inlined bind values are harder to detect, and will be fixed in a separate issue: https://github.com/jOOQ/jOOQ/issues/12598

**Comment by wal1dcha1b** [comment]
The wrong behaviour is produced with the batch insert even when disabling the cache.

**Comment by lukaseder** [comment]
Thanks, @wal1dcha1b. I'll look into this, soon
