### ISSUE TITLE
Jackson MismatchedInputException on nested JSON with MariaDB (backslash is added on JSON subarray)

### ISSUE THREAD

**Issue by JayAhn2** [jOOQ/jOOQ#12627]
### Expected behavior
`Result`
```
{
   "id":28584990277632,
   "active":1,
   "name":"ABC",
   "typeId":1,
   "nutrients":[{"id": 28585010200576, "type": "CARBOHYDRATE", "amount": 200.00}],
}
```

### Actual behavior
`Generated SQL`
```sql
SET @t = @@group_concat_max_len;
SET @@group_concat_max_len = 4294967295;
SELECT JSON_OBJECT('id', `dbname`.`food`.`id`,
                   'active', `dbname`.`food`.`active`,
                   'name', `dbname`.`food`.`name`,
                   'nutrients', (SELECT JSON_MERGE_PRESERVE('[]', CONCAT('[', GROUP_CONCAT(
                JSON_OBJECT('id', `dbname`.`food_nutrient`.`id`, 'type',
                            `dbname`.`food_nutrient`.`type`,
                            'amount', `dbname`.`food_nutrient`.`amount`) SEPARATOR ','), ']'))
                                 FROM `dbname`.`food_nutrient`
                                 WHERE `dbname`.`food_nutrient`.`food_id` = `dbname`.`food`.`id`))
FROM `dbname`.`food`
WHERE `dbname`.`food`.`id` = 28584990277632;
SET @@group_concat_max_len = @t;;
```
```
{
   "id":28584990277632,
   "active":1,
   "name":"ABC",
   "typeId":1,
   "nutrients":"[{\"id\": 28585010200576, \"type\": \"CARBOHYDRATE\", \"amount\": 200.00}]",
}
```

### Steps to reproduce the problem
In MySQL, the backslash is not added, and it is deserialized without any issue, but in MariaDB, the above json result cannot be deserialized due to backslash.

As I found in the MariaDB ticket(https://jira.mariadb.org/browse/MDEV-13701), Backlash would be added when we use `concat()` or `group_contact()` as it returns string. 

Could you help me with this issue?

### Versions

- jOOQ: 3.15.4
- Java: OpenJDK 11
- Database (include vendor): MariaDB
- OS: Mac
- JDBC Driver (include name if inofficial driver): MariaDB

**Comment by JayAhn2** [comment]
I found the reason, the dialect of JOOQ was set to mysql...... with mariaDB works great.

**Comment by lukaseder** [comment]
Great to hear that. Yes, the two database products are fixing various weird issues in this area at different paces!
