### ISSUE TITLE
typo in jOOQ-academy setup script

### ISSUE THREAD

**Issue by johnrtian** [jOOQ/jOOQ#12639]
There is an extraneous comma at the end of line 34 (`fk_t_book_author_id`) in the db-h2.sql setup script:
https://github.com/jOOQ/jOOQ/blob/e77df40080b9f73a2da1b7436ee875ad2973731c/jOOQ-examples/jOOQ-academy/src/main/resources/db-h2.sql#L25-L36

This causes `maven clean install` in jOOQ-academy to fail:
```
[ERROR] Failed to execute goal org.codehaus.mojo:sql-maven-plugin:1.5:execute (create-database-h2) on project jooq-academy: Syntax error in SQL statement "
...
[ERROR]  CONSTRAINT PK_T_BOOK PRIMARY KEY (ID),
[ERROR]  CONSTRAINT FK_T_BOOK_AUTHOR_ID FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID),
[ERROR]  )[*]
[ERROR]  "; expected "identifier"; SQL statement:
[ERROR]  
```

### Versions
- jOOQ: 3.16.0

**Comment by lukaseder** [comment]
Thanks a lot for your report. It seems as though a trailing comma feature must have been removed from a more recent H2 version. I recall the original H2 author being a big fan, and the current primary maintainer being quite the opposite of a fan 😅
