### ISSUE TITLE
PostgreSQL CockroachDB CodeGen Error - unknown function: information_schema._pg_char_max_length()

### ISSUE THREAD

**Issue by samueldlightfoot** [jOOQ/jOOQ#12635]
### Expected behavior

Code generation should succeed and create model classes.

### Actual behavior

Error thrown during generation.

`Caused by: org.jooq.exception.DataAccessException: SQL [with recursive domains(domain_id, base_id, typbasetype, src) as (select d.oid, d.oid, d.typbasetype, case when c.oid is not null then array[pg_get_constraintdef(c.oid)] end from pg_catalog.pg_type as d join pg_catalog.pg_namespace as n on n.oid = d.typnamespace left outer join pg_catalog.pg_constraint as c on d.oid = c.contypid where (d.typtype = ? and n.nspname in (?, ?, ?, ?, ?)) union all select domains.domain_id, d.oid, d.typbasetype, case when c.conbin is null then domains.src else array_append(domains.src, pg_get_constraintdef(c.oid)) end from domains join pg_catalog.pg_type as d on domains.typbasetype = d.oid left outer join pg_catalog.pg_constraint as c on d.oid = c.contypid) select n.nspname, d.typname, d.typnotnull, d.typdefault, b.typname, information_schema._pg_char_max_length(d.typbasetype, d.typtypmod) as character_maximum_length, information_schema._pg_numeric_precision(d.typbasetype, d.typtypmod) as numeric_precision, information_schema._pg_numeric_scale(d.typbasetype, d.typtypmod) as numeric_scale, domains.src from pg_catalog.pg_type as d join domains on (domains.typbasetype = ? and domains.domain_id = d.oid) join pg_catalog.pg_type as b on domains.base_id = b.oid join pg_catalog.pg_namespace as n on n.oid = d.typnamespace where (d.typtype = ? and n.nspname in (?, ?, ?, ?, ?)) order by n.nspname, d.typname]; ERROR: unknown function: information_schema._pg_char_max_length()`

### Steps to reproduce the problem

- If the problem relates to code generation, please post your code generation configuration

```
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.15.0.xsd">
	<jdbc>
		<driver>org.postgresql.Driver</driver>
		<url>jdbc:postgresql://localhost:26257/payment?sslmode=disable</url>
		<user>sam</user>
		<password>pw</password>
	</jdbc>

	<generator>
		<database>
			<name>org.jooq.meta.postgres.PostgresDatabase</name>
			<includes>.*</includes>
			<inputSchema>public</inputSchema>
		</database>

		<generate/>

		<target>
			<packageName>com.example.cockroachpoc.model</packageName>
			<directory>/path/to/your/dir</directory>
		</target>
	</generator>
</configuration>
```

- If the problem relates to upgrades, please check if your RDBMS version is still supported by jOOQ: https://www.jooq.org/download/support-matrix
- A complete set of DDL statements can help re-create the setup you're having
- An MCVE can be helpful to provide a complete reproduction case: https://github.com/jOOQ/jOOQ-mcve

### Versions

- jOOQ: 3.14.15
- Java: 11.0.5
- Database (include vendor): CockroachDB
- OS: WIndows
- JDBC Driver (include name if inofficial driver): Postgres

**Comment by lukaseder** [comment]
Thanks for your report. Does it work for you if you're using the `org.jooq.meta.cockroachdb.CockroachDBDatabase` instead of the `org.jooq.meta.postgres.PostgresDatabase`

**Comment by samueldlightfoot** [comment]
Thanks for the quick response.

I'm using the open source version which I'm assuming from the error message means does not support the CRDB database.

`09:58:29.413 [main] ERROR org.jooq.codegen.GenerationTool - Error in file: /jooq-config.xml. Error : Your configured database type was not found: org.jooq.meta.cockroachdb.CockroachDBDatabase. This can have several reasons:
- You want to use a commercial jOOQ Edition, but you pulled the Open Source Edition from Maven Central.`

**Comment by lukaseder** [comment]
Ah, yes indeed. To use CRDB, please use the jOOQ Professional Edition, or the free trial edition. You can find the supported database products per edition here:
https://www.jooq.org/download/#databases
