### ISSUE TITLE
OracleDatabase::sequences produces query that doesn't work on older ojdbc driver versions

### ISSUE THREAD

**Issue by jorn86** [jOOQ/jOOQ#12638]
### Expected behavior
Generator should not crash

### Actual behavior
Generator crashes with `DataAccessException: <snip> Error while reading field: "SYS"."ALL_SEQUENCES"."CYCLE_FLAG"`

### Steps to reproduce the problem
I checked in my database, and the actual values in this column are "Y" and "N". The code in `OracleDatabase#sequences` is `ALL_SEQUENCES.CYCLE_FLAG.coerce(SQLDataType.BOOLEAN)`. I made a subclass and changed that to `DSL.field(ALL_SEQUENCES.CYCLE_FLAG.equal("Y"))`, and that makes it work correctly on my database.

Now I have to admit this database is heavily customized and the schema is not under my control. If this behaviour is unique to this Oracle instance, I can live with a patched `OracleDatabase` class (and thanks for making that easy to do). But I can't judge if that's the case, so I'll just report this and see what you think.

### Versions
- jOOQ: 3.15.4
- Java: 8
- Database (include vendor): Oracle 19

**Comment by lukaseder** [comment]
Thanks for your report.

That shouldn't crash and doesn't in our integration tests. `Y` and `N` are valid boolean values. When I run this on a schema containing:

```sql
create sequence y cycle maxvalue 100;
create sequence n nocycle;
```

I get:

```java
public class Sequences {

    /**
     * The sequence <code>TEST.N</code>
     */
    public static final Sequence<BigInteger> N = Internal.createSequence("N", Test.TEST, SQLDataType.DECIMAL_INTEGER(38).nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>TEST.Y</code>
     */
    public static final Sequence<Byte> Y = Internal.createSequence("Y", Test.TEST, SQLDataType.TINYINT.nullable(false), null, null, null, 100, false, null);
```

So, while the generator doesn't crash, it doesn't produce the right values for this flag either.

Can you please post the stack trace of `<snip>`, as well as possibly help reproduce the crash with a minimal schema?

**Comment by lukaseder** [comment]
I've created a separate issue about the code generation flaw: https://github.com/jOOQ/jOOQ/issues/12640

**Comment by jorn86** [comment]
Sorry for the late reply, I haven't been at work for a few days.

The machine I'm running this on isn't connected to the internet, so unfortunately I can't copy/paste the entire stacktrace. But I'll try to highlight the interesting parts:

```
org.jooq.codegen.GeneratorException: Error generating code for catalog
... JavaGenerator
... GenerationTool
caused by ... DataAccessException: SQL [select null catalog, ... SYS.ALL_SEQUENCES.CYCLE_FLAG, ... from SYS.ALL_SEQUENCES  where ... ]; Error while reading field: "SYS"."ALL_SEQUENCES"."CYCLE_FLAG" // this is the only occurrence of CYCLE_FLAG in the query
at org.jooq.meta.AbstractDatabase.onError
at org.jooq.meta.AbstractDatabase.getSequences
at org.jooq.meta.AbstractDatabase.getSequences
at org.jooq.codegen.JavaGenerator.generateSchemaIfEmpty
caused by DataAccessException with the same message & query
caused by DataAccessException with the same message & query
caused by SQLException with the same query
caused by SQLException: Fail to convert to internal representation
at oracle.jdbc.driver.CharCommonAccessor.getBoolean
at oracle.jdbc.driver.T4CVarcharAccessor.getBoolean
at oracle.jdbc.driver.OracleResultSetImpl.getBoolean
at org.jooq.tools.jdbc.DefaultResultSet.getBoolean
```

I don't have access to the code that generates the schema, but I can run a query against my database or inspect it with Oracle SQL developer. I'm not a DBA or Oracle expert so please be specific :-)

**Comment by lukaseder** [comment]
Oh, I see - might be that we're relying on a more recent ojdbc feature? What exact driver version are you using?

**Comment by jorn86** [comment]
I'm using `com.oracle.database.jdbc:ojdbc:11.2.0.4`

**Comment by jorn86** [comment]
... and having said that, I'm going to see if I can upgrade to `com.oracle.database.jdbc:ojdbc8:21.3.0.0`. We're running on JDK8 so that should be doable.

**Comment by lukaseder** [comment]
I see, so that could be it. Would be interesting if you can confirm this. In the meantime, I'll just replace the coercion by your suggestion...

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.5 (https://github.com/jOOQ/jOOQ/issues/12671)

**Comment by jorn86** [comment]
@lukaseder I can confirm that updating to `com.oracle.database.jdbc:ojdbc8:21.3.0.0` also resolves the issue!

**Comment by lukaseder** [comment]
Very good, thanks a lot for the feedback!

**Comment by lukaseder** [comment]
jOOQ 3.15.5 has been released with this fix. Thanks again for your report
