### ISSUE TITLE
How to unquote a json value?

### ISSUE THREAD

**Issue by oclay1st** [jOOQ/jOOQ#12643]
What is the proper way to generate something like this on MySQL  ```json_unquote(json_extract(`name`, '$.en') ?```

 current field: ```jsonValue(USER.NAME, "$.en").as("name")``` 
 resturns ```"Jhon"```  
 expected ```Jhon``` without quotes

**Comment by lukaseder** [comment]
You can always resort to using [plain SQL templating](https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/) if there's a vendor specific SQL feature that jOOQ does not yet support.
