### ISSUE TITLE
Add EnumType.<E extends EnumType>lookupLiteral(Class<E>, String) and generate E.lookupLiteral(String) methods

### ISSUE THREAD

**Issue by andredasilvapinto** [jOOQ/jOOQ#12663]
Java's native `enum.valueOf("string")` uses the name of the enum, not the literal. Automatically generated enums can have differences between the name of enum and the literal value (e.g. Java can't use `-` in the enum name), which breaks `valueOf`.

**Comment by lukaseder** [comment]
Thanks for your message. Yes, you cannot use `valueOf()` to look up literals, only to look up the generated `Enum::name`. But what is it that you're asking here?

**Comment by lukaseder** [comment]
A generated `lookup(String literal)` method on each generated enum?

**Comment by andredasilvapinto** [comment]
exactly!

**Comment by lukaseder** [comment]
Yeah, why not...

**Comment by lukaseder** [comment]
In the meantime, a simple utility like this will do the trick for you:

```java
final class EnumTypes {

    private static final Map<Class<?>, Map<String, EnumType>> LOOKUP = new ConcurrentHashMap<>();

    @SuppressWarnings("unchecked")
    static <E extends Enum<E> & EnumType> E lookupLiteral(Class<E> enumType, String literal) {
        return (E) LOOKUP.computeIfAbsent(enumType, t ->
            Stream.of(enumType.getEnumConstants()).collect(Collectors.<E, String, EnumType>toMap(E::getLiteral, identity()))
        ).get(literal);
    }

    private EnumTypes() {}
}
```

When working with Eclipse, you might need to remove the above intersection type: https://bugs.eclipse.org/bugs/show_bug.cgi?id=577466

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.16. Thanks again for your feature request.

**Comment by andredasilvapinto** [comment]
Thanks

**Comment by andredasilvapinto** [comment]
@lukaseder just a small note. I think it is a bit misleading to say that `getLiteral` is similar to `valueOf` as the former returns null on failed lookups, while the latter throws an exception. It might be worth adding that to the docs: https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/EnumType.java#L97-L99
