### ISSUE TITLE
How to override default catalog name?

### ISSUE THREAD

**Issue by kaifeur** [jOOQ/jOOQ#12677]
### Your question:

Let's talk about this schema:

```
My Postgres server/
├── db1/
│   └── public/
│       └── my_table/
│           ├── column_1_in_db1
│           └── column_2_in_db1
└── db2/
    └── public/
        └── my_table/
            ├── column_3_in_db2
            └── column_4_in_db2
```

I'm using jOOQ generator with Postgres. PostgresDatabase class provides only default catalog (with an empty name).

1. How can I override default catalog name? This does not work:
```kotlin
val database = Database()
            .withName(PostgresDatabase::class.qualifiedName)
            .withInputSchema("public")
            .withIncludeSequences(true)
            .withCatalogs(
                CatalogMappingType()
                    .withOutputCatalogToDefault(false)
                    .withInputCatalog("")
                    .withOutputCatalog("db1")
                    .withSchemata(
                        SchemaMappingType()
                            .withOutputSchemaToDefault(false)
                            .withInputSchema("public")
                            .withOutputSchema("public")
                    )
            )
```
2. How can I generate classes for different databases (i.e. catalogs) into the same package? They will generate the same `DefaultCatalog.kt` file for different databases.

### Versions:

- jOOQ: 3.15.4
- Java: openjdk version "11.0.13" 2021-10-19 LTS
- Database (include vendor): Postgers 14.1-1.pgdg110+1
- OS: macOS Big Sur 11.6.1
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver, v. 42.3.1

**Comment by lukaseder** [comment]
Thanks for your message.

Catalogs are currently supported only where they can be used in SQL, natively, i.e. in T-SQL dialects (such as SQL Server). Why do you need a catalog to be associated with your generated code? You cannot use it to qualify your SQL identifiers in PostgreSQL, so if you had the catalog in your generated code, that would produce wrong SQL.

Why do you want multiple code generation runs produce code in the same package? I think your real question is something else, I'd rather answer your real question than how to achieve the workarounds you're trying to achieve here.

**Comment by kaifeur** [comment]
Let's assume I have two databases in my postgres docker container – `db1` and `db2`.
I want to run jOOQ generator and generate classes for each database – some classes for `db1` and some classes for `db2`.
`db1` and `db2` are "catalogs" (am I wrong?).

So if they are, than jOOQ generator will only work with catalog (`db1` or `db2`) that was in JDBC URL: `jdbc:postgresql://localhost:5432/db1` -> generator will only generate classes for `db1`. And only `DefaultCatalog` class will be generated.

How can I make jOOQ to generate classes for each catalog?

**Comment by lukaseder** [comment]
I see. You can't have a single code generator run generate code for multiple catalogs in PostgreSQL, because the `db1` connection cannot access the meta data of `db2`, unfortunately. You'll have to run multiple independent runs, but as you've noticed, you cannot generate them into the same package. You need a separate package on a higher level for all the catalogs.

I think this is just a matter of specifying the right `<target/>` for each configuration run:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-target/

Does this help?

**Comment by kaifeur** [comment]
Already implemented it that way. I hoped you would know the right way to do it (and it would be possible).
Anyway, thank you for the answer.
