### ISSUE TITLE
Potential resource leak in SettingsTools static initialiser

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [jOOQ/jOOQ#12678]
https://github.com/jOOQ/jOOQ/blob/1e70ccfef9a83d4e7754de3a571ebfff7ee1cbff/jOOQ/src/main/java/org/jooq/conf/SettingsTools.java#L78

The program can potentially fail to release a system resource.

**Comment by lukaseder** [comment]
Thanks a lot for your report. Yes, there's some risk of this happening. Will fix right away.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.5 (https://github.com/jOOQ/jOOQ/issues/12679). Thanks again!
