### ISSUE TITLE
SQL Translation Error:  aliases in window functions while converting Redshift query to Postgresql query.

### ISSUE THREAD

**Issue by bayram53** [jOOQ/jOOQ#12693]
### SQL translator incorrectly translates this query:
Table schema
```sql
create table relations(
  parent_name varchar(100),
  child_name varchar(100)
);
```

Redshift query: 
```sql
select
  parent_name,
  count(child_name) children_count,
  row_number() over (order by children_count) rank
from relations
group by parent_name
```

Postgresql translation ouput:
```sql
select
  relations.parent_name,
  count(relations.child_name) as children_count,
  row_number() over (order by children_count) as rank
from relations
group by relations.parent_name
```

It looks like translator incorrectly translates query above. As far as I know Redshift allows aliases in row_number-order by window, but Postgresql does not allows aliases in that window.

Thanks

**Comment by lukaseder** [comment]
Thanks a lot for your report. Yes, we'd love to be able to support this transformation. The pending feature request is here: https://github.com/jOOQ/jOOQ/issues/11820

Closing this as a duplicate.
