### ISSUE TITLE
ResultSetMetaData::getColumnTypeName should produce the correct ARRAY type

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12690]
Starting with H2 2.0.202, arrays are now properly typed, unlike before in 1.4.200, when they were all just `Object[]`, so this is no longer possible:

```sql
create table t (i array);
```

But this is:

```sql
create table t (i integer array);
```

When fetching data from this table, the `ResultSetMetaData` still produces the old `ARRAY` value:

```java
try (Statement s = connection.createStatement()) {
    try {
        s.execute("create table t (i integer array)");

        try (ResultSet rs = s.executeQuery("select i from t")) {
            System.out.println(rs.getMetaData().getColumnTypeName(1));
        }
    }
    finally {
        s.execute("drop table t");
    }
}
```

This prints `ARRAY` (in HSQLDB it prints `INTEGER ARRAY`, in PostgreSQL, it prints `_int4`, the weird PG specific notation)

The same is true for this query:

```sql
select data_type from information_schema.columns where table_name = 'T';
```

Though in this case, I can figure out the array type myself, using `information_schema.element_types`. But with `ResultSetMetaData`, there's not really a way to detect the array type now? Is this an oversight or a bug? I'd say a bug. The `org.h2.value.TypeInfo.toString()` value evaluates to `INTEGER ARRAY`

**Comment by katzyn** [comment]
Maybe you meant to create this issue in bugtracker of H2?

**Comment by lukaseder** [comment]
OMG, yes! 😅 Thanks. Here it is: https://github.com/h2database/h2database/issues/3241
