### ISSUE TITLE
Mysql Create Event not supported with code generator.

### ISSUE THREAD

**Issue by VigneshTK91** [jOOQ/jOOQ#12714]
Is there any way to support a code generator for Mysql Event using a code generator like below?
Is there any way to exclude this from the code generator to avoid below error.

```

delimiter |

CREATE EVENT ttl
    ON SCHEDULE
        EVERY 1 day
    COMMENT 'TTL record'
    DO
    BEGIN
        DELETE FROM * WHERE ttl < NOW();
    END |
delimiter ;
```

Error :

Caused by: org.jooq.impl.ParserException: GENERATOR, GLOBAL TEMPORARY TABLE, INDEX, OR ALTER VIEW, OR REPLACE VIEW, SCHEMA, SEQUENCE, TABLE.

### Versions

- jOOQ: 3.13.4
- Java: java 11
- Database (include vendor): Mysql (Amazon RDS)
- OS: mac
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your message.

You seem to be using the `DDLDatabase`. We don't support that syntax, and quite a bit of other vendor-specific syntax. For best results, we always suggest to connect to a live database for your code generation. If you prefer using the `DDLDatabase`, you can comment out sections that are not supported by jOOQ's parser / jOOQ in general as documented here (look for `/* [jooq ignore start] */`):

- https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-parser/
- https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl/
