### ISSUE TITLE
Manual section "daos" should link to "codegen-daos"

### ISSUE THREAD

**Issue by Jotschi** [jOOQ/jOOQ#12725]
The section should also describe how to actually configure the generator that way. I bet it is somewhere in the docs but it would be useful to reference it there.

----
See: https://www.jooq.org/doc/3.15/manual/sql-execution/daos/

**Comment by lukaseder** [comment]
Done, will be published within the next hours. Thanks again

**Comment by Jotschi** [comment]
@lukaseder No problem. I was also wondering whether there is a setting for the codegen to generate r2dbc compliant DAOs. I did however not found a matching setting in the XSD of the maven plugin.

**Comment by lukaseder** [comment]
> I was also wondering whether there is a setting for the codegen to generate r2dbc compliant DAOs.

See: https://github.com/jOOQ/jOOQ/issues/11717
