### ISSUE TITLE
DSLContext.batchInsert() alternative

### ISSUE THREAD

**Issue by esfomeado** [jOOQ/jOOQ#12726]
### Versions:

- jOOQ: 3.14
- Java: Java 8
- Database (include vendor): Postgres 13.4
- OS: Windows 10
- JDBC Driver (include name if unofficial driver): https://mvnrepository.com/artifact/org.postgresql/postgresql/42.2.22

Hi @lukaseder,

This issue is related with [4533](https://github.com/jOOQ/jOOQ/issues/4533).

I'm working on a project where we insert bulk data using `DSLContext.batchInsert()` and it's been a performance bottleneck for us.

The solution that we found is to wrap the values that we want to insert in temporary tables and then insert them.

This approach is 3x faster but has the drawback that it's not "straightforward" as `DSLContext.batchInsert()`.

Would you be interested in a project sample of how we do this? Do you think there is a better way to workaround this issue?

Thanks

**Comment by lukaseder** [comment]
Thanks for your message. About time #4533 is fixed... In the meantime, have you tried using the loader API? https://www.jooq.org/doc/latest/manual/sql-execution/importing/importing-sources/importing-source-records

I don't know what else to tell you. It's a known issue...
