### ISSUE TITLE
ListAgg not working with filter clause.

### ISSUE THREAD

**Issue by turbosheep44** [jOOQ/jOOQ#12742]
### Expected behavior

Aggregate column using `listAgg` and `filterWhere` should work together on Oracle database.

### Actual behavior

The generated SQL produces an error:

```
ORA-30497: Argument should be a constant or a function of expressions in GROUP BY.
```

### Steps to reproduce the problem

Consider a table similar like the following:

| table_id | column | display | sort |
-|-|-|-
1 | Red | 1 | null
1 | Blue | 3 | 1
1 | Green | 2 | 2
2 | Purple | 1 | null
2 | Yellow | 2 | 1

I would like the following output:

| table_id | display_columns | sort_columns |
-|-|-
1 | Red,Green,Blue | Blue,Green
2 | Purple,Yellow | Yellow

And so I created the following query:

```java
                DSL.using(connection, SQLDialect.ORACLE)
                    .select(
                        tableColumns.TABLE_ID,
                        DSL.listAgg(tableColumns.COLUMN, ",")
                            .withinGroupOrderBy(tableColumns.DISPLAY)
                            .as("DISPLAY_COLUMNS"),
                        DSL.listAgg(tableColumns.COLUMN, ",")
                            .withinGroupOrderBy(tableColumns.SORT)
                            .filterWhere(tableColumns.SORT.isNotNull())
                            .as("ORDER_COLUMNS")
                    )
                    .from(tableColumns)
                    .groupBy(tableColumns.LIST_ID);
```

This generates the following SQL, which throws error ORA-30497:
```sql
        select
            "TABLE_COLUMNS"."TABLE_ID",
            listagg("TABLE_COLUMNS"."COLUMN", ',')
                within group (order by "TABLE_COLUMNS"."DISPLAY") "DISPLAY_COLUMNS",
            listagg(
                case when "TABLE_COLUMNS"."SORT" is not null then "TABLE_COLUMNS"."COLUMN" end,
                case when "TABLE_COLUMNS"."SORT" is not null then ',' end
            )
                within group (order by "TABLE_COLUMNS"."SORT") "ORDER_COLUMNS"
        from
            "TABLE_COLUMNS" group by"TABLE_COLUMNS"."TABLE_ID"
```

The correct SQL should be the following:
```diff
        select
            "TABLE_COLUMNS"."TABLE_ID",
            listagg("TABLE_COLUMNS"."COLUMN", ',')
                within group (order by "TABLE_COLUMNS"."DISPLAY") "DISPLAY_COLUMNS",
            listagg(
                case when "TABLE_COLUMNS"."SORT" is not null then "TABLE_COLUMNS"."COLUMN" end,
-                case when "TABLE_COLUMNS"."SORT" is not null then ',' end
+                ','
            )
                within group (order by "TABLE_COLUMNS"."SORT") "ORDER_COLUMNS"
        from
            "TABLE_COLUMNS" group by"TABLE_COLUMNS"."TABLE_ID"
```

### Versions

- jOOQ:            3.14.9
- Java:              Java 8
- Database:      Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
- OS:                Windows
- JDBC Driver:  oracle.jdbc.OracleDriver

**Comment by turbosheep44** [comment]
For those who may come across this issue before it is resolved, changing the `listAgg` statement to the following is a good workaround:
```java
DSL.listAgg(DSL.when(tableColumns.SORT.isNotNull(), tableColumns.COLUMN), ",")
    .withinGroupOrderBy(tableColumns.SORT)
    .as("ORDER_COLUMNS")

```

**Comment by lukaseder** [comment]
Thanks for your report. This might be the same issue as https://github.com/jOOQ/jOOQ/issues/8543

**Comment by lukaseder** [comment]
Yes, it's the same underlying issue as https://github.com/jOOQ/jOOQ/issues/8543, the feature hasn't been implemented yet. Will fix right away.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.6 (https://github.com/jOOQ/jOOQ/issues/12744). Thanks again for the report!

**Comment by matjazs** [comment]
This breaks the following use-case for PostgreSQL:

```Java
SelectJoinStep<Record1<String>> query = create
            .select(DSL.groupConcatDistinct(DSL.coalesce(TABLE1.FIELD1, TABLE1.FIELD2)))
            .from(TABLE1);
```

Instead of rendering SQL:

```SQL
select string_agg(distinct coalesce("schema1"."table1"."field1", "schema1"."table1"."field2"), ',')
from "schema1"."table1"
```

I get this (note the separator argument being part of the wrong parentheses):

```SQL
select string_agg(distinct (coalesce("schema1"."table1"."field1", "schema1"."table1"."field2"), ','))
from "schema1"."table1"
```

**Comment by lukaseder** [comment]
Thanks @matjazs. May I ask you to create a new issue?
