### ISSUE TITLE
Additional SQL statements after JDBC connection

### ISSUE THREAD

**Issue by Oeitho** [jOOQ/jOOQ#12759]
### Use case:

Please describe the use-case you have. This will better help us understand the context in which you're looking for a new feature.

In a current project that I'm part of with an Oracle database, jooq-codegen is used for generating Java objects from database objects and procedures. Multiple versions of these objects and procedures exists at all time as we use [Edition-Based Redefinition](https://docs.oracle.com/cd/E11882_01/appdev.112/e41502/adfns_editions.htm#ADFNS020), and we need to generate from the correct edition at build time.

### Possible solution you'd like to see:

Please describe a possible solution you'd like to see in jOOQ, ideally with example code.

Being able to alter the session using a SQL statement after the JDBC connection is created but before starting the code generation.

### Possible workarounds:

Please describe the possible workarounds you've implemented to work around the lacking functionality.

The workaround we use is to move objects to ORA$BASE before generating types, and not using this edition for anything else.

Other possible workarounds include:
- creating a logon trigger in the database to alter the session
- changing the default edition used in the schema

### Versions:

- jOOQ: 3.13.2
- Java: Java 8
- Database (include vendor): Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.13.0.0.0
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): https://mvnrepository.com/artifact/com.oracle.ojdbc/ojdbc8/19.3.0.0

**Comment by lukaseder** [comment]
Thanks a lot for reporting this issue here. This seems like a very good enhancement, not just for the edition-based redefinition feature, but generally useful, e.g. to create / clean up some state specifically useful for the code generator, including creating some auxiliary objects, such as synonyms, etc.

Will look into including this in the upcoming jOOQ 3.16

**Comment by lukaseder** [comment]
For the upcoming jOOQ 3.16 (hopefully this week), I've added these two configuration elements to the code generator config's `<jdbc>` element:

```xml
  <element name="initScript" type="string" minOccurs="0" maxOccurs="1">
    <annotation><appinfo><jxb:property><jxb:javadoc><![CDATA[A script to run after creating the JDBC connection, and before running the code generator.]]></jxb:javadoc></jxb:property></appinfo></annotation>
  </element>

  <element name="initSeparator" type="string" minOccurs="0" maxOccurs="1">
    <annotation><appinfo><jxb:property><jxb:javadoc><![CDATA[The separator used to separate statements in the initScript.]]></jxb:javadoc></jxb:property></appinfo></annotation>
  </element>
```

That ought to cover 95% of use-cases similar to yours.

**Comment by lukaseder** [comment]
The documentation will appear here: https://www.jooq.org/doc/dev/manual/code-generation/codegen-advanced/codegen-config-jdbc/

**Comment by lukaseder** [comment]
This has introduced some new system properties, which aren't documented yet:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-system-properties/
