### ISSUE TITLE
Mention fetchSingle() in the manual section about fetching

### ISSUE THREAD

**Issue by theHacker** [jOOQ/jOOQ#12766]
### Your question:

I just upgraded from jOOQ 3.13.4 to 3.14.3.
This upgrade includes the `@Nullable` annotation you added (nice one btw :+1:).
However this also breaks a lot of my Kotlin code:
```kt
fun getCountOfFoos(): Int = create
    .select(count())
    .from(FOO)
    .fetchOne { it.value1() } // Type mismatch: inferred type is Int? but Int was expected
```

Previously `fetchOne()` returned an `Int!`. I knew it would always returned **exactly** one return, so I was not afraid of `NPE`.
Now `fetchOne()` returns an `Int?` and I have to specify a "can never happen" myself.

I checked the jOOQ API again, whether there is a more fitting function for this case, and I stumbled upon `fetchSingle()` which seems to fit exactly my use-case: It returns `@NotNull T` and promises "exactly one resulting record".

In the [jOOQ Manual (5.3 Fetching)](https://www.jooq.org/doc/3.15/manual-single-page/#fetching) there is no mention of `fetchSingle()`.

Rather than filing a bug report about the fuzzy manual, I first want to ask whether I understand correctly:
```java
// The "standard" fetch when you know your query returns only one record. This may return null.
R fetchOne();    // Kotlin: fetchOne(): R?

// The "standard" fetch when you know your query returns exactly one record. This will never null.
R fetchSingle(); // Kotlin: fetchSingle(): R
```

### Versions:

- jOOQ: 3.14.3
- Java: 11 by Kotlin 1.4.10
- Database (include vendor): H2
- OS: Linux
- JDBC Driver (include name if inofficial driver): `org.h2.Driver`

**Comment by lukaseder** [comment]
Thanks a lot for your documentation request. I agree, this should be documented on that section.

The Javadoc is already clear:

- `fetchOne()`: Execute the query and return at most one resulting record.
- `fetchSingle()`: Execute the query and return exactly one resulting record.

Doesn't hurt adding this to the manual as well.

**Comment by lukaseder** [comment]
The `fetchSingle()` method was added in jOOQ 3.10: https://github.com/jOOQ/jOOQ/issues/6468

**Comment by theHacker** [comment]
Thanks for your answer :)
