### ISSUE TITLE
Issue upgrading 3.14.15 to 3.15.0 because of superfluous generics on `DSL` date/time methods

### ISSUE THREAD

**Issue by apankowski** [jOOQ/jOOQ#12768]
Hello :slightly_smiling_face: I'm the owner of [Garcon](https://github.com/apankowski/garcon) pet project using jOOQ :heart: and Kotlin :heart:. Recently I decided on upgrading its stack to newest versions of tools & components. Everything went pretty smooth and I'm progressing on a feature branch. While upgrading jOOQ to 3.15.5 I encountered a compilation problem which led to me to a potential issue.

The issue is easy to fix but it seems to apply to a couple of methods and so it might be undesirable to users of jOOQ and maybe even to the jOOQ Team - not sure.

So the compilation error I got is:

```
> Task :compileKotlin FAILED
e: /garcon/src/main/kotlin/dev/pankowski/garcon/infrastructure/persistence/JooqSynchronizedPostRepository.kt: (204, 9): Not enough information to infer type variable T
```

[the offending lines](https://github.com/apankowski/garcon/blob/9d877d12b2e0007171e2189c0f925edafa13c13c/src/main/kotlin/dev/pankowski/garcon/infrastructure/persistence/JooqSynchronizedPostRepository.kt#L204) are:

```
context.selectFrom(SYNCHRONIZED_POSTS)
      .where(...)
      .and(...)
      .and(
        // *** Line just below is problematic one ***
        timestampAdd(
          SYNCHRONIZED_POSTS.REPOST_LAST_ATTEMPT_AT.coerce(Timestamp::class.java),
          power(2, SYNCHRONIZED_POSTS.REPOST_ATTEMPTS - 1) * baseDelay.toSeconds(),
          DatePart.SECOND
        )
          .coerce(SYNCHRONIZED_POSTS.REPOST_LAST_ATTEMPT_AT)
          .lessThan(Instant.now())
      )
```

I was able to narrow it down to an exact version switch that causes this behavior - it's 3.14.15 (generally: any 3.14.x version) to 3.15.0 (generally: any 3.15.x version). Doing some digging it seems that the signature of some date-time-related `DSL` methods has changed between these versions.

For 3.14.x in `DSL.java` there's a bunch of methods under `// XXX Date and time functions` section, e.g.

```
public static Field<Date> dateAdd(Date date, Number interval)
public static Field<Timestamp> timestampAdd(Field<Timestamp> date, Field<? extends Number> interval, DatePart datePart)

```

For 3.15.x some of them have been moved under `// Date functions` section with additional unused `<T>` type parameter, e.g.

```
public static <T> Field<Date> dateAdd(Date date, Number interval)
public static <T> Field<Timestamp> timestampAdd(Field<Timestamp> date, Field<? extends Number> interval, DatePart datePart)
```

Since type parameter `T` is not bound and not used, Kotlin compiler (not sure about Java) complains. The solution is trivial - just pass `Any` for Kotlin or `Object` for Java as the value of the type parameter.

What was surprising to me is that it seems that all methods in `// Date functions` in 3.15.x have this additional unused (?) type parameter `<T>` which Kotlin compiler complains about. Also I haven't found this mentioned in [3.15 release announcement on the blog](https://blog.jooq.org/tag/jooq-3-15/) nor on [the Google group](https://groups.google.com/g/jooq-user/c/rqw-sRKgmC8) so I thought it might not be intentional and wanted to report it to you just in case.

### Versions:

- jOOQ: 3.14.15 / 3.15.0
- Java: 17
- Database (include vendor): Postgres 14
- OS: Ubuntu 21.04, amd64
- JDBC Driver (include name if inofficial driver): official postgre JDBC driver

### Reproducible example:

I've created a dedicated [feature/jooq-3.15-upgrade](https://github.com/apankowski/garcon/tree/feature/jooq-3.15-upgrade) branch which you can play around with. To see the failure:

1. checkout the branch
2. ensure you have JDK 17
3. go to [this line](https://github.com/apankowski/garcon/blob/9d877d12b2e0007171e2189c0f925edafa13c13c/build.gradle.kts#L143), comment it and uncomment the next one (switching from 3.14.15 to 3.15.0)
4. run `./gradlew clean build`

**Comment by lukaseder** [comment]
Thanks for your message. The Java compiler is able to ignore the unnecessary type variable. Curious that kotlin can't ignore it. Seems like a bug in the kotlin compiler? If the type is irrelevant, then `Any` should be inferred, IMO.

In any case, that's a known issue and will be fixed in jOOQ 3.16: https://github.com/jOOQ/jOOQ/issues/12212

For background info: Most of the jOOQ API is generated from a DSL (not published), and there was a bug in the generation of those particular methods (methods where the *implementation* uses a `<T>` type variable, but it shouldn't leak into the API)
