### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by azatgt1996** [jOOQ/jOOQ#12762]
There aren't comments in function/stored procedures

**Comment by lukaseder** [comment]
Thank you for your message.

I'm sorry, I don't know what you mean by this. Can you please elaborate.

**Comment by azatgt1996** [comment]
Comments are not saved during the migrate of function from MSSQL to Postgresql.

**Comment by lukaseder** [comment]
I see, thanks for the clarification. We currently do not plan on maintaining those in our expression tree representation, see also these links for details:

- https://github.com/jOOQ/jOOQ/issues/12538
- https://www.jooq.org/doc/dev/manual/sql-building/dsl-context/custom-settings/settings-parser/ (`parseRetainCommentsBetweenQueries` flag)
