### ISSUE TITLE
create column comment on MySQL

### ISSUE THREAD

**Issue by megamind-1** [jOOQ/jOOQ#12769]
Dear developer,  how can I create column comment when create table on MySQL? (jooq 3.14.15, MySQL 5.7)

this is convert sql code, I didn't find any line about column comment
```
            for (int i = 0; i < columnFields.size(); i++) {
                DataType<?> type = columnType(ctx, i);
                if (identity == null && type.identity())
                    identity = columnFields.get(i);

                ctx.visit(columnFields.get(i));

                if (select == null) {
                    ctx.sql(' ');
                    Tools.toSQLDDLTypeDeclarationForAddition(ctx, type);
                }

                if (i < columnFields.size() - 1)
                    ctx.sql(',').formatSeparator();
            }
```

**Comment by lukaseder** [comment]
Thanks a lot for your message. We don't support MySQL's column comment syntax yet. See also: https://github.com/jOOQ/jOOQ/issues/6995

**Comment by megamind-1** [comment]
Thank you for your reply,
In my point of view, adding column comment is diff when creating table than when alter table in MySQL, sql just like this:
```
create table `t_table` (
  `id` bigint null comment 'id'
)

CREATE TABLE `t_table` (
  `id` BIGINT NULL
)
```
I've already know data type, just add comment when creating table not altering table, maybe there's no problem.
:P

**Comment by lukaseder** [comment]
We cannot represent MySQL's column comment syntax irrespective of whether you want that done in the `CREATE` or `ALTER` statement
