### ISSUE TITLE
Emulate Oracle's LISTAGG() in SQL Server using STUFF

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1277]
this is an example:

``` sql
SELECT Column1,
stuff((
    SELECT ', ' + Column2
    FROM tableName as t1
    where t1.Column1 = t2.Column1
    FOR XML PATH('')
    ), 1, 2, '')
FROM tableName as t2
GROUP BY Column1
```

**Comment by delostilos** [comment]
Hi,

You can also build an ordered version:
<pre><code>
 select table_schema
      , table_name
     -- list_agg(column_name, ', ') within group(order by ordinal_position)
     -- postgresql string_agg(column_name, ', ' order by ordinal_position) 
      , stuff((select ', ' + c2.column_name
			     from information_schema.columns c2
				   -- group by
			    where c2.table_schema = c1.table_schema
			      and c2.table_name = c1.table_name
				   -- order by 
			    order 
			       by c2.ordinal_position
			      for xml path(''), type).value('.', 'varchar(4000)') -- extract element value and convert
            ,1,2,'') column_names
   from information_schema.columns c1
  group
     by table_schema
      , table_name
</code></pre>

**Comment by lukaseder** [comment]
Hey, thank you for documenting this, @delostilos. You've always been good at spotting these emulation techniques. Let's see if this makes it in a future jOOQ :)

**Comment by andre-ss6** [comment]
Thanks a lot for this. You've just helped me a ton :) 
Does anyone know if there's any catch to this? Any difference in behavior?

**Comment by lukaseder** [comment]
@andre-ss6: There might be :-)

**Comment by andre-ss6** [comment]
Yea, of course, that's why I asked if anyone has actually seen any difference :p 
At least for now, we haven't seen any here. If we notice anything wrong, I'll post here :)

**Comment by lukaseder** [comment]
Thanks a lot for your help!

**Comment by knutwannheden** [comment]
Note that SQL Server 2017 and later support `STRING_AGG()` natively: #9868.

**Comment by lukaseder** [comment]
I think that a formal emulation of this functionality will quickly turn out to be too complicated, as all sorts of joins, derived tables, etc. need to be duplicated in the emulation's correlated subquery.
