### ISSUE TITLE
Compilation errors in generated code when enabling <pojosAsJavaRecordClasses> and <embeddables>

### ISSUE THREAD

**Issue by HongyiFu** [jOOQ/jOOQ#12776]
### Expected behavior
They work together nicely

### Actual behavior
Compilation error in generated code

### Steps to reproduce the problem
Given this configuration,

<pre>
<code>
&lt;configuration&gt;
  &lt;jdbc&gt;
    &lt;driver&gt;org.postgresql.Driver&lt;/driver&gt;
    &lt;url&gt;${db.url}&lt;/url&gt;
    &lt;username&gt;${db.username}&lt;/username&gt;
    &lt;password&gt;${db.password}&lt;/password&gt;
  &lt;/jdbc&gt;
  &lt;generator&gt;
    &lt;strategy&gt;
      &lt;name&gt;com.example.plugin.jooq.CustomGeneratorStrategy&lt;/name&gt;
    &lt;/strategy&gt;
    &lt;database&gt;
      &lt;name&gt;org.jooq.meta.postgres.PostgresDatabase&lt;/name&gt;
      &lt;includes&gt;.*&lt;/includes&gt;
      &lt;excludes&gt;flyway_schema_history&lt;/excludes&gt;
      &lt;inputSchema&gt;public&lt;/inputSchema&gt;
      &lt;recordVersionFields&gt;version&lt;/recordVersionFields&gt;
      &lt;embeddables&gt;
        &lt;embeddable&gt;
          &lt;name&gt;address&lt;/name&gt;
          &lt;fields&gt;
            &lt;field&gt;&lt;expression&gt;country&lt;/expression&gt;&lt;/field&gt;
            &lt;field&gt;&lt;expression&gt;postcode&lt;/expression&gt;&lt;/field&gt;
            &lt;field&gt;&lt;expression&gt;state&lt;/expression&gt;&lt;/field&gt;
            &lt;field&gt;&lt;expression&gt;city&lt;/expression&gt;&lt;/field&gt;
            &lt;field&gt;&lt;expression&gt;address1&lt;/expression&gt;&lt;/field&gt;
            &lt;field&gt;&lt;expression&gt;address2&lt;/expression&gt;&lt;/field&gt;
            &lt;field&gt;&lt;expression&gt;address3&lt;/expression&gt;&lt;/field&gt;
          &lt;/fields&gt;
        &lt;/embeddable&gt;
      &lt;/embeddables&gt;
    &lt;/database&gt;
    &lt;target&gt;
      &lt;packageName&gt;com.example.app.jooq.codegen&lt;/packageName&gt;
      &lt;directory&gt;src/main/java&lt;/directory&gt;
    &lt;/target&gt;
    &lt;generate&gt;
      &lt;fluentSetters&gt;true&lt;/fluentSetters&gt;
      &lt;daos&gt;true&lt;/daos&gt;
      &lt;pojosAsJavaRecordClasses&gt;true&lt;/pojosAsJavaRecordClasses&gt;
      &lt;generatedAnnotation&gt;true&lt;/generatedAnnotation&gt;
      &lt;generatedAnnotationType&gt;DETECT_FROM_JDK&lt;/generatedAnnotationType&gt;
      &lt;generatedAnnotationDate&gt;true&lt;/generatedAnnotationDate&gt;
      &lt;nullableAnnotation&gt;true&lt;/nullableAnnotation&gt;
      &lt;nullableAnnotationType&gt;org.jetbrains.annotations.Nullable&lt;/nullableAnnotationType&gt;
      &lt;nonnullAnnotation&gt;true&lt;/nonnullAnnotation&gt;
      &lt;nonnullAnnotationType&gt;org.jetbrains.annotations.NotNull&lt;/nonnullAnnotationType&gt;
      &lt;jpaAnnotations&gt;true&lt;/jpaAnnotations&gt;
      &lt;jpaVersion&gt;2.2&lt;/jpaVersion&gt;
      &lt;validationAnnotations&gt;true&lt;/validationAnnotations&gt;
    &lt;/generate&gt;
  &lt;/generator&gt;
&lt;/configuration&gt;
</code>
</pre>

The following code is generated. See comment "compile error" for parts where the weird interaction occurs

1. setters is generated for record
2. getters uses Java Bean getter instead of record getter

<pre>
<code>
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "building",
    schema = "public",
    indexes = {
        @Index(name = "idx_building_name", columnList = "name ASC")
    }
)
public record BuildingDTO(
    UUID          id,
    Object        name,
    String        country,
    Object        postcode,
    Object        state,
    Object        city,
    Object        address1,
    Object        address2,
    Object        address3,
    Short         version,
    JSONB         extInfo,
    LocalDateTime createdOn,
    LocalDateTime updatedOn
) implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.address</code>.
     */
    public BuildingDTO setAddress(@NotNull AddressDTO value) {
        // compile error
        setCountry(
            // compile error
            value.getCountry());
        setPostcode(value.getPostcode());
        setState(value.getState());
        setCity(value.getCity());
        setAddress1(value.getAddress1());
        setAddress2(value.getAddress2());
        setAddress3(value.getAddress3());
        return this;
    }

    /**
     * Getter for <code>public.address</code>.
     */
    @NotNull
    public AddressDTO getAddress() {
        return new AddressDTO(
            // compile error
            getCountry(),
            getPostcode(),
            getState(),
            getCity(),
            getAddress1(),
            getAddress2(),
            getAddress3()
        );
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BuildingDTO (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(country);
        sb.append(", ").append(postcode);
        sb.append(", ").append(state);
        sb.append(", ").append(city);
        sb.append(", ").append(address1);
        sb.append(", ").append(address2);
        sb.append(", ").append(address3);
        sb.append(", ").append(version);
        sb.append(", ").append(extInfo);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
</code>
</pre>

The embeddable type is generated correctly
<pre>
<code>
/**
 * The embeddable <code>public.address</code>.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.15.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record AddressDTO(
    String country,
    Object postcode,
    Object state,
    Object city,
    Object address1,
    Object address2,
    Object address3
) implements Serializable {

    private static final long serialVersionUID = 1L;

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AddressDTO (");

        sb.append(country);
        sb.append(", ").append(postcode);
        sb.append(", ").append(state);
        sb.append(", ").append(city);
        sb.append(", ").append(address1);
        sb.append(", ").append(address2);
        sb.append(", ").append(address3);

        sb.append(")");
        return sb.toString();
    }
}
</code>
</pre>

The custom generator just inserts suffix "DTO" to class name of pojos.

<pre>
<code>
public class CustomGeneratorStrategy extends DefaultGeneratorStrategy {

    @Override
    public String getJavaClassName(Definition definition, Mode mode) {
        String className = super.getJavaClassName(definition, mode);
        if (mode == Mode.POJO) {
            className = className + "DTO";
        }
        return className;
    }
}
</code>
</pre>

### Versions

- jOOQ: 3.15.5
- Java: 17
- Database (include vendor): Postgresql
- OS: macOS Monterey v12.1
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll investigate this in a bit

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.16.0 and 3.15.6 (https://github.com/jOOQ/jOOQ/issues/12778). Thanks again for your report!
