### ISSUE TITLE
DEBUG log both executed SQL and SQL with inlined bind values

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1278]
None

**Comment by kiru** [comment]
Is it possible to disable only SQL logging with inlined bind values (and first five results)? I'd like to get only the executed SQL log as output. I've copied the LoggerListener and modified it, but it would be more pleasant to set it in the configs ( I'm not sure if that is useful for anyone else ).

**Comment by lukaseder** [comment]
@kiru Thank you very much for your message. As a side note, rest assured, we do not run out of github issue IDs any time soon :-) This means you are very free to create an entirely new issue. This will better help us (and you!) track issues, rather than if you comment on a remotely related issue that has been closed 6 years ago.

Regarding your question: The `LoggerListener` is so simple it is much easier for users to just write their own rather than for us to create sophisticated configuration and maintain that configuration, see #7301
