### ISSUE TITLE
Feature Comparison on website is different from docs

### ISSUE THREAD

**Issue by mkurz** [jOOQ/jOOQ#12783]
According to https://www.jooq.org/download/ "Readonly columns" is only availabe in the "Professional" edition:
<kbd>
<img width="750" src="https://user-images.githubusercontent.com/644927/148289113-15fbd851-40be-4e6f-b5ea-f3e6451c1d9b.png" />
</kbd>
But [the docs say](https://www.jooq.org/doc/3.16/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-readonly-columns/) its availabe in every edition:

<kbd>
<img width="750" src="https://user-images.githubusercontent.com/644927/148289390-c7f458d4-2aad-447c-afd0-2f9ebcfb17a6.png" />
</kbd>

**Comment by mkurz** [comment]
Alright, actually I think _all_ features that are listed Professional edition and higher in the comparison table are labeled wrong in the docs.. In the docs they show up with at least express edition, some of them also with oss edition...

**Comment by lukaseder** [comment]
Thanks a lot for your report. There are two documentation bugs indeed. The easy fix is to make the code generation section for readonly columns commercial only, just like the other readonly related sections, e.g.

- https://www.jooq.org/doc/3.16/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-synthetic-objects/codegen-database-synthetic-readonly-columns/
- https://www.jooq.org/doc/3.16/manual/sql-building/column-expressions/readonly-columns/

The main distinction between express edition and professional edition is the database product that can be used and the maximum number of licenses, so in this case, it's the https://www.jooq.org/download page that's wrong (after all, we don't publish distinct artifacts yet for the 3 commercial editions, so it wouldn't be possible to prevent accidental usage of an unlicensed feature)

**Comment by lukaseder** [comment]
Fixed. The manual will be updated in about ~1 hour. Thanks again for your report.
