### ISSUE TITLE
Field recognized as text instead of Boolean 

### ISSUE THREAD

**Issue by esfomeado** [jOOQ/jOOQ#12787]
### Your question:

Let's image I have the following:

```
public final TableField<SampleRecord, Boolean> ENABLED = createField( DSL.name( "enabled" ), SQLDataType.BOOLEAN );
...

final Table<SampleRecord> table = DSL.values( rows ).as( this, this.fields() );

CreateTable.onCommitDrop( dsl,
                          this.getName(),
			  dsl.select( ENABLED )
			  .from( table ) );

DSL.coalesce( sampleTable.ENABLED, OTHER.ENABLED ).as( ENABLED ),
```

Every field is defined as Boolean but I get this error:
`ERROR: COALESCE types text and Boolean cannot be matched`

Unless I cast the ENABLED field to Boolean on the select of the CreateTable.

Why does this happen? In every place is specified that is a Boolean field.

### Versions:

- jOOQ: 3.14
- Java: Java 8
- Database (include vendor): Postgres 13.4
- OS: Windows 10
- nJDBC Driver (include name if unofficial driver): https://mvnrepository.com/artifact/org.postgresql/postgresql/42.2.22

**Comment by lukaseder** [comment]
Thanks for your message. Can you please show a *complete* example that helps reproduce this?

**Comment by lukaseder** [comment]
I'd love to have a better look at the problem, but from the description, I can't see what might have gone wrong. The code isn't complete to reproduce the issue.

If you'd like me to have another look, perhaps an MCVE based on this template could help? https://github.com/jOOQ/jOOQ-mcve
