### ISSUE TITLE
Support parsing LOG(n) without explicit base, based on input dialect

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12843]
jOOQ 3.12 added support for parsing `LOG(n)` without base only for SQL Server: https://github.com/jOOQ/jOOQ/issues/8682

A variety of dialects support this form of the `LN(n)` or `LOG10(n)` function. The ambiguity must be resolved based on the parse dialect:

**`LN(n)`**:

- [x] Access: https://support.microsoft.com/en-us/office/log-function-c6ef3039-c0b1-445e-b2a3-cca03ec28b0b
- [x] BigQuery: https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#log
- [x] Derby: https://db.apache.org/derby/docs/10.2/ref/rreffunclog.html
- [x] H2 (deprecated): http://www.h2database.com/html/functions.html#log
- [x] HSQLDB: http://www.hsqldb.org/doc/2.0/guide/builtinfunctions-chapt.html
- [x] MariaDB: https://mariadb.com/kb/en/log/
- [x] MemSQL: https://archived.docs.singlestore.com/v7.1/reference/sql-reference/numeric-functions/log/
- [x] MySQL: https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_log
- [x] SQL Server: https://docs.microsoft.com/en-us/sql/t-sql/functions/log-transact-sql?view=sql-server-ver15
- [x] Sybase ASE: https://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc38151.1510/html/iqrefbb/Log.htm
- [x] Sybase SQL Anywhere: https://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.help.sqlanywhere.12.0.1/dbreference/log-function.html

**`LOG10(n)`**:

- [x] CockroachDB: https://www.cockroachlabs.com/docs/stable/functions-and-operators.html#float-functions
- [x] PostgreSQL: https://www.postgresql.org/docs/current/functions-math.html
- [x] Redshift: https://docs.aws.amazon.com/redshift/latest/dg/r_LOG.html
- [x] SQLite: https://www.sqlite.org/lang_mathfunc.html#log
- [x] Teradata: https://docs.teradata.com/r/1DcoER_KpnGTfgPinRAFUw/be3e~o6KeCqzb4N_Gfcwzg
- [x] Vertica: https://www.vertica.com/docs/9.3.x/HTML/Content/Authoring/SQLReferenceManual/Functions/Mathematical/LOG.htm

**Doesn't parse** (will default to `LN(n)` behaviour):

These either don't support `LOG` at all, or only the 2 argument version

- [x] Db2
- [x] Exasol
- [x] Firebird
- [x] HANA
- [x] Informix
- [x] Oracle
- [x] Snowflake

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0 and 3.16.2 (https://github.com/jOOQ/jOOQ/issues/12844)

**Comment by mrotteveel** [comment]
Firebird has a single argument `ln` and `log10` in addition to the 2-argument `log`: 

- [`ln`](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-scalarfuncs-ln)
- [`log10`](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-scalarfuncs-log10)
