### ISSUE TITLE
jOOQ Open Source Edition code generation doesn't work PostgreSQL 11 or less because of ERROR: column pg_attribute.attgenerated does not exist

### ISSUE THREAD

**Issue by kirillparfenov** [jOOQ/jOOQ#12854]
When I'm using JOOQ codegen 3.16.1 and my PostgreSQL database version is 11.10 I get next exception:
**ERROR: column pg_attribute.attgenerated does not exist**

 **attgenerated** appeared in PostgreSQL 12.

**Comment by lukaseder** [comment]
Thanks for your report. While the jOOQ Open Source Edition 3.16 requires PostgreSQL 14 to work (see https://www.jooq.org/download/support-matrix), we try hard not to break any queries against the `information_schema` / `pg_catalog` for older versions of PostgreSQL, even in the Open Source Edition. For best results, I do recommend using the jOOQ Professional Edition, though, if you're using older RDBMS versions.

In this particular case, we check if we're running code generation queries on a PG 12 compatible version like this:

https://github.com/jOOQ/jOOQ/blob/b8f680781870bcc6eff4b0e1f1b5fcbf8e9e1444/jOOQ-meta/src/main/java/org/jooq/meta/postgres/PostgresDatabase.java#L1070-L1076

And that `is12()` method is called before accessing the `attgenerated` field. How can I reproduce the issue you're seeing?

**Comment by lukaseder** [comment]
My bad. The `is12()` check is being performed only in the commercial distributions. It has been removed from the jOOQ Open Source Edition. It would have been here:

https://github.com/jOOQ/jOOQ/blob/b8f680781870bcc6eff4b0e1f1b5fcbf8e9e1444/jOOQ-meta/src/main/java/org/jooq/meta/postgres/PostgresDatabase.java#L1133-L1137

Will fix this right away!

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0 and 3.16.2 (https://github.com/jOOQ/jOOQ/issues/12860). I'm planning a 3.16.2 release next week.

Thanks again for the report!

**Comment by lukaseder** [comment]
This patch fixes the issue, should you wish to patch your distribution yourself: https://github.com/jOOQ/jOOQ/commit/51ff93c157b8fb0d3c2827f1551177b31866660f.patch
