### ISSUE TITLE
Add support for CREATE SEQUENCE .. AS <data type>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12851]
HSQLDB has a `CREATE SEQUENCE .. AS <data type>` syntax, where it's possible to specify the type (e.g. `INTEGER`, `BIGINT`) of a sequence:
http://www.hsqldb.org/doc/guide/databaseobjects-chapt.html#dbc_sequence_creation

We already support typed sequences in the code generator, but not yet in:

- [x] DDL
- [x] DDL export
- [x] Interpreter (?)
- [x] ~Diff~ (not yet interesting, before we have https://github.com/jOOQ/jOOQ/issues/16415)
- [x] Parser
- [x] Code generator
- [x] `MetaImpl`
- [x] `InformationSchema` (already supports the data type)
- [x] Documentation

Dialect support

- [x] CockroachDB: https://www.cockroachlabs.com/docs/stable/create-sequence
  - [x] API
  - [x] Codegen
  - [x] Meta
- [x] Db2: https://www.ibm.com/docs/en/db2/9.7?topic=statements-create-sequence
  - [x] API
  - [x] Codegen
  - [x] Meta
- [x] Derby: https://db.apache.org/derby/docs/10.6/ref/rrefsqljcreatesequence.html
  - [x] API
  - [x] Codegen
  - [x] Meta
- [x] H2: https://www.h2database.com/html/commands.html#create_sequence
  - [x] API
  - [x] Codegen
  - [x] Meta
- [x] HSQLDB: https://www.hsqldb.org/doc/guide/databaseobjects-chapt.html#dbc_sequence_creation
  - [x] API
  - [x] Codegen
  - [x] Meta
- [x] PostgreSQL: https://www.postgresql.org/docs/current/sql-createsequence.html
  - [x] API
  - [x] Codegen
  - [x] Meta
- [x] SQL Server: https://learn.microsoft.com/en-us/sql/t-sql/statements/create-sequence-transact-sql?view=sql-server-ver16
  - [x] API
  - [x] Codegen
  - [x] Meta
- [x] Yugabyte: https://docs.yugabyte.com/preview/api/ysql/the-sql-language/statements/ddl_create_sequence/ (undocumented, see https://github.com/yugabyte/yugabyte-db/issues/21307)
  - [x] API
  - [x] Codegen
  - [x] Meta

**Comment by katzyn** [comment]
This syntax is a part of the SQL Standard and it is also supported by DB2, H2, PostgreSQL, SQL Server and possibly others.

**Comment by lukaseder** [comment]
Thanks for the hint, @katzyn

**Comment by lukaseder** [comment]
Looking into this now. It doesn't seem possible / reasonable to implement this backwards compatibly in terms of the `QOM` API, given that the statement will now be `OQM.CreateSequence<T>` (generic). It is, however, possible to keep the DSL API backwards compatible thanks to Java's raw type support.

**Comment by lukaseder** [comment]
Fewer dialects support the clause also for `ALTER SEQUENCE` statements:

- https://github.com/jOOQ/jOOQ/issues/16415

**Comment by lukaseder** [comment]
There's a subtle change of behaviour in the DDL export now:

The DDL export from meta data can no longer distinguish between BIGINT typed sequences which use the default type (BIGINT), and those which have an explicit AS BIGINT clause in their creation. Hence, the export will now always include the AS clause, if the dialect supports it, unless the meta data does not have any data type (e.g. `SQLDataType.OTHER`)

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.20.

**Comment by lukaseder** [comment]
There's a bug in HSQLDB: https://sourceforge.net/p/hsqldb/bugs/1698

This bug will be produced when exporting DDL from `MetaImpl`, as we get these `MINVALUE`. I've created a separate issue for this:

- https://github.com/jOOQ/jOOQ/issues/16417
