### ISSUE TITLE
Postgres random UUID

### ISSUE THREAD

**Issue by esfomeado** [jOOQ/jOOQ#12861]
### Your question:

I have the following query that I'm trying to convert to jOOQ.

```
SELECT Md5(Random() :: text || Clock_timestamp() :: text) :: uuid AS "new_key",
       "offer"."offer_key"                                   AS "old_key"
FROM   "schema"."offer"
WHERE  ( "schema"."offer"."template_key" = 1 ) 
```

The issue is how can I generate a random UUID for each record?

If I use something like `DSL.val(UUID.randomUUID())` it will put the same ID on all rows.

I saw that there is a new function for this in newer versions but is there anything I can use on 3.14?

Thanks

### Versions:

- jOOQ: 3.14.14
- Java: Java 8
- Database (include vendor): Postgres 13.4
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): https://mvnrepository.com/artifact/org.postgresql/postgresql/42.2.22

**Comment by lukaseder** [comment]
Thanks a lot for your message

> I saw that there is a new function for this in newer versions but is there anything I can use on 3.14?

Why not upgrade?

In any case, you can always use plain SQL templating for missing functionality: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

**Comment by esfomeado** [comment]
> Why not upgrade?

We have lot of dependencies that required upgrading before moving to Java 17 but it should be done by the end of the year.

Thanks for your support, have a great day.
