### ISSUE TITLE
jooq code gen with liquibase fails in a maven multi module project with 3.16.0

### ISSUE THREAD

**Issue by pgokul** [jOOQ/jOOQ#12872]
### Expected behavior

jooq code generation works witg maven multi module project with liquibase xml in resources

### Actual behavior

jooq code generation fails 

### Steps to reproduce the problem

In a multi module project , code gen fails with the following config

```
<plugin>
		<groupId>org.jooq</groupId>
		<artifactId>jooq-codegen-maven</artifactId>
		<dependencies>
			...
		</dependencies>
		<executions>
			<execution>
				<goals>
					<goal>generate</goal>
				</goals>
			</execution>
		</executions>
		<configuration>
			<generator>
				<database>
					<name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
					<properties>
						<property>
							<key>scripts</key>
							<value>{moduleName}/src/main/resources/db/changelog/db.changelog-master.yaml</value>
						</property>
					</properties>
				</database>
			</generator>
		</configuration>
	</plugin>

```

This works fine with 3.15.5 but fails with 3.16.0

MCVE at https://github.com/pgokul/jOOQ-mcve
### Versions

- jOOQ: 3.16.0
- Java: 11
- Database (include vendor): postgres
- OS: mac os monterey
- JDBC Driver (include name if inofficial driver): pg jdbc driver

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll investigate this soon.

**Comment by lukaseder** [comment]
Probably another limitation from the fix in jOOQ 3.14: https://github.com/jOOQ/jOOQ/issues/9866

**Comment by lukaseder** [comment]
This is a configuration from our integration tests that will work:

```xml
<execution>
    <id>generate-liquibase-xml-rootpath</id>
    <phase>generate-test-sources</phase>
    <goals>
        <goal>generate</goal>
    </goals>
    <configuration>
        <generator>
            <database>
                <name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
                <properties>
                    <property>
                        <key>rootPath</key>
                        <value>${basedir}/src/main/resources</value>
                    </property>
                    <property>
                        <key>scripts</key>
                        <value>liquibase.xml</value>
                    </property>
                </properties>
            </database>
            <target>
                <packageName>org.jooq.codegen.test.liquibase.xml.db</packageName>
            </target>
        </generator>
    </configuration>
</execution>
```

**Comment by lukaseder** [comment]
I'm implementing this as a new feature, which I'll backport to 3.16.5: https://github.com/jOOQ/jOOQ/issues/13031

The "regression" had been introduced by the upgrade to Liquibase 4:
https://github.com/jOOQ/jOOQ/issues/11659

That upgrade should have been accompanied with this new feature as LB 4 no longer supports `FileSystemResourceAccessor` without an explicit set of rootPaths, so it could be argued that the regression is an incompatible change in Liquibase.
