### ISSUE TITLE
Add DSL.nullCondition(), a condition that correctly represents the NULL / UNKNOWN predicate value

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12883]
In order to be able to correctly transform and reason about predicate logic (see https://github.com/jOOQ/jOOQ/issues/7284), we need a formal way to express a `NULL` condition.

In dialects that correctly implement the `BOOLEAN` type, this can just be `NULL`. In other dialects, we can probably emulate this as `NULL = NULL`. To be investigated.

The complete list of dialect implementations will be provided here:

**Supports `NULL` in predicates**

- [x] CockroachDB
- [x] Db2 11.1
- [x] Exasol
- [x] Firebird 3.0
- [x] H2
- [x] HANA
- [x] MariaDB
- [x] MySQL
- [x] PostgreSQL
- [x] SQLite
- [x] YugabyteDB

**Requires a cast, such as `CAST(NULL AS BOOLEAN)`**

- [x] Derby
- [x] HSQLDB
- [x] Informix

**Requires an emulation, such as `NULL = NULL`**

- [x] Oracle
- [x] SQL Server

**Not yet tested**

- See https://github.com/jOOQ/jOOQ/issues/12928

**Comment by katzyn** [comment]
H2, since the version 1.4.200, has standard `UNKNOWN` literal. Unlike `NULL`, it definitely has a `BOOLEAN` data type in H2. Usually there is no difference in expressions, but in some special cases data type has a meaning (`VALUES UNKNOWN` produces a result with `BOOLEAN` column etc.)

**Comment by lukaseder** [comment]
Thanks for the pointer. I was going to investigate that later on, but since hardly anyone implements this, I didn't think it will be important at first. But will be good to keep in mind.

**Comment by lukaseder** [comment]
For the record, the usual approach, e.g. with Derby, HSQLDB, and possibly others, will be to generate `CAST(NULL AS BOOLEAN)`

**Comment by lukaseder** [comment]
Using `field(nullCondition())` seems to yield wrong results in some dialect emulations: https://github.com/jOOQ/jOOQ/issues/13993
