### ISSUE TITLE
I wonder why Named is used here

### ISSUE THREAD

**Issue by 1004789224** [jOOQ/jOOQ#12880]
https://github.com/jOOQ/jOOQ/blob/b9b9b2c8014ec44fd5bd16a5a47133d804680666/jOOQ/src/main/java/org/jooq/impl/R2DBC.java#L670

before:
![image](https://user-images.githubusercontent.com/32547368/149736423-776835b0-43d7-47a8-97b0-71dd27ed0f0e.png)
after:
![image](https://user-images.githubusercontent.com/32547368/149736510-e3ff9208-0127-447b-a94c-841c95b7de7f.png)
I have an extra 'p1' in this sql
i think it's a bug

**Comment by lukaseder** [comment]
Thanks for your message.

R2DBC drivers expect named parameters to be used, with different syntaxes, but mostly of the form `$param`, though indexed parameters of the form `$1` also tends to work.

So, there's no bug here. However, you probably have some other question / expectation that wasn't matched by what jOOQ is doing. I'll be happy to answer your *actual* question...

**Comment by 1004789224** [comment]
@lukaseder thanks for your response
This is the generated SQL:select `user`.`id`, `user`.`nick_name`, `user`.`phone`, `user`.`email`, `user`.`head_portrait_id`, `user`.`state`, `user`.`type`, `user`.`platform`, `user`.`os`, `user`.`equipment`, `user`.`register_ip`, `user`.`last_login_at`, `user`.`reversion`, `user`.`create_time`, `user`.`update_time` from `user` limit ?p1
and i has an error with it :
    com.github.jasync.sql.db.mysql.exceptions.MySQLException: Error 1064 - #42000 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?p1' at line 1

The environment in which my program runs:
spring boot 2.5.8
jooq:3.15.5
jasync-r2dbc-mysql:2.0.5

**Comment by lukaseder** [comment]
I see, well we integration tested things using https://github.com/mirromutth/r2dbc-mysql, not using jasync-r2dbc. That's the driver we recommend using.

**Comment by 1004789224** [comment]
thanks,it works

**Comment by lukaseder** [comment]
Thanks for the quick feedback. I've created a feature request to collect user feedback related to the other driver: https://github.com/jOOQ/jOOQ/issues/12881, to see if we should support that as well in the future. Given that it brings more complexity than needed (written in kotlin, thus pulling in kotlin libs, built on top of yet another driver), I'm reluctant to support it, but maybe, someone has a compelling use-case. I think you just chose it because it was listed on top of the others, in the list?

**Comment by 1004789224** [comment]
Jasync-sql is more active than r2dbc-mysql, and r2dbc-mysql，last release was a year ago. jasync-sql also has more stars than R2DBc-mysql

**Comment by lukaseder** [comment]
Thanks, I recommend leaving your comment on https://github.com/jOOQ/jOOQ/issues/12881, such that it can be tracked.
