### ISSUE TITLE
H2 data type parsing regression

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#12897]
### Expected behavior

The following test case passes with JOOQ 3.13.1 and H2 1.4.200:

```
    @Test
    public void testJooq() {
        var conn = DSL.using("jdbc:h2:mem:");
        conn.execute("create table t1(c1 varchar)");
        var tables = conn.meta().getTables();
        for (var t: tables) {
            if (t.getName().equals("T1")) {
                int sqlType = t.field(0).getDataType().getSQLType();
                assertNotEquals(Types.OTHER, sqlType);
                assertEquals(Types.VARCHAR, sqlType);
            }
        }
    }

```

### Actual behavior

The test fails when I upgrade to JOOQ 3.16.2 and H2 2.1.210. In particular, `getSqlType()` for the varchar column yields `Types.OTHER`.

### Steps to reproduce the problem

See test case above.

### Versions

- jOOQ: 3.16.2
- Java: 17
- Database (include vendor): H2 2.1.210
- OS: Mac OSX
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Your code works for me. This looks like a duplicate of https://github.com/jOOQ/jOOQ/issues/12794, specifically this comment: https://github.com/jOOQ/jOOQ/issues/12794#issuecomment-1007223153, which has been backported to 3.16.1.

Can you please check if you're really using jOOQ 3.16.2?

**Comment by lalithsuresh** [comment]
@lukaseder apologies. There was an annoying interaction in the build where the Gradle JOOQ plugin which was pulling in an older version of JOOQ, which was messing with the test.

Closing.

**Comment by lukaseder** [comment]
No worries
