### ISSUE TITLE
Parser fails to parse SET SCHEMA 'string-literal'

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12890]
In PostgreSQL, it is legal to use string literals as identifiers in some places, it seems, e.g.

```sql
SET SCHEMA 'public';
```

I guess this is because the `SET` command accepts values in any form, see:
https://www.postgresql.org/docs/current/sql-set.html

```
SET [ SESSION | LOCAL ] configuration_parameter { TO | = } { value | 'value' | DEFAULT }
```

Our parser cannot handle this yet.

**Comment by lukaseder** [comment]
Our grammar already claims it's possible, but it isn't:

```
setSchemaStatement = ( 'SET' | 'OPEN' ) (
  [ 'CURRENT' ] 'SCHEMA'
| 'CURRENT SQLID'
) [ '=' ] ( schemaName | stringLiteral )
;
```

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0 and 3.16.3 (https://github.com/jOOQ/jOOQ/issues/12891)

**Comment by katzyn** [comment]
@lukaseder
Most likely this is because the SQL Standard requires a character string value to be specified.

**Comment by lukaseder** [comment]
Oh wow, that's weird, I was unaware of this specification. I mean, the standard does specify identifiers, why not use them here?

**Comment by katzyn** [comment]
I don't know, but I guess it was designed to work with dynamic names inside prepared statements (not in JDBC sense). But it is also perfectly valid as direct statement where it doesn't look nice.
