### ISSUE TITLE
Jooq modify a query programatically

### ISSUE THREAD

**Issue by basanthjenuhb** [jOOQ/jOOQ#12937]
### Your question:

We have a requirement to modify SQL queries at runtime.
Assume a table called transactions and the original query being
```
select quantity, amount from transactions limit 10
```
We want to modify the query run the it for a particular customer
```
select quantity, amount from transactions where customer_id = <my_customer_id> limit 10
```
And it can go for complex cases:
Original query
```
select 
    quantity, 
    amount, 
    account 
from 
    transactions
inner join
    accounts on
        transactions.account_id = accounts.account_id
limit 10
```
This being modified to 
```
select 
    quantity, 
    amount, 
    account 
from 
    transactions
inner join
    accounts on
        transactions.account_id = accounts.account_id
        and accounts.customer_id = <my_customer_id>
where
    transactions.customer_id = <my_customer_id>
limit 10
```

Basically `customer_id` is my multi-tenant column and I want to programatically add this key to all queries to all tables in the query
Sort of like manually implementing Oracle's VPD or postgres' row level security

I know Jooq has a query parse API but unable to find examples on how to use it to modify the query in question

### Versions:

- jOOQ:
- Java:
- Database (include vendor): POSTGRES
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
You can use a `VisitListener` to implement client side row level security:
https://blog.jooq.org/implementing-client-side-row-level-security-with-jooq/

Starting from jOOQ 3.16, there's an experimental new public query object model (QOM) API, which greatly simplifies the task:
https://www.jooq.org/doc/latest/manual/sql-building/model-api/

... it supports expression tree traversal:
https://www.jooq.org/doc/latest/manual/sql-building/model-api/model-api-traversal/

... and replacement functionality:
https://www.jooq.org/doc/latest/manual/sql-building/model-api/model-api-replacement/

The QOM API is still under heavy development, so expect it to change incompatibly in the next minor releases. But we'll definitely implement the row level security use-case soon, out of the box, based on this feature set: https://github.com/jOOQ/jOOQ/issues/2682
