### ISSUE TITLE
Feedback about manual section "settings-jdbc-flags"

### ISSUE THREAD

**Issue by Kai2810** [jOOQ/jOOQ#12948]
whats the time unit for `withQueryTimeout​(Integer value)` method 
----
See: https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-jdbc-flags/

**Comment by lukaseder** [comment]
See the links on the flag, pointing to: https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/Query.html#queryTimeout(int), https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/Statement.html#setQueryTimeout(int)

(It's seconds, we'll add that to the manual as well)
