### ISSUE TITLE
Maven download problem with version 3.16.3

### ISSUE THREAD

**Issue by eitan-rosenberg** [jOOQ/jOOQ#12957]
There is  a maven download problem with version 3.16.3.

when using:

`
<dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>3.16.3</version>
        </dependency>
`

the download fails.

It is working fine with:

`
<dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>3.16.2</version>
        </dependency>
`

Please help.
Regards

**Comment by lukaseder** [comment]
Thanks for your report. The dependency is there alright:
https://repo1.maven.org/maven2/org/jooq/jooq/3.16.3/

The jOOQ-mcve project builds just fine if I upgrade it to the 3.16.3 dependency:
https://github.com/jOOQ/jOOQ-mcve

You might be using a Maven Central cache that isn't up to date yet?

**Comment by eitan-rosenberg** [comment]
Thanks for the response.

"You might be using a Maven Central cache that isn't up to date yet?" gave me an idea, 

I delete G:\MyMavenRepo\org\jooq in my local maven Repository and 3.16.3 was downloaded just fine.

Thanks again.
