### ISSUE TITLE
Can no longer store/retrieve blob data exceeding 1M in H2 2.0

### ISSUE THREAD

**Issue by oflege** [jOOQ/jOOQ#12956]
### Your question:

H2 2.1.210 blob values larger than 1024*1024 bytes must be set using `PreparedStatement.setBlob` as `PreparedStatement.setBytes` checks for the length to be <= 1M and throws an Exception otherwise. jOOQ always uses `setBytes` as far as I can see. A related problem occurs when trying to fetch a column value that exceeds 1M bytes. 
Not sure if this can be considered a bug in jOOQ, a fix would still be awesome.

```
val c = DSL.using("jdbc:h2:mem:test")
c.execute("create table x (id INTEGER GENERATED ALWAYS AS IDENTITY, data LONGBLOB)")
c.execute("insert into x (data) values (?)", "A".repeat(2000000).toByteArray()) // fails
```

### Versions:

- jOOQ: 3.16.3
- Database (include vendor): H2 2.1.210

**Comment by masc3d** [comment]
works well with `1.4.199`, so possibly regressing in `2.1.210`

**Comment by lukaseder** [comment]
Thanks for your report. That's quite the annoying regression indeed. By now, even ojdbc can handle very large `byte[]` values, no longer requiring the tedious `Blob` management, so I see this as a regression in H2, irrespective of the new "standard" support for `VARBINARY` values.

Anyway, jOOQ will make it work for you, as always. We'll just bind all binary values as `Blob`, instead.

The workaround is to implement your custom data type binding for the time being: https://www.jooq.org/doc/latest/manual/sql-building/queryparts/custom-bindings/

**Comment by lukaseder** [comment]
For anyone looIn fact, you don't have to write the binding yourself. We have an out-of-the-box one for you: `org.jooq.impl.BlobBinding`

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0 and 3.16.4 (https://github.com/jOOQ/jOOQ/issues/12960). Thanks again for your report.

**Comment by lukaseder** [comment]
I guess I was too optimistic when claiming that `setBytes()` works almost everywhere for `BLOB` columns. The new test that was introduced here failed in MySQL too: https://github.com/jOOQ/jOOQ/issues/12963 (at least on our CI/CD server, not locally on my machine).

While this here is a regression for H2 only, given that H2 has changed their default behaviour, for other RDBMS, the fix might introduce other problems (binding everything as `Blob` instead of `byte[]` has other impacts), so I won't backport the fix for #12963

**Comment by oflege** [comment]
> For anyone looIn fact, you don't have to write the binding yourself. We have an out-of-the-box one for you: `org.jooq.impl.BlobBinding`

Unfortunatly, BlobBinding is incompatible with H2's PostgreSQL Compatibility Mode, as `cast(? as BLOB)` no longer works. H2 2.x is a gift that keeps on giving...

**Comment by lukaseder** [comment]
> Unfortunately, BlobBinding is incompatible with H2's PostgreSQL Compatibility Mode, as `cast(? as BLOB)` no longer works. H2 2.x is a gift that keeps on giving...

Why do you use that, instead of e.g. https://www.testcontainers.org ?

**Comment by lukaseder** [comment]
In any case, we don't support H2's various compatibility modes. The integration test matrix would explode if we did, and I always recommend integration testing with the actual thing instead of H2.
