### ISSUE TITLE
Generated POJO field types not detected properly on auto increment or default value columns (H2)

### ISSUE THREAD

**Issue by masc3d** [jOOQ/jOOQ#12955]
### Expected behavior
Types should be generated correctly

### Actual behavior
Types will be generated as `Object` when column has identity / auto increment or default value.

### Steps to reproduce the problem
Create H2 table having columns using auto increment and / or default values and generate POJOs from it

### Versions

- jOOQ: 3.16.3
- Java: 17.0.2
- Database (include vendor): H2-1.4.199
- JDBC Driver (include name if inofficial driver): H2-1.4.199

**Comment by lukaseder** [comment]
Thanks for your report. I can reproduce this. Note that due to numerous CVEs in H2, it is recommended you upgrade to the latest H2 2.1.210 version, which shouldn't produce this problem in jOOQ 3.16.3

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0 and 3.16.4 (https://github.com/jOOQ/jOOQ/issues/12962).

**Comment by lukaseder** [comment]
Note: While we try not to break things in the jOOQ Open Source Edition for older database dialects of various RDBMS, we only officially support older dialects in the commercial distributions.
