### ISSUE TITLE
Feedback about manual section "settings-render-mapping"

### ISSUE THREAD

**Issue by RobertG-git** [jOOQ/jOOQ#12987]
Hi, 

I'm not sure if I found a bug, or only if I make something wrong, but I will add here my situation.
I use bellow bean to change the schema name from sq to esq_test.
    
```java
@Configuration
public class Config {

    @Bean
    public DefaultConfigurationCustomizer configurationCustomiser() {
        return (DefaultConfiguration c) -> c.settings()
                .withRenderQuotedNames(RenderQuotedNames.EXPLICIT_DEFAULT_UNQUOTED)
                .withRenderMapping(new RenderMapping()
                        .withSchemata(
                                new MappedSchema().withInput("sq")
                                        .withOutput("esq_test")));
    }
}
``` 

It works very well, except for native SQL like second field:
- first field: ` REQUEST_ACO.NAME,` 
- second field: `  field("string_agg(DISTINCT (COALESCE(" + REQUEST_ACO.NAME + ", ''::character varying)::text || '__'::text) || " REQUEST_ACO.ACO_IPN + "::text, '/'::text)", String.class).as(ACOS),` 

Here is the generated SQL:
- first field: `esq_test.request_aco.name,` --> correct
- second field: `string_agg(distinct (coalesce("sq"."request_aco"."name", ''::character varying)::text || '__'::text) || "sq"."request_aco"."aco_ipn"::text, '/'::text) acos,` --> wrong

As you can see schema is still "sq" in the second field. The first field was changed to esq_test as expected.
Can you please help me with your opinion? It is a bug, unsupported feature or I do something wrong.

Thank you for the great work!

----
See: https://www.jooq.org/doc/3.16/manual/sql-building/dsl-context/custom-settings/settings-render-mapping/

**Comment by lukaseder** [comment]
jOOQ doesn't parse your plain SQL template other than for templating purposes. The whole purpose of plain SQL templates is to support syntax that jOOQ doesn't understand, so jOOQ couldn't possibly parse it, and offer the usual expression tree transformation feature set.

You're concatenating `Field.toString()` to your plain SQL template, so by the time the template is used to render SQL, it's too late.

However, why not just use the templating functionality?

```java
field("... coalesce({0}, '')", String.class, REQUEST_ACO.NAME);
```

See:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

**Comment by RobertG-git** [comment]
Ok, understood.
I have not used templating functionality because I was not aware of this feature in JOOQ (still learning) but indeed seems to be what I need.

Thank you a lot for your support. I have managed to fix everything :).
