### ISSUE TITLE
Replace the tutorial by a downloadable example

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12984]
The manual's tutorial on https://www.jooq.org/doc/latest/manual/getting-started/tutorials/jooq-in-7-steps/ has been contributed a very long time ago by Ikai Lan, see also: https://ikaisays.com/2011/11/01/getting-started-with-jooq-a-tutorial/

It is a frequent source of frustration for new users, because it's notoriously outdated, see e.g. https://github.com/jOOQ/jOOQ/issues/9723

It uses a standalone code generation approach, which is not at all what I'd recommend new users do. It would be much better if new users could download an integration tested, maven-based example project from github that uses an in-memory database, such as H2, to minimise dependencies and risks of doing something wrong. Even the MCVE would be better suited than the current tutorial.

**Comment by perlun** [comment]
> It uses a standalone code generation approach, which is not at all what I'd recommend new users do.

I agree. I tried this approach for a while until a colleague managed to convince me to try a better approach... :grin:

**Comment by lukaseder** [comment]
The "downloadable example" will be hosted in a new project: https://github.com/jOOQ/demo

The task to create it is https://github.com/jOOQ/demo/issues/1

**Comment by lukaseder** [comment]
Closing this as a duplicate of https://github.com/jOOQ/demo/issues/1
