### ISSUE TITLE
Feedback about manual section "codegen-tables"

### ISSUE THREAD

**Issue by perlun** [jOOQ/jOOQ#12991]
This page states the following:

> **Routine** generation can be deactivated using the tables flag

I presume this should rather be something like this:

> **Table** generation can be deactivated using the tables flag

----
See: https://www.jooq.org/doc/3.16/manual/code-generation/codegen-tables/

**Comment by lukaseder** [comment]
Yes, thanks.

**Comment by lukaseder** [comment]
Other sections are affected, too: 

<img width="405" alt="image" src="https://user-images.githubusercontent.com/734593/152540877-0a648247-b4f1-4210-805a-44b5c5a13161.png">
