### ISSUE TITLE
ParsingConnection doesn't correctly execute batches when using ParamType.INLINED or StatementType.STATIC_STATEMENT

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#12998]
Creating a table like this:

```sql
create table t (s text);
```

Then, running this code on a `ParsingConnection`:

```java
@Test
public void testInsertBatch () throws SQLException {
    String sql = "INSERT INTO t VALUES (?)";
    try (PreparedStatement s = connection.prepareStatement(sql)) {
        for (int i = 1; i < 100; i++) {
            s.setString(1, Integer.toString(i));
            s.addBatch();
        }

        s.executeBatch();
    }
}
```

Inserts 100 times the value `1`, instead of the actual values. It seems that the batch bind values aren't maintained.

**Comment by lukaseder** [comment]
As reported by @wal1dcha1b in other issues, such as https://github.com/jOOQ/jOOQ/issues/12598#issuecomment-1027009374 and https://github.com/jOOQ/jOOQ-mcve/issues/19.

**Comment by lukaseder** [comment]
Our existing integration test looks like this, and it doesn't fail:

```java
public void testTranslateSQLExecuteJDBCDirectlyBatchSingle() throws Exception {
    String sql = "INSERT INTO t_author (id, first_name, last_name) VALUES (?, ?, ?)";

    try (Connection c = create(settings()).parsingConnection();
        PreparedStatement s = c.prepareStatement(sql)) {

        s.setInt(1, 3);
        s.setString(2, null);
        s.setString(3, "a");
        s.addBatch();
        s.setInt(1, 4);
        s.setString(2, "b");
        s.setString(3, "b");
        s.addBatch();
        s.setInt(1, 5);
        s.setString(3, "c");
        s.addBatch();
        s.executeBatch();

        Result<A> a = getAuthors(3, 4, 5);
        assertEquals(asList(3, 4, 5), a.getValues(TAuthor_ID()));
        assertEquals(asList(null, "b", "b"), a.getValues(TAuthor_FIRST_NAME()));
        assertEquals(asList("a", "b", "c"), a.getValues(TAuthor_LAST_NAME()));
        s.clearBatch();

        s.setInt(1, 6);
        s.setString(2, "d");
        s.setString(3, "d");
        s.addBatch();
        s.executeBatch();

        Result<A> a2 = getAuthors(3, 4, 5, 6);
        assertEquals(asList(3, 4, 5, 6), a2.getValues(TAuthor_ID()));
        assertEquals(asList(null, "b", "b", "d"), a2.getValues(TAuthor_FIRST_NAME()));
        assertEquals(asList("a", "b", "c", "d"), a2.getValues(TAuthor_LAST_NAME()));
   }
   finally {
       deleteAuthors(3, 4, 5, 6);
   }
}
```

However, I could reproduce the problem with @wal1dcha1b's MCVE as provided by email

**Comment by lukaseder** [comment]
Yeah, huh, the MCVE is using `settings.withParamType(ParamType.INLINED)`. This means that we inline the bind values of the first bind value set, and then repeat that without patching the SQL string again.

The main problem is first that we silently execute something that is clearly wrong. This could be fixed by throwing an exception when consecutive renderings don't produce the same SQL string for the batch (we're currently still re-parsing and re-generating the string on every bind set, at least when things aren't cached).

But when things are cached (and they should be, for performance reasons), then this can't be checked with reasonable efforts anymore.

So, the question is, should batching be rejected when `ParamType.INLINED` is set? @wal1dcha1b: What's the reason you turned on this flag in the first place?

**Comment by wal1dcha1b** [comment]
Hi @lukaseder,

Yes, I think this is caused by the ParamType.INLINED flag.
I've turned it on because it helped me out to overcome the implicit casts issues.

We are using **setString** for all the variable types, so I've created an implicit cast in postgresql :
CREATE CAST (character varying AS numeric)
	WITH INOUT
	AS IMPLICIT; 
and i've used this Inlined flag.
Otherwise, if the flag is off, it would work with the numeric columns, but not with bigint, smallint, and integer ..., and if  we create the same cast for the other numeric types, it would be ambiguous for the database to know which cast to use...

It's complicated, if you see what I am through

**Comment by lukaseder** [comment]
> It's complicated, if you see what I am through

Yes, you can probably write a book by now 😅

I'll think about what this all means for jOOQ and batch statements. Probably, we'd have to untangle the batch and run queries individually again. Worse performance, but at least it's correct... Will get back to this issue next week. For now, if you know you're batching, you should probably turn off the `ParamType.INLINED` flag.

**Comment by wal1dcha1b** [comment]
Yes, Thank you.

I'll keep you updated.

**Comment by user18081998** [comment]
Hello @lukaseder I am picking up @wal1dcha1b 's work after 2 years and we still do have this problem. Can you please look into this issue again?

**Comment by lukaseder** [comment]
Thanks for your ping, @user18081998. To be sure, nothing has changed on your end? This is still about using `ParamType.INLINED` or `StatementType.STATIC_STATEMENT` on your translated SQL queries, and then batching failing?

**Comment by user18081998** [comment]
Yes exactly except we are using the default statementType (StatementType.PREPARED_STATEMENT)

**Comment by lukaseder** [comment]
Thanks for the confirmation. The two have the same effect on rendered SQL

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.6 (https://github.com/jOOQ/jOOQ/issues/16357)
- 3.18.13 (https://github.com/jOOQ/jOOQ/issues/16358)
- 3.17.22 (https://github.com/jOOQ/jOOQ/issues/16359)
