### ISSUE TITLE
Compilation error in KotlinGenerator output when implicit join path cache conflicts with keyword

### ISSUE THREAD

**Issue by owyke** [jOOQ/jOOQ#13008]
### Expected behavior
Expected to get Kotlin code that compiles.
### Actual behavior
The name of the one to many mapping is an invalid identifier which fails compilation.

### Steps to reproduce the problem
Running jOOQ codegen with `org.jooq.codegen.KotlinGenerator` having a one to many relation named as a kotlin keyword results in a compilation error.

See MCVE @ https://github.com/owyke/jOOQ-mcve

### Versions

- jOOQ: 3.16.3
- Java: N/A
- Database (include vendor): N/A
- OS: N/A
- JDBC Driver (include name if inofficial driver): N/A

**Comment by lukaseder** [comment]
Thanks a lot for your report and MCVE. I can reproduce the problem. Will investigate.

**Comment by lukaseder** [comment]
Thanks for your suggested PR. I agree with your fix.

Would you mind signing the transfer of rights agreement which allows for dual licensing your fix? https://www.jooq.org/legal/contributions

**Comment by owyke** [comment]
Glad to be able to contribute to such an awesome project.
I just signed the agreement.

**Comment by lukaseder** [comment]
Thanks, @owyke, and thanks again for your report!

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0, 3.16.4 (https://github.com/jOOQ/jOOQ/issues/13019), and 3.15.8 (https://github.com/jOOQ/jOOQ/issues/13020)

**Comment by lukaseder** [comment]
This fix was incomplete at the time, as the assumption was that backticks `` ` `` are introduced to support reserved words as identifiers / method names, etc. But they're also used for quoting of identifiers containing special characters, which is still not supported:

- https://github.com/jOOQ/jOOQ/issues/18654
