### ISSUE TITLE
Add a rootPath property to the LiquibaseDatabase configuration for the FileSystemResourceAccessor

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13031]
As previous issues have shown:

- https://github.com/jOOQ/jOOQ/issues/11659
- https://github.com/jOOQ/jOOQ/issues/12872

Starting from jOOQ 3.16, with our Liquibase 4.x dependency, we need to offer a new `rootPath` configuration to pass to the `FileSystemResourceAccessor`. The correct configuration could then look like this:

```xml
<execution>
    <id>generate-liquibase-xml-rootpath</id>
    <phase>generate-test-sources</phase>
    <goals>
        <goal>generate</goal>
    </goals>
    <configuration>
        <generator>
            <database>
                <name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
                <properties>
                    <property>
                        <key>rootPath</key>
                        <value>${basedir}/src/main/resources</value>
                    </property>
                    <property>
                        <key>scripts</key>
                        <value>liquibase.xml</value>
                    </property>
                </properties>
            </database>
            <target>
                <packageName>org.jooq.codegen.test.liquibase.xml.db</packageName>
            </target>
        </generator>
    </configuration>
</execution>
```

**Comment by lukaseder** [comment]
An error that may appear with this new feature is:

> 17:51:25,147 [ERROR] Failed to execute goal org.jooq.trial:jooq-codegen-maven:3.17.0-SNAPSHOT:generate (generate-liquibase-xml-rootpath) on project jooq-test-codegen: Error running jOOQ code generation tool: Error while exporting schema: Error Reading Changelog File: Found 2 files that match liquibase.xml: file:/C:/Users/lukas/jOOQ/3.17/workspace/jOOQ-pro/jOOQ-test-codegen/src/main/resources/liquibase.xml, file:/C:/Users/lukas/jOOQ/3.17/workspace/jOOQ-pro/jOOQ-test-codegen/target/classes/liquibase.xml

I guess the solution will be that in the presence of a `rootPath`, we use *only* `FileSystemResourceAccessor`, and in the absence, we use *only* `ClassLoaderResourceAccessor`

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0 and 3.16.5 (https://github.com/jOOQ/jOOQ/issues/13032)

**Comment by lukaseder** [comment]
Thanks for your message, @marcelstoer. 

> (I hope it's ok to leave a comment rather than opening a new issue or asking on SO or the Google Groups.)

Sure it's OK. It just means that there's a quick question and answer, and any problem that you might have right now won't be tracked on the issue tracker, if that's what you intended.

If you're certain that it's a bug/regression, a new issue is obviously better, it can still be closed or rejected, if it's not.

In any case, I'm not sure if this is really a problem caused by jOOQ. You've asked a similar question before, and I closed it as a duplicate:

- https://github.com/jOOQ/jOOQ/issues/15393

Personally, I don't have a ton of confidence that jOOQ can reasonably keep up with Liquibase's frequent incompatible changes in this area without breaking things as well. But if you can provide an MCVE (via a new issue), I'll be happy to have a closer look.

Keep in mind that the `LiquibaseDatabase` is a quick-and-dirty utility that simplifies code generation based on liquibase migrations. A much more thorough way to generate jOOQ code is to use testcontainers and run an actual migration there. See this post with a Flyway example, which should be equivalent:
https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

**Comment by marcelstoer** [comment]
> If you're certain that it's a bug/regression

I am certain it is _not_ a jOOQ issue 😄 I was simply wondering how to best deal with the issue Liquibase left us with. Maybe you have ideas we didn't think of.

> You've asked a similar question before

Indeed, when I took to the internet yesterday looking for similar reports I found my own GH issue from last summer. Then I remembered that I had attempted to update from 3.14 to 3.18 (Pro) before, but had given up then.

To summarize:
- If your Liquibase changesets are not on the classpath and have only "local" references
-> use `rootPath` and `scripts`
- If your Liquibase changesets are not on the classpath but have classpath references
-> you can't use `rootPath`
-> instead add the changeset location to the classpath

Your plugin should run in the Maven `generate-sources` phase at which point the Maven resources are not available `target/classes` yet and, hence, the plugin's classpath doesn't contain them yet.

Is there a way to tell the plugin to include `src/main/resources` in its classpath? I checked the generator config XSD but didn't find anything.

**Comment by lukaseder** [comment]
> > If you're certain that it's a bug/regression
> 
> I am certain it is _not_ a jOOQ issue 😄 I was simply wondering how to best deal with the issue Liquibase left us with. Maybe you have ideas we didn't think of.

I don't. But I'm curious to learn if jOOQ is doing something suboptimal. I haven't looked into Liquibase's more recent improvements. Perhaps it is now again possible to combine classpath lookups with non-classpath lookups. I recall it was possible in Liquibase before, and there's an issue discussing their backwards incompatible change, where several folks were complaining about it... Perhaps they reverted it by now?

> Your plugin should run in the Maven `generate-sources` phase at which point the Maven resources are not available `target/classes` yet and, hence, the plugin's classpath doesn't contain them yet.

Well, the recommended approach from jOOQ's perspective is often to modularise things, see also the `JPADatabase`:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-jpa/

```
                        +-------------------+
                        | Your JPA entities |
                        +-------------------+
                             ^         ^
                  depends on |         | depends on
                             |         |
          +---------------------+   +---------------------+
          | jOOQ codegen plugin |   | Your application    |
          +---------------------+   +---------------------+
                             |         |
                   generates |         | depends on
                             v         v
                     +-------------------------+
                     | jOOQ generated classes  |
                     +-------------------------+
```

People seem to try to avoid modularising their application, but there are a lot of benefits if the application is modular.

> Is there a way to tell the plugin to include `src/main/resources` in its classpath? I checked the generator config XSD but didn't find anything.

jOOQ really really doesn't want to start getting opinionated about what things are considered the "classpath." Such problem should *always* be solved by build system configuration.

**Comment by marcelstoer** [comment]
Thanks for the additional feedback. Just FYI in case someone else might ask for it, there's another issue that currently prevents me from upgrading: https://github.com/mockk/mockk/issues/1118. Affects only Kotlin + mockk setups.
