### ISSUE TITLE
Avoid generating H2 NUMBER type alias for NUMERIC types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13043]
Historically, we assumed `NUMBER` (as in Oracle) is just an alias for `NUMERIC` (as in PostgreSQL). Because H2 supported `NUMBER` as well, we've generated that for H2. But it seems that a recent version of H2 has incompatibly changed the alias to mean `DECFLOAT` now, a new H2 (and standard SQL) type.

Given this script:

```sql
create table t (n number, m numeric);

select data_type, h2version()
from INFORMATION_SCHEMA.COLUMNS
where table_name = 'T'
```

We can observe:

**In H2 2.0.202**:

```
|DATA_TYPE|H2VERSION()|
|---------|-----------|
|NUMERIC  |2.0.202    |
|NUMERIC  |2.0.202    |
```

**In H2 2.1.210**

```
|DATA_TYPE|H2VERSION()|
|---------|-----------|
|DECFLOAT |2.1.210    |
|NUMERIC  |2.1.210    |
```

We currently do not yet support the `DECFLOAT` data type, see https://github.com/jOOQ/jOOQ/issues/10880

~This is an incompatible change compared to the behaviour of jOOQ 3.16.x, especially when using `NUMERIC` for `CAST` and in DDL, so I won't backport this issue.~

**Comment by lukaseder** [comment]
Thinking about this, the problem is created by an incompatible change in H2 along with the fact that jOOQ generated `NUMBER` for `NUMERIC` casts and column definitions, so the expectation is really for jOOQ `SQLDataType.NUMERIC` to produce a `NUMERIC` column also in H2.

I'll backport.

**Comment by katzyn** [comment]
@lukaseder
In H2 2.0.204 and later versions `NUMBER` means `DECFLOAT(40)`, `NUMBER(something)` means `NUMERIC(something)` for better compatibility with Oracle and it actually should normally be used only in Oracle compatibility mode, it isn't a native data type of H2. H2 actually can reject it in some other modes (currently only in PostgreSQL compatibility mode).

**Comment by lukaseder** [comment]
> In H2 2.0.204 and later versions `NUMBER` means `DECFLOAT(40)`, `NUMBER(something)` means `NUMERIC(something)` for better compatibility with Oracle

Huh, not sure if I would have managed to reverse engineer these rules 😅.

> it isn't a native data type of H2. H2 actually can reject it in some other modes (currently only in PostgreSQL compatibility mode).

Maybe not anymore? I guess I had implemented that stuff about 12 years ago. Perhaps at the time, `NUMBER` was documented? Anyway. Good riddance. We shouldn't generate `NUMBER` for `NUMERIC` types.
