### ISSUE TITLE
Support array[] syntax for PostgreSQL dialect?

### ISSUE THREAD

**Issue by victornoel** [jOOQ/jOOQ#13045]
### Expected behavior

```sql
SELECT unnest(ARRAY['a','b']) AS foo
```

should be accepted by the parser as it is valid PostgreSQL syntax

### Actual behavior

Instead it gives me the following error:
```
Unknown function: [1:15] SELECT unnest([*]array['a','b']) as foo
```

### Steps to reproduce the problem

On https://www.jooq.org/translate/ it doesn't work :)

### Versions

- jOOQ: 3.15.4 and up I guess?
- Java: 11
- Database (include vendor): PostgreSQL

**Comment by lukaseder** [comment]
Thanks for your report. I wish that "feature" would go away from PostgreSQL. How can any function in the `SELECT` clause produce more than one row in the result set? It's against everything logical in SQL. Not just that, you might think that this produces a cartesian product with the rest of your query, but nope, try this:

```sql
SELECT unnest(ARRAY['a', 'b']) AS a, unnest(ARRAY[1, 2, 3]) AS b
```

The result isn't a cartesian product, but a full outer join on the array ordinals:

```
|a  |b  |
|---|---|
|a  |1  |
|b  |2  |
|   |3  |
```

So, it means the same thing as this:

```sql
SELECT a, b
FROM unnest(ARRAY['a', 'b']) WITH ORDINALITY AS a (a, o)
FULL OUTER JOIN unnest(ARRAY[1, 2, 3]) WITH ORDINALITY AS b (b, o) USING (o)
```

I don't really want to spend too much time on this "feature", given that the recommended way to use `UNNEST` in PostgreSQL (in my opinion) is the standard SQL syntax, which we do support:

```sql
SELECT * FROM unnest(ARRAY['a','b']) AS foo (foo)
```

**Comment by victornoel** [comment]
@lukaseder thx for the explanation, and especially for the alternative standard SQL syntax! I agree with you it looks better and less error prone :)
