### ISSUE TITLE
Ability to configure Deprecated-annotation on columns and tables

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#13052]
### Use case:

Given a list of columns and/or tables that we want to remove from our database schema, it would be nice if we could configure jOOQ to add `@Deprecated`-annotations on the generated code for us.

This functionality would make it much easier for us to communicate breaking changes in the database schema in a way that can be picked up by developers and CI-systems etc.

**Comment by lukaseder** [comment]
Does a `@deprecated` Javadoc tag suffice or do you need the annotation? If it's the former case, then you can do that with synthetic comments:

https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-comments

For IDEs and thus developers, it should be enough. Maybe not for your CI-system use-case? What would be a use-case that requires the annotation?

**Comment by alf** [comment]
I wasn’t aware of that possibility. I’ll close this for now and re-open if it’s not sufficient. Thanks.
