### ISSUE TITLE
Feedback about manual section "for-update-clause"

### ISSUE THREAD

**Issue by haumacher** [jOOQ/jOOQ#13064]
The page does not say how I actually can perform the update on the result set. 

```
		Result<Record> result = _context.select().from(MY_TABLE).where(MY_TABLE.COL.eq(value)).forUpdate().fetch();
		for (Record record : result) {
			record.setValue(MY_TABLE.COL, newValue);
			
			result.up...???
		}
```
Am I missing something?

----
See: https://www.jooq.org/doc/3.16/manual/sql-building/sql-statements/select-statement/for-update-clause/

**Comment by lukaseder** [comment]
You're probably looking for the equivalent of JDBC's `ResultSet.CONCUR_UPDATABLE` flag, which jOOQ currently doesn't support: https://github.com/jOOQ/jOOQ/issues/1846. This has already been a relatively rare use case in JDBC itself, and in 13 years of jOOQ, it's the first time I've seen it being requested from jOOQ.

You can upvote https://github.com/jOOQ/jOOQ/issues/1846, but I don't think we'll be implementing this any time soon.

In the meantime, you can emulate the feature with jOOQ by specifying the `ResultQuery::resultSetConcurrency` and possibly the `ResultQuery::resultSetType` prior to execution, and then execute the query with `ResultQuery::fetchLazy` before accessing the underlying JDBC `ResultSet` via `Cursor::resultSet`, e.g.

```java
try (Cursor<Record> result = _context.select()
    .from(MY_TABLE)
    .where(MY_TABLE.COL.eq(value))
    .forUpdate()
    .resultSetConcurrency(ResultSet.CONCUR_UPDATABLE)
    .fetchLazy()
) {
    for (Record record : result) {
        result.resultSet().setString(index, newValue);

        // No update needed
        // result.up...???
    }
}
```

If that's not what you're looking for, you can always fetch updatable records:
https://www.jooq.org/doc/latest/manual/sql-execution/crud-with-updatablerecords/

And then call `DSLContext.batchStore()` on the modified records, or something like that.
