### ISSUE TITLE
Postgres JSONB in WHERE CLAUSE

### ISSUE THREAD

**Issue by Mike497** [jOOQ/jOOQ#13125]
### Question:

Hello to JOOQ community!)
I have Postgres DB table like this:
`CREATE TABLE event (
    id serial NOT NULL PRIMARY KEY
    properties jsonb NOT NULL
);`
Properties column contains JSON array values, e.g. like: [{"key": "value"}]

Using maven plugin, I'm generating JOOQ classes to work with it. Also, there I have a custom binding from JSONB properties to my custom Java class. Everything works well (inserting/fetching records), but I have an issue when building filter JOOQ query with WHERE clause for properties column. I try to create JOOQ condition like this to get property with specific key value:

`DSL.condition("{0} @> {1}", Event.EVENT.PROPERTIES, "[{\"key\": \"" + value + "\"}]")`

So, I'm expecting Postgres 'contains' ( @> ) operator to work, but `.fetch()` fails with DataAccessException:
`ERROR: operator does not exist: jsonb @> character varying
Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
Position: 345`

Funny thing here is when in debug mode I try to get query as String and execute it in Postgres client, it works fine.) It produces WHERE clause string like this:
`where ("service"."event"."properties" @> '[{"key": "test-value"}]')`
and actually filters necessary data.

But when executing Java code, I'm getting the above error...
Could you please help me to fix it?

### Versions:

- jOOQ: 3.14.8
- Java: 11
- Database (include vendor): Postgres 12
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver

**Comment by Mike497** [comment]
UPD:
I solved this issue by writing condition like this:
`DSL.condition("{0} @> {1}", Event.EVENT.PROPERTIES, JSONB.valueOf("[{\"key\": \"" + value + "\"}]"))`

**Comment by lukaseder** [comment]
Thanks a lot for your message. I'm glad to see that you've already found a solution.

In [plain SQL templating](https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/), anything that isn't an `org.jooq.QueryPart` will be wrapped as a bind variable using `DSL.val(Object)`. So, your solution is the same as this:

```java
// Yours
DSL.condition("{0} @> {1}", Event.EVENT.PROPERTIES, JSONB.valueOf("[{\"key\": \"" + value + "\"}]"))

// ... is convenience for:
DSL.condition("{0} @> {1}", Event.EVENT.PROPERTIES, val(JSONB.valueOf("[{\"key\": \"" + value + "\"}]")))
```

The latter can be useful in case you need additional converters / bindings attached. Alternatively, you can take care of the proper SQL generation yourself, this being a plain SQL template. If you wish to bind a `String` value as you attempted originally, just cast the bind value to `JSONB` manually:

```java
DSL.condition("{0} @> {1}::jsonb", Event.EVENT.PROPERTIES, "[{\"key\": \"" + value + "\"}]")
```

I hope this helps
