### ISSUE TITLE
Does BeanCopier not support org.jooq.JSON?

### ISSUE THREAD

**Issue by Matthew-Han** [jOOQ/jOOQ#13130]
### Your question:

I used json type fields in MySQL5.7，So my record and pojo class is also json type, like this:

```java

PageRes page = new PageRes(1, 10);
List<TShow> shows = showDao.fetchPage(
                page,
                ctx.select().from(T_SHOW).where(xxx),
                TShow.class);

public class TShow {
  ...
  private org.jooq.JSON field;
}
```
Now I have a VO with exactly the same field and type, like this:

```java
public class ShowVO {
  ...
  private org.jooq.JSON field;
}
```

And I want to copy the properties with BeanCopier and build a res. Although I successfully copy the value to VO, I get this Exception:

```java
org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class org.jooq.JSON]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.jooq.JSON and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.xxx.model.R["data"]->java.util.ArrayList[0]->com.xxx.vo.ShowVO["fieId"])
```

But the fieId in ShowVO has TShow's value, but there is always get this Exception.

### Versions:

- jOOQ: 3.14.15
- Java: 1.8
- Database (include vendor): MySQL
- OS: current macOS
- JDBC Driver 8.0.25

**Comment by lukaseder** [comment]
Thanks a lot for your message. I'm not sure what `BeanCopier` is or how it should be involved here. But from your stack trace, it seems it's using Jackson behind the scenes? If you have Jackson on the classpath, why keep a reference to JSON data, when you can map stuff automatically, instead?

e.g.

```java
public class Something {
  String firstName;
  String lastName;
}
public class ShowVO {
  ...
  private Something  field;
}
```

And now let jOOQ / Jackson map things automatically:

```java
List<TShow> shows = showDao.fetchPage(
                page,
                ctx.select().from(T_SHOW).where(xxx),
                ShowVO.class); // Map the JSON automatically to Something
```

This is a `DefaultConverterProvider` feature in jOOQ, see:
https://www.jooq.org/doc/latest/manual/sql-execution/fetching/converter-provider/

I hope this helps

**Comment by Matthew-Han** [comment]
> Thanks a lot for your message. I'm not sure what `BeanCopier` is or how it should be involved here. But from your stack trace, it seems it's using Jackson behind the scenes? If you have Jackson on the classpath, why keep a reference to JSON data, when you can map stuff automatically, instead?
> 
> e.g.
> 
> ```java
> public class Something {
>   String firstName;
>   String lastName;
> }
> public class ShowVO {
>   ...
>   private Something  field;
> }
> ```
> 
> And now let jOOQ / Jackson map things automatically:
> 
> ```java
> List<TShow> shows = showDao.fetchPage(
>                 page,
>                 ctx.select().from(T_SHOW).where(xxx),
>                 ShowVO.class); // Map the JSON automatically to Something
> ```
> 
> This is a `DefaultConverterProvider` feature in jOOQ, see: https://www.jooq.org/doc/latest/manual/sql-execution/fetching/converter-provider/
> 
> I hope this helps

Thank you for your answer! JooQ is a special product, and I can see your team's efforts, thank you very much!
