### ISSUE TITLE
Feedback about manual section "codegen-ddl"

### ISSUE THREAD

**Issue by roded** [jOOQ/jOOQ#13189]
This is a very useful feature to allow end-to-end build of a jOOQ project with no external dependencies. Please continue to support.

A space is missing in "Ignoring unsupportedcontent".

Cheers.

----
See: https://www.jooq.org/doc/3.16/manual/code-generation/codegen-ddl/

**Comment by lukaseder** [comment]
Thanks for your feedback about the feature and the typo. The typo is fixed. A new manual version should be deployed soon.
