### ISSUE TITLE
KotlinGenerator cannot read existing catalog/schema version

### ISSUE THREAD

**Issue by gavlyukovskiy** [jOOQ/jOOQ#13211]
### Expected behavior
[Schema and catalog versions](https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-version-providers/) can be used to avoid code re-generation. This should be supported for `KotlinGenerator` as well as `JavaGenerator`.

### Actual behavior
When using `KotlinGenerator` the code to read old version
```
String oldVersion = readVersion(getFile(catalog), "catalog");
```
returns `null` due to [regex](https://github.com/jOOQ/jOOQ/blob/version-3.16.0-branch/jOOQ-codegen/src/main/java/org/jooq/codegen/JavaGenerator.java#L8405) expecting curly braces (`{`) instead of square braces (`[`) inside `@Generated` annotation (see examples below).

### Steps to reproduce the problem

- If the problem relates to code generation, please post your code generation configuration
```
<plugin>
    <groupId>org.jooq</groupId>
    <artifactId>jooq-codegen-maven</artifactId>
    <executions>
        <execution>
            <id>generate-sources</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <jdbc>
                    <driver>org.postgresql.Driver</driver>
                    <url>jdbc:postgresql://localhost:5432/db</url>
                    <user>user</user>
                    <password>password</password>
                </jdbc>
                <generator>
                    <name>org.jooq.codegen.KotlinGenerator</name>
                    <database>
                        <name>org.jooq.meta.postgres.PostgresDatabase</name>
                        <includes>.*</includes>
                        <inputSchema>public</inputSchema>
                        <catalogVersionProvider>SELECT :catalog_name || '_1'</catalogVersionProvider>
                        <schemaVersionProvider>SELECT :schema_name || '_1'</schemaVersionProvider>
                    </database>

                    <generate>
                        <pojos>true</pojos>
                        <javaTimeTypes>true</javaTimeTypes>
                        <fluentSetters>true</fluentSetters>
                    </generate>
                    <target>
                        <packageName>com.example.model</packageName>
                        <directory>src/main/kotlin</directory>
                    </target>
                </generator>
            </configuration>
        </execution>
    </executions>
</plugin>
```

For this configuration `KotlinGenerator` produces:
```
@Generated(
    value = [
        "https://www.jooq.org",
        "jOOQ version:3.14.15",
        "catalog version:_1"
    ],
    comments = "This class is generated by jOOQ"
)
```

while `JavaGenerator` produces:
```
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.14.15",
        "catalog version:_1"
    },
    comments = "This class is generated by jOOQ"
)
```

### Versions

- jOOQ: 3.14.15
- Java: 17
- Kotlin: 1.6.10
- Database (include vendor): Postgres 11
- OS: MacOS 12.1
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.3.1 (official)

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can reproduce this. Probably, the `ScalaGenerator` is also affected

**Comment by gavlyukovskiy** [comment]
@lukaseder seems like is handled specifically there - `+ (scala ? "Array\\([^)]*?" : "\\{[^}]*?") +`, I have opened PR to use different one for Kotlin as well - #13212

**Comment by lukaseder** [comment]
Right.

**Comment by gavlyukovskiy** [comment]
Thank you, @lukaseder!
