### ISSUE TITLE
Add Javadoc to all XJC-generated "withers" and setters of boolean types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13225]
Some "withers" don't have any Javadoc, e.g. `Settings::withRenderCatalog`. Others do, e.g. `Settings::withRenderMapping`. That's probably a bug in the XJC plugin used to generate these withers: `org.jvnet.jaxb2_commons:jaxb2-fluent-api:3.0`

The plugins aren't really maintained anymore, so perhaps we just roll our own, instead?

**Comment by axelfontaine** [comment]
I just hit this today with `withReturnAllOnUpdatableRecord`. This would be quite a usability improvement for anyone configuring the `Settings` object with code completion in an IDE.

**Comment by lukaseder** [comment]
Yeah, I ran into this again recently. We already have an XJC plugin to add our own `equals()`, `hashCode()`, `toString()` methods, as well as `XMLBuilder` and `XMLAppendable` API, perhaps it isn't so hard and painful after all...

**Comment by lukaseder** [comment]
Hmm, the Javadoc is absent, when there's no useful documentation on the setter. Check the `setReturnAllOnUpdatableRecord` method. Its Javadoc is generic and not really useful. I wonder why this is the case. It's present on the getter `isReturnAllOnUpdatableRecord`. This seems to happen with all `boolean` typed methods.

**Comment by lukaseder** [comment]
Yeah, turns out this isn't hard at all.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.2 (https://github.com/jOOQ/jOOQ/issues/16066)
- 3.18.9 (https://github.com/jOOQ/jOOQ/issues/16067)
- 3.17.18 (https://github.com/jOOQ/jOOQ/issues/16068)
