### ISSUE TITLE
Add more examples to manual section "codegen-database-version-providers"

### ISSUE THREAD

**Issue by seanf** [jOOQ/jOOQ#13246]
This section mentions three possibilities for the code generation SPI:

> - By providing a fully qualified class name that implements any of `org.jooq.meta.CatalogVersionProvider` or `org.jooq.meta.SchemaVersionProvider` respectively for programmatic version providing.
> - By providing a `SELECT` statement returning one row with one column containing the version string. The `SELECT` statement may contain a named variable called `:catalog_name` or `:schema_name` respectively.
> - By providing a constant, such as a Maven property, for instance.

But only the second option (a `SELECT` statement) _appears_ to have any examples. I had to read http://www.jooq.org/xsd/jooq-codegen-3.16.0.xsd before I realised that the same property can be used with any of the three value types (class name, `SELECT` statement string or a constant). It would be nice if this were clearer, since there is some helpful guidance hidden away inside the XSD. 

Also, despite the name "XML (standalone and maven)" it's not entirely obvious that the example `<configuration>` in the XML example can be used directly as the `<configuration>` of the Maven plugin. By way of comparison, it's an unfortunate fact that the cargo-maven-plugin uses an element called `<configuration>` for a _subtree_ of its Maven `<configuration>`.

(My interest is in skipping codegen (and ideally a container startup via `org.testcontainers.jdbc.ContainerDatabaseDriver`) when my schema SQL file hasn't changed, based on a SHA1 checksum in a Maven property. I got something working via antrun, but unfortunately jOOQ still connects to the database and triggers the container startup.)

----
See: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-version-providers/

**Comment by lukaseder** [comment]
I've pushed an improved manual section that lists more configuration examples. I'll be happy to address other concerns in separate issues

**Comment by seanf** [comment]
> Thanks for your valuable feedback.
> 
> > But only the second option (a `SELECT` statement) _appears_ to have any examples [...]
> 
> I agree, you shouldn't have to look at the XSD to find out how to actually configure the other 2 bullets. I'll rewrite this section so that each bullet has its own example code snippet.

Great, thanks Lukas.
> 
> > Also, despite the name "XML (standalone and maven)" it's not entirely obvious that the example `<configuration>` in the XML example can be used directly as the `<configuration>` of the Maven plugin.
> 
> What alternative would have made this clearer, keeping in mind that we don't want to add too much noise to the manual, which keeps repeating this `<configuration>` element?

Given that understandable constraint, I'm not sure. Maybe a link to a section that talks about how `<configuration>` works in Maven (ie just the same as a jOOQ XML file). Most devs would probably just assume that `<configuration>` equals `<configuration>` and be fine - I'm just shell-shocked by having used cargo. I guess the `xmlns` attribute threw me too - I'm not used to seeing that in Maven configuration.

> Note, if any improvement is possible, it would be done in a separate issue, as it isn't strictly related to this section here.
> 
> > I got something working via antrun, but unfortunately jOOQ still connects to the database and triggers the container startup
> 
> Can you create a separate feature request for this?

Will do. Thanks.
