### ISSUE TITLE
Manual should distinguish more clearly between Maven XML and standalone XML content

### ISSUE THREAD

**Issue by seanf** [jOOQ/jOOQ#13262]
On pages like this, I found the "XML (standalone and maven)" configuration a bit confusing. It wasn't entirely obvious (at least to me) that the example `<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.16.5.xsd">` in the XML example could be used directly as the `<configuration>` of the Maven plugin. 

My experience is coloured by the unfortunate fact that the cargo-maven-plugin uses an element called `<configuration>` for a _subtree_ of its Maven `<configuration>`. I think I was also confused by the presence of `xmlns="http://www.jooq.org/xsd/jooq-codegen-3.16.5.xsd"` which seems pretty unusual for Maven plugin configuration.

As for how to make this clearer (across all the pages which use this pattern), it's hard to say, but maybe one of these:

- split the jooq-config.xml example tab out from Maven XML (and strip the `xmlns`)
- add a link to a page which explains that the same configuration actually does work in both contexts. This could be done via the Help overlay, although to be honest I hadn't read that whole [help page](https://www.jooq.org/doc/latest/manual/getting-started/the-manual) before now. 
![image](https://user-images.githubusercontent.com/54155/157823024-fa18f586-1c94-4c3a-beba-fe61651ed453.png)
- assume that most devs haven't had to deal with cargo-maven-plugin and will probably just get it

Related: https://github.com/jOOQ/jOOQ/issues/13246

----
See: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-version-providers/

**Comment by lukaseder** [comment]
Thanks a lot for your feedback, that makes sense. I'll think about how this could be improved.

**Comment by lukaseder** [comment]
So, it is indeed weird to document the XML namespace in Maven, although, it's still useful to know that an XSD exists, where users can read about their options. I'm aware of a lot of users who look up the XSD for guidance as it is a simple reference that documents *all* flags, compared to the manual where flags are documented across many sections.

So, I think:

- It's definitely worth creating separate tabs for Maven XML and standalone XML
- The standalone XML would contain what the current XML for both contexts contains
- The Maven XML would
  - Have the xmlns moved from the `<configuration>` attribute to a comment indicating compatibility
  - Another comment that could be helpful is that a Maven `<configuration>` can be part of the `<plugin>` or `<execution>`
  - These two comments should fit in a single line, which is probably possible
- The help section could definitely contain some additional info about how this works
- The main section explaining the maven plugin already explains that the two types of `<configuration>` are compatible: https://www.jooq.org/doc/3.16/manual/code-generation/codegen-maven. But obviously, no matter what is documented, such things are hard to find 😉

The main benefit of this improvement would then be to remove the confusion about the `xmlns` attribute.

**Comment by lukaseder** [comment]
Looking into this now. My feeling here is that my previous comment would overcomplicate things. It should be sufficient to just move the `xmlns` from an attribute to a comment documenting the XSD. The formal declaration isn't necessary in the standalone case either...

**Comment by seanf** [comment]
> Looking into this now. My feeling here is that my previous comment would overcomplicate things. It should be sufficient to just move the `xmlns` from an attribute to a comment documenting the XSD. The formal declaration isn't necessary in the standalone case either...

That makes sense, but I did like the sound of this:

> * Another comment that could be helpful is that a Maven `<configuration>` can be part of the `<plugin>` or `<execution>`

**Comment by lukaseder** [comment]
> That makes sense, but I did like the sound of this:
> 
> > * Another comment that could be helpful is that a Maven `<configuration>` can be part of the `<plugin>` or `<execution>`

The jOOQ manual can't explain maven basics on every page, though

**Comment by lukaseder** [comment]
> > That makes sense, but I did like the sound of this:
> > > * Another comment that could be helpful is that a Maven `<configuration>` can be part of the `<plugin>` or `<execution>`
> 
> The jOOQ manual can't explain maven basics on every page, though

While these things can't be explained on every page, it probably doesn't hurt to link to these sections from every code generation example:

- https://www.jooq.org/doc/latest/manual/code-generation/codegen-maven/
- https://www.jooq.org/doc/latest/manual/code-generation/codegen-gradle/
- https://www.jooq.org/doc/latest/manual/code-generation/codegen-programmatic/

Anything maven specific that needs explaining will then be covered (it is, already) in the maven section.

**Comment by seanf** [comment]
> > > That makes sense, but I did like the sound of this:
> > > > * Another comment that could be helpful is that a Maven `<configuration>` can be part of the `<plugin>` or `<execution>`
> > 
> > 
> > The jOOQ manual can't explain maven basics on every page, though

You're quite right, that fact is basic Maven plugin configuration. I didn't read that point closely enough before, sorry. If you know where plugin `<configuration>`s go in Maven plugin declarations generally, it's enough just to know that the example _is_ a Maven plugin `<configuration>` (which is where I had a misunderstanding initially).

> 
> While these things can't be explained on every page, it probably doesn't hurt to link to these sections from every code generation example:
> 
> * [jooq.org/doc/latest/manual/code-generation/codegen-maven](https://www.jooq.org/doc/latest/manual/code-generation/codegen-maven/)
> * [jooq.org/doc/latest/manual/code-generation/codegen-gradle](https://www.jooq.org/doc/latest/manual/code-generation/codegen-gradle/)
> * [jooq.org/doc/latest/manual/code-generation/codegen-programmatic](https://www.jooq.org/doc/latest/manual/code-generation/codegen-programmatic/)
> 
> Anything maven specific that needs explaining will then be covered (it is, already) in the maven section.

Yes, that makes sense. Thanks @lukaseder.

**Comment by seanf** [comment]
That looks much clearer now, thank you!
