### ISSUE TITLE
Feedback about manual section "checker-framework"

### ISSUE THREAD

**Issue by seanf** [jOOQ/jOOQ#13296]
The title mentions "Error Prone", but it's not mentioned again in the body, which makes it seem like a leftover.

Also, how is jooq-checker _actually_ integrated? It's not really covered in the manual page nor in the blog post, as far as I can see. 

Is it necessary to set up a given project either for Error Prone or for Checker, and then if jooq-checker is available on the annotation path it will just work? That seems to be the case in the sample project: https://github.com/jOOQ/jOOQ/blob/1eff19ed6db3c5a4f1f6e569a75ef1c23be789f5/jOOQ-examples/jOOQ-checker-framework-example/pom.xml#L85-L128

On the other hand, the example Maven config for maven-compiler-plugin in the blog post doesn't mention Checker or Error Prone, just jooq-checker. Ref https://blog.jooq.org/jsr-308-and-the-checker-framework-add-even-more-typesafety-to-jooq-3-9/#:~:text=specify%20the%20following%20Maven%20compiler%20configuration

Also, is there any way of choosing the default dialect for `SQLDialectChecker` for a whole application, without having to create a `package-info.java` in every package?

----
See: https://www.jooq.org/doc/latest/manual/tools/checker-framework/

**Comment by lukaseder** [comment]
Thanks for your message.

> The title mentions "Error Prone", but it's not mentioned again in the body, which makes it seem like a leftover.

Yeah, makes sense to add a Maven example also for error prone. I've created an issue for that: https://github.com/jOOQ/jOOQ/issues/13298

The example project already contains an example profile for error prone.

> Is it necessary to set up a given project either for Error Prone or for Checker, and then if jooq-checker is available on the annotation path it will just work?

Yes, that's how it works. `jooq-checker` is just a compiler plugin, which uses either the checker framework or error prone as a set of compiler plugin libraries, whatever works best for you (both have their issues and JDK incompatibilities, regrettably).

> On the other hand, the example Maven config for maven-compiler-plugin in the blog post doesn't mention Checker or Error Prone, just jooq-checker

The blog post is from 2016, when the error prone integration wasn't yet implemented. But again, both implementations work the same way from the jOOQ side of things. The difference is how you configure the checker in your compiler plugin configuration, and what kind of output you're getting.

> Also, is there any way of choosing the default dialect for `SQLDialectChecker` for a whole application, without having to create a `package-info.java` in every package?

See:

- https://github.com/jOOQ/jOOQ/issues/9115
- https://github.com/jOOQ/jOOQ/issues/12770
