### ISSUE TITLE
Microsoft SQL Server 2019 support

### ISSUE THREAD

**Issue by ergonben** [jOOQ/jOOQ#13327]
### Your question:

What are your plans to support SQL Server 2019 in jOOQ?

In the current [version support matrix](https://www.jooq.org/download/support-matrix), I see that the latest supported version is 2017.

We consider using DBMS version 2019 with jOOQ configuration `org.jooq.SQLDialect.SQLSERVER2017` but not sure if that's a good idea. Alternatively, we can consistently use DBMS version 2017 but it'd be nice if we could use the latest.

Thanks for any help.

### Versions:

- jOOQ: 3.16.5 Professional
- Java: 11 (AdoptOpenJDK)
- Database (include vendor): Microsoft SQL Server 2019
- OS: Linux
- JDBC Driver (include name if unofficial driver): `com.microsoft.sqlserver:mssql-jdbc:10.2.0.jre11`

**Comment by lukaseder** [comment]
Thanks a lot for your message. We've been supporting MS SQL Server 2019 for a long time now, but there hasn't been anything noteworthy (for jOOQ) in that version that warranted a dedicated dialect in jOOQ. See: https://docs.microsoft.com/en-us/sql/sql-server/what-s-new-in-sql-server-ver15?view=sql-server-ver15

This is why there isn't any `SQLSERVER2019` dialect. But of course, our support matrix should reflect that we officially support and integration test against SQL Server 2019.

I hope this clarifies things?

**Comment by lukaseder** [comment]
Support matrix is updated

**Comment by ergonben** [comment]
Thank you, all good then. That's hyperspeed.
