### ISSUE TITLE
Feedback about manual section "jooq-in-7-steps-step3"

### ISSUE THREAD

**Issue by Paurush496** [jOOQ/jOOQ#13332]
I find it very difficult to integrate this in a gradle project. I am not an expert using gradle, and hence need an appropriate documentation to follow.

----
See: https://www.jooq.org/doc/3.16/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step3/

**Comment by lukaseder** [comment]
Thanks for your feedback. We have a few open tasks to make gradle usage more first class in the manual and examples, e.g. by offering an official gradle plugin and some more downloadable examples.

In the meantime, why not follow the examples from the suggested third party gradle plugin?
https://github.com/etiennestuder/gradle-jooq-plugin
