### ISSUE TITLE
forceIntegerTypesOnZeroScaleDecimals with off-by-one error?

### ISSUE THREAD

**Issue by torstenwerner** [jOOQ/jOOQ#13340]
### Expected behavior

I expected that NUMBER(19) would be generated to a Long field as documented at https://www.jooq.org/doc/3.13/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-zero-scale-decimals/ but it is generated to BigInteger. But it works as expected for NUMBER(10).

### Actual behavior

I have checked the code org.jooq.impl.DefaultDataType#getNumericClass:

                else if (precision < LONG_PRECISION)
                  return Long.class;

Effectively it is `precision < 19` but shouldn't it be `precision <= 19` instead? If I am correct I'd like to see a change of `<` into `<=`.

### Steps to reproduce the problem

code generation gradle setup:

    jooq {
        version = '3.13.3'
        edition = nu.studer.gradle.jooq.JooqEdition.PRO_JAVA_8
        configurations {
            main {
                generationTool {
                    logging = org.jooq.meta.jaxb.Logging.WARN
                    jdbc {
                        driver = 'oracle.jdbc.driver.OracleDriver'
                        url = 'jdbc:oracle:thin:@//localhost:1521/ORCLCDB'
                        user = '...'
                        password = '...'
                    }
                    generator {
                        name = 'org.jooq.codegen.DefaultGenerator'
                        database {
                            name = 'org.jooq.meta.oracle.OracleDatabase'
                            schemata {
                                schema {
                                    inputSchema = 'one'
                                }
                                schema {
                                    inputSchema = 'two'
                                }
                                schema {
                                    inputSchema = 'three'
                                }
                            }
                            excludes = '(?i:BIN\\$.*)'
                        }
                        generate {
                            deprecated = false
                            records = true
                            immutablePojos = true
                            fluentSetters = true
                            pojosEqualsAndHashCode = true
                        }
                        target {
                            packageName = 'com.example.something'
                            directory = 'src/main/generated-java/'
                        }
                        strategy.name = 'org.jooq.codegen.DefaultGeneratorStrategy'
                    }
                }
            }
        }
    }

### Versions

- jOOQ: 3.13.3
- Java: 11
- Database (include vendor): oracle
- OS: macos
- JDBC Driver (include name if inofficial driver): com.oracle.database.jdbc:ojdbc8:19.13.0.0.1

**Comment by lukaseder** [comment]
Thanks a lot for your report. This is a documentation bug. It should read `NUMBER(18, 0)`, not `NUMBER(19, 0)`. The idea here is this: jOOQ is a database-first SQL API, meaning that your database holds the source of truth, more than your Java code. As such, the precision available in the database must fit into the corresponding Java type. `NUMBER(18, 0)` is guaranteed to fit in a `Long`. `NUMBER(19, 0)`, on the other hand, might overflow when reading it into a `Long`, so we must pick the next bigger integer type.

It's the same with all the other integer types, e.g. `NUMBER(2, 0)` is guaranteed to fit in a `Byte`, but `NUMBER(3, 0)` is very likely to overflow.

The next manual update will fix this. Thanks again for your report.
