### ISSUE TITLE
Invalid code generated when pojosEqualsAndHashCode option is enabled and column name is 'other'

### ISSUE THREAD

**Issue by spac-valentin** [jOOQ/jOOQ#13355]
### Expected behavior
`equals` to be working as expected.

### Actual behavior
Generated `equals` wrongly compares the object passed as parameter with the `other` field of the current instance.

### Steps to reproduce the problem

- create a table that has a column named `other` 
- generate pojo and check `equals` method.

### Versions

- jOOQ: 3.15.4
- Java: 13

```java
@Override
public boolean equals(Object obj) {
    if (this == obj)
        return true;
    if (obj == null)
        return false;
    if (getClass() != obj.getClass())
        return false;
    final MyObj other = (MyObj) obj;
    if (id == null) {
        if (other.id != null)
            return false;
    }
    else if (!id.equals(other.id))
        return false;
    if (other == null) {                // <- this should have been this.other, so that it refers to 
        if (other.other != null)   //  the field, not the other object
            return false;
    }
    else if (!other.equals(other.otherResources)) // should be !this.other.equals(...)
}

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0, 3.16.6 (https://github.com/jOOQ/jOOQ/issues/13356), and 3.15.10 (https://github.com/jOOQ/jOOQ/issues/13356). Thanks again for your report!
