### ISSUE TITLE
Generated SQL Server code uses `sp_executeSQL`, which fails for binary (case sensitive) collations

### ISSUE THREAD

**Issue by ergonben** [jOOQ/jOOQ#13379]
### Expected behavior

When using `alterColumn(…).defaultValue(42)`, jOOQ should generate SQL Server code with `sp_executesql`. Such code is valid even for a binary DB collation like `Latin1_General_100_BIN2`.

### Actual behavior

The generated code uses `sp_executeSQL`, which then fails on execution with an error: "Could not find stored procedure 'sp_executeSQL'." For case insensitive collations, there is no such error.

### Steps to reproduce the problem

Complete reproduction case: https://github.com/ergonben/jOOQ-mcve

### Versions

- jOOQ: 3.16.5 Professional
- Java: 11 (AdoptOpenJDK)
- Database (include vendor): Microsoft SQL Server 2019
- OS: Linux
- JDBC Driver (include name if unofficial driver): `com.microsoft.sqlserver:mssql-jdbc:10.2.0.jre11`

**Comment by lukaseder** [comment]
Thanks a lot for your report. That's weird, it looks as though some regex search/replace produced the upper case `SQL`. Will fix right away.

**Comment by ergonben** [comment]
Thank you very much! Looking forward to these releases then. Do you have a planned release date so that I can manage expectations?
