### ISSUE TITLE
Embedded keys cause the original column(s) to be private?

### ISSUE THREAD

**Issue by atollk** [jOOQ/jOOQ#13371]
### Your question:

I am testing the jOOQ trial at the moment to use the "embedded keys" feature.
Unless I am missing something, generating embedded types for the primary key of a given table causes the original "raw" columns to become `private`. Not only does that mean that the code I have implemented with the OS version so far becomes incompatible but I also wouldn't even know how to write queries that directly access those columns anymore for the case of composite keys.

Is this something that's simply not possible to do with that feature or am I using it wrong?

### Versions:

- jOOQ: 3.16.5
- Kotlin: 1.5
- Database (include vendor): Postgres 11
- OS: Arch Linux
- JDBC Driver (include name if inofficial driver): ?

**Comment by atollk** [comment]
I see. I appreciate the fast answer.

Is there an open issue for that change which can be used to track progress?

**Comment by lukaseder** [comment]
From my previous reply:

> *See also discussion here: https://github.com/jOOQ/jOOQ/issues/13036*

**Comment by lukaseder** [comment]
A better issue addressing this feature request is:

- https://github.com/jOOQ/jOOQ/issues/17177

**Comment by lukaseder** [comment]
A simpler solution that will be implemented sooner than #17177 is to mark underlying columns of embedded keys, etc. as `hidden` columns with the new jOOQ 3.20 `<hidden/>` feature:

- https://github.com/jOOQ/jOOQ/issues/13411
- https://github.com/jOOQ/jOOQ/issues/17761

The columns will be accessible via `Table.fieldsIncludingHidden().field("name")`, for example.
