### ISSUE TITLE
Using jOOQ the Generics way

### ISSUE THREAD

**Issue by eitan-rosenberg** [jOOQ/jOOQ#13385]
I am trying to create a generic method (create_2) using the generated JOOQ class.

I created the method  but I fail to find the correct parameter that is accepted 
by input parameter (TT_Table) 

Here is my code so far:

```java
package crud.generics;

import java.sql.Connection;

import org.jooq.DSLContext;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.impl.UpdatableRecordImpl;

import io.vavr.control.Try;
import myDataSources.MyDataSource;

public class Main {

	public static class MyCrud {

		private final DSLContext dslContext;

		public MyCrud(final DSLContext dslContext) {
			this.dslContext = dslContext;
		}

		public <TT_Table extends TableImpl<UpdatableRecordImpl<?>>> void create_2(final TT_Table tt_Table) {

			final UpdatableRecordImpl<?> newRecord = dslContext.newRecord(tt_Table);

			/* Some code */

			newRecord.store();

		}

	}

	public static void main(final String[] args) {
		new Main();
	}

	public Main() {

		final Connection connection = Try.of(() -> MyDataSource.my_data_base.getDataSource().getConnection()).get();

		final DSLContext dslContext = DSL.using(connection);

		final MyCrud myCrud = new MyCrud(dslContext);

		/*
		 * What will be the parameter for create_2 ????
		 * myCrud.create_2(Tables.MY_CRUD_DATA);// Fail compile The method
		 * create_2(TT_Table) in the type Main.MyCrud is not applicable for the
		 * arguments (MY_CRUD_DATA)
		 */

	}

}
```

Can someone help me.

Regards

[Main - Copy.java.txt](https://github.com/jOOQ/jOOQ/files/8381933/Main.-.Copy.java.txt)

**Comment by lukaseder** [comment]
You shouldn't capture the `Table<?>` type but its `R extends Record` type with your type variables:

```java
public <R extends UpdatableRecord<R>> void create2(Table<R> t) {
    final R newRecord = dslContext.newRecord(t);
    // ...
    newRecord.store();
}
```

I hope this helps

**Comment by eitan-rosenberg** [comment]
This helps a lot.

Many Thanks.

public <R extends UpdatableRecord<R>> void create(final Table<R> table) {

			final DefaultConverterProvider defaultConverterProvider = new DefaultConverterProvider();

			final R newRecord = dslContext.newRecord(table);

			Try.run(() -> {

				final Field<Object> field = table.field(DSL.field("FIRSTNAME"));

				final DataType<?> dataType = field.getDataType();

				final Object convertedValue = defaultConverterProvider.provide(String.class, dataType.getType())
						.from("Thank you Lukas Eder !!!");

				newRecord.setValue(field, convertedValue);

				newRecord.store();

			}).onFailure(throwable -> {
				MyLogger.log(Level.SEVERE, "{0}", throwable.getMessage());
			});

		}
		
		The result.....
		
![image](https://user-images.githubusercontent.com/48506054/160885581-0d8b26bc-06f6-4011-a13c-aed4d0d7908b.png)
