### ISSUE TITLE
jOOQ-checker should system property defaults that apply to the entire checked code

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13399]
The current implementation of `jOOQ-checker` requires an annotation per package, which can be annoying. Some users have suggested making package annotations hierarchical: https://github.com/jOOQ/jOOQ/issues/9115

This is against the spirit of what packages are in Java. While some third parties pretend packages are hierarchical, they aren't really, in vanilla Java (e.g. a package private class isn't visible in subpackages), so I'm reluctant to go down that route.

A better approach would be to annotate modules instead: https://github.com/jOOQ/jOOQ/issues/12770. Some users will continue to oppose modules, even if by now, the feature can be used quite well in many projects.

So, a third option, which is perfectly reasonable, would be to allow for configuring defaults in the absence of explicit annotations for the entirety of the checked code, directly in the maven / gradle configuration of the `jOOQ-checker` checkers.

The design of this configuration will be discussed here, later.

**Comment by lukaseder** [comment]
This needs to be done only for the `SQLDialectChecker` and `SQLDialectMatcher`. The `PlainSQLChecker` and `PlainSQLMatcher` already default to disallowing usage of plain SQL, which is a reasonable default. Since there is no way to disallow plain SQL usage in a more narrow scope (the annotation is `@Allow.PlainSQL`, and it doesn't take arguments), there's no point in specifying a global "allow plain SQL" default.

**Comment by lukaseder** [comment]
Egh. It looks like there's significant work to be done first to get our examples to work on JDK 17. So far, we're assuming JDK 8...

**Comment by remal** [comment]
@lukaseder can annotation processor options be used instead of system properties? Sorry for opening a discussion in a closed issue.

**Comment by lukaseder** [comment]
@remal I had wrestled with these things way too long yesterday even to get the system properties through to the annotation processors (supporting both checker framework and error prone, which both don't work on all JDKs). So, I prefer not to spend too much time on this again right now... A PR could have chances, though.

What's the problem of passing system properties? How would annotation processor options be passed, instead? (In terms of maven configuration, implementation, etc.)?

**Comment by remal** [comment]
@lukaseder hmm... How can I pass these system properties in Gradle, for example? Yes, I can configure forking, and, potentially, pass system properties to forked JVM process, etc... Probably, it won't be very hard. But it's really not very clear for me why not to use annotation processor args for that. These args are intended to be used exactly for this - to configure annotation processors.

I don't use Checkerframework, but use Errorprone. Errorprone Gradle plugin has a nice way of configuring checks, so it will be really convenient and consistent to configure jOOQ checks in the same way as other checks.

**Comment by lukaseder** [comment]
@remal: I don't know how it works in Gradle. Once we formally support gradle ourselves, there will be more examples / coverage of such functionality, see https://github.com/jOOQ/jOOQ/issues/12985

Can you find out on your end? There are many other issues that require attention, and this one isn't a top priority. It already took a day, which is way more than I had hoped. I hope you understand. Again, a PR would have chances of being considered in this area. I agree that other ways of passing arguments may be suitable.

To give context, nothing is well documented in this area, so, everything has to be reverse engineered, drawing conclusions from observations rather than specification. Besides, these APIs don't support several versions of JDKs very well, because they're using poorly documented, internal compiler APIs. It's very frustrating to the extent where I have wondered time and again if jOOQ should continue maintaining the `jOOQ-checker` module at all!
