### ISSUE TITLE
Replace internal usage of DatatypeConverter::parseBase64Binary by java.util.Base64

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13393]
We have a historic dependency on JAXB (the API), which may soon be removed: https://github.com/jOOQ/jOOQ/issues/13047

A part of the API is the `DatatypeConverter` class, which used to be the only way in the JDK to encode/decode base64 values. That has changed with Java 8's `java.util.Base64`. Let's replace usages in jOOQ's internals.

**Comment by baev** [comment]
@lukaseder is there any chance to have the change ported to 3.16.x ?

**Comment by lukaseder** [comment]
@baev This is mostly a cosmetic change, as far as I can tell? Why would you need a backport?

**Comment by baev** [comment]
we use 2.16 with spring boot in production for a while. And so far everything is ok except we found that if you run a query that returns `byte[]` in debug mode (`LoggerListener` is enabled) there are the following exception occurs:

```
java.lang.NoClassDefFoundError: jakarta/xml/bind/DatatypeConverter] with root cause
java.lang.NoClassDefFoundError: jakarta/xml/bind/DatatypeConverter
at org.jooq.impl.AbstractResult.format0(AbstractResult.java:1350)
at org.jooq.impl.AbstractResult.format(AbstractResult.java:197)
at org.jooq.impl.AbstractFormattable.format(AbstractFormattable.java:117)
at org.jooq.tools.LoggerListener.log(LoggerListener.java:188)
at org.jooq.tools.LoggerListener.resultEnd(LoggerListener.java:171)
at org.jooq.impl.ExecuteListeners.resultEnd(ExecuteListeners.java:252)
at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:240)
at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177)
at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88)
at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259)
at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2843)
```

**Comment by baev** [comment]
As workaround I can create a binding for that column and use some wrapper class instead of byte array. That way `toString` method will be used instead of `DatatypeConverter#printBase64Binary`

**Comment by lukaseder** [comment]
Hmm, that's curious, the dependency is declared correctly, though?

https://github.com/jOOQ/jOOQ/blob/745b01b4f2c1330a70361966fa972c1a5639a55d/jOOQ/pom.xml#L107-L110

Did you remove this dependency from your classpath, e.g. to avoid trouble of having `javax` and `jakarta` namespaces on your classpath?

I guess it could be backported, but I'm still trying to understand the root cause here, because we do have a JAXB dependency throughout jOOQ for various purposes, so you might still have `NoClassDefFoundError` elsewhere...

**Comment by lukaseder** [comment]
Backported to 3.16.7 (https://github.com/jOOQ/jOOQ/issues/13529)

**Comment by baev** [comment]
we use dependency substitution to only have jakarta dependencies in classpath (versions with javax namespace), and so far the only dependency that uses jakarta namespace is JOOQ (as far as I know). And we have separate classpath for generator so it works. 

> because we do have a JAXB dependency throughout jOOQ for various purposes, so you might still have `NoClassDefFoundError` elsewhere...

We just trying to avoid using such API's (bye-bye DefaultRecordMapper). This issue is the first one so far

**Comment by lukaseder** [comment]
I see. Well, in this particular case, the reliance on JAXB is merely incidental, since for a long time, this used to be the only base64 encoding/decoding API available in the JDK...
