### ISSUE TITLE
Configuration not used when using DSL.multiselect

### ISSUE THREAD

**Issue by pawelgosztyla** [jOOQ/jOOQ#13421]
### Expected behavior
In the following context:
```
multiset(
    [some select]
).as("fieldName").convertFrom(c -> c.into(SomeClass.class))
```
Serialization to SomeClass should use the provided configuration. For example if org.jooq.conf.Settings.setMapConstructorParameterNames(true) is used then the DefaultRecordMapper should use constructor parameters.

### Actual behavior
Serialization to SomeClass of the multiselect field does not use the configuration. New instance of DefaultConfiguration() is used instead when deserialising.

However this:
```
multiset(
    [some select]
).as("fieldName").convertFrom(c -> {
    c.attach(dslContext.configuration());
    return c.into(SomeClass.class));
});
```
works as expected

### Steps to reproduce the problem

Use settings that affect deserialization (for example mapConstructorParameterNames), then try to use convertFrom on multiselect field.
By debugging I have found that during deserialization the default context is used which comes from MultisetDataType::convert method:
```
ResultImpl<R> result = new ResultImpl<>(CTX.configuration(), row);
```

### Versions

- jOOQ: 3.16.5
- Java: java SE 17
- Database (include vendor): PostgreSQL 14.0
- OS: macOS 12.3.1
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.3.3

**Comment by pawelgosztyla** [comment]
Looks like the context is more complex and it is harder to reproduce than I thought.

**Comment by lukaseder** [comment]
Thanks a lot for your report. This looks related to https://github.com/jOOQ/jOOQ/issues/12269, the problem there was also that the user configuration wasn't used when creating results and records in *nested multisets*, the top level multiset is fine.

I'm planning to release versions 3.16.6 and 3.15.10 soon with a fix, so I'm assuming this here is a duplicate of https://github.com/jOOQ/jOOQ/issues/12269.

Would love to hear your early feedback if you could try 3.16.6-SNAPSHOT. You can build it from github, or, if you're licensed, download a snapshot build from here: https://www.jooq.org/download/versions

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/12269

**Comment by pawelgosztyla** [comment]
Yes, In my case I also have nested multisets and I do some nontrivial conversions so there is high probability that this is the same issue. When I have some time tomorrow I will check the 3.16.6-SNAPSHOT. Thanks.

**Comment by pawelgosztyla** [comment]
I checked 3.16.6-SNAPSHOT and it looks like it does not fix my issue.
As I do some complex conversions, I tried to isolate the problem and I have created new issue with better description: https://github.com/jOOQ/jOOQ/issues/13438

**Comment by lukaseder** [comment]
Thanks, @pawelgosztyla. I'll look into that issue in a bit.
