### ISSUE TITLE
Missing space in Scala code generation leads to compile errors

### ISSUE THREAD

**Issue by philippjenniunic** [jOOQ/jOOQ#13441]
### Expected behavior
`jooq-codegen-maven` should generate Scala code, that compiles, as it does with version 3.13.6:

```
/**
   * The column <code>sismedia_v4.wetter.wetter</code>.
   */
  val WETTER_ : TableField[WetterRecord, Condition] = createField(DSL.name("wetter"), org.jooq.impl.SQLDataType.INTEGER, "", new WeatherConditionConverter())
```

### Actual behavior (version: 3.14.0)
generated Scala code does not compile:

```
/**
   * The column <code>sismedia_v4.wetter.wetter</code>.
   */
  val WETTER_: TableField[WetterRecord, Condition] = createField(DSL.name("wetter"), SQLDataType.INTEGER, "", new WeatherConditionConverter())
```
```
[ERROR] /database/generated/tables/Status.scala:83: illegal start of simple pattern
[ERROR] /database/generated/tables/Status.scala:83: type application is not allowed in pattern

```

### Analysis so far
- if the field name is the same as the table name, the field has an underline as suffix (`WETTER_`)
- starting from jooq-codegen-maven 3.14.0 there is no space between the name of the variable and the colon afterward:
```
val WETTER_: TableField[WetterRecord, Condition]
   no space^
```
- these two facts (underline at the end of variable and no space after underline _ and before colon :) cause the Scala source code not to compile anymore
- the with version 3.13.6, we don't have this problem

### Steps to reproduce the problem
- config XML snippet:
```
<plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <executions>
                    <execution>
                        <id>jooq-codegen</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <scope>runtime</scope>
                        <version>${mysql.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <jdbc>
                        <driver>com.mysql.jdbc.Driver</driver>
                        <url>${URI}</url>
                        <user>[...]</user>
                        <password>[...]</password>
                    </jdbc>
                    <generator>
                        <name>org.jooq.codegen.ScalaGenerator</name>
                        <database>
                            <name>org.jooq.meta.mysql.MySQLDatabase</name>
                            <inputSchema>demoSchema</inputSchema>
                            <includes>.*</includes>
                            <forcedTypes>
                                <forcedType>
                                    <userType>weather.Condition.Condition</userType>
                                    <converter>database.converters.WeatherConditionConverter</converter>
                                    <includeExpression>sismedia_v4.wetter.wetter</includeExpression>
                                </forcedType>
                        </database>
                        <target>
                            <packageName>[...]dia.database.generated</packageName>
                        </target>
                    </generator>
                </configuration>
            </plugin>
```
- create a table that has a field with the same name as the table:
```
create table wetter
(
    id                                int(5)                                    not null,
    wetter                            int                                       null
)
```
- `mvn compile`

### Versions

- jOOQ: 3.14.0
- Java: Scala 2.13
- Database (include vendor): MySQL
- OS: Windows
- JDBC Driver (include name if inofficial driver): MySQL Driver 8.0.28

**Comment by lukaseder** [comment]
Thanks for your report. The current version is 3.16.5, can you please check with that first to see if the problem persists?

**Comment by philippjenniunic** [comment]
Alright, I will do so. And provide feedback.

However: Currently we need to stay on 3.14 because we use `spring-boot-starter-jooq`: It's newest version (2.6.6) depends on jooq 3.14.15. See https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-jooq/2.6.6

**Comment by philippjenniunic** [comment]
Generation with 3.16.5 was possible by turning setting `<generate><jooqVersionReference>false</jooqVersionReference></generate>`.

Results:
- 3.13.6: Compiles ✔
- 3.14.0 and 3.14.15: does not compile ❌
- 3.16.5: Compiles ✔

**Comment by lukaseder** [comment]
> Currently we need to stay on 3.14 because we use `spring-boot-starter-jooq`: It's newest version (2.6.6) depends on jooq 3.14.15. See https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-jooq/2.6.6

There's no reason why you can't upgrade jOOQ nonetheless by overriding the dependency. Please try it again, the bug was fixed and backported to 3.14.2: https://github.com/jOOQ/jOOQ/issues/10877

**Comment by lukaseder** [comment]
> * 3.14.0 and 3.14.15: does not compile ❌

Are you sure you were using 3.14.15? Accidentally pulling in the wrong version seems to be a very common mistake when working with Spring Boot...

**Comment by philippjenniunic** [comment]
Thanks for looking into it!

Yes, I am sure, because:
- during execution of `mvn compile` it welcomes me with `Thank you for using jOOQ 3.14.15`
- with version 3.14.15 I am not allowed to use the configuration property jooqVersionReference because it does not seem to exist yet.

I saw the issue that you marked as a duplicate. There a problem with `CLASS` was mentioned. I would say, that the same problem also occurs if the field name is the same name as the table name. But that's just blind guessing. At least it does not compile with version 3.14.15 as far as I can see.

**Comment by lukaseder** [comment]
> * during execution of `mvn compile` it welcomes me with `Thank you for using jOOQ 3.14.15`

That's the runtime version logging itself. The code generator version can still be different, they're two separate Maven artifacts.

> I saw the issue that you marked as a duplicate. There a problem with `CLASS` was mentioned. I would say, that the same problem also occurs here as well but with a different reason: if the field name has the same name as the table name (table: wetter, fieldname: wetter). But that's just blind guessing. At least it does not compile with version 3.14.15 as far as I can see.

The fix was applied to many places: 

![image](https://user-images.githubusercontent.com/734593/162765812-9318e92f-cc14-47fc-8387-ba49dff2254f.png)

See also comment here: https://github.com/jOOQ/jOOQ/issues/10877#issuecomment-725450196

**Comment by philippjenniunic** [comment]
> Well, if upgrading isn't an option, you might still try a custom generator strategy as a workaround:
> 
> * https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/
> * https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/

Thank you for providing these ideas! Meanwhile, I decided to
- use JOOQ in whatever version is suggested and provided by  https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-jooq/2.6.6 inside the project and
- 3.16.5 to execute the generation.

I guess there is no risk if the code compiles at the end (my first thought was, that it is an absolute no go to have two different versions of the "same" library in the dependencies. But this case is a bit different ;-)).
And... we also have the integration tests of our application. So that's my workaround for now.

**Comment by lukaseder** [comment]
> * use JOOQ in whatever version is suggested and provided by  https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-jooq/2.6.6 inside the project and
> * 3.16.5 to execute the generation.

I recommend you don't do that. The runtime library should match the code generation library as much as possible. E.g. the 3.16.5 code generator may choose to generate code calling 3.16.5 API, which you don't have in 3.14.x

**Comment by lukaseder** [comment]
Try a matcher strategy: https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy. It's a 1-2 minutes of setup to specify the `<tableIdentifier>` for your `WETTER` table to be something other than `WETTER_`

**Comment by philippjenniunic** [comment]
For the record:
I am now using 3.16 only (code generation and runtime). I was able to upgrade.

Thanks for the awesome support in this ticket.

**Comment by lukaseder** [comment]
Great to hear it worked out!
