### ISSUE TITLE
Make use of GitHub's release feature?

### ISSUE THREAD

**Issue by mkurz** [jOOQ/jOOQ#13459]
I was just wondering if there is a reason why you don't also publish releases within GitHub (https://github.com/jOOQ/jOOQ/releases)?
It's possible now to watch only for releases:
<kbd><img width="300" src="https://user-images.githubusercontent.com/644927/164013737-998b37b7-903f-4713-883f-93c1d3be1e57.png" /></kbd>
That might be interesting for people not subscribed to your mailing list.
Also I see a lot of projects actually now make use of that GitHub feature recently, so I was just wondering.

**Comment by lukaseder** [comment]
(I'm going to close this for now because I don't think it's going to happen. Might reopen if there's a good reason I'm overlooking)
