### ISSUE TITLE
Rendering stored procedure call on MySql misfunctions

### ISSUE THREAD

**Issue by nbrugger-tgm** [jOOQ/jOOQ#13456]
### Expected behavior
Rendering a stored procedure call that returns a ResultSet should result in a JDBC Statement that will be translated to the SQL Query 
```sql
CALL myprocedure(?,?)
```
### Actual behavior
Rendering a stored procedure call that returns a ResultSet produces the JDBC Statement 
```sql
{ ? = CALL myprocedure(?,?) }
``` 
The mysql procedure driver translates this to:
```sql
SELECT myprocedure(?,?)
```
which causes an exception since myprocedure is a procedure and not a function

### Steps to reproduce the problem
Working plain JDBC example : 
```java
var cs = con.prepareCall("{call myprocedure(?)}");
cs.setInt(1,13992);
cs.execute();//This is the method jooq uses to execute the statement
var rs = cs.getResultSet(); //works
```
Non-working plain JDBC :
```java
var cs = con.prepareCall("{? = call myprocedure(?)}");
cs.setInt(2,13992);
cs.execute(); //fails with query "select ...."
var rs = cs.getResultSet();
```
procedure
```sql
DELIMITER //
CREATE PROCEDURE `myprocedure`(in some_value int)
    READS SQL DATA
    DETERMINISTIC
BEGIN
    select
		some_value*5 as "RETURN_COLUMN",
		some_value*15 as "RETURN_COLUMN2",
		some_value*25 as "RETURN_COLUMN3";
END//
```
(autogenerated) jOOQ procedures
```java
public class SumTable extends AbstractRoutine<Result<Record>> {

    private static final Parameter<Result<Record>> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.RESULT, false, false);
    private static final Parameter<Integer> PARAMETER = Internal.createParameter("some_value", SQLDataType.INTEGER, false, false);


    /**
     * Create a new routine call instance
     */
    public SumTable() {
        super("myprocedure", <some_schema>, SQLDataType.RESULT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(PARAMETER);
    }
}
```

### Versions

- jOOQ: 3.16.3
- Java: 17
- Database (include vendor): mysql 8
- OS: Ubuntu (WSL)
- JDBC Driver (include name if inofficial driver): mysql-connector-java:8.0.27 with tomcat-jdbc:10.0.8 (hiakari doesnt work as well)

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll investigate what went wrong here, soon. Our integration tests cover a similar usage, but perhaps, there's a subtle difference in how you're doing things...

**Comment by lukaseder** [comment]
So, your `myprocedure` procedure produces an `AbstractRoutine<java.lang.Void>` type, as expected. The way to call it is:

```java
Myprocedure p = new Myprocedure();
p.setSomeValue(1);
p.execute(configuration);
System.out.println(p.getResults());
```

This prints the expected result:

```
Result set:
+-------------+--------------+--------------+
|RETURN_COLUMN|RETURN_COLUMN2|RETURN_COLUMN3|
+-------------+--------------+--------------+
|            5|            15|            25|
+-------------+--------------+--------------+

Update count: 0
```

Your generated code shows a different procedure: `SumTable`, which seems to correspond to a table valued function, which you should place in the `SELECT .. FROM` clause.

I might be able to help you further with that, but I don't see any bug here. If you think there's a bug, please provide a fully self-contained reproducer (e.g. based on the template here: https://github.com/jOOQ/jOOQ-mcve)

**Comment by lukaseder** [comment]
Why not just use an actual MySQL database when you're using vendor specific features? H2 can't emulate most of these procedural language features, so I wouldn't go down that road. You could set up a MySQL database for code generation (and integration testing!) using testcontainers: https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

**Comment by nbrugger-tgm** [comment]
Ok so i have been using jooq now for quite long and i always was using a very cumbersom workaround to do this
gradle -> liquibase -> testcontainers (mysql/postgres) -> jooqGenerator.

As far as i haver seen for this combination of technologies there was no way to do it without doing everything yourself.

So i created a tested extension for jooq generation that does this task : https://github.com/nitok-software/jooq-liquibase-extension

Is there any need from @lukaseder your side to integrate this into `jooq-meta` or should I rather polish it a little more and maintain it as a "sidecar" for this use case? I think this is a beautiful workflow and would very much improve build processes with jOOQ.

Please keep in mind that my code is heavily based on your metaclasses (3.16.3) and i left your copyright on it - if there is any change I need to do please let me know

**Comment by lukaseder** [comment]
@nbrugger-tgm For maven, there's also this:

- https://github.com/testcontainers/testcontainers-jooq-codegen-maven-plugin

But as you can see 1) it doesn't support gradle yet, and 2) it has limitations when it comes to specific liquibase feature support. Which seems obvious, combining the tools yourself is *always* more powerful than depending on a third party integrator.

Your own library will have your own limitations, which aren't important to you, but as soon as someone else uses it, they might run into them.

For jOOQ, I don't think it makes sense to maintain such third party solutions. jOOQ isn't Spring Boot, or any other integrator platform.
