### ISSUE TITLE
New configuration to generate implicit join definitions ALWAYS from foreign key name

### ISSUE THREAD

**Issue by morki** [jOOQ/jOOQ#13457]
### Use case:

We are using meaningful names for our foreign key constraints to easily navigate using implicit join feature.
Now, when there is only one foreign key relation to some table, the implicit join reference is named after table instead of foreign key. 

### Possible solution you'd like to see:

Create some code generator configuration to always use foreign key name instead (the same as when there are 2 and more relations).

### Possible workarounds:

Don't use this feature or use it inconsistently.

### Versions:

- jOOQ: 3.16
- Java: 11
- Database (include vendor): PostgreSQL
- OS: Linux
- JDBC Driver (include name if inofficial driver): official

**Comment by morki** [comment]
Take a following example:

```sql
create table person (
  id   int  not null generated always as identity,
  name text not null,

  primary key (id)
);

create table book (
  id          int  not null generated always as identity,
  name        text not null,
  author_id   int  not null,
  reviewer_id int  not null,

  primary key (id),
  constraint author foreign key (author_id) references person (id),
  constraint reviewer foreign key (reviewer_id) references person (id)
);

create table gallery (
  id        int  not null generated always as identity,
  name      text not null,
  author_id int  not null,

  primary key (id),
  constraint author foreign key (author_id) references person (id)
);
```

What the usage looks like:

```kotlin
BOOK.author().NAME;
BOOK.reviewer().NAME;
GALLERY.person().NAME; // inconsistent and not descriptive
```

What am I requesting:

```kotlin
BOOK.author().NAME;
BOOK.reviewer().NAME;
GALLERY.author().NAME; // consistent and descriptive
```

**Comment by morki** [comment]
The same can apply to new "implicit multiset" in https://github.com/jOOQ/jOOQ/issues/13069

**Comment by lukaseder** [comment]
Thanks a lot for your report. The current behaviour is implemented by the `DefaultGeneratorStrategy`. You can easily override it by implementing your own generator strategy:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/

I'll think about whether the default implementation should really be configurable, or changed, or something else.

**Comment by lukaseder** [comment]
OK, so the most sensible thing to do here is to add a flag that influences the `DefaultGeneratorStrategy` only, and has no effect on the code generation itself, which is agnostic of these names. For the record, this is how the name is created in `JavaGenerator`:

```java
String keyMethodName = out.ref(getStrategy().getJavaMethodName(foreignKey));
```

And this is the current implementation:

```java
    @Override
    public String getJavaMethodName(Definition definition, Mode mode) {
        // [#7148] If table A references table B only once, then B is the ideal name
        //         for the implicit JOIN path. Otherwise, fall back to the foreign key name
        if (definition instanceof ForeignKeyDefinition) {
            ForeignKeyDefinition fk = (ForeignKeyDefinition) definition;
            TableDefinition referenced = fk.getReferencedTable();

            if (fk.getKeyTable().getForeignKeys(referenced).size() == 1)
                return getJavaMethodName(referenced, mode);
        }

        return getJavaClassName0LC(definition, Mode.DEFAULT);
    }
```

I still think it's a reasonable default for simple schemas, and for the out of the box experience. My "goto dogfooding example" is the [Sakila database](https://www.jooq.org/sakila), where I can navigate the schema like this: `CUSTOMER.address().city().country()`.

By "out of the box", I mean, specifically:

- A lot of people don't even name their constraints (!). The main reason to name constraints (outside of jOOQ's implicit join feature usage), is to be able to drop constraints more easily again.
- If constraints are named, they tend to be named in a technical way, not optimised for implicit joins, maybe even using Hungarian notation, such as `fk_something` or `something_key`, which would be awful as implicit join names

In both of the above cases, it would be ideal to use a generator strategy instead.

But anyway, I get your point. *IF* you name your constraints specifically for this feature, then you obviously want to have consistent behaviour in the `DefaultGeneratorStrategy`, and that behaviour is to always use the constraint names, not the table names.

**Comment by lukaseder** [comment]
The flag is called `<implicitJoinPathsUseTableNameForUnambiguousFKs/>` and it defaults to `true` (the status quo). You will be able to achieve the desired behaviour using:

```xml
<implicitJoinPathsUseTableNameForUnambiguousFKs>false</implicitJoinPathsUseTableNameForUnambiguousFKs>
```

**Comment by morki** [comment]
Thank you very much @lukaseder! Another step to paid licence for me :)

**Comment by lukaseder** [comment]
Are you suggesting, this could be a commercial only feature? 😅

**Comment by morki** [comment]
For me, it can be, because this is practicaly very useful with #13069 which is commercial only too :+1:

**Comment by morki** [comment]
Together it is ORM of new generation :)

**Comment by lukaseder** [comment]
Great to hear! Do you have any feedback about https://github.com/jOOQ/jOOQ/issues/13069 in particular (ideally directly on that issue, or chime in here: https://github.com/jOOQ/jOOQ/issues/13063). The specific design of this feature might still be a bit of a moving target, so you can still very much influence it with your use-cases.
