### ISSUE TITLE
dependency scope setting issues

### ISSUE THREAD

**Issue by DataProvided** [jOOQ/jOOQ#13450]
Hi,

We are developing a tool to check whether the dependencies' scopes in maven are set rightly and reasonably. 

Our tools have found some issues in your project about scope setting in maven' pom.xml file.

- in `jOOQ-scala_2.13\pom.xml`, `org.scala-lang:scala-library` scope should be `compile`  instead of `provided`.
- in `jOOQ\pom.xml`, `org.postgresql:postgresql` scope should be `compile`  instead of `provided`.
- in `jOOQ\pom.xml`, `org.slf4j:slf4j-api` scope should be `compile`  instead of `provided`.

Please help us confirm whether the above reports are right and explain why it should set like these.

Thanks a lot.

**Comment by lukaseder** [comment]
> Please help us confirm whether the above reports are right and explain why it should set like these.

I'll be more than happy to do so. My hourly rate is EUR 300. Is that something you can work with?
