### ISSUE TITLE
InsertOnDuplicateStep with conditional

### ISSUE THREAD

**Issue by VigneshTK91** [jOOQ/jOOQ#13507]
### Use case:
we have use-case that is pretty common i want to understand how can we efficiently solve this problem using JOOQ.

In DB Table we have some column like id, updated_at and status. we have been using batch with insertOnDuplicateStep
which was working earlier smooth for us. now we have a scenario that whenever the status in table row is 'active' we have to update the updated_at field whereas for 'inactive' or 'other status' we don't want to update the updated_at field but remaining fields we want to update.

how can i achieve this scenario using insertOnDuplicateStep with condition.

Please describe the use-case you have. This will better help us understand the context in which you're looking for a new feature.

### Possible solution you'd like to see:
Query all the record from table do the separation in business logic.

Please describe a possible solution you'd like to see in jOOQ, ideally with example code.

### Possible workarounds:

Please describe the possible workarounds you've implemented to work around the lacking functionality.

### Versions:

jOOQ: 3.13.4
Java: java 11
Database (include vendor): Mysql (Amazon RDS)
OS: mac
JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your message. You can append a synthetic `WHERE` clause to your `INSERT .. ON DUPLICATE KEY UPDATE` statement. e.G.

```java
LocalDateTime ts = LocalDateTime.now();

ctx.insertInto(T)
   .columns(T.ID, T.UPDATED_AT, T.STATUS)
   .values(1, ts, status)
   .onDuplicateKeyUpdate()
   .set(T.UPDATED_AT, ts)
   .where(T.STATUS.notIn("inactive", "other status"))
   .execute();
```

The clause is synthetic because it's not natively supported by MySQL (as it is in PostgreSQL, for example). But jOOQ can easily emulate it as such:

```sql
INSERT INTO t (id, updated_at, status)
VALUES (1, :ts, :status)
ON DUPLICATE KEY UPDATE SET
  updated_at = CASE
    WHEN status NOT IN ('inactive', 'other status') THEN :ts
    ELSE updated_at
  END
```

The update count and locking semantics might be a bit different from PostgreSQL, as the row is probably "touched", but logically, it's the same thing.

**Comment by lukaseder** [comment]
It seems the `InsertOnConflictWhereStep::where` clause lacks MySQL support: https://github.com/jOOQ/jOOQ/issues/13508. That's just a documentation flaw for you, though. You should still be able to use the clause. In case it doesn't work, as always, please try upgrading to the latest jOOQ version as we constantly improve emulation support for various dialects.

**Comment by VigneshTK91** [comment]
@lukaseder : My scenarion is when the status is 'inactive' only update_at field i don't want update remaining fields it should get update.

with the example you have given it will not update any field when the status is 'inactive'.

can you help me with the adding criteria only for one set field is it possible...?

**Comment by VigneshTK91** [comment]
@lukaseder when i add a where to any set it is applicable to every set is there anyway i can restrict to only one set.

please the generated query.

```
  `ad`.`data_series_path` = case
    when `ad`.`status` not in (
      'inactive', 'archieved'
    ) then values(`ad`.`data_series_path`)
    else `ad`.`data_series_path`
  end, 
  `ad`.`billing_entity_id` = case
    when `ad`.`status` not in (
      'inactive', 'archieved'
    ) then values(`ad`.`billing_entity_id`)
    else `ad`.`billing_entity_id`
  end, 
  `ad`.`updated_at` = case
    when `ad`.`status` not in (
      'inactive', 'archieved'
    ) then values(`ad`.`updated_at`)
    else `ad`.`updated_at`
  end
```

**Comment by lukaseder** [comment]
My point is, *instead of* adding `WHERE`, add the necessary `CASE` expressions yourself.

**Comment by VigneshTK91** [comment]
Thanks for the information, so you are saying that in Jooq Query add this case.
if you are share me sample example or code sample adding a case in Jooq query that could really helpful.

**Comment by lukaseder** [comment]
As I said. Don't use `where()` but use the `case_()` expression explicitly:

```java
ctx.insertInto(T)
   .columns(T.ID, T.UPDATED_AT, T.STATUS)
   .values(1, ts, status)
   .onDuplicateKeyUpdate()
   .set(T.UPDATED_AT, when(T.STATUS.notIn("inactive", "other status"), ts).else_(T.UPDATED_AT))
   .execute();
```

**Comment by VigneshTK91** [comment]
Thanks a lot, it helped 👍
