### ISSUE TITLE
Fetch single relation in single query

### ISSUE THREAD

**Issue by rauldeheer** [jOOQ/jOOQ#13518]
### Question:

Hi.

First of all, here is a [Stackoverflow link](https://stackoverflow.com/questions/72109324/jooq-3-16-fetch-one-to-one) to my question.

I basically want to fetch a record with a relation, but I cannot use multiset because I only want to retrieve one single item, so I do not want a `List<T>`.

The DTO I want to populate looks like this:

```kotlin
data class(
    val id: UUID
    val product: ProductDTO 
) 
```

How do I achieve this?

### Versions:

- jOOQ: 3.16
- Java: 17
- Database: PostgreSQL 
- OS: macOS 12.1

**Comment by lukaseder** [comment]
Thanks, the SO question already has an answer.
