### ISSUE TITLE
Can a database field have multiple Converter ?

### ISSUE THREAD

**Issue by Zhangjiayiaa** [jOOQ/jOOQ#13521]
![image](https://user-images.githubusercontent.com/104960969/166862439-9df642e7-3b97-419a-95c2-4bdb159c0ec7.png)

**Comment by lukaseder** [comment]
Thanks for your message. The default behaviour of the `<converter/>` configuration is to try to match a qualified or unqualified Java identifier, and then assume it's a converter type with a default constructor, such as in your example.

But if your `<converter/>` configuration doesn't match a valid Java identifier, the code generator will just inline whatever you put there, which can be useful as "inline converters", for example:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-inline-converter/

The example from the above manual section:

```xml
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.16.5.xsd">
  <generator>
    <database>
      <forcedTypes>
        <forcedType>

          <!-- Specify the Java type of your custom type. This corresponds to the Converter's <U> type. -->
          <userType>java.time.Year</userType>
    
          <!-- Associate that custom type with your inline converter. -->
          <converter>org.jooq.Converter.ofNullable(
            Integer.class, Year.class, 
            Year::of, Year::getValue
          )</converter>

          <!-- A Java regex matching fully-qualified columns, attributes, parameters. Use the pipe to separate several expressions. -->
          <includeExpression>.*\.YEAR.*</includeExpression>
        </forcedType>
      </forcedTypes>
    </database>
  </generator>
</configuration>
```

In that sense, you can pass any type of valid Java expression that produces a valid `Converter<String, Map<?, ?>>`, including chained converters. You can chain converters manually, or using `org.jooq.Converters.of(...)`

I hope this helps

**Comment by lukaseder** [comment]
We still support Java 8 in newer jOOQ versions, see the full list of distributions per JDK version here:
https://www.jooq.org/download/versions

The API you're listing is just convenience API though. You can achieve the same things by creating data types using `DataType::asConvertedDataType`, and then `Field::coerce`.

**Comment by lukaseder** [comment]
This is by far not the only thing you're missing out on, if you stick to Java 8 and/or jOOQ 3.14! Check out jOOQ 3.15's `MULTISET` operator:
https://blog.jooq.org/jooq-3-15s-new-multiset-operator-will-change-how-you-think-about-sql/

I strongly recommend upgrading either the JDK or jOOQ, or both.

**Comment by Zhangjiayiaa** [comment]
thank you very much !
