### ISSUE TITLE
Avoid rendering PostgreSQL native cast operator :: which cannot be used in Hibernate native queries

### ISSUE THREAD

**Issue by rkarp** [jOOQ/jOOQ#13534]
### Expected behavior

The result of `getSQL()` should always be usable for native queries, as described here: https://www.jooq.org/doc/latest/manual/sql-execution/alternative-execution-models/using-jooq-with-jpa/using-jooq-with-jpa-entities/

### Actual behavior

If the result of `getSQL()` contains `::` casts, Hibernate `createNativeQuery()` will convert those to a single `:`, resulting in syntax errors from the DB.

See also this blog post: https://vladmihalcea.com/how-do-solve-the-postgresql-cast-operator-issue-with-jpa-and-hibernate/

Maybe the solution would be to only generate `cast()` expressions?

### Steps to reproduce the problem

- Create an enum in the DB
- Run the code generator
- Use something like `.where(MY_TABLE.MY_ENUM_VALUE.eq(inline(MyEnum.enum_variant)))`
- Try to use Hibernate `createNativeQuery()` as described above

### Versions

- jOOQ: 3.16.6
- Java: 11
- Database (include vendor): Postgres 13.4
- OS: Linux
- JDBC Driver (include name if inofficial driver): 42.3.1

**Comment by rkarp** [comment]
Hibernate supports `:` for named parameters in native queries, see: https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html#sql-query-parameters

The conversion `::` -> `:` seems to be intentional, see this issue: https://hibernate.atlassian.net/browse/HHH-1237. I don't know if Hibernate would change this again now, since it would break many existing native queries.

I tested this in more detail, and `::` or `\:\:` do not get touched inside SQL inline strings, so there is definitely some parsing happening, as described here: https://stackoverflow.com/a/33500944. However, that means that simply escaping `:` in the whole string would not be correct. I wrote this code to do the replacement only outside of SQL strings (`'...'`):

```java
        String sqlString = query.getSQL();
        // Double colons outside of SQL strings
        String replacedSqlString = Pattern.compile("'[^']*'|(:)|[^':]*", Pattern.DOTALL)
            .matcher(sqlString)
            .results()
            .map(matchResult -> {
                if (matchResult.group(1) == null) {
                    return matchResult.group();
                } else {
                    return "::";
                }
            })
            .collect(Collectors.joining());
```
It seems to work, but I don't know if there are really no edge cases where it breaks down.

MySQL is also affected, so this is a Hibernate specific issue: https://stackoverflow.com/questions/4169582/escaping-the-colon-character-in-jpa-queries.

I'm not sure how to solve this properly for all jOOQ users, but I guess one way might be to add another method like `getSQLForHibernate()` that would return `::::` instead of `::` in Postgres casts, or more generally double `:` in relevant positions.

As for my use case: Yes, I need to fetch a list of entities, and the code that I converted to jOOQ was just a string-based native query that fetches them (ironically containing `::::` for one cast, which would have been broken if hibernate changed this behavior). The query is quite complex, so using jOOQ is very nice there.

**Comment by lukaseder** [comment]
> Hibernate supports : for named parameters in native queries, see

Yeah, so does jOOQ in plain SQL templates, but our parser is a bit smarter about these things. It can look ahead and behind to avoid such easy to resolve ambiguities. Though, there are ambiguities with other usages of `:` in PostgreSQL, e.g. in arrays, when using the `[a:b]` syntax. The workaround there is just to add a space in between: `[a : b]`

> The conversion `::` -> `:` seems to be intentional, see this issue: https://hibernate.atlassian.net/browse/HHH-1237. I don't know if Hibernate would change this again now, since it would break many existing native queries.

Oh boy. 😅 They were hacking around at the time, huh.

> I wrote this code to do the replacement only outside of SQL strings (`'...'`):

That's a good defensive measure. You could also try doing that outside of comments (`--.*?\n`, `/\*.*?\*/`) and outside of quoted identifiers (`"[^"]*"`), though note that both the string and identifier pattern doesn't take into account the escaping of apostrophes and double quotes, e.g. this is a valid string literal, containing a single apostrophe: `''''`

> MySQL is also affected, so this is a Hibernate specific issue: https://stackoverflow.com/questions/4169582/escaping-the-colon-character-in-jpa-queries.

Wow, the token after `:` is `=`, which isn't even a valid identifier part. One would have hoped that the named parameter parser in Hibernate's native query execution would be so smart as to check for those things.

That does seem like a significant bug...

> I'm not sure how to solve this properly for all jOOQ users, but I guess one way might be to add another method like `getSQLForHibernate()`

It's a bug in Hibernate. We don't want to hard code this bug's behaviour in jOOQ. Imagine if we did, someone would ask for `getSQLForEclipseLink()` and `getSQLForOpenJPA()` and `getSQLForMyBatis()` and what not.

The `getSQL()` method produces valid SQL for the target database product. We use a lot of vendor specific syntax. If we started patching that SQL for all the flaws of all the other ORMs out there, we'd never get back to meaningful work, plus, it would be very cumbersome to ensure quality by testing all of this. For example, recently, jOOQ has added support for new data types in PostgreSQL. PostgreSQL uses tons of very weird operator names, just look for `SELECT * FROM pg_catalog.pg_operator`. Things like `?@>` or `~<=~`. What are the chances that some of them cause clever ORMs to break again? We can't possibly handle all of these things.

`::` has been a valid cast operator in PostgreSQL and Informix for ages. I don't see why jOOQ should avoid them, not in `getSQL()`, and not in a poorly tested, weird `getSQLForHibernate()`.

In the short term, I think your regex must have to suffice.

**Comment by lukaseder** [comment]
I'll re-evaluate the possibility of generating only `CAST(x AS y)` instead of `x::y` next week. Perhaps I've overestimated the risks and efforts.

**Comment by lukaseder** [comment]
A new `NoPGCastListener` like the below could be introduced to prevent regressions of this issue:

```java
public class NoPGCastListener implements ExecuteListener {

    @Override
    public void renderEnd(ExecuteContext ctx) {
        assertFalse(ctx.sql(), ctx.sql().contains("::"));
    }
}
```

It currently produces 102 integration tests failures, showing how ubiquitous this cast currently is in jOOQ, at least in terms of how often it manifests in PostgreSQL specific integration tests.

**Comment by lukaseder** [comment]
OK, so with quite a few changes, some of them hinting at the regression risk, I've managed to run all integration tests with none of them failing with the above `NoPGCastListener`.

The regression risk for a backport is too high, I don't want to risk this. But the improvement can ship with jOOQ 3.17.

**Comment by lukaseder** [comment]
Another fun syntax Hibernate can't handle: T-SQL's `geometry::STGeomFromText(...)`

**Comment by lukaseder** [comment]
This seems to have introduced a regression: https://github.com/jOOQ/jOOQ/issues/13723
