### ISSUE TITLE
Wrong documentation for <printMarginForBlockComment/>

### ISSUE THREAD

**Issue by jmterrettaz** [jOOQ/jOOQ#13536]
Hi 
I guess there is a mistake in the documentation: when I put as documented 
      `<printMarginForJavadoc>120</printMarginForJavadoc>`
in my pom.xml, I get the error: 
`Cannot find 'printMarginForJavadoc' in class org.jooq.meta.jaxb.Generate`

I think that the correct element is:
      `<printMarginForBlockComment>120</printMarginForBlockComment`

I found it in https://javadoc.io/doc/org.jooq/jooq-meta/latest/org.jooq.meta/org/jooq/meta/jaxb/Generate.html#printMarginForBlockComment

Best regards,
Jean-Marc
SBB IT

----
See: https://www.jooq.org/doc/3.17/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-whitespace/

**Comment by lukaseder** [comment]
Thanks a lot for your report. That's a documentation bug, indeed. Will fix right away.
