### ISSUE TITLE
Feedback about manual section "codegen-ddl"

### ISSUE THREAD

**Issue by aru-trackunit** [jOOQ/jOOQ#13556]
Hi,

Dependency from the very bottom of the documentation

```
<groupId>org.jooq.trial</groupId>
<artifactId>jooq-meta-extensions</artifactId>
<version>3.12.4</version>
```

should be replaced with the one below
```
<groupId>org.jooq</groupId>
<artifactId>jooq-meta-extensions</artifactId>
<version>3.12.4</version>
```

----
See: https://www.jooq.org/doc/3.12/manual/code-generation/codegen-ddl/

**Comment by lukaseder** [comment]
You have omitted the comments that are there in the documentation:

```xml
<dependency>
  <!-- Use org.jooq            for the Open Source Edition
           org.jooq.pro        for commercial editions, 
           org.jooq.pro-java-8 for commercial editions with Java 8 support,
           org.jooq.pro-java-6 for commercial editions with Java 6 support,
           org.jooq.trial      for the free trial edition 
                 
       Note: Only the Open Source Edition is hosted on Maven Central. 
             Import the others manually from your distribution -->
  <groupId>org.jooq.trial</groupId>
  <artifactId>jooq-meta-extensions</artifactId>
  <version>3.12.4</version>
</dependency>
```

So, this seems to sufficiently explain what needs to be done?

**Comment by lukaseder** [comment]
Hmm, I've just noticed now that the default `groupId` is inconsistent across the manual. Some sections default to the `org.jooq.trial` groupId, others to the `org.jooq` one:

<img width="223" alt="image" src="https://user-images.githubusercontent.com/734593/168288733-11afdbaf-d2af-4405-9232-8378b66ecb2f.png">

I guess we could consistently use the `org.jooq` one everywhere...

**Comment by lukaseder** [comment]
Fixed. The changes will be deployed with the next manual build, soon.

Thanks again for your report.
