### ISSUE TITLE
Update R2DBC dependency to 1.0.0.RELEASE

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13565]
Upgrades:

- [x] `io.r2dbc:r2dbc-spi:1.0.0.RELEASE`
- [x] `io.r2dbc:r2dbc-h2:1.0.0.RELEASE`
- [x] `org.mariadb:r2dbc-mariadb:1.1.3`
- [x] `io.r2dbc:r2dbc-mssql:1.0.0.RELEASE`
- [x] `com.oracle.database.r2dbc:oracle-r2dbc:1.1.0`
- [x] `org.postgresql:r2dbc-postgresql:1.0.0.RELEASE`

Incompatible SPI changes:

- [x] `Result::getRowsUpdated` now returns `Publisher<Long>`, not `Publisher<Integer>`

Problems resolved by this upgrade:

- https://github.com/r2dbc/r2dbc-h2/issues/226

**Comment by lukaseder** [comment]
Attempt this upgrade again, it seems all drivers are now ready:
https://twitter.com/mp911de/status/1590984400061497351

**Comment by bmorris591** [comment]
MariaDB released their R2DBC 1.0.0 compatible driver late last year - https://github.com/mariadb-corporation/mariadb-connector-r2dbc/releases/tag/1.1.3

**Comment by lukaseder** [comment]
Thanks, @bmorris591

**Comment by lukaseder** [comment]
No regressions could be observed in the integration tests. Instead, a few issues were fixed by the drivers. The only hiccup is the incompatible change of `Result::getRowsUpdated`, which we have to translate from `Long` to `Integer` as the jOOQ API only knows `Integer` update counts, historically.

**Comment by lukaseder** [comment]
Ah, nope. The unofficial `dev.miku:r2dbc-mysql:0.8.2.RELEASE` driver doesn't support `1.0.0.RELEASE` yet, so we must continue to support the old `Result::getRowsUpdated` method signature, via rawtypes and runtime casts
