### ISSUE TITLE
Add QOM.Aliasable, a query object model type implemented by all aliasable objects

### ISSUE THREAD

**Issue by makkarpov** [jOOQ/jOOQ#13596]
### Use case:

When building libraries that operate on user-supplied schema it often could be useful to determine whether `Table[T]` instance is aliased and if it is --- what base table is and what alias it has.

### Possible solution you'd like to see:

Expose public methods e.g. `boolean isAliased()`, `Table<R> aliasedTable()`, `Name alias()`. This information is already stored in TableImpl, but is not public.

### Possible workarounds:

Reflection. But this is getting more and more difficult as JDK updates.

### Versions:

- jOOQ: 3.16.6
- Others: not relevant

**Comment by lukaseder** [comment]
Thanks for your message. You can start using the new (experimental!) jOOQ 3.16.0 query object model (`QOM`) API:
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/QOM.TableAlias.html

Just check if your table is a `QOM.TableAlias`:

```java
if (table instanceof QOM.TableAlias<?> alias) {
    println("%s as %s".formatted(alias.$table(), alias.$alias());
} 
```

**Comment by makkarpov** [comment]
This is exactly what I tried at it didn't work on generated tables:

```scala
println(Tables.PG_CLASS.as("meow").isInstanceOf[QOM.TableAlias[_]])
// => false
```

**Comment by lukaseder** [comment]
Good point, that currently can't be accessed via the same API. I'll think about how this might be designed.

**Comment by lukaseder** [comment]
This is trickier than I had first thought. The following `QueryPart` implementations have an override of `AbstractTable::as`:

<img width="463" alt="image" src="https://user-images.githubusercontent.com/734593/171628131-774a85ec-50f1-45d3-9186-ca83f54a1f64.png">

Some of these still return a `TableAlias`, but others also return a specialisation. Ideally, the specialisations.

### Generated tables

The main reason why generated tables covariantly override `TableImpl::as` is for type safe access to columns from the alias, e.g.:

```scala
val c: PgClass = PG_CLASS.as("c")
select(c.OID)
```

So, the most canonical solution at the time was to simply override `PgClass::as` on every generated class to return another instance of `PgClass` with the alias property.

### Possible solutions

**1. Let `TableImpl <: TableAlias`**

So, one trivial solution here would be to let `TableImpl <: TableAlias`, and change the contract on `TableAlias::$alias` to be `@Nullable`. I don't like that very much. I would want a `QOM.TableAlias` to *guarantee* it is an alias, not just the table reference itself.

**2. Generate subclasses of generated tables for aliasing**

A bit cleaner, but producing many more classes would be a solution that generates 2 subclasses for each generated `TableImpl`:

- `PgClass <: TableImpl`: The ordinary table reference
- `PgClass.PgClassAlias <: PgClass & TableAlias`: The aliased table reference

The same would be done with all internal specialisations.

This approach has a slight usability drawback, e.g. when people use type inference like this:

```scala
var c = PG_CLASS.as("c")
c = PG_CLASS // Cannot be assigned to variable of type PgClass.PgClassAlias
```

Probably not that big of an issue in Scala, where mutable variables aren't too popular, but might happen in Java. This would thus be an incompatible change.

**3. Duplicate generated classes**

This isn't really viable as it would make the table reference and the alias incompatible in client code, backwards incompatibly if users are assigning one to the other, but worth mentioning here, so this wouldn't work anymore:

```scala
var c = PG_CLASS
c = c.as("c")
```

There are other problems that arise from duplication.

### Conclusion

I can't make a decision yet, about this. The new `QOM` API is still experimental, and a moving target, so other similar issues might arise. After studying those, I might make a more informed decision.

The immediate workaround for you would be to check if you have a `TableImpl` and then check if `org.jooq.impl.TableImpl.alias == null`. You can do that by placing some custom logic into the `org.jooq.impl` package. Reflection works too, of course. Sure, the JDK starts forbidding things like that, but the `QOM` API is experimental, too, so there's not a perfect option for you right now.

**Comment by lukaseder** [comment]
Another option, which I hadn't thought of yet, is to add a new `QOM.Aliasable` API, which is going to be implemented by all aliasable types, both `Table` and `Field` subtypes. It will look like this:

```java
public interface Aliasable<Q extends QueryPart> {
    @NotNull Q $aliased();
    @Nullable Name $alias();
}
```

If `$alias() == null` then `$aliased() == this`, otherwise, it will give access to the base type.

**Comment by lukaseder** [comment]
The new type now almost makes `TableAlias` and `FieldAlias` obsolete, with the exception of: `TableAlias` and `FieldAlias` can make a `@NotNull` guarantee on `$alias()`
