### ISSUE TITLE
Add JSONtoJacksonConverter, JSONBtoJacksonConverter, XMLtoJAXBConverter implementations

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13605]
Users will probably re-implement the same kinds of `Converter` all the time to implement data binding from and to `JSON`, `JSONB`, and `XML` columns using any library of:

- Jackson
- ~Gson~
- JAXB

We could offer such converters out of the box in new modules:

- `jooq-jackson-extensions`
- ~`jooq-gson-extensions`~
- ~`jooq-jaxb-extensions`~

Remarks:

- There's a possibility of moving some of the internal Jackson/Gson reflective logic from the `DefaultConverterProvider` to those extensions, and load the logic using service loaders, etc?
- The `jooq-jaxb-extensions` module is not yet necessary, as we still have a dependency on the JAXB API in the jOOQ library, so we might as well still use that for the time being.
- Additional code generation convenience might be added, optionally: https://github.com/jOOQ/jOOQ/issues/13607

**Comment by lukaseder** [comment]
I mean, it's not like it's rocket science to implement such a converter manually. But being able to just write a bit of configuration is certainly nice.

**Comment by lukaseder** [comment]
I'm going to run a quick poll about the popularity of various JSON binding libraries. I have a feeling that I'm overestimating Gson's popularity, so I'm tempted to postpone a `jooq-gson-extensions` module:
https://twitter.com/lukaseder/status/1529822203809656832

**Comment by lukaseder** [comment]
Let's not forget to add this module with the commercial distributions: https://github.com/jOOQ/jOOQ/issues/13608

**Comment by lukaseder** [comment]
https://github.com/jOOQ/jOOQ/issues/13607 has been implemented as well (code generation convenience).

I'll make sure this also works with the most common Jackson extensions, e.g.:

- For kotlin
- For `java.time` types (which I think aren't supported out of the box, still?)

**Comment by lukaseder** [comment]
It seems that this is a sensible way to initialise the `ObjectMapper`:

```java
        mapper = JsonMapper
            .builder()
            .findAndAddModules()
            .build();
```

That way, users can add their own modules to the classpath, and Jackson will auto-discover them. I'll do this as well for the `DefaultConverterProvider`, which works with Jackson reflectively

**Comment by ayush-finix** [comment]
Do you think having the Configuration or something accept an ObjectMapper (or, ideally multiple) would enable clients to do whatever they want (things like naming conventions (snake/camel), extension modules, etc. We have some unfortunate cases where we use jsonb columns, but the values are all snake case or the values are all camel case. Without being able to configure the objectmapper, it would still require a custom converter (not that that's really very hard).

**Comment by lukaseder** [comment]
Thanks for your comments, @ayush-finix. It's a frequently re-occurring request to allow for a `Converter` to access some configured objects, see e.g. https://github.com/jOOQ/jOOQ/issues/13801

You can always just do that yourself. This particular converter here is just a convenience out of the box feature without the goal of overengineering the defaults. It'll not be enough in many use-cases, so you probably better roll your own.

If you think that `JSONtoJacksonConverter` could profit from additional functionality, please do create a new issue. This issue here is closed and not being tracked, so if there's anything to be done, it won't be on any roadmap, currently.

**Comment by elwaxoro** [comment]
Apologies if I missed this, but how should the converter be used? This is a partial gradle config, along with a compiler error from a generated table file. Column named "data" is jsonb type.

gradle config:
```
generator.apply {
                  name = "org.jooq.codegen.DefaultGenerator"
                  database.apply {
...
                      forcedTypes.add(
                          org.jooq.meta.jaxb.ForcedType()
                              .withUserType("com.fasterxml.jackson.databind.JsonNode")
                              .withBinding("org.jooq.jackson.extensions.converters.JSONBtoJacksonConverter")
                              .withIncludeExpression(".*")
                              .withIncludeTypes("JSONB?")
                      )
```

compiler output:
```
  required: Class
  found:    no arguments
  reason: actual and formal argument lists differ in length
  where U is a type-variable:
    U extends Object declared in class JSONBtoJacksonConverter
/blah-blah-path/db/jooq/generated/tables/Foo.java:69: error: constructor JSONBtoJacksonConverter in class JSONBtoJacksonConverter<U> cannot be applied to given types;
    public final TableField<FooRecord, JsonNode> DATA = createField(DSL.name("data"), SQLDataType.JSONB.nullable(false), this, "", new JSONBtoJacksonConverter());
```

**Comment by lukaseder** [comment]
Sorry for the delay, @elwaxoro. For faster replies (in the future), a new issue (including support requests) probably works better, as it will appear in open issue reports.

Please have a look at the following section to see how to configure the converter:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-jackson-converter/
