### ISSUE TITLE
Maven repository for commercial editions

### ISSUE THREAD

**Issue by morki** [jOOQ/jOOQ#13603]
### Use case:

I just purchased jOOQ Express edition to use new multiset convenience and use snapshot builds for testing. I thought that I can use my licence key as an authentication to some Maven repository that can be proxied in Artifactory, Nexus or other Maven repository. 
Without this option I need to mannualy download every version, place somehow to Maven repository, no automation involved.

Maybe I am missing something, maybe it is all easy, but for me, this is drastically worse developer experience than using OSS edition.

### Possible solution you'd like to see:

It would be cool to expose some sort of Maven repository authenticatible with the licence key.

### Possible workarounds:

Manually upload the downloaded ZIP file to some Maven repository (now I even don't know how to do properly).

### Versions:

- jOOQ: -
- Java:  -
- Database (include vendor): -
- OS: -
- JDBC Driver (include name if inofficial driver): -

**Comment by lukaseder** [comment]
Yes, that would be great, see https://github.com/jOOQ/jOOQ/issues/9906

**Comment by lukaseder** [comment]
https://github.com/jOOQ/jOOQ/issues/9906 has been implemented and a Maven repository for commercial artifacts is now available at https://repo.jooq.org
