### ISSUE TITLE
org.jetbrains.annotations dependency should be requires transitive

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13619]
Our `module-info` currently lists:

```java
requires static org.jetbrains.annotations;
```

But it should be:

```java
requires static transitive org.jetbrains.annotations;
```

So clients can automatically use the annotations, which are part of our API after all, not just used internally.

**Comment by lukaseder** [comment]
I'm not sure what impact this change has on client code in terms of backwards compatibility, as this is kinda breaking new grounds for jOOQ. I guess there could be edge cases where users:

- Didn't import the dependency yet, and now suddenly have it, thus enabling some null checks they didn't have before (including the usual false positives)
- Imported the dependency themselves, and now suddenly get a conflict because jOOQ exports it to them

Hence, I won't backport this change.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.17.0

**Comment by lukaseder** [comment]
This seems not to work. I'm not sure if I'm misunderstanding how `static transitive` work together, or if this is somehow a maven related problem. Better just revert this change for now. I don't have the nerve to investigate this.

**Comment by hho** [comment]
@lukaseder I think it should also be a required (and transitive) dependency in Maven (it's currently set to "provided" and "optional" instead)? I just tried to upgrade from 3.18.7 to 3.19.1 and my build broke because I didn't have Jetbrains annotations on the classpath.

**Comment by lukaseder** [comment]
It's not a required dependency. Why would it be? You can create a new issue with details about your broken build.

**Comment by superxiao** [comment]
@lukaseder 
When using lombok, and generated UDT using jooq, `org.jetbrains:annotations` seems to become a required dependency (without it the code fails to compile).
https://github.com/projectlombok/lombok/issues/3782

**Comment by lukaseder** [comment]
@superxiao Thanks for pointing out this bug in Lombok.
