### ISSUE TITLE
UnsupportedOperationException when selecting single nested row with JSON column

### ISSUE THREAD

**Issue by MrBergin** [jOOQ/jOOQ#13611]
### Expected behavior

Given I can select multiple nested rows (with multiset) that contain JSON columns, I also expect the same behaviour to work for single nested rows that contain JSON columns. For example if I have the following table:

```
CREATE TABLE Example(
    id bigint,
    some_json json
)
```

Then I would expect the following code to work:
```
data class SomeJsonWrapper(val someJson: JSON?)

dslContext.select(
    row(EXAMPLE.SOME_JSON).mapping(::SomeJsonWrapper)
).from(EXAMPLE)
    .where(EXAMPLE.ID.eq(1L))
    .fetchSingle()
```

### Actual behavior

The following exception is thrown instead:

```
Caused by: java.lang.UnsupportedOperationException: Class class org.jooq.JSON is not supported
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgFromString(DefaultBinding.java:3907)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgSetValue(DefaultBinding.java:3954)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.lambda$pgNewRecord$6(DefaultBinding.java:3946)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgNewRecord(DefaultBinding.java:3942)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3766)
	at org.jooq.impl.DefaultBinding$DefaultRecordBinding.get0(DefaultBinding.java:3691)
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1016)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1574)
	... 10 more
```

### Steps to reproduce the problem

I was having trouble putting into words the steps to reproduce the issue, so I've created an example project instead which you can [find here](https://github.com/DoGoodDev/jooq-bug/tree/master/src/main/kotlin/dev/dogood/jooq/bugs). I've freshly cloned the repo and run the main method, but if we get a case of "only works on my machine" please give me a shout. But roughly speaking all I've done is:

* Generate Jooq code with an example table that has a JSON column
* Try to select an individual nested row from that table

As an aside, I am able to work around this by wrapping my `JSON` field in a `multiset` (instead of `row`), and then selecting a `single` result (in kotlin this will throw an exception if there is not exactly one result), which achieves what I want in a noisier, less safe way:

```
val example1 = EXAMPLE
val example2 = EXAMPLE

dslContext.select(
    multiset(
        selectFrom(example2).where(example1.ID.eq(example2.ID))
    ).convertFrom { r -> SomeJsonWrapper(r.single().someJson) },
).from(example1)
    .where(example1.ID.eq(exampleId))
    .fetchSingle()
```

### Versions

- jOOQ: 3.16.6
- Java: 17
- Database (include vendor): postgresql:13
- OS: Manjaro 21.2.6 Qonos
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.3.6

**Comment by lukaseder** [comment]
Thanks for your report. I'll try to reproduce this soon.

**Comment by lukaseder** [comment]
I can reproduce this issue with the following, more minimal reproducer:

```java
JSON j = create().fetchValue(row(jsonArray(val(1), val(2)))).value1();
assertJSONEquals(json("[1,2]"), j);
```

Other data types are probably affected as well, including:

- `JSON`
- `JSONB`
- `XML`
- Spatial types
- Others?

**Comment by lukaseder** [comment]
I'll fix this for `JSON`, `JSONB`, and `XML` for now. Will look into other data types in a separate issue.

**Comment by lukaseder** [comment]
Might be. The deserialisation of named UDTs and unnamed ROW types is the same, so the issues might be related. Will check and add an integration test for reading and writing bind values of the following type:

```sql
CREATE TYPE u_13611 AS (
  j1 json,
  j2 jsonb,
  x xml
)
```

Thanks for bringing this up, @jadrovski.

**Comment by lukaseder** [comment]
Yeah, can reproduce the same error, and the fix for this issue fixes yours as well, @jadrovski

**Comment by bertwin** [comment]
Sorry for commenting on this old issue, but i encountered a very similar issue with a `YearToSecond`  field in a `array(select(row(` construct.

```
ERROR 68799 --- [atcher-worker-1] o.j.i.D.org.jooq.impl.DefaultBinding     : Cannot parse array       : {"(time,3,3,2022-08-16,aa,,00:00:03,,,{})"}

java.lang.UnsupportedOperationException: Class class org.jooq.types.YearToSecond is not supported
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgFromString(DefaultBinding.java:3937)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.pgSetValue(DefaultBinding.java:3984)
        at org.jooq.impl.DefaultBinding$DefaultRecordBinding.lambda$pgNewRecord$13(DefaultBinding.java:3976)
        at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:144)
```

This seems to work as a workaround:
```kotlin
field(LINE.TIME.qualifiedName, SQLDataType.VARCHAR)
   .convertFrom {  PostgresUtils.toYearToSecond(it) },
```

**Comment by lukaseder** [comment]
@bertwin Closed issues aren't on any tracking report, so while your workaround might help someone, a more thorough solution can only be implemented if you create a new issue with more details. It's probably not even strictly related to this issue here.
