### ISSUE TITLE
Allow obtaining `TableField`s from tables dynamically

### ISSUE THREAD

**Issue by makkarpov** [jOOQ/jOOQ#13612]
### Use case:

When operating with dynamically-generated schema, it often could be useful to have `TableField` instance (e.g. because you want to know the underlying table at later stages). Currently only plain `Field`s could be retrieved dynamically by name. This seems like artificial limitation, since dynamic table fields are still table fields.

### Possible solution you'd like to see:

Allow to retrieve `TableField` out of `Table` by it's name. Just one most generic overload will suffice, it should not have tons of them like it does in normal DSL. Or just change all methods of `Table` interface to return `TableField` (replacing a type with subtype in subinterface should not break anything).

### Possible workarounds:

None known. You can probably create a wrapper class that will delegate class to `Field` and `getTable` call to table, but I'm not sure whether jOOQ will work with such wrapper.

### Versions:

- jOOQ: 3.16.6
- Others: not relevant

**Comment by makkarpov** [comment]
Same logic applies to obtaining a list of all fields belonging to particular table

**Comment by lukaseder** [comment]
For the record, here's another example of where someone first thought that getting a hold of a `TableField` reference is what they needed, and the suggestion was even less feasible in the jOOQ API: https://github.com/jOOQ/jOOQ/issues/10020

**Comment by makkarpov** [comment]
Use case is very simple: dynamic schemas. You generate bunch of `CREATE TABLE` statements, and you need to somehow access resulting tables. There are some pieces in the code that need to know origin of the field - so `TableFields` come into play.

Also, from typing perspective `TableField`s are nothing more than `Field` + `Table<R> getTable()`. If field has originated from some weird table - you will just get that weird table back.

**Comment by lukaseder** [comment]
But what do you need this for?

**Comment by makkarpov** [comment]
Application (actually packaged like library, so it's configured programmatically) that reads PostgreSQL logical decoing stream and keeps it's state in a bunch of tables derived from user tables (with unnecessary fields removed, and some metadata added). Those derived tables are dynamic with respect to application, since they are generated from supplied configuration.

**Comment by makkarpov** [comment]
No, I'm not. Currently as a workaround I created wrapper class that extends `TableField`, delegates all field calls and implements `getTable` method.

User tables are just generated, so yes, they are technically extending TableImpl, but it's just codegen. Dynamic tables currently are just stubbed with `DSL.table(DSL.name(schema, table))`. Since I already know what they contain, I don't use any introspection methods on tables themselves. But table identity matters, and this is where `TableField` is extremely helpful to carry that identity along with fields.

**Comment by lukaseder** [comment]
As I thought. From your description alone, I doubt that any implementation in jOOQ would have solved the underlying problem for you...

Anyway. Thanks for sharing the use-case. Might be useful in the future for further API design in this space.
