### ISSUE TITLE
Test container does not close in example

### ISSUE THREAD

**Issue by kny78** [jOOQ/jOOQ#13635]
### Expected behavior
Test container is closed after the build

### Actual behavior
The test container is living after the build

### Steps to reproduce the problem
mvn install
Check for running containers.

### Versions

- jOOQ: 3.16.6
- Java: 17
- Database (include vendor): PostgreSQL
- OS: Linux
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Fixed as per your PR: https://github.com/jOOQ/jOOQ/pull/13636.

Thanks again
