### ISSUE TITLE
Ability to download OSS edition snapshot

### ISSUE THREAD

**Issue by morki** [jOOQ/jOOQ#13657]
### Use case:

I am using OSS edition on some project for my customer. I am paying commercial edition personally. I would like to use latest features for this project before they are released in public.

### Possible solution you'd like to see:

I would like to see OSS edition in snapshot download. 

### Possible workarounds:

I don't know.

**Comment by lukaseder** [comment]
Thanks for your feature request. Huh, we're uploading those snapshots to our FTP server and on S3, but we're not listing them on the https://www.jooq.org/download/versions page.

Should be an easy fix. Will do next week.

The workaround would be to check out the sources from github and build them yourself, it's just a `mvn clean install`

**Comment by lukaseder** [comment]
The downloads are now available on https://www.jooq.org/download/versions. Thanks again for pointing this out.
