### ISSUE TITLE
Connection::close call is skipped when R2DBC query fails

### ISSUE THREAD

**Issue by SimonAlthoff** [jOOQ/jOOQ#13669]
### Expected behavior

Connection is returned to the pool after completion/error

### Actual behavior

Connection is not returned to the pool and is never released.

### Steps to reproduce the problem

1. Run a query inserting an id, creating a conflict
2. Run a second query (this one never gets executed)

<details>
  <summary>Source Code of Test Class</summary>
  
```
@ExtendWith(SpringExtension.class)
@Slf4j
public final class TestTest {

    @Autowired
    private DSLContext context;

    @Autowired
    private ConnectionPool connectionPool;

    @TestConfiguration
    static class TestConfigurationClass {
        @Bean
        public ConnectionFactory connectionFactory() {
            return ConnectionFactories.get(ConnectionFactoryOptions
                    .parse("r2dbc:postgresql://localhost:5432/test")
                    .mutate()
                    .option(ConnectionFactoryOptions.USER, "test")
                    .option(ConnectionFactoryOptions.PASSWORD, "test")
                    .build()
            );
        }

        @Bean
        protected DSLContext weatherDataRepositoryDslContext() {

            return DSL.using(connectionPool());
        }

        @Bean
        protected ConnectionPool connectionPool() {
            ConnectionPoolConfiguration connectionPoolConfiguration = ConnectionPoolConfiguration
                    .builder(connectionFactory())
                    .initialSize(1)
                    .maxSize(1)
                    .build();

            return new ConnectionPool(connectionPoolConfiguration);
        }
    }

    @Test
    public void test() {

        //Row with id 1 is already present in the DB
        Publisher<Integer> values = context.insertInto(DSL.table("test"))
                .columns(DSL.field("id"))
                .values(1);

        Flux.from(values)
                .onErrorResume(ign -> Mono.empty())
                .blockLast();

        //This never finishes
        Flux.from(context.select().from("test"))
                .map(record -> record)
                .blockLast();
    }
}
```
</details>

### Observations

I was not able to reproduce this with h2 in the MCVE project because there _AbstractResultSubscriber.complete_ was calling the downstream _complete_ method because it had no forwarders and this in turn closed the connection. In my Postgres setup however _forwarders_ was not empty so the downstream _complete_ method was never called.

### Versions

- jOOQ: 3.16.6
- Java: 11
- Database (include vendor): Postgres 10.21
- OS: Windows 10 
- JDBC Driver (include name if inofficial driver): r2dbc-postgresql 0.8.12.RELEASE
- Connection Pool: r2dbc-pool 0.9.0.RELEASE

**Comment by lukaseder** [comment]
Thanks a lot for your report. Will look into this soon.

**Comment by lukaseder** [comment]
I'm trying to reproduce this, but how could I? There's no test / assertion / check, etc. and the debug logs all look clean to me. First off, I removed the Spring dependencies, which just complicate setting things up (I'm assuming it's not Spring causing the problem), so I tested this:

```java
// The usual ConnectionFactory from jOOQ's integration tests
ConnectionFactory cf = dbSetup.connectionFactory;
ConnectionPoolConfiguration connectionPoolConfiguration = ConnectionPoolConfiguration
        .builder(cf)
        .initialSize(1)
        .maxSize(1)
        .build();

ConnectionPool cp = new ConnectionPool(connectionPoolConfiguration);
DSLContext context = DSL.using(cp);

Publisher<Integer> values = context.insertInto(DSL.table("test"))
        .columns(DSL.field("id"))
        .values(1);

System.out.println(Flux.from(values)
        .onErrorResume(ign -> Mono.empty())
        .blockLast());

System.out.println(Flux.from(context.select().from("test"))
        .map(record -> record)
        .blockLast());
```

And this prints:

```
11:43:51,085 DEBUG [ConnectionPool                ] - Obtaining new connection from the pool
11:43:51,160 DEBUG [PARAM                         ] - [cid: 0x1][pid: 43] Bind parameter [0] to: 1
11:43:51,189 DEBUG [QUERY                         ] - [cid: 0x1][pid: 43] Executing query: insert into test (id) values ($1)
11:43:51,189 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Request:  [Parse{name='S_0', parameters=[23], query='insert into test (id) values ($1)'}, Bind{name='B_0', parameterFormats=[FORMAT_BINARY], parameters=[CompositeByteBuf(ridx: 0, widx: 4, cap: 4, components=1)], resultFormats=[], source='S_0'}, Describe{name='B_0', type=PORTAL}, Execute{name='B_0', rows=0}, Close{name='B_0', type=PORTAL}, Sync{}]
11:43:51,198 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Response: ParseComplete{}
11:43:51,198 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Response: BindComplete{}
11:43:51,198 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Response: NoData{}
11:43:51,198 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Response: CommandComplete{command=INSERT, rowId=0, rows=1}
11:43:51,199 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Response: CloseComplete{}
11:43:51,199 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Response: ReadyForQuery{transactionStatus=IDLE}
11:43:51,201 DEBUG [PooledConnection              ] - Releasing connection
1
11:43:51,480 DEBUG [ConnectionPool                ] - Obtaining new connection from the pool
11:43:51,501 DEBUG [QUERY                         ] - [cid: 0x1][pid: 43] Executing query: select * from test
11:43:51,502 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Request:  Query{query='select * from test'}
11:43:51,507 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Response: RowDescription{fields=[Field{column=1, dataType=23, dataTypeModifier=-1, dataTypeSize=4, format=FORMAT_TEXT, name='id', table=1956764}]}
11:43:51,507 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Response: DataRow{columns=[PooledSlicedByteBuf(ridx: 0, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 40, widx: 72, cap: 496))]}
11:43:51,522 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Response: DataRow{columns=[PooledSlicedByteBuf(ridx: 0, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 52, widx: 72, cap: 496))]}
11:43:51,522 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Response: CommandComplete{command=SELECT, rowId=null, rows=2}
11:43:51,522 DEBUG [ReactorNettyClient            ] - [cid: 0x1][pid: 43] Response: ReadyForQuery{transactionStatus=IDLE}
11:43:51,522 DEBUG [PooledConnection              ] - Releasing connection
+----+
|  id|
+----+
|   1|
+----+
```

It seems the connection is released properly? How can I reproduce the problem? Note that a reproducer that is based on our template here: https://github.com/jOOQ/jOOQ-mcve, would probably be the simplest approach to reliably show the problem.

**Comment by SimonAlthoff** [comment]
I didn't add any assertions because the second call to the database doesn't finish because it doesn't get (only) the connection from the pool.

I will try to create a mcve. Am I allowed to use a Postgres DB in there?

**Comment by lukaseder** [comment]
> I didn't add any assertions because the second call to the database doesn't finish because it doesn't get (only) the connection from the pool.

I see, well that didn't happen in my case...

> I will try to create a mcve. Am I allowed to use a Postgres DB in there?

Sure, you can assume some pre-existing database, that part will be easy to set up.

**Comment by SimonAlthoff** [comment]
I was able to reproduce this in the mcve environment:

https://github.com/SimonAlthoff/jOOQ-mcve/tree/issue_13669

**Comment by lukaseder** [comment]
I can reproduce it, thanks a lot. Reminds me of https://github.com/jOOQ/jOOQ/issues/13343

**Comment by lukaseder** [comment]
Ah yes, the difference is that in your MCVE, you now insert the record twice. You didn't do that originally, in the issue description.

**Comment by lukaseder** [comment]
Indeed, it looks like the `org.jooq.impl.R2DBC.Forwarding::onError` path does not lead to correct completion as the `org.jooq.impl.R2DBC.Forwarding::onComplete` path does.

**Comment by lukaseder** [comment]
A related problem is present with the new reactive transactions: https://github.com/jOOQ/jOOQ/issues/13738

**Comment by SimonAlthoff** [comment]
Great work so far. Thanks you!

**Comment by lukaseder** [comment]
https://github.com/jOOQ/jOOQ/issues/13343 is related, but not the same. When an exception occurs before actually executing the query (e.g. because of a rendering bug in jOOQ), then chances are, the reactive stream hangs as it waits forever for the `onError` signal.

**Comment by lukaseder** [comment]
OK, that was quite the chore (like everything reactive) 😅. I've now fixed:

- This issue
- Lacking `Connection::close` calls when running batches and transactions
- Hanging processes when jOOQ has rendering bugs, they now fail ordinarily: https://github.com/jOOQ/jOOQ/issues/13343

It wasn't trivial to get this right across dialects. One reason why you may have experienced different behaviour in PostgreSQL and H2 is that:

- H2's implementation seems quite synchronous, not really asynchronous
- PostgreSQL's implementation seems to send `onComplete()` calls on the `Result` even if the contained `Row` values haven't completed yet. Not sure if this is a scheduling bug in r2dbc-postgres or if this is something that clients should be able to handle, but jOOQ now attempts to sync on these, delaying the closing of the connection until both these completions are signalled
- SQL Server's implementation seems to work a bit differently from PostgreSQL's, namely instead of multiple `Segment` values, it sends multiple `Result` values. I'm not sure if this is to be expected according to the specs, though I don't see any reason why drivers shouldn't be free to stream data through either SPI type. I've asked for clarification in the SPI javadoc here: https://github.com/r2dbc/r2dbc-spi/issues/270. jOOQ made the wrong assumption that there will be only a single `Result`, and multiple `Segment` values, which produced some wrong data processing in some cases and some dialects

That's it for now, I hope.

**Comment by lukaseder** [comment]
It appears that there are still cases where this doesn't work, see https://github.com/jOOQ/jOOQ/issues/14489
