### ISSUE TITLE
 The <expression/> element in <forcedType/> is deprecated

### ISSUE THREAD

**Issue by grandinj** [jOOQ/jOOQ#13699]
Noting that this may be a bug in the gradle plugin, not the jOOQ generator, sorry if this is the wrong place.

### Expected behavior

Warning, and hard error

### Actual behavior

Deprecation warning

### Steps to reproduce the problem

Use something like:
    forcedTypes {
        forcedType {
            expression = ".*_HZ"
         }
in gradle script

This now appears to be ignored.
Which should result in a hard error, because it breaks our build, because the forcedType is not applied.
Deprecation normally means : "this is currently supported, but will be going away" :-)

### Versions

- jOOQ: 3.16.5
- Java: 11
- Database (include vendor): H2 1.4+
- OS: All
- JDBC Driver (include name if inofficial driver): H2

**Comment by grandinj** [comment]
Never mind, seems updating H2 changed the reported data type, which meant the pattern didn't match, sorry for the noise

**Comment by lukaseder** [comment]
> Never mind, seems updating H2 changed the reported data type, which meant the pattern didn't match, sorry for the noise

Yeah, I've noticed those changes (and so have many others)! I still hope that was worth it... 😅

You should see a warning about unused forced types. The deprecation is unrelated. Starting with jOOQ 3.17, those warnings can be turned into failures, see:

- https://github.com/jOOQ/jOOQ/issues/10677
- https://www.jooq.org/doc/dev/manual/code-generation/codegen-advanced/codegen-config-onerror/
