### ISSUE TITLE
IS it possible to use first column of with clause in 2nd with clause query

### ISSUE THREAD

**Issue by pradipyogi59** [jOOQ/jOOQ#13697]
Hello i have below query

```sql
WITH temp1 (column1) as 
(SELECT .....), 

temp2 (column2) as 
(select * from someTable where name >= 
select min(column1) from temp1
.......
)
(select * from.....)
```

So i want to use tamp1 and collumn1 in 2nd with clause(temp2) 
so is it possible ? not find any suitable solution.

**Comment by lukaseder** [comment]
You have to assign the first CTE to a local variable:

```java
Table<?> temp1 = name("temp1").fields("column1").as(...);
Table<?> temp2 = name("temp2").fields("column2").as(...);
```

And in the second CTE, reference `temp1` and dereference its columns using `temp1.field("column1")`. Alternatively, store those fields also in local variables to get type safety.
