### ISSUE TITLE
Wrong query in example of manual section about dynamic SQL

### ISSUE THREAD

**Issue by Markus-Patt** [jOOQ/jOOQ#13717]
Ok, jooq-beginner here, but shouldn't the last example

```
 result = result.and(BOOK.AUTHOR_ID.in(
            selectOne().from(AUTHOR).where(
                    AUTHOR.FIRST_NAME.like("%" + request.getParameter("author") + "%")
                .or(AUTHOR.LAST_NAME .like("%" + request.getParameter("author") + "%"))
            )
        ));
```
be
```
 result = result.and(BOOK.AUTHOR_ID.in(
            **select(AUTHOR.ID)**.from(AUTHOR).where(
                    AUTHOR.FIRST_NAME.like("%" + request.getParameter("author") + "%")
                .or(AUTHOR.LAST_NAME .like("%" + request.getParameter("author") + "%"))
            )
        ));
```
?

If I didn't miss anything, the original only selects only books of the author with the id = 1 (and a matching name).

Or did I miss something here?

----
See: https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql/

**Comment by lukaseder** [comment]
Yes, of course, thanks a lot for pointing this out. I suspect there must have been an original example that used `EXISTS` instead of `IN`

**Comment by lukaseder** [comment]
Fix will be included in the next build of the manual. Thanks again!
