### ISSUE TITLE
When use first CTA field in 2nd CTA and then run query then getting  error : Unknown column 'table1.column1' in 'where clause

### ISSUE THREAD

**Issue by pradipyogi59** [jOOQ/jOOQ#13727]
```java
CommonTableExpression<Record1<Integer>> as1 = name("table1").fields("column1")
    .as(
        select(STUDENT.NUMBER).from(STUDENT)
    );

CommonTableExpression<Record1<String>> as3 = name("table2").fields("column2")
    .as(
        select(DEPARTMENT.NAME).from(DEPARTMENT).
        where(DEPARTMENT.ID.eq((Field<UInteger>) **as1.field("column1")**))
    );
```

In as3 i have compare DEPARTMNET.ID with as1.field(column1)
                
**Now when i run like below :**

```java
Result<Record> fetch =
create.with(as1).with(as3).select(asterisk()).from(as1,as3).fetch();

Result<? extends Record1<?>> fetch2=
create.with(as1).with(as3).select(as3.field("column2")).from(as1, as3).fetch();
```
                
both fetch,fetch2 give below exception :
                 **Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'table1.column1' in 'where clause'**
                 
I have referred below jooq document
http://www.jooq.org/doc/latest/manual/sql-building/sql-statements/with-clause/

**Comment by lukaseder** [comment]
Thanks for your message. Well, the error says what the problem is. Your `as3` CTE didn't declare any dependency on `as1`. You have to put `as1` in `as3`'s `FROM` clause.

I'm not sure what you were trying to do here, but your query wouldn't work in plain SQL either...
