### ISSUE TITLE
Getting started section should clarify that jooq is the main dependency, and jooq-meta, jooq-codegen are typically unneeded

### ISSUE THREAD

**Issue by wcurrie** [jOOQ/jOOQ#13737]
The [preparation](https://www.jooq.org/doc/latest/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step1/) steps seem to guide users fo include all 3 dependencies: jooq, jooq-meta and jooq-codegen. 

Seems like the common usage is include only the `jooq` dependency, like in the jOOQ-mcve-java [pom.xml](https://github.com/jOOQ/jOOQ-mcve/blob/87215b064af4be3ce9eec91724e491ab3c42f528/jOOQ-mcve-java/pom.xml#L39-L44). Leaving the jooq-meta and jooq-codegen dependencies to be pulled in by the codegen plugin.

Would it make sense to clarify in the docs that typically only the `jooq` dependency is required? 

Seems like a consumer would only need the meta and codegen dependencies to run `org.jooq.codegen.GenerationTool` manually. Or other cases like reading from information_schema themselves using meta.

Thanks.

**Comment by lukaseder** [comment]
Thanks for your feedback. I agree, such a remark could be helpful. The additional dependencies are occasionally required when extending the code generator, but they aren't in that tutorial. The tutorial might be replaced in the future (there are pending tasks), but it would still make sense to add this remark to the existing tutorial.

**Comment by lukaseder** [comment]
Ah yes, the reason is the same why this tutorial will be replaced. It advocates using the `GenerationTool` as a standalone code generation tool 2 pages later, in case of which, of course, the dependency needs to be added, just as you suggested.
