### ISSUE TITLE
Inconsistent construction of OffsetDateTime

### ISSUE THREAD

**Issue by diastremskii** [jOOQ/jOOQ#13750]
### Expected behavior

When selecting an OffsetDateTime value using row value expression, the result is the same as selecting without `row()`

### Actual behavior

When using `row()`, the end result has the time zone returned from Postgres, i.e. `2020-03-15T02:00+02:00`
When not using `row()`, the end result is in UTC, i.e. `2020-03-15T00:00Z`
In this example, Postgres returns `2020-03-15 02:00:00+02` in both cases.
Presumably, the issue happens because different parsing logic is used, [this](https://github.com/jOOQ/jOOQ/blob/3dfe4750dca207cc1a77016e79c5c0adb28bacd4/jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java#L3232) one without `row()` and [this](https://github.com/jOOQ/jOOQ/blob/3dfe4750dca207cc1a77016e79c5c0adb28bacd4/jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java#L2993) one with it.

### Steps to reproduce the problem

Run these two functions and compare the results:
```
// Returns 2020-03-15T00:00Z
fun withoutRow(): OffsetDateTime =
    context
        .select(inline("2020-03-15 02:00:00+02").cast(OffsetDateTime::class.java))
        .fetchOne()!!
        .value1()

// Returns 2020-03-15T02:00+02:00
fun withRow(): OffsetDateTime =
    context
        .select(row(inline("2020-03-15 02:00:00+02").cast(OffsetDateTime::class.java)))
        .fetchOne()!!
        .value1()
        .value1()
```

### Versions

- jOOQ: 3.16.6
- Java: 17.0.3
- Database (include vendor): PostgreSQL
- OS: MacOS
- JDBC Driver (include name if unofficial driver): 42.3.3

**Comment by lukaseder** [comment]
Thanks for your report. This seems related: https://github.com/jOOQ/jOOQ/issues/12699

I think I've already seen the problem you're mentioning but I can't find the exact issue right now. Will investigate soon.

**Comment by lukaseder** [comment]
I've tried reproducing this issue just now, it no longer reproduces:

```java
var x =
ctx.select(
        inline("2000-03-15 02:02:02+02").cast(SQLDataType.OFFSETDATETIME),
        row(inline("2000-03-15 02:02:02+02").cast(SQLDataType.OFFSETDATETIME)))
    .fetchSingle();

println(x.value1().equals(x.value2().value1()));
```

The log output is:

```
13:30:58,076 DEBUG [LoggerListener                ] - Executing query          : select cast('2000-03-15 02:02:02+02' as timestamp with time zone), row (cast('2000-03-15 02:02:02+02' as timestamp with time zone)) as "nested" -- SQL rendered with a free trial version of jOOQ 3.19.0-SNAPSHOT
13:30:58,077 DEBUG [LoggerListener                ] - -> with bind values      : select cast('2000-03-15 02:02:02+02' as timestamp with time zone), row (cast('2000-03-15 02:02:02+02' as timestamp with time zone)) as "nested"
13:30:58,155 DEBUG [LoggerListener                ] - Fetched result           : +-------------------------+---------------------------+
13:30:58,155 DEBUG [LoggerListener                ] -                          : |cast                     |nested                     |
13:30:58,155 DEBUG [LoggerListener                ] -                          : +-------------------------+---------------------------+
13:30:58,155 DEBUG [LoggerListener                ] -                          : |2000-03-15T01:02:02+01:00|(2000-03-15T01:02:02+01:00)|
13:30:58,155 DEBUG [LoggerListener                ] -                          : +-------------------------+---------------------------+
13:30:58,155 DEBUG [LoggerListener                ] - Fetched row(s)           : 1
true
```

There have been numerous fixes in this area (nested records), so this is probably a duplicate by now.
