### ISSUE TITLE
Sql injection in JOOQ

### ISSUE THREAD

**Issue by KirillKurdyukov** [jOOQ/jOOQ#13761]
### Your question:

Hello!

I am developing a service that accepts a list of sql queries with named parameters. Parameter types are specified together with sql.

And then the user sets the parameters and the sql that he wants to execute.

I need the query to be correct and there is no sql injection. This is how I make named parameters

```
        val params: List<Param<*>> = input.map {
            val schema = sqlScriptSchema.params[it.key]
                ?: throw NotFoundParamSchema("Not found param ${it.key} for sql script")

            logger.info { "Bind postgres param: ${it.key} with type: ${schema.typeParam}. ${schema.description}" }

            when (TypePostgres.valueOf(schema.typeParam)) {
                TypePostgres.STRING -> DSL.param(it.key, it.value)
                TypePostgres.INT -> DSL.param(it.key, it.value.toInt())
                TypePostgres.LONG -> DSL.param(it.key, it.value.toLong())
                TypePostgres.BOOLEAN -> DSL.param(it.key, it.value.toBoolean())
                TypePostgres.FLOAT -> DSL.param(it.key, it.value.toFloat())
                TypePostgres.DOUBLE -> DSL.param(it.key, it.value.toDouble())
            }
        }
```

```

dslContext: DSLContext

dslContext.fetch(sql.sql, *sql.params.toTypedArray())
```
sql.sql : String. 

Did I understand the Api? 

### Versions:

- jOOQ: 3.15.4

**Comment by lukaseder** [comment]
Thanks a lot for your message.

Behind the scenes, a `PreparedStatement` is created and the `sql.params` will be bound as ordinary JDBC bind values. There is no SQL injection risk, if you do not concatenate any values to your `sql.sql` string.

Even if you use inline values (https://www.jooq.org/doc/latest/manual/sql-building/bind-values/inlined-parameters/), jOOQ will take care of properly escaping those values when inlining them to your SQL string.

**Comment by KirillKurdyukov** [comment]
Thanks Lukas!
