### ISSUE TITLE
Non-existent alias reference generated in `ORDER BY` clause

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#13789]
### Expected behavior

The query contains a generated alias, or the alias reference is not produced

### Actual behavior

```sql
select
  id as id,
  name as name,
  age as age
from users
where (
  name = 'John'
  and age > 30
)
order by alias_63755482.name asc
offset 0 rows
fetch next 10 rows only
```

### Steps to reproduce the problem

The relevant bit of code is below -- if this isn't useful, I can provide a project with a minimal reproduction and test case

```kt
fun queryRequestToSQL(request: QueryRequest): String {
    val columns = request.query.fields.filterValues { it is ColumnField }
        .map { it.key to it.value as ColumnField }
        .map { (alias, selectedField) -> field(name(selectedField.column)).`as`(alias) }

    val stmt = select(columns)
        .from(table(name(request.table)))
        .apply {
            request.query.where?.let { where(whereToSQL(it) as Condition) }
            orderBy(request.query.order_by.map { order ->
                field(name(order.column))?.let {
                    when (order.ordering) {
                        OrderType.ASC -> it.asc()
                        OrderType.DESC -> it.desc()
                    }
                }
            })
            limit(inline(request.query.limit))
            offset(inline(request.query.offset))
        }

    return ctx.render(stmt)
}
```

- If the problem relates to code generation, please post your code generation configuration
- If the problem relates to upgrades, please check if your RDBMS version is still supported by jOOQ: https://www.jooq.org/download/support-matrix
- A complete set of DDL statements can help re-create the setup you're having
- An MCVE can be helpful to provide a complete reproduction case: https://github.com/jOOQ/jOOQ-mcve

### Versions

- jOOQ: 3.17
- Java: 18
- Database (include vendor): N/A
- OS: Windows 11
- JDBC Driver (include name if unofficial driver): N/A

**Comment by lukaseder** [comment]
Thanks for your report. That looks like an alias produced from an implicit join path, but I can't see it in your code example. It would definitely be useful to reduce your example to something more minimal to be certain it's not a user error.

**Comment by GavinRay97** [comment]
Sure no problem, give me just a few minutes and I'll upload a zip with a minimal project 👍

**Comment by GavinRay97** [comment]
Here you are, should be able to run the `App.kt` main to get the same output, let me know if there's anything wonky with it

[jooq-repro.zip](https://github.com/jOOQ/jOOQ/files/9067326/jooq-repro.zip)

**Comment by lukaseder** [comment]
Thanks I can reproduce it. Very weird. The alias is already in the query, and not generated by the query:

<img width="297" alt="image" src="https://user-images.githubusercontent.com/734593/177939445-883dac0c-a973-4aee-96b9-ea3404168b31.png">

Will investigate further

**Comment by lukaseder** [comment]
Ah yes, haha 😅 Check out what your `field()` method really does... I've never been convinced that kotlin's binding `this` to something random was a good idea. It's just a super dangerous tool...

See also: https://twitter.com/gregopet/status/1534873925313826816

**Comment by lukaseder** [comment]
I'm still wondering how we can help users detect this mistake more easily. I mean, the main thing that should have caused suspicion is the nullability of the `field()` result:

<img width="285" alt="image" src="https://user-images.githubusercontent.com/734593/177941232-7ebe8039-bf53-45b8-aead-b376db0adc5c.png">

Versus

<img width="270" alt="image" src="https://user-images.githubusercontent.com/734593/177941254-d7a6f238-8024-4a4b-b397-c6520b4ec762.png">

It's obvious in hindsight, but not when you're coding, in case of which it's rather surprising. What I mean is that if you had chosen the right method, then you'd get a warning on this `.?let` usage:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/734593/177941483-7f152eb5-16b1-462b-a397-7b63ba0db706.png">

But how can we make this more obvious, if at all?

**Comment by GavinRay97** [comment]
Oh my god, this is maybe one of the most terrifying bugs I've ever seen, ahaha.
Thanks for helping diagnose this, never in a million years would have figured this one out on my own.
