### ISSUE TITLE
Postgres 15 adds support for SQL:2016 Standard JSON methods/operators

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#13807]
### Use case:

Postgres 15 will add support for SQL:2016 Standard JSON operators/methods:
- https://postgrespro.com/blog/pgsql/5969433

With jOOQ abstracting away syntax there's not a ton new here for users, except a `JSON_TABLE` function.

Some users may also like the increased portability of generated SQL provided by using the standard JSON methods in place of Postgres-specific ones (they are made to be drop-in compatible).

Would be great to have a flag in jOOQ to toggle use of these at some point, not particularly pressing though =)

**Comment by lukaseder** [comment]
Duplicates:

- https://github.com/jOOQ/jOOQ/issues/13760
- https://github.com/jOOQ/jOOQ/issues/10643
