### ISSUE TITLE
MySQL DEFAULT CURRENT_TIMESTAMP column is generated as computed column

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13818]
Using MySQL 8.0.29, the following table:

```sql
CREATE TABLE t_computed (
    name text NOT NULL,
    creationDate datetime DEFAULT CURRENT_TIMESTAMP
);
```

Produces wrong generated code:

```java
public final TableField<TComputedRecord, Timestamp> CREATIONDATE = 
    createField(DSL.name("creationDate"), SQLDataType.TIMESTAMP(0).generatedAlwaysAs(DSL.field("", SQLDataType.TIMESTAMP)), this, "");
```

Instead of using a default expression, the generated code references an empty computed column expression. This leads to wrong behaviour in the commercial distribution, where computed columns are by default readonly columns, and thus excluded from DML even if users include them explicitly.

While this behaviour does not affect OSS users, the metadata is still wrong, which leads to wrong DDL being produced when calling `DSLContext::ddl` on this table

**Comment by lukaseder** [comment]
The problem is with this logic in `MySQLTableDefinition`:

```java
// [#6492] MariaDB supports a standard IS_GENERATED, but MySQL doesn't (yet)
boolean generated = record.get(COLUMNS.EXTRA) != null && record.get(COLUMNS.EXTRA).toUpperCase().contains("GENERATED");
GenerationOption generationOption =
      "VIRTUAL GENERATED".equalsIgnoreCase(record.get(COLUMNS.EXTRA))
    ? GenerationOption.VIRTUAL
    : "STORED GENERATED".equalsIgnoreCase(record.get(COLUMNS.EXTRA))
    ? GenerationOption.STORED
    : null;
```

It wrongly assumes that the presence of the word `GENERATED` suffices to identify computed columns, when in fact, `DEFAULT` expressions contain `DEFAULT_GENERATED` in that column.

**Comment by lukaseder** [comment]
This isn't a regression though. It seems to happen with this particular `DEFAULT` expression. It doesn't happen with this table definition, for example:

```sql
CREATE TABLE t_computed (
    name text NOT NULL,
    creationDate datetime DEFAULT '2000-01-01 00:00:00'
);
```

**Comment by lukaseder** [comment]
Well, in a way, this is a regression on https://github.com/jOOQ/jOOQ/issues/5574

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0, 3.17.3 (https://github.com/jOOQ/jOOQ/issues/13819), and 3.16.9 (https://github.com/jOOQ/jOOQ/issues/13820)

**Comment by borovikovd** [comment]
@lukaseder seems to re-appear in 3.20.6

**Comment by lukaseder** [comment]
@borovikovd I'm not aware of any regression. Our integration tests don't indicate this. Please create a new issue with all the requested details and reproducer.
