### ISSUE TITLE
Wrong example in manual section about ST_Equals

### ISSUE THREAD

**Issue by mumumi** [jOOQ/jOOQ#13816]
Wrong content in the examples.

----
See: https://www.jooq.org/doc/latest/manual/sql-building/conditional-expressions/spatial-predicates/st-equals-predicate/

**Comment by lukaseder** [comment]
Thanks a lot for the feedback. I'm assuming you mean the examples at the bottom, which show `st_disjoint` rather than `st_equals`. Will fix right away

**Comment by lukaseder** [comment]
The fix should be deployed within the next 2 hours. Thanks again.
