### ISSUE TITLE
Aliasing `json_object` and `json_arrayagg` and using slightly different semantics

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#13822]
### Your question:

I have a niche dialect of SQL I am working with for one project,
and it uses a variant of Postgres but with slightly different syntax for JSON operators.

It uses `jsonArray_agg`, and `jsonObject`, with subquery `AS` syntax instead of `KEY, VALUE` or colons:

```sql
SELECT
    jsonObject (
        artist."ArtistId" AS ArtistId,
        artist."Name" AS Name,
        (SELECT jsonArray_agg (jsonObject (
            album."AlbumId" AS AlbumId,
            album."Title" AS Title
        )) 
        FROM album
        WHERE album."ArtistId" = artist."ArtistId") AS Albums
    )
FROM
    artist
WHERE
    artist."ArtistId" IS NOT NULL
    AND artist."Name" IS NOT NULL
LIMIT 10
```

My thought was that I could alias jOOQ's existing json to a new function with different spelling, and make an extension function like this for `jsonArray_agg`:

```kt
fun DSL.customJsonObject(subquery: SelectQuery<*>): Field<*> =
    DSL.function("jsonObject", String::class.java, subquery) // Not quite sure exactly what goes here

fun DSL.customJsonArrayAgg(subquery: SelectQuery<*>): Field<*> =
    DSL.function("jsonArray_agg", String::class.java) // Not quite sure exactly what goes here
```

### Versions:

- jOOQ: 3.18-SNAPSHOT Enterprise
- Java: 18
- Database (include vendor):
- OS:
- JDBC Driver (include name if unofficial driver):

**Comment by GavinRay97** [comment]
If I do a disgusting thing and post-process the rendered query by replacing
- `jsonObject(select`
With
- `jsonObject(`

Then the following code should work I think.
Is there a cleaner way though?

```kt
fun <T : org.jooq.Record> customJsonObject(field: SelectSelectStep<T>) =
    DSL.field("jsonObject({0})", field)

fun <T> customJsonArrayAgg(field: Field<T>) =
    DSL.field("jsonArray_agg({0})", field.dataType, field)

fun main() {
    val ctx = DefaultDSLContext(SQLDialect.POSTGRES, Settings().withRenderFormatted(true))

    val testQuery = DSL.select(
        customJsonObject(
            DSL.select(
                DSL.field("id").`as`("id"),
                DSL.field("name").`as`("name")
            )
        ),
        DSL.select(
            customJsonArrayAgg(
                customJsonObject(
                    DSL.select(
                        DSL.field("id").`as`("id"),
                        DSL.field("name").`as`("name")
                    )
                )
            )
        ).`as`("baz")
    )
    println(ctx.render(testQuery))
}
```

```sql
select
  jsonObject(select
    id as "id",
    name as "name"
  ),
  (
    select jsonArray_agg(jsonObject(select
      id as "id",
      name as "name"
    ))
  ) as "baz"
```

**Comment by lukaseder** [comment]
Thanks for your message. That's a curious dialect. Which one is it? And why don't they follow the SQL standard?

Your solution, as always with these things, is to use plain SQL templating: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

The `DSL::function` method won't work for you. You really need a sophisticated template:

```java
fun <T : org.jooq.Record> customJsonObject(vararg list: JSONEntry<*>) =
    DSL.field("jsonObject({0})", SQLDataType.JSON,
        DSL.list(list.map(e => DSL.sql("{0} as {1}", e.value(), e.key())))
    )
```

I'm using `JSONEntry` here, so you can continue using the `key(..).value(..)` syntax in jOOQ.

You could also use a `VisitListener` to translate native `QOM.JSONObject` or `QOM.JSONArrayAgg` to your own version prior to rendering. That way, you could use jOOQ native API and translate the dialect to your own version globally, rather than having to think about this all the time. Note that the `QOM` API is still experimental as of jOOQ 3.17

Hope this helps

**Comment by GavinRay97** [comment]
If you're curious, it's Teiid:

https://github.com/teiid/teiid
http://teiid.github.io/teiid-documents/14.0.x/content/reference/r_json-functions.html

I wound up using your `XMLAGG` emulation because the native syntax there is supported -- you really saved my butt with that!

**Comment by lukaseder** [comment]
> If you're curious, it's Teiid:

Interesting. They do seem to reference standard SQL a few times in their doc:

- https://docs.jboss.org/teiid/6.2/reference/en-US/html/sql_support.html
- https://teiid.io/about/why-teiid/

I don't see a good reason not to follow the standard and invent something weird instead. Even PostgreSQL 15 will finally follow more standard syntax.

Maybe you could create a feature request with them? This is just an improvement to the parser (and docs of course). No need to add new features...

> I wound up using your `XMLAGG` emulation because the native syntax there is supported -- you really saved my butt with that!

Sounds like the path of least resistance here!
