### ISSUE TITLE
How to disable DefaultCatalog generated?

### ISSUE THREAD

**Issue by OliverLiangx** [jOOQ/jOOQ#13829]
### Your question:

I try many configs but all of them doesn't work  when I try to disable generate DefaultCatelog. The reason why I don't want to generate it is that I generate custom codes in my api package and I don't want to import maven jooq dependency.

### Versions:

- jOOQ: 3.15.1
- Java: jdk11
- Database (include vendor): postgres
- OS:
- JDBC Driver (include name if unofficial driver):

**Comment by lukaseder** [comment]
Thanks for your message. You cannot deactivate that, we need a catalog instance in jOOQ's internals, and a few code generation features also rely on this type being present.

I don't fully understand the limitation you're describing related to importing jOOQ. You seem to be doing something quite different from what jOOQ is supposed to do for you. Are you just trying to use jOOQ's code generation for something completely different?

I might be able to help you with your *actual* question, which isn't about disabling `DefaultCatalog`. Just let me know.

**Comment by OliverLiangx** [comment]
@lukaseder  Thanks for your reply. In my project, I use jooq generator plugin to generate enum class by custom generator. 
This is my plugin configuration :
`    <build>
        <plugins>
            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <executions>
                    <execution>
                        <id>convergence-enum</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <jdbc>
                                
                                <driver>org.postgresql.Driver</driver>
                                <url>jdbc:postgresql://postgres:5432/local_db</url>
                                <user>my_db_user</user>
                                <password>my_db_password</password>
                            </jdbc>

                            <generator>
                                <name>xx.jooq.generator.EnumGenerator</name>

                                <database>
                                    
                                    <name>org.jooq.meta.postgres.PostgresDatabase</name>
                                    <inputSchema>public</inputSchema>
                                    <includes>project_status_enum | project_status_ai_enum</includes>
                                    <excludes />
                                </database>
                                <generate>
                                    <deprecated>false</deprecated>
                                </generate>
                                <target>
                                    
                                    <packageName>xx.project</packageName>
                                    <directory>target/generated-sources/project</directory>
                                </target>
                            </generator>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>42.2.20</version>
                    </dependency>
                    <dependency>
                        <groupId>xx</groupId>
                        <artifactId>xx-jooq-generator</artifactId>
                        <version>${project.version}</version>
                        <scope>compile</scope>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>`
And I put it in my api pom.xml, which will have my enum class generated in api jar and be imported by other module. But I don't want to import org.jooq dependency in this pom. It will cause all modules which import api jar will import org.jooq dependency too. I want to generate only enum class by this plugin.

**Comment by OliverLiangx** [comment]
And If I don't import org.jooq in my api maven pom.xml. It will cause this:
![image](https://user-images.githubusercontent.com/96855134/181485977-4a71b9e5-1053-4d55-b44e-2428e3408324.png)

**Comment by lukaseder** [comment]
I see, but your generated enum types will still depend on jOOQ as well: https://github.com/jOOQ/jOOQ/issues/10806

I can see the use-case here. Will think about this. As it is now, you'll have to do either:

- Some post processing
- Implement your own code generation logic by extending the `JavaGenerator` and removing the parts that you don't need

**Comment by OliverLiangx** [comment]
@lukaseder  I already do that by extending the JavaGenerator and remove all the classes that I don't need except "DefaultCatalog.java".  I will try other ways. Thanks for your soon reply.

**Comment by OliverLiangx** [comment]
I noticed that you answer this in https://github.com/jOOQ/jOOQ/issues/10806. Have it be imporved in version 3.18.0?

**Comment by lukaseder** [comment]
> @lukaseder I noticed that you answer this in #10806. Have it be imporved in version 3.18.0?

The task being in that milestone just means that it might be considered. Though, since it's a lot of work with a lot of edge cases and new possible bugs, I don't think it's gonig to be a priority.
