### ISSUE TITLE
Calling `fieldsRow()` within a `multiset` call causes all fields of fetched Record object to be null. (but not POJO)

### ISSUE THREAD

**Issue by joshp123** [jOOQ/jOOQ#13823]
Creating this issue as suggested by Lukas Eder here: https://stackoverflow.com/questions/73083090/jooq-fetchinto-with-fieldsrow-returns-null-for-record-object-but-not-for-pojo. 

### Expected behavior

When calling `fieldsRow()` within a `multiset` call, a fetched Record object has all fields correctly populated.

### Actual behavior

When calling `fieldsRow()` within a `multiset` call, all fields of the relevant Record object are null.
When fetching into a POJO object with an otherwise identical query, all fields are correctly populated.
When fetching each individual column of the table into a Record object, all fields are correctly populated.

### Steps to reproduce the problem

```
conf ->
    conf.dsl()
	.select(
	    RUN.fieldsRow().as("run").convertFrom(r -> r.into(RunRecord.class)),
	    RUN_PROGRESS
		.fieldsRow()
		.as("run_progress")
		.convertFrom(r -> r.into(RunProgressRecord.class)),
	    multiset(
		    select(REASON.fieldsRow()) <----- 
			.from(REASON)
			.where(REASON.RUN_ID.eq(RUN.ID)))
		.as("reasons")
		.convertFrom(r -> r.into(Reason.class)))   <---- 
	.from(RUN)
	.leftOuterJoin(RUN_PROGRESS)
	.on(RUN_PROGRESS.RUN_ID.eq(RUN.ID))
	.where(RUN.ID.eq(runId.getValue()))
    .fetch()
```

`fieldsRow()` and fetching into a generated Record class, all fields of the retrieved `ReasonRecord` objects are null!?!

```
conf ->
    conf.dsl()
	.select(
	    RUN.fieldsRow().as("run").convertFrom(r -> r.into(RunRecord.class)),
	    RUN_PROGRESS
		.fieldsRow()
		.as("run_progress")
		.convertFrom(r -> r.into(RunProgressRecord.class)),
	    multiset(
		    select(REASON.fieldsRow())
			.from(REASON)
			.where(REASON.RUN_ID.eq(RUN.ID)))
		.as("reasons")
		.convertFrom(r -> r.into(ReasonRecord.class)))   <---- 
	.from(RUN)
	.leftOuterJoin(RUN_PROGRESS)
	.on(RUN_PROGRESS.RUN_ID.eq(RUN.ID))
	.where(RUN.ID.eq(runId.getValue()))
    .fetch()
```

Selecting each `Reason` field individually, everything works as expected again:

```
conf ->
    conf.dsl()
	.select(
	    RUN.fieldsRow().as("run").convertFrom(r -> r.into(RunRecord.class)),
	    RUN_PROGRESS
		.fieldsRow()
		.as("run_progress")
		.convertFrom(r -> r.into(RunProgressRecord.class)),
	    multiset(
		    select(REASON.RUN_ID, REASON.REASON_)  <------
			.from(REASON)
			.where(REASON.RUN_ID.eq(RUN.ID)))
		.as("reasons")
		.convertFrom(r -> r.into(ReasonRecord.class)))
	.from(RUN)
	.leftOuterJoin(RUN_PROGRESS)
	.on(RUN_PROGRESS.RUN_ID.eq(RUN.ID))
	.where(RUN.ID.eq(runId.getValue()))
    .fetch()
```

### Versions

- jOOQ: 3.16.7
- Java: 17
- Database (include vendor): Postgres 11 (local in Docker)
- OS: MacOS
- JDBC Driver (include name if unofficial driver): I don't actually know.

If there's anything further I can do help diagnose the issue, please let me know! Thank you.

**Comment by lukaseder** [comment]
I can reproduce this with jOOQ 3.18. Will look into a fix now.

**Comment by lukaseder** [comment]
This is a great reminder that the additional mapping type safety introduced with jOOQ 3.15's ad-hoc converter provider can be of great use here. Much better than using reflection, you could have used the `Records.mapping(Klass::new)` idiom, which would have produced a compilation error in this particular case...
