### ISSUE TITLE
jOOQ 3.17 LTREE type generating as Any instead of LTREE

### ISSUE THREAD

**Issue by rauldeheer** [jOOQ/jOOQ#13826]
We've just upgraded to jOOQ 3.17, since we are interested in the new `LTREE` type that is included in the `org.jooq:jooq-postgres-extensions` package. We've read [this](https://blog.jooq.org/3-17-0-release-with-computed-columns-audit-columns-pattern-matching-reactive-transactions-and-kotlin-coroutine-support/) blogpost, installed the required package and updated all jOOQ versions in our build file to `3.17.2`. However, the generated jOOQ code still uses `Any` as a type instead of `LTREE`. 

### Versions
- jOOQ: 3.17.2
- Java: 17
- Database (include vendor): Postgresql
- OS: macOS
- Language: Kotlin (jooq-kotlin installed)

**Comment by lukaseder** [comment]
Thanks for your message.

Hard to say what went wrong without seeing what you did *exactly*. Can you post your complete code generation configuration, or show an MCVE (template here: https://github.com/jOOQ/jOOQ-mcve)?

**Comment by lukaseder** [comment]
I couldn't reproduce this at the time.

**Comment by jasonab** [comment]
For future reference, this happens if the extensions JAR is not on the code generator classpath
