### ISSUE TITLE
JSONB read as null, although it has a value in the database

### ISSUE THREAD

**Issue by jarasez** [jOOQ/jOOQ#13833]
I have a simple query that selects a row from a table: 

```java
dslContext.selectFrom(MyTableTable.MY_TABLE)
                .where(MyTableTable.MY_TABLE.ID.eq(id))
                .fetchOneInto(MyTableImpl.class);
```

MY_TABLE has a column of type jsonb, called config. 
Sometimes, the fetched result has config null (org.jooq.tools.LoggerListener.debug Fetched result debug message), though in the database it has values.
Also noticed that if it has a value, but I am re-executing the above query in debugger, after the 5th execution the config field is always null. 
The behavior is random, does anyone have an idea what might be causing it?

### Versions:

- jOOQ: 3.14.15
- Java: OpenJDK 11
- Database (include vendor): PostgreSQL 14.3

**Comment by lukaseder** [comment]
I can imagine at least three reasons why this could happen:

- You're in some transactional situation where the value is indeed `null` for your transaction at the time when you read it, even if in the database (using a different transaction) you can already see a newer or still see an older value.
- There's a bug when reading a very specific `JSONB` value. I'd have to know how to reproduce this, though
- There's a bug when displaying the `JSONB` value in `LoggerListener`. In that case, the `null` value wouldn't appear in your actual code, only in the logs

**Comment by lukaseder** [comment]
If you find it's one of the latter 2 possible bugs (or some other bug), please let me know, ideally with instructions on how to reproduce this. I'll then reopen this issue.
