### ISSUE TITLE
Select without a `fetch` leaks DB connection

### ISSUE THREAD

**Issue by mahdix** [jOOQ/jOOQ#13835]
### Expected behavior

If I don't include a `fetch` call to execute a SELECT statement, I should not be able to treat the statement as a resultset.

### Actual behavior

Below code:
```
return dslContext.selectFrom(TABLE_1)
            .where(...)
            .orderBy(...)
            .limit(1)
            .stream()
            .map(MyClass::getCreatedAt)
            .findFirst();
```
works fine. Returns empty (as stream will be empty) and keeps the DB connection open. 

It does not make sense to convert a half-way complete SQL command to a "Stream" but it is possible because `SelectLimitPercentStep` extends `ResultQuery` which has a `stream` function.

### Steps to reproduce the problem

Run a simple SQL command live above example. It will return `Optional.empty()` and keep DB connection open.

### Versions

- jOOQ: 3.16.8
- Java: 16
- Database (include vendor): MySQL 8
- OS: Mac OS
- JDBC Driver (include name if unofficial driver): MySQL

**Comment by lukaseder** [comment]
See my answer to your question here:
https://stackoverflow.com/a/73191064/521799
