### ISSUE TITLE
Feedback about manual section "jooq-in-7-steps-step1"

### ISSUE THREAD

**Issue by tazieee** [jOOQ/jOOQ#13834]
Why don't you specify an introduction on how to install Gradle?
You suggested a third party plugin in your response to a previous Issue.
https://github.com/jOOQ/jOOQ/issues/13332#issuecomment-1076367075

If the official position is that Gradle implementation is not established, why don't you introduce the [third party plugin](https://github.com/etiennestuder/gradle-jooq-plugin) in your tutorial?
Also, how about adding a note in the README.md recommending the use of Maven?

Thank you for your maintaining!

----
See: https://www.jooq.org/doc/3.17/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step1/

**Comment by lukaseder** [comment]
Thanks a lot for your message.

Please note that an official gradle plugin is on the roadmap, without any guaranteed delivery date, of course: https://github.com/jOOQ/jOOQ/issues/12985

> Why don't you specify an introduction on how to install Gradle?

I take that installing gradle is something that is best documented by gradle itself? What installation instructions would you expect from jOOQ? How can we keep up to date with the latest gradle version? It doesn't seem like something we should delve into doing...

> If the official position is that Gradle implementation is not established, why don't you introduce the [third party plugin](https://github.com/etiennestuder/gradle-jooq-plugin) in your tutorial?

It could be done, but then again, why not do it "right" with #12985, first.

> Also, how about adding a note in the README.md recommending the use of Maven?

Not sure what you're suggesting. The `README.md` currently doesn't really contain any interesting information with respect to tutorials. Why would we just "recommend the use of Maven"?

From what I can tell, there seem to be a couple of specific issues that you ran into when looking into jOOQ, but I can't see anything actionable here.
