### ISSUE TITLE
Exception in jooq code gen maven plugin when using a procedure for a trigger

### ISSUE THREAD

**Issue by pgokul** [jOOQ/jOOQ#13836]
### Expected behavior

jooq code gen maven plugin should generate the classes for the db schema containing a trigger

### Actual behavior

jooq code gen maven plugin throws an exception

### Steps to reproduce the problem

- Create a liquibase changeset with a trigger procedure call

` <?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
      http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.4.xsd">
  <changeSet author="gokul" id="2" runOnChange="true">
    
    <createProcedure procedureName="fn_trig_eid">
      CREATE OR REPLACE FUNCTION fn_trig_eid() RETURNS TRIGGER AS $PROC$
      BEGIN
      RETURN NEW;
      END
      $PROC$ LANGUAGE plpgsql VOLATILE;
    </createProcedure>
    
    <rollback>
      DROP FUNCTION fn_trig_eid();
    </rollback>
  </changeSet>
</databaseChangeLog> `
- Running the codegen throws the exception
` [ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.16.8:generate (jooq-generate) on project pi: Error running jOOQ code generation tool: Error while exporting schema: liquibase.exception.MigrationFailedException: Migration failed for change set changelog-2.proc.xml::2::gokul:
[ERROR]      Reason: liquibase.exception.DatabaseException: Syntax error in SQL statement "CREATE OR REPLACE [*]FUNCTION fn_trig_eid() RETURNS TRIGGER AS $PROC$\000a      BEGIN\000a      RETURN NEW;\000a      END\000a      $PROC$ LANGUAGE plpgsql VOLATILE"; expected "FORCE, VIEW, ALIAS, SEQUENCE, USER, TRIGGER, ROLE, SCHEMA, CONSTANT, DOMAIN, TYPE, DATATYPE, AGGREGATE, LINKED, MEMORY, CACHED, LOCAL, GLOBAL, TEMP, TEMPORARY, TABLE, SYNONYM, UNIQUE, HASH, SPATIAL, INDEX"; SQL statement:
[ERROR] CREATE OR REPLACE FUNCTION fn_trig_eid() RETURNS TRIGGER AS $PROC$
[ERROR]       BEGIN
[ERROR]       RETURN NEW;
[ERROR]       END
[ERROR]       $PROC$ LANGUAGE plpgsql VOLATILE [42001-210] [Failed SQL: (42001) CREATE OR REPLACE FUNCTION fn_trig_eid() RETURNS TRIGGER AS $PROC$
[ERROR]       BEGIN
[ERROR]       RETURN NEW;
[ERROR]       END
[ERROR]       $PROC$ LANGUAGE plpgsql VOLATILE]
[ERROR] -> [Help 1]
`
- When running the liquibase tool, there are no exceptions and the procedure is created witthout any errors
`
Aug 01, 2022 8:26:17 PM liquibase.changelog
INFO: Stored procedure created
Aug 01, 2022 8:26:17 PM liquibase.changelog
INFO: ChangeSet schemas/sql/changelog-2.proc.xml::2::gokul ran successfully in 12ms
`

### Versions

- jOOQ: 3.16.8
- Java: openjdk version "11.0.16"
- Database (include vendor): postgres
- OS: macOS Monterey 12.4
- JDBC Driver (include name if unofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your message. The way `LiquibaseDatabase` (as well as `DDLDatabase`, `JPADatabase`) works currently is that all migrations are simulated on an in-memory H2 database. This means that if you're using plain SQL, we cannot translate the vendor specific SQL yet. See this blog post for details:
https://blog.jooq.org/how-to-simulate-a-liquibase-migration-using-h2/

If you wish to use vendor specific features, better run your migration on a testcontainers managed database instead, see e.g. this blog post for an idea (replace Flyway by Liquibase, and it's the same thing):
https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/
