### ISSUE TITLE
jOOQ is not able to insert values for postgres varchar[]

### ISSUE THREAD

**Issue by hadson172** [jOOQ/jOOQ#13847]
### Expected behavior
When executing insert i should be able to insert varchar values.

### Actual behavior
Getting error:

> Resolved [org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [insert into app_user (firstname, lastname, email, password, verified, roles) values (?, ?, ?, ?, ?, ?)]; nested exception is org.postgresql.util.PSQLException: ERROR: column "roles" is of type character varying[] but expression is of type character varying<EOL>

### Steps to reproduce the problem
Add column to user table:

> 
> ALTER TABLE app_user
> ADD COLUMN roles VARCHAR[] NOT NULL;
> 

Execute jOOQ insert:

```
create.insertInto(table("app_user"),
            field("firstname"),
            field("lastname"),
            field("email"),
            field("password"),
            field("verified"),
            field("roles")
        ).values(
            appUser.firstname,
            appUser.lastname,
            appUser.email,
            appUser.password,
            appUser.verified,
            PostgresUtils.toPGArrayString(
                appUser.roles.toTypedArray()
            )
        ).execute() > 0

```
When I render builder to sql with inlined paramters I am getting something like this:

`insert into app_user (firstname, lastname, email, password, verified, roles) values ('Jan1', 'Kowalski1', 'foo@gmail.com', 'DABC', false, '{"USER"}')`

Execute directly with pgsql is working.
jOOQ throws aboved exception

### Versions

- jOOQ: 3.16.8
- Java: 11
- Database (include vendor): postgresql 14.2.2
- OS: windows
- JDBC Driver (include name if unofficial driver): official 42.3.6

**Comment by hadson172** [comment]
Connected to https://github.com/jOOQ/jOOQ/issues/13848

**Comment by lukaseder** [comment]
Thanks for your updates. I commented on your other issue https://github.com/jOOQ/jOOQ/issues/13848#issuecomment-1214760788

In short, please use the code generator with jOOQ:
https://blog.jooq.org/why-you-should-use-jooq-with-code-generation/

Otherwise, attach data type information to your `field()` specifications, e.g. `field("roles", String[].class)`
