### ISSUE TITLE
KotlinGenerator produces directory names with backticks when catalog names contain special characters

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13866]
Since https://github.com/jOOQ/jOOQ/issues/10751, we have a database (catalog) called `db-10751`, which has to be handled correctly by the code generator, as `-` is an illegal character in Java identifiers.

The `KotlinGenerator` produces a directory name called `` `db-10751` `` (including backticks) for that database.

**Comment by sgrimm** [comment]
Possibly the same underlying problem: I was just updating a project to start generating code for multiple PostgreSQL schemas, and I noticed that it's generating a directory called `` `public` `` for the `public` schema. I assumed it's because `public` is a Java keyword.

**Comment by lukaseder** [comment]
Thanks for the hint, @sgrimm. That would be far more significant than the original issue, as it would affect all multi schema setups.

It seems that all of the multi schema code generation setups are currently only covered by the `JavaGenerator` integration tests, which would explain why this has gone unnoticed.

The workaround is to use a `GeneratorStrategy` to override the generated package name.

**Comment by lukaseder** [comment]
Though, it's still mostly cosmetic? Having added those tests, I can't see any compilation errors, or other issues?

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0, 3.17.5 (https://github.com/jOOQ/jOOQ/issues/14037), and 3.16.11 (https://github.com/jOOQ/jOOQ/issues/14038)

**Comment by sgrimm** [comment]
Yes, it's purely cosmetic; Kotlin doesn't require package names to match source file directory names (a double-edged sword for sure).
