### ISSUE TITLE
Feedback about manual section "codegen-version-control"

### ISSUE THREAD

**Issue by 847689421** [jOOQ/jOOQ#13905]
help, I want to only control the code version of pojo, and the others are generated through continuous integration. Can you guide me how to do it?
Do you use .gitignore to exclude other code except pojo, then submit pojo to the code repository, and regenerate pojo and other code in continuous integration?
![image](https://user-images.githubusercontent.com/20372242/186066674-ed60486e-4cbd-46a3-93c2-a3d9f94f20c6.png)

----
See: https://www.jooq.org/doc/latest/manual/code-generation/codegen-version-control/

**Comment by lukaseder** [comment]
Thanks for your messsage.

In such a case, you'd typically run the code generator twice, with different configurations. Once for POJOs only, and once for everything but POJOs. But having a `.gitignore` only in some directories is also an option. The latter option would definitely profit from a `GeneratorStrategy` that makes sure POJOs are located in some entirely different package from where they are by default:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/

**Comment by lukaseder** [comment]
I will adapt the section of the manual to reflect these ideas.

**Comment by 847689421** [comment]
ok, i see, thanks a lot
