### ISSUE TITLE
Consider moving the commercial distributions to Maven Central

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#13914]
There's no technical or legal reason why the commercial edition shouldn't be hosted on Maven Central, both from our perspective as well as from sonatype's. There are numerous commercially licensed jars on Maven Central, including e.g.:

- ojdbc
- Db2 JDBC driver
- Flyway

Let's consider the implications of such a move for:

- jOOQ Express Edition
- jOOQ Professional Edition
- jOOQ Enterprise Edition

It won't work for the jOOQ Trial Edition, though, as the trial expires 30 days after download, and there's no way to implement this on Maven Central.

An alternative is this: https://github.com/jOOQ/jOOQ/issues/9906

**Comment by lukaseder** [comment]
Looking into this soon. There's also a popular use-case to use jOOQ's commercial editions in an Open Source software, which is currently quite difficult to achieve, technically and legally.

By offering distribution-only binaries on Maven Central, accompanied by a distribution-only license, which is free of charge, we enable this use-case very simply. Such Open Source software will only need licenses to develop their Open Source software, not to run it. End users would accept our terms by running jOOQ (for free).

**Comment by viveleroi** [comment]
Very glad to hear, I have been eagerly awaiting this. My software project was delayed a bit but this will have a major impact on my open source product's users.

**Comment by lukaseder** [comment]
Thanks for your feedback, @viveleroi.

I think in particular, the separate free distribution license text, that is independent of the developer license, will be very beneficial for users like you, removing any legal doubts and technical hurdles from your end users who are just using your software.

I'll expect this improvement to be ready for jOOQ 3.18.0, which is due for Q1 2023.

**Comment by lukaseder** [comment]
Still reviewing the legal implications of this, so can't push this before the release of 3.18 anymore.

**Comment by lukaseder** [comment]
I'm currently looking into https://github.com/jOOQ/jOOQ/issues/9906, which I prefer much over publishing stuff to Maven Central.

Many customers with outdated credit card information, etc. continue paying only if they have *some* sort of reminder that they haven't paid. So, unless jOOQ starts implementing some sort of license server, the approach from https://github.com/jOOQ/jOOQ/issues/9906 seems much simpler to implement checks.

I'm closing this in favour of https://github.com/jOOQ/jOOQ/issues/9906, which I *promise* will ship very soon!

**Comment by lukaseder** [comment]
https://github.com/jOOQ/jOOQ/issues/9906 has been implemented and a Maven repository for commercial artifacts is now available at https://repo.jooq.org

**Comment by lukaseder** [comment]
It just offers a second download channel for paying customers:

1. ZIP file downloads from here: https://www.jooq.org/download/versions
2. Maven repository downloads from here: https://repo.jooq.org

You can link to https://repo.jooq.org from your open source project if you want. Customers will still need a license key to access that repository
