### ISSUE TITLE
NPE when unnesting converted array data type

### ISSUE THREAD

**Issue by paulius-p** [jOOQ/jOOQ#13918]
### Expected behavior

When trying to `unnest` a converted data type using a converter (ie. from `Object[]` to `UUID[]`) you get an NPE:
```
java.lang.NullPointerException
	at java.base/java.lang.Class.isAssignableFrom(Native Method)
	at org.jooq.impl.ArrayTable.init(ArrayTable.java:124)
	at org.jooq.impl.ArrayTable.<init>(ArrayTable.java:118)
	at org.jooq.impl.ArrayTable.<init>(ArrayTable.java:83)
	at org.jooq.impl.ArrayTable.<init>(ArrayTable.java:77)
	at org.jooq.impl.DSL.unnest0(DSL.java:11091)
	at org.jooq.impl.DSL.unnest(DSL.java:11067)
```

This worked in `3.14.x`. Seems this change causes this - https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/impl/ArrayTable.java#L91 

### Actual behavior

Should be able to unnest array type field.

### Steps to reproduce the problem

Trying to `unnest` a generated array field with a converter
```
createField(DSL.name("SOME_IDS"), SQLDataType.OTHER.getArrayDataType(), this, "", new ObjectArrayToUuidArrayConverter());
```

Using forced type in `pom.xml`
```
<forcedType>
                      <userType>java.util.UUID[]</userType>
                      <converter>com.converter.ObjectArrayToUuidArrayConverter</converter>
                      <includeExpression>SOME_IDS</includeExpression>
                      <includeTypes>ARRAY</includeTypes>
</forcedType>
```

and then trying to `unnest` this field in a query.

### jOOQ Version

3.15.12

**Comment by lukaseder** [comment]
Thanks for your report. What database product is this about? H2? Things have changed a bit around H2 in recent releases, as H2 2.x now supports standard SQL arrays. Does the problem still persist in jOOQ 3.17?

**Comment by lukaseder** [comment]
I cannot reproduce the problem like this on jOOQ 3.17 nor on jOOQ 3.15:

```java
class ObjectArrayToUuidArrayConverter extends AbstractConverter<Object[], UUID[]> {
    ObjectArrayToUuidArrayConverter() {
        super(Object[].class, UUID[].class);
    }

    @Override
    public UUID[] from(Object[] databaseObject) {
        return null;
    }

    @Override
    public Object[] to(UUID[] userObject) {
        return null;
    }
}
class T extends TableImpl<Record> {
    T() {
        super(DSL.name("T"));
    }
    Field<?> C = createField(DSL.name("SOME_IDS"), SQLDataType.OTHER.getArrayDataType(), this, "", new ObjectArrayToUuidArrayConverter());
};

System.out.println(DSL.unnest(new T().C));
```

Can you please provide a fully self-contained reproducer? An MCVE (template here: https://github.com/jOOQ/jOOQ-mcve) could help, but it might not be required to reproduce this issue.

**Comment by paulius-p** [comment]
> I cannot reproduce the problem like this on jOOQ 3.17 nor on jOOQ 3.15:
> 
> ```java
> class ObjectArrayToUuidArrayConverter extends AbstractConverter<Object[], UUID[]> {
>     ObjectArrayToUuidArrayConverter() {
>         super(Object[].class, UUID[].class);
>     }
> 
>     @Override
>     public UUID[] from(Object[] databaseObject) {
>         return null;
>     }
> 
>     @Override
>     public Object[] to(UUID[] userObject) {
>         return null;
>     }
> }
> class T extends TableImpl<Record> {
>     T() {
>         super(DSL.name("T"));
>     }
>     Field<?> C = createField(DSL.name("SOME_IDS"), SQLDataType.OTHER.getArrayDataType(), this, "", new ObjectArrayToUuidArrayConverter());
> };
> 
> System.out.println(DSL.unnest(new T().C));
> ```
> 
> Can you please provide a fully self-contained reproducer? An MCVE (template here: https://github.com/jOOQ/jOOQ-mcve) could help, but it might not be required to reproduce this issue.

I get the same error using your example on `3.15.12`. 
Code is generated against H2 database where the column type is `ARRAY` and is run against a PSQL db (though the query does not reach the db anyway due to the NPE).

**Comment by lukaseder** [comment]
> I get the same error using your example on `3.15.12`.

I'm pasting this code into the MCVE template https://github.com/jOOQ/jOOQ-mcve, downgrade jOOQ to 3.15.12, and I cannot reproduce it. So, what am I missing? Are you *sure* you're using the exact jOOQ version you've mentioned?

In your stack trace:

```
java.lang.NullPointerException
	at java.base/java.lang.Class.isAssignableFrom(Native Method)
	at org.jooq.impl.ArrayTable.init(ArrayTable.java:124)
```

That line 124 doesn't really make sense to me:
https://github.com/jOOQ/jOOQ/blob/version-3.15.12/jOOQ/src/main/java/org/jooq/impl/ArrayTable.java#L124

**Comment by lukaseder** [comment]
> `createField` creates a `ConvertedDataType`, which extends from `AbstractDataType`, which in turn returns `null` on `getArrayComponentType` (and not the delegate's), when constructing `ArrayTable` object.

Prose is good, but code is better :)

**Comment by paulius-p** [comment]
> Prose is good, but code is better :)

Yes, truly. 

> Are you sure you're using the exact jOOQ version you've mentioned?

I've tried to do the same in the `mcve` repo, and it worked. Then I've looked dumb-founded what's wrong and indeed it seems I missed a number when bumping the version :facepalm: 
It was present in `3.15.2` , but no longer present in `3.15.12` which I actually wanted to use.

Sorry for the confusion.

**Comment by lukaseder** [comment]
Perfect, thanks for the confirmation.

There were a few backports in this area around 3.15.9:

- https://github.com/jOOQ/jOOQ/issues/13073
- https://github.com/jOOQ/jOOQ/issues/13097

Quite possibly, one of them fixed your issue
