### ISSUE TITLE
Trying to use a forced generator and converter on a synthetic colmn

### ISSUE THREAD

**Issue by basanthjenuhb** [jOOQ/jOOQ#13927]
### Your question

We use JOOQ for our query generation use cases.
One of the things that I am trying to do is as followes

- We have a table say `invoices` with a column called `amount` - `numeric(22, 0)`
- The value in this column is stores with some extra zeroes for precision use cases.
- Example: `100$` would be stored as `100_000_000`
- What is want to do is create a synthetic column called `human_readable_amount` - `integer`
- This column would internally refer to `amount` column on read via `generator`
- After read, the `numeric` value would be converted to `integer` value by a converter.

I have tried it using codegen.
But not able to get it working
Here is my config

```
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.17.0.xsd">

    <logging>TRACE</logging>

    <generator>
        <database>
            <name>org.jooq.meta.xml.XMLDatabase</name>
            <properties>
                <property>
                    <key>dialect</key>
                    <value>POSTGRES</value>
                </property>
                <property>
                    <key>xmlFile</key>
                    <value>./src/main/resources/postgres-schema.xml</value>
                </property>
            </properties>

            <syntheticObjects>

                <columns>
                    <column>
                        <tables>transaction</tables>
                        <name>human_readable_amount</name>
                        <type>numeric(22, 0)</type>
                    </column>
                </columns>
            </syntheticObjects>

            <customTypes>
                <customType>
                    <name>AMOUNT_TYPE</name>
                    <type>java.lang.Integer</type>
                    <converter>com.basanth.learning.jooqcodegen.models.converters.AmountConverter</converter>
                </customType>
            </customTypes>

            <forcedTypes>
                <forcedType>
                    <name>AMOUNT_TYPE</name>
                    <generator>ctx -> AMOUNT</generator>
                    <includeExpression>invoice.readable_amount</includeExpression>
                </forcedType>
            </forcedTypes>
        </database>
    </generator>
</configuration>
```

Now, this fails during codegen
Reason being
https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/impl/AbstractTable.java#L830-L832
```
protected static final <R extends Record, TR extends Table<R>, T, U> TableField<R, U> createField(Name name, DataType<T> type, TR table, String comment, Converter<T, U> converter, Generator<R, TR, U> generator) {
        return createField(name, type, table, comment, converter, null, generator);
    }
```
The method returns `TableField<R, U>`
And expects `Generator<R, TR, U> generator`

so, in my case, it translates  to `TableField<Invoices, Integer>` and `Generator<R, TR, BigInteger.class> generator`
since `AMOUNT` is of type `numeric(22, 0)` so `BigInteger`
Since is sees Integer and BigInteger, it fails

Please let me know if what I am trying is even possible
Other examples I have seen were where generator was to used to create fields of same type.
But what I am trying is of different types.
My expectation was, even though the generator is producing `Field<BigInteger>`
the converter I am providing would always be used to convert it to Integer before I get it

### jOOQ Version

3.17.0

### Database product and version

POSTGRESQL12

### Java Version

8

### OS Version

MAc OS Latest

### JDBC driver name and version (include name if unofficial driver)

postgresql:42.4.2

**Comment by lukaseder** [comment]
Thanks for your message. I'm assuming your `AmountConverter` is a `Converter<BigInteger, Integer>`, so that should satisfy the type constraints.

Do you really *need* to use `customType`? It's been a deprecated feature for a while. There might be a bug in this area, where the new `<generator>` feature doesn't work with some cases of `<customType>` yet. If you think there's a bug, can you please share:

- The XML file containing your schema
- The code of the `AmountConverter`

Other than that: Does this work for you?

```xml
<forcedTypes>
    <forcedType>
        <generator>ctx -> AMOUNT</generator>
        <userType>java.lang.Integer</userType>
        <converter>com.basanth.learning.jooqcodegen.models.converters.AmountConverter</converter>
        <includeExpression>invoice.readable_amount</includeExpression>
    </forcedType>
</forcedTypes>
```

Also, given that this is new functionality in jOOQ 3.17, it's always a good idea to check the latest patch release, too, in this case 3.17.3. I'm not aware of a bug fix in this area, but you never know.

**Comment by lukaseder** [comment]
Ah, no my bad. I can see the mistake now. If you supply a `Converter<T, U>`, then your generator must produce a value of type `U`, not `T`, according to the current API.

I'll have to review if this is really correct.

**Comment by basanthjenuhb** [comment]
yup.
Ideally the combination should be
```
Converter<T, U>
Generator<T>
```
so when `T` is retrieved from database, `T` can be converted to `U` using the converter

**Comment by basanthjenuhb** [comment]
@lukaseder any updates on this ?

**Comment by lukaseder** [comment]
Thanks a lot for your patience.

It took a bit of digging into the design process where the `Generator<?, ?, T>` type was defined, and I believe that the currently published design is correct. An example that uses `STORED` semantics (for simplicity)

```sql
create table pythagoras (
  a int,
  b int,
  c int
);
```

Now, we want to compute `c = sqrt(a^2 + b^2)`. We'd write (for brevity, I'll omit full qualification of `org.jooq.impl.DSL.*`):

```xml
<forcedTypes>
    <forcedType>
        <generator>ctx -> sqrt(square(A).plus(square(B)))</generator>
        <includeExpression>C</includeExpression>
    </forcedType>
</forcedTypes>
```

Now, we want to do this with `Double` in the client, not with `Integer`. So, we've added

```xml
<forcedTypes>
    <forcedType>
        <name>DOUBLE</name>
        <includeExpression>A|B</includeExpression>
    </forcedType>
    <forcedType>
        <generator>ctx -> sqrt(square(A).plus(square(B)))</generator>
        <name>DOUBLE</name>
        <includeExpression>C</includeExpression>
    </forcedType>
</forcedTypes>
```

The experssion for `C` is still correct, as we're squaring and adding doubles (the `U` type). If we had to create an expression based on the `T` type (integer), we couldn't use `A` and `B` anymore, here. As far as your user code is concerned `T` doesn't exist anymore, only `U` does.

In your own example, the computed column will have to take care of converting itself directly in the generator expression, using

```xml
<forcedTypes>
    <forcedType>
        <name>INTEGER</name>
        <generator>ctx -> AMOUNT.convertFrom(new com.basanth.learning.jooqcodegen.models.converters.AmountConverter())</generator>
        <includeExpression>invoice.readable_amount</includeExpression>
    </forcedType>
</forcedTypes>
```

Of course, a different design would have been possible as well. There are merits to both approaches. But the design that was chosen was assuming that expressions may be based on columns that have themselvse converters and bindings.

**Comment by lukaseder** [comment]
... and you'd declare your `READABLE_AMOUNT` synthetic column as an `INTEGER` column, not a `NUMERIC` one:

```xml
<syntheticObjects>
    <columns>
        <column>
            <tables>transaction</tables>
            <name>readable_amount</name>
            <type>INTEGER</type>
        </column>
    </columns>
</syntheticObjects>

```
