### ISSUE TITLE
Show deprecation warning for javax.persistence annotations also for method and field annotations

### ISSUE THREAD

**Issue by muehmar** [jOOQ/jOOQ#13925]
### Use case

When mapping a class to a jooq record with `javax.persistence.Column` annotations for the getter methods with the `DSLContext.newRecord` method, I got no warning when using Jooq 3.17.2. The `Tools.hasColumnAnnotations` does only check the annotations of the class and not annotations on method level.

No serious problem, but if there is already a warning when using the wrong package, one might show it also for classes without annotations on class level instead of digging into the code why the mapping fails.

### jOOQ Version

3.17.2 Pro

### Database product and version

MariaDB 10.3

### Java Version

Java 11

**Comment by lukaseder** [comment]
Thanks for your suggestion. I agree, this could be done. It's not too much extra runtime effort (because `Tools::hasColumnAnnotations` is cached on a per-class basis), and it definitely helps trouble shoot issues on a per-class basis.

We'll traverse all methods and members of a type.
