### ISSUE TITLE
Idea: facilities for bridging jOOQ converters to Spring converters

### ISSUE THREAD

**Issue by runeflobakk** [jOOQ/jOOQ#13958]
### Background

I am very fond of "semantically typing" my IDs. By that, I mean that instead of passing around longs, Strings, or even UUIDs, I prefer to pass a custom type, typically implemented as a Java `record` looking like something like this:

```java
public record PublicSomethingId(UUID value) {
    public static class JooqConverter extends BetterAbstractConverter<UUID, PublicSomethingId> {
        public JooqConverter() {
            super(UUID.class, PublicSomethingId::new, PublicSomethingId.class, PublicSomethingId::value);
        }
    }
    public static PublicSomethingId generateNew() {
        return new PublicSomethingId(UUID.randomUUID());
    }
}
```
I then declare the `PublicSomethingId.JooqConverter` to be used with a `forcedType` in my POM.
`BetterAbstractConverter` (excuse the silly name) extends `org.jooq.impl.AbstractConverter`, and is my own base class to be able to create concrete converter classes with a single constructor invocation instead of overriding two methods, as mandated by `AbstractConverter`. I need to use subclassing instead of the many convenient factory methods already provided by jOOQ in order to be able to declare it as a forced type for the code generator (#13787). `BetterAbstractConverter` is an abstract class variant of
`Converter.of(Class fromType, Class toType, Function from, Function to)` (types omitted for brevity).

This works well, and I am able to keep the ID encapsulated through the entire application (or [middleware](https://blog.jooq.org/stop-mapping-stuff-in-your-middleware-use-sqls-xml-or-json-operators-instead/), if you prefer 😄) and used directly in the jOOQ queries instead of unwrapping them.

This way the type system has saved me several times from mixing up my IDs, comparing apple IDs with orange IDs, and so on. I have on multiple occasions experienced systems which has served wrong data simply because the IDs have been mixed up.

---

Now, I use the same strategy for my custom ID types with whatever Web framework I am using. Nowadays I tend to use Spring Boot, and thus prefer to declare my custom ID types as parameters to my controller handler methods:
```java
@RestController
class SomethingController {

    @GetMapping("/somethings/{id}")
    Something getSomething(@PathVariable("id") PublicSomethingId id) { ... }
}
```
So to achieve this, I need to implement a Spring converter similar to the jOOQ one, and usually one that converts "both ways" to be able to include `PublicSomethingId` in response entities, not just as a request parameter.

### Use case

I have implemented the "jOOQ pattern" for converters as an implementation of a Spring [`GenericConverter`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/convert/converter/GenericConverter.html), in order to support conversion both ways; to be a sort of "mirror" of the converter pattern in jOOQ.

<details>
  <summary><tt>class BilateralConverter&lt;T1, T2&gt; implements org.springframework.core.convert.converter.GenericConverter</tt> (click to show)</summary>
<pre>
import org.springframework.core.convert.TypeDescriptor;
import org.springframework.core.convert.converter.Converter;
import org.springframework.core.convert.converter.GenericConverter;

import java.util.Set;

public class BilateralConverter<T1, T2> implements GenericConverter {

    private final Set<ConvertiblePair> theConvertiblePairs;
    private final Converter<? super T1, T2> toSecondType;
    private final Converter<? super T2, T1> toFirstType;
    private final Class<T1> firstType;
    private final Class<T2> secondType;

    public BilateralConverter(Class<T1> firstType, Converter<? super T1, T2> toSecondType, Class<T2> secondType, Converter<? super T2, T1> toFirstType) {
        this.firstType = firstType;
        this.toSecondType = toSecondType;
        this.secondType = secondType;
        this.toFirstType = toFirstType;
        this.theConvertiblePairs = Set.of(new ConvertiblePair(firstType, secondType), new ConvertiblePair(secondType, firstType));
    }

    @Override
    public final Set<ConvertiblePair> getConvertibleTypes() {
        return theConvertiblePairs;
    }

    @Override
    public final Object convert(Object source, TypeDescriptor sourceType, TypeDescriptor targetType) {
        if (firstType.isAssignableFrom(sourceType.getType()) && secondType.isAssignableFrom(targetType.getType())) {
            return toSecondType.convert(firstType.cast(source));
        } else if (secondType.isAssignableFrom(sourceType.getType()) && firstType.isAssignableFrom(targetType.getType())) {
            return toFirstType.convert(secondType.cast(source));
        } else {
            throw new IllegalArgumentException("Unable to convert " + source + " from " + sourceType + " to " + targetType);
        }
    }

    public <T0> BilateralConverter<T0, T2> compose(Class<T0> zerothType, Converter<? super T0, T1> toExistingFirstType, Converter<? super T1, T0> toZerothType) {
        return new BilateralConverter<>(zerothType, toExistingFirstType.andThen(this.toSecondType), this.secondType, this.toFirstType.andThen(toZerothType));
    }

    public <T0> BilateralConverter<T0, T2> compose(BilateralConverter<T0, T1> convertBefore) {
        return compose(convertBefore.firstType, convertBefore.toSecondType, convertBefore.toFirstType);
    }

    public <T3> BilateralConverter<T1, T3> andThen(Class<T3> thirdType, Converter<? super T2, T3> toThirdType, Converter<? super T3, T2> toExistingSecondType) {
        return new BilateralConverter<>(this.firstType, this.toSecondType.andThen(toThirdType), thirdType, toExistingSecondType.andThen(toFirstType));
    }

    public <T3> BilateralConverter<T1, T3> andThen(BilateralConverter<T2, T3> convertAfter) {
        return andThen(convertAfter.secondType, convertAfter.toSecondType, convertAfter.toFirstType);
    }

}</pre>
</details>

In addition I have an adapter especially for _converting_ an existing jOOQ converter to a Spring converter:
```java
import BilateralConverter;

public class JooqConverterAdapter<T1, T2> extends BilateralConverter<T1, T2> {
    public JooqConverterAdapter(org.jooq.Converter<T1, T2> jooqConverter) {
        super(jooqConverter.fromType(), jooqConverter::from, jooqConverter.toType(), jooqConverter::to);
    }
}
```
As an extra quirk, to be able to use a jOOQ converter with an UUID as its "from type", Spring needs the type to be a `String`. This is supported by using one of the `compose` methods to amend the conversion between `String` and  `UUID`.

All this makes it rather simple to register a Spring converter by reusing the jOOQ converter:
```java
@Bean
public WebMvcConfigurer webMvcConfigurer() {
    return new WebMvcConfigurer() {
        @Override
        public void addFormatters(FormatterRegistry registry) {
            registry.addConverter(
                new JooqConverterAdapter<>(new PublicSomethingId.JooqConverter())
                        .compose(String.class, UUID::fromString, UUID::toString));
        }
    };
}
```

The String/UUID conversion may be such a common case that a small standalone Spring converter may be in order, simplifying adding converters to the `FormatterRegistry` even further:

```java
public class StringUuidBilateralConverter extends BilateralConverter<String, UUID> {
    public StringUuidBilateralConverter() {
        super(String.class, UUID::fromString, UUID.class, UUID::toString);
    }
}

// creating Spring converter, reusing PublicSomethingId.JooqConverter,
// converting between String <--> PublicSomethingId
new JooqConverterAdapter<>(new PublicSomethingId.JooqConverter()).compose(new StringUuidBilateralConverter())
```

### Possible workarounds

So this is more a question than a request really. Since this approach has worked very well for me, I would like to offer it or any relevant part of it, if interesting, back to the jOOQ community. Maybe it is something that is applicable for jOOQ-spring-boot-example, if not as a part of the library itself? If this sparks your interest at all, let me know how I may assist in contributing any of it, if so desired 😄 

It could just as well live as a completely separate open source jOOQ-extension, but I wanted to ask if you think it would be worth having as part of jOOQ itself before considering open sourcing it myself.

Thank you!

### jOOQ Version

jOOQ Community 3.17.2

### Database product and version

PostgreSQL 11.13

### Java Version

Temurin-17.0.4.1+1

**Comment by lukaseder** [comment]
Thanks for your feature request. 

### Regarding your intro:

jOOQ 3.14 introduced embeddables, including a way to automatically create embeddables for primary keys / unique keys as well as all foreign keys referencing them:

- https://github.com/jOOQ/jOOQ/issues/2530
- https://github.com/jOOQ/jOOQ/issues/6124

You can find the documentation here:

- https://www.jooq.org/doc/latest/manual/code-generation/codegen-embeddable-types/codegen-embedded-keys/

### Regarding your actual feature request:

I'm not sure if I understand the value added by your implementation? Your `compose()` method looks just like jOOQ's `Converters::of` or `Converter::andThen`, so it seems unnecessary.

The fact that it implements Spring's `GenericConverter` seems interesting, but maintaining a core module just for that needs much more thought than just "this looks useful."

For example, the idea of building such a registry for `T/U` type pairs and their relevant converter has been rejected here: https://github.com/jOOQ/jOOQ/issues/3896#issuecomment-305459175. While users can obviously decide for any such pair to be unique and unambiguous, jOOQ cannot. For the same pair `T/U`, there may exist multiple possible converters, depending on specific context.

As such, I'm not convinced yet why this should go into jOOQ. Of course, no one keeps you from maintaining your own library.
