### ISSUE TITLE
Feedback about manual section "sql-dialect-family"

### ISSUE THREAD

**Issue by jiangtiqiang** [jOOQ/jOOQ#13962]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/sql-dialect-family/

### Feedback

jooq's sql-dialect-famliy support opengauss  database?

**Comment by lukaseder** [comment]
Thanks a lot for your message. No, we don't support that product, and it's unlikely we'll support it in the near future, given its low popularity in this ranking here:
https://db-engines.com/de/ranking

However, after briefly looking at its documentation, perhaps you can get quite far with the PostgreSQL, H2, or HSQLDB dialects, which are all quite standards compliant.
