### ISSUE TITLE
MultiSet not working with H2 v1? 

### ISSUE THREAD

**Issue by theodiefenthal** [jOOQ/jOOQ#13968]
### Expected behavior

I formulated a query which seems to be fine on compile time, but throws erros at runtime. The query should just run fine :) 

Here is my query utilizing MultiSet:

```
    private List<UserGroup> readUsergroupsWithDataSources(DSLContext ctx, Condition cond) {
        return ctx.select(row(
                        USER_GROUP.ID,
                        USER_GROUP.VERSION,
                        USER_GROUP.NAME,
                        USER_GROUP.DESCRIPTION,
                        USER_GROUP.LABELS.convertFrom(UserGroupDAO::convertToStringsSet),
                        multiset(
                                select(USER_GROUP_DATASOURCE.DATASOURCE_ID)
                                        .from(USER_GROUP_DATASOURCE)
                                        .where(USER_GROUP_DATASOURCE.USER_GROUP_ID.eq(USER_GROUP.ID))
                        ).as("datasources").convertFrom(r -> r.intoSet(Record1::value1))
                ).mapping(UserGroup::new)
        )
                .from(USER_GROUP)
                .where(cond)
                .fetch(Record1::value1);
    }
 ```

As this query compiles fine, I exptected it to deliver my desired result. 

### Actual behavior

However, I receive the following error:

```
SQL [select "TESTDB"."USER_GROUP"."ID" "row.ID", "TESTDB"."USER_GROUP"."VERSION" "row.VERSION", "TESTDB"."USER_GROUP"."NAME" "row.NAME", "TESTDB"."USER_GROUP"."DESCRIPTION" "row.DESCRIPTION",  "TESTDB"."USER_GROUP"."LABELS" "row.LABELS", (select coalesce(json_arrayagg(json_array("v0" null on null)), json_array(null on null)) from (select "TESTDB"."USER_GROUP_DATASOURCE"."DATASOURCE_ID" "v0" from "TESTDB"."USER_GROUP_DATASOURCE" where "TESTDB"."USER_GROUP_DATASOURCE"."USER_GROUP_ID" = "TESTDB"."USER_GROUP"."ID") "t") "row.datasources" from "TESTDB"."USER_GROUP" where "TESTDB"."USER_GROUP"."ID" = cast(? as varchar(36))]; Feld "TESTDB.USER_GROUP.ID" nicht gefunden
Column "TESTDB.USER_GROUP.ID" not found; SQL statement:
CREATE FORCE VIEW (
    SELECT
        "TESTDB"."USER_GROUP_DATASOURCE"."DATASOURCE_ID" AS "v0"
    FROM "TESTDB"."USER_GROUP_DATASOURCE"
    WHERE "TESTDB"."USER_GROUP_DATASOURCE"."USER_GROUP_ID" = "TESTDB"."USER_GROUP"."ID"
) AS
SELECT
    "TESTDB"."USER_GROUP_DATASOURCE"."DATASOURCE_ID" AS "v0"
FROM "TESTDB"."USER_GROUP_DATASOURCE"
WHERE "TESTDB"."USER_GROUP_DATASOURCE"."USER_GROUP_ID" = "TESTDB"."USER_GROUP"."ID" [42122-200]
org.jooq.exception.DataAccessException: SQL [select "TESTDB"."USER_GROUP"."ID" "row.ID", "TESTDB"."USER_GROUP"."VERSION" "row.VERSION", "TESTDB"."USER_GROUP"."NAME" "row.NAME", "TESTDB"."USER_GROUP"."DESCRIPTION" "row.DESCRIPTION",  "TESTDB"."USER_GROUP"."LABELS" "row.LABELS", (select coalesce(json_arrayagg(json_array("v0" null on null)), json_array(null on null)) from (select "TESTDB"."USER_GROUP_DATASOURCE"."DATASOURCE_ID" "v0" from "TESTDB"."USER_GROUP_DATASOURCE" where "TESTDB"."USER_GROUP_DATASOURCE"."USER_GROUP_ID" = "TESTDB"."USER_GROUP"."ID") "t") "row.datasources" from "TESTDB"."USER_GROUP" where "TESTDB"."USER_GROUP"."ID" = cast(? as varchar(36))]; Feld "TESTDB.USER_GROUP.ID" nicht gefunden
Column "TESTDB.USER_GROUP.ID" not found; SQL statement:
CREATE FORCE VIEW (
    SELECT
        "TESTDB"."USER_GROUP_DATASOURCE"."DATASOURCE_ID" AS "v0"
    FROM "TESTDB"."USER_GROUP_DATASOURCE"
    WHERE "TESTDB"."USER_GROUP_DATASOURCE"."USER_GROUP_ID" = "TESTDB"."USER_GROUP"."ID"
) AS
SELECT
    "TESTDB"."USER_GROUP_DATASOURCE"."DATASOURCE_ID" AS "v0"
FROM "TESTDB"."USER_GROUP_DATASOURCE"
WHERE "TESTDB"."USER_GROUP_DATASOURCE"."USER_GROUP_ID" = "TESTDB"."USER_GROUP"."ID" [42122-200]
	at org.jooq_3.16.6.H2.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3071)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:316)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2867)
	at org.jooq.impl.ResultQueryTrait.collect(ResultQueryTrait.java:357)
	at org.jooq.impl.ResultQueryTrait.fetch(ResultQueryTrait.java:1462)
	......
```

Please note that I am using jooq 3.16.6 and h2 1.4.200. Sadly, I can't upgrade h2 right now.. 

### Steps to reproduce the problem

try to execute the query. 

### jOOQ Version

JOOQ Professional 3.16.6

### Database product and version

H2 1.4.200

### Java Version

OpenJDK 11

### OS Version

Windows 10 x64

### JDBC driver name and version (include name if unofficial driver)

h2 1.4.200 MODE=Oracle.

**Comment by lukaseder** [comment]
Thanks for your report.

I'll have to probably add something to the error messages from exceptions when people run into this limitation here: https://github.com/jOOQ/jOOQ/issues/12045

Some SQL dialects cannot correlate derived tables, and correlated `MULTISET` currently rely on this. The workaround might be to use `MULTISET_AGG`.

However, since this is a significant H2 limitation for such queries, I also recommend considering using https://www.testcontainers.org

**Comment by theodiefenthal** [comment]
Off-topic: :D I'd be really happy if you could convince my team to use testcontainers instead of h2. Every few month I have to apply some workarounds due to h2 and I start a discussion in the team to use testcontainers instead of h2. "but then, our project doesn't run with `gradlew build` anymore on a fresh developer machine as it first requires to install docker for every developer.... On a project packaged in docker images deployed on a kubernetes cluster...

But thanks for the explanation. I somehow already new that it must be an h2 issue..

**Comment by lukaseder** [comment]
> Off-topic: :D I'd be really happy if you could convince my team to use testcontainers instead of h2. Every few month I have to apply some workarounds due to h2 and I start a discussion in the team to use testcontainers instead of h2. "but then, our project doesn't run with `gradlew build` anymore on a fresh developer machine as it first requires to install docker for every developer.... On a project packaged in docker images deployed on a kubernetes cluster...

You don't *have to* run testcontainers locally. Are you aware of the company behind it? https://www.atomicjar.com
