### ISSUE TITLE
Wrong Java version support listed on website for jOOQ 3.17 Open Source Edition

### ISSUE THREAD

**Issue by etiennestuder** [jOOQ/jOOQ#13976]
### Expected behavior

Compiling a project with a dependency to org.jooq:jooq-codegen:3.17.x should work when using JDK 11, given this [list](https://www.jooq.org/download/versions#oss).

### Actual behavior

Fails to compile:
https://scans.gradle.com/s/2ankdnixupdmc/console-log?task=:compileGroovy#L2

### Steps to reproduce the problem

- configure JDK 11 on the path
- take a sample project and define a dependency to org.jooq:jooq-codegen:3.17.x
- make sure the project uses jOOQ codegen classes
- compile the project --> will fail

### jOOQ Version

3.17.x available from MavenCentral

### Database product and version

No DB involved.

### Java Version

JDK 11

### OS Version

MacOS

**Comment by lukaseder** [comment]
Thanks a lot for your report, and sorry for the delay. The notification email didn't seem to come through.

Starting with jOOQ 3.17, the baseline is Java 17 for the jOOQ Open Source Edition, see https://github.com/jOOQ/jOOQ/issues/12430

But the list you've linked is indeed wrong. I'll fix it right away.

**Comment by lukaseder** [comment]
Fixed: https://www.jooq.org/download/versions#oss

Thanks again for your report!

**Comment by etiennestuder** [comment]
Thanks, @lukaseder.
