### ISSUE TITLE
Code generator produces wrong ordering of DataType properties for nullable and defaulted array types

### ISSUE THREAD

**Issue by arlampin** [jOOQ/jOOQ#14005]
### Expected behavior

If I have the following SQL definition in Postgres 14 database:
```
CREATE TABLE xxx (
    id  SERIAL PRIMARY KEY,
    foo TEXT[] NOT NULL DEFAULT ARRAY []::TEXT[],
    bar TEXT[] NOT NULL,
    baz TEXT[] DEFAULT ARRAY []::TEXT[]
);
```
then running codegen should result in correct nullable and default definitions in generated `XxxTable`

### Actual behavior

Here are the relevant parts of generated file

```
/**
 * The column <code>public.xxx.foo</code>.
 */
public final TableField<XxxRecord, String[]> FOO = createField(DSL.name("foo"), SQLDataType.CLOB.getArrayDataType(), this, "");

/**
 * The column <code>public.xxx.bar</code>.
 */
public final TableField<XxxRecord, String[]> BAR = createField(DSL.name("bar"), SQLDataType.CLOB.getArrayDataType(), this, "");

/**
 * The column <code>public.xxx.baz</code>.
 */
public final TableField<XxxRecord, String[]> BAZ = createField(DSL.name("baz"), SQLDataType.CLOB.getArrayDataType(), this, "");
```

None of the three columns have nullability nor default values.

### Steps to reproduce the problem

Run codegen with default settings using given SQL.

### jOOQ Version

3.17.4 Open Source

### Database product and version

PostgreSQL 14.2 on aarch64-apple-darwin20.6.0

### Java Version

openjdk version "18.0.2.1" 2022-08-18

### OS Version

Macos

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.0

**Comment by lukaseder** [comment]
Thanks for your report. I will look into this, soon

**Comment by lukaseder** [comment]
Looking into this now. Related issues include:

- https://github.com/jOOQ/jOOQ/issues/14618
- https://github.com/jOOQ/jOOQ/issues/14628

**Comment by lukaseder** [comment]
Doesn't seem to be a code generation issue. Using the `DDLDatabase` in a code generation integration test with:

```sql
CREATE TABLE arrays.t_14005 (
  a_nn int ARRAY NOT NULL,
  a_d int ARRAY DEFAULT ARRAY[1],
  a_d_nn int ARRAY NOT NULL DEFAULT ARRAY[1]
);
```

I'm getting:

```java
/**
 * The column <code>ARRAYS.T_14005.A_NN</code>.
 */
public final TableField<T_14005Record, Integer[]> A_NN = createField(DSL.name("A_NN"), SQLDataType.INTEGER.nullable(false).array(), this, "");

/**
 * The column <code>ARRAYS.T_14005.A_D</code>.
 */
public final TableField<T_14005Record, Integer[]> A_D = createField(DSL.name("A_D"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("ARRAY [1]"), SQLDataType.INTEGER)).array(), this, "");

/**
 * The column <code>ARRAYS.T_14005.A_D_NN</code>.
 */
public final TableField<T_14005Record, Integer[]> A_D_NN = createField(DSL.name("A_D_NN"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("ARRAY [1]"), SQLDataType.INTEGER)).array(), this, "");
```

At least on jOOQ 3.18.0. So, probably a problem when reading the PostgreSQL specific `information_schema` and `pg_catalog` views and tables

**Comment by lukaseder** [comment]
Hmm, nope, there's still a problem. The information is generated on the array's base type, not on the array itself. These tests fail:

```java

@Test
public void testMetaConstraints() {
    assertFalse(T_14005.A_NN.getDataType().nullable());
    assertFalse(T_14005.A_D_NN.getDataType().nullable());
    assertTrue(T_14005.A_D.getDataType().nullable());
}

@Test
public void testMetaDefaults() {
    assertFalse(T_14005.A_NN.getDataType().defaulted());
    assertTrue(T_14005.A_D_NN.getDataType().defaulted());
    assertTrue(T_14005.A_D.getDataType().defaulted());
}
```

**Comment by arlampin** [comment]
I checked with 3.18 and I can confirm that at least my reported problem was fixed

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.16 (https://github.com/jOOQ/jOOQ/issues/17753)
- 3.18.23 (https://github.com/jOOQ/jOOQ/issues/17754)
