### ISSUE TITLE
Exclude SQLITE_SEQUENCE, SQLITE_MASTER, SQLITE_STAT% when <includeSystemTables/> is false

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14007]
SQLite has a few system tables, such as:

- `SQLITE_SEQUENCE`
- `SQLITE_MASTER`
- `SQLITE_STAT%`

Which should probably not be included by default in generation output, e.g. to prevent issues like:

- https://github.com/jOOQ/jOOQ/issues/14001

We're already excluding the system tables used for virtual tables, see:

- #11176

**Comment by lukaseder** [comment]
Since the flag defaults to `false`, this will be an incompatible change for existing code generation setups.

**Comment by DaveO-Home** [comment]
@lukaseder - I don't really need the sequence table, except to generate the seq. I just wanted to get rid of the warning. I would remove the forcedtype if you default to excluding it.  The blob worked because the default datatype for sqlite is 'BLOB'.

**Comment by lukaseder** [comment]
OK, perfect, thanks for the feedback.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.18
