### ISSUE TITLE
Feedback about manual section runtime-schema-mapping

### ISSUE THREAD

**Issue by daicoden** [jOOQ/jOOQ#14008]
Section to TableMapping:

Regardless of the desire to remap the schema name, you must still configure an input or inputExpression for the MappedSchema to be applied to tables.  

```
Settings settings = new Settings()
    .withRenderMapping(new RenderMapping()
    .withSchemata(
        new MappedSchema().withInputExpression(Pattern.compile(".*"))
                          .withTables(
         new MappedTable().withInput("AUTHOR")
                          .withOutput("MY_APP__AUTHOR"))));

```

Will apply the mapping for all schema's with a AUTHOR table.

**Comment by daicoden** [comment]
I realized I was reading the head documentation, I'm currently on jooq 3.14.16, so I opened the feedback prematurely.

FWIW: 3.14.16 and 3.17 both say:

```
Table mapping and schema mapping can be applied independently, by specifying several MappedSchema entries in the above configuration. jOOQ will process them in order of appearance and map at first match. Note that you can always omit a MappedSchema's output value, in case of which, only the table mapping is applied. If you omit a MappedSchema's input value, the table mapping is applied to all schemata!

```

I do not believe is true on 3.14.16 - if you omit a MappedSchema's input value, it is applied to none... you have to add an inputExpression, but I don't have an easy way to check 3.17.

**Comment by lukaseder** [comment]
Thanks for the pointer. You're right. While I vaguely remember there might have been such a feature in the past, it must have been obsoleted when regular expressions could be used in the mapping, in case of which a more explicit `.*` schema input pattern is used to apply a table mapping to all schemas.

I'll fix the manual right away.
