### ISSUE TITLE
Code Gen - Sqlite3 with internal sequence (autoincrement primary key) - unrecognized datatype

### ISSUE THREAD

**Issue by DaveO-Home** [jOOQ/jOOQ#14001]
### Expected behavior

No deprecation errors

### Actual behavior

../generated/tables/records/SqliteSequenceRecord.kt: (36, 73): 'NAME: TableField<SqliteSequenceRecord, Any?>' is deprecated. Unknown data type.
Same error for field 'SEQ'

### Steps to reproduce the problem

Problem: sqlite creates the sqlite-sequence table without datatypes. The default affinity is 'BLOB'.
See; https://renenyffenegger.ch/notes/development/databases/SQLite/internals/schema-objects/sqlite_sequence

Try
```
sqlite3 test.db <<EOF
create table test (test integer primary key autoincrement not null);
EOF
```
to create the sqlite-sequence table.

Using
```
Configuration configuration = new Configuration()
    .withJdbc(new Jdbc()
            .withUrl(jdbcUrl))
    .withGenerator(new Generator()
        .withName("org.jooq.codegen.KotlinGenerator")
        .withDatabase(new Database()
            .withName("org.jooq.meta.sqlite.SQLiteDatabase")
            .withOutputSchemaToDefault(true)
            .withIncludeTables(true)
            .withIncludePrimaryKeys(true)
            .withInputSchema("")
            .withExcludes(
                "USERS|UNDELIVERED|MESSAGES"))
        .withGenerate(new Generate()
            .withDeprecated(false)
        )
        .withTarget(new Target()
            .withPackageName("golf.handicap.generated")
            .withClean(true)
            .withDirectory("./src/main/kotlin")))
    .withLogging(Logging.WARN);
GenerationTool.generate(configuration);
```

### jOOQ Version

JOOQ Community 3.17.2 & .4

### Database product and version

SQLite 3.36.0 2021-06-18 18:36:39 5c9a6c06871cb9fe42814af9c039eb6da5427a6ec28f187af7ebfb62eafaalt1 zlib version 1.2.11 gcc-12.0.1 20220118 (Red Hat 12.0.1-0)

### Java Version

openjdk version "17.0.4.1" 2022-08-12 OpenJDK Runtime Environment (Red_Hat-17.0.4.1.1-1.fc36) (build 17.0.4.1+1) OpenJDK 64-Bit Server VM (Red_Hat-17.0.4.1.1-1.fc36) (build 17.0.4.1+1, mixed mode, sharing)

### OS Version

Fedora 5.19.9-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 15 09:49:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### JDBC driver name and version (include name if unofficial driver)

org.xerial:sqlite-jdbc:3.31.1

**Comment by DaveO-Home** [comment]
This may be related to;  #13826

**Comment by lukaseder** [comment]
Thanks a lot for your report. I've tried a few combinations of versions and configurations, without success. II always got the expected column definition:

```kotlin
val TEST: TableField<T_14001Record, Int?> = createField(DSL.name("test"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")
```

There must be something related to how you create the table, e.g. with:

```
sqlite3 test.db <<EOF
create table test (test integer primary key autoincrement not null);
EOF
```

But perhaps that's not how you did it in your actual test case? How can this be reproduced, e.g. using the `org.xerial` driver alone? We have a template that can be used to create minimal, complete, verifiable examples (MCVE) for reproduction: https://github.com/jOOQ/jOOQ-mcve

**Comment by DaveO-Home** [comment]
I use vert.x, there are too many dependencies to reproduce.  Are you testing against sqlite3? You have to create at least one table with autoincrement to get the problem.  The table that will show up is 'SqliteSequenceRecord'. I see you are using a db with identity, sqlite uses autoincrement. See; https://stackoverflow.com/questions/12785780/sqlite-insert-into-identity-column.
Thanks for reviewing

**Comment by lukaseder** [comment]
I see now. This is about the `sqlite_sequence` table, not the `test` table. It wasn't clear to me at first. Well, SQLite doesn't produce any data types on that:

```sql
select
  name,
  type,
  "notnull",
  dflt_value,
  pk,
  hidden
from pragma_table_xinfo('sqlite_sequence')
where (hidden in (0, 2, 3));
```

Resulting in:

```
|name|type|notnull|dflt_value|pk |hidden|
|----|----|-------|----------|---|------|
|name|    |0      |          |0  |0     |
|seq |    |0      |          |0  |0     |
```

So, what could we possibly do? The table definition from `sqlite_master` yields:

```sql
CREATE TABLE sqlite_sequence(name,seq)
```

Since we can't really make any guesses, `Object` (or kotlin `Any`) is our best guess.

You can either specify the data types in the code generator:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-rewrite/

Or exclude the table from generation output

**Comment by DaveO-Home** [comment]
I was trying to find 'forcedType' in the java program configuration method. Can you provide how to change the code I supplied above for 'forcedType'.  - thanks

**Comment by DaveO-Home** [comment]
This seems to work:
```
 ForcedType ft = new ForcedType();
 ft.setName("BLOB");
 ft.withIncludeExpression("SEQ|NAME");

....
.withDatabase(new Database()
.withForcedTypes(ft)
....

```

**Comment by lukaseder** [comment]
I've just noticed we're excluding this table from our code generation output, explicitly. I suspect we could do this by default in case the `<includeSystemTables/>` flag is set to `false`? See https://github.com/jOOQ/jOOQ/issues/14007

Thoughts on this? Why did you opt for setting the type to `BLOB` rather than just excluding the table? Do you read from it?
