### ISSUE TITLE
Bad table names (lower case / upper case) generated in HSQLDB under some circumstances

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1401]
See this thread for details:

https://groups.google.com/d/topic/jooq-user/qDKCmMI9-14/discussion

**Comment by benallard** [comment]
Copying the solution from the mentioned thread here as well for completeness.

```
Settings s = getSettings(); 
s.setRenderNameStyle(RenderNameStyle.AS_IS); 
```

**Comment by lukaseder** [comment]
@benallard Thanks for your comment. What's the specific issue you were having? This issue here is very old, and I'm not actually sure there is an issue after all...

If you did run into a problem, please create a new issue here on GitHub
