### ISSUE TITLE
Override void insert method of daoImpl class

### ISSUE THREAD

**Issue by Gem-Jasvinder** [jOOQ/jOOQ#14013]
How can we override insert method of DaoImpl class and change its return type to record?
jooq version:3.14.16
Database product and version
Mysql
Java Version
11
OS Version
windows
JDBC driver name and version (include name if unofficial driver)

**Comment by lukaseder** [comment]
Thanks for your message.

You cannot. The more you want to change `DAO`, the more you should consider simply rolling your own. If you look at the code of `DAOImpl`, it's really trivial. All it does is create some convenience on top of ordinary jOOQ API. So your best options are:

- Use ordinary jOOQ API directly (I mean, it's just `ctx.selectFrom(MY_TABLE).fetch()` to produce a `MyTableRecord`!)
- Build your own little library for common tasks

I hope this helps
