### ISSUE TITLE
Feedback about manual section "codegen-extension-postgres"

### ISSUE THREAD

**Issue by jiangtiqiang** [jOOQ/jOOQ#14042]
### The documentation URL

https://www.jooq.org/doc/latest/manual/code-generation/codegen-extensions/codegen-extension-postgres/

### Feedback

hi ,here we have two problems when we use jooq in our project with postgresql,  can you help me ?

1 when we insert a record to postgresql9.2's  table ,  the table have a primary id ,the id is auto increment,  the jooq will 
execute a sql like  :  insert into table(id,name,phone) values (null,'xxx','xxx'), 
then we will get an error. how can we solve this ?

2 when we update a column ,  but the column have  a default value , we set the value to null , the sql:
update table set column=null where id='xxxx';   
we will get an error again. 

is there any way to solve this promlem ?

**Comment by lukaseder** [comment]
Thanks for your message

> 1 when we insert a record to postgresql9.2's table , the table have a primary id ,the id is auto increment, the jooq will
> execute a sql like : insert into table(id,name,phone) values (null,'xxx','xxx'),
> then we will get an error. how can we solve this ?

You're probably including the `ID` column explicitly or implicitly in your jOOQ query in some way. This can happen, for example, if you're using `DSLContext.newRecord(TABLE, pojo)` and you don't have the expected meta data on your `TABLE` (e.g. `NOT NULL` constraint and `DEFAULT` expression / `IDENTITY` flag). Hard to say, of course, without seeing your actual code. (It's always a good idea to show what you're doing *exactly*)

> 2 when we update a column , but the column have a default value , we set the value to null , the sql:
> update table set column=null where id='xxxx';
> we will get an error again.

It's probably the same reason as above. jOOQ does exactly what you tell it to do, explicitly or implicitly.

I'll be able to help you better once you show the exact code you've written.

**Comment by jiangtiqiang** [comment]
this is my code:

  public int addParamItemValue(ParamValueDto paramValueDto) {
        DbParamPropValueRecord paramPropValueRecord = create.newRecord(DB_PARAM_PROP_VALUE);
        BeanUtils.copyProperties(paramValueDto, paramPropValueRecord);
        return paramPropValueRecord.insert();
    }


@Data
public class ParamValueDto {
    private long id;
    private String itemValue;
    private long groupId;
    private String tenantId;
}

when the id's value is null and id is auto increment in postgresql, the jooq will execute:   

**insert into db_param_prop_value(id,item_value,group_id,tenant_id) values (null,'xxx','xxx','xxx')**
 

is there any configuration to tell jooq that we should not insert id column when id is autoincrement, like this ?

**insert into db_param_prop_value(item_value,group_id,tenant_id) values ('xxx','xxx','xxx')**

**Comment by lukaseder** [comment]
This:

```java
BeanUtils.copyProperties(paramValueDto, paramPropValueRecord);
```

Probably sets the ID value to `NULL`. When you do that explicitly, then your intent can only be to include `NULL` in the set of columns to be inserted. If you don't want that, don't set it (or reset it).

If your primary key column is non-null and the generated code has this information along with the identity column information, then jOOQ might be smart about this when copying values into the record. But I can't see what your `BeanUtils` does, so if you explicitly set the ID value, then jOOQ can only think of it as "you *want* this."

There doesn't need to be any such configuration to not do this, because it would be much more sensible to simply not set the ID to `NULL`.
