### ISSUE TITLE
Avoid duplicate bean names in Spring annotations

### ISSUE THREAD

**Issue by sgrimm** [jOOQ/jOOQ#14045]
### Use case

Generated DAOs with Spring annotations should work if there are multiple tables with the same name in different schemas.

Currently, if you have Spring annotations enabled, jOOQ puts `@Repository` on the DAO classes and Spring uses the unqualified class name as the default bean name. When there are two DAO classes with the same names in different packages, Spring treats the collision as an error.

### Possible solution

Explicitly set the bean name in the `@Repository` annotation, and generate a name that avoids these collisions (e.g., prefixing with the catalog/schema names if the table isn't in the default schema).

### Possible workarounds

I was already subclassing `KotlinGenerator` for other reasons, so I turned off the Spring annotation option in the jOOQ codegen configuration and added this to my subclass:

```kotlin
  override fun printClassAnnotations(
      out: JavaWriter,
      definition: Definition,
      mode: GeneratorStrategy.Mode
  ) {
    super.printClassAnnotations(out, definition, mode)

    if (definition is TableDefinition && mode == GeneratorStrategy.Mode.DAO) {
      // Can't call the jOOQ strategy method to generate the DAO class name because it's package-
      // private, so generate it from definition.table.name (which already includes the schema name)
      val beanName =
          definition.table.name.replace(Regex("[._](.)")) { it.groupValues[1].capitalize() } + "Dao"
      out.println("@%s(\"%s\")", out.ref("org.springframework.stereotype.Repository"), beanName)
    }
  }
```

This isn't robust in the face of table names with special characters, and it adds the schema prefix even for the default schema, but for my code base it does the trick.

### jOOQ Version

3.17.4

### Database product and version

PostgreSQL 14.5 (Homebrew)

### Java Version

openjdk version "17.0.4" 2022-07-19 LTS

### OS Version

OS X 12.6

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.0

**Comment by lukaseder** [comment]
Thanks for your report. The best workaround here is to use a generator strategy. That's what they're for:

- Programmatic: https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/
- Configurative: https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/

I'm not sure if jOOQ should handle this out of the box. Bean names may follow some logic and assumptions from user code or Spring itself, and I don't know if jOOQ can find a reasonable default here, that won't lead to yet more trouble. But I won't reject this issue. Keeping it open to collect more user feedback. Perhaps that's something more users will run into, eventually.

Personally, I feel this is a flaw in Spring. The types are fully qualified and clearly distinct, so I think Spring should be able to handle this out of the box, just like class loaders can handle this out of the box. Have you tried reporting it to Spring? It's probably a duplicate (not an unknown problem, e.g. https://stackoverflow.com/q/32265539/521799), but it's always good to remind vendors about pain points.

**Comment by sgrimm** [comment]
You're absolutely right: this is really a Spring problem. And not only that, Spring already has a built-in way to address it, which I totally failed to find before filing this issue. You can set the default bean naming strategy to generate fully-qualified names: https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/FullyQualifiedAnnotationBeanNameGenerator.html

For Spring Boot, you can set the name generator class as a parameter of the `@SpringBootApplication` annotation.

Hopefully that helps someone else who runs into this. I guess given how easy the fix is, there's really no reason jOOQ should do anything to solve this.

**Comment by lukaseder** [comment]
Thanks for the follow-up, @sgrimm. I guess that `FullyQualifiedAnnotationBeanNameGenerator` is the way to go here, it's the simplest approach, and solves the root cause.

In that case, I agree, there's nothing to fix here in jOOQ.
