### ISSUE TITLE
DSL.row() renders as "row(x, y)", but documentation shows it rendered as "(x, y)"

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#14051]
### Expected behavior

With the following code:
```kt
val simpleQuery = select(
    row(
        inline("rows"),
        inline(1)
    )
)

DefaultDSLContext(SQLDialect.POSTGRES, Settings().withRenderFormatted(true))
    .render(simpleQuery)
    .also {
        println(it)
    }
```

Based on the docs here: https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/row-value-expressions/#dialect-support

![image](https://user-images.githubusercontent.com/26604994/194134378-8ad722d9-48fb-4b1c-8755-7175874c2f96.png)

I would expect to see:
```sql
select ('rows', 1)
```

### Actual behavior

Instead I get:
```sql
select row ('rows', 1)
```

### Steps to reproduce the problem

See above

### jOOQ Version

3.18.0-SNAPSHOT Enterprise

### Database product and version

N/A

**Comment by lukaseder** [comment]
Thanks for your report. When https://github.com/jOOQ/jOOQ/issues/11812 was implemented (support for `ROW` projections), some edge cases in integration tests suggested it be better to always generate the `ROW` keyword where supported:

https://github.com/jOOQ/jOOQ-pro/blob/e28c26dc80f82c1ca34bbbec1c0e651ecdf177dc/jOOQ/src/main/java/org/jooq/impl/RowAsField.java#L127-L130

The documentation doesn't document `RowAsField` behaviour, just ordinary `RowImpl` behaviour, where the distinction between `ROW (x)` and `(x)` is irrelevant. I actually thought of adding `ROW` there as well, but you never know what weird regression such a change would produce.

As such, things work as designed. You probably have a different problem in mind than the one you reported. Feel free to report that, too if it's still relevant, though if this is about an unsupported dialect, you probably already know the answer :)
