### ISSUE TITLE
How to remove alias of table?

### ISSUE THREAD

**Issue by pafer001** [jOOQ/jOOQ#14075]
### Your question

sql is
`select  calendar_info.id  from calendar_info`
I need 
`select id  from calendar_info`

how can I do?

 

### jOOQ Version

JOOQ-3.14.15

### Database product and version

Mysql

### Java Version

openjdk version "11.0.3" 2019-04-16

**Comment by lukaseder** [comment]
You're probably looking for this feature: https://github.com/jOOQ/jOOQ/issues/8893

But so far, we haven't seen good reasons to implement it. People usually ask a simplified question like yours, i.e. how to remove the table qualification. But there usually isn't a good reason to do it.

What's your reason?
