### ISSUE TITLE
Add support for the Postgres "DISTINCT ON" clause

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1410]
See an emulation example here:
- http://stackoverflow.com/questions/10515391/oracle-equivalent-of-postgres-distinct-on

And a related thread:
- https://groups.google.com/forum/#!topic/jooq-user/I-JbzaJ56hw

**Comment by enwired** [comment]
Thanks! I was looking for something like this today.
By the way, the Javadocs for SelectDistinctOnStep give an example that seems to be unrelated to "DISTINCT ON".

**Comment by lukaseder** [comment]
Glad it helps! You probably mean the Javadoc of the interface itself? Yes, it's the same for all of the different steps of the DSL. I suspect we could improve those Javadocs. I have created an issue for this: https://github.com/jOOQ/jOOQ/issues/4478
