### ISSUE TITLE
How to abort the execution of SQL during execution?

### ISSUE THREAD

**Issue by tabuyos** [jOOQ/jOOQ#14116]
### Your question

When I detect a special value or symbol, I need to abort the execution of the current SQL immediately, can I do it in the method:`org.jooq.impl.DefaultExecuteListener#executeStart`? How to do it?

### jOOQ Version

3.14.16

### Database product and version

mysql 8.0 by docker

### Java Version

oracleJDK 1.8_341

**Comment by lukaseder** [comment]
Thanks for your message.

Even better than `executeStart()`, you can listen to the `renderEnd()` event and prevent the `Connection::prepareStatement` call and all the bind variable set calls.

You do so by just throwing an exception.
