### ISSUE TITLE
SQLite batch-insert is much slower when using DataSource than when using Connection

### ISSUE THREAD

**Issue by mrieser** [jOOQ/jOOQ#14124]
### Expected behavior

I try to insert a large number (e.g. 50k) of rows into a simple table in SQLite with jOOQ. I expect the performance of the batch-insert to be similar, independent whether I use `DSL.using(dataSource, ...)` or `DSL.using(connection, ...)`.

### Actual behavior

When I use a DataSource object (either `org.sqlite.SQLiteDataSource` or `com.zaxxer.hikari.HikariDataSource`) in `DSL.using(...)`, the batch-insert takes about 30 seconds on my machine.

If I use a Connection object (`java.sql.Connection`) in `DSL.using(...)`, the batch-insert executes in less than 1 second.

When I use JDBC instead of jOOQ, the batch-insert executes in less than 1 second with `setAutoCommit(false); ....; commit();`. **Without disabling** auto-commit, it would also take about 30 seconds. This gives to me the impression that the jooq-transaction is not properly used when a DataSource is used for SQLite.

When using a PostgreSQL database, no performance difference can be noted between using a Connection or a DataSource. So it seems to be specific to SQLite (and maybe other db engines, but certainly not to all).

### Steps to reproduce the problem

I created a small repository with example code: https://github.com/mrieser/sqlite-jooq-test

It uses Maven as build process and dependency management, FlywayDB for the database initialization, TestContainers for testing with PostgreSQL. `mvn clean test` should build everything and run the tests that highlight the problem.

### jOOQ Version

jOOQ Community Edition 3.17.4

### Database product and version

SQLite (org.xerial, 3.39.3.0)

### Java Version

openjdk version "19" 2022-09-20, but also observed with openjdk 17

### OS Version

macOS 12.6

### JDBC driver name and version (include name if unofficial driver)

org.xerial:sqlite-jdbc:3.39.3.0

**Comment by lukaseder** [comment]
Your mistake is here:
https://github.com/mrieser/sqlite-jooq-test/blob/a11726d5dd07a67721dda7f797fb58b33e3ce5f7/src/main/java/SqliteDB.java#L153-L158

You're not using the argument `Configuration c` from the lambda, which is the transactional configuration. You're using the outer `db()` reference again, which isn't transactional, so you're obtaining a new `Connection` for the batch.

Can you try again after fixing this?

**Comment by mrieser** [comment]
Thank you for the feedback! Indeed, using `c.dsl()` instead of `db()` fixed the issue.

Sorry, I must have missed that part when reading about transactions in jOOQ.

And interesting that this "api-misuse" manifested only in this very specific setting, but not in others.

**Comment by lukaseder** [comment]
> And interesting that this "api-misuse" manifested only in this very specific setting, but not in others.

You would have noticed eventually, because of wrong transactional behaviour 😬
