### ISSUE TITLE
sentinel-reactor-adapter使用中异步线程调用ContextUtil.getContext()报NullPointerException

### ISSUE THREAD

**Issue by vancaraka** [jOOQ/jOOQ#14122]
### Your question

使用sentinel-reactor-adapter做reactor模式请求的熔断，请求进入sentinel的entry是一个线程，异常处理为另一个线程，请问我希望从异常处理的线程中获取Context该如何做？有没有已经有的接口或方法可以实现

### jOOQ Version

none

### Database product and version

none

### Java Version

jdk 1.8

**Comment by lukaseder** [comment]
I'm sorry, no Chinese speakers here...
