### ISSUE TITLE
InsertValueStepN.columns does not accept an array which results in mandatory toList conversion

### ISSUE THREAD

**Issue by TheBestPessimist** [jOOQ/jOOQ#14128]
### Your question

Please see the link here: https://github.com/TheBestPessimist/Youtube-Subscriptions-Mailer/blob/ecfa81ae5828bfd371da77540a7412178ce12267/src/main/kotlin/land/tbp/youtube/YoutubeService.kt#L50-L58

_(still learning jooq here)_

I am trying to learn how to insert many lines with jooq, and reading the github (somehow the website documentation is so large that i cannot find what i'm looking for there :D) i come upon `.valuesOfRecords()` in [this issue](https://github.com/jOOQ/jOOQ/issues/11758).

The suggestion is : `dsl.insertInto(table).columns(table.fields()).valuesOfRecords(records).SQL`.

The suggestion above doesn't look very nice to me in Kotlin because `table.fields()` returns an array, while `.colums` expects a list. So i need to change my array to a list instead:

```kotlin
        ctx.dsl().insertInto(SUBSCRIPTION)
            .columns(SUBSCRIPTION.fields().asList())
            .valuesOfRecords()
            .execute()
```

Is this something that should/could be improved?

### jOOQ Version

OSS 3.17.4

### Database product and version

sqlite 3.39.2

### Java Version

temurin 18

### OS Version

Windows 10 LTSC

### JDBC driver name and version (include name if unofficial driver)

org.xerial:sqlite-jdbc:3.39.3.0

**Comment by lukaseder** [comment]
Ah, I see now, you're using kotlin. In Java, you can just pass `fields()` to the `columns(Field<?>...)` method. I don't see into kotlin well enough to comment on why they didn't just support the very same syntax for arrays/varargs as in Java, at least whenever Java interoperability is concerned. I think you can just turn the array into a varargs argument using `*SUBSCRIPTION.fields()`? Or, you use `asList()`.

I'm not sure what could be improved here on the jOOQ side... It isn't just about the `columns()` method. This will happen time and again throughout jOOQ API, which accepts `Collection<? extends T>` and `T...` varargs as alternative overloads.

Any specific suggestions for improvement?

**Comment by TheBestPessimist** [comment]
First, thanks for reminding me of the spread operator. That works nicely.

One other thing which works nicely is an extension function to do that for me:

```kotlin
fun <R : Record> InsertSetStep<R>.columns(fields: Array<Field<*>>): InsertValuesStepN<R> = this.columns(*fields)
```

usage:
```kotlin

        ctx.dsl().insertInto(SUBSCRIPTION)
            .columns(SUBSCRIPTION.fields()) 
            .valuesOfRecords()
            .execute()
```

Would this be something you'd consider adding to jooq-kotlin? Would you accept a PR?

**Comment by lukaseder** [comment]
Thanks for the hint. Might be an option, though I'll have to investigate the possible edge cases of doing this, first. Surely, adding an additional overload, while solving this problem, will introduce another.

**Comment by lukaseder** [comment]
Noting that `Fields.fields()` may be one of the very few places where jOOQ actually returns an array, so possibly, this really isn't worth it.

**Comment by lukaseder** [comment]
After some additional consideration, I don't want to address anything here. This is a kotlin specific problem, and it probably only relates to using `Fields.fields()`. It's annoying, sure, but unless there's a simple fix (which I don't see yet), I don't want to address it. Adding 100s of extension functions doesn't scale. Adding an extension function only for this particular case also doesn't scale.
