### ISSUE TITLE
Wrong descriptions in manual section "codegen-extension-postgres"

### ISSUE THREAD

**Issue by marek-klima** [jOOQ/jOOQ#14126]
### The documentation URL

https://www.jooq.org/doc/latest/manual/code-generation/codegen-extensions/codegen-extension-postgres/

### Feedback

Currently the doc is displaying this info (among others):
- citext is a label tree data structure.
- ltree is "case insensitive text".

These are mixed (`ltree` is data structure, `citext` is text).

**Comment by lukaseder** [comment]
Thanks a lot. Fixed. The manual will be updated within 1-2h
