### ISSUE TITLE
Wrong claims about SQL standard optional FROM clause in manual

### ISSUE THREAD

**Issue by wfhartford** [jOOQ/jOOQ#14130]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-building/table-expressions/dual/

### Feedback

This page appears to have contradictory information. I could be interpreting the text incorrectly, but it appears that these to sentences contradict each other:
* The first sentence on the page: _The SQL standard specifies that the FROM clause is optional in a SELECT statement._
* The first following bullet point: _The ones that always require a FROM clause (as required by the SQL standard)_

**Comment by lukaseder** [comment]
Thanks for your report. That text is clearly incorrect. The SQL standard has a mandatory `FROM` clause.

**Comment by lukaseder** [comment]
Fixed. The manual will be updated within 1-2h. Thanks again.
