### ISSUE TITLE
Typo in window function section of the manual

### ISSUE THREAD

**Issue by kokrui** [jOOQ/jOOQ#14182]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/window-functions/

### Feedback

Just a tiny typo -- `percentileDisc` is spelled `precentileDisc` and `percentileCont` is spelled `precentileCont` in the first code block
<img width="725" alt="image" src="https://user-images.githubusercontent.com/29654756/200566740-74cb5315-69e5-4648-bb55-26d07a04b43d.png">

**Comment by kokrui** [comment]
Went to check the rest of the repo for similar typos, found one in DSL on line 29245 -- will PR that!

**Comment by lukaseder** [comment]
Thanks a lot for letting us know. This is fixed. The manual will be updated within ~1h
