### ISSUE TITLE
How to inject a custom ID (distributed ID) into the primary key(non auto increment) field when inserting?

### ISSUE THREAD

**Issue by tabuyos** [jOOQ/jOOQ#14229]
### Your question

Hi @lukaseder  

I'm new to JOOQ and I have some questions.

1. How to inject a custom ID (distributed ID) into the primary key(non auto increment) field when inserting?
2. Why does the VisitListener SPI execute twice?
3. How to get all the fields and tables of the current statement?
4. How to get the inserted object (`returning().fetchOne()` always returns null)

For the first question, I use the VisitListener SPI to be implement, the process of implementing this feature is too
hard, but due to the second question, my ID will be generated twice.

I am sorry for my English ability and expressiveness.

always returns null(primary key is non-auto-increment)

<img width="577" alt="image" src="https://user-images.githubusercontent.com/45193148/202151872-ecf08116-02d2-49c2-8aa5-50cc05d19d95.png">

my IdVisitListener:

```java
private static final Logger recorder = Recorder.getLogger(IdVisitListener.class);

  private final WillowService willowService;

  private InsertQuery<?> insertQuery;
  private boolean startInsert = false;
  private Long primaryKey = null;

  public IdVisitListener(WillowService willowService) {
    this.willowService = willowService;
  }

  private void renderPrimaryKey(VisitContext context) {
    if (!startInsert) {
      return;
    }
    if (context.clause() == Clause.TABLE_REFERENCE) {
      QueryPart queryPart = context.queryPart();
      if (queryPart instanceof Table) {
        Table<?> table = (Table<?>) queryPart;
        String schemaName =
            context.settings().isRenderSchema()
                ? Optional.ofNullable(table.getSchema()).map(Named::getName).orElse(null)
                : null;
        Field<Object> primaryKeyField = DSL.field(DSL.name(schemaName, table.getName(), "id"));
        Optional.ofNullable(context.renderContext())
            .map(Context::paramType)
            // .filter(type -> type == ParamType.INDEXED)
            .ifPresent(
                type -> {
                  primaryKey = Optional.ofNullable(primaryKey).orElseGet(willowService::getId);
                  recorder.info("generate primary key: {}", primaryKey);
                });
        insertQuery.addValue(primaryKeyField, primaryKey);
      }
    }
  }

  private void captureInsertQuery(VisitContext context) {
    if (!startInsert) {
      return;
    }
    if (context.clause() == Clause.INSERT_INSERT_INTO) {
      QueryPart queryPart = context.queryPart();
      if (queryPart instanceof InsertQuery) {
        insertQuery = (InsertQuery<?>) queryPart;
      }
    }
  }

  @Override
  public void clauseStart(VisitContext context) {
    if (context.clause() == Clause.INSERT) {
      startInsert = true;
    }
    captureInsertQuery(context);
  }

  @Override
  public void visitStart(VisitContext context) {
    renderPrimaryKey(context);
  }
```

### jOOQ Version

3.14.16

### Database product and version

mysql 8.0 by docker

### Java Version

oracleJDK 1.8_341

**Comment by lukaseder** [comment]
Thanks for your message

> 1. How to inject a custom ID (distributed ID) into the primary key(non auto increment) field when inserting?

I'm not sure I understand what the problem here is. You just add it to the `VALUES()` clause...

> 2\. Why does the VisitListener SPI execute twice?

Can you share some more details about this observation. The most probable cause is that we have 2 types of `org.jooq.Context`:

- `RenderContext` renders SQL
- `BindContext` binds bind values

> 3\. How to get all the fields and tables of the current statement?

The easiest way would be to use the query object model traversal API, which is still experimental in jOOQ 3.17 / 3.18, but it's the most powerful and also the simplest approach:
https://www.jooq.org/doc/latest/manual/sql-building/model-api/model-api-traversal

What you're doing depends on new work implemented only in jOOQ 3.18 (`INSERT` statement support, `JOIN` traversal support).

You can obviously use a `VisitListener` as well, but as you've noticed, it's much harder to get right.

> 4\. How to get the inserted object (`returning().fetchOne()` always returns null)

Depending on the dialect, `returning()` only works in the presence of an identity column that is known to jOOQ. You mentioned you didn't have a MySQL `AUTO_INCREMENT` column, so I'm afraid you won't be able to use this clause with jOOQ on MySQL.

**Comment by tabuyos** [comment]
> Thanks for your message
> 
> > 1. How to inject a custom ID (distributed ID) into the primary key(non auto increment) field when inserting?
> 
> I'm not sure I understand what the problem here is. You just add it to the `VALUES()` clause...
> 
> > 2. Why does the VisitListener SPI execute twice?
> 
> Can you share some more details about this observation. The most probable cause is that we have 2 types of `org.jooq.Context`:
> 
> * `RenderContext` renders SQL
> * `BindContext` binds bind values
> 
> > 3. How to get all the fields and tables of the current statement?
> 
> The easiest way would be to use the query object model traversal API, which is still experimental in jOOQ 3.17 / 3.18, but it's the most powerful and also the simplest approach: https://www.jooq.org/doc/latest/manual/sql-building/model-api/model-api-traversal
> 
> What you're doing depends on new work implemented only in jOOQ 3.18 (`INSERT` statement support, `JOIN` traversal support).
> 
> You can obviously use a `VisitListener` as well, but as you've noticed, it's much harder to get right.
> 
> > 4. How to get the inserted object (`returning().fetchOne()` always returns null)
> 
> Depending on the dialect, `returning()` only works in the presence of an identity column that is known to jOOQ. You mentioned you didn't have a MySQL `AUTO_INCREMENT` column, so I'm afraid you won't be able to use this clause with jOOQ on MySQL.

Thank you for your reply

<img width="672" alt="image" src="https://user-images.githubusercontent.com/45193148/202161343-c4c95f29-a69d-4c7d-8d5c-aca86c083ede.png">

I added two output prints, besides my ID is generated twice, I also noticed a difference in renderContext: parameters are INDEXED and INLINED Is this the cause of this problem?

>  >1. How to inject a custom ID (distributed ID) into the primary key(non auto increment) field when inserting?

> I'm not sure I understand what the problem here is. You just add it to the VALUES() clause...

I have a lot of Record objects, I can't execute `values()` for each object (because there are too many), so I want to automatically inject an ID value for my primary key by intercepting, for this I specifically implemented an `IdVisitListener` SPI, like the code I posted, but because it was executed twice, causing my ID to be generated repeatedly.

**Comment by lukaseder** [comment]
> I added two output prints, besides my ID is generated twice, I also noticed a difference in renderContext: parameters are INDEXED and INLINED Is this the cause of this problem?

You're deep down inside of a debugging session, which I cannot access. It's hard to answer such questions, sorry...

Our issue template suggests creating an MCVE (minimum complete verifiable example, template here: https://github.com/jOOQ/jOOQ-mcve) to make sure we can discuss the same things.

Especially when talking about something as complex as the `VisitListener`, it would be very hard to answer a question without being able to reproduce the *exact* behaviour you're seeing.

> I have a lot of Record objects, I can't execute `values()` for each object (because there are too many), so I want to automatically inject an ID value for my primary key by intercepting, for this I specifically implemented an `IdVisitListener` SPI, like the code I posted, but because it was executed twice, causing my ID to be generated repeatedly.

So, then you already have your answer about that particular question. E.g. use a `VisitListener`. Now there's only the question remaining how you can recognise which one of the two traversals is the one relevant to you.

**Comment by tabuyos** [comment]
Thank you very much for your timely reply.

For the previous question(use custom `ID` to autofill a primary key), I have already implemented it in other ways: implement a default `insert(Record record)` method in the interface, aha, there is nothing that cannot be solved by adding an intermediate layer, how can it be wrong? The main reason is that I am not familiar with `JOOQ` :)

Thank you again and your team for `JOOQ`

非常感谢您, 以及您的团队为`JOOQ`所做出的贡献和努力
