### ISSUE TITLE
Syntax error when from current_timestamp when precision bind value is specified for Postgres

### ISSUE THREAD

**Issue by lukas-krecan** [jOOQ/jOOQ#14256]
### Expected behavior

I am using `currentLocalDateTime(6)`. When used on Postgress (with Postgress dialect) I expect it to ignore the precision and use `current_timestamp` literal. It genrates the function most likely due to the fact that Postgres is missing in  `CurrentTimestamp.NO_SUPPORT_PRECISION`

### Actual behavior

Fails with Syntax error 

```
STATEMENT:  insert into "shedlock" ("locked_by", "name", "lock_until", "locked_at") values ($1, $2, (current_timestamp($3) + cast($4 as interval day to second)), current_timestamp($5)) on conflict do nothing[\n]"
ERROR:  syntax error at or near "$3" at character 108
```

### Steps to reproduce the problem

Use `currentLocalDateTime(6)` in insert on Postgres. 

### jOOQ Version

3.17.5 Open source

### Database product and version

Postgres 13

**Comment by lukaseder** [comment]
Thanks for your report. We should inline that value for you, but you can already do that yourself using `currentLocalDateTime(inline(6))`

**Comment by lukas-krecan** [comment]
Thanks, `inline` indeed helped.

**Comment by lukaseder** [comment]
Fixed in versions

- 3.19.0
- 3.18.8 (https://github.com/jOOQ/jOOQ/issues/15747)
- 3.17.17 (https://github.com/jOOQ/jOOQ/issues/15748)
- 3.16.23 (https://github.com/jOOQ/jOOQ/issues/15749)
