### ISSUE TITLE
How-to: Fold over arbitrary-length list to assemble a UNION

### ISSUE THREAD

**Issue by SebastianKG** [jOOQ/jOOQ#14260]
### Your question

I'm interested in how I can express the following `UNION` query using `fold` (in Kotlin, but there is a Java equivalent of course):

``` kotlin
db.select().from(Tables.TOPICS).orderBy(Tables.TOPICS.ID).limit(3)
    .union(db.select().from(Tables.TOPICS).orderBy(Tables.TOPICS.ID).limit(3))
    .union(db.select().from(Tables.TOPICS).orderBy(Tables.TOPICS.ID).limit(3))
```

I tried to write it like so:

``` kotlin
listOf(3, 3).fold(
    db.select().from(Tables.TOPICS).orderBy(Tables.TOPICS.ID).limit(3)
) { acc, it ->
    acc.union(
        db.select().from(Tables.TOPICS).orderBy(Tables.TOPICS.ID).limit(it)
    )
}
```

...but I get the compiler error:

```
Type mismatch.
Required:
SelectLimitPercentStep<Record!>
Found:
SelectOrderByStep<Record!>
```

I understand that this is because the initial value for the fold is a query (potentially) awaiting a limit-percent, while the union (the accumulator in the fold) could take an order-by next, but I cannot seem to wrap either the accumulated value nor the initial value to match each others' type and make the fold possible. Is there a way of doing this that I'm not aware of? Thank you for your help.

### jOOQ Version

org.jooq:jooq:3.16.6

### Database product and version

PostgreSQL 13.6 (Ubuntu 13.6-1.pgdg20.04+1+b1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit

### Java Version

openjdk version "11" 2018-09-25

### OS Version

Ubuntu 20.04.4 LTS

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.4.0

**Comment by lukaseder** [comment]
Thanks for your message. It seems this is because of `fold()` being invariant with respect to its generic type variables, combined with limitations of type inference in kotlin? You probably have to hint the type of `acc` in your case:

```kotlin
listOf(3, 3).fold(
    db.select().from(Tables.TOPICS).orderBy(Tables.TOPICS.ID).limit(3)
) { acc: Select<Record>, it ->
    acc.union(
        db.select().from(Tables.TOPICS).orderBy(Tables.TOPICS.ID).limit(it)
    )
}
```

But rather than fold, why not map and reduce?

```kotlin
listOf(3, 3)
    .map { db.select().from(Tables.TOPICS).orderBy(Tables.TOPICS.ID).limit(it) as Select<Record> }
    .reduce { a, b -> a.union(b) }
```

Still needs an upcast or type hints for the same reason, though. Which is regrettable, Java doesn't require such hints in this particular case:
https://blog.jooq.org/map-reducing-a-set-of-values-into-a-dynamic-sql-union-query/

I hope this helps
