### ISSUE TITLE
Field::contains should implement PostgreSQL @> also for JSONB types

### ISSUE THREAD

**Issue by saibotma** [jOOQ/jOOQ#14262]
### Use case

@> can be GIN-Indexed and thus useful to quickly lookup if a key-value pair exists.

### jOOQ Version

jOOQ Community 3.17.5

### Database product and version

Postgres 15 and older

**Comment by lukaseder** [comment]
Thanks for your report. We already support it via `Field.contains()`, though only for arrays. Did you have something else in mind?

**Comment by lukaseder** [comment]
Makes sense, thanks. Yes it compiles but generates a string contains implementation, i.e. `arg1 like '%' || arg2 || '%'`. It certainly makes sense to retrofit this for `JSON` and `JSONB`

**Comment by saibotma** [comment]
Thanks for the information. That means the current workaround is to use jOOQ's plain SQL support?

**Comment by lukaseder** [comment]
Yes

**Comment by lukaseder** [comment]
Will implement native support only for now. Emulations could be done separately: https://github.com/jOOQ/jOOQ/issues/14264, though they're probably not so simple.

**Comment by saibotma** [comment]
Wow, that was fast!
