### ISSUE TITLE
Median emulation ignores FILTER and OVER clauses

### ISSUE THREAD

**Issue by valenterry** [jOOQ/jOOQ#14276]
### Expected behavior

When using `median($field).filterWhere(condition)` with Postgres Dialect, the filter-condition should either be applied or it should not compile or at least an error should be thrown.

There should also be a way to opt out of the median emulation for higher postgres version where median can be used.

### Actual behavior

When using `median($field).filterWhere(condition)` the condition is simply ignored when median is emulated with percentiles, leading to a wrong result

### Steps to reproduce the problem

Use `median($field).filterWhere(condition)` anywhere in a query.

See also: https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/impl/Median.java#L97

### jOOQ Version

3.17.3

### Database product and version

Postgres 13

### Java Version

17

### OS Version

Any

### JDBC driver name and version (include name if unofficial driver)

Any

**Comment by lukaseder** [comment]
Thanks a lot for your report. Will look into this right away.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0, 3.17.6 (https://github.com/jOOQ/jOOQ/issues/14277), and 3.16.12 (https://github.com/jOOQ/jOOQ/issues/14278)

**Comment by lukaseder** [comment]
Thanks again for your report.

Until this is released, the workaround is to use `PERCENTILE_CONT` directly.

**Comment by lukaseder** [comment]
For the record, the `OVER ()` clause was also being ignored, in case `MEDIAN` was used as window function.

**Comment by valentin-panalyt** [comment]
Thanks for the super quick fix and workaround, I appreciate it a lot!
