### ISSUE TITLE
Kotlin Value Classes in Constructor lead to name based mapping failure

### ISSUE THREAD

**Issue by F43nd1r** [jOOQ/jOOQ#14283]
### Expected behavior

DefaultRecordMapper should map primary constructors with kotlin value class parameters by name.

### Actual behavior

DefaultRecordMapper map primary constructors with value class parameters by index.

This is caused by a failure of https://github.com/jOOQ/jOOQ/blob/eea0e6191135ee3bb9d0e0066cc43265644a4a56/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java#L508 because a nonnullable value class is represented by the primitive type it wraps in java.

Most likely the code in https://github.com/jOOQ/jOOQ/blob/eea0e6191135ee3bb9d0e0066cc43265644a4a56/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java#L491 should be adjusted to consider value classes

### Steps to reproduce the problem

 ```kotlin
@JvmInline
value class Baz(val value: Int)

class Foo(val bar: Int, val baz: B)

jooq.select(FOO.BAZ, FOO.BAR).from(FOO).fetchInto(Foo::class.java)
```
this will result in bar and baz values being switched due to the aforementioned failure to identify the constructor of Foo with parameter names and the fallback to index based injection.

### jOOQ Version

jOOq community 3.17.5

### Database product and version

mysql 8.0.31

### Java Version

openjdk version "17.0.5" 2022-10-18

### OS Version

Arch Linux

### JDBC driver name and version (include name if unofficial driver)

com.mysql:mysql-connector-j:8.0.31

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll look into this right away

**Comment by lukaseder** [comment]
Yeah, I can confirm, your assessment is correct. We're getting a reference to the value class `Baz` using kotlin's reflection APIs, but jOOQ should never see that class, and work only with the type of its value (recursively, in case a value class wraps another value class)
