### ISSUE TITLE
Parentheses in WITH + UNION triggers bug in mysql-connector-j

### ISSUE THREAD

**Issue by Taraxul** [jOOQ/jOOQ#14358]
### Steps to reproduce the problem

This issue might be a bit niche: it isn't directly jOOQ's fault, and seems to exist at an intersection of MySQL, jOOQ and JPA/Hibernate. Sorry if this is inappropriate to report here, I was hoping to find if there was anything that could be done from jOOQ's side.

**The mysql-connector-j side:**
In the connector, the context of a WITH statement is scanned as the first valid _unparenthesised_ keyword (eg. SELECT) to determine if the query will return results. If it doesn't recognise a valid keyword, it throws java.sql.SQLException: Statement.executeQuery() cannot issue statements that do not produce result sets, and won't execute the statement.

Because of a bug in the connector (https://bugs.mysql.com/bug.php?id=108195) affecting at least versions 8.0.29, 30 and 31, the keyword UNION isn't recognised - if it's found, it will refuse to execute.

**The jooq side:**
When using withRecursive() followed by a select() that includes a union(), jOOQ wraps the first SELECT statement after WITH in parentheses, eg:

WITH RECURSIVE cte AS (...)
(SELECT ...)
UNION (SELECT ...)

The parentheses around the SELECT on the second line push the connector's WITH context detection down to 'UNION' instead, which it doesn't consider to be a form that returns results. This causes the connector to throw the exception above.

**The JPA/Hibernate side:**
The bug report mentions using execute() instead of executeQuery() as a workaround, but unfortunately for my case this query is being passed through JPA as a native query, where the specific connector method is outside of my control.

I appreciate this is probably a very edge case, but I'm at a loss as to how to work around the issue in this configuration. Is there a way to get jOOQ to not generate parentheses around the first SELECT statement here, or should I be looking for another way to get JPA/Hibernate to run the workaround execute* method while still loading the results into entities?

### jOOQ Version

jOOQ open source 3.17.5

### Database product and version

MySQL 8.0.30 via official Docker image

### Java Version

Oracle OpenJDK 17.0.2

### JDBC driver name and version (include name if unofficial driver)

mysql:mysql-connector-java:8.0.29 + 8.0.30 + 8.0.31

**Comment by Taraxul** [comment]
Not sure if it helps, but I tracked back through the connector versions and this problem was introduced in 8.0.27, so it affects all connector versions since October 2021.

**Comment by lukaseder** [comment]
Thanks for your detailed report.

This doesn't affect execution from within jOOQ. We've been integration testing with the connector version 8.0.28, so we'd have noticed. The reason is that we call `Statement::execute` in order to be able to fetch all interleaved update counts, exceptions, and other result sets, that might be generated by triggers and what not.

Why are you using Hibernate to execute jOOQ queries? You're forgoing a lot of cool jOOQ features this way, including e.g. `MULTISET`: https://blog.jooq.org/jooq-3-15s-new-multiset-operator-will-change-how-you-think-about-sql, Spatial queries, everything that has to do with custom `Converter` or `Binding` types, etc.

Since this doesn't affect jOOQ execution, and is a severe MySQL connector problem, which ought to be fixed there with high priority, I'm closing this issue as won't fix.

A workaround could be to wrap such queries in derived tables:

```java
// instead of:
ctx.with("cte").as(selectZero()).selectOne().union(selectZero()).fetch()

// write:
ctx.with("cte").as(selectZero()).selectFrom(selectOne().union(selectZero())).fetch()
```

But I'd really just execute queries with jOOQ directly.

**Comment by Taraxul** [comment]
Hi Lukas, thanks for taking a look.

Using JPA's EntityManager to load JPA entities is part of jooq's user guide (https://www.jooq.org/doc/latest/manual/sql-execution/alternative-execution-models/using-jooq-with-jpa/using-jooq-with-jpa-entities/). I was under the impression this was needed to load deep relationships present in the original query result.

We chose this method quite a while ago so it's entirely possible I've missed something important in jooq's capabilities either then or since. I'll take another look through the docs and run some experiments to see if jooq can handle that aspect directly instead.

Agreed on this being a pretty important MySQL connector bug, but it seems their team hasn't touched it in months so figured I'd check in here first. Thanks again for your help!

**Comment by lukaseder** [comment]
> Using JPA's EntityManager to load JPA entities is part of jooq's user guide (https://www.jooq.org/doc/latest/manual/sql-execution/alternative-execution-models/using-jooq-with-jpa/using-jooq-with-jpa-entities/). I was under the impression this was needed to load deep relationships present in the original query result.

It's possible to do this, yes. If you're fetching entities, then this approach might work well for you, indeed. Though, given that you're using a `UNION`, I wonder if you're really fetching entities?

Anyway, I didn't want to judge, sorry, if it came across this way. While it's possible to use jOOQ only as a SQL builder and execute things elsewhere, there are limitations, and I'm always curious about why people choose this approach.

I'll update the manual making sure it's understood that this isn't a recommended way to use jOOQ, it's just a possible way. I'll post an update here, once that section (and possibly a blog post highlighting all the benefits of executing things with jOOQ directly) is ready.

For the time being, did the derived table workaround work for you?

**Comment by Taraxul** [comment]
Confirming the derived table workaround you provided does solve the problem in connector 8.0.31. Thanks again for your help, Lukas!

**Comment by lukaseder** [comment]
Thanks for the confirmation and the example. I guess it does make sense to project entities this way
