### ISSUE TITLE
Case-sensitivity option in DSL.orderBy() API. MySQL doesn't preserve case, requires `ORDER BY BINARY` for case-sensitive ordering.

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#14367]
### Use case

It'd be nice to have a generic way to specify case-sensitivity behavior for ordering expressions.
Ran into some unexpected behavior where our `order_by` tests for MySQL dialect were failing, and it turned out to be because of:

![image](https://user-images.githubusercontent.com/26604994/205738472-42877a67-66ab-4a8e-9bd3-4956cc4e41d2.png)

It'd be nice to be able to write e.g.

```kt
when (elem.order_direction) {
    OrderDirection.ASC -> field.asc().nullsLast().caseSensitive()
    OrderDirection.DESC -> field.desc().nullsFirst().caseSensitive()
}
```

Semantically, this information is part of the `ORDER BY`'s `collation` property.
- https://stackoverflow.com/a/49740037/13485494

I'm not sure where the proper place for something like this is in jOOQ's query model.

Here's a hacky prototype idea:

```kt
// Example:
//  SELECT * FROM t ORDER BY BINARY a, BINARY b, c;
fun <T : Field<*>> caseSensitiveOrderByField(field: T, caseSensitive: Boolean): CustomField<*> {
    return CustomField.of("case_sensitive_order_by_field", field.dataType) { ctx ->
        when (ctx.dialect().category()) {
            org.jooq.SQLDialectCategory.MYSQL -> {
                if (caseSensitive) {
                    ctx.visit(DSL.field("BINARY {0}", field.dataType, field))
                } else {
                    ctx.visit(field)
                }
            }

            else -> ctx.visit(field)
        }
    }
}
```

### jOOQ Version

3.18.0-SNAPSHOT Enterprise

### Database product and version

n/a

**Comment by lukaseder** [comment]
Thanks for your suggestion.

jOOQ supports the ISO/IEC 9075-2:2016(E) 10.7 &lt;collate clause>, which seems to be a more appropriate way to do this in general, see also:
https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#cast-character-set-conversions

Use e.g. `field.collate("utf8mb3_bin")`

**Comment by lukaseder** [comment]
See also:
https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/collations/
