### ISSUE TITLE
Slow TableAlias::equals implementation, when argument type is TableImpl

### ISSUE THREAD

**Issue by juriad** [jOOQ/jOOQ#14371]
### Expected behavior

I want to `get` value out of a `Record` by a `Field` fast - it should not matter how the `Field` is constructed.

### Actual behavior

Getting a value out of a record (a generic record) based on a field hugely depends on the qualification of fields.

Problematic:
![image](https://user-images.githubusercontent.com/886346/205876268-cdb5b113-4f00-464a-b2ec-49bc61ba892c.png)

It all comes down to `TableField.equals` that compares the `Table`s:
```
StringUtils.equals(getTable(), other.getTable())
```

`AbstractNamed` already has a fast exit:
```
    @Override
    public boolean equals(Object that) {
        if (this == that)
            return true;
        if (that == null)
            return false;

        // [#2144] Non-equality can be decided early, without executing the
        // rather expensive implementation of AbstractQueryPart.equals()
        if (that instanceof AbstractNamed)
            if (!getQualifiedName().equals(((AbstractNamed) that).getQualifiedName()))
                return false;

        return super.equals(that);
    }
```
But it still goes up to the generic `org.jooq.impl.AbstractQueryPart#equals` where rendering is involved.

It seems to me that two tables (and possibly other named things) could be compared just by their qualified names.

I have my fix (see below), and it works for me, I am pretty sure that is not how iOOQ should be used. After the fix, the section from the screenshot took only 126 ms, with `IndexCachingAccessor` taking 40 ms and jOOQ not even shown in the profiler.

I just wanted to show a place that looks quite easy to optimize.

### Steps to reproduce the problem

We have a dynamic schema and generate our queries in layers (conceptually):

```
DATA = select * from data_table where record_type = $type
PERM = select * from P join data_table_permissions where allowed_roles && $roles
AS_CHILD = select * from PERM join (some parent query) on id = parent_id
COMPUTED = select *, c1, c2, c3 from AS_CHILD join ... join ...
FILTERED = select * from AS_CHILD join t1 join t2, join t3 where ... and t1... and t2... and t3...
UNPAGED = select *, row_number() over (partition by parent_id) from FILTERED 
select * from UNPAGED where rn <= 10
```

At any level, we may need to refer to any original field from data_table or a previously computed field (such as c1).
Each of the capitalized selects is in fact `Table<Record>` after calling `Select.asTable(String)`.

Profiler shows us that a lot of time is spent in `Table.field(Field)` which we need because the field needs to be correctly qualified - we cannot refer to `data_table.parent_id` on `FILTERED` - we need `FILTERED.parent_id` instead. We wrote a tiny function:
```
    public static <T> Field<T> fqn(Table<?> table, Field<T> field) {
        return DSL.field(DSL.name(table.getName(), field.getName()), field.getDataType());
    }
```

That does the translation much faster - there is no looping over all fields in the table - see `org.jooq.impl.FieldsImpl#field0(org.jooq.Field<?>, org.jooq.impl.FieldsImpl.FieldOrIndex<U>)`

This fixed some issues and created new ones. `Record.get(Field)` is slow. The issue is very similar - there is looping - and expensive(!) equality on `TableFieldImpl`. Specifically `StringUtils.equals(getTable(), other.getTable())` is slow when one is `TableAlias` (for the `Field` inside returned `Record`) and the other is `TableImpl` (created by our `fqn` function).

We overcame this issue too:
```
    class IndexCachingAccessor {
        private final IdentityHashMap<Field<?>, Integer> cache = new IdentityHashMap<>();

        public <T> T get(Record r, Field<T> field) {
            Integer index = cache.computeIfAbsent(field, f -> r.indexOf(field.getName()));
            return (T) r.get(index);
        }
    }
```
We never return two columns of the same name, so we can avoid comparison of the tables - just field names are enough. Moreover, by caching the index of the `Field` per `Query` we make getting data from the Nth record much faster than any `Field`-based method could provide.

### jOOQ Version

3.16.5 pro

### Database product and version

Postgres

### Java Version

openjdk version "11.0.12" 2021-07-20

### OS Version

Linux

**Comment by juriad** [comment]
This demonstrates the issue.
I am getting these results on my machine:
```
Benchmark                      Mode  Cnt     Score     Error  Units
AliasTest.by_identity          avgt    5     3.581 ±   0.404  ns/op
AliasTest.by_index             avgt    5     1.567 ±   0.119  ns/op
AliasTest.by_name1             avgt    5    11.656 ±   2.978  ns/op
AliasTest.by_name2             avgt    5    12.477 ±   4.354  ns/op
AliasTest.original_by_wrapped  avgt    5    66.798 ±   5.907  ns/op
AliasTest.super_slow           avgt    5  1193.775 ± 516.623  ns/op
AliasTest.wrapped_by_original  avgt    5    31.611 ±   4.137  ns/op
```


```
package org.jooq.mcve.test.java;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.concurrent.TimeUnit;

import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.openjdk.jmh.annotations.Scope;
import org.openjdk.jmh.annotations.*;
import org.openjdk.jmh.infra.Blackhole;
import org.openjdk.jmh.runner.Runner;
import org.openjdk.jmh.runner.options.Options;
import org.openjdk.jmh.runner.options.OptionsBuilder;

import static org.jooq.mcve.java.tables.Test.TEST;

@State(Scope.Benchmark)
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@Warmup(iterations = 1, time = 100, timeUnit = TimeUnit.MILLISECONDS)
@Measurement(iterations = 5, time = 100, timeUnit = TimeUnit.MILLISECONDS)
public class AliasTest {
    private DSLContext ctx;

    private Record record1;
    private Record record2;
    private Field<Integer> af;
    private Integer index;

    @Setup(Level.Trial)
    public void setup() throws SQLException {
        System.getProperties().setProperty("org.jooq.no-logo", "true");
        System.getProperties().setProperty("org.jooq.no-tips", "true");

        var connection = DriverManager.getConnection("jdbc:postgresql://localhost:5431/postgres", "postgres", "postgres");
        ctx = DSL.using(connection);

        ctx.meta(TEST).ddl(new DDLExportConfiguration().createSchemaIfNotExists(true).createTableIfNotExists(true)).executeBatch();

        ctx.deleteFrom(TEST).execute();
        ctx.insertInto(TEST).columns(TEST.ID).values(42).execute();

        SelectJoinStep<Record> select = ctx
                .select(DSL.val(1).as("one"))
                .select(TEST.ID)
                .from(TEST);

        record1 = select.fetchOne();

        Table<Record> a = select.asTable("a");
        af = DSL.field(DSL.name(a.getName(), TEST.ID.getName()), TEST.ID.getDataType());

        SelectJoinStep<Record> select2 = ctx.select(DSL.asterisk()).from(a);

        record2 = select2.fetchOne();

        index = record1.indexOf(TEST.ID);
    }

    @Benchmark
    public void by_identity(Blackhole blackhole) {
        Integer integer = record1.get(TEST.ID);
        blackhole.consume(integer);
    }

    @Benchmark
    public void wrapped_by_original(Blackhole blackhole) {
        Integer integer = record2.get(TEST.ID);
        blackhole.consume(integer);
    }

    @Benchmark
    public void original_by_wrapped(Blackhole blackhole) {
        Integer integer = record1.get(af);
        blackhole.consume(integer);
    }

    @Benchmark
    public void super_slow(Blackhole blackhole) {
        Integer integer = record2.get(af);
        blackhole.consume(integer);
    }

    @Benchmark
    public void by_name1(Blackhole blackhole) {
        // it does not matter if TEST.ID.getName() or af.getName() is used - both are trivial Strings
        Integer integer = (Integer) record1.get(TEST.ID.getName());
        blackhole.consume(integer);
    }

    @Benchmark
    public void by_name2(Blackhole blackhole) {
        Integer integer = (Integer) record2.get(TEST.ID.getName());
        blackhole.consume(integer);
    }

    @Benchmark
    public void by_index(Blackhole blackhole) {
        Integer integer = (Integer) record1.get(index);
        blackhole.consume(integer);
    }

    public static void main(String[] args) throws Exception {
        Options opt = new OptionsBuilder().include(AliasTest.class.getSimpleName()).forks(1).build();
        new Runner(opt).run();
    }
}
```

**Comment by lukaseder** [comment]
Looking into this now, can confirm the benchmark results:

```
Benchmark                      Mode  Cnt    Score     Error  Units
AliasTest.by_identity          avgt   25    7.019 ┬▒   0.312  ns/op
AliasTest.by_index             avgt   25    3.111 ┬▒   0.162  ns/op
AliasTest.by_name1             avgt   25   12.489 ┬▒   0.381  ns/op
AliasTest.by_name2             avgt   25   12.955 ┬▒   0.217  ns/op
AliasTest.original_by_wrapped  avgt   25   74.265 ┬▒   1.256  ns/op
AliasTest.super_slow           avgt   25  999.881 ┬▒ 153.157  ns/op
AliasTest.wrapped_by_original  avgt   25   47.368 ┬▒   0.967  ns/op
```

**Comment by lukaseder** [comment]
I think the best type of fix here is this:

> It seems to me that two tables (and possibly other named things) could be compared just by their qualified names.

Not all named things live in the same namespace. Namespacing is vendor specific. I feel that future implementations should address this.

However, given that `AbstractQueryPart.equals()` implements exactly this default behaviour already, your suggested change would at least be backwards compatible (there are always edge cases that make `equals()` intransitive and thus wrong).

Clearly, as you say, the default should be avoided. See also this issue: https://github.com/jOOQ/jOOQ/issues/11126

**Comment by lukaseder** [comment]
Fixing this in `TableAlias` and `TableImpl` yields a much better result:

```
Benchmark                      Mode  Cnt   Score   Error  Units
AliasTest.by_identity          avgt   25   7.102 ┬▒ 0.331  ns/op
AliasTest.by_index             avgt   25   2.888 ┬▒ 0.145  ns/op
AliasTest.by_name1             avgt   25  12.342 ┬▒ 0.455  ns/op
AliasTest.by_name2             avgt   25  13.000 ┬▒ 0.283  ns/op
AliasTest.original_by_wrapped  avgt   25  74.737 ┬▒ 1.490  ns/op
AliasTest.super_slow           avgt   25  20.534 ┬▒ 0.264  ns/op
AliasTest.wrapped_by_original  avgt   25  51.466 ┬▒ 6.049  ns/op
```

There's obviously more room for improvement with the other ones. I'll look into these things now.

**Comment by lukaseder** [comment]
OK, with the remaining ones, it appears that we're just looping:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/734593/222455807-72796812-f60d-4cdb-802a-871c98c5990a.png">

There's already a task for that. I'm not sure if there's any low hanging fruit in this area: https://github.com/jOOQ/jOOQ/issues/13384

**Comment by lukaseder** [comment]
The same should be done for `FieldAlias` and `TableFieldImpl`

**Comment by lukaseder** [comment]
Yes, it's possible. Backported to 3.17.9 (https://github.com/jOOQ/jOOQ/issues/14745), and 3.16.15 (https://github.com/jOOQ/jOOQ/issues/14746)
