### ISSUE TITLE
Add DSL.raw(String) and Settings.renderPlainSQLTemplatesAsRaw to allow plain SQL without templating

### ISSUE THREAD

**Issue by redhead** [jOOQ/jOOQ#14379]
### Use case

We encountered a weird situation when a SQL file was executed just fine using the JDBC driver directly and failed when executed in JOOQ.

The file had a Dollar-Quoted string constant which contained a definition of a multidimensional array to be processed by the SQL. 

E.g.:

```sql
DO $$
    DECLARE
        tags varchar[2][];
        p varchar[];
    begin
        -- ----------ˇ --------------------------- here we use the Dollar-Quoted String Constant to define the multi dimensional array
        tags := $s${
            {aadClientCredential, system},
            {aadCredentialBase, system}
        }$s$;

        foreach p slice 1 in array tags
            loop
                raise notice 'Array: %', p; -- <------------------- here it should print 2-element array (twice), but it renders it as 4-element (once) 
            end loop;
    end
$$;

```

When we run the content of the file using JooQ (`execute`) the content of the `$s$` is actually parsed using the Template Language and somehow streamlined into a single-dimensional array (instead of a 2-dimensional).

The template language is ignored in normal single-quoted strings, but it is allowed in the dollar-quoted ones.

### Possible solution

It would be nice if JooQ provided a way how to completely disable the template language for raw SQLs, or some of the SQL parts. Or provide more information about the dollar-quoted strings in the documentation.

### Possible workarounds

We could use a single-quoted string in our case, but in different cases it might not work so easily. Or custom escape sequence for `{ and }`

### jOOQ Version

3.16.5

### Database product and version

Postgres 14

### Java Version

OpenJDK 11

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.3.6

**Comment by lukaseder** [comment]
Thanks a lot for your report. First off, I think this particular error observation is a bug. jOOQ's plain SQL templates don't apply to string contents if the string literals are delimited by apostrophes, e.g. `'{0}'` is recognised as a string literal containing `{0}`, not a template placeholder.

When using the `SQLDialect.POSTGRES`, this logic should also apply to dollar quoted string literals (and the same in Oracle for their `q'[...]'` and related syntaxes). I'll fix this bug separately: https://github.com/jOOQ/jOOQ/issues/14379. The caveat there is that maybe, users wish to use templating inside of the `DO $$ .. $$` string, but not necessarily inside of nested strings, see discussion in #14379.

I agree that apart from that, occasionally, it would be useful to turn off templating. I can see two options for that:

- [ ] Add a `DSL.raw(String): SQL` method, which creates a template that generates verbatim content. It is not possible to have bind values or template placeholders and replacements in such a "template."
- [ ] Add a `Settings.plainSQLTemplating` flag that can be turned off for the scope of a `Configuration`, to effectively turn off the feature.

I don't think we'll need a raw option for every single template accepting method, that would produce too many overloads. So, the explicit approach for queries would be to run:

```java
// This is how it would be done
ctx.execute(raw("the SQL statement"));

// This would be overkill
ctx.executeRaw("the SQL statement");
```

**Comment by lukaseder** [comment]
It may be tempting tto treat any `DSL.sql(String)` (without bind values or template placeholder replacements) as a raw SQL string as well, but the templating feature you ran into here is the support for delimiting keywords as `{keyword}` (which then applies the `Settings.renderKeywordCase`).

It's not the best feature of these templates, but iit's a feature we can't simply ignore in this case.

**Comment by lukaseder** [comment]
The raw template feature is now implemented for jOOQ 3.18.0. I might look into the bug #14380 as well, although it's not so simple to fix without breaking existing assumptions.

Thanks again for your report!

**Comment by lukaseder** [comment]
Documentation available here: https://www.jooq.org/doc/dev/manual/sql-building/plain-sql-templating-raw/

**Comment by redhead** [comment]
That was quick. Thanks!

**Comment by lukaseder** [comment]
This improvement obsoletes:

- https://github.com/jOOQ/jOOQ/issues/10582
