### ISSUE TITLE
How to use CTE with UPDATE?

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#14381]
### Your question

I'm trying to translate https://stackoverflow.com/a/8702291/14731 into JOOQ. I can't figure out how to write this CTE component:

```
upsert as
( 
    update mytable m 
        set field1 = nv.field1,
            field2 = nv.field2
    FROM new_values nv
    WHERE m.id = nv.id
    RETURNING m.*
)
```

### jOOQ Version

3.17.5

### Database product and version

Postgresql 15.0

### Java Version

19

### OS Version

Microsoft Windows [Version 10.0.19045.2311]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.0

**Comment by lukaseder** [comment]
What are you struggling with, specifically?

**Comment by cowwoc** [comment]
I tried something along the lines of:

```
var upsert = DSL.name("upsert").
			fields(aoc.ASK_ORDER_ID.getUnqualifiedName(), aoc.INDEX_IN_TRANSACTION.getUnqualifiedName(),
				aoc.TRANSACTION_ID_THAT_CANCELLED.getUnqualifiedName()).
			as(DSL.update(aoc).
				set(aoc.ASK_ORDER_ID, askId.getValue()).
				set(aoc.INDEX_IN_TRANSACTION, Shorts.checkedCast(indexInTransaction)).
				set(aoc.TRANSACTION_ID_THAT_CANCELLED, transactionIdThatCancelled.getValue()).
				returning());
```

where `aoc` is a table. I get a compiler error:

```
Required type:
ResultQuery<R>
Provided: UpdateResultStep<Record>
reason: no instance(s) of type variable(s) exist so that Record conforms to Record3<?, ?, ?>
```

**Comment by lukaseder** [comment]
I see, the problem here is probably that for historic reasons, `returning()` always produces the `<R>` type of the `INSERT` or `UPDATE` statement, i.e. the type of `aoc`, whereas you want a `Record3<...>` type. You should use `returningResult` instead.

The incompatible change that will fix this eventually is here: https://github.com/jOOQ/jOOQ/issues/5070
