### ISSUE TITLE
Broken link in a logging statement and Javadoc

### ISSUE THREAD

**Issue by ThierryCurtil** [jOOQ/jOOQ#14383]
### Expected behavior

the new valid link seems to be : https://jdbc.postgresql.org/documentation/query/#getting-results-based-on-a-cursor

### Actual behavior

The log written by jooq is : 
> INFO  org.jooq.impl.AbstractResultQuery.lambda$info$5 [L.349] - Fetch Size               : A fetch size of 1000 was set on a auto-commit PostgreSQL connection, which is not recommended. See http://jdbc.postgresql.org/documentation/head/query.html#query-with-cursor

the link : http://jdbc.postgresql.org/documentation/head/query.html#query-with-cursor is broken

### Steps to reproduce the problem

any select() with a `fetchSize(xxx)` followed by a `fetchLazy()` outside of a transactional context will produce the above log statement.

### jOOQ Version

jooq 3.17.5

### Database product and version

postgresql 14

### Java Version

azul 17

### OS Version

ubuntu 22

**Comment by lukaseder** [comment]
Thanks a lot for your report. Will fix right away.

**Comment by lukaseder** [comment]
The broken link is also in the `ResultQuery.fetchSize(int)` Javadoc

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.18.0, 3.17.7 (https://github.com/jOOQ/jOOQ/issues/14384), and 3.16.13 (https://github.com/jOOQ/jOOQ/issues/14385)
