### ISSUE TITLE
Wrong example code in manual section "connection-access"

### ISSUE THREAD

**Issue by djarnis73** [jOOQ/jOOQ#14382]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-execution/connection-access/

### Feedback

The example that produces results looks like it calls the wrong method (uses `connection` instead of `connectionResult`):

```
// When you produce results
int rows = create.connection(c -> {
    try (Statement s = c.createStatement()) {
        return s.executeUpdate("INSERT INTO author (id, first_name, last_name) VALUES (3, 'William', 'Shakespeare')";
    }
});
```
I think it should read:
```
// When you produce results
int rows = create.connectionResult(c -> {
    try (Statement s = c.createStatement()) {
        return s.executeUpdate("INSERT INTO author (id, first_name, last_name) VALUES (3, 'William', 'Shakespeare')");
    }
});
```
I tried pasting the example into my IDE and discovered that it also misses the last ')' before the ';' in both examples.

**Comment by lukaseder** [comment]
Yes, you're right, thank you for the report. Will fix this right away.

**Comment by lukaseder** [comment]
The fix will be published in ~2h. Thanks again.
