### ISSUE TITLE
Using set(column, value) syntax for CTEs

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#14386]
### Your question

Is it possible to the `set(column, value)` syntax with CTEs?

Given:

```
WITH new_values (id, field1, field2) as (
  values 
     (1, 'A', 'X'),
     (2, 'B', 'Y'),
     (3, 'C', 'Z')
)
```

Is it possible to write something along the lines of:

```
DslContext.with("new_values").
set("id", 1).
set("field1", "A").
set("field2", "X")
```

and so on? I find this syntax much easier to read than specifying a list of fields followed by a list of values.

### jOOQ Version

3.17.5

### Database product and version

Postgresql 15.0

### Java Version

19

### OS Version

Microsoft Windows [Version 10.0.19045.2311]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.0

**Comment by lukaseder** [comment]
Thanks for your message.

I don't think this is an area where jOOQ should "innovate" with new syntax in the DSL. The idea you're having can be implemented sufficiently well using

```java
select(val(1).as("id"), val("A").as("field1"), val("X").as("field2")).unionAll(
select(val(2).as("id"), val("B").as("field1"), val("Y").as("field2"))).unionAll(
select(val(3).as("id"), val("C").as("field1"), val("Z").as("field2")))
```
