### ISSUE TITLE
Jackson deserialising not recognising JSONB type

### ISSUE THREAD

**Issue by lewisjluck** [jOOQ/jOOQ#14394]
### Your question

Hi all,

New to jooq and looking for some help. I am using Jackson to deserialise some json files into Jooq TableRecords specific to my database. The relevant code snippet is below. This works fine for most of my records, however one database I have a field which stores parameters in JSON format, which JOOQ stores in JSONB. 

When running the Jackson object mapper below on this database, I get the following error:

com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `org.jooq.JSONB` (although at least one Creator exists): cannot deserialize from Object

This would suggest that Jackson cannot process JSON into JSON? Is there specific JOOQ configuration or a Jackson module I need to pass into the objectMapper? Have looked around fruitlessly for solutions and am yet to find one (maybe it is so simple as to not need a solution).

Really appreciate any help!

```java
ObjectMapper objectMapper = new ObjectMapper()
            .setVisibility(PropertyAccessor.CREATOR, Visibility.PUBLIC_ONLY)
            .setVisibility(PropertyAccessor.FIELD, Visibility.NONE)
            .setVisibility(PropertyAccessor.SETTER, Visibility.NONE);
        objectMapper.registerModule(new JavaTimeModule());
        String jsonStr = new String(DbIntegrationTest.class.getClassLoader().getResourceAsStream("testdata/" + 
fileName).readAllBytes());
        T[] resultArray = (T[]) Array.newInstance(recordClass, 0);
        List<TableRecord<?>> records = Arrays.asList(objectMapper.readValue(jsonStr, resultArray.getClass()));
```

### jOOQ Version

jOOQ 3.17.2

### Database product and version

PostgresQL 14.5

**Comment by lukaseder** [comment]
Thanks for your message. Perhaps, there is a way to tell Jackson how to map JSON content into a `JSONB` object in jOOQ. I don't know Jackson well enough to show you the best way. Perhaps https://stackoverflow.com might help? Or tutorials like this? https://www.baeldung.com/jackson-deserialization

You probably just have to register some type conversion to ensure Jackson can wrap the serialised JSON in `JSONB::valueOf` or `JSONB::jsonb`.

However, it's not unlikely you can use jOOQ's out of the box JSON import support, see e.g.
https://www.jooq.org/doc/latest/manual/sql-execution/importing/importing-sources/importing-source-json/

And `DSLContext::fetchFromJSON`

**Comment by lewisjluck** [comment]
Thanks for your help Lukas! Probably was more of a Jackson question now I think about it. Solved by making a custom deserialiser module using the JSONB.jsonb method and registering it to the object mapper in Jackson. 

Cheers!
