### ISSUE TITLE
deleteFrom throw ClassCastException when using Spring Boot 3.0 and R2dbc

### ISSUE THREAD

**Issue by hantsy** [jOOQ/jOOQ#14397]
### Expected behavior

it seems there is a R2dbc SPI compatibility issues. In Spring Boot 3.0, the R2dbc SPI are upgrade to the latest 1.0.

https://github.com/hantsy/spring-r2dbc-sample/blob/master/jooq-kotlin-co-gradle/src/test/kotlin/com/example/demo/PostRepositoriesTest.kt#L76

```kotlin 
 val deletedPostsCount = Mono.from(dslContext.deleteFrom(POSTS)).awaitSingle()
```

### Actual behavior

It throws a Long cast to Int exception.

### Steps to reproduce the problem

Check out my sample project https://github.com/hantsy/spring-r2dbc-sample/blob/master/jooq-kotlin-co-gradle/

Run the https://github.com/hantsy/spring-r2dbc-sample/blob/master/jooq-kotlin-co-gradle/src/test/kotlin/com/example/demo/PostRepositoriesTest.kt

### jOOQ Version

3.17.6

### Database product and version

Postgres 12

### Java Version

17

### OS Version

Windows 10

### JDBC driver name and version (include name if unofficial driver)

R2dbc postgres managed by Spring Boot 3.0

**Comment by lukaseder** [comment]
Thanks for your report. You didn't paste a stack trace, though I'm assuming that this is due to the various R2DBC 0.9 vs 1.0 incompatibilities? We don't support R2DBC 1.0 yet, see: https://github.com/jOOQ/jOOQ/issues/13565
