### ISSUE TITLE
Support JPA 3.1 and generate GenerationType.UUID for generated UUID columns in PostgreSQL

### ISSUE THREAD

**Issue by wolfgangkirchler** [jOOQ/jOOQ#14408]
### Expected behavior

I would expect the following code to be generated:

```
/**
   * Getter for <code>fis.airplane.uuid</code>.
   */
  @Id
  @GeneratedValue(strategy =GenerationType.UUID)
  @Column(name = "uuid", nullable = false)
  public UUID getUuid() {
      return this.uuid;
  }
```

### Actual behavior

the following code is generated (without @GeneratedValue annotation)

```
/**
   * Getter for <code>fis.airplane.uuid</code>.
   */
  @Id
  @Column(name = "uuid", nullable = false)
  public UUID getUuid() {
      return this.uuid;
  }
```

this leads to the problem, that I cannot use the POJOs as JPA entities. The insert of the first value fails

### Steps to reproduce the problem

SQL definition (used to generate the sources with jooq)

```
CREATE TABLE airplane_model (
    uuid UUID NOT NULL default gen_random_uuid(),
    manufacturer VARCHAR(255),
    model_name VARCHAR(255),
    model_name_detail VARCHAR(255),
    engine_type VARCHAR(255),

    CONSTRAINT pk_airplane_model PRIMARY KEY (UUID)
);
```

sources are generated with jooq-maven-plugin + flyway
```
<plugin>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-maven-plugin</artifactId>
    <version>9.8.1</version>
  
    <executions>
        <execution>
            <phase>generate-sources</phase>
            <goals>
                <goal>migrate</goal>
            </goals>
        </execution>
    </executions>
  
    <configuration>
        <url>${jooq.codegen.db.url}</url>
        <user>${jooq.codegen.db.username}</user>
        <password>${jooq.codegen.db.password}</password>
        <locations>
            <location>filesystem:src/main/resources/flyway/migration</location>
        </locations>
  
        <schemas>${db-schema.name}</schemas>
    </configuration>
  </plugin>
  <plugin>
    <groupId>org.jooq</groupId>
    <artifactId>jooq-codegen-maven</artifactId>
    <version>${jooq.version}</version>
      <executions>
        <execution>
            <phase>generate-sources</phase>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <jdbc>
            <url>${jooq.codegen.db.url}</url>
            <user>${jooq.codegen.db.username}</user>
            <password>${jooq.codegen.db.password}</password>
        </jdbc>
        <generator>
            <name>org.jooq.codegen.JavaGenerator</name>
            <database>
                <includes>.*</includes>
                <inputSchema>${db-schema.name}</inputSchema>
            </database>
            <target>
                <packageName>com.example.jakartablueprint.jooq</packageName>
                <directory>target/generated-sources/jooq</directory>
            </target>
  
            <generate>
                <pojos>true</pojos>
                <jpaAnnotations>true</jpaAnnotations>
            </generate>
            </strategy>
        </generator>
    </configuration>
  </plugin>
```

p.s. I use the same workaround as described here: https://stackoverflow.com/questions/35059736/jooq-generated-pojo-missing-generatedvalue-annotation but i would be nice to fix this in a future version

### jOOQ Version

3.17.5

### Database product and version

postgres:14-bullseye

### Java Version

azul-17

### OS Version

MacOS 12.6

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.0

**Comment by lukaseder** [comment]
Thanks for your suggestion. This would require supporting JPA 3.1.

I think the assumption that a  `DEFAULT` expression that produces a UUID is a `@GeneratedValue` is a bit of a stretch. Even if it seems reasonable in your case, I can imagine similar cases where it isn't so clear that this UUID value has the function of an identity.

In any case, this support for JPA in the code generator as well as the `DefaultRecordMapper` is a feature that I've come to regret for quite a while now. While there are some valid use-cases, jOOQ will never completely implement all of these JPA features in the code generator.

Would you mind sharing the use-case you have for generating JPA annotations as well as why this particular annotation is important to you?

**Comment by wolfgangkirchler** [comment]
Thanks for your reply. I wanted to use jooq to generate JPA entities out of the DB schema to safe implementing these classes manually and have one source of truth (the DB schema). Now I understand this will never work completely, especially in such cases.

I think I will ditch the creation of POJOs and implement the JPA entities manually, even if it is some repetitive work.

**Comment by lukaseder** [comment]
I think that JPABuddy will be more appropriate for you? Or, of course, switching to using jOOQ completely :)
