### ISSUE TITLE
JSON-generating code with LATERAL joins fails on MySQL when swapping test from 8.0 -> 5.7

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#14411]
### Your question

Our code produces SQL like the below:

```sql
set @@group_concat_max_len = 4294967295;
select json_object(
  'rows', coalesce(
    json_merge(
      '[]',
      concat(
        '[',
        group_concat(`json`.`json_obj` separator ','),
        ']'
      )
    ),
    json_array()
  ),
  'aggregates', null
)
from lateral (
  select
    `Chinook`.`Artist`.*,
    json_object(
      'Name', `Artist`.`Name`,
      'ArtistId', `Artist`.`ArtistId`
    ) as `json_obj`
  from `Chinook`.`Artist`
  limit 2147483647
  offset 0
) as `json`;
set @@group_concat_max_len = @t;
```

The output format is the shape:
```js
{
  "rows": [
      {
         "foo": 1,
          "nested": [] // recursive 'rows'
     }
  ],
  "aggregates": {
      "nested": {} // recursive 'aggregates'
   }
}
```

This works perfectly fine on MySQL 8.x, however prior to launching we wanted to test on MySQL 5.7
I suppose I was under the assumption that swapping the version would be the only change but it looks like that was a mistaken assumption.

What's the best course of action to take here?

### jOOQ Version

3.18.0-SNAPSHOT Enterprise

### Database product and version

MySQL 5.7

### Java Version

OpenJDK 17

**Comment by lukaseder** [comment]
Thanks for your message.

I don't think `LATERAL` can be emulated easily on MySQL 5.7, nor can correlated derived tables be emulated easily, in case you're going to try that. E.g. the following is perfectly fine in MySQL 8 and most modern RDBMS:

```sql
select (
  select *
  from (select a) u
)
from (select 1 a) t
```

But it fails in MySQL 5.7 with:

> Unknown column 'a' in 'field list'

This limitation will be worked around for jOOQ 3.18's `MULTISET` support for some simple cases: https://github.com/jOOQ/jOOQ/issues/12045. But as soon as `MULTISET` are nested 2 levels deep, chances are users will run into the problem again.

jOOQ's JSON support itself should work on MySQL 5.7. From what I remember, there were only a few minor differences, which jOOQ attempts to handle, e.g. whether to use `JSON_MERGE` or `JSON_MERGE_PRESERVE`.

I can help you with a few specific additional cases that you may have. But it won't be easy. If I remember correctly, you're also heavily relying on `ROW_NUMBER()` usage, another MySQL 8 feature, which you may be able to emulate with this hackish approach of using local variables: https://stackoverflow.com/a/64312283/521799

**Comment by lukaseder** [comment]
Note, if you find specific limitations which are probably bugs or missing features in jOOQ (e.g. an edge case difference in behaviour of some JSON function between 5.7 and 8), just let me know. They might be simple to implement.

**Comment by GavinRay97** [comment]
Ah man, this doesn't look so great for us, in terms of MySQL early-version support!

Thanks Lukas, for the swift and comprehensive reply, as usual!

**Comment by lukaseder** [comment]
> Ah man, this doesn't look so great for us, in terms of MySQL early-version support!

Well, your less fancy queries can probably still be made to work?

**Comment by GavinRay97** [comment]
It is all or nothing for us unfortunately.

Since we are an engine/intermediary, every query must be treated as a black box that potentially is some monster of a user-generated query with 100 levels of nesting 🙁

**Comment by lukaseder** [comment]
I'm still optimistic. I've found hundreds of workarounds for so many limitations in so many dialects 😅

**Comment by GavinRay97** [comment]
But you're LUKAS EDER! 🤣 

On a serious note, I think we can probably do it for 5.7

We have a strategy that works for "MapReduce-engines-masquerading-as-RDBMS" like Presto and Snowflake that involves emulating `LATERAL` joins using `PARTITION BY` and `GROUP BY`, and I think it should work here

It's just going to be suuuuper ugly and hacky, compared to the nice code that produces the example SQL in the original issue.
Oh whale

**Comment by lukaseder** [comment]
> But you're LUKAS EDER! 🤣

I meant, I'm for hire to brainstorm such things, as you know :)

> It's just going to be suuuuper ugly and hacky, compared to the nice code that produces the example SQL in the original issue.

That ought to teach them to use such "old" technology (hmm, MySQL 8 is only from 2018)
