### ISSUE TITLE
Upgrade Spring Boot example to use Spring Boot 3.0

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14436]
The Spring Boot example should make use of Spring Boot 3.0:
https://github.com/jOOQ/jOOQ/tree/main/jOOQ-examples/jOOQ-spring-boot-example

**Comment by lukaseder** [comment]
Out of the box, the upgrade doesn't work:

```
[INFO] Running org.jooq.example.spring.QueryTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.331 s <<< FAILURE! - in org.jooq.example.spring.QueryTest
[ERROR] org.jooq.example.spring.QueryTest  Time elapsed: 0.331 s  <<< ERROR!
java.lang.IllegalStateException: Could not load TestContextBootstrapper [class org.springframework.boot.test.context.SpringBootTestContextBootstrapper]. Specify @BootstrapWith's 'value' attribute or make the default bootstrapper class available.
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.test.context.SpringBootTestContextBootstrapper]: Unresolvable class definition; nested exception is java.lang.NoClassDefFoundError: org/springframework/test/context/aot/AotTestAttributes
Caused by: java.lang.NoClassDefFoundError: org/springframework/test/context/aot/AotTestAttributes
Caused by: java.lang.ClassNotFoundException: org.springframework.test.context.aot.AotTestAttributes

[INFO] Running org.jooq.example.spring.TransactionTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 s <<< FAILURE! - in org.jooq.example.spring.TransactionTest
[ERROR] org.jooq.example.spring.TransactionTest  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalStateException: Could not load TestContextBootstrapper [class org.springframework.boot.test.context.SpringBootTestContextBootstrapper]. Specify @BootstrapWith's 'value' attribute or make the default bootstrapper class available.
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.test.context.SpringBootTestContextBootstrapper]: Unresolvable class definition; nested exception is java.lang.NoClassDefFoundError: org/springframework/test/context/aot/AotTestAttributes
Caused by: java.lang.NoClassDefFoundError: org/springframework/test/context/aot/AotTestAttributes
Caused by: java.lang.ClassNotFoundException: org.springframework.test.context.aot.AotTestAttributes
```

**Comment by lukaseder** [comment]
This is because we declare the `${spring.version}` to be 5.3.20 throughout examples and tests, including the `jOOQ-meta-extensions-hibernate` module!

Since Spring 6.0 requires Java 17, we can't upgrade that dependency yet, making things a bit more complicated. I'll have to think about this again.

**Comment by lukaseder** [comment]
The solution might be to move `${spring.version}` from the parent `pom.xml` to `jOOQ-meta-extensions-hibernate`, and specify a separate `${spring.version}` in the examples...

**Comment by lukaseder** [comment]
Trying this again. There's also a test that uses `org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy` from spring boot 2.x

**Comment by lukaseder** [comment]
Spring Boot is moving rather fast these days:
https://twitter.com/sergialmar/status/1727693306149093859?s=20

Better have an up-to-date example:

**Comment by lukaseder** [comment]
Alternative take, maybe, let's have no example at all.

Examples in the *jOOQ* repository are good to have to show *jOOQ* features. That's what the demo is for:

- https://github.com/jOOQ/jOOQ/issues/14894
- https://github.com/jOOQ/demo

All potential third parties that claim to auto-configure jOOQ can have their own examples / starters / etc. Documenting the fact that Spring Boot changes things so drastically all the time isn't the burden of libraries like jOOQ. jOOQ works out of the box really simply. All that is needed is a JDBC connection. Nothing else is really *needed* to get jOOQ to work.

**Comment by yu-nutmeg** [comment]
I'm having exactly the same issue, what was the solution to this problem?

**Comment by lukaseder** [comment]
This issue was about an upgrade of an example project, which we've deleted in the meantime. It is unlikely you'll find help here in the context of this issue.

Please create a new one with all the necessary details to help you.
