### ISSUE TITLE
Upgrade to Jooq 3.17.6 and Spring Boot 3.0.0 -> AbstractMethodError

### ISSUE THREAD

**Issue by stuzfuz** [jOOQ/jOOQ#14430]
### Expected behavior

working as with previous version

### Steps to reproduce the problem

```
022-12-26T20:58:48.774+01:00 ERROR 22584 --- [nio-8090-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.AbstractMethodError: Receiver class org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator does not define or inherit an implementation of the resolved method 'abstract void end(org.jooq.ExecuteContext)' of interface org.jooq.ExecuteListener.] with root cause

java.lang.AbstractMethodError: Receiver class org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator does not define or inherit an implementation of the resolved method 'abstract void end(org.jooq.ExecuteContext)' of interface org.jooq.ExecuteListener.
	at org.jooq.impl.ExecuteListeners.end(ExecuteListeners.java:270) ~[jooq-3.17.6.jar:na]
	at org.jooq.impl.Tools.safeClose(Tools.java:3152) ~[jooq-3.17.6.jar:na]
	at org.jooq.impl.Tools.safeClose(Tools.java:3115) ~[jooq-3.17.6.jar:na]
```

### jOOQ Version

3.17.6

### Database product and version

MySql 8

### Java Version

17

### OS Version

Version 10.0.22621.963

### JDBC driver name and version (include name if unofficial driver)

mysql:mysql-connector-java:8.0.13

**Comment by lukaseder** [comment]
Thanks for your message. `org.springframework.boot.autoconfigure.jooq.JooqExceptionTranslator` is not a class that belongs to jOOQ or is maintained by jOOQ. I suggest reporting this to the appropriate Spring Boot project.

**Comment by lukaseder** [comment]
Though, to be honest, I'm not sure if they're doing anything wrong? The class looks OK to me: https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/jooq/JooqExceptionTranslator.java
