### ISSUE TITLE
Delay ExecuteContext::connection in BatchMultiple and BatchSingle

### ISSUE THREAD

**Issue by db2222** [jOOQ/jOOQ#14445]
### Expected behavior

listener.start to be called before setting connection.

The reason for this is that we need special database connection logic that is applied during the ExecuteListener.

### Actual behavior

It is the other way around. Meaning the execute listener is too late.

See AbstractQuery in comparison. There it works as expected.

### Steps to reproduce the problem

Call DSL.batch(commands).execute.
An execute listener kicks in too late.

### jOOQ Version

3.17.4

### Database product and version

Database independent

**Comment by lukaseder** [comment]
Thanks for your report. I agree, this doesn't look consistent.

Types where `ExecuteContext::connection` is called before `ExecuteListener::start`

- `BatchSingle`
- `BatchMultiple`

Types where `ExecuteContext::connection` is called after `ExecuteListener::start`

- `AbstractQuery`
- `AbstractRoutine`

I'll review integration tests soon. There is probably no benefit in eagerly allocating the `Connection`. However, do note that from your description, perhaps a `ConnectionProvider` might be a better place to implement what you're trying to do?

**Comment by lukaseder** [comment]
While I agree the inconsistency isn't nice, I'm not sure if this is a bug or just something that hasn't been specified well enough. Some users may have come to rely on the status quo, hence, I'm reluctant to backport the change.

I'll implement it in jOOQ 3.18, though.
