### ISSUE TITLE
Feedback about translation tool

### ISSUE THREAD

**Issue by onovikov16** [jOOQ/jOOQ#14514]
Hello,

right now i.m trying to translate this
decode(NSI_DB.V_RAILWAY_SYSDATE.RW_CN_ID, 178, ' ', '10')||NSI_DB.V_RAILWAY_SYSDATE.RW_CODE

**Comment by onovikov16** [comment]
sorry, i sent message before it was completed (  
So, i'm tryin to translate and it results nothing.  In december i had the same situation, but later it starts to work. Do you know the reason of this?  
Thank you

**Comment by onovikov16** [comment]
![image](https://user-images.githubusercontent.com/102693474/213095141-bea43dd7-8c74-4eec-87ff-fedd99cc68eb.png)

**Comment by lukaseder** [comment]
Thanks for your report. We currently have a OS level problem on the server executing these queries. I've installed a crontab that reboots the server when the problem appears, so currently, it runs again, and the problem should appear less often.

Note, you can always run the translator locally as well.
