### ISSUE TITLE
GROUP_CONCAT manual page is missing a reference to `Settings.renderGroupConcatMaxLenSessionVariable`

### ISSUE THREAD

**Issue by oxygenecore** [jOOQ/jOOQ#14511]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/aggregate-functions/group-concat-function/

### Feedback

This is a missing part in doc, but exists in the blog: https://blog.jooq.org/mysqls-allowmultiqueries-flag-with-jdbc-and-jooq/
I was looking for a setting to disable the multiquery syntax because it's messing up the int result of a statement call (AWS Aurora's OUTFILE TO S3), did not find in the official docs, but found in the blog. I bet it's needed from time to time for others :)

**Comment by oxygenecore** [comment]
Also, I think an example of settings override would be helpful as well as an example :)

**Comment by lukaseder** [comment]
Thanks for your feedback. Yes, it would make sense to document this `Settings` flag. And with the new "references to this page" section at the bottom of all referenced sections (see https://github.com/jOOQ/jOOQ/issues/14342), there will be an automatic back reference from the `GROUP_CONCAT` page to the relevant `Settings` page

**Comment by lukaseder** [comment]
The flag was introduced in jOOQ 3.15: https://github.com/jOOQ/jOOQ/issues/12092

**Comment by lukaseder** [comment]
Done. The new sections will be added in about 1h. Thanks again for your report.

**Comment by lukaseder** [comment]
There's the manual page:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-group-concat/

With a backlink from the page you've mentioned:

<img width="783" alt="image" src="https://user-images.githubusercontent.com/734593/212979860-63afd53d-c2e5-43d3-8b37-ca20b4d20c3e.png">

**Comment by oxygenecore** [comment]
Great! Thank you! 😃👍
