### ISSUE TITLE
Emulate some window functions for SQLDialect.MYSQL_5_7

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14529]
As shown in this blog post:
https://blog.jooq.org/emulating-window-functions-in-mysql-5-7/

Some window functions can be emulated in MySQL 5.7 if we make some assumptions (and validate them using SQL transformation, etc.). For example:

```sql
SELECT
  a, b,
  ROW_NUMBER() OVER (PARTITION BY a ORDER BY b DESC) AS rn1,
  json_extract(
    @rn := json_set(
      @rn, @path := concat('$."', a, '"'), 
      (coalesce(json_extract(@rn, @path), 0) + 1)
    ), 
    @path
  ) AS rn2,
  @rn AS debug -- Added for debugging purposes only
FROM (
  SELECT 1 AS a, 3 AS b UNION ALL
  SELECT 2 AS a, 4 AS b UNION ALL
  SELECT 1 AS a, 5 AS b UNION ALL
  SELECT 2 AS a, 6 AS b
) AS t, (SELECT @rn := '{}') r
ORDER BY b DESC;
```

Produces:

```
|a  |b  |rn1|rn2|debug               |
|---|---|---|---|--------------------|
|2  |6  |1  |1.0|{"1": 2.0, "2": 1.0}|
|1  |5  |1  |1.0|{"1": 1.0}          |
|2  |4  |2  |2.0|{"1": 2.0, "2": 2.0}|
|1  |3  |2  |2.0|{"1": 2.0}          |
```

**Comment by lukaseder** [comment]
@GavinRay97: I'm still reluctant to go forward with these emulations as there are probably tons of edge cases (see caveats in the blog post). If you could try the approach on your end and provide feedback, that would be great. If you had a list of distinct window function usages that you're doing, even better. Keeping an eye out for:

- Window function name (`ROW_NUMBER`, `RANK`, etc.)
- Distinct `PARTITION BY` clauses (absent, 1 column, 2 column, expressions)
- Distinct `ORDER BY` clauses (absent, 1 column, ..., expressions, `NULLS FIRST`, etc.)
- Distinct window frame clauses (`ROWS` / `RANGE`)
- Other points of interest

**Comment by lukaseder** [comment]
The `@x := <expr>` syntax can be supported independently: https://github.com/jOOQ/jOOQ/issues/2558

**Comment by GavinRay97** [comment]
Heya Lukas, we'll be taking up this emulation implementation in the near future, as I believe it's the only way for us to compile GraphQL queries of arbitrary depth to a single SQL query for earlier MySQL.

Thanks again so much for reasoning about this and figuring it out.

> If you had a list of distinct window function usages that you're doing, even better

The rough logic that we use for constructing the window functions, with some details removed is:

```kt
    private fun mkQueryFrom(ctx: QueryGenCtx): SelectConditionStep<Record> {
        val parentJoinCols: List<Field<*>> = mkParentJoinKeyFields(ctx)

        return DSL.select(
            // Base columns
            DSL.table(DSL.name(ctx.currentTableName.value)).asterisk(),
            // Relationship field names from sub-query joins
            // IE: "Albums"."rows_and_aggregates" as "Albums" (from the "Albums" sub-query in an Artist -> Albums query)
            ...
            // Row number + order by
            DSL.rowNumber().over(
                DSL.partitionBy(
                    parentJoinCols
                ).orderBy(
                    mkOrderByField(ctx).distinct()
                )
            ).`as`("rn")
        ).from(
            DSL.table(DSL.name(ctx.currentTableName.value))
        ).apply {
            mkJoinsRequiredForRowNumberOrderByClause(ctx, this)
        }.apply {
            // mkQueryJoins is mutually recursive with mkQuery
            mkQueryJoins(ctx, this)
        }.where(
            mkQueryWhere(ctx)
        ).apply {
            this.orderBy(
                DSL.field(DSL.name("rn"))
            )
        }
    }
```

**Comment by lukaseder** [comment]
OK, so arbitrary `PARTITION BY` expressions and arbitrary `ORDER BY` expressions, the worst case :) Anyway, if an emulation was implemented at all, then the worst case would have to be expected anyway.

**Comment by lukaseder** [comment]
According to https://en.wikipedia.org/wiki/MySQL#Release_history, end of support for MySQL 5.7 is October 2023. Given how hairy this is and that everyone should be on MySQL 8 by now (for tons of reasons), I'm not going to implement this.

The idea is documented here, and users can still manually implement this in client code (probably much more easily, because it can be implemented on an ad-hoc basis, rather than a generic one).
