### ISSUE TITLE
How to change metadata naming conventions in JPADatabase generator?

### ISSUE THREAD

**Issue by Michal-Kucera** [jOOQ/jOOQ#14523]
### Your question

Hello!

I'm sorry in advance if there is documentation about this, but I couldn't find it.

I'm using `nu.studer.jooq` Gradle plugin to generate metadata models from my entities, using `JPADatabase` db type.

My problem is that I'm building a new application based on legacy tables which apparently have table names and column names in slightly unfriendly format where all words are together, e.g. instead of `company_name` we have `companyname`, instead of `bank_terminal_prefix_id` we have `bankterminalprefixid`, same applies for tables.

This causes my queries to look like follows:

```kotlin
dslContext.select(ID, COMPANYNAME, BANKTERMINALPREFIXID).from(MERCHANTACCOUNTS)
...
```

I'm wondering if there is an option to tell to the generator to not take the value from `@jakarta.persistence.Column#name` but rather take it from the field name (or anything else) that I have in my classes, e.g. `companyName` and `bankTerminalPrefixId`, so it is nicely formatted, for example as this:

```kotlin
dslContext.select(ID, COMPANY_NAME, BANK_TERMINAL_PREFIX_ID).from(MERCHANT_ACCOUNTS)
...
```

I'd be happy for any general advice about code generation, doesn't necessarily need to be specific to this Gradle plugin.

Cheers
Michal

### jOOQ Version

3.17.6

### Database product and version

not applicable I guess, but at the end I use Postgres

### Java Version

17

### OS Version

Mac OS 13.1

### JDBC driver name and version (include name if unofficial driver)

not applicable I suppose, I use only org.jooq:jooq-meta-extensions-hibernate:3.17.6

**Comment by lukaseder** [comment]
You can influence the generated Java identifiers from the code generator using a generator strategy:

- Programmatic: https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/
- Configurative: https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/

I hope this helps
