### ISSUE TITLE
Possible bug in `ReferenceImpl` when `fetchParents` has empty result set

### ISSUE THREAD

**Issue by apatrida** [jOOQ/jOOQ#14543]
### Expected behavior

The code in `ReferenceImpl` has calls to `uk.getFields` or similar such as:

```@Override
    public final Result<O> fetchParents(Collection<? extends R> records) {
        if (records == null || records.size() == 0)
            return new ResultImpl<>(new DefaultConfiguration(), uk.getFields());
        else
            return extractDSLContext(records).selectFrom(parents(records)).fetch();
    }
```

yet it is constructed from `createForeignKey` using this logic allowing fields to be overridden on construction:

```
ukFields == null ? uk.getFieldsArray() : ukFields,
```

which implies the `ukFields` should be used instead of those form the index from that point onwards.  For the reference, it returns this overridden field list when asked on which fields is it a reference.  But then the rest of the code ignores this and uses `uk.getFields`.  This is either inconsistent, an error, or intentional (but I don't get why).

Why override the fields if that override means nothing later?

### Steps to reproduce the problem

see above

### jOOQ Version

3.17.6

### Database product and version

any

**Comment by apatrida** [comment]
Why am I playing with this?  Because I have databases without foreign keys but with Kotlin I can add extension functions that fake them:

```
// allow implied join to a table by pretending there is a foreign key

fun QuestionsTable.AUTHOR(): UsersTable {
    val fakeForeign = Internal.createForeignKey(
        QuestionsTable.QUESTIONS,
        DSL.name("fk_fake_questions_to_user"),
        arrayOf(QuestionsTable.QUESTIONS.USER_ID),
        RrDbKeys.KEY_USERS_PRIMARY,
        arrayOf(UsersTable.USERS.ID),
        false
    )
    return UsersTable(this, fakeForeign) 
}
```

so I got curious about the dangers of doing so (found none, because if the indexes are there, who cares if the actual foreign key constraint exists). 

I do, however, have to put that extension into the `impl` package because everything is package local, while I have strong beliefs I should be allowed to make a `ForeignKey` implementation I don't want to implement that longer list of methods, nor can I override `ReferenceImpl`.

**Comment by lukaseder** [comment]
Thanks for your report, @apatrida. Let's take a step back from 1) Your analysis of internal behaviour, 2) Your usage of internal API to 3) What you really want to achieve and why.

I mean, you're using internal API (The `Internal` class name probably gave it away), so you're probably aware of things that might not really be bugs, but just things that can't be used this way. Rather than trying to make hacks work, I'd like to understand what it is you're trying to do, and why you chose to use internal API for this.

**Comment by lukaseder** [comment]
Here's a useful website showing why I try not to answer the initial question, but rather look for the *actual* question: https://xyproblem.info.

It's a common pattern, and I fall into this trap myself a lot, when asking questions about other products :)

**Comment by apatrida** [comment]
I wasn't actually asking how to use this internal API, but rather was exploring options for implied joins when code generation does not see foreign keys (because there aren't any).  And in the process, noticed that this code appeared possibly wrong, or inconsistent so was bringing it to your attention.

I know there are:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-synthetic-objects/codegen-database-synthetic-fks/

and was exploring options for non-codegen if available, or a way to replace 12+ lines of configuration for each of hundreds of tables with 1 liners in extension functions.
