### ISSUE TITLE
Forcetype for MySQL `int unsigned`

### ISSUE THREAD

**Issue by apatrida** [jOOQ/jOOQ#14545]
### Your question

I cannot figure out how to make a force-type regex match against `int unsigned` in MySQL.

`int.*unsigned` and even just `.*unsigned.*` match nothing.

I want to force type them to `BIGINT` or to the Kotlin built-in unsigned types (not the JOOQ U* types)

### jOOQ Version

3.17.6

### Database product and version

MySQL 5.7

**Comment by apatrida** [comment]
Is the `includeTypes` not match against the full type w/unsigned flag?

I can try the SQL based type match maybe, checking that.

**Comment by apatrida** [comment]
Yep, that worked fine.

```SELECT CONCAT(c.table_schema, '.', c.table_name, '.', c.column_name) FROM information_schema.columns c WHERE c.table_schema = 'rr_db' AND c.data_type = 'int' AND c.column_type LIKE 'int%unsigned';```

**Comment by lukaseder** [comment]
Thanks for your message. It appears that jOOQ pretends this type is called `INTUNSIGNED`, without whitespace. This is definitely confusing, I wonder if this needs fixing.

Of course, since tons of folks may already match the type without whitespace, a fix would have to keep that working.

**Comment by lukaseder** [comment]
Sure, that might make sense: https://github.com/jOOQ/jOOQ/issues/14550
