### ISSUE TITLE
Casting between an `Insert` and an `InsertResult` that has a `returning()`

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#14559]
### Your question

I'm attempting to do the below, and running into some cast issues:

`... cannot be cast to class org.jooq.InsertResultStep (org.jooq.impl.InsertImpl and org.jooq.InsertResultStep are in unnamed module of`

Which is strange, because the type of `this.returning()` is `InsertResultStep`:

![image](https://user-images.githubusercontent.com/26604994/214928838-e5f86304-7749-442c-b508-2ad5cec8e9ec.png)

```kt
val insertQuery =
    DSL
        .insertInto(DSL.table(DSL.name(thisInsertSchema.table.value)))
        .apply {
            for (row in operation.rows) {
                for ((fieldName, field) in thisInsertSchema.fields) {
                    when (field) {
                        is ColumnInsertSchema ->  this.set(DSL.field(field.column), row.value[fieldName])
                    }
                }
                // Next row
                (this as InsertSetMoreStep<*>).newRecord()
            }
        } as InsertSetMoreStep<*>

val ret = insertQuery.apply {
    if (operation.ret != null) {
        this.returning(operation.ret.map { (fieldName, field) ->
            when (field) {
                is Column -> DSL.field(field.column).`as`(fieldName)
                is Other -> DSL.noField()
            }
        })
    } else {
        this.returning(DSL.noField())
    }
}

return ret as InsertResultStep<*>
```

### jOOQ Version

3.18.0-SNAPSHOT Enterprise

### Database product and version

N.A

### Java Version

OpenJDK 17

### OS Version

Fedora 38 WSL2

### JDBC driver name and version (include name if unofficial driver)

N/A

**Comment by lukaseder** [comment]
Thanks for your report. Is there a more minimal way to reproduce this? E.g. this doesn't fail (in Java):

```java
InsertResultStep<?> x = (InsertResultStep<?>)
    ((InsertSetMoreStep) ctx.insertInto(table("t")).columns(field("i", INTEGER)).values(1)).returning(noField());
```

**Comment by GavinRay97** [comment]
On second thought, I feel like it's more of a Kotlin language problem than a jOOQ problem, not your issue.
Thanks for replying Lukas.

If I rewrite the function so that it doesn't use `.apply` but instead uses your way, it works.

**Comment by lukaseder** [comment]
Ah, I see now. Indeed, you cannot use `apply`:

```kotlin
inline fun <T> T.apply(block: T.() -> Unit): T
```

It takes `T` and returns `T` (not the block result!), but `T` being inferred to `InsertSetMoreStep<*>` cannot be upcast to `InsertResultStep`.

<img width="355" alt="image" src="https://user-images.githubusercontent.com/734593/215181104-15260277-9774-45fc-8037-0d64796adc44.png">

It's funny they called it `apply`, which sounds like a function is being applied. You probably wanted `let`:

```kotlin
inline fun <T, R> T.let(block: (T) -> R): R
```
