### ISSUE TITLE
Feedback about manual section "jooq-in-7-steps-step3"

### ISSUE THREAD

**Issue by MykKuc** [jOOQ/jOOQ#14562]
### The documentation URL

https://www.jooq.org/doc/latest/manual/getting-started/tutorials/jooq-in-7-steps/jooq-in-7-steps-step3/

### Feedback

I am doing all the steps as in the documentation, but I get this error that `Error: Could not find or load main class org.jooq.codegen.GeneratioTool` .

Here is the script that I am executing:
```
$ java -classpath jooq-3.16.3.jar:\
> jooq-meta-3.16.3.jar:\
> jooq-codegen-3.16.3.jar:\
> reactive-streams-1.0.3.jar:\
> r2dbc-spi-0.9.0.RELEASE.jar:\
> jakarta.xml.bind-api-3.0.0.jar:. \
> org.jooq.codegen.GeneratioTool library.xml
Error: Could not find or load main class org.jooq.codegen.GeneratioTool
Caused by: java.lang.ClassNotFoundException: org.jooq.codegen.GeneratioTool
```

**Comment by lukaseder** [comment]
That's just a typo. It's called `GenerationTool`, not `GeneratioTool`

**Comment by MykKuc** [comment]
But I get the same error even if I change it into GenerationTool. 
```
Error: Could not find or load main class org.jooq.codegen.GenerationTool
Caused by: java.lang.ClassNotFoundException: org.jooq.codegen.GenerationTool
```

**Comment by lukaseder** [comment]
I'm assuming all the `jar` files are local in the directory you're running this from?

**Comment by MykKuc** [comment]
I have create a temporary directory in my project name jooqtmp/ as per instructions: `The easiest way to generate a schema is to copy the jOOQ jar files (there should be 3) and the MySQL Connector jar file to a temporary directory. Then, create a library.xml that looks like this`
My temporary directory looks like this:
![jooq-snip](https://user-images.githubusercontent.com/60236539/215069064-e0a31123-da2b-4ef8-9c52-908f4f063904.PNG)
I SSH into that directory using Git Bash and I execute the following commands as per instructions:
![commands](https://user-images.githubusercontent.com/60236539/215070141-93d62167-7e31-4822-8643-0c4436474a82.PNG)

**Comment by lukaseder** [comment]
But your shell is inside of `try-jooq` or inside of `try-jooq/jooqtmp`?

**Comment by MykKuc** [comment]
My shell is inside try-jooq/jooqtmp directory.

**Comment by lukaseder** [comment]
I can see it now. I missed out on the fact that you're actually on Windows, not linux. Using bash on Windows is a bit tricky  in this case, I suspect.

If you run `java -help`, you can find that on Windows (bash or any other shell, such as the windows terminal, `cmd.exe`, etc.) you have to use `;` as a classpath separator, not `:`. That's what the JRE expects. On my Windows machine (in German):

```
    --class-path <Klassensuchpfad mit Verzeichnissen und ZIP-/JAR-Dateien>
                  Eine durch ; getrennte Liste mit Verzeichnissen, JAR-Archiven
                  und ZIP-Archiven, in denen nach Klassendateien gesucht wird.
```

Now in bash, in order to use the `;` character in your command, you'll have to wrap the `-classpath` argument in double quotes, e.g. `java -classpath "jooq-3.16.3.jar;jooq-meta-3.16.3.jar;..."`

Does that work for you?

**Comment by lukaseder** [comment]
We'll definitely add a comment to the manual. That's very confusing indeed.

**Comment by MykKuc** [comment]
Yes, now the generation is working fine. Finally, I have spent over 2 days trying to figure things out. Thank you very much. 😃

**Comment by lukaseder** [comment]
Oh boy, well, some things are learned the hard way 😬. At least, I hope that going forward, jOOQ will bring you lots of joy!
