### ISSUE TITLE
Wrong window function example in manual

### ISSUE THREAD

**Issue by devmind-ua** [jOOQ/jOOQ#14615]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/window-functions/

### Feedback

Hi,

I the [Some examples](https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/window-functions/#some-examples) section jOOQ counterpart for SQL `ROW_NUMBER() OVER (ORDER BY BOOK.ID),` should be `rowNumber().over().orderBy(BOOK.ID),`.

Now it is `rowNumber().over().partitionBy(BOOK.AUTHOR_ID),`.

Best regards,
Iurii.

**Comment by lukaseder** [comment]
Yes, indeed, thank you.
