### ISSUE TITLE
Java 8 support in 3.17.8 Free Trial version? 

### ISSUE THREAD

**Issue by chenguangshen** [jOOQ/jOOQ#14643]
### Expected behavior

According to https://www.jooq.org/download/versions, the free trial version 3.17.8 should support Java 8  

### Actual behavior

- Using the downloaded free trial 3.17.8 jar for a Java 8 project would result in a build error, similar to the one described in https://stackoverflow.com/questions/71561604/jooq-throws-class-file-for-java-util-concurrent-flow-not-found-for-where-conditi
- Using Java 8 + OSS 3.14.16 would NOT result in the same build error 
- Using Java 11 + free trial 3.17.8 jar would NOT result in the same build error either

### Steps to reproduce the problem

Build using Java 8 and the jOOQ free trial 3.17.8 jar

### jOOQ Version

Free Trial 3.17.8

### Database product and version

MySQL

### Java Version

OpenJDK 8

### OS Version

Mac OS

**Comment by lukaseder** [comment]
Thanks for your message. Have you downloaded the right distribution from that download page?

<img width="236" alt="image" src="https://user-images.githubusercontent.com/734593/219298604-6ba04baa-01f2-4495-86af-82e529a2ab15.png">

Once you have, please note as stated throughout the manual, e.g. here:
https://www.jooq.org/doc/3.18/manual/code-generation/codegen-maven/

... that you have to use the right Maven groupId for the various artifacts, e.g.:

```xml
<plugin>
  <!-- Specify the maven code generator plugin -->
  <!-- Use org.jooq                for the Open Source Edition
           org.jooq.pro            for commercial editions with Java 17 support, 
           org.jooq.pro-java-11    for commercial editions with Java 11 support,
           org.jooq.pro-java-8     for commercial editions with Java 8 support,
           org.jooq.trial          for the free trial edition with Java 17 support, 
           org.jooq.trial-java-11  for the free trial edition with Java 11 support, 
           org.jooq.trial-java-8   for the free trial edition with Java 8 support 
         
       Note: Only the Open Source Edition is hosted on Maven Central. 
             Import the others manually from your distribution -->
  <groupId>org.jooq.trial-java-8</groupId>
  <artifactId>jooq-codegen-maven</artifactId>
  <version>3.18.0-SNAPSHOT</version>
```

I hope this helps

**Comment by lukaseder** [comment]
You don't have to use Maven, you can use any other means of adding jOOQ's jar files to your classpath.
