### ISSUE TITLE
SpringBoot 3.0+ custom schema settings ignored

### ISSUE THREAD

**Issue by osiwko** [jOOQ/jOOQ#14666]
### Steps to reproduce the problem

I have a problem after migrating project to SpringBoot 3.0+. I have a database with custom schema name which name is injected in runtime via:
```
@Bean  
Settings settings() { 
         return new Settings()
                .withRenderMapping(new RenderMapping()
                        .withSchemata(new MappedSchema().withInput("").withOutput(databaseSchema)));
 }
```
_(This is done like this due issue with integration tests which uses public schema by default)_

Currently those settings are ingored completly. DSLContext has empty schemata during runtime which leads to error
`jOOQ; bad SQL grammar [select \"some_table\".\"id\", (....)]",`
Also after creating manually table "some_table" in public schema everything works (which is not expected behivour ofc). Help 🥲 

### jOOQ Version

spring-boot-starter-jooq:3.0.2

### Database product and version

Postgres 15

### Java Version

17

### JDBC driver name and version (include name if unofficial driver)

postgresql:42.5.1

**Comment by lukaseder** [comment]
Thank you for your report. I'm not aware of any such problem. If you're convinced this is a problem caused by jOOQ, can you please provide a reproducer that shows how you configured Spring Boot? We have a template for "MCVE" (minimal, complete, verifiable examples) here: https://github.com/jOOQ/jOOQ-mcve

However, it seems more likely that something has changed in Spring Boot itself, so it is probably not a jOOQ problem. In that case, please report it to Spring Boot, instead.

**Comment by osiwko** [comment]
It might be a problem of JooqAutoConfiguration in spring-boot-autoconfigure:

v.2.7.7:
![Screenshot at Feb 22 20-41-36](https://user-images.githubusercontent.com/37174425/220745969-0545a2f9-3986-4de8-ab4a-5e576940faf9.png)
![Screenshot at Feb 22 20-57-57](https://user-images.githubusercontent.com/37174425/220745974-a6f81666-53d7-4a11-aa11-22ea40d00444.png)

v.3.0.2
![Screenshot at Feb 22 20-43-44](https://user-images.githubusercontent.com/37174425/220746038-2d136063-0057-4756-8c68-2e737029bb12.png)

**Comment by lukaseder** [comment]
So, perhaps you could report it to spring boot, then?
https://github.com/spring-projects/spring-boot

**Comment by lukaseder** [comment]
We're not yet integration testing with Spring Boot 3.0, our example is still using 2.x, see https://github.com/jOOQ/jOOQ/issues/14436

**Comment by osiwko** [comment]
@lukaseder I will report it to spring boot team, thank you 🙂
