### ISSUE TITLE
Not all sequences from PostgreSQL generated into Java

### ISSUE THREAD

**Issue by mhogerheijde** [jOOQ/jOOQ#14677]
### Expected behavior

When upgrading from `3.14.16` to `3.17.8`, I noticed that not all sequences from our schema are generated into `Sequences.java`. I found this behaviour to start from `3.15.0` onwards.

Given a schema with the following squences:
```
psql (12.8 (Debian 12.8-1.pgdg110+1))
Type "help" for help.

example=# \ds
                 List of relations
 Schema |        Name        |   Type   |  Owner
--------+--------------------+----------+----------
 public | example3_id_seq    | sequence | postgres
 public | example4_id_seq    | sequence | postgres
 public | example_id_seq     | sequence | postgres
 public | example_two_id_seq | sequence | postgres
(4 rows)
```

I expect all sequences to be generated.

The following is actually generated:

```
/*
 * This file is generated by jOOQ.
 */
package com.example;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@Generated(
    value = {
        "https://www.jooq.org/",
        "jOOQ version:3.15.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.example4_id_seq</code>
     */
    public static final Sequence<Long> EXAMPLE4_ID_SEQ = Internal.createSequence("example4_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.example_two_id_seq</code>
     */
    public static final Sequence<Long> EXAMPLE_TWO_ID_SEQ = Internal.createSequence("example_two_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
````

Using `3.14.16` with an otherwise exactly the same configuration, jOOQ generates this

```
/*
 * This file is generated by jOOQ.
 */
package com.example;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@Generated(
    value = {
        "https://www.jooq.org/",
        "jOOQ version:3.14.16"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.example3_id_seq</code>
     */
    public static final Sequence<Long> EXAMPLE3_ID_SEQ = Internal.createSequence("example3_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.example4_id_seq</code>
     */
    public static final Sequence<Long> EXAMPLE4_ID_SEQ = Internal.createSequence("example4_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.example_id_seq</code>
     */
    public static final Sequence<Long> EXAMPLE_ID_SEQ = Internal.createSequence("example_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.example_two_id_seq</code>
     */
    public static final Sequence<Long> EXAMPLE_TWO_ID_SEQ = Internal.createSequence("example_two_id_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
```

Where all sequences are generated.

### Actual behavior

I tried to reduce the example to the minimal schema I could and ended up with the example code found at https://github.com/mhogerheijde/jooq-sequences/.

The schema contains 4 different ways of including sequences and in `3.15.0` and higher, 2 of the sequences don't end up in the `Sequences.java` file, while all other configuration is kept the same.

It also shows the behaviour under `3.14.16`, where all 4 sequences are output into `Sequences.java`.

Below a table of the results I found, given the exact same jOOQ configuration.

<table>
<thead>
<tr>
<th>Sequence</th>
<th>Table</th>
<th>table name is sequence prefix?</th>
<th>Default?</th>
<th>3.14.16</th>
<th>3.15.0</th>
<th>3.17.8</th>
</tr>
</thead>
<tbody>
<tr>
<td><p dir="auto"><code>example_id_seq</code></p></td>
<td><p dir="auto"><code>example</code></p></td>
<td><p dir="auto">yes, <code>example</code></p></td>
<td><p dir="auto">column <code>example.id</code> by alter table</p></td>
<td><p dir="auto">yes</p></td>
<td><p dir="auto">no</p></td>
<td><p dir="auto">no</p></td>
</tr>
<tr>
<td><p dir="auto"><code>example_two_id_seq</code></p></td>
<td><p dir="auto"><code>example2</code></p></td>
<td><p dir="auto">no, <code>example2</code> and <code>example_two</code> are not similar.</p></td>
<td><p dir="auto">column <code>example2.id</code> by alter table.</p></td>
<td><p dir="auto">yes</p></td>
<td><p dir="auto">yes</p></td>
<td><p dir="auto">yes</p></td>
</tr>
<tr>
<td><p dir="auto"><code>example3_id_seq</code></p></td>
<td><p dir="auto"><code>example3</code></p></td>
<td><p dir="auto">yes, <code>example3</code></p></td>
<td><p dir="auto">column <code>example.id</code> within create table.</p></td>
<td><p dir="auto">yes</p></td>
<td><p dir="auto">no</p></td>
<td><p dir="auto">no</p></td>
</tr>
<tr>
<td><p dir="auto"><code>example4_id_seq</code></p></td>
<td><p dir="auto"><code>example4</code></p></td>
<td><p dir="auto">yes, <code>example4</code></p></td>
<td><p dir="auto">Not used as default</p></td>
<td><p dir="auto">yes</p></td>
<td><p dir="auto">yes</p></td>
<td><p dir="auto">yes</p></td>
</tr>
</tbody>
</table>

### Steps to reproduce the problem

Either use the code at https://github.com/mhogerheijde/jooq-sequences/ and follow the readme

or

1. Load the following schema into a database
```
-- Sequence has prefix of table name
CREATE SEQUENCE example_id_seq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

CREATE TABLE example
(
  id bigint NOT NULL
);

ALTER TABLE ONLY example
  ALTER COLUMN id SET DEFAULT nextval('example_id_seq'::regclass);


-- Sequence has different prefix to table name
CREATE SEQUENCE example_two_id_seq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

CREATE TABLE example2
(
  id bigint NOT NULL
);

ALTER TABLE ONLY example2
  ALTER COLUMN id SET DEFAULT nextval('example_two_id_seq'::regclass);


-- sequence has same prefix as table name, but it is directly set as the default value
CREATE SEQUENCE example3_id_seq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

CREATE TABLE example3
(
  id bigint NOT NULL DEFAULT nextval('example3_id_seq'::regclass)
);


-- sequence has same prefix as table name, but it is not used as a default
CREATE SEQUENCE example4_id_seq
  START WITH 1
  INCREMENT BY 1
  NO MINVALUE
  NO MAXVALUE
  CACHE 1;

CREATE TABLE example4
(
  id bigint NOT NULL
);
```

2. Generate java code from this schema. (with 3.15.0 or higher)
3. Inspect `Sequences.java`

Only 2 sequences are present in the generated code.

### jOOQ Version

3.15.0+

### Database product and version

PostgreSQL 12.8 (Debian 12.8-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2 .1 20210110, 64-bit

### Java Version

openjdk version "17.0.2" 2022-01-18

### OS Version

Ubuntu 22.10 (5.19.0-31-generic)

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by lukaseder** [comment]
Thanks a lot for your message.

The relevant change is:

- https://github.com/jOOQ/jOOQ/issues/10899
- https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-include-object-types/

See also:

- https://github.com/jOOQ/jOOQ/issues/12435

I hope this helps

**Comment by mhogerheijde** [comment]
Hi Lukas,

I forgot to look through closed issues before opening this issue, my apologies for that!

Thanks for the quick reply!

**Comment by lukaseder** [comment]
No worries :) These things are hard to find when you don't know the exact keywords to look for.
