### ISSUE TITLE
Absence of DEFAULT dialect in NO_SUPPORT_ILIKE Set

### ISSUE THREAD

**Issue by gneeri** [jOOQ/jOOQ#14680]
### Expected behavior

Given the code comments around the `LIKE_IGNORE_CASE` operator (namely: This translates to this not ilike value in SQLDialect.POSTGRES, or to lower(this) not like lower(value) in all other dialects), I was expecting that the DEFAULT dialect would lower case `LIKE` comparison values appropriately. This, however, was not the case, due to the absence of the DEFAULT dialect in the `NO_SUPPORT_ILIKE` Set in Like.java.  

### Steps to reproduce the problem

Render SQL using the `LIKE_IGNORE_CASE` operator against the DEFAULT dialect.

### jOOQ Version

jOOQ Professional 3.18.0-SNAPSHOT

### Database product and version

Athena (we were using the DEFAULT dialect for this)

**Comment by lukaseder** [comment]
From the `SQLDialect.DEFAULT` Javadoc:
https://www.jooq.org/javadoc/dev/org.jooq/org/jooq/SQLDialect.html#DEFAULT

> This dialect is chosen in the absence of a more explicit dialect. It is not intended to be used with any actual database as it may combined dialect-specific things from various dialects.

So, any expectations that you may have towards its behaviour can be broken at any time. Its main purpose is to produce *something* when calling   `QueryPart.toString()` on arbitrary query parts, for debugging purposes. In fact, there's an epic task going on to change its behaviour towards what one would expect from the API or parser syntax, away to something that pretends to be a least common denominator across dialects (how would one even test such a thing?):

- https://github.com/jOOQ/jOOQ/issues/9085

Regarding your actual use-case, Athena support is on the roadmap:

- https://github.com/jOOQ/jOOQ/issues/5414

See this resource for further information about new dialects:

- https://github.com/jOOQ/jOOQ/discussions/14059
