### ISSUE TITLE
does jooq have a way to add comment to the sql generated by jooq ?

### ISSUE THREAD

**Issue by zkhzkhz** [jOOQ/jOOQ#14716]
### Your question

 Because we need to find slow sql bugs 

### jOOQ Version

3.14.15

### Database product and version

Postgres SQL 11+

### Java Version

jdk11

**Comment by lukaseder** [comment]
Thanks for your message. You can use the Oracle style hint clause for this:
https://www.jooq.org/doc/latest/manual/sql-building/hints/hints-oracle/

It's not really Oracle specific, just places the comment you pass to it at the Oracle specific location (right after the `SELECT` keyword).

Alternatively, an `ExecuteListener` will be more powerful and low level, to add comments to all of your queries.

Hope this helps

**Comment by zkhzkhz** [comment]
solved by add implement on ExucuteListener(method:executeStart()）)

**Comment by zkhzkhz** [comment]
thank you!
