### ISSUE TITLE
Add missing set(String, Param) and setLocal(String, Param) overloads

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14711]
I'm not sure why these overloads were omitted at the time, but there's not really a very good reason to do it, I think? The main reason I can imagine is to force people to think about whether the name needs to be quoted or not (default being quoted, and thus case sensitive)... But since folks will probably just go ahead and wrap their string with `DSL.name()` (instead of `DSL.unquotedName()`), they'll get the same effect.

**Comment by zhuangdaz** [comment]
@lukaseder Hi Lukas, I am looking to add `SET AndScanReordering = 'True'; `([doc](https://docs.pinot.apache.org/operators/tutorials/performance-optimization-configurations#query-option-to-enable-and-predicate-reordering)) to my Pinot query but not familiar the best approach to set it. Should I set it when creating a DSLcontext or I am able to set it per query?

**Comment by lukaseder** [comment]
@zhuangdaz Use an `ExecuteListener` to prepend statements to queries.
