### ISSUE TITLE
ClassCastException when returning number of updated rows from reactive query

### ISSUE THREAD

**Issue by spheenik** [jOOQ/jOOQ#14752]
### Expected behavior

The number of updated rows can be returned as an Integer

### Actual behavior

It seems to be a Long

### Steps to reproduce the problem

I use Spring Boot 3.0.3 and R2DBC.
I execute the following update:

```java
    public Mono<Integer> acceptCookiePolicy(UUID uid) {
        return Mono.from(
                ctx.update(CLIENT)
                        .set(CLIENT.COOKIES_ACCEPTED, true)
                        .where(CLIENT.UID.eq(uid))
        );
    }
```

When I execute this, and then `map()` or `flatMap()` on it's result, I get a ClassCastException:

```
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132) ~[reactor-core-3.5.3.jar:3.5.3]
```

It seems the result comes back as a Long from the Postgres-Driver, while JOOQ is assuming it to be an Integer.

### jOOQ Version

3.17.8

### Database product and version

PostgreSQL 15.1 

### Java Version

17.0.6.u10-2

### OS Version

Arch Linux

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.4

**Comment by spheenik** [comment]
RDBC Driver class `io.r2dbc.postgresql.PostgresqlResult` definitively returns it as a Long. The subscriber seems to be a `org.jooq.impl.AbstractRowCountQuery` which indeed assumes it will get an Integer.

**Comment by spheenik** [comment]
Found this issue:

https://github.com/jOOQ/jOOQ/issues/14261

So you seem to be aware. I'm going to try with the 3.18 SNAPSHOT.

**Comment by spheenik** [comment]
I seem to be unable to acquire the 3.18.0-SNAPSHOT of jooq-codegen. Is it available somewhere?

**Comment by lukaseder** [comment]
Thanks for your report, and for following up.

> I seem to be unable to acquire the 3.18.0-SNAPSHOT of jooq-codegen. Is it available somewhere?

Here, if you're licensed: https://www.jooq.org/download/versions, or you can build from github.
