### ISSUE TITLE
Can we manually edit audit-columns?

### ISSUE THREAD

**Issue by cmrgKoradir** [jOOQ/jOOQ#14768]
### Your question

We have audit timestamps `created` and `last_modification` defined.

```groovy
forcedTypes {
    forcedType {
        auditInsertTimestamp = true
        name = "INSTANT"
        includeExpression = "created"
    }
    forcedType {
        auditInsertTimestamp = true
        auditUpdateTimestamp = true
        name = "INSTANT"
        includeExpression = "last_modification"
    }
    forcedType {
        name = "INSTANT"
        includeTypes = '''
              TIMESTAMPTZ
            | TIMESTAMP
        '''
    }
    forcedType {
        auditInsertUser = true
        name = "int"
        includeExpression = "created_by_id"
    }
    forcedType {
        auditInsertUser = true
        auditUpdateUser = true
        name = "int"
        includeExpression = "modified_by_id"
    }
}
```

For sake of determinism, we may want to manually set e.g. the creation date in integration tests that rely on it.

e.g.

```kotlin
dslContext
    .update(FOO)
    .set(FOO.CREATED, hardcodedDate)
    .where(FOO.ID.eq(fooId))
    .execute()
```

However, upon inspection, the query that this actually generates is

```
update "public"."foo" set "last_modification" = cast(current_timestamp as timestamp with time zone), "modified_by_id" = ? where "public"."foo"."id" = ?
```

i.e. the `created` update is removed from the query.

I do understand that most of the times, we do want jOOQ to ignore creation-scope audit columns during queries.
But is there a way we can force the update when we DO want to change it?

### jOOQ Version

Pro 3.17.6

### Database product and version

PostgreSQL 13.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit

**Comment by lukaseder** [comment]
So, after giving this some more thought, I do think we should have flags turning off the functionality for certain queries: https://github.com/jOOQ/jOOQ/issues/14775

**Comment by lukaseder** [comment]
So, after giving this some more thought, I do think we should have flags turning off the functionality for certain queries: https://github.com/jOOQ/jOOQ/issues/14775

**Comment by lukaseder** [comment]
See also:

- https://github.com/jOOQ/jOOQ/issues/16781
