### ISSUE TITLE
Oracle: Support fetching the last-inserted ID for tables with known auto-inc PK's, maybe through `RETURNING .. INTO`?

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#14772]
### Use case

It appears that `identity` functionality is not natively supported by jOOQ for Oracle.

This is a big blocker for us -- as part of mutations, we allow returning the inserted rows in the response.
We use the last-inserted ID to fetch the set of inserted records for tables with auto-inc PK's.

It seems like the `RETURNING INTO` clause may be able to be used for something like this?

```java
OraclePreparedStatement pstmt = (OraclePreparedStatement)con.prepareStatement(
                 "insert into t ( x ) values ( 1 ) returning y into ?");

pstmt.registerReturnParameter(1, OracleTypes.VARCHAR, 20);

boolean done;
done = pstmt.execute();

ResultSet rset = pstmt.getReturnResultSet();
while (rset.next()) {
    String name = rset.getString(1);
    System.out.print(name);
}

// C:\temp>java JDBCreturning
// HELLO
```

I'll defer to your Oracle knowledge here.

Assuming that schema information is available about an Oracle database, is there any way in jOOQ to implement this functionality or similar that allows for returning of inserted rows?

Thank you =)

### jOOQ Version

3.18.0-SNAPSHOT Enterprise

### Database product and version

Oracle 21c

**Comment by GavinRay97** [comment]
Another idea maybe:

```sql
-- Perform an anonymous block to get the last ID of the ARTIST table
DECLARE
    v_last_id NUMBER;
BEGIN
    SELECT ARTISTID INTO v_last_id FROM ARTIST ORDER BY ARTISTID DESC FETCH FIRST ROW ONLY;
    -- Insert a new record greater than the last ID
    INSERT INTO ARTIST (ARTISTID, NAME) VALUES (CAST(v_last_id + 1 AS NUMBER(10)), 'Foobar 1');
    INSERT INTO ARTIST (ARTISTID, NAME) VALUES (CAST(v_last_id + 2 AS NUMBER(10)), 'Foobar 2');
    INSERT INTO ARTIST (ARTISTID, NAME) VALUES (CAST(v_last_id + 3 AS NUMBER(10)), 'Foobar 3');
END;
```

Although this doesn't seem possible with the current `SelectIntoStep`

I tried:
```kt
val stmt = DSL.begin(
    DSL.declare(DSL.variable("v_last_id", SQLDataType.INTEGER)),
    DSL.select(DSL.field("ArtistId"))
        .into(DSL.table("v_last_id"))
        .from(DSL.table("Artist"))
        .orderBy(DSL.field("ArtistId").desc())
        .limit(1),
    DSL.insertInto(DSL.table("Artist"))
        .columns(DSL.field("ArtistId"), DSL.field("Name"))
        .values(DSL.field("v_last_id").plus(1), DSL.inline("Foobar 1")),
    // ...
)
```

And that renders with the Oracle dialect:
```sql
begin
  create table v_last_id
  as
  select ArtistId
  from Artist
  order by ArtistId desc
  fetch next ? rows only;
  insert into Artist (
    ArtistId,
    Name
  )
  values (
    (v_last_id + ?), 
    'Foobar 1'
  );
  -- ...
```

**Comment by lukaseder** [comment]
Thanks for your report. You must be running into some very specific issue, because we've been supporting Oracle PL/SQL `RETURNING` out of the box for a long time,  maybe even since jOOQ 1.x days? Some insight here:
https://blog.jooq.org/the-many-ways-to-return-data-from-sql-dml/

Can you please show what exactly you're doing and what isn't working for you?

**Comment by GavinRay97** [comment]
Sure, to elaborate a bit, we initially tried to use `.returning()` but ran into some issues with it:
- https://github.com/jOOQ/jOOQ/issues/14771

It seems to work when only the identity column(s) are selected, but if other columns are selected then an NPE is thrown.

We went with something like this to get the set of rows:
```kt
val insertQuery = DSL.insertInto(DSL.table(DSL.name(op.table.value)))
    .columns(columns)
    .valuesOfRows(rows)

val affectedRows = txn.dsl().execute(insertQuery)

val firstInsertedId = txn.dsl().lastID().toLong()
val lastInsertedId = firstInsertedId + affectedRows - 1
```

Which works great, except that `.lastID()` does not work on Oracle 

Maybe we can swap to using `returning()` and asking only for the identity column, since that seems to work?

**Comment by lukaseder** [comment]
Yeah, I'm afraid there's no silver bullet with `RETURNING`. Though, I'm still not sure what doesn't work about `RETURNING` in Oracle. I'll look at the (MySQL specific?) NPE from #14771 tomorrow.

**Comment by GavinRay97** [comment]
Specifically with Oracle, I get:

```java
java.lang.NullPointerException: Cannot invoke "org.jooq.impl.QueryPartList.size()" because "this.rendered.bindValues" is null
        at org.jooq_3.18.0-SNAPSHOT.ORACLE.debug(Unknown Source)
        at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1101)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:341)
        at org.jooq.impl.DMLQueryAsResultQuery.fetch(DMLQueryAsResultQuery.java:144)
        at org.jooq.impl.Tools.attach(Tools.java:1526)
        at org.jooq.impl.DefaultDSLContext.fetch(DefaultDSLContext.java:4629)
```

**Comment by GavinRay97** [comment]
Ah, removing `.withStatementType(StatementType.STATIC_STATEMENT)` seems to fix it.

**Comment by GavinRay97** [comment]
Going to close this as using `returning()` without static statements seems to work,
though a second issue has popped up when trying to insert multiple rows this way

**Comment by GavinRay97** [comment]
Ah, the reasons for using `STATIC_STATEMENT` everywhere were so that it's easier to debug since the values are inlined in the SQL and in the OpenTelemetry spans that we record.

Outside of that, had no particular reasons, and I don't think it's a huge deal to be honest.

**Comment by lukaseder** [comment]
> Ah, the reasons for using `STATIC_STATEMENT` everywhere were so that it's easier to debug since the values are inlined in the SQL and in the OpenTelemetry spans that we record.

Ah, I see. Well, jOOQ does that out of the box for you if you turn it on:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-execute-logging/

Or, you could implement your own debug log using an `ExecuteListener`. Though I see you want to debug the *exact* SQL being executed, not a re-render.

However, in production, you should avoid inlining bind values in Oracle (or any RDBMS with an execution plan cache), to avoid cursor cache contention.

> After seeing what `returning()` generates for Oracle, I bow down to you for figuring out how to do this.
> This is insane, I cannot believe it works and it gives me anxiety, lol.

It gives me anxiety as well, if I hear there's a possible bug in there 😅
