### ISSUE TITLE
Add <E, R : Record1<E>>ResultQuery<R>.fetchValue(): E? extension method to kotlin

### ISSUE THREAD

**Issue by strindberg** [jOOQ/jOOQ#14777]
### Use case

We use the new (3.18) and newish (3.16?) Kotlin extension methods on single-value records extensively, and it enables fantastically neat and succinct code. To enable re-use, we have a lot of methods as the following, which return a Record of a mapped type:

```kotlin
fun userColumns() = row(USER.FIRST_NAME, USER.LAST_NAME).mapping(::UserRef)
```

This can be used in multisets very nicely:
```kotlin
jooq.select(
...
multiset(
  select(userColumns())
  from(USER)
  where(...)
).intoList()
)
```

The new `fetchList()` gives the same benefit in a fetch:
```kotlin
jooq.select(userColumns())
  from(USER)
  where(...)
).fetchList()
```

However, using this method when fetching a single value still looks slightly odd, with an explicit mapping lambda:
```kotlin
jooq.select(userColumns())
  from(USER)
  where(...)
).fetchOne { it.value1() }
```

The above works, of course, but my suggestion would be two minor additional extension methods to a Record1:

```kotlin
fun <E, R : Record1<E>> ResultQuery<R>.fetchIntoOne(): E? = fetchOne { it.value1() }

fun <E, R : Record1<E>> ResultQuery<R>.fetchIntoSingle(): E = fetchSingle { it.value1() }
```

This would allow our developers to write the above as this:

```kotlin
jooq.select(userColumns())
  from(USER)
  where(...)
).fetchIntoOne()
```

This looks a little bit nicer while still being clear about what happens. We have already added these methods to our own utility code, but perhaps it could be considered for inclusion in jOOQ proper?

### jOOQ Version

3.18.0

### Database product and version

Postgresql 15

**Comment by lukaseder** [comment]
Thanks for your message.

You could destructure `Record1` like this:

```kotlin
val (x) = jooq.select(userColumns()).from(USER).where(...).fetchSingle
```

Or, there's always:

```kotlin
jooq.fetchValue(query)
```

But I agree, we can add a `ResultQuery<E, R : Record1<E>>.fetchValue(): E?` function that maps to `fetchOne()`. A `fetchSingleValue()` method could be added as well. We don't have that on  `DSLContext`, yet.
