### ISSUE TITLE
How to add swagger or spring doc annotation to pojos columns？

### ISSUE THREAD

**Issue by liu-xinhui** [jOOQ/jOOQ#14779]
### Your question

`spring boot`+`spring doc`+`jooq`
I want add doc for frontend
like 
```
@Schema(title ="filed description")
private String filed;
``` 

### jOOQ Version

3.18

### Database product and version

mysql:8.0.32

### Java Version

openjdk-17.0.2

### OS Version

all

### JDBC driver name and version (include name if unofficial driver)

com.mysql.cj.jdbc.Driver:8.0.32

**Comment by lukaseder** [comment]
Thanks for your message. I'm sorry, I don't really understand what you're asking. Can you be a bit more specific?

**Comment by liu-xinhui** [comment]
@lukaseder how to add `@Schema` annotation to generate pojos class field
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/7698511/224638153-590fd689-8206-47b0-a8ff-840796ab9f3d.png">

**Comment by liu-xinhui** [comment]
I have read the doc `Custom generator strategies`,but not found way to add custom annotation to filed.
https://www.jooq.org/doc/3.18/manual/code-generation/codegen-generatorstrategy/

**Comment by lukaseder** [comment]
I see. We currently don't have a way to add custom annotations to arbitrary locations. While it would be possible to implement this, it would be a lot of effort to get it right for all:

- POJO generation modes (e.g. mutable / immutable / records, etc)
- Supported languages

I think there's already a feature request on the roadmap to do this eventually, but it's currently not a priority.

You can always override or patch the `JavaGenerator`'s `generatePojo()` methods, though.

**Comment by liu-xinhui** [comment]
thank you
