### ISSUE TITLE
Code generator is annotating setters/getters of nullable columns in Record classes with `@Nullable`.

### ISSUE THREAD

**Issue by thomasneuteboom** [jOOQ/jOOQ#14786]
### Expected behavior

```java
    /**
     * Setter for <code>player.id</code>.
     */
    public void setId(@NotNull Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>player.id</code>.
     */
    @NotNull
    public Integer getId() {
        return (Integer) get(0);
    }
```

### Actual behavior

The class generator is setting `@Nullable` on a non-nullable column. I'm using Postgres. I've not experienced this problem with MySQL before.

```java
    /**
     * Setter for <code>player.id</code>.
     */
    public void setId(@Nullable Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>player.id</code>.
     */
    @Nullable
    public Integer getId() {
        return (Integer) get(0);
    }
```

Strangely the `username` that is also a not-nullable column is annotated correctly:
```java
    /**
     * Setter for <code>player.username</code>.
     */
    public void setUsername(@NotNull String value) {
        set(1, value);
    }

    /**
     * Getter for <code>player.username</code>.
     */
    @NotNull
    public String getUsername() {
        return (String) get(1);
    }
```

The `created_at` has the same issue as the `id`.

**Table structure in the database where the code was generated from:**
<img width="771" alt="Screenshot 2023-03-13 at 16 56 49" src="https://user-images.githubusercontent.com/1652432/224756780-ce1b6b8e-a1ee-43d5-b253-71c9c74f3c40.png">

### Steps to reproduce the problem

**Gradle Kotlin DSL:**
```kotlin
jooq {
    version.set("3.18.0")
    configurations {
        create("main") { 
            generateSchemaSourceOnCompilation.set(true)

            jooqConfiguration.apply {
                logging = Logging.DEBUG
                jdbc.apply {
                    driver = "org.postgresql.Driver"
                    url = "jdbc:postgresql://127.0.0.1:5432/database"
                    user = "user"
                    password = "secret"
                }
                generator.apply {
                    name = "org.jooq.codegen.DefaultGenerator"
                    database.apply {
                        name = "org.jooq.meta.postgres.PostgresDatabase"
                        inputSchema = "public"
                    }
                    generate.apply {
                        isNullableAnnotation = true
                        nullableAnnotationType = "org.jetbrains.annotations.Nullable"
                        isNonnullAnnotation = true
                        nonnullAnnotationType = "org.jetbrains.annotations.NotNull"
                    }
                    strategy.name = "org.jooq.codegen.DefaultGeneratorStrategy"
                }
            }
        }
    }
}
```

**SQL Migration V1__create_player_table.sql:**
```
CREATE TABLE "public"."player" (
    "id" int4 NOT NULL,
    "username" varchar NOT NULL,
    "password" varchar,
    "updated_at" timestamp,
    "created_at" timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY ("id")
);
```

### jOOQ Version

3.18.0

### Database product and version

PostgresSQL 15.2

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.4

**Comment by lukaseder** [comment]
Thanks for your message.

The reason for this is that you probably have a `DEFAULT` expression (an identity) on your table. That means that POJOs and records are allowed to contain `NULL` values prior to insertion.

I hope this helps.

**Comment by thomasneuteboom** [comment]
Thanks for your reply! 🙏🏼

I've removed the `DEFAULT` expression from the `created_at` column in the table. The annotation for the `created_at` column is now indeed `@NotNull`. Unfortunately, the column `id` getter and setter is still `@Nullable`. Why do you think this happens?

```java
    /**
     * Setter for <code>player.id</code>.
     */
    public void setId(@Nullable Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>player.id</code>.
     */
    @Nullable
    public Integer getId() {
        return (Integer) get(0);
    }
```

```
CREATE TABLE "public"."player" (
    "id" int4 NOT NULL,
    "username" varchar NOT NULL,
    "password" varchar,
    "updated_at" timestamp,
    "created_at" timestamp NOT NULL,
    PRIMARY KEY ("id")
);
```

**Comment by lukaseder** [comment]
The logic from `JavaGenerator` is this:

```java
    private boolean effectivelyNotNull(DataTypeDefinition type) {
        return !type.isNullable()
            && !type.isDefaulted()
            && !type.isIdentity();
    }
```

The only remaining reason is that it's an identity column (e.g. a `serial`), and that your UI isn't showing this information.

**Comment by dsvensson** [comment]
This also relates to how immutable interfaces are generated. While this is correct for creating content, as the default exists, all fetches will be non-nullable for columns with default, if the column is non-null.

**Comment by lukaseder** [comment]
Can you provide an example, @dsvensson

**Comment by dsvensson** [comment]
Similar to this issue. But instead of Integer I have a UUID as follows:

```
                                   Table "public.document"
        Column         |           Type           | Collation | Nullable |      Default       
-----------------------+--------------------------+-----------+----------+--------------------
 document_id           | uuid                     |           | not null | uuid_generate_v4()
...
Indexes:
    "document_pkey" PRIMARY KEY, btree (document_id)
...
```

Which will become `@Nullable` in `DocumentRecord`, and `IDocument` because it has a default. I get that it makes sense to have it `@Nullable` as you can pass a `DocumentRecord` with `documentId` set to `NULL`, and the right thing for me to do would be to remove all the defaults, especially as our JPAs generate defaults client side for most if not all of these cases. It would be nice if it was possible to just simply treat non-nullable columns with default as non-null as an option, and require client side to always pass in a value.

**Comment by lukaseder** [comment]
I see, I was distracted by the interface part, which just adds more complexity to the problem without really changing it.

> It would be nice if it was possible to just simply treat non-nullable columns with default as non-null as a generator-option, like:

It was obvious that someone would eventually request a flag, indeed :)

And, as you might imagine, there will soon be dozens of other flag requests related to nullability, introducing the impossibility to test them all, producing tons of edge cases of combinations of flags that may or may not work at compile time or at runtime.

For example, someone might want to have `isNullableDefaults = false` in generated code, but not at runtime (when loading the POJO into the Record). Once more proving that this nullability "promise" is just a lie. I mean, the simple workaround is always to just use the `JavaGenerator`, or wait until kotlin implements language support for the platform type.

See:

- https://github.com/Kotlin/KEEP/issues/82
- https://youtrack.jetbrains.com/issue/KT-56899/Denotable-nullability-flexible-platform-types-T

**Comment by lukaseder** [comment]
... my bad, I just realised, this is about the `JavaGenerator` and generated annotations. So, the "platform type" already exists, and it consists of removing the annotations from the code generation configuration, if they don't work for you.

**Comment by dsvensson** [comment]
Turns out it was very trivial to extend the JavaGenerator to deal with nullability in a way that makes sense in this specific case by using the Kotlin delegate by to reduce the amount of boilerplate. Sorry for the noise.

**Comment by lukaseder** [comment]
Regarding your customisations:

> Looks like I have to vendor the complete `org.jooq.meta.postgres.PostgresDatabase` family of classes if I would create something custom for this. 

I wouldn't recommend that. You'll remove the `DEFAULT` information everywhere, leading to subtle runtime behavioural changes (whenever the `DEFAULT` is relevant).

> Now that I think of it, perhaps it's possible to just customize the `JavaGenerator`.

That's certainly an option. People frequently ask for custom extension hooks for arbitrary annotations (not nullability related), e.g.:

- https://github.com/jOOQ/jOOQ/issues/13846

Perhaps, that's the way to go here.

**Comment by lukaseder** [comment]
> Sorry for the noise.

No noise, it's always good to hear that people find something "wrong." That doesn't mean the suggested solution is the way to go, but it certainly means that the status quo is not good.
