### ISSUE TITLE
Additional Condition Kotlin Extensions

### ISSUE THREAD

**Issue by yahorbarkouski** [jOOQ/jOOQ#14788]
### Use case

In order to build highly-conditional jOOQ queries on Kotlin I don't see a better way now than just

1. Extract condition from the query to a separate variable
2. Append it by jOOQ conditions based on your request' conditions, using `when` and `if` statements

Example:
```
var condition = noCondition()

request.name?.let {
    condition = condition.and(BOOK.NAME.eq(it))
}
```

Since we're on Kotlin it looks cumbersome, and the language allows us to make it a little more comfortable

### Possible solution

In our company we're using jOOQ helpers for such cases, like
```
fun <T> Condition.andIfPresent(filter: T?, filterCondition: (T) -> Condition): Condition =
    filter?.let { f -> this.and(filterCondition(f)) } ?: this

fun <T> Condition.orIfPresent(filter: T?, filterCondition: (T) -> Condition): Condition =
    filter?.let { f -> this.or(filterCondition(f)) } ?: this
```

That help us to turn our example in something like this:
```
var condition = noCondition()
    .andIfPresent(request.name) { BOOK.NAME.eq(it) }
```

Looks clear and simple, and shorten your repository files. The reason for this request is to get feedback and make a PR with this feature and a bit more if accepted, so it can be consider as Pre-PR feedback checker

### jOOQ Version

3.17.2

### Database product and version

N/A

**Comment by lukaseder** [comment]
Thanks for your suggestion.

This approach doesn't scale in terms of API design. You want convenience for `and` and `or`, but others will want the same convenience for `xor` and `add` and `mul` and `sub` and `div` and `is[Not]DistinctFrom` and `join` and `leftJoin` and `rightJoin` and many many other things.

All the while the primitives to do this are already available:

- In jOOQ (e.g. put all conditions in a `List` / `Stream` whatever, and reduce with `Condition::and`)
- In kotlin (e.g. `let`, `auto`, `apply`, etc.)

The primitives are much more composable, will never feel wrong or incomplete. Perhaps you're missing a `letIf()` primitive in kotlin, like this?

```kotlin
inline fun <T> T.letIf(test: Boolean, block: (T) -> T): T = if (test)
    block(this)
else
    this
```

But that's not a jOOQ specific thing.

**Comment by lukaseder** [comment]
To illustrate a bit more what I mean by this doesn't scale, you also introduced the notion of `IfPresent` to mean "non-null" to the API. But that just covers one possible test. What if arbitrary `Boolean` expressions should be available? What if they should be lazy? And soon, you'll have 3-4 of these `ifs` *per* operator (`and`, `or`, etc.)
