### ISSUE TITLE
SQLDialect version check throws NumberFormatException in Percona DB

### ISSUE THREAD

**Issue by codylerum** [jOOQ/jOOQ#14791]
### Expected behavior

Query executes without issue as it did in 3.17.8

### Actual behavior

throws NumberFormatException when executing query (insert in this case)

Rolling back to 3.17.8 resolves the issue.

### Steps to reproduce the problem

mysql percona version 8.0.29-21

`select version()` returns `8.0.29-21`

```
NumberFormatException
For input string: "29-21"

org.jooq_3.18.0.MYSQL in debug
java.lang.NumberFormatException in forInputString at line 67
java.lang.Integer in parseInt at line 668
java.lang.Integer in parseInt at line 786
org.jooq.SQLDialect in patchVersion at line 1381
org.jooq.SQLDialect in supportsDatabaseVersion at line 1368
org.jooq.impl.DefaultExecuteContext in connection at line 642
org.jooq.impl.DefaultExecuteContext in connection at line 620
org.jooq.impl.AbstractQuery in execute at line 308
org.jooq.impl.AbstractDelegatingQuery in execute at line 115
```

### jOOQ Version

3.18.0

### Database product and version

8.0.29-21 (Percona Server (GPL), Release '21', Revision 'c59f87d2854')

### Java Version

JDK 17.0.56

### OS Version

Linux

### JDBC driver name and version (include name if unofficial driver)

mysql connector j 8.0.30

**Comment by lukaseder** [comment]
Thanks a lot for your report. While we don't currently integration test perconadb, this should certainly not fail. Will look into this right away.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.19.0, 3.18.1 (https://github.com/jOOQ/jOOQ/issues/14792), 3.17.10 (https://github.com/jOOQ/jOOQ/issues/14793), and 3.16.16 (https://github.com/jOOQ/jOOQ/issues/14794).

Given the significance of this problem, the fix will be released this week, still.

Thanks again for your report.

**Comment by lukaseder** [comment]
Related: I've put adding regression tests for Percona DB on the roadmap:
https://github.com/jOOQ/jOOQ/issues/14795

Possibly, it might even make sense to support the dialect properly and independently.

**Comment by codylerum** [comment]
@lukaseder Just an FYI (I know this is already fixed) but I was adding some more tests on my side to exercise JOOQ bit more and I hit this when using 3.18.0 with just standard github actions mysql instance

`java.lang.NumberFormatException: For input string: "32-0ubuntu0"`

So it's probably more common to have some trailer on the mysql version

**Comment by lukaseder** [comment]
Thanks for the heads-up. The new regex should cover that format, too.
