### ISSUE TITLE
Error when PostgreSQL anonymous block contains dollar quoted string token

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14800]
Our anonymous block implementation generates a `DO` statement on PostgreSQL, e.g.:

```sql
do
$$
begin
end;
$$;
```

This is fine until the block's content contains `$$` somewhere, e.g. in an identifier. We should:

- [x] ~Use a more unique token by default, e.g. `$block$`~
- [x] Make the default token configurable, so users can override it in the even more unlikely even of conflict

**Comment by lukaseder** [comment]
An additional option seemed to be to escape nested dollar quoted strings, but that's not possible as per the documentation: https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

> Indeed, no characters inside a dollar-quoted string are ever escaped: the string content is always written literally.

**Comment by lukaseder** [comment]
Thinking about this again, I don't want to change the default of `$$`. It is not really more likely to cause conflicts than any other token. But changing the default is likely to cause a regression in someone else's code.

**Comment by benhag** [comment]
It would be perfectly ok for me if the default remains unchanged, as long as I can configure another value.

I'm currently using `"tag_" + UUID.randomUUID().toString().replace('-', '_')` as token.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.19.0
