### ISSUE TITLE
Upgrade checkerframework to 3.19.0 to better support JDK 17

### ISSUE THREAD

**Issue by nicchongwb** [jOOQ/jOOQ#14806]
### Use case

Request to look into JDK 17 support for jooq-checker.

The `jooq-checker` relies on checkerframework. According to https://checkerframework.org/CHANGELOG.md checkerframework >= 3.19.0 support JDK 17. However, checkerframework 3.10.0 removed `SourceChecker.getChecker()`. The `getChecker()` method is being used in `org.jooq.checker` classes such as:
- JOOQ-checker/src/main/java/org/jooq/checker/AbstractChecker.java
- jOOQ-checker/src/main/java/org/jooq/checker/PlainSQLChecker.java
- jOOQ-checker/src/main/java/org/jooq/checker/SQLDialectChecker.java

This is a compare release of checkerframework 3.10.0 and 3.9.1:
- https://github.com/typetools/checker-framework/compare/checker-framework-3.9.1...checker-framework-3.10.0

SourceChecker.java

### Possible solution

In `checkerframework 3.9.1`, SourceChecker.getChecker() is declared as such:

```java
@Override
public SourceChecker getChecker() {
    return this;
}
```

We know that `getChecker()` is being used in `AbstractChecker` class that extends `SourceChecker` class. Also since `PlainSQLChecker` & `SQLDialectChecker` class extends `AbstractChecker` class, maybe instead of using `getChecker()` in the `AbstractChecker` class, we make the following changes:

```Java
// jOOQ-checker/src/main/java/org/jooq/checker/AbstractChecker.java
abstract class AbstractChecker extends SourceChecker {
	// Add getSourceChecker() to replace usage of getChecker()
	SourceChecker getSourceChecker() {
		return (SourceChecker) this;
	}

	Void error(Object node, String message) {
		// getChecker().report(Result.failure(message, node), node);
		getSourceChecker().report(Result.failure(message, node), node);
		return null;
	}

	// ...
}
```

Then in `PlainSQLChecker` & `SQLDailectChecker`, we replace `getChecker()` with `getSourceChecker()`

```Java
// jOOQ-checker/src/main/java/org/jooq/checker/PlainSQLChecker.java
public class PlainSQLChecker extends AbstractChecker {
	@Override
	protected SourceVisitor<Void, Void> createSourceVisitor() {
		
		// return new SourceVisitor<Void, Void>(getChecker()) { 
		//	...	
		// }

		return new SourceVisitor<Void, Void>(getSourceChecker()) { 
		//	...	
		}
	}
}
```

```Java
// jOOQ-checker/src/main/java/org/jooq/checker/SQLDialectChecker.java
public class SQLDialectChecker extends AbstractChecker {
	@Override
	protected SourceVisitor<Void, Void> createSourceVisitor() {
		
		// return new SourceVisitor<Void, Void>(getChecker()) { 
		//	...	
		// }

		return new SourceVisitor<Void, Void>(getSourceChecker()) { 
		//	...	
		}
	}
}
```

With this method, we avoid relying on `getChecker()` since its actual implementation at checkeframework <=3.9.1 is just to return the `SourceChecker` instance itself.

### Possible workarounds

None at the moment

### jOOQ Version

JOOQ Open Source 3.17.0

### Database product and version

 PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

### Java Version

java 17.0.6 2023-01-17 LTS

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by lukaseder** [comment]
Thanks a lot for your report.

We've had little community feedback in this area in the past, which is why we haven't tackled upgrading this module in the past yet. It's tricky, given the dual dependency on 2 not-too-well-maintained third parties.

But it's certainly something worth looking into again for jOOQ 3.19.

**Comment by nicchongwb** [comment]
> Thanks a lot for your report.
> 
> We've had little community feedback in this area in the past, which is why we haven't tackled upgrading this module in the past yet. It's tricky, given the dual dependency on 2 not-too-well-maintained third parties.
> 
> But it's certainly something worth looking into again for jOOQ 3.19.

Welcome. Just an update as I am currently working to see what must be changed for `jOOQ-checker` source files to support JDK 17 and also checkerframework >= 3.9.1

According to https://github.com/typetools/checker-framework/blob/master/docs/CHANGELOG.md#version-391-january-13-2021 , In checkerframework 3.9.1, the methods from `TreeUtils` were copied to `TreePathUtil`.

Then in https://github.com/typetools/checker-framework/blob/master/docs/CHANGELOG.md#version-3100-february-1-2021 , checkerframework 3.10.0 removed the methods on `TreeUtils` and suggested to use the ones in `TreePathUtil` instead.

In `jOOQ-checker/src/main/java/org/jooq/checker/Tools.java`, of JOOQ 3.18.0, the following imports were used:

```java
import static org.checkerframework.javacutil.TreeUtils.elementFromDeclaration;
import static org.checkerframework.javacutil.TreeUtils.elementFromUse;
import static org.checkerframework.javacutil.TreeUtils.enclosingClass;
import static org.checkerframework.javacutil.TreeUtils.enclosingMethod;
```

Solution:

```java
import static org.checkerframework.javacutil.TreePathUtil.elementFromDeclaration;
import static org.checkerframework.javacutil.TreePathUtil.elementFromUse;
import static org.checkerframework.javacutil.TreePathUtil.enclosingClass;
import static org.checkerframework.javacutil.TreePathUtil.enclosingMethod;
```

**Comment by nicchongwb** [comment]
@lukaseder I am able to get jooq-checker to work with JDK 17. However, I will need to add in the following `<compilerArgs>` arguments in the root pom.xml as follows:

```xml
<arg>--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</arg>
<arg>--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED</arg>
<arg>--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</arg>
<arg>--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>
<arg>--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</arg>
<arg>--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED</arg>
<arg>--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED</arg>
<arg>--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED</arg>
<arg>--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</arg>
<arg>--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
<arg>--add-exports=jdk.compiler/com.sun.source.tree=ALL-UNNAMED</arg>
```

However when I compile with the added `<arg>`, I will get the following error:

```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project jooq-checker: Compilation failure
[ERROR] error: exporting a package from system module jdk.compiler is not allowed with --release
[ERROR]
[ERROR] -> [Help 1]
```

This can be resolved by commenting out the `<release>17</release>` in root pom.xml's `maven-compiler-plugin` configuration.

**Comment by nicchongwb** [comment]
Hi I made a PR at https://github.com/jOOQ/jOOQ/pull/14881 for you to review the changes and test on your end, these changes worked for my standalone project.

**Summary**
Issue:
- Jooq-checker does not support JDK 17

Findings:
- The jooq-checker relies on checkerframework and checkerframework >= 3.19.0 supports JDK 17. Refer to https://github.com/typetools/checker-framework/blob/master/docs/CHANGELOG.md#version-3100-february-1-2021
- checkerframework 3.10.0 removed `getChecker()` method. Refer to https://github.com/typetools/checker-framework/blob/master/docs/CHANGELOG.md#version-3100-february-1-2021
- `AbstractMatcher.java` will need reflective access to `com.sun.tools.javac.tree.JCTree` 
- `SourceChecker` class will need reflective access to `com.sun.tools.javac.util`
- I suspect that `<release>17</release>` is automatically added by IntelliJ IDE. This will cause an issue for javac as we need to use `--add-exports` for compilerArgs. Refer to https://youtrack.jetbrains.com/issue/IDEA-176994

Side-note:
If the proposed solution is accepted, then moving forward it is important to comment out `<release>17</release>` in any pom.xml files (root project and subprojects)

---

**Solution**
Modify the relevant files.

pom.xml
- Comment out `<release>17</release>` due to https://youtrack.jetbrains.com/issue/IDEA-176994
- Upgraded org.checkerframework from 2.5.6 to 3.19.0 (minimum version for JDK 17)
- Added compilerArgs as checkerframework >= 3.10.0 need access to `com.sun.tools.javac.tree` and `com.sun.tools.javac.util`

jOOQ-xtend/pom.xml
- Comment out `<release>17</release>` due to https://youtrack.jetbrains.com/issue/IDEA-176994


jOOQ-checker/src/main/java/org/jooq/checker/AbstractChecker.java
- Removed `import org.checkerframework.framework.source.Result;`
- Added getSourceChecker()
- Replaced getChecker().report() call with this.getSourceChecker().reportError()

jOOQ-checker/src/main/java/org/jooq/checker/PlainSQLChecker.java
jOOQ-checker/src/main/java/org/jooq/checker/SQLDialectChecker.java
- Replaced getChecker() call with getSourceChecker()


jOOQ-checker/src/main/java/org/jooq/checker/Tools.java
- Replaced import classpath of TreeUtils to TreePathUtil (refer to https://github.com/typetools/checker-framework/blob/master/docs/CHANGELOG.md#version-391-january-13-2021)

**Comment by muehmar** [comment]
Any chance this would make it into a next jooq version? Luckily most of our projects are no longer based on JDK 8 :-)

**Comment by lukaseder** [comment]
Thanks a lot for your feedback folks. I can't make any promises. jOOQ 3.19 already has a ton of big features waiting to finish...

**Comment by nicchongwb** [comment]
> Any chance this would make it into a next jooq version? Luckily most of our projects are no longer based on JDK 8 :-)

You can make the following changes as shown in https://github.com/jOOQ/jOOQ/pull/14881 and just publish the jooq-checker library in the mean time.

You may want to have your own package path instead of org.jooq
and also have your own version specified. I used gradle to publish this jar artifact btw.

**Comment by lukaseder** [comment]
As commented here, I'll be looking into this now:
https://github.com/jOOQ/jOOQ/pull/14881#issuecomment-2015058878

The fix will be implemented in 3.20 only, without backports, as it requires a significant upgrade of a third party library.

**Comment by lukaseder** [comment]
I just realised, checkerframework 3.19 seems to still support JDK 8 as well (!) That would simplify things.

**Comment by lukaseder** [comment]
Nope. getting these errors on JDK 8 compilations:

```
[ERROR]   CheckerTest.testAllowOnlyFail:123 » NoSuchField ANNOTATION_PROCESSOR_MODULE_PATH
[ERROR]   CheckerTest.testAllowOnlyFailDefaultSystemProperty:147 » NoSuchField ANNOTATION_PROCESSOR_MODULE_PATH
[ERROR]   CheckerTest.testAllowOnlySuccess:81 » NoSuchField ANNOTATION_PROCESSOR_MODULE_PATH
[ERROR]   CheckerTest.testAllowOnlySuccessDefaultSystemProperty:103 » NoSuchField ANNOTATION_PROCESSOR_MODULE_PATH
[ERROR]   CheckerTest.testNoAllowOnAllSupportFail:185 » NoSuchField ANNOTATION_PROCESSOR_MODULE_PATH
[ERROR]   CheckerTest.testNoAllowOnNoSupportSuccess:169 » NoSuchField ANNOTATION_PROCESSOR_MODULE_PATH
[ERROR]   CheckerTest.testNoAllowOnSomeSupportFail:203 » NoSuchField ANNOTATION_PROCESSOR_MODULE_PATH
[ERROR]   CheckerTest.testPlainSQLFail:306 » NoSuchField ANNOTATION_PROCESSOR_MODULE_PATH
[ERROR]   CheckerTest.testPlainSQLSuccess:289 » NoSuchField ANNOTATION_PROCESSOR_MODULE_PATH
[ERROR]   CheckerTest.testRequireOnlyFail:240 » NoSuchField ANNOTATION_PROCESSOR_MODULE_PATH
[ERROR]   CheckerTest.testRequireOnlyFailDefaultSystemProperty:266 » NoSuchField ANNOTATION_PROCESSOR_MODULE_PATH
[ERROR]   CheckerTest.testRequireSuccess:222 » NoSuchField ANNOTATION_PROCESSOR_MODULE_PATH
```
