### ISSUE TITLE
How can I convert a field to SelectConditionStep?

### ISSUE THREAD

**Issue by skipkolch** [jOOQ/jOOQ#14805]
### Your question

I have a simple table:

```
CREATE TABLE segment
(
    id               SERIAL                      NOT NULL,
    last_update_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    life_time        INTEGER                     NOT NULL,
    CONSTRAINT segment_id_pk PRIMARY KEY (id)
);
```

I want to get a selection that fits the condition:
**`last_update_time < current_time - life_time`**, where
current_time - system current time (Timestamp)
life_time - lifetime in seconds

I'm writing a query using jooq:
```
fun expiredSegments(currentTime: Timeterm): List<SegmentRecord> {
    return configuration.dsl()
        .selectFrom(SEGMENT)
        .where(SEGMENT.LAST_UPDATE_TIME.le(SEGMENT.LIFE_TIME.convertFrom { currentTime.minusSeconds(it.toLong()) }))
        .fetch { it.into(SEGMENT) }
    }
```

and I get an exception:
`org.jooq.exception.DataAccessException: SQL [select "public"."segment"."id" from "public"."segment" where "public"."segment"."last_update_time" <= "public"."segment"."life_time"]; the operator does not exist: timestamp without time zone <= integer`

How can I convert a field to SelectConditionStep?

### jOOQ Version

3.17.5

### Database product and version

postgresql 12

### Java Version

17

### OS Version

Win 10

**Comment by lukaseder** [comment]
Thanks for your message.

Your question isn't really about how to convert a field to a `SelectConditionStep` (scalar subqueries can be created by wrapping them with `DSL.field(Select)`: https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/scalar-subqueries/)

Your question is how to implement an expression in jOOQ. Your mistake is that you tried to implement the expression on the client, in kotlin, but you really want a SQL expression like this:

````java
DSL.currentTimestamp().minus(SEGMENT.LIFE_TIME)
```

Does this help?

**Comment by lukaseder** [comment]
OK, then just wrap it with `DSL.val(currentTime)`

**Comment by lukaseder** [comment]
See: https://stackoverflow.com/q/67522537/521799
