### ISSUE TITLE
NPE in Converter.from(databaseObject) for NOT NULL column when using outer join

### ISSUE THREAD

**Issue by robbytx** [jOOQ/jOOQ#14816]
### Expected behavior

When applying a Converter to a `NOT NULL` column, I would expect the `Converter.from(databaseObject)` method to be invoked only with non-null values.  In the case of an outer join to the table, where the record is missing, I would expect the conversion process to be skipped, rather than invoked as `Converter.from(null)`.

### Actual behavior

When a `Result` contains a `NOT NULL` column whose value is null as a result of a missing outer join, it appears that jOOQ invokes `Converter.from(null)`, potentially violating the expectations of the converter implementation and producing an NPE:
```
Exception in thread "main" org.jooq.exception.DataAccessException: SQL [select `jooq_join_converter_npe_issue`.`parent`.`id`, `jooq_join_converter_npe_issue`.`parent`.`name`, `jooq_join_converter_npe_issue`.`parent`.`child_id`, `jooq_join_converter_npe_issue`.`child`.`id`, `jooq_join_converter_npe_issue`.`child`.`name` from `jooq_join_converter_npe_issue`.`parent` natural left outer join `jooq_join_converter_npe_issue`.`child` where `jooq_join_converter_npe_issue`.`parent`.`id` = ?]; Error while reading field: "jooq_join_converter_npe_issue"."child"."name", at JDBC index: 5
	at org.jooq_3.16.15.MYSQL.debug(Unknown Source)
	at org.jooq_3.16.15.MYSQL.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3123)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:689)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1464)
	at org.jooq.impl.CursorImpl$CursorIterator.hasNext(CursorImpl.java:1425)
	at org.jooq.impl.CursorImpl.fetchNext(CursorImpl.java:238)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:177)
	at org.jooq.impl.AbstractCursor.fetch(AbstractCursor.java:88)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:284)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2843)
	at example.Example.main(Example.java:29)
Caused by: java.sql.SQLException: Error while reading field: "jooq_join_converter_npe_issue"."child"."name", at JDBC index: 5
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1588)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1525)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.apply(CursorImpl.java:1484)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:143)
	at org.jooq.impl.CursorImpl$CursorIterator.fetchNext(CursorImpl.java:1449)
	... 9 more
Caused by: java.lang.NullPointerException
	at example.Example$StringCaseConverter.from(Example.java:37)
	at example.Example$StringCaseConverter.from(Example.java:33)
	at org.jooq.impl.DefaultBinding$InternalBinding.get(DefaultBinding.java:1017)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1578)
	... 13 more
```

This behavior does not match my expectations, and AFAICT it does not appear to have been reported as an issue.  I can sort of understand the rationale for jOOQ's behavior (i.e. "How can it know whether a column is null because of missing join vs just being null?"), except that `field.getDataType().nullable() == false` so it definitely *can* know the underlying field is not null.

I've reproduced this on the latest versions supported by my current configuration, and I am filing this bug report to solicit feedback on whether the behavior exhibited is expected and desired or not.  If it is not, then I am happy to re-confirm the issue remains on the latest available version, and consider whether/how this could be fixed.

### Steps to reproduce the problem

```sql
-- src/main/resources/db/migration/V1__create_schema.sql:

CREATE TABLE `child` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    PRIMARY KEY (`id`)
);

CREATE TABLE `parent` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(255) NOT NULL,
    `child_id` int(11) DEFAULT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `parent_child_id_fk` FOREIGN KEY (`child_id`) REFERENCES `child` (`id`)
);
```

```java
// src/main/java/example/Example.java

package example;

import com.mysql.cj.jdbc.MysqlDataSource;
import org.jooq.*;
import org.jooq.generated.tables.records.ParentRecord;
import org.jooq.impl.DSL;

import static org.jooq.generated.Tables.CHILD;
import static org.jooq.generated.Tables.PARENT;

public class Example {

    public static void main(String[] args) {
        MysqlDataSource dataSource = new MysqlDataSource();
        dataSource.setURL("jdbc:mysql://localhost:3306/");
        dataSource.setUser(System.getProperty("mysql.user", "root"));
        dataSource.setPassword(System.getProperty("mysql.password", ""));
        DSLContext SQL = DSL.using(dataSource, SQLDialect.MYSQL);

        ParentRecord parent = SQL.newRecord(PARENT);
        parent.setName("example");
        parent.store();
        System.out.println(parent);

        Result<Record> result = SQL.select()
                .from(PARENT)
                .naturalLeftOuterJoin(CHILD)
                .where(PARENT.ID.equal(parent.getId()))
                .fetch();
        System.out.println(result);
    }
    
    public static class StringCaseConverter implements Converter<String, String> {

        @Override
        public String from(String databaseObject) {
            return databaseObject.toLowerCase(); // NPE occurs here
        }

        @Override
        public String to(String userObject) {
            return userObject.toUpperCase();
        }

        @Override
        public Class<String> fromType() {
            return String.class;
        }

        @Override
        public Class<String> toType() {
            return String.class;
        }
    }
}
```

```xml
<!-- pom.xml -->

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>jooq-join-converter-npe-issue</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>

        <jooq.version>3.16.15</jooq.version>
        <mysql.database>jooq_join_converter_npe_issue</mysql.database>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>${jooq.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>8.0.31</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-maven-plugin</artifactId>
                <version>7.15.0</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>migrate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <url>jdbc:mysql://localhost:3306/information_schema</url>
                    <user>${mysql.user}</user>
                    <password>${mysql.password}</password>
                    <schemas>
                        <schema>${mysql.database}</schema>
                    </schemas>
                </configuration>
            </plugin>
            <plugin>
            <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>${jooq.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.16.0.xsd">
                    <jdbc>
                        <url>jdbc:mysql://localhost:3306/</url>
                        <user>${mysql.user}</user>
                        <password>${mysql.password}</password>
                    </jdbc>
                    <generator>
                        <database>
                            <name>org.jooq.meta.mysql.MySQLDatabase</name>
                            <inputSchema>${mysql.database}</inputSchema>
                            <forcedTypes>
                                <forcedType>
                                    <includeTypes>(?i)^varchar\(\d+\)$</includeTypes>
                                    <userType>String</userType>
                                    <nullability>NOT_NULL</nullability><!-- Converter applies only to NOT NULL columns! -->
                                    <converter>example.Example.StringCaseConverter</converter>
                                </forcedType>
                            </forcedTypes>
                        </database>
                    </generator>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

### jOOQ Version

3.16.15

### Database product and version

MySQL 5.7.35

### Java Version

openjdk version "11.0.15" 2022-04-19

### OS Version

macOS Monterery 12.6.3

### JDBC driver name and version (include name if unofficial driver)

com.mysql:mysql-connector-j:8.0.31

**Comment by lukaseder** [comment]
Thanks for your report.

The expectation for jOOQ to *"know"* why a certain value was `NULL` is a bold one, for there can be a lot of reasons for this to occur, including:

- Outer joins
- Unions
- Derived tables
- Any arbitrary usage where you have a query containing a column called `C` (but which isn't `C`), and you read that column using a `C` reference

The information about non-nullability is by no means reliable in general, even if it feels like this in your specific case. There are tons of discussions about this in the context of using jOOQ in kotlin. The topic is summarised here:
https://github.com/jOOQ/jOOQ/issues/13999

Ultimately, it's just better to always implement `null` aware converters.

I hope this helps.

**Comment by robbytx** [comment]
Thank you for the feedback.  I understand there are many challenges that make non-nullability difficult (or impossible) to implement in general across the jOOQ API, so it's necessary to assume that values can be null in most places, even if a specific column is not-null.

However, I'm wondering more specifically whether it is correct to invoke a converter using null for a non-null field.  If my converter were say something like:
```java
public class ToStringConverter<T> implements Converter<T, String> {

    @Override
    public String from(T databaseObject) {
        return String.valueOf(databaseObject);
    }

    ...
}
```

And if that converter were applied to a NOT NULL column, then it would work properly in the common cases, but it would result in `"null"` (a String) rather than a `null` value for the column in the case of an outer join, or other scenario where the result set contained null.  This is technically null-safe but incorrect nonetheless.

A workaround for this issue (which I believe could be embedded into codegen if not jOOQ itself) would be to wrap converters for non-null columns with null-safe protection using something like the following:
```java
public class NullSafeDelegatingConverter<T, U> extends AbstractConverter<T, U> {

    private final Converter<T, U> delegate;

    public NullSafeDelegatingConverter(Converter<T, U> delegate) {
        super(delegate.fromType(), delegate.toType());
        this.delegate = delegate;
    }

    @Override
    public final U from(T t) {
        return t == null ? null : delegate.from(t);
    }

    @Override
    public final T to(U u) {
        return u == null ? null : delegate.to(u);
    }
}
```

**Comment by lukaseder** [comment]
> However, I'm wondering more specifically whether it is correct to invoke a converter using null for a non-null field.

Yes it could be.

> This is technically null-safe but incorrect nonetheless.

Why not? *You* don't want this encoding (this time), but who knows if someone else does (or you, at some other occasion)? Maybe, someone doesn't like the default SQL `NULL` <-> Java `null` encoding from jOOQ, and overrides it with a `Converter` that never returns `null`, but some `NULL` object instead. Who is jOOQ to judge this person by removing that option in a clever amount of operators, such as left join (but not elsewhere!)? What about the `NULLIF(a, b)` function. Should that function inherit this cleverness and stop calling the `Converter` associated with it?

This idea is opening a can of worms of tons of edge cases that are probably not what *most* people want, whereas the status quo might not be what *some* people want, yet it is logical, predictable, and straightforward.

> A workaround for this issue (which I believe could be embedded into codegen if not jOOQ itself)

Yes, you can do that and wrap your own converter in that. jOOQ also has `Converter.ofNullable(...)`, which does the same thing.

There's nothing wrong with the premise of not wanting to handle this case in every converter all the time. But that doesn't mean that jOOQ should implement an immensely complex feature that fixes one thing but breaks another thing.

**Comment by lukaseder** [comment]
> (Although I've found such converters to be of limited utility in my applications because of other scenarios like unset values in records where the getter may still return Java null.)

Indeed, makes me wonder if the client side record initialisation should have passed through converters... It would be a subtle breaking change and probably not worth addressing, but interesting point.

> I suggest this behavior should at least be documented in the Converter API Javadoc and/or [in the manual](https://www.jooq.org/doc/3.19/manual/sql-execution/fetching/data-type-conversion/). I myself have been using jOOQ for 10 years, including a custom converter of this sort, and it was only recently that I stumbled across this behavior, since my application rarely uses outer joins.

But that kinda suggests that it's really an edge case, and that documentation might be more of a distraction / noise than help. I'm thinking about it this way. The status quo is logical and not really unexpected. It is easy to see that this design was chosen, as opposed to another, so no extra documentation is needed.

You would like to document a caveat about `LEFT JOIN` on the `Converter` Javadoc? But it's completely unrelated! Which other SQL operators would you then document on `Converter`? Or where? A "common" pitfalls page? But it doesn't appear to be common.

If this isn't about documenting `LEFT JOIN` on `Converter`, but about general `Converter` behaviour, then I'd argue it's already documented:

> Furthermore, it is recommended (yet not required) that 
> •converter.from(null) == null
> •converter.to(null) == null

From the above, one could derive that converter implementations are strongly recommended to be `NULL` aware. I guess I could make that explicit. "Implementations must be able to handle `null` conversions"

I think this may be a disconnect between what users expect from a `LEFT JOIN` and what it really is. "Regrettably," (or probably, conveniently) in SQL and relational algebra, `JOIN` results are "flattened," meaning the resulting column expression is somewhat disconnected from its original declaration. An interesting case is `A JOIN B USING (X)` where `X` can be `NOT NULL` in `A` but nullable in `B`. According to the SQL standard, only one unqualified column `X` should be resulting from this operation (as per the standard, `X := COALESCE(A.X, B.X)`). What is its nullability? It's `nullable(A.X) OR nullable(B.X)`. But what would this mean for jOOQ? That's what I meant by "complexity."

At the same time, it would often be more interesting to nest records of join operands, so `BOOK ⋈ AUTHOR` should produce a tuple of type `(BOOK, AUTHOR)` rather than `(BOOK.ID, BOOK.TITLE, AUTHOR.ID, AUTHOR.FIRST_NAME, ...)`. Once records are nested this way, one could argue that the entire record is `NULL` and thus we wouldn't have to look at individual attributes and their converters.

It would be very hard to get the semantics right, since the underlying SQL implementations cannot easily convey the information of whether the left joined row is really "completely `NULL`" or whether all of its columns are somehow "accidentally `NULL`." Scala's Slick tried to go down this route, if I'm not mistaken. They avoided the problem (I think) by not offering too many SQL primitives and pretending that Scala style `map` and `flatMap` etc. operations can be mapped to SQL. But the ensuing type nesting wasn't only well received with the community. All the unnesting that was required after a complex join graph seemed very tedious. It's always a tradeoff.

Anyway, since this nesting isn't happening, neither in SQL nor in jOOQ, the individual columns do become relevant, throughout the jOOQ API. Their non-nullability isn't guaranteed, their precise semantics depends on the context where they're used, and this produces 100s of little "caveats" that aren't really caveats, they're logical, unless the expectation is for a record to be nested, or for more sophisticated operators or functions to not exist.

However, the one place where additional documentation (in addition to this issue) could be added is https://stackoverflow.com/questions/tagged/jooq. Their SEO is very good, so other users who run into similar questions may find your question and my answer there, if you have some time.

**Comment by lukaseder** [comment]
Thanks a lot, I appreciate it. I will answer in a bit!
