### ISSUE TITLE
Question about manually closing a connection

### ISSUE THREAD

**Issue by AnvarYasinov1997** [jOOQ/jOOQ#14824]
### Your question

In the latest production build, I used jooq 3.17.4 and (r2dbc-pool, r2dbc-spi, r2dbc-postgresql) 0.9.1.RELEASE, I had a problem that when unsubscribing, the connection did not return to the pool, and I used the following construction

`private lateinit var connectionPool: ConnectionPool`

```kotlin
fun test() {
          val successBlock: (connection: Connection) -> Mono<*> = { connection ->
             Mono.from(connection.commitTransaction())
                .thenReturn(Unit)
                .then(Mono.from(connection.close()))
         }

        val errorBlock: (connection: Connection, e: Throwable) -> Mono<*> = { connection, _ ->
            Mono.from(connection.rollbackTransaction())
                .thenReturn(Unit)
                .then(Mono.from(connection.close()))
        }

        val cancelBlock: (connection: Connection) -> Mono<*> = { connection ->
            Mono.from(connection.rollbackTransaction())
                .thenReturn(Unit)
                .then(Mono.from(connection.close()))
        }

        val businessLogicFunction: (config: Configuration) -> Mono<Pair<FirstRecord, SecondRecord>> = { config: 
        Configuration ->
            // coroutine builder
            mono {
                val first = config.dsl().insertInto(FIRST)
                    .set(FIRST.TEST_DATA, "first test data - ${UUID.randomUUID()}")
                    .returning()
                    .awaitFirst()
                val second = config.dsl().insertInto(SECOND)
                    .set(SECOND.FIRST_ID, first.id)
                    .set(SECOND.TEST_DATA, "second test data - ${UUID.randomUUID()}")
                    .returning()
                    .awaitFirst()
                Pair(first, second)
            }
        }

        val dslContextBlock: (connection: Connection) -> Mono<Any> = { connection ->
            Mono.from(DSL.using(connection).transactionPublisher(businessLogicFunction))
        }

        runBlocking {
            // Here I don't use the DSL.using(connectionPool) method
            val savedPair =
                Mono.usingWhen(connectionPool.create(), dslContextBlock, successBlock, errorBlock, cancelBlock)
                    .awaitFirst()

            println(savedPair)
        }
 }
```

We have now updated jooq 3.18.0 and (r2dbc-pool, r2dbc-spi, r2dbc-postgresql) to version 1.0.0.RELEASE. Can the following code be used to manage connections reliably

```kotlin
fun test() {
        val businessLogicFunction: (config: Configuration) -> Mono<Pair<FirstRecord, SecondRecord>> { config: Configuration 
   ->
            // coroutine builder
            mono {
                val first = config.dsl().insertInto(FIRST)
                    .set(FIRST.TEST_DATA, "first test data - ${UUID.randomUUID()}")
                    .returning()
                    .awaitFirst()
                val second = config.dsl().insertInto(SECOND)
                    .set(SECOND.FIRST_ID, first.id)
                    .set(SECOND.TEST_DATA, "second test data - ${UUID.randomUUID()}")
                    .returning()
                    .awaitFirst()
                Pair(first, second)
            }
        }

        runBlocking {
            // 
            val savedPair =
                DSL.using(connectionPool).transactionPublisher(businessLogicFunction)
                    .awaitFirst()

            println(savedPair)
        }
}
```

Here I transfer control of the connection and the responsibility of rolling back the weight and committing it to api jooq.

Can I 100% trust DSL.using(connectionPool) to manage my pool and protect resource overkill like Mono.usingWhen()?

Sorry for the ugly format)

### jOOQ Version

3.18.0

### Database product and version

14.5-alpine

### Java Version

17

### OS Version

Ubuntu 20.04.3 LTS

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:r2dbc-postgresql:1.0.0.RELEASE

**Comment by lukaseder** [comment]
Thanks for your message.

Many bugs have been fixed. Perhaps you ran into one. I'm not sure what your actual question here is. `DSL.using(ConnectionFactory)` will attempt to implement the resource management lifecycle that does both `ConnectionFactory::create` and `Connection::close`, just like when you pass a JDBC `DataSource`.

Can you 100% trust it? Well, if there are no more undiscovered bugs left...? There were bugs like this one in the past: https://github.com/jOOQ/jOOQ/issues/13802. Not sure if this is what you have in mind.

**Comment by AnvarYasinov1997** [comment]
I want to note that I use the connection pool to initialize the DSLContext, for example, when a user request is canceled, my connection was not returned to the pool, and other clients could not use my pool, because the pool simply does not know that my client has released the connection

**Comment by lukaseder** [comment]
> I thought maybe you would have a quick answer for me, should I refuse to close connections manually, or can I be sure that in case of canceling the search for the source Publisher jooq will close the connection with 100% guarantee, as in the case of Mono.usingWhen( connectionPool.create, block, closeResourseBlock)

Well, that's the design. If you pass a `Connection`, then you own the connection and must close it yourself. If you pass a `ConnectionFactory`, then jOOQ owns the connection and closes it for you.

But I don't know what *100% guarantee* means. There's no such thing as exactly once delivery, so let's just focus on the intended design, and potential bugs that you may have encountered (ideally with reproducers).
