### ISSUE TITLE
Add warnings to manual and Javadoc about ON KEY ambiguity caveats

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14876]
The `ON KEY` feature is not really a good feature:
https://www.jooq.org/doc/latest/manual/sql-building/table-expressions/joined-tables/join-predicate-on-key/

It was relatively simple to implement in jOOQ 2.0:

- https://github.com/jOOQ/jOOQ/issues/578

... but then had tons of issues over the years:

- https://github.com/jOOQ/jOOQ/issues/2870
- https://github.com/jOOQ/jOOQ/issues/4637
- https://github.com/jOOQ/jOOQ/issues/5209
- https://github.com/jOOQ/jOOQ/issues/6266
- https://github.com/jOOQ/jOOQ/issues/7626
- https://github.com/jOOQ/jOOQ/issues/12200
- https://github.com/jOOQ/jOOQ/issues/12214
- https://github.com/jOOQ/jOOQ/issues/14668
- https://github.com/jOOQ/jOOQ/issues/14671
- https://github.com/jOOQ/jOOQ/issues/14870

Most issues were related to things not working when:

- Tables are aliased
- Join tables are nested
- Ambiguities are not discovered correctly

Even if all bugs are fixed, the feature has a significant flaw, similar to `JOIN .. USING` or `NATURAL JOIN`. It produces queries that are hard to evolve. For example:

```sql
CREATE TABLE author (id INT PRIMARY KEY);
CREATE TABLE book (id INT PRIMARY KEY, title TEXT, author_id INT REFERENCES author);
```

Now this query works:

```java
ctx.select()
   .from(AUTHOR)
   .join(BOOK).onKey()
   .fetch();
```

But after this schema change, the query stops working without any way to detect this at compile time:

```sql
ALTER TABLE book ADD co_author_id INT REFERENCES author;
```

The `onKey()` clause without explicit join column arguments is now ambiguous.

People like this feature, so it's not a candidate for deprecation. But at least, we should add a big warning to the manual and Javadoc.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.19.0, 3.18.2 (https://github.com/jOOQ/jOOQ/issues/14877), 3.17.11 (https://github.com/jOOQ/jOOQ/issues/14878), and 3.16.17 (https://github.com/jOOQ/jOOQ/issues/14879)

**Comment by pietrol83** [comment]
thank you very much for the information you gave me.

**Comment by lukaseder** [comment]
@pietrol83 You're welcome

**Comment by lukaseder** [comment]
while I'm documenting this, I'll also add a disclaimer to the equally dangerous `JOIN .. USING` and `NATURAL JOIN` syntaxes, at least in the manual.

**Comment by lukaseder** [comment]
The manual is being updated now, with the new disclaimers. I'll also add a section to the "Don't do this" section: 

- https://www.jooq.org/doc/latest/manual/reference/dont-do-this/
- https://github.com/jOOQ/jOOQ/issues/14552

While `ON KEY` isn't so risky (especially when passing explicit key references), the `NATURAL JOIN` clause should certainly not be used.
