### ISSUE TITLE
Use environment variable in XMLDatabase xml

### ISSUE THREAD

**Issue by seraphniu** [jOOQ/jOOQ#14900]
### Your question

Hey,

I'm trying to set up codegen in gradle, but jooq/XMLDatasource fail to use relative path before gradle set up its own working directly.

**build.gradle**
```
String jooqConfig = new File("$rootDir/jooq/jooq-config.xml").getText("UTF-8")
org.jooq.codegen.GenerationTool.generate(jooqConfig)
```

**jooq/jooq-config.xml** - this refers to ddl.xml for more configuration details. however the file cannot be located with relative path, although absolute path works. 
My question:  is there a way to use an environment variable here?  say ${rootDir}/jooq/ddl.xml. I tried but failed.
I couldn't find in the example/manual.

```
<configuration xmlns='http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd'>
  <generator>
    <database>
      <name>org.jooq.meta.xml.XMLDatabase</name>
      <properties>
        <property>
          <key>dialect</key>
          <value>MYSQL</value>
        </property>
        <property>
          <key>xml-file</key>
          <value>jooq/ddl.xml</value>
        </property>
      </properties>
    </database>
........
</configuration>
```
error:
```
Could not load schemata
java.lang.RuntimeException: Error while opening files jooq/ddl.xml or null
	at org.jooq.meta.xml.XMLDatabase.info(XMLDatabase.java:251)
	at org.jooq.meta.xml.XMLDatabase.getSchemata0(XMLDatabase.java:472)
```

test build.gradle without $rootDir: you can see gradle set working directory to gradle daemon folder. that's why jooq cannot locate the file.
```

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating root project 'test'.
> javax.xml.bind.UnmarshalException
   - with linked exception:
  [java.io.FileNotFoundException: /Users/xxxx/.gradle/daemon/5.6.4/jooq/jooq-config.xml (No such file or directory)]
```

### jOOQ Version

jooq professional edition 3.11.11

### Database product and version

mysql 5.7

### Java Version

openjdk version "1.8.0_332" Zulu 8.62.0.19-CA-macos-aarch64

### OS Version

MacOs 13.3 (22E252)

**Comment by lukaseder** [comment]
Thanks a lot for your message. There isn't any way to pass environment variables to that XML file. So far, the stance was that most people use Maven or Gradle and thus directly embed the XML in a Maven plugin (or the Groovy/Kotlin configuration in the Gradle plugin), where Maven's property support can be used.

Other users use programmatic configuration, in case of which custom parameters become trivial.

But there has been a previous feature request for the `DDLDatabase`, that could be extended here. It wouldn't be too hard to do: https://github.com/jOOQ/jOOQ/issues/7787

**Comment by lukaseder** [comment]
Note, you don't seem to be asking for this feature to be supported in the `XMLDatabase`'s XML, right? You're looking for this feature in the jOOQ code generation configuration file?

**Comment by lukaseder** [comment]
> current code generation works in amd64 macos, but not arm64 macos. The reason is that gradle uses project directory as working directory in amd64, but gradle's working directory points to gradle temporary folder.

I'm sure there's a gradle solution to this for the time being.

**Comment by lukaseder** [comment]
Other than that, you can always search-replace in your XML file to implement the feature yourself, as a workaround.
