### ISSUE TITLE
Work around Oracle 23c regression when nesting aggregate JSON functions in MULTISET

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#14902]
There seems to be a regression in queries like these:

```sql
select json_array(
  (
    select coalesce(
      json_arrayagg(json_array(v0)),
      json_array()
    )
    from (
      select json_array('Hello', 'World') v0
      from DUAL
    ) t
  )
) v0
from DUAL
```

This used to work on 21c, producing:

```
[[[["Hello","World"]]]]
```

But in 23c, we now get an error:

> SQL Error [978] [42000]: ORA-00978: nested group function without GROUP BY

That's a significant regression, which breaks most `MULTISET` usage. Luckily, it seems we can work around this regression by adding an explicit dummy `GROUP BY` clause:

```sql
select json_array(
  (
    select coalesce(
      json_arrayagg(json_array(v0)),
      json_array()
    )
    from (
      select json_array('Hello', 'World') v0
      from DUAL
    ) t
    group by null
  )
) v0
from DUAL
```

Note that `GROUP BY ()` (which is implicit in the absence of `GROUP BY`) also doesn't work.

While this Oracle bug probably affects all SQL queries, I trust that Oracle will provide a timely fix. In the meantime, we can at least patch our own `MULTISET` generated queries.

I've also reported this here:
https://forums.oracle.com/ords/apexds/post/regression-in-oracle-23c-when-nesting-json-aggregate-functi-9538

**Comment by lukaseder** [comment]
Hmm, a lot of `MULTISET` queries still work, e.g. this one:

```sql
select
  "TEST"."T_AUTHOR"."ID",
  "TEST"."T_AUTHOR"."FIRST_NAME" "nested.FIRST_NAME",
  "TEST"."T_AUTHOR"."LAST_NAME" "nested.LAST_NAME",
  (
    select coalesce(
      json_arrayagg(json_array("t"."v0" format json, "t"."v1" format json null on null returning clob) format json returning clob),
      json_array(returning clob)
    )
    from (
      select
        json_array("TEST"."T_BOOK"."ID", "TEST"."T_BOOK"."TITLE" null on null returning clob) "v0",
        (
          select coalesce(
            json_arrayagg(json_array("t"."v0" null on null returning clob) format json returning clob),
            json_array(returning clob)
          )
          from (
            select "TEST"."T_BOOK_TO_BOOK_STORE"."BOOK_STORE_NAME" "v0"
            from "TEST"."T_BOOK_TO_BOOK_STORE"
            where "TEST"."T_BOOK_TO_BOOK_STORE"."BOOK_ID" = "TEST"."T_BOOK"."ID"
            order by "v0"
            fetch next 9223372036854775807 rows only
          ) "t"
        ) "v1"
      from "TEST"."T_BOOK"
      where "TEST"."T_BOOK"."AUTHOR_ID" = "TEST"."T_AUTHOR"."ID"
      order by "TEST"."T_BOOK"."ID"
      fetch next 9223372036854775807 rows only
    ) "t"
  )
from "TEST"."T_AUTHOR"
order by "TEST"."T_AUTHOR"."ID"
```

Perhaps, this is very specific to our test suites using `SELECT .. FROM DUAL` queries.

**Comment by lukaseder** [comment]
Since we don't officially support 23c yet, I'll backport 23c related fixes only to the 3.18 branch, assuming that early adopters of Oracle 23c are also early adopters of jOOQ versions.

**Comment by GavinRay97** [comment]
Oh hey just as a heads-up, I hit this same bug with our manually-written JSON generating functions

I asked for an explanation and workaround on the forums:
- https://forums.oracle.com/ords/apexds/post/oracle-21c-bug-in-json-object-when-using-both-json-arrayagg-2528
- See the first long post by `Mathguy`, not sure how accurate it is, but it's very detailed
	- https://forums.oracle.com/ords/apexds/post/oracle-21c-bug-in-json-object-when-using-both-json-arrayagg-2528#comment_338540941487605298167799212825478060356

The `GROUP BY` solution is nice -- the way we discovered to work around it was the push the `json_arrayagg()` down into the subquery

**Comment by lukaseder** [comment]
Thanks for documenting this here, @GavinRay97. I had thought about adding the workaround to all queries that user `JSON_ARRAYAGG`, but then decided against it. There's too much risk of introducing something unwanted to arbitrary queries.

The `MULTISET` case is different, because there, users don't actually write any aggregate functions, so jOOQ has more "freedom" to rewrite the query.

I do hope this bug is temporary in Oracle, though. I don't know if mathguy is right. It's a regression, the query worked previously:
https://forums.oracle.com/ords/apexds/post/regression-in-oracle-23c-when-nesting-json-aggregate-functi-9538

Though, perhaps the cases are subtly different.
