### ISSUE TITLE
KotlinGenerator: Nullable `TableField`

### ISSUE THREAD

**Issue by atollk** [jOOQ/jOOQ#14929]
### Use case

(I realize that nullability is a recurring topic of discussion for jOOQ but afaik, this exact point has not been clarified.)

Currently, the `KotlinGenerator` generates `TableField`s with a nullable column type always. (See `JavaGenerator.java:6161`)

```java
            else if (kotlin) {
                out.println("%sval %s: %s<%s, %s?> = createField(%s.name(\"%s\"), %s, this, \"%s\"" + converterTemplate(converter) + converterTemplate(binding) + converterTemplate(generator) + ")",
                    columnVisibility, columnId, TableField.class, recordType, columnType, DSL.class, columnName, columnTypeRef, escapeString(comment(column)), converter, binding, generator);
            }
```

### Possible solution

I'd expect the nullability to be infered in some way and only added conditionally. I'd guess using the nullability of the DB column itself would be fine but maybe I am missing a use case where it's not?

If a direct change is not possible or unwanted, adding another nullability-flag to the generator, as was done with `kotlinNotNullPojoAttributes` and others recently, seems like an alternative.

### Possible workarounds

Add `?` and `!!` everywhere in our code, which is not only cumbersome but also loses the null-safety feature of Kotlin.

### jOOQ Version

3.18.2

### Database product and version

Postgres 15

### Java Version

Kotlin 1.6.10

### OS Version

macOS Ventura Version 13.2.1 (22D68)

**Comment by lukaseder** [comment]
Thanks for your suggestion. Please refer to https://github.com/jOOQ/jOOQ/issues/13999

> If a direct change is not possible or unwanted, adding another nullability-flag to the generator, as was done with `kotlinNotNullPojoAttributes` and others recently, seems like an alternative.

No, that's not a good alternative here, as I've illustrated numerous times in many discussions.

Even the POJO feature was a slippery slope, although I can see that the DAO / POJO use-case makes nullability non-ambiguous.

This is absolutely not the case with anything related to the DSL and query building. It would be a mistake to give this tool to users in the form of a configuration flag. See, again, https://github.com/jOOQ/jOOQ/issues/13999

> Add `?` and `!!` everywhere in our code, which is not only cumbersome but also loses the null-safety feature of Kotlin.

You don't have any nullability type safety either way.

If the lack of kotlin language support for platform types (which is the only sane choice here) is a burden, then please just use the `JavaGenerator`, or upvote the relevant kotlin language feature requests:

- https://youtrack.jetbrains.com/issue/KT-56899/Denotable-nullability-flexible-platform-types-T
- https://github.com/Kotlin/KEEP/issues/82
