### ISSUE TITLE
Manual section about code generation configuration contains wrong comment about LiquibaseDatabase

### ISSUE THREAD

**Issue by simasch** [jOOQ/jOOQ#14942]
### The documentation URL

https://www.jooq.org/doc/3.18/manual/code-generation/codegen-configuration/

### Feedback

This looks like a copy/paste mistake. The documentation for LiquibaseDatabase is not appropriate:

This value can be used to reverse-engineer schemas defined by JPA annotated entities
(requires jooq-meta-extensions-hibernate dependency)
                   
org.jooq.meta.extensions.jpa.JPADatabase
                   
This value can be used to reverse-engineer schemas defined by JPA annotated entities
(requires jooq-meta-extensions-liquibase dependency)
                   
org.jooq.meta.extensions.liquibase.LiquibaseDatabase

**Comment by lukaseder** [comment]
Yes, you're right, thanks a lot for the report.

**Comment by lukaseder** [comment]
Fixed. The manual will be updated in about 2h. Thanks again.
