### ISSUE TITLE
Possible problem when converting Instant to OffsetDateTime with different daylight saving time

### ISSUE THREAD

**Issue by ayzenquwe** [jOOQ/jOOQ#14943]
### Expected behavior

I'm adding a row into a table with a `timestamptz` column using `DSLContext`:
```
dsl.insertInto(table)
                .set(values)
                .returningResult(keys)
                .fetch();
```

I'm using Instant with this value: `2022-12-02T12:01:20Z`

I expect to see something like `2022-12-02T14:01:20+02:00` in the DB (using my local time offset).

### Actual behavior

Instead, I see `2022-12-02T13:01:20+02:00`, which is `2022-12-02T11:01:20Z` - one hour behind the timestamp I provided.

I suspect [this line](https://github.com/jOOQ/jOOQ/blob/ead855fc00a004a0d3e9d1f04ddacd092b29bc89/jOOQ/src/main/java/org/jooq/tools/Convert.java#L1376) from `org.jooq.tools.Convert.java` has a problem:
`return (X) toTimestamp(time, nanos).toLocalDateTime().atOffset(OffsetDateTime.now().getOffset());`

I'm currently located in Germany, so my current time zone is CEST (UTC+02:00) and CET (UTC+01:00) in Winter due to daylight saving time.

This is what happens from my understanding:
1. At the point when that line is being executed, time=1669982480000 and nanos=0. This is correct, as this value corresponds to `2022-12-02T12:01:20Z`, which I passed into JOOQ.
2. The method `toTimestamp` returns converted value with my local time zone: `2022-12-02T13:01:20+01:00`, which is still correct. The interesting thing here is that it uses my local time zone from this particular time, when it was Winter - CET (UTC+01:00).
3. The method `toLocalDateTime` returns the same time but without a time zone, which is `2022-12-02T13:01:20`. It's still correct, considering it was 13:01:20 (my local time) when the event happened.
4. The last part gets my CURRENT local time zone and applies it to the previous value to get `OffsetDateTime`. Since it's already mid April my local time zone is CEST (UTC+02:00), which means an incorrect offset is being used, resulting in `2022-12-02T13:01:20+02:00`.

### Steps to reproduce the problem

Save Instant with a different daylight saving time zone than it's now into timestamptz column. For example, you have CEST timezone now, save Instant with time when it was CET (somewhere in Winter).

### jOOQ Version

3.17.6

### Database product and version

PostgreSQL 14.3.2

### Java Version

Oracle 17.0.4

### OS Version

MacOS 12.6

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by frjonsen** [comment]
With Daylight Savings coming up in Europe in a few days, we also had some tests that started to fail due to this. We create schedules for triggering events in (now + 30 days), which creates timestamps in the next day DST period, which is inserting timestamps which are off by one hour (we are based in Sweden, so current  at CET, changing to CEST soon).

Did @ayzenquwe ever come up with a workaround?

**Comment by lukaseder** [comment]
Thanks for your patience, folks. I've just fixed this issue, which looks like a duplicate:

- https://github.com/jOOQ/jOOQ/issues/14866

The fix will ship today with:

- 3.20.0
- 3.19.7
- 3.18.14
- 3.17.23

If the issue you're seeing persists, please let me know and I'll reopen.
