### ISSUE TITLE
JOOQ batch with reactive way

### ISSUE THREAD

**Issue by ugurkas-gopuff** [jOOQ/jOOQ#14966]
### Your question

I am trying to make JOOQ batch insert/update by using reactive way but without execute statement it does not work.  
The following jooq code does not works, it throws error like `UnsupportedOperationException`:  After this batchUpsert I want to make other operations so I want to make it reactive. 

```java
  public Mono<Integer> batchUpsert(Collection<ProductRelation> relations) {
    if (relations.isEmpty()) {
      return Mono.just(0);
    }
    List<Query> queries = new ArrayList<>();
    for (ProductRelation relation : relations) {
      InsertOnConflictConditionStep<ProductRelationRecord> query = getUpsertQuery(relation);
      queries.add(query);
    }

    return Mono.from(dslContext.batch(queries));
  }
```

```java
  private InsertOnConflictConditionStep<ProductRelationRecord> getUpsertQuery(ProductRelation pr) {
    Condition isThereAnyDiff = PRODUCT_RELATION.QUANTITY.notEqual(pr.getQuantity());
    return dslContext.insertInto(PRODUCT_RELATION)
                     .set(PRODUCT_RELATION.PRODUCT_ID, pr.getProductId())
                     .set(PRODUCT_RELATION.RELATED_PRODUCT_ID, pr.getRelatedProductId())
                     .set(PRODUCT_RELATION.QUANTITY, pr.getQuantity())
                     .onConflict(PRODUCT_RELATION.PRODUCT_ID, PRODUCT_RELATION.RELATED_PRODUCT_ID)
                     .doUpdate()
                     .set(PRODUCT_RELATION.QUANTITY, pr.getQuantity())
                     .where(isThereAnyDiff);
  }
```

How can I run without execute? because with `execute` it is blocking call and it is not reactive code. If I add `execute`, it breaks the reactive chain. Till adding subscriber, I should not execute anything.

Could you please help me about this?

### jOOQ Version

3.18

### Database product and version

PostgreSQL 11.18 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit

### Java Version

19.0.2

### OS Version

macOS Ventura [Version 13.2]

**Comment by lukaseder** [comment]
Thanks for your message. The thing that isn't supported here is to run a batch on a JDBC connection using a reactive way. But I take this isn't what you wanted in the first place? Are you not using R2DBC? If you do, are you sure you have jOOQ configured correctly?

Note, that once you have this sorted, you will want to return a `Flux<Integer>`, as the batch will return multiple update counts.

**Comment by lukaseder** [comment]
I'll improve the exception to contain a more explicit error message: https://github.com/jOOQ/jOOQ/issues/14967

**Comment by ugurkas-gopuff** [comment]
Thanks for your quick response. Yes I am using R2DBC, do you support this `Flux.from(dslContext.batch(queries))` ? this throws error but if i put `execute`, it works (of course it is not reactive). However I've other read queries and they work. Also other insert/update queries work correctly. Only batch is failing.
``` java
Flux.from(dslContext.select()
                               .from(LOCATIONS))
               .map(dbRecord -> dbRecord.into(Locations.class));
``` 

```java
Mono.from(dslContext.insertInto(JOB)
                               .set(JOB.TYPE, jobRequest.getType().toString())
                               .set(JOB.PROPERTY_UPDATE_TYPE, jobRequest.getPropertyImportType().name())
                               .returning())
               .map(dbRecord -> dbRecord.into(Job.class));
```

**Comment by lukaseder** [comment]
> Yes I am using R2DBC, do you support this `Flux.from(dslContext.batch(queries))` ?

Yes, it's supported. Can you please post the stack trace?

> However I've other read queries and they work. Also other insert/update queries work correctly. Only batch is failing.

jOOQ has implemented the reactive APIs on both JDBC and R2DBC backed configurations, so most operations work even if you didn't correctly configure an R2DBC connection (but have a JDBC one).

I suspect you didn't configure jOOQ correctly.

**Comment by ugurkas-gopuff** [comment]
Hmm I've checked now this db and it uses jdbc:postgresql. And as far as I understand you don't support batch for JDBC connection using a reactive way. Actually we were using R2DBC but we changed it recently because of transactional problem (it was not working). If we change connection to R2DBC, it should work right?

**Comment by lukaseder** [comment]
There had been some bugs with R2DBC/jOOQ/transactions. The known bugs should be fixed now.

> And all R2DBC functionality works correctly ?

That's a bold question. This stuff is so terribly complicated on all levels, I will probably never say yes to this question.
