### ISSUE TITLE
Problem with queryTimeout() being ignored.

### ISSUE THREAD

**Issue by Timsgmlr** [jOOQ/jOOQ#14973]
### Your question

I'm using a streamed query which looks like this:
```
select(timestamp, value)
    .from(seriesId)
    .where(timebucket.between(properties.start).and(properties.end))
    .groupBy(timestamp)
    .orderBy(sortBy)
    .query    
.fetchSize(fetchSize)
.fetchStreamInto(SeriesPoint::class.java)
```

I want to close the stream after a certain time if the stream hasn't been consumed completely (e.g. due to a client-side issue).  I tried using queryTimeout() in the query directly and also setting it globally via a Spring configuration like so:
```
@Configurationclass JooqConfig {
@Bean    
fun jooqConfigurationCustomizer(@Value("\${series.points.stream-timeout}") queryStreamTimeout: Duration) =
        DefaultConfigurationCustomizer { config ->
            config.settings().withQueryTimeout(queryStreamTimeout.toSeconds().toInt())
        }
}
```

During debugging, I can see that the timeout is set in the DSLContext, but it's not actually cancelling the query. The expected behavior is that the query should be cancelled and the stream should be closed when the timeout is reached.

Could you please help me out on how to make the query timeout work for streamed queries? I'm not sure if there's an oversight on my end or if it's a jOOQ issue. 

### jOOQ Version

3.18

### Database product and version

PostgreSQL 15.2 (Ubuntu 15.2-1.pgdg22.04+1) 

### Java Version

17

**Comment by lukaseder** [comment]
Thanks for your message.

jOOQ doesn't manage resources for your. This particular flag is just being passed to the JDBC `Statement`, which can do whatever with it.

The pgjdbc driver uses a `TaskQueue` to call `Statement::cancel` eventually. I hope this helps with tracking down the problem.
