### ISSUE TITLE
EnumConverter that changes the casing of the names

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#14979]
### Your question

I want to write a custom `EnumConverter` that extends the default behavior but changes the name of the enum values from lowercase in the database to uppercase in Java. There doesn't seem to be a way to do this because `convert()` is not accessible outside of JOOQ.

### jOOQ Version

3.18.1

### Database product and version

Postgresql 15

### Java Version

20

### OS Version

Microsoft Windows [Version 10.0.19045.2846]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment]
Thanks for your message.

`EnumConverter` is just a bit of convenience, specific to the most common use-cases when mapping between numbers (ordinals) or strings to Java enums. You don't have to use it, you can use your own converter.

In this particular case, you can probably still use it and have your own implementation call the `EnumConverter(Class<T>, Class<U>, Function<? super U, ? extends T>)` constructor, where the function implements the logic you're looking for.

I'm not sure why you need jOOQ's internal  `convert()` utility here. I mean, jOOQ has a single utility for all types of common `T` <-> `U` conversions, but you don't really need it for this task?

Let me know if you have any remaining specific questions.

**Comment by cowwoc** [comment]
My understanding is that by default, JOOQ will generate Java-enums for each ENUM found in a Postgresql schema.

I want to create a generator that retains this behavior (processes all postgres enums) but changes the name of the Java ENUM values (I mistakenly referred to this as fields above).

Given:

```
CREATE TYPE auth_provider AS ENUM
(
  'evm',
  'email'
);
```

in the database schema, I want the following Java enum to get generated:

```
public enum AuthProvider implements EnumType {

    EVM("evm"),

    EMAIL("email");

    private final String literal;

    private AuthProvider(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "auth_provider";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static AuthProvider lookupLiteral(String literal) {
        return EnumType.lookupLiteral(AuthProvider.class, literal);
    }
}
```

Thoughts?

**Comment by lukaseder** [comment]
Ahhaaa 😅, then just use a generator strategy

- https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/
- https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/

**Comment by lukaseder** [comment]
Look for `<enumLiteral>`
