### ISSUE TITLE
ask for advice，How to use jooq to export all table structures of one database to sql script

### ISSUE THREAD

**Issue by 847689421** [jOOQ/jOOQ#14974]
### Your question

I want to export all the table structures of a certain database to sql scripts, is there any best practice for jooq? 
The method I can think of at present is to use org.jooq.DSLContext#meta().ddl() to obtain, and then traverse and call the toString() method of org.jooq.Query to output the string to a sql file.

### jOOQ Version

3.18.3

### Database product and version

mysql

**Comment by lukaseder** [comment]
Thanks for your message.

Apparently, you've already found the solution, so what questions remain?

**Comment by 847689421** [comment]
I'm not sure if there is another better way, so please ask. No more questions, sorry to bother you.

**Comment by lukaseder** [comment]
I'm not sure what exactly you're trying to achieve, so I'm not sure if there are any "better" solutions for you...
