### ISSUE TITLE
Pass TransactionDefinition to TransactionSubscription

### ISSUE THREAD

**Issue by pohlond** [jOOQ/jOOQ#14982]
### Use case

It would be nice to pass TransactionDefinition to org.jooq.impl.R2DBC.TransactionSubscription via org.jooq.impl.DefaultDSLContext#transactionPublisher.
Current implementation of TransactionSubscription calls c.beginTransaction().subscribe(...) on postgre connection but there is also an option to call  c.beginTransaction(td: TransactionDefinition).

### jOOQ Version

3.18.2

### Database product and version

PostgreSQL 13.7 (Debian 13.7-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**Comment by lukaseder** [comment]
Thanks a lot for your feature request. I'm assuming this is about `io.r2dbc.spi.TransactionDefinition`. I don't think we'll expose this type in our API, but rather, introduce our own way of modelling readonly transactions as well as the isolation level.

That request already has a ticket: https://github.com/jOOQ/jOOQ/issues/4836
