### ISSUE TITLE
OffsetDateTimeRange javadoc should reference tstzrange not tsrange

### ISSUE THREAD

**Issue by jmax01** [jOOQ/jOOQ#14995]
https://github.com/jOOQ/jOOQ/blob/55a74c04d78cdb3d34c7f7c7c3ab2af24129e68d/jOOQ-postgres-extensions/src/main/java/org/jooq/postgres/extensions/types/OffsetDateTimeRange.java#L43

**Comment by lukaseder** [comment]
Thanks a lot for your report and for your PR.

Fixed in jOOQ 3.19.0, 3.18.4 (https://github.com/jOOQ/jOOQ/issues/14999), and 3.17.13 (https://github.com/jOOQ/jOOQ/issues/15000)
