### ISSUE TITLE
Improve Javadoc of lookupLiteral() for generated enums

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#15024]
The Javadoc of `lookupLiteral()` in generated enums should be identical to `EnumType.lookupLiteral()`. Specifically, it should clarify that no match return null (it does not throw an exception).

**Comment by lukaseder** [comment]
Sure, why not.

**Comment by lukaseder** [comment]
For the record, I guess we could also generate the `@Nullable` annotation if that annotation is specified: https://github.com/jOOQ/jOOQ/issues/15025.
