### ISSUE TITLE
Emulate INSERT .. ON DUPLICATE KEY IGNORE in remaining dialects, using INSERT .. SELECT WHERE NOT EXISTS

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1503]
As suggested here:

https://github.com/jOOQ/jOOQ/issues/19

**Comment by bjcohen** [comment]
:+1:

**Comment by TheE** [comment]
Count this as interest.

**Comment by lukaseder** [comment]
That should do the trick. I suspect three interested users ought to be enough :)

**Comment by TheE** [comment]
Thanks. Still two questions:

1. Is there a reason why SQLite does not use the native [`INSERT OR IGNORE`](https://www.sqlite.org/lang_insert.html) command?
2. Are these changes planned for the 3.6 branch or will we need to wait for 3.7?

**Comment by lukaseder** [comment]
@TheE : Thanks for pointing this out. Yes, we should use SQLite's native syntax. I simply wasn't aware of it. This will be implemented with #4376.

These changes are due for jOOQ 3.7 (late 2015)
