### ISSUE TITLE
Why Record count and .offset() is int instead of long?

### ISSUE THREAD

**Issue by wwc7654321** [jOOQ/jOOQ#15040]
### Your question

I wander why jooq returns count as int instead of long, and offset is int too. 
Compared to spring and other framework, they choose long. Will this cause some error if records is more than MAX_INT ?

int org.jooq.DSLContext#fetchCount(...)
org.jooq.SelectLimitStep#offset(int)

### jOOQ Version

3.11.10

### Database product and version

mysql 5.7

### Java Version

1.8

**Comment by lukaseder** [comment]
Thanks for your report. See: https://github.com/jOOQ/jOOQ/issues/3714

TL;DR: Just historic reasons, mainly because JDBC used to return `int` for update counts, etc.
