### ISSUE TITLE
JOOQ execute system sql about pg_settings

### ISSUE THREAD

**Issue by lushengBrother** [jOOQ/jOOQ#15049]
### Your question

Will JOOQ execute the following system SQL when executing SQL
`select count(*) from pg_settings where name = 'support_batch_bind' and setting = 'on'`
I found that there are a large number of records of executing this SQL in the PG database pg_stat_activity

### jOOQ Version

3.11.4

### Database product and version

PostgreSQL 9.2

### Java Version

1.8

### OS Version

Red Hat 7.6

### JDBC driver name and version (include name if unofficial driver)

org.postgresql.Driver

**Comment by lukaseder** [comment]
Thank you very much for your message.

I'm sorry, I'm not sure what you're asking. Are you asking how to write this SQL query with jOOQ? Or, are you asking how to set a setting in PostgreSQL (with or without jOOQ)?

**Comment by lushengBrother** [comment]
> Thank you very much for your message.
> 
> I'm sorry, I'm not sure what you're asking. Are you asking how to write this SQL query with jOOQ? Or, are you asking how to set a setting in PostgreSQL (with or without jOOQ)?

None of them, I mean whether the JOOQ framework itself executes this SQL in the background, because I see a lot of this SQL in the active sessions of the PG database, but it is not the business SQL I wrote

**Comment by lukaseder** [comment]
I see, thanks for the clarification. No, jOOQ doesn't run any such queries unless you tell it to.
