### ISSUE TITLE
JOOQ creates SQL for incorrect colum type, when wrapped in a with-statement

### ISSUE THREAD

**Issue by ewirch** [jOOQ/jOOQ#15057]
### Expected behavior

JOOQ should generate SQL matching the colum type regaldless if the select statement is wrapped in a `with` statement, or not.

### Actual behavior

JOOQ generates different SQL in both cases. Select statement (not wrapped in `with` statements) generates correct SQL code. If the same statement is wrapped in a `with` statement, generated SQL is wrong.

### Steps to reproduce the problem

```java
// CAMPAIGN_REACH_HELPER.MONTHS is of type TableField<CampaignReachHelperRecord, String[]>
var singleSelect = jooq.select(DSL.asterisk()).from(CAMPAIGN_REACH_HELPER)
  .where(CAMPAIGN_REACH_HELPER.MONTHS.contains(new String[] {"JUNE"}))

singeSelect.getSQL(ParamType.INLINED);
// produces: select * from campaign_reach_helper where campaign_reach_helper.months @> cast(:1 as varchar[])

var wrappedInWith = DSL.with("result_query").as(singleSelect).select(DSL.asterisk()).from("result_query");
wrappedInWith.getSQL(ParamType.INLINED);
// produces: with "result_query" as (select * from "public"."campaign_reach_helper" where "public"."campaign_reach_helper"."months" like (('%' || cast(:1 as varchar)) || '%') escape '!') select * from result_query
```

Here are the both conditions side by side:
```
campaign_reach_helper.months @> cast(:1 as varchar[])
"public"."campaign_reach_helper"."months" like (('%' || cast(:1 as varchar)) || '%') escape '!'
```

If it helps, this is the configuration we use:
```java
DSLContext getJooqDslContext() {
    var settings = new Settings()
        .withRenderSchema(false)
        .withTransformInlineBindValuesForFieldComparisons(true);
    return DSL.using(SQLDialect.POSTGRES, settings);
}
```

### jOOQ Version

3.18.4

### Database product and version

PostgreSQL 13

### Java Version

temurin-19.0.2

### OS Version

Arch Linux

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.0

**Comment by ewirch** [comment]
Apparently the result is as expected, when I use `jooq.with()` instead of `DSL.with()`:
```java
jooq.with("result_query").as(singleSelect).select(DSL.asterisk()).from("result_query");
```
Is this behavior by design? I mean, regardless if I use `jooq.with()` or `DSL.with()`, the column passed to `where` has type information, and it is the same type.

**Comment by lukaseder** [comment]
Thanks for your message.

If you look at the APIs:

- `DSL` only offers static methods, which produce objects that do not have a `Configuration` "attached" (in the sense of `org.jooq.Attachable`)
- `DSLContext` is the "DSL in the context of a `Configuration`", which creates "attached" objects

See also:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/

**Comment by lukaseder** [comment]
Specifically, a `Query` that does not have any `Configuration` (and thus `SQLDialect`) can't possibly render PostgreSQL specific SQL.
