### ISSUE TITLE
Add DSLContext.transactionCoroutine overload accepting CoroutineContext

### ISSUE THREAD

**Issue by trietsch** [jOOQ/jOOQ#15103]
### Use case

The Kotlin Coroutines extension functions for jOOQ don't allow to set a coroutine context. This is necessary if the context contains information needed in the transaction. Currently, the `mono` function from Reactor creates a new, empty coroutine context.

### Possible solution

[Already made a PR](https://github.com/jOOQ/jOOQ/pull/15102), it is quite trivial.

### Possible workarounds

Rewrite the function ourselves, like we've currently done. But of course it's better if it's in the official library.

### jOOQ Version

jOOQ Open Source 3.18.4

### Database product and version

PostgresQL 12

### Java Version

Temurin 18

**Comment by lukaseder** [comment]
Thanks for your feature request and implementation suggestion. Can you:

- Show an example of where this would be useful in your client code?
- Explain why a seemingly backwards incompatible change is OK (i.e. is it really backwards incompatible, or will the change be source compatible in kotlin)?

**Comment by trietsch** [comment]
@lukaseder thanks for your reply! An example how we would use this, is to pass on a CoroutineContext from a parent. Here you can see how we're using it with our workaround.
```
val context = checkNotNull(coroutineContext[ZedTokenContext]) {
        "No ZedTokenContext found in coroutine context - should be set by the ZedTokenRequestServerInterceptor"
    }
jooq.transactionCoroutine(context) {
    // do DB work
}
```

This allows to pass on relevant context from a parent coroutine context, which I extract first.

This is not a backwards incompatible change, due to the fact that a default value has been provided in the suggested code change, that is identical to the default value that `mono` uses itself, namely `EmptyCoroutineContext`. The code therefore offers two functions, one without an argument, and one with an argument.

**Comment by lukaseder** [comment]
Can you please elaborate with a real world example of what this is useful for?

It's certainly binary incompatible, not sure if there are source incompatible implications. I agree that for some calls it might not matter, but I would really like to avoid incompatibilities if it's possible.

**Comment by trietsch** [comment]
All I can provide in terms of an example is our use case. In an RPC call (we're using gRPC with Kotlin), a token that is provided by an end-user of our APIs is added to the coroutine context. This call eventually ends up in a DAO, where we use a transaction to ensure that the database actions are in the same transaction as the interaction with an external permissions system, that needs to be modified as well, after the database actions are done. Hence, both the database actions and the interaction with the external permissions system are in the same transaction.
For the interaction with the external permissions system, we need to use the token that was set in the coroutine context. Therefore, we need to be able to access that value from the coroutine context within the transaction, as it is used there.

AFAIK it is source compatible, as it doesn't break existing usages of the current `transactionCoroutine` extension function.

By the way, great that you're thinking about compatibility and usages :)

**Comment by trietsch** [comment]
Alright, seems like a good conclusion for now. I won't make a MCVE for now, as that would just be setting a coroutine context with our specific coroutine context element, and then showing that we're going to access that in the transaction.
A real world example would include a gRPC app, that sets the context value in an interceptor, and then showing that that should still be accessible in the jooq transaction.

**Comment by lukaseder** [comment]
I've given this some additional thought. There's probably no issue with the overload approach, specifically if there's no default value for the `context` parameter. Will do this for 3.19

**Comment by trietsch** [comment]
Great, thanks for your help!

**Comment by lukaseder** [comment]
I'll backport this to:

- 3.18.5
- 3.17.14

Along with a bug fix, for a bug which you may have run into, as well? 

- https://github.com/jOOQ/jOOQ/issues/14997
