### ISSUE TITLE
How Do I Automatically Update the Update Time

### ISSUE THREAD

**Issue by loong024** [jOOQ/jOOQ#15106]
### Your question

How Do I Automatically Update the Update Time

### jOOQ Version

3.14.16

### Database product and version

PostgreSql

### Java Version

11

### OS Version

mac

**Comment by lukaseder** [comment]
Thanks a lot for your message. There are multiple ways to do this with jOOQ. The easiest is:

- [Audit columns](https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-audit/)
- [Client side computed columns](https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-computed/)

Audit columns are a special case of client side computed columns. You can also implement a `VisitListener` or a implement [model API replacement](https://www.jooq.org/doc/latest/manual/sql-building/model-api/model-api-replacement/). For simple cases, you could also implement a `RecordListener`, but that only works with `UpdatableRecord` operations, not with arbitrary DML.

Finally, you can also implement a server side trigger, which is usually the safest way to guarantee that such update time is always applied, no matter the client.
