### ISSUE TITLE
Maven generation plugin: avoid regeneration of sources if inputs haven't changed

### ISSUE THREAD

**Issue by nikita2206** [jOOQ/jOOQ#15172]
### Use case

I want to call it incremental compilation, but it's not really it.

When using Jooq's Maven code generation plugin, along with testcontainers (which allows for zero-dependency/zero-config onboarding of developers to projects using Jooq).
Every time you run `mvn compile` you incur regeneration of Jooq sources, which includes: starting up the testcontainer (with PostgreSQL in our case), applying all migrations, and then Jooq introspecting the schema and regenerating everything. (you can avoid Jooq's schema introspection and regeneration by using existing features, but starting up the container and applying migrations is one of the costliest steps, so I'm looking to avoid specifically these steps as well)

Some people tend to use `mvn compile` instead of IDE's built-in buiding infrastracture (e.g. IntelliJ's 'Build'), another issue we are hitting is that before each push we want to make it habit for everyone to run the checks such as ErrorProne, Formatting checks, etc., they happen to depend on recompilation (in other words we have to run `mvn compile` in this case).
I observe that Jooq's regeneration is by far the longest phase usually, because `javac` is most of the time avoided thanks to incremental recompilation. It also happens to be almost always unnecessary, as schema changes are not frequent.

### Possible solution

- Allow the users of the Maven codegen plugin specify which files are responsible for the schema, i.e. normally these would be migrations:
```
<schemaDefinitionInputs>
  <schemaDefinitionInput>${project.basedir}/src/main/resources/migrations</schemaDefinitionInput>
</schemaDefinitionInputs>
```

- Calculate the checksum of these migrations
- After generation phase is done, write that checksum along with the generated files in a separate file (e.g. `target/generated-sources/jooq/.jooq-checksum`)

Next time codegen plugin is invoked:
- Calculate the checksum of input files (migrations)
- Check if the target directory contains the `.jooq-checksum` file and if that file matches the checksum
- If checksums match, skip generation phase

I've implemented the idea described here to verify that it's possible with Maven, and that it will work as I expect it. The code may be better to demonstrate the idea than the text: https://github.com/nikita2206/jOOQ/pull/1

### Possible workarounds

- use gradle instead, which allows for very extensive customization: unfortunately that's not an option for us
- implement a Maven extension: this is completely workable, the only downside is that the experience wouldn't be out of the box, and this experience would be nice for anyone who's using Jooq's Maven codegen plugin, so it feels like a lot of people could benefit from it

### jOOQ Version

3.18.4

### Database product and version

PostgreSQL

**Comment by lukaseder** [comment]
Does this help?
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-version-providers/

**Comment by lukaseder** [comment]
I see.

Well jOOQ is unlikely to re-implement what gradle did much better here. In your case, the migrations are files located in a directory. But how to reliably find that snapshot without knowing exactly how the migration works? It's not impossible to implement something specific to 80% of Flyway's use-cases (always missing the remaining 20%), but wouldn't you much rather request this sort of feature from Maven (saying that Gradle already has it)? It would be a *much* better solution.

On the other hand, in a very simple case, you could just calculate the checksum with any arbitrary means in a maven plugin, compare that with a previously stored value, and then pass the `<skip/>` value to jOOQ's maven plugin, if needed. As you can see, this is again done completely outside of jOOQ, using a bunch of maven plugins, showing again that jOOQ maybe shouldn't be doing this itself.

I'm not completely against the idea, but it's work (especially maintenance work), and I think the ask from jOOQ here is exaggerated. jOOQ shouldn't know all that much about other software.

Having said so, this feature request has a high chance of being implemented:

- https://github.com/jOOQ/jOOQ/issues/13263

It will address the shortcomings of the existing schema / catalog version providers, which rely on knowledge of specific schemas / catalogs. I think that implementations that read the version from a file or system property would be sufficient to relatively easily implement your requirement with a few lines of plugin code.

**Comment by nikita2206** [comment]
Thanks for the expanded reply! GlobalVersionProvider idea might work indeed, as long as we are able to put the configuration somewhere (configuration that says where is the directory with SQL files), that's currently the issue with implementing it as a Maven extension for example. (in a multi-module Maven project, you can have multiple modules each with their own uses of jOOQ codegen plugin, so this can't be global per entire project)

As for the Gradle way, I'm actually unsure that Gradle implements it quite this same way (I couldn't find in the code where it tracks individual migration files, given that it's impossible to explicitly specify which files are feeding into the database), which leads me to suspect that it doesn't actually achieve this avoidance of regenerating jOOQ sources as long as migrations haven't changed?

Anyways, I understand your reluctance and will pursue the Maven extension route further, thank you.

**Comment by lukaseder** [comment]
> Thanks for the expanded reply! GlobalVersionProvider idea might work indeed, as long as we are able to put the configuration somewhere (configuration that says where is the directory with SQL files)

Well, the implementation can do that. There can be multiple implementations. Like the other version providers, it's just a Java interface that can supply a version string in any way it wants, including reading a checksum file from the disk.

> (in a multi-module Maven project, you can have multiple modules each with their own uses of jOOQ codegen plugin, so this can't be global per entire project)

The implementation could be configurable.

But frankly, this new SPI would just generate a version string into generated code, and then check if the current version matches the one from existing generated code, skipping re-generation if there's a match.

Relying on a `GlobalVersionProvider` doesn't really change all that much compared to doing all of this outside of jOOQ, and passing a `<skip/>` flag depending on some changed checksum/hash, because I doubt that the out of the box `GlobalVersionProvider` would offer such specific logic. Here's the code of the `CatalogVersionProvider` instantiation, for example:

```java
if (!isBlank(d.getCatalogVersionProvider())) {
    try {
        cvp = (CatalogVersionProvider) Class.forName(d.getCatalogVersionProvider()).newInstance();
        log.info("Using custom catalog version provider : " + cvp);
    }
    catch (Exception ignore) {
        if (d.getCatalogVersionProvider().toLowerCase(locale).startsWith("select")) {
            cvp = new SQLCatalogVersionProvider(connection, d.getCatalogVersionProvider());
            log.info("Using SQL catalog version provider : " + d.getCatalogVersionProvider());
        }
        else {
            cvp = new ConstantCatalogVersionProvider(d.getCatalogVersionProvider());
        }
    }
}
```

It would work the same way for the `GlobalVersionProvider`:

1. Try instantiating a class
2. Otherwise, try running a SQL query
3. Otherwise, use the value as a constant

I don't know if such a thing already exists, but it shouldn't be too hard to implement as a standalone maven plugin? Would be a fun project to open source. There's this source of inspiration, for example, but it doesn't do exactly what you need:
https://github.com/raphw/maven-checksum-extension

> As for the Gradle way, I'm actually unsure that Gradle implements it quite this same way (I couldn't find in the code where it tracks individual migration files, given that it's impossible to explicitly specify which files are feeding into the database), which leads me to suspect that it doesn't actually achieve this avoidance of regenerating jOOQ sources as long as migrations haven't changed?

I haven't investigated how it works exactly, but yes, that's exactly the promise:

https://github.com/etiennestuder/gradle-jooq-plugin#configuring-the-jooq-generation-task-to-participate-in-incremental-builds-and-build-caching

**Comment by nikita2206** [comment]
I'm actually doing something quite similar with the skip flag in the Maven extension, it should be relatively easy to port that to a GlobalVersionProvider once that is avaible 🙂
Looking forward to that!

> I haven't investigated how it works exactly, but yes, that's exactly the promise:

You're right, I'm just ignorant about how Gradle works and there's no example of declaring task inputs in the gradle-jooq-plugin's README. But indeed if you declare inputs this way `inputs.files(project.fileTree(dir: "resources", include: "migrations/*.sql"))`, this is quite brilliant from Gradle.
