### ISSUE TITLE
Make JDK 21 the baseline for the jOOQ Open Source Edition

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15177]
JDK 21 will be GA on 2023-09-19 (see https://openjdk.org/projects/jdk/21/). It is the next LTS build of Java. We can already create a jOOQ build for JDK 21 and offer this to paying customers (the jOOQ Open Source Edition will remain on a JDK 17 baseline for another while).

There are a few JEPs of interest to jOOQ:

- [JEP 430](https://openjdk.org/jeps/430): String templates. Useful for:
  - https://github.com/jOOQ/jOOQ/issues/15179
- [JEP 440](https://openjdk.org/jeps/440): Record patterns. Useful for:
  - https://github.com/jOOQ/jOOQ/issues/14577
- [JEP 446](https://openjdk.org/jeps/446): Scoped values (preview)
  - https://github.com/jOOQ/jOOQ/issues/15701
- [JEP 453](https://openjdk.org/jeps/453): Structured concurrency (preview)

From earlier JDK versions

- [JEP 408](https://openjdk.org/jeps/408): Simple web server
- [JEP 413](https://openjdk.org/jeps/413): Code snippets in Javadoc

**Comment by axelfontaine** [comment]
Another one to add to the list: update `DefaultExecutor` to use `Executors.newVirtualThreadPerTaskExecutor()`

**Comment by lukaseder** [comment]
> Another one to add to the list: update `DefaultExecutor` to use `Executors.newVirtualThreadPerTaskExecutor()`

Is that really necessary / a good idea? The default is using the fork join pool. Isn't that a good default anymore in JDK 21? Seems like an "art for art's sake" improvement, to me. I'm willing to look at specific use-cases, best practices, precedents from elsewhere.

**Comment by lukaseder** [comment]
This has been delayed a bit, but I think by now, it's safe to say JDK 21 is the new stable build with JDK 22 having shipped already and JDK 23 being around the corner:

- https://en.wikipedia.org/wiki/Java_version_history

Instead of offering a JDK 21 build to paying customers only, we'll increase the baseline to 21 for all distributions, and offer JDK 17, 11, and 8 builds only to paying customers, starting from jOOQ 3.20.

A new support matrix website will help document this:
https://github.com/jOOQ/jOOQ/issues/17104

**Comment by lukaseder** [comment]
A new website documents the JDK version support across editions:

- https://github.com/jOOQ/jOOQ/issues/17104
- https://www.jooq.org/download/support-matrix-jdk
