### ISSUE TITLE
Duplicated suffix when overriding pojo class name rule

### ISSUE THREAD

**Issue by leonkacowicz** [jOOQ/jOOQ#15206]
### Expected behavior

```kotlin
.withStrategy(
    Strategy().withMatchers(
        Matchers().withTables(
            MatchersTableType()
                .withExpression(".*")
                .withPojoClass(
                    MatcherRule()
                        .withTransform(MatcherTransformType.PASCAL)
                        .withExpression("$0_dto")
                )
        )
    )
)
```

This code should make the pojo classes look like "BookDto", "AuthorDto", etc.

### Actual behavior

Jooq is generating the pojo classes like "BookDtoDto", "AuthorDtoDto", etc.

### Steps to reproduce the problem

Run the jooq code generator using the following strategy:

```
.withStrategy(
    Strategy().withMatchers(
        Matchers().withTables(
            MatchersTableType()
                .withExpression(".*")
                .withPojoClass(
                    MatcherRule()
                        .withTransform(MatcherTransformType.PASCAL)
                        .withExpression("$0_dto")
                )
        )
    )
)
```

### jOOQ Version

jOOQ community version 3.18.4 (org.jooq:jooq-codegen:3.18.4)

### Database product and version

PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

### Java Version

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment (build 17.0.7+7) OpenJDK 64-Bit Server VM (build 17.0.7+7, mixed mode)

### OS Version

linux kernel 6.3.6

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by leonkacowicz** [comment]
I just tested the expression as `^.*$` instead o `.*` and the problem seems to go away.

**Comment by leonkacowicz** [comment]
Apparently:
`Pattern.compile(".*").matcher("abc").replaceAll("$0_suffix")` returns `"abc_suffix_suffix"`, and `Pattern.compile("^.*$").matcher("abc").replaceAll("$0_suffix")` returns `"abc_suffix"`.
And I don't know if this is a bug or the specified behavior.

**Comment by leonkacowicz** [comment]
The reason for this is that the regex first matches the string "abc" starting at 0 and with length 3, and then it matches the empty string starting at 3 with length 0, and replaces that empty string with "_suffix" again.

**Comment by leonkacowicz** [comment]
This is just some weird edge case from the java regex matcher, I believe it's ok to resolve this issue as "Won't Fix"

**Comment by lukaseder** [comment]
Thanks for your report. Indeed, this is a very "fun" caveat of Java's regular expression implementation. I think everyone finds this out the hard way, me included: 😅
https://stackoverflow.com/a/71674370/521799
