### ISSUE TITLE
change in seekAfter / orderBy count mismatch handling in 3.15.0+ intentional or not?

### ISSUE THREAD

**Issue by FyiurAmron** [jOOQ/jOOQ#15211]
### Your question

in jOOQ versions before 3.15.0 (3.14.16 included), in case you had `seekAfter` call with e.g. 2 arguments, but the `orderBy` had e.g. 1 argument, the code handled it gracefully, via (partial snippet from `Tools.java` from 3.14.16)

```
    private final List<? extends Field<?>> seekValues(Object[] values) {
        if (getQuery() instanceof SelectQueryImpl) {
            SelectQueryImpl<R> query = (SelectQueryImpl<R>) getQuery();
            List<Field<?>> fields = query.getOrderBy().fields();
            DataType<?>[] types = new DataType[fields.size()];

            for (int i = 0; i < types.length; i++)
                types[i] = fields.get(i).getDataType();

            return Tools.fields(values, types);
        }
        else
            return Tools.fields(values);
    }
    
    static final List<Field<?>> fields(Object[] values, DataType<?>[] types) {
        if (values == null || types == null)
            return new ArrayList<>();

        int length = Math.min(values.length, types.length); // NOTE THIS! :)
        List<Field<?>> result = new ArrayList<>(length);

        for (int i = 0; i < length; i++)
            result.add(field(values[i], types[i]));

        return result;
    }
```

Even on count mismatch, length was valid and the fields were set correctly. However, from 3.15.0+, we have

```
    @SuppressWarnings("unchecked")
    static final <T> Field<T>[] fieldsArray(Object[] values, DataType<T> type) {
        return map(values, v -> field(v, type), Field[]::new);
    }

    static final List<Field<?>> fields(Object[] values, DataType<?>[] types) {
        return asList(fieldsArray(values, types));
    }
```
etc. used for that, which obviously crashes in such case with the less-than-understandable `ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1` . Is this change in behaviour intentional or not? I wasn't able to find anything about this directly in 3.15.0 release notes or docs. If it is not intentional, is this actually a bug or a gray area? If it's intentional, where can I find more documentation about this case, and would adding a better error message to this exception (or simply using a more explicit exception and message) be possible?

### jOOQ Version

jOOQ 3.14.16 vs jOOQ 3.15.0+

### Database product and version

N/A

### Java Version

N/A

### OS Version

N/A

### JDBC driver name and version (include name if unofficial driver)

N/A

**Comment by lukaseder** [comment]
I see, so you passed arrays or collections, not individual fields. This may have worked by accident. What would be a use-case of passing too many fields to the seek clause? I can see to few (though the ordering would be unstable, so the feature wouldn't be used correctly). But why pass too many?

**Comment by FyiurAmron** [comment]
@lukaseder honestly? I can't say, this is a legacy code from people I won't even be able to meet :D I think they did it by mistake or omission, as I also see no real sense in it, though still it worked without crashing for `3.14.16` and before.

Assuming this is indeed the case (i.e. that the old behaviour was unintentional and that it basically makes no sense to do it so it should throw), what would you say about improving that exception? I.e. checking if the lengths are valid for the `seekAfter`, and throwing either a more explicit exception or at least improving on the message somehow?

**Comment by lukaseder** [comment]
> and throwing either a more explicit exception or at least improving on the message somehow?

Yeah, maybe that could be done. I'll think about it, as well as improving other field list size comparisons, which may be similar:

- https://github.com/jOOQ/jOOQ/issues/15222

The reason this hasn't been checked yet is because in 80% of API usages, which aren't dynamic SQL, the Java compiler already prevents this misuse, but of course the collection accepting overloads have to be dealt with separately.

I'm closing this as the question has been answerd. Further work will be done in #15222
