### ISSUE TITLE
SelectImpl.asTable() produces invalid SQL if columns have the same unqualified name

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#15227]
### Steps to reproduce the problem

Given a `SelectImpl` representing this query:

```
SELECT "public"."quest"."id",
       "public"."quest"."project_id",
       "public"."quest"."quest_type_id",
       "public"."quest"."name",
       "public"."quest"."description",
       "public"."quest"."summary",
       "public"."quest"."hero_img",
       "public"."quest"."card_img",
       "public"."quest"."achievement_img",
       "public"."quest"."start_at",
       "public"."quest"."end_at",
       "public"."quest"."created_at",
       "public"."user_quest"."user_id",
       "public"."user_reward_verified"."user_id",
       "public"."user_reward_claimed"."user_id"
FROM   "public"."quest"
       JOIN "public"."quest_reward"
         ON "public"."quest_reward"."quest_id" = "public"."quest"."id"
       LEFT OUTER JOIN "public"."user_quest"
                    ON ( "public"."user_quest"."quest_id" =
                         "public"."quest"."id"
                         AND "public"."user_quest"."user_id" = 1 )
       LEFT OUTER JOIN "public"."user_reward_verified"
                    ON ( "public"."user_reward_verified"."reward_id" =
                         "public"."quest_reward"."id"
                         AND "public"."user_reward_verified"."user_id" = 1 )
       LEFT OUTER JOIN "public"."user_reward_claimed"
                    ON ( "public"."user_reward_claimed"."reward_id" =
                         "public"."quest_reward"."id"
                         AND "public"."user_reward_claimed"."user_id" = 1 )
WHERE  ( "public"."quest"."id" <> "public"."quest"."id"
          OR ( "public"."user_quest"."user_id" = 1
               AND "public"."user_reward_verified"."reward_id" IS NOT NULL
               AND "public"."user_reward_claimed"."reward_id" IS NOT NULL )
          OR ( "public"."user_quest"."user_id" = 1
               AND "public"."user_reward_verified"."reward_id" IS NULL
               AND "public"."user_reward_claimed"."reward_id" IS NULL )
          OR "public"."user_quest"."user_id" IS NULL ) 
```

invoking `SelectImpl.fields()` invokes `asTable()` somewhere under the hood, which results in JOOQ transforming the query into:

```
SELECT "alias_77239393"."id",
       "alias_77239393"."project_id",
       "alias_77239393"."quest_type_id",
       "alias_77239393"."name",
       "alias_77239393"."description",
       "alias_77239393"."summary",
       "alias_77239393"."hero_img",
       "alias_77239393"."card_img",
       "alias_77239393"."achievement_img",
       "alias_77239393"."start_at",
       "alias_77239393"."end_at",
       "alias_77239393"."created_at",
       "alias_77239393"."user_id",
       "alias_77239393"."user_id",
       "alias_77239393"."user_id"
FROM   (SELECT "public"."quest"."id",
               "public"."quest"."project_id",
               "public"."quest"."quest_type_id",
               "public"."quest"."name",
               "public"."quest"."description",
               "public"."quest"."summary",
               "public"."quest"."hero_img",
               "public"."quest"."card_img",
               "public"."quest"."achievement_img",
               "public"."quest"."start_at",
               "public"."quest"."end_at",
               "public"."quest"."created_at",
               "public"."user_quest"."user_id",
               "public"."user_reward_verified"."user_id",
               "public"."user_reward_claimed"."user_id"
        FROM   "public"."quest"
               JOIN "public"."quest_reward"
                 ON "public"."quest_reward"."quest_id" = "public"."quest"."id"
               LEFT OUTER JOIN "public"."user_quest"
                            ON ( "public"."user_quest"."quest_id" =
                                 "public"."quest"."id"
                                 AND "public"."user_quest"."user_id" = 1 )
               LEFT OUTER JOIN "public"."user_reward_verified"
                            ON ( "public"."user_reward_verified"."reward_id" =
                                 "public"."quest_reward"."id"
                                 AND "public"."user_reward_verified"."user_id" =
                                     1 )
               LEFT OUTER JOIN "public"."user_reward_claimed"
                            ON ( "public"."user_reward_claimed"."reward_id" =
                                 "public"."quest_reward"."id"
                                 AND "public"."user_reward_claimed"."user_id" =
                                     1 )
        WHERE  ( "public"."quest"."id" <> "public"."quest"."id"
                  OR ( "public"."user_quest"."user_id" = 1
                       AND "public"."user_reward_verified"."reward_id" IS NOT
                           NULL
                       AND "public"."user_reward_claimed"."reward_id" IS NOT
                           NULL )
                  OR ( "public"."user_quest"."user_id" = 1
                       AND "public"."user_reward_verified"."reward_id" IS NULL
                       AND "public"."user_reward_claimed"."reward_id" IS NULL )
                  OR "public"."user_quest"."user_id" IS NULL )) AS
       "alias_77239393" 
```

There are two problems with this:

1. I asked for the names of the fields in the original SQL query, not the new names it created in the aliased field.
2. The new query is invalid because:

```
"public"."user_quest"."user_id",
"public"."user_reward_verified"."user_id",
"public"."user_reward_claimed"."user_id"
```

are converted into:

```
"alias_77239393"."user_id",
"alias_77239393"."user_id",
"alias_77239393"."user_id"
```

and PostgreSQL complains:

```
org.jooq.exception.DataAccessException: SQL [
select "alias_77239393"."id",
			 "alias_77239393"."project_id",
			 "alias_77239393"."quest_type_id",
			 "alias_77239393"."name",
			 "alias_77239393"."description",
			 "alias_77239393"."summary",
			 "alias_77239393"."hero_img",
			 "alias_77239393"."card_img",
			 "alias_77239393"."achievement_img",
			 "alias_77239393"."start_at",
			 "alias_77239393"."end_at",
			 "alias_77239393"."created_at",
			 "alias_77239393"."user_id",
			 "alias_77239393"."user_id",
			 "alias_77239393"."user_id"
from (select "public"."quest"."id",
						 "public"."quest"."project_id",
						 "public"."quest"."quest_type_id",
						 "public"."quest"."name",
						 "public"."quest"."description",
						 "public"."quest"."summary",
						 "public"."quest"."hero_img",
						 "public"."quest"."card_img",
						 "public"."quest"."achievement_img",
						 "public"."quest"."start_at",
						 "public"."quest"."end_at",
						 "public"."quest"."created_at",
						 "public"."user_quest"."user_id",
						 "public"."user_reward_verified"."user_id",
						 "public"."user_reward_claimed"."user_id"
			from "public"."quest"
						 join "public"."quest_reward" on "public"."quest_reward"."quest_id" = "public"."quest"."id"
						 left outer join "public"."user_quest"
														 on ("public"."user_quest"."quest_id" = "public"."quest"."id" and
																 "public"."user_quest"."user_id" = ?)
						 left outer join "public"."user_reward_verified" on ("public"."user_reward_verified"."reward_id" =
																																 "public"."quest_reward"."id" and
																																 "public"."user_reward_verified"."user_id" =
																																 ?)
						 left outer join "public"."user_reward_claimed"
														 on ("public"."user_reward_claimed"."reward_id" = "public"."quest_reward"."id" and
																 "public"."user_reward_claimed"."user_id" = ?)
			where ("public"."quest"."id" <> "public"."quest"."id" or ("public"."user_quest"."user_id" = ? and
																																"public"."user_reward_verified"."reward_id" is not null and
																																"public"."user_reward_claimed"."reward_id" is not null) or
						 ("public"."user_quest"."user_id" = ? and "public"."user_reward_verified"."reward_id" is null and
							"public"."user_reward_claimed"."reward_id" is null) or
						 "public"."user_quest"."user_id" is null)) as "alias_77239393"];
ERROR: column reference "user_id" is ambiguous
```

### jOOQ Version

3.18.3

### Database product and version

PostgreSQL 15.0, compiled by Visual C++ build 1914, 64-bit

### Java Version

openjdk version "20" 2023-03-21

### OS Version

Microsoft Windows [Version 10.0.19045.3031]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment]
Thank you very much for your report. Can you please provide an *exact* reproducer, ideally a minimal one (e.g. based on this template: https://github.com/jOOQ/jOOQ-mcve, but that may not be necessary), where you show jOOQ code and what kinds of calls produce the problem? Otherwise, it will be very hard to be sure I'm looking at the exact problem you're experiencing.

**Comment by jkmtumulak516** [comment]
I created a MCVE here: https://github.com/jkmtumulak516/jOOQ-mcve-issue-15227.

```zsh
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JavaTest.mcveTest:119 » DataAccess SQL [select "alias_39380357"."cd", "alias_39380357"."cd" from (select "mcve"."test"."cd", "mcve"."other"."cd" from "mcve"."test" join "mcve"."other" on "mcve"."test"."id" = "mcve"."other"."test_id") as "alias_39380357"]; ERROR: column reference "cd" is ambiguous
  Position: 8
[INFO] 
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

```

**Comment by lukaseder** [comment]
Thanks a lot for taking the time, @jkmtumulak516. I'll check it out right away.

**Comment by lukaseder** [comment]
Hm, I see, I thought that this was about something where jOOQ generated ambiguous column names in a derived table, which would be a bug.

But here, you're explicitly declaring ambiguous columns in a derived table, which isn't supported by any RDBMS. What would you want jOOQ to do here? Transform your SQL query to "make it work"?

I mean, it's possible, but very laborious. We'd have to transform the entire query on all scope levels. For example:

```sql
SELECT c1 AS a, c2 AS a -- Unalias generated aliases
FROM (
  SELECT *
  FROM (
    SELECT t1.a AS c1, t2.a AS c2 -- Generated aliases
    FROM t1, t2
  )
)
```

But if you reference the columns (you'd expect `T1.A` to be there somehow), then it gets more hairy:

```sql
SELECT c1 AS a, c2 AS a
FROM (
  SELECT *
  FROM (
    SELECT t1.a AS c1, t2.a AS c2
    FROM t1, t2
  )
  WHERE c1 = 'x' AND c2 = 'y' -- Substitute expressions by aliases
)
```

What if you added the original expressions again in scope?


```sql
SELECT c1 AS a, c2 AS a
FROM (
  SELECT t1.a AS c1 -- Realias this scope's column again!
  FROM (
    SELECT t1.a AS c1, t2.a AS c2
    FROM t1, t2
  ), t1
  WHERE t1.a = 'x' AND c2 = 'y' -- Substitute expressions by aliases, but only from nested scopes!
)
```

This gets hairier and hairier the more you think about it. What if your `t1.a` columns already have an alias, that you prefer over the generated one? Should we again re-alias the expression or not?

This is a particular SQL feature that jOOQ won't attempt to fix for users. Yes, it's annoying that derived tables can't have ambiguous column names, even if you're only projecting them, never referencing them. Top level queries don't have this problem, but derived tables do.

Note, you can always use the replacement API to pattern match any such derived tables and transform the query to something that you prefer, if you're looking for a generic solution:
https://www.jooq.org/doc/latest/manual/sql-building/model-api/model-api-replacement/

Or, you just alias the columns, explicitly.

**Comment by cowwoc** [comment]
> you're explicitly declaring ambiguous columns in a derived table

Can you please clarify? Where is the derived table coming from? I don't see it when I look at https://github.com/jOOQ/jOOQ-mcve/compare/main...jkmtumulak516:jOOQ-mcve-issue-15227:main#diff-f5948193c16ff23f9b6bcb3f9162fd959d37e00d7be11cd523d823d68ce56d2dR99?

Also, correct me if I'm wrong, but I'm expecting `query.fields()` to return `TEST.CD, OTHER.CD`. What's wrong with this assumption, and is there any other way for me to retrieve those fields at runtime?

**Comment by lukaseder** [comment]
Sure, no problem. The derived table is right here:
https://github.com/jkmtumulak516/jOOQ-mcve-issue-15227/blob/6a1c63b0999b674ac6a646eb737a6d895b136011/jOOQ-mcve-java-postgres/src/test/java/org/jooq/mcve/test/java/postgres/JavaTest.java#L117

```java
        Select<Record> secondQuery  = ctx.select(selectFields)
            .from(query);
```

You're putting a query in a `FROM` clause. See also:
https://www.jooq.org/doc/latest/manual/sql-building/table-expressions/derived-tables/

> Also, correct me if I'm wrong, but I'm expecting `query.fields()` to return `TEST.CD, OTHER.CD`. What's wrong with this assumption

Yes, the assumption here is wrong, although, I can see how you came to make it. Think about it this way. A query is a "closed" object that behaves "like a `Table`". That's why `Select<R> extends TableLike<R>`. That subtype relationship allows you to use queries in a lot of places where you can use a `Table`, for convenience. I.e. you can place it in the `FROM` clause without explicitly specifying a correlation name (alias), which is required in most dialects. If you don't provide one, jOOQ will generate it for you, based on the query contents. That would be the `alias_39380357` in your case.

Now, if a query should behave like a `Table`, then its various `TableLike` methods should behave like those of a `Table`, too, and the only way to make this consistent is to assume that a query acting like a `TableLike` is, in fact, an unnamed derived table.

Just replace your `var query =` with `TableLike<?> query =`. You'd probably expect the derived table behaviour much more than the one you did expect now? If you're using a query like a derived table, think about joining derived tables. You will now want to dereference columns from the *derived table* using `query.field("column_name")`, for example, to form a `JOIN .. ON` predicate. You want that column to be qualified with the derived table's correlation name, not with whatever is going on *inside* of the derived table. So, from the *outside* of the query, client code would expect what is currently implemented most of the time.

> and is there any other way for me to retrieve those fields at runtime?

Sure, there's a historic `Select.getSelect()` method that allows for accessing the projection. This method should have been internal,  but a very long time ago, it was made public API, and it's unlikely that will change, so you can use it. The caveat here is that it will resolve asterisks and similar expressions, so it's not *exactly* the projection.

There is also experimental API (subject to change) via the new query object model, where you can access the projection using `Select::$select`, see:
https://www.jooq.org/doc/latest/manual/sql-building/model-api/
