### ISSUE TITLE
Are nested multisets supported ?

### ISSUE THREAD

**Issue by rrnair-98** [jOOQ/jOOQ#15228]
### Your question

First things first thanks for making this framework. 
I've been playing around with jooq for the last few days and have a deeply nested relationship that I'd like to fetch it goes something like this

Job (1)->(*) SpawnedJob

SpawnedJob(1) -> (1) Question
SpawnedJob(1) -> (1)Paragraph

Paragraph(1)->(*) Question

Question(1)->(*) Option

I've written a jooq query to fetch a job with is spawned jobs and questions bound to this spawned job using nested multiset and it goes like this
```
this.dslContext.select(Tables.JOBS.ID, Tables.JOBS.UID,
                        multiset(
                                select(Tables.SPAWNED_JOBS.ID, Tables.SPAWNED_JOBS.JOB_ID, Tables.SPAWNED_JOBS.STATE, Tables.SPAWNED_JOBS.TABLE_INDEX, Tables.SPAWNED_JOBS.CREATED_AT,
                                        Tables.SPAWNED_JOBS.TYPE,
                                        multiset(
                                                select(
                                                        Tables.QUESTIONS.ID, Tables.QUESTIONS.ANSWER, Tables.QUESTIONS.DIFFICULTY, Tables.QUESTIONS.EXPLANATION, Tables.QUESTIONS.EXPLANATION_HTML,
                                                        Tables.QUESTIONS.MAX_MARKS, Tables.QUESTIONS.MIN_MARKS, Tables.QUESTIONS.TAGS, Tables.QUESTIONS.TYPE, Tables.QUESTIONS.HTML_CONTENT
                                                    ).from(Tables.QUESTIONS).
                                                    where(Tables.QUESTIONS.SPAWNED_JOB_ID.eq(Tables.SPAWNED_JOBS.ID))
                                        ).as("questions").convertFrom(r -> r.map(mapping(QuestionDto::new)))).
                                    from(Tables.SPAWNED_JOBS).
                                    where(Tables.SPAWNED_JOBS.JOB_ID.eq(id)
                                )
                        ).as("all_spawned_jobs").convertFrom(r -> r.map(mapping(SpawnedJob::new)))
                ).
                from(Tables.JOBS).
                where(Tables.JOBS.ID.eq(id)).
                fetch(mapping(Job::new)).get(0);
```
 and it lead to a  jooq DataAccessException
```
org.jooq.exception.DataAccessException: SQL [select "public"."jobs"."id", "public"."jobs"."uid", (select coalesce(json_agg(json_build_array("v0", "v1", "v2", "v3", "v4", "v5", "v6")), json_build_array()) from (select "public"."spawned_jobs"."id" as "v0", "public"."spawned_jobs"."job_id" as "v1", "public"."spawned_jobs"."state" as "v2", "public"."spawned_jobs"."table_index" as "v3", "public"."spawned_jobs"."created_at" as "v4", "public"."spawned_jobs"."type" as "v5", (select coalesce(json_agg(json_build_array("v0", "v1")), json_build_array()) from (select "public"."questions"."id" as "v0", "public"."questions"."answer" as "v1" from "public"."questions" where "public"."questions"."spawned_job_id" = "public"."spawned_jobs"."id") as "t") as "v6" from "public"."spawned_jobs" where "public"."spawned_jobs"."job_id" = ?) as "t") as "all_spawned_jobs" from "public"."jobs" where "public"."jobs"."id" = ?]; Error while reading field: "all_spawned_jobs", at JDBC index: 3

```
I tested the generated query and it seemed to work fine on psql ... I would appreciate some help in understanding what Im doing wrong. Are nested multisets not supported ? I planned on fetching options, paragraphs and questions bound to paragraphs using mulisets as well.

### jOOQ Version

3.17.5

### Database product and version

postgresql 14.7

### Java Version

open jdk 17

### OS Version

win 11, ubuntu 22.04

### JDBC driver name and version (include name if unofficial driver)

postgresql:42.3.8

**Comment by lukaseder** [comment]
Thanks for your report. Yes, they're supported. You can nest any level of nested records or collections. But there have been bugs, and there might still be bugs.

If you think you ran into a bug, please:

- Upgrade to the latest jOOQ version first and try again
- If it persists, can you please add the additional requested information for a new bug (see https://github.com/jOOQ/jOOQ/issues/new/choose) to help reproduce the problem?

**Comment by lukaseder** [comment]
Closing this for now. I'll be happy to revisit once there's a reproducer for any potential bugs.
