### ISSUE TITLE
Wrong properties for timestamp columns in generated DDL

### ISSUE THREAD

**Issue by mgramin** [jOOQ/jOOQ#15229]
### Expected behavior

I am using the schema exporting feature of jOOQ extensively, and I expected that DDL from jOOQ `ddl()` method:
```sql
create table test_date_types_table (
  timestamp_column_nullable timestamp null,
  timestamp_column_not_null timestamp not null,
  timestamp_column_default timestamp
);
```

### Actual behavior

But I received this DDL from jOOQ:
```sql
create table `sakila`.`test_date_types_table` (
  `timestamp_column_nullable` timestamp,
  `timestamp_column_not_null` timestamp not null default null,
  `timestamp_column_default` timestamp not null default null
)
```

That DDL doesn't work, because we have not null columns with null value by default:
```
Invalid default value for 'timestamp_column_not_null'
```

And our nullable column `timestamp_column_default` is no longer nullable.

### Steps to reproduce the problem

1. Create a table (disabling `NO_ZERO_DATE` mode):
```sql
set sql_mode='';
create table test_date_types_table (
  timestamp_column_nullable timestamp null,
  timestamp_column_not_null timestamp not null,
  timestamp_column_default timestamp
);
```

2. Run this Java code to generate DDL for the table:
```java
        Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:6000/sakila", "root", "admin");
        Configuration configuration = new DefaultConfiguration().set(conn).set(SQLDialect.MYSQL.family());
        Meta currentMeta = using(configuration).meta();

        Query[] queries = currentMeta
                .filterSchemas(v -> v.getName().equalsIgnoreCase("sakila"))
                .ddl()
                .queries();

        for (Query query : queries) {
            System.out.println(query);
        }
```

### jOOQ Version

jOOQ Professional Edition 3.18.4

### Database product and version

MySQL 5.7.42

### Java Version

openjdk 17.0.2 2022-01-18

### OS Version

Microsoft Windows [Version 10.0.19044.2846]

### JDBC driver name and version (include name if unofficial driver)

mysql-connector-java:8.0.33

**Comment by lukaseder** [comment]
Thanks for your report and sorry for the delay. This issue seems to have slipped by our notification reports. Will look into it right away.

**Comment by lukaseder** [comment]
OK, I see. I'm getting this as well with MySQL 5.7:

```sql
create table `test`.`test_date_types_table` (
  `timestamp_column_nullable` timestamp,
  `timestamp_column_not_null` timestamp not null default null,
  `timestamp_column_default` timestamp not null default null
);
```

This isn't a jOOQ problem, though. Try running this query:

```sql
select table_name, column_name, is_nullable, column_default
from information_schema.columns
where table_name = 'test_date_types_table';
```

It produces the unwanted constraint:

```
|TABLE_NAME           |COLUMN_NAME              |IS_NULLABLE|COLUMN_DEFAULT     |
|---------------------|-------------------------|-----------|-------------------|
|test_date_types_table|timestamp_column_nullable|YES        |                   |
|test_date_types_table|timestamp_column_not_null|NO         |0000-00-00 00:00:00|
|test_date_types_table|timestamp_column_default |NO         |0000-00-00 00:00:00|
```

Which MySQL adds on its own. This was all due to an absolutely insane feature in older MySQL versions. I once stumbled upon this "feature" as well in MariaDB, which they have now removed as well, following suit after MySQL 8:

- https://jira.mariadb.org/browse/MDEV-28470

See also:

- https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html
- https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp

Try this:

```sql
SET GLOBAL explicit_defaults_for_timestamp = 1;

create table test_date_types_table (
  timestamp_column_nullable timestamp null,
  timestamp_column_not_null timestamp not null,
  timestamp_column_default timestamp
);

select table_name, column_name, is_nullable, column_default
from information_schema.columns
where table_name = 'test_date_types_table';
```

Now you'll get the expected behaviour also on MySQL 5.7:

```
|TABLE_NAME           |COLUMN_NAME              |IS_NULLABLE|COLUMN_DEFAULT|
|---------------------|-------------------------|-----------|--------------|
|test_date_types_table|timestamp_column_nullable|YES        |              |
|test_date_types_table|timestamp_column_not_null|NO         |              |
|test_date_types_table|timestamp_column_default |YES        |              |
```

And jOOQ produces:

```sql
create table `test`.`test_date_types_table` (
  `timestamp_column_nullable` timestamp,
  `timestamp_column_not_null` timestamp not null,
  `timestamp_column_default` timestamp
);
```

There's really not much jOOQ can do here. The original DDL is transformed when you create the table, as if you actually added the `NOT NULL` constraint there.
