### ISSUE TITLE
Add support for MySQL DECIMAL/FLOAT/DOUBLE/REAL UNSIGNED types in Meta and code generation

### ISSUE THREAD

**Issue by mgramin** [jOOQ/jOOQ#15230]
### Expected behavior

I expected that DDL from jOOQ `ddl()` method:
```sql
create table test_point_types_table (
  decimal_column_20_unsigned decimal(20) unsigned not null
);
```

### Actual behavior

But I received the DDL with broken data type (`other`) instead `decimal(20) unsigned`:
```sql
create table `sakila`.`test_point_types_table` (
  `decimal_column_20_unsigned` other not null
)
```

### Steps to reproduce the problem

1. Create a table:
```sql
create table test_point_types_table (
  decimal_column_20_unsigned decimal(20) unsigned not null
);
```

2. Run this Java code to generate DDL for the table:
```java
        Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:6000/sakila", "root", "admin");
        Configuration configuration = new DefaultConfiguration().set(conn).set(SQLDialect.MYSQL.family());
        Meta currentMeta = using(configuration).meta();


        Query[] queries = currentMeta
                .filterSchemas(v -> v.getName().equalsIgnoreCase("sakila"))
                .ddl()
                .queries();

        for (Query query : queries) {
            System.out.println(query);
        }
```

### jOOQ Version

jOOQ Professional Edition 3.18.4

### Database product and version

MySQL 5.7.42

### Java Version

openjdk 17.0.2 2022-01-18

### OS Version

Microsoft Windows [Version 10.0.19044.2846]

### JDBC driver name and version (include name if unofficial driver)

mysql-connector-java:8.0.33

**Comment by lukaseder** [comment]
Thanks a lot for your report.

Interesting, I wasn't aware of these types. They're not documented here:

- https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html

Unlike unsigned integers:

- https://dev.mysql.com/doc/refman/8.0/en/integer-types.html

When creating your example table, I'm getting this warning:

> UNSIGNED for decimal and floating point data types is deprecated and support for it will be removed in a future release.

My intuition is that `DECIMAL UNSIGNED` isn't really a useful data type, given that `CHECK` constraints have finally been implemented in MySQL 8.0.16.

See also:

- https://stackoverflow.com/q/71531634/521799

In any case, we can add support for these types when reverse engineering old schemas that still use this deprecated type.

**Comment by lukaseder** [comment]
> In any case, we can add support for these types when reverse engineering old schemas that still use this deprecated type.

Meaning, we'll effectively just ignore the `UNSIGNED` part.

**Comment by lukaseder** [comment]
> Interesting, I wasn't aware of these types. They're not documented here:

My bad. I didn't scroll down enough.

**Comment by lukaseder** [comment]
> However, the resulting DDL does not include the "unsigned" clause for columns.

Yes, I don't think we'll be supporting that. It would be a ton of effort for a feature that has been deprecated in MySQL and that I haven't seen in any other RDBMS.

**Comment by mgramin** [comment]
Got it, thank you again.
