### ISSUE TITLE
Any solution for slow start with spring ?

### ISSUE THREAD

**Issue by wwc7654321** [jOOQ/jOOQ#15235]
### Your question

My spring application takes too many longer time to startup  when  use Jooq .

It takes about 90s to init DSLConent  , and most time spent in Spring AdvisorAutoProxyCreator.

I found some issues about this , but not sure is there any solution to speed up ?

spring-boot version: 2.1.4

### jOOQ Version

3.11.10

### Database product and version

mysql 5.7

### Java Version

1.8

**Comment by lukaseder** [comment]
Thanks for your message. Here's what I would do:

1. Upgrade everything (Spring, jOOQ, MySQL, Java). There are probably many improvements on all ends if you do this. For example, the Java compiler has seen drastic improvements between 8 and 11. Spring Boot probably has, too.
2. Check with Spring Boot folks (after you've upgraded). This is mostly a Spring problem, not a jOOQ problem.

I hope this helps

**Comment by kindabit** [comment]
You may want to look into the Auto-configuration feature of spring boot: https://docs.spring.io/spring-boot/reference/using/auto-configuration.html

I don't use code generation, so I just disabled it.
