### ISSUE TITLE
Is there a way to force a field to be not nullable in a kotlin pojo?

### ISSUE THREAD

**Issue by leonkacowicz** [jOOQ/jOOQ#15246]
### Your question

I have a table with a not-null field, but that has a default value. Because of the default value, the kotlin pojo is generated with a nullable type for this field. I understand the reason for that is that I can put a null value in the pojo and use that to insert into the table with the generated DAO, taking advantage of the default value. But for querying, the database guarantees that the field is not null, so it's annoying to have to deal with the nullable field from the pojo. I tried using a "ForcedType" in the codegen step, but I didn't manage to force the generated field to be not nullable. Is there a way to force this?

### jOOQ Version

jOOQ community version 3.18.4 (org.jooq:jooq-codegen:3.18.4)

### Database product and version

PostgreSQL 15.3 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

### Java Version

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment (build 17.0.7+7) OpenJDK 64-Bit Server VM (build 17.0.7+7, mixed mode)

### OS Version

linux kernel 6.3.6

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by nucle** [comment]
Did you try this:
````
 <implicitJoinPathsAsKotlinProperties>true</implicitJoinPathsAsKotlinProperties>
      
      <!--  Workaround for Kotlin generating setX() setters instead of setIsX() in byte code for mutable properties called 
            <code>isX</code>. Default is true. -->
      <kotlinSetterJvmNameAnnotationsOnIsPrefix>true</kotlinSetterJvmNameAnnotationsOnIsPrefix>
      
      <!-- Generate POJOs as data classes, when using the KotlinGenerator. Default is true. -->
      <pojosAsKotlinDataClasses>true</pojosAsKotlinDataClasses>
      
      <!-- Generate non-nullable types on POJO attributes, where column is not null. Default is false. -->
      <kotlinNotNullPojoAttributes>false</kotlinNotNullPojoAttributes>
      
      <!-- Generate non-nullable types on Record attributes, where column is not null. Default is false. -->
      <kotlinNotNullRecordAttributes>false</kotlinNotNullRecordAttributes>
      
      <!-- Generate non-nullable types on interface attributes, where column is not null. Default is false. -->
      <kotlinNotNullInterfaceAttributes>false</kotlinNotNullInterfaceAttributes>

````

https://www.jooq.org/doc/latest/manual/code-generation/kotlingenerator/

**Comment by leonkacowicz** [comment]
my generator config is like this:
```
Generate()
    .withPojos(true)
    .withDaos(true)
    .withPojosAsKotlinDataClasses(true)
    .withKotlinNotNullPojoAttributes(true)
    .withKotlinNotNullRecordAttributes(true)
    .withKotlinNotNullInterfaceAttributes(true)
    .withComments(true)
```

The generator is creating non-nullable types of not-null columns. The problem is that for not-null columns that have a default value, it creates the POJO with a nullable type for the fields with default values. I would like to force the fields to have a non-nullable types. I tried looking into the ForcedTypes, and tried a few configurations, but none worked like I described.

**Comment by lukaseder** [comment]
> The problem is that for not-null columns that have a default value, it creates the POJO with a nullable type for the fields with default values

There you have your answer. Prior to storing a defaulted value, it is allowed to be `NULL`, so the field is effectively nullable even if only for a certain amount of time in the lifecycle of the record. Even more so when you have a POJO that you want to store. The POJO must be able to contain `null` values that will then be inserted (or rather, omitted from the insert, because the intention can only be to apply the `DEFAULT`).

I'll add a remark to the XML comments of those flags to be sure this is understood. It is surprising at first, indeed.

> I would like to force the fields to have a non-nullable types. I tried looking into the ForcedTypes, and tried a few configurations, but none worked like I described.

There won't be any additional flags for this. What appears annoying at first makes perfect sense if you think about it.

**Comment by lukaseder** [comment]
The task to add more documentation is here: https://github.com/jOOQ/jOOQ/issues/15248

**Comment by leonkacowicz** [comment]
Sorry, the first thing I said was "I understand the reason for that is that I can put a null value in the pojo and use that to insert into the table with the generated DAO, taking advantage of the default value. But for querying, the database guarantees that the field is not null"

This application is not the only component that accesses this DB and for this application it *does not* make sense for this field to be nullable at any point of the lifecycle (since it should never rely on the default value), I can do other workarounds to re-write the jooq-generated code (i.e. `sed`) to correct this, but I believe the code-generator should offer the possibility of forcing this, the same way it offers the possibility of forcing any types.

I'd like to ask that this is reconsidered.

Thanks

**Comment by lukaseder** [comment]
> Sorry, the first thing I said was "I understand the reason for that is that [...]"

My bad, I didn't catch that

> but I believe the code-generator should offer the possibility of forcing this, the same way it offers the possibility of forcing any types.

OK, maybe synthetic `DEFAULT` expressions similar to other synthetic clauses in the code generator can be a thing in the future, but this won't be about generated nullability, specifically. It will just be a side effect of that. I've created this issue:

- https://github.com/jOOQ/jOOQ/issues/15251

In the meantime, you can probably implement a jOOQ-meta `Database` implementation that strips all `ColumnDefinition` of their defaults...
