### ISSUE TITLE
Update jakarta.xml.bind:jakarta.xml.bind-api from 3.0.0 to 4.0.0

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#15275]
### Use case

Please update jakarta.xml.bind:jakarta.xml.bind-api as a new major version is out and the old one's transitive dependencies (activation) are causing problems:

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Two versions of module jakarta.activation found in target\lib (jakarta.activation-api-2.1.2.jar and jakarta.activation-2.0.0.jar)
```

This prevents applications from running. My workaround was to add the following dependency:

```
<dependency>
	<!-- This dependency ships with JOOQ. Jakarta Mail ships with a newer version -->
	<groupId>jakarta.xml.bind</groupId>
	<artifactId>jakarta.xml.bind-api</artifactId>
	<version>3.0.0</version>
	<exclusions>
		<exclusion>
			<groupId>com.sun.activation</groupId>
			<artifactId>jakarta.activation</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

though I don't know how safe it is to do this long-term.

### jOOQ Version

3.18.3

### Database product and version

N/A

**Comment by lukaseder** [comment]
Thanks for your suggestion.

I thought there already was such an issue to upgrade this dependency, but apparently there isn't. We have a build that runs 4 times a year to help look into dependency updates, so this usually isn't forgotten.

Note that if you run into this particular problem now, you might run into it again in the future, when the versions aren't in sync.

What is curious here is that you're running into this despite jOOQ's dependency on the JAXB API being marked optional since jOOQ 3.18: https://github.com/jOOQ/jOOQ/issues/13047. So, I think it would definitely be worth investigating further, why you're having this issue.

**Comment by lukaseder** [comment]
Ah yes, one reason why we couldn't upgrade to 4.0.0 yet is because that version requires Java 11, and jOOQ's commercial distributions still support Java 8.

**Comment by lukaseder** [comment]
It's probably possible to downgrade the dependency for the Java 8 build only. I'll investigate this for jOOQ 3.19

**Comment by lukaseder** [comment]
Note that we only depend on the JAXB API, not on the `jakarta.activation-api` directly. If we upgrade the JAXB API dependency to 4.0.0, the transitive `jakarta.activation-api` dependency will still only be at version 2.1.0, not 2.1.2, so this upgrade might not solve your problem.

**Comment by lukaseder** [comment]
No obvious issues detected in the build. Let's see what the complete CI/CD pipeline thinks about this upgrade. I'll comment if there's any caveat.

Otherwise: upgrade implemented for 3.19.0

**Comment by lukaseder** [comment]
This issue looks similar: https://github.com/jOOQ/jOOQ/issues/15069#issuecomment-1547257694

Though I couldn't reproduce it yet. But my main idea there was:

> > cannot access class jakarta.xml.bind.annotation.XmlSchema (in unnamed module @0x10e31a9a)
> 
> Somehow, you're building your application using the modulepath instead of classpath, but introduce the optional dependency in the unnamed module, instead of formally as its own module.

Not sure if that's also the issue in your case.

**Comment by cowwoc** [comment]
I don't depend directly on jakarta.xml. The only reason I chose to add it as a dependency is to force a change to the version number.

I suspect my case is different.
