### ISSUE TITLE
Various Meta DDL related issues

### ISSUE THREAD

**Issue by mgramin** [jOOQ/jOOQ#15293]
### Use case

Code generation is one of the main features of jOOQ. Moreover, jOOQ not only provides Java code generation, but also DDL generation. Additionally, jOOQ enables the transformation of DDL between different databases. In this feature request, we suggest collecting all known issues and ideas to improve jOOQ's DDL code generation.

- https://github.com/jOOQ/jOOQ/issues/15236
- https://github.com/jOOQ/jOOQ/issues/15230
- https://github.com/jOOQ/jOOQ/issues/15039
- https://github.com/jOOQ/jOOQ/issues/15292
- https://github.com/jOOQ/jOOQ/issues/15291
- https://github.com/jOOQ/jOOQ/issues/15229
- https://github.com/jOOQ/jOOQ/issues/15298
- https://github.com/jOOQ/jOOQ/issues/15300
- https://github.com/jOOQ/jOOQ/issues/15302
- https://github.com/jOOQ/jOOQ/issues/15303
- https://github.com/jOOQ/jOOQ/issues/15310
- https://github.com/jOOQ/jOOQ/issues/15318
- https://github.com/jOOQ/jOOQ/issues/15322
- https://github.com/jOOQ/jOOQ/issues/15323
- https://github.com/jOOQ/jOOQ/issues/15324
- https://github.com/jOOQ/jOOQ/issues/15325
- https://github.com/jOOQ/jOOQ/issues/15326
- https://github.com/jOOQ/jOOQ/issues/15384
- https://github.com/jOOQ/jOOQ/issues/15520
- https://github.com/jOOQ/jOOQ/issues/15530
- https://github.com/jOOQ/jOOQ/issues/15531

### jOOQ Version

jOOQ Professional Edition 3.18.4

### Database product and version

All databases

**Comment by lukaseder** [comment]
Thanks a lot for this overview. I'll comment on tasks individually. You can track progress also from here on github, given github's automatic color scheme for open/closed issue references in lists:

![image](https://github.com/jOOQ/jOOQ/assets/734593/ab7e2cb9-b0ff-443c-b42a-a210f23e40d0)

**Comment by lukaseder** [comment]
I'm closing this issue as it's just referencing other issues that have been / will be implemented independently.
