### ISSUE TITLE
Meta.ddl() export generates wrong DDL for constraints with USING INDEX clause in Oracle

### ISSUE THREAD

**Issue by mgramin** [jOOQ/jOOQ#15291]
### Expected behavior

Oracle allows constructions like this (and we have come across it in real SQL scripts):

```sql
CREATE TABLE COUNTRIES (
    COUNTRY_ID CHAR (2 BYTE) NOT NULL,
    COUNTRY_NAME VARCHAR2 (40 BYTE),
    REGION_ID NUMBER);

CREATE UNIQUE INDEX COUNTRY_C_ID_PKX ON COUNTRIES (COUNTRY_ID ASC);

ALTER TABLE COUNTRIES
    ADD CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY (COUNTRY_ID);
```

As a result, we have a simple table with a primary key and a unique key for the same field. Although in modern versions, we could create only a primary key and Oracle will automagically create a unique index, we are working with what we have.

We expect that Oracle META will export the DDL of this type of table correctly, preserving constraints and indexes and without any errors during execution of the resulting script.

### Actual behavior

However, jOOQ exports the DDL for this table, as follows:
```sql
create table "TEST"."COUNTRIES" (
  "COUNTRY_ID" char(2) not null,
  "COUNTRY_NAME" varchar2(40),
  "REGION_ID" number,
  constraint "COUNTRY_C_ID_PK"
    primary key ("COUNTRY_ID")
);
create unique index "TEST"."COUNTRY_C_ID_PKX" on "TEST"."COUNTRIES"("COUNTRY_ID" asc);
```

This leads to an error during execution: "ORA-01408: such column list already indexed".
The first statement has already created a unique index with a primary key automatically. Therefore, the second query fails.

### Steps to reproduce the problem

Create a table in DB:
```sql
CREATE TABLE COUNTRIES (
    COUNTRY_ID CHAR (2 BYTE) NOT NULL,
    COUNTRY_NAME VARCHAR2 (40 BYTE),
    REGION_ID NUMBER);

CREATE UNIQUE INDEX COUNTRY_C_ID_PKX ON COUNTRIES (COUNTRY_ID ASC);

ALTER TABLE COUNTRIES
    ADD CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY (COUNTRY_ID);
```

Run this code:
```java
        Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "test", "test");
        Configuration configuration = new DefaultConfiguration().set(conn).set(SQLDialect.ORACLE);
        Meta meta = using(configuration).meta();

        Arrays.stream(meta.filterSchemas(v -> v.getName().equalsIgnoreCase("test"))
                        .ddl()
                        .queries())
                .map(Object::toString)
                .forEach(System.out::println);
```

Execute the resulting query against a different database or schema:
```sql
create table "TEST"."COUNTRIES" (
  "COUNTRY_ID" char(2) not null,
  "COUNTRY_NAME" varchar2(40),
  "REGION_ID" number,
  constraint "COUNTRY_C_ID_PK"
    primary key ("COUNTRY_ID")
)
create unique index "TEST"."COUNTRY_C_ID_PKX" on "TEST"."COUNTRIES"("COUNTRY_ID" asc)
```

### jOOQ Version

jOOQ Professional Edition 3.18.4

### Database product and version

Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production

### Java Version

openjdk 17.0.2 2022-01-18

### OS Version

Microsoft Windows [Version 10.0.19044.2846]

### JDBC driver name and version (include name if unofficial driver)

com.oracle.database.jdbc:ojdbc11:23.2.0.0

**Comment by lukaseder** [comment]
Thanks a lot for your report. That's a fun edge case. There are probably other RDBMS with a similar situation.

Reminds me of this syntax that we have to yet support:

- https://github.com/jOOQ/jOOQ/issues/8631

Various RDBMS allow for using an existing index as a backing implementation of a constraint. And effectively, this seems to be what Oracle does behind the scenes, automatically for you:

```sql
select constraint_name, index_name
from all_constraints
where constraint_type = 'P'
where table_name = 'COUNTRIES';
```

Resulting in:

```
|CONSTRAINT_NAME|INDEX_NAME      |
|---------------|----------------|
|COUNTRY_C_ID_PK|COUNTRY_C_ID_PKX|
```

So, while it's reasonable to fix this in the short term by reordering DDL statements based on such matching columns, I'll keep in mind that a thorough fix would be to use the formal information and go ahead with the feature support of

- https://github.com/jOOQ/jOOQ/issues/8631

The latter is a lot more work, of course, so I can't promise when that will ship.

**Comment by lukaseder** [comment]
As a workaround, you can export DDL twice to reorder statements, via the `DDLExportConfiguration::flags` setting

**Comment by lukaseder** [comment]
One might be tempted to re-order the DDL irrespective of whether this case is present, but not all RDBMS support `ALTER TABLE .. ADD CONSTRAINT`. Some dialects support constraints only in `CREATE TABLE` (I know, I know)...

So, I think it would be best to (for now) only reorder statements in this particular case.

**Comment by lukaseder** [comment]
The same thing happens with `UNIQUE` constraints too, of course:

```sql
create table t (
  i number
);

create unique index ix on t (i asc);
alter table t add constraint ip unique (i);
select constraint_name, index_name
from all_constraints
where constraint_type in ('P', 'U')
and table_name = 'T';
```

Producing:

```
|CONSTRAINT_NAME|INDEX_NAME|
|---------------|----------|
|IP             |IX        |
```

**Comment by lukaseder** [comment]
Also, the order of columns is relevant in composite keys/indexes. I.e. this works:

```sql
create table t (
  i number,
  j number
);

alter table t add constraint ip unique (j, i);
create unique index ix on t (i, j);

select constraint_name, index_name
from all_constraints
where constraint_type in ('P', 'U')
and table_name = 'T';
```

Now, the constraint isn't using the index:

```
|CONSTRAINT_NAME|INDEX_NAME|
|---------------|----------|
|IP             |IP        |
```

While the two indexes are semantically the same for uniqueness checking, their performance characteristics are different, so Oracle allows creating them redundantly.

**Comment by lukaseder** [comment]
Also, with `DESC` ordering, the problem goes away:

```java
create table t (
  i number
);

alter table t add constraint ip unique (i);
create unique index ix on t (i desc);
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.6 (https://github.com/jOOQ/jOOQ/issues/15294)
- 3.17.15 (https://github.com/jOOQ/jOOQ/issues/15295)
- 3.16.21 (https://github.com/jOOQ/jOOQ/issues/15296)

Thanks again for your report!
