### ISSUE TITLE
MetaImpl is missing view source code or unique constraints for objects in other catalogs

### ISSUE THREAD

**Issue by mgramin** [jOOQ/jOOQ#15318]
### Expected behavior

We expect that Meta.ddl() exports a valid DDL for a view:
```sql
create view test.test_table_view as select * from test.test_table;
```

### Actual behavior

Meta.ddl() exports broken DDL for views:
```sql
create view [test].[test_table_view]([id])
as
```

### Steps to reproduce the problem

Create a view in DB:
```sql
CREATE SCHEMA test;

create table test.test_table (
	id integer
);

create view test.test_table_view as select * from test.test_table;
```

Run this code:
```java
        Connection conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;encrypt=false;databaseName=sakila;ACCEPT_EULA=Y", "SA", "YourStrong@Passw0rd");
        Configuration configuration = new DefaultConfiguration().set(conn).set(SQLDialect.SQLSERVER);
        Meta meta = using(configuration).meta();

        Arrays.stream(meta.filterSchemas(v -> v.getName().equalsIgnoreCase("test"))
                        .ddl()
                        .queries())
                .map(Object::toString)
                .forEach(System.out::println);
```

Executing the resulting query against a different database or schema:
```sql
create view [test].[test_table_view]([id])
as
```

leads to the error:
```sql
SQL Error [102] [S0001]: Incorrect syntax near 'as'.
```

### jOOQ Version

jOOQ Professional Edition 3.18.4

### Database product and version

Microsoft SQL Server 2022 (RTM-CU4) (KB5026717) - 16.0.4035.4 (X64)  	May  1 2023 10:34:45  	Copyright (C) 2022 Microsoft Corporation 	Developer Edition (64-bit) on Linux (Ubuntu 20.04.6 LTS) <X64>

### Java Version

openjdk 17.0.2 2022-01-18

### OS Version

Microsoft Windows [Version 10.0.19044.2846]

### JDBC driver name and version (include name if unofficial driver)

com.microsoft.sqlserver:mssql-jdbc:12.3.1.jre11-preview

**Comment by lukaseder** [comment]
Thanks a lot for your report. I tried your example in the latest 3.19.0-SNAPSHOT and 3.18.6-SNAPSHOT versions, and got the expected result:

```sql
create view [test].[test_table_view]([id])
as
select *
from test.test_table
```

Anything else I should be looking out for? How can I reproduce this?

**Comment by lukaseder** [comment]
Just to be sure, this isn't a duplicate of https://github.com/jOOQ/jOOQ/issues/15236 ? Can you check a 3.18.6-SNAPSHOT build from here?
https://www.jooq.org/download/versions

**Comment by lukaseder** [comment]
I also can't reproduce this with 3.18.4

**Comment by mgramin** [comment]
Thank you for your investigation.
Sorry, my mistake. I created the view in one database but connected to another database.

The query `SELECT object_definition(OBJECT_ID(N'test.test_table_view'))` will return the valid DDL if you are connected to the test database, and `null` if you are connected to any other database.

Should jOOQ ignore those views?

**Comment by lukaseder** [comment]
I see now, I can reproduce this:

```sql
create database x;
use x;
create view v (a) as select 1;
```

And then go back to the original database and run a `meta()` query to get this:

```sql
create view [dbo].[v]([a])
as
;
```

Definitely not what should happen. I'll look into this tomorrow.

**Comment by lukaseder** [comment]
I've had a look at this. It seems we're not setting the catalog name with a `use` command prior to querying the `information_schema` or `sys` views. The code generator does this right, but `MetaImpl` doesn't. Other queries might be affected as well, e.g. those for sequences.

**Comment by lukaseder** [comment]
Yeah, as I expected, this also happens with queries for unique keys:

```java
    private void assertSQLServerMetaCrossCatalogUniqueKeys() {
        List<? extends UniqueKey<?>> uk1 =
        create().meta()
                .filterSchemas(s -> s.getName().equals(schema().getName()))
                .filterTables(t -> t.getName().equalsIgnoreCase("t_author"))
                .getTables()
                .get(0)
                .getUniqueKeys();

        assertEquals(1, uk1.size());
        assertEquals(1, uk1.get(0).getFields().size());
        assertEquals("last_name", uk1.get(0).getFields().get(0).getName().toLowerCase());
    }
```

I'll fix that as well in the same go

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.6 (https://github.com/jOOQ/jOOQ/issues/15396)
- 3.17.15 (https://github.com/jOOQ/jOOQ/issues/15397)
- 3.16.21 (https://github.com/jOOQ/jOOQ/issues/15398)

Thanks again for your report!

**Comment by lukaseder** [comment]
View source code hasn't been fetched prior to 3.18 at all: https://github.com/jOOQ/jOOQ/issues/9818. But the backports will still fix the unique key case.

**Comment by lukaseder** [comment]
We're still missing sequences from other catalogs:

- https://github.com/jOOQ/jOOQ/issues/18858
