### ISSUE TITLE
Add native support for Db2 XML type in DDL, code generator, etc.

### ISSUE THREAD

**Issue by mgramin** [jOOQ/jOOQ#15323]
### Expected behavior

We expect that Meta.ddl() exports a valid DDL for tables with XML columns:
```sql
CREATE TABLE "DB2INST1"."CUSTOMER"  (
		  "CID" BIGINT NOT NULL , 
		  "INFO" XML , 
		  "HISTORY" XML);
```

### Actual behavior

Meta.ddl() turns XML columns into CLOB columns:
```sql
create table "DB2INST1"."CUSTOMER" (
  "CID" bigint not null,
  "INFO" clob,
  "HISTORY" clob,
  constraint "PK_CUSTOMER"
    primary key ("CID")
)
```

### Steps to reproduce the problem

Create a table with XML columns in DB:
```sql
CREATE TABLE "DB2INST1"."CUSTOMER"  (
		  "CID" BIGINT NOT NULL , 
		  "INFO" XML , 
		  "HISTORY" XML);
```

Run this code:
```java
        Connection conn = DriverManager.getConnection("jdbc:db2://localhost:50000/sample", "db2inst1", "secret_password");
        Configuration configuration = new DefaultConfiguration().set(conn).set(SQLDialect.DB2);
        Meta meta = using(configuration).meta();

        Arrays.stream(meta.filterSchemas(v -> v.getName().equalsIgnoreCase("DB2INST1"))
                        .ddl()
                        .queries())
                .map(Object::toString)
                .forEach(System.out::println);
```

Executing the resulting query against a different database or schema:
```sql
create table "DB2INST1"."CUSTOMER" (
  "CID" bigint not null,
  "INFO" clob,
  "HISTORY" clob,
  constraint "PK_CUSTOMER"
    primary key ("CID")
)
```

### jOOQ Version

jOOQ Professional Edition 3.18.4

### Database product and version

DB2 v11.5.8.0

### Java Version

openjdk 17.0.2 2022-01-18

### OS Version

Microsoft Windows [Version 10.0.19044.2846]

### JDBC driver name and version (include name if unofficial driver)

com.ibm.db2.jcc:db2jcc:db2jcc4

**Comment by lukaseder** [comment]
Thanks a lot for your report.

It appears that Db2's `XML` type has been added to the `DB2DataType` class long before we actually supported XML in jOOQ:

```java
public static final DataType<String> XML = new BuiltInDataType<>(FAMILY, SQLDataType.CLOB, "xml");
```

Let me check what it means to retrofit supporting the `SQLDataType.XML` for Db2. This won't just affect generated DDL, but also other functionality.

**Comment by lukaseder** [comment]
It looks like this is a simple fix in isolation. Though, as it may have significant impact on users relying on the existing behaviour, I won't backport it. jOOQ 3.19 will add formal support for the Db2 `XML` type in jOOQ's type system, including for DDL, casts, etc.

I've created a separate issue to track down more potential shortcomings of a lack of `XML` type support in Db2 and other dialects:

- https://github.com/jOOQ/jOOQ/issues/15332

Thanks again for your report!
