### ISSUE TITLE
Meta.ddl() should export tables first, then views

### ISSUE THREAD

**Issue by mgramin** [jOOQ/jOOQ#15326]
### Expected behavior

We expect that Meta.ddl() will provide a valid ordering for exporting tables and views:
```sql
create table TEST_TABLE (ID varchar(50));

CREATE VIEW c AS SELECT * FROM TEST_TABLE;

CREATE VIEW b AS SELECT * FROM c;

CREATE VIEW a AS SELECT * FROM b;
```

### Actual behavior

Meta.ddl() exports tables and views in wrong order:
```sql
create view "DB2INST1"."A"("ID")
as
select *
from B
create view "DB2INST1"."B"("ID")
as
select *
from C
create view "DB2INST1"."C"("ID")
as
select *
from TEST_TABLE
create table "DB2INST1"."TEST_TABLE" (
  "ID" varchar(50)
)
```

### Steps to reproduce the problem

Create a table and a few views:
```sql
create table TEST_TABLE (ID varchar(50));

CREATE VIEW c AS SELECT * FROM TEST_TABLE;

CREATE VIEW b AS SELECT * FROM c;

CREATE VIEW a AS SELECT * FROM b;
```

Run this code:
```java
        Connection conn = DriverManager.getConnection("jdbc:db2://localhost:50000/sample", "db2inst1", "secret_password");
        Configuration configuration = new DefaultConfiguration().set(conn).set(SQLDialect.DB2);
        Meta meta = using(configuration).meta();

        Arrays.stream(meta.filterSchemas(v -> v.getName().equalsIgnoreCase("DB2INST1"))
                        .ddl()
                        .queries())
                .map(Object::toString)
                .forEach(System.out::println);
```

Executing the resulting query against a different database or schema:
```sql
create view "DB2INST1"."A"("ID")
as
select *
from B
create view "DB2INST1"."B"("ID")
as
select *
from C
create view "DB2INST1"."C"("ID")
as
select *
from TEST_TABLE
create table "DB2INST1"."TEST_TABLE" (
  "ID" varchar(50)
)
```

leads to the error:
```sql
SQL Error [42704]: "DB2INST1.B" is an undefined name.. SQLCODE=-204, SQLSTATE=42704, DRIVER=4.31.10
```

### jOOQ Version

jOOQ Professional Edition 3.18.4

### Database product and version

DB2 v11.5.8.0

### Java Version

openjdk 17.0.2 2022-01-18

### OS Version

Microsoft Windows [Version 10.0.19044.2846]

### JDBC driver name and version (include name if unofficial driver)

com.ibm.db2.jcc:db2jcc:db2jcc4

**Comment by lukaseder** [comment]
Thanks for your suggestion. You're right, that seems useful. We currently don't maintain object dependency trees that would be required for this purpose, in none of the meta models (generated code, JDBC `DatabaseMetaData` backed, or XML backed). I've created a feature request for this:
https://github.com/jOOQ/jOOQ/issues/15327

Numerous RDBMS provide this meta information directly from their dictionary views, so we can get it right out of the box for many (not all) RDBMS. If this information isn't available, we can still try to parse the views for this purpose, though we'll be running into any limitation of our parser if views use too many vendor specific features.

**Comment by lukaseder** [comment]
Will look into this soon. While maintaining the complete order of views is a bit harder (https://github.com/jOOQ/jOOQ/issues/15327), re-ordering tables and views in the "obvious" way (tables first, then views) seems much more simple.

I'll make this issue about that.

**Comment by lukaseder** [comment]
I mean, that aleady addresses the most important issue.

Some RDBMS (e.g. Oracle) allow for views to be invalid for a certain time, only to compile them later when they're all "ready", so in those RDBMS, the order of view creation might not be very important.

**Comment by lukaseder** [comment]
Also, this improvement can be backported, #15327 probably not.

If you have other ideas of partial fixes that could be backported, I'm all ears.
