### ISSUE TITLE
function returning setof record type results in generated table

### ISSUE THREAD

**Issue by robstoll** [jOOQ/jOOQ#15358]
### Expected behavior

no need to generate a table for the following function because we return an existing record.

```
CREATE TABLE my_schema.bar
(
    baz varchar not null
);

CREATE OR REPLACE FUNCTION my_schema.foo()
 RETURNS SETOF bar
 LANGUAGE sql
 STABLE STRICT
AS $function$
select * from my_schema.bar where baz = 'happy coding'
$function$;
```

### Actual behavior

creates a table Foo and Routines.foo returning Foo instead of Bar:
```
    /**
     * Get <code>my_schema.foo</code> as a table.
     */
    public static Foo foo() {
        return tables.Foo.FOO.call(
        );
    }
```
I guess it would make sense to have an own Foo if it were defined as read-only table or the like.

**Edit:**
Looks like this was a breaking change introduced with jooq 3.18.x, when using jooq 3.17.13 it generated a FooRecord in addition. Although breaking change, I think it is a step in the right direction. One step ahead (don't generate table Foo) and we are good I guess

### Steps to reproduce the problem

see code above

### jOOQ Version

3.18.4

### Database product and version

postgresql 

### Java Version

jdk 17

### OS Version

ubuntu 22.04

**Comment by lukaseder** [comment]
That looks correct to me, no?

The `Routines.foo()` method returns a *function call*, not the result. You're not executing the function by calling that method. The point is for this function call to be embeddable in SQL queries, such as:

```java
ctx.selectFrom(Routines.foo()).fetch();
```

There should also be a `Routines.foo(Configuration)` method, which should return `Result<BarRecord>`

**Comment by robstoll** [comment]
It's not entirely wrong, but it would be better if Routines.foo() would return Bar because, imagine you have defined something for type Bar, then you cannot re-use because Routines.foo() does not return Bar but Foo

**Comment by lukaseder** [comment]
But it's not a `Bar` table it's a stored function call returning `BarRecord`, so why would you want the code generator to ignore this fact?

I feel there's an underlying use-case here that you can't implement the way you want, which is why you're saying *"it would be better if..."* even if you should be saying *"I would like to do X,  but here's why the status quo is making this hard..."*

Without context, it won't make sense to discuss a claim like *"it would be better"*, because it obviously wouldn't just be better. It would be different, for some unknown reason, "better" to you (though, I'm not sure about this yet), it would probably be worse for others, etc.

**Comment by robstoll** [comment]
> But it's not a Bar table it's a stored function call returning BarRecord, so why would you want the code generator to ignore this fact?

First of all, I am totally happy with the overload which returns BarRecord, it's the overload which returns Foo which bothers me.

I don't think we need the distinction and as far as I can see, the code generator kind of ignores it as well because it defines `Foo extends TableImpl<BarRecord>` and not something like `Foo extends TableFunctionImpl<BarRecord>`. But I don't mind that. I think we don't need a Foo because it is a 1:1 copy of `Bar extends TableImpl` or do I miss something?

Regarding the use case, I have different tables which have columns in common. Let's say Table A, B and Bar are sharing the same column Z which is a boolean. I let Table A, B and Bar implement a common interface. Some function expects this interface because it creates a query based on the given table.

With the current state, I have to make sure each generated class for table functions implement the same interface. Absolutely doable but a bit annoying.

I don't see the use case why we need a separate `Foo`. I get that we would need it if I had returned custom columns instead of a table.

**Comment by lukaseder** [comment]
I'm sorry for the delay. I can see your points. I'll think about it a bit more. Perhaps the desired behaviour could be achieved simply by subclassing the original table, or by introducing a common base class for both to subclass.

The main reason I objected is again the fact that the runtime `QueryPart` isn't the same. One is a function call producing a table type, the other is a table reference. When you traverse jOOQ expression trees with traversers / replacers (in the `QOM` API), then you would definitely want to be able to distinguish between the two (e.g. to substitute one for the other). The fact that currently both are `TableImpl` is merely incidental.

What you're asking for is type *compatibility* in the DSL, not for the two things to be the *same thing*. (It's different for `Record` types, where the function table record can indeed act like the actual table record)
