### ISSUE TITLE
Table with 255 columns generates record and POJO objects whose constructors have too many parameters

### ISSUE THREAD

**Issue by timveil** [jOOQ/jOOQ#15375]
### Expected behavior

the java generator should create a "record" object with a valid number of constructor parameters that compiles.

### Actual behavior

the java generator generates a record object that doesn't compile with the error `java: too many parameters`

### Steps to reproduce the problem

the issue only impacts the record and pojo types when generating java code pointing to a table with exactly 255 columns.  i believe the logic in the `JavaGenerator` class at line number 2162 is incorrect....

`if (pojoArgument || degree > 0 && degree < 256) {`

should be...

`if (pojoArgument || degree > 0 && degree < 255) {`

this seems to be related to the earlier issue #3176.

### jOOQ Version

3.18.5

### Database product and version

postgres 14

### Java Version

openjdk 11.0.19 2023-04-18

### OS Version

mac

### JDBC driver name and version (include name if unofficial driver)

postgres 42.6.0

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can reproduce this. Famous off-by-1 error. Interestingly, our tests only covered "usual sizes" (few columns) and very large tables, not the sizes at the exact threshold.

The workaround here would be to simply exclude a column with includes / excludes settings, or add a synthetic column (e.g. a computed column, server side or client side), or just a dummy column to the table.

**Comment by lukaseder** [comment]
The problem with the off-by-1 error is that the 255th parameter is `this`, a synthetic parameter for instance methods. The limit for instance method is really 254 parameters, when it is 255 for static methods.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.6 (https://github.com/jOOQ/jOOQ/issues/15376)
- 3.17.15 (https://github.com/jOOQ/jOOQ/issues/15377)
- 3.16.21 (https://github.com/jOOQ/jOOQ/issues/15378)

**Comment by lukaseder** [comment]
Fun fact, if there were any `long` or `double` parameters, then the number of supported parameters would be smaller:
https://stackoverflow.com/a/30581726/521799

Luckily, we don't support primitive types like that in our generated models, so we don't run into that "feature."
