### ISSUE TITLE
Exception thrown inside blocking TransactionPublishable gets wrapped by DataAccessException unlike when thrown from non-blocking TransactionPublishable

### ISSUE THREAD

**Issue by saibotma** [jOOQ/jOOQ#15394]
### Expected behavior

jOOQ should wrap the source exception once.

### Actual behavior

jOOQ wraps the source exception twice.

### Steps to reproduce the problem

- Create a simple Kotlin project
- Run `main` of the example code below.
- Notice that it prints `first cause: java.lang.Exception: Test; second cause null` twice.
- Run the test of the example code below.
- Notice that it prints `first cause: java.lang.Exception: Test; second cause null` and then `first cause: org.jooq.exception.DataAccessException: Exception when blocking on publisher; second cause java.lang.Exception: Test`

JUnit: `org.junit.jupiter:junit-jupiter-api:5.9.3`
Kotlin: 1.9.0

<details>
<summary>Example</summary>

```
import kotlinx.coroutines.runBlocking
import org.jooq.SQLDialect
import org.jooq.impl.DSL
import org.jooq.kotlin.coroutines.transactionCoroutine
import org.junit.jupiter.api.Test
import org.postgresql.ds.PGSimpleDataSource

fun main() {
    runExample()
}

class ATest {
    @Test
    fun test() {
        runExample()
    }
}

fun runExample() {
    val dataSource = PGSimpleDataSource().apply {
        databaseName = "x"
        user = "x"
        password = "x"
        serverNames = arrayOf("localhost")
        portNumbers = intArrayOf(5432)
    }
    val dslContext = DSL.using(dataSource, SQLDialect.POSTGRES)
    runBlocking {
        try {
            dslContext.transactionResult { _ ->
                throw Exception("Test")
            }
        } catch (e: Exception) {
            println("first cause: ${e.cause}; second cause ${e.cause?.cause}")
        }
        try {
            dslContext.transactionCoroutine { _ ->
                throw Exception("Test")
            }
        } catch (e: Exception) {
            println("first cause: ${e.cause}; second cause ${e.cause?.cause}")
        }
    }
}
```

</details>

### jOOQ Version

Community 3.18.5

### Database product and version

Postgres 15.3

### Java Version

openjdk version "17.0.6" 2023-01-17

### OS Version

MacOs 13.4 (22F66)

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment]
Thanks for your report. I tried your code with 3.19.0-SNAPSHOT and got this:

```
first cause: java.lang.Exception: Test; second cause null
first cause: java.lang.Exception: Test; second cause null
```

Will try again with 3.18.5

**Comment by lukaseder** [comment]
Same with 3.18.5 and 3.18.6-SNAPSHOT. Can you please try to isolate the problem in an MCVE (e.g. following the usual template here: https://github.com/jOOQ/jOOQ-mcve)

**Comment by saibotma** [comment]
Can reproduce it here:
https://github.com/saibotma/jooq-transaction-coroutine-mcve/blob/main/jOOQ-mcve-kotlin-postgres/src/test/kotlin/org/jooq/mcve/test/kotlin/postgres/KotlinTest.kt

Log cutout:
```
first cause: java.lang.Exception: Test; second cause null
21:56:45,716 DEBUG [org.jooq.impl.DefaultConnectionProvider           ] - setting auto commit      : false
21:56:45,737 DEBUG [reactor.util.Loggers                              ] - Using Slf4j logging framework
21:56:45,742 DEBUG [org.jooq.impl.DefaultConnectionProvider           ] - rollback                 
21:56:45,742 DEBUG [org.jooq.impl.DefaultConnectionProvider           ] - setting auto commit      : true
first cause: org.jooq.exception.DataAccessException: Exception when blocking on publisher; second cause java.lang.Exception: Test
```

**Comment by lukaseder** [comment]
Thanks a lot for your patience. Having a look at the MCVE now, and I can reproduce the issue. I suspect that I may have originally used an R2DBC connection at the time, rather than a JDBC one, which didn't trigger the blocking code, and thus the wrapping in question.

There's an internal `R2DBC::block` utility, which looks like this:

```java
    static final <T> T block(Publisher<? extends T> publisher) {
        Object complete = new Object();
        LinkedBlockingQueue<Object> queue = new LinkedBlockingQueue<>();
        publisher.subscribe(subscriber(s -> s.request(1), queue::add, queue::add, () -> queue.add(complete)));

        try {
            Object result = queue.take();

            if (result instanceof Throwable t)
                throw new DataAccessException("Exception when blocking on publisher", t);
            else if (result == complete)
                return null;
            else
                return (T) result;
        }
        catch (InterruptedException e) {
            throw new DataAccessException("Exception when blocking on publisher", e);
        }
    }
```

It currently doesn't re-throw `Throwable`, because it is used from locations where it isn't allowed to do so. But in the case where transactions are wrapped, this doesn't have to be the case:

```java
    static final class BlockingTransactionSubscription<T> extends AbstractSubscription<T> {
        final DSLContext                  ctx;
        final TransactionalPublishable<T> transactional;

        BlockingTransactionSubscription(
            DSLContext ctx,
            Subscriber<? super T> subscriber,
            TransactionalPublishable<T> transactional
        ) {
            super(subscriber);

            this.ctx = ctx;
            this.transactional = transactional;
        }

        @Override
        final void request0() {
            try {
                subscriber.onNext(ctx.transactionResult(c -> block(transactional.run(c))));
                // No need to wrap Throwable here:           ^^^^^
                subscriber.onComplete();
            }
            catch (Throwable t) {
                subscriber.onError(t);
            }
        }
    }
```

So, I agree we should change this to have consistent behaviour between JDBC and R2DBC backed transactionCoroutines, but it's an incompatible change and thus won't be backported.
