### ISSUE TITLE
Update Gradle example to Kotlin syntax

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#15407]
### The documentation URL

https://www.jooq.org/doc/latest/manual/code-generation/codegen-gradle/

### Feedback

Kotlin is now the preferred language for authoring Gradle builds. The example should be amended or replaced with Kotlin in addition to/instead of Groovy.

**Comment by lukaseder** [comment]
Thanks for your suggestion. This is a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/10504

Please note that I'm working on an official gradle plugin:

- https://github.com/jOOQ/jOOQ/issues/12985

It will include a more idiomatic kotlin DSL integration:

- https://github.com/jOOQ/jOOQ/issues/15400
