### ISSUE TITLE
Feedback about manual section "data-type-conversion"

### ISSUE THREAD

**Issue by eduardolbueno** [jOOQ/jOOQ#15409]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-execution/fetching/data-type-conversion/

### Feedback

Please provide an example of how to filter a query by a custom data type. The page's example only shows how to map a select field, not the other way around (convert from user value to database value).

I have tried several things both with DSL.field and DSL.val, but JOOQ always uses the from() method of the converter no matter what I try.

**Comment by lukaseder** [comment]
Thanks for your message. That particular section could probably be improved, I'll think about that. There are examples all over the place elsewhere, though not on that page.

No matter how you're using `Converter<T, U>` types, they're usually attached to a `DataType<U>`, and thus to a `Field<U>`. In the simplest terms, to convert between `String` and `UserType`:

```java
DataType<String> t = SQLDataType.VARCHAR;
DataType<UserType> u = s.asConvertedDataType(new UserTypeConverter());
```

Now, you can use it everywhere, e.g.

```java
// Plain SQL template:
Field<U> f1 = DSL.field("expression", u);

// Implicit bind values:
Condition c = f1.eq(new UserType());

// Explicit bind values:
Field<U> f2 = DSL.val(new UserType(), u);
```

You'll see that `DataType` is ubiquitous in jOOQ's API
