### ISSUE TITLE
ask, is there a built-in log of the log transaction?

### ISSUE THREAD

**Issue by 847689421** [jOOQ/jOOQ#15408]
### Your question

Ask, is there a built-in log of the log transaction? such begin transaction, commit transaction. If not, how to customize the implementation.

### jOOQ Version

3.18.4

### Database product and version

mysql

**Comment by lukaseder** [comment]
Assuming you're using the `DefaultTransactionProvider`, and jOOQ's transaction API, you can configure a `TransactionListener` to add additional logs.

Alternatively, using a `LoggingConnection` proxy should also do the trick:
https://www.jooq.org/doc/latest/manual/sql-execution/logging-connection/

**Comment by lukaseder** [comment]
I've double checked. You should see `DEBUG` log output from the `DefaultConnectionProvider` class, e.g.:

```
10:16:56,346 DEBUG [DefaultConnectionProvider     ] - setting auto commit      : false
// ...
10:17:51,939 DEBUG [DefaultConnectionProvider     ] - rollback                 
10:17:51,940 DEBUG [DefaultConnectionProvider     ] - setting auto commit      : true
```

The `DefaultTransactionProvider` uses those methods, so it doesn't log anything in addition.

**Comment by 847689421** [comment]
👌Thanks a lot, I'll try。
