### ISSUE TITLE
<pojosAsJavaRecordClasses/> doesn't work with tables containing more than 254 columns

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15411]
The usual Java limit of methods having at most 254 parameters (255 for static methods) is still causing trouble with generated records:

```java
    Integer c254,
    Integer c255
) implements Serializable {
```

The compiler complains:

> Too many parameters, parameter c255 is exceeding the limit of 255 words eligible for method parameters

The solution here is to just generate ordinary POJOs for these tables.

Related problems:

- https://github.com/jOOQ/jOOQ/issues/3176
- https://github.com/jOOQ/jOOQ/issues/15375

I've just noticed, we don't have any integration tests that check these limits for Scala and Kotlin generated code. I'm not sure if those compilers somehow work around the limitation, which is purely a JVM limitation, not strictly a Java language one (i.e. it would be possible for the Java compiler to create synthetic wrapper objects, and unwrap them transparently)

**Comment by rmannibucau** [comment]
@lukaseder even if the fallback you mention is what I used in my app as a quick workaround when I hit that, another (better in some cases) option is to use embeddable records since it will keep the record nature, this is what we used in @yupiik/fusion persistence module, this is not as neat as "flat" records but at least you are strongly immutable, keep an uniform programming model, you stay anemic and JVM efficient so can be another alternative which can be worse mentionning.

**Comment by lukaseder** [comment]
@rmannibucau jOOQ can't make arbitrary decisions about what to embed in what structure, so sure, you as a user can work around such limitations this way, but this issue is about jOOQ's code generator producing something that compiles out of the box.

**Comment by rmannibucau** [comment]
@lukaseder got it but my point is that failling with an error message pointing out some solution can be as wise as doing something magic so fix would be to enhance the error message.

**Comment by lukaseder** [comment]
I've stumbled upon this issue again. I agree with this:

> my point is that failling with an error message pointing out some solution can be as wise as doing something magic so fix would be to enhance the error message.

Will add a warning message to the generation log output:

- https://github.com/jOOQ/jOOQ/issues/17247

**Comment by lukaseder** [comment]
Closing this as won't fix, because there isn't anything we can do on behalf of the user in this case.
