### ISSUE TITLE
3.16.1 Does not support Java8 ?

### ISSUE THREAD

**Issue by wwc7654321** [jOOQ/jOOQ#15415]
### Your question

Because of H2 CVE, we update from 3.14 to 3.16.1 ,but unable to compile:

`org/jooq/codegen/maven/Plugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

3.16.1 Does not support Java8 ? Where can I get the compability information of all versions?

### jOOQ Version

Jooq OpenSource 3.16.1

### Database product and version

mysql 5.7

### Java Version

1.8

**Comment by lukaseder** [comment]
You can find the JDK version support matrix of the various jOOQ Editions here:
https://www.jooq.org/download/versions/#oss

We still support Java 8 in all commercial distributions, and there are no plans to drop support for now.

**Comment by wwc7654321** [comment]
Got it, Open Source Version supports Java8 up to jooq 3.14.16, and Commercial version supports Java8 to all  jooq version

**Comment by lukaseder** [comment]
Yes
