### ISSUE TITLE
Failed to convert Integer to LocalDateTime

### ISSUE THREAD

**Issue by ncheema** [jOOQ/jOOQ#15428]
### Expected behavior

Integer, BigInt and other non decimal date types shoud qualify for "date" conversations.

### Actual behavior

current code only checks for long type. 
https://github.com/jOOQ/jOOQ/blob/2c69f45a7278ad4613c2016dc2bd98964dd4ce30/jOOQ/src/main/java/org/jooq/tools/Convert.java#L947-L952

This results in code invoking the following block which works for timestamp type but not for localdatetme. Note this path is a sideffect of not supporting the Integer and other number type on line 947

https://github.com/jOOQ/jOOQ/blob/2c69f45a7278ad4613c2016dc2bd98964dd4ce30/jOOQ/src/main/java/org/jooq/tools/Convert.java#L1283-L1296

### Steps to reproduce the problem

```kotlin
// ts data Type is LocalDateTime
dslContext.newRecord( table, mapOf(Pair("ts", 2017010))) 
```

### jOOQ Version

Enterprise Java 3.18

### Database product and version

Postgres

### Java Version

Java 11

**Comment by lukaseder** [comment]
Thanks for your suggestion.

We can't implement this as requested. It's not a bug, nor a suggestion with only one obvious solution! Integer timestamps are a slippery slope in all languages, databases, etc. What does the integer represent? You seem to think (given the example) that a decimal `YYYYMMDD` representation in the form of a `java.lang.Integer` is an "obvious" representation of a timestamp (or datetime), but is it really? How can we be sure the user doesn't prefer an epoch value in seconds?

It's different with `Long`. For years, `System.currentTimeMillis()` and many other JDK methods have been working with epoch timestamps in milliseconds.

But this isn't the case for `Integer` values.

A case could be made for `BigInteger`, but I haven't encountered this feature request yet, so far. Is it something that people really expect to work? A `BigInteger` representing an epoch timestamp?

I prefer not to jump to conclusions here. These auto-conversions are very historic in jOOQ. They're not something we should double down on light heartedly. It's very easy to create explicit `Converter` implementations in jOOQ, which aren't ambiguous. You can also override the global behaviour with a custom `ConverterProvider`. I prefer not to take action here.

**Comment by ncheema** [comment]
>It's different with Long. For years, System.currentTimeMillis() and many other JDK methods have been working with epoch timestamps in milliseconds.

Integers can very much can represent epoch(to a certain datet-time). for example 2017010 results in `Thu Jan 01 1970 00:33:37` .

**Comment by ncheema** [comment]
I acknowledge your concerns, however, it should be noted that the current design also contains the gaps you mentioned. In my opinion, a possible solution could be to offer a compromise by giving the client the option to either override or expand upon the existing behavior based on their preferences.

**Comment by lukaseder** [comment]
> a possible solution could be to offer a compromise by giving the client the option to either override or expand upon the existing behavior based on their preferences.

Did you have a look at the options I gave in my previous comment?
https://github.com/jOOQ/jOOQ/issues/15428#issuecomment-1655570033

Specifically:

> It's very easy to create explicit `Converter` implementations in jOOQ, which aren't ambiguous. You can also override the global behaviour with a custom `ConverterProvider`.

**Comment by lukaseder** [comment]
In case this isn't clear, I'm referring to features like these:

- https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-converter/
- https://www.jooq.org/doc/latest/manual/sql-execution/fetching/converter-provider/

**Comment by ncheema** [comment]
Converter Provider is exactly what I need. I was unable to find documentation on how to globally register it? or is it auto registered based on type?

**Comment by lukaseder** [comment]
Well, you can delegate to a `DefaultRecordUnmapper` instance for all things that you don't want to cover yourself?

**Comment by ncheema** [comment]
> Well, you can delegate to a DefaultRecordUnmapper instance for all things that you don't want to cover yourself?

Certainly, delegating to a DefaultRecordUnmapper instance is a viable option for handling this. While it would have been preferable to have overrides on a per-field basis, I appreciate your guidance on this matter. Although I am satisfied with the current override approach, I would appreciate it if you could consider the benefits of adding field-specific overrides.
