### ISSUE TITLE
SQL decimal type generated as BigInteger instead of BigDecimal

### ISSUE THREAD

**Issue by jaroslav-sagan-evooq** [jOOQ/jOOQ#15439]
### Your question

I'm trying to update jOOQ version in our project from `3.15.12` to `3.17.14` and I'm encountering an issue with types in generated java classes.

The table column in liquibase script is defined as follow:
```
- column:
    name: volume
    type: DECIMAL
```

With jOOQ `3.15.12` the corresponding generated java field is of type `BigDecimal` (SQLDataType.DECIMAL)

With jOOQ `3.16.20` the corresponding generated java field is of type `BigInteger` (SQLDataType.DECIMAL_INTEGER) which brakes our project compilation.

I had look at release notes of jOOQ `3.16.20` but I have not noticed anything that could lead to this issue.

Any idea what could be causing this issue and how to resolve it?
I know that I could use `forcedTypes` in maven but it feels like a not correct solution for something that used to work without any issues.

### jOOQ Version

3.16.20

### Database product and version

H2 2.1.214

### Java Version

openjdk version "17.0.7" 2023-04-18 LTS

**Comment by katzyn** [comment]
If you also upgraded your version of H2 from 1.\*.\*, it can be related to changes in H2 itself.

`DECIMAL` data type without parameters can hold only integer values as it should.

**Comment by lukaseder** [comment]
Thanks for your help, @katzyn. I vaguely remember this change as well in H2. jOOQ, by default, generates `BigInteger` for zero-scale `DECIMAL` types, as that most closely represents the datatype in the database. You an check the `INFORMATION_SCHEMA.COLUMNS` table to see what H2 reports as a data type.

As such, I think your schema is now wrong after the H2 upgrade, and you should make the scale explicit. Using a forced type would just hide the fact that H2 now stops storing the fractional part on a `DECIMAL` type.

Let me know if you have any further questions.

**Comment by jaroslav-sagan-evooq** [comment]
Thank you for your help @katzyn and @lukaseder, the issue is really caused by the `DECIMAL` type, after adding precision and scale the generated type was again `BigDecimal`
