### ISSUE TITLE
Provide a common abstraction for SelectSeekLimitStep and SelectLimitStep

### ISSUE THREAD

**Issue by Spikhalskiy** [jOOQ/jOOQ#15435]
### Use case

I have a query factory method that does or does not apply .seek() depending on the input parameters. The user of this factory method should be able to apply a .limit(). Currently, there is no interface that can be returned from the method for this purpose. limit() methods are defined independently in `SelectSeekLimitStep` and `SelectLimitStep`.

```
fun caller() {
  val dtos = buildSelect().limit(10).fetch()
}

fun buildSelect(paginationToken: PaginationToken?): SOMETHING {
  val selectQuery = ....
  return if (paginationParams != null) selectQuery.seek() else selectQuery
}
```

### Possible solution

It looks like SelectLimitStep can extend SelectSeekLimitStep right now. If this hierarchy looks wrong, maybe a new common parent can be introduced with

```
    SelectForUpdateStep<R> limit(Number numberOfRows);
    SelectForUpdateStep<R> limit(Field<? extends Number> numberOfRows);
```

### Possible workarounds

In the situation I described, .limit can be pushed into the builder and be called in

```
fun buildSelect(paginationToken: PaginationToken?): SOMETHING {
  val selectQuery = ....
  return if (paginationParams != null) selectQuery.seek().limit(n) else selectQuery.limit(n)
}
```

but even this workaround is kinda unpleasant, because we need to have code duplicated for `.limit` in different `if` branches because of this lack of the common abstraction.

### jOOQ Version

3.18.5

**Comment by lukaseder** [comment]
Thanks for your suggestion.

It is unlikely this is the best approach to solve the problem. The DSL has grown complex and adding "common types" to it doesn't seem right, given that some clauses may only appear on some DSL paths. Adding auxiliary types now for very specific non-DSL usage purposes is likely not to be forward compatible, meaning a future clause addition will be in contradiction with an auxiliary type that has been added short-sightedly.

It's a DSL after all, not an ordinary builder API (as opposed to the historic `SelectQuery` or the new experimental query object model API, where clauses can be added to queries in arbitrary order).

As such, I will reject this feature request asking for new auxiliary DSL types.

However, have you tried passing `DSL::noField`?
https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql/no-field/
