### ISSUE TITLE
JOOQ Codegen on Firebird 2.5 error

### ISSUE THREAD

**Issue by sugihartolim** [jOOQ/jOOQ#15438]
### Steps to reproduce the problem

I understand that firebird 2.5 is not supported anymore by JOOQ OSS after 3.7 according to this page: https://www.jooq.org/download/support-matrix 

But here's a rather weird regression that i found when running JOOQ codegen on a production database: 

Running codegen on a firebird 2.5 database fails under the latest JOOQ with the following error: 
> ```Error running jOOQ code generation tool: Error generating code for catalog: org.jooq.exception.DataAccessException: SQL [select trim(RDB$FIELDS.RDB$FIELD_NAME) RDB$FIELD_NAME, case RDB$FIELDS.RDB$FIELD_TYPE when cast(? as smallint) then cast(? as smallint) else RDB$FIELDS.RDB$CHARACTER_LENGTH end CHAR_LEN, RDB$FIELDS.RDB$FIELD_PRECISION, -(RDB$FIELDS.RDB$FIELD_SCALE) FIELD_SCALE, case RDB$FIELDS.RDB$FIELD_TYPE when cast(? as smallint) then case when RDB$FIELDS.RDB$FIELD_SUB_TYPE = cast(? as smallint) then cast(? as varchar(4000)) when (RDB$FIELDS.RDB$FIELD_SUB_TYPE = cast(? as smallint) and RDB$FIELDS.RDB$FIELD_SCALE < cast(? as smallint)) then cast(? as varchar(4000)) when RDB$FIELDS.RDB$FIELD_SUB_TYPE = cast(? as smallint) then cast(? as varchar(4000)) else cast(? as varchar(4000)) end when cast(? as smallint) then case when RDB$FIELDS.RDB$FIELD_SUB_TYPE = cast(? as smallint) then cast(? as varchar(4000)) when (RDB$FIELDS.RDB$FIELD_SUB_TYPE = cast(? as smallint) and RDB$FIELDS.RDB$FIELD_SCALE < cast(? as smallint)) then cast(? as varchar(4000)) when RDB$FIELDS.RDB$FIELD_SUB_TYPE = cast(? as smallint) then cast(? as varchar(4000)) else cast(? as varchar(4000)) end when cast(? as smallint) then cast(? as varchar(4000)) when cast(? as smallint) then cast(? as varchar(4000)) when cast(? as smallint) then cast(? as varchar(4000)) when cast(? as smallint) then cast(? as varchar(4000)) when cast(? as smallint) then cast(? as varchar(4000)) when cast(? as smallint) then cast(? as varchar(4000)) when cast(? as smallint) then case when RDB$FIELDS.RDB$FIELD_SUB_TYPE = cast(? as smallint) then cast(? as varchar(4000)) when (RDB$FIELDS.RDB$FIELD_SUB_TYPE = cast(? as smallint) and RDB$FIELDS.RDB$FIELD_SCALE < cast(? as smallint)) then cast(? as varchar(4000)) when RDB$FIELDS.RDB$FIELD_SUB_TYPE = cast(? as smallint) then cast(? as varchar(4000)) else cast(? as varchar(4000)) end when cast(? as smallint) then cast(? as varchar(4000)) when cast(? as smallint) then cast(? as varchar(4000)) when cast(? as smallint) then cast(? as varchar(4000)) when cast(? as smallint) then cast(? as varchar(4000)) when cast(? as smallint) then case RDB$FIELDS.RDB$FIELD_SUB_TYPE when cast(? as smallint) then cast(? as varchar(4000)) when cast(? as smallint) then cast(? as varchar(4000)) else cast(? as varchar(4000)) end else cast(? as varchar(4000)) end FIELD_TYPE, bin_or(coalesce(RDB$FIELDS.RDB$NULL_FLAG, cast(? as smallint)), coalesce(RDB$FIELDS.RDB$NULL_FLAG, cast(? as smallint))) RDB$NULL_FLAG, trim(RDB$FIELDS.RDB$VALIDATION_SOURCE) RDB$VALIDATION_SOURCE, trim(RDB$FIELDS.RDB$DEFAULT_SOURCE) RDB$DEFAULT_SOURCE from RDB$FIELDS where (RDB$FIELDS.RDB$FIELD_NAME not like cast(? as varchar(4000)) or RDB$FIELDS.RDB$FIELD_NAME not like cast(? as varchar(4000)) or RDB$FIELDS.RDB$FIELD_NAME not like cast(? as varchar(4000))) order by RDB$FIELDS.RDB$FIELD_NAME]; Dynamic SQL Error; SQL error code = -204; Implementation limit exceeded; block size exceeds implementation restriction [SQLState:54000, ISC error code:335544381] -> [Help 1] ```

I understand that the SQL Error Message came from firebird due to the 64KB row limit, but that SQL can't be right.   

Here's a quick bisection on different versions of codegen, something broke it in 3.16.xx release 
```
3.7.4 OK
3.12.4 OK 
3.14.16 OK 
3.15.12 OK 
3.16.20 FAIL 
3.18.4 FAIL 
```
Just in case i'm barking up the wrong tree, and this is actually CastMode acting up again, how do i specify CastMode.NEVER on maven codegen? 

Thank you.

### jOOQ Version

multiple tested

### Database product and version

firebird 2.5

### Java Version

jdk 17 

### JDBC driver name and version (include name if unofficial driver)

jaybird 5.0.2

**Comment by lukaseder** [comment]
Thanks for your report. I'm not getting such an error. Probably, one of these issues fixed the problem for the commercial editions and FB 2.5:

- #1727
- #3398

I recommend upgrading jOOQ to a commercial distribution (the jOOQ Express Edition supports Firebird 2.5), or upgrading Firebird itself.
