### ISSUE TITLE
AutoConverter loses nanosecond precision when converting from Instant to LocalDateTime or OffsetDateTime

### ISSUE THREAD

**Issue by wingsofovnia** [jOOQ/jOOQ#15433]
### Expected behavior

When `TIMESTAMP`/`DATETIME` is "forced" into `java.time.Instant` (no converter specified), writing a record and reading it back returns the same `Instant`.

### Actual behavior

When forcing `TIMESTAMP`/`DATETIME` into `java.time.Instant` using default conversion, nano part is lost on write-read.

### Steps to reproduce the problem

1. Set up forcing of `TIMESTAMP`/`DATETIME` into `java.time.Instant`, see https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/
The generated field looks like this:
```kt
val CREATED_AT: TableField<TestRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", AutoConverter<LocalDateTime, Instant>(LocalDateTime::class.java, Instant::class.java))
```
2. Create a record (`TestRecord` here) using `Instant(2023-08-01T14:58:50.688595Z)` (for example).
3. Write it into the table and read back.
4. The record retrieved has `Instant(2023-08-01T14:58:50.688Z)`

`595` got trimmed:
```
written: Instant(2023-08-01T14:58:50.688595Z)
read:    Instant(2023-08-01T14:58:50.688Z)
```

Pseudocode of a use-case:
```
val id = 1;
val createdAt = Instant.now()
val origTestRecord = TestRecord(id = id, createdAt = createdAt)
jooqRepo.insert(origTestRecord)

val retrievedTestRecord = jooqRepo.findById(id)
assertEquals(origTestRecord, retrievedTestRecord) // fails due to createdAt not being eq
```

The loss occurs here, where `Instant` falls into a condition, where `OffsetDateTime` is expected:
https://github.com/jOOQ/jOOQ/blob/2c69f45a7278ad4613c2016dc2bd98964dd4ce30/jOOQ/src/main/java/org/jooq/impl/Convert.java#L1558-L1560

One way to fix might be to treat `Instant` exclusively here like other `java.time` types:
https://github.com/jOOQ/jOOQ/blob/2c69f45a7278ad4613c2016dc2bd98964dd4ce30/jOOQ/src/main/java/org/jooq/impl/Convert.java#L987-L999

As a workaround, a custom converter `Converter<LocalDateTime, Instant>` can be used.

### jOOQ Version

3.18.5

### Database product and version

PostgreSQL 14.8 (Homebrew) on x86_64-apple-darwin21.6.0, compiled by Apple clang version 14.0.0 (clang-1400.0.29.202), 64-bit

### Java Version

openjdk version "17.0.7" 2023-04-18

### OS Version

MacOS 12.6.6

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment]
Thanks a lot for your report.

Can you please share the exact code generation configuration to create your column definition, as well as the `CREATE TABLE` statement for your table?

**Comment by lukaseder** [comment]
Having another look at this, I guess I was side-tracked by the fact that you attached a converter to the column.

We can work with only the `Convert` utility to look into a fix.

**Comment by lukaseder** [comment]
> The loss occurs here, where `Instant` falls into a condition, where `OffsetDateTime` is expected:

This assessment isn't correct. The `millis()` method is used only to convert `Temporal` values to `Long` or `ULong`, in case of which the loss of precision is expected. At least, when converting between `OffsetDateTime` and `Instant` directly, that problem doesn't appear.

So, I still need to try to reproduce this the way you're running the code.

**Comment by lukaseder** [comment]
Ah, I've just noticed, you're using `TIMESTAMP`, not `TIMESTAMP WITH TIME ZONE`! Is this by accident? It doesn't look like the correct data type to use when you want an `Instant`..

**Comment by lukaseder** [comment]
Maybe, I should have read your report to the end, thoroughly 😅

> One way to fix might be to treat `Instant` exclusively here like other `java.time` types: [...]

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.6 (https://github.com/jOOQ/jOOQ/issues/15456)
- 3.17.15 (https://github.com/jOOQ/jOOQ/issues/15457)
- 3.16.21 (https://github.com/jOOQ/jOOQ/issues/15458)

**Comment by wingsofovnia** [comment]
Thank you for looking into that!
