### ISSUE TITLE
Ability to write lazily-materialized dialect dependent code, via something like `DSL.ifDialect(SQLDialect)` or `DSL.whenDialect(EnumMap<SQLDialect, Field>)`

### ISSUE THREAD

**Issue by GavinRay97** [jOOQ/jOOQ#15430]
### Use case

There are, in a few nooks and crannies of our codebase, workarounds for bugs on certain dialects in which we use alternate field values.

Currently we do this by threading a `SQLDialect` value through the code -- though this is less-than-ideal because we don't enforce that the passed `SQLDialect` is the one used when the `DSL.context()` is created and the statement rendered.

Our code has bits like:
```kt
DSL.select().let {
  if (dialect == SQLDialect.Oracle)
	workaroundForOracleBug(it)
  else
    it
}
```

It would be nice if jOOQ had a method to declare things like using the agnostic `DSL` static methods so that during rendering/materialization the proper path is chosen.

I'm imagining an API something like:
```kt
DSL.select().let {
  DSL.ifDialect(SQLDialect.Oracle, workaroundForOracleBug(it), it)
}

DSL.select().let {
    DSL.whenDialect(
        EnumMap<SQLDialect, Field<*>>(
            mapOf(
                SQLDialect.ORACLE to workaroundForOracleBug(it),
                SQLDialect.POSTGRES to it
            )
        ),
        // Maybe allow passing a fallback/default param here?
        it
    )
}
```

Please let me know if something like this is already possible or this isn't technically feasible.

Thank you!
- Gavin

### jOOQ Version

3.19.0-SNAPSHOT Enterprise

### Database product and version

N/A

**Comment by lukaseder** [comment]
Thanks for your message.

I believe, the `CustomField` and similar types would probably help here?

- https://www.jooq.org/doc/latest/manual/sql-building/queryparts/custom-queryparts/
- https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/CustomField.html

For example:

```java
CustomField.of(name, dataType, ctx -> {
    if (ctx.family() == ORACLE)
        return ...;
    else
        return ...;
});
```

**Comment by GavinRay97** [comment]
Ah I didn't think about the possibility of making wrappers around `CustomField`.

For anyone who wants to do something like this in the future, you can do something like:
```kt
fun <T> ifDialect(dialect: SQLDialect, fieldWhenTrue: Field<T>, fieldWhenFalse: Field<T>) =
    CustomField.of("if_dialect", fieldWhenTrue.dataType) { ctx ->
        ctx.visit(
            if (this.dialect == dialect) {
                fieldWhenTrue
            } else {
                fieldWhenFalse
            }
        )
    }

fun <T> whenDialect(dialectToFieldMap: Map<SQLDialect, Field<T>>, defaultValue: Field<T>? = null) =
    CustomField.of("when_dialect", dialectToFieldMap.values.first().dataType) { ctx ->
        ctx.visit(
            dialectToFieldMap[this.dialect]
                ?: defaultValue
                ?: throw IllegalArgumentException("No default field value provided")
        )
    }
```
