### ISSUE TITLE
Support "RANGE BETWEEN" for date-ranges

### ISSUE THREAD

**Issue by valentin-panalyt** [jOOQ/jOOQ#15440]
### Use case

The following SQL should be supported:
```
max(date_column) over (partition by foo_column order by date_column RANGE BETWEEN '1 year' PRECEDING AND CURRENT ROW)
```

Currently there is support for using a fixed number of rows (using `org.jooq.WindowSpecificationRowsStep#rowsBetweenPreceding(int number)`) but not for specifying a date-range such as `1 year` or `1 week`.

### Possible solution

Support the other range-cases. See: https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS and look for `RANGE BETWEEN '1 day' PRECEDING AND '10 days' FOLLOWING` on this page.

### Possible workarounds

No workarounds except generating a plain sql-string inplace.

### jOOQ Version

3.18.4

### Database product and version

Postgres 15

**Comment by lukaseder** [comment]
Thanks for your report. This is already on our roadmap: https://github.com/jOOQ/jOOQ/issues/5577
