### ISSUE TITLE
Materialized view fields not generated

### ISSUE THREAD

**Issue by trourance** [jOOQ/jOOQ#15475]
### Your question

I'm not sure if it's a bug or a current limitation. 
Since jooq-3.18.6, I'm able to generate code for `CREATE MATERIALIZED VIEW` statement using CockroachDB dialect. However, only the table is created, I have no `TableField` in the corresponding class.

### jOOQ Version

jOOQ Professional Edition 3.18.6

### Database product and version

CockroachDB 22.9

### Java Version

openjdk version "11.0.16.1"

### OS Version

Linux

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment]
Thanks for your report. Our integration tests indicate no such thing. But of course, there could always be an edge case that our tests don't cover.

Can you please provide further information, i.e. a complete reproducer? We have a template for reproducers here: https://github.com/jOOQ/jOOQ-mcve, but it may not be necessary. At least a `CREATE MATERIALIZED VIEW` statement along with all the underlying table definitions, and a code generation configuration that helps reproduce the problem will be required, though.

**Comment by trourance** [comment]
The issue was due to a partial update of jooq artifacts. Once it has been fixed, the fields have been generated correctly in the code. Sorry for the noise.

**Comment by trourance** [comment]
The issue was due to a partial update of jooq artifacts. Once it has been fixed, the fields have been generated correctly in the code. Sorry for the noise.

**Comment by lukaseder** [comment]
No problem, thanks for the feedback.
