### ISSUE TITLE
RecordMapper for multiset operator

### ISSUE THREAD

**Issue by MelleD** [jOOQ/jOOQ#15477]
I discovered the [multiset operator](https://blog.jooq.org/jooq-3-15s-new-multiset-operator-will-change-how-you-think-about-sql/) and am trying to use it to join.
However, I get problems with record mapping to turn the table records back into POJOs
With "normal" selects this could easily be done with tableRecord.into. However, that no longer works.

Multiset operator

```
      final Foo foo =
            getDslContext().select(
                        asterisk(),
                        multiset(
                              select( asterisk() )
                                    .from( BARS )
                                    .where( BARS.FOO_ID.eq( FOO.ID ) )
                        ).as( "bars" ),
                  )
                  .from( FOO )
                  .where( FOO.ID.eq(1) )
                  .fetchOne( this::createEntity );
```

```
   public Foo createEntity( final FooRecord tableRecord) {
      return tableRecord.into( Foo.class );
   }
```

Error
```
FUNCTIONAL PROPERTY
An error occurred when mapping record to class Foo

Caused by: org.jooq.exception.DataTypeException: Cannot convert from +----+-----------+--------+---------+----------+----------------+-------------+----------------+
|  id|name|foo_id
+----+-----------+--------+---------+----------+----------------+-------------+----------------+
|   1|KWPYPZZYQH |       1|
|   2|ASZVW      |       1|
+----+-----------+--------+---------+----------+----------------+-------------+----------------+
 (class org.jooq.impl.ResultImpl) to interface java.util.Set
	at org.jooq.impl.Convert$ConvertAll.fail(Convert.java:1591)
	at org.jooq.impl.Convert$ConvertAll.from(Convert.java:1432)
	at org.jooq.impl.Convert.convert0(Convert.java:442)
	at org.jooq.impl.Convert.convert(Convert.java:517)
	at org.jooq.impl.DefaultConverterProvider.lambda$provide$1(DefaultConverterProvider.java:121)
	at org.jooq.Converter$1.from(Converter.java:181)
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:355)
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:971)
	at org.jooq.impl.DefaultRecordMapper$MutablePOJOMapper.map(DefaultRecordMapper.java:901)
	... 98 more
```

What is the best way to map the relationship?
I guess I have to map the bar table record somewhere

### jOOQ Version

jOOQ Professional 3.18.4

### Database product and version

SQL Server TestContainer or Azure SQL

**Comment by lukaseder** [comment]
> but as you can see there is a problem with the internal relationships with Set

Well, I can guess what you're doing, but I can't really see it. E.g. if you could include the actual target data types in a reproducer, I can better see what your expectations might be.

**Comment by MelleD** [comment]
I created a small example: https://github.com/MelleD/muliset-example and used the our pro dep. 

1. Start docker
2. mvn clean build install
3. Execute FooRepositoryTest#testSelect

Then you should see:

```
...
Caused by: org.jooq.exception.DataTypeException: Cannot convert from +----+------+----+
|  id|foo_id|name|
+----+------+----+
|   1|     1|bar1|
|   2|     1|bar2|
+----+------+----+
 (class org.jooq.impl.ResultImpl) to interface java.util.Set
```

**Comment by lukaseder** [comment]
> I created a small example: https://github.com/MelleD/muliset-example

Thanks for that. I can reproduce it. Will try to minimise the example. I think it should work, given how simple the mapping is. We do support nesting `List<Bar>`, but not `Set<Bar>` yet in nested collection mappings. But I don't think there's any good reason why we shouldn't. `Result.intoSet()` semantics is well defined in jOOQ, so we can do this with the reflective approach. I double checked, if you're declaring `List<Bar>` (or `Set<Bar>`, in the future) in a property, then the types aren't erased entirely from reflection access, at least.

In any case, rather than depending on reflection magic, I think the explicit approach should be better.

> So is there a possibility to select all fields?

You can just project `FOO` (the table), and attach an ad-hoc converter to it, if you like.

**Comment by MelleD** [comment]
> In any case, rather than depending on reflection magic, I think the explicit approach should be better.

I now use the convert method directly, that also works in my real example. That didn't work before because of the `asterisk() `methods, because the return type is different then. That was my mistake

> You can just project FOO (the table), and attach an ad-hoc converter to it, if you like.

What do you mean? Do you have an example or documentation?

**Comment by lukaseder** [comment]
> > You can just project FOO (the table), and attach an ad-hoc converter to it, if you like.
> 
> What do you mean? Do you have an example or documentation?

https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/select-clause/select-clause-table/

**Comment by lukaseder** [comment]
Here's the follow up issue regarding the mapping of `Set<P>` from `DefaultRecordMapper`:

- https://github.com/jOOQ/jOOQ/issues/15488

**Comment by MelleD** [comment]
Hey @lukaseder one more question:

Do you also have experience with multiset and the seek method? I am currently checking which method is better for us. We (unfortunately) have an entity that has many relationships and needs to be fully loaded.

When searching for an entity directly, the multiset is much faster, but in conjunction with the seek method, the multiset is slower than to load the relations with SELECT IN (for every relation)

**Comment by lukaseder** [comment]
Maybe this helps?
https://blog.jooq.org/the-performance-of-various-to-many-nesting-algorithms/

**Comment by MelleD** [comment]
> Maybe this helps?

I have read the article. For this reason I started an benchmark experiment.


That will probably be the reason.
"
For large-ish data sets (where filter = false), the N+1 factor of a MULTISET correlated subquery can become a problem (due to the nature of algorithmic complexity), as it prevents using more efficient hash joins. In these cases, the single query JOIN based approach or 1-query-per-nest-level approach are better
"

But it's very interesting.
Attempt is: 400,000 records with some relationships and loop over the whole dataset ( steps of 500) using the seek method.
The overall perfomance is almost identical. Tried it also with 100k,200k,300k looks the same.

```
StopWatch 'Performance Test Result All': running time = 1502469270790 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
707049674333  047 %  Select In All
795419596457  053 %  Select MULTISET All
```

But "only" loading the first 500 (first page) always has a big performance difference.
```
StopWatch 'Performance Test Result All First Page': running time = 239347251108 ns
---------------------------------------------
ns         %     Task name
---------------------------------------------
9134133874  004 %  Select In All First Page
230213117234  096 %  Select MULTISET All First Page
```


With a filter, the mulitset is unbeatable.

**Comment by lukaseder** [comment]
> With a filter, the mulitset is unbeatable.

Great to hear

> But "only" loading the first 500 (first page) always has a big performance difference.

SQL performance is a fun topic. A lot of RDBMS implement only "so many" SQL transformations. And then, suddenly, they add new ones and the results you're seeing today will be outdated.

For example, the claim I made in the article about hash joins being prevented will (hopefully) be outdated as well some day. There's no reason why JSON aggregation should remain completely opaque to optimisers forever. People will probably use these features more and more, now that everyone is pushing JSON (thanks also to Oracle and their standardisation efforts!)

I can't see what exactly you're doing with SEEK and MULTISET, so I'm not sure what could be the exact reason for the observed performance difference, but perhaps, there's a simple trick already today to make the optimiser choose a better plan.

**Comment by MelleD** [comment]
> SQL performance is a fun topic. A lot of RDBMS implement only "so many" SQL transformations. And then, suddenly, they add new ones and the results you're seeing today will be outdated.

That's so true. Luckily we currently have no performance issue and the improvements are in ms range.
I wanted to test and compare this method (which was new to me).

> I can't see what exactly you're doing with SEEK and MULTISET

I haven't looked at the execution plan of the Seek yet.

As a test, I simply used the same select as for a single record, only without the where condition. Then I simply iterate through with the seek method from start to end + load the relations. I haven't done any further analysis yet

**Comment by lukaseder** [comment]
> I saw currently the default for SQL Server is XML emulation. Maybe should I try another emulation?

The reason is SQL Server's limited JSON array support in the past. Recent SQL Server versions have added `JSON_ARRAY` support, but if I remember correctly there were still many bugs.
