### ISSUE TITLE
Map Reducing a Set of Values Into a Dynamic SQL UNION Query

### ISSUE THREAD

**Issue by trourance** [jOOQ/jOOQ#15470]
### Your question

Based on the information posted in the following blog [post](https://blog.jooq.org/map-reducing-a-set-of-values-into-a-dynamic-sql-union-query/), I have tried to reproduce something similar for a multiple conditional joins I need in my SQL statement.

However, it seems that this is not a valid option anymore since the following [change](https://github.com/jOOQ/jOOQ/issues/8558#ref-commit-32daa4e) has been pushed in the code as I get the following error:
`In jOOQ 3.x's mutable DSL API, it is not possible to use the same instance of a Select query on both sides of a set operation like s.union(s)`.

So my question is simple: how is it possible to do that nowadays ?

### jOOQ Version

jOOQ Professional Edition 3.18.2

### Database product and version

CockroachDB 22.9

### Java Version

openjdk version "11.0.16.1"

### OS Version

Linux

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment]
Thanks for your message.

I just tried the exact example from the log post, and it produces the expected SQL.

Can you show your actual code, please?

**Comment by trourance** [comment]
Sorry, I'm not using Java so I'm posting a simplified example I've used in Koltin.

```
val baseQuery = select(table.ID, table.NAME).from(table)
val serialCondition = table.SERIAL.containsIgnoreCase(pattern)
val serialQuery: Select<Record2<UUID, String>> = baseQuery.where(serialCondition)
val otherIdCondition = table.OTHER_ID.containsIgnoreCase(pattern)
val otherIdQuery: Select<Record2<UUID, String>> = baseQuery.where(otherIdCondition)
val NfcCondition = table.NFC.containsIgnoreCase(pattern)
val NfcQuery: Select<Record2<UUID, String>> = baseQuery.where(NfcCondition)

val queries = listOf(serialQuery, otherIdQuery, NfcQuery)
return queries.reduce { acc, record2s ->
            acc.union(record2s)
        }
```

I've tried another variant with:
```
val queries = serialQuery.union(otherIdQuery).union(NfcQuery)
```

But I get the same exception.

**Comment by lukaseder** [comment]
The explanation is in the error. `SelectImpl` (the implementation of the `Select` DSL) is mutable for historic reasons, and as such, you shouldn't re-use a `Select` multiple times like this. Fixing this is on the roadmap, but won't be simple (or done soon) for backwards compatibility reasons.

Just extract your `val baseQuery` into a `fun baseQuery()`, and construct the base query several times, instead.

**Comment by trourance** [comment]
That explains perfectly why your example works and mine does not.
