### ISSUE TITLE
Slow compilation time 

### ISSUE THREAD

**Issue by oclay1st** [jOOQ/jOOQ#15496]
### Your question

I'm looking for an advice. Recently I tried JOOQ in a very large project with several tables in the database, 215 to be precise. The code generation tool was really fast, but the amount of generated classes (tables and records only), increased the compilation time of the project in 25 seconds. 
Is there any advice to reduce impact of  the generated classes during the compilation time?. Thanks

### jOOQ Version

3.18.4

### Database product and version

PotsgresSQL15

### Java Version

17

### OS Version

Linux

**Comment by lukaseder** [comment]
Thanks for your message. I've noticed a few users report such issues in the recent past. The common workaround is to turn off `<recordsImplementingRecordN/>`, which is a flag that hardly anyone uses, but defaults to `true`.

jOOQ 3.19 will switch the default to `false`:

- https://github.com/jOOQ/jOOQ/issues/15487

I hope this helps
