### ISSUE TITLE
Direct saving InputStream/OputputStream to table column?

### ISSUE THREAD

**Issue by CamilYed** [jOOQ/jOOQ#15515]
### Your question

Hello,

suppose I want to save a file directly from the controller to the database as a stream of bytes. 

Is this possible using JOOQ and Postgres I have not found anything to guide me to the answer in the documentation.

Let's assume that I have the spring controller:

```
   @PostMapping
    void uploadExcel(@RequestParam("file") MultipartFile file) {
        repository.upload(file.getInputStream());
    }
```

### jOOQ Version

3.17.4

### Database product and version

Postgres 13

### Java Version

17

### OS Version

Osx

### JDBC driver name and version (include name if unofficial driver)

postgres 42.5.0

**Comment by lukaseder** [comment]
Maybe this helps?
https://www.jooq.org/doc/latest/manual/reference/reference-data-types/data-types-lobs/

Note you can always revert to using JDBC if jOOQ doesn't expose one of the underlying concepts explicitly. For example, you can get a JDBC connection using `DSLContext.connection(c -> { ... })`

But anyway, if you look at the pgjdbc implementation, any `InputStream` that you pass to it is either consumed as `byte[]` or `char[]` in some way, so you're not actually gaining anything in the case of PostgreSQL, as opposed to just storing your `byte[]` directly with jOOQ.
