### ISSUE TITLE
Manual should stop recommending use of deprecated DefaultExecuteListener or DefaultRecordListener

### ISSUE THREAD

**Issue by cies** [jOOQ/jOOQ#15511]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-execution/execute-listeners/

### Feedback

On that page I read:

> For convenience and better backwards-compatibility, consider extending [org.jooq.impl.DefaultExecuteListener](https://www.jooq.org/javadoc/latest/org/jooq/impl/DefaultExecuteListener.html) instead of implementing this interface.

And:

> `// Extending DefaultExecuteListener, which provides empty implementations for all methods...`

Once I followed the advice I found that `DefaultExecuteListener` is deprecated.

Maybe there's more cases in the docs.

**Comment by lukaseder** [comment]
Thanks for your hint. Will look into this soon.

**Comment by lukaseder** [comment]
The same applies to the `RecordListener` SPI:
https://www.jooq.org/doc/latest/manual/sql-execution/crud-with-updatablerecords/crud-record-listener/

**Comment by lukaseder** [comment]
I believe I got them all now. Thanks again for your report!

**Comment by cies** [comment]
I'm glad I can help. Thank you for jooq!
