### ISSUE TITLE
Support for typealiases on certain columns

### ISSUE THREAD

**Issue by reubenfirmin** [jOOQ/jOOQ#15538]
### Use case

It's very nice in kotlin to be able to create typealiases for certain things. For example:

```
typealias FooId = UUID

data class(val id: FooId, val name: String)
```

This is not enforced by the compiler, but does lead to self documenting code. Can this be supported as an option?

### jOOQ Version

3.18.6

### Database product and version

Postgres 15

**Comment by lukaseder** [comment]
I'm closing this as won't fix, because the specific idea of "type alias awareness", or even "generating type aliases" doesn't seem worth pursuing at this point.
