### ISSUE TITLE
Kotlin data classes shouldn't include hashCode, toString, equals

### ISSUE THREAD

**Issue by reubenfirmin** [jOOQ/jOOQ#15534]
### Expected behavior

Generated kotlin code shouldn't include overrides of equals/hashcode/toString.

### Steps to reproduce the problem

Generate kotlin pojos.

### jOOQ Version

Jooq open source 3.18.6

### Database product and version

Postgres 15

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/10917
