### ISSUE TITLE
How do I configure codegen to exclude certain columns from the pojos?

### ISSUE THREAD

**Issue by reubenfirmin** [jOOQ/jOOQ#15535]
### Your question

There are certain columns that I don't want to be loaded into pojos.

For example, db housekeeping columns like created / modified don't belong in business logic, and so shouldn't be loaded (and we'd certainly never want to send them to the frontend).

As another example, the field containing the user password hash really shouldn't be loaded either.

Is there a way to set up excludes on a per table basis?

### jOOQ Version

3.18.6

### Database product and version

Postgres 15

**Comment by lukaseder** [comment]
Thanks for your message.

If you *never* need those columns projected (or filtered, etc.), you can exclude them in the code generator, so jOOQ won't know about them. Use `<includeExcludeColumns/>` for that:

- https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-includes-excludes/

If you need them occasionally in queries, I suggest listing the columns explicitly in your queries, which is always a good idea:

- https://www.jooq.org/doc/latest/manual/reference/dont-do-this/dont-do-this-sql-select-all/

Or use views! That's a prime use-case for SQL views. You can also write views with jOOQ by creating reusable derived tables. Or you could patch your generated SQL to exclude those columns when you don't need them:

- https://www.jooq.org/doc/latest/manual/sql-building/model-api/model-api-replacement/

A future jOOQ version will offer emulated invisible column support, too:

- https://github.com/jOOQ/jOOQ/issues/14070

I hope this helps

**Comment by lukaseder** [comment]
> As another example, the field containing the user password hash really shouldn't be loaded either.

That would be a great use-case for the invisible column feature:

- https://github.com/jOOQ/jOOQ/issues/14070

Where jOOQ would allow for querying the column, but it would never automatically project it.

**Comment by reubenfirmin** [comment]
The second solution could work; however, the kotlin data classes have non-null representations of these columns, so I can't omit columns if I loadInto classes (and thus, may as well just select asterisk). 

A good example of the use case would be a passwordHash column; maybe you want to compute the hash of the incoming password in code and then do the comparison in the db against what is stored, so you still need to be able to filter on the column, but don't want it to populate pojos.

Invisible columns does sound like it could work, though it'd need some metadata in the postgres ddl in my case that could mark them columns to be treated in this way.
