### ISSUE TITLE
Datetime precision isn't maintained by code generator for domain types

### ISSUE THREAD

**Issue by Player0X1** [jOOQ/jOOQ#15555]
### Your question

Hello everyone! 

I have statement of domain creation in my sql migration: 
`create domain instant_t AS timestamp(3);`
I used a precision of 3 for timestamp.
But when I do codegen I always get a result of LOCALDATETIME(0).

Use a config file with forcedtype and custom converter from localdatetime to instant (UTC without timezone):
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd  http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd">

    <jdbc>
        <driver>org.postgresql.Driver</driver>
        <url>@com.company.migrations.datasource@</url>
        <user>@com.company.migrations.user@</user>
        <password>@com.company.migrations.password@</password>
    </jdbc>

    <generator>
        <database>
            <name>org.jooq.meta.postgres.PostgresDatabase</name>

            <includes>.*</includes>

            <excludes>schema_version | __.*</excludes>
            <inputSchema>@com.company.migrations.schemaName@</inputSchema>
            <outputSchemaToDefault>true</outputSchemaToDefault>

            <forcedTypes>
                <forcedType>
                    <userType>java.time.Instant</userType>
                    <converter>com.company.converters.jooq.JooqInstantConverter</converter>
                    <types>timestamp|instant_t</types>
                </forcedType>
            </forcedTypes>
        </database>

        <generate>
            
            <javaTimeTypes>true</javaTimeTypes>
        </generate>
            </generator>
</configuration>

So the result of generation of Domain.java is :
```
 /**
     * The domain <code>instant_t</code>.
     */
    public static final Domain<Instant> INSTANT_T = Internal.createDomain(
          schema()
        , DSL.name("instant_t")
        , SQLDataType.LOCALDATETIME(0) // should be precision 3
        , new JooqInstantConverter()
    );

```
How I can set a precision or find any workaround for that?
Many thanks!

### jOOQ Version

org.jooq:jooq:3.18.6

### Database product and version

Postgres 13

### Java Version

openjdk 17

### OS Version

Windows 10

### JDBC driver name and version (include name if unofficial driver)

postgresql:42.4.1

**Comment by lukaseder** [comment]
Thanks a lot for your report.

The query that we're running to discover domain types is this one:

```sql
with recursive
  domains(domain_id, base_id, typbasetype, src) as (
    select
      d.oid,
      d.oid,
      d.typbasetype,
      case
        when c.oid is not null then array[pg_get_constraintdef(c.oid)]
      end
    from (
      pg_catalog.pg_type as d
        join pg_catalog.pg_namespace as alias_34093787
          on d.typnamespace = alias_34093787.oid
      )
      left outer join pg_catalog.pg_constraint as c
        on d.oid = c.contypid
    where (
      d.typtype = 'd'
      and alias_34093787.nspname in (
        'public'
      )
    )
    union all
    select
      domains.domain_id,
      d.oid,
      d.typbasetype,
      case
        when c.conbin is null then domains.src
        else array_append(
          domains.src,
          pg_get_constraintdef(c.oid)
        )
      end
    from domains
      join pg_catalog.pg_type as d
        on domains.typbasetype = d.oid
      left outer join pg_catalog.pg_constraint as c
        on d.oid = c.contypid
  )
select
  alias_34093787.nspname,
  d.typname,
  d.typnotnull,
  d.typdefault,
  b.typname,
  information_schema._pg_char_max_length(d.typbasetype, d.typtypmod) as character_maximum_length,
  information_schema._pg_numeric_precision(d.typbasetype, d.typtypmod) as numeric_precision,
  information_schema._pg_numeric_scale(d.typbasetype, d.typtypmod) as numeric_scale,
  domains.src
from (
  pg_catalog.pg_type as d
    join pg_catalog.pg_namespace as alias_34093787
      on d.typnamespace = alias_34093787.oid
  )
  join domains
    on (
      domains.typbasetype = 0
      and domains.domain_id = d.oid
    )
  join pg_catalog.pg_type as b
    on domains.base_id = b.oid
where (
  d.typtype = 'd'
  and alias_34093787.nspname in (
    'public'
  )
)
order by alias_34093787.nspname, d.typname
```

It appears that we should also be fetching `information_schema._pg_datetime_precision(d.typbasetype, d.typtypmod)` as we do for columns.

I'll fix this right away.

**Comment by lukaseder** [comment]
These dialects are also affected:

- Oracle
- SQL Server

These dialects get it right already:

- H2
- HSQLDB

This one doesn't support timestamp precision:

- Firebird

**Comment by Player0X1** [comment]
Thank you.
@lukaseder, can you give me an estimated release date, please? 

Current workaround as we use is replaces codegenerated Domains.java with SQLDataType.LOCALDATETIME(0) by correct one with SQLDataType.LOCALDATETIME(3). Yes it`s dirty hack)

**Comment by lukaseder** [comment]
As soon as I push this, it will be built in the next nightly builds available from here if you're licensed:
https://www.jooq.org/download/versions

Other than that, there are no release date promises.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.7 (https://github.com/jOOQ/jOOQ/issues/15560)
- 3.17.16 (https://github.com/jOOQ/jOOQ/issues/15561)
- 3.16.22 (https://github.com/jOOQ/jOOQ/issues/15562)

**Comment by lukaseder** [comment]
I've found a related issue that has been discovered based on the tests from this issue.

The domain doesn't have a `CHECK` constraint (unlike others, from our integration tests), and thus isn't being generated in some dialects, e.g. HSQLDB.

I've created a separate issue for this:

- https://github.com/jOOQ/jOOQ/issues/15673
