### ISSUE TITLE
Slow IDE response?

### ISSUE THREAD

**Issue by oclay1st** [jOOQ/jOOQ#15552]
### Your question

Is there any technical reason for the amount of classes/interfaces ending from 1 to 22? and also why ending in 22? . Example Row1,Row2....,the Records class with a lot of parameters, etc. Sometimes my IDE spends tens of seconds searching a method/class when using JOOQ.

Lukas, nothing to criticize. I really appreciate your work. Thanks

### jOOQ Version

3.18.4

### Database product and version

PotsgresSQL15

**Comment by lukaseder** [comment]
> Is there any technical reason for the amount of classes/interfaces ending from 1 to 22?

Java doesn't have higher kinded generics (hardly any language does), so we need to pretend it does by duplicating types. Look at the JDK's own `Function`, `BiFunction` types, etc.

> and also why ending in 22?

Why not? (Scala used to have this limit)

> Sometimes my IDE spends tens of seconds searching a method/class when using JOOQ.

Report a bug to the IDE. I'm assuming this is IntelliJ? From my experience, Eclipse fares much better in this particular aspect. There have been tons of issues reported to IntelliJ, specifically by kotlin users. The more bugs reported, the better the IDE gets.

In my experience, this isn't about the 22-arity of types, but about the simple fact that the `DSL` class has so many methods (yet still far from the JVM's limit).

I hope this helps

**Comment by oclay1st** [comment]
@lukaseder Thanks!

**Comment by jurajmlich-a** [comment]
Most likely not but if you're using Kotlin and K2 compilation then that explains the issue. If you K2 in IntelliJ settings, it'll work much faster. There's a bug in YouTrack. Putting here it for reference for other people who have also spent trying to figure out why IntelliJ is driving me instane working with JOOQ :) 

https://youtrack.jetbrains.com/issue/KTIJ-32452/K2-Code-completion-is-too-slow-for-jOOQ-type

**Comment by JurajMlich** [comment]
Most likely not but if you're using Kotlin and K2 compilation then that explains the issue. If you K2 in IntelliJ settings, it'll work much faster. There's a bug in YouTrack. Putting here it for reference for other people who have also spent trying to figure out why IntelliJ is driving me instane working with JOOQ :) 

https://youtrack.jetbrains.com/issue/KTIJ-32452/K2-Code-completion-is-too-slow-for-jOOQ-type
