### ISSUE TITLE
Is it thread safe to create static variables that represent fields or tables?

### ISSUE THREAD

**Issue by maurociancio** [jOOQ/jOOQ#15618]
### Your question

Like this:

```
class A {
  static final Field<Long> myField = SOME_TABLE.ID.as("id");
  static final MY_TABLE myTable = SOME_TABLE.as("someTable");
  void methodThatIsInvokedConcurrently() {
    // create a query that uses myField or myTable in the select or in the where
  }
}
```

Is it safe? When should I be worried about doing this?
Thanks, I couldnt find it the docs.

### jOOQ Version

3.18.3

### Database product and version

mysql 5.7+

### Java Version

jdk 17

**Comment by lukaseder** [comment]
There's nothing specific to your usage. The generated code has been designed to be mostly static-initialisable (due to its nature of using so many static fields to benefit static imports). It doesn't really matter who initialises it first.

There are some edge cases where race conditions may arise by initialising different parts of the generated code in parallel.

**Comment by maurociancio** [comment]
Hey, thanks!

If I understand you correctly, what you're saying it's JOOQ already does what i'm doing... the generated code from the tables looks like this:

```
class Tables {
  static final Table TABLE = new Table(...)
}
class Table {
  static final Field ID = new Field(..)
}
```

So when you make a query and use them, you are already using a shared instante. I am right?

Thanks again!

**Comment by lukaseder** [comment]
Well, jOOQ's generated code is what it is. Perhaps, you have a *specific* question?

**Comment by maurociancio** [comment]
Im sorry, here I go again. In the following code:

```
class A {
  static final Field<Long> myField = SOME_TABLE.ID.as("id");
  static final MY_TABLE myTable = SOME_TABLE.as("someTable");
  void methodThatIsInvokedConcurrently() {
    // create a query that uses myField or myTable in the select or in the where
  }
}
```

The method `methodThatIsInvokedConcurrently` is going to be invoked from in parallel from different threads. Should I be worried that I'm using myField or myTable that are static (so, shared amongst all threads)?

Thanks!

**Comment by lukaseder** [comment]
Well, a class is initialised by the class loader only on a single thread. Until `A.<clinit>` finishes, all other threads block on any access to `A`.

But this isn't jOOQ specific. You probably have other static members. What makes you worry about the jOOQ ones?

**Comment by maurociancio** [comment]
Sorry. My question is about if fields or table are mutable. If fields or table (jooq classes) are mutable and shared amongst threads, races conditions can happen.

Im worried about that, not about the initialization order.

**Comment by lukaseder** [comment]
Well, I'm glad I insisted, because that wasn't what you asked, originally :)

Generated code is immutable. Everyone is using jOOQ's generated code this way.
