### ISSUE TITLE
Feedback about manual section "inlined-parameters"

### ISSUE THREAD

**Issue by lhauspie-adeo** [jOOQ/jOOQ#15657]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-building/bind-values/inlined-parameters/

### Feedback

Hello, and thanks for your work. Your tool seems to be powerful.

It could be nice to explain how and when it's useful to inline.
In which cases we have to inline and in which cases we have to not inline.

Thanks in advance 🙏

**Comment by lukaseder** [comment]
See here:
https://blog.jooq.org/when-to-use-bind-values-and-when-to-use-inline-values-in-sql/

I'll add the link to the manual page
