### ISSUE TITLE
read jooq-settings.xml got:Cannot find the declaration of element 'Settings'

### ISSUE THREAD

**Issue by dekingorg** [jOOQ/jOOQ#15692]
### Your question

Hello, I am a JAXB noob. I encountered this error when trying to load a  jooq-settings.xml configuration file. Did I make any mistakes in the jooq-settings.xml ? Also, do you have any examples of a jooq-settings.xml?
```
import static org.jooq.impl.DSL.field;
import static org.jooq.impl.DSL.table; 
import org.jooq.Query;   
import org.jooq.impl.DSL;

public class JooqTest {
	public static void main(String[] args) { 

		Query query = DSL.select(field("username")).from(table("member")); 
	}
}
```
jooq-settings.xml:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Settings xmlns="http://www.jooq.org/xsd/jooq-runtime-3.8.0.xsd"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.jooq.org/xsd/jooq-runtime-3.8.0.xsd jooq-runtime-3.8.0.xsd">
	<ParamType>INLINED</ParamType> 
</Settings>
```
error:
```
org.xml.sax.SAXParseException; lineNumber: 5; columnNumber: 42; cvc-elt.1.a: Cannot find the declaration of element 'Settings '
```

### jOOQ Version

3.15.12

### Database product and version

Mysql 8.0.27

### Java Version

openjdk version "17.0.1" 2021-10-19

### OS Version

Microsoft Windows [Version 10.0.16299.194]

**Comment by lukaseder** [comment]
Please take a look at the XSD:

- https://www.jooq.org/xsd/jooq-runtime-3.8.0.xsd
- https://www.jooq.org/xsd (for more recent versions)

There are no `PascalCase` element declarations, only `camelCase` ones. `PascalCase` names are reserved for types, but XSD types aren't visible in your XML documents.
