### ISSUE TITLE
Feedback about manual section "the-manual"

### ISSUE THREAD

**Issue by mjawadbutt** [jOOQ/jOOQ#15703]
### The documentation URL

https://www.jooq.org/doc/3.18/manual/getting-started/the-manual/

### Feedback

The product is extermely well design and powerful but the manual is VERY poorly designed, confusing, written in mimalist style and lacks good examples and corresponding explanations. PLEASE improve the docs it will help a lot with sales also!!

**Comment by lukaseder** [comment]
Thank you so much for your feedback.

The feedback was written in a minimalist style and lacks good examples of actionable suggestions. ;)

Also, we get a lot of feedback that our manual is top notch, so it's unlikely it's *fundamentally* wrong.

If you have any *specific* feedback, about a *specific section*, I'll be happy to hear it.
