### ISSUE TITLE
Add support for REGEXP_REPLACE()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1571]
A lot of RDBMS support regex replacing content in strings. We should offer a standardised API for this functionality in `DSL`.

Dialects whose support will be included:

**Replace all matches by default**

- [x] Db2: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0061496.html
- [x] Informix: https://www.ibm.com/support/knowledgecenter/SSGU8G_12.1.0/com.ibm.dbext.doc/ids_dbxt_559.htm
- [x] MySQL: https://dev.mysql.com/doc/refman/8.0/en/regexp.html#function_regexp-replace
- [x] Oracle: https://docs.oracle.com/en/database/oracle/oracle-database/18/sqlrf/REGEXP_REPLACE.html#GUID-EA80A33C-441A-4692-A959-273B5A224490
- [x] Teradata: https://docs.teradata.com/reader/kmuOwjp1zEYg98JsB8fu_A/aohu2GV5DgPH0R5jQKr2HQ
- [x] Vertica: https://www.vertica.com/docs/9.2.x/HTML/Content/Authoring/SQLReferenceManual/Functions/RegularExpressions/REGEXP_REPLACE.htm

**Replace all matches, no support for replace first match, see #10151**

- [x] H2: http://h2database.com/html/functions.html#regexp_replace
- [x] HSQLDB: http://www.hsqldb.org/doc/2.0/guide/builtinfunctions-chapt.html
- [x] MariaDB: https://mariadb.com/kb/en/regexp_replace/

**Replace first match by default**

- [x] CockroachDB: https://www.cockroachlabs.com/docs/stable/functions-and-operators.html
- [x] MemSQL: https://docs.memsql.com/v7.0/reference/sql-reference/regular-expression-functions/regexp_replace/
- [x] PostgreSQL: https://www.postgresql.org/docs/current/functions-matching.html

Standard SQL doesn't have such a function. PostgreSQL's behaviour might be more consistent with other standard regex functions, which tend to act on the first match by default, such as e.g. `SUBSTRING_REGEX`.

Perhaps, we could introduce two synthetic functions:

- `REGEXP_REPLACE_ALL()` and `REGEXP_REPLACE_FIRST()` to offer both behaviours explicitly, ignoring the various specialised flags available in Db2, MySQL, Oracle.

The parser would default to parsing `REGEXP_REPLACE` as `REGEXP_REPLACE_ALL`, except when using PostgreSQL as the input dialect, in case of which the default is `REGEXP_REPLACE_FIRST` (in the absence of a `'g'` pattern.

----
See also #620

**Comment by lukaseder** [comment]
Other dialects than the ones listed above may support regular expressions, and will get their support separately, on demand.

**Comment by oneiros-de** [comment]
This seems to be missing from the manual.

**Comment by lukaseder** [comment]
Thanks for the pointer. Yes, a few functions are missing from the manual. There's a task somewhere to discover them automatically (because otherwise, this keeps happening).

Will document this one right away, though.
