### ISSUE TITLE
Generate comments also on other PostgreSQL object types

### ISSUE THREAD

**Issue by robstoll** [jOOQ/jOOQ#15723]
### Use case

it would be nice if the comments we write functions would be reflected in code documentation, i.e. in javadoc/KDoc/scaladoc

### Possible solution

Adjust the generator to include comments

### jOOQ Version

3.18.5

### Database product and version

PostgreSQL 14.5

### Java Version

17

### OS Version

linux

### JDBC driver name and version (include name if unofficial driver)

don't know but shouldn't matter

**Comment by robstoll** [comment]
thanks for the quick reply. Shall I report a bug then? I would not have created this feature request if it already worked :wink: 
Currently all I get on Routines.foo is:
```
 /**
     * Call
     * <code>my_schema.foo</code>
     */
```

**Comment by lukaseder** [comment]
I overlooked your detail *"and especially functions"*. We simply don't look into function comments yet.

**Comment by lukaseder** [comment]
Note, this isn't just about Javadoc. We also generate comments throughout our meta model, so doing this right will take a bit more time, and investigation about which RDBMS even support comments on functions.

**Comment by robstoll** [comment]
Also my bad, did not realise it already works for columns and tables

**Comment by lukaseder** [comment]
Looking into this now. No need to:

- Add support for the DDL statement
- Check out other dialects

I can just implement this for PostgreSQL only, for now. Will look into other types of comments as well, including:

- `DOMAIN`
- `SCHEMA`
- `SEQUENCE`
- `TRIGGER`
- `TYPE`

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.20.0
