### ISSUE TITLE
Improve on DuckDB support

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15732]
jOOQ 3.19 has introduced experimental DuckDB support:

- https://github.com/jOOQ/jOOQ/issues/12052

Many bugs and limitations have been discovered, including a few show stoppers for jOOQ's CI/CD pipeline (e.g. segmentation faults, which brought down the entire Jenkins process, not just individual tests). As such, the development was put on hold until the DuckDB jdbc driver stabilises.

This issue will track further developments in jOOQ 3.20 (and possibly later).

- [x] `MULTISET` support
  - [x] `MULTISET` via `NATIVE` support with `ARRAY(SELECT ROW(...))`
  - [x] `MULTISET_AGG` via `NATIVE` support with `ARRAY_AGG(ROW(...))`
- [x] Arrays:
  - [x] `ARRAY[...]` literals
  - [x] Array bind values: `CAST(CAST('["a", "b"]' AS JSON) AS TEXT ARRAY)` (The JDBC driver doesn't support array bind values yet)
  - [x] Array code generation support
  - [x] `ARRAY_AGG()` support
  - [x] Array function support
    - [x] `ARRAY_CONCAT()`
    - [x] `ARRAY_APPEND()`
    - [x] `ARRAY_PREPEND()`
    - [x] `ARRAY_OVERLAP()` (via `ARRAY_INTERSECT()`)
    - [x] `ARRAY_REMOVE()` (via `ARRAY_FILTER()`)
    - [x] `ARRAY_REPLACE()` (via `ARRAY_TRANSFORM()`)
  - [x] Replace standard SQL `TYPE ARRAY` notation by `TYPE[]` since `TYPE ARRAY ARRAY` isn't supported, but `TYPE[][]` is
- [x] Code generation
  - [x] `CHECK` constraints
anyway
- [x] Datetime arithmetic
- [x] Quantified `LIKE`
- [x] `LIKE` with non-string types
- [x] Support the `JSON` data type
- [x] Sequences
  - [x] `DSL.sequence()` literal
  - [x] `currval()` support
  - [x] `nextval()` support
  - [x] `nextvals()` support
  - [x] Code generation support (the query is currently wrong)
- [x] Identities
  - [x] Code generation support
- [x] `STRING_AGG` support
- [x] `COUNT(DISTINCT ..)` support 
  - [x] `Table` overloads
  - [x] Multi-column overload should count distinct tuples, i.e. `COUNT(DISTINCT (a, b))` instead of `COUNT(DISTINCT a, b)`
- [x] `UPDATE .. SET RVE` cannot be emulated with `UPDATE .. FROM`, as the `UPDATE` target table isn't in the `FROM` clause scope.
- [x] `MetaCatalog` support
- [x] DDL support
  - [x] `CHECK` constraint support
  - [x] `ALTER TABLE .. ADD <tableElement>` syntax
  - [x] `CREATE TYPE`
  - [x] Auto create a sequence to emulate an identity column
- [x] Data type support
  - [x] Support for reading UDTs
  - [x] ~Support generating nested UDTs~ This is too hard to do, and thus not worth it. Let's wait until they fix https://github.com/duckdb/duckdb/discussions/8832
  - [x] Support writing binary data with `PreparedStatements.setBytes()` and reading it with `ResultSet.getBlob()`
  - [x] Fix all sorts of string types, like `CLOB`, `LONGVARCHAR`, etc. to be mapped to `STRING`
- [x] DML support
  - [x] `UPDATE .. FROM` support
  - [x] `DELETE .. USING` support
- [x] Better catalog support
- [x] Reverse engineer error messages to detect `DataAccessException::sqlStateClass`
- [x] Correctly interpret always case insensitive identifiers
- [x] Spatial support: https://github.com/jOOQ/jOOQ/issues/16830
- [x] Native `ROW` and `Struct` support
  - [x] Related limitation: https://github.com/jOOQ/jOOQ/issues/16839

Other tasks:

- [x] Remove experimental status from dialect. ~0.10.0 seems quite stable now.~ (so many regressions again after upgrading from 0.10.1 to 0.10.2)
- [x] Upgrade to 0.10.1
- [x] Upgrade to 0.10.2
- [x] Upgrade to 1.0.0: https://github.com/jOOQ/jOOQ/issues/16836

New bugs discovered:

- https://github.com/duckdb/duckdb/issues/10695
- https://github.com/duckdb/duckdb/issues/11274
- https://github.com/duckdb/duckdb/issues/11281
- https://github.com/duckdb/duckdb/issues/11283
- https://github.com/duckdb/duckdb/issues/11284
- https://github.com/duckdb/duckdb/issues/11288
- https://github.com/duckdb/duckdb/issues/11293
- https://github.com/duckdb/duckdb/issues/11294
- https://github.com/duckdb/duckdb-java/issues/13
- https://github.com/duckdb/duckdb/issues/11381
- https://github.com/duckdb/duckdb/issues/11780
- https://github.com/duckdb/duckdb/issues/11781
- https://github.com/duckdb/duckdb-java/issues/36
- https://github.com/duckdb/duckdb-java/issues/37

Documentation issues:

- https://github.com/duckdb/duckdb-web/issues/2559
- https://github.com/duckdb/duckdb-web/issues/2611

**Comment by lukaseder** [comment]
See work implemented in:

- https://github.com/jOOQ/jOOQ/issues/16287

**Comment by lukaseder** [comment]
There's still much improvement work to do. I'll reopen to track this further in 3.20

**Comment by lukaseder** [comment]
The `SQLDialect.DUCKDB` won't be experimental anymore in 3.20.

**Comment by lukaseder** [comment]
@humaidkidwai I'll try eventually, but I'm not too hopeful:
https://github.com/jOOQ/jOOQ/issues/16287#issuecomment-2137250656

**Comment by humaidkidwai** [comment]
DuckDB dialect [closely follows](https://duckdb.org/docs/sql/postgresql_compatibility.html) PostgreSQL. Has anyone reported using the PostgreSQL dialect as a workaround in this forum? 

For eg: Spatial predicates, as per [jOOQ documentation](https://www.jooq.org/doc/latest/manual/sql-building/conditional-expressions/spatial-predicates/st-contains-predicate/), says that DuckDB is Unsupported. I was wondering if there is anyone from the community who has just used the Postgres dialect (stContains(geometry1, geometry2) in this case) and worked with DuckDB

**Comment by lukaseder** [comment]
To be clear about what I meant: DuckDB has had a history of introducing breaking changes, which make integration testing impossible. 0.10.3 has introduced such a regression. I haven't tried 1.0 yet. 

> DuckDB dialect [closely follows](https://duckdb.org/docs/sql/postgresql_compatibility.html) PostgreSQL. Has anyone reported using the PostgreSQL dialect as a workaround in this forum?

I wouldn't do that if I were you. Use the `SQLDialect.DUCKDB` dialect. There's no reason to prefer another dialect. That claim of closely following PostgreSQL is just a high level claim. Our integration tests show that when looking at details, the dialects are quite different.

> For eg: Spatial predicates, as per [jOOQ documentation](https://www.jooq.org/doc/latest/manual/sql-building/conditional-expressions/spatial-predicates/st-contains-predicate/), says that DuckDB is Unsupported. I was wondering if there is anyone from the community who has just used the Postgres dialect (stContains(geometry1, geometry2) in this case) and worked with DuckDB

When I first looked at DuckDB's spatial support, it wasn't as sophisticated as this resource claims now:
https://duckdb.org/docs/extensions/spatial.html

I'll have another look, soon, ideally via a separate issue:

- https://github.com/jOOQ/jOOQ/issues/16830

**Comment by lukaseder** [comment]
Yeah, we can definitely extend our spatial function support to DuckDB for jOOQ 3.20.

**Comment by lukaseder** [comment]
For the record, here's the regression in the DuckDB JDBC driver that prevented 0.10.3 and 1.0.0 upgrades so far:

- https://github.com/duckdb/duckdb-java/issues/36

I think we can work around it now.

**Comment by lukaseder** [comment]
DuckDB 1.0.0 support will ship with jOOQ 3.20:

- https://github.com/jOOQ/jOOQ/issues/16836

**Comment by humaidkidwai** [comment]
> DuckDB 1.0.0 support will ship with jOOQ 3.20:

Great news 🎉

**Comment by lukaseder** [comment]
Regarding spatial support, the only limitation I've encountered so far is that `WKB_BLOB` types can't be read automatically via JDBC yet:

- https://github.com/duckdb/duckdb-java/issues/37

I'll wait and see how this is being addressed by the JDBC driver team. Maybe, we'll work around this limitation. Otherwise, manual casts to `BLOB` are possible too, of course.

**Comment by humaidkidwai** [comment]
How about ST_GeomFromWKB?

I feel like that would be used more often usually

**Comment by lukaseder** [comment]
> How about ST_GeomFromWKB?

It works with `varbinary` bind values:

```
prepareStatement         : select st_geomfromwkb(cast(? as varbinary))
Fetched result           : +--------------+                           
                         : |st_geomfromwkb|                           
                         : +--------------+                           
                         : |POINT (1 2)   |                           
                         : +--------------+                           
Fetched row(s)           : 1                                          
```

But strangely doesn't work with binary literals:

```sql
select st_geomfromwkb(cast(X'0101000000000000000000F03F0000000000000040' as varbinary));
```

The error being:

> SQL Error: Not implemented Error: WKB Reader: Geometry type 79 not supported

**Comment by lukaseder** [comment]
Hmm, OK, perhaps our binary literals are wrong. This works:

```sql
select st_geomfromwkb('\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF0\x3F\x00\x00\x00\x00\x00\x00\x00\x40'::blob);
```
