### ISSUE TITLE
With settings.withParamType(ParamType.INLINED), the query params are not inlined

### ISSUE THREAD

**Issue by obourgain** [jOOQ/jOOQ#15753]
### Expected behavior

Not sure if this is a bug or a misunderstanding on my side.
If I set paramType to ParamType.INLINED, I would expect the query to be rendered with parameters inlined.

### Actual behavior

Jooq uses bind parameters.

### Steps to reproduce the problem

* set settings.withParamType(ParamType.INLINED)
* execute a query and look at the query actually executed
** with database tools or a debugger
* the query uses bind parameters

MCVE: [https://github.com/obourgain/jOOQ-mcve/tree/force_inline_doesnt_work](https://github.com/obourgain/jOOQ-mcve/tree/force_inline_doesnt_work)

### jOOQ Version

3.18.7

### Database product and version

PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

**Comment by lukaseder** [comment]
Thanks for your message.

I take that using `pg_stat_statements` should be equivalent to `pg_stat_activity`, and removes the need for breakpoints and open cursors, or even using Java. Run this in your SQL editor (e.g. Dbeaver):

```sql
select cast('{}' as jsonb);
select query from pg_stat_statements where query like '%jsonb%';
```

You'll get:

```
select cast($1 as jsonb)
```

This isn't jOOQ specific. If you run:

```java
ctx.settings().withParamType(ParamType.INLINED);
System.out.println(ctx.select(val(JSONB.jsonb("{}"))).getSQL());
```

You'll get what you're expecting (check also the debug logs):

```sql
select cast('{}' as jsonb)
```

Note that jOOQ always runs a JDBC `PreparedStatement`, unless you override this with the `Settings.statementType` value, see:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-statement-type/
