### ISSUE TITLE
MiniJAXB::marshal(XMLAppendable, OutputStream) does not flush decorating writer

### ISSUE THREAD

**Issue by daniel-huss** [jOOQ/jOOQ#15767]
### Expected behavior

I was using this code to clone a configuration:

```kotlin
/**
 * @return A deep copy of this configuration.
 */
fun Configuration.copy(): Configuration {
    val outputStream = ByteArrayOutputStream(1024)
    MiniJAXB.marshal(this, outputStream)
    outputStream.flush()
    return MiniJAXB.unmarshal(ByteArrayInputStream(outputStream.toByteArray()), Configuration::class.java)
}
```

### Actual behavior

This throws an exception:  "Error while reading xml: begin -1, end -1, length 0 ->"

Looking at the code, I saw that the marhsal function creates a decorating `OutputStreamWriter`:

```java
    public static void marshal(XMLAppendable object, OutputStream out) {
        marshal(object, new OutputStreamWriter(out));
    }
````

But the `Writer` overload of `marshal` never flushes the writer it receives. I think in this case flushing (not closing) would be the responsibility of the code that created the decorating OutputStreamWriter.

### Steps to reproduce the problem

-

### jOOQ Version

3.18.7

### Database product and version

none

**Comment by lukaseder** [comment]
I double-checked if there are any other internal `Writer` instances worth flushing. It appears that the other ones have all been flushed already, at the latest since:

- https://github.com/jOOQ/jOOQ/issues/13023
