### ISSUE TITLE
`UpdatableRecord::copy()` sets all the record fields as changed, is this the desired behaviour?

### ISSUE THREAD

**Issue by apontini** [jOOQ/jOOQ#15775]
### Your question

Hey!
While working with jOOQ 3.15.4 (open source edition) I found the following behaviour:
I have a table (say, `MyTable`) and its generated record object (`MyTableRecord`) with 3 columns: `ColA`, `ColB` (which is set as `not null`) and `ColC`.

This is the code snipped that I was working on:
```java
MyTableRecord firstRecord = new MyTableRecord();
firstRecord.setColA("testA");

MyTableRecord secondRecord = firstRecord.copy();
firstRecord.setColC("testC1");
secondRecord.setColC("testC2");

context.batchInsert(List.of(firstRecord, secondRecord)).execute();
```

I noticed that when `secondRecord` is inserted, `ColB` is set as `null`, making the query fail. By investigating further, I noticed that the `copy()` method is actually going through all of `firstRecord`'s fields and calling `set()` on all of `secondRecord`'s fields, thus adding all of those to the `changed` bitmap.
Is this the intended behaviour?
I was expecting the record resulting from `copy()` to be the exact replica of the first record, thus my confusion here.

### jOOQ Version

3.15.4

### Database product and version

PostgreSQL 14.9

**Comment by lukaseder** [comment]
Yes, see the Javadoc:
https://www.jooq.org/javadoc/3.18.x/org.jooq/org/jooq/UpdatableRecord.html#copy()
