### ISSUE TITLE
Unable to rollback the DB statements when using transactionCoroutine with DataSource connection

### ISSUE THREAD

**Issue by giottcww** [jOOQ/jOOQ#15777]
### Expected behavior

Our project is setup with Spring + JOOQ + Kotlin Coroutine + Hikari Data Source, and we tried the below [example](https://www.jooq.org/doc/latest/manual/sql-building/kotlin-sql-building/kotlin-coroutines#NE40A7) provided from official document.

```kotlin
fun mcveTest() {
  runBlocking {
      ctx.transactionCoroutine { c ->
          c.dsl()
              .insertInto(tableType)
              .set(record)
              .returning()
              .awaitFirst()
          
          throw RuntimeException()
      }  // <---- Should be rollback over here
  }
}
``` 

### Actual behavior

However, insert/update statements are committed immediately after awaitFirst() execution, transaction is unable to rollback even an exception is being throw afterward.

### Steps to reproduce the problem

Compared the connections populated during "begin of tx" and "execution". Seems it is unable to reuse the same connection and acquire a new connection.

### Running with transactionCoroutine
1. Begin Tx (Running in main thread) -> PgConnection@**13844**
<img width="1289" alt="image" src="https://github.com/jOOQ/jOOQ/assets/100355958/2bcdddda-f9f7-4ec2-bfed-b1884b05993d">

2. Execute Statement (Running in worker thread) -> PgConnection@**14455**
<img width="1308" alt="image" src="https://github.com/jOOQ/jOOQ/assets/100355958/49b83882-eb1c-4cd3-b2e7-3fc798f44533">

### Running with transaction
1. Begin Tx (Running in main thread) -> PgConnection@**13705**
<img width="1310" alt="image" src="https://github.com/jOOQ/jOOQ/assets/100355958/5f279692-55f7-4bf2-9513-50ad8a6448ac">

2. Execute Statement (Running in main thread) -> PgConnection@**13705**
<img width="1306" alt="image" src="https://github.com/jOOQ/jOOQ/assets/100355958/b02c6442-6773-4c48-b434-1afe2b7afce2">

MCVE: https://github.com/giottcww/jOOQ-mcve

### jOOQ Version

3.17.8

### Database product and version

PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1)

### Java Version

openjdk version 17

**Comment by giottcww** [comment]
Found https://github.com/jOOQ/jOOQ/issues/10850 this issue after completing the MCVE, no quite sure if it is related.

Tested with R2DBC connection pool, it work well. But If I stick with my data source in blocking way, wanna know is it thread safe to use DefaultTransactionProvider?

Or, I shouldn't do it in this way?

**Comment by lukaseder** [comment]
You're using a very outdated version. The latest 3.17 version is 3.17.16, currently, and there's also 3.18.7. Please check first if the issue persists after an upgrade (there had been tons of bugfixes).

**Comment by giottcww** [comment]
Yes, the project has been run for quite a long time, should be time to update the dependencies.

I have reproduced the issue again in the mcve project, using the latest version 3.18.7, got the same result.
<img width="1219" alt="image" src="https://github.com/jOOQ/jOOQ/assets/100355958/a2359971-b5c1-4e50-b8e0-cbb436a4bd23">
<img width="1263" alt="image" src="https://github.com/jOOQ/jOOQ/assets/100355958/79370834-9aa9-4d88-b1b0-4e95c5a919e4">

Seems in CoroutineExtensions line 23 & 24, the transactionPublisher begin the tx in current thread while mono (TransactionalPublishable parameter) run the tx SQL in worker thread.

transactionPublisher(mono) 
  -> BlockingTransactionSubscription
    -> ctx.transactionResult 
       -> txProvider.begin
    -> transactional.run   // the mono is being published to worker thread here

**Comment by lukaseder** [comment]
Thanks a lot for your confirmation.

Since you've already worked with our MCVE template, can you share it somewhere so it will be simpler to reproduce? I can try from your pasted code, but from experience, the actual MCVE really helps avoiding any pitfalls that should be read between the lines...

**Comment by giottcww** [comment]
opps, push to wrong branch, can you see it right now?

**Comment by lukaseder** [comment]
Ah, my bad. I didn't see that you've added the link to your edited issue description. Will check it out now, thanks!

**Comment by lukaseder** [comment]
Ah yes, I get it. This a similar issue as:

- https://github.com/jOOQ/jOOQ/issues/15702

Except this time, you're using the blocking implementation, whereas that other issue was using the non-blocking implementation.

Although, with the coroutine wrappers, things are a bit different than with actual publishers. While in #15702, one could argue that throwing the exception directly from a `TransactionalPublishable` is wrong from a user code point of view, it makes perfect sense from within a coroutine.

I'll check what needs to be done.

**Comment by lukaseder** [comment]
Ah nope, that's not it. It's a Spring related problem. If you turn on debug logging, you'll see that jOOQ correctly attempts to roll back your transaction, but your connection is in auto-commit mode, (even if it shouldn't be):

```
16:44:17,990 DEBUG [pport.AbstractPlatformTransactionManager#getTransaction  :370 ] - Creating new transaction with name [null]: PROPAGATION_NESTED,ISOLATION_DEFAULT
16:44:17,997 DEBUG [.datasource.DataSourceTransactionManager#doBegin         :267 ] - Acquired Connection [HikariProxyConnection@707834059 wrapping org.postgresql.jdbc.PgConnection@70485aa] for JDBC transaction
16:44:18,000 DEBUG [.datasource.DataSourceTransactionManager#doBegin         :285 ] - Switching JDBC Connection [HikariProxyConnection@707834059 wrapping org.postgresql.jdbc.PgConnection@70485aa] to manual commit
16:44:18,000 DEBUG [org.postgresql.jdbc.PgConnection        #setAutoCommit   :948 ] -   setAutoCommit = false
16:44:18,005 DEBUG [reactor.util.Loggers$Slf4JLogger        #debug           :244 ] - Using Slf4j logging framework
16:44:21,298  INFO [org.jooq.tools.JooqLogger               #lambda$info$5   :355 ] - 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.18.7 (Build date: 2023-10-10T12:53:05Z)
                                      
16:44:21,299  INFO [org.jooq.tools.JooqLogger               #lambda$info$5   :355 ] - 

jOOQ tip of the day: Whenever jOOQ doesn't support a native SQL feature, use plain SQL templating: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

16:44:21,313 DEBUG [org.jooq.tools.JooqLogger               #lambda$debug$3  :278 ] - Executing query          : insert into "mcve"."test" ("cd") values (?)
16:44:21,314 DEBUG [org.jooq.tools.JooqLogger               #lambda$debug$3  :278 ] - -> with bind values      : insert into "mcve"."test" ("cd") values (43)
16:44:21,317 DEBUG [ramework.jdbc.datasource.DataSourceUtils#doGetConnection :116 ] - Fetching JDBC Connection from DataSource
16:44:21,320  INFO [org.jooq.tools.JooqLogger               #lambda$info$5   :355 ] - Version                  : Database version is supported by dialect POSTGRES: 16.0 (Debian 16.0-1.pgdg120+1)
16:44:21,328 DEBUG [org.jooq.tools.JooqLogger               #lambda$debug$3  :278 ] - Affected row(s)          : 1
16:44:32,556 DEBUG [pport.AbstractPlatformTransactionManager#processRollback :833 ] - Initiating transaction rollback
16:44:32,557 DEBUG [.datasource.DataSourceTransactionManager#doRollback      :345 ] - Rolling back JDBC transaction on Connection [HikariProxyConnection@707834059 wrapping org.postgresql.jdbc.PgConnection@70485aa]
16:44:32,558 DEBUG [org.postgresql.jdbc.PgConnection        #rollback        :1011] - Rollback requested but no transaction in progress
16:44:32,559 DEBUG [org.postgresql.jdbc.PgConnection        #setAutoCommit   :948 ] -   setAutoCommit = true
16:44:32,560 DEBUG [.datasource.DataSourceTransactionManager#pAfterCompletion:389 ] - Releasing JDBC Connection [HikariProxyConnection@707834059 wrapping org.postgresql.jdbc.PgConnection@70485aa] after transaction
```

**Comment by lukaseder** [comment]
Ah yes, of course! If you add `c.connectionProvider().acquire()` to your lambda, you'll see you'll get Spring's auto configured `TransactionAwareDataSourceProxy`, which is a thread bound implementation of a `DataSource`. You cannot use that with coroutines, which remove thread-boundedness.

You have to decide whether you want to use Spring only for transactions, or jOOQ only. Mixing the two won't work well.

**Comment by lukaseder** [comment]
You'll find relevant discussions here:

- https://github.com/spring-projects/spring-boot/issues/24049
- https://github.com/spring-projects/spring-boot/issues/30760

I think that Spring Boot should improve their auto configuration somehow, but I'm not quite sure how, or if it's possible.

**Comment by giottcww** [comment]
Thanks for your quick response, let me take some time to have look on it.

**Comment by lukaseder** [comment]
Let me check this once more. People run into this frequently, and Spring Boot hasn't improved this situation in a while.

We could perhaps implement some different logic in `DefaultDSLContext::transactionResult0` in order to remove thread boundedness from the transactional logic, working around Spring's configuration from our side.

**Comment by lukaseder** [comment]
In any case, removing Spring's auto configuration from jOOQ is certainly the simplest, and most pragmatic way forward here. Just inject the HikariCP directly to jOOQ and you're set.

**Comment by giottcww** [comment]
Thanks for clarification, we decided to fallback to R2DBC connection pool for better integrity.

I was through, with `transactionCoroutine`, the thread schedule / thread pool should be controlled by my coroutine context. If I managed the execution of SQL in the same context, even I switch to use a thread-bound JDBC data source, it should be executed on the same thread. I am wrong, stay with `transactionCoroutine` also mean, the child context / scheduler can be switched, that should enable the full power of event loop.


I don’t think Spring will do anything with `TransactionAwareDataSourceProxy:: setReobtainTransactionalConnections`, it inherit the `DataSource`, it is part of JDBC world (assume thread-bound). If we would like to mix the `@Transactional` with `transactionPublisher`, as per Spring said from [here](https://spring.io/blog/2019/05/16/reactive-transactions-with-spring#how-imperative-transaction-management-works) and [here](https://docs.spring.io/spring-data/r2dbc/docs/1.1.0.RELEASE/api/org/springframework/data/r2dbc/connectionfactory/R2dbcTransactionManager.html),

> Reactor Context is to reactive programming what ThreadLocal is to imperative programming: Contexts allow binding contextual data to a particular execution. For reactive programming, this is a Subscription. Reactor’s Context lets Spring bind the transaction state, along with all resources and synchronizations, to a particular Subscription.

> Note: The ConnectionFactory that this transaction manager operates on needs to return independent Connections. The Connections may come from a pool (the typical case), but the ConnectionFactory must not return scoped scoped Connections or the like. This transaction manager will associate Connection with context-bound transactions itself, according to the specified propagation behavior. It assumes that a separate, independent Connection can be obtained even during an ongoing transaction.

- They manage the tx state `ReactiveTransaction` in the context of Subscription
- Connections are independent to the tx state

**Comment by lukaseder** [comment]
Thanks for following up.

I've created an issue to at least log a message when we recognise a configuration and API usage that is unlikely to work as expected:

- https://github.com/jOOQ/jOOQ/issues/15787

Giving this additional thought, I'm not convinced we can fix this on our end.
