### ISSUE TITLE
`isKotlinNotNullPojoAttributes` still generates nullable for primary key 

### ISSUE THREAD

**Issue by shiqicao** [jOOQ/jOOQ#15774]
### Expected behavior

set `isKotlinNotNullPojoAttributes` to true, but it still generate primary key type as nullable 

### Actual behavior

primary key type should be non-nullable type in generated pojos if `isKotlinNotNullPojoAttributes` is true

### Steps to reproduce the problem

1. create a table
```sql
CREATE
    TABLE
        team(
            id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
            name VARCAHR(10) NOT NULL
        );
```
2. let jooq generate kotlin pojos

### jOOQ Version

3.18.7

### Database product and version

Postgre

**Comment by lukaseder** [comment]
Thanks for your message.

An identity column is nullable prior to an insert, so there's no way to model this fact other than making it nullable always. See also discussion here:

- https://github.com/jOOQ/jOOQ/issues/14566
