### ISSUE TITLE
withRenderQuotedNames not work

### ISSUE THREAD

**Issue by RussiaVk** [jOOQ/jOOQ#15789]
### Expected behavior

```select * from `member` where `userId` = ? order by `date` ```

### Actual behavior

`select * from member where userId = ? order by date`

### Steps to reproduce the problem

```
import static org.jooq.impl.DSL.field;
import static org.jooq.impl.DSL.table;
import org.jooq.DSLContext;
import org.jooq.SQLDialect;
import org.jooq.conf.RenderQuotedNames;
import org.jooq.conf.Settings;
import org.jooq.impl.DSL;

public class SQLTest {
	public static void main(String[] args) {
		Settings settings = new Settings().withRenderQuotedNames(RenderQuotedNames.ALWAYS);
		DSLContext context = DSL.using(SQLDialect.MYSQL, settings);
		System.out.println(context.select().from(table("member")).where(field("userId").eq(field("?")))
				.orderBy(field("date")).getSQL());
	}
}
```

### jOOQ Version

3.15.12

### Database product and version

Mysql 8.0.27

### Java Version

openjdk version "17.0.1" 2021-10-19

### OS Version

Microsoft Windows [Version 10.0.16299.194]

**Comment by lukaseder** [comment]
Thanks for your message.

Please have a look at the difference between using plain SQL templates vs. identifiers:

- https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/
- https://www.jooq.org/doc/latest/manual/sql-building/names/
