### ISSUE TITLE
NLS_SORT in JOOQ

### ISSUE THREAD

**Issue by okasoy** [jOOQ/jOOQ#15796]
### Your question

Is there any way to write that statement in JOOQ?

```
SELECT *
  FROM test
  ORDER BY NLSSORT(name, 'NLS_SORT = Slovak');
```

### jOOQ Version

JOOQ Pro 3.18.7

### Database product and version

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0

### Java Version

openjdk 17

### JDBC driver name and version (include name if unofficial driver)

oracle.jdbc.OracleDriver

**Comment by lukaseder** [comment]
Thank you very much for your message. jOOQ doesn't support Oracle's `NLS` functions and settings out of the box, but you can easily implement a plain SQL template do this for you:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

E.g.

```java
DSL.field("nlssort({0}, 'NLS_SORT = Slovak')", TEST.NAME)
```
