### ISSUE TITLE
Add method documentation to `UpdatableRecordImpl`

### ISSUE THREAD

**Issue by cies** [jOOQ/jOOQ#15798]
### Use case

We used `UpdatableRecordImpl.store()` and expected it would give us an id back (we were only storing one record); but it gave us the number of affected records back. This is understandable from a SQL perspective, that's how it has worked for a very long time. But we got bitten by it...

A bit of comment on `UpdatableRecordImpl`, on the `store()` method, but also maybe on other methods would have been very helpful. Since `UpdatableRecordImpl` is what IntelliJ shows the documentation of.

Currently is only have class docs saying:

    A record implementation for a record holding a primary key
    This type is for JOOQ INTERNAL USE only. Do not reference directly

I'd like to reference this file, as in, use the javadocs as a reference. Maybe "do not call directly" is a better wording.

### Possible solution

Add docs.

### Possible workarounds

Remember that store() returns a number of affected records.

### jOOQ Version

3.18.6-OSS

### Database product and version

MySQL

**Comment by lukaseder** [comment]
Thanks for your suggestion. I think everything is clear in the Javadoc?
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/UpdatableRecord.html#store()

`UpdatableRecordImpl` doesn't change anything about the `UpdatableRecord` contract, and inherits the documentation, so you'll see it here too:
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/UpdatableRecordImpl.html#store()

**Comment by cies** [comment]
Tested it yesterday: did not show up in IntelliJ. Tested it today: does show up. If I find out why/when it did not, I'll report back. Thanks for looking into it.

**Comment by lukaseder** [comment]
Perhaps, the Javadoc wasn't pulled from Maven central when you first tried it...?
