### ISSUE TITLE
Misleading example in manual's section about the CREATE TRIGGER statement

### ISSUE THREAD

**Issue by djarnis73** [jOOQ/jOOQ#15816]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-building/ddl-statements/create-statement/create-trigger-statement/create-trigger-statement-events/

### Feedback

Just read the documentation and the last example look slightly wrong in the sense that it creates a trigger using `.beforeInsert().orUpdate().orDelete()` but logs the text `"Row deleted in BOOK"` perhaps a better text would be `"Row inserted or updated or deleted in BOOK"`.

**Comment by lukaseder** [comment]
Thanks a lot for your report. Well spotted!

**Comment by lukaseder** [comment]
Fixed. The manual will be updated in 2-3 hours with the new text.
