### ISSUE TITLE
Get SQL dialect

### ISSUE THREAD

**Issue by losador** [jOOQ/jOOQ#15810]
### Your question

Hello, is there any way to get the SQL dialect from config in code, not using '@Value' annotation?

### jOOQ Version

JOOQ Pro 3.18.7

### Database product and version

Oracle Database 19c Enterprise Edition

### Java Version

openjdk version "17"

### OS Version

mac

### JDBC driver name and version (include name if unofficial driver)

oracle.jdbc.OracleDriver

**Comment by lukaseder** [comment]
Thanks for your message.

I'm trying to guess what you're doing and what your actual question here is. jOOQ doesn't have any `@value` annotation, nor is it opinionated about how you configure it. You're probably using Spring, and you can use Spring in any way you want to configure jOOQ. In the end, jOOQ just receives a `SQLDialect` in its `Configuration` in one way or another. For example, you can create a `DefaultConfiguration` explicitly, or call `DSL.using(...)` to create one implicitly.

Possibly, this helps?
https://blog.jooq.org/how-to-customise-a-jooq-configuration-that-is-injected-using-spring-boot/

I can further help you with a *specific* question about a *specific* Spring setup.

**Comment by losador** [comment]
Yes, i am using spring and setting up jooq.sql-dialect in application.properties. Question is can i get that jooq.sql-dialect value in my code?

**Comment by lukaseder** [comment]
Well, you injected a `Configuration` or `DSLContext`, so you just call `Configuration.dialect()` on it

**Comment by losador** [comment]
Thanks, it works
