### ISSUE TITLE
Compilation error in KotlinGenerator generated code for tables containing a FROM column, when <interfaces> is activated

### ISSUE THREAD

**Issue by devkanro** [jOOQ/jOOQ#15848]
### Expected behavior

Using `this` for fields.

```kotlin
fun from(from: IEmail) {
    this.id = from.id
    this.from = from.from
    this.to = from.to
}
```

### Actual behavior

JOOQ Kotlin Generator will generate those code when table has field named `from`.

```kotlin
fun from(from: IEmail) {
    id = from.id
    from = from.from // attention this line, field and parameter name conflicted
    to = from.to
}
```

### Steps to reproduce the problem

See module `jOOQ-mcve-kotlin-mysql` and run compile task

https://github.com/devkanro/jOOQ-mcve-15848

### jOOQ Version

3.18.7

### Database product and version

Mysql 8

**Comment by lukaseder** [comment]
Thanks a lot for your report. Will look into this right away.

**Comment by lukaseder** [comment]
We already do this correctly in generated records.

**Comment by lukaseder** [comment]
The integration test added for this problem helped uncover yet another (unrelated) problem:

- https://github.com/jOOQ/jOOQ/issues/15850

**Comment by lukaseder** [comment]
Fixed in versions

- 3.19.0
- 3.18.8 (https://github.com/jOOQ/jOOQ/issues/15851)
- 3.17.17 (https://github.com/jOOQ/jOOQ/issues/15852)
- 3.16.23 (https://github.com/jOOQ/jOOQ/issues/15853)
