### ISSUE TITLE
Add support for MD5 in SNOWFLAKE dialect

### ISSUE THREAD

**Issue by yonatanl2** [jOOQ/jOOQ#15844]
### Use case

Per the documentation, MD5 is not implemented in SNOWFLAKE dialect in jooq https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/string-functions/md5-function/

Snowflake supports MD5 https://docs.snowflake.com/en/sql-reference/functions/md5

### jOOQ Version

jOOQ Enterprise 3.18.4

### Database product and version

SNOWFLAKE

### Java Version

openjdk 20

### JDBC driver name and version (include name if unofficial driver)

net.snowflake:snowflake-jdbc:3.13.33

**Comment by lukaseder** [comment]
Thanks for the pointer. Will update this right away. Note that jOOQ already rendered `MD5(..)` for Snowflake (and all other dialects), so this is mainly a documentation issue as the necessary dialect in the method's `@Support` annotation is missing.

**Comment by yonatanl2** [comment]
Great, thanks for the clarification @lukaseder !
