### ISSUE TITLE
How use "INET_ATON" function in jooq?

### ISSUE THREAD

**Issue by RussiaVk** [jOOQ/jOOQ#15863]
### Your question

How use INET_ATON function( or something similar) in jooq?
I need use this function in jooq to get such sql statement.

```SELECT 1 FROM VISITOR_TABLE WHERE  `ip`=INET_ATON(?) LIMIT 1 ```   

### jOOQ Version

3.15.12

### Database product and version

Mysql 8.0.27

### Java Version

openjdk version "17.0.1" 2021-10-19

### OS Version

Microsoft Windows [Version 10.0.16299.194]

**Comment by lukaseder** [comment]
Thanks for your message. Have you had a closer look at plain SQL templates, which I recommended some time ago?


- https://github.com/jOOQ/jOOQ/issues/15789#issuecomment-1794185055
- https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

**Comment by RussiaVk** [comment]
`DSL.select(field("someField")).from(table("TABLE")).where(field("ip").eq(field("INET_ATON(?)"))).getSQL();`
