### ISSUE TITLE
Code generator doesn't run on jooq 3.9.1 cause javax/xml/bind/JAXB

### ISSUE THREAD

**Issue by dycasxe101** [jOOQ/jOOQ#15865]
### Expected behavior

Hai All,

kindly help me
I have many project A until G
on project A, i can code generate and maven install nothing problems. but on anther project did not success, always get error.
Uses java 1.8 Azul

```
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment Zulu18.32+13-CA (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Zulu18.32+13-CA (build 18.0.2.1+1, mixed mode, sharing)
```

Maven 3.8.8 or 3.9.5
`Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)
Maven home: /Users/admin_fintopia/Documents/project/apache-maven-3.8.8
Java version: 18.0.2.1, vendor: Azul Systems, Inc., runtime: /Users/admin_fintopia/Library/Java/JavaVirtualMachines/azul-18.0.2.1/Contents/Home
Default locale: en_ID, platform encoding: UTF-8
OS name: "mac os x", version: "13.6", arch: "aarch64", family: "mac"`

Here the error
```
ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.9.1:generate (default) on project overseas-payment-common: Execution default of goal org.jooq:jooq-codegen-maven:3.9.1:generate failed: A required class was missing while executing org.jooq:jooq-codegen-maven:3.9.1:generate: javax/xml/bind/JAXB
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.jooq:jooq-codegen-maven:3.9.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/admin/.m2/repository/org/jooq/jooq-codegen-maven/3.9.1/jooq-codegen-maven-3.9.1.jar
[ERROR] urls[1] = file:/Users/admin/.m2/repository/org/jooq/jooq-codegen/3.9.1/jooq-codegen-3.9.1.jar
[ERROR] urls[2] = file:/Users/admin/.m2/repository/org/jooq/jooq/3.9.1/jooq-3.9.1.jar
[ERROR] urls[3] = file:/Users/admin/.m2/repository/org/jooq/jooq-meta/3.9.1/jooq-meta-3.9.1.jar
[ERROR] urls[4] = file:/Users/admin/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
[ERROR] urls[5] = file:/Users/admin/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.11/plexus-interpolation-1.11.jar
[ERROR] urls[6] = file:/Users/admin/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.jar
[ERROR] urls[7] = file:/Users/admin/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
```

### Steps to reproduce the problem

i tried many things, change java version, maven version, and another info, on my m2, javax.xml.bind already exist

### jOOQ Version

3.9.1

### Database product and version

mysql

### Java Version

openjdk version "18.0.2.1" 2022-08-18

**Comment by lukaseder** [comment]
Thanks for your message.

That old version of jOOQ was made when Java 8 was still the common baseline everywhere. The JDK 8 still included JAXB, so declaring it as a dependency wasn't necessary at the time, as you can see here:
https://repo1.maven.org/maven2/org/jooq/jooq/3.9.1/jooq-3.9.1.pom

If you're planning on upgrading the JDK but not jOOQ, you'll have to supply such dependencies yourself, to the code generator and to the runtime.

Or, you just upgrade jOOQ, because later versions of jOOQ officially support your JDK 18.

I hope this helps
