### ISSUE TITLE
how to translate SQL from postgresql to mysql

### ISSUE THREAD

**Issue by louishust** [jOOQ/jOOQ#15870]
### Your question

I'm using the free edition, and want to convert SQL from postgresql grammar to mysql grammar, is there some docs about how to convert sql? 

### jOOQ Version

free edition

### Database product and version

postgresql and mysql

**Comment by lukaseder** [comment]
Thanks for your message. You should find everything here:
https://www.jooq.org/doc/latest/manual/sql-building/sql-parser/
