### ISSUE TITLE
Make it possible to wrap ThreadLocalTransactionProvider so transactions would work seamlessly

### ISSUE THREAD

**Issue by victorbr** [jOOQ/jOOQ#15874]
### Use case

Our code that uses JOOQ also broadcasts events (using a mechanism not related to JOOQ, specific mechanism is not relevant). If the code sending those events runs inside a JOOQ transaction, I would like these events to be published only upon commit and not before that. In order to implement this seamlessly, I have tried to wrap `ThreadLocalTransactionProvider` into a custom implementation, delegating the API calls to the standard provider, but doing additional actions as well (in particular, being able to determine whether the thread is inside a transaction or not).
However, e.g. the method 
```
public <T> T transactionResult(ContextTransactionalCallable<T> transactional)
```
of `DefaultDSLContext` does an `instanceof` check which fails. If only it would check an instance of an interface, I could implement that interface and delegate to the underlying provider. However, `ThreadLocalTransactionProvider` is a specific implementation class and the calls break.

### Possible solution

To extract a public interface from `ThreadLocalTransactionProvider` and to test `instanceof` of this interface in the implementation of `DefaultDSLContext`'s transaction methods.

### Possible workarounds

I guess the same could be implemented with a transaction listener, but I couldn't figure out how to do that seamlessly for the client code and/or how to install a listener for a specific transaction.
**UPDATE** It's perfectly possible to do what I wanted with a listener, so for my specific use-case I'm all set! Still, I guess everyone would benefit from not referencing a specific implementation class 😄 

### jOOQ Version

3.18.7

### Database product and version

PostgreSQL 15.2

**Comment by lukaseder** [comment]
Why not just implement this in a `TransactionListener`?

**Comment by victorbr** [comment]
> Why not just implement this in a `TransactionListener`?

Right. See the later **UPDATE** in the description. Feel free to close but perhaps consider it - who knows what other use case might stumble upon it. Otherwise sorry for the noise! 🙏

**Comment by lukaseder** [comment]
I saw the UPDATE, but too late, in fact.

I don't think there's a use-case here to open up internals.
