### ISSUE TITLE
Optimistic locking without fetching entire record

### ISSUE THREAD

**Issue by akoppathn** [jOOQ/jOOQ#15889]
### Your question

I have a situation where I want to update a few columns for a record and take advantage of optimistic locking (via a version column). The issue is that I want to avoid fetching the entire record first as I have no need for retrieving that data.

Based on some of the reading I have done, it seems like the only way to do this is to not use the updatable record api and manually include a where clause for the version check. My hesitation with this is it is really easy to forget to apply that version check, which is why the UpdatableRecord implementation of optimistic locking is ideal.

Assuming I am correct in my analysis, are there any tips/recommendations on how to make an accidental skipping of a version check less likely? 

### jOOQ Version

jOOQ Professional 3.18

### Database product and version

Oracle 19c

**Comment by lukaseder** [comment]
Thanks for your message. You don't have to load the entire record. In fact, it is not recommended to do so *unless* you need the entire record (or most of it). Instead, load just a few columns (including the ID and version columns), and fetch the result into the `UpdatableRecord` type that implements the optimistic locking functionality:

```java
TRecord r =
ctx.select(T.ID, T.VERSION, T.DATA)
   .from(T)
   .where(T.ID.eq(1))
   .fetchInto(T); // Pass the generated org.jooq.Table here
```

Note, this isn't really related to optimistic locking.

I hope this helps.

**Comment by akoppathn** [comment]
I should have been more clear in my original question. I do not have a need to fetch any data at all.

Let's assume I have a table with three columns: id, note, and version. If I have a web application with an http endpoint where a user is able to update a note, they would supply the id, the version number associated with the row that they are attempting to update (which would have been retrieved at some point via a different endpoint), and the new note.

In that circumstance, to perform the update operation, I don't technically need any data from the database before the appropriate update query can be produced.

**Comment by lukaseder** [comment]
Well, there's `UpdatableRecord::merge`, does this help?

**Comment by akoppathn** [comment]
Apologies for the delayed response. `UpdatableRecord::merge` works for most cases. The one case that it does not work for relates to some backwards compatibility needs we have with our older system that manages version differently.

To provide some additional context, we want to gradually move workflow from a different framework to jOOQ. The existing framework that we have manages the updating of version columns automatically via database triggers happen on row update. It should be noted that when a row is first inserted, it is saved with a null value in the version column. It is only after it is updated for the first time after insert that the trigger fires and adds a version. I don't love that behavior, but it is what it is.

When we enable versioning in jOOQ, inserts performed by jOOQ `UpdatableRecord` result in a version of "1" (which is fine for both systems). When jOOQ `UpdatableRecord` attempts to update a row, assuming it already has a version, it will increment it by 1. In this case, the database trigger will disregard that portion of the update and replace it with a different version. As far as we can tell this does not seem to be a problem. 

Where we have an issue is in using `UpdatableRecord::merge` to update a row that was originally created from our existing framework but was never updated after the creation. In this case, the version value in the database is null and the `UpdatableRecord::merge` will attempt to do an insert instead of an update. In this situation, we would have wanted it to do an update and add a where clause that says `version is null`

Long term, it is our desire to remove the legacy database trigger and allow jOOQ to completely handle versioning. Unfortunately, there will be a period of time where both will need to coexist.

I have been searching through the API and `UpdatableRecordImpl` to see if there's a reasonably way to accommodate this edge case without needing to fetch unnecessary data while still being able to take advantage of audit columns and optimistic locking capabilities.

Unfortunately, I have come up empty handed here.

**Comment by lukaseder** [comment]
Thanks for the clarifications. Would it not be possible to one-shot update all data to have a non-nullable version value? With the trigger, this should be as simple as:

```sql
UPDATE t SET version = version
```

Or something similar, and you'd have worked around this situation.

In any case, I think there might be something wrong with the `MERGE` implementation of our optimistic locking feature. This code just runs an `INSERT` on H2, for example:

```java
ctx.settings().setExecuteWithOptimisticLocking(true);
TBookRecord r = ctx.fetchOne(T_BOOK, T_BOOK.ID.eq(4));

r.setTitle("a");
r.merge();
```

Despite the fact that clearly the record has been fetched from the database. I'll investigate this soon.

**Comment by lukaseder** [comment]
An additional trigger that fires after the existing one could take care of setting the versions to something non-null on insert?
