### ISSUE TITLE
Support overriding settings on a per-query basis

### ISSUE THREAD

**Issue by akoppathn** [jOOQ/jOOQ#15909]
### Use case

It would be nice to be able override several [Custom Settings](https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/) on a per-query basis.

For example, the ability to only enable `withReturnAllOnUpdatableRecord` in places that you actually need it. Or the ability to have optimistic locking enabled by default, but be able to tactically disable it for some use cases while still being able to use the `UpdatableRecord` API.

I suspect this could be done by defining multiple `DSLContext` instances, but I'm sure there are other "gotchas" that come with that.

### jOOQ Version

Professional 3.18.7

### Database product and version

Oracle 19c

**Comment by lukaseder** [comment]
You can use `Configuration.deriveSettings()`:
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/Configuration.html#deriveSettings(java.util.function.Function)

Use `DSLContext::configuration` and `Configuration::dsl` to turn one type into the other.

**Comment by lukaseder** [comment]
What made you think so? All the `derive()` methods simply create a copy of the `Configuration`, so you can modify the copy without affecting the original. But things like the `TransactionProvider` or `ConnectionProvider` are copied as well, and thus the derived `Configuration` inherits all of their state.

How could the documentation (manual, javadoc?) be improved to make this more clear?

**Comment by akoppathn** [comment]
In the following example, the update performed using `create2` inside of the `create.transaction` does not get rolled back following the database error that comes from executing the trx.dsl().update on the line afterwards. I'll need to do some more investigation into what I am doing wrong here.

```
Configuration newConfig = create.configuration().deriveSettings(settings -> {
      settings.setExecuteWithOptimisticLocking(false);
      settings.setReturnAllOnUpdatableRecord(false);
      return settings;
    });
DSLContext create2 = newConfig.dsl();
create.transaction(trx -> {
      create2.newRecord(TABLE).setId(401L).setNote("some new note").update();
      trx.dsl().update(TABLE).set(TABLE.NOTE, "this is going to throw an exception").where("some invalid sql").execute();
});
```
