### ISSUE TITLE
DSLContext#transactionCoroutine exception structure is unexpected and different from DSLContext#transaction

### ISSUE THREAD

**Issue by Spikhalskiy** [jOOQ/jOOQ#15908]
### Expected behavior

`context.transaction { configuration -> throw OurOwnException() }`
`context.transactionCoroutine { configuration -> throw OurOwnException() }`
lead to the same `OurOwnException` being thrown from the call.

### Actual behavior

`context.transaction { configuration -> throw OurOwnException() }` leads to the expected `OurOwnException`.
`context.transactionCoroutine { configuration -> throw OurOwnException() }` leads to unexpected double wrapped structure:
```
org.jooq.exception.DataAccessException: Exception when blocking on publisher
  Caused by: org.jooq.exception.DataAccessException: Exception when blocking on publisher
    Caused by: OurOwnException
```

### Steps to reproduce the problem

[stacktrace.txt](https://github.com/jOOQ/jOOQ/files/13519880/stacktrace.txt)

### jOOQ Version

3.18.5

### Database product and version

Postgres 15

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/15394
