### ISSUE TITLE
Support for postgres custom types in `jooq-meta`?

### ISSUE THREAD

**Issue by cbossi** [jOOQ/jOOQ#15925]
### Your question

I wonder whether `jooq-meta` supports postgres custom types (e.g. enum types)?

Assume the following simple schema for reproduction:
```
DROP SCHEMA IF EXISTS tasks CASCADE;

CREATE SCHEMA tasks;

set schema 'tasks';

create type task_status as enum ('TODO', 'IN_PROGRESS', 'DONE');

create table task
(
    id     uuid primary key default gen_random_uuid(),
    text   text        not null,
    status task_status not null
);
```

The following test fails, since the data type of the `status` column is `other` (and not `task_status` as expected):
```
@Test
fun mcveTest() {
    val tasksSchema = ctx().meta().schemas.single { it.name == "tasks" }
    val taskTable = tasksSchema.tables.single { it.name == "task" }
    val statusField = taskTable.fields().single { it.name == "status" }

    assertEquals("task_status", statusField.dataType.name)
}

```
I created a [MCVE](https://github.com/cbossi/jOOQ-mcve-15925) with the example above. (see [init.sql](https://github.com/cbossi/jOOQ-mcve-15925/blob/main/jOOQ-mcve-kotlin-postgres/src/main/resources/db/migration/init.sql) and [KotlinTest](https://github.com/cbossi/jOOQ-mcve-15925/blob/main/jOOQ-mcve-kotlin-postgres/src/test/kotlin/org/jooq/mcve/test/kotlin/postgres/KotlinTest.kt))

Am I doing something wrong?

Furthermore I wonder if there is any method to get custom data types? Something like `getTypes()` on `org.jooq.Schema`?

Of course I could get the information using JDBC directly (querying the catalog tables `pg_catalog.pg_type`, `pg_catalog.pg_enum`, ...). I am just wondering whether `jooq-meta` really does not support custom data types, since the jooq code generator does support it (with the exact same example). And I assume the generator is based on `jooq-meta`?

Thanks in advance for clarification.

### jOOQ Version

3.18.7

### Database product and version

PostgreSQL 16.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit

### Java Version

17 (Kotlin 1.8.22)

**Comment by lukaseder** [comment]
Thanks a lot for your message.

`jOOQ-meta` (the module) supports enums, as you can see in generated code in your MCVE. But the `DSLContext::meta` API doesn't, yet, see:

- https://github.com/jOOQ/jOOQ/issues/9509

I hope this helps
