### ISSUE TITLE
Getting the connection reference when running a query

### ISSUE THREAD

**Issue by valentin-panalyt** [jOOQ/jOOQ#15937]
### Your question

I would like to conditionally cancel a query that I run by calling dslContext.fetch(query). My DSLContext is configured using a Hikari connection pool. So basically, I would need to get the specific connection that the query is being run on, so that I can cancel the query (cancel_backend or similar) based on some external event.

Is that possible with JOOQ?

### jOOQ Version

JOOQ 3.18.4

### Database product and version

Postgres 15

### Java Version

jdk 17

**Comment by lukaseder** [comment]
A `org.jooq.Query` will keep a reference to the running JDBC `Statement` internally, so you can call `Query.cancel()` on it (the call will simply be ignored, if there's no current `Statement`).

Another place where you can access the current JDBC `Statement` is the `ExecuteListener` SPI.

I hope this helps.

**Comment by valentin-panalyt** [comment]
Thanks for the answer - I've got a follow up question though. I already have a `org.jooq.Select` at hand. I could turn this into an sql string and then pass it to context.query(querySqlString) to get a query object. However, is there a better way to do this?
