### ISSUE TITLE
Example of using MockFileDatabase with a "bulk collect" insert

### ISSUE THREAD

**Issue by akoppathn** [jOOQ/jOOQ#15932]
### Your question

I am attempting to use the MockFileDatabase to do some lightweight testing. Unfortunately, I am struggling to get it to work for queries that are subject to the PLSQL "bulk collect" capabilities (e.g. withReturnIdentityOnUpdatableRecord). Is there an example anywhere of how to mock the result set for these types of queries?

### jOOQ Version

3.18.7

### Database product and version

Oracle 19c

**Comment by lukaseder** [comment]
Thanks for your message.

As disclaimed in the relevant manual sections below:

- https://www.jooq.org/doc/latest/manual/sql-execution/mocking-connection/
- https://www.jooq.org/doc/latest/manual/sql-execution/mock-file-database/

> Disclaimer: The general idea of mocking a JDBC connection with this jOOQ API is to provide quick workarounds, injection points, etc. using a very simple JDBC abstraction. It is NOT RECOMMENDED to emulate an entire database (including complex state transitions, transactions, locking, etc.) using this mock API. Once you have this requirement, please consider using an actual database product instead for integration testing, rather than implementing your test database inside of a MockDataProvider.

I'd say, mocking `CallableStatemen` that rely on JDBC `OUT` parameters is currently out of scope. You're probably better off with integration testing, or mocking your service layer. But really, integration testing is what jOOQ generally recommends, e.g. using testcontainers.
