### ISSUE TITLE
jOOQ-codegen-gradle should resolve relative directories with respect to the gradle project, not the running process

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#15944]
As reported here:

- https://stackoverflow.com/q/77676948/521799
- https://github.com/mattupstate/jooq-gradle-example/

When not providing jOOQ with absolute `target` paths, then the relative directory is resolved with respect to the running process, e.g.:

```
  target dir             : C:\Users\lukas\.gradle\daemon\8.5\target\generated-sources\jooq
```

Instead of the gradle project. We do this already for the maven plugin, so let's do it as well for the gradle plugin. The default should be `build/generated-sources/jooq` instead of `target/generated-sources/jooq`

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.1 (https://github.com/jOOQ/jOOQ/issues/15945)

**Comment by mattupstate** [comment]
Would it be possible to use Gradle's filesystem types, such as `org.gradle.api.file.Directory`, instead of `String` for file oriented values?

**Comment by lukaseder** [comment]
Can you please be more specific. Where *specifically* should jOOQ use those types?
