### ISSUE TITLE
SQLite requires parenthesised DEFAULT expressions in DDL

### ISSUE THREAD

**Issue by felixscheinost** [jOOQ/jOOQ#15943]
### Expected behavior

I expect that translating the following statement from SQLite to SQLite is possible:

```SQL
CREATE TABLE "main"."flyway_schema_history" (
    "id" INT NOT NULL PRIMARY KEY,
    "created_on" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now'))
);
```

### Actual behavior

Parsing this using `ParsingConnection` either gives an exception "Unknown function", and when `parseUnknownFunctions = true`, it yields the following, incorrect SQL:

```SQL
create table main.flyway_schema_history (
  id int not null,
  created_on clob not null default strftime('%Y-%m-%d %H:%M:%f', 'now'),
  primary key (id)
)
```

The round brackets are the DEFAULT expression need to be preserved.

https://www.sqlite.org/lang_createtable.html shows that the `(` `)` around `expr` are required.

![grafik](https://github.com/jOOQ/jOOQ/assets/31761492/731b5e6d-30b5-4a8b-8cdc-1b40444cf6c4)

### Steps to reproduce the problem

- Go to https://www.jooq.org/translate/
- Enter the query
- Input Dialect: SQLite
- Output Dialect: SQLite (newest version)
- Need to check "parse unknown functions"

### jOOQ Version

jOOQ OSS 3.19.3

### Database product and version

SQLite 3.44

### Java Version

OpenJDK 17

**Comment by lukaseder** [comment]
Thanks for your report. Interesting, the only expression we've integration tested so far with `DEFAULT` expressions is `CURRENT_DATE`. This works in SQLite:

```sql
create table t (
  i int,
  d date default current_date,
  primary key (i)
);
```

Though, indeed, it isn't documented this way. I guess it doesn't hurt to just always add the extra parentheses.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.1 (https://github.com/jOOQ/jOOQ/issues/15954)
- 3.18.8 (https://github.com/jOOQ/jOOQ/issues/15955)
- 3.17.17 (https://github.com/jOOQ/jOOQ/issues/15956)
- 3.16.23 (https://github.com/jOOQ/jOOQ/issues/15957)

Thanks again for your report!

**Comment by felixscheinost** [comment]
Cool, thanks for the quick fix!
