### ISSUE TITLE
Feedback about manual section "codegen-gradle"

### ISSUE THREAD

**Issue by edvinasstaupas** [jOOQ/jOOQ#15953]
### The documentation URL

https://www.jooq.org/doc/latest/manual/code-generation/codegen-gradle/

### Feedback

There is little to no information about configuration properties and other details like default values codegen plugin has.

**Comment by lukaseder** [comment]
Why would you want any such thing on that page? The code generation plugin has tons of documentation, and there's always a gradle version for those things...

Random example:

<img width="806" alt="image" src="https://github.com/jOOQ/jOOQ/assets/734593/fb5319cc-68a4-48a0-99d1-8de140e14d80">

From here:
https://www.jooq.org/doc/latest/manual/code-generation/schema-mapping/

**Comment by StevenCurran** [comment]
Also it seems that the docs about applying the plugin have the .trail. Path present. Took me a while to figure out that the plugin did not need that in the artifactory tooling we have.

Is this a mistake in the new docs for adding the plugins {} declaration?

**Comment by lukaseder** [comment]
I'm assuming you mean this?

<img width="796" alt="image" src="https://github.com/jOOQ/jOOQ/assets/734593/aa2518c7-7a1b-4c1e-ad1d-a30691026462">

How else would you document these Maven groupIds?

**Comment by edvinasstaupas** [comment]
What I was searching for was https://www.jooq.org/xsd/jooq-codegen-3.19.0.xsd. I am not really familiar with jOOQ documentation and finding this wasn't very intuitive. XSD format is not very readable as well. In general other tools and frameworks are starting to use AI powered documentation _chatbots_. One of the examples would be [kapa.ai](https://www.kapa.ai) I found it very useful when searching for right answers in documentation. If you would like to see it in action, it is implemented in [temporal.io](https://docs.temporal.io/).

**Comment by lukaseder** [comment]
Sorry to hear that. I'm sure chatbots can be helpful, but I don't think you need an embedded one in the docs. ChatGPT is quite good with generic jOOQ questions as well.

Anyway. I don't see anything actionable in this issue so I'm closing it. Thanks again for your feedback.

**Comment by lukaseder** [comment]
But I guess for the time being, at least this footer can be added also to that particular page, where it is missing:

<img width="1177" alt="image" src="https://github.com/jOOQ/jOOQ/assets/734593/1fb789d2-6ac0-47c2-913e-7b4f6c86a8cd">

It is present with every other maven/gradle/programmatic tab set...

**Comment by StevenCurran** [comment]
> I'm assuming you mean this?
> 
> <img alt="image" width="796" src="https://private-user-images.githubusercontent.com/734593/291383177-aa2518c7-7a1b-4c1e-ad1d-a30691026462.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMDE1MjUsIm5iZiI6MTcwMzAwMTIyNSwicGF0aCI6Ii83MzQ1OTMvMjkxMzgzMTc3LWFhMjUxOGM3LTdhMWItNGMxZS1hZDFkLWEzMDY5MTAyNjQ2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQxNTUzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDJhNDgyYzRkMjg0Nzk4NjMxMzRiOTEwYWY5ZTVhODEzYTc5ZTRlODhiZDIxOGJkNTljMmQxZjFlYTcwYzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j_vzVvlrHRNrVUno2xQvTQdM6iqevO1t40l5udwCKNY">
> How else would you document these Maven groupIds?

Yes I actually missed the commented ones. Is there a reason why trail and not the open source one is the default? The default on the binary hosting services like sona / mvncentral are not using the trial version. Is it worth changing that line to be the default uncommented version? 

https://mvnrepository.com/artifact/org.jooq/jooq-codegen-gradle/3.19.0

**Comment by edvinasstaupas** [comment]
I have got the plugin up and running, but I needed to specify `buildscript{}` with driver dependency. Maybe that would be helpful to include in example code snippet. I can see that previous versions without official gradle plugin had `buildscript{}` included. I spent a whole day trying to figure out what was missing haha and only stumbled upon an old configuration that had driver dependency specified in `buildscript`.

**Comment by lukaseder** [comment]
> I have got the plugin up and running, but I needed to specify `buildscript{}` with driver dependency. Maybe that would be helpful to include in example code snippet. I can see that previous versions without official gradle plugin had `buildscript{}` included. I spent a whole day trying to figure out what was missing haha and only stumbled upon an old configuration that had driver dependency specified in `buildscript`.

@edvinasstaupas The correct way is to add:

```
dependencies {
    jooqCodegen("${group}:jooq-meta-extensions:${version}")
}
```

This should obviously be part of the documentation. Will add it right away.

**Comment by lukaseder** [comment]
> > Is there a reason why trial and not the open source one is the default? The default on the binary hosting services like sona / mvncentral are not using the trial version. Is it worth changing that line to be the default uncommented version?
> 
> @StevenCurran The same question will be asked by anyone who _doesn't_ want the open source edition.

I just realised, the maven documentation usually uses the OSS groupId. So, I'll switch for consistency reasons.

**Comment by edvinasstaupas** [comment]
> > I have got the plugin up and running, but I needed to specify `buildscript{}` with driver dependency. Maybe that would be helpful to include in example code snippet. I can see that previous versions without official gradle plugin had `buildscript{}` included. I spent a whole day trying to figure out what was missing haha and only stumbled upon an old configuration that had driver dependency specified in `buildscript`.
> 
> @edvinasstaupas The correct way is to add:
> 
> ```
> dependencies {
>     jooqCodegen("${group}:jooq-meta-extensions:${version}")
> }
> ```
> 
> This should obviously be part of the documentation. Will add it right away.

Commented out `buildscript` and added:
```
jooqCodegen "org.jooq:jooq-meta-extensions:$jooqVersion"
``` 
but still now get `java.lang.ClassNotFoundException: org.mariadb.jdbc.Driver`

My full build.gradle for reference, maybe you will find what I am missing:
```
// buildscript {
//     repositories {
//         maven {
//             private repo
//         }
//     }
//     dependencies {
//        classpath  "org.mariadb.jdbc:mariadb-java-client:3.3.1"
//     }
// }

plugins {
    id 'java'
    id 'org.jooq.jooq-codegen-gradle' version "3.19.0"
    id 'org.springframework.boot' version '3.0.5'
    id 'io.spring.dependency-management' version '1.1.0'
    id 'org.springdoc.openapi-gradle-plugin' version "1.6.0"
}

group = 'redacted'
version = '0.0.1-SNAPSHOT'
java.sourceCompatibility = JavaVersion.VERSION_18

def lombokVersion = "1.18.30"
def jooqVersion = "3.19.0"
def mariaDbVersion = "3.3.1"
def flywayVersion = "9.4.0"
def springdocOpenApiVersion = "2.2.0";
def temporalVersion = "1.22.3"
def minioVersion = "8.4.6"

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

openApi {
    apiDocsUrl.set("http://localhost:2001/api-docs")
    waitTimeInSeconds.set(20)
    outputDir.set(file("../../openapi/"))
    outputFileName.set("Openapi.json")
}

repositories {
    maven {
        // private repo
    }
}

dependencies {
    // Spring
    implementation "org.springframework.boot:spring-boot-configuration-processor"

    // Database
    implementation "org.springframework.boot:spring-boot-starter-data-jdbc"
    implementation "org.flywaydb:flyway-core:$flywayVersion"
    implementation "org.flywaydb:flyway-mysql:$flywayVersion"
    implementation "org.jooq:jooq:$jooqVersion"
    implementation "org.jooq:jooq-meta:$jooqVersion"
    implementation "org.jooq:jooq-codegen:$jooqVersion"
    implementation "org.mariadb.jdbc:mariadb-java-client:$mariaDbVersion"
    jooqCodegen "org.jooq:jooq-meta-extensions:$jooqVersion"

    // Lombok
    compileOnly "org.projectlombok:lombok:$lombokVersion"
    annotationProcessor "org.projectlombok:lombok:$lombokVersion"
    testCompileOnly "org.projectlombok:lombok:$lombokVersion"
    testAnnotationProcessor "org.projectlombok:lombok:$lombokVersion"

    // web
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation "org.springframework.boot:spring-boot-starter-validation"

    // openapi
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:$springdocOpenApiVersion"

    // Min.io
    implementation "io.minio:minio:$minioVersion"

    // Temporal
    implementation "io.temporal:temporal-sdk:$temporalVersion"
    implementation 'com.google.protobuf:protobuf-java-util:3.25.0'

    // Micrometer
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework:spring-aspects'
    implementation 'org.springframework.boot:spring-boot-starter-aop'
    implementation 'io.micrometer:micrometer-registry-prometheus:1.9.7'

    // json
    implementation 'org.json:json:20230618'

    // tests
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation "io.temporal:temporal-testing:$temporalVersion"
}

tasks.named('test') {
    useJUnitPlatform()
}

java {
    withSourcesJar()
}

jooq {
    configuration {
        jdbc {
            driver = 'org.mariadb.jdbc.Driver'
            url = 'jdbc:mariadb://127.0.0.1:3306'
            user = 'root'
            password = 'password'
            schema = 'schema'
        }
        logging = org.jooq.meta.jaxb.Logging.TRACE
        generator {
            name = 'org.jooq.codegen.DefaultGenerator'
            database {
                name = 'org.jooq.meta.mariadb.MariaDBDatabase'
                inputSchema = 'schema'
                excludes = "flyway_schema_history"
                forcedTypes {
                    // forced types
                }
            }
            generate {
                deprecated = false
                records = true
                immutablePojos = false
                fluentSetters = false
            }
            target {
                basedir = "${projectDir}"
                packageName = 'package'
                directory = 'src/generated/java'
            }
            strategy {
                name = "org.jooq.codegen.DefaultGeneratorStrategy"
            }
        }
    }
}
```

**Comment by lukaseder** [comment]
> Commented out `buildscript` and added:
> 
> ```
> jooqCodegen "org.jooq:jooq-meta-extensions:$jooqVersion"
> ```
> 
> but still now get `java.lang.ClassNotFoundException: org.mariadb.jdbc.Driver`

Yeah, well, I pasted a random dependency that *I* needed in my integration tests 😉 I should have placed the coordinates of the mariadb JDBC driver instead.

```
dependencies {
    jooqCodegen "org.mariadb.jdbc:mariadb-java-client:$mariaDbVersion"
}
```

**Comment by edvinasstaupas** [comment]
It works! Thank you for your help.
I got it running and as I understand, `jooqCodegen` task is started every time any task is started. If I have an empty database but records referenced in code or changes in my schema, after task finishes, records might have changed and app doesnt compile. I find that unintuitive. During development often there is no need to have a running database with current schema configuration. Using `-x jooqCodegen` task is not started and everything works. Is there a way to disable automatic running?

**Comment by lukaseder** [comment]
> During development often there is no need to have a running database with current schema configuration.

That's intriguing. Why not?

In any case, it's not uncommon to have database change management in place (e.g. Flyway, Liquibase), so you can declare those migration files as inputs for the `jooqCodegen` task, which will then not be run unless those files change.

This seems to be more of a gradle question in general, though.

**Comment by lukaseder** [comment]
Btw, you might also want to discuss here:

- https://github.com/jOOQ/jOOQ/issues/15966

This issue here is slowly turning into a generic all gradle related discussion, but in order to track improvements, it's usually better to create individual issues going forward.

**Comment by StevenCurran** [comment]
> > > Is there a reason why trial and not the open source one is the default? The default on the binary hosting services like sona / mvncentral are not using the trial version. Is it worth changing that line to be the default uncommented version?
> 
> > 
> 
> > @StevenCurran The same question will be asked by anyone who _doesn't_ want the open source edition.
> 
> 
> 
> I just realised, the maven documentation usually uses the OSS groupId. So, I'll switch for consistency reasons.

Thank you sir. Keep up the amazing work on this product!
