### ISSUE TITLE
How can I inject configuration using jaxb?

### ISSUE THREAD

**Issue by RussiaVk** [jOOQ/jOOQ#15964]
### Your question

The configuration seems to not support auto injection via jaxb.
How can I inject configuration using jaxb?(just like jooq-settings.xml)
Can you please give me some guidance or examples?

### jOOQ Version

3.15.12

### Database product and version

Mysql 8.0.27

### Java Version

openjdk version "17.0.1" 2021-10-19

### OS Version

Microsoft Windows [Version 10.0.16299.194]

**Comment by lukaseder** [comment]
I'm sorry, I don't know what "inject configuration using jaxb" means.

**Comment by RussiaVk** [comment]
> I'm sorry, I don't know what "inject configuration using jaxb" means.

Just like Jooq can read Settings from jooq-settings.xml file without hard code.

**Comment by RussiaVk** [comment]
> > I'm sorry, I don't know what "inject configuration using jaxb" means.
> 
> Just like Jooq can read Settings from jooq-settings.xml file without hard code.

I need set SQLDialect via xml to get rid of below hard code.
`DSL.using(SQLDialect.MYSQL)`

**Comment by lukaseder** [comment]
You can't do that with jOOQ API, but you can probably figure out your own configuration format that supports this.
