### ISSUE TITLE
Cannot look up tasks.named("jooqCodegen") from gradle scripts

### ISSUE THREAD

**Issue by strindberg** [jOOQ/jOOQ#15974]
### Expected behavior

During a build, we use the flyway gradle plugin to set up a database in a Postgres container, and then configure the Jooq code generation task to run against this database. This works fine in the unofficial gradle plugin. This also means that the Jooq code generating task is dependent on the flyway task having run first.

### Actual behavior

I cannot find a way to make the `jooqCodegen` task dependent on the `flywayMigrate` task. (We're using the Kotlin version of gradle, btw). The following leads to a compilation error in the IDE:

``` kotlin
tasks.jooqCodegen {
    dependsOn(tasks.flywayMigrate)
}
```

This, surprisingly, also doesn't work:
```kotlin
tasks.named("jooqCodegen") {
    dependsOn(tasks.flywayMigrate)
}
```
it produces:
```
* What went wrong:
Task with name 'jooqCodegen' not found in root project 'cc-backend'.
```

### Steps to reproduce the problem

Configure your build.gradle.kts as above to see the problem.

### jOOQ Version

3.19.0

### Database product and version

Postgres 15

**Comment by lukaseder** [comment]
Thanks for your report. Can you please provide a complete `build.gradle.kts` file?

**Comment by lukaseder** [comment]
Thanks a lot. I'll look into it soon

**Comment by lukaseder** [comment]
Does this work for you?

```kotlin
tasks.all {
    if (name.equals("jooqCodegen"))
        dependsOn(tasks.flywayMigrate)
}
```

**Comment by strindberg** [comment]
No, it makes no difference: the task is not found.

I have the impression that the jooq task is added by the plugin too late: when I run `gradle tasks` I do see "jooqCodegen", but it doesn't seem to be available at configuration time in the build file, which suggests to me that perhaps the plugin is adding this task in the wrong part of the process?

**Comment by lukaseder** [comment]
My assumption was as well that there's a timing issue. Though, you can do this:

```kotlin
tasks.all {
    println(name)
}
```

And it prints:

```

> Configure project :
assemble
build
buildDependents
buildEnvironment
buildNeeded
check
classes
clean
compileJava
compileTestJava
components
dependencies
dependencyInsight
dependentComponents
flywayBaseline
flywayClean
flywayInfo
flywayMigrate
flywayRepair
flywayUndo
flywayValidate
help
init
jar
javaToolchains
javadoc
kotlinDslAccessorsReport
model
outgoingVariants
prepareKotlinBuildScriptModel
processResources
processTestResources
projects
properties
resolvableConfigurations
tasks
test
testClasses
wrapper
jooqCodegen

> Task :jooqCodegen

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
12:08:38: Execution finished 'jooqCodegen'.
```

**Comment by lukaseder** [comment]
So, while the `jooqCodegen` task is included in the list of tasks, it appears last instead of appearing in alphabetic order, which probably hints at why it's being added too late.

**Comment by lukaseder** [comment]
So, it seems that combining these two changes solves the issue:

- Stop calling `project.afterEvaluate(...)` to configure the tasks
- Switch from calling `TaskContainer.create(...)` to `TaskContainer.register(...)`

**Comment by strindberg** [comment]
Yes with my (limited) knowledge of gradle, that makes sense: `afterEvaluate` is run after all the tasks are configured, and probably explains why other tasks are not able to see the jooq tasks during configuration.

**Comment by lukaseder** [comment]
> Yes with my (limited) knowledge of gradle, that makes sense: `afterEvaluate` is run after all the tasks are configured, and probably explains why other tasks are not able to see the jooq tasks during configuration.

To be honest, I only used it, because it helped work around some error about task dependencies can't be modified after some stage of the configuration process 😅

**Comment by lukaseder** [comment]
Ah, no there were other reasons, too. The `executions` were available only in `afterEvaluate()`. I guess that changing these things will keep me busy for another few hours...

**Comment by axelfontaine** [comment]
Facing this as well. This is a blocker for adoption of the new Gradle plugin. Almost everyone using it in combination with Flyway or Liquibase will stumble upon this.

**Comment by hsl43** [comment]
> So, it seems that combining these two changes solves the issue:
> 
>     * Stop calling `project.afterEvaluate(...)` to configure the tasks
> 
>     * Switch from calling `TaskContainer.create(...)` to `TaskContainer.register(...)`

@lukaseder Why do you advise against using `project.afterEvalute()`?  

I have a project where I need the `jooqCodgen` task to run:
* **before** a kapt-based code generator runs (because it uses some jOOQ generated classes), and
* **after** another code generator runs (because I have a custom jOOQ JavaGenerator that depends on these other generated class

I had the same problem as the reporter wherein the `jooqCodegen` task wasn't defined in time during the Gradle configuration, but placing that configuration in the `afterEvaluate` block solved the problem, e.g.:
```
afterEvaluate {
  val jooqCodegenTask = tasks.named("jooqCodegen")

  jooqCodegenTask {
    dependsOn(tasks.openApiGenerate)
  }

  tasks.named("kaptGenerateStubsKotlin") {
    dependsOn(jooqCodegenTask)
  }
}
```

**Comment by lukaseder** [comment]
> @lukaseder Why do you advise against using `project.afterEvalute()`?

The reason I used it is because by the time my code got the callback, all the configuration has been established, and as such, I could more easily create complex configuration (e.g. a task that runs all executions). But I figured out a way to do this in `configureEach()` now.

I was once again biased by my usage of Maven, where there's a completely inert XML file, whose structure is known entirely when configuring the plugin, unlike in gradle's case, where the configuration is actual code that is executed, and cannot really be reflected upon.

Anyway, jOOQ-codegen-maven will not configure itself in the `afterEvaluate()` event. This hint alone shows that it's fishy:
https://github.com/jOOQ/jOOQ/issues/15974#issuecomment-1866068517

**Comment by lukaseder** [comment]
N.B: The fix has already been implemented on main for 3.20.0-SNAPSHOT and 3.19.2-SNAPSHOT, you can try it out. I can't release it yet, because I have a few tests due that I'd like to implement first.

**Comment by strindberg** [comment]
I have tested the 3.19.2-SNAPSHOT version, and it seems to have fixed the issue. That's great!

However, there is an issue that I haven't seen earlier: no matter how I specify the directory where I want the generated code to be produced, it always ends up under "build/generated-sources/jooq". I assume this is not directly related to this issue, so if you want I could create another issue, but I have used variants of the configuration I posted earlier in this thread, of which this is the relevant snippet:

```kotlin
jooq {
    configuration {
        ...
        generator {
            ...
                target {
                    directory = generatedPath
                }
            }
        }
    }
}
```

At first I thought it might be that the variable "generatedPath" was not set, but it doesn't seem to work with a hard-coded path either. It could possibly be related to some timing mismatch when the configuration value is read?

**Comment by lukaseder** [comment]
Thanks for your report, @strindberg. I recall having seen this, thought it was fixed already. Will check again.

As mentioned before, the plugin needs more tests. In particular, a test that doesn't have any `executions { }`, but only a `configuration { }`. (The main purpose of the `executions { }` was to facilitate integration testing multiple configurations...

**Comment by lukaseder** [comment]
The problem appears to be that the logic in `CodegenTask` is run prematurely again. At that moment, the user's configuration logic hasn't been invoked yet (despite being in `configureEach()`)

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.2 (https://github.com/jOOQ/jOOQ/issues/16057)
