### ISSUE TITLE
Cannot verify www.jooq.org's certificate on ubuntu-latest (Github Actions)

### ISSUE THREAD

**Issue by baev** [jOOQ/jOOQ#15978]
### Expected behavior

We use Github Actions to download JOOQ distribution and push it to our private registry. Script uses `ubuntu-latest` agent and `wget`.

We expect the distribution to be downloaded successfully.

### Actual behavior

Recently, we have started getting the following error:

```
Resolving www.jooq.org (www.jooq.org)... 84.16.84.89, 2001:1600:4:11::3d
Connecting to www.jooq.org (www.jooq.org)|84.16.84.8[9](https://github.com/.../.../actions/runs/.../job/...#step:3:10)|:443... connected.
ERROR: cannot verify www.jooq.org's certificate, issued by ‘CN=Sectigo RSA Extended Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB’:
  Unable to locally verify the issuer's authority.
```

Using `--no-check-certificate` option helps

### Steps to reproduce the problem

Probably just wget jooq.org from Ubuntu machine

### jOOQ Version

3.19.0

### Database product and version

PostgreSQL

**Comment by lukaseder** [comment]
Thanks for the feedback. I can reproduce this with wget. Will contact the hoster who installed our certificate.

**Comment by lukaseder** [comment]
Another workaround is described here:
https://serverfault.com/a/1118636/74851

**Comment by lukaseder** [comment]
Very curious. This seems to happen only with `jooq.org` and `www.jooq.org`, not with the other domains under this certificate, including e.g. `repo.jooq.org`

**Comment by lukaseder** [comment]
It looks like the problem is solved by the hoster now. I can't reproduce the issue anymore on my end using `wget`. Can you?
