### ISSUE TITLE
Version release statement not updated.

### ISSUE THREAD

**Issue by edvinasstaupas** [jOOQ/jOOQ#15992]
### The documentation URL

https://www.jooq.org/download/

### Feedback

`[10]: Since jOOQ 3.19 (to be released in 2023) and later versions` should be updated as 3.19 is already released.

**Comment by lukaseder** [comment]
Thanks for your hint.

There's a pending task to update the legal parts of the 3.19 release, with this page being part of it, but I can already fix it now.
