### ISSUE TITLE
Cannot project TableAsField if table contains embeddables in PostgreSQL

### ISSUE THREAD

**Issue by NorbertKawinski** [jOOQ/jOOQ#15991]
### Expected behavior

Records are returned when selecting a table with embeddables by using `.select(Xyz).from(Xyz)`.

### Actual behavior

Exception: 
```
org.jooq.exception.DataAccessException: 
SQL [select row ("mcve"."person"."person_id", "mcve"."person"."name") as "person" from "mcve"."person"]; 
Error while reading field: row (  "mcve"."person"."person_id",  "mcve"."person"."name"), at JDBC index: 1
```

Full logs: https://pastebin.com/y1A3sAJU

### Steps to reproduce the problem
MCVE: https://github.com/NorbertKawinski/jOOQ-mcve

Enable embeddables generation:
```
<embeddableDomains>.*</embeddableDomains>
```

Create following schema:
```
CREATE DOMAIN mcve.person_id AS uuid;
CREATE TABLE mcve.person
(
    person_id mcve.person_id PRIMARY KEY,
    name varchar(255) NOT NULL
);
INSERT INTO mcve.person (person_id, name)
VALUES ('00000000-0000-0000-0000-000000000002', 'Wladzio');
```

Run following code:
```
ctx.select(PERSON).from(PERSON).fetch();
```

### jOOQ Version

org.jooq.pro:jooq:3.19.0

### Database product and version

postgres:16.1-alpine Docker image

### Java Version

Openjdk 21.0.1

### OS Version

Microsoft Windows 11 Pro [10.0.22621 Build 22621]

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by NorbertKawinski** [comment]
You can also check MCVE here: https://github.com/NorbertKawinski/jOOQ-mcve (main branch)

**Comment by lukaseder** [comment]
Thanks a lot for your report and MCVE. I'll look into this soon.

**Comment by lukaseder** [comment]
Thanks for your patience. I can reproduce the problem with your test. Curiously, our own integration tests don't fail for very similar queries. Will investigate right away.

**Comment by lukaseder** [comment]
Related issue:

- https://github.com/jOOQ/jOOQ/issues/12237

That issue has added a test which is known to fail, similar to your case, where an embeddable is used in a `ROW()` expression in `SELECT`. But the known limitation isn't listed yet in:

- https://github.com/jOOQ/jOOQ/issues/15892

I'll add it.

**Comment by lukaseder** [comment]
This seems to be PostgreSQL specific, since we're using `ROW()` to implement `TableAsField` in PostgreSQL. The problem doesn't appear with HSQLDB, for example, where `ROW()` projections are emulated by flattening the row.
