### ISSUE TITLE
RenderTable.WHEN_AMBIGUOUS_COLUMNS doesn't cover all ambiguous column name cases

### ISSUE THREAD

**Issue by rszyler** [jOOQ/jOOQ#15998]
### Expected behavior

If `WHEN_AMBIGUOUS_COLUMNS` is set as `renderTables` setting then `org.jooq.impl.SelectQueryImpl#accept0` will detect if there are columns with the same name in `select` section but it doesn't check other sections where columns can have duplicates like where, join on, order by or if if there is conflict on column name because query contains multiple tables

Place to change in code - org.jooq.impl.SelectQueryImpl#accept0:
```
            case WHEN_AMBIGUOUS_COLUMNS: {
                if (knownTableSource() && !hasAmbiguousNames(getSelect()))
                    context.data(DATA_RENDER_TABLE, false);

                break;
            }
```

Fix seems to be complicated and require more complex solution. If idea behind this flag was to be next step over WHEN_MULTIPLE_TABLES (to add table names to column names less often like not adding it if it's not needed even if query contains multiple tables) then to achieve this goal multiple steps need to be done:
- first check all tables used in query and identify not unique column names between them
- in select, on, where, group by, order by sections check if there is any column name from list created in previous step

Just checking if there are 2 column with the same name in query is not enough because if in query there is more that one table used then even if column name is used only once in query but it exists in both tables used in query then db engine would not be able to select from witch table this column should be used

If complex solution cannot be developed then I think this flag should be removed to not confused developers trying to use it and generate potential problems.

### Actual behavior

When `WHEN_AMBIGUOUS_COLUMNS` is set as `renderTables` setting then table name is not added to column name when query contains columns with the same name across multiple tables.

Example code for query:
```
        return getJooq(sourceId)
                .select(REMOTE_CLOUD_GROUP_MEMBERS.GROUP_ID, REMOTE_CLOUD_GROUP_MEMBERS.MEMBER_ID)
                .from(REMOTE_CLOUD_GROUP_MEMBERS)
                .innerJoin(REMOTE_CLOUD_GROUP)
                .on(REMOTE_CLOUD_GROUP_MEMBERS.SOURCE_ID.eq(REMOTE_CLOUD_GROUP.SOURCE_ID)
                        .and(REMOTE_CLOUD_GROUP_MEMBERS.MEMBER_ID.eq(REMOTE_CLOUD_GROUP.GROUP_ID)))
                .where(REMOTE_CLOUD_GROUP_MEMBERS.CHILD_GROUP.eq(true)
                        .and(REMOTE_CLOUD_GROUP_MEMBERS.SOURCE_ID.eq(sourceId)))
                .fetch()
                .stream()
                .collect(groupingBy(Record2::value1, mapping(Record2::value2, toList())));
```
Error with generated query (both tables have `group_id` column:
```
org.jooq.exception.IntegrityConstraintViolationException: SQL [select `group_id`, `member_id` from `fsmeta_231227_yP2Qt`.`remote_cloud_group_members` join `fsmeta_231227_yP2Qt`.`remote_cloud_group` on (`source_id` = `source_id` and `member_id` = `group_id`) where (`child_group` = ? and `source_id` = ?)]; Column 'group_id' in field list is ambiguous
```

### Steps to reproduce the problem

Set renderTable in Settings to WHEN_AMBIGUOUS_COLUMNS.
Create code with query containing 2 tables, both having column with the same name like select(x.z).from(x).join(y).on(x.z.eq(y.z))

### jOOQ Version

3.19.1

### Database product and version

8.0.33-google

### Java Version

openjdk 17.0.9 2023-10-17

**Comment by lukaseder** [comment]
Thank you for your report.

Related issues include:

- https://github.com/jOOQ/jOOQ/issues/15996
- https://github.com/jOOQ/jOOQ/issues/15997

I don't think it's impossible to fix this. We know all the tables that are in scope at any given query level, so we can calculate whether there are ambiguous column names, irrespective of whether the ambiguity arises between tables on the same scope level or a different one.

**Comment by lukaseder** [comment]
Also:

- https://github.com/jOOQ/jOOQ/issues/16119

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.4 (https://github.com/jOOQ/jOOQ/issues/16124)
- 3.18.11 (https://github.com/jOOQ/jOOQ/issues/16125)

jOOQ 3.17 didn't have https://github.com/jOOQ/jOOQ/issues/8893 yet, so this bugfix isn't needed in 3.17
