### ISSUE TITLE
Wrong code generation configuration example

### ISSUE THREAD

**Issue by vlaship** [jOOQ/jOOQ#16000]
### The documentation URL

https://www.jooq.org/doc/3.19/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-default-catalog-and-schema/

### Feedback

There is an issue
instead of 
```
configuration {
  generator {
    database {
      defaultCatalog = false
      defaultSchema = false
    }
  }
}
```
should be
```
configuration {
  generator {
    generate {
      defaultCatalog = false
      defaultSchema = false
    }
  }
}
```
and maybe isDefaultCatalog and isDefaultSchema

**Comment by lukaseder** [comment]
Thanks a lot for your report.

The fix will be published with a new version of the manual, soon.

I realise we don't have any tests covering these configuration snippets against the XSD, which would probably simple to achieve. I'll document any other potential fixes here with this issue.

**Comment by lukaseder** [comment]
There doesn't seem to be any other issue, currently.
