### ISSUE TITLE
Primary key non-null id fields in are generated as null in kotlin

### ISSUE THREAD

**Issue by reubenfirmin** [jOOQ/jOOQ#16007]
### Expected behavior

Non null id fields with defaults are generated as being nullable in the data classes. This shouldn't happen.

### Steps to reproduce the problem

Schema:

```
CREATE TABLE account
(
    id       uuid primary key default uuid_generate_v4() not null,
    name     text        not null,
    created  timestamptz not null default now(),
    modified timestamptz not null default now(),
    deleted  timestamptz,
    CONSTRAINT check_modified CHECK (modified >= created)
);
```

Code generator options:

```
                    .withGenerate(Generate()
                        .withPojos(true)
                        .withKotlinNotNullPojoAttributes(true)
                        .withKotlinNotNullInterfaceAttributes(true)
                        .withKotlinNotNullRecordAttributes(true)
                        .withPojosAsKotlinDataClasses(true)
                        // jooq bug - these should be default false for data classes
                        // (https://github.com/jOOQ/jOOQ/issues/10917)
                        .withPojosEqualsAndHashCode(false)
                        .withPojosToString(false)
                        .withImmutablePojos(true)
                    )
```

...generates:

```
data class Account(
    val id: UUID? = null,
    val name: String,
    val created: OffsetDateTime? = null,
    val modified: OffsetDateTime? = null,
    val deleted: OffsetDateTime? = null
): Serializable {
}
```

Here id is both "not null" AND has a default behavior set; it clearly should not be nullable.

### jOOQ Version

3.18.6

### Database product and version

Postgres 15

### Java Version

OpenJDK version 17

### OS Version

Ubuntu 23.10

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by lukaseder** [comment]
Some duplicates:

- https://github.com/jOOQ/jOOQ/issues/14786
- https://github.com/jOOQ/jOOQ/issues/14787
- https://github.com/jOOQ/jOOQ/issues/14948
- https://github.com/jOOQ/jOOQ/issues/14978

**Comment by reubenfirmin** [comment]
@lukaseder 

From one of the other tickets:

> So, what to do with such a NULL? Despite the clear design of a Record (explicit setting the value = including it in the DML operation), we have to ignore these NULL values, even if set explicitly. So, we must allow users to be able to set the value of an otherwise non-NULL column to NULL.

That defeats the purpose of requesting nonnull properties in data classes. In my case I have different types for form objects (newly requested creations) and database entities (jooq produced code). Having to assert non-null throughout the code on columns which are marked non-null in the schema bulldozes over kotlin's null safety.

If the user doesn't request non null properties, then sure, mark them as "?". But if they do, why not let them have what they request?

**Comment by lukaseder** [comment]
> But if they do, why not let them have what they request?

You didn't request this what you think you're requesting. You requested a default to be applicable via your schema design. How could a default apply to your data class if its property wasn't nullable / null capable? People always think of the "read case," which indeed covers 90% of all interactions with your data class.

But the "write case" must have some way of offering omitting the default.

As unhappy as the status quo makes everyone who keeps requesting a change to this, it would simply not be correct to mark a null capable attribute non-null (otherwise, why not just remove the default).

The only way I see to ever solve this (and I've linked to that discussion many times) is to cleanly separate data representations of data prior to insert / after insert / prior to update / after update, etc., see this discussion here:

- https://github.com/jOOQ/jOOQ/issues/14566#issuecomment-1413780398

**Comment by reubenfirmin** [comment]
@lukaseder Right, but I'm not using these objects for write - that's a pattern that I've followed in kotlin, which has long preceded using jooq. If I have an object with a nullable id, then I don't know the provenance of that id - it could have come from the UI, or it could have come from the DB. I can't use it as a form object without explicitly guarding against the UI trying to set an id (which would be bad). And, of course, every time I use id of the object, I have to assert that it's non null (which gets rid of a big benefit of kotlin) or clutter the code with useless branches.

To give you a specific example, what I'm doing in this project is:

a) Form object, created by me:
```
import rcp.model.jooq.enums.Currency
import rcp.model.jooq.enums.QuantityUnit
import java.math.BigDecimal

data class NewIngredient(val name: String, val supplier: String, val quantity: BigDecimal, val unit: QuantityUnit,
                         val price: BigDecimal, val currency: Currency)
```

b) Entity object, created by jooq:

```
/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Ingredient(
    val id: UUID? = null,
    val name: String,
    val supplier: String,
    val price: BigDecimal,
    val currency: Currency,
    val quantity: BigDecimal,
    val unit: QuantityUnit,
    val accountId: UUID? = null,
    val created: OffsetDateTime? = null,
    val modified: OffsetDateTime? = null,
    val deleted: OffsetDateTime? = null
): Serializable {
}
```

c) Read:

```
fun get(authUser: AuthUser, id: UUID): Ingredient? {
        println("(TODO) Will check $authUser")
        return dsl.select()
            .from(Ingredient)
            .where(Ingredient.Id.eq(id))
            .get()
    }
```

d) Write:

```
    fun create(authUser: AuthUser, newIngredient: NewIngredient): Ingredient? {

        return dsl.insertInto(Ingredient)
            .columns(Ingredient.Name, Ingredient.Supplier, Ingredient.Price, Ingredient.Currency,
                Ingredient.Quantity, Ingredient.Unit)
            .values(newIngredient.name, newIngredient.supplier, newIngredient.price, newIngredient.currency,
                newIngredient.quantity, newIngredient.unit)
            .returningResult(Ingredient.Id)
            .id()
            ?.run {
                get(authUser, this)
            }
    }
```    

I get that this is more verbose than some would want, but it has the huge advantage that if I'm dealing with an Ingredient, I'm 100% sure it came from the DB, and if I'm dealing with a NewIngredient, I know it's a form object. Because NewIngredient doesn't have an id, I don't have to check it everywhere. 

The weakest aspect is that there's no typing associating NewIngredient and Ingredient, so their types _could_ get out of sync. (Without Jooq, I was using an interface for this, and my form objects were basically proxy implementations of the interface, sans id). 

Note that the other defaults follow the same logic. There should be zero way for the UI to be able to set created/modified/deleted also, but if I were to use the jooq entity object as a form object, I'd have to add guards in the write path preventing these from being set. So it's actually less code to have a data class that is specifically for the write path than to use the jooq entity class, have null handling everywhere, and have guards on db metadata columns that the outside world shouldn't be allowed to set.

What about adding a switch to allow users who don't want a write path with jooq-objects to have non-nulls on  properties with defaults?

**Comment by lukaseder** [comment]
I understand there are various expectations towards jOOQ and use-cases / data interaction patterns, and I understand that everyone with strong opinions about nullability will be disappointed by the status quo. It's not that you're bringing new points to the discussion, there are no surprises.

jOOQ has to find a least common denominator somewhere, and that's simply:

- Either defaults have a semantics (for jOOQ)
- Or they don't (for jOOQ)

Probably something along the lines of https://github.com/jOOQ/jOOQ/issues/14566 will be implemented eventually, in case of which multiple DTOs / POJOs / data classes will be generated *per table* and *per read/write path*, but that's not the case now, and that just means people have to decide:

- Whether they accept jOOQ's current one-size-fits all philosophy, with all the trade-offs
- Or they don't, and roll their own (generated or not)

In fact, you want *exactly* #14566, and not what's in place now. And you *can*! Just don't use jOOQ's generated POJOs (jOOQ will work with yours as well). You can even extend jOOQ's code generator to generate them for you in any way you want.

> What about adding a switch to allow users who don't want a write path with jooq-objects to have non-nulls on properties with defaults?

Why add 1000s of poorly tested flags (and flag combinations) to offer an even more mediocre one-size-fits-all solution rather than implementing something ground breaking like #14566. I don't want to spend the time on more nullability flags.

If you're never going to care about those defaults, just hide them from jOOQ's code generator. We don't have synthetic defaults yet:

- https://github.com/jOOQ/jOOQ/issues/15251

But you can easily override the `PostgresDatabase` and remove all the knowledge about `DEFAULT` expressions from the meta data again, prior to generating code. Or you use a dummy database schema for code generation (e.g. using testcontainers), in which you remove all the defaults.

**Comment by reubenfirmin** [comment]
> Why add 1000s of poorly tested flags (and flag combinations)

Well, to be fair I wasn't suggesting thousands :) 

This/similar seems to be a pretty common request from Kotlin users. But, if #14566 will be more comprehensive then take all my votes for this. 

> But you can easily override the PostgresDatabase

Does sound feasible. Is there a clean patch point for this that you'd suggest? I could intercept getters that return TableDefinition, and then transform ColumnDefinitions so that DataTypeDefinition.isDefaulted always returns false...something like that?

**Comment by lukaseder** [comment]
> This/similar seems to be a pretty common request from Kotlin users

The request is common, the specific suggestion is always different. This shouldn't be solved with yet another flag.

> Does sound feasible. Is there a clean patch point for this that you'd suggest? I could intercept getters that return TableDefinition, and then transform ColumnDefinitions so that DataTypeDefinition.isDefaulted always returns false...something like that?

Something like that, yes.

**Comment by reubenfirmin** [comment]
Alright, cool; in case anybody else wants similar in future, this works. 

```
class DefaultSuppressingPostgresConfig: PostgresDatabase() {

    override fun getTables0(): MutableList<TableDefinition> {
        val pgTables = super.getTables0()
        return pgTables
            .map(::wrapTableDefinition)
            .toMutableList()
    }

    private fun wrapTableDefinition(table: TableDefinition): TableDefinition {
        return Proxy.newProxyInstance(
            TableDefinition::class.java.classLoader,
            arrayOf<Class<*>>(TableDefinition::class.java),
            TableDefinitionModifyingHandler(table)
        ) as TableDefinition
    }
}

class TableDefinitionModifyingHandler(
    private val tableDef: TableDefinition
) : InvocationHandler {

    override fun invoke(proxy: Any?, method: Method, args: Array<Any?>?): Any? {
        val result = method.invoke(tableDef, *(args ?: emptyArray()))

        if (method.getName().equals("getColumns") && result is List<*>) {
            return result.map { column ->
                this.modifyColumnDefinition(column as ColumnDefinition)
            }
        } else if (method.getName().startsWith("getColumn") && result is ColumnDefinition) {
            return modifyColumnDefinition(result)
        }

        return result
    }

    private fun modifyColumnDefinition(columnDef: ColumnDefinition): ColumnDefinition {
        val columnImpl = columnDef as DefaultColumnDefinition
        val originalDataType = columnDef.type
        val modifiedDataType = Proxy.newProxyInstance(
            DataTypeDefinition::class.java.classLoader,
            arrayOf(DataTypeDefinition::class.java),
            DataTypeModifyingHandler(tableDef, columnDef, originalDataType)
        ) as DataTypeDefinition

        return DefaultColumnDefinition(tableDef, columnImpl.name, columnImpl.position, modifiedDataType,
            columnImpl.isIdentity, columnImpl.isReadonly, columnImpl.comment)
    }
}

class DataTypeModifyingHandler(
    private val tableDef: TableDefinition,
    private val columnDef: ColumnDefinition,
    private val original: DataTypeDefinition
) : InvocationHandler {

    override fun invoke(proxy: Any, method: Method, args: Array<Any>?): Any? {
        if (method.name == "isDefaulted") {
            val orig = method.invoke(original, *(args ?: emptyArray()))
            if (orig is Boolean && orig) {
                println("Turning off nullability for ${tableDef.name}.${columnDef.name}")
            }
            return false
        }

        return method.invoke(original, *(args ?: emptyArray()))
    }
}
```

**Comment by lukaseder** [comment]
Thanks for sharing this here, @reubenfirmin

**Comment by danielstravito** [comment]
@reubenfirmin Where should it be used? I tried the following:

```
database.apply {
    name = "com.foo.mygenerator.DefaultSuppressingPostgresConfig"
    ...
}
```

And added the following to the dependencies section:
```
jooqGenerator(libs.postgresql)
jooqGenerator(projects.libraries.mygenerator)
```

It builds just fine, and the dependency is correctly pulled in, but the generator doesn't seem to run. Generated code is unchanged. Verified with `--no-configuration-cache --no-build-cache` to rule out cache to no avail. If I write any random string in database.name I still don't get any errors.

**Comment by danielstravito** [comment]
Fresh eyes found the issue. So long JOOQ config in build.gradle.kts that there was another `name =` hiding further down overwriting the former. :see_no_evil: Everything works as expected. Sorry for the noise.

**Comment by danielstravito** [comment]
@reubenfirmin Did you have to do something special to get forcedTypes working with this workaround? The nullability is correctly fixed, but everything using EnumConverter breaks. Explicit type mappers work fine though.

What used to generate as:
```
new EnumConverter<String, MyEnum>(String.class, MyEnum.class)
```
Now generates as:
```
new EnumConverter<MyEnum, MyEnum>(MyEnum.class, MyEnum.class)
```

Can't spot anything obvious in that PostgresDatabase subclass that would account for that, and haven't found anything in JOOQ that seems to take special care if the class is directly PostgresDatabase.

Also switched to the new official gradle plugin to rule that out, but it behaves identical to the nu.studer one. Not sure if it's an actual bug, or just a bug in the workaround.
