### ISSUE TITLE
Method for optional conditional expressions

### ISSUE THREAD

**Issue by oliveryasuna** [jOOQ/jOOQ#16001]
### Use case

Many developers avoid inline if-statements as they can be hard to read and debug. The docs suggests them here: https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql/no-condition/.

### Possible solution

jOOQ should include a method that wraps the common if-statement. Something simple, like the following:

```java
// With a much better name...
public Condition conditionalCondition(boolean predicate, Condition condition) {
  if(predicate) {
    return condition;
  } else {
    return noCondition();
  }
}

// And more...
public Condition conditionalCondition(boolean predicate, Condition... conditions)
public Condition conditionalCondition(boolean predicate, Collection<? extends Condition> collection)
// ...
```

Or maybe it is built into `where` and `and`, though that may over-complicate the implementations.

Further:

I do strongly feel that such a method belongs in jOOQ. While it is a simple method anyone can create, jOOQ already has a lot of those.

### jOOQ Version

Latest

### Database product and version

N/A

### Java Version

N/A

### OS Version

N/A

### JDBC driver name and version (include name if unofficial driver)

N/A

**Comment by lukaseder** [comment]
Thanks for your suggestion. There's no benefit of this:

```java
conditionalCondition(predicate, condition)
```

Over this:

```java
predicate ? condition : noCondition()
```

Au contraire, it means there's more API, and more possibilities of users requesting even more API (e.g. `conditionalCondition(Predicate predicate, ...)` for lazy predicate evaluation), and then the same thing for all other types of query part.

**Comment by oliveryasuna** [comment]
@lukaseder Thanks for considering this. I get your argument, from a code ownership perspective, it's a slippery slope.
