### ISSUE TITLE
Request - (optional) kotlin support for typealias on column ids

### ISSUE THREAD

**Issue by reubenfirmin** [jOOQ/jOOQ#16017]
### Use case

Typealiases in Kotlin are a nice feature for self-documenting properties (and more especially, their usages). Prior to Jooq our projects would commonly use typealiases on database id columns, which is especially nice for foreign keys.

Instead of:

```
data class Book(id: UUID, name: String, authorId: UUID)

// some service function

getBooksById(id: UUID)
```

...you get:

```
data class Book(id: BookId, name: String, authorId: AuthorId)

// some service function

getBooksById(id: BookIdId)
```

Could you consider adding a flag to the code generation to support this? 

### jOOQ Version

3.18.6

### Database product and version

Postgres 15

### Java Version

OpenJDK version 17

### OS Version

Ubuntu 23.10

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by lukaseder** [comment]
jOOQ has something even better (because it's type safe). Embedded keys!
https://www.jooq.org/doc/latest/manual/code-generation/codegen-embeddable-types/codegen-embedded-keys/

Unlike type aliases, it also works for composite keys
