### ISSUE TITLE
Pagination Helper

### ISSUE THREAD

**Issue by cemremengu** [jOOQ/jOOQ#16022]
### Use case

Although JOOQ recommends using keyset, pagination is still mostly based on limit and offset. JOOQ currently does not provide a helper for this so every time we need pagination, we run  `fetchCount` with the query first and then run query by adding `limit` and `offset`. We currently utilize our own helper class for this but a fluent helper API  provided directly by JOOQ itself can be better.

### Possible solution

I am proposing an API and approach based on [SeaORM ](https://docs.rs/sea-orm/latest/sea_orm/struct.Paginator.html) paginator

A select query will have a method called `paginate` which will take the page size (i.e. limit) and initialize a `Paginator` instance.

`SelectPaginator paginator = db.select().from("mytable").paginate(50)`

`Paginator` API may provide various fetch methods which will take the page index to be fetched (starts from zero) as the argument. I am suggesting 2 of them initially:

`paginator.fetchMaps(0)`

`paginator.fetchInto(0, aClass.class)`

Additionally, the `Paginator` should provide helper methods so that users can build a pagination responses easily:

```
numItems (fetchCount)
numPages (derived from page size and num items)
numItemsAndPages (convenience method when user wants both)
```

There can be methods for iteration as well like `fetch_next` but I am not sure if they are necessary.

Not sure if considered before but I believe this will be a great addition to the library.

### Possible workarounds

Write a wrapper class like :

```
var query = db.select().from("myTable").getQuery()

var paginator = new Paginator(dslContext, query, 10); // we need dslContext for doing `fetchCount`

paginator.fetchInto(0, aClass.class);

// other methods
```

### jOOQ Version

all versions

### Database product and version

relational dbs

**Comment by lukaseder** [comment]
jOOQ won't endorse this approach of calculating total counts first. It is very costly for absolutely no good reason in most applications. While offset pagination can be useful for the first 2-3 pages, it never is useful to reach the last page. Knowing the last page (or even the second last one) is a UX error in my opinion. You could completely omit those buttons from your UI and no one would miss them (e.g. look at Google. They don't offer this functionality). As such, it's a good thing that this is painful for users, so they are motivated to look for alternatives.

All of these ORMs with their paginators seem to offer a silly construct to handle the trivial case, which doesn't really need all that much convenience. What about more complicated queries? As soon as you add more clauses to your query, pagination becomes more complex as this article shows:
https://blog.jooq.org/calculating-pagination-metadata-without-extra-roundtrips-in-sql/

**Comment by cemremengu** [comment]
I think your perception on this topic is a bit emotional and detached from reality to be honest but fair enough. Thanks for your work and taking your time to reply!

**Comment by lukaseder** [comment]
Sure. More detached emotions about this topic here:
https://blog.jooq.org/why-most-programmers-get-pagination-wrong/

I'm already regretting those silly DAOs (that "reality" craves so much), I don't want to regret another similar thing.

It's super easy to build this on top of jOOQ, you can even open source it.
