### ISSUE TITLE
Generated implicit join alias collision when child table foreign keys share the same name

### ISSUE THREAD

**Issue by strindberg** [jOOQ/jOOQ#16111]
### Steps to reproduce the problem

We see unexpected errors in a query where we join several tables used for inheritance: the generated sql gives two of the joined tables the same alias. I have created a MCVE here: https://github.com/strindberg/jooq-simple, branch jooq_issue_16111.

This is the sql definitions:

```sql
create type issue_type as enum ('CONSENT', 'COMPLETE');

create table issue
(
    id              bigint generated by default as identity primary key,
    type            issue_type not null,
    unique (id, type)
);

create table issue_consent
(
    id   bigint     not null primary key,
    type issue_type not null
        constraint type_constraint check (type = 'CONSENT'::issue_type),
    constraint issue foreign key (id, type) references issue (id, type)
);

create table issue_complete
(
    id   bigint     not null primary key,
    type issue_type not null
        constraint type_constraint check (type = 'COMPLETE'::issue_type),
    constraint issue foreign key (id, type) references issue (id, type)
);
```

We generate the jOOQ code with the latest (3.19.2) version, and use this query (obviously our real query does something useful):

```kotlin
        jooq.select(
            row((value(5))).mapping(::Wrapper)
        ).from(
            ISSUE
                .join(ISSUE.issueComplete())
                .join(ISSUE.issueConsent())
        ).fetchValue()
```

This produces the following error:

```
org.jooq.exception.DataAccessException: SQL [select row (?) as "nested"
from "issue"
  join "issue_complete" as "alias_84250150"
    on (
      "alias_84250150"."id" = "issue"."id"
      and "alias_84250150"."type" = "issue"."type"
    )
  join "issue_consent" as "alias_84250150"
    on (
      "alias_84250150"."id" = "issue"."id"
      and "alias_84250150"."type" = "issue"."type"
    )]; ERROR: table name "alias_84250150" specified more than once
```

The MCVE can be run with './gradlew build'. The generated code is included in the repository.

### jOOQ Version

3.19.2

### Database product and version

Postgresql 15

**Comment by lukaseder** [comment]
Thanks for your report. I see how this can happen, it's because the two foreign keys of the child tables share the same name. This didn't risk happening previously, because even if constraints have a per-table namespace (not all RDBMS do this), then going from child to parent would still have only a distinct set of key names per path segment.

But now, with to-many paths available, there's a risk of such collisions. We'll simply have to take the name of the child table into consideration in the computation of this alias.

The workaround is to alias the paths explicitly, e.g.:

```java
jooq.select(
    row((value(5))).mapping(::Wrapper)
).from(
    ISSUE
        .join(ISSUE.issueComplete().as("a"))
        .join(ISSUE.issueConsent().as("b"))
).fetchValue()
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.4 (https://github.com/jOOQ/jOOQ/issues/16116)

Thanks again for your report!

**Comment by lukaseder** [comment]
Note, this fix will re-generate all aliases for to-many paths on all queries, independently of whether there's an ambiguity. This may impact execution plan caching when going live with the fix version.
