### ISSUE TITLE
Mark tags as releases in GitHub repo

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#16112]
### Use case

GitHub provides a repo watch setting that makes it easy to watch repos for releases and see those in the GitHub notification inbox. This is a nice central channel for monitoring dependency upgrades. Integrating jOOQ into this seems like a low hanging fruit and arguably a better user experience that being forced to check a separate mailing list or X account just for announcements.

### jOOQ Version

n/a

### Database product and version

n/a

**Comment by lukaseder** [comment]
I know I have a task for this somewhere. On the other hand, and *even better* channel is @dependabot

**Comment by lukaseder** [comment]
I've added all releases between 3.17.0 and 3.19.3 to https://github.com/jOOQ/jOOQ/releases. I won't document older releases here on github, as 3.16 and earlier is no longer being maintained.

Future releases will be announced here as well.
