### ISSUE TITLE
The Simplest Jooq Config does not work in 3.19.3

### ISSUE THREAD

**Issue by hantsy** [jOOQ/jOOQ#16128]
The fix of https://github.com/jOOQ/jOOQ/issues/16083 introduce a new issue, the simplest config like the following will cause the Gradle build failed.

```koltin 
jooq{
    version = "$jooqVersion"  // the default (can be omitted)
    configuration { } // no executions to name the config
}

```

It will fail the build with following error. 

```bash
 * What went wrong:
Could not determine the dependencies of task ':compileKotlin'.
> Task with path 'jooqCodegenMain' not found in root project 'demo'.
```

Check the Github action build result: https://github.com/hantsy/spring-r2dbc-sample/pull/345

**Comment by lukaseder** [comment]
Thanks for your report. You've already mentioned this:

- https://github.com/jOOQ/jOOQ/issues/16083#issuecomment-1893224706

I've explained there why I don't think this is a bug. What do you expect this to do?

**Comment by hantsy** [comment]
The issue is this configuration succeeded in 3.19.2, but failed in 3.19.3 when running simple build command, `./gradlew clean build -x test`.

My sample project did not refer the task `jooqCodeGen` or `jooqCodeGenMain` in the Gradle build script.

**Comment by lukaseder** [comment]
OK, I checked out your branch that you mentioned earlier:

```
lukas@DESKTOP-F2SE3C1 MINGW64 ~/jOOQ/mcve/spring-r2dbc-sample
$ git fetch origin jooq-3.19.3-config
From https://github.com/hantsy/spring-r2dbc-sample
 * branch            jooq-3.19.3-config -> FETCH_HEAD

lukas@DESKTOP-F2SE3C1 MINGW64 ~/jOOQ/mcve/spring-r2dbc-sample
$ git checkout jooq-3.19.3-config
Switched to a new branch 'jooq-3.19.3-config'
branch 'jooq-3.19.3-config' set up to track 'origin/jooq-3.19.3-config'.
```

Then ran this:

```
lukas@DESKTOP-F2SE3C1 MINGW64 ~/jOOQ/mcve/spring-r2dbc-sample
$ cd jooq-kotlin-co-gradle/

lukas@DESKTOP-F2SE3C1 MINGW64 ~/jOOQ/mcve/spring-r2dbc-sample/jooq-kotlin-co-gradle
$ ll
total 26
-rw-r--r-- 1 lukas 197121 7207 Jan 23 13:10 build.gradle.kts
drwxr-xr-x 1 lukas 197121    0 Jan 23 13:08 gradle
-rw-r--r-- 1 lukas 197121  106 Jan 23 13:08 gradle.properties
-rwxr-xr-x 1 lukas 197121 8692 Jan 23 13:08 gradlew
-rw-r--r-- 1 lukas 197121 2868 Jan 23 13:08 gradlew.bat
-rw-r--r-- 1 lukas 197121   26 Jan 23 13:08 settings.gradle.kts
drwxr-xr-x 1 lukas 197121    0 Jan 23 13:08 src

lukas@DESKTOP-F2SE3C1 MINGW64 ~/jOOQ/mcve/spring-r2dbc-sample/jooq-kotlin-co-gradle
$ ./gradlew clean build -x test
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileKotlin'.
> Task with path 'jooqCodegenMain' not found in root project 'demo'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 27s
```

You have this in your `build.gradle.kts`:

```
tasks.withType<KotlinCompile> {
    dependsOn("jooqCodegenMain") // This right here. Remove "Main", as I said earlier.
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict", "-opt-in=kotlin.RequiresOptIn")
        jvmTarget = "21"
    }
}
```

There's no such task as `jooqCodegenMain`, *unless* you declare an `execution` called `main`, as per the documentation:

https://www.jooq.org/doc/latest/manual/code-generation/codegen-gradle/

I haven't documented too much about this plugin yet (see https://github.com/jOOQ/jOOQ/issues/16087), but I did document this:

<img width="861" alt="image" src="https://github.com/jOOQ/jOOQ/assets/734593/3ecada10-6648-4c6d-a780-6c170637de71">

You can also try running `gradlew tasks` on your own project, as I had suggested:

```
lukas@DESKTOP-F2SE3C1 MINGW64 ~/jOOQ/mcve/spring-r2dbc-sample/jooq-kotlin-co-gradle
$ ./gradlew tasks | grep jooq
jooqCodegen - jOOQ code generation for all executions
```

There's only this particular task, the task that runs *all* the executions (or the default configuration in the absence of executions).

Does this clarify things?

**Comment by lukaseder** [comment]
Just to be *very* clear: Remove `Main` here:
https://github.com/hantsy/spring-r2dbc-sample/blob/jooq-3.19.3-config/jooq-kotlin-co-gradle/build.gradle.kts#L84

And write this instead:

```kotlin
dependsOn("jooqCodegen")
```

**Comment by hantsy** [comment]
Thanks for pointing out the issue.
