### ISSUE TITLE
Add support for STORED computed columns in `alterColumn`

### ISSUE THREAD

**Issue by felixscheinost** [jOOQ/jOOQ#16120]
### Use case

I would like to issue the following query using jOOQ:

```SQL
ALTER TABLE table
MODIFY COLUMN some_column INT GENERATED ALWAYS AS (...) STORED;
```

I want to maintain the complex compute expression in code and update it on startup of the application.

I tried something like the following:

```java
      dslContext.alterTable(TABLE)
        .alterColumn(TABLE.SOME_COLUMN)
        .set(
          TABLE.SOME_COLUMN.dataType
            .generatedAlwaysAs(...)
            .stored()
        )
        .execute()
```

But that didn't seem to work. Seems like the `GENERATE ALWAYS AS` is currently only rendered for `ADD COLUMN` and not for `MODIFY COLUMN`?

Thanks in advance!

### Possible solution

Could jOOQ support rendering the `GENERATE ALWAYS AS`? 

Did I try the wrong way? I couldn't find any examples of generateAlwaysAs + alterColumn.

### Possible workarounds

I considered using `dropColumn` + `addColumn`. When coupled with droppping and recreating indices this could even have performance benefits probably.

### jOOQ Version

jOOQ Professional 3.17.19

### Database product and version

MariaDB 10.6.10

### Java Version

Corretto 17

### OS Version

macOS 14.2

### JDBC driver name and version (include name if unofficial driver)

org.mariadb.jdbc:mariadb-java-client:3.2.0

**Comment by lukaseder** [comment]
Thanks for your feature request. We have an open issue for this here:

- https://github.com/jOOQ/jOOQ/issues/12665

**Comment by felixscheinost** [comment]
Sorry I missed that when looking for existing issues. Thanks!

**Comment by lukaseder** [comment]
No worries
