### ISSUE TITLE
How do I get an array (or list/set) of `TableField`s of a table?

### ISSUE THREAD

**Issue by oliveryasuna** [jOOQ/jOOQ#16201]
### Your question

The following inheritance exists for all generated table classes: `MyTable <- AbstractTable <- Table <- Fields`.

The `Fields` class offers the `Field<?>[] fields()` method. What surprises me is that, throughout this inheritance, there is no method such as `TableField<R, ?>[] tableFields()`.

We can do the following:

```java
final Field<?>[] fields = table.fields();
```

Or the following:

```java
final TableField<RECORD, ?>[] tableFields = Arrays.stream(table.fields())
        .map(field -> (TableField<RECORD, ?>)field)
        .toArray(TableField[]::new);
```

**But not the following:**

```java
final List<TableField<RECORD, ?>> tableFieldList = Arrays.stream(table.fields())
        .map(field -> (TableField<RECORD, ?>)field)
        .toList();
```

This makes sense because of Java's type-erasure. It seems that there _should_ exist a `TableField<R, ?>[] tableFields()` method in `Table`.

Here is my current workaround:

```java
final List<TableField<RECORD, ?>> tableFieldList = List.of(Arrays.stream(table.fields())
        .map(field -> (TableField<RECORD, ?>)field)
        .toArray(TableField[]::new));
```

### jOOQ Version

3.19.3

### Database product and version

Irrelevant

### Java Version

Irrelevant

### OS Version

Irrelevant

### JDBC driver name and version (include name if unofficial driver)

Irrelevant

**Comment by lukaseder** [comment]
Thanks for your message.

There had once been a feature request on the roadmap, which was rejected primarily for backwards compatibility reasons:

- https://github.com/jOOQ/jOOQ/issues/3971

Note that the change isn't just about providing a collection of `TableField`,  but also about looking up individual `TableField` instances. So, either we do covariant overrides (backwards incompatible), or offer new API (tons of new methods). Neither is very compelling, especially given how rare this request is.

I don't recall whether the change was possible or not (i.e. there might be some `Table` types where returning collections of `TableField` isn't possible).

Why do you need this?

**Comment by lukaseder** [comment]
To answer your question: Your workaround is the only way, currently.

**Comment by oliveryasuna** [comment]
@lukaseder Is there any reason you could not add the proposed method `tableFields()` to `Table`? It would be backwards-compatible, would it not?

**Comment by lukaseder** [comment]
I don't think anything new has come up since my last comment?
https://github.com/jOOQ/jOOQ/issues/16201#issuecomment-1926390879
