### ISSUE TITLE
multi table queries, the result is not incorrect

### ISSUE THREAD

**Issue by 2308502963** [jOOQ/jOOQ#16207]
### Use case

when I am using multi table queries，like this:
```sql
dslContext.select(T_TEMPLATE, T_ORGAN.NAME.as("orgName"))
                .from(T_TEMPLATE).innerJoin(T_ORGAN).on(T_ORGAN.ID.eq(T_TEMPLATE.ORG_ID))
                .fetchOneInto(TemplateResp.class);
```
the query result is incorrect.
so, is this way is not incorrect or not support?

### jOOQ Version

jooq:3.18.4

### Database product and version

maraisdb 11.3.1

### Java Version

jdk17

### OS Version

windows11

**Comment by lukaseder** [comment]
Thanks for your message. Your query nests the `T_TEMPLATE` table into a nested record, see:

- https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/nested-records/
- https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/select-clause/select-clause-table/

You probably didn't want that. What you probably wanted is to project a flat result set like this:

```java
dslContext.select(T_TEMPLATE.fields())
          .select(T_ORGAN.NAME.as("orgName"))
```

I hope this helps
