### ISSUE TITLE
Manual gradle codegen examples use wrong property name for boolean properties when using jOOQ-codegen-gradle with kotlin

### ISSUE THREAD

**Issue by danielstravito** [jOOQ/jOOQ#16213]
### The documentation URL

https://www.jooq.org/doc/3.19/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-enum-converter/

### Feedback

The suggested way of using enum converter is via:

```
        forcedType {

          // Specify the Java type of your custom type. This corresponds to the Converter's <U> type.
          userType = "com.example.MyEnum"

          // Apply the built in org.jooq.impl.EnumConverter.
          enumConverter = true

          // A Java regex matching fully-qualified columns, attributes, parameters. Use the pipe to separate several expressions.
          includeExpression = ".*\\.MY_STATUS"
        }
```

But this results in the following with 3.19.3:
```
  Line 60:                                                                      enumConverter = true
                    ^ Cannot access 'enumConverter': it is protected in 'ForcedTypeExtension'
```

Changing `enumConverter` to `isEnumConverter` fixes the compilation error.

**Comment by lukaseder** [comment]
Thanks a lot for your report. Other properties are affected too, in other manual pages, e.g.

<img width="618" alt="image" src="https://github.com/jOOQ/jOOQ/assets/734593/aa1d2bdb-2fa6-4c55-9d7f-737d6689da9e">

This code is generated automatically from the XML, so it should be an easy, thorough fix.

**Comment by lukaseder** [comment]
The manual will be updated within 2-3h. Thanks again for your report!

**Comment by danielstravito** [comment]
Oh noes, you overdid it:

```

configuration {
  isGenerator {
    isDatabase {
      isForcedTypes {
        isForcedType {
```
