### ISSUE TITLE
Does JOOQ support postgresql Jsonb "?|" operator

### ISSUE THREAD

**Issue by SubbuSPS** [jOOQ/jOOQ#16214]
### Your question

Need the solution to implement below query in JOOQ

select * from sampletable s  where s.fromportjson-> 'FromPort' ?| ARRAY['KEMBA','TZDAR'] and s.toportjson-> 'ToPort' ?| ARRAY['CLANF','TZTGT']

Sample data 
1. For column fromportjson is "{"FromPort": ["KEMBA", "CLARI", "TZDAR"]}" 
2. For column toportjson is "{"ToPort": ["CLANF", "CLARI", "CLBAR"]}" 

### jOOQ Version

3.19.3

### Database product and version

PostgreSQL 16.1

### Java Version

java 11

**Comment by lukaseder** [comment]
Thanks for your message. See also the answer given here:

- https://stackoverflow.com/q/38340086/521799
