### ISSUE TITLE
pgvector support

### ISSUE THREAD

**Issue by michaeldlfx** [jOOQ/jOOQ#16220]
### Use case

I love using jOOQ with PostgreSQL, so thank you for this awesome project 🎉 

I would love to see type safe DSL support for the [pgvector](https://github.com/pgvector/pgvector) extension to support AI use cases.

Maybe this can serve as an inspiration?

https://docs.spring.io/spring-ai/reference/api/vectordbs/pgvector.html

Looking forward to hearing from you,

Thanks again,

Michael

### Possible solution

- https://github.com/pgvector/pgvector-java

### jOOQ Version

Latest

### Database product and version

PostgreSQL  15.5

### Java Version

21 

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.1

**Comment by lukaseder** [comment]
Thanks for your suggestion.

It's unlikely this will currently be prioritised. After many years of getting upvotes on other extensions, eventually some support was added for things like `RANGE` types, `INET` types, `CITEXT`, `HSTORE` in: https://github.com/jOOQ/jOOQ/tree/main/jOOQ-postgres-extensions

These are popular extensions. `pgvector` probably needs a lot more time to get adoption.

But of course, you can easily publish your own extensions module, similar to the one above if you think others will benefit.

**Comment by michaeldlfx** [comment]
Alright, thanks for the swift reply! Do you have a recommendation for an extension I can have a look at to get an idea how to implement a great jOOQ extension?

**Comment by lukaseder** [comment]
Look at https://github.com/jOOQ/jOOQ/tree/main/jOOQ-postgres-extensions

**Comment by michaeldlfx** [comment]
Cool, thanks! 👍
