### ISSUE TITLE
How do I OR together a literal and the value of a column on onConflict?

### ISSUE THREAD

**Issue by reubenfirmin** [jOOQ/jOOQ#16244]
### Your question

When updating in an insert onconflict, I want to set X to true if either Table.X is true or the "x" literal param is passed in as true. I.e. something like:

```
.onConflict()
.doUpdate(Table.X, or(value(Table.X), x))
```

I couldn't find anything either in the manual or browsing through code completion that addresses this scenario. Is it supported? Thanks!

### jOOQ Version

Jooq open source 3.18.6

### Database product and version

Postgres 15

### Java Version

OpenJDK version 17

### OS Version

Ubuntu 23.10

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by reubenfirmin** [comment]
Ah, it appears that:

``` .set(Table.X, if (x) { inline(true) } else { Table.X })```

does the right thing. Maybe.

**Comment by lukaseder** [comment]
You wrapped the wrong expression with `DSL.value()`. Do this instead:

```kotlin
or(Table.X, value(x))
```
