### ISSUE TITLE
Oracle to Postgres query translation: sysdate is not converted to current_timestamp

### ISSUE THREAD

**Issue by EvgenyMilenin** [jOOQ/jOOQ#16253]
### Expected behavior

On this page https://www.jooq.org/translate/ select Input Dialect - Oracle, Output- Postgres. Try to convert this query:
`select trunc(sysdate) from dual`

It it should be 
`SELECT date_trunc('day', CURRENT_TIMESTAMP)`

### Actual behavior

Output is
`SELECT date_trunc('day', sysdate)`

### Steps to reproduce the problem

On this page https://www.jooq.org/translate/ select Input Dialect - Oracle, Output- Postgres.

### jOOQ Version

N/A

### Database product and version

N/A

### Java Version

N/A

### OS Version

N/A

### JDBC driver name and version (include name if unofficial driver)

N/A

**Comment by lukaseder** [comment]
Thanks for your report. This is a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/9716
