### ISSUE TITLE
JavaGenerator doesn't generate serialVersionUID in Path classes

### ISSUE THREAD

**Issue by norrisjeremy** [jOOQ/jOOQ#16254]
### Expected behavior

jOOQ should respect the `generatedSerialVersionUID` generator option and generate a `serialVersionUID` for the new `org.jooq.Path` implementing inner classes.

For example, if I have `<generatedSerialVersionUID>CONSTANT</generatedSerialVersionUID>` configured, then I should see something like this generated:
```
public class Xyz extends TableImpl<XyzRecord> {

    private static final long serialVersionUID = 1L;
    ...

    public static class XyzPath extends Xyz implements Path<XyzRecord> {

        private static final long serialVersionUID = 1L;
        ...
    }
}
```

### Actual behavior

However, in the new jOOQ 3.19,  if I have `<generatedSerialVersionUID>CONSTANT</generatedSerialVersionUID>` configured, then I instead see this:
```
public class Xyz extends TableImpl<XyzRecord> {

    private static final long serialVersionUID = 1L;
    ...

    public static class XyzPath extends Xyz implements Path<XyzRecord> {

        // No serialVersionUID field is present here
        ...
    }
}
```

This in turn leads to Java compiler warnings, which causes build failures for us since we run with `-Werror`:
```
[WARNING] /.../src/main/java/.../tables/Xyz.java:[115,18] [serial] serializable class XyzPath has no definition of serialVersionUID
```

### Steps to reproduce the problem

Run the jOOQ Java code generator, for example via the `jooq-codegen-maven` Maven plugin:

```
mvn jooq-codegen:generate
```

Generator config:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.19.2.xsd">
    <jdbc>
        <driver>com.mysql.cj.jdbc.Driver</driver>
        <url>jdbc:mysql://w.x.y.z:3306/</url>
        <user>...</user>
        <password>...</password>
    </jdbc>
    <generator>
        <database>
            <name>org.jooq.meta.mysql.MySQLDatabase</name>
            <includes>xyz</includes>
            <excludes></excludes>
            <schemata>
                <schema>
                    <inputSchema>test</inputSchema>
                </schema>
            </schemata>
        </database>
        <generate>
            <pojos>true</pojos>
            <fluentSetters>true</fluentSetters>
            <pojosEqualsAndHashCode>true</pojosEqualsAndHashCode>
            <generatedSerialVersionUID>CONSTANT</generatedSerialVersionUID>
        </generate>
        <target>
            <packageName>a.b.c</packageName>
            <directory>src/main/java</directory>
        </target>
    </generator>
</configuration>
```

### jOOQ Version

3.19.3

### Database product and version

MySQL

### Java Version

openjdk version "21.0.2" 2024-01-16 LTS

### OS Version

n/a

### JDBC driver name and version (include name if unofficial driver)

com.mysql:mysql-connector-j:8.3.0

**Comment by lukaseder** [comment]
Thanks a lot for your report. That's an oversight indeed. Will fix right away.
