### ISSUE TITLE
dslContext.selectCount().from(TABLE).fetchOneInto(Integer.class) -> Warning Of NullpointerException

### ISSUE THREAD

**Issue by eyabc** [jOOQ/jOOQ#16255]
### Your question

hello? I am a Korean developer who loves Jooq. I am always grateful to use it.
This is my first time using a repository while using Jooq for 3 years. I'm not good at Korean, but I'm asking questions using Google Translate. Please understand.

Use the dslContext.selectCount().from(TABLE).fetchOneInto(Integer.class) statement.
When using FetchOneInto, there are usually no records matching the condition.
I know there is a possibility of NullpointerException being thrown.
In this case, I don't think a runtime error occurs because count always returns 0 if there are no records matching the condition.

@SuppressWarnings("ConstantConditions")
Is it possible to modify the development so that there is no Warning in the case of using selectCount() in the Jooq library without using ?

Thanks for reading.

### jOOQ Version

3.17.0

### Database product and version

Mysql 8.0.29

### Java Version

17

### OS Version

Mac 14.1.1

### JDBC driver name and version (include name if unofficial driver)

org.springframework.boot:spring-boot-starter-data-jdbc:2.7.6

**Comment by lukaseder** [comment]
You can use `fetchSingleInto()` instead of `fetchOneInto()`. In jOOQ `fetchOne()` means 0-1 records, whereas `fetchSingle()` means exactly 1 record (or a `NoDataFoundException`).

**Comment by eyabc** [comment]
You gave an amazing answer. Thank you so much. I hope to make friends with the repository of jooq. 😊
