### ISSUE TITLE
Remove unnecessary up-to-date prevention in jOOQ-codegen-gradle plugin

### ISSUE THREAD

**Issue by mklnwt** [jOOQ/jOOQ#16275]
### Use case

When using migration files or a migration tool (i.e. Liquibase) the Gradle jOOQ code generation is running on every re-compilation.

It is possible to add the migration files to the inputs of the Gradle task, but due to `getOutputs().upToDateWhen(task -> false);` the task will never be `UP-TO-DATE`.

This can also not be circumvented with adding custom `upToDateWhen` to the task on usage site.

### Possible solution

Since jOOQ is generating the outputs into a separate folder, it is possible to utilize Gradle's fingerprinting to check if the files have changed.

Properly implement this.
```kotlin
// TODO: Can we optimise this without using internals?
getOutputs().upToDateWhen(task -> false);
```

At least give the option to disable this behavior via a flag/property so custom or default `upToDateWhen` can be used.

### Possible workarounds

It is possible to manually prevent the task from running again by using `onlyIf { ... }`.
For this it would be necessary to manually check fingerprinting though.

### jOOQ Version

jOOQ OSS 3.19.1

### Database product and version

PostgreSQL 15

### Java Version

17

### OS Version

Windows 11

**Comment by lukaseder** [comment]
Thanks for your suggestion.

> Properly implement this.

How, specifically?

> At least give the option to disable this behavior via a flag/property so custom or default `upToDateWhen` can be used.

I'd rather solve this properly rather than adding more flags / properties that need documentation etc.

**Comment by mklnwt** [comment]
Usually Gradle should be able to take care of the up-to-date check. So just removing the line should actually return to the default behaviour of fingerprinting the output and comparing it to the previous output fingerprint.

I don't know what the intention of adding this check was, so I can't tell you how to implement this.

**Comment by lukaseder** [comment]
> I don't know what the intention of adding this check was, so I can't tell you how to implement this.

Frankly, I don't remember. I'll just remove the statement then.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.4 (https://github.com/jOOQ/jOOQ/issues/16294)

**Comment by lukaseder** [comment]
Apparently, just removing the statement is even worse:

- https://github.com/jOOQ/jOOQ/issues/16316

**Comment by lukaseder** [comment]
I'll revert this change and release 3.19.5 right away. The change was definitely not good. Between generating too often and not generating at all, the former is clearly the lesser evil.

I'll think about how to make the plugin aware of flyway or liquibase inputs again.

**Comment by lukaseder** [comment]
I've created a new issue to think about a proper implementation:

- https://github.com/jOOQ/jOOQ/issues/16318
