### ISSUE TITLE
Document ARRAY_APPEND and ARRAY_PREPEND functions

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#16274]
### Your question

For a table `t` containing a `text[]` `a` what would be the jOOQ equivalent of

```sql
update t set a = a || 'New Array Element'::text where t.id = 123
```

I couldn't find any reference to this in the manual or issue tracker.

### jOOQ Version

3.19.3

### Database product and version

PostgreSQL 15.3

**Comment by axelfontaine** [comment]
Never mind. Solved it by using a function instead of the operator:

```kotlin
jooq.update(T).set(T.A, DSL.arrayAppend(T.A, value)).where(T.ID.eq(id)).execute()
```

It may be worth adding some info about `array_append` and ideally also the `||` operator somewhere under https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/array-functions/

**Comment by lukaseder** [comment]
> It may be worth adding some info about `array_append` and ideally also the `||` operator somewhere under https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/array-functions/

Thanks, yes I will do that, seems to have been an oversight.

**Comment by lukaseder** [comment]
Ah no, it's here: https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/array-functions/array-concat-function/

So, what's missing in your opinion? Something like putting "ARRAY_CONCAT (|| operator) in the title?

**Comment by lukaseder** [comment]
Ah yes, I'm sorry, I misread.

> An example with `update`, while not strictly necessary, would also be a nice addition to show it applies beyond `select`.

I'd rather not. It's not related. People keep asking about adding unrelated examples to `update` (e.g. how to update `X = X + 1`. We'd have a 50 page manual about update alone :)

**Comment by lukaseder** [comment]
The functions were added in jOOQ 3.18:

- https://github.com/jOOQ/jOOQ/issues/11981

**Comment by lukaseder** [comment]
Fixed. The manual will be re-deployed in 2-3h
