### ISSUE TITLE
Allow for specifying inputs to the gradle CodegenTask in order to participate in incremental builds

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16318]
It's currently not possible to tell the `jOOQ-codegen-gradle` plugin what its inputs are, it always assumes its outputs aren't up to date. See also:

- https://github.com/jOOQ/jOOQ/issues/16275
- https://github.com/jOOQ/jOOQ/issues/16316

It would be useful to make the plugin aware of:

- Liquibase
- Flyway
- Other inputs in some way

**Comment by mklnwt** [comment]
@lukaseder the issue is in using the output to decide whether to update or not.
Gradle itself can clearly decide if the output has changed (i.e. file removed).

In this case you want to use the input to make the decision.

**Comment by ThoSap** [comment]
Like the inputs where declared in the unofficial jOOQ Gradle plugin:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/v9.0/example/configure_jooq_with_flyway/build.gradle#L62-L68

**Comment by lukaseder** [comment]
The "unofficial" jOOQ Gradle plugin can still be used if it is preferred. There's no obligation to do everything like it did.

In this specific case, I think there's a better solution, one that knows more about jOOQ code generation.

- The default is to assume outputs are never up to date (because we don't know)
- If we're using the `DDLDatabase`, `XMLDatabase`, `JPADatabase` then the inputs are known to jOOQ and can be used by the gradle plugin
- If we're using Flyway or Liquibase (the most popular database change management utilities), then there's a possibility to auto-detect their outputs somehow (I'll have to investigate what their gradle plugins are doing)

**Comment by mklnwt** [comment]
The default should assume that the inputs are never up-to-date, not the outputs.
The output check is there to make sure the files outputted by the code generation haven't been deleted or modified.

Otherwise I agree, the input checks should only trigger when using one of the file based generation.

**Comment by lukaseder** [comment]
> The default should assume that the inputs are never up-to-date, not the outputs.

Thanks for the correction. We're all referring to this particular statement in `CodegenTask`:

```java
getOutputs().upToDateWhen(task -> false);
```

So, I suspect that we're saying the same thing, yes?

**Comment by mklnwt** [comment]
The logic should be something like this:

```Kotlin
// Only if the generation is targeted against an actual database set this:
getOutputs().cacheIf(task -> isGenerationFromFile || isGenerationFromMigrationTool)

// DDLDatabase, XMLDatabase, JPADatabase
// add files to input

// Database migration tools
// depend on migration tool inputs/files
```

Don't use `getOutputs().upToDateWhen(task -> false);`. It's only meant for checking if the generated files have changed.

**Comment by xenomachina** [comment]
My understanding is that:

- `upToDateWhen` determines whether the **previous** output can be reused for this current execution.

- `cacheIf` determines whether the **current** output should be saved in the build cache for possible use in future executions.

In the case of jOOQ, I think it would be ideal to have two "modes", and use both of these methods, but in only one of these modes:

- **Non-deterministic**: The output can change for reasons that Gradle is unaware of.

  The previous output cannot be reused so it should use `upToDateWhen { task -> false }`.

  The current output also can never be reused, so there is no point in caching it, so it should use `cacheIf{ task -> false }`.

- **Deterministic**: The output is determined entirely by the task's inputs that Gradle is aware of.

  Gradle's default behavior is correct for this mode: it'll only reuse the previous output if there has been no change to the task inputs (ie: the input file locations, the contents of these input files, and input properties) and it'll cache the output for possible future use. Neither `upToDateWhen` or `cacheIf` need be called in this mode.

To select between these two modes, the task's constructor can use the presence of input files (or directories). ie:

- No input files ⇒ Non-deterministic

- One or more input files ⇒ Deterministic

If the user doesn't know **all** of their inputs, then they shouldn't specify **any**, and they'll get the safe-but-slow non-deterministic mode.

Conversely, the only reason to specify inputs is if you're going to specify all of them, in which case the more efficient deterministic mode should be correct.

**Comment by mklnwt** [comment]
@xenomachina that sums it up really well.

I would still say it's not necessary to use `upToDateWhen`.

If you're using **Non-deterministic**, `cacheIf` from the previous run will be `false` anyway and the output won't be cached. There's no need to also set `upToDateWhen`.

Even better would be to create a cacheable and a non-cacheable task depending on the scenario (files/migration tools vs db).

Maybe setting `cacheIf` as `false` to go into **Deterministic** mode if the inputs are empty like you suggested could also work. Then the user could provide their own inputs if they wanted to add their own caching strategy. This could also enable strategies that rely on a timestamp or checksum as well.

Forcefully setting `upToDateWhen` to `false` (even if **Non-deterministic** shouldn't be cached) prevents users from overriding the behaviour with their own up-to-date check.

> You can add multiple such predicates. The task outputs cannot be reused when any predicate returns false.

**Comment by martinqcz** [comment]
> Forcefully setting upToDateWhen to false (even if Non-deterministic shouldn't be cached) prevents users from overriding the behaviour with their own up-to-date check.

@lukaseder The problem is that outputs.upToDateWhen() is adding the condition to Gradle's AndSpec() so if the plugin sets it to false there is no way how to override it in the build script.
In my case I know I'm that I'm using flyway and all inputs for flyway are in one folder, so I could set the folder as inputs.dir telling the Gradle to execute the jooqCodegen task only if my migration files changed, but because the plugin sets upToDateWhen to false, it does not work.

**Comment by mklnwt** [comment]
Assuming this is our configuration

```kotlin
configure<org.jooq.codegen.gradle.CodegenPluginExtension> {
    configuration {
        generator {
            name = "org.jooq.codegen.KotlinGenerator"
            database {
                name = "org.jooq.meta.extensions.liquibase.LiquibaseDatabase"
                properties {
                    property {
                        key = "rootPath"
                        value = "$projectDir/src/main/resources/liquibase"
                    }
                    property {
                        key = "scripts"
                        value = "liquibase.xml"
                    }
                    property {
                        key = "defaultNameCase"
                        value = "lower"
                    }
                }
            }
        }
    }
}
```

Declaring the `CodegenTask` for file based generation (i.e. Liquibase) with the following should work.
```
val rootPath = TODO("This has to be acquired") // src/main/resources/liquibase
inputs.dir(layout.dir(rootPath))

val generatedJooqSources = TODO("This has to be acquired") // generated-sources/jooq
outputs.dir(layout.buildDirectory.dir(generatedJooqSources))
```

Then it would make sense to hint in the documentation on how to disable build cache and how to specify additional inputs if scripts are outside of the `rootPath`.

**Comment by ollin** [comment]
Hello @lukaseder , we have the same situation as @martinqcz . We could (and want to) control when the generation is executed and currently have no possibility. Our steps are flyway -> postgres -> jooq -> classes. I.e. we only want to execute when the flyway files have changed. Using Flyway directly as the basis for generation is not an option for us because we use Postgres-specific things that H2 does not provide in memory.

**Comment by martinqcz** [comment]
@lukaseder 
Correct solution that is in line with Gradle's philosophy and recommendations how to write plugins is to create two plugins. One base plugin that contains all the logic, but without any too specific irevertible configuration. Second plugin then can apply the base plugin and add some opinionated configuration like setting `upToDateWhen` if needed. 
Then if someone has different needs or use case and the opinionated plugin configuration does not work for him, there is still possibility to use the base plugin and configure it differently.
So please change the Gradle plugin to be as good as the jOOQ library itself. I have exactly the same use case as @ollin where in memory H2 does not work.

**Comment by lukaseder** [comment]
> Correct solution that is in line with Gradle's philosophy and recommendations how to write plugins is to create two plugins.

@martinqcz Please point to said philosophy and recommendations.

> Then if someone has different needs or use case and the opinionated plugin configuration does not work for him, there is still possibility to use the base plugin and configure it differently.

That sounds like most people are going to do their own thing anyway, yes? What are 10 lines of official jOOQ plugin good for, if it will never suit anyone's needs?

> So please change the Gradle plugin to be as good as the jOOQ library itself. I have exactly the same use case as @ollin where in memory H2 does not work.

I understand this use-case. Eventually, this will be addressed. Good things come to those who wait.

**Comment by martinqcz** [comment]
> @martinqcz Please point to said philosophy and recommendations.

It written [here](https://docs.gradle.org/current/userguide/implementing_gradle_plugins_binary.html#capabilities-vs-conventions) and `java-base` and `java` plugins are perfect example of this approach.


> That sounds like most people are going to do their own thing anyway, yes? What are 10 lines of official jOOQ plugin good for, if it will never suit anyone's needs?

People can choose between base and opinionated plugin, default may be still the opinionated one like the `java` plugin itself. Most project use java and only minority needs special handling so they apply just `java-base`.

> I understand this use-case. Eventually, this will be addressed. Good things come to those who wait.
I created [PR](https://github.com/jOOQ/jOOQ/pull/16817) where there are two plugins.

**Comment by lukaseder** [comment]
> It written [here](https://docs.gradle.org/current/userguide/implementing_gradle_plugins_binary.html#capabilities-vs-conventions) and `java-base` and `java` plugins are perfect example of this approach.

Thanks for the pointer. The way this is written, I see this as an idea, not as a strong recommendation, or even a must have. I'll keep it in the back of my mind, or you can create an issue for this, and people can then discuss *actual* benefits. Until *actual* benefits and use-cases arise, I prefer not to complicate things any further at this point.

Always also think of new users and non-power users, who will be overwhelmed by choice.

> People can choose between base and opinionated plugin, default may be still the opinionated one like the `java` plugin itself. Most project use java and only minority needs special handling so they apply just `java-base`.

But to me, this sounds like art for art's sake at this point. In all the years where the Maven plugin existed, no one requested such configurability from it. I don't see why you'd expect this to happen here, yet.

Given that you're mentioning this specifically in light of this up-to-date output logic, I do believe that the plugin can be opinionated about this topic, because the different ways of generating jOOQ code aren't infinite. There's basically:

- jOOQ is entirely in charge of managing inputs/outputs (e.g. `DDLDatabase`, `JPADatabase`, `XMLDatabase`)
- jOOQ isn't entirely in charge of managing inputs/outputs (e.g. `PostgresDatabase`)
  - But gradle might know about this (e.g. using Flyway / Liquibase)
  - And gradle doesn't know about this (external migration, probably rare)

I don't want to overengineer things. The simpler, the better.

**Comment by lukaseder** [comment]
Regarding @xenomachina's comment here:

https://github.com/jOOQ/jOOQ/issues/16318#issuecomment-2040853333

> To select between these two modes, the task's constructor can use the presence of input files (or directories). ie:
> 
> * No input files ⇒ Non-deterministic
> * One or more input files ⇒ Deterministic

If this is expected to be sufficient, we'll still have to check the types of input files. E.g. these are input files as well:

```
C:\Users\lukas\.m2\repository\org\jooq\trial\jooq-meta-extensions\3.20.0-SNAPSHOT\jooq-meta-extensions-3.20.0-SNAPSHOT.jar
C:\Users\lukas\.m2\repository\org\jooq\trial\jooq-meta\3.20.0-SNAPSHOT\jooq-meta-3.20.0-SNAPSHOT.jar
C:\Users\lukas\.m2\repository\com\h2database\h2\2.2.224\h2-2.2.224.jar
C:\Users\lukas\.m2\repository\org\jooq\trial\jooq\3.20.0-SNAPSHOT\jooq-3.20.0-SNAPSHOT.jar
C:\Users\lukas\.m2\repository\jakarta\xml\bind\jakarta.xml.bind-api\4.0.1\jakarta.xml.bind-api-4.0.1.jar
C:\Users\lukas\.m2\repository\io\r2dbc\r2dbc-spi\1.0.0.RELEASE\r2dbc-spi-1.0.0.RELEASE.jar
C:\Users\lukas\.m2\repository\jakarta\activation\jakarta.activation-api\2.1.2\jakarta.activation-api-2.1.2.jar
C:\Users\lukas\.m2\repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar
```

It makes sense to consider the classpath as "input" to the plugin. When the classpath changes (e.g. jOOQ version upgrade), then code must be re-generated even without any migration taking place.

**But**, if the only inputs are classpath, and no migration scripts, then it's safe to assume we don't know whether outputs are up to date.

I do like the simplicity of just being able to specify additional inputs, though, without having to specify additional flags. I specifically agree with this assumption:

> If the user doesn't know **all** of their inputs, then they shouldn't specify **any**, and they'll get the safe-but-slow non-deterministic mode.
> 
> Conversely, the only reason to specify inputs is if you're going to specify all of them, in which case the more efficient deterministic mode should be correct.

Even if they're deliberately not specifying all of their inputs, we should assume that this is deliberate. E.g. there could be a file containing a version number, irrespective of the actual migration files, so that version number could be the entire input, e.g. as a hack to prevent a migration / re-generation

**Comment by lukaseder** [comment]
A trickier question is whether input properties should be considered. Our plugin itself declares:

```java
    @Input
    public Provider<String> getInput() {
        return providers.provider(() ->
            configuration.getConfiguration().toString()
        );
    }
```

Obviously, whenever the configuration changes, we must re-generate as well.

It's possible for users to declare their own inputs only in form of properties, too, e.g. again a version number property. They might expect a re-generation to take place *only* whenever that property changes.

I now understand why Etienne's plugin just has a flag that allows for making things *very clear*, without any room for misinterpretation of any inputs. I'm not sure why his plugin doesn't also use `cacheIf()`, though. But it does look like depending only on input heuristics will be too risky, as there are too many possible edge cases where we can't really know what input we can reasonably ignore for such a caching decision.

**Comment by lukaseder** [comment]
OK, I think we're set. I'm going with a slightly adapted version of @xenomachina's suggestion:

1. By default, we don't cache things, because we can't make any assumptions about the meta data source
2. An exception to this are our own "interpreting" databases, which can provide inputs to the tasks automatically. I've extracted this idea into a new issue: https://github.com/jOOQ/jOOQ/issues/16818
3. If users provide explicit inputs to the task, then we assume we can safely cache things (previously mentioned inputs, including classpath, and our own properties, are assumed to be ignorable)
4. In case this logic is wrong due to an overlooked edge case, and thus we cache too eagerly, there will be a property that can be turned off explicitly:

    ```kotlin
    tasks.named("jooqCodegen") {
        dependsOn(tasks.named("flywayMigrate"))
        // We provide inputs for some reason
        inputs.files(fileTree("src/main/resources/db/migration"))
        // Yet, we don't want these inputs to be considered as a reason to enable caching
        setProperty("caching", false)
    }
    ```

**Comment by lukaseder** [comment]
Fun fact, when a task is up to date, then its actions (e.g. `doFirst()`) aren't executed. Thus, we don't have a source set 🫠.

This gift will keep giving.

**Comment by lukaseder** [comment]
That's probably a similar problem as the one mentioned here:

- https://github.com/jOOQ/jOOQ/issues/16088
- https://groups.google.com/g/jooq-user/c/WYKlwguBHwE

Will try to continue chasing this down, soon.

**Comment by mklnwt** [comment]
@lukaseder the problems with up-to-date checks is not down to the source set(s).
There might be a follow-up issue, but generally speaking the inputs are the bigger problem at hand.

Clearly setting `getOutputs().upToDateWhen(task -> false);` is blocking everyone from implementing their own logic.

I do agree, though, that there needs to be a definitive way for casual users and then another way of overriding this (by defining inputs) for power users.

I still believe something as simple as adding a property that allows "power users" to disable the default `upToDateWhen` would be sufficient for the short-term.
```
getOutputs().upToDateWhen(task -> task.property.get("cachingEnabled"));
```
with setting it to `false` as default.

**Comment by mklnwt** [comment]
A member of our team implemented this as a work-around for the meantime.

```kotlin
tasks.withType<org.jooq.codegen.gradle.CodegenTask> {
    onlyIf { task ->
        // Check if any of the Liquibase files have been modified since the last build
        val lastModified = task.inputs.files.maxOfOrNull { it.lastModified() } ?: 0

        val lastBuildTime = layout.buildDirectory.file("lastBuildTime").orNull?.asFile
            ?.takeIf { it.exists() }
            ?.readText()
            ?.toLong()
            ?: 0

        lastModified > lastBuildTime
    }

    // Task action to update the last build time
    doLast {
        layout.buildDirectory.file("lastBuildTime").get().asFile.writeText(System.currentTimeMillis().toString())
    }
}
```

**Comment by lukaseder** [comment]
> @lukaseder the problems with up-to-date checks is not down to the source set(s).

I can't show you what I'm seeing because the tests aren't open source, but once I enable caching, this happens when I build the test module twice in a row:

```
lukas@DESKTOP-5SUOB0D MINGW64 ~/jOOQ/3.20/workspace/jOOQ-pro/jOOQ-test-codegen/jOOQ-test-codegen-gradle/jOOQ-test-codegen-gradle-kotlin-only-configuration-flyway
$ ./gradlew clean jooqCodegen test

> Task :jOOQ-test-codegen-gradle-kotlin-only-configuration-flyway:flywayMigrate
Flyway upgrade recommended: H2 2.2.224 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.2.220.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 8s
7 actionable tasks: 7 executed

lukas@DESKTOP-5SUOB0D MINGW64 ~/jOOQ/3.20/workspace/jOOQ-pro/jOOQ-test-codegen/jOOQ-test-codegen-gradle/jOOQ-test-codegen-gradle-kotlin-only-configuration-flyway
$ ./gradlew jooqCodegen test

> Task :jOOQ-test-codegen-gradle-kotlin-only-configuration-flyway:flywayMigrate
Flyway upgrade recommended: H2 2.2.224 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.2.220.

> Task :jOOQ-test-codegen-gradle-kotlin-only-configuration-flyway:compileTestJava FAILED
C:\Users\lukas\jOOQ\3.20\workspace\jOOQ-pro\jOOQ-test-codegen\jOOQ-test-codegen-gradle\jOOQ-test-codegen-gradle-kotlin-only-configuration-flyway\src\test\java\org\jooq\codegen\gradle\test\GradleTest.java:10: error: package org.jooq.codegen.gradle.test.flyway.db does not exist
        Table<?> t1 = org.jooq.codegen.gradle.test.flyway.db.Tables.T;
                                                            ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jOOQ-test-codegen-gradle-kotlin-only-configuration-flyway:compileTestJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1s
5 actionable tasks: 3 executed, 2 up-to-date
```

So, clearly something related to source sets is still very wrong (though disabling caching hides this fact). It's probably related to the other topic:
https://github.com/jOOQ/jOOQ/issues/16753

> There might be a follow-up issue, but generally speaking the inputs are the bigger problem at hand.

So, no. The *bigger* problem is the source sets issue as it is a correctness issue. This issue here is "just" a performance issue.

> Clearly setting `getOutputs().upToDateWhen(task -> false);` is blocking everyone from implementing their own logic.

Yes, that's understood. Though it makes things *work* (for now)

**Comment by lukaseder** [comment]
Let me put it this way. Once the `CodegenTask` is successfully cached, currently, it seems to no longer emit its contents to the `main` source set (or gradle "forgets" this for some reason), so the generated sources are no longer on the classpath.

**Comment by lukaseder** [comment]
OK, so I got it to work. The key problem with the source sets in the context of caching was that this logic wasn't invoked for cached tasks:

```java
            task.doFirst(t -> {
                SourceSetContainer source = project
                    .getExtensions()
                    .findByType(SourceSetContainer.class);

                if (source != null) {
                    source.configureEach(sourceSet -> {
                        if (sourceSet.getName().equals("main"))
                            sourceSet.getJava().srcDir(task.getOutputDirectory());
                    });
                }
            });
```

https://github.com/jOOQ/jOOQ/commit/12ac2d781b04191d3d19785f399fcc146b4122de#diff-fd1cc29a1e96274bf4cf4ad91fd38b0b43aa7dea221128973b7a8da6e88915fdL111

So, this means that the tasks's output directory wasn't being contributed to the source set, and thus the compilation error ensued.

I'm now explicitly adding the outputs to the source set, when the task is up-to-date:

https://github.com/jOOQ/jOOQ/commit/12ac2d781b04191d3d19785f399fcc146b4122de#diff-63373c59ee7ee8e03328aee7f0a0cd58de7b485bd98f351848e321728c45761cR97

I don't think that's sound by gradle. It looks like a bug to me. The build cache should listen to all source set changes made by tasks, and make those a part of the cache, otherwise the cache is doing the wrong things.

If anyone could build 3.19.10-SNAPSHOT or 3.20.0-SNAPSHOT and verify that the new solution works for them, that would be great. As a reminder, the new solution is:

- Both `cacheIf()` and `upToDateWhen()` are `false` by default
- They are true *iff* users specify inputs to the task that aren't
  - The task's classpath (i.e. any `.jar` file)
  - The task's own properties
  - The task's `"caching"` property is `true`. This flag allows for turning off the caching in case it behave unexpectedly

**Comment by lukaseder** [comment]
Implemented in versions:

- 3.20.0
- 3.19.10 (https://github.com/jOOQ/jOOQ/issues/16820)

**Comment by mklnwt** [comment]
Why did the source set behavior change between `3.19.5` & `3.19.6+` though?

I think registering the source set in `doFirst` (`task.doFirst(CodegenTask::registerSourceSet);`) is the culprit.

`doFirst` & `doLast` are only executed if the task is not up-to-date.

Source sets shouldn't be registered in the task, but rather in the plugin itself:
https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSetOutput.html

**Comment by lukaseder** [comment]
> Why did the source set behavior change between `3.19.5` & `3.19.6+` though?

That was the change:
- https://github.com/jOOQ/jOOQ/compare/version-3.19.5..version-3.19.6#diff-fd1cc29a1e96274bf4cf4ad91fd38b0b43aa7dea221128973b7a8da6e88915fd
- https://github.com/jOOQ/jOOQ/commit/7da530e6e27a6f077dd01788379a001571399622

Done because of:

- https://github.com/jOOQ/jOOQ/issues/16188

The source set can't be eager generated in case output directory parts should be lazy evaluated.

> I think registering the source set in `doFirst` (`task.doFirst(CodegenTask::registerSourceSet);`) is the culprit.
> 
> `doFirst` & `doLast` are only executed if the task is not up-to-date.

I can see that, but whatever these things do to modify the configuration/task/etc. graph should be reflected in the cache, no? Conversely, why would it be possible to add a source set from a task action if this is forbidden?

> Source sets shouldn't be registered in the task, but rather in the plugin itself:

But why?

I've seen both practices in various locations. In principle, it's the task that emits a source set, not the plugin. Imagine our plugin adds another task, e.g. help or validate, or whatever. These wouldn't emit source sets, only the codegen tasks do. Plus, codegen tasks can be nested with `executions`:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-gradle/#multiple-executions

In that case, there's a parent task with multiple child tasks, which can all be executed individually, each contributing to the source sets, possibly to different ones in the future.

**Comment by lukaseder** [comment]
But yeah, that's it. If I just replace

```java
task.doFirst(CodegenTask::registerSourceSet);
```

by

```java
CodegenTask.registerSourceSet(task);
```

Then there's a regression on https://github.com/jOOQ/jOOQ/issues/16188, but at least IntelliJ will be able to pick up source sets again.

But again, I think this is wrong. To evaluate the source set, the configuration needs to be evaluated. For that, the configuration's `Action` needs to be executed. And that's something we want to avoid, *unless* the task is executed.

I'll investigate this a bit more.

**Comment by mklnwt** [comment]
It shouldn't be `CodegenTask.registerSourceSet(task);` either.

It should be in the `apply` of the plugin. Completely unrelated to the task.

**Comment by lukaseder** [comment]
> It should be in the `apply` of the plugin. Completely unrelated to the task.

The `apply` function of the plugin doesn't even know yet if the `JavaPlugin` (or Kotlin, for that matter) has been applied yet. See also this previous error in jOOQ's plugin: 

- https://github.com/jOOQ/jOOQ/issues/16113

So, it would appear that this is premature. Anyway, the question whether our plugin should *create* new source sets, or just *contribute* to existing ones is another task. Currently, we just want to contribute to the main source set.

I'm not really sure why a task shouldn't be able to do that. It's most certainly related to the task in jOOQ's case. The task knows its `configuration/target/directory`. The plugin itself knows no such thing, it just knows tasks. So, I don't really see what you mean by "unrelated to the task."

**Comment by mklnwt** [comment]
Sorry, my bad. You definitely need the outputs of a task, but lazily.

https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSetOutput.html

The accessing the outputs will give you a provider. This behaviour can be cached I reckon.

**Comment by lukaseder** [comment]
Regarding:

> A lot of plugins are breaking rules at various places.

I mean, can you truly blame them? At some point, most folks just want to ship stuff, and not endlessly debate all the hundreds of footguns.

I truly hope that "declarative gradle" will fix things...

**Comment by lukaseder** [comment]
> I think you'd have to configure the task and then use the task providers output outside of the task configuration to configure the source sets.

I've been trying to wrestle those APIs for hours. `TaskProvider.configure(Action)` just returns `void`, and there's no way to cleanly access such a task afterwards for post processing.

I guess I will stumble upon the Right Thing™ eventually. E.g. this is still on the top of my TODO list:
https://youtrack.jetbrains.com/issue/IDEA-354580/IDEA-excludes-jOOQ-codegens-folder

**Comment by oleg-nenashev** [comment]
> I mean, can you truly blame them? At some point, most folks just want to ship stuff, and not endlessly debate all the hundreds of footguns.

Yes, it is a problem of the tool and not of the end users. We should do better. There is hope for Declarative Gradle, as well as better documentation and apis

**Comment by lukaseder** [comment]
Thanks a lot for chiming in, @oleg-nenashev!

> > I mean, can you truly blame them? At some point, most folks just want to ship stuff, and not endlessly debate all the hundreds of footguns.
>
> Yes, it is a problem of the tool and not of the end users. We should do better. There is hope for Declarative Gradle, as well as better documentation and apis

I think the documentation is great. But it's also vast, and thus it's hard to find the answer for a very specific question, like "what if I want to add to a source set from a task?" or "what if I want to create a source set per task."

Also, I'm still discovering all the good parts of gradle. I understand every feature once a user explains it to me (e.g. lazy configuration, lazy execution). But many of these things invalidate my assumptions about gradle, leading to code that worked before (for some users) now no longer working (for other users).

Anyway, unlike those users I mentioned, I have to get it right in the long run (and I will!), because this plugin will have to cater to a lot of users with a lot of use-cases.

**Comment by lukaseder** [comment]
I've added a comment here:
https://github.com/jOOQ/jOOQ/issues/16188#issuecomment-2163372158

> I've looked into options for hours now, and I really don't know how to allow for both:
> 
> * Lazy configuration
> * Eager discovery of source sets in IntelliJ
> 
> The source sets are generated only when the code generation task is executed due to this change, and IntelliJ obviously doesn't want to execute the task automatically, and gradle doesn't have a way of simulating the execution (I think?), so the only remaining option that I'm seeing is to offer two ways to invoke the plugin:
> 
> * Normal (non-lazy), where source sets are available automatically
> * Lazy, where source sets are available only if declared explicitly by the user

Thoughts, everyone?
