### ISSUE TITLE
QOM.Count.$field() should return null instead of internal asterisk representation

### ISSUE THREAD

**Issue by michael-simons** [jOOQ/jOOQ#16344]
### Expected behavior

`select count(*)` parses the asterisk into a generic SQLField, not the Asterisk.

### Actual behavior

The count(*) clause should contain the Asterisk.

### Steps to reproduce the problem

```java
package org.neo4j.driver.jdbc.translator.impl;

import org.jooq.Asterisk;
import org.jooq.SQLDialect;
import org.jooq.Select;
import org.jooq.impl.DSL;
import org.jooq.impl.QOM;

public class X {
	public static void main(String... a) {
		var context = DSL.using(SQLDialect.DEFAULT);
		var qom = context.parser().parse("SELECT count(*) FROM tab");

		var select = (Select<?>) qom.$queries().$first();
		var count = (QOM.Count) select.$select().$first();
		System.out.println(count.$field() instanceof Asterisk);
	}
}
```

### jOOQ Version

3.19.3

### Database product and version

n/a

### Java Version

17

### OS Version

macOS

**Comment by lukaseder** [comment]
Thanks for your message.

I understand that leaking the internal asterisk representation isn't nice in the case of `QOM.Count.$field()`. However, it's not correct to assume `org.jooq.Asterisk` would be a better type for the result:

1. That's a `DSL` type, not a `QOM` type. It is used to create queries, including expressions based on the `*`, such as `* EXCEPT (...)`. 
2. `Asterisk` doesn't extend `Field`, it's a different beast.

If you will, the `*` in `COUNT(*)` is just a weird syntactic token for something that should really be `COUNT()` (no argument). So, I'd argue the better solution here is to make `QOM.Count.$field()` nullable and return `null` in case there isn't any argument.

**Comment by lukaseder** [comment]
Related issue: 

- https://github.com/jOOQ/jOOQ/issues/16345

**Comment by lukaseder** [comment]
Also related:

- https://github.com/jOOQ/jOOQ/issues/16346

**Comment by lukaseder** [comment]
Fixed in version 3.20.0

**Comment by lukaseder** [comment]
As a workaround, for the time being, you can:

- `null` check the result for forward compatibility
- Compare the result's `toString()` rendering with `"*"`

E.g.:

```java
if ("*".equals("" + count.$field()) || count.$field() == null)
```

**Comment by michael-simons** [comment]
Thanks a lot, Lukas!

Pretty much exactly what I did! The null check will replace the instance check, I had originally in addition to the toString.

Pleasure working with you and nice seeing how flexible all of this is still is.
