### ISSUE TITLE
Insert with booleans fails when using policies and simple query mode

### ISSUE THREAD

**Issue by diastremskii** [jOOQ/jOOQ#16360]
### Expected behavior

The query is executed successfully

### Actual behavior

Query fails with an exception

### Steps to reproduce the problem

The underlying cause might be the same as https://github.com/jOOQ/jOOQ/issues/16334, so not sure if it's a duplicate, but the way to reproduce the problem is different and here it's possible to reproduce without batch insert, just with a regular one.

The key part of reproducing this issue is to set `preferQueryMode=simple` (while for batch insert it reproduces without simple mode). Similar to the other issue, the steps are:

Create a test table, this time with a boolean:

```sql
create table sales
(
    id            int     primary key not null,
    name          text    not null,
    price         int     not null,
    tenant_id     uuid    not null,
    is_discounted boolean not null
);
```

Define a tenant:
```kotlin
val tenantA = UUID.fromString("55be0301-83f5-45e6-8e1d-e902fe99dc43")
```

Add jOOQ policies on the table:

```kotlin
DefaultPolicyProvider().append(SALES, SALES.TENANT_ID.eq(tenantA))
```

Run the "regular" insert query:
```kotlin
context
    .insertInto(SALES)
    .set(
        SalesRecord().also {
            it.id = 100
            it.name = "test"
            it.price = 3
            it.isDiscounted = true
            it.tenantId = tenantA
        }
    )
    .execute()
```

And the generated query looks like this:
```sql
INSERT INTO
    "public"."sales" (
        "id",
        "name",
        "price",
        "tenant_id",
        "is_discounted"
    )
SELECT
    "t"."id",
    "t"."name",
    "t"."price",
    "t"."tenant_id",
    "t"."is_discounted"
FROM
    (
        SELECT
            100,
            'test',
            3,
            '55be0301-83f5-45e6-8e1d-e902fe99dc43',
            TRUE
    ) AS "t" (
        "id",
        "name",
        "price",
        "tenant_id",
        "is_discounted"
    )
WHERE
    "t"."tenant_id" = '55be0301-83f5-45e6-8e1d-e902fe99dc43';
```

And it fails with:
```
Caused by: org.postgresql.util.PSQLException: ERROR: column "is_discounted" is of type boolean but expression is of type text
  Hint: You will need to rewrite or cast the expression.
```

### jOOQ Version

3.19.4

### Database product and version

PostgreSQL 15.2

### Java Version

Amazon Corretto 17

### OS Version

MacOS 14.2.1

### JDBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment]
Thanks for your report. I can reproduce the problem with the JDBC parameter `preferQueryMode=simple`, but not with ordinary bind values, nor with inline values. (E.g. via `Settings.statementType == STATIC_STATEMENT`).

If you look at the pgjdbc flag's documentation:
https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/jdbc/PreferQueryMode.html

It says:

> Note: this is for debugging purposes only.

I'd say this is a bug in pgjdbc, if at all?

**Comment by lukaseder** [comment]
Yeah, clearly a bug in pgjdbc. Specifically in `org.postgresql.core.NativeQuery.toString(ParameterList parameters)`, there's no type information available with bind values anymore, which is why the `TRUE` literal is inlined into the query as `'TRUE'`, which obviously isn't correct!

It can be reproduced with vanilla pgjdbc like this, for example:

```java
try (
    Connection c = DriverManager.getConnection(
        "jdbc:postgresql://localhost:5432/postgres?preferQueryMode=simple",
        "postgres",
        "test"
    );
    PreparedStatement ps = c.prepareStatement("select (select false) union select (select ?)")
) {
    ps.setBoolean(1, true);

    try (ResultSet rs = ps.executeQuery()) {
        while (rs.next())
            System.out.println(rs.getBoolean(1));
    }
}
```

Producing:

```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: UNION types boolean and text cannot be matched
  Position: 36
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
	at org.jooq.testscripts.JDBC.main(JDBC.java:44)
```

Without the flag, this just prints:

```
false
true
```

**Comment by diastremskii** [comment]
Damn, wow, true. Thanks a lot! I'll close the issue.
Also great vanilla example, clearly shows the problem.

> Note: this is for debugging purposes only.

True, but I'd say in reality it's not used only for debugging, since for some things it's required. For example, DataDog [requires](https://docs.datadoghq.com/database_monitoring/setup_postgres/troubleshooting/#postgres-extended-query-protocol) simple query mode for collecting explain-plans (for older PG versions).

**Comment by lukaseder** [comment]
It's specific to `BOOLEAN` (or `UUID`). Many other types are supported. I've reported this issue to pgjdbc:

- https://github.com/pgjdbc/pgjdbc/issues/3145

**Comment by lukaseder** [comment]
> For example, DataDog [requires](https://docs.datadoghq.com/database_monitoring/setup_postgres/troubleshooting/#postgres-extended-query-protocol) simple query mode for collecting explain-plans (for older PG versions).

Use jOOQ's `STATIC_STATEMENT` flag then. We integration test most of jOOQ with that flag active as well. See: https://www.jooq.org/doc/latest/manual/sql-execution/statement-type/

**Comment by diastremskii** [comment]
Ah ok, we will look into it. Thank you!
