### ISSUE TITLE
Compilation error in generated Indexes.java when index references embeddables that replace their underlying fields

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16379]
When using embeddables that replace their underyling fields (including e.g. `<embeddablePrimaryKeys/>`), there's a compilation error in generated `Indexes.java` files because the index declaration references the `private` columns of the embeddable. E.g.:

```sql
CREATE TABLE s_simple_key_1.t_simple_key_2 (
  i INT NOT NULL,
  j INT NOT NULL,
  
  CONSTRAINT pk_t_simple_key_2 PRIMARY KEY (i),
  CONSTRAINT fk_t_simple_key_2_1 FOREIGN KEY (j) REFERENCES s_simple_key_1.t_simple_key_1
);

CREATE INDEX s_simple_key_1.i_simple_key_2 ON s_simple_key_1.t_simple_key_2 (i, j);
```

Produces:

```java
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index I_SIMPLE_KEY_2 = Internal.createIndex(
        DSL.name("I_SIMPLE_KEY_2"), TSimpleKey_2.T_SIMPLE_KEY_2, 
        new OrderField[] { 
            TSimpleKey_2.T_SIMPLE_KEY_2.I, // These references don't compile
            TSimpleKey_2.T_SIMPLE_KEY_2.J 
        }, false
    );
}
```

And

```java
public class TSimpleKey_2 extends TableImpl<TSimpleKey_2Record> {

    // Because the declarations are private
    private final TableField<TSimpleKey_2Record, Integer> I = createField(DSL.name("I"), SQLDataType.INTEGER.nullable(false), this, "");
    private final TableField<TSimpleKey_2Record, Integer> J = createField(DSL.name("J"), SQLDataType.INTEGER.nullable(false), this, "");

    public final TableField<TSimpleKey_2Record, PkTSimpleKey_1Record> FK_T_SIMPLE_KEY_2_1 = Internal.createEmbeddable(DSL.name("PK_T_SIMPLE_KEY_1"), PkTSimpleKey_1Record.class, true, this, J);
    public final TableField<TSimpleKey_2Record, PkTSimpleKey_2Record> PK_T_SIMPLE_KEY_2 = Internal.createEmbeddable(DSL.name("PK_T_SIMPLE_KEY_2"), PkTSimpleKey_2Record.class, true, this, I);

    ...
```

**Comment by lukaseder** [comment]
We'll probably have to look up columns from the table or from the embeddable. Ideally on a per-column basis, because an index may contain both embeddable and non-embeddable columns.

**Comment by lukaseder** [comment]
One option would be to mark replaced fields of embeddables as hidden and make them availabel via `Table.fieldsIncludingHidden()`, for lookup! This would match how Oracle implements `OBJECT` types (i.e. "native embeddables") embedded in tables, which are implemented with invisible fields:

```sql
create type o as object (a int, b int);
create table t (o1 o, o2 o);
select 
  internal_column_id, 
  column_id, 
  column_name, 
  qualified_col_name,
  data_type
from all_tab_cols 
where table_name = 'T'
order by internal_column_id;
```

Resulting in:

```
|INTERNAL_COLUMN_ID|COLUMN_ID|COLUMN_NAME |QUALIFIED_COL_NAME|DATA_TYPE|
|------------------|---------|------------|------------------|---------|
|1                 |1        |O1          |O1                |O        |
|2                 |1        |SYS_NC00002$|"O1"."A"          |NUMBER   |
|3                 |1        |SYS_NC00003$|"O1"."B"          |NUMBER   |
|4                 |2        |O2          |O2                |O        |
|5                 |2        |SYS_NC00005$|"O2"."A"          |NUMBER   |
|6                 |2        |SYS_NC00006$|"O2"."B"          |NUMBER   |
```

**Comment by NorbertKawinski** [comment]
I would love this to be fixed! :)

At this moment whenever I need an index on an embeddable I use a workaround with generated column like:
```
create table t(
    indexed_column int GENERATED ALWAYS AS (normal_column) STORED,
    normal_column embeddable_type,
);
```
Do you know of any better workaround?

**Comment by lukaseder** [comment]
I mean turning off the generation of `Indexes.java`, of course, not the indexes themselves.

**Comment by NorbertKawinski** [comment]
Oh, you're right. I can fix it by disabling indexes generation. Sorry my bad :)

It seems that this workaround with generated columns I mentioned above was for https://github.com/jOOQ/jOOQ/issues/16036 instead.

**Comment by lukaseder** [comment]
> It seems that this workaround with generated columns I mentioned above was for #16036 instead.

Let me have another look at that issue soon.

**Comment by lukaseder** [comment]
This can be fixed simply, once embeddable component paths are available as per:

- https://github.com/jOOQ/jOOQ/issues/17177

An embeddable that replaces its fields works just like a `UDT` type, which offers path access to its attributes, starting from jOOQ 3.19:

- https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/user-defined-type-attribute-paths

There are numerous reasons why embeddable field paths are a necessity, so let's finally tackle this.

**Comment by lukaseder** [comment]
Hmm, 2 additional thoughts:

- The embeddable field paths will remain an optional feature, if only because of the many additional classes being generated. If turned off, then bugs like this one here will still remain
- We now have hidden fields, since 3.20, which perfectly matches what these columns really are: https://www.jooq.org/doc/dev/manual/sql-building/column-expressions/hidden-columns

Here's a feature request to retrofit the `<replacesFields/>` flag to mean hiding the underlying fields:

- https://github.com/jOOQ/jOOQ/issues/17761

**Comment by lukaseder** [comment]
Heh, it's not an "additional thought," see:

- https://github.com/jOOQ/jOOQ/issues/16379#issuecomment-1971505694

I'll implement things this way in jOOQ 3.20.
