### ISSUE TITLE
Add arity check to synthetic foreign key configuration to avoid wrong generated code when FK / UK columns mismatch

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#16378]
### Expected behavior

jOOQ should either:

1. detect the error and fail with a friendly error message
2. generate code that does not typecheck so the compilation fails with an unfriendly error message

### Actual behavior

jOOQ generates syntactically valid but semantically invalid code that (if you're lucky) generates invalid SQL and fails at runtime.

### Steps to reproduce the problem

Given the following schema and jooq configuration:

```sql
CREATE TABLE mcve.a (
  aid1 NUMBER(7) NOT NULL,
  aid2 NUMBER(7) NOT NULL,
  aid3 NUMBER(7) NOT NULL,
  primary key (aid1, aid2, aid3)
);

CREATE TABLE mcve.b (
  bid1 NUMBER(7) GENERATED ALWAYS AS IDENTITY NOT NULL,
  aid1 NUMBER(7) NOT NULL,
  aid3 NUMBER(7) NOT NULL,
  primary key (bid1)
);
```

```xml
...
<syntheticObjects>
    <foreignKeys>
        <foreignKey>
            <name>A__FOR__B</name>
            <tables>B</tables>
            <fields>
                <field>aid1</field>
                <field>aid2</field>
                <field>aid3</field>
            </fields>
            <referencedTable>A</referencedTable>
            <referencedFields>
                <field>aid1</field>
                <field>aid2</field>
                <field>aid3</field>
            </referencedFields>
        </foreignKey>
    </foreignKeys>
</syntheticObjects>
...
```

jOOQ generates:

```java
...
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ARecord> SYS_C008293 = Internal.createUniqueKey(A.A, DSL.name("SYS_C008293"), new TableField[] { A.A.AID1, A.A.AID2, A.A.AID3 }, true);
    public static final UniqueKey<BRecord> SYS_C008297 = Internal.createUniqueKey(B.B, DSL.name("SYS_C008297"), new TableField[] { B.B.BID1 }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BRecord, ARecord> A__FOR__B = Internal.createForeignKey(B.B, DSL.name("A__FOR__B"), new TableField[] { B.B.AID1, B.B.AID3 }, Keys.SYS_C008293, new TableField[] { A.A.AID1, A.A.AID2 }, true);
}
```

which is obviously incorrect.

### jOOQ Version

3.19.1

### Database product and version

Oracle Free

### Java Version

17

**Comment by lukaseder** [comment]
Thanks for your report. I agree this should fail. 

We usually don't fail the entire code generation (most exceptions are intercepted and logged), and I don't think we should generate invalid code, ever. Typically, if such a configuration is wrong, then a warning is logged.

I've created a separate issue to generate some additional warnings when other object types don't match (e.g. table name):

- https://github.com/jOOQ/jOOQ/issues/16385

**Comment by lukaseder** [comment]
If the typo happens with the `<referencedFields/>`, the synthetic foreign key is currently being silently ignored, and with #16385, there will be a warning message like this:

```
[WARNING] No unique key found for synthetic foreign key: <name>FK_SYNTHETIC_KEYS_MISMATCH</name><tables>COLUMN_MISMATCH_CHILD</tables><referencedTable>COLUMN_MISMATCH_PARENT</referencedTable><fields><field>A1</field><field>A2</field><field>A4</field></fields><referencedFields><field>A1</field><field>A2</field><field>A4</field></referencedFields>
```

So, my suggestion would be consistent. The FK field list must also be ignored if it doesn't correspond to a list of the expected length, matching the UK field list length.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.6 (https://github.com/jOOQ/jOOQ/issues/16389)
- 3.18.13 (https://github.com/jOOQ/jOOQ/issues/16390)
- 3.17.22 (https://github.com/jOOQ/jOOQ/issues/16391)

**Comment by alf** [comment]
Excellent. Thank you.
