### ISSUE TITLE
Can we build dynamic SQL in the form of a query language like JPQL?

### ISSUE THREAD

**Issue by bijgu1997** [jOOQ/jOOQ#16381]
### Your question

Hi @lukaseder,

We are developing a client application where based on the user's inputs, we are dynamically building a HQL/JPQL query and executing it against an Oracle database. For example, we are building the following HQL statement directly:
```
select sub.tranId, sub.merchName
from (
  select trn.transactionId as tranId, add.merchantName as merchName
  from Transactions trn
  join Addendums add
   on add.transactionId= trn.transactionId) sub
```

We are facing a number of issues with JPQL as it has limited support for sub-queries in the FROM clause and embeddable types and we are considering a migration to jOOQ.

I found a few threads on StackOverflow where you gave examples on how jOOQ can be used to dynamically build queries by defining the select entities, where clause/s and joins separately before building the query through the DSL API. Is there another way  to build dynamic queries which bypasses the method chaining in the DSL API and is more similar to building a query in JPQL? 

Any help would be greatly appreciated. 

### jOOQ Version

jOOQ 3.19.4

### Database product and version

Oracle 19c

**Comment by lukaseder** [comment]
There's a historic `SelectQuery` API which is still maintained. You can access it via `DSLContext.selectQuery()`.

I don't really understand why you want to *"bypass the method chaining"* though. Perhaps you have a specific issue with that? It's probably easy to resolve. Note that all jOOQ queries are dynamic SQL queries. Whether you use an imperative or functional programming style to construct such queries is usually not too important. See e.g. these resources here:

- https://blog.jooq.org/a-functional-programming-approach-to-dynamic-sql-with-jooq/
- https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql/

I can probably help with more specific questions, though again, I don't understand what it means for an API to be *"more similar to building a query in JPQL"*
