### ISSUE TITLE
Code generation tool - Generate :  liquibase.exception.MigrationFailedException on column type VARCHAR2(255 CHAR) (Oracle)

### ISSUE THREAD

**Issue by lefebvrecharlie** [jOOQ/jOOQ#16420]
### Your question

Hello jOOQ Team,

I am currently in the process of upgrading my project to jOOQ version 3.19.5. Previously, with an older version of jOOQ, I did not encounter any issues with Liquibase changesets that contained columns with the type VARCHAR2(255 CHAR). However, since attempting to migrate to jOOQ 3.19.5, I've run into a blocker related to processing these specific changesets.

The error I encounter is related to the syntax in my Liquibase changeset files when jOOQ's code generator tries to interpret them. Here's the core of my jOOQ generator configuration in my pom.xml:

```
<configuration>
    <generator>
        <database>
            <name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
            <properties>
                <property>
                    <key>rootPath</key>
                    <value>${basedir}/src/main/resources/db/changelog</value>
                </property>
                <property>
                    <key>scripts</key>
                    <value>changelog.xml</value>
                </property>
                <property>
                    <key>includeLiquibaseTables</key>
                    <value>false</value>
                </property>
                <property>
                    <key>changeLogParameters.contexts</key>
                    <value>test</value>
                </property>
            </properties>
            <!-- Custom type mappings omitted for brevity -->
        </database>
        <target>
            <packageName>com.xxxx.xxxx.jooq</packageName>
            <directory>target/generated-sources</directory>
        </target>
        <generate>
            <daos>true</daos>
            <springAnnotations>true</springAnnotations>
        </generate>
    </generator>
</configuration>
```

```
   <changeSet author="xxxx" id="xxxx-xxxx">
        <createTable tableName="xxxxx_xxxxxxx">
            <column name="xxxx_xxxx" type="NUMBER(10, 0)">
                <constraints primaryKey="true" primaryKeyName="xxx_xxxxxxx"/>
            </column>
            <column name="xxxx_xxxxx" type="TIMESTAMP(6)"/>
            <column name="xxxx_xxxx" type="VARCHAR2(255 CHAR)"/>
            <column name="xxxxx_xxxx" type="VARCHAR2(255 CHAR)"/>
            <column name="xxxxx_xxxx" type="VARCHAR2(255 CHAR)"/>
            <column name="xxxx_xxxx" type="VARCHAR2(255 CHAR)"/>
        </createTable>
    </changeSet>
```

```
[ERROR] Failed to execute goal org.jooq.pro:jooq-codegen-maven:3.19.5:generate (default) on project xxx: Error running jOOQ code generation tool: Error while exporting schema: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset xxx::xxx::xxx:
[ERROR] Reason: liquibase.exception.DatabaseException: Erreur de syntaxe dans l'instruction SQL "CREATE TABLE PUBLIC.xxx (xxx numeric(10, 0) NOT NULL, xxx TIMESTAMP(6), xxx VARCHAR(255 []CHAR), xxx VARCHAR(255 CHAR), xxx VARCHAR(255 CHAR), xxx VARCHAR(255 CHAR), CONSTRAINT xxx PRIMARY KEY (xxx))"; attendu "CHARACTERS, OCTETS, )"
[ERROR] Syntax error in SQL statement "CREATE TABLE PUBLIC.xxx (xxx numeric(10, 0) NOT NULL, xxx TIMESTAMP(6), xxx VARCHAR(255 []CHAR), xxx VARCHAR(255 CHAR), xxx VARCHAR(255 CHAR), xxx VARCHAR(255 CHAR), CONSTRAINT xxx PRIMARY KEY (xxx))"; expected "CHARACTERS, OCTETS, )"; SQL statement:
[ERROR] CREATE TABLE PUBLIC.xxx (xxx numeric(10, 0) NOT NULL, xxx TIMESTAMP(6), xxx VARCHAR(255 CHAR), xxx VARCHAR(255 CHAR), xxx VARCHAR(255 CHAR), xxx VARCHAR(255 CHAR), CONSTRAINT xxx PRIMARY KEY (xxx)) [42001-224] [Failed SQL: (42001) CREATE TABLE PUBLIC.xxx (xxx numeric(10, 0) NOT NULL, xxx TIMESTAMP(6), xxx VARCHAR(255 CHAR), xxx VARCHAR(255 CHAR), xxx VARCHAR(255 CHAR), xxx VARCHAR(255 CHAR), CONSTRAINT xxx PRIMARY KEY (xxx))]
```

Given this situation, my question is: Do I need to modify all my Liquibase changeset files to accommodate this migration, or is there a configuration option that I might be missing which could resolve this syntax interpretation issue without needing to alter the changesets?

I'm developing on Java 21, and this syntax issue seems to be a new occurrence with the transition to jOOQ 3.19.5. I'd greatly appreciate any guidance or suggestions on how to best approach resolving this issue.

Thank you for your time and help.

### jOOQ Version

jOOQ Pro 3.19.5

### Database product and version

Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production

### Java Version

21

### OS Version

Mac OS 14.3.1

### JDBC driver name and version (include name if unofficial driver)

Oracle JDBC 19.3.0.0

### Spring Boot Version
3.2.3

### Liquibase
4.26.0

### Maven Version
3.9.4

**Comment by lukaseder** [comment]
Thank you very much for your message. This appears to be a bug, probably caused by the implicit upgrade of the backing H2 database implementation on which we execute the liquibase migration.

H2 cannot parse this:

```sql
CREATE TABLE t (
  vc_char varchar2(255 char),
  vc_byte varchar2(255 byte)
);
```

It raises:

```
SQL Error [42001] [42001]: Syntax error in SQL statement "CREATE TABLE t (\000d\000a  vc_char varchar2(255 [*]char),\000d\000a  vc_byte varchar2(255 byte)\000d\000a)"; expected "CHARACTERS, OCTETS, )"; SQL statement:
CREATE TABLE t (
  vc_char varchar2(255 char),
  vc_byte varchar2(255 byte)
) [42001-220]
```

It expects the standard SQL `CHARACTERS` keyword, instead of `CHAR`.

I think the quickest workaround for this problem is to copy the liquibase migration file and patch the contents, removing the `CHAR` keyword, which isn't necessary for code generation purposes. With Maven, you could achieve this using:

- `org.apache.maven.plugins:maven-resources-plugin` for copying the liquibase files
- `com.google.code.maven-replacer-plugin:replacer` for replacing contents in the files

I don't see a simple way to fix this in the current `LiquibaseDatabase`, but we have a more thorough improvement on the way where we stop using H2 behind the scenes and start interpreting the DDL ourselves:

- https://github.com/jOOQ/jOOQ/issues/7034

**Comment by lefebvrecharlie** [comment]
Hi!
Thank you for your prompt response. I was able to solve the problem using the method you pointed out to me.

I had to replace several expressions to successfully get through the generation.

    "CHAR" -> ""
    "SYSDATE" -> "CURRENT_TIMESTAMP"
    "SYSTIMESTAMP" -> "CURRENT_TIMESTAMP"
    "SEQ_xxx.NEXTVAL" -> "NEXTVAL('SEQ_xxx')"

**Comment by lukaseder** [comment]
Looking into this now. We'll offer a new flag `useParsingConnection` to allow for translating between dialects from what Liquibase generates to the target dialect we're currently using in our interpreting databases:

- https://github.com/jOOQ/jOOQ/issues/17495

This should allow for handling these cases

**Comment by lukaseder** [comment]
`SYSDATE` will still not be supported right away. I'll have another look at this issue:

- https://github.com/jOOQ/jOOQ/issues/9716

But `VARCHAR2(255 CHAR)` will now work.

**Comment by lukaseder** [comment]
Another way to solve such issues starting from jOOQ 3.20 will be the new support for passing along properties to Liquibase:

- https://github.com/jOOQ/jOOQ/issues/17593
