### ISSUE TITLE
jOOQ does not use custom converter/binding for spatial types in dynamic queries

### ISSUE THREAD

**Issue by RB14** [jOOQ/jOOQ#16426]
### Steps to reproduce the problem

I'm in the process of upgrading jOOQ to `3.16` (and then to the more recent versions gradually) and I encountered some weird behavior when it comes to fetching `Geometry` columns in dynamic SQL queries. This problem does not happen in the generated code because I disabled `spatialTypes` and registered a `forcedType` with my custom binding. My binding converts `Geometry` fields to JTS' geometry (I'm actually using [this](https://github.com/dmitry-zhuravlev/jooq-postgis-spatial) nice open source extension , which admittedly hasn't changed much in the last 3 years, but it works perfectly for the generated code).

My problem happens in the following scenario:

```java
dslContext.execute("CREATE TABLE foo (geom geometry)");
dslContext.execute("INSERT INTO foo (geom) VALUES (st_geomfromtext('POINT(1 2)',4326))");
Field<Geometry> geomField = DSL.field("geom", SQLDataType.OTHER.asConvertedDataType(new JTSGeometryBinding()));
Geometry geom = dslContext
  .selectFrom("foo")
  .fetchOne(geomField);
```

So basically I have a table which does not exist in the generated code (it was created dynamically at some point), and I'm trying to fetch some `Geometry` data from it. When I call `fetchOne(geomField)` I make sure to pass in a `Field` that was constructed using my JTS converter, so I expect jOOQ to use that converter when it fetches the data, but instead I'm getting this error:

```
org.jooq.exception.DataAccessException: The out of the box binding for geometry is available in the commercial jOOQ distribution only. Alternatively, you can implement your own custom binding.
```

Now I noticed that the problem can be avoided if I change the query code to be:
```java
Geometry geom = dslContext
  .select(geomField)
  .from("foo")
  .fetchOne(geomField);
```

Earlier in the log I see that the first query is being translated to `select * from foo`, and the second query is `select geom from foo`, so surely it has something to do with that.

Now I'm thinking there might be multiple problems here:
1. If Spatial support is only avaialble in the commercial version of jOOQ, why is it enabled (and fails) in the non-commrecial version? I mean why not just treat it as an unkown type (like any other unkown type that doesn't have an explicit binding) and let the user can decide how to handle it.. I think making it fail-by-default is not very intuitive. 
2. The error tells me that I can "implement my own custom binding", but I already did it, it's just unclear how I should build the query itself with that binding. I would expect that both forms of the query above would work the same way.

I'm truly sorry if this problem had been addressed in later versions of jOOQ (I did try to look it up).

Thanks so much for all the amazing work you're doing with this library!

### jOOQ Version

3.16.23

### Database product and version

PostgreSQL 13

### Java Version

openjdk version "11.0.14" 2022-01-18

### JDBC driver name and version (include name if unofficial driver)

42.3.9

**Comment by lukaseder** [comment]
Thanks for your message.

If you look at your query:

```java
Geometry geom = dslContext
  .selectFrom("foo")
  .fetchOne(geomField);
```

Why would you expect the converter to apply here? `ResultQuery.fetchOne(Field)` is just convenience for `ResultQuery.fetchOne()?.get(Field)` (`?.` being hypothetical `null` handling, as in kotlin). So, when jOOQ executes your plain SQL query, it has no information about data types

> org.jooq.exception.DataAccessException: The out of the box binding for geometry is available in the commercial jOOQ distribution only. Alternatively, you can implement your own custom binding.

The error appears when jOOQ cannot find any custom bindings for spatial types, as the out of the box support isn't available in the jOOQ Open Source Edition:

- https://github.com/jOOQ/jOOQ/issues/982

If you opt to use your own bindings, then you can diregard that part of the error message and focus only on the reason why your custom binding wasn't found.

> 1. If Spatial support is only avaialble in the commercial version of jOOQ, why is it enabled (and fails) in the non-commrecial version? I mean why not just treat it as an unkown type (like any other unkown type that doesn't have an explicit binding) and let the user can decide how to handle it.. I think making it fail-by-default is not very intuitive.

How else would we let people know that they can upgrade to unlock certain features? The error message *did* also hint at the type being "unknown," just a special kind of unknown. We could just pass along some random JDBC type (probably `PGobject`) but that would just fail differently, later on, possibly with a `ClassCastException`, so I don't think this is really a problem. Your assumptions on how to use a `Converter` were wrong, so it's in your best interest that your code fails *somehow*.

> 2\. The error tells me that I can "implement my own custom binding", but I already did it, it's just unclear how I should build the query itself with that binding. I would expect that both forms of the query above would work the same way.

You didn't pass the binding to the jOOQ query in your first example. You did in the second example.

Now, there's a mandatory blog post I always link to in cases like these:
https://blog.jooq.org/why-you-should-use-jooq-with-code-generation/

A lot of problems (*especially* data type binding related ones) go away entirely if you opt into using code generation. There are *so many* advantages of using the code generator. Unless you have a dynamic schema that is unknown at compile time, I highly recommend looking into this option.

> I'm truly sorry if this problem had been addressed in later versions of jOOQ (I did try to look it up).

I don't think it's different in 3.19

**Comment by RB14** [comment]
Thanks so much for the detailed answer and for all the references!


> Why would you expect the converter to apply here? `ResultQuery.fetchOne(Field)` is just convenience for `ResultQuery.fetchOne()?.get(Field)` (`?.` being hypothetical `null` handling, as in kotlin). So, when jOOQ executes your plain SQL query, it has no information about data types

Right, so I don't know why, but my intuition told me that since this is the first time in this query that I'm asking explicitly for that field, it would use its binding, before actually fetching and using jOOQ's native bindings. But sure, the docs say exactly what you wrote. I guess it's important to distinguish between the part where I build the query, before its actual execution, to the part where it's already executed and now I am only fetching the data.

> If you opt to use your own bindings, then you can diregard that part of the error message and focus only on the reason why your custom binding wasn't found.

Right, thanks, maybe the message can be slightly improved to accommodate cases where the error is in the query itself and not necessarily the use of bindings.

> How else would we let people know that they can upgrade to unlock certain features? The error message _did_ also hint at the type being "unknown," just a special kind of unknown. We could just pass along some random JDBC type (probably `PGobject`) but that would just fail differently, later on, possibly with a `ClassCastException`, so I don't think this is really a problem. Your assumptions on how to use a `Converter` were wrong, so it's in your best interest that your code fails _somehow_.

Right, so I actually forgot how it behaves for unknown types that don't have bindings (it's been a while since it happened to me), but if it still fails (and not, say, return a `PGobject` like you suggested), then I agree that adding the additional information about the specific type is beneficial. Thanks for the clarification.

> Now, there's a mandatory blog post I always link to in cases like these: https://blog.jooq.org/why-you-should-use-jooq-with-code-generation/
> 
> A lot of problems (_especially_ data type binding related ones) go away entirely if you opt into using code generation. There are _so many_ advantages of using the code generator. Unless you have a dynamic schema that is unknown at compile time, I highly recommend looking into this option.

Right, we are indeed using the code generation for the most part of our application, but this specific use-case was actually in one of our tests that creates a table dynamically (although I imagine we could implemented that test differently).
