### ISSUE TITLE
Batch insert, batchInsert(), of static records changes behavior between subsequent calls

### ISSUE THREAD

**Issue by maguro** [jOOQ/jOOQ#16451]
### Expected behavior

When I call `batchInsert()` with a list of static jOOQ record instances multiple times, I expect jOOQ to use the same insert command for each call. 

### Actual behavior

What happens is that subsequent calls to  `batchInsert()` use `insert into "foo" default values`, which violates existing integrity constraints in `foo`.

### Steps to reproduce the problem

    CREATE TABLE IF NOT EXISTS foo.bar
    (
        "BEGIN" TIMESTAMP WITH TIME ZONE NOT NULL,
        "END"   TIMESTAMP WITH TIME ZONE,

        PRIMARY KEY ("BEGIN")
    );

generate Java DB records for `bar`

Write a test that creates static instances of the records and batch insert them multiple times, clearing the table between inserts.

### jOOQ Version

jOOQ Profesional Edition 3.18.3

### Database product and version

PostgresSQL 12

### Java Version

JDK 17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

postgresql 42.7.2

**Comment by lukaseder** [comment]
Thanks for your message.

jOOQ `UpdatableRecord` types aren't immutable. Any action on them mutates their state, specifically their internal `Record.changed()` flags. A successful `INSERT` means that subsequent changes to the record are expected to produce an `UPDATE` of the same value, not another `INSERT`.

You can, however, call `UpdatableRecord.copy()` and re-insert the copy of the data.

I hope this helps.
