### ISSUE TITLE
Multi-tenant code generation and column ordering

### ISSUE THREAD

**Issue by alexrkopp** [jOOQ/jOOQ#16477]
### Your question

Hello,

I work on a multi-tenant application backed by Oracle Database. Each tenant has a separate schema with the same set of tables and columns. As such, I am pointing the jOOQ code generator at one of the schemas and using that generated code for all tenants. Recently I noticed that depending on the schema we use for generation, it results in slightly different results. The differences are in the column ordering. Specifically the index used in `set(<index>, value)` for a given column may be different depending on the tenant.

Is this inherently dangerous or problematic? I do not think it is, but wanted to double check.

One other side effect that worries me a bit more is that the generated record's constructor parameter order changes, which could be a problem if there's any code that is using it, though I would hope/expect internal automated tests to catch issues there. Unless the internals of jOOQ somehow rely on it, I might be inclined to "extend" the code generation to suppress the generation of the "detached, initialized" record constructor and request that developers use the other "detached" constructor, followed by invoking the necessary setters.

Any insight or advice that can be provided here would be appreciated

### jOOQ Version

jOOQ 3.19

### Database product and version

Oracle

### Java Version

openjdk 21

**Comment by lukaseder** [comment]
Thanks for your message.

This is a common situation, even with column ordering being different between development, test, and production database instances, as DDL isn't always run in the same way. The only reason why this could ever be a problem with jOOQ is when you use the `*` explicitly in a `SELECT *` query (e.g. using `DSL.asterisk()` or with plain SQL templates). In those cases, the database will dictate the column order, and jOOQ's generated code might not match. If you construct your queries ordinarily, i.e. with generated code, this won't happen.

I hope this helps

**Comment by alexrkopp** [comment]
Thanks for the confirmation. Upon further investigation, it seems like it would not be straight forward to extend JavaGenerator and simply avoid running of generateRecordConstructor, which writes the "detached, initialised" constructor. Would there be any appetite in making that method protected instead of private in a future version? Or some other way of skipping the creation of that one constructor?

**Comment by lukaseder** [comment]
> Upon further investigation, it seems like it would not be straight forward to extend JavaGenerator and simply avoid running of generateRecordConstructor, which writes the "detached, initialised" constructor.

I don't see why you would want to do this. It sounds like a very complicated solution to a problem that I'm unaware of. Do you have any specific example where the constructor parameter order will give you problems?

> Would there be any appetite in making that method protected instead of private in a future version? Or some other way of skipping the creation of that one constructor?

I'd rather not. More API surface = more trouble in the future, always. There's almost always a better solution than making internal stuff public.

**Comment by lukaseder** [comment]
I see now, thanks for clarification. Do you not have a controlled environment where the table structure is always the same, rather than generating code from what appears to be a production schema?

I always recommend a process where:

- Database change management is used (e.g. Flyway, Liquibase, etc.)
- Thus, all migrations are repeatable in integration test setups (testing e.g. using testcontainers)
- Such an environment is then used for code generation as well

See also:
https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

jOOQ also has other means of code generation, including:

- Interpreting DDL: https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl/
- Using an XML schema representation: https://www.jooq.org/doc/latest/manual/code-generation/codegen-xml/

In either case, I think the right thing to do here is to use a deterministic meta data source for code generation.

If tenants are allowed to be different, then ordering of the columns is only one problem. Another is that a column may be present here, but not there.

**Comment by alexrkopp** [comment]
What you suggest is reasonable, though there are some technical, operational, and organizational issues that make none of those options truly feasible. Most are not problems that jOOQ is going to solve.

For example, early in my jOOQ journey, I did test out DDLDatabase, but quickly ran into incompatibilities with oracle-specific DDL being (understandably) unable to be handled by the in-memory H2 database.

The issue of "a column may be present here, but not there" is not actually a concern because we have other controls that ensure all tenants have the same tables, columns, indexes, etc.

In any event, it sounds like the "solution" is less technical and more operational operational in nature: set expectations that the code generation always be triggered against the same tenant.

Thanks for your help.

**Comment by lukaseder** [comment]
> For example, early in my jOOQ journey, I did test out DDLDatabase, but quickly ran into incompatibilities with oracle-specific DDL being (understandably) unable to be handled by the in-memory H2 database.

I understand. It does quickly run into limitations for more sophisticated schemas.

> In any event, it sounds like the "solution" is less technical and more operational operational in nature: set expectations that the code generation always be triggered against the same tenant.

I've just thought of another solution that might help here? There's a code generation SPI that allows for overriding the ordering of objects, for precisely this reason:

https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-order-provider/

The main purpose of this SPI is to stabilise any non-deterministic ordering, but your case seems similar. Perhaps this helps, in addition to always generating against the same tenant, of course.
