### ISSUE TITLE
Meta::ddl produces incorrect DDL for SQLite, when there are FOREIGN KEY constraints

### ISSUE THREAD

**Issue by marceloverdijk** [jOOQ/jOOQ#16470]
### Expected behavior

For SQLite foreign keys should be generated as part of the create table statement.

This because SQLite does not support adding a constraint to an existing table, but that it should be part of the create table statement.

See this StackOverflow article:

https://stackoverflow.com/questions/1884818/how-do-i-add-a-foreign-key-to-an-existing-sqlite-table

### Actual behavior

jOOQ generates statements in this order:
- create table; including pk + uk(s
- created index(es)
- alter table add foreign key constraint

### Steps to reproduce the problem

My setup is to use the `org.jooq.meta.extensions.ddl.DDLDatabase` to generate schema, tables etc from a `create_schema.sql` file which contains:

``` 
CREATE TABLE "continent"
( "id" VARCHAR(255) NOT NULL PRIMARY KEY
, "code" VARCHAR(2) NOT NULL UNIQUE
, "name" VARCHAR(255) NOT NULL UNIQUE
, "demonym" VARCHAR(255)
);

CREATE TABLE "country"
( "id" VARCHAR(255) NOT NULL PRIMARY KEY
, "alpha2_code" VARCHAR(2) NOT NULL UNIQUE
, "alpha3_code" VARCHAR(3) NOT NULL UNIQUE
, "name" VARCHAR(255) NOT NULL UNIQUE
, "demonym" VARCHAR(255)
, "continent_id" VARCHAR(255) NOT NULL REFERENCES "continent" ("id")
);

CREATE INDEX "country_continent_id_index" ON "country" ("continent_id");
```

Then when doing:

```
Settings settings = new Settings()
        .withRenderFormatted(true);

DSLContext ctx = DSL.using(SQLDialect.SQLITE, settings);

Queries ddl = ctx.ddl(DEFAULT_SCHEMA);
ddl.forEach(query -> {
    System.out.println(query);
});
```

it gives:

```
create table continent (
  id varchar(255) not null,
  code varchar(2) not null,
  name varchar(255) not null,
  demonym varchar(255),
  constraint CONSTRAINT_E primary key (id),
  constraint CONSTRAINT_E7 unique (code),
  constraint CONSTRAINT_E7F unique (name)
)

create table country (
  id varchar(255) not null,
  alpha2_code varchar(2) not null,
  alpha3_code varchar(3) not null,
  name varchar(255) not null,
  demonym varchar(255),
  continent_id varchar(255) not null,
  constraint CONSTRAINT_3 primary key (id),
  constraint CONSTRAINT_39 unique (alpha2_code),
  constraint CONSTRAINT_391 unique (alpha3_code),
  constraint CONSTRAINT_3917 unique (name)
)

create index country_continent_id_index on country(continent_id)

alter table country add constraint CONSTRAINT_39175 foreign key (continent_id) references continent (id)
```

When executing this against the actual SQLite database (or instead of printing calling `query.execute()`) it will fail with:

> SQL [alter table country add constraint CONSTRAINT_39175 foreign key (continent_id) references continent (id)]; [SQLITE_ERROR] SQL error or missing database (near "constraint": syntax error)

### jOOQ Version

3.19.6 open source

### Database product and version

SQLite

### Java Version

17

**Comment by lukaseder** [comment]
Thanks a lot for your report. As discussed on the mailing list (see https://groups.google.com/g/jooq-user/c/At5WzUp-1Po/m/HcDGulccAAAJ), there are 2 ways to go about this:

- Do a toplogical sort, assuming there are no cycles between tables and their relationships
- Support adding constraints directly with the column using `ALTER TABLE t ADD c type REFERENCES u`. This will be quite tricky

I'll probably think about the topological sort option first, as this could be useful for other dialects as well, in case someone prefers that style. If there are cycles, then for now, there will still be invalid `ALTER TABLE .. ADD CONSTRAINT` statements.

**Comment by marceloverdijk** [comment]
Interestingly, (and I tested it with SQLiteStudio), this works in SQLite without errors:

```
-- Create the Author table
CREATE TABLE Author (
    author_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    favorite_book_id INTEGER,
    FOREIGN KEY (favorite_book_id) REFERENCES Books(book_id)
);

-- Create the Books table
CREATE TABLE Books (
    book_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    author_id INTEGER NOT NULL,
    FOREIGN KEY (author_id) REFERENCES Author(author_id)
);
```

So you can create a table (`Authors` in this case) which references to a at that stage non-existing other table (`Books`)...

**Comment by lukaseder** [comment]
OMG, this database 😅. Well, that's good to know.

**Comment by lukaseder** [comment]
Implementing this now. A new `DDLExportConfiguration::inlineForeignKeyConstraints` flag will be made available, with the usual 3 states:

- `ALWAYS`: This will always inline FK constraints into the table definition
- `WHEN_NEEDED`: This will inline FK constraints only for dialects where this is necessary (i.e. SQLite). This will be the default
- `NEVER`: This will never inline FK constraints into the table definition

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17160)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17161)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17162)

**Comment by lukaseder** [comment]
Other constraint types should be configurably inlinable as well:

- https://github.com/jOOQ/jOOQ/issues/17163
