### ISSUE TITLE
Render standard SQL DATE literal on MySQL, instead of JDBC date literal

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16498]
In 3.5.0, we've started rendering JDBC date literals (`{d ...}`) for MySQL, see:

- https://github.com/jOOQ/jOOQ/issues/3648

This may no longer be necessary in more recent versions of MySQL, MariaDB. It would be better to avoid the JDBC syntax so the SQL can be used outside of JDBC as well.

Let's investigate.

**Comment by lukaseder** [comment]
Welp:

```sql
create table t (b datetime);
alter table t alter column b set default timestamp '1970-01-01 00:00:00.0';
```

This throws:

> SQL Error [1067] [42000]: Invalid default value for 'b'

Both of these work:

```sql
alter table t alter column b set default {ts '1970-01-01 00:00:00.0'};
alter table t alter column b set default '1970-01-01 00:00:00.0';
```

I've created a bug for this:
https://bugs.mysql.com/bug.php?id=114450

That's the only limitation I've encountered. It would be possible to work around this specific problem for DDL only, but it's still a limitation I worry about, so I'm not convinced the existing behaviour is so bad? After all, MySQL documents that they accept the ODBC escape syntax:
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-literals.html

Why do you prefer standard SQL here, @marceloverdijk?

**Comment by lukaseder** [comment]
I'll reject this issue. The ODBC syntax is officially supported, and it works better, so there's no reason to switch, given that there seem to be limitations, still.

**Comment by marceloverdijk** [comment]
I understand closing the issue.

> Why do you prefer standard SQL?

In general I would always prefer the standard SQL expressions over ODBC syntax (although MySQL supports it).

**Comment by lukaseder** [comment]
> In general I would always prefer the standard SQL expressions over ODBC syntax (although MySQL supports it).

I see. Though, as mentioned on the user group, jOOQ will generate what works best, not what looks nicest:
https://groups.google.com/g/jooq-user/c/rCN6Idq28yc

**Comment by lukaseder** [comment]
...  I mean, in a way, you're requesting a "what works best" solution over a "what looks nicest" solution in this bug as well:

- https://github.com/jOOQ/jOOQ/issues/16470

**Comment by marceloverdijk** [comment]
> > In general I would always prefer the standard SQL expressions over ODBC syntax (although MySQL supports it).

> I see. Though, as mentioned on the user group, jOOQ will generate what works best, not what looks nicest:
> https://groups.google.com/g/jooq-user/c/rCN6Idq28yc

I fully agree! Don't get me wrong, I meant in case both would work I would prefer the standard SQL expression.

> ... I mean, in a way, you're requesting a "what works best" solution over a "what looks nicest" solution in this bug as well:
> https://github.com/jOOQ/jOOQ/issues/16470

In this case I don't mind if FK is generated as part of the create table or not.
Currently creating DDL output just errors when running it on SQLite as explained in that ticket...

**Comment by lukaseder** [comment]
I'll investigate this once more. I've had issues with the `{ts ..}` syntax since recently

**Comment by lukaseder** [comment]
Ah, that `{ts ..}` "regression" I've noticed is due to DST, it appears!

Due to this issue:

- https://github.com/jOOQ/jOOQ/issues/16539

jOOQ creates a `TIMESTAMP` type in DDL, not a `DATETIME` type:

```sql
create table t (
  dummy int not null,
  ts timestamp,
  primary key (dummy)
);
```

And now, this default is out of range for the  `TIMESTAMP` type, when I run this on my machine:

```sql
alter table t alter column ts set default '1970-01-01 00:00:00.0';
```

Whereas this is not out of range:


```sql
alter table t alter column ts set default '1970-01-01 01:00:00.0';
```

This has been noticed only recently, because the relevant integration test has been added only recently.
