### ISSUE TITLE
GeneratorStrategy::getJavaMemberOverride should be called with Mode.DAO for all member-specific fetchByXYZ methods generated in a DAO

### ISSUE THREAD

**Issue by mikebski** [jOOQ/jOOQ#16501]
### Use case

I want to define an interface for each DAO to implement, and have 2 issues:

1. Cannot provide `override` methods for DAO, only for RECORD and POJO 
2. Vararg methods with Int type cannot be used with interfaces - See https://stackoverflow.com/questions/78209587/kotlin-interface-with-generic-inteface-method-with-vararg-generic-param-cannot and https://youtrack.jetbrains.com/issue/KT-9495/vararg-and-substitution-of-primitives-for-type-parameters

### Possible solution

The first part of the if works fine, support for the second would solve this issue

```
override fun getJavaMemberOverride(definition: Definition?, mode: GeneratorStrategy.Mode?): Boolean {
        LOGGER.info("Member Override: Generator mode is $mode for ${definition?.qualifiedName}")
        if (mode == GeneratorStrategy.Mode.POJO && definition?.qualifiedName?.startsWith("itr.itr_ne_") == true) {
            if (NamedEntity.FIELD_NAMES.contains(definition.name)) {
                return true
            }
        }
        if (mode == GeneratorStrategy.Mode.DAO && definition?.qualifiedName?.startsWith("itr.itr_ne_") == true) {
            if (INamedEntityService.FIELD_NAMES.contains(definition.name)) {
                return true
            }
        }
        return super.getJavaMemberOverride(definition, mode)
    }
```

For the varargs but, consider using `Collection<Int>` or something so an interface method can be written that the generated method will properly implement.

### Possible workarounds

Can't really think of a workaround

### jOOQ Version

3.20.0-SNAPSHOT

### Database product and version

Any

### Java Version

Any

### JDBC / R2DBC driver name and version (include name if unofficial driver)

Any

**Comment by lukaseder** [comment]
Thanks for your feature request. Can you please provide a specific example of an interface with its methods, and how you'd like to have that implemented in your DAOs?

**Comment by mikebski** [comment]
In the generated DAO there is a method:

`fun fetchById(vararg values: Int)`

My kotlin interface that I'm adding to the dao via the `DefaultGeneratorStrategy` override tries to define this method and so I need

`override fun fetchById(vararg values: Int)` in my dao- the problem is that my `getJavaMemberOverride` method in my generator strategy is not being called for DAOs so I can't add override to DAO methods...

**Comment by mikebski** [comment]
In other words, the first if works fine but the second is never called  because the generator does not let me do this for a DAO...
```
override fun getJavaMemberOverride(definition: Definition?, mode: GeneratorStrategy.Mode?): Boolean {
        LOGGER.info("Member Override: Generator mode is $mode for ${definition?.qualifiedName}")
        if (mode == GeneratorStrategy.Mode.POJO && definition?.qualifiedName?.startsWith("itr.itr_ne_") == true) {
            if (NamedEntity.FIELD_NAMES.contains(definition.name)) {
                return true
            }
        }
        if (mode == GeneratorStrategy.Mode.DAO && definition?.qualifiedName?.startsWith("itr.itr_ne_") == true) {
            if (INamedEntityService.FIELD_NAMES.contains(definition.name)) {
                return true
            }
        }
        return super.getJavaMemberOverride(definition, mode)
    }
```

**Comment by lukaseder** [comment]
Sorry for the delay, thanks for the example. I can see what you mean now. I'll investigate this soon.

**Comment by lukaseder** [comment]
Looking into this now. I'm not sure if this is the intended effect, but we only have one method to decide whether to add an `override` modifier *per member*. Currently, we're generating up to 3 such methods, meaning they all have to be declared in the interface. For example:

```kotlin
public interface DAOInterface<P> {
    public fun fetchRangeOfI(lowerInclusive: Int?, upperInclusive: Int?): List<P>
    public fun fetchByI(vararg values: Int): List<P>
    public fun fetchOneByI(value: Int): P?
}
```

It would be possible, in principle, to give more fine-grained control over this, but at some point, we're going to be overengineering `DAO` generation.

**Comment by lukaseder** [comment]
This feature hasn't been released yet, so no backports are necessary:

- https://github.com/jOOQ/jOOQ/issues/10776
