### ISSUE TITLE
Streaming query stores all results

### ISSUE THREAD

**Issue by vad0** [jOOQ/jOOQ#16519]
### Expected behavior

When I read data from a DB in a streaming fashion I expect it to process elements one by one and avoid loading the whole dataset into memory. Some batching can exist under the hood, but the whole dataset should not be cached.

### Actual behavior

I get OOM while reading many rows in a streaming fashion. The problem is here: QueryExecutorImpl::procesReqults. 
![image](https://github.com/jOOQ/jOOQ/assets/10008122/662c1327-a663-419b-8b81-535599dda49e)
My understanding is that Tuple contains data about single row. For some reason jOOQ stores all tuples in ArrayList tuples, which becomes extremely large. Why does this ArrayList exist in the first place? It shouldn't be needed when data is processed in a streaming fashion.

### Steps to reproduce the problem

Select a lot of rows from a DB and set small Xmx.

### jOOQ Version

3.19.6

### Database product and version

Postgres 15

### Java Version

21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.3

**Comment by lukaseder** [comment]
Thanks for your message. jOOQ doesn't have any `QueryExecutorImpl` utility, nor does it fetch records into `Tuple` types. jOOQ's own streaming execution methods don't eager fetch your data.

**Comment by vad0** [comment]
![image](https://github.com/jOOQ/jOOQ/assets/10008122/6261f2a9-8086-4672-9cb1-31900125311d)
This is how my call stack looks like. Obviously, jOOQ tries to fetch data lazily, but fails to do so. Yes, QueryExecutorImpl lives in Postgres JDBC driver. But anyway, jOOQ should know how to work with this driver to read data lazily, if laziness is required.

**Comment by lukaseder** [comment]
You can specify the JDBC fetchSize via jOOQ `ResultQuery::fetchSize`.
