### ISSUE TITLE
Dead link in manual section "jooq-and-java-8"

### ISSUE THREAD

**Issue by abhishekomp** [jOOQ/jOOQ#16523]
### The documentation URL

https://www.jooq.org/doc/3.19/manual/getting-started/jooq-and-java-8/

### Feedback

The page mentions about the link [https://blog.jooq.org/java-8-friday-no-more-need-for-orms/] for in-depth reading. However, this page doesn't seem to exist. Please have a check.
Thanks

**Comment by lukaseder** [comment]
Thanks a lot for your report. I've fixed that page. The updated manual will be available in 2-3 hours.
