### ISSUE TITLE
Document missing Parser::parseSelect and Parser::parseStatement methods in manual

### ISSUE THREAD

**Issue by sivaraam** [jOOQ/jOOQ#16531]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-building/sql-parser/sql-parser-api/

### Feedback

The manual is neatly written. It would be great if the APIs of `Parser` such as [`parseSelect`]( https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/Parser.html#parseSelect(java.lang.String)) and [`parseStatement`](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/Parser.html#parseStatement(java.lang.String)) are also covered in the document.

Specifically, I came looking at the document to know what's specifically different between the general `parseQuery` and the specific `parseSelect` APIs. I could understand that it is intuitive to presume that the latter would successfully only parse a SELECT query and fail for other kind of queries. It would be great if the document mentions this explicitly so that we could validate such presumptions rather than having to try it out and cross-check the same 😉 

Having said that, I suppose this is something that could actually be mentioned in the JavaDoc itself 🤔

**Comment by lukaseder** [comment]
Thanks a lot for your suggestions. I agree the methods are missing from that page. I can see adding 1-2 words regarding the types themselves, but it's not worth repeating their semantics everywhere they appear. The types are so ubiquitous. For example, they're distinguished here:

- https://blog.jooq.org/a-brief-overview-over-the-most-common-jooq-types/

**Comment by lukaseder** [comment]
- `parseSelect()` was added in 3.11: https://github.com/jOOQ/jOOQ/issues/7264
- `parseStatement()` was added in 3.12: https://github.com/jOOQ/jOOQ/issues/8290

**Comment by lukaseder** [comment]
I've marginally improved the Javadoc by repeating the fact that `parseSelect()` attempts to parse a SQL string into a `Select` type, both in the header and in the exception message. Though, again, I'm not sure if there's any reasonable way to better convey this. The jOOQ types are self-explanatory, in my opinion. For example, the [`org.jooq.Query`](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/Query.html) Javadoc has an impressive list of "known subinterfaces" (including stuff like `QOM.DropTrigger`, etc.):

![image](https://github.com/jOOQ/jOOQ/assets/734593/9a92641a-5672-4169-8fdb-2f25d2128046)

Whereas the [`org.jooq.Select`](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/Select.html) Javadoc clearly states that it is about `SELECT` statements.

I don't think core concepts need to be repeated all over the documentation. Such repetition might help new users (if readers find it through their path through the docs. There will always be paths that don't lead past such repeated documentation), but it is always noise for more experienced users.
