### ISSUE TITLE
Wrong SEMI JOIN example in manual section "dont-do-this-sql-select-distinct"

### ISSUE THREAD

**Issue by to-do42** [jOOQ/jOOQ#16547]
### The documentation URL

https://www.jooq.org/doc/latest/manual/reference/dont-do-this/dont-do-this-sql-select-distinct/

### Feedback

Hi,

I stumbled upon a part of the last example regarding the SEMI JOIN

```
WHERE author.id IN (
  SELECT book.id
```

but it should not read

```
WHERE author.id IN (
  SELECT book.author_id
```

or did I miss something regarding those SEMI JOINS ?

Kind regards
(and thank you very much for JOOQ)
Dominik

**Comment by lukaseder** [comment]
Yes of course, you're right. Thanks for the report!
