### ISSUE TITLE
Parser.parseQuery: Param.getParamName() returns null

### ISSUE THREAD

**Issue by Captain1653** [jOOQ/jOOQ#16568]
### Your question

Hello.

I need to parse SQL-query and get column names and column values for Postres in java (from text file without database):
`INSERT INTO public."MY_TABLE" ("COLOR", "ID", "PARENT_ID") VALUES ('green', 200, 540)`

I use `org.jooq.Parser`:
```

Parser parser = DSL.using(SQLDialect.POSTGRES).parser();
Query query = parser.parseQuery("INSERT INTO public.\"MY_TABLE\" (\"COLOR\", \"ID\", \"PARENT_ID\") VALUES ('green', 200, 540)");
System.out.println("PARAMS=" + query.getParams());
```

Output is 
`PARAMS={1='green', 2=200, 3=540}`

It works correctly, but I need parameter names, because `PARENT_ID` and `ID` can be in different places in my SQL-query.

Is it possible to get map?
`PARAMS={COLOR='green', ID=200, PARENT_ID=540}`

I tried to use `param.getParamName()`, but result is null.
`System.out.println("ParamName=" + query.getParam("1").getParamName());`

Did I missed something? I think, that is a bug and name should be returned, but I'm not sure.

Kind regards

### jOOQ Version

JOOQ Community Edition 3.16.19

### Database product and version

Postgres

### Java Version

openjdk version "11.0.14.1" 2022-02-08

**Comment by lukaseder** [comment]
Thanks for your message.

There is no name associated with your parameter in your parsed SQL. A parameter name would be this, for example:

```sql
insert into t (a, b, c) values (:a, :b, :c)
```

The parameter name has no relation with the `INSERT` column that you're placing the parameter into. You can think this through and see how complex your expectation will get with only little changes, e.g. what would you expect here?

```sql
insert into t (a, b, c) values ('green' || ' x', 200 + 1, log(500))
```

What's your expectation now? You can easily see that there's obvious relationship between the value `'green'` and the column `a` anymore.

Instead, use the model API and analyse the SQL query directly:

- https://www.jooq.org/doc/latest/manual/sql-building/model-api/

E.g.

```java
if (query instanceof QOM.Insert i) {

    // Analyse these:
    i.$columns();
    i.$values();
}
```

I hope this helps

**Comment by lukaseder** [comment]
Note, you'll have to upgrade in order to use `QOM.Insert`

**Comment by Captain1653** [comment]
Thank you for detailed explanation
