### ISSUE TITLE
Cannot set TIMESTAMPTZ columns converted to java.time.Instant to DSL.now()

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#16564]
### Expected behavior

`jooq.update(T).set(T.A, DSL.now()).execute()` compiles

### Actual behavior

The statement fails to compile.

### Steps to reproduce the problem

Create a table as follows:

```sql
CREATE TABLE t(a TIMESTAMPTZ);
```

Add this forced type:

```
forcedType {
    name = "INSTANT"
    includeExpression = "t\\.a"
}
```

Run the generator and then try to compile this code

```kotlin
jooq.update(T).set(T.A, DSL.now()).execute()
```

### jOOQ Version

3.19.5

### Database product and version

PostgreSQL 15.3

### Java Version

openjdk version "21.0.1" 2023-10-17 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.1

**Comment by lukaseder** [comment]
Use `DSL.currentInstant()`:
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/DSL.html#currentInstant()
