### ISSUE TITLE
Support delimiter expressions in LISTAGG() and GROUP_CONCAT()

### ISSUE THREAD

**Issue by raoua-eng** [jOOQ/jOOQ#16563]
### Use case

When attempting to use the listagg function with chr(10) as a delimiter in jOOQ, the parser encounters an error and fails to parse the SQL query. This prevents the successful parsing of SQL queries that utilize listagg with newline characters as delimiters.

**Reproducer:**
````
public class ListaggReproducer {
    public static void main(String[] args) {
        // JDBC connection parameters
        String url = "jdbc:postgresql://url/username";
        String username = "XXX";
        String password = "XXX";

        // SQL query with listagg and chr(10) delimiter
        String sql = "SELECT listagg(emp_name, chr(10)) WITHIN GROUP (ORDER BY column_name) AS result FROM employe";

        try (Connection conn = DriverManager.getConnection(url, username, password);
             PreparedStatement pstmt = conn.prepareStatement(sql);
             ResultSet rs = pstmt.executeQuery()) {

            // Fetch and print the result
            while (rs.next()) {
                String result = rs.getString("result");
                System.out.println(result);
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

````

### jOOQ Version

3.19.6

### Database product and version

PostgreSQL 14.5

### Java Version

Java 11

**Comment by lukaseder** [comment]
Thanks a lot for your suggestion. I agree, we should support expressions with the `LISTAGG()` separator argument, not just in the parser, but in general.

In general, there is also room for transforming expressions into constants if it's possible. For example `CHR(10)` can be transformed into `'\n'` (where `\n` is the line feed character). This could be done independently of `LISTAGG()` as there are other cases where expressions aren't allowed in some dialects:

- https://github.com/jOOQ/jOOQ/issues/16579
