### ISSUE TITLE
Reactive interface for plain SQL execution

### ISSUE THREAD

**Issue by o-shevchenko** [jOOQ/jOOQ#16580]
### Your question

Is that possible to execute plain SQL and read data as a Flux using JOOQ?

I expect we should be able to have Publisher as return type for `fetch`, but I don't see such a method.
What is the recommended way to run SQL (not using JOOQ API to build SQL)?
Example:
```
val sql = "SELECT * FROM my_table"
val result: Flux<*> = Flux.from(context.fetch(sql))
```

I can use:
```
val stream = Flux.fromStream(Flux.from(context.fetch(sql).stream())
```
But I'm not sure how it will work and want to avoid stream creating

### jOOQ Version

3.19.7

### Database product and version

Snowflake

### Java Version

17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

net.snowflake:snowflake-jdbc:3.15.1

**Comment by lukaseder** [comment]
Thanks for your message. Use `resultQuery(sql)` to get a plain SQL `ResultQuery`. See also:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql/

**Comment by o-shevchenko** [comment]
Thanks for the quick answer @lukaseder !
