### ISSUE TITLE
Ensure PostgreSQL 'serial' Column Type Generates Non-Nullable Kotlin Variable

### ISSUE THREAD

**Issue by MuhamedMagdi** [jOOQ/jOOQ#16593]
### Your question

I encountered an issue where the Kotlin Pojo generated from a SQL table definition incorrectly marks a serial primary key as nullable. Below is the SQL table definition and the corresponding Kotlin data class.

SQL Table Definition:

```sql
CREATE TABLE dummy (
    id serial PRIMARY KEY NOT NULL,
    name VARCHAR (50) NOT NULL
);
```

Generated Kotlin Pojo:
```kt
data class Dummy(
    val id: Int? = null,  // Expected: 'val id: Int', not nullable
    val name: String
): Serializable
```
Expected Behavior:
The ``id`` field in the Kotlin class should not be nullable, reflecting its definition in the SQL table as a non-nullable PRIMARY KEY.

Actual Behavior:
The ``id`` field is generated as a nullable integer (Int?), which is inconsistent with the SQL definition where the ``id`` is explicitly marked as NOT NULL.

Additional Query:
While I am aware this might not constitute an actual bug, I am interested in understanding how to ensure that the ``id`` in the generated Kotlin Pojo remains non-nullable. Any guidance or modifications to the code generation process that could enforce this would be highly appreciated.

### jOOQ Version

JOOQ Open Source 3.19.6

### Database product and version

PostgreSQL 16.2 (Ubuntu 16.2-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit

### Java Version

Java SE 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql.Driver

**Comment by lukaseder** [comment]
See:

- https://github.com/jOOQ/jOOQ/issues/14786
- https://github.com/jOOQ/jOOQ/issues/14787
- https://github.com/jOOQ/jOOQ/issues/14948
- https://github.com/jOOQ/jOOQ/issues/14978

**Comment by lukaseder** [comment]
> While I am aware this might not constitute an actual bug, I am interested in understanding how to ensure that the `id` in the generated Kotlin Pojo remains non-nullable. Any guidance or modifications to the code generation process that could enforce this would be highly appreciated.

jOOQ doesn't offer this, currently. Various rationales given at previous issues.
