### ISSUE TITLE
isTrue() / isFalse() interpreted wrong for Oracle dialect

### ISSUE THREAD

**Issue by jonathan-weiss** [jOOQ/jOOQ#16610]
### Expected behavior

The methods `isTrue()` / `isFalse()` on a field of type `org.jooq.Field<Boolean>` should respect the configured dialect.
ORACLE SQL: `<TABLE>.<FIELD> = 1`
POSTGRES SQL: `<TABLE>.<FIELD> = true`

This is working with JOOQ 3.17.7 (org.jooq.pro-java-8:jooq)
This is not working with JOOQ 3.19.7 (org.jooq.pro-java-8:jooq)

### Actual behavior

ORACLE SQL: `<TABLE>.<FIELD> = true`
POSTGRES SQL: `<TABLE>.<FIELD> = true`

### Steps to reproduce the problem

Given a simple table "MANDANT" with a boolean field "AKTIV":
```kotlin
val jooqConf: Configuration = DefaultConfiguration().set(SQLDialect.ORACLE)
val selectQuery = DSL.using(jooqConf).select(DSL.asterisk()).from(MandantDsl.TABLE).where(MandantDsl.TABLE.AKTIV.isTrue).sql
// selectQuery is "select * from MANDANT where MANDANT.AKTIV = 1" in JOOQ 3.17.7
// selectQuery is "select * from MANDANT where MANDANT.AKTIV = true" in JOOQ 3.19.7

```

### jOOQ Version

jOOQ Enterprise 3.19.7 for JAVA 8

### Database product and version

not relevant

### Java Version

openjdk version "1.8.0_392"

### JDBC / R2DBC driver name and version (include name if unofficial driver)

not relevant, but com.oracle.database.jdbc:ojdbc8:12.2.0.1.0

**Comment by lukaseder** [comment]
Thanks for your report.

jOOQ 3.19 added support for Oracle 23c:

- https://github.com/jOOQ/jOOQ/issues/14011

23c finally (!) has `BOOLEAN` type support. You can see database version support here:
https://www.jooq.org/download/support-matrix

If you're using `SQLDialect.ORACLE` (the family), that will always map to the latest dialect version of the family. If you wish to continue working with older Oracle versions, please use the relevant dialect version.

Can you confirm this addresses the issue you're seeing?

**Comment by jonathan-weiss** [comment]
It was exactly that, thank you very much for your quick response.
I never thought I'd see Oracle natively supporting Boolean in my lifetime :-)

Beschti Grüess us dä Ergon Zürich, Jonathan

**Comment by lukaseder** [comment]
@jonathan-weiss You'll like to hear what else they support in 23c!
