### ISSUE TITLE
Support for generation of different SQL

### ISSUE THREAD

**Issue by Beliefuture** [jOOQ/jOOQ#16611]
### Use case

Thanks for your efforts on this great project!

I have two questions listed below:

1. Does this project provide the off-the-shelf function to generate different SQL by traversing the syntax AST from scratch (e.g., generate different syntactically correct SQL queries just like randomly walking through a superset AST, i.e., with all the clauses supported)?

2. What should be done if I want to support a new DBMS dialect?

### jOOQ Version

3.17.2

### Database product and version

PostgreSQL 12

**Comment by lukaseder** [comment]
Thanks for your message.

> 1. Does this project provide the off-the-shelf function to generate different SQL by traversing the syntax AST from scratch (e.g., generate different syntactically correct SQL queries just like randomly walking through a superset AST, i.e., with all the clauses supported)?

I'm afraid, I don't know what this means.

> 2\. What should be done if I want to support a new DBMS dialect?

See:

- https://github.com/jOOQ/jOOQ/discussions/14059

**Comment by Beliefuture** [comment]
> Thanks for your message.
> 
> > 1. Does this project provide the off-the-shelf function to generate different SQL by traversing the syntax AST from scratch (e.g., generate different syntactically correct SQL queries just like randomly walking through a superset AST, i.e., with all the clauses supported)?
> 
> I'm afraid, I don't know what this means.
> 
> > 2. What should be done if I want to support a new DBMS dialect?
> 
> See:
> 
> * [Support for new dialects #14059](https://github.com/jOOQ/jOOQ/discussions/14059)

Hi! 

For 1., I want to generate random SQL queries strictly conform to the standard grammars with different clauses, i.e., the same as synthesize different ASTs.

**Comment by lukaseder** [comment]
Like a fuzzer? No, we don't offer such functionality

**Comment by Beliefuture** [comment]
> Like a fuzzer? No, we don't offer such functionality

Yes, just generate different SQL queries of high diversity. Could I ask if the `fuzzer` mentioned refer to specific projects?

**Comment by lukaseder** [comment]
It's a well defined concept in software testing: https://en.wikipedia.org/wiki/Fuzzing
