### ISSUE TITLE
Write flux stream into a table

### ISSUE THREAD

**Issue by o-shevchenko** [jOOQ/jOOQ#16612]
### Your question

Is that posible to write data stream into a table using JOOQ?
That's how we read data:
```
val result =  Flux.from(context.resultQuery(sql))
```
Is that possible to write Flux into a table? I don't see API for that.
It should be supported to write data into a table that already exists or into a new table. So, I expect we should be able to specify SQL instead of using JOOQ API.

### jOOQ Version

3.19.7

### Database product and version

Snowflake

### Java Version

18

### JDBC / R2DBC driver name and version (include name if unofficial driver)

net.snowflake:snowflake-jdbc:3.16.0

**Comment by lukaseder** [comment]
Use the `INSERT` statement:
https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/insert-statement

It comes in different flavours. Either you create one statement per row, and execute them individually, or you batch them, or your create a bulk insert statement (a single `INSERT` with multiple rows)

I hope this helps

**Comment by o-shevchenko** [comment]
Thanks for the answer @lukaseder . I see INSERT but I don't see it's possible to use stream to write data. We need to write a big data set with billions of records, so we can't create INSERT for each raw. 
Could you point me to a doc or example with writing flux stream into a table?
Thanks!

**Comment by lukaseder** [comment]
There's no specific manual page for this particular use-case. Test the various approaches that I've mentioned (`RowCountQuery` also extends `Publisher`, so there's that), including bypassing jOOQ / R2DBC / SQL for your inserts to find the best / fastest approach for your needs.

**Comment by o-shevchenko** [comment]
Hi
I wrote the following example for write:
```Kotlin
val insertQueries = batch.map { record ->
                    val columns = record.fields?.map { DSL.field(DSL.name(it.key)) }
                    val values = record.fields?.map { it.value }
                    batchContext.insertInto(DSL.table(DSL.name(databaseId, schemaId, tableId)))
                        .columns(columns)
                        .values(values?.toList())
                }
                log.debug("Executing batch insert of size ${batch.size}")
                batchContext.batch(insertQueries).execute()
```
but this code is very slow.

I'm training to use Loader API instead. But I'm not sure how to write data into a table:
```Kotlin
private fun processBatch(
        databaseId: String,
        schemaId: String,
        tableId: String,
        batch: List<DataRecord>,
        dslContext: DSLContext
    ): Mono<*> {
        return Mono.fromCallable {
            val table = DSL.table(DSL.name(databaseId, schemaId, tableId))
            val loader = dslContext.loadInto(table)
                .onErrorIgnore()
                .bulkAll()
                .commitAll()
                .batchAll()
                .loadRecords(batch.map { it.toRecord(dslContext, table) })
                .fieldsCorresponding()
                .execute().also {
                    log.debug("Batch insert completed for ${batch.size} records")
                }
            loader.processed()
        }
        ...
        fun DataRecord.toRecord(dslContext: DSLContext, table: Table<*>): Record {
    val record = dslContext.newRecord(table)
    this.fields?.forEach { dataField ->
        record.set(DSL.field(DSL.name(dataField.key)), dataField.value)
    }
    return record
}
 ```
 For our use case here we just need to write data into a table. The table name is provided at the run time. So, I don't have a generated table. And when I'm trying to use `loadRecords` and create jooq.Record from my DTO, I'm getting:
 ```
 Method threw 'java.lang.IllegalArgumentException' exception.
 Field "field_name" is not contained in row type ()
 ```
 
 @lukaseder, Could you let me know how we can write data faster and utilize Loader API?
 Thanks!
