### ISSUE TITLE
Visibility when UNotYetImplemented of ContraintImpl will be addressed ?

### ISSUE THREAD

**Issue by davidouagne** [jOOQ/jOOQ#16622]
### Your question

Hello,

Do you have visibility on the implementation date of the ConstraintImpl class with the QOM class?

Put differently, when will the 'UNotYetImplemented' interface of the ConstraintImpl class be handled?

Thank you for your very useful work!

### jOOQ Version

3.19.7

### Database product and version

PostgreSQL 15.6

**Comment by lukaseder** [comment]
There's no such "planned date," though we can prioritise. What's the use-case of getting access to constraint information?

**Comment by davidouagne** [comment]
Hello,

Thank you for your quick response, unlike mine ;-)

My need is to use your library to produce diagrams using PlantUML. As it stands, it is possible to handle constraints using a Regex approach, thereby completing the parsing task. However, it would be more robust if your library performed this task, wouldn't it?

**Comment by lukaseder** [comment]
I'm implementing support for this in jOOQ 3.20.0 now.
