### ISSUE TITLE
Wrong title in manual section "alter-table-drop-foreign-key"

### ISSUE THREAD

**Issue by MikePSQR** [jOOQ/jOOQ#16679]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-building/ddl-statements/alter-statement/alter-table-statement/alter-table-drop-foreign-key/

### Feedback

The headline says "drop primary key" instead of "drop foreign key"

**Comment by lukaseder** [comment]
Thanks, fixed. The fix will be live in 2-3h
