### ISSUE TITLE
meta() should provide information about custom data type

### ISSUE THREAD

**Issue by rbuehlma** [jOOQ/jOOQ#16785]
### Use case

We want to write some string value to a custom typed field where the application has no knowledge of the type.

The idea is to read out the field type and then use a SQL cast (Postgres in our case) to convert the string value to the desired type.

```
        dslContext().execute("CREATE TYPE custom_enum AS ENUM ('value1', 'value2');")
        dslContext().execute("CREATE TABLE test_table ( field1 custom_enum )")

        var field = dslContext().meta().getTables(table.name).first().field(field1)!!

        field.dataType.name // should be "custom_enum" but is "other"
```

### jOOQ Version

3.18.7

### Database product and version

PostgreSQL

**Comment by lukaseder** [comment]
Thanks for your message.

See:

- https://github.com/jOOQ/jOOQ/issues/9509
