### ISSUE TITLE
NullPointerException in MetaImpl when looking up a dropped table from a disabled foreign key in MySQL

### ISSUE THREAD

**Issue by arne-kroeger** [jOOQ/jOOQ#16782]
### Use case

If you create a FK reference to an existing table and disable the foreign key checks and delete the referenced table and activate the check again (or import only parts of a database) the FK references a not existing table. 

If using the meta data package of jooq you will get a NullPointerException in MetaImpl: 

```java
Table<Record> pkTable = MetaImpl.this.lookupTable(schema, (String)k.get(2, String.class));
```

as pkTable ist null here you get the exception some lines later when accessting `pkTable.field`.

### Possible solution

There should be a way to skip or handle these errors without changing the database structure as it might be out of scope. This could enable parsing without permission of changing source data structure.

Tell MySQL and MariaDB to fix these broken status... ;-)

### Possible workarounds

Fixing the root problem inside the database by correct or remove the FKs that references unknown tables or skipping the complete tables with these FKs.

### jOOQ Version

JOOQ 3.19.8

### Database product and version

10.11.5-MariaDB-1:10.11.5+maria~ubu2204-log

### Java Version

openjdk 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.mysql.cj.jdbc.Driver

**Comment by lukaseder** [comment]
Thanks for your report. I'd say this is a bug. I vaguely recall handling this case in the code generator. We simply ignore foreign keys whose referenced table can't be looked up for any reason (including the table being excluded by code generation).

Should be a simple fix.

**Comment by arne-kroeger** [comment]
I thought about it and had a bug report first but thought about fixing a bug that shouldn't be possible as it breaks the logic on database side wouldn't be fair. 

Thanks for fixing!

**Comment by lukaseder** [comment]
> I thought about it and had a bug report first but thought about fixing a bug that shouldn't be possible as it breaks the logic on database side wouldn't be fair.

jOOQ isn't opinionated about your database design (I am, of course, but jOOQ isn't). If your RDBMS allows a thing, then jOOQ should be able to handle that thing.

**Comment by lukaseder** [comment]
With a test like this:

```java
    @Test
    public void testMySQLMetaWithDanglingForeignKey() throws Exception {
        Table<?> t = table(name("t"));
        Table<?> u = table(name("u"));
        Field<Integer> i = field(name("i"), INTEGER);

        try {
            create().createTable(t)
                    .column(i)
                    .primaryKey(i)
                    .execute();

            create().createTable(u)
                    .column(i)
                    .constraint(foreignKey(i).references(t, i))
                    .execute();

            create().execute("SET FOREIGN_KEY_CHECKS=0");
            create().dropTable(t).execute();
            create().execute("SET FOREIGN_KEY_CHECKS=1");

            Table<?> u2 = new MetaDataTests<>(this).metaTable("u");
            assertEquals(0, u2.getReferences().size());
        }
        finally {
            ignoreThrows(() -> create().dropTable(u).execute());
            ignoreThrows(() -> create().dropTable(t).execute());
        }
    }
```

I can reproduce this NPE in the latest version:

```
java.lang.NullPointerException: Cannot invoke "org.jooq.Table.field(String)" because "pkTable" is null
	at org.jooq.impl.MetaImpl$MetaTable.lambda$9(MetaImpl.java:1218)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:986)
	at org.jooq.impl.MetaImpl$MetaTable.getReferences(MetaImpl.java:1194)
	at org.jooq.impl.FilteredMeta$FilteredTable.getReferences(FilteredMeta.java:517)
	at org.jooq.test.MySQLTest.testMySQLMetaWithDanglingForeignKey(MySQLTest.java:1350)
```
