### ISSUE TITLE
Inserting data with pre-existing audit column data

### ISSUE THREAD

**Issue by wblucca** [jOOQ/jOOQ#16781]
### Your question

I am using generated code and an audit provider to set some audit fields on inserts and updates. However, I'm trying to reuse the same generated code for an insert that migrates data with pre-existing metadata. In that statement I need to preserve the values in the `CREATED` and `CREATEDBY` audit columns. In the generated table class, these fields have the following `AuditGenerators` to leverage an audit provider in the DSL configuration:
```Java
new org.jooq.impl.AuditGenerator<>(org.jooq.AuditType.TIMESTAMP, org.jooq.GeneratorStatementType.INSERT)
new org.jooq.impl.AuditGenerator<>(org.jooq.AuditType.USER, org.jooq.GeneratorStatementType.INSERT)
```

In any other CRUD operation with jOOQ, I want the audit provider to fill these and the other audit fields in, but for this specific statement for the data migration, I want it to keep the values specified in the insert statement. I'm currently creating records from a DomainObject class using the `.set...()` methods, inserting them in a single statement, then returning the new IDs:
```Java
public List<Long> doImport(List<DomainObject> data) {
  return jooq.insertInto(TABLENAME)
      .set(data.stream().map(this::objToRecord).toList())
      .returningResult(TABLENAME.ID)
      .fetch()
      .into(Long.class);
}

private TablenameRecord objToRecord(DomainObject obj) {
  return jooq.newRecord(TABLENAME)
      .setColumn1(obj.column1())
      .setColumn2(obj.column2())
      .setCreated(obj.created())
      .setCreatedby(obj.createdby());
}
```

Doing this causes the audit provider to still overwrite the `CREATED` and `CREATEDBY` fields before inserting.

What is the best way to have jOOQ use the fields in the record object being inserted for just this query? Does it need its own `AuditProvider` for just this use case?

### jOOQ Version

jOOQ Professional Edition 3.19.5

### Database product and version

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production (Version 19.19.0.0.0)

### Java Version

openjdk version "21.0.2" 2024-01-16 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.oracle.database.jdbc:ojdbc11

**Comment by lukaseder** [comment]
Thanks for your message.

The section about audit columns has a small disclaimer at the bottom, which subtly hints at one way to circumvent the audit logic:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-audit/

> The computed column expression (and thus the audit expressions) is a property of the generated [org.jooq.DataType](https://www.jooq.org/javadoc/latest/org/jooq/DataType.html). As such, the property can only be enforced on expressions which make this flag available to jOOQ. For example, if you're using [plain SQL templates](https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/) without passing along a DataType with the computed expression enabled, then the feature cannot be enforced.

So, any plain SQL template that lacks the audit column's `DataType` reference (containing the `AuditGenerator` reference) will be able to help here. It's not very obvious, though.

We'll also soon support turning off the feature using a new `Settings` flag:

- https://github.com/jOOQ/jOOQ/issues/14775

I hope this helps

**Comment by lukaseder** [comment]
See also:

- https://github.com/jOOQ/jOOQ/issues/14768

**Comment by wblucca** [comment]
Awesome! Thanks for pointing out the workaround and the new feature. That will be really helpful.
