### ISSUE TITLE
Update jooq-meta-extensions-hibernate to work with Hibernate6

### ISSUE THREAD

**Issue by kennymacleod** [jOOQ/jOOQ#16809]
### Use case

The `JpaDatabase` codegen tool does not work with Hibernate 6, due to API changes between 5.6 and 6, some of which seem rather non-ovious.

### jOOQ Version

3.19 OS

### Database product and version

n/a

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/13721
