### ISSUE TITLE
Deprecate internal, protected AbstractRecord.from(Record) method

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16815]
There's a historic, internal, `protected` method `AbstractRecord.from(Record)`:

```java
    /**
     * This method was implemented with [#799]. It may be useful to make it
     * public for broader use...?
     */
    protected final void from(Record source) {
        ConverterContext cc = Tools.converterContext(this);

        for (Field<?> field : fields.fields.fields) {
            Field<?> sourceField = source.field(field);

            if (sourceField != null && source.changed(sourceField))
                Tools.setValue(this, field, source, sourceField, cc);
        }
    }
```

This method is not used internally, as there are better replacements. It is also not currently used by generated code. Still, we can't simply remove it because it is `protected`, so there's a slight chance that users implemented code generation extensions which call this method, so let's deprecate it first, before removal.

**Comment by Teutron-flo** [comment]
@lukaseder, after upgrading from 3.19 to 3.20 and rerun of the code generator, I can see that the from() function is used inside my generated classes, one example:

	public OfferDataRecRecord printContents(
		  String inSourceOfOfferData
	) {
		PrintContents p = new PrintContents();
		p.setSelf(this);
		p.setInSourceOfOfferData(inSourceOfOfferData);

		p.execute(configuration());
		from(p.getSelf());
		return p.getSelf();
	}

So I can not confirm your sentences: "It is also not currently used by generated code"
is that maybe an issue in the future?

BR
Florian

**Comment by lukaseder** [comment]
Thanks for your message @Teutron-flo. It appears that this deprecation was premature indeed. I had overlooked the UDT member procedure test cases. Will revert the deprecation.
