### ISSUE TITLE
Cannot find the $ prefix used for named parameters in generated SQL

### ISSUE THREAD

**Issue by EMIR1HUB** [jOOQ/jOOQ#16816]
### Your question

There is a problem when generating a query on Postgres with parameters. 
Example:

```sql
SELECT * FROM some WHERE id = :1 and id =:2   -- values are substituted
SELECT * FROM some WHERE id = $1 and id = $2  -- values are not substituted.
```

I read in the documentation and in discussions that it is necessary to specify setParamType(ParamType.NAMED) and to explicitly specify the prefix setRenderNamedParamPrefix(“$”), but according to the results jooq does not see these prefixes. 

this is what the config looks like:

```java
@Bean
  @Primary
  public org.jooq.Configuration jooqConfiguration(ConnectionProvider connectionProvider,
      Settings jooqSettings) {
    DefaultConfiguration configuration = new DefaultConfiguration();
    configuration.setSQLDialect(datasourceConfig().getSqlDialect());
    jooqSettings.setParamType(ParamType.NAMED);
    jooqSettings.setRenderNamedParamPrefix("$");
    jooqSettings = jooqSettings.withExecuteLogging(true);
    configuration.setSettings(jooqSettings);
    configuration.setConnectionProvider(connectionProvider);
    configuration.set(executeListeners);
    return configuration;
  }
```

  I can't figure out what the error could be that it can't and use the `$` prefix.

### jOOQ Version

3.19.3

### Database product and version

PostgreSQL

### Java Version

17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:jar:42.5.2

**Comment by lukaseder** [comment]
Thanks for your message.

But how are you using jOOQ? I don't see why the `$` prefix is important to you. You're not using R2DBC, I take? Nor the parser?

Can you show an example of a jOOQ query that doesn't work for you, and how you execute/parse/use it, etc.?

**Comment by EMIR1HUB** [comment]
Запросы я подавал в формате PL/pgSQL, но для откладки решил использовать простой запрос в формате 
`SELECT country_id FROM country WHERE name = $1`

который передается в метод вместе с массивом параметров

int affectedRows = dsl.query(parameters.getSql(), parameters.getSqlParameters()).execute(); 

на момент входа в метод query он выбрасывает ошибку "параметр $1 не существует", но когда использую `:1`, то данные подставляются как нужно. Вы правы R2DBC не использую.

**Comment by lukaseder** [comment]
Ah, I see what you're trying to do. jOOQ's plain SQL templates don't support alternative named parameter prefixes yet, see:

- https://github.com/jOOQ/jOOQ/issues/8822

There's currently no workaround for this. I hope this helps.
