### ISSUE TITLE
YearToSecond on INTERVAL documentation

### ISSUE THREAD

**Issue by mihalyr** [jOOQ/jOOQ#16826]
### The documentation URL

https://www.jooq.org/doc/latest/manual/reference/reference-data-types/data-types-intervals/

### Feedback

Hi, would it be possible to mention `YearToSecond` on the [INTERVAL](https://www.jooq.org/doc/latest/manual/reference/reference-data-types/data-types-intervals/) documentation page? Perhaps even adding a few examples. My colleague today was going to gave up on trying to do `now() - interval 'some interval'` with JOOQ and was about to switch to calculating the deadline in Java, as we did not notice `YearToSecond` existed at first.

**Comment by lukaseder** [comment]
Thanks for the feedback. Yes indeed:
https://github.com/jOOQ/jOOQ/issues/4008

Closing this as a duplicate
