### ISSUE TITLE
Wrong DataAccessException to IntegrityConstraintViolationException translation for DuckDB

### ISSUE THREAD

**Issue by dk2k** [jOOQ/jOOQ#16834]
### Expected behavior

Line 3634 - string is lower cased
Line 3638 - check against "constraint Error: not nullL constraint failed" with a capital letter E. As a result the code in the corresponding block is unreachable.

### Steps to reproduce the problem

Line 3634 - string m is lower cased
Line 3638 - check against "constraint Error: not nullL constraint failed" with a capital letter E. As a result the code in the corresponding block is unreachable.

### jOOQ Version

main

### Database product and version

whatever

### Java Version

whatever

### JDBC / R2DBC driver name and version (include name if unofficial driver)

whatever

**Comment by lukaseder** [comment]
Thanks for your report. Will look into this right away.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.11 (https://github.com/jOOQ/jOOQ/issues/16835)
