### ISSUE TITLE
Confusion on `COLUMN is true` vs. `COLUMN = true`

### ISSUE THREAD

**Issue by jankoh** [jOOQ/jOOQ#16843]
### Your question

Hello,

we use (on PostgreSQL) a couple of state tables of the following form:
```sql
-- whatever enitity
create table entity(
    entity_id bigint not null,
    ...
    primary key (entity_id)
);

-- the state table, (every insert sets all older rows of entity_id to active = false via trigger)
create table entity_state
(
    entity_id bigint not null,
    type_status varchar(8) not null,
    date_and_time timestamptz not null,
    active bool not null,
    user_id bigint not null,
    primary key (entity_id, date_and_time)
);
```
to keep track of status changes, their relevant timestamps and the users making the change. Selecting data in a specific status information via Jooq is usually done using some kind of
```kotlin
dsl.select(asterisk())
    .from(entity)
    .join(entity_state).on(
        entity.ENTITY_ID.eq(entity_state.ENTITY_ID)
            .and(entity_state.TYPE_STATUS.eq("DESIRED_STATUS"))
            .and(entity_state.ACTIVE.isTrue)
)
```

In an earlier version of jooq (I think 3.18, but I'm not quite sure), this translated to
```sql
select *
from entity
join entity_state
    on entity.entity_id = entity_state.entity_id
    and entity_state.type_status = 'DESIRED_STATUS'
    and entity_state.active is true
```
However, 3.19 translates it to 
```sql
select *
from entity
join entity_state
    on entity.entity_id = entity_state.entity_id
    and entity_state.type_status = 'DESIRED_STATUS'
    and entity_state.active = true
```

For state tables holding a lot of data, we generate partial indexes in the form of 
```sql
create unique index entity_state_active_idx on entity_state (entity_id, type_status) where active is true;
```
so the generated selection ca use that index when the old Jooq made use of the `is` operator. In 3.19 the index isn't used anymore, we ould have to regenerate it in the form
```sql
create unique index entity_state_active_idx on entity_state (entity_id, type_status) where active = true;
```

So my question is: was this change intended, so we need to update our indexes or might this be some kind erroneous behaviour? Are we maybe abusing the `isTrue` method of `Field` and should use a different operator? 

I tried to find info in the documentation, but maybe missed the relevant part.

Thanks a lot and best regards, Jan

### jOOQ Version

3.19.10

### Database product and version

PostgreSQL 15.7 on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

### Java Version

openjdk version "21.0.3" 2024-04-16 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.3

**Comment by lukaseder** [comment]
Thanks for your message.

> In an earlier version of jooq (I think 3.18, but I'm not quite sure), this translated to

I don't recall that having ever been the case. Try this with jOOQ 3.18.0:

```java
System.out.println(DSL.field("a", SQLDataType.BOOLEAN).isTrue());
```

It prints:

```sql
a = true
```

In fact, this issue has been around forever, and is unlikely to be fixed soon due to backwards compatibility reasons:

- https://github.com/jOOQ/jOOQ/issues/4153

jOOQ never correctly implemented the standard SQL `IS TRUE` / `IS FALSE` / `IS UNKNOWN` predicates.

The only way you can achieve this currently is by using a plain SQL template. But why even compare the non-null column with `TRUE`? Why not just declare this?

```sql
create unique index entity_state_active_idx on entity_state (entity_id, type_status) where active;
```

And query this?

```java
dsl.select(asterisk())
    .from(entity)
    .join(entity_state).on(
        entity.ENTITY_ID.eq(entity_state.ENTITY_ID)
            .and(entity_state.TYPE_STATUS.eq("DESIRED_STATUS"))
            .and(entity_state.ACTIVE)
)
```

**Comment by jankoh** [comment]
Ah, I wasn't aware this
```kotlin
dsl.select(asterisk())
    .from(entity)
    .join(entity_state).on(
        entity.ENTITY_ID.eq(entity_state.ENTITY_ID)
            .and(entity_state.TYPE_STATUS.eq("DESIRED_STATUS"))
            .and(entity_state.ACTIVE)
)
```
would work as expected. I must admit, I find it looking a bit weird. but In the end, it should be equivalent to using "=" in both cases. And, of course, you're right, this is completely fine for a non-null column, since the only difference would occur in the null-case.

I just stumbled across this, since we changed our indexes from `active = true` to `active is true` since the queries used `is` and so the indexes were not used. I'm not sure what cased this, though...

Tnanks again, and best wishes!

**Comment by lukaseder** [comment]
> I must admit, I find it looking a bit weird. but In the end, it should be equivalent to using "=" in both cases.

Yes, it's equivalent, just like these are equivalent in Java:

```java
if (active) { ... }
if (active == true) { ... }
```

I would say the `== true` variant is less idiomatic in Java, and probably also in SQL, once you get used to using `BOOLEAN` columns as ordinary predicates...
