### ISSUE TITLE
onConflict should not require column name(s) or constraint name(s)

### ISSUE THREAD

**Issue by reubenfirmin** [jOOQ/jOOQ#16850]
### Expected behavior

Suppose a join table:

```
A: uuid not null
B: uuid  (fk)
C: uuid  (fk)
```

with unique constraints:

```
A,B
B,C
```

When I insert into this table, I should be able to provide an onConflict handler _without_ also specifying which columns can cause the conflict, because either of these unique constraints could fire. This is quite possible in SQL, where `conflict_target` is optional.

### Actual behavior

The last onConflict to be specified overrides any prior onConflicts set; all must have either constraint name or columns specified.

### Steps to reproduce the problem

Described above

### jOOQ Version

Jooq open source 3.18.6

### Database product and version

Postgres 15

### Java Version

OpenJDK version 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.1

**Comment by lukaseder** [comment]
Thanks for your message.

In PostgreSQL, given:

```sql
create table t (
  a int not null,
  b int,
  c int,
  
  constraint uk_1 unique (a, b),
  constraint uk_2 unique (b, c)
);
```

This is possible:

```sql
insert into t values (1, 2, 3) on conflict do nothing;
```

And supported in jOOQ via

```java
insertInto(T).values(1, 2, 3).onConflictDoNothing();
```

This, however, isn't possible:

```sql
insert into t values (1, 2, 3) on conflict do update set c = 1;
```

The error is:

```
ERROR: ON CONFLICT DO UPDATE requires inference specification or constraint name
  Hint: For example, ON CONFLICT (column_name).
```

SQLite has a more general implementation, which we might support soon (though not sure if it's possible to emulate on PostgreSQL):

- https://github.com/jOOQ/jOOQ/issues/13274

When you work with MySQL's `onDuplicateKeyUpdate()` clause, then jOOQ will render a `MERGE` statement that includes all the known unique constraints in the `MERGE`'s `ON` predicate. Perhaps that's what you were looking for.

> The last onConflict to be specified overrides any prior onConflicts set; all must have either constraint name or columns specified.

I'm not sure how you're doing this, it isn't possible using the DSL API, unless you do some tricks (e.g. assigning `Step` types to local variables and relying on the current mutable implementation, which is discouraged as per the Javadoc).

So, I don't think we have a bug or limitation here.
