### ISSUE TITLE
Add a configuration example to the manual section "converter-provider"

### ISSUE THREAD

**Issue by itisbugra** [jOOQ/jOOQ#16866]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-execution/fetching/converter-provider/

### Feedback

No information regarding how do you register the new `ConverterProvider` instance to the jOOQ side.

**Comment by lukaseder** [comment]
Thanks a lot for your report. Indeed, the precedent would be a few sections before, the `RecordMapperProvider` SPI, which is documented here:

- https://www.jooq.org/doc/latest/manual/sql-execution/fetching/recordmapperprovider/

All SPIs are configured the same way, but it's obviously useful to show an example on every page, for this.

**Comment by lukaseder** [comment]
Fixed. The manual will be updated soon.
