### ISSUE TITLE
TIMESTAMP(0) doens't work in DDL statements as the datetime precision is simply omitted

### ISSUE THREAD

**Issue by MikePSQR** [jOOQ/jOOQ#16865]
### Expected behavior

`SQLServerDataType.DATETIME2.precision(0)` should result into `datetime2(0)`

### Actual behavior

`SQLServerDataType.DATETIME2.precision(0)` results into `datetime2` which is effectively `datetime2(7)`

### Steps to reproduce the problem

`context.createTable("table") .column("datetime", SQLServerDataType.DATETIME2.precision(0)).getSQL()`

### jOOQ Version

3.19.8

### Database product and version

Microsoft SQL Server 2019 (RTM-CU25) (KB5033688) - 15.0.4355.3 (X64) Developer Edition (64-bit) on Linux (Ubuntu 20.04.6 LTS) <X64>

### Java Version

openjdk 17.0.11 2024-04-16

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.microsoft.sqlserver:mssql-jdbc:11.2.3.jre17

**Comment by lukaseder** [comment]
Thanks a lot for your report.

Please note the `SQLServerDataType` class is deprecated. You shouldn't reference it directly. Though, the sam ething happens when using the recommended alternative: `SQLDataType.TIMESTAMP(0)`.

I'll look into this soon.

**Comment by lukaseder** [comment]
Looking into this now. Interestingly, we get it right for casts:

```java
String ts6 = "2000-01-01 01:15:30.123456";
String ts3 = "2000-01-01 01:15:30.123000";
String ts0 = "2000-01-01 01:15:30.000000";

assertEquals(Timestamp.valueOf(ts6), create().select(cast(ts6, TIMESTAMP(6))).fetchOne(0));
assertEquals(Timestamp.valueOf(ts3), create().select(cast(ts6, TIMESTAMP(3))).fetchOne(0));
assertEquals(Timestamp.valueOf(ts0), create().select(cast(ts6, TIMESTAMP(0))).fetchOne(0));
```

E.g. the last query produces this:

```sql
select cast(? as datetime2(0))
```

Also, it appears this isn't SQL Server specific. E.g. in PostgreSQL, when parsing this:

```sql
select cast(null as timestamp(0));
create table t (ts timestamp(0));
```

We're generating:

```sql
select cast(null as timestamp(0));
create table t (
  ts timestamp
);
```

See:

- https://www.jooq.org/translate

The reason is that we're checking `DataType.precision() > 0` rather than `DataType.precisionDefined()`

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.11 (https://github.com/jOOQ/jOOQ/issues/16897)
- 3.18.18 (https://github.com/jOOQ/jOOQ/issues/16898)
- 3.17.27 (https://github.com/jOOQ/jOOQ/issues/16899)

**Comment by MikePSQR** [comment]
@lukaseder Just checked the new release (3.19.11) and `datetime2` is fixed, but the issue is still present for `SQLDataType.LOCALTIME(0)` on SQL Server

**Comment by lukaseder** [comment]
Thanks for following up, @MikePSQR. I've created a new issue for this:

- https://github.com/jOOQ/jOOQ/issues/17069

**Comment by lukaseder** [comment]
I'll just check `OFFSETDATETIME` as well, to be sure. Will update #17069 in case that also fails.

**Comment by lukaseder** [comment]
Also related, but not the same issue, we don't really support binding any `TIME` values with precision, as we're internally still using the `java.sql.Time` API from JDBC, which truncates precisions:

- https://github.com/jOOQ/jOOQ/issues/17070

Will fix that as well, soon.
