### ISSUE TITLE
Add support for XuGuDB

### ISSUE THREAD

**Issue by kimwqy** [jOOQ/jOOQ#16896]
### Use case

A new MySQL compatible RDBMS will be available soon, it seems:https://www.xugudb.com/

### jOOQ Version

3.12.4

### Database product and version

XuGuDB 12.0.0

**Comment by lukaseder** [comment]
Thanks for your suggestion.

It is always interesting to think about new dialects. However, our roadmap is already full with requests for dialects that are ranking higher up on this list:
https://db-engines.com/en/ranking

If XuGuDB ever makes it to this list, and if we can connect reasonable business to such an integration, we might consider it.

Looking at the website, I have doubts that this will happen very soon. I'm closing this for now. We'll re-open it when (if) it ever becomes more relevant to our customer base.
