### ISSUE TITLE
Wrong syntax rendered for SQL Server UNION queries with LIMIT in their subqueries

### ISSUE THREAD

**Issue by db2222** [jOOQ/jOOQ#16912]
### Expected behavior

Only top should be generated in this scenario to have a valid MSSQL syntax.

### Actual behavior

Additionally to top also offset / fetch next are generated leading to an invalid statement.

### Steps to reproduce the problem

Given the following jOOQ query:
```
select(one()).from(dummy).limit(1)
.union(select(zero()).from(dummy).limit(1))
.orderBy(one())
```

This generates the following invalid syntax with SQL Server (Oracle and H2 are correct):
```
(
  select top 1 1
  from dummy
  offset 0 rows
  fetch next 1 rows only
)
union (
  select top 1 0
  from dummy
)
order by 1
```

The problem is that offset / fetch next is generated for the first part of the union even though it should only be top.
It only occurs with >= SQLDialect.SQLSERVER2012.
With SQLSERVER2008 it is fine as there is no offset / fetch next logic.

Could it maybe be (partly) related to #7467?

Side note: The SQL from above obviously does not really make any sense.
It is just boiled down from an actual SQL to pinpoint/highlight the issue 😉

### jOOQ Version

jOOQ Professional Edition 3.17.4

### Database product and version

SQL Server >= 2012

**Comment by lukaseder** [comment]
Thanks for your report. This looks similar to this one:

- https://github.com/jOOQ/jOOQ/issues/7467

Will look into it right away.

**Comment by lukaseder** [comment]
The case where an `OFFSET` clause is specified in addition to `LIMIT` is harder to get right, due to #7467. I'll still look into both of these issues, though the `LIMIT` only case is much easier to fix.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.11 (https://github.com/jOOQ/jOOQ/issues/16913)
- 3.18.18 (https://github.com/jOOQ/jOOQ/issues/16914)
- 3.17.27 (https://github.com/jOOQ/jOOQ/issues/16915)

**Comment by lukaseder** [comment]
Similar problem in Firebird with the same query:

- https://github.com/jOOQ/jOOQ/issues/16922

**Comment by lukaseder** [comment]
Numerous similar issues have been fixed over the past week, including:

- https://github.com/jOOQ/jOOQ/issues/7467
- https://github.com/jOOQ/jOOQ/issues/3791
- https://github.com/jOOQ/jOOQ/issues/13533
- https://github.com/jOOQ/jOOQ/issues/14965
- https://github.com/jOOQ/jOOQ/issues/15189
- https://github.com/jOOQ/jOOQ/issues/16912
- https://github.com/jOOQ/jOOQ/issues/16928
- https://github.com/jOOQ/jOOQ/issues/16938
- https://github.com/jOOQ/jOOQ/issues/16946
