### ISSUE TITLE
Add an example implementation for IntegerToYearConverter in the manual

### ISSUE THREAD

**Issue by mihai-tatar** [jOOQ/jOOQ#16926]
### The documentation URL

https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-converter/

### Feedback

It would help if the referenced `com.example.IntegerToYearConverter ` would also be included as a snippet, so that it's more clear how the `<genericConverter>true</genericConverter>` part influences its implementation.

**Comment by lukaseder** [comment]
Sure, why not. Though, `<genericConverter>` can usually be ignored.

**Comment by lukaseder** [comment]
I'll add an example.

I've also created a separate issue to explain the (mostly unneeded) flag in a separate section:

- https://github.com/jOOQ/jOOQ/issues/16927
