### ISSUE TITLE
Using aliases inside of row expression on Postgres results in invalid SQL

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#16932]
### Expected behavior

jOOQ on Postgres should work similar to on Oracle where aliases within row expressions work just fine.

### Actual behavior

The query causes a DataAccessException.

### Steps to reproduce the problem

jOOQ generates invalid SQL given the following query in [jOOQ-mcve](https://github.com/alf/jOOQ-mcve/blob/main/jOOQ-mcve-java-postgres/src/test/java/org/jooq/mcve/test/java/postgres/JavaTest.java#L86):

```java
        var result = ctx.select(
                row(TEST.ID.as("foo"), TEST.CD.as("bar")))
                .from(TEST)
                .fetch();
```

which leads to the following error message:

```
org.jooq.exception.DataAccessException: SQL [select row ("foo", "bar") as "nested" from "mcve"."test"]; ERROR: column "foo" does not exist
```

### jOOQ Version

3.19.10

### Database product and version

PostgreSQL 15

### Java Version

17

**Comment by alf** [comment]
We're just getting started using jOOQ with Postgres and stumbled upon this which is blocking our progress. Hopefully there is an easy fix?

**Comment by alf** [comment]
The same jOOQ query generates the following sql for Oracle:

```sql
select "MCVE"."TEST"."ID" "nested.foo",
"MCVE"."TEST"."CD" "nested.bar"
from "MCVE"."TEST"
```

**Comment by lukaseder** [comment]
@alf, does this help?
https://www.jooq.org/doc/latest/manual/sql-building/queryparts/declaration-vs-reference/

I can see why you were expecting things to work the same way in PostgreSQL as they worked in Oracle, though I'd rather say this syntax should not have worked in Oracle, in the first place.

**Comment by alf** [comment]
I just checked whether or not my intention actually works in Postgres and ... no, it doesn't. Ooops, my bad. That explains things. My mental model was off.

https://www.postgresql.org/docs/16/sql-expressions.html#SQL-SYNTAX-ROW-CONSTRUCTORS

**Comment by lukaseder** [comment]
If you want to have typed nested records in PostgreSQL, you need to `cast(row(ID, CD) as my_type)` and declare it up front. That's also how you do this in Oracle with `OBJECT` types, btw. Otherwise, it's possible (in principle, see https://github.com/jOOQ/jOOQ/issues/13937) to name nested records in jOOQ, but not in SQL.

**Comment by alf** [comment]
Thank you, to be honest we don’t really need this. We use `row(…).mapping(TestDto::new)` so the names don’t matter. We just added them for developer readability.

Moving forward we might do less mapping and just produce json directly. In this case we’ll replace `row` with `json_object` and there we can set names as needed.
