### ISSUE TITLE
Best way to unit test custom generator strategies

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#16961]
### Your question

I'm writing a generator strategy for our database and find that it is a bit cumbersome to write unit tests for these.

What I'm currently doing is to subclass `AbstractMetaDatabase` and use `org.jooq.DSLContext.meta(String... sources)` to implement `protected Meta getMeta0()`. This is almost perfect, except for the fact that `protected void loadUniqueKeys(DefaultRelations relations)` in `AbstractMetaDatabase`  hard codes the names of the primary keys. Thus I have to make sure that the primary keys in my DDL scripts match these names. That is: `PK_<table name>`.

Is there a better way to do this that I'm missing? Is this hard coding of key names a bug or a feature? :)

### jOOQ Version

3.19.10

### Database product and version

PostgreSQL 15

**Comment by lukaseder** [comment]
That's a good question, probably worth a blog post. A few of jOOQ's features have been implemented precisely to test the code generation logic, in our case that in `GenerationTool`, but it's no different from when you want to test the logic in your generator strategy. The idea is that unit testing doesn't work well for such thing, but "integration testing" (i.e. testing the output of the code generation run, using the compiler) works very easily.

An example maven plugin execution from our code generation tests looks like this:

```xml
<execution>
    <id>generate-enumtypeswithgeneratorstrategy</id>
    <phase>generate-test-sources</phase>
    <goals>
        <goal>generate</goal>
    </goals>
    <configuration>
        <generator>
            <database>
                <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
                <properties>
                    <property>
                        <key>scripts</key>
                        <value>${basedir}/src/main/resources/enumtypeswithgeneratorstrategy.sql</value>
                    </property>
                </properties>
            </database>
            <strategy>
                <name>org.jooq.codegen.test.EnumTypesGeneratorStrategy</name>
                <java><![CDATA[package org.jooq.codegen.test;

import org.jooq.codegen.DefaultGeneratorStrategy;
import org.jooq.meta.Definition;

/**
 * See https://github.com/jOOQ/jOOQ/issues/9903
 */
public class EnumTypesGeneratorStrategy extends DefaultGeneratorStrategy {

    @Override
    public String getJavaClassName(Definition definition, Mode mode) {
        return mode == Mode.ENUM
            ? definition.getOutputName().replaceAll("_", "")
            : super.getJavaClassName(definition, mode);
    }
}
]]></java>
            </strategy>
            <target>
                <packageName>org.jooq.codegen.test.enumtypeswithgeneratorstrategy.db</packageName>
            </target>
        </generator>
    </configuration>
</execution>
```

There's also a `<pluginManagement>` managed default configuration for the stuff shared among tests. Note that you don't have to embed the strategy code in the test execution, you can also place it elsewhere, of course. On the other hand, the `DDLDatabase` can have inline SQL scripts, which might simplify testing for individual cases.

You could then run 10s of these executions, for each test case.

> This is almost perfect, except for the fact that `protected void loadUniqueKeys(DefaultRelations relations)` in `AbstractMetaDatabase` hard codes the names of the primary keys. Thus I have to make sure that the primary keys in my DDL scripts match these names. That is: `PK_<table name>`.
> 
> Is there a better way to do this that I'm missing? Is this hard coding of key names a bug or a feature? :)

It's a default implementation. Probably not the best one. I don't recall why it was done this way, though I don't want to change it unless there's a more obvious issue with it...

I hope this helps.
