### ISSUE TITLE
Disable timestamp precision in codegenerator

### ISSUE THREAD

**Issue by cmdjulian** [jOOQ/jOOQ#16972]
### Your question

When using the JooQ code generator it always generates the following code: 

```java
public static final Parameter<OffsetDateTime> START = Internal.createParameter("start", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false, false);
```

Is there a flag or similar within the JooQ generator to get rid of the precision? This results in some SQL errors for me :(
I need the generator to produce something like the following:

```java
public static final Parameter<OffsetDateTime> START = Internal.createParameter("start", SQLDataType.TIMESTAMPWITHTIMEZONE, false, false);
```

### jOOQ Version

org.springframework.boot:spring-boot-starter-jooq

### Database product and version

postgresql 15.7

### Java Version

openjdk 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.3

**Comment by lukaseder** [comment]
You can use data type rewriting to map the type to `TIMESTAMP WITH TIME ZONE`, without precision.

Curious, why would you need that? What are those "some SQL errors"?

**Comment by lukaseder** [comment]
Here's the documentation:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-rewrite/

**Comment by cmdjulian** [comment]
Thanks Lukas!

We are using TimescaleDB to manage our time-series data and use jooq to dynamically build aggregation queries etc. 
 
The Tablefield of the time column in our timescaledb hypertables is generated with a given precision like this:

```
createField(DSL.name("time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, ""); 
```

So when using the time_bucket_gapfill() https://docs.timescale.com/api/latest/hyperfunctions/gapfilling/time_bucket_gapfill/ function, the sql will look like this:

```
"time_bucket_gapfill"(bucket_width" := cast('0 years 0 mons 0 days 1 hours 0 mins 0.0 secs' AS INTERVAL),
ts" := "public"."float_aggregate_hourly"."time"::TIMESTAMP(6) WITH TIME ZONE)
```

Notice the cast to timestamp (6). This causes an issue because timescaledb raises the following error:
`“ERROR: invalid time_bucket_gapfill argument: ts needs to refer to a single column if no start or finish is supplied Hint: Specify start and finish as arguments or in the WHERE clause.”` Even though a start and end have been supplied in the where clause. When removing the (6) it works fine.
