### ISSUE TITLE
Enable isUnnamed flag in code generator

### ISSUE THREAD

**Issue by Timsgmlr** [jOOQ/jOOQ#16974]
### Your question

Hi jOOQ Team, 

We are using TimescaleDB in conjunction with jOOQ and the jOOQ code generator in our project. We have encountered an issue with TimescaleDB functions that do not support named parameters, specifically the time_weight() function ([documentation link](https://docs.timescale.com/api/latest/hyperfunctions/time-weighted-calculations/time_weight#time_weight)).

The generated code to use this function in jOOQ looks like this:
``` java
public static final Parameter<String> METHOD = Internal.createParameter("method", SQLDataType.CLOB, false, false);
public static final Parameter<OffsetDateTime> TS = Internal.createParameter("ts", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false, false);
public static final Parameter<Double> VALUE = Internal.createParameter("value", SQLDataType.DOUBLE, false, false);
```

In this code, the second false in each row represents the isUnnamed flag. When we manually set this flag to true, the function works correctly.

Is it possible to configure the jOOQ code generator to automatically set the isUnnamed flag to true for specific functions or parameters? If so, could you provide guidance on how to achieve this?

Thank you for your assistance!

### jOOQ Version

org.springframework.boot:spring-boot-starter-jooq

### Database product and version

postgresql 15.7

### Java Version

openjdk 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.3

**Comment by lukaseder** [comment]
Thanks for your message. There's no API to influence this flag. You can look into jOOQ-meta internals to see how it is defined, and possibly patch jOOQ on your end.

Once we support Timescale, I'm sure we can make this work out of the box:

- https://github.com/jOOQ/jOOQ/issues/9594
