### ISSUE TITLE
Exception when doing Meta.ddl() export with tables that have USE or GO or similar field or table aliases

### ISSUE THREAD

**Issue by bamboomoon** [jOOQ/jOOQ#16979]
### Steps to reproduce the problem

1. Create a table in PostgreSQL:
```sql
create table if not exists temp."user"
(
    name varchar(1024),
    id   bigint default nextval('temp.use_id_seq'::regclass) not null
        constraint use_pkey
            primary key
);
```

2. Create a view using 'USE' as an alias:
```sql
create view "temp"."test" as select "use"."id" from "temp"."user" as "use";
```

3. Use the following Java code to export the view DDL:
```java 
   Connection conn = DriverManager.getConnection("jdbc:postgresql://127.0.0.1:5432/dev", "postgres", "postgres");
            Configuration configuration = new DefaultConfiguration().set(conn).set(SQLDialect.POSTGRES);
            Meta currentMeta = DSL.using(configuration).meta();

            List<String> queries = Arrays.stream(currentMeta
                            .filterSchemas(v -> v.getName().equalsIgnoreCase("temp"))
                            .ddl()
                            .queries())
                    .map(Object::toString).toList();
            System.out.println(queries);
```

4. **The exported DDL is incorrect:**
```sql
 create view "temp"."test"("id")
as
create view "test" as  SELECT use.id
   FROM temp."user" use
```
5. An error is logged:
```java 
2024-07-16 14:15:28.012  INFO 10061 --- [           main] org.jooq.impl.DDL                        : Cannot parse view source: create view "test" as  SELECT use.id
   FROM temp."user" use;

org.jooq.impl.ParserException: Identifier expected: [2:24] ...w "test" as  SELECT use.id
   FROM temp."user" use[*];
	at org.jooq.impl.DefaultParseContext.expected(ParserImpl.java:14686)
	at org.jooq.impl.DefaultParseContext.parseName(ParserImpl.java:12341)
	at org.jooq.impl.DefaultParseContext.parseCatalogName(ParserImpl.java:12217)
	at org.jooq.impl.DefaultParseContext.parseUse(ParserImpl.java:2676)
	at org.jooq.impl.DefaultParseContext.parseQuery(ParserImpl.java:1242)
	at org.jooq.impl.DefaultParseContext.lambda$parse$0(ParserImpl.java:902)
	at org.jooq.impl.DefaultParseContext.wrap(ParserImpl.java:14913)
	at org.jooq.impl.DefaultParseContext.parse(ParserImpl.java:890)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:768)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:763)
	at org.jooq.impl.DDL.applyAs(DDL.java:175)
	at org.jooq.impl.DDL.createTableOrView(DDL.java:122)
	at org.jooq.impl.DDL.queries(DDL.java:403)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:549)
	at org.jooq.impl.AbstractMeta.ddl(AbstractMeta.java:542)
```

Working Example (Without 'use' as alias):
When creating a view without using 'use' as an alias, the export works correctly:
1. View creation SQL:
```sql
create view "temp"."test" as select "user"."id" from "temp"."user";
```

2. Correctly exported view DDL:
```sql
create view "temp"."test"("id")
as
select "user".id
from temp."user";

```

### jOOQ Version

JOOQ 3.18.5

### Database product and version

PostgreSQL 15.3 (Debian 15.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit

### Java Version

openjdk 17.0.2 2022-01-18 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.4

**Comment by lukaseder** [comment]
Thanks for your report. jOOQ's parser seems to expect T-SQL multi statement syntax here, where T-SQL allows for consecutive statements to be issued without semi colon in between them. This probably shouldn't apply when parsing PostgreSQL syntax.

I'll look into this soon.

**Comment by lukaseder** [comment]
Yes, indeed. Other keywords like `GO` are also forbidden as aliases, when parsing multiple statements. Others include:

- `ALTER`
- `BEGIN`
- `COMMENT`
- `CREATE`
- `DECLARE`
- `DELETE`
- `DROP`
- `END`
- `GO`
- `GRANT`
- `INSERT`
- `MERGE`
- `RENAME`
- `REVOKE`
- `SELECT`
- `SET`
- `TRUNCATE`
- `UPDATE`
- `USE`
- `VALUES`
- `WITH`

The best way forward here is probably to add a new `Settings.parserRequireDelimiter` that governs this parser behaviour:

- `true`: A delimiter is always required between statements
- `false`: A delimiter isn't required between statements (the default, for backwards compatibility)

The delimiter can already be set from within a script by using the MySQL style `DELIMITER ...` command, but we still need this additional flag to make sure users can require the delimiter, in case of which we don't need to check for these "forbidden statement keywords".

I don't think I can implement this as a simple bug fix, given that new configuration API and documentation is required. The only workaround I can see is to use a different alias in the view, e.g. just `u`.

**Comment by lukaseder** [comment]
Hmm, perhaps it's possible to fix your specific case of using `Meta.ddl().queries()` without new configuration API, given that we're in control of what is being parsed there.

I've moved the new API to a separate feature request:

- https://github.com/jOOQ/jOOQ/issues/17013

**Comment by lukaseder** [comment]
The only reason why we're parsing possibly multiple queries is to be able to parse an optional delimiter at the end of the query:

- #10594

I guess this can be achieved differently

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.11 (https://github.com/jOOQ/jOOQ/issues/17014)
- 3.18.18 (https://github.com/jOOQ/jOOQ/issues/17015)
- 3.17.27 (https://github.com/jOOQ/jOOQ/issues/17016)
