### ISSUE TITLE
Count for query

### ISSUE THREAD

**Issue by o-shevchenko** [jOOQ/jOOQ#16981]
### Your question

Is it possible to use JOOQ API to get the total row count for a query?
```Kotlin
val code = "SELECT * FROM my_yable WHERE field1="asd""
context.resultQuery(code)
```
I want to get count first but don't want to build something like that:
```
SELECT COUNT(*)
FROM (
    $code
) AS subquery;
```

I tried to use:
```Kotlin
context.selectCount().from(originalQuery)
```
and 
```Kotlin
context.fetchCount(originalQuery)
```
it doesn't work with query but with only tables.

Is it possible to get count from query or have an alias for the query:
```Kotlin
val countQuery = context.selectCount().from(originalQuery.asTable("subquery"))
```

### jOOQ Version

3.19.10

### Database product and version

SAP HANA

### Java Version

17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.sap.cloud.db.jdbc:ngdbc:2.21.11

**Comment by lukaseder** [comment]
Why not just do this?

```java
context.selectCount().from(DSL.table("({0})", originalQuery).as("t"));
```

**Comment by o-shevchenko** [comment]
Thanks, @lukaseder, for the example.
It's not intuitive that we can use `DSL.table("({0})", originalQuery)`

**Comment by lukaseder** [comment]
The feature is called plain SQL templating: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/
