### ISSUE TITLE
jOOQ-codegen-gradle plugin doesn't work with Gradle's configuration cache feature

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#16997]
When enabling the Gradle configuration cache, e.g. in `gradle.properties`:

```
org.gradle.configuration-cache=true
```

Then the code generation integration tests fail with this error:

```
$ ./gradlew jooqCodegen
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Duser.language=en
Calculating task graph as no configuration cache is available for tasks: jooqCodegen

FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache problems found in this build.

2 problems were found storing the configuration cache.
- Task `:jOOQ-test-codegen-gradle-kotlin-only-configuration:jooqCodegen` of type `org.jooq.codegen.gradle.CodegenTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/8.2/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:jOOQ-test-codegen-gradle-kotlin-only-configuration:jooqCodegen` of type `org.jooq.codegen.gradle.CodegenTask`: invocation of 'Task.project' at execution time is unsupported.
  See https://docs.gradle.org/8.2/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution

See the complete report at file:///C:/Users/lukas/jOOQ/3.20/workspace/jOOQ-pro/jOOQ-test-codegen/jOOQ-test-codegen-gradle/build/reports/configuration-cache/6t7gw6hw3q8emolg7ula0skz0/a1j6q7iuvafynxhe6zr173zbs/configuration-cache-report.html
> Invocation of 'Task.project' by task ':jOOQ-test-codegen-gradle-kotlin-only-configuration:jooqCodegen' at execution time is unsupported.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 3s
1 actionable task: 1 executed
Configuration cache entry discarded with 2 problems.
```

**Comment by lukaseder** [comment]
The documentation page shows that we mustn't store references to `Project` or other *"Gradle model types"* in our `CodegenTask`, as these cannot be serialised:

- https://docs.gradle.org/8.2/userguide/configuration_cache.html#config_cache:requirements:disallowed_types

A quick google for the error message shows that everyone and their dog's gradle plugin has run into this, historically, as stuff that used to work no longer did when gradle introduced this configuration cache feature.

I can't say yet how easy it is to fix this particular issue. For now, the workaround is to disable the error message, or configuration caching for our plugin, using `--no-configuration-cache`

**Comment by lukaseder** [comment]
While some references to `Project` can be avoided by refactoring things to look up `Project` related properties (e.g. the `NamedConfiguration` can store the `Project.getLayout().getProjectDirectory()` in the constructor, instead of looking it up later), the logic in `CodegenTask.registerSourceSet()` is harder to refactor.

**Comment by lukaseder** [comment]
We're far from alone with this:

- https://github.com/gradle/gradle/issues/13454
- https://github.com/gradle/gradle/issues/13490

**Comment by lukaseder** [comment]
After a lot of additional trial and error, it appears that the main problem is this code here:
https://github.com/jOOQ/jOOQ/blob/3cade0204f6fc19601f75cee844b4d8495d617ec/jOOQ-codegen-gradle/src/main/java/org/jooq/codegen/gradle/CodegenTask.java#L94

Which reads:

```java
        // [#16318] When the task is up-to-date, we still have to register our source set contributions, which
        //          apparently aren't being cached by gradle's build cache.
        getOutputs().upToDateWhen(task -> registerSourceSet(task) && upToDate(task));
```

This registering of source sets while trying to check if the task is up to date happens "too late," and thus shouldn't be done.

When removing it, I cannot seem to trigger a regression. I vaguely recall this having been about some manual changes to the task inputs, but the discussion around this issue was long:

- https://github.com/jOOQ/jOOQ/issues/16318

And the conclusion was that task inputs have to be declared explicitly by users, so perhaps, this isn't necessary after all...

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.11 (https://github.com/jOOQ/jOOQ/issues/17044)

Will request user feedback on snapshot builds first, though, prior to releasing

**Comment by NikolayMetchev** [comment]
You can do what the third party plugin does and have a allInputsDeclared property to control this behaviour

**Comment by lukaseder** [comment]
There's a `caching` property since [#16318](https://github.com/jOOQ/jOOQ/issues/16318#issuecomment-2160605973)
