### ISSUE TITLE
JOOQ Batch using MemSQL instead of MySQL for Timestamp in Batch Statement

### ISSUE THREAD

**Issue by noahisch** [jOOQ/jOOQ#16995]
### Expected behavior

I was expecting MySQL batch jooq to generate something like
`modified_at = '2024-07-30 04:04:39.613192'`

### Actual behavior

`modified_at` = {ts '2024-07-30 03:39:22.701232'}`

### Steps to reproduce the problem

I am using JOOQ codegen with the following config
```
jooq {
    configuration {
        generator {
            generate {
                javaTimeTypes = true
            }
            database {
                target {
                    packageName = "com.jooq"
                }
                name = "org.jooq.meta.extensions.ddl.DDLDatabase"
                properties {
                    property {
                        key = "scripts"
                        value = "src/main/resources/database.sql"
                    }
                    property {
                        key = "sort"
                        value = "semantic"
                    }
                    property {
                        key = "unqualifiedSchema"
                        value = "none"
                    }
                    property {
                        key = "defaultNameCase"
                        value = "as_is"
                    }
                }
            }
        }
    }
}
```

An example database would be 
```
CREATE TABLE `items`
(
    `id`                      bigint      NOT NULL,
    `modified_at`                  datetime(6) NOT NULL,
    PRIMARY KEY (`id`)
);
```
If I build a batch statement like 
```
DSL.using(dataSource, SQLDialect.MYSQL);
context.batch(
context
        .update(ITEMS)
        .set(ITEMS.MODIFIED_AT,LocalDateTime.now(ZoneOffset.UTC))
        .where(
            ITEMS.ID.eq(100L));
...).execute();
```

it generates the statement 
`modified_at = {ts '2024-07-30 03:39:22.701232'}`, which does not work with mysql

### jOOQ Version

3.19.10

### Database product and version

MySQL-8.0.20

### Java Version

17

**Comment by lukaseder** [comment]
Thanks for your report. We'll switch to using standard SQL datetime literals in jOOQ 3.20 (for other reasons), see:

- https://github.com/jOOQ/jOOQ/issues/16498

> `modified_at = {ts '2024-07-30 03:39:22.701232'}`, which does not work with mysql

I'm curious about why you'd think so. The ODBC escape syntax is certainly supported in MySQL, see: https://dev.mysql.com/doc/refman/8.0/en/date-and-time-literals.html

What exactly didn't work for you? Why did you think this is related to MemSQL?

**Comment by lukaseder** [comment]
> I thought that this was using MemSQL due to the documentation on the timestamp function: https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/datetime-functions/timestamp-function/
> 
> MemSQL is the only one that renders using `{ts ...}`, I was not aware that this was a supported syntax in MySQL.

Ah, I see, thanks for the clarification. That makes sense. #16498 didn't change the behaviour for MemSQL (or MySQL 5.7 and earlier), and the website is built using jOOQ 3.20.0-SNAPSHOT already, which is why you're seeing the difference.

> I'm using Vitess, which is running MySQL 8, and it does not allow the ODBC syntax. It throws a syntax error on the first "{".

I see. Well, we don't support Vitess, so I can't really say what should work there and what shouldn't. They claim MySQL compatibility, and this ODBC syntax works on MySQL (and has always been documented) but does  not work on Vitess, so I'd say it's a bug in Vitess? I'd try reporting it there.
