### ISSUE TITLE
jOOQ generate an extract for DSL.week instead of a datepart

### ISSUE THREAD

**Issue by loicmathieu** [jOOQ/jOOQ#16998]
### Expected behavior

On SQLServer, `DSL.week(timestamp)` should generate `datepart(ww, [timestamp])`

### Actual behavior

When using `DSL.week()` on SQLServer, it generates `extract(week from [timestamp])` but `extract` is not supported on SQLServer.

### Steps to reproduce the problem

Use `DSL.week(timestamp)` on any date type field in SQLServer

### jOOQ Version

Professional Edition 3.19

### Database product and version

SQLServer 2022

### Java Version

Java 21

**Comment by loicmathieu** [comment]
@lukaseder I saw https://github.com/jOOQ/jOOQ/issues/9512 and it's not exactly the same as in https://github.com/jOOQ/jOOQ/issues/9512 `extract()` is used in the code, here only `DSL.week(timestamp)` is used in the code which translate to an SQL `extract()` which should not be the case in SQLServer.

**Comment by lukaseder** [comment]
`DSL.week(x)` is just short for `DSL.extract(x, DatePart.WEEK)`:
https://github.com/jOOQ/jOOQ/blob/c7d2f2ec92eabb8a0b6c19e95cb56c127af6186b/jOOQ/src/main/java/org/jooq/impl/DSL.java#L28853
