### ISSUE TITLE
Add support for the SQL standard UNIQUE predicate

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1699]
The SQL:1999 standard specifies:

```
8.10 <unique predicate>

Function
  Specify a test for the absence of duplicate rows.

Format
  <unique predicate> ::=
     UNIQUE <table subquery>
```

This might be a useful addition that could be simulated non-trivially by comparing

``` sql
(SELECT COUNT(*) FROM [table subquery]) = 
  (SELECT COUNT(*) FROM ([table subquery] UNION [empty row]))
```

Or better, as suggested by @knutwannheden :

```sql
SELECT 1 WHERE UNIQUE (SELECT 1 a, 2 b UNION ALL SELECT 1 a, 2 b);

SELECT 1
WHERE NOT EXISTS (
  SELECT NULL
  FROM (SELECT 1 a, 2 b UNION ALL SELECT 1 a, 2 b) t
  GROUP BY a, b
  HAVING count(*) > 1
  OR NOT (a, b) IS NOT NULL -- See spec extract, below
);
```

And 

```sql
SELECT 1 WHERE NOT UNIQUE (SELECT 1 a, 2 b UNION ALL SELECT 1 a, 2 b);

SELECT 1
WHERE EXISTS (
  SELECT NULL
  FROM (SELECT 1 a, 2 b UNION ALL SELECT 1 a, 2 b) t
  GROUP BY a, b
  HAVING count(*) > 1
  OR NOT (a, b) IS NOT NULL -- See spec extract, below
);
```

**Comment by lukaseder** [comment]
@knutwannheden I've added a `OR NOT (a, b) IS NOT NULL` predicate to your suggestion. The way I interpret the standard (see https://github.com/jOOQ/jOOQ/issues/1699#issuecomment-51905912), this seems necessary. What do you think?

**Comment by lukaseder** [comment]
Actually, there are two ways to interpret this:

### 1. Unique predicate is always false in the presence of rows containing nulls:

```sql
SELECT 1 WHERE UNIQUE (SELECT 1 a, 2 b UNION ALL SELECT 1 a, 2 b);

SELECT 1
WHERE NOT EXISTS (
  SELECT NULL
  FROM (SELECT 1 a, 2 b UNION ALL SELECT 1 a, 2 b) t
  GROUP BY a, b
  HAVING count(*) > 1
  OR NOT (a, b) IS NOT NULL
);
```

### 2. Unique predicate does not consider rows containing nulls:


```sql
SELECT 1 WHERE UNIQUE (SELECT 1 a, 2 b UNION ALL SELECT 1 a, 2 b);

SELECT 1
WHERE NOT EXISTS (
  SELECT NULL
  FROM (SELECT 1 a, 2 b UNION ALL SELECT 1 a, 2 b) t
  WHERE (a, b) IS NOT NULL
  GROUP BY a, b
  HAVING count(*) > 1
);
```

Thinking about it more thoroughly, I tend to interpret the standard as in 2), not 1)...

**Comment by knutwannheden** [comment]
I think you are right. How can you keep all these NOTs straight in your head this early in the morning? :-)

**Comment by lukaseder** [comment]
> How can you keep all these NOTs straight in your head this early in the morning?

I tampered with them long enough until they produced the expected result on https://www.db-fiddle.com ;-)

**Comment by lukaseder** [comment]
Similar task: #1700

**Comment by knutwannheden** [comment]
Should `NOT UNIQUE (SELECT NULL UNION ALL SELECT NULL)` evaluate to `true`? And how about `NOT UNIQUE (SELECT 1, NULL UNION ALL SELECT 1, NULL)`?

Doesn't the `WHERE (a, b) IS NOT NULL` predicate lead to the rows getting excluded and thus the result evaluating to `false`?

**Comment by knutwannheden** [comment]
Possibly using `NOT (<ROW> IS NULL)` makes more sense here than using `<ROW> IS NOT NULL`. See https://blog.jooq.org/tag/row-value-expressions/. This at least works better for examples like `NOT UNIQUE (SELECT 1, NULL UNION ALL SELECT 1, NULL)`.

But I am still unsure about how `NOT UNIQUE` should behave when there are multiple rows where *all* fields are `NULL`.

**Comment by lukaseder** [comment]
> Should NOT UNIQUE (SELECT NULL UNION ALL SELECT NULL) evaluate to true

No it should not. Because *"If there are no two rows in T such that the value of each column in one row is non-null and [...], then the result of the `<unique predicate>` is true"*

In your example, there are no such two rows, so the subquery is "unique", and your negation makes it false.

> And how about NOT UNIQUE (SELECT 1, NULL UNION ALL SELECT 1, NULL)

Same. *"such that the value of each column in one row is non-null"*

> Doesn't the WHERE (a, b) IS NOT NULL predicate lead to the rows getting excluded and thus the result evaluating to false?

Yes, and that's desired because in my example 2) from https://github.com/jOOQ/jOOQ/issues/1699#issuecomment-482453617, I used `NOT EXISTS`:

```sql
SELECT 1 WHERE UNIQUE (SELECT 1 a, 2 b UNION ALL SELECT 1 a, 2 b);

SELECT 1
WHERE NOT EXISTS (
  SELECT NULL
  FROM (SELECT 1 a, 2 b UNION ALL SELECT 1 a, 2 b) t
  WHERE (a, b) IS NOT NULL
  GROUP BY a, b
  HAVING count(*) > 1
);
```

So, if any of a or b is null, then the `WHERE` clause is false, and the row is excluded from the uniqueness check. So that row can never contribute to any given `count(*) > 1`. With your examples of only two rows that are "unique" (because they contain nulls), the `NOT EXISTS` subquery yields `true`, and that's what we want.

> Possibly using NOT (<ROW> IS NULL) makes more sense here than using <ROW> IS NOT NULL

I don't think so. Here's the truth table in SQL:2016:

![image](https://user-images.githubusercontent.com/734593/56597628-242e8e80-65f3-11e9-9511-bc7af5171087.png)

> But I am still unsure about how NOT UNIQUE should behave when there are multiple rows where all fields are NULL.

The way I read it is that we don't care if the're *all* null. We care if there is *any* field that is null. I.e. `(a, b) IS NOT NULL`

**Comment by knutwannheden** [comment]
Yes, I should have read the spec more carefully.

Since the SQL specification isn't freely publicly available and none of the supported DBs natively support `UNIQUE`, we should maybe add more Javadoc explaining what this predicate is. Or at least add a dedicated section to the reference manual as there e.g. is for `IN` and `EXISTS`. I will create a separate issue for this documentation task.

**Comment by lukaseder** [comment]
> Yes, I should have read the spec more carefully.

No worries. It is a very difficult to read document, and I often do not get it right the first time without discussing it with someone :) (e.g. the H2 maintainers).

> Since the SQL specification isn't freely publicly available

The last freely available standard already specified the predicate:
https://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt

> Or at least add a dedicated section to the reference manual as there e.g. is for IN and EXISTS

We could discuss making the Javadoc more elaborate, but that's a lot of work. I wouldn't add too much Javadoc only to `UNIQUE`, just maybe a short paragraph and a simple example.

The manual definitely needs a section.

**Comment by lukaseder** [comment]
Interestingly, support for the `UNIQUE` predicate is being worked on for PostgreSQL: https://twitter.com/pg_xocolatl/status/1123481865460027392

**Comment by lukaseder** [comment]
The tests for this feature fail in Vertica because its `<rve> IS NOT NULL` implementation seems to be implemented wrong. See #8709. I'll fix this for Vertica.
