### ISSUE TITLE
Row[N].in(Row[N]...), Row[N].between(...), and Row[N].is[Not]DistinctFrom(...) should apply data type bindings if necessary

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#17018]
### Expected behavior

Should just work because that's what we're used to.

### Actual behavior

```
DataAccess SQL [select "mcve"."test"."id" from "mcve"."test" where ("mcve"."test"."id") in ((?))]; ERROR: operator does not exist: uuid = character varying
```

### Steps to reproduce the problem

https://github.com/alf/jOOQ-mcve/tree/d84be552d237a93042dc54cb776b929c7377a7c4

In short, the following causes errors when the ID column has been forcedTyped to String:

```sql
ctx.select(TEST.ID)
   .from(TEST)
   .where(row(TEST.ID).in(row(UUID.randomUUID().toString())))
```

Here's the force type config:

```xml
<forcedType>
    <userType>java.lang.String</userType>
    <includeExpression>TEST.ID</includeExpression>
    <lambdaConverter>
        <from>UUID::toString</from>
        <to>UUID::fromString</to>
    </lambdaConverter>
</forcedType>
```

### jOOQ Version

3.19.10

### Database product and version

PostgreSQL 16

### Java Version

OpenJDK 17

**Comment by lukaseder** [comment]
Thanks for your report. Indeed, this seems to be a similar case as:

- https://github.com/jOOQ/jOOQ/issues/8517

But for the `IN` predicate. The workaround when jOOQ cannot correctly infer types is as always, to be explicit about types. I.e.:

```java
ctx.select(TEST.ID)
   .from(TEST)
   .where(row(TEST.ID).in(row(val(UUID.randomUUID().toString(), TEST.ID))))
//                            ^^^ explicit bind value           ^^^^^^^ passing the desired data type
```

**Comment by lukaseder** [comment]
The `BETWEEN` and `DISTINCT` predicates are also affected

**Comment by lukaseder** [comment]
In the `DISTINCT` case, the problem may be masked by an emulation that uses `RowCondition` as an implementation, which already profits from https://github.com/jOOQ/jOOQ/issues/8517

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.11 (https://github.com/jOOQ/jOOQ/issues/17022)
- 3.18.18 (https://github.com/jOOQ/jOOQ/issues/17023)
- 3.17.27 (https://github.com/jOOQ/jOOQ/issues/17024)

Please note this does not affect using subqueries with `IN`, which is a different topic / challenge.
