### ISSUE TITLE
Add BigQuery support for JSON_OBJECTAGG

### ISSUE THREAD

**Issue by mathieusanchez** [jOOQ/jOOQ#17017]
### Use case

I need to generate a JSON object from a query on BigQuery.

### Possible solution

BigQuery support on the `json_object` method, a key array and a value array for creating json objects.
https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions#json_object

### jOOQ Version

3.20

### Database product and version

BigQuery latest

### Java Version

openJDK 17.0.8.1 2023-08-24

**Comment by lukaseder** [comment]
Thanks for your suggestion.

`JSON_OBJECT()` support has already been implemented for jOOQ 3.20:

- #16754

You can access 3.20.0-SNAPSHOT builds from here:

- https://www.jooq.org/download/versions

But I see that the overload taking key and value arrays does indeed correspond to standard SQL `JSON_OBJECTAGG`. I've overlooked that when implementing #16754. It's probably possible to emulate most usages of the standard SQL syntax, then. Will look into this right away.

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.20.0. The feature should be available in tomorrow's 3.20.0-SNAPSHOT build.

**Comment by lukaseder** [comment]
There's a feature combination that I currently don't know how to emulate yet: When combining `NULL ON NULL` and `FILTER` clauses, e.g.:

```java
jsonObjectAgg(x, y).nullOnNull().filterWhere(c)
```

The `FILTER` emulation depends on the `NULL` flag to be `ABSENT ON NULL`, currently. I've recently fixed this for Oracle, which has a useful `JSON_TRANSFORM` function that can be used for this emulation:

- https://github.com/jOOQ/jOOQ/issues/12073
- https://github.com/jOOQ/jOOQ/issues/16751

But I don't see how to do this simply with BigQuery (Other than doing some weird subquery unnesting tricks, which have their own problems)
