### ISSUE TITLE
Invalid SQL generated for INSERT .. ON DUPLICATE KEY IGNORE or ON DUPLICATE KEY UPDATE emulations using MERGE

### ISSUE THREAD

**Issue by shaunbrockhoff-wk** [jOOQ/jOOQ#17092]
### Expected behavior

Using onDuplicateKeyIgnore() on an insert against a table with an alias should generate valid SQL. In the linked MCVE, valid SQL is generated when no alias is used:
```
merge into "MCVE"."TEST" using (select cast(? as int) "CD") "t" on "MCVE"."TEST"."ID" = cast(? as int) when not matched then insert ("CD") values ("t"."CD")
```

### Actual behavior

When an alias is used, this query is generated:
```
merge into "MCVE"."TEST" "a" using (select cast(? as int) "CD") "t" on "MCVE"."TEST"."ID" = cast(? as int) when not matched then insert ("CD") values ("t"."CD")
```
and this exception is thrown:
`org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "MCVE.TEST.ID" not found`

### Steps to reproduce the problem

[MCVE branch](https://github.com/jOOQ/jOOQ-mcve/compare/main...shaunbrockhoff-wk:jOOQ-mcve:onDuplicateKeyIgnore-alias)

### jOOQ Version

3.19.10

### Database product and version

H2 2.3.230, in MySQL mode

### Java Version

openjdk 21.0.2

**Comment by lukaseder** [comment]
Thanks for your message.

You'll find numerous issues on the issue tracker or discussions on the user group about this topic, e.g.:

- https://github.com/jOOQ/jOOQ/issues/13892
- https://github.com/jOOQ/jOOQ/issues/13240
- https://github.com/jOOQ/jOOQ/issues/2474

The solution is simple: Don't use H2 in MySQL mode with jOOQ.

**Comment by shaunbrockhoff-wk** [comment]
@lukaseder thanks for the quick response! I'll look into seeing if we can run without MySQL mode. However, this particular issue does appear to affect H2 even when it's not running in compatibility mode.

**Comment by lukaseder** [comment]
OK, I'll try reproducing the issue without compatibility mode

**Comment by lukaseder** [comment]
This isn't H2 specific, but happens with all dialects that emulate the feature with `MERGE` (and also for the `ON DUPLICATE KEY UPDATE` clause).

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17109)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17110)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17111)

**Comment by lukaseder** [comment]
Related bug:

- https://github.com/jOOQ/jOOQ/issues/17112

**Comment by lukaseder** [comment]
Related issue:

- https://github.com/jOOQ/jOOQ/issues/18324
