### ISSUE TITLE
KotlinGenerator contains incomplete list of Kotlin forbidden identifier characters

### ISSUE THREAD

**Issue by matsudamper** [jOOQ/jOOQ#17099]
### Expected behavior

```kotlin
enum class JTestType(@get:JvmName("literal") public val literal: String) : EnumType {
    settings_3aignore("settings:ignore"),
```

### Actual behavior

```kotlin
enum class JTestType(@get:JvmName("literal") public val literal: String) : EnumType {
    `settings:ignore`("settings:ignore"),
```

error
```
Name contains illegal characters: :
```

settings
```kotlin
val generator = Generator()
            .withName("org.jooq.codegen.KotlinGenerator")
            .withStrategy(
                org.jooq.meta.jaxb.Strategy()
                    .withName("org.jooq.codegen.example.JPrefixGeneratorStrategy")
            )
            .withGenerate(generate)
            .withDatabase(database)
            .withTarget(target)
```

### Steps to reproduce the problem

Include a colon in the enum

### jOOQ Version

3.19.11

### Database product and version

MySQL 8.0.36

### Java Version

Amazon coretto 21.0.1

### JDBC / R2DBC driver name and version (include name if unofficial driver)

mysql:mysql-connector-java:8.0.18

**Comment by matsudamper** [comment]
relation
https://github.com/jOOQ/jOOQ/issues/10837

**Comment by lukaseder** [comment]
Thanks for your report. I'll look into this right away.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17114)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17115)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17116)

**Comment by lukaseder** [comment]
Related bug:

- https://github.com/jOOQ/jOOQ/issues/17117
