### ISSUE TITLE
CASE expression on BOOLEAN type emulation in JSON constructor causes ORA-40590: invalid format on Oracle XE 18

### ISSUE THREAD

**Issue by andreahn** [jOOQ/jOOQ#17113]
### Expected behavior

Generated SQL should work

### Actual behavior

Generated SQL produces ORA-40590: invalid format

### Steps to reproduce the problem

Demonstrated [here](https://github.com/andreahn/jOOQ-mcve/commit/119128521541c4fa56dc8a456505019b73742613). I encountered this issue when writing correlated subqueries, so I have an example for a subquery which generates an SQL query with `json_array` as well as an example using `DSL.jsonArray()`.

It seems to be a similar problem to [this issue](https://github.com/jOOQ/jOOQ/issues/12072), but for `json_array` instead of `json_arrayagg`.

### jOOQ Version

3.19.11

### Database product and version

Oracle 18 XE

### Java Version

OpenJDK 17

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can confirm, this doesn't work:

```sql
select json_array(
  case when 1 < 2 then json_object(key 'a' value 1) end
)
from dual
```

Producing:

> ORA-40590: invalid format

And the same workaround works around the problem:

```sql
select json_array(
  case when 1 < 2 then json_object(key 'a' value 1) else null end
)
from dual
```

Producing:

> [{"a":1}]

**Comment by lukaseder** [comment]
The problem also appears with `JSON_OBJECT`:

```java
select json_object(
  key 'k'
  value case when 1 < 2 then json_object(key 'a' value 1) end
)
from dual
```

Or `JSON_OBJECTAGG`:

```sql
select json_objectagg(
  'k',
  case when 1 < 2 then json_object(key 'a' value 1) end
)
from dual
```

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.12 (https://github.com/jOOQ/jOOQ/issues/17121)
- 3.18.19 (https://github.com/jOOQ/jOOQ/issues/17122)
- 3.17.28 (https://github.com/jOOQ/jOOQ/issues/17123)

**Comment by lukaseder** [comment]
Hmm, I've just had a look at your MCVE. The issue you've linked (https://github.com/jOOQ/jOOQ/issues/12072) isn't the same as what you're showing, which seems to have to do with booleans.

Let me double check.

**Comment by lukaseder** [comment]
E.g. this hackery prevents the bug 😅

```java
try (PreparedStatement s = connection.prepareStatement(
    """
    select
      json_array(
        (select case
          case when 1 = 1 then ? end
          when 1 then 'true'
        end from dual)
        format json
      )
    from dual
    """
)) {
    s.setInt(1, 1);

    try (ResultSet rs = s.executeQuery()) {
        while (rs.next())
            System.out.println(rs.getString(1));
    }
}
```

Or this, possibly less problematic, as it doesn't generate a new subquery scope:

```java
try (PreparedStatement s = connection.prepareStatement(
    """
    select
      json_array(
        coalesce(null, case
          case when 1 = 1 then ? end
          when 1 then 'true'
        end)
        format json
      )
    from dual
    """
)) {
    s.setInt(1, 1);

    try (ResultSet rs = s.executeQuery()) {
        while (rs.next())
            System.out.println(rs.getString(1));
    }
}
```

And I've done it before to work around an ojdbc bug pre Oracle 23ai:

- #13156 
- #15835
- https://stackoverflow.com/q/71268781/521799

**Comment by lukaseder** [comment]
I can confirm, the `NVL(NULL, <CASE expr>)` hack fixes the issue in both the tests of your MCVE here: https://github.com/andreahn/jOOQ-mcve/commit/119128521541c4fa56dc8a456505019b73742613

**Comment by lukaseder** [comment]
Related bug:

- https://github.com/jOOQ/jOOQ/issues/17124
