### ISSUE TITLE
<unsignedTypes/> flag doesn't work outside of MySQLDatabase

### ISSUE THREAD

**Issue by northcoder-repo** [jOOQ/jOOQ#17135]
### Your question

**Summary:**

The `<unsignedTypes>false</unsignedTypes>` directive is apparently ignored when generating Java from a `information_schema.xml` file containing unsigned data types.

Am I doing something wrong? Is this the expected behavior?

---

**Set-Up**:

I generate my jOOQ classes in a two-step process:

**Step 1**: I generate `information_schema.xml` using the following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <!-- JDBC connection parameters -->
    <jdbc>
        <driver>com.mysql.cj.jdbc.Driver</driver>
        <url>jdbc:mysql://localhost:3306/sakila</url>
        <user>redacted</user>
        <password>redacted</password>
    </jdbc>
    <!-- Generator parameters -->
    <generator>
        <name>org.jooq.codegen.XMLGenerator</name>
        <database>
            <name>org.jooq.meta.mysql.MySQLDatabase</name>
            <includes>.*</includes>
            <excludes></excludes>
            <inputSchema>sakila</inputSchema>
        </database>
    </generator>
</configuration>
```

I see that the resulting XML uses unsigned integers, as expected - for example:

```xml
<table_name>actor_info</table_name>
<column_name>actor_id</column_name>
<data_type>intunsigned</data_type>
```

This reflects the [Sakila database](https://github.com/jOOQ/sakila/tree/main/sql-server-sakila-db) I am using.

**Step 2**: I generate my jOOQ classes using a different jOOQ XML config file which reads the above schema XML file as its input (I do not connect to the DB). 

I include the following [unsigned types directive](https://www.jooq.org/doc/3.19/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-unsigned-types/) in this second XML generator file:

```xml
<configuration>
  <generator>
    <database>
      <unsignedTypes>false</unsignedTypes>
    </database>
  </generator>
</configuration>
```
---

**The issue:**

I expect the above process to result in Java types such as `Integer` being used, instead of jOOQ types such as `org.jooq.types.UInteger`.

For example, I expect this in `ActorRecord.java`:

```java
public void setActorId(Integer value) {
    set(0, value);
}
```

However, I actually get code like this (`UInteger` instead of `Integer`):

```java
public void setActorId(UInteger value) {
    set(0, value);
}
```

The `<unsignedTypes>false</unsignedTypes>` directive in the above mentioned step 2 has apparently been ignored.

---

**Workaround:**

If I remove `<unsignedTypes>false</unsignedTypes>` from step 2, and add it to step 1, then I get a schema XML file which no longer contains unsigned data types - and then in step 2 I get the Java code I was originally expecting to get.

---

I don't know if this unexpected behavior is an issue with jOOQ, or an issue with my understanding of jOOQ. Ideally, I would want my XML schema generated in step 1 to accurately reflect the source database schema. The workaround is absolutely not a problem - but is it really needed (and if so, why)?

Any guidance is appreciated.

### jOOQ Version

jOOQ open source edition 3.19.10 

### Database product and version

MySQL 8.0.28

### Java Version

openjdk version "21.0.2" 2024-01-16 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.mysql:mysql-connector-j:8.0.33

**Comment by lukaseder** [comment]
Thanks for your report. This flag has been implemented purely as a feature of the `MySQLDatabase`. As such, all other types of `Database` (including `XMLDatabase`, `JPADatabase`, `DDLDatabase`) won't apply the flag. I'd say this is a bug.

**Comment by lukaseder** [comment]
The workaround would be to use data type rewriting in your second code generation run:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/codegen-database-forced-types-rewrite/

**Comment by guss77** [comment]
This change causes jOOQ on MySQL to generate `UNumber` Java types for unsigned types, even if `unsignedTypes` is set to `false`. I'll open a new issue about this.

**Comment by lukaseder** [comment]
Thanks for your message and investigations @guss77. I'll have a look at this early next week.

**Comment by lukaseder** [comment]
The workaround is to use data type rewriting. I do think that perhaps this flag is no longer necessary anyway? It was introduced a long time before we had forced types (including data type rewriting, converters, etc.). I'll move to deprecating the flag starting from jOOQ 3.20:

- https://github.com/jOOQ/jOOQ/issues/17535

The alternative is documented in that issue.
