### ISSUE TITLE
Invalid Java 8 publications in the jOOQ repository

### ISSUE THREAD

**Issue by muehmar** [jOOQ/jOOQ#17130]
### Actual behavior

We connected the https://repo.jooq.org/ Repository as Remote Repository in our Artifactory. We use in one project the Java 8 Pro Version of 3.15.4. Our code fails to compile when using the meta and codegen dependencies. These artifacts seem to contain actually the classes from the jooq artifact itself (like DSLContext) but do not contain the classes (or package) I would expect in these artifacts, thus the code does not compile.

This does no seem to be an issue only for the mentioned version, this seems to be the case for all Java 8 Pro artifacts up to version 3.18.7.

Curiously, if I download the version via download section of the homepage, the artifacts seem to be correct.

### Steps to reproduce the problem

Download the jar https://repo.jooq.org/repo/org/jooq/pro-java-8/jooq-codegen/3.15.4/jooq-codegen-3.15.4.jar an check the content, there is the class org.jooq.DSLContext but no package org.jooq.codegen.

### jOOQ Version

Professional 3.15.4

### Database product and version

MS SQL Server 2017

### Java Version

Java 8

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can confirm this. Other artifacts also seem to be affected. I'll look into this, soon. For the time being, please work with the ZIP file download and the manual install/deployment of artifacts.

**Comment by muehmar** [comment]
Thank you very much! The problem for our artifacts is solved now, after cleaning the cache in our artifactory, we get now the correct artifacts.

**Comment by lukaseder** [comment]
Thanks for the confirmation. The job finished last night at 22:30.

I wonder how this could have happened in the first place. I don't see how a regression could have occurred. Perhaps the original initialisation just never worked correctly for the older artifacts...
