### ISSUE TITLE
Programatic code generation produces no output

### ISSUE THREAD

**Issue by KrisReal** [jOOQ/jOOQ#17144]
### Expected behavior

I'd expect jooq to generate the specified schema into my specified directory

### Actual behavior

Task was executed without any error code, but the output dir is still empty...

### Steps to reproduce the problem

In my Task, I start and PostgreSQL container, apply an flyway migrate to it and then let jooq generate the code from that migrated DB

This is the last part of the gradle task (the reference `it` is the autoclosable PostgresTestcontainer):

```
tasks.register("generateJooqCode") {
    group = "jooq"
    description = "Starts a PostgreSQL Testcontainer, applies Flyway migrations, and generates JOOQ code."

    doLast {
      //Start PostgreSQL Container as Autoclosable
      //.....
      //Apply flyway migrations
      //.....

      val jooq = org.jooq.meta.jaxb.Configuration()
                          .withJdbc(
                              org.jooq.meta.jaxb.Jdbc().apply {
                                  url = it.jdbcUrl
                                  user = it.username
                                  password = it.password
                                  driver = "org.postgresql.Driver"
                              }
                          )
                          .withGenerator(
                              org.jooq.meta.jaxb.Generator().apply {
                                  name = "org.jooq.codegen.KotlinGenerator"
                                  database = org.jooq.meta.jaxb.Database().apply {
                                     name = "org.jooq.meta.postgres.PostgresDatabase"
                                     inputSchema = "public"
                                     excludes = "flyway_schema_history"
                                  }
                                  generate = org.jooq.meta.jaxb.Generate().apply {
                                      isRecords = false
                                      isPojos = true
                                      isPojosAsKotlinDataClasses = true
                                      isPojosEqualsAndHashCode = true
                                      isKotlinNotNullPojoAttributes = true
                                      isImplicitJoinPathsToMany = false
                                   }
                                   target = org.jooq.meta.jaxb.Target().apply {
                                      packageName = "de.test.db.jooq"
                                      directory = "src/main/generated"
                                   }
                             }
                        )
        org.jooq.codegen.GenerationTool.generate(jooq)
    }
}
````

And here are the necessary classpath dependencies specified in the jooq docs: 
```
buildscript {
    dependencies {
        classpath("org.postgresql:postgresql:42.7.4")
        classpath("org.flywaydb:flyway-database-postgresql:10.17.2")
        classpath("org.jooq:jooq:3.19.11")
        classpath("org.jooq:jooq-codegen:3.19.11")
        classpath("org.jooq:jooq-meta:3.19.11")
        classpath("org.testcontainers:postgresql:1.20.1")
    }
}
```

To make sure the issue lies not in my Configuration, I used the regular Jooq Codegen Gradle Plugin inside my task like this `jooq {...}` with the same configuration and there I got the wanted Output...

Idk. if I'm missing something very obvious but I'd hope to get at least a warning inside my gradle task if jooq doesn't like something. Instead, I just get this:

```
Task :generateJooqCode
BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
```

### jOOQ Version

JOOQ Open Source 3.19.11

### Database product and version

PostgreSQL 16.2

### Java Version

Oracle GraalVM version "21.0.1" 2023-10-17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.4

**Comment by lukaseder** [comment]
> but I'd hope to get at least a warning inside my gradle task if jooq doesn't like something.

Have you tried adding `--info` to your command to get log output?

**Comment by KrisReal** [comment]
Thanks for the hint💪🏽

I just realized Gradle put the Generated code all the time into: /Users/kristian/.gradle/daemon/8.8/src/main/generated  🤦🏽

**Comment by lukaseder** [comment]
Ah yes, "obviously." The plugin knows the plugin/project location and resolves relative paths relative to the project, which is what everyone wants, but if you run the standalone code generator, then that doesn't know the context from which it is run, i.e. it just relies on the JVM to resolve relative paths.
