### ISSUE TITLE
Typo in section "settings-implicit-join-type"

### ISSUE THREAD

**Issue by northcoder-repo** [jOOQ/jOOQ#17142]
### The documentation URL

https://www.jooq.org/doc/3.19/manual/sql-building/dsl-context/custom-settings/settings-implicit-join-type/

### Feedback

The code `withRenderImplicitJoinTypeToMany` should be `withRenderImplicitJoinToManyType`.

Error "cannot find symbol" if you try to use the code provided in the manual.

See also the 3.19 JavaDoc for [withRenderImplicitJoinToManyType](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/conf/Settings.html#withRenderImplicitJoinToManyType(org.jooq.conf.RenderImplicitJoinType)) (which is correct).

**Comment by lukaseder** [comment]
Thanks a lot for your report. Fixed.
