### ISSUE TITLE
Explicit path join with Kotlin mapping fails because of alias

### ISSUE THREAD

**Issue by SightStudio** [jOOQ/jOOQ#17157]
### Expected behavior

I'm confused this is bug. 
I report this since it works differently in Java and Kotlin.

**can we see this as a bug?**
(I hope these two work the same way.)

---- 

When I tried to use ExplicitPathJoin like select as Table, Kotlin gives MappingException

```kotlin
data class FilmWithActor(
    val film: Film,
    val filmActor: FilmActor,
    val actor: Actor
);

// kotlin cause NPE
fun findFilmWithActorsList(): List<FilmWithActor> {
    return dslContext
        .select(
            FILM,
            FILM.filmActor,
            FILM.filmActor.actor
        ).from(FILM)
        .join(FILM.filmActor)
        .join(FILM.filmActor.actor)
        .fetchInto(FilmWithActor::class.java)
}
```

But It works fine in java

```java
// works fine when FilmWithActor is java record either.
@Getter
public class FilmWithActor {
    private final Film film;
    private final FilmActor filmActor;
    private final Actor actor;

    public FilmWithActor(Film film, FilmActor filmActor, Actor actor) {
        this.film = film;
        this.filmActor = filmActor;
        this.actor = actor;
    }
}

// (java) this works fine
public List<FilmWithActor> findFilmWithActorsList() {
    return dslContext.select(
                    FILM,
                    FILM.filmActor(),
                    FILM.filmActor().actor()
            )
            .from(FILM)
            .join(FILM.filmActor())
            .join(FILM.filmActor().actor())
            .fetchInto(FilmWithActor.class);
}
```

### Actual behavior

After spending some time debugging, I found the difference.
**ImmutablePOJOMapper** in DefaultRecordMapper. 

[(here)](https://github.com/jOOQ/jOOQ/blob/2766f16ce52e1b3efdb8c54790ed1704e3b73267/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java#L1029)
```java
ImmutablePOJOMapper(
    Constructor<E> constructor, 
    Class<?>[] parameterTypes, 
    /* this one cause trouble */ List<String> propertyNames, 
   boolean supportsNesting
) {
    //....
}
```

In Kotlin, **'propertyNames'** (constructor parameter of the ImmutablePOJOMapper) 
are fixedly entered with field names of the Kotlin data class. [(here)](https://github.com/jOOQ/jOOQ/blob/2766f16ce52e1b3efdb8c54790ed1704e3b73267/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java#L542)

However, in ExplicitPathJoin, the mapping fails because alias goes 'alias_xxx' rather than the field name.

On the contrary, in Java, 'propertyNames' are entered as EmptyList(). (so it can be handled in [here](https://github.com/jOOQ/jOOQ/blob/2766f16ce52e1b3efdb8c54790ed1704e3b73267/jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java#L1047))
So it's entered in accordance with the constructor order and operates normally. Regardless of alias name.

It also works in Kotlin if I specify an alias, as shown in the attached MCVE. 
However, I’m concerned that the difference in behavior between Java and Kotlin might negatively impact the user experience. 
I even had to spend a lot of time to figure out why they behaved differently.

<img width="1230" alt="image" src="https://github.com/user-attachments/assets/ee2b1b6d-4fb6-4be4-9403-18e1587bd6b4">

### Steps to reproduce the problem

MCVE is [here.](https://github.com/SightStudio/jOOQ-mcve/blob/mcve/sightstudio-%231/jOOQ-mcve-kotlin-mysql/src/test/kotlin/org/jooq/mcve/test/kotlin/mysql/KotlinTest.kt) 

this is fail case [(link)](https://github.com/SightStudio/jOOQ-mcve/blob/mcve/sightstudio-%231/jOOQ-mcve-kotlin-mysql/src/test/kotlin/org/jooq/mcve/test/kotlin/mysql/KotlinTest.kt#L150)

### jOOQ Version

jOOQ oss 3.19.11

### Database product and version

not database specific

### Java Version

not jvm specific

### JDBC / R2DBC driver name and version (include name if unofficial driver)

not JDBC driver specific

**Comment by lukaseder** [comment]
Thanks for your report. I believe the `DefaultRecordMapper` behaviour is laid out without doubt? See the Javadoc:

- https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/impl/DefaultRecordMapper.html

See:

> If Kotlin is available and the argument class has Kotlin reflection meta data available, and [Settings.isMapConstructorParameterNamesInKotlin()](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/conf/Settings.html#isMapConstructorParameterNamesInKotlin()) is turned on, parameter names are reflected and used

**Comment by SightStudio** [comment]
@lukaseder 

Thanks a lot! I read https://github.com/jOOQ/jOOQ/issues/4627 and https://github.com/jOOQ/jOOQ/issues/8959

Looks like the reason **mapConstructorParameterNames's** default value (for java) is false is for backward compatibility.

<img width="576" alt="image" src="https://github.com/user-attachments/assets/af810804-d932-49b2-bac5-f2d65b82d00e">

I'm considering whether to turn off this setting (because only for ExplicitPathJoin) or to assign an alias to each path

the reason I thought that was...
this looks much better to me

```kotlin
fun findFilmWithActorsListLast(): List<FilmWithActorName> {
        return dslContext
            .select(
                FILM,
                FILM.filmActor,
                FILM.filmActor.actor,
            ).from(FILM)
            .join(FILM.filmActor)
            .join(FILM.filmActor.actor)
            .fetchInto(FilmWithActor::class.java)
    }
```

rather than this. :)

```kotlin
fun findFilmWithActorsListLast(): List<FilmWithActorName> {
        val FILM_ACTOR = FILM.filmActor.`as`("filmActor")
        val ACTOR = FILM.filmActor.actor.`as`("actor")
        return dslContext
            .select(
                FILM,
                FILM_ACTOR,
                ACTOR,
            ).from(FILM)
            .join(FILM_ACTOR)
            .join(ACTOR)
            .fetchInto(FilmWithActor::class.java)
    }
```

It seems like I'll have to choose one of them. but agin, Thanks a lot

**Comment by lukaseder** [comment]
Well, I can certainly see your point. The aliases are being generated this way because they're designed  to:

- Be unpredictable (users shouldn't rely on it)
- Unique within the query (for obvious reasons)
- Stable across queries / VMs / etc. (to improve cachability of execution plans)

But these features are desirable mostly for the implicit join part of the feature, not the projection part of paths (tables in general), where I can certainly see how you'd like the implicit name of the column to be `actor`, not `alias_9137419032874`.

I'll consider this for the future:

- https://github.com/jOOQ/jOOQ/issues/17170

Perhaps, the implicit column alias can be different from the implicit table alias, or we simply make the `DefaultRecordMapper` aware of this situation.
