### ISSUE TITLE
NVARCHAR types Appending 'N' to restrict appending in query

### ISSUE THREAD

**Issue by muskaan62** [jOOQ/jOOQ#17164]
### Your question

for NVARCHAR type jooq is appending 'N' for values in insert query with DEFAULT dialect.

```java
Field<?> textCol = DSL.field("text_col", SQLDataType.NVARCHAR);
fieldMap.put(textCol, "Some Text");
context.insertInto(DSL.table(tableName),
                    fieldMap.keySet()).values(fieldMap.values());
```

query Generated

```sql
insert Query insert into denodo_data_types_insert_mysql (text_col)
values (N'Some Text')
```
but denodo is not able to parse the query..
**is there a way or settings in jooq context object to prevent appending the 'N' for NVARCHAR types.?**

### jOOQ Version

3.17.3

### Database product and version

Denodo 8

### Java Version

11

### JDBC / R2DBC driver name and version (include name if unofficial driver)

Denodo 8 driver

**Comment by lukaseder** [comment]
Thanks for your message.

Assuming you just want to remove the `N`, you could either:

- Use an `ExecuteListener` and patch all generated SQL to replace `N'` by `'`
- Use the `SQLDataType.VARCHAR` type instead, and possibly (depending on what Denodo requires), implement your own custom data type binding: https://www.jooq.org/doc/latest/manual/sql-building/queryparts/custom-bindings/
