### ISSUE TITLE
SQL Translation Error

### ISSUE THREAD

**Issue by wordhardqi** [jOOQ/jOOQ#17171]
### SQL translator incorrectly translates this query:

```sql
WITH
  FUNCTION answer()
  RETURNS BIGINT
  RETURN 42
SELECT 'The answer is ' || CAST(answer() as varchar)

**Comment by lukaseder** [comment]
Thanks for your report.

Duplicate of https://github.com/jOOQ/jOOQ/issues/11460

**Comment by lukaseder** [comment]
What SQL dialect is your example from?
