### ISSUE TITLE
pgsql DDL generate JAVAPO create index will be error

### ISSUE THREAD

**Issue by mrone0** [jOOQ/jOOQ#17175]
### Expected behavior

I want to produce Java PO objects through SQL

### Actual behavior

![Snipaste_2024-09-03_14-46-21](https://github.com/user-attachments/assets/5e14e4dc-4bfc-4625-acd6-dd58c6757874)

### Steps to reproduce the problem

database: pgsql,
SQL DDL FIle
jooq version: 3.18.18
driver: r2dbc
sql：

```sql
CREATE  TABLE public.activity_daily_check (
    id integer GENERATED BY DEFAULT AS IDENTITY ,
   create_time bigint NOT NULL,
)
CREATE INDEX IF NOT EXISTS activity_daily_check_create_time ON public.activity_daily_check USING btree (create_time) TABLESPACE pg_default;
```

### jOOQ Version

3.18.18

### Database product and version

pgsql 14.4

### Java Version

17.0.9

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:r2dbc-postgresql:1.0.2.RELEASE

**Comment by lukaseder** [comment]
Thanks for your message.

I'm assuming you're using the `DDLDatabase`:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl/

We'll never support 100% of all vendor specific storage clauses, it's simply not possible / reasonable. There will always be limitations with the `DDLDatabase`.

You can comment out your `TABLESPACE` with jOOQ's parser comment ignore syntax (commenting it only for jOOQ, not for PostgreSQL):
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-parser/

Or, just use testcontainers for your code generation, see e.g.
https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

I hope this helps
