### ISSUE TITLE
Add native support for DISTINCT ON in DuckDB

### ISSUE THREAD

**Issue by sergey-pashkevich** [jOOQ/jOOQ#17181]
### The documentation URL

https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/select-clause/select-clause-distinct-on/

### Feedback

DuckDB supports 'distinct on' syntax.

**Comment by DavidSousaZ** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by sergey-pashkevich** [comment]
I mean that regarding the official documentation duckdb support distinct on syntax. The documentation may be outdated

**Comment by lukaseder** [comment]
Thanks a lot for your report.

This isn't strictly a documentation bug. Rather, we didn't support the clause at all for DuckDB. Will check it out right away.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.20. Thanks again for your report!
