### ISSUE TITLE
(gradle codegen) support incremental build and caching using allInputsDeclared

### ISSUE THREAD

**Issue by laurentperez** [jOOQ/jOOQ#17201]
### Use case

Hello

context : 

- `allInputsDeclared` does not seem possible using the official jooq gradle plugin (this one, not the one from Etienne)
- see https://github.com/etiennestuder/gradle-jooq-plugin?tab=readme-ov-file#configuring-the-jooq-generation-task-to-participate-in-incremental-builds-and-build-caching
- the following code does not build
 
![image](https://github.com/user-attachments/assets/ff58eb29-9383-4c33-9700-b07276558201)

- throwing

```
Exception is:
ScriptCompilationException(scriptCompilationErrors=[ScriptCompilationError(message=Unresolved reference: allInputsDeclared, location=/home/lperez/.gradle/.tmp/gradle-kotlin-dsl-14738013662644042356.tmp/build.gradle.kts (96:5))])
        at org.gradle.kotlin.dsl.support.KotlinCompilerKt.compileKotlinScriptModuleTo(KotlinCompiler.kt:191)
        at org.gradle.kotlin.dsl.support.KotlinCompilerKt.compileKotlinScriptToDirectory(KotlinCompiler.kt:149)
```

### Possible solution

- allow `allInputsDeclared`

### Possible workarounds

- I'm curious if workarounds may exist ?

### jOOQ Version

jooqVersion=3.19.6

### Database product and version

postgres 15

### Java Version

21

**Comment by lukaseder** [comment]
Thanks for your message. I don't understand why you want this flag in jOOQ. It's just an arbitrary solution to a problem by the third party plugin - why would we copy it?

Our plugin detects when you declare inputs that aren't our own, so you don't have to do anything special, see:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-gradle/codegen-gradle-data-change-management/

I hope this helps

**Comment by lukaseder** [comment]
> jooqVersion=3.19.6

I suggest upgrading, though. We keep fixing bugs in this experimental feature!
