### ISSUE TITLE
for Binary jooq is encoding the value.

### ISSUE THREAD

**Issue by muskaan62** [jOOQ/jOOQ#17233]
### Your question

I am trying to insert value for binary types..
say value is "hello" so the input i am giving in the query is 
```
Field<?> binary_col = DSL.field("binary_col", SQLDataType.BINARY);
            fieldMap.put(binary_col, "68656C6C6F");
Query insertQueryTemplate = context.insertInto(DSL.table("binarybittest"),
                    fieldMap.keySet()).values(fieldMap.values());
```
The query is generated with encoding 
```
insert  into binarybittest (binary_col)
values (X'36383635364336433646')
```
is there a way in jooq ( probably a setting via context object or other way) that prevents this encoding for binary types
so that the query genrated will look like this 
```
insert  into binarybittest (binary_col)
values ('68656C6C6F')
```

### jOOQ Version

3.17.3

### Database product and version

Denodo 8

### Java Version

11

**Comment by lukaseder** [comment]
Just use `VARCHAR` instead of `BINARY` to get a string literal in your output.
