### ISSUE TITLE
Diagnostics not working

### ISSUE THREAD

**Issue by oliveryasuna** [jOOQ/jOOQ#17273]
### Expected behavior

I expected the `DiagnosticsListener` methods to be called.

### Actual behavior

The `DiagnosticsListener` methods are not called.

### Steps to reproduce the problem

```java
final Connection connection = ...;
final ConnectionProvider connectionProvider = new DefaultConnectionProvider(connection);

final DSLContext dsl = DSL.using(connectionProvider, SQLDialect.POSTGRES);

dsl.configuration().set(new LoggingDiagnosticsListener());

final List<Long> ids = dsl
        .select(PORTAL_USER.ID)
        .from(PORTAL_USER)
        .limit(100)
        .fetch(Record1::component1);

for(final Long id : ids) {
    dsl
            .selectFrom(PORTAL_USER)
            .where(PORTAL_USER.ID.eq(id))
            .fetch();
}
```

Thank you for taking your time to look at my issue.

### jOOQ Version

jOOQ Community Edition 3.19.11

### Database product and version

PosgreSQL

### Java Version

21

**Comment by oliveryasuna** [comment]
The following works, but seems highly unintuitive. What am I missing?

```java
Connection connection = dataSourceProvider.get().getConnection();
ConnectionProvider connectionProvider = new DefaultConnectionProvider(connection);

DSLContext dsl = DSL.using(connectionProvider, SQLDialect.POSTGRES);

dsl.configuration().set(new LoggingDiagnosticsListener());

connection = dsl.diagnosticsConnection();
connectionProvider = new DefaultConnectionProvider(connection);

dsl = DSL.using(connectionProvider, SQLDialect.POSTGRES);
```

**Comment by lukaseder** [comment]
We can't turn on diagnostics within jOOQ's internals by default. But there's `Settings.diagnosticsConnection` to do this for you, as documented throughout the manual and the Javadoc:

- https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-diagnostics-connection/
- https://www.jooq.org/doc/latest/manual/sql-execution/diagnostics/
- https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/DiagnosticsListener.html

I hope this helps

**Comment by oliveryasuna** [comment]
@lukaseder Thanks. Is there a way to disable the default jOOQ `DiagnosticsListener`?

**Comment by lukaseder** [comment]
> Thanks. Is there a way to disable the default jOOQ `DiagnosticsListener`? Also, my solution would always cause a connection leak.

I'm assuming you mean the logging listener. Have you read the linked resources from my previous comment?

> Also, my solution would always cause a connection leak.

I cannot see your complete solution, you've only shown snippets. But you're managing your own JDBC connection, it seems, so you must handle its resource management.

> I tried this, but it did not work:

What did not work, specifically? Did you add a `DiagnosticsListener` in another section of the code?

**Comment by oliveryasuna** [comment]
> What did not work, specifically? Did you add a DiagnosticsListener in another section of the code?

Shouldn't that code add the default diagnostics listener?

**Comment by oliveryasuna** [comment]
My end goal would be to create a `DSLContext` that would track diagnostics, such as repeated statements.

**Comment by oliveryasuna** [comment]
@lukaseder First, I just want to thank you very much for taking your time to discuss this with me.

I discovered that some of my developers have a tendency to write N+1 queries. It has been a struggle to catch all of these, as I cannot be the one to review every single PR. I recently discovered jOOQ diagnostics feature, and would love to use it to find potential inefficient code (not just N+1s).

1. I would like to disable the default listener because I need a custom listener to print logs that begin with specific text, so we can easily identify them. Specifically, we use New Relic, so we can set up alerts for logs that contain a specific text.
2. Sorry, I do not understand this question.

Here is my full code. We use Google Guice for injection, but the same concept could be applied to other DI frameworks such as Spring.

```java
import com.google.inject.persist.PersistService;
import com.google.inject.persist.UnitOfWork;
import jakarta.inject.Inject;
import jakarta.inject.Provider;
import jakarta.inject.Singleton;
import org.jooq.Configuration;
import org.jooq.ConnectionProvider;
import org.jooq.DSLContext;
import org.jooq.SQLDialect;
import org.jooq.conf.Settings;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultConfiguration;
import org.jooq.impl.DefaultConnectionProvider;
import org.jooq.impl.DefaultDiagnosticsListenerProvider;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Optional;

@Singleton
class DSLContextProvider implements Provider<DSLContext>, UnitOfWork, PersistService {

    // Static fields
    //--------------------------------------------------

    private static final Logger LOGGER = LoggerFactory.getLogger(DSLContextProvider.class);

    // Fields
    //--------------------------------------------------

    private final ThreadLocal<DSLContext> currentDsl = new ThreadLocal<>();

    private final ThreadLocal<DefaultConnectionProvider> currentConnectionProvider = new ThreadLocal<>();

    private final Provider<DataSource> dataSourceProvider;

    private final Provider<Settings> settingsProvider;

    private final Provider<SQLDialect> sqlDialectProvider;

    // Constructors
    //--------------------------------------------------

    @Inject
    public DSLContextProvider(
            final Provider<DataSource> dataSourceProvider,
            final Provider<Settings> settingsProvider,
            final Provider<SQLDialect> sqlDialectProvider
    ) {
        super();

        this.dataSourceProvider = dataSourceProvider;
        this.settingsProvider = settingsProvider;
        this.sqlDialectProvider = sqlDialectProvider
    }

    // Methods
    //--------------------------------------------------

    @Override
    public DSLContext get() {
        return Optional.ofNullable(currentDsl.get())
                .orElseGet(() -> {
                    begin();

                    return currentDsl.get();
                });
    }

    @Override
    public void begin() {
        if(isWorking()) {
            LOGGER.trace("Work already begun on thread: {}", Thread.currentThread().getName(), new Exception());

            return;
        }

        prepareDsl();
    }

    private void prepareDsl() {
        final DataSource dataSource = dataSourceProvider.get();
        final Settings settings = settingsProvider.get();
        final SQLDialect sqlDialect = sqlDialectProvider.get();

        DefaultConnectionProvider connectionProvider = null;

        try {
            connectionProvider = new DefaultConnectionProvider(dataSource.getConnection());

            final Configuration tempConfig = prepareConfig(settings, sqlDialect, connectionProvider)
                    .set(new DefaultDiagnosticsListenerProvider(new LoggingDiagnosticsListener()));

            final Connection connection = DSL.using(tempConfig)
                    .diagnosticsConnection();

            connectionProvider = new DefaultConnectionProvider(connection);

            final Configuration finalConfig = tempConfig.derive(connectionProvider);

            final DSLContext dsl = DSL.using(finalConfig);

            currentDsl.set(dsl);
            currentConnectionProvider.set(connectionProvider);
        } catch (final Exception e) {
            if(connectionProvider != null) {
                try {
                    connectionProvider.acquire()
                            .close();
                } catch (final SQLException e2) {
                    LOGGER.error("Failed to close connection.", e2);
                }
            }

            throw new RuntimeException("Failed to get connection on thread: " + Thread.currentThread().getName(), e);
        }
    }

    private Configuration prepareConfig(final Settings settings, final SQLDialect sqlDialect, final ConnectionProvider connectionProvider) {
        return new DefaultConfiguration()
                .set(settings.withDiagnosticsLogging(false))
                .set(sqlDialect)
                .set(connectionProvider);
    }

    @Override
    public void end() {
        if(currentDsl.get() == null) {
            LOGGER.trace("No work to end on thread: {}", Thread.currentThread().getName(), new Exception());

            return;
        }

        try {
            LOGGER.debug("Closing connection provider.");

            currentConnectionProvider.get()
                    .acquire()
                    .close();
        } catch(final SQLException e) {
            LOGGER.error("Failed to close connection.", e);
        }

        currentDsl.remove();
        currentConnectionProvider.remove();
    }

    @Override
    public void start() {
        // NO-OP.
    }

    @Override
    public void stop() {
        // NO-OP.
    }

    DefaultConnectionProvider getCurrentConnectionProvider() {
        return currentConnectionProvider.get();
    }

    boolean isWorking() {
        return (currentDsl.get() != null);
    }

}
```

`LoggingDiagnosticsListener` is just a custom implementation of `DiagnosticsListener`. It is not strictly necessary, as I could use jOOQ's implementation and filter those logs, so it's just a preference.

The code that I need help with is really that in `prepareDsl()`. As you can probably see, this method will always cause a connection leak. That is what I need help with. Is there a way to enable diagnostics without having to create a temporary configuration just to obtain a `DiagnosticsConnection`?

**Comment by lukaseder** [comment]
OK, I see. jOOQ also has a `org.jooq.impl.LoggingDiagnosticsListener`, thus my confusion.

So, just:

1. Add the listener to the `Configuration`
2. Turn on `DiagnosticsConnection.ON` in your `Settings`
3. Turn off jOOQ's `Settings.diagnosticsLogging`

Pretty much what the docs say. Do you think the docs weren't clear about this? If so, how could they be improved? Here are again the links:

- https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-diagnostics-connection/
- https://www.jooq.org/doc/latest/manual/sql-execution/diagnostics/
- https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/DiagnosticsListener.html

**Comment by oliveryasuna** [comment]
I'll get back to you on the docs, thanks.

Still confused though, how can I do this without creating two connections? My above code always causes a connection leak.

**Comment by lukaseder** [comment]
Aaah, I see the problem now. There actually seems to be a bug where the internal `DiagnosticsConnection` wrapper (which is created when using `DiagnosticsConnection.ON`) is created afresh for every query execution. As such, diagnostics that should span several queries don't work, such as the repeated statement detection.

I'll look into this early next week.

> Still confused though, how can I do this without creating two connections? My above code always causes a connection leak.

Well, from a high level, I'd say you shouldn't call `acquire()` on the `ConnectionProvider` (please read its Javadoc for why). Also, make sure you close the original `Connection` from your `DataSource`. A debugger certainly helps here... It's hard to debug this only looking at code.

**Comment by oliveryasuna** [comment]
@lukaseder That seems to explain why queries using the `dsl` from the following code never trigger diagnostics. Thank you.

```java
final Connection connection = ...;
final ConnectionProvider connectionProvider = new DefaultConnectionProvider(connection);

final DSLContext dsl = DSL.using(new DefaultConfiguration()
        .set(connectionProvider)
        .set(SQLDialect.POSTGRES)
        .set(new Settings().withDiagnosticsConnection(DiagnosticsConnection.ON)));
```

**Comment by oliveryasuna** [comment]
@lukaseder Did you want to reopen this issue or open a new one?

**Comment by lukaseder** [comment]
Thank you for your patience. My last comment was:

> I'll look into this early next week.

**Comment by oliveryasuna** [comment]
@lukaseder Sure, I just assumed there would be an open issue, either this one reopened or a new one but, I couldn't find one.

**Comment by lukaseder** [comment]
Issue discussiong `DiagnosticsConnection.ON` behaviour:

- https://github.com/jOOQ/jOOQ/issues/17343
