### ISSUE TITLE
Add support for DSL.currentCatalog() in MariaDB, MemSQL, MySQL via the DATABASE() function

### ISSUE THREAD

**Issue by RenBrand** [jOOQ/jOOQ#17341]
### Expected behavior

Executing a "select database()" on a MySQL DB to return the currently used DB.

### Actual behavior

The ParsingConnection translates a call of "`select database()`" on a MySQL DB to "`select current_database()`" but this function isn't supported on a MySQL and ends in the following error from the DB:

```
SQL State  : 42000
Error Code : 1305
Message    : FUNCTION mysql_db.current_database does not exist
```

### Steps to reproduce the problem

- use a ParsingConnection, the [Online-Translator](https://www.jooq.org/translate/) or the ParseCLI
- translate the statement "`select database()`" into the MySQL dialect
- execute the result "`select current_database()`" on a MySQL instance

### jOOQ Version

jOOQ OpenSource  3.19.11

### Database product and version

MySQL 9.0.1

### Java Version

openJDK 23 2024-09-17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.mysql:mysql-connector-j:8.3.0

**Comment by RenBrand** [comment]
It seams that the `org.jooq.impl.CurrentCatalog` is missing a "MySQL"/"MariaDB" case in the switch of the `accept(Context)` - method.

**Comment by lukaseder** [comment]
Thanks for your suggestion. Sure, we can map the `DSL.currentCatalog()` implementation to MySQL's `DATABASE()` function. We're doing this already with `DSL.currentSchema()` (as MySQL doesn't have schemas, only catalogs).

**Comment by RenBrand** [comment]
Thanks that was fast.
