### ISSUE TITLE
Firebird wrong create sequence syntax

### ISSUE THREAD

**Issue by RenBrand** [jOOQ/jOOQ#17355]
### Expected behavior

Create a sequence in a firebird DB with a start value.

### Actual behavior

The SQL`CREATE SEQUENCE sequence_name MINVALUE 1;` is translated to 'CREATE SEQUENCE sequence_name MINVALUE 1;' in Firebird too, but Firebird uses `STARTS WITH` (see: [Firebird Sequence](https://www.firebirdsql.org/file/documentation/chunk/en/refdocs/fblangref40/fblangref40-ddl-sequence.html)) instead of `MINVALUE` and hence the SQL fails with:

```
SQL Error [335544634] [42000]: Dynamic SQL Error; SQL error code = -104; Token unknown - line 1, column 31; MINVALUE [SQLState:42000, ISC error code:335544634]

Error position: pos: 30
```

### Steps to reproduce the problem

- use a ParsingConnection, the [Online-Translator](https://www.jooq.org/translate/) or the ParserCLI
- translate the statement "CREATE SEQUENCE sequence_name MINVALUE 1;" into the Firebird dialect
- execute the result "create sequence sequence_name minvalue 1" on a MySQL instance

### jOOQ Version

jOOQ OpenSource 3.19.11

### Database product and version

Firebird 4.0 LI-V4.0.2.2816

### Java Version

openJDK 23 2024-09-17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.firebirdsql.jdbc:jaybird:5.0.4.java11

**Comment by RenBrand** [comment]
It seams that the org.jooq.impl.CreateSequenceImpl#REQUIRES_START_WITH Set is missing the "FIREBIRD"-Dialect.

**Comment by lukaseder** [comment]
Thanks for your message.

`START WITH` and `MINVALUE` aren't the same thing, so your expectation here isn't justified.

Please note that we don't report SQL clauses that we *know* aren't supported in the translator yet. In those cases, jOOQ just renders the default syntax, see:

- https://github.com/jOOQ/jOOQ/issues/9319

**Comment by lukaseder** [comment]
> * execute the result "create sequence sequence_name minvalue 1" on a MySQL instance

Just to be sure, this is a typo, yes? MySQL isn't really involved in this issue?

**Comment by RenBrand** [comment]
Yes sorry this was a mistake.

> > * execute the result "create sequence sequence_name minvalue 1" on a MySQL instance
> 
> Just to be sure, this is a typo, yes? MySQL isn't really involved in this issue?

**Comment by RenBrand** [comment]
> Thanks for your message.
> 
> `START WITH` and `MINVALUE` aren't the same thing, so your expectation here isn't justified.
> 
> Please note that we don't report SQL clauses that we _know_ aren't supported in the translator yet. In those cases, jOOQ just renders the default syntax, see:
> 
>     * [Translator should report unsupported SQL syntax #9319](https://github.com/jOOQ/jOOQ/issues/9319)

Yes `minValue` and `start with` are two different kind of things but failing as mentioned in https://github.com/jOOQ/jOOQ/issues/9319 isn't the right thing from my point of view. Maybe the behavior should be configurable, e.g. in the settings, so the developer can decided if he likes to

- fail (as requested in https://github.com/jOOQ/jOOQ/issues/9319)
- render the content as is (the current behavior)
- drop the unsupported property or
- adapt the element to a different one

This could be different implementations of an `UnsupportedSQLSyntaxStrategy` configured in the settings.

**Comment by lukaseder** [comment]
Thanks for your suggestions. When / if we implement #9319, rest assured we'll do the right thing.
