### ISSUE TITLE
Casting to allow comparison between columns of different types affects performance

### ISSUE THREAD

**Issue by J4000** [jOOQ/jOOQ#17375]
### Your question

```
jooq.select(TABLE1.DESCRIPTION)
  .join(TABLE2)
  .on(TABLE2.CODE.eq(TABLE1.ID)
  .fetch()
```

TABLE2.CODE is a varchar, whereas TABLE1.ID is a Number.  This comparison works fine in straight sql, but in java/jooq I need to cast to ensure the types are the same.  I've done this 

```
jooq.select(TABLE1.DESCRIPTION)
  .join(TABLE2)
  .on(TABLE2.CODE.eq(TABLE1.ID.cast(VARCHAR(10)))
  .fetch()
```

This works, but does have an impact on the performance of the query, and the buffers increased by ~25-30%.  Any suggestions on different approaches would be welcome! Its worth noting that (unfortunately) changing the types of the tables is not viable, these are legacy tables and I'm porting an existing query over to jooq.

### jOOQ Version

1.0.0-alpha.14

### Database product and version

Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

### Java Version

OpenJDK Runtime Environment Corretto-21.0.1.12.1

**Comment by lukaseder** [comment]
Thanks for your message. A `CAST` is a `CAST`, so this behaviour is expected. You probably just want to ignore the type difference, though be careful, the auto-conversion can still prevent index access, see this article:
https://blog.jooq.org/are-you-binding-your-oracle-dates-correctly-i-bet-you-arent/

In any case, what you're looking for is data type coercion:
https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/datatype-coercions/

**Comment by lukaseder** [comment]
I'll add a link between manual sections and Javadoc to make `coerce()` more discoverable:
https://github.com/jOOQ/jOOQ/issues/17376

Of course, you can always resort to using rawtypes as well if you want to ignore types in jOOQ:

```java
TABLE2.CODE.eq((Field) TABLE1.ID)
```

**Comment by J4000** [comment]
Amazing, thanks @lukaseder
