### ISSUE TITLE
IN-list padding truncates row IN lists to 1000 elements in Oracle pre 23ai

### ISSUE THREAD

**Issue by alf** [jOOQ/jOOQ#17397]
### Expected behavior

After we enabled IN-list Padding we've received reports of incomplete/wrong results from our APIs, it seems jOOQ now truncates in-lists to 1000 elements.

We expect jOOQ to produce large enough in-lists to contain all our provided values. If we break some limit we should get an exception, not return bad data.

### Actual behavior

After enabling in-list-padding it seems in-lists with more than 1000 elements gets silently truncated to 1000.

### Steps to reproduce the problem

This is a weird one. I haven't been able to reproduce the issue on Oracle 18 XE yet, but when I run the following test against our Oracle 19 in our DEMO (clone of production) database it fails.

```java
        var keyRows = ctx
                .select(EMNE.INSTITUSJONSNR_EIER, EMNE.INSTITUSJONSNR, EMNE.EMNEKODE, EMNE.VERSJONSKODE)
                .from(EMNE)
                .limit(1024)
                .fetch();

        var count = ctx
                .selectCount()
                .from(EMNE)
                .where(row(EMNE.INSTITUSJONSNR_EIER, EMNE.INSTITUSJONSNR, EMNE.EMNEKODE, EMNE.VERSJONSKODE).in(keyRows))
                .fetchOne(0, Integer.class);


        assertEquals(keyRows.size(), count);
```

The assertion fails because the resulting count is 1000, not the expected 1024.

### jOOQ Version

3.19.12

### Database product and version

Oracle 19

**Comment by alf** [comment]
If I run the sql produced by the following against the database directly, I get the expected result.

```
var sql = ctx
                .selectCount()
                .from(EMNE)
                .where(row(EMNE.INSTITUSJONSNR_EIER, EMNE.INSTITUSJONSNR, EMNE.EMNEKODE, EMNE.VERSJONSKODE).in(keyRows)).toString();
```

**Comment by lukaseder** [comment]
Thanks a lot for your report.

**Comment by lukaseder** [comment]
Indeed, it appears that this flag hasn't been implemented for `ROW IN` predicates. Will fix this right away

**Comment by lukaseder** [comment]
Note, this problem is specific to Oracle 19c or earlier. In 23ai, the 1000 element limit of `IN` lists goes away, and the lists can be larger anyway.

**Comment by alf** [comment]
Thank you for the quick handling.
