### ISSUE TITLE
Wrong manual example for enum matchers

### ISSUE THREAD

**Issue by Serjlee** [jOOQ/jOOQ#17427]
### Expected behavior

This configuration snippet is supposed work (also [suggested by the documentation](https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/codegen-matcher-enums/)):
```groovy
jooq {
    configuration {
         generator {
            strategy {
                matchers {
                    enums {
                        enum {
                            expression = "SOMETHING"
                            enumImplements = "myinterface"
                        }
                    }
                }
            }
        }
    }
}
```

It does work using "manual" generation via .xml configuration using jOOQ's codegen jar.

### Actual behavior

> Could not compile build file '/.../build.gradle'.
> startup failed:
  build file '.../build.gradle': 30: Unexpected input: '{' @ line 30, column 6.

The IDE will also be very unhappy about the reserved word `enum` being used that way.

I'm unable to work around the issue as `-Djooq.codegen.configurationFile=jooq-config.xml` is apparently ignored by the gradle plugin

### Steps to reproduce the problem

Just try to run `./gradlew jooqCodegen` using the configuration snippet above, no matter if the enum actually exists in the DB (as the Groovy/Kotlin configuration will fail well before the plugin actually does something)

It will also fail using Kotlin instead of Groovy.

Escaping `enum` as `'enum'` will change the error to:
`> Could not find method enum() for arguments [...]`

### jOOQ Version

3.19.13

### Database product and version

PostgreSQL 15

### Java Version

openjdk 21.0.3 2024-04-16 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.6.0

**Comment by lukaseder** [comment]
Thanks a lot for your report. I'll look into this soon

**Comment by lukaseder** [comment]
The `MatchersEnumTypeListExtension` class that is used here is generated in Java, and as such, no backtick or other type of escaping is available. Thus, we're using the usual approach from the DSL API, where a `_` is appended. The method name is `enum_`.

I'll make sure this is documented correctly

**Comment by lukaseder** [comment]
`default` is also wrong:

- https://www.jooq.org/doc/dev/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-synthetic-objects/codegen-database-synthetic-defaults/

**Comment by lukaseder** [comment]
Fixed. The manual will be updated within a few hours.

**Comment by Serjlee** [comment]
Good to know about the `_` suffix, I had no idea

Thank you so much!
