### ISSUE TITLE
Cannot call Record.reset(Field), Record.original(Field), Record.changed(Field), Record.touched(Field), Record.modified(Field) with embeddable field arguments

### ISSUE THREAD

**Issue by Rattenkrieg** [jOOQ/jOOQ#17433]
### Expected behavior

I have an embeddable composite field consisting of two columns. I get IllegalArgumentException when I try to reset this field in the record

MCVE: https://github.com/Rattenkrieg/jOOQ-mcve/pull/1/files

### Actual behavior

```
 IllegalArgument Field "mcve"."composite_key_example"."entity_1_id", "mcve"."composite_key_example"."entity_2_id" is not contained in row type ("mcve"."composite_key_example"."entity_1_id", "mcve"."composite_key_example"."entity_2_id", "mcve"."composite_key_example"."some_payload")
```

### Steps to reproduce the problem

```java

CompositeKeyExampleRecord record = ctx.fetchOne(COMPOSITE_KEY_EXAMPLE, COMPOSITE_KEY_EXAMPLE.ENTITY_1_ID.eq(1));
record.reset(COMPOSITE_KEY_EXAMPLE.COMPOSITE_ID);
```

```sql

CREATE TABLE mcve.composite_key_example (
  entity_1_id INT NOT NULL,
  entity_2_id INT NOT NULL,
  some_payload TEXT NOT NULL
);

ALTER TABLE mcve.composite_key_example ADD PRIMARY KEY (entity_1_id, entity_2_id);

```

```xml
<generator>
    <database>
        <includes>.*</includes>
        <schemata>

            <!-- PostgreSQL is lower case by default -->
            <schema>
                <inputSchema>mcve</inputSchema>
            </schema>
        </schemata>

        <embeddables>
        <embeddable>
            <catalog/>
            <schema>mvce</schema>
            <name>composite_key_example_id</name>
            <referencingName>composite_id</referencingName>
            <tables>composite_key_example</tables>
            <fields>
                <field><expression>entity_1_id</expression></field>
                <field><expression>entity_2_id</expression></field>
            </fields>
        </embeddable>
        </embeddables>
    </database>
    <generate>
        <generatedAnnotation>false</generatedAnnotation>
    </generate>
    <target>
        <packageName>org.jooq.mcve.java.postgres</packageName>
        <directory>src/main/java</directory>
    </target>
</generator>
```

### jOOQ Version

Open source edition 3.19.13

### Database product and version

postgres:latest

### Java Version

openjdk 21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.2

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can see how this could be reasonably expected to work, given that setters and getters allow this call as well for non-replacing embeddables. Things work as expected with replacing embeddables, including embedded keys:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-embeddable-types/codegen-embedded-keys/

**Comment by lukaseder** [comment]
With non-replacing embeddables, the workaround is to simply iterate over the embeddable's fields and to reset them individually.

**Comment by lukaseder** [comment]
The `Record.original(Field)` method is also affected

**Comment by Rattenkrieg** [comment]
> With non-replacing embeddables, the workaround is to simply iterate over the embeddable's fields and to reset them individually.

Yep, this is how I patched if for now
```javaj
/// works
for (var field : COMPOSITE_KEY_EXAMPLE.COMPOSITE_ID.getTable().fields()) {
    record.reset(field);
}
```

Thank you!

**Comment by lukaseder** [comment]
Fixed in versions: 

- 3.20.0
- 3.19.14 (https://github.com/jOOQ/jOOQ/issues/17436)
- 3.18.21 (https://github.com/jOOQ/jOOQ/issues/17437)
- 3.17.30 (https://github.com/jOOQ/jOOQ/issues/17438)
