### ISSUE TITLE
Close JDBC connection

### ISSUE THREAD

**Issue by o-shevchenko** [jOOQ/jOOQ#17440]
### Your question

What is the best wa to close the connection for DSLContext?

I need to create DSLContext for each request because we can use different configuration confs or creds.

```Kotlin
@Component
class Context() {

    fun create(
        properties: Properties, credentials: Credentials
    ): DSLContext {
        val properties = credentials.toProperties()
        val connection = DriverManager.getConnection("jdbc:sap://${properties.host}:${properties.port}", properties)
        return DSL.using(conn)
    }
}
```
In this case I think JOOQ won't close connection after query execution.

I've tried to use CloseableDSLContext and invoke `close` or utilize Kotlin `use {}` to close the connection. But as far as I see connection is never closed because it's not DefaultCloseableConnectionProvider. And DefaultCloseableConnectionProvider is package private, so we can relly use it.
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/e2398e44-a73f-4aac-aba0-1b3b3a1104d4">

```Kotlin
@Component
class Context() {

    fun create(
        properties: Properties, credentials: Credentials
    ): CloseableDSLContext {
        val properties = credentials.toProperties()
        val connection = DriverManager.getConnection("jdbc:sap://${properties.host}:${properties.port}", properties)
        return DefaultCloseableDSLContext(DefaultConnectionProvider(connection), JDBCUtils.dialect(connection))
    }
}
```
<img width="962" alt="image" src="https://github.com/user-attachments/assets/abdc85bf-6de5-4218-aea5-0aee25a4b739">

### jOOQ Version

3.19.12

### Database product and version

com.sap.cloud.db.jdbc:ngdbc:2.22.11

### Java Version

17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.sap.cloud.db.jdbc:ngdbc:2.22.11

**Comment by o-shevchenko** [comment]
The only way we can use it is migration to `DataSourceConnectionProvider`:
```Kotlin
@Component
class Context() {

    fun create(
        properties: Properties, credentials: Credentials
    ): DSLContext {
        val dataSource = DriverManagerDataSource()
        dataSource.setDriverClassName(DRIVER_CLASS_NAME)
        dataSource.url = "jdbc:sap://${browserProperties.host}:${browserProperties.port}"
        dataSource.connectionProperties = properties
        return DSL.using(DataSourceConnectionProvider(dataSource), JDBCUtils.dialect(dataSource.connection))
    }
}
```

**Comment by o-shevchenko** [comment]
Looks like it doesn't work for reactive context, we need to close connection once stream is completed.
Probably, that means we need DefaultCloseableDSLContext and close it manually.
So, the problem is still valid.

**Comment by o-shevchenko** [comment]
@lukaseder Do you have any ideas?
Thanks!

**Comment by o-shevchenko** [comment]
The only way to create DefaultCloseableConnectionProvider is:
```Kotlin
return DSL.using(url, properties)
```

**Comment by lukaseder** [comment]
The rule of thumb is: whoever creates a resource also closes the resource. So:

- If you're passing a previously created `Connection` to jOOQ, then you must close this connection outside of jOOQ, jOOQ won't do it for you.
- If jOOQ creates a connection for you, then jOOQ must close it for you (e.g. by using the `CloseableDSLContext`).

We don't offer a `CloseableDSLContext` for a reactive context. You'll have to manage resources yourself, e.g. by using `Flux.usingWhen()`: https://projectreactor.io/docs/core/release/api/reactor/core/publisher/Flux.html#usingWhen-org.reactivestreams.Publisher-java.util.function.Function-java.util.function.Function-
