### ISSUE TITLE
Kotlin generated code should use by lazy syntax for cached Path instances

### ISSUE THREAD

**Issue by assylias** [jOOQ/jOOQ#17455]
### Use case

When a foreign key is defined, the generator generates a path such as:

    private lateinit var _instrumenttype: InstrumenttypePath

    /**
     * Get the implicit join path to the
     * <code>instrument.InstrumentType</code> table.
     */
    fun instrumenttype(): InstrumenttypePath {
        if (!this::_instrumenttype.isInitialized)
            _instrumenttype = InstrumenttypePath(this, FK_INSTRUMENT_INSTRUMENTTYPE, null)

        return _instrumenttype;
    }

    val instrumenttype: InstrumenttypePath
        get(): InstrumenttypePath = instrumenttype()

If the value never changes, this could probably be replaced with a `by lazy` delegation:

    val instrumenttype: InstrumenttypePath by lazy { InstrumenttypePath(this, FK_INSTRUMENT_INSTRUMENTTYPE, null) }

    /**
     * Get the implicit join path to the
     * <code>instrument.InstrumentType</code> table.
     */
    fun instrumenttype() = instrumenttype

It simplifies the code and also guarantees thread safety.

### jOOQ Version

jOOQ Pro 3.19.11

### Database product and version

SQL Server 17

### Java Version

21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.microsoft.sqlserver:mssql-jdbc:12.8.1.jre11

**Comment by lukaseder** [comment]
Thanks for your suggestion. Thread safety isn't a real concern here, because the cached values are immutable, so if the instances are initialised multiple times, that has no effect on the runtime. Eventually, all thread local instances will converge towards the "winning" instance.

But I agree, your suggested version does look better.

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.20.0
