### ISSUE TITLE
How to use new construction options for TableImpl?

### ISSUE THREAD

**Issue by Aleksei-Chursin** [jOOQ/jOOQ#17502]
### Your question

Hi, we have used constructor that is now deprecated following way:

```
TableImpl<Record>(
    alias,
    Public.PUBLIC,
    child,
    childPath,
    aliased,
    parameters,
    DSL.comment("some comment"))
```

After upgrade to 3.19.14, this constructor became deprecated. Following constructor appears to be most close option:

```
 public TableImpl(Name name, Schema schema, Table<?> path, ForeignKey<?, R> childPath, InverseForeignKey<?, R> parentPath, Table<R> aliased, Field<?>[] parameters, Comment comment) {
        this(name, schema, path, childPath, parentPath, aliased, parameters, comment, TableOptions.table(), (Condition)null);}
```

So i would expected change to look like this:

```
TableImpl<Record>(
    alias,
    Public.PUBLIC,
    child,
    childPath,
    childPath?.inverseKey,
    aliased,
    parameters,
    DSL.comment("some comment"))
```

But clearly this is not how it is expected to work, as i get following error:

```
None of the following functions can be called with the arguments supplied.
InverseForeignKey<*, Record!>,
```

As per [my comment](https://github.com/jOOQ/jOOQ/commit/2804ddc2d2e4df71369ee52cb650485868379820#diff-139653c6d36401ee567087adbc760961e2ddf2e28ab055862c87fd7e4025febdR229), to me childPath should be inverse of parentPath, meaning <R, ?>. 

I probably miss something, could you please assist?

### jOOQ Version

3.19.14

### Database product and version

postgresql14.12

### Java Version

21

**Comment by lukaseder** [comment]
> So i would expected change to look like this:
> 
> ```
> TableImpl<Record>(
>     alias,
>     Public.PUBLIC,
>     child,
>     childPath,
>     childPath?.inverseKey,
>     aliased,
>     parameters,
>     DSL.comment("some comment"))
> ```

Thanks for your message. You can look at standard `KotlinGenerator` output for examples. You don't have to meddle with the path and inverse path. Those things are constructor arguments of *your* constructor (if you want to support paths), and will be populated by generated path expressions.

If you don't know what these are, or don't care, then just pass a `null` value (knowing that implicit join paths won't be supported by your code).

But again, I think the best option here is to just look at what the out of the box generator is doing and adapt from that. It's also not unlikely that you don't have to re-implement everything. What are you really trying to do? It's very rare that people have to re-implement all of jOOQ's code generation and tamper with internal API like this.

> As per [my comment](https://github.com/jOOQ/jOOQ/commit/2804ddc2d2e4df71369ee52cb650485868379820#diff-139653c6d36401ee567087adbc760961e2ddf2e28ab055862c87fd7e4025febdR229), to me childPath should be inverse of parentPath, meaning <R, ?>.

Well, no, that's not a problem here at all. These types have been designed as they are, and they are correct.
