### ISSUE TITLE
PostgreSQL partitioned table and codegen not using UpdatableRecordImpl.

### ISSUE THREAD

**Issue by witoldsz** [jOOQ/jOOQ#17504]
### Expected behavior

Codegen generates a class extending `UpdatableRecordImpl<...>`.

### Actual behavior

Codegen generates a class extending `TableRecordImpl<...>`.

### Steps to reproduce the problem

I have an issue with PostgreSQL (ver.15) partitions and code generator. 
- I had a regular table `transaction_unit` and there was a `TransactionUnitRecord extends UpdatableRecordImpl<...>` implementation generated. 
- Now I have migrated the table, so it is now partitioned and there is a `TransactionUnitRecord extends TableRecordImpl<...>` instead.

The difference is: before table migration, I had `.store()` method on the record objects, now it is gone. Is this a bug?

### jOOQ Version

3.19.13

### Database product and version

PostgreSQL 15.4 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit

### Java Version

openjdk 17.0.3 2022-04-19

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.5.0

**Comment by lukaseder** [comment]
Thanks for your report. Our integration tests include a table like this:

```sql
create table t_partitioned_pk (
  id int not null,
  d date not null,
  
  constraint pk_t_partitioned_pk primary key (id, d)
) partition by range (d);
```

And it produces this expected output:

```java
public class TPartitionedPkRecord extends UpdatableRecordImpl<TPartitionedPkRecord> { ... }
```

Can you please provide a complete reproducer? We have a template here:
https://github.com/jOOQ/jOOQ-mcve

But perhaps this is just a matter of a specific partition clause in PostgreSQL that behaves differently. In any case, I need to be able to reproduce the problem.

**Comment by witoldsz** [comment]
Wait a minute :bulb: 

I think the issue I have is that 2 tables had to get rid of the primary key! So this is not about the partitions, but about not having the pkey.

**Comment by lukaseder** [comment]
> That would conclude the bug report, I guess?

Looks like it, thanks for following up.
