### ISSUE TITLE
Regression in code generation for MariaDB where unsignedTypes=false is ignored

### ISSUE THREAD

**Issue by guss77** [jOOQ/jOOQ#17515]
### Expected behavior

Given a table schema such as
```
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
```

and having the generator configured with
```
<database>
	<name>org.jooq.meta.mariadb.MariaDBDatabase</name>
	<includes>.*</includes>
	<unsignedTypes>false</unsignedTypes>
</database>
```

I'd expect the POJO to look like:
```
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String name;
    private String email;
...
```

### Actual behavior

Instead, the generator create a POJO as thus
```
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private UInteger id;
    private String name;
    private String email;
...
```

### Steps to reproduce the problem

I'm using the vertx-jooq library, with it - and some custom converters and types, the generator configuration looks as thus:
```
<generator>
<name>io.cloudonix.lib.model.support.ExtendedClassicJDBCGuiceVertxGenerator</name>
<strategy>
	<name>io.cloudonix.lib.model.support.ExtendedVertxGeneratorStrategy</name>
</strategy>
<database>
	<name>org.jooq.meta.mariadb.MariaDBDatabase</name>
	<includes>.*</includes>
	<inputSchema>api_core</inputSchema>
	<outputSchema>api_core</outputSchema>
	<unsignedTypes>false</unsignedTypes>
	<forcedTypes>
		<!-- Convert tinyint to boolean -->
		<forcedType>
			<name>BOOLEAN</name>
			<includeTypes>(?i:TINYINT\(1\))</includeTypes>
		</forcedType>
		<!-- Convert varchar column with name 'profile' to a io.vertx.core.json.JsonObject -->
		<forcedType>
			<userType>io.vertx.core.json.JsonObject</userType>
			<converter>io.cloudonix.lib.model.support.JsonObjectLaxConverter</converter>
			<includeExpression>.*(?:profile|routes|interconnect_acl|parameters)</includeExpression>
			<nullability>ALL</nullability>
			<objectType>COLUMN</objectType>
		</forcedType>
		<forcedType>
			<userType>java.time.Instant</userType><!-- instead of java.sql.Timestamp -->
			<binding>io.cloudonix.lib.model.support.TimestampBinding</binding>
			<includeTypes>.*\b(timestamp|datetime)\b.*</includeTypes>
		</forcedType>
		<forcedType>
			<userType>java.util.UUID</userType>
			<includeTypes>BINARY\(16\)</includeTypes>
			<binding>io.cloudonix.lib.model.support.BinaryUUIDBinding</binding>
		</forcedType>
		<forcedType>
			<userType>io.cloudonix.model.time.PeriodDuration</userType>
			<converter>io.cloudonix.model.utilities.DurationBinding</converter>
			<includeTypes>VARCHAR</includeTypes>
			<includeExpression>.*(?:_duration|_period)</includeExpression>
			<nullability>ALL</nullability>
			<objectType>COLUMN</objectType>
		</forcedType>
	</forcedTypes>
</database>
<target>
	<packageName>io.cloudonix.model</packageName>
	<directory>${project.build.directory}/generated-sources/model</directory>
</target>
<generate>
	<interfaces>false</interfaces>
	<daos>true</daos>
	<fluentSetters>true</fluentSetters>
	<pojosEqualsAndHashCode>true</pojosEqualsAndHashCode>
	<javaTimeTypes>false</javaTimeTypes>
</generate>
</generator>
```

### jOOQ Version

3.19.14

### Database product and version

MariaDB 10.11

### Java Version

openjdk version "21.0.4" 2024-07-16

### JDBC / R2DBC driver name and version (include name if unofficial driver)

mariadb-java-client 2.7.12

**Comment by guss77** [comment]
The problem looks to be in the change introduced to solve issue #17135 . Specifically the code in [MySQLTableDefinition.getElements0()`](https://github.com/jOOQ/jOOQ/blob/fdbeea9977596bf69b3653855c4d18958e257500/jOOQ-meta/src/main/java/org/jooq/meta/mysql/MySQLTableDefinition.java#L147) generates a fully qualified type name with precision specified from the schema interogation, so the MySQL type `INT UNSIGNED` (no precision specified)` is converted into a data type specification of `"intunsigned(10)"`, then in the [`DefaultDataTypeDefinition` constructor](https://github.com/jOOQ/jOOQ/blob/fdbeea9977596bf69b3653855c4d18958e257500/jOOQ-meta/src/main/java/org/jooq/meta/DefaultDataTypeDefinition.java#L134) the check `typeName.toLowerCase().endsWith("unsigned")` fails and the "unsigned" part isn't being removed.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.16 (https://github.com/jOOQ/jOOQ/issues/17532)
- 3.18.23 (https://github.com/jOOQ/jOOQ/issues/17533)
- 3.17.32 (https://github.com/jOOQ/jOOQ/issues/17534)

**Comment by lukaseder** [comment]
The workaround is to use data type rewriting. I do think that perhaps this flag is no longer necessary anyway? It was introduced a long time before we had forced types (including data type rewriting, converters, etc.). I'll move to deprecating the flag starting from jOOQ 3.20:

- https://github.com/jOOQ/jOOQ/issues/17535

The alternative is documented in that issue.

**Comment by guss77** [comment]
> The workaround is to use data type rewriting. I do think that perhaps this flag is no longer necessary anyway? 

I'm using data type rewriting, but for specific cases (specific column names in specific tables). I'm not sure how would you use data type rewriting to replace all unsigned in numeric with a signed type? If you are removing this feature, I think you should post a full example code - in the documentation - on how to achieve the exact same behavior using data type rewriting.

**Comment by lukaseder** [comment]
> The alternative is documented in that issue.
