### ISSUE TITLE
Feedback about manual section "codegen-gradle"

### ISSUE THREAD

**Issue by LarsEckart** [jOOQ/jOOQ#17518]
### The documentation URL

https://www.jooq.org/doc/latest/manual/code-generation/codegen-gradle/

### Feedback

Dunno if this is feedback for your page, or rather the gradle plugin.

My little project is using SQLite. When using jooq code gen from CLI, I've the following setup:
```
root/
   libs/
     library.xml
     jooq-libs.jar
     items.db
   src/
      main/
build.gradle
items.db
```
As you can see, my db is originally in root, but i copied it into the libs folder and then was using following jdbc url `<url>jdbc:sqlite:items.db</url>` and then i get the following logs:

```
11:56:06 INFO Database parameters      
11:56:06 INFO ----------------------------------------------------------
11:56:06 INFO   dialect                : SQLITE
11:56:06 INFO   URL                    : jdbc:sqlite:items.db
11:56:06 INFO   target dir             : /Users/xxx/GitHub/checkout-kata/src/main/java
11:56:06 INFO   target package         : kata.jooq
```

Then I figured, I rather do it with a gradle plugin.
Here my config in `build.gradle`:
```
jooq {
    configuration {
        jdbc {
            driver = "org.sqlite.JDBC"
            url = "jdbc:sqlite:items.db"
```

I run `gradlew jooqCodegen -d` while in project root folder. I get the following output
```
2024-10-31T11:59:29.888+0200 [INFO] [org.jooq.codegen.AbstractGenerator]   dialect                : SQLITE
2024-10-31T11:59:29.888+0200 [INFO] [org.jooq.codegen.AbstractGenerator]   URL                    : jdbc:sqlite:items.db
2024-10-31T11:59:29.888+0200 [INFO] [org.jooq.codegen.AbstractGenerator]   target dir             : /Users/xxx/GitHub/checkout-kata/src/main/java
```
But then it doesn't find any tables. it also doesn't throw errors, I guess that's a SQLite feature that it just creates a file if it cannot find one and pretends everything is okay.
When I use a fully qualified path in `build.gradle` like `url = "jdbc:sqlite:/Users/xxx/GitHub/checkout-kata/items.db"` then it works. 
Executing `gradle properties` claims that `rootDir: /Users/xxx/GitHub/checkout-kata` so I'm bit confused why a relative path in `build.gradle` doesnt work.

**Comment by LarsEckart** [comment]
Ok, I seem to run into the same problem when using flyway gradle plugin.
```
flyway {
    url = 'jdbc:sqlite:checkout.db'
}
```
i ran this, run succeeded, but i didnt find any checkout.db file. i changed a migration file, ran flywayMigrate again, and it complains about "invalid checksum". So Somewhere it creates the db file, I just cannot find it. Not even from search in macos Finder :/ 

So I assume this isn't really an issue for you/jooq, and rather for me to learn something.

**Comment by LarsEckart** [comment]
There we go. My jdbc url was missing `:file`. Problem solved.

**Comment by lukaseder** [comment]
Thanks for your messages. The file is probably being created in the gradle execution directory, which is somewhere within `~/.gradle/caches` if memory serves. It's a weird default by Gradle and affects all usages of such local paths. jOOQ doesn't know anything about JDBC URL contents (and I doubt it should), so it currently doesn't propagate any configured paths to the drivers, or override the current directory (not sure if that's even possible in the JVM, without starting a new process, see https://stackoverflow.com/a/840229/521799)
