### ISSUE TITLE
AbstractRecord::compareTo doesn't produce correct ordering

### ISSUE THREAD

**Issue by bligny** [jOOQ/jOOQ#17580]
### Actual behavior

When upgrading to Jooq from 3.13.6 to 3.19.15 (yes I know, quite a big jump), we noticed that the results of the comparison of two `Record` is not the same as before.

See example hereunder

### Steps to reproduce the problem

Example: comparing (string, string) 2-tuples: 

**PREVIOUSLY**

```  
* Compare
+-----------+----+
|mt         |c   |
+-----------+----+
|op-tenant-1|LU  |
+-----------+----+
vs 
+-----------+----+
|mt         |c   |
+-----------+----+
|op-tenant-1|N   |
+-----------+----+
=> returns -2
```

**NOW**

```
* Compare
+-----------+----+
|mt         |c   |
+-----------+----+
|op-tenant-1|LU  |
+-----------+----+
vs 
+-----------+----+
|mt         |c   |
+-----------+----+
|op-tenant-1|N   |
+-----------+----+
=> returns 2363
```

Is this a wanted behaviour, knowing that `"LU".compareTo("N")` is negative ?

I see that Jooq is internally using `hashCode()` to perform the comparison:
```java
object1.hashCode() - object2.hashCode();
```

and indeed:
```java
System.out.println("LU".compareTo("N"));
System.out.println("LU".hashCode() - "N".hashCode());
```
are printing quite different results:
```
-2
2363
```

### jOOQ Version

3.19.15 (OpenSource)

### Database product and version

H2

### Java Version

21.0.4-amzn

### JDBC / R2DBC driver name and version (include name if unofficial driver)

H2 2.2.220

**Comment by lukaseder** [comment]
Thanks a lot for your report. Egh, this problem was introduced with this fix here:

- https://github.com/jOOQ/jOOQ/issues/10614

`hashCode()` is used for "uncomparable" object types (rather than throwing a `ClassCastException`). Obviously, this fix shouldn't have removed the otherwise reasonable ordering of `Comparable` data.

Will fix this right away. Our tests for this functionality amazingly didn't cover comparing by actual values, only comparing values with `null`, which still works. This is why the regression wasn't discovered, at the time.

**Comment by lukaseder** [comment]
This was really tough luck... There actually were simple record comparison tests but they either:

- Compared very simple data points where the `hashCode()` actually corresponded to the value, such as `Integer`
- Compared records without relying on the actual ordering, just the fact that the ordering is reproducible

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.16 (https://github.com/jOOQ/jOOQ/issues/17587)
- 3.18.23 (https://github.com/jOOQ/jOOQ/issues/17588)
- 3.17.32 (https://github.com/jOOQ/jOOQ/issues/17589)

**Comment by bligny** [comment]
@lukaseder 
any hint about the planning of next 3.20.0 release ?

**Comment by lukaseder** [comment]
> any hint about the planning of next 3.20.0 release ?

"Soon"
