### ISSUE TITLE
ORA-22848 thrown if a BLOB or CLOB field is used in comparison predicates

### ISSUE THREAD

**Issue by RenBrand** [jOOQ/jOOQ#17600]
### Expected behavior

The query operations `equal()`, `eq()`, `notEqual()` and `ne()` should work on CLOB columns in ORACLE too. They do work in other DB systems like postgreSQL and Microsoft SQL Server and they could be supported in ORACLE with the `dbms_lob.compare(clob, clob)` operation.

### Actual behavior

A condition which uses these kind of operations throws an ORA-22848 - Error with the message:

`SQL Error [22848] [99999]: ORA-22848: cannot use CLOB type as comparison key`

### Steps to reproduce the problem

* create a the following table
   ```SQL
   CREATE TABLE T2 (
     "V" CLOB NOT NULL
   );

  INSERT INTO T2 ( "V" ) VALUES ( 'anEntry' ), ('anotherEntry');
   ```
* generate the jOOQ metadata for this table
* execute the following statement
   ```Java
   ctx.fetchExists(T2, T2.V.eq( "anotherEntry" ) )
   ```

### jOOQ Version

jOOQ Professional Edition 3.19.15

### Database product and version

Oracle Database 23ai Free Release 23.0.0.0.0 - Develop, Learn, and Run for Free

### Java Version

openjdk version "21" 2023-09-19

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.oracle.database.jdbc:ojdbc11:23.5.0.24.07

**Comment by RenBrand** [comment]
I've created MCVE for this: https://github.com/RenBrand/jOOQ-mcve/tree/jOOQ-Issue-17600

**Comment by lukaseder** [comment]
Thanks for your suggestion. I don't see why not, we're already doing similar things for other data types in other RDBMS.

We should probably apply this emulation also for `ROW` comparisons, where possible. At least for `row(lob, x).eq(y, z)` style predicates.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.16 (https://github.com/jOOQ/jOOQ/issues/17605)
- 3.18.23 (https://github.com/jOOQ/jOOQ/issues/17606)
- 3.17.32 (https://github.com/jOOQ/jOOQ/issues/17607)

This likely affects also other dialects, which will be discovered once the integration tests have run through. I'll fix those as well in this context here.

The part about row predicates and also quantified comparison predicates will be addressed later through this separate issue:

- https://github.com/jOOQ/jOOQ/issues/17608

**Comment by RenBrand** [comment]
BTW, this is also a problem with the "IN" and "NOT IN" operators these could be simulated.

E.g.:
```SQL
SELECT * FROM "T2" WHERE "T2"."V" IN ( 'anEntry', 'anotherEntry' ); -- fails also with an ORA-22848

-- but it can be simulated with
SELECT *
  FROM "T2"
 WHERE (
	DBMS_LOB.COMPARE( "T2"."V", 'anEntry' ) = 0
	OR
	DBMS_LOB.COMPARE( "T2"."V", 'anotherEntry' ) = 0
 );
```

A "NOT IN" can also be simulated.
```SQL
SELECT * FROM "T2" WHERE "T2"."V" NOT IN ( 'anEntry', 'anotherEntry' ); -- fails also with an ORA-22848

-- but it can be simulated with
SELECT *
  FROM "T2"
 WHERE (
	DBMS_LOB.COMPARE( "T2"."V", 'anEntry' ) <> 0
	AND
	DBMS_LOB.COMPARE( "T2"."V", 'anotherEntry' ) <> 0
 );
```
I'm sure it's not super fast, but the queries want break with an ORA-22848. (@lukaseder: If thing this could be useful too and you want I can file a new feature/bug/issue for it too.)

**Comment by lukaseder** [comment]
>  (@lukaseder: If you thing this could be useful too and you want I can file a new feature/bug/issue for it too.)

Yes, please do open a new issue.
