### ISSUE TITLE
Meta.ddl() doesn't export ON DELETE clause for foreign keys in postgres

### ISSUE THREAD

**Issue by NikolayMetchev** [jOOQ/jOOQ#17616]
### Expected behavior

If you have a foreign key constraint with `ON DELETE CASCADE` for example when you call the Meta.ddl() method it will not print the cascade clause.
Ideally this clause will be printed for foreign keys.

```sql
ALTER TABLE
  table
ADD
  CONSTRAINT "table_other_table_id_fkey" FOREIGN KEY ("other_table_id") REFERENCES other_table ("id") ON DELETE CASCADE;
```

### Actual behavior

```sql
ALTER TABLE
  table
ADD
  CONSTRAINT "table_other_table_id_fkey" FOREIGN KEY ("other_table_id") REFERENCES other_table ("id");
```

### Steps to reproduce the problem

```sql
CREATE TABLE other_table (
  "id" uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY
);

CREATE TABLE table (
  id uuid NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
 other_table_id UUID NOT NULL references other_table (id) ON DELETE CASCADE
);
```

### jOOQ Version

3.19.15

### Database product and version

Postgres 14/16

### Java Version

17

### JDBC / R2DBC driver name and version (include name if unofficial driver)

rg.postgresql:postgresql:42.7.4

**Comment by lukaseder** [comment]
Thanks for your report. This is a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/9736
