### ISSUE TITLE
INSERT .. RETURNING TableRecords attached to wrong Configuration when AbstractDMLQuery::emulateOracleReturning is true

### ISSUE THREAD

**Issue by RenBrand** [jOOQ/jOOQ#17620]
### Expected behavior

Attached Records read during a transaction should be usable (= working `update()`, `store()` - methods) outside of the transaction which read the record. This would be the same behavior as seen in other DB systems (e.g.: PostgreSQL).

### Actual behavior

An attached record read inside of a transaction and modified afterwards outside of this transaction causes a "Connection already closed"-Exception during the call of the  `update()` or `store()` methods. This happens especially if a connection pool is in use.

The reason is a wrong `configuration` held by the returned records caused by `org.jooq.impl.AbstractDMLQuery.execute(ExecuteContext, ExecuteListener)` which emulates the returning-call of Oracle with a `procedureCall()` instead of a `preparedStatement()`. The row-creation code uses `ctx.configuration()` which returns the `derivedConfiguration` of the `DefaultExecutionContext` which holds the Proxy-Connection which is closed after the reading transaction ends.

Other simulations (e.g.: SQLite),  and also the `preparedStatement()` implementation use the `DefaultExecutionContext.originalConfiguration()` configuration to build their rows, causing the returned attached records to create a new transaction on `update()` or `store()` outside of the reading transaction.

### Steps to reproduce the problem

* Create the following table (important use lower case columns so the emulateOracleReturning-part is executed)
```SQL
CREATE TABLE T3(
   "id" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY(START with 1 INCREMENT by 1),
   "content" VARCHAR(256),
   
   CONSTRAINT pk_t3 PRIMARY KEY ("id")
);
```
* generate the jOOQ metadata
* add a connection pool to the test (e.g.: commonly used hikari-cache)
* execute the following example
```java
T3Record t3Rec = ctx.transactionResult(cfg -> {
  return cfg.dsl().insertInto( T3 )
                  .columns(T3.CONTENT)
                  .values("AValue")
                  .returning()
                  .fetchOne();
} );

t3Rec.setContent( "An updated value!" );
t3Rec.update();
```

### jOOQ Version

jOOQ Professional Edition 3.19.15

### Database product and version

Oracle Database 23ai Free Release 23.0.0.0.0 - Develop, Learn, and Run for Free

### Java Version

openjdk version "21" 2023-09-19

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.oracle.database.jdbc:ojdbc11:23.5.0.24.07

**Comment by lukaseder** [comment]
Thanks for your suggestion and analysis.

I can see that there's something fishy in the current behaviour, mostly that the record keeps being attached to the `Configuration` that went out of scope. We cannot prevent this entirely, as returning the record isn't the only way of propagating it outside of the transaction. You could also just put it into a `AtomicReference<T3Record>`, a `T3Record[]` or other data structure, or a field of the enclosing class scope. jOOQ has no way of detecting any such "scope leak."

Relying on the connection pool to indicate that the connection has gone stale is dangerous, it may or may not have been closed. So the current behaviour isn't well defined (though it is predictable). One way to address this is to put the transactional `Configuration` in a state where it no longer works. But that might be breaking things for many existing applications out there.

The other way is what you're suggesting, but that, too might break assumptions of applications out there, though less likely so.

**Comment by lukaseder** [comment]
The workaround is, of course, to attach the record to the outer `Configuration` explicitly:

```java
T3Record t3Rec = ctx.transactionResult(cfg -> { ... });

t3Rec.attach(ctx.configuration());
t3Rec.setContent("An updated value!");
t3Rec.update();
```

This can also be automated using a `TransactionListener`

**Comment by lukaseder** [comment]
> This can also be automated using a `TransactionListener`

My bad, `TransactionListener` cannot access the transaction result yet. I'll add this as a new feature:

- https://github.com/jOOQ/jOOQ/issues/17622

**Comment by RenBrand** [comment]
> Thanks for your suggestion and analysis.
> 
> I can see that there's something fishy in the current behaviour, mostly that the record keeps being attached to the `Configuration` that went out of scope. We cannot prevent this entirely, as returning the record isn't the only way of propagating it outside of the transaction. You could also just put it into a `AtomicReference<T3Record>`, a `T3Record[]` or other data structure, or a field of the enclosing class scope. jOOQ has no way of detecting any such "scope leak."
> 
> Relying on the connection pool to indicate that the connection has gone stale is dangerous, it may or may not have been closed. So the current behaviour isn't well defined (though it is predictable). One way to address this is to put the transactional `Configuration` in a state where it no longer works. But that might be breaking things for many existing applications out there.
> 
> The other way is what you're suggesting, but that, too might break assumptions of applications out there, though less likely so.

Thanks for the fast response and the workaround, but I didn't get the part with the "broken assumption of applications", all other DB-specific implementations already use the "originalConfiguration" (i.e.: SQLite - `AbstractDMLQuery V3.15.19 Line 1119`,  CUBRID - `AbstractDMLQuery V3.15.19 Line 1145` , PostgreSQL, MSSQL, ...) and the code is working there. I failed only because I switched over to ORACLE so what kind of assumption could others have here?

**Comment by lukaseder** [comment]
I see what you mean. I'll have another look. I may have wrongly assumed that attachment happens elsewhere in this case.

**Comment by lukaseder** [comment]
Looking into this now. A related, past issue is:

- https://github.com/jOOQ/jOOQ/issues/7569

**Comment by lukaseder** [comment]
It appears this happens only when `AbstractDMLQuery::emulateOracleReturning` is true, i.e. when any of the following is true:

- The estimated row count is > 1 (e.g. multi row inserts)
- We're returning the `ROWID` value
- We're returning expressions
- We're returning quoted identifiers (as is the case in your case)
- We're returning UDTs

**Comment by RenBrand** [comment]
That's also my impression and that's why I thought it is more a bug than a feature.

**Comment by lukaseder** [comment]
> That's also my impression and that's why I thought it is more a bug than a feature.

Ah yes, you already mentioned `emulateOracleReturning` so in your issue description.

**Comment by lukaseder** [comment]
The fix removes the issue from your MCVE.
