### ISSUE TITLE
Fixing the `Ambiguous key name` warning is harder than it should be

### ISSUE THREAD

**Issue by cies** [jOOQ/jOOQ#17641]
### Your question

After upgrading jOOQ to 3.19.x we had some trouble (mostly fixed by #17374). Now it works, but we still have a bunch (~10) warnings thrown at us during `generateJooq`.

The look like this:

```
WARNING Ambiguous key name       : The database object FK_ScheduleItem_ProgramItem__programItem_id generates an inbound key method name programitem which conflicts with the previously generated outbound key method name. Use a custom generator strategy to disambiguate the types. More information here:
 - https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/
 - https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/
```

So I read all the docs and tried to fix our custom strategy by adding "call" as the docs suggest:

```kotlin
  /** Despite the name this is also used when generating Kotlin code. */
  override fun getJavaMethodName(definition: Definition, mode: GeneratorStrategy.Mode): String {
    return "call" + super.getJavaMethodName(definition, mode)
  }
```

But this leads to the weird behavior that sometimes `call` is added 2 times! This because `DefaultGeneratorStrategy.getJavaMethodName(...)`  calls `getJavaMethodName(x, mode)` instead of `this.getJavaMethodName(x, mode)` in several places. Have a look here:

```java
    @Override
    public String getJavaMethodName(Definition definition, Mode mode) {
        // [#7148] If table A references table B only once, then B is the ideal name
        //         for the implicit JOIN path. Otherwise, fall back to the foreign key name
        if (getUseTableNameForUnambiguousFKs()) {
            if (definition instanceof ForeignKeyDefinition fk) {
                TableDefinition referenced = fk.getReferencedTable();

                if (fk.getTable().getForeignKeys(referenced).size() == 1)
                    return getJavaMethodName(referenced, mode);
            }
            else if (definition instanceof InverseForeignKeyDefinition fk) {
                TableDefinition referencing = fk.getReferencingTable();

                if (fk.getTable().getInverseForeignKeys(referencing).size() == 1)
                    return getJavaMethodName(referencing, mode);
            }
            else if (definition instanceof ManyToManyKeyDefinition k) {
                TableDefinition t1 = k.getForeignKey1().getReferencedTable();
                TableDefinition t2 = k.getForeignKey2().getReferencedTable();

                if (t1.getManyToManyKeys(t2).size() == 1)
                    return getJavaMethodName(t2, mode);
                else
                    return getJavaClassName0LC(k.getForeignKey2(), Mode.DEFAULT);
            }
        }

        return getJavaClassName0LC(definition, Mode.DEFAULT);
    }
```

I have a hunch that `getJavaMethodName(x, mode)` should be replaced with `this.getJavaMethodName(x, mode)` in these places in `DefaultGeneratorStrategy`, but I'm not sure.

Maybe the explanation on how to fix the warning can also be clearer, as I'm right now trying something like this to fix the warnings:

```kotlin
  /** Despite the name this is also used when generating Kotlin code. */
  override fun getJavaMethodName(definition: Definition, mode: GeneratorStrategy.Mode): String {
    when (definition) {
      is ManyToManyKeyDefinition -> {
        val t1: TableDefinition = definition.foreignKey1.referencedTable
        val t2: TableDefinition = definition.foreignKey2.referencedTable
        if (t1.getManyToManyKeys(t2).size == 1) return super.getJavaMethodName(t2, mode)
        return "call" + super.getJavaMethodName(definition, mode)
      }
    }
    return super.getJavaMethodName(definition, mode)-
  }
```

I copied over the content from the `is ManyToManyKeyDefinition` block from `DefaultGeneratorStrategy` to avoid some sort of recursion happening. Since `getJavaMethodName(...)` is called a lot, and I only want to change the name of the cases that result in warnings, it's pretty hard to figure out what actually needs to be done to prevent the warnings.

### jOOQ Version

3.19.15

### Database product and version

MySQL 8.0.33

### Java Version

21

### JDBC / R2DBC driver name and version (include name if unofficial driver)

mysql-connector-j 9.0.0

**Comment by lukaseder** [comment]
Thanks for your message.

While a complete reproducer (following our template: https://github.com/jOOQ/jOOQ-mcve) may not be necessary, I will certainly need at least a database schema that reproduces the issue, and your complete code generation configuration.

**Comment by cies** [comment]
@lukaseder I've created a PR for our MVCE here: https://github.com/jOOQ/jOOQ-mcve/pull/49

**Comment by lukaseder** [comment]
OK, so the reason why this is happening is simple: There are 2 paths from the `User` table to the `UserPreference` table:

- one-to-many from `User` to `UserPreference`
- many-to-many from `User` to `UserPreference_ScheduleFilterUser` to `UserPreference`

Since no custom strategy re-defines the method names, the latter cannot be generated and this warning is logged (in case you'd like to have the method).

Your generator strategy is not being applied in your MCVE: https://github.com/jOOQ/jOOQ-mcve/pull/49. I'm assuming you just forgot to add it in your jOOQ-codegen-gradle configuration?

```kotlin
strategy {
    name = "nl.stager.jooq.StagerGeneratorStrategy"
}
```

Once I add that, it works and once I change it to this:

```kotlin
      is ManyToManyKeyDefinition -> {
        val t1: TableDefinition = definition.foreignKey1.referencedTable
        val t2: TableDefinition = definition.foreignKey2.referencedTable
        return "call" + super.getJavaMethodName(definition, mode)
      }
```

... then it works and the warnings go away.

> I have a hunch that `getJavaMethodName(x, mode)` should be replaced with `this.getJavaMethodName(x, mode)` in these places in `DefaultGeneratorStrategy`, but I'm not sure.

`this` is implied in Java, that wouldn't change anything.

**Comment by lukaseder** [comment]
The warning itself could certainly offer more debug information:

- https://github.com/jOOQ/jOOQ/issues/17677

**Comment by lukaseder** [comment]
Regarding a fix here, I'm not certain if there's really a problem. I wonder if the schema example is really very common? Usually, relationships between tables are *either* one-to-many *or* many-to-many. The fact that you have both would hint at there being a good chance that you really want to rename the default method either:

- Using a strategy
- Or by turning off the default behaviour where we just generate a method based on the table name, and use the key name, instead (that would require a more strict schema naming design)

**Comment by lukaseder** [comment]
After fixing #17677, the warning will now look like this, and be more clear, I hope:

```
Ambiguous key name       : The many-to-many key (mcve.FK_UserPreference_ScheduleFilterUser__user_id, mcve.FK_UserPreference_ScheduleFilterUser__userPreference_id) generates an inbound key method name userpreference on table mcve.User which conflicts with the previously generated key method name for key mcve.FK_UserPreference__user_id. Use a custom generator strategy to disambiguate the types. More information here:
 - https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/
 - https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/
Ambiguous key name       : The many-to-many key (mcve.FK_UserPreference_ScheduleFilterUser__userPreference_id, mcve.FK_UserPreference_ScheduleFilterUser__user_id) generates an inbound key method name user on table mcve.UserPreference which conflicts with the previously generated key method name for key mcve.FK_UserPreference__user_id. Use a custom generator strategy to disambiguate the types. More information here:
 - https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy/
 - https://www.jooq.org/doc/latest/manual/code-generation/codegen-matcherstrategy/
```

**Comment by lukaseder** [comment]
Regarding the original claim, "fixing .. is harder than it should be," one option is to be able to turn off the generation of many-to-many paths entirely. You can turn off all to-many paths already, but not just the many-to-many ones, which are the actual problem here, and probably less useful in general. I've created a feature request for this:

- https://github.com/jOOQ/jOOQ/issues/17683

**Comment by cies** [comment]
@lukaseder Danke dir!

> Your generator strategy is not being applied in your MCVE

Oops overlooked that.

> After fixing https://github.com/jOOQ/jOOQ/issues/17677, the warning will now look like this, and be more clear, I hope:

Yes, much clearer. I spend quite a bit search for what I actually have to adjust in our custom generator. Maybe it could name the method (`getJavaMethodName`) that needs to be reimplemented and/or the case that needs to be handled (`definition instanceof ManyToManyKeyDefinition`). That would have saved me 2 hours of searching and trial-and-error things.

> The fact that you have both would hint at there being a good chance that you really want to rename the default method either (1) using a strategy, or (2) by turning off the default behaviour 

Yes. I've considered to turn it off, or ignore the warnings. The point here is that I have no clue how much we love this feature until we've actually played with it. So we need it, at least for a while, to experience the benefits it brings us.

**Comment by lukaseder** [comment]
> Maybe it could name the method (`getJavaMethodName`) that needs to be reimplemented and/or the case that needs to be handled (`definition instanceof ManyToManyKeyDefinition`).

Makes sense.
