### ISSUE TITLE
Accept CONSTRAINT_INDEX_ as a possible system index name prefix in H2

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#17652]
We recognise this pattern as H2 system index name: `^(?i:PRIMARY_KEY_|UK_INDEX_|FK_INDEX_).*$`

Given this schema:

```sql
create table t (id int primary key);
create table u (id int references t);
create table v (id int unique);

select index_name
from INFORMATION_SCHEMA.INDEXES;
```

It seems that we're missing the last two:

```
|INDEX_NAME         |
|-------------------|
|PRIMARY_KEY_5      |
|CONSTRAINT_INDEX_5 |
|CONSTRAINT_INDEX_56|
```

Not sure if this has changed in H2, but let's just add the prefix as well.

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.20.0
- 3.19.16 (https://github.com/jOOQ/jOOQ/issues/17653)
- 3.18.23 (https://github.com/jOOQ/jOOQ/issues/17654)
- 3.17.32 (https://github.com/jOOQ/jOOQ/issues/17655)

**Comment by lukaseder** [comment]
Another name that I've encountered just now: `CONSTRAINT_1F_INDEX_7`

**Comment by katzyn** [comment]
`CONSTRAINT` is not a mandatory part of generated index name. Such names are only used for indexes of unnamed constraints.

```SQL
CREATE TABLE TEST(A INT, B INT, CONSTRAINT ABCD UNIQUE(A));
SELECT INDEX_NAME FROM INFORMATION_SCHEMA.INDEXES;
> ABCD_INDEX_2
```

`INFORMATION_SCHEMA.INDEX.IS_GENERATED` is the only reliable solution.

**Comment by lukaseder** [comment]
> `INFORMATION_SCHEMA.INDEX.IS_GENERATED` is the only reliable solution.

Understood. But the meta data isn't available yet as `DatabaseMetaData::getIndexInfo` doesn't export it, so heuristics are necessary for the moment.
