### ISSUE TITLE
How to join more than 2 tables using JOOQ and use multiset_agg in a type-safe manner?

### ISSUE THREAD

**Issue by 18anandn** [jOOQ/jOOQ#17664]
### Your question

Suppose we have 3 tables `user`, `post` and `comment`. Each have a one-to-many relationship with the later.
The goal is to get all the posts by user and all the comments by posts. I want to achieve this using `multiset_agg` and not `multiset` and the number of rows in the user table is large. First, I thought of using a CTE but was not able to find a way to give type support to the result of a column derived using multiset_agg.

Query example:
```
val userId = field("u1", Long::class.java)
val userEmail = field("u2", String::class.java)
val userTable = name("userTable")
  .fields(userId.name, userEmail.name)
  .`as`(
    select(
      USER.USER_ID,
      USER.EMAIL,
    )
      .from(USER)
      .where(USER.USER_ID.`in`(request.userIdList))
  )

val postId = field("p1", Long::class.java)
val postUserId = field("p2", Long::class.java)
val postContent = field("p3", String::class.java)
val postComments = field("p4")
val postTable =
  name("postTable")
    .fields(
      postId.name,
      postUserId.name,
      postContent.name,
      postComments.name
    ).`as`(
      select(
        POST.POST_ID,
        POST.USER_ID,
        POST.CONTENT,
        multisetAgg(
          COMMENT.COMMENT_ID,
          COMMENT.CONTENT,
        )
      )
        .from(POST)
        .innerJoin(userTable)
        .on(userId.eq(POST.POST_ID))
        .leftJoin(COMMENT)
        .on(COMMENT.POST_ID.eq(POST.POST_ID))
        .groupBy(POST.POST_ID)
    )

val data = dslContext
  .with(userTable)
  .with(postTable)
  .select(
    userId,
    userEmail,
    multisetAgg(
      postId,
      postContent,
      postComments,
    )
  )
  .from(userTable)
  .leftJoin(postTable)
  .on(userId.eq(postUserId))
  .groupBy(userId, userEmail)
  .fetch()
```
In this case, how do I make `postComments` type-safe in the query result?

### jOOQ Version

3.16.2

### Database product and version

PostgreSQL

### Java Version

Java 21

**Comment by lukaseder** [comment]
Don't use multiple joins and aggregation, it won't work because of the cartesian products created by the joins. Follow the examples here:
https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/multiset-value-constructor/

**Comment by 18anandn** [comment]
Thank you @lukaseder for the quick response.

I wanted to avoid using `MULTISET` because of the problem mentioned in [this](https://blog.jooq.org/the-performance-of-various-to-many-nesting-algorithms/#:~:text=readable%20and%20maintainable.-,The%20conclusion%20is%3A,-For%20jOOQ%20users) blog. It's great for small datasets and also if the size of the result table on the left is not that large. So I wanted to use `MULTISET_AGG` in my case since the data size is large.

Also how does the above query give a cartesian product of tables? It does an explicit join on foreign keys.

**Comment by lukaseder** [comment]
> It's great for small datasets and also if the size of the result table on the left is not that large.

Have you measured performance? I personally doubt that comments-per-post will produce very large data sets, but that may just be an example to simplify your actual use-case?

> Also how does the above query give a cartesian product of tables? It does an explicit join on foreign keys.

I see, I thought you had 2 child tables, not 1 child table and 1 parent table. So, it's possible, of course.

So, regarding your actual question:

> In this case, how do I make `postComments` type-safe in the query result?

The simplest approach is to avoid unnecessary derived tables. Both your `userTable` and `postTable` derived tables seem unnecessary. Just think of this `MULTISET_AGG` query as the same thing as a query that aggregates just the `COUNT(*)` of comments per post/user.

**Comment by 18anandn** [comment]
I want to get is comments per post as well as posts per user.

Also doing the following worked for me. Is this the correct way to do it?
```
val postComments = field(select(multisetAgg(
  COMMENT.COMMENT_ID,
  COMMENT.CONTENT,
))).`as`("p4")
```

**Comment by lukaseder** [comment]
> Also doing the following worked for me. Is this the correct way to do it?

You cannot nest aggregate functions inside of aggregate functions.

**Comment by 18anandn** [comment]
Hmmm. In the end it generated the correct query for me. I checked it in the logs. The only reason that I had to the above is because I wanted type-safety.
Is there a right way to get type-safety in this case? I know `MULTISET` will solve this issue but it is a bit more expensive and slow compared to join in the size of tables that I am working on.
Also I gave the user-post-comment scenario just as an example and it is not what I am working on.

**Comment by lukaseder** [comment]
> Hmmm. In the end it generated the correct query for me. I checked it in the logs. The only reason that I had to the above is because I wanted type-safety.

Well, the question is turning a bit "dynamic." I don't know what exactly you're asking me when you're asking *Is this the correct way to do it." I checked your usage of `postComments` in the original question, and you're using it from within `multisetAgg()`, so I just pointed out what I saw.

> Is there a right way to get type-safety in this case?

I mean, I guess you're trying to get a hold of a `DataType<Result<...>>` instance in some way, and here (https://github.com/jOOQ/jOOQ/issues/17664#issuecomment-2497672308), you've just constructed one arbitrarily, and are now re-using it to coerce a data type onto an expression whose data type isn't known to the compiler. Is that correct?

There are many tricks to do this, but the best way is to always dereference a field directly from a derived table using `Table.field(Field<T>)`. If your `Field<T>` reference is an aliased expression (like you did), then that will try to dereference the alias from the table and just assume the types match. It's not "type safe," but it helps get a reference to the desired type.

**Comment by 18anandn** [comment]
@lukaseder Sorry for the confusion I created.

I just want a way to get the `postComment` field above in a type-safe manner. Also, the query is suprisingly generated correctly:
```
WITH "userTable"("u1", "u2")
     AS (SELECT "public"."user"."user_id",
                "public"."user"."email"
         FROM   "public"."user"
         WHERE  "public"."user"."user_id" IN ( ?, ? )),
     "postTable"("p1", "p2", "p3")
     AS (SELECT "public"."post"."post_id",
                "public"."post"."user_id",
                "public"."post"."content",
                Jsonb_agg(Jsonb_build_array("public"."comment"."comment_id",
                                    "public"."comment"."content"))
         FROM   "userTable"
                JOIN "public"."post"
                  ON "public"."post"."user_id" = u1
                LEFT OUTER JOIN "public"."comment"
                             ON
                "public"."comment"."post_id" =
                "public"."post"."post_id"
         GROUP  BY "public"."post"."post_id")
SELECT u1,
       u2,
       Jsonb_agg(Jsonb_build_array(p1, p2, "p3"))
FROM   "userTable"
       LEFT OUTER JOIN "postTable"
                    ON u1 = p2
GROUP  BY u1,
          u2 
```
>There are many tricks to do this, but the best way is to always dereference a field directly from a derived table using Table.field(Field<T>). If your Field<T> reference is an aliased expression (like you did), then that will try to dereference the alias from the table and just assume the types match. It's not "type safe," but it helps get a reference to the desired type.

Sorry. I don't understand what you mean by this. Can you please provide a small example?

**Comment by lukaseder** [comment]
> Sorry. I don't understand what you mean by this. Can you please provide a small example?

![image](https://github.com/user-attachments/assets/abd2de32-feb9-4e42-8cf7-169d0e877d2c)

😅

Well, here goes my continued guesswork as to what you're trying to ask me (and I might be barking up the wrong tree), but alas.

```java
Field<String> aliasedField = T.X.as("y");
Table<?> derivedTable = table(select(y).from(T));
Field<String> typeSafeDereferencedFieldFromDerivedTable = derivedTable.field(aliasedField);
```

I don't know if this helps or not.

**Comment by 18anandn** [comment]
Haha. I think I am not being clear here. 
>Field<String> aliasedField = T.X.as("y");
Table<?> derivedTable = table(select(y).from(T));

The problem is that this table `T` is derived table in my case. And the type of the aliased field in my example is something like this `Field<Result<Record2<Long, String>>>`. And this field comes from the `multiset_agg` used in the first derived table.

So the question is, if I have a multiset_agg column in one derived table, and I have to aggregate this column again in another derived table using multiset_agg without losing type-safety.

Sample schema:
```
[
   users: {
      {
         user_id: 1,
         user_email: a@b.com
         posts: [
            {
               post_id: 1,
               post_content: "example"
               comments: [
                  comment_id: 1,
                  comment_content: "sample"
               ]
            }
         ]
      }
   }
]
```

**Comment by lukaseder** [comment]
> The problem is that this table `T` is derived table in my case.

Does it really matter? Just "recurse" over my explanation... You'll keep dereferencing `Field` expressions from tables, irrespective of how you construct the table/field expression.

Anyway, I guess you already found the solution, since you're already doing this...
