### ISSUE TITLE
KotlinGenerator doesn't respect visibility modifier configuration for companion object and its contents

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#17714]
### Expected behavior

Generated code doesn't contain any warnings or the warnings are suppressed

### Actual behavior

Current generated code (cleaned for clarity):

```kotlin
@Suppress("UNCHECKED_CAST")
open class MessageRecord : UDTImpl<MessageRecordRecord>(DSL.name("message_record"), null, null, false) {
    public companion object { // <---- fails with Redundant visibility modifier.
        public val MESSAGE_RECORD: MessageRecord = MessageRecord() // <---- Redundant visibility modifier.
    }
}
```

```kotlin
@Suppress("UNCHECKED_CAST")
open class DefaultCatalog : CatalogImpl("") {
    companion object {
        public val DEFAULT_CATALOG: DefaultCatalog = DefaultCatalog()  // <---- fails with Redundant visibility modifier.
    }
}
```

```kotlin
@Suppress("UNCHECKED_CAST")
open class Pgmq : SchemaImpl("pgmq", DefaultCatalog.DEFAULT_CATALOG) {
    public companion object { // <---- fails with Redundant visibility modifier.
    }
}
```

```kotlin
@Suppress("UNCHECKED_CAST")
open class Archive : AbstractRoutine<Boolean>("archive", Pgmq.PGMQ, SQLDataType.BOOLEAN) {
    fun setMsgId(field: Field<Long?>): Unit { // <---- fails with Redundant return 'Unit' type. 
        setField(Archive.MSG_ID, field)
    }
}
```

```kotlin
fun create(
      configuration: Configuration
    , queueName: String?
): Unit { // <---- fails with Redundant return 'Unit' type. 
    val p = Create()
    p.setQueueName(queueName)

    p.execute(configuration)
}
```

The warnings triggered are `REDUNDANT_VISIBILITY_MODIFIER` and `REDUNDANT_RETURN_UNIT_TYPE`

### Steps to reproduce the problem

Use Kotlin 2.1.0 with the new [extraWarnings feature](https://kotlinlang.org/docs/whatsnew21.html#extra-compiler-checks)

### jOOQ Version

jOOQ OSS 3.19.15

### Database product and version

PostgreSQL 17.1

### Java Version

Eclipse Temurin 23.0.1 Win11 x64

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql:42.7.4

**Comment by lukaseder** [comment]
The visibility modifier warning is bugged, it still appears even with `-Xexplicit-api=strict` (which I find more important to test).

Nevertheless, we do have a visibility modifier setting in the code generator, and it appears it isn't respected for these companion objects, so let's fix that.

The `Unit` complaint is weird. I believe there used to be a warning as well with `-Xexplicit-api=strict` if you omitted that? Now the warning is inverse? I mean, this can obviously be changed but I feel we shouldn't spend too much time on such cosmetic things.

**Comment by lukaseder** [comment]
> hence my suggestion to suppress them

I don't think I will generate suppress warnings for such specific things. I'll never be done, and some user will find another linter and expect jOOQ's codegen to "behave."

Users can compile generated code ignoring these warnings, and compile their own code with any warnings settings. I have this discussion every now and then with Java developers who turn on `-Werror` on jOOQ-generated code. The answer is always the same: "Just turn it off"

> eliminates the warning as well.

That is... absurd :)

Anyway, I just checked why the `: Unit` token is being generated occasionally (but not everywhere). It's just because it's way easier in some cases to always generate the return type on a method, rather than creating separate templates for each case. Usually, this only affects cases where a fluent setter is possible. If the return type is always `Unit` (i.e. `void`), then it's usually not generated.

I will check the visibility cases, though. Again, we have a flag for this, and it's probably not being respected.

**Comment by lukaseder** [comment]
I just turned on the `-Wextra` flag to check what's being emitted, and indeed, we'll never be done. Things like *"Redundant modality modifier"* or *"Redundant call of conversion method"*, or again *"Redundant visibility modifier"* when `-Xexplicit-api=strict` is set (I'll report a bug about this, this is certainly wrong).

**Comment by lukaseder** [comment]
Here's the bug regarding redundant visibility modifiers and `-Xexplicit-api=strict`

https://youtrack.jetbrains.com/issue/KT-73642/Wextra-emits-Redundant-visibility-modifier-warnings-despite-Xexplicit-apistrict-being-set

**Comment by lukaseder** [comment]
I'll think about the `Unit` case again. While it is absurd (to me) that the block syntax would produce a warning whereas the expression syntax doesn't, the expression syntax seems to be leaner anyway. I'll see if we can replace it everywhere.

**Comment by lukaseder** [comment]
Nope, the places where this applies are too complex. In the other cases, we already generate the expression syntax.

**Comment by axelfontaine** [comment]
Just found out and verified that `@Suppress("warnings")` suppresses all warnings. How about just generating

```kotlin
@file:Suppress("warnings")
```

at the top of every file and be done with it?

**Comment by lukaseder** [comment]
Is it documented?

**Comment by lukaseder** [comment]
It does seem to work, and it would definitely be pragmatic, similar to what we're doing in the Java generated code. But I can't seem to find authoritative documentation around it, e.g.:

https://stackoverflow.com/q/40604446/521799

**Comment by lukaseder** [comment]
Anyway, I'll investigate this a bit further. Definitely a good solution if it does work. I've created this issue for it:

- https://github.com/jOOQ/jOOQ/issues/17727
