### ISSUE TITLE
Add native support for ANY_VALUE() in PostgreSQL 16+

### ISSUE THREAD

**Issue by superxiao** [jOOQ/jOOQ#17732]
### Use case

PostgreSQL 16 introduced the `any_value` aggregate. This matches the intent of `DSL.anyValue()`. Currently, jOOQ translates `DSL.anyValue()` to `MIN()` for PostgreSQL. With PostgreSQL 16+, jOOQ should use `any_value` instead.

Example
```java
DSL.anyValue(
    DSL.firstValue(EMPLOYEE_DETAIL.SALARY)
       .over(DSL.partitionBy(EMPLOYEE_DETAIL.DEPARTMENT_ID)
               .orderBy(EMPLOYEE_DETAIL.LAST_UPDATED.desc()))
)
```
For PostgreSQL 16+, this should translate to `any_value`. For older versions, it can fallback to `MIN()`.

Specifically `min` does not support `JSONB` columns.

### jOOQ Version

jOOQ opensource 3.19.15

### Database product and version

PostgreSQL 16+

### JDBC / R2DBC driver name and version (include name if unofficial driver)

org.postgresql:postgresql 42.7.4

**Comment by lukaseder** [comment]
Thanks for your suggestion. That makes sense. Though, I don't think your expression will work. You cannot nest a window function in an aggregate function.
