### ISSUE TITLE
Configuration of jOOQ Generator to generate getters and setters to access data through field name instead of the index

### ISSUE THREAD

**Issue by thaihocdang27** [jOOQ/jOOQ#17784]
### Your question

Is there a Configuration of jOOQ Generator to generate getters and setters to access data through field name instead of the index? I couldn't find any documentation.

By adding or dropping columns the index will change. in this moment the old or not yet deployed applications will access data through the wrong index.

Or are there reasons why we shouldn't access data through the field name?

### jOOQ Version

jOOQ codegen 3.19.8

### Database product and version

MySql 8.0.31-google

**Comment by lukaseder** [comment]
Thanks for your message.

There's no such option nor plan to introduce it. Lookups by name are currently `O(N)` in jOOQ, as opposed to `O(1)` lookups by index.

In any case, for most practical matters, a schema version mismatch between your database and jOOQ-generated code is irrelevant. You must be running into a very specific problem that can probably be avoided easily. I'll be happy to help if you share more details.
