### ISSUE TITLE
Regression when enabling <jpaAnnotation> for NOT NULL DEFAULT columns, which should continue to be marked as @Column(nullable = true)

### ISSUE THREAD

**Issue by robbytx** [jOOQ/jOOQ#17787]
### Expected behavior

Given the following:
```mysql
CREATE TABLE `test` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `column_with_default` varchar(255) NOT NULL DEFAULT 'some default',
  `column_no_default` varchar(255) NOT NULL,
  `column_nullable` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);
```

And the configuration:
```xml
<generator>
    <name>org.jooq.codegen.ScalaGenerator</name>
    <generate>
        <jpaAnnotations>true</jpaAnnotations>
        <nullableAnnotation>true</nullableAnnotation>
        <nullableAnnotationType>org.checkerframework.checker.nullness.qual.Nullable</nullableAnnotationType>
    </generate>
</generator>
```

Then version 3.16.22 generates `TestRecord.scala` with `@Column(..., nullable = false)` for each getter except `column_nullable` (as expected):
```scala
@Entity
@Table(
  name = "test",
  schema = "my_schema"
)
class TestRecord extends UpdatableRecordImpl[TestRecord](Test.TEST) with Record4[Long, String, String, String] {
  /**
   * Setter for <code>my_schema.test.id</code>.
   */
  def setId(value: Long): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>my_schema.test.id</code>.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id", nullable = false)
  def getId: Long = get(0).asInstanceOf[Long]

  /**
   * Setter for <code>my_schema.test.column_with_default</code>.
   */
  def setColumnWithDefault(value: String): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>my_schema.test.column_with_default</code>.
   */
  @Column(name = "column_with_default", nullable = false, length = 255)
  def getColumnWithDefault: String = get(1).asInstanceOf[String]

  /**
   * Setter for <code>my_schema.test.column_no_default</code>.
   */
  def setColumnNoDefault(value: String): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>my_schema.test.column_no_default</code>.
   */
  @Column(name = "column_no_default", nullable = false, length = 255)
  def getColumnNoDefault: String = get(2).asInstanceOf[String]

  /**
   * Setter for <code>my_schema.test.column_nullable</code>.
   */
  def setColumnNullable(value: String): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>my_schema.test.column_nullable</code>.
   */
  @Column(name = "column_nullable", length = 255)
  @Nullable
  def getColumnNullable: String = get(3).asInstanceOf[String]

  ...
}
```

### Actual behavior

Upon upgrading to 3.19.16, then only `@Column(name = "column_no_default",` still has `nullable = false`. (`@Column(name = "id")` and `@Column(name = "column_with_default", length = 255)` do not, and therefore default to `nullable = true`.)

```scala
@Entity
@Table(
  name = "test",
  schema = "my_schema"
)
class TestRecord extends UpdatableRecordImpl[TestRecord](Test.TEST) {
 
  /**
   * Setter for <code>my_schema.test.id</code>.
   */
  def setId(value: Long): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>my_schema.test.id</code>.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "id")
  @Nullable
  def getId: Long = get(0).asInstanceOf[Long]

  /**
   * Setter for <code>my_schema.test.column_with_default</code>.
   */
  def setColumnWithDefault(value: String): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>my_schema.test.column_with_default</code>.
   */
  @Column(name = "column_with_default", length = 255)
  @Nullable
  def getColumnWithDefault: String = get(1).asInstanceOf[String]

  /**
   * Setter for <code>my_schema.test.column_no_default</code>.
   */
  def setColumnNoDefault(value: String): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>my_schema.test.column_no_default</code>.
   */
  @Column(name = "column_no_default", nullable = false, length = 255)
  def getColumnNoDefault: String = get(2).asInstanceOf[String]

  /**
   * Setter for <code>my_schema.test.column_nullable</code>.
   */
  def setColumnNullable(value: String): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>my_schema.test.column_nullable</code>.
   */
  @Column(name = "column_nullable", length = 255)
  @Nullable
  def getColumnNullable: String = get(3).asInstanceOf[String]

  ...
}
```

This change appears to have originated from [b26a5c60c86 (JavaGenerator.java:8038)](https://github.com/jOOQ/jOOQ/commit/b26a5c60c86#diff-e4e540ae36541b656b055ae8e2064243e0366dab891f27aa7676ee10ccdf2413R8038) where the condition was changed from simply checking the column's nullability to the more expansive `effectivelyNotNull` condition.

Since I know that the behavior surrounding nullability annotations & types have been undergoing various discussions, our project has been intentionally using the JPA `@Column` annotation (via reflection) to understand whether the underlying column that backs the property accepts null value, which is useful in a variety of contexts such as generating documentations & API specifications.

Per the [JPA specification](https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0#a14330), the `nullable` attribute for `@Column` annotations should indicate:
> Whether the database column is nullable.

It's not clear to me why this attribute should be true for columns having a default value (or a special IDENTITY type), since these are typically indicated in other ways (via `columnDefinition`, field initializers, Hibernate's `@ColumnDefault`).

Therefore, I believe that the correct value for this annotation should be based strictly on whether the column accepts null values (as before), and I am requesting that the original behavior be restored.  Without this, the process of determining definitively whether a column is nullable requires additional reflection to:

1. Determine the Table backing the record by either:
  * Instantiating the record (only possible if there is a default constructor) and then calling `record.getTable()`, or
  * Using the `@Table` annotation to resolve the table via the `DefaultCatalog`.
2. Use `table.field(name).getDataType.nullable()` to obtain the true `nullable` property.

Although possible, this requires extra code specific to jOOQ, rather than relying purely on the JPA specification, reducing the available tooling that can be used.

---
P.S. In addition to losing `nullable=false`, the affected getters also appear to have surprisingly gained an `@Nullable` annotation, but fortunately this behavior appears to have already been addressed in #16002.

### Steps to reproduce the problem

See **Expected Behavior** above for the DDL and code generation configuration.

### jOOQ Version

jOOQ Open Source 3.19.16

### Database product and version

mysql  Ver 8.0.40 for macos14.7 on arm64 (Homebrew)

### Java Version

openjdk version "21.0.5" 2024-10-15 LTS

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.mysql:mysql-connector-j:8.4.0

**Comment by lukaseder** [comment]
Thanks for your report. I agree the JPA annotation should reflect the type as it is in the database, and as it is generated in the `TableImpl` class, not the POJO attribute type, which is nullable because of the `DEFAULT` value.

> P.S. In addition to losing `nullable=false`, the affected getters also appear to have surprisingly gained an `@Nullable` annotation,

It's not surprising, it's very logical, and has been explained throughout related issues.
