### ISSUE TITLE
Issue with Aliasing in jOOQ returning Clause when Mapping to Kotlin data class

### ISSUE THREAD

**Issue by keemjoonsung** [jOOQ/jOOQ#17819]
### Your question

I'm using jOOQ to map query results to a Kotlin data class. Here's the structure of my data class:

```
data class DBUser(
    private val pk: Long,
    private val identifier: String,
    private val password: String,
    private val role: String,
    private val withdrawn: Boolean,
    private val createdAt: LocalDateTime,
    private val updatedAt: LocalDateTime,
)
```
In my MySQL 8.2 database, all fields are stored in snake_case (e.g., created_at, updated_at).

To map the query result to DBUser, I wrote the following code:

```
private fun insertOrUpdateUser(user: BaseUser): DBUser {
    return dsl
        .insertInto(USER)
        .set(USER.ID, user.pk.getOriginal())
        .set(USER.IDENTIFIER, user.identifier.value)
        .set(USER.PASSWORD, user.password.value)
        .set(USER.ROLE, user.role.name)
        .set(USER.WITHDRAWN, false)
        .set(USER.CREATED_AT, user.audit.createdAt)
        .set(USER.UPDATED_AT, user.audit.updatedAt)
        .onDuplicateKeyUpdate()
        .set(USER.IDENTIFIER, user.identifier.value)
        .set(USER.PASSWORD, user.password.value)
        .set(USER.ROLE, user.role.name)
        .set(USER.WITHDRAWN, user.withdrawn)
        .set(USER.UPDATED_AT, user.audit.updatedAt)
        .returning(
            USER.ID.`as`("pk"),
            USER.IDENTIFIER.`as`("identifier"),
            USER.PASSWORD.`as`("password"),
            USER.ROLE.`as`("role"),
            USER.WITHDRAWN.`as`("withdrawn"),
            USER.CREATED_AT.`as`("createdAt"),
            USER.UPDATED_AT.`as`("updatedAt"),
        )
        .fetchInto(DBUser::class.java)
        .first()
}
```
Since my DBUser fields use camelCase naming (e.g., createdAt, updatedAt), I used as("createdAt") for the aliases in the returning clause to match the class fields. However, the mapping failed with a NullPointerException.

When I changed the aliases in the returning clause to use snake_case (e.g., as("created_at")), it worked perfectly:

```
.returning(
    USER.CREATED_AT.`as`("created_at"),
    USER.UPDATED_AT.`as`("updated_at"),
)
```
This successfully mapped the fields to DBUser.

My Question
Why does using aliases that match the actual Kotlin class field names (e.g., createdAt) fail, while using snake_case aliases (e.g., created_at) works?

I understand that jOOQ might be applying some automatic conversion from snake_case to camelCase during the mapping process, but in this case, I explicitly used the exact field name from the class in the alias, and it still failed.

What happens internally in jOOQ during the mapping process with fetchInto and aliases in the returning clause? Are there any specific limitations or considerations when mapping to Kotlin data class objects?

Let me know if there’s anything else I should clarify.

### jOOQ Version

JOOQ Opensource Edition 3.19.16

### Database product and version

MySQL 8.2

### Java Version

openjdk version "17.0.10" 2024-01-16

### JDBC / R2DBC driver name and version (include name if unofficial driver)

com.mysql:mysql-connector-j:8.2

**Comment by lukaseder** [comment]
Thanks for your message.

See the Javadoc of the method:
https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/InsertReturningStep.html#returning(org.jooq.SelectFieldOrAsterisk...)
