### ISSUE TITLE
Add Setting to always fetch all record data after INSERT or UPDATE

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1859]
Properly dealing with `DEFAULT` values was suggested in this thread here:
https://groups.google.com/d/topic/jooq-user/_cp2-mrtZ7k/discussion

Apart from `DEFAULT` values, trigger-generated values are currently not reflected in a jOOQ `UpdatableRecord` after a `store()`, `insert()`, or `update()` operation. The only thing fetched back from the database is the `IDENTITY` value after an `INSERT`.

This was also requested on this thread here:
http://stackoverflow.com/q/18276421/521799

And in this issue here #2697

**Comment by mumutu** [comment]
how to make the `configuration.data(DATA_OMIT_RETURNING_CLAUSE)` TRUE ??
 it seems there is no way to prevent the query behavior even there is only `IDENTITY` key exist

**Comment by lukaseder** [comment]
@mumutu: Thank you for your comment. The `DATA_OMIT_RETURNING_CLAUSE` is an internal flag that cannot be modified through public API.

If you believe to have found a bug, would you mind creating a new issue here on github (https://github.com/jOOQ/jOOQ/issues/new) showing what isn't working correctly for you?
