### ISSUE TITLE
Deprecate ConditionProvider, OrderProvider, LockProvider types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1881]
These types do not offer much value by themselves. In a later stage, their methods will be unified into `SimpleSelectQuery` as `SelectQuery` will extend the former (#1880)

**Comment by viveleroi** [comment]
Is there a replacement for this yet? I add the same conditions to `SelectQuery` and `DeleteQuery` builders so I have a shared method but it seemed like `ConditionProvider` was the most appropriate argument but it's marked for removal so naturally my IDE/gradle warns me. Looking up the issue, I see it's a decade old so I'm not sure if I'm missing something.

**Comment by lukaseder** [comment]
Yes, the model API will replace these features, but it's still experimental:
https://www.jooq.org/doc/latest/manual/sql-building/model-api

**Comment by viveleroi** [comment]
Can you point me to which piece would replace the `ConditionProvider`, I'm looking through and there's quite a bit. A search only shows the query/ConditionProvider classes I already know of. 

My code essentially is a shared function that does this:

```java
protected void addConditions(ConditionProvider queryBuilder) {
    if (this.location() != null) {
        queryBuilder.addConditions(EXAMPLE_TABLE.X.equal(this.location().x()));
    }
    ...
```

**Comment by viveleroi** [comment]
Actually, I just modified my method to return a `List<Condition>` that I can add directly to the query builder. No need to pass JOOQ stuff around.

**Comment by lukaseder** [comment]
Sure. There's usually no good reason to use those mutating API methods, which is why they were deprecated in the first place.
