### ISSUE TITLE
Support INSERT onDuplicateKeyIgnore() for H2

### ISSUE THREAD

**Issue by cowwoc** [jOOQ/jOOQ#19]
JOOQ doesn't support insert.onDuplicateKeyIgnore() for H2, nor does it allow INSERT ... WHERE NOT EXISTS as mentioned here: http://stackoverflow.com/questions/6736518/h2-java-insert-ignore-allow-exception

We need a way to insert a new row, unless it already exists (this is the counterpart to MERGE support).

**Comment by slayful** [comment]
Hi there!
I don't believe this issue finally got addressed by the referenced tickets.
https://github.com/jOOQ/jOOQ/commit/46074ed30b7fe8ab501b64f4f0272e543910ed79 seems to be addressing only sqlite:

I've tried latest H2 and jOOQ versions with H2 compliant mode without any any luck.

Trying to run with SQLITE compliant mode gets me this: 
```
! org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT OR[*] IGNORE INTO <db-name>.<table-name> (<columns>) VALUES (?, ?, ?) "; expected "INTO"; SQL statement:
```

Any plans for addressing this issue for H2? We're using H2 for integration tests and this is basically all we're missing to test everything conveniently. :)

**Comment by lukaseder** [comment]
Hi @slayful, this is a very old issue, and I'm sure it was implemented as good as possible at the time, but certainly, you may have run into some other problem. Would you mind creating a new issue with:

- Some example code that you wrote
- The expected behaviour
- The actual behaviour

Thanks
