### ISSUE TITLE
Add support for views expressed in jOOQ

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1969]
It should be possible to register ...
- plain SQL
- jOOQ client code

... as "views" that are made accessible through code generation. Such views would then generate `org.jooq.Table` objects with related `org.jooq.Field` column objects. An example:

``` java
select(V.COL1, V.COL2).from(V).where(V.COL3.equal(1));
```

... where `V` is a generated object, generated from either:

``` java
select(A.X1.as("col1"), A.X2.as("col2"), A.X3.as("col3")).from(A).where(...)
```

or from:

``` java
String sql = "SELECT a.x1 col1, a.x2 col2, a.x3 col3 FROM a WHERE ...";
```

Read more about the original idea here:
- https://groups.google.com/d/topic/jooq-user/FhDh-kkdxhw/discussion
- https://groups.google.com/d/msg/jooq-user/7hfDlmEwfQI/pblBBG4EBwAJ

**Comment by thiloplanz** [comment]
> The advantage of those views (over the feature discussed in #3796) is the fact that you can reference columns by name, rather than by index - which is much more natural and readable.

Today I hit the 22-columns limit for typesafe Records for the first time. In addition to it getting really tedious to keep track of columns by index, a view would presumably also remain typesafe for as many columns as you want ( or your application forces you to have )

**Comment by lukaseder** [comment]
> Today I hit the 22-columns limit for typesafe Records for the first time.

It was inevitable :)

> In addition to it getting really tedious to keep track of columns by index

Yes, true record types (named-attribute tuples) would be awesome in Java. Unfortunately, it is currently not possible.

> a view would presumably also remain typesafe for as many columns as you want ( or your application forces you to have )

No, the generic type safety that is used in unions for instance, is always index-based. While it would be possible to have views with formal column declarations, there is actually no formal connection between the column and the view from a Java parser perspective.

Of course, I'm not quite sure what use-case you had in mind when you thought that these views might be a solution for it...

**Comment by thiloplanz** [comment]
> a view would presumably also remain typesafe for as many columns as you want 

All I meant to say is that with the view, you could refer to columns by name (where name is a compile-time symbol pointing to a typed column definition), just as you can for tables (or database views) right now, even if the table has 321 columns. On the "receiving end",  you would not be dealing with `Select<Record21<T1,T2......>` anymore, but have a `Select<FooViewRecord>`.

**Comment by lukaseder** [comment]
I see, I guess I was mislead by the comparison with the index-based type safety. Yes, such views would lead to being able to reference columns by name. However, right now, we're not quite sure how to implement them in a very convenient way. Writing them manually seems a bit tedious...

**Comment by lukaseder** [comment]
A workaround has been kindly contributed in #7115 by @victorbr

**Comment by lukaseder** [comment]
This feature would be very useful to implement #8012

**Comment by lukaseder** [comment]
Looking into this again in the context of https://github.com/jOOQ/jOOQ/issues/11054, a feature that will ship with jOOQ 3.15

**Comment by lukaseder** [comment]
Related feature from jOOQ 3.17: Client side computed columns (virtual and stored): https://github.com/jOOQ/jOOQ/issues/9879

**Comment by lukaseder** [comment]
This feature has already been prototyped (but not documented) as "synthetic views": https://github.com/jOOQ/jOOQ/issues/11054. I might have another look at the implementation.

Closing this as a duplicate of https://github.com/jOOQ/jOOQ/issues/11054.
