### ISSUE TITLE
Add support for the EXASOL database

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#1985]
It appears that a free to use test version can be used in Docker, for our development purposes:

- https://www.exasol.com/product-overview/community-edition-download/
- https://github.com/exasol/docker-db
- https://github.com/exasol/exasol-testcontainers

Syntax info:

- https://docs.exasol.com/sql/select.htm

They have their own simple SQL builder, which is a start:

- https://github.com/exasol/sql-statement-builder

### Specific points of interest

**Workaround in jOOQ**

- [x] The `VALUES()` constructor does not support bind variables (e.g. `VALUES (?), (?)`) (workaround by inlining bind values)
- [x] `DELETE` statements don't support parameters in `WHERE` clause, unless for trivial predicates: https://www.exasol.com/support/browse/EXASOL-875
- [x] `MERGE` isn't as powerful as in other RDBMS. Our `INSERT .. ON DUPLICATE KEY UPDATE` emulation should be changed: https://github.com/jOOQ/jOOQ/issues/11880
- [x] The JDBC driver can't handle `NULL` values of type `-6` (`TINYINT`) as bind values

**Not addressed yet**

- Self-referencing foreign keys can't be created with `CREATE TABLE`, only with `ALTER TABLE`
- `CREATE SCHEMA` implies `OPEN SCHEMA`, which breaks a lot of integration test assumptions. Does it break client code as well?
- `UPDATE .. SET x = (SELECT)` doesn't work with correlated subqueries. The MySQL hack from #6583 doesn't work, because correlated subqueries can't be correlated from within a derived table in the subquery.
- JDBC batch statements with single SQL strings and multiple bind variable sets are not yet supported

**Not implemented**

- Indexes can be created with the `ENFORCE` command, but without a name. However, Exasol claims that users should never need to create indexes manually, so we won't implement this.

**Moved to other issues**

- Missing data types will be supported (eventually) via a new data type registry: https://github.com/jOOQ/jOOQ/issues/5713
  - There is no binary data type.
  - There is no `TIME` data type.

### Bugs encountered (let's wait for a fix in Exasol)

**Workaround in jOOQ**

- [x] Internal error when using bind variables on predicates with CONNECT BY and LEVEL from JDBC https://community.exasol.com/t5/discussion-forum/internal-error-when-using-bind-variables-on-predicates-with/td-p/3416 (workaround by inlining bind values)
- [x] Set operations don't correspond to the documented syntax. We'll apply the usual workarounds with derived tables: https://community.exasol.com/t5/discussion-forum/exasol-doesn-t-implement-standards-compliant-e071-01-etc-set/m-p/3540#M812

**Waiting for an Exasol fix**

- [x] Wrong calculation of PERCENTILE_DISC if the same query contains PERCENTILE_CONT as well https://community.exasol.com/t5/discussion-forum/wrong-calculation-of-percentile-disc-if-the-same-query-contains/td-p/3397
- [x] Wrong implementation of the NOT IN predicate in the presence of nulls https://community.exasol.com/t5/discussion-forum/wrong-implementation-of-the-not-in-predicate-in-the-presence-of/td-p/3412
- [x] Wrong results for CONNECT BY NOCYCLE https://community.exasol.com/t5/discussion-forum/wrong-results-for-connect-by-nocycle/m-p/3418#M785
- [x] Internal server error when using LEVEL in START WITH https://community.exasol.com/t5/discussion-forum/internal-server-error-when-using-level-in-start-with/m-p/3419#M786
- [x] Invalid select-list in subselect https://community.exasol.com/t5/discussion-forum/invalid-select-list-in-subselect/m-p/3524#M805 (this issue prevents most of our implicit join path expressions from working)
- [x] The `LISTAGG` window function unfortunately uses the `<within group specification>` as a window order specification: https://docs.exasol.com/sql_references/functions/alphabeticallistfunctions/listagg.htm. We won't work around this, as it seems to work as designed.
- [x] `VALUES()` constructor can't handle `NULL` values of type `DATE` or `TIMESTAMP`. Other types are fine: https://community.exasol.com/t5/discussion-forum/unallowed-type-combination-in-tupel-error-when-using-date-type/m-p/3547#M816
- [x] `LAST_VALUE (x) OVER ()` (empty window specification) produces wrong results: https://community.exasol.com/t5/discussion-forum/first-value-and-last-value-with-empty-over-shouldn-t-produce/m-p/4764#M1120
- [x] `BETWEEN SYMMETRIC` edge case: https://community.exasol.com/t5/discussion-forum/wrong-result-in-query-with-various-between-and-between-symmetric/td-p/4788

**Comment by cith** [comment]
Hi Lukas,

is this still on the road map? 

We are planning to query a Exasol database from our application in the near future. The default Dialect seems not to work with Exasol without further configurations/tweaks (before we only had DB2/H2 to query).

Or is there a similar dialect which could be used or tweaks for the default dialect?

Thanks in advance.

Greetings Christian

**Comment by lukaseder** [comment]
Thank you very much for your message, @cith. We do have it on our long term roadmap, but so far, in 11 years, you've been the first to request an integration :)

We're mostly looking at this ranking here to prioritise supporting new dialects: https://db-engines.com/en/ranking

There are a few dialects that have a higher priority, such as BigQuery, but we're certainly open to discussing Exasol support again.

> Or is there a similar dialect which could be used or tweaks for the default dialect?

I currently cannot tell without running the integration tests

> Edit: Ok, with a bit of adjusting of the query is was possible with the default Dialect.

The devil is in the details. Simple selects are easy to get to work, but then, there are a lot of edge cases that work differently in all databases, such as:

- Is a dual table required?
- Is a dual table required when there are where/group by/having clauses?
- Can unions be nested?
- Can joins be nested?

And then, there are all the built in functions that need translation. So, getting something to work is the easy part. Guaranteeing it will work is the hard part.

What's your use case, using Exasol?

**Comment by cith** [comment]
Thank you for your detailed answer and explanation.

Basically spoken our use case is to execute user-written (analytical) sql and also generated sql based on given metadata. For the latter we use JooQ to build the queries.

For now the queries which are execute are possible with Jooq against the Exasol, as said with some adjustments.

**Comment by lukaseder** [comment]
Thanks. Well, we can reconsider the prioritisation, but I cannot make any promises right now, I'm afraid.

**Comment by cith** [comment]
Thanks for taking it in consideration.

**Comment by lukaseder** [comment]
Moving this back to 3.15.0 for re-consideration

**Comment by lukaseder** [comment]
A customer has sponsored the re-prioritisation of this integration, meaning this will ship in jOOQ 3.15.0 by Q2 2021

**Comment by redcatbear** [comment]
A couple of (potential) answers to some of your open points:
* No binary type: this is owed to the fact that Exasol is intended solely for analytical purposes. If required the established way is to Base64-encode binary into `VARCHAR`. Since there is a 2 million character limit on `VARCHAR` columns and Base64 has a 33% overhead, this is not suitable for mass binary data though.
* Exasol indeed has no dedicated time type. The two obvious workarounds are either using timestamps with a fixed date that is ignored (default is 01.01.0001 as far as I remember) or `VARCHAR`.
* While it is possible to create indices by hand, this is not recommended. Exasol automatically maintains indices (https://docs.exasol.com/performance/best_practices.htm). That being said:
     ```sql
     ENFORCE [LOCAL|GLOBAL] INDEX ON <table> ( <column-list> );
     DROP [LOCAL|GLOBAL] INDEX ON <table> ( <column-list> );
     ```
* ```CREATE TABLE``` works without ```OPEN SCHEMA``` if you prefix the table name with the schema name and a dot.

**Comment by lukaseder** [comment]
Thanks a lot, @redcatbear. I greatly appreciate this!

- The binary/time type discussion is not really Exasol specific in this case. Exasol is just a reminder for jOOQ to offer more standardised behaviour in this area, and more easily pluggable replacements for missing data types. For example, Oracle also doesn't have a true `TIME` type (although it exists in some syntaxes, e.g. `CAST`), and we currently emulate it by truncating `TIMESTAMP` to epoch date `1970-01-01`, which is quite arbitrary.
- Given that Exasol indexes cannot be named (?), maintaining them like that is currently not possible with jOOQ (we don't support a structural drop by referencing column lists yet as I don't think many other RDBMS support such a syntax. I'm only aware of Oracle allowing dropping `UNIQUE` constraints structurally rather than nominally). I've noticed the best practices as well, so I think we simply won't support these syntaxes for now.
- Sure, there are workarounds for the implicit `OPEN SCHEMA` command, but since we're not in control of user-defined DDL statements created with jOOQ, the table may not be qualified. So, I wonder if perhaps, there could be a compatibility mode that automatically opens the previously opened schema whenever someone creates a schema with jOOQ. But let's wait until actual customers run into this.

**Comment by redcatbear** [comment]
Not integrating the index manipulation should be fine. Our notion is that you can't really do it better by hand then the database does it automatically, so it is pointless in pretty much every case.

**Comment by redcatbear** [comment]
When it comes to schema opening, I would suggest to rather throw an error with a proper mitigation message than to use any statefull magic. In my experience those automatisms always come back to haunt you at some point.

**Comment by redcatbear** [comment]
By the way. We have a SQL statement builder (https://github.com/exasol/sql-statement-builder) with public code. Maybe there are some things there that could help you figuring out your solutions.

**Comment by lukaseder** [comment]
> Not integrating the index manipulation should be fine. Our notion is that you can't really do it better by hand then the database does it automatically, so it is pointless in pretty much every case.

I've always wondered why we still have to do this in most RDBMS :)

> When it comes to schema opening, I would suggest to rather throw an error with a proper mitigation message than to use any statefull magic. In my experience those automatisms always come back to haunt you at some point.

Well, the haunting automatism in question is the auto-switch to the just-created schema, which I've never seen in any previous RDBMS. Does it haunt you yet? ;)

The use-case of such a flag in jOOQ would be to standardise over all RDBMS. The expected behaviour in a vendor agnostic setup that supports 5-10 RDBMS would be to not switch any session flags based on not strictly related statements.

On the other hand, it is indeed not unwise to always fully qualify identifiers, so chances are, users will work around this on their own.

> By the way. We have a SQL statement builder (https://github.com/exasol/sql-statement-builder) with public code. Maybe there are some things there that could help you figuring out your solutions.

Yes, I've seen this and I was going to get in touch. What kinds of specific help did you think of?

**Comment by redcatbear** [comment]
> On the other hand, it is indeed not unwise to always fully qualify identifiers, so chances are, users will work around this on their own.
Exactly. Not using fully qualified identifiers is a convenience thing for interactive querying. E.g. when you do a quick session in your favourite SQL client. In code the best practice should be using fully-qualified (and of course quoted) identifiers.
> What kinds of specific help did you think of?
Maybe about creating non-SQL-standard (read Exasol-specific) constructs. On the other hand the SSB probably does not contain a lot of those yet, except scripting statements.

**Comment by lukaseder** [comment]
> In code the best practice should be using fully-qualified (and of course quoted) identifiers.

I'm just trying to aim for an 80/20 solution (or rather, 98/02) for now. There are many good reasons to work on unqualified identifiers, including e.g. multi-tenancy, schema agnosticity, etc. jOOQ ultimately never judges its users - there's always a reason to do X.

Anyway. There are many ways / workarounds of resetting the current schema to the one before a new schema was created, so this isn't a thing that needs to be addressed urgently.

> Maybe about creating non-SQL-standard (read Exasol-specific) constructs. On the other hand the SSB probably does not contain a lot of those yet, except scripting statements.

I see. jOOQ has never had many issues with vendor specific syntax. We can standardise and/or emulate almost everything. For now, the goal is to get all our integration tests to pass in 3.15, such that our customers can start working with / migrate to Exasol.

**Comment by lukaseder** [comment]
Support integrated for jOOQ 3.15
