### ISSUE TITLE
Add Batch.size() to indicate the number of queries that will be executed by a batch operation

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2028]
Adding size() to `org.jooq.Batch` might make sense. For `org.jooq.impl.BatchSingle`, this would return the number of bind value sets. For `org.jooq.impl.BatchMultiple`, this would return the number of queries. This number would correspond to the length of the int[] returned by Batch.execute()

This was discussed here:
https://groups.google.com/d/topic/jooq-user/RMIOQhOsX1A/discussion

**Comment by mkurz** [comment]
Is there a way to **set** the batch size? E.g. If we have a `Result` with 1000 entries and we want to batch update them, but by batches of 50 per update statement, wouldn't it be comfortable if we could just pass the batch size to jOOQ and let it handle that for us? Right now we would have to split the `Result` ourselves.
Something like:
`DSL.using(connection, somedialect).batchUpdate(worlds).setBatchSize(50).execute();`
@lukaseder What do you think? However it's just an idea, nothing really high priority for us.

**Comment by lukaseder** [comment]
Thanks for the suggestion, @mkurz. That sounds interesting indeed. We already have a way to specify things like bulk / batch / commit sizes in the loader API, but not in the batch API. It would certainly make sense to think about this. I've created https://github.com/jOOQ/jOOQ/issues/6815

**Comment by mkurz** [comment]
Thanks!

**Comment by mkurz** [comment]
Offtopic: I added a play-jOOQ project to the TechEmpower benchmarks: https://github.com/TechEmpower/FrameworkBenchmarks/pull/3062

**Comment by lukaseder** [comment]
Thanks. I've seen your ping. Will look into this later
