### ISSUE TITLE
Add support for the MemSQL database

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2059]

**Comment by rohanprabhu** [comment]
Is this still on the roadmap?

**Comment by lukaseder** [comment]
@rohanprabhu Yes sure. But it's not planned for a specific release yet

**Comment by batyape** [comment]
Do you have a planned release date?

**Comment by lukaseder** [comment]
Not yet, although we're seeing more traction for this integration. Will increase priority of this issue

**Comment by batyape** [comment]
@lukaseder Thank for your answer.

**Comment by lludwa** [comment]
+1

**Comment by knutwannheden** [comment]
Docker hub has an official image: https://hub.docker.com/_/memsql.

**Comment by knutwannheden** [comment]
* MySQL compatibility: https://docs.memsql.com/introduction/latest/memsql-faq/#what-is-the-relationship-between-memsql-and-mysql
* SQL reference: https://docs.memsql.com/sql-reference/v6.7/sql-reference-overview/

**Comment by knutwannheden** [comment]
MemSQL support has been integrated for jOOQ 3.12.
