### ISSUE TITLE
Add support for the Postgres INET data type (java.net.InetAddress)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2092]
See this discussion here for more insight:
https://groups.google.com/d/topic/jooq-user/YErDInFpPAg/discussion

**Comment by tomdcc** [comment]
Just a +1 here for adding `inet` type support to `PostgresDataType` - it's a built-in type that has been around since Postgres 6.4. @domdorn's above formulation works well for me here, or alternatively something that translates to/from `java.net.InetAddress` would also be fine.

**Comment by lukaseder** [comment]
Thanks for the feedback, @tomdcc. We'll look again at this for 3.9

**Comment by AlexisCothenet** [comment]
But java.net.InetAddress.getByName("192.168.1.1/32") will throw an exception whereas cidr supports this format. Am i wrong ?

**Comment by lukaseder** [comment]
Possibly. Whether `InetAddress` is a good candidate for a user type has yet to be decided. It probably isn't, and we'll add something like `org.jooq.postgres.extensions.types.Hstore`

**Comment by benstpierre** [comment]
We used this type in hibernate via hibernate-types and loved it. https://github.com/vladmihalcea/hibernate-types/blob/master/hibernate-types-55/src/main/java/com/vladmihalcea/hibernate/type/basic/Inet.java.  I would LOVE to have all of these types Vlad's library has in Hibernate in Postgresql.

**Comment by lukaseder** [comment]
Thanks for your feedback, @benstpierre. I'll look into this today.

**Comment by lukaseder** [comment]
pgjdbc delivers the usual `PGobject` when reading the value with `ResultSet::getObject`. Calling `ResultSet::getString` produces the expected string representation of the IP address. `ResultSet::getBytes` doesn't produce anything meaningful (e.g. to benefit instantiating the `InetAddress` subtype from `InetAddress::getByAddress(byte[])`)

In any case, as I commented earlier, `InetAddress` isn't the correct user type for PG's `inet` type, as the `inet` type can contain netmasks, such as:

```sql
select '192.168.0.0/24'::inet
```

Such a value can't be represented by `InetAddress`, so we'll have to create a new custom   `org.jooq.postgres.extensions.types.Inet` type

**Comment by lukaseder** [comment]
IPv6 supports the same routing prefix syntax but with a different semantics. To my understanding, these values can be only very small integer numbers (up to `32` in IPv4, up to `128` in IPv6), so a nullable `Integer` might be a reasonable choice here, where `null` means that there is no prefix and the `inet` value is only an IP address.

**Comment by lukaseder** [comment]
Probably makes sense to support the `cidr` type also, in the same step.

**Comment by lukaseder** [comment]
Will also tackle the task of auto-configuring the bindings in the code generator if they can be found on the classpath, and if the auto-configuration isn't turned off: https://github.com/jOOQ/jOOQ/issues/10763

**Comment by lukaseder** [comment]
This is now implemented for jOOQ 3.17.0. Auto-discovery of these extension types will be implemented later, today: https://github.com/jOOQ/jOOQ/issues/10763
