### ISSUE TITLE
Add support for non-standard date-time fields in the EXTRACT() function

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2132]
Postgres supports a variety of other "date parts" than the ones specified in the SQL standard:
https://www.postgresql.org/docs/current/static/functions-datetime.html#FUNCTIONS-DATETIME-EXTRACT

When adding new parts, we'll have to:

- Annotate parts with `SQLDialect`
- Implement native support where available
- Emulate support where possible (in separate tickets)

The followint date parts (from PostgreSQL) would be useful:

- `CENTURY` (emulation based on `YEAR`)
- `DECADE` (emulation based on `YEAR`)
- `ISO_DAY_OF_WEEK` (see #7792)
- `DAY_OF_WEEK` (see #7792)
- `DAY_OF_YEAR` (see #7793)
- `EPOCH` (see #7794)
- `MICROSECOND`
- `MILLENNIUM`
- `MILLISECOND`
- `QUARTER` (see #7796)
- `TIMEZONE`
- `TIMEZONE_HOUR` (actually part of the SQL standard)
- `TIMEZONE_MINUTE` (actually part of the SQL standard)
- `WEEK`

Support will be needed in the following functions:

- [x] `extract()`

In a separate task, we'll add support for these: 

- [x] `dateAdd()` (see #8823)
- [x] `dateSub()` (see #8823)
- [x] `localDateAdd()` (see #8823)
- [x] `localDateSub()` (see #8823)
- [x] `localDateTimeAdd()` (see #8823)
- [x] `localDateTimeSub()` (see #8823)
- [x] `timestampAdd()` (see #8823)
- [x] `trunc()` (see #8418)

----
This was requested here:
- https://groups.google.com/d/topic/jooq-user/IVy74kfg988/discussion
- https://groups.google.com/d/msg/jooq-user/Xff7ajkwDUk/5KfnZl_0CAAJ
- http://stackoverflow.com/q/23335674/521799

**Comment by lpireyn** [comment]
I want to implement this by adding values to the `DatePart` enum and ensuring that all its uses (`switch`, etc.) are still valid. Is there any reason against modifying the enum? Can values be inserted among the existing values (therefore modifying their ordinal value) without disrupting the existing code?

**Comment by lukaseder** [comment]
Adding new values to the enum will come with substantial integration testing and emulation efforts to make sure that the new literal works across all 20 supported RDBMS. Note that `EXTRACT()` is not the only function relying on `DatePart`. We prefer to be careful with adding this feature - probably not a good contribution candidate.

**Comment by lukaseder** [comment]
`EXTRACT()` support is implemented for PostgreSQL.

- Emulations will be done in other databases, where applicable
- Other datetime arithmetic functions will be supported as well

**Comment by lukaseder** [comment]
There's still a lot of work getting this to work for every function (other than the trivial `EXTRACT()`) and in every SQL dialect that can emulate it. I have set the current implementation to deprecated / experimental. Will look into this again in 3.12

**Comment by lukaseder** [comment]
Other functions will be supported via separate issues, including #8418 (trunc) and #8823 (various add/sub functions)

**Comment by lyginne** [comment]
`String rendered =    DSL.using(SQLDialect.SQLSERVER2017).render(DSL.extract(EVENT.START_DATE, DatePart.WEEK))`
expeted:
`"datepart(wk, event.start_date)"`
actual:
`"extract(week from event.start_date)"`

Should i create an issue for that, or is it already known?

**Comment by lukaseder** [comment]
Thank you very much for your report, @lyginne. Would you mind creating an issue for that? That should be supported in SQL Server. We'll investigate why it doesn't work.

**Comment by lyginne** [comment]
Created one: #9512
