### ISSUE TITLE
Support MySQL's INSERT .. VALUES(), () ON DUPLICATE KEY UPDATE x = VALUES(x) syntax (multi-insert with update)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2134]
This is probably not properly supported:
```sql
INSERT INTO beautiful (name, age)
      VALUES
      ('Helen', 24),
      ('Katrina', 21),
      ('Samia', 22),
      ('Hui Ling', 25),
      ('Yumie', 29)
ON DUPLICATE KEY UPDATE
     age = VALUES(age),
     ...
```

As referenced here:
- https://groups.google.com/d/topic/jooq-user/UcfkQQByCBk/discussion
- https://groups.google.com/forum/#!topic/jooq-user/D8RjRIBwxaE

**Comment by killermonk** [comment]
If you use the following on a normal insert query builder
.onDuplicateKeyUpdate()
	.set(field("DateValue"), (Object)field("VALUES(DateValue)"))
	.set(field("NumericValue"), (Object)field("VALUES(NumericValue)"))
	.set(field("TextValue"), (Object)field("VALUES(TextValue)"));

Then a call to getSQL() gives you the following SQL:
on duplicate key update DateValue = VALUES(DateValue), NumericValue = VALUES(NumericValue), TextValue = VALUES(TextValue)

There might be a better way to do this, but this worked for me.

**Comment by lukaseder** [comment]
@killermonk : Thanks for contributing. This is actually a very good way to go ahead and do this. Alternatively, you could extract the functionality in your own class:

```java
class MyDSL {
    public static <T> Field<T> values(Field<T> field) {
        return DSL.field("VALUES({0})", field.getDataType(), field);
    }
}
```

That could now be used as such in a type safe way:

```java
.onDuplicateKeyUpdate()
    .set(T.DATE_VALUE, MyDSL.values(T.DATE_VALUE))
    .set(T.NUMERIC_VALUE, MyDSL.values(T.NUMERIC_VALUE))
    .set(T.TEXT_VALUE, MyDSL.values(T.TEXT_VALUE))
```

**Comment by lukaseder** [comment]
Added `MySQLDSL.values()` due to popular request.

**Comment by demongaorui** [comment]
@adriancole Could you share the url of the separate issue about *text.batchInsert().onDuplicateKeyUpdate(true)* ?  I want to use this functionality as well.

**Comment by adriancole** [comment]
@demongaorui as far as I can tell I never created that issue

**Comment by demongaorui** [comment]
@adriancole I see...

@lukaseder Do we have a way to do **ext.batchInsert().onDuplicateKeyUpdate(true)** now?
I want to do multiple rows insert/onDuplicateKeyUpdate in only one execution.

**Comment by lukaseder** [comment]
@demongaorui: The suggested API probably won't work this way. Perhaps, we'll add a `UpdatableRecord.upsert()` and thus a `batchUpsert()` method at some point, but the `ON DUPLICATE KEY UPDATE` clause is too powerful to be passed to the `batchInsert()` statement as a simple extension.

Right now, however, you can easily batch actual `ON DUPLICATE KEY UPDATE` statements like this:

```java
insertInto(TABLE).set(record).onDuplicateKeyUpdate().set(record)
```

Hope this helps

**Comment by demongaorui** [comment]
@lukaseder  Thank you very much for rapid reply. 

Currently, I am using

```java
for (Record record : records) {
  db.insertInto(TABLE).set(record)
     .onDuplicateKeyUpdate().set(record)
     .execute();
}
```

But this will cause running many queries to db. For direct insert, we could do like
```java
db.insertInto(TABLE).set(record1).newRecord().set(record2).execute();
```
So all the records could be inserted in just one execution. 

Is there any way we could do insert/onDuplicateKeyUpdate for multiple records in one execution?

**Comment by lukaseder** [comment]
Yes, I'm sorry I may not have been clear. You can batch the statements with this API:
https://www.jooq.org/doc/latest/manual/sql-execution/batch-execution

**Comment by demongaorui** [comment]
@lukaseder  Thank you very much for your info!

**Comment by lukaseder** [comment]
This feature would be very interesting to emulate in other dialects: https://github.com/jOOQ/jOOQ/issues/11882

**Comment by lukaseder** [comment]
To looking for a batched version of the syntax, jOOQ 3.14 has learned this new trick, a "batched connection": https://www.jooq.org/doc/latest/manual/sql-execution/batched-connection/
