### ISSUE TITLE
Improve QueryPartList.removeNulls() as this is called very often

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2145]
The internal `QueryPartList.removeNulls()` method accounts for 10-15% of the time needed when accessing record properties through `Record.setValue()` and `Record.getValue()`. This time can be reduced by adding a simple `c.contains(null)` defender check in the method, as nulls are hardly ever passed to `QueryPartLists`

**Comment by lukaszx0** [comment]
This causes NPE when ImmutableCollection is passed. Immutable collections don't support `null` at all and calling `contains` on them throws NPE. Eg.:

```java

List<SelectField<?>> selectFields = Lists.of(...)
// or with guava:
// List<SelectField<?>> selectFields = ImmutableList.of(...)

SelectConditionStep<Record> selectedTransfersStep = context
          .select(selectFields)
          // ...
```

**Comment by lukaseder** [comment]
Interesting, what version of Guava does that? Version 26 doesn't seem to throw a NPE on calling `ImmutableCollection.contains(null)`: https://github.com/google/guava/blob/v26.0/guava/src/com/google/common/collect/ImmutableList.java#L422

Anyway, may I suggest you open up a new issue with a way to reproduce this problem (stack trace, your actual code including third party dependency versions, etc.). This issue is 5.5 years old and maybe it is only remotely related to your issue...

**Comment by lukaseder** [comment]
Relevant issue to fix this for immutable collections that aren't lenient with nulls (e.g. JDK 9 `List.of()`) is #7991
