### ISSUE TITLE
Integrate ARRAY types with UDT's

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#226]
Create an ARRAY of UDT (e.g. u_address_type[])

---

This is currently not supported by the postgres JDBC driver. Check out http://groups.google.com/group/pgsql.interfaces.jdbc/browse_thread/thread/58617fe3ca15cc2f#

---

Some test cases have been added, but it looks as though this feature cannot be implemented before the JDBC driver adds true SQLData support

**Comment by lukaseder** [comment]
@desiderantes Thanks for your message. I'm closing this ancient issue as it is really not very descriptive (my fault) and because there had been tons of improvements in more recent releases, so perhaps it's not really the problem you're facing.

Would you mind creating a new issue with steps to reproduce your problem?

**Comment by desiderantes** [comment]
Thanks @lukaseder, I created #7496 for that.
