### ISSUE TITLE
Enhance API to provide access to ARRAY elements

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#229]
Currently, ARRAY's can only be referenced as a whole, e.g.

``` sql
SELECT isbn FROM t_book;
```

But in fact, it may be a lot more interesting, if these kinds of constructs were possible as well:

``` sql
SELECT isbn[1] FROM t_book;
SELECT * FROM t_bookORDER BY isbn[1];
```

The API is `Field.get(int index)`. This will make using actual `isbn[1]` syntax possible out of the box in Kotlin. The problem is that a method on `Field` cannot reason about its own `T` type being a `T[]` type, and get access to the array component type... Kotlin's infix functions could help here, same for Scala's implicit methods but there's no solution in Java.

**Comment by tomdcc** [comment]
+1 Ran into needing this today

**Comment by lukaseder** [comment]
Thanks, for the feedback, @tomdcc. We still don't have a solution for this, although the workaround is rather easy:

```java
public static <T> Field<T> get(Field<T[]> field, int index) {
    return (Field) DSL.field("{0}[{1}]", field.getDataType().getType().getComponentType(), val(index));
}
```

**Comment by hwaring** [comment]
+1 ran into this. Workaround worked great

**Comment by lukaseder** [comment]
This has been added via https://github.com/jOOQ/jOOQ/issues/10175 (`DSL.arrayGet()`). In jOOQ 3.14, we'll ship a `jOOQ-kotlin` module, which includes these two `operator` functions:

```kotlin
@Support
inline operator fun <T> Field<Array<T>>.get(index: Int) = arrayGet(this, index)

@Support
inline operator fun <T> Field<Array<T>>.get(index: Field<Int>) = arrayGet(this, index)
```

Allowing for this usage:

```kotlin:
val a = field(unquotedName("a"), INTEGER.arrayDataType)
assertEquals(arrayGet(a, 1), a[1])
```
