### ISSUE TITLE
Add DSL.noField() for "conditional" LIMIT, OFFSET, GROUP BY, ORDER BY support when creating dynamic SQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2333]
For many other clauses, dynamic SQL creation is somewhat facilitated by allowing ~`null` or~ empty list/array arguments. This is not the case for the `LIMIT .. OFFSET` clause. It should be possible to pass an argument to `LIMIT .. OFFSET`, which has no effect, similar to `DSL.noCondition()`, perhaps a `DSL.noField()` expression.

### API

The usual overloads for `Field<T>` expressions apply:

- [x] `DSL.noField(): Field<?>`, when the `T` type doesn't matter
- [x] `DSL.noField(Class<T>): Field<T>`, when the `T` type matters (only in `SELECT`)
- [x] `DSL.noField(DataType<T>): Field<T>`, when the `T` type matters (only in `SELECT`)
- [x] `DSL.noField(Field<T>): Field<T>`, when the `T` type matters (only in `SELECT`)

### Behavioural specification:

**Select clauses**

- [x] If it's in the `SELECT` clause or anywhere where we need a value (e.g. a built in function argument), we produce `NULL` of that column type
- [x] If it's in the `GROUP BY` clause, we skip the field. If it's the only field, we don't group
  - [x] This includes winodw function `PARTITION BY`
- [x] If it's in the `ORDER BY` clause, we skip the field. If it's the only field, we don't order
  - [x] This includes window function `ORDER BY`
  - [x] This includes aggregate function `ORDER BY`
  - [x] This includes aggregate function `WITHIN GROUP (ORDER BY ...)` (the clause is mandatory, though)
- [x] If it's in the `LIMIT` or `OFFSET` clause, we skip the clause.

**Expressions**

- [x] `noField()` implements `SortField` and always returns itself, e.g. when calling `noField().asc()`

**Other interactions**

- [x] `condition(noField())` produces `noCondition()`
- [x] `field(noCondition())` produces `noField(BOOLEAN)`

**Additional changes**:

- https://github.com/jOOQ/jOOQ/issues/13428

----
See also the original discussion here:
https://groups.google.com/forum/?fromgroups=#!topic/jooq-user/o0PdW8MCYT4

**Comment by romejoseph** [comment]
@lukaseder Do you have any update for this?

**Comment by lukaseder** [comment]
Thanks for your ping, @romejoseph. There are numerous places in the jOOQ API where such a "no value" would be useful, similar to the `DSL.noCondition()`, which can be used for predicates. With predicates, this seems simpler, because there are only a few operators involved, such as `AND`, `OR`, etc. With integer and other values, things tend to be more complicated.

Allowing `null` is not a good idea because `null` is a valid value in SQL and it would not be possible to distinguish between the rare cases where sending an actual `null` value to SQL is desireable and where it should mean nothing.

In this particular case, however, there exists a reasonable and easy workaround. Use something like `DSL.inline(Integer.MAX_VALUE)` for limit, and `DSL.inline(0)` for offset.

**Comment by lukaseder** [comment]
This has been implemented for jOOQ 3.17.0, finally. Some open issues will be addressed here: https://github.com/jOOQ/jOOQ/issues/13428, including whether to apply this `noField()` to `GROUPING SETS` or binary expressions such as `noField().add(1)`.

Additional such constructors, such as `noTable()` or `noSelect()` might be added via https://github.com/jOOQ/jOOQ/issues/12969

**Comment by lukaseder** [comment]
Interesting use-case that I haven't considered yet would be DML statements, e.g. conditional `UPDATE` clauses:

- https://github.com/jOOQ/jOOQ/issues/7723
- https://github.com/jOOQ/jOOQ/issues/13585

Specifically:

```java
ctx.update(T)
   .set(T.COL1, "X")
   .set(T.COL2, condition ? val("Y") : noField(T.COL2))
   .execute();
```

**Comment by lukaseder** [comment]
`UPDATE` and `DELETE` support has been implemented in this issue. `INSERT` is still due: https://github.com/jOOQ/jOOQ/issues/13588

**Comment by alf** [comment]
This is great! 👏

**Comment by lukaseder** [comment]
This doesn't yet work for the `SEEK` clause: https://github.com/jOOQ/jOOQ/issues/14395

**Comment by alf** [comment]
Thanks for the heads up.

**Comment by MikePSQR** [comment]
this is great, but I still can't do `.limit(myLimit == Integer.MAX_VALUE ? noField() : myLimit)` is there some clean-ish way to do that or my best bet is still as described here? https://stackoverflow.com/a/66442511

**Comment by lukaseder** [comment]
It works for me (do pass a data type, e.g. `noField(INTEGER)`)

**Comment by lo-guevara** [comment]
@lukaseder I'm trying to use the noField() with update.. set to update a column based on whether a parameter is present, but I'm getting some errors. 

In Kotlin, springboot, using jooq 3.18.2

```
fun updateAnchor(anchorDay: Int?) {
    dsl
        .update(SUBSCRIPTION)
        .set(SUBSCRIPTION.STATUS, anchorDay ?: noField(Int::class.java))
        .execute()
}
```
I tried using it the same way you described with the conditional directly in the set() but I'm getting an error that `anchorDay ?: noField(Int::class.java)` can't be supplied as an argument to set(). 


<img width="1004" alt="Screenshot 2024-05-16 at 11 57 41 AM" src="https://github.com/jOOQ/jOOQ/assets/16786959/62de41b2-2b8b-47ea-a010-7a7982ebdfb3">

**Comment by alf** [comment]
I believe `noField` should be supplied as the first argument to `set`.

**Comment by lo-guevara** [comment]
@alf thanks! I was able to get it to work with this:

```
fun updateAnchor(anchorDay: Int? = null) {
    dsl
        .update(SUBSCRIPTION)
        .set(
                if (anchorDay != null) SUBSCRIPTION.ANCHOR_DAY else noField(Int::class.java), 
                anchorDay
         )
        .execute()
}
```

**Comment by lukaseder** [comment]
@lo-guevara You cannot write `anchorDay ?: noField(Int::class.java)` as `anchorDay` is of type `Int?` and the fallback expression is of type `Field<Int?>`, so the kotlin compiler doesn't know what to do with it.

Do this instead:

```kotlin
if (anchorDay != null) value(anchorDay) else noField(Int::class.java)
```

See:

- https://stackoverflow.com/q/67522537/521799
- https://www.jooq.org/doc/latest/manual/sql-building/bind-values/indexed-parameters/
