### ISSUE TITLE
Support PostgreSQL multi table TRUNCATE statement

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2356]
Postgres allows for truncating several tables at a time through the `TRUNCATE [name], ...` syntax. This should be supported by jOOQ as well:

https://www.postgresql.org/docs/current/sql-truncate.html

**Comment by Spirarel** [comment]
Hey Lukas, did this ever get written?
I couldn't find documentation for it. I'm looking for a handy way to "reset" the DB between integration tests. Right now that looking like it's going to be a map over tables with truncate and cascade.

<img width="1024" alt="Screenshot 2023-08-22 at 10 22 51 AM" src="https://github.com/jOOQ/jOOQ/assets/10119394/dfe38d43-3087-4f20-a687-750f647fec9d">

**Comment by lukaseder** [comment]
This does have a surprising number of upvotes. I'll look into it, at least as far as native support is concerned. Emulations are less likely to be prioritised.

**Comment by lukaseder** [comment]
Emulation task:

- https://github.com/jOOQ/jOOQ/issues/15556

**Comment by lukaseder** [comment]
Implemented for jOOQ 3.19
