### ISSUE TITLE
INSERT .. RETURNING always returns null for dynamically created tables

### ISSUE THREAD

**Issue by svenjacobs** [jOOQ/jOOQ#2374]
INSERT .. RETURNING always returns null for dynamically created tables (that is when not using jOOQ's code generation). Database is MySQL 5.6.10. Using jOOQ 3.0.0-RC2.

```java
// record is always null
Record record = create.insertInto(tableByName("MY_TABLE"), fieldByName("FIELD1"), fieldByName("FIELD2"))
	.values(values)
	.returning(fieldByName("ID_FIELD"))
	.fetchOne();
```

Here's why:

In `AbstractStoreQuery` the generated ID is correctly fetched and then passed to `selectReturning()` at line 308. However in `selectReturning()` there's the check

```java
if (into.getIdentity() != null)
```

at line 361 which always fails because `getIdentity()` in `AbstractTable` always returns *null*

```java
public Identity<R, ? extends Number> getIdentity() {
    return null;
}
```

As a workaround I thought, well then I create an anonymous instance of `QualifiedTable`, overwrite `getIdentity()` and pass that instance to `insertInto()` but unfortunately `QualifiedTable` (and also `AbstractTable`) is package-protected.

Please provide means to specify an identity column for dynamically created tables.

**Comment by lukaseder** [comment]
It's probably not possible to solve this issue reliably, short of either:

- Looking up meta-information at run time, which is quite a change
- Letting users implement their own `Table` implementations, that contain a `Identity` reference.

**Comment by lasjen** [comment]
Hi Lukas
Have generated code, and try this (which I thought should work in Oracle):
DSLContext create = DSL.using(DatabaseUtil.getConnection(), SQLDialect.ORACLE);

      Record rec = create.insertInto(AUTHOR, AUTHOR.ID, AUTHOR.FIRST_NAME, AUTHOR.LAST_NAME)
                     .values(create.nextval(AUTHOR_SEQ), first_name, last_name).returning(AUTHOR.ID).fetchOne();

Always returns NULL. Am I doing something wrong?

**Comment by lukaseder** [comment]
Hi @lasjen: Thanks for reporting. API usage looks perfect to me. Do note that `DSLContext.nextval(Sequence)` runs a query to fetch the next value into the client. It doesn't generate a `AUTHOR_SEQ.NEXTVAL` expression in the generated SQL string.

I'll need to further investigate this. Perhaps the JDBC driver doesn't yield any results... What Oracle version and ojdbc driver version are you using?

**Comment by lasjen** [comment]
Oracle database 12.1.0.1 and ojdbc7.jar version 12.1.0.2.

—Lasse

**Comment by lukaseder** [comment]
Thanks for the pointer. Perhaps this does have something to do with the ojdbc7 version. I'll investigate ASAP! I have created a new issue for this: https://github.com/jOOQ/jOOQ/issues/5543
