### ISSUE TITLE
Make it easier to implement DSLContext

### ISSUE THREAD

**Issue by nicoulaj** [jOOQ/jOOQ#2463]
The new API in 3.0 with DSLContext + DSL static constructors is fine, but it locks users from extending implementations of DSLContext.

I would be great if one the following changes was made:
- Make DSLContextImpl + constructors public
- Make it easy to use the delegation pattern by providing a DelegatingDSLContext, so we can do stuff like this:

``` java
class MyDSLContext extends DelegatingDSLContext {

    MyDSLContext() {
        super(DSL.using(...));
    }

    // Overridden methods + own methods
}
```

**Comment by lukaseder** [comment]
While making `DefaultDSLContext` public has been implemented successfully (https://github.com/jOOQ/jOOQ/issues/2466), adding a means to delegate to another context hasn't gotten any traction.

I'll close this issue as "won't fix"
