### ISSUE TITLE
Inconsistent Field lookup behavior from Record

### ISSUE THREAD

**Issue by azell** [jOOQ/jOOQ#2501]
As documented via the mailing list, Record.getValue(Field) will not work as expected when multiple Fields share the same name even if the fields belong to different tables.

``` java
... select(FOO.ID, BAR.ID) ...

Object foo = record.getValue(FOO.ID);
Object bar = record.getValue(BAR.ID);
```

In this instance, foo and bar will share the same value though both distinct fields are present in the record.  This is not intuitive as TableFieldImpl objects know their parent table, and use it in the equals method.  Record.intoMap will also fail due to the common field name.

One way to get around this:

``` java
  public static Map<Field<?>, Object> build(Record record) {
    Map<Field<?>, Object> fields = Maps.newHashMap();
    Field[]               arr    = record.fields();

    for (int i = 0, j = arr.length; i < j; ++i) {
      fields.put(arr[i], record.getValue(i));
    }

    return fields;
  }

  public static <T> T get(Map<Field<?>, Object> fields, Field<T> field) {
    return field.getType().cast(fields.get(field));
  }
```

Now the caller can obtain the distinct fields and retain the generic type information.  Is there a way to support this in the Record class itself?

**Comment by fedotxxl** [comment]
Is any workaround for this problem? I think current behaviour is very confusing. Is it possible to check is `BAR` table joined or not?

**Comment by lukaseder** [comment]
@fedotxxl Coincidentally, there is a very recent discussion on the user group about this:
https://groups.google.com/forum/#!topic/jooq-user/5ziIzqgWYQw
