### ISSUE TITLE
Add RecordUnmapper<E, R extends Record> to allow for the inverse operations of RecordMapper

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2520]
Currently, `RecordMapper<R extends Record, E>` is the "best" way to inject custom ORM functionality mapping jOOQ records to custom domain models.

However, there is currently no interface allowing for loading custom domain models back to jOOQ records, short of `Record.from(Object)`, which is the inverse of jOOQ's "basic ORM feature" `Record.into(Class<?>)`.

As the long-term strategy in jOOQ is not to provide any more ORM features, such an API would be the right step forward. (Name to be discussed)

---

This feature evolved from a critique by @ben-manes in #2519, where he claimed that adding more `from()` methods to `Record` would not match the right long-term strategy.

**Comment by collinpeters** [comment]
:+1: from me. See reference here: https://groups.google.com/forum/#!topic/jooq-user/UZDZjTQADt0

**Comment by dcominottim** [comment]
+1
