### ISSUE TITLE
Cannot combine INSERT .. SELECT with INSERT .. ON DUPLICATE KEY .. due to DSL API flaw

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2529]
The `INSERT` DSL API does not allow to combine `INSERT ... SELECT` with `INSERT ... ON DUPLICATE KEY { UPDATE | IGNORE }`. This is due to the declaration of `InsertValuesStepN`:

```java
public interface 
    InsertValuesStepN<R extends Record>
extends 
    InsertOnDuplicateStep {

    Insert<R> select(Select<?> select);
```

Instead of returning `InsertOnDuplicateStep`, `Insert` is returned.

----
Related issue: #2123

**Comment by wesleyk** [comment]
Hello, is this issue now resolved given https://github.com/jOOQ/jOOQ/issues/3779 has been fixed? Thanks!

**Comment by lukaseder** [comment]
@wesleyk : Good point, unfortunately, no. This will be an independent fix. I've increased the priority of this issue

**Comment by wesleyk** [comment]
Ah okay, thanks for the quick response @lukaseder!

**Comment by mikebridge** [comment]
@lukaseder Is this related to the following scala code?  I tried combining `onDuplicateKeyIgnore` with `returning` but didn't see a way to do it:

```scala
ctx.insertInto(ACCOUNT, ACCOUNT.USERNAME, ACCOUNT.GIVENNAME, ACCOUNT.FAMILYNAME, ACCOUNT.EMAIL)
    .values(account.username, account.givenname, account.familyname, account.email)
    .onDuplicateKeyIgnore()
    .returning(ACCOUNT.ID, ACCOUNT.DATECREATED) // invalid!
    .fetchOne()
```

**Comment by lukaseder** [comment]
Thanks for the reminder, @mikebridge. That's https://github.com/jOOQ/jOOQ/issues/2123. I've given it a higher priority.

**Comment by mikebridge** [comment]
Thanks @lukaseder.  A try/catch workaround is fairly straightforward but that would be a nice-to-have feature.  

(I didn't mention I was running this over postgresql.)

**Comment by lukaseder** [comment]
@mikebridge What do you mean by a try/catch workaround?

**Comment by mikebridge** [comment]
@lukaseder Sorry, I meant I would try inserting the record and then catch an exception if it's a duplicate, à la https://groups.google.com/d/msg/jooq-user/jvIAlNQOsDg/c7gIR9dvKzQJ

**Comment by lukaseder** [comment]
Oh, I see, thanks for the pointer. Yes of course, that works as well.
