### ISSUE TITLE
Support Converters for ARRAY data types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2533]
In Postgres, HSQLDB, H2 and Oracle, users can use array data types, such as:

```sql
create table x (
    value text[]
)
```

jOOQ maps `text[]` to `String[]`. If a user wants to convert `value` to a custom type, they would need to register a `Converter<String[], com.example.CustomType[]>`.

However, this seems not to work:
https://groups.google.com/forum/?fromgroups#!topic/jooq-user/k0IOPpdsxYo

**Comment by kovrus** [comment]
+1

**Comment by lukaseder** [comment]
This is in fact a duplicate of #4388
