### ISSUE TITLE
Deprecate fetchLater() and FutureResult<R>

### ISSUE THREAD

**Issue by alexeyr** [jOOQ/jOOQ#2581]
`fetchLater` methods return a `FutureResult<R>`. Unfortunately, it doesn't allow the user to register callbacks which will execute when the result is fetched, as do Scala `Future` or Guava `ListenableFuture`. This is a very useful capability for asynchronous programming. See, e.g., http://code.google.com/p/guava-libraries/wiki/ListenableFutureExplained.

**Comment by lukaseder** [comment]
See also: https://github.com/jOOQ/jOOQ/issues/5012 for a better implementation in jOOQ 3.8
