### ISSUE TITLE
Add implicit conversions from Scala functions to RecordHandler, TransactionRunnable, and others

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2600]
To allow use of Scala's lambdas in handler and mapper callbacks similarly to Java 8 examples in the manual, another conversions could be added to the `Conversions` object:

``` Scala
implicit def fun2handler[R <: Record](f: R => Unit): RecordHandler[R] = new RecordHandler[R] {
  def next(record: R) = f(record)
}
```

Other types (as of jOOQ 3.9):
- `ConnectionRunnable`
- `ExecuteEventHandler`
- `RecordHandler`
- `ThreadLocalTransactionalRunnable`
- `TransactionalRunnable`

---

See also #2595 (originally requested by @alexeyr)

**Comment by s4nk** [comment]
A similar conversion would be useful for TransactionRunnable

**Comment by lukaseder** [comment]
Thank you very much for the feedback, @s4nk. There are probably even more. I'll adapt the issue to reflect this

**Comment by lukaseder** [comment]
Not much traction in this issue. Won't fix.
