### ISSUE TITLE
Add support for Google BigQuery

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2620]
This SQL dialect might be worth exploring:
- https://developers.google.com/bigquery
- https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax

Some specialties that are worth keeping in mind have been postponed for a later release: https://github.com/jOOQ/jOOQ/issues/12058

### Other known issues:

**Not ready for 3.15**

- https://github.com/jOOQ/jOOQ/issues/11835: `ORDER BY` cannot reference expressions from `SELECT DISTINCT`
- https://github.com/jOOQ/jOOQ/issues/11837: `SELECT AS STRUCT` support
- https://github.com/jOOQ/jOOQ/issues/11842: `LEFT JOIN` / `SEMI JOIN` / `ANTI JOIN` limitations

**Fixed in 3.15**

- https://github.com/jOOQ/jOOQ/issues/11838: Aliases and other identifiers can't have `.` or other special characters
- https://github.com/jOOQ/jOOQ/issues/11841: Work around the Simba driver's lack of support for `NULL` bind variables

**Comment by jscinoz** [comment]
For what it's worth, since the last update on this issue, Bigquery has introduced a [new SQL dialect](https://cloud.google.com/bigquery/docs/reference/standard-sql) that is compliant with the SQL:2011 standard (& has a few extensions beyond that) and rebranded their previous dialect as "[Legacy SQL](https://cloud.google.com/bigquery/docs/reference/legacy-sql)"

**Comment by lukaseder** [comment]
Thanks for the update, @jscinoz. Indeed this now looks more promising: https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax

We'll review this - perhaps there's some synergy after all in supporting this dialect along with the new Google Spanner SQL dialect.

This might be done in the jOOQ Enterprise Edition

**Comment by kprochazka** [comment]
@lukaseder is there any update on this ?

**Comment by lukaseder** [comment]
@kprochazka No. If there was, this issue would be updated :-)

**Comment by lukaseder** [comment]
For the record, we're currently evaluating the additiona of a variety of "cloud SQL" dialects, including Amazon Aurora ones, BigQuery is a candidate, and maybe others. I currently cannot make any promises as to when this will ship.

**Comment by lukaseder** [comment]
Tackling this now for jOOQ 3.15

**Comment by lukaseder** [comment]
Spanner support is moved to  a separate issue: #11454

**Comment by lukaseder** [comment]
Additional work will be done in a future release: https://github.com/jOOQ/jOOQ/issues/12058
