### ISSUE TITLE
DAO.insert() and other DAO operations do not respect DEFAULT values

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2700]
As indicated here:
http://stackoverflow.com/q/18276421/521799

When inserting a POJO through a `DAO`, jOOQ will generate explicit `NULL` values for every attribute of the POJO that has a Java `null` value. This may not be appropriate if both `NOT NULL` and `DEFAULT` clauses are present in a table's underlying `DDL`.

jOOQ should leverage generated metadata (see #2699) to infer that a POJO `null` value should map to a `DEFAULT` value in generated SQL in both `INSERT` and `UPDATE` statements. Example:

``` sql
INSERT INTO bug(foo, bar)
VALUES(3, DEFAULT)

UPDATE bug SET bar = DEFAULT WHERE foo = 3
```

---

Related issue #2697

**Comment by mbayealioune** [comment]
Hi Lukas,

I am using Postgres 12 with jooq version 3.12
I am running into this issue that is normally solved already

I am using the generated DAO to make an insertion into the DB, the generated SQL is :
