### ISSUE TITLE
Add DataType.defaulted() and DataType.nullable() 

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2702]
As indicated here:
http://stackoverflow.com/q/18276421/521799

While `NULL` / `NOT NULL` constraints are already part of jOOQ's generated metadata through JPA / JSR-303 annotations, they're not yet formally available on the generated `DataType` objects.

In addition to nullability, the presence of a `DEFAULT` clause should also be annotated to indicate to jOOQ that in the absence of any explicit value, `INSERT` statements may generate non-`NULL` values for some columns.

---

Related issue: #2697

**Comment by shubham-vl** [comment]
Hi Lukas,

Can you just provide a sample code for using DataType.defaulted() to use for every table in system. So if in mysql i define default value jooq pojo should take care of that value.

**Comment by lukaseder** [comment]
@shubham-vl: Thanks for your enquiry. Would you mind providing some more details? What exactly (in SQL) are you trying to do?

**Comment by shubham-vl** [comment]
So we have jooq generated dao insert method, now what we are trying to do is using that,  Jooq generated pojo to call jooq insert api,  but if a variable is not set in jooq pojo its inserting as null instead of mysql default set value.

**Comment by lukaseder** [comment]
Is there a `NOT NULL` constraint on the column?

**Comment by shubham-vl** [comment]
yes it is.

Regards

Shubham Jaju

**Comment by lukaseder** [comment]
OK, I might still need a bit more information. Would you mind posting:

- The DDL of your table
- The jOOQ code that you wrote that fails according to your assumptions

**Comment by shubham-vl** [comment]
I think I figured it out . Some of the columns were marked as default
`value` but was not marked as `not null`.

Regards

Shubham Jaju

**Comment by lukaseder** [comment]
Thanks for the feedback.
