### ISSUE TITLE
Add Setting (or other mechanism) to override "changed" flag alteration behaviour

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2704]
Currently, the "changed" flag in a `Record` value is changed no matter if the value actually changes. This might not be what some users desire, as can be seen in these threads:
- https://groups.google.com/forum/#!topic/jooq-user/KoDpSMN7OzQ
- https://groups.google.com/d/msg/jooq-user/KtYYN8hD_uo/LScpH_ysSWkJ
- https://groups.google.com/forum/#!topic/jooq-user/gtMxNzg02NA
- https://groups.google.com/forum/#!topic/jooq-user/8MBETRVrLCM
- https://groups.google.com/forum/#!topic/jooq-user/52y94BV2upY
- https://groups.google.com/forum/#!topic/jooq-user/gTixth2pAVY
- https://groups.google.com/forum/#!topic/jooq-user/bDN84EDTbhc

Users should be able to influence this behaviour more easily, instead of implementing checks on their side and then explicitly manipulating the "changed" flags.

**Comment by deinspanjer** [comment]
I'm going to be another user wanting this.  I was going to post on the forums, but I did my studying first and found my way to this thread.

For my use case, I'm pulling data from some service, and using a key provided to look up my internal representation of the object in my database.  When I do that lookup, I get my primary key, but I need to be able to synchronize the POJO object and the record object, determine if there are any changed fields, and if so, do an update.

**Comment by lukaseder** [comment]
Thanks for the feedback, @deinspanjer. Would you mind adding a code example with some comments to the text? I'm not sure about what the English version means to you...
