### ISSUE TITLE
Add DSLContext.newRecord(Field<?>...) to support the creation of custom record types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2722]
In addition to the pre-existing `DSLContext.newRecord(Table)` method(s), there is also room for:
- `Record DSLContext.newRecord(Field<?>...)`
- `<T1> Record1<T1> DSLContext.newRecord(Row1<T1>)`
- `<T1, T2> Record2<T1, T2> DSLContext.newRecord(Row2<T1, T2>)`
- `<T1, T2, ..., T[N]> Record2<T1, T2, ..., T[N]> DSLContext.newRecord(Row[N]<T1, T2, ..., T[N]>)`

This would allow for creating custom records for custom row types.

---

See also this related discussion:
https://groups.google.com/forum/#!topic/jooq-user/BNWthTVXH7c

**Comment by kutoxinyi** [comment]
Is there any special using `DSLContext.newRecord(table)` to create record, Any difference with creating record by `Record rec = new Record()`?

**Comment by lukaseder** [comment]
@kutoxinyi: Yes, it is already "attached" to the `DSLContext`'s underlying `Configuration`. So, you can call `rec.store()` on it.
