### ISSUE TITLE
Add support for Amazon Redshift

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2728]
This would be a nice additional database to support:
http://aws.amazon.com/de/redshift/

**Comment by mapoulin** [comment]
Is there anything missing for complete support of Redshift/Postgres 8.x ?

We have been using jOOQ with Redshift for the past year and it seems to work well. The only thing we noticed was the lack of detection of the primary/foreign/unique keys when generating classes.

If I were to contribute the detection, would the code remain open-source? Is Redshift considered a commercial/enterprise database?

**Comment by lukaseder** [comment]
> Is there anything missing for complete support of Redshift/Postgres 8.x ?

We simply don't know (yet) as we've never integration-tested jOOQ with Redshift ourselves. But we're aware of a variety of users that have integrated successfully (with the odd patch needed)

> The only thing we noticed was the lack of detection of the primary/foreign/unique keys when generating classes.

Good to know. Probably, the dictionary views have improved since Postgres 8.x

> If I were to contribute the detection, would the code remain open-source? Is Redshift considered a commercial/enterprise database?

This is the main reason why we're not yet officially supporting Redshift. It challenges our business model. While Postgres 8,x would fall into the jOOQ Open Source Edition scope, Redshift wouldn't - it would be in the jOOQ Professional Edition. On the other hand, if we made it commercial, most people would bypass our commercial license and still use the open source edition.

Hence, right now, I cannot promise that your contribution would remain open source - but I can promise that we'll look into official support within the next months

**Comment by lukaseder** [comment]
We're evaluating feasibility of this integration for jOOQ 3.7 now. It's looking good from a first glance. We won't support this under the Open Source Postgres `SQLDialect` though, as there are too many subtle differences showing up in the integration tests. We'll create a new, commercial `SQLDialect.REDSHIFT`

**Comment by lukaseder** [comment]
@mapoulin : The integration is looking pretty good so far. Would you be interested in getting access to a jOOQ 3.7 preview?

**Comment by mapoulin** [comment]
@lukaseder Glad to hear integration is looking good and thanks for the offer ! I wish we could help but my team is not yet ready to upgrade to the professional edition.

**Comment by lukaseder** [comment]
@mapoulin Thanks for the feedback. Sure, I understand. Perhaps in the future, you will be able to get more value out of the professional edition as your project might grow, or as you might be adding support for other databases.

If there's anything else we can do for you, just let me know.
