### ISSUE TITLE
Default to using a Configuration from a ThreadLocal when no Configuration is "attached"

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2732]
In jOOQ 4.0, jOOQ will take care of a better separation of mutable and immutable API. In the mean time, it is worth thinking about handling thread-safety with respect to queries in a better manner, possibly through the introduction of a `ThreadLocal` keeping a reference to a "context" `Configuration`. This would involve:
### Creating attached objects and executing them:

``` java
DSL.using(...).select().from(...).fetch();
```

This will behave as today, for backwards-compatibility reasons. Queries created through DSLContext will be attached to their creating Configuration and execute themselves in the context of such a Configuration
### Creating unattached objects and executing them:

``` java
DSL.using(...).fetch(
    select().from(...)
)
```

This will no longer attach the argument query, but pull a Configuration from a ThreadLocal that is set (and unset) in the DSLContext.fetch() method
### Executing queries in a "block"

The above distinction would then allow for creating blocks around several queries. In the long run, such a model might allow for transaction listeners and other useful SPI:

``` java
DSL.using(...).run(new Runnable() {
    public void run() {
        // These methods pull a Configuration from a ThreadLocal
        select().from(...).fetch();
        insertInto().values(...).execute();
    }
});
```

Such blocks would also be very convenient to use with Java 8 lambdas:

``` java
DSL.using(...).run(() -> {
    // These methods pull a Configuration from a ThreadLocal
    select().from(...).fetch();
    insertInto().values(...).execute();
});
```

Supporting such blocks would allow for nesting blocks. Hence, the ThreadLocal would really be a ThreadLocal<Deque<Configuration>>, keeping track of the nesting of Configurations / blocks.
### Consequences

This would mean that jOOQ would:
1. Use an attached Configuration if available, for backwards-compatibility reasons
2. Try to get a Configuration from a ThreadLocal, if the current Query is not "attached"
3. Throw a DetachedException (or similar) if both of the above fail.

Such a solution would allow for a smooth transition towards jOOQ 4.0, when later versions of jOOQ 3.x could deprecate DSLContext's various Query construction DSL entry points, indicating that attaching queries will eventually not be supported anymore.

Such a solution would also allow for using jOOQ in a more threadsafe way, without resorting to client-side pooling tricks, and without having to wait for jOOQ 4.0

---

See also this discussion here:
https://groups.google.com/forum/#!topic/jooq-user/iomrnfK9cws

**Comment by billoneil** [comment]
I'm looking to implement something along these lines on my own with the caveat that I want multiple different connection pools. Basically, explicitly create a thread local `Configuration` from a specific pool then all further `DSL` use will use that configuration. Had a question related to this.

> Supporting such blocks would allow for nesting blocks. Hence, the ThreadLocal would really be a ThreadLocal<Deque>, keeping track of the nesting of Configurations / blocks.

Do you see Configuration's changing within nested blocks? I figure the configuration could already have a thread local transaction provider that will handle the transactional nesting parts. Would this also be needed for the configurations? My basic use cases of jOOQ basically share a same configuration across all of the code.

**Comment by lukaseder** [comment]
This feature would help executing queries that were constructed from `DSL`'s static methods. In the examples, there's an implied static import of `org.jooq.impl.DSL.*`. In other words, with a thread local configuration, we could do:

```java
DSL.selectOne().fetch();
```

Right now, this will throw a `DetachedException`, because the query is not attached to a configuration.
If this is just about connections and connection pools, you can very easily use a `DataSource` that makes use of thread bound connections / transactions and pass that to jOOQ without any special implementation. Or, you implement this semantics manually in your own `ConnectionProvider`. Then, the `Configuration` can be shared among all the threads - which is what most people actually do with jOOQ.

**Comment by lukaseder** [comment]
I've never had a very good feeling abou this idea. Rejected.
