### ISSUE TITLE
Bad inlining, setting, and registering of LocalDate, LocalTime, LocalDateTime, OffsetTime, OffsetDateTime bind values

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2738]
When inlining `Timestamp` bind values that are of type `PostgresDataType.TIMESTAMPWITHTIMEZONE`, the values are incorrectly inlined (without bind value)

While this particular data type is provided by jOOQ's API, it remains unclear if there are additional (custom?) data types, whose inline strategy is unknown to jOOQ.

**Comment by tedyoung** [comment]
I'm wondering what the status of this is, as I'm looking to store timestamptz information (really, Java 8's OffsetDateTime) -- how much of a problem is this?

**Comment by lukaseder** [comment]
Thanks for your feedback @tedyoung. Indeed, supporting this type was kind of a "problem" before our decision to support Java 8 (#3645), and thus JSR-310 (#4338) with jOOQ 3.7. Once we have JSR-310 support, there's no stopping us from supporting `TIME[STAMP] WITH TIME ZONE` data types in those RDBMS that support them.

However, we're still contemplating what to do with our numerous date/time arithmetic methods in `DSL`, which we cannot easily migrate to support JSR-310.

In the meantime, you'll be able to use jOOQ's data type `Binding` to bind your own `TIMESTAMPTZ` <-> `OffsetDateTime` mapping. For details, see:
http://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings/
