### ISSUE TITLE
Correctly implement RecordListener semantics for batch execution

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2770]
In jOOQ 3.2, RecordListener was introduced through #2010. This useful API is currently a bit ambiguous with respect to batch CRUD operations, such as `DSLContext.batchStore()`.

In this issue, the behaviour should be well-defined for jOOQ 3.3

**Comment by Quurks** [comment]
This issue is marked as fixed, but the javadoc notice from https://github.com/jOOQ/jOOQ/commit/4167a01ce93189a905890918de87e577a242743a still remains

**Comment by lukaseder** [comment]
@Quurks Thanks for the hint, nice catch. Will be fixed with #4036
