### ISSUE TITLE
Add JavaDoc on Settings classes

### ISSUE THREAD

**Issue by gquintana** [jOOQ/jOOQ#2830]
The meaning of the settings attributes is described as comments in http://www.jooq.org/xsd/jooq-runtime-2.5.0.xsd. These comments should be present in the JavaDoc http://www.jooq.org/javadoc/latest/org/jooq/conf/Settings.html as well.

I guess it's a matter of tuning the JAXB code generation:

```
<xsd:complexType name="RenderMapping">
  <xsd:annotation>
    <xsd:appinfo>
      <jxb:class name="RenderMapping">
        <jxb:javadoc>Configure render mapping for runtime schema / table rewriting in  generated SQL</jxb:javadoc>
      </jxb:class>
    </xsd:appinfo>
  </xsd:annotation>
</xsd:complexType> 
```

**Comment by lukaseder** [comment]
Implemented this as good as possible (i.e. no Javadoc generated on enums)
