### ISSUE TITLE
Consider if the default for Settings.renderSchema should be changed from "true" to "false"

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#2846]
Default values for `Settings` should reflect what most users "prefer" to use when getting started with jOOQ. It's good that `Settings` exist and that they can be adapted for use by "power users". But some "power user" defaults might be limiting for new jOOQ setups.

The renderSchema is one of them as can be seen here:
https://groups.google.com/d/msg/jooq-user/E47KwEcSvJI/gubGSN_LSMQJ

**Comment by phile314-fh** [comment]
I just stumbled over the ``renderSchema`` setting, as I was getting confused why Jooq used a different db than I had in the connection string. I would advocate for setting ``renderSchema`` to ``false`` by default.

**Comment by lukaseder** [comment]
In almost 10 years, this issue got hardly any traction. It could be interesting for some users to avoid generating a schema, but for others, this might cause a significant regression.

We'll settle with "this is just how jOOQ works by default". By default, we're assuming the entire *database* is owned by the application, not just a schema. As such, multi schema setups are not uncommon, so the full qualification is useful.
