### ISSUE TITLE
jooq-codegen-maven should look into project dependencies for jdbc driver

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#2886]
Currently, even though my project depends on a jdbc driver (the jooq api needs it), I need to redefine the same dependency as part of the Maven Plugin Config.

This is redundant and easy the fix. I've done it in the Flyway Maven plugin, and it works great.

**Comment by lukaseder** [comment]
@axelfontaine : You're doing something similar in Flyway if I'm not mistaken. Does this still work on JDK 9 for you?

**Comment by axelfontaine** [comment]
@lukaseder JDK 9 support for Flyway is still WIP. I'll let you know.

**Comment by lukaseder** [comment]
Alright
