### ISSUE TITLE
jooq-codegen-maven should use a target directory relative to the module

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#2887]
Currently the directory specified as target is relative to the reactor. This is ok if all you have is a single module. In a multi-module build it is confusing, as it is relative to the parent module and not the module itself.

The workaround is to specify an absolute path. This is not obvious as the examples on the website use a relative one.

**Comment by lukaseder** [comment]
Hmm, running into this problem time and again (see e.g. #8335, #8336). Is there a more generic way to handle this, @axelfontaine ? Ideally, the working directory would be changed for every maven plugin, but that seems a bit dangerous as Maven might make 1-2 assumptions about the working directory itself (and perhaps it's not even possible).

**Comment by lukaseder** [comment]
I guess a thorough solution would be to make it configurable with sensible defaults: #8337
