### ISSUE TITLE
jooq-codegen-maven configuration elements lack documentation

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#2888]
IntelliJ provides very nice javadoc-like popovers with the docs about Maven plugin configuration properties. This is a big help as you don't have to go back and forth between the ide and some external documentation source.

This doc is currently missing. It is trivial to add and greatly enhances the experience.

**Comment by lukaseder** [comment]
In fact, the suggestion made on Dec 11, 2013 (https://github.com/jOOQ/jOOQ/issues/2888#issuecomment-30315723) won't help much, as jOOQ only has two elements declared at that level. Nested elements are not described in that plugin.xml.

I agree that it would be nice if there were better tooling, but I currently don't know how to do it. I'll close this issue for the time being. We can reopen it, if there's an easy solution.
