### ISSUE TITLE
Add aliases for Java types to Conversions.scala

### ISSUE THREAD

**Issue by alexeyr** [jOOQ/jOOQ#2927]
One issue with using jOOQ from Scala is that, e.g. `Short` in Scala code refers to Java `short`, not to `java.lang.Short`. So I end up either writing `java.lang.Short` explicitly (ugly!) or defining aliases

```
type JShort = java.lang.Short
type JInt = java.lang.Integer // not strictly necessary, just for consistency
... // same for other primitives
type JBigInteger = java.lang.BigInteger
type JBigDecimal = java.lang.BigDecimal
```

and importing them everywhere. So it would be nice to have them in Conversions.scala by default.

**Comment by lukaseder** [comment]
I don't recall any similar requests in the past years. It does, however, seem like quite a bit of work to get right. I'd rather not do this.
