### ISSUE TITLE
Application hanging upon loadCSV call

### ISSUE THREAD

**Issue by Gaffney** [jOOQ/jOOQ#2941]
Freezes when I am executing from an external thread that is receiving its connections from a connection pool (BoneCP).

```java
    public run() {
         ...
          Stopwatch sw = Stopwatch.createStarted();
          {
            DSLContext create = Connect.newDSLContext(connection);
            readCsvIntoTable(create, reader);
          }
          long elapsed = sw.stop().elapsed(MILLISECONDS);
    
          if (_log.isInfoEnabled()) {
            _log.info(format(Messages.INF_TIME_TO_PROCESS_MS, elapsed, csv.getName()));
          }
        ...
     }
```

Relevant code from "readCsvIntoTable":

```java
     create.loadInto(table).loadCSV(csvReader).fields(table.fields()).execute();
```

2014-01-12 07:13:10 INFO  FileLoader:79 - Took 177113ms to process file File.csv

Note that without multithreading and reusing connections from the connection pool, this same code takes < 100ms.

**Comment by lukaseder** [comment]
We now have #2664 for batch execution and #3975 for bulk insertion with the loader API. Obviously, native database support for data loading will always outperform passing via jOOQ and JDBC, but I think the batch and bulk execution modes already help a lot.

I'm closing this issue for now, as I don't see any further way to improve the speed of the loader API. We can create new issues in the future, should these measures be insufficient.
