### ISSUE TITLE
Unsigned BigInt Doesn't Fit into Long, but jOOQ Correlates Them

### ISSUE THREAD

**Issue by dacc** [jOOQ/jOOQ#3]
We have a lot of unsigned bigint columns in our database, and use String to store their values in Java, because there is no "primitive" numeric type large enough to hold them.  I noticed that the jOOQ code generator treats unsigned bigint as Long, but this will probably cause value overflows and other unexpected behavior at extreme values.

**Comment by ebrandsberg** [comment]
More information on this topic at:  http://www.jooq.org/doc/3.0/manual/reference/reference-data-types/data-types-unsigned/ in relation to how JOOQ deals with this topic.
