### ISSUE TITLE
Add <outputSchemaToDefault/> to support "default schemas" during code generation

### ISSUE THREAD

**Issue by Nic0w** [jOOQ/jOOQ#3018]
When leaving empty the property "outputSchema" (ie `<outputSchema></outputSchema>` ) in JOOq Code Generator config file, the generated code defaults to "DefaultSchema" and schema "" (empty String) is hardcoded as a result, which makes the code more "portable". It is a feature but I can't find anymore where I found this information...
The problem is, when used in a pom.xml with Maven, the code generator simply ignore the empty outputSchema and reuse the inputSchema instead of defaulting to "" (empty String)

**Comment by oleg-smith** [comment]
@lukaseder Could you add the final option name to docs, please? 

It takes a while to figure working config which is `<outputSchemaToDefault>true</outputSchemaToDefault>`

**Comment by lukaseder** [comment]
@oleg-smith: Thank you very much for your suggestion.

We've recently improved this part of the manual for the manual version number 3.9:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-catalog-and-schema-mapping

Maybe, you were looking at a different version of the manual. Do you think that would have helped? Or can we improve this in another way?

**Comment by shreyabaid007** [comment]
> @oleg-smith: Thank you very much for your suggestion.
> 
> We've recently improved this part of the manual for the manual version number 3.9:
> https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-catalog-and-schema-mapping
> 
> Maybe, you were looking at a different version of the manual. Do you think that would have helped? Or can we improve this in another way?

Is this deprecated for jooq version 3.12? Because jooq codegen is unable to convert enums

**Comment by lukaseder** [comment]
> Is this deprecated for jooq version 3.12? Because jooq codegen is unable to convert enums

May I ask you to report a new bug? https://github.com/jOOQ/jOOQ/issues/new/choose

**Comment by shreyabaid007** [comment]
> > Is this deprecated for jooq version 3.12? Because jooq codegen is unable to convert enums
> 
> May I ask you to report a new bug? https://github.com/jOOQ/jOOQ/issues/new/choose

Done!
