### ISSUE TITLE
INSERT .. RETURNING does not return any value in H2, when no AUTO_INCREMENT column is involved

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3035]
This might be more of a missing feature in H2, but H2 only returns "generated values" when a record is inserted into a table with an `AUTO_INCREMENT` column.

jOOQ's (and PostgreSQL's) understanding of `INSERT .. RETURNING` should _always_ be able to return the inserted records.

**Comment by jhyot** [comment]
just wanted to let you know that we ran into this issue, and a fix / workaround in jooq would be great for us. For the moment we are doing a manual Select SEQUENCE.netxval() before an Insert to emulate the behaviour.

**Comment by lukaseder** [comment]
@jhyot: Thank you very much for your feedback. Indeed, this would be very desireable also for H2. Unfortunately, it is not yet entirely clear if this can be emulated at all.

On the flip side, manual sequence generation (as opposed to using triggers in Oracle) tends to be a lot faster as can be seen in this interesting post: https://oracle-base.com/articles/12c/identity-columns-in-oracle-12cr1. So, perhaps, this missing H2 feature is a good opportunity, depending on your use-case?

**Comment by jhyot** [comment]
Thanks for the link; that neatly summarizes our options, since (as you may know) we want to preserve interoperability of our code with H2 and Oracle.

Our options are:
* Use Sequences, and do a SELECT for the nextval before every INSERT. (slow because of additional network round trip).
* Use autoincrement on H2 and Trigger on Oracle; Trigger might be 10x slower as showed in your link but still faster than the network round trip.
* Use autoincrement on H2 and sequences on Oracle, until we can migrate to 12c. This would be ideal if jOOQ can abstract the different ID generating mechanisms away? I'm not sure if that's possible?

**Comment by lukaseder** [comment]
> since (as you may know) we want to preserve interoperability of our code with H2 and Oracle.

Yes, I know :)

> Use Sequences, and do a SELECT for the nextval before every INSERT. (slow because of additional network round trip).

Indeed, and that would be a nice use-case for PL/SQL :) Otherwise, if you're inserting more than one row, pre-fetching a set of sequence values in one go and bulk / batch inserting the rows in one go again might help greatly

> Use autoincrement on H2 and Trigger on Oracle; Trigger might be 10x slower as showed in your link but still faster than the network round trip.

That's true. Probably the best solution right now.

> Use autoincrement on H2 and sequences on Oracle, until we can migrate to 12c. This would be ideal if jOOQ can abstract the different ID generating mechanisms away? I'm not sure if that's possible?

Yes, with jOOQ 3.9, Oracle 12c IDENTITY columns will be supported: https://github.com/jOOQ/jOOQ/issues/3146. Both H2's `autoincrement` and Oracle's `IDENTITY` columns are modeled using jOOQ's `Identity` meta information.

**Comment by lbednarski** [comment]
I still have exactly the same problem. Has this been repaired or it's not possible?

**Comment by lukaseder** [comment]
@lbednarski No, the issue is still open

**Comment by bitbrain** [comment]
This exact issue just bit me. I hope it gets fixed soon.

**Comment by lukaseder** [comment]
Thanks for the comment, @bitbrain. I have requested a new feature in H2 to solve this more thoroughly: https://github.com/h2database/h2database/issues/1847

Since the table has no identity (`auto_increment` column), we can probably assume that clients are responsible for defining the primary key, so we could refresh all the inserted rows by running another query that filters on the previously inserted primary keys. That's not so different from what jOOQ currently does in other databases. I will investigate. (This thought simply hadn't occurred to me before)

**Comment by lukaseder** [comment]
Indeed, a first draft seems to indicate that in the presence of primary key meta data but in the absence of identity meta data, we can:

- Attempt to fetch all rows for the previously inserted primary key values on `INSERT .. VALUES` statements
- Repeat the `SELECT` statement in case of an `INSERT .. SELECT` statement
- Attempt to fetch all previously updated rows by repeating the `WHERE` clause of the `UPDATE` statement (and possibly `ORDER BY` and `LIMIT`)
- Attempt to run a `SELECT` statement prior to a `DELETE` statement, pre-fetching all the rows that are about to be deleted

This kind of workaround might improve the current support for `RETURNING` on a variety of RDBMS that do not have native support, especially for `UPDATE .. RETURNING` and `DELETE .. RETURNING`.

Of course, without native support, the transactional implications are a bit brittle here. There are possible race conditions, depending on the transaction isolation level, if we have to run several statements. But that's already the case with a variety of other `RETURNING` emulations.

I will continue investigating this.

**Comment by bitbrain** [comment]
> This kind of workaround might improve the current support for RETURNING on a variety of RDBMS that do not have native support, especially for UPDATE .. RETURNING and DELETE .. RETURNING.

@lukaseder I think in any case we can improve JOOQ - if an operation is not supported by the underlying database (e.g. H2) **AND** JOOQ does not have a fallback logic available, JOOQ should throw an exception in my opinion. In the case of `INSERT .. RETURNING`, JOOQ remains silent and I have no idea what's going wrong (unless I enable debug logging).

**Comment by lukaseder** [comment]
@bitbrain I agree in this case.

**Comment by katzyn** [comment]
In H2 1.4.200 behavior of `Statement.getGeneratedKeys()` was changed, it returns results compatible with `SELECT <columns> FROM FINAL TABLE (command)`. Column list is constructed from the specified names or indexes, or is determined automatically as described in Javadoc of `org.h2.jdbc.JdbcStatement.getGeneratedKeys()`. I think this issue could be resolved with that change.

**Comment by LouizFC** [comment]
@lukaseder any news on this one? sorry for pinging, but I have a issue on a internal project that have this one as a dependency

**Comment by lukaseder** [comment]
Thanks for the ping, @LouizFC. It appears that indeed, we can now fix this in the absence of an `IDENTITY` column. You can, already, by specifying it to the code generator via `<syntheticIdentities/>`:
https://www.jooq.org/doc/3.13/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-synthetic-identities

I'll look into a fix.

**Comment by lukaseder** [comment]
Fixed in 3.14.0. Backport scheduled for 3.13.2 (#9949)

**Comment by lukaseder** [comment]
This fix leads to a few regressions in other SQL dialects. It's not that easy.

**Comment by lukaseder** [comment]
Perhaps, this will all be much easier if we supported H2's data change delta table: #9676

**Comment by katzyn** [comment]
`getGeneratedKeys()` in H2 1.4.200 returns the same values as `FINAL TABLE`, but it shouldn't be affected by a bug in implementation of data change delta tables.

But you need to pass names or ordinal numbers of all required columns to H2, otherwise list of columns to return will be determined automatically based on properties of columns.

**Comment by lukaseder** [comment]
I prefer to implement this directly using the data change delta table. A lot of jOOQ's internals get *much* easier when we don't have to call `getGeneratedKeys()` anymore for a given dialect. Besides, the generated SQL can be used outside of jOOQ as well, e.g. in https://www.jooq.org/translate

**Comment by LouizFC** [comment]
Thanks for the hard work of both of you. If there is something I can do, just ping me. (But I doubt there is something I can do for a SQL Guru and for a H2 maintainer)

**Comment by lukaseder** [comment]
When H2's data change delta table will be supported natively (https://github.com/jOOQ/jOOQ/issues/9676), this issue here will go away. In the meantime, there are workarounds using `<syntheticIdentities/>` or #10400.

**Comment by lukaseder** [comment]
Closing this as won't fix, in favour of data change delta table (#9676)

**Comment by lukaseder** [comment]
I can confirm the currently ignored integration test now works on H2 2.0.202 when we implement `RETURNING` using data change delta tables (#9676)
