### ISSUE TITLE
Distribute commercial jOOQ artifacts under a different groupId to avoid conflicts

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3073]
> classifier:
The classifier allows to distinguish artifacts that were built from the same POM but differ in their content. It is some optional and arbitrary string that - if present - is appended to the artifact name just after the version number.
> As a motivation for this element, consider for example a project that offers an artifact targeting JRE 1.5 but at the same time also an artifact that still supports JRE 1.4. The first artifact could be equipped with the classifier jdk15 and the second one with jdk14 such that clients can choose which one to use.
>
> Another common use case for classifiers is the need to attach secondary artifacts to the project's main artifact. If you browse the Maven central repository, you will notice that the classifiers sources and javadoc are used to deploy the project source code and API docs along with the packaged class files.

Taken from:
http://maven.apache.org/pom.html

This was suggested by @jonnybbb

Instead of using classifiers (which may be rejected by some repositories) we should simply change the `groupId` from `org.jooq` to `org.jooq.[distribution]` where `[distribution]` is any of:

- `trial`
- `pro`
- `pro-java-6`

**Comment by lukaseder** [comment]
Instead of using classifiers (which may be rejected by some repositories) we should simply change the `groupId` from `org.jooq` to `com.datageekery.jooq.[distribution]` where `[distribution]` is any of:

- `trial`
- `pro`
- `pro-java-6`

**Comment by jonnybbb** [comment]
Great, looking forward to it!

**Comment by lukaseder** [comment]
Yeah, it was so simple... :-/ Interesting feedback from another customer: Classifiers are not accepted by some Nexus configurations. But changing the `groupId` is really a trivial, non-intrusive way to publish all the artifacts in different styles.

If the diff is not too big, we're going to re-release all versions under the new `groupId`
