### ISSUE TITLE
ResultQuery.fetchInto() doesn't work with Scala case classes

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3088]
jOOQ should be able to map `Records` onto Scala case classes:

``` scala
  test("MapCaseClass") {
    val books1 =
    dsl().select(T_BOOK.ID, T_BOOK.AUTHOR_ID, T_BOOK.TITLE)
         .from(T_BOOK)
         .orderBy(T_BOOK.ID asc)
         .fetchInto(classOf[BookCase])

    assert(4 == books1.size());
    assert(BookCase(1, 1, "1984")         == books1.get(0));
    assert(BookCase(2, 1, "Animal Farm")  == books1.get(1));
    assert(BookCase(3, 2, "O Alquimista") == books1.get(2));
    assert(BookCase(4, 2, "Brida")        == books1.get(3));

    val books2 =
    dsl().select()
         .from(T_BOOK)
         .orderBy(T_BOOK.ID asc)
         .fetchInto(classOf[BookCaseWithConstructorProperties])

    assert(4 == books2.size());
    assert(BookCaseWithConstructorProperties(1, 1, "1984")         == books2.get(0));
    assert(BookCaseWithConstructorProperties(2, 1, "Animal Farm")  == books2.get(1));
    assert(BookCaseWithConstructorProperties(3, 2, "O Alquimista") == books2.get(2));
    assert(BookCaseWithConstructorProperties(4, 2, "Brida")        == books2.get(3));
  }
```

with

``` scala
case class BookCase(
  id: Int,
  authorId: Int,
  title: String)

case class BookCaseWithConstructorProperties @ConstructorProperties(Array("id", "authorId", "title")) (
  id: Int,
  authorId: Int,
  title: String)
```

---

See also this thread:
https://groups.google.com/forum/#!topic/jooq-user/IQ4j8glws9s

**Comment by oleg-smith** [comment]
@lukaseder Looks like, mapping to case classes works only by index, not by field name - which is unexpected.

In my test I changed field positions and it did not work, though it did work when columns and fields had the same order.

**Comment by lukaseder** [comment]
Thank you for your comment, @oleg-smith. It may be unexpected to you at first, but it makes perfect sense when you think of it in a broader SQL context. When you write a union, for instance:

```sql
SELECT a, b, c FROM t
UNION
SELECT c, a, x FROM u
```

Then this works perfectly, even if the two union subqueries produce entirely distinct sets of column names. The union is performed based on column indexes. In the same way, `fetchInto()`, when working with an immutable "POJO" (case class in scala), it passes arguments in the order of definition, not by their name.

If you had a mutable "POJO" (as in Java, with getters and setters) and a default constructor, then the names are used.

This is consistent with SQL, and in fact, it is the only possibility in Java, because argument names are not retained by the JVM. There's no reliable way to introspect argument names through reflection, *except* if there's an annotation like `@ConstructorProperties` available (see my original code examples above).

I hope this helps

**Comment by oleg-smith** [comment]
Thank you for your response, Lukas. 

I disagree - union column name set is defined by first select and it can be mapped by name to case class.

I don't think your analogy with this union makes it impossible to implement - say, we have 2 sets of column names (from sql and from case class), but case class requires it to be ordered to put to constructor. 

We can reorder sql columns to match case class constructor order.

There is a way to get case class fields in order of declaration https://stackoverflow.com/questions/16079113/scala-2-10-reflection-how-do-i-extract-the-field-values-from-a-case-class/16079804#16079804

**Comment by lukaseder** [comment]
It was just an analogy and as every analogy, [it lends to discussing the analogy instead of the real thing](https://twitter.com/lukaseder/status/880003993946251265) :)

Anyway, I still think it's a useful analogy to show that sometimes, matching of tuple types, e.g. *among union subselects* is done by index, not by name. Do note there's also `UNION CORRESPONDING` in the SQL standard, which overrides the matching-by-index behaviour to prefer a matching-by-name behaviour. (I'm not aware of any implementations, though).

Likewise, the default behaviour when constructing a case class is also matching-by-index, not by-name:

```scala
MyCaseClass(1, 2, 3)
```

Obviously, because we don't have any names available. We could even say that matching between SQL queries and jOOQ `Record[N]` types can *by default* only be reasonably done by index, not by name, because SQL allows for duplicate column names.

In any case, if you still disagree with the current `DefaultRecordMapper` implementation, you can easily override it by providing an alternative SPI implementation as documented here: https://www.jooq.org/doc/latest/manual/sql-execution/fetching/pojos-with-recordmapper-provider

This would override all calls to different `into(Class)` methods.

> There is a way to get case class fields in order of declaration 

jOOQ is a Java library, we don't have access to Scala reflection tools, and we're not planning to do this in the near future (otherwise, we'll need to support Kotlin, Ceylon, etc. reflection tools as well)

Having said so, if there's a low hanging fruit that would simplify your life within what's possible with standard JDK API, I'm more than happy to discuss it!

**Comment by oleg-smith** [comment]
Got it, thanks!

**Comment by 419928194516** [comment]
Just leaving this here for anyone who might need it when facing this issue.

First, a way to map Record[N] into a Tuple[N]

```scala
object Tuples {
  private[this] val ctors = {
    import java.lang.reflect.Constructor
    val ab = scala.Array.newBuilder[Constructor[_]]
    for (i <- 1 to 22) {
      val tupleClass = Class.forName("scala.Tuple" + i)
      ab += tupleClass.getConstructors.apply(0)
    }
    ab.result()
  }
  def from(elems: scala.Array[AnyRef]): Product = elems.length match {
    case size if size <= 22 => ctors(size - 1).newInstance(elems: _*).asInstanceOf[Product]
    case _ => throw new Exception("Can't construct Tuple of size > 22")
  }
}
// usage:
  DSL
      using(con,SQLDialect.MYSQL)
      fetch(sql)
      map(r => Tuples.from(r.intoArray))
      map({ case (a,b,c,d,e,f,g,h,i) => (a,b,c,d) })
      mkString(",\n")
```
mapping positional query into positional case class

```scala
  import scala.reflect.runtime.universe._
  def intoCaseByPos[T: TypeTag](r: org.jooq.Record):T = {
    val ctor = typeTag[T].mirror.runtimeClass(typeOf[T]).getConstructors.head
    ctor.newInstance(r.intoArray: _*).asInstanceOf[T]
  }
// usage
  DSL
      using(con,SQLDialect.MYSQL)
      fetch(sql)
      map(intoCaseByPos[YourCaseClass] _)
      mkString(",\n")
```

and by name
```scala
  import scala.reflect.runtime.universe._
  def intoCaseByName[T: TypeTag](r: org.jooq.Record):T = {
    val ctor = typeTag[T].mirror.runtimeClass(typeOf[T]).getConstructors.head
    val params = typeOf[T].decl(termNames.CONSTRUCTOR)
      .asMethod.paramLists.flatten.map { sym => sym.name.toString }.toArray
    ctor.newInstance(params.map { name => r.getValue(name) } : _*).asInstanceOf[T]
  }
// usage
  DSL
      using(con,SQLDialect.MYSQL)
      fetch(sql)
      map(intoCaseByName[YourCaseClass] _)
      mkString(",\n")
```
