### ISSUE TITLE
Provide a clear comparison of Records vs DAOs + POJOs

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#3089]
From the manual it is not immediately clear in which situations one should go for one option over the other.

A two column comparison would be ideal here. Many subtle aspects (keeping track of changes, ...) are different from what many users have been accustomed to in a JPA world.

Also a general recommendation for the right type of access for various types of applications, including the complexity & performance implications of the choice.

**Comment by lukaseder** [comment]
Postponing this until we know what we'll do with these DAOs (#5984)

**Comment by lukaseder** [comment]
While there is always room for improvement in documenting things, this issue has not been seeing a lot of traction, neither on the issue itself, nor elsewhere.

On the deprecation discussion (#5984), people have shown a vast array of expectations towards maintaining DAO functionality, a lot of which we would not have thought of ourselves. DAOs are what they are. Simple per-table `Record` to POJO mapping and fetching auxiliary utilities with a very limited feature set.

The have a single section in the very big jOOQ manual, which shows they're absolutely not important, and most people can ignore them safely.

I don't think we need to state our vision here much more clearly.
