### ISSUE TITLE
Generate Table.fetchOne(Configuration, T1, T2, ..., T[N]) methods to fetch UpdatableRecord by primary key

### ISSUE THREAD

**Issue by thiloplanz** [jOOQ/jOOQ#3118]
jOOQ knows what the primary key for the table is, so it would be nice to have a method to fetch a TableRecord by primary key value (instead of having to write the WHERE clause ourselves).

Something like

```
 MyTableRecord record = context.selectByPrimaryKey(MyTable.MYTABLE, 1234);
```

This method would support composite primary keys by using varargs. Order of values has to match column order defined in primary key.

**Comment by lukaseder** [comment]
These little conveniences don't scale well, and we have so many already. The title doesn't sound like something that we'll be using very often. Rejected.
