### ISSUE TITLE
Add Queries DSLContext.ddl(Schema), ddl(Table) and others to re-generate known artefacts

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3160]
Given all the known meta information jOOQ has from the code generator, test databases could be generated using

```java
Queries queries = ctx.ddl(mySchema);
```

----
See also:
http://stackoverflow.com/q/22729855/521799

**Comment by lukaseder** [comment]
We don't have enough DDL support yet to implement this correctly

**Comment by oleg-smith** [comment]
@lukaseder could you tell how to make generator reflect auto_incremented field? 3.9.1 does not do it for mysql table
`CREATE TABLE test
(
    id BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT
 )`

When I call jooq.ddl(TEST) it does not put AUTO_INCREMENTED clause as this is not included in the generated code.

**Comment by lukaseder** [comment]
@oleg-smith: Unfortunately, this currently isn't possible in jOOQ 3.9 due to a lack of meta data information in the generated model. It will be part of jOOQ 3.10:

- https://github.com/jOOQ/jOOQ/issues/6221
- https://github.com/jOOQ/jOOQ/issues/6222

A workaround would be to use a post-processor on the generated code, adding the `.identity(true)` call on the relevant data type definitions...
