### ISSUE TITLE
Add support for CTE (Common Table Expressions / WITH-clause) also for DML statements

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3174]
With #454, CTE (common table expressions) are finally supported in jOOQ 3.4. Some databases support CTE also for DML (`INSERT`, `UPDATE`, `DELETE`, `MERGE`). That should also be supported by jOOQ.

If a database supports CTE only with `SELECT` (or not at all), such CTE should be inlined wherever they're referenced.

----
See also:
- #3173 
- https://groups.google.com/forum/#!topic/jooq-user/tJW1ueJekSM

**Comment by kbalyasnikov** [comment]
Hi @lukaseder !

This issue is labeled as Fixed but I didn't find how to use CTE with DML in 3.7. Is it still work in progress?

**Comment by lukaseder** [comment]
Thanks for your enquiry, @kbalyasnikov. The idea of this issue is that you can prefix any DML statement with the `WITH` clause, as you did:

```sql
WITH ...
INSERT INTO
```

Putting DML statements as a source of CTE is not yet supported. See also: https://github.com/jOOQ/jOOQ/issues/4474

**Comment by kbalyasnikov** [comment]
Thanks, @lukaseder !
