### ISSUE TITLE
Let ResultQuery<R>, InsertResultStep<R>, UpdateResultStep<R>, DeleteResultStep<R> extend Fetchable<R>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3185]
There are currently only `fetch()` and `fetchOne()` methods, no convenience methods that allow for fetching single columns. These should be added.

Unfortunately, we need a new type that does not extend `Publisher<R>`, because the `Insert<R>`, `Update<R>`, `Delete<R>` types already extend `Publisher<Integer>`

---

As suggested by users here:
- https://groups.google.com/forum/#!topic/jooq-user/SLq4XUjSj_I
- https://groups.google.com/forum/#!topic/jooq-user/bdXmgXqBY6E

**Comment by alkemist** [comment]
Just as another datapoint, I found this after trying to work out why I could use a `deleteFrom` query as a `.in(«delete»)` predicate.

Looking forward to this feature.

**Comment by hepin1989** [comment]
MySQL

```
        return dslContext.deleteFrom(applications)
                .where(applications.ID.eq(ULong.valueOf(id)))
                .returning()
                .fetchOne()
                .into(ApplicationInfosService.ApplicationInfo.class);
```

give my NPE,

at least it should returning a null but not give me anaNPE.

**Comment by lukaseder** [comment]
@hepin1989 Thanks for your message. It *is* returning `null`, but from `fetchOne()`. If you want to avoid this problem, you can call `fetchOptional()` instead.

**Comment by lukaseder** [comment]
A new type `Fetchable<R>` will be introduced, which contains all of the convenience API and offers a single implementation for all subtypes in `AbstractFetchable<R>`, with only a few specialisations for `fetch()`, `fetchLazy()`, and `fetchMany()`

**Comment by lukaseder** [comment]
If we allow a backwards incompatible change where the `XResultStep<R>` no longer extends `X<R>` for `X<R> = Insert<R> | Update<R> | Delete<R>` (see #11720), then the type hierarchy can be improved and these `XResultStep<R>` types can extend `ResultQuery<R>` directly!

This is much better than introducing a new confusing `Fetchable<R>` type.
