### ISSUE TITLE
Add support for Binding (i.e. "Type Providers")

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3248]
There is a variety of vendor-specific data types that are hard to support in jOOQ. One example is the PostgreSQL JSON type (#2788), which could either be supported by hard-coding things into jOOQ's internals, or by abstracting the way:
- ... variables are rendered (e.g. `?` or `CAST(? AS VARCHAR)` or `?::json`)
- ... variables are inlined (e.g. `'A string''s life'`)
- ... variables are serialised (to `PreparedStatement`, `CallableStatement`, `SQLOutput`)
- ... variables are deserialised (from `ResultSet`, `CallableStatement`, `SQLInput`)

This abstraction could be very useful in the long run, as jOOQ's type support mechanism could be finally enhanced to accommodate all of these user-defined or vendor-specific types.

Furthermore, such `Binding` implementations could supersede the current `Converter` feature.

---

See also 
- #982 (GIS extensions)
- #2230 (INTERVAL types)
- #2788 (JSON types)
- #2710 (Unsound internal caching of DefaultDataType)
- https://groups.google.com/forum/#!topic/jooq-user/bQm9OuA59TE (`DATE WITHOUT TIMESTAMP` handling)

**Comment by facundofarias** [comment]
Can't find code samples of use of Type Providers.
Can you provide some? Specifically with the Postgresql JSON.
Thanks!

**Comment by facundofarias** [comment]
So, answering my question:
http://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings/
http://stackoverflow.com/questions/27044702/how-to-insert-a-updatable-record-with-json-column-in-postgresql-using-jooq

Thanks anyway.

**Comment by lukaseder** [comment]
@facundofarias : Yep, luckily for your use-case, the PostgreSQL/JSON integration is currently the only official example we have. We'll be adding more examples, soon

**Comment by austingandy** [comment]
@lukaseder digging up this pretty old post to see if any more official examples were ever added. I'm still only seeing the PostgreSQL/JSON integration in the docs, but would love to see a similar example for HSTORE.

**Comment by lukaseder** [comment]
@austingandy Why not use the out-of-the-box binding provided here: https://github.com/jOOQ/jOOQ/tree/main/jOOQ-postgres-extensions
