### ISSUE TITLE
Add JOIN convenience methods to DELETE and UPDATE statements

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3266]
MySQL (and probably some other databases) allows for using JOIN expressions in DELETE and UPDATE statements.

For API consistency reasons, and for improved convenience, it would be nice to have JOIN methods on these statements, delegating to `Table.join()`

---

See also:
- https://groups.google.com/forum/#!topic/jooq-user/MBYnGI3jV3Y
- #2464 
- #2579

**Comment by egmanoj** [comment]
@lukaseder Tried the `JOIN` syntax (example below) but the generated query is running afoul of MySQL.
The following query aims to delete all books of a particular author.

```java
dsl.delete(BOOK.join(AUTHOR).onKey()).where(AUTHOR.ID.eq(...)).execute()
```

This raises an exception.

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ... at line 1
```

**Comment by lukaseder** [comment]
Yes, I'm sorry, I misunderstood the MySQL syntax at some time (or confused it with PostgreSQL syntax). The syntax is really `DELETE [ tables ] FROM [ joins ] WHERE [ predicates]` and the `FROM` clause is the part. There is currently no easy way to force jOOQ to put that `[ tables ]` element at the right place.

Note there's a documented workaround here:
https://groups.google.com/forum/#!topic/jooq-user/MBYnGI3jV3Y

**Comment by charneykaye** [comment]
+1

**Comment by scadgek** [comment]
I suppose, there's no support for `USING` clause either? See example here: https://www.postgresql.org/docs/9.0/static/sql-delete.html#AEN64666

Posting this question here since is related to the issue as it's another way of doing joins in DELETE statements.

**Comment by lukaseder** [comment]
@scadgek: There's a separate feature request for PostgreSQL's `USING` clause: https://github.com/jOOQ/jOOQ/issues/4245

**Comment by leonids2019** [comment]
It's shame that this is not supported yet :(. you cannot really do a delete with join in MySQL.
For me that was really big surprise.

**Comment by leonids2019** [comment]
It is marked as an enhancement but this is really a bug.
.delete(T1.innerJoin(IDS).on(T1.ID.eq(IDS.ID)))
.execute();
generates incorrect statement in MySQL.

**Comment by mikymigs** [comment]
+1
The only alternative for the moment is to have a delete where with a subquery :'(

**Comment by viggin543** [comment]
+1

**Comment by lukaseder** [comment]
Thanks for your many upvotes, folks. I've increased the priority of this.

**Comment by jdmuriel** [comment]
+1

**Comment by morettilucas** [comment]
+1

**Comment by lukaseder** [comment]
I take that most people who upvote this are actually in need of a fix for `DELETE .. JOIN`, which I will address separately: https://github.com/jOOQ/jOOQ/issues/11924

The convenience methods are completely optional once that works, but it currently doesn't. `UPDATE .. JOIN` should work already.

**Comment by lukaseder** [comment]
Some progress report (I'll update this comment):

- https://github.com/jOOQ/jOOQ/issues/11924 is fixed for jOOQ 3.15.0 (`delete(T1.join(T2).on(...))` syntax for multi table `DELETE`)

**Comment by morettilucas** [comment]
+1

**Comment by lukaseder** [comment]
The title of this issue is about the `JOIN` convenience methods, which I won't implement. As some users have reported, using a `Table::join` in the `UPDATE` or `DELETE` statement should be possible now, as per this comment:
https://github.com/jOOQ/jOOQ/issues/3266#issuecomment-850267104

Other syntaxes have also been supported by now, including `FROM` or `USING` clauses. So, I think there's nothing left to do here.

**Comment by lukaseder** [comment]
Resolved as "won't fix", because the convenience syntax won't be added.
