### ISSUE TITLE
Let QueryPart extend Cloneable

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#327]

**Comment by garthgoodson** [comment]
This functionality would be really helpful.  There have been a number of times that I've wanted to clone a select query part way through building it, to do something slightly different than the original, but while keeping the original intact.

**Comment by lukaseder** [comment]
Oh interesting, there was once such an idea? Better close it as won't fix now. Here's why:

1. In jOOQ 4.0, we'll invest quite a bit of time refactoring most of the jOOQ API to become immutable. Having mutability in our API was an early design mistake, making a lot of things rather complicated now. With strictly immutable `QueryParts`, there will be no use-case for cloning them.
2. Even without immutability, a much more idiomatic (as of Java 8) way to reuse `QueryParts` is to resort to a more functional programming style. Here's an article we've written that explains this: https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq
