### ISSUE TITLE
Add support for CREATE and DROP DATABASE statements

### ISSUE THREAD

**Issue by ooxi** [jOOQ/jOOQ#3272]
Hi,

[this was asked before](https://groups.google.com/forum/#!topic/jooq-user/HrHLY3UhqGg) and you (@lukaseder) stated that `create database` etc. support is on the JOOQ roadmap. Since the thread is quite old I wanted to ask whether or nor JOOQ currently contains support for `create database` or `show` statements?

-- ooxi

**Comment by lukaseder** [comment]
I'm postponing this feature request for now. `CREATE DATABASE` would first require more standardised `org.jooq.Catalog` support in jOOQ. However, it is currently not very clear at what level we should really do support catalogs. Few databases support them, and some confuse databases / catalogs with schemas...

**Comment by lukaseder** [comment]
I'm implementing `CREATE DATABASE` support now via: #10210. `CREATE SCHEMA` support has been added a while ago, which translates to `CREATE DATABASE` in MySQL, for example.
