### ISSUE TITLE
Expose a new Log SPI, which can be implemented by popular loggers

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3280]
The current `JooqLogger` picks up whatever logger it finds first on the classpath in this order:
- slf4j
- log4j
- java.util.logging

What's missing here is the Maven logger, or whatever other logger users may prefer. It would be better to provide a new `Log` SPI similar to that of Maven (`org.apache.maven.plugin.logging.Log`), which can be implemented by users. This would also allow to improve logging of the jOOQ code generator through Maven, as the Maven plugin would also be able to pass a new implementation of this SPI to jOOQ.

---

See also #3274

**Comment by HansiJanosch** [comment]
Would be great if this could not be moved further to the future. Or maybe log4j2 could be added in the meantime.

**Comment by lukaseder** [comment]
@HansiJanosch: Yes indeed, this would be a great feature, but it currently isn't our top priority. Note that you can always use slf4j to bridge to your preferred log4j version already today.

**Comment by lukaseder** [comment]
Won't fix in favour of #7643
