### ISSUE TITLE
ForcedType doesn't apply to PostgreSQL ARRAY types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3310]
There is currently no way of rewriting PostgreSQL ARRAY types with converters, e.g. to lists: from `INTEGER[]` to `List<Integer>`. jOOQ-Meta's internals do not keep track of the proper types at all times, some major refactorings will be needed to implement this in jOOQ 3.5

----
See also:
http://stackoverflow.com/q/23993065/521799

**Comment by lightoze** [comment]
Any chance it will be implemented in 3.8?

**Comment by lukaseder** [comment]
Hmm, I'll need to review if the problem still exists in the way it did at the time. I'm not sure if `Converters` can be made to work here, but data type `Bindings` might. Will look into this and provide feedback soon, hopefully.

**Comment by lukaseder** [comment]
(of course, any input on how you'd like to use this, and what you've tried thus far might help give the right direction!)

**Comment by lightoze** [comment]
I remember that I had presumably this problem for 3.6. I had a type with custom binding and I failed to make arrays of that type to work.

**Comment by lukaseder** [comment]
OK, I will re-iterate the issue, but I cannot make any promises. At the time I opened this issue, it would have been rather hard to do because of jOOQ-meta's inner workings (and technical debts)

**Comment by lukaseder** [comment]
This is in fact also a duplicate of #4388
