### ISSUE TITLE
Support the SQL standard array_agg function

### ISSUE THREAD

**Issue by mkscrg** [jOOQ/jOOQ#3329]
As far as I can tell, jOOQ doesn't support Postgres's `array_agg` function. It would be a nice way to deal with simple one-to-many relationships, without having to deal with reconciling multiple records post-fetch.

Does this exist and I'm missing it? Or can you suggest a workaround to use it with generated table definitions?

For clarity's sake, I'm thinking of code that looks like this:

    List<Foo> foos = DSL.using(config).select(FOO.id, FOO.name, arrayAgg(BAR.id))
            .from(FOO.join(BAR).on(FOO.id.eq(BAR.fooId)))
            .fetch(fooMapper);

**Comment by lukaseder** [comment]
In Oracle, this can be implemented using `COLLECT()` (http://www.oracle-developer.net/display.php?id=306, #648)
