### ISSUE TITLE
Regression? "Not Null" constraint violation with PSQL 8.4 and DSLContext#newRecord(Table<R> t, Object o) and JOOQ 3.4

### ISSUE THREAD

**Issue by schleinzer** [jOOQ/jOOQ#3380]
The following code only works with the commented line enabled, while it worked flawlessly with JOOQ 3.1.0 and w/o that line.

```java
UpdatableRecord rec = dsl.newRecord(table, pojo);
rec.reset("id"); // only required in 3.4.0
rec.store();
```

I guess, JOOQ should never copy a "null" field from a pojo to a record field marked as a primary key and/or "defaulted".

**Comment by lukaseder** [comment]
This has been fixed in jOOQ 3.5 via #3582
