### ISSUE TITLE
NOT NULL constraints and type information are incorrectly generated when using Firebird DOMAINs for data types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3382]
When using this DDL:

``` sql
CREATE TABLE BUPDATERLINKS (
    IDBUPDATERLINKS  IDENT /* IDENT = VARCHAR(22) NOT NULL */,
    BULREFPARENT     REFERENCE /* REFERENCE = VARCHAR(22) DEFAULT '-1' */,
    BULTYPE          ENTIER /* ENTIER = INTEGER DEFAULT 0 */,
    BULREFBYTYPE     REFERENCE /* REFERENCE = VARCHAR(22) DEFAULT '-1' */,
    BULDEST          LIB500 /* LIB500 = VARCHAR(500) */,
    BULJSON          BLOBTEXT /* BLOBTEXT = BLOB SUB_TYPE 1 SEGMENT SIZE 80 */,
    BULSTATE         ENTIER /* ENTIER = INTEGER DEFAULT 0 */,
    BULDATEACTION    DATECOMPLETE /* DATECOMPLETE = TIMESTAMP */,
    BULACTIF         ENTIER /* ENTIER = INTEGER DEFAULT 0 */,
    FTPDATE          DATECOMPLETE2 /* DATECOMPLETE2 = TIMESTAMP DEFAULT 'now' NOT NULL */,
    CREATEDATE       DATECOMPLETE2 /* DATECOMPLETE2 = TIMESTAMP DEFAULT 'now' NOT NULL */
);
```

... where `IDENT` etc. are domains, then the jOOQ code generator does not correctly pick up the data types and the constraints. E.g. for `IDBUPDATERLINKS`, it generates:

``` java
jooq.impl.SQLDataType.VARCHAR.length(88)
```

instead of

``` java
jooq.impl.SQLDataType.VARCHAR.length(22).nullable(false)
```

---

See also:
https://groups.google.com/forum/#!topic/jooq-user/m2TbAfbQ87c

**Comment by JDI-Developers** [comment]
I seem to have the near-identical issue with PostgreSQL as well.
On the latest version (3.17.7)

Consider the following DDL:

```sql
CREATE DOMAIN MYDOMAIN AS CHAR(2);

CREATE TABLE EXAMPLE (
  TEST MYDOMAIN NOT NULL
);
```
The datatype that is generated for the column `TEST` is:
`Domains.MYDOMAIN.getDataType()`
instead of the expected:
`Domains.MYDOMAIN.getDataType().nullable(false)`

**Comment by lukaseder** [comment]
Thanks for your comment, @JDI-Developers. This issue was about generating the type information on the column itself, not on the domain. Domain support was added much later. I've created a new issue to validate that the constraint information is going to be generated on both the column and the domain: https://github.com/jOOQ/jOOQ/issues/14617

**Comment by lukaseder** [comment]
Well, #14617 doesn't reproduce. Non-nullable domains are generated correctly. But I get it. You reported something quite different. The domain type is nullable, but you override this on the referencing table directly: https://github.com/jOOQ/jOOQ/issues/14618

**Comment by lukaseder** [comment]
Same issue with `DEFAULT` expressions: https://github.com/jOOQ/jOOQ/issues/14628

**Comment by JDI-Developers** [comment]
> Well, #14617 doesn't reproduce. Non-nullable domains are generated correctly. But I get it. You reported something quite different. The domain type is nullable, but you override this on the referencing table directly: #14618

I had noticed that the domain information indeed gets lost, and put that in my workaround as well.
If the domain has a Nullability of `NOT NULL` then the table specification should not override the domain, because a `NULL` value on the table will still violate the domain check. (At least for Postgres)

```java
@Deprecated
@Override
protected String getTypeReference(Database db, SchemaDefinition schema, JavaWriter out, String t, int p, int s,
                                  int l, boolean n, boolean i, boolean r, String g, QOM.GenerationOption go,
                                  String ge, String d, Name u) {
    if (db.getDomain(schema, u) != null && !n) {
        String identifier = getStrategy().getFullJavaIdentifier(db.getDomain(schema, u));
        StringBuilder sb = new StringBuilder();
        sb.append("org.jooq.impl.Internal.createDomain(");
        sb.append(identifier);
        sb.append(".getSchema(), ");
        sb.append(identifier);
        sb.append(".getQualifiedName(), ");
        sb.append(identifier);
        sb.append(".getDataType().nullable(false), ");
        sb.append(identifier);
        sb.append(".getChecks().size() != 1 ? null : ");
        sb.append(identifier);
        sb.append(".getChecks().get(0)");
        sb.append(").getDataType()");
        return sb.toString();
    }
    return super.getTypeReference(db, schema, out, t, p, s, l, n, i, r, g, go, ge, d, u);
}
```

**Comment by lukaseder** [comment]
I'm not sure what you're saying. Is this the same problem? A new problem? A general remark?

If it's a new problem, may I ask you to create a new issue?
