### ISSUE TITLE
Avoid generating new SQL statements for every bind variable length in Firebird 3

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3398]
Because of #1727, jOOQ generates `CHAR` and `VARCHAR` lengths in bind variable `CAST` expressions for Firebird. This is causing issues when trying to use statement caching or batch statements.

jOOQ should generate more predictable SQL in non-edge-cases like simple `UPDATE` or `INSERT` statements.

Another side-effect of this is that `Settings.cacheParsingConnection` produces wrong results

---

See also:
- https://groups.google.com/forum/#!topic/jooq-user/MOfE-206QL4
- http://stackoverflow.com/q/42340848/521799
- #1749
- https://github.com/jOOQ/jOOQ/issues/1735
- #9992
- https://github.com/jOOQ/jOOQ/issues/12598

**Comment by mrotteveel** [comment]
Is there a way to avoid this for clob data types (`BLOB SUB_TYPE TEXT`)? I'm running into a problem where jOOQ is generating casts for a clob column, and I'm trying to reuse the `Query`, but that fails as jOOQ generates the cast based on the first bind, and this fails as subsequent values are longer.

**Comment by lukaseder** [comment]
@mrotteveel That looks like a different problem, would you mind opening a new issue with some help to reproduce the problem?

**Comment by mrotteveel** [comment]
@lukaseder Will do, might take a few days though.

**Comment by lukaseder** [comment]
Removing the value specific cast length doesn't produce any regressions in Firebird 3.0.4, and even fixes a bug when caching parsed and translated SQL: https://github.com/jOOQ/jOOQ/issues/12598, so I'm thinking to simply remove this logic from the `SQLDialect.FIREBIRD_3_0` dialect.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.16.0. The behaviour remains unmodified for `SQLDialect.FIREBIRD_2_5`, but has been removed from `SQLDialect.FIREBIRD_3_0`

**Comment by lukaseder** [comment]
This might be quite the change for existing applications, which have come to somehow rely on the previous casts, which is why I'm not backporting the fix.
