### ISSUE TITLE
Change DSL.sum(Field<? extends Number>) to DSL.sum(Field<?>)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3415]
Some databases allow for summing up boolean / bit values (with `false = 0`, `true = 1`). These don't map to `java.lang.Number`. We should relax type safety on the `sum()` function, then (probably on some others as well), and possibly return something other than `BigDecimal`

Tasks:

- [ ] Investigate what other API is strictly tied to `Number` and should be changed, too
- [ ] Investigate what API can be changed source-compatibly, and what changes are backwards incompatible

---

See also:
- http://stackoverflow.com/q/24784922/521799
- https://github.com/jOOQ/jOOQ/issues/10649
- https://github.com/jOOQ/jOOQ/issues/11088

**Comment by axelfontaine** [comment]
Until this is fixed, the deprecated `Field.sum()` method offers a workaround for #10649 by producing a record with a `BigDecimal` which can then be manually be converted again to the required type.

**Comment by lukaseder** [comment]
Thanks for the hint, @axelfontaine. I've created a new issue to look into this problem more thoroughly, as this is obviously not just about `DSL.sum()`. What would solve this thoroughly would be an incompatible change of all `Field<T>` types to `Field<T, U>`: https://github.com/jOOQ/jOOQ/issues/11088

If that were available, we could re-define `sum()` as:

```java
public static <T extends Number, U> AggregateFunction<T, U> sum(Field<T, U> field) { ... }
```

**Comment by lukaseder** [comment]
This has been a re-occuring problem, especially with some newer data types, such as:

- `java.time` types (a lot of API is `java.sql` type based)
- `JSON`, `JSONB`, `XML` types (where users might want to attach some JAXB/Jackson/Gson binding)
- Spatial types (where users might want to attach JTS bindings, etc.)

The only thorough solution I've come up with so far is #11088, which is a heavy breaking change, and probably causes additional complexity in client code with the added generics, but it might be worth pursuing in the future. Perhaps, I can eventually find a source compatible way to change this, or at least a way that doesn't break *everything*.

In any case, the workarounds are always simple, via plain SQL templating, and now we even have `DSL.aggregate()`, in case the usual `FILTER` and `OVER` DSL is required. I don't like patching individual functions because that misses the big picture. Today it's `sum()`, tomorrow it's `sumDistinct()`, then it's `trunc()`, `floor()`, etc.

Closing this as a duplicate of #11088
