### ISSUE TITLE
Add support for intercepting PreparedStatements, collecting individual bind value sets into larger batch sets

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3419]
In some cases, we can simply collect all JDBC statements into sets of batches like so:

``` java
// "Regular code":
// ---------------
module1.insertSomething(configuration);
module2.insertSomethingElse(configuration);

// The above might generate... (each line is a statement)
// INSERT INTO something (A, B) VALUES (?, ?)
// INSERT INTO something (A, B) VALUES (?, ?)
// INSERT INTO something (A, B) VALUES (?, ?)
// INSERT INTO something (A, B, C) VALUES (?, ?, ?)
// INSERT INTO something (A, B, C) VALUES (?, ?, ?)
// INSERT INTO something (A, B) VALUES (?, ?)
// INSERT INTO something_else (X, Y) VALUES (?, ?)
// INSERT INTO something_else (X, Y) VALUES (?, ?)
// INSERT INTO something_else (X, Y) VALUES (?, ?)

// "Batch-collecting code":
DSL.using(configuration).batch(ctx -> {
    module1.insertSomething(ctx);
    module2.insertSomethingElse(ctx);
});

// The above might now generate... (each line is a batch statement)
// INSERT INTO something (A, B) VALUES (?, ?)       -- With 3 calls to PreparedStatement.addBatch()
// INSERT INTO something (A, B, C) VALUES (?, ?, ?) -- With 2 calls to PreparedStatement.addBatch()
// INSERT INTO something (A, B) VALUES (?, ?)       -- With 1 calls to PreparedStatement.addBatch() or perhaps this won't generate a batch
// INSERT INTO something_else (X, Y) VALUES (?, ?)  -- With 2 calls to PreparedStatement.addBatch()
```

On a JDBC level, the rules are simple:

1. Each time a new SQL text is encountered, the previous batch (if any) is executed
2. Each time the same SQL text is encountered, the statement is not executed, but the bind values are collected
3. When the transaction ends or the connection closes, the last (unexecuted) batch is executed

---

See also:
- https://groups.google.com/forum/#!topic/jooq-user/RRAYf2OUO8U
- https://groups.google.com/d/msg/jooq-user/6P7vG7--tG0/zFH0l5PSBgAJ
- https://stackoverflow.com/q/64027819/521799

**Comment by lukaseder** [comment]
There are still a few caveats related to `INSERT .. RETURNING` (which cannot be batched) and a few other cases. Let's look at this once more.

**Comment by filpano** [comment]
Hi @lukaseder, I'm the person that created the SO post that you added to this issue. Although I'm sure it was in the works for a bit longer, I just saw that you updated the milestone of this issue several hours ago as well fixed it through commit `f491e8c`. I do hope that I influenced your decision to do so at this time, but I still want to give feedback on the simply *fantastic* level support that you're providing.

I look forward to upgrading to `3.14` and having a look at all the juicy new features!

**Comment by lukaseder** [comment]
Thanks for your nice words and for the feedback, @filpano. This issue has been dormant for a while. There was some buzz back in 2014, since then, there wasn't too much interest - but I've always wanted to implement this. After all, it isn't too difficult to do (the devil is in the details of properly buffering the more complex JDBC interaction patterns, of course).

Your feedback prior to releasing 3.14 would already be very helpful. In essence, what you probably want to do is wrap your JDBC `Connection` in a [`BatchedConnection`](https://github.com/jOOQ/jOOQ/blob/main/jOOQ/src/main/java/org/jooq/tools/jdbc/BatchedConnection.java) whenever that makes sense from a performance perspective.

Two caveats to keep in mind:

- As soon as we need to fetch generated IDs, batching no longer works, and statements are executed individually again. Keep this in mind when you plan to use `UpdatableRecord.store()` (you can turn off fetching generated IDs using `Settings.returnIdentityOnUpdatableRecord` as I've mentioned on SO as well. For completeness' sake, and if someone else reads this, let's repeat it here)
- You won't get any update counts as usual, when you use a `BatchedConnection`. I don't think there's any way we could fix this. This will affect `DEBUG` logs and the result of `UpdatableRecord.store()`

There are probably more, which I'll discover while writing integration tests. Most edge cases will arise from using the `BatchedConnection` directly, not necessarly from using it within jOOQ

**Comment by lukaseder** [comment]
More caveats will be discussed and addressed here: https://github.com/jOOQ/jOOQ/issues/10692
