### ISSUE TITLE
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" }) in the generated Keys.java broken with javac

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#3481]
`"all"` seems to be an Eclipse extension -> http://stackoverflow.com/questions/13729840/javac-ignoring-suppresswarningsall

IntelliJ uses javac by default. Adding all to the list, causes javac to ignore the remaining categories (unchecked, rawtypes) and still issue a warning. This then causes the messages tool window to open automatically in IntelliJ (quite annoying). Removing all from the list fixes this.

Tested with javac 1.7.0u55 on Win 8.1 x64 and jOOQ 3.4.1

**Comment by lukaseder** [comment]
I suspect this is no longer a problem in IntelliJ? It seems IntelliJ interprets Eclipse's `"all"` correctly now...
