### ISSUE TITLE
Add support for -> and ->> PostgreSQL operators in jOOQ-Scala

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3491]
PostgreSQL has a couple of operators to manipulate JSON values. We should allow for using them on jOOQ `Fields`

Probably, other sorts of operators could also be supported natively on jOOQ `Fields`

---

See also:
- http://stackoverflow.com/q/25068563/521799
- http://www.postgresql.org/docs/9.3/static/functions-json.html

**Comment by testark** [comment]
@lukaseder any progress on this?

**Comment by lukaseder** [comment]
No. In fact, it might not make sense to implement this in jOOQ, out of the box. I mean, which JSON library should we even bind to? :-/

**Comment by testark** [comment]
@lukaseder can't you just implement (`DSL.max()`, `DSL.min()`, etc...)-like operators?

**Comment by lukaseder** [comment]
I'm not sure if I understand...?
