### ISSUE TITLE
Add Javadoc links to classes inside manual code snippets

### ISSUE THREAD

**Issue by stevesims330** [jOOQ/jOOQ#3504]
For example, a link on the word "Factory" in the 2.x documentation at http://www.jooq.org/doc/3.2/manual/sql-execution/daos/#comment-1531328075 would go to Factory's JavaDoc.

**Comment by lukaseder** [comment]
We've added a few utilities to manual code-sections in the meantime, hidden behind a "show imports" button:

![image](https://github.com/jOOQ/jOOQ/assets/734593/cb15b35b-d01f-41c3-9cc8-a118dc52df61)

When clicked:

![image](https://github.com/jOOQ/jOOQ/assets/734593/9604b20d-f5dc-4fd6-974c-a44fb26ec119)
