### ISSUE TITLE
DSLContext.batch(String) doesn't accept bind variables

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3547]
Currently, it is not possible to bind and bind variables to a plain SQL batch statement that is created using the `DSLContext.batch(String)` convenience method:

``` java
// Doesn't work, the bind value 1 is not applied:
x.batch("insert into test values(?)").bind(1).execute();
```

Instead of applying a bind value of `1`, `null` is bound. This is because internally, jOOQ wraps the SQL string in a `SQLQuery`, and then extracts `Param` objects from that `SQLQuery` to convert them.

---

See also: http://stackoverflow.com/q/25277680/521799

**Comment by MikePryadko** [comment]
Hi @lukaseder ! If it fixed now could you describe how it works now, please? :upside_down_face:

**Comment by lukaseder** [comment]
@MikePryadko I could, but that has a chance of not actually helping you. Maybe, you ask a new, specific support request with examples of what doesn't work for you, instead? https://github.com/jOOQ/jOOQ/issues/new/choose
