### ISSUE TITLE
Add Setting to enable / disable fetching of warnings

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3558]
Apparently, some JDBC drivers issue a server-side round trip to actively get the warnings when `PreparedStatement.getWarnings()` is called. This was introduced with #3011 and #3076.

Sometimes, those warnings are really needed, but often they aren't. With a new Setting, we could generally prevent this unnecessary load on the server.

---

See also:
- https://groups.google.com/forum/#!topic/jooq-user/yKmq0ZYodq0
- #3011

**Comment by atul2512** [comment]
Hey,
what is the setting name to disable warning.I couldnot findout in any docs.
Thanks

**Comment by lukaseder** [comment]
@atul2512 It's `Settings.setFetchWarnings()`. Hope this helps
