### ISSUE TITLE
Emulate PostgreSQL's DISTINCT ON clause

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3564]
PostgreSQL supports the `DISTINCT ON` clause (#1410), which can be emulated in various ways in other databases:
- Using `GROUP BY` and `MAX()` (probably too complicated)
- Using `FIRST_VALUE() OVER()` ranking functions (probably doable, see https://github.com/jOOQ/jOOQ/issues/3564#issuecomment-529352017)

---

See also: http://stackoverflow.com/a/10515397/521799

**Comment by maxkremer** [comment]
+1

**Comment by lukaseder** [comment]
Thanks for the feedback, @maxkremer. In order to better understand the motivation, would you mind showing the kind of query that you're looking into writing here?

**Comment by maxkremer** [comment]
I want to use the postgresql `distinct on` functionality. For example:

```
         SELECT distinct on (A.person_id) A.person_id, O.session_id,  timestamp_ AS step_ts_min
	 FROM event_page O 
	 JOIN alias A ON (O.person_alias = A.alias)
	 WHERE O.timestamp_ between  '2016-11-03 16:01:20.35' and  '2017-01-02 16:01:20.35'  
	 ORDER BY A.person_id, timestamp_ asc
```

[postgres doc](https://www.postgresql.org/docs/9.5/static/sql-select.html#SQL-DISTINCT)

**Comment by maxkremer** [comment]
Bumped into this one again today. Anyway workaround to handle this @lukaseder  ?

**Comment by lukaseder** [comment]
Sure, you can emulate the clause, depending on your query. In your previous case (https://github.com/jOOQ/jOOQ/issues/3564#issuecomment-274882464), this could be written as:

```sql
SELECT person_id, session_id, timestamp_ AS step_ts_min
FROM (
  SELECT
    a.person_id,
    o.session_id,
    o.timestamp_,
    row_number() OVER (PARTITION BY a.person_id ORDER BY o.timestamp_asc) rn
  FROM event_page o
  JOIN alias a ON (o.person_alias = a.alias)
  WHERE o.timestamp_ between '2016-11-03 16:01:20.35' and  '2017-01-02 16:01:20.35'
) t
WHERE rn = 1
ORDER BY person_id, timestamp_
```

There are other ways to emulate this.

**Comment by lukaseder** [comment]
For the record (as others have asked about this emulation), while it can be done relatively easily manually, as in the previous examples, a generic emulation for all sorts of edge cases is far from trivial. This is why this hasn't been implemented yet.

**Comment by lukaseder** [comment]
I've just had another look at `DISTINCT ON` in the context of a blog post. It appears that the emulation is actually straightforward using `first_value()` and `last_value()` window functions. For example:

```sql
select distinct on (film_id) film_id, title, rental_date
from film
join inventory using (film_id)
join rental using (inventory_id)
order by film_id, rental_date desc
```

Seems equivalent to 

```sql
select distinct 
  film_id, 
  first_value(title) over w as title, 
  first_value(rental_date) over w as rental_date 
from film
join inventory using (film_id)
join rental using (inventory_id)
window w as (
  partition by film_id
  order by rental_date desc
  range between unbounded preceding and unbounded following
)
order by film_id, rental_date desc
```

The rule being:

- The columns `p` in `distinct on (p)` will be the window `partition`, and part of the projection
- The columns `o` in `order by o` will be the window `order` (the partition can be excluded, optionally)
- The complete range is needed in case we need `last_value`
- The columns `f` in the projection that are not in `p` will be projected as `first_value(f) over w`

**Comment by lukaseder** [comment]
There might be special cases I'm currently overlooking, but given how close the `window` operation and the `distinct` operation are in the logical order of operations (https://blog.jooq.org/2016/12/09/a-beginners-guide-to-the-true-order-of-sql-operations/), I cannot see too many caveats here, even if expressions are involved.

**Comment by lukaseder** [comment]
Intuitively, a caveat is when we use `DISTINCT ON` together with window functions. It appears that window functions are just placed into the query without being affected by this transformation. To be verified.

**Comment by katzyn** [comment]
BTW, H2 supports this clause too since 1.4.198, however, results in 1.4.198 are not compatible with PostgreSQL in presence of `ORDER BY` clause, this incompatibility was resolved in 1.4.199.

I don't know how it is implemented in PostgreSQL, but implementation in H2 is not related with window functions in any way and I don't see any good reason to use them for that purpose in the database internally.

**Comment by lukaseder** [comment]
Well, what can I say... Splendid! You've been very busy improving H2, have you? :)

> I don't know how it is implemented in PostgreSQL, but implementation in H2 is not related with window functions in any way and I don't see any good reason to use them for that purpose in the database internally.

Agreed, there are better ways to implement `DISTINCT ON` internally, than using window functions, although for jOOQ, the emulation is viable.

I personally don't like the `DISTINCT ON` syntax at all. It is very confusing for beginners. A much better approach is Oracle's `KEEP` syntax. The syntax is also very esoteric, but this kind of query should really be solved using ordinary aggregate functions: https://stackoverflow.com/a/57850685/521799

I've created a feature request for support of H2 `DISTINCT ON` in jOOQ: https://github.com/jOOQ/jOOQ/issues/9183

**Comment by katzyn** [comment]
From my point of view `DISTINCT ON` works in pretty clear way and this way can be easily guessed from its syntax. But PostgreSQL is very restrictive about it, in H2 requirements are much weaker.

**Comment by lukaseder** [comment]
I've had another look at this possible emulation. Since we're emulating `FOR XML` and `ROWNUM`, there has been some additional infrastructure for transforming a `Select` into an augmented derived table. A quick draft shows that the [`ROW_NUMBER()` based approach](https://github.com/jOOQ/jOOQ/issues/3564#issuecomment-340408401) could work just fine:

> ```sql
> SELECT person_id, session_id, timestamp_ AS step_ts_min
> FROM (
>   SELECT
>     a.person_id,
>     o.session_id,
>     o.timestamp_,
>     row_number() OVER (PARTITION BY a.person_id ORDER BY o.timestamp_asc) rn
>   FROM event_page o
>   JOIN alias a ON (o.person_alias = a.alias)
>   WHERE o.timestamp_ between '2016-11-03 16:01:20.35' and  '2017-01-02 16:01:20.35'
> ) t
> WHERE rn = 1
> ORDER BY person_id, timestamp_
> ```


Rules:

- Let S be the original `SELECT`
- Let T be a derived table based S with
  - No `DISTINCT ON` columns
  - No `ORDER BY` clause
  - An additional `RN` column defined as `ROW_NUMBER() OVER (PARTITION BY <distinct on> ORDER BY <order by>)`
- Substitute S by `SELECT qualify(T, S.select) FROM T WHERE RN = 1 ORDER BY unqualified(S.orderBy)`

Seems simple enough! Will cover with sufficient integration tests and ship with 3.14.

rowNumber().over(partitionBy(fields(distinctOn)).orderBy(orderBy)).as("rn")

**Comment by lukaseder** [comment]
Looking good. Will run some additional tests next week to cover unions and a few other operators that might get in the way.

**Comment by lukaseder** [comment]
There might be some issues with the usual edge cases, e.g. when a projection contains duplicate column names, which is allowed in top-level queries, but not in derived tables.  We're already handling this in a few cases, but instead of fixing this on a case-by-case basis, we should improve our internal framework for handling complex `SELECT` transformations: https://github.com/jOOQ/jOOQ/issues/10749
