### ISSUE TITLE
Allow to match <types/> with precision and scale

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3666]
The manual claims that precision and scale can be used for `<forcedTypes/>` in the `<types/>` element:

``` xml
    <!-- Add a Java regular expression matching data types to be forced to
           have this type.

           Data types may be reported by your database as:
           - NUMBER
           - NUMBER(5)
           - NUMBER(5, 2)
           - any other form

           It is thus recommended to use defensive regexes for types.

           If provided, both "expressions" and "types" must match. -->
      <types>.*</types>
```

... but that's not true. Only the actual type name can be matched. We should allow for matching:
- The simple type name
- The type name using precision / scale

---

See also #3661

**Comment by xyalan** [comment]
I use jooq-codegen with 3.8.4, but precision and scale can not match.

**Comment by lukaseder** [comment]
@xyalan What have you tried? Do note that these are regular expressions, so you have to escape parentheses...
