### ISSUE TITLE
Treat identical UNION [ ALL ] and INTERSECT set operations as associative avoiding unnecessary parentheses

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3676]
The `UNION [ ALL ]` and `INTERSECT` set operations are associative, i.e. the following are the same

``` sql
-- UNION
(A UNION B) UNION C
A UNION (B UNION C)

-- UNION ALL
(A UNION ALL B) UNION ALL C
A UNION ALL (B UNION ALL C)

-- INTERSECT
(A INTERSECT B) INTERSECT C
A INTERSECT (B INTERSECT C)
```

Similar to `AND` and `OR`, we should thus treat these operations as associative among themselves, and avoid adding the above unnecessary parentheses:

``` sql
A UNION B UNION C
A UNION ALL B UNION ALL C
A INTERSECT B INTERSECT C
```

---

Note, this is only true if there are no `ORDER BY` and `LIMIT` clauses in the subselects. Otherwise, the parentheses are essential

---

See also:
- #2815
- #3579
- #3664
- #9751

**Comment by lukaseder** [comment]
This improvement could fix quite a few issues, such as #9751, so we're expediting this for 3.13, and possibly even backporting it to 3.12.4, with a feature toggle in case we miss a regression.

**Comment by knutwannheden** [comment]
The implemented fix is currently an all-or-nothing approach. I.e. either all combined queries are parenthesized or none of them are. So if at least one the queries is deemed to require a parenthesis pair, then all of them will get it. This could of course be fine tuned, but that is considered out of scope for this issue.

**Comment by lukaseder** [comment]
Yes, I considered fine tuning this, but I don't see the value right now. Vendor agnostic set operation support is a mess as it is already. I don't like to touch this area any more than is (known to be) needed.

**Comment by lukaseder** [comment]
One caveat mentioned in https://github.com/jOOQ/jOOQ/issues/9751#issuecomment-576452476 is that currently, the formatting is not right, as can be seen here:

```sql
select `test`.`t_book`.`ID`
from `test`.`t_book`
where `test`.`t_book`.`AUTHOR_ID` in (
  select `test`.`t_author`.`ID`
  from `test`.`t_author`
  where `test`.`t_author`.`ID` = 1
  union select `test`.`t_author`.`ID`
  from `test`.`t_author`
  where `test`.`t_author`.`ID` = 2
)
order by `test`.`t_book`.`ID`
```

I'll investigate this and possibly backport

**Comment by lukaseder** [comment]
After the fix, the formatting is now correct:

```java
select `test`.`t_book`.`ID`
from `test`.`t_book`
where `test`.`t_book`.`AUTHOR_ID` in (
  select `test`.`t_author`.`ID`
  from `test`.`t_author`
  where `test`.`t_author`.`ID` = 1
  union
  select `test`.`t_author`.`ID`
  from `test`.`t_author`
  where `test`.`t_author`.`ID` = 2
)
order by `test`.`t_book`.`ID`
```
