### ISSUE TITLE
Add a jOOQ / Spring Batch example

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3716]

**Comment by GianPaoloBuffo** [comment]
Hi Lukas, I see you've decided not to add a Spring Batch example. Is there a reason for this? I'm trying to use jOOQ for this very purpose

**Comment by lukaseder** [comment]
It's a effort / benefit ratio thing (for me). Would you be interested to provide an example?

**Comment by GianPaoloBuffo** [comment]
My need for an example is that I myself can't quite figure out how to integrate the two (at least in an elegant way). If I figure it out, I'll make sure to get back to you with the solution

**Comment by gildegoma** [comment]
Hello Guys! This is certainly not the most elegant/correct way to achieve this, but you can look at some examples in https://github.com/alv-ch/alv-ch-batches, like this [one](https://github.com/alv-ch/alv-ch-batches/blob/master/jobdesk/master/src/main/java/ch/alv/batches/master/to/jobdesk/VacanciesToJobdeskConfiguration.java). Mainly the project has a central/master database and use jOOQ for importing or exporting data from/into other media (files, elasticsearch, other rdbms,...)

**Comment by lukaseder** [comment]
Very nice, thanks for sharing @gildegoma

**Comment by pavan2017** [comment]
@lukaseder is there any example on how to use jooq with springbatch? i tried searching but didnt find any examples

**Comment by lukaseder** [comment]
@pavan2017 I don't know if anyone else has written one. I haven't

**Comment by wvdberg** [comment]
For reading you can write a class like this

```
public class JooqPagingItemReader<T> extends AbstractPagingItemReader<T> {

  private Collection<? extends SortField<?>> sortFields;

  private Supplier<SelectWhereStep> queryProvider;

  private JooqRecordMapper<T> recordMapper;
```

I'm looking for a way to do the writing still...

**Comment by luistrigueiros** [comment]
Hi I have create and example and provided an article about this, available at: 

- https://luistrigueiros.medium.com/spring-batch-with-jooq-example-a29ee9472b2c

Hope we can find a recommend why of doing this.
