### ISSUE TITLE
Let org.jooq.Cursor implement java.io.Closeable

### ISSUE THREAD

**Issue by chenkelmann** [jOOQ/jOOQ#3735]
The Cursor class already has a close() method, so just adding "implements Closeable" would do the trick.

What is the benefit? 

When using jooq under Android, one often wants to fill lists with lazy loaded db content. To do this properly, one needs a Loader. If Cursor implemented Closeable, one generic Loader can cleanly open, handle & dispose of all kinds of resources, i.e. one can use the same generic Loader for Jooq, content from a network, file etc. Right now one needs to create an extra jooq Cursor Loader, as Cursor is not closeable. 

Also, having a resource that can be close()-ed implement Closeable pacifies my OCD.

**Comment by lukaseder** [comment]
Duplicated by #4336.

With Java 7 having gone end-of-live, we think it's time to move on with jOOQ and support Java 8 in the free Open Source edition. We can continue supporting Java 6 in commercial editions. This means that we can proceed and let `Cursor` and `Query` types extend `AutoCloseable`
