### ISSUE TITLE
Publish manual also in EPUB format

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3772]
As suggested by a customer, there is an alternative, open publication format in which we could publish the manual:
http://en.wikipedia.org/wiki/EPUB

The format is XML based, so the current XSLT processing might just work almost out-of-the-box

**Comment by lukaseder** [comment]
There doesn't seem to be an easy (or easy to find) way to transform our XML manual into an epub format without knowing much of epub's internals...

**Comment by pjean** [comment]
Maybe I can take a look into the generation if you indicate me what you can generate now and how ?

**Comment by lukaseder** [comment]
We have home-grown XML -> HTML and XML -> FO -> PDF transformation XSLs. We might open-source them eventually (https://github.com/jOOQ/jOOQ/issues/3358), but for now, you could just assume a very simple XML structure that contains a hierarchy of sections.

**Comment by pjean** [comment]
epub format is a mix of xhtml and xml (See https://github.com/IDPF/epub3-samples). I think a XSL transformation can do the trick but you should open-source it first to see what we can do.

**Comment by lukaseder** [comment]
Yes, that's what I *think* would work too. :-)

The manual XML is really extremely trivial:

```xml
<manual version="3.5">
	<section id="manual">
		<title>The jOOQ User Manual. Multiple Pages</title>
		<content><html>
			<h2 id="Overview"><a href="#Overview" name="Overview">Overview</a></h2>
			<p>This manual is divided into six main sections:</p>
                        ...
                </html></content>
                <sections>
			<section id="preface">
				<title>Preface</title>
				<content><html>
                                ...
                </sections>
```

**Comment by lukaseder** [comment]
I've uploaded a snapshot version here: https://gist.github.com/lukaseder/435ef3c3dede01b8e405

**Comment by pjean** [comment]
Great, thank you for the snapshot but I think that is not enough. xsl transformation for xml to html will be very helpful because it can be mainly reused as well as css, font, ... (all materials to obtain html version)

**Comment by lukaseder** [comment]
Hmm, OK, let's proceed differently... as long as we don't have the manual as open source, I don't think we can really accept contributions, or work towards them.

I've had a go at this. Here's a first draft:
http://www.jooq.org/doc/3.6/manual-epub/manual-epub-3.6.epub

Apart from adding more beautiful styling, I can see the following issues:

- Code is too wide
- There are no page numbers (yet)

Do you know how this is usually handled?

**Comment by ooxi** [comment]
Btw :+1: for open sourcing the documentation. I know how hard it is to release something which isn't "perfect" (like a bunch of custom xml files glued together by some perl magic ;)) but that's nevertheless the best thing to do :)

**Comment by lukaseder** [comment]
It's not about it being perfect - it *is* already perfect, of course ;)

It's about prioritising doing issue #3358 vs all the other 1000 issues :)

**Comment by lukaseder** [comment]
OK, the EPUB manual is live and linked from http://www.jooq.org/learn. Any concrete feedback is very welcome

**Comment by ooxi** [comment]
:+1: nice

**Comment by lukaseder** [comment]
@ooxi : Too bad. I'm really not 100% conviced that we deliver state of the art, yet.
