### ISSUE TITLE
Immutable Configuration

### ISSUE THREAD

**Issue by Quurks** [jOOQ/jOOQ#3776]
As far as I understand ( https://groups.google.com/forum/#!topic/jooq-user/ojz-EF9U4Cw ) a DSLContext is safe to use by multiple threads when

a) it is not modified
b) the ConnectionProvider can be used by mutiple threads
c) the SPI are threadsafe

it would be nice to have an optional immutable Configuration to prevent "accidental" modifications to a configuration

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/13079
