### ISSUE TITLE
Cannot combine INSERT ... SELECT with RETURNING

### ISSUE THREAD

**Issue by lpireyn** [jOOQ/jOOQ#3779]
PostgreSQL (and possibly other dialects) [allows INSERT with SELECT and RETURNING](http://www.postgresql.org/docs/9.3/static/sql-insert.html). The API doesn't support combining the two.

Example:
``` java
DSL
    .insertInto(myTable, myField1, myField2)
    .select(mySelect)
    .returning(myField3)
;
```

**Comment by lukaseder** [comment]
See also:
- https://groups.google.com/d/msg/jooq-user/OlIOeEQQpec/7woMPgl8JIIJ
- http://stackoverflow.com/q/29434194/521799

**Comment by arlampin** [comment]
I noticed this doesn't work with `insertInto(Table<R> into, Collection<? extends Field<?>> fields)` method, as returned InsertValuesStepN's `select()` returns plain `Insert`, and not for example `InsertOnDuplicateStep`.

Is this on purpose, or is this an oversight on InsertValuesStepN implementation? And is there some work around if so?

To be clear, what I would like to work is:
```java
context.insertInto(table, someFieldCollection)
  .select(someSelect)
  .returning()
  .fetch()
```

**Comment by lukaseder** [comment]
You're right, thank you very much, @arlampin. I've created a new issue for this: https://github.com/jOOQ/jOOQ/issues/5509
