### ISSUE TITLE
Add Field<String> DSL.currentSchema()

### ISSUE THREAD

**Issue by gschlager** [jOOQ/jOOQ#3783]
A lot of methods in jOOQ-meta need a schema as parameter. However, there's no easy way to get the current schema used in the database connection.
It would be great if there were a simple utility method that returns the `SchemaDefinition` or at least the name of the currently used schema.

Here are a few ways to determine the current schema depending on the database (more can be found in the concrete implementations of Flyway's [DbSupport](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/dbsupport/DbSupport.java) class):
 - MySQL / MariaDB: `getCatalog()` of the JDBC connection
 - PostgreSQL: `SELECT current_schema()`
 - H2: `SELECT SCHEMA()`

**Comment by lukaseder** [comment]
Implemented for some dialects. More support will follow
