### ISSUE TITLE
Add support for the ANY() aggregate function

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3798]
Currently, this seems to be backed only by MySQL's `ANY_VALUE()`:
http://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_any-value

See also @morgo's comment on the blog:
http://blog.jooq.org/2014/11/20/use-mysqls-strict-mode-on-all-new-projects/#comment-95750

In other SQLDialects, we may be able to emulate this behaviour via `MAX()`

**Comment by rwiggins** [comment]
Would it be possible to add this to MySQLDSL in the short term? That is, with no emulation for the other DBs?

**Comment by lukaseder** [comment]
@rwiggins : No, I'd rather add this to `DSL` directly, just like `EVERY()`. After all, it can probably be emulated using `MAX()`. I'd like to learn more about how this is being used. What's the use-case that you have in mind?

**Comment by lukaseder** [comment]
As a workaround: Plain SQL aggregate functions will ship with jOOQ 3.15: https://github.com/jOOQ/jOOQ/issues/1729, but plain SQL templating has always been an option: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

This particular aggregate function will be supported via https://github.com/jOOQ/jOOQ/issues/11458
