### ISSUE TITLE
Deprecate <immutablePojos/> and replace by new PojoStyle configuration

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3821]
With #3713, we'll introduce a POJO style that governs this kind of behaviour of generated POJOs. This is going to be redundant with the existing `<immutablePojos/>` flag, as we're introducing a `PojoStyle` configuration like this:

``` xml
  <simpleType name="PojoStyle">
    <restriction base="string">
      <enumeration value="JAVA"/>
      <enumeration value="JAVA_IMMUTABLE"/>
      <enumeration value="SCALA_CASE_CLASS"/>
      <enumeration value="KOTLIN_DATA_CLASS"/>
      <enumeration value="KOTLIN_DATA_CLASS_IMMUTABLE"/>
    </restriction>
  </simpleType>
```

Notice that Kotlin data classes could be mutable as well with `var`: https://kotlinlang.org/docs/reference/data-classes.html

---

See also #3713

**Comment by feoktant** [comment]
Hey @lukaseder , is this still open? Maybe it is possible to participate somehow?

**Comment by lukaseder** [comment]
Thanks for the offer, @feoktant. There are simpler issues to implement. This one requires quite a bit of design decisions, backwards compatibility considerations, etc. What kind of participation did you have in mind?

**Comment by feoktant** [comment]
Let me show what I want to achieve :)
Here is two converters I want to use:

```scala
import java.lang.{Long => JLong}

import org.jooq.Converter

class JLongToLongConverter extends Converter[JLong, Long] {
  override def from(bigintValue: JLong): Long = Predef.Long2long(bigintValue)
  override def to(userObject: Long): JLong = Predef.long2Long(userObject)
  override def fromType(): Class[JLong] = classOf[JLong]
  override def toType: Class[Long] = classOf[Long]
}

class IntegerToIntConverter extends Converter[Integer, Int] {
  override def from(databaseObject: Integer): Int = Predef.Integer2int(databaseObject)
  override def to(userObject: Int): Integer = Predef.int2Integer(userObject)
  override def fromType(): Class[Integer] = classOf[Integer]
  override def toType: Class[Int] = classOf[Int]
}
```

With such converter I have problem with compilation in `Records`:
```scala
  def getUsertId : scala.Long = {
    val r = get(11)
    if (r == null) null else r.asInstanceOf[scala.Long]
  }
```

It could be solved via custom code generator, like this:
```
  def setUserId(value : scala.Long) : Unit = {
    if(value.isDefined) value.foreach(set(11, _))
    else set(11, null)
  }

  def getUsertId : Option[scala.Long] = {
    val r = get(11)
    if (r == null) None else Some(r.asInstanceOf[scala.Long])
  }
```

Is it possible to solve somehow?

**Comment by lukaseder** [comment]
Oh oh. Option! There will quite likely be no Option in jOOQ for another while - see item #1 of this blog post:
https://blog.jooq.org/2017/07/25/5-things-you-may-not-have-known-about-jooq

I really recommend you don't follow that path. You get some quick wins when working with `UpdatableRecord` (although, still, your non-Option types can be `null`, so it'll be a lie). But you'll pay a big price when doing some just slightly more sophisticated SQL, e.g. an outer join (as illustrated in the article).

In any case, the Option debate is not related to this issue, which talks about introducing a way to generate case classes instead of the more Java-ish immutable POJOs...

**Comment by feoktant** [comment]
@lukaseder thank you for such perfect answer! And link to article was very useful

**Comment by feoktant** [comment]
From your answer, I can still have my own generator with POJO's, which have Scala types and Option's:
```scala
case class SomePojo(
    id: Long,
    smth: Option[Long],
    comment: Option[String]
) extends Serializable {

  def getId: JLong = id // implicit conversion of not nullable Int to java.util.Long 
  def getSmth: JLong = timfrti.map(Predef.long2Long).orNull // Here is nullable value
  def getComment: String = comment.orNull // Java's nullable value
}
```

As I understood, pojos are used only in dao's. So it is ok from JOOQ vision, right?

**Comment by lukaseder** [comment]
I'm assuming you also bound a converter to the table definitions, because otherwise, jOOQ won't know how to call the case class constructor, regardless if from within DAOs or any other way involving the `DefaultRecordMapper`

**Comment by feoktant** [comment]
No, in this case all other thing remains without changes. Records still have java types, and the only place it is combined with scala is case classes constructor. In getters scala types mapped to java

**Comment by PCasafont** [comment]
There could be immutable kotlin data classes as well (var -> val)

**Comment by lukaseder** [comment]
Yes, thanks @PCasafont. I've already updated the description

**Comment by ayush-finix** [comment]
Java records are also out in preview for jdk 14.

**Comment by lukaseder** [comment]
Thanks, @ayush-finix. We'll look into this: https://github.com/jOOQ/jOOQ/issues/10287

I'll close this issue here - I prefer keeping things as they are with the `<immutablePojos/>` flag (for now), and look into these styles through separate issues, including Scala case classes: #3713
