### ISSUE TITLE
Add support for CREATE TEMPORARY TABLE and all related flags

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3853]
See also:
https://groups.google.com/forum/#!topic/jooq-user/4C4hW1Hku78

**Comment by lukaseder** [comment]
Support added for Oracle and PostgreSQL for now

**Comment by elwinleee** [comment]
In mysql, it should be create temporary table instead of create global temporary table.

**Comment by lukaseder** [comment]
@elwinleee Thanks for the suggestion. Yes, we should support temp tables also for MySQL. We'll do that for jOOQ 3.7 in #4375.
