### ISSUE TITLE
Improve Javadoc on DSLContext.executeInsert(), executeUpdate(), and executeDelete() about optimistic locking not applying

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3862]
There is a feature request trying to implement optimistic locking using client side computed columns for all queries, not just the ones generated by `DSLContext::executeUpdate` et al: 

- https://github.com/jOOQ/jOOQ/issues/13339

I think this is better implemented more generically.

For example, the presence of `DSLContext.executeUpdate(TableRecord, Condition)` allows for running non-record based, bulk updates. The two methods are very similar, yet also very distinct. I'm not too fond of creating such a big semantic difference between the two. The Javadoc is quite clear:

> Update a table. 
>
> `UPDATE [table] SET [modified values in record] WHERE [record is supplied record]`

It's a simple utility. It doesn't do more than that. However, I think it's worth documenting this fact. E.g. `executeInsert()` also has such a disclaimer:

> Unlike UpdatableRecord.store(), this does not change any of the argument record's internal "changed" flags, such that a subsequent call to UpdatableRecord.store() might lead to another INSERT statement being executed.

**Comment by billoneil** [comment]
I think this may be related.

This works
```java
OrganizationRecord record = create.
            .newRecord(Tables.ORGANIZATION)
            .setName(name)
            .setDateCreated(LocalDate.now())
            .setTsCreated(LocalDateTime.now())
            .setEnabled(true);
        record.insert();
```

This does not
```java
OrganizationRecord record = new OrganizationRecord()
                .setName(name)
                .setDateCreated(LocalDate.now())
                .setTsCreated(LocalDateTime.now())
                .setEnabled(true);
        OrganizationRecord x = create.insertInto(Tables.ORGANIZATION).set(record).returning().fetchOne();
```

Would it be recommended to always use the record.store / insert methods for now?

**Comment by lukaseder** [comment]
Hi @billoneil, I'm not sure how is this related? There's no optimistic locking on insert statements, only on updates / deletes... Would you mind creating a new issue, if you think there is a problem?

**Comment by billoneil** [comment]
I thought it was related because of the similar execution paths. Operating on the records directly work as expected but passing the record into an insert / update behaves differently. My guess is if there is a fix it could fix both at the same time. I'll make a new issue and link it to this one when I get home and you can close if it's working as designed.

**Comment by lukaseder** [comment]
You're not even calling `DSLContext.executeUpdate()` :)

**Comment by lukaseder** [comment]
Having read through the other issue, I see why you think there could be a fix for both. Nevertheless, these are two distinct problems. While this one certainly needs to be fixed, the other one is quite a change and I'm not sure if I fully agree with it.

**Comment by karishmasingh20** [comment]
Hi, has this been fixed?

**Comment by lukaseder** [comment]
No

**Comment by karishmasingh20** [comment]
I also have any issue in maybe in the same regard that I opened an issue for https://github.com/jOOQ/jOOQ/issues/12657

**Comment by lukaseder** [comment]
There is a feature request trying to implement optimistic locking using client side computed columns for all queries, not just the ones generated by `DSLContext::executeUpdate` et al: 

- https://github.com/jOOQ/jOOQ/issues/13339

I think this is better implemented more generically.

For example, the presence of `DSLContext.executeUpdate(TableRecord, Condition)` allows for running non-record based, bulk updates. The two methods are very similar, yet also very distinct. I'm not too fond of creating such a big semantic difference between the two. The Javadoc is quite clear:

> Update a table. 
>
> `UPDATE [table] SET [modified values in record] WHERE [record is supplied record]`

It's a simple utility. It doesn't do more than that. However, I think it's worth documenting this fact. E.g. `executeInsert()` also has such a disclaimer:

> Unlike UpdatableRecord.store(), this does not change any of the argument record's internal "changed" flags, such that a subsequent call to UpdatableRecord.store() might lead to another INSERT statement being executed.

**Comment by lukaseder** [comment]
Fixed in versions

- 3.19.0
- 3.18.5 (https://github.com/jOOQ/jOOQ/issues/15139)
- 3.17.14 (https://github.com/jOOQ/jOOQ/issues/15140)
- 3.16.20 (https://github.com/jOOQ/jOOQ/issues/15141)
