### ISSUE TITLE
Let org.jooq.Condition extend org.jooq.Field<Boolean>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3867]
In SQL, boolean column expressions and predicates are the same thing. This is specified in the SQL standard, and implemented also in a couple of databases, such as PostgreSQL.

Perhaps we should reflect this by letting `Condition` extend `Field<Boolean>`, which would make using some parts of the jOOQ API much easier. Other options would be to let `Condition` extend `SelectField<Boolean>, GroupField` to bring at least _some_ convenience.

This needs to be carefully evaluated though, as the side-effects on all of the API are non-negligible, and perhaps not backwards-compatible.

---

See also this discussion here:
- https://groups.google.com/forum/#!topic/jooq-user/D-V3kC8b1qs
- https://groups.google.com/forum/#!topic/jooq-user/z5I7667R8X8

**Comment by knutwannheden** [comment]
@lukaseder Reopen or add "Wontfix" resolution?

**Comment by lukaseder** [comment]
Something went wrong when I edited those tags on 2018-10-29

**Comment by lukaseder** [comment]
This is a duplicate of https://github.com/jOOQ/jOOQ/issues/11969, it was implemented in jOOQ 3.17
