### ISSUE TITLE
Include third-party dependencies via the Maven Shade Plugin

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3869]
Currently, we have a couple of dependencies that we internalised into jOOQ-local packages, e.g. commons-lang.

In principle it would be better to include the actual dependencies in order to automate upgrades etc. There is the Maven Shade Plugin that takes care of creating an "uber jar", which can also relocate the dependencies' packages in order to avoid the usual conflicts with transitive dependency hell:
http://maven.apache.org/plugins/maven-shade-plugin

**Comment by thiloplanz** [comment]
How important is it for people to have jOOQ work without any extra jar file dependencies? 
The alternative would be to just declare the dependencies and have them be supplied by the user. 

Should not be too much trouble for anyone, no trouble for Maven users, makes for possibly slightly lighter artefacts (if things like commons-lang are already used by the application), OTOH also makes for potential version conflicts with unstable dependencies.

Personally, I don't like "uber jars" for anything except executable jar files (and there I love them, though recently more in the capsule variety).

Also note that jOOQ cannot be used without supplying at least one additional jar file anyway (the JDBC driver you want to use).

What are these dependencies? Are they currently stripped down to only the parts that jOOQ requires (that would mostly remove the slightly lighter objection above)?

**Comment by lukaseder** [comment]
> How important is it for people to have jOOQ work without any extra jar file dependencies?

It is quite important to a couple of our customers.

> if things like commons-lang are already used by the application

We only use `StringUtils` from there. The overhead is negligible.

> OTOH also makes for potential version conflicts with unstable dependencies.

Yes. See some competitor products who have dependency issues throughout the dependency chain up into Spring Data, etc.

> What are these dependencies?

- JSON Simple (parts)
- CSV Parser (parts)
- Apache Commons (1 class)
- jOOU
- jOOR

They're all currently manually included. Note that we really only need parts of those dependencies, which is why we don't want to create a full dependency.

Perhaps we might create two distributions. One with included dependencies, and one that governs everything via Maven.

**Comment by sytolk** [comment]
It's a very bad practice to include dependencies in jooq package. Тhis may cause conflicts in some projects that use original ones with different version like dependency. Its need to remove it from jooq and include all dependency in maven pom.xml 
For not maven users it`s have Intellij IDEA/Eclipce artifact creation with included dependencies in jooq.jar or maven plugins to do this.. but it`s a stupid I can`t think more about these users..

**Comment by lukaseder** [comment]
> It's a very bad practice to include dependencies in jooq package

That's not true. There are a couple of projects out there that pull in (and re-package!) partial dependencies in order to avoid the upstream dependency hell that would be created otherwise.

Both solutions have their advantages and drawbacks. We opted for the smaller evil.

Rest assured that we are *very keen* on not having any dependencies at all, unless it is really inevitable, or unless it would be unwise to re-invent the wheel (as in the case of CSV or JSON libraries). But there are tons of these libraries out there, we don't want to explicitly prefer one over the other, so please consider our internalised dependencies as jooq-internal, not for you to re-use.

> Тhis may cause conflicts in some projects

No, we repackaged the dependencies that we pulled in. E.g. json-simple is now in the `org.jooq.tools.json` package. There is no potential for conflicts - except, of course, in auto-completion of your IDE

**Comment by sytolk** [comment]
Yes I have include unknown version of json-simple instead of 1.1.1 with auto-completion of my IDE, how do you know ? :) Now I have two version of json-simple included in my project war file and I`m so happy :) maybe its need to write Android like Proguard configuration file with the JOOQ exclude things ;) 
or think about repackage jooq.jar -> jooq-core jooq-json(json-simple) and so on..
if you're afraid of hell you will never see heaven.

**Comment by lukaseder** [comment]
> How did you know ?

Well, this is really the only source of confusion. The two classes have the same name, yet they're in different packages. Outside of IDE tooling, the two classes are completely distinct.

But that's OK. jOOQ has a lot of types that conflict with other libraries in this way. E.g. `Field`, `Condition`, `Table`, etc.

> or think about repackage jooq.jar -> jooq-core jooq-json(json-simple) and so on..

That's what I said, and that's what we might be doing in jOOQ 4.0

> if you're afraid of hell you will never see heaven.

You may have your specific use-cases. We have seen tons of others. It's not that easy to suit everyone

**Comment by lukaseder** [comment]
The existing manual "shading" of third parties worked well and kept the `jar` file slim by avoiding unnecessary inclusions.
