### ISSUE TITLE
Support SAP HANA UPSERT

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3887]
HANA has a very simple and useful `UPSERT` syntax. Perhaps, we can transform `MERGE` statements into this syntax:
http://help.sap.com/saphelp_hanaplatform/helpdata/en/20/fc06a7751910149892c0d09be21a38/content.htm

We can certainly transform the H2 `MERGE` syntax to this `UPSERT`

**Comment by ooxi** [comment]
MySQL's `INSERT INTO ... ON DUPLICATE KEY UPDATE` can also be transformed to `UPSERT` but not the other way around (because `UPSERT` supports user defined conditions but MySQL only primary keys)

**Comment by lukaseder** [comment]
@ooxi: I don't think that MySQL's `INSERT INTO .. ON DUPLICATE KEY UPDATE` can be transformed into `UPSERT`. MySQL allows for different values to be passed to `INSERT` and `UPDATE` variants, just like the SQL standard `MERGE`. E.g. when there's no duplicate key, insert `A=1`. Otherwise, update `B='2'`

**Comment by ooxi** [comment]
Yes, you are correct, I did not think of that :)

**Comment by lukaseder** [comment]
We'll support this via H2's `MERGE` syntax right now. HANA's functionality is covered 100% by this syntax.
