### ISSUE TITLE
Add Configuration.converterProvider() to allow for implementing default converters between <T> and <U> types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3896]
Some data type pairs are not natively convertible, e.g. Joda `DateTime` to `java.util.Date`. Users should be able to register converters for arbitrary pairs of `<U>` and `<T>`, which will apply as "fallbacks" when there is no concrete conversion scheme, e.g. in the context of an `into(Class)` call.

This is also useful for hooking JSON or XML binding algorithms into jOOQ on a global level, see #10062, #10065

Like the existing `RecordMapperProvider`, the `ConverterProvider` can provide a `Converter<T, U>` for a source and target data type:

```java
public interface ConverterProvider {
    <T, U> Converter<T, U> provide(Class<T> tType, Class<U> uType);
}
```

A `DefaultConverterProvider` is made available, implementing jOOQ's current default conversion behaviour from `org.jooq.tools.Convert`. It is recommended that a custom implementation delegates to an instance of the `DefaultConverterProvider` for all data type pairs that it doesn't know how to convert.

---

See also:
https://groups.google.com/forum/#!topic/jooq-user/xW51kTXkb4w

**Comment by chimpeenuts** [comment]
Is there a reason this issue was closed?

I ask because I'm trying to do something very basic:
```java
dslContext()
.select(
		DSL.currentTimestamp().as("timestamp"),
		PACKAGE_HEALTH.NIS_ID
)
.from(PACKAGE_HEALTH)
.fetchInto(MyCustomDTO.class);
```

MyCustomDTO.class:
```java
public class MyCustomDTO {
	private UUID          _nisId;
	private ZonedDateTime _timestamp;

	public UUID getNisId() {
		return _nisId;
	}

	public void setNisId(UUID nisId) {
		_nisId = nisId;
	}

	public ZonedDateTime getTimestamp() {
		return _timestamp;
	}

	public void setTimestamp(ZonedDateTime timestamp) {
		_timestamp = timestamp;
	}
}
```
When the query executes, I get:
```
Caused by: org.jooq.exception.DataTypeException: Cannot convert from 1496160513555 (class java.lang.Long) to class java.time.ZonedDateTime
	at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1118)
	at org.jooq.tools.Convert$ConvertAll.toDate(Convert.java:1070)
	at org.jooq.tools.Convert$ConvertAll.from(Convert.java:789)
	at org.jooq.tools.Convert.convert0(Convert.java:316)
	at org.jooq.tools.Convert.convert(Convert.java:308)
	at org.jooq.tools.Convert.convert(Convert.java:380)
```

I am at a loss for how I tell the `dslContext` about the CustomConverter I have for SQL Timestamp --> ZonedDataTime.java.

We use Jooq to generate "Record" objects and I can define the "forced type" there:
```java
...
new ForcedType()
		.withName(ZonedDateTime.class.getName())
		.withExpression("timestamp")
		.withTypes("timestamp")
```

And of course there are all the `fetch` methods for a **single** field that have overloaded methods that take a custom converter...but I'm at a loss for how I use the `fetchInto` capability with a custom/non-Jooq generated POJO with types that I do indeed have Jooq Custom Converters but can't actually tell the current DSL context to use those converters.

I thought `ConverterProvider` would be the way to go, but it all looks "experimental" and "non-functional".

**Comment by nkoterba** [comment]
If the idea of a list of *global* converters is unsettling, perhaps an overloaded `fetchInto` method that takes an arbitrary list of Converters and consults those during default Record mapping? This would align with the other `fetch` methods that allow providing a Converter on a *per-field* basis.

```java
<E> List<E> fetchInto(Class<? extends E> type, Converter<?, ?> converters...) throws DataAccessException, MappingException;
```

**Comment by lukaseder** [comment]
@chimpeenuts 

> Is there a reason this issue was closed?

Yes, the main reason is that context-free converter graphs cannot decide once and for all what is the best path from A to B. Example: `Converter<byte[], String>`. There are several reasonable ways to encode binary data in a string:

- `String(byte[])` constructor
- uuencode
- base64
- hex
- `Arrays.toString(byte[])`

A graph whose edges are only defined by the types `<T, U>` of a converter cannot make any decision about which converter to pick. This problem gets more complex when combining converters, e.g., consider this chain graph:

- `<UUID, long[]>`
- `<long[], String>`
- `<UUID, String>`

What's the ideal path between `<UUID, String>`? The shortest? But what if we want to display two longs, e.g. for debugging?

The problem is that adding a new converter to a graph can have tons of impact and lead to many regressions as many assumptions previously made can break. So, this feature would be very fragile.

> I am at a loss for how I tell the dslContext about the CustomConverter I have for SQL Timestamp --> ZonedDataTime.java.

I see that this can be a problem, but what's your expectation here? The SQL timestamp is a `TIMESTAMP WITHOUT TIME ZONE` and `ZonedDateTime` doesn't really have a corresponding SQL type. Would you like the resulting value to contain your local time zone? We could definitely add this feature to `Convert`

> I thought ConverterProvider would be the way to go, but it all looks "experimental" and "non-functional".

Yes, it would have been the way to go but I think the API was added prematurely.

@nkoterba 

> perhaps an overloaded fetchInto method that takes an arbitrary list of Converters and consults those during default Record mapping? 

I think such an API might be a bit unpractical. We don't want to tamper with that all the time, at each `fetchInto()` call.

Note, there's already the possibility of overriding the `DefaultRecordMapper` behaviour through a `RecordMapperProvider`:

https://www.jooq.org/doc/latest/manual/sql-execution/fetching/pojos-with-recordmapper-provider/

**Comment by lukaseder** [comment]
Following up on the discussions in #10065 and #10062, I'm reviving this issue here. There are indeed a few cases where a global way of overriding data type conversion would be useful. Users will have to be careful to delegate to jOOQ's out of the box conversion algorithms by default.

**Comment by lukaseder** [comment]
We'll need to take into consideration `DataType.convert()` methods, as they cannot access `Configuration.converterProvider()`. Both jOOQ internal code and client code must be careful not to use `DataType.convert()` when a `Configuration` would otherwise be available and more suitable.

**Comment by lukaseder** [comment]
A lot of overloads will be affected in various types, including:

- `Record`
- `Result`
- `ResultQuery`

**Comment by lukaseder** [comment]
This implementation will fix a minor issue where custom `Converter`s were invoked on methods like `ResultQuery.fetchOne(int, Converter)` even if there was no resulting `Record`

**Comment by lukaseder** [comment]
First implementation draft added. TODOs:

- [ ] There is potential in caching `ConverterProvider` lookups inside of cached `RecordMapper` implementations. To be investigated
- [ ] Review other usages of `org.jooq.tools.Convert` to see if there are any missing opportunities to call the new SPI
- [ ] Decide what to do with `DataType.convert()`
- [ ] Documentation in the manual
- [ ] Example implementation using JAXB (since we still have the dependency on the JAXB API)

**Comment by lukaseder** [comment]
Just added this to the integration tests and the manual:

```java
public static class Name {
    public String firstName;
    public String lastName;
}

public static class Book {
    public String title;
}

public static class Author {
    public Name name;
    public List<Book> books;
}
```

And then:

```java
List<Author> authors = create()
  .select(jsonObject(
     jsonEntry("name", jsonObject(
       jsonEntry("firstName", AUTHOR.FIRST_NAME),
       jsonEntry("lastName", AUTHOR.LAST_NAME)
     )),
     jsonEntry("books", jsonArrayAgg(
       jsonObject("title", BOOK.TITLE)
     ))
  ))
  .from(AUTHOR)
  .join(BOOK).on(AUTHOR.ID.eq(BOOK.AUTHOR_ID))
  .groupBy(AUTHOR.ID, AUTHOR.FIRST_NAME, AUTHOR.LAST_NAME)
  .orderBy(AUTHOR.ID)
  .fetchInto(Author.class);
```

This looks *very* promising!

**Comment by lukaseder** [comment]
The example depends on an additional improvement: #10071. Otherwise, that last line needs to be `.fetch(r -> r.get(0, Author.class))`, which is cumbersome.
