### ISSUE TITLE
Enhance DefaultRecordMapper (and Unmapper) to follow JavaBeans conventions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3903]
When a column is called `firstName` (case-sensitive), jOOQ currently doesn't call the setter `setFirstName()`. From a JavaBeans conventions perspective, this is surprising.

Historically, jOOQ's `DefaultRecordMapper` was designed to follow SQL conventions more strictly than JavaBeans conventions, which is why a call to `setfirstName()` is preferred (e.g. in SQL Server, names are PascalCased (`FirstName`), which leads to the expected behaviour again)

With https://github.com/jOOQ/jOOQ/issues/5354 implemented in jOOQ 3.10, we *must* implement this as well!

---

See also:
- https://groups.google.com/forum/#!topic/jooq-user/u6M_1nt7UqM
- https://github.com/jOOQ/jOOQ/issues/5354

**Comment by lukaseder** [comment]
This already works in our existing integration test suite, which was introduced with #5354. Let's close this as worksforme and look out for additional bugs

**Comment by bitbrain** [comment]
JOOQ 3.10.x hype intensifies. 😍

**Comment by lukaseder** [comment]
Yay, stay tuned. Only a few hours left @bitbrain
