### ISSUE TITLE
Allow for customising generated file headers

### ISSUE THREAD

**Issue by jreznot** [jOOQ/jOOQ#3906]
It leads to duplicated comment before package statement and before class.

```
/**
 * This class is generated by jOOQ.
 */
```

Usually before package we place license/copyright statement.

**Comment by lukaseder** [comment]
Note: the class Javadoc is only present when there is no comment on the table in your database (see also #3598).

I guess we could actually extend the code generator to allow for custom file headers to include custom license / copyright statements...
