### ISSUE TITLE
Four octects are sent to Postgres for each negative byte in a byte[]

### ISSUE THREAD

**Issue by gortiz** [jOOQ/jOOQ#3923]
When JOOQ sends array of bytes to Postgres, it uses the octal format. To do the conversion from binary byte to octal, it uses java.lang.Integer#toOctalString(int) and the byte is automatically casted to integer. It works fine with positive bytes, but not with negative ones.

For example, when [-1] is inserted, [377] should be sent to Posgresql. Instead of that, Java transforms the byte -1 to the integer -1, represented in octal as 377 377 377 377, and jOOQ sends the array [377, 377, 377, 377]!

**Comment by lukaseder** [comment]
This issue is dealt with in the relevant pull request here: #3924
