### ISSUE TITLE
Add support for PostgreSQL functions returning single table records

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3942]
In addition to `SETOF` functions (#3376), which return a set of a given table type, it is also possible to return only a single row from a table type. E.g.:

```sql
CREATE OR REPLACE FUNCTION f_search_book(p_title character varying)
  RETURNS t_book AS
$BODY$
SELECT * FROM t_book
WHERE (LOWER(title) LIKE LOWER('%' || $1 || '%'))
LIMIT 1;
$BODY$
  LANGUAGE sql VOLATILE
  COST 100;
```

This works in a similar way to functions returning UDTs.

**Comment by opncow** [comment]
Is this the same as returning a single "row" of an UDT?

**Comment by lukaseder** [comment]
@opncow: Not strictly, at least as far as the code generator is concerned.
