### ISSUE TITLE
Add a flag to DefaultTransactionProvider to disable the support for nested transactions via savepoints

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3955]
Nested transactions are not always needed. Sometimes, it would be fine if nested transaction scopes would simply be ignored, delegating all commit / rollback decisions to the outer scope.

We should add a flag that disables nesting via savepoints to the `DefaultTransactionProvider`

----
See also:
- https://groups.google.com/forum/#!topic/jooq-user/zM1EzgaEcxg
- https://groups.google.com/forum/#!topic/jooq-user/zG0U6CkxI5o

**Comment by jCalamari** [comment]
Is there a way to disable nesting via savepoints in 3.6.2?

**Comment by lukaseder** [comment]
@jCalamari : You could implement your own `TransactionProvider`. Use the `DefaultTransactionProvider` as a basis for your implementation. The latest version already contains a workaround for SAP Hana's missing `Savepoint` support:

https://github.com/jOOQ/jOOQ/blob/eff6bb61f0a5f7ff3e4c758d93c4eb9df805827f/jOOQ/src/main/java/org/jooq/impl/DefaultTransactionProvider.java#L137
