### ISSUE TITLE
Apply Base64 encoding to binary types when formatting them to XML, JSON, etc.

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#3961]
The current implementation is not really helpful. It simply applies `byte[].toString()` or perhaps `Arrays.toString(byte[])`. In an actual export, we should base64 encode all `byte[]`

----
See also:
http://www.jooq.org/doc/3.2/manual/sql-building/column-expressions/cast-expressions/#comment-1798774534

**Comment by lukaseder** [comment]
@jonnybbb : I remember your JSON import contribution. Have you ever imported binary data?

**Comment by jonnybbb** [comment]
@lukaseder : No we just used non binary data for our imports

**Comment by lukaseder** [comment]
@jonnybbb OK, thanks for the info. I'll adapt also the import feature to support base64 encoded binary data
