### ISSUE TITLE
JOOQ DAOs insert

### ISSUE THREAD

**Issue by sytolk** [jOOQ/jOOQ#3970]
I have migrate from Spring jdbcTemplate to JOOQ v.3.5.1. The generated DAOs will save my time for SQL insert/update sql queries. Thanks! 
But I can`t find in generated DAOs insert method that return generated ID for MySQL. Something like this with Spring jdbcTemplate:
```java
KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(
                new PreparedStatementCreator() {
                    public PreparedStatement createPreparedStatement(Connection connection) throws SQLException {
                        PreparedStatement ps = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
                        ps.setInt(1, 1);
                        return ps;
                    }
                }, keyHolder
        );
        return keyHolder.getKey().intValue();
```

the only thing is http://www.jooq.org/doc/2.5/manual/sql-building/sql-statements/insert-statement/
Postgres's INSERT .. RETURNING - (I don`t know how it works internally for the MySQL ??)
Custom query for insert.. it`s better to add here method:
http://www.jooq.org/doc/2.6/manual/sql-execution/daos/
```
int insert(P object) throws DataAccessException;
```
or to return Object with the populated generated ID.

**Comment by lukaseder** [comment]
Thanks for your enquiry. Unfortunately, this feature is still missing from jOOQ's DAOs. Related issues are:

- https://github.com/jOOQ/jOOQ/issues/2536
- https://github.com/jOOQ/jOOQ/issues/3021

You can use jOOQ's `INSERT .. RETURNING` support also with MySQL, in case of which a call to `Statement.getGeneratedKeys()` is made. This also works with `UpdatableRecord.store()`, which automatically refreshes the `ID` value on the `UpdatableRecord`

I hope this helps. If you have further questions, do not hesitate to ask. We're also providing help on the jOOQ User Group, by the way:
https://groups.google.com/d/forum/jooq-user
