### ISSUE TITLE
Result.formatJSON() doesn't correctly escape quotation marks

### ISSUE THREAD

**Issue by Oneiros90** [jOOQ/jOOQ#3974]
I'm having troubles in parsing the resulting string of Result.formatJSON(). When some of the values contain a quotation mark the parser can't correctly work: I think that quotation marks inside values should be escaped (" to \") in order to create a valid JSON string. Is this a bug of the formatJSON() function? Or am I missing something?

**Comment by lukaseder** [comment]
jOOQ internally uses [json-simple](https://code.google.com/p/json-simple/), which properly escapes all quotation marks. Can you show an example of where this doesn't work?

**Comment by lukaseder** [comment]
@Oneiros90 : Do you have any further input for this? I cannot reproduce any issue related to the escaping of quotes...

**Comment by Oneiros90** [comment]
I'm sorry but i cannot reproduce the same issue due I don't have the same datas anymore... however, I think you can reproduce it pretty simply:
1) create a sql table containing a string value with a quote symbol (")
2) call a select query with Result.formatJSON() and look at the json result

**Comment by lukaseder** [comment]
I run this program:

```java
DSLContext ctx = create();
try {
    ctx.execute("create view x as select 'This string contains \"quoted\" content' v");
    System.out.println(ctx.fetch("select v from x").formatJSON());
}
finally {
    ctx.execute("drop view x");
}
```

Log output:

```
15:22:53,926 DEBUG [org.jooq.tools.LoggerListener                     ] - Executing query          : select v from x
15:22:53,942 DEBUG [org.jooq.tools.StopWatch                          ] - Query executed           : Total: 13.758ms
15:22:55,772 DEBUG [org.jooq.tools.LoggerListener                     ] - Fetched result           : +-------------------------------------+
15:22:55,772 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |V                                    |
15:22:55,772 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +-------------------------------------+
15:22:55,772 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : |This string contains "quoted" content|
15:22:55,772 DEBUG [org.jooq.tools.LoggerListener                     ] -                          : +-------------------------------------+
```

JSON output:

```
{"fields":[{"name":"V","type":"VARCHAR"}],"records":[["This string contains \"quoted\" content"]]}`
```

This looks correct to me, doesn't it?

**Comment by Oneiros90** [comment]
Nevermind, it looks like the problem was because of a bug in the javascript
injection of the json output.
Thank you very much



*L O R E N Z O   V A L E N T E*
COMPUTER SCIENTIST
FRONT-END / BACK-END DEVELOPER
oneiros.valente@gmail.com

<https://plus.google.com/u/0/+LorenzoValente>
<https://www.facebook.com/lorenzo.valente> <https://twitter.com/Oneiros90>
<https://www.youtube.com/user/Bibicut90>
<http://www.reddit.com/user/Oneiros90/>

2015-01-26 15:25 GMT+01:00 Lukas Eder <notifications@github.com>:

**Comment by lukaseder** [comment]
OK, thanks for the feedback
