### ISSUE TITLE
support JPA @Enumerated fields/getters

### ISSUE THREAD

**Issue by brmeyer** [jOOQ/jOOQ#3989]
When transforming records into JPA entities, it would be helpful to support `@Enumerated`.  Enough assumptions can be made about `@Enumerated(EnumType.ORDINAL)` and `@Enumerated(EnumType.STRING)` based on the column type.

**Comment by lukaseder** [comment]
Related: #1197

**Comment by lukaseder** [comment]
I agree, this might be a low-hanging fruit. We already support data type conversion from / to enums in jOOQ, in the same way as JPA via `org.jooq.impl.EnumConverter`

**Comment by lukaseder** [comment]
This will not be implemented. See #4263
