### ISSUE TITLE
support JPA @SecondaryTable

### ISSUE THREAD

**Issue by brmeyer** [jOOQ/jOOQ#3990]
As an example, say you have a `User` and a `UserMetadata` table (bad example, but take it for what it's worth).  The `User` entity would have something like `@SecondaryTable(name = "meta", pkJoinColumns = @PrimaryKeyJoinColumn(name = "user_id"))` on the class.  Columns residing in the secondary table would be annotated with `@Column(name = "first_name", table = "meta")`.

Ensure that when jOOQ selects `User` and joins it with `UserMetadata`, it's able to populate all the fields in the entity, even if they're marked as using the secondary table.  Not sure if this is already supported, but I was having some issues with it when I gave it a shot.

**Comment by lukaseder** [comment]
Hmm, interesting. I wasn't aware of this annotation. How is it different from `@OneToOne`?

**Comment by brmeyer** [comment]
It could of course be modeled with a `@OneToOne`.  But in some contexts, like my example, it can make more sense to model that with a single Entity.  `User#getFirstName` is more natural than `User#getMetadata#getFirstName`.  Not a right/wrong solution, but just an additional option.

**Comment by lukaseder** [comment]
Aha, silly me. I should've read the docs to the end. Hmm, I wonder if jOOQ really needs any adaptation at this point. When the `first_name` column is present in any `Record`, and that record is mapped into a type that has a `@Column(name = "first_name")` annotation, then that mapping is always applied, no matter what table the data came from...

On a SQL level, the table producing a column is not really a reliable piece of information. The only thing that really matters is the column name or the column index. Do you have a specific query / mapping use-case in mind where jOOQ would need adaptation?

**Comment by brmeyer** [comment]
> When the first_name column is present in any Record, and that record is mapped into a type that has a @Column(name = "first_name") annotation, then that mapping is always applied, no matter what table the data came from

That's exactly what I suspected/assumed, but I had trouble with it early on.  Let me give it another shot before anyone worries about it ;)  Thanks

**Comment by lukaseder** [comment]
Well, we had that discussion about `@Column` annotations on private fields being ignored by jOOQ (#3643). Perhaps that was the trouble you've had? Also, if there is ambiguity between two `first_name` columns in the same `Record`, then jOOQ won't be able to resolve that ambiguity

**Comment by brmeyer** [comment]
Right, this was after converting everything to getter annotations, temporarily.  But like I said, don't sweat it for now.  Odds are it was a symptom of something else stupid I was doing...

**Comment by lukaseder** [comment]
This will not be implemented. See #4263
