### ISSUE TITLE
Allow dynamic schema name in SchemaImpl

### ISSUE THREAD

**Issue by brmeyer** [jOOQ/jOOQ#3991]
This a bit of an edge case, but here goes...

When apps are deployed to a cloud PaaS (OpenShift, Heroku), the platform typically brings down the database and all other resources prior to building the app.  So, adding jOOQ code generation through the Maven plugin won't work, since the DB isn't available during build time.

An alternative is to commit the generated classes.  If you have only one instance of the app/DB, great, that works.

In my case, we run dozens of instances of this app from a single code base, each targeting a different organization, and each with their own endpoint and DB.  In OpenShift's case, the DB name is always the app name -- forcing it to use a consistent name isn't currently possible (not sure about Heroku).

So, currently, I generate the code and manually change the `SchemaImpl` constructor to something like:

private MySchema() {
	super(System.getenv("OPENSHIFT_APP_NAME"));
}

Although it seems silly, it would be really useful to somehow configure jOOQ to use a `System.getenv` (or any arbitrary code) in place of the schema name.

**Comment by lukaseder** [comment]
I suspect that runtime schema mapping might already be sufficiently covering this feature request?
http://www.jooq.org/doc/latest/manual/sql-building/dsl-context/runtime-schema-mapping/

**Comment by brmeyer** [comment]
Perfect, apologies for not seeing that first.  Will give it a shot.  Feel free to reject this one.

**Comment by lukaseder** [comment]
Sure, no worries. Let me know if it fulfills your use-case. Note, there are also pending feature requests to further improve runtime identifier mapping:

- For columns: https://github.com/jOOQ/jOOQ/issues/2949
- Based on regular expressions: https://github.com/jOOQ/jOOQ/issues/2928
