### ISSUE TITLE
remove json-simple source from jooq

### ISSUE THREAD

**Issue by sytolk** [jOOQ/jOOQ#4005]
I have found that json JSONObject class is included in jooq package. If I have dependend original source

mvnrepository.com/artifact/com.googlecode.json-simple/json-simple/1.1.1

I will include in my project this class twice.. Please remove json-simple source from jooq package and set it like maven dependency.

**Comment by lukaseder** [comment]
We're going to be thinking about better handling of third-party dependencies in jOOQ 4.0. Before that, we cannot really break backwards-compatibility and address these issues.

One issue dealing with the same topic is #3869

The most likely approach will be to deliver two types of binaries:

- One to have external dependencies
- One to embed all external dependencies
