### ISSUE TITLE
Jooq w/ Flyway & Derby Embedded

### ISSUE THREAD

**Issue by mikereinhold** [jOOQ/jOOQ#4007]
Currently I am trying to use Flyway with Jooq and Embedded Derby in a Maven project. I have Flyway configured to run prior to Jooq as per the documentation, however when the jooq code generator runs, it dies with:

ERROR XSDB6:Another instance of Derby may have already booted the database

From the research that I have done, this appears to be a classloader issue relating to the fact that I have the embedded derby dependency defined as a dependency under the jooq codegen plugin. Removing the dependency from under the plugin directly results in a NoClassDefFound exception.

I'm not sure why jooq needs the dependency to be declared under the plugin while flyway does not, however with an embedded Derby database this results in a severe issue since both class definitions loaded under separate classloaders cannot connect to the same database at the same time.

I should be able to work around this issue by either breaking the build up into 2 passes (undesirable due to issues with CI) or change the build to use the Client-Server Derby instead of an embedded Derby (just added complexity). It would be awesome to avoid needing the Embedded Derby dependency elements under the plugin and instead rely on the project having the dependency.

**Comment by lukaseder** [comment]
> I'm not sure why jooq needs the dependency to be declared under the plugin while flyway does not

That shouldn't be the case. jOOQ's plugin dependencies are optional, too. @axelfontaine himself made that feature request https://github.com/jOOQ/jOOQ/issues/2886 :)

Can you please provide the pom.xml (with all jdbc URLs, etc.) that's not working for you?

**Comment by mikereinhold** [comment]
Thanks for the link to the feature request! After reading through it, I noticed that I somehow had an old version of the codegen plugin being resolved (3.4.2). I updated the version to 3.5.1 and the dependency resolution worked as expected. So that's cool!

Unfortunately, I'm still seeing getting the SQL exception from Derby:
ERROR XSDB6:Another instance of Derby may have already booted the database

Just thinking out loud: I'm not that familiar with how Maven executes plugins, but it seems like it might be related to how Maven is forking for execution of the plugins (if it is indeed forking). I've also since found that even when the flyway:migrate goal is not bound, running maven for the site goal causes the same exception (the codegen is executed twice and fails on the second time).

It is almost as if the plugins are not closing the database properly or stopping Derby, which shouldn't be necessary if the plugins are all being executed in the same Derby context... 

You can see the latest version of the pom in my repo here: https://github.com/CourseScheduler/scheduler-legacy/blob/fccdb44a0b69a6621d37a47e6fba6a8535e3864d/pom.xml

If I get adventuresome, I'll try to debug through the Maven execution to determine what the Derby context is and whether the plugin execution mechanism appears to be the problem or what.

**Comment by lukaseder** [comment]
I'm sorry for the delay. I forgot to post an answer here. I don't see anything out of the ordinary in your configuration.

The issue you're running into is this one here (I suspect):
https://issues.apache.org/jira/browse/DERBY-5856

Indeed, Maven has plugin-specific class loaders:
http://maven.apache.org/guides/mini/guide-maven-classloading.html

And that's what prevents the same database from being accessed by both Flyway and jOOQ plugins.

I'm not sure if you can do anything at the client side. Perhaps, it would be possible for the two plugins to tweak class loading in some way, although these things usually tend to be dangerous. It would be interesting to know if Flyway perhaps doesn't close the JDBC Connection "early" enough for the lock to be removed, before the jOOQ plugin starts?

**Comment by mikereinhold** [comment]
Hi Lukas,

Thanks for your response - I had been looking at that Derby issue
previously but didn't have the context of Maven classloading to be sure.

I just confirmed in the Flyway plugin source that it is not shutting down
the Derby database or instance explicitly. In which case, the Derby
instance in that classloader will shut down implicitly when the plugin /
classloader / Derby context expires? Under "normal circumstances", this
would be when the JVM shuts down, but it's not clear to me if that is due
to garbage collection or finalization of the Derby class or via a runtime
shutdown hook... Again, I'm not sure how Maven handles the lifecycle of
plugin objects, but I would hope that the objects & classes used by the
plugin go out of scope and are garbage collected, finalized, and unloaded
after plugin execution is complete. If that is correct and the Derby
cleanup happens with the class and not via a shutdown hook, then inserting
a delay (or possibly a forced garbage collection) between the Flyway plugin
and the jOOQ plugin could allow the Flyway Derby instance to expire and
shutdown cleanly.

Messing with the plugin class loading is probably non-ideal and
non-trivial. I think it would be better and safer to add an option to the
plugins to explicitly shutdown the Derby database or instance after the
main plugin activity is complete. If I don't have any luck the delay I can
try going that route.

This is not a "critical issue" as I can work around this by using a
slightly more manual build process (aka, run the flyway migrate target, run
the jooq generate target, add/update jooq generated sources in version
control, normal build & package targets).

On Wed, Feb 4, 2015 at 3:03 PM, Lukas Eder <notifications@github.com> wrote:

> I'm sorry for the delay. I forgot to post an answer here. I don't see
> anything out of the ordinary in your configuration.
>
> The issue you're running into is this one here (I suspect):
> https://issues.apache.org/jira/browse/DERBY-5856
>
> Indeed, Maven has plugin-specific class loaders:
> http://maven.apache.org/guides/mini/guide-maven-classloading.html
>
> And that's what prevents the same database from being accessed by both
> Flyway and jOOQ plugins.
>
> I'm not sure if you can do anything at the client side. Perhaps, it would
> be possible for the two plugins to tweak class loading in some way,
> although these things usually tend to be dangerous. It would be interesting
> to know if Flyway perhaps doesn't close the JDBC Connection "early" enough
> for the lock to be removed, before the jOOQ plugin starts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jOOQ/jOOQ/issues/4007#issuecomment-72927743>.
>



-- 
*Mike Reinhold* | Co-Founder

**Comment by lukaseder** [comment]
Mike, thanks for the additional insight. Perhaps, you might be able to hook into Flyway's existing migration lifecycle to shutdown the connection?

- http://flywaydb.org/documentation/maven/migrate.html ("callbacks")
- http://flywaydb.org/documentation/api/javadoc/org/flywaydb/core/api/callback/FlywayCallback.html

I think we should have have the same kind of callback in jOOQ, in case any other Maven plugin will run after the jOOQ plugin. I have created #4033 for this.

**Comment by mikereinhold** [comment]
I've read about the callbacks, however I did not even think about using a
callback. :)

I'll check out the documentation and see if I can easily shutdown the Derby
database or instance. I'm not positive if closing the Derby connection will
cause the embedded Derby database to be released. If it does not, there is
a connection syntax you can use with embedded Derby to stop the database or
the instance: ex. to shutdown the entire embedded Derby instance connect
with this JDBC URL: "jdbc:derby:;shutdown=true" (see
http://db.apache.org/derby/docs/10.0/manuals/develop/develop12.html). .

I'll let you know if this works! If so, similar callbacks in jOOQ would be
very helpful.





On Thu, Feb 5, 2015 at 7:47 AM, Lukas Eder <notifications@github.com> wrote:

> Mike, thanks for the additional insight. Perhaps, you might be able to
> hook into Flyway's existing migration lifecycle to shutdown the connection?
>
>    - http://flywaydb.org/documentation/maven/migrate.html ("callbacks")
>    -
>    http://flywaydb.org/documentation/api/javadoc/org/flywaydb/core/api/callback/FlywayCallback.html
>
> I think we should have have the same kind of callback in jOOQ, in case any
> other Maven plugin will run after the jOOQ plugin. I have created #4033
> <https://github.com/jOOQ/jOOQ/issues/4033> for this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jOOQ/jOOQ/issues/4007#issuecomment-73040597>.
>



-- 
*Mike Reinhold* | Co-Founder

**Comment by lukaseder** [comment]
I'm not too familiar with Derby. I (think I) know that HSQLDB has a `SHUTDOWN` command that needs to be issued explicitly.

The JDBC URL part looks reasonable as well...

**Comment by lukaseder** [comment]
@mikereinhold : for the time being, here's a workaround that spawns Flyway in a new process:
http://stackoverflow.com/a/28403621/521799

**Comment by mikereinhold** [comment]
Thanks - I'll give this a shot and let you know the results

On Mon, Feb 9, 2015 at 2:44 AM, Lukas Eder <notifications@github.com> wrote:

> @mikereinhold <https://github.com/mikereinhold> : for the time being,
> here's a workaround that spawns Flyway in a new process:
> http://stackoverflow.com/a/28403621/521799
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jOOQ/jOOQ/issues/4007#issuecomment-73468578>.
>



-- 
*Mike Reinhold* | Co-Founder

**Comment by AveryRegier** [comment]
The simple approach I tried first failed, but this works (mostly): 
https://github.com/AveryRegier/flyway-simple

Schemas and Java based migrations don't work with this approach.

**Comment by mikereinhold** [comment]
@lukaseder, @AveryRegier -

Thanks for your suggestions! I was able to get this working slightly differently by just invoking the desired maven goal in the exec plugin (instead of using @AveryRegier's command line wrapper). You can see this in the latest commit to my POM https://github.com/CourseScheduler/scheduler-legacy/commit/3e682b9976a843681b265be761cf3fadbee40316. 

Short version is:
```xml
<plugin>
	<groupId>org.codehaus.mojo</groupId>
	<artifactId>exec-maven-plugin</artifactId>
	<executions>
		<execution>
			<id>flyway-migrate-db</id>
			<phase>generate-sources</phase>
			<goals>
				<goal>exec</goal>
			</goals>
			<configuration>
				<executable>mvn</executable>
				<arguments>
					<argument>flyway:migrate</argument>
				</arguments>
			</configuration>
		</execution>
		<execution>
			<id>jooq-db-generate</id>
			<phase>generate-sources</phase>
			<goals>
				<goal>exec</goal>
			</goals>
			<configuration>
				<executable>mvn</executable>
				<arguments>
					<argument>jooq-codegen:generate</argument>
				</arguments>
			</configuration>
		</execution>
	</executions>
</plugin>
```

This way my flyway and jooq goals are still configured the same and can easily be invoked outside or inside of the lifecycle the same way. This works around the classloader issues pretty cleanly.

This works fine with Jenkins as well - no issues in CI. The only caveat (really pretty minor) is that you can't rely on the embedded maven that is built in to your IDE since the exec will search the system PATH. Weird things might happen if your system mvn is of a significantly different version than the embedded mvn.

**Comment by AveryRegier** [comment]
This worked for me rather well, in both the IDE (IntelliJ, where you configure where it finds maven) and CI (travis-ci.org).  My command line workaround worked for a while then started failing with the same problem again.

**Comment by mikereinhold** [comment]
@AveryRegier - Glad it worked for you also!

**Comment by lukaseder** [comment]
I'm closing this for now as there is probably not much that can be done from the jOOQ side
