### ISSUE TITLE
Add support for LATERAL to DB2

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4015]
Markus Winand (@fatalmind) has done some research on `LATERAL` availability in various SQL dialects. jOOQ currently documents and integration-tests support only for Oracle 12c and PostgreSQL 9.3+, but there are also
- DB2 LUW
- SQLite 3.8.8

SQL Server support via `CROSS / OUTER APPLY` emulation is already covered in #2920

http://de.slideshare.net/MarkusWinand/modern-sql/16

**Comment by fatalmind** [comment]
If it is red and in brackers, it means it doesn't support it as of that version!

Markus Winand
markus.winand@winand.at
T +43 1 9444047

Maderspergerstrasse 1-3/9/11
1160 Wien
AUSTRIA

**Comment by lukaseder** [comment]
> If it is red and in brackers, it means it doesn't support it as of that version!

@fatalmind : Yep. I've just realised when I saw the same notation for `WITH` in a subsequent slide :)
