### ISSUE TITLE
Add a ScalaGenerator

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4021]
At some point, a code generator that generates actual Scala code is inevitable, e.g. to support the `scala.Int` type.

**Comment by romanxts** [comment]
+1

**Comment by manuelbernhardt** [comment]
Unsurprisingly I fully agree that this feature is a good idea (it would be useful in an upcoming project). We should have a chat about it tomorrow.

**Comment by lukaseder** [comment]
@manuelbernhardt We certainly should :) Looking forward. I'm on my way to Linz and will arrive in Vienna early tomorrow morning.

**Comment by lukaseder** [comment]
OK, hacked this together on my way back from Vienna ;-) Looking good, so far - a couple of remaining compiler errors in the generated sources remain.

This will be a cool new feature for jOOQ 3.6!

**Comment by lukaseder** [comment]
@manuelbernhardt, @romanxts: What's you folks' opinion here:

jOOQ knows the `<immutablePojos/>` flag. When turned on, the Java code generator generates something like:

```java
public class Pojo {
    private String value1;
    private String value2;

    public Pojo(String value1, String value2) {
        this.value1 = value1;
        this.value2 = value2;
    }

    public String getValue1() {...}
    public String getValue2() {...}
}
```

In Scala, that would probably correspond to a case class. What about non-immutable Pojos? Is that a common-ish practice in Scala? I know I can write:

```scala
class Pojo(
    private var value1 : String,
    private var value2 : String
) {
    def this() = {
        this(null, null);
    }

    def getValue1 : String = {...}
    def getValue2 : String = {...}

    def setValue1(value1 : String) : Unit = {...}
    def setValue2(value2 : String) : Unit = {...}
}
```

Apart from the fact that I'm currently using `null` in the example, would that be somewhat idiomatic Scala?

**Comment by manuelbernhardt** [comment]
Wow, that was fast! Awesome!

In Scala, a mutable class would look like this:

```scala
    class Pojo(var value1: String, var value2: String)
    val p = new Pojo("foo", "bar")
    p.value1 = "baz"
    println(p.value1) // prints "baz"
```

Though to be honest, I can't really recall having seen much of these constructs when interacting with databases. State that is queried from the database usually lives in a case class, and any updates are done on the level of a field or set of fields directly through a method. So I'd say that case class generation would be largely sufficient.

**Comment by lukaseder** [comment]
Well, we do have the flag `<immutablePojos/>`, which I'd like to maintain, unless mutable pojos are really absolutely unidiomatic Scala.

So, your suggestion seems to hint at public fields without getters and setters?

**Comment by billoneil** [comment]
Case classes do give you the connivence copy method.  Immutability is definitely preferred in Scala but I wouldn't see a reason not to support mutable classes.

```
// example of changing a field in an immutable case class.
val pojo: Pojo = Pojo("value1", "value2")
val updated: Pojo = pojo.copy(value2 = "new value2")
```

Make sure you watch out for the field limit on case classes.  Once you go over 22 fields in a case class the apply and unapply methods no longer work for free.  I have seen a few libraries use heterogeneous lists (HList) once you pass the 22 field limit.  Unfortunately this is a problem you run into fairly frequently with code generation from databases especially with poorly designed schemas.  HLists might require the code to depend on an additional library so this could impact your design decisions.

**Comment by lukaseder** [comment]
22 is a poorly designed schema? I'll show you some serious fact table of a BI environment of a client of ours... ;)

But thanks for the hints! I keep forgetting about HList et al. I guess we'll keep the case class feature a separate one (#3713) and default to generating regular (mutable / immutable) classes for pojos as in Java. That'll be cleaner.

**Comment by manuelbernhardt** [comment]
The aritly limit on case classes has been [lifted in Scala 2.11](https://issues.scala-lang.org/browse/SI-7296) so this shouldn't be an issue any longer. But I agree that this is a different issue. Thanks Lukas, this is going to be great to use!

**Comment by lukaseder** [comment]
Ah, interesting. I'll have to read up on that some time!

Talking about Scala 2.11 (vs. 2.10). From a code generator perspective, there shouldn't be anything specific that we should keep in mind to keep source compatibility between Scala "minor" (major?) releases, right? I mean, the caveats in Scala usually arise from binary compatibility, not source compatibility, am I right?

**Comment by manuelbernhardt** [comment]
It depends :) To get a full appreciation of the problem [here's a good video](https://www.youtube.com/watch?v=g1Pqyskjx8M). But I would go ahead and say that there is nothing to worry about in terms of source or binary compatibility for this use-case, since the generated code will belong to a project anyway and depend on that project's lifecycle.

**Comment by lukaseder** [comment]
> since the generated code will belong to a project anyway and depend on that project's lifecycle

Yes, but perhaps, we should assume a minimal Scala version that generated source code supports. E.g. generated Java code assumes Java 1.6
