### ISSUE TITLE
Allow for specifying constraints with CREATE TABLE statements

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4050]
jOOQ 3.6 will support `ALTER TABLE .. ADD CONSTRAINT` statements. Constraints can also be specified on the `CREATE TABLE` statement directly. Sometimes, this might be faster / more convenient. In other cases, this is the only way to specify constraints at all (e.g. SQLite).

Users should also be able to pass the new `org.jooq.Constraint` type to `CREATE TABLE` statements.

**Comment by apatrida** [comment]
This has yet to be released?

**Comment by lukaseder** [comment]
@apatrida : Yes. jOOQ 3.8 is due for early Q2 2016
