### ISSUE TITLE
How to change record instantiation?

### ISSUE THREAD

**Issue by ooxi** [jOOQ/jOOQ#4057]
Hi,

since #3308 I'm carrying around [a small patch](https://github.com/ooxi/jOOQ/compare/newInstance-preview) to allow custom record creation: instead of invoking the default constructor of `MyTableRecord` directly, a static factory method `MyTableRecord.newInstance` will be invoked, if available.

Could you please advise on how to achieve similar behavior using jOOQ without a custom patch?

**Comment by lukaseder** [comment]
This will be covered by #1838, #3313. Implementation-wise, I suspect that the "record factory" will be injectable via the existing `RecordListener`

**Comment by lukaseder** [comment]
Heh, #3308 is also a duplicate of #1838 and #3313 by you :). Message received. We'll make it a priority for jOOQ 3.6

**Comment by ooxi** [comment]
That would be great :)
