### ISSUE TITLE
Add class prefixes, suffixes and other options to the code generator

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#408]
**Author: @fractalizer**
Hello.

It would be good for a generator to have the following settings:
- Table class name prefix (default - empty)
- Table class name suffix (default - empty)
- Record class name prefix (default - empty)
- Record class name suffix (default - "Record")
- Enum class name prefix (default - empty)
- Enum class name suffix (default - empty)
- Class naming scheme
  - "As in DB"
  - "UpperCamelCase" (default)
  - "lowerCamelCase"
- Class names word separator
  - "_" (default)
  - "none"

---

'''EDIT:'''

Implement this as a "`ConfigurationNamingStrategy`" once the concept of `NamingStrategy` is available in source code generation (see #374)

Make this available once XML configuration for source code generation is supported (see #395). With a public XSD file describing the configuration options, it will be easier to keep track of the various supported settings

**Comment by roma2341** [comment]
For my use case it was enough to use:
<strategy>
	<name>org.jooq.codegen.example.JPrefixGeneratorStrategy</name>
</strategy>
To separate jooq generated classes from my hibernate entities

**Comment by lukaseder** [comment]
> I can't just set any class I want because I can't force maven to build this class before execution of jooq codegen

Of course you can. You can create a separate maven module with this strategy, build that before code generation, and then reference it. Or you use a matcher strategy, which is entirely configurable. Starting from jOOQ 3.19, it will be possible to provide an inline Java class in your code generation configuration, and we'll compile that in-memory for you:

- https://github.com/jOOQ/jOOQ/issues/15209

> need a working example of such configuration.

Maybe, you have a specific question? It's just standard multi module maven setup, so I'm not sure what kind of question you may have about this.
