### ISSUE TITLE
Generated Record classes should provide map() 

### ISSUE THREAD

**Issue by stevetodd** [jOOQ/jOOQ#4095]
I want to be able to do this:

```
dslContext.fetchOne(FOO, ...).map(this::map);
```
where I have in the same class
```
public MySpecialFoo map(FooRecord record) {
    MySpecialFoo mySpecialFoo = new MySpecialFoo()

    // do stuff with record

   return mySpecialFoo;
}
```
Right now, AbstractRecord.map() is declared as:
```
public final <E> E map(RecordMapper<Record, E> mapper)
```
With a generic Record. :disappointed: 

I would love the generator to generate a method like:
```
public final <E> E map(RecordMapper<FooRecord, E> mapper)
```

**Comment by lukaseder** [comment]
Yes, we'd love to do that as well, but unfortunately, we cannot override the `Record.map()` method in an incompatible way like you suggested. The only way we could make this work is by making `Record` recursively generic:

```java
interface Record<R extends Record<R>> {
    <E> E map(RecordMapper<R, E> mapper);
}
```

But we think that recursive generics are a terrible idea for a variety of reasons:
http://blog.jooq.org/2013/06/28/the-dangers-of-correlating-subtype-polymorphism-with-generic-polymorphism/

One way to work around this might be to operate on `Result<R>`, a type that has `<R>` as a generic parameter:

```java
dslContext.fetch(FOO, ...).map(this::map).get(0);
```

We're obviously open to other ideas, too.

**Comment by lukaseder** [comment]
It would be great if this could be fixed easily, but unfortunately, there doesn't seem to be a way. We'll reopen this, once there's a solution
