### ISSUE TITLE
Document how to use Converter and Binding without the code generator

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4099]
If users aren't using the source code generator, it may not be obvious how to use `Converter` and `Binding` implementations with custom `Field` implementations. We should document that.

----
Also, add integration tests.

**Comment by facundofarias** [comment]
:+1: 

Thanks for that!

**Comment by lukaseder** [comment]
You're welcome. Documentation added to jOOQ 3.6 manual
