### ISSUE TITLE
Use "&lt;" for "<" and "&gt;" for ">"  in javadoc

### ISSUE THREAD

**Issue by snooppy** [jOOQ/jOOQ#4100]
It's a bit confusing, when you write queries and see, for example, for **le** operation javadoc: ```java this = value``` instead of  ```java this <= value```

**Comment by lukaseder** [comment]
Thanks for pointing this out to us. We had turned off HTML validation in the Javadocs because Java 8's Javadoc validator is quite strict - but in this case, it would've been good to detect this.

**Comment by lukaseder** [comment]
This seems like a pretty good regex to match opening angle brackets in Javadocs:

```
# Search:
^(\s+\*(?! >)\s*.*?)<(?![/\w])(.*?)$

# Replace
$1&lt;$2
```

The `>` character doesn't need to be escaped in HTML
