### ISSUE TITLE
Overload DDL API to accept Name instead of String arguments

### ISSUE THREAD

**Issue by nicolas-f** [jOOQ/jOOQ#4110]
Hi,

We are starting to use JOOQ for OrbisGIS project. But as JOOQ quotes the schema I provide I'm stuck on dropping an index.

```java
print org.jooq.impl.DSL.dropIndex("\"MYSCHEMA\".\"MYTABLE\"").getSQL()
print org.jooq.impl.DSL.dropIndex("MYSCHEMA.MYTABLE").getSQL()
```
Gives

```sql
drop index """MYSCHEMA"".""MYTABLE"""
drop index "MYSCHEMA.MYTABLE"
```

How to define the schema of the index ?
Thanks
Regards,

-- 
Nicolas Fortin
IRSTV FR CNRS 2488
GIS        http://orbisgis.org
Spatial DB http://h2gis.org
Noise      http://noisemap.orbisgis.org

**Comment by lukaseder** [comment]
Hello Nicolas,

Indeed, there are some missing pieces in the API, it seems. We'll be fixing those by overloading the existing API:

```java
// existing:
dropIndex(String name);

// new
dropIndex(org.jooq.Name qualifiedName);
```

In the mean time, you can workaround this issue by using `Settings.renderNameStyle` to prevent the quoting. The default is `RenderNameStyle.QUOTED`. Use `RenderNameStyle.AS_IS` instead.

**Comment by nicolas-f** [comment]
Hi

Ok Thanks. I will try this.

Regards,
-Nicolas

**Comment by lukaseder** [comment]
The improvement has now been implemented.
In jOOQ 3.6, the easiest way to provide qualified names will be:

```java
import static org.jooq.impl.DSL.*;

dropIndex(name("MYSCHEMA", "MYTABLE"));
```

**Comment by nicolas-f** [comment]
Impressive ! Thank you.
