### ISSUE TITLE
Cross-release several jooq-scala deliverables

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4111]
Most Scala libraries are built several times for a matching scala version.

For instance, Scalatest is released as:
- scalatest_2.10
- scalatest_2.11
- scalatest_2.12

The two deliverables are compiled from the same sources but are not expected to be binary compatible.

We should do the same with jooq-scala

---

See also:
- http://stackoverflow.com/a/28818994/521799
- https://twitter.com/lukaseder/status/572697043682107393

**Comment by metasim** [comment]
@lukaseder Is a 2.11 version available yet?

**Comment by lukaseder** [comment]
No, unfortunately, it isn't yet. I'm sorry for the delay in this - we should increase this issue's priority for jOOQ 3.8

**Comment by metasim** [comment]
[Here are some notes](https://github.com/davidB/scala-maven-plugin/wiki/frequently-asked-questions#cross-building-with-maven) on cross-compiling with Mavenb. Let the Scala community know if you want help porting to SBT (effort depends on how much continuity you enforce between modules through your parent POM).

**Comment by lukaseder** [comment]
We won't be building this artifact with SBT. I'm sure there's a Maven-based solution that fits our build.

Unfortunately, there's not much the community can do without us doing 90% of the work explaining how our commercial builds and distribution work...

**Comment by lukaseder** [comment]
This will be done from jOOQ 3.10 onwards. In the absence of time to further research the options offered by Maven or other build tools, we'll simply duplicate our builds, making the latest Scala dependency (2.12) the default source code, which is copied (and possibly, patched) to older scala builds. This will work the same way as our current Java 6/7 and Java 8 builds, and future Java 9 build.

Likewise, older Scala releases will be supported in the commercial jOOQ distributions only, whereas the latest ones are supported in the jOOQ Open Source Edition as well. In jOOQ 3.10, this will be:

- jOOQ OSS Edition: Scala 2.11+
- jOOQ Commercial Editions: Scala 2.10+
