### ISSUE TITLE
Invalid SQL generated when using UNSIGNED data types with MySQL DDL statements

### ISSUE THREAD

**Issue by msteiger** [jOOQ/jOOQ#4117]
I'm writing a small tool that converts/copies SQL tables across different dialects. It creates the new table at the target DB similar to the following snippet:

```java
for (Field<?> f : srcTable.fields()) {
    DataType<?> dataType = f.getDataType(dialect);
    dstContext.createTable(dstTable).column(f.getName(), dataType) // and appends to this step
}
```

This converts `MySQL -> SQLite` nicely, but fails for `MySQL -> MySQL`. I see two issues:

* The `dataType` converts `INT` to `signed` and tries to use that to create the new column, but `signed` is not valid for MySQL. I assume that the data type conversion is incorrect. I added a small hack that preserves `int` and `int unsigned` to temporarily fix that.

* The first createTable() call writes out `int unsigned` as expected, but the second (and probably all after) seems to delete the space char. The reason could be that the second call to `column()` is run on `CreateTableColumnStep`.

An example:

     create table `MyTable`(`col1` int unsigned null, `col2` intunsigned null)

Related: #3337

**Comment by lukaseder** [comment]
The first issue you're describing (`INT` being converted to `signed`) is fixed with #3341.

**Comment by lukaseder** [comment]
I can reproduce the missing space issue. Thanks for reporting. We'll fix this ASAP

**Comment by lukaseder** [comment]
This issue is now fixed for jOOQ 3.6. We'll also merge a fix to 3.5.4 and 3.4.6. Perhaps, other data types (in other databases) are affected as well. We'll be adding additional integration tests to check that.

Thanks again for reporting!

**Comment by msteiger** [comment]
Thank you for the amazingly quick fix. I can confirm that the first issue was resolved from 3.5.2 to 3.5.3.

**Comment by lukaseder** [comment]
Thanks for the confirmation

**Comment by lukaseder** [comment]
Reopening this to fix this also for MariaDB
