### ISSUE TITLE
Invalid SQL generated when using TINYTEXT with MySQL DDL statements

### ISSUE THREAD

**Issue by msteiger** [jOOQ/jOOQ#4120]
I'm writing a small tool that converts/copies SQL tables across different dialects.

MySQL's `TINYTEXT` is converted to `char(255) (java.lang.String)` DataType. Calling the column() method on `CreateTableImpl` converts it into `tinytext(255)`, which is not valid for MySQL. It should be `tinytext` without the length specifier.

I assume that the `Utils.toSQLDDLTypeDeclaration()` methods needs to be tweaked to *not* declare the length for some data type / dialect combinations.

**Comment by lukaseder** [comment]
Related: #4117

**Comment by lukaseder** [comment]
Hmm, could you perhaps provide an example that produces the `tinytext(255)` column declaration? I don't get that at my side. Does this happen with jOOQ 3.5.3, or with the latest 3.6.0-SNAPSHOT that you've built in #4117?

**Comment by msteiger** [comment]
I couldn't find nightlies / snapshot builds on the website, so I'm using jOOQ 3.5.3 for now. I can reproduce the problem by creating a MySQL table (with HeidiSQL)

    CREATE TABLE `MyTable` (`meter` TINYTEXT NULL);

I use the MySQL jdbc4 driver to connect to the DB and try to copy it like this:

```java
DSLContext dstContext = DSL.using(target);
Table<Record> dstTable = DSL.tableByName(srcTable.getName());
CreateTableColumnStep createTable = null;
Configuration dialect = dstContext.configuration();

for (Field<?> f : srcTable.fields()) {
    DataType<?> dataType = f.getDataType(dialect);
    if (createTable == null) {
    	createTable = dstContext.createTable(dstTable).column(f.getName(), dataType);
    } else {
        createTable = createTable.column(f.getName(), dataType);
    }
}
createTable.execute();
```

It crashes with a `DataAccessException` - SQL syntax error:

    create table `MyTable`(`meter` tinytext(255) null)

**Comment by lukaseder** [comment]
> I couldn't find nightlies / snapshot builds on the website, so I'm using jOOQ 3.5.3 for now.

Yes, we're offering those only to paying customers, right now.

> `for (Field<?> f : srcTable.fields()) {`

Is `srcTable` a generated table or did you obtain it from `org.jooq.Meta`?

**Comment by lukaseder** [comment]
Never mind. I can reproduce it with `org.jooq.Meta`:

```sql
CREATE TABLE t_2926 (
  t1 TINYTEXT,
  t2 TEXT,
  t3 MEDIUMTEXT,
  t4 LONGTEXT
)
```

And then:

```java
int i = 1;

Table<?> table =
Seq.seq(create().meta().getTables())
   .filter(t -> "t_2926".equals(t.getName().toLowerCase()))
   .findFirst()
   .get();

CreateTableColumnStep step =
create().createTable("t")
        .column("id", MySQLDataType.INTEGERUNSIGNED);

for (Field<?> field : table.fields()) {
    step = step.column("n" + i++, field.getDataType(create().configuration()));
}

step.execute();
```

**Comment by msteiger** [comment]
Yes, I'm using `org.jooq.Meta` to find the matching `org.jooq.Schema` and iterate over the Tables in it, similar to how you do it.

**Comment by lukaseder** [comment]
Thanks for the update. I suspect that we should ignore all length information with "LOB types", i.e. standard or vendor-specific data types that match any of `CLOB`, `NCLOB` or `BLOB`. This is true for DDL and for casting.

Thanks again for reporting this.

**Comment by lukaseder** [comment]
This fix here just fixed the syntax errors. What we should do instead, though, is remember what lob type we got as input in the code generator, or wherever, and then reproduce that when exporting SQL:

- https://github.com/jOOQ/jOOQ/issues/18742

Since we usually work with the generic `SQLDataType` instead of the dialect specific literals, I suspect we'll have to maintain the `length` property of the lob, internally.

**Comment by lukaseder** [comment]
I don't understand the point of this snark?
