### ISSUE TITLE
Add <username/> as a synonym for <user/> in the code generation configuration

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4124]
This is something that people will always have to look up. Is it `"user"` or `"username"`? Let's just accept both in the code generation configuration, and take whatever is set. In case both are set, we should fail, of course.

**Comment by lukaseder** [comment]
Perhaps, it's not a good idea. Then, people will start wondering what the difference is...

**Comment by chilloutman** [comment]
How about this?

You pick either `user` or `username` as the designated one. But you still look for the other one when parsing. When you find the other, you fail, but you generate a nice message like: "Found invalid node <user> in code generation configuration. Did you mean <username>?".

**Comment by lukaseder** [comment]
@chilloutman Unfortunately, there is no such thing as "when parsing". We're using XSD / XJC to parse XML into generated classes, which are also used by the Maven plugin. I.e. it's not possible to hide this logic without adding new public API (which will lead to confusion)

**Comment by lukaseder** [comment]
OK, I'm doing this now. It's about the fifth time I've been bothered by the difference between the `sql-maven-plugin` and our plugin ;)

**Comment by ooxi** [comment]
I propose `userna` as compromise!

**Comment by lukaseder** [comment]
Thank you for your valuable input! ;)
