### ISSUE TITLE
@javax.persistence.Column.name() is case-insensitive

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4128]
jOOQ currently treats column names as provided by JPA's `@Column.name()` property as case-sensitive, but this is not the case, unless they're quoted:

```java
@Column(name = "CASE_insensitive")
int caseInsensitive

@Column(name = "\"CASE_sensitive\"")
int caseSensitive
```

----
See also:
https://twitter.com/lukaseder/status/573506390960050178

**Comment by lukaseder** [comment]
This won't be merged. The regression risks are too high.

**Comment by derekm** [comment]
@lukaseder -- We're hitting a different case-sensitivity issue using dynamic field access on a table based on string names.

E.g., `.where(table.field(VALUE, String.class).eq(value))`

We use your `JPADatabase` to codegen off of H2, but then our string-based or `Name`-based dynamic references become case-sensitive as compared to PostgreSQL.

**Comment by lukaseder** [comment]
@derekm: You can turn off the generation of quoted names in jOOQ by using `Settings.renderNameStyle` up until jOOQ 3.11, or `Settings.renderQuotedNames` from jOOQ 3.12 onwards

**Comment by ivangreene** [comment]
@lukaseder working with Derek on this issue; this is more an issue with getting a Field from a Table and not influenced by the runtime Settings.
For example, given a JPA entity:
```java
@Entity
@Table(name="foo")
public class Foo {
  @Column(name="bar")
  private String bar;
}
```
After running generation against H2, we have to reference the column 'bar' with `Foo.FOO.field("BAR", String.class)`, whereas if we generated against Postgres which folds unquoted identifiers to lowercase, we would access that field with `Foo.FOO.field("bar", String.class)`. This is a contrived example and I'm aware in both cases we can simply use `Foo.FOO.BAR` to get the same field, but our real case is using the TableLike#field methods for more dynamic access.

So it is difficult to judge where the responsibility lies. For the time being we have gotten around this by setting a Hibernate config to use a physical naming strategy that quotes all identifiers, however it feels less than optimal to need to configure that.

**Comment by lukaseder** [comment]
I see now, thanks for the clarification. Would you mind opening up a new issue with this description? The original issue is about the `DefaultRecordMapper`. Yours is about the `JPADatabase`
