### ISSUE TITLE
No milliseconds value when reading Timestamp values from SQLite

### ISSUE THREAD

**Issue by deepking** [jOOQ/jOOQ#4134]
I have high precision dates stored in an SQLite.
```
2015-03-05 10:23:13.333
```
However the milliseconds value is lost.
Thanks.

org.jooq.impl.DefaultBinding(L:1866)
```java
if (timestamp != null) {
      return new Timestamp(parse("yyyy-MM-dd HH:mm:ss", timestamp));
}
```
org.xerial:sqlite-jdbc:3.8.7

org.jooq:jooq:3.5.3

**Comment by lukaseder** [comment]
Hmm, interesting. I suspect that the fractional seconds are not always reported by Xerial / SQLite, which is why this implementation aimed to stay on the safe side. But we should obviously support fractional sections, if they're present.

**Comment by deepking** [comment]
The timestamp in sqlite 
```
2015-03-30 09:59:08.44
```
is converted to 
```
2015-03-30 09:59:08.044
```
It's the problem of SimpleDateFormat.
[SimpleDateFormat is not parsing the milliseconds correctly](http://stackoverflow.com/questions/7159895/simpledateformat-is-not-parsing-the-milliseconds-correctly)

Is it possible to add the trailing zeros while INSERT?

**Comment by lukaseder** [comment]
Thanks for reporting. I can reproduce this. Unfortunately, our integration tests used a timestamp like `2015-02-02 15:30:45.123`, with no trailing zeros. When inserting a timestamp like `2015-02-02 15:30:45.100`, I get the same issue.

I'll handle this as a bug in a new issue.

**Comment by lukaseder** [comment]
... in fact, I don't even know why we're using `SimpleDateFormat` at all. `Timestamp.valueOf()` works just as well

**Comment by lukaseder** [comment]
... it was because of `Date` being sent as `yyyy-mm-dd hh:mm:ss`, which couldn't be parsed by `Date.valueOf()`, but could be parsed by `SimpleDateFormat`.

Let's stay clear of `SimpleDateFormat` and handle the special `Date` case.
