### ISSUE TITLE
Add support for specifying the encoding when loading CSV or JSON with the Loader API

### ISSUE THREAD

**Issue by fge** [jOOQ/jOOQ#4141]
Section 5.11.1 gives an example of a CSV import which looks like this:

```java
create.loadInto(AUTHOR)
      .loadCSV(inputstream)
     // etc
```

Now, the problem is twofold:

* this doesn't account for the encoding of the CSV file at all;
* when looking at the available methods (JooQ 3.5.3), I see that there exists the following methods: .loadCsv(File), .loadCsv(InputStream), .loadCsv(Reader).

Only the latter can potentially take the system encoding into account.

My suggestion is that the two other methods add a Charset as an argument so as to be able to read CSVs not encoded with the current system's default encoding.

While I have not tested this, I am quite sure this can lead to problems...

**Comment by lukaseder** [comment]
Thanks for your feature request. In fact, this isn't about the documentation, but merely about missing functionality? You're right, of course. We should offer to specify the encoding in the API

**Comment by fge** [comment]
Well, I do see the documentation as a potential problem too since in many cases you get CSVs from external sources.

If you're on a Windows OS, for instance, and you get a CSV encoded in UTF-8 which happens to have characters whose encoded form differs from that of cp-1252 you're basically screwed...

**Comment by lukaseder** [comment]
I understand. But when we add the functionality, we can also fix the documentation to document the new functionality...

**Comment by lukaseder** [comment]
Fixed. Thanks for reporting this nice catch! I've also added a small remark to the documentation of 3.5 and less. The documentation in 3.6 will read:

```java
create.loadInto(AUTHOR)
      .loadCSV(inputstream, encoding)
     // etc
```

This should make it clear

**Comment by lukaseder** [comment]
Interesting question, by the way: http://stackoverflow.com/q/29086758/521799.

I guess, it wouldn't be too unreasonable to also support a listener API for you to listen to loading progress: https://github.com/jOOQ/jOOQ/issues/4143 We'll implement that as well for jOOQ 3.6
