### ISSUE TITLE
generator:add marker interface to pojos

### ISSUE THREAD

**Issue by hepin1989** [jOOQ/jOOQ#4142]
how about add support to adding marker interface to the generated pojos?
like ```public interface Message{}``` and then will generate pojo like 
```public class Pojo implement Message{}```
this will be handy

**Comment by lukaseder** [comment]
This is covered by the generator strategy feature:
http://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy

You have to implement (just an example):

```java
@Override
public List<String> getJavaClassImplements(Definition definition, Mode mode) {
    return Arrays.asList(Serializable.class.getName(), Cloneable.class.getName());
}
```

**Comment by hepin1989** [comment]
thank you ,very much
