### ISSUE TITLE
Add onRow(LoaderRowListener) to the Loader API

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4143]
jOOQ's `Loader` API might be used for long running operations, where users might want to know how far they've progressed. There should be a way to register a callback that will get a status update after each load.

----
See also:
http://stackoverflow.com/q/29086758/521799

**Comment by lukaseder** [comment]
@fge: Perhaps this new API will resolve your issues from http://stackoverflow.com/q/29086758/521799 ...?

**Comment by fge** [comment]
Uhm, I'd have to test it; from this patch alone I don't really see how do create a `Loader` to begin with ;)

As a completely unrelated side note, I noticed that there could be a better API to map columns to either booleans or enums; for instance (out of the wild):

```java
// Here the Field is a Field<String>
Mappers.map(someField).toBoolean("valueForTrue", "valueForFalse");
// Here the Field is a Field<Integer>
Mappers.map(someField).toBoolean(1, 0);
// Here the Field is a Field<Integer>
Mappers.map(someField).toEnum(theEnumClass).byOrdinal();
// Here the Field is a Field<String>
Mappers.map(someField).toEnum(theEnumClass).byName();
// A Field<String> again...
Mappers.map(someField).toEnum(theEnumClass).usingToString();
```

**Comment by lukaseder** [comment]
> Uhm, I'd have to test it; from this patch alone I don't really see how do create a Loader to begin with

No worries. jOOQ 3.6 will be out soon (April-ish), so you can play around with it, then.

> As a completely unrelated side note

Interesting. Would be a nice API addition for those users that aren't using the source code generator. Would you mind creating a new issue / feature request for that?
