### ISSUE TITLE
Add <immutablePojosPublicFields/> to generate case-class style POJOs

### ISSUE THREAD

**Issue by hepin1989** [jOOQ/jOOQ#4150]
I want to set the generated pojo's filed's accessibility,current is private,for the immutable one,I want to make the field be public,so that when I am using reflectasm,it will be quicker,

**Comment by lukaseder** [comment]
That certainly makes sense to add as a code generation option in addition to the existing ones.

If you want that behaviour already today, you can override the relevant `JavaGenerator.generatePojo()` method(s) to generate alternative POJO styles.

**Comment by hepin1989** [comment]
thank @lukaseder ，I will take a try.:P

**Comment by lukaseder** [comment]
This is duplicated / covered by #3821
