### ISSUE TITLE
Allow for specifying an external location for the jOOQ code generator configuration

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4163]
This is useful mainly when using jOOQ with Maven.

---

See also:
http://stackoverflow.com/q/29379703/521799

**Comment by ooxi** [comment]
I'm not entirely convinced, that having an external custom types declaration adds any value. The user said he has so many custom types that the pom gets too large an he's annoyed by that.

The correct thing to do would be splitting up the project and having one module just for the jOOQ generated code.

**Comment by lukaseder** [comment]
> The correct thing to do would be splitting up the project and having one module just for the jOOQ generated code.

True. Nonetheless, there might be a nice feature out there somewhere. Just because there is an issue doesn't mean there will be an implementation. We just don't want to forget anything...

**Comment by mischak** [comment]
This issue is solved with #5477 in version 3.9. Thanks for the Christmas present :)

**Comment by lukaseder** [comment]
@mischak : Merry Christmas and a Happy New Year to you! :)

**Comment by lukaseder** [comment]
Closed as duplicate of #5477
