### ISSUE TITLE
Generate varargs setters for array types on interfaces / records / pojos, etc.

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4164]
On generated interfaces / records / pojos, etc. we should generate a varargs setter for array types. For instance:

```sql
CREATE TABLE t_arrays (
  id integer not null,
  string_array VARCHAR(20)[],
)
```

This should produce:

```java
interface TArrays {
    Integer getId();
    void setId(Integer id);

    String[] getStringArray();
    void setStringArray(String... stringArray);
}
```

**Comment by axelfontaine** [comment]
+1 This is really a low hanging fruit that nicely improves readability!

**Comment by lukaseder** [comment]
Deal!

**Comment by lukaseder** [comment]
@axelfontaine Unfortunately, this was a terrible idea. Have you run into simmilar issues as https://github.com/jOOQ/jOOQ/issues/5733?

**Comment by axelfontaine** [comment]
No, but the issue described there really only applies to types that are already arrays (byte arrays in that case). For that this is no good, for all others it is a clear win.

**Comment by lukaseder** [comment]
What do you mean by "others"?

**Comment by axelfontaine** [comment]
All other types (String, Integer, MyCustomType, ...)

**Comment by lukaseder** [comment]
But why would they be varargs? They're all single-arity types, not ... well ... arrays :)

**Comment by lukaseder** [comment]
OK, so you just mute the warning, then?

**Comment by axelfontaine** [comment]
In my current situation I have a couple of methods that are now generated as `setAbc(String... value)` and they produce no warnings in IntelliJ. I don't have the byte[] case.

**Comment by lukaseder** [comment]
Oh really, they produce no warnings in IntelliJ? That's interesting. Also not when building with Maven / javac?

**Comment by axelfontaine** [comment]
No warnings in Maven with javac either.

Note that I am only using Records, no POJOs or DAOs.

**Comment by lukaseder** [comment]
Interesting. There should be a warning in the records too. Perhaps, your tables have more than 22 columns (in case of which the records wouldn't implement `Record[N]<T1, T2, ..., T[N]>`?
