### ISSUE TITLE
Add support for MySQL's mandatory ON clause in the DROP INDEX statement

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4179]
MySQL's `DROP INDEX` statement has a mandatory `ON` clause, as index names are not unique:
https://dev.mysql.com/doc/refman/5.7/en/drop-index.html

**Comment by frodnix** [comment]
Now jooq have the following problem - I can't code database-independent `DROP INDEX`. I suppose the correct way should be `dropIndex(indexName).on(tableName)` and jooq should produce `ON` clause for MySQL and no `ON` clause for other databases.

**Comment by lukaseder** [comment]
You're right, thank you very much for the hint. Indeed, we'll do that for jOOQ 3.10. I've created a separate feature request: https://github.com/jOOQ/jOOQ/issues/6258
