### ISSUE TITLE
ExecuteType.BATCH JavaDoc: not yet supported

### ISSUE THREAD

**Issue by Quurks** [jOOQ/jOOQ#4185]
```java
public enum ExecuteType {
    // [...]
    /**
     * A batch statement is being executed (not yet supported)
     */
    BATCH,
    // [...]
}
```

"not yet supported" is either obsolete (BATCH is returned in DefaultExecuteContext), or it should be specified what exactly is not supported

**Comment by lukaseder** [comment]
Interesting, yes that Javadoc has been obsolete for a while. Thanks for reporting!
