### ISSUE TITLE
Generated Record.values() does nothing

### ISSUE THREAD

**Issue by Quurks** [jOOQ/jOOQ#4190]
The generated implementation of a record for values() just returns the record, it doesn't set any values

https://github.com/jOOQ/jOOQ/blob/master/jOOQ-codegen/src/main/java/org/jooq/util/JavaGenerator.java#L1059-L1062 (same for scala)

Introduced in babb0a4f49a05287e8bc82c9300089059b4c7805

**Comment by lukaseder** [comment]
Interesting... Thanks for reporting!
