### ISSUE TITLE
Cannot stack <forcedTypes> with Converters or Bindings.

### ISSUE THREAD

**Issue by LassoMike** [jOOQ/jOOQ#4208]
I have a use-case where I need to set a MySQL "0000-00-00" date on a non-nullable field so i forced the type to VARCHAR; however, i must also use a Converter on top of that to apply some extra data transformations. Currently you can only do one or the other, not both. (The Converter forces me to use java.sql.Date and the only way to set "0000-00-00" with it is to make it null...this throws errors on a non-nullable field). 

It would be nice to be able to force a type and then be able to apply a Converter(http://www.jooq.org/doc/3.5/manual/sql-execution/fetching/data-type-conversion/) or Binding(http://www.jooq.org/doc/3.5/manual/code-generation/custom-data-type-bindings/) on top of that.

**Comment by lukaseder** [comment]
Thanks for reporting. I think this is a duplicate, but I can't seem to find the other issue. But we're aware of this limitation.

You *can* use an `org.jooq.Binding<java.sql.Date, YourType>`, though. This doesn't mean that you will actually have to use the `java.sql.Date` type. The details of this aren't well documented, we're working on that. We'll soon show similar examples with `BLOB` and `CLOB` types.

**Comment by LassoMike** [comment]
thanks Lukas!

**Comment by lukaseder** [comment]
Sure. Let me know if you're interested in an actual example. I think your case would also be interesting for the manual... What extra data transformations did you intend to do?

**Comment by LassoMike** [comment]
**This entire example assumes that you are working with a NON-NULLABLE Date field in MySQL and your JDBC connector string has zeroDateTimeBehavior=convertToNull (JDBC will convert MySQL's DATE from "0000-00-00" to NULL since "0000-00-00" is not a valid Java date).**

I completely understand if the case below seems incredibly crazy and specific so a more useful and generic one would be having a user passing in an Optional<Date> and then have the binding store the date as "0000-00-00" if the Optional is empty or as the regular date if it's not. This case would still require the Date to be generated as a VARCHAR/String since the DB column would still be non-nullable.

As for my actual use case, for legacy reasons, it is kind of insane. I have a NON-NULLABLE Date field in MySQL, instead of nulls it will store a zero date. It is used to store birthdays. We have decided that we are no longer interested in the year so the input will be a date in the form "mm/dd". If birthday is blank the database should store it as "0000-00-00" and if it isn't it would be "2015-04-21" (the year will be set to the current year).

Here is the Binding code that I wrote to do just that. It doesn't work because Jooq is looking for a BindingClass with the signature:  

```
public final class BirthdayBinding implements Binding<Date, String>
```

Actual Binding class:
```
public final class BirthdayBinding implements Binding<String, String> {
    @Override
    public Converter<String, String> converter() {
        return new Converter<String, String>() {
            @Override
            public String from(final String databaseObject) {
                return Optional.ofNullable(databaseObject == null ? null : LocalDate.parse(databaseObject))
                        .map(
                                x -> (x.getMonthValue() < 10 ? "0" + x.getMonthValue() : x.getMonthValue()) + "/" +
                                        (x.getDayOfMonth() < 10 ? "0" + x.getDayOfMonth() : x.getDayOfMonth())
                        )
                        .orElse("");
            }

            @Override
            public String to(final String userObject) {
                if ("".equals(userObject) ||
                        userObject == null ||
                        "0000-00-00".equals(userObject)) {
                    return "0000-00-00";
                } else {
                    return new java.sql.Date(
                            Instant.parse(
                                    StringUtils.replace(
                                            ZonedDateTime.now().getYear() +
                                                    "-" + userObject + "T00:00:00.00Z",
                                            "/",
                                            "-"
                                    ))
                                    .toEpochMilli()
                    ).toString();
                }
            }

            @Override
            public Class<String> fromType() {
                return String.class;
            }

            @Override
            public Class<String> toType() {
                return String.class;
            }
        };
    }

    @Override
    public void sql(final BindingSQLContext<String> ctx) throws SQLException {
        ctx.render().visit(DSL.val(ctx.convert(converter()).value())).sql("?");
    }

    @Override
    public void register(final BindingRegisterContext<String> ctx) throws SQLException {
        ctx.statement().registerOutParameter(ctx.index(), Types.VARCHAR);
    }

    @Override
    public void set(final BindingSetStatementContext<String> ctx) throws SQLException {
        ctx.statement().setString(ctx.index(), Objects.toString(ctx.convert(converter()).value(), null));
    }

    @Override
    public void set(final BindingSetSQLOutputContext<String> ctx) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public void get(final BindingGetResultSetContext<String> ctx) throws SQLException {
        ctx.convert(converter()).value(ctx.resultSet().getString(ctx.index()));
    }

    @Override
    public void get(final BindingGetStatementContext<String> ctx) throws SQLException {
        ctx.convert(converter()).value(ctx.statement().getString(ctx.index()));
    }

    @Override
    public void get(final BindingGetSQLInputContext<String> ctx) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }
}
```

I have tried setting the forced types like this, but only the Birthday one works:

```
<forcedType>
    <name>Birthday</name>
    <expression>
        .*\.[Ii]s[A-Z].*|
        (?i:people\.dob)
    </expression>
    <types>(?i:DATE(\s*\(\d+\))?(\s*UNSIGNED)?)</types>
</forcedType>
<forcedType>
    <name>VARCHAR</name>
    <expression>
        .*\.[Ii]s[A-Z].*|
        (?i:people\.dob)
    </expression>
    <types>(?i:DATE(\s*\(\d+\))?(\s*UNSIGNED)?)</types>
</forcedType>
```

Here is the customType for completion:

```
<customType>
    <name>Birthday</name>
    <type>java.lang.String</type>
    <converter>com.lasso.jooq.BirthdayConverter</converter>
</customType>
```

Sorry for the super long post! I hope we can help each other out :D.

**Comment by lukaseder** [comment]
Thank you very much for the detailed feedback. This is indeed very helpful. I'll be looking into this next week, hopefully.

**Comment by saem** [comment]
Hi @lukaseder, we're running into this issue in more and more places as we're trying to convert away from hibernate to jooq. Unfortunately, we have a number of datetime fields (that can't be migrated for various reasons), that are non-nullable, but have "0000-00-00 00:00:00" values. Reading them out as nulls, via the JDBC driver parameter, and using a forced type that wraps them in an optional makes that side easy enough to handle. However, writes are still problematic, we need empty/null values to be converted to a "0000-00-00 00:00:00" when they're heading into the database.

Being able to use forced types and bindings (as attempted here) seems like it would address this as well, so I decided to add the use case, I hope that's the right thing to do.

**Comment by lukaseder** [comment]
@saem, @LassoMike : I'm sorry for the delay - this issue got off my radar somehow.

From the jOOQ side, you *could* implement a `Binding<Date, String>`, or `Binding<Date, Optional<String>>`, and not use the `Binding.converter()` for data type conversion, but interact with JDBC directly. Is that an option in your cases?

Another idea would be to implement a database trigger, that "cleans up" `NULL` values into `0000-00-00...` on `INSERT OR UPDATE`. This is interesting anyway, as other (non-Java) applications or SQL Workbench clients, etc. might also access the database.

Clearly, stacking forced types as originally requested will be the most useful feature. However, I'm currently not sure if that is possible to implement.

**Comment by saem** [comment]
Thanks, @lukaseder.

We ended up going the Binding route, and dealt with JDBC directly.

**Comment by lukaseder** [comment]
Closing this as worksforme as the `Binding` route offers sufficient functionality here
