### ISSUE TITLE
Support for Teradata

### ISSUE THREAD

**Issue by jeremieSimon** [jOOQ/jOOQ#4209]
Hi, 

I would love it if you could add support for Teradata in your Dialects.
If you take PR, I can try to add that. 
Let me know

Thanks

**Comment by lukaseder** [comment]
Thanks for your interest in jOOQ and for asking.

This is a duplicate of:

- https://github.com/jOOQ/jOOQ/issues/629 (Teradata support)
- https://github.com/jOOQ/jOOQ/issues/2862 (Teradata Aster support)

Support will not make it into the upcoming (next week's) jOOQ 3.6, but we might be able to make Teradata a priority for jOOQ 3.7 under the terms of the jOOQ Enterprise Edition.

**Comment by jeremieSimon** [comment]
@lukaseder , thanks for your quick reply. 
Do you guys take PR from non jooq guy?

**Comment by lukaseder** [comment]
Yes, we do accept smaller contributions under these terms: http://www.jooq.org/legal/contributions (which allow us to dual license jOOQ).

Depending on the contribution size, we're also willing to offer discounts on our commercial subscriptions. Does this sound interesting to you?

**Comment by jeremieSimon** [comment]
Yes, very. Not necessary interesting in the discount :)
I really like what you guys did, so I'd love helping to get that feature roll out in the coming version.

**Comment by lukaseder** [comment]
A vendor's dream! I will be contacting you within the next days to discuss details. Is the E-Mail address given here OK? https://github.com/jeremieSimon

**Comment by jeremieSimon** [comment]
Yes that address is good. 
Cool, I'll wait for your email. 

Thanks!
