### ISSUE TITLE
ORA-00904: "SYS"."ALL_PROCEDURES"."OBJECT_ID": invalid identifier when using the code generator with Oracle 10g

### ISSUE THREAD

**Issue by lastcmaster** [jOOQ/jOOQ#4224]
select * from V$VERSION;
Oracle Database 10g Enterprise Edition Release 10.2.0.1.0 - Prod
PL/SQL Release 10.2.0.1.0 - Production
"CORE	10.2.0.1.0	Production"
TNS for Linux: Version 10.2.0.1.0 - Production
NLSRTL Version 10.2.0.1.0 - Production

+ java -cp /Users/glz/.m2/repository/org/jooq/jooq/3.6.0/jooq-3.6.0.jar:/Users/glz/.m2/repository/org/jooq/jooq-meta/3.6.0/jooq-meta-3.6.0.jar:/Users/glz/.m2/repository/org/jooq/jooq-codegen/3.6.0/jooq-codegen-3.6.0.jar:/Users/glz/.m2/repository/com/oracle/ojdbc/11.2.0.3/ojdbc-11.2.0.3-jdk6.jar:. org.jooq.util.GenerationTool /tstheap.xml
Apr 23, 2015 2:41:44 PM org.jooq.tools.JooqLogger info
INFO: Initialising properties  : /tstheap.xml
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: License parameters       
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   Thank you for using jOOQ and jOOQ's code generator
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:                          
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: Database parameters      
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   dialect                : ORACLE
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   URL                    : jdbc:oracle:thin:@lora.hq.ismobile.com:1521:orcl
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   target dir             : test
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   target package         : com.ismobile.test.heap
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   includes               : [.*]
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   excludes               : []
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   includeExcludeColumns  : false
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:                          
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: DefaultGenerator parameters
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   strategy               : class org.jooq.util.DefaultGeneratorStrategy
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   deprecated             : true
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   generated annotation   : true
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   JPA annotations        : false
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   validation annotations : false
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   instance fields        : true
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   records                : true
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   pojos                  : false
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   immutable pojos        : false
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   interfaces             : false
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   daos                   : false
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   relations              : true
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   global references      : true
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:                          
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: Generation remarks       
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:   none                   
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO:                          
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: Generating schemata      : Total: 1
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: No schema version is applied for schema VFTEST. Regenerating.
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: Generating schema        : Vftest.java
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: Sequences fetched        : 0 (0 included, 0 excluded)
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: Tables fetched           : 1 (1 included, 0 excluded)
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: UDTs fetched             : 0 (0 included, 0 excluded)
Apr 23, 2015 2:41:45 PM org.jooq.tools.JooqLogger info
INFO: Generating tables        
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Synthetic primary keys   : 0 (0 included, 0 excluded)
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Overriding primary keys  : 1 (0 included, 1 excluded)
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Generating table         : Tstheap.java [input=TSTHEAP, output=TSTHEAP, pk=SYS_C00608743]
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: ARRAYs fetched           : 0 (0 included, 0 excluded)
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Enums fetched            : 0 (0 included, 0 excluded)
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Tables generated         : Total: 1.608s
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Generating table references
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Table refs generated     : Total: 1.611s, +2.256ms
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Generating Keys          
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Keys generated           : Total: 1.614s, +3.143ms
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Generating table records 
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Generating record        : TstheapRecord.java
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Table records generated  : Total: 1.625s, +11.633ms
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger warn
WARNING: SQL exception            : Exception while executing meta query: ORA-00904: "SYS"."ALL_PROCEDURES"."OBJECT_ID": invalid identifier

Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new

select 
  "SYS"."ALL_OBJECTS"."OWNER", 
  "SYS"."ALL_OBJECTS"."OBJECT_NAME", 
  "SYS"."ALL_OBJECTS"."OBJECT_ID", 
  "SYS"."ALL_PROCEDURES"."AGGREGATE"
from "SYS"."ALL_OBJECTS"
  left outer join "SYS"."ALL_PROCEDURES"
  on (
    "SYS"."ALL_OBJECTS"."OWNER" = "SYS"."ALL_PROCEDURES"."OWNER"
    and "SYS"."ALL_OBJECTS"."OBJECT_ID" = "SYS"."ALL_PROCEDURES"."OBJECT_ID"
    and "SYS"."ALL_OBJECTS"."OBJECT_NAME" = "SYS"."ALL_PROCEDURES"."OBJECT_NAME"
  )
where (
  upper("SYS"."ALL_OBJECTS"."OWNER") in ('VFTEST')
  and "SYS"."ALL_OBJECTS"."OBJECT_TYPE" in (
    'FUNCTION', 'PROCEDURE'
  )
)
order by 
  "SYS"."ALL_OBJECTS"."OWNER" asc, 
  "SYS"."ALL_OBJECTS"."OBJECT_NAME" asc, 
  "SYS"."ALL_OBJECTS"."OBJECT_ID" asc
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger error
SEVERE: Error while fetching functions
org.jooq.exception.DataAccessException: SQL [select "SYS"."ALL_OBJECTS"."OWNER", "SYS"."ALL_OBJECTS"."OBJECT_NAME", "SYS"."ALL_OBJECTS"."OBJECT_ID", "SYS"."ALL_PROCEDURES"."AGGREGATE" from "SYS"."ALL_OBJECTS" left outer join "SYS"."ALL_PROCEDURES" on ("SYS"."ALL_OBJECTS"."OWNER" = "SYS"."ALL_PROCEDURES"."OWNER" and "SYS"."ALL_OBJECTS"."OBJECT_ID" = "SYS"."ALL_PROCEDURES"."OBJECT_ID" and "SYS"."ALL_OBJECTS"."OBJECT_NAME" = "SYS"."ALL_PROCEDURES"."OBJECT_NAME") where (upper("SYS"."ALL_OBJECTS"."OWNER") in (?) and "SYS"."ALL_OBJECTS"."OBJECT_TYPE" in (?, ?)) order by "SYS"."ALL_OBJECTS"."OWNER" asc, "SYS"."ALL_OBJECTS"."OBJECT_NAME" asc, "SYS"."ALL_OBJECTS"."OBJECT_ID" asc]; ORA-00904: "SYS"."ALL_PROCEDURES"."OBJECT_ID": invalid identifier

	at org.jooq.impl.Utils.translate(Utils.java:1644)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:661)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:356)
	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:290)
	at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2316)
	at org.jooq.util.oracle.OracleDatabase.getRoutines0(OracleDatabase.java:436)
	at org.jooq.util.AbstractDatabase.getRoutines(AbstractDatabase.java:905)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:367)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:268)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:426)
	at org.jooq.util.GenerationTool.generate(GenerationTool.java:176)
	at org.jooq.util.GenerationTool.main(GenerationTool.java:151)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "SYS"."ALL_PROCEDURES"."OBJECT_ID": invalid identifier

	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:445)
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:879)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:450)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:884)
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1167)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1289)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3584)
	at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3685)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1376)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:194)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:247)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:342)
	... 9 more
Apr 23, 2015 2:41:46 PM org.jooq.tools.JooqLogger info
INFO: Packages fetched         : 0 (0 included, 0 excluded)
Apr 23, 2015 2:41:47 PM org.jooq.tools.JooqLogger info
INFO: Queues fetched           : 0 (0 included, 0 excluded)
Apr 23, 2015 2:41:47 PM org.jooq.tools.JooqLogger info
INFO: Removing excess files    
Apr 23, 2015 2:41:47 PM org.jooq.tools.JooqLogger info
INFO: GENERATION FINISHED: VFTEST: Total: 1.823s, +197.121ms

**Comment by lukaseder** [comment]
Thank you very much for reporting. We'll look into this right away

**Comment by lukaseder** [comment]
... just to be sure, what Oracle version are you using?

**Comment by lastcmaster** [comment]
V$VERSION:
Oracle Database 10g Enterprise Edition Release 10.2.0.1.0 - Prod
PL/SQL Release 10.2.0.1.0 - Production
"CORE	10.2.0.1.0	Production"
TNS for Linux: Version 10.2.0.1.0 - Production
NLSRTL Version 10.2.0.1.0 - Production

**Comment by lukaseder** [comment]
Thanks for the info. The code generator is currently only integration-tested with Oracle 11g. This has caused issues in the past as well. While the runtime library isn't really affected much by the differences between 10g and 11g, the code generator might be, as we're querying dictionary views that might not have been available at the time.

In fact, this is a regression of #1683. I'll investigate a potential fix.

Also, there might be a useful new feature derived from these findings. People are probably interested in maintaining different versions of their schemas, not just dictionary views, but also for their own data. It would be good if columns could be annotated with a custom version number - or perhaps there are other means to handle this. I've created a feature request for that particular idea: #4232

**Comment by lukaseder** [comment]
I've just noticed that the `ALL_PROCEDURES.OVERLOAD` column isn't available in 10g either. We use that to order overloaded package procedures. I suspect the `OVERLOAD` index can be emulated using

```sql
select 
  OWNER, OBJECT_NAME, PROCEDURE_NAME,
  ROW_NUMBER() OVER(PARTITION BY OWNER, OBJECT_NAME, PROCEDURE_NAME) OVERLOAD
from
  ALL_PROCEDURES
```

Although the generated indexes might not always be deterministic... Before implementing #4157, jOOQ used the `ALL_ARGUMENTS` table to find that `OVERLOAD` ([supported in 10g](http://docs.oracle.com/cd/B19306_01/server.102/b14237/statviews_1014.htm#REFRN20015)), but not all procedures are listed in `ALL_ARGUMENTS` (hence, #4157)

**Comment by lukaseder** [comment]
The fixed query to fetch standalone procedures is now:

```sql
select 
  "SYS"."ALL_OBJECTS"."OWNER", 
  "SYS"."ALL_OBJECTS"."OBJECT_NAME", 
  "SYS"."ALL_OBJECTS"."OBJECT_ID", 
  "SYS"."ALL_PROCEDURES"."AGGREGATE"
from "SYS"."ALL_OBJECTS"
  left outer join "SYS"."ALL_PROCEDURES"
  on (
    "SYS"."ALL_OBJECTS"."OWNER" = "SYS"."ALL_PROCEDURES"."OWNER"
    and "SYS"."ALL_OBJECTS"."OBJECT_NAME" = "SYS"."ALL_PROCEDURES"."OBJECT_NAME"
  )
where (
  upper("SYS"."ALL_OBJECTS"."OWNER") in (
    -- list input schemas here
  )
  and "SYS"."ALL_OBJECTS"."OBJECT_TYPE" in (
    'FUNCTION', 'PROCEDURE'
  )
)
order by 
  "SYS"."ALL_OBJECTS"."OWNER" asc, 
  "SYS"."ALL_OBJECTS"."OBJECT_NAME" asc, 
  "SYS"."ALL_OBJECTS"."OBJECT_ID" asc
```

The fixed query

```sql
select distinct 
  "SYS"."ALL_PROCEDURES"."PROCEDURE_NAME", 
  "SYS"."ALL_OBJECTS"."OBJECT_ID", 
  "SYS"."ALL_ARGUMENTS"."OVERLOAD"
from "SYS"."ALL_OBJECTS"
  join "SYS"."ALL_PROCEDURES"
  on (
    "SYS"."ALL_OBJECTS"."OWNER" = "SYS"."ALL_PROCEDURES"."OWNER"
    and "SYS"."ALL_OBJECTS"."OBJECT_NAME" = "SYS"."ALL_PROCEDURES"."OBJECT_NAME"
  )
  left outer join "SYS"."ALL_ARGUMENTS"
  on (
    "SYS"."ALL_ARGUMENTS"."OWNER" = "SYS"."ALL_PROCEDURES"."OWNER"
    and "SYS"."ALL_ARGUMENTS"."PACKAGE_NAME" = "SYS"."ALL_PROCEDURES"."OBJECT_NAME"
    and "SYS"."ALL_ARGUMENTS"."OBJECT_NAME" = "SYS"."ALL_PROCEDURES"."PROCEDURE_NAME"
  )
where (
  "SYS"."ALL_OBJECTS"."OWNER" in ( /* input schema here */ )
  and "SYS"."ALL_OBJECTS"."OBJECT_TYPE" = 'PACKAGE'
  and "SYS"."ALL_PROCEDURES"."PROCEDURE_NAME" is not null
  and "SYS"."ALL_PROCEDURES"."OBJECT_NAME" = /* package name here */
)
order by 
  "SYS"."ALL_PROCEDURES"."PROCEDURE_NAME" asc, 
  "SYS"."ALL_ARGUMENTS"."OVERLOAD" asc
```

Can you confirm these queries work on Oracle 10g?
