### ISSUE TITLE
Add Result.formatCSV(boolean) (and related convenience methods) to avoid header

### ISSUE THREAD

**Issue by craigsoules** [jOOQ/jOOQ#4239]
Hello,

I'll start by saying that jOOQ is amazing, and thank you so much for your work on it!

It would be great to have an option in the Result.formatCSV() calls to have the CSV generated without a header.  This would be especially useful when trying to write CSV of result sets that don't fit in memory, since I can use the Cursor class to retrieve the results lazily, but when I use the formatCSV() each result batch gets it's own set of headers, which makes it hard to append to the previous batch...

Thanks so much!
Craig

**Comment by lukaseder** [comment]
Thanks for your nice words. Yes, that would probably be useful. As a workaround, you could use the `formatCSV(Writer)` overload and implement your own `Writer` that just skips the first row (i.e. until the first encounter of a `\n`)

**Comment by ooxi** [comment]
Maybe I'm missing something (reasing your commit on mobile) butvI think you've omitted the `@param` documentation for `header`

**Comment by lukaseder** [comment]
Nice catch!
