### ISSUE TITLE
daoImplements option in MatcherStrategy not generating an implements statement in DAO class

### ISSUE THREAD

**Issue by mikereinhold** [jOOQ/jOOQ#4248]
The *JavaGenerator.generateDao(TableDefinition table, JavaWriter out)* method is not outputting the *implements* statement as part of the class definition (lines 2113 & 2116 of JavaGenerator). As a result, the _daoImplements_ Table MatcherStrategy option is not functioning properly - the generated DAO does not implement the specified interface as expected.

Ex.

```xml
<table>
     <expression>EXAMPLE</expression>
     <pojoExtends>com.example.AbstractExample</pojoExtends>
    <pojoImplements>com.example.Example</pojoImplements>
    <daoImplements>com.example.ExampleDao</daoImplements>
</table>
```

The POJO will have the correct base class and interfaces, however the DAO does not have the expected interface.

**Comment by mikereinhold** [comment]
Looks like this issue is present in both 3.5 and 3.6 minor versions - I haven't gone back to older versions to confirm.

**Comment by lukaseder** [comment]
Thank you very much for reporting!

**Comment by mikereinhold** [comment]
My pleasure! 

I have the proposed changes in my fork [here](https://github.com/mikereinhold/jOOQ/commit/22ad5a2cd31d4608498c694562153922069e2fd1#diff-aaa83edc55e463bc44fecee3fc51fa3e).

I can submit this as a PR once I've tested more thoroughly.

**Comment by lukaseder** [comment]
Oops, I'm sorry. Didn't see the fork in time :) There had been two more related issues:

1. This line here: https://github.com/mikereinhold/jOOQ/commit/22ad5a2cd31d4608498c694562153922069e2fd1#diff-aaa83edc55e463bc44fecee3fc51fa3eR2072 would've caused NPE when there are no primary keys in the table
2. `DefaultGeneratorStrategy` contained some old, never-executed code that generated a wrong interface specification. I don't know where that came from...

**Comment by mikereinhold** [comment]
No worries! Just glad to see it's fixed :) Thanks!

**Comment by lukaseder** [comment]
You're welcome
