### ISSUE TITLE
Deprecate support for JPA annotations in DefaultRecordMapper

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4263]
Mapping is not jOOQ's business. We believe that mapping should be done using functional interfaces and streams:
http://blog.jooq.org/2014/04/11/java-8-friday-no-more-need-for-orms

We also believe that JPA's annotation-based approach is extremely limited and non-expressive:
http://blog.jooq.org/2015/04/15/how-jpa-2-1-has-become-the-new-ejb-2-0

The consequence for jOOQ's long-term strategy is to:

- Offer more simple out-of-the-box mapping algorithms in `DefaultRecordMapper` (e.g. via nested records: #2360 and multisets: #3884)
- Blog more about useful techniques of mapping  / flatmapping tabular results into object hierarchies
- Remove support for JPA annotations in jOOQ
- Blog more about how to use jOOQ with JPA's native query API (for those who want to support JPA annotations) (see also #1843)

We will gradually deprecate JPA annotation usage by adding a new `Setting`, whose default value will enable JPA annotation usage (emitting a warning) in jOOQ 3.7 - changing the default value to disabled in jOOQ 3.8, and removing JPA annotation support in the `DefaultRecordMapper` (and elsewhere) in jOOQ 4.0

**Comment by brmeyer** [comment]
For what it's worth, one of my favorite capabilities in jOOQ was how easy it was to plug it into existing ORM applications.  Supporting a CQRS pattern, without having to strip out the existing DAO architecture, was in my opinion a huge selling point.  I get that it's not your core competency and focus area, but it was definitely an additive feature that was beneficial to new users.

Maybe the integration with the native query API will help...

**Comment by lukaseder** [comment]
Yes, don't get me wrong. We'll continue to invest time into basic mapping functionality, specifically when it's leveraging functional programming techniques. I just don't believe that we should spend any more time implementing JPA annotations, which are a dead end. I'm sure that JPA 3.0 will be very different, and will offer a more explicit / less declarative alternative to annotations. I hope that Hibernate will, too.

In the mean time, those users who already have JPA / Hibernate on their stacks will probably appreciate using jOOQ as a SQL generator only and executing the queries with Hibernate's native query API, and perhaps `SqlResultSetMapping`. In any case, it will work much better than anything we can implement, since we really don't want to spend too much time on those annotations...

**Comment by zellus** [comment]
Using @Column() for getters and setters was key to migrate from eclipselink to jooq in order to generate mappable DTOs. Many getters and setters did not comply with jooq's field name to getter/setter naming convention. I'm looking forward to a more expressive approach as long as one can map field, getter and setter independently.

**Comment by lukaseder** [comment]
@zellus: Interesting point, thanks for sharing!

I guess that we can "save" some functionality over to examples of how to implement the `RecordMapperProvider` SPI. There will also be a new module (soon), called jOOQ-extensions where we'll include API that integrates jOOQ with JPA's native query APIs. It would make sense to ship such a `RecordMapperProvider` implementation in that new module.

**Comment by lukaseder** [comment]
We won't deprecate this support after closer consideration. In a future version, there might not be a dependency towards JPA annotations in `DefaultRecordMapper`, but in a different mapper

**Comment by lukaseder** [comment]
As a follow-up to this discussion, starting from jOOQ 3.20, the JPA annotation support will be extracted into a separate module called `jOOQ-jpa-extensions`, which implements a new SPI for this purpose:

- https://github.com/jOOQ/jOOQ/issues/16500

This best reflects the stance jOOQ has with respect to this historic feature, which shouldn't be part of jOOQ's core (due to the dependencies, etc.) but can be occasionally useful nonetheless.
