### ISSUE TITLE
navigationMethods

### ISSUE THREAD

**Issue by costa974** [jOOQ/jOOQ#4267]
How to resurrect "navigationMethods" generation from version 2.6.
The idea behind JOOQ is good, but without the ability to navigate the object graph is quite useless.

**Comment by lukaseder** [comment]
Thanks for your suggestion. We're already tracking this discussion here: #4210. We don't object navigation of the object graph, but at the time when this was implemented in 2.6, it was implemented very poorly.

If the existence of this feature is a tipping point for whether jOOQ is "useless" or not for you, then I strongly suggest to stick with a classic ORM like Hibernate.

**Comment by lukaseder** [comment]
Duplicate: #4210
