### ISSUE TITLE
Code generation: ERROR: Internal error: unsupported join type: 3

### ISSUE THREAD

**Issue by Azuaron** [jOOQ/jOOQ#4274]
PostgreSQL Java driver 9.4 on Amazon Redshift.

During the org.jooq.util.postgres.PostgresDatabase:getTables0() function (line 286) the following error is thrown:

ERROR: Internal error: unsupported join type: 3

Strangely, it gives me the query it tries to execute, and if I run that query directly against the database I do not get the error.

I'm using Maven, here is the pom config:
```
<plugin>
	<groupId>org.jooq</groupId>
	<artifactId>jooq-codegen-maven</artifactId>
	<version>3.6.1</version>
	<executions>
		<execution>
			<goals>
				<goal>generate</goal>
			</goals>
		</execution>
	</executions>
	<dependencies>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>9.4-1201-jdbc41</version>
		</dependency>
	</dependencies>
	<configuration>
		<!-- JDBC connection parameters -->
		<jdbc>
			<driver>org.postgresql.Driver</driver>
			<url>jdbc:postgresql://redshift.location</url>
			<user>username</user>
			<password>pw</password>
		</jdbc>
		<!-- Generator parameters -->
		<generator>
			<name>org.jooq.util.DefaultGenerator</name>
			<database>
				<name>org.jooq.util.postgres.PostgresDatabase</name>
				<includes>.*</includes>
				<excludes></excludes>
				<inputSchema>schemaName</inputSchema>
			</database>
			<target>
				<packageName>org.jooq.dw.entity</packageName>
				<directory>target/generated-sources/jooq</directory>
			</target>
			<generate>
				<deprecated>false</deprecated>
				<globalObjectReferences>false</globalObjectReferences>
			</generate>
		</generator>
	</configuration>
</plugin>
```

**Comment by lukaseder** [comment]
Thanks for reporting this. I'm assuming you're trying to use the PostgreSQL dialect to run the code generator against an Amazon Redshift instance? We're currently adding official support for Redshift (see #2728). I've also encountered this particular issue recently. It has to do with bind variables being put in certain join predicates, and was probably a bug in old PostgreSQL versions (which Redshift inherited). Our integration tests for jOOQ 3.7 no longer suffer from this issue...

**Comment by Azuaron** [comment]
Yes, Postgres 9.4. I've extended the PostgresDatabase class, and was able to "fix" the error by commenting out 
```
281: .and(PG_PROC.PRONAME.concat("_").concat(oid(PG_PROC)).eq(ROUTINES.SPECIFIC_NAME))
```
and changing 
```
268: .where(TABLES.TABLE_SCHEMA.in(getInputSchemata()))
.
.
282: .where(ROUTINES.ROUTINE_SCHEMA.in(getInputSchemata()))
```
To use a CustomCondition that builds the IN clause without parameter injection.

**Comment by lukaseder** [comment]
Hmm, yes... Well, Redshift doesn't support stored procedures anyway, so the whole `getRoutines0()` method can be commented out.

Also, removing the `UNION` actually did the trick for us (as we don't need to look for table-valued functions, which is the second subquery's intent)

**Comment by lukaseder** [comment]
... I'm closing this issue as it will not appear with the jOOQ 3.7 `SQLDialect.REDSHIFT` dialect.
