### ISSUE TITLE
Document MySQL connector's fetchSize behaviour in ResultQuery.fetchSize()

### ISSUE THREAD

**Issue by gabadi** [jOOQ/jOOQ#4280]
I've a query with 3M rows, so i execute it with a cursor. But it seams like jooq it's keeping all the result in memory because i've GC limit exception during the fecth.

i've tried:
query.fetchLazy(fetchSize)
query.fetchSize(fetchSize).fetchLazy()

but without any success.

Any idea of what may be happening

**Comment by gabadi** [comment]
I love mysql
this solves the mysql jdbc issue: 
query.fetchSize(Integer.MIN_VALUE).fetchLazy()

**Comment by lukaseder** [comment]
Yes, I've stumbled upon this too, in the past. It's a bit annoying to see that in some cases, the JDBC specs isn't implemented correctly... Perhaps, we could add a remark to the Javadoc?

**Comment by lukaseder** [comment]
Interesting caveat with setting `Integer.MIN_VALUE`:
http://stackoverflow.com/a/2448607/521799
