### ISSUE TITLE
Add support for MySQL's STRAIGHT_JOIN

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4281]
See also:
- https://dev.mysql.com/doc/refman/5.7/en/join.html
- https://groups.google.com/forum/#!topic/jooq-user/oE8cduOEM5o

MariaDB seems to support only a `STRAIGHT_JOIN` hint (which can already be used in jOOQ). CUBRID doesn'ts upport `STRAIGHT_JOIN`

**Comment by cotej** [comment]
I'm finding that this feature still is not working in 3.8.2.  Trying to execute a fairly straight-forward query, and my DbDialect is set to MYSQL.
`
ResultSet rs = DSL_CONTEXT
  .select(Tables.EVENT.ID, Tables.EVENT.EVENT_DELIVERY_TIME, Tables.EVENT_CREATOR.SIGNATURE)
  .from(Tables.EVENT.straightJoin(Tables.EVENT_CREATOR).on(Tables.EVENT_CREATOR.ID.eq(Tables.EVENT.EVENT_CREATOR_ID)))
  .orderBy(Tables.EVENT.ID.desc())
  .limit(10)
  .fetchResultSet();
`

Which results in the following exception:
`
java.lang.IllegalArgumentException: Bad join type: STRAIGHT_JOIN
  at org.jooq.impl.JoinTable.translateClause(JoinTable.java:292)
  at org.jooq.impl.JoinTable.accept(JoinTable.java:164)
  ...
`
And it indeed seems like there is no logic to handle STRAIGHT_JOIN in JoinTable.java source

**Comment by lukaseder** [comment]
Thank you very much for reporting. I have created a separate issue for this, which I'll fix immediately:
https://github.com/jOOQ/jOOQ/issues/5380
