### ISSUE TITLE
Error marshalling or unmarshalling a user defined type

### ISSUE THREAD

**Issue by oogifu** [jOOQ/jOOQ#4282]
Hi,

Trying code generation using jOOQ 3.6.1 using the Derby database.
I have the following exception.

WARNING: SQL exception            : Exception while executing meta query: Error marshalling or unmarshalling a user defined type: org.apache
.derby.catalog.types.TypeDescriptorImpl; local class incompatible: stream classdesc serialVersionUID = -5485274209578709396, local class ser
ialVersionUID = -3812847726962874375

Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new

select
  "SYS"."SYSCOLUMNS"."COLUMNNAME",
  "SYS"."SYSCOLUMNS"."COLUMNNUMBER",
  "SYS"."SYSCOLUMNS"."COLUMNDATATYPE",
  "SYS"."SYSCOLUMNS"."COLUMNDEFAULT",
  "SYS"."SYSCOLUMNS"."AUTOINCREMENTINC"
from "SYS"."SYSCOLUMNS"
where "SYS"."SYSCOLUMNS"."REFERENCEID" = 'a8604102-014d-50eb-3a5c-ffff86da659b'
order by "SYS"."SYSCOLUMNS"."COLUMNNUMBER" asc
May 15, 2015 3:34:09 PM org.jooq.tools.JooqLogger warn
WARNING: SQL exception            : Exception while executing meta query: Error marshalling or unmarshalling a user defined type: org.apache
.derby.catalog.types.TypeDescriptorImpl; local class incompatible: stream classdesc serialVersionUID = -5485274209578709396, local class ser
ialVersionUID = -3812847726962874375

Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new

Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new

**Comment by oogifu** [comment]
The above prevents the generation of the tables. 
App, Keys and Tables.java classes are generated.
The records package classes are generated.
However, the .tables package is not generated.
Any idea?

**Comment by lukaseder** [comment]
Thank you very much for reporting this. Interesting, so there are two bugs:

1. The concrete issue that causes the exception
2. The fact that this issue prevents code generation for the complete schema

The latter seems more severe, but in order to analyse this, could you please provide us with some example DDL that can be used to reproduce this issue?

**Comment by oogifu** [comment]
Hi Lukas,

Thanks for getting back to me. I had a fairly big schema.. so I trimmed it down just to one table - see below - and the issue remains. I am using Derby bundled with JDK 8 20 with derby-10.11.1.1.jar and derbyclient-10.11.1.1.jar.
I am using the jooq/meta/codegen -3.6.1.jar.

This is the single table:

create table tbl_MyCustomer (
  uuid varchar(64) not null,
  name varchar(64) not null,
  esc boolean default false,
  max_vol_amount double not null,
  max_nb int not null,
  agg_time varchar(32) not null,
  requests_interval int not null,
  primary key(uuid)
);

The stack trace is still the same:

Exception while executing meta query: Error marshalling or unmarshalling a user defined type: org.apache.derby.catalog.types.TypeDescriptorImpl; local class incompatible: stream classdesc serialVersionUID = -5485274209578709396, local class serialVersionUID = -3812847726962874375

ERROR 2015-05-15 17:38:41,673 JavaGenerator [main] - Error while generating table APP.TBL_MYCUSTOMER
org.jooq.exception.DataAccessException: SQL [select "SYS"."SYSCOLUMNS"."COLUMNNAME", "SYS"."SYSCOLUMNS"."COLUMNNUMBER", "SYS"."SYSCOLUMNS"."COLUMNDATATYPE", "SYS"."SYSCOLUMNS"."COLUMNDEFAULT", "SYS"."SYSCOLUMNS"."AUTOINCREMENTINC" from "SYS"."SYSCOLUMNS" where "SYS"."SYSCOLUMNS"."REFERENCEID" = '9c3e00f1-014d-56ee-d014-ffff86da659b' order by "SYS"."SYSCOLUMNS"."COLUMNNUMBER" asc]; Error marshalling or unmarshalling a user defined type: org.apache.derby.catalog.types.TypeDescriptorImpl; local class incompatible: stream classdesc serialVersionUID = -5485274209578709396, local class serialVersionUID = -3812847726962874375
	at org.jooq.impl.Utils.translate(Utils.java:1644)

...

Thanks

**Comment by oogifu** [comment]
Let me know if you need anything else. Thanks.

**Comment by lukaseder** [comment]
Hmm, to me, this looks like an instance of this issue here:
https://issues.apache.org/jira/browse/DERBY-6785

Is your Derby server also version 10.11.1.1?

**Comment by oogifu** [comment]
Indeed. Thanks. I should have thought about that! It now works. Cheers.

**Comment by lukaseder** [comment]
No worries. In the past, I've encountered similar issues with Derby. Googling the `serialVersionUID` values (`5485274209578709396`, `3812847726962874375`) usually helped, as it did in this case...
