### ISSUE TITLE
Add support for PostgreSQL 9.5

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4299]
Add a new `SQLDialect` to the `POSTGRES` family, and document / implement support for:

- `GROUPING SETS` (including `CUBE` and `ROLLUP`)
- `FOR UPDATE SKIP LOCKED`
- `INSERT .. ON CONFLICT {  UPDATE | DO NOTHING }` (http://www.postgresql.org/docs/9.5/static/sql-insert.html)
- `TABLESAMPLE` (see #2561)

----
see also:
https://wiki.postgresql.org/wiki/What%27s_new_in_PostgreSQL_9.5

**Comment by kbalyasnikov** [comment]
Hi, @lukaseder!

According to implementation in 3.7.0-SNAPSHOT the only supported "conflict" columns a those defined as primary key fields. But PostgreSQL actually supports any column with unique constraints.

**Comment by lukaseder** [comment]
Yes, I'm aware of that. So far, we haven't added explicit support in the jOOQ API yet, but emulated this feature for other syntaxes (H2, MySQL), where primary keys are the only "conflict sources". I'm not quite sure yet about the utility of being able to supply alternative keys. Is this for legacy applications where a primary key is missing for whatever reason?

**Comment by kbalyasnikov** [comment]
For example consider this table definition:

```
CREATE TABLE signup_request (
  token                VARCHAR(32)                                             NOT NULL,
  email                VARCHAR(100)                                            NOT NULL,
  date_of_signup       TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()               NOT NULL,
  date_of_confirmation TIMESTAMP WITHOUT TIME ZONE,
  PRIMARY KEY (token)
);

ALTER TABLE signup_request ADD CONSTRAINT signup_request_uidx_email UNIQUE (email);
```

With Posgres 9.5 i can build upsert query like this:

```
INSERT INTO signup_request (token, email) VALUES('token_value', 'some@email.com') ON CONFLICT(email) DO UPDATE SET token = 'new_token_value';
```

Table and query are from real project i'm working on.

**Comment by lukaseder** [comment]
Interesting, why wouldn't you make `email` the primary key then? It is very uncommon to update the primary key...

**Comment by kbalyasnikov** [comment]
Yes, that would work in this particular case. Thanks. Still i think it would be great if jOOQ will support conflict column or key selection.

**Comment by lukaseder** [comment]
You're right, and we actually already have this functionality via the H2 `MERGE .. KEY .. VALUES` API. I've reopened #4464 to remember this...

**Comment by kbalyasnikov** [comment]
Thanks, Lukas!
