### ISSUE TITLE
Add support for java.time

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4338]
The new Java 8 API (see #3645) allows for making use of the new `java.time` API, which we should support out-of-the-box in `DefaultBinding` and `Convert`, `SQLDataType` and other jOOQ API.

The JDBC spec (http://download.oracle.com/otndocs/jcp/jdbc-4_2-mrel2-eval-spec/index.html) specifies:

- Added support to map `java.time.LocalDate` to JDBC DATE.
- Added support to map `java.time.LocalTime` to JDBC TIME
- Added support to map `java.time.LocalDateTime` to JDBC TIMESTAMP.
- Added support to map `java.time.OffsetTime` to JDBC TIME_WITH_TIMEZONE.
- Added support to map `java.time.OffsetDateTime` to JDBC TIMESTAMP_WITH_TIMEZONE.

----
There is a significant issue with this task related to the `org.jooq.impl.DSL`'s current use of generics in date/time functions. For instance, we have hard-wired `java.sql.Timestamp` into methods such as:

```java
public static Field<DayToSecond> timestampDiff(Field<Timestamp> timestamp1, Field<Timestamp> timestamp2) { ... }

public static Field<DayToSecond> timestampDiff(Field<Timestamp> timestamp1, Timestamp timestamp2) { ... }
```

These methods cannot be overloaded with their `LocalDateTime` or `OffsetDateTime` alternatives. Also, there is not a common super type that could be used, as the legacy `java.util.Date` API has not be retrofitted with a common marker interface, such as `java.time.temporal.TemporalAccessor` or `java.time.temporal.Temporal` (probably for good reasons), which means the only possible way to stay at least somewhat backwards compatible and provide the same functionality is by removing type constraints and using wildcards where generics are involved:

```java
public static Field<DayToSecond> timestampDiff(Field<?> timestamp1, Field<?> timestamp2) { ... }
```

... or by further overloading where at least one non-generic type is involved:

```java
public static Field<DayToSecond> timestampDiff(Field<Timestamp> timestamp1, Timestamp timestamp2) { ... }
public static Field<DayToSecond> timestampDiff(Field<? extends Temporal> timestamp1, LocalDateTime timestamp2) { ... }
public static Field<DayToSecond> timestampDiff(Field<? extends Temporal> timestamp1, OffsetDateTime timestamp2) { ... }
```

(If only Java supported union types...)

----
This is a prerequisite for #4429

**Comment by kag0** [comment]
@lukaseder is this feature currently in release? Could you link to some code snippets or docs on how to work with java 8 time in JOOQ?

**Comment by lukaseder** [comment]
@kag0 Yes and no.

- Yes, it's available meaning that `DefaultRecordMapper` and `DefaultBinding` can handle the types and bind them correctly
- No, it's not available in the code generator, or in the public `DSL` API because of open questions regarding how to overload existing functionality, such as `DSL.timestampDiff()`. The issues here are generic type erasure, which prevent overloading `Field<Timestamp>` and `Field<LocalDateTime>`, for instance

Because of this, there are currently no public docs

**Comment by mdomasevicius** [comment]
@lukaseder any new developments on the java 8 time issues discussed almost a year ago?

**Comment by lukaseder** [comment]
@mdomasevicius Thanks for your message. As you can see, this issue is closed and fixed, which means that jOOQ officially supports `java.time` types. However, there may be bugs. If you think you've encountered a bug, please feel free to create a new issue.

**Comment by t9t** [comment]
@lukaseder I'm upgrading to jOOQ 3.10.0 and notice that some of my code breaks, because the PostgreSQL time `timestamp with time zone` is now translated to `OffsetDateTime`. However, there is no matching `DSL.timestampDiff()` to compare `OffsetDateTime`.

Is it an oversight that these are missing, or am I overlooking some other solution I could use?

For reference, my code currently looks like this, to determine a date field is more than 7 days in the past:
```
.where(DSL.timestampDiff(DSL.currentTimestamp(), USER.LAST_SYNC).le(DayToSecond(7)))
```

`"user"."last_sync"` is a `timestamp with time zone` which was formerly translated into a `Timestamp`, and now a `OffsetDateTime` (note also that `current_timestamp()` in PostgreSQL returns a `timestamp with time zone`).

**Comment by lukaseder** [comment]
Thanks for your message, @t9t. For the record (for future visitors): The missing `timestampDiff()` for `OffsetDateTime` feature is discussed here: #6723
