### ISSUE TITLE
Document ALTER TABLE .. ADD CONSTRAINT statement in the manual

### ISSUE THREAD

**Issue by darkfrog26** [jOOQ/jOOQ#4365]
I'm new to JOOQ, so perhaps this is easy for someone that has been using it for a while, but I can't seem to figure out or find any examples of how to alter a table and add a foreign key constraint.  I see it referenced in the code, I've even found details about it in ConstraintImpl, but I can't seem to figure out how do context.alterTable().add(constraint) to handle it.  It would be great to have this mentioned in the documentation here: http://www.jooq.org/doc/3.6/manual/sql-building/ddl-statements/alter-statement/

**Comment by lukaseder** [comment]
Hmm, you're right. The documentation for that syntax seems to be missing. There's `DSL.constraint()` as an entry point to form an `org.jooq.Constraint` that can be passed to the `ALTER TABLE` statement:
http://www.jooq.org/javadoc/latest/org/jooq/impl/DSL.html#constraint-java.lang.String-

We'll document this in the manual
