### ISSUE TITLE
Occasional errors using DSL.timestampAdd() with MySQL

### ISSUE THREAD

**Issue by ShibaBandit** [jOOQ/jOOQ#4370]
I've been receiving intermittent exceptions using DSL.timestampAdd() with MySQL in Amazon RDS (MySQL 5.6.22).

My function call looks like:

```java
List<Field<?>> params = new LinkedList<>();
Long prodTtlSec = <SOME VALUE>;
params.add(DSL.val(isPermanent ? null : DSL.timestampAdd(DSL.currentTimestamp(), prodTtlSec, DatePart.SECOND)));
```

org.jooq.exception.SQLDialectNotSupportedException: Type class org.jooq.impl.DateAdd is not supported in dialect DEFAULT
    at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:757) ~[1.0-20150604.201643-39/:na]
    at org.jooq.impl.DefaultDataType.getDataType(DefaultDataType.java:704) ~[1.0-20150604.201643-39/:na]
    at org.jooq.impl.DSL.getDataType(DSL.java:13585) ~[1.0-20150604.201643-39/:na] at org.jooq.impl.DSL.val(DSL.java:11979) ~[1.0-20150604.201643-39/:na]
    ............

Relevant maven dependencies:
jooq 3.6.1
jooq-meta 3.6.1
mysql-connector-java 5.1.35

The stack trace only occurs sometimes in the same execution path. If anyone has ideas why this might occur sometimes or how to resolve it, I would really appreciate it.

**Comment by lukaseder** [comment]
See also:
https://groups.google.com/forum/#!topic/jooq-user/n_eYDbz0qLQ

**Comment by ShibaBandit** [comment]
I was working around an insert 'where not exists' API limitation that you've fixed in jooq 3.7. 
https://github.com/jOOQ/jOOQ/issues/3779

I realized that if I use DSL.timestampAdd() while accumulating list items I would get a stacktrace indicating dateAdd was not supported. Example:

```java
List<Field<?>> params = new LinkedList<>();
params.add(DSL.val(
    DSL.timestampAdd(DSL.currentTimestamp(), longValueHere, DatePart.SECOND)));

final SelectConditionStep<Record1<String>> notExistsSelect = context.select(TABLENAME.UUID).from(TABLENAME)
                        .where(TABLENAME.FK_UUID.equal(fkUuid)
                                .and(TABLENAME.valueA.equal(valueA)));

SelectConditionStep<Record> insertIntoSelect =
    context.select(params).whereNotExists(notExistsSelect);

context.insertInto(TABLENAME, fields).select(insertIntoSelect).execute();
```

However, if I remove the 'whereNotExists' and just do a regular insert:

```java

context.insertInto(TABLENAME).
                        .set(TABLENAME.COLNAME, DSL.timestampAdd(DSL.currentTimestamp(),
                                prodVisTtlSec, DatePart.SECOND))
                        .execute();
```

I do not get an error. I had assumed I was misusing the API and closed the issue. If this is not the case, I can reopen it.

**Comment by ShibaBandit** [comment]
I added my initial comment back for reference.

**Comment by lukaseder** [comment]
Thanks. As mentioned on the user group, this is probably a simple API misuse. Instead of:

```java
params.add(DSL.val(DSL.timestampAdd(DSL.currentTimestamp(), longValue, DatePart.SECOND)))
```

write

```java
params.add(DSL.timestampAdd(DSL.currentTimestamp(), longValue, DatePart.SECOND))
```

**Comment by ShibaBandit** [comment]
Thank you.

**Comment by apatrida** [comment]
If you use `DSL.currentTimestamp()` in an alter table it also drops the SqlDialect on the floor and defaults to `Default` dialect instead of whatever is configured.

```
            db.alterTable("Accounts")
                    .alterColumn("dtCreated").defaultValue(DSL.currentTimestamp())
                    .execute()
```

Is that a misuse of the API as well?  or is there another way to set the current time as a default value on a table?

**Comment by lukaseder** [comment]
@apatrida : Thanks for documenting this, and for creating a related issue. I suspect we can continue discussing the use of `currentTimestamp()` in DDL statements directly there: https://github.com/jOOQ/jOOQ/issues/5140
