### ISSUE TITLE
Make dialect-specific DSL constructors protected to allow further subtyping

### ISSUE THREAD

**Issue by lightoze** [jOOQ/jOOQ#4380]
Existing private constructors in DB-specific DSL classes make them non-extendable. It would be handy to extend them from a custom DSL, so that you don't have to distinguish e.g. PostgresDSL and CustomPostgresDSL.

**Comment by lukaseder** [comment]
Thanks for your suggestion. You're right, this is why we made the `DSL()` default constructor `protected` in the first place, to allow for dialect-specific subclasses, which "extend" the DSL namespace.

We'll get that through for you in jOOQ 3.7
