### ISSUE TITLE
jOOQ performing queries on pg_catalog?

### ISSUE THREAD

**Issue by gcobr** [jOOQ/jOOQ#4394]
I have some applications using jOOQ with PostgreSQL, and I see that they are performing too many queries on the pg_catalog system view.

Is this an expected behavior of jOOQ?
If so, is there any way to avoid this?

**Comment by lukaseder** [comment]
Hello (and sorry for the delay)

> Is this an expected behavior of jOOQ?

I guess it is right now, although there is certainly room for improvement. What particular query / queries are causing issues at your side? What is the size of your catalog (number of tables / views / procedures, etc)?

> If so, is there any way to avoid this?

There might be, by being more selective with the generator. But we'll certainly need more information to help you...

**Comment by lukaseder** [comment]
@gcobr: Is this still an issue for you? Do you perhaps have any additional info that you could share with us?

**Comment by gcobr** [comment]
I believe that the issue is actually related to the PostgreSQL Driver, according to this: http://www.postgresql.org/message-id/201111150859.pAF8xKZW012012@wwwmaster.postgresql.org

**Comment by lukaseder** [comment]
Ah, interesting. So this isn't really happening when using the code generator? Because the generator doesn't use the JDBC driver's `DatabaseMetaData` or `ResultSetMetaData`... How did you encounter this issue?

**Comment by gcobr** [comment]
A colleague told me about this ..
So far, we upgraded the JDBC driver to its latest version and the problem seems to be gone.

**Comment by lukaseder** [comment]
Alright, thanks for the feedback. I'll close this as "worksforme", then.
