### ISSUE TITLE
How to get MySQL table metadata using jooq?

### ISSUE THREAD

**Issue by ducaddepar** [jOOQ/jOOQ#4395]
(This is a question rather than an issue)

How to get MySQL table metadata using jooq? I'm interested in getting a list of all tables and the list of columns sorted by ordinal position in each table.

**Comment by ooxi** [comment]
I think a platform like [stack**overflow**](http://stackoverflow.com/questions/tagged/jooq) is better suited for this kind of questions :)

Have a look at [Viewing Metadata](https://dev.mysql.com/doc/refman/5.1/en/view-metadata.html) especially on how to query the `INFORMATION_SCHEMA` views
