### ISSUE TITLE
DSLContext.meta().getTables() return empty fields list for every table in MySQL

### ISSUE THREAD

**Issue by ducaddepar** [jOOQ/jOOQ#4399]
I tried to use DSLContext.meta().getTables() to fetch the list of table names and columns per table. It fetches all the table names correctly. However, the field list for each table is empty. I'm using mysql with jooq 3.6.2.

**Comment by lukaseder** [comment]
That doesn't sound good... Just to be sure, what JDBC driver are you using?

**Comment by lukaseder** [comment]
In fact, I can reproduce this. Thanks a lot for reporting. Will look into fixing this ASAP

**Comment by lukaseder** [comment]
... In fact, I'm sorry I was too quickly. I can only reproduce this for tables from the `information_schema`, not for other tables (which is still an issue).

Is there any further information that you could provide us with to help reproduce the issue you're having? Or were you referring to the `information_schema` tables as well?

**Comment by lukaseder** [comment]
MySQL's JDBC driver has a setting that indicates whether a "null" catalog passed to `DatabaseMetaData.getColumns()` means the "current" catalog or all catalogs. This is probably what is causing the issue in a multi-schema setup. jOOQ should work around this setting by explicitly fetching all catalogs
