### ISSUE TITLE
Docs bug: Difference GeneratorStrategy & Strategy unclear

### ISSUE THREAD

**Issue by derabbink** [jOOQ/jOOQ#4401]
Following the docs on ["Configuring your code generator with Java"](http://www.jooq.org/doc/3.6/manual/code-generation/codegen-programmatic/) and ["Using custom generator strategies to override naming schemes"](http://www.jooq.org/doc/3.6/manual/code-generation/codegen-generatorstrategy/) leaves the reader (at least me) unclear about the the difference between `org.jooq.util.GeneratorStrategy` and `org.jooq.util.jaxb.Strategy`.

The former document describes the fluent construction of a `org.jooq.util.jaxb.Configuration` object, which receives a `org.jooq.util.jaxb.Generator` object. This `Generator` can also be configured with a `org.jooq.util.jaxb.Strategy` object, but this type does not match that of the latter document (which describes a `org.jooq.util.GeneratorStrategy`.

I would like to see the docs be more clear about how the proposed extension of the `DefaultGeneratorStrategy` in the latter document can be used in a pure Java configuration, i.e. in a setup where there is no configuration XML linking the `Configuration` (or even the `Configuration`'s `Generator`) to this `GeneratorStrategy`.

I am working with `org.jooq:jooq-codegen:3.6.2`.

**Comment by lukaseder** [comment]
Thanks for reporting. I agree, these types don't seem to speak for themselves when encountered for the first time. We'll improve this as you've suggested. Ideally, all configuration elements should be documented individually and with examples in XML and via the API

**Comment by lukaseder** [comment]
While I can still see how this can be confusing, I don't really see a good solution to this particular problem:

- Solving it only for this section of the manual is not thorough. There might be other, similar cases where we should help readers qualify types
- Solving this generically is quite difficult, I don't see how, yet.

I'm closing this issue as "won't fix", hoping that at some point, a generic solution does appear.
