### ISSUE TITLE
transactionResult ignores Throwables

### ISSUE THREAD

**Issue by Nthalk** [jOOQ/jOOQ#4404]
https://github.com/jOOQ/jOOQ/blob/8c4f4dc90f4b2762636c1f042d5188253dd7f462/jOOQ/src/main/java/org/jooq/impl/DefaultDSLContext.java#L321

In my testing, I use assertions and sometimes throwables within transaction blocks, however JOOQ's `transaction` method only rolls back on `Exception`, causing one test to block others, and transactions to be left hanging.

Could the above line be changed to intercept `Throwable` to prevent this issue?

**Comment by ooxi** [comment]
I don't think we should catch `Throwable` instead of `Exception` since the general rule of thumb is to never catch `Error` instances. Imagine an `OutOfMemoryError`.

Nevertheless I agree that we should make an exception for `AssertionError` and extend the catch cause to `Exception | AssertionError` (or multiple catch statements if Java 6 is still an issue).

**Comment by lukaseder** [comment]
Interesting thoughts but I don't think that `AssertionError` should be treated differently from other `Error` types as it is used to assert things who would be rather fatal if the assertion fails - i.e. not common bugs. What reasonable use-case of an `AssertionError` do you have in mind, where an explicit rollback would be justified?

**Comment by Nthalk** [comment]
Testing. I want all my tests in transactions, and I want to roll back the
transaction every time, not just when the test completes successfully.

I suppose that I should just write a junit runner, but it seemed strange
that all throwables were not being handled.

Also, I think that this is a case where you should catch (and rethrow)
throwables, as the system might not exit and cause database deadlocks for
other dependent systems.

**Comment by lukaseder** [comment]
But wouldn't you use `@Before` and `@After` (or as you said, maybe a junit runner) to properly setup the transaction and initialise / reset the test data? That's what we're doing anyway.

I don't agree that an `Error` should be a signal for explicit transaction rollbacks. A rollback is a very resource intensive operation that can possible trigger numerous other exceptions, errors, or waits. From the client point of view, there should be no such heavy cleanup operation undertaken while propagating an Error.

Instead, the error should propagate as quickly as possible, killing the JVM process and all of its sockets, which most DBMS will be able to detect.

Now, that's not a well researched opinion of mine, but perhaps you can point me to the `Throwable` handling of other APIs, like Spring Data, Hibernate, etc.? I'm curious to see how (and why) they're doing things one or the other way.

**Comment by Nthalk** [comment]
Dear, before and after work for my purpose

**Comment by lukaseder** [comment]
@Nthalk: Sometimes, the simplest solutions work best :)
