### ISSUE TITLE
ScalaGenerator generates Java code for MySQL / PostgreSQL enum types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4427]
The generator generates Java code in a Scala class for Postgres enums :
   e.g. 

```sql
CREATE TYPE preparation_time AS ENUM ('quick', 'average', 'lengthy');
```

-> PreparationTime.scala which contains : 

```java
public enum PreparationTime implements EnumType {
```

----
See also original bug report by Suleiman Khan:
https://groups.google.com/d/msg/jooq-user/uIvhuXwLXUg/bzwX9AMSxQsJ

**Comment by Laxenade** [comment]
Hi, can you confirm that it is working? I was trying to get enum working with this change however, it does't seem to work as I got `class Array takes type parameters [error]   def values() : Array = Array(` errors in the enum types when compiling. The corresponded generated code is 
```scala
object MeshLifecycle {
  def values() : Array = Array(    <= error 
      alive
    , coma
    , dead
  )

  def valueOf(s : String) : MeshLifecycle = s match {
    case "alive" => alive
    case "coma" => coma
    case "dead" => dead
    case _ => throw new IllegalArgumentException()
  }
}
```

**Comment by lukaseder** [comment]
Thank you very much for pointing this out, @Laxenade. You're right. Our integration tests for Scala were temporarily turned off, which is why this has gone unnoticed. It is not yet finished.

**Comment by Laxenade** [comment]
Yea, was looking at the source code, the code calls `Class<E>.getEnumConstants()` in `DefaultDataType` at some point, and as far as i know the enum generated by jooq is not a java enum type.

**Comment by lukaseder** [comment]
Indeed, the task is not yet finished.

**Comment by lukaseder** [comment]
Unfortunately, the current "hack" to look up the companion object is the best way to do things with Java reflection, see: http://stackoverflow.com/a/36079502/521799

We'll leave things as they are right now, working together with users to improve the situation where needed.
