### ISSUE TITLE
Add <javaTimeTypes/> to code generator configuration to generate Java 8 java.time types instead of java.sql types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4429]
The new Java 8 API (see #3645) should support generating `java.time` types by default, rather than the insufficient `java.sql` types. This is useful when supporting `{ TIME | TIMESTAMP } WITH TIME ZONE` types.

The JDBC spec (http://download.oracle.com/otndocs/jcp/jdbc-4_2-mrel2-eval-spec/index.html) specifies:
- Added support to map `java.time.LocalDate` to JDBC DATE.
- Added support to map `java.time.LocalTime` to JDBC TIME
- Added support to map `java.time.LocalDateTime` to JDBC TIMESTAMP.
- Added support to map `java.time.OffsetTime` to JDBC TIME_WITH_TIMEZONE.
- Added support to map `java.time.OffsetDateTime` to JDBC TIMESTAMP_WITH_TIMEZONE.

**Comment by yzmyyff** [comment]
When will you release v3.7? 
I really want to change the time type.

And, could it be easily implement on v 3.6.x?

Thanks a lot for your works.

**Comment by ooxi** [comment]
You can always use Converter for custom `java.time` types

**Comment by lukaseder** [comment]
3.7 is due for the end of September

**Comment by lukaseder** [comment]
We won't be able to add support for JSR-310 in jOOQ 3.7's code generator. There are still too many open questions. Only the runtime will be capable of handling these data types.

**Comment by lightoze** [comment]
When implementing date-time handling functions for Java 8, please also keep in mind possibility to use other types such as Instant and Duration (for intervals).

**Comment by lukaseder** [comment]
Yes, indeed. `Duration` corresponds to SQL's `INTERVAL DAY TO SECOND`, whereas `YearMonth` corresponds to SQL's `INTERVAL YEAR TO MONTH`

**Comment by eiswind** [comment]
Is there any progress on this one or do I still need to use custom types?

**Comment by lukaseder** [comment]
@eiswind: Unfortunately, no progress yet. Chances are, that jOOQ 3.9 will be delayed a bit to get this in, though. It's really a priority to finally support JSR 310 in jOOQ

**Comment by lukaseder** [comment]
This is now implemented as an opt-in flag. With more end user experience, we'll eventually switch the flag's default value to `true` (https://github.com/jOOQ/jOOQ/issues/5714)

**Comment by stupidSheep** [comment]
Hi @lukaseder I just wanted to thank you for implementing this feature! I started migrating to jooq a few weeks back and was eagerly looking forward to java.time API support :-) 
Many thanks (and apologies for the off-topic comment)!

**Comment by lukaseder** [comment]
Hey, you're welcome, "@stupidSheep" :)
