### ISSUE TITLE
SQL Server vs. SQL Server Express

### ISSUE THREAD

**Issue by ooxi** [jOOQ/jOOQ#4495]
What's the difference between jOOQ support of SQL Server and SQL Server Express? I'm interested whether it's possible to use jOOQ Express with an SQL Server if I restrict myself to SQL Server Express features (just simple selecting and code generation).

*Edit*: Please do not only describe if it's technically possible but also if it's a valid usage according to the license.

**Comment by lukaseder** [comment]
Thanks alot for asking

There's currently no technical difference between the deliverables. They're all available from here:
http://www.jooq.org/download/versions

From a license perspective, the jOOQ Express Edition may be used only with a database listed in the jOOQ Express Edition column in this list:
http://www.jooq.org/legal/licensing#databases

In other words, any Open Source database, or Microsoft Access, Oracle Express Edition, SQL Server Express Edition. From a SQL perspective, there are only few SQL features that are not available in the express editions. The database feature limitation is mostly related to the number of cores that can be used, or parallel sessions that are possible.

So, I suspect that the jOOQ Express Edition doesn't apply to your use-case.

Does the above help / answer your question? What is the use-case that you're evaluating jOOQ for?

**Comment by ooxi** [comment]
Yes this does answer my question. We have a couple of systems writing to MSSQL databases which might be downgradable to SQL Server Express but I'm not sure. I think the operations team installed the full version to be sure, not because it's needed (mostly production line machines logging their state, nothing fancy)

**Comment by lukaseder** [comment]
Well, apart from jOOQ Express being cheaper, SQL Server Express is free, so that might be worth evaluating, indeed.

Glad I could help. Let me know if you have any additional questions.
