### ISSUE TITLE
Wrapping condition as field should produce parentheses

### ISSUE THREAD

**Issue by lightoze** [jOOQ/jOOQ#4506]
Please consider this use case:
```
field(account.username.concat("A").eq("AA")).eq(true)
```
The output is invalid SQL like that:
```
("public"."account"."username" || 'A') = 'AA' = true
```
Interpreted as `("public"."account"."username" || 'A') = ('AA' = true)`
The same problem happens with other operators, including "is not distinct from" inside decode() implementation, etc.

**Comment by lukaseder** [comment]
You're right, thanks for pointing this out to us
