### ISSUE TITLE
Select on an inner select which is a join, can potentially cause column conflict

### ISSUE THREAD

**Issue by RohanPrabhuNomadly** [jOOQ/jOOQ#4509]
Given a table:

```
CREATE TABLE book(
    id int,
    name character varying,
    author_id int
);

CREATE TABLE author(
    id int,
    name character varying);
```

The following runs fine:

```
Select<?> select = dsl.select().from(Tables.BOOK.join(Tables.AUTHOR).on(
    Tables.BOOK.AUTHOR_ID.eq(Tables.AUTHOR.ID)));
```

This is a problem:

```
SelectQuery<?> selectQuery = dsl.selectQuery();
selectQuery.addFrom(select);
```

The error I get is:

```
column reference "id" is ambiguous
```

And it is pretty obvious why. This is the generated SQL when I wrap it up:

```
select
    "alias_16627593"."id", "alias_16627593"."name", "alias_16627593"."author_id",
    "alias_16627593"."id", "alias_16627593"."name"
from (
    select
        "public"."book"."id", "public"."book"."name", "public"."book"."author_id",
        "public"."author"."id", "public"."author"."name"
);
```

Essentially, the table name from the fields is being completely removed, which I think is possibly causing the issue. Is there a way around this?
## Use case

Even though I do believe this is a bug, this potentially could be one of the things not worth the effort of supporting. Hence it would be remiss of me to not mention my use case. I am trying to create a generic way to namespace all my queries. A skeletal structure of my function would like:

```
public <T extends TableLike<R>, R extends Record> T namespaced(T from, String namespace) {
    Fields<?>[] fields = from.fields();
    SelectQuery<?> selectQuery = dsl.selectQuery();

    fields.forEach { field ->
        if (field.name == "namespace" && field.getType() == String.class) {
           selectQuery.addCondition(field.eq((Object)namespace));
        }
    }

    return (SelectQuery<R>)selectQuery;
}
```

Even if there are other ways to do what I am trying to do above, I still believe that if `x` is a valid `TableLike` then so should `SELECT * FROM x`. Or in other words, `x` and `SELECT * FROM x` should have similar behaviour. Kindly mention your thoughts on the same.

**Comment by lukaseder** [comment]
The best way to work around this issue is to explicitly rename all columns of the derived table. E.g.:

```java
SelectQuery<?> selectQuery = dsl.selectQuery();
selectQuery.addFrom(select.asTable("t", "col1", "col2", ...));
```

That way, you can disambiguate the individual columns. We also have a feature on the roadmap, which might help solve this problem without needing to rename each column individually: https://github.com/jOOQ/jOOQ/issues/4512

Unfortunately, this is a common problem when working with SQL in general. While top-level statements are allowed to have duplicate column names in them, derived tables are not. So your assumption is essentially not correct:

> I still believe that if x is a valid TableLike then so should SELECT * FROM x

Nonetheless, I'll leave this issue open, as a better solution to work around this issue is certainly very desireable

**Comment by RohanPrabhuNomadly** [comment]
Since I need to do this in a generalized way, I guess I am just going to try and do this (not near a computer right now):
    int field = 0;
    SelectQuery<?> selectQuery = dsl.selectQuery();
    selectQuery.addFrom(select.asTable(
        Arrays.asList(select.fields())
            .stream()
            .map("field_" + field++)
            .collect(Collectors.toList())
            .asArray());

**Comment by lukaseder** [comment]
Yes, exactly. That will almost work, you'll have to use something like `AtomicInteger` or an `int[]` though, to update outer scope from the lambda. 

Or if you also add [jOOλ](https://github.com/jOOQ/jOOL) to your stack, you can make that:

```java
SelectQuery<?> selectQuery = dsl.selectQuery();
selectQuery.addFrom(select.asTable(
    Seq.of(select.fields()).zipWithIndex().map(t -> "field_" + t.v2).toList()
));
```

**Comment by lukaseder** [comment]
I'm closing this as won't fix. This is how all SQL implementations work:

- Top level selects are allowed to contain ambiguous column names
- Derived tables may not contain ambiguous column names

There's no automatic workaround for this that wouldn't alter the query's semantics.
