### ISSUE TITLE
ScalaGenerator generates broken code when using xxxImplements

### ISSUE THREAD

**Issue by robbytx** [jOOQ/jOOQ#4526]
Using a configuration like:
```xml
<generator>
  <name>org.jooq.util.ScalaGenerator</name>
  <strategy>
    <matchers>
      <tables>
        <table>
          <expression>^.*$</expression>
          <recordImplements>test.Trait</recordImplements>
        </table>
      </tables>
    </matchers>
  </strategy>
</generator>
```
will lead to code like:
```scala
class MyTableRecord extends UpdatableRecordImpl[MyTableRecord](MyTable.MY_TABLE) with Trait, Record1<String> {
 ...
}
```

The invalid syntax is ``with Trait, Record1<String>``.
The correct syntax is ``with Trait with Record1<String>``.

Judging from the code, I believe this is a simple fix in the ``JavaGenerator`` class replacing all occurrences of ``[[before= with ][%s]]`` with ``[[before= with ][separator= with ][%s]]``.

**Comment by lukaseder** [comment]
Thanks a lot for reporting! Hmm, interesting, you're probably right with that suggested fix. We'll have a look soon.

**Comment by lukaseder** [comment]
Yep, your suggestion does it. Thanks for the heads-up!
