### ISSUE TITLE
Add manual section about DSLContext.connection()

### ISSUE THREAD

**Issue by sargue** [jOOQ/jOOQ#4528]
Some documentation about how the connection is managed inside a transaction and an example of how to obtain the current connection inside a transaction (if applicable) might be useful [in the manual](http://www.jooq.org/doc/3.6/manual/sql-execution/transaction-management/).

See this [SO question](http://stackoverflow.com/questions/32435779/how-to-get-the-underlying-connection-inside-a-transaction-using-jooq).

**Comment by lukaseder** [comment]
Excellent, thank you for the reminder!

**Comment by lukaseder** [comment]
I'm wondering if we should be adding some sort of method like `DSLContext.withConnection(Consumer<Connection>)`, which would allow to work around your original issue... The issue was how t access the JDBC `Connection` from within the transaction. This new method would solve that problem better than documentation...

**Comment by sargue** [comment]
I totally agree. Not only will solve my case but I think it does it in a more generic way. You can even use the construct on non-transactional code. And the `try` / `acquire()` / `finally` / `release()` construct is avoided with a much cleaner approch.

And it is even better if you are using (as I am) Java 8.

**Comment by lukaseder** [comment]
> You can even use the construct on non-transactional code

Yes, the "transactional" semantics is implicit, depending on whether you happen to be in a transaction or not. The semantics of the lambda would be the same as that of the try-with-resources statement. At the beginning of the lambda, the `Connection` is "`required()`", and at the end, it is "`released()`".

Now for the hardest part: How to name this method :)

**Comment by lukaseder** [comment]
I'll leave this issue open as there is definitely room for more documentation in this area. The other feature is implemented:

```java
DSL.using(configuration)
   .connection(connection -> {
      try (PreparedStatement stmt = connection.prepareStatement("insert ...")) {
          stmt.executeUpdate();
      }
   });
```

**Comment by lukaseder** [comment]
I finally documented #4552 also in the manual now.
