### ISSUE TITLE
ExceptionTranslator in spring examples shouldn't use dialect.name() for SQLErrorCodeSQLExceptionTranslator

### ISSUE THREAD

**Issue by aner-perez** [jOOQ/jOOQ#4557]
`dialect.name()` returns "POSTGRES_9_4" in my test which is the name of the dialect enum value.

`SQLErrorCodeSQLExceptionTranslator` expects the values returned by `java.sql.DatabaseMetaData.getDatabaseProductName()` to map database names.  In my case this should be "PostgreSQL".  It seems like there is a `ThirdParty` inner class in `org.jooq.SQLDialect` that implements `public final String springDbName()` which could be used to solve this issue but I can't figure out how to access it.

Regardless, with the current code, `SQLErrorCodeSQLExceptionTranslator` will always end up falling back to the `SQLStateSQLExceptionTranslator` implementation because it cannot find the dialect by name.

**Comment by lukaseder** [comment]
>  but I can't figure out how to access it.

```java
SQLDialect.POSTGRES_9_4.thirdParty().springDbName();
```

Does that answer your question / solve those problems?

**Comment by aner-perez** [comment]
For some reason the jooq-3.6.2.jar I have (from a maven dependency) does not have a `SQLDialect.thirdParty()` instance method.  This was the confusing part since I could see it in the code on GitHub.  Is this a new method that didn't exist in 3.6.2?

Ideally, line 77 of org.jooq.example.spring.exception.ExceptionTranslator would be changed from:
```Java
                    ? new SQLErrorCodeSQLExceptionTranslator(dialect.name())
```
to
```Java
                    ? new SQLErrorCodeSQLExceptionTranslator(dialect.thirdParty().springDbName())
```

**Comment by lukaseder** [comment]
Oh, I'm sorry, this has been added only in jOOQ 3.7 via https://github.com/jOOQ/jOOQ/issues/4253. My bad.

Until we release 3.7, you'll either have to build 3.7 yourself, or re-implement that mapping logic.

**Comment by aner-perez** [comment]
I still think

https://github.com/jOOQ/jOOQ/blob/master/jOOQ-examples/jOOQ-spring-example/src/main/java/org/jooq/example/spring/exception/ExceptionTranslator.java

should be updated to use `dialect.thirdParty().springDbName()` instead of `dialect.name()` as it is currently doing.

**Comment by lukaseder** [comment]
I'm very sorry - and thanks for insisting. I was slow today. Yes, of course, the example `ExceptionTranslator` should be adapted now!
