### ISSUE TITLE
Add BatchBindMoreStep in order to make at least one BatchBindStep.bind() call mandatory

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4558]
Currently, it's possible to write:

``` java
DSL.using(configuration)
   .batch(query)
   .execute();
```

Prior to #4554, this silently ignored the query as there were no bind variables set to a `BatchSingle` configuration. The fix in #4554 will just execute the statement as a `BatchMultiple`, although that probably wasn't the intent of the user.

The `BatchBindStep` returned from `batch(Query)` should no longer extend `Batch`, and thus no longer give access to the `execute()` method before at least one bind value set is provided.

---

See also: #4554

**Comment by steveash** [comment]
I vote _against_ this feature.  See my comment on [#4554]

**Comment by lukaseder** [comment]
Thank you for your feedback, @steveash. This will be a strategic decision for jOOQ 4.0, which hasn't been made yet. I can certainly see your point.

Essentially, there is a concept of a DSL API (which is used for "static SQL", in case of which this issue here makes sense), and a model API (which is used for "dynamic SQL", in case of which your vote against this issue makes sense).

It is not yet fully clear whether a much clearer distinction between DSL API and model API is really a path worth taking in jOOQ 4.0

**Comment by steveash** [comment]
Right that makes sense, and i can certainly get behind something like: change batch(Query):BatchBindStep to batchBind(Query):MoreBatchBindStep with the addition of a new api to make binding multiple statements simpler. Something like the options we have been talking about in this discussion https://groups.google.com/forum/m/#!topic/jooq-user/6P7vG7--tG0

**Comment by lukaseder** [comment]
This hasn't received any traction at all, and I haven't felt any user would have liked this change. Rejecting.
