### ISSUE TITLE
Add support for the PostgreSQL MODE() ordered-set aggregate function

### ISSUE THREAD

**Issue by dmitrygusev** [jOOQ/jOOQ#4568]
> Postgres 9.4 has built-in aggregate function mode()
https://wiki.postgresql.org/wiki/Aggregate_Mode

We're currently using it by creating a class like this:

```
package org.jooq.impl;

import org.jooq.OrderedAggregateFunction;

public class CustomFunctions
{
    public static OrderedAggregateFunction<Object> mode()
    {
        return new Function<Object>("mode", SQLDataType.OTHER);
    }
}
```

and then `create.select(CustomFunctions.mode().withinGroupOrderBy(...))`.

**Comment by lukaseder** [comment]
Absolutely! Thanks for your suggestion

**Comment by lukaseder** [comment]
Hmm, I wonder though if there isn't a way to determine the type more formally. I've often wondered why PostgreSQL chose not to allow any arguments in `mode(column ref)`...

**Comment by dmitrygusev** [comment]
Hey @lukaseder 
Any reasons why this is not on the 3.7.x branches yet?

**Comment by lukaseder** [comment]
Thank you very much for checking back in on this. We're not backporting features to older minor releases. This feature will be supported in jOOQ 3.8, due this month.
