### ISSUE TITLE
Unexpected column result (null) when using recursive CTEs on H2

### ISSUE THREAD

**Issue by michael-simons** [jOOQ/jOOQ#4574]
Environment: jOOQ 3.6.3, h2 1.4.188, Spring Boot 1.2.6

Given the following table structure:

```
create table menu_entries (
    id integer not null auto_increment,
    label varchar(2048) not null,    
    href  varchar(2048),
    lfdnr integer not null,
    parent_id integer null,
    PRIMARY KEY (id),   
    FOREIGN KEY (parent_id) REFERENCES menu_entries(id)
);
```

Containing the following data:

```
INSERT INTO menu_entries values (1, 'News', null, 1, null);
INSERT INTO menu_entries values (2, 'Heise', 'http://heise.de', 1, 1);
INSERT INTO menu_entries values (3, 'Heise Sec', 'http://www.heise.de/security/', 1, 2);
INSERT INTO menu_entries values (4, 'Golem', 'http://golem.de', 2, 1);
INSERT INTO menu_entries values (5, 'SQL', null, 2, null);
INSERT INTO menu_entries values (6, 'Use the index, Luke', 'http://use-the-index-luke.com/de', 1, 5);
```

I can use an hierarchical query in H2 shell, console or i.e. NetBeans services:

```sql
WITH src(id, parent_id, label, href, path) AS (
  (
    SELECT 
      public.menu_entries.id, 
      public.menu_entries.parent_id, 
      public.menu_entries.label, 
      public.menu_entries.href, 
      CAST(public.menu_entries.lfdnr AS VARCHAR) path
    FROM public.menu_entries
    WHERE public.menu_entries.parent_id IS NULL
  )
  UNION ALL (
    SELECT 
      public.menu_entries.id, 
      public.menu_entries.parent_id, 
      public.menu_entries.label, 
      public.menu_entries.href, 
      (src.path || '.' || CAST(public.menu_entries.lfdnr AS VARCHAR)) path
    FROM public.menu_entries
      JOIN src
      ON src.id = public.menu_entries.parent_id
  )
)
SELECT *
FROM src
ORDER BY src.path ASC
```

This query uses a CTE that starts with selecting all entries without a parent, using their running number as path. 

The CTE is recursive, joins itself with the parent_id. The new path is calculated by concatenating the previous path with a ".". 

The path is used to correctly order the result set.

Running the query inside H2 results in:

ID | PARENT_ID | LABEL                | HREF                             | PATH
---|-----------|----------------------|----------------------------------|------
1  |           | News	              |                                  | 1
2  | 1         | Heise	              | http://heise.de	                 | 1.1
3  | 2         | Heise Sec	      | http://www.heise.de/security/	 | 1.1.1
4  | 1         | Golem	              | http://golem.de	                 | 1.2
5  |           | SQL	              |                                  | 2
6  | 5         | Use the index, Luke  | http://use-the-index-luke.com/de | 2.1

The above query is actually the correct printed version that jOOQ generates given the following statement:

```java
	final Field<String> path = field(name("src", "path"), String.class);
	final Field<String> lfdnr = cast(MENU_ENTRIES.LFDNR, String.class);
	this.create
		.with("src", "id", "parent_id", "label", "href", "path")
		.as(
			select(
				MENU_ENTRIES.ID,
				MENU_ENTRIES.PARENT_ID,				
				MENU_ENTRIES.LABEL,
				MENU_ENTRIES.HREF,
				lfdnr.as("path")
			)
			.from(MENU_ENTRIES)	
			.where(MENU_ENTRIES.PARENT_ID.isNull())
			.unionAll(
			    select(
				MENU_ENTRIES.ID,
				MENU_ENTRIES.PARENT_ID,				
				MENU_ENTRIES.LABEL,
				MENU_ENTRIES.HREF,
				path.concat(val("."), lfdnr).as("path")
			    )
			    .from(MENU_ENTRIES)	
			    .join("src").on(field(name("src", "id")).eq(MENU_ENTRIES.PARENT_ID))
			)
		)
		.select()
		.from(table(name("src")))
		.orderBy(path.asc())
		.fetchInto(r -> {
		    System.out.println(r);
		});
```

The output is as follows:

```
+----+---------+-----+---------------+------+
|ID  |PARENT_ID|LABEL|HREF           |PATH  |
+----+---------+-----+---------------+------+
|2   |1        |Heise|http://heise.de|{null}|
+----+---------+-----+---------------+------+
+----+---------+-----+---------------+------+
|ID  |PARENT_ID|LABEL|HREF           |PATH  |
+----+---------+-----+---------------+------+
|4   |1        |Golem|http://golem.de|{null}|
+----+---------+-----+---------------+------+
+----+---------+-------------------+--------------------------------+------+
|ID  |PARENT_ID|LABEL              |HREF                            |PATH  |
+----+---------+-------------------+--------------------------------+------+
|6   |5        |Use the index, Luke|http://use-the-index-luke.com/de|{null}|
+----+---------+-------------------+--------------------------------+------+
+----+---------+---------+-----------------------------+------+
|ID  |PARENT_ID|LABEL    |HREF                         |PATH  |
+----+---------+---------+-----------------------------+------+
|3   |2        |Heise Sec|http://www.heise.de/security/|{null}|
+----+---------+---------+-----------------------------+------+
+----+---------+-----+------+----+
|ID  |PARENT_ID|LABEL|HREF  |PATH|
+----+---------+-----+------+----+
|1   |{null}   |News |{null}|1   |
+----+---------+-----+------+----+
+----+---------+-----+------+----+
|ID  |PARENT_ID|LABEL|HREF  |PATH|
+----+---------+-----+------+----+
|5   |{null}   |SQL  |{null}|2   |
+----+---------+-----+------+----+
```

I'm using the following configuration for rendering:

```java
final DefaultConfiguration hlp = new DefaultConfiguration();
	return hlp
		.derive(hlp.settings()
			.withRenderNameStyle(RenderNameStyle.LOWER)
			.withRenderKeywordStyle(RenderKeywordStyle.UPPER)
			.withRenderFormatted(true)
		)
		.derive(connectionProvider)
		.derive(transactionProvider)
		.derive(executeListenerProvider)			
		.derive(SQLDialect.H2);
```

The result is identical if i use the quoted rendering and change the statement above accordingly.

If the problem is on my side, i owe you a drink.

**Comment by lukaseder** [comment]
I remember this bug that I've reported a long time ago on the H2 mailing list:
https://groups.google.com/d/msg/h2-database/OJfqNF_Iqyo/brxu-Lu3c78J

Perhaps you can work around it by replacing `val(".")` by `inline(".")`. Alternatively, use `StatementType.STATIC_STATEMENT` in your `Settings` to inline all bind variables.

Note that we currently don't run integration tests with CTE against H2, as they're not yet formally supported by H2 (note the "disclaimer" about them being "experimental"):
http://www.h2database.com/html/advanced.html#recursive_queries

**Comment by michael-simons** [comment]
Hello Lukas,

thanks for looking at this and sorry for the report. Inlining the bind variable works as expected. I wasn't aware of that bug and as either wrote the query myself or copy & pasted the generated one couldn't blame H2.

And yes, an exception thrown by H2 would be way better than returning wrong results.

**Comment by lukaseder** [comment]
> And yes, an exception thrown by H2 would be way better than returning wrong results.

That's true. But remember that this is an experimental feature. Given the fact that there has been no action on this bug since my report (which was a long time ago), I suspect that CTE aren't a priority for Thomas Müller right now... I'd stay clear of them in H2

**Comment by michael-simons** [comment]
It's just for a demo… But then, the same applies as with experimental features: Stuff will be used / copy & pasted.

**Comment by lukaseder** [comment]
Exactly :) You're going to regret having used this feature ;)
