### ISSUE TITLE
JavaWriter uses regex syntax unsupported in Java <1.8

### ISSUE THREAD

**Issue by dbichko** [jOOQ/jOOQ#4576]
JavaWriter.java in 3.6.3, line 121:

```java
Matcher m = Pattern.compile("(?s:^.*?\\Rpackage\\s+(.*?);?\\R.*?$)").matcher(string);
```
**\R** is new in 1.8, which I don't believe is explicitly required for jOOQ.

**Comment by lukaseder** [comment]
Thank you very much for reporting this! This is a regression introduced with #4229 (#4230).

The linebreak matcher `\R` corresponds to "Any Unicode linebreak sequence, which is equivalent to `\u000D\u000A|[\u000A\u000B\u000C\u000D\u0085\u2028\u2029]`"

It was indeed introduced in Java 8 only, and must thus not be used in jOOQ for backwards compatibility.

**Comment by lukaseder** [comment]
This will be merged to 3.6.4 as #4583

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.7. We'll hopefully be able to publish a fix by Tuesday this week in 3.6.4.

**Comment by lukaseder** [comment]
This is now fixed and published also in 3.6.4

**Comment by dbichko** [comment]
Thanks for the really quick fix!

**Comment by lukaseder** [comment]
You're welcome. This was a real show-stopper...
