### ISSUE TITLE
Ensure that jOOQ internally uses regular expressions that are Java 6 compatible

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4582]
While a lot of differences between Java 6 and Java 8 can be covered by compilation alone, there are some more subtle differences (and potential bugs) that can be introduced via using external domain specific languages such as regular expressions.

For instance, the useful `\R` escape sequence was introduced in Java 8, but must not be used by jOOQ in order to stay Java 6 compatible (at runtime!)

We should, at build-time, look for all `Pattern.compile()`, `String.split()`, `String.replaceAll()` and similar calls that take regular expressions, and test the expression with the JDK 6.

----
See also: #4576

**Comment by ooxi** [comment]
We experienced the same problem once and were tempted to use [Ragel](http://www.colm.net/open-source/ragel/) as a JDK independent regular expression compiler. We ended up not doing so (waiting for the next potential bug was more cost efficient).

What is your opinion to using an external regular expression engine?

**Comment by lukaseder** [comment]
Good point. But then again, you'll have to remember using Ragel every time you have to remember using non-Java 8 regex syntax. The mental effort of getting it right 1-2 years down the line is the same...

In this particular case, we'll simply proceed with adding source code generation integration tests also to the JDK 6 build (we currently have only runtime tests)
