### ISSUE TITLE
The JPA Column annotation should not be mandatory

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4586]
Currently, jOOQ's `DefaultRecordMapper` either applies mapping by convention _OR_ via JPA `@Column` annotations. But in JPA, the `@Column` annotation is not mandatory on entities. If absent, default behaviour applies. jOOQ should also implement this behaviour.

---

See also:
- http://www.jooq.org/doc/latest/manual/sql-execution/fetching/pojos/#comment-2277831834
- #4263
- https://stackoverflow.com/questions/59514118/map-table-record-into-jpa-entity

**Comment by kag0** [comment]
Related to this, entity fields which are marked with `@Column` but do not have the `name` defined on the annotation are ignored. Not sure if this is intended behavior or not.

Current code (`Tools.getAnnotatedMembers`) has
```java
if (namesMatch(name, column.name())) { // if the column annotation name field matches the reflected field name
    result.add(accessible(member));
}
```

**Comment by lukaseder** [comment]
Thanks for the feedback, @kag0. This is not the intended behaviour. Even if jOOQ doesn't really implement JPA, it should adhere to the JPA spec where JPA annotations are interpreted.

**Comment by knutwannheden** [comment]
Further, the `DefaultRecordMapper` should probably skip any members annotated with JPA's `@Transient` annotation.

**Comment by lukaseder** [comment]
> Further, the `DefaultRecordMapper` should probably skip any members annotated with JPA's `@Transient` annotation.

Can you please create a separate issue?

**Comment by knutwannheden** [comment]
> Can you please create a separate issue?

Done.

**Comment by lukaseder** [comment]
The `DefaultRecordMapper` support for JPA annotations may have been added prematurely a very long time ago. It's not the most idiomatic approach to mapping things in jOOQ, especially since jOOQ 3.15's ad-hoc converter APIs, which are all type safe.

We won't add more complexity to the reflective mappings anymore, see also: https://github.com/jOOQ/jOOQ/issues/4263
