### ISSUE TITLE
Add DSLContext.query(SQL) etc

### ISSUE THREAD

**Issue by kxbmap** [jOOQ/jOOQ#4594]
I recognize that there is no way to execute `org.jooq.SQL` instance directly.
`DSLContext.query(SQL)` is usefull for the following case.

```java
SQL sql = createSomeSQL();
DSL.using(configuration).query(sql).execute();
```

And Scala's string interpolation:
```scala
val sql = sql"""
  insert into foo values (${id}, ${value});
"""
DSL.using(configuration).query(sql).execute()
```

Maybe other `xxx(String sql, Object... bindings)` methods can also add `xxx(SQL sql)` version.

**Comment by lukaseder** [comment]
Thanks for your feature request. You're completely right. Internally, all `xxx(String, Object...)` calls wrap arguments via `DSL.sql()` anyway, but we so far haven't exposed the internal APIs that are necessary to use the `org.jooq.SQL` type directly.

Will do for jOOQ 3.7

**Comment by lukaseder** [comment]
Curious about the string interpolation example:

```scala
val sql = sql"""
  insert into foo values (${id}, ${value});
"""
```

What does `sql` do in your case? Embed `QueryPart` objects into a SQL string template?

**Comment by kxbmap** [comment]
My early implementation is:
https://github.com/kxbmap/jooqs/blob/master/core/src/main/scala/com/github/kxbmap/jooqs/syntax/package.scala#L78-L87
https://github.com/kxbmap/jooqs/blob/master/core/src/test/scala/com/github/kxbmap/jooqs/syntax/SQLInterpolationSpec.scala

And thanks for quick response.

**Comment by lukaseder** [comment]
Very interesting, thanks for sharing! I suspect that this is definitely something we could add to jOOQ-scala!
