### ISSUE TITLE
forcedType match fails for exact table and column

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#4595]
I have a table `app` that has a column `name` on which I want to force the type using a converter. This should only apply to this exact column.

I have tried various expressions with no luck: `.*\.app\.name` and `app\.name`

```
<forcedType>
     <name>AppNameType</name>
     <expression>.*\.app\.name</expression>
     <types>text</types>
</forcedType>
```

What am I doing wrong? I couldn't find an example of this type of match in the manual. Sorry if I missed something obvious.

I am using jOOQ 3.6.4

**Comment by lukaseder** [comment]
It doesn't look like you're doing anything wrong. Here are some things to check:

- Is that a regression? Did this work in previous versions?
- Did you get case sensitivity right?
- Is the column really of type `text`, not of type `varchar` or `character varying`?

**Comment by axelfontaine** [comment]
Regression: no idea, first time I need this

Case sensitivity: should be OK as the DB is PostgreSQL and table & column
names are unquoted

Column type: all my string columns are defined as text and my other
forcedType declarations work fine with it

**Comment by lukaseder** [comment]
> my other forcedType declarations work fine with it

What's the difference between this one and the others?

**Comment by axelfontaine** [comment]
They only match exact column names, not including the table name. Ex.:
.*\.abc

**Comment by lukaseder** [comment]
That's very curious. What's the DDL of the `app` table?

**Comment by axelfontaine** [comment]
For reference here are some more, all working fine:

```
<forcedType>
     <name>OsType</name>
     <expression>.*\.os</expression>
     <types>text</types>
</forcedType>
<forcedType>
    <name>Plan</name>
    <expression>.*plan.*</expression>
    <types>text</types>
</forcedType>
<forcedType>
    <name>VersionType</name>
    <expression>.*version(_number)?</expression>
    <types>text</types>
</forcedType>
```

**Comment by axelfontaine** [comment]
Here is the relevant DDL:

```
CREATE TABLE app (
  id UUID NOT NULL CONSTRAINT app_pk PRIMARY KEY DEFAULT uuid_generate_v4(),
  account_id UUID NOT NULL REFERENCES account,
  name TEXT NOT NULL
);
```

**Comment by axelfontaine** [comment]
Brown paper bag moment: I had a mismatch between forcedType name and customType name.

Improvement suggestion: fail build if forcedType name doesn't exist in list of types

**Comment by lukaseder** [comment]
I was just going to ask for the customType name :)

Hmm, you're right. I thought there was a warning mechanism in place when there's a `forcedType` match, but there doesn't exist any `customType` definition, or `SQLDataType` by that name.

**Comment by axelfontaine** [comment]
Our comments crossed. See my updated suggestion.

**Comment by lukaseder** [comment]
Huh, I haven't thought about that yet. So, you mean like:

```xml
<customType>
    <converter>...</converter>
    <forcedTypes>
        <forcedType>
            <expression>...</expression>
            <types>...</types>
        </forcedType>
        <forcedType>
            <expression>...</expression>
            <types>...</types>
        </forcedType>
    </forcedTypes>
</customType>
```

**Comment by axelfontaine** [comment]
Yes! No duplication (or even need for names)!

**Comment by lukaseder** [comment]
It took long years for this obvious-looking feature request to surface :)

**Comment by lukaseder** [comment]
(I suspect this is only historic. `<forcedType/>` was there before `<customType/>`...)
