### ISSUE TITLE
Log warning when <forcedType/> doesn't have any matching SQLDataType or <customType/>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4597]
Users might have typos in their `<customType/>` definitions and then, `<forcedType/>` is silently ignored.

We should emit warnings in these cases, to help users debug these typos.

----
See also:
https://github.com/jOOQ/jOOQ/issues/4595

**Comment by axelfontaine** [comment]
I would vote for (optionally) breaking the build. Fail fast FTW!

**Comment by lukaseder** [comment]
You're right

**Comment by lukaseder** [comment]
Hmm, it's hard to factor out the existing logic in order to make it available to the `GenerationTool`. I suspect a warning will do in this case. The advantage is: We'll get tons of warnings, which may or may not be related, so everything can be fixed in one go.
