### ISSUE TITLE
Allow for nesting <forcedType/> in appropriate <customType/> to allow for more concise code generation configuration

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4598]
The following two would be equivalent configurations:

### New

```xml
<forcedType>
    <userType>...</userType>
    <converter>...</converter>
    <expression>...</expression>
    <types>...</types>
</forcedType>
```

### Old

```xml
<customType>
    <name>someNotReallyUsefulName</name>
    <converter>...</converter>
</customType>

...

<forcedType>
    <name>someNotReallyUsefulName</name>
    <expression>...</expression>
    <types>...</types>
</forcedType>
<forcedType>
    <name>someNotReallyUsefulName</name>
    <expression>...</expression>
    <types>...</types>
</forcedType>
```

----
See also:
https://github.com/jOOQ/jOOQ/issues/4595#issuecomment-145264312

**Comment by gregopet** [comment]
These properties don't seem to be available in the `org.jooq.util.jaxb.Configuration` class yet..

**Comment by lukaseder** [comment]
The `<forcedType/>` element is a child of `/configuration/generator/database`. The position of this element hasn't changed with this feature here, there's just a couple of additional flags that you can set directly on it. See also:
http://www.jooq.org/doc/latest/manual/code-generation/custom-data-types

(the 3.8 manual hasn't been updated with this feature yet, this is work in progress)
