### ISSUE TITLE
Improve generics

### ISSUE THREAD

**Issue by rgoldberg** [jOOQ/jOOQ#4601]
Generics should be improved.

e.g., in `org.jooq.UpdateSetStep<R extends Record>`:

    <T> UpdateSetMoreStep<R> set(Field<T> field, T value);

should be changed to:

    <T> UpdateSetMoreStep<R> set(Field<? super T> field, T value);

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. What would be the value of this particular change?

**Comment by rgoldberg** [comment]
Yeah, now that I think about it, it shouldn't make a difference, since T can just be reassigned to be whatever the super is.

I had a generics wildcard capture issue calling that method with a bounded `Field<? extends ...>` argument, and hoped that adding `? super ` would fix it, but you've pointed out that it won't.

**Comment by lukaseder** [comment]
OK, thanks for the feedback. Yes, I think it might be dangerous to play around with variance on these methods. Perhaps, there would be some use-cases that could benefit from the change, but others might not, or it might even be wrong in some situations.
