### ISSUE TITLE
Compilation error in generated code when column is of type "TIMESTAMP WITH TIME ZONE" in Oracle

### ISSUE THREAD

**Issue by michael-simons** [jOOQ/jOOQ#4624]
Oracle 10g, 10.2.0.3.0, Oracle JDBC Driver 11.2.0.4, Java 8

I've got this table

```
CREATE TABLE KA_LASTWERTE
 (ID NUMBER(16,0) NOT NULL
 ,KA_ANFRAGEN_NEUKUNDEN_ID NUMBER(16,0) NOT NULL
 ,ZEITSTEMPEL TIMESTAMP WITH TIME ZONE
 ,WERT NUMBER
 )
/
```

Ends up as:
```
desc ka_lastwerte
 Name					   Null?    Typ
 ----------------------------------------- -------- ----------------------------
 ID					   NOT NULL NUMBER(16)
 KA_ANFRAGEN_NEUKUNDEN_ID		   NOT NULL NUMBER(16)
 ZEITSTEMPEL					    TIMESTAMP(6) WITH TIME ZONE
 WERT						    NUMBER

```

Using jOOQ 3.6.4, this is represented in the record as
```
public final TableField<KaLastwerteRecord, Object> ZEITSTEMPEL = createField("ZEITSTEMPEL", org.jooq.impl.DefaultDataType.getDefaultDataType("TIMESTAMP(6) WITH TIME ZONE"), this, "");
```

Whereas in jOOQ 3.7.0 i end up with

```
public final TableField<KaLastwerteRecord, OffsetDateTime> ZEITSTEMPEL = createField("ZEITSTEMPEL", org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");
```

But there's no such attribute in org.jooq.impl.SQLDataType and the class fails to compile.

**Comment by lukaseder** [comment]
Thanks for reporting. Interesting - I was sure we had turned off this feature for 3.7 as it was not yet fully ready. Will look into it asap. In the meantime, you can probably work around this problem using type-rewriting:

```xml
<forcedType>
    <name>TIMESTAMP</name>
    <expression>ZEITSTEMPEL</expression>
</forcedType>
```

**Comment by michael-simons** [comment]
You're welcome. 

At the moment using that column type is somewhat experimental for us as well… Although it would be nice to have, it seems not very well supported (in Oracle), but i wanted to let know nevertheless. 

Thanks for the workaround.

**Comment by lukaseder** [comment]
> Although it would be nice to have, it seems not very well supported (in Oracle)

Interesting, what's the problem that you've experienced?

One thing that's interesting is the fact that Oracle chose to actually store the time zone (not the offset!) with the value, unlike other databases that just use this data type as an alias for a UTC "instant" (modelled in Java with `java.time.Instant`)...

**Comment by lukaseder** [comment]
Thanks again for submitting this. I can reproduce the issue. Will fix this ASAP

**Comment by michael-simons** [comment]
That is exactly what i experienced, here's the excerpt from our code (reverting back to PreparedStatement, was using JPA/Hibernate back then):

```
/**
 * Dieses Formatter entspricht dem Oracle Format 'YYYY-MM-DD HH24:MI:SS TZR TZD'.
 */
public static final DateTimeFormatter TIMESTAMP_TZ_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss VV z", Locale.ENGLISH);

// …

// Wie einige Dinge im Oracle JDBC Treiber, funktioniert dieses schöne Statement nur in der Theorie:
// ps.setTimestamp(2, Timestamp.from(lastwert.getZeitstempel().toInstant()), GregorianCalendar.from(lastwert.getZeitstempel()));
// In der Theorie sollte die Zeitzone des Kalendarparameters berücksichtigt werden. Dies wird sie auch, allerdings nur in Teilen,
// der Zeitzonenoffset (TZD) wird ignoriert :/
// Deswegen nutze ich statt dessen den Umweg über einen String und die to_timestamp_tz Methode.
//
// Das Mapping, TIMESTAMP WITH TIME ZONE zu Calendar annotiert mit @TEMPORAL(TIMESTAMP) funktioniert
// wie erwartet.
ps.setString(2, lastwert.getZeitstempel().format(TIMESTAMP_TZ_FORMATTER));
ps.setDouble(3, lastwert.getWert());
```

**Comment by lukaseder** [comment]
Hmm, aren't you supposed to use the `oracle.sql.TIMESTAMPTZ` type to bind a variable?

**Comment by michael-simons** [comment]
See, the issue is good for both of us :) Thanks for the hint!

**Comment by lukaseder** [comment]
The fix is to alias the `SQLDataType.OFFSETDATETIME` with `SQLDataType.TIMESTAMPWITHTIMEZONE`. The alias is needed for consistency reasons:

- SQL names are used for types in the `java.sql.*` package, like `Time`, `Timestamp`, `Date`. The time-zoned types don't have an equivalent `java.sql.*` type, but they still need a representation with a SQL name.
- JSR-310 names are used for types in the `java.time.*` package, like `OffsetTime`, etc. All SQL types have a corresponding type in this package.
