### ISSUE TITLE
[jooq-codegen-maven] a suggestion for command line arguments for user and password

### ISSUE THREAD

**Issue by jinahya** [jOOQ/jOOQ#4631]
Sometimes, specifying `user` and `password` in `pom.xml` can be regarded as a bad practice.

I tried this.

````
public class Plugin extends AbstractMojo {

    @Parameter(property = "jdbc.user") private String user;
    @Parameter(property = "jdbc.password") private String password;

    @Override
    public void execute() throws MojoExecutionException {
        // ...
            if (user != null) {
                jdbc.withUser(user);
            }
            if (password != null) {
                jdbc.withPassword(password);
            }
            configuration.setJdbc(jdbc);
        // ...
}
````
Now I can invoke maven with parameters.
````
$ mvn -Djdbc.user=some -Djdbc.password=some ...
````

**Comment by lukaseder** [comment]
Thanks for your suggestion.

I tend to recommend using external property files and loading them with the `properties-maven-plugin`. This is explained here, for example:
http://www.petrikainulainen.net/programming/tips-and-tricks/creating-profile-specific-configuration-files-with-maven

Passwords on the command line aren't really best practice either, as you will have them in your command line history - possibly surviving your session. Nonetheless, I can see the value of having additional means of providing parts of the configuration. We'll think about this.

**Comment by lukaseder** [comment]
I still don't have a good feeling with this. Clearly, we shouldn't use simple, ambiguous parameters like `jdbc.user`. The user might pass those to some other plugin / process, but not to the jOOQ plugin. They will apply "by accident".

Once we use longer names, we risk making this new feature too tedious to use, compared to just simply specifying:

```xml
<jdbc>
  <user>${jdbc.user}</user>
</jdbc>
```

The above is just a bit more to type. I think that's not asking too much from users.

I'm thus rejecting this feature request.

**Comment by lukaseder** [comment]
We'll implement this through #7011 in jOOQ 3.11
