### ISSUE TITLE
error prone update where clause when using by mistake field() instead of value() 

### ISSUE THREAD

**Issue by jonnybbb** [jOOQ/jOOQ#4633]
To figure out if a record with some same values already exits in the database and executing therefor an update instead of an insert you might want to execute a select Query first.

```sql
   Record1<String> subId = jooq.select(SUB.SUB_KEY).from(SUB)
                .where(SUB.SUB_NAME.eq(record.getSubName())).fetchOne();
```

Using field1() instead of value1() results in updating all records, because `SUB.SUB_KEY.eq(subId.field1())` is always true

```Java
if (subId != null) {
jooq.update(SUB).set(SUB.SUB_DATA, record.getSubData())
 .where(SUB.SUB_KEY.eq(subId.field1())).execute();
        }
```
Not sure whether jooq could figure out those kind statements which are very likely an error

**Comment by ooxi** [comment]
You most certainly would not since you've introduced a [race condition](https://de.wikipedia.org/wiki/Time-of-Check-to-Time-of-Use-Problem)

**Comment by lukaseder** [comment]
> Not sure whether jooq could figure out those kind statements which are very likely an error

In general, the likelihood of an error in such a situation is a very tough thing to debate. Some people like to always have a dummy predicate in *all* queries, just to enforce the `WHERE` clause / keyword. That way, they can then append / comment out predicates always with `AND`, which is much simpler from a syntactic perspective:

```sql
SELECT *
FROM t
WHERE 1 = 1
-- AND a = b
-- AND c = d
AND e = f
```

Conversely, a forgotten `WHERE` clause in a `DELETE` statement is likely an error, but perhaps it is not? Should we really tell the user? I personally prefer not to.

If, however, you know that this is not a sensible use-case in your application, you could implement a `VisitListener` that checks for the presence of such predicates (or the absence of `WHERE` clauses).

**Comment by lukaseder** [comment]
(Regardless of the wontfix label, I'm very open to discussion in case there is potential for improvement of the API! Perhaps there's a low hanging fruit?)

**Comment by jonnybbb** [comment]
The VisitListener is what I am looking for. Thanks!

I do not see any low hanging fruit either.

**Comment by lukaseder** [comment]
Ok, thanks for the feedback. In fact, I now remember that I had thought about providing an out-of-the-box "lint visit listener", which could be hooked into development / CI to generate reports about potentially bad queries. This listener could also check for execution plans, index usage, etc. Would be interesting to assemble some ideas around that...
