### ISSUE TITLE
Updating from version 3.6.2 to 3.7.0 doesn't work

### ISSUE THREAD

**Issue by facundofarias** [jOOQ/jOOQ#4679]
Not sure if it is only me, but I am getting this error message:
```
java.lang.UnsupportedClassVersionError: org/jooq/ConnectionProvider : Unsupported major.minor version 52.0
```
Any ideas?
Thanks a lot!

**Comment by abhiranjan** [comment]
Is your Java compile time & run time are matching? 
See if these helps:-
http://stackoverflow.com/questions/24790834/cant-fix-unsupported-major-minor-version-52-0-even-after-fixing-compatibility
http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

**Comment by facundofarias** [comment]
Yes, I've only changed the pom.xml file, by changing the JOOQ version.

More info:
$ java -version
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

$ system_profiler SPSoftwareDataType
      System Version: OS X 10.9.5 (13F1066)
      Kernel Version: Darwin 13.4.0

**Comment by lukaseder** [comment]
Hi Facundo,

Thank you very much for your enquiry. This year, Oracle has stopped supporting and maintaining the free versions of the Oracle JDK 7 and less. We took the opportunity to follow suit in favour of native Java 8 support in jOOQ 3.7 (#3645), which makes jOOQ even better for our users, who wish to integrate typesafe SQL with lambdas, streams, optional, JSR-310, and much more.

However, we continue supporting Java 6 and Java 7 in the commercial distributions of jOOQ, which leaves you with these options:

1. Upgrade your Java version to Java 8
2. Upgrade your jOOQ version to the jOOQ Professional Edition
3. Stay on jOOQ 3.6 with Java 7

I strongly recommend 1) or 2). Let me know if we can be of any help with your decision.
