### ISSUE TITLE
Manual's "More info about how to read this manual" always refers to 3.4 version of the manual

### ISSUE THREAD

**Issue by arlampin** [jOOQ/jOOQ#4685]
I noticed that the small exclamation mark that appears on hover on manual's code blocks always links to version 3.4 manual, regardless of current page's version.

**Comment by lukaseder** [comment]
Ooh, thanks for letting us know. Will fix that ASAP

**Comment by lukaseder** [comment]
Fixed. You might need to refresh the website. Thanks again for reporting!
