### ISSUE TITLE
Allow specifying database name without regenerating code

### ISSUE THREAD

**Issue by jdevera** [jOOQ/jOOQ#4689]
I'm using `org.jooq.util.xml.XMLDatabase` to generate code to query a database, as a build step, in boxes with no access to the database, but I think this problem is common to any database source.

The name of the database is configurable in the project I'm working on, but I find that if I have to change it, I'd have to regenerate the code, which is not compatible with the database being a configurable parameter.

I've played around (hacked) a bit and I see I can modify the generated code to provide an initializer method to set the database name, but it involves modifying the generated code with some ugly tools.

I think this could be a nice option for the generated code, to be able to set the database name dynamically from the app code.

**Comment by lukaseder** [comment]
Does the schema mapping feature help, perhaps?
http://www.jooq.org/doc/latest/manual/code-generation/schema-mapping

**Comment by jdevera** [comment]
Actually, the runtime schema mapping does exactly what I needed. Thanks, I missed that first.

**Comment by lukaseder** [comment]
Great, glad it'll work out for you. Thanks for the feedback!
