### ISSUE TITLE
Add an unused forced type hint about Pattern.COMMENTS being turned on to help debug regexes with whitespace

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4691]
SQL Data types may contain whitespaces, e.g. `TIMESTAMP WITH TIME ZONE`. jOOQ currently doesn't match those correctly, unless the whitespace is escaped:

``` xml
<types>timestamp\ with\ time\ zone</types>
```

The reason for this is the fact that those regexes are parsed by the jOOQ code generator with the `COMMENTS` flag switched on, which removes whitespace.

This is very unfortunate in cases like the above. We should find a way to improve this.

---

See also:
http://stackoverflow.com/q/33173842/521799

**Comment by heenenee** [comment]
The `COMMENTS` flag was introduced by https://github.com/jOOQ/jOOQ/issues/3860.

**Comment by lukaseder** [comment]
@heenenee Thanks for the additional hint. That'll come in handy looking into the feature history!

**Comment by lukaseder** [comment]
#9520 added log information about unused forced types. We could add additional information about whitespace as debug information in that message.
