### ISSUE TITLE
Relax API contracts on DAOImpl by removing final keyword on methods

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4696]
We generally discourage extending jOOQ behaviour via subtype polymorphism. This is why we make heavy use of package private visibility as well as of the `final` keyword on methods and classes.

There is one type, however, where our application of `final` has been heavily criticised in the past: `DAOImpl`, the base class for all generated `DAO` objects.

This is clearly a sign that we got our `DAO` contract(s) wrong - albeit the existing feedback doesn't help much in improving the contract. It may be OK, for the time being, to relax the constraints on the API by removing `final`. Eventually, we'll get more feedback as users continue to extend this type.

----
See also: #4854

**Comment by lukaseder** [comment]
This is a non-breaking change that imposes no risk when merging to older releases. It will thus be merged to 3.5.5 (#4866), 3.6.5 (#4865), and 3.7.3 (#4864)

**Comment by danadam** [comment]
One disadvantage of having them non-final is that varargs methods can't have @SafeVarargs annotation.

**Comment by lukaseder** [comment]
Yeah, I suspect we'll live with that limitation now, given that #5984 might be implemented soon...
