### ISSUE TITLE
Make CombinedCondition public or add new DSL method

### ISSUE THREAD

**Issue by brmeyer** [jOOQ/jOOQ#4719]
Consider an "advanced search" function, querying user profiles.  The resulting query might look something like the following.

Search input: "Brett Meyer"

Where condition:
(first_name = 'Brett' OR last_name = 'Brett') AND (first_name = 'Meyer' OR last_name = 'Meyer')

From a real world example, I'm building up a List of Conditions, which later gets applied as a where condition:

```
List<Condition> conditions = new ArrayList<>();

...

List<Condition> searchConjunction = new ArrayList<>();
for (String searchToken : searchSplit) {
	Condition searchTermDisjunction = Projects.PROJECTS.TITLE.eq(searchToken)
			.or(Projects.PROJECTS.PROJECT_DESCRIPTION.eq(searchToken))
			.or(Projects.PROJECTS.RECIPIENT_FIRST_NAME.eq(searchToken))
			.or(Projects.PROJECTS.RECIPIENT_LAST_NAME.eq(searchToken))
			.or(Projects.PROJECTS.RECIPIENT_ADDRESS_1.eq(searchToken))
			.or(Projects.PROJECTS.RECIPIENT_ADDRESS_2.eq(searchToken))
			.or(Projects.PROJECTS.RECIPIENT_CITY.eq(searchToken))
			.or(Projects.PROJECTS.RECIPIENT_STATE.eq(searchToken))
			.or(Projects.PROJECTS.RECIPIENT_PHONE.eq(searchToken))
			.or(Projects.PROJECTS.RECIPIENT_EMAIL.eq(searchToken));
	searchConjunction.add(searchTermDisjunction);
}
conditions.add(new CombinedCondition(Operator.AND, searchConjunction));
```

So, I'm dynamically building a conjunction of disjunctions.

Note the last line.  Since CombinedCondition is not public, I'm out of luck here.  Thoughts on making CombinedCondition public or adding `DSL#conjunction(List<Condition>)` / `DSL#disjunction(List<Condition>)` methods?  The latter would be cleaner...

Of course, there may be a cleaner way to do this specific example, but the concept could be applicable elsewhere.

Happy to contribute a PR, but thought I'd get feedback first.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion.

The currently available public API for this use-case is [`DSL.condition(Operator, Condition...)`](
http://www.jooq.org/javadoc/latest/org/jooq/impl/DSL.html#condition-org.jooq.Operator-org.jooq.Condition...-) and its overload [`DSL.condition(Operator, Collection<? extends Condition>)`](
http://www.jooq.org/javadoc/latest/org/jooq/impl/DSL.html#condition-org.jooq.Operator-java.util.Collection-)

Does that sufficiently cover your case?

**Comment by lukaseder** [comment]
Oh, and there are also these, which are even shorter:

- [`DSL.and(Condition...)`](http://www.jooq.org/javadoc/latest/org/jooq/impl/DSL.html#and-org.jooq.Condition...-)
- [`DSL.and(Collection<? extends Condition>)`](http://www.jooq.org/javadoc/latest/org/jooq/impl/DSL.html#and-java.util.Collection-)
- [`DSL.or(Condition...)`](http://www.jooq.org/javadoc/latest/org/jooq/impl/DSL.html#or-org.jooq.Condition...-)
- [`DSL.or(Collection<? extends Condition>)`](http://www.jooq.org/javadoc/latest/org/jooq/impl/DSL.html#or-java.util.Collection-)

Added as of #3904

**Comment by brmeyer** [comment]
Argh!  Of course.  Apologies -- don't try new things at 1am w/ little sleep ;)

**Comment by lukaseder** [comment]
I can relate to that :)
