### ISSUE TITLE
Recognise pgjdbc-ng JDBC URL in JDBCUtils.dialect(String)

### ISSUE THREAD

**Issue by alokmenghrajani** [jOOQ/jOOQ#4730]
com.impossibl.postgres.jdbc.PGDriver requires using jdbc connection strings which look like "jdbc:pgsql:...". (more info https://github.com/impossibl/pgjdbc-ng).

Besides a missing if statement (`url.startsWith("jdbc:pgsql:")`) in `JDBCUtils.dialect(String url)`, jOOQ seems to work fine with this alternate postgres driver.

**Comment by lukaseder** [comment]
Thank you very much for pointing this out. The additional JDBC URL is unique enough, I'm sure we can go ahead with this binding.

I'm curious, what's the advantage of using this alternative JDBC driver for PostgreSQL?

**Comment by alokmenghrajani** [comment]
The new driver has PreparedStatement caching. I'm not sure if our setup leverages it, but we decided to give it a shot.
