### ISSUE TITLE
Repeated calls to SELECT on the same Insert object no longer create new InsertSelectQueries

### ISSUE THREAD

**Issue by ruke47** [jOOQ/jOOQ#4736]
As of https://github.com/jOOQ/jOOQ/commit/e7dec0fb210b2527e188081b77874d39a8c5cddc#diff-9f32bb484c0a5fa834f7e52868d95dcaR146

I have, roughly
```java
final InsertValueStep2<TableRecord, Integer, String> base = 
        db.insertInto(TABLE, TABLE.COL_A, TABLE.COL_B);
final List<Insert<TableRecord>> inserts = new ArrayList<>();
for (Pair<Integer, String> pair : myData) {
    base.select(pair.getValue0(), pair.getValue1());
}
db.batch(inserts).execute();
```

As of 3.7.0, only the last value in my Collection of Pairs will "win", and get inserted into the database.

I'm not sure if this counts as a duplicate of #4402 or not.

**Comment by lukaseder** [comment]
Thank you very much for reporting. That's a very interesting observation. I'm surprised that it would have worked before, though. An `INSERT .. SELECT` statement can have only one `SELECT` statement.

The correct usage would be to either:

- Collect all pairs into individual `Select` and then combine them all with `UNION ALL`.
- Use `INSERT .. VALUES`, which can be called multiple times.
- Use the model API (`db.insertQuery()`) instead, which is more straightforward for these cases.

There is a more general API problem here. In principle, you shouldn't be allowed to call that `select()` method several times. With jOOQ 4.0, as of #2198, all DSL API elements will become immutable. This will help prevent such API usage.
