### ISSUE TITLE
Add Settings for default naxRows, fetchSize, queryTimeout and other values

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4753]
Users can specify JDBC flags on a per-query basis also with jOOQ, e.g. `fetchSize` or `queryTimeout`. It would be good to be able to specify a default that is applied to all queries executed by jOOQ.

----
See also:
http://stackoverflow.com/q/33867507/521799

**Comment by pires** [comment]
Is the timeout in milliseconds or what?

**Comment by lukaseder** [comment]
No, seconds. jOOQ doesn't do anything special here. It's just delegating the value to JDBC's `Statement.setQueryTimeout()`

**Comment by KirillKurdyukov** [comment]
Hi, Lukas! Why is the timeout in seconds and not in milliseconds?

**Comment by lukaseder** [comment]
https://github.com/jOOQ/jOOQ/issues/4753#issuecomment-234723119
