### ISSUE TITLE
Reduce log level of most DefaultRelations messages from INFO to DEBUG

### ISSUE THREAD

**Issue by tomdcc** [jOOQ/jOOQ#4764]
Hi

We are generating DAOs etc for out table in a Postgres `public` schema, and are explicitly telling the code generator that we are only interested in that schema via the `inputSchema` option.

We are getting a number of warnings about foreign keys on tables that are not in that schema, like this:

```
Ignoring foreign key     : my_table__my_fkeyname (public.my_table.my_column) referencing some_other_table_pk references a schema out of scope for jooq-meta: null
```

I've explicitly asked jOOQ not to look in other schemas, so I shouldn't get warnings about those.

As a workaround I could stop logging warnings, but I don't want to turn off ALL warnings as I'd like to see others that might appear.

**Comment by lukaseder** [comment]
Thank you very much for reporting this. The idea behind the warning is to indicate that perhaps, you might want to have this foreign key relationship in your output, but you don't know why it doesn't appear.

I agree that some log messages tend to unnecessarily fill the logs when you "know what you're doing". Adding means of fine-tuning logging, however, will need more foresight, as such fine-grained configuration flags are hard to maintain. What's bothering you in particular, here? The amount of log messages? The warning rather than info level?

**Comment by tomdcc** [comment]
Hi Lukas, thanks for the quick response.

I could configure the log level to never show warnings from jOOQ, but then I might miss something that appeared during later development. I'd rather not do that.

I have put some workarounds in our builds (explicitly excluding all known pgcrypto functions and explicitly dropping test schemas before doing generation) but before I did that there were a LOT of jOOQ warnings. I could have left them there, but the result would be the same as hiding them all - a new "real" warning would get missed among all the noise.

As far as the issue that I raised here, I think this is a bug, not just a warning configuration issue. If I've explicitly asked to map schema "x", I shouldn't get warnings about schema "y".

On the general issue of warnings, they're warnings (And not errors) because sometimes they're not an issue. Warnings are really only useful if you can turn them off in the specific cases that are ok - otherwise they're just noise.

**Comment by lukaseder** [comment]
> As far as the issue that I raised here, I think this is a bug, not just a warning configuration issue. If I've explicitly asked to map schema "x", I shouldn't get warnings about schema "y".

I see what you mean, but the bug is really the fact that this is a warning, rather than debug level log, right?

The same might apply to the other issue you've reported

**Comment by lukaseder** [comment]
The log level for this particular message is INFO, currently (and has been, for a while), not `WARN`. I guess we could further reduce the log level to `DEBUG` as constraint information isn't really too interesting in the code generator...
