### ISSUE TITLE
Unnecessary SQL exception logged in code generator

### ISSUE THREAD

**Issue by ookke** [jOOQ/jOOQ#4783]
This exception appeared after upgrading from jOOQ 3.5.4 code generator to 3.7.1. We are using Postgres 9.3, I'm a bit puzzled because:

a) the query has a where 1=0 clause which will cause it to never return anything

b) I checked the information_schema.parameters table in our db and indeed it doesn't have a parameter_default column, is the jooq postgres meta schema based on a newer postgres version where this was added or?

```
SQL exception            : Exception while executing meta query: ERROR: column parameters.parameter_default does not exist
  Position: 8

Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new

select "information_schema"."parameters"."parameter_default"
from "information_schema"."parameters"
where 1 = 0
```

**Comment by ookke** [comment]
Looks like it has been added in Postgres 9.4: http://www.postgresql.org/docs/9.4/static/infoschema-parameters.html vs. http://www.postgresql.org/docs/9.3/static/infoschema-parameters.html

**Comment by lukaseder** [comment]
Thanks for reporting. This is a check that we run to see if the relevant column exists. The 1=0 predicate is there to prevent results, we don't care about results, we only care about the exception. 

See:
https://github.com/jOOQ/jOOQ/blob/version-3.7.1/jOOQ-meta/src/main/java/org/jooq/util/postgres/PostgresRoutineDefinition.java#L153

However, you shouldn't see that exception in your logs, though. It's a perfectly accepted situation. We'll investigate why this shows up in your logs.

**Comment by ookke** [comment]
Ah, makes sense. Thanks for the clarification!

I get the output when running a gradle task that does the code generation if that makes any difference in reproducing this.

**Comment by lukaseder** [comment]
It shouldn't make a difference, but might be interesting heads-up, thanks!

**Comment by lukaseder** [comment]
I can reproduce this issue with PostgreSQL 9.3. It happens in any code generation configuration. Will fix this ASAP.

Thanks again for reporting!
