### ISSUE TITLE
Add Schema.getCatalog() and render the catalog in SQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4792]
Some databases (e.g. SQL Server) support a catalog, which contains several schemas. Typically, the catalog maps to the database.

jOOQ should (finally) support the catalog object.

----
See also: #2032

**Comment by ooxi** [comment]
:+1:

**Comment by lukaseder** [comment]
Thanks for the feedback, @ooxi. This feature was overdue.

**Comment by ooxi** [comment]
Any chance this will be available to 3.7, too? Or when is a 3.8 release to be expected?

**Comment by lukaseder** [comment]
> Any chance this will be available to 3.7, too?

No way I will merge this to 3.7 :-) Specifically, the code generator change (#2032) is huge and there is substantial risk of regressions / unforeseen edge cases / subtly backwards-incompatible configuration changes.

> Or when is a 3.8 release to be expected?

Hopefully by the end of Q1 2016, but such a date is never a promise :) The big features which may delay this are:

- SQL:2011 temporal validity support
- DB2 for z support
- VoltDB support

But you should be able to build 3.8-SNAPSHOT with this feature by the end of this week, I hope.

**Comment by lukaseder** [comment]
What database are you using jOOQ with, btw? PostgreSQL?

**Comment by ooxi** [comment]
I did not realize this patch relies on another huge patch, not merging is expected then (after all it's a feature so 3.8 is the right place anyway. I was just curious to use it). Using a 3.8 snapshot will work, too :)

**Comment by lukaseder** [comment]
Yeah, well, this here is just a small issue for the "less important" part - the runtime API. By itself, it wouldn't be very useful anyway - apart from plain SQL usage.

**Comment by lukaseder** [comment]
@ooxi What database are you using jOOQ with? I might not implement catalog support for all databases right away... But it would be great to cover yours if you want to play around with it :)

**Comment by ooxi** [comment]
@lukaseder SQL Server :)

**Comment by lukaseder** [comment]
@ooxi: Ooh, Jackpot - that's the main target database for this feature right now. But then you cannot build it yourself from GitHub. We'll release a SNAPSHOT preview to the website next week, then:
http://www.jooq.org/download/versions

Will let you know!

**Comment by lukaseder** [comment]
@ooxi: This feature is now available in the latest SNAPSHOT preview download from our website:
http://www.jooq.org/download/versions

As this is a snapshot, we recommend not going to production with this preview release, as things are still moving and might change.

Your early feedback is very welcome, though!
