### ISSUE TITLE
temporarily disable auto commit before query?

### ISSUE THREAD

**Issue by jgangemi** [jOOQ/jOOQ#4826]
is it possible to disable auto commit via the `DSLContext` before executing a query and if so, how? i want to change the fetch size for a cursor/stream query which postgres doesn't like with auto commit enabled.

if this can't be done, do you have any suggestions on how to pull back 1 million+ rows in an efficient and fast manner? my current thought is to get the max primary key value and page through it.

thanks!

**Comment by lukaseder** [comment]
The real question here is: What are you using for your transaction layer? Spring TX, or Java EE? Or jOOQ's transaction API?

Specifying the fetch size is certainly an option. Another one would be to use the synthetic `SEEK` clause in jOOQ:
http://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/seek-clause

Don't use `OFFSET` pagination in this case:
http://use-the-index-luke.com/no-offset

**Comment by jgangemi** [comment]
i'm using jOOQ's transaction api however i don't have a need for a transaction w/ this query.

ultimately what i'm looking to do is run the select statement and then dump the results into queue where another process will pick them up for export. i'm currently doing this w/ a `cursor` (although i am about to start using streams now that java 8 support that has been added), but the performance of the cursor is horrible and i `OOME` if try to use the default fetch size w/ the stream. 

as a test i disabled auto commit (on the connection via the datasource), set the fetch size iterated the results using the stream and the performance was much better.

**Comment by lukaseder** [comment]
Turning off autocommit means you're implicitly starting a transaction... Within a jOOQ transaction scope, autocommit is thus turned off:

```java
DSL.using(configuration)
   .transaction(c -> {
      // Autocommit is turned off for all queries in here...
   });
```

Clearly, to prevent the `OOME`, you should set the fetch size and / or perform keyset pagination (`SEEK` clause).

As far as `org.jooq.Cursor` vs. `java.util.stream.Stream` is concerned, they're equivalent in terms of performance.

I hope this helps. Let me know if you have any additional questions.

**Comment by jgangemi** [comment]
awesome, i will give that a try, thank you!!!!
