### ISSUE TITLE
Add code generation support for column DEFAULT values

### ISSUE THREAD

**Issue by dbarbato** [jOOQ/jOOQ#4841]
As a part of unit and integration testing, we're using jooq to recreate our database in H2. To do this we're leveraging the DefaultSchema and jooq generated objects.

The original database has default values on several columns, those columns are also not nullable. There currently doesn't appear to be a way to  capture the default values during the object generation phase.

We've looked through the documentation and can't see anything to enable this functionality. Have we missed something or would this be a feature request? If this is a feature request, is there a workaround we could use in the mean time?

Many thanks

**Comment by lukaseder** [comment]
Thanks for your enquiry.

What do you mean by *"capture the default values during the object generation phase"* ? Default values are supported, but I'm not sure what you're missing...

**Comment by dbarbato** [comment]
Thanks for getting back to me so quickly!

We have original tables defined in mysql which resemble : 
```
CREATE TABLE `tableA` (
  `column1` varchar(73) DEFAULT NULL,
  `column2` timestamp NOT NULL DEFAULT '2010-10-10 00:00:00',
  `column3` timestamp NOT NULL DEFAULT '2010-10-10 00:00:00',
  `utc_mod_time` timestamp NOT NULL DEFAULT '2010-10-10 00:00:00' ON UPDATE CURRENT_TIMESTAMP
) 
```
(While this shows default values for timestamps, this could also apply to varchar or other types)
The objects that we're currently generating don't have any reference to the default values that columns1-3 store. This means that when we go to recreate the database in H2, we have no means to automatically set the default value for a column.

Currently I'm doing the following to generate the in memory version of the database:
```
		List<Table<?>> tables = DEFAULT_SCHEMA.getTables();
		for (Table<?> table : tables) {
			CreateTableAsStep<Record> tableToCreate = jooq.createTable(table);
			CreateTableColumnStep column = null;
			for (@SuppressWarnings("rawtypes")
			Field field : table.fields()) {
				column = tableToCreate.column(field, field.getDataType());
			}
			if (column != null) {
				System.out.println(column.getSQL());
				column.execute();
			}
		}
```

**Comment by lukaseder** [comment]
Oh, I see. Thanks for the details. Indeed, jOOQ does not get a hold of the expression used for defaulted columns, only the fact that it is defaulted. I'll turn this into a feature request to consider adding this in a future version.

I can currently not think of a workaround. Specifically, I'm assuming that your "real" database schema is not H2 but MySQL, and this is one of the areas where databases aren't 100% standards compliant. What keeps you from developing / testing against MySQL directly?

**Comment by dbarbato** [comment]
Sorry, I thought I'd mentioned the original was MySQL, I must have edited it out of one of my original comments. 

There's nothing stopping us from doing that, infact it's what we currently do. 

There are several reasons we're looking at running the database in memory during the dev phase:

1. It should speed up the test cycle on the local machine. 
2. The database is much more likely to be running the correct schema at the correct version - devs aren't expected to run liquibase every time someone makes a change, the latest schema is just pulled down by maven and used next time a test is run.
3. The database starts in a known state. There's no one accidentally relying on data that's hanging around. 

We will continue to run the tests against mysql during CI to ensure compatibility.

**Comment by dbarbato** [comment]
In order to work around this for the time being, I was trying to set a hard coded default value based on the column type. The only place in the API I can see to set a default value is  http://www.jooq.org/javadoc/latest/org/jooq/AlterTableAlterStep.html , is there a way to do this via the create statement, or only via alter table?

**Comment by lukaseder** [comment]
Hmm, our integration tests don't indicate that DDL run against MySQL is much much slower than DDL run against H2 - but it's up to you. There's always a tradeoff between correctness and performance... Perhaps you'll find a way to auto-generate equivalent DDL, although from my experience, it's often good to do some of these things manually.

Unfortunately, jOOQ really currently doesn't support custom `DEFAULT` clauses in DDL, neither when reading meta data, nor when creating it. See also #3852
