### ISSUE TITLE
Query.getBindValues() returns <U> types. Add a new method returning <T> types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4886]
The current implementation of `Query.getBindValues()` collects the `<U>` type values put into `DSL.val()`, which are the user types in the context of converters or bindings.

We should also have a method that returns the `<T>` types (database types). It is important to note that the behaviour will depend on whether the `Query` is attached, i.e. whether a `SQLDialect` is available.

Potentially, it will be best to deprecate the existing method and add two new methods with very clear semantics. A substantial amount of manual pages need to be updated.

---

See also:
http://www.jooq.org/doc/latest/manual/sql-execution/alternative-execution-models/using-jooq-with-jpa/using-jooq-with-jpa-entities/#comment-2432835053

**Comment by nkoterba** [comment]
:+1: Thanks for the quick response to the documentation comment and also creating this issue.

I like the suggested solution...having a method on the `Query` object that returns the `<T>` (database types) would be ideal for this use case scenario so that Jooq users do not have to fuss with matching up query parameters and also calling `converter.to` (which gets a bit at the internals of Jooq) versus its functionality.

**Comment by lukaseder** [comment]
Unfortunately, the comments on the manual have been deleted, so I don't know the exact discussion anymore.

While extracting the `U` types is straightforward (they're the types embedded in the query), extracting the `T` types is not. A `T` type can be obtained by invoking a `Converter<T, U>` (simple) or by calling through to a `Binding<T, U>` (much harder), where `T` of the `Binding<T, ?>` isn't even guaranteed. A `Binding` can bind anything it wants to JDBC.

As such, the method this issue suggests adding would have to collect binds via a dummy `PreparedStatement`.

Users can already call `getParams()` to get a hold of all the embedded `Param<?>` values. From there on, they might be able to invoke converters manually if they know what they're doing. Shouldn't be too much extra glue code for this edge case.

I won't change this in jOOQ. The use-case of extracting bind values is rather marginal. It is only useful for those cases where users try to avoid migrating query execution also to jOOQ, which should be inevitable. While jOOQ does support extracting SQL and binds, the ideal use-case of using jOOQ is to execute queries with jOOQ directly. A ton of great features are accessible only this way (e.g. `MULTISET`).
