### ISSUE TITLE
Add UniqueKey.getName() and ForeignKey.getName(), and generate this info in Keys.java

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4901]
When using generated code for DDL, it is currently not possible to find the name of a primary / unique / or foreign key apart from the literal in Keys.java (which is accessible in theory via reflection, although that's not nice).

We should add additional API that allows for accessing this information programmatically, and then adapt the code generator to generate the info in String form.

**Comment by cluelessjoe** [comment]
Thanks =)

**Comment by lukaseder** [comment]
@cluelessjoe You're welcome! :)
