### ISSUE TITLE
Codegen from Flyway migration scripts

### ISSUE THREAD

**Issue by cvanes** [jOOQ/jOOQ#4905]
Would it be possible to generate jOOQ required classes from Flyway migration scripts? We'd like to be able to remove the need to connect to a database at build time but we don't want to lose the type safety benefits by doing so.

**Comment by lukaseder** [comment]
jOOQ supports an `XMLDatabase` meta data source:
http://www.jooq.org/doc/latest/manual/code-generation/codegen-xml

Third party XML formats can be XSL transformed into jOOQ's format, which has to be in this form:
http://www.jooq.org/xsd/jooq-meta-3.5.4.xsd

Does Flyway support snapshot XMLs or something similar? From what I thought I'd know, Flyway only manages deltas, in case of which this appraoch will be a bit tricky...

**Comment by cvanes** [comment]
It doesn't look like Flyway supports a snapshot of the latest database schema in XML format but the XMLDatabase approach looks like it will fit our needs. Thanks!

**Comment by lukaseder** [comment]
OK, great. Let us know if you need any additional info
