### ISSUE TITLE
Generated functions without parameter names produce malformed SQL

### ISSUE THREAD

**Issue by rbellamy** [jOOQ/jOOQ#4920]
I generated a Postgres Plus Advanced Server function, which has a SQL signature of:
```sql
CREATE OR REPLACE FUNCTION edb_get_function_arguments(oid)
```
And jOOQ created Java:
```java
/**
 * This class is generated by jOOQ
 */
package com.terradatum.jooq.util.postgresplus.pg_catalog.routines;


import com.terradatum.jooq.util.postgresplus.pg_catalog.PgCatalog;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.8.0"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EdbGetFunctionArguments extends AbstractRoutine<String> {

	private static final long serialVersionUID = -777686852;

	/**
	 * The parameter <code>pg_catalog.edb_get_function_arguments.RETURN_VALUE</code>.
	 */
	public static final Parameter<String> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.CLOB, false);

	/**
	 * The parameter <code>pg_catalog.edb_get_function_arguments._1</code>.
	 */
	public static final Parameter<Long> _1 = createParameter("_1", org.jooq.impl.SQLDataType.BIGINT, false);

	/**
	 * Create a new routine call instance
	 */
	public EdbGetFunctionArguments() {
		super("edb_get_function_arguments", PgCatalog.PG_CATALOG, org.jooq.impl.SQLDataType.CLOB);

		setReturnParameter(RETURN_VALUE);
		addInParameter(_1);
	}

	/**
	 * Set the <code>_1</code> parameter IN value to the routine
	 */
	public void set__1(Long value) {
		setValue(_1, value);
	}

	/**
	 * Set the <code>_1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
	 */
	public void set__1(Field<Long> field) {
		setField(_1, field);
	}
}
```
Which I was then using like this:
```java
Routines.edbGetFunctionArguments(oid(p.asTable)).as("arguments")
```
Producing the following SQL:
```sql
"pg_catalog"."edb_get_function_arguments"("_1" := "p".oid) as "arguments"
```
And generating the following syntax error:
```
ERROR: function pg_catalog.edb_get_function_arguments(_1 := oid) does not exist
Hint: No function matches the given name and argument types. 
You might need to add explicit type casts.
```

I did see your mention of the `format_type` system function in the mailing list, but can find no examples of its use. My guess is that the SQL generator should not use named notation when calling functions that are prefixed by the underscore (e.g. `_1`) in the generated code, as that is an indicator that the source SQL doesn't have a named parameter.

*Work-around:*
```
field("edb_get_function_arguments({0})", String.class, oid(p.asTable())).as("arguments")
```

**Comment by lukaseder** [comment]
Thanks for reporting. It does seem that this rare use-case is not yet supported by the jOOQ runtime, even though the code generator handles it correctly. Or, put differently, there's a regression introduced in jOOQ 3.7 by the support for defaulted parameters (#4254).

My I ask what the use-case of using unnamed parameters in PostgreSQL is?

**Comment by rbellamy** [comment]
Calling numerous (dare I say all?) system functions. I just wrapped up a first-pass at creating definitions for use with Postgres Plus Advanced Server (PPAS) - specifically to support package codegen.

During that effort, I needed to call the function mentioned to get the method signature.

**Comment by lukaseder** [comment]
Oh, interesting, I wasn't aware of that. That makes this a significant regression, then! Will fix ASAP
