### ISSUE TITLE
Convert.convert(long, Instant.class) shouldn't pass by LocalDateTime

### ISSUE THREAD

**Issue by alexwen** [jOOQ/jOOQ#4935]
The jOOQ Convert class improperly converts to an Instant:
https://github.com/jOOQ/jOOQ/blob/11115c674127bed3d9c40b6d10b0dfa33d94398a/jOOQ/src/main/java/org/jooq/tools/Convert.java#L1061

relevant code:
```
            else if (toClass == Instant.class) {
                return (X) new Timestamp(time).toLocalDateTime().atOffset(OffsetDateTime.now().getOffset()).toInstant();
            }
```

This will result in an incorrect conversion in places with changing offsets, as in parts of the United States, if the server is not configured to use the default offset. If the time being converted is in a different offset in the future or past then the current offset, then the result of this conversion will be off by an hour or more.

It would be much simpler here to, and less error prone, to use `Instant.ofEpochMillis` instead of using the local date and time as an intermediary.

**Comment by lukaseder** [comment]
Thanks for reporting. This has probably just been an oversight. `Instant.ofEpochMillis` is indeed much more suitable.
