### ISSUE TITLE
Add support for CREATE TABLE IF NOT EXISTS

### ISSUE THREAD

**Issue by yakovsh** [jOOQ/jOOQ#4936]
Right now only CREATE TABLE is supported, it would be nice to have support for CREATE TABLE IF EXISTS.

I can try putting together a pull request if interested.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I suspect you mean adding support for `create table if NOT exists`... This would indeed be useful, and I think that other `CREATE [ object ] IF NOT EXISTS` statements could be supported as well.

A pull request would be very appreciated. Please find our contributor guidelines here and let me know if you have any questions:
https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

**Comment by lukaseder** [comment]
Just needed this myself today :)
Fixed.
