### ISSUE TITLE
Add a jOOQ / Flyway migration example using programmatic migration scripts

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4945]
The current jOOQ / Flyway migration example shows how to use Flyway to migrate text-based SQL scripts.

Sometimes, it may be useful to use jOOQ's DDL API instead, using type safe schema representations for each migration. We should show how this can be done by example

---

See:
- https://github.com/cluelessjoe/jooq-flyway-typesafe-migration
- https://groups.google.com/forum/#!topic/jooq-user/I9iLbMQNN8o

**Comment by cluelessjoe** [comment]
For information the repo you mention above as been deleted a while ago and replaced by https://github.com/cluelessjoe/jooq-flyway-typesafe-migration

**Comment by lukaseder** [comment]
Thanks, I've updated the link.

I'm not sure why that issue was rejected. In all of `org.jooq.Scope`, we always allow for arbitrary user state to be passed along, regardless of that scope's semantics (an example scope is an `ExecuteListener`). This has served us very well, including using that state map ourselves in internals, when we didn't want to create new scope API for some edge case.

Having said so, I really like the type safe migrations approach you've shown. At first, it looks a bit weird, because it suffers from a bootstrapping problem. `CREATE TABLE` statements can't use generated code, because at that point, the generated code has not been generated yet. But all the other statements can use generated code.

This is definitely something to keep in mind when we start supporting multi version code generation:
https://github.com/jOOQ/jOOQ/issues/9626

**Comment by lukaseder** [comment]
Examples using third parties are quite a bit of maintenance work, keeping the third party code up to date. I think that two text based flyway examples are enough for now. I don't really want to offer a programmatic one.
