### ISSUE TITLE
DBLink error during codegen (JOOQ 3.7.1, Oracle 12c) 

### ISSUE THREAD

**Issue by eoliphan** [jOOQ/jOOQ#4951]
While doing a *jooq-codegen:generate* from maven, I got a message requesting that I log the following error with you guys

```
select 1 "one"
from "SYS"."ALL_DB_LINKS"@"EGDEMO.GRANTSOLUTIONS.GOV"
where 1 = 0
[INFO] Error while accessing dblink: SQL [select 1 "one" from "SYS"."ALL_DB_LINKS"@"EGDEMO.GRANTSOLUTIONS.GOV" where 1 = 0]; ORA-12154: TNS:could not resolve the connect identifier specified
```

**Comment by lukaseder** [comment]
Thank you very much for reporting this issue. You've already closed it: Were you able to resolve it on your side? Is there anything we can do for you regarding this issue?

**Comment by lukaseder** [comment]
Related: #4953
