### ISSUE TITLE
Deprecate Param.setValue(), setConverted(), setInline()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#4991]
With jOOQ 4.0, we're making a lot of API immutable. This should include the bind variable API. In general, it cannot be guaranteed that a single bind variable that is passed to a query like this:

```java
TABLE.COLUMN.eq(bindVariable)
```

will be retained in the generated SQL as is, or produced by `Query.getBindValues()` as is. For instance, user-defined types (see `UDT` and `UDTRecord`) may be bound as a single value to Oracle's JDBC driver, but not to PostgreSQL's JDBC driver, where the value generates a `ROW(?., ?, ..., ?)::type` expression.

It is thus unwise to allow users to modify `Param` content.

**Comment by slavap** [comment]
@lukaseder Then it would be nice to add method: ConditionWithParamProvider.createCondition(Object paramConvertedValue);
I'm using it for adding additional restrictions to my query, like:
```java
WhereCondition predefined = qryParts.findWherePredefined(si.getFldName());
String sv = si.getSearchVal();
ConditionWithParam cond = predefined.provider.createCondition();
cond.param.setConverted(sv);
andConds.add(cond.condition);
query.addConditions(Operator.AND, andConds);
```

**Comment by lukaseder** [comment]
@slavap: From your code example, I'm not so sure what you're trying to achieve, or what you're trying to suggest here. But if your use-case is to "add additional restrictions to your query", then the suggested approach *in general* (and per this particular deprecation) is to go more immutable and functional, rather than mutable and imperative.

The chapter about dynamic SQL illustrates this to some extent: https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql

And also this blog post:
https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq

**Comment by slavap** [comment]
@lukaseder I have many services, each one constructs QueryParts on initialization.
Then I have generic code, which has no any knowledge about particular tables or fields, i.e. I just cannot write: result = result.and(BOOK.TITLE.like("%" + request.getParameter("title") + "%"));
So I need to find predefined WhereCondition by field name (just string), and then substitute value to it. And of course this generic code has no information what comparison should be used: like, contains, equal, or something else.

**Comment by lukaseder** [comment]
@slavap That example resembles what I meant by a functional approach. Now, I'm not sure what exactly you're asking me here, sorry :-/

**Comment by slavap** [comment]
@lukaseder There is a long gap between second code example and first code example from my initial post, i.e. they don’t know about each other at all, so I have to use:
cond.param.setConverted(searchValue)
Which is deprecated now, so I’m asking to add new additional constructor:
predefined.provider.createCondition(searchValue)

**Comment by lukaseder** [comment]
@slavap: I'm sorry, but I can't really discuss a specific feature request like yours where you suggest a concrete method on an object chain that I don't even know what it is (what's `predefined` and what's `provider`?)

May I please ask you to create a new issue and to explain your *use-case*, rather than trying to offer a solution already? I think it is a bit early to discuss solutions before actually understanding the *use-case*.

**Comment by slavap** [comment]
@lukaseder Sure, I can create new issue. But I have described my use case exactly :-(

**Comment by lukaseder** [comment]
> But I have described my use case exactly :-(

I'm sorry but your idea of "exact description" really doesn't match mine :-)

I'm convinced that the confusion here stems from quite complicated code on your side that should be simplified first. Thus far, you have shown a few snippets, leaving out many other parts that would be required to understand *what you did*. However, I'd much prefer ot understand *what you intend to do*. Unfortunately, I don't understand that yet, and by the very nature of how you tried to explain it, I concluded that your code is too complicated and needs simplification first.

An example:

> here is a long gap between second code example and first code example from my initial post, i.e. they don’t know about each other at all

Now I'm even more confused. Should I even look at the second example, or is only the first one relevant?

> I’m asking to add new additional constructor: predefined.provider.createCondition(searchValue)

But *why* and *where* should this be added? I'm sorry, I really don't understand your use-case, nor your feature request.

Maybe this helps? https://stackoverflow.com/help/mcve

**Comment by slavap** [comment]
@lukaseder I'm very sorry, but I'm just somehow managed to mix up my own code with jOOQ's one :-( Perhaps it was wrong phase of the moon :-( 
```java
DSL public static <T> Param<T> param(String name, T value) 
```
works just fine for me and I don't need param setConverted() at all.
Sorry once again.

**Comment by lukaseder** [comment]
@slavap : Heh, that's what I thought :-) Thanks for the clarification

**Comment by slavap** [comment]
@lukaseder One more question. Query.getParams() still has the following comment: "Get a Map of named parameters. The Map itself cannot be modified, but the Param elements allow for modifying bind values on an existing Query". So what is the "proper" way to change params values now (considering future immutability of params) ? Or query should be constructed again from scratch ?

**Comment by lukaseder** [comment]
> Or query should be constructed again from scratch ?

Yes, that's the ideal way unless you're *very certain* that this causes performance issues. Do note that `Query.execute()` is not a thread safe operation anyway in jOOQ 3.x, so in most cases, you're safer constructing queries again from scratch.
