### ISSUE TITLE
Support for emulating VALUES clauses in H2 is inefficient

### ISSUE THREAD

**Issue by tjwilson90** [jOOQ/jOOQ#4992]
Currently VALUES clauses in H2 are emulated with multiple SELECT and UNION ALL queries. This performs very poorly in H2 with hundreds of clauses (and also tends to oom quickly).

It's mentioned in the source that H2's native support for VALUES clauses is not used because there is no way to rename it using derived column lists. However, couldn't
```DSL.values(rows).as(tableName, fieldNames)```
be emulated as
```SELECT C1 fieldName[0], C2 fieldName[1], ... FROM VALUES(rows[0], rows[1], ...) tableName```

From (limited) testing this seems to perform much better.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. You're right, there's room for improvement. I wonder what the limitation was at the time. It was a while when this was implemented. Probably, today, we can proceed as you suggested

**Comment by lukaseder** [comment]
(in any cas, unnesting arrays is probably even faster)

**Comment by lukaseder** [comment]
Derived column lists are already correctly emulated in H2 as in other databases using the following generic construct:

```sql
-- Native support
t AS table_alias (column_alias1, column_alias2, ..., column_aliasN)

-- Emulation
SELECT NULL AS column_alias1, NULL AS column_alias2, ..., NULL AS column_aliasN
WHERE 1 = 0
UNION ALL
SELECT *
FROM t
```

So, the suggested improvement already works out of the box.
