### ISSUE TITLE
Add CompletionStage<Result<R>> ResultQuery.fetchAsync() and fetchAsync(Executor)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5012]
There are various ways how jOOQ could implement "async" SQL (not truly async, as JDBC is still blocking). The JDK 5's standard way to execute things asynchronously is by using an `ExecutorService`, which completes tasks in a `Future`.

This API was deprecated in the past (reasons mentioned in this ticket: #2581). Java 8 now has the `CompletableFuture`, which is a much better abstraction for a `Future` than its base type. However, because a `CompletableFuture` cannot be interrupted, we might prefer the `CompletionStage` type as a result type to avoid confusion (see http://www.nurkiewicz.com/2015/03/completablefuture-cant-be-interrupted.html)

jOOQ will have two new methods `fetchAsync()` and `fetchAsync(Executor)`, which map to `CompletableFuture.supplyAsync(Supplier[, Executor])`

#4371 will deal with fetching an "observable", in order to provide not only "async" API but also "reactive" API.

**Comment by nikolaykuz** [comment]
Hello Lukas,
I wonder what happens when we use Spring transactions and  fetchAsync() ?
As far as I understand Spring transaction is bound to a thread, how do you handle it?

Please, see http://stackoverflow.com/questions/10407301/how-to-use-spring-transaction-in-multithread

**Comment by lukaseder** [comment]
@nikolaykuz The correct semantics has to be implemented in the `TransactionProvider`. I suspect it might be worth documenting this somewhere...

**Comment by lukaseder** [comment]
Documentation task here: https://github.com/jOOQ/jOOQ/issues/5351
