### ISSUE TITLE
java.lang.ClassCastException: org.jooq.impl.TableFieldImpl cannot be cast to org.jooq.SelectField

### ISSUE THREAD

**Issue by sandromark78** [jOOQ/jOOQ#5039]
The following piece of code works fine with the version 3.5.3 but it generates the exception java.lang.ClassCastException when the version 3.7.2 is used.
```java
	public <T> T getParameter(@Nonnull Configuration _conf, @Nonnull TableField<ParameterRecord, T> _tf) throws DataAccessException, IllegalArgumentException {
		return DSL.using(nonNull(_conf)).select(nonNull(_tf)).from(PARAMETER).fetchAny().value1();
	}
```
ParameterRecord is the record for the PARAMETER table.

**Comment by lukaseder** [comment]
Thank you very much for reporting. Could you please also post the stack trace you're getting for that `ClassCastException`?

**Comment by lukaseder** [comment]
Hmm, I suspect this must be a class loading issue at your side. Are you sure you don't have the old jOOQ version on the classpath somewhere?

**Comment by sandromark78** [comment]
There is not the stack trace because the exception happens in the conversion of  the parameters (in the *from* function call).  
I am using Maven and I am debugging directly from Eclipse, so I guess that it is not a classpath problem... in any case, I agree with you that it seems a class loading problem.

**Comment by lukaseder** [comment]
Hmm, I'm not sure if I understand the rationale why there isn't any stack trace. How did you know about the `ClassCastException`, then?

Is there anything you can provide us with (e.g. reproducible test case)  to help us debug this for you? As it stands now, I really cannot reproduce such an issue, I'm afraid...

**Comment by sandromark78** [comment]
I understand. I try to replicate the problem with a new piece of code for you.... before the end of the day.
Thank you very much in advance.

**Comment by sandromark78** [comment]
Hi Lukas!  
Yesterday I did more tests: it is a problem of the Eclipse environment! You was right!  
I did a specific new project only for testing that specific function call... and It worked fine!
Now I have only to fix the problem in the real production project :D
Thank you very much for your help.

**Comment by lukaseder** [comment]
Sure, no worries. Thought it would be a bit too esoteric for us not to notice :)
