### ISSUE TITLE
Add support for ALTER TABLE, SEQUENCE, VIEW, INDEX IF EXISTS ..

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5087]

**Comment by katzyn** [comment]
Your contribution to H2 was included in 1.4.192:
https://github.com/h2database/h2database/pull/287
But some `@Support` annotations are still missing for H2. I noticed `ALTER SEQUENCE`, but maybe there are others, I didn't check them all.

**Comment by lukaseder** [comment]
Thanks a lot, @katzyn. We'll check up on that. https://github.com/jOOQ/jOOQ/issues/9374
