### ISSUE TITLE
Bad deserialisation of PostgreSQL UDTs that contain boolean attributes

### ISSUE THREAD

**Issue by akobiakov** [jOOQ/jOOQ#5088]
Postgres serializes boolean fields of UDTs as `t`/`f`, so 
```
    private static final <T> T pgFromString(Class<T> type, String string) {
        ...
        else if (type == Boolean.class) {
            return (T) Boolean.valueOf(string);
        }
```
produces `false` for the `t` literal.
Note that the behaviour [was changed](http://www.postgresql.org/docs/9.5/static/release-9-5.html#AEN125316) in Postgres 9.5:
> Use assignment cast behavior for data type conversions in PL/pgSQL assignments, rather than converting to and from text (Tom Lane)
>
> This change causes conversions of Booleans to strings to produce true or false, not t or f. 

See also http://www.postgresql.org/docs/9.4/static/datatype-boolean.html

**Comment by lukaseder** [comment]
Thank you very much for reporting. Indeed, there's something fishy here. I cannot seem to insert this type into a table either. Will investigate

**Comment by lukaseder** [comment]
Never mind the insert issue. That's a regression on 3.8.0-SNAPSHOT only due to a recent optimisation.

**Comment by lukaseder** [comment]
This was an easy fix. We already have facilities that can handle various string representations for boolean literals. I guess this was just an oversight in this particular PostgreSQL-specific deserialisation logic.

Thanks again for reporting!

**Comment by akobiakov** [comment]
Thank you very much for the quick fix! Looking forward to see this released some day. :)
