### ISSUE TITLE
Wrong SQL generated for multi row INSERT when ON DUPLICATE KEY IGNORE is emulated

### ISSUE THREAD

**Issue by MatiasSMd** [jOOQ/jOOQ#5089]
Using **JOOQ v3.7.2**
Using **PostgreSQL 9.5**

With the following (example) table:
```sql
CREATE TABLE "public".countries (
  country_code CHARACTER VARYING PRIMARY KEY
);
```
The following code fails to work as expected:
```java
create.insertInto(COUNTRIES, COUNTRIES.COUNTRY_CODE)
  .values("AR")
  .values("US")
  .onDuplicateKeyIgnore()
  .execute();
```

Since it only inserts "US".

------------------
The generated query seems to be:
```sql
insert into "public"."countries" ("country_code")
select 'US'
where not exists (
  select 1 as "one"
  from "public"."countries"
  where "public"."countries"."country_code" = 'US'
)
```

(which, BTW, doesn't use [the PostgreSQL support for upsert](https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#INSERT_..._ON_CONFLICT_DO_NOTHING.2FUPDATE_.28.22UPSERT.22.29) which I thought it was supported by JOOQ 3.7 as for #4299)

**Comment by lukaseder** [comment]
Thank you very much for your report and for your suggestion.

I've registered a separate issue #5093 for the improved emulation of `ON DUPLICATE KEY IGNORE` via `ON CONFLICT` in PostgreSQL 9.5. This issue will deal with the bad emulation of `ON DUPLICATE KEY IGNORE` with multi-row inserts, which affects all SQL dialects

**Comment by lukaseder** [comment]
Regarding #5093, this works when you're using `SQLDialect.POSTGRES_9_5`. I've fixed this to work also with `SQLDialect.POSTGRES` which should always represent the "latest" dialect of a currently supported database.
