### ISSUE TITLE
ScalaGenerator produces an invalid import expression for SQL array types

### ISSUE THREAD

**Issue by kusamakura** [jOOQ/jOOQ#5095]
Following this [post from StackOverflow](http://stackoverflow.com/questions/30751083/convert-types-of-postgresql-uuid-arrays-using-jooq) (related: https://github.com/jOOQ/jOOQ/issues/4388), I tried to use the built-in ScalaGenerator. One of my tables has an Array data type. jOOQ generates the following first few lines for the table definition and for the record definition:
```scala
import Array

import java.lang.Class
import java.lang.String
import java.util.UUID
```

The erroneous line is `import Array`, as it's unqualified. It's being used for passing an argument to `@Generated`. Scala's default Array definition works fine, and removing this line fixes the problem.

**Comment by lukaseder** [comment]
Thank you very much for reporting this issue. We'll look into this ASAP.

Perhaps, as a workaround, you could use the `maven-ant-plugin` to search-replace `import Array` out of generated files after the code generation ran through...

**Comment by kusamakura** [comment]
No problem. I went back to using the default JavaGenerator for the time being. Oh, and thanks for the great work you're doing here!
