### ISSUE TITLE
Result.formatXXX() methods should flush Writers to prevent data loss

### ISSUE THREAD

**Issue by MatiasSMd** [jOOQ/jOOQ#5106]
Using jOOQ 3.7.2 (confirmed in master)

The issue seems to be caused by the fact that an `OutputStreamWriter` is created to wrap the (argument) `OutputStream` but is not flushed:
eg (in `master 2e91fda46154f229bf82b9af988f65f896a50d49`):
```
ResultImpl:732: formatCSV(new OutputStreamWriter(stream), header, delimiter, nullString);
```

I tried to create a pull request (even created the [fork](https://github.com/MatiasSMd/jOOQ)) but then realized that I can't do a flush so easily because it throws a `java.io.IOException` (not allowed by the method signature).
Looking around the code, I noticed the (unchecked) org.jooq.exception.IOException, but wouldn't fit in this case since this wouldn't be a DB IO error.

So, I let you decide which is the best solution (not that my pool request would save you much work anyway :p )

**Comment by lukaseder** [comment]
Thanks for your report. And nice catch. Indeed, it would make sense to flush all writers at the end of existing `try { ... } catch` blocks. Will fix right away
