### ISSUE TITLE
Remove Vertabelo Plugin from jOOQ-meta-extensions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5113]
In the past, we have tried different integrations and collaborated with other vendors. These collaborations have usually not produced enough traction for us, including:

- The jOOQ Console
- The SQL Parser integration
- The Vertabelo plugin

In this particular case (Vertabelo Plugin), recent events have shown that we have been supporting a potential competitor for our own market (http://mobile-orm.vertabelo.com), which is why we can no longer ship this plugin.

The plugin will remain Open Source and Apache 2.0 Licensed. It is still available in relevant distributions from Maven Central, e.g.
http://search.maven.org/#artifactdetails%7Corg.jooq%7Cjooq-meta-extensions%7C3.7.2%7Cjar

And Vertabelo is obviously more than welcome to continue maintaining it, hosting it elsewhere, and blogging about it (see also #5111)

**Comment by aner-perez** [comment]
Doh!  Say it ain't so!  This plugin brought me great joy in the last 6+ months...  Vertabelo and JOOQ fit so well together.  I was checking if the new XML schema changes in Vertabelo were being worked on when I found this issue (and #5111 ).  Excuse me while I cry quietly in the corner :-(

**Comment by lukaseder** [comment]
Thank you very much for your feedback. We're very sorry about these developments ourselves. But this doesn't mean the integration will no longer work (or perhaps be maintained by Vertabelo). It only means we're no longer shipping the extension with our next releases.

Vertabelo's (e-point's) strategy is to support all sorts of ORMs (not only Java ones), and at the same time, offer basic ORM solutions with Mobile ORM and OneWebSQL. In our opinion, this means it will be better for Vertabelo to host the Vertabelo-jOOQ-integration on their servers, under their namespaces.

**Comment by aner-perez** [comment]
I totally understand but it still makes me said when mommy and daddy decide to live separately.  I have brought this issue up on the Vertabelo forums to see what their response is.

Sadly, the timing is not the best because the current code generator plugin for Vertabelo is not able to detect primary keys due to the recent Vertabelo schema change, making the generated code less than optimal.  This leaves me with no easy path forward until Vertabelo decides to adopt this code.

**Comment by lukaseder** [comment]
> I have brought this issue up on the Vertabelo forums to see what their response is.

Do you have a link, perhaps?

As a workaround, for the time being, Vertabelo's fork containing the upgrade can be built from this GitHub repository:
https://github.com/nablaone/jOOQ

I hope this helps

**Comment by aner-perez** [comment]
Good news!  They have agreed to take over the code generator integration with Vertabelo.  See the following [topic](http://support.vertabelo.com/topics/709-take-over-hosting-of-vertabelo-jooq-integration/) on their forums.

Thanks for your quick responses as always, they  are much appreciated.
