### ISSUE TITLE
Unable to connect generated code to a database with different name

### ISSUE THREAD

**Issue by eckyputrady** [jOOQ/jOOQ#5132]
Hi,

I have a scenario as follow where I expect JOOQ has handled but unfortunately it has not handled:

1. Create a database `db1` with any tables
2. Generate code based on `db1`
3. Try doing any queries with jooq, everything should be fine
4. Drop database `db1` and create database `db2` with exactly the same tables
5. Try doing any queries with jooq. The queries will fail. **Expected**: the query should be working.

After digging the generated code, it seems that the database name is hard-coded in `<DatabaseName>.java`?

Thank you

**Comment by ooxi** [comment]
Have a look at [MappedSchema](http://www.jooq.org/javadoc/3.7.x/org/jooq/conf/MappedSchema.html) :-)

**Comment by lukaseder** [comment]
Thank you @ooxi!

@eckyputrady It is *great* that jOOQ gets this right, out of the box. :) (with jOOQ 3.8 and SQL Server, for instance, we even generate the catalog name as well : `[catalog].[schema].[table].[column]`). Who is jOOQ to blindly assume that your (accidentally) identical schemas aren't used in parallel *at the same time* (e.g. for replication purposes, etc.), in case of which full qualification is a necessity.

Do note that in addition to what @ooxi suggested, you can also tell jOOQ not to render any schemas in generated SQL:

```java
new Settings().withRenderSchema(false)
```
