### ISSUE TITLE
Add LoaderXXXStep.fields(FieldMapper) for better mapping between source and target fields

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5145]
The behaviour of `loadRecords()` might be a bit counter intuitive to a user that is used to using jOOQ otherwise. In most situations, when working with records, any mapping is based on column names, not on column indexes. 

The following configuration, however, doesn't work:

```java
create().loadInto(TAuthor())
        .loadRecords(newAuthor(5), newAuthor(6))
        .fields(TAuthor_ID(), TAuthor_LAST_NAME())
        .execute();
```

where...

```java
protected final A newAuthor(int id) {
    A record = create().newRecord(TAuthor());

    record.setValue(TAuthor_ID(), id);
    record.setValue(TAuthor_LAST_NAME(), "XX");

    return record;
}
```

Intuitively, since `ID` and `LAST_NAME` are set on both the record and on the `fields()` specification, the expectation is for these two columns to be inserted. However, what is really done is that the first column in author (as per code generation) is mapped to `ID` and the second column is mapped to `LAST_NAME`.

It should be safe to change this behaviour as it is certainly not what anyone would expect.

**Comment by michael-simons** [comment]
Thanks, Lukas. I fully agree.

**Comment by lukaseder** [comment]
The current Javadoc leaves no doubt about the current behaviour, and it is consistent with other API.

I suspect the fix here will be to create new target `Field` definition methods, which avoid the existing ambiguity. For instance, using lambda expressions:

```java
create().loadInto(TAuthor())
        .loadRecords(newAuthor(5), newAuthor(6))
        .fields((index, field) -> field.getName().equals("ID") 
                   ? TAuthor_ID() 
                   : field.getName().equals("LAST_NAME") 
                   ?  TAuthor_LAST_NAME() 
                   : null)
        .execute();
```
