### ISSUE TITLE
Pull up AttachableInternal.configuration() to Attachable. Remove AttachableInternal

### ISSUE THREAD

**Issue by Centaur** [jOOQ/jOOQ#5149]
Currently the `configuration()` api is defined in an internal api `AttachableInternal`. 

In my case I need to know whether my `Query` has already had a connection attached or not, since this `Query` may come from the dummy `DefaultConfiguration` or a  configuration inside a transaction.

**Comment by lukaseder** [comment]
Thank you for your suggestion. The `Attachable` API stems from jOOQ's legacy, which we're trying to slowly remove in the future. A `Query` should be an immutable object, whereas the `Configuration` is a context that takes a `Query` for execution. Not sure yet, how this will be designed in jOOQ 4.0, but opening up the existing internals would be a move in the wrong direction.

You can, however, access the `AttachableInternal` API already today if you're willing to access the configuration this way.

**Comment by Centaur** [comment]
Thanks for the quick response.  

As for the accessibility, I find it not quite easy. At runtime the query I get is something like `DeleteImpl`, `UpdateImpl`, etc and there seems no obvious way to cast to `AttachableInternal` .

**Comment by lukaseder** [comment]
I understand that this isn't easy, after all, it shouldn't be easy to access internal API (which normally shouldn't be used).

Perhaps, we can look at this from a different angle. Why don't you *know* whether the query is already attached? Is there perhaps a problem with application design, or does jOOQ make application design (with respect to attaching queries) difficult for you?

Do note that you can also always work around this limitation by using `DSLContext.fetch(ResultQuery)` or `DSLContext.execute(Query)`

**Comment by Centaur** [comment]
What I am trying to do is essentially to separate sql composition and query execution. A typical dao method looks like 

```java
Observable<Int> delete(configuration: Configuration = defaultConfiguration) {
    return SqlExecutor.executeAsync(DSL.using(configuration).delete(MYTABLE))
}
``` 

Where `SqlExecutor.executeAsync()` is reponsible for `executing` the composed sql in some thread pool and return the result as a reactive stream.

We need the `configuration` parameter here so that users can call `delete()` alone (where a DefaultConfiguration that only knows the sql dialect is used) or together with other dao method calls in a transaction,   like

```java
Observable<ComposedResult> complexService() {
  return doInTransaction ( configuration ->
       compose(Dao1.delete(configuration), Dao2.update(configuration))  
}) 
```

It is in the implementation of `SqlExecutor.executeAsync()` where I need to know whether the query is already attached or not. If not,  attach it to a newly created `DSLContext` with a connection, otherwise, just execute it immediately since it is already in a transaction.

I am using jooq in vertx, which provides an async/non-blocking environment with a special thread pool dedicated to run blocking code such as jdbc call.  Which means that the codes that invoke the dao methods does not run  on the same thread pool as those in `SqlExecutor.executeAsync()` and those in `doInTransaction`, and only the latter two should know anything about the jdbc connection.

**Comment by lukaseder** [comment]
Hmm, indeed, I think your `SqlExecutor` should run queries with the two methods I suggested. This way, your queries never need to be attached, but always run in a well known but encapsulated context. Does that make any sense?

**Comment by Centaur** [comment]
Did not find `DSLContext.fetch(ResultQuery)` and the other `DSLContext.fetch()` methods do not provide as much type information as the more specific `Query` apis.  Actually I failed to see how using these methods whould help in distinguishing between transactional and non-transactional senarios. 
Anyway, thanks a lot for your patience and suggestions.

**Comment by lukaseder** [comment]
Even if we'll redesign this in jOOQ 4.0, it makes sense to improve the API already now. If we pull up `AttachableInternal.configuration()` to `Attachable`, we can even remove the arcane `AttachableInternal` type.

Removal in a minor release is OK with our backwards compatibility guidelines as it's internal API.
