### ISSUE TITLE
PostgreSQL ARRAY_AGG() with ORDER BY clause

### ISSUE THREAD

**Issue by nsorger** [jOOQ/jOOQ#5172]
There are currently two open issues (#5159 and #5160) regarding PostgreSQL's ARRAY_AGG().

Do these issues also tackle the support for [ORDER BY in ARRAY_AGG expressions](http://www.postgresql.org/docs/current/static/sql-expressions.html#SYNTAX-AGGREGATES)?

If not I'd like to suggest a new feature to support ORDER BY in ARRAY_AGG expressions like the following code naively does:

```java
    @Support({ POSTGRES })
    public static <T> Field<T[]> arrayAgg(final Field<T> field, final WindowSpecificationOrderByStep orderByPart) {
        return field("array_agg({0} {1})", field.getDataType().getArrayType(), field, orderByPart);
    }
```

**Comment by lukaseder** [comment]
Thank you very much for your feedback. Those issues are in fact the same issue. We maintain "merge" issues to remind ourselves of merging a fix to a previous minor release stream. Unfortunately, there's no way to specify several milestones on a GitHub issue.

You can already use `ORDER BY` with `ARRAY_AGG()` in jOOQ:

```java
DSL.arrayAgg(TAB.A).orderBy(TAB.B)
```

Hope this helps.
