### ISSUE TITLE
Add support for Amazon Aurora MySQL Edition

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5196]
See: https://aws.amazon.com/rds/aurora/details/?nc1=h_ls

**Comment by neilebliss** [comment]
I take it from this that attempting to use jooq with an aurora db will not work at this point?

**Comment by lukaseder** [comment]
It might work with some dialect and with very simple queries, but it probably doesn't work in many edge cases. Currently, there's no official support, indeed.

**Comment by Mikiewitch** [comment]
Any progress with this feature?

**Comment by lukaseder** [comment]
Yes, we're scheduling this for 3.11 (due by early 2018) but haven't started investigating yet.

**Comment by okrasz** [comment]
Will Aurora support be part of the open source edition or commercial?

**Comment by lukaseder** [comment]
@okrasz It'll be part of the jOOQ Professional Edition, just like Amazon Redshift - which is a comparable dialect: https://www.jooq.org/legal/licensing#databases

**Comment by lukaseder** [comment]
Implementing support for this in the jOOQ Professional Edition 3.11. This issue will add support for Amazon Aurora MySQL Edition. The PostgreSQL Edition will be supported through #7433, also in the jOOQ Professional Edition 3.11
