### ISSUE TITLE
Add support for PostgreSQL's EXCLUDED table

### ISSUE THREAD

**Issue by testark** [jOOQ/jOOQ#5214]
PostgreSQL introduced a "special" `EXCLUDED` table to be used on `INSERT INTO ... ON CONFLICT (...) DO UPDATE ...` statements. It would be great if jOOQ could provide a "placeholder" for this special table.

---

See also:
- http://www.postgresql.org/docs/9.5/static/sql-insert.html

**Comment by lukaseder** [comment]
Interesting feature, thanks for the hint. Reminds me of the `INSERTED`, `UPDATED`, `DELETED` "magic" tables in Oracle triggers or in SQL Server `OUTPUT` clauses.

The easiest way to get this already today might be by using simple aliasing, where you alias the table inserted into as `TABLE.as("excluded")`

**Comment by sharatvisweswara** [comment]
Hi Luka, thanks for all your great work on Jooq. Just a note for anyone else who ends up here that the `TABLE.as("excluded")` hack does not work unless you also use `Settings.withRenderNameStyle(RenderNameStyle.AS_IS)` when creating the DSLContext. By default, quoting the `EXCLUDED` keyword makes PostgresQL look for a corresponding `FROM` clause and fail the insert.

**Comment by lukaseder** [comment]
Thanks for your comment, @sharatvisweswara. Are you sure, though? The following code works:

```sql
CREATE TABLE x (i INT PRIMARY KEY, j INT);

INSERT INTO x VALUES (1, 1)
ON CONFLICT (i)
DO UPDATE SET j = "excluded".j
RETURNING *;
```

The pseudo-table is really called `"excluded"` (in lower case letters), as I've described in my example. It is not a keyword, and in order to make my suggestion work, you indeed need wo write the alias in lower case or disable quoting as you suggested.

Note also: jOOQ 3.10 will introduce new ways to create a `org.jooq.Name` through `DSL.unquotedName()`, which will always be unquoted, regardless of `Settings.renderNameStyle`

**Comment by xathien** [comment]
Since this is still floating around `Long-term goals and ideas`... would it be possible to make `.set(someRecord).onDuplicateKeyUpdate().execute()` automatically use the `excluded` table? Right now it generates syntactically valid SQL, but it uses the default table name, which causes the query to update nothing. 🙂

**Comment by lukaseder** [comment]
@xathien Would you mind creating a new issue for that with some details / examples? I think your issue isn't strictly related to this feature request.

**Comment by xathien** [comment]
You're right, it's not strictly related--I'll file a new issue.

**Comment by knutwannheden** [comment]
This is also relevant for SQLite which now also supports the INSERT ON CONFLICT clause of Postgres.

**Comment by lukaseder** [comment]
Good point, @knutwannheden. I've been working on an emulation of `RETURNING` via SQL Server's `OUTPUT` clause, which has syntactically similar pseudo tables called `DELETED` and `INSERTED` (#4498). To support such syntactic constructs, a new internal (or public?) API will be needed that takes a set of `SelectFieldOrAsterisk` and re-qualifies them under a new table name.

So, this new feature can be useful in this `EXCLUDED` case as well.

**Comment by abonander** [comment]
Shouldn't very basic support for Postgres simply consist of generating an extra `EXCLUDED` field on table classes that's just initialized with `new MyTable(DSL.name("EXCLUDED"), null)`?

**Comment by lukaseder** [comment]
@abonander Thanks for your suggestion. I have some reservations here.

1. I would personally find that confusing, as you'd be writing `MY_TABLE.EXCLUDED.COLUMN_NAME` when using jOOQ, and that looks like a nested record.
2. (less important), there might be conflicts with actual columns called `EXCLUDED`, which we can handle, but they would be annoying.
3. The feature is relatively arcane, I don't think it deserves such a big presence on *every* generated table. You could obviously do this in your own version of the code generator, by implementing `JavaGenerator::generateTableClassFooter`, though.

**Comment by lukaseder** [comment]
Notice, we have an internal utility called `Tools::qualify`, which does exactly what's needed here, and it would work for all RDBMS, including also SQL Server, which has similar tables, or future trigger support, when we want to dereference columns from a trigger pseudo table like `:NEW` or `:OLD`. This utility will also work with non-generated code, so it will be a more thorough solution.

By the way, there's already a generated `rename(String)` method on all generated tables, that produces the wanted table reference...

**Comment by dsvensson** [comment]
It would be nice if `rename(String)` was part of some public interface rather than declared on `TableImpl` so that generic code could perform the `tbl.rename("EXCLUDED")` part.

**Comment by lukaseder** [comment]
@dsvensson Yes indeed, that would be nice: https://github.com/jOOQ/jOOQ/issues/5242

**Comment by monosoul** [comment]
A simple Kotlin extension function to turn any table field into an excluded field:

```kotlin
import org.jooq.Field
import org.jooq.Record
import org.jooq.TableField
import org.jooq.impl.DSL

fun <R : Record, T> TableField<R, T>.asExcluded(): Field<T> = DSL.field("EXCLUDED.$name", dataType)
```

And then just call it as `MY_TABLE.COLUMN_NAME.asExcluded()`

**Comment by lukaseder** [comment]
A native implementation has been added. Will try to emulate it, too, for dialects that support only `MERGE`, then tackle this auto-excluded syntax: https://github.com/jOOQ/jOOQ/issues/7912

**Comment by lukaseder** [comment]
Emulation will be done in a separate task: https://github.com/jOOQ/jOOQ/issues/13571

**Comment by lukaseder** [comment]
As mentioned here: https://github.com/jOOQ/jOOQ/issues/12099 and here https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html, the `VALUES(x)` syntax is deprecated in MySQL. Starting from 8.0.20, instead of:

```sql
INSERT INTO t1 (a,b,c) VALUES (1,2,3),(4,5,6)
  ON DUPLICATE KEY UPDATE c=VALUES(a)+VALUES(b);
```

We should generate

```sql
INSERT INTO t1 (a,b,c) VALUES (1,2,3),(4,5,6) AS new
  ON DUPLICATE KEY UPDATE c = new.a+new.b;
```

**Comment by lukaseder** [comment]
MariaDB didn't follow suit here. I couldn't find a feature request for this new syntax, and probably, they're not doing it.

**Comment by lukaseder** [comment]
Jesus...

![image](https://user-images.githubusercontent.com/734593/168996986-4d82678e-a3b3-4a58-8eda-8d5770495c8e.png)

**Comment by lukaseder** [comment]
Of course, the new MySQL syntax only works with `INSERT .. VALUES`, not with `INSERT .. SELECT`, in case of which I guess we'll have to wrap the `SELECT` query in a derived table and name it explicitly.

**Comment by lukaseder** [comment]
Emulations now work correctly. Parser support will be implemented separately: https://github.com/jOOQ/jOOQ/issues/13573

**Comment by lukaseder** [comment]
Another issue will cover more "advanced" emulation use-cases where the column isn't located at the top level of the `SET` clause: https://github.com/jOOQ/jOOQ/issues/13575
