### ISSUE TITLE
Add support for FOR SHARE OF in Postgres dialect

### ISSUE THREAD

**Issue by kbalyasnikov** [jOOQ/jOOQ#5218]
At the moment there is no support for this syntax in jOOQ. The syntax is same as for FOR UPDATE and described in [official documentation](http://www.postgresql.org/docs/current/static/sql-select.html#SQL-FOR-UPDATE-SHARE).

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. That certainly makes sense. For the time being, this can be emulated by using `FOR UPDATE` instead, and replacing the `FOR UPDATE` clause in the generated SQL string by `FOR SHARE` via a `ExecuteListener.renderEnd()` event

**Comment by kbalyasnikov** [comment]
@lukaseder, thanks for accepting suggestion!

**Comment by knutwannheden** [comment]
I may be missing something, but `SelectForUpdateStep` has had a `forShare()` method for a very long time already (oldest Git revision has it as well: https://github.com/jOOQ/jOOQ/blob/5666cfd019b650f117d61672de7cd366e024befc/jOOQ/src/main/java/org/jooq/SelectForUpdateStep.java).

However, I noticed that the method doesn't return `SelectForUpdateOfStep` as for example `forUpdate()` does. As a result the `FOR SHARE` clause doesn't allow the `NOWAIT` option. This is wrong and should be corrected and we could do that in the scope of this issue.

**Comment by knutwannheden** [comment]
I probably missed the `OF` in the issue title. That would also be resolved by changing the return type of `forShare()` as described.

**Comment by knutwannheden** [comment]
OK, wasn't quite as trivial as I thought. The `SelectQuery` API is rather different here and would require the addition of a set of `setForShareOf()` methods as well as `setForShareWait()` and `setForShareNoWait()` methods and even a `setForShareSkipLocked()` method.

**Comment by knutwannheden** [comment]
The DSL API has been changed as proposed and the `SelectQuery` now also supports specifying the `OF` and `WAIT | NOWAIT | SKIP LOCKED` clauses for all lock modes. Whether a given combination of lock mode and flags makes sense, depends on the SQL dialect.
