### ISSUE TITLE
ALTER TABLE .. RENAME CONSTRAINT .. doesn't work for H2

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5224]
H2 can only rename indexes, not constraints.

Feature request pending:
https://groups.google.com/forum/#!topic/h2-database/ASdGeMfcC5k

**Comment by knutwannheden** [comment]
AFAICT this has been addressed in H2 long ago (see https://github.com/h2database/h2database/commit/1eb9a748b8d2e8685996c19eba92249fb998b715) and should also work well in jOOQ.

**Comment by lukaseder** [comment]
@knutwannheden Thanks for digging this up. All the better! :)
