### ISSUE TITLE
Manual section showing jOOQ+JPA usage should take into account Binding and Converter

### ISSUE THREAD

**Issue by gabadi** [jOOQ/jOOQ#5243]
I had some issues with the documentation that i've already solved.
The issue is in [this page](http://www.jooq.org/doc/3.8/manual/sql-execution/alternative-execution-models/using-jooq-with-jpa/using-jooq-with-jpa-entityresult/):

There gives this binding example:

```
public static <E> List<E> nativeQuery(EntityManager em, org.jooq.Query query, String resultSetMapping) {

    // Extract the SQL statement from the jOOQ query:
    Query result = em.createNativeQuery(query.getSQL(), resultSetMapping);

    // Extract the bind values from the jOOQ query:
    List<Object> values = query.getBindValues();
    for (int i = 0; i < values.size(); i++) {
        result.setParameter(i + 1, values.get(i));
    }

    return result.getResultList();
}
```

And the issue is that when i've some kind of convertion in that field, the binded parameter isn't converted.

I've used this instead:

```
public static <E> List<E> nativeQuery(EntityManager em, org.jooq.Query query, String resultSetMapping) {

    // Extract the SQL statement from the jOOQ query:
    Query result = em.createNativeQuery(query.getSQL(), resultSetMapping);

    // Extract the bind values from the jOOQ query:
        query.getParams()
                .forEach((k, v) -> 
                        result.setParameter(
                                Integer.valueOf(k) - 1,
                                ((Converter)v.getBinding().converter()).to(v.getValue())
                        )
                );

    return result.getResultList();
}
```

Thanks

**Comment by lukaseder** [comment]
Thank you very much for pointing this out. You're right, in the event of using bindings / converters, extra steps need to be taken to apply the binding / converter also to JPA. Strictly speaking, bindings aren't really supported here, as they can bind only to JDBC. But converters will work.

We'll add a fix to the manual ASAP.

**Comment by gabadi** [comment]
Perfect! Thanks for your work
