### ISSUE TITLE
code geration from .sql

### ISSUE THREAD

**Issue by FallenRiteMonk** [jOOQ/jOOQ#5269]
Is it possible possible to generate all the schema files from sql script?

This would be very useful for me since I have my database running in a docker (mariadb docker container) and I have a sql script which generates all my database tables on startup, so at the moment I have to start my docker container to generate my JOOQ schema files, but if it would be possible to generate those form a sql script, I could just specify the same script as I have for my docker container.

**Comment by lukaseder** [comment]
Thank you very much for your message. jOOQ's code generator doesn't ship with a SQL parser for all the 21 RDBMS that are currently supported - it would be much too buggy. But I'd recommend installing the SQL script on an actual database instance prior to running code generation. This can be done with:

- The sql-maven-plugin
- Flyway
- Any other SQL execution utility

We generally recommend using Flyway. Here's a blog post showing how to hook Flyway together with jOOQ in Maven builds:

https://blog.jooq.org/2014/06/25/flyway-and-jooq-for-unbeatable-sql-development-productivity/

Hope this helps. If you have any additional questions, just ask.
