### ISSUE TITLE
In the doc, part " 4.4.2. The CREATE statement " add a "nullable(false)" example

### ISSUE THREAD

**Issue by cluelessjoe** [jOOQ/jOOQ#5289]
Hi

I had to look around to figure out how to add a non null constraint, which turned out to be "nullable(false)" called on the dataType itself.

An example of it in the Part 4.4.2 The CREATE statement would have helped a lot, so maybe... ^^

Thanks again a lot for JooQ, it rocks :)

++

**Comment by lukaseder** [comment]
Thank you for your suggestion and for your nice words.

Indeed, I thought myself the other day that the DDL section of the manual does deserve some more details :) Will do, soon!

**Comment by cluelessjoe** [comment]
Thx a lot. Let me know if I can help in any way :)

**Comment by lukaseder** [comment]
Are you willing to contribute to the manual? Unfortunately, we still don't have it open sourced, but that could be a good moment to actually do it...

**Comment by cluelessjoe** [comment]
Well, I would love to be able to offer some PR on the matter :) Way better than just asking for something isn't it ?

**Comment by lukaseder** [comment]
It is an excellent idea :)

Sorry for the delay in this. I've now finally implemented https://github.com/jOOQ/jOOQ/issues/3358, which means the manual's source XML files are now on GitHub. If you're still interested in providing content, may I please ask you to:

1. Read this document and sign the transfer of rights agreement: https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md
2. Send a PR on this file: https://github.com/jOOQ/jOOQ/blob/master/jOOQ-manual/src/main/resources/org/jooq/web/manual-3.8.xml (I'll merge to the appropriate older versions, then)

**Comment by cluelessjoe** [comment]
I didn't forget you, I have something to finish first and then back to you :)

but really nice and sweet!

**Comment by lukaseder** [comment]
Sure no worries. DDL statements have been around and poorly documented for a while now, so we're not in a hurry :)

**Comment by cluelessjoe** [comment]
I did it directly in the file, and I'll start again my hunt to have someone in my company provide the "Corporate Contributor Information"...

**Comment by lukaseder** [comment]
OK, thank you very much for the hint, and the contributions so far. I'll be on vacation for the next weeks, I'll look into the improvements afterwards, once the legal stuff is done.

**Comment by cluelessjoe** [comment]
Well, I managed to get someone in my company to confirm I'm free to contribute and thus I filled the transfer of rights agreement :) Crazy stuff ;) 

++

**Comment by lukaseder** [comment]
Thank you very much, and thanks for taking this seriously. Yes, it's crazy... You can imagine now how much of a legal mess Open Source is in general. Few people / libraries get this right. Imagine a significant jQuery or Spring contribution was actually "illegal"...

Thanks again for your PRs. I'll merge them now!
