### ISSUE TITLE
Avoid parsing ? in plain SQL if followed immediately by another operator-like character in PostgreSQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5307]
PostgreSQL has some funky operators, some of which contain `?`, which is currently parsed by jOOQ as a bind variable marker in plain SQL `QueryParts`:
https://www.postgresql.org/docs/9.5/static/functions-json.html

**Comment by stickfigure** [comment]
This doesn't seem to fully work, or at least there's some sort of edge case that I'm hitting that produces the same error:

http://stackoverflow.com/questions/38340086/how-to-use-postgres-json-operators-in-a-where-condition-with-jooq

**Comment by lukaseder** [comment]
Thanks for the hint. I've indeed only fixed jOOQ's parser in order not to inline any bind variables at the wrong positions. There's also a JDBC bug / limitation, which [I've documented in a separate question](http://stackoverflow.com/q/38370972/521799)

**Comment by stickfigure** [comment]
Ah hah! Thanks, that answers everything.
