### ISSUE TITLE
Log a warning in the code generator if a table is reported to have two identity columns - Merge [#5335]

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5338]

**Comment by alvinjayreyes** [comment]
Hi Lukas.

We can create another method in the AbstractTableDefinition to get all identities for a specific table. This will allow the JavaGenerator to 1) return a list of Identitiy definition for a specific table and 2) to check if there are multiple identities. We can then use this to log the warning on the code generator.

The definition of the method doesn't have to be on the interface level. We can introduce is on Abstract class.

**Comment by alvinjayreyes** [comment]
Add the following on TableDefinition.java
```

    /**
     * Get the identities for this table.
     */
    List<IdentityDefinition> getIdentities();
```

Implement it on the AbstractTableDefinition.java

    ```
@Override
    public final List<IdentityDefinition> getIdentities() {
    	List<IdentityDefinition> identities = new ArrayList<IdentityDefinition>();
        for (ColumnDefinition column : getColumns()) {
            if (column.isIdentity()) {
            	identities.add(new DefaultIdentityDefinition(column));
            }
        }
    	return identities;
    }
```

Log warning on JavaGenerator.java

            ```
	//	Log a warning if there are multiple identities on the table.
            	if(table.getIdentities().size() > 1) {
            		log.warn("Multiple Identitiy definitions found on table " + table.getName());
            	}
```

**Comment by lukaseder** [comment]
Thanks for your suggestion, @alvin-reyes. I don't agree, though. I'm not aware of a database that allows multiple identities per table. Here's the definition from the SQL:2011 standard:

> 4.15.11 Identity columns
> 
> The columns of a base table BT can optionally include *not more than one* identity column. [...]

so I don't think that adding this as public API would be reasonable.

More information about this issue can be found in its parent issue here: https://github.com/jOOQ/jOOQ/issues/5335
