### ISSUE TITLE
Add XMLGenerator to produce an XML file containing meta information according to jooq-meta.xsd

### ISSUE THREAD

**Issue by jdevera** [jOOQ/jOOQ#5347]
Since jOOQ supports an XML file describing the schema of a database as a replacement for a database connection, it would be extremely handy to have the option to generate this file somehow from an existing database, so that one can run jOOQ multiple times afterwards without access to the DB and obtain the same generated code.

It could either be a special call to generate only this file or it could be a by-product of the regular code generation.

**Comment by lukaseder** [comment]
Excellent idea. In fact, that was the original plan. But I cannot seem to find any relevant issue for this on GitHub, which is probably why it was forgotten in the end.

**Comment by robrez** [comment]
+1

**Comment by lukaseder** [comment]
Done. Your early feedback is very welcome. There are probably some bugs and edge cases that I haven't thought of, specifically related to data types.

**Comment by lukaseder** [comment]
In order to use the new generator, just specify:

```xml
<generator>
    <name>org.jooq.util.XMLGenerator</name>
    ...
</generator>
```

The rest of the configuration stays the same (where applicable)

**Comment by robrez** [comment]
Thanks for the quick work! Will try it out.

For future reference, in-case someone stumbles upon this issue, we are referencing this part of the docs (6.23 in v3.8):
http://www.jooq.org/doc/3.8/manual/code-generation/codegen-xml/

**Comment by robrez** [comment]
Got around to testing this today, worked like a charm!

Out of curiosity, would you be opposed to some configuration allowing to output separate schema files per-table or schema?

**Comment by lukaseder** [comment]
@robrez Thanks for your feedback! Greatly appreciated.

Interesting idea, would you mind elaborating a bit on your use-case? Also, would you perhaps find the existing `<includes/>` and `<excludes/>` functionality to be suitable for this?

**Comment by robrez** [comment]
@lukaseder Absolutely, a custom postprocessor using XSLT, stax or sax would work fine. I was just noticing how well the current control structures in XMLGenerator could lend themselves to writing multiple output files.

My use case may be a bit odd - but, we currently generate xml metadata using an inhouse tool (inferior to jooq). We have extended the meta-model beyond just what exists in the database/dbmetadata/stmtmetadata to build out a data-dictionary of sorts which includes descriptions and some other stuff. We currently store all of that in an xml file per-table. We use the xml files to generate different things including some c code, some reports, data-dictionary tables, etc.

My goal is to separate our proprietary meta-model into separate xml files and pairing those files with your generated xml as needed.

**Comment by lukaseder** [comment]
> I was just noticing how well the current control structures in XMLGenerator could lend themselves to writing multiple output files.

Oh, I see. Yes indeed, it could, but I'm a bit reluctant of adding too many features for which there is an existing and not too painful workaround. Feature creep is dangerous for maintainers :)

For instance: Should foreign keys still be listed in per-table split files (when the referenced table is in another file) or not?

> My goal is to separate our proprietary meta-model into separate xml files and pairing those files with your generated xml as needed.

Hmm, as far as that is concerned, I think an XSLT / XPath based solution could easily work on the existing jOOQ XML format without the need to split things.
