### ISSUE TITLE
how to write mysql CONVERT expression

### ISSUE THREAD

**Issue by pandaxba** [jOOQ/jOOQ#5348]
anyone can help me?
how can i write this sql by jooq dsl?
```
select * from tb order by CONVERT( `name` USING gbk ) asc;
```

**Comment by lukaseder** [comment]
Thanks a lot for your enquiry. If ever jOOQ is missing some vendor-specific functionality, "plain SQL" will be the answer:
http://www.jooq.org/doc/latest/manual/sql-building/plain-sql

In your case, write:

```java
DSL.field("convert({0} USING gbk)", tb.NAME);
```

And supply that to the `orderBy()` clause.

Hope this helps,
Lukas
