### ISSUE TITLE
@Nullable and @NonNull annotations

### ISSUE THREAD

**Issue by ntrrgc** [jOOQ/jOOQ#5353]
It would be very useful if jOOQ code (both library and codebase) used `@Nullable` and `@NonNull` annotations, as it would help many tools (including languages like Kotlin!) to warn of potential null pointer dereferences.

After seeing https://blog.jooq.org/2016/05/09/jsr-308-and-the-checker-framework-add-even-more-typesafety-to-jooq-3-9/ I hoped to see it implemented in `master`, but I was wrong.

Are there any plans to introduce these useful annotations?

**Comment by lukaseder** [comment]
Heh, yeah, which ones to support, that's the question... :) Currently, jOOQ supports JSR-303 bean validation annotations in the code generator. You can turn that on by specifying the appropriate flag:

```xml
 <!-- Annotate POJOs and Records with JSR-303 validation annotations
       Defaults to false -->
  <validationAnnotations>false</validationAnnotations>
```

What particular annotations / JSRs / libraries did you have in mind?

**Comment by ntrrgc** [comment]
Good question... I actually stumbled on this question short after posting this:

http://stackoverflow.com/questions/4963300/which-notnull-java-annotation-should-i-use

It does not look good at all. 

[Java 8 adds `@NonNull`](https://blogs.oracle.com/java-platform-group/entry/java_8_s_new_type), but doesn't add a `@Nullable` annotation, which looks more important: you want to be warned of what could crash, not of what is harmless. Should tools assume that everything `@NotNull` is `@Nullable`? Unlikely. I could not find rules anywhere on how that annotation or the lack thereof should be interpreted.

JetBrains annotations look simple and useful and are supported at least in Kotlin, IntelliJ and Eclipse. They are very explicit since there is no default. `@NotNull` just means that thing (return value, parameter, property) can't be null and `@Nullable` means they can.

Here is an example of an annotated class:

```java
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public class AnnotationsDemo {
    @Nullable
    Integer explicitlyNullable(@Nullable Integer a) {
        return null;
    }

    @NotNull
    Integer explicitlyNotNullable(@NotNull Integer a) {
        return a + 2;
    }

    Integer withoutAnnotation(Integer a) {
        return a + 3;
    }
}
```

![](http://i.imgur.com/K27m18E.png)

You can see in the autocomplete box that nullable types contain a `?` (Kotlin for nullable), non nullable types contain no marks (Kotlin for non nullable) and unannotated types contain `!` (Kotlin for «I don't know, it's your problem. Maybe fine.»)

Explicitly annotating everything is nice for the consumer, though may be too verbose to be done in practice at times, especially for method parameters. There are some annotations to provide defaults, such as this https://www.jetbrains.com/help/idea/2016.1/parametersarenonnullbydefault-annotation.html#ParametersAreNonnullByDefault though they have their own problems (additional libraries, came from retired JEPs, not supported in Kotlin...)

IntelliJ has a feature that scans Java code to add annotations (*Analyze/Infer Nullity*) which can make the process quite faster.

Eclipse also has its own package for declaring nullity which includes an annotation for defaults (which is a bit complex since it can be overridden by another default). http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftask-using_null_annotations.htm I don't know to what degree it's supported by languages and tools.

At this moment my bet would be on the JetBrains package. It's easy, explicit and well supported.

**Comment by lukaseder** [comment]
> It does not look good at all.

Yeah, what a mess, right? :)

> At this moment my bet would be on the JetBrains package. It's easy, explicit and well supported.

And mine would be firmly against that package, but in favour of JSR 305. Oh crap, I meant 303. Or 308? Damnit... :)

I'm going to close this as won't fix. jOOQ 4.0 foresees a lot of additional code generation hooks that allow for these extensions, such that users will be able to do whatever they want and easily so, unlike in jOOQ 3.x, where most such changes require patching the `JavaGenerator`.

Right now, my only suggestion for you is to do precisely that: Patch the `JavaGenerator`

**Comment by lukaseder** [comment]
For the record, in the meantime, I have changed my mind (mostly because of Kotlin's high adoption rate), and implemented this via https://github.com/jOOQ/jOOQ/issues/6244
