### ISSUE TITLE
Incorrect order of HSQL column definition tokens: "DEFAULT" and "NULL"

### ISSUE THREAD

**Issue by evbo** [jOOQ/jOOQ#5356]
Jooq>=3.8.0 code-generates create table statements similar to the following for HSQLdb:

`create table schema_name.table_name(col_name varchar(255) not null default NULL, ...)`

But for HSQLdb, the order in the column definition needs to be:

`create table schema_name.table_name(col_name varchar(255) default NULL not null, ...)`

**_Temporary Work Around:_**
The only work-around-solution I could find was to listen to the context and interrupt the generated SQL, removing the incorrect placement of "default NULL" statements.

See this posting for further details on the background of this issue: https://groups.google.com/forum/#!topic/jooq-user/M5OpjPezPp4

**Comment by lukaseder** [comment]
Absolutely. Thanks for reporting.

In fact, there are a few other DDL related integration tests currently failing for HSQLDB. Will look into fixing these during the next days.

**Comment by lukaseder** [comment]
This fix will be merged to 3.8.3 (https://github.com/jOOQ/jOOQ/issues/5359)
