### ISSUE TITLE
Add ResultQuery.fetchStreamInto()

### ISSUE THREAD

**Issue by jasonfry89** [jOOQ/jOOQ#5361]
When using `.selectFrom` combined with `.fetchStream`, returned is `Stream<MyRecord>`. When I cannot use `.selectFrom` (e.g. I have to perform a join), I'm not sure how to get a `Stream<MyRecord>` without calling `.fetchInto`, which (if my understanding is correct) performs an eager fetch of all records in the result set. 

Assuming that the above is correct, could a `.fetchStreamInto` method be created?

**Comment by lukaseder** [comment]
Indeed, there are currently quite a few convenience methods missing when fetching streams. The idea is that `Stream.map()` makes all those convenience methods rather easy to implement at the client side, when operating directly on individual records. For instance, you could write:

```java
Stream<MyTableRecord> stream = 
    select(...)
    .from(...)
    .fetchStream()
    .map(r -> r.into(MY_TABLE));
```

However, we'll look into this. There are probably some cases, where a convenience method would help users get the job done more quickly.
