### ISSUE TITLE
Add support for ALTER TABLE .. ADD CONSTRAINT .. USING INDEX (...)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5418]
In Oracle, it is possible to specify an inline `CREATE INDEX` statement too:

```sql
ALTER TABLE t ADD CONSTRAINT u UNIQUE (c) USING INDEX i;
```

Some other databases support this as well, e.g. PostgreSQL (although, in PostgreSQL, the column set cannot be respecified)

**Comment by knutwannheden** [comment]
Just came across this one, as it doesn't support PostgreSQL and in fact `usingIndex()` is only available in the commercial editions. I don't see how the DSL allows respecifying the column list, so my understanding is that we should be able to add PostgreSQL support. Should I open a ticket for this?

**Comment by lukaseder** [comment]
Yes, please open a ticket for this, we can open up the API and the PostgreSQL specific parts of the implementation to the OSS edition.

Note that Oracle supports both syntaxes:

- Referencing an existing index by name
- Referencing a create index statement of a not-yet-existing index (`USING INDEX (CREATE INDEX ...)`)

![image](https://user-images.githubusercontent.com/734593/57758993-3d5dc300-76f9-11e9-973c-1ead2d39a176.png)
