### ISSUE TITLE
Make some private methods protected in DefaultGeneratorStrategy

### ISSUE THREAD

**Issue by er1c** [jOOQ/jOOQ#5420]
I was adding a custom namer for my scala-generated classes & wanted to drop the "get" prefix.

First pass I thought I was going to do something like:

```
class JOOQGeneratorStrategy extends DefaultGeneratorStrategy {
  override def getJavaGetterName(definition: Definition, mode: Mode): String = {
    /*return "get" + */getJavaClassName0(definition, Mode.DEFAULT)
  }
}
```

But the getJavaClassName0 helpers are all flagged as private.  Can we mark these as protected instead of private for more easily implementing specific overrides?

https://github.com/jOOQ/jOOQ/blob/6c7d9cf98be07f53d3ea68b6231aefeaabcf8de4/jOOQ-codegen/src/main/java/org/jooq/util/DefaultGeneratorStrategy.java#L56-L58
https://github.com/jOOQ/jOOQ/blob/6c7d9cf98be07f53d3ea68b6231aefeaabcf8de4/jOOQ-codegen/src/main/java/org/jooq/util/DefaultGeneratorStrategy.java#L197
https://github.com/jOOQ/jOOQ/blob/6c7d9cf98be07f53d3ea68b6231aefeaabcf8de4/jOOQ-codegen/src/main/java/org/jooq/util/DefaultGeneratorStrategy.java#L202
https://github.com/jOOQ/jOOQ/blob/6c7d9cf98be07f53d3ea68b6231aefeaabcf8de4/jOOQ-codegen/src/main/java/org/jooq/util/DefaultGeneratorStrategy.java#L226

**Comment by lukaseder** [comment]
Thank you very much for your suggestion.

When the question is "can we make these private methods protected/public", then the answer is usually: "there's probably a better way" :) Keeping as many things private as possible is a key feature of the jOOQ API. We can freely improve things without breaking anything in client code. Making something as specific as the `getSubPackage()` method protected/public would lead to many regrets later on.

In this particular case, you should be able to access the super implementation of `getJavaGetterName()` directly, no? E.g.

```scala
  abstract override def getJavaGetterName(definition: Definition, mode: Mode): String = {
    return "get" + super.getJavaClassName(definition, Mode.DEFAULT)
  }
```

I'm sure there are other ways to reach the other things that you have in mind. Perhaps, if you're willing to discuss your specific use-case, we can find solutions (and possibly feature requests) together?
