### ISSUE TITLE
ScalaGenerator should follow Scala Style Guide in generated code

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5422]
Currently, the ScalaGenerator generates:

``` scala
identifier : Type = value
```

When it should generate:

``` scala
identifier: Type = value
```

All improvements:

- [x] Avoid whitespace before `:`
- [x] Avoid `return` where possible
- [x] Use expression method bodies `def x(): T = expr` (single line) rather than `def x(): T = { expr }` (multi line)

----
See:
- http://docs.scala-lang.org/style/naming-conventions.html#values_variable_and_methods
- A fix is suggested in this PR: https://github.com/jOOQ/jOOQ/pull/5421, commit https://github.com/jOOQ/jOOQ/pull/5421/commits/ca3e0b371bbb44f1555478046a6926e40c422ce2

**Comment by lukaseder** [comment]
Implemented with https://github.com/jOOQ/jOOQ/pull/5421.

This change is too minor compared to the lines of code adapted. We'll thus not merge this to jOOQ 3.8.x

**Comment by lukaseder** [comment]
Hmm... This seems to introduce regressions related to the disambiguations put in place by jOOQ when adding suffixes. For instance, the following is illegal scala code:

```scala
def getClass_: Integer = { ... }
```

**Comment by er1c** [comment]
Just so this note is somewhere, it occurred to me, this can be fixed in scala by wrapping the identifier in backticks if the last character is an underscore `_` 

```
scala> def getClass_: String = "foo"
<console>:1: error: '=' expected but identifier found.
def getClass_: String = "foo

scala> def `getClass_`: String = "foo"
getClass_: String
```

I'll try submitting a more complete PR that includes the proper SCALA escaping of the identifier - maybe we can move this back from the "wontfix" bucket with a little bit more work.

**Comment by er1c** [comment]
I fucked with this for probably more than I should have today, but I think it's coming together fine: https://github.com/jOOQ/jOOQ/pull/5431

**Comment by lukaseder** [comment]
> this can be fixed in scala by wrapping the identifier in backticks if the last character is an underscore _

Interesting. But this doesn't mean that the call site will need to quote the identifier too, right?

**Comment by er1c** [comment]
@lukaseder Correct, the call site does not need to escape the identifier....unless the identifier had whitespace characters in it...you could technically do:

```
object FooBar {
  def `foo and bar`: String = "foo and bar"
}

FooBar.`foo and bar`
```

Will yield "foo and bar"

**Comment by lukaseder** [comment]
Fixing this now in the context of #10191
