### ISSUE TITLE
Don't escape Scala-style setter names produced by naming strategies in ScalaGenerator

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5424]
It is perfectly fine to have methods named `/` or `a_=` in Scala. The latter is a setter naming convention (see #5421). This is currently not possible in jOOQ, as these special characters (which aren't allowed in Java) are escaped by jOOQ.

This escaping should not happen in Scala.

----
Originally reported by @er1c here: https://twitter.com/ericpeters/status/755088676959293441

See also: https://github.com/jOOQ/jOOQ/pull/5421

**Comment by lukaseder** [comment]
@er1c, the problematic logic is here:
https://github.com/jOOQ/jOOQ/blob/11115c674127bed3d9c40b6d10b0dfa33d94398a/jOOQ-codegen/src/main/java/org/jooq/util/GenerationUtil.java#L184

There's an easy way to add a conditional that runs only in the Scala case. The hard part is to decide when we need to escape stuff. Perhaps, we just simply don't escape anything at all in Scala?

**Comment by er1c** [comment]
@lukaseder  In theory the escaping is more technically "correct" than not - if you had a table (from I don't know whose database - that had a ":" or "_=" as part of the name then those should be escaped.  From a practical standpoint, doing that escaping limits your ability to generate the appropriate get/setter methods like the issue described above. 


I'd suggest either:

1. Define the interface convertToIdentifier in AbstractGeneratorStrategy (https://github.com/jOOQ/jOOQ/blob/master/jOOQ-codegen/src/main/java/org/jooq/util/AbstractGeneratorStrategy.java) & change references in the GeneratorStrategyWrapper.java (https://github.com/jOOQ/jOOQ/blob/master/jOOQ-codegen/src/main/java/org/jooq/util/GeneratorStrategyWrapper.java) to use that implementation; or

2. Make "escaping" an option to turn off as part of  the AbstractGeneratorStrategy - as an indication that all of the implemented getJavaGetterName/getJavaSetterName/etc are "responsible" for doing their own escaping

To be clear, I'd be fine with turning it off for the entire scala language, it would help my immediate need a lot :)

But I don't know if anyone that is currently using your scala generator is relying on some of the escaping logic for their DBMSes with weird column/table names/etc.

**Comment by lukaseder** [comment]
Unfortunately, it's not as simple as we might wish. What about a table named `"first-name"`?

I think the simplest solution to enable your particular use-case is to not escape the `=` sign when it is the last character of an identifier, when generating Scala code. As we encounter more of these symbolic method name use-cases, we can try to find a more thorough solution. I'd rather not open [this can of worms](http://stackoverflow.com/a/7657692/521799) entirely right now :)

**Comment by lukaseder** [comment]
There. The following generator strategy now works correctly for `Record` types:

```java
public class ScalaGetterSetterStrategy extends DefaultGeneratorStrategy {

    @Override
    public String getJavaSetterName(Definition definition, Mode mode) {
        if (mode == Mode.RECORD)
            return super.getJavaMemberName(definition, Mode.DEFAULT) + "_=";
        else
            return super.getJavaSetterName(definition, mode);
    }

    @Override
    public String getJavaGetterName(Definition definition, Mode mode) {
        if (mode == Mode.RECORD)
            return super.getJavaMemberName(definition, Mode.DEFAULT);
        else
            return super.getJavaSetterName(definition, mode);
    }
}
```

**Comment by lukaseder** [comment]
Regarding your suggestions:

I'd suggest either:

> Define the interface convertToIdentifier in AbstractGeneratorStrategy (https://github.com/jOOQ/jOOQ/blob/master/jOOQ-codegen/src/main/java/org/jooq/util/AbstractGeneratorStrategy.java) & change references in the GeneratorStrategyWrapper.java (https://github.com/jOOQ/jOOQ/blob/master/jOOQ-codegen/src/main/java/org/jooq/util/GeneratorStrategyWrapper.java) to use that implementation; or

I'd prefer not to make that public. It is hardly a good idea to make anything not well thought through public :)

> Make "escaping" an option to turn off as part of the AbstractGeneratorStrategy - as an indication that all of the implemented getJavaGetterName/getJavaSetterName/etc are "responsible" for doing their own escaping

Hmm, that could indeed be an interesting flag. I've registered a feature request for this:
https://github.com/jOOQ/jOOQ/issues/5428

**Comment by er1c** [comment]
@lukaseder  You should publish the above `ScalaGetterSetterStrategy` into `org.jooq.util`, I can make a PR if you want, but you already did that work.

**Comment by er1c** [comment]
@lukaseder it's verbose, but it should probably be ScalaGetterSetterGeneratorStrategy too ...oye

**Comment by lukaseder** [comment]
I'm rather thinking of merging it into default functionality, if it goes into the core at all: https://github.com/jOOQ/jOOQ/issues/5426

If it doesn't become the new default, then I think that examples in the manual might be more generally useful than specialised strategies. I mean, this strategy only renames getters and setters. What if you want to rename also properties? Classes?
