### ISSUE TITLE
Error in DefaultGeneratorStrategy documentation

### ISSUE THREAD

**Issue by ooxi** [jOOQ/jOOQ#5436]
The documentation for [table naming with `DefaultGeneratorStrategy`](http://www.jooq.org/doc/3.8/manual/code-generation/codegen-generatorstrategy/#N3A39E) seems to be wrong.

If I read the code correctly

> // 2: strategy.getJavaClassName(table)

should be

> // 2: strategy.getJavaClassName(table, Mode.DEFAULT)

**Comment by lukaseder** [comment]
Thank you very much for reporting. This should be correct. The first one of your quoted code lines is just a convenience for the second, see also the Javadoc:

![image](https://cloud.githubusercontent.com/assets/734593/17028832/1ea567fc-4f69-11e6-814b-4acdcd22327e.png)

**Comment by ooxi** [comment]
You are right. I somehow though `String getJavaClassName(Definition)` is final.
