### ISSUE TITLE
Add implicit def asField[T](Option[T]): Field[T] to Conversions.scala

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5441]
It might be an interesting automatic conversion to add from `Option[T]` to `Field[T]` in the jOOQ API:

```scala
implicit def asField[T](r: Option[T]): Field[T] = DSL.value(r.getOrElse(null.asInstanceOf[T]))
```

See also this discussion here:
https://groups.google.com/d/msg/jooq-user/L8sH6SDCItA/eqo9B8tWAAAJ

Possible caveats:

- There might be new compile-time ambiguities for those that already use `Option` support via the code generator and converters
- This might introduce compile-time performance overhead throughout the jOOQ DSL

**Comment by er1c** [comment]
I'm still trying to get this to actually work "implicitly"

```
[error] /Users/eric/Work/ta-catalog/src/main/scala/ta/db/CatalogUserManager.scala:194: type mismatch;
[error]  found   : org.jooq.TableField[ta.db.generated.tables.records.CatalogUserRecord,String]
[error]  required: org.jooq.Field[java.io.Serializable]
[error] Note: String <: java.io.Serializable (and org.jooq.TableField[ta.db.generated.tables.records.CatalogUserRecord,String] <: org.jooq.Field[String]), but Java-defined trait Field is invariant in type T.
[error] You may wish to investigate a wildcard type such as `_ <: java.io.Serializable`. (SLS 3.2.10)
[error]       .set(CATALOG_USER.FIRST_NAME, row.firstName)
```

As far as "compile-time performance overhead" - I wouldn't worry about that impact on the scala-side of the world.

**Comment by er1c** [comment]
Blerg, yeah this won't necessarily work as hoped because the implicit won't get called because the .set will still match against a type "Serializable"

I mean, it "will work" but you have to essentially tell the .set which trype to use.  so if `row.firstName` is an `Option[String]` and `CATALOG_USER.FIRST_NAME` is `Field[String]`, you can do a `.set[String](CATALOG_USER.FIRST_NAME, row.firstName)` to get it to work in scala, but at that point it requires adding the type (which might make it more readable) but still not a great solution...hmmmm

**Comment by lukaseder** [comment]
Thanks for your comments.

> As far as "compile-time performance overhead" - I wouldn't worry about that impact on the scala-side of the world.

What do you mean by this? Do you mean that Scala compilation performance is already very bad? Anyway, I don't agree with this. I always worry about performance. It should be a feature, not an option. In my opinion, this includes compile time performance.

> to get it to work in scala, but at that point it requires adding the type (which might make it more readable) but still not a great solution...hmmmm

Yes, indeed. The existing frequent overloading of `(Field[T], T)` with `(Field[T], Field[T])` already leads to quite a few nasty compile time ambiguities (among others, in Java, the impossibility to pass a `null` literal as the value, unless casting it to `(T)`). Adding more overloads will increase the risk.

**Comment by er1c** [comment]
@lukaseder re: performance, implicit have a negligible compile-time impact in scala compiler, there are other reasons why the scala compiler is slow ;) But for this particular "do implicits add to the copmile-time performance overhead" the answer is no, they already have their implicit lookups, this just adds another record with no real measurable impact on compile time performance

**Comment by lukaseder** [comment]
You never know. Sometimes, there's just a really bad, edge-casey compiler bug that cannot really be solved easily. E.g. http://stackoverflow.com/q/34223249/521799

:) OK, anyway. The compile time ambiguity seems to be a show stopper for this feature anyway. I'm going to close this issue for now.
