### ISSUE TITLE
Support default methods in DefaultRecordMapper.ProxyMapper

### ISSUE THREAD

**Issue by forraikrisztian** [jOOQ/jOOQ#5442]
Hi,

We have run into the following issue:

- created az `interface` with `defult` method(s)
- used `fetchInto` with the created interface

The returned (proxy)object correctly contained all fields available in the database, but all `default` methods resulted in `null`.

Could you please also look at it?

**Comment by lukaseder** [comment]
Interesting, thank you very much for reporting. We'll look into this as soon as possible.

**Comment by forraikrisztian** [comment]
Thanks!

**Comment by lukaseder** [comment]
This now works for default methods in public interfaces. I couldn't figure out yet how to allow for calling invokespecial on protected / (package) private interfaces yet... Hope that's not an immediate limitation

**Comment by forraikrisztian** [comment]
Yes, thank you very much!

2016-07-25 14:05 GMT+02:00 Lukas Eder <notifications@github.com>:

**Comment by lukaseder** [comment]
The logic implemented for this fix has stopped working on JDK 9 and more recent:

- https://github.com/jOOQ/jOOQ/issues/15482

This has been a known problem for a while, but there hasn't been any issue in the issue tracker.
