### ISSUE TITLE
Document jOOQ 3.8 <forcedType/> configuration changes

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5443]
This very useful feature is not yet documented in the manual:
https://github.com/jOOQ/jOOQ/issues/4598

**Comment by ooxi** [comment]
Is there an example of how to use the new `<forcedType />` syntax anywhere? I have a couple of columns which should be handled as enumeration values not as integers and think the new `<forcedType />` configuration is exactly what I'm looking for.

**Comment by lukaseder** [comment]
@ooxi, yes, the linked issue (https://github.com/jOOQ/jOOQ/issues/4598) contains an example:

```xml
<forcedType>
    <userType>...</userType>
    <converter>...</converter>
    <expression>...</expression>
    <types>...</types>
</forcedType>
```

It's just a simplification of the existing syntax, which doesn't rely on a "named `<customType/>`" anymore.

**Comment by lukaseder** [comment]
OK, the "simple configuration" using only `<forcedType/>` is now documented:
http://www.jooq.org/doc/3.8/manual/code-generation/custom-data-types/
