### ISSUE TITLE
Support UPSERT returning values

### ISSUE THREAD

**Issue by jacobg** [jOOQ/jOOQ#5475]
I'd like to be able to do this:

```
dslContext().insertInto(_table)
				.set(insertFields)
				.onDuplicateKeyUpdate()
				.set(updateFields)
				.returning(returnFields)
				.execute()
```

Returning would apply to both insert and update cases.

Here is Postgres documentation on supporting RETURNING clause for UPSERT:
https://www.postgresql.org/docs/9.5/static/sql-insert.html

**Comment by lukaseder** [comment]
Thanks a lot for reporting. Indeed, there's a missing feature to allow for combining these clauses. We already have an issue for that: https://github.com/jOOQ/jOOQ/issues/2123. Hopefully, this will make it into jOOQ 3.9

**Comment by jacobg** [comment]
Thanks Lukas!
