### ISSUE TITLE
Field with alias query contribution problem

### ISSUE THREAD

**Issue by robrez** [jOOQ/jOOQ#5478]
Fields using aliases can cause invalid sql to be produced...

eg:
```java
DSLContext create = DSL.using(conn, SQLDialect.POSTGRES);
MyTable table = MyTable.MY_TABLE.as("t");
Field<String> f = MyTable.ID.as("myId");
Field<String> fc = DSL.decode().when(f.ne(""), f).otherwise("").as("myCase");
String sql = create.select(f, fc)
        .from(table)
        .where(f.like("A%")
        .getSQL();
```

```sql
SELECT
    "t"."id" as "myId",
    case 
        when "myId" <> '' then "myId"
        else ''
    end as "myCase"
WHERE
    "myId" like 'A%';

ERROR:  column "myId" does not exist
```

I don't think it would be unreasonable to say "Ok, then don't do that"; And, I'm aware there are any number of ways to workaround something like this.

At the same time I thought it might be worth mentioning here, in an issue.

I'm not familiar enough w/ jooq internals at this time to know whether a contribution step may have have enough context to know things like "Don't use the alias if I'm contributing to a boolean expression"

**Comment by lukaseder** [comment]
Thank you very much for reporting

> I don't think it would be unreasonable to say "Ok, then don't do that";

Indeed, that's what I was going to say :)

In fact, jOOQ does exactly what you tell jOOQ to do. jOOQ doesn't know if that aliased field reference is declared at the same top level SELECT, or if you perhaps used it in a derived table (a SELECT in the FROM clause), in case of which the alias would be available / in scope in the top level SELECT, and thus your query would be correct.

What you wanted to do instead is this:

```java
DSLContext create = DSL.using(conn, SQLDialect.POSTGRES);
MyTable table = MyTable.MY_TABLE.as("t");
Field<String> f = MyTable.ID;
Field<String> fc = DSL.decode().when(f.ne(""), f).otherwise("");
String sql = create.select(f.as("myId"), fc.as("myCase"))
        .from(table)
        .where(f.like("A%")
        .getSQL();
```

**Comment by robrez** [comment]
Neat, I didn't realize that `.as(...)` resulted in a new object reference (versus setting a property inside the same object).  Thanks for the help

**Comment by lukaseder** [comment]
Yeah, there's a section about (im)mutability in the manual here:
http://www.jooq.org/doc/latest/manual/sql-building/sql-statements/dsl-and-non-dsl

We try to make most operations immutable as it will allow for making using SQL through jOOQ much more composable. E.g. for cases like this one.
