### ISSUE TITLE
ResultImpl#intoMap produces an incorrect error message on duplicate key

### ISSUE THREAD

**Issue by akobiakov** [jOOQ/jOOQ#5481]
Looks like there is a bug in how `ResultImpl#intoMap` reports about a duplicate key in a result set: a key index is logged instead of a key itself.

E.g.:

```
Caused by: org.jooq.exception.InvalidResultException: Key 0 is not unique in Result for +--------+-------+
|video_id|     id|
+--------+-------+
|  162362|1228860|
|  162348|1228847|
...
```

See https://github.com/jOOQ/jOOQ/blob/5df74b0e835782716c59a5b98fa4bd5d8a7945e7/jOOQ/src/main/java/org/jooq/impl/ResultImpl.java#L1316

**Comment by lukaseder** [comment]
Thank you very much for reporting. Indeed, that could be improved. I still think that the record index is useful, but the message is clearly wrong as it is now.

**Comment by jasonab** [comment]
It appears that there are several other places in this same file that have the same problem, although I don't know if they are all fixable in the same way.

See lines 1727 and 1918 as examples.

**Comment by lukaseder** [comment]
@jasonab : Lines 1727 and 1918 of *what*? :) `ResultImpl` on version 3.11.2 has only 1720 lines: https://github.com/jOOQ/jOOQ/blob/version-3.11.2/jOOQ/src/main/java/org/jooq/impl/ResultImpl.java

**Comment by lukaseder** [comment]
But indeed, I can find other instances. I've created an issue to fix this more thoroughly: #7655

**Comment by jasonab** [comment]
Apologies, I was referring to 3.10.6 (the latest Spring Boot version). Thanks for taking a look.

**Comment by lukaseder** [comment]
OK cool. So I think I've found the right two spots then.
