### ISSUE TITLE
Documentation of DSL#sql(String, QueryPart ...) does not mention parsing bind value placeholders ("?")

### ISSUE THREAD

**Issue by rtomsick** [jOOQ/jOOQ#5483]
The documentation for `DSL#sql(String, QueryPart ...)` does not appear to match the behavior.

Steps to reproduce:
---

Create a query which uses `DSL#sql(String, QueryPart ...)`.  In the SQL itself, include the `?` character (a valid operator with Postgres jsonb columns) in addition to an indexed placeholder (e.g. `{0}`).  Pass at least one query part.

Expected outcome:
---

Query renders with the indexed placeholder replaced by the given query part.

Actual outcome:
---

Query renders with the `?` character replaced by the given query part.

Explanation:
---

I haven't looked at the code, but I'm pretty sure this should be considered a bug, as the documentation makes no mention of positional parameters being supported or even parsed in this mode.  For bonus points, this also means that I can't use the DSL syntax for queries that rely on Postgres jsonb contains operator.

Please let me know if you need any further information to reproduce the issue.  Thanks for writing jOOQ!

**Comment by lukaseder** [comment]
Thank you very much for your report. jOOQ 3.8.3 stops parsing *some* `?` characters, specifically when they're not "alone" (e.g. the `?|` operator) (3.8.3: https://github.com/jOOQ/jOOQ/issues/5365, 3.9.0: https://github.com/jOOQ/jOOQ/issues/5307).

The reason why jOOQ replaces that `?` character is for backwards compatibility with old jOOQ versions. Unfortunately, we cannot change this as it would probably break quite some code out there. You're right, though. This should be mentioned in the Javadoc, at least.

You don't have to use the operator in PostgreSQL, though. You can always use the backing function, in most cases, as a workaround:

- http://stackoverflow.com/q/38340086/521799
- http://stackoverflow.com/a/38370973/521799

Do note that chances are, you wouldn't get the operator past the PostgreSQL JDBC driver either.

**Comment by lukaseder** [comment]
I remember now the exact reason why the current behaviour is as it is. Unfortunately, the overload `sql(String, QueryPart...)` is a more specific version of `sql(String, Object...)`, not an incompatible one. So in case you pass a list of `QueryPart` to the former, and a single value is not a query part, then the latter, less specific overload is still applicable. This might be desired, though, for instance:

```java
// This calls sql(String, Object...)
sql("select {0}, {1} from {2}", TABLE.COL, 1 /* bind value */, TABLE);
```

So, ultimately, the two methods are executing the same logic.
