### ISSUE TITLE
Add a new jooq-postgres-extensions module for PostgreSQL specific extension

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5507]
PostgreSQL is one of the feature richest databases that jOOQ users use. At the same time, it ships with a lot of vendor specific API. We cannot directly use that API from the jOOQ core module, but if we had a jOOQ-postgres module, we could add an optional dependency on the PostgreSQL JDBC driver and reference stuff like `org.postgresql.util.HStoreConverter` (see also [Leigh Whiting's message on the user group](https://groups.google.com/d/msg/jooq-user/0FV4kis66pM/hm8hz-BeCgAJ))

I think that such a new module would be very well received with the community and would lead to quite a few community contributions.

---

Note that other databases with lots of vendor-specific features (e.g. Oracle) follow the JDBC standard APIs a bit more closely, which means that we already provide out-of-the-box support for a lot of advanced features (such as object or table types)

---

See also:
- https://groups.google.com/d/msg/jooq-user/0FV4kis66pM/hm8hz-BeCgAJ
- http://stackoverflow.com/a/39394930/521799

**Comment by safaci2000** [comment]
+1. I'd, love to see this module come out.

**Comment by skroll** [comment]
Excellent, I have quite a few custom bindings and a PostgresDSL class that I've had to maintain, and having some of these distributed with jOOQ itself would be great.

**Comment by lukaseder** [comment]
Looking into this now, for jOOQ 3.15. Related improvement: https://github.com/jOOQ/jOOQ/issues/10763 (automatically generate `<forcedType/>` configurations from available bindings)

**Comment by lukaseder** [comment]
A first working draft is committed here: https://github.com/jOOQ/jOOQ/tree/main/jOOQ-postgres-extensions. PRs are very welcome! (Please observe the usual rules here: https://github.com/jOOQ/jOOQ/blob/main/CONTRIBUTING.md)

**Comment by baev** [comment]
There is a bunch of PGObject classes available that possible targets for adding bindings.

PGInterval, PGMoney (should be avoided as far as I know), and geometry types. The question is what are the best possible types for the binding's <U> type variable for all these PG* types.

From my point of view the most required binding is for PGInterval as it's widely used for analytics functions.

The other useful bindings are for `tsvector` and `tsquery`. There are no such PGObjects available, so we'll need to create our types for them.

I can't see any use of `tsquery` and `tsvector` type within Java codebase, so they may just be a class that holds string representation inside. And since there are not much full text functions available in PostgreSQL it may worth to add them as well.

**Comment by lukaseder** [comment]
Thanks a lot for your suggestions, @baev!

I'm commenting them individually:

> PGInterval

Do we gain anything compared to our existing `SQLDataType.INTERVAL`, `SQLDataType.INTERVALYEARTOMONTH`, and `SQLDataType.INTERVALDAYTOSECOND` types? Intervals are quite the standard feature. What would we gain from an additional, PostgreSQL specific binding?

> PGMoney (should be avoided as far as I know)

Indeed, we won't support that type, see https://github.com/jOOQ/jOOQ/issues/4364 and https://github.com/jOOQ/jOOQ/issues/6852. I don't think we should support it in this extension module either.

> and geometry types

These are *very* interesting indeed. However, I wonder if it's a good idea to support them here in this extensions module, with this being a very popular feature request: https://github.com/jOOQ/jOOQ/issues/982.

GIS types are quite standard, and there are various libraries out there that standardise on them also in Java. Without having done any research, this is one example from Google: https://geotools.org. There are others, here: https://stackoverflow.com/q/2404492/521799

I wouldn't really want to expose the JDBC driver's PG* types, although it *is* an option. But I think I'd like to do some research on possible GIS support first, and then, perhaps, offer a standardised implementation in jOOQ's core, not in this extensions module.

> The other useful bindings are for `tsvector` and `tsquery`.

These would be interesting indeed. I don't think we need any client side data type for these, given that they can be represented as Strings within PostgreSQL. The docs says:

```sql
SELECT 'a fat cat sat on a mat and ate a fat rat'::tsvector;
SELECT 'fat & rat'::tsquery;
```

See https://www.postgresql.org/docs/current/datatype-textsearch.html. So supporting these types would just mean implementing the boring glue code to read/write the type, and the cast.

A defensive, forward compatible approach would be to offer wrapper types in this module, similar to `org.jooq.JSON` and `org.jooq.JSONB`, such that we can add functionality in the future. I wouldn't mind that. Also, introducing such a wrapper type for the `Hstore` type `Map<String, String>` could be useful.

I'll implement the `Hstore` type today, to set an example.

Other types that are interesting in this context are the various range types, see: https://github.com/jOOQ/jOOQ/issues/2968

**Comment by lukaseder** [comment]
I like the `HstoreBinding` and its application much more, now that we have an `Hstore` wrapper type. It's cleaner, and no unsafe casts are needed to cast `Map.class` to `Class<Map<String, String>>`

**Comment by baev** [comment]
maybe it worth to add `PostgreSQLDataType` class with `HSTORE` declared?

**Comment by lukaseder** [comment]
> maybe it worth to add `PostgreSQLDataType` class with `HSTORE` declared?

No, we'd have to add it to `SQLDataType` as well, and start supporting it for all RDBMS. This is really about opt in extensions to core jOOQ

**Comment by baev** [comment]
is there an issue to track?

**Comment by lukaseder** [comment]
Track what?

**Comment by hisener** [comment]
Hey @lukaseder, we have a PostGIS [Geometry](https://github.com/postgis/postgis-java/blob/master/postgis-jdbc-geometry/src/main/java/net/postgis/jdbc/geometry/Geometry.java) binding in our @PicnicSupermarket codebase. Would you be interested in porting it to `jooq-postgres-extensions` with an optional [`postgis-geometry`](https://github.com/postgis/postgis-java) dependency?

**Comment by lukaseder** [comment]
Thanks for your suggestion. I think that GIS is a topic that deserves being discussed outside of this PG specific extensions module: https://github.com/jOOQ/jOOQ/issues/982

A lot of RDBMS have GIS support, and GIS is quite standard, see: https://www.iso.org/committee/54904/x/catalogue. It is definitely a popular request, so it would make sense to think about this more thoroughly. But this PG specific extensions modules is about stuff that is really PG specific, such as e.g. `hstore` or `intrange` or other types.

**Comment by hisener** [comment]
Clear, I subscribed to that issue, as well. 👍

**Comment by lukaseder** [comment]
Well, this new module will ship in jOOQ 3.15 with an impressive 1 supported pg specific data type :) Let's see how user contributions work out in the near future.
