### ISSUE TITLE
Make JavaWriter.ref() methods public

### ISSUE THREAD

**Issue by sir-maniac** [jOOQ/jOOQ#5517]
You're doing a great job with jOOQ!  I love the elegance of the design, and found it either directly addresses my use cases, or is extensible enough to allow me to address them without too much trouble.

In summary, I'd humbly suggest the following to improve code generation customization:
1. Provide a way to to convert the string of a class name with the formatted JavaWriter.print() methods. OR make ref() methods public so they can be accessed from a subclass of JavaGenerator.
2. Improve JavaWriter.ref() so multiple type parameters of a generic can be processed(as of 3.8.4, only one can)

## Rationale
The JavaGenerator(which I've been using as examples for my own customization), liberally uses ref() directly, as it builds the various parts of the code, and I've found it useful to format the code similarly, without having to add printClass() calls, interrupting the formatted print calls.  

In my code generation, I add custom interfaces with multiple generic arguments(for example IdDAO<R extends Record,P>), when returning strings from GeneratorStrategy.getJavaClassImplements(), JavaWriter doesn't convert the 2 type arguments to their non-qualified name.  "`IdDAO<com.company.SomeRecord,com.company.SomePojo>`" does not convert to "`IdDAO<SomeRecord, SomePojo>`" without calling ref() on each before returning.  I have not found a workaround for this, except to track the JavaWriter in my GeneratorStrategy, and call out.ref in these methods.

For reference for anyone else having this trouble I currently implemented the following as a workaround:

I subclassed JavaWriter, and made the ref methods public:
```Java
public class JavaWriterExt extends JavaWriter {
...
    @Override
    public ref(...) {
        return super.ref(...);
    }
...
}
```

In my custom `JavaGenerator`:
```Java
public class MyJavaGenerator extends JavaGenerator {
	private MyGeneratorStrategy strategy;

	@Override
	public void setStrategy(GeneratorStrategy strategy)
	{
		this.strategy = (MyGeneratorStrategy)strategy;
		super.setStrategy(strategy);
	}

...

	@Override
	protected JavaWriterExt newJavaWriter(File file) {
		JavaWriterExt out = new JavaWriterExt(file, generateFullyQualifiedTypes(), targetEncoding);
		strategy.setOut(out);
		return out;
	}

	@Override
	protected void closeJavaWriter(JavaWriter out) {
		strategy.setOut(null);
		super.closeJavaWriter(out);
	}
...
}
```

My GeneratorStrategy:
```Java
public MyGeneratorStrategy extends DefaultGeneratorStrategy {
	private JavaWriterExt out;
...
	public void setOut(JavaWriterExt out)
	{
		this.out = out;
	}
...
	@Override
	public List<String> getJavaClassImplements(Definition definition, Mode mode)
	{
		if (definition instanceof TableDefinition &&  mode == Mode.DEFAULT)
		{
			String recordType = out.ref(getFullJavaClassName(definition, Mode.RECORD));
			String pojoType = out.ref(getFullJavaClassName(definition, Mode.POJO));
			String daoType = out.ref(getFullJavaClassName(definition, Mode.DAO));

			return Collections.singletonList(
					String.format("com.company.MyTable<%s, %s<%s, %s>>", recordType, daoType, recordType, pojoType));
		} else if (definition instanceof TableDefinition &&  mode == Mode.DAO) {
			String recordType = out.ref(getFullJavaClassName(definition, Mode.RECORD));
			String pojoType = out.ref(getFullJavaClassName(definition, Mode.POJO));
			String daoType = out.ref(getFullJavaClassName(definition, Mode.DAO));
			
			return Collections.singletonList(
					String.format("%s<%s, %s>", daoType, recordType, pojoType));
 		}

		return null;
	}
}
```

**Comment by lukaseder** [comment]
Thank you very much for your detailed feature request.

> OR make ref() methods public so they can be accessed from a subclass of JavaGenerator.

Sure, why not. As a workaround, you could put your JavaGenerator subclass in the `org.jooq.util.` package, which would give you access to the method as well.

> 2. Improve JavaWriter.ref() so multiple type parameters of a generic can be processed(as of 3.8.4, only one can)

Perhaps we could do that (as part of a separate feature request), but I'd like to learn about the rationale behind this a bit more. I'm a bit reluctant to implement a Java syntax parser that takes into account all the caveats of generic type definitions...

**Comment by lukaseder** [comment]
Implemented public `ref()` methods. Thanks again for your suggestion.
