### ISSUE TITLE
problem using DSL.unnest in "insert into ... select" query

### ISSUE THREAD

**Issue by Centaur** [jOOQ/jOOQ#5519]
I am using `insert into ... select` to insert a `Long role_id` and a `List<Long> resource_ids` into a many-to-many table, each new row has the same `role_id`. The sql should look like: 

```sql
insert  into role_resource 
select role_id, x
from unnest(resource_ids) x 
```

My first attemp
```java
dsl.insertInto(ROLE_RESOURCE)
     .select(
        dsl.selectFrom(DSL.values(DSL.row(role_id, DSL.unnest(resource_ids)))))
```

When executing, it throws `IllegalArgumentException` with message `Cannot interpret argument of type class org.jooq.impl.ArrayTable as a Field: "array_table"`

Second attemp:
```java
dsl.insertInto(ROLE_RESOURCE)
     .select(
       dsl.select(DSL.value(role_id), DSL.field("x")).from(DSL.unnest(resource_ids).asTable("x")))
```

When executing, it throws `DataAccessException` with generated sql 

```sql
insert into role_resource (role_id, resource_id) select ?, x from (select * from unnest(?::any[]) as x(COLUMN_VALUE)) as x returning role_resource.role_id, role_resource.resource_id 
```

and `ERROR: syntax error at or near "any"`

What is the correct way to write this query?

**Comment by lukaseder** [comment]
Thank you very much for reporting. Indeed, there are a couple of issues with the `DSL.unnest()` function. I'm investigating and will be fixing individual issues. In the meantime, as a workaround, this code works for me:

```java
        // Pass an array, not a List. That way, jOOQ / PostgreSQL will use the correct type information
        Integer[] values = { 1, 2, 3 };

        // The unnested column is called `COLUMN_VALUE` in jOOQ (for Oracle compatibility)
        Field<Integer> columnValue = field(name("COLUMN_VALUE"), int.class);

        Result<Record2<String, Integer>> r1 = create()
            .select(
                val("a"),
                columnValue)
            .from(unnest(values).as("x"))
            .fetch();
```

**Comment by lukaseder** [comment]
I have fixed all relevant issues. This should now work in jOOQ 3.9, and the workaround already works in jOOQ 3.8.4, if I'm not mistaken.

Please let me know if you encounter any further issues / have any further questions.
