### ISSUE TITLE
Custom binding between Timestamp and java.time.Instant is not used when inserts are batched

### ISSUE THREAD

**Issue by problemzebra** [jOOQ/jOOQ#5539]
I have a custom binding between Instant and the TIMESTAMP database type to ensure that the calender time zone is always set to UTC to avoid that the database shifts java.time.Instant values by 2 hours (because the database timezone is Europe/Berlin -> UTC +2).

This binding is not used when I execute a batched insert (the set(...) methods are not called). However, the binding is used when inserts are not batched.

Database: Oracle 12
JDBC driver: ojdbc7 12.1.0.2.0
Jooq version: 3.8.3

**Batched insert**

``` java
...
valuesList.add(jooqContext().dsl()
                                        .insertInto(TABLE_A)
                                        .columns(TABLE_A.ID,
                                                 ...
                                                 TABLE_A.FROM_TIME_UTC,
                                                 TABLE_A.TO_TIME_UTC,
                                                 ...
                                                 TABLE_A.V99)
                                        .values(id,
                                                 ...
                                                val(itemToInsert.getFrom(), TABLE_A.FROM_TIME_UTC),
                                                val(itemToInsert.getTo(), TABLE_A.TO_TIME_UTC),
                                                ...
                                                ...));
        }

        jooqContext().dsl().batch(valuesList).execute();
...
```

**Generated Jooq class**

``` java
...
 public final TableField<XXRecord, Instant> FROM_TIME_UTC = createField("FROM_TIME_UTC", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "", new TimestampUtcBinding());
...
```

**Custom Binding**

``` java
public class TimestampUtcBinding implements Binding<Timestamp, Instant> {
    private static final long serialVersionUID = 1;

    private final Converter<Timestamp, Instant> converter;
    private final DefaultBinding<Timestamp, Instant> delegate;

    public TimestampUtcBinding() {
        this.converter = new Converter<Timestamp, Instant>() {
            @Override
            public Instant from(Timestamp databaseObject) {
                if (databaseObject == null) {
                    return null;
                }
                return databaseObject.toInstant();
            }

            @Override
            public Timestamp to(Instant userObject) {
                if (userObject == null) {
                    return null;
                }
                return Timestamp.from(userObject);
            }

            @Override
            public Class<Timestamp> fromType() {
                return Timestamp.class;
            }

            @Override
            public Class<Instant> toType() {
                return Instant.class;
            }
        };
        this.delegate = new DefaultBinding<>(converter);
    }

    @Override
    public final Converter<Timestamp, Instant> converter() {
        return converter;
    }

    @Override
    public final void sql(BindingSQLContext<Instant> ctx) throws SQLException {
        delegate.sql(ctx);
    }

    @Override
    public final void register(BindingRegisterContext<Instant> ctx) throws SQLException {
        delegate.register(ctx);
    }

    @Override
    public final void set(BindingSetStatementContext<Instant> ctx) throws SQLException {
        Instant value = ctx.value();
        PreparedStatement statement = ctx.statement();
        if (value == null) {
            statement.setNull(ctx.index(), Types.TIMESTAMP);
        } else {
            Timestamp timestamp = Timestamp.from(value);
            TimeZone utcTimeZone = TimeZone.getTimeZone(ZoneId.of(ZoneOffset.UTC.getId()));
            Calendar calendar = Calendar.getInstance(utcTimeZone);
            statement.setTimestamp(ctx.index(), timestamp, calendar);
        }
    }

    @Override
    public final void set(BindingSetSQLOutputContext<Instant> ctx) throws SQLException {
        delegate.set(ctx);
    }

    @Override
    public final void get(BindingGetResultSetContext<Instant> ctx) throws SQLException {
        ResultSet resultSet = ctx.resultSet();
        TimeZone utcTimeZone = TimeZone.getTimeZone(ZoneId.of(ZoneOffset.UTC.getId()));
        Calendar calendar = Calendar.getInstance(utcTimeZone);
        Timestamp timestampUtc = resultSet.getTimestamp(ctx.index(), calendar);

        if (timestampUtc == null) {
            ctx.value(null);
        } else {
            ctx.value(timestampUtc.toInstant());
        }
    }

    @Override
    public final void get(BindingGetStatementContext<Instant> ctx) throws SQLException {
        delegate.get(ctx);
    }

    @Override
    public final void get(BindingGetSQLInputContext<Instant> ctx) throws SQLException {
        delegate.get(ctx);
    }
}
```

**Comment by lukaseder** [comment]
Thank you very much for your detailed bug report. We'll investigate this ASAP. If confirmed, a fix will go into patch release 3.8.5 next week - this seems like a significant issue

**Comment by lukaseder** [comment]
I've investigated this and I can reproduce the problem the way it is exposed here. Your batch call:

```java
jooqContext().dsl().batch(valuesList).execute();
```

Will run a multi statement batch, which doesn't support bind variables. In other words, there is no need for jOOQ to call the `set()` methods as the underlying statement isn't really a prepared statement. All the conversion will need to be implemented in the `sql()` method, e.g.:

```java
    @Override
    public final void sql(BindingSQLContext<Instant> ctx) throws SQLException {
        if (ctx.render().paramType() == INLINED)
            delegate.sql(/* conversion here to produce inline bind variable */);
        else
            delegate.sql(ctx);
    }
```

I have registered a feature request to improve the manual for this: https://github.com/jOOQ/jOOQ/issues/5545

Does this help or do you think there are any other issues that might not have been covered by this answer?

**Comment by problemzebra** [comment]
Thanks for your answer.

Would it in general be possible to handle batching in Jooq transparently?

**Comment by lukaseder** [comment]
What do you mean by "transparently"?

**Comment by problemzebra** [comment]
If everything works without batching everything should also work with batching. Because it is error prone if custom Bindings are actually not used when e.g. an insert is batched. I guess most users will think that the JDBC level interaction is always the same (from the custom Binding) no matter wether the insert is batched or not (like with standard JDBC).

Initially we haven't batched the inserts. Then we optimized our code for better performance... ;)

Jooq does not use a PreparedStatment for batch inserts?

**Comment by lukaseder** [comment]
Well ... :)

There are two ways to create statements in JDBC: Static statements and prepared statements. There are also two ways to create batch statements in JDBC: Static statements (multiple SQL strings) and prepared statements (single SQL string and multiple bindings).

jOOQ mirrors this behaviour and if you're writing your own binding, you must ensure that both statement types are going to be supported. It is clearly a documentation flaw that the static statement case isn't explained well enough. #5545 (and possibly other improvements) will fix this.

You chose the static statement, multiple SQL string, no bind variable API, which is also explained here (look for "several queries"):
http://www.jooq.org/doc/latest/manual/sql-execution/batch-execution

Also relevant:
http://www.jooq.org/doc/latest/manual/sql-execution/statement-type

Having said so, I'm very open to learn how we can further improve the `org.jooq.Binding` documentation to help users get this right!

**Comment by michaelsproul** [comment]
I'm having the same problem with `DSLContext.batchInsert`, is that to be expected? The stack trace I'm getting shows that jOOQ is using a prepared statement:

```
org.jooq.exception.DataAccessException: SQL [insert into "public"."message" ("metadata") values (cast(? as varchar))]; Batch entry 0 insert into "public"."message" ("metadata") values (cast(NULL as varchar)) was aborted: ERROR: column "metadata" is of type json but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 258  Call getNextException to see the cause.
        at org.jooq.impl.Tools.translate(Tools.java:1941)
        at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:659)
        at org.jooq.impl.BatchSingle.executePrepared(BatchSingle.java:259)
        at org.jooq.impl.BatchSingle.execute(BatchSingle.java:182)
        at org.jooq.impl.BatchCRUD.executePrepared(BatchCRUD.java:159)
        at org.jooq.impl.BatchCRUD.execute(BatchCRUD.java:100)
        at rungopher.db_access.DbMessage.persist(DbMessage.java:46)
        at rungopher.StartCampaign.sendFirstMessages(StartCampaign.java:166)
        at rungopher.StartCampaign.start(StartCampaign.java:85)
        at rungopher.CampaignEventHandler.handleDelivery(CampaignEventHandler.java:46)
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into "public"."message" ("campaign_id", "conversation_id", "start_state", "end_state", "link_followed", "kind", "sender", "recipient", "content", "metadata", "timestamp", "source") values (777, 15, '<<start>>', 'askEmail', 0, 'outbound_sms'::"public"."message_kind", '+61418974654', '+61434193516', 'Hi friend, what''s your email?', cast(NULL as varchar), 1474442678514002972, 0) was aborted: ERROR: column "metadata" is of type json but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 258  Call getNextException to see the cause.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:148)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:780)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1662)
        at org.jooq.tools.jdbc.DefaultStatement.executeBatch(DefaultStatement.java:93)
        at org.jooq.impl.BatchSingle.executePrepared(BatchSingle.java:239)
        ... 12 more
```

[stack trace edited to remove irrelevant columns, I can try creating a more minimal example if you think this is a bug]

I'm using the JSON<->GSON binding copied verbatim from the example here:

http://www.jooq.org/doc/3.8/manual/code-generation/custom-data-type-bindings/

**Comment by lukaseder** [comment]
@michaelsproul Thank you very much for reporting. I think this is not exactly the same issue as the one reported by @problemzebra. We don't see their stack trace here in the issue, but their call to `batch(valuesList)` executes an `org.jooq.impl.BatchMultiple` statement, which doesn't work with prepared statements.

I cannot reproduce such an issue right away. In our integration tests, batching stuff with bindings works. Could you perhaps post your Java code to help reproduce this?

**Comment by michaelsproul** [comment]
@lukaseder, I've isolated a minimal test case and created a stand-alone repository for it:

https://github.com/michaelsproul/jooq-batch-insert-bind

**Comment by lukaseder** [comment]
Thank you very much, @michaelsproul. Will look at it ASAP

**Comment by lukaseder** [comment]
@michaelsproul: Thanks again for your test case. I can reproduce the issue, but the problem is: You're not applying the binding in the code generator. Will comment directly in your code...

**Comment by michaelsproul** [comment]
(resolved, thank you)
