### ISSUE TITLE
Bad predicate generated for INSERT .. ON DUPLICATE KEY IGNORE emulation in PostgreSQL 9.3 dialect

### ISSUE THREAD

**Issue by sytolk** [jOOQ/jOOQ#5540]
I have JOOQ 3.8 and Postgre version:
`PostgreSQL 9.2.15 on x86_64-redhat-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4), 64-bit`
and this Query:
``` 
dsl.insertInto(PERSON_ROLES, PERSON_ROLES.PERSON_ID, PERSON_ROLES.ROLE_ID)
                .values(personId, roleId).onDuplicateKeyIgnore().execute();
```
If I have SQLDialect=POSTGRES_9_3
```xml
<property name="SQLDialect">
            <value type="org.jooq.SQLDialect">POSTGRES_9_3</value>
</property>
```
This is generated query and exception:
```
BadSqlGrammarException: jOOQ; bad SQL grammar [insert into "public"."person_roles" ("person_id", "role_id") select "t"."person_id", "t"."role_id" from (select ? as "person_id", ? as "role_id" where not exists (select 1 as "one" from "public"."person_roles" where "public"."person_roles"."id" = cast(? as varchar))) as "t"]; nested exception is org.postgresql.util.PSQLException: ERROR: operator does not exist: bigint = character varying
```
If I have SQLDialect=POSTGRES_9_5 this:
```
BadSqlGrammarException: jOOQ; bad SQL grammar [insert into "public"."person_roles" ("person_id", "role_id") values (?, ?) on conflict do nothing]; nested exception is org.postgresql.util.PSQLException: ERROR: syntax error at or near "on"
```
If its have SQLDialect for Postgre 9.2 ?

**Comment by sytolk** [comment]
Or it`s better not to use onDuplicateKeyIgnore() with old version of Postgre and check if unique key exist first :)

**Comment by lukaseder** [comment]
Hmm, we currently don't officially support PostgreSQL 9.2 anymore, but I think the query should work with the 9.3 dialect. The question is, why aren't you specifying the `PERSON_ROLES.ID` column? Could you perhaps post the DDL of your table?

**Comment by sytolk** [comment]
This is DDL I have on localhost Postgres 9.5 and the generated SQL query for this dialect works without problems. I try to insert person_id role_id that exist in person_roles table.
```
CREATE TABLE person_roles
(
id BIGINT PRIMARY KEY NOT NULL,
person_id BIGINT,
role_id INTEGER,
CONSTRAINT person_roles_person__fk FOREIGN KEY (person_id) REFERENCES person (id),
CONSTRAINT person_roles_role__fk FOREIGN KEY (role_id) REFERENCES role (id)
);
CREATE UNIQUE INDEX person_roles_person_id_role_id_uindex ON person_roles (person_id, role_id);
```

**Comment by lukaseder** [comment]
Hmm, are you sure you've provided all the required info? Is there some trigger or sequence or serial, etc. on the primary key? As it stands now, you cannot insert a NULL value into it, regardless of the PostgreSQL version.

**Comment by sytolk** [comment]
I have copy DDL from my IDE Intelij. ID column is autoincremented
id BIGINT default nextval('person_roles_id_seq'::regclass) -- part of primary key

**Comment by lukaseder** [comment]
That does change 1-2 things. So, the original primary key type was probably `serial8`, not `bigint`.

I can now reproduce the issue with the PostgreSQL 9.3 dialect. Will investigate

**Comment by sytolk** [comment]
After I have view the generated SQL for PostgreSQL 9.3 I have upgrade to 9.5 production server too :)
I have copy this DDL for my local PostgreSQL 9.5 I don`t have v9.2 anymore but it should be the same?

**Comment by lukaseder** [comment]
It's OK I could reproduce the issue, thanks :) Great to hear you've upgraded. There are quite a few goodies in the server anyway... :)

**Comment by cuigaochong** [comment]
Hi,i user mysql 5.6 ,generate jooq(3.8.5) by gradle（https://github.com/etiennestuder/gradle-jooq-plugin） ,but have a error like this ：
jOOQ; bad SQL grammar [insert into "stargate"."deployment_log" ("app_id", "push_sequence", "environment", "result") values (?, ?, ?, ?)]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"stargate"."deployment_log" ("app_id", "push_sequence", "environment", "result")' at line 1
	at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:99)

**Comment by lukaseder** [comment]
@cuigaochong You seem to be using a wrong SQLDialect. It generates double quotes `"` on MySQL, when you should be generating backticks `` ` ``
