### ISSUE TITLE
Code generator should delete catalog and schema directories when no longer configured

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5556]
Assuming that at some point, a user configures:

```xml
<schemata>
    <schema>
        <inputSchema>schema1</inputSchema>
    </schema>
    <schema>
        <inputSchema>schema2</inputSchema>
    </schema>
    <schema>
        <inputSchema>schema3</inputSchema>
    </schema>
</schemata>
```

And then, they decide that schema3 is no longer needed:

```xml
<schemata>
    <schema>
        <inputSchema>schema1</inputSchema>
    </schema>
    <schema>
        <inputSchema>schema2</inputSchema>
    </schema>
</schemata>
```

The jOOQ code generator should remove all the code in the schema3 directory.

Note that single catalog / single schema code generations omit the catalog / schema package in the path. This means that when removing the second last schema, the whole hierarchy changes.

----
- Depends on https://github.com/jOOQ/jOOQ/issues/4794

**Comment by jdimeo** [comment]
What about trying to use the Maven plugin with multiple `<execution>` s? I would like to generate code with two different `<strategy>` s and it's looking like one run of the plugin is clearing out the files of the previous run.

**Comment by lukaseder** [comment]
@jdimeo The executions are logically independent in Maven, just as if you had two entirely independent applications generate code into the same directory. So, you shouldn't do that.

You can either turn off the cleaning of the target, though that will be annoying when you drop or rename objects (see https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-target/), or better, generate things into two separate target directories. You can still generate things in the same package, though.

Alternatively, implement your own programmatic strategy that can handle both use-cases at the same time, if the configurative one doesn't suffice.

**Comment by jdimeo** [comment]
Thank you - I had missed that `<clean>` was available!
