### ISSUE TITLE
DataTypeException: Cannot convert from String to class [B when generated code contains VARBINARY type with default value

### ISSUE THREAD

**Issue by Signatured** [jOOQ/jOOQ#5569]
Getting this issue when trying to run any query.

Query:

```java
PlayerRecord rec = Database.get().selectFrom(Tables.PLAYER).where(Tables.PLAYER.ID.eq(1)).fetchAny();
```

[Full Stack Trace](https://gist.github.com/8311a132643c36c3b133196e99d5064a)
[Xenforo Class](https://gist.github.com/eb2b5386b1cbd7fdce3162cb6f10f932)
[XfAdminLog Class](https://gist.github.com/cae9479b1dc72100c3034cbfaf8b1836)

**Comment by Signatured** [comment]
Let me know if more info is needed to diagnose issue.

**Comment by lukaseder** [comment]
Thank you very much for reporting. This is a regression introduced with https://github.com/jOOQ/jOOQ/issues/4841 (support for default values in generated code)

As a quick workaround, you could remove the `DEFAULT` clause from the table, or revert to a jOOQ version before 3.8, or patch the code generator in order not to produce these defaults (I can help you with that, if that's an option. I would need to know the database you're using, then...)

**Comment by lukaseder** [comment]
Thanks again for reporting. I can reproduce this using the following table:

```sql
CREATE TABLE t_5569 (
  val VARBINARY(5) DEFAULT ''
)
```
