### ISSUE TITLE
Incorrect ambiguity warning when column name appears in 3+ joined tables

### ISSUE THREAD

**Issue by sgrimm-sg** [jOOQ/jOOQ#5578]
In `Fields.field(Field)` there is a message "Ambiguous match found for X" that's logged in cases where the unqualified form of the requested field name matches more than one field in the field list. However, this message is logged too eagerly and shows up even in cases where there's no ambiguity.

To see the problem, join three tables that all have a column with the same name. Call `field()` with the the name of the table and column (but not the schema) from the third table. The ambiguity message is logged even though the method eventually finds an exact match and returns it as expected. The message isn't logged if you search for the first or second table's version of the column.

**Comment by lukaseder** [comment]
Huh, very interesting. Thank you very much for reporting. Indeed, this seems to happen only for the third "ambiguous" match. Will investigate...

**Comment by lukaseder** [comment]
Oh yes, it's obvious. The algorithm is wrong. The `log.info` call should happen outside of the loop if there had not been any previous loop break by the `return` statement. Current implementation:

```java
        for (Field<?> f : fields) {
            String fName = f.getName();

            if (tableName != null) {
                String tName = tableName(f);

                if (tName != null && tableName.equals(tName) && fName.equals(fieldName))
                    return (Field<T>) f;
            }

            // In case no exact match was found, return the first field with matching name
            if (fName.equals(fieldName)) {
                if (columnMatch == null)
                    columnMatch = f;
                else
                    // [#4476] [#4477] This might be unintentional from a user
                    // perspective, e.g. when ambiguous ID columns are present.
                    log.info("Ambiguous match found for " + fieldName + ". Both " + columnMatch + " and " + f + " match.", new SQLWarning());
            }
        }
```

**Comment by lukaseder** [comment]
Will merge this to 3.8.5 (https://github.com/jOOQ/jOOQ/issues/5579). Thanks again for reporting!
