### ISSUE TITLE
Publish the generated source dir in the Maven code generator plugin to help IDEs pick up the source dir

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5582]
As explained by @mstahv

For example:
https://github.com/viritin/vwscdn/blob/83a2c4406791679794b8231937bfb77d7b1813d0/maven-plugin/src/main/java/in/virit/vwscdn/VWSCDNMojo.java#L117

**Comment by lukaseder** [comment]
Hmm, no, it's already being done, in fact:
https://github.com/jOOQ/jOOQ/blob/227c0c07773cd963202a10fe06fb83f667235570/jOOQ-codegen-maven/src/main/java/org/jooq/util/maven/Plugin.java#L199

**Comment by lukaseder** [comment]
Hmm, perhaps that call should be done *before* generating sources in that directory?

**Comment by mstahv** [comment]
If I add this config to project, the generated sources seems to be picked up by Eclipse:

        		<plugin>
        			<groupId>org.eclipse.m2e</groupId>
        			<artifactId>lifecycle-mapping</artifactId>
        			<version>1.0.0</version>
        			<configuration>
        				<lifecycleMappingMetadata>
        					<pluginExecutions>
        						<pluginExecution>
        							<pluginExecutionFilter>
        								<groupId>org.jooq</groupId>
        								<artifactId>
        									jooq-codegen-maven
        								</artifactId>
        								<versionRange>
        									[3.8.4,)
        								</versionRange>
        								<goals>
        									<goal>generate</goal>
        								</goals>
        							</pluginExecutionFilter>
        							<action>
        							<execute><runOnConfiguration>true</runOnConfiguration></execute>
        							</action>
        						</pluginExecution>
        					</pluginExecutions>
        				</lifecycleMappingMetadata>
        			</configuration>
        		</plugin>

So, it might be that this kind of "hint" for Eclipse is needed as well. In Vaadin plugin we use this file so that people don't need to clutter their project pom.xml files:

https://github.com/vaadin/maven-plugin/blob/master/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml

**Comment by lukaseder** [comment]
Interesting, thank you very much for your hints, @mstahv. That m2e XML file really seems more user friendly for us to add, than expecting everyone to add their own lifecycle mapping to user pom.xml's - which tend to become quite large already.

**Comment by mstahv** [comment]
Yep, that made a big difference for my example projects (which had to support Eclipse as well ;-) ). But, as said, it seems to somehow fix the original problem as well.

**Comment by lukaseder** [comment]
Hmm, I've tried all of these things with Eclipse Neon, but I fail to see how they work... They don't seem to do the trick for me, or perhaps I'm misunderstanding the problem...

**Comment by mstahv** [comment]
Is it hard to build jOOQ? Maybe I could give it a try.

**Comment by lukaseder** [comment]
Just `mvn clean install`. There are many simple examples here: https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples

**Comment by lukaseder** [comment]
Oh wait, I'm still fighting with build issues in the Open Source Edition on GitHub on the master branch... :-/ Perhaps this branch will be easier:
https://github.com/jOOQ/jOOQ/tree/version-3.8.0-branch

**Comment by mstahv** [comment]
I tried and it seems to work for me. So this is how it looks like before:

<img width="550" alt="screenshot 2016-10-22 11 53 36" src="https://cloud.githubusercontent.com/assets/1478052/19618319/ad1a8272-984f-11e6-97a1-0ee6fe6d605f.png">

And even after mvn clean install, unless one manually configures classpath:

<img width="405" alt="screenshot 2016-10-22 11 54 06" src="https://cloud.githubusercontent.com/assets/1478052/19618321/b6880be0-984f-11e6-9bca-e5991c3a2493.png">

And with the change in my pull request it builds and configures automatically:
<img width="1017" alt="screenshot 2016-10-22 11 52 18" src="https://cloud.githubusercontent.com/assets/1478052/19618326/cff6e970-984f-11e6-92df-b4f2ad10354f.png">

I tested using this example project. Built a development version to local maven repo and overrided the jooq maven plugin version:
https://github.com/alejandro-du/vaadin-spring-jooq-demo

**Comment by mstahv** [comment]
@lukaseder, if you test with Eclipse with an existing project, be sure to always remove all eclipse config files before trying to re-import the project.

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/pull/5616

**Comment by lukaseder** [comment]
> @lukaseder, if you test with Eclipse with an existing project, be sure to always remove all eclipse config files before trying to re-import the project.

Hmm, I'm still unable to reproduce this issue. Note that this github repository is not the one I actually work with, it's just a clone. The actual repository has checked-in .classpath and other resources, so perhaps, I somehow inadvertently worked around the problem. I try to avoid m2e as much as I can, anyway...

But if it helps you, that's great!

**Comment by mstahv** [comment]
It does and I'm sure this change will make many people happier with jOOQ. I think the .classpath file is what configures the classpath in Eclipse, so if generated sources have already been defined there, there should be no issue. I tend to avoid adding IDE specific files (like the .classpath file by Eclipse) to SCM.

**Comment by lukaseder** [comment]
> I tend to avoid adding IDE specific files (like the .classpath file by Eclipse) to SCM.

I know I know :) But see, I never trust the IDE and once I (finally) get something to work, I want to replicate it to all machines. E.g. the `.settings` directory is another nice resource that can be useful in SCM.

But YMMV of course.
