### ISSUE TITLE
java.math.BigInteger should be generated for Oracle INTEGER columns

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5589]
Run these queries:

```sql
DROP TABLE t;
CREATE TABLE t (i INTEGER, n NUMBER);

INSERT INTO t (i, n)
VALUES (
  12345678901234567890.1234567890,
  12345678901234567890.1234567890);

SELECT *
FROM t;

SELECT column_name, data_type, data_precision, data_scale 
FROM user_tab_cols 
WHERE table_name = 'T';
```

To get:

```
I                       T
------------------------------------------------------ 
12345678901234567890	12345678901234567890.123456789
```

And

```
COLUMN_NAME  DATA_TYPE  DATA_PRECISION  DATA_SCALE
I            NUMBER                     0
N            NUMBER
```

As can be seen, the artificial `INTEGER` type produces a `NUMBER(?, 0)` type, which should be mapped to `BigInteger`, not `BigDecimal`

This change will introduce a backwards incompatibility for some users, which means we won't port the fix to 3.8

**Comment by leoandru** [comment]
Could this be done for PostgreSQL NUMERIC(?, 0), Numeric(?) types?

**Comment by lukaseder** [comment]
@leoandru: Yes, sure. Will investigate soon. I've created a new issue for this: https://github.com/jOOQ/jOOQ/issues/5736
