### ISSUE TITLE
Add Field.containsIgnoreCase() to support Postgres' ILIKE operator

### ISSUE THREAD

**Issue by maxkremer** [jOOQ/jOOQ#5619]
Similar to #1423.

Would be good to have the convenience of wild card inclusion found in  'Field.contains()'  used with the  `ILIKE` operator from Postgres as in `Field.likeIgnoreCase()`

**Comment by lukaseder** [comment]
You're right, that would be consistent. Thank you very much for your suggestion.

I do wonder, though, if we shouldn't generally review these "ignore case" methods. The current implementation isn't really correct for most languages. Probably, we should use `COLLATE` clauses, instead...
