### ISSUE TITLE
Add support for PL/SQL TABLE and associative array types in Oracle 18c

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5620]
This feature request has been separated from the support for PL/SQL `RECORD` types, which are easier to implement (see https://github.com/jOOQ/jOOQ/issues/330) and serialise.

Tasks:

- [x] Add a new `org.jooq.AssociativeArrayRecord<K, V>` type, similar to the `ArrayRecord<E>` type. 
- [x] Add code generation support for associative arrays
- [x] Implement runtime support for `IN` parameters
- [x] Implement runtime support for `OUT` parameters

Test scenarios:

- [x] Everything below as `IN` and `OUT` parameter
- [x] Empty arrays
- [x] `NULL` valuse
  - [x] As scalar array elements
  - [x] As record array elements (we don't currently handle Oracle's `R1(R2(null), null) = R1(null, null)` semantics)
  - [x] As object array elements (we don't currently handle Oracle's `R1(R2(null), null) = R1(null, null)` semantics)
  - [x] As record components
- [x] Associative array IN/OUT parameters are mixed with other emulated IN/OUT parameters, such as 
  - [x] PL/SQL records
  - [x] `%ROWTYPE`
  - [x] `BOOLEAN`
- [x] Combinations of:
  - [x] Index by number / varchar
  - [x] Scalar values
  - [x] `PL/SQL RECORD` values
    - [x] Including nested records
  - [x] `%ROWTYPE` values
  - [x] SQL `OBJECT` type values
    - [x] Including nested objects
  - [x] ~`PL/SQL TABLE` values~ (probably not possible to support)
  - [x] ~SQL `TABLE` or `VARRAY` values~ (probably not possible to support)
  - [x] `PL/SQL BOOLEAN` values
  - [x] ~Attach converters to values~ (see https://github.com/jOOQ/jOOQ/issues/14127)
- [x] Oracle versions (we won't support this for 11g anymore, perhaps not even 12c, depending on how hard it is to emulate there)
  - [x] 21c
  - [x] 18c
  - [x] ~12c~

---

See also:
- https://github.com/jOOQ/jOOQ/issues/330
- https://github.com/jOOQ/jOOQ/issues/5849 (emulation in 11g and 12cR1)
- #7125 (code generation support)
- https://twitter.com/dmcghan/status/823951114492112896?s=03
- https://github.com/jOOQ/jOOQ/issues/13957

**Comment by lukaseder** [comment]
It's perfectly possible to do this through the use of `sys_refcursor` values:
https://twitter.com/lukaseder/status/798074593655357440

In 12c, the types can be fetched using the `TABLE(table_var)`  constructor in PL/SQL and then opened as a cursor in to a `sys_refcursor` variable.

In 11g, a workaround through a jOOQ-generated temp table (see tweet) might be possible.

Quite possibly, we won't support this feature in 11g, though.

**Comment by lukaseder** [comment]
Agh... I was too optimistic. As soon as any associative array, table, or varray contains PL/SQL RECORD, we're back to not being able to fetch it using SQL. :(

**Comment by lukaseder** [comment]
Here's how to discover the associative array index type:
http://stackoverflow.com/a/42118501/521799

**Comment by lukaseder** [comment]
Here's one solution to fetching a `TABLE OF <record> INDEX BY VARCHAR2` with a generated PL/SQL block:

```sql
DECLARE
  -- These types will be made available by the user
  TYPE r IS RECORD (a NUMBER(3), b VARCHAR2(50));
  TYPE t IS TABLE OF r INDEX BY VARCHAR2(50);
  
  -- These ref cursors are generated. One per column in the record
  cur1 sys_refcursor;
  cur2 sys_refcursor;
  
  -- These columns are generated. One per column in the record
  col1 dbms_sql.number_table;
  col2 dbms_sql.varchar2_table;
  
  -- The local reference to the table
  val  t;

  -- The associative array index type
  idx  VARCHAR2(50);

  -- The result loop value (used for col[N])
  i    PLS_INTEGER := 1;
BEGIN

  -- These assignments would be replaced by some PL/SQL procedure or function call
  val('a').a := 1;
  val('a').b := 'a';
  
  val('b').a := 2;
  val('b').b := 'b';
  
  -- The loop iterates over the resulting table and copies all values to the generated columns
  idx := val.FIRST;
  WHILE idx IS NOT NULL
  LOOP  
    col1(i) := val(idx).a;
    col2(i) := val(idx).b;
    i := i + 1;
    idx := val.NEXT(idx);
  END LOOP;
  
  -- Generated opening of cursors for each column individually
  OPEN cur1 FOR SELECT * FROM TABLE(col1);
  OPEN cur2 FOR SELECT * FROM TABLE(col2);

  -- Returning of each cursor individually
  dbms_sql.return_result(cur1);
  dbms_sql.return_result(cur2);
END;
/
```

The essence here is that we're using one `sys_refcursor` per column and return them from the PL/SQL block individually. There are a couple of alternatives, that might help make this work even on Oracle 11g:

- `dbms_sql.return_result` was added to 12c. We could use classic `? := cur[N]` assignment and OUT parameters instead
- `TABLE(col[N])` works with associative arrays from `dbms_sql` since Oracle 12c. We'd need SQL types to store the values locally, if we don't use that feature.

**Comment by lukaseder** [comment]
More research is needed in this area - also Oracle 12c ojdbc has added support for PL/SQL tables. 12cR1 supports only scalar types in PL/SQL tables, and only the values of an associative array. In 12cR2, there are plans of supporting also keys through a `Map<K, Struct>` type!

**Comment by lukaseder** [comment]
Indeed, the Oracle 12cR2 JDBC driver supports deserialising PL/SQL TABLE types and associative arrays. We'll implement this first and support the 11g and 12cR1 emulation later.

**Comment by knutwannheden** [comment]
I think associative array types (and also REF CURSOR in parameters) are now supported by the 19c JDBC driver.

**Comment by lukaseder** [comment]
I hadn't seen the `REF CURSOR` in parameters, which is great news. The emulation is hairy. Regarding associative array types, from how I understand the API, only `VARCHAR2` and `NUMBER` valued arrays are supported, not `RECORD` valued arrays, right?

But it would be great to support this, even if for 19c only. A number of existing jOOQ customers are waiting for this feature.

**Comment by knutwannheden** [comment]
So far I had really just read the headline and thus don't know any specifics. But it deserves some investigation.

**Comment by lukaseder** [comment]
As discussed in this issue here: https://github.com/jOOQ/jOOQ/issues/11768#issuecomment-884809998, it seems associative arrays still cannot be created using `OracleConnection.createARRAY()` or similar methods. While prepared statements have some means (deprecated by now) of creating and fetching associative arrays, I can't seem to find how to construct an object.

So, I'm going to investigate emulation possibilities now.

**Comment by lukaseder** [comment]
So, @phbreitbach, you will be pleased to hear that `OUT` parameters are now supported, including for a schema like this:

```sql
  TYPE pls_assoc_i_n IS TABLE OF NUMBER        INDEX BY PLS_INTEGER;
  TYPE pls_assoc_i_v IS TABLE OF VARCHAR2(50)  INDEX BY PLS_INTEGER;
  TYPE pls_assoc_i_r IS TABLE OF pls_r_t       INDEX BY PLS_INTEGER;
  TYPE pls_assoc_i_s IS TABLE OF pls_row_sub_t INDEX BY PLS_INTEGER;
  TYPE pls_assoc_i_o IS TABLE OF u_book_type   INDEX BY PLS_INTEGER;
  TYPE pls_assoc_i_t IS TABLE OF u_book_table  INDEX BY PLS_INTEGER;
  TYPE pls_assoc_v_n IS TABLE OF NUMBER        INDEX BY VARCHAR2(50);
  TYPE pls_assoc_v_v IS TABLE OF VARCHAR2(50)  INDEX BY VARCHAR2(50);
  TYPE pls_assoc_v_r IS TABLE OF pls_r_t       INDEX BY VARCHAR2(50);
  TYPE pls_assoc_v_s IS TABLE OF pls_row_sub_t INDEX BY VARCHAR2(50);
  TYPE pls_assoc_v_o IS TABLE OF u_book_type   INDEX BY VARCHAR2(50);
  TYPE pls_assoc_v_t IS TABLE OF u_book_table  INDEX BY VARCHAR2(50);
  
  TYPE pls_r_nested3 IS RECORD (
    n1 NUMBER,
    n2 NUMBER
  );
  
  TYPE pls_r_nested2 IS RECORD (
    nested1 pls_r_nested3,
    n1 NUMBER,
    nested2 pls_r_nested3
  );
  
  TYPE pls_r_nested1 IS RECORD (
    n1 NUMBER,
    nested1 pls_r_nested2,
    n2 NUMBER,
    nested2 pls_r_nested2,
    n3 NUMBER
  );
  
  TYPE pls_u_nested IS RECORD (
    n1 NUMBER,
    nested1 u_nested_1,
    n2 NUMBER
  );
  
  TYPE pls_assoc_i_nested IS TABLE OF pls_r_nested1 INDEX BY PLS_INTEGER;
  TYPE pls_assoc_v_nested IS TABLE OF pls_r_nested1 INDEX BY VARCHAR2(50);

  PROCEDURE p_assoc_all (
    p_1 IN NUMBER,
    p_in OUT pls_assoc_i_n,
    p_iv OUT pls_assoc_i_v,
    p_ir OUT pls_assoc_i_r,
    p_io OUT pls_assoc_i_o,
    p_inested OUT pls_assoc_i_nested,
    p_2 IN OUT NUMBER,
    p_vn OUT pls_assoc_v_n,
    p_vv OUT pls_assoc_v_v,
    p_vr OUT pls_assoc_v_r,
    p_vo OUT pls_assoc_v_o,
    p_vnested OUT pls_assoc_v_nested,
    p_3 OUT NUMBER
  );
```

There's now a fun emulation like this that manages to properly serialise all out parameters via individual collections:

```sql
declare
  "a2" "TEST"."PLS_OBJECTS"."PLS_ASSOC_I_N";
  "e2" number(10);
  "i2" pls_integer := 1;
  "k2" DBMS_SQL.NUMBER_TABLE;
  "v2" DBMS_SQL.NUMBER_TABLE;
  "a3" "TEST"."PLS_OBJECTS"."PLS_ASSOC_I_V";
  "e3" number(10);
  "i3" pls_integer := 1;
  "k3" DBMS_SQL.NUMBER_TABLE;
  "v3" DBMS_SQL.VARCHAR2_TABLE;
  "a4" "TEST"."PLS_OBJECTS"."PLS_ASSOC_I_R";
  "e4" number(10);
  "i4" pls_integer := 1;
  "k4" DBMS_SQL.NUMBER_TABLE;
  "v41" DBMS_SQL.NUMBER_TABLE;
  "a5" "TEST"."PLS_OBJECTS"."PLS_ASSOC_I_O";
  "e5" number(10);
  "i5" pls_integer := 1;
  "k5" DBMS_SQL.NUMBER_TABLE;
  "v51" DBMS_SQL.NUMBER_TABLE;
  "v52" DBMS_SQL.VARCHAR2_TABLE;
  "a6" "TEST"."PLS_OBJECTS"."PLS_ASSOC_I_NESTED";
  "e6" number(10);
  "i6" pls_integer := 1;
  "k6" DBMS_SQL.NUMBER_TABLE;
  "v61" DBMS_SQL.NUMBER_TABLE;
  "v6211" DBMS_SQL.NUMBER_TABLE;
  "v6212" DBMS_SQL.NUMBER_TABLE;
  "v622" DBMS_SQL.NUMBER_TABLE;
  "v6231" DBMS_SQL.NUMBER_TABLE;
  "v6232" DBMS_SQL.NUMBER_TABLE;
  "v63" DBMS_SQL.NUMBER_TABLE;
  "v6411" DBMS_SQL.NUMBER_TABLE;
  "v6412" DBMS_SQL.NUMBER_TABLE;
  "v642" DBMS_SQL.NUMBER_TABLE;
  "v6431" DBMS_SQL.NUMBER_TABLE;
  "v6432" DBMS_SQL.NUMBER_TABLE;
  "v65" DBMS_SQL.NUMBER_TABLE;
  "a8" "TEST"."PLS_OBJECTS"."PLS_ASSOC_V_N";
  "e8" varchar2(4000);
  "i8" pls_integer := 1;
  "k8" DBMS_SQL.VARCHAR2_TABLE;
  "v8" DBMS_SQL.NUMBER_TABLE;
  "a9" "TEST"."PLS_OBJECTS"."PLS_ASSOC_V_V";
  "e9" varchar2(4000);
  "i9" pls_integer := 1;
  "k9" DBMS_SQL.VARCHAR2_TABLE;
  "v9" DBMS_SQL.VARCHAR2_TABLE;
  "a10" "TEST"."PLS_OBJECTS"."PLS_ASSOC_V_R";
  "e10" varchar2(4000);
  "i10" pls_integer := 1;
  "k10" DBMS_SQL.VARCHAR2_TABLE;
  "v101" DBMS_SQL.NUMBER_TABLE;
  "a11" "TEST"."PLS_OBJECTS"."PLS_ASSOC_V_O";
  "e11" varchar2(4000);
  "i11" pls_integer := 1;
  "k11" DBMS_SQL.VARCHAR2_TABLE;
  "v111" DBMS_SQL.NUMBER_TABLE;
  "v112" DBMS_SQL.VARCHAR2_TABLE;
  "a12" "TEST"."PLS_OBJECTS"."PLS_ASSOC_V_NESTED";
  "e12" varchar2(4000);
  "i12" pls_integer := 1;
  "k12" DBMS_SQL.VARCHAR2_TABLE;
  "v121" DBMS_SQL.NUMBER_TABLE;
  "v12211" DBMS_SQL.NUMBER_TABLE;
  "v12212" DBMS_SQL.NUMBER_TABLE;
  "v1222" DBMS_SQL.NUMBER_TABLE;
  "v12231" DBMS_SQL.NUMBER_TABLE;
  "v12232" DBMS_SQL.NUMBER_TABLE;
  "v123" DBMS_SQL.NUMBER_TABLE;
  "v12411" DBMS_SQL.NUMBER_TABLE;
  "v12412" DBMS_SQL.NUMBER_TABLE;
  "v1242" DBMS_SQL.NUMBER_TABLE;
  "v12431" DBMS_SQL.NUMBER_TABLE;
  "v12432" DBMS_SQL.NUMBER_TABLE;
  "v125" DBMS_SQL.NUMBER_TABLE;
begin
  "TEST"."PLS_OBJECTS"."P_ASSOC_ALL" (
    "P_1" => 1, 
    "P_IN" => "a2", 
    "P_IV" => "a3", 
    "P_IR" => "a4", 
    "P_IO" => "a5", 
    "P_INESTED" => "a6", 
    "P_2" => ?, 
    "P_VN" => "a8", 
    "P_VV" => "a9", 
    "P_VR" => "a10", 
    "P_VO" => "a11", 
    "P_VNESTED" => "a12", 
    "P_3" => ?
  );
  "e2" := "a2".first;
  while "e2" is not null loop
    "k2"("i2") := "e2";
    "v2"("i2") := "a2"("e2");
    "i2" := "i2" + 1;
    "e2" := "a2".next("e2");
  end loop;
  ? := "k2";
  ? := "v2";
  "e3" := "a3".first;
  while "e3" is not null loop
    "k3"("i3") := "e3";
    "v3"("i3") := "a3"("e3");
    "i3" := "i3" + 1;
    "e3" := "a3".next("e3");
  end loop;
  ? := "k3";
  ? := "v3";
  "e4" := "a4".first;
  while "e4" is not null loop
    "k4"("i4") := "e4";
    "v41"("i4") := "a4"("e4")."A";
    "i4" := "i4" + 1;
    "e4" := "a4".next("e4");
  end loop;
  ? := "k4";
  ? := "v41";
  "e5" := "a5".first;
  while "e5" is not null loop
    "k5"("i5") := "e5";
    "v51"("i5") := "a5"("e5")."ID";
    "v52"("i5") := "a5"("e5")."TITLE";
    "i5" := "i5" + 1;
    "e5" := "a5".next("e5");
  end loop;
  ? := "k5";
  ? := "v51";
  ? := "v52";
  "e6" := "a6".first;
  while "e6" is not null loop
    "k6"("i6") := "e6";
    "v61"("i6") := "a6"("e6")."N1";
    "v6211"("i6") := "a6"("e6")."NESTED1"."NESTED1"."N1";
    "v6212"("i6") := "a6"("e6")."NESTED1"."NESTED1"."N2";
    "v622"("i6") := "a6"("e6")."NESTED1"."N1";
    "v6231"("i6") := "a6"("e6")."NESTED1"."NESTED2"."N1";
    "v6232"("i6") := "a6"("e6")."NESTED1"."NESTED2"."N2";
    "v63"("i6") := "a6"("e6")."N2";
    "v6411"("i6") := "a6"("e6")."NESTED2"."NESTED1"."N1";
    "v6412"("i6") := "a6"("e6")."NESTED2"."NESTED1"."N2";
    "v642"("i6") := "a6"("e6")."NESTED2"."N1";
    "v6431"("i6") := "a6"("e6")."NESTED2"."NESTED2"."N1";
    "v6432"("i6") := "a6"("e6")."NESTED2"."NESTED2"."N2";
    "v65"("i6") := "a6"("e6")."N3";
    "i6" := "i6" + 1;
    "e6" := "a6".next("e6");
  end loop;
  ? := "k6";
  ? := "v61";
  ? := "v6211";
  ? := "v6212";
  ? := "v622";
  ? := "v6231";
  ? := "v6232";
  ? := "v63";
  ? := "v6411";
  ? := "v6412";
  ? := "v642";
  ? := "v6431";
  ? := "v6432";
  ? := "v65";
  "e8" := "a8".first;
  while "e8" is not null loop
    "k8"("i8") := "e8";
    "v8"("i8") := "a8"("e8");
    "i8" := "i8" + 1;
    "e8" := "a8".next("e8");
  end loop;
  ? := "k8";
  ? := "v8";
  "e9" := "a9".first;
  while "e9" is not null loop
    "k9"("i9") := "e9";
    "v9"("i9") := "a9"("e9");
    "i9" := "i9" + 1;
    "e9" := "a9".next("e9");
  end loop;
  ? := "k9";
  ? := "v9";
  "e10" := "a10".first;
  while "e10" is not null loop
    "k10"("i10") := "e10";
    "v101"("i10") := "a10"("e10")."A";
    "i10" := "i10" + 1;
    "e10" := "a10".next("e10");
  end loop;
  ? := "k10";
  ? := "v101";
  "e11" := "a11".first;
  while "e11" is not null loop
    "k11"("i11") := "e11";
    "v111"("i11") := "a11"("e11")."ID";
    "v112"("i11") := "a11"("e11")."TITLE";
    "i11" := "i11" + 1;
    "e11" := "a11".next("e11");
  end loop;
  ? := "k11";
  ? := "v111";
  ? := "v112";
  "e12" := "a12".first;
  while "e12" is not null loop
    "k12"("i12") := "e12";
    "v121"("i12") := "a12"("e12")."N1";
    "v12211"("i12") := "a12"("e12")."NESTED1"."NESTED1"."N1";
    "v12212"("i12") := "a12"("e12")."NESTED1"."NESTED1"."N2";
    "v1222"("i12") := "a12"("e12")."NESTED1"."N1";
    "v12231"("i12") := "a12"("e12")."NESTED1"."NESTED2"."N1";
    "v12232"("i12") := "a12"("e12")."NESTED1"."NESTED2"."N2";
    "v123"("i12") := "a12"("e12")."N2";
    "v12411"("i12") := "a12"("e12")."NESTED2"."NESTED1"."N1";
    "v12412"("i12") := "a12"("e12")."NESTED2"."NESTED1"."N2";
    "v1242"("i12") := "a12"("e12")."NESTED2"."N1";
    "v12431"("i12") := "a12"("e12")."NESTED2"."NESTED2"."N1";
    "v12432"("i12") := "a12"("e12")."NESTED2"."NESTED2"."N2";
    "v125"("i12") := "a12"("e12")."N3";
    "i12" := "i12" + 1;
    "e12" := "a12".next("e12");
  end loop;
  ? := "k12";
  ? := "v121";
  ? := "v12211";
  ? := "v12212";
  ? := "v1222";
  ? := "v12231";
  ? := "v12232";
  ? := "v123";
  ? := "v12411";
  ? := "v12412";
  ? := "v1242";
  ? := "v12431";
  ? := "v12432";
  ? := "v125";
end;
```

It would obviously be better if we didn't have to flatten the associative arrays, but:

1. It seems only simple arrays with scalar values (i.e. non-records) can be read using ojdbc directly, e.g. `DBMS_SQL.NUMBER_TABLE`.
2. I still can't seem to be able to *write* such arrays as in-parameters.
3. Even so, if the array values are `RECORD`, `%ROWTYPE`, or anything other more sophisticated, the ojdbc driver doesn't seem to help.

I'll continue working on this to implement the remaining missing features, including:

- `IN` parameter support
- Nesting tables
- Other edge cases, such as e.g. `BOOLEAN` values.

**Comment by lukaseder** [comment]
Remaining failing tests in the @phbreitbach MCVE: https://github.com/phbreitbach/jOOQ-mcve (due to missing `IN` parameter support):

```
Tests in error:
  arrayAsInOutParamTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 1
  arrayAsInOutParamRowTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 1
  arrayAsInParamTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 1
  arrayAsInRowParamTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 1
  arrayAsInOutNocopyParamTest(org.jooq.mcve.test.java.JavaTest): SQL [null]; Error while writing value at JDBC bind index: 1

Tests run: 7, Failures: 0, Errors: 5, Skipped: 0
```

**Comment by lukaseder** [comment]
Note the emulation is targeted at Oracle 12c. In 18c, reading associative arrays has much better support. I'll investigate this with the next increments.

**Comment by lukaseder** [comment]
This issue wasn't closed at the time the partial feature implementation has shipped in jOOQ 3.16+. So far, associative array `OUT` parameters are supported. `IN` and `IN OUT` parameters haven't been supported yet. They will be in jOOQ 3.18, see also: https://github.com/jOOQ/jOOQ/issues/13957

**Comment by lukaseder** [comment]
Clearly, nested `TABLE` types can't be serialised yet...

**Comment by lukaseder** [comment]
I've removed 12c from the list of Oracle versions for which we'll support these features. The current implementations tend to depend on the fact that e.g. PL/SQL `TABLE` types can be bound as ordinary arrays, as well as PL/SQL `RECORD` types can be bound as ordinary UDTs.

**Comment by lukaseder** [comment]
I'm closing this feature here. jOOQ 3.18 will finally officially support PL/SQL associative arrays, and document this support. Additional future work (new faeture support, bugfixes) will be implemented in separate issues.
