### ISSUE TITLE
Add runtime support for PL/SQL RECORD types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5627]
After #330 (code generation support for PL/SQL `RECORD` types), this will now also support them in the runtime library.

The following combinations need to be integration tested:

- Mixing `IN`, `IN/OUT`, `OUT`, and function return values
- Nesting `RECORD` types in `RECORD` types
- Mixing `RECORD` parameters with ordinary scalar parameters 
- Mixing `RECORD` parameters with `OBJECT` parameters 
- Nesting `OBJECT` types in `RECORD` types
- `%rowtype` records, which are really anonymous records

----
See also #330

**Comment by lukaseder** [comment]
@DiabolusExMachina This is looking good for jOOQ 3.9. Would you be interested in beta testing this version? I'd be curious about your most complicated `RECORD` type / procedure / edge cases...

**Comment by DiabolusExMachina** [comment]
@lukaseder Yes that would great!

**Comment by lukaseder** [comment]
OK, great, thank you very much! I'll be in touch soon
