### ISSUE TITLE
Regression when reading PostgreSQL bytea[] type

### ISSUE THREAD

**Issue by tomdcc** [jOOQ/jOOQ#5633]
Hi

This worked up to 3.8.4 but broke in 3.8.5.

If we return an array of postgres bytea objects, in the returned `byte[][]` instead of the actual byte data, we get the `\x` encoded form which has then been turned into bytes. So if returning `ARRAY [ 'hi'::bytea ]`, instead of getting the equivalent of `"hi".getBytes()` as the element in the array, we get the equivalent of `"\\x6869".getBytes()`.

Test case here: https://gist.github.com/tomdcc/52a7e572a4a8fd2082e081bf94cf2397

Cheers

**Comment by lukaseder** [comment]
Thank you very much for reporting. We certainly don't have any integration tests right now that covers `byte[][]` or `bytea[]` types, so this has gone unnoticed in the patch release.

Will investigate immediately. One of these fixes might be at fault:

- https://github.com/jOOQ/jOOQ/commit/a14e3b5032d49c7f46261edcc101a32acb553360
- https://github.com/jOOQ/jOOQ/commit/8eb73b418032f6dbd6be445c7b92200c6eb0d7f3#diff-ae2560e6f61daf3b89fc5bcfafa285fb

**Comment by lukaseder** [comment]
It's the first one:

- https://github.com/jOOQ/jOOQ/commit/a14e3b5032d49c7f46261edcc101a32acb553360

**Comment by lukaseder** [comment]
Hmm, the regression exposes a bigger flaw in the way PostgreSQL arrays are deserialised by jOOQ in `org.jooq.impl.DefaultBinding.pgGetArray()`. There are some related issues here:

- https://github.com/jOOQ/jOOQ/issues/5613
- https://github.com/jOOQ/jOOQ/pull/5586

I suspect there is actually an issue in (or misunderstanding on my side about) the PostgreSQL JDBC driver when deserialising `bytea[]` types. The behaviour of `ResultSet.getArray().getArray()` differs from `ResultSet.getArray().getResultSet()`. The former produces an `Object[]` containing `PGobject` wrappers (which contain the `\x` encoding), whereas the latter produces the expected `byte[][]`.

**Comment by lukaseder** [comment]
@tomdcc: There's a fix here: 

- 3.9.0: https://github.com/jOOQ/jOOQ/commit/9596aa9c2e34957885a98eb1898a28386e927dc1
- 3.8.6: https://github.com/jOOQ/jOOQ/commit/181dedd5e55e787f47289c33e8a6d6806cf8d803

Would you be interested in confirming that the fix applied to the 3.8 branch works for you? If so, I'll release 3.8.6 this week.

**Comment by tomdcc** [comment]
@lukaseder tested against 3.8.0 branch, tests passed! Thanks for the quick turnaround!

**Comment by lukaseder** [comment]
Thanks a lot for the feedback. I'll release 3.8.6 tomorrow

**Comment by lukaseder** [comment]
Version 3.8.6 is released to the [website](http://www.jooq.org/download/versions) and should be available to Maven Central within the next 1-2 hours

**Comment by etiennestuder** [comment]
Awesome. Thanks for the quick fix, @lukaseder !
