### ISSUE TITLE
Add support for PostgreSQL ON CONFLICT DO UPDATE WHERE

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5637]
The `WHERE` clause is not yet supported as of #5297

In fact, `INSERT .. ON DUPLICATE KEY IGNORE` could be emulated using this in jOOQ, rather than the more complicated `INSERT .. SELECT .. EXISTS`

----
See also:
- #5297
- https://www.postgresql.org/docs/9.5/static/sql-insert.html

**Comment by dano** [comment]
I was just looking for this functionality. Glad to see it's on the radar for 3.10.0.
