### ISSUE TITLE
Add DSL.localDateAdd() localDateSub(), localDateDiff()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5645]
These would work the same way as `DSL.dateAdd()`, `DSL.dateSub()`, `DSL.dateDiff()`, except that they operate on `LocalDate` instead of `java.sql.Date`

**Comment by bitbrain** [comment]
Preparing a Pull Request right now. @lukaseder you are okay with that or is there already work on this?

**Comment by lukaseder** [comment]
Sure, thank you very much for your offer, @bitbrain. May I just ask you to read this first and sign the transfer of rights agreement linked from the document:
https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

**Comment by lukaseder** [comment]
Fixed this, partially taking over @bitbrain's PR #6215. There's still content missing, namely working with timestamps / local date time, which has been extracted into a new issue: https://github.com/jOOQ/jOOQ/issues/6220.
