### ISSUE TITLE
CTE and multiple select

### ISSUE THREAD

**Issue by dmiorandi** [jOOQ/jOOQ#5654]
in a CTE (I don't know if only here) when I try to use multiple select only last one is taken into account.

so
```java
.with(q).as(
      select(f1,f2,...).from(x)
)
.select(x.fields())
.select(onemorefield)
.from(q)
```

only onemorefield is printed in query. First select completly ignored. By your github posts should work.
Probably this is due to jooq doesn't know fields in "q" because q is a generic Record?

**Comment by dmiorandi** [comment]
ok found is exactly what I suspect. Creating an array of fields and reusing it in both first select and main select it works. My bad. This is not a bug.

**Comment by lukaseder** [comment]
OK, glad you found the source, thanks for following up.
