### ISSUE TITLE
generate not working when using jooq-codegen-gradle

### ISSUE THREAD

**Issue by SidneyXu** [jOOQ/jOOQ#5680]
I follow the [README.md](https://github.com/jOOQ/jOOQ/blob/master/jOOQ-examples/jOOQ-codegen-gradle/README.md) and want to generate pojos

```groovy
def writer = new StringWriter()
def xml = new groovy.xml.MarkupBuilder(writer)
.configuration('xmlns': 'http://www.jooq.org/xsd/jooq-codegen-3.6.0.xsd') {
    jdbc() {
        driver('org.h2.Driver')
        url('jdbc:h2:~/test-gradle')
        user('sa')
        password('')
    }
    generator() {
        database() {
        }
        generate() {
         // add this
          pojos(true)
        }
        target() {
            packageName('org.jooq.example.gradle.db')
            directory('src/main/java')
        }
    }
}

println writer.toString()
```

but  it not working, console outpus

```xml
<database>
</database>
<pojos>true</pojos>
<target>
...
</target>
```

it maybe a mistake of `MarkupBuilder`，but when i change to `generate('')` it take effect

**Comment by lukaseder** [comment]
Thank you very much for your message. We should definitely fix our example to use the third party Gradle plugin instead, which we usually recommend using:
https://github.com/etiennestuder/gradle-jooq-plugin

The problem you're running into is documented here:
https://groups.google.com/d/msg/jooq-user/wi4S9rRxk4A/ROopvY2SAAAJ

Hope this helps
