### ISSUE TITLE
Add MockFileDatabase.nullLiteral() allowing to override the null literal in DSLContext.fetchFromTXT()

### ISSUE THREAD

**Issue by samy-deghou** [jOOQ/jOOQ#5681]
Currently, column types are not supported in the file-based MockDataProvider feature.
The `MockFileDatabase` class is indeed marked as experimental so column types appears to be an advanced feature, however, `NULL` values (as illustrated in the table below) are considered as strings ("NULL"). This seems to be an important point to be solved ?

Maybe this could be a first place to start with if we are to consider column types ?

> ```
> select * from substanceForAllDocIDs;
> +--------+---------------+-----------+
> | docID  | substanceName | EStanceID |
> +------------------------------------+
> | sm_msi | NULL          | Al-Nb-Ni  |
> | sm_msi | NULL          | Al-Nb-Ni  |
> +------------------------------------+
> @ rows: 2
> ```

**Comment by lukaseder** [comment]
Thank you very much for your feedback. The current implementation of the `MockFileDatabase` redirects parsing to [`DSLContext.fetchFromTXT()`](http://www.jooq.org/javadoc/latest/org/jooq/DSLContext.html#fetchFromTXT-java.lang.String-) using the default `NULL` encoding: `{null}` (i.e. the same default that is applied when formatting a result through `Result.format()`).

We should probably provide options to override this default in the `MockFileDatabase`, as `fetchFromTXT()` also allows for overriding it.

I'll change this feature request here to the addition of such a flag.

**Comment by samy-deghou** [comment]
great thanks !

**Comment by lukaseder** [comment]
This was, in fact, implemented incorrectly. We'll fix this in a later version: #8125
