### ISSUE TITLE
jOOQ generated code contains deprecated calls

### ISSUE THREAD

**Issue by jhyot** [jOOQ/jOOQ#5697]
jOOQ generates code for me that results in deprecation warnings from the Java compiler. It would be nice if the generated code does not call deprecated methods.

The generated code looks like this:
```
public class SdoOrdinateArrayRecord extends ArrayRecordImpl<BigDecimal> {

    private static final long serialVersionUID = -38852139;

    /**
     * Create a new <code>MDSYS.SDO_ORDINATE_ARRAY</code> record
     */
    public SdoOrdinateArrayRecord() {
        super(Mdsys.MDSYS, "SDO_ORDINATE_ARRAY", org.jooq.impl.SQLDataType.NUMERIC);
    }

    /**
     * Create a new <code>MDSYS.SDO_ORDINATE_ARRAY</code> record
     */
    public SdoOrdinateArrayRecord(BigDecimal... array) {
        this();
        set(array);   // <--- WARNING HERE
    }

    /**
     * Create a new <code>MDSYS.SDO_ORDINATE_ARRAY</code> record
     */
    public SdoOrdinateArrayRecord(Collection<? extends BigDecimal> collection) {
        this();
        set(collection);  // <-- WARNING HERE
    }
}
```

And the warnings are:

> Warning:(44, 9) java: set(T...) in org.jooq.impl.ArrayRecordImpl has been deprecated
> Warning:(52, 9) java: set(java.util.Collection<? extends T>) in org.jooq.impl.ArrayRecordImpl has been deprecated

I have marked the line numbers in the source above.

Just for good measure, I have the deprecated flag set to false in the codegen config:
```
<generator>
  <generate>
    <deprecated>false</deprecated>
  </generate>
</generator>
```

**Comment by lukaseder** [comment]
Thank you very much for reporting this. You're right, that warning also appears in our integration tests - not sure why it wasn't reported in Eclipse.
