### ISSUE TITLE
Add support for PostgreSQL ON CONFLICT .. DO NOTHING

### ISSUE THREAD

**Issue by fleroy84** [jOOQ/jOOQ#5699]
Hello,

Postgresql 9.5 allows one to specify one field for instruction "on conflict … do ignore".

In class "InsertQueryImpl" in the 3.9.0-SNAPSHOT version, I can see that in case of an "on conflict … do update" case, fields can be passed as parameters to build the SQL query but not for the "on conflict … do ignore" case. 

In my project, I have a table with a PK and a column with a unique constraint.
When I use the instruction  "on conflict … do ignore", both constraints are checked because jOOQ does not specify any field. As a result, Postgresql 9.5 checks every field with a unique constraint.
I want to specify the field on which the constraint will be verified.

I would like, if possible, something like : 

getDslContext()
      .insertInto([myTable])
      .set([myRecord])
      .onConflict([myField])
      .doIgnore())

Thank you.

**Comment by lukaseder** [comment]
Oh, interesting. I think we've overlooked that clause when `ON CONFLICT` was implemented. That's certainly worth adding, especially since we already have a synthetic `onDuplicateKeyIgnore()` clause.

Thanks for the suggestion.

**Comment by safaci2000** [comment]
+1 on this feature. I thought it was already implemented. It's a must have for me as well.
