### ISSUE TITLE
Add option to disable code generation of comments

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5703]
Different flags should allow for disabling the generation of comments on:

- Tables
- Columns
- Attributes
- Procedures
- etc.

**Comment by michael-simons** [comment]
Thanks Lukas!
The following use case appeared:

```sql
comment on column blub.x is 'y -> something';
```

leads to a JavaDoc 

```
 /**
  * The column <code>BLUB.X</code>. y -> something
  */
// ...
```

The Java 8 JavaDoc compiler rejects this with "error: bad use of '>'"

Which is actually another ticket I'm gonna create right away.

**Comment by lukaseder** [comment]
Oh wow, thanks for letting us know! This looks like some XSS vulnerability in jOOQ generated Javadoc :/ (well, it takes a special kind of evil to put malicious HTML code in an Oracle column comment...)

**Comment by michael-simons** [comment]
Who would ever think of such an evil thing?! ;)

**Comment by lukaseder** [comment]
I don't know. But I'm paranoid (as I have some security background)
