### ISSUE TITLE
Escape HTML characters in generated JavaDoc

### ISSUE THREAD

**Issue by michael-simons** [jOOQ/jOOQ#5704]
If a database comment contains certain characters like `<` and `>`, the JavaDoc compiler rejects them with an error, for example:

```sql
comment on column blub.x is 'y -> something';
```

leads to a JavaDoc 

```
 /**
  * The column <code>BLUB.X</code>. y -> something
  */
// ...
```

The error is "error: bad use of '>'"

You can generate the JavaDoc in a Maven project with mvn javadoc:javadoc or it is automatic generated with the release plugin.

See #5703

**Comment by lukaseder** [comment]
Thank you very much for reporting. We'll fix this ASAP
