### ISSUE TITLE
Code generator's <recordVersionFields/> setting does not match column

### ISSUE THREAD

**Issue by gadieichhorn** [jOOQ/jOOQ#5706]
Using 3.8.6
Maven 3.3
JDK 1.8

I am trying to generate VERSION column optimistic locking

migration done with flyway

```
create table ENTITY (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    VERSION INTEGER NOT NULL,

    PRIMARY KEY (ID)
}
```

my settings (in pom plugin)
```
                    <generator>
                        <name>org.jooq.util.DefaultGenerator</name>
                        <database>
                            <name>org.jooq.util.h2.H2Database</name>
                            <includes>.*</includes>
                            <excludes>SCHEMA_VERSION</excludes>
                            <recordVersionFields>VERSION</recordVersionFields>
                            <schemata>
                                <schema>
                                    <inputSchema>test</inputSchema>
                                </schema>
                            </schemata>
                        </database>
                        <generate>
                            <daos>true</daos>
                            <fluentSetters>true</fluentSetters>
                        </generate>
                        <target>
                            <packageName>com.model</packageName>
                            <directory>target/generated-sources/jooq</directory>
                        </target>
                    </generator>
```

I dont see any difference in generated code to indicate the version is handled by JOOQ...

thanks.

**Comment by lukaseder** [comment]
All of the jOOQ code generator configuration's regular expressions are case-sensitive by default. You can make them insensitive by wrapping them in `(?i:...)`. I remember that Flyway creates a lower-case, case sensitive `"schema_version"` table even in databases where the default case is upper case (like H2).

I guess the fix in your case will be any of these:

```xml
                            <excludes>(?i:SCHEMA_VERSION)</excludes>
```

or

```xml
                            <excludes>schema_version</excludes>
```

**Comment by lukaseder** [comment]
I'm sorry, I opened the wrong question :) You should see a `getRecordVersion()` method in your generated table. Is it not there?

**Comment by gadieichhorn** [comment]
Yes, I plan to write some tests to prove it works properly when the version value is not defined in INSERT queries.

the Table
```
public class Dictionary extends TableImpl<DictionaryRecord> {

  public final TableField<DictionaryRecord, Integer> VERSION = createField("VERSION",   org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
```

```
   @Override
    public TableField<DictionaryRecord, Integer> getRecordVersion() {
        return VERSION;
    }
```
   
I would expect the POJO constructor to emit the version as it is handled automatically... what do you think?

```
 public Dictionary(
        Long    id,
        Integer version,    
       ...
    ) {
        this.id = id;
        this.version = version;
   ...
}
```

**Comment by gadieichhorn** [comment]
I am attempting to insert a row without the version value...

testThatCanQueryTheDatabaseWithJooqDSLContext[0](com.rds.observato.data.jdbc.model.JooqDSLTest)  Time elapsed: 0.364 sec  <<< ERROR!
org.jooq.exception.DataAccessException: SQL [insert into "observato"."DICTIONARY" ("NAME", "VALUE") values (?, ?)]; **NULL not allowed for column "VERSION"; SQL statement:**

**Comment by lukaseder** [comment]
OK, so code generation works, right? And you're running an `INSERT` query through the jOOQ API? Or through `UpdatableRecord.store()`? Because currently, optimistic locking is implemented only for the latter, i.e. for `UpdatableRecord` operations.

**Comment by gadieichhorn** [comment]
The code generation works, thanks! 👍 

SUCCESS! thanks for your support

```
        DictionaryRecord data = dsl.newRecord(Dictionary.DICTIONARY);
        int store = data.setKey(UUID.randomUUID().toString()).setName("name").setValue("value").store();
        assertThat("insert one DICTIONARY record", store, is(1));

```

**Comment by lukaseder** [comment]
Thanks for the feedback.
