### ISSUE TITLE
Function delegates window RANGE calls to ROWS

### ISSUE THREAD

**Issue by bkrieger** [jOOQ/jOOQ#5708]
In Function.java, the `range...` functions call `windowSpecification.rows...`, when they should be calling `windowSpecification.range...`.

See https://github.com/bkrieger/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/impl/Function.java#L737

**Comment by lukaseder** [comment]
This issue is "duplicated" by PR https://github.com/jOOQ/jOOQ/pull/5707

**Comment by bkrieger** [comment]
Thanks a lot! Was still verifying with my company whether I was asked to
sign the forms, so probably easier this way.

**Comment by lukaseder** [comment]
@bkrieger: Yeah, I understand. These legal things are a pain, unfortunately...
