### ISSUE TITLE
Change <javaTimeTypes/> default value to "true"

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5714]

**Comment by abhrj** [comment]
Hi!

Is it not `true` by default yet? 

I performed code generation on a new project with latest jooq and latest postgresql driver, and jooq has generated `java.time.OffsetDateTime` fields instead of `java.sql.Timestamp`.

**Comment by lukaseder** [comment]
@abhrj It is not true by default, indeed. But if you're using `TIMESTAMPTZ` data types in your database, since there is no representation for that type in the `java.sql` module, the `java.time` module types are generated nonetheless.
