### ISSUE TITLE
Is jooq support to add custom hints in front of Select?

### ISSUE THREAD

**Issue by yifanyou** [jOOQ/jOOQ#5731]
db:mysql
Like this:
/*balance*/ select * from xxx

If not, is there some simple solutions?

thx

**Comment by lukaseder** [comment]
There's a `.hint()` clause that you can add right after the `.select()` clause:

```java
select(A, B).hint("/* balance */") ...
```

The comment will not be inserted at the position that you've requested, it'll be added where Oracle / MySQL hints are expected to be placed:

```sql
SELECT /* balance */ A, B ...
```

If you really want to prepend a comment to a SQL statement, the best way forward would be to use an `ExecuteListener` and patch the generated SQL string accordingly. Let me know if you need help with that.
