### ISSUE TITLE
Add a configuration option for varargs setters

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5733]
The new generated varargs setters (https://github.com/jOOQ/jOOQ/issues/4164) should have been introduced with a new configuration option to avoid warnings in generated code.

See also @ben-manes's feedback on the mailing list:
https://groups.google.com/d/msg/jooq-user/zlDXGePK7e8/85Hdjo9aEAAJ

**Comment by etiennestuder** [comment]
@lukaseder A fix would be great since we are affected by that ;-)

**Comment by lukaseder** [comment]
@etiennestuder I'm curious: how are you affected?

**Comment by etiennestuder** [comment]
@lukaseder We make the file build on compiler warnings. So now the compile fails.

**Comment by lukaseder** [comment]
OK, I see. I've just had a similar case before: https://github.com/jOOQ/jOOQ/issues/5775#issuecomment-270889860.

Hmm, this is third-party generated code - so perhaps you could be a bit more lenient with the warnings on that?

**Comment by codeturner** [comment]
I'm seeing the same thing.  Unfortunately, it's polluting our previously clean list of java warnings in Eclipse, and violating our team policy.  And Eclipse doesn't allow you to disable this warning in generated code only, so we're ignoring them for now, but ... broken windows.

However, we're only seeing this for byte[] values.  I cannot think of a use case where a user of jooq would want to set the value of a byte[] by passing in a vararg list of individual bytes.

Can the generator simply not convert an array to varargs if the value type is a primitive?

**Comment by lukaseder** [comment]
OK, message received. This feature was a mistake :)

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.10. This will be merged to version 3.9.2 (https://github.com/jOOQ/jOOQ/issues/5861) hopefully next week.
