### ISSUE TITLE
Bad type mapping for PostgreSQL TIME[STAMP] WITH TIME ZONE and SQL Server DATETIMEOFFSET types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5734]
This should've been included with https://github.com/jOOQ/jOOQ/issues/4429

**Comment by deinspanjer** [comment]
So what is the current behavior of the code when mapping a TIMESTAMP WITH TIMEZONE through jOOQ? Is the resulting LocalDateTime the wall clock representation of the time in UTC or system local timezone?

If it is system local, will we have to explicitly convert it back to an OffsetDateTime using the system local timezone before working with it?

**Comment by lukaseder** [comment]
The current behaviour is that of the underlying JDBC driver. I would not rely on this and explicitly bind the type for the time being using a custom `Binding`

**Comment by lukaseder** [comment]
In fact, this isn't an "enhancement" but a bad pre-existing type mapping in `PostgresDataType` and `SQLServerDataType`, where the `time[stamp] with time zone` and `datetimeoffset` types were mapped to JDBC's `Time[stamp]` types.

Fixing this will make for an incompatible change, which is acceptable in 3.10. I'll still have to think about a possible workaround that can be merged to 3.9.1, without introducing a breaking change.

**Comment by devinrsmith** [comment]
Is this still slated for 3.10.0?

**Comment by lukaseder** [comment]
@devinrsmith : At the moment: Yes

**Comment by lukaseder** [comment]
This has been implemented for 3.10 on Jan 16. We won't backport this feature to the 3.9 versions as it introduces an incompatible change for pre-existing interpretations of these data types.

Users who want to upgrade to 3.10 and want to maintain `TIMESTAMP WITHOUT TIME ZONE` semantics can apply a forced type.
