### ISSUE TITLE
MockResultSet should call Converter to transform MockResult's <U> back to <T>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5771]
See also:
- http://stackoverflow.com/q/22205655/521799
- https://groups.google.com/forum/#!topic/jooq-user/dDWrILEqFzw

**Comment by an-cwi** [comment]
I'm running into an issue that seems to be related, despite not using generated models as the original poster(s) were. I have a custom data type (and converter) for Postgres' JSONB type, and while mocking I don't see why I need to deal with JSON serialization at all. The `MockResult` record contains the expected type (corresponding to `T` in `DataType<T>`), but I'm getting an exception saying that `String` can't be converted to `T`. It seems to be a result of the custom converter is being used to convert `T` to `String`, but `ConvertAll()` being used to attempt the reverse (`String` to `T`).

Between stepping through the code and looking at your fix for this ticket, it looks like a number of conversions are being done. I'm confused as to why conversion is needed at all for mock results? If the mock record contains the expected user type, shouldn't that be able to be fetched directly without any conversion?

I may be completely off base here, I've been staring at this for too long. Let me know if you need more details, and I can try to provide some code samples. Thanks.

**Comment by lukaseder** [comment]
@an-cwi Thanks for your message. I'm not sure if it is related to this issue. Could be. But ideally, may I ask you to create a new issue, possibly following our MCVE (Minimal, Complete, Verifiable Example) guidelines and template https://github.com/jOOQ/jOOQ-mcve

This will help us track down the problem and help you much more quickly.

**Comment by an-cwi** [comment]
Can I first get clarification about data type conversion with respect to mock results? Why is any conversion needed in the first place? Why does `MockResult` contain `<U>` (to reference the title of this ticket)?
I don't want to go to the work of creating an MCVE if I'm just completely misunderstanding the intended behaviour of jOOQ's result mocking or if this can be explored first with a simple question. Thanks.

**Comment by lukaseder** [comment]
> Why does MockResult contain <U> (to reference the title of this ticket)?

A `Result` contains `Field<U>` references with converters that have converted the database / JDBC type `<T>` to the user type `<U>`. `MockResultSet` is a lower level abstraction API, which has no notion of such a `<U>` type, it only knows JDBC types, so the value needs to be converted back to `<T>`.

**Comment by an-cwi** [comment]
Ok, I think there's still an issue when mocking a record containing a converted type field, but at this point I've been able to workaround the issue by using a "mock" data type which just represents the user type directly without using a custom binding/converter, essentially faking that the DB can store the user type directly. Unfortunately I don't have time to put together a whole new issue right now, though, sorry about that. Thanks for your timely responses.

**Comment by lukaseder** [comment]
No worries
