### ISSUE TITLE
Add support for ALTER TABLE .. RENAME COLUMN in MySQL

### ISSUE THREAD

**Issue by obirider** [jOOQ/jOOQ#5781]
When executing this statement

```java
context.alterTable("Log").renameColumn("comment").to("message").execute();
```

I get the following exception:

```
... java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'column `comment` to `message`' at line 1
Query is : alter table `Log` rename column `comment` to `message`
```

**Comment by lukaseder** [comment]
This is currently not supported for MySQL. The `@Support` annotation is wrong, it should exclude MySQL dialects.

**Comment by obirider** [comment]
> This is currently not supported for MySQL. The `@Support` annotation is wrong, it should exclude MySQL dialects.

Can you do that in the meantime?
Otherwise the issue is actually a defect and not an enhancement I think.

**Comment by lukaseder** [comment]
Thanks for pinging. I see that MySQL 8 added support for this syntax:
https://dev.mysql.com/worklog/task/?id=10761

This removes the difficulties of emulating it by making sure the exact column definition is re-createdin an `ALTER TABLE .. CHANGE` statement.

We'll include this in jOOQ 3.12

**Comment by lukaseder** [comment]
This should already work in MySQL 8 as the default implementation of the statement matches MySQL's syntax: https://github.com/jOOQ/jOOQ/blob/version-3.11.11/jOOQ/src/main/java/org/jooq/impl/AlterTableImpl.java#L828

**Comment by lukaseder** [comment]
I have created a separate issue for MySQL 5.7 support, but we are unlikely to prioritise it soon, as it is quite difficult to emulate: https://github.com/jOOQ/jOOQ/issues/9025
