### ISSUE TITLE
gradle jooq generate mixes identity names

### ISSUE THREAD

**Issue by rainoko** [jOOQ/jOOQ#5797]
In 3.9 jooq generate adds sometimes  into table class identity from keys with underscore but do not do this in Key class itself. So compiler fails because no underscored name in keys class.

Seems todo if package and table share the name.
Db is postgresql 9.3

**Comment by lukaseder** [comment]
This could be a duplicate of https://github.com/jOOQ/jOOQ/issues/5783.

Would you mind either:

- Checking #5783 to see if that's the same issue as yours
- Provide some steps to reproduce the issue in your case (e.g. some `DDL` and your code generator configuration)

**Comment by rainoko** [comment]
yes seems to be duplicate. I close this and will wait 3.9.1 to retry. If exists after that Ill reopen it again with small demo code.

**Comment by lukaseder** [comment]
Sounds like a plan, thank you!
