### ISSUE TITLE
jooq-codegen-3.9.0.xsd can only be downloaded via https

### ISSUE THREAD

**Issue by sargue** [jOOQ/jOOQ#5803]
The namespace is defined as:

http://www.jooq.org/xsd/jooq-codegen-3.9.0.xsd

Note the *http*. But if you try to load that you get HTTP 307 internal redirect to the HTTPS version.

I am a big fan of HTTPS everywhere but this breaks my IDE autocompletion. IDE bug? Don't know, the XSD references itself as http, not https.

![image](https://cloud.githubusercontent.com/assets/333808/22153315/1ea9fd0a-df27-11e6-9a60-12d78f91bfe0.png)

**Comment by lukaseder** [comment]
Hmm, you're right, thanks for reporting. We shouldn't redirect the XSD files...

**Comment by lukaseder** [comment]
Our hoster doesn't make it easy to prevent the redirect, I'm afraid.
