### ISSUE TITLE
Oracle types in package are not generated

### ISSUE THREAD

**Issue by DiabolusExMachina** [jOOQ/jOOQ#5814]
The jOOQ generator does not generate classes for types inside a package if only the package name is given. 

Given a package with the name "per_per". If I tell jOOQ to include this package in the code-generation with
```xml
<includes>per_per</includes>
```
It will create classes for all Stored Procedures inside the package. But the types in the package are ignored. 

This behavior stays exactly the same if I use this: 
```xml
<includes>per_per(\..*)?</includes>
```

Only if I add each type with name then jOOQ will generate classes. 
```xml
<includes>per_per
| TYPE_NAME1
| TYPE_NAME2
|...
</includes>
```

I think it would be a great improvement if I only had to specifiy the package name and the jooq generator includes the types and the procedures inside the package.

**Comment by lukaseder** [comment]
I'm sorry, I might not have been paying attention previously to what could have contributed to this issue. There are two things:

1. Regular expressions are case-sensitive, so unless your package is really lower case in Oracle (`"per_per"`, with double quotes), then the regex won't match your package.
2. Regular expressions match either fully qualified names (`SCHEMA.PACKAGE` and `SCHEMA.PACKAGE.PROCEDURE`), or unqualified names only (`PACKAGE` and `PROCEDURE`). So, when writing `PER_PER(\..*)?`, then there's probably a missing schema name, such as in `SCHEMA.PER_PER(\..*)?`

**Comment by DiabolusExMachina** [comment]
Yes that is working. Thanks!
