### ISSUE TITLE
oracle 11g pagination

### ISSUE THREAD

**Issue by bassmake** [jOOQ/jOOQ#5825]
Hi,
after migration to 3.9.1 pagination is not working. Generated SQL looks like this
```
offset ? rows fetch next ? rows only
```
which is not supported by oracle11g

**Comment by lukaseder** [comment]
Thank you very much for your report. What `SQLDialect` are you using? `ORACLE11G` or `ORACLE`?

**Comment by bassmake** [comment]
`ORACLE11G`

**Comment by lukaseder** [comment]
Hmm, I tried reproducing this, e.g. with:

```java
Select<Record1<Integer>> q = DSL.using(connection, SQLDialect.ORACLE11G)
   .selectOne()
   .limit(1)
   .offset(1);

System.out.println(q);
System.out.println(q.fetch());
```

The generated SQL is:

```sql
select "v0" "one"
from (
  select 
    "x"."v0", 
    rownum "rn"
  from (
    select 1 "v0"
    from dual
  ) "x"
  where rownum <= (1 + 1)
)
where "rn" > 1
order by "rn"
```

And the result is correct as well. Do you perhaps have an example query where this fails for you?

**Comment by bassmake** [comment]
in the end we have used `ORACLE` dialect. after setting it to `ORACLE11G` the problem was solved

**Comment by lukaseder** [comment]
Thank you very much for the feedback. I'm glad there's no regression here :)
