### ISSUE TITLE
PostgreSQL connections stay idle if maven gets interrupted

### ISSUE THREAD

**Issue by driverpt** [jOOQ/jOOQ#5837]
If for some reason maven fails, we notice that connections stay open.

`org.postgresql.util.PSQLException: FATAL: sorry, too many clients already`

Is this a maven or a plugin issue ?

**Comment by driverpt** [comment]
After some analysis, i believe this is somehow related Thread-Safety.

Is this Plugin Thread-safe?

**Comment by lukaseder** [comment]
Thank you very much for your enquiry. Would you mind showing what you're doing? :) From the information you've given, It's not easy to give you an authoritative answer...

**Comment by driverpt** [comment]
@lukaseder , please ignore this issue. This wasn't a Maven Plugin issue.

When using Spring Boot we had a Test failing with a TooManyConnectionsException. We thought it was the jOOQ plugin that didn't release the connections, but it's related to the Connection Pool itself.

Thanks and again, sorry for wasting time.

**Comment by lukaseder** [comment]
No worries :)
