### ISSUE TITLE
default conversion of tinyint(1) is Boolean and tinyint(>1) is Byte

### ISSUE THREAD

**Issue by ldaume** [jOOQ/jOOQ#5839]
If one use a tinyint(1) for low integer values in a table like this.
```sql
CREATE TABLE `tinyint_test`
  (
     `tinyint_value` TINYINT(1) NOT NULL DEFAULT '1'
  )
engine = innodb
DEFAULT charset = utf8
COLLATE = utf8_unicode_ci;

INSERT INTO tinyint_test
VALUES      (5);  
```

The default conversion is `Boolean`, but the `get(Field<?> field, Class<? extends T> type)` method converts it always to `0` or `1`, which can lead to ugly behaviours.

e.g.
```java
final DSLContext using = DSL.using(sqlDataSource.getDataSource(), SQLDialect.MYSQL);
final Field<Integer> tinyIntField = DSL.field("tinyint_value", Integer.class);

final Record booleanRecord = using.select().from(DSL.table("tinyint_test")).fetchOne();
final Integer booleanTinyintValue = booleanRecord.get(tinyIntField, Integer.class);
assertThat(booleanTinyintValue).isEqualTo(1);

final Record intRecord = using.select(tinyIntField).from(DSL.table("tinyint_test")).fetchOne();
final Integer intTinyintValue = intRecord.get(tinyIntField, Integer.class);
assertThat(intTinyintValue).isEqualTo(5);
```

It throws a `ClassCastException` just in case of the simple `get(Field<T> field)` method:
final Integer booleanTinyintValue = booleanRecord.get(tinyIntField ~, Integer.class~ );

If one use `tinyint (N)` with `N> 1`, a` ClassCastException` is always thrown because of the `Byte` type.
So, `tinyint(N)`, where `N > 1` behaves much more predictable.

**Comment by lukaseder** [comment]
Thank you very much for your report. I can reproduce the `ClassCastException` on `Integer booleanTinyIntValue = booleanRecord.get(tinyIntField)` (which I'll fix ASAP), but I'm not sure why the display size `N` should get in the way here. Did you set any JDBC driver setting to implement boolean semantics? I'm aware that people often "abuse" the `TINYINT(1)` type for booleans in MySQL, but in fact, the `N` value is meaningless, the type is really just `TINYINT`, which maps to `Byte` in jOOQ by default...

**Comment by lukaseder** [comment]
I've registered a new issue for the `ClassCastException`: https://github.com/jOOQ/jOOQ/issues/5846.

This issue here will deal with any potential issue related to MySQL `TINYINT(N)` where `N=1` or `N>1`

**Comment by ldaume** [comment]
In this example a HikariDataSource is used for the connection with a HikariConfig like this:
```java
hikariConfig.setJdbcUrl("jdbc:mysql://" + url + ":" + port + "/" + database
                                + "?useJDBCCompliantTimezoneShift=true"
                                + "&useLegacyDatetimeCode=false"
                                + "&serverTimezone=UTC"
                                + "&zeroDateTimeBehavior=convertToNull"
                                + "&characterEncoding="
                                + encoding);
```

**Comment by lukaseder** [comment]
Thanks for sharing. There's nothing out of the ordinary there from the `tinyint` vs. boolean perspective. Perhaps I'm simply misunderstanding you, then. Why do you think that the display size of your tiny int column matters to this issue?

**Comment by ldaume** [comment]
The difference is the select step.
If one selects all with `using.select().from ...`, the result in the test case is 1: `assertThat(booleanTinyintValue).isEqualTo(1)`.

If one selects just the field with `using.select(tinyIntField).from ...`, the result in the test case is 5: `assertThat(intTinyintValue).isEqualTo(5)`.

If that is intended, everything is fine.

**Comment by lukaseder** [comment]
Oh, I'm sorry, I overlooked that. Hmm, but in my test case, that's not true:

```sql
CREATE TABLE t_5839 (
  `tinyint_value` TINYINT(1)
)
```

And then.

```java
    @Test
    public void testMySQLIntegerTypesWithPlainSQL() {
        clean(T_5839);

        assertEquals(1, create().execute(
            "insert into t_5839 (`tinyint_value`) "
          + "values (?)",
            (byte) 5));

        Field<Integer> tinyint = field("tinyint_value", Integer.class);

        Record r1 = create().fetchOne("select * from t_5839");
        assertEquals(5, (int) r1.get(tinyint, Integer.class));
//        assertEquals(5, (int) r1.get(tinyint));

        Record r2 = create().select().from("t_5839").fetchOne();
        assertEquals(5, (int) r2.get(tinyint, Integer.class));
//        assertEquals(5, (int) r2.get(tinyint));

        Record1<Integer> r3 = create().select(tinyint).from("t_5839").fetchOne();
        assertEquals(5, (int) r3.get(tinyint, Integer.class));
//        assertEquals(5, (int) r3.get(tinyint));
    }
```

What MySQL server and JDBC driver versions are you using?

**Comment by lukaseder** [comment]
(in any case, you should never get `1` back from the query, always `5`, as that's the value in the database)

**Comment by hepin1989** [comment]
`TableField<FacadeScriptFunctionsRecord, Byte> MONITOR`

![image](https://user-images.githubusercontent.com/501740/33651180-db9073d0-da9f-11e7-9ad8-205c488e1990.png)

**Comment by hepin1989** [comment]
@lukaseder I set to boolean ,but still get Byte via generator

**Comment by lukaseder** [comment]
@hepin1989 Thanks for your comments. This issue is currently missing any steps to reproduce the problem. Your comments don't seem to change that. Please, would you mind opening a new issue (as I'm not sure if your comments are really related) and be a bit more specific? It's hard to guess what you meant by those two comments...

**Comment by lukaseder** [comment]
See also #7719
