### ISSUE TITLE
ClassNotFoundException occures when generate codes form JPA entity by maven plugin

### ISSUE THREAD

**Issue by GYWang1983** [jOOQ/jOOQ#5845]
The `ClassNotFoundException` occures when I generate codes form JPA entity by maven plugin.

```java
Caused by: java.lang.ClassNotFoundException: org.jooq.codegen.sample.jpa.domain.UserAccessLog
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.jooq.util.jpa.JPADatabase.create0(JPADatabase.java:135)
```
The code generator cannot load the JPA entity classes defined in the project.

The sample project in the attachment. And I executed it by Jdk 1.8.0_72 & maven 3.3.9

[codegen_log.txt](https://github.com/jOOQ/jOOQ/files/760107/codegen_log.txt)
[jooq-codegen-sample.zip](http://mc.58panda.com/static/jooq-codegen-sample.zip)

I think the problem is caused by the ClassLoader misused

The code in the org.jooq.util.jpa.JPADatabase
```java
for (String pkg : packages.split(","))
    for (BeanDefinition def : scanner.findCandidateComponents(defaultIfBlank(pkg, "").trim()))
        metadata.addAnnotatedClass(Class.forName(def.getBeanClassName()));  // Use the the ClassLoader of caller
```
modify to
```java
ClassLoader cl = Thread.currentThread().getContextClassLoader();
for (String pkg : packages.split(","))
    for (BeanDefinition def : scanner.findCandidateComponents(defaultIfBlank(pkg, "").trim()))
        metadata.addAnnotatedClass(Class.forName(def.getBeanClassName(), true, cl));
```

the problem will be fixed

**Comment by lukaseder** [comment]
Thank you very much for your complete report and fix suggestion. It's true that perhaps, we should use the context class loader, but I don't think this will solve the issue. I can still set up a configuration where the `ClassNotFoundException` appears with the context class loader, e.g. when removing the `<schemata>` configuration from your pom.xml example.

The problem is simply the fact that the JPA entities are not compiled (and thus not on the classpath) yet when the jOOQ code generator is triggered. The solution for this is to put the entities in a separate Maven module.

**Comment by GYWang1983** [comment]
The JPA entities must be compiled, because they have been loaded successful by `ClassPathScanningCandidateComponentProvider`.  If the class files were not in the classpath, there should be no jood record file generated, not a `ClassNotFoundException` appears.

The function `Class.forName(String)` use the caller's `ClassLoader` by default, and the caller is `JPADatabase`, loaded by the maven plugin class loader which not contains the project classpath.
[Document about guide-maven-classloading](http://maven.apache.org/guides/mini/guide-maven-classloading.html)
![image](https://cloud.githubusercontent.com/assets/5241758/22739245/d26d029c-ee45-11e6-8ea9-22e0d303737b.png)

So, even if put the entities in a separate Maven module, they will not be loaded by the plugin class loader, unless add the module to the plugin as a dependency.

In `org.jooq.util.maven.Plugin`, the under line creates a custom class load which contains the project classpath, and put it into the thread context.
```java
// [#2886] Add the surrounding project's dependencies to the current classloader
Thread.currentThread().setContextClassLoader(getClassLoader());
```
So, we can use the context class loader instead of default class loader.

**Comment by lukaseder** [comment]
> In org.jooq.util.maven.Plugin, the under line creates a custom class load which contains the project classpath, and put it into the thread context.

You're right, nice catch. I agree with your fix proposed in your pull request #5848 then. May I ask you to please read through our contribution guidelines and sign our transfer of rights agreement, which allows us to dual-license your contribution?
https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

Thanks again very much for your contribution!

**Comment by GYWang1983** [comment]
Ok, I've signed it.

**Comment by lukaseder** [comment]
Thank you very much
