### ISSUE TITLE
Data loader unable to decode Base64 encoding binary types

### ISSUE THREAD

**Issue by codeturner** [jOOQ/jOOQ#5858]
I'm attempting to use the formatter to dump test data out into a csv file for each table in our schema.  I would then commit these files into our source repo so that other developers can load test data for development.  I then use loadInto to import the data.  This is by far the best solution I could come up with, since jOOQ already knows our schema, and it's easier to maintain the test data by editing csv files.  Plus, we can do a snapshot dump of the database to merge changes into the source repo.  Perfect!

This works great except when I bump into binary types.  The fix for issue [#3961] converts binary values to base64 encoded strings when formatting to XML, JSON, CSV, etc.  However, when trying to load back those values using loadInto, the converter doesn't know it needs to be decoded, and the data ends up corrupted.

I think base64 is a great way of representing a binary value, but can we fix the importer to recognize that the input is base64 encoded, and then automatically decode it?

I propose prepending a tag to the value, something like "BASE64:" so that when the converter sees that tag prepended to the value, it can decode it before use.  I think this is harmless since any user of the exported data will have to process the binary value before using it anyway.

Thoughts?

**Comment by lukaseder** [comment]
Thank you very much for your report. The implicit specification of #3961 (and of other features) is for jOOQ's export functionality to be reversible on import. The fact that #3961 is not reversible is an oversight and should be fixed in all relevant places.

I'm not a fan of an arbitrary prefix, though. The decision to encode export data is based on the value's data type (i.e. `byte[]`). It would be more formally correct to make that decision based on the `Field.getType()`, which is mostly the same. In any case, we should definitely make that decision based on `Field.getType()` upon import (much like we parse numbers if the `Field.getType() == Integer.class`, for instance).

**Comment by lukaseder** [comment]
Do note there is also a pending feature request that allows for specifying custom import/export formatters: https://github.com/jOOQ/jOOQ/issues/2741

**Comment by codeturner** [comment]
Another option I thought about was using MySQL's way of specifying a binary using the hexidecimal literal format: X'4D7953514C'.  But this isn't a SQL standard, so that seemed as arbitrary to me as a prefix.

I was hesitant in making the assumption that all imported values to type byte[] would be expected to be in base64 format.  That's why I felt that the importing data type should have a way of indicating to the converter that it is encoded and needs to be decoded.  But if we can make that assumption to get it to work, I'd be beyond happy.

Ideally, I'd love for this to work without custom import/export formatters, but in the end, I just want to be able to import the results of an export.  Any way I can help?

**Comment by lukaseder** [comment]
[Here, have an overview over various SQL hex literals](http://stackoverflow.com/a/9320943/521799) (heh, I documented that myself 5 years ago...)

Rest assured, #2741 will provide exactly what you need. I don't see any disadvantage over your prefix solution. You could even implement a couple of formatters that parse the prefix and handle this transparently for you.

> Any way I can help?

Thanks for the offer. You could of course fork jOOQ and have a stab at implementing #2741. Given the complexity of the task, there's significant risk that you might overlook something for any suggestion to be considered to be merged into jOOQ, though... I'll leave it up to you.

**Comment by codeturner** [comment]
One worry I have is that specifying a custom formatter on the output will not be as seamless as I was hoping.  My code simply loops thru all of the tables in my schema object to dump and load all data. The code is very simple to pull this off.  However, with a custom fomatter, I fear that I'll have to now inspect each table to determine how to format a specific field.

Here's my example code:

```java
	private void dump(DSLContext dsl, Schema schema, String baseDir) throws IOException {
		for (Table<?> table : schema.getTables()) {
			final String fileName = baseDir + "/" + table.getName() + ".csv";
			try (FileWriter writer = new FileWriter(fileName)) {
			    dsl.selectFrom(table).fetch().formatCSV(writer);
			} catch (IOException e) {
				LOGGER.error("Error while dumping", e);
				throw new RuntimeException(e);
			}
		}
	}
	private void load(DSLContext dsl, Schema schema, String baseDir) throws IOException {
		for (Table<?> table : schema.getTables()) {
			final String fileName = baseDir + "/" + table.getName() + ".csv";
			File csv = new File(fileName);
			if (csv.exists()) {
				try {
					Loader<?> loader = dsl.loadInto(table)
							.batchAll()
							.commitAll()
							.loadCSV(csv)
							.fields(table.fields())
							.execute();
					if (!loader.errors().isEmpty()) {
						for (LoaderError error : loader.errors()) {
							LOGGER.error("import error for row={}", error.row(), error.exception());
						}
						throw new RuntimeException("Error importing.");
					}
				} catch (IOException e) {
					LOGGER.error("Error while loading", e);
					throw e;
				}
			}
		}
	}
```

**Comment by lukaseder** [comment]
> However, with a custom fomatter, I fear that I'll have to now inspect each table to determine how to format a specific field.

Well... :) You simply cannot have custom formatting without specifying when to apply custom formatting.

Without making any promises here, the custom formatters might be applicable at several levels of SPI injection:

- On individual data types
- On individual columns (like the existing `Converter` / `Binding` feature)
- On a new data type registry (https://github.com/jOOQ/jOOQ/issues/5713) (this will probably work best)
- On individual  `formatCSV()` / `loadCSV()` / `fetchFromCSV()` calls

**Comment by codeturner** [comment]
Wow, I just noticed commit 64c3655, which fixed it exactly as I needed!  Thanks for the quick response!  You are the best!

**Comment by lukaseder** [comment]
> You are the best!

I know ;)
