### ISSUE TITLE
Add Setting.apostropheEscaping to allow for alternative escaping of apostrophes

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5873]
In most SQL databases, single quotes inside of string literals are escape by doubling them, e.g.:

```sql
SELECT 'The string''s length is 25' FROM dual
```

But in some SQL dialects (e.g. [SOQL](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_quotedstringescapes.htm)), they need to be escaped with a backslash:

```sql
SELECT 'The string\'s length is 25' FROM dual
```

While we will not add formal support for SOQL, it certainly makes sense to make this escaping configurable, similar to `Settings.backlashEscaping` (we'll need to study the interaction between these two)

**Comment by sawyna** [comment]
Hi I would like to take up this issue. I was the one who raised question on stackoverflow.

**Comment by lukaseder** [comment]
@sawyna Thank you very much for your offer. Let me know if you need any help.

**Comment by sawyna** [comment]
@lukaseder I am new to open source contribution. I might need some help to get started. I assume I should fork jooq repo, work on the issue and create a PR. Please correct me if I am wrong

**Comment by lukaseder** [comment]
@sawyna No worries, thanks for asking.

I've just updated our contribution guidelines with some ideas: https://github.com/jOOQ/jOOQ/blob/master/CONTRIBUTING.md

Let me know if you still have any open questions that aren't covered in there.

**Comment by lukaseder** [comment]
This will not be implemented in jOOQ. Rationale here: https://github.com/jOOQ/jOOQ/pull/7314#issuecomment-374185946
