### ISSUE TITLE
Add support for MySQL's CROSS JOIN .. ON clause

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5875]
MySQL seems to think of the `CROSS` keyword as a synonym for `INNER`, which is why it allows `CROSS JOIN .. ON`.

~We won't "pollute" the jOOQ DSL API with this option~ (yes we will), but since it is possible to add a `Condition` with the model API's `addJoin()` method, e.g.:

```java
query.addJoin(sortLocation, JoinType.CROSS_JOIN, sortLocation.ID.equal(sortLocationId));
```

We should generate the "right" SQL, being:

- `CROSS JOIN .. ON` in MySQL
- an additional predicate in the `WHERE` clause in other databases

Note, this does not apply to `NATURAL JOIN`

----
See also:
- https://www.jooq.org/doc/3.2/manual/sql-building/column-expressions/aliased-columns/#comment-3155931058
- https://dev.mysql.com/doc/refman/5.7/en/join.html

**Comment by chriswareham** [comment]
I wonder if an SQL compliant and portable implementation would be for the code generator to simply add a WHERE condition rather than ignoring the condition. This would work and wouldn't require a special case for MySQL that adds an ON condition.

**Comment by lukaseder** [comment]
@chriswareham : If a MySQL user tells jOOQ that's what they want to do, the jOOQ policy is usually to let them do exactly that. For instance, if a MySQL user wants to use `ON DUPLICATE KEY UPDATE`, we'll generate that as well, not the `MERGE` statement (even if MySQL eventually decides to implement `MERGE`)

For the avoidance of doubt: Do note that after the implementation of this feature, the condition will not be ignored in *any* database.

**Comment by lukaseder** [comment]
This really complicates jOOQ's internals with hardly any gain at all. There's no advantage in using `CROSS JOIN` the way MySQL suggests as MySQL users can just adhere to the SQL standard interpretation of `CROSS JOIN` and `INNER JOIN` through jOOQ API.

The parser, however, will be able to parse a `A CROSS JOIN B ON P` expression and translate it to `A JOIN B ON P` through #7518.

I will close this as won't fix
