### ISSUE TITLE
Schema version check does not work with Scala

### ISSUE THREAD

**Issue by tPeltola** [jOOQ/jOOQ#5879]
Every time code generation is invoked, generator logs `"No previous version available for schema <retracted>. Regenerating."`. If Java code is generated, version check works and the code is not regenerated. It seems to me that the regex in `JavaGenerator#readVersion` does not match Scala array.

**Comment by lukaseder** [comment]
Thanks a lot for reporting. I can reproduce this, will fix ASAP

**Comment by lukaseder** [comment]
Indeed, the regex is wrong, but also the `strategy.getFile()` method doesn't return the `.scala` file, but the `.java` file, which is corrected only in `JavaGenerator.newJavaWriter()`

**Comment by tPeltola** [comment]
Nice work, thanks!
