### ISSUE TITLE
Document the fact that only the first matching <forcedType/> is a applied to a data type definition

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#5885]
In jOOQ 3.9, when multiple `forcedType` potentially match the same column, the first match is selected (based on the order they were declared in `pom.xml`).

This behavior should be explicitly documented here: https://www.jooq.org/doc/3.9/manual/code-generation/custom-data-types/

**Comment by lukaseder** [comment]
You're absolutely right. There are also 1-2 other chapters where this should be documented.

I'm sensing another feature here. We could improve the log messages too, to document this behaviour. This might be picked up more easily by users looking for reasons why their `forcedType` doesn't match. Details here: https://github.com/jOOQ/jOOQ/issues/5889

**Comment by deinspanjer** [comment]
The generator strategy matchers operate in this same manner, and I am relying on that behavior to implement some rather convoluted table name to pojo name conversions.
I'm not sure if any of the features or documentation you are considering would extend to that area, but if so, I'd be happy to share the details of those conversions so they could be considered in that context.

**Comment by lukaseder** [comment]
@deinspanjer : Yes your insight would be greatly appreciated, thank you for the offer. Feel free to post anything you'd like to share here, or if you prefer, provide a link to a gist.

**Comment by deinspanjer** [comment]
Here is a gist with the config and notes.  As I said, it isn't specifically dealing with forcedType, but it does deal with the order of processing.  I hope it might be useful in your consideration.

When I was debugging which regex actually matched a particular object name, I would sometimes change all the output expressions to give each a numeric prefix so I could look at the resulting classes and determine which rule generated them.  I think having something in the output of the generator that indicates that would be convenient for either matchers or forcedTypes.

**Comment by lukaseder** [comment]
Very interesting, thank you. A good example of how to leverage the abort-on-first-match behaviour. In the case of forcedType, I had a similar use-case in mind, where the "least specific" regex (the "fallback") will be listed at the bottom, whereas more specific ones are on top.

Also, I'm glad that we eventually decided to turn on the regex "comments" flag for you :) (which allows for formatting regular expressions)

**Comment by lukaseder** [comment]
@deinspanjer: I'll implement your idea in a separate step: https://github.com/jOOQ/jOOQ/issues/6434
