### ISSUE TITLE
Add "view imports" text to manual on hover icon

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5900]
The existing "how to read the manual" icon in each code block is still not clear enough:

![image](https://cloud.githubusercontent.com/assets/734593/23205627/dea18cd6-f8ea-11e6-85c5-221f4bc3b121.png)

It should probably be accompanied with a little text, such as "view imports".

Perhaps, we could add a bigger hover element that can be clicked away with a "got it" button (storing that in a cookie) to make sure people will not be annoyed by the instructional element.

----
See discussion here:
https://www.jooq.org/doc/latest/manual/getting-started/use-cases/jooq-as-a-sql-builder-with-code-generation/#comment-3168773940

**Comment by axelfontaine** [comment]
As an alternative to this adding a little bit of JS that expands the code section to reveal the "noise" such as imports, works very well, as shown in the Kotlin docs: https://kotlinlang.org/docs/reference/list-operations.html

**Comment by lukaseder** [comment]
I like that, thanks for the pointer! The idea there is that the `+` button allows for producing a fully self contained code snippet, that can be copy pasted into an IDE project...

**Comment by lukaseder** [comment]
Duplicate of #10495, which has been implemented.
