### ISSUE TITLE
Treat null QueryPart[] or Collection<QueryPart> arguments like empty lists

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5903]
Instead of passing an explicit `DSL.trueCondition()` in the event of not having any predicates at all, it might be useful for some users / use-cases to be able to pass `null` as an equivalent value:

Current behaviour:

```java
public static <T> Condition onlyIfNotNull(Function<T, Condition> operator, T value) {
    return (value != null) ? operator.apply(value) : trueCondition();
}
```

Usage:

```java
.where(onlyIfNotNull(ID::in, ids))
```

Potentially new behaviour:

```java
public static <T> Condition onlyIfNotNull(Function<T, Condition> operator, T value) {
    return (value != null) ? operator.apply(value) : null;
}
```

This was suggested in a discussion on the manual:
https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql/#comment-3170125504

It's not sure yet if this is a good idea as accepting nulls might be obscuring bugs rather than "failing early".

----
Related (rejected) feature request: https://github.com/jOOQ/jOOQ/issues/1817

**Comment by thomasgillet** [comment]
Very good idea indeed. I'm using the `onlyIfNotNull` method a lot and it often leads to a pile of `1 = 1` in the generated SQL. Not very harmful but not very satisfactory either.

To avoid obscuring bugs, what about a special `Condition` object? Something like `DSL.noCondition()`, or `DSL.emptyCondition()`?

**Comment by lukaseder** [comment]
Well, the other option is, of course, to pass an empty collection:

```java
public static <T> List<Condition> onlyIfNotNull(Function<T, Condition> operator, T value) {
    return (value != null) ? Arrays.asList(operator.apply(value)) : Collections.emptyList();
}
```

That's perhaps a bit cleaner, because passing `where((Condition) null)` means you're really passing

```java
new Condition[] { null };
```

**Comment by thomasgillet** [comment]
Ah yes, the special condition object already exists indeed.
But using a collection where it is in fact a single `Condition` makes things a little awkward. The signature of `onlyIfNotNull` would become quite strange.

But ok, I'll take the advice anyway, thanks.

**Comment by lukaseder** [comment]
Accepting `null` seems dangerous. But indeed, we have added support for a new `DSL.noCondition()`, which can be passed to all API accepting conditions, having the same effect as if the API call wasn't made in the first place: #6817
