### ISSUE TITLE
Support "replay on exception"

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5905]
(or also "retry on exception")

I was talking to a customer at Voxxed Days Zurich and they had an interesting idea:

In their setup, connecting to a galera cluster, some queries may stall when running against a node that is saturated / not responding, etc. They want to then quickly discard the JDBC connection, provide a new one to the thread and re-run the same query on a new connection.

The use-case described above assumes that the connection is in auto-commit mode (otherwise, the functionality would need to be implemented in the `TransactionProvider`). In this case, an implementation could be done inside of `ExecuteListener`, intercepting timeout exceptions, and then triggering the replay through a dedicated `ExecuteContext` SPI call.

This still needs more thinking, but the general idea is interesting. This isn't the first time a jOOQ user was interested in a "replay on exception" feature.

(The issue title may change when this feature is more clearly specified)

**Comment by srujanakuntumalla** [comment]
Hi @lukaseder  ,
We faced similar situation. I have done research to figure out any manual way to intercept the listener and redo the query in the event of connection failure. But, ended up without much details and this looks like right place to discuss this. 
Have you find at least a temporary way to perform such action with JOOQ right now.? I am looking for a way to handle this scenario by the time the implementation comes into JOOQ

**Comment by lukaseder** [comment]
"Replay on exception" would require the entirety of client code to be fully transactional, which it isn't, at least not on the JVM. Any state change (mutation) that isn't tracked is lost, and not "replayable". This includes code that resides outside of jOOQ.

It doesn't make sense to implement such a feature in jOOQ. It would have to be implemented elsewhere, in some framework logic. That framework could then support jOOQ and jOOQ would automatically profit from it, but it isn't a jOOQ feature.
