### ISSUE TITLE
MockFileDatabase shouldn't trim lines

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5921]
Currently, parsed lines are trimmed and newlines are not maintained. The combination thereof can lead to wrong SQL strings as in the following example:

```
select a
from (select 1 as a);
> A
> -
> 1
@ rows: 1
```

Which is parsed as:

```sql
select afrom (select 1 as a)
```

Note the syntax error.

**Comment by lukaseder** [comment]
This could be considered a somewhat incompatible change, which is why we're not merging this to 3.9

**Comment by azizmwondha** [comment]
Ah, but a new line is whitespace. Even the DB will interpret and execute:

`select a
from (select 1 as a);`

in the same manner as:

`select a from (select 1 as a)`

and not:

`select afrom (select 1 as a)`.

**Comment by lukaseder** [comment]
Thanks for your comment, @azizmwondha. This is an old issue, which has been fixed. What are you trying to say, then?
