### ISSUE TITLE
Enhance InsertOnDuplicateSetMoreStep to support Postgres syntax

### ISSUE THREAD

**Issue by emrul** [jOOQ/jOOQ#5933]
Raising this issue since I've been hammering on a workaround all day and have become stuck on this:

Postgres supports the following INSERT syntax 
INSERT INTO ... ON CONFLICT DO UPDATE SET ... WHERE ... RETURNING ...

When calling set() in jOOQ we get returned an InsertOnDuplicateSetMoreStep that doesn't allow us to specify any WHERE conditions or allow specifying a 'returning' clause.

**Comment by lukaseder** [comment]
Thanks for your report. These are known limitations and are due for jOOQ 3.10:

- `ON CONFLICT .. RETURNING`: https://github.com/jOOQ/jOOQ/issues/2123
- `ON CONFLICT .. WHERE`: https://github.com/jOOQ/jOOQ/issues/5637

Closing this as a duplicate
