### ISSUE TITLE
SQLServer: record.update throws "com.microsoft.sqlserver.jdbc.SQLServerException: Cannot update identity column 'id'."

### ISSUE THREAD

**Issue by fedotxxl** [jOOQ/jOOQ#5941]
Looks like `record.update` tries to update ID (which is sequence) and get's an exception from SQL Server. How to exclude ID field from update? Is it configurable?

**Comment by lukaseder** [comment]
The `UpdatableRecord` will include all columns in an update statement that were changed in the record. You can verify this through `Record.changed(Field)`. If you do not have any means of intercepting the setting / modification of a primary key value, you can reset the field through `Record.reset(Field)` or modify the changed flag through `Record.changed(Field, false)`.

Do note that some databases (including SQL Server, when not using identities) allow for actually modifying a primary key value, even if that is generally not recommended.

Let me know if this answers your question.

**Comment by Duvel** [comment]
@lukaseder thanks for the info, I was able to solve my problem with this info:

```
                    Account account = account from other source
                    AccountRecord accountRecord = context.newRecord(ACCOUNT, account)
                    accountRecord.changed(ACCOUNT.ID, false)
                    accountRecord.update()
```

Because of the object mapping the field ID got "changed", although it didn't.

**Comment by lukaseder** [comment]
> Because of the object mapping the field ID got "changed", although it didn't.

It's a question of how you define "changed". In our language, it got "changed," but not "modified", although we're not using the therm modified.

This is a frequent topic of debate. A poll on twitter produced the result that among 174 votes, 84.5% prefer the way jOOQ currently works, only 15.5% would wish for the behaviour to be different: https://twitter.com/lukaseder/status/1232326838426505216

There may be some subtle improvements possible in certain cases, where jOOQ could do the right thing™ (e.g. exceptions in the presence of identities, etc.), but every such exception is also a regression risk for existing users, as well as an additional source of complexity in this area.
