### ISSUE TITLE
Improve DSLContext.batchStore() performance

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5962]
This is a known issue (although, cannot seem to find the issue...)

`DSLContext.batchStore()` et al need to run through all records to collect the individual statements that would be generated on individual `Record.store()` calls, in order to preserve semantics.

This can turn out to be quite slow on the client side (while the actual batching runs at normal speed, again). Surely, there's room for improvement here.

**Comment by nathanmerrill** [comment]
Is there a workaround for this?  It takes over a minute to insert 5000 records over here.

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/4533
