### ISSUE TITLE
Add JavaGenerator.printPackageComment() to allow for overriding this

### ISSUE THREAD

**Issue by chriswareham** [jOOQ/jOOQ#5968]
It's possible to extend the `org.jooq.util.JavaGenerator` class to prevent the code generator from printing class JavaDoc by simply overriding the `printClassJavadoc()` method. However, it's not as simple to do the same to prevent printing the comment that precedes the package declaration.

The following would allow this:

```
    protected void printPackage(JavaWriter out, Definition definition) {
        printPackage(out, definition, GeneratorStrategy.Mode.DEFAULT);
    }

    protected void printPackage(JavaWriter out, Definition definition, GeneratorStrategy.Mode mode) {
        printPackageComment(out, definition, mode);

        if (scala)
            out.println("package %s", getStrategy().getJavaPackageName(definition, mode));
        else
            out.println("package %s;", getStrategy().getJavaPackageName(definition, mode));

        out.println();
        out.printImports();
        out.println();
    }

    protected void printPackageComment(JavaWriter out, Definition definition, GeneratorStrategy.Mode mode) {
        String header = getStrategy().getFileHeader(definition, mode);

        if (!StringUtils.isBlank(header)) {
            out.println("/*");
            printJavadocParagraph(out, header, "");
            out.println("*/");
        }
    }
```

**Comment by chriswareham** [comment]
Just to note it's possible to provide a custom generator strategy to do this, but this would require an extra custom class when I have already extended the `JavaGenerator` class to modify or inhibit other behaviour.

**Comment by lukaseder** [comment]
Interesting, you're right. That behaviour should be overrideable as well. Thanks for your suggestion!

**Comment by lukaseder** [comment]
Note, this is also covered by https://github.com/jOOQ/jOOQ/issues/3906, which you can use as a workaround. I won't close this here as a duplicate. The two mechanisms are orthogonal.
