### ISSUE TITLE
Converter.of[Nullable] converters aren't serializable when passing lambdas

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#5974]
In jOOQ 3.9, we've introduced new convenience API to construct converters from lambda expressions (https://github.com/jOOQ/jOOQ/issues/5398).

These converters are not serializable, because the lambdas are not serializable by default. Perhaps, there's a way to work around this limitation.

**Comment by danieldietrich** [comment]
Suggestion (maybe it works):

```java
static <T, U, FROM extends Function<? super T, ? extends U> & Serializable,
               TO extends Function<? super U, ? extends T> & Serializable>
    Converter<T, U> of(
        Class<T> fromType,
        Class<U> toType,
        FROM from,
        TO to) { ... }
```

**Comment by lukaseder** [comment]
@danieldietrich I have (of course!) tried this already, but I got some serialisation exceptions, which I hadn't investigated yet :)

**Comment by danieldietrich** [comment]
@lukaseder Yes, this is some tricky stuff. I don't know how serialization behaves when things are captured from the outer scope of a lambda...

**Comment by lukaseder** [comment]
We won't fix this as it will lead to tons of possibly undesired side-effects. If users want serializable lambda converters, they can do this explicitly.
