### ISSUE TITLE
issue about using newRecord to insert a record

### ISSUE THREAD

**Issue by VeryVery** [jOOQ/jOOQ#5983]
Here's my function:
---
NodesRecord record = context.newRecord(Nodes.NODES);
record.setId("001");
record.store();

return record;
---

sometimes, out of the function, I got the result

record01.getId() != "001"

that's amazing!!!

but the record in my database is correct.

**Comment by lukaseder** [comment]
Thank you very much for your message. Well, there are many reasons why this doesn't work for you. Essentially two things come to mind:

1) You should *never* compare strings with `==` or `!=` in Java. These operators compare *identity* not *value*. Use `String.equals()` instead:
    ```java
    record01.getId().equals("001")
    ```
2) jOOQ fetches trigger / sequence / identity generated values automatically when you call `record.store()`. Perhaps, your inserted value is simply overwritten (in some cases)?

I hope this helps. Let me know if you have any further questions.

**Comment by VeryVery** [comment]
sorry about my unclear expression.
I know "never compare strings with == or != in Java", I using String.equals() in my source code.

Here is my code:

function createNode()
```
NodesRecord record = context.newRecord(Nodes.NODES);
String id = UUID.randomUUID().toString();
record.setId(id);
record.store()

        if(!org.apache.commons.lang3.StringUtils.equals(id, record.getId()))
        {
            System.out.println("OMG, why they are not equals");
        }

return record;
```

that is all, sometimes I see my log, I found the output "OMG, why they are not equals".
PS: the id I used is UUID, I think is not overwritten.

**Comment by lukaseder** [comment]
Thanks for the clarification. Well, this behaviour surely is unexpected, but I still believe that something must have happened in the database, e.g. a trigger that overwrites your UUID? Can you show an example that helps reproducing this, including:

- The database you're using
- The DDL of your `NODES` table
- All triggers and other objects related to this `NODES` table
- The generated code of the `Nodes.java` table and the `NodesRecord` updatablerecord
