### ISSUE TITLE
jOOQ-codegen quiet option

### ISSUE THREAD

**Issue by aram535** [jOOQ/jOOQ#6008]
It would be great if we could have a quiet option (-s --silence?) option for the codegen for scripting purposes, warnings and errors could still override and print out but otherwise return codes are enough of an indication of success or failure.

**Comment by lukaseder** [comment]
Sure, check this out:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-logging

Just set the level to `FATAL` and enjoy the nice and quiet. :)

**Comment by aram535** [comment]
Is it possible that the studer gralde plugin isn't passing that argument along?  <Logging>FATAL</Logging> doesn't exactly translate to Gradle DSL.

**Comment by lukaseder** [comment]
@aram535: I've seen you've deleted your latest comment... Does that mean it's working for you now?

**Comment by aram535** [comment]
Yes, after 8 edits, frustrated grunts and a few tears.  It turns out you have to spell the keyword "logging" right for it to work ... who knew.

**Comment by lukaseder** [comment]
Oh, I see. Thanks for the feedback. Yes, "loging" et al. has failed me in the past, too ;)
