### ISSUE TITLE
Add better documentation for the JPADatabase

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6011]
It is not clear to everyone that the JPADatabase needs to depend on a previously built module containing JPA annotated entities:

----
See also:
http://stackoverflow.com/q/42968155/521799

**Comment by oexza** [comment]
Hi Lukas, Is there a working example somewhere demoing this? I've searched through google and can't find any.

**Comment by lukaseder** [comment]
@oexza Yes, here: https://www.jooq.org/doc/latest/manual/code-generation/codegen-jpa

Hope this helps, let me know. There's always room for improvement.

**Comment by lukaseder** [comment]
Also, a working example is here:

- https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples/jOOQ-jpa-example-entities
- https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples/jOOQ-jpa-example

**Comment by 18anandn** [comment]
> Also, a working example is here:
> 
> * https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples/jOOQ-jpa-example-entities
> * https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples/jOOQ-jpa-example

Hi @lukaseder . The examples seem to be moved somewhere. Where can I find them?
