### ISSUE TITLE
Document Settings

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#6018]
Currently the Settings class contains useless autogenerated NadaDoc (tm).

Documentation for the various settings is sorely lacking. The only way to actually obtain it is to look into https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/resources/xsd/jooq-runtime-3.9.0.xsd

Especially things like setReturnAllOnUpdatableRecord are a great fit for PostgreSQL and DEFAULT values, yet due to the total lack of documentation they are most probably vastly underutilized. (Which Google seems to confirm since searching for "returnAllOnUpdatableRecord" only returns a grand total of 7 results, all by Data Geekery)

**Comment by lukaseder** [comment]
Thanks for the suggestion. Yes, absolutely agree: https://github.com/jOOQ/jOOQ/issues/5231

(as for the Javadoc, I still haven't found a viable way to generate Javadoc with XJC without completely messing up the XSD specification. But that too, would be a nice feature to have, if there's a way! https://github.com/jOOQ/jOOQ/issues/2830)
