### ISSUE TITLE
Some solutions about avoiding delete all records in one table when in sql after 'where' results in true

### ISSUE THREAD

**Issue by yifanyou** [jOOQ/jOOQ#6026]
is there some solutions to solve this problem in jooq???

for examples
delete from table where true = true
delete from table where true = true and 1=1 .....
delete from table where (some clauses result in true)

thx！！

**Comment by lukaseder** [comment]
> is there some solutions to solve this problem in jooq???

There always is :)

> delete from table where true = true

You can get a hold of a `true` literal by using `DSL.inline(true)`, e.g.

```java
DSL.using(configuration)
   .deleteFrom(TABLE)
   .where(inline(true).eq(inline(true)))
   .execute();
```

> delete from table where true = true and 1=1 .....

Just append more predicates using `and()`

```java
inline(true).eq(inline(true)).and(inline(1).eq(inline(1)))
```

> delete from table where (some clauses result in true)

I'm sure your answers will be in this chapter of the manual:
https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql

In particular, you can write:

```java
Condition condition = DSL.trueCondition();

if (something)
    condition = condition.and(A.eq(B));

if (somethingElse)
    condition = condition.and(X.eq(Y));
```

Hope this helps

**Comment by yifanyou** [comment]
Thx very much! Nice answer. But I mean if there is only true or true things after 'where', which will make delete-sql remove all rows in table..It is a problem...

**Comment by lukaseder** [comment]
I see, I'm sorry - I didn't get that from your question. You're essentially asking how to prevent an unconditionally true predicate in the `DELETE .. WHERE` clause? But I think that's not generally possible. jOOQ cannot detect things like `0 = 1 - 1` or `some_column / some_column = 1` etc to be "unconditionally" true.

Maybe, let's discuss your real use-case... it's very easy to get caught up in examples. What kind of query are you generating dynamically, and why could its `WHERE` clause perhaps be "unconditionally true"?

**Comment by yifanyou** [comment]
thx！it's really variable.  I will check the cases next..
