### ISSUE TITLE
Table alias ignored using fluent API?

### ISSUE THREAD

**Issue by rtomsick** [jOOQ/jOOQ#6032]
Description
---

It appears that table aliases used in a SELECT ... JOIN ... style query are being ignored by #fetch(RecordMapper<?>) and friends.

Steps to reproduce
---
Attempt a query like the following:

```java

return this.ctx()
	.selectFrom(INTERNAL_USERS.as("u")
			.join(OTHER_USERS.as("i"))
			.on(field(name("u", "id"))
				.eq(field(name("i", "id")))))
	.where(field(name("i", "identifier")).eq(identifier))
	.and(field(name("u", "username")).eq(username))
	.fetchOne(r -> new User(r.get(field(name("u", "id"), UUID.class))));

```

(In the above, assume `INTERNAL_USERS` and `OTHER_USERS` are defined as `DSL.table(DSL.name("table_name"))`, and that all column names are correct and exist in the specified tables.)

Expected outcome
---

Record is mapped to new `User`

Actual outcome
---

The following warning is produced (stack trace edited for confidentiality):

```
2017-03-30 16:48:52.353  INFO 10608 --- [           main] org.jooq.impl.Fields                     : Ambiguous match found for id. Both "PUBLIC"."internal_users"."id" and "PUBLIC"."other_users"."id" match.

java.sql.SQLWarning: null
	at org.jooq.impl.Fields.field(Fields.java:134) [jooq-3.9.1.jar:na]
	at org.jooq.impl.Fields.indexOf(Fields.java:272) [jooq-3.9.1.jar:na]
	at org.jooq.impl.RowImpl.indexOf(RowImpl.java:314) [jooq-3.9.1.jar:na]
	at org.jooq.impl.Tools.indexOrFail(Tools.java:1320) [jooq-3.9.1.jar:na]
	at org.jooq.impl.AbstractRecord.get(AbstractRecord.java:225) [jooq-3.9.1.jar:na]
	at <REMOVED>
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:526) ~[jooq-3.9.1.jar:na]
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2876) ~[jooq-3.9.1.jar:na]
```

Environment
---
jOOQ 3.9.1
HSQLDB 2.3.4
Java 8

Discussion
---

I believe that this is a correct and valid use of the API (based on the documentation).  I'm using qualified names via `DSL#name(String ...)`, which I believe is the right way to do this.

Please let me know if you need additional information.

**Comment by rtomsick** [comment]
As an addendum, if I instead do `field(name(INTERNAL_USERS.getName(), "id"), UUID.class)`, no warning is produced.  This makes sense given the working theory that the aliases aren't in the result.

**Comment by lukaseder** [comment]
Thanks a lot for reporting. With plain SQL queries (as in your case), jOOQ relies on the JDBC driver's capability of correctly / completely implementing the JDBC `ResultSetMetaData` API, which documents table names along with column names.

Unfortunately, not all databases report the table alias name in this case. E.g. HSQLDB reports the physical table name (and the schema name, too).

Unfortunately, I can currently not think of any way how jOOQ can get this right when using plain SQL for HSQLDB...

**Comment by rtomsick** [comment]
OK.  I figured it was a DB-layer quirk.  The project in question is using jOOQ to abstract over several different user-selectable DBs, so that explains why I'm finding all these quirks out the hard way.

Thanks for the quick response!

**Comment by lukaseder** [comment]
Well, one option that would work across all databases would be to use the code generator here. In that case, the column disambiguation would be obvious for jOOQ...
