### ISSUE TITLE
Add DSLContext.currval(Name) and nextval(Name)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6044]

**Comment by steinard** [comment]
For some reason DSLContext.nextval("sequenceName") does not work in Postgres. I had to implement this workaround:

public class SeqGenerator {

    private SqlDialect dialect;
    private String seqSchema;

    public SeqGenerator(SqlDialect dialect, String schema) {
        this.dialect = dialect;
        if(dialect == SqlDialect.Oracle) schema = "";
        else if(dialect == SqlDialect.PostgreSql) schema = schema.toLowerCase();
        this.seqSchema = schema;
    }

    public long next(DSLContext ctx, String seq) {
        if (seqSchema.length() > 0) seq = seqSchema + "." + seq;

        if(dialect == SqlDialect.PostgreSql){
            Result<Record> r =  ctx.fetch("select nextval('"+seq+"')");
            return (long) r.getValue(0, 0);
        }
        BigInteger nextId = ctx.nextval(seq);
        return nextId.longValue();
    }
}

**Comment by steinard** [comment]
Great, thanks, I already have a layer of abstraction where I can specify this.
