### ISSUE TITLE
No support for ON CONFLICT DO NOTHING RETURNING syntax?

### ISSUE THREAD

**Issue by lehphyro** [jOOQ/jOOQ#6076]
I'm trying to return the generated id from an insert but it seems I cannot call `returning()` after calling `onConflictDoNothing()`, is there a way to do this? Here is a sample SQL that I'm trying to create with jOOQ:
```
WITH input(column1, column2) AS (VALUES(0, 1),(2, 3)), ins AS (INSERT INTO target_table (column1, column2) SELECT * FROM input ON CONFLICT DO NOTHING RETURNING id, column2) SELECT id, column2 FROM ins
```

**Comment by lukaseder** [comment]
Thank you very much for your report.

Yes, these are known limitations.

- `ON CONFLICT .. RETURNING`: https://github.com/jOOQ/jOOQ/issues/2123 (likely to be in jOOQ 3.10)
- CTE from `ResultQuery`: https://github.com/jOOQ/jOOQ/issues/4474 (still quite a few open questions in terms of API design / backwards compatibility)

**Comment by pedro-borges** [comment]
It seems that postgres 13.4 does not support this.

jOOQ is generating the following sql for me and indeed postgres does returns a result when it inserts, but empty result on duplicate.

`insert into "public"."tenants" ("id", "public_id", "environment_id", "vendor_id")
values (nextval('"public"."tenants_id_seq"'),'219b72f7-08fc-4785-b328-ad3fce9362c6','environment1','vendor1')
on conflict on constraint "ux_tenants__environment_id__vendor_id"                                                                                                                                     do nothing                                                                                                                                                                                            returning "public"."tenants"."id";`

Is this a known issue with postgres?

**Comment by lukaseder** [comment]
Yes, that's how PostgreSQL works. Not related to jOOQ.
