### ISSUE TITLE
Replace usage of String.split() by Pattern.split()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6077]
Quite some potential for micro-optimising certain use-cases. E.g.:

- `DefaultRenderContext.formatIndentLockStart()` to calculate the new indentation (this showed up in a profiling session)
- `DefaultBinding.parse()`: to split date and time parts
- `Tools.parseTXT`: to split lines
- `LoggerListener.logMultiline`: to split lines (this one might have some impact on debug loggers!)
- `StringUtils.toCamelCase()`: might affect code gen
- `MockFileDatabase.loadOneResult()`: to debug log result

**Comment by zhurs** [comment]
String.split has optimization for case, when pattern contains only one non-special symbol, and little bit faster, than precompiled Pattern
https://gist.github.com/zhurs/bbf42626f5fcaab3145c86a3d6ec6d7b

**Comment by lukaseder** [comment]
Thanks for your comment, @zhurs, that's an interesting observation. I'll review the change soon. The most important ones were using actual regexes (multi newline characters), but it would certainly be better to benchmark each individual case.

**Comment by lukaseder** [comment]
OK, those usages where the fast-path actually applied were now reverted. Thanks again for your hint, @zhurs !
