### ISSUE TITLE
Prefer Java 8 syntax (method references, lambda expressions) in manual example

### ISSUE THREAD

**Issue by benmccann** [jOOQ/jOOQ#6109]
The docs have lots of very verbose syntax like:

    // Write callbacks to receive records from select statements
    List<Integer> ids =
    create.selectFrom(BOOK)
          .orderBy(BOOK.ID)
          .fetch()
          .map(new RecordMapper<BookRecord, Integer>() {
              @Override
              public Integer map(BookRecord book) {
                  return book.getId();
              }
          });

This makes it seem like it's very verbose to use Jooq and turned me off at first glance. After looking more closely I realize most of these examples could be rewritten such as:

    // Write callbacks to receive records from select statements
    List<Integer> ids =
    create.selectFrom(BOOK)
          .orderBy(BOOK.ID)
          .fetch()
          .map(book -> book.getId());

**Comment by benmccann** [comment]
Nevermind. I see that the Java 8 syntax is there later on. I didn't read that far initially. I wonder if the Java 8 version should come first (or at some point be the only version since Java 7 is now end-of-life)

**Comment by lukaseder** [comment]
I agree with inversing the order, thanks for the suggestion. I'd certainly like to keep the verbose version, because it's important to be aware of the `RecordMapper` type, which can be implemented in a non-lambda fashion, of course.
