### ISSUE TITLE
Broken code in docs

### ISSUE THREAD

**Issue by benmccann** [jOOQ/jOOQ#6110]
This code snippet is inconsistent and uses both `MyBook2` and `MyBook3` meaning I doubt it compiles

    public class MyBook3 {
      public final String title;
      public final int id;
  
      @ConstructorProperties({ "title", "id"})
      public MyBook2(String title, int id) {
        this.title = title;
        this.id = id;
      }
    }

**Comment by lukaseder** [comment]
Thank you very much for your report. Fixed. Will be included in the manual after the nightly build.
