### ISSUE TITLE
how to create database from JPA annotations entities with jooq？

### ISSUE THREAD

**Issue by zzsoszz** [jOOQ/jOOQ#6135]
just like  hibernate.ddl-auto to generate with jpa antations,is there any way to do that?

**Comment by lukaseder** [comment]
Thank you very much for your enquiry.

jOOQ does not implement JPA, nor is it a formal JPA provider, so we do not currently intend to support this kind of code generation. You can easily use Hibernate for that task, though. In fact, the `JPADatabase` that is part of the `jooq-meta-extensions` module (see https://www.jooq.org/doc/latest/manual/code-generation/codegen-jpa) does precisely that: It uses Spring to load all JPA-annotated entities and uses Hibernate behind the scenes to generate an H2 in-memory database, which it then reverse engineers to jOOQ classes.

Hope this helps

**Comment by zzsoszz** [comment]
thanks for your answer!
i have tried JPADatabase,but how to configre the naming stratege  to control the column name.i found there are different when mapping nested object,jooq has no underscore ,spring data jpa  has underscore ;

@Entity
public class Activity {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	@OneToOne
	private ActivityResult activityResult;**_(activityResult will map to  activityresult_id in jooq,and map to activity_result_id in spring data jpa )_**
}
@Entity
public class ActivityResult {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id ;
	private String winningnumber;
}

**Comment by lukaseder** [comment]
I think the difference you're experiencing doesn't have anything to do with jOOQ, but rather with how Hibernate (used by jOOQ's `JPADatabase`) and Spring Data JPA differ, potentially. If you want to stay on the safe side, I'd consider these options:

- Put `@Table` annotations everywhere, e.g `@Entity @Table(name="activity_result") public class ActivityResult
- Personally, I'd write the DDL manually, and generate the JPA entities, not the other way round. This always pays off in the long run, but that's up to you.

**Comment by lukaseder** [comment]
Regarding 

> Personally, I'd write the DDL manually, and generate the JPA entities, not the other way round. This always pays off in the long run, but that's up to you.

I've finally written up a blog post explaining why I think "database first" should be preferred over "Java first" https://blog.jooq.org/2018/06/06/truth-first-or-why-you-should-mostly-implement-database-first-designs/
