### ISSUE TITLE
VarargsSetters property in AbstractGenerator.java but VarargSetters in jooq-codegen.xsd

### ISSUE THREAD

**Issue by epkugelmass** [jOOQ/jOOQ#6137]
jOOQ 3.9.2

It's not intuitive that the programmatic election of the new varargs setters configuration option is different from the XML version. This mildly increases the challenge of transitioning from XML to a programmatic configuration. It also makes it more challenging to use AbstractGenerator.java as a guide for writing the XML configuration.

https://github.com/jOOQ/jOOQ/commit/e4c59ac2972b4825135a468b1fce2fc7468e864c#diff-09ac4bfd3b6015c9e0de76470332a9f7R557

**Comment by lukaseder** [comment]
While I agree there's some unfortunate difference between the `Generator` class generated from the XSD using XJC (not under version control) and the `AbstractGenerator` API that you've seen in the commit message.

Yet, do not be confused by this commit. The programmatic API that you're using is generated from XSD using XJC, so there's a 1:1 match between the XML and programmatic APIs.

I think we might be better off to check in generated sources to avoid confusion. I've registered a feature request for this: https://github.com/jOOQ/jOOQ/issues/6139.

Thanks again for your message!
