### ISSUE TITLE
is there any way to integrate with spring data jpa?

### ISSUE THREAD

**Issue by zzsoszz** [jOOQ/jOOQ#6138]
i what use spring jpa generate database and complex query,and use jooq for scaled query. 
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

**Comment by lukaseder** [comment]
Thank you very much for your enquiry. There are many ways to integrate with JPA. We dedicated a short section of the manual to this topic:
https://www.jooq.org/doc/latest/manual/sql-execution/alternative-execution-models/using-jooq-with-jpa

I hope this answered your questions. If you have any specific questions, let us know and we'll be very happy to assist.
