### ISSUE TITLE
Update for Record with LocalDate primary key column fails

### ISSUE THREAD

**Issue by oflege** [jOOQ/jOOQ#6149]
When I try to update a Record with an (unmodified) LocalDate primary key (FEIERTAG.DATUM), the update fails with an exception:

 uncategorized SQLException for SQL [begin update "FEIERTAG" set "FEIERTAG"."BEMERKUNG" = ? where "FEIERTAG"."DATUM" = ? returning "FEIERTAG"."DATUM" into ?; ? := sql%rowcount; end;]; SQL state [99999]; error code [17004]; Invalid column type: 1111;

The problem seems to be that the "returning..." parameter is bound with type OTHER (1111) and oracle does not know how to handle that.
(A workaround would be to set DATA_OMIT_RETURNING_CLAUSE temporarily to true)

**Comment by lukaseder** [comment]
Thank you very much for reporting this. With what version are you seeing this error?

**Comment by lukaseder** [comment]
Hmm, there had been a couple of fixes related to `LocalDate` and other JSR-310 data types in https://github.com/jOOQ/jOOQ/issues/2738. I currently cannot seem to reproduce this issue in jOOQ 3.10. We'll evaluate again if this fix can be merged to 3.9.3

**Comment by lukaseder** [comment]
I can reproduce this error in jOOQ 3.9.2

**Comment by lukaseder** [comment]
Confirmed: #2738 fixes this issue. Will mark this as a duplicate and merge #2738 on version 3.9.3
