### ISSUE TITLE
Generate deprecation for all objects referencing DataType<Object> (unknown type)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6212]
It would be helpful for users to see that something is not configured correctly (e.g. missing custom data type binding), or if jOOQ is missing a feature (missing support for vendor-specific data type) by having a `@deprecated` annotation being generated on all objects that refer to a `DataType<Object>`

Obviously, this should be made configurable with a new setting.

**Comment by jdimeo** [comment]
This isn't working for me - in both 3.10.0 and 3.10.1 I have jOOQ configured:
```
<generator>
	<generate>
		<pojos>true</pojos>
		<interfaces>true</interfaces>
		<globalObjectReferences>false</globalObjectReferences>
		<fluentSetters>true</fluentSetters>
		<deprecationOnUnknownTypes>false</deprecationOnUnknownTypes>
	</generate>
	...
```
But deprecations are still being generated on my columns with unrecognized types. What am I missing?

**Comment by lukaseder** [comment]
Thanks a lot for reporting. Yeah, it would definitely help if we'd actually read the flag 😐 

![image](https://user-images.githubusercontent.com/734593/33141404-5399a722-cfb3-11e7-97ca-00f27a440e88.png)

Will fix immediately. This will be backported to 3.10.2 these days (#6846)

**Comment by lukaseder** [comment]
#6845 is now fixed on master. Thanks again for reporting.

**Comment by jdimeo** [comment]
No problem at all, thanks for the lightening fast response and fix!

**Comment by etiennestuder** [comment]
@lukaseder IMO, it would be informative to also mention `deprecationOnUnknownTypes` on the deprecation Javadoc (which currently only talks about adding a binding).

**Comment by lukaseder** [comment]
@etiennestuder : You're right, thanks for the suggestion. I've created #6958
