### ISSUE TITLE
Add a flag to enforce emulation of row value expression predicates

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6230]
Not all databases can handle row value expression predicates for optimal index usage.

We shouldn't generate such expressions in the SEEK clause, or at least provide a setting to override the behaviour.

Other feature emulations might need enforcement as well. Let's analyse this in a broader context.

----
See also:
http://stackoverflow.com/q/43986902/521799

**Comment by hecvd** [comment]
Well... good to know this is in the roadmap at least

**Comment by lukaseder** [comment]
Thank you for your comment, @hecvd. You can always expand row value expression predicates manually to their equivalent scalar value predicates, e.g. `(a, b) > (x, y)` is the same as `(a > x) or (a = x and b > y)`. This is obviously a bit more laborious if you use these predicates via the `seek()` clause.

What situation did you run into, where this caused any issues?

**Comment by hecvd** [comment]
Thanks your your answer Lukas!
It is basically what you described above. Our database doesn't support this type of row value expression and I was trying to find a way to force the sql renderer to use the `emulated` implementation of this. We'll either use the scala value predicates that are also mentioned in the blog post or a window function depending on each case. I thought it was strange nobody had requested to force one behavior over the other and then found this.

**Comment by lukaseder** [comment]
> Our database doesn't support this type of row value expression

What's your database? jOOQ translates SQL to many dialects, and when the predicate is not supported (e.g. in oracle), it automatically translates it to what I've described.

> I thought it was strange nobody had requested to force one behavior over the other and then found this

Why would they? If you write `(a, b) > (x, y)` in jOOQ, you probably want `(a, b) > (x, y)` in SQL. And again, if it's not supported, jOOQ already emulates it. It's rare that an emulation would want to be forced.

**Comment by hecvd** [comment]
Yes, now that you mention it, you are right. This use case shouldn't be that common. For this particular case, we are using spark sql through a jdbc and the default dialect. It works mostly fine.

**Comment by lukaseder** [comment]
I'm closing this issue - it hasn't seen much traction in the past years.

1. We currently don't want to offer a set of feature toggles to trigger the emulation of individual syntaxes irrespective of SQL dialect.
2. If a dialect is supported, we're already producing what we believe is optimal SQL. If it isn't, we can generate different SQL (as for the SEEK clause) via a dedicated issue.

So, there isn't really a need for this particular feature flag.
