### ISSUE TITLE
ExecuteContext can't get UpdateQuerylmpl 

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [jOOQ/jOOQ#6231]
I want to do some things after insert or update at special table
so i use ExecuteListener to get ExecuteContext,then i could know this query is StoreQuery or not,but i couldn't get table info,insert data field and data object map,because UpdateQuerylmpl and InsertQuerylmpl is protected.
what should i do to get a object like UpdateQuerylmpl,whick make me could get table info,etc.
waiting your reply

**Comment by lukaseder** [comment]
Thank you very much for your enquiry. There is currently no way to access the table of a DML statement through public API. I can see two options:

- Use internal API as you suggested
- Use a `VisitListener` to extract the relevant table information: https://www.jooq.org/javadoc/latest/org/jooq/VisitListener.html

I hope this helps
