### ISSUE TITLE
DataType.nullable() and defaultValue() are not generated for enum types

### ISSUE THREAD

**Issue by katsharp** [jOOQ/jOOQ#6241]
When generating a field of enum type the code generation defaults to a nullable field - event thought the column may be not nullable.

https://github.com/jOOQ/jOOQ/blob/eb33ce9cf729d778f425f7f944b55a2efd0a6dfd/jOOQ-codegen/src/main/java/org/jooq/util/JavaGenerator.java#L5399

This can cause problems later when using DSLContext.newRecord and Tools.resetChangedOnNotNull is then called.

**Comment by lukaseder** [comment]
Thank you very much for your bug report and for tracking this down to the right line of code. Indeed, neither the `nullable()` nor the `defaultValue()` information is being generated.

This affects MySQL and PostgreSQL. We'll fix this ASAP.

**Comment by lukaseder** [comment]
Hmm, other vendor-specific types (e.g. Oracle arrays) are also affected. Will need to check this further

**Comment by lukaseder** [comment]
This is now fixed for jOOQ 3.11. Will be merged to 3.10.6 (#7199) and 3.9.7 (#7200)
