### ISSUE TITLE
Create annotation to ignore a setter during record mapping

### ISSUE THREAD

**Issue by ypconstante** [jOOQ/jOOQ#6243]
Maybe it would be interesting to have annotation to identify that a method should be ignored during a record mapping. One situation that this annotation would be useful is #6242, if the annotation existed I could just mark the setter as ignored while the error is not fixed.

**Comment by lukaseder** [comment]
Yes indeed. That annotation already exists, it is called `@javax.persistence.Column` :) Hope this helps. More information on the [`DefaultRecordMapper` Javadoc](https://www.jooq.org/javadoc/latest/org/jooq/impl/DefaultRecordMapper.html)
