### ISSUE TITLE
Null batchSQL when running a batch with a single query

### ISSUE THREAD

**Issue by ypconstante** [jOOQ/jOOQ#6249]
When running a batch insert with a single query, the `contextExecuteListener.executeEnd` receives a context with the value of batchSQL as an array with a null value.

![upload](https://cloud.githubusercontent.com/assets/8113764/26221642/a3b1e562-3bed-11e7-92a2-d18d527ac8b9.png)

**Comment by lukaseder** [comment]
Thank you very much for your report. I'll investigate this ASAP

**Comment by lukaseder** [comment]
Hmm, I see where this got wrong. Internally, `DefaultExecuteContext` assumes that a `batchQueries[].length` of 1 means we're not actually executing a batch. That should be an easy fix.
