### ISSUE TITLE
XMLGenerator: UniqueConstraintCatalog set to referenced key instead of catalog

### ISSUE THREAD

**Issue by HansiJanosch** [jOOQ/jOOQ#6251]
During generation of XML the unique constraint catalog is set to the name of the referenced key instead of its catalog. This also leads to errors when trying to generate Java classes from this generated XML file.

>                     rc.setUniqueConstraintCatalog(referenced.getOutputName());

**Comment by lukaseder** [comment]
Thank you very much for your report. We'll fix this ASAP
