### ISSUE TITLE
Infinity values not correctly escaped with PostgreSQL

### ISSUE THREAD

**Issue by tPeltola** [jOOQ/jOOQ#6252]
When inserting floating point infinity in a batch with jOOQ to a PostgreSQL database, the insert fails with error:

`Caused by: java.sql.BatchUpdateException: Batch entry 2,547 insert into "s"."t" ("c1", "c2", "c3", "c4", "c5", "c6", "c7", "c8", "c9", "c10", "c11", "c12", "c13", "c14") values ('str', timestamp '2017-04-05 23:59:59.999', 1, 1, 1, 1, -1, 'A', 120, Infinity, 0.181, Infinity, null, 'NaN'::float4) on conflict do nothing was aborted: ERROR: column "infinity" does not exist`

https://www.postgresql.org/docs/9.6/static/datatype-numeric.html#DATATYPE-FLOAT describes how the infinity must be escaped inside single quotes. This is similar to NaN in https://github.com/jOOQ/jOOQ/issues/5250.

**Comment by lukaseder** [comment]
Thank you very much for reporting. We'll look into this ASAP.

The workaround here would be to implement a custom data type binding, which takes care of better SQL generation for these bind variables:
https://www.jooq.org/doc/latest/manual/sql-building/queryparts/custom-bindings

**Comment by tPeltola** [comment]
Yes, that is what I thought when I checked how NaN was handled, but run out of time to try last week. That does indeed work around the problem.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.15.0 and 3.14.9 (#11702)
