### ISSUE TITLE
Deprecate DSLContext.bindContext() and renderContext()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6280]
These methods should not have been exposed to public API and will be removed in jOOQ 4.0. The types they return are arguments to a variety of SPIs, including `QueryPart.accept(Context<?>)`, but there's no need to manually create such types.

----
See also: https://github.com/jOOQ/jOOQ/issues/6279

**Comment by billoneil** [comment]
I'm interested in being able to take apart / rewrite SQL. It seems like I would be able to use Context.visit to find various QueryParts. With these methods being deprecated is there any other way to achieve this?

An example would be taking an update statement and converting it to a select to predict how many rows would be impacted by the update.

**Comment by lukaseder** [comment]
Possibly a `VisitListener` is the right approach? But I doubt that it will be easy. Currently, the custom SQL transformation capabilities are very limited in jOOQ as most needed API is internal. We're working on improving this in a future release, by offering a public API to the complete query model.
