### ISSUE TITLE
Add DSL.arrayAggDistinct()

### ISSUE THREAD

**Issue by GuiSim** [jOOQ/jOOQ#6281]
Currently the DSL contains `*Distinct` variants of most aggregation functions.

```
maxDistinct
avgDistinct
sumDistinct
..
```

It does not however have a function for `ARRAY_AGG(DISTINCT ...)`

I think a `DSL.arrayAggDistinct(...)` could be pretty useful.

Thanks for the great library!

**Comment by lukaseder** [comment]
You're right, that definitely makes sense. Also, I've noticed that `listAgg()` (which translates to `STRING_AGG()` in PostgreSQL) doesn't have a distinct version either. Added another feature request: https://github.com/jOOQ/jOOQ/issues/6283
