### ISSUE TITLE
Don't generate type length modifier for PostgreSQL bytea types in DDL

### ISSUE THREAD

**Issue by DevCybran** [jOOQ/jOOQ#6289]
When executing a `createTable` DDL-statement in the following manner:
```
create
	.createTable("table1")
	.column("ID", SQLDataType.INTEGER.nullable(false))
	.column("field1", SQLDataType.BINARY(96)) // <-- Problem!
	.constraint(DSL.constraint("table1_primary").primaryKey("ID"))
	.execute();
```
which is transformed to the following SQL statement:
`SQL [create table "table1"("ID" int not null, "field1" bytea(96) null, constraint "table1_primary" primary key ("ID"))];`

The call fails on PostgreSQL databases (dialect `SQLDialect.POSTGRES`) with the following exception:
` org.postgresql.util.PSQLException: ERROR: type modifier is not allowed for type "bytea"`

This is most likely due to the explicit length on the binary field, which PostgreSQL does not support. It would be great if jOOQ would know about this limitation and omit the length of the binary field in this case.

**Comment by lukaseder** [comment]
Thank you very much for reporting. Hmm, yes interesting. So you're using this type length for compatibility reasons with other databases, right?

It certainly makes sense to avoid generating the length in PostgreSQL.

**Comment by lukaseder** [comment]
... hmm, what's your expectation towards the behaviour of a fixed-length `BINARY(96)` type in PostgreSQL, though, which knows only variable-length `bytea`? Wouldn't `VARBINARY(96)` be a better choice, here?

**Comment by DevCybran** [comment]
Basically I want my application to stay independent of the actual database system being used. The application has the requirement to store a fixed-length byte array in the database - whether the underlying database field has a static or dynamic length is not really important.
I use the length for compatibility reasons, and simply because it makes sense because I know the length upfront (and the database can possibly use this information to optimize the table layout - at least if it's not PostgreSQL ;) )
Using `VARBINARY(96)` does not really make sense, because I know the _exact_ length (also, I already tried that, it throws the same error). As a workaround, I currently check the database type for PostgreSQL and omit the length specification through custom type wrappers - but that's not ideal, as it adds database-system-dependent code, which I want to avoid.

Edit: Wow, quick fix, thanks!

**Comment by lukaseder** [comment]
I see, thanks for the info. Well, I suspect you could add a `CHECK` constraint in PostgreSQL:

```sql
CREATE TABLE t(x bytea check (octet_length(x) = 96));
```

In fact, we should probably generate that check constraint in the future. I've created a feature request for this: https://github.com/jOOQ/jOOQ/issues/6291

**Comment by DevCybran** [comment]
I just tested the application without my workaround against a PostgreSQL test database using the updated jOOQ master branch, and was able to verify the fix - everything is working as intended!

The `CHECK` constraint is a good idea, thank you!
