### ISSUE TITLE
Add support for the Teradata database

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#629]
See http://www.teradata.com/

----
Known limitations:
- Code generator support for foreign key relationships: #7520
- Stored procedures are not yet supported: #7529
- `QUALIFY` clause not yet supported: #7426
- `UNION .. LIMIT` not yet supported: #7531

**Comment by ylgkger** [comment]
Teradata is very popular database. We are looking forward to see the supporting for Teradata. Hope we can see this in next release.

**Comment by lukaseder** [comment]
Confirming, we'll implement Teradata support in jOOQ 3.11 (shipping probably in May 2018).
