### ISSUE TITLE
Confusing documentation versions

### ISSUE THREAD

**Issue by benmccann** [jOOQ/jOOQ#6302]
When I click "learn" at the top of the page, it shows the newest docs are 3.9: https://www.jooq.org/learn/

However, when I'm on a page for the 3.9 docs it says at the top: "This page in other versions: 3.10 | 3.9 | 3.8 | 3.7 | 3.6 | 3.5 | 3.4 | 3.3 | Old, end-of-life releases: 3.2 | 3.1 | 3.0 | 2.6 | 2.5"
https://www.jooq.org/doc/3.9/manual-single-page/#code-generation

So what's the newest? 3.9 or 3.10?

**Comment by lukaseder** [comment]
Thanks for reporting. Yeah, you're right, we messed that up (and it's a known issue: https://github.com/jOOQ/jOOQ/issues/6297). Will fix today.

**Comment by lukaseder** [comment]
This is now fixed. Your further feedback would be very welcome
