### ISSUE TITLE
Oracle flashback query for aliased table results in invalid sql

### ISSUE THREAD

**Issue by oflege** [jOOQ/jOOQ#6303]
invoking oracle's asOfScn(...) or asOfTimestamp(...) on an aliased table to create a flashback query results in an invalid sql statement that puts the alias before the " as of ..." clause, e.g.
"select ... from mytable **t** as of ... " instead of the correct syntax "select ... from mytable as of ... **t** "

**Comment by lukaseder** [comment]
Thank you very much for your report. We'll look into this immediately.

**Comment by lukaseder** [comment]
I can reproduce this using:

```java
Result<TAuthorRecord> a2 =
create().selectFrom(T_AUTHOR.as("a")
                            .versionsBetweenScnMinvalue()
                            .andMaxvalue())
        .orderBy(T_AUTHOR.as("a").ID)
        .fetch();
assertTrue(a2.size() >= 2);
```

Notice how the jOOQ API allows for constructing the illegal syntax explicitly by specifying the `AS` clause prior to the flashback query clauses.

The following works as a workaround:

```java
Result<TAuthorRecord> a3 =
create().selectFrom(T_AUTHOR.versionsBetweenScnMinvalue()
                            .andMaxvalue()
                            .as("a"))
        .orderBy(T_AUTHOR.as("a").ID)
        .fetch();
assertTrue(a3.size() >= 2);
```

This fix will internally rewrite version 1) presented above to version 2)

**Comment by lukaseder** [comment]
Fixed. We'll backport this to jOOQ 3.9.4. Thanks again for reporting!
