### ISSUE TITLE
ALTER TABLE .. ADD COLUMN ignores column type's DEFAULT clause

### ISSUE THREAD

**Issue by DevCybran** [jOOQ/jOOQ#6316]
When adding a column to an existing table with a default value through the `alterTable` DSL, the default value is ignored and will not be part of the generated SQL statement. This will either silently produce a wrong table layout, or fail with an error if the column is non-nullable and the table to be altered already contains rows.

Example:
```
dsl
	.alterTable("my_table")
	.addColumn("new_important_column", SQLDataType.TINYINT.nullable(false).defaultValue(1))
	.execute();
```
will lead to SQL statement:
```
alter table `my_table` add `new_important_column` tinyint not null
```

This occurs with all database systems and all column data types I have tested so far. When creating a new table instead, the default value will be applied as expected.

**Comment by lukaseder** [comment]
Thank you very much for reporting. Indeed, I can confirm this currently only works for `CREATE TABLE`, not `ALTER TABLE .. ADD` statements. We'll fix this ASAP.
