### ISSUE TITLE
Generate javax.persistence.Index annotation

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6323]
If JPA annotations are generated, we should also generate `@Index` annotations, similar to the existing `@UniqueConstraint` annotations that are being generated on entities

**Comment by garethjrichards** [comment]
Did this fix just break backwards compatibility with JPA 2.0? @Index doesn't seem to be available in any JPA 2.0 implementation I can find.

**Comment by lukaseder** [comment]
Thank you very much for the hint, @garethjrichards. You're right, this is an oversight. I've created a new issue that allows for specifying the JPA version compatibility to the code generator: https://github.com/jOOQ/jOOQ/issues/6772

We'll backport this new feature to 3.10.2, which should ship in early November. As a workaround, I suggest post-processing the generated sources by removing all references to this annotation.

Alternatively, you can patch / override the `JavaGenerator.printTableJPAAnnotation()` method.

**Comment by garethjrichards** [comment]
No problem @lukaseder , might just move to the 2.1 spec regardless. Which implementation would you recommend for this EclipseLink, Hibernate, or DataNucleus?

**Comment by lukaseder** [comment]
Oh, ehm... A JPA implementation recommendation... Let's see, how could I possibly answer this? :) What are you going to use JPA *for*?

**Comment by garethjrichards** [comment]
Sorry, didn't make myself clear. I meant what implementation of javax.persistence would you recommend for JPA 2.1 spec in JOOQ. We still have some use of the JOOQ generated Record objects which use JPA.

**Comment by lukaseder** [comment]
I'm really not sure what you're asking here. We generate JPA annotations for documentation purposes, not to actually use the generated objects as entities. For that, a lot of annotations would still be missing (e.g. we don't generate any relationship annotations). So, if you want to work with entities, you better generate them using your preferred JPA provider directly, and I really cannot make any recommendations about those. They're all rather different, but people often pick the one that ships with their application server (or default to Hibernate, outside of application servers)

**Comment by garethjrichards** [comment]
I see, I was unaware it was documentation only. The [docs](https://www.jooq.org/doc/2.6/manual/getting-started/dependencies/) seemed to point to a dependency on javax.persistence when enabling record models. I naively assumed it was required. I have since seen that JPA annotations can be removed from generation entirely (which for us is much better). Thanks for pointing me in the right direction.

**Comment by lukaseder** [comment]
Sorry, I was imprecise. Yes we also have a runtime dependency on those annotations for two reasons:

- If we generate them, we also need to be able to link them at runtime
- The `DefaultRecordMapper` can actually use `@Column` annotations for its mapping. This doesn't correspond to a TCK-compliant JPA implementation at all, though. We're just using the fact that pre-existing entities might have intereting column name information for our mappers.
