### ISSUE TITLE
Exception thrown when creating table with converted VARCHAR type

### ISSUE THREAD

**Issue by Faithcaio** [jOOQ/jOOQ#6330]
As requested (https://github.com/jOOQ/jOOQ/issues/5807) here the issue with a small example maven project:
https://github.com/Faithcaio/jOOQIssueExample

Just run the main function to reproduce.

```
Exception in thread "main" org.jooq.exception.DataAccessException: SQL [create table `mytablename`(`id` int not null auto_increment, `name` varchar not null)]; You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'not null)'
```
___
Creating a Table with a DataType which is a String (or anything that has a length) representation of something fails because the VARCHAR type is missing the length.

From my example:
Generated DDL:
```sql 
create table `mytablename`(`id` int not null auto_increment, `name` varchar not null)
```
Expected:
```sql 
create table `mytablename`(`id` int not null auto_increment, `name` varchar(64) not null)
```
___
This is because `Tools#toSQLDDLTypeDeclaration` checks for `DataType#hasLength` which is implemented in `DefaultDataType` as `return (type == byte[].class || type == String.class) && !isLob();`
Obviously my Player class is none of those so the length is not added.

I think this could be fixed by checking if `binding.converter().fromType()` has a length instead of type

**Comment by lukaseder** [comment]
Thank you very much for your report and for the detailed investigation. I'll look into this ASAP

**Comment by lukaseder** [comment]
Indeed, I can reproduce this and your assessment is correct. We shouldn't compare types with `DefaultDataType.type` but with `DefaultDataType.binding.converter().fromType()` instead.

This is a delicate change, I'll need to further investigate this, but I'm sure this issue is different from #5807. I'll delete the comments there.

**Comment by lukaseder** [comment]
I can confirm that your suggested fix would solve this problem.

**Comment by lukaseder** [comment]
I've created another issue https://github.com/jOOQ/jOOQ/issues/6331 which describes this problem on a more general scale.

**Comment by lukaseder** [comment]
Good news, no regressions were discovered.
