### ISSUE TITLE
Error when passing java.util.Date to DSL.timestamp()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6333]
The following error is raised when passing a `java.util.Date` instance (not a subtype like `java.sql.Date` or `java.sql.Timestamp`) to the `DSL.timestamp() method:

> [main] WARN org.jooq.exception.SQLDialectNotSupportedException - Not supported by dialect : Type class java.util.Date is not supported in dialect DEFAULT

**Comment by LassoMike** [comment]
same issue with `DSL.date()` method

**Comment by lukaseder** [comment]
@LassoMike Does the problem still persist with version 3.10.0? Note, the fix hasn't been backported to 3.9 and 3.8 yet. I've scheduled a backport for 3.9.7 and 3.8.10

**Comment by LassoMike** [comment]
my apologies, im using 3.9.3, time to update!
