### ISSUE TITLE
aliasing in fields, TABLE.fieldStream().map(field -> field.as("category_"+field.getName())).toArray(Field[]::new)

### ISSUE THREAD

**Issue by kingbbode** [jOOQ/jOOQ#6350]
Hello.

I am using a DTO object that contains Jooq pojo.

```java
Class DTO {
 Long idx;
 JTableA atable;
 JTableB btable;
}
```

I use `fetchMap` to get the Map, and `ModelMapper` to DTO.

```java
 List<Map<String, Object>> record =
                dsl
                        .select(TABLE_A.IDX.as("Idx"))
                        .select(TABLE_A.fieldStream().map(field -> field.as("atable_"+field.getName())).toArray(Field[]::new))
                        .select(CATEGORY.fieldStream().map(field -> field.as("btable_"+field.getName())).toArray(Field[]::new))
                        .from(TABLE_A)
                        .join(TABLE_B).on(TABLE_B.IDX.eq(TABLE_A.TABLE_B_IDX))
                        .fetchMaps();
        List<DTO> contentResponses = modelMapper.map(record, new TypeToken<List<DTO>>() {
        }.getType());
```

It is cumbersome and unclear to associate an alias to the joins of two tables at this case.

```java
TABLE.fieldStream().map(field -> field.as("atable_"+field.getName())).toArray(Field[]::new)
```

So I think that the basic support of this feature can make JOOQ better.

For example,

```java
Field<?>[] fields(java.util.function.Function<? super Field<?>,? extends String> aliasFunction)
```
More simply,

```java
Field<?>[] fieldsWithPrefix(String prefix)
Field<?>[] fieldsWithPrefix(String prefix, String... fieldNames)
```

Thank you

Cheers !!

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. We'll look into this. Surely, there's room for improvement, but we shouldn't jump to adding too many of these utility functions. For instance, I don't think a `fieldsWithPrefix()` method is a good idea.

Note, you can already create a derived column list using functions when using `Table.as(String, Function)`

**Comment by kingbbode** [comment]
In this situation, `Table.as(String, Function)` is inefficient.

```java
Table<JPostsRecord> posts = POSTS.as("POSTS", field -> "post_"+field.getName());
        Table<JCommentsRecord> comments = COMMENTS.as("COMMENTS", field -> "comments_"+field.getName());
        return dsl
                .select(posts.fields("post_ID", "post_TITLE"))
                .select(comments.fields("comments_NAME", "comments_EMAIL", "comments_CONTENT"))
                .from(posts)
                .join(comments).on(comments.field("comments_POST_ID", Integer.class).eq(posts.field("post_ID", Integer.class)))
                .where(comments.field("comments_EMAIL").isNotNull()
                        .and(posts.field("post_NAME", String.class).ne(comments.field("comments_NAME", String.class))))
                .fetchMaps();
```


when using `Table.as(String, Function)`, we can not use `JOOQ POJO`. So we have to specify the prefix and type class in all the conditions of the subordinate.

**query**
```
select `POSTS`.`post_ID`, `POSTS`.`post_TITLE`, `COMMENTS`.`comments_NAME`, `COMMENTS`.`comments_EMAIL`, `COMMENTS`.`comments_CONTENT` from (select * from (select null as `post_ID`, null as `post_TITLE`, null as `post_CONTENT`, null as `post_CREATED_ON`, null as `post_NAME` from dual where 1 = 0) x union all select * from (select * from `jooq-practice`.`POSTS` as `POSTS`) x) as `POSTS` join (select * from (select null as `comments_ID`, null as `comments_POST_ID`, null as `comments_NAME`, null as `comments_EMAIL`, null as `comments_CONTENT`, null as `comments_CREATED_ON` from dual where 1 = 0) x union all select * from (select * from `jooq-practice`.`COMMENTS` as `COMMENTS`) x) as `COMMENTS` on `COMMENTS`.`comments_POST_ID` = `POSTS`.`post_ID` where (`COMMENTS`.`comments_EMAIL` is not null and `POSTS`.`post_NAME` <> `COMMENTS`.`comments_NAME`)
```

In addition, I need only a prefix, not a table alias. Table aliases make the query complex.

So I made the utilities.

```java
return dsl
                .select(JooqUtil.prefixAlias("post_", POSTS, "ID", "CONTENT"))
                .select(JooqUtil.prefixAlias("comments_", COMMENTS, "NAME", "EMAIL", "CONTENT"))
                .from(POSTS)
                .join(COMMENTS).on(COMMENTS.POST_ID.eq(POSTS.ID))
                .where(COMMENTS.EMAIL.isNotNull()
                        .and(POSTS.NAME.ne(COMMENTS.NAME))
                )
                .fetchMaps();
```

Because alias is a prefix for output, you can use Jooq pojo. we can use Jooq Pojo to make coding more stable and clean.

**query**
```
select `jooq-practice`.`POSTS`.`ID` as `post_ID`, `jooq-practice`.`POSTS`.`CONTENT` as `post_CONTENT`, `jooq-practice`.`COMMENTS`.`NAME` as `comments_NAME`, `jooq-practice`.`COMMENTS`.`EMAIL` as `comments_EMAIL`, `jooq-practice`.`COMMENTS`.`CONTENT` as `comments_CONTENT` from `jooq-practice`.`POSTS` join `jooq-practice`.`COMMENTS` on `jooq-practice`.`COMMENTS`.`POST_ID` = `jooq-practice`.`POSTS`.`ID` where (`jooq-practice`.`COMMENTS`.`EMAIL` is not null and `jooq-practice`.`POSTS`.`NAME` <> `jooq-practice`.`COMMENTS`.`NAME`)
```

We can see a cleaner query than before.

Although I can personally create and use this utility, So I think that the basic support of this feature can make JOOQ better.

**Comment by lukaseder** [comment]
Thank you again for your comments and for your suggested pull request. I really think this kind of convenience API / utility needs much more thought before being added to jOOQ. I think the workaround by writing such a utility yourself is totally acceptable right now:

```java
return dsl
    .select(JooqUtil.prefixAlias("post_", POSTS, "ID", "TITLE"))
    .select(JooqUtil.prefixAlias("comments_", COMMENTS, "NAME", "EMAIL", "CONTENT"))
```

jOOQ is a SQL expression tree API and as such allows for powerful composition of SQL `QueryParts` very easily. People do this all the time. Before we add something like this into the core API, I'd really like to think this through a lot more, first.

**Comment by kingbbode** [comment]
Thank you. I just wanted to alias the field only as shown below.

```
return dsl
                .select(POSTS.fields(field -> "comments_"+field.getName(), "ID", "TITLE" ))
                .select(COMMENTS.fields(field -> "comments_"+field.getName(), "NAME", "EMAIL", "CONTENT"))
                .from(POSTS)
                .join(COMMENTS).on(COMMENTS.POST_ID.eq(POSTS.ID))
                .where(COMMENTS.EMAIL.isNotNull()
                        .and(POSTS.NAME.ne(COMMENTS.NAME))
                )
                .fetchMaps();
```

Thank you for your answer.

**Comment by lukaseder** [comment]
Sure, I understand your request and that's a perfectly valid use-case. I just want to think this through more thoroughly.

**Comment by kingbbode** [comment]
Thank you. I just wanted to alias the field only as shown below.

```
return dsl
                .select(POSTS.fields(field -> "comments_"+field.getName(), "ID", "TITLE" ))
                .select(COMMENTS.fields(field -> "comments_"+field.getName(), "NAME", "EMAIL", "CONTENT"))
                .from(POSTS)
                .join(COMMENTS).on(COMMENTS.POST_ID.eq(POSTS.ID))
                .where(COMMENTS.EMAIL.isNotNull()
                        .and(POSTS.NAME.ne(COMMENTS.NAME))
                )
                .fetchMaps();
```

It was a mistake that the function was written up to the `ROW`.
Only the changes of these four classes are possible.

- TableLike
- AbsractTable
- SelectImpl
- SelectQueryImpl

Do not want to add this feature to TableLike? 
Thank you for your answer.

**Comment by lukaseder** [comment]
Thank you for your additional feedback.

1) I understand your use-case
2) I want to give this more thought before proceeding

Thanks for your understanding.

**Comment by kingbbode** [comment]
Thank you.

Cheers !! I Love jOOQ.

**Comment by pschichtel** [comment]
I'm not entirely sure I get the issue, but still: Couldn't this be done using a VisitListener? I recently did a [table prefixing listener](https://github.com/CubeEngine/core/blob/master/libcube/src/main/java/org/cubeengine/libcube/service/database/mysql/TablePrefixer.java) to transparently support table prefixes.

**Comment by lukaseder** [comment]
@pschichtel Sure, there are many ways to do these things and a `VisitListener` is certainly one of them (thanks for sharing!).

However, a `VisitListener` is a globally applicable utility, whereas the suggestion being discussed here is local, i.e. for the scope of a single query.

**Comment by lukaseder** [comment]
Years later, and I'm still not convinced we should add such auxiliary API to jOOQ. It seems like too much of a clever, ad-hoc solution, difficult to align with a big API like jOOQ in a consistent way. When in fact, the client side auxiliary method is super easy to implement.

Users are often disappointed when the fluent API "breaks" in jOOQ, but I had much rather occasional "breakage" than surprising, inconsistent API. This is also why the other functional methods are going to be deprecated: #10156.

I'm closing this as won't fix. External tools are sufficient. A new jOOQ API will not suffice. Someone will come and want a `filter(Predicate)` method that filters on these columns prior to aliasing. And before we know it, we've re-built the `Stream` API.
