### ISSUE TITLE
Call PostgreSQL function with two dimensional array as a parameter

### ISSUE THREAD

**Issue by risbarov** [jOOQ/jOOQ#6351]
Hello dear support team!

I'm using JOOQ 3.9.2 and PostgreSQL 9.6.2. In my DB I have function with **two dimensional array** as a parameter:

```
FUNCTION fn_modify_token (dict_id BIGINT, col_value TEXT[][]) RETURNS TEXT
```

Is it possible to call this function via JOOQ?
I read https://www.jooq.org/doc/3.9/manual/sql-execution/stored-procedures but I can't use generated methods in Routines.java, because JOOQ generates one-dimensional array:

```java
public static String fnModifyToken(Configuration configuration, Long dictId, String[] colValue) {
    ...
}
```

Thanks!

**Comment by lukaseder** [comment]
Thanks for your enquiry. PostgreSQL's two-dimensional arrays are currently not supported by jOOQ: https://github.com/jOOQ/jOOQ/issues/252
