### ISSUE TITLE
formatJSON() for Records

### ISSUE THREAD

**Issue by jc064522** [jOOQ/jOOQ#6354]
`fetch()` returns a `Result` and `fetchOne()` returns a `Record`. Only `Result`s have `formatJSON()`. 

This built-in formatting is really useful. But if I can't use it in both cases I need to roll something else. If I have to roll something else then I'll just use that instead of `formatJSON()`, which seems like a shame. 

Is there any way to have this functionality on both please?

**Comment by jc064522** [comment]
Happy to consider submitting a PR if you can give me some guidance about the best way forward.

**Comment by lukaseder** [comment]
Thanks for reporting. You're absolutely right, which is why we've already implemented it for the upcoming jOOQ 3.10 (due for late Q3 2017): https://github.com/jOOQ/jOOQ/issues/5894

**Comment by lukaseder** [comment]
Note, as a workaround, you can wrap a single record in a `Result` using `DSLContext.newResult(fields).add(record)` and call `formatJSON()` on that...

**Comment by jc064522** [comment]
Thanks for the pointer. I'll do that for now.
