### ISSUE TITLE
Cannot interpret argument of type class org.jooq.impl.SelectImpl as a Field

### ISSUE THREAD

**Issue by ciaccia** [jOOQ/jOOQ#6360]
Hi Lukas,
Check this situation where we have 2 tables containing each 1 column. I want to extract the minimal value from both columns

(in Postgres)
```
create table a(t timestamptz);
create table b(t timestamptz);

insert into a(t) values ('2017-01-01T10:00:00.000+02:00'), ('2017-01-02T10:00:00.000+02:00'), ('2017-01-03T10:00:00.000+02:00'), ('2017-01-04T10:00:00.000+02:00'); 
insert into b(t) values ('2017-01-03T20:00:00.000+02:00'), ('2017-01-04T05:00:00.000+02:00'); 

select least((select min(a.t) from a as a), (select min(b.t) from b as b));
```

When I try to execute the same SQL statement in jOOQ:
```
Record1<SelectJoinStep<Record1<Timestamp>>> record = dslCtx.select(DSL.least(DSL.select(DSL.min(Tables.A.T)).from(Tables.A), DSL.select(DSL.min(Tables.B.T)).from(Tables.B))).fetchOne();
```
I get the following exception:
```
java.lang.IllegalArgumentException: Cannot interpret argument of type class org.jooq.impl.SelectImpl as a Field: select min("public"."a"."t")
from "public"."a"
```

I know I can rewrite the same SQL using a cross join (it also works fine in jOOQ):
```
select least(min(a.t), min(b.t)) from a as a, b as b;
```
I was just wondering why it didn't work.
Cheers

**Comment by lukaseder** [comment]
Thank you very much for your enquiry. You have to use [`Select.asField()`](https://www.jooq.org/javadoc/latest/org/jooq/FieldLike.html#asField--) or [`DSL.field(Select)`](https://www.jooq.org/javadoc/latest/org/jooq/impl/DSL.html#field-org.jooq.Select-) to transform a select statement to a `Field` when passing it to `least()`.

It would certainly make sense for jOOQ to do that automatically, though, as your code doesn't look wrong from a user perspective. I have registered a feature request for this: https://github.com/jOOQ/jOOQ/issues/6362

Note, you shouldn't use a cross join here. A cross join might generate a lot of unnecessary load in the database. An alternative I could think of is to write this query:

```sql
select min(t)
from (
  select t from a
  union all
  select t from b
) x
```

**Comment by ciaccia** [comment]
Hi Lukas, thanks a lot for your answer.

I have just a question about this: do you know why (Eclipse Oxygen) loses the template <T> if I don't assign the step to a variable first? I try to be clearer with an example... Here I can get the `java.sql.Timestamp` without any cast:
```
SelectSelectStep<Record1<Timestamp>> step = dslCtx.select(DSL.least(DSL.select(DSL.min(A.T)).from(Tables.A).asField(), DSL.select(DSL.min(B.T)).from(Tables.B).asField()));
java.sql.Timestamp t = step.fetchOne().value1();
````
Here below I don't assign the step to a variable first writing everything inline:
```
Record1<Object> record = dslCtx.select(DSL.least(DSL.select(DSL.min(A.T)).from(Tables.A).asField(), DSL.select(DSL.min(B.T)).from(Tables.B).asField())).fetchOne();
````

The Record1 has an Object template and I couldn't find any way to fix it. Is this a jOOQ issue, a Java Generics limitation or an Eclipse issue?

**Comment by lukaseder** [comment]
Hmm, it's a combination of things. If you're using `asField()`, then type inference needs to kick in to infer the `<T>` type of the resulting `Field<T>` that is passed to the `DSL.least()` function.

If you'd be using `DSL.field(Select)` instead, this wouldn't happen.
