### ISSUE TITLE
Create an alias for Table.as (reserved word in Kotlin)

### ISSUE THREAD

**Issue by olivierlemasle** [jOOQ/jOOQ#6361]
`as` is a reserved word in Kotlin.

Therefore, Kotlin users are forced to use the cumbersome syntax

```kotlin
MY_TABLE.`as`("alias")
```

Providing an alias to [`Table.as()`](https://www.jooq.org/javadoc/latest/org/jooq/Table.html#as-java.lang.String-), such as `aliased` (or `alias` ?), would allow the less concise but more readable syntax:

```kotlin
MY_TABLE.aliased("alias")
```

**Comment by olivierlemasle** [comment]
BTW, there is the same issue with [`Field.in()`](https://www.jooq.org/javadoc/latest/org/jooq/Field.html#in-T...-).

**Comment by lukaseder** [comment]
Thanks for pointing this out. This is unfortunate indeed, but we're definitely open to aliasing these method names. We've already done so with `DSL.value()` -> `DSL.val()` for an improved Scala experience.

**Comment by lukaseder** [comment]
I'll postpone this for now. While `DSL.value()` / `DSL.val()` is perfectly fine as `val()` is not a SQL keyword but just jOOQ API, things are different with `as` and `in`, which correspond to well-known SQL keywords. Discovering an alias for them in the jOOQ API might be more effort than quoting them. So, the solution might not be as straight-forward as aliasing the method to `alias`.

Will keep thinking about this, and collect more community feedback.

**Comment by olivierlemasle** [comment]
I understand your concern.

Regarding `Field.in()`, there's another solution. In a Kotlin project using jOOQ, it is possible to add these extension functions:

```kotlin
// Could also be "inSet" instead of "isIn"
fun <T> Field<T>.isIn(vararg values: T) = this.`in`(*values)
fun <T> Field<T>.isIn(vararg values: Field<*>) = this.`in`(*values)
fun <T> Field<T>.isIn(values: Collection<*>) = this.`in`(values)
fun <T> Field<T>.isIn(result: Result<out Record1<T>>) = this.`in`(result)
fun <T> Field<T>.isIn(query: Select<out Record1<T>>) = this.`in`(query)
```

These functions could also be added to a project jOOQ-kotlin (cf #6256, even if I share you doubts over operator precedence). The benefit of this solution is to hide the alias to non-Kotlin jOOQ users.

For `Table.as()`, extension functions are also possible but not sufficient:

```kotlin
fun <R : Record> Table<R>.alias(alias: String): Table<R> = this.`as`(alias)
fun <R : Record> Table<R>.alias(alias: String, vararg fieldAliases: String): Table<R> = this.`as`(alias, *fieldAliases)
```

`Table.as()` is overriden in jOOQ-generated classes, with "more precise" return type, so the alias cannot be done by a single extension method and would require a change in jOOQ generator.

**Comment by lukaseder** [comment]
Revisiting this issue. I like the fact that in Kotlin, anyone can create their own extension functions to "fix" issues like these without any hassle. I can't seem to like any of the alternatives enough to include them in the API.

`IN` is such an obvious, clear SQL term, it's hard to replace it by anything else. Besides, there are a ton of `in` methods in all `Row` APIs, as well as `notIn()` methods which should probably be aliased consistently.

The same is true for `as`, which is a keyword that is repeated in many contexts in SQL:

- `CREATE TABLE .. AS ..`
- `CREATE VIEW .. AS ..`
- `WITH .. AS (..)`
- `[ column name ] AS ..`
- `[ table name ] AS ..`

Again, many methods distributed across the API would need an alias.

I'm still undecided what to do here.

**Comment by lukaseder** [comment]
I'm looking at this suggestion once more. I really don't like adding aliases for `as` and `in` just for the Kotlin use case. The rationale is given in my previous comment:
https://github.com/jOOQ/jOOQ/issues/6361#issuecomment-463996674

The keywords `as` and `in` are just way too common in the SQL language, and an alias such as `alias()` would not be discovered easily. An alias such as `as_()` would be discoverable, but equally ugly as `` `as()` ``. Besides, the additional byte code size for all the overloads really doesn't pull its weight. There's no winning solution here.

In languages like Kotlin, it is very easy to create things like `inline` functions that take care of aliasing third party method names. That way, arguments about whether the alias should be called `alias()` or `aliased()` or `as_()` or something else can be offloaded to user code.

I'm closing this as "won't fix"
