### ISSUE TITLE
Support PostgreSQL ON CONFLICT with conditional conflict target

### ISSUE THREAD

**Issue by sgrimm-sg** [jOOQ/jOOQ#6365]
If you have a table with a partial unique index (in the example, on `col1` values less than 10), the following SQL works:

```
INSERT INTO mytable (col1, col2) VALUES (1, 2)
ON CONFLICT (col1) WHERE col1 < 10 DO UPDATE SET col2 = 2;
```

Unfortunately, there seems to be no way to get jOOQ to generate this SQL; the `onConflict()` method doesn't return a query part that accepts a `.where()` call.

jOOQ version: 3.9.1
Database: PostgreSQL 9.6
Java version: 1.8.0_121

**Comment by sgrimm-sg** [comment]
My initial version of this issue was not correct, so I edited it to demonstrate the actual limitation rather than my own confusion.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. We're aware of this limitation and will provide a solution in jOOQ 3.10: https://github.com/jOOQ/jOOQ/issues/5637.

**Comment by S-Berhane** [comment]
Hi @lukaseder, just wondering if this was actually resolved? If so, could you provide an example?

To me, it still doesn't seem possible to add a predicate to the conflict. 
Handling conflicts for partial unique indexes in postgres can't be specified by its name, so doing `ON CONFLICT (col1) WHERE col1 < 1` is necessary.

**Comment by S-Berhane** [comment]
nvm it's still open here https://github.com/jOOQ/jOOQ/issues/6736.

**Comment by lukaseder** [comment]
@S-Berhane Thanks for your message. Yes, it's a duplicate.
