### ISSUE TITLE
Field.in(Collection<?> values) should take Collection<? extends T>

### ISSUE THREAD

**Issue by adrianmsmith** [jOOQ/jOOQ#6387]
Field has the following methods:

    Condition in(Collection<?> values);
    Condition in(T... values);

But as far as I can see, if one method takes a T... then the other method should take a `Collection<? extends T>` (as opposed to `Collection<?>`).

Right now I had a runtime error, because of passing the wrong things to in(...), and I think, that's what jOOQ should defend against :)

**Comment by lukaseder** [comment]
Ah, yes, the delicate details and depths of maintaining an internal domain specific language in a host language as primitive as Java :)

You may have noticed that your method list is incomplete. There are really:

```java
Condition in(Collection<?>);
Condition in(Field<?>...);
Condition in(Result<? extends Record1<T>>);
Condition in(Select<? extends Record1<T>>);
Condition in(T...);
```

Let's examine this from a language feature perspective. While Java supports method overloading, it erases generics, has covariant arrays (and thus a risk of heap pollution), and doesn't support union types. The real API that would be desirable instead is:

```java
Condition in(Many<T>)
```

Where the hypothetical type alias `Many` stands for:

```java
// A single "T" value is either a bind value or an expression of type "T"
type One<T> = T | Field<T>
type Many<T> = 
    Collection<One<T>>
  | Varargs<One<T>>
  | Result<? extends Record1<T>>
  | Select<? extends Record1<T>>
```

If jOOQ were written in a more advanced language (e.g. Ceylon), then certainly, we wouldn't have the regrettable `in(Collection<?>)` method. But in Java, lacking the aforementioned language features, this is as close as it gets to supporting the above `in(Many<T>)` predicate.

Hope this helps

**Comment by adrianmsmith** [comment]
Thanks for the answer!
