### ISSUE TITLE
DSLContext.ddl() should distinguish between table types (table, temporary table, view, etc.)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6412]
Currently, our generated runtime meta model only knows about tables.

In the future, we should be able to distinguish tables from views (see also #2370), from materialised views, from temporary tables, etc. This information should then be used to distinguish between the different object types when generating DDL through `DSLContext.ddl()`

- [x] `TABLE` (already supported, the default)
- [x] `TEMPORARY`
- [x] `VIEW`
- [x] `MATERIALIZED_VIEW`: Support DDL statements first: https://github.com/jOOQ/jOOQ/issues/9483

**Comment by lalithsuresh** [comment]
Is there any work under way on this? It would be very useful to have! In particular, we'd like to extract out tables and views from a database using the code generator, and have our application create identical tables and views at runtime. As of now, we're forced to run a script out of band to create the views we need because the DDL treats views as tables.

**Comment by lukaseder** [comment]
Thanks for the feedback, @lalithsuresh. Indeed, it would be very useful to have. It's definitely something worth looking into in jOOQ 3.12. Of course, this is part of a far bigger change than just the `ddl()` API, so no promises yet.

**Comment by lukaseder** [comment]
We're implementing this feature for jOOQ 3.13. I have already implemented support for exporting DDL produced by our new DDL interpreter. For this, we first needed a new `TableOptions` class that contains all the extra meta model information, including the `Select` statement, or whether the view is materialised, etc (see https://github.com/jOOQ/jOOQ/issues/2370).

We'll then proceed to supporting the code genenration of such `TableOptions` classes in generated code. That, too will be done through https://github.com/jOOQ/jOOQ/issues/2370.
