### ISSUE TITLE
byte[] record field code generation fails errorprone checks

### ISSUE THREAD

**Issue by jbarnettwomply** [jOOQ/jOOQ#6414]
http://errorprone.info/ from google finds the following issue with jooq generated code: http://errorprone.info/bugpattern/Overrides

The generated class in this case is 
```
public class XyzRecord extends UpdatableRecordImpl<XyzRecord> implements Record11<Long, byte[], byte[], String, byte[], String, Instant, Instant, Integer, Instant, Instant> {
```

and reports the following errors on the byte[] fields:
```
[Overrides] Varargs doesn't agree for overridden method
    public XyzRecord value2(byte... value) {
                           ^
    (see http://errorprone.info/bugpattern/Overrides)
  Did you mean 'public XyzRecord value2(byte[] value) {'?

[Overrides] Varargs doesn't agree for overridden method
    public XyzRecord value3(byte... value) {
                           ^
    (see http://errorprone.info/bugpattern/Overrides)
  Did you mean 'public XyzRecord value3(byte[] value) {'?

[Overrides] Varargs doesn't agree for overridden method
    public XyzRecord value5(byte... value) {
                           ^
    (see http://errorprone.info/bugpattern/Overrides)
  Did you mean 'public XyzRecord value5(byte[] value) {'?
```

The fields that generate these are defined in postgres as `BYTEA NOT NULL`

Would it be possible to update the code generator to define arrays instead of varags and not fail this check?

Thanks

**Comment by lukaseder** [comment]
Thank you very much for your report. Please use the code generation flag introduced with https://github.com/jOOQ/jOOQ/issues/5733 in 3.9.2 to revert to generating arrays as method argument types, rather than varargs

**Comment by jbarnettwomply** [comment]
setting `<generator><generate><vargargSetters>false</varargSetters></generate></generator>` in our maven plugin configuration worked, thanks!
