### ISSUE TITLE
Change SQLite's INSERT .. VALUES implementation to support standard multi-row VALUES() clause

### ISSUE THREAD

**Issue by nathanmerrill** [jOOQ/jOOQ#6418]
If I run the following:

    create.loadInto(table).bulkAfter(5000).loadJSON(items).fields(table.fields()).execute()

on a SQLite database, jOOQ will try to use a compound select (joining the 5000 tables together) to insert the data.  SQLite only[ supports up to 500 terms in a compound select](https://sqlite.org/limits.html)

I don't understand why it even needs to do a compound select at all.  Wouldn't using a single table with VALUES() work much better?

**Comment by lukaseder** [comment]
Thanks for reporting this. That's interesting. When we first added SQLite support, the multi-row `VALUES()` clause was not yet supported as can be seen in this archived version of the manual:
https://web.archive.org/web/20120327113710/http://sqlite.org/lang_insert.html

The feature was supported in version 3.7.11:
https://sqlite.org/changes.html#version_3_7_11

It definitely makes sense to change the jOOQ implementation then. We'll do this for jOOQ 3.10

**Comment by lukaseder** [comment]
This change will require SQLite 3.7.11 from jOOQ 3.10 onwards.

**Comment by lukaseder** [comment]
This also affects the standalone `DSL.values()` constructor

**Comment by nathanmerrill** [comment]
Awesome, thanks!  Can't wait for 3.10, then.
