### ISSUE TITLE
returning on conflict inserts

### ISSUE THREAD

**Issue by jottyfan** [jOOQ/jOOQ#6429]
In postgreSQL 9.5, it is possible to use such a statement:

```sql
create table t(a serial, b integer, c integer, d text, unique(b, c));

insert into t(b,c,d) values (1,2,'test')
on conflict (b,c)
do update set d = 'test'
returing a;
```
The jooq code would look like that:
```java
DSL.insertInto(T, T.b, T.c, T.d).values(1, 2, 'test')
  .onConflict(T.b, T.c).doUpdate()
  .set(T.d, 'test')
  .returning(T.a);
```
Jooq 3.9.4 does not allow to append the `returing(T.a)` to the statement, the error message is:

```java
The method returning(TableField<T,Integer>) 
is undefined for the type InsertOnDuplicateSetMoreStep<TRecord>
```

Would be nice to have this included in the next version of jooq.

**Comment by lukaseder** [comment]
Thanks for reporting. This is due for 3.10. Duplicate issues (and workarounds) listed here: https://github.com/jOOQ/jOOQ/issues/2123
