### ISSUE TITLE
Throw TooManyRowsException in { Insert | Update | Delete }ResultStep.fetchOne() and fetchOptional()

### ISSUE THREAD

**Issue by t9t** [jOOQ/jOOQ#6440]
When performing a `SELECT` query and calling `fetchOne()`, it will throw a `TooManyRowsException` when the result contains more than one row.

However, when performing an `INSERT` or `UPDATE` query with a `RETURNING` clause, `fetchOne()` just returns the first row when multiple rows are returned.

I would expect that the latter would also throw a `TooManyRowsException`, consistent with the former.

**Comment by lukaseder** [comment]
Thank you very much for reporting. Indeed, there's an inconsistency between these APIs. I suspect that even if fixing this means to introduce an incompatible change, the change may be well received as the status quo is probably not desireable (i.e. when accidentally updating several rows, getting only the first is clearly a bug).

So, we can introduce this change in a minor release, but not merge it to 3.9

**Comment by lukaseder** [comment]
Hmm, the interesting question is what should happen with the SQL statement's outcome. Usually, when an exception is thrown from a SQL statement, the statement will have been rolled back / ignored.

With `TooManyRowsException`, this isn't the case as the exception is thrown by the client *after* query execution. This didn't have any significant effects with `SELECT` statements (unless `FOR UPDATE` is included), but things are different for other DML statements.

I guess the status quo is acceptable (other similar examples are exceptions thrown from SQL Server `RAISERROR` statements, which do not impact the SQL batch, but still throw an exception in the client). But we'll definitely have to add some documentation to the exception. I've added this feature request: #6443

**Comment by t9t** [comment]
Fair point, I hadn't thought of that (and I'm glad that you did!). I guess methods can't be (easily) renamed, otherwise probably something like `fetchFirst()` would be more appropriate.
