### ISSUE TITLE
Allow for overriding timestamps used for optimistic locking

### ISSUE THREAD

**Issue by anuraaga** [jOOQ/jOOQ#6445]
Currently, in places like `TableRecordImpl`, timestamps may be added to a record using `System.currentTimeMillis()`. This makes unit testing difficult - instead, it should be possible for a user to override `Clock` on the `Configuration` and using it when creating `Timestamp`s within JOOQ.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. Are you aware of the fact that you can put any user-defined object in [`Configuration.data()`](https://www.jooq.org/javadoc/latest/org/jooq/Configuration.html#data--)? 

I currently don't see unit testing as a compelling enough use case to add such an overrideable `Clock` object into `Configuration`'s public API, given the availability of the above workaround...

I'll close this as won't fix. Feel free to reopen if you think I've missed something.

**Comment by anuraaga** [comment]
@lukaseder Thanks - I should have included a link to the problematic line of code

https://github.com/jOOQ/jOOQ/blob/b9f34a58a783ba1eb313e1499f6c24eb3f55c4f3/jOOQ/src/main/java/org/jooq/impl/TableRecordImpl.java#L316

This is run when calling something like `record.store()`, and causes the current system time to be added to the context's bindings. As it's nice to verify all the bindings of a query in a unit test, it would be helpful to be able to override the source of time for this code flow. I don't think `Configuration.data()` applies here since it's about behavior in framework code, not user code.

**Comment by lukaseder** [comment]
Oh I see, I'm sorry for the confusion on my side. Yes, that makes sense. We'll think of something.

**Comment by anuraaga** [comment]
@lukaseder Thanks! By the way, I can't seem to re-open the issue since not a collaborator, so you may need to re-open it

**Comment by lukaseder** [comment]
OK, this will now be available to the Java 8 builds of jOOQ, through #6447 (the new `Configuration.clock()` API). Thanks again for your suggestion.
