### ISSUE TITLE
MockStatement does not return an update count when generated keys are requested.

### ISSUE THREAD

**Issue by anuraaga** [jOOQ/jOOQ#6446]
Currently, MockStatement does not return an update count when there is any result data. This is not valid when generated keys are requested since the keys would be returned as result data. `MockDataProvider`'s documentation even documents that returning generated keys as the result data is expected behavior.

Not returning update count can have impact on other code like in `TableRecordImpl` which doesn't attempt to read generated keys when it is `-1`.

I think a reasonable fix is to check `autoGeneratedKeys` in `MockStatement`

https://github.com/jOOQ/jOOQ/blob/1ed96d2f18ee008ca79740cf078ea76da3694c7b/jOOQ/src/main/java/org/jooq/tools/jdbc/MockStatement.java#L224

```java
    @Override
    public int getUpdateCount() throws SQLException {
        checkNotClosed();
        return (result != null && resultIndex < result.length)
            && (result[resultIndex].data == null || autoGeneratedKeys != Statement.NO_GENERATED_KEYS)
            ? result[resultIndex].rows
            : -1;
    }
```

**Comment by lukaseder** [comment]
Thank you very much for your report and suggested fix. May I ask you also to show where this impacts you currently? E.g.

1. Some example `MockDataProvider`
2. Some example client code, where the current behaviour breaks your assumptions

**Comment by lukaseder** [comment]
Closing this issue. There may well be a bug in this area, but without a reproducer on the API level, it's hard to see what is expected of jOOQ here.
