### ISSUE TITLE
Code generation regression for <dateAsTimestamp>

### ISSUE THREAD

**Issue by McNetic** [jOOQ/jOOQ#6453]
When I update from jOOQ 3.9.2 to 3.9.3 (or 3.9.4), the dateAsTimestamp option does longer longer work (at least for org.jooq.util.oracle.OracleDatabase) 
(I'm not sure generate->deprecated should be true, but it does not have any influence on this issue)

**Comment by lukaseder** [comment]
Thank you very much for reporting this. I can confirm this no longer works, also with 3.10-SNAPSHOT. I'll investigate why this hasn't been picked up by our integration tests and will fix this ASAP

**Comment by lukaseder** [comment]
> (I'm not sure generate->deprecated should be true, but it does not have any influence on this issue)

No, that's not related here, indeed.

**Comment by lukaseder** [comment]
This appears to be a regression that has been introduced with the combination of:

- https://github.com/jOOQ/jOOQ/issues/5239 (introduced in 3.9.0)
- https://github.com/jOOQ/jOOQ/issues/5762 (introduced in 3.9.3)

**Comment by lukaseder** [comment]
This is now fixed in 3.10-SNAPSHOT and 3.9.5. We'll release 3.9.5 on Friday

**Comment by McNetic** [comment]
Thank you very much. That was quick :-).
