### ISSUE TITLE
Support converting from java.sql.Array to Object[] types

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6454]
It is currently not possible to convert from `java.sql.Array` to `Object[]` (or `Integer[]`, `String[]`, etc...)

**Comment by lukaseder** [comment]
Implementing this should probably fix https://github.com/jOOQ/jOOQ/issues/13454

**Comment by lukaseder** [comment]
This is a low risk backport. Since this does fix #13454, I'll backport this to 3.16.7

**Comment by lemmingapex** [comment]
When do you plan on releasing `3.16.7` @lukaseder ?

**Comment by lukaseder** [comment]
Soon.

**Comment by lukaseder** [comment]
Maybe next week?
