### ISSUE TITLE
Generate comments also on POJOs

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6456]
Table / Column comments are currently not being generated on POJOs. We should fix that.

----
See also:
- https://stackoverflow.com/q/45318847/521799

**Comment by knutwannheden** [comment]
As proposed on StackOverflow  I suggest we add a simple Javadoc comment to the fields. So instead of

```java
    private Integer   id;
    private String    firstName;
    private String    lastName;
```

we would generate

```java
    /** Field corresponding to column <code>PUBLIC.AUTHOR.ID</code>. */
    private Integer   id;

    /** Field corresponding to column <code>PUBLIC.AUTHOR.FIRST_NAME</code>. */
    private String    firstName;

    /** Field corresponding to column <code>PUBLIC.AUTHOR.LAST_NAME</code>. */
    private String    lastName;
```

@lukaseder Any comments on this?

**Comment by knutwannheden** [comment]
All generated classes which are POJOs or subclasses of `CatalogImpl`, `SchemaImpl`, `TableImpl`, `UpdatableRecordImpl` currently have the same Javadoc:

```java
/**
 * This class is generated by jOOQ.
 */
```

If we want to change that, I suggest we do that in another issue.

**Comment by lukaseder** [comment]
> we would generate

I'd rather not introduce a new Javadoc style, because users will want to make that configurable as well, on a per Javadoc target basis (e.g. attributes single/multi line javadoc, getters / setters single/multi line javadoc). Let's just keep one single Javadoc style:

```java
/**
 * The Javadoc
 */
```

I personally don't see the point of generating Javadoc on private filelds like that. Instead, we should generate it on all getters / setters, which we're already doing for other object types' getters / setters.

> If we want to change that, I suggest we do that in another issue.

Since we don't have an issue, I suggest we don't change that :) (I can think of a few higher priorities)
