### ISSUE TITLE
Typo in DSLContext.fetchCount() and error in DSLContext.fetchExists() Javadoc

### ISSUE THREAD

**Issue by qiaoruntao** [jOOQ/jOOQ#6478]
In comment of `fetchCount` and function, it says "@return The number or records in the table", however it is more reasonable if says "@return The number of records in the table".
`fetchExists` function has the same problem, however it returns a boolean not an int, so it needs a little more change.

**Comment by qiaoruntao** [comment]
my jooq version is 3.9.5, however DSLContext.java in jooq master branch still has this problem, so I assume this problem has not be fixed

**Comment by lukaseder** [comment]
Thank you very much for your report. This is now fixed in 3.10.
