### ISSUE TITLE
XMLDatabase doesn't work when dialect is not a SQLDialect.family()

### ISSUE THREAD

**Issue by eikemeier** [jOOQ/jOOQ#6493]
A simple [information_schema.xml](https://github.com/jOOQ/jOOQ/files/1203044/information_schema.xml.txt) generated from a PostgreSQL database contains types in lower case, like “character varying”:

      <data_type>character varying</data_type>

Following [the documentation](https://www.jooq.org/doc/3.9/manual/code-generation/codegen-xml/), “any of the [the SQLDialect values](https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/SQLDialect.java#L167)” is valid as an dialect, so lets try **POSTGRES_9_5** in [configuration.xml](https://github.com/jOOQ/jOOQ/files/1203048/configuration.xml.txt).

        <property>
          <key>dialect</key>
          <value>POSTGRES_9_5</value>
        </property>

Processing with

      java -cp 'jooq-3.9.5.jar:jooq-meta-3.9.5.jar:jooq-codegen-3.9.5.jar' org.jooq.util.GenerationTool configuration.xml

results in a file generated/org/jooq/generated/tables/Customer.java with

    public final TableField<CustomerRecord, Object> NAME = createField("name", org.jooq.impl.DefaultDataType.getDefaultDataType("character varying"), this, "");

because the data types are [defined for the family](https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/util/postgres/PostgresDataType.java#L87), not the dialect:

    DefaultDataType<String>(SQLDialect.POSTGRES, SQLDataType.VARCHAR, "character varying")

changing the dialect in configuration.xml to **POSTGRES** results in the expected result:

    public final TableField<CustomerRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

which is fine, but took me a while to figure out. Perhaps [the documentation](https://github.com/jOOQ/jOOQ/blob/master/jOOQ-manual/src/main/resources/org/jooq/web/manual-3.9.xml#L17506) should read “any of the SQLDialect dialect _families_” or SQLDialect.family() should be used in code generation.

**Comment by lukaseder** [comment]
Thank you very much for the detailed report. This doesn't look like a documentation problem only, I think it's a bug. It should be possible to specify a dialect, not just a family (the behaviour should be the same in this case).

I'll look into this in more detail, soon.

Thanks,
Lukas

**Comment by lukaseder** [comment]
I can reproduce this. A fix is on the way. Thanks again for reporting.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.10. This will also be merged to 3.9.6 and 3.8.9

**Comment by eikemeier** [comment]
Thanks, great job!
