### ISSUE TITLE
Emulate INSERT .. ON DUPLICATE KEY UPDATE .. RETURNING with SELECT .. FROM FINAL TABLE (MERGE ..) in DB2

### ISSUE THREAD

**Issue by ramachandrann** [jOOQ/jOOQ#6494]
JOOQ 3.10.0-SNAPSHOT is supposed to support the returning() method when using the onDuplicateKeyUpdate() but it seems to be generating invalid SQL for DB2 LUW.  

If we use the execute() method instead of the returning() then it works.  If we remove the onDuplicateKeyUpdate() then the returning() works but they don't seem to work together.

We need to get back the P_ID on insert or update when the row exists so we would like to use these provided features. 

              dslContext.insertInto(PAYMENT, TABLE1.DESC)
                     .values("Some description")
                     .onDuplicateKeyUpdate()
                     .set(TABLE1.DESC, "Some description")
                     .returning(TABLE1.P_ID)
                     .fetchOne();

org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [select "P_ID" from final table (merge into "SCHEMA1"."TABLE1' using (select 1 "one" from "SYSIBM"."DUAL") on "SCHEMA1"."TABLE1'."P_ID" = cast(? as integer) when matched then update set "SCHEMA1"."TABLE1'."DESC" = cast(? as varchar(32672)) when not matched then insert ("DESC") values (cast(? as varchar(32672))))]; nested exception is com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-104, SQLSTATE=42601, SQLERRMC=select "P_ID" from final table (;BEGIN-OF-STATEMENT;<space>, DRIVER=4.15.100
                at org.jooq_3.10.0.DB2_10.debug(Unknown Source) ~[na:na]

**Comment by ramachandrann** [comment]
By when do you foresee 3.10.0-SNAPSHOT released with this feature?

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. This would be a very interesting addition, given that DB2 has support for the SQL standard `{ FINAL | NEW | OLD

**Comment by lukaseder** [comment]
It looks like a couple of internal refactorings will be needed to implement this thoroughly. I'd rather implement #5306 first, which will give much better access to the feature than the emulation itself (and the emulation will be easy, once #5306 is implemented).

I'm thus postponing this for 3.11

**Comment by lukaseder** [comment]
As a workaround, plain SQL can always be used, e.g.

```java
ctx.fetch("SELECT * FROM FINAL TABLE ({0})", mergeStatement);
```

**Comment by lukaseder** [comment]
This emulation should work correctly now in jOOQ 3.18 (probably earlier, too). We've added support for the data change delta table in the meantime:

<img width="898" alt="image" src="https://user-images.githubusercontent.com/734593/203774362-7e53a481-4346-4465-853f-975ec64b0eba.png">
