### ISSUE TITLE
Not possible to join after `selectFrom()`

### ISSUE THREAD

**Issue by jhyot** [jOOQ/jOOQ#6503]
The handy shortcut `selectFrom(<table>)` does not allow any joins to be performed on this query.

I found a use case where I only select from one table, but do the join to do some filtering on the result.

This is not possible:
```java
sql.selectFrom(TABLE1)
                .innerJoin(TABLE2).on(TABLE1.XY.eq(TABLE2.ABC))
                .where(/* conditions for TABLE1 and 2 */)
                .map(new Table1Mapper());
```
instead I have to resort to this more verbose way:

```java
sql.select(TABLE1.fields())
                .from(TABLE1)
                .innerJoin(TABLE2).on(TABLE1.XY.eq(TABLE2.ABC))
                .where(/* conditions for TABLE1 and 2 */)
                .fetchInto(TABLE1)
                .map(new Table1Mapper());
```

Probably the join could be replaced by a subselect or similar, but sometimes the join may be the more natural way to write such a query...?

**Comment by lukaseder** [comment]
Thank you very much for your enquiry. There are a couple of things to notice here:

### 1. Convenience JOIN APIs

JOIN is not a `SELECT` keyword but an operator that is placed between two tables. So, all the `join()` methods on the `Select` API are mere convenience for `Table.join(Table).on(Condition)`. If you want to work with `selectFrom()`, you could pass such a joined table to the method.

### 2. `selectFrom()`'s main purpose

The main purpose of the "convenient" `selectFrom()` method is to fetch all rows from a table to create an `UpdatableRecord`, whose modifications can be stored back to the database easily. In your case, it might well be worth to use the more verbose way, which is more suitable for this kind of query where you're not interested in the `UpdatableRecord`

### 3. You probably want semi join, not inner join

Your query might not produce the results you need, as you seem to want to run a semi join (implemented in SQL through `IN` predicates or `EXISTS` predicates). Be careful not to produce any accidental cartesian products.
