### ISSUE TITLE
Add support for JOIN with selectFrom()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6541]
When users write `selectFrom()`, sometimes they would like to implement a semi join through an inner join as follows:

```sql
SELECT a.*
FROM a
JOIN b USING (a_id)
```

In this particular case, jOOQ's `selectFrom(A)` approach seems useful, as it allows for fetching `UpdatableRecord` from table `A`, only if there's a corresponding value in `B`.

Of course, this would be better implemented using semi join

```sql
SELECT *
FROM a
WHERE a_id IN (SELECT a_id FROM b)

-- Alternatively
SELECT *
FROM a
WHERE EXISTS (SELECT 1 FROM b WHERE a.a_id = b.a_id)
```

But in some databases, semi join is less well optimised than inner join. Besides, jOOQ also supports this synthetic semi join syntax, which isn't currently easily possible with `selectFrom(A)`:

```sql
SELECT *
FROM a
LEFT SEMI JOIN b USING (a_id)
```

Several users have been looking for this feature, so we should offer it.

----

An additional use-case can be seen here (where a column from the joined table is used for ordering): https://github.com/jOOQ/jOOQ/issues/7003

**Comment by lukaseder** [comment]
There might be some subtleties related to generating the qualified asterisk when using the plain SQL `selectFrom()` overloads, perhaps a known limitation?

**Comment by knutwannheden** [comment]
As I understand it the idea is to change all `selectFrom()` methods to return `SelectJoinStep` rather than `SelectWhereStep`. Is this correct?

> Besides, jOOQ also supports this synthetic semi join syntax, which isn't currently easily possible with `selectFrom(A)`:
> 
> ```sql
> SELECT *
> FROM a
> LEFT SEMI JOIN b USING (a_id)
> ```

AFAICT the following works and would already be quite close:
```java
create().selectFrom(A.leftSemiJoin(B).using(A.ID))
```
But if I understand the issue correctly, this is what is wanted instead:
```java
create().selectFrom(A).leftSemiJoin(B).using(A.ID)
```

**Comment by lukaseder** [comment]
> As I understand it the idea is to change all `selectFrom()` methods to return `SelectJoinStep` rather than `SelectWhereStep`. Is this correct?

Yes, that's what I think should be done from an API perspective.

> AFAICT the following works and would already be quite close:
> 
> ```java
> create().selectFrom(A.leftSemiJoin(B).using(A.ID))
> ```

Indeed, that already works, but it produces `EXISTS` queries, which might not be the desired thing. Let's focus on the examples where users want to-one inner or outer joins. The best example I've seen from users is the one where the join is needed for an `ORDER BY` clause, e.g.

```sql
SELECT a.*
FROM a
JOIN b ON a.x = b.x
ORDER BY b.y
```

**Comment by knutwannheden** [comment]
Rendering the qualified asterisk properly indeed turns out to be a problem. I started out with a very naive implementation of `DefaultDSLContext#selectFrom(Table)`:
```java
    public <R extends Record> SelectJoinStep<R> selectFrom(Table<R> table) {
        return new SelectImpl(configuration(), null).select(table.asterisk()).from(table);
    }
```
This works as desired for code like:
```java
ctx.selectFrom(A);
ctx.selectFrom(table("a"));
```
But breaks down when passing a join table:
```java
ctx.selectFrom(A.join(b).using(A_ID));
ctx.selectFrom(table("a").join(table("b")).using(field("a_id")));
```
as it would end up being rendered like:
```sql
select a
  join b
    on "a"."a_id" = "b"."a_id".*
from a
  join b
    on "a"."a_id" = "b"."a_id"
```
Any proposal on how to best fix this? Should for instance `SelectFieldList#accept()` and `QualifiedAsteriskImpl#accept()` use a `Context#data()` entry?

**Comment by lukaseder** [comment]
Nice catch. There are two parts to this:

1. We *could* (but might be a mess, implementation wise) prevent the qualified asterisk, and revert to an unqualified asterisk, if after `selectFrom()`, we don't call any `join()` methods.
2. I think this is a separate problem, unrelated to this particular task. You can produce this problem also explicitly, using this:

    ```java
    Table<?> joined = A.join(b).using(A_ID);
    ctx.select(joined.asterisk()).from(joined);
    ```

    In this case, the qualified asterisk should probably expand to two qualified asterisks: `A.asterisk(), B.asterisk()`. Worth a separate issue?

**Comment by lukaseder** [comment]
... if (2) is possible to implement, then (1) is probably unnecessary

**Comment by knutwannheden** [comment]
1. AFAICT the problem is when we call something like `join()` _inside_ `selectFrom()` as in `selectFrom(A.join(B))`. With `join()` _after_ `selectFrom()` (e.g. `selectFrom(A).join(B)`) we want the table qualification (`SELECT A.* FROM A JOIN B`) as per this issue.
2. There are other types of table which have the same problem (e.g. `GenerateSeries`), in which case I think rendering an unqualified asterisk may be the only option. So I wonder if we shouldn't do the same for `JoinTable` then.
3. I stumbled across one more issue when testing this. Due to how the `SelectQueryImpl#resolveAsterisk()` and `SelectQueryImpl#getSelectResolveSomeAsterisks0()` methods get called while rendering, the qualified asterisk does not end up getting resolved when rendering the SQL. This part of the code looks like it could be tricky to get right in all cases. I have not yet found the right solution.

**Comment by lukaseder** [comment]
I'm not quite sure if I understand the problems (2) and (3). However, the more I think about this (and the problems caused / questions raised by this), I wonder if the feature request is really legitimate.

- `selectFrom(A)` projects the type of `ARecord`, whatever that is.
- A join may seem useful at first, but raises a lot of questions, including whether we really still want to project A, or the unqualified asterisk, as might also be reasonably expected by other users. After all, this stuff just looks like syntax sugar.
- With the above ambiguities, we might be implementing something flaky and/or even wrong.
- At the same time, what users requesting this feature actually *want* is a way to project generated records, *and still* join other tables

That last bullet can still be achieved with jOOQ's ordinary syntax, e.g.

```java
Result<ARecord> result =
ctx.select(A.asterisk())
   .from(A)
   .join(B).on(A.X.eq(B.X))
   .orderBy(B.Y)
   .fetchInto(A); // Magic here
```

Perhaps we should simply reject this issue in favour of the above straight forward, unsurprising solution.

**Comment by knutwannheden** [comment]
> Perhaps we should simply reject this issue in favour of the above straight forward, unsurprising solution.

Yes, perhaps. Adding one more way to achieve the same thing is not always helpful.

**Comment by lukaseder** [comment]
Done
