### ISSUE TITLE
Support formatting of multi dimensional arrays in Result.format()

### ISSUE THREAD

**Issue by JanecekPetr** [jOOQ/jOOQ#6545]
### Expected behavior and actual behavior:
While debugging a misbehaving query, I found this in the debug output:
```
Fetched result           : +--------------------------------------------------+
                         : |data                                              |
                         : +--------------------------------------------------+
                         : |[[Ljava.lang.String;@4bd31064, [Ljava.lang.Stri...|
                         : |[[Ljava.lang.String;@329dbdbf, [Ljava.lang.Stri...|
                         : +--------------------------------------------------+
```

...which is not very useful. The problem is that the query contains:
```
arrayAgg(array(SOME_TABLE.FIELD, SOME_TABLE.VALUE)).as("data")
```

I expected the array contents to be shown correctly.

### Steps to reproduce the problem:
Run a query containing an array.

### Versions:

- jOOQ: 3.9.5
- Database (include vendor): Postgres 9.4.1
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.1.3

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. Currently, jOOQ doesn't really support PostgreSQL's nested arrays even if in this case, it seems to work "accidentally". The relevant feature request is #252

Nevertheless, I agree, it would make sense to pretty print them in the debug log output and in other formatted forms.

**Comment by lukaseder** [comment]
OK, this was easy. Thanks again for the suggestion!
