### ISSUE TITLE
newRecord(TABLE, tablePojo).insert bug

### ISSUE THREAD

**Issue by thegodofwar** [jOOQ/jOOQ#6546]
i do not want use insert into ... returning to get primary key,so i do:

```java
 MediaMgmtAccessUrilogRecord record =
        dslContext.newRecord(MEDIA_MGMT_ACCESS_URILOG, mediaMgmtAccessUrilog);
    record.insert();
    mediaMgmtAccessUrilog.setId(record.getId());
```

but when concurrent process,get org.jooq.exception.NoDataFoundException: Exactly one row expected for refresh. Record does not exist in database.

is this a bug?

**Comment by lukaseder** [comment]
Thanks for taking the time to report this issue.

There had been a bug like this in the past - would you mind indicating:

- Your jOOQ version
- Your JDBC driver and version
- Your database product and version

**Comment by thegodofwar** [comment]
1，jooq version：3.9.5
2，mysql jdbc version：5.1.30
3，mysql version：5.5.32-log

Error Detail：
org.jooq.exception.NoDataFoundException: Exactly one row expected for refresh. Record does not exist in database.
	at org.jooq.impl.UpdatableRecordImpl.refresh(UpdatableRecordImpl.java:345)
	at org.jooq.impl.TableRecordImpl.getReturningIfNeeded(TableRecordImpl.java:234)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:210)
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:171)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:167)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:155)
	at org.jooq.impl.TableRecordImpl.insert(TableRecordImpl.java:150)

**Comment by thegodofwar** [comment]
i am confused with wether i can use:
dslContext.newRecord(TABLE, POJO);
record.insert();
POJO.setId(record.getId());

to replace dslContext.insertInto(table).set(xx).set(xx).returning().fetchOne() ?

this write too much code

**Comment by thegodofwar** [comment]
@lukaseder

**Comment by lukaseder** [comment]
Thank you very much for your updates. I will investigate this soon.

**Comment by thegodofwar** [comment]
@lukaseder 
hi, lukaseder ,what about this question?

**Comment by lukaseder** [comment]
Thank you very much for your patience and I'm sorry for the delay. Would you mind posting the DDL for your `MEDIA_MGMT_ACCESS_URILOG` table as well as the type of your value `mediaMgmtAccessUrilog`? Specifically, I'm interested in what the primary key value of your `mediaMgmtAccessUrilog` was, before you called `newRecord()`

**Comment by thegodofwar** [comment]
ddl
`CREATE TABLE `media_mgmt_access_urilog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `empId` varchar(255) DEFAULT NULL,
  `hostIp` varchar(255) DEFAULT NULL,
  `param` varchar(255) DEFAULT NULL,
  `updateTime` datetime DEFAULT NULL,
  `uri` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IndexUri` (`uri`),
  KEY `IndexEmpId` (`empId`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8`

pojo type:
`public class MediaMgmtAccessUrilog implements Serializable {

    private Long      id;
    private String    empid;
    private String    hostip;
    private String    param;
    private Timestamp updatetime;
    private String    uri;`

i am sure the id of pojo is null when i post this into newRecord.

**Comment by thegodofwar** [comment]
this case focu when concurrently do inserting, so i feel maybe this is a newRecord concurrent bug.

**Comment by lukaseder** [comment]
Thanks for the update. Everything looks OK here. I currently cannot reproduce this with your JDBC driver version (or the latest version) and MySQL 8.0.2, nor with 5.7... Will look further.

**Comment by lukaseder** [comment]
Cannot reproduce with 3.10-SNAPSHOT nor with 3.9.5. Would you mind sharing your `Settings` that you put in your jOOQ `Configuration`?
