### ISSUE TITLE
Support multiple external configuration files through <configurationFiles/>

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#6548]
### Expected behavior and actual behavior:

Currently the jOOQ Code Generator Maven plugin supports an undocumented setting (no mention on https://www.jooq.org/doc/3.9/manual/code-generation/codegen-configuration/) called `configurationFile`. In a modular app, it would be great to be able to split out parts of the config into a separate file per module (say for specific converters and forcedTypes). Those XML files could then dynamically be recombined them in a module further down the dependency graph (say the web app) by merging their individual sections.

### Versions:

- jOOQ: 3.9

**Comment by lukaseder** [comment]
Thanks for your suggestion. This is a Maven plugin only configuration flag, and it's documented here:
https://www.jooq.org/doc/3.9/manual/code-generation/codegen-maven

I can see where you're going. Will think about this, some parts of the configuration might be worth merging from several sources indeed. However, I also would like to avoid overengineering this part of the config, so perhaps, there's a more low hanging fruit to do what you'd like to do.

### Workarounds:

Once you read an external configuration file in XML form, XSLT seems like a reasonable way to compose a more complex configuration, e.g. by preprocessing the configuration using the xml-maven-plugin.

Another option for more powerful recombination of configuration elements is the programmatic configuration.

**Comment by axelfontaine** [comment]
I did indeed manage to come to some sort of workaround by resorting to XML entities and passing `-Djavax.xml.accessExternalDTD=all` to the Maven JVM to make it work. It would be great if you could automatically activate support for XML entities and XInclude in the XML parser when reading in the external config file to avoid having to remember to pass this to Maven.

Also (one can only dream) support for Maven property filtering in the external config file would be fantastic as it would save a number of intermediate steps and generally make it much easier to externalize the config.

**Comment by lukaseder** [comment]
> XML entities

Interesting feedback. I agree that could be done and it doesn't pose a security issue in this case, as it only affects the code generator. Will look into it in a separate issue: #6550

> Also (one can only dream) support for Maven property filtering in the external config file would be fantastic as it would save a number of intermediate steps and generally make it much easier to externalize the config

Would you mind elaborating?

**Comment by axelfontaine** [comment]
Right now the jOOQ config contains a `<jdbc>` section with connection properties. When externalizing the generator config, it is currently no longer possible to easily use Maven placeholders in this section without resorting to combine the resources plugin with a change of phase of the jooq plugin. If the jooq plugin could automatically perform the filtering upon loading, this would be much more intuitive.

Alternative: allow defining part of the config in the `pom.xml` to selectively override parts of the external config file. Both Boxfuse and Flyway do this and it has proven extremely helpful.

**Comment by lukaseder** [comment]
I see, thanks. Will think about it

**Comment by lukaseder** [comment]
I'm looking into this now. Loading two XML files is easy. The trick is how to merge them. The XML files are loaded into a Java representation that is both JAXB and Maven compatible, so this helps move the problem from an XML problem to a Java problem. It's easy to see how two lists should be merged. Merging this:

```xml
<!-- source 1: -->
<forcedTypes>
  <forcedType>A</forcedType>
  <forcedType>B</forcedType>
</forcedTypes>

<!-- source 2: -->
<forcedTypes>
  <forcedType>C</forcedType>
  <forcedType>D</forcedType>
</forcedTypes>
```

Leads to this:

```xml
<!-- source 1: -->
<forcedTypes>
  <forcedType>A</forcedType>
  <forcedType>B</forcedType>
  <forcedType>C</forcedType>
  <forcedType>D</forcedType>
</forcedTypes>
```

Or in Java:

```java
// Load sources individually
Database source1 = new Database();
Database source2 = new Database();

// Merge source2 into source1
source1.getForcedTypes().addAll(source2.getForcedTypes());
```

Two conflicting list elements will not be merged. There is no way to identify a list element by ID or value.

The interesting question is what happens when merging two "scalar" values, such as `Database.excludes`. My intuition is to take only the first source value and ignore all others. There is of course a justified use case of merging such values as well, and it makes sense in some cases (see #6556), but that would have to be solved again on an object model level, e.g. by moving from the single `<excludes/>` element model to another list:

```xml
<!-- instead of -->
<database>
  <excludes>.*some_regex.*</excludes>
</database>

<!-- do this -->
<database>
  <excludes>
    <exclude>.*some_regex.*</exclude>
    <exclude>.*some_other_regex.*</exclude>
  </excludes>
</database>
```

**Comment by lukaseder** [comment]
Hmm, Maven only seems to merge properties in the way I described, not lists:
https://blog.sonatype.com/2011/01/maven-how-to-merging-plugin-configuration-in-complex-projects

The suggested behaviour is that of `combine.children="append"`
