### ISSUE TITLE
Support XML entities in XML-based code generator configuration

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6550]
See also @axelfontaine's comment in this issue here:
https://github.com/jOOQ/jOOQ/issues/6548#issuecomment-326245386

----
Side note on security: While XML entities are dangerous from a security perspective, in the context of code generator configuration, they're OK as it is unlikely for an attacker to inject a code generation configuration snippet into jOOQ users' build environments. This does not affect any runtime XML usage.

**Comment by axelfontaine** [comment]
Don't forget the "modern" equivalent: XInclude.

**Comment by lukaseder** [comment]
Related: https://github.com/jOOQ/jOOQ/issues/6556

**Comment by lukaseder** [comment]
It's a fun idea, a bit esoteric. But I don't like implementing it:

- It works only with XML, not with gradle or the programmatic configuration
- It might not even work with Maven
- Maven has its own mechanism, which works out of the box and is jOOQ agnostic, see e.g. https://github.com/jOOQ/jOOQ/issues/6556

I think that the kind of power user who would be using this, is also a user who would be generating jOOQ code generation configurations using XSLT dynamically, so XML entities aren't necessary.
