### ISSUE TITLE
Mark Maven plugin as @ThreadSafe

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#6554]
### Expected behavior and actual behavior:

When running the jOOQ code generator Maven plugin in a parallel Maven build (using for example `-T2`) Maven outputs the following warning:

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in mymodule:
[WARNING] org.jooq:jooq-codegen-maven:3.9.5
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```

Marking the mojo as threadsafe eliminates this.

### Versions:

- jOOQ: 3.9.5

**Comment by lukaseder** [comment]
Interesting, thanks for the suggestion. The jOOQ-meta API is, in fact, not thread safe, meaning that two threads shouldn't access the same meta data instance (e.g. of `org.jooq.util.AbstractDatabase`). This may not be a problem in most cases, but we obviously have to be careful here. I'll certainly look into this, though. If two executions don't interact with each other, parallelism is certainly a desireable trait.

What's your use-case of using parallelism? Do you want to run two code generation runs in parallel? Or other things?

**Comment by axelfontaine** [comment]
We have multiple modules in our project. Each modules owns a subset of the tables in the database and uses jOOQ to generate the corresponding classes as part of a parallel Maven build. This works just fine, which leads me to believe that marking the mojo as threadsafe shouldn't be a big deal as each module gets its own instance of the mojo.

**Comment by lukaseder** [comment]
I see.

Yeah, I'll have to check if any `static` members are used, though. There shouldn't be, but there might, you never know :) Anyway, nothing that cannot be fixed.

**Comment by lukaseder** [comment]
I have not found any reason why the plugin execution shouldn't be thread safe. The next version will have this property.
