### ISSUE TITLE
Avoid package cycles in generated code

### ISSUE THREAD

**Issue by axelfontaine** [jOOQ/jOOQ#6555]
### Expected behavior and actual behavior:

The generated code currently contains package cycles (between `Keys`and individual table classes for example). This is a design smell that should be avoided.

### Versions:

- jOOQ: 3.9.5

**Comment by axelfontaine** [comment]
How to solve this the easy way:

- invert Keys reference: let the global Key class reference a Key in the Table class that contains it, instead of having the table class reference the global keys class
- let `<globalObjectReferences>false</globalObjectReferences>` disable the generation of **all** global object references, including Keys

**Comment by lukaseder** [comment]
Thanks for your suggestion. We've had this request a couple of times on the mailing list. The main advantage of allowing cycles is the fact that we can easily avoid compilation errors in tons of edge cases by simply placing objects of similar names in different packages.

The idea that packages are perceived as hierarchical in a sense where a "cycle" is undesirable is historic and not generally applicable, if perhaps a bit academic, in my opinion. After all, we could certainly criticise the Java language for not having introduced a more formal module system from the beginning, where dependencies and hierarchies are a native concept, as opposed to packages.

As a workaround, you can easily place all generated objects in the same package by using a generator strategy (handling the naming edge cases yourself):
https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy

In any case, this will not be a priority anytime soon for the jOOQ code generator. I haven't really met a convincing argument against the status quo, other than, perhaps that some tools like Sonar would detect this as a potential flaw.

**Comment by lukaseder** [comment]
I have always had strong opinions about this, e.g. more recently:

- https://twitter.com/lukaseder/status/1476540309672800260
- https://twitter.com/lukaseder/status/1631555487693930504

By now, I'm even more convinced that this whole package cycle bikeshed is just a distraction from the real historic problem: That Java didn't have first class modules in the language (though the ecosystem always treated `jar` files as modules).

Cycles between packages of a module are perfectly fine. There's no smell. So there's no need to address this "problem." At the same time, generated jOOQ code can be perfectly modularised. It is a module, depending only on the jOOQ module, and client code can depend on both.

I'm closing this as won't fix.
