### ISSUE TITLE
Error in Record.compareTo(...) Javadoc

### ISSUE THREAD

**Issue by fjf2002** [jOOQ/jOOQ#6557]
The Javadoc at https://www.jooq.org/javadoc/3.8.x/org/jooq/Record.html#compareTo-org.jooq.Record- says:

_X[i] = Y[i] means (X[i] == null && Y[i] == null) || X[i].compareTo(Y[i]) < 0_

Don't you mean:
X[i] = Y[i] means (X[i] == null && Y[i] == null) || X[i].compareTo(Y[i]) **==** 0

?

**Comment by lukaseder** [comment]
Nice observation, thanks for letting us know!
