### ISSUE TITLE
Add a recursive CTE example to the manual

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6562]

**Comment by casagiacomo** [comment]
i need to create in jooq this type of query:
table T1 = query complex with join union ecc

after I need to create jooq trasformation for:

with RECURSIVE(
T1)
,LOOP_T1(
select * from T1
union
select * from LOOP_T1 join T1
)
select * from LOOP_T1

it's possibile? 
PS I have postgres 9.2

**Comment by Artus2b** [comment]
I was looking just for that. I think it's a tough one, because you need the reference to the CTE's fields _inside_ the said CTE.

Here is my shot: (based on [PostgreSQL's recursive CTE exemple](https://www.postgresql.org/docs/current/queries-with.html))
```sql
WITH RECURSIVE t(n) AS (
    VALUES (1)
  UNION ALL
    SELECT n+1 FROM t WHERE n < 100
)
SELECT sum(n) FROM t;
```
```java
Name cteName = name("t");
Field<Integer> field = field("n", Integer.class);
name(cteName).fields(field.getName())
        .as(
                select(val(1))
                        .unionAll(
                                select(field.plus(val(1)))
                                        .from(cteName)
                                        .where(field.lessThan(val(100)))
                        )
        );
```

If I'm wrong then I'd be a good customer for that new documentation :)
Thanks for all your work!

**Comment by SimonCJacobs** [comment]
@Artus2b Thanks for your work on that it helped me get going with this. As I worked through it I thought I'd add my solution since you didn't include the main part of the query:

```
Name cteName = name("t");
Field<Integer> field = field("n", Integer.class);
CommonTableExpression<Record1<Integer>> cte =
  name(cteName).fields(field.getName())
    .as(
      select(val(1))
        .unionAll(
          select(field.plus(val(1)))
            .from(cteName)
            .where(field.lessThan(val(100)))
          )
    );
Result result = create.withRecursive( cte )
  .select( sum( field ) )
  .from( cte )
  .fetch();
```

**Comment by lukaseder** [comment]
Finally documented with an example
