### ISSUE TITLE
Result.formatJSON() does not correctly format array types

### ISSUE THREAD

**Issue by maxkremer** [jOOQ/jOOQ#6563]
### Expected behavior and actual behavior:

ResultImp.formatJson() does not check if the dataType is an array and as such does not correctly serialize SQL array types. The json ends up looking like this

```
{
"fields":[{"table":"bar","name":"foo","type":"VARCHAR"}]
,"records":[["[Ljava.lang.String;@6e35f78d"],["[Ljava.lang.String;@7a98e8fe"]]
}
```

expected JSON should look something like this
```
{
"fields":[{"table":"bar","name":"foo","type":"VARCHAR"}]
,"records":[
    [["value0","value1","value2"]]
   , [["valueX","valueY","valueZ"]]
  ]
}
```

### Steps to reproduce the problem (on postgresql 9.6):
```
--set up the schema and insert values
create table bar(
   foo varchar[]
);
insert into bar values(  '{value0, value1, value2}');
insert into bar values(  '{value0, value1, value2}');
```
The buggy json values can be produces as follows in java

```
//d is a DSL context
d.fetch("select foo from bar").formatJSON();
```

The above bug is problematic when using a caching layer with JOOQ that serializes cachable results using the above fromatJSON method in an external cache (eg REDIS)

To fix this problem formatJSON need to check if a DataType.isArray() and handle it properly.

### Versions:

- jOOQ: 3.9.2
- Database (include vendor): Postgresql 9.6
- JDBC Driver (include name if inofficial driver): postgres JDBC 42

**Comment by lukaseder** [comment]
Thank you very much for your report. I agree with your suggested improvement. In the case of JSON export (and import) the preferred serialisation is obvious.

**Comment by maxkremer** [comment]
Studying the implementation of `formatJSON` and comparing it to `formatCSV` (which handles arrays correctly) it appears that the `formatJSON0` private method is less sophisticated than the `format0` method (used in fromatCSV) which included the check `value.getClass().isArray()` in the if-else statement. Hope that helps.

**Comment by lukaseder** [comment]
You're probably referring to this recent fix here, right? https://github.com/jOOQ/jOOQ/commit/6321f8060fd19624c4b29b5b3df91b00f59032ca

It doesn't really apply in the case of JSON. The fix I've linked is just for visual formatting in places where data types are not well defined (e.g. `format()`, `formatHTML()`, `formatCSV()`). In the case of `formatJSON()`, the implementation can be more specific.

**Comment by lukaseder** [comment]
Related: #6565

**Comment by maxkremer** [comment]
This got me thinking about other complex data types like HSTORE as well the JSONB type (both postgres). Would your changes to Result.formatJSON() handle those?

**Comment by lukaseder** [comment]
That would be nice and the implementation would look obvious, once jOOQ supports those types. Unfortunately, right now, they're not supported out of the box, mainly because it's not obvious what type to map them to in Java. But that can change (both on the roadmap), and it will be a good idea to implement out-of-the-box JSON serialisation for those types too, then.

**Comment by safaci2000** [comment]
I'm not sure if it's still on the roadmap, but Java 9 was supports to have a native JSON parser.  I think both HSTORE and JSON be can be mapped to that JSON library since it becomes part of core.  Though that won't be out for a while and it avoids the discussion of.. Jackson JSON vs GSON vs <insert lib here>

**Comment by lukaseder** [comment]
@safaci2000 Where do you see such support in Java 9? https://docs.oracle.com/javase/9/whatsnew/toc.htm

**Comment by safaci2000** [comment]
@lukaseder it doesn't look like it is on their roadmap but it was initially slated for java 9.  https://jaxenter.com/json-api-dropped-java-9-113028.html

Just a thought.. is JSON becomes a first class citizen for java core, then that's one approach you can take.

**Comment by lukaseder** [comment]
@safaci2000: Sure, I've been waiting (and looking out) for this for a while, but it hasn't become part of Java SE...

**Comment by maxkremer** [comment]
Hi @lukaseder I just tried this with 3.10 and it still thows a class cast exception. Does not appear to be fixed

**Comment by lukaseder** [comment]
Thanks for your message, @maxkremer. This particular test works for me:

```java
    @Test
    public void testPostgresFormatJSONWithArrays() {
        String json1 =
        create().select(arrayAgg(T_AUTHOR.FIRST_NAME), arrayAgg(T_AUTHOR.LAST_NAME))
                .from(T_AUTHOR)
                .fetch()
                .formatJSON(new JSONFormat().header(false));

        assertEquals("[[[\"George\",\"Paulo\"],[\"Orwell\",\"Coelho\"]]]", json1);

        String json2 =
        create().select((Field<String[][]>) arrayAgg(array(T_AUTHOR.FIRST_NAME, T_AUTHOR.LAST_NAME)))
                .from(T_AUTHOR)
                .fetch()
                .formatJSON(new JSONFormat().header(false));

        assertEquals("[[[[\"George\",\"Orwell\"],[\"Paulo\",\"Coelho\"]]]]", json2);
    }
```

What am I doing differently from you?

**Comment by maxkremer** [comment]
Works for me too. I think my issue is deserializing from JSON into a mock result. 
```
Caused by: java.lang.ClassCastException: [Ljava.lang.String; cannot be cast to java.lang.String
	at org.jooq.tools.jdbc.MockResultSet.getString(MockResultSet.java:383) ~[na:na]
	at org.jooq.tools.jdbc.DefaultResultSet.getString(DefaultResultSet.java:111) ~[na:na]
	at org.jooq.impl.CursorImpl$CursorResultSet.getString(CursorImpl.java:922) ~[na:na]
	at org.jooq.impl.DefaultBinding.get(DefaultBinding.java:1539) ~[na:na]
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1704) ~[na:na]
```

**Comment by lukaseder** [comment]
> Do you want me to log a new issue?

Yes please, I think I'd need a few more details to see what you mean...
