### ISSUE TITLE
Add some examples about interval usage to the manual

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6579]
See also:
https://www.jooq.org/doc/latest/manual/reference/reference-data-types/data-types-intervals/#comment-3516813343

**Comment by safaci2000** [comment]
Any updates on this?  It would be useful.

**Comment by lukaseder** [comment]
@safaci2000 Thanks for your message. Yes, it would be useful, no doubt.

**Comment by robertcsakany** [comment]
+1 We also trying figure out how can we use. We would like to simple add datePart which is fraction of second. And haven't found solution.

**Comment by lukaseder** [comment]
@robertcsakany Use `Field.add(interval)`, or `DSL.dateAdd()` or `DSL.timestampAdd()`

**Comment by lukaseder** [comment]
Notice, date time arithmetic is about to be added via https://github.com/jOOQ/jOOQ/issues/10078, soon.

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/10078
