### ISSUE TITLE
Support WHERE clause in ON DUPLICATE KEY UPDATE (Postgres)

### ISSUE THREAD

**Issue by devinrsmith** [jOOQ/jOOQ#6582]
Postgres allows setting of a WHERE condition on the update part of an upsert, https://www.postgresql.org/docs/current/static/sql-insert.html:

```
    DO UPDATE SET { column_name = { expression | DEFAULT } |
                    ( column_name [, ...] ) = ( { expression | DEFAULT } [, ...] ) |
                    ( column_name [, ...] ) = ( sub-SELECT )
                  } [, ...]
              [ WHERE condition ]
```

It doesn't look like this as possible with JOOQ at the moment.

**Comment by lukaseder** [comment]
Thanks for your suggestion. This will be supported in the upcoming jOOQ 3.10: https://github.com/jOOQ/jOOQ/issues/5637, due in 2 weeks.

**Comment by devinrsmith** [comment]
Ah thanks! My github search foo failed me!
