### ISSUE TITLE
Improve DSLContext.batchStore() Javadoc, indicating that it does not execute MERGE / UPSERT semantics

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6584]
People often mistake `batchStore()` for a sort of `MERGE` statement shortcut, which it isn't (although, that would be nice). We should clarify the semantics in the Javadoc.

----
See also:
https://stackoverflow.com/q/46211742/521799

**Comment by safaci2000** [comment]
It would also be nice if the doc provided examples on how to use it in conjunction with an upsert/merge.  That took a while to figure and isn't very obvious for the young un-initiated padawan.

**Comment by lukaseder** [comment]
@safaci2000  I'm not sure what you're referring to. It currently doesn't support upsert/merge...

**Comment by safaci2000** [comment]
Ah, sorry I think I'm confusing it with .batch() I remember using it before and passing it a list of InsertOnDuplicateSetMoreStep which worked fine as far as I can tell.  I stand corrected, sorry for the confusion.
