### ISSUE TITLE
ON CONFLICT clause generated from .onDuplicateKeyUpdate(true) should also contain the unique keys.

### ISSUE THREAD

**Issue by blindbox** [jOOQ/jOOQ#6592]
Creating a new issue instead of continuing #6462  because I realized that I commented on the wrong issue since the previous issue was related to emulation.
### Expected behavior and actual behavior:
Current behavior: Currently `ON CONFLICT` only contains the primary key.

Expected: `ON CONFLICT` clause should also contain the unique keys, as suggested for emulation in #6462 

### Steps to reproduce the problem:
Referring back to this [comment](https://github.com/jOOQ/jOOQ/issues/6462#issuecomment-327661322), I should clarify that when I did a query like this:
```scala
// the table user_details has user_id as the unique key. JOOQ's models has been generated.
val qb = DSL.using(SQLDialect.POSTGRES_9_5)
val userDetailsRecord = new UserDetailsRecord()
userDetailsRecord.setAddress("SomeAddress")
userDetailsRecord.setUserId(123)
val insertQuery = qb.insertQuery(Tables.USER_DETAILS)
insertQuery.addRecord(userDetailsRecord)
insertQuery.onDuplicateKeyUpdate(true)
insertQuery.addValueForUpdate(Tables.USER_DETAILS.ADDRESS, "SomeAddress")
val theSql = insertQuery.getSQL(ParamType.INLINED)
```

`theSql`'s query turns out to be:
```sql
INSERT INTO "USER_DETAILS" ("address", "user_id")
VALUES
  ('SomeAddress', 123)
ON CONFLICT ("id")
  DO UPDATE SET "address" = 'SomeAddress'
```
Notice how the `user_id` doesn't get added to the ON CONFLICT clause, causing a duplicate key  error on `user_id` when running this query

(Note, I might have made some spelling errors because I fuzzied up the names just in case)

### Versions:

- jOOQ: 3.9.3
- Database (include vendor): PostgreSQL 9.5
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver 42.1.1

**Comment by lukaseder** [comment]
Thank you very much for your detailed explanations. I do think that's exactly the same as the issue described in #6462, even if the exact query use-case seems different.

Feel free to reopen if you think that this is really something else... In any case, when using PostgreSQL directly, I do suggest using the `ON CONFLICT` clause directly for best results.
