### ISSUE TITLE
Change the JPADatabase properties

### ISSUE THREAD

**Issue by woniper** [jOOQ/jOOQ#6603]
### Expected behavior and actual behavior:
The jooq-meta-extension(JPADatabase) uses H2DB as a base. How about expanding it so that you can change it to receive url, username, and password using properties and input DB information?

Because you might want to change url, username, password. 
For example, if you want to use h2 mode as mysql. (`jdbc:h2:mem:jooq-meta-extensions;MODE=MYSQL`)
And can I fix it?

### Steps to reproduce the problem:
config.xml
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.9.2.xsd">
    <generator>
        <name>org.jooq.util.DefaultGenerator</name>
        <strategy>
            <name>org.jooq.util.example.JPrefixGeneratorStrategy</name>
        </strategy>
        <database>
            <name>org.jooq.util.jpa.JPADatabase</name>
            <includes>public.*</includes>
            <properties>
                <property>
                    <key>packages</key>
                    <value>com.jooq.domain</value>
                </property>
                <property>
                    <key>url</key>
                    <value>jdbc:h2:mem:jooq-meta-extensions;MODE=MYSQL</value>
                </property>
                <property>
                    <key>username</key>
                    <value>admin</value>
                </property>
                <property>
                    <key>password</key>
                    <value>1234</value>
                </property>
            </properties>
        </database>
        <target>
            <packageName>com.jooq</packageName>
            <directory>src/generated/java</directory>
            <encoding>UTF-8</encoding>
        </target>
    </generator>
</configuration>
```

JPADatabase
```
String url = defaultIfBlank(properties.getProperty("url"), "jdbc:h2:mem:jooq-meta-extensions");
String user = defaultIfBlank(properties.getProperty("user"), "sa");
String password = defaultIfBlank(properties.getProperty("password"), "");

... skip ...

```

### Versions:
- jOOQ: 3.9.5
- Database (include vendor): H2DB
- JDBC Driver (include name if inofficial driver): org.h2.Driver

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. The fact that these two meta data sources are currently using an H2 database behind the scenes should remain an implementation detail. For instance, in the future, we might want to solve such issues more thoroughly by using the actual target database inside a docker container: #6551.

So, instead of adding a new feature (like exposing this internal H2 JDBC URL) that needs to be supported and kept backwards compatible, perhaps we can find another solution for you that solves the problem you're having... What problem are you trying to solve?

**Comment by woniper** [comment]
As I mentioned in the example, I wanted to inject url from outside and set it.
I wanted to set it to mode = mysql, but I thought it was a way to fix it.
thank you.

**Comment by lukaseder** [comment]
Thanks for your message. I understood that this is *what* you'd like to do, but I'm not sure about *why* you want to do that...

**Comment by woniper** [comment]
I want to create a class from JPADatabase to H2DB in mysql mode because I use the actual DB as mysql.
Could the generated class be affected by the DB?

**Comment by lukaseder** [comment]
The database shouldn't affect the generated classes, unless you'd be using fancy data types or stored procedures, which is mostly not the case when people use the `JPADatabase` - so I wouldn't worry about this too much...

**Comment by woniper** [comment]
@lukaseder oh~ thank you so much.
