### ISSUE TITLE
Jooq Gradle plugin fails with Java 9

### ISSUE THREAD

**Issue by relgames** [jOOQ/jOOQ#6605]
### Steps to reproduce the problem:
Run Gradle plugin with Java 9, task "generate"

### Versions:
- jOOQ: 3.9.5
- plugin: 'nu.studer.jooq' version '2.0.7'
- Database (include vendor): postgres

```
> Task :generateEatelliaJooqSchemaSource
Error: Unable to initialize main class org.jooq.util.GenerationTool
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/ValidationEventHandler
```

**Comment by relgames** [comment]
I think I opened it in the wrong repo. Opened there https://github.com/etiennestuder/gradle-jooq-plugin/issues/55

**Comment by etiennestuder** [comment]
I've added an [example](https://github.com/etiennestuder/gradle-jooq-plugin/issues/55#issuecomment-340503912) on how to pass JVM args to the jOOQ generator when using the gradle-jooq-plugin.

**Comment by lukaseder** [comment]
Thank you very much for documenting this, @etiennestuder !

**Comment by etiennestuder** [comment]
Sure, @lukaseder !
