### ISSUE TITLE
Generated table should have compile time constants with field names

### ISSUE THREAD

**Issue by classyPimp** [jOOQ/jOOQ#6618]
The title says it all.
I'm using sort of ORM generation via annotation processing, which uses Jooq under hood.
For example one of the annotations which such processor uses:
```
@TableField(name = "ID")
var id: Long? = null 
```
There, I have to provide a stringified field name, when I could more safely use something like `name = Table.FIELD_NAME_FOR_ID`

**Comment by lukaseder** [comment]
Duplicate of #5210
