### ISSUE TITLE
Postgres 9.3 "insert ... on conflict do nothing" emulation ignores provided column for conflict resolution

### ISSUE THREAD

**Issue by JanecekPetr** [jOOQ/jOOQ#6623]
### Expected behavior and actual behavior:
There are many (some of them closed) issues similar to this, mainly https://github.com/jOOQ/jOOQ/issues/6462 and https://github.com/jOOQ/jOOQ/issues/6592, but either I misunderstood some of them, or the issue is always slightly different. Sorry if this is a duplicate, I tried :).

The emulation of "insert ... on conflict do nothing" for Postgres 9.3 disregards my hint of what column to use for conflict resolution, and uses just the primary key instead. Am I doing something wrong, or this is the intended and only behaviour possible (as suggested in https://github.com/jOOQ/jOOQ/issues/19)?

Given this DDL:

```sql
CREATE TABLE something (
    something_id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE -- yeah, that's a natural primary key in the real code
);
```

in postgres-9.3-mode, I expected this insert:

```java
Insert<SomethingRecord> insert = insertInto(SOMETHING)
    .columns(SOMETHING.NAME)
    .values("blablabla")
    .onConflict(SOMETHING.NAME).doNothing();
```

to generate SQL like:

```sql
insert into something (name)
select t.name
from (
	select ? as name
	where not exists (
		select 1 as one
		from something
		where something.name = ?    -- this line is interesting
	)
) as t
```

Instead, I see:

```sql
insert into something (name)
select t.name
from (
	select ? as name
	where not exists (
		select 1 as one
		from something
		where something.something_id = ?    -- issue here
	)
) as t
```

### Versions:

- jOOQ: 3.10
- Database (include vendor): PostgreSQL 9.3
- JDBC Driver (include name if inofficial driver): 42.1.3

**Comment by lukaseder** [comment]
Thanks a lot for your detailed report. I'm not sure if it's a duplicate, but it's definitely worth exploring more in detail!

**Comment by joe776** [comment]
We encountered the same issue using H2 and jooq 3.10.5.
From looking at the class `InsertQueryImpl` I guess that the issues lies here: https://github.com/jOOQ/jOOQ/blob/dbf7f9d4fc2c8c78a8446b7f4ce1bc8d9a54d588/jOOQ/src/main/java/org/jooq/impl/InsertQueryImpl.java#L450-L451
In the default case `toInsertSelect` simply looks at the primary key, and ignores the QueryPartList `onConflict`.
From the code, it seems that Postgres 9.3 should actually work, as the dialect is explicitly handled. So I'm not exactly sure what else is happening there.

**Comment by JanecekPetr** [comment]
Two years later, as Postgres 9.3 is reaaaly old now, I suggest we close this issue (and/or file a follow-up for H2 as suggested by joe776 above). I hope the number of people who'd benefit from the fix is dropping rapidly every day. We, for example, do no care anymore.

A good compromise would be to mark the `onConflicet(Field field)` method as Postgres 9.5 compatible, only, via an annotation.

**Comment by lukaseder** [comment]
Thanks for the update. We'll still keep the issue open for the moment. There are more systems using old RDBMS versions out there than you'd think (same with JDK versions!) :)

**Comment by lukaseder** [comment]
I've had a look at this issue now. Even if PostgreSQL 9.3 is hardly ever used, this emulation is still being used for Firebird, for example. But it looks as though the issue is gone?

<img width="766" alt="image" src="https://user-images.githubusercontent.com/734593/203799682-82c9eb34-6623-457b-94eb-8330f6eb0242.png">

However, I think that a recent refactoring has removed the `INSERT .. SELECT` emulation for all PG dialect versions, including 9.3 and 9.4. That has to be restored: https://github.com/jOOQ/jOOQ/issues/14294
