### ISSUE TITLE
UpdatableRecordImpl.store() appears broken

### ISSUE THREAD

**Issue by nedtwigg** [jOOQ/jOOQ#6634]
### Expected behavior and actual behavior:

For some very simple code, I get an error when I call `store()`.

### Steps to reproduce the problem:

```sql
CREATE TABLE easytrial
(
  id serial,
  email character varying(255),
)
```

```java
EasytrialRecord trial = new EasytrialRecord();
trial.setEmail("name@email.com");
trial.attach(create.configuration());
trial.insert();

EasytrialRecord resultRecord = create.fetchOne(EASYTRIAL);
assertThat(resultRecord.getEmail()).isEqualTo("name@email.com");
resultRecord.setEmail("someOtherEmail");
resultRecord.store(); // error is thrown here
```

```
ERROR:  column "public" of relation "easytrial" does not exist at character 33
STATEMENT:  update "public"."easytrial" set "public"."easytrial"."email" = $1 where "public"."easytrial"."id" = $2
```

### Versions:

- jOOQ: 3.9.6
- Database (include vendor): PostgreSQL 9.5.3
- JDBC Driver (include name if inofficial driver): 42.1.4

**Comment by lukaseder** [comment]
Thanks for your report. Are you sure the `SQLDialect` inside of your configuration is correctly set to some `POSTGRES` dialect?

**Comment by nedtwigg** [comment]
Aha!  Thanks for the fix!

Due to a weird bootstrapping issue, I have initialize my db url with `jdbc://OVERRIDDEN_PROGRAMATICALLY`, and then I set the real URL later.  But that allowed the "DEFAULT" dialect to sneak through...

**Comment by lukaseder** [comment]
That's what I thought :) The dialect is used here in your case:
https://github.com/jOOQ/jOOQ/blob/version-3.10.0/jOOQ/src/main/java/org/jooq/impl/FieldMapForUpdate.java#L80
