### ISSUE TITLE
Improve "no catalogs were loaded" error message

### ISSUE THREAD

**Issue by deinspanjer** [jOOQ/jOOQ#6644]
### Expected behavior and actual behavior:
Expect to be able to use the maven plugin to generate from a Postgres database same as in 3.9
Actual behavior is the warning:
`[WARNING] No catalogs were loaded  : Please check your connection settings, and whether your database (and your database version!) is really supported by jOOQ. Also, check the case-sensitivity in your configured <inputCatalog/> elements.`

### Steps to reproduce the problem:
Run the maven plugin with a database specified in the jdbc url and an inputCatalog configured in the generator:
```
<configuration>
  <!--<logging>DEBUG</logging>-->
  <jdbc>
    <driver>org.postgresql.Driver</driver>
    <url>jdbc:postgresql://localhost:5432/mydb</url>
    <user>${jooq-codegen.user}</user>
    <password>${jooq-codegen.password}</password>
  </jdbc>
  <generator>
    <database>
      <name>org.jooq.util.postgres.PostgresDatabase</name>
      <inputCatalog>mydb</inputCatalog>
      <outputCatalog>myoutputdb</outputCatalog>
      <inputSchema>myschema</inputSchema>
      <includes>.*</includes>
    </database>
  </generator>
</configuration>
```

In 3.9.2 and earlier, this generates fine, it reads all the objects in the "myschema" schema of the "mydb" database.
In 3.10.0, including the `<inputCatalog>` element causes the generation to fail.  If you omit that configuration element, then it seems to generate as before.

It is fine for this to be a breaking change since that is what the 3.10.0 version allows, but either a better warning or documentation indicating this change would be good. (*please* forgive me if I just missed the documentation somewhere. I did search on the group, github, and the manual for the keywords postgres and inputCatalog.)

### Versions:

- jOOQ: 3.10.0
- Java: 8
- Database (include vendor): Postgres 9.6.2
- JDBC Driver (include name if inofficial driver): official

**Comment by deinspanjer** [comment]
I just hit the same issue when trying to generate from an XMLDatabase with the dialect SQLSERVER to java files:
`[INFO] No <inputCatalog/> was provided. Generating ALL available catalogs instead.`
`[WARNING] No schemata were loaded  : Please check your connection settings, and whether your database (and your database version!) is really supported by jOOQ. Also, check the case-sensitivity in your configured <inputSchema/> elements : null`

The configuration is:
```
<generator>
    <database>
        <name>org.jooq.util.xml.XMLDatabase</name>
        <properties>
            <property>
                <key>dialect</key>
                <value>SQLSERVER</value>
            </property>
            <property>
                <key>xml-file</key>
                <value>
                    ${project.basedir}/src/xml-schemas/${db-version}/information_schema.xml
                </value>
            </property>
        </properties>
        <inputSchema>dbo</inputSchema>
    </database>
</generator>```

**Comment by lukaseder** [comment]
Thank you for your report. I agree there should be a better error message. In fact, catalogs are currently supported only in `SQLServerDatabase`. There's a pending feature request to add support to the `XMLDatabase` as well: #5832.

Do you think there's another error hiding in your second issue, where this error was reported?

> [WARNING] No schemata were loaded : Please check your connection settings, and whether your database (and your database version!) is really supported by jOOQ. Also, check the case-sensitivity in your configured <inputSchema/> elements : null

**Comment by lukaseder** [comment]
... if you think there's another error, please feel free to open another issue and I'll look at this ASAP

**Comment by deinspanjer** [comment]
Well, the reason I titled this as a breaking change is because the exact same jooq-codegen-maven configurations that work with 3.9.2 do not work at all with 3.10.  They report this warning about no catalogs found and do not generate any classes.

Things got more confusing because the solution was different for the two engines.  For Postgres, I had to take the `<inputCatalog>` element out, but for the generation from XML, I have not yet found a solution other than downgrading.

**Comment by lukaseder** [comment]
I see, thanks for the clarifications. Sure, we could call this a breaking change, but the PostgreSQL behaviour was simply wrong. In the presence of a `<inputCatalog/>`  all catalogs that are not input catalogs should be filtered. In the future, we might figure out how to map PostgreSQL's databases to catalogs, because that's what they correspond to:

```sql
SELECT DISTINCT catalog_name FROM information_schema.schemata;
```

Unfortunately, it is currently not possible to discover catalogs across catalogs, so the above query always yields exactly 1 row, right now.

Perhaps, the way forward for you to have consistent behaviour between PostgreSQL and SQL Server is for you to define `<outputCatalogToDefault>` in SQL Server, which will produce an empty "default" catalog, just like in PostgreSQL. This should also work when generating the XML file...

**Comment by deinspanjer** [comment]
I am absolutely fine with removing the inputCatalog for my postgres config (already did so).  I felt this should be documented somewhere in case someone else runs into the issue, which this github issue does adequately. :)

I still haven't figured out what is needed to get the XMLDatabase w/SQLServer dialect config generating though.  I get that warning even though the config does not provide an inputCatalog.  I'll look further and open a new issue if I can get a better repro or other information.

**Comment by lukaseder** [comment]
> I am absolutely fine with removing the inputCatalog for my postgres config (already did so). I felt this should be documented somewhere in case someone else runs into the issue, which this github issue does adequately. :)

I see, sorry, I didn't read this between the lines. Thanks again for documenting all these things! I know it takes time to do so, I really appreciate it.

> I'll look further and open a new issue if I can get a better repro or other information

Yes, please do so. Release 3.10.1 will probably ship on Wednesday, this week. If this is easily fixable, I'll be very happy to include it.
