### ISSUE TITLE
Add support for PostgreSQL 10 IDENTITY columns

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6659]
Support [PostgreSQL 10 `IDENTITY` columns](https://wiki.postgresql.org/wiki/New_in_postgres_10#Identity_Columns) in jOOQ:

- [x] Parser support for SQL standard `GENERATED ... AS IDENTITY` clause
- [x] Support `GENERATED ... AS IDENTITY` in DSL API for `CREATE TABLE` and `ALTER TABLE`

**Comment by timur-sh** [comment]
I'll pick up this one.

I'm starting to investigate of it. Do you have any advices for implementation this feature?

**Comment by lukaseder** [comment]
@timur-sh The first thing that needs to be done is figuring out what needs to be done :-)

These things are probable tasks:

- [ ] Create a table that has an identity and see if the code generator correctly picks it up. If not, fix the code generator. E.g. these two are used in the SQL Server integration tests:

    ```sql
    CREATE TABLE t_identity_pk (
      id INTEGER IDENTITY(1,1) NOT NULL,
      val int,
    
      CONSTRAINT pk_t_identity_pk PRIMARY KEY (id)
    );
    CREATE TABLE t_identity (
      id INTEGER IDENTITY(1,1) NOT NULL,
      val int
    );
    ```

- [ ] Retrofit the DDL APIs to generate identity columns rather than serials if `SQLDialect.POSTGRES` or `SQLDialect.POSTGRES_10` is used.
- [ ] Adapt the parser to any PostgreSQL specific IDENTITY syntax

**Comment by timur-sh** [comment]
I retrofitted the code generation and DDL APIs to work with identity columns of PostgreSQL 10 and previous versions. The Parser isn't required any modifications.

**Comment by mkurz** [comment]
@timur-sh @lukaseder so is there more work that needs to be done besides https://github.com/timur-sh/jOOQ/commit/e1bc3a178a3903ec145232518e782ac33b1af5a4? Would be great to see this in 3.11... :wink:

**Comment by lukaseder** [comment]
@mkurz Thanks for the ping. The feature has been postponed to 3.12 for now

**Comment by azell** [comment]
Recent versions of Postgres set `COLUMNS.IS_IDENTITY` as expected.  Version 9 does not, and will presumably still need the custom logic in **PostgresTableDefinition.getElements0**

```
              record.get(COLUMNS.IS_IDENTITY, boolean.class) // this is new!
                  || defaultString(record.get(COLUMNS.COLUMN_DEFAULT))
                      .trim()
                      .toLowerCase()
                      .startsWith("nextval"),
```

**Comment by mjburghoffer** [comment]
Are there any workaround to forcing IDENTITY to be used instead of SERIAL when generating a CREATE TABLE statement from a table?

**Comment by knutwannheden** [comment]
As a consequence of implementing this change, the jOOQ 3.13 open source edition will no longer be able to execute `CREATE TABLE` with identity (`SERIAL`) columns statements (built using jOOQ's DDL API) against PostgreSQL 9 and older.

**Comment by lukaseder** [comment]
@knutwannheden What subtasks are still missing here?

**Comment by knutwannheden** [comment]
> @knutwannheden What subtasks are still missing here?

I am still investigating this. All previously discussed topics should already be addressed now. For instance I would like to check if `ALTER TABLE` needs any changes.

**Comment by lukaseder** [comment]
I see. Could you perhaps edit the issue description and add a bullet list with what has been done and what you think still needs doing?

**Comment by knutwannheden** [comment]
AFAICT everything is now in place.
