### ISSUE TITLE
SQLPerformanceWarning

### ISSUE THREAD

**Issue by GordeevArt** [jOOQ/jOOQ#6675]
There are warnings in code generation (tool for gradle org.jooq.util.GenerationTool):

> WARNING: Slow SQL                 : Total: 9.245s
> Oct 10, 2017 12:45:15 PM org.jooq.tools.JooqLogger warn
> WARNING: Slow SQL                 : jOOQ Meta executed a slow query (slower than 5 seconds)
> 
> Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new
> ```sql
> with recursive "domains"("domain_id", "base_id", "typbasetype", "src") as (
>   (
>     select 
>       "d".oid, 
>       "d".oid, 
>       "d"."typbasetype", 
>       array["c"."consrc"]
>     from "pg_catalog"."pg_type" as "d"
>       join "pg_catalog"."pg_namespace" as "n"
>       on "n".oid = "d"."typnamespace"
>       left outer join "pg_catalog"."pg_constraint" as "c"
>       on "d".oid = "c"."contypid"
>     where (
>       "d"."typtype" = 'd'
>       and "n"."nspname" in ('public')
>     )
>   )
>   union all (
>     select 
>       "domains"."domain_id", 
>       "d".oid, 
>       "d"."typbasetype", 
>       case when "c"."consrc" is null then "domains"."src"
>            else array_append("domains"."src", "c"."consrc")
>       end
>     from "domains"
>       join "pg_catalog"."pg_type" as "d"
>       on "domains"."typbasetype" = "d".oid
>       left outer join "pg_catalog"."pg_constraint" as "c"
>       on "d".oid = "c"."contypid"
>   )
> )
> select 
>   "n"."nspname", 
>   "d"."typname", 
>   "d"."typnotnull", 
>   "d"."typdefault", 
>   "b"."typname", 
>   "b"."typlen", 
>   "domains"."src"
> from "pg_catalog"."pg_type" as "d"
>   join "domains"
>   on (
>     "domains"."typbasetype" = 0
>     and "domains"."domain_id" = "d".oid
>   )
>   join "pg_catalog"."pg_type" as "b"
>   on "domains"."base_id" = "b".oid
>   join "pg_catalog"."pg_namespace" as "n"
>   on "n".oid = "d"."typnamespace"
> where (
>   "d"."typtype" = 'd'
>   and "n"."nspname" in ('public')
> )
> org.jooq.util.AbstractDatabase$1$SQLPerformanceWarning
> 	at org.jooq.util.AbstractDatabase$1.executeEnd(AbstractDatabase.java:273)
> 	at org.jooq.impl.ExecuteListeners.executeEnd(ExecuteListeners.java:162)
> 	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:274)
> 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
> 	at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:315)
> 	at org.jooq.impl.AbstractResultQuery.iterator(AbstractResultQuery.java:326)
> 	at org.jooq.impl.SelectImpl.iterator(SelectImpl.java:2718)
> 	at org.jooq.util.postgres.PostgresDatabase.getDomains0(PostgresDatabase.java:534)
> 	at org.jooq.util.AbstractDatabase.getDomains(AbstractDatabase.java:1323)
> 	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:481)
> 	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:376)
> 	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:298)
> 	at org.jooq.util.GenerationTool.run(GenerationTool.java:617)
> 	at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
> 	at org.jooq.util.GenerationTool.main(GenerationTool.java:175)
> ```

- jOOQ: 3.9.5
- Java: 1.8
- Database: PostgreSQL 9.6.2
- JDBC Driver: org.postgresql:postgresql:42.1.3.jre7
- Gradle: 4.1

**Comment by GordeevArt** [comment]
[types.txt](https://github.com/jOOQ/jOOQ/files/1374771/types.txt)
Yes, the system has huge number of custom pg-functions yet.

19 rows:

>  nspname |         typname         | typnotnull | typdefault |  typname  | typlen |                                                src                                                
> ---------+-------------------------+------------+------------+-----------+--------+---------------------------------------------------------------------------------------------------
>  public  | datetime                | f          |            | timestamp |      8 | {NULL}
>  public  | mediumstring            | f          |            | varchar   |     -1 | {NULL}
>  public  | shortstring             | f          |            | varchar   |     -1 | {NULL}
>  public  | longstring              | f          |            | varchar   |     -1 | {NULL}
>  public  | inner_id_string         | f          |            | varchar   |     -1 | {NULL}
>  public  | letter                  | f          |            | varchar   |     -1 | {NULL}
>  public  | sex                     | f          |            | varchar   |     -1 | {"((VALUE)::text = ANY (ARRAY[('M'::character varying)::text, ('F'::character varying)::text]))"}
>  public  | phone                   | f          |            | varchar   |     -1 | {"((VALUE)::text ~ '^\\+[0-9]{1,3} \\([0-9]{1,7}\\) [0-9]{1,9}'::text)"}
>  public  | short_contingent_string | f          |            | varchar   |     -1 | {NULL}
>  public  | double                  | f          |            | float8    |      8 | {NULL}
>  public  | negative                | f          |            | float8    |      8 | {"(VALUE < (0)::double precision)"}
>  public  | nonnegative             | f          |            | float8    |      8 | {"(VALUE >= (0)::double precision)"}
>  public  | positive                | f          |            | float8    |      8 | {"(VALUE > (0)::double precision)"}
>  public  | skey                    | f          |            | int4      |      4 | {NULL}
>  public  | fskey                   | f          |            | int4      |      4 | {NULL}
>  public  | fskeyp                  | t          |            | int4      |      4 | {NULL}
>  public  | negativeint             | f          |            | int4      |      4 | {"(VALUE < 0)"}
>  public  | nonnegativeint          | f          |            | int4      |      4 | {"(VALUE >= 0)"}
>  public  | positiveint             | f          |            | int4      |      4 | {"(VALUE > 0)"}
> (19 rows)

Domains:

>  typnamespace | count 
> --------------+-------
>          2200 |    19
>         12981 |     5
> (2 rows)

Catalog types in attachment.

**Comment by lukaseder** [comment]
Oh, I see, thanks for the quick reply. The number of domains you have is rather slim, but the query somehow recursively pulls in all the many types that are irrelevant to the query itself. I'll see what can be done.

**Comment by GordeevArt** [comment]
Ok, thank you

**Comment by lukaseder** [comment]
Hmm, I cannot seem to reproduce the issue. I've added:

- Around 20 domains
- Around 6000 composite types
- Around 3000 tables using the 20 domains

E.g. with scripts like these:

```sql
DO $$
DECLARE
  stmt TEXT;
BEGIN
  FOR stmt IN (
    SELECT 'create domain d' || n || ' AS int CHECK (VALUE > 0);' AS stmt
    FROM generate_series(1, 20) s(n)
  ) LOOP
    EXECUTE stmt;
  END LOOP;
END $$;
```

The query still runs very fast. I've tried with PostgreSQL 9.6.5, though, perhaps there's an optimisation that was implemented between 9.6.2 and 9.6.5? After a quick glance, I hadn't seen anything special in the release notes...

What do you get when you run `EXPLAIN` on the original query run by jOOQ?

**Comment by GordeevArt** [comment]
Well, I triyed on different databases with same structure:

>                                                                               QUERY PLAN                                                                               
> -----------------------------------------------------------------------------------------------------------------------------------------------------------------------
>  Nested Loop  (cost=2349.73..2383.72 rows=1 width=270) (actual time=2.205..3.218 rows=19 loops=1)
>    CTE domains
>      ->  Recursive Union  (cost=0.28..2349.04 rows=404 width=44) (actual time=0.086..3.094 rows=38 loops=1)
>            ->  Nested Loop Left Join  (cost=0.28..197.07 rows=4 width=44) (actual time=0.085..0.760 rows=19 loops=1)
>                  ->  Nested Loop  (cost=0.00..147.00 rows=4 width=8) (actual time=0.070..0.714 rows=19 loops=1)
>                        Join Filter: (d_1.typnamespace = n_1.oid)
>                        Rows Removed by Join Filter: 5
>                        ->  Seq Scan on pg_namespace n_1  (cost=0.00..1.07 rows=1 width=4) (actual time=0.011..0.011 rows=1 loops=1)
>                              Filter: (nspname = 'public'::name)
>                              Rows Removed by Filter: 5
>                        ->  Seq Scan on pg_type d_1  (cost=0.00..145.62 rows=24 width=12) (actual time=0.058..0.700 rows=24 loops=1)
>                              Filter: (typtype = 'd'::"char")
>                              Rows Removed by Filter: 2987
>                  ->  Index Scan using pg_constraint_contypid_index on pg_constraint c  (cost=0.28..11.16 rows=136 width=43) (actual time=0.001..0.001 rows=0 loops=19)
>                        Index Cond: (d_1.oid = contypid)
>            ->  Hash Right Join  (cost=151.59..214.39 rows=40 width=44) (actual time=1.155..1.159 rows=10 loops=2)
>                  Hash Cond: (c_1.contypid = d_2.oid)
>                  ->  Seq Scan on pg_constraint c_1  (cost=0.00..56.91 rows=1491 width=43) (actual time=0.003..0.186 rows=1492 loops=1)
>                  ->  Hash  (cost=151.09..151.09 rows=40 width=44) (actual time=0.935..0.935 rows=10 loops=2)
>                        Buckets: 1024  Batches: 1  Memory Usage: 8kB
>                        ->  Hash Join  (cost=1.30..151.09 rows=40 width=44) (actual time=0.460..0.931 rows=10 loops=2)
>                              Hash Cond: (d_2.oid = domains_1.typbasetype)
>                              ->  Seq Scan on pg_type d_2  (cost=0.00..138.10 rows=3010 width=8) (actual time=0.002..0.694 rows=3011 loops=2)
>                              ->  Hash  (cost=0.80..0.80 rows=40 width=40) (actual time=0.008..0.008 rows=19 loops=2)
>                                    Buckets: 1024  Batches: 1  Memory Usage: 10kB
>                                    ->  WorkTable Scan on domains domains_1  (cost=0.00..0.80 rows=40 width=40) (actual time=0.001..0.002 rows=19 loops=2)
>    ->  Nested Loop  (cost=0.56..34.02 rows=1 width=210) (actual time=2.201..3.192 rows=19 loops=1)
>          ->  Nested Loop  (cost=0.28..25.71 rows=1 width=148) (actual time=2.196..3.156 rows=19 loops=1)
>                ->  CTE Scan on domains  (cost=0.00..9.09 rows=2 width=40) (actual time=2.188..3.113 rows=19 loops=1)
>                      Filter: (typbasetype = '0'::oid)
>                      Rows Removed by Filter: 19
>                ->  Index Scan using pg_type_oid_index on pg_type d  (cost=0.28..8.30 rows=1 width=116) (actual time=0.002..0.002 rows=1 loops=19)
>                      Index Cond: (oid = domains.domain_id)
>                      Filter: (typtype = 'd'::"char")
>          ->  Index Scan using pg_type_oid_index on pg_type b  (cost=0.28..8.30 rows=1 width=70) (actual time=0.001..0.002 rows=1 loops=19)
>                Index Cond: (oid = domains.base_id)
>    ->  Index Scan using pg_namespace_oid_index on pg_namespace n  (cost=0.13..0.65 rows=1 width=68) (actual time=0.001..0.001 rows=1 loops=19)
>          Index Cond: (oid = d.typnamespace)
>          Filter: (nspname = 'public'::name)
>  Planning time: 0.673 ms
>  Execution time: 3.362 ms
> (41 rows)
 

>  Nested Loop  (cost=2162.33..2196.32 rows=1 width=270) (actual time=346.299..347.478 rows=19 loops=1)
>    CTE domains
>      ->  Recursive Union  (cost=0.28..2161.64 rows=404 width=44) (actual time=13.136..347.293 rows=38 loops=1)
>            ->  Nested Loop Left Join  (cost=0.28..180.12 rows=4 width=44) (actual time=13.134..264.292 rows=19 loops=1)
>                  ->  Nested Loop  (cost=0.00..130.28 rows=4 width=8) (actual time=1.685..220.953 rows=19 loops=1)
>                        Join Filter: (d_1.typnamespace = n_1.oid)
>                        Rows Removed by Join Filter: 5
>                        ->  Seq Scan on pg_namespace n_1  (cost=0.00..1.07 rows=1 width=4) (actual time=0.008..0.009 rows=1 loops=1)
>                              Filter: (nspname = 'public'::name)
>                              Rows Removed by Filter: 5
>                        ->  Seq Scan on pg_type d_1  (cost=0.00..128.90 rows=24 width=12) (actual time=1.676..220.932 rows=24 loops=1)
>                              Filter: (typtype = 'd'::"char")
>                              Rows Removed by Filter: 2984
>                  ->  Index Scan using pg_constraint_contypid_index on pg_constraint c  (cost=0.28..11.06 rows=140 width=43) (actual time=2.278..2.278 rows=0 loops=19)
>                        Index Cond: (d_1.oid = contypid)
>            ->  Hash Right Join  (cost=134.79..197.34 rows=40 width=44) (actual time=41.475..41.484 rows=10 loops=2)
>                  Hash Cond: (c_1.contypid = d_2.oid)
>                  ->  Seq Scan on pg_constraint c_1  (cost=0.00..56.45 rows=1545 width=43) (actual time=0.005..80.655 rows=1505 loops=1)
>                  ->  Hash  (cost=134.29..134.29 rows=40 width=44) (actual time=1.035..1.035 rows=10 loops=2)
>                        Buckets: 1024  Batches: 1  Memory Usage: 8kB
>                        ->  Hash Join  (cost=1.30..134.29 rows=40 width=44) (actual time=0.529..1.028 rows=10 loops=2)
>                              Hash Cond: (d_2.oid = domains_1.typbasetype)
>                              ->  Seq Scan on pg_type d_2  (cost=0.00..121.52 rows=2952 width=8) (actual time=0.004..0.824 rows=3008 loops=2)
>                              ->  Hash  (cost=0.80..0.80 rows=40 width=40) (actual time=0.010..0.010 rows=19 loops=2)
>                                    Buckets: 1024  Batches: 1  Memory Usage: 10kB
>                                    ->  WorkTable Scan on domains domains_1  (cost=0.00..0.80 rows=40 width=40) (actual time=0.002..0.002 rows=19 loops=2)
>    ->  Nested Loop  (cost=0.56..34.02 rows=1 width=210) (actual time=346.279..347.435 rows=19 loops=1)
>          ->  Nested Loop  (cost=0.28..25.71 rows=1 width=148) (actual time=346.273..347.401 rows=19 loops=1)
>                ->  CTE Scan on domains  (cost=0.00..9.09 rows=2 width=40) (actual time=346.252..347.330 rows=19 loops=1)
>                      Filter: (typbasetype = '0'::oid)
>                      Rows Removed by Filter: 19
>                ->  Index Scan using pg_type_oid_index on pg_type d  (cost=0.28..8.30 rows=1 width=116) (actual time=0.003..0.003 rows=1 loops=19)
>                      Index Cond: (oid = domains.domain_id)
>                      Filter: (typtype = 'd'::"char")
>          ->  Index Scan using pg_type_oid_index on pg_type b  (cost=0.28..8.30 rows=1 width=70) (actual time=0.001..0.001 rows=1 loops=19)
>                Index Cond: (oid = domains.base_id)
>    ->  Index Scan using pg_namespace_oid_index on pg_namespace n  (cost=0.13..0.65 rows=1 width=68) (actual time=0.002..0.002 rows=1 loops=19)
>          Index Cond: (oid = d.typnamespace)
>          Filter: (nspname = 'public'::name)
>  Planning time: 269.865 ms
>  Execution time: 347.628 ms
> (41 rows)

Well, it is fast now. Maybe it produces when Postgres is overloaded.

**Comment by lukaseder** [comment]
> Well, it is fast now. Maybe it produces when Postgres is overloaded.

Thanks for the details. OK if it only happened once, I'll happily continue investigating when it happens again. For then, we already have the execution plans (although, the execution time looks reasonable in those plans)

**Comment by lukaseder** [comment]
This issue has not seen any traction recently, neither on the OP's system, nor on anyone else's system.

Closing this for now. We can reopen if it re-appears.
