### ISSUE TITLE
DDLDatabase fails when engine=InnoDB is specified

### ISSUE THREAD

**Issue by jkubrynski** [jOOQ/jOOQ#6708]
If an engine is defined for a table DDLDatabase throws `C42000_NO_SUBCLASS`:

```
create table test (id bigint) engine=InnoDB;
```

**Comment by lukaseder** [comment]
Thanks for your report. Indeed, these vendor specific storage clauses are currently not parsed correctly as they have no representation in the jOOQ DSL API. I'll look into this ASAP.

**Comment by lukaseder** [comment]
This depends on #6131, which I'll implement for 3.11 right now

**Comment by lukaseder** [comment]
Thanks again for your report. This feature has been added to the parser. Unfortunately, as this depends on new API, we can only release the fix in jOOQ 3.11

**Comment by lukaseder** [comment]
@jkubrynski Do you have any other similar features that you'd be expecting from the `DDLDatabase`? Rather than iterating on individual issues over weeks, I'd be happy to implement a bulk of missing features in one go...

**Comment by jkubrynski** [comment]
I've already submitted all I had :)
