### ISSUE TITLE
Support precision on TIME and TIMESTAMP data types

### ISSUE THREAD

**Issue by jkubrynski** [jOOQ/jOOQ#6726]
For example in MySQL 5.7 you can use `datatime(6)` which fails in JOOQ parser

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. You're absolutely right, this is an important missing feature, especially in the DDL module of jOOQ. Currently, jOOQ only supports `TIMESTAMP` data types without any precision (which usually applies a default precision).

This should definitely be fixed.

**Comment by lukaseder** [comment]
This was not implemented for JSR-310 types, unfortunately: #10193
