### ISSUE TITLE
why JooQ's  DAOImpl insert(P p) with refresh method？

### ISSUE THREAD

**Issue by thegodofwar** [jOOQ/jOOQ#6728]
when i use jooq's DAOImpl like this    
```java
@Repository
public class DingTaskDao extends DAOImpl<DingdingCorpTaskRecord, DingdingCorpTask, Long> {

  @Autowired(required = false)
  @Qualifier(value = "xissContext")
  private DSLContext xissContext;

  @PostConstruct
  public void init() {
    Optional.ofNullable(xissContext).ifPresent(x -> setConfiguration(x.configuration()));
  }

  public DingTaskDao() {
    super(DINGDING_CORP_TASK, DingdingCorpTask.class);
  }

  @Override
  public Long getId(DingdingCorpTask dingdingCorpTask) {
    return dingdingCorpTask.getId();
  }

}
```

when i use these code below:

```java
DingdingCorpTask dingdingCorpTask = new DingdingCorpTask();
    dingdingCorpTask.setSeeds("seeds");
    dingTaskDao.insert(dingdingCorpTask);
```

focus error:
`Exactly one row expected for refresh. Record does not exist in database`

> when i see debug  log of jooq ,i find DAOImpl'insert(P p) will execute select pojo from db where pk=? after  insert. 

so i think the reason of this error is:

> we use a db proxy that wtite sql like insert will connect to mysql master server and execute,but read sql like select connect to mysql slave server and execute.

- i am very very wondering why DAOImpl's insert(P p) contains refresh methed（with a duplicated select）？

- can i forbid refresh methed of DAOImpl's insert(P p)？

### Versions:

- jOOQ:3.9.5
- Java:1.8
- Database (include vendor):mysql 5.6+
- JDBC Driver (include name if inofficial driver):5.1.30

**Comment by lukaseder** [comment]
Thank you very much for your report and for your questions:

> i am very very wondering why DAOImpl's insert(P p) contains refresh methed（with a duplicated select）？

Internally, `DAOImpl` delegates to `UpdatableRecordImpl.insert()`, which fetches generated keys and other generated columns. Depending on the database you're using (including MySQL), this might result in a separate `SELECT` query.

> can i forbid refresh methed of DAOImpl's insert(P p)？

Yes you can. The `Settings.returnAllOnUpdatableRecord` flag governs this.

**Comment by thegodofwar** [comment]
thank you very much,lukaseder! but are you sure about

> Settings.returnAllOnUpdatableRecord

i find source code of UpdatableRecordImpl 
` final Collection<Field<?>> setReturningIfNeeded(StoreQuery<R> query) {
        Collection<Field<?>> key = null;

        if (configuration() != null)
            if (!TRUE.equals(configuration().data(DATA_OMIT_RETURNING_CLAUSE)))

                // [#1859] Return also non-key columns
                if (TRUE.equals(configuration().settings().isReturnAllOnUpdatableRecord()))
                    key = Arrays.asList(fields());

                // [#5940] Getting the primary key mostly doesn't make sense on UPDATE statements
                else if (query instanceof InsertQuery || updatablePrimaryKeys(settings(this)))
                    key = getReturning();

        if (key != null)
            query.setReturning(key);

        return key;
    }`

i think right answer is 

> configuration().data(DATA_OMIT_RETURNING_CLAUSE) = true;

@lukaseder

**Comment by lukaseder** [comment]
@thegodofwar Have you tried it?

1. We still want to fetch generated identities by default. This is done through `Statement.getGeneratedKeys()` for MySQL. See: https://github.com/jOOQ/jOOQ/blob/version-3.10.1/jOOQ/src/main/java/org/jooq/impl/AbstractDMLQuery.java#L506
2. The other columns are no longer fetched if we're looking only for the identity value. See https://github.com/jOOQ/jOOQ/blob/version-3.10.1/jOOQ/src/main/java/org/jooq/impl/AbstractDMLQuery.java#L674
3. You cannot set the `DATA_OMIT_RETURNING_CLAUSE` flag, that's an internal flag

**Comment by thegodofwar** [comment]
@lukaseder  i have tried it. this config Not Work.
`x.configuration().settings().setReturnAllOnUpdatableRecord(false);`
still excute:
`select `yuwan`.`user`.`id` from `yuwan`.`user` where `yuwan`.`user`.`id` = ?`

`x.configuration().settings().setReturnAllOnUpdatableRecord(true);`
still execute:
` select `yuwan`.`user`.`id`, `yuwan`.`user`.`name`, `yuwan`.`user`.`password`, `yuwan`.`user`.`address`, `yuwan`.`user`.`telephone`, `yuwan`.`user`.`avatar`, `yuwan`.`user`.`nick`, `yuwan`.`user`.`platform`, `yuwan`.`user`.`open_id`, `yuwan`.`user`.`register_time`, `yuwan`.`user`.`last_login_time` from `yuwan`.`user` where `yuwan`.`user`.`id` in (?)`
