### ISSUE TITLE
An example of enum generation

### ISSUE THREAD

**Issue by czyzby** [jOOQ/jOOQ#6740]
It seems that previous version of jOOQ allowed generating enumeration tables, but it is no longer possible with the official API. Is there an example of a custom code generator that is able to fetch all rows from a table and generate an enum instead of a table class?

**Comment by lukaseder** [comment]
Thanks for your message. Yes, indeed, the master data generation feature was removed with jOOQ 3.0. You can still look at version 2.6.2's sources on Maven Central:
http://search.maven.org/#artifactdetails%7Corg.jooq%7Cjooq-codegen%7C2.6.2%7Cjar

Essentially, you just take inspiration from the `JavaGenerator`, hook into some of the overridable methods, fetch the rows from your tables (preferably using jOOQ, of course) and use the internal `JavaGenerator` API to create the class...
