### ISSUE TITLE
Code generator could ideally generate a static field containing the name

### ISSUE THREAD

**Issue by rohanprabhu** [jOOQ/jOOQ#6744]
### Expected behavior and actual behavior:

If the generated code generated something similar to:

    public class Users extends TableImpl<UsersRecord> {
        public final static NAME = "users";
   
       ...
    }

It would be really useful and provide a good amount of compile-time safety (and refactor safety as well) by allowing the usage of this name in annotations (a good number of people use a mix of JPA + jOOQ, and this makes the integration even better):

    @Column(name = Tables.USERS.NAME)

And probably for some other places where people might be using custom annotations. As of now in other parts of the code one could do it with `Tables.USERS.getName()`, but this obviously cannot be used in annotations

### Steps to reproduce the problem:

*Feature request, not a bug*

### Versions:

*Feature request, not a bug*

**Comment by lukaseder** [comment]
Thanks for your suggestion. Yes that could be a useful feature in some situations. We're tracking this idea under #5210

In the meantime, it's relatively easy to enhance the `JavaGenerator` by overriding it and implementing a custom code section:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-custom-code/
