### ISSUE TITLE
DDL statements on MySQL create CHAR column instead of VARCHAR column on unknown lengths

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6745]
When running DDL statements on MySQL, e.g.

```java
    public void testCreateTableWithUnknownLengthStringColumn() throws Exception {
        Table<?> t = table(name("t"));
        Field<String> s = field(name("s"), String.class);

        try {
            create().createTable(t).columns(s).execute();
            assertEquals(1, create().insertInto(t, s).values((String) null).execute());
            assertEquals(1, create().insertInto(t, s).values("a").execute());
            assertEquals(1, create().insertInto(t, s).values("abc").execute());
            assertEquals(1, create().insertInto(t, s).values("abcdefghijklmnopqrstuvwxyz").execute());

            List<String> list = create().select(s).from(t).orderBy(s.asc().nullsFirst()).fetch(s);
            assertEquals(asList(null, "a", "abc", "abcdefghijklmnopqrstuvwxyz"), list);
        }
        finally {
            ignoreThrows(create().dropTable(t)::execute);
        }
    }
```

Then, a `char` column is created instead of a `varchar` column:

```sql
create table `t`(
  `s` char null
)
```

This is because the cast data type is used for DDL, not the actual data type.

The problem even persists when specifying:

```java
Field<String> s = field(name("s"), SQLDataType.VARCHAR);
```

But not when specifying:

```java
Field<String> s = field(name("s"), SQLDataType.VARCHAR(30));
```

The difficulty will be to pick a reasonable default length for DDL as MySQL has a maximum row size of 65535: https://stackoverflow.com/a/13506920/521799

A reasonable solution would be to generate

```sql
create table `t`(
  `s` text null
)
```

----
See also:
- https://groups.google.com/forum/#!topic/jooq-user/i0MswJr_N_M
- https://groups.google.com/forum/#!topic/jooq-user/61qU8PbFBNM

**Comment by lukaseder** [comment]
@knutwannheden This issue has been bugging me for a while - I'm uncertain what the solution should be here. TL;DR: MySQL doesn't know `VARCHAR` columns of unspecified length, and picking a random default length is tricky because of the maximum rowsize of 65535.

What's your opinion here?

**Comment by lukaseder** [comment]
The issue can be illustrated on https://www.jooq.org/translate/

![image](https://user-images.githubusercontent.com/734593/59698012-1fe7b180-91ef-11e9-9b73-d44e33b64ded.png)

**Comment by knutwannheden** [comment]
I have very limited knowledge about MySQL. What we do for Oracle (use VARCHAR(4000)) makes sense. I assume using the maximum isn't necessarily valid on MySQL?

**Comment by lukaseder** [comment]
The point is that an entire *row* can have at most 65535 bytes in MySQL

**Comment by knutwannheden** [comment]
Also for Oracle the `VARCHAR2(4000)` type may seem somewhat arbitrary. Depending on the context (e.g. when translating between dialects) it may not make sense or possibly the database has extended data types enabled (allowing up to `VARCHAR2(32K)`, although implicitly using `CLOB`s behind the scene) and would rather use longer strings.

AFAIK `TEXT` in MySQL can in expressions be treated like a normal `VARCHAR` (e.g. when using string functions), so I am thinking we may just as well use that. Of course it will have implications for performance, etc. But IMHO it may be a good compromise.

**Comment by lukaseder** [comment]
> Also for Oracle the VARCHAR2(4000) type may seem somewhat arbitrary. Depending on the context (e.g. when translating between dialects) it may not make sense or possibly the database has extended data types enabled (allowing up to VARCHAR2(32K), although implicitly using CLOBs behind the scene) and would rather use longer strings.

Indeed, we need to think about how to emulate "max varchar2" data types in Oracle at some point. Until then, `VARCHAR2(4000)` is a very reasonable default, because what else would a user expect when translating from a dialect that allows "max varchar" semantics to be expressed with a `varchar` type without length?

> AFAIK TEXT in MySQL can in expressions be treated like a normal VARCHAR (e.g. when using string functions), so I am thinking we may just as well use that. Of course it will have implications for performance, etc. But IMHO it may be a good compromise.

We currently map `TEXT` to `SQLDataType.CLOB` for dialects like MySQL and PostgreSQL

**Comment by lukaseder** [comment]
We'll fix this by translating length-less `varchar` types to `text` in MySQL dialect families.
