### ISSUE TITLE
PostgreSQL 10 multi column update expressions should use ROW()

### ISSUE THREAD

**Issue by rrrrrrrramba** [jOOQ/jOOQ#6763]
I am experimenting with PostgreSQL v10 and jOOQ 3.10.1.

Since PGv10, there is a break/fix in `UPADTE` queries with row value expressions. See https://www.postgresql.org/message-id/j9WVrqf9R9p8t103UQjQsp4u5-T579pZ-z8vB4vCYeApzBrqtr8XTQeWWWjlqRs0Lk2Fm8Oilxv6y2VC6q0hAy2V48i9a3xqDJ2ZMnrK_Q8%3D%40protonmail.com for background information. It boils down to the following query:

`UPDATE some_table SET (some_column) = (some_value)`

This is not allowed anymore. If there is just one column, we must add `ROW()`:

`UPDATE some_table SET (some_column) = ROW(some_value)`

Now, I did some experiments in jOOQ and encountered a case in which jOOQ produces an incorrect query for a v10 database. The following expression produces a query without `ROW()`. Here, `select()` returns a select statement which returns just one column:

```java
public Table<Record> table() { return ... }
public List<Field<?>> fields() { return ... }
public Select<Record> select() { return ... }

ctx.update(table()).set((Row1) DSL.row(fields()), (Row1) select().fieldsRow()).from(select())
```

Sidenote: Regarding the casts to `Row1`, I expected the following to work, but it produces a compile error:

```java
public Table<Record> table() { return ... }
public List<Field<?>> fields() { return ... }
public Select<Record> select() { return ... }

ctx.update(table()).set(DSL.row(fields()), select().fieldsRow()).from(select())
```

Let me know if you need more information from me. Thank you.

**Comment by lukaseder** [comment]
Thanks for pointing this out. That's an very surprising, backwards-incompatible change. Well, we can fix it on our side by introducing a new `SQLDialect` in jOOQ 3.11. The problem is that the new `ROW` syntax was rejected in PostgreSQL 9.6, so the execution of this change is really very unfortunate...

There are two workarounds I can see right now:

- Introduce a dummy column and always update that as well
- Manually check if your row is of degree 1, and if it is, avoid `Row1` and use an ordinary, single-column update instead.

      ```java
      if (fields().length == 1))
          ctx.update(table()).set((Field) fields()[0], (Field) field(select())).execute();
      else
          ctx.update(table()).set((Row1) DSL.row(fields()), (Row1) select().fieldsRow()).from(select()).execute();
      ```

**Comment by lukaseder** [comment]
Backporting the addition of a new `SQLDialect` is too risky for regressions, so we cannot backport a fix that relies on the new SQLDialect to e.g. 3.10.2.

I think that with the documented workaround above (not using `Row1` with `UPDATE`), we're not in a hurry to backport this fix for an issue that probably doesn't appear too often.

**Comment by rrrrrrrrramba** [comment]
Hi Lukas,

Thank you for feedback. Always adding the `ROW()` for v10+ seems like a good fix.

Note that the UPSERT case is also impacted: `INSERT INTO ... ON CONFLICT DO UPDATE ...`. (And possibly other constructions which involve an `UPDATE`).

**Comment by lukaseder** [comment]
We currently do not support `ROW()` for upsert. Maybe we should...

**Comment by rrrrrrrrramba** [comment]
You should! :)

**Comment by lukaseder** [comment]
Perhaps. But not a high priority.

**Comment by rrrrrrrrramba** [comment]
I agree. It could be easily written as a `UPDATE ... SET (..., ..., ...) = (select ..., ..., ...)`.
