### ISSUE TITLE
Avoid setting DefaultExecuteContext ThreadLocals if not needed

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6767]
There are a few `ThreadLocal` variables in `DefaultExecuteContext`, which are always set but hardly ever used:

- `DefaultExecuteContext.LOCAL_DATA` (needed only for Oracle UDT bindings)
- `DefaultExecuteContext.LOCAL_CONNECTION` (needed only for Oracle Array bindings)
- `DefaultExecuteContext.LOCAL_CONFIGURATION` (needed only for Oracle UDT bindings)

Allocating the thread local map internally can be costly as is shown in this benchmark:

![image](https://user-images.githubusercontent.com/734593/32221160-c19151ac-be34-11e7-821c-152eb1702ccb.png)

We can easily avoid the allocation for non-Oracle dialects, and perhaps allocate things lazily in Oracle

**Comment by timur-sh** [comment]
I'm not sure where I should post this question :)

Could you let know, what tool you use to do the benchmark?

**Comment by lukaseder** [comment]
The screenshots were taken from JMC, which ships with the JDK and is free to use for development (not for production): http://www.oracle.com/technetwork/java/javaseproducts/mission-control/java-mission-control-1998576.html (if in doubt, ask Oracle what the difference between the two is).

Note that this isn't a benchmarking tool, but a profiling tool, operating on samples, and thus being biased in many ways. If you really want to benchmark your code, use JMH instead: http://openjdk.java.net/projects/code-tools/jmh/ (or combine the two)

**Comment by timur-sh** [comment]
Thanks a lot!

**Comment by lukaseder** [comment]
I haven't come across this again in subsequent profiling sessions.
