### ISSUE TITLE
Add a <jpaVersion/> code generator configuration

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6772]
When we generate JPA annotations, we must be careful to respect the JPA version. The recent introduction of the `@Index` annotation that was generated with #6323 broke some assumptions by users who were restricting their generated code to use JPA 2.0 only (or less).

We need a new flag that allow for restricting the JPA version to be considered with `<jpaAnnotations/>`. If no such flags are specified, then the latest JPA version is assumed (just like the `SQLDialect` family / dialect duality).

The new flag is called `<jpaVersion>2.0</jpaVersion>`.

**Comment by timur-sh** [comment]
@lukaseder I'll pick it up.

**Comment by lukaseder** [comment]
Thanks again for your contribution! This is now in jOOQ 3.11
