### ISSUE TITLE
TableRecordImpl do not implement Record[N].component[1-N]() methods.

### ISSUE THREAD

**Issue by alexturc** [jOOQ/jOOQ#6795]
In JOOQ 3.10.1 TableRecordImpl does not implement newly added methods Record[N].component\[1-N\](), like AbstractRecord does, leading to compilation errors.

The was introduced by [#6245](https://github.com/jOOQ/jOOQ/issues/6245).

**Comment by lukaseder** [comment]
Thanks for your report. You have to re-generate your code with jOOQ 3.10.1 to run it with 3.10.1. Hope this helps
