### ISSUE TITLE
Improve DefaultRecordMapper::init MappingException message

### ISSUE THREAD

**Issue by stellingsimon** [jOOQ/jOOQ#6807]
`DefaultRecordMapper::init(E instance)` seems to reference `this` instead of `instance` in its `MappingException` thrown on line 342:

    throw new MappingException("No matching constructor found on type " + type + " for record " + this);

### Steps to reproduce the problem:

    DefaultRecordMapper mapper = ...;
    mapper.init(null);

### Expected behavior and actual behavior:

Expected:

`org.jooq.exception.MappingException: No matching constructor found on type class com.company.MyClass for record null`

Actual:

`org.jooq.exception.MappingException: No matching constructor found on type class com.company.MyClass for record org.jooq.impl.DefaultRecordMapper@46d8f407`

### Versions:

- jOOQ: 3.7.3
- Java: 1.8
- Database (include vendor): PostgreSQL

**Comment by lukaseder** [comment]
Thanks for your report. Indeed, it doesn't make sense to put `this` in the error message. But the `instance` reference probably isn't very useful either, most `RecordMapper` instances do not have an `instance` reference. The `rowType` reference might be the most useful additional information here.
