### ISSUE TITLE
JDBCUtils.dialect(Connection) should recognise database version

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6814]
Currently, `JDBCUtils.dialect(Connection)` simply returns the family, not the dialect, which includes the database version. In the `Connection` overload, it should be possible to derive the version from the JDBC driver information.

----
This could be considered a somewhat breaking change, as clients might have relied on the fact that the family is returned, not the dialect

**Comment by lukaseder** [comment]
Implemented the discussed changes. Thanks again for your contribution, @timur-sh !

**Comment by timur-sh** [comment]
Thank you for your product too!
