### ISSUE TITLE
[question] jOOQ open-source with Postgres on AWS/Azure

### ISSUE THREAD

**Issue by metacubed** [jOOQ/jOOQ#6821]
AWS and Azure both offer Postgres as a service:

- [Amazon RDS for PostgreSQL](https://aws.amazon.com/rds/postgresql/)
- [Azure Database for PostgreSQL](https://azure.microsoft.com/en-us/services/postgresql/)

Both these services host and provide standard "community" releases of PostgreSQL. Is the ASL-licensed version of jOOQ (open-source) allowed for use with these services?

**Comment by lukaseder** [comment]
Thank you very much for your question. The ASL 2.0 does not restrict any usage of the licensed material beyond what is permitted / forbidden / required by the ASL 2.0:
https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

So, there's no legal restriction for you to use the jOOQ Open Source Edition with the mentioned databases.

**Comment by metacubed** [comment]
Thanks for the quick response!
