### ISSUE TITLE
Add DSLContext.explain(Query)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6823]
This new API would run an `EXPLAIN` call for a query to estimate the query's cardinality and return that value to the user.

The API would take care of reverse engineering individual database's explain functionality to get to the cardinality estimate.

For a rationale, see this discussion here:
https://github.com/jOOQ/jOOQ/issues/3594#issuecomment-345691778

An initial implementation will include support for:

- [x] H2
- [x] MySQL
- [x] Oracle
- [x] PostgreSQL

**Comment by stangls** [comment]
thank you :smile_cat:
