### ISSUE TITLE
Error when passing java.util.Date to DSL.year(), month(), day(), hour(), minute(), second()

### ISSUE THREAD

**Issue by tomBP** [jOOQ/jOOQ#6825]
This seems to be the same error as https://github.com/jOOQ/jOOQ/issues/6333. If I pass a `java.util.Date` to `DSL.month()` I get the error:

> Type class java.util.Date is not supported in dialect DEFAULT

If I pass a java.sql.Date, it works as expected. I first encountered this in 3.7.4 but it also fails in 3.10.1. I'm using jOOQ with Spring Boot 1.5.8, MySQL 5.7 and Hikari 2.3.5.

**Comment by lukaseder** [comment]
Thank you very much for your report. Indeed, that is a similar issue as #6333 and it affects all the date parts from `year()` to `second()`. Will fix this ASAP.

**Comment by tomBP** [comment]
You're welcome! Thanks for the great library.

**Comment by lukaseder** [comment]
Thanks for the nice words :)
