### ISSUE TITLE
UPDATE ... RETURNING sequence value doesn't work

### ISSUE THREAD

**Issue by victorbr** [jOOQ/jOOQ#6826]
When using UPDATE ... RETURNING with an expression that is not a field of the updated table, the returning result set is incorrect. The specific case that doesn't work is returning `currval` of a sequence whose `nextval` is used in the UPDATE clause, like this:
```
Sequence<BigInteger> seq = DSL.sequence("myseq");
BigInteger result = sql.update(t).set(t.id, seq.nextval()).returning(seq.currval()).fetchOne().get(0, BigInteger.class);
```
The generated SQL is correct, the  ResultSet returned by the driver is correct as well, but JOOQ interprets it incorrectly - the `Record` returned by `fetchOne` is believed to have the fields of the table instead of the single bigint field and the values are all nulls. I believe the problem is in [these lines](https://github.com/jOOQ/jOOQ/blob/master/jOOQ/src/main/java/org/jooq/impl/AbstractDMLQuery.java#L683) of `AbstractDMLQuery#execute` method (
```
            // [#3682] Plain SQL tables do not have any fields
            if (table.fields().length > 0)
                returned = returned.into(table);
```
that basically override the correct `returned`.

### Versions:

- jOOQ: 3.10
- Java: 1.8
- Database (include vendor): Postgres
- JDBC Driver (include name if inofficial driver): Postgres 9.4-1201-jdbc41

**Comment by lukaseder** [comment]
Thank you very much for your report. Yes indeed, this is an unfortunate design error, which we'll hopefully fix soon:

- https://github.com/jOOQ/jOOQ/issues/5622
- https://github.com/jOOQ/jOOQ/issues/6715

**Comment by victorbr** [comment]
Thank you for immediate turnaround!
Would like to take this opportunity to thank you for this fantastic project! I've been using it for a couple of years now and totally in love with it!

**Comment by lukaseder** [comment]
Thanks for your nice words :)
