### ISSUE TITLE
DSL.cast generates wrong name in Postgres

### ISSUE THREAD

**Issue by ciaccia** [jOOQ/jOOQ#6840]
Consider the following SQL (note the second column is `text` despite containing an UUID):

```sql
CREATE table sre.jooq_cast
(
    id bigserial PRIMARY KEY,
    uuid text NOT NULL,
    name text
);

insert into sre.jooq_cast(id, uuid, name) VALUES
(NEXTVAL('sre.jooq_cast_id_seq'), uuid_generate_v4() , 'bar'),
(NEXTVAL('sre.jooq_cast_id_seq'), uuid_generate_v4() , 'foo');
```

The following code:

```java
Record3<Long, UUID, String>[] arr = dslCtx.select(JOOQ_CAST.ID, DSL.cast(JOOQ_CAST.UUID, UUID.class), JOOQ_CAST.NAME).from(JOOQ_CAST).fetchArray();
for (int i = 0; i < arr.length; i++) {
    Record3<Long, UUID, String> row = arr[i];
    System.out.println(row);
}
```

Prints something like:

    +----+------------------------------------+----+
    |  id|cast                                |name|
    +----+------------------------------------+----+
    |   1|fd9393ec-7f6b-4962-b1b4-713eab006210|bar |
    +----+------------------------------------+----+
    +----+------------------------------------+----+
    |  id|cast                                |name|
    +----+------------------------------------+----+
    |   2|c1e0afaf-1b0d-40ab-be1e-7a8184be554f|foo |
    +----+------------------------------------+----+

The second column is named `cast`, despite it should be `uuid` (i.e. casting a column does not change its name, at least in psql). This query works fine in the editor:

```sql
select t.uuid from (select c.id, cast(c.uuid as uuid), c.name from sre.jooq_cast c) as t;
```

The changed name of the second column prevents me from doing something like:

```java
Record3<Long, UUID, String>[] arr = dslCtx.select(JOOQ_CAST.ID, DSL.cast(JOOQ_CAST.UUID, UUID.class), JOOQ_CAST.NAME).from(JOOQ_CAST).fetchArray();
for (int i = 0; i < arr.length; i++) {
    Record3<Long, UUID, String> row = arr[i];
    UUID uuid = row.get(JOOQ_CAST.UUID, UUID.class);
}
```

The last line generates an exception:

    java.lang.IllegalArgumentException: Field ("sre"."jooq_cast"."uuid") is not contained in Row ("sre"."jooq_cast"."id", cast("sre"."jooq_cast"."uuid" as uuid), "sre"."jooq_cast"."name")

Ideally `DSL.cast` for a table column should preserve the original name.

**Comment by lukaseder** [comment]
Thanks for your report. But I don't agree with your assessment. A cast is an expression like any other. What would the name of a column be if you wrote:

```sql
CAST(first_name || ' ' || last_name)
```

It is not really defined, and jOOQ simply defaults to the function name in these cases. The databases all behave differently here, some behave like jOOQ, some don't assign names at all, and some strip the expression of whitespace and use that as a name - jOOQ just ignores the actual name produced by the database.

If you want your column to be called UUID, simply name it this way:

```java
DSL.cast(JOOQ_CAST.UUID, UUID.class).as("uuid")
```

Or: 

```java
DSL.cast(JOOQ_CAST.UUID, UUID.class).as(JOOQ_CAST.UUID)
```
