### ISSUE TITLE
SQLDataType.INTEGER.identity(true) not working for SQLLite

### ISSUE THREAD

**Issue by ianpurton** [jOOQ/jOOQ#6841]
### Expected behavior and actual behavior:
For the following DDL snippet 

        val ddl = sql.createTable("users")
                .column("id", SQLDataType.INTEGER.identity(true))

I would expect the following column to be generated

**id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL**

instead I get

**id int not null**

This then means SQLite diesn't generate an auto increment identity. If I do a search and replace and then execute the DDL I get the expected behaviour.

i.e. the easy fix is to generate the DDL to a string and then

    replace("id int not null", "id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL")

### Steps to reproduce the problem:
Create a SQLLite DSLContenxt and call createTable
### Versions:

- jOOQ: 3.10.1
- Java: 8
- Database (include vendor): SQLLite
- JDBC Driver (include name if inofficial driver): sqlite-jdbc-3.20.0.jar

**Comment by lukaseder** [comment]
Thanks for your feedback. Yes indeed, we hadn't implemented this yet. Will add support for this right away

**Comment by lukaseder** [comment]
Fixed for 3.11. This is a candidate for merging to 3.10.2 (#6844) - not sure about the merge complexity yet, though...
