### ISSUE TITLE
the maven plugin should support configure DataSource:)

### ISSUE THREAD

**Issue by hepin1989** [jOOQ/jOOQ#6851]
### Expected behavior and actual behavior:
Support configure datasource for code generation, currently it's only support jdbc in the xml config.
### Versions:

- jOOQ: 3.8.0
- Java: 1.8.0
- Database (include vendor): MySQL
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your feature request. But what does it mean to configure a data source for code generation? Can you please describe your use-case a bit more?

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/33172146-e3cc03fe-d089-11e7-89a0-bacff17140ac.png)

**Comment by lukaseder** [comment]
Oh, I see. But we already have that method. What's keeping you from using it?

**Comment by lukaseder** [comment]
Duplicate of #4891
