### ISSUE TITLE
SQLiteTableDefinition.toString() prints "." after empty schema - Merge [#6855]

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6859]

**Comment by timur-sh** [comment]
As I found `SQLiteTableDefinition.toString()` uses a method `AbstractDefinition@getQualifiedInputName`. Thus, this issue related to all implementation of `AbstractDefinition`. Right?

**Comment by lukaseder** [comment]
This issue is already resolve, please see the parent issue #6855 for details. This issue here is the "merge ticket" to merge the fix to version 3.9.7. Unfortunately, GitHub doesn't allow for specifying several milestones for an issue.
