### ISSUE TITLE
Code generator doesn't work in Java 6 build, which calls java.lang.reflect.Method.getParameterCount()

### ISSUE THREAD

**Issue by a-derevyanko** [jOOQ/jOOQ#6860]
### Expected behavior and actual behavior:
We use pro java 6 version of JOOQ
Generator uses java.lang.reflect.Method#getParameterCount in org.jooq.util.JavaGenerator which available only since Java 1.8.

Now jooq can`t generate classes under jdk 1.7

you could replace the Java8 specific

> m.getParameterCount()

with

> m.getParameterTypes().length

### Steps to reproduce the problem:
Run org.jooq.util.GenerationTool on JDK 1.7

### Versions:

- jOOQ: 3.1.10
- Java: 1.7
- Database (include vendor): Oracle
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report. I can confirm that JDK 8 API is used, erroneously. We'll look into why this slipped through our integration tests.

There will be a 3.10.2 release next week. This should definitely be part of it.

**Comment by lukaseder** [comment]
This is now fixed for jOOQ 3.11 on master. The regression was introduced in jOOQ 3.10.0 with https://github.com/jOOQ/jOOQ/commit/97b3c857d3fa57716f3ff534add30c288d5872c9. The fix will be backported to 3.10.2 with #6869

Thanks again for reporting this.
