### ISSUE TITLE
Cannot use ThreadLocalTransactionalCallable with TransactionProvider of type class org.jooq.impl.DefaultTransactionProvider

### ISSUE THREAD

**Issue by hepin1989** [jOOQ/jOOQ#6861]
### Steps to reproduce the problem:
I built the DefaultDSLContext directly from `DataSource`, but when I use dslContext.TransactionalResult(...),it give me this.

![image](https://user-images.githubusercontent.com/501740/33218492-1d28fb04-d178-11e7-93f3-84c1d770fff0.png)

### Versions:

- jOOQ: 3.10.1
- Java: 1.8
- Database (include vendor): Mysql
- JDBC Driver (include name if inofficial driver):

**Comment by hepin1989** [comment]
The exception there should at least give out an link to a FAQ web page.

**Comment by lukaseder** [comment]
Thanks for your report. Yes, this is a known issue: #6732. The current state is not something we'd like to document - instead we'd rather fix it ASAP.
