### ISSUE TITLE
fetchOne.Into(class) should not throw NPE when record is not found

### ISSUE THREAD

**Issue by hepin1989** [jOOQ/jOOQ#6863]
### Expected behavior and actual behavior:
return null 

### Steps to reproduce the problem:
![image](https://user-images.githubusercontent.com/501740/33249330-f4b63d96-d364-11e7-8a05-fa8f3a777f76.png)

I will go with fetchOptional.
### Versions:

- jOOQ: 3.10.1
- Java:1.0.8
- Database (include vendor):Mysql
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report.

`fetchOne()` returns `null` on record not found as indicated by its Javadoc. There is no way the NPE can be prevented in that call chain. However, there are `fetchOneInto()`, which works around this problem, or you can always call `fetchOptional()`

**Comment by hepin1989** [comment]
@lukaseder Thank your. I will go to `fetchOneInto` then.

**Comment by hepin1989** [comment]
BTW, why not a book for jooq?

**Comment by lukaseder** [comment]
> BTW, why not a book for jooq?

Thanks for the suggestion, I've thought about this in the past. It's a planning / priorities thing :)
