### ISSUE TITLE
add  VAVR types support ?

### ISSUE THREAD

**Issue by hepin1989** [jOOQ/jOOQ#6864]
### Expected behavior and actual behavior:

maybe add support for VAVR?

like `Optional<R> fetchOptional()` with `Option<R> fetchOption()` on Reacord.

### Versions:

- jOOQ: 3.10.1
- Java:1.8
- Database (include vendor):Mysql
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your suggestion.

jOOQ follows an almost zero-dependency strategy, see also: https://www.jooq.org/doc/latest/manual/getting-started/dependencies

While vavr is certainly a cool library, we would only do our users a disservice by depending on it. It is very easy to combine jOOQ with vavr in the client side if needed. Of course, we recommend using jOOλ instead :)
https://github.com/jOOQ/jOOL
