### ISSUE TITLE
DefaultRecordMapper should prefer calling public constructors over private ones

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6868]
Currently, the `DefaultRecordMapper` will find the first (arbitrary) matching constructor and call that one, if the number of arguments matches the number of mapped columns. E.g. when selecting:

```sql
SELECT first_name, last_name FROM person
```

And mapping that to:

```java
class Person {
  private Person(Object a, Object b) { .. }
  public Person(String firstName, String lastName) { .. }
}
```

Then, there's a slight chance of the private constructor being called instead of the public one.

----
This is a slight breaking change as some people might have relied on the existing behaviour, although we think that was wrong.

**Comment by eric239** [comment]
@lukaseder I'll pick this one up 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lukaseder** [comment]
Very cool, thank you very much, @eric239 !

**Comment by eric239** [comment]
@lukaseder simply sorting the constructors array to have public ones before non-public seems to be sufficient unless I'm missing something; the (trivial) PR's out

**Comment by lukaseder** [comment]
Very nice idea. We can expect the number of constructors on a POJO to be reasonably low, such that the sort operation won't hurt, at least it can be expected to be faster than two calls to the reflection API.

**Comment by lukaseder** [comment]
Thanks again very much for your contribution. This will now be part of jOOQ 3.11
