### ISSUE TITLE
Add Settings.mapMutablePojoStrategy

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6870]
The current implementation of the `DefaultRecordMapper` has several strategies blended into one:

- Mapping by JPA annotations
- Mapping by JavaBeans compliant setters / getters
- Mapping by "jOOQ style" setters / getters

Specifically the latter two can lead to strange edge cases as can be seen here:
https://groups.google.com/forum/#!topic/jooq-user/dVIniFSHzgs

Specifically, there may be a column `ID` whose JavaBeans compliant setter is `setId()`, whereas there may also be a column `SET_ID` whose "jOOQ style" setter is also `setId()`.

This new flag will allow for turning individual strategies on and off. The default being the status quo.

**Comment by timur-sh** [comment]
@lukaseder I pick it up. I found method `getMatchingGetter` acts like the `getMatchingSetters`. I suppose the similar issue can be appeared using the `getMatchingGetter`. What do you think?

If so, the `mapMutablePojoStrategy` flag must be used for this method too.

**Comment by lukaseder** [comment]
If this is implemented, it will be done as part of:

- https://github.com/jOOQ/jOOQ/issues/11974
