### ISSUE TITLE
Record.store and DSLContext.insertInto behave differently when optimistic locking is enabled.

### ISSUE THREAD

**Issue by billoneil** [jOOQ/jOOQ#6882]
### Expected behavior and actual behavior:
Using Record.store and DSLContext.insertInto should behave the same when inserting a record.

### Steps to reproduce the problem:

Using the following.

```java
        DataSourceConnectionProvider dcp = new DataSourceConnectionProvider(ds);
        Configuration jooqConfig = new DefaultConfiguration();
        jooqConfig.set(SQLDialect.MYSQL);
        jooqConfig.set(dcp);
        jooqConfig.set(new ThreadLocalTransactionProvider(dcp));
        jooqConfig.settings()
                  .withExecuteWithOptimisticLockingExcludeUnversioned(true);
```
Relevant section of codegen
```java
.withDatabase(new Database()
                    .withName(MySQLDatabase.class.getName())
                    .withIncludes(".*")
                    .withExcludes("password_hash")
                    .withIncludeExcludeColumns(true)
                    .withForcedTypes(forcedTypes)
                    .withRecordVersionFields("rec_version") // optimistic locking column
                    .withInputSchema("sj_access"))
```

Using Record.store will automatically populate `rec_version` to 1 and insert is successful
```java
        OrganizationRecord record = create
            .newRecord(Tables.ORGANIZATION)
            .setName(name)
            .setDateCreated(LocalDate.now())
            .setTsCreated(LocalDateTime.now())
            .setEnabled(true);
        record.insert();
```

```2017-12-01 08:13:55.543 [main] DEBUG org.jooq.tools.LoggerListener - -> with bind values      : insert into `sj_access`.`organization` (`name`, `enabled`, `date_created`, `ts_created`, `rec_version`) values ('test1111', true, {d '2017-12-01'}, {ts '2017-12-01 08:13:55.503'}, 1)```

Using DSLContext.insertInto does not populate the `rec_version` and throws an exception for the non null field.

```java
OrganizationRecord record = new OrganizationRecord()
                .setName(name)
                .setDateCreated(LocalDate.now())
                .setTsCreated(LocalDateTime.now())
                .setEnabled(true);
        record = create.insertInto(Tables.ORGANIZATION).set(record).returning().fetchOne();
```
```Exception in thread "main" org.jooq.exception.DataAccessException: SQL [insert into `sj_access`.`organization` (`name`, `enabled`, `date_created`, `ts_created`) values (?, ?, ?, ?)]; Field 'rec_version' doesn't have a default value```

### Versions:

- jOOQ: 3.10.1
- Java: 8
- Database (include vendor): MySQL
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for reporting this. I see what you mean. The optimistic locking feature thus far is a feature that only works with the `UpdatableRecord.store()` et al. methods, i.e. it is an "active record" feature. I'm not convinced that it should extend to any manual insert / update / delete statement. Even if it should, it wouldn't depend on you using `set(record)`, it would have to work for all statements made to a table that has a configured record version an/or timestamp column, e.g.

```java
create.insertInto(ORGANIZATION).defaultValues().execute();
```

We'd have to think through all possible edge cases to be sure that this really works well. Perhaps we can pull this off. But in any case, this must be governed by an additional `Setting` that can be opted into (or out of).

**Comment by billoneil** [comment]
I think you are right, I was a little short sighted thinking it would be easy to fix this for insert and didn't think about updates. I think it makes sense to leave this as an "active record" only feature because we wouldn't be able to just magically figure out the current version id on arbitrary updates without a hidden performance hit (plus that would be too much magic).

I think its fine to close this issue unless you think it's worth considering but I have been convinced otherwise. I'll stick with the active record mode when building my generic DAO class.
