### ISSUE TITLE
Add support for loading default values and comments for org.jooq.Meta columns

### ISSUE THREAD

**Issue by kingmagicoo** [jOOQ/jOOQ#6883]
### Expected behavior and actual behavior:
I tried to use DSLContext.meta() to fetch metadata. It fetches the COLUMN_NAME、 DATA_TYPE、TYPE_NAME、COLUMN_SIZE、BUFFER_LENGTH、DECIMAL_DIGITS、NUM_PREC_RADIX、NULLABLE correctly. However, it return empty comment and default value

```sql
CREATE TABLE `t_account_mark` (
`ACCOUNT`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '0' COMMENT 'fa' ,
`TYPE`  int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'my' ,
`VALUE`  int(10) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'mv' ,
`UPDATE_TIME`  datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'up' ,
PRIMARY KEY (`VALUE`, `ACCOUNT`)
)
```

```java
Connection connection = 
    	        DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/demo", "root","root");
    	DSLContext create = DSL.using(connection, SQLDialect.MYSQL);
    	
    	List<Table> table = create.meta().getTables().stream()
    			.filter(t -> t.getName().equals("t_account_mark"))
    			.collect(Collectors.toList());
    	
    	Stream.of(table.get(0).fields()).forEach(f -> {
    		System.out.println("name:" + f.getName());
    		System.out.println("comments:" + f.getComment());
    		DataType dataType = f.getDataType();
    		System.out.println("default value:" + dataType.defaultValue());
    	});
```

Output:

```
name:ACCOUNT
comments:
default value:null
name:TYPE
comments:
default value:null
name:VALUE
comments:
default value:null
name:UPDATE_TIME
comments:
default value:null
```

### Versions:

- jOOQ:3.9.1
- Java:1.8
- Database (include vendor):MYSQL
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report. Indeed, we should add support for these things, which are currently not loaded from the `org.jooq.Meta`'s underlying `DatabaseMetaData`. Not all databases / JDBC drivers support fetching defaults and comments, but MySQL does, so we should certainly fix this.

**Comment by lukaseder** [comment]
This won't be backported to 3.10 or older releases as there is always a slight risk of regressions when working with the `DatabaseMetaData` API, which is often poorly implemented by JDBC drivers.
