### ISSUE TITLE
Add support for PostgreSQL ON CONFLICT .. ON CONSTRAINT ..

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6906]
We already support `ON CONFLICT .. ` , but there's another possible clause that further specifies the `ON CONFLICT` clause:

> where conflict_target can be one of:
> 
>     ( ... )
>     ON CONSTRAINT *constraint_name*

----
See also:
https://www.postgresql.org/docs/current/static/sql-insert.html

**Comment by timur-sh** [comment]
@lukaseder I'd like to pick it up. I will add a new `onConflictOnConstraint(name)` method. Should the `name`' argument to be a new `Constraint` type, or the `Keyword` is appropriate for this ?

**Comment by lukaseder** [comment]
We already have a type for this. In fact, we have two types and both should be supported by overload:

- `org.jooq.Constraint` (this is used in DDL statements)
- `org.jooq.UniqueKey` (this is generated by the code generator)

In general, `Keyword` is almost always the wrong choice of type for things that are names or references. I mean, it corresponds to keywords like `SELECT` or `AS`, etc., not to names.

**Comment by lukaseder** [comment]
Thanks again for your contribution. This is now implemented for jOOQ 3.11

**Comment by lukaseder** [comment]
Added parser support as well: https://github.com/jOOQ/jOOQ/commit/fe34d9a84c26701763c0b2099445eb5a5d89fdd0
