### ISSUE TITLE
Generated create schema ddls using ddl() function error

### ISSUE THREAD

**Issue by zjh-coder** [jOOQ/jOOQ#6908]
### Expected behavior and actual behavior:
I'm using the method in this [article](https://www.jooq.org/doc/3.9/manual/sql-building/ddl-statements/generating-ddl/) to generate ddls for unit test environment initialized, it seems to have two issues.

1. generated ddl doesn't contain auto_increment statment。

2. foreign key reference error: if the table has a foreign key, it will reference all primary keys of another table no matter if another table has multiple primary keys.

### Versions:
- jOOQ: 3.9.5
- Java: 1.8
- Database (include vendor): mysql 5.7
- JDBC Driver (include name if inofficial driver): 5.1.31

**Comment by lukaseder** [comment]
Thank you very much for your report.

> generated ddl doesn't contain auto_increment statment。

This was fixed with #6221

> foreign key reference error: if the table has a foreign key, it will reference all primary keys of another table no matter if another table has multiple primary keys.

Would you mind providing a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) for this case?

Thanks

**Comment by zjh-coder** [comment]
Thank you very much for your response.
I'm using the following SQL create a table in MySQL.
```SQL
create table summarized_activity
(
	activity_id bigint not null primary key,
	location_id bigint null,
	
	constraint summarized_activity_string_resource_string_id_fk
		foreign key (location_id) references string_resource (string_id)
);
```
And string_resource table is created by this SQL.
```SQL
create table string_resource
(
	string_id bigint auto_increment,
	language_type varchar(64) not null,
	string_value varchar(128) null,
	create_time datetime default CURRENT_TIMESTAMP null,
	update_time datetime default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP,
	primary key (string_id, language_type)
);
```

But when I'm using JOOQ generate DDL of the summarized_activity table, I get SQL like this:
```SQL
create table summarized_activity
(
	activity_id bigint not null primary key,
	location_id bigint null,
	
	constraint summarized_activity_string_resource_string_id_fk
		foreign key (location_id) references string_resource (string_id, language_type)
);
```

**Comment by lukaseder** [comment]
Thank you very much for the additional info. Will look into this shortly.

**Comment by lukaseder** [comment]
Oh,  I see now. The `summarized_activity_string_resource_string_id_fk` is a single-column foreign key referenceing a non-key column in `string_resource`. That's crazy, why would MySQL even allow this? Consider the following program:

```sql
CREATE TABLE t_6908_a (
  id BIGINT AUTO_INCREMENT,
  xy BIGINT NOT NULL,
  
  CONSTRAINT pk_t_6908_a PRIMARY KEY (id, xy)
);

CREATE TABLE t_6908_b (
  id BIGINT NOT NULL,
  fk BIGINT     NULL,
  
  CONSTRAINT pk_t_6908_b PRIMARY KEY (id),
  CONSTRAINT fk_t_6908_b_t_6908_a FOREIGN KEY (fk) REFERENCES t_6908_a (id)
);

INSERT INTO t_6908_a (id, xy) VALUES (2, 2);
INSERT INTO t_6908_a (id, xy) VALUES (1, 2);
INSERT INTO t_6908_b (id, fk) VALUES (1, 1);
```

What does it mean now, for a record in `t_6908_b` to reference the value `1`?

Consider this query:

```sql
SELECT * 
FROM t_6908_a a JOIN t_6908_b b ON a.id = b.fk
WHERE b.id = 1;
```

It now returns two rows even if `b` only yields 1 row and we're moving from a foreign key to a (non-unique) "primary key". That violates every assumption we might make about foreign keys. Add to that the possibility of an `ON DELETE CASCADE` rule. Deleting any record in the parent table will delete the record in the child table.

We could fix this in the code generator of course. For this, we'd need:

- A synthetic "unique" key in the referenced table
- A way to recognise that the foreign key is not referencing any actual primary or unique key

But I'd really rather recommend you clean up your database design and avoid this funky MySQL flaw.

I've registered a bug at MySQL: https://bugs.mysql.com/bug.php?id=89014

**Comment by lukaseder** [comment]
One option would be this:

```sql
create table string_resource
(
	string_id bigint auto_increment,
	language_type varchar(64) not null,
	string_value varchar(128) null,
	create_time datetime default CURRENT_TIMESTAMP null,
	update_time datetime default CURRENT_TIMESTAMP null on update CURRENT_TIMESTAMP,
	primary key (string_id),
        unique (string_id, language_type)
);
```

**Comment by lukaseder** [comment]
We'll observe the progress on the MySQL bug to see if this is really a bug or a feature in MySQL

**Comment by zjh-coder** [comment]
Thank you so much for the explanation, I'll think about your advice and stay tuned for this issue

**Comment by lukaseder** [comment]
I'm happy to report that our integration tests for this schema here now fail in MySQL 9.3.0:

- https://github.com/jOOQ/jOOQ/issues/6908#issuecomment-353344685

This means that MySQL finally fixed this problem where they allowed for such bogus foreign keys to be created.
