### ISSUE TITLE
Avoid wrapping BufferedReader with new BufferedReader in loadCSV(Reader)

### ISSUE THREAD

**Issue by pvo-stroeer** [jOOQ/jOOQ#6909]
I have a situation where I need to use `DSLContext.loadInto()` to regularly import large CSV files (10M+ rows) into a DB table. The problem is that I have no influence on how the CSV file is formatted as I download it from a third-party API (CSV reports from Google DFP, to be explicit about it).

My DB table has one additional column, the `NETWORK_CODE`, which allows me to store CSV files from multiple networks in the same table. Unfortunately, that column is missing in the CSV file.

As I was unable to define a constant column value in my `DSLContext.loadInto()` call, I tried to use my own implementation of `BufferedReader` which overrides `void readLine()` and prepends each line with the constant network code string.

Unfortunately, jOOQ's `LoaderImpl` wraps each `Reader` in a new instance of `BufferedReader`. This prevents `LoaderImpl` to call my own implementation of `readLine()` and always uses the default implementation instead.

Wouldn't it make a lot of sense to only wrap `Reader`s, that are no instances of `BufferedReader`?

~~~ java
@Override
public final LoaderImpl<R> loadCSV(Reader reader) {
    content = CONTENT_CSV;
    if (reader instanceof BufferedReader) {
        data.reader = (BufferedReader) reader;
    } else {
        data.reader = new BufferedReader(reader);
    }
    return this;
}
~~~

Of course, `loadXML(Reader)` and `loadJSON(Reader)` would get equivalent changes.

I know my solution is some kind of pragmatic hack, but the change I supposed would also make sense in situations where you already have a `BufferedReader` and don't want jOOQ to create its own instance.

### Expected behavior and actual behavior:

I expect to be able to provide my own implementation of `java.io.BufferedReader` in a `DSLContext.loadInto(Table).loadCsv(Reader)` statement.

jOOQ wraps each `Reader` in a `BufferedReader` and effectively voids my own implementation.

### Steps to reproduce the problem:

Create a class that extends `BufferedReader`, override `void readLine()` and use that class in a `DSLContext.loadInto(Table).loadCsv(Reader)` statement.

### Versions:

- jOOQ: 3.6.9
- Java: jdk-8u151-windows-x64
- Database (include vendor): MySQL 5.7.22
- JDBC Driver (include name if inofficial driver): mysql:mysql-connector-java:5.1.44

**Comment by lukaseder** [comment]
Thanks for your suggestion.

However, we cannot accept a feature request that tries to change some of jOOQ's internals in order to inject ("hack") some behaviour into jOOQ's internals. The API accepts a `Reader` and you should not make any assumptions about the internals' usage of a `BufferedReader`. We may as well decide tomorrow, that we don't want to use a `BufferedReader` after all.

The approach you've tried to take is reasonable, except that you have to adhere to the `Reader` API only (which is a bit more low level)

**Comment by pvo-stroeer** [comment]
I fully understand. Do you have a suggestion, how I could find another workaround that doesn't rely on jOOQ internals?

**Comment by lukaseder** [comment]
Just refactor your attempted approach to inject additional content into `Reader` rather than `BufferedReader`. I.e. you could write a proxying `Reader` that just buffers individual lines obtained from its delegate reader and adds that additional column, and then sends that content out. Should be really simple. Just a bit more work than your original idea.

**Comment by pvo-stroeer** [comment]
Tedious but indeed doable. Thanks a lot.

**Comment by pvo-stroeer** [comment]
For the ones who are suffering from a similar problem:

I came up with my own implementation of `Reader` that delegates to a `PushbackReader`, which is capable of unreading characters from the `Reader`. That way I was able to prepend each line with a constant string.

**Comment by lukaseder** [comment]
Thanks for documenting. Would be cool to see an implementation in code, if you're interested in open sourcing it? You could paste it here in the issue, or on the user group: https://groups.google.com/d/forum/jooq-user

**Comment by pvo-stroeer** [comment]
Here's my implementation:

~~~ java
import static com.google.common.base.Preconditions.checkArgument;
import static com.google.common.base.Preconditions.checkNotNull;
import static java.lang.Math.max;
import static java.lang.Math.min;

import java.io.IOException;
import java.io.PushbackReader;
import java.io.Reader;

public class NetworkCodeAwareCsvReader extends Reader {

    private static final int END_OF_STREAM = -1;

    private static final int SEPARATOR_LENGTH = 1;
    private static final int MAX_LOOKAHEAD = 1;

    private final String networkCode;
    private final char csvSeparator;
    private final PushbackReader pushbackReader;

    public NetworkCodeAwareCsvReader(String networkCode, char csvSeparator, Reader reader) throws IOException {

        checkNotNull(networkCode, "Network Code is null");
        checkArgument(!networkCode.isEmpty(), "Network Code is empty");
        checkArgument(!containsCharacter(networkCode, csvSeparator), "Network Code contains CSV separator char");
        checkNotNull(reader, "Reader is null");

        this.csvSeparator = csvSeparator;
        this.networkCode = networkCode;
        final int pushbackBufferSize = networkCode.length() + SEPARATOR_LENGTH + MAX_LOOKAHEAD;
        this.pushbackReader = new PushbackReader(reader, pushbackBufferSize);
        pushbackNetworkCode();
    }

    private static boolean containsCharacter(String string, char character) {
        return string.indexOf(character) != -1;
    }

    @Override
    public int read(char[] cbuf, int off, int len) throws IOException {

        len = determineNumberOfCharactersToRead(cbuf, off, len);

        int character;
        int charactersRead = 0;

        for (int i = 0; i < len; i++) {

            character = pushbackReader.read();

            if (character == END_OF_STREAM) {
                break;
            }

            cbuf[off + i] = (char) character;
            charactersRead++;

            if (character == '\n') {
                handleNewLine();
            }
        }

        if (charactersRead == 0) {
            return END_OF_STREAM;
        } else {
            return charactersRead;
        }
    }

    private int determineNumberOfCharactersToRead(char[] cbuf, int off, int len) {
        return max(0, min(len, cbuf.length - off));
    }

    private void handleNewLine() throws IOException {
        final int nextCharacter = pushbackReader.read();
        if (nextCharacter != END_OF_STREAM) {
            pushbackReader.unread(nextCharacter);
            pushbackNetworkCode();
        }
    }

    private void pushbackNetworkCode() throws IOException {
        // push back first column (network code) in reverse order
        pushbackReader.unread(csvSeparator);
        pushbackString(networkCode);
    }

    private void pushbackString(String string) throws IOException {
        for (int i = string.length() - 1; i >= 0; i--) {
            pushbackReader.unread(string.charAt(i));
        }
    }

    @Override
    public void close() throws IOException {
        pushbackReader.close();
    }
}
~~~

Feel free to post a link to this issue on the jooq-user mailing list.

**Comment by lukaseder** [comment]
Very cool, thanks a lot for sharing!
