### ISSUE TITLE
Add support for WITH GRANT OPTION clause to GRANT statement

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6913]
This is a minor addition to #6812

**Comment by timur-sh** [comment]
I've completed my investigation what databases are support `WITH GRANT OPTIONS` clause. This is summarize in the list below:
1. **HSQLDB** http://hsqldb.org/doc/guide/accesscontrol-chapt.html 
2. **Firebird** https://firebirdsql.org/refdocs/langrefupd25-security-grant-revoke.html. This database supports `WITH {GRANT|ADMIN} OPTION`. For now we omit `ADMIN` clause, and will use rest of the clause `WITH GRANT OPTION`
3. **MySQL / MariaDB** https://dev.mysql.com/doc/refman/8.0/en/grant.html / https://mariadb.com/kb/en/library/grant/
4. **PostgreSQL** https://www.postgresql.org/docs/10/static/sql-grant.html 

Thus the [previous grammar form](https://github.com/jOOQ/jOOQ/issues/6812#issuecomment-346331783) will be extended to
```
grantStatement ::= GRANT <privilege> ON <table> TO { <user> | <role> } [ WITH GRANT OPTION ]
```

I plan to add a method `withGrantOption()`. 

Must be added a `GRANT_WITH_GRANT_OPTION` to `Clause` class?

**Comment by lukaseder** [comment]
Thank you very much for your investigation. Yes, indeed, it's a standard feature:

![image](https://user-images.githubusercontent.com/734593/34149406-3e0eb09e-e4a5-11e7-9672-b6874260f145.png)

It's also supported by:

- DB2: https://www.ibm.com/support/knowledgecenter/en/SSEPEK_11.0.0/sqlref/src/tpc/db2z_sql_granttableorviewprivileges.html
- Oracle: https://docs.oracle.com/database/121/SQLRF/statements_9014.htm#SQLRF01603
- SQL Server: https://docs.microsoft.com/en-us/sql/t-sql/statements/grant-transact-sql

And probably others.

Indeed, there should be a `withGrantOption()` method on a new optional DSL "step" type that extends (and replaces references to) `GrantFinalStep`

**Comment by lukaseder** [comment]
Note that for completeness' sake, we should also allow for revoking this option: #6931

**Comment by timur-sh** [comment]
I could not add support for DB2, Oracle and other dialects, because them are not open source.

**Comment by timur-sh** [comment]
Could you say, where can I get a SQL standard specification 2016?

**Comment by lukaseder** [comment]
Hey, no worries at all about the commercial dialects. I'll add those if necessary, or we can postpone things until later. I just wanted to document this here on the issue for completeness' sake.

The SQL standard specification documents can be obtained from ISO:
https://www.iso.org/standard/63556.html

It's not free, but worth the trouble if you're interested in looking into this document a bit more. You should always purchase the SQL/Foundation document. The others are for lesser known extensions to the foundation.

There are also some free late draft versions on the web, which may not be entirely complete or accurate but if you're not going to depend on the exact standard, they might be good enough:
https://stackoverflow.com/q/6000847/521799

**Comment by timur-sh** [comment]
Could I add a parser for it?

**Comment by lukaseder** [comment]
Yes, please, go ahead

**Comment by timur-sh** [comment]
Create please separate task for it

**Comment by lukaseder** [comment]
You can include it in this one here, putting #6913 in the commit message. The parser and parser grammar should always be adapted when the DSL API is changed. I just forgot about this, because the parser is still quite new and I tend to forget updating it myself...
