### ISSUE TITLE
Update was failed "ERROR: column 'test_schema'. of relation 'test_table' does not exist"

### ISSUE THREAD

**Issue by BohdanKorinnyi** [jOOQ/jOOQ#6915]
### Expected behavior and actual behavior:
I expect to get a updated row in database, but error occurs. `ERROR: column 'schemaname'. of relation 'tablename' does not exist`
### Steps to reproduce the problem:
```
dslContext.update(Tablename.TABLENAME)
                .set(Tablename.TABLENAME.CREATED_ON, value.getCreatedOn())
                .set(Tablename.TABLENAME.NOT_CREATED, value.getNotCreated())
                .set(Tablename.TABLENAME.FILTERED, value.getFiltered())
                .where(Tablename.TABLENAME.ID.eq(value.getId()))
                .execute();
```
Log with query:
```
2017-12-14 00:11:34.657 DEBUG 12816 --- [nio-8090-exec-6] org.jooq.tools.LoggerListener            : -> with bind values      : UPDATE "schemaname"."tablename" SET "schemaname"."tablename"."created_on" = 'value', "schemaname"."tablename"."not_created" = NULL, "schemaname"."tablename"."filtered" = NULL WHERE "schemaname"."tablename"."id" = 9
```
### Versions:

- jOOQ: 3.9.4
- Java: 1.8.0_151
- Database (include vendor): PostgreSQL 9.4.11 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver

**Comment by lukaseder** [comment]
Thanks for your report. Are you sure your `dslContext` is using the `SQLDialect.POSTGRES` to generate this SQL statement? jOOQ is well aware of the fact that columns in the `UPDATE .. SET` clause must not be qualified in PostgreSQL: https://github.com/jOOQ/jOOQ/blob/version-3.9.4/jOOQ/src/main/java/org/jooq/impl/FieldMapForUpdate.java#L83

But in your case, that check seems to fail.
