### ISSUE TITLE
Add support for REVOKE GRANT OPTION FOR

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6931]
This is a minor addition to #6812, the inverse operation of #6913 (`GRANT .. WITH GRANT OPTION`).

The feature will be implemented with `DSL[Context].revokeGrantOptionFor(...)` methods. There's no additional `Step` type needed in the DSL API.

**Comment by lukaseder** [comment]
So this would then also need parser support. If you want, you can also implement parser support in a single commit referencing both "[#6913] [#6931]" (funny how these two issues have almost the same issue number...)

**Comment by timur-sh** [comment]
Yes, I'll pick up this one too.
