### ISSUE TITLE
Multi-DB Codegen via Maven malfunctioning

### ISSUE THREAD

**Issue by kevinmarvin** [jOOQ/jOOQ#6942]
### Expected behavior and actual behavior:
Using the [linked](https://gist.github.com/kevinmarvin/948d89aad861b57c25ac9d84de9fdfbd) configuration information from pom.xml, I expect that JOOQ objects will be generated.  Presently, they give the [linked](https://gist.github.com/kevinmarvin/772e88396dd986674f53ce1ab5807860) error.

I need this to work so I can add an additional DB connection (for a vendor supplied PGSQL DB)

### Steps to reproduce the problem:

Put this in your pom, watch it make with the error.
Use Intellij idea to run the maven plugin.

or run it from the command line (mvn 3.5.0)

mvn org.jooq:jooq-codegen-maven:3.10.2:generate

### Versions:

- jOOQ: 3.10.2
- Java: 1.8.0
- Database (include vendor): Postgres 9.6
- JDBC Driver (include name if inofficial driver): org.postgresql.postgresql(42.1.4)

**Comment by lukaseder** [comment]
Thanks for your report. I don't see anything wrong in the configuration and can correctly use it from an ordinary build.

When invoking the plugin explicitly, please do see if this helps: https://stackoverflow.com/q/3779369/521799
