### ISSUE TITLE
Add <includeTriggerRoutines/> flag to exclude the generation of PostgreSQL trigger routines

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6951]
In PostgreSQL, triggers are ordinary functions that can be reused among tables. These functions return a `TRIGGER` type, which currently maps to `Object` in jOOQ and generates a deprecation because of #6212.

We should add a flag `<includeTriggerRoutines/>`, which turns off the generation of trigger routines in PostgreSQL. The default is `false` (exclusion), but users wishing to generate these objects can turn this back on again.

**Comment by etiennestuder** [comment]
+1 on removing them, I never had a reason/desire to refer to them from my Java code.

**Comment by etiennestuder** [comment]
Nice!
