### ISSUE TITLE
org.jooq.tools.StringUtils.toCamelCase() works weird

### ISSUE THREAD

**Issue by Noel-bk** [jOOQ/jOOQ#6957]
### Expected behavior and actual behavior:
Hello. I'm new to JOOQ.
I'm just wondering about this:

Table name: `FooBar`

Expected after gradle task `generateModelJooqSchemaSource`, generated class name is `FooBar`
But, actual generated class name is `Foobar`.

I found that this is because org.jooq.tools.StringUtils.toCamelCase() method.
Even if the table name is already PascalCase, it is changed to lowercase after the `toCamelCase()` call except for the first character.
I just wanted to remain my table name itself.
I checked that it works well in the case of `fooBar`, `foo_bar`, `Foo_Bar`, `Foo_bar` -> `FooBar`

Is it on purpose or am I missing something?
Or you would mind if I make a pull request?
Any opinion would be appreciated.
Thanks!!

### Steps to reproduce the problem:
run gradle task `generateModelJooqSchemaSource`
### Versions:

- jOOQ: 3.10.0
- Java: 1.8+
- Database (include vendor): MySql 5.6

**Comment by lukaseder** [comment]
Thank you very much for your report. This works as designed. If you want to override the default behaviour, you can specify your own generator strategy:

- Programmatic: https://www.jooq.org/doc/3.10/manual/code-generation/codegen-generatorstrategy
- Configurative: https://www.jooq.org/doc/3.10/manual/code-generation/codegen-matcherstrategy/

**Comment by Noel-bk** [comment]
@lukaseder 
Thank you for your support.
As you mentioned, I tried latter one: `Configurative`

This is my gradle code which defines matchers.
```
strategy {
    name = null
    matchers {
      tables {
        table {
            tableIdentifier {
                transform = 'PASCAL'
                expression = 'J_$0'
            }
            tableClass {
                transform = 'PASCAL'
                expression = 'J_$0'
            }
        }
      }
    }
}
```

But after gradle task `generateModelJooqSchemaSource`, generated class' name is still `JFoobar`.

Then I found the code in `org.jooq.util.MatcherStrategy`:
```
private final String transform(String string, MatcherTransformType transform) {
        if (transform == null)
            return string;

        switch (transform) {
            case AS_IS:
                return string;
            case LOWER:
                return string.toLowerCase();
            case UPPER:
                return string.toUpperCase();
            case CAMEL:
                return StringUtils.toCamelCaseLC(string);
            case PASCAL:
                return StringUtils.toCamelCase(string);

            default:
                throw new UnsupportedOperationException("Transform Type not supported : " + transform);
        }
}
```

Now I couldn't understand at all that you said `StringUtils.toCamelCase()` works as degisned.
I think in case PASCAL: it should be `FooBar`.
It seems not working..

Could you tell me more about it?
Thank you so much and Happy new year!!

**Comment by lukaseder** [comment]
Please use the `AS_IS` transformation. Both `CAMEL` and `PASCAL` transformations will remove underscores in the same way. The only difference is: `PASCAL` keeps the first letter in upper case (e.g. `ClassNames`) whereas `CAMEL` keeps the first letter in lower case (e.g. `methodNames`)

**Comment by dbrokaw** [comment]
Like the original poster, our database names are also already in Pascal case, and using matchers works for us for everything *except* the generated Java field members, where there's no way to use matchers to generate the Java members in the standard camelCase format you'd expect in a Java POJO, e.g. `relatedPersonId`:
- If we use `AS_IS`, they get generated as PascalCase since that's what our DB names are already in, e.g. `RelatedPersonId`.
- If we use `PASCAL`, they get all letters after the initial one lower-cased, e.g. `Relatedpersonid`.

If the main intent of the `StringUtils` methods is to remove `_` and ` ` characters and then have the name end up in Pascal or Camel, I'm not understanding why it would be useful or by design for them actually *lower-case* all letters after the initial one, if the name happened to already have appropriate casing -- e.g. the line
```
                result.append(word.substring(1).toLowerCase());
````
in StringUtils.toCamelCase().

Is there something I'm missing?

**Comment by lukaseder** [comment]
Thanks for your comments, @dbrokaw 

> It seems like that line could easily be removed to fix this issue

Unfortunately, no. The input String is mostly `SNAKE_CASE` with all upper case letters. They do have to be transformed to lower case.

A programmatic generator strategy is the only way forward here right now:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-generatorstrategy

**Comment by lukaseder** [comment]
Here's how this could be fixed more thoroughly for matcher strategies. We'll add additional `MatcherTransformType` values:

- `LOWER_FIRST_LETTER`
- `UPPER_FIRST_LETTER`

I think with this, it should be possible to achieve `relatedPersonId` properties in POJOs starting from `RelatedPersonId` column names. I've created a separate issue for this: #8360

**Comment by dbrokaw** [comment]
Thanks Lucas -- makes sense and the additional transform types should help.  Thanks for the quick turnaround!

**Comment by Noel-bk** [comment]
@lukaseder Thank you so much..!
