### ISSUE TITLE
Is there a password/encryption password on the MS Access file?

### ISSUE THREAD

**Issue by shivchadha** [jOOQ/jOOQ#6959]
I tried to use the "access-sakila.mdb" file in MS Access, but was prompted to enter a password. I entered my MS Access/365 password, to no avail. 

From my understanding, these file types can be encrypted/given passwords? Has anyone else experienced this and found a work-around?

**Comment by lukaseder** [comment]
Thanks for your message. Is this really related to jOOQ, though? If so, how?

**Comment by shivchadha** [comment]
Yes, it is related since I found the "access-sakila" file in that tree:
https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples/Sakila

Can you point me in the right direction, since I can't find anything about
a password in the readme
<https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples/Sakila/ms-access-sakila-db>
.

Best,
Shiv

**Comment by lukaseder** [comment]
Oh interesting, thanks for the pointer. I have actually never tried. I don't know the password, I'm afraid. I'll remove the port from the repository

**Comment by shivchadha** [comment]
Hm.... do you have any idea where I can get a similar database in a msb
format? I'm taking a SQL class and need that database in a MDB file format
to continue.

**Comment by lukaseder** [comment]
No idea, sorry. You could, of course, adapt the scripts for one of the other databases and load that in your own Access database

**Comment by shivchadha** [comment]
Thanks!


Still new to using Access and SQL - any recommendations on how to do that?

**Comment by lukaseder** [comment]
Trial and error :-)

**Comment by fortunewalla** [comment]
https://github.com/ivanceras/sakila/issues/4#issuecomment-2422184496
