### ISSUE TITLE
Password for MS Access MDB file Inquiry

### ISSUE THREAD

**Issue by shivchadha** [jOOQ/jOOQ#6960]
I tried to use the "access-sakila.mdb" file in MS Access, but was prompted to enter a password. I entered my MS Access/365 password, to no avail.

From my understanding, these file types can be encrypted/given passwords? Has anyone else experienced this and found a work-around?

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/6959

**Comment by fortunewalla** [comment]
https://github.com/ivanceras/sakila/issues/4#issuecomment-2422184496
