### ISSUE TITLE
Manual examples for code generation includes / excludes contain wrong regular expressions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6972]
The manual contains wrongly escaped regular expressions in the Java (programmatic) and Gradle examples

----
See also:
https://www.jooq.org/doc/3.9/manual/code-generation/codegen-advanced/codegen-config-includes-excludes/#comment-3687830297

**Comment by kalkrishnan** [comment]
@lukaseder How do I whitelist tables in JOOQ? If I am going against a large database and only want to generate a few tables in my project, how would I do that?
