### ISSUE TITLE
DDLDatabase and JPADatabase should use unique in-memory database name

### ISSUE THREAD

**Issue by victornoel** [jOOQ/jOOQ#6980]
### Expected behavior and actual behavior:

When using `DDLDatabase` configured in Maven code generator plugin and executed via Eclipse's M2E, it seems that the in-memory h2 database persist between runs (I suppose because the maven execution is done within the Eclipse's JVM or something like that). This makes jooq print failures about already existing tables.

`DDLDatabase` should thus ensure the in-memory db is empty before executing itself.

### Versions:

- jOOQ: 3.10.2

**Comment by lukaseder** [comment]
That's interesting, thanks for reporting! Will look into it right away.

**Comment by lukaseder** [comment]
I can reproduce this easily through:

```java
// Works
public static void main(String[] args) throws Exception {
    for (int i = 0; i < 2; i++) {
        Properties info = new Properties();
        info.put("user", "sa");
        info.put("password", "");
        try (Connection connection = new org.h2.Driver().connect("jdbc:h2:mem:jooq-meta-extensions", info)) {
            try (Statement s = connection.createStatement()) {
                s.executeUpdate("create table t(i int)");
            }
        }
    }
}

// Fails:
public static void main(String[] args) throws Exception {
    for (int i = 0; i < 2; i++) {
        Properties info = new Properties();
        info.put("user", "sa");
        info.put("password", "");
        Connection connection = new org.h2.Driver().connect("jdbc:h2:mem:jooq-meta-extensions", info);
        try (Statement s = connection.createStatement()) {
            s.executeUpdate("create table t(i int)");
        }
    }
}
```

The workaround will be to use a "random" suffix (e.g. timestamp) on the database name `jooq-meta-extensions`. A more thorough fix will be implemented in jOOQ 3.11: #6982

**Comment by lukaseder** [comment]
The suffix is also important if two code generation runs are run in parallel...

**Comment by lukaseder** [comment]
This is fixed for jOOQ 3.11 on master (patch available here: https://github.com/jOOQ/jOOQ/commit/a43ac7f19c720cbe509dd4e59399d29711513e08). And will be merged to 3.10.3 (#6983) and 3.9.7 (#6984).

You can already apply the above patch, or simply use the fixed `DDLDatabase` class from your own class path: https://github.com/jOOQ/jOOQ/blob/a43ac7f19c720cbe509dd4e59399d29711513e08/jOOQ-meta-extensions/src/main/java/org/jooq/util/ddl/DDLDatabase.java

**Comment by victornoel** [comment]
@lukaseder great reactivity :) thanks!

**Comment by jdimeo** [comment]
I just came here to log the same issue! thanks for the fast response. I was also able to workaround the issue using table regexes and schemata clauses to "slice" the tables I needed for each POM (I'm generating different parts of the DB to different artifacts in a multi-module Maven build).
