### ISSUE TITLE
DDLDatabase and JPADatabase should use unique in-memory database name - Merge [#6980]

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#6984]

**Comment by JanecekPetr** [comment]
Found this stale backmerge by accident when looking for a related DdlDatabase issue.

I guess it's no longer feasible to do this, so it should be closed?

**Comment by lukaseder** [comment]
We're currently not planning any 3.9.x releases anymore, but we might in the future, in case of which this would be backported, if feasible. So, no to closing.

Are you using jOOQ 3.9.6? Is upgrading to a newer version possible?

**Comment by JanecekPetr** [comment]
> but we might in the future

Aha, that clears it up.

> Are you using jOOQ 3.9.6?

No, we're on 3.11, experimenting with 3.12 (everything looks ok so far, but we'll wait for a couple more bugfix releases). As I said, I found this by accident and thought it was long forgotten.

Thanks for your reactivity!

**Comment by lukaseder** [comment]
OK. No, it wasn't forgotten. Github, unfortunately, doesn't allow for putting several milestones on an issue. Otherwise, we could track possible backports more easily. Instead, we create these merge tickets for things that we think might be worth backporting to a given release.

This is independent of whether we actually do publish that release. Chances are high that if a customer asks for a 3.9.6 release, because they cannot upgrade, that we might include a few additional ones of these issues.

But chances are also high that we're not going to publish 3.9.6 anymore, in case of which all of the issues in this milestone will be closed.

> (everything looks ok so far, but we'll wait for a couple more bugfix releases)

Looking forward to your additional reports! Greatly appreciated :-)
