### ISSUE TITLE
Confusing debug log output when fetchOptional or fetchOne throw TooManyRowsException

### ISSUE THREAD

**Issue by tkaiser** [jOOQ/jOOQ#7001]
### Expected behavior and actual behavior:
I run a query using Postgresql `SELECT DISTINCT ON ...` to get a single record back. I want to wrap this with `fetchOptional` to get either a record or none, if the table is empty.
This works for an empty table and a table with a single row, but once there is more than one row in the table I get the following exception when executing this DSL call:
```
dsl.select(TIMESTAMP, RAW, EXCLUDED, INVALID)
            .distinctOn(TIMESTAMP)
            .from(COMBINATION_RUN)
            .orderBy(TIMESTAMP.desc())
            .fetchOptional()
```

```
org.jooq.exception.TooManyRowsException: Cursor returned more than one result
	at org.jooq.impl.Tools.fetchOne(Tools.java:1499)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:520)
	at org.jooq.impl.AbstractResultQuery.fetchOptional(AbstractResultQuery.java:616)
	at org.jooq.impl.SelectImpl.fetchOptional(SelectImpl.java:2962)
```
### Steps to reproduce the problem:
Table definition
```
-- auto-generated definition
CREATE TABLE combination_run
(
  combination_run_id BIGSERIAL NOT NULL
    CONSTRAINT combination_run_pkey
    PRIMARY KEY,
  timestamp          TIMESTAMP NOT NULL,
  raw_count          INTEGER   NOT NULL,
  invalid_count      INTEGER   NOT NULL,
  exluded_count      INTEGER   NOT NULL
);
```
Existing data:
```
INSERT INTO public.combination_run (combination_run_id, timestamp, raw_count, invalid_count, exluded_count) VALUES (1, '2018-01-05 09:50:08.146000', 968, 0, 0);
INSERT INTO public.combination_run (combination_run_id, timestamp, raw_count, invalid_count, exluded_count) VALUES (2, '2018-01-05 09:55:00.600000', 5, 0, 0);
```

Output from jOOQ LoggerListener
```
Executing query          : select distinct on ("public"."combination_run"."timestamp") "public"."combination_run"."timestamp", "public"."combination_run"."raw_count", "public"."combination_run"."exluded_count", "public"."combination_run"."invalid_count" from "public"."combination_run" order by "public"."combination_run"."timestamp" desc
Query executed           : Total: 3.975ms
Fetched result           : +---------------------+---------+-------------+-------------+
                         : |timestamp            |raw_count|exluded_count|invalid_count|
                         : +---------------------+---------+-------------+-------------+
                         : |2018-01-05 09:55:00.6|        5|            0|            0|
                         : +---------------------+---------+-------------+-------------+
```

Then the exception is thrown. Notice there is apparently one row returned but still a `TooManyRowsException` is thrown.

This should be easy to workaround but still a bug IMO.
### Versions:

- jOOQ: 3.9.6
- Java: java version "1.8.0_91"
- Database (include vendor): Postgres 10.1
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:9.4-1200-jdbc41

**Comment by lukaseder** [comment]
The problem here is that the debug log output doesn't indicate the fact that there were more than one rows. Here's what you get when executing the query in any SQL client:

![image](https://user-images.githubusercontent.com/734593/34603286-9f3cc5b6-f203-11e7-8687-f20a7e1580b5.png)

I'll change the title accordingly

**Comment by tkaiser** [comment]
argh sorry that was sort of careless on my side. I didn't run the actual query manually because I copied/adapted it over from another project where I run straight SQL, it was actually always intended to be run with an additional `LIMIT 1` clause. Now I wonder how it ever worked on the other project... ;) Thanks for your help, this is very low priority obviously.

**Comment by lukaseder** [comment]
> I didn't run the actual query manually because ...

... because you trusted jOOQ so much! Which is good news :-)

> this is very low priority obviously.

But super easy to fix

**Comment by lukaseder** [comment]
Since this change slightly alters `ExecuteListener` behaviour in the event of an exception, I won't merge this to older releases.
