### ISSUE TITLE
Inside transactionAsync() method, Vertx.currentContext() gets nullified

### ISSUE THREAD

**Issue by rbhammar** [jOOQ/jOOQ#7010]
I am facing i issue with transactionAsync() method with Vertx JOOQ. There is a single Vertx context for whole application. Inside transactionAsync() method method, My Vertx.currentContext().owner() value is getting null.That means, my vertx context is getting nullified and out of this method, i lost vertx context.

### Steps to reproduce the problem:

```java
    public static void testTransaction() throws SQLException {
     //   Configuration configuration = TestDB.getConnectionConfig();

       Vertx vertx = Vertx.currentContext().owner();
        AuthorDao dao = new AuthorDao(configuration);
        dao.setVertx(vertx);
        dao.executeAsync(dslContext -> {
                    CompletionStage stage = dslContext.transactionAsync(
                            configuration -> {

                                Vertx v = Vertx.currentContext().owner();
                                System.out.println("Vertx : " + v);

                                Object result = DSL.using(configuration).insertInto(Tables.AUTHOR, Tables.AUTHOR.AUTHOR.ID, Tables.AUTHOR.AUTHOR.NAME)
                                        .values("0", "0").execute();

                                System.out.println("Inserted : " + result);

                                result = DSL.using(configuration).insertInto(Tables.AUTHOR, Tables.AUTHOR.AUTHOR.ID, Tables.AUTHOR.AUTHOR.NAME)
                                        .values("9", "9").execute();

                                System.out.println("Inserted : " + result);

                                result = DSL.using(configuration).update(Tables.AUTHOR).set(Tables.AUTHOR.NAME, "-1").where(Tables.AUTHOR.ID.eq("0")).execute();

                                System.out.println("updated : " + result);

                          // throwException();
                            });
                    stage.thenApply(t -> {
                        try {
                            printData();
                        } catch (Exception e) {}
                        return null;
                    });

                    return "SUCCESS";
                },///CLOVER:OFF
                handler -> {

                    if (handler.failed()) {
                        System.out.println("failed");
                    } else {
                        System.out.println("Passed");
                    }

                });
      //  printData();
    }
```

### Versions:

- jOOQ: 3.10.3
- Java: 1.8
- Database (include vendor): Postgresql - 42.1.4 
-vertx: 3.5.0
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
jOOQ's `xyzAsync()` methods are governed internally by the `org.jooq.ExecutorProvider` SPI, which defaults to `org.jooq.impl.DefaultExecutorProvider`, which again runs things on the `ForkJoinPool.commonPool()` as can be seen here:

```java
public class DefaultExecutor implements Executor {

    private static final Executor EXECUTOR         =
        /* [java-8] */
        ForkJoinPool.getCommonPoolParallelism() > 1
      ? ForkJoinPool.commonPool()
      : /* [/java-8] */
        new Executor() {
            @Override
            public void execute(Runnable command) {
                new Thread(command).start();
            }
        };

    @Override
    public final void execute(Runnable command) {
        EXECUTOR.execute(command);
    }
}
```

If you wish to implement different behaviour, I'm sure you can easily write the glue code to bind the jOOQ `xyzAsync()` API to Vertx.

On the other hand, perhaps you're going to be better off not using jOOQ's async API at all, but to let Vertx handle the entire asynchronicity and run only jOOQ statements inside of a Verticle.

I hope this helps

**Comment by rbhammar** [comment]
@lukaseder -- Thank you.
Use case is : To execute multiple queries in a single transaction ASYNCHRONOUSLY and dao's methods won't help here as I have to perform joins on multiple tables (dao's methos work on single table).
Without using jOOQ's xyzAsync() methods, will that be taken care by?
Ex:
 CompletionStage stage = getDLSContext().transaction(
                action -> {
                   Result r = DSL.using(action).select(select)
                            .from(from).orderBy(orderBy).fetch();

                    DSL.using(configuration).insertInto(Tables.AUTHOR, Tables.AUTHOR.AUTHOR.ID, Tables.AUTHOR.AUTHOR.NAME)
                            .values("0", "0").execute();

                   handler.handle(r);
                });

Will this work as expected as I am not using vertx context anywhere while executing queries.

Thanks,
Rajal

**Comment by lukaseder** [comment]
> and dao's methods won't help here as I have to perform joins on multiple tables (dao's methos work on single table)

Yes, then don't use DAOs. We do have a feature request to extend the async APIs to DAOs: #5916, but we're probably not going to implement it, as DAOs are going to be deprecated: #5984

> Without using jOOQ's xyzAsync() methods, will that be taken care by?

`execute()` methods are blocking on the same thread.

It seems that you really need to decide whether you want to use jOOQ's asynchronous APIs (and then use `executeAsync()`), or vertx (and then wrap each individual query in a verticle).
