### ISSUE TITLE
Implement a language-agnostic enum encoding

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7025]
The current `org.jooq.EnumType` helps identifying jOOQ-specific enums by adding information like:

- catalog
- schema
- type name
- literal (which may contain characters that `Enum.name()` cannot contain)

What's currently missing is a way to discover all the different `EnumType` instances without resorting to `java.lang.Enum` API, which has some disadvantages:

- ~It doesn't work in Scala (see #5758)~ (no longer an issue, see https://github.com/jOOQ/jOOQ/issues/10998)
- It doesn't allow for creating enums dynamically (e.g. in the parser, see #6485, #7017)
- It produces some edge cases with respect to enum literal names that conflict with Java reserved words or illegal characters (see #8555)

It should definitely be possible to create enums dynamically without relying on JDK internals, in case of which they'll automatically work in Scala as well.

**Comment by rsmckinney** [comment]
Here's another issue with generating the enum classes dynamically.  I'm using the jOOQ parser to generate types at compile-time as javac encounters sql table/query names; the generated enum type names do not resolve within the java compiler.  I can probably force this this to work, however perhaps a better approach would have the API provide means to register a service for custom generation of types?

**Comment by lukaseder** [comment]
> @rsmckinney perhaps a better approach would have the API provide means to register a service for custom generation of types?

What kinds of use cases would such a service fulfil, apart from providing more flexibility around enum types?

**Comment by lukaseder** [comment]
This is really a non-trivial problem. We need a type / `Class<? extends EnumType>` at runtime *per enum* for the DDL use case. Compiling it on the fly works, even if it is ugly. Addressing individual issues (e.g. #8555) separately might be easier by fixing this compiled enum.

**Comment by lukaseder** [comment]
Another good reason to prioritise this is the fact that ad-hoc compilation can be slow, e.g. here in our integration tests:

![image](https://user-images.githubusercontent.com/734593/74838972-c65af800-5324-11ea-9578-d4a388c79df0.png)

**Comment by lukaseder** [comment]
Postponing this for now as the Scala bullet has been "defused", see https://github.com/jOOQ/jOOQ/issues/10998

**Comment by lukaseder** [comment]
The requirements on this issue aren't too clear, and again, the problems originating from the Scala emulation of enums are gone in Scala 3, so I'm closing this as won't fix.
