### ISSUE TITLE
Does jOOQ support Java 9?

### ISSUE THREAD

**Issue by ooxi** [jOOQ/jOOQ#7047]
I tried upgrading my project to Java 9 but it now fails compiling with the following message

> A required class was missing while executing XXX:generate: javax/xml/bind/JAXB

After some digging it [was suggested](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j) to explicitly depend on JAXB. I also found issue #6610 which describes the same approach but was closed because it might cause other trouble.

Thus my question: does jOOQ currently support Java 9? I'm using 3.8.4 and of cause will update, if Java 9 is supported in a newer version.

**Comment by lukaseder** [comment]
As the issue mentions, jOOQ is not modularised yet (see #6486), but it does support Java 9, meaning we integration test on Java 9. Currently, as jOOQ isn't modularised, you could add `--add-modules java.se.ee` to your Maven `MODULE_OPTS`

See: https://github.com/jOOQ/jOOQ/issues/6477

These problems aren't specific to jOOQ. All libraries that aren't modules yet will face similar problems, and in fact, libraries that have a JAXB dependency have two times the trouble. While it is easy to have a dependency on the API, it's not so easy to configure Maven / Jigsaw to help users find the implementation. One solution might be to remove JAXB from jOOQ.

**Comment by ooxi** [comment]
Thanks for the fast reply!
