### ISSUE TITLE
Generated scala code contains deprecation warning for TableImpl

### ISSUE THREAD

**Issue by er1c** [jOOQ/jOOQ#7051]
### Expected behavior and actual behavior:

```
[error] C:\Users\Eric Peters\IdeaProjects\ta-catalog\orig\src\main\scala\ta\db\generated\tables\AdminCatalogPermission.scala:53:131: constructor TableImpl in class TableImpl is deprecated: see corresponding Javadoc for more information.
[error] class AdminCatalogPermission(alias : Name, aliased : Table[AdminCatalogPermissionRecord], parameters : Array[ Field[_] ]) extends TableImpl[AdminCatalogPermissionRecord](alias, Tecalliance.TECALLIANCE, aliased, parameters, "") {
[error]
```

I believe the `\"%s\"` in https://github.com/jOOQ/jOOQ/blob/eec46ca0835bb5e5f433ad76adc75ed31fabb0bc/jOOQ-codegen/src/main/java/org/jooq/util/JavaGenerator.java#L3636-L3637 simply needs to be updated to be `DSL.comment(\"%s\")`

I'll test this locally and create a PR if that fixes it.

### Steps to reproduce the problem:

Generate a scala output.

### Versions:

- jOOQ: 3.11.0-SNAPSHOT
- Java:
- Database (include vendor):
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Gee you're quick. That `DSL.comment()` feature was added last week and is still work in progress :)
