### ISSUE TITLE
condition cannot add();

### ISSUE THREAD

**Issue by lapDog** [jOOQ/jOOQ#7056]
### Steps to reproduce the problem:
![image](https://user-images.githubusercontent.com/11813246/34931654-c4f2a2f8-fa0a-11e7-98f7-dd578aeac4d0.png)
![image](https://user-images.githubusercontent.com/11813246/34931664-d426288a-fa0a-11e7-9c2e-70dd126123dc.png)
![image](https://user-images.githubusercontent.com/11813246/34931680-e3807fe2-fa0a-11e7-94fa-cb3a651f9b4f.png)

### Versions:

- jOOQ:3.10.3
- Java:1.8
- Database (include vendor):mysql5.5
- JDBC Driver (include name if inofficial driver):mysql-connector...

**Comment by lukaseder** [comment]
Thank you for your request. I'm afraid, I'm not sure what exactly you're reporting here, though. May I ask you to read these guidelines here: https://stackoverflow.com/help/mcve and follow up with clear steps to reproduce your problem?

**Comment by lapDog** [comment]
![image](https://user-images.githubusercontent.com/11813246/34932696-de52ee98-fa0e-11e7-8c1e-5efe9ebc85d1.png)
I solved it. = =

**Comment by lukaseder** [comment]
Oh, I'm sorry, I can see it now. Yes, the `Condition` API is immutable. Calling `condition.and(other)` does not modify the original condition, but returns the new one. Your solution is one option, the other would be:

```java
Condition result = trueCondition();
if (something)
    result = result.and(x);
if (somethingElse)
    result = result.and(y);
```

See also these sections of the manual:

- https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/dsl-and-non-dsl (the part about mutability)
- https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql

Hope this helps.
