### ISSUE TITLE
stop supporting oracle database?

### ISSUE THREAD

**Issue by YongkwonPark** [jOOQ/jOOQ#7060]
### Steps to reproduce the problem:

i tried to generate code in gradle.
code generation script was written as...

```
task('generateJooq') { doLast {
    def writer = new StringWriter()
    new MarkupBuilder(writer).configuration('xmlns': 'http://www.jooq.org/xsd/jooq-codegen-3.9.2.xsd') {
        jdbc() {
            driver('oracle.jdbc.OracleDriver')
            url('jdbc:oracle:thin:@dburl:ORCL')
            user("${user}")
            password("${password}")
        }
        generator() {
            database() {
                name('org.jooq.util.oracle.OracleDatabase')
                inputSchema('...')
                outputSchemaToDefault(true)
            }
            generate() {
            }
            target() {
                packageName('...')
                directory('...')
            }
        }
    }

    GenerationTool.generate(
        JAXB.unmarshal(new StringReader(writer.toString()), org.jooq.util.jaxb.Configuration.class)
    )
}}
```

code generation was not successful
exception called 'java.lang.ClassNotFoundException: org.jooq.util.oracle.OracleDatabase' occurred
'org.jooq.util.oracle.OracleDatabase' not in jooq-3.9.6.jar

but it is specified in the 3.9 version documentation.
https://www.jooq.org/doc/3.9/manual/code-generation/codegen-advanced/codegen-config-database/

what have i missed?

### Versions:

- jOOQ: 3.9.6
- Java: 1.8
- Database (include vendor): oracle 11
- JDBC Driver (include name if inofficial driver): ojdbc6-11

**Comment by YongkwonPark** [comment]
i confirmed it was commercial support.

**Comment by lukaseder** [comment]
Thank you very much for your request. I'm glad you've been able to resolve it. Let me know if you have any questions regarding our commercial distributions and / or Oracle database support.

**Comment by hamed701326** [comment]
so for using of oracle database support, should we buy commercial distributions?

**Comment by lukaseder** [comment]
Thank you very much for your message, @hamed701326.

Please refer to this page to see what jOOQ Edition supports which SQL dialect:
https://www.jooq.org/download/#databases

Oracle is supported by the jOOQ Professional Edition and jOOQ Enterprise Edition
