### ISSUE TITLE
Compilation error in generated DAOs when primary key is a composite type

### ISSUE THREAD

**Issue by stangls** [jOOQ/jOOQ#7068]
### Expected behavior and actual behavior:

Expected: The code-generator should generate valid Java code.

Actual behavior: The code-generator creates DAO-code which returns a record instead of a pojo, which does not compile.

### Steps to reproduce the problem:
1. create a small database:
```
create type complex as ( a INT, b int );
create table using_complex (
  id complex not null PRIMARY KEY
);
```
2. run codegenerator with DAOs & POJOs enabled.
3. try to compile generated class `UsingComplexDao`
the error looks something like this:
`protected ComplexRecord getId(de.id4i.app.jooq.tables.pojos.UsingComplex object) {
        return object.getId();
    }`

### Versions:

- jOOQ: 3.10.2
- Java: 1.8.0_151
- Database (include vendor): PostgreSQL 9.6
- JDBC Driver (include name if inofficial driver): official postgresql driver 9.4.1212.jre7

**Comment by stangls** [comment]
confirmed problem with current stable jooq 3.10.3 and codegen 3.10.3

**Comment by lukaseder** [comment]
Thank you very much for your report. I'll look into this soon.

**Comment by lukaseder** [comment]
I can reproduce this, thanks again for reporting. Very interesting. Clearly, the POJO type should be used as a primary key type in this particular case. Let's see if this can really be enforced, though.

**Comment by lukaseder** [comment]
Cool, it was very easy to fix. Will backport to 3.10.5 (#7110) and 3.9.7 (#7111)
