### ISSUE TITLE
Support PostgreSQL SMALLSERIAL and BIGSERIAL types in parser / DDLDatabase

### ISSUE THREAD

**Issue by JanecekPetr** [jOOQ/jOOQ#7074]
### Expected behavior and actual behavior:
I have a DDL script like this:
```
CREATE TABLE some_table (
    some_column BIGSERIAL PRIMARY KEY,
    some_column2 VARCHAR(100) NOT NULL UNIQUE
);
```
and am generating the jOOQ via the `DDLDatabase` from this script. The creation fails, I'm assuming the postgres-only `BIGSERIAL` type is the issue here. I'm also pretty sure you already know about this, but the plugin said to report this, so I am.

### Steps to reproduce the problem:
See DDL script above, run it through the code generation via DDLDatabase.

```
[INFO] --- jooq-codegen-maven:3.10.4:generate (default) @ my-project ---
[INFO] No <inputCatalog/> was provided. Generating ALL available catalogs instead.
[INFO] No <inputSchema/> was provided. Generating ALL available schemata instead.
[INFO] License parameters       
[INFO] ----------------------------------------------------------
[INFO]   Thank you for using jOOQ and jOOQ's code generator
[INFO]                          
[INFO] Database parameters      
[INFO] ----------------------------------------------------------
[INFO] Reading from file: src/main/resources/db/migration/schema.sql
[ERROR] An exception occurred while parsing script source : src/main/resources/db/migration/schema.sql. Please report this error to https://github.com/jOOQ/jOOQ/issues/new
org.jooq.impl.ParserException: C42000_NO_SUBCLASS: CREATE TABLE some_table (
    some_column BIGSERIAL PRIMARY KEY,
    some_column2 VARCHAR(100) NOT NULL UNIQUE
);
	at org.jooq.impl.ParserImpl$ParserContext.unexpectedToken(ParserImpl.java:6068)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:555)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:353)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:345)
	at org.jooq.util.ddl.DDLDatabase.create0(DDLDatabase.java:129)
	at org.jooq.util.AbstractDatabase.create(AbstractDatabase.java:237)
	at org.jooq.util.AbstractDatabase.create(AbstractDatabase.java:226)
	at org.jooq.util.AbstractDatabase.getDialect(AbstractDatabase.java:208)
	at org.jooq.util.AbstractGenerator.logDatabaseParameters(AbstractGenerator.java:131)
	at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:271)
	at org.jooq.util.GenerationTool.run(GenerationTool.java:642)
	at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)
	at org.jooq.util.maven.Plugin.execute(Plugin.java:192)
```

### Versions:

- jOOQ: 3.10.4
- Java: 8
- Database (include vendor): DDLDatabase (Data Geekery™ GmbH). DDL for Postgres.
- JDBC Driver (include name if inofficial driver): N/A

**Comment by lukaseder** [comment]
Thanks for your report. Bad timing, the 3.10.4 release just shipped today :-)

Indeed, we should support this type as well. In the meantime, you can use `SERIAL8` as a synonym.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.11.0. Will be merged to 3.10.5 (#7080)

**Comment by hoon720823** [comment]
also TIMESTAMPTZ(n) is not supported..

**Comment by lukaseder** [comment]
@hoon720823 Should work with 3.10.5: https://github.com/jOOQ/jOOQ/blob/version-3.10.5/jOOQ/src/main/java/org/jooq/impl/ParserImpl.java#L5646

If not, may I ask you to create a new issue with a reproducible example?

**Comment by hoon720823** [comment]
ok! i will test on it asap!

**Comment by hoon720823** [comment]
https://github.com/jOOQ/jOOQ/blob/version-3.10.5/jOOQ/src/main/java/org/jooq/impl/ParserImpl.java#L5646

at line 5636
                else if (parseKeywordIf(ctx, "SMALLSERIAL"))
                    return SQLDataType.SMALLINT.identity(true);
would be a better if like this:
                else if (parseKeywordIf(ctx, "SMALLSERIAL") ||
                         parseKeywordIf(ctx, "SERIAL2") )
                    return SQLDataType.SMALLINT.identity(true);

**Comment by lukaseder** [comment]
@hoon720823 Thanks a lot for the hint. That's an oversight indeed. `SERIAL4` and `SERIAL8` are already parsed as expected.
