### ISSUE TITLE
DDLDatabase not working with PostgresSQL database dump

### ISSUE THREAD

**Issue by nporteschaikin** [jOOQ/jOOQ#7084]
### Expected behavior and actual behavior:

When I attempt to generate classes with the `DDLDatabase` generator against a PostgreSQL schema definition generated with `pg_dump`, I receive the following error:

```
SEVERE: An exception occurred while parsing script source : src/main/resources/database.sql. Please report this error to https://github.com/jOOQ/jOOQ/issues/new
org.jooq.impl.ParserException: C42000_NO_SUBCLASS: sion 9.6.6
-- Dumped by pg_dump version 9.6.6

[*]SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_sessi
```

### Steps to reproduce the problem:

Import this (sanitized) SQL definition

```
--
-- PostgreSQL database dump
--

-- Dumped from database version 9.6.6
-- Dumped by pg_dump version 9.6.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: data; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA data;


ALTER SCHEMA data OWNER TO postgres;

SET search_path = data, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: foo; Type: TABLE; Schema: data; Owner: postgres
--

CREATE TABLE foo (
    id bigint NOT NULL,
    foo bigint NOT NULL,
    bar character varying NOT NULL,
);
```

### Versions:

- jOOQ: 3.10.4
- Java: 8
- Database (include vendor): PostgreSQL

**Comment by lukaseder** [comment]
Thank you very much for your detailed report.

We've already fixed parsing (and ignoring) `SET` commands in #6485. I think it's worth completely merging recent progress in the parser to the 3.10 branch, there are a lot of improvements.

I wonder if we should consider the `SET search_path` command, though. Perhaps in a separate issue.

Your issue raises an interesting concern: The pg_dump export. There are a few additional statements that we currently cannot parse, but we should (and ignore them):

```sql
COMMENT ON DATABASE <identifier> IS <comment>;
ALTER SCHEMA <identifier> OWNER TO <identifier>;
CREATE EXTENSION [ IF NOT EXISTS ] <identifier> [ WITH SCHEMA <identifier> ];
COMMENT ON EXTENSION <identifier> IS <comment>; 
CREATE DOMAIN <identifier> AS <type> CONSTRAINT <identifier> <check_constraint>;
ALTER DOMAIN <identifier> OWNER TO <identifier>;
CREATE TYPE <identifier> AS <type def>; -- In particular enum types may soon be supported by the DDLDatabase
ALTER TYPE <identifier> OWNER TO <identifier>; 
```

**Comment by lukaseder** [comment]
Some additional commands that may be emitted by pg_dump have been supported.

I guess in order to support unqualified object names in these scripts, we'll have to add formal support (and emulations) of the `SET search_path` command. I've created a separate feature request for this: #7087

**Comment by lukaseder** [comment]
I've noticed the `character varying` data type also cannot be parsed correctly. Created a separate issue for this: #7089

Notice, there is a remaining syntax error on your side in your example:

```sql
CREATE TABLE foo (
    id bigint NOT NULL,
    foo bigint NOT NULL,
    bar character varying NOT NULL, -- Excess comma here
);
```

**Comment by lukaseder** [comment]
Alright. The recent fixes made sure that your particular pg_dump export could be loaded by the `DDLDatabase`. If you want, you could try building 3.11.0-SNAPSHOT from GitHub master and run the import again.

I'll be very happy to fix any other issues / add other features that you may find / need.

**Comment by nporteschaikin** [comment]
Hi @lukaseder! Thanks for getting these fixes out so quickly. I started working with jOOQ recently 👍 

Any idea when `3.11.0` will be shipped? We're using Maven to manage dependencies; I can hold off until it's available there.

**Comment by lukaseder** [comment]
There's no release date for 3.11 yet (although it will be probably in late Q1 2018 / early Q2 2018). But I'm considering shipping all of #5955 and #6485 in 3.10.5, which could ship within the next 2-3 weeks.

**Comment by nporteschaikin** [comment]
Thanks @lukaseder! Really looking forward to these fixes being available.

**Comment by nporteschaikin** [comment]
Hey @lukaseder - any update on a release?

**Comment by lukaseder** [comment]
We're still on time for the 2-3 weeks deadline, right? :) Will release next week. You can use jOOQ 3.11-SNAPSHOT from GitHub master for that part, if you want...

**Comment by nporteschaikin** [comment]
Thank you, @lukaseder! Sorry to pry :)

**Comment by lukaseder** [comment]
No worries. Release date is Feb 15, promised

**Comment by nporteschaikin** [comment]
@lukaseder I saw your 3.10.5 commit 🎉  could you publish it to Maven?

**Comment by lukaseder** [comment]
What's missing? http://search.maven.org/#artifactdetails%7Corg.jooq%7Cjooq%7C3.10.5%7Cjar
