### ISSUE TITLE
nullable postgres array not settable in pojo

### ISSUE THREAD

**Issue by stangls** [jOOQ/jOOQ#7099]
### Expected behavior and actual behavior:
* expected: nullable array-field can be set to `null`
* actual: there is only one method: `setFieldname( Fieldtype... fieldName )` which can set an empty array, but not a null value.

### Steps to reproduce the problem:
* create a table with a nullable array:
```
create table t (
  id SERIAL,
  f INT [] NULL DEFAULT NULL
);
```
* insert data, to show that postgres supports this:
```
insert into t (f) values ('{1,2,3}');
insert into t (f) values ('{}');
insert into t (f) values (null);

select * from t;
```
* generate POJOs and DAOs via JOOQ.
* try to fetch data via JOOQ DAO ⇒ works
* try to create a new pojo with a null value for `f` ⇒ impossible!

### Versions:

- jOOQ: 3.10
- Java: 1.8
- Database (include vendor): postgres 9.6
- JDBC Driver (include name if inofficial driver): postgres official

**Comment by stangls** [comment]
possible easy solution:
add a method `setFieldname( Fieldtype[] fieldName )`

**Comment by lukaseder** [comment]
Thanks for your report. There are two options:

- You can turn off the generation of varargs using the `<varargSetters/>` flag inside of `<generate/>`
- The proper way to pass `null` to a varargs argument in Java is `setFieldname((Fieldtype[]) null)`

> possible easy solution

That won't work. Varargs are just syntax sugar for arrays. This won't compile:

```java
class X {
  void m(Object... o) {}
  void m(Object[] o) {}
}
```

**Comment by stangls** [comment]
Thanks for the hint using `varargSetters` :smile_cat:
