### ISSUE TITLE
Add support for START TRANSACTION, COMMIT, ROLLBACK, SAVEPOINT statements

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7106]
Unlike the JDBC counterparts, we should model these statements as actual statements, such that they can be used in generated SQL, including anonymous blocks and/or batches, as well as in the parser. The latter is particularly important, as we'll need to support these statements in the `DDLDatabase`

Standard SQL statements to support:

- [x] `START TRANSACTION`
  - [x] When running this statement as a standalone query, we must switch the JDBC driver's auto commit mode in some dialects. This includes:
    - [x] Db2
    - [x] Exasol
    - [x] Firebird
    - [x] HANA
    - [x] HSQLDB
    - [x] Oracle
    - [x] SQL Server
- [x] `SAVEPOINT <name>`
- [x] `RELEASE SAVEPOINT <name>`
- [x] `COMMIT`
- [x] `ROLLBACK` [ `TO SAVEPOINT <name>` ]

Support will be added to:

- [x] `DSL` API
- [x] `QOM` API
- [x] Parser

For dialects (all the dialects supporting procedural code):

- [x] Db2
  - [x] There doesn't seem to be a `START TRANSACTION` command?
- [x] EXASOL
  - [x] There doesn't seem to be a `START TRANSACTION` command? We'll just execute `COMMIT` on the top level for now
- [x] H2
- [x] HANA
- [x] HSQLDB
  - [x] Blocks cannot manage their transactions (they're always `BEGIN ATOMIC`)
  - [x] Top level `START TRANSACTION` statements have to set the JDBC auto commit mode to `true`
- [x] Informix
- [x] MariaDB
- [x] MySQL
- [x] Oracle
  - [x] Top level `START TRANSACTION` statements have to set the JDBC auto commit mode to `true`
- [x] PostgreSQL
  - [x] Blocks are already transactional, they cannot start new transactions, i.e. `START TRANSACTION` must be rendered only outside of blocks (which is currently not possible, I think?).
  - [x] `SAVEPOINT` support isn't available within blocks, only as standalone statements
- [x] SQL Server
  - [x] Top level `START TRANSACTION` statements have to set the JDBC auto commit mode to `true`
- [x] YugabyteDB

But also for these dialects, outside of supporting procedural code

- [x] CockroachDB (procedural code will be supported soon)
- [x] MemSQL
- [x] SQLite
- [x] Teradata
  - [x] `SAVEPOINT` are not supported
  - [x] `ROLLBACK` raises an error
- More dialects here: https://github.com/jOOQ/jOOQ/issues/14456

These ones don't work:

- [x] BigQuery (we don't really support transactions yet)
- [x] Firebird
  - [x] Blocks cannot manage their transactions
  - [x] Top level transaction statements mess up the wire protocol. I don't have the nerve to debug this

More work:

- [x] Documentation

**Comment by remal** [comment]
Are there any news on the issue?

**Comment by lukaseder** [comment]
@remal Thank you very much for your message. Would you mind sharing a bit of insight into your use case? Understanding why this would add value to your work would help us better prioritise this feature request.

**Comment by remal** [comment]
When I discovered the issue, I thought that JOOQ doesn't support savepoints. But now I've done some search and found that savepoints **are** supported. If I'm right, my question above doesn't make sense...

**Comment by lukaseder** [comment]
This issue is about supporting the SQL `SAVEPOINT` statement as supported by various RDBMS. This is especially useful when using jOOQ's new procedural API.

You can access the JDBC API easily through jOOQ, or directly, if you want to create explicit savepoints. If you're not using jOOQ's transaction API, then jOOQ doesn't care about your transactions. If you do use jOOQ's transaction API, savepoints are implicitly supported by nesting transactions.

**Comment by remal** [comment]
To recap...
# Savepoints are supported through JDBC API or jOOQ's transaction API
# Currently savepoints are not supported in JOOQ's procedural API

Am I right?

**Comment by lukaseder** [comment]
Right

**Comment by lukaseder** [comment]
Moving this to all editions from the commercial editions only, as the statements can also be used as standalone queries, not just as procedural statements.

**Comment by lukaseder** [comment]
This is a great opportunity to review implementing readonly transactions as well as transaction isolation levels: https://github.com/jOOQ/jOOQ/issues/4836

Both via the transaction API and via this new DSL/QOM API

**Comment by lukaseder** [comment]
This has now been implemented for most dialects. A few remaining dialects (which don't have procedural support yet) are listed here: https://github.com/jOOQ/jOOQ/issues/14456
