### ISSUE TITLE
AbstractQuery.execute() doesn't wrap exceptions into DataAccessException as mentioned in docs

### ISSUE THREAD

**Issue by natashaml** [jOOQ/jOOQ#7108]
Hi,
Interface Query.execute() throws DataAccessException, but I have problem with AbstractQuery.execute(), because method doesn't wrap this exception.

**Comment by lukaseder** [comment]
Thank you very much for your report. May I please ask you to provide a bit more information? Right now, I'm not really sure what you're reporting here. Here are some useful guidelines on how to create a minimal, complete, verifiable example:
https://stackoverflow.com/help/mcve
