### ISSUE TITLE
Support WITH clause for H2

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7112]
H2 1.4.196 now supports `WITH` for `SELECT`: https://github.com/h2database/h2database/issues/479, https://github.com/h2database/h2database/issues/480

We can now adapt our documentation and add the relevant `@Support` annotations

**Comment by anshum17** [comment]
```
Caused by: org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement WITH LPM AS[*] (SELECT * FROM RDS_ADMINISTRATION.WARMPOOL_CONFIG ) SELECT * FROM LPM ; expected (; SQL statement:
with lpm as (select * from rds_administration.warmpool_config ) select * from lpm [42001-79]
```
I am getting this error with H2Database (1.4.196).

```SQL = "with lpm as (select * from rds_administration.warmpool_config ) select * from lpm"```
