### ISSUE TITLE
jOOQ generator generates wrong setter for Postgres bytea

### ISSUE THREAD

**Issue by ciaccia** [jOOQ/jOOQ#7113]
Consider the following Postgres (9.4) table:

    create table jooq_bug
    (
       id bigserial primary key NOT NULL,
       val bytea not null
    );

When I generate the corresponding class using jOOQ 3.9.0 (and newer), the class looks something like:

    public class JooqBugRecord extends UpdatableRecordImpl<JooqBugRecord> implements Record2<Long, byte[]> {
        
        public void setVal(byte... value) {
            set(1, value);
        }

With jOOQ 3.8.9 (and older), the `setVal` method looked like:

    public void setVal(byte[] value) {
        set(1, value);
    }

Starting with version 3.9.0, jOOQ replaced the `byte[]` parameter with `byte...` which despite being similar creates issues with `@Override` annotation.

Is this a desired change or something wrong? I have to manually modify the generated source code to compile my project which is not really nice...

Thanks a lot

**Comment by lukaseder** [comment]
This probably helps: https://github.com/jOOQ/jOOQ/issues/5733

You can turn off this feature by using `<varargsSetters/>` in the code generation configuration.

**Comment by ciaccia** [comment]
Hi Lukas, thanks a lot for your answer.

Just just for the sake of completeness, how do you handle the java warning on the generated class saying `Varargs methods should only override or be overridden by other varargs methods unlike JooqBugRecord.value1(byte...) and Record2<Long,byte[]>.value1(byte[])`?

**Comment by lukaseder** [comment]
@ciaccia : You unfortunately can't suppress this particular warning with javac.
