### ISSUE TITLE
jOOQ does not allow to define a custom type so that it can be used in an array of such type

### ISSUE THREAD

**Issue by desiderantes** [jOOQ/jOOQ#7124]
### Expected behavior and actual behavior:
By defining a custom type for, let's say UUID in Postgres to `java.util.UUID`, I expect that a field with and array of UUID wil result in a  `java.util.UUID[]` type. Instead, it's completely ignored in the code generation.

### Versions:

- jOOQ: 3.10
- Java: 8
- Database (include vendor): PostgreSQL
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your report. Would you mind filling out that "steps to reproduce the problem" section? There's a lot of subtlety lost in translation when you simply describe the problem in text...

**Comment by lukaseder** [comment]
I'll close this for now. Feel free to provide additional details and I will be very happy to look into it.
