### ISSUE TITLE
Problem using pojoExtends

### ISSUE THREAD

**Issue by f-renout** [jOOQ/jOOQ#7137]
### Expected behavior and actual behavior:
I try to use pojoExtends in order to archieve a limited level of inheritance.
I have 2 tables User and Group which have both 2 attributes in common : id and name
I try to declare pojoExtends property on Matcher strategy for tables User and Group but generated pojos duplicate field already declared in the inherited class
### Steps to reproduce the problem:
Create a class SubjectEntity (cf section CLASS)
Then create 2 tables (cf section DATABASE below)
Then lauch the generation using jooq configuration provided : here a gradle script (cf section SCRIPT below)
The POJOS User and Group extends SubjectEntity but redefine id and name
I was expecting that field declared in the inherited class will not be redefined

```java
public class SubjectEntity {

    private SubjectType subjectType;
    private UUID id;

    public SubjectType getSubjectType() {
        return subjectType;
    }

    public void setSubjectType(SubjectType subjectType) {
        this.subjectType = subjectType;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }
}
```

```sql
CREATE TABLE
    GROUP
    (
        subject_type TEXT NOT NULL,
        name TEXT NOT NULL,
        email TEXT,
        is_operator BOOLEAN NOT NULL,
        is_dispatcher BOOLEAN NOT NULL,
        is_supervisor BOOLEAN NOT NULL,
        id UUID NOT NULL,
        supergroup UUID,
        PRIMARY KEY (id),
    );

CREATE TABLE
    USER
    (
        subject_type TEXT NOT NULL,
        login TEXT NOT NULL,
        first_name TEXT NOT NULL,
        last_name TEXT NOT NULL,
        email TEXT,
        phone_number TEXT,
        id UUID NOT NULL,
        PRIMARY KEY (id),
        UNIQUE (login)
    );
```

```groovy
import groovy.xml.MarkupBuilder
import javax.xml.bind.JAXB

apply plugin: 'java'

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    compile 'org.jooq:jooq:3.10.4'
    runtime 'org.postgresql:postgresql:42.1.1'
}

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        classpath 'org.jooq:jooq-codegen:3.10.4'
        classpath 'org.postgresql:postgresql:42.1.1'
    }
}
def writer = new StringWriter()
def xml = new MarkupBuilder(writer)
        .configuration('xmlns': 'http://www.jooq.org/xsd/jooq-codegen-3.10.0.xsd') {
    jdbc() {
        driver('org.postgresql.Driver')
        url('jdbc:postgresql://localhost:5432/database')
        user('the_user')
        password('the_password
    }
    generator() {
        database() {
            name 'org.jooq.util.postgres.PostgresDatabase'
            inputSchema 'public'
        }
        strategy{
            matchers {
                tables{
                    table{
                        expression 'User'
                        pojoExtends 'com.manuloc.helpdesk.data.entities.SubjectEntity'
                    }
                    table{
                        expression 'Group'
                        pojoExtends 'com.manuloc.helpdesk.data.entities.SubjectEntity'
                    }
                }

            }
        }
        generate() {
            daos true
            validationAnnotations false
            javaTimeTypes true
        }
        target() {
            packageName('com.manuloc.helpdesk.data.jooq.gen')
        }
    }
}
org.jooq.util.GenerationTool.generate(
        JAXB.unmarshal(new StringReader(writer.toString()), org.jooq.util.jaxb.Configuration.class)
)
```

### Versions:

- jOOQ: 3.10.4
- Java: 1.8.0_161-b12
- Database (include vendor): Postgresql
- JDBC Driver (include name if inofficial driver): 42.1.1

**Comment by lukaseder** [comment]
Thank you for your detailed feature request.

However, I'm not sure if your expectations here make sense, at least not on the current feature level that we're offering. The code generator cannot "guess" what your intention is when you have attributes present in a super class that you're adding to generated code.

Of course, you could achieve this by implementing your own code generation logic in a subclass of the `JavaGenerator`, overriding the relevant methods that generate the POJOs. Currently, you'd have to override the entire POJO generation. In future versions, we'll allow overriding on a more fine-grained level, e.g. on a per-attribute and per-getter / setter basis.

Then again, what are you gaining from this subtype polymorphism of state? Wouldn't an interface of this type be sufficient?

```java
public interface SubjectEntity {
    SubjectType getSubjectType();
    void setSubjectType(SubjectType subjectType);
    UUID getId();
    setId(UUID id);
}
```
