### ISSUE TITLE
how to give a temp column default value

### ISSUE THREAD

**Issue by Paul0523** [jOOQ/jOOQ#7142]
Assuming table have only 'name' column，how to achieve this sql，eg： select 0 c1, 'success' c2, t.name from test t;

**Comment by lukaseder** [comment]
Thanks for your question. You can use bind values or literals for this:
https://www.jooq.org/doc/latest/manual/sql-building/bind-values

Specifically, write:

```java
// Assuming you're using the code generator:
Test t = TEST.as("t");

DSL.using(configuration)
   .select(
       val(0).as("c1"),
       val("success").as("c2"),
       t.NAME)
   .from(t)
   .fetch();
```

**Comment by Paul0523** [comment]
@lukaseder Thank you.
