### ISSUE TITLE
Provide little helper for join always

### ISSUE THREAD

**Issue by neonailol** [jOOQ/jOOQ#7144]
Sometimes i want to join tables no matter what and right now syntax for this is like `.leftJoin(someSubSelect()).on(trueCondition())`, i would like it to be more declarative, like for example `.leftJoin(someSubSelect()).always()`. I am aware that writing `.leftJoin(someSubSelect()).on()` will do the same for me, but it not so much obvious.

**Comment by lukaseder** [comment]
Thanks for your suggestion.

I'm not convinced that we should add such a method. We'd have to add it everywhere a `Condition` is acceptable for consistency reasons. And then, someone will want a `never()` method, and potentially some other "convenient" methods that keep you from writing something as simple as `on(trueCondition())`.

If `trueCondition()` is too tedious for you to write, you can "alias" it:

```java
public static final Condition ALWAYS = DSL.trueCondition();
```

And then

```java
.leftJoin(someSubSelect()).on(ALWAYS)
```
