### ISSUE TITLE
Change DSL.unnest(List) and table(List) to unnest(Collection) and table(Collection)

### ISSUE THREAD

**Issue by dwilches** [jOOQ/jOOQ#7166]
### Expected behavior and actual behavior:
The `unnest` method is declared as:

    public static Table<?> unnest(List<?> list) {
        return unnest(list.toArray());
    }

Which means we can't use it with a `Set`:

    Set<UUID> mySet = new HashSet<>();
    Table<?> t = unnest(mySet);

The `unnest` method could be declared instead as:

    public static Table<?> unnest(Collection<?> list) {
        return unnest(list.toArray());
    }

so we can use any collection (the `toArray` method actually belongs to `Collection`).

### Steps to reproduce the problem:

    Set<UUID> mySet = new HashSet<>();
    Table<?> t = unnest(mySet);

### Versions:

- jOOQ: 3.10.2
- Java: 1.8.0
- Database (include vendor): PostgreSQL 9.5
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for the suggestion. Indeed, there's no reason to not accept collections in this particular API. A simple workaround would be to proxy your set with the `List` type, delegating the `toArray()` call to your set.
