### ISSUE TITLE
Errors should also roll back a transaction

### ISSUE THREAD

**Issue by amc6** [jOOQ/jOOQ#7167]
### Expected behavior and actual behavior:
Expected all `Throwable`s to safely close a transaction, but only non-`Error` `Throwable`s do. It looks like this is the intended behavior based on https://github.com/jOOQ/jOOQ/issues/6608 but was surprising to me. 

To be fair, the `Error` documentation says that `An Error ...indicates serious problems that a reasonable application should not try to catch.` And based on that description alone, jooq does seem to be doing the right thing. Unfortunately junit uses `AssertionError` to indicate test failures. This causes the transaction to not be closed properly at the end of the test, and can interfere with subsequent tests. Given that junit is such a common library it might be worthwhile to handle Errors like normal exceptions.

If there are worries about masking the underlying `Error` when attempting to close the transaction, that code could be special-cased to guarantee that the original `Error` is always rethrown even when an exception occurs while closing the transaction.

### Steps to reproduce the problem:
Throw an `Error` (not an `Exception`) inside a transaction block and note that the transaction is not closed.

### Versions:
- jOOQ: 3.10.1

**Comment by lukaseder** [comment]
Thanks for the suggestion. Indeed, we probably shouldn't deal with errors differently from exceptions and other throwables (apart from rethrowing the error rather than wrapping it). I think that #6608 took inspiration from some spring version, but the latest spring versions also do not handle errors any different...

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.11. This will not be backported to earlier minor releases as it constitutes a subtle change of behaviour, which might be surprising when upgrading to the next patch release.
