### ISSUE TITLE
insertInto().select().returning() returns nothing

### ISSUE THREAD

**Issue by dustContributor** [jOOQ/jOOQ#7204]
### Expected behavior and actual behavior:

insertInto with a returning statement should be returning the row(s) that was(were) inserted. 

### Steps to reproduce the problem:

A concrete example would be this:
```java
db.insertInto( ORDER_DETAIL,
  ORDER_DETAIL.ID_ORDER,
  ORDER_DETAIL.ID_COMPONENT,
  ORDER_DETAIL.QUANTITY,
  ORDER_DETAIL.TOTAL_PRICE )
  .select(
    db.select(
      DSL.inline( UInteger.valueOf( model.orderId ) ),
      COMPONENT.ID,
      DSL.inline( UInteger.valueOf( model.quantity ) ),
      COMPONENT.PRICE.mul( Long.valueOf( model.quantity ) ) )
      .from( COMPONENT )
      .where( COMPONENT.ID.eq( componentId ) ) )
  .returning( ORDER_DETAIL.fields() )
  .fetch()
```
That inserts a new ORDER_DETAIL just fine, but it returns an empty Result<OrderDetailRecord>. 

ORDER_DETAIL table consists of a compound key between ID_ORDER and ID_COMPONENT, plus the columns QUANITY and TOTAL_PRICE.

### Versions:

- jOOQ: 3.10.2
- Java: 8u111
- Database (include vendor): MySQL 5.6.21
- JDBC Driver (include name if inofficial driver): MySQL Connector 5.1.43

**Comment by lukaseder** [comment]
Thanks for your report. Would you mind showing the complete DDL of the `ORDER_DETAIL` table?

**Comment by dustContributor** [comment]
Sorry for the delay:

```sql
CREATE TABLE `ORDER_DETAIL` (
  `ID_ORDER` int(10) unsigned NOT NULL,
  `ID_COMPONENT` int(10) unsigned NOT NULL,
  `QUANTITY` int(10) unsigned NOT NULL,
  `TOTAL_PRICE` int(10) unsigned NOT NULL,
  KEY `ORDER_DETAIL_COMPONENT_FK` (`ID_COMPONENT`),
  KEY `ORDER_DETAIL_ORDER_FK` (`ID_ORDER`),
  CONSTRAINT `ORDER_DETAIL_COMPONENT_FK` FOREIGN KEY (`ID_COMPONENT`) REFERENCES `COMPONENT` (`ID`) ON DELETE CASCADE,
  CONSTRAINT `ORDER_DETAIL_ORDER_FK` FOREIGN KEY (`ID_ORDER`) REFERENCES `ORDER` (`ID`) ON DELETE CASCADE
);
```

**Comment by lukaseder** [comment]
Oh, I see, thanks for the update. There's no `AUTO_INCREMENT` column in your table, so the MySQL JDBC driver doesn't return any generated keys. I'm afraid there's not much we can do on the jOOQ side...
