### ISSUE TITLE
Generate fluent API from a more formal BNF specification

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#721]
#720 could also be achieved by using an external BNF-specification to fluent API generator. That could be an entirely independent project from jOOQ

**Comment by lukaseder** [comment]
We're doing that now behind the scenes. The API generator isn't open source, though.

**Comment by lukaseder** [comment]
... and it's also not a BNF specification 😅

**Comment by tarilabs** [comment]
would you consider, or was there already, some article that describe it ?

I was subscribed to this github issue 😅  I believe for this part:

> That could be an entirely independent project from jOOQ

thanks in any case!

**Comment by lukaseder** [comment]
Nah, it's too messy and specific to jOOQ... So writing about it means cleaning it up first.

**Comment by lukaseder** [comment]
There's this project here for anyone interested:
https://github.com/verhas/fluflu
