### ISSUE TITLE
MySQL 5.7.21, jOOQ 3.10.5, routines are not generating

### ISSUE THREAD

**Issue by aram535** [jOOQ/jOOQ#7214]
### Expected behavior and actual behavior:

Routines should be available after code generation

### Steps to reproduce the problem:

Have a small project that I can share with you. However, this is enough to see the issue

```
CREATE SCHEMA TESTDB;
CREATE PROCEDURE `TESTDB`.`foo` .... 
SELECT DISTINCT db from `mysql`.`proc`;

```

### Versions:

- jOOQ: 3.10.5
- Java: Oracle 1.8.0_161_b12
- Database (include vendor): MySQL 5.7.21
- JDBC Driver (include name if inofficial driver): 6.0.6

MySQL's fault on this one... the proc names are being stored as lowercase no matter what the name of the database is. 

Workaround -- remove the inputSchema and generate all schemas and the routines are generated OR exclude rather than include schemas.

**Comment by lukaseder** [comment]
Thanks for your report.

I'm sorry, but I'm not sure what you're reporting, though. There are various different settings in MySQL related to case sensitivity. Also, there are different behaviours on Windows and Linux/Unix systems. Could that explain things?

If not, could you perhaps share that project (including jOOQ code generation config) you've mentioned so I can see what exactly you're expecting?

**Comment by aram535** [comment]
Sure ... project is @ https://github.com/aram535/jooqGenTest

It's using gradle plugin for the most part ... but I also did create a library.xml for debugging via eclipse. 

What it comes down to is: 

creating schema TDB --> 
inputSchema = TDB
AbstractDatabase.getInputSchemata() returns TDB
MySQLDatabase.getRoutines() does a SELECT ... WHERE db='TDB' 
which returns 0 rows .. 

If you select * --> db=tdb 

If you know of a mysql setting that stores SPROC DB names the same case as the schema case that would solve my problem but I have not found it.

**Comment by lukaseder** [comment]
Thanks for the test case. Hmm, this reminds me an awful lot of this issue here:

- https://bugs.mysql.com/bug.php?id=86022
- https://github.com/jOOQ/jOOQ/issues/5213

The workaround there was to specify the inputschema twice (or add any other additional input schema). Can you confirm this workaround works for you? E.g. run:

```sql
SELECT DISTINCT db from `mysql`.`proc` WHERE db IN ('TDB', 'dummy');
```

> If you know of a mysql setting that stores SPROC DB names the same case as the schema case that would solve my problem but I have not found it.

Does `lower_case_table_names` affect it?
https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html

**Comment by aram535** [comment]
The select returns no rows .... you would have to do:

`SELECT DISTINCT db from `mysql`.`proc` WHERE db IN ('TDB', lcase('TDB'));`

for it to return anything. 

lower_case_table_names is actually the complete opposite of this issue.  I am going to report this to MySQL. No matter what, whatever the case I use when I define the SPROC should be what is in the table.   

I opened up a bug report with Oracle, though I doubt they'll fix it.
https://bugs.mysql.com/bug.php?id=89774

**Comment by lukaseder** [comment]
Thanks for reporting this. Could you also check `information_schema.routines`? Is the information in there correct? From MySQL 8.0 onwards, we'll query that table instead of `proc` (which has gone!)

In the meantime, I guess ideally we'll add lower-case versions of each input schema to that query...

**Comment by aram535** [comment]
Yes, information_schema has the same issue ... I actually included that in the bug report to Oracle. 

Great.  Thanks for the upcoming patch.

**Comment by aram535** [comment]
Just to confirm .. tried mysql 8 ... 

`mysql> select routine_schema from information_schema.ROUTINES WHERE routine_schema='TDB';
+----------------+
| ROUTINE_SCHEMA |
+----------------+
| TDB            |
| TDB            |
| TDB            |
+----------------+
3 rows in set (0.00 sec)`

`mysql> select @@version;
+--------------+
| @@version    |
+--------------+
| 8.0.3-rc-log |
+--------------+`

**Comment by lukaseder** [comment]
Hmm, sorry, how is it the same issue in MySQL 8 with information_schema? Upper case is correct / expected, no?

I cannot promise a patch yet. I really need to be able to reproduce this first, I haven't been successful yet...

**Comment by aram535** [comment]
Hi, 

I was confirming your findings with MySQL 8 -- all schema names are in the proper case, all good.
With < 8 obviously the problem does exist.  

I can provide a docker command to set up a 5.7 + SQL to build a test case if you like?

**Comment by lukaseder** [comment]
I see, thanks for the clarification. Yes, that docker command would be really great, thanks for offering it!

**Comment by aram535** [comment]
Sent a couple of options in an email.  Happy to help further if required.

**Comment by lukaseder** [comment]
Thanks a lot. Will investigate next week...

**Comment by lukaseder** [comment]
I'm revisiting old issues and ran across this one. Unfortunately, I cannot seem to find that email you had sent at the time. I'm very sorry about that. Do you still have the issue on your side? I'm still unable to reproduce the case.

**Comment by aram535** [comment]
I think we can close this out.  The workaround of "exclude" rather than mass include worked out for us and it's a non-issue for later versions of MySQL.   Thanks.

**Comment by lukaseder** [comment]
Thanks a lot for the feedback!
