### ISSUE TITLE
JPA Database code generation fails at presumably correctly annotated POJOs

### ISSUE THREAD

**Issue by SkiffCMC** [jOOQ/jOOQ#7225]
### Expected behavior and actual behavior:
I try to generate jOOQ classes from JPA-annotated entities with jooq-codegen-plugin for Maven, but it fails with error:
Failed to execute goal org.jooq:jooq-codegen-maven:3.10.5:generate (default) on project my-project: Error running jOOQ code generation tool: Error while exporting schema: JoinTable.name() on a @ToOne association has to be explicit: long class name with bad annotation goes here
Annotation which causes error looks like:
```
            @XmlElement(name = "*UTF8EncodedName*")
            @Valid
            @OneToOne(fetch=FetchType.EAGER,cascade= CascadeType.ALL)
            @JoinTable(
		            joinColumns=
		            @JoinColumn(referencedColumnName="id"),
		            inverseJoinColumns=
		            @JoinColumn(referencedColumnName="id"))
            @CascadeOnDelete
protected className fieldName;
```
Class className exists, contains "id" field and is annotated as @Entity without references to the first class or corresponding table.
The strange thing is that these POJOs transform to database perfectly with eclipselink 2.7.0, so annotations seem to be correct(eclipselink use className as missing table name in created database), and it seems to be correct behaviour for JPA2.1 standard as i tried to google. I assume that Hibernate 5.2.10 used by plugin must support JPA2.1 also and do the same, but something seems to be wrong...

### Steps to reproduce the problem:

Use project with two JPA Entities with the same annotations as JPADatabase source for codegen plugin.

### Versions:

- jOOQ: 3.10.5
- Java: 1.8.0_141
- Database (include vendor): JPADatabase
- OS:Windows
- JDBC Driver (include name if inofficial driver):-

**Comment by lukaseder** [comment]
Thanks for your report. This does indeed look like an error produced by Hibernate, which is used behind the scenes by jOOQ. I can see making the choice of JPA provider used by `JPADatabase` configurable: #7226. But until then, I don't think there's much that can be done on the jOOQ side. You could report a bug to Hibernate, though.
