### ISSUE TITLE
InsertOrUpdate feature

### ISSUE THREAD

**Issue by meyacine** [jOOQ/jOOQ#7227]
### Expected behavior and actual behavior:
Is there a way to get InsertOrUpdate feature, also for batch queries

**Comment by lukaseder** [comment]
Thank you very much for your request.

- What database vendor and version are you using?
- What kind of query do you want to batch

**Comment by meyacine** [comment]
Hi Luka,
I'm using the version 3.9.5 of jooq, and PostgreSQL as DBMS.
Thank's for your reply

**Comment by lukaseder** [comment]
Well, I'd use the `INSERT .. ON CONFLICT` query in PostgreSQL and send that to the `batch()` API:
https://www.jooq.org/doc/latest/manual/sql-execution/batch-execution

I hope this helps

**Comment by meyacine** [comment]
I've already seen this documentation. There no way with Jooq. It's a **fail** 👎 to do it using JDBC. 

I think also, that this issue is not fixed.

The idea is to provide a Collection of UpdatableRecord to a batchInsertOrUpdate method.

Example : 
instead of
```
aDsl.batchStore(records).execute();
```
desired
```
aDsl.batchInsertOrUpdate(records).execute();
```

Thank you

**Comment by lukaseder** [comment]
> I've already seen this documentation. There no way with Jooq. It's a fail 👎 to do it using JDBC.

Maybe, the manual is a bit misleading, but if you scroll down, you'll see the jOOQ version.

> I think also, that this issue is not fixed.

Well, your question was short and so was the answer :-) I'm sorry if I didn't answer your question to your full satisfaction, but in my experience, the more time you invest in a complete question with all details, the better the answer. Here is a good document on that topic:
https://stackoverflow.com/help/mcve

> aDsl.batchInsertOrUpdate(records).execute();

jOOQ currently doesn't offer that. So, this is probably a duplicate of https://github.com/jOOQ/jOOQ/issues/2961, then.

Thanks again
Lukas
