### ISSUE TITLE
Add support for ALTER TABLE .. ADD .. [ FIRST | BEFORE | AFTER ]

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7241]
At least H2, HSQLDB, and MySQL have native support for adding a column at a certain position, logically, in a table. In Oracle, this can be emulated by marking the column invisible and visible again:
https://community.oracle.com/ideas/3036#comment-1016298

### HSQLDB:

```
<add column definition> ::= ADD [ COLUMN ] <column definition> [ BEFORE <other column name> ]
```

### MySQL (And Aurora MySQL, MemSQL):

```
ADD [COLUMN] col_name column_definition [FIRST | AFTER col_name]
```

### H2

Supports all syntaxes

----
See: 
- http://www.hsqldb.org/doc/2.0/guide/databaseobjects-chapt.html#dbc_schemas_schema_objects
- https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

**Comment by vojtapol** [comment]
We decided to add an extra step to the build pipeline which preprocesses the SQL migration files a bit, e.g. drops certain keywords that the jOOQ parser can't handle etc.

This issue is a show stopper though. We do have a few `AFTER` statements in our migration and since we often use default mappers and our POJOs have no setters we need to be 100% sure that the column order matches the constructor order of the POJOs.

**Comment by lukaseder** [comment]
>  e.g. drops certain keywords that the jOOQ parser can't handle etc.

Curious, what are those keywords? Would be nice to get a feature request about this.

> This issue is a show stopper though

Thanks for your comment. I'll revisit this for a prioritisation in 3.12. I cannot make any promises, though. The databases are, unfortunately, very different in this area.

However, do note that there is `org.jooq.meta.Database.setOrderProvider()` which you can use to override the ordering of objects as supplied by the database:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-order-provider

This seems to be a cleaner, more vendor agnostic way to handle this...

**Comment by vojtapol** [comment]
We often use multiline `ALTER` statements in MySQL:
```SQL
ALTER TABLE `user`
  MODIFY COLUMN `first_name` VARCHAR(190) NOT NULL,
  MODIFY COLUMN `last_name` VARCHAR(190) NOT NULL,
  MODIFY COLUMN `password` CHAR(60) NOT NULL;
```

I am not sure if an issue has already been filed but the jOOQ parser can't handle this. Our preprocessing script splits these into separate `ALTER` statements to bypass that.

> However, do note that there is org.jooq.meta.Database.setOrderProvider()

Thanks for the tip, we will look into that.

**Comment by lukaseder** [comment]
> We often use multiline ALTER statements in MySQL

Thanks for the pointer. Indeed, support for these kinds of statements are on the roadmap: #7898. Emulating them requires a bit more sophistication in the new procedural language abstraction API: #6475

**Comment by lukaseder** [comment]
Implemented for jOOQ 3.13.0

**Comment by vojtapol** [comment]
Amazing addition @lukaseder. Now we just need https://github.com/jOOQ/jOOQ/issues/8834 and I think we can finally generate jOOQ classes from our migration files. 🎉

**Comment by lukaseder** [comment]
One step at a time :)
