### ISSUE TITLE
jOOQ not getting configuration from maven

### ISSUE THREAD

**Issue by johnkeates** [jOOQ/jOOQ#7247]
### Expected behavior and actual behavior:
I configured jOOQ's plugin as follows:

```


            <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>3.10.5</version>
                <executions>
                    <execution>
                        <id>jooq-codegen</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <jdbc>
                                <driver>com.filemaker.jdbc.Driver</driver>
                                <url>jdbc:filemaker://192.168.123.123/filemakerdb</url>
                            </jdbc>
                            <generator>
                                <database>
                                    <name>org.jooq.util.jdbc.JDBCDatabase</name>
                                    <includes>.*</includes>
                                    <excludes></excludes>
                                </database>
                                <target>
                                    <directory>target/generated-sources/jooq-classes</directory>
                                    <packageName>my.special.package</packageName>
                                </target>
                            </generator>
                        </configuration>
                    </execution>
                </executions>
            </plugin>


```
I run `mvn jooq-codegen:generate -X` and I expect some classes to end up in the generated-sources directory, yet this fails for some reason because none of the configuration makes it into jooq.

### Steps to reproduce the problem:
Run `mvn jooq-codegen:generate -X`
 get:

```
[DEBUG] -----------------------------------------------------------------------
[DEBUG] Goal:          org.jooq:jooq-codegen-maven:3.10.5:generate (default-cli)
[DEBUG] Style:         Regular
[DEBUG] Configuration: <?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <project>${project}</project>
</configuration>
[DEBUG] =======================================================================
```

and further down:

```
[ERROR] Incorrect configuration of jOOQ code generation tool
[ERROR]
The jOOQ-codegen-maven module's generator configuration is not set up correctly.
This can have a variety of reasons, among which:
- Your pom.xml's <configuration> contains invalid XML according to jooq-codegen-3.10.0.xsd
- There is a version or artifact mismatch between your pom.xml and your commandline
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.307 s
[INFO] Finished at: 2018-03-02T22:57:18+01:00
[INFO] Final Memory: 14M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.10.5:generate (default-cli) on project myspecialproject: Incorrect configuration of jOOQ code generation tool. See error above for details. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jooq:jooq-codegen-maven:3.10.5:generate (default-cli) on project myspecialproject: Incorrect configuration of jOOQ code generation tool. See error above for details.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Incorrect configuration of jOOQ code generation tool. See error above for details.
	at org.jooq.util.maven.Plugin.execute(Plugin.java:163)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR]
```
It makes sense that it doesn't like an empty configuration, but I'm pretty sure the configuration in pom.xml is correct, yet not passed to jooq for some reason?
### Versions:

- jOOQ: 3.10.5 (both plugin and dependency)
- Java: 1.8.0_131, vendor: Oracle Corporation
- Database (include vendor): FileMaker
- OS: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"
- JDBC Driver (include name if inofficial driver): com.filemaker.jdbc.Driver
- Apache Maven 3.5.0

**Comment by johnkeates** [comment]
Putting the configuration directly inside the plugin level and not inside  `<executions><execution>` does work

**Comment by johnkeates** [comment]
I'm probably just not using maven correctly to point to the right execution meaning this has little to do with jooq.

**Comment by lukaseder** [comment]
Interesting, thanks for reporting. The configuration does look correct, though, and I cannot reproduce this particular issue (with Maven 3.5.2)...

Let me know if you think this is worth investigating further.

**Comment by florianluediger** [comment]
Just FYI, I had the same issue. My configuration and log outputs look similar to @johnkeates in the first post. Putting the configuration out of the execution block directly into the plugin block fixes this issue for me, too.

My system:

- jOOQ version: 3.11.2
- Java version: 1.8.0_161
- Maven version: 3.5.4
- Database: HSQLDB
- OS: Windows 10 x64

**Comment by lukaseder** [comment]
Thanks for your post, @florianluediger. Another report is this: https://stackoverflow.com/q/51226145/521799

Will try again to reproduce this.

**Comment by lukaseder** [comment]
I can reproduce it now, don't know what I did differently earlier this year (https://github.com/jOOQ/jOOQ/issues/7247#issuecomment-370365620). Will investigate

**Comment by lukaseder** [comment]
As shown in this answer (https://stackoverflow.com/q/51226145/521799) this is not something that jOOQ seems to be able to do much about. There are at least three known workarounds:

- Move the configuration from the `<execution>` tag to the `<plugin>` tag
- Move the plugin to a profile
- Rename the execution to `default-cli`

**Comment by abonander** [comment]
@lukaseder I've run into an issue here; I need to configure multiple executions of the plugin as I need to generate DSLs for multiple databases in the same project (aggregating data from several applications, each of which talks to their own database). I don't see any other way that I can do this other than having per-execution configuration.

The POM reference implies that this either should get merged with or supercede the `<configuration />` block for the whole plugin but it doesn't really go into details on semantics: https://maven.apache.org/pom.html#Plugins

If we're sure this is not a jOOQ bug then it's a Maven bug and needs to be addressed by them because the way the documentation reads, it leads me to think that per-execution configuration should behave at least _similarly_ to global configuration for a plugin.

**Comment by lukaseder** [comment]
Thanks for your comments, @abonander. You can reuse some configuration from `<pluginManagement>`. Not sure if this helps...

**Comment by abonander** [comment]
Okay, so funnily enough this doesn't appear to work if you run `maven jooq-codegen:generate` but if you have multiple executions configured then running `maven compile` will run all the executions with correct configuration. There's a little note in the plugins guide that hints that this is the expected behavior:

> Note: Configurations inside the `<executions>` element used to differ from those that are outside `<executions>` in that they could not be used from a direct command line invocation because they were only applied when the lifecycle phase they were bound to was invoked. So you had to move a configuration section outside of the executions section to apply it globally to all invocations of the plugin. Since Maven 3.3.1 this is not the case anymore as you can specify on the command line the execution id for direct plugin goal invocation. Hence if you want to run the above plugin and it's specific execution1's configuration from the command-line, you can execute:
>  `mvn myqyeryplugin:queryMojo@execution1`

So it seems that you have to specify the execution ID to run or else just running the goal will only use the outer config. I guess since executions bind to phases, not goals, it doesn't make sense to Maven when asked to execute the `jooq-codegen:generate` goal to run the plugin 6 times. It's very counterintuitive though and I hate that this behavior isn't more clearly documented.

**Comment by abonander** [comment]
Additionally it does appear that common configuration *can* go in the outside `<configuration>` block and it will get merged with the configuration of each execution.

**Comment by lukaseder** [comment]
In the past, I've used profiles for such purposes, too. Also, you can use jOOQ's `<configurationFile>` flag to re-use an external configuration file, to prevent repetition

**Comment by kongchen** [comment]
> As shown in this answer (https://stackoverflow.com/q/51226145/521799) this is not something that jOOQ seems to be able to do much about. There are at least three known workarounds:
> 
> * Move the configuration from the `<execution>` tag to the `<plugin>` tag
> * Move the plugin to a profile
> * Rename the execution to `default-cli`
> 
> This seems to be how maven works - probably not much that can be done on the jOOQ side.

The solution seems not suiteable for multiple datasource? 

I came to this issue because I want to use multiple datasources in my project, according to this answer: https://stackoverflow.com/a/26105204, I added multiple executions but failed due to this issue. 

Is there anything missing?

**Comment by lukaseder** [comment]
While Maven does support multiple configurations (one per execution), it is not possible to invoke those executions explicitly in Maven short of running them all in a complete build, with the exception of what I've documented previously:
https://github.com/jOOQ/jOOQ/issues/7247#issuecomment-404445693

This is not a problem in jOOQ, but a problem in Maven. Try configuring multiple XJC code generation configurations in the same way, you'll run into the same problem.

Workarounds do exist, including the possibility of extracting a configuration to an external XML file, referencing the file from the Maven configuration, and setting up some infrastructure to call the `GenerationTool` manually from the command line.

**Comment by kongchen** [comment]
@lmarchau Thanks for your reply. I tried several approaches yesterday and finally have a workaround but with some limitation(only 2 datasource)

Lucky I only have 2 datasource, and I configured 2 executions, one named `default-cli` and the other named `default`, which can help me generate codes in one build.

```
<plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>${jooq.version}</version>
                <executions>
                    <execution>
                        <id>default-cli</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <configurationFile>datasource-1.xml</configurationFile>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <configurationFile>datasource-2.xml</configurationFile>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>${mysql.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by paulschmitz82** [comment]
@abonander did you find a solution? i currently got the same problem
