### ISSUE TITLE
PARSER ERRO on Select *, whatever 

### ISSUE THREAD

**Issue by fredpolicarpo** [jOOQ/jOOQ#7256]
```java
context.parser().parseQuery('select *, (a - b) as c from (select x, y, sum(z) as a, sum(d) as b from foo) inner_')
```

**C42000_NO_SUBCLASS: Unexpected content after end of query input: [1:9] select *[*], (a - b) as c from (select x, y, sum(z) as a, sum(d) as b from foo) inner_**

**Comment by lukaseder** [comment]
Thank you very much for your report. This is a known issue in jOOQ 3.10.x. Fixing it required supporting qualified and unqualified asterisks (see #1677), which has been implemented for jOOQ 3.11. There will be no backport to jOOQ 3.10 for this feature.

jOOQ 3.11 is due for early Q2 2018
