### ISSUE TITLE
Deprecate org.jooq.Clause

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7258]
The `VisitListener` SPI is rather hard to implement correctly. One reason for this is that `org.jooq.Clause` is:

- Incompletely specified (e.g. some clauses are simply missing: #3261, an issue open since 2014 and few people noticed!)
- Positioned randomly inside of `QueryPart` implementations (e.g. are there wrappers around expressions? How many? Etc.)

There has been a pending feature request to replace the `Clause` by actual `QueryPart` implementations: #3654, which is probably also not a good idea.

With this deprecation, we'll get feedback from users actually using the `Clause`, and we can better assess what to implement (if anything at all) in the future. The discussion will be open, and it might even include deprecating and removing the `VisitListener` SPI entirely

**Comment by matthewcachiaweavr** [comment]
Adding feedback as instructed in `Clause.java`'s deprecation note.

Context:
- MySQL 8
- Micronaut 4 (jOOQ 3.19.7 comes bundled; version dictated by framework).
- Blanket Row-level Locking across all schemas which have a specific column (_owner_).
- A row is considered accessible if: _owner_ is `null` or is equal to the subject accessing that piece of data.

[The code snippet you provided in your article](https://blog.jooq.org/implementing-client-side-row-level-security-with-jooq/) fits perfectly for my needs. At the same time I also agree that the visit listener with the current _Clauses_ is really hard to work with.

Using an _ExecutionListener_(by tapping onto the context's query) proved much easier and works for the most part, except in certain "inline" situations where the query itself doesn't seem to be mutable. Take CTEs for example:

```sql
WITH
  cte1 AS (SELECT a, b FROM table1)
SELECT a, b FROM cte1
```

While I was able to access the inner query, I was unable to mutate it to become `SELECT ... FROM table1 WHERE ownerId = ...`). This forced me to revisit the _VisitListener_ approach.

I would be happy to provide you the ExecutionListener approach, if you wish.

**Comment by lukaseder** [comment]
Agh, I meant to update that article a long time ago. Row level security are a feature in jOOQ now, since jOOQ 3.19:
https://www.jooq.org/doc/latest/manual/sql-building/queryparts/policies/

**Comment by lukaseder** [comment]
Ah, it's already mentioned in the middle, but not highlighted... I'll add it again at the top.

**Comment by gaecfov** [comment]
@matthewcachiaweavr Are you using the commercial version? https://blog.jooq.org/implementing-client-side-row-level-security-with-jooq/, the code is very early here, I want to ExecutionListener implementation based on open source version, I need to decide whether to add the tenant information based on some table-based rule (such as whether the tenant_id column is included), but I can't find an api to fetch the relevant table information in the ExecutionListener. Can you provide some suggestions? Thank you very much

**Comment by lukaseder** [comment]
@gaecfov Do give policies a try: https://www.jooq.org/doc/latest/manual/sql-building/queryparts/policies. They're available even in the jOOQ Express Edition and will be much simpler and way more robust for you.

You can use the new `QOM` API traversal methods from the `ExecuteListener`, also with the jOOQ Express Edition: https://www.jooq.org/doc/latest/manual/sql-building/model-api/model-api-traversal, or if you must use the OSS edition, you can try to traverse a `Select` using pattern matching on the `QOM` API (`Select::$from` and then continue pattern matching things manually, from there). But again, it will be way easier and more robust with out of the box functionality.
