### ISSUE TITLE
Generator doesn't select appropriate DataType for Columns using an enum from another schema

### ISSUE THREAD

**Issue by stellingsimon** [jOOQ/jOOQ#7271]
### Expected behavior and actual behavior:

When generating the JOOQ model for a view that references an enum from another schema, the DataType is `DefaultDataType.getDefaultDataType("USER-DEFINED")` instead of the correct `PostgresDataType.VARCHAR.asEnumDataType(com.xxx.MyType.class)` when there is a `<forcedType>` definition applying to said column. The resulting JOOQ model does not compile without manual changes.

### Steps to reproduce the problem:

Create two schemas `defining_schema` and `referencing_schema` in a Postgres database. Then:

    CREATE TYPE defining_schema.my_enum AS ENUM ('VAL_A', 'VAL_B');
    CREATE VIEW referencing_schema.my_view AS (SELECT 'VAL_A'::defining_schema.my_enum AS enum_typed_column);
    CREATE VIEW referencing_schema.my_view_with_forced_type AS (SELECT 'VAL_A'::defining_schema.my_enum AS forced_enum_typed_column);

Now run the JOOQ java code generator with the following configuration:

    <inputSchema>defining_schema</inputSchema>
    <inputSchema>referencing_schema</inputSchema>
    ...
    <forcedType>
      <userType>com.xxx.MyForcedType</userType>
      <binding>com.xxx.MyForcedTypeBinding</binding>
      <expression>referencing_schema\.my_view_with_forced_type\.forced_enum_typed_column</expression>
    </forcedType>

Actual output:

    public final TableField<MyViewRecord, MyType> ENUM_TYPED_COLUMN = createField("enum_typed_column",
                                                                     org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.xxx.MyType.class),
                                                                     this,
                                                                     "");
                                                                     
    public final TableField<MyViewWithForcedTypeRecord, MyForcedType> FORCED_ENUM_TYPED_COLUMN = createField("forced_enum_typed_column",
                                                                                                             org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"),
                                                                                                             this,
                                                                                                             "",
                                                                                                             new MyForcedTypeJooqBinding());

Expected: Both `ENUM_TYPED_COLUMN` and `FORCED_ENUM_TYPED_COLUMN` should have the `DataType` `org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(com.xxx.MyType.class)`.

### Hints for analysis:

With a debugger attached to the generator, I observe that on `JavaGenerator.java:3583` (Method `generateTable(TableDefinition table, JavaWriter out)`, just inside the `for`-Loop over Columns) we get a DataTypeDefinition that uses the `referencing_schema` instead of the `defining_schema`:

![screenshot_2018-03-09_11-25-29](https://user-images.githubusercontent.com/7038847/37203233-4f20e448-238d-11e8-91e1-839232203286.png)

However, I cannot for the life of me find out *why* it uses the wrong schema in this very particular scenario...

### Potentially related issues:

 * #4682
 * #6367

### Versions:

- jOOQ: 3.10.5
- Java: 1.8
- Database (include vendor): Postgres-9.5
- OS: Linux
- JDBC Driver (include name if inofficial driver): Postgres 42.2.1

**Comment by lukaseder** [comment]
Thanks for your report. Are you sure both schemas are correctly included? You shouldn't be able to duplicate the `<inputSchema>` element. The correct approach is:

```xml
<schemata>
  <schema>
    <inputSchema>...</inputSchema>
  </schema>
  <schema>
    <inputSchema>...</inputSchema>
  </schema>
</schemata>
```

See also: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-catalog-and-schema-mapping/

**Comment by stellingsimon** [comment]
I'm sorry, I guess I was too brief in my description. Here's the relevant portion of the configuration XML that we generate:

      <schemata>
        <schema>
          <inputSchema>defining_schema</inputSchema>
        </schema>
        <schema>
          <inputSchema>referencing_schema</inputSchema>
        </schema>
      </schemata>
      <includes>.*</includes>
      <excludes>schema_version</excludes>
      <forcedTypes>
        <forcedType>
          <userType>com.xxx.MyForcedType</userType>
          <binding>com.xxx.MyForcedType.MyForcedTypeJooqBinding</binding>
          <expression>referencing_schema\.my_view_with_forced_type\.forced_enum_typed_column</expression>
        </forcedType>
      </forcedTypes>

I should note that we use this configuration to generate Java classes for 16 schemas with a total of >500 tables, and only two views exhibit the problem mentioned here. Everything else is generated just as expected. :-)

**Comment by lukaseder** [comment]
I shouldn't have doubted you, I know the size of your projects :-)

I will look into this right away

**Comment by stellingsimon** [comment]
Thanks Lukas. Maybe the following info helps you:

I set a conditional breakpoint in the constructor of `DefaultDataTypeDefinition` and found that on this path, a `DefaultDataTypeDefinition` with schema `referencing_schema` but `userType` `defining_schema.my_type` is created:

        at org.jooq.util.DefaultDataTypeDefinition.<init>(DefaultDataTypeDefinition.java:182)
        at org.jooq.util.AbstractTypedElementDefinition.mapDefinedType(AbstractTypedElementDefinition.java:237)
        at org.jooq.util.AbstractTypedElementDefinition.getType(AbstractTypedElementDefinition.java:124)
        at org.jooq.util.DefaultColumnDefinition.getType(DefaultColumnDefinition.java:52)
        at org.jooq.util.JavaGenerator.generateTable(JavaGenerator.java:3581)
        at org.jooq.util.JavaGenerator.generateTable(JavaGenerator.java:3531)
        at org.jooq.util.JavaGenerator.generateTables(JavaGenerator.java:3518)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:451)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:405)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:327)
        at org.jooq.util.GenerationTool.run(GenerationTool.java:642)
        at org.jooq.util.GenerationTool.generate(GenerationTool.java:203)

It seems that this data type is then used when generating the columns.
The problematic line seems to be this one from `AbstractTypedElementDefinition:237`:

    result = new DefaultDataTypeDefinition(db, child.getSchema(), t, l, p, s, n, d, u, converter, binding, uType);

In this calling context, `child.getSchema()` is the schema of the field (which is `referencing_schema`), but instead the value from the `uType` should be used, similar to `PostgresTableDefinition:102`:

    String schemaName = record.get(COLUMNS.UDT_SCHEMA);

I hope that helps :-)

**Comment by lukaseder** [comment]
I can reproduce the issue. Thanks for the heads-up. Will investigate further

**Comment by lukaseder** [comment]
I can confirm, the type schema is incorrect for such type definitions. Let's look at why this happens...

**Comment by lukaseder** [comment]
Eh, should've read your comment to the end, you pointed to line 237, which I can confirm links the wrong schema. It should be:

```java
    result = new DefaultDataTypeDefinition(db, definedType.getSchema(), t, l, p, s, n, d, u, converter, binding, uType);
```

Will confirm this through the integration tests...

**Comment by lukaseder** [comment]
Yeah, that fixes it, with no regressions in the integration tests. Thanks again for your help!

Will merge this to jOOQ 3.10.6: #7272

**Comment by stellingsimon** [comment]
I retested with 3.10.6 and the actual outcome is still the same (`DefaultDataType.getDefaultDataType("USER-DEFINED")`), there seems to be some kind of follow-up problem. Debugging at JavaGenerator:3583 I see that `column.getType().getSchema()` is now `null`, which seems pretty odd.

![jooq_7271_followup_1](https://user-images.githubusercontent.com/7038847/37701250-8a30e8ac-2cee-11e8-8e4b-69ca8ab820a5.png)

**Comment by lukaseder** [comment]
@stellingsimon : I had received a notification about a retest of yours and a follow-up problem (quite some time ago). Trying to follow up on this, but your comment seems to have been deleted. Is there anything else left to do here, in your opinion?

**Comment by stellingsimon** [comment]
@lukaseder: Nothing to do here, thanks for checking!

My follow-up problem turned out to be a different one (in our build, not JOOQ), it just caused the same symptom. I deleted my comment because I didn't want to mislead anyone.

**Comment by lukaseder** [comment]
Great, thanks for the feedback
