### ISSUE TITLE
Allow customization of LoggerListener

### ISSUE THREAD

**Issue by Diagoras** [jOOQ/jOOQ#7301]
JOOQ has an _awesome_ default logging implementation - it captures everything I'm interested in and makes very clear what's happening. However, there doesn't seem to be a way to customize how things are logged. For example, I'd be interested in both logging at the INFO level and also using a marker.

Of course I can just do something ugly (like copy paste the class and modify all the log calls to include my changes), but I was wondering if there was a way to make logging more customizable. I'm not sure what would be the best way to do that - my usecase only requires changing the log level and passing a marker, but I could see others wanting features like selective logging (eg. turn off query execution time or returned results).

Thanks, and let me know if you need any more details.

**Comment by lukaseder** [comment]
Thanks for your suggestion. Yeah, I think we could add a few more flags to `Settings` to fine-tune how we log things out of the box. Something along the lines of:

- `Settings.executeLoggingBindVariables` (log level)
- `Settings.executeLoggingSqlString` (log level)
- `Settings.executeLoggingSqlStringInline` (log level)
- `Settings.executeLoggingResult` (log level)
- `Settings.executeLoggingResultNumberOfRows` (int)
- `Settings.executeLoggingException` (log level)

**Comment by lukaseder** [comment]
@Diagoras Notice: I wrote "Something along the lines of ...", this wasn't a complete suggestion of what needs to be done. I'll revert your actual adaptations of the logger and re-implement them. Will keep the parts that make sense.

**Comment by lukaseder** [comment]
On second thought, I'll revert the entire thing. This is going to overengineer the out of the box logger. It's super easy to write your own logger by simply copy pasting the `LoggerListener`...

**Comment by lukaseder** [comment]
... a more elaborate rationale:

- The suggested PR was far from complete and introduced a few significant regressions
- These things are much more work than they seem to cause, at first
- One thing that hasn't been covered yet is the documentation in the manual. Once these things are documented, they're hard to change

Reviewing the above concerns, the suggestion simply doesn't add enough value to justify the additional costs of maintaining the solution.
