### ISSUE TITLE
Add support for the SET command to assign values to variables

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7306]
In databases supporting procedural languages, there is always a way to assign a value to a variable.

- [x] In SQL Server, we can generate the `SET` command for this. It can even take `SELECT` statements as argument expressions
- [x] In Oracle, a `SET` command translates either to an assignment `var := value;` or ...
- [x] ... to a `SELECT .. INTO` statement

There may be other syntaxes

----
For variable declarations, see #7305 (this depends on declarations)

**Comment by sainth-** [comment]
Maybe it's also possible to support the [SET LOCAL of PostgreSQL](https://www.postgresql.org/docs/current/sql-set.html). So it will be possible to support RLS shown like [here](https://medium.com/@cazzer/designing-the-most-performant-row-level-security-strategy-in-postgres-a06084f31945).

**Comment by lukaseder** [comment]
@sainth- Thanks for your comment. That's a different type of `SET` command. This issue is about assigning a value to a previously declared local variable, within a statement batch, anonymous block, or stored procedure - i.e. part of the procedural languages. Yours is part of the SQL language.

**Comment by lukaseder** [comment]
(by which I mean to say: I sense a completely separate use-case in your message, which I'm more than happy to discuss in a new github issue!)

**Comment by sainth-** [comment]
@lukaseder Sorry, my mistake. I will create a new issue.
