### ISSUE TITLE
Document <javaTimeTypes> in the manual

### ISSUE THREAD

**Issue by stellingsimon** [jOOQ/jOOQ#7310]
I'm trying to find the documentation for `<javaTimeTypes>` in the manual, to no avail. It's advertised in [this blog post](https://blog.jooq.org/2017/01/06/how-to-write-a-quick-and-dirty-converter-in-jooq/) and in issue #4429, but apparently [not in the documentation](https://www.google.ch/search?q=site%3Ajooq.org+javaTimeTypes).

PS: Okay, so looking at the XSD it seems to belong into the `<generate>` tag. Would be nice to find it in a more prominent place, though ;-)

**Comment by lukaseder** [comment]
Thanks for reporting. Yes, we should document this.
