### ISSUE TITLE
Trailing newRecord() results in NULL insert statement

### ISSUE THREAD

**Issue by ben-manes** [jOOQ/jOOQ#7322]
In __3.9.2__, when a `newRecord()` is the last statement then the call has no effect (per JavaDoc). In __3.10.5__ this results in a statement with `NULL` values. If the `newRecord()` is set to preceding then the query is generated correctly. (Below sample is a little messy, because I codegen on H2 and run against Postgres, so cast for enum et. al.)

```java
private void assignRelationships(...) {
  InsertQuery<EntityByMetadataRecord> insert = db.insertQuery(ENTITY_BY_METADATA);
  activeIds.forEach(id -> addRelationship(insert, entity.getUniqueId(), id, dataType.active));
  inactiveIds.forEach(id -> addRelationship(insert, entity.getUniqueId(), id, dataType.inactive));
  insert.execute();
}

private void addRelationship(InsertQuery<EntityByMetadataRecord> insert,
    UUID entityId, UUID schemaId, Field<String> relationship) {
  insert.addValue(ENTITY_BY_METADATA.ENTITY_ID, entityId);
  insert.addValue(ENTITY_BY_METADATA.METADATA_ID, schemaId);
  insert.addValue(ENTITY_BY_METADATA.RELATIONSHIP, relationship);
  insert.newRecord();
}
```

#### jOOQ 3.9.2
```sql
INSERT INTO entity_by_metadata (
  entity_id, 
  metadata_id, 
  relationship
)
VALUES (
  'feb8888a-3a2a-4b10-9c3c-cb4df5ad1b47', 
  '11111111-0000-0000-0000-000000000000', 
  CAST('active' AS entity_relationship)
), (
  'feb8888a-3a2a-4b10-9c3c-cb4df5ad1b47', 
  '11111111-0000-0000-0000-000000000003', 
  CAST('active' AS entity_relationship)
), (
  'feb8888a-3a2a-4b10-9c3c-cb4df5ad1b47', 
  '11111111-0000-0000-0000-000000000014', 
  CAST('active' AS entity_relationship)
)
```

#### jOOQ 3.10.5
```sql
INSERT INTO entity_by_metadata (
  entity_id,
  metadata_id,
  relationship
)
VALUES (
  '0ffee995-8b06-463c-af4f-e73095ad9680',
  '11111111-0000-0000-0000-000000000000',
  CAST('active' AS entity_relationship)
), (
  '0ffee995-8b06-463c-af4f-e73095ad9680',
  '11111111-0000-0000-0000-000000000003',
  CAST('active' AS entity_relationship)
), (
  '0ffee995-8b06-463c-af4f-e73095ad9680',
  '11111111-0000-0000-0000-000000000014',
  CAST('active' AS entity_relationship)
), (
  NULL,
  NULL,
  NULL
)
```

**Comment by lukaseder** [comment]
Thank you very much for your detailed report. Indeed, the Javadoc is correct. The `newRecord()` call shouldn't add a new record immediately. I'll investigate this, soon.

**Comment by lukaseder** [comment]
The change was introduced with #6373 / https://github.com/jOOQ/jOOQ/commit/361c240e01085809b33bcf97b230f16eea643fa3

The breaking change was not an accident - I'll have to reconstruct why it was required, though, to see if it:

- Was implemented prematurely (Javadoc is still right, and we should rewind to 3.9 behaviour)
- Was implemented for a good reason (Javadoc is outdated)

**Comment by lukaseder** [comment]
I cannot see a good reason why #6373 needs to be maintained, other than the internals for #4420 being a bit more straightforward / less error-prone. Which isn't really that good of a reason for introducing a backwards incompatibility. The behaviour stated by the Javadoc is very convenient, akin to Java's way of allowing trailing commas in array literal. Additionally, jOOQ allows for leading `newRecord()` calls, which are ignored if not strictly necessary. This additional feature wasn't challenged by the description of #6373 either (although, it was implemented), which is inconsistent.

So, I believe that #6373 was a mistake, the Javadoc is correct, and since the Javadoc hasn't been changed, we can revert to the old behaviour. Given that there isn't too much value in adding a new, empty record using `newRecord()` (or even adding several empty records using consecutive `newRecord()` calls), there is less risk for regressions to people upgrading from 3.9.x.

I will think about this once more. Attached is a patch that would revert #6373 while maintaining #4420
[7322.patch.txt](https://github.com/jOOQ/jOOQ/files/1872010/7322.patch.txt)

**Comment by ben-manes** [comment]
Thanks. Will there will be a unit test added to assert the conclusion, regardless of what the decision is? I assume these exist in your private repository, but just want to make sure.

**Comment by lukaseder** [comment]
Yes of course. Curiously, the part about the trailing `newRecord()` calls wasn't covered, but the leading ones was. The new test (in case #6373 is reverted) looks like this:

```java
    public void testInsertMultipleTrailingNewRecordCall() {
        jOOQAbstractTest.reset = false;

        InsertQuery<A> q = create().insertQuery(TAuthor());
        q.newRecord();
        q.newRecord();
        q.newRecord();
        q.newRecord();
        q.addValue(TAuthor_ID(), val(37));
        q.addValue(TAuthor_LAST_NAME(), "Dürrenmatt");
        q.newRecord();
        q.newRecord();
        q.addValue(TAuthor_ID(), 88);
        q.addValue(TAuthor_FIRST_NAME(), "Eric Emmanuel");
        q.addValue(TAuthor_LAST_NAME(), "Schmitt");
        q.newRecord();
        q.addValue(TAuthor_ID(), val(93));
        q.addValue(TAuthor_YEAR_OF_BIRTH(), 1899);
        q.addValue(TAuthor_LAST_NAME(), "Kästner");
        q.newRecord();
        q.newRecord();
        q.newRecord();

        assertEquals(3, q.execute());

        Result<A> authors =
        create().selectFrom(TAuthor())
                .where(TAuthor_ID().greaterThan(30))
                .orderBy(TAuthor_ID())
                .fetch();

        assertEquals(3, authors.size());
        assertEquals(Integer.valueOf(37), authors.getValue(0, TAuthor_ID()));
        assertEquals(Integer.valueOf(88), authors.getValue(1, TAuthor_ID()));
        assertEquals(Integer.valueOf(93), authors.getValue(2, TAuthor_ID()));
        assertNull(authors.getValue(0, TAuthor_FIRST_NAME()));
        assertEquals("Eric Emmanuel", authors.getValue(1, TAuthor_FIRST_NAME()));
        assertNull(authors.getValue(2, TAuthor_FIRST_NAME()));
        assertEquals("Dürrenmatt", authors.getValue(0, TAuthor_LAST_NAME()));
        assertEquals("Schmitt", authors.getValue(1, TAuthor_LAST_NAME()));
        assertEquals("Kästner", authors.getValue(2, TAuthor_LAST_NAME()));
        assertNull(authors.getValue(0, TAuthor_YEAR_OF_BIRTH()));
        assertNull(authors.getValue(1, TAuthor_YEAR_OF_BIRTH()));
        assertEquals(1899, authors.getValue(2, TAuthor_YEAR_OF_BIRTH()));
    }
```

**Comment by lukaseder** [comment]
#6373 will be reverted in jOOQ 3.11, so 3.9 and 3.11 behave the same way
