### ISSUE TITLE
Replace cursor-based FOR UPDATE emulation in SQL Server by table hints

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7328]
The current emulation of `FOR UPDATE` in SQL Server creates a `CONCUR_UPDATABLE` JDBC `ResultSet` and updates the rows while iterating them. The same is done for CUBRID.

This approach is not an entirely accurate emulation of the `FOR UPDATE` clause, as it may produce deadlocks if two client processes lock rows in inverse order.

A much better option would be to add a table hint to all the relevant tables in order to lock their rows:
https://docs.microsoft.com/en-us/sql/t-sql/queries/hints-transact-sql-table

When removing this for SQL Server, we'll also remove the functionality for `CUBRID`, which is deprecated (https://github.com/jOOQ/jOOQ/issues/9403).

Once this is removed, the manual and Javadoc can be updated (search for `CONCUR_UPDATABLE` or `TYPE_SCROLL_SENSITIVE`)

**Comment by knutwannheden** [comment]
Some notes:
* This issue refers to the logic implemented in `AbstractResultQuery.prepare(ExecuteContext)` and `SelectQueryImpl.accept0(Context<?>)`
* Both `SelectQueryImpl` and `AbstractResultQuery` declare a static `NO_SUPPORT_FOR_UPDATE` field

Question:
* If the `FOR UPDATE` clause doesn't have an `OF` clause, would we then have to render a `WITH (UPDLOCK)` clause for every table appearing in any of the (possibly nested or inside `WITH`) `FROM` clauses?
* Does this work with views? I suppose that needs to be tested.
* If there *is* an `OF` clause, will we be able to map this to the correct table reference in a (possibly nested) `FROM` clause?

**Comment by lukaseder** [comment]
> If the FOR UPDATE clause doesn't have an OF clause, would we then have to render a WITH (UPDLOCK) clause for every table appearing in any of the (possibly nested or inside WITH) FROM clauses?

This is my intuition. Like with any other RDBMS that have native `FOR UPDATE` support, the presence of `FOR UPDATE` in a query limits the possibilities of what can be placed in the `FROM` clause. I imagine there are some rules, which we can implement as well. I would imagine the usual "updatable view" rules apply here as well. To be researched.

> Does this work with views? I suppose that needs to be tested.

**Comment by lukaseder** [comment]
There is some subtlety when aliasing tables, or when there are existing hints. For example, this is the correct syntax:

```sql
select * from book as b with (updlock, nowait)
```

These are incorrect:

```sql
select * from book with (updlock) as b;
select * from book with (updlock) with (nowait);
```

**Comment by lukaseder** [comment]
We probably need integration tests for using `FOR UPDATE` with aliased tables anyway. This might not be implemented correctly in some dialects.

**Comment by lukaseder** [comment]
In order to support concatenated hints, we need new API that allows for plain SQL templating in those hints: #10023
