### ISSUE TITLE
jOOQ 3.10.6 download fail

### ISSUE THREAD

**Issue by ahamana** [jOOQ/jOOQ#7338]
### Steps to reproduce the problem:
The pom file of the jOOQ parent 3.10.6 is not found in the Bintray, so the Gradle dependency settings fail.
https://jcenter.bintray.com/org/jooq/jooq-parent/3.10.6/jooq-parent-3.10.6.pom

### Versions:
- jOOQ: 3.10.6

**Comment by lukaseder** [comment]
Thank you very much for your report. Indeed, something went wrong with the deployment on Maven Central - not on our side.

Will try to re-release the jooq-parent artifact

**Comment by lukaseder** [comment]
So, the parent pom is now available from Maven Central:
http://search.maven.org/#artifactdetails%7Corg.jooq%7Cjooq-parent%7C3.10.6%7Cpom

For reasons only the Maven gods know, it isn't listed in a search, though:
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.jooq%22%20AND%20a%3A%22jooq-parent%22

Please, re-test and reopen if this didn't fix the issue for you

**Comment by ahamana** [comment]
@lukaseder The download has no problem now.
Many thanks for your quick action.

**Comment by lukaseder** [comment]
Great, thanks for the feedback
