### ISSUE TITLE
How to make native SQL statements support paging using JOOQ

### ISSUE THREAD

**Issue by kkrgwbj** [jOOQ/jOOQ#7339]
How to make native SQL statements support paging using JOOQ？

**Comment by lukaseder** [comment]
Thank you very much for your enquiry. Would you mind showing an example of what you've tried to do and how that failed? Specifically, I'm interested in what you mean by "native SQL statements" and how you'd expect jOOQ to "support paging" for them...

**Comment by kkrgwbj** [comment]
for example 
     select * from push_content LIMIT 0,10
I want to implement this function, but I do not want to use the Record mode.

**Comment by lukaseder** [comment]
The `LIMIT` clause is documented here:
https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/limit-clause

I'm not sure how this is related to "native SQL", though, or what you mean by Record mode...

**Comment by kkrgwbj** [comment]
my English is not very good. I would like to implement this function similar to the following, but JOOQ does not seem to support
## 
dslContext.fetch("select * from xxx").limit(10).offset(1).into(xxxx)
##

**Comment by lukaseder** [comment]
Well, you could create a derived table from your plain SQL query and then apply limit / offset on that:

```java
dslContext.select().from("(select * from xxx) t").limit(10).offset(1).fetch().into(xxx);
```

Does this help?

**Comment by kkrgwbj** [comment]
@lukaseder Thank you, this is I wanted, but how to use it on the oracle database

**Comment by lukaseder** [comment]
1. I do assume you're now using at least the free trial of the jOOQ Professional Edition (see also https://github.com/jOOQ/jOOQ/issues/7323)
2. If you do, what are you struggling with *specifically*
