### ISSUE TITLE
Field.as(Field) and Table.as(Table) should inherit alias-defining Named's quoted flag

### ISSUE THREAD

**Issue by keithdotpower** [jOOQ/jOOQ#7342]
### Expected behavior and actual behavior:

Before I get down to the bug report, I want to say thanks for writing this library, I'm finding it great so far.

I expect when I do:
```
        SelectQuery quoteBugQuery = create.select(count().as(field("COUNT")))
                .from(table("BOOK"))
                .orderBy(field("COUNT"))
                .getQuery();
```
to get something like:
`select count(*) as "COUNT" from BOOK order by "COUNT"`
where both mentions of the aliase COUNT are quoted.

Instead I get:
`select count(*) as "COUNT" from BOOK order by COUNT`

which results in column "count" does not exist from Postgres. Note that if I use all uppercase for COUNT it works for H2 but breaks for Postgres and vice versa, so I can't just change the casing.

### Workaround:

The workaround I'm using for now is to use as() again in the orderBy, like so:

```
        SelectQuery quoteBugQuery = create.select(count().as(field("COUNT")))
                .from(table("BOOK"))
                .orderBy(field("COUNT").as("COUNT"))
                .getQuery();
```

### Steps to reproduce the problem:

```
        DSLContext create = DSL.using(org.jooq.SQLDialect.POSTGRES_9_5);
        SelectQuery quoteBugQuery = create.select(count().as(field("COUNT")))
                .from(table("BOOK"))
                .orderBy(field("COUNT"))
                .getQuery();
        System.out.println("Problem query is " + quoteBugQuery.getSQL());
```
Also occurs for H2 dialect

### Versions:

- jOOQ: 3.10.6
- Java: 8
- Database (include vendor): H2 and Postgres
- OS: Mac OSX
- JDBC Driver (include name if inofficial driver): N/A, happens at query gen time

**Comment by lukaseder** [comment]
Thank you very much for your report. The `ORDER BY` clause is behaving correctly. For details about the distinction between the plain SQL API and the identifier / name APIs, please refer to the manual:

- https://www.jooq.org/doc/latest/manual/sql-building/plain-sql
- https://www.jooq.org/doc/latest/manual/sql-building/names

So, you'll simply have to use `field(name("COUNT"))`, or better: reuse the reference directly (similar to one of your workarounds):

```java
    Field<?> count = count().as(field("COUNT"));
    SelectQuery quoteBugQuery = create.select(count)
                .from(table("BOOK"))
                .orderBy(count)
                .getQuery();
```


What's acting inconsistently here is the `as(Field)` call, which quotes the `Field`'s name when it shouldn't.

The fix would be easy, but not backwards compatible. This needs further investigation.

**Comment by keithdotpower** [comment]
Thanks Lukas. I prefer your workaround using name(), I'll use that in my code too.

**Comment by lukaseder** [comment]
Fixing this now for jOOQ 3.14. In the meantime, our understanding of quoted and unquoted names has improved. `SQLField` needs to wrap the argument SQL string in `DSL.unquotedName()`.

As this might be considered a backwards incompatible change (even if the incompatibility would be *very* subtle), I'm not backporting the fix to earlier releases.
