### ISSUE TITLE
Add Settings.parseUnknownFunctions to turn off failing on unknown functions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7344]
The jOOQ parser doesn't know all vendor-specific functions yet. We need a flag that simply accepts unknown functions and renders them as plain SQL functions in the output.

There are two modes:

- `FAIL`: Functions have to be known by the parser, or, once implemented, by the catalog: #7163. This is the default
- `IGNORE`: Unknown functions (parser or catalog) will be passed on as plain SQL

**Comment by JulianEberius** [comment]
Hi!
We just tried to use this feature in jOOQ 3.11, but it seems to fail on unknown functions with zero parameters. Specifically, we tried to parse Impala's pi() function, using the MySQL dialect, and the jOOQ parser seems to expect at least one field inside the brackets.
