### ISSUE TITLE
Error when binding null values to UUID types in PostgreSQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7351]
There is an error when binding a null value to a UUID type in PostgreSQL:

```
Caused by: org.postgresql.util.PSQLException: ERROR: column "id" is of type uuid but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 225
    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2422)
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2167)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
    at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
    at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:144)
    ...
    at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:209)
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:429)
    at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:452)
    at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:347)
    ... 51 more
```

----
See also: https://stackoverflow.com/q/49490526/521799

**Comment by vlsi** [comment]
@lukaseder , this one seems to be relevant: https://github.com/pgjdbc/pgjdbc/pull/1160

It looks like it jOOQ should use `setNull(column, type, typeName)` API.

**Comment by lukaseder** [comment]
@vlsi : `setNull(index, Types.OTHER)` worked for me.

**Comment by vlsi** [comment]
>@vlsi : setNull(index, Types.OTHER) worked for me.

It is not the proper way to push types with names.

Consider `select 1 from ... where ? is null`

`setNull(index, Types.OTHER)` won't help you there

**Comment by lukaseder** [comment]
Yes you're right thanks for the pointer

**Comment by lukaseder** [comment]
Added a cast around known UUID bind variables. Your query will then be:

```sql
select 1 from ... where cast(? as uuid) is null
```

**Comment by vlsi** [comment]
> Added a cast around known UUID bind variables. Your query will then be:

Of course "adding cast" solves the problem, however  `where ? is null` should work with `setNull(column, type, typeName)`

**Comment by lukaseder** [comment]
Yes it would, but it would either depend on the linked fix in the driver (not everyone will upgrade immediately), or on specifying the correct `oid` as the `type` argument (which would have to be done just as in the fix). Since the `DefaultUUIDBinding` is used by default in jOOQ's internals, it is very easy to add a cast around the bind variable. Plus, the generated SQL will also work out of the box when jOOQ doesn't execute the query, e.g. when someone runs `Query.getSQL()` and wants to execute that on e.g. Spring or Hibernate.

**Comment by vlsi** [comment]
>  it would either depend on the linked fix in the driver

It would not. Current implementation in pgjdbc is it just ignores `typeName`
That is `setNull(column, Types.OTHER, "uuid")` is exactly the same as `setNull(column, Types.OTHER)` in current driver, and it will transparently support `where ? is null` as the driver side is fixed.

**Comment by lukaseder** [comment]
As I said, it would either depend on the fix, *or* on specifying the correct `oid` as the `type` argument. :) I'm more in favour of simply casting...

**Comment by lukaseder** [comment]
(what I'm trying to say is: I don't see the value of doing this in a eventually forward compatible way, possibly risking a regression elsewhere or with other JDBC drivers when there's a better fix that works today and for everyone)

**Comment by vstepchik** [comment]
Hi, I've tried the v3.11.2, doing the `runExists` with the `WHERE` condition checking if there is a row with uuid column containing a null value, and still got this exception:

```
org.springframework.jdbc.BadSqlGrammarException: jOOQ; bad SQL grammar [select 1 as "one" from "main_schema"."sample_table" where ("main_schema"."sample_table"."deleted" = false and "uuid_type_fk" = cast(? as varchar))]; nested exception is org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = character varying
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 99
```

DDL:
```sql
create table sample_table (
  id           uuid                    not null primary key,
  uuid_type_fk uuid references other_table,
  deleted      boolean default false   not null
);
```
Is this a bug or me doing something wrong?

**Comment by lukaseder** [comment]
@vstepchik Would you mind creating a new issue with complete details and steps to reproduce your case? Thanks!

**Comment by vstepchik** [comment]
@lukaseder #7670 Thanks!
