### ISSUE TITLE
Let Cursor extend Formattable

### ISSUE THREAD

**Issue by deventh** [jOOQ/jOOQ#7353]
Now we have export functionality `org.jooq.Result#formatCSV(Writer writer)` only for the fetched completely in memory data: `org.jooq.Result`.
Would be nice to have the same for fetched lazy as stream to save memory for the large data sets: `org.jooq.Cursor` directly to the output `java.io.Writer`

**Comment by lukaseder** [comment]
Thanks for your suggestion. That makes sense. We'll try to implement it in the next version

**Comment by lukaseder** [comment]
Via #7355, the API can be pulled up from `Result` into a common `Formattable` API. The implementation is the same, both will iterate over a set of rows, except that the iteration is repeatable in `Result`, and non-repeatable in `Cursor`

**Comment by lukaseder** [comment]
... hmm, this `Formattable` type could extend to all the other operations too, including `intoGroups()` or `intoMap()`, etc. There's no need to keep entire intermediate `Record` instances around if all we care about is a `Map<String, String>`...
