### ISSUE TITLE
IndexOutOfBounds when trying to do a MERGE with SELECT in Postgres

### ISSUE THREAD

**Issue by joe776** [jOOQ/jOOQ#7359]
### Expected behavior and actual behavior:
Expected: A proper error message
Actual: IndexOutOfBoundsException at MergeImpl.java:1332

### Steps to reproduce the problem:
Create a MERGE statement that uses a SELECT clause and try to execute the statement.

I only later realized that this kind of statement is not supported, however there could be a better error message. There is already a check for that [here](https://github.com/jOOQ/jOOQ/blob/b2f9a4e5ad55b71b760a73f1e64c56cc2cce2fb6/jOOQ/src/main/java/org/jooq/impl/MergeImpl.java#L1349), however, it is only executed after already trying to access the empty `upsertValues` field. Could this check be made earlier to avoid the exception?

From the code, the same seems to be true for `toSQLMySQLOnDuplicateKeyUpdate` just above that.

### Versions:

- jOOQ: 3.10.6
- Java: 1.8
- Database (include vendor): Postgres
- OS: macOS 10.13.3
- JDBC Driver (include name if inofficial driver): Postgres 42.2.2

**Comment by lukaseder** [comment]
Thanks for your report

> Create a MERGE statement that uses a SELECT clause and try to execute the statement.

Would you mind showing an actual example of such a statement?

**Comment by joe776** [comment]
A simplified version looks like this:
```
Select<?> data = DSL
    .select(DSL.inline(id), DSL.inline(key), DSL.inline(value))
    .where(DSL.not(DSL.exists(DSL.select(DSL.one())
            .from(TABLE)
            .where(TABLE.KEY.eq(key)))))
    .union(DSL.select(TABLE.ID, TABLE.KEY, DSL.inline(value))
            .from(TABLE)
            .where(TABLE.KEY.eq(key));

context.mergeInto(TABLE)
    .columns(TABLE.ID, TABLE.KEY, TABLE.VALUE)
    .select(data)
    .execute();
```
`id` ist the primary key generated in the code during the insert or update. So we check for existence of the row through the external `key`. I believe we ended up with a query like this, because the KEYS clause is also not supported in Postgres (or H2 which we use for quick unit testing).
We are now doing it in two queries; try to update, if no rows are affected insert.
