### ISSUE TITLE
Deprecate <SQLDialect>DataType classes

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7375]
Each `SQLDialect` has a `<SQLDialect>DataType` class which lists the translation of the `SQLDataType` types to the specific dialect and registers these translations in the `DefaultDataType`'s internal cache. In a future version, this internal cache will be improved through #5713 (quite a tricky change) as the current implementation has a few concurrency issues, which can lead to dead locks in the worst case: #3777

There is no reason why users should reference these types directly. They are used only for internal reasons. We should deprecate all these classes accordingly, and eventually move them to the internals. Deprecation is the safest way to prevent further deadlocks without changing anything.

**Comment by jklingsporn** [comment]
Hi,
I was recently switching to 3.11. and after running the code-generation  saw some compiler warnings, that the generated `Table` classes use one of the deprecated `SQLDataTypes`. So if those types are referenced in the generated classes you can hardly reduce the visibility scope?

**Comment by lukaseder** [comment]
Thanks for your message, @jklingsporn. Those types should no longer be referenced by generated code. Did you re-generate your code using the latest version of the code generator? If so, how can such a reference be reproduced?

**Comment by jklingsporn** [comment]
Here you go: https://github.com/jklingsporn/jooq-test

**Comment by lukaseder** [comment]
Thanks, but I only see the `SQLDataType` being referenced in that project, not e.g. the `PostgresDataType`...?

**Comment by jklingsporn** [comment]
I guess you are right - but that type is also deprecated.

**Comment by lukaseder** [comment]
Nope :) https://www.jooq.org/javadoc/latest/org/jooq/impl/SQLDataType.html

Compare to: https://www.jooq.org/javadoc/latest/org/jooq/util/postgres/PostgresDataType.html

**Comment by lukaseder** [comment]
Cheers to you too! :-)

**Comment by etiennestuder** [comment]
> There is no reason why users should reference these types directly. They are used only for internal reasons.

We have a custom function in Postgres with the signature 
```
CREATE OR REPLACE FUNCTION foo(TEXT [])
   ...
```

and in the Javacode, we define a field like this
```
        DSL.field("foo({0})", PostgresDataType.TEXT, binding);
```

are you saying we should not do it this way? If so, what would be the proper way in the Java code that does not refer to PostgresDataType.TEXT?

**Comment by lukaseder** [comment]
@etiennestuder Use `SQLDataType.CLOB`

**Comment by etiennestuder** [comment]
Thanks, @lukaseder!
