### ISSUE TITLE
Error in PLSQL procedure if CLOB OUT PARAMETER is > 32kb

### ISSUE THREAD

**Issue by DiabolusExMachina** [jOOQ/jOOQ#7380]
### Expected behavior and actual behavior:

Hello. we have a procure like this. 
```
PROCEDURE createWrapper(
  p_id                       IN     NUMBER
  ,p_text                   OUT    CLOB);
```
If we call it and the p_text CLOB is > 32kb we get the following error. If the clob is < 32kb everything is fine. 

> org.jooq.exception.DataAccessException: SQL [{ call "TEST"."SCHEMA"."createWrapper"(?, ?) }]; ORA-06502: PL/SQL: numerischer oder Wertefehler ORA-06512: in Zeile 1
> [04.04.18 09:36:06:408 CEST] 00000093 SystemErr     R 	at org.jooq_3.10.2.ORACLE11G.debug(Unknown Source)
> [04.04.18 09:36:06:408 CEST] 00000093 SystemErr     R 	at org.jooq.impl.Tools.translate(Tools.java:2197)
> [04.04.18 09:36:06:408 CEST] 00000093 SystemErr     R 	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:704)
> [04.04.18 09:36:06:409 CEST] 00000093 SystemErr     R 	at org.jooq.impl.AbstractRoutine.executeCallableStatement(AbstractRoutine.java:502)
> [04.04.18 09:36:06:409 CEST] 00000093 SystemErr     R 	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:340)
> [04.04.18 09:36:06:409 CEST] 00000093 SystemErr     R 	at org.jooq.impl.AbstractRoutine.execute(AbstractRoutine.java:317)

### Steps to reproduce the problem:
Call a plsql procedure with an CLOB out field that is greater than 32kb
### Versions: 
- jOOQ:3.10.2
- Java: 1.7
- Database (include vendor): Oracle 11
- JDBC Driver (include name if inofficial driver): ojbdc7

**Comment by lukaseder** [comment]
Thank you very much for your report. Interesting - we're mostly binding `CLOB` types as `String` including using `CallableStatement.getString()` in this particular case. However, we've run into 1-2 issues in the past, mostly related to encoding when the size of the LOB is around the limits of either the SQL engine (4000 bytes) or the PL/SQL engine (32kb). Can you confirm this happens with any size of CLOB larger than 32kb (e.g. some MBs)?

A workaround would be to apply your own custom data type binding, e.g. by applying `org.jooq.impl.ClobBinding` to this particular type (or to any `CLOB` if you prefer). This binding will still fetch the `CLOB` as a `String`, i.e. fetch it completely into memory.

**Comment by lukaseder** [comment]
The problem is that the OUT parameter is registered as `Types.VARCHAR` when it should be registered as `Types.CLOB`.

**Comment by DiabolusExMachina** [comment]
Thank you very much for fixing this. Is there any change that there will be a 3.10.7 Release with this Bugfix?

**Comment by lukaseder** [comment]
Yes, I can schedule a downport of the fix to 3.10.7: #7408. I cannot promise a release date yet. 3.10.7 doesn't look too interesting yet: https://github.com/jOOQ/jOOQ/milestone/157

Have you tried applying the workaround mentioned in a previous comment? https://github.com/jOOQ/jOOQ/issues/7380#issuecomment-378638156

**Comment by DiabolusExMachina** [comment]
Great thanks again. 

Some of my colleges are currently trying your suggested workaround. I'll ask them if it works for them.

**Comment by DiabolusExMachina** [comment]
I can confirm that the workaround does work.
