### ISSUE TITLE
Issues with routine generation for PostgreSQL

### ISSUE THREAD

**Issue by erikthered** [jOOQ/jOOQ#7391]
### Expected behavior and actual behavior:
We have several custom routines in our PostgreSQL database that I would expect the codegen to generate classes for under the `routines` package, but classes for these are being generated under the `tables` and `tables.records` packages.  Functions from the [tablefunc](https://www.postgresql.org/docs/9.6/static/tablefunc.html) extension are also not getting picked up as routines

We do have two custom functions (along with the functions from the `uuid-ossp` extension) which are showing up correctly under the `routines` package. 

### Steps to reproduce the problem:
Run the code generator against a local copy of our database.

### Versions:

- jOOQ: 3.10.6
- Java: OpenJDK Runtime Environment (Zulu 8.25.0.1-macosx) (build 1.8.0_152-b16)
- Database (include vendor): PostgreSQL 9.6.5
- OS: MacOS 10.13.3
- JDBC Driver: `org.postgresql:postgresql:42.2.1`

**Comment by lukaseder** [comment]
Thanks for your message. By default, table valued functions are generated as tables by jOOQ as this adds more value overall to using them. You can turn off this code generator feature by specifying:

```xml
<configuration>
  <generator>
    <database>
      <tableValuedFunctions>false</tableValuedFunctions>
    </database>
  </generator>
</configuration>
```

See also:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-table-valued-functions

Hope this helps
