### ISSUE TITLE
Rename jooq-meta and jooq-codegen packages to avoid conflicts in JPMS

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7419]
In the Java 9 JPMS, it is not allowed for multiple modules to use the same package names. We're currently doing this a few times, e.g. by reusing `org.jooq.util` in all of `jooq.jar`, `jooq-meta.jar`, `jooq-codegen.jar`.

Changing package names constitutes a major incompatible change and should not be done lightheartedly. In this case, we have to make an exception, renaming packages only in `jooq-meta.jar` and `jooq-codegen.jar`, leaving those in `jooq.jar` untouched.

All packages in the above modules will have the following new prefixes:

- `jooq-meta.jar`: `org.jooq.meta`
- `jooq-meta-extensions.jar`: `org.jooq.meta.extensions`
- `jooq-codegen.jar`: `org.jooq.codegen`
- `jooq-codegen-maven.jar`: `org.jooq.codegen.maven`

This is a prerequisite to modularise jOOQ: #4699

**Comment by akawalsky** [comment]
My dependencies look like

```
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>${org.jooq.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jooq.meta</groupId>
            <artifactId>jooq-meta</artifactId>
            <version>${org.jooq.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jooq.codegen.maven</groupId>
            <artifactId>jooq-codegen-maven</artifactId>
            <version>${org.jooq.version}</version>
        </dependency>
```

but when running `mvn install` its not finding these in any public maven repo. Strangely, running this in intellij gives me no issues. Any idea what might be wrong here?

**Comment by lukaseder** [comment]
@akawalsky : Only the package names (inside these artifacts) have been renamed. No artifacts or groups have been renamed. The `<groupId>org.jooq</groupId>` should be used everywhere
