### ISSUE TITLE
Code generation XML config snippets should refer to XMLNS in manual

### ISSUE THREAD

**Issue by bobtiernay-okta** [jOOQ/jOOQ#7420]
### Expected behavior and actual behavior:

For novices and experts alike, having autocomplete of xml elements in the IDE is very convenient and helps exploration. The documentation makes no mention of the XML Schema (that I could find). It would be instructive to add an example to the docs in that regard:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.10.0.xsd"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.jooq.org/xsd/jooq-codegen-3.10.0.xsd http://www.jooq.org/xsd/jooq-codegen-3.10.0.xsd">
...
```

**Comment by lukaseder** [comment]
Thanks for the suggestion. You're right, we're frequently doing this for the other XML content as can be seen in the single page manual (search for "xsd"):
https://www.jooq.org/doc/latest/manual-single-page

Certainly makes sense for the code generation XML snippets, too. I think the `xmlns` link will suffice, the `xsi` namespace would make the snippets a bit noisy.

**Comment by lukaseder** [comment]
Fixed. Manual will be updated with the next nightly build. Thanks again for the suggestion.
