### ISSUE TITLE
Stop rendering "FROM dual" in MySQL 8+ and MariaDB 10.4+

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7421]
Some databases can usually do without a `FROM` clause, but sometimes, in some edge cases, do require it. Like Teradata when using set operations. 

This is OK:

```sql
SELECT 1
```

This is invalid:

```sql
SELECT 1 UNION ALL SELECT 2
```

It would be great if the peculiarities of all databases would be taken into account and `FROM` would be generated only if strictly required. MySQL is similar and requires a `FROM dual` clause in some edge cases.

See: https://stackoverflow.com/q/49901803/521799

**Comment by knutwannheden** [comment]
According to MySQL's [documentation](https://dev.mysql.com/doc/refman/8.0/en/select.html):
> `DUAL` is purely for the convenience of people who require that all `SELECT` statements should have `FROM` and possibly other clauses. MySQL may ignore the clauses. MySQL does not require `FROM DUAL` if no tables are referenced.
It would be interesting to see which edge cases require the `FROM DUAL` clause. Our integration tests all seem to be fine without it.

**Comment by lukaseder** [comment]
> It would be interesting to see which edge cases require the `FROM DUAL` clause. Our integration tests all seem to be fine without it.

What are your findings here, @knutwannheden ?

**Comment by knutwannheden** [comment]
> What are your findings here, @knutwannheden ?

I didn't find any (our integration tests all work fine without the `FROM DUAL` clause). Are you aware of any?

**Comment by lukaseder** [comment]
I never documented them. I just remember that they appeared with complex joins and unions. Did you try with MySQL 5.7 as well?

**Comment by knutwannheden** [comment]
> Did you try with MySQL 5.7 as well?

No, I only tested with MySQL 8.0. But I could test this with MySQL 5.7 as well.

**Comment by lukaseder** [comment]
MySQL 8 implemented a truck load of improvements, so quite possibly, this has been cleaned up by MySQL. I'm positive that `FROM` was necessary in edge cases some time ago, but that might have also been in times of 5.5, and I never checked again in the last 10 years.

**Comment by lukaseder** [comment]
We still support MySQL 5.7, so I'd like to be sure about that version as well. If there are also no regressions in 5.7, then I'm fine with removing the requirement of a `FROM` clause (and `DUAL` table) in MySQL in the next minor release.

**Comment by knutwannheden** [comment]
To be on the safe side we could also just remove the `FROM DUAL` clause for MySQL 8.0.

**Comment by lukaseder** [comment]
Yes we could.

**Comment by lukaseder** [comment]
I've changed this issue to be strictly about MySQL dialects. I think in other dialects that currently require the `FROM` clause, the discussion is more complicated.

**Comment by knutwannheden** [comment]
I can confirm that the `FROM DUAL` clause is indeed required in many cases for MySQL 5.7.

**Comment by lukaseder** [comment]
Could you list 2-3 examples for sake of documentation?

**Comment by knutwannheden** [comment]
Apparently in MySQL 5.7 a query with a `WHERE` clause must also have a `FROM` clause. Same is true for the `GROUP BY` clause. So the following queries won't parse, although this is valid in MySQL 8.0:
```sql
select 1
where 1=1;

select 1
group by 1;
```
Interestingly enough this restriction does not apply to the `ORDER BY` clause.

Note: There could be more cases when a `FROM` clause must be present in MySQL 5.7.

**Comment by lukaseder** [comment]
> Interestingly enough this restriction does not apply to the `ORDER BY` clause.

From a SQL standard perspective, the idea is that `WHERE` and `GROUP BY` are part of the `<table expression>`, whereas `ORDER BY` is not.

**Comment by lukaseder** [comment]
This change has produced a very significant regression in jOOQ 3.13 for MySQL 5.7: https://github.com/jOOQ/jOOQ/issues/9832

The code generator currently works with `SQLDialect.MYSQL`, which corresponds to `MYSQL_8_0_19`, where `DUAL` is no longer needed. There's currently no way to discover the dialect version dynamically, nor to set it explicitly.

Further discussion in issue #9832

**Comment by lukaseder** [comment]
Given the significant regression (https://github.com/jOOQ/jOOQ/issues/9832) caused by this improvement, I'll revert it for 3.13. We can still consider re-implementing this improvement in the future, but with the code generator in mind.

**Comment by lukaseder** [comment]
Having another look at this - after all, we would like to move on with our generated SQL syntax, and stop rendering `FROM dual` if it isn't really required.

The problem in #9832 is the call to `DSLContext::fetchExists`

```java
    public boolean fetchExists(Select<?> query) {
        return selectOne().whereExists(query).fetchOne() != null;
    }
```

If we change that to:

```java
    public boolean fetchExists(Select<?> query) {
        return fetchValue(field(exists(query)));
    }
```

Then the queries run by the code generator will continue to run also on older versions of MySQL and MariaDB. At the same time, we can implement #7421 and move our generated SQL forward for those users who use newer versions of their RDBMS.

To stay on the safe side in the commercial distributions of the code generator, which still officially support those versions, we can change the initialisation of the `DSLContext` to this:

```java
    protected DSLContext create0() {
        SQLDialect dialect = JDBCUtils.dialect(getConnection());
        return DSL.using(getConnection(), dialect.family() != MARIADB ? MARIADB : dialect);
    }
```

**Comment by lukaseder** [comment]
The reason why we had regressions for MariaDB in the commercial distributions is this: https://github.com/jOOQ/jOOQ/issues/11216

**Comment by lukaseder** [comment]
Commit is here: https://github.com/jOOQ/jOOQ/commit/b7425905f3172ec57890b5862e14f8d930862734
