### ISSUE TITLE
Excess ORDER BY "rn" generated in ORACLE11G dialect when LIMIT is used without ORDER BY

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7427]
This query

```java
Select<Record1<Integer>> q = DSL.using(connection, SQLDialect.ORACLE11G)
   .selectOne()
   .limit(1)
   .offset(1);

System.out.println(q);
```

Produces this SQL

```sql
select "v0" "one"
from (
  select 
    "x"."v0", 
    rownum "rn"
  from (
    select 1 "v0"
    from dual
  ) "x"
  where rownum <= (1 + 1)
)
where "rn" > 1
order by "rn"
```

The `order by "rn"` clause isn't strictly necessary when the user query doesn't have any explicit ordering. We probably shouldn't generate it

And the result is correct as well. Do you perhaps have an example query where this fails for you?

**Comment by bubna22** [comment]
i have met this trouble in 3.10.2

**Comment by lukaseder** [comment]
This appears to be a regression introduced with #5068. It has no functional effects but the execution plan turns out to be much worse with the unnecessary `ORDER BY` clause
