### ISSUE TITLE
Let ResultQuery return immutable lists

### ISSUE THREAD

**Issue by romnempire** [jOOQ/jOOQ#7449]
### Expected behavior and actual behavior:

ResultQuery is returning me mutable lists.  I can't think of a good reason anyone would want to be mutating those lists?  I know this is more of a style thing than anything else, but in case nobody had really thought about it, just wanted to flag.

### Steps to reproduce the problem:

call `<E> List<E> fetch(RecordMapper<? super R, E> mapper)` on some ResultQuery.  Call `add()` on the returned list.

### Versions:

- jOOQ: 3.10.6
- Java: 1.8.0_131
- Database (include vendor): postgres 10.1 from brew
- OS: high sierra 10.13.4
- JDBC Driver (include name if inofficial driver): 42.1.4

**Comment by lukaseder** [comment]
Thanks for your report. Indeed, a lot of things in jOOQ are mutable, which, after closer inspection, should be immutable instead. There are a few other open issues in this area that are due for jOOQ 4.0 (no release date yet). I'll add your suggestion to the things to be considered.

**Comment by lukaseder** [comment]
In the meantime, `Result` has a few other usages than just being returned from a `ResultQuery`, including users creating custom results with `DSLContext::newResult`, e.g. for the `MockDataProvider` SPI.

With that in mind, and there not being a pressing reason to change the behaviour, I'll reject this.
