### ISSUE TITLE
Deprecate SEEK BEFORE

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7461]
The `SEEK BEFORE` clause doesn't really work (yet). It is quite hard to fix: #6380.
Until it is fixed, we should deprecate it to clearly indicate that it isn't working as expected.

**Comment by mbenson** [comment]
I am attempting to implement bidirectional paging by inverting the seek logic when navigating to the previous page. Is there a well-understood approach for me to manually implement proper "seek before" functionality?

**Comment by lukaseder** [comment]
Thanks for your nice words. The easiest way to invert seek is to invert order by and to revert the order of the result set again in the client. Essentially, just what is written in #6380.

We'll undeprecate "seek before" at some point in the future by fixing #6380, but I think that this issue and many others will be a lot easier to fix / implement, after some internal model redesign.

**Comment by mbenson** [comment]
I did end up following to #6380 and actually had been planning to do something like this before finding `#seekBefore()`. Thanks!
