### ISSUE TITLE
Make ambiguous field match throw rather than log a warning in Fields.class

### ISSUE THREAD

**Issue by vojtapol** [jOOQ/jOOQ#7462]
## Problem
I understand that it is useful for many users to be relaxed in case of ambiguous column matching. In our case though I believe it is always an error. 

[Related line in the `Fields.class`](https://github.com/jOOQ/jOOQ/blob/b2f9a4e5ad55b71b760a73f1e64c56cc2cce2fb6/jOOQ/src/main/java/org/jooq/impl/Fields.java#L131)

We coerce a general `Record` type into generated table record like so:
```java
CustomerRecord customerRecord = record.into(CUSTOMER);
```
If the `record` was a result of a badly constructed query the `customerRecord` can now end up with invalid values in certain fields. Many of our tables have a `name` column so the ambiguity is quite possible.

## Solution
I would like to propose an addition of a feature flag that would turn the warning log (see linked code above) into an exception.

**Comment by lukaseder** [comment]
Thanks for your suggestion. Totally agree. This is a duplicate of #4477
