### ISSUE TITLE
NullPointerException in values

### ISSUE THREAD

**Issue by lucasbarrossantos** [jOOQ/jOOQ#7486]
### Steps to reproduce the problem:

```java
for (Record immobile: immobileResult) {
Record entity = sql_server
                        .select(field("id")).from(table("entity"))
                        .where(cast(field("version"), String.class).eq(cast(immobile.getValue("entity_id"), String.class)))
                        .fetchAny();

create
   .insertInto(field("entidade_id"))
   .values(entity.getValue("id")) // NullPointerException
.execute();
}
```

### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lucasbarrossantos** [comment]
Yes, but when there is no reference, getValue ("") does not appear in list and gives NullPointerException error

**Comment by lucasbarrossantos** [comment]
I realized that the Result <Record> resulted; only appears which is not null in the database

**Comment by lukaseder** [comment]
I'm not sure if I understand. Is the `entity` reference null or not? If not, can you please post a stack trace?

**Comment by lucasbarrossantos** [comment]
It turns out that if any data is null then it does not appear in the Record collection. And so it gives error when I try to access the object by r.getValue (""), because it does not bring

**Comment by lukaseder** [comment]
Yes, nothing is equal to `null` in SQL. Here's a good explanation about SQL's three valued logic:
https://modern-sql.com/concept/three-valued-logic

Anyway. Your logic should handle the case where `entity == null`
