### ISSUE TITLE
Default Temporal -> OffsetDateTime conversion can use incorrect offset

### ISSUE THREAD

**Issue by tomdcc** [jOOQ/jOOQ#7487]
### Expected behavior and actual behavior:

Code started not using our defined converter due to #6794. Instead we were getting the default conversion. This was returning an OffsetDateTime that was 1 hour different to the expected date, which started tripping our tests.

Root of the problem is [here](https://github.com/jOOQ/jOOQ/blob/version-3.10.7/jOOQ/src/main/java/org/jooq/tools/Convert.java#L1094) I think:

``` java
return (X) new Timestamp(time).toLocalDateTime().atOffset(OffsetDateTime.now().getOffset());
```

I'm executing this in TZ `Australia/Adelaide`. The value provided was an `Instant`  with value `2018-01-17T12:00:00Z`. The returned value was an `OffsetDateTime` of `2018-01-17T22:30+09:30`. The time has moved forward 10.5h (correct) but the offset is only 9.5 hours (incorrect). On `2018-01-17`, the offset for `Australia/Adelaide` was `+10:30` as we have daylight savings then. `OffsetDateTime.now().getOffset()` is giving the offset now, rather than the offset at the time represented by the value. `new Timestamp(long).toLocalDateTime()` is getting it right, though, and the two are out of sync.

Note that there are a few places in that class that `OffsetDateTime.now()` is being used - they're probably all affected.

### Steps to reproduce the problem:

Convert an `Instant` to an `OffsetDateTime` in a TZ with daylight savings that represents a date when the TZ offset is different to now due to daylight savings.

### Versions:

- jOOQ: 3.10.1
- Java: 1.8
- Database (include vendor): Postgres 10.3
- OS: Mac OS
- JDBC Driver (include name if inofficial driver): Official Postgres

**Comment by lukaseder** [comment]
Closing this as worksforme for the time being. Feel free to reopen if the problem persists.

**Comment by lukaseder** [comment]
(Notice, we have a template to create MCVE's now, in case this helps: https://github.com/jOOQ/jOOQ-mcve)
