### ISSUE TITLE
Nullability is not correctly generated for Postgres JSONB columns

### ISSUE THREAD

**Issue by arlampin** [jOOQ/jOOQ#7500]
### Expected behavior and actual behavior:
Expected: A database NOT NULL column is generated with `.nullable(false)`
Actual: It's not.

### Steps to reproduce the problem (include example code if possible):
In SQL DDL I have
```
create table Foo (
  ...
  filter_content JSONB NOT NULL
  ...
)
```

But the resulting jOOQ TableImpl
```
public final TableField<Foo, JsonNode> FILTER_CONTENT = createField("filter_content", org.jooq.impl.DefaultDataType.getDefaultDataType("jsonb"), this, "", new JsonbBindings());
```
(JsonNode is from Jackson, JsonbBindings is a custom binding)

I haven't tested with other vendor specific types than JSONB.

### Versions:

- jOOQ: 3.10.6
- Java: 1.8.0_172
- Database (include vendor): PostgreSQL 10.3
- OS:
- JDBC Driver (include name if inofficial driver): PostgreSQL JDBC 42.2.2

**Comment by lukaseder** [comment]
Thanks a lot for reporting this. Will look into this soon. It probably isn't related to the JSONB type, but will happen with all "unknown" types.

**Comment by lukaseder** [comment]
... I'm going to assume that default values are also affected

**Comment by lukaseder** [comment]
This is similar to #6241

**Comment by lukaseder** [comment]
Fixed.

This was a bit of a delicate change, depending also on other changes made recently for jOOQ 3.11, which is why I won't merge the change to 3.10 or older releases.
