### ISSUE TITLE
Support for SQL "create temporary table newTable LIKE oldTable including indexes/defaults/constraints" statements

### ISSUE THREAD

**Issue by ibribaliki** [jOOQ/jOOQ#7502]
SQL supports creating tables by other table's structure: create temporary table X LIKE y including ...(defaults, constraints.. )

Is it somehow supported in JOOQ?, or will be supported in the future? Because all I've found is support in create temporary table with column definitions, or by select query.

Thanks in advance

**Comment by lukaseder** [comment]
Thanks for the suggestion. Indeed, some databases support this kind of feature. The SQL standard knows:

```sql
CREATE TABLE x AS SELECT ...
```

So in order to emulate `CREATE TABLE x LIKE y`, simply `SELECT * FROM y`. This may or may not include defaults, constraints, etc.

We'll keep this idea on the roadmap to see if there is any further interest in the feature. Given how it may be difficult to emulate on all databases, if copying "advanced" metadata like defaults, constraints, etc. are involved, I don't want to prioritise this right now.

**Comment by ibribaliki** [comment]
Hi lukaseder. I understand what you say about the scope of interest and the prioritization of this feature. Here are the reasons why such feature could help me:

1. In my case, I wanted to create a table like y, but populate it from a combination of calculations & temporary table(which has another schema.. not the same as y). CREATE TEMPORARY TABLE x as (..) wouldn't help in this case. I'm aware of the fact that this can be achieved trickily, like executing this: create ... table x as (select * from y where false), so I'll get an empty table with the desired schema, but I prefer neater ways to do so.

2. I actually want to copy the defaults from the metadata. In my case, I use redshift with jooq so I want to copy the distkeys & sortkeys from the copied table. "including defaults" allows that.

**Comment by lukaseder** [comment]
1. I really don't see why the approach isn't neat enough. jOOQ 3.11 will even support the `WITH [ NO ] DATA` clauses (https://github.com/jOOQ/jOOQ/issues/7139). It's a standard, so neat by definition.
2. Yeah, that's cool, and I'll think about it. Right now, you could try getting the existing meta information, and creating DDL statements from them using `DSLContext.ddl()`. Not sure how easy it is to extract only the defaults, though.

**Comment by ibribaliki** [comment]
Your alternative solutions look great, but 
1. Redshift doesn't support CREATE TEMPORARY TABLE AS TABLE X WITH NO DATA, unfortunately. 
2. I wasn't familiar with DSLContext.ddl() until now. It's nice, but it indeed doesn't extract the defaults. In my case, it doesn't copy the sortkey/distkeys from the source table.

The only solution that works for me now is  
dslContext.execute("create temporary table X LIKE Y 
including defaults");

**Comment by lukaseder** [comment]
1. But jOOQ does :-P (and emulates it, see #7139)

**Comment by ibribaliki** [comment]
The technique you suggested in #7139 copies the schema, but it won't copy any other metadata(defaults, constraints).

Here's an example I've made, using both your technique and another technique that works for me:

Given a table "tablexx" with 2 columns, "sha1" and "userId":

```
select * from pg_table_def where tablename='tablexx' limit 5;;
 schemaname | tablename | column |          type          | encoding | distkey | sortkey | notnull 
------------+-----------+--------+------------------------+----------+---------+---------+---------
 pg_temp_64 | tablexx   | sha1   | character varying(255) | none     | t       |       0 | f
 pg_temp_64 | tablexx   | userid | bigint                 | none     | f       |       1 | f

```
^ here tablexx has a sortkey and a distkey.

Now I copy it using the technique you suggested:

```
CREATE TEMPORARY TABLE tablexxcopy as (select * from tablexx where 1=0);
SELECT
select * from pg_table_def where tablename='tablexxcopy';
 schemaname |  tablename  | column |          type          | encoding | distkey | sortkey | notnull 
------------+-------------+--------+------------------------+----------+---------+---------+---------
 pg_temp_64 | tablexxcopy | sha1   | character varying(255) | none     | f       |       0 | f
 pg_temp_64 | tablexxcopy | userid | bigint                 | none     | f       |       0 | f
(2 rows)
```

^ Neither the sortkey nor the distkey were copied.

Alternatively, this does copy them:

```
CREATE TEMPORARY TABLE tablexxcopy2 (like tablexx including defaults);
CREATE TABLE
select * from pg_table_def where tablename='tablexxcopy2';
 schemaname |  tablename   | column |          type          | encoding | distkey | sortkey | notnull 
------------+--------------+--------+------------------------+----------+---------+---------+---------
 pg_temp_64 | tablexxcopy2 | sha1   | character varying(255) | none     | t       |       0 | f
 pg_temp_64 | tablexxcopy2 | userid | bigint                 | none     | f       |       1 | f
(2 rows)
```

**Comment by lukaseder** [comment]
Yes, you're right, and I understand the use case, of course. What I suggested earlier were workarounds, not a solution. Do note, however, that I think it wouldn't be a bad idea to keep the meta data external to the schema somewhere and re-create the copies from scratch. What keeps you from remembering how you created the original table in the first place?

**Comment by tomdcc** [comment]
Also, Postgres (and maybe others, unsure) allows constructs like
```
CREATE TABLE foo (
  extra_column_1 int,
  extra_column_2 text,
  LIKE some_other_table
);
```
which are not covered currently.

**Comment by lukaseder** [comment]
I have created a new, separate issue where we discuss the feature and possible emulations more thoroughly, and without the distraction caused by my original confusion around this feature: #8860

Thanks again for your report. This is definitely something we want to look into in the near future.
