### ISSUE TITLE
Add support for PostgreSQL functions returning anonymous RECORD types

### ISSUE THREAD

**Issue by desiderantes** [jOOQ/jOOQ#7503]
### Expected behavior and actual behavior:
When returning RECORD from a PostgreSQL function, jOOQ picks it up as returning java.lang.Void instead of Record(Impl).

### Steps to reproduce the problem (include example code if possible):
With the following SQL:
```sql
CREATE TABLE custom_table (
  table_name TEXT           NOT NULL,
);

CREATE OR REPLACE FUNCTION custom_func()
  RETURNS RECORD AS $$
DECLARE retval RECORD;
BEGIN
  SELECT *
  FROM custom_table
  LIMIT 1
  INTO retval;
  return retval;
end;
$$
language plpgsql;
```
Run the codegen. The generated Routine, CustomFunc, has the following signature:

```java
public class CustomFunc extends AbstractRoutine<java.lang.Void>
```

### Versions:

- jOOQ: 3.10.7
- Java: 8
- Database (include vendor): postgreSQL
- OS: GNU/Linux
- JDBC Driver (include name if unofficial driver): official (pgjdbc)

**Comment by lukaseder** [comment]
Thanks for your report. Indeed, this is currently not supported (see also #6404). The problem is that jOOQ currently doesn't support nested records *in general* (see #2360). Your function would be similar to such a nested record.

An additional caveat from this particular syntax is the complete lack of type information on the returned record. E.g. this is possible:

```sql
CREATE OR REPLACE FUNCTION f_rec(c int)
RETURNS record AS
$$
  DECLARE
    v_result record;
  BEGIN
    IF c = 1 THEN
      SELECT 1 c1
      INTO v_result;
    ELSIF c = 2 THEN
      SELECT 1 c1, 2 c2
      INTO v_result;
    ELSE
      SELECT 1 c1, 2 c2, 3 c3
      INTO v_result;
    END IF;

    RETURN v_result;
  END;
$$ LANGUAGE plpgsql;

SELECT f_rec(1), f_rec(2), f_rec(3)
```

Yielding:

```
f_rec |f_rec |f_rec   |
------|------|--------|
(1)   |(1,2) |(1,2,3) |
```

Such lack of type safety currently cannot be represented in the jOOQ API easily. If you're always going to return `SELECT * FROM custom_table`, I recommend returning `SETOF custom_table`, instead.

**Comment by desiderantes** [comment]
What if I'm returning multiple `JOIN`t tables?

**Comment by lukaseder** [comment]
@desiderantes What do you mean by this?

**Comment by desiderantes** [comment]
What should the return type be for `SELECT * FROM table1 JOIN table2 ON table1.id = table2.other_id` ?

**Comment by desiderantes** [comment]
> Such lack of type safety currently cannot be represented in the jOOQ API easily

Why not? I mean, the alternative is just ignore the result type, which is wrong. At least a bag of data, like a Map<String,Object> or even Map<String, ByteArray> would be better than java.lang.Void.

**Comment by lukaseder** [comment]
Well, the main point which you seem to be missing is the fact that we simply don't support this type of function yet. I've only illustrated the difficulties in getting adding support right as an explanation. That doesn't change anything about the fact that the function is right now not supported. We might argue that it could have been better to generate `java.lang.Object` as the result type, and generate the functions as deprecated, but that seems to be a detail.

In any case, we will support these functions in the future.

Thanks

**Comment by lukaseder** [comment]
Having another look at this now, we support nested records in projections since jOOQ 3.15, so this might be a great addition.

**Comment by lukaseder** [comment]
In other words, this would be much better:

```sql
CREATE TABLE custom_table (
  table_name TEXT NOT NULL
);

CREATE OR REPLACE FUNCTION custom_func()
  RETURNS custom_table AS $$
DECLARE retval custom_table;
BEGIN
  SELECT *
  FROM custom_table
  LIMIT 1
  INTO retval;
  return retval;
end;
$$
language plpgsql;
```

**Comment by lukaseder** [comment]
Related feature request: https://github.com/jOOQ/jOOQ/issues/5405
