### ISSUE TITLE
Add support for Clickhouse

### ISSUE THREAD

**Issue by dimiii** [jOOQ/jOOQ#7539]
ClickHouse is an open source column-oriented database management system capable of real-time generation of analytical data reports using SQL queries.

https://clickhouse.com/

It has a JDBC driver, FYI: https://central.sonatype.com/artifact/com.clickhouse/clickhouse-jdbc

### Peculiarities

- [x] `CREATE TABLE` has a mandatory `ENGINE = ..` clause, and we need to generate a default. We'll use `MergeTree()` if there's a `PRIMARY KEY` and `Log()` if there isn't. This might be subject to future change.
- [x] `CREATE INDEX` has a mandatory `TYPE` clause. We'll default to `minmax` for now.
- [x] `JSON` support isn't really ready without the experimental `JSON` type: https://clickhouse.com/docs/en/sql-reference/data-types/json. E.g. it's very hard to nest `JSON` strings without running into quoting issues, like `["{\"a\":\"b\"}"]` when we want `[{"a":"b"}]`
- [x] Arrays can be primitive. E.g. `groupArray(id)` may produce an `int[]` type: https://github.com/jOOQ/jOOQ/issues/16448
- [x] Integration tests run all queries with this suffix: `settings join_use_nulls = 1, group_by_use_nulls = 1, aggregate_functions_null_for_empty = 1`. We won't tamper with ClickHouse's peculiarities by normalising the SQL, assuming users also add this suffix to get a more standard SQL experience.
- [x] `EXCEPT [ ALL ]` and `INTERSECT [ ALL ]` are not implemented correctly: https://github.com/ClickHouse/ClickHouse/issues/61529. We can't really "fix" this, though we'll generate `DISTINCT` on `except()` and `intersect()`.
- [x] Some window functions use wrong (non standard) default `RANGE` clauses, e.g. `LEAD` and `LAG`
- [x] Implicit column names from CTE or derived tables are unreliable as they might include a table name. We should auto-alias all CTE or derived table contents.

### Database features / missing features:

- No `UNIQUE` constraints
- No named `PRIMARY KEY` constraints
- No `FOREIGN KEY` constraints
- No identities

### Some bugs found:

**In the database**

- https://github.com/ClickHouse/ClickHouse/issues/60992
- https://github.com/ClickHouse/ClickHouse/issues/61004
- https://github.com/ClickHouse/ClickHouse/issues/61014
- https://github.com/ClickHouse/ClickHouse/issues/61391
- https://github.com/ClickHouse/ClickHouse/issues/61461
- https://github.com/ClickHouse/ClickHouse/issues/62166
- https://github.com/ClickHouse/ClickHouse/issues/62183

**In the JDBC driver**

- https://github.com/ClickHouse/clickhouse-java/issues/1625
- https://github.com/ClickHouse/clickhouse-java/issues/1626

### Missing features to work around:

- [x] https://github.com/ClickHouse/ClickHouse/issues/58242
- [x] https://github.com/ClickHouse/ClickHouse/issues/61020
- [x] https://github.com/ClickHouse/ClickHouse/issues/61195
- [x] `UNION .. ORDER BY` doesn't exist. `ORDER BY` and `LIMIT` are applied to individual queries, so we have to wrap the set operations in a derived table, see: https://clickhouse.com/docs/en/sql-reference/statements/select/union

### Other interesting features to support (maybe in the future)

- https://github.com/jOOQ/jOOQ/issues/16447

----
See also:
- https://github.com/jOOQ/jOOQ/discussions/14059

**Comment by lukaseder** [comment]
Thank you very much for your suggestion.

Right now, ClickHouse doesn't seem to have gained a lot of traction [1], so the cost/benefit ratio for an integration on our side is not favourable for going forward. We'll keep it in the back of our heads, though.

[1]: https://db-engines.com/en/ranking

**Comment by dimiii** [comment]
> is not favourable for going forward

So, there is no point in PR? You think it is going to be too difficult for a beginner from the side?
I thought I could manage it taking work on Vertica as an exemplar.

**Comment by lukaseder** [comment]
> So, there is no point in PR?

Thanks for asking first :) We wouldn't want to maintain the integration right now. 20% of the work is adding support for a new dialect. 80% (or even more) is maintaining it in the future.

> Do you think it is going to be too difficult for a beginner from the side? I thought I could manage it taking work on Vertica as an exemplar.

It's quite a bit of work (just added support for 4 new dialects over the past weeks), definitely possible, but:

1. Reviewing would be a tremendous amount of work for little gain in this case
2. You don't have the integration tests (they're closed source), so it's not really easy to judge whether your suggestions will be correct, or whether you're breaking anything for the other 25 dialects we're currently supporting.

Having said so, if you think an integration will add value to your business, you are more than welcome to fork jOOQ and maintain the integration on your side. I'll be happy to answer any questions you may have on the user group: https://groups.google.com/forum/#!forum/jooq-user

**Comment by lukaseder** [comment]
Looking into this, next for a jOOQ 3.15 integration.

**Comment by lukaseder** [comment]
Known issues will be collected here: https://github.com/jOOQ/jOOQ/issues/10792

**Comment by lukaseder** [comment]
A few moments into trying to add support, and there are quite the significant issues already, making me question adoption. E.g. the database has no constraints, nor `UPDATE` / `DELETE` statements. Also, there are quite a few deviations from standard SQL in `SELECT` alone:
https://clickhouse.tech/docs/en/sql-reference/statements/select/

This hints at a significant amount of effort in maintaining the integration tests and assessing which of the many jOOQ API features will not be supported.

Upvoters: What's your stake here / your expectations of having jOOQ support for Clickhouse?

**Comment by lukaseder** [comment]
I'll stop here, for now. I'm happy to discuss a sponsored project. Anyone interested, please reach out to sales@datageekery.com.

**Comment by PHameete** [comment]
Came here hoping to get lucky ;-) unfortunately not. I think ClickHouse is gaining popularity for analytical workloads. In my experience it is very fast, and can be a good option when you outgrow your single-node setup, or when you can benefit from reading data in parallel from multiple nodes.

Currently, the only way to query ClickHouse from Java is via JDBC. My hope was to be able to use JOOQ to write type-safe queries and to compose them programmatically. The alternative is generating SQL strings and putting them in prepared statements which is not great.

I'm not sure if this was already the case when you last checked their docs, but UPDATE and DELETE is supported in a non-standard way. See https://clickhouse.tech/docs/en/sql-reference/statements/alter/update/ and https://clickhouse.tech/docs/en/sql-reference/statements/alter/delete/

**Comment by lukaseder** [comment]
Thanks for your comment, @PHameete. After a few hours attempting to build a Clickhouse integration, I think it was safe to say that everything Clickhouse is pretty non-standard "SQL", as in: It looks kinda SQL-ish, but really isn't SQL. This makes an integration rather effortful. It could be done, sure, but cost/benefit for us as vendors is currently not very good - at least not under the assumption that we continue offering OSS dialects under our own OSS license.

We could break with that, of course, and offer commercial only support for Clickhouse. I'll review this option again for jOOQ 3.15

**Comment by PHameete** [comment]
Yes I can imagine that will be a big effort... I think jOOQ support would be great to have as a ClickHouse user, given that there are no alternatives to plain JDBC. Thanks for taking your time to consider Lukas :-)

**Comment by lukaseder** [comment]
Alright. Well, there's still some momentum in that area, given that we'll be adding support for at least BigQuery, Ignite, and Snowflake as well in jOOQ 3.15...

**Comment by lukaseder** [comment]
I'm afraid, I'll have to keep this in jOOQ 3.16 unless we can find budget from a sponsored project for this. (Coincidentally, a customer is going to sponsor Exasol support, so that will have priority)

**Comment by Madusudanan** [comment]
ClickHouse integration in jooq would be really useful. They have broken away from Yandex and they are a separate entity  - ClickHouse Inc and is gaining a lot of popularity ([Cloudflare, Cisco, Uber etc.,](https://clickhouse.com/docs/en/about-us/adopters) ). We are using it internally at locale.ai (The company I am currently working for) but unfortunately, we cannot contribute right now. Hope that it will be added in the future as it is very cumbersome to maintain hand written queries in analytical databases as the queries are pretty huge in genera.

**Comment by sendreams** [comment]
still unsupport? waiting for it

**Comment by sendreams** [comment]
@lukaseder There is hope, when will 3.19 be released

**Comment by tadas-subonis** [comment]
How it's coming along?

**Comment by fatekingsama** [comment]
Five years ago, I'm still waiting

**Comment by lukaseder** [comment]
Having another look for jOOQ 3.20

**Comment by georgymukha** [comment]
Hey! Is there any way to generate fields for ClickHouse? Working on new project which use ClickHouse instead of PSQL or MySQL and seems it doesn't work with CH properly. I can generate tables, but I cannot see any fields in the classes. And seems it will take long time to wait  JOOQ 3.20 as this issue was opened on Jun 1, 2018...
Thank you in advance!

**Comment by lukaseder** [comment]
@georgymukha: build 3.20.0-SNAPSHOT from github, or if you're licensed, access snapshot builds from here: https://www.jooq.org/download/versions

**Comment by AhmadDarwich** [comment]
Hello! Do you know approximately when it will be released?

**Comment by lukaseder** [comment]
@AhmadDarwich approximately this year

**Comment by NINNiT** [comment]
Looking forward to this!

**Comment by lukaseder** [comment]
I will release the status quo of the `SQLDialect.CLICKHOUSE` in 3.20 as an "experimental" dialect. More work will be done in the future:

- https://github.com/jOOQ/jOOQ/issues/17461

ClickHouse is very different from other dialects both in terms of syntax and behaviour, so I'm not very confident that the existing implementation is complete. I don't really have a very clear picture with respect to `NULL` handling, for example, which seems *very* weird, compared to *all* the other dialects I've seen so far.

Users are advised that jOOQ may incompatibly change behaviour to further normalise `NULL` handling in the future - or not. This hasn't been decided yet.
