### ISSUE TITLE
Add ResultQuery.fetchLazy(Consumer<? super Cursor<R>>)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7542]
Idea from the manual discussion:
https://www.jooq.org/doc/latest/manual/sql-execution/fetching/lazy-fetching/#comment-3928277577

To avoid try-with-resources calls, which break the API fluency, we could have auto-closing methods that pass the result as a `Consumer<...>` type, rather than returning the type, so

```java
DSL.using(configuration)
   .select(...)
   .from(...)
   .fetchLazy(cursor -> {
       cursor.fetchNext();
       ...
       // No need to close the cursor, will be closed upon leaving the Consumer
       // Regardless if the cursor is consumed completely, or if there's an exception
   });
```

A similar API could be implemented for `fetchStream()` and other `AutoCloseable` returning methods.

Perhaps, instead of overloading the method, it would be better to give this type of method a new name

**Comment by lukaseder** [comment]
Any exception between the `fetchLazy()` call and the final consumption of each individual record would result in a resource leak, I'm afraid. But perhaps, that's missing your point? Or, perhaps you're missing the point of this issue? :-)

**Comment by w25r** [comment]
You are right, my mistake.  It's really a separate issue.  The try-with-resources makes the code clunky, and needing to handle the incrementing of the cursor makes the code clunky, and my solution only addresses the latter.  So ideally BOTH would be done, and we could combine the solutions.

**Comment by lukaseder** [comment]
Alright, so let's restart then. Would you mind creating a new issue and start with the use-case description? We can then still proceed to discussing potential solutions...

**Comment by lukaseder** [comment]
I don't think we really need such a new API. Procedural usage of `Cursor` has always been possible with `fetchLazy()`, and a more FP approach can be implemented via `fetchStream()`. Using jOOλ, or other streaming libraries, it's possible to turn the stream into chunks.

Closing this as won't fix.
