### ISSUE TITLE
Setting role with ExecuteListener::renderEnd fails

### ISSUE THREAD

**Issue by chevalleyc** [jOOQ/jOOQ#7544]
### Expected behavior and actual behavior:
The goal is to set the role on a session by prepending an arbitrary query with 'SET ROLE xyz' by invocation of renderEnd.This mechanism does not return the expected query result or throw and exception.
### Steps to reproduce the problem (include example code if possible):
Example (hard coded stuff)

#### SettingRoleListener

```
public class SettingRoleListener extends DefaultExecuteListener {
...
    @Override
    public void renderEnd(ExecuteContext executeContext) {
        executeContext.sql("SET ROLE postgres;"+executeContext.sql());
    }
}
```
#### Invocation (example than can be easily tried...)
```
        DSLContext context = testDomainAccess.getContext();
        ExecuteListenerProvider executeListenerProvider = new DefaultExecuteListenerProvider(new SettingRoleListener(true, "postgres", new String[]{}));
        context.configuration().set(executeListenerProvider);
        Result result = context.fetch("SELECT table_name FROM information_schema.tables WHERE table_schema='public';");
        System.out.println(result);
```

##### with prepending as above
```
+------------+
|UPDATE_COUNT|
+------------+
|           0|
+------------+
```

##### Without prepending (renderEnd commented out, or 'SET ROLE...` removed)

```
+---------------------------------+
|table_name                       |
+---------------------------------+
|aql_temp_result                  |
|catalog                          |
|catalog_interfaces               |
|catalog_reports                  |
|catalog_templates                |
.......
```
### Versions:

- jOOQ: 3.10.0
- Java: 1.8
- Database (include vendor): Postgresql 10
- OS: Windows 7
- JDBC Driver (include name if inofficial driver):  postgresql-9.4-1204.jdbc42.jar

**Comment by lukaseder** [comment]
Thanks for your message.

Unfortunately, you cannot just prepend a statement to the one that jOOQ is executing and expect jOOQ to be able to get the "right" result. The way most JDBC drivers and the JDBC API work when sending "statement batches" (i.e. `;` separated statements in a single string) is that you have to iterate over the statement results as documented in this blog post:
https://blog.jooq.org/2017/07/13/how-i-incorrectly-fetched-jdbc-resultsets-again/

When using jOOQ, you could use `fetchMany()` for this:

```java
System.out.println(DSL.using(con).fetchMany(
    "SET SCHEMA 'information_schema'; SELECT * FROM tables"
));
```

Notice how each individual statement produces either:

- An update count
- A result set
- An exception

And `fetchMany()` will fetch them all.

Unfortunately, with `ExecuteListener`, you cannot intercept the `execute()` call and fetch/ignore that first update count. The solution would be to run a separate statement prior to executing jOOQ's statement - or better, to initialise the role in your data source / transaction manager.

I hope this helps.
