### ISSUE TITLE
ForcedType configurations should have include / exclude expressions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7545]
Currently, we can specify `<expression>` and `<types>` to forced type configurations, to specify which columns should be included. It would be useful to also be able to exclude some columns, just like we can include / exclude schemas / tables / columns in general.

Of course, negative lookaheads could be used as well, but they're more tedious to maintain.

**Comment by knutwannheden** [comment]
As part of this issue `<forcedType>` will be completed with the following new elements:
* `<includeExpression>` ("synonym" for `<expression>` and `<expressions>`),
* `<excludeExpression>`,
* `<includeTypes>` ("synonym" for `<types>`),
* and `<excludeTypes>`.

**Comment by knutwannheden** [comment]
Is the configuration validated against the schema? Would it make sense for the schema to only allow one of `<includeExpression>`, `<expression>`, and `<expressions>`?

**Comment by lukaseder** [comment]
> Is the configuration validated against the schema? 

Yes, `GenerationTool.load(InputStream)` validates it, see:

https://github.com/jOOQ/jOOQ/blob/962cfecf363fda90646c415c53c4d00a36bb1049/jOOQ-codegen/src/main/java/org/jooq/codegen/GenerationTool.java#L909-L923

> Would it make sense for the schema to only allow one of `<includeExpression>`, `<expression>`, and `<expressions>`?

I think that at some point in the past, I had used `<xsd:choice>` rather than `<xsd:all>` in the XSD, but if I'm not mistaken, XJC couldn't really handle this very well, so I've stopped using it. Also, other tooling, such as the Maven plugin, the Gradle plugin, or programmatic configuration do not pass by this validation logic, but assemble the `Configuration` object themselves, such that a warning somewhere further down the call stack in `GenerationTool` would be more useful anyway.

**Comment by spsheni** [comment]
@lukaseder , When is Version 3.12.0 planned? We needed this feature.

**Comment by lukaseder** [comment]
@spsheni Thank you very much for your message. 3.12 will be released in Q2 2019, no specific date planned yet.

You can work around this missing feature either by:

- Using negative lookaheads in your regular expressions
- Using programmatic code generation configuration: https://www.jooq.org/doc/3.11/manual/code-generation/codegen-programmatic

Hope this helps

**Comment by spsheni** [comment]
Thank you @lukaseder for your updates.
Our requirement was to force TINYINT(1) to Boolean in all tables. But few tables were in exception to it. With few experiments I am able to achieve it by adding multiple forcedType sections with desired order. Attaching sample snippet,

```
	<forcedTypes>
		<forcedType>
			<name>TINYINT</name>
			<expression>.*\.tableA\.columnx|.*\.tableA\.columny</expression>
		</forcedType>
		<forcedType>
			<name>BOOLEAN</name>
			<types>(?i:TINYINT)</types>
		</forcedType>
	</forcedTypes>
```

**Comment by lukaseder** [comment]
@spsheni Yes, that works, too. Thanks for documenting this here.
