### ISSUE TITLE
Support JPA @AttributeConverter in DefaultRecordMapper

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7550]
The `DefaultRecordMapper` should pick up JPA `@AttributeConverter` annotations and apply it when mapping from jOOQ records to JPA annotated "pojos"

**Comment by rponte** [comment]
Cool! Looking forward to this feature!

By the way, the name of annotation is not `@AttributeConverter ` but `@Converter`.

**Comment by lukaseder** [comment]
https://docs.oracle.com/javaee/7/api/javax/persistence/AttributeConverter.html

**Comment by lukaseder** [comment]
The `DefaultRecordMapper` support for JPA annotations may have been added prematurely a very long time ago. It's not the most idiomatic approach to mapping things in jOOQ, especially since jOOQ 3.15's ad-hoc converter APIs, which are all type safe.

We won't add more complexity to the reflective mappings anymore, see also: https://github.com/jOOQ/jOOQ/issues/4263
