### ISSUE TITLE
INSERT .. ON DUPLICATE KEY { IGNORE | UPDATE } emulation should consider all UNIQUE keys on PostgreSQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7552]
This is a continuation of a previous issue (#6462) to fix this also on PostgreSQL, which is quite harder. An anonymous block may need to be generated in this case, see:
https://stackoverflow.com/a/38066008/521799

**Comment by AlexStiyer** [comment]
Has anyone made any progress on adding this functionality or can anyone supply more context? I may be able to set aside some time to do some research and work this. 

As I understand, the issue may be more closely related to Postgres than to an implementation in JOOQ.

**Comment by lukaseder** [comment]
Thanks for your offer, @AlexStiyer.

> As I understand, the issue may be more closely related to Postgres than to an implementation in JOOQ.

Yes, I currently don't see how we can best emulate the MySQL semantics in PostgreSQL. PostgreSQL allows for addressing only one unique key in the `ON CONFLICT` clause, whereas MySQL's `ON DUPLICATE KEY UPDATE` always uses all unique keys for the conflict decision.

For example:

```sql
create table t (
  id int primary key,
  a int unique,
  b int unique
);
```

When upserting data into this table, in MySQL, any conflict (on `id`, `a`, or `b`) will produce the `UPDATE` behaviour. In PostgreSQL, only one of these constraints can be chosen, and if there's a conflict on the others, the `INSERT` will still fail.

I think this is a missing feature in PostgreSQL, which also doesn't support standard SQL `MERGE`, which would allow for expressing conflict resolution predicates based on all columns (see https://github.com/jOOQ/jOOQ/issues/6462)

For the record, I'm checking to see if an improvement is on the way in PostgreSQL:
https://twitter.com/lukaseder/status/1501857645082423296

If you know another syntactic workaround, I'm all ears. The main suggestion was to generate a PL/pgSQL block, which checks all constraints if there are multiple known constraints.

> As a work around, is this then still an open issue?

Your example is not a viable workaround. If you're listing multiple columns in the `ON CONFLICT` clause, then that just addresses a composite unique constraint, not multiple single-column unique constraints

**Comment by mkurz** [comment]
Regarding `MERGE`: There is work going on, maybe it even makes it into PostgreSQL 15 in September: https://commitfest.postgresql.org/37/3408/ (Thread: https://www.postgresql.org/message-id/flat/20201231134736.GA25392@alvherre.pgsql). The current commit fest goes until beginning of april (around the 7th or 8th usually), then PGv15 is feature froozen.

**Comment by mkurz** [comment]
Regardin "resolving conflicts on multiple unique constraints": Are you subscribed the the pgsql hackers list? Maybe you can post it in there and someone picks it up? :wink:

**Comment by lukaseder** [comment]
> Regarding `MERGE`: There is work going on, maybe it even makes it into PostgreSQL 15 in September:

There have been patches available for `MERGE` for a while now, but things do take time, and it's a very difficult statement to get right in terms of ACID.

I'm always having conversations about it, and pushing on twitter as well:

- https://twitter.com/pg_xocolatl/status/1247552140844961794
- https://twitter.com/lukaseder/status/1460320704780513295
- https://twitter.com/pg_xocolatl/status/1356305451718213632
- https://twitter.com/pg_xocolatl/status/1356315926002597888

> Regarding "resolving conflicts on multiple unique constraints": Are you subscribed the the pgsql hackers list? Maybe you can post it in there and someone picks it up? 😉

I've always found twitter to be a better channel than a mailing list with 500000 emails per day... But you can post it there!

**Comment by AlexStiyer** [comment]
@lukaseder Thank you for the quick response. I now understand the issue better. 

I will keep an eye out on the Postgres release schedule, hopefully we see movement on this soon.

**Comment by lukaseder** [comment]
@AlexStiyer You too can send a message to said mailing list, explaining your use-cases...

**Comment by lukaseder** [comment]
I'm looking into a related issue: https://github.com/jOOQ/jOOQ/issues/11552. There, the problem is with `UpdatableRecord::merge`, which produces an `INSERT .. ON DUPLICATE KEY UPDATE` statement, because naturally, when calling `merge()` on a record, all unique keys should be considered for the decision whether to `INSERT` or `UPDATE`.

A thought that crossed my mind is that it would be possible to cycle through all unique keys, starting with the primary key, and check if they have been included in the `INSERT` column list *explicitly*, and only then use the key in the `ON CONFLICT` clause. That would still not work correctly if there are multiple unique constraints, but at least it would fix this issue here when:

- There's a surrogate primary key, which is obviously omitted
- There's a single candidate key, which is provided

I'm reluctant to implement this, because things would work for such a table above, and as soon as another `UNIQUE` key is added, things would stop working. But it's definitely food for thought.

**Comment by AlexStiyer** [comment]
@mkurz after talking with the team my use case is fine to use with OnConflict after some adjustments. I may not have the best context to add to the email chain. I would appreciate if you reach out, and I will continue to monitor.

@lukaseder Would this work around become obsolete once Postgres implements the missing functionality?

**Comment by lukaseder** [comment]
> @lukaseder Would this work around become obsolete once Postgres implements the missing functionality?

I've just documented an idea here. I'm not very keen on implementing it, as it seems to be asking for more trouble than adding value. As such, I'm hoping we'll get `MERGE` before I will revisit this issue here, in case of which we can switch the `INSERT .. ON DUPLICATE KEY` emulation to `MERGE`

**Comment by lukaseder** [comment]
A related issue could be fixed in SQLite 3.35, which added support for "generalised" `ON CONFLICT`, i.e. 0-N `ON CONFLICT` targets for `DO UPDATE`: https://github.com/jOOQ/jOOQ/issues/13273.

Still hoping that at least the 0 targets case will be supported in PostgreSQL.

**Comment by mkurz** [comment]
Today is our lucky day. 11 minutes ago `MERGE` was merged (:wink:) into PostgreSQL, so it will be available in PG15: https://github.com/postgres/postgres/commit/7103ebb7aae8ab8076b7e85f335ceb8fe799097c

**Comment by mkurz** [comment]
> Today is our lucky day. 11 minutes ago `MERGE` was ~merged~ commited (wink) into PostgreSQL, so it will be available in PG15: [postgres/postgres@7103ebb](https://github.com/postgres/postgres/commit/7103ebb7aae8ab8076b7e85f335ceb8fe799097c)

From the commit message, some limitations: `...MERGE does not support targetting updatable views or foreign tables, and
RETURNING clauses are not allowed either.  These limitations are likely
fixable with sufficient effort....`

**Comment by lukaseder** [comment]
> Today is our lucky day. 11 minutes ago `MERGE` was ~merged~ commited (😉) into PostgreSQL, so it will be available in PG15: [postgres/postgres@7103ebb](https://github.com/postgres/postgres/commit/7103ebb7aae8ab8076b7e85f335ceb8fe799097c)

Thanks a lot for the ping. I'll be looking forward to playing with that, once it's available.

I've created a new issue to add support for a `SQLDialect.POSTGRES_15` dialect: https://github.com/jOOQ/jOOQ/issues/13358

> From the commit message, some limitations: `...MERGE does not support targetting updatable views or foreign tables, and RETURNING clauses are not allowed either. These limitations are likely fixable with sufficient effort....`

Well, that `RETURNING` clause itself isn't really standard SQL. The SQL standard specifies the `<data change delta table>`, which supports reading from `MERGE` output. But I think that's a separate discussion.

**Comment by Rajdeepkaur245** [comment]
Does anyone have workarounds for the upsert query with multiple constraints? I am facing the same issue where I have a table with one primary key and one unique key constraint on some other fields.

create table test id integer primary key, subid integer unique key subiduniquekey, name varchar;

I have my upsert query as
 insert into table values (1, 1, 'test') on conflict on conflict on constraint subiduniquekey update name=excluded.name;

Whenever I have concurrent upsert to this table, sometimes it fails for unique key violation on primary key, although on subsequent retries query does not give any failure. 
Concurrent inserts to this table fails

**Comment by lukaseder** [comment]
jOOQ 3.18 will support PostgreSQL 15, which has `MERGE` support: https://github.com/jOOQ/jOOQ/issues/13358

We'll fix this issue here by delegating `INSERT .. ON DUPLICATE KEY UPDATE` support to `MERGE` for PostgreSQL 15.

**Comment by lukaseder** [comment]
Since this relies on new jOQO 3.18 stuff (#13358), I won't backport a fix.
