### ISSUE TITLE
Commercial edition Sybase issue ( CEIL ) jooq-3.10.7.jar

### ISSUE THREAD

**Issue by pom75** [jOOQ/jOOQ#7558]
### Expected behavior and actual behavior:
I can't use Ceil function with commercial edition trial on Sybase :
Caused by: com.sybase.jdbc4.jdbc.SybSQLException: Function 'ceil' not found            

### Steps to reproduce the problem (include example code if possible):
            
```java
create.select().from("TABLE_TEST").where(field("TABLE_TEST.PROFILE_KEY").equal(ceil(field("TABLE_TEST.PROFILE_KEY",SQLDataType.DECIMAL(5))))).execute();
```

works with:

```java
create.select().from("TABLE_TEST").where(field("TABLE_TEST.PROFILE_KEY").equal(field("{ceiling}({0})", SQLDataType.DECIMAL(5), field("TABLE_TEST.PROFILE_KEY",SQLDataType.DECIMAL(5))))).execute();
```

### How to fix it 

org.jooq.impl.Ceil.java

```java
        case SYABSE:
        case ASE:
        case SQLSERVER:
        case H2:
            return DSL.field("{ceiling}({0})", this.getDataType(), new QueryPart[]{this.argument});
```

Regards,
Stéphane Ferreira

**Comment by lukaseder** [comment]
Thank you very much for your report. Just to be sure, is this about Sybase SQL Anywhere, or Sybase ASE?

**Comment by pom75** [comment]
I'm using Sybase ASE 15.77 and 16
but in the debugger configuration.dialect().family() = Sybase 

my code : 
    public static void jooqTest(String url, String user,String password) {
        try(Connection conn = DriverManager.getConnection(url, user, password);
            DSLContext create = DSL.using(conn)) {
            create.select().from("TABLE_TEST").where(field("TABLE_TEST.PROFILE_KEY").equal(ceil(field("TABLE_TEST.PROFILE_KEY",SQLDataType.DECIMAL(5))))).execute();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
  <dependency>
                <groupId>sybase</groupId>
                <artifactId>jconn4</artifactId>
                <version>7.07.21018</version>
            </dependency>
            <dependency>
                <groupId>sybase</groupId>
                <artifactId>EccpressoFIPS</artifactId>
                <version>7.07.21018</version>
            </dependency>
            <dependency>
                <groupId>sybase</groupId>
                <artifactId>EccpressoFIPSJca</artifactId>
                <version>7.07.21018</version>
            </dependency>

**Comment by lukaseder** [comment]
Thanks for the additional feedback. Do note that `SQLDialect.SYBASE` corresponds to Sybase SQL Anywhere, whereas `SQLDialect.ASE` corresponds to Sybase ASE. This should already solve your problem, as you can see in your original pasted code where there is:

```java
case ASE:
```

- ASE calls the function `ceiling`: http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc36271.1600/doc/html/san1393050430974.html
- SYBASE supports both `ceiling` and `ceil`: http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.help.sqlanywhere.12.0.1/dbreference/ceiling-function.html

**Comment by pom75** [comment]
Thanks
Why when I do not specify any SQLDialect in `DSLContext create = DSL.using (conn)`, It detect me as Sybase and not as ASE?

**Comment by lukaseder** [comment]
Oh, I see, thanks for pointing that out. I'll think about this - perhaps we should change the default, or try to detect the actual dialect more reliably. Currently, the detection is done from the connection string, and they're not unambiguous.

**Comment by lukaseder** [comment]
... to stay on the safe side, use:

```java
DSLContext create = DSL.using (conn, SQLDialect.ASE)
```
