### ISSUE TITLE
Could not transfer artifact org.jooq:jooq-codegen-maven:pom:3.10.7 from/to central

### ISSUE THREAD

**Issue by BohdanKorinnyi** [jOOQ/jOOQ#7559]
### Expected behavior and actual behavior:
I tried to update Spring Boot version to 2.0.2 with jOOQ starter (3.10.7 jOOQ inside) but during build I get the following error:
```
[ERROR] Plugin org.jooq:jooq-codegen-maven:3.10.7 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.jooq:jooq-codegen-maven:jar:3.10.7: Could not transfer artifact org.jooq:jooq-codegen-maven:pom:3.10.7 from/to central (https://repo.maven.apache.org/maven2): 
java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 1]
```
It works well for Spring Boot 2.0.1 and jOOQ 3.10.6.

Thanks!
### Versions:

- jOOQ: 3.10.7
- Java: 1.8.0_171
- Database (include vendor): PostgreSQL 9.4
- OS: Ubuntu 18.04 LTS
- Spring Boot: 2.0.1.RELEASE

**Comment by BohdanKorinnyi** [comment]
I am not sure the error exactly related to jOOQ but in any case during update Spring Boot version build fails with message related to jOOQ

**Comment by lukaseder** [comment]
I'll be very happy to help once I know how to reproduce this :-)

**Comment by lukaseder** [comment]
(what I mean by that: Could you provide an MVCE: https://stackoverflow.com/help/mcve)

**Comment by BohdanKorinnyi** [comment]
1. Created a maven project using start.spring.io. Select Spring Boot version 2.0.2, add PostgreSQL and jOOQ.
2. Add generate plugin like here https://github.com/BohdanKorinnyi/issue/blob/master/pom.xml
3. Execute `mvn clean install`

Actual: build fails
Expected: build finish successfully

1. Change Spring Boot version from `<version>2.0.2.RELEASE</version>` to `<version>2.0.1.RELEASE</version>`.
2. Execute `mvn clean install`

Actual: build finish successfully
Expected: build finish successfully

**Comment by lukaseder** [comment]
Thanks for your example project. I've tried reproducing any issues, and obviously, Spring Boot will complain about missing database connection parameters as your `application.properties` file is empty:
https://github.com/BohdanKorinnyi/issue/blob/master/src/main/resources/application.properties

This is an example that would look more like it:
https://github.com/jOOQ/jOOQ/blob/master/jOOQ-examples/jOOQ-spring-boot-example/src/main/resources/application.properties

But I couldn't reproduce the problem you've referred to.

You've closed this issue, so I'm assuming you can no longer reproduce it yourself?

**Comment by BohdanKorinnyi** [comment]
Thanks for your effort @lukaseder !
I was my mistake to report issue in jOOQ and after spending some time in Google in found out that the reason for issue isn't related to jOOQ.

The problem occurs only for Ubuntu 18 users.
Workaround is [here](https://gist.github.com/mikaelhg/527204e746984cf9a33f7910bb8b4cb6)
