### ISSUE TITLE
JDBCUtils should recognise :sybase:Tds:

### ISSUE THREAD

**Issue by pom75** [jOOQ/jOOQ#7560]
https://github.com/jOOQ/jOOQ/blob/33dfa611d4d3fa523b72a07ff5cbe3a4158f25ec/jOOQ/src/main/java/org/jooq/tools/jdbc/JDBCUtils.java#L1

There is 2 driver for Sybase ASE : jTDS JDBC Driver ( :jtds:sybase:) and jConnect for JDBC (:sybase:Tds:).
Can you add jconnect support ?

Here :
```
if (url.contains(":jtds:sybase:")) {
                        return SQLDialect.ASE;
```

http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc01776.1602/doc/html/san1357754914053.html

**Comment by lukaseder** [comment]
Thanks a lot for your suggestion. This definitely makes sense. Implemented for jOOQ 3.12
