### ISSUE TITLE
Support mixing constraint definitions and columns in the parser

### ISSUE THREAD

**Issue by JanecekPetr** [jOOQ/jOOQ#7567]
### Expected behavior and actual behavior:
The following SQL DDL:

```sql
CREATE TABLE foo (
    bar BIGSERIAL NOT NULL,
    baz TEXT NOT NULL,
    PRIMARY KEY (bar, baz),
    
    qux TEXT NOT NULL
);
```

should parse without a hiccup. However, the SQL parser chokes on it and throws:

```
CHECK, CONSTRAINT, FOREIGN KEY, INDEX, KEY, PRIMARY KEY, or UNIQUE expected: [6:5] ...NOT NULL,
    PRIMARY KEY (bar, baz),

    [*]qux TEXT NOT NULL
);
```

instead. When tha table constraint is put after all column constraints, all works out nicely:

```sql
CREATE TABLE foo (
    bar BIGSERIAL NOT NULL,
    baz TEXT NOT NULL,
    qux TEXT NOT NULL,
    PRIMARY KEY (bar, baz)
);
```

```
$ java -cp jooq-3.11.0.jar org.jooq.ParserCLI -t POSTGRES -s "$(cat notepad2)"
create table foo(bar serial8 not null, baz text not null, qux text not null, primary key (bar, baz));
```

### Steps to reproduce the problem (include example code if possible):
Put the DDL above into https://www.jooq.org/translate/, or run

```
java -cp jooq-3.11.0.jar org.jooq.ParserCLI -t POSTGRES -s "$(cat notepad)"
```

with a `notepad` file containing the code instead.

### Versions:

- jOOQ: 3.11
- Java: N/A
- Database (include vendor): The original DDL has been written for and is accepted by Postgres
- OS: N/A
- JDBC Driver (include name if inofficial driver): N/A

**Comment by lukaseder** [comment]
Thanks a lot for the report. Indeed, this had been a conscious omission at some point, given the limited perceived utility of the syntax. What's the use-case of defining tables this way?

Having said so, it can definitely be supported it in a future version.

**Comment by lukaseder** [comment]
Definitely a bug, though. The grammar already allowed for mixing the different type of DDL subclauses:
https://www.jooq.org/doc/latest/manual/sql-building/sql-parser/sql-parser-grammar/#createTableStatement

**Comment by JanecekPetr** [comment]
> What's the use-case of defining tables this way?

Personal preference.

If

```
CREATE TABLE foo (
    bar BIGSERIAL PRIMARY KEY,
    baz TEXT NOT NULL,
    qux TEXT NOT NULL
);
```

is an accepted code style, then in similar fashion declaring a PK over two columns should be as close to the column declarations as possiblem shouldn't it?

Having some extra constraints in-line and some at the end of the table declaration seems strange when you can have constraints close to the columns they refer to... I think.

**Comment by lukaseder** [comment]
> is an accepted code style, then in similar fashion declaring a PK over two columns should be as close to the column declarations as possiblem shouldn't it?

I see your point, although I have never thought about it this way. While the convenience can be handy, I have always preferred to create tables without constraints and then alter them immediately afterwards. Even with "inline" constraints, I would usually not prefer the syntax you've shown because I always want to name my constraints.

But fair enough. Ultimately, if it's possible in SQL, it should be possible in jOOQ.
