### ISSUE TITLE
Support alternative PostgreSQL array syntax in parser

### ISSUE THREAD

**Issue by JanecekPetr** [jOOQ/jOOQ#7571]
### Expected behavior and actual behavior:

I expect

```sql
CREATE TABLE foo (
    bar BIGSERIAL PRIMARY KEY,
    conditions TEXT ARRAY
);
```

to be the same as

```sql
CREATE TABLE foo (
    bar BIGSERIAL PRIMARY KEY,
    conditions TEXT[]
);
```

However, the former fails in the jOOQ parses with

```
Token ')' expected: [3:21] ...  bar BIGSERIAL PRIMARY KEY,
    conditions TEXT [*]ARRAY
);
```

whereas the latter parses just fine.

### Steps to reproduce the problem (include example code if possible):

Run the code above through the jOOQ Parser.

### Versions:

- jOOQ: 3.11
- Java: N/A
- Database (include vendor): The DDL has been written for and is being accepted by Postgres
- OS: N/A
- JDBC Driver (include name if inofficial driver): N/A

**Comment by lukaseder** [comment]
Thanks a lot for reporting. Indeed, we should treat these two as the same.

**Comment by lukaseder** [comment]
Note that according to the documentation, specifying an explicit size is also possible, but not yet supported by the jOOQ parser:
https://www.postgresql.org/docs/current/static/arrays.html

E.g.

```sql
create table x (
  i int[5],
  j int array[5]
)
```
