### ISSUE TITLE
KeepNamesGeneratorStrategy ignored

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#7572]
### Expected behavior and actual behavior:
I'm using code generation via maven, with the following XML block:
```

<generator>
            <database>
              <name>org.jooq.util.derby.DerbyDatabase</name>
              <includes>
                  CURR.*
              </includes>
              <excludes></excludes>
              <inputSchema></inputSchema>
              <outputSchema></outputSchema>
            </database>
            <strategy>
              <name>org.jooq.util.KeepNamesGeneratorStrategy</name>
            </strategy>
            <target>
              <packageName>com.vrg.generated</packageName>
              <directory>target/generated-sources/jooq</directory>
            </target>
</generator>

```
I have tables and fields in the form MyName (pascal case). And yet, JOOQ generates table and field names as MYCASE. I'd expect it instead to retain the pascal case form for everything. What's going on?

### Versions:

- jOOQ: 3.11.0 (also tested 3.10.5)
- Java: 1.8.0_101-b13
- Database (include vendor): Apache Derby (this worked fine on sqlite for some reason)
- OS: OSX High Sierra
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your report. The jooq-meta and jooq-codegen package names have changed between versions 3.10 and 3.11. See:

- https://github.com/jOOQ/jOOQ/issues/7556
- https://github.com/jOOQ/jOOQ/issues/7419

The package name is now: `org.jooq.codegen.KeepNamesGeneratorStrategy`
