### ISSUE TITLE
java.lang.ClassCastException: org.jooq.meta.extensions.ddl.DDLDatabase cannot be cast to org.jooq.util.Database

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#7577]
### Expected behavior and actual behavior:

I'm following the instructions in the documentation to use code generation from a supplied schema file (as opposed to a database): https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl/#comment-3635452023

I instead get an exception: `java.lang.ClassCastException: org.jooq.meta.extensions.ddl.DDLDatabase cannot be cast to org.jooq.util.Database`

### Steps to reproduce the problem (include example code if possible):

Here is the relevant block from my maven pom.xml.
```

<generator>
            <database>
                <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
                <properties>
                    <!-- Specify the location of your SQL script. Future versions may also support more than one script, or directories -->
                    <property>
                        <key>scripts</key>
                        <value>tables.sql</value>
                    </property>
                </properties>
            </database>
           ...
          </generator>
```

### Versions:

- jOOQ: 3.11.0
- Java: 1.8.0_101
- Database (include vendor): 
- OS: OSX High Sierra
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your report. Why are you getting a `org.jooq.util.Database` reference? In jOOQ 3.11, packages have been renamed, and the `org.jooq.util.Database` type is now in `org.jooq.meta.Database`. One reason why you could be getting this is because you didn't upgrade all artifacts to 3.11 (e.g. you upgraded jOOQ-meta-extensions, but not jOOQ-meta).

Can you confirm this?

**Comment by lalithsuresh** [comment]
I don't see how that can happen. Here are my dependencies:
``
<dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>3.11.0</version>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-meta</artifactId>
            <version>3.11.0</version>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-meta-extensions</artifactId>
            <version>3.11.0</version>
        </dependency>
``

**Comment by lalithsuresh** [comment]
Ah, my bad. The code generator I was using was still version 3.10.5.

**Comment by lukaseder** [comment]
Thanks for the feedback - glad you could resolve it!

**Comment by lalithsuresh** [comment]
Thanks a lot for the prompt responses!
