### ISSUE TITLE
jOOQ Codegen 3.11.0 Fail on Java 10 with java.lang.NoClassDefFoundError: com/sun/xml/bind/v2/model/annotation/AnnotationReader

### ISSUE THREAD

**Issue by delmania** [jOOQ/jOOQ#7580]
I'm trying to run the code generation tool against an H2 database. But it's failing since it can't find the annotationreader class.

This is the command line I'm using: 

> java -classpath jooq-3.11.0.jar:jooq-codegen-3.11.0.jar:jooq-meta-3.11.0.jar:h2-1.4.197.jar:jaxb-api-2.3.0.jar:jaxb-runtime-2.3.0.1.jar:. --add-modules java.xml.bind org.jooq.codegen.GenerationTool jooq-config.xml

### Versions:

- jOOQ: 3.11.0
- Java: 10
- Database (include vendor):H2, 1.4.197
- OS: macIS
- JDBC Driver (include name if inofficial driver): org.H2.Driver

**Comment by lukaseder** [comment]
Does it work if you remove these: `jaxb-api-2.3.0.jar:jaxb-runtime-2.3.0.1.jar:` and run this instead?

> java -classpath jooq-3.11.0.jar:jooq-codegen-3.11.0.jar:jooq-meta-3.11.0.jar:h2-1.4.197.jar:. --add-modules java.xml.bind org.jooq.codegen.GenerationTool jooq-config.xml

**Comment by lukaseder** [comment]
Note, a future version of jOOQ will ship with `generationtool.bat` and `generationtool.sh` scripts: #7586. These should be updated to work on all JDKs, specifically on JDK 11, the `java.xml.bind` module will no longer ship with the JDK itself.

**Comment by lukaseder** [comment]
@davinkevin : These errors are easier to avoid when using Maven, as the transitive dependencies will be included automatically. For example, `java.activation` is a module that is used by JAXB, transitively.

**Comment by davinkevin** [comment]
I have this problem during a maven build 😓.
So I would like to know what could be done to fix this the right way...

**Comment by lukaseder** [comment]
@davinkevin But then, this isn't the same issue. Would you mind creating a new one with details helping to reproduce your specific issue?

**Comment by davinkevin** [comment]
I can do it, but this will be the same error generated from the `jOOQ-codegen-maven` plugin.

**Comment by lukaseder** [comment]
The typical solution to this kind of problem is not jOOQ specific. It "just" boils down to putting *all* the required (and transitive) dependencies on the classpath for jOOQ to be able to pick them up. See, for example:
https://stackoverflow.com/a/36557993/521799

There had been a lot of trouble with jOOQ and JAXB in the past. This is very unfortunate for users, as the JAXB dependency is an internal detail. Users should not need to worry about setting up such transitive dependencies correctly.

As a result, I have now implemented a "Mini JAXB" API for jOOQ internal use, such that in the absence of JAXB on the classpath, jOOQ can continue loading XML files. See #7734
