### ISSUE TITLE
Add new ResourceManagingScope which allows for Binding implementations to register resources which are freed after execution

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7591]
Inside of `BindingSetStatementContext`, there's a possibility of creating resources to bind them to JDBC. For example `FileInputStream`: https://stackoverflow.com/a/50903522/521799

```java
class StreamingLobBinding implements Binding<String, File> {
    ...
    @Override
    public void set(BindingSetStatementContext<File> ctx) {
        // Ideally: register the input stream somewhere for explicit resource management
        ctx.statement()
           .setBinaryStream(ctx.index(), new FileInputStream(ctx.value()));
    }
}
```

Currently, users have to remember their created resources somehow (e.g. using thread locals) and free / close them after the statement is executed. It would be better if we offered SPI where such resources can be registered, or even more generically, callbacks can be registered. E.g.

```java
    public void set(BindingSetStatementContext<File> ctx) {
        final FileInputStream stream = new FileInputStream(ctx.value());
        ctx.onStatementClose(() -> stream.close());
        ctx.statement()
           .setBinaryStream(ctx.index(), stream);
    }
```

**Comment by fortm** [comment]
I think `ctx.value(new FileInputStream(ctx.value())` should be `new FileInputStream(ctx.value()` above.

I am trying to come up with Converters and rest of method implementations for ThreadLocal version but currently failing to implement from, to and handling exceptions in set

`public class StreamingLobBinding implements Binding<String, File> {

    @Override
    public Converter<String, File> converter() {
        return new Converter<String, File>() {
            @Override
            public File from(String s) {
                return null;  // here ?
            }

            @Override
            public String to(File file) {
                return null; // here ?
            }

            @Override
            public Class<String> fromType() {
                return String.class;
            }

            @Override
            public Class<File> toType() {
                return File.class;
            }
        };
    }

    @Override
    public void sql(BindingSQLContext<File> ctx) throws SQLException {
        ctx.render().visit(DSL.val(ctx.convert(converter()).value())).sql("");
    }

    @Override
    public void register(BindingRegisterContext<File> ctx) throws SQLException {
        ctx.statement().registerOutParameter(ctx.index(), Types.CLOB);
    }

    @Override
    @SneakyThrows  // here ?
    public void set(BindingSetStatementContext<File> ctx) throws SQLException {
        final FileInputStream stream = new FileInputStream(ctx.value());
        CustomExecuteContext.register(stream);

        ctx.statement().setBinaryStream(ctx.index(), stream);
    }

    @Override
    public void set(BindingSetSQLOutputContext<File> ctx) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }

    @Override
    public void get(BindingGetResultSetContext<File> ctx) throws SQLException {
        ctx.convert(converter()).value(ctx.resultSet().getString(ctx.index()));
    }

    @Override
    public void get(BindingGetStatementContext<File> ctx) throws SQLException {
        ctx.convert(converter()).value(ctx.statement().getString(ctx.index()));
    }

    @Override
    public void get(BindingGetSQLInputContext<File> ctx) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }
}
`

Also in Usage it is complaining below - cannot resolve method which goes away when eliminating COL1 from columns and values and keeping only COL2.

`DataType<File> fileType = TABLE1.COL2.getDataType().asConvertedDataType(new StreamingLobBinding());
            Field<File> fileCol2 = DSL.field(TABLE1.COL2.getName(), fileType);
            dsl.insertInto(TABLE1)
                    .columns(TABLE1.COL1, fileCol2)
                    .values(command, DSL.val({an instance of java.io.File}, fileType))
                    .execute();
`
Execution Context 
`
public class CustomExecuteContext {
    private static final ThreadLocal<List<InputStream>> STREAMS = new ThreadLocal<List<InputStream>>();

    static final void register(InputStream stream) {
        STREAMS.get().add(stream);
    }

}
`

Can you point to some sample implementation for Clob (string) to File conversion using ThreadLocal. I can follow along and correct mistakes above.

Thanks

**Comment by lukaseder** [comment]
> I think ctx.value(new FileInputStream(ctx.value()) should be new FileInputStream(ctx.value() above.

Yes of course, copy paste error. Thanks for the pointer.

> I am trying to come up with Converters and rest of method implementations for ThreadLocal version but currently failing to implement from, to

You don't *have* to implement `from()` and `to()`, unless you're calling them yourself (and you're doing that implicitly, because you're using the `convert()` method. The important methods in the `Converter` for the `Binding` are `fromType()` and `toType()`, which are needed because of generic type erasure.

> and handling exceptions in "set"

Wrap them in a `SQLException` or a `RuntimeException`

**Comment by fortm** [comment]
one more change requested in solution - changing `DSL.val(file, fileType)` to `DSL.val(file, fileType).getValue()`, otherwise it gives compile error in insert statement with COL1 that is TEXT type.

```
 dsl.insertInto(TABLE1)
                    .columns(TABLE1.COL1, fileCol2)
                    .values("ABBB", DSL.val(file, fileType).getValue())
                    .execute();
```

I now get SQLFeatureNotSupportedException while insert.

```
Caused by: java.sql.SQLFeatureNotSupportedException
	at org.sqlite.jdbc4.JDBC4PreparedStatement.setBinaryStream(JDBC4PreparedStatement.java:96)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.setBinaryStream(DefaultPreparedStatement.java:344)
	at com.test.real.StreamingLobBinding.set(StreamingLobBinding.java:56)
	at org.jooq.impl.DefaultBindContext.bindValue0(DefaultBindContext.java:62)
```

This is because JDBC4PreparedStatement.class in` sqlite-jdbc` does not support `setBinaryStream`

```
    public void setBinaryStream(int parameterIndex, InputStream x) throws SQLException {
        throw new SQLFeatureNotSupportedException();
    }
```
So I am left with using `setBytes ` instead of `setBinaryStream `  in `StreamingLobBinding - set `  which needs byte[] and will mitigate advantages of using an inputStream in first place. 

```
    public void set(BindingSetStatementContext<File> ctx) throws SQLException {
        final ByteArrayInputStream stream = new ByteArrayInputStream(FileUtils.readFileToByteArray(ctx.value()));

        ctx.statement().setBinaryStream(ctx.index(), stream);
        //ctx.statement().setBytes(ctx.index(), IOUtils.toByteArray(stream));
    }
```

Thanks

**Comment by lukaseder** [comment]
> one more change requested in solution - changing DSL.val(file, fileType) to DSL.val(file, fileType).getValue(), otherwise it gives compile error in insert statement with COL1 that is TEXT type.

I think this is based on a misunderstanding of my answer here: https://stackoverflow.com/a/50903522/521799

Observe that in my answer, I didn't use a string to indicate the column type on the `set()` clause like you just did:

```java
dsl.insertInto(TABLE1)
                    .columns(TABLE1.COL1, fileCol2)
                    .values("ABBB", DSL.val(file, fileType).getValue())
                    .execute();
```

You cannot mix `T` types with `Field<T>` types in the `values()` clause. Write this, instead:

```java
dsl.insertInto(TABLE1)
                    .columns(TABLE1.COL1, fileCol2)
                    .values(DSL.val("ABBB"), DSL.val(file, fileType))
                    .execute();
```

> This is because JDBC4PreparedStatement.class insqlite-jdbc does not support setBinaryStream

Oh, interesting, I had overlooked this important detail. In that case, I don't think you really have a good way to optimise this here, using jOOQ's binding SPI. Better revert to the old version, and perhaps concatenate the LOB object in several steps using:

```sql
INSERT INTO table1 (col1, col2) VALUES ('ABBB', null);
UPDATE table1 SET col2 = coalesce(col2, '') || <first MB>;
UPDATE table1 SET col2 = coalesce(col2, '') || <second MB>;
UPDATE table1 SET col2 = coalesce(col2, '') || <third MB>;
```
