### ISSUE TITLE
Add support for Java 11

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7595]
jOOQ 3.12 shall officially support Java 11. The main point of interest here is the lack of JAXB in the JDK, which jOOQ depends upon.

**Comment by hbrackmann** [comment]
a quick tip: https://github.com/javaee/jaxb-v2/issues/1168
For me the only viable solution was to use a snapshot version of jaxb.

**Comment by lukaseder** [comment]
@hbrackmann: cool, thanks for the heads up!

**Comment by lukaseder** [comment]
Removing the jaxb-api `runtime` scope and adding an explicit activation dependency in Maven is sufficient to build jOOQ.
