### ISSUE TITLE
Add search box to Javadocs

### ISSUE THREAD

**Issue by manouti** [jOOQ/jOOQ#7598]
It would be nice to include the search feature from JDK 9 in the generated API docs. Maybe with a specific maven-javadoc-plugin configuration that points to javadocExecutable or using an overriden JDK toolchain.

**Comment by lukaseder** [comment]
Great idea, thanks for the suggestion. Will look into how this can be done

**Comment by lukaseder** [comment]
This will probably be automatic with jOOQ 3.12, which is the first modular jOOQ release and which will be built with JDK 10 or 11.

For the time being, the workaround is to google search e.g. for `Binding`:

```
site:https://www.jooq.org/javadoc/latest Binding
```

**Comment by lukaseder** [comment]
I can confirm, this is automatic with JDK 9+. E.g. here's the jOOX Javadoc, which includes the search box:
https://www.jooq.org/products/jOOX/javadoc/latest/index.html?overview-summary.html

So, this feature will ship for free with jOOQ 3.12 and #6612

**Comment by manouti** [comment]
Awesome, thanks!
