### ISSUE TITLE
Provide an SPI to abstract over the execution engine

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7605]
Currently, jOOQ is tied to JDBC only. But in the future, it will make sense to override this default and delegate to other execution APIs through extensions to the core runtime library. Some examples:

- JPA `EntityManager`: #6543
- ADBA: https://github.com/oracle/oracle-db-examples/tree/master/java/AoJ
- R2DBC: https://github.com/r2dbc/r2dbc-client

Switching the underlying execution model will have a lot of additional effects on other SPI and API. For example:

- The `Binding` and `ExecuteListener` SPIs will need to be re-written, or abstracted over as well, as it is tighly coupled to JDBC as well
- Others?

**Comment by mkurz** [comment]
For this feature you may be interested in https://github.com/pgjdbc/pgadba.

**Comment by lukaseder** [comment]
Thanks for the pointer. Indeed, I'm following the various efforts around ADBA and R2DBC. The APIs are promising, but both are not stable yet. This is definitely something I will look into for jOOQ 3.13, though.

**Comment by lukaseder** [comment]
Duplicate of #6298
