### ISSUE TITLE
Add support for exporting CHECK constraints through DSLContext.ddl()

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#7629]
### Expected behavior and actual behavior:

We're performing code generation as follows:
```

            <database>
                <name>org.jooq.meta.extensions.ddl.DDLDatabase</name>
                <properties>
                    <property>
                        <key>scripts</key>
                        <value>tables.sql</value>
                    </property>
                </properties>
            </database>
```
Where tables.sql has:

```
CREATE TABLE mytable (
  col1 varchar(36),
  CHECK (col1 IN ('ON', 'OFF'))
);
```

The generated code does not seem to account for that check constraint:

```
System.out.println(create.ddl(Tables.MYTABLE));
// Prints:
// create table "PUBLIC"."MYTABLE"(
//  "COL1" varchar(36)
// );
```
I would expect the check constraints for that table to be parsed too.

Is this specific to code generation from scripts? Any workarounds?

### Versions:

- jOOQ: 3.11
- Java: 1.8.0_101-b13
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for reporting this. This is, in fact, a missing feature. We'll first need:

- A runtime meta model for check constraints (outside of DDL): #7638
- Code generation support: #7639

**Comment by lukaseder** [comment]
We're now exporting check constraints that are available from meta information through `DSLContext.ddl()` and `Meta.ddl()`. We still need code generation support (#7639), and support through other ways of producing runtime meta information (#9562)

**Comment by lukaseder** [comment]
Code generation support and other means of producing `CHECK` constraints has now been implemented. This feature will be ready for use in jOOQ 3.13
