### ISSUE TITLE
Offer an improved VisitListener

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7642]
`org.jooq.Clause` was deprecated in jOOQ 3.11 with #7258, because:

- It was implemented incompletely (e.g. no `LIMIT` clause, no window function clauses, no DDL clauses, etc.)
- It was implemented incorrectly (e.g. some SQL transformations are not reflected through appropriate clauses)
- It is difficult to maintain

While the concept of a `VisitListener` is very interesting, we need a better approach. This issue will collect ideas and work as a placeholder for a more formal specification.

----
See:
- Cache invalidation: https://groups.google.com/forum/#!topic/jooq-user/7efwPq6gHYg

**Comment by recursinging** [comment]
I noticed that `org.jooq.Clause` has been deprecated while evaluating an upgrade from version 3.5.2 to 3.11.4.  I would miss this functionality should it be removed.  

My primary use of `VisitListner` is as a simple foot-gun guard in a shared-schema multi-tenant environment, ensuring the tenant identifying column is included as a condition clause of any DML statements.  This will (and has) prevented a catastrophe should a developer forget to include the condition when doing something with the fluent API.

`VisitListner` is very powerful and I can imagine it being a burden to maintain, especially if it should be complete.  But I can also imagine that most of the actual use cases (like my own) for it are usually pretty simple. I'd suggest just letting it remain incomplete, and simply documenting what is not covered, or limiting the scope of a replacement to something where a walkable SQL syntax tree is not expected.

Just my two cents.

**Comment by lukaseder** [comment]
Thank you very much for your feedback, @recursinging. Rest assured, there will be at least a replacement for how `VisitListener` works right now, probably an improvement. At this point, the deprecation is a way to gather feedback like yours, and removal of `org.jooq.Clause` will definitely not happen for a few more years.

I like your use-case. A lot of use-cases that `VisitListener` is used for, evolve around shared schema multi tenancy / row level security ([probably due to our blog post](https://blog.jooq.org/2015/06/17/implementing-client-side-row-level-security-with-jooq/)). I'm curious:

1. What database are you using? Some databases offer ways of implementing such logic in views, which would make sure that *no process* could ever get this wrong (not just *no jOOQ query*)
2. Are you sure you need `org.jooq.Clause` for your current implementation?

> I'd suggest just letting it remain incomplete, 

Sure, it will remain as it is for quite a while

> and simply documenting what is not covered

I understand the motivation behind that comment, but maintaining such a documentation would turn increasingly difficult. Much better go forward and replace the mechanism by something better.

> or limiting the scope of a replacement to something where a walkable SQL syntax tree is not expected.

I'm not sure what you mean by that. The `VisitListener` SPI is extremely powerful, and if anything at all, I'd love to extend its expression tree walking capabilities, not reduce them. But they need a better design. The `org.jooq.Clause` has been introduced *only* for this SPI. It has no other use. I'm sure there's a much better design possible, that would allow for all existing functionality to work, *and* new functionality to be implemented much more easily.

**Comment by recursinging** [comment]
> What database are you using? Some databases offer ways of implementing such logic in views, which would make sure that no process could ever get this wrong (not just no jOOQ query)

MySQL 5.7 with thousands of regularly changing tenants across hundreds of tables, historically we've treated the RDBMS as a dumb store (mainly for portability's sake) which has kept things like row security in application code (although I am relaxing this a bit as the disparity between the different DB vendor feature-sets shrinks).  The `VisitListener` SPI has been a boon for us in this regard.

> Are you sure you need org.jooq.Clause for your current implementation?

I am not aware of a better way to identify the context of a visit invocation... `context.queryPart() instanceof ...` conditions perhaps?

> The VisitListener SPI is extremely powerful, and if anything at all, I'd love to extend its expression tree walking capabilities, not reduce them.

Indeed, the power of the `VisitListener` SPI is impressive.  I was simply suggesting that if the actual practical use cases for run-time SQL transformation in the wild are limited to a few simple ones like mine, then perhaps it does not need to be more powerful, but easier to use?  Commanding an overview of all the variations an SQL statement structure might take poses quite a challenge for even a seasoned developer. Implementing a robust transform using the `VisitListener` SPI is tough.  Having to maintain a stack of scopes to properly handle sub-select transforms is not exactly intuitive, especially if you've never actually needed a sub-select in your client code.  Perhaps what I am imagining is not the `VisitListener` SPI at all, but something else entirely built atop it.

Then of course, I'm only considering my use cases here.

**Comment by lukaseder** [comment]
> MySQL 5.7

OK, I was hoping PostgreSQL or Oracle. I'm not currently aware of a vendor specific feature in MySQL that can do this.

> I am not aware of a better way to identify the context of a visit invocation... context.queryPart() instanceof ... conditions perhaps?

Yes, that's what I had in mind.

> Indeed, the power of the VisitListener SPI is impressive. I was simply suggesting that if the actual practical use cases for run-time SQL transformation in the wild are limited to a few simple ones like mine, then perhaps it does not need to be more powerful, but easier to use?

In my eyes, easier to use = more powerful. Also, easier to use = there will be more actual practical use cases. Specifically, in your case, it is extremely difficult to catch all the possible cases of acceptable predicates. E.g.:

Are you checking:

- Join predicates
- Semi joins (`EXISTS()`) predicates that effectively select a single tenant
- Plain SQL predicates
- Etc.

Probably not, because the `VisitListener` doesn't make this very easy. I can think of a much better SPI that exposes some internal expression tree representation that can then be walked more easily. Before implementing that, I would like to see what projects Amber and Valhalla will offer me here. There is definitely a lot to gain from using algebraic data types and/or value types for such tree traversal.

> Perhaps what I am imagining is not the VisitListener SPI at all, but something else entirely built atop it.

Yes, I see what you mean. It would be great if there were out of the box SQL transformation features for the most common use-cases of the `VisitListener`, including shared schema multi tenancy and row level security. This is similar to the schema mapping feature, which is essentially another way of implementing multi tenancy.

So I think I will review #2682, which does precisely this (perhaps not even using a `VisitListener` under the hood)

**Comment by recursinging** [comment]
Funny, I was the one who got #2682 rolling with that forum post.

> I can think of a much better SPI that exposes some internal expression tree representation that can then be walked more easily.

Without really knowing the JOOQ internals so well, and speaking from my limited experience implementing the a simple templating language (Liquid) in Java using ANTLR, I found the `ParseTreeListener` implementation [generated from a given ANTLR grammar](https://github.com/antlr/antlr4/blob/master/doc/listeners.md) to be more intuitive.  

The base implementation having an empty concrete `enter*` and `exit*` method to extend for each node of the parser grammar allows a subclass implementer to pick and choose the relevant nodes to implement logic on.  This eliminates the need for the conditional logic (and node identity enumeration like `org.jooq.Clause`) necessary in an SPI like `VisitListener` at the cost of requiring more boilerplate code.

I see you now have an SQL parser in the library, and a documented grammar, I could (naively) imagine a node visiting SPI as a base class with `enter*` and `exit*` methods reflecting the names you've given the parse nodes of that grammar.  The grammar documentation can then be used as guidance for better understanding which methods would be necessary to override in order to cover corner cases like the ones you mentioned.

I'll reiterate, I am not familiar with the JOOQ internals, I don't know if your internal expression tree reflects that of the SQL parser grammar you've documented, or if such an SPI would be practical from a performance or maintenance perspective. I did find that style of node visiting easier to grasp, especially together with a concrete grammar as reference.

**Comment by lukaseder** [comment]
> Funny, I was the one who got #2682 rolling with that forum post.

Cool, so welcome back! :-)

> Without really knowing the JOOQ internals so well, and speaking from my limited experience implementing the a simple templating language (Liquid) in Java using ANTLR, I found the ParseTreeListener implementation generated from a given ANTLR grammar to be more intuitive.

I would much prefer this not to be about the "language" itself as represented by the parser (note that the parse is a hand written recursive descent parser, so there's no obvious tooling that could automatically generate things), but rather about the expression tree expressed in `QueryPart` subtypes. If we manage to expose the entire expression tree using algebraic data types (ADT), transforming them will be very elegant. The effect will be similar to what you've shown about that `ParseTreeListener`

**Comment by stellingsimon** [comment]
We are using `Clause` to implement row-level security with custom policies in two separate projects (one on Oracle Standard Edition, the other on PostgreSQL 9.5).

Our `VisitListener` is used to generically modify SELECT statements by adding arbitrary conditions that may depend on the tables accessed and the application user performing the access. 

Some implementation details:

 * it distinguishes tables from selects aliased as tables
 * it distinguishes inner-joins from left joins
 * it handles nested selects (e.g. as used in the LIMIT-emulation used on Oracle dialects)

However, we can afford to *not* look into/manipulate

 * join predicates
 * semi joins (EXISTS()) predicates
 * plain SQL predicates

@lukaseder If needed I may be able to share code snippets via a non-public channel.

**Comment by lukaseder** [comment]
Thanks a lot for your input, @stellingsimon. I'd love to see some code snippets, indeed! I think that your use-case should be entirely covered by the new `Table.where()` clause: https://github.com/jOOQ/jOOQ/issues/8010, which can then be used for row level security and other things: https://github.com/jOOQ/jOOQ/issues/8012 (the latter unfortunately won't ship with 3.12 anymore)

Doing this kind of transformation with a `VisitListener` (and a future improved listener) is obviously possible, but jOOQ should be able to implement such a common and simple use case in a much simpler way, without the requirement of users implementing such delicate SQL transformation logic themselves.

**Comment by lukaseder** [comment]
... N.B: The `Table.where()` approach effectively turns tables into views with a filter, such as described in this blog post: https://blog.jooq.org/2016/10/20/be-careful-when-emulating-parameterised-views-with-sys_context-in-oracle/. Unlike the approach from the blog post (which is possible in both Oracle and PostgreSQL, and I recommend you review this option!) the `Table.where()` clause allows for fully dynamic SQL generation, not just hard coded predicates against some context values.

**Comment by a-derevyanko** [comment]
We use this functionality to search for incorrectly formed IN conditions - conditions with a variable number of bind variables. Such queries are bad for query cache (https://asktom.oracle.com/pls/asktom/f?p=100:11:0::::P11_QUESTION_ID:494231000346774971), therefore we try not to use them.
Today I noticed that part of the code
`context.clause() == Clause.CONDITION_IN`
deprecated.

Will there be an equivalent replacement for the possibility of implementing a IN condition check?

**Comment by lukaseder** [comment]
I'm glad you asked. We have an entire feature request for new diagnostics which could be added in the future: https://github.com/jOOQ/jOOQ/issues/7527. The one you've mentioned is already available.

There's IN-list padding which might be interesting to you: https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-in-list-padding

Also, the `DiagnosticsListener` could help you with this. You could render your query a second time with the above IN-list padding set to a meaningful value, and then look for the `DiagnosticsListener::duplicateStatements` event, see:
https://www.jooq.org/doc/latest/manual/sql-execution/diagnostics/diagnostics-duplicate-statements/

**Comment by wouterhund** [comment]
We are looking into using this while eagerly waiting for https://github.com/jOOQ/jOOQ/issues/9163 to solve https://github.com/jOOQ/jOOQ/issues/5208

Using `instanceof` is difficult due to the relevant classes (`FieldAlias`, `Alias`) being package-private, which is lead us to using `VisitListener` in the first place.

**Comment by lukaseder** [comment]
While `Clause` will be removed, eventually, `VisitListener` won't be. It's highly effective and it will get an upgrade in jOOQ 3.16 when the new experimental query object model API goes live. Using that, it will be *much* easier to transform any SQL fragment from a `VisitListener` or also from an `ExecuteListener`, as the entire expression tree will be available as a public API.

At this point, I don't think there's anything that needs to be improved in the `VisitListener`, so closing this as won't fix.

**Comment by eralmansouri** [comment]
> While `Clause` will be removed, eventually, `VisitListener` won't be. It's highly effective and it will get an upgrade in jOOQ 3.16 when the new experimental query object model API goes live. Using that, it will be _much_ easier to transform any SQL fragment from a `VisitListener` or also from an `ExecuteListener`, as the entire expression tree will be available as a public API.
> 
> At this point, I don't think there's anything that needs to be improved in the `VisitListener`, so closing this as won't fix.

Given that in the [model API](https://www.jooq.org/doc/latest/manual/sql-building/model-api/) all of traversal, replacement, pattern transformation, mapping replacer, listening replacer and decomposing replacer are added as pro-features only, is there an alternative to free users that currently depend on this deprecated feature for [client-side row-level security](https://blog.jooq.org/implementing-client-side-row-level-security-with-jooq/)?

**Comment by lukaseder** [comment]
Since this feature set is such a set of power user features, the best alternative is upgrading to a commercial edition! All of these features are available already with the jOOQ Express Edition.
