### ISSUE TITLE
jOOQ 3.11+ transitive dependency prevents it from being loaded on WebLogic 12.1.3

### ISSUE THREAD

**Issue by Pazus** [jOOQ/jOOQ#7649]
### Expected behavior and actual behavior:
After upgrate jOOQ (pro) from 3.10.7 to any 3.11 version and deploying `war` to WebLogic 12.1.3 (precisely 12.1.3.0.0) the `war` doesn't start with error:
```
weblogic.application.ModuleException: null
null
	at weblogic.servlet.internal.WebAppModule.createModuleException(WebAppModule.java:1824)
	at weblogic.servlet.internal.WebAppModule.init(WebAppModule.java:270)
	at weblogic.servlet.internal.WebAppModule.init(WebAppModule.java:682)
	at weblogic.application.internal.flow.ScopedModuleDriver.init(ScopedModuleDriver.java:162)
	at weblogic.application.internal.ExtensibleModuleWrapper.init(ExtensibleModuleWrapper.java:98)
	Truncated. see log file for complete stacktrace
Caused By: java.lang.IllegalArgumentException
	at com.bea.objectweb.asm.ClassReader.<init>(Unknown Source)
	at com.bea.objectweb.asm.ClassReader.<init>(Unknown Source)
	at weblogic.application.utils.annotation.ClassInfoImpl.<init>(ClassInfoImpl.java:41)
	at weblogic.application.utils.annotation.ClassfinderClassInfos.polulateOneClassInfo(ClassfinderClassInfos.java:240)
	at weblogic.application.utils.annotation.ClassfinderClassInfos.populateClassInfos(ClassfinderClassInfos.java:193)
	Truncated. see log file for complete stacktrace
```

According to similar problem reported to Spring-Boot (https://github.com/spring-projects/spring-boot/issues/13125) it is connected to ASM.

~~My suggestion: the problem is caused by setting Java 10 as a target version for compiler.~~

### Versions:

- jOOQ: 3.10.7, 3.11+
- Java: 8
- Database (include vendor): any
- OS: any
- JDBC Driver (include name if inofficial driver): any

**Comment by lukaseder** [comment]
Thank you very much for your report. Hmm, so you're using Java 10 or 8 in this case? In case you're using the `maven-compiler-plugin` version 3.7.0 (or less), I'm aware of an issue related to that plugin and ASM, where you should simply upgrade the ASM dependency to the compiler plugin. An example can be seen here:
https://stackoverflow.com/a/49398936/521799

What made you think this is jOOQ related?

**Comment by Pazus** [comment]
Ok. I see I need to provide more details on the application.
It's a Java8 application compiled with maven-compiler 3.1 with 1.8 as both source and target.
It works well on WL 12.1.3.0.0 with 3.10.7 but if I change only jooq to 3.11.X (all of them) and try to deploy it to WebLogic it fails on war start with the exception I've provided.

**Comment by Pazus** [comment]
The WebLogic server runs under jdk1.8.0_151 if it matters

**Comment by lukaseder** [comment]
I see, thanks for the updates. So there is no change to your WLS and JDK environments, just the upgrade of jOOQ to 3.11. So, the comment about Java 10 is not relevant to the problem?

> My suggestion: the problem is caused by setting Java 10 as a target version for compiler.

**Comment by Pazus** [comment]
I realized I was wrong as I noticed `<target>10</target>` but its in examples.
But the problem still remains.

**Comment by lukaseder** [comment]
OK, thanks for the update. Is there anything specific to the `war` file that might help reproduce this? I'll try reproducing this early next week. Might take a while until I get a setup with WLS that might resemble yours.

**Comment by lukaseder** [comment]
Here's another instance of this error:
- http://mail-archives.apache.org/mod_mbox/logging-notifications/201711.mbox/%3CJIRA.13120226.1511356169000.299143.1511356200159@Atlassian.JIRA%3E
- https://stackoverflow.com/q/51066919/521799
- https://stackoverflow.com/q/50607732/521799

The last link hints at this problem appearing when *running* WLS with Java 7 - which you don't. Does the problem persist when you use the jOOQ Pro Edition for Java 6?

**Comment by Pazus** [comment]
Found it! 
It's the same reason mentioned in http://mail-archives.apache.org/mod_mbox/logging-notifications/201711.mbox/%3CJIRA.13120226.1511356169000.299143.1511356200159@Atlassian.JIRA%3E

You added explicit dependency:
```
            <!-- From JDK 9 onwards, the JAXB dependency needs to be made explicit -->
            <dependency>
                <groupId>javax.xml.bind</groupId>
                <artifactId>jaxb-api</artifactId>
                <version>2.3.0</version>
            </dependency>
```
And version 2.3.0 contains version-specifica compiltion (don't remember how the feature is called but if you open `jaxb-api-2.3.0.jar` and go to `META-INF\versions\` you seу a class compiled for java 9). Such feature is not allowed on Weblogic 12.1.3, which by the way is the reason we can't update `log4j2` to something newer than `2.8.2`

**Comment by lukaseder** [comment]
Oh wow, that's a great find! Thanks for pointing this out here. Huh, I guess I will not be able to postpone cross releasing JDK 6, 8, 9 builds much longer (specifically the 8 build). This was planned for jOOQ 3.12, but I'm sure it can be backported to 3.11.

Will increase the priority of this. Will also have to think of a way to regression test this, without depending on WLS...

Perhaps, as a workaround, you could exclude that dependency from your jOOQ dependency? E.g.

```xml
<dependency>
    <groupId>org.jooq.pro</groupId>
    <artifactId>jooq</artifactId>
    <version>3.11.2</version>
    <exclusions>
        <exclusion>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
        </exclusion>
    </exclusions> 
</dependency>
```

**Comment by Pazus** [comment]
Yes, it works. At least untill you use any method introduced in 2.3.0. 
How about downgrading jaxb-api version for 3.11?

**Comment by lukaseder** [comment]
> How about downgrading jaxb-api version for 3.11?

Yes, I've thought about that, too. Does 2.2.12 work for you?

**Comment by Pazus** [comment]
Yes, with jaxb-api 2.2.12 the app deploys to WLS. Are you going to downgrade the depencency in 3.11.3?

**Comment by lukaseder** [comment]
Thanks for your verification, greatly appreciated! I'll evaluate whether the dependency can be downgraded while still working on JDK 9+ If not, cross releasing might be inevitable, even for jOOQ 3.11.

**Comment by lukaseder** [comment]
Tests all run through with the 2.2.12 dependency on jOOQ 3.11 on both JDK 10 and 8. This definitely simplifies the fix for jOOQ 3.11, when no cross releasing has to be backported.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.12 (through the new cross release mechanism, where the jaxb-api dependency is explicit only in the JDK 9+ build)

Backport scheduled for jOOQ 3.11.3 (through a downgrade of the jaxb-api dependency to 2.2.12): #7653

I will release 3.11.3 this week, with these changes: https://github.com/jOOQ/jOOQ/milestone/161

Thanks again for all your help in this issue!

**Comment by lukaseder** [comment]
The JAXB dependency must be present also in pre JDK 9 builds if jOOQ is to be built with JDK 11+. The change on jOOQ 3.12 was reverted here:
https://github.com/jOOQ/jOOQ/commit/3f76c48a0a630f0c2a6f8fd4f0e9fa831ec577b4

Cross releasing will take care of getting the dependencies right:

- JDK 9+: jaxb-api 2.3
- JDK 6-8: jaxb-api 2.2

The change in jOOQ 3.11.3 is not affected.

**Comment by lukaseder** [comment]
Related: https://github.com/jOOQ/jOOQ/issues/9401
