### ISSUE TITLE
codegen maven plugin doesn't work with maven 2.2.1

### ISSUE THREAD

**Issue by xdpsee** [jOOQ/jOOQ#7654]
### Expected behavior and actual behavior:
codegen maven plugin doesn't work with maven 2.2.1,  but maven 3 work

### Versions:

- jOOQ: 3.11.2
- Java: 1.8
- Database (include vendor): MySQL 8
- OS: macOS
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report. Maven 3.0 was released 8 years ago in 2010. Maven 2.x has reached "end of life" according to the documentation: https://maven.apache.org/docs/history.html

Please upgrade your Maven installation.

**Comment by lukaseder** [comment]
Note as a workaround, you could always run the code generator using something like the maven-antrun-plugin:

https://www.jooq.org/doc/latest/manual/code-generation/codegen-ant
