### ISSUE TITLE
Let jOOQ register itself as a JDBC driver

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7666]
jOOQ should work as a JDBC driver just like other JDBC proxies, e.g. through JDBC URLs like:

> jdbc:jooq:h2:~/test

It would then delegate all calls to the actual driver but allow for intercepting things, e.g.:

- Loading a `MockFileDatabase`
- Exposing the `ParsingConnection`
- Exposing the `DiagnosticsConnection`

This will just add an additional access path to existing functionality.

Obviously, it should register itself through `src/resources/META-INF/services/java.sql.Driver`

**Comment by epkugelmass** [comment]
As an alternative, jOOQ can register itself through the `service` facilities in module-info.java. See http://openjdk.java.net/projects/jigsaw/quick-start#services

I don't know if this can be used in conjunction with `META-INF/services`. If it can't, I imagine you'd want to stick with META-INF as the lowest-common-denominator.

**Comment by lukaseder** [comment]
>  As an alternative, jOOQ can register itself through the service facilities in module-info.java^

To my understanding, this is not an alternative but the same thing, modularised

**Comment by lukaseder** [comment]
Having looked at how users interact with jOOQ's JDBC proxies (if at all), there's always a programmatic component, e.g. to specify `Settings`, `Configuration` or other SPI. As such, the quick-and-dirty approach via JDBC URLs won't scale well (unless we encode all `Settings`, etc. as JDBC URL parameters, which seems excessive for such power user features).

I won't implement this. Programmatic APIs suffice for now.
