### ISSUE TITLE
JOOQ generator should explicitly set collation when querying `information_schema`

### ISSUE THREAD

**Issue by stellingsimon** [jOOQ/jOOQ#7669]
### Expected behavior and actual behavior:
**Actual behavior:**

We're currently experiencing subtle diffs in the JOOQ-generated meta-model when the model is generated on different machines, even though the DB setup is fully reproducible. The diffs affect the import statement order, the order of tables listed in `Schema`, the order of unique/foreign keys in `Keys`, and thereby also the value of `serialVersionUID` etc. 

This leads to distractions for the devs and worse, many unnecessary merge conflicts.

The cause turned out to be this: Depending on the DB's default collation, e.g. the tables are returned in a different order. This happens even if only ASCII characters are used for table names, e.g. `_`:

 * using collation "C", `contact_x_contact_category > contacts_configuration`
 * using collation "en_US.utf8", `contacts_configuration > contact_x_contact_category`

Unfortunately, at least Postgres doesn't allow to change a databases' default collation without recreating it from scratch. Even if that's an option, it takes a long time to pinpoint `LC_COLLATE` as the source of these random-looking diffs, which may drive away potential customers that are reluctant regarding code-generation.

**Expected behavior:**

The JOOQ generator uses a fixed collation when querying the `INFORMATION_SCHEMA`, thus ensuring byte-equal meta-model classes given that the DB was set up using exactly the same SQL statements.

PS: As of JOOQ 3.10, we can work around this issue by using the `orderProvider` configuration, but it is rather clumsy and took a bit of trial-and-error to get right:

```
package com.example;

import org.jooq.meta.CatalogDefinition;
import org.jooq.meta.CheckConstraintDefinition;
import org.jooq.meta.DataTypeDefinition;
import org.jooq.meta.Definition;
import org.jooq.meta.EnumDefinition;
import org.jooq.meta.ForeignKeyDefinition;
import org.jooq.meta.IdentityDefinition;
import org.jooq.meta.IndexDefinition;
import org.jooq.meta.RoutineDefinition;
import org.jooq.meta.SchemaDefinition;
import org.jooq.meta.SequenceDefinition;
import org.jooq.meta.TableDefinition;
import org.jooq.meta.UDTDefinition;
import org.jooq.meta.UniqueKeyDefinition;

import java.util.Comparator;

/**
 * Depending on Postgres's default collation JOOQ's generator produces different output, since e.g.:
 * <ul>
 *     <li>using collation "C", {@code contact_x_contact_category > contacts_configuration}</li>
 *     <li>using collation "en_US.utf8", {@code contacts_configuration > contact_x_contact_category}</li>
 * </ul>
 * Our Docker images use the collation "en_US.utf8", but natively installed Postgres instances may differ.
 * We use a fixed Java-based ordering to ensure the generated meta-model is byte-equal on all platforms.
 */
public class UTF8BinCollationOrderProvider implements Comparator<Definition> {

    @Override
    public int compare(Definition o1, Definition o2) {

        // excerpt from JOOQ's documentation: https://www.jooq.org/doc/3.11/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-order-provider/
        //
        // While changing the order of "top level types" (like tables) is irrelevant to the jOOQ runtime, there may be some side-effects to changing the order of
        // table columns, user-defined type attributes, routine parameters,
        // as the database might expect the exact same order as is defined in the database.

        // WARNING:
        // only re-order definitions that have no natural order, i.e. where the JOOQ generator in {@code PostgresDatabase} uses ORDER BY ...
        // ordering other definitions may result in compiler errors or more subtle bugs, e.g. if a Record constructor's argument list doesn't match the natural column order found in DB

        if (o1 instanceof TableDefinition && o2 instanceof TableDefinition) {
            return platformIndependentCompare(o1, o2);
        } else if (o1 instanceof IndexDefinition && o2 instanceof IndexDefinition) {
            return platformIndependentCompare(o1, o2);
        } else if (o1 instanceof ForeignKeyDefinition && o2 instanceof ForeignKeyDefinition) {
            return platformIndependentCompare(o1, o2);
        } else if (o1 instanceof UniqueKeyDefinition && o2 instanceof UniqueKeyDefinition) {
            return platformIndependentCompare(o1, o2);
        } else if (o1 instanceof CheckConstraintDefinition && o2 instanceof CheckConstraintDefinition) {
            return platformIndependentCompare(o1, o2);
        } else if (o1 instanceof IdentityDefinition && o2 instanceof IdentityDefinition) {
            return platformIndependentCompare(o1, o2);
        } else if (o1 instanceof SchemaDefinition && o2 instanceof SchemaDefinition) {
            return platformIndependentCompare(o1, o2);
        } else if (o1 instanceof CatalogDefinition && o2 instanceof CatalogDefinition) {
            return platformIndependentCompare(o1, o2);
        } else if (o1 instanceof EnumDefinition && o2 instanceof EnumDefinition) {
            return platformIndependentCompare(o1, o2);
        } else if (o1 instanceof DataTypeDefinition && o2 instanceof DataTypeDefinition) {
            return platformIndependentCompare(o1, o2);
        } else if (o1 instanceof SequenceDefinition && o2 instanceof SequenceDefinition) {
            return platformIndependentCompare(o1, o2);
        } else if (o1 instanceof RoutineDefinition && o2 instanceof RoutineDefinition) {
            return platformIndependentCompare(o1, o2);
        } else if (o1 instanceof UDTDefinition && o2 instanceof UDTDefinition) {
            return platformIndependentCompare(o1, o2);
        } else {
            return 0; // Retain input ordering
        }
    }

    private int platformIndependentCompare(Definition o1, Definition o2) {
        return o1.getQualifiedInputName().compareTo(o2.getQualifiedInputName());
    }
}
```

### Steps to reproduce the problem (include example code if possible):

```
-- emulate a Postgres instance with default collation en_US.utf8:
select table_schema, table_name
from information_schema.tables
order by table_schema collate "en_US.utf8", table_name collate "en_US.utf8";

-- emulate a Postgres instance with default collation C:
select table_schema, table_name
from information_schema.tables
order by table_schema collate "C", table_name collate "C";
```

### Versions:

- jOOQ: 3.11.2
- Java: 1.8
- Database (include vendor): Postgres 9.5
- OS: Linux / Windows
- JDBC Driver (include name if inofficial driver): Postgres JDBC 42.2.1

**Comment by lukaseder** [comment]
Thank you very much for your detailed report. That is a very interesting problem, indeed. I would have suggested the order provider for this, but you already know it.

https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-order-provider/

> The JOOQ generator uses a fixed collation when querying the INFORMATION_SCHEMA, thus ensuring byte-equal meta-model classes given that the DB was set up using exactly the same SQL statements.

I don't think that fixing this to something will be a good idea. Surely, utf-8 might be a good choice but there are always unexpected cases in languages like Arabic or Japanese that can only be handled properly, if things are configurable. Thus: `<orderProvider/>`.

I'm not so sure about the collation idea yet. Surely, that is an option, but it is not at as portable as you might wish. If it is difficult to guarantee a default local being correctly set on a system, it will be even more difficult to make sure all collations are even installed on your target system. Depending on the RDBMS, adding a new collation is about as difficult as changing it, so once again, jOOQ cannot assume collations, and making them configurable might work only in some environments.

The Java based solution is much more versatile and it's easy to guarantee it works. I understand that you find the order provider clumsy, but I think this might just be as good as it gets, given the clumsiness of this problem set per se.

> The diffs affect the import statement order

This is not configurable yet. It uses the JDK's default locale to sort imports using a `TreeSet`. At least, it's independent of the database and can probably be overridden easily with a command line flag passed to the code generator. Definitely worth making configurable as well. Will think about the implications.

**Comment by lukaseder** [comment]
> I have to admit my "solution" may not be one after all and propose closing this issue as WONTFIX.

Yeah, I've thought a bit more about your solution as well. After all, we'd have to allow users to provide a collation on a *per usage basis*, which would become quite hard to maintain as this would expose all the internal queries to the configuration API, making it harder to change the queries themselves, in the future. E.g. in some databases, we might choose not to have any `ORDER BY` clause at all and sort entirely in memory after fetching the objects...

I've created a separate issue for overriding the import ordering: #7680.

Notice that there are workarounds for the import ordering issue:

- You could use `<fullyQualifiedTypes/>` to avoid using imports entirely :-)
- You could override the `JavaWriter`, which takes care of writing the `import` statements in the correct order. To override it, just override `JavaGenerator.newJavaWriter()`, and then override `JavaWriter.beforeClose()`

**Comment by lukaseder** [comment]
Closing this (collations for codegen queries) as won't fix
