### ISSUE TITLE
Batch Update 

### ISSUE THREAD

**Issue by DheerajKumarReddyKotha** [jOOQ/jOOQ#7674]
### Expected behavior and actual behavior: 

When I do a batch of updates, I am expecting one long continuous query same like we get for batch of inserts but currently the logs show individual queries getting executed for updates and one long continuous query for inserts.

### Steps to reproduce the problem (include example code if possible):
                 UInteger ID = UInteger.valueOf(100);
                 final BatchBindStep query;
                query = context.get().batch(DSL
                        .update(TABLE)
                        .set(TABLE.FIELD1, (UInteger) null)
                        .where(TABLE.FIELD2.eq((UInteger) null)
                                .and(TABLE.FIELD3.eq((UInteger) null))
                                .and(TABLE.FIELD1.lt((UInteger) null)
                                        .or(TABLE.FIELD1.isNull())))
                );
                
                map.entrySet().forEach(row -> query
                        .bind(row.getValue(),ID,row.getKey(),row.getValue())
                );
                
                return query.execute();

### Versions:

- jOOQ:3.10.0
- Java:8
- Database (include vendor):MYSQL
- OS:WINDOWS
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your request.

I think you're confusing what jOOQ understands when using the terms "batch updating / inserting" and "bulk updating / inserting". A batch statement is a "batch of statements" where several statements are sent to the server in one go, but the statements are separate. A bulk statement is a single statement that operates on a "bulk of rows".

When you say, you're expecting an update statement like that other insert statement, I'm quite sure you didn't create the insert statement using `DSLContext.batch()`, but by appending new rows to it, e.g. by calling `values()` several times.

There is no equivalent form of an `UPDATE` statement in SQL, but of course, you could create your own of this style:

```sql
UPDATE t
SET v = CASE WHEN .. THEN .. WHEN .. THEN .. WHEN .. THEN .. END
WHERE ...
```

Not sure how much you'll gain from this, though.
