### ISSUE TITLE
Implement "char" (SQL) as Character (Java)

### ISSUE THREAD

**Issue by jbarop** [jOOQ/jOOQ#7687]
Hi,

I noticed that JOOQ treats single characters as strings. If I have the following table
```
CREATE TABLE "example_table" (
   "example_field" CHAR
);
```
and access the field like so `record.get(EXAMPLE_TABLE.EXAMPLE_FIELD)` a `String` is returned. I expected a `Character`.

It would be nice if `SQLDataType.CHAR` would be baked by `Character` instead of `String`. Probably a breaking change.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion.

I don't think this is a good idea to support out of the box. A SQL `CHAR` can encode any vendor specific collation and might contain UTF-8 or UTF-32 data, or any other esoteric encoding, whereas a `java.lang.Character` is guaranteed to be a UTF-16 encoded character. It would be asking for trouble to map these types by default.

However, it is very easy for you to implement a `Converter` and bind that to your generated `EXAMPLE_FIELD` meta information, such that `CHAR` and `CHAR(1)` and `VARCHAR(1)` types are automatically mapped to `java.lang.Character`

I hope this helps
