### ISSUE TITLE
JOOQ lack of some sql setence

### ISSUE THREAD

**Issue by viccP** [jOOQ/jOOQ#7704]
### Expected behavior and actual behavior:

when i try to use "update select"setence,for example:

```
UPDATE table1 alias
SET (column_name,column_name ) = (
SELECT (column_name, column_name)
FROM table2
WHERE column_name = alias.column_name)
WHERE column_name = VALUE
```
it  seems jooq not suppor this sql setence yet.

### Steps to reproduce the problem:
step1:use dsl context
step2:try to use jooq finish a update-select setence
 
so i use dsl.excute(sql) temporary

### Versions:
- jOOQ:3.11.3
- Java:1.8.0_161
- Database :mysql  Ver 14.14 Distrib 5.5.52, for osx10.8 (i386) using readline 5.1
- OS:MacOS 10.13.6
- JDBC Driver :mysql-connector-java-5.1.44.jar

**Comment by lukaseder** [comment]
What's not working?

```java
ctx.update(TABLE1)
   .set(row(TABLE1.COL1, TABLE1.COL2), 
        select(TABLE2.COL1, TABLE2.COL2).from(TABLE2).where(TABLE2.X.eq(TABLE1.X)))
   .where(TABLE1.Y.eq(value))
   .execute();
```

**Comment by lukaseder** [comment]
I hope this helps. Please let me know if I can be of any further assistance.

**Comment by viccP** [comment]
How can i do using jooq for below case:
```
update 
    table1 t1 
    left join table2 t2 on (t1.id=t2.id)
    left join table3 t3 on (t1.id=t3.id)
set 
     t1.status='2'
where 
     t2.some_val>=t3.some_val and t1.status='0'

```
this sql setence is legal and useful  in mysql 5.5.52

**Comment by lukaseder** [comment]
Does it not work to simply `TABLE1.leftJoin(TABLE2).on(...)`?

**Comment by viccP** [comment]
here is original sql
```
update 
    table1 t1 
    left join table2 t2 on (t1.id=t2.id)
    left join table3 t3 on (t1.id=t3.id)
set 
     t1.status='2'
where 
     t2.some_val>=t3.some_val and t1.status='0'

```
then i try to translate above sql such as
```
dsl.update(table1)
. leftJoin(table2).on(table1.id.eq(table2.id))
. leftJoin(table3).on(table1.id.eq(table3.id))
.set(table1.status, "2")
.where(condition here)
```
but i can't find suitable API to use.so i wonder if jooq not support update-join setence yet

**Comment by lukaseder** [comment]
Do note that `LEFT JOIN` is not a keyword / clause in the `SELECT` or `UPDATE` statements, it's an *operator* that connects two tables. As such, the fact that you can write `select(..).from(t).leftJoin(u)...` is merely syntax sugar in jOOQ's API. Behind the scenes, what you're doing is `table1.leftJoin(table2)`, i.e. you're applying the operator on the *tables* directly. So, try:

```java
dsl.update(table1 // Remove parenthesis here
. leftJoin(table2).on(table1.id.eq(table2.id))
. leftJoin(table3).on(table1.id.eq(table3.id))) // Add parenthesis here
.set(table1.status, "2")
.where(condition here)
```

**Comment by viccP** [comment]
i got your point,thanks very much :),it works
