### ISSUE TITLE
Dead link to MySQL manual on group by page

### ISSUE THREAD

**Issue by rmcloughlin** [jOOQ/jOOQ#7707]
This page https://www.jooq.org/doc/latest/manual/sql-building/sql-statements/select-statement/group-by-clause/ contains a link entitled "MySQL manual" (http://dev.mysql.com/doc/refman/5.6/en/group-by-hidden-columns.html) which is dead.

**Comment by lukaseder** [comment]
Thank you very much for reporting this.

I think the whole section about *"MySQL's deviation from the SQL standard"* could just simply be removed
