### ISSUE TITLE
getSql(ParamType.Indexed) producing named parameters

### ISSUE THREAD

**Issue by ayush-finix** [jOOQ/jOOQ#7709]
### Expected behavior and actual behavior:

With something like: 
```
final Field<BigDecimal> selectCase = DSL.when(LEDGER_ENTRIES.TYPE.eq(
        com.verygood.payments.processing.service.domain.jooq.enums.LedgerEntryType.CREDIT),
        LEDGER_ENTRIES.AMOUNT)
        .otherwise(LEDGER_ENTRIES.AMOUNT.mul(-1)).sum();
final SelectConditionStep<Record1<BigDecimal>> query = jooq.select(selectCase)
        .from(LEDGER_ENTRIES)
        .where(LEDGER_ENTRIES.ACCOUNT_ID.eq(accountId));
```
`query.getSql(ParamType.Indexed)`

produces

`select sum(case when "accounting"."ledger_entries"."type" = ?::"accounting"."ledger_entry_type" then "accounting"."ledger_entries"."amount" else ("accounting"."ledger_entries"."amount" * ?) end) from "accounting"."ledger_entries" where "accounting"."ledger_entries"."account_id" = ?`

which reads as having 3 indexed parameters + 1 named parameter when I follow https://www.jooq.org/doc/3.10/manual/sql-execution/alternative-execution-models/using-jooq-with-jpa/using-jooq-with-jpa-entities/

I'm not sure if this is a jooq issue or not, but I feel like the expected sql from Indexed wouldn't have `?::"accounting"."ledger_entry_type"` in it (https://stackoverflow.com/questions/4169582/escaping-the-colon-character-in-jpa-queries). Inlined seems to work fine, and named generates `select sum(case when "accounting"."ledger_entries"."type" = :1::"accounting"."ledger_entry_type" then "accounting"."ledger_entries"."amount" else ("accounting"."ledger_entries"."amount" * :2) end) from "accounting"."ledger_entries" where "accounting"."ledger_entries"."account_id" = :3` which reads as having 3 named parameters although one of them is `1::"accounting"."ledger_entry_type"`.

### Versions:

- jOOQ: 3.10.6
- Java: 1.8.0_172
- Database (include vendor): postgres 10.4
- OS: mac 10.13.6
- JDBC Driver (include name if unofficial driver): postgres

**Comment by lukaseder** [comment]
Thank you very much for your report. I think there's a misunderstanding here. `::` is a cast operator in PostgreSQL, so the first bind parameter is cast to the `accounting.ledger_entry_type` type (an enum, I guess?)

Is this causing problems to your usage of the SQL string?
