### ISSUE TITLE
After upgrading to java 10, jooq fails during the compilation

### ISSUE THREAD

**Issue by vicmosin** [jOOQ/jOOQ#7718]
### Expected behavior and actual behavior:
Compilation without issues
### Steps to reproduce the problem (include example code if possible):
Compilation of the programm with maven-compiler-plugin v3.8.0 gives the following error:
```
Compilation failure
/.../src/main/java/com/example/data/Tables.java:[68,8] class com.example.data.Tables clashes with package of same name
```
### Versions:

- jOOQ:3.11.3
- Java:10
- Database (include vendor):mysql
- OS:MacOS 10.13.6 (17G65)
- JDBC Driver (include name if inofficial driver): mysql-connector-java 8.0.12

### Additional notes
I am not sure, but it seems that it's somehow related to lombok. I.e. as soon as I configure maven-compiler-plugin with:
```
<plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
       <configuration>
              <annotationProcessorPaths>
                    <annotationProcessorPath>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                   </annotationProcessorPath>
              </annotationProcessorPaths>
     </configuration>
</plugin>
```
jooq starts to fail with defined exception. As soon as I remove `annotationProcessorPaths` from configuration, lombok starting to produce issues :)

**Comment by lukaseder** [comment]
@vicmosin You've closed this issue already, am I right assuming that there's no problem, after all?

**Comment by vicmosin** [comment]
@lukaseder I am sorry, I somehow managed to fix it but now have another module produces the same error. So it is actual for me

**Comment by lukaseder** [comment]
OK, I see you've added additional information related to lombok. Are you sure this issue is really related to jOOQ, though, and not just a lombok problem?

**Comment by lukaseder** [comment]
... in particular, can you provide an [MCVE](https://stackoverflow.com/help/mcve), i.e. a complete `pom.xml` file with all version numbers contained in it that helps reproduce the issue?

**Comment by vicmosin** [comment]
Looks like it's related to my local congifuration. Thanks
