### ISSUE TITLE
Add code generation flag to treat MySQL TINYINT(1) as BOOLEAN

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7719]
In MySQL, `TINYINT(1)`, by convention, is treated as a `BOOLEAN` type. We should introduce a code generation flag to expose this behaviour.

Instead of focusing only on `TINYINT(1)`, we'll add a flag that allows for replacing `INFORMATION_SCHEMA.COLUMNS.DATA_TYPE` by `INFORMATION_SCHEMA.COLUMNS.COLUMN_TYPE` for integer types:

- `tinyint`
- `smallint`
- `mediumint`
- `int`
- `bigint`

We'll add a new flag `<integerDisplayWidths>true</integerDisplayWidths>` which defaults to `true` and can be deactivated to get the old behaviour of jOOQ 3.11.

With the above flag in place, it's now possible to force `TINYINT(1)` and similar types to `BOOLEAN`:

```xml
<forcedType>
  <name>BOOLEAN</name>
  <types>(?i:(TINY|SMALL|MEDIUM|BIG)?INT(UNSIGNED)?\(1\))</types>
</forcedType>
```

----
See also:
https://stackoverflow.com/q/51694152/521799

**Comment by pareklund** [comment]
Until 3.12.0 is released, is there a workaround other than manually map from Byte in the POJO class to boolean in my domain class?

**Comment by lukaseder** [comment]
@pareklund Sure! You could use programmatic code generator configuration to generate the regular expression that matches all the `TINYINT(1)` columns in your schema:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-programmatic

Alternatively, you map directly from the jOOQ record to your domain class using jOOQ's `Record.into(DomainClass.class)` method. It can translate between numeric and boolean types.

**Comment by pareklund** [comment]
Ok, thanks for the quick reply!

**Comment by lukaseder** [comment]
I've documented this also on the blog: https://blog.jooq.org/2019/09/27/how-to-map-mysqls-tinyint1-to-boolean-in-jooq/
