### ISSUE TITLE
Slow query - not a bug, but something to look at

### ISSUE THREAD

**Issue by aram535** [jOOQ/jOOQ#7743]
### Expected behavior and actual behavior:

The generation of tables is throwing a "Slow query".   Most likely this is a one-off as there is a massive SQL job running this morning but the expected behaviour should be that the generator does not need to look at EVERY schema int he database.   It should be limited to the SCHEMAS listed in the database section of the DSL (only 7).  Currently, it's pulling over 40 schemas that have thousands of columns.

### Steps to reproduce the problem (include example code if possible):

Using excludes we exclude a lot of the schemas that are not relevant to the application:

```
         generator {
             name = 'org.jooq.util.DefaultGenerator'
             strategy {
                 name = 'org.jooq.util.DefaultGeneratorStrategy'
             }   
             database {
                 name = 'org.jooq.util.mysql.MySQLDatabase'
                 excludes = 'archive.*... ' 

```

Aug 10, 2018 4:40:18 AM org.jooq.tools.JooqLogger warn
WARNING: Slow SQL                 : Total: 11.69s
Aug 10, 2018 4:40:18 AM org.jooq.tools.JooqLogger warn
WARNING: Slow SQL                 : jOOQ Meta executed a slow query (slower than 5 seconds)

Please report this bug here: https://github.com/jOOQ/jOOQ/issues/new

```sql
select 
  `information_schema`.`COLUMNS`.`TABLE_SCHEMA`, 
  `information_schema`.`COLUMNS`.`COLUMN_COMMENT`, 
  `information_schema`.`COLUMNS`.`TABLE_NAME`, 
  `information_schema`.`COLUMNS`.`COLUMN_NAME`, 
  `information_schema`.`COLUMNS`.`COLUMN_TYPE`
from `information_schema`.`COLUMNS`
where (
  `information_schema`.`COLUMNS`.`COLUMN_TYPE` like 'enum(%)'
  and (
    `information_schema`.`COLUMNS`.`TABLE_SCHEMA` in (
      'information_schema', ....  full list of schemas ..., 'mysql', 'performance_schema', 'sys'
    )
    or 1 = 0
  )
)
order by 
  `information_schema`.`COLUMNS`.`TABLE_SCHEMA` asc, 
  `information_schema`.`COLUMNS`.`TABLE_NAME` asc, 
  `information_schema`.`COLUMNS`.`COLUMN_NAME` asc
```

org.jooq.util.AbstractDatabase$1$SQLPerformanceWarning
        at org.jooq.util.AbstractDatabase$1.executeEnd(AbstractDatabase.java:283)
        at org.jooq.impl.ExecuteListeners.executeEnd(ExecuteListeners.java:146)
        at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:260)
        at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:344)
        at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:314)
        at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2594)
        at org.jooq.util.mysql.MySQLDatabase.getEnums0(MySQLDatabase.java:395)
        at org.jooq.util.AbstractDatabase.getEnums(AbstractDatabase.java:1445)
        at org.jooq.util.JavaGenerator.generateSchemaIfEmpty(JavaGenerator.java:361)
        at org.jooq.util.JavaGenerator.generateCatalogIfEmpty(JavaGenerator.java:350)
        at org.jooq.util.JavaGenerator.generate(JavaGenerator.java:324)
        at org.jooq.util.GenerationTool.run(GenerationTool.java:639)
        at org.jooq.util.GenerationTool.generate(GenerationTool.java:200)
        at org.jooq.util.GenerationTool.main(GenerationTool.java:172)

### Versions:

- jOOQ: 3.10.1
- Java: 8
- Database (include vendor): mysql 5.7
- OS: Linux
- JDBC Driver (include name if inofficial driver): com.mysql.cj.jdbc.Driver 6.0.6

**Comment by lukaseder** [comment]
Thank you very much for reporting. You're saying:

> It should be limited to the SCHEMAS listed in the database section of the DSL (only 7). Currently, it's pulling over 40 schemas that have thousands of columns.

And then you're listing:

> ```sql
> `information_schema`.`COLUMNS`.`TABLE_SCHEMA` in (
>       'information_schema', ....  full list of schemas ..., 'mysql', 'performance_schema', 'sys'
>     )
> ```

Does this "full list of schemas" really contain 7 or 40 schemas? It should contain 7.

Would you mind showing that "database section of the DSL" to see if there's a potential misconfiguration?

**Comment by aram535** [comment]
Well, 40 is an over exaggeration but it isn't 7 either. 
```sql
select 
  `information_schema`.`COLUMNS`.`TABLE_SCHEMA`, 
  `information_schema`.`COLUMNS`.`COLUMN_COMMENT`, 
  `information_schema`.`COLUMNS`.`TABLE_NAME`, 
  `information_schema`.`COLUMNS`.`COLUMN_NAME`, 
  `information_schema`.`COLUMNS`.`COLUMN_TYPE`
from `information_schema`.`COLUMNS`
where (
  `information_schema`.`COLUMNS`.`COLUMN_TYPE` like 'enum(%)'
  and (
    `information_schema`.`COLUMNS`.`TABLE_SCHEMA` in (
      'information_schema', 'A1', 'A2', 'C1', 'C2', 'C3.', 'D1', 
      'D2', 'I1', 'M2', 'N1', 'N2', 'N3', 'O1', 'Q1', 
      'R1', 'S1', 'S2', 'S3', 'S4', 'S5', 'T1', 'T2', 
      'U3', 'b1', 'mysql', 'performance_schema', 'sys'
    )
    or 1 = 0
  )
)
order by 
  `information_schema`.`COLUMNS`.`TABLE_SCHEMA` asc, 
  `information_schema`.`COLUMNS`.`TABLE_NAME` asc, 
  `information_schema`.`COLUMNS`.`COLUMN_NAME` asc
```

The exclude in the build should be excluding more than half of the schemas listed.

**Comment by aram535** [comment]
And here is the database { ... } section 
```
 database {
                 name = 'org.jooq.util.mysql.MySQLDatabase'
                 excludes = 'a1.*|c1.*|s1.*|information_schema.*|b1.*|c2.*|mysql.*|O1.*|performance_schema.*|Q1.*|R1.*|sys.*|T1.*|T2.*'
                forcedTypes { ... repeats about 12 times } 
```

**Comment by aram535** [comment]
No, we don't have inputSchema defined -- that's the misunderstanding.  I assume the exclude would happen after "discovery" before the actual query.  I think I can reverse the exclude to a bunch of includes to resolve this.

**Comment by lukaseder** [comment]
I think there's still a misunderstanding here. You cannot solve this with includes / excludes. Both of these regular expressions are applied in the client using Java regexes. They are not sent to the database in the form of SQL queries. In order to reduce the number of schemas that are part of your reported SQL query, you really need to use `inputSchema`
