### ISSUE TITLE
Add support for ALTER TABLE ONLY

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7751]
When working with table hierarchies, PostgreSQL has a special `ONLY` clause that allows for altering only that specific table, not the entire hierarchy:
https://www.postgresql.org/docs/current/static/sql-altertable.html

We should reflect that in the jOOQ API and in the parser. See #7745

**Comment by brmeyer** [comment]
Hey @lukaseder, what are the chances we could simply ignore the `ONLY` clause while parsing, in the short term for `DDLDatabase`'s sake?

**Comment by lukaseder** [comment]
Thanks for your comment, @brmeyer. I'll have a look at your other issue first (#8907) to give you a more complete answer. What I can say now already is that `ONLY` is a concept that spreads across DDL and DML in both PostgreSQL and the SQL standard, and I would prefer not to implement a quick fix here.

We can have a look at this in jOOQ 3.13, though.

Do note that jOOQ 3.12 (due soon) will implement a thorough workaround, where you can use a special SQL comment syntax that will make jOOQ ignore some parts of your input SQL: https://github.com/jOOQ/jOOQ/issues/8325

Until then, the workaround is to preprocess your SQL files prior to passing them to the `DDLDatabase`, with some regex replacement.

**Comment by lukaseder** [comment]
... It appears that pgdump blindly appends this clause even if no table inheritance is involved :( This is a good reason to increase the priority of fixing this.

**Comment by lukaseder** [comment]
Well, I thought this `ONLY` keyword appears also in other DDL statements (e.g. `DROP`) but it seems it doesn't. It does appear in DML statements:

**`SELECT`**

![image](https://user-images.githubusercontent.com/734593/60803451-82432a80-a17b-11e9-9762-adb68612e326.png)

**`UPDATE`**

![image](https://user-images.githubusercontent.com/734593/60803463-8bcc9280-a17b-11e9-859f-572f9550e015.png)

**`DELETE`**

![image](https://user-images.githubusercontent.com/734593/60803470-91c27380-a17b-11e9-9005-5e7ca3391060.png)

We currently support the keyword via `PostgresDSL.only()` for DML statements. This issue will not bind the keyword to that API, as it would not allow for emulating it on `DDLDatabase`'s H2 database right now. We'll do that at a later stage.

**Comment by lukaseder** [comment]
This is now parsed and ignored in jOOQ 3.12

**Comment by brmeyer** [comment]
Amazing, thanks @lukaseder! And agree, I was surprised to see pg_dump throwing that in for no particular reason...

**Comment by lukaseder** [comment]
Well, the pg_dump output is targeted for PostgreSQL to consume, so I guess it's not an unreasonable default.
