### ISSUE TITLE
Add an integration test to discover all DSL API that is not covered by the parser

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7755]
Current integration / unit tests check whether the parser produces the same result as a hand-written DSL statement. This works very well, but has a minor flaw: We do not detect if there is DSL API that has not yet been covered by the parser.

Such a new agent based integration test would help make the parser more complete.

Missing features include:

- [ ] `DATE_SUB`
- [ ] `TIMESTAMP_SUB`
- [ ] `TIMESTAMP_ADD`

----
See also:
https://groups.google.com/forum/#!topic/jooq-user/GyeeCyqH0z0

**Comment by knutwannheden** [comment]
I take it that the intended scope of this issue is to make sure that all *supported* built-in functions are covered by the tests.

I am hoping we can modify and reuse our current bytecode instrumentation logic for this use case somehow.

I am also wondering how the parser should deal with unsupported built-in functions and other stored procedures. But that is of course a different issue.

**Comment by lukaseder** [comment]
> I take it that the intended scope of this issue is to make sure that all supported built-in functions are covered by the tests.

Yes of course. Any built in function present in `DSL` should be reachable and called through some path by the parser.

> I take it that the intended scope of this issue is to make sure that all supported built-in functions are covered by the tests.

That's what I was hoping, too :)

> I am also wondering how the parser should deal with unsupported built-in functions and other stored procedures. But that is of course a different issue.

https://github.com/jOOQ/jOOQ/issues/7344

**Comment by knutwannheden** [comment]
I was thinking that the parser test could register a callback with the test agent, much like it already implicitly happens for integration tests. But since the `jOOQ-test-agent` project already depends on `jOOQ` this will be a bit problematic.

Options to resolve this which I can see:

1. Use Java reflection to register the callback in the test code.
2. Pass some kind of command line option to the agent.
3. Move the test out of project `jOOQ`.
4. Move the agent into the `jOOQ` project.

Of these I probably like 4 best. It would of course also entail making the Javassist dependency somehow development-time only. Or maybe the `provided` scope can be used?

**Comment by knutwannheden** [comment]
To expand on the idea with the callback: The agent would still intercept certain method calls, but the interceptor would not directly call some hardcoded callback, but instead dispatch using a static list of registered listeners. So the test would before a test runs (i.e. using `@Before` or `@BeforeClass`, as appropriate), register a callback using a static method provided by the agent.

**Comment by knutwannheden** [comment]
Instead of moving the whole Java agent from `jOOQ-test-agent` to `jOOQ`, we could also just move the static dispatcher and listener list. This could be a good first step. Any proposal for where to put such an internal (yet public) class in `jOOQ`? Should we create a new `internal` subpackage?

**Comment by lukaseder** [comment]
I prefer *3. Move the test out of project jOOQ.*

> It would of course also entail making the Javassist dependency somehow development-time only. Or maybe the provided scope can be used?

I see adding a dependency to the runtime API as a show stopper for this option. These kinds of tests should have zero impact on the the user experience of anyone using the API, so if it cannot reside in the test scope of the jOOQ artifact only, but needs to enter the jar scope, then I think it should be moved out of the jOOQ artifact.

**Comment by lukaseder** [comment]
> Any proposal for where to put such an internal (yet public) class in jOOQ? Should we create a new internal subpackage?

The question that should be asked here is what do we gain from adding new public API, even if it is marked internal? It seems like a workaround for a dependency problems we have in testing and we only lose as we increase the API surface without adding any value. OTOH, moving tests outside of the module is quasi free.

**Comment by knutwannheden** [comment]
Moving the tests out of jOOQ works for me. I will look into it.

**Comment by knutwannheden** [comment]
Note: One problem which we won't be able to solve is that some built-ins can have different names or aliases in various dialects. E.g. `SQRT` vs `SQR`.

**Comment by knutwannheden** [comment]
Committed a first implementation of this test with https://bitbucket.org/jooq/jooq/commits/b7dd847a2262ff16b31e09dad853549baadec727.

As already mentioned the current test won't be able to make sure that the parser can successfully parse all dialects of a given built-in function. E.g. `TIMESTAMPADD` or `TIMESTAMP_ADD`. This would require yet more sophisticated testing.

**Comment by knutwannheden** [comment]
A follow-up issue will be created to complete the parser test suite with tests for yet uncovered built-in functions.

**Comment by lukaseder** [comment]
> Note: One problem which we won't be able to solve is that some built-ins can have different names or aliases in various dialects. E.g. SQRT vs SQR.

Indeed, I'm not sure if this is really easily testable. We don't know what other syntax there is, out there, and whether it is really representable through existing jOOQ API.

Would be nice if somehow this could be discovered, though. I cannot think of anything.

**Comment by knutwannheden** [comment]
This issue mentions `TIMESTAMP_ADD` and `TIMESTAMP_SUB`. There are indeed SQL dialects out there which have functions by this name (e.g. Google BigQuery), although none of which are supported by jOOQ at this time. Curiously jOOQ's manual also refers to `TIMESTAMP_ADD`: https://www.jooq.org/doc/3.12/manual/sql-building/column-expressions/date-and-time-functions/.

This being said, some of the supported dialects do have a `TIMESTAMPADD` function and / or `DATE_ADD` or `DATEADD` functions. These require dialect specific parsing: https://blog.jooq.org/2014/02/06/youre-very-likely-to-have-gotten-sql-date-time-arithmetic-wrong/.

**Comment by lukaseder** [comment]
> This issue mentions TIMESTAMP_ADD and TIMESTAMP_SUB. There are indeed SQL dialects out there which have functions by this name (e.g. Google BigQuery), although none of which are supported by jOOQ at this time. 

The reason for this naming was the pre-existence of `DATE_ADD` and `DATE_SUB` functions in a variety of dialects, and thus I wanted to have consistent naming for timestamps. Unlike with SQL dialects, jOOQ cannot easily overload `DATE_ADD` to support both `DATE` and `TIMESTAMP` types, because of generic type erasure. I.e. these overloads are not possible in Java:

- `dateAdd(Field<Date>, ...)`
- `dateAdd(Field<Timestamp>, ...)`
