### ISSUE TITLE
How to use custom sql in orderBy

### ISSUE THREAD

**Issue by cdxf** [jOOQ/jOOQ#7781]
I want to use `orderBy` function with custom sql like this;

` ORDER BY ts_rank(p_search.document, to_tsquery('english', 'Endangered & Species')) DESC;`

But `orderBY` only allows me to choose specific fields. Currently, I can use custom SQL statement in WHERE clause but not in ORDER BY clause, is there any reason for this?

**Comment by lukaseder** [comment]
The plain SQL convenience methods in the SELECT API are limited to a few clauses. There's a pending feature request to change this: #5003

In the meantime, do notice that the plain SQL `WHERE` clause overload is simply convenience for wrapping your plain SQL string in an actual `Condition` type, through `DSL.condition(...)`. In your case, use one of the `DSL.field(String, Object...)` overloads.
