### ISSUE TITLE
Support Java 8 only in Professional and Enterprise Edition

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7789]
The new support scheme is:

- ~Java 6-7: Works on Enterprise Edition only~ Support will be dropped: https://github.com/jOOQ/jOOQ/issues/11196
- Java 8: Works on Professional Edition and Enterprise Edition
- Java 11+ Works on Open Source Edition, Professional Edition, and Enterprise Edition

**Comment by lukaseder** [comment]
We do not really profit from a lot of Java 11 features (yet). The only useful dependency is the `Flow` API dependency, which we introduced with #4371

Given the Java 8 / Java 11 market shares, for one more release (jOOQ 3.12), we could have the jOOQ Open Source Edition support Java 8, still, and implement this change in jOOQ 3.13 only.

**Comment by marshallpierce** [comment]
FWIW my dayjob (and all my side projects) are on Java 11+, so if it makes your life easier to only support 11, we won't mind! Also, who are these people who are staying up to date on libraries but not JVMs? I haven't met them but I suppose they must be out there :thinking: 
We will be exploring modularization soon now that Gradle 6.4 supports it out of the box.

**Comment by lukaseder** [comment]
> FWIW my dayjob (and all my side projects) are on Java 11+, so if it makes your life easier to only support 11, we won't mind!

Thanks for increasing the survey sample from 0 to 1 😁

> Also, who are these people who are staying up to date on libraries but not JVMs? I haven't met them but I suppose they must be out there 🤔

Different cost centre. Libraries are usually managed by developers (flexible). JVMs are managed by operations (inflexible).

**Comment by lukaseder** [comment]
Let's run a survey on Twitter: https://twitter.com/lukaseder/status/1256135063948976129. It's already some feedback, better than nothing.

**Comment by marshallpierce** [comment]
> Different cost centre. Libraries are usually managed by developers (flexible). JVMs are managed by operations (inflexible).

Ah yes. I had suppressed the memories of working in Big Enterprise. Those shops can pay for a license to get Java 8 or worse, though. :)

**Comment by lukaseder** [comment]
> Ah yes. I had suppressed the memories of working in Big Enterprise. Those shops can pay for a license to get Java 8 or worse, though. :)

Not saying they shouldn't but again, that's a different cost centre. It's not a matter of being able to afford it. It's a matter of being able to activate the huge supply chain machinery that is the purchasing department. :)

**Comment by lukaseder** [comment]
Postponing for another minor release. Not enough people are on Java 11 yet, and the Java 11 distribution doesn't offer enough value yet, other than a `module-info` file and `Flow` usage.

**Comment by lukaseder** [comment]
Starting with jOOQ 3.15, support for Java 6 and 7 will be dropped: #11196. In that context, I'll revisit this issue here to increase the value proposition of the Professional and Enterprise Editions

**Comment by lukaseder** [comment]
Done. We'll document this via the support matrix, too: https://github.com/jOOQ/jOOQ/issues/11993
