### ISSUE TITLE
Add Settings.namedParamPrefix to generate "$n" parameter notation in PostgreSQL

### ISSUE THREAD

**Issue by yonigibbs** [jOOQ/jOOQ#7797]
Postgres has a slightly different standard from most databases for parameters to be bound into a prepared query or a batch. For example, rather than:
`INSERT INTO some_table VALUES (?, ?)`
or
`INSERT INTO some_table VALUES (:1, :2)`
in Postgres this syntax can be used instead:
`INSERT INTO some_table VALUES ($1, $2)`

(See [here](https://www.postgresql.org/docs/10/static/sql-prepare.html) for examples of this.)

If using jOOQ to generate SQL (but not to run it), this can be quite important. For example, if using [reactive-pg-client](https://github.com/reactiverse/reactive-pg-client), the `$n` syntax is required, as (I think) the SQL is passed through the Postgres, and it's IT which does the parameter value substitution.

I can't see a way to get the SQL generated by calling `Query.getSQL` to use this syntax. As far as I can see it's hard coded to use a colon in `org.jooq.impl.Val.getBindVariable()`.

Is my understanding right, or is there a way to do this that I've not found?

Assuming there isn't currently a way to do this, I wonder if this is something that could be added to jOOQ?  I'm happy to submit a pull request with this change if you think this is useful.  Below is one possible approach, based on a quick look at the code (so no doubt I've missed stuff!).  However I'm happy to do something completely different if you have another preference.

Thanks!

**Possible solution:**
Rather than hard-coding anything about dollar signs or anything, this relies on passing in a function which will customise how named parameters are injected into the SQL.
- In the `org.jooq.Context` interface, add a new property called `namedParameterSupplier`, of type `BiFunction<String, Integer, String>`. This is a function which will be called to get the string to inject into the SQL for a bind parameter. This function will take in two parameters: the parameter name and the parameter index (in the particular case of Postgres only the index is required, but supplying the name will allow for other customisations that may be required by other systems: maybe this is YAGNI?). The function will return a string containing the text to inject into the SQL.
- In `org.jooq.Query` add an overload of `getSql` that takes in a `namedParameterSupplier` (which implicitly sets the `paramType` to `NAMED`. This works as per the other overloads, but when constructing a `RenderContext` (in `DefaultDSLContext.renderNamedParams`) it will additionally pass the supplied function into the context so it's available later when binding the parameter value.
- In `org.jooq.impl.Val.getBindVariable()` update the code to check this `namedParameterSupplier` property from the `ctx` variable.  If it's null, stick to the current behaviour, otherwise invoke the function instead and get it to generate the value to inject, as shown below:

```
    final String getBindVariable(Context<?> ctx) {
        if (ctx.paramType() == NAMED || ctx.paramType() == NAMED_OR_INLINED) {
            int index = ctx.nextIndex();
            if (ctx.namedParameterSupplier() == null) {
                if (StringUtils.isBlank(getParamName()))
                    return ":" + index;
                else
                    return ":" + getParamName();
            } else {
                return ctx.namedParameterSupplier().apply(getParamName(), index);
            }
        }
        else {
            return "?";
        }
    }
```

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I think there is already a similar feature request somewhere, but I cannot seem to find it. In any case, I agree, we should make this configurable.

This should be done through a new `Settings` and it will affect (at least) three places:

1. The generation of such bind variables when rendering SQL
2. The plain SQL parser that replaces bind placeholders by actual values when inlining
3. The parser

Note, I don't think your suggested implementation is correct. Only the `:index` syntax should be affected. Or, perhaps, we should rather introduce a new param type. Something like `NUMBERED` that would default to `:index` in most databases and to `$index` in PostgreSQL

**Comment by yonigibbs** [comment]
Cool, thanks Lukas.  Sounds like you think it's best for someone who knows the code better than me to make the change (which sounds sensible to me), so I'll leave it with you.

But if you want me to have a bash, I'm happy to try, if you just point me at the relevant bits in the code for the points above.

Cheers!

**Comment by lukaseder** [comment]
> Sounds like you think it's best for someone who knows the code better than me to make the change (which sounds sensible to me), so I'll leave it with you.

Sure, that's what I had thought - especially bullets 2 and 3 might not be trivial

**Comment by lukaseder** [comment]
This has already been implemented in jOOQ 3.12 for other reasons (R2DBC support): https://github.com/jOOQ/jOOQ/issues/8486. I'm closing this as a duplicate.

**Comment by EMIR1HUB** [comment]
The project has jooq 3.19.3. When I use `:1` in a query, the values are substituted into the query, but when I use `$1`, jooq does not substitute. 

This is what Log looks like

ERROR: parameter $1 does not exist
  Where: PL/pgSQL function inline_code_block, line 5, SQL statement
	at org.jooq_3.19.3.POSTGRES.debug(Unknown Source)

**Comment by lukaseder** [comment]
@EMIR1HUB: Please, can you open a new support issue and provide complete information.
