### ISSUE TITLE
How to automatically inject entity class nested entity properties ?

### ISSUE THREAD

**Issue by lapDog** [jOOQ/jOOQ#7805]
i use lefe join anothor table, like this.

```java
public List<TXbCouponFlowInfoForm> getUserXbcouponAvailable(Integer userid){
		Table table = T_XBCOUPON.as("xbcoupon");
		return create.select(getBaseColumnList(table.fields())).from(T_XBCOUPON_FLOW)
				.leftJoin(table).on(T_XBCOUPON_FLOW.COUPONID.eq(((TXbcoupon) table).ID))
				.where(T_XBCOUPON_FLOW.USERID.eq(userid))
				.and(T_XBCOUPON_FLOW.STATUS.eq(1))
				.fetchInto(TXbCouponFlowInfoForm.class);
	}
```

and my entity like this.

```
@EqualsAndHashCode(callSuper = true)
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TXbCouponFlowInfoForm extends TXbcouponFlow {

    private TXbcoupon xbcoupon;

}
```

TXbcoupon,It's an auto-generated entity by JOOQ-codegen...but, xbcoupon is null...No automatic injection.
So,how to do this...like mybatis association or collections.
### Versions:

- jOOQ:3.11.3
- Java:1.8
- Database (include vendor): mysql
- OS: win10
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your message. The `DefaultRecordMapper` currently does not officially support nested records, but there's an undocumented feature that you might be interested in using. When you rename all the columns joined from `TXbcoupon` to `xbcoupon.<column_name>`, then jOOQ will do the nested record mapping automatically. Note that `xbcoupon` matches the name of your property in the `TXbCouponFlowInfoForm` class.

I hope this helps

**Comment by lapDog** [comment]
But it didn't work. 😭

**Comment by lapDog** [comment]
@lukaseder help,,

**Comment by lapDog** [comment]
![1535106504 1](https://user-images.githubusercontent.com/11813246/44580360-3fc76800-a7cc-11e8-8617-8858933d24bc.jpg)
![1535106526 1](https://user-images.githubusercontent.com/11813246/44580364-42c25880-a7cc-11e8-981d-083bc02a6090.jpg)
![1535106669 1](https://user-images.githubusercontent.com/11813246/44580367-4524b280-a7cc-11e8-9e7d-675264093442.jpg)
![1535106736 1](https://user-images.githubusercontent.com/11813246/44580371-46ee7600-a7cc-11e8-9e27-452e735b4763.jpg)

this is my test msg...What's wrong? bro... @lukaseder

**Comment by lukaseder** [comment]
I'm sorry, I should have been more precise. Your column has to be named `"xbcoupon.id"`, so rename it `TABLE.ID.as("xbcoupon.id")`

**Comment by lapDog** [comment]
It's working, but it's a bit cumbersome. I hope the new version is better. Thank you.
