### ISSUE TITLE
codegen-maven support lombok annotation?

### ISSUE THREAD

**Issue by lapDog** [jOOQ/jOOQ#7806]
i wanna use lombok annotation on entity,But it seems that the entity class generated by the Codegen-maven is not supported. 

- jOOQ:3.11.3
- Java:1.8
- Database (include vendor):mysql
- OS:win10
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your enquiry. Please refer to the manual section about custom code sections to be added to the code generator:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-custom-code

In a similar way as you can add custom code sections, you can override the `JavaGenerator.printClassAnnotations()` method to specify the annotations that you would want to be generated on any of your classes.

I hope this helps
