### ISSUE TITLE
JOOQ execute insert  lost data

### ISSUE THREAD

**Issue by deepbreath** [jOOQ/jOOQ#7812]
### Expected behavior and actual behavior:

I use paging to request the server to get goods data, 1000 data per page,In client get all the response data
when l  execute 
"dbContext().insertInto(GOODS).set(record).onDuplicateKeyUpdate().set(record).execute();"
it will be insert 80000 data,but just insert 50000 data.
And primary key is not repeated.

### Steps to reproduce the problem (include example code if possible):

for(GoodsInfoRecord  record:params){
dbContext().insertInto(GOODS).set(record).onDuplicateKeyUpdate().set(record).execute();``
}

### Versions:

- jOOQ:3.8.6
- Java:1.8
- Database (include vendor):postgresql10
- OS: windows10 64bit
- JDBC Driver (include name if inofficial driver):

**Comment by deepbreath** [comment]
@lukaseder

**Comment by lukaseder** [comment]
Thank you very much for your report. I'm assuming from your last comment and the fact that you've closed this issue already that you were able to resolve it?

If not, please let me know and I will be very happy to assist you.

**Comment by lukaseder** [comment]
@deepbreath I'm sorry, but I really cannot help you with the information you've provided so far. Your second example doesn't seem to be strictly related to your first one, and I don't see how you got to the second one from the first one. Also, I would definitely need some information helping me to reproduce your problem in addition to your description of the problem.

Here's a very good resource explaining how to provide an MCVE (Minimal, Complete, Verifiable Example): https://stackoverflow.com/help/mcve

I'll be very happy to help, but I definitely need more information
