### ISSUE TITLE
SQLServer NVARCHAR column query parameter is set as VARCHAR

### ISSUE THREAD

**Issue by kwonnamsonwwh** [jOOQ/jOOQ#7825]
### Expected behavior and actual behavior:
I'm researchig jOOQ Professional trial to use in our project with SQLServer 2017.

When there is NVARCHAR column and when the column is used as a query parameter, 
the parameter must be set with PreparedStatement.setNString() or setObject() with type java.sql.JDBCType#NVARCHAR.

But jOOQ uses PreparedStatement.setString().

This behavior causes problems when VARCHAR and NVARCHAR are used together.

### Steps to reproduce the problem (include example code if possible):
1. just make a table with nvarchar and varchar  columns. (`public final TableField<ContractTypeRecord, String> Contract_Nm = createField("Contract_Nm", org.jooq.impl.SQLDataType.NVARCHAR(50), this, "");`
2. execute query with nvarchar column query parameter in where clause. `where(CONTRACT_TYPE.Contract_Nm.eq("P"))`

### Versions:

- jOOQ: Professional trial 3.11.4
- Java: Oracle JDK 8u171
- Database (include vendor): MS SQLServer 2017 Linux version
- OS: SQL Server on Docker, java application on Windows 10
- JDBC Driver (include name if inofficial driver): com.microsoft.sqlserver:mssql-jdbc:6.4.0.jre8

**Comment by lukaseder** [comment]
Thank you very much for your message. Indeed, currently, jOOQ treats `VARCHAR` and `NVARCHAR` types alike, which is not correct for all databases and collations. The workaround right now is to implement your own custom data type binding and apply that to all generated classes:
https://www.jooq.org/doc/latest/manual/code-generation/custom-data-type-bindings

Let me know if you need any help with that and I will be very happy to assist you.

**Comment by kwonnamsonwwh** [comment]
I tried with the following Binding. but `NVARCHARJooqBinding#set(org.jooq.BindingSetStatementContext<java.lang.String>)` never called.
```
public class NVARCHARJooqBinding implements Binding<String, String> {
    @Override
    public Converter<String, String> converter() {
        return new Converter<String, String>() {
            @Override
            public String from(String s) {
                return s;
            }

            @Override
            public String to(String s) {
                return s;
            }
            @Override
            public Class<String> fromType() {
                return String.class;
            }
            @Override
            public Class<String> toType() {
                return String.class;
            }
        };
    }

 // this method is called
    @Override
    public void sql(BindingSQLContext<String> ctx) throws SQLException {
        ctx.render().visit(DSL.val(ctx.convert(converter()).value())).sql("");
    }

    @Override
    public void register(BindingRegisterContext<String> ctx) throws SQLException {
        ctx.statement().registerOutParameter(ctx.index(), Types.NVARCHAR);
    }

// this is never called
    @Override
    public void set(BindingSetStatementContext<String> ctx) throws SQLException {
        ctx.statement().setNString(ctx.index(), ctx.value());
    }

    @Override
    public void set(BindingSetSQLOutputContext<String> ctx) throws SQLException {
        throw new SQLFeatureNotSupportedException("bindingSetSQLOutputContext not supported.");
    }

    @Override
    public void get(BindingGetResultSetContext<String> ctx) throws SQLException {
        ctx.convert(converter()).value(ctx.resultSet().getNString(ctx.index()));
    }

    @Override
    public void get(BindingGetStatementContext<String> ctx) throws SQLException {
        ctx.convert(converter()).value(ctx.statement().getNString(ctx.index()));
    }

    @Override
    public void get(BindingGetSQLInputContext<String> ctx) throws SQLException {
        throw new SQLFeatureNotSupportedException("bindingGetSQLInputContext not supported.");
    }
}
```

jOOQ generate column like the following
```
    public final TableField<BooksRecord, String> title = createField("title", org.jooq.impl.SQLDataType.NVARCHAR(128).nullable(false), this, "", new NVARCHARJooqBinding());
```
I made a query like the following
```
jooqDsl.selectFrom(BOOKS.with("NOLOCK"))
                .where(BOOKS.title.eq(title))
                .fetch();
```

**Comment by lukaseder** [comment]
Thank you very much for adding these details. The implementation looks correct. I will investigate this soon.

**Comment by lukaseder** [comment]
Thank you very much for your patience. I wasn't able to immediately reproduce this issue as I erroneously thought this might have anything to do with the fact that both `<T>` and `<U>` are bound to the same type `String`.

The problem is really that the manual is misleading / wrong about the `sql()` implementation. I have created a separate issue for fixing the manual: #7864

```java
    public void sql(BindingSQLContext<String> ctx) throws SQLException {
        if (ctx.render().paramType() == ParamType.INLINED)
            ctx.render().visit(DSL.inline(ctx.value()));
        else
            ctx.render().sql("?");
    }
```

I hope this helps
