### ISSUE TITLE
InformationSchema.toString() methods generate empty <comment> elements

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7827]
The `XMLGenerator` produces empty `<comment></comment>` elements, which is unnecessary:

```xml
        <column>
            <table_catalog></table_catalog>
            <table_schema>PUBLIC</table_schema>
            <table_name>T_725_LOB_TEST</table_name>
            <column_name>LOB</column_name>
            <data_type>BLOB</data_type>
            <character_maximum_length>2147483647</character_maximum_length>
            <numeric_precision>0</numeric_precision>
            <numeric_scale>0</numeric_scale>
            <ordinal_position>2</ordinal_position>
            <is_nullable>true</is_nullable>
            <comment></comment>
        </column>
```

**Comment by lukaseder** [comment]
We'll fix this in jOOQ 3.12 only, as the way these XML contents are generated have been changed recently:

- JAXB is being removed
- We're generating `toString()` methods and use those, instead of marshalling the contents

**Comment by knutwannheden** [comment]
As a result of this change the `InformationSchemaTest` in the `jOOQ-test-codegen-no-jaxb` now fails. If this is due to a regression with respect to the JAXB serializer's behavior, this change might have to be partially reverted.

**Comment by lukaseder** [comment]
@knutwannheden It seems that there is no regression here. The adapted `MiniJAXB` / `toString()` implementation seems to be consistent with JAXB. This means the test and the previous implementation were wrong. I will fix accordingly

**Comment by knutwannheden** [comment]
Even better!
