### ISSUE TITLE
Does JOOQ support mysql's substring_Index function?

### ISSUE THREAD

**Issue by liqiaolin520** [jOOQ/jOOQ#7832]
Does JOOQ support mysql's substring_Index function?

If you support, please tell me how to use it!thank you

**Comment by lukaseder** [comment]
Thanks for your request.

You can use jOOQ's `POSITION()` function support through `DSL.position()`

**Comment by liqiaolin520** [comment]
Are there any cases?Please demonstrate!Because I looked, still do not know how to use!

**Comment by lukaseder** [comment]
Consider `SUBSTRING_INDEX(string, delimiter, number)`

You can emulate this function using the appropriate jOOQ API for:

```java
SUBSTRING(string, POSITION(string, delimiter, number))
```

Or, you can write your own plain SQL template:

```java
public static Field<String> substringIndex(Field<String> string, Field<String> delimiter, Field<Integer> number) {
    return DSL.field("substring_index({0}, {1}, {2})", SQLDataType.VARCHAR, string, delimiter, number);
}
```

See:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

**Comment by liqiaolin520** [comment]
Thanks, got it!I'm going to do that for any function that I don't cover

**Comment by mataoqun** [comment]
Thank you for your reply, I know how to do it.

**Comment by lukaseder** [comment]
For the record, we'll implement native support for this function in jOOQ 3.15: https://github.com/jOOQ/jOOQ/issues/11647
