### ISSUE TITLE
Allow projecting record into a table alias

### ISSUE THREAD

**Issue by vojtapol** [jOOQ/jOOQ#7840]
I have a query similar to this:

```java
Book thriller = BOOK.as("thriller_book");
Book comedy = BOOK.as("comedy_book");
Book fiction = BOOK.as("fiction_book");

Author a = jooq.select()
    .from(AUTHOR)
    .leftJoin(thriller).on(AUTHOR.THRILLER_BOOK_ID.eq(thriller.ID))
    .leftJoin(comedy).on(AUTHOR.COMEDY_BOOK_ID.eq(comedy.ID))
    .leftJoin(fiction).on(AUTHOR.FICTION_BOOK_ID.eq(fiction.ID))
    .fetchInto(Author.class)
```

This results in a record that has some fields from table AUTHOR and then 3 times identically named fields from table BOOK with different prefixes where they belong to either thriller, comedy or fiction. 

I would like a way to "project" the fields into Book DTO by their resulting table name like so:
```java
Book comedyBook = record.into("comedy").into(Book.class);
```

Currently I guess I could do it by calling `record.fields()` and then iterate over all the fields and filter out those that have a table name starting with "comedy" like so:
```java
TableField[] comedyFields = Arrays.stream(record.fields())
    .filter(f -> ((TableField) f).getTable().getQualifiedName().getName()[0].startsWith("comedy"))
    .toArray(TableField[]::new);

Book comedyBook = record
    .into(comedyFields)
    .into(BOOK)
    .into(Book.class);
```

Am I missing an easy way to do this?

**Comment by lukaseder** [comment]
Hmm, well for starters, your logic here:

```java
TableField[] comedyFields = Arrays.stream(record.fields())
    .filter(f -> ((TableField) f).getTable().getQualifiedName().getName()[0].startsWith("comedy"))
    .toArray(TableField[]::new);
```

Can be replaced by this:

```java
Field<?>[] comedyFields = comedy.fields();
```

Otherwise, I'm not quite sure how to help you as I don't fully understand the use-case. What's the idea behind author having a foreign key to three categories of books? Is there a reason why you haven't normalised this?

**Comment by vojtapol** [comment]
Lukas, your suggestion works perfectly. My code ends up looking like this:

```java
Book comedyBook = record.into(BOOK.as("comedy")).into(Book.class);
```

with which I am more than happy.

The reason why this is not normalized is because in my case there will never be more than these three "book types" so I don't want to have another table.

Feel free to close this issue. Thank you very much.

**Comment by lukaseder** [comment]
Thanks for the feedback. I'm happy to hear it worked out for you.
