### ISSUE TITLE
Condition.toString()  renders incorrectly for Field.likeRegex(String pattern)

### ISSUE THREAD

**Issue by maxkremer** [jOOQ/jOOQ#7842]
### Expected behavior and actual behavior:

`Field.likeRegex('patten').toString()` renders incorrectly.

Renders as  **fieldname like_regex '[pattern]'**, expected behaviour is to render as **fieldname ~ '[pattern]'**

Weird thing is when you're executing the query direct with JOOQ agains the db the SQL is correct. It only happens when trying to stringify parts of the query.

### Steps to reproduce the problem (include example code if possible):
```
System.out.println(DSL.field("foobar", String.class).likeRegex( "\\m(google|youtube)\\.").toString());
```	    
	 

### Versions:

- jOOQ: 3.10.1
- Java: 1.8.0_60
- Database (include vendor): postgresql9.5
- OS: ubuntu 14
- JDBC Driver (include name if inofficial driver): postgresql-42.2.2.jar

**Comment by lukaseder** [comment]
The `QueryPart.toString()` method does not generate any predictable SQL string, specifically, the `SQLDialect` is not defined for such a method call. If you want to extract vendor specific SQL from a `QueryPart`, use the various `DSLContext.render(QueryPart)` methods.

Hope this helps
