### ISSUE TITLE
Add support for SQLite window functions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7865]
See:
https://sqlite.org/releaselog/3_25_0.html

Xerial is not up to date yet:
https://search.maven.org/search?q=sqlite-jdbc

**Comment by knutwannheden** [comment]
Now Xerial is up to date.

**Comment by lukaseder** [comment]
Excellent news, thanks for the pointer, @knutwannheden. Will update jOOQ immediately, for version 3.12

**Comment by lukaseder** [comment]
Unfortunately, SQLite doesn't fully support the `WINDOW` clause, which is why it will be emulated: #8279
