### ISSUE TITLE
DataType defaultValue type doesn't have to be the same of the field itself

### ISSUE THREAD

**Issue by gustavecha** [jOOQ/jOOQ#7869]
Hi,

I'm currently discovering Jooq and it appears that the type of a default value assigned to a field to build a CREATE TABLE statement should be the same as the field.
For instance, I can't write :
DataType<UUID> a = SQLDataType.UUID;
a.defaultValue("gen_random_uuid()");

while it is perfectly right in postgresql.

How can I manage to set such a function like gen_random_uuid() to my UUID field as default value?
Thanks in advance for any useful help, all the best

### Versions:

- jOOQ: 3.11.5
- Java: 8
- Database (include vendor): Postgresql-10.2
- OS: Ubuntu
- JDBC Driver (include name if inofficial driver): no driver

**Comment by lukaseder** [comment]
Note that `DataType` is an immutable data type, so `a.defaultValue("...")` has no effect on `a`, but returns a new `DataType` instance. Does that answer your question?

**Comment by gustavecha** [comment]
Thanks @lukaseder 
Given problem is when I code a.defaultValue("gen_random_uuid()");, I get an error because 
defaultValue(String) isn't available for DataType<UUID> although it returns a new DataType instance.

This would help a lot to set String default values for non-String DataTypes :)

**Comment by lukaseder** [comment]
Oh, I see - sorry for the confusion on my side.

The method you're looking for is `DataType.defaultValue(Field<T>)`, where you can pass any `Field<UUID>` reference, including one that you can construct using the plain SQL templating API:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

So, write:

```java
a.defaultValue(field("gen_random_uuid()", UUID.class));
```

**Comment by gustavecha** [comment]
You were right, it works perfectly.
Thanks !
