### ISSUE TITLE
Add support for Java 11

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7870]
Java 11 will soon be released:
http://openjdk.java.net/projects/jdk/11

jOOQ 3.12 should formally support Java 11

**Comment by lukaseder** [comment]
There are still some ASM transitive dependency issues, especially when building the Maven plugin. Let's wait again for a while with this task.

**Comment by ieugen** [comment]
Any ETA on this? We are planing a migration for Java 11 and then I saw this which is a blocker. Java 8 is EOL in a few weeks so kind of no way out.

**Comment by lukaseder** [comment]
@ieugen Thanks for your message. jOOQ 3.12 will officially support Java 11. jOOQ 3.11 is already integration tested with Java 11. If you have found any issues, please do report them and we'll look into it.
