### ISSUE TITLE
Convert Avro schema to CREATE TABLE statements with Jooq

### ISSUE THREAD

**Issue by gustavecha** [jOOQ/jOOQ#7875]
Hi,

I think I'm getting lost in translating Avro schemas to CREATE TABLE statement for PgSQL with Jooq.
Such schemas give all details needed to build a table, but fields typing is getting really hard.
https://avro.apache.org/docs/1.8.2/spec.html

There is no problem to map common Avro types to Jooq types. Issues rise when converting from Avro Fixed type (let's say JSON string) to Jooq type with converter
https://www.jooq.org/doc/3.11/manual/sql-building/queryparts/custom-bindings/

For instance, Avro doesn't know what UUID is and we should define a fixed type (i.e a custom type) in the JSON schema definition.
Or Jooq doesn't have built-in JSON type, nor Avro.
How could I iterate over my fields and make an efficient mapping without if .... UUID then... else JSON then... ELSE otherType then... ?
This would remove the big advantage of Avro to define completely custom types.

Is it possible to have some generic field type in Jooq to let Avro stands for {name:"myField", type:[null,"blablabla"]} and get a SQL string "myField null blablabla DEFAULT NULL" ?

Thanks in advance

### Versions:

- jOOQ: 3.11.5
- Java: 8
- Database (include vendor): PgSQL 10
- OS: Ubuntu
- JDBC Driver (include name if inofficial driver): no driver

**Comment by lukaseder** [comment]
Thank you very much for your message.

There is currently no supported public API for this, but you can create a new jOOQ type by using internal API, e.g.

```java
new DefaultDataType(SQLDialect.POSTGRES, Object.class, "blablabla");
```

Despite this being internal, it will not break any time soon in the future. I hope this helps

**Comment by gustavecha** [comment]
Sounds good with DefaultDataType. Thank you :)

Why restricting this DefaultDataType to Jooq internal use?

**Comment by lukaseder** [comment]
> Why restricting this DefaultDataType to Jooq internal use?

Because unless a sufficient number of people provides a sufficient number of credible use-cases, any jOOQ functionality better stay internal (and usually final and package private). 10 years of jOOQ experience shows that internal, final, and private is always the best default.
