### ISSUE TITLE
Single element array expressions must generate trailing comma in H2

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#7878]
### Expected behavior and actual behavior:
The following query returns an Integer[] array result with two elements rather than an array with a nested array as the second element:

```java
DSLContext create = DSL.using(conn, SQLDialect.H2);
Result<?> result = create.select(array(1, array(2))).from(dual()).fetch();
```

This is also similar to what the following query returns (although here the result is an Object[] array):

```java
DSLContext create = DSL.using(conn, SQLDialect.H2);
Result<Record> result = create.resultQuery("select (1, (2)) from dual").fetch();
```

This query returns the expected result (note the trailing comma for the nested array):

```java
DSLContext create = DSL.using(conn, SQLDialect.H2);
Result<Record> result = create.resultQuery("select (1, (2,)) from dual").fetch();
```

A minor glitch is also that when the last query's result is formatted as CSV (using `formatCSV()`) the result looks something like this:

```java
"1, (2,)"
"[1, [Ljava.lang.Object;@13526e59]"
```

### Steps to reproduce the problem (include example code if possible):

See above.

### Versions:

- jOOQ: 3.12
- Java: 10.0.2
- Database (include vendor): H2
- OS: OSX
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can reproduce this issue. Interestingly, this test doesn't fail:

```java
    @Test
    public void testH2SingleElementArrays() {

        // [#7878] In H2, a single element array needs to be rendered as (1,)
        Integer[] array = create().fetchValue(select(array(1)));
        assertEquals(1, array.length);
        assertEquals(1, (int) array[0]);
    }
```

Because of the type information available to jOOQ, and the internal implicit conversions, jOOQ automatically converts the single `Integer` value that is returned from H2 into an `Integer[]`...

**Comment by knutwannheden** [comment]
Interesting. I did actually also test `select(array(1))` and was surprised to get back an Integer[], but didn't investigate it any further.

**Comment by lukaseder** [comment]
OK, so the second query in this test fails as expected:

```java
    @Test
    public void testH2SingleElementArrays() {

        // [#7878] In H2, a single element array needs to be rendered as (1,)
        Integer[] a1 = create().fetchValue(select(array(1)));
        assertEquals(1, a1.length);
        assertEquals(1, (int) a1[0]);

        Object[] a2 = (Object[]) create().fetchValue(create().select(array(1)).getSQL(INLINED));
        assertEquals(1, a1.length);
        assertEquals(1, (int) a1[0]);
    }
```

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.12. Backports scheduled for 3.11.6 (#7883) and 3.10.9 (#7884).

Thanks again for reporting!

**Comment by lukaseder** [comment]
Btw, notice, you don't need `.from(dual())` in jOOQ :-)

jOOQ will generate the `FROM` clause if necessary, and avoid it otherwise, if you just run a `select(...).fetch()`. Some details here:
https://www.jooq.org/doc/latest/manual/sql-building/table-expressions/dual

**Comment by lukaseder** [comment]
I know :-) Well, the SQL standard requires a `FROM` clause:

```
<query specification> ::=
  SELECT [ <set quantifier> ] <select list> <table expression>

<table expression> ::= 
  <from clause> 
    [ <where clause> ] 
    [ <group by clause> ] 
    [ <having clause> ] 
    [ <window clause> ]
```

And the SQL standard also specifies a `VALUES` clause or table value constructor:

```
<query expression> ::=
  [ <with clause> ] <query expression body>
    [ <order by clause> ] [ <result offset clause> ] [ <fetch first clause> ]

<query expression body> ::=
    <query term>
  | <query expression body> UNION [ ALL | DISTINCT ]
    [ <corresponding spec> ] <query term>
  | <query expression body> EXCEPT [ ALL | DISTINCT ]
    [ <corresponding spec> ] <query term>
  
<query term> ::=
    <query primary>
  | <query term> INTERSECT [ ALL | DISTINCT ]
    [ <corresponding spec> ] <query primary>

<query primary> ::=
    <simple table>
  | <left paren> <query expression body>
    [ <order by clause> ] [ <result offset clause> ] [ <fetch first clause> ] <right paren>

<simple table> ::=
    <query specification>
  | <table value constructor>
  | <explicit table>
 
<table value constructor> ::=
VALUES <row value expression list>
```

So th standard way to get something "from dual" would be:

```sql
SELECT * FROM (VALUES(1)) t(c)
```

Having a known dual table is nice too, of course.
