### ISSUE TITLE
Invalid javadoc created for deprecated data types

### ISSUE THREAD

**Issue by McNetic** [jOOQ/jOOQ#7893]
### Expected behavior and actual behavior:
For deprecated types, jooq inserts a \@deprecated javadoc tag with a hint to <deprecationOnUnknownTypes/>. This should be enclosed in a \@literal tag, because it causes the javadoc to be invalid because of non-matching tags, which in turn is a javadoc error since java 8. 

### Steps to reproduce the problem (include example code if possible):
See above

### Versions:

- jOOQ: 3.11.5
- Java: 8
- Database (include vendor): Oracle, but should not matter
- OS: Windows/Linux
- JDBC Driver (include name if inofficial driver): ojdbc, but should not matter

**Comment by lukaseder** [comment]
Thanks a lot for the report and the suggested fix. I agree that the generated code's Javadoc should be linted according to the standard

**Comment by lukaseder** [comment]
Thanks a lot for the report and for the suggested fix. I agree that the generated Javadoc should pass doclint's default setting.

In the jOOQ API, we've turned it off:

```xml
<additionalparam>-Xdoclint:none</additionalparam>
```

This might work as a workaround for the time being.

**Comment by McNetic** [comment]
Thank you. I disabled generation of deprecation for unknown fields for the time being; it is only one historical XMLTYPE field in our whole model anyways.

**Comment by lukaseder** [comment]
Integrated in jOOQ 3.12. Backport to 3.11.6 scheduled (#7895).

Thanks again!
