### ISSUE TITLE
Add support for H2 window functions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7906]
The upcoming H2 version 1.4.198 is going to support window functions, see:

- https://github.com/h2database/h2database/pull/1453
- https://github.com/h2database/h2database/pull/1454
- https://github.com/h2database/h2database/pull/1457
- https://github.com/h2database/h2database/pull/1461

And various others.

**Comment by katzyn** [comment]
@lukaseder
It looks like you missed `GROUP` in `WindowRowsStep` and non-default `EXCLUDE` clauses in `WindowSpecificationExcludeStep`.
https://github.com/h2database/h2database/blob/cc90f2178c0db3c40e3cfc1263012ba72d736057/h2/src/docsrc/help/help.csv#L2575-L2608

**Comment by lukaseder** [comment]
@katzyn Thanks a lot for the pointer. I must have overlooked this for some reason. Excellent! :) I'll have to update this blog post as well:
https://blog.jooq.org/2018/07/05/postgresql-11s-support-for-sql-standard-groups-and-exclude-window-function-clauses/
