### ISSUE TITLE
Overload fetchXYZ(T, Collection<? extends Condition>) and fetchXYZ(T, Condition...)

### ISSUE THREAD

**Issue by jpomykala** [jOOQ/jOOQ#7914]
### Expected behavior and actual behavior:
Actual:
```
Condition withEmail = U.EMAIL.eq(authEmail);
context.fetchOne(U, withEmail);
```

Expected:

```
Condition withEmail = U.EMAIL.eq(authEmail);
Condition isEnabled = U.ENABLED.isTrue();
context.fetchOne(U, List.of(withEmail, isEnabled));
```

### Versions:

- jOOQ: 3.10.6

What do you think about this? I'm ready to contribute if necessary.

**Comment by lukaseder** [comment]
How about just using `DSL.and(withEmail, isEnabled)`, or even `withEmail.and(isEnabled)`?

**Comment by lukaseder** [comment]
Thanks for the feedback, @jpomykala.

I've given this some thought. The expectation is clearly to be offered with several convenience overloads throughout the jOOQ API:

- `method(Condition)`
- `method(Condition...)`
- `method(Collection<? extends Condition>)`

There isn't really a good reason why these overloads shouldn't be offered in this particular API. So, we'll add it.
