### ISSUE TITLE
Use H2 1.4.198 domain qualification for enums stored as domains

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7917]
With change https://github.com/h2database/h2database/issues/1261#issuecomment-402644993 in H2 1.4.198, stored enum types are now stored as domains, and their definition is referenced from `INFORMATION_SCHEMA.COLUMNS.COLUMN_TYPE` (see also #1507 for column type qualification).

This change broke our logic in `H2Database`, so we need to:

- Discover enum types from the `INFORMATION_SCHEMA.DOMAINS` table as well
- Link them in the code generator
- Generate qualified enums if they're stored as domains

**Comment by katzyn** [comment]
For the next version of H2 (201) `INFORMATION_SCHEMA` is significantly changed. Old (1.4.200 compatible with some additions) information schema can be also accessed with `;OLD_INFORMATION_SCHEMA=TRUE` setting in connection URL and this setting may be removed in 202, for example. It is designed as temporary workaround only.

Presence of `INFORMATION_SCHEMA.INFORMATION_SCHEMA_CATALOG_NAME` table indicates that the new information schema is used.

In the new information schema enum values can be read from `INFORMATION_SCHEMA.ENUM_VALUES` for both domain-based types and column-based types.
```SQL
CREATE DOMAIN D AS ENUM('a', 'b');
> ok

CREATE TABLE T(A ENUM('c', 'd'), B D);
> ok

TABLE INFORMATION_SCHEMA.INFORMATION_SCHEMA_CATALOG_NAME;
>> SCRIPT

SELECT * FROM INFORMATION_SCHEMA.ENUM_VALUES WHERE OBJECT_SCHEMA = 'PUBLIC'
    AND OBJECT_NAME = 'T' AND OBJECT_TYPE = 'TABLE';
> OBJECT_CATALOG OBJECT_SCHEMA OBJECT_NAME OBJECT_TYPE ENUM_IDENTIFIER VALUE_NAME VALUE_ORDINAL
> -------------- ------------- ----------- ----------- --------------- ---------- -------------
> SCRIPT         PUBLIC        T           TABLE       1               c          1
> SCRIPT         PUBLIC        T           TABLE       1               d          2
> SCRIPT         PUBLIC        T           TABLE       2               a          1
> SCRIPT         PUBLIC        T           TABLE       2               b          2
> rows: 4

SELECT * FROM INFORMATION_SCHEMA.ENUM_VALUES WHERE OBJECT_SCHEMA = 'PUBLIC'
    AND OBJECT_NAME = 'D' AND OBJECT_TYPE = 'DOMAIN';
> OBJECT_CATALOG OBJECT_SCHEMA OBJECT_NAME OBJECT_TYPE ENUM_IDENTIFIER VALUE_NAME VALUE_ORDINAL
> -------------- ------------- ----------- ----------- --------------- ---------- -------------
> SCRIPT         PUBLIC        D           DOMAIN      TYPE            a          1
> SCRIPT         PUBLIC        D           DOMAIN      TYPE            b          2
> rows: 2
```
`ENUM_IDENTIFIER` is the value of `DTD_IDENTIFIER` from `INFORMATION_SCHEMA.COLUMNS` or `INFORMATION_SCHEMA.DOMAINS`.

---

For 201, enum ordinal values are changed to be 1-based by default. Persistent databases from older versions must be opened with `;ZERO_BASED_ENUMS=TRUE` in JDBC connection URL.

---

It is possible that there will be two releases with different default values of many settings, a compatible one and the new one, but final decision wasn't made yet.

**Comment by lukaseder** [comment]
Thanks for the heads-up, @katzyn

**Comment by lukaseder** [comment]
Implementing this now for H2 1.4.200, as the code generation support for `DOMAIN` types (#681) will produce regressions if we don't do this here.

**Comment by lukaseder** [comment]
This was a single line change, only `DOMAINS.DOMAIN_TYPE != 'ENUM'` needed to be added to the `H2Database::getDomains0` query
