### ISSUE TITLE
Documentation examples using jOOQ with JPA show wrong Query.getParams() usage

### ISSUE THREAD

**Issue by gregorko** [jOOQ/jOOQ#7937]
I'm using JOOQ to build the SQL query but will execute the query through an alternative way like described here.
http://www.jooq.org/doc/3.11/manual-single-page/#alternative-execution-models
I came across an issue where parameters get inlined and therefore the number of parameters did not match the query.
Basically my code is very similar to what is described as the second example in the paragraph:
http://www.jooq.org/doc/3.11/manual-single-page/#using-jooq-with-jpa-native

```
    // Extract the bind values from the jOOQ query:
    int i = 0;
    for (Param<?> param : query.getParams().values()) {
        result.setParameter(i + 1, convertToDatabaseType(param));
        i++;
    }
```
When parameters are in lined, the number of parameters that getParams() returns will be higher then the number of placeholders in the query. Therefore I this example will not work. I also tried to use query.getSQL(NAMED). But the positioning will also not match.

I know I can use query.getBindValues() but as I understand this might limit the usage of custom data types or bindings. Maybe a method like Query.getParams(ParamType) could help? This could then return the parameters matching the placeholder of the build SQL.

- jOOQ: 3.10

**Comment by lukaseder** [comment]
Hi @gregorko 

I'm very sorry for the delay in this. The issue tracker notification email must have been lost. Indeed, there are some cases where the example doesn't work. In this particular case, I recommend adding a particular check `&& !param.isInline()` to the loop.

Will fix the examples to include this check.

**Comment by lukaseder** [comment]
The correct loop is:

```java
    // Extract the bind values from the jOOQ query:
    int i = 1;
    for (Param<?> param : query.getParams().values())
        if (!param.isInline())
            result.setParameter(i++, convertToDatabaseType(param));
```

**Comment by lukaseder** [comment]
I think there are already other issues requesting additional API to get a hold of a `Param` list which models only actual bind parameters, not inline values. In particular, that type should be a list, which guarantees order more formally than a `Map.values()` call, which relies on a specific `Map` implementation's iteration order (`LinkedHashMap` in this case)

**Comment by lukaseder** [comment]
Manual updated. New version will go live soon.
