### ISSUE TITLE
Incorrect Javadoc entry for Field#containsIgnoreCase

### ISSUE THREAD

**Issue by ccjmne** [jOOQ/jOOQ#7938]
I came across a slip-up in the Javadoc for `Field#containsIgnoreCase(Field<String> value)`:

https://github.com/jOOQ/jOOQ/blob/5a958a8df9843d8b2cbe58d41e6664b417b78d63/jOOQ/src/main/java/org/jooq/Field.java#L1674-L1690

This method is described as: _translating to `this not ilike ...`_ while it should be: `this ilike ...`, just like the `#likeIgnoreCase(String, char)` it is conceptually similar to.

That's just a problem with the documentation: the actual implementation in `AbstractField` is fine.

I've had a thorough look for other potential mishaps of the same sort in that same interface but couldn't find any. I hope it's not too insignificant for a PR...

**Comment by lukaseder** [comment]
Thanks a lot for your contribution! Nice catch.

> I hope it's not too insignificant for a PR...

Not at all! We like to have accurate documentation, so every single issue found and fixed is greatly appreciated :-)

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.12. Backport scheduled for 3.11.8 (#8049) and 3.10.9 (#8050)
