### ISSUE TITLE
Add SQLDataType.INSTANT

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#7952]
We should support the JSR 310 data type `java.time.Instant`, which can be easily populated from `BIGINT`, `TIMESTAMP`, and `TIMESTAMP WITH TIME ZONE` data types.

Especially when working with PostgreSQL, `TIMESTAMP WITH TIME ZONE` is really just a unix timestamp, i.e. a `java.time.Instant`

**Comment by lukaseder** [comment]
The application of this type can be achieved e.g. by using:

```xml
<forcedType>
  <name>INSTANT</name>
  <type>(?i:TIMESTAMP\ WITH\ TIME\ ZONE)</type>
</forcedType>
```

**Comment by alamothe** [comment]
Will this work for `BIGINT`? Thanks!

**Comment by alamothe** [comment]
👍  This is what I'm doing now. I was under the impression that I could skip the converter now. Thanks for the clarification!

**Comment by JanecekPetr** [comment]
Is this a duplicate of #5663?

**Comment by lukaseder** [comment]
Yes, thanks a lot for spotting @JanecekPetr

**Comment by dmsergeevN26** [comment]
> Nope, the converter can be skipped for `TIMESTAMP WITH TIME ZONE` data types only

If i remove the `forcedType` config it converts TIMESTAMP WITH TIME ZONE into OffsetDateTime not Instant. What am I missing?

**Comment by alex-lx** [comment]
Does this work for `TIMESTAMP` in MySQL?

**Comment by lukaseder** [comment]
MySQL doesn't have a `TIMESTAMP WITH TIME ZONE` style data type, so we do not currently support `INSTANT` for MySQL. Adding `@Support` annotations on `SQLDataType` constants should make this more clear in the future: https://github.com/jOOQ/jOOQ/issues/6741

**Comment by adrianmsmith** [comment]
Note that the above code is now:
```
<forcedType>
  <name>INSTANT</name>
  <types>(?i:TIMESTAMP\ WITH\ TIME\ ZONE)</types>
</forcedType>
```
(plural `<types>`) in newer jOOQ versions.

**Comment by lukaseder** [comment]
Thanks for the hint, @adrianmsmith. I've updated my comment

**Comment by benstpierre** [comment]
Why not have built in support for time stamp mapping to instant? Seems like a common use case and writing a converter is fine for me but would intimidate some newer jooq users.

**Comment by lukaseder** [comment]
Thanks for your comment, @benstpierre. jOOQ has built in support for mapping `TIMESTAMPTZ` to `Instant`. It's just not the default, as we've followed the JDBC specification of mapping `TIMESTAMP WITH TIME ZONE` to `OffsetDateTime`.

You don't need a converter, just use data type rewrites. Also, no need to be intimidated. For all practical purposes, `Instant` and `OffsetDateTime` are the same data type, the latter is following the JDBC spec and the SQL standard more closely than the former.

I hope this helps

**Comment by matusfaro** [comment]
For newer jooq users (like me) or for the lazy, here is an implementation that:
- Works for both creating schema and codegen (from the created schema)
- Uses JOOQ 3.16.10 (last minor version supporting Java 11)
- Uses Mysql 5.7
- Custom DataType to produce `DATETIME(precision)` in mysql; doesn't use `INSTANT` as it causes: `error in your SQL syntax: 'instant(6) not null'`
- Assumes mysql's `--explicit-defaults-for-timestamp` is set to prevent default value and on update clause. Workaround is to create field as `nullable(true)` and after table schema creation, set it back to non null if needed.

### Setup

Define explicit mysql `DATETIME` data type for schema creation:
```java
// MoreSQLDataType.java
public static final DataType<LocalDateTime> DATETIME = new BuiltInDataType<>(LocalDateTime.class, "datetime(p)");
```

Since codegen will pick up DATETIME and a LocalDateTime, define a converter into Instant
```java
// LocalDateTimeToInstantConverter
public class LocalDateTimeToInstantConverter extends AbstractConverter<LocalDateTime, Instant> {

    public LocalDateTimeToInstantConverter() {
        super(LocalDateTime.class, Instant.class);
    }

    @Override
    public Instant from(LocalDateTime t) {
        return t == null ? null : t.toInstant(ZoneOffset.UTC);
    }

    @Override
    public LocalDateTime to(Instant u) {
        return u == null ? null : LocalDateTime.ofInstant(u, ZoneOffset.UTC);
    }
}
```

For storing an Instant, handle precision problems in a `Binding` that wraps the converter:
```java
// LocalDateTimeToInstantBinding.java
public class LocalDateTimeToInstantBinding implements Binding<LocalDateTime, Instant> {

    private static final long serialVersionUID = 1;

    private final Converter<LocalDateTime, Instant> converter;
    private final Binding<LocalDateTime, Instant> delegate;

    public LocalDateTimeToInstantBinding() {
        this.converter = new LocalDateTimeToInstantConverter();
        this.delegate = DefaultBinding.binding(this.converter);
    }

    @Override
    public final Converter<LocalDateTime, Instant> converter() {
        return converter;
    }

    @Override
    public final void sql(BindingSQLContext<Instant> ctx) throws SQLException {
        delegate.sql(ctx);
    }

    @Override
    public final void register(BindingRegisterContext<Instant> ctx) throws SQLException {
        delegate.register(ctx);
    }

    @Override
    public final void set(BindingSetStatementContext<Instant> ctx) throws SQLException {
        Instant value = ctx.value();
        PreparedStatement statement = ctx.statement();
        if (value == null) {
            statement.setNull(ctx.index(), Types.TIMESTAMP);
        } else {
            Timestamp timestamp = Timestamp.from(value);
            TimeZone utcTimeZone = TimeZone.getTimeZone(ZoneId.of(ZoneOffset.UTC.getId()));
            Calendar calendar = Calendar.getInstance(utcTimeZone);
            statement.setTimestamp(ctx.index(), timestamp, calendar);
        }
    }

    @Override
    public final void set(BindingSetSQLOutputContext<Instant> ctx) throws SQLException {
        delegate.set(ctx);
    }

    @Override
    public final void get(BindingGetResultSetContext<Instant> ctx) throws SQLException {
        ResultSet resultSet = ctx.resultSet();
        TimeZone utcTimeZone = TimeZone.getTimeZone(ZoneId.of(ZoneOffset.UTC.getId()));
        Calendar calendar = Calendar.getInstance(utcTimeZone);
        Timestamp timestampUtc = resultSet.getTimestamp(ctx.index(), calendar);

        if (timestampUtc == null) {
            ctx.value(null);
        } else {
            ctx.value(timestampUtc.toInstant());
        }
    }

    @Override
    public final void get(BindingGetStatementContext<Instant> ctx) throws SQLException {
        delegate.get(ctx);
    }

    @Override
    public final void get(BindingGetSQLInputContext<Instant> ctx) throws SQLException {
        delegate.get(ctx);
    }
}
```

### Usage

Create table:
```java
mysql.createTableIfNotExists("account")
        .column("created", MoreSQLDataType.DATETIME(6).notNull())
        ...
```

Codegen with config as code:
```java
// JooqGenerator.java
GenerationTool.generate(new Configuration()
        .withGenerator(new Generator()
                .withDatabase(new Database()
                        .withForcedTypes(new ForcedType()
                                .withUserType(Instant.class.getCanonicalName())
                                .withIncludeTypes("(?i:DATETIME)")
                                .withBinding(LocalDateTimeToInstantBinding.class.getCanonicalName())))
        ...
```
Generates code:
```java
// Account.java
public final TableField<JooqAccountRecord, Instant> CREATED = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "", new LocalDateTimeToInstantBinding());
```

**Comment by lukaseder** [comment]
Thanks, @matusfaro. Mind creating a new issue for this? I'd say this is a bug:

> * Custom DataType to produce `DATETIME(precision)` in mysql; doesn't use `INSTANT` as it causes: `error in your SQL syntax: 'instant(6) not null'`

Regarding:

> * Assumes mysql's `--explicit-defaults-for-timestamp` is set to prevent default value and on update clause. Workaround is to create field as `nullable(true)` and after table schema creation, set it back to non null if needed.

Yeah, what a terrible historic "feature." I've also talked MariaDB out of continuing support for this: https://jira.mariadb.org/browse/MDEV-28470
