### ISSUE TITLE
Generated wrong code when a mysql table's field has comment

### ISSUE THREAD

**Issue by kenvix** [jOOQ/jOOQ#7958]
### Expected behavior and actual behavior:
compile my code successfully, but failed.     
![image](https://user-images.githubusercontent.com/4546175/47253575-7ac1e100-d487-11e8-8537-e7c701710677.png)

![image](https://user-images.githubusercontent.com/4546175/47253572-6a116b00-d487-11e8-9940-9d49fe9ee207.png)

### Steps to reproduce the problem (include example code if possible):
Create a mysql table with a field which has some comments.      
for example:      
```sql
CREATE TABLE `commentserver`.`Untitled`  (
  `pid` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'aaa',
  `name` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NOT NULL COMMENT 'aaa',
  PRIMARY KEY (`pid`) USING BTREE,
  UNIQUE INDEX `name`(`name`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Dynamic;
```
### Versions:

- jOOQ: 3.11.5
- Java: 11
- Database (include vendor): com.mysql.jdbc.Driver
- OS: Windows 10.0.17763.55
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your report. It looks like you're using jOOQ 3.11 to generate code, but jOOQ 3.10 (or older) to compile the generated code. Can you confirm?

**Comment by kenvix** [comment]
Thank you for your reply, look like it is really using jOOQ 3.10. I still don't know why jooq 3.10 is installed :(
