### ISSUE TITLE
Code generation for 2 Schemas

### ISSUE THREAD

**Issue by batousik** [jOOQ/jOOQ#7964]
I want to generate POJOs for 2 out of 300 schemas available in Oracle DB, but in xml I can only pass an empty tag for all schemas or single schema name.

```xml
<element name="inputSchema" type="string" default="" minOccurs="0" maxOccurs="1">
        <annotation><appinfo><jxb:property><jxb:javadoc><![CDATA[The schema that is used locally as a source for meta information.
<p>
This cannot be combined with the {@link #getSchemata()} configuration element.
If left empty (and without any {@link #getSchemata()} configuration element), jOOQ will generate all available schemata.]]></jxb:javadoc></jxb:property></appinfo></annotation>
      </element>
```

### Versions:

- jOOQ: 3.11.5
- Java: 1.8
- Database (include vendor): Oracle 11.2.0.4.0
- OS: win 7
- JDBC Driver (include name if inofficial driver): com.oracle.ojdbc6:11.2.0.3

**Comment by lukaseder** [comment]
Thanks for your message. The top level `inputSchema` element is a convenient form of doing what you have described: Supply only one schema to the code generator configuration.

You can use the `<schemata>` element to specify several schemas in one go, see also:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-catalog-and-schema-mapping

I hope this helps

**Comment by batousik** [comment]
found example for gradle, thanks.
`// Two schemas from any catalog
myConfigurationName(sourceSets.main) {
  generator {
    database {
      schemata {
        schema {
          inputSchema = 'schema1'
        }
        schema {
          inputSchema = 'schema2'
        }
      }
    }
  }
}
`
