### ISSUE TITLE
question:how to update record without null filed? like mybatis updateByPrimaryKeySelective

### ISSUE THREAD

**Issue by sofior** [jOOQ/jOOQ#7967]
- jOOQ:3.10.8
- Java:8
- Database (include vendor):mysql 5.7
- OS:ubuntu 18.04.1 lts
- JDBC Driver (include name if inofficial driver):com.mysql.jdbc.Driver

**Comment by lukaseder** [comment]
From how I understand MyBatis, in order to get equivalent functionality, you will need to make sure you don't have any `Record.changed()` flags on the relevant columns of your record.
