### ISSUE TITLE
Query PostgreSQL- Count colum return value when value equal 0

### ISSUE THREAD

**Issue by Dangtrungphu** [jOOQ/jOOQ#7992]
I have query 1:
select c.danh_muc_tin_text[1],count(c.danh_muc_tin_text) 
from com_tin_tuc c, thang t
where EXTRACT(MONTH FROM c.time_create)= CAST(t.date AS INT)
group by c.danh_muc_tin_text

result: [
![3](https://user-images.githubusercontent.com/40323522/47661853-7060bf00-dbcc-11e8-80a8-8b1e5cfc9447.PNG)
](url)

when i change query 2:

select c.danh_muc_tin_text[1],count(c.danh_muc_tin_text) 
from com_tin_tuc c, thang t
where EXTRACT(MONTH FROM c.time_create)= 9
group by c.danh_muc_tin_text

![4](https://user-images.githubusercontent.com/40323522/47661959-9e460380-dbcc-11e8-810f-07034fd928a8.PNG)

How to resutl have 4 row as query 1 with rows null  colum count equal 0. thanks

**Comment by Dangtrungphu** [comment]
> I have query 1:
> select c.danh_muc_tin_text[1],count(c.danh_muc_tin_text)
> from com_tin_tuc c, thang t
> where EXTRACT(MONTH FROM c.time_create)= CAST(t.date AS INT)
> group by c.danh_muc_tin_text
> 
> result: [ ![3](https://user-images.githubusercontent.com/40323522/47661853-7060bf00-dbcc-11e8-80a8-8b1e5cfc9447.PNG) ](url)
> 
> when i change query 2:
> 
> select c.danh_muc_tin_text[1],count(c.danh_muc_tin_text)
> from com_tin_tuc c, thang t
> where EXTRACT(MONTH FROM c.time_create)= 9
> group by c.danh_muc_tin_text
> 
> ![4](https://user-images.githubusercontent.com/40323522/47661959-9e460380-dbcc-11e8-810f-07034fd928a8.PNG)
> 
> How to resutl have 4 row as query 1. thanks

**Comment by lukaseder** [comment]
You may want to use a left join instead of an implicit inner join:

```sql
select c.danh_muc_tin_text[1],count(t.date)
from com_tin_tuc c
left join thang t
on EXTRACT(MONTH FROM c.time_create)= CAST(t.date AS INT)
group by c.danh_muc_tin_text
```

I hope this helps

**Comment by Dangtrungphu** [comment]
@lukaseder Excellent it worked as I desired. thanks you.
