### ISSUE TITLE
jOOQ does not substitue '?' insides single quotes

### ISSUE THREAD

**Issue by oripwk** [jOOQ/jOOQ#7996]
#### Expected
jOOQ should substitute the question marks inside the single quotes
#### Actual
* jOOQ does not substitute the question marks inside the single quotes
* We get error: `Data truncation: Invalid GIS data provided to function st_geometryfromtext`

### Steps to reproduce the problem (include example code if possible):
```java
    DSL.using(config).select()
        .from("locations")
        .where("ST_Contains(ST_Envelope(ST_GeomFromText('LineString(? ?,? ?)')), point)", topLeftLatitude, topLeftLongitude, bottomRightLatitude, bottomRightLongitude)
        .fetch(locationDtoMapper)
```
### Versions:

- jOOQ: 3.11.0
- Java: 8
- Database (include vendor): MySQL 5.7
- OS: MacOS
- JDBC Driver (include name if inofficial driver):  JDBC Connector 6.0.6

**Comment by lukaseder** [comment]
Counter example:

```java
DSL.using(config)
   .select()
   .from("x")
   .where("c = 'Is this the real life? Or is this just ' || ?", fantasy)
   .fetch();
```

Should jOOQ really replace placeholder inside of strings? Most likely not.

Here's some useful information about how to do this correctly:
https://gis.stackexchange.com/a/122786

Hope this helps!
