### ISSUE TITLE
Failed to execute goal org.jooq:jooq-codegen-maven:3.11.5:generate

### ISSUE THREAD

**Issue by BohdanKorinnyi** [jOOQ/jOOQ#7998]
Hi, I use Spring Boot 2.1.0.RELEASE with `jooq-codegen-maven` plugin.

### Expected behavior and actual behavior:
When I run build it fails with the error 
```
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.11.5:generate (default) on project demo: Error running jOOQ code generation tool: Your configured org.jooq.util type was not found.
[ERROR] Do note that in jOOQ 3.11, jOOQ-meta and jOOQ-codegen packages have been renamed. New package names are:
[ERROR] - org.jooq.meta
[ERROR] - org.jooq.meta.extensions
[ERROR] - org.jooq.codegen
[ERROR] - org.jooq.codegen.maven
```
I have the following code in plugin:
```
<build>
        <plugins>
             <plugin>
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
......
```
Also I use JOOQ starter:
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jooq</artifactId>
        </dependency>
```

Where do I have to change package names?
### Versions:

- jOOQ: 3.11.5
- Java: 11.0.1
- Database (include vendor): PostgreSQL 9.4.15 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit
- OS: Ubuntu
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver

**Comment by lukaseder** [comment]
I suspect the error message already explains sufficiently well what's happening here:

```
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.11.5:generate (default) on project demo: Error running jOOQ code generation tool: Your configured org.jooq.util type was not found.
[ERROR] Do note that in jOOQ 3.11, jOOQ-meta and jOOQ-codegen packages have been renamed. New package names are:
```

You were probably copying some code generation configuration from the jOOQ manual of an older version than 3.11, and are now using jOOQ 3.11, where packages have been renamed (see again error message).

I hope this helps
