### ISSUE TITLE
Wrong SQL generated when H2 OffsetDateTime values are inlined

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8026]
The following SQL is generated when an `OffsetDateTime` value is inlined in H2:

```sql
cast('1970-01-01 00:00:00+02:00' as timestamp with time zone)timestamp with time zone '1970-01-01 00:00:00+02:00'
```

After the cast, the timestamp literal is repeated. This doesn't happen when using bind variables.

The regression was introduced with #5895 and is present in jOOQ 3.12 only, so far.

**Comment by lukaseder** [comment]
@katzyn It's probably a bug in this case. The cast is generated for Java bind values that are not of type `OffsetDateTime`, but when passing an actual `OffsetDateTime`, no cast should be needed

**Comment by katzyn** [comment]
I mean code in `sqlInline0()` method that takes an `OffsetDateTime` as argument:
https://github.com/jOOQ/jOOQ/blob/e924faa75c1188b78ab5312f845441dbb5345996/jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java#L2600-L2605

**Comment by lukaseder** [comment]
Yes I know what you meant :-) Given this is fully supported now, it's probably a bug.

**Comment by katzyn** [comment]
Also cast to `TIMESTAMP(9) WITH TIME ZONE` should be used in H2 for passed values with possible high resolution if you need such cast somewhere. Java 9 and later versions return 7 fractional digits from `Instant.now()`, `OffsetDateTime.now()` and similar methods on Windows systems. Cast to `TIMESTAMP WITH|WITHOUT TIME ZONE` without precision rounds passed value to default 6 fractional digits. We had an invalid issue about such behavior. It was quite surprising, but some people want to store and retrieve timestamps with such resolution.

Literals don't have precision parameter and support up to 9 fractional digits in H2, any additional digits are ignored.

**Comment by lukaseder** [comment]
Thanks for the additional hint about the precision. You're right, we're currently not managing that optimally, not just with H2. I'll look into this in a separate issue #8029
