### ISSUE TITLE
Setting globalObjectReferences to false seems to hide Foreign keys

### ISSUE THREAD

**Issue by Cybergern** [jOOQ/jOOQ#8028]
### Expected behavior and actual behavior:

Expected behaviour: 

Generates table classes that include foreign key information

Actual behaviour:

Foreign keys are detected and added during generation according to the logging but getReferences() in every class is just the default implementation from AbstractTable.

If I comment out the globalObjectReferences = false option, the keys appear again as normal.

Sorry if this is the expected behaviour but I was unable to find anything about it when searching.

We previously used version 3.10.1 of JOOQ and did not see this behaviour, but then we were also using jdk 8u161, switching to latest version of JOOQ is part of our effort to upgrade to Java 11.

### Steps to reproduce the problem (include example code if possible):

This is our plugin element for generating the Jooq-tables:

`<plugin>

				<groupId>org.jooq</groupId>
				<artifactId>jooq-codegen-maven</artifactId>
				<version>${jooq.version}</version>

				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>

				<configuration>

					
					<jdbc>
						<driver>com.mysql.jdbc.Driver</driver>
						<url>jdbc:mysql://${database.host}:${database.port}/accounting_test</url>
						<user>${database.username}</user>
						<password>${database.password}</password>
					</jdbc>

					
					<generator>
						<database>
							<name>org.jooq.meta.mysql.MySQLDatabase</name>
							<includes>.*</includes>
							<excludes/>
							<inputSchema>bleh_test</inputSchema>
						</database>
						<target>
							<packageName>bleh.core.infrastructure.model.jooq</packageName>
							<directory>target/generated-sources/jooq</directory>
						</target>
						<strategy>
							<name>org.jooq.codegen.example.JPrefixGeneratorStrategy</name>
						</strategy>
						<generate>
							<records>false</records>
							<deprecated>false</deprecated>
							<globalObjectReferences>false</globalObjectReferences>
						</generate>
					</generator>
				</configuration>
			</plugin>`

### Versions:

- jOOQ: 3.11.7
- Java: openjdk-11
- Database (include vendor): MySQL 5.6.41
- OS: Fedora 29
- JDBC Driver (include name if inofficial driver): com.mysql.jdbc.Driver

**Comment by lukaseder** [comment]
Thanks for your report. Currently, all constraint information is contained only in the `Keys.java` class, not the generated tables, so turning off the references to such objects effectively removes the objects.

This is probably not optimal, but that's how it works now.

What's the reason you're turning off those references? Do note, you can turn them off individually, see:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-globals

**Comment by Cybergern** [comment]
In our case I think it was a misunderstanding about what that particular option does and then when we upgraded JOOQ and our JDK, we suddenly could not join tables anymore until we removed that particular option. The intent in our case was to not have any references to the actual database name since we're just using its schema to generate the JOOQ-classes, i.e. our actual database is named bleh, while the database we're using to generate the classes is bleh_test. This however, seems to work just fine even without that option.

**Comment by lukaseder** [comment]
You want to use the schema mapping feature:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-catalog-and-schema-mapping

In particular, the `<outputSchemaToDefault>true</outputSchemaToDefault>` flag

**Comment by Cybergern** [comment]
Thank you, I have added it to our generator configuration.

**Comment by lukaseder** [comment]
I've reviewed this issue a few times, but to this date, can't think of a simple solution for this. Changing this would change a lot of code generation and static initialisation behaviour, which is always a source of trouble.

I prefer not to improve this, unless there's a compelling reason to do so.
