### ISSUE TITLE
ALTER TABLE .. RENAME TO .. should fully qualify tables if supported by the database

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8042]
Currently, the `ALTER TABLE schema.table1 RENAME TO schema.table2` statement does not qualify the `table2` table, because that's not supported in a few databases. We should always qualify the table if such qualification is provided, as the semantics of the statement may change depending on what the session's default schema / database may be.

----
See: https://stackoverflow.com/q/53210516/521799

**Comment by do4gr** [comment]
This is the jooq call we're making `sql.alterTable(table(name(schema1, table1))).renameTo(name(schema1, table2))`

This generates `alter table "schema1"."table1" rename to "schema1"."table2"` on both MySQL and Postgres (different quotation of course). But Postgres does not accept the qualification on the rename to part. 

So I think the correct behaviour would be to qualify the renameTo on MySql but not on Postgres.

**Comment by lukaseder** [comment]
Thanks for the additional comments. Yes of course, I agree. The same statement should work on all RDBMS, if it can be reasonably emulated. I was just pointing out a workaround for the time being, and also for others who may stumble upon this.

The issue title is quite clear, and according to that title, this issue was not implemented correctly.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.12. Backport will be scheduled again under #8043, for 3.11.10
