### ISSUE TITLE
PostgreSQL 'INTERVAL' datatype without binding

### ISSUE THREAD

**Issue by cfstras** [jOOQ/jOOQ#8046]
### Expected behavior and actual behavior:
I have the following function in a PostgreSQL database with timescaledb installed
```postgresql
create function time_bucket(bucket_width interval, ts timestamp)
```

jOOQ generates the following code in Routines.java:
```java
...
/**
 * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
 */
@java.lang.Deprecated
public static Field<Timestamp> timeBucket1(Object bucketWidth, Timestamp ts) {
    TimeBucket1 f = new TimeBucket1();
    f.setBucketWidth(bucketWidth);
    f.setTs(ts);

    return f.asField();
}
...
```

The documentation talks about the DayToSecond datatype being provided in jOOQ, but apparently it isn't used. We would expect to get DayToSecond, or java.time.Duration, but instead it becomes `Object`

We've tried to wrap the function in another one using `interval day to second` explicitly, but PostgreSQL seems to ignore that and defines the function as raw `interval` anyway.

### Steps to reproduce the problem (include example code if possible):

- Use postgres from docker image `timescale/timescaledb:0.12.1-pg10`
- generate using the config below
```xml
<generator>
    <database>
        <name>org.jooq.meta.postgres.PostgresDatabase</name>
        <includes>.*</includes>
        <inputSchema>public</inputSchema>
        <excludes>set_adaptive_chunking
            | flyway_schema_history
        </excludes>
    </database>
    <target>
        <packageName>my.package</packageName>
        <directory>target/generated-sources</directory>
    </target>
</generator>
```

### Versions:

- jOOQ: 3.11.5
- Java: 11
- Database (include vendor): PostgreSQL 10 with timescale 0.12.1
- OS: Tested on OSX Mojave & Windows 10
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver

**Comment by lukaseder** [comment]
Thank you very much for your message. We should absolutely support this data type in the near future. The relevant feature request is #2230

I'm closing this as a duplicate
