### ISSUE TITLE
How does batchUpdate know which lines should be updated?

### ISSUE THREAD

**Issue by ruiruige** [jOOQ/jOOQ#8051]
Sorry to ask question here, I can not found similar questions on any site.
This function:

    Batch batchUpdate(Collection<? extends UpdatableRecord<?>> records);

For example, if I use it like this:
    
    dsl.batchUpdate(List<MyObject> objList).execute()

I was wondering how does jooq find the lines to be updated?  Does it find all primary keys in objList, and then update the lines by the  primary keys using batch operation?

**Comment by viccP** [comment]
here is my understanding：

>dsl.batchUpdate(List<MyObject> objList).execute() 

your sample code   will be translated  as above

dsl.batch(dsl.update(MyObject).set( MyObject .filed1,"?").set(MyObject.field2,"?")....
for(MyObject obj:objList){
   batch.bind(obj.field1,obj.field2.....)
}
batch.execute();

**Comment by ruiruige** [comment]
Thanks

**Comment by lukaseder** [comment]
> @ruiruige Sorry to ask question here, I can not found similar questions on any site.

GitHub is perfectly fine. Other options for community support are:

- https://stackoverflow.com/questions/tagged/jooq
- https://groups.google.com/d/forum/jooq-user

> @viccP here is my understanding [...]

That's not the exact way how it works. The authoritative Javadoc is on this method:
https://www.jooq.org/javadoc/latest/org/jooq/DSLContext.html#batchStore-org.jooq.UpdatableRecord...-

Other, similar methods refer to it
