### ISSUE TITLE
Can not update with order by and limit

### ISSUE THREAD

**Issue by ruiruige** [jOOQ/jOOQ#8052]
for example, the raw sql is valid:

    update tbl set col=value where condition=another_value order by xxx limit 100

but i can not use jooq to achieve this, I can not get an order by function after update and where

### Versions:

- jOOQ: 3.10.4
- Java: 1.8
- Database (include vendor): Mysql 5.7
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by viccP** [comment]
你可以参考一下这个回答#7704，之前我也问过作者一些update语句的问题，他在里面有解释，我觉得应该和你这个问题类似。

**Comment by ruiruige** [comment]
感谢/Thanks
Although this problem is not solved, but this will be a workaround:

    ctx.update(TABLE1)
       .set(row(TABLE1.COL1, TABLE1.COL2), 
            select(TABLE2.COL1, TABLE2.COL2).from(TABLE2).where(TABLE2.X.eq(TABLE1.X)))
       .where(TABLE1.Y.eq(value))
       .execute();

**Comment by lukaseder** [comment]
Thanks a lot for your report. We've finally supported MySQL's extensions to standard SQL, including `{ UPDATE | DELETE } ... [ ORDER BY .. ] [ LIMIT .. ]` in jOOQ 3.12: #714

Emulations on other SQL dialects are also available: #7839
