### ISSUE TITLE
Problem with mapping of pojos fields in camelCase and column in "underscore case"

### ISSUE THREAD

**Issue by f-renout** [jOOQ/jOOQ#8056]
### Expected behavior and actual behavior:
I've generated dao and pojos from a postgresql database (version 10)
In this database, columns names are underscored (for example update_user)
The pojos field name avec camelCased
When I try to retrieve datas from this table, every field where the name is with _ is setted to null into the pojo.

I presume I miss some configuration but I can't figure where

Exprected behaviour : my fields are properly mapped between pojo and database table

### Steps to reproduce the problem (include example code if possible):

snipped of config used to generate code
jooq {
    version = '3.11.7' // the default (can be omitted)
    ocz(sourceSets.main) {
        jdbc {
            driver = 'org.postgresql.Driver'
            url = postgre_url
            user = postgre_user
            password = postgre_password
        }
        generator {
            strategy{

            }
            database {
                name = 'org.jooq.meta.postgres.PostgresDatabase'
                inputSchema = 'public'
                excludes='Pg.*|Schema.*'
            }
            generate {
                daos = true
                validationAnnotations = false
                javaTimeTypes = true
                pojosEqualsAndHashCode = true
            }
            target {
                packageName = 'com.manuloc.occasion.middle.data.jooq.gen'
                directory = 'src/main/java'
                encoding = 'UTF-8'
            }
        }
    }
}

Snipped of code use to retrieve a DSL Context
    private static Connection getBdCon() throws SQLException {

        String url = "jdbc:postgresql://localhost/occasion?user=XXXX&password=YYYY";
        Connection conn = DriverManager.getConnection(url);
        return conn;
    }

    public static DSLContext getContext(Connection con) {
        Settings settings = new Settings()
            ;
        DSLContext using = DSL.using(con, SQLDialect.POSTGRES, settings);
        return using;
    }

### Versions:

- jOOQ: 3.11.7
- Java: 1.8.0_191
- Database (include vendor): Postgresql 10.0
- OS: Ubuntu 18.10
- JDBC Driver (include name if inofficial driver): postgre official driver (42.2.5)

**Comment by f-renout** [comment]
It was a problem related to REST not to JOOQ, thanks to java type erasure, I didn't realise that my expected List<POJO> was a List<HashMap>
Sorry for the inconvenience

**Comment by lukaseder** [comment]
Thanks a lot for following up. Glad you could find the issue.
