### ISSUE TITLE
jOOq codegen from SQL script

### ISSUE THREAD

**Issue by JimiJones** [jOOQ/jOOQ#8058]
### Expected behavior and actual behavior:
Using generated script from liquibase I would like to use codegen with it but it contains UPDATE request and doesn't seem being readable or skipable by codegen reading process.
`org.jooq.impl.ParserException: Keyword 'SET' expected: [325:26] ...OM `dictionaryentry`;`

### Steps to reproduce the problem (include example code if possible):
UPDATE `table1` t1 SET t1.field1 = (SELECT t2.field2 FROM `table2` t2 WHERE t2.name = t1.name);

### Versions:
- jOOQ: jooq-codegen-maven 3.11.7
- Java: 11
- Database (include vendor): Sql script from liquibase
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): org.jooq.meta.extensions.ddl.DDLDatabase

**Comment by lukaseder** [comment]
Thanks a lot for your report. This has been fixed in jOOQ 3.12 through #7518

![image](https://user-images.githubusercontent.com/734593/48897879-9552f580-ee4b-11e8-874d-7ef0c74dfa9d.png)

We'll soon backport a few of these fixes to 3.11
