### ISSUE TITLE
Generated code doesn't include foreign key cascade

### ISSUE THREAD

**Issue by inssein** [jOOQ/jOOQ#8091]
### Expected behavior and actual behavior:

DDL of the `contact_email` table:
```
CREATE TABLE `contact_email` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `email_address` varchar(254) NOT NULL DEFAULT '',
  `contact_id` int(11) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `contact_id` (`contact_id`),
  CONSTRAINT `contact_email_ibfk_1` FOREIGN KEY (`contact_id`) REFERENCES `contact` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11508 DEFAULT CHARSET=utf8
```

Generated DDL of `contact_email` table from jOOQ:
```
create table `contact_email`(
  `id` int unsigned not null auto_increment,
  `email_address` varchar(254) not null default '',
  `contact_id` int unsigned not null,
  constraint `KEY_contact_email_PRIMARY`
    primary key (`id`),
    constraint `contact_email_ibfk_1`
      foreign key (`contact_id`)
      references `contact` (`id`)
    );
```

Note that `ON DELETE CASCADE ON UPDATE CASCADE` is missing on the foreign key relationship.

### Why is this important?
We have a feature where we build database tables from the generated code, for testing against. This has been working so far (with some quirks that we have overcome), but we recently hit a snag where we could not delete entities due to this issue.

### Versions:

- jOOQ: 3.11.4
- Java: 8
- Database (include vendor): MySQL
- OS: Mojave
- JDBC Driver (include name if inofficial driver): 5.1.6

**Comment by lukaseder** [comment]
Thank you very much for your report.

> Generated DDL of contact_email table from jOOQ

How do you generate this DDL specifically?

**Comment by lukaseder** [comment]
We have been improving a few runtime meta model types in for jOOQ 3.13's DDL interpretation feature. I will look into this again for inclusion. We currently lack any runtime model on `org.jooq.ForeignKey`, which could represent these actions, including on generated code.

I have created a separate issue for this: #9736. Closing this as a duplicate.

**Comment by inssein** [comment]
Sorry @lukaseder I had totally missed your response to this! It is now so long ago that I don't exactly remember, since jOOQ doesn't generate any database tables, but we had written some code to take in a jOOQ Table class and create a database table out of it, and I think that was missing the data.

**Comment by lukaseder** [comment]
No worries, it was my fault. I thought I needed a detail for reproduction, but in fact I didn't. There's simply a ton of missing functionality in this area.

**Comment by inssein** [comment]
I don't know how you do it, but watching you work on this project (and your StackOverflow answers) is a true inspiration. 

Over 13 years of consistent dedication to this project! 
![image](https://github.com/user-attachments/assets/a6f4433f-5bb5-4036-85f0-57a6261e8a37)

Thank you!

**Comment by lukaseder** [comment]
Well, it pays the rent and more 😉
