### ISSUE TITLE
DDLDatabase cannot handle tables KEY/INDEX clause in create table

### ISSUE THREAD

**Issue by amir20001** [jOOQ/jOOQ#8097]
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

```
CREATE TABLE `FOO` (
  `id`   VARCHAR(10) NULL,
  `name` VARCHAR(10),
  PRIMARY KEY (`id`),
  KEY (`id`)
);
```
replacing key with index produces the same error.
error msg:
`[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.10.8:generate (default) on project : Error running jOOQ code generation tool: C42000_NO_SUBCLASS: [19:3] LL,
[ERROR]   `name` VARCHAR(10),
[ERROR]   PRIMARY KEY (`id`),
[ERROR]   [*]KEY (`id`)
[ERROR] );`
### Versions:

jOOQ: 3.10.8
Java: 1.8.0_181-b13
Database (include vendor): mysql
OS: mac os 10.13.6
JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Support was added in 3.11 through #7171
