### ISSUE TITLE
DDLDatabase cannot handle alter table add index syntax.

### ISSUE THREAD

**Issue by amir20001** [jOOQ/jOOQ#8098]
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

```
CREATE TABLE `FOO` (
  `id`   VARCHAR(10) NULL,
  `name` VARCHAR(10),
  PRIMARY KEY (`id`)
);

ALTER TABLE `FOO` ADD INDEX (`name`);

```
produces the following error

```
org.jooq.impl.ParserException: C42000_NO_SUBCLASS: [9:29] RIMARY KEY (`id`)
);

ALTER TABLE `FOO` ADD INDEX [*](`name`);
```

### Versions:
jOOQ: 3.10.8
Java: 1.8.0_181-b13
Database (include vendor): mysql
OS: mac os 10.13.6
JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your report. Support for this syntax was added in jOOQ 3.11.0 through #7171
