### ISSUE TITLE
DDLDatabase cannot handle uniq index with name inside create table

### ISSUE THREAD

**Issue by amir20001** [jOOQ/jOOQ#8099]
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
https://github.com/amir20001/jOOQ-mcve/tree/error-with-uniq-index
running `mvn clean generate-sources`
will result in the following error.

```org.jooq.impl.ParserException: Token '(' expected: [4:16] ... NULL AUTO_INCREMENT,
  value INT,
  UNIQUE INDEX [*]`value_un` (`value`),
  CONSTRAINT pk_test PRIMARY KEY (id)
);
```
### Versions:
jOOQ: 3.10.8
Java: 1.8.0_181-b13
Database (include vendor): mysql
OS: mac os 10.13.6
JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your report. Support for this syntax is due in a near future version of jOOQ, hopefully jOOQ 3.12: #7268
