### ISSUE TITLE
INT and MONEY Type not supported by dialect SQLSERVER2012

### ISSUE THREAD

**Issue by jungleerohan** [jOOQ/jOOQ#8100]
```
*WARN* [Database Thread-32] org.jooq.impl.MetaDataFieldProvider Not supported by dialect : Type INT is not supported in dialect SQLSERVER2012 
*WARN* [Database Thread-32] org.jooq.impl.MetaDataFieldProvider Not supported by dialect : Type MONEY is not supported in dialect SQLSERVER2012
```

why is this warning coming ? 

It has no impact on actual results though.

**Comment by lukaseder** [comment]
Thank you very much for your report. This issue should not appear, although, I cannot reproduce it easily. How can this be reproduced?

**Comment by lukaseder** [comment]
Our integration tests don't show this kind of warning, and I'm not sure how to reproduce it.

Closing this as "works for me".
