### ISSUE TITLE
Add support for ALTER DATABASE with DDLDatabase

### ISSUE THREAD

**Issue by amir20001** [jOOQ/jOOQ#8104]
### Expected behavior and actual behavior:
 I think it should be safe for jooq to ignore it.
### Steps to reproduce the problem https://github.com/amir20001/jOOQ-mcve/tree/error-with-create-table:
```
ALTER DATABASE test
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;
```
generates the following error

```
Error running jOOQ code generation tool: DOMAIN, INDEX, SCHEMA, SEQUENCE, SESSION, TABLE, or VIEW expected: [1:7] ALTER [*]DATABASE test
[ERROR] DEFAULT CHARACTER SET utf8
[ERROR] DEFAULT COLLATE utf8_general_ci;
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### Versions:

- jOOQ: 3.11.7
- Java:1.8
- Database (include vendor): mysql

**Comment by lukaseder** [comment]
Thanks for your report. Indeed, jOOQ currently doesn't support statements like `{ CREATE | ALTER | DROP } DATABASE`

**Comment by amir20001** [comment]
workaround.
put it into an executable comment.
`/*! ALTER DATABASE test DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci; */`

**Comment by lukaseder** [comment]
Aha! :-) That's a funky feature. We'll have to support it in jOOQ's parser (with a flag to activate / deactivate its parsing, of course): #8112

For the time being: Excellent idea! This workaround will work well with all sorts of MySQL specific syntax that isn't strictly necessary for the `DDLDatabase`. Thanks for pointing this out.

**Comment by lukaseder** [comment]
Implementing parser support for:

```sql
ALTER {DATABASE | SCHEMA} [db_name]
    alter_specification ...

alter_specification:
    [DEFAULT] CHARACTER SET [=] charset_name
  | [DEFAULT] COLLATE [=] collation_name
  | DEFAULT ENCRYPTION [=] {'Y' | 'N'}
```

As documented here: https://dev.mysql.com/doc/refman/8.0/en/alter-database.html

The statement will currently be ignored by jOOQ.
