### ISSUE TITLE
Resolve relative paths in target directory in Maven plugin - Merge [#8086]

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8120]

**Comment by paninics** [comment]
Thank you for the fix. However, there's a subtle bug lurking in the fix you made. You're concatenating `File.separator`. What if `project.getBasedir()` returns a path with a trailing slash?

` generator.getTarget().setDirectory(new File(project.getBasedir() + File.separator + generator.getTarget().getDirectory()).getCanonicalPath());`

So what we should do instead is leverage `File` api's constructor to avoid such pitfalls.

` generator.getTarget().setDirectory(new File(project.getBasedir(), generator.getTarget().getDirectory()).getCanonicalPath());`

**Comment by lukaseder** [comment]
Thanks for the hint. You're probably right
