### ISSUE TITLE
returningResult() returns generated record type when returning only the identity

### ISSUE THREAD

**Issue by doomchild** [jOOQ/jOOQ#8128]
### Expected behavior and actual behavior:

I expect that when I call `returningResult` that only the columns I've specified will be available in later steps.  Unfortunately, it appears that this is not what's actually happening, because I get an exception like so:

`org.jooq.exception.MappingException: Cannot map multi-column record of degree 6 to value type class java.lang.Integer`

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

The following query results in the exception being thrown (`mrns` is a `List<Mrn>` in this example):

```java
return context.insertInto(MRNS,
  MRNS.MRN,
  MRNS.DOMAIN,
  MRNS.MEMBERID,
  MRNS.TENANTID
)
  .values(
    mrns.get(0).getMrn(),
    mrns.get(0).getDomain(),
    memberId,
    tenantId
  )
  .values(
    mrns.get(1).getMrn(),
    mrns.get(1).getDomain(),
    memberId,
    tenantId
  )
  .returningResult(MRNS.ID)
  .fetch()
  .into(Integer.class);
```

### Versions:

- jOOQ: 3.11.7
- Java: 1.8.0_152
- Database (include vendor): MySQL 5.7.22 running in AWS RDS
- OS: Mac OS 10.14.1 (Mojave)
- JDBC Driver (include name if inofficial driver): 8.0.13

**Comment by lukaseder** [comment]
Thank you very much for your report. While trying to reproduce this issue, I've noticed another problem that could appear for the same reason as this one: #8131

Will fix this right away

**Comment by doomchild** [comment]
Thanks for the quick turnaround!
