### ISSUE TITLE
Perhaps you meant to reference the column "pg_proc.prolang".

### ISSUE THREAD

**Issue by poemp** [jOOQ/jOOQ#8129]
### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for taking the time to get in touch.

Perhaps we did mean to reference that column, but what for? And what's not working for you because we don't

**Comment by lukaseder** [comment]
I see, thank you very much for the clarification. Yes indeed, we have fixed #7785 recently.
