### ISSUE TITLE
Make getFileRoot non-final

### ISSUE THREAD

**Issue by Karl-Sa** [jOOQ/jOOQ#8147]
I would like to avoid having files generated by jOOQ to be stored in folders that match the package name.
This is because IntelliJ IDEA allows to attach a package prefix to a source code folder, making it unnecessary to create all the directories, so I don't need them.

I tried creating a generator strategy to provide the package without specifying it in the .xml file but the directories still get created below the target directory.

So I think that the simplest workaround would be to use a custom generator that extends JavaGenerator and simply overrides getFileRoot() in AbstractGenerator.
But to do so the final modifier needs to be removed.

If there's another way to achieve what I need I'm all ears.

**Comment by Karl-Sa** [comment]
Got the names wrong, JavaGenerator should have been DefaultGeneratorStrategy and AbstractGenerator should have been AbstractGeneratorStrategy.
Hence a custom generator strategy would be enough, no need for a custom generator altogether.

**Comment by lukaseder** [comment]
Thanks for your report. Indeed, a generator strategy should allow for this feature to be implemented. I think from how I read your second comment, you were successful in doing so? If not, please feel free to reopen this issue.

**Comment by Karl-Sa** [comment]
Sorry for the confusion.
I got the names wrong in the first comment, I tried to edit it but apparently GitHub won't let me.
So I added a second one.

To achieve what I need I think the most straightforward way would be to make getFileRoot() non-final in AbstractGeneratorStrategy.

**Comment by lukaseder** [comment]
I'd rather not open up any such implementation. In standard Java compilation scenarios, deviating from the package name = file system path correspondence doesn't seem supported, or a good idea. What's the reason why you want to avoid those directories?

**Comment by Karl-Sa** [comment]
IntelliJ IDEA allows to specify a package prefix for a sources folder.
This avoids having to create the subfolders that make up the prefix.
For me it's a rather handy feature, makes things more concise.

**Comment by lukaseder** [comment]
Yes, I understand that this feature exists, but given that the code generator generates all the directories for you, what do you get out of it? The fact that you no longer need to expand all the directories by clicking on them? But perhaps there's a better visual representation in IntelliJ to prevent that?
