### ISSUE TITLE
By my testing, spring did not instrumenting tons of api calls for dslcontext, there is only 1 call.

### ISSUE THREAD

**Issue by xuzhao103389** [jOOQ/jOOQ#8164]
By my testing, spring did not instrumenting tons of api calls for dslcontext, there is only 1 call.
I am pretty sure that there is memory leakage within this API:
public DefaultDSLContext(Configuration configuration) {
    super(configuration, configuration == null ? null : configuration.data());
  }

_Originally posted by @xuzhao103389 in https://github.com/jOOQ/jOOQ/issues/7994#issuecomment-451396669_

all the details is in this defect: https://github.com/jOOQ/jOOQ/issues/7994

**Comment by lukaseder** [comment]
Thank you for your report. I currently don't see how this adds new information to your previous report, which is still missing information about how to reproduce this issue: https://github.com/jOOQ/jOOQ/issues/7994#issuecomment-451396669

I'm thus closing this as a duplicate of #7994
