### ISSUE TITLE
Add condition to Tools#field to allow QueryParts if there is an appropriate converter.

### ISSUE THREAD

**Issue by daicoden** [jOOQ/jOOQ#8165]
### Expected behavior and actual behavior:

Given a ForcedType's UserType set to a table instance, I would expect the field to work like other ForcedTypes. 

However, due to #4771, a table instance is a QueryPart and an exception is thrown.

I reviewed the code on master, and it appears like it's still an issue.

A solution would be to check if the value is an instanceof QueryPart && the field.getConverter() is not the identity converter. If this sounds like a good solution I can open a PR, though I am not sure how I would verify that the converter is the identity converter because it's an anonymous class. I would probably extract the IdentityConverter as a static class in `Converters`, and use instanceof in the check.

Thanks!

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

I can open an MVCE if this is not clear:

```
// A behavior added to a table.
public interface DirtyTable<R extends DirtyRecord<R>> extends Table<R> {
    @SuppressWarnings("unchecked")
    default Field<Integer> getDirtyField() {
        return (Field<Integer>) field("dirty");
    }
}

// converter
public class DerivableTypeConverter implements Converter<String, DirtyTable> {

    Map<String, DirtyTable> DIRTY_TABLES = ImmutableMap.<String, DirtyTable>builder()
            .put("targets", Targets.TARGETS)
            ...
            .build();

    @Override
    public DirtyTable from(String databaseObject) {
        return Preconditions.checkNotNull(DIRTY_TABLES.get(databaseObject));
    }

    @Override
    public String to(DirtyTable userObject) {
        return userObject.getName();
    }

    @Override
    public Class<String> fromType() {
        return String.class;
    }

    @Override
    public Class<DirtyTable> toType() {
        return DirtyTable.class;
    }
}

// example usage where derivationRecord has a field with a ForcedType of DirtyTable

derivationRecord.setDirtyTable(Targets.TARGETS);
derivationsRecord.store(); // BOOM! java.lang.IllegalArgumentException: Cannot interpret argument of type class edu.hawaii.cfht.aso.jooq.model.tables.Targets as a Field: "observing"."targets"
```

### Versions:

- jOOQ: 3.9.2
- Java: 1.8.0_102
- Database (include vendor): mariadb
- OS: macos
- JDBC Driver (include name if inofficial driver): com.mysql.cj.jdbc.Driver

**Comment by lukaseder** [comment]
Thank you very much for your request. What would be the use-case of using any `QueryPart` as the `<U>` type in a `Converter`? At first, this seems like a very remote edge case to me (this being the first time this request popped up), compared to the problem #4771 and other issues are solving, which happens far more often with new users.

> A solution would be to check if the value is an instanceof QueryPart && the field.getConverter() is not the identity converter. If this sounds like a good solution

It doesn't :) It sounds like a hack.

> I can open a PR, though I am not sure how I would verify that the converter is the identity converter because it's an anonymous class. I would probably extract the IdentityConverter as a static class in Converters, and use instanceof in the check.

Let's discuss use-cases first. Fixing this might be far more difficult than you seem to expect right now. A lot of jOOQ API "conveniently" allows for treating `<T>` and `Field<T>` as the same thing at run time. It is almost impossible to backwards compatibly change this feature.

**Comment by daicoden** [comment]
> Let's discuss use-cases first. Fixing this might be far more difficult than you seem to expect right now.

For sure - I figured I better check before doing anything.  FWIW - It does seem like the place where the error checking occurs should be after the conversion, because a user could write a converter which accidentally evades the check code.

The use case is polymorphic joins. Maybe there's another way that I missed? It's kind of like fetchChildren, but no foreign key.

## More concrete

I have a DefaultGeneratorStrategy, which attaches an interface `DirtyTable` to a generated table implementation, for this example, a table called `targets`. 

```
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Targets extends TableImpl<TargetsRecord> implements DirtyTable<TargetsRecord> {
```

I have another class which has a polymorphic join to targets.  There are several other dirty tables. The polymorphic table is named `derivations`.

I have a forced type and converter on `derivations.dirty_type` which converts the string table name into the `DirtyTable`, and allows me to do:

`dslContext.selectFrom(derivationRecord.getDirtyTable()).where(derivationRecord.getDirtyTable().getJoinField().eq(derivation.getDirtyId()).fetchOne();`

## Workaround

If you don't think it worth pursing feel free to close - I did manage to get everything working by removing the check, though would appreciate other ideas on how to accomplish polymorphic joins so I don't have to leave the patch in :-p.

```
        try {

            CtClass tools = ClassPool.getDefault().get("org.jooq.impl.Tools");
            CtClass objectType = ClassPool.getDefault().get("java.lang.Object");
            CtClass fieldType = ClassPool.getDefault().get("org.jooq.Field");
            CtClass[] params = new CtClass[] {objectType, fieldType};
            CtMethod method = tools.getMethod("field", Descriptor.ofMethod(fieldType, params));
            tools.removeMethod(method);

            String body = ""
                    + "{\n"
                    + "  if ($1 instanceof org.jooq.Field) {\n"
                    + "    return (org.jooq.Field) $1;\n"
                    + "  } else {\n"
                    + "    return org.jooq.impl.DSL.val($1, $2);\n"
                    + "  }\n"
                    + "}";

            method.setBody(body);
            tools.addMethod(method);

            tools.writeFile(".");
            tools.toClass();
        } catch (NotFoundException | IOException | CannotCompileException e) {
            throw new RuntimeException(e);
        }
```

Thanks

**Comment by lukaseder** [comment]
> The use case is polymorphic joins.

I see, that's quite intriguing. I'll think about this use case a bit. Of course, ideally, you would be normalising your schema for tons of other reasons, including performance, integrity checking, etc. But I guess that's not an option right now.

> Workaround

Oh my :)

Well, a far more robust workaround would be to create a simple wrapper type for `org.jooq.Table`, which has the same effect as your workaround, but won't break very simply. You would then write:

```java
dslContext
    .selectFrom(derivationRecord.getDirtyTable().unwrap()) // Only one extra call here
    .where(derivationRecord.getDirtyTable().getJoinField().eq(derivation.getDirtyId())
    .fetchOne();
```

Of course, this example also shows once more the weaknesses of this approach. You have to run a second query to implement the join, rather than doing this in a single query (I guess?)

In any case, I do agree there might be some use-cases where `org.jooq.QueryPart` subtypes are acceptable types for `<U>`  in converters or data type bindings, but the fix will definitely not be easy.

**Comment by lukaseder** [comment]
I've let this issue rest a bit.

In the meantime, I still don't think I properly understand the use-cases, or rather, the suggested solutions. Polymorphic joins have their (rare) place, but I don't think jOOQ needs to.

- Support them formally through some advanced API
- Encourage their usage

I don't have a clear picture of a more generic feature that could be implemented here, other than the many ways of:

- Writing dynamic SQL in user code
- Transforming SQL at runtime (e.g. via the new `QOM` API)

Hence, I'm closing this as "won't fix"
