### ISSUE TITLE
DefaultOffsetDateTimeBinding fails when year field is negative

### ISSUE THREAD

**Issue by hylkevds** [jOOQ/jOOQ#8178]
### Expected behavior and actual behavior:
Try to store a date that does not have 4 year digits, like 
`-3999-01-01T00:00:00Z` (5 year digits)
`500-01-01T01:01:01Z` (3 year digits)

DefaultBinding.java: https://github.com/jOOQ/jOOQ/blob/1044ab4900cbae4be9f76a68e330d690d8ff5cd4/jOOQ/src/main/java/org/jooq/impl/DefaultBinding.java#L2768

Assumes the date is 10 digits long when cutting out the T from the ISO timestamp. This of course fails when the year is 5 or 3 digits long, and thus an invalid date is generated. Like `-3999-01-0 T00:00:00+00:00` for the first example.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

- Create a database with a `timestamp with timezone` field
- Try to insert one of the above dates

### Versions:

- jOOQ: 3.11.7
- Java: any
- Database (include vendor): any if I read the code correctly
- OS: any
- JDBC Driver (include name if inofficial driver): any if I read the code correctly

**Comment by hylkevds** [comment]
Small addition: 3 digit years should never happen, since they get leading zeroes.
So the problem is just with negative dates.

**Comment by lukaseder** [comment]
#7987 cannot be implemented easily as it would introduce new regressions with pre Gregorian calendar dates. Since strings are still used when inlining date literals, I'll fix this issue here separately.

**Comment by lukaseder** [comment]
Another, related bug, which needs to be fixed first: #8181

**Comment by lukaseder** [comment]
Another problem is when using `java.sql.Date` (which is used by jOOQ internally, for backwards compatibility and continued Java 6 support) - they don't support BC dates well.

Oh my. This is opening up a can of worms... :)

**Comment by lukaseder** [comment]
Fixed in 3.12. Backport scheduled for 3.11.10 (#8184)

This issue fixes only negative year fields. 5-digit years will be handled here: #8185
