### ISSUE TITLE
[question] Custom type use generic type 

### ISSUE THREAD

**Issue by cn-src** [jOOQ/jOOQ#8180]
Custom converter, jOOQ codegen like this:
```java
 public final TableField<DemoRecord, List> NAME = createField("name"
```
How to add a String generic type
```java
<DemoRecord, List<String>>
```
Now whether to support?
thanks

**Comment by lukaseder** [comment]
Just write:

```xml
<userType>java.util.List&lt;String&gt;</userType>
```

... in the appropriate code generation configuration. I'll be happy to provide more specific help if you have any more specific questions

**Comment by superxiao** [comment]
@lukaseder would this work with any type argument, such as for some custom POJO type `A`:
```xml
<userType>java.util.List&lt;A&gt;</userType>
```

**Comment by lukaseder** [comment]
@superxiao Why wouldn't it?

**Comment by superxiao** [comment]
@lukaseder Thanks, just curious. I'm pitching my team to switch to jooq from a similar framework, which implemented just this earlier in the year. Before that, the framework spit `LinkedHashMap` instead of the specified generic type with type parameter. Great to know this is not an issue for jooq.
