### ISSUE TITLE
Add additional documentation that explains DefaultGeneratorStrategy's role in disambiguating names

### ISSUE THREAD

**Issue by mkotlikov** [jOOQ/jOOQ#8219]
### Expected behavior and actual behavior:
Expected: codegen creates unique names for each index in **Indexes.java**.
Actual: codegen creates an index named **PRIMARY** multiple times in **Indexes.java**.
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve): 
Create a custom generator and override **getJavaIdentifier()** as specified in the link
https://www.jooq.org/doc/3.11/manual/code-generation/codegen-generatorstrategy/

>     /**
>      * Override this to specifiy what identifiers in Java should look like.
>      * This will just take the identifier as defined in the database.
>      */
>     @Override
>     public String getJavaIdentifier(Definition definition) {
>         return definition.getOutputName();
>     }

Generate the code!

### Versions:

- jOOQ: >= 3.9.6
- Java: 8
- Database (include vendor): MySQL
- OS: Any
- JDBC Driver (include name if inofficial driver): com.mysql.cj.jdbc.Driver

**Comment by lukaseder** [comment]
Thank you very much for your report. The out-of-the-box generator strategies work around this by prefixing the index name by the table name. In most cases, it is recommended taking inspiration, or even delegating to the `DefaultGeneratorStrategy`.

Is your expectation for the manual to show an example of a "custom" generator strategy that still works around all the little caveats of all the different RDBMS? I think that would be overkill. How could the manual be improved without overwhelming first time generator strategy implementors?

**Comment by LassoMike** [comment]
I would replace it with the code below. The first time generator would know that the method `getJavaIdentifier()` is there and is override-able, and copy and pasting the `AsInDatabaseStrategy` class would just work. 

> /**
>  * Override this to specifiy what identifiers in Java should look like.
>  * This will just take the identifier as defined in the database.
>  */
> @Override
> public String getJavaIdentifier(Definition definition) {
>     return super.getJavaIdentifier(definition);
> }

To implement my own version of `getJavaIdentifier()` I ended up copying the code from `DefaultGeneratorStrategy` and then modifying it. It would have been nicer if `final String getFixedJavaIdentifier()` in `AbstractGeneratorStrategy` was protected `final protected String getFixedJavaIdentifier()`, so that I didn't have to copy the `getFixedJavaIdentfier()` method into my custom generator.

Also, I believe this may have been the issue experienced here https://github.com/jOOQ/jOOQ/issues/6729#issuecomment-381406011.

**Comment by lukaseder** [comment]
Thanks for the various pointers / feedback. I will think about this. There's definitely room for improvement

**Comment by lukaseder** [comment]
> I would replace it with the code below. The first time generator would know that the method getJavaIdentifier() is there and is override-able, and copy and pasting the AsInDatabaseStrategy class would just work.

Hmm. Well the point of illustrating an `AsInDatabaseStrategy` is precisely to *not* use the `DefaultGeneratorStrategy` implementation, but to show how something else could be implemented.

I'll just add a few comments to each method that hints at the possibility of calling the `super` implementation if needed.

In a perfect world, there would be a dozen of strategies, each with their own purpose, including:

- One to name things
- One to disambiguate things
- Others...

But perhaps, that would just be overengineered. I think a comment will suffice.

**Comment by lukaseder** [comment]
> To implement my own version of getJavaIdentifier() I ended up copying the code from DefaultGeneratorStrategy and then modifying it. It would have been nicer if final String getFixedJavaIdentifier() in AbstractGeneratorStrategy was protected (final protected String getFixedJavaIdentifier()), so that I didn't have to copy the getFixedJavaIdentfier() method into my custom generator.

Or, you could just implement it like this:

```java
    @Override
    public String getJavaIdentifier(Definition definition) {
        if (definition instanceof IndexDefinition)
            return super.getJavaIdentifier(definition);
        // My own implementation, otherwise
    }
```

> Also, I believe this may have been the issue experienced here #6729 (comment).

Indeed, thanks for the pointer!
