### ISSUE TITLE
Replace IN clause with one bind value to EQ clause

### ISSUE THREAD

**Issue by a-derevyanko** [jOOQ/jOOQ#8239]
Queries would be more optimal if, in the case of a single bind parameter for IN clause, a condition of equality was generated, and not the occurrence.

As I see, org.jooq.impl.InCondition replaces IN clause with 1=0 if the bind values collection is empty.  In my opinion this is wrong behaviour, and exception is more expected in this case.

### Versions:

jOOQ: 3.10.8
Java: 1.7
Database (include vendor): Oracle
JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Regarding your second part:

> As I see, org.jooq.impl.InCondition replaces IN clause with 1=0 if the bind values collection is empty. In my opinion this is wrong behaviour, and exception is more expected in this case.

This is a matter of perspective. I find it quite regrettable for the `IN` predicate not to have a version that allows for an empty `IN` list. jOOQ wants `IN (:b1, :b2, ..., :bN)` to behave consistently with `IN (SELECT ...)`, where `IN (empty set)` is the same as `FALSE` and `NOT IN (empty set)` is the same as `TRUE`

Hope this helps

**Comment by a-derevyanko** [comment]
I am sorry, the request is irrelevant.
We are using oracle array table as IN clauses parameter. There is no need to use an array table in the case when only one parameter is present in the condition. 
My mistake is that I assumed that this optimization works in the standard case of IN clause.

**Comment by a-derevyanko** [comment]
> I find it quite regrettable for the `IN` predicate not to have a version that allows for an empty `IN` list

But there is no need to make a request if we know that he will not return anything? :)

**Comment by lukaseder** [comment]
> But there is no need to make a query if we know that it will not return anything? :)

jOOQ could try to be clever here, but why not let the database do its work? The assumption by jOOQ is that users want for a specific query to be run exactly in the way they wrote it, for whatever reason (e.g. to trigger some SQL rewriting in the database).

Check this out:

```sql
EXPLAIN PLAN FOR
SELECT * FROM film WHERE 1 = 0;

SELECT * FROM TABLE(dbms_xplan.display);
```

The plan is:

```
Plan hash value: 1079187905
 
---------------------------------------------------------------------------
| Id  | Operation          | Name | Rows  | Bytes | Cost (%CPU)| Time     |
---------------------------------------------------------------------------
|   0 | SELECT STATEMENT   |      |     1 |   396 |     0   (0)|          |
|*  1 |  FILTER            |      |       |       |            |          |
|   2 |   TABLE ACCESS FULL| FILM |  1000 |   386K|    15   (0)| 00:00:01 |
---------------------------------------------------------------------------
 
Predicate Information (identified by operation id):
---------------------------------------------------
 
   1 - filter(NULL IS NOT NULL)
```

Observe the `filter(NULL IS NOT NULL)`, which just truncates the execution plan and prevents accessing the `FILM` table.
