### ISSUE TITLE
Cannot bind variables while building sql

### ISSUE THREAD

**Issue by PengShangwen** [jOOQ/jOOQ#8242]
### Expected behavior and actual behavior:
I'm using jOOQ-3.11.9 to build SQL. The following is my code:

    String sql = DSL.using(SQLDialect.MYSQL)
            .select(DSL.asterisk())
            .from(table("service"))
            .where("name = ?", "service1")
            .getSQL();

What I expect is

    select * from service where (name = "service1")

But the result is

    select * from service where (name = ?)

Is there anything wrong with my code? Or Is it a bug?

### Versions:

- jOOQ: 3.11.9
- Java: 8
- Database (include vendor): mysql
- OS: linux
- JDBC Driver (include name if inofficial driver): null

**Comment by lukaseder** [comment]
Thank you very much for your request.

This works as expected. The default `Settings.statementType` value is `StatementType.PREPARED_STATEMENT`, so jOOQ by default generates bind value placeholders in your SQL string, which can be used for execution in other tools, such as JDBC, Spring, etc.

You can pass the `ParamType.INLINE` value to the `getSQL()` method, or specify `Settings.withStatementType(StatementType.STATIC_STATEMENT)`

Please consider the explanation in the Javadoc for more details:
https://www.jooq.org/javadoc/latest/org/jooq/Query.html#getSQL--
