### ISSUE TITLE
Custom strategies cannot override most of the strategy methods

### ISSUE THREAD

**Issue by guss77** [jOOQ/jOOQ#8253]
### Expected behavior and actual behavior:

When writing a custom implementation of a `GeneratorStrategy`, one would expect that they can implement any method specified in `GeneratorStrategy` and the generator will call it during generator.

Unfortunately, because `AbstractGenerator` wraps the provided strategy implementation in `GeneratorStrategyWrapper` - this does now actually work: `GeneratorStrategyWrapper` extends `AbstractGeneratorStrategy` and forward only select calls to the delegate, the rest it lets `AbstractGeneratorStrategy` handle.

For example, all the `getFullJava*` methods are not delegated so if a custom strategy does implement any of these methods - it will never be called.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

1. Create a new `GeneratorStrategy` implementation, possibly by extending `AbstractStrategyGenerator` or `DefaultGeneratorStrategy`.
2. Implement `getFullJavaClassName(Definition definition, Mode mode)` to do something interesting, or just throw a `RuntimeException`
3. Specify the new custom strategy as the strategy to use.
4. Run jOOQ code generation and wait for your method to be called, but prepare to be disappointed.

### Versions:

- jOOQ: 3.11.5
- Java: 11
- Database (include vendor): MariaDB 10.3.6
- OS: Ubuntu 18.10
- JDBC Driver (include name if inofficial driver): mariadb-java-client 2.3.0

**Comment by lukaseder** [comment]
Thank you very much for your request.

Indeed, the current design makes it easy to get this wrong, namely to implement methods that are utility methods rather than SPI methods... Perhaps there should be 2 APIs:

- The one used by jOOQ internally to find names for objects
- The one you can implement (currently, the intention is for users to extend `DefaultGeneratorStrategy`, in case of which this cannot happen because the methods you're not supposed to implement are `final`)

I will think about how this should be fixed.

**Comment by guss77** [comment]
So, if I understand correctly - custom generators and strategies are not allowed to use different names for things?

**Comment by lukaseder** [comment]
@guss77 That doesn't sound like you've understood correctly :-) What made you understand that, or better, what are you really trying to achieve?

**Comment by guss77** [comment]
I figured out why I'm having difficulties communicating: I'm extending the  `GeneratorStrategy` API through [jklingsporn/vertx-jooq](https://github.com/jklingsporn/vertx-jooq) `VertxGeneratorStrategy` which implements and delegates to the pure Interface `GeneratorStrategy`, and it doesn't look at `AbstractGeneratorStrategy`. Maybe I should open a ticket there that `VertxGeneratorStrategy` should extend `AbstractGeneratorStrategy` instead?

The problem I'm trying to solve is that I want to override the POJO class names, in Daos, just for specific tables, not for all tables. The overridden classes extend the original POJOs so they are compatible in all cases, and just add some logic that can be implemented as more complex setters (setting one field changes other fields to maintain business rules) or add business logic specific methods (do a set of field read/write operations that represent a single business action). I understand that POJOs are not business objects, but I found this use case much more useful, simple and less clanky the writing wrapper business classes and then try to wrap and unwrap them correctly anytime some code access a DAO.

For simplicity of implementation, my business wrappers (I call them "concrete classes") have the same name as the POJO class they extend, just in a different package.

Currently, I'm implementing the same logic by overriding the JavaWriter and replacing text before it is written - which is a horrible way of going about things, so I thought it'll be a better idea to do my work inside the strategy, which has such useful sounding method names :smile: .

Looking at `AbstractGeneratorStrategy`, I can see that I'm allowed to override `getJavaClassName()` as well as `getJavaPackageName()` - the first has the information I need (do I want to replace the POJO class with the concrete class?) and the latter the capability I need (to replace the package name). To get both the information and the capability to act on it, I think I need `getFullJavaClassName()`.

I can probably achieve what I need by putting my concrete classes in the same package as the POJOs and have a class name prefix - something like: `com.example.model.pojos.ConcreteEntity`.

**Comment by lukaseder** [comment]
I've had another look at this issue. I'm not sure if there's really anything actionable here. The underlying use-case sounds like something few people are doing this way, so I'm not sure if the general purpose `GeneratorStrategy` is really flawed.

We can re-iterate if there's still something you think needs doing.
