### ISSUE TITLE
Using .in() and .notIn() with mutable collections

### ISSUE THREAD

**Issue by pedro-borges** [jOOQ/jOOQ#8260]
### Expected behavior and actual behavior:
We are experiencing a weird behaviour when building queries using .in(Collection) when the collection is not guaranteed to be immutable. If the list changes between building the predicate and the actual render of the query's sql the results are undefined, we have seen type cast errors `IN (cast 'uuidcode' as varchar)` and `IN (null)` scenarios.

The quick fix for us was to duplicate the Set at predicate declaration by simply replacing `mySet` with `new HashSet<>(mySet)`

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
Build a `IN` predicate backed by a non empty collection (a Set in our case) and clear the collection before executing the query. In our use case we're using a Collection<UUID> on a uuid DB type field. We're using jOOQ's codegen.

### Versions:

- jOOQ: 3.11.7
- Java: 1.8
- Database (include vendor): Postgres 9.6
- OS: Multiple (MacOS, amazon linux AMI)
- JDBC Driver (include name if unofficial driver): Portgres 42.2.5.jre7

**Comment by lukaseder** [comment]
Thank you very much for your report. This looks like a duplicate of #7991, which was backported to 3.11.8 through #8002. Could you please try upgrading to the latest jOOQ version?

**Comment by pedro-borges** [comment]
Great stuff Lukas, will do.
