### ISSUE TITLE
JOOQ generator dosnt generate classes with JPAdatabase

### ISSUE THREAD

**Issue by eleoleeye** [jOOQ/jOOQ#8267]
### Expected behavior and actual behavior:
I use gradle gradle-jooq-plugin:3.0.2 and hibernate.  Entityes was moved to other module. But i get :  

> Task :application:generateSampleJooqSchemaSource
Jan 29, 2019 4:25:55 PM org.jooq.tools.JooqLogger info
INFO: Initialising properties  : /home/ins/java/proejcts/home/demo2/application/build/tmp/generateSampleJooqSchemaSource/config.xml
Jan 29, 2019 4:25:55 PM org.jooq.tools.JooqLogger info
INFO: No <inputCatalog/> was provided. Generating ALL available catalogs instead.
Jan 29, 2019 4:25:55 PM org.jooq.tools.JooqLogger info
INFO: No <inputSchema/> was provided. Generating ALL available schemata instead.
Jan 29, 2019 4:25:55 PM org.jooq.tools.JooqLogger info
INFO: License parameters       
Jan 29, 2019 4:25:55 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Jan 29, 2019 4:25:55 PM org.jooq.tools.JooqLogger info
INFO:   Thank you for using jOOQ and jOOQ's code generator
Jan 29, 2019 4:25:55 PM org.jooq.tools.JooqLogger info
INFO:                          
Jan 29, 2019 4:25:55 PM org.jooq.tools.JooqLogger info
INFO: Database parameters      
Jan 29, 2019 4:25:55 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Jan 29, 2019 4:25:55 PM org.jooq.tools.JooqLogger warn
WARNING: No packages defined      : It is highly recommended that you provide explicit packages to scan
Jan 29, 2019 4:25:55 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate Core {5.3.7.Final}
Jan 29, 2019 4:25:55 PM org.hibernate.cfg.Environment <clinit>
INFO: HHH000206: hibernate.properties not found
Jan 29, 2019 4:25:58 PM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.0.4.Final}
Jan 29, 2019 4:25:58 PM org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Jan 29, 2019 4:25:58 PM org.hibernate.tool.hbm2ddl.SchemaExport execute
INFO: HHH000227: Running hbm2ddl schema export
Jan 29, 2019 4:25:58 PM org.hibernate.tool.schema.internal.SchemaCreatorImpl applyImportSources
INFO: HHH000476: Executing import script 'org.hibernate.tool.schema.internal.exec.ScriptSourceInputNonExistentImpl@3a435908'
Jan 29, 2019 4:25:58 PM org.hibernate.jpa.internal.util.LogHelper logPersistenceUnitInformation
INFO: HHH000204: Processing PersistenceUnitInfo [
        name: AttributeConverterExtractor
        ...]
Jan 29, 2019 4:25:58 PM org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
Jan 29, 2019 4:25:59 PM org.hibernate.tool.schema.internal.SchemaCreatorImpl applyImportSources
INFO: HHH000476: Executing import script 'org.hibernate.tool.schema.internal.exec.ScriptSourceInputNonExistentImpl@3a435908'
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   dialect                : H2
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   URL                    : 
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   target dir             : src/main/java
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   target package         : com.example.jooq
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   includes               : [.*]
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   excludes               : []
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   includeExcludeColumns  : false
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:                          
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: JavaGenerator parameters 
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   annotations (generated): true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   annotations (JPA: any) : false
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   annotations (JPA: version): 
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   annotations (validation): false
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments               : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on attributes : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on catalogs   : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on columns    : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on keys       : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on links      : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on packages   : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on parameters : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on queues     : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on routines   : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on schemas    : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on sequences  : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on tables     : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   comments on udts       : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   daos                   : false
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   deprecated code        : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   global references (any): true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   global references (catalogs): true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   global references (keys): true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   global references (links): true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   global references (queues): true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   global references (routines): true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   global references (schemas): true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   global references (sequences): true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   global references (tables): true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   global references (udts): true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   indexes                : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   instance fields        : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   interfaces             : false
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   interfaces (immutable) : false
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   javadoc                : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   keys                   : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   links                  : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   pojos                  : false
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   pojos (immutable)      : false
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   queues                 : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   records                : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   routines               : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   sequences              : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   table-valued functions : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   tables                 : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   udts                   : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:   relations              : true
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:                          
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: Generation remarks       
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO:                          
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: ----------------------------------------------------------
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: Generating catalogs      : Total: 1
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.11.2
                                      
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: ARRAYs fetched           : 0 (0 included, 0 excluded)
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: Enums fetched            : 0 (0 included, 0 excluded)
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: Packages fetched         : 0 (0 included, 0 excluded)
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: Routines fetched         : 0 (0 included, 0 excluded)
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: Tables fetched           : 0 (0 included, 0 excluded)
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: UDTs fetched             : 0 (0 included, 0 excluded)
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: Excluding empty catalog  : 
Jan 29, 2019 4:25:59 PM org.jooq.tools.JooqLogger info
INFO: Removing excess files    

My gradle files : 
main gradle : 

```
buildscript {

    repositories {
        mavenCentral()
        jcenter()
        maven { url "https://repo.spring.io/plugins-release" }
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:2.1.1.RELEASE"
        classpath "net.ltgt.gradle:gradle-apt-plugin:0.19"
    }

}


allprojects { project ->
    apply plugin: 'java'
    apply plugin: 'idea'
    apply plugin: 'net.ltgt.apt'
    apply plugin: 'net.ltgt.apt-idea'
    apply plugin: 'io.spring.dependency-management'


    repositories {
        mavenCentral()
        jcenter()
        maven { url "https://artifactory.hiendsys.ru/list/libs/" }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
    }

    sourceCompatibility = 1.8
    targetCompatibility = 1.8

    compileJava.options.encoding = 'UTF-8'
    compileJava.dependsOn(processResources)

    group = 'com.hes.cc'
    version = '6.2.2-RELEASE'

    dependencies {
        
        annotationProcessor group: "org.projectlombok", "name": "lombok"
        compile group: "org.projectlombok", "name": "lombok"
        annotationProcessor group: 'org.hibernate', name: 'hibernate-jpamodelgen'
        compile group: 'org.hibernate', name: 'hibernate-jpamodelgen'
        annotationProcessor "org.mapstruct:mapstruct-processor:1.2.0.Final"
        compile "org.mapstruct:mapstruct-jdk8:1.2.0.Final"
        annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"
        
        compile "org.hibernate:hibernate-envers"
        compile 'eu.bitwalker:UserAgentUtils:1.21'
        compile 'org.springframework:spring-context-support'
        compile 'org.springframework.boot:spring-boot-starter-web'
        compile 'org.springframework.boot:spring-boot-starter-data-jpa'
        compile 'org.springframework.boot:spring-boot-starter-thymeleaf'
        compile 'org.springframework.boot:spring-boot-starter-security'
        
    }

    compileJava {
        doLast {
            file('build/classes/java/main/META-INF/spring-configuration-metadata.json')
                    .renameTo(file('src/main/resources/META-INF/spring-configuration-metadata.json'))
        }
    }

    dependencyManagement {
        imports {
            mavenBom("org.springframework.boot:spring-boot-dependencies:2.1.1.RELEASE")
        }
    }
}
```

code generator gradle : 

```
buildscript {
    repositories {
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "nu.studer:gradle-jooq-plugin:3.0.2"
    }
}

apply plugin: 'org.springframework.boot'
apply plugin: 'nu.studer.jooq'

dependencies {
    compile project(':data')

    compile group: 'org.postgresql', name: 'postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-jooq'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    compile group: 'org.jooq', name: 'jooq-meta-extensions', version: '3.11.7'


    jooqRuntime "org.postgresql:postgresql"
    jooqRuntime 'org.jooq:jooq-meta-extensions:3.11.7'

}

jooq {

    sample(sourceSets.main) {
        generator {
            name = 'org.jooq.codegen.DefaultGenerator'
            strategy {
                name = 'org.jooq.codegen.DefaultGeneratorStrategy'
            }
            database {
                name = 'org.jooq.meta.extensions.jpa.JPADatabase'
                includes = ".*"
            }

            generate {
            }
            target {
                packageName = 'com.example.jooq'
                directory = 'src/main/java'
            }
        }
    }
}
```

and entity module(data module) : 
```
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
}
```

I spent a lot of time but didn't get a good result.

### Versions/:

- jOOQ: 3.11.7
- Java: 1.8
- Database (include vendor): postgres:42.2.5
- OS: ubuntu
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
It appears that you should add an additional `jooqRuntime` dependency to your project for the code generator to be able to pick it up. Adding it to the `dependencies` is not enough. See also a similar example here:
https://github.com/etiennestuder/gradle-jooq-plugin/blob/17c59c708541c656722d92aa4730f9dd41467512/example/use_custom_generator/build.gradle#L11-L15
