### ISSUE TITLE
Emulate inline window specifications based on other window definitions in SQLite

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8279]
SQLite now supports window functions and jOOQ has added support for them (#7865). SQLite also has native `WINDOW` clause support, so this works:

```sql
select row_number() over a
window a as (partition by 1)
```

However, this doesn't:

```sql
select row_number() over (a order by 1)
window a as (partition by 1)
```

SQLite doesn't support creating inline window specifications that are based on other window definitions. We need to emulate the above by creating this SQL instead:

```sql
select row_number() over synthetic
window 
  a as (partition by 1),
  synthetic as (partition by 1 order by 1) -- a cannot be referenced here either
```

Or even just:

```sql
select row_number() over (partition by 1 order by 1)
```

I.e. not render the `WINDOW` clause at all, but emulate it, which is much simpler to implement.

**Comment by knutwannheden** [comment]
MemSQL has pretty much the same limitation: https://docs.memsql.com/concepts/v6.7/window-functions-guide/

**Comment by lukaseder** [comment]
Interesting, so this might be worth exploring for MemSQL, then! Alternatively, just like in SQLite, we can (for now), just never generate any `WINDOW` clause and inline them all entirely, like e.g. in Oracle.

**Comment by knutwannheden** [comment]
For now I copied the approach for SQLite.
