### ISSUE TITLE
PDF manual is missing content contained in <em> tags

### ISSUE THREAD

**Issue by rmdefi** [jOOQ/jOOQ#8281]
I downloaded the PDF version of the manual for offline reading, but some sentences are missing words, compared to the HTML version. Sometime it is obvious (the sentence doesn't make sense), sometime is is more insidious (changing the meaning of the sentence).

Here are some examples from the manual of jOOQ 3.11:

In section https://www.jooq.org/doc/3.11/manual/getting-started/jooq-and-jpa/, there is the sentence:
"JPA (and ORMs in general) try to solve the object graph persistence problem"
But in the PDF:
' JPA (and ORMs in general) try to solve the problem."
In the same section, there is the title:
"jOOQ only has some of the answers."
But in the PDF it is:
"jOOQ only has of the answers."

Digging a bit in the sources of the manual, and how it is converted to PDF, it seems that all the text that are in _em_ tags are missing.
Looking at the stylesheet converting the source to XSL-FO:
https://github.com/jOOQ/jOOQ/blob/master/jOOQ-manual/src/main/resources/org/jooq/web/pdf.xsl
I think the problem is that there are no explicit rule for transforming an _em_ to something else, so it is handled by the generic rule at
https://github.com/jOOQ/jOOQ/blob/4793a9c4614e3d4f9cf28ae03b4bcac53c828df5/jOOQ-manual/src/main/resources/org/jooq/web/pdf.xsl#L573
which will simply copy it, and the XSL-FO processor don't know what to do with an _em_ element, so I suppose it simply ignore it, along with its content.

So, there should be an explicit rule to convert the _em_ to proper XSL-FO, similar to the one for _strong_ at:
https://github.com/jOOQ/jOOQ/blob/4793a9c4614e3d4f9cf28ae03b4bcac53c828df5/jOOQ-manual/src/main/resources/org/jooq/web/pdf.xsl#L528

I only checked the manual for jOOQ 3.11, but I suppose the problem exists for all versions.

**Comment by lukaseder** [comment]
Thank you very much for your detailed analysis. Indeed, looks like the styling of `<em>` tags was forgotten. Curious that this went undetected for so long - there aren't too many `<em>` tags in the manual...
