### ISSUE TITLE
BatchCRUD does not update optimistic locking version and timestamp values in UpdatableRecord

### ISSUE THREAD

**Issue by yaseenkadir** [jOOQ/jOOQ#8283]
### Expected behavior and actual behavior:
Expected: Batch insert with versioned fields should update the fields on the record.
Actual: Version field does not get updated.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
https://github.com/yaseenkadir/jooq-batch-insert-version-bug/blob/master/src/test/java/com/github/yaseenkadir/jbivb/tables/records/FoobarTest.java#L30-L54

### Versions:

- jOOQ: 3.11.9
- Java: 1.8
- Database (include vendor): Postgresql
- OS: Mac OSX Mojave 10.14.2
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver

**Comment by lukaseder** [comment]
Related https://github.com/jOOQ/jOOQ/issues/11937

**Comment by lukaseder** [comment]
Fixed in versions:

- 3.19.0
- 3.18.8 (https://github.com/jOOQ/jOOQ/issues/15739)
- 3.17.17 (https://github.com/jOOQ/jOOQ/issues/15740)
- 3.16.23 (https://github.com/jOOQ/jOOQ/issues/15741)
