### ISSUE TITLE
Allow configurations for prefix/suffix Table class names

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#830]
Hey, great product!

I'd like to suggest that you make generated table classes configurable in that in jooq.properties I can specify generator.strategy.meta-class-suffix and that gets automatically read by DefaultGeneratorStrategy. It looks like you've already started to implement that functionality. That would be awesome if you could!

**Comment by roma2341** [comment]
Still can't set prefixes... And custom strategy way is not possible because strategy class have to be prebuilt
