### ISSUE TITLE
Emulate procedural languages in H2 for Java 6

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8304]
Currently, for simplicity reasons, we're generating code only for Java 7+ (using try-with-resources in generated procedures). If someone wants to run stored procedures on H2 on Java 6, we'll have to add support for this separately.

**Comment by katzyn** [comment]
The latest stable version of H2 that supports Java 6 is 1.3.176 (2014-04-05).
The latest beta version of H2 that supports Java 6 is 1.4.191 Beta (2016-01-21). 
Both versions are not supported in any way by H2 community.

**Comment by lukaseder** [comment]
Oh interesting, thanks for the pointer. I remember the discussion now, especially the part about the super important Fortune 10 company that has 700 devs on 6 continents (but would probably not have paid a cent for Java 6 maintenance) :-) https://github.com/h2database/h2database/issues/300

So, I'll close this issue here.
