### ISSUE TITLE
Use provided database instead of in-memory H2 for DDLDatabase

### ISSUE THREAD

**Issue by Addvilz** [jOOQ/jOOQ#8311]
### Use case:

It would be very useful to be able to have DDL use a real albeit temporary database instance for code generation instead of embedded H2. This would require some user-side setup, but otherwise could work exactly as H2. 

As an example, for me the real value behind DDL generator is it's ability to pick up SQL files, load and execute them, and produce generated code.

It would be, of course, possible to do this with some custom coding and using the existing code generator, but it would be a nice feature to have as an extra to DDL nevertheless, and might be quite simple to implement based on the DDL that is already there.

At this point, there is no way for me to use DDLDatabase extension for projects where using it is most beneficial - having hundreds of tables designed ER-first and using a lot of vendor specifics that H2 simply has no support for.

Related to #7034.

### Possible solution you'd like to see:

Configurable DDLDatabase or a new extension similar to DDLDatabase with ability to configure JDBC DSN to be used + options to "rewrite" database name, use temporary random name etc.

In perfect scenario, given JDBC DSN the extension could choose a random database name, potentially overwrite the SQL to use that random name (basic find/replace could work as an configurable option?), load the SQL, generate code, and then destroy the database.

### Possible workarounds:

I am currently using a custom Gradle task that works exactly as described in the solution minus the random database name. But it's by no means pretty. And not everyone uses Gradle.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion.

I don't fully understand why you wouldn't just use Flyway before the jOOQ code generation, though? See an example here:
https://github.com/jOOQ/jOOQ/tree/master/jOOQ-examples/jOOQ-flyway-example

**Comment by Addvilz** [comment]
@lukaseder sure thing!

I could use Flyway as well as my own Gradle task (like right now), but given the DDLDatabase is already there, and it works quite close to how Flyway works in theory, why not have this feature native?

Fact is, I don't always use Flyway for various reasons (other schema/migration tools used, other constraints) and I believe this being part of jOOQ directly without need for external tools would be pretty cool thing to have.

**Comment by lukaseder** [comment]
The reason why I'm sceptical is this. You're saying:

> and *it works quite close to how Flyway works in theory*, why not have this feature native?

Yet, you're also saying:

> Configurable DDLDatabase or a new extension similar to DDLDatabase *with ability to configure JDBC DSN to be used + options to "rewrite" database name, use temporary random name etc.*

That *etc.* is a treacherous one. Sooner than later, this DDLDatabase will evolve in a full fledged Flyway, at which point I'm wondering why not just use Flyway?

At this point, I don't see a compelling enough use case to move forward with a Flyway-style DDLDatabase given that using Flyway properly is such an easy alternative, even if *"I don't always use Flyway for various reasons (other schema/migration tools used, other constraints)"*. This doesn't mean I completely disagree with your request, it just means I don't see a good reason to prioritise it right now.

Note, the main benefit of the DDLDatabase is not to have any dependencies on an actual external database. Running translated DDL on H2 works well. Maybe even better would be to interpret / simulate the DDL in memory (#7034), which will remove the dependency on actual H2 features.

But if an in-memory / temporary database running on the target RDBMS software is an option, then adding the Flyway maven / gradle plugin to the build prior to running the jOOQ code generator is really the best solution.

**Comment by Addvilz** [comment]
For me the main argument is user experience - I just want to add some jOOQ dependencies, point it to a) SQL schema b) JDBC connection, and get code generated out of it. Generating code from JDBC connection is a good option as it is, yet not always convenient - what database instance do you point jOOQ to, to get the latest schema? Local? Remote for specific version? It's a perfectly fine option, but not for all use cases. Option A with DDLDatabase is very nice option, but for one issue - H2 does not support everything MySQL would, for example. At the end you are left with a choice - generate code from real database, generate code from SQL (unless you have incompatible schema or limit yourself to only what H2 supports) or use a 3rd party tool. 

All of the available options have merit and use cases to them, sure, I do not doubt that. In fact, option of generating code from a database has been working very well for me now for quite a few years. What I am trying to convey, it could potentially be done better, even if it means replicating part of a tool that already exists for the sake of improved user experience providing an end-to-end solution.

As far as priorities goes, I have no expectations here. There are workarounds to achieve this, so please take this as just a suggestion if you consider at some point to move in this direction.

**Comment by lukaseder** [comment]
> All of the available options have merit and use cases to them, sure, I do not doubt that. In fact, option of generating code from a database has been working very well for me now for quite a few years. What I am trying to convey, it could potentially be done better, even if it means replicating part of a tool that already exists for the sake of improved user experience providing an end-to-end solution.

I don't deny the possibility of an improved user experience if a user only needs to use a single tool instead of two. But there's a cost / benefit ratio, and I sincerely believe that at this point, using Flyway yields much lower cost / higher benefit than doing what you suggest.

I'm open to discussing why you think this isn't the case, but so far, I'm still missing the big trouble you're having in using Flyway

> There are workarounds to achieve this

The way I understand this, the "workaround" here is to implement a partial Flyway in jOOQ. The thorough solution is to use Flyway. But maybe, you could better describe the pain points to help me better understand why you don't like that approach.

**Comment by lukaseder** [comment]
Related, or possibly duplicate: #6551
