### ISSUE TITLE
Better implementation for internal ScopeStack

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8315]
The internal `ScopeStack` is used for:

- Resolving implicit joins
- Resolving local variables in procedural scopes (`BEGIN .. END`)

It will be used for other things in the future. The current implementation is rather canonical, modelling scope environments as `Map<K, List<V>>` where the value list is the stack, which is filled with nulls in case a scope is deeply nested.

There are other implementations possible, including a `Map<K, V>`, where the map contains only the current scope level, and a separate `List<K|V|int>` map contains all the "pushed" state that is hidden / shadowed at any given scope level. Discussion here:
https://twitter.com/hkdennis2k/status/1093535837126516736

The motivation of the improved solution is to optimise for arbitrary scopes where hiding is the exception (which should mostly be the case).

**Comment by knutwannheden** [comment]
I will look into this.

I think I found a small optimization opportunity for `DefaultRenderContext#scopeRegister()`: We shouldn't need to build both the `tables` and the `keys` lists.

Original code:

```java
    @Override
    public RenderContext scopeRegister(QueryPart part) {
        if (scopeStack.inScope()) {
            if (part instanceof TableImpl) {
                Table<?> root = (Table<?>) part;
                Table<?> child = root;
                List<ForeignKey<?, ?>> keys = new ArrayList<ForeignKey<?, ?>>();
                List<Table<?>> tables = new ArrayList<Table<?>>();

                while (root instanceof TableImpl && (child = ((TableImpl<?>) root).child) != null) {
                    keys.add(((TableImpl<?>) root).childPath);
                    tables.add(root);
                    root = child;
                }

                ScopeStackElement e = scopeStack.getOrCreate(root);
                if (e.joinNode == null)
                    e.joinNode = new JoinNode(root);

                JoinNode childNode = e.joinNode;
                for (int i = keys.size() - 1; i >= 0; i--) {
                    ForeignKey<?, ?> k = keys.get(i);
                    Table<?> t = tables.get(i);

                    JoinNode next = childNode.children.get(k);
                    if (next == null) {
                        next = new JoinNode(t);
                        childNode.children.put(k, next);
                    }

                    childNode = next;
                }
            }
        }

        return this;
    }
```

Without `keys`:

```java
    @Override
    public RenderContext scopeRegister(QueryPart part) {
        if (scopeStack.inScope()) {
            if (part instanceof TableImpl) {
                Table<?> root = (Table<?>) part;
                Table<?> child = root;
                List<Table<?>> tables = new ArrayList<Table<?>>();

                while (root instanceof TableImpl && (child = ((TableImpl<?>) root).child) != null) {
                    tables.add(root);
                    root = child;
                }

                ScopeStackElement e = scopeStack.getOrCreate(root);
                if (e.joinNode == null)
                    e.joinNode = new JoinNode(root);

                JoinNode childNode = e.joinNode;
                for (int i = tables.size() - 1; i >= 0; i--) {
                    Table<?> t = tables.get(i);
                    ForeignKey<?, ?> k = ((TableImpl<?>) t).childPath;

                    JoinNode next = childNode.children.get(k);
                    if (next == null) {
                        next = new JoinNode(t);
                        childNode.children.put(k, next);
                    }

                    childNode = next;
                }
            }
        }

        return this;
    }
```

**Comment by lukaseder** [comment]
Without having studied the suggestion, I'm sure there is room for small improvements in the existing algorithm, but I really think we should replace the algorithm entirely. Not necessarily the one in `DefaultRenderContext`, but the one in `ScopeStack`

**Comment by knutwannheden** [comment]
Understood. I would like to start with creating a more complete test suite for the existing implementation.

**Comment by lukaseder** [comment]
Absolutely.

**Comment by knutwannheden** [comment]
I still have some difficulty understanding the concrete proposal here. At the very least it is necessary that the scope stack remembers which level a variable was defined in, so that it can be removed again, when leaving that level / context.

Another naive implementation would be based on `List<Map<K, V>>`, where the list represents the scope stack. To make lookups faster, one could have an additional `Map<K, V>` containing the merged set of all currently visible variables. But it seems like this isn't quite what is being proposed.

**Comment by lukaseder** [comment]
The point is that the stack doesn't need to know exactly what elements are being pushed on the stack. If all pushing ops and popping ops are in the correct order, they will push and pop the right things automatically. Just like in Java's serialization algorithm. You don't need to adhere to any specific format, as long as all serialisers and deserialisers "push" and "pop" things in the right order.

The point here (as mentioned also in this tweet: https://twitter.com/hkdennis2k/status/1093535837126516736) is to have:

1. A mutable map for current values in scope
2. A stack for values that are hidden/shadowed, and *only* for those values

Based on the assumption that hiding/shadowing is done only very rarely, *especially* in the context of jOOQ's usage of this `ScopeStack`, this seems like a very optimal implementation.

**Comment by knutwannheden** [comment]
If the client calls `set()` to "push" an element there would now have to be a new `unset()` operation to "pop" an element, which the client would have to call before `scopeEnd()`?

Otherwise I don't quite see how this would work for your example below (I added `k`). How would the `ScopeStack` know to remove `k` when leaving the nested scope?

```ada
declare
  i int;
  j int;
begin
  -- in scope: i, j
  declare
    i int;
    k int;
  begin
    -- in scope: i (nested, out i is shadowed), j, k
    null;
  end;
end;
```

I feel like I am missing something here...

**Comment by lukaseder** [comment]
The `ScopeStack` should take care of it. We're pushing stuff on a certain *level* (and we tell the `ScopeStack` when we enter or leave a level). The `ScopeStack` takes care of keeping track what element was pushed on what level, and when to restore it.

```sql
declare -- Entering new level 1
  i int; -- Declaring i on 1
  j int; -- Declaring j on 1
begin
  -- in scope: i, j
  declare -- Entering new level 2
    i int; -- Declaring i on 2, push (i, 1) to the stack
    k int; -- Declaring k on 2
  begin
    -- in scope: i (nested, out i is shadowed), j, k
    null;
  end; -- Leaving level 2, popping (i, 1) from the stack, deleting k from the scope
end; -- Leaving level 1, deleting i and j from the scope
```

**Comment by knutwannheden** [comment]
> The `ScopeStack` should take care of it.

That is what I also thought. But I still don't see how this can be achieved only with a mutable map for all visible variables and a stack for hidden variables only. The variable `k` would thus not be in the stack, only in the map. But then the map's type can't be `Map<K, V>`, as the associated level wouldn't be captured.

Again, I seem to be missing something...

**Comment by lukaseder** [comment]
If you re-read the description, one possible implementation (1) is to have the map contain only the *current* level's data and to push *everything* else on the stack.

Another implementation possibility (2) that hasn't been mentioned in the issue (but on the twitter discussion, I believe) is to have the map contain the *current* level and level annotation information, and the stack contains only data that has been shadowed.

(1) has a simpler current level map but copies more stuff around, (2) has more data on the current level map but is more lazy with copying stuff around.

There are surely other possibilities. This must have been discussed millions of times when designing compilers and similar things. I haven't done all the research yet, but I'm positive something far more optimal than the current implementation can be found.

**Comment by knutwannheden** [comment]
OK, then I understand. I was confused by some of the phrasing. Essentially (1) boils down to a `List<Map<K, V>>` implementation.

What I like about the current solution is that it has fast lookups, which isn't so well supported by (1) without any additional structure.

Let's further discuss exactly which operations we need to optimize here and what the data will look like (scope levels and variable counts). But we could certainly improve the current implementation by only "growing" the lists when `put()` is called (currently `get()` also does this). This would speed up `get()` to `O(1)`. I suggest we do this and then use that as a reference when comparing against other implementations.

**Comment by lukaseder** [comment]
> Essentially (1) boils down to a `List<Map<K, V>>` implementation.

You can try it but I doubt this will perform well for long lists. JDK's maps have a lot of initial overhead. Early jOOQ records were maps. `Object[]` is *much* better as a backing storage.

> What I like about the current solution is that it has fast lookups, which isn't so well supported by (1) without any additional structure.

What's your worry? There's always a map containing everything that's in scope. There's that additional data structure containing previous scope levels for the sake of restoring them when we exit the scope. Accessing scope data is always O(1)

> Let's further discuss exactly which operations we need to optimize here 

We need to find a tradeoff between optimising for:

- Lots of variables
- Lots of scopes (depth)
- Lots of shadowing

In descending order of importance

> But we could certainly improve the current implementation by only "growing" the lists when put() is called (currently get() also does this). This would speed up get() to O(1). 

Yes please try that. That could be backported, perhaps

**Comment by knutwannheden** [comment]
Great. I will also try to work out some "representative" examples with access patterns which we can use in benchmark tests.

**Comment by knutwannheden** [comment]
The change to `DefaultRenderContext.scopeRegister()` yields an improvement of around 3-4% in the SQL rendering.

**Comment by lukaseder** [comment]
So far, this hasn't really been popping up in benchmark profiling sessions, so I doubt that this is really that big of a bottleneck.
