### ISSUE TITLE
Publish existing jOOQ-xtend project as a Maven module

### ISSUE THREAD

**Issue by dantonini** [jOOQ/jOOQ#8323]
Hi,
There is the jooq-xtend module in source repository but no artifact in maven central.
It would be nice to have.

Cheers

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I agree, this should be done. If I remember correctly, at the time this "module" was created, there didn't exist good maven plugins for Xtend...

**Comment by lukaseder** [comment]
Starting from jOOQ 3.13, we'll publish this project as a Maven module both on Maven Central and in our commercial ZIP files.
