### ISSUE TITLE
Wrong documentation for forceIntegerTypesOnZeroScaleDecimals

### ISSUE THREAD

**Issue by marceloverdijk** [jOOQ/jOOQ#8332]
### Expected behavior and actual behavior:

I have a Postgres db with types like `NUMERIC(4)` for which the jOOQ codegen generates something like:

```
public final TableField<SeasonRecord, Short> YEAR = createField("year", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");
```

Because it is a small numeric jOOQ decides to use a `Short`.

However I would like to generate an `Integer` type instead.

Reading https://www.jooq.org/doc/3.11/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-zero-scale-decimals/ I was hoping to change the generator behaviour.

That page mentions to do:

```
configuration
  .withGenerator(new Generator(
    .withGenerate(new Generate()
      .withForceIntegerTypesOnZeroScaleDecimals(true))));
```

but the `Generate` class does not have `withForceIntegerTypesOnZeroScaleDecimals` method.

Looking at Github I noticed the `Database` class does have such a method: https://github.com/jOOQ/jOOQ/blob/master/jOOQ-meta/src/main/java/org/jooq/meta/jaxb/Database.java#L1531

So I wonder if the documentation is correct?

When using it like:

```
                .withGenerator(Generator()
                    .withDatabase(Database()
                        .withForceIntegerTypesOnZeroScaleDecimals(true)
                        .withName("org.jooq.meta.postgres.PostgresDatabase")
                        .withInputSchema("public")
                        .withOutputSchemaToDefault(true))
```

(at least this compiles) but either the generator does not pick it up or my expectation is wrong.

It still generates the `Short` instead of the `Integer` I was expecting / hoping for:

```
public final TableField<SeasonRecord, Short> YEAR = createField("year", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");
```

### Versions:

- jOOQ: `3.11.9`
- Java: `8` 
- Database (include vendor): `Postgres 10`
- OS: `MacOS`
- JDBC Driver (include name if inofficial driver): `org.postgresql:postgresql:42.2.5`

**Comment by lukaseder** [comment]
Thank you very much for your report. Interesting observation, I can totally see how this could have been misunderstood. What is meant here by "integer types" is ... integer in the mathematical sense. In other words, anything but a `BigDecimal` (including `BigInteger`) :)

So the behaviour is correct. `Short` is the most "appropriate" integer type for a `NUMERIC(4)` type. I will improve the documentation to explain this better.

You can use the data type rewriting feature, where you simply tell the jOOQ code generator that your `NUMERIC(4)` type should really be an `INT` type:
https://www.jooq.org/doc/latest/manual/code-generation/data-type-rewrites

**Comment by lukaseder** [comment]
Hmm, thinking about it, is there really anything missing in the documentation?
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-zero-scale-decimals

**Comment by marceloverdijk** [comment]
OK the behaviour was misunderstood indeed :-)
I will look into https://www.jooq.org/doc/latest/manual/code-generation/data-type-rewrites.

The error in the documentation is regarding https://www.jooq.org/doc/3.11/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-zero-scale-decimals/

It mentions:

```
configuration
  .withGenerator(new Generator(
    .withGenerate(new Generate()
      .withForceIntegerTypesOnZeroScaleDecimals(true))));
```
 
But the `withForceIntegerTypesOnZeroScaleDecimals` method is not on the `Generate` class.
It is on the `Database` class like:

```
.withGenerator(Generator()
  .withDatabase(Database()
    .withForceIntegerTypesOnZeroScaleDecimals(true))
```

See https://github.com/jOOQ/jOOQ/blob/master/jOOQ-meta/src/main/java/org/jooq/meta/jaxb/Database.java#L1531

**Comment by lukaseder** [comment]
Oh indeed, you're right! I'm sorry for the confusion, how could I miss that from your original description...
