### ISSUE TITLE
DSL.noCondition()

### ISSUE THREAD

**Issue by mbayealioune** [jOOQ/jOOQ#8344]
### Your question:
Hi,
I am backporting code using jooq 3.11 to jooq 3.10 version.
And I was using in the 3.11 code version, things like:
`if( searchingCondition.equals( DSL.noCondition() ) )`
or
`DSL.noCondition().and(....`

How can I do the same thing in jooq 3.10 where DSL.noCondition() does not exist ?

Thnx in advance for your help.

### Versions:

- jOOQ: 3.10
- Java: 8
- Database (include vendor): Postgres
- OS: Linux Centos
- JDBC Driver (include name if inofficial driver): postgresql-jdbc4

**Comment by lukaseder** [comment]
Thank you very much for your message.

Previous versions of jOOQ had `DSL.trueCondition()` (for use with `AND`) and `DSL.falseCondition()` (for use with `OR`). They work almost the same way as `DSL.noCondition()`, except that they generate an "ugly" `1 = 1` or `1 = 0` predicate in the generated SQL. It doesn't affect your SQL query semantics or performance, it's just less nice.

Hope this helps

**Comment by mbayealioune** [comment]
Thank you very much for the quick response
and BTW, you've done a great job guys, the framework is awesome !
