### ISSUE TITLE
Problem with parsing UUID[] in PostgreSQL

### ISSUE THREAD

**Issue by estertheracoon** [jOOQ/jOOQ#8348]
Hi Lukas,

As explained on https://stackoverflow.com/questions/54803631/parse-an-array-of-uuids, we get an exception when getting back a field of type `UUID[]`. It happens with the following code and schema:

```
    context
        .select(Tables.T1.IDENTIFIER)
        .select(PostgresDSL.array(context.select(Tables.T2.IDENTIFIER).from(Tables.T2).where(<omitted>)).as("_references"))
        .from(Tables.T1)
        .fetch();

    t1(identifier uuid primary key)
    t2(identifier uuid primary key, t1_identifier uuid foreign key t1(identifier))
```

We get:

```
    org.jooq.exception.DataTypeException: Cannot convert from e472b684-0b04-4799-a3e1-a31711a78182 (class org.postgresql.util.PGobject) to class java.util.UUID
        at org.jooq.tools.Convert$ConvertAll.fail(Convert.java:1166)
        at org.jooq.tools.Convert$ConvertAll.from(Convert.java:1055)
        at org.jooq.tools.Convert.convert0(Convert.java:321)
        at org.jooq.tools.Convert.convert(Convert.java:313)
        at org.jooq.tools.Convert.convert(Convert.java:385)
        at org.jooq.impl.DefaultBinding$DefaultUUIDBinding.get0(DefaultBinding.java:3805)
```

If you need additional information from me, please let me know that.

I thank you kindly!

Ester, The Racoon

**Comment by estertheracoon** [comment]
An additional question: is there a work-around possible?

**Comment by lukaseder** [comment]
Thank you very much for your report. I'm sorry, I cannot reproduce this issue neither on jOOQ 3.12 nor on 3.11.9. I'm probably missing something from your specific setup. Would it be possible to create an MCVE to be sure this can be reproduced? A template can be found here:
https://github.com/jOOQ/jOOQ-mcve

**Comment by estertheracoon** [comment]
Hi Lukas,

Something must have been (very) off, because I cannot reproduce it anymore. All is working fine now.

I will close this report and re-open if I can reproduce it.

**Comment by lukaseder** [comment]
Great, thanks for the feedback!
