### ISSUE TITLE
Add fetchOneAsync

### ISSUE THREAD

**Issue by zatziky** [jOOQ/jOOQ#8354]
### Use case:

We need to fetch one result asynchronously.

### Possible solution you'd like to see:

I'd like to see a method `fetchOneAsync()`. 

```
return dsl
   ...
   .fetchOneAsync()
```

### Possible workarounds:

```
return supplyAsync(() -> {
    return dsl
       ...
       .fetchOne()
)
```

### Additional info
There's already `fetchAsync()` but it maps to a collection.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I'll close this as a duplicate of #7951
