### ISSUE TITLE
Add support for Sequence Increment By and Start option

### ISSUE THREAD

**Issue by benallard** [jOOQ/jOOQ#8366]
### Use case:

Using the DDL module

``` java
aContext.createSequence("SEQ_NAME").execute
```

I wish I could specify the increment by value and start value.

### Possible solution you'd like to see:

``` java
aContext.createSequence(DSL.sequence("SEQ_NAME").incrementBy(50).startWith(1000)).execute()
```

Like we do with constraints or such.

### Possible workarounds:

``` java
aContext.execute("CREATE SEQUENCE SEQ_NAME INCREMENT BY 50 START WITH 1000");
```

### Versions:

- jOOQ: 3.10.6
- Java: 8
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your request. We've implemented these and others for jOOQ 3.12 through #7748
