### ISSUE TITLE
This works in pgAdmin

### ISSUE THREAD

**Issue by lveronese** [jOOQ/jOOQ#8378]
### SQL translator does not parse this query:

```sql
update utl_load_rec r
set data = substring(data, 1, 1) || '"dataReg":"@date:'|| to_char(t.load_time, 'DD\/MM\/YYYY') ||'",' || substring(r.data, 2)
from utl_load t
where t.codice_azienda = r.codice_azienda
and t.load_id = r.load_id
and t.mode = 'FE' 
and position('"dataReg":' IN r.data) = 0
```

### Parser output:

```sql
Token ')' expected: [2:78] ...1, 1) || '"dataReg":"@date:'|| to_char(t.load_time[*], 'DD\/MM\/YYYY') ||'",' || substring(r.data, 2)
from utl_load t
where t.codice_...
```

**Comment by lveronese** [comment]
Also, if I remove the second argument, I get this translation for SQL Server 2014:
```SQL
UPDATE r
SET data = ((((substring(
      data, 
      1, 
      1
    ) + '"dataReg":"@date:') + CAST(t.load_time AS varchar(max))) + '",') + substring(
      r.data, 
      2, 
      2147483647
    ))
FROM utl_load t
WHERE (
  t.codice_azienda = r.codice_azienda
  AND t.load_id = r.load_id
  AND t.mode = 'FE'
  AND CHARINDEX('"dataReg":', r.data) = 0
)
```
which references r which is a non existing table, since this was the alias of the original UPDATE target table.

**Comment by lukaseder** [comment]
Thanks for your report. Interesting, I could have sworn we already support for `TO_CHAR(date, string)`, given that we support parsing `TO_DATE(string, string)` (not necessarily translating it). I have created a feature request for this to support `TO_CHAR()` in the DSL API: #8381. The parser will support it via #7518

Indeed, aliased tables are not allowed in SQL Server's `UPDATE` clause, so this must be emulated. We could remember that all `r` references are really `utl_load_rec` and inline the alias in SQL Server wherever the scope of the original `r` has not been overridden:

```sql
UPDATE utl_load_rec
SET data = ((((substring(
      data, 
      1, 
      1
    ) + '"dataReg":"@date:') + CAST(t.load_time AS varchar(max))) + '",') + substring(
      utl_load_rec.data, 
      2, 
      2147483647
    ))
FROM utl_load t
WHERE (
  t.codice_azienda = utl_load_rec.codice_azienda
  AND t.load_id = utl_load_rec.load_id
  AND t.mode = 'FE'
  AND CHARINDEX('"dataReg":', utl_load_rec.data) = 0
)
```

I have created a separate issue for this: #8382

The workaround for now is to do this manually in your original query.

Thanks again for reporting! I'll close this issue as a duplicate as its parts will be dealt with in 3 separate issues.

**Comment by lukaseder** [comment]
A possibly more robust way to emulate this, at least for SQL Server, would be to generate a CTE:

```sql
WITH r AS (SELECT * FROM utl_load_rec)
UPDATE r
SET data = ((((substring(
      data, 
      1, 
      1
    ) + '"dataReg":"@date:') + CAST(t.load_time AS varchar(max))) + '",') + substring(
      r.data, 
      2, 
      2147483647
    ))
FROM utl_load t
WHERE (
  t.codice_azienda = r.codice_azienda
  AND t.load_id = r.load_id
  AND t.mode = 'FE'
  AND CHARINDEX('"dataReg":', r.data) = 0
)
```

That way, SQL Server can figure out the correct name resolution.

**Comment by lukaseder** [comment]
In fact, we already have such a CTE based approach in place, when updating views in SQL Server (#3606):

**Oracle**:

```sql
update (select * from t) t
set t.x = 1;
```

**SQL Server**

```sql
with t as (
  select *
  from t
)
update t
set t.x = 1
```

So, this will be straightforward.
