### ISSUE TITLE
Pull up OracleDSL.toChar() to DSL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8381]
Oracle and PostgreSQL (and possibly others) support formatting temporal data types using `TO_CHAR(date, format)`. We should pull up the `OracleDSL.toChar()` methods to `DSL` and make them generally available. For static format strings, we can probably get quite far emulating those.

**Comment by knutwannheden** [comment]
The parser also still needs support for the `TO_CHAR` function with two arguments.

**Comment by lukaseder** [comment]
Reviewing this again for inclusion in jOOQ 3.14 as it is a frequently failing feature in queries submitted to https://www.jooq.org/translate

**Comment by lukaseder** [comment]
See also: https://github.com/jOOQ/jOOQ/issues/10641
