### ISSUE TITLE
Allow forced types to only match columns in a particular table

### ISSUE THREAD

**Issue by robertatcanva** [jOOQ/jOOQ#8392]
### Use case:

Hi,

Apologies if I've misread the documentation or have missed something.

It appears that the expression in forcedType is used for matching against column names only, or can be used in conjunction with the types element to match (column name, type). Unfortunately we have a number of cases where we have columns with the same name and type in the same database, but in different tables: and we only want to use a forcedType binding for those columns in some of the tables.

### Possible solution you'd like to see:

Support for matching a subset of tables for forcedTypes.

### Versions:

- jOOQ: 3.11.1
- Java: 8+
- Database (include vendor): MySQL 5.6
- OS: Linux
- JDBC Driver (include name if inofficial driver): MySQL

**Comment by lukaseder** [comment]
Thank you very much for your message.

Almost all regular expressions that match identifiers in jOOQ's code generator try to match:

- The unqualified identifier
- The fully qualified identifier

Do note that "fully" here means that you may have to include catalog and/or schema, or use wildcards:

```xml
<forcedType>
  <expression>.*\.TABLE_NAME\.COLUMN_NAME</expression>
</forcedType>
```

Hope this helps

**Comment by robertatcanva** [comment]
That worked! Thanks very much.
