### ISSUE TITLE
Sakila data insertion script produces foreign key constraint violations for PostgreSQL

### ISSUE THREAD

**Issue by bmintz** [jOOQ/jOOQ#8400]
#### Expected

The only errors that are output are related to permissions, for instance:

```
psql:postgres-sakila-insert-data.sql:108: ERROR:  permission denied: "RI_ConstraintTrigger_a_25128" is a system trigger
```

#### Actual 

There are also errors about foreign key violations (just a few of them are provided here):

```
psql:postgres-sakila-insert-data.sql:7771: ERROR:  insert or update on table "staff" violates foreign key constraint "staff_store_id_fkey"
DETAIL:  Key (store_id)=(1) is not present in table "store".
psql:postgres-sakila-insert-data.sql:7776: ERROR:  insert or update on table "staff" violates foreign key constraint "staff_store_id_fkey"
DETAIL:  Key (store_id)=(2) is not present in table "store".
```

```
psql:postgres-sakila-insert-data.sql:231608: ERROR:  insert or update on table "payment" violates foreign key constraint "payment_customer_id_fkey"
DETAIL:  Key (customer_id)=(599) is not present in table "customer".
```

```
psql:postgres-sakila-insert-data.sql:12919: ERROR:  insert or update on table "inventory" violates foreign key constraint "inventory_store_id_fkey"
DETAIL:  Key (store_id)=(1) is not present in table "store".
```

### Steps to reproduce the problem:

As an unprivileged postgresql user (ie not the superuser):

1. `psql -c 'CREATE DATABASE sakila;'`
2. `psql -d sakila -f postgres-sakila-schema.sql`
3. `psql -d sakila -f postgres-sakila-insert-data.sql 2>insert-data-errors`

### Versions:

- jOOQ: commit ed7733e8b1d73674f01e3a61a6f37d708e4b68c9
- Java: N/A
- Database (include vendor): postgresql 11.1-3 (Arch Linux extra repository)
- OS: Linux kernel version 4.20.12-arch1-1-ARCH
- JDBC Driver (include name if inofficial driver): N/A

**Comment by bmintz** [comment]
[Full error log from step 3](https://github.com/jOOQ/jOOQ/files/2950698/insert-data-errors.txt)

It would seem that this is simply due to the INSERT INTO statements being in the wrong table order:
`store` comes after `staff` for instance. Oddly, running the script multiple times did not reduce the occurrence of foreign key violations.

**Comment by bmintz** [comment]
As a workaround for those also looking for a PostgreSQL port of the Sakila database, I found a page of [sample databases](https://wiki.postgresql.org/wiki/Sample_Databases) from the Postgres wiki. There's a link on there to pgFoundry, where they have a Postgres port called pagila. I also found a more recently updated version of pagila: https://github.com/devrimgunduz/pagila

**Comment by lukaseder** [comment]
Thank you very much for your report. I just tried the deletion script, which produces another error...

> SQL Error [23503]: FEHLER: Aktualisieren oder Löschen in Tabelle »staff« verletzt Fremdschlüssel-Constraint »store_manager_staff_id_fkey« von Tabelle »store«  Detail: Auf Schlüssel (staff_id)=(1) wird noch aus Tabelle »store« verwiesen.

Will look into these right away

**Comment by lukaseder** [comment]
> As an unprivileged postgresql user (ie not the superuser)

Indeed, the `postgres` user doesn't run into this problem

**Comment by lukaseder** [comment]
Hmm, I'm not sure how a not super user and not owner should be able to manipulate such schema objects in PostgreSQL: https://dba.stackexchange.com/a/69552/2512

I'm closing this as won't fix. Our examples currently make this assumption of being run as that super user. If there's an easy fix to this problem, I'm very open to suggestions on how to alter the scripts.
