### ISSUE TITLE
Add support for parsing REGEXP, RLIKE, and LIKE_REGEX operator

### ISSUE THREAD

**Issue by hariprasad501** [jOOQ/jOOQ#8401]
Trying to convert Mysql query with REGEXP to Oracle 10g, but failing
### SQL translator incorrectly translates this query:

```sql
select * from pet where name REGEXP 'w'
```

### Parser output:

```sql
Unexpected token or missing query delimiter: [1:30] select * from pet where name [*]REGEXP 'w'
```

**Comment by lukaseder** [comment]
Thanks a lot for your report. We'll fix this soon.

**Comment by lukaseder** [comment]
`REGEXP` *and* `RLIKE` are both synonyms for `REGEXP_LIKE()`, which makes the expression a bit more compatible, see https://dev.mysql.com/doc/refman/8.0/en/regexp.html#operator_regexp

**Comment by lukaseder** [comment]
`NOT REGEXP` and `NOT RLIKE` also exist as operators.

**Comment by lukaseder** [comment]
`LIKE_REGEX` is the equivalent operator in DB2, Derby, Firebird, Ingres, SQL Server, Sybase.
