### ISSUE TITLE
Is there a way to create a copy of a statement/query?

### ISSUE THREAD

**Issue by hellectronic** [jOOQ/jOOQ#8408]
I tried to search for an answer, but did not find anything about copying a statement/query.

The use case:
* create a stament until point A, make a copy B
* call getQuery() and optionally call query.addLimit()
* use copied statement B for another call

The two statements differ mostly only in optional Limits and should be two separate statements.

**Comment by lukaseder** [comment]
The current API does not allow for this as it is partially mutable. See also:
https://www.jooq.org/doc/3.11/manual/sql-building/sql-statements/dsl-and-non-dsl

However, nothing prevents you from building jOOQ queries in a functional way:
https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq/

... in case of which it will be straightfoward to implement what you're trying to do.

I hope this helps

**Comment by hellectronic** [comment]
Ok, thank you for the fast response!
