### ISSUE TITLE
H2: Cannot use = ANY() with column from select

### ISSUE THREAD

**Issue by ivangreene** [jOOQ/jOOQ#8410]
### Expected behavior and actual behavior:
When using H2 database, `DSL.any(Field<>)` cannot be used with a Field that is the result of a select. This results in the error:
```
Caused by: org.h2.jdbc.JdbcSQLException: Column "v.c1" not found; SQL statement:
select "MCVE"."TEST"."VALUE", "MCVE"."TEST"."ID", "v"."c1" from "MCVE"."TEST", ((select null "c1" where 1 = 0) union all (select * from (values ((cast(? as int), cast(? as int), cast(? as int), cast(? as int))), ((cast(? as int), cast(? as int)))) "v")) "v" where "MCVE"."TEST"."VALUE" = any (select "array_table"."COLUMN_VALUE" from table("COLUMN_VALUE" integer = "v"."c1") "array_table") [42122-197]
```
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
See MCVE test here: https://github.com/ivangreene/jOOQ-mcve/blob/0632514e5d33b9b2c55206c08e4e2785f04314d1/src/test/java/org/jooq/mcve/test/MCVETest.java

### Versions:

- jOOQ: 3.11.7
- Java: SE 8
- Database (include vendor): H2 1.4.197
- OS: MacOS 10.14.2
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your report. I can reproduce this issue. Will investigate right away.

**Comment by lukaseder** [comment]
I wonder if this is really a bug in jOOQ or rather a missing feature in H2, where H2 cannot resolve the array column name in this particular syntax. I'll run this by the H2 maintainers...

**Comment by lukaseder** [comment]
This is the issue I've created in H2: https://github.com/h2database/h2database/issues/1815. If the issue is confirmed, then jOOQ's generated SQL is correct, just doesn't work yet. If the issue is not confirmed, we need to find another way to do this operation, but I currently cannot think of one.

**Comment by lukaseder** [comment]
As suggested here: https://github.com/h2database/h2database/issues/1815#issuecomment-473858648

We can directly call `unnest()` in the predicate, rather than calling it from a `from` clause. This works:

```sql
select *
from (values (array[1, 2])) t(a)
where 1 in (unnest(t.a));
```

**Comment by ivangreene** [comment]
Thanks for doing the research on that! Unfortunately as far as I can tell this is a condition that cannot be expressed in jOOQ (without raw sql) because `Field#in` does not accept a Table which is returned by `DSL#unnest`. So I think for now I will just use `DSL.sql` with this condition

**Comment by ivangreene** [comment]
Unfortunately this does not look like it works correctly on H2 v1.4.997. I am getting false positives on the predicate (I had to modify the above suggestion a bit, using the jOOQ generated sql as a starting place):
```sql
select "v"."c1" from ((select null "c1" where 1 = 0) union all (select * from (values ((1, 2)), ((3, 4))) "v")) "v" where 0 in (table(i int = "v"."c1"));
```
This will return 2 rows, which is incorrect because 0 appears in none of them.

Trying H2 v1.4.999 seems to handle the predicate properly, however the above syntax I posted does not work in v1.4.999 due to a separate issue, I will create another.

**Comment by katzyn** [comment]
Just for information.

1. `IN` predicate in H2 before 1.4.198 does not support row values on the left side and multi-column queries on the right side. There were some workarounds with H2-specific arrays, but all these workarounds don't work any more and should be replaced with the standard syntax.

2. The `(SELECT NULL columnName WHERE FALSE) UNION ALL (real values)` in the generated SQL here looks like a replacement for a derived column list. For H2 1.4.198+ something like `SELECT * FROM (real values) T(columnName)` is expected here. Derived column list syntax in 1.4.197 has known issues and older versions don't support it at all.

**Comment by lukaseder** [comment]
> @ivangreene Unfortunately as far as I can tell this is a condition that cannot be expressed in jOOQ (without raw sql) because Field#in does not accept a Table which is returned by DSL#unnest

Indeed, and we might generate that kind of SQL in the future for you, even if you continue using the current API methods. This will be transparent to users.

> @katzyn IN predicate in H2 before 1.4.198 does not support row values on the left side and multi-column queries on the right side. There were some workarounds with H2-specific arrays, but all these workarounds don't work any more and should be replaced with the standard syntax.

We'll figure it out

> The (SELECT NULL columnName WHERE FALSE) UNION ALL (real values) in the generated SQL here looks like a replacement for a derived column list. For H2 1.4.198+ something like SELECT * FROM (real values) T(columnName) is expected here. Derived column list syntax in 1.4.197 has known issues and older versions don't support it at all.

Indeed. We're currently staying backwards compatible with older H2 versions.

**Comment by lukaseder** [comment]
> Indeed. We're currently staying backwards compatible with older H2 versions.

This claim has been reviewed. jOOQ 3.12 will support H2 1.4.198+. We will not maintain compatibility with older versions.

**Comment by lukaseder** [comment]
I've had another look at this. I don't think jOOQ can help you work around this. H2 is missing a feature which jOOQ calls "correlated derived tables". For example, this doesn't work:

```sql
select *
from (values (1)) as t (a)
where a in (
  select x
  from (
    select a
  ) u (x)
);
```

The error is:

> SQL Error [42122] [42S22]: Column "A" not found; 

Derived table `t` is correlated to the outer query as its contents reference `t.a`. This works in numerous RDBMS, including e.g. PostgreSQL:

```
|a  |
|---|
|1  |
```

But not in H2. And as such, I don't think the `ANY(array field reference)` expression can be made to work.
