### ISSUE TITLE
Add utility method to define negative computed value

### ISSUE THREAD

**Issue by dantonini** [jOOQ/jOOQ#8411]
Hi, 
I don't know if this is a real lack (or just my ignorance)

Here is my scenario:
I want update a column with a negative computed value, let's say
field2 = - field1

How can I do that?
I cannot found a way to define negative computed value but using the following workaround:
ctx.update(TABLE).set( FIELD2, DSL.val(BigDecimal.ZERO).minus(FIELD2) )

Am I missing something? 
Can you add DSL.minus() or something else to define a negative computed value?
So I can write:
ctx.update(TABLE).set( FIELD2, DSL.minus(FIELD2) )

Regards

**Comment by lukaseder** [comment]
Thank you very much for your report. There's [`Field.neg()`](https://www.jooq.org/javadoc/latest/org/jooq/Field.html#neg--) that you can use. So, just write `FIELD2.neg()`

I just realised that this method doesn't exist on `DSL`, which would have made it more obvious to discover. I've created a separate feature request for this: #8412

**Comment by dantonini** [comment]
In this specific case, I find FIELD.neg() almost unreadable.
That's why DSL.neg(FIELD) could be useful.

Thanks for the quick response.

**Comment by lukaseder** [comment]
You could use Kotlin, where -FIELD translates to a call to `FIELD.unaryMinus()` :)
