### ISSUE TITLE
Rollback should not be called when TransactionListener.commitEnd() throws exception

### ISSUE THREAD

**Issue by johnlcox** [jOOQ/jOOQ#8413]
### Expected behavior and actual behavior:

I'm not entirely sure what the expected behavior would be, but the actual behavior is that if a `TransactionListener` throws an exception from `#commitEnd` the call to `TransactionProvider#rollback` throws a `NoSuchElementException`. This occurs because the transaction was already successfully commited so a rollback can't occur and the transaction provider is expecting an element in the configurations  `Deque`.

The `NoSuchElementException` is added to the suppressed exception list so the actual exception still bubbles up, but it is a bit weird. Even without the `NoSuchElementException` this presents a case where calls to `DSLContext#transactionResult` result in a `RuntimeException` but that a rollback did not occur; counter to the Javadoc 'indicating that a rollback has occurred.'

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

https://github.com/johnlcox/jOOQ-mcve/tree/NoSuchElementException

### Versions:

- jOOQ: 3.11.10
- Java: 8
- Database (include vendor): N/A
- OS: N/A
- JDBC Driver (include name if inofficial driver): N/A

**Comment by lukaseder** [comment]
Thanks a lot for the MCVE. I can reproduce the problem. Will investigate

**Comment by lukaseder** [comment]
The problem only appears in the `ThreadLocalTransactionProvider`, not the `DefaultTransactionProvider`

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.12. Backport scheduled for 3.11.11 (#8419) and 3.10.9 (#8420)
