### ISSUE TITLE
java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory

### ISSUE THREAD

**Issue by yuhwb** [jOOQ/jOOQ#8416]
### Expected behavior and actual behavior:
java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
### Versions:

- jOOQ:2.11.10
- Java:jdk10
- Database (include vendor):mysql
- OS:windows10
- JDBC Driver (include name if inofficial driver):com.mysql.jdbc.Driver

**Comment by lukaseder** [comment]
Thank you very much for your report. There had been numerous previous reports (and documented workarounds) for using jOOQ with JDK 9+ related to the removal of JAXB from the JDK. Please consider looking up those workarounds and see if any of them fit your case.

I'm happy to help you further with your particular case, but I would definitely need a bit more information on how you've reached this exception. Ideally, you would provide that MCVE that was suggested to be added by the issue tracker template.

Hope this helps
