### ISSUE TITLE
Unit Test Jooq conditions

### ISSUE THREAD

**Issue by mbayealioune** [jOOQ/jOOQ#8425]
### Your question:
Hi,

Is there any way to unit test a jooq Condition class ?
I build complex conditions based on various configurations.
I want to to mock something like :
- when this method is called, return this specific condition that I have created
And after I will assert it in my unit test by checking "and" and "or" conditions, for example if they are the same or they contain it...

I hope It was clear. I am a french speaker, sorry for bad english.

### Versions:

- jOOQ: 3.10  & 3.11
- Java: 8
- Database (include vendor):Postgres
- OS: Linux Centos
- JDBC Driver (include name if inofficial driver):postgresql-jdbc4

**Comment by lukaseder** [comment]
As of jOOQ 3.11, there is no direct way to introspect a jOOQ expression tree, as the data model is completely internal. You could of course use reflection as a workaround to access these internals, with all the risks associated with that appraoch.

A future jOOQ version will give access to a publicly available expression tree model, but we're not there yet.

What you could do already now is implement a [`VisitListener`](http://www.jooq.org/javadoc/latest/org/jooq/VisitListener.html) that is called whenever any given `QueryPart` is "visited" by the SQL renderer.

However, I'm curious to learn more about your use-case. I'm not quite sure what you're trying to achieve here. SQL is a complex language. A `Condition` can contain correlated subqueries and with those, almost the entirety of the SQL language, which should be rather difficult to unit test. Wouldn't integration tests be better suited to what you're trying to do here?

**Comment by mbayealioune** [comment]
Hey,
It's allready intégration tested.
I will look at the visitlistener and wait for future implementation with a tree model.

Thnx for the quick answer!

Envoyé de mon iPhone

**Comment by lukaseder** [comment]
Another thought: You can always write unit tests for calls to `toString()`, or perhaps a bit more predictably: `DSLContext.render(QueryPart)`...

**Comment by mbayealioune** [comment]
I thinked about the toString one, but I will definitely use the
DSLContext.render(QueryPart)
Thank you very much :)

Le lun. 18 mars 2019 à 09:38, Lukas Eder <notifications@github.com> a
écrit :
