### ISSUE TITLE
Add support for SQLite ON CONFLICT

### ISSUE THREAD

**Issue by angusholder** [jOOQ/jOOQ#8433]
### Use case:

Trying to call `.onConflict(...).doUpdate()` or `.onDuplicateKeyUpdate()` on a query using SQLite currently throws `SQLDialectNotSupportedException("The ON DUPLICATE KEY UPDATE clause cannot be emulated for SQLite")`.

### Possible solution you'd like to see:

As of 3.24 (2018-06-04) SQLite supports [upsert](https://www.sqlite.org/lang_UPSERT.html), and as far as I know, it follows Postgres' implementation to the letter, so I'm hoping that enabling support for it is just a matter of adding SQLite to the switch cases for the existing Postgres code paths, specifically in `InsertQueryImpl.accept0()` by the looks of it.

### Possible workarounds:

Checking if a row exists then using that to choose whether to issue insert or update.

### Versions:

- jOOQ: 3.11.9
- Java: 11
- Database (include vendor): SQLite 3.24
- OS: Raspbian
- JDBC Driver (include name if inofficial driver): Xerial SQLite

**Comment by lukaseder** [comment]
Thank you very much for pointing this out. Very cool, I missed out on this improvement. We'll add support in jOOQ 3.12
