### ISSUE TITLE
DSL.currentTimestamp() does not work with PostgreSQL

### ISSUE THREAD

**Issue by tfeiner** [jOOQ/jOOQ#8436]
### Expected behavior and actual behavior:

DSL.currentTimestamp() should generate "current_timestamp" in PostgreSQL, but it
generates "current_timestamp()", which leads to the following error in PostgreSQL:

      [42601] ERROR: syntax error at or near ")"

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

use DSL.currentTimestamp() in a query

### Versions:

- jOOQ: 3.11.9
- Java:  Adapt OpenJDK 1.8.0_202
- Database (include vendor): PostgreSQL 11.2
- OS: macOS Mojave 10.14.3
- JDBC Driver (include name if inofficial driver): PostgreSQL 42.2.2

**Comment by lukaseder** [comment]
jOOQ correctly generates `current_timestamp` - the literal, not `current_timestamp()` - the function, when you generate your SQL using the `SQLDialect.POSTGRES` dialect. Please check if you have correctly configured jOOQ to run with PostgreSQL.

**Comment by tfeiner** [comment]
Thanks, works for me, sorry for disturbing you.

**Comment by lukaseder** [comment]
No worries :)
