### ISSUE TITLE
Fix sqlite timestamp default value issue & Add datetime datatype 

### ISSUE THREAD

**Issue by brrinta** [jOOQ/jOOQ#8442]
### default value with timestamp/datetime 
if there are a column "default current_timestamp" it removed from the create field in case of sqlite while for mysql it work

### Currently datetime datatype converted to timestamp. So another datatype datetime can be added.
public static final DataType<LocalDateTime> DATETIME = new DefaultDataType<LocalDateTime>(null, LocalDateTime.class, "datetime");

**Comment by lukaseder** [comment]
Thank you very much for your request.

I'm afraid, I'm not really sure what seems to be the problem here. Would you mind describing it with a few more details? In particular, I'm not sure what you mean by the fact that the default expression is being removed.

Can you show a complete code example that illustrates the problem you're experiencing? Keep in mind that this example should help very clearly reproduce the problem.

**Comment by brrinta** [comment]
This is the create table statement:

CREATE TABLE example (
    id         INTEGER  PRIMARY KEY AUTOINCREMENT,
    name       TEXT,
    updateTime DATETIME DEFAULT CURRENT_TIMESTAMP 
);


This is what jooq generate 
`
public final TableField<ExampleRecord, LocalDateTime> UPDATETIME = createField("updateTime", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");
`
 there are no default value for the updatetime field


Full table code:
`
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Example extends TableImpl<ExampleRecord> {

    private static final long serialVersionUID = 200302369;

    /**
     * The reference instance of <code>example</code>
     */
    public static final Example EXAMPLE = new Example();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExampleRecord> getRecordType() {
        return ExampleRecord.class;
    }

    /**
     * The column <code>example.id</code>.
     */
    public final TableField<ExampleRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>example.name</code>.
     */
    public final TableField<ExampleRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>example.updateTime</code>.
     */
    public final TableField<ExampleRecord, LocalDateTime> UPDATETIME = createField("updateTime", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * Create a <code>example</code> table reference
     */
    public Example() {
        this(DSL.name("example"), null);
    }

    /**
     * Create an aliased <code>example</code> table reference
     */
    public Example(String alias) {
        this(DSL.name(alias), EXAMPLE);
    }

    /**
     * Create an aliased <code>example</code> table reference
     */
    public Example(Name alias) {
        this(alias, EXAMPLE);
    }

    private Example(Name alias, Table<ExampleRecord> aliased) {
        this(alias, aliased, null);
    }

    private Example(Name alias, Table<ExampleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Example(Table<O> child, ForeignKey<O, ExampleRecord> key) {
        super(child, key, EXAMPLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ExampleRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EXAMPLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ExampleRecord> getPrimaryKey() {
        return Keys.PK_EXAMPLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ExampleRecord>> getKeys() {
        return Arrays.<UniqueKey<ExampleRecord>>asList(Keys.PK_EXAMPLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Example as(String alias) {
        return new Example(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Example as(Name alias) {
        return new Example(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Example rename(String name) {
        return new Example(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Example rename(Name name) {
        return new Example(name, null);
    }
}
`

**Comment by lukaseder** [comment]
Thank you very much for your additional information. Unfortunately, I fail to be able to reproduce this. In my case, the `Example` table content does contain the default expression.

I think an MCVE would definitely help reproduce this: https://github.com/jOOQ/jOOQ-mcve

**Comment by lukaseder** [comment]
Tried again, still cannot reproduce this with jOOQ 3.14.0-SNAPSHOT.
