### ISSUE TITLE
sql  writing

### ISSUE THREAD

**Issue by tangheng666** [jOOQ/jOOQ#8448]
### Your question:

sql:  select 2 as  `type`   from t_supply_product;
sql Statement   is such that, Excuse me 2 as type  in JOOQ  How to express ?  

Thank you
### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your message. Your jOOQ statement can be written as follows:^

```java
// Assuming these static imports
import static com.example.generated.Tables.*;
import static org.jooq.impl.DSL.*;

DSLContext ctx = ...;
ctx.select(inline(2).as("type"))
   .from(T_SUPPLY_PRODUCT)
   .fetch();
```

Alternatively, instead of `DSL.inline()`, use `DSL.val()`. See also: https://www.jooq.org/doc/latest/manual/sql-building/bind-values

**Comment by tangheng666** [comment]
Thank you, thank you for your product.
