### ISSUE TITLE
Record implements value5(T5) in Record5; overridden method has no '...'

### ISSUE THREAD

**Issue by bkuberek** [jOOQ/jOOQ#8470]
### Your question:

Hi, I started getting this warning in my Maven build when I added a PostgreSQL ARRAY column to my model.

I am not sure what this means or how to fix it.

#### Table schema

```sql
CREATE TABLE "team_member" (
    "team_gid"   TEXT NOT NULL,
    "person_gid" TEXT NOT NULL,
    "is_owner"   BOOL NOT NULL DEFAULT FALSE,
    "is_member"  BOOL NOT NULL DEFAULT FALSE,
    "role"       TEXT[]        DEFAULT NULL,
    PRIMARY KEY ("team_gid", "person_gid")
)
    WITHOUT OIDS
```

#### JOOQ Generation Warning
```
[WARNING] /Users/bkuberek/Development/code/spotify/lexikon/lexikon-db/target/generated-sources/generated/com/spotify/lexikon/database/generated/tables/records/TeamMemberRecord.java:[295,28] value5(String...) in TeamMemberRecord implements value5(T5) in Record5; overridden method has no '...'
  where T5,T1,T2,T3,T4 are type-variables:
    T5 extends Object declared in interface Record5
    T1 extends Object declared in interface Record5
    T2 extends Object declared in interface Record5
    T3 extends Object declared in interface Record5
    T4 extends Object declared in interface Record5
```

#### Generated Record

On line 295

```java
    /**
     * {@inheritDoc}
     */
    @Override
    public TeamMemberRecord value5(String... value) {
        setRole(value);
        return this;
    }
```

### Versions:

- jOOQ: 3.11.10
- Java: "11.0.1" 2018-10-16 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.1+13-LTS) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.1+13-LTS, mixed mode)
- Database (include vendor): PostgreSQL 9.6.12
- OS: Mac OS X Mojave 10.14.3
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.5

**Comment by lukaseder** [comment]
Thank you very much for your request.

You can use `<varargSetters>false</varargSetters>` in your code generation configuration to turn off this behaviour.

See also: #5733

I hope this helps
