### ISSUE TITLE
Not able to generate DDL with Oracle Database

### ISSUE THREAD

**Issue by Neha1993** [jOOQ/jOOQ#8480]
Below is the code which I have tried with Postgres Database to generate DDL and it worked:

```java
DSLContext dSLContext = DSL.using(getPostgresqlDataSource().getConnection());
List<Table<?>> t =  dSLContext.meta().getTables("banks");
Queries ddl = dSLContext.ddl(t);
for (Query query : ddl.queries()) {
    System.out.println(query);
}

private static DataSource getPostgresqlDataSource() {
    DriverManagerDataSource dataSource = new DriverManagerDataSource();
    dataSource.setUrl(System.getenv("WORLD_JDBC_URL"));
    dataSource.setUsername(System.getenv("WORLD_JDBC_USERNAME"));
    dataSource.setPassword(System.getenv("WORLD_JDBC_PASSWORD"));
    return dataSource;
}

private static DataSource getOracleDataSource() throws SQLException {
    DriverManagerDataSource dataSource = new DriverManagerDataSource();
    dataSource.setUrl(System.getenv("WORLD_JDBC_URL"));
    dataSource.setUsername(System.getenv("WORLD_JDBC_USERNAME"));
    dataSource.setPassword(System.getenv("WORLD_JDBC_PASSWORD"));
    return dataSource;
}
```

But the same code did not work with Oracle database. Below is the output which I have got:

```sql
create table "DB"."CITIZEN"(
  "ENROLMENT_ID" other null,
  "NPR_OR_TIN" other null,
  "ADDHAAR_NO" other null,
  "FULL_NAME" other null,
  "GENDER" other null,
  "DATEOFBIRTH_OR_AGE" other null,
  "ADDRESS_LINE1" other null,
  "ADDRESS_LINE2" other null,
  "ADDRESS_LINE3" other null,
  "CITY" other null,
  "POST_OFFICE" other null,
  "DISTRICT" other null,
  "SUB_DISTRICT" other null,
  "STATE" other null,
  "PIN_CODE" other null,
  "EMAIL_ID" other null,
  "MOBILE_NO" other null,
  "FATHER_NAME" other null,
  "MOTHER_NAME" other null,
  "GUARDIAN_NAME" other null,
  "SPOUSE_NAME" other null,
  "INTRODUCER_AADHAAR_NO" other null,
  "DOCUMENTS_TYPE_NAME" other null
)
```

There is no datatype, min-max length, null/notnull/ constraint..

Below is the version which I have used:

```xml
<dependency>
	<groupId>org.jooq</groupId>
	<artifactId>jooq</artifactId>
	<version>3.11.10</version>
</dependency>
<dependency>
	<groupId>org.jooq</groupId>
	<artifactId>jooq-codegen</artifactId>
	<version>3.11.10</version>
</dependency>
<dependency>
	<groupId>org.jooq</groupId>
	<artifactId>jooq-meta</artifactId>
	<version>3.11.10</version>
</dependency>
```

**Comment by lukaseder** [comment]
Thank you very much for your report. You're using the jOOQ Open Source Edition for this (which does not support Oracle), instead of the jOOQ Professional Edition (which supports Oracle). Note the jOOQ Open Source Edition uses Maven `<groupId>org.jooq</groupId>`, whereas the jOOQ Professional Edition uses Maven `<groupId>org.jooq.pro</groupId>`.

Can you please retry with the jOOQ Professional Edition?

**Comment by Neha1993** [comment]
I have tried with trial professional Edition, below is the output which i have got:

create table "DB"."BANK_BRANCH"(
  "BANK_CODE" number(20) not null,
  "CODE" varchar2(20) not null,
  "NAME" varchar2(45) not null,
  "IFSC" varchar2(11) not null,
  "PHOTO" varchar2(250) null,
  "TYPE" varchar2(45) not null,
  "MICR" number not null,
  "ADDRESS_LINE1" varchar2(250) not null,
  "ADDRESS_LINE2" varchar2(250) not null,
  "ADDRESS_LINE3" varchar2(250) null,
  "POSTAL_CODE" number not null,
  "CITY" varchar2(45) not null,
  "STATE" varchar2(45) not null,
  "SERVICES" varchar2(90) not null,
  "GEO_LATITUDE" varchar2(20) null,
  "GEO_LONGITUDE" varchar2(20) null,
  "ATM_AT_BRANCH" varchar2(10) null,
  constraint "SYS_C0031033"
    primary key ("CODE")
)
comment on column "DB"."BANK_BRANCH"."BANK_CODE" is 'the bank code'
comment on column "DB"."BANK_BRANCH"."NAME" is 'the name of the bank'
comment on column "DB"."BANK_BRANCH"."IFSC" is 'The ifsc code of bank branch'
comment on column "DB"."BANK_BRANCH"."MICR" is 'The micr code of the bank'
comment on column "DB"."BANK_BRANCH"."CITY" is 'The city name where bank is located'
comment on column "DB"."BANK_BRANCH"."STATE" is 'The state namw where bank is located'



It took 8 minutes to generate DDL..

**Comment by lukaseder** [comment]
Thanks for your message. Yes indeed, there are known performance issues when querying the `org.jooq.Meta` API like you did: #3799. Behind the scenes, unfortunately, the entire database meta model is loaded eagerly prior to providing you with information about the table you've requested. This includes e.g. the `SYS` schema.

I've increased the priority of #3799 to fix this.
