### ISSUE TITLE
3.11 vs. 3.12 version mismatches between Constants.java and XSD files

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8484]
The not yet published jooq-codegen-3.12.xsd references the 3.11. namespace:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
  xmlns:tns="http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd"
  xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
  targetNamespace="http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd"
  elementFormDefault="qualified"
  jxb:version="2.1">
```
Similarly `Constants#XSD_META` is defined as "jooq-meta-3.11.0.xsd" rather than "jooq-meta-3.12.0.xsd". 

Finally `Constants#XSD_META` is defined as "3.11" rather than "3.12". 

Older releases are not affected.

**Comment by knutwannheden** [comment]
Also note that Constants.XSD_META is wrong (should be 3.12 rather than 3.11). Same goes for Constants.MINOR_VERSION. To be fixed in same issue / commit?

**Comment by lukaseder** [comment]
Nice catch. These issues did not seem to show up in any existing integration tests, at least not as failures, maybe as warnings. Will be good to have this covered with new tests.
