### ISSUE TITLE
Review callers of Tools#field(T) in AbstractField

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8500]
Make sure that all callers of `Tools#field(T)` in `AbstractField` are correct and shouldn't be using `Tools#field(Object, Field)` instead. This question came while working on #8429.

**Comment by lukaseder** [comment]
In the context of #11061, #11070, and #11091, I'm currently automating some API and implementation generation using our API generation tool chain, including relevant unit testing, making sure that these calls will be correct in the future. So, this will be fixed automatically as part of other work.
