### ISSUE TITLE
Add a parent pom.xml for all examples

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8507]
A lot of examples share some plugins / dependencies. Re-defining them in each example creates too much noise. We should have a parent pom.xml for these examples instead.

**Comment by knutwannheden** [comment]
I suppose we can add the parent `pom.xml` directly to the jOOQ-examples directory.

**Comment by lukaseder** [comment]
@knutwannheden Yes, that's what I had in mind. Then, a minor change to the top level `pom.xml` might be needed as well, or we remove the examples from the top level `pom.xml`

**Comment by lukaseder** [comment]
This was implemented and committed without reference to this issue:
https://github.com/jOOQ/jOOQ/commit/385887eb51860412e4b16c28856efc5e6bd05504#diff-7787c9133f44a36cd5eb2b69f3236035
