### ISSUE TITLE
Equals on fields not symmetric

### ISSUE THREAD

**Issue by scranen** [jOOQ/jOOQ#8509]
### Expected behavior and actual behavior:
**Context**
  I'm trying to work around #4477 by checking that `record.field(f)` equals `f`. 

**Expected behaviour**
  `record.field(f).equals(f)` yields the same result as `f.equals(record.field(f))`.

**Actual behaviour**
  it doesn't.

### Steps to reproduce the problem:
Generate code for the following table:
```sql
CREATE TABLE FOO (ID BIGINT);
```
The following comparison shows that `equals` is not symmetric:
```java
Field<Long> withSchema = DSL.field(DSL.name("PUBLIC", "FOO", "ID"), Long.class);
assertTrue(FOO.ID.equals(withSchema));
assertFalse(withSchema.equals(FOO.ID));
```

### Further information
I noticed the following when trying to work around this issue, but I'm uncertain if this is a bug or a design choice.

Note that `FOO.ID` is only ever equal to a field if it includes the qualifier `"PUBLIC"`:
```java
Field<Long> noSchema = DSL.field(DSL.name("FOO", "ID"), Long.class);
assertFalse(FOO.ID.equals(noSchema));
assertFalse(noSchema.equals(FOO.ID));
```
This is strange, because `FOO.ID.getQualifiedName()` does not include that qualifier. However, its `toString()` does:
```java
assertEquals(FOO.ID.toString(), "\"PUBLIC\".\"FOO\".\"ID\"");
assertEquals(FOO.ID.getQualifiedName(), DSL.name("FOO", "ID"));
```

### Versions:

- jOOQ: 3.11.9
- Java: 11
- Database (include vendor): Postgres 9
- OS: MacOS

**Comment by lukaseder** [comment]
Related issue: https://github.com/jOOQ/jOOQ/issues/10635

**Comment by lukaseder** [comment]
I think I may have just run into this while trying to fix a performance issue in `TableField::equals` implementations: #11126

**Comment by lukaseder** [comment]
I can reproduce this with 3.14.4 but not with 3.14.5-SNAPSHOT. I'm assuming that #11126 has fixed this already.
