### ISSUE TITLE
Update SQLite identifier list in DefaultRenderContext#SQLITE_KEYWORDS

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8511]
Comparing http://www.sqlite.org/lang_keywords.html with `DefaultRenderContext#SQLITE_KEYWORDS` there is a good dozen new keywords in SQLite, mostly related to windowing functions. These should be added so that `DefaultRenderContext#literal()` works correctly for corresponding identifiers.

**Comment by lukaseder** [comment]
You're right, nice catch
