### ISSUE TITLE
InsertOnConflictWhereStep#where() should return InsertOnConflictConditionStep

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8515]
INSERT's ON CONFLICT DO UPDATE's WHERE clause is implemented by `InsertOnConflictWhereStep`. There `where()` methods in here now return `InsertReturningStep` rather than the dedicated `InsertOnConflictConditionStep`.

**Comment by lukaseder** [comment]
It's interesting how long this has gone unnoticed :)

The `InsertOnConflictConditionStep` currently extends `InsertFinalStep`. It should indeed extend `InsertReturningStep`, which is the type returned by `where()`
