### ISSUE TITLE
Transform MySQL IN (SELECT .. LIMIT) to derived table

### ISSUE THREAD

**Issue by kjeet** [jOOQ/jOOQ#8521]
The following snippit generatews a SQL statement not supported in MySQL:
```
Query q = using(SQLDialect.MYSQL_5_7).deleteFrom(table("table1"))
    .where(field("table1_pk").in(
        select(field("table1_pk")).from(table("table1"))
             .where(field("col1").eq(inline(123)))
                 .limit(5).offset(10)
        ));
System.out.println(using(SQLDialect.MYSQL_5_7).renderInlined(q));
```
generates
```
delete from table1 where table1_pk in (select table1_pk from table1 where col1 = 123 limit 5 offset 10)
```
When run via mysql cli, throws
```
ERROR 1235 (42000): This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'
```

### Versions:

- jOOQ: 3.11.9
- Java: JDK11
- Database (include vendor): MySQL 5.7.25

**Comment by kjeet** [comment]
Googling around, something along the lines of
```
delete a from table1 a INNER JOIN (select table1_pk from table1 where col1 = 123 limit 5 offset 10) b ON a.table1_pk = b.table1_pk;
```
seems to work.

**Comment by lukaseder** [comment]
Very interesting, thanks for your report. jOOQ 3.12 will support `DELETE .. LIMIT` (see #714). You will be able to write a query like this:

```sql
delete from table1
where col1 = 123
limit 5
offset 10
```

However, we should definitely emulate your particular predicate as well, given that MySQL still cannot handle it. We'll emulate it via `EXISTS`

```sql
delete from table1 t1
where exists (
  select 1
  from table1 t2
  where t2.col1 = 123
  and t2.table1_pk = t1.table1_pk
  limit 5
  offset 10
)
```

As a workaround, you can manually write this `exists()` predicate yourself.

**Comment by lukaseder** [comment]
An even easier emulation for MySQL is to wrap the subquery in a derived table.

This query doesn't work:
https://www.db-fiddle.com/f/rvgqjk5Ws69v33kRqtVi7L/0

select *
from users u
where u.id in (
  select user_id
  from users_dishes
  limit 1
)
```

Causing the same error:

> Query Error: Error: ER_NOT_SUPPORTED_YET: This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'

But this one does:
https://www.db-fiddle.com/f/7Xkvq7no15Mkq9mVdMc3fy/0

```sql
select *
from users u
where u.id in (
  select *
  from (
    select user_id
    from users_dishes
    limit 1
  ) t
)
```

**Comment by lukaseder** [comment]
We've already worked around a similar limitation of MySQL when using self-references of a table from correlated subqueries in DML statements (see #6583). In fact, you have such a self-reference in your example `DELETE` statement, which means it would still not work if we had transformed it to `EXISTS()`.

**Comment by lukaseder** [comment]
This limitation also affects the row value expression `in` predicate, e.g. this doesn't work:

```sql
select *
from users u
where (u.id, 1) in (
  select user_id, 1
  from users_dishes
  limit 1
)
```

This does:

```sql
select *
from users u
where (u.id, 1) in (
  select *
  from (
    select user_id, 1
    from users_dishes
    limit 1
  ) t
)
```

**Comment by lukaseder** [comment]
It works with equality:

```sql
select *
from users u
where u.id = (
    select user_id
    from users_dishes
    limit 1
)
```

**Comment by lukaseder** [comment]
A possible fix could depend on #3497 *"Add methods to Context to distinguish between derived tables and other types of subqueries"*. We have to generate a specific kind of correlated subquery only in case we're inside some specific case, not in other cases.

**Comment by lukaseder** [comment]
(Curiously, the rationale for #3497 is quite similar, for Informix, not MySQL)

**Comment by lukaseder** [comment]
Finally fixing this in jOOQ 3.15.0 as a new configurable SQL transformation, see https://github.com/jOOQ/jOOQ/issues/9767

**Comment by lukaseder** [comment]
Doing this also for MemSQL: https://github.com/jOOQ/jOOQ/issues/14717
