### ISSUE TITLE
Emulate the PL/SQL BOOLEAN type in SQL functions in Oracle 12c

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8522]
With #365, jOOQ supports the PL/SQL BOOLEAN type in standalone stored procedure and function calls by translating `1/0/NULL` to `TRUE/FALSE/NULL` in an anonymous PL/SQL block. The same trick is in fact also possible when using the `WITH` clause to define a bridge function that bridges between numbers and booleans.

Consider this function:

```sql
CREATE OR REPLACE FUNCTION f_bool (p BOOLEAN DEFAULT TRUE) RETURN VARCHAR2 IS
BEGIN
  RETURN CASE 
    WHEN p THEN 'TRUE'
    WHEN NOT p THEN 'FALSE'
    ELSE 'NULL'
  END;
END f_bool;
/
```

First off, if the function has a default value for the boolean parameter, and the user does not supply a value for that parameter, then we can call it as follows:

```sql
SELECT f_bool FROM dual;
```

If, however, the user wants to pass a value to the parameter, then a working emulation is this:

```sql
WITH
  FUNCTION f_bool_ (i NUMBER) RETURN VARCHAR2 IS
  BEGIN
    RETURN f_bool(NOT i = 0);
  END f_bool_;
SELECT f_bool_(1) FROM dual;
```

jOOQ should generate that synthetic bridge method and translate between `NUMBER` and `BOOLEAN` transparently for the user.

**Comment by lukaseder** [comment]
If the function returns a `BOOLEAN`, and we're not passing that `BOOLEAN` to another function (in case of which no translation is needed), then we have to translate the `BOOLEAN` back to a number in the auxiliary function:

```sql
WITH
  FUNCTION f_bool__ (i NUMBER) RETURN NUMBER IS
    r BOOLEAN;
  BEGIN
    r := pls_objects.f_bool(CASE 
      WHEN i = 1 THEN TRUE
      WHEN i = 0 THEN FALSE
      ELSE NULL
    END);
    
    RETURN CASE WHEN r THEN 1 WHEN NOT r THEN 0 ELSE NULL END;
  END f_bool__;
SELECT f_bool__(1) FROM dual;
/
```

**Comment by lukaseder** [comment]
> and we're not passing that BOOLEAN to another function (in case of which no translation is needed)

In fact, the SQL engine cannot handle such intermediary `BOOLEAN` values. We have to wrap all the calls

**Comment by lukaseder** [comment]
Seems like nesting `with function` in a correlated subquery isn't possible, which would be the easiest way to implement this:

```sql
-- Doesn't work
select (
  with 
    function f return number is
    begin 
      return 1; 
    end f; 
  select f 
  from dual
) from dual;
```

Without such a local auxiliary function, we will have to emit a CTE to the top level select: #3607, which is a very useful feature per se, but not trivial to implement. In other words, whenever the renderer encounters a PL/SQL boolean function argument or return value, it should render the auxiliary call instead of itself, and notify some hypothetical CTE collector of the presence of the auxiliary function declaration(s).

So, this feature depends on #3607

**Comment by lukaseder** [comment]
In the presence of other CTE, the function must be prepended:

```sql
with   
  function f return number is
  begin 
    return 1; 
  end f; 
  x(a) as (select 1 from dual)
select f(), a
from x;
```

**Comment by lukaseder** [comment]
The function call may also originate from within another CTE:

```sql
with   
  function f return number is
  begin 
    return 1; 
  end f; 
  x(a) as (select f() from dual)
select a
from x;
```

**Comment by lukaseder** [comment]
Supporting these in DML statement may not be possible...

**Comment by lukaseder** [comment]
A first working draft is implemented:
https://twitter.com/lukaseder/status/1117160235846840320

Will fix edge cases and clean up and check in on Monday. This feature will definitely ship for jOOQ 3.12!

**Comment by knutwannheden** [comment]
Would an alternative to wrapping the methods be to have dedicated conversion functions and apply those to the parameters and return value? The only advantages I see with that is that the conversion functions could be declared as `DETERMINISTIC` (probably mostly irrelevant) and the PL/SQL call stacks (e.g. when logging errors) wouldn't include the synthetic wrapper.

Also, can `CASE WHEN i = 1 THEN TRUE WHEN i = 0 THEN FALSE ELSE NULL END` be condensed to `i = 1`?

**Comment by lukaseder** [comment]
> @knutwannheden Would an alternative to wrapping the methods [...]

There are a variety of jOOQ emulations that would profit from the generation of synthetic schema level objects, this being one of them. There's a pending feature request to add support for a `SystemConnectionProvider`, which provides jOOQ with a "system" connection on which we can create such auxiliary types and objects: #8194 

Without such an API, it would be unwise to start creating such objects. We could, of course, document the required objects and rely on users setting them up for us, and then configuring jOOQ with their real world names and qualifiers, but that is not very user friendly.

So, right now, a lot of these emulations simply work through generating inline, anonymous PL/SQL either in a `BEGIN .. END` block, or with this issue also in `WITH` clauses of SQL statements.

> Also, can CASE WHEN i = 1 THEN TRUE WHEN i = 0 THEN FALSE ELSE NULL END be condensed to i = 1? Only difference would be that result would also be FALSE for all other numbers than 0 (like 2).

Yes, indeed. Or rather, when `NOT i = 0`, as that would make `0` the same as `false`, all the other numbers `true`, and `null` stays `null`

**Comment by lukaseder** [comment]
I'll fix all my comments to use `NOT i = 0` or equivalent.

**Comment by lukaseder** [comment]
A first implementation draft has been added. The following things need to be integration tested, still:

- [ ] Combining boolean functions with CTE (the emulation functions must syntactically precede the CTE, see https://github.com/jOOQ/jOOQ/issues/8522#issuecomment-482841978)
- [ ] Multiple distinct boolean function calls
- [ ] Chained boolean function calls
- [ ] Conflicts when people use the data type rewriting feature on functions
- [ ] Boolean functions in DML
- [ ] Benchmark the current scope stack solution

**Comment by lukaseder** [comment]
Thanks, @knutwannheden for adding the forgotten files

**Comment by lukaseder** [comment]
Remaining tasks have been moved to 3.13 via #8930. This feature works in 3.12 for many out of the box cases, and as such, the feature request will be closed
