### ISSUE TITLE
MiniJAXB#append() doesn't work for enum types

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8527]
Calling `MiniJAXB#append()` for two non-`null` enums will currently fail with a `ReflectException` because the method attempts to invoke the class default constructor, which will fail for enum types: 

https://github.com/jOOQ/jOOQ/blob/1673a1b971345720a86e7b4f3319e84fabc98363/jOOQ/src/main/java/org/jooq/conf/MiniJAXB.java#L375

Since the JAXB models also defines Java enums, this use case should also be supported.

**Comment by knutwannheden** [comment]
An example for a test which currently fails:

```java
        assertEquals(
            new Settings().withRenderQuotedNames(RenderQuotedNames.ALWAYS),
            MiniJAXB.append(
                new Settings().withRenderQuotedNames(RenderQuotedNames.ALWAYS),
                new Settings().withRenderQuotedNames(RenderQuotedNames.ALWAYS)
            )
        );
```

**Comment by lukaseder** [comment]
Interesting, nice catch. The existing integration tests seem not to cover this case.

What would be the retained value in case the two enums were different? I'd say, the second value, as the second value also overrides the first one in case a setter is called.

**Comment by knutwannheden** [comment]
AFAICT the logic in `MiniJAXB#append()` will currently retain the first value (see last return of method).

**Comment by knutwannheden** [comment]
Another interesting use case is when the object has a property of a type like java.lang.Boolean which isn't declared in the same package as the JAXB types. In that case append() will do nothing, which also translates to keeping the property value of the first object.

**Comment by lukaseder** [comment]
> AFAICT the logic in MiniJAXB#append() will currently retain the first value (see last return of method).

You're right. This is because of the check where the first child must either be null or equal to the default, only then the second child is set on the setter:

https://github.com/jOOQ/jOOQ/blob/1673a1b971345720a86e7b4f3319e84fabc98363/jOOQ/src/main/java/org/jooq/conf/MiniJAXB.java#L395-L396

I remembered wrong, then. The rationale lies in how Maven merges XML trees by default, I think. I hadn't implemented all the different Maven configurations of merging trees.

> Do you think that return is wrong?

I recall now that this seemed to me to be the most reasonable default behaviour in the Maven context. If someone declares something with Maven, that would override anything that has been declared in an external configuration file, as the Maven config is "more local". So, I don't think it is wrong, currently.

In any case, the enum merging must behave like the rest.

> Another interesting use case is when the object has a property of a type like java.lang.Boolean which isn't declared in the same package as the JAXB types. In that case append() will do nothing, which also translates to keeping the property value of the first object.

That would be consistent, then, and I think that's exactly how I thought about this functionality, when I implemented it.

Notice that `MiniJAXB` doesn't aim for implementing a generally reusable way of merging JAXB annotated trees. It focuses on how jOOQ works with XJC generated code, as a minimalist solution to make JAXB an optional dependency, see #7734.

**Comment by knutwannheden** [comment]
I read the Maven documentation regarding "append" (see https://maven.apache.org/pom.html). There is is stated that the concatenation is not recursive (as in `MiniJAXB#append()`). Also, I get the impression that Maven's "append" behavior is only specified for multi-valued properties, so it isn't quite clear to me what `append()` should do with e.g. Integer typed properties. I will have to read the jOOQ documentation on this.

**Comment by knutwannheden** [comment]
>> Another interesting use case is when the object has a property of a type like java.lang.Boolean which isn't declared in the same package as the JAXB types. In that case append() will do nothing, which also translates to keeping the property value of the first object.

> That would be consistent, then, and I think that's exactly how I thought about this functionality, when I implemented it.

Just to be clear: Does that mean that properties like for example `Settings#fetchServerOutputSize` cannot be overridden?

**Comment by knutwannheden** [comment]
Looking at the code and the test cases I think the logic is now mostly clear. I have created a new test case and modified the code of `append()` so that it should work as expected for enums now as well.

**Comment by lukaseder** [comment]
> I read the Maven documentation regarding "append" (see https://maven.apache.org/pom.html). There is is stated that the concatenation is not recursive (as in MiniJAXB#append())

I think there's some confusion about naming. The default in Maven is "merge":

```xml
<!-- combine.children="merge" is the default -->
```

Perhaps the `MiniJAXB.append()` method should be renamed to `merge()`

> Just to be clear: Does that mean that properties like for example Settings#fetchServerOutputSize cannot be overridden?

That depends on your definition of "overridden". An external configuration file cannot override the inline Maven plugin configuration. But the inline Maven plugin configuration can override the external configuration file. The question is which way around you want to define "overriding".

The way I understand Maven, "external" configuration is for example `<pluginManagement>`, and "local" configuration is for example `<plugin>`. The latter should override the former, not the other way round.

**Comment by knutwannheden** [comment]
AFAICT a property like `Settings#fetchServerOutputSize` can currently not be overridden given the current implementation of `MiniJAXB#append()`. I suppose we could change the implementation and also rename the method to `merge()` (as you suggest), but we should probably handle that in a separate issue 😃 .

**Comment by lukaseder** [comment]
> I suppose we could change the implementation

I'll be happy to review a code example. I'm not quite sure how it's not possible.

> and also rename the method to merge() (as you suggest)

Yes

> but we should probably handle that in a separate issue 😃 .

Yes! :-)

**Comment by knutwannheden** [comment]
You are of course right. Given the parameter order to `append()` the effect will be that of an override. I was just confused about the comment in the unit test: `// Don't override scalar values on the left side`.
