### ISSUE TITLE
Add configuration option to anonymize exception messages

### ISSUE THREAD

**Issue by yissachar** [jOOQ/jOOQ#8534]
### Use case:

When JOOQ encounters a SQL error it will throw an exception with the information about what went wrong. This contains lots of useful information but can also contain sensitive information. In our use case we would like to log the exception directly but since many values in our database contain private information we cannot.

### Possible solution you'd like to see:

The ideal solution for us would involve specifying which database columns are sensitive, and a function to anonymize the column (in many cases this would simply be e.g. a function that returns `[REDACTED]`, but we have situations where we would like to hash the value so that we can correlate them). However, partial solutions would still be useful (i.e. a simple boolean flag that specifies whether to include raw database values or not in the  exception message).

### Possible workarounds:

Instead of logging the exception as is,  we try to extract some safe info from the exception and just log those bits and pieces but this is not as useful as the full exception message.

### Versions:

- jOOQ: 3.11.11

**Comment by lukaseder** [comment]
Thank you very much for your message. It is difficult to foresee what precise limitations and requirements you may have for a very generic, framework based solution here. Why not instead implement an `ExecuteListener` and intercept all exceptions yourself, by implementing `ExecuteListener.exception(ExecuteContext)`?

See
http://www.jooq.org/javadoc/latest/org/jooq/ExecuteListener.html

Of course, there might be a low hanging fruit somewhere, but I would need much more thorough requirements to assess whether we can do something useful and not too complicated in this area.

**Comment by yissachar** [comment]
This is basically what we're doing at the moment, but there is not enough information compared to the raw log that we get from JOOQ.

For instance when we we execute a SELECT statement and one of the relations doesn't exist there are a few pieces of information available to use from the ExecuteListener:

1. The raw message: `ERROR: relation "foo.bar" does not exist\n Position 72`
2. The SQL state: `42P01`
3. The select statement

In this case the raw message would be perfect for us, but we don't have any way of knowing that. The select statement is also safe in this case but we also don't know that. The only thing that is guaranteed to be safe is the SQL state, so we log that and it would give us enough information to know that relation doesn't exist, but not enough information to know which one doesn't exist.

And we can't log the raw message because in many cases it can contain private data, for instance a unique conflict logs the insert statement as well as the value that is not unique:

```Batch entry 1 insert into "foo"."bar" ("baz", "tar") values ('sensitive', 'notsensitive') was aborted: ERROR: duplicate key value violates unique constraint "my_pkey"
  Detail: Key (baz, tar)=(sensitive, notsensitive) already exists.  Call getNextException to see other errors in the batch.```

I was assuming that JOOQ had more information available about the exception, but after thinking about I realize you're just passing on the error received from the database as a String so I guess there's not much you can do generically.

I think we'll just have to go over the list of [SQL error codes](https://www.postgresql.org/docs/9.6/errcodes-appendix.html) and determine which can't contain actual data and whitelist those to log the full data and for the rest just log the SQL state.

Thanks

**Comment by lukaseder** [comment]
> I was assuming that JOOQ had more information available about the exception, but after thinking about I realize you're just passing on the error received from the database as a String so I guess there's not much you can do generically.

Indeed, I don't think there's much we can do here. Offering such an SPI would be quite difficult and brittle, as many RDBMS keep changing their "stringly typed" error messages all the time. Even relying on SQL error codes is brittle as soon as you have to support more than one vendor / dialect.
