### ISSUE TITLE
Use MySQL's native derived column lists support

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8541]
AFAICT it looks like MySQL natively supports derived column lists as of version 8.0.1: https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-sql-syntax. A quick test with db-fiddle seems to confirm this. jOOQ currently emulates it for MySQL 8.0.

Unusure about support in current Aurora MySQL and MariaDB.

**Comment by lukaseder** [comment]
You're right. We should support this feature from MySQL 8.0 onwards. Notice that MySQL supports derived column lists for derived tables, but not for arbitrary table references, just like SQL Server.

This works:

```sql
SELECT *
FROM (SELECT 1 a) t(x);
```

But this doesn't

```sql
SELECT *
FROM a AS t(x);
```

jOOQ already has proper emulations for these things.

I'm currently not able to find the Aurora SQL syntax reference. They had one in the past, but I cannot see it right now. If in doubt, we can leave things as they are for Aurora, as the emulation always works.

MariaDB currently doesn't support the syntax yet:
https://mariadb.com/kb/en/library/join-syntax

**Comment by lukaseder** [comment]
I've implemented this only for MySQL
