### ISSUE TITLE
Add support for CockroachDB

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8545]
They now have a version on docker:
https://hub.docker.com/r/cockroachdb/cockroach/

And the core distribution is free:
https://www.cockroachlabs.com/pricing/

**Comment by lukaseder** [comment]
Currently known limitations of CockroachDB:

- [ ] No user defined schema support: https://github.com/cockroachdb/cockroach/issues/26443. This seems to be worked on. We'll add support for this when ready.

**Comment by geekyme** [comment]
Hi @lukaseder, if the core distribution of CockroachDB is free, why does JOOQ require a paid license for this? Seems like CockroachDB's business model is similar to MariaDB - https://mariadb.com/pricing/, and MariaDB is offered under JOOQ's free distribution.

**Comment by lukaseder** [comment]
Thank you very much for your message, @geekyme.

Indeed, the way MariaDB presents itself has changed over the past years. At first, it marketed itself as "the old MySQL", the one that was truly open source. Which is why it got adopted quickly by a few linux distributions as a replacement for MySQL. Today, the distinction is no longer clear. SkySQL follows a more credible business model than just being "the old MySQL", and indeed, they present themselves in a similar way as CockroachDB.

Our distinction between what is a dialect for the Open Source Edition, and what is a dialect for the commercial distributions is not an exact science. There are clear candidates for both editions, such as:

- Db2, Oracle, SQL Server, etc, being clearly commercial only
- Derby, H2, HSQLDB, PostgreSQL, SQLite, and in my opinion still MySQL, being clearly mainly open source (despite some commercial offerings)

And then, there are many dialects like CockroachDB that offer a free core. Our opinion here is that a free core is not enough to qualify as a truly open source database in terms of our own licensing. The question is: How does the brand market itself. How is it best used in production. And CockroachDB clearly markets itself as a commercial database.

As I said, MariaDB didn't, originally, but does today. We might re-consider re-licensing the MariaDB drivers eventually, or create several MariaDB drivers, the existing one for the Open Source Edition and a new one for commercial offerings, such as #7519 / https://mariadb.com/resources/blog/mariadb-tx-3-0-first-to-deliver-on-the-promise-of-enterprise-open-source.

We haven't decided yet. I hope this helps.
