### ISSUE TITLE
Add support for SQLite window function extensions from version 3.28

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8548]
SQLite 3.28 has added support for new window function features:
https://www.sqlite.org/changes.html#version_3_28_0

This includes:

- [x] `GROUPS` clause
- [x] `EXCLUDE` clause
- [x] Window chaining (not supported yet for 3.25: #8279)
- [x] Short form of the range clause (e.g. `<number> PRECEDING`)

----
See:
https://www.sqlite.org/changes.html#version_3_28_0

**Comment by lukaseder** [comment]
Window chaining support requires the publication of the latest xerial version

**Comment by katzyn** [comment]
@lukaseder
You also fixed some support annotations in `WindowExcludeStep` here, but `excludeNoOthers()` is still incomplete:
https://github.com/jOOQ/jOOQ/blob/fa9422521fb7d454c1651791a47b51f2c6e94756/jOOQ/src/main/java/org/jooq/WindowExcludeStep.java#L91-L98
`SQLITE` was already here, but It should include `H2` too.

**Comment by lukaseder** [comment]
@katzyn Nice catch, thanks!

**Comment by lukaseder** [comment]
`org.xerial:sqlite-jdbc:3.30.1` is now available
