### ISSUE TITLE
Improve documentation regarding nullable forced types

### ISSUE THREAD

**Issue by yaseenkadir** [jOOQ/jOOQ#8554]
Sorry not sure this actually qualifies as a bug ticket, please let me know if I should delete/move it somewhere else.

Documentation around forced types handling null types are not quite clear.

For example on this page, there is no mention of the `<nullability>` XML field https://www.jooq.org/doc/3.11/manual/code-generation/custom-data-types/.
```xml
<database>

  <!-- Then, associate custom types with database columns -->
  <forcedTypes>
    <forcedType>
    
      <!-- Specify the Java type of your custom type. This corresponds to the Converter's <U> type. -->
      <userType>java.util.GregorianCalendar</userType>

      <!-- Associate that custom type with your converter. -->
      <converter>com.example.CalendarConverter</converter>
      
      <!-- Add a Java regular expression matching fully-qualified columns. Use the pipe to separate several expressions.
           
           If provided, both "expressions" and "types" must match. -->
      <expression>.*\.DATE_OF_.*</expression>
      
      <!-- Add a Java regular expression matching data types to be forced to
           have this type.
      
           Data types may be reported by your database as:
           - NUMBER              regexp suggestion: NUMBER
           - NUMBER(5)           regexp suggestion: NUMBER\(5\)
           - NUMBER(5, 2)        regexp suggestion: NUMBER\(5,\s*2\)
           - any other form
           
           It is thus recommended to use defensive regexes for types.
           
           If provided, both "expressions" and "types" must match. -->
      <types>.*</types>
    </forcedType>
  </forcedTypes>
</database>
```

It is mentioned on this page here though. https://www.jooq.org/doc/3.11/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/

```xml
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.11.0.xsd">
  <generator>
    <database>
      <!-- The first matching forcedType will be applied to the data type definition. -->
      <forcedTypes>
        <forcedType>

          <!-- Specify any data type that is supported in your database, or if unsupported, a type from org.jooq.impl.SQLDataType -->
          <name>BOOLEAN</name>

          <!-- Add a Java regular expression matching fully-qualified columns. Use the pipe to separate several expressions.
               If provided, both "expressions" and "types" must match. -->
          <expression>.*\.IS_VALID</expression>
          
          <!-- Add a Java regular expression matching data types to be forced to have this type.

               Data types may be reported by your database as:
               - NUMBER              regexp suggestion: NUMBER
               - NUMBER(5)           regexp suggestion: NUMBER\(5\)
               - NUMBER(5, 2)        regexp suggestion: NUMBER\(5,\s*2\)
               - any other form.

               It is thus recommended to use defensive regexes for types.

               If provided, both "expressions" and "types" must match. -->
          <types>.*</types>
          
          <!-- Force a type on ALL / NULL (nullable) / NOT_NULL (non-nullable) types -->
          <nullability>ALL</nullability>
        </forcedType>
      </forcedTypes>
    </database>
  </generator>
</configuration>
```

> Force a type on ALL / NULL (nullable) / NOT_NULL (non-nullable) types

Adding the `<nullability>` tag to the documentation for that first page I linked would be nice. But I'd also like to suggest improving the description surrounding the `<nullability>` tag. 

Perhaps

```xml
<!-- Force a type depending on data type nullability. Field is optional, will default to ALL.
- ALL - force type regardless of whether data type is nullable or not
- NULL - force type only when data type is nullable
- NOT_NULL - force type only when data type is not null
-->
<nullability>ALL</nullability>
```

**Comment by lukaseder** [comment]
Thank you very much for your thorough report

> Sorry not sure this actually qualifies as a bug ticket, please let me know if I should delete/move it somewhere else.

Don't worry, we'd move it for you in case this applies.

> Adding the `<nullability>` tag to the documentation for that first page I linked would be nice.

Hmm, we should have one page that documents all flags in detail, and the other ones that simply list the flags and refer to the first page for details. Not all flags are relevant on each page.

> But I'd also like to suggest improving the description surrounding the `<nullability>` tag.

I agree that's a better description.

**Comment by lukaseder** [comment]
>> But I'd also like to suggest improving the description surrounding the `<nullability>` tag.
>
> I agree that's a better description.

This has been fixed and will be updated soon. The remaining parts take more thought. Will do later.

**Comment by lukaseder** [comment]
An additional improvement that doesn't require restructuring everything is to link to the `<forcedTypes/>` section here: https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-forced-types/, whenever forced types are mentioned

**Comment by yaseenkadir** [comment]
Thanks so much Lukas!
