### ISSUE TITLE
Support GROUP BY ROLLUP on SQL Data Warehouse

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8556]
According to the release notes (see https://docs.microsoft.com/en-us/azure/sql-data-warehouse/release-notes-10-0-10106-0#march-2019) SQL Data Warehouse supports GROUP BY ROLLUP as of March 2019. This appears to be missing in the `DSL#rollup()` annotations.

**Comment by lukaseder** [comment]
Indeed, nice catch. This is what the `GROUP BY` manual page now references:

![image](https://user-images.githubusercontent.com/734593/56562932-de4dd800-65aa-11e9-8041-19e569909d01.png)

See: https://docs.microsoft.com/en-us/sql/t-sql/queries/select-group-by-transact-sql?view=azure-sqldw-latest

**Comment by lukaseder** [comment]
This just boils down to adding the dialect to the relevant `@Support` annotation, as the syntax is the same as for SQL Server:

![image](https://user-images.githubusercontent.com/734593/56563032-11906700-65ab-11e9-9d0b-aea9aecc67d3.png)

**Comment by knutwannheden** [comment]
Should we create a separate issue for the `WITH DISTRIBUTED_AGG` query hint clause?

**Comment by lukaseder** [comment]
> Should we create a separate issue for the WITH DISTRIBUTED_AGG query hint clause?

I prefer not to support that particular hint explicitly. There are a variety of T-SQL style hints, e.g. join hints: #5694 and other `WITH` clauses that could be supported without knowledge of tokens like `DISTRIBUTED_AGG`. For example, we already support [`Table.with(String)`](https://www.jooq.org/javadoc/latest/org/jooq/Table.html#with-java.lang.String-) without knowing anything about the specific hints that are possible in SQL Server.

So, I think we don't need a separate issue right now for this SQL Datawarehouse syntax.
