### ISSUE TITLE
Support spring-data-jdbc @Column

### ISSUE THREAD

**Issue by cn-src** [jOOQ/jOOQ#8559]
### Use case:

Support `org.springframework.data.relational.core.mapping.Column` mapping pojo.

### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I'm assuming you mean for this annotation to be supported by the  `DefaultRecordMapper`.

There are a variety of third party tools that offer handy annotations that could be interpreted in a similar way as JPA's `@Column` annotation.

At this point, I would not like to invest too much into supporting all of these, given that we have a very simple backdoor where the `DefaultRecordMapper` can be replaced: A `RecordMapperProvider`:
https://www.jooq.org/doc/latest/manual/sql-execution/fetching/pojos-with-recordmapper-provider

Maybe, if this kind of idea gets enough traction, we can review it in a future version.

**Comment by lukaseder** [comment]
We'll consider this in a more generic context, when abstracting the dependency on JPA: #8599
