### ISSUE TITLE
Provide API interface to indicate whether context is transactional

### ISSUE THREAD

**Issue by sinaa** [jOOQ/jOOQ#8564]
### Use case:

In certain situations, a user may want to know whether or not the context they're using (perhaps one that is passed down to a method) is on a transactional context (e.g., to ensure/assert that context is transactional).

### Possible solution you'd like to see:

Based on the `toString()` implementation of `DefaultConfiguration`, this should be simple as adding a new method like below:

```java
public boolean isTransactional(){
  return transactionProvider != null && !(transactionProvider instanceof NoTransactionProvider);
}
```

Another solution would be to provide a getter for the current value of transactionProvider (regardless of whether or not it is an instance of NoTransactionProvider). While there already is a method `transactionProvider()` in the `DefaultConfiguration` class, it tries to go out of its way to return a DefaultTransactionProvider if the current transactionProvider is `NoTransactionProvider`. So there seems to be no public getter for the current value of `transactionProvider`.

### Possible workarounds:

One workaround seems to be around looking for certain magic keys in the context.configuration().data() that otherwise don't exist when not in a transactional context. (e.g., `DATA_DEFAULT_TRANSACTION_PROVIDER_AUTOCOMMIT`, but I'm not sure if this is a reliable indicator).

Another ugly workaround seems to be to match the `toString()` of a `context.configuration()` against `transactional=true`.

### Versions:

- jOOQ: 3.11.9
- Java: 11
- Database (include vendor): Postgres

**Comment by lukaseder** [comment]
Thank you very much for your request. I agree that this could be a useful thing to know.

Regarding your suggestions:

> Another solution would be to provide a getter for the current value of transactionProvider (regardless of whether or not it is an instance of NoTransactionProvider)

I'd like to avoid such a getter as it would lead to confusion. The existing getter must return a reasonable default implementation in the absence of a user provided implementation to work out of the box when calling `DSLContext.transaction()` and similar methods.

However, it might be possible to get public access to the `TransactionContext` that a `TransactionProvider` would see. Or at least to a read only view of it. That ` TransactionContext` could have additional methods including whether we're in a jOOQ managed transaction, the nesting level, etc. 

Such a feature could integrate with future improvements that include read only transactions and transaction isolation levels (#4836)

> One workaround seems to be around looking for certain magic keys in the context.configuration().data() that otherwise don't exist when not in a transactional context. (e.g., DATA_DEFAULT_TRANSACTION_PROVIDER_AUTOCOMMIT, but I'm not sure if this is a reliable indicator).

This is definitely not reliable when upgrading jOOQ, although it may work for you as long as you stay on any given jOOQ version. But these `DATA_` keys are internal utilities and as such, not documented nor supported.

> Another ugly workaround seems to be to match the toString() of a context.configuration() against transactional=true

Indeed, even less reliable :)

**Comment by sinaa** [comment]
@lukaseder I appreciate that there are many competing features to be developed, and that this issue may not be high priority. So I wanted to ask if you have a preferred suggestion to be used in the meantime?

Like you said, neither the `DATA_` attribute keys and the `toString()` are reliable indicators to rely on. So, is there an alternative you'd recommend (at least until this is properly implemented)?

**Comment by lukaseder** [comment]
> Like you said, neither the DATA_ attribute keys and the toString() are reliable indicators to rely on. So, is there an alternative you'd recommend (at least until this is properly implemented)?

Well, as a workaround, you *could* rely on this, guarding your assumptions via a set of integration tests. I'm not aware of any urgent tasks in the transaction API area that would precede this (without guarantee, of course), so such a workaround might be stable enough for 1-2 years.

**Comment by lukaseder** [comment]
Revisiting this. I'm not really a fan of exposing this information in any way, mainly because it will only work with the `DefaultTransactionProvider` implementation, not e.g. with Spring, or when someone uses plain JDBC transactions.

A simple workaround could be to use a `TransactionListener` and manage this information in a user-controlled way. Alternatively, using `ctx.connectionResult(c -> c.getAutoCommit())` would give access to the JDBC transaction state. Both workarounds can be based on the assumption that jOOQ transactions are used (which are translated to JDBC transactions).

With these workarounds, I prefer rejecting adding any additional API in this area.
