### ISSUE TITLE
DAO.update() fail to update row on a table with composite primary key which contains a DATETIME field

### ISSUE THREAD

**Issue by guytavor** [jOOQ/jOOQ#8566]
Consider the following table
```
CREATE TABLE `test_table` (
  `id` int(11) NOT NULL,
  `id2` datetime NOT NULL,
  `value` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`,`id2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

The following test case fails:
```java
 private static Configuration configuration;
  private static Connection connection = null;


  @Test
  public void test() throws SQLException {
    connection = DriverManager.getConnection(InstallationConfiguration.getDbUrl());
    configuration = new DefaultConfiguration().set(connection).set(SQLDialect.MYSQL);

    TestTable pojo = new TestTable(1, new Timestamp(1), "hello");
    final TestTableDao dao = new TestTableDao(configuration);
    dao.insert(pojo);

    TestTable record2 = new TestTable(1, new Timestamp(1), "world");

    new TestTableDao(configuration).update(record2);

    assertEquals("world", dao.findAll().get(0).getValue());
  }
```

However - if the field is defined BIGINT(21), the test passes.

MySQL 5.7.21 on Mac. JOOQ: 3.11.11

**Comment by lukaseder** [comment]
Thank you very much for your report. I cannot reproduce this out of the box. Are you certain that there is not perhaps a time zone issue between your client and server?

**Comment by guytavor** [comment]
Hi,
Client is java unit case, Server is Mysql which returns IDT (israel day
time zone), which is what the computer is configured for.

mysql> SELECT @@system_time_zone;
>
> +--------------------+
>
> | @@system_time_zone |
>
> +--------------------+
>
> | IDT                |
>
> +--------------------+
>
>
does the provided unit test pass at your end?

Live long and prosper 🖖

Guy
*scoompa*

**Comment by lukaseder** [comment]
Yes, your works as expected with UTC:

```
@@system_time_zone|
------------------|
UTC               |
```

I've tried setting the time zone to something else using 

```sql
SET SESSION time_zone = CET
```

It doesn't change anything on my end.

Perhaps an MCVE might help? https://github.com/jOOQ/jOOQ-mcve

**Comment by lukaseder** [comment]
I didn't manage to reproduce this problem. Will close as "works for me".
