### ISSUE TITLE
SQL Translation Error

### ISSUE THREAD

**Issue by ramands** [jOOQ/jOOQ#8569]
### SQL translator incorrectly translates this query:

```sql
SELECT (pm.start_date   interval 330 minute) from demo
```

### Parser output:

```sql
Token ')' expected: [1:34] SELECT (pm.start_date   interval [*]330 minute) from demo
```

**Comment by lukaseder** [comment]
Thank you very much for your report.

May I ask: What RDBMS's interval arithmetic syntax is this?

**Comment by lukaseder** [comment]
Unfortunately, we cannot fix this issue without knowing the RDBMS dialect, which is needed to look up the specific syntax.
