### ISSUE TITLE
Add parser support for RATIO_TO_REPORT

### ISSUE THREAD

**Issue by katzyn** [jOOQ/jOOQ#8572]
### SQL translator does not accept `RATIO_TO_REPORT()` function:

```SQL
SELECT RATIO_TO_REPORT(A) OVER (PARTITION BY B) FROM C
```
### Output:
```
Unknown function: [1:24] SELECT RATIO_TO_REPORT([*]A) OVER (PARTITION BY B) FROM C;
```

This non-standard function seems to be supported by jOOQ, but translator can't parse it.

**Comment by lukaseder** [comment]
Thank you very much for your report. Will fix immediately.

**Comment by lukaseder** [comment]
For the record, it is emulated as follows in H2 and others:

```sql
select cast(a as decimal) / sum(a) over (partition by b) from c;
```

**Comment by katzyn** [comment]
This issue wasn't about H2, but `RATIO_TO_REPORT()` should not be emulated for H2 output target, at least when source function doesn't have window ordering and window frame clauses:
https://h2database.com/html/functions.html#ratio_to_report
Different databases that have such function have different restrictions.

**Comment by lukaseder** [comment]
Nice, thanks for the pointer. We'll add native support in a future release: https://github.com/jOOQ/jOOQ/issues/8575
