### ISSUE TITLE
Add support for SQLite partial indexes

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8588]
The `@Support` annotation on the `CreateIndexWhereStep#where()` methods does not include `SQLITE`, although SQLite supports partial indexes: https://www.sqlite.org/partialindex.html.

**Comment by lukaseder** [comment]
It's a feature, not a bug :-) The feature was introduced in SQLite 3.8.0. I must have overlooked it. We should definitely support it in jOOQ 3.12.

**Comment by knutwannheden** [comment]
I found this one using the @Support verification in testing.

**Comment by knutwannheden** [comment]
Is the `WHERE` clause in `CREATE INDEX` considered a storage clause? https://github.com/jOOQ/jOOQ/blob/a7215a91baa67988bd0b29d31d07eb832d1f2695/jOOQ/src/main/java/org/jooq/impl/CreateIndexImpl.java#L320

**Comment by lukaseder** [comment]
> I found this one using the @Support verification in testing.

Yes, so there are two things:

1) We haven't officially supported the feature for SQLite yet (new feature)
2) We have (accidentally) already integration tested the feature in SQLite (internal bug)

At least, that's how I see it. I like features more than bugs... :)

> Is the WHERE clause in CREATE INDEX considered a storage clause?

Rationale for that logic in #7853

**Comment by knutwannheden** [comment]
Completely agree with your feature vs. bug reasoning.
