### ISSUE TITLE
Support more DDL for MySQL

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8595]
jOOQ now also supports `CREATE SCHEMA`, `CREATE OR REPLACE VIEW`, and `DROP SCHEMA` for MySQL.

**Comment by lukaseder** [comment]
Thanks. Seems like an oversight in the implementation of #8438 et al.

**Comment by knutwannheden** [comment]
Since I worked on MySQL only, I left Aurora out for now.
