### ISSUE TITLE
Support more DML for MySQL

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8596]
The jOOQ API doesn't explicitly state (using `@Support`) that the following clauses are supported in MySQL:

* `INSERT ... ON CONFLICT ON CONSTRAINT` (which is emulated)
* `MERGE ... VALUES` (also emulated)
* Derived column alias list for CTEs using a name function

**Comment by lukaseder** [comment]
Hmm, I'm just wondering if this is really correct. The emulation works via `ON DUPLICATE KEY UPDATE`, but that's not *exactly* the same as `ON CONFLICT ON CONSTRAINT`, for example. The MySQL syntax checks *all* unique constraints for conflicts. The PostgreSQL syntax only checks a *single* unique constraint for conflicts.

Perhaps our test cases are too simple?

**Comment by lukaseder** [comment]
As discussed, we'll keep the annotations and add additional Javadoc documenting the edge case where the emulation might do too much.

**Comment by knutwannheden** [comment]
In commit dc4857e0514e46a1b8357ba9e50e1336e89991d8 the overloaded `InsertQuery#onConflictOnConstraint(UniqueKey)` method was changed to support all dialects (i.e. with a simple `@Support`). I suppose this was by accident?

**Comment by lukaseder** [comment]
This is because `DO NOTHING` can be emulated in any dialect

**Comment by knutwannheden** [comment]
Right. But then all overloaded `onConflictOnConstraint()` methods should probably have the same `@Support` annotation.

**Comment by lukaseder** [comment]
Nope :) Only the one you found has an argument containing column information that is needed for the emulation. The other overloads that reference the constraint by name do not pass on column information, so it is not possible (currently) to emulate the overload...

Well, in fact, we could try to look up the `UniqueKey` from the `Constraint` or `Name` reference. Perhaps we do have all the meta data.

**Comment by lukaseder** [comment]
... if that last bit is the case, you could create a new issue and implement it :)

**Comment by knutwannheden** [comment]
> Nope :) Only the one you found has an argument containing column information that is needed for the emulation. The other overloads that reference the constraint by name do not pass on column information, so it is not possible (currently) to emulate the overload...

I still don't quite get this. Looking at the implementation it looks like they should all work equally well:

```java
    @Override
    public final void onConflictOnConstraint(Constraint constraint) {
        onConflictOnConstraint0(constraint);
    }

    @Override
    public void onConflictOnConstraint(UniqueKey<R> constraint) {
        if (StringUtils.isEmpty(constraint.getName()))
            throw new IllegalArgumentException("UniqueKey's name is not specified");

        this.onConstraintUniqueKey = constraint;
        onConflictOnConstraint0(constraint(name(constraint.getName())));
    }

    @Override
    public final void onConflictOnConstraint(Name constraint) {
        onConflictOnConstraint0(constraint(constraint));
    }

    private void onConflictOnConstraint0(Constraint constraint) {
        this.onConstraint = constraint;

        if (onConstraintUniqueKey == null) {
            for (UniqueKey<R> key : table().getKeys()) {
                if (constraint.getName().equals(key.getName())) {
                    onConstraintUniqueKey = key;
                    break;
                }
            }
        }
    }
```

In fact it is `onConflictOnConstraint(UniqueKey)` which looks a bit funny, since it first looks up the `Constraint` with the same name and then again looks up the `UniqueKey` with the same name.

**Comment by knutwannheden** [comment]
I also just noticed that we should probably also add `MYSQL` to the `InsertOnDuplicateStep#onConflictOnConstraint()` methods. In the commit 554b8fcd1e1a2eaa29acfac30cf6172724474065 I only changed the `@Support` annotations of these methods in `InsertQuery`.

**Comment by knutwannheden** [comment]
Note: It looks like the `ON CONFLICT ON CONSTRAINT` emulation works via `MERGE` (see #7409) and for MySQL this is in turn emulated using `ON DUPLICATE KEY UPDATE`.

**Comment by knutwannheden** [comment]
In summary I think your analysis regarding the `ON DUPLICATE KEY UPDATE` emulation is correct. (Although one weird thing is that MySQL returns an update count of 2 instead of 1 in such cases.)

But I also think that we can keep the MySQL support on the discussed method, since it should in any case be correct for the `DO NOTHING` clause (`InsertOnConflictDoUpdateStep#doNothing()`). Also note that `InsertOnConflictDoUpdateStep#doUpdate()` doesn't yet state MySQL support anyway.
