### ISSUE TITLE
I want to query the data of the two tables together and eventually merge them into one DTO. How to do?

### ISSUE THREAD

**Issue by wushuaiping** [jOOQ/jOOQ#8597]
### Your question:
Write the following code using QueryDSL
```java
jpaQueryFactory
            .from(contractAggregate)
            .leftJoin(contractAggregate.buildings, building)
            .where(where)
            .select(contractAggregate)
            .groupBy(contractAggregate.contractId)
            .transform(groupBy(contractAggregate.contractId).list(
                Projections.bean(ContractWithExpenseDTO.class,
                    contractAggregate.contractId,
                    contractAggregate.startDate,
                    contractAggregate.spaceUnit,
                    contractAggregate.baseTermAreaSize,
                    contractAggregate.endDate,
                    GroupBy.set(building.buildingId
                    ).as("buildingIds")
                )));
```
How can you write something like this using jooq?

DTO
```java
public class ContractWithExpenseDTO {

    private Long contractId;

    private LocalDateTime startDate;

    private LocalDateTime endDate;

    private Set<Long> buildingIds;

    private BigDecimal baseTermAreaSize;

    private ContractSpaceUnitEnum spaceUnit;
}
```
### Versions:

- jOOQ: 3.11.11
- Java: JDK8
- Database (include vendor): MYSQL 8.1
- OS: macOS Mojave
- JDBC Driver (include name if inofficial driver): 

Thanks

**Comment by lukaseder** [comment]
Thank you very much for your message. I'm not fully fluent with QueryDSL, but from what this looks like, I would expect the following to work in a similar way:

```java
Map<ContractRecord, List<Long>> result =
ctx.select()
   .from(CONTRACT)
   .leftJoin(BUILDING).on(CONTRACT.CONTRACT_ID.eq(BUILDING.CONTRACT_ID))
   .fetchGroups(CONTRACT, r -> r.get(BUILDING.BUILDING_ID));
```

This fetches results into a map, not into nested DTOs.

jOOQ currently doesn't support fetching into nested DTOs. We'll work on such features in the near future. For the time being, a third party plugin might help getting comparable functionality into jOOQ:
https://simpleflatmapper.org/0106-getting-started-jooq.html

**Comment by wushuaiping** [comment]
> Thank you very much for your message. I'm not fully fluent with QueryDSL, but from what this looks like, I would expect the following to work in a similar way:
> 
> ```java
> Map<ContractRecord, List<Long>> result =
> ctx.select()
>    .from(CONTRACT)
>    .leftJoin(BUILDING).on(CONTRACT.CONTRACT_ID.eq(BUILDING.CONTRACT_ID))
>    .fetchGroups(CONTRACT, r -> r.get(BUILDING.BUILDING_ID));
> ```
> 
> This fetches results into a map, not into nested DTOs.
> 
> jOOQ currently doesn't support fetching into nested DTOs. We'll work on such features in the near future. For the time being, a third party plugin might help getting comparable functionality into jOOQ:
> https://simpleflatmapper.org/0106-getting-started-jooq.html

Thanks
