### ISSUE TITLE
Add utility Tools#isScalarSubquery(Field)

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8607]
A simple utility to do an `instanceof ScalarSubquery` check would be nice.

**Comment by lukaseder** [comment]
Or even `Tools.extractScalarSubquery(Field):Select`, which returns `null` if there's no extractable `Select` statement.

**Comment by lukaseder** [comment]
There was probably a reason why this would have been nice, but it's not documented here. We'll live with the status quo.
