### ISSUE TITLE
Some MySQL encryption functions were removed in MySQL 8.0.x

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8611]
Some of the MySQL encryption functions documented (https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html) were removed in "service releases". This should probably be reflected in `MySQLDSL` and the corresponding integration tests should be disabled (when testing against a current release).

**Comment by lukaseder** [comment]
Nice catch. Agreed.

**Comment by lukaseder** [comment]
Deprecating support for these functions:

- `DECODE()`
- `DES_DECRYPT()`
- `DES_ENCRYPT()`
- `ENCODE()`
- `ENCRYPT()`
- `PASSWORD()`

As listed here:
https://dev.mysql.com/doc/refman/5.7/en/encryption-functions.html

In the long run, these dialect specific DSL classes might be removed:
https://github.com/jOOQ/jOOQ/issues/10796
