### ISSUE TITLE
Passing arrays of generated tableRecords to a stored procedure generates SQL that won't parse due to cast ::any[]

### ISSUE THREAD

**Issue by uncbailey1** [jOOQ/jOOQ#8614]
### Your question:
In looking for a workaround for issue #8612, I tried something else that is failing.  In reality, we want to pass an array of records into our function.  when I do this, I don't get the SQLDialectNotSupportedException, but the generated SQL apparently does not parse and throws an error.  The generate SQL is trying to do a cast to any[]...see below.

I have also tried not using the intermediate type and changed the stored function to take in an array of my_table as the input parameter (i.e., in_param my_table[]) and I get the same behavior as described below.

```sql
CREATE TYPE list_of_my_table_records AS (
    my_records myTable[]
);

CREATE FUNCTION do_some_stuff(in_param list_of_my_table_records) RETURNS TEXT AS $$
BEGIN
    RETURN 'test';
END $$ LANGUAGE plpgsql;
```

Java code to invoke the function would do something like the following;

```java
ListOfMyTableRecords input = new ListOfMyTableRecords();
input.setMyRecords(listOfRecords.stream().map(this::MapToMyTableRecord).collect(toList()).toArray());

DoSomeStuff doSomeStuff = new DoSomeStuff();
doSomeStuff.attach(create.configuration());
doSomeStuff.setIn_param(input);
doSomeStuff.execute();
return doSomeStuff.getReturnValue();
```

Here is the error thrown

```
  ComposedException 1 :
	org.jooq.exception.DataAccessException: SQL [select "do_some_stuff" from "do_some_stuff"("in_param" := row(?::any[]))]; ERROR: syntax error at or near "any"
```

### Versions:
    jOOQ: 3.7.3
    Java: build 1.8.0_141-b16
    Database (include vendor): Postgreql 10.0
    OS: Centox 7
    JDBC Driver (include name if inofficial driver):

**Comment by uncbailey1** [comment]
I added a note to #8612 which applies here as well.  I can get this to work correctly if I add a type to the DB which maps to the same generated table record for my table and I can pass arrays of the UDT without issue.

**Comment by lukaseder** [comment]
Finally trying to reproduce this on my side with:

```sql
CREATE TABLE t_8614 (i int, j int);

CREATE TYPE u_8614 AS (
  r t_8614[]
);

CREATE OR REPLACE FUNCTION f_8614 (i u_8614) RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT string_agg(t.i || ':' || t.j, ',') FROM unnest((i).r) AS t); 
END
$$ LANGUAGE plpgsql;
```

Then with this test:

```java
@Test
public void testPostgresFunctionWithUDTContainingArrayOfTableRecord() {
    assertNull(Routines.f_8614(configuration(), new U_8614Record((T_8614Record[]) null)));
    assertNull(Routines.f_8614(configuration(), new U_8614Record(new T_8614Record[0])));
    assertEquals("1:2", Routines.f_8614(configuration(), new U_8614Record(new T_8614Record[] { new T_8614Record(1, 2) })));
    assertEquals("1:2,3:4", Routines.f_8614(configuration(), new U_8614Record(new T_8614Record[] { new T_8614Record(1, 2), new T_8614Record(3, 4) })));
}
```

The test passes, and runs this query:

```sql
select "f_8614" from "public"."f_8614"("i" := row(?::t_8614[])::"public"."u_8614")
```

It seems this issue has been fixed in the meantime. I remember quite a few improvements in the area of casting such data types.
