### ISSUE TITLE
Missing NOTICE file from commons-lang

### ISSUE THREAD

**Issue by tazle** [jOOQ/jOOQ#8615]
It appears that jooq includes code from commons-lang under ASL 2.0. ASL 2.0. requires that the contents of a NOTICE file in the work be included with redistributions (section 4 d). Commons-lang has a NOTICE file (e.g. mirrored at https://github.com/apache/commons-lang/blob/master/NOTICE.txt). You do list Apache Commons at http://www.jooq.org/legal/licensing, but that page seems to be missing some of the information, and does not appear to be part of your distribution package.

On the whole, it would be helpful to have a list of all embedded 3rd party party packages available in the source repository, together with proper attributions.

### Versions:

- jOOQ: 3.9.6, 3.11.11

**Comment by lukaseder** [comment]
Thank you very much for your report. You're right, we need to reproduce this notice file content to comply with the ASL 2.0 of our shaded dependencies. We'll fix this ASAP and backport the fix to a few recent releases.

I like your idea of adding a list of dependencies and their license to the deliverables, both in the zip file downloaded from our website: https://www.jooq.org/download, as well as in the jOOQ runtime jar file, e.g. inside of `META-INF`.

Another issue that we would like to address is to re-implement our hand-written shading in a way that makes it clear which parts of these dependencies are the original code, and which part is our adaptation. For example, we've added a few methods to the commons-lang derived class `StringUtils`, which are our own. It would be better to separate these bits of work.

**Comment by lukaseder** [comment]
Reading through the [ASL 2.0 text](https://github.com/apache/commons-lang/blob/master/LICENSE.txt) (emphasis mine):

>      (d) If the Work includes a "NOTICE" text file as part of its
>          distribution, then any Derivative Works that You distribute must
>          include a readable copy of the attribution notices contained
>          within such NOTICE file, excluding those notices that do not
>          pertain to any part of the Derivative Works, in *at least one*
>          of the following places: within a NOTICE text file distributed
>          as part of the Derivative Works; within the Source form *or
>          documentation*, if provided along with the Derivative Works; or,
>          within a display generated by the Derivative Works, if and
>          wherever such third-party notices normally appear. The contents
>          of the NOTICE file are for informational purposes only and
>          do not modify the License. You may add Your own attribution
>          notices within Derivative Works that You distribute, alongside
>          or as an addendum to the NOTICE text from the Work, provided
>          that such additional attribution notices cannot be construed
>          as modifying the License.

So, with a liberal interpretation of the text, we can say that we already comply with the license. Nevertheless, it will be better to also fulfil the option where we, ourselves, include a `NOTICE` file in our distribution that amends our included dependencies' `NOTICE` files.

**Comment by lukaseder** [comment]
I've added the `NOTICE.txt` file to all artifacts that we publish. Old versions cannot be modified on Maven Central, but I'll backport this to 3.11.12 (#8664) and 3.10.9 (#8665).

Thanks again for pointing this out.
