### ISSUE TITLE
Missing DB2 dialect versions in SelectQueryImpl#WRAP_EXP_BODY_IN_DERIVED_TABLE

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8625]
The emulation `SelectQueryImpl#WRAP_EXP_BODY_IN_DERIVED_TABLE` is dialect specific but also contains families like `DB2` and `ACCESS`. This needs to be checked.

**Comment by lukaseder** [comment]
`ACCESS` is OK because there's only one versioned dialect `ACCESS2013` (unnecessarily). But for `DB2`, it doesn't seem like the configuration is superfluous. I suspect this is an oversight, and we should add all `DB2` versions.

**Comment by lukaseder** [comment]
... in other words, the current behaviour is wrong for `DB2_10` and `DB2_11`
