### ISSUE TITLE
Track MemSQL savepoint support

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8628]
MemSQL currently doesn't appear to handle savepoints correctly. This has been reported in the forum: https://www.memsql.com/forum/t/support-for-savepoints/689.

The purpose of this issue is to track the status of this bug / limitation.

**Comment by knutwannheden** [comment]
As commented in the forum savepoints are not supported.

**Comment by lukaseder** [comment]
I think we can close and reject this, then?
