### ISSUE TITLE
MySQL does not support DROP INDEX IF EXISTS

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8634]
Remove `MYSQL` from `@Support` annotations on `DSLContext#dropIndexIfExists()` methods, as it is not supported and cannot easily be emulated, as MySQL doesn't support anonymous code blocks.

**Comment by knutwannheden** [comment]
Same for `DSL#dropIndexIfExists()` of course.

**Comment by lukaseder** [comment]
Hmm, yes, I must have mistakenly thought that this functionality was available, because MariaDB has it:
https://mariadb.com/kb/en/library/drop-index/

**Comment by lukaseder** [comment]
Note that jOOQ 3.12 can emulate anonymous code blocks on MySQL. Not sure if you're going to like it :)

**Comment by knutwannheden** [comment]
:astonished: How does that work? Would you recommend we implement this for DROP INDEX IF EXISTS?

**Comment by lukaseder** [comment]
MySQL supports statement batches (`;` separated statements). So, we can either:

- Just run several statements in such a statement batch (works only for SQL)
- Create a procedure, run it, drop it again, in such a statement batch (works also for procedural code)

**Comment by lukaseder** [comment]
> Would you recommend we implement this for DROP INDEX IF EXISTS?

Maybe, in the future.
