### ISSUE TITLE
Separate section for jOOQ's SQL extensions

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8642]
I am thinking it might make sense to have a separate section in the manual which gives an overview of all "synthetic SQL extensions" part of jOOQ as a means to "whet the appetite".

**Comment by lukaseder** [comment]
Interesting thought. Why not? Well, the clauses' own documentation pages would still be located where they are now, where it makes sense in the context of the DSL documentation, for example:

- https://www.jooq.org/doc/3.11/manual/sql-building/sql-statements/select-statement/seek-clause/
- https://www.jooq.org/doc/3.11/manual/sql-building/sql-statements/select-statement/implicit-join/

But a new section would summarise all the synthetic SQL features.

**Comment by lukaseder** [comment]
We now have a section for this.

I don't think we should repeat too much syntax / examples on this page, but instead maintain a list of links towards other manual pages that explain the feature in the right context.

The current list might be incomplete - we'll maintain it as we go in the future.
