### ISSUE TITLE
Apply Settings.fetchSize also to other statements than ResultQuery

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8646]
The `Settings.fetchSize` (and possibly other JDBC flags) are currently applied only to `ResultQuery`. When stored procedures return cursors, it is equally useful to modify the fetch size of a JDBC statement, in particular in Oracle, where the default is 10.

**Comment by knutwannheden** [comment]
`Statement#setFetchSize(int)` must be called after the statement has been prepared and before it is being executed. For the time being it seems easiest to add a new protected `AbstractQuery#setFetchSize(int, ExecuteContext)` method and have that being called by the various subclasses. Does that sound reasonable?

**Comment by lukaseder** [comment]
I'm not sure we gain a lot right now from this abstraction. Everywhere we execute JDBC statements, we know exactly where to set the fetch size. We can put that logic there.

Note the driver for this change is a customer needing this feature on `AbstractRoutine`

**Comment by knutwannheden** [comment]
I see. I was thinking this was mostly about `AbstractDMLQuery` (e.g. for the `RETURNING` clause). In that case adding a member to `AbstractQuery` is indeed not the right place. I was just thinking we might want to have a utility method like the following, which we can reuse:

```java
    protected final void setFetchSize(int fetchSize, ExecuteContext ctx) throws SQLException {
        // [#1263] [#4753] Allow for negative fetch sizes to support some non-standard
        // MySQL feature, where Integer.MIN_VALUE is used
        int f = SettingsTools.getFetchSize(fetchSize, ctx.settings());
        if (f != 0) {
            if (log.isDebugEnabled())
                log.debug("Setting fetch size", f);

            ctx.statement().setFetchSize(f);
        }
    }
```

Maybe add it to `Tools` or `SettingsTools`?

**Comment by lukaseder** [comment]
Oh yes, sure. We can have such a utility. There are similar utilities in `Tools`. `SettingsTools` is public API and in a different package, so I wouldn't put it there. If possible, try making it package private (e.g. in `Tools`).

**Comment by knutwannheden** [comment]
Hmm... Not sure how we should test this. Any proposal?

**Comment by lukaseder** [comment]
Yes, look at `org.jooq.test.PreparedStatementFlagTest.testFetchSizeViaSettings()
