### ISSUE TITLE
Query parser fails to parse the mysql YEAR data type

### ISSUE THREAD

**Issue by billoneil** [jOOQ/jOOQ#8647]
### Expected behavior and actual behavior:
The query parser fails to parse the MySQL `YEAR` data type.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
https://github.com/billoneil/jOOQ-mcve/pull/1/files#diff-a6ed11aa6430e485005acd9a8693f7f9R55

### Versions:

- jOOQ: 3.11.11
- Java: 8
- Database (include vendor): MySQL
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks for your report. Indeed, the current support for MySQL's `YEAR` type is insufficient. This isn't just a parser issue, but affects jOOQ globally.

I'm undecided whether we should standardise on this `YEAR` type (and possibly other useful temporal types) in `SQLDataType`, offering them on all RDBMS, or if there's an alternative solution.

**Comment by lukaseder** [comment]
I'm afraid that right now, the recommendation in this area is to not use the `YEAR` data type and use either a `DATE` or an `SMALLINT` instead.

**Comment by billoneil** [comment]
Would there be a way to utilize the code generators forced types to convert a year to a `DATE` or `SMALLINT` on the fly? I'm not sure if the API could support that and it would probably be some work. Just throwing a thought out there since this seems to have an existing workaround on the code generation side. That would allow the use of the parser without changing schemas and if it is ever implemented in the future the forced type could be removed.

**Comment by lukaseder** [comment]
Just to be sure: The `YEAR` type does not cause any issues with jOOQ's code generator or runtime, but with the `DDLDatabase` and/or the parser.

A workaround would be to regex-replace `YEAR` by `DATE` (or something similar) prior to parsing the SQL, and then applying a converter on the generated output.

**Comment by lukaseder** [comment]
Will support the MySQL `YEAR` data type in jOOQ 3.18: https://github.com/jOOQ/jOOQ/issues/2500
