### ISSUE TITLE
Query parser fails to parse alter table drop foreign key

### ISSUE THREAD

**Issue by billoneil** [jOOQ/jOOQ#8648]
### Expected behavior and actual behavior:
The query parser should parse the alter table statement without throwing an exception

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
https://github.com/billoneil/jOOQ-mcve/pull/1/files#diff-a6ed11aa6430e485005acd9a8693f7f9R47

### Versions:

- jOOQ: 3.11.11
- Java: 8
- Database (include vendor): MySQL
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report. Indeed, we should support parsing this syntax, but we need to support the syntax in the jOOQ API first (#8649). Unfortunately, emulating the standard `DROP CONSTRAINT` syntax on MySQL is difficult as we do not know if a given `org.jooq.Constraint` is a unique key or a foreign key.

I'm closing this as a duplicate of #8649

**Comment by lukaseder** [comment]
I'm afraid, I currently cannot think of a workaround...

**Comment by lukaseder** [comment]
#8649 is implemented in jOOQ 3.12
