### ISSUE TITLE
Add support for parsing VALUES <row value special case>, ...

### ISSUE THREAD

**Issue by katzyn** [jOOQ/jOOQ#8653]
1. Query parser can't parse the table value constructor that immediately contains a row value special case.
```
<table value constructor> ::= VALUES <row value expression list>

<row value expression list> ::=
    <table row value expression> [ { <comma> <table row value expression> }... ]

<table row value expression> ::= <row value special case> | <row value constructor>

<row value special case> ::= <nonparenthesized value expression primary>
```
SQL-92 has a different grammar, but it allows such construction too.

Query
```SQL
VALUES 1, 2, 3
```
is vaild in DB2, recent versions of H2 and possibly in some other databases. Translate tool reports the following error:
```SQL
Token '(' expected: [1:8] VALUES [*]1, 2, 3;
```

The expected behavior is to parse it properly and produce
```SQL
VALUES (1), (2), (3)
```
for output dialects that don't support that standard syntax or in all dialects unconditionally.

2. Query parser cannot parse the table value constructor that immediately contains an explicit row value constructor with `ROW` keyword.
```
<row value constructor> ::=
    <common value expression>
  | <boolean value expression>
  | <explicit row value constructor>

<explicit row value constructor> ::=
    <left paren> <row value constructor element> <comma>
        <row value constructor element list> <right paren>
  | ROW <left paren> <row value constructor element list> <right paren>
  | <row subquery>
```

```SQL
VALUES ROW(1)
```

```SQL
Token '(' expected: [1:8] VALUES [*]ROW(1)
````

Both issues are caused by the following incomplete implementation where some uncommon cases are missing:
https://github.com/jOOQ/jOOQ/blob/ebce61b0fcbacd04e087a7ca5132cd61e6f315d0/jOOQ/src/main/java/org/jooq/impl/ParserImpl.java#L4713-L4733

**Comment by katzyn** [comment]
Both constructions require feature T051 “Row types” in the implementations and many databases don't support them.

The `T:Defect` label was inserted from the issue template form and I can't change it to `T:Enhancement` label by myself.

**Comment by lukaseder** [comment]
Thank you very much for your thorough report. Very interesting, I hadn't encountered these syntaxes yet (as PostgreSQL doesn't support either one of them), but you're absolutely right. Great to see that H2 supports them.

We'll implement support for these syntaxes soon.

**Comment by katzyn** [comment]
jOOQ has the same issue with `<contextually typed table value constructor>` part in the standard `<insert statement>`:
```SQL
INSERT INTO TEST VALUES 1, (2), ROW(3);
```
https://github.com/jOOQ/jOOQ/blob/ebce61b0fcbacd04e087a7ca5132cd61e6f315d0/jOOQ/src/main/java/org/jooq/impl/ParserImpl.java#L1651-L1656

`<merge statement>` is also affected.
https://github.com/jOOQ/jOOQ/blob/ebce61b0fcbacd04e087a7ca5132cd61e6f315d0/jOOQ/src/main/java/org/jooq/impl/ParserImpl.java#L1873-L1874

Contextually typed expressions have the very similar syntax.

**Comment by lukaseder** [comment]
Looking into this now. I guess the jOOQ parser still cannot reliably distinguish between `(` used for row value expressions and `(` used for subqueries. Parsing this is a challenge:

```sql
values (select 1)
```

**Comment by lukaseder** [comment]
OK, I can re-use a backtracking algorithm used in `parseTerm()`, which is slow but seems correct. One day, I'll fix that...
