### ISSUE TITLE
Add static utilities SQLDialect#families(SQLDialect...) and dialects(SQLDialect...)

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8662]
The proposed `SQLDialect#families(SQLDialect...)` and `dialects(SQLDialect...)` would both return an `EnumSet<SQLDialect>` and would have the advantage over the standard `EnumSet#of(Object...)` that they also work without arguments, where one would otherwise have to use `EnumSet#noneOf(Class)`.

**Comment by lukaseder** [comment]
I totally think that `SQLDialect#families()` would be useful. But I'm not sure what `dialects()` should do? The semantics of these methods is that of `map()`, not `filter()`, I assume?

**Comment by lukaseder** [comment]
Do note that in `Functions.xtend` (private `jOOQ-tools` project), we already have:

```
    def static EnumSet<SQLDialect> families(SQLDialect[] dialects) {
        if (dialects == null || dialects.length == 0)
            return families;
            
        val result = EnumSet::noneOf(typeof(SQLDialect));
        
        for (SQLDialect d : dialects) {
            if (d != SQLDialect.SQL99 && d != SQLDialect.DEFAULT) 
                result.add(d.family());
        }
        
        return result;
    }
```

**Comment by knutwannheden** [comment]
`families()` would be used to get an EnumSet of families and `dialects()` when the entries correspond to dialects. But if we don't have any use case for `dialects()` yet, we should probably wait with that.

**Comment by knutwannheden** [comment]
Possibly we could still use Java's `assert` if we "externalize" the checking into a separate method, as I assume we would then only add the bytecode for a single method call. We could then in `families()` validate that indeed all objects correspond to families, none are deprecated, none are duplicated, and if we want even make sure that they are alphabetically sorted.

**Comment by lukaseder** [comment]
> dialects() when the entries correspond to dialects. But if we don't have any use case for dialects() yet, we should probably wait with that.

My problem here is that every family is also implicitly a dialect, so I'm not sure how this would be useful with the current design. The method would always return the input array.

> Possibly we could still use Java's assert if we "externalize" the checking into a separate method, as I assume we would then only add the bytecode for a single method call.

What problem is an assertion solving here? Remember, you're thinking of adding something to the public API. The assertion seems to handle a problem that might occur in private jOOQ edition management logic. I think it would be wrong to place an assertion with knowledge about the specific use case of your specific call site into this public API.

> We could then in families() validate that indeed all objects correspond to families, none are deprecated, none are duplicated, and if we want even make sure that they are alphabetically sorted.

We can also just write a unit test :)

**Comment by knutwannheden** [comment]
> We can also just write a unit test :)

I suppose you mean that we would add code to also instrument `SQLDialect#families()` in `SupportVerificationTransformer`. An interceptor could then record all "incorrect" calls and the integration test could then assert that none were found. Although we would have to make sure that this test runs as late as possible after all classes which use `SQLDialect#families()` (typically in static field initializers) have been initialized. Or did you have something completely else in mind?

**Comment by lukaseder** [comment]
I'm really not sure what "incorrect" calls you have in mind. Could you please explain?

**Comment by knutwannheden** [comment]
For calls to `families()` I would for instance want to verify that all given `SQLDialect` objects indeed represent a family and not version specific dialects. And for the sake of consistency why not also verify that the array doesn't contain duplicates and is alphabetically ordered (as we usually have it).

**Comment by lukaseder** [comment]
But that sounds like a unit test, no?

**Comment by lukaseder** [comment]
I'm still not sure if I properly understood this requirement here. An explanation in code would help.
