### ISSUE TITLE
Fix Javadoc links in manual

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8663]
In the jOOQ manual the HTTP links to jOOQ's own Javadoc is broken in the case of links to class members. So for example the link from http://www.jooq.org/doc/3.12/manual/sql-building/sql-statements/insert-statement/insert-default-values/ to https://www.jooq.org/javadoc/3.12.x/org/jooq/impl/DSL.html#defaultValue() should actually link to https://www.jooq.org/javadoc/3.12.x/org/jooq/impl/DSL.html#defaultValue--.

While URI fragments would actually allow for '(' and ')' characters (without being encoded), Javadoc doesn't use them in the anchors.

**Comment by lukaseder** [comment]
The URL is generated by `html-utils.xsl` in the private `jOOQ-website` project. But parts of it are hard-coded in the various `manual-x.y.xml` files. I guess we should standardise on how we encode the `@anchor` element in the manual files and then implement the URL encoding logic only in the XSL file.

**Comment by knutwannheden** [comment]
Yes, changing all the manuals wouldn't make sense. Especially since these dashes don't really make things more readable!

**Comment by knutwannheden** [comment]
Also in the case of links to methods of the JDK Javadoc the URI fragments don't look correct in the rendered HTML (they appear to be missing). See for example https://www.jooq.org/doc/3.11/manual/sql-building/dsl-context/custom-settings/settings-jdbc-flags/.

**Comment by lukaseder** [comment]
> Yes, changing all the manuals wouldn't make sense. Especially since these dashes don't really make things more readable!

Well, not sure if I agree. A regex might lead to a quick win here... :)

> Also in the case of links to methods of the JDK Javadoc the URI fragments don't look correct in the rendered HTML (they appear to be missing). See for example https://www.jooq.org/doc/3.11/manual/sql-building/dsl-context/custom-settings/settings-jdbc-flags/.

What am I looking for, specifically?

**Comment by knutwannheden** [comment]
In the manual we for instance have `<reference class="java.sql.Statement" anchor="#setQueryTimeout(int)" title="Statement.setQueryTimeout()"/>` which now links to https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/Statement.html rather than https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/Statement.html#setQueryTimeout(int).

Although I now also don't understand why in the JDK links the URI fragments apparently look differently. Looks like I am still missing something here...

**Comment by lukaseder** [comment]
I see. A bug, probably.

**Comment by knutwannheden** [comment]
I fixed the problem with the missing anchors in the Javadoc links. But I am not sure with what versions of Javadoc we need to escape characters like `(` in the anchors. With newer versions of Javadoc that does not appear to be important. The manual published on jooq.org looks correct.

But the XSLT code looks a bit wrong, as I assume that `$minorVersion > '3.3'` will evaluate to false for version 3.12. But we may be lucky here, because we apparently *don't* want to apply the `java-8-javadoc-anchor` template anyway. Possibly this is necessary for the manuals for the `pro-java-6` and `pro-java-8` editions?

```xml
<xsl:choose>
    <xsl:when test="$minorVersion > '3.3'">
        <xsl:call-template name="java-8-javadoc-anchor">
            <xsl:with-param name="anchor" select="@anchor"/>
        </xsl:call-template>
    </xsl:when>
    <xsl:otherwise>
        <xsl:value-of select="@anchor"/>
    </xsl:otherwise>
</xsl:choose>
```

**Comment by lukaseder** [comment]
> But the XSLT code looks a bit wrong, as I assume that $minorVersion > '3.3' will evaluate to false for version 3.12

Oh boy, yes of course. OTOH, the lowest version we still link to in public is 3.2, so maybe, hardcoding 3.2 in the otherwise case might do the trick: https://www.jooq.org/learn

I think that this `-` anchor was introduced, and removed again later.

> Possibly this is necessary for the manuals for the pro-java-6 and pro-java-8 editions?

Luckily, we don't have separate manuals or Javadoc on the website. It's all just the `pro` edition. But historically, that was built with some given Java version...

**Comment by lukaseder** [comment]
The link mentioned in the description is working correctly by now, so this is probably a duplicate.
