### ISSUE TITLE
Does Record CRUD not automatically close the connection?

### ISSUE THREAD

**Issue by cn-src** [jOOQ/jOOQ#8666]
### Your question:

In a spring-boot project, use jooq like this:

```java
    @Autowired
    private DSLContext dslContext;
    
    public void insert() {
        final ProjectRecord record = new ProjectRecord();
        record.attach(dslContext.configuration());
        record.insert();
    }
```
Does the connection not automatically close?

### Versions:

- jOOQ: 3.11.11
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your request.

jOOQ uses a [`ConnectionProvider`](https://www.jooq.org/javadoc/latest/org/jooq/ConnectionProvider.html) behind the scenes and always calls `acquire()` before running a statement and `release()` after running it. Depending on how you have configured your `ConnectionProvider`, this may or may not close your JDBC connection. For example, when you pass jOOQ a standalone `Connection`, then it is never closed (`DefaultConnectionProvider`). When you pass it a `DataSource`, then the `Connection` is always closed (`DataSourceConnectionProvider`).

I hope this helps
