### ISSUE TITLE
Add ForeignKey.reverse(UniqueKey)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8670]
In order to reverse the navigation over one-to-one foreign keys (foreign keys that coincide with unique keys), we could use a new method `ForeignKey.reverse(UniqueKey)`.

Given:

```sql
CREATE TABLE a (
  x INT NOT NULL PRIMARY KEY
);
CREATE TABLE b (
  x INT UNIQUE REFERENCES a
);
```

Calling 

```java
B.getReferences(A).get(0).reverse()
```

Would yield a synthetic foreign key reference as if we had:

```sql
CREATE TABLE a (
  x INT NOT NULL PRIMARY KEY REFERENCES b
);
CREATE TABLE b (
  x INT PRIMARY KEY
);
```

For the avoidance of doubt, we should introduce a new super type of `ForeignKey` that:

- Doesn't really have a name
- Clearly communicates that it is not part of the schema

**Comment by alf** [comment]
This seems to be related to other work going on and being targeted for 3.19?
