### ISSUE TITLE
Some @Support annotations have duplicated dialects

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8671]
One such example is `DSL#trunc(Field, Field)`.

Also it could make sense to check that all `@Support` annotations list the dialects in alphabetical order.

**Comment by knutwannheden** [comment]
Also added test to make sure this stays correct in the future.

**Comment by lukaseder** [comment]
> Also it could make sense to check that all @Support annotations list the dialects in alphabetical order.

Look at `Loopback` in `Splitter.xtend`

**Comment by knutwannheden** [comment]
I will take a look, but I already extended our AnnotationsTest to check this.

**Comment by lukaseder** [comment]
That's a good idea. `Loopback` can be used to fix it, if it's wrong, but I guess with a test, that will no longer be needed...
