### ISSUE TITLE
SQL Translation Error

### ISSUE THREAD

**Issue by sadegbenle** [jOOQ/jOOQ#8673]
### SQL translator incorrectly translates this query:

```sql
CREATE TABLE DEVICES
(
  ID integer NOT NULL,
  NAME varchar(50),
  CONSTRAINT PK_DEVICES_0 PRIMARY KEY (ID)
)

**Comment by knutwannheden** [comment]
Thank you very much for your feedback. Can you please indicate for which SQL output dialect the translator (http://www.jooq.org/translate/) produces an incorrect translation and also what part of it is incorrect?

**Comment by lukaseder** [comment]
Thanks again for reporting.

We couldn't see anything wrong with the given query's parsing or translation. Feel free to reopen this issue, possibly with some additional information to help reproduce this, if you think there's a problem.
