### ISSUE TITLE
Complete parser test suite with tests for all supported built-in functions

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8674]
With #7755 we now have an integration test which uncovers all supported built-in functions which aren't covered by an existing parser test.

The purpose of this issue is to add any such missing tests.

**Comment by knutwannheden** [comment]
A parser test for Oracle's `CONNECT_BY_ROOT` pseudo column succeeded, somewhat surprisingly, since the parser doesn't yet support this. This is because the parser in the end parses it as a regular field name and in the parser tests the meta lookups are not configured to fail.

On the positive side the new coverage test (#7755) fails.

**Comment by knutwannheden** [comment]
We now have parser tests for `CONNECT_BY_ISCYCLE`, `CONNECT_BY_ISLEAF`, and `CONNECT_BY_ROOT`.

**Comment by knutwannheden** [comment]
I looked at the problem with the coverage of the `default()_` method. The keyword is being parsed by `parseName()` in the end. I suppose the produced AST still serializes to the correct SQL, but that might not be true when translating to a different dialect (not supporting `DEFAULT`). 

I suspect `parseSetClauseList()` should do a `parseKeywordIf(ctx, "DEFAULT")`?

**Comment by lukaseder** [comment]
I agree with your implementation. It does produce the "correct" SQL output, although the `RenderKeywordCase` setting is not applied correctly (pascal case `Default`!)

**Comment by knutwannheden** [comment]
> the RenderKeywordCase setting is not applied correctly (pascal case Default!)

Where is this wrong? I don't understand how this is a problem in the parser.

**Comment by lukaseder** [comment]
It was wrong before because the parser parsed a `Name`, not a `Keyword` (produced by `default_()`). It is correct now.

**Comment by knutwannheden** [comment]
Got it. Seems like I can finally close this one :-)
