### ISSUE TITLE
Enable Settings.parseUnknownFunctions in DDLDatabase

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8678]
There's no point in raising errors when unknown functions are encountered by the `DDLDatabase`. We can mostly just skip them, or perhaps log a warning (which would require a new enum value)

----
See https://github.com/jOOQ/jOOQ/issues/7344 *Add Settings.parseUnknownFunctions to turn off failing on unknown functions*

**Comment by knutwannheden** [comment]
See item I added to jOOQ/Tasks#6 😄

**Comment by lukaseder** [comment]
While this is a useful improvement, it is insufficient for PostgreSQL's / pg_dump's `SELECT pg_catalog.set_config('search_path', '', false);`, which has to be interpreted explicitly: https://github.com/jOOQ/jOOQ/issues/8910
