### ISSUE TITLE
about statistics measurement requirement

### ISSUE THREAD

**Issue by welkinbai** [jOOQ/jOOQ#8680]
### Your question:
Hi，jOOQ is amazing. My company use statsD to collect metrics for monitoring SQL performance and I known there is ExecuteListener for doing this.But the metrics like P50, P99, P99.9, execute times, timeout times , all of these need I code to calculate by myself.
Can jOOQ directly provide these metrics?or any other 3th library or framework can do this for me?

thanks.

### Versions:

- jOOQ:3.11.11
- Java:1.8
- Database (include vendor):mysql
- OS:linux
- JDBC Driver (include name if inofficial driver):mysql

**Comment by lukaseder** [comment]
Thank you very much for your request. We currently do not support such functionality out of the box, but we plan to offer it in the future via our diagnostics API:
https://www.jooq.org/doc/latest/manual/sql-execution/diagnostics

Calculating execution time percentiles will definitely be part of that new product. Right now, you will probably need to calculate this yourself, or use some third party profiler, like AppDynamics or Dynatrace.
