### ISSUE TITLE
jOOQ generation tool produces Vertica composite unique key columns in wrong order

### ISSUE THREAD

**Issue by blacky0x0** [jOOQ/jOOQ#8686]
### Expected behavior and actual behavior:
Actual: jOOQ tool generates an unpredictable order of columns for composite primary/unique key 
 in Vertica DB therefore we always get some changes in generated Java code.
Expected: jOOQ generates composite/unique key columns order as it's presented in the table.

### Steps to reproduce the issue
For example, let's assume we have the following table in Vertica DB:
```
CREATE TABLE t (
  aaa_id      INTEGER   NOT NULL,
  bbb_id      INTEGER   NOT NULL,
  ccc_type    INTEGER   NOT NULL,
  start       TIMESTAMP NOT NULL DEFAULT '',
  end         TIMESTAMP NOT NULL DEFAULT '',
  PRIMARY KEY (aaa_id, ccc_type, start, end)
)
```

This issue occurs when we use `jooq-codegen-maven` for generating `POJO`, `DAO` and other stuff like `jpaAnnotations`. jOOQ generation tool will produce composite unique key with wrong order columns in the code:
```
# jOOQ generation tool with `jpaAnnotations=true` can produce the following code:
@UniqueConstraint(columnNames = ("start", "aaa_id", "ccc_type", "end"))
# or
@UniqueConstraint(columnNames = ("aaa_id", "ccc_type", "end", "start"))

# but the correct one should be the following
@UniqueConstraint(columnNames = ("aaa_id", "ccc_type", "start", "end"))
```

### Versions:

- jOOQ: 3.10.2
- Java: 1.8
- Database: Vertica v9.0
- OS: linux 16.04.5 LTS
- JDBC Driver: com.vertica.vertica-jdbc v9.0.1

**Comment by lukaseder** [comment]
Thank you very much for your report.

The order of generated columns in the `@UniqueConstraint` annotation currently has no effect on jOOQ, but if that particular order is wrong, the order might also be wrong in the `Keys.java` class, in case of which a reproduction of the DDL code via `DSLContext.ddl()` might be wrong.

We'll investigate this soon.

**Comment by blacky0x0** [comment]
Yep, exactly. Thank for the reply

**Comment by lukaseder** [comment]
I can confirm the order of columns isn't correct, also in older versions of Vertica

**Comment by lukaseder** [comment]
`VerticaDatabase.fetchKeys()` orders constraint information only by schema/name/constraint name. There doesn't seem to be a column in the `CONSTRAINT_COLUMNS` meta data view that allows for ordering the columns by their appearance in the constraint:

```sql
select * 
from constraint_columns
where constraint_name = 'C_PRIMARY';
```

**Comment by lukaseder** [comment]
This query would allow it:

```sql
select *
from v_catalog.primary_keys
where constraint_name = 'C_PRIMARY'
order by ordinal_position;
```

A similar table exists for foreign keys, but unfortunately, not for unique keys.

**Comment by lukaseder** [comment]
While fixing this, I've also noticed another issue: https://github.com/jOOQ/jOOQ/issues/8700, where no foreign key meta information is produced by jOOQ's code generator.
