### ISSUE TITLE
Trim switch inconsistent wrt SQL dialects

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8699]
The implementation of `Trim` does a switch over `configuration.dialect()` but then the cases reference families (e.g. `SQLITE`). This needs to be corrected by adding cases for the dialect versions (e.g. `SQLITE_3_25`).

**Comment by lukaseder** [comment]
Very nice catch! I wonder if we can automate the detection of such a regression. It is introduced usually when a family starts getting new versions (but didn't have dialect versions before)...

**Comment by knutwannheden** [comment]
Yes, I was thinking if we for example could use the Checker framework for this.

**Comment by lukaseder** [comment]
> Yes, I was thinking if we for example could use the Checker framework for this.

How would that work? Notice that the checker framework, very regrettably, only supports JDK 8 (still!). Error Prone is more promising.

**Comment by knutwannheden** [comment]
I am not exactly sure what can be done with either of these frameworks. But I was hoping we could implement a check to make sure that every switch over an expression which in the end accesses `Configuration#dialect()` not only contains a case for the dialect (where version specific literals exist).
