### ISSUE TITLE
Add DSL#log(Field, Field) overload

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8703]
The current `DSL#log()` overloads (`log(Number, int)` and `log(Field, int)`) don't allow for the computation of logarithms where the base is a floating point value or some arbitrary expression (as in e.g. `LOG(LENGTH('AA'), 4)`). Many dialects support this, so in order to allow the parser to parse such expressions a new `DSL#log(Field, Field)` overload is required.

**Comment by knutwannheden** [comment]
For the new overload we still need to work out what the `@Support` list should look like.

**Comment by lukaseder** [comment]
> we still need to work out what the @Support list should look like.

A pragmatic approach in this case is to duplicate the one from the existing methods, and then fix bugs as we encounter them with tests.

**Comment by knutwannheden** [comment]
> A pragmatic approach in this case is to duplicate the one from the existing methods, and then fix bugs as we encounter them with tests.

That's what I did for now. Automated tests should then help us here.
