### ISSUE TITLE
Work around Vertica's incorrect IS NOT NULL implementation

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8709]
The following statement:

```sql
SELECT (1, null) IS NOT NULL;
```

Should produce `false` according to the SQL standard:

![image](https://user-images.githubusercontent.com/734593/58485542-8cc5d980-8164-11e9-89f0-9c59e8a3bce2.png)

In Vertica 8.1.1, however, it produces `true`. Perhaps this has been fixed in a newer version of Vertica, but to stay on the safe side, we should revert to emulating the predicate for Vertica, rather than using the native syntax.

**Comment by knutwannheden** [comment]
Will you report this as a bug against Vertica?

**Comment by lukaseder** [comment]
> Will you report this as a bug against Vertica?

I'm still investigating if this is still the case with Vertica 9. I have 8 here.

**Comment by lukaseder** [comment]
Note that Cubrid and HSQLDB also implement it wrong...

**Comment by knutwannheden** [comment]
:-(

**Comment by lukaseder** [comment]
OK, reported here: https://forum.vertica.com/discussion/240641/null-predicate-does-not-behave-according-to-the-sql-standard-and-e-g-postgresql#latest

**Comment by katzyn** [comment]
All released versions of H2 also have the same problem with both `rowValue IS NULL` and `rowValue IS NOT NULL`.

The next version will not be affected:
https://github.com/h2database/h2database/pull/1956

**Comment by lukaseder** [comment]
Thanks, @katzyn. I think I had noticed this flaw at some point, and simply reverted to emulating the `<rve> IS [ NOT ] NULL` predicate in H2.

Good to know that it will be implemented correctly, soon. I've added a reminder to upgrade jOOQ to use native support in H2, when we officially support that version: https://github.com/jOOQ/jOOQ/issues/8719
