### ISSUE TITLE
Supports an prowerful  pagination tool

### ISSUE THREAD

**Issue by fangjinuo** [jOOQ/jOOQ#8712]
[Here](https://github.com/fangjinuo/sqlhelper) is a powerful sql pagination tool，it supports almost all RMDBs，and working with many ORM framework ，so I wish it will be used in JOOQ .

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. And congratulations on publishing your OSS project. I remember the days when I first created jOOQ 11 years ago. How to get started? How to get traction? Who will build upon my work?

Of course, you are well aware that a new pagination tool like yours is *much more* likely to build on something established like jOOQ, and that we currently do not have any need to build upon a "pagination tool". Evidently, jOOQ is about much more than pagination, and if there's any flaw in our own implementations (offset *and* keyset pagination), we'll be quick to fix it. If you know of any such flaws, please let us know.

Nevertheless, I appreciate your efforts to reach out to other products, and I wish you the best of luck with your future endeavours.
