### ISSUE TITLE
Add a typescript version of jooq with typesafe sql and ddl

### ISSUE THREAD

**Issue by xialvjun** [jOOQ/jOOQ#8713]
### Use case:

```sh
; just like knex
npx jooq migrate make -n init_database
npx jooq migrate --latest -c connection_string

npx jooq types -c connection_string -o ./src/dbt.ts
```

```ts
// timestamp_init_database.ts
import jooq from 'jooq';

export async function up(db: jooq.DB<PG>) {}
export async function down(db: jooq.DB<PG>) {}
```

```ts
// index.ts
import jooq from 'jooq';

import {BOOK, dialect} from './dbt';
// dialect is of type enum Dialect { PG, MYSQL, ... }
const db: jooq.DB<PG> = jooq({ debug: true, dialect })(`postgres://username:password@host:port/db`);

(async () => {
  const books = await db.select(BOOK.TITLE)
      .from(BOOK)
      .where(BOOK.PUBLISHED_IN.eq(2011))
      .orderBy(BOOK.TITLE);
  console.log(books.length);
})();
```

**TypeScript has a much more powerful type system than java, I believe jooq can do more things in it and shock the world.**

**Comment by lukaseder** [comment]
Thank you very much for your suggestions. I have already prototyped this particular language integration. Typescript does indeed offer a few very attractive language features for a DSL like jOOQ, mainly:

- Named and defaulted parameters
- Structural typing
- First class union and intersection types

Alas, supporting new languages is a very big project, and there would be more interesting target languages first, with larger markets, before Typescript, such as e.g. C#, C++, PHP.

We'll eventually tackle this challenge and offer jOOQ on a variety of other platforms, but I cannot make any promises about when this will happen.

**Comment by alamothe** [comment]
Are there any updates here?

The whole JVM ecosystem seems kind of stuck and many projects are migrating to node+TypeScript. We really want to migrate too, if JOOQ was available we would have already.

**Comment by xialvjun** [comment]
@alamothe  https://github.com/juanluispaz/ts-sql-query  you can have a look.

**Comment by lukaseder** [comment]
What's your budget, @alamothe?

**Comment by AlbertLacambraNexplore** [comment]
@alamothe when facing the same problem we used  https://github.com/juanluispaz/ts-sql-query . Never regret it.

**Comment by dangnhdev** [comment]
After tried prisma and typeorm I missed jooq so much.

**Comment by lukaseder** [comment]
@dangnhdev Come back to the JVM!
