### ISSUE TITLE
Add support for the LOG10 function

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8715]
SQL Server provides a `LOG10()` function as of version 2008 which is used to compute the logarithm of a given float value in base 10: https://docs.microsoft.com/en-us/sql/t-sql/functions/log10-transact-sql?view=sql-server-2017. This could be implemented by jOOQ and also be emulated for all other dialects.

Also the SQL parser should understand `LOG10()`.

As a "workaround" it is of course already today to write `log(<x>, 10)` instead of `log10(<x>)`.

**Comment by knutwannheden** [comment]
Derby also has a `LOG10()` function. As Derby doesn't have a `LOG()` function accepting a `base` parameter, it might be interesting to add this DSL API.

**Comment by lukaseder** [comment]
Many dialects actually don't accept a `base` parameter, including:

- Access
- DB2
- Derby
- H2
- HSQLDB
- Informix
- Ingres
- Sybase ASE
- Sybase SQL Anywhere
- Teradata

Perhaps, others also have a native `LOG10` function...

**Comment by lukaseder** [comment]
Dialects with native `LOG10` support:

- [x] Access
- [x] Db2
- [x] Firebird
- [x] H2
- [x] HSQLDB
- [x] Informix
- [x] MariaDB
- [x] MemSQL
- [x] MySQL
- [x] PostgreSQL
- [x] Redshift (it's called `LOG` there)
- [x] SQL Server
- [x] SQL Data Warehouse
- [x] Sybase ASE
- [x] Sybase SQL Anywhere
- [x] Teradata (it's called `LOG` there) 
- [x] Vertica
