### ISSUE TITLE
Support DSL#md5() for SQL Server

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8716]
SQL Server's `HASHBYTES()` should be used to implement `DSL#md5()`: https://docs.microsoft.com/en-us/sql/t-sql/functions/hashbytes-transact-sql?view=sql-server-2017

**Comment by lukaseder** [comment]
Cool. I wonder if we should offer any other hashing algorithms. `MD5()` has long ago lost its cryptographic "attractiveness", although it is still useful for simple and fast hashing.

Not supporting the other ones might look like we're actually suggesting to use `MD5()` instead.

**Comment by knutwannheden** [comment]
Yes, we should probably have an issue for that. We should investigate whether it is now common practice to have a "dispatcher" function like `HASHBYTES()` or `DBMS_CRYPTO.HASH()` and in that case go down that route.

**Comment by lukaseder** [comment]
> Yes, we should probably have an issue for that. We should investigate whether it is now common practice to have a "dispatcher" function like HASHBYTES() or DBMS_CRYPTO.HASH() and in that case go down that route.

There probably are many dialects with such functions. But the algorithm description might not always be the same (e.g. `SHA1` vs `sha1` vs `sha-1`...)

**Comment by knutwannheden** [comment]
SQL Server supports MD2, MD4, MD5, SHA, SHA1, SHA2_256, and SHA2_512 via `HASHBYTES()`. All but the last two are marked as deprecated as of version 2016, but will continue working.

In MySQL there are dedicated functions for MD5, SHA, SHA1, and SHA2, none of which are deprecated and `SHA2()` accepts an optional hash-length parameter to compute the SHA-224, SHA-256, SHA-384, and SHA-512 hashes.

**Comment by knutwannheden** [comment]
Since `DSL#md5()` now works for SQL Server I close this issue. I created a new issue for the support of other hash functions.
