### ISSUE TITLE
Wrong SQL generated when using qualified index references with H2 CREATE or DROP INDEX statements

### ISSUE THREAD

**Issue by masc3d** [jOOQ/jOOQ#8723]
### Expected behavior and actual behavior:

Index operations like `dropIndex` fail as table name is included in statement, which is invalid for h2 and causes syntax error.

### Steps to reproduce the problem

execute eg. `dropIndex(Index)` using generated jooq classes for h2.

when performing `dropIndex` using index instance from `meta()` it works, as those indexes are correctly qualified for h2.

issue also occurs with `createIndex(Index)` for same reason, possibly other operations are affected as well.

### Versions:

- jOOQ: 3.11.11
- Java: 10.0.2
- Database (include vendor): h2-1.4.199
- OS: macos-10.14.5
- JDBC Driver (include name if inofficial driver): h2-1.4.1.99

**Comment by masc3d** [comment]
a workaround is to re-create the index before executing statement eg
```kotlin
    /**
     * TODO workaround for #jooq-8723, invalid qualified names for h2 indexes
     */
    fun Index.fixed(): Index {
        return Internal.createIndex(
            DSL.name(listOf(this.table.schema.name, this.name)),
            this.table,
            this.fields.toTypedArray(),
            this.unique
        )
    }

```

**Comment by lukaseder** [comment]
Thank you very much for your report. Indeed, I can reproduce this as well. The easiest workaround is to drop the index by name:

```java
ctx.dropIndex(index.getUnqualifiedName()).execute();
```

**Comment by masc3d** [comment]
> Or to qualify it with the schema explicitly, if not in the public schema.

yes, classes are actually generated with
```
.withInputSchema('PUBLIC')
.withOutputSchema("PUBLIC")
```
unqualified more simple for `dropIndex` yes, but actually need to re-`createIndex` lateron.

**Comment by lukaseder** [comment]
> but actually need to re-createIndex lateron.

The same workaround applies in that case:

```java
ctx.createIndex(index.getUnqualifiedName()).on(index.getTable(), index.getFields()).execute();
```

**Comment by masc3d** [comment]
> ```java
> ctx.createIndex(index.getUnqualifiedName()).on(index.getTable(), index.getFields()).execute();
> ```

does it work with unique though?

**Comment by lukaseder** [comment]
```java
if (index.getUnique())
  ctx.createUniqueIndex(index.getUnqualifiedName()).on(index.getTable(), index.getFields()).execute();
else
  ctx.createIndex(index.getUnqualifiedName()).on(index.getTable(), index.getFields()).execute();
```

**Comment by masc3d** [comment]
that was quick! thanks @lukaseder 😊

**Comment by lukaseder** [comment]
You're welcome.

Other dialects are affected as well, but possibly in different ways. E.g. in MySQL, it's not possible to qualify an index name directly, only via the `ON` clause - meaning an index cannot reside in a different schema than the corresponding table.

**Comment by lukaseder** [comment]
This seems to have introduced a regression: https://github.com/jOOQ/jOOQ/issues/9414
