### ISSUE TITLE
Support Oracle Reactive Streams Ingestion

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8725]
This is a new performance extension in the new 19c driver: https://docs.oracle.com/en/database/oracle/oracle-database/19/jjdbc/high-speed-ingestion-of-data-streams.html

**Comment by lukaseder** [comment]
Interesting, I was not aware of this improvement. It seems orthogonal to Oracle's efforts around ADBA.

> The use of this interface is transparent to the end user and you need to make very little change to your application code for performing a direct path load operation.

Do we really need to do anything to support that? It looks as though a JDBC proxy could intercept our `prepareStatement()` calls and replace them by `prepareDirectPath()`.

To me, this doesn't look like something where cost / benefit is in a good ratio, compared to investing more time in supporting ADBA (and R2DBC) directly. See e.g. https://github.com/jOOQ/jOOQ/issues/4371

**Comment by lukaseder** [comment]
> To me, this doesn't look like something where cost / benefit is in a good ratio

In other words, I would definitely want to wait for a paying customer to request this feature explicitly.
