### ISSUE TITLE
Licensing: jOOQ Aurora MySql and non-Aurora MySql differences

### ISSUE THREAD

**Issue by rajanadar** [jOOQ/jOOQ#8726]
### Your question:
Since AWS Aurora promises compatibility between Aurora MySql and non-Aurora MySql for a client application, why can't we use 'jOOQ Open Source Edition' to do Aurora MySql as well?

Are there technical differences in jOOQ or is that a licensing concern?

e.g. If a client application were to set the jOOQ dialect to MySql (not Aurora_MySql) and use it to connect to Aurora MySql, would that result in technical issues OR is that a licensing concern of an open-source-edition being used instead of the professional-edition?

**Comment by lukaseder** [comment]
Thank you very much for your question.

> why can't we use 'jOOQ Open Source Edition' to do Aurora MySql as well?

You can

> Are there technical differences in jOOQ or is that a licensing concern?

We do not officially support this integration, but the jOOQ Open Source Edition can be used for whatever purpose you want, as long as you adhere to the ASL 2.0 license. (https://www.apache.org/licenses/LICENSE-2.0.html)

> e.g. If a client application were to set the jOOQ dialect to MySql (not Aurora_MySql) and use it to connect to Aurora MySql, would that result in technical issues

There may be technical issues, indeed. We do not formally support this integration. For best results, we recommend you use the jOOQ Professional Edition and the `SQLDialect.AURORA_MYSQL` dialect.

I hope this helps

**Comment by rajanadar** [comment]
thanks for the quick response @lukaseder
