### ISSUE TITLE
DSL#localDateTime(LocalDateTime) drops fractional seconds on SQLite

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8730]
When using `DSL#localDateTime(LocalDateTime)` with SQLite the returned result never has any fractional seconds. This is because the `LocalDateTime` is not simply rendered as as string literal (as in the `timestamp(Date)` case), but as a call to the `datetime()` function (see code in class `DateOrTime`). This can easily be fixed by simply changing the problematic method to return `Tools.field(value)`.

**Comment by lukaseder** [comment]
It appears that `DSL.localTime(LocalTime)` might also be affected. `DSL.localDate(LocalDate)` doesn't have the problem, but still unnecessarily wraps the bind value in `org.jooq.impl.DateOrTime`

**Comment by lukaseder** [comment]
Also affected: `DSL.offsetTime(OffsetTime)` and `DSL.offsetDateTime(OffsetDateTime)`

**Comment by knutwannheden** [comment]
Also affected: `DSL.instant(Instant)`
