### ISSUE TITLE
Support DSL#offset[Date]Time() and DSL#instant() for SQLite

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8735]
SQLite supports date, date-time, and time types using the `date()`, `datetime()`, and `time()` built-in functions, which are already used by jOOQ. These functions also support offset time zones, which means that these can be used to support the Java 8 `Offset[Date]Time` types.

It should be noted that the `datetime()` and `time()` functions don't return any fractional seconds, so instead the `strftime()` function should be used. At least for OffsetDateTime until OffsetTime can be supported (see #8733). See here for SQLite details: https://www.sqlite.org/lang_datefunc.html.

**Comment by lukaseder** [comment]
Very nice. Now that these methods are supported, the question arises whether all the other JSR-310 / Java 8 time API features are supported too, for SQLite?

**Comment by knutwannheden** [comment]
Well, casting of date and time types still needs to be implemented properly for SQLite. I also found that there are some corner cases where date arithmetic doesn't yield the expected results. E.g. `'2012-02-29' + 1 year` yields `2013-03-01` whereas jOOQ (and SQL standard I suppose?) expects `2013-02-28`.
