### ISSUE TITLE
Avoid catching NumberFormatException when parsing potential numbers

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8736]
jOOQ currently uses `Integer#parseInt(String)` in some places and then has some fallback logic in case of a `NumberFormatException`. An example of this is `Tools#renderAndBind()` which is in fact used quite frequently.

Having some method like `Tools#tryParseInt(String)` returning an `Integer` (which would be `null` if the string cannot be parsed as a base-10 integer) similar to Guava's `Longs#tryParse(String)` would be nice. It should both perform better as no stack traces need to be built (although this is of course negligible compared to I/O time) and also the application would be throwing fewer exceptions (which is "flagged" by some profilers).

**Comment by knutwannheden** [comment]
Using a custom `tryParseInt()` instead of `Integer#parseInt()` yields better performance. The throughput is around 300 times higher when parsing a list of 20K strings like this: `[10000000, 10000000-, 10000001, 10000001-, 10000002, 10000002-, ...]`. I.e. every second element won't parse on the last char.

```
Benchmark                  Mode  Cnt     Score     Error  Units
ParseInt.testParseInt     thrpt   21    64.247 ±   8.507  ops/s
ParseInt.testTryParseInt  thrpt   21  1813.628 ± 108.674  ops/s
```

**Comment by lukaseder** [comment]
Nice. Did you post the benchmark code somewhere, or can you post it here?

Also, it would be interesting to see numbers when there are no bad input strings to compare the happy paths (which is mostly applicable)

**Comment by knutwannheden** [comment]
The benchmark will be in the repository, but I can also post it somewhere.

As explained above the array contains 50% "bad" strings all interleaved with the "good" strings.

**Comment by lukaseder** [comment]
> The benchmark will be in the repository, but I can also post it somewhere.

That would be great. In the past, having example snippets available also helped community members report related issues that we might have overlooked.

> As explained above the array contains 50% "bad" strings all interleaved with the "good" strings.

I understand. It's great to see that we're improving in this particular case. But that's probably an edge case. In most cases, we'll be on the happy path where 99.9% of all strings are parseable numbers. I would like to see if we're going to have a regression in that area.

**Comment by knutwannheden** [comment]
> I understand. It's great to see that we're improving in this particular case. But that's probably an edge case. In most cases, we'll be on the happy path where 99.9% of all strings are parseable numbers. I would like to see if we're going to have a regression in that area.

I see. For the case of `Tools#renderAndBind()` I assumed a 50-50 distribution would be about right and for `DefaultBinding#parse(Class, String)` (used to parse SQLITE dates and times) I expect the distribution to be even further away from the happy path, as I expect dates more often to be represented in string form. This being said it of course still makes sense to test the happy path.

**Comment by knutwannheden** [comment]
`HAPPY_PATH` means 100%, `EVEN_SPLIT` is 50%, and `SAD_PATH` is 0% parseable values:

```
Benchmark                             (distribution)   Mode  Cnt     Score      Error  Units
ParseIntBenchmark.testIntegerValueOf      HAPPY_PATH  thrpt    5  4220.672 ± 1267.448  ops/s
ParseIntBenchmark.testIntegerValueOf      EVEN_SPLIT  thrpt    5   142.986 ±    7.836  ops/s
ParseIntBenchmark.testIntegerValueOf        SAD_PATH  thrpt    5    77.191 ±    7.297  ops/s
ParseIntBenchmark.testTryParseInt         HAPPY_PATH  thrpt    5  4685.361 ±  345.036  ops/s
ParseIntBenchmark.testTryParseInt         EVEN_SPLIT  thrpt    5  4082.392 ±  493.595  ops/s
ParseIntBenchmark.testTryParseInt           SAD_PATH  thrpt    5  4437.445 ±   44.599  ops/s
```

**Comment by knutwannheden** [comment]
Benchmark and implementation code can be seen here: https://gist.github.com/knutwannheden/46a6982f45421e91824d3ccd5934c1e3.

**Comment by lukaseder** [comment]
> I see. For the case of Tools#renderAndBind() I assumed a 50-50 distribution would be about right

Oh wow, indeed. Nice catch! Would be interesting to see a before/after benchmark on some arbitrary jOOQ SQL generation of a query that uses some plain SQL templating internally...

We could probably improve a few other things in the implementation of plain SQL templating.

>  I expect the distribution to be even further away from the happy path, as I expect dates more often to be represented in string form. This being said it of course still makes sense to test the happy path.

You're right. I had `Convert` logic in mind, which uses the same technique

> HAPPY_PATH means 100%, EVEN_SPLIT is 50%, and SAD_PATH is 0% parseable value

No regression, but clear win. Great news!

**Comment by lukaseder** [comment]
This issue is a candidate for backporting to 3.11.12. I'll review this more thoroughly tomorrow

**Comment by knutwannheden** [comment]
OK. And let's also see if we can find some more cases where we want to use this technique rather than dealing with `NumberFormatException`.

**Comment by lukaseder** [comment]
Yes. Maybe even under this same issue?

**Comment by knutwannheden** [comment]
> Yes. Maybe even under this same issue?

Yes, I will reopen this one until we have concluded the investigation.

**Comment by knutwannheden** [comment]
One minor improvement that comes to mind would be to offer a `tryParseInt()` overload with additional `offset` and `length` parameters. This would help slightly on the "happy path" in `renderAndBind()` as we could then skip the extra `String#substring()` call.

**Comment by lukaseder** [comment]
>  as we could then skip the extra String#substring() call.

That sounds like a major improvement to me :-)

**Comment by knutwannheden** [comment]
Let me look into it.

**Comment by knutwannheden** [comment]
Looking at the other cases in `Convert` where we catch `NumberFormatException` where we typically use `BigDecimal(String)` as in:

```java
try {
    return (U) Byte.valueOf(new BigDecimal(from.toString().trim()).byteValue());
}
catch (NumberFormatException e) {
    return Reflect.initValue(toClass);
}
```

We could of course here also use `tryParseInt()`. That would probably improve the performance in case the value to convert indeed represents a number. But if it doesn't or the number has a fractional part we would still have to resort to `BigDecimal(String)`. So I am a bit unsure about this one, but I guess it can't really hurt to first try with `tryParseInt()` (or `tryParseLong()`). Any thoughts?

**Comment by knutwannheden** [comment]
What also bothers me a bit about the conversion like the one shown in the previous comment is the *narrowing primitive conversion* being performed, which can lose information or lead to the opposite sign. Is this intentional or an oversight?

**Comment by lukaseder** [comment]
> but I guess it can't really hurt to first try with tryParseInt() (or tryParseLong()). Any thoughts?

When we reach this code, we *probably* have a number in `String` form, and it is *probably* an integer number without fractional part, as we're about to convert it to `Byte`, which is also an integer number. Otherwise, we'd get a rounding error.

Of course, users might be aware of this and desire exactly this behaviour, but I'd say that 60% - 80% will want to convert some integer value in string form to actual integer types. So we'll gain a lot by not instantiating the `BigDecimal` for those people while we don't lose too much for the others.

The workaround to improve speed is always to implement a custom data type binding and intercept jOOQ behaviour on the JDBC level, where the appropriate mapping between whatever the DB type is and the `Byte` type can be done very early on, which would even prevent allocating the intermediate string.

So, I do approve of this kind of change.

> Edit: Some use cases relying on conversions like the one above: When casting strings to number types (e.g. using cast()) 

The cast should be done by the database. Did you maybe have something else in mind?

> or when using the Loader to load CSV data where there are number-typed fields, as the Loader calls DataType#convert(Object).

Yes that's one place where conversion is being done. There are many other places.

> What also bothers me a bit about the conversion like the one shown in the previous comment is the narrowing primitive conversion being performed, which can lose information or lead to the opposite sign. Is this intentional or an oversight?

This works by design and can be reviewed in the next major release, e.g. through https://github.com/jOOQ/jOOQ/issues/4681

**Comment by knutwannheden** [comment]
AFAICT we can now close this issue. Please reopen if I missed something.

**Comment by lukaseder** [comment]
Yes, I agree
