### ISSUE TITLE
Add Settings.(execute|record)Listener(Start|End)InvocationOrder to support LIFO ordering on end() events

### ISSUE THREAD

**Issue by epkugelmass** [jOOQ/jOOQ#8740]
### Use case:

I'd like to use ExecuteListener in ways that emulate the LIFO semantics of traditional interceptor or filter APIs. Put differently, invocation order of ExecuteListeners for a particular start/end phase pair (render, bind, fetch, etc.) should be reversed. If there are two Listeners A and B, then I would like the invocation order to be A.renderStart, B.renderStart, B.renderEnd, A.renderEnd. The current behavior is A.renderStart, B.renderStart, A.renderEnd, B.renderEnd.

LIFO semantics play better with ThreadLocal resource management, which is heavily leveraged by Spring and other frameworks.

### Possible solution you'd like to see:

org.jooq.impl.ExecuteListeners#prepareEnd and similar methods iterate through delegate Listeners in reverse order.

A much heavier solution would be an alternative ExecuteInterceptor API that looks more like javax.servlet.Filter or io.grpc.Client/ServerInterceptor.  

### Possible workarounds:

Users rework ExecuteListeners to handle the current invocation order. This is not always possible because ThreadLocal state is used in third-party libraries (e.g. Spring) and the user-written ExecuteListener is only a bridge.

### Versions:

- jOOQ: 3.11.8
- Java: 11.0.2
- Database (include vendor): MySQL 5.6
- OS: Mac 10.14.4
- JDBC Driver (include name if inofficial driver): MySQL Connector 5.1.39

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I see your point, and don't disagree.

Of course, we cannot simply change the existing behaviour, as people may rely on 2x FIFO iterations both for `start` and `end` events. But we could definitely introduce a new `Settings` enum that specifies the iteration order. For now, I'd suggest:

- `ExecuteListenerInvocationOrder.FIFO_START_FIFO_END` (the default)
- `ExecuteListenerInvocationOrder.FIFO_START_LIFO` (what you're requesting)

**Comment by lukaseder** [comment]
Or, we could have two `InvocationOrder` references, one for each `start()` and `end()` events. Perhaps that's cleaner and more versatile, and leaves room to possibly ordering the invocation for exceptions as well, in the future.

**Comment by lukaseder** [comment]
In fact, yes, a generic `InvocationOrder` is more desireable, because this change also applies to `RecordListener` invocations

**Comment by lukaseder** [comment]
At this point, the terms `FIFO` and `LIFO` become unclear. I think I prefer `DEFAULT` and `REVERSE`

**Comment by lukaseder** [comment]
... Also: `TransactionListener` and `VisitListener`

**Comment by lukaseder** [comment]
I simplified the description of the feature request in a new issue, which I'll implement right away: https://github.com/jOOQ/jOOQ/issues/8746

Closing this as a duplicate. Thanks again for your suggestion!

**Comment by lukaseder** [comment]
This is now implemented in jOOQ 3.12 through #8746

**Comment by epkugelmass** [comment]
Thank you so much Lukas. Excited for 3.12.0 to come out.
