### ISSUE TITLE
Add Settings.(execute|record|transaction|visit)Listener(Start|End)InvocationOrder to support REVERSE ordering on end() events

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8746]
In some situations, the existing "FIFO" ordering of listeners for both `[action]Start()` *and* `[action]End()` events is not always the most suitable. Sometimes, users wish to have jOOQ iterate over their listeners in reverse order for `end()` events. See rationale here: https://github.com/jOOQ/jOOQ/issues/8740

This new feature will add a new `InvocationOrder` enum with values `DEFAULT` (as it is today) and `REVERSE` (as requested), which can be applied to all of:

- [x] `ExecuteListener` `start` and `end` events individually
- [x] `RecordListener` `start` and `end` events individually
- [x] `TransactionListener` `start` and `end` events individually
- [x] `VisitListener` `start` and `end` events individually

----
See also: https://github.com/jOOQ/jOOQ/issues/8740

**Comment by knutwannheden** [comment]
Alternatively, we could as a first step only support two out of four possibilities:
* Invoking both `start` and `end` events on listeners in order
* Invoking `start` events in order and `end` events in reverse listener order

**Comment by lukaseder** [comment]
See discussion here, and why I opted against it: https://github.com/jOOQ/jOOQ/issues/8740

**Comment by lukaseder** [comment]
The current implementation is checking if a given `InvocationOrder` setting is the `DEFAULT`. We should better check the inverse, if it is `REVERSE` and act accordingly. That way, both `DEFAULT` and `null` have the `DEFAULT` behaviour.
