### ISSUE TITLE
Improve rendering performance of SQL templates

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8751]
Many parts of jOOQ's query rendering rely on the rendering of keywords as implemented by `Tools#renderAndBind()` and the logic in `KeywordImpl`. One performance problem with the latter is that it up-front renders the keyword in all supported styles: AS_IS, LOWER, UPPER, and PASCAL. Typically only one of these will end up being used, so it would make sense to do the rendering lazily. This will also save some memory.

A JMH test shows that when rendering a specific test query (tailored to highlight this problem, see below), the throughput can be increased by some 10% by rendering the non AS_IS styles lazily.

Measurements with original `KeywordImpl` implementation:

```
Benchmark                            (keywordStyle)   Mode  Cnt    Score    Error  Units
SQLRenderingBenchmark.testRenderSQL           AS_IS  thrpt   10  506.968 ± 19.177  ops/s
SQLRenderingBenchmark.testRenderSQL           UPPER  thrpt   10  471.848 ± 21.253  ops/s
```

Measurements with lazy implementation:
```
Benchmark                            (keywordStyle)   Mode  Cnt    Score     Error  Units
SQLRenderingBenchmark.testRenderSQL           AS_IS  thrpt   10  556.058 ±  62.828  ops/s
SQLRenderingBenchmark.testRenderSQL           UPPER  thrpt   10  497.088 ± 105.860  ops/s
```

Here is the test query that was used for the testing:

```java
    static Select<?> query(DSLContext ctx) {
        Field<?>[] fields = new Field[1000];
        for (int i = 0; i < fields.length; i++)
            fields[i] = DSL.substring(val("string"), 1, 3);
        return ctx.select(fields);
    }
```

**Comment by knutwannheden** [comment]
By further optimizing the logic of `Tools#renderAndBind()` discerning between keywords and bind vale indexes, the throughput of the SQL rendering can be further increased by another 15% or so:

```
Benchmark                            (keywordStyle)   Mode  Cnt    Score    Error  Units
SQLRenderingBenchmark.testRenderSQL           AS_IS  thrpt   10  651.452 ± 12.786  ops/s
SQLRenderingBenchmark.testRenderSQL           UPPER  thrpt   10  612.181 ± 22.264  ops/s
```

**Comment by lukaseder** [comment]
> discerning between keywords and bind vale indexes

By this you mean avoiding the `substring()` call (as in the commits)? Or is there something else you've changed?

**Comment by lukaseder** [comment]
Another benchmark worth exploring would check if using ordinary API using `Context.sql()` and `Context.visit()` calls might be faster. We don't *have to* use plain SQL templating internally

**Comment by knutwannheden** [comment]
> By this you mean avoiding the substring() call (as in the commits)? Or is there something else you've changed?

Yes, that's what I mean.

> Another benchmark worth exploring would check if using ordinary API using Context.sql() and Context.visit() calls might be faster. We don't have to use plain SQL templating internally

Sounds interesting.

**Comment by knutwannheden** [comment]
I am also wondering a bit if it really pays off to call `String#toCharArray()` at the beginning of `Tools#renderAndBind()` instead of using `String#charAt()` everywhere. But testing that would take quite a bit of work, so I guess it isn't worth it.

**Comment by knutwannheden** [comment]
> Another benchmark worth exploring would check if using ordinary API using Context.sql() and Context.visit() calls might be faster. We don't have to use plain SQL templating internally.

So instead of something like:
```java
DSL.field("{substring}({0} {from} {1})", SQLDataType.VARCHAR, args)
```
we would have:
```java
ctx.visit(K_SUBSTRING).sql('(').visit(args[0]).sql(' ').visit(K_FROM).sql(' ').visit(args[1]).sql(')')
```
That is definitely more work, but could be well worth it for some frequently used SQL templates.

In the JMH test I have been testing with this would look as follows:
```
Benchmark                            (keywordStyle)   Mode  Cnt    Score    Error  Units
SQLRenderingBenchmark.testRenderSQL           AS_IS  thrpt   10  785.304 ± 41.364  ops/s
SQLRenderingBenchmark.testRenderSQL           UPPER  thrpt   10  816.680 ± 60.939  ops/s
```

**Comment by knutwannheden** [comment]
I close this issue and we can then create a separate issue if we think we should be using `visit()` and `sql()` directly in some implementation classes, as this isn't directly related to this issue.

**Comment by lukaseder** [comment]
> I am also wondering a bit if it really pays off to call String#toCharArray() at the beginning of Tools#renderAndBind() instead of using String#charAt() everywhere. But testing that would take quite a bit of work, so I guess it isn't worth it.

I think that one of the reasons I did that was that `String#charAt()` appeared in profiling sessions excessively. Of course, this is probably due to some savepoints, and just a profiling artefact, not necessarily a performance issue.

> That is definitely more work, but could be well worth it for some frequently used SQL templates.
>
> In the JMH test I have been testing with this would look as follows [...]

Impressive!

> I close this issue and we can then create a separate issue if we think we should be using visit() and sql() directly in some implementation classes, as this isn't directly related to this issue.

Yes, I do think we should tackle this, even if it is much more work. When templating was first applied everywhere in the internals, there were much fewer `QueryPart` implementations, which made the templating so convenient. But now that we have all the `QueryPart`s (e.g. `Keyword`), we can try to avoid templating. I'll create a separate issue soon.

**Comment by knutwannheden** [comment]
OK.

I found one more place which we can use to increase performance slightly: By changing the body of `DefaultIntegerBinding#sqlInline0()` from `ctx.render().sql(value.toString());` to `ctx.render().sql(value);`. I will create one more commit for that.

**Comment by lukaseder** [comment]
Ah, because we can bypass the formatting logic? Perhaps that's another case for an entirely new issue. Add `sql()` overloads for all sorts of numeric data types, and then check the entire code base for opportunities where we could bypass the formatting logic.

**Comment by knutwannheden** [comment]
Also note that `AbstractStringBuilder#append(int)` has an optimized implementation relying on package private methods, which will thus perform better than first converting the `Integer` to a `String`.

**Comment by lukaseder** [comment]
Hah, yes. Nice. So we win twice for those cases. Probably an edge case, globally, but if someone does a lot of `DSL.inline()`, it might be useful. I've created a new, separate issue for this: https://github.com/jOOQ/jOOQ/issues/8753

It includes:

- Adding the new API that delegates to optimised `StringBuilder` methods
- Making sure the new (and existing) API is used thoroughly, rather than passing `toString()` versions of primitives to the `Context.sql()` API.

**Comment by lukaseder** [comment]
Regarding the improvement mentioned here: https://github.com/jOOQ/jOOQ/issues/8751#issuecomment-499535008, where we would replace plain SQL templating by `Context.sql()` and `Context.visit()` API calls, I've created a separate issue for this:

https://github.com/jOOQ/jOOQ/issues/8754
