### ISSUE TITLE
Add additional Context.sql(long), sql(float), sql(double)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8753]
Both jOOQ's `DefaultRenderContext`, and the `StringBuilder` implementation have optimised versions for serialising *some* non-String values. We should add relevant API (we already have `sql(int)`) and thoroughly use it throughout the code base

**Comment by knutwannheden** [comment]
I propose to not add a new `sql(boolean)` method, as I think `true` and `false` would typically be expected to be treated as keywords and as such follow the keyword rendering style. Please reopen if you disagree.

**Comment by lukaseder** [comment]
Yes you're right. Also, the logic of whether booleans really exist or should be emulated using `1` and `0` should not reside in the `Context`
