### ISSUE TITLE
Avoid using plain SQL templating, internally

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8754]
Internally, we have a lot of plain SQL templating usage, such as for example in `org.jooq.impl.Substring`. The `FIREBIRD` implementation looks like this:

```java
DSL.field("{substring}({0} {from} {1} {for} {2})", SQLDataType.VARCHAR, getArguments());
```

This is convenient because it is a bti more readable than constructing the same thing through the `Context` API:

```java
ctx.visit(K_SUBSTRING).sql('(').visit(arg0).sql(' ').visit(K_FROM).sql(' ').sql(' ').visit(arg1).sql(' ').visit(K_FOR).sql(' ').visit(arg2).sql(')')
```

But a simple benchmark shows a 20% improvement by the latter over the former. Previous benchmark (after some plain SQL templating improvements have already been applied): https://github.com/jOOQ/jOOQ/issues/8751#issuecomment-499500402

```
Benchmark                            (keywordStyle)   Mode  Cnt    Score    Error  Units
SQLRenderingBenchmark.testRenderSQL           AS_IS  thrpt   10  651.452 ± 12.786  ops/s
SQLRenderingBenchmark.testRenderSQL           UPPER  thrpt   10  612.181 ± 22.264  ops/s
```

After replacing plain SQL templating by ordinary `Context` API usage

```
Benchmark                            (keywordStyle)   Mode  Cnt    Score    Error  Units
SQLRenderingBenchmark.testRenderSQL           AS_IS  thrpt   10  785.304 ± 41.364  ops/s
SQLRenderingBenchmark.testRenderSQL           UPPER  thrpt   10  816.680 ± 60.939  ops/s
```

The benchmark actually uses the 2-argument version without the `K_FOR` and `arg[2]` as shown above.

Improving this will definitely help a variety of SQL generation situations, especially when a lot of column expressions / functions / emulations are projected or otherwise involved in generated SQL.

----
This is a big change so we will not backport it to older versions

**Comment by knutwannheden** [comment]
Most SQL templating in jOOQ has now been removed. There are still some cases left which are not that easy to refactor.

**Comment by knutwannheden** [comment]
There is some more SQL templating in `IsDistinctFrom`: https://github.com/jOOQ/jOOQ/blob/17c38715258582c527348e2f4376338f480c50b8/jOOQ/src/main/java/org/jooq/impl/IsDistinctFrom.java#L131-L138

@lukaseder But why is the `mySQLCondition` delegate being cached? I imagine we could get rid of this when we replace the SQL templating.

**Comment by lukaseder** [comment]
> But why is the mySQLCondition delegate being cached? I imagine we could get rid of this when we replace the SQL templating.

I don't remember. I imagine yes, we could get rid of it. I don't see its value.
