### ISSUE TITLE
Parse DEFAULT keyword in UPDATE

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8758]
The parser should parse the `DEFAULT` keyword in `UPDATE ... SET X = DEFAULT` and `INSERT INTO ... VALUES (DEFAULT)` and map it to `DSL#default_()`.

**Comment by lukaseder** [comment]
Nice catch. It does parse the expression, but recognises it as a column name.

**Comment by lukaseder** [comment]
If you're planning to fix this right away, could you please add a reference to #7518 (3.12 parser fixes). Otherwise to #8452 (3.13 parser fixes)

**Comment by knutwannheden** [comment]
From the commit message? Too late already. :-( I thought it was best to have specific issues.

**Comment by lukaseder** [comment]
Commit message would have been nice to have for the next time. No worries at all. But adding it to the bullet list in #7518 would be nice, too. There are many examples.

**Comment by lukaseder** [comment]
Note, the `DEFAULT` keyword can also be used with `INSERT` statements... also not supported yet:

```sql
INSERT INTO t (x) VALUES (DEFAULT);
```

**Comment by knutwannheden** [comment]
Now, for dialects which don't natively support the `DEFAULT` keyword in this context, I suppose the original implementation was correct... For now I guess we will however leave it at this. What do you think?

**Comment by lukaseder** [comment]
Yes, we'll fix that once we support parser input strictness: https://github.com/jOOQ/jOOQ/issues/7336. Currently, we don't support that and the default is to assume users write SQL in the "jOOQ dialect".

**Comment by knutwannheden** [comment]
> Note, the DEFAULT keyword can also be used with INSERT statements.

Good catch. I will fix that as well.
