### ISSUE TITLE
Add missing dialects to DSLContext#mergeInto(Table)

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8766]
The method `DSLContext#mergeInto(Table)` (and `DSL#mergeInto(Table)`) is missing some dialects when compared to the other overloaded `mergeInto()` methods. Specifically these are `AURORA_POSTGRES`, `HANA`, and `POSTGRES_9_5`.

**Comment by lukaseder** [comment]
Nice catch. I believe, this used to be the overload for the SQL standard `MERGE` syntax only, before [jOOQ/jOOQ#5011] extended the DSL and made `DSLContext.mergeInto(Table)` accessible also to the H2-specific `MERGE` syntax via `mergeInto(Table).columns(...)`, which is available to more dialects.
