### ISSUE TITLE
Fix @Support annotations on AlterTableDropStep

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8773]
The `@Support` annotations on the methods of `AlterTableDropStep` (`cascade()` and `restrict()`) don't explicitly list any dialects. Although the dialects actually supporting `ALTER TABLE ... DROP COLUMN ... [ CASCADE | RESTRICT ]` is probably limited. This should be fixed.

**Comment by lukaseder** [comment]
Indeed. Probably, most dialects support `RESTRICT` either explicitly as a keyword, or implicitly as a default behaviour, but `CASCADE` is unlikely to be widely supported.

**Comment by lukaseder** [comment]
This was fixed with https://github.com/jOOQ/jOOQ/issues/9380 in jOOQ 3.13
