### ISSUE TITLE
Record.get(n) etc, Javadoc could state if n starts from 0 or 1

### ISSUE THREAD

**Issue by adrianmsmith** [jOOQ/jOOQ#8775]
Hey, I hope this is the right place to post this, if not, please let me know where I could post this.

I have been using jOOQ for about 4 years now, full-time. Even so, I still get confused as to whether methods like record.get(2) returns the value of the 2nd or 3rd field.

I'm sure it's very obvious to the jOOQ maintainers, but alas I forget it each time, despite working with jOOQ very regularly! Java arrays and Lists start from 0, JDBC ResultSets famously [start from 1](https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html#getByte(int)) so either option would be plausible in my opinion.

I'm sure it's documented somewhere but I can never find it.

My suggestion: Each such method, the Javadoc 

     * @param index The field's index

could be extended by saying "starts from 0" or "starts from 1".

(Seen on jOOQ 3.10.5).

If you would like me to submit a pull request to put this info in the Javadoc, I would be happy to do so.

**Comment by knutwannheden** [comment]
Thank you very much for your report. Please note that there is a section on this topic in the jOOQ manual (https://www.jooq.org/doc/3.11/manual/sql-building/zero-based-vs-one-based/) which may help you remember which APIs are zero-based and one-based.

This being said I still agree with you that it wouldn't hurt to mention this in the Javadoc of the relevant methods. Thank you for the suggestion.

**Comment by adrianmsmith** [comment]
Sorry for not being more explicit, I didn't mean to suggest it wasn't
documented anywhere. Although I admit I didn't find that link, I shall
bookmark it now :-)

If you're writing code using jOOQ, you type in `record.get(` in the IDE and
the IDE then pops up the Javadoc window, that's all your looking at at that
moment. You could change the window to the browser and google for the
answer, but it would be more convenient if the answer was right there.

I know that makes it redundant. But if the main problem with redundancy is
that it's more difficult to change things, this being 0-based or 1-based
can't ever be changed, so I think there's no problem with putting the
information redundantly in the Javadocs there.

>

**Comment by lukaseder** [comment]
Tackling this now for jOOQ 3.15.0. I'm listing the API that will be updated here:

### 0-based

- [ ] `Record::changed`
- [ ] `Record::field`
- [ ] `Record::fields`
- [ ] `Record::from`
- [ ] `Record::fromArray`
- [ ] `Record::fromMap`
- [ ] `Record::get`
- [ ] `Record::getValue`
- [ ] `Record::indexOf` (return value)
- [ ] `Record::original`
- [ ] `Record::reset`

### 1-based

- [ ] ...

More to come. We could definitely profit from extracting API to a common type, first: https://github.com/jOOQ/jOOQ/issues/11031

**Comment by lukaseder** [comment]
I might have just scratched the surface... Finding all relevant Javadocs might take a while, but I think that documenting the methods from the new `org.jooq.Fields` type is already very useful.
