### ISSUE TITLE
Add REDSHIFT support to methods of SelectLimitStep

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8776]
Redshift has native support for `ORDER BY ... LIMIT ... OFFSET`: https://docs.aws.amazon.com/redshift/latest/dg/r_SELECT_synopsis.html. The corresponding `@Support` annotations on `SelectLimitStep` should properly reflect this.

**Comment by lukaseder** [comment]
This was implemented in jOOQ 3.15.0 with https://github.com/jOOQ/jOOQ/issues/11961
