### ISSUE TITLE
Formattable String formatCSV(boolean header, char delimiter) header value is always ignored

### ISSUE THREAD

**Issue by giuliozelante** [jOOQ/jOOQ#8777]
I was expecting  to call the aforementioned constructor and get a CSV without the header.
looking at the source code I noticed that value is completely ignored in the implementation

to reproduce this behaviuour just create a select and apply formatCSV(false,{delimiter}) after fetch method

Versions:

- jOOQ: 3.11.9
- Java: 8
- Database (include vendor): MySql 5.7
- OS: Windows 10 pro x64

**Comment by knutwannheden** [comment]
Thank you very much for your report. Yes, you are quite right, this particular overload of `formatCSV()` in `AbstractFormattable` is wrong:

https://github.com/jOOQ/jOOQ/blob/f0acb5693bb8375f03efbbb18e73fd4a6b457114/jOOQ/src/main/java/org/jooq/impl/AbstractFormattable.java#L151-L156

We will fix this issue in 3.12 and consider backporting the fix to 3.11.

**Comment by knutwannheden** [comment]
The fix has been committed to 3.12 and will also be made available as part of the upcoming 3.11.12 release. Thanks for the report!
