### ISSUE TITLE
Formattable String formatCSV(boolean header, char delimiter) header value is always ignored - Merge [#8777]

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8778]
Merge issue for #8777.

**Comment by lukaseder** [comment]
This issue is not present in jOOQ 3.11. It was a regression introduced in 3.12 only, through the refactoring where `AbstractFormattable` was extracted.

**Comment by lukaseder** [comment]
My mistake... `AbstractFormattable` was introduced in 3.12, but the bug existed in `AbstractCursor`
