### ISSUE TITLE
SQL Server: Support AlterIndexStep#renameTo()

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8780]
SQL Server's `ALTER INDEX` statement requires an `ON` clause which is why `DSL#alterIndex()` (but not `DSL#alterIndexIfExists()`) returns `AlterIndexOnStep` rather than `AlterIndexStep`. But the `AlterIndexOnStep#on()` methods in turn return `AlterIndexStep`. Although here the `renameTo()` methods don't list `SQLSERVER` support, even though the corresponding emulation has been implemented.

It may in fact also be possible to emulate the `IF EXISTS` clause, in which case the `DSL#alterIndexIfExists()` methods could also be listed to support SQL Server.

**Comment by lukaseder** [comment]
Very nice catch!

The `IF EXISTS` clause part is a separate issue (feature request), though.

**Comment by knutwannheden** [comment]
`AlterTableStep#renameIndex()` now also supports SQLSERVER2016.
