### ISSUE TITLE
Check if ALTER INDEX ... RENAME can be supported by all SQL Server versions

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8788]
Currently `DSL#alterIndex()` states support for SQLSERVER2016. It should be checked if older version can be supported as well, so that this can be changed to SQLSERVER.

This also includes `AlterTableStep#renameIndex()` which internally has been implemented as an "alias" for `DSL#alterIndex()` for the SQLSERVER family.

**Comment by lukaseder** [comment]
Customers haven't asked for this feature yet, and as time moves on, these older SQL Server versions are used less and less likely, making this feature less likely to be useful to any paying customers...

I'll reject this for now. We can reopen if someone requires it.
