### ISSUE TITLE
Add support for parsing MySQL numeric interval literals

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8789]
MySQL supports a set of numeric interval literals, where the interval is described by a number, instead of a string. For example:

```sql
interval 1 year
interval 1 quarter -- (= interval 3 month)
interval 1 month
interval 1 week -- (= interval 7 day)
interval 1 day
interval 1 hour
interval 1 minute
interval 1 second
interval 1 millisecond -- (not officially supported, but we can easily emulate it)
interval 1 microsecond
interval 1 nanosecond -- (not officially supported, but we can easily emulate it)
```

In addition to the above MySQL interval units (e.g. `year`), we'll also support parsing the plural form, as this is supported by some other dialects (e.g. `years`)

The non-numeric interval literals will be supported under a separate issue (#8790)

----
See:
- https://dev.mysql.com/doc/refman/8.0/en/expressions.html#temporal-intervals
- https://github.com/jOOQ/jOOQ/issues/8765

**Comment by knutwannheden** [comment]
Note: I think MySQL even supports expressions as in `interval 1+2 year`.

**Comment by lukaseder** [comment]
Yes, this will be supported separately as jOOQ currently cannot express dynamic interval expressions, only interval literals: #8792
