### ISSUE TITLE
Add Settings.transformAnsiJoinToTableLists to support pre-ANSI join syntax

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8800]
Some systems may wish to use jOOQ on Oracle 8i despite the fact that we don't formally support that version. For the parser and SQL translation tools, it might be useful to be able to turn off ANSI JOIN generation. It shouldn't be too difficult to transform jOOQ's ANSI join syntax to "classic joins" for simple queries. So, we'll generate:

### cross join

```sql
-- ANSI
select t1.a, t2.b from t1 cross join t2

-- Pre ANSI
select t1.a, t2.b from t1, t2
```

### inner join

```sql
-- ANSI
select t1.a, t2.b from t1 join t2 on t1.x = t2.x

-- Pre ANSI
select t1.a, t2.b from t1, t2 where t1.x = t2.x
```

### (left / right) outer join

```sql
-- ANSI
select t1.a, t2.b from t1 left join t2 on t1.x = t2.x

-- Pre ANSI
select t1.a, t2.b from t1, t2 where t1.x = t2.x(+)
```

Some join syntaxes (`NATURAL JOIN`, `FULL JOIN`, partitioned outer join, `APPLY`, `LATERAL`, etc.) cannot be emulated using pre-ansi joins. Also, complex join graphs are not reasonably possible. We may document these limitations.

This is the inverse of #7265.

**Comment by knutwannheden** [comment]
Outer join is tricky as it also requires the `(+)` on other expressions for that object in the WHERE clause, IIRC.

**Comment by lukaseder** [comment]
I don't see the difficulty (yet), as existing predicates from the `WHERE` clause must not be modified. For example, if someone writes:

```sql
-- ANSI
select t1.a, t2.b 
from t1 
  left join t2 
    on t1.x = t2.x and t2.y = 1
where t1.z = 1
and t2.z = 1 -- Possibly a bug but we won't touch this
```

Then the transformation is still straightforward. We only add `(+)` to all predicates that are involved with an ansi `left join` or `right join`:

```sql
-- Pre ANSI
select t1.a, t2.b 
from t1, t2
where t1.x = t2.x(+)
and t2.y(+) = 1
and t1.z = 1
and t2.z = 1 -- Possibly a bug but we won't touch this
```

**Comment by lukaseder** [comment]
This feature would profit tremendously from a new query object model that supports built-in, generic pattern matching. But we can already implement some limited internal pattern matching for `org.jooq.Condition`, which is necessary to add the `(+)` operator to all relevant expressions.

Since there is a customer who would like to see this shipped in 3.13, I'll expedite an internal pattern matcher that helps support this transformation, keeping in mind that this needs to be refactored for 3.14 (see #9767)

**Comment by lukaseder** [comment]
A preliminary implementation with the following known limitations has been added:

Transformation not possible using pre-ANSI join syntax                      
------------------------------------------------------                      
- Full outer joins (not possible in Oracle pre-ANSI join syntax)            
- Partitioned outer joins                                                   
- Apply                                                                     
                                                                            
Transformation not yet implemented (please request feature if applicable)   
-------------------------------------------------------------------------   
- "Complex" join conditions, such as between predicate, etc.                
- Field expressions                                                         
- Plain SQL expressions                                                     
- Non-trivially nested join expressions (transformation not always possible)
- Semi / anti joins                                                         
- Natural joins                                                             

This implementation might be improved for 3.13 still, but might as well ship as is.

**Comment by lukaseder** [comment]
Documentation for this feature will be added through https://github.com/jOOQ/jOOQ/issues/9767, in a later release
