### ISSUE TITLE
questionmark in generated SQL

### ISSUE THREAD

**Issue by UCSBGauchos** [jOOQ/jOOQ#8801]
### Your question:
This is my fluent API in JAVA:
DSLContext create = DSL.using(SQLDialect.MYSQL);
        String sql = create.select(field("BOOK.TITLE"), field("AUTHOR.FIRST_NAME"), field("AUTHOR.LAST_NAME"))
                .from(table("BOOK"))
                .join(table("AUTHOR"))
                .on(field("BOOK.AUTHOR_ID").eq(field("AUTHOR.ID")))
                .where(field("BOOK.PUBLISHED_IN").equal("weber"))
                .getSQL();
        System.out.println(sql);

But my SQL generated is:
select BOOK.TITLE, AUTHOR.FIRST_NAME, AUTHOR.LAST_NAME from BOOK join AUTHOR on BOOK.AUTHOR_ID = AUTHOR.ID where BOOK.PUBLISHED_IN = ?
 
Why there is a queationmark ? at the end of the SQL?

### Versions:

- jOOQ:3.11.11
- Java: 1.8

**Comment by lukaseder** [comment]
Thank you very much for your question.

The default behaviour in jOOQ is to always generate bind variables. This can be overridden in a variety of ways, including for example by calling an alternative `Query.getSQL(ParamType)` overload.

Please refer to the manual for further information:
https://www.jooq.org/doc/latest/manual/sql-building/bind-values
