### ISSUE TITLE
Dows the SQL Builder support this complex query?

### ISSUE THREAD

**Issue by UCSBGauchos** [jOOQ/jOOQ#8802]
### Your question:
I have a complex query:

```sql
SELECT claim.ant_policy_no, ant_claim_no, prod_no, claim_report_time, claim_success_time
	, claim_status,
FROM (
	SELECT ant_policy_no
	FROM ods_cathay_prod.ods_person_www_with_part
	WHERE pt > '2017-05-01'
		AND account_id = '${account_id}'
	GROUP BY ant_policy_no
) person
	INNER JOIN (
		SELECT ant_policy_no, ant_claim_no, prod_no, claim_report_time, claim_success_time
			, claim_status
		FROM dw_f_claim_www
		WHERE pt = '${pt}'
	) claim
	ON person.ant_policy_no = claim.ant_policy_no;
```

Does the JOOQ SQL builder support it? expecially for select XXX from (select XXX from XXX) ? 

### Versions:

- jOOQ:3.11.11
- Java: jdk 1,8

**Comment by lukaseder** [comment]
Thank you very much for your message. Yes, jOOQ supports derived tables and other kinds of nested selects. See this page for examples: https://www.jooq.org/doc/latest/manual/sql-building/table-expressions/nested-selects

In your case, I'm positive that you can re-write your query to avoid the derived tables entirely (which may even perform better on some RDBMS):

```sql
SELECT 
  claim.ant_policy_no, 
  claim.ant_claim_no, 
  claim.prod_no, 
  claim.claim_report_time, 
  claim.claim_success_time,
  claim.claim_status
FROM ods_cathay_prod.ods_person_www_with_part person
INNER JOIN dw_f_claim_www claim
ON person.ant_policy_no = claim.ant_policy_no
WHERE person.pt > '2017-05-01'
AND person.account_id = '${account_id}'
AND claim.pt = '${pt}'
GROUP BY person.ant_policy_no;
```

Depending on the semantics of your query, this could even be transformed into a semi join (using `IN` or `EXISTS`)
