### ISSUE TITLE
Improve performance of StringUtils#replace()

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8803]
By replacing the two calls of the form `stringBuilder.append(string.substring(start, end))` and `stringBuilder.append(string.substring(start))` with `stringBuilder.append(string, start, end)` it turns out that the performance of `StringUtils#replace()` can be increased quite a lot (for the cases when there are indeed replacements to be made). In the example of `replace("foo$bar$baz", "$", "$$")` the improvement is in the order of 25% (more "scientific" JMH benchmarks still outstanding) with most Java versions.

https://github.com/jOOQ/jOOQ/blob/ae13be078dd921e796430957e648b648cf67599e/jOOQ/src/main/java/org/jooq/tools/StringUtils.java#L783-L790

**Comment by knutwannheden** [comment]
Newer versions of Apache Commons also do this: https://github.com/apache/commons-lang/blob/dc2953e5e41f0d5bf069349bbd7c6fe26f3362e1/src/main/java/org/apache/commons/lang3/StringUtils.java#L6365

**Comment by lukaseder** [comment]
Nice catch. Looking forward to the benchmark. I've already seen a huge change when replacing `String.replace()` (which used to use regex behind the scenes in older JDKs) by `StringUtils.replace()`: #6672

But we could definitely upgrade the `StringUtils` implementation to a newer version of Apache Commons Lang. In fact, we could benchmark again also using JDK's `String.replace()` again, since they optimised the implementation in JDK 9, I believe. We could call the `StringUtils` method only in JDK 6 and 8 builds.

**Comment by knutwannheden** [comment]
This practically takes us full circle: apache/commons-lang#300 :rofl:

**Comment by knutwannheden** [comment]
I adapted and reran the existing `StringReplaceBenchmark` on JDK 11.0.3 comparing Java's `String#replace()` with the original `StringUtils#replace()` and the modified `StringUtils#replace()`:

```
StringReplaceBenchmark.newStringUtilsReplace         SHORT_STRING_NO_MATCH  thrpt   15  136696558.883 ± 5539183.518  ops/s
StringReplaceBenchmark.newStringUtilsReplace        SHORT_STRING_ONE_MATCH  thrpt   15   21573283.745 ± 1273144.642  ops/s
StringReplaceBenchmark.newStringUtilsReplace  SHORT_STRING_SEVERAL_MATCHES  thrpt   15   10319473.868 ±  157766.679  ops/s
StringReplaceBenchmark.newStringUtilsReplace          LONG_STRING_NO_MATCH  thrpt   15   63451250.626 ±  416993.401  ops/s
StringReplaceBenchmark.newStringUtilsReplace         LONG_STRING_ONE_MATCH  thrpt   15   10916587.418 ±  523161.578  ops/s
StringReplaceBenchmark.newStringUtilsReplace   LONG_STRING_SEVERAL_MATCHES  thrpt   15    6754738.800 ±  362925.617  ops/s
StringReplaceBenchmark.oldStringUtilsReplace         SHORT_STRING_NO_MATCH  thrpt   15  138325279.685 ± 6683663.486  ops/s
StringReplaceBenchmark.oldStringUtilsReplace        SHORT_STRING_ONE_MATCH  thrpt   15   13915850.907 ± 1066899.532  ops/s
StringReplaceBenchmark.oldStringUtilsReplace  SHORT_STRING_SEVERAL_MATCHES  thrpt   15    6302286.875 ±  295003.048  ops/s
StringReplaceBenchmark.oldStringUtilsReplace          LONG_STRING_NO_MATCH  thrpt   15   62552106.915 ±  424790.976  ops/s
StringReplaceBenchmark.oldStringUtilsReplace         LONG_STRING_ONE_MATCH  thrpt   15   11104012.182 ±  695039.816  ops/s
StringReplaceBenchmark.oldStringUtilsReplace   LONG_STRING_SEVERAL_MATCHES  thrpt   15    4968998.206 ±  365142.713  ops/s
StringReplaceBenchmark.stringReplace                 SHORT_STRING_NO_MATCH  thrpt   15  152733762.380 ± 7390628.290  ops/s
StringReplaceBenchmark.stringReplace                SHORT_STRING_ONE_MATCH  thrpt   15   22994216.580 ± 1048718.701  ops/s
StringReplaceBenchmark.stringReplace          SHORT_STRING_SEVERAL_MATCHES  thrpt   15    9330246.052 ±  236595.752  ops/s
StringReplaceBenchmark.stringReplace                  LONG_STRING_NO_MATCH  thrpt   15   71332459.273 ± 2485759.725  ops/s
StringReplaceBenchmark.stringReplace                 LONG_STRING_ONE_MATCH  thrpt   15   11404700.065 ±  740490.787  ops/s
StringReplaceBenchmark.stringReplace           LONG_STRING_SEVERAL_MATCHES  thrpt   15    5294072.338 ±  222579.544  ops/s
```

As can be seen the modified `StringUtils` improves the performance for the case when there are matches and makes it on par with JDK's `String#replace()` or maybe even slightly faster. For the case when there are no matches the JDK is clearly the fastest.

**Comment by knutwannheden** [comment]
Running the same benchmark on JDK 1.8.0_212:

```
Benchmark                                                            (str)   Mode  Cnt          Score          Error  Units
StringReplaceBenchmark.newStringUtilsReplace         SHORT_STRING_NO_MATCH  thrpt   15  183214918.033 ±  9154334.152  ops/s
StringReplaceBenchmark.newStringUtilsReplace        SHORT_STRING_ONE_MATCH  thrpt   15   17687122.912 ±  2326984.515  ops/s
StringReplaceBenchmark.newStringUtilsReplace  SHORT_STRING_SEVERAL_MATCHES  thrpt   15   11168697.303 ±   247454.911  ops/s
StringReplaceBenchmark.newStringUtilsReplace          LONG_STRING_NO_MATCH  thrpt   15   40941082.051 ±  7880713.325  ops/s
StringReplaceBenchmark.newStringUtilsReplace         LONG_STRING_ONE_MATCH  thrpt   15    9508518.093 ±   356279.166  ops/s
StringReplaceBenchmark.newStringUtilsReplace   LONG_STRING_SEVERAL_MATCHES  thrpt   15    6262502.166 ±   389410.867  ops/s
StringReplaceBenchmark.oldStringUtilsReplace         SHORT_STRING_NO_MATCH  thrpt   15  163138812.628 ± 22928179.210  ops/s
StringReplaceBenchmark.oldStringUtilsReplace        SHORT_STRING_ONE_MATCH  thrpt   15   13167257.247 ±   436309.983  ops/s
StringReplaceBenchmark.oldStringUtilsReplace  SHORT_STRING_SEVERAL_MATCHES  thrpt   15    7294592.565 ±   481707.121  ops/s
StringReplaceBenchmark.oldStringUtilsReplace          LONG_STRING_NO_MATCH  thrpt   15   36098701.341 ±  2740790.165  ops/s
StringReplaceBenchmark.oldStringUtilsReplace         LONG_STRING_ONE_MATCH  thrpt   15    8958061.182 ±   906307.297  ops/s
StringReplaceBenchmark.oldStringUtilsReplace   LONG_STRING_SEVERAL_MATCHES  thrpt   15    5130807.020 ±   198251.717  ops/s
StringReplaceBenchmark.stringReplace                 SHORT_STRING_NO_MATCH  thrpt   15    8100630.423 ±   275085.009  ops/s
StringReplaceBenchmark.stringReplace                SHORT_STRING_ONE_MATCH  thrpt   15    4321399.953 ±   154583.206  ops/s
StringReplaceBenchmark.stringReplace          SHORT_STRING_SEVERAL_MATCHES  thrpt   15    2690464.402 ±   138324.337  ops/s
StringReplaceBenchmark.stringReplace                  LONG_STRING_NO_MATCH  thrpt   15    7195433.257 ±   212151.366  ops/s
StringReplaceBenchmark.stringReplace                 LONG_STRING_ONE_MATCH  thrpt   15    1873524.473 ±    60727.906  ops/s
StringReplaceBenchmark.stringReplace           LONG_STRING_SEVERAL_MATCHES  thrpt   15    1394085.491 ±    41767.999  ops/s
```

Here `StringUtils` performs significantly better than the JDK's `String#replace()`. And also here the modified version is faster than the original `StringUtils`.

I am somewhat surprised that the JDK 8 apparently performs so much better than the JDK 11 in this benchmark. I am aware that String internals have changed many times ever since Java 6, but I still didn't expect this much of a difference.

**Comment by slandelle** [comment]
> I am aware that String internals have changed many times ever since Java 6, but I still didn't expect this much of a difference.

Do you force GC algorithm in your JMH benchmarks? Otherwise you're running with Parallel on JDK8 and G1 on JDK11 and you can't tell where the difference come from.

**Comment by knutwannheden** [comment]
> @knutwannheden Do you force GC algorithm in your JMH benchmarks? Otherwise you're running with Parallel on JDK8 and G1 on JDK11 and you can't tell where the difference come from.

@slandelle No, so far I didn't. Thanks for the pointer.

**Comment by knutwannheden** [comment]
Closing this issue as fixed. As soon as we drop Java 6 and Java 8 support it would probably make sense to switch to `String#replace()`.
