### ISSUE TITLE
When to perform code generation

### ISSUE THREAD

**Issue by raderio** [jOOQ/jOOQ#8804]
When to perform code generation? 
Before every run(build/deploy) or test command? Or the task should be called separated from other tasks? 
What is common practice for this action?

**Comment by lukaseder** [comment]
Thank you very much for your question.

There's not a one-size-fits-all answer to this question. We've elaborated on this topic in a blog post:
https://blog.jooq.org/2014/09/08/look-no-further-the-final-answer-to-where-to-put-generated-code

All approaches have their pros and cons, you should pick the one that best suits your development workflow.
