### ISSUE TITLE
Support OVERLAY() function

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8805]
`OVERLAY()` is a special form function specified in the SQL standard and supported by a few SQL databases / engines, including PostgreSQL, Firebird, Vertica, CockroachDB, and DB2. See here for extract from standard: https://docs.microsoft.com/en-us/openspecs/sql_standards/ms-tsqliso02/4293aba8-8d28-4d30-9824-7a1dd9e4807c.

The function needs support in:

- [x] DSL
- [x] Emulations in dialects that don't support this, including:
  - [x] Access
  - [x] Derby
  - [x] H2
  - [x] HANA
  - [x] HSQLDB
  - [x] Informix
  - [x] Ingres
  - [x] MySQL dialects
  - [x] Oracle
  - [x] Redshift
  - [x] SQLite
  - [x] T-SQL dialects (including Sybase)
  - [x] Teradata
- [x] Parser

**Comment by lukaseder** [comment]
Interesting. First time I see it, but it appears quite useful. Should be easy to emulate too:

```sql
-- 1
overlay(a placing b from c)

-- 2
overlay(a placing b from c [for d])
```

Becomes

```sql
-- 1
substring(a, 1, c - 1) || b || substring(a, c + length(b))

-- 2
substring(a, 1, c - 1) || b || substring(a, c + d)
```

**Comment by lukaseder** [comment]
The SQL standard confirms my emulation suggestion:

![image](https://user-images.githubusercontent.com/734593/75148933-207f0300-5701-11ea-8226-dff732b8652b.png)

**Comment by knutwannheden** [comment]
DB2's `OVERLAY()` unfortunately works a bit differently (see https://www.ibm.com/support/knowledgecenter/SSEPEK_12.0.0/sqlref/src/tpc/db2z_bif_overlay.html). The `LENGTH` parameter is defaulted to `1` if unspecified and thus `OVERLAY('abcdefg' PLACING 'xxx' FROM 2)` will on DB2 evaluate to `axxxcdefg` rather than `axxxxefg` as with other dialects.

Does jOOQ need some setting which allows controlling whether features should be emulated when the native feature doesn't comply with the SQL standard?

**Comment by lukaseder** [comment]
LUW link here: https://www.ibm.com/support/knowledgecenter/SSEPGG_10.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0050492.html

That default makes no sense :-/ but oh well. I guess we should fix the parser too, then. When the parse dialect is DB2, it would be better to generate an explicit length of 1, then.

**Comment by lukaseder** [comment]
For the record, the SQL standard disagrees with DB2:

![image](https://user-images.githubusercontent.com/734593/75442572-1149c080-5960-11ea-9535-d9f2e939dd39.png)
