### ISSUE TITLE
Compilation error in generated code when sequence has the same name as its containing schema

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8808]
This schema

```sql
CREATE SCHEMA s1;
CREATE SEQUENCE s1.s1;
```

... produces a compilation error

```
[ERROR] C:\Users\lukas\workspace\jOOQ-pro\jOOQ-test-codegen\src\test\java\org\jooq\codegen\test\xmlexport\java\db\s1\Sequences.java:[20,73] error: self-reference in initializer
[ERROR] C:\Users\lukas\workspace\jOOQ-pro\jOOQ-test-codegen\src\test\java\org\jooq\codegen\test\xmlexport\java\db\s1\Sequences.java:[20,75] error: cannot find symbol
[ERROR]   symbol:   variable S1
[ERROR]   location: variable S1 of type Sequence<Long>
```

... in generated code:

```java
public class Sequences {

    /**
     * The sequence <code>S1.S1</code>
     */
    public static final Sequence<Long> S1 = new SequenceImpl<Long>("S1", S1.S1, org.jooq.impl.SQLDataType.BIGINT);
}
```

**Comment by knutwannheden** [comment]
The simplest solution is to always generate a qualified name reference to the static sequence singleton field.

**Comment by lukaseder** [comment]
> The simplest solution is to always generate a qualified name reference to the static sequence singleton field.

That's always the simplest solution, but it's also always nice if we don't have fully qualified names. Isn't there a rule we can derive when this issue is likely to happen?

**Comment by knutwannheden** [comment]
I suppose we would have to check if any of the sequences in the target schema has the same name as the schema. Since we have the full set of sequences available in `generateSequences()` we could of course do that.

**Comment by lukaseder** [comment]
I would very much prefer that, yes :)

**Comment by knutwannheden** [comment]
OK. Let's do that.

**Comment by lukaseder** [comment]
Notice, there might be some pre-existing utility, although I'm not 100% sure. The generator strategies do some name disambiguation already

**Comment by knutwannheden** [comment]
Too late... I will take another look.

**Comment by lukaseder** [comment]
No worries then. I'm really not sure if there is such a tool. There are some tools, but this particular case doesn't sound like something I had solved before in exactly this way.

**Comment by lukaseder** [comment]
I like the implementation!

**Comment by knutwannheden** [comment]
I suppose we could use similar logic when generating the `Tables` class with its static members referring to the various table classes. But it maybe isn't worth it.

**Comment by lukaseder** [comment]
Tables already has some sort of disambiguation, when there is a column by the same name. It works a bit differently, there. The table identifier will get a `_` suffix, e.g. when we have:

```sql
CREATE TABLE t(t INT);
```

The table will be called `T_` and the column will be called `T` by default. This is different, because both identifiers are declared in the same generated table file. We don't have this problem with sequences, where the schema and the sequence are not declared in the same file, so it's only a reference problem, not a declaration problem.

**Comment by knutwannheden** [comment]
Instead of

```java
public static final DaosPk DAOS_PK = org.jooq.codegen.test.daos.db.tables.DaosPk.DAOS_PK;
```

we could however simply generate

```java
public static final DaosPk DAOS_PK = DaosPk.DAOS_PK;
```
But that isn't really related to this issue anymore.

**Comment by lukaseder** [comment]
Ah yes, perhaps that's because at the point this code generation logic was written, I hadn't created the `GeneratorWriter.ref(String, int)` overload yet, which allows for specifying a number of "segments", which should be kept in a qualified name. E.g.:

- `1` = `DAOS_PK`
- `2` = `DaosPk.DAOS_PK`
- `3` = `tables.DaosPk.DAOS_PK`

Want to create a new issue to improve this for 3.12?

**Comment by knutwannheden** [comment]
Sure, I can create the issue.

**Comment by lukaseder** [comment]
For the reference, the issue is: #8863

**Comment by lukaseder** [comment]
This also affects other object types, see #10561. I'll implement a more generic solution.
