### ISSUE TITLE
POSTGRES: Support DSL#convert()

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8812]
The commercial jOOQ editions have the function `DSL#convert()` which in its implementation (see class `ConvertDateTime`) also support `POSTGRES`, but the two `DSL#convert()` methods don't list `POSTGRES` support in the `@Support` annotation, which looks like an oversight.

It should also be checked, if this can be supported natively for `AURORA_POSTGRES`.

**Comment by knutwannheden** [comment]
Note: The current `TO_CHAR` formats used in `ConvertDateTime` are not all quite correct for Postgres. For instance the `FF` part should be `MS` or `US`. See https://www.postgresql.org/docs/current/functions-formatting.html.

**Comment by lukaseder** [comment]
Thanks. This is a new 3.12 feature, so you could fix the PostgreSQL issue directly in #8238

**Comment by knutwannheden** [comment]
I see. Either that or fix it in 3.13. First I thought it was as easy as adding `POSTGRES` to the `@Support` annotation.

**Comment by lukaseder** [comment]
> I see. Either that or fix it in 3.13. First I thought it was as easy as adding POSTGRES to the @Support annotation.

Up to you to decide.

- Fix now: #8238
- Fix later: New issue

**Comment by lukaseder** [comment]
Oh, this is already the issue. Never mind :)

**Comment by knutwannheden** [comment]
Fixed as part of ##8238.
