### ISSUE TITLE
Refactor internal org.jooq.impl.Function to require Field rather than QueryPart parameters in constructor

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8814]
`Function` is used internally in a number of places, especially when invoking the equivalent of varargs functions in SQL. The constructors declare a `QueryPart...` vararg parameter, but it would be better if this could be changed to `Field...` so that the SQL rendering can use `visit(<arg>)` when rendering SQL rather than `visit(DSL.field("{0}", <arg>))`. This requires refactoring of `DSL#groupingSets()`.

**Comment by lukaseder** [comment]
I'm not sure anymore what the rationale of this improvement was, nor do I see any `visit(DSL.field("{0}", <arg>))` anymore. Perhaps it's outdated.
