### ISSUE TITLE
Bad SQL generated in PostgreSQL when calling nextval on a sequence with apostrophes in its name

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8820]
Consider this valid sequence in PostgreSQL:

```sql
create sequence "can't";
```

The apostrophe is not correctly escaped, nor is the sequence quoted, so we cannot currently select `nextval` from this sequence. This also affects H2, as jOOQ doesn't generate the standard syntax `NEXT VALUE FOR <name>`, but `nextval('<name>')`

**Comment by knutwannheden** [comment]
Make sure this also works correctly for Postgres with qualified sequence names.
