### ISSUE TITLE
Add support for additional DB2 and SQLDATAWAREHOUSE DateParts

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8825]
In the context of `DSL#extract()` jOOQ already implements support for some `DatePart` enum literals, where the `@Support` annotation doesn't yet include `DB2`. The same is true for SQL Data Warehouse. This should be corrected.

**Comment by lukaseder** [comment]
Cool, thanks! Huh, our newest integration tests probably don't cover this as these enum literals cannot be instrumented easily, such as methods. Would it be possible to cover this case also in our new `@Support` validating integration tests?

**Comment by knutwannheden** [comment]
> Would it be possible to cover this case also in our new `@Support` validating integration tests?

I created a corresponding issue already.
