### ISSUE TITLE
Wrong rendering of Oracle's CREATE SEQUENCE `NO` clauses

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8832]
Oracle's `NO` clauses should be rendered as for `INFORMIX`. I.e. `NOCACHE` rather than `NO CACHE`, etc. Currently jOOQ does this incorrectly.

**Comment by lukaseder** [comment]
What made you think it's currently wrong?
https://docs.oracle.com/database/121/SQLRF/img_text/create_sequence.htm

**Comment by knutwannheden** [comment]
The issue description is a bit misleading. The current rendering is `NO CACHE` rather than `NOCACHE`. Let me fix that.

**Comment by lukaseder** [comment]
Ah, I see. Makes sense
