### ISSUE TITLE
Correct CreateSequenceFlagsStep#noCache() for Postgres

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8836]
Postgres `CREATE SEQUENCE` does not have a `NO CACHE` clause: https://www.postgresql.org/docs/current/sql-createsequence.html. But by simply omitting the `CACHE` clause (or using `CACHE 1`) the same effect is achieved, since the default on Postgres is no caching.

**Comment by lukaseder** [comment]
I'd prefer omitting the clause, rather than specifying `CACHE 1`, if omitting already has this effect.

**Comment by knutwannheden** [comment]
Agreed.
