### ISSUE TITLE
Add support for [NOT] LIKE ANY (subquery) and [NOT] LIKE ALL (subquery)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8853]
jOOQ 3.12 introduces synthetic `[NOT] LIKE ANY` and `[NOT] LIKE ALL` operators (#8577). It should also be possible to combine these operators with subqueries as in:

```java
field.like(all("a%", "%b"));
field.like(all(select(...)));

field.notLike(any("a%", "%b"));
field.notLike(any(select(...)));
```

The emulation for the subqueries case is not entirely obvious:

**`a LIKE ANY (select)`**:

```sql
TRUE = ANY (
  SELECT a LIKE pattern
  FROM (select) AS t(pattern)
)
```

**`a NOT LIKE ALL (select)`**:

```sql
FALSE = ALL (
  SELECT a LIKE pattern
  FROM (select) AS t(pattern)
)
```

The emulation above will also work correctly in the presence of `NULL` values on either side of the operator.

**Comment by knutwannheden** [comment]
As discussed we will probably need new `DSL#all(Field...)` and `DSL#any(Field...)` methods. Or should the existing `all(Object...)` and `any(Object...)` be made to cover for that?

Also, should we add new `all(Collection<?>)` and `any(Collection<?>)` methods?

**Comment by lukaseder** [comment]
> As discussed we will probably need new DSL#all(Field...) and DSL#any(Field...) methods. Or should the existing all(Object...) and any(Object...) be made to cover for that?

Yes, we need the new methods, even if the existing one could work, too. The reason is the type signature:

```java
public static <T> QuantifiedSelect<Record1<T>> any(T... array);
public static <T> QuantifiedSelect<Record1<T>> any(Field<T>... array);
```

If we only had the first, then writing something like

```java
var s = any(inline("a"), inline("b"));
```

Would yield an inferred type of `QuantifiedSelect<Record1<Param<String>>>`, which is not what we want. We want inference to produce `QuantifiedSelect<Record1<String>>`

**Comment by lukaseder** [comment]
... we could have a `Collection<? extends Field<T>>` overload. `Collection<?>` wouldn't work in this case, because we couldn't infer the type of `<T>`, which would make the overload useless.

**Comment by knutwannheden** [comment]
Derby also has problems with `NULL`s in quantified predicates.

**Comment by lukaseder** [comment]
> ... we could have a Collection<? extends Field<T>> overload. Collection<?> wouldn't work in this case, because we couldn't infer the type of <T>, which would make the overload useless.

I think we should have these in a later step. I've created an issue for this: #8885

> Derby and HSQLDB also have problems with NULLs in quantified predicates. Do we report issues for these?

Yes we do! HSQLDB issues are often resolved quite quickly, I'd say 50% of the time. Derby issues remind me of `/dev/null` but you never know :)

**Comment by knutwannheden** [comment]
> Yes we do! HSQLDB issues are often resolved quite quickly, I'd say 50% of the time. Derby issues remind me of /dev/null but you never know :)

* HSQLDB ticket: https://sourceforge.net/p/hsqldb/bugs/1554/
* Derby ticket: https://issues.apache.org/jira/browse/DERBY-7048
