### ISSUE TITLE
transactionResult Rollback caused an exception

### ISSUE THREAD

**Issue by TopSpoofer** [jOOQ/jOOQ#8855]
### Your question:

```
mycode like :

dsl.transactionResult { cfg =>
    val newDsl = DSL.using(cfg)
     do something use newDsl and down
     throw exception
     do something use newDsl
}
```

it made an exception : org.jooq.exception.DataAccessException: Rollback caused 

why not Rollback ok?

### Versions: 3.10.8

- jOOQ: 3.10.8
- Java: 1.8
- Database (include vendor): mysql
- OS: mac
- JDBC Driver (include name if inofficial driver):    mysql  Driver  8.0.11

**Comment by lukaseder** [comment]
jOOQ's transaction API supports nesting transactions. The way we designed this API, each exception obviously ends your own transactional code, and then rolls back the transaction that you wrapped in that block until the beginning of your block, which might be the beginning of a transaction, or a savepoint, depending on whether you nest your logic.

However, you threw an exception, or some library you've used might have thrown an exception. jOOQ cannot decide for all exception types what should be done, so the only reasonable default behaviour is to re-throw the exception.

If you don't want it to be rethrown, but continue at your safepoint, you have to wrap your logic in try-catch. Here's how to do that with Java:

```java
try {
    dsl.transactionResult { cfg =>
        var newDsl = DSL.using(cfg)
        // do something use newDsl and down
        throw new MyException();
        // do something use newDsl
   }
}
catch (MyException e) {
}
```
