### ISSUE TITLE
Use imported class name in Tables.java to dereference singleton table instance

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8863]
Currently the code generator sometimes generates qualified class names as for example in the `Tables` class:

```java
    public static final DaosPk DAOS_PK = org.jooq.codegen.test.daos.db.tables.DaosPk.DAOS_PK;
```
Since there already is an import for the class, this could be simplified to:

```java
    public static final DaosPk DAOS_PK = DaosPk.DAOS_PK;
```
Possibly there are more other cases like this one.

**Comment by lukaseder** [comment]
Well, we could optimise this for 90% of the cases, but beware that if a table is called `T`, then the generated code would be illegal:

```java
    public static final T T = T.T;
```

Everything is there for a reason :-) But we could indeed use the importet type, if its name does not equal the constant name, such as `"DAOS_PK".equals("DaosPK")`

**Comment by lukaseder** [comment]
From experience, I think this is a special case, and there are other special cases. I'd prefer to create new separate issues for these things, rather than fix many of these possible additional generated imports in one go.
