### ISSUE TITLE
Support Scala 2.13

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8870]
Scala 2.13 has been released to Maven Central on June 7, 2019: https://search.maven.org/artifact/org.scala-lang/scala-compiler/2.13.0/jar

We should start integration testing this version and formally support it in jOOQ. This will be the version supported by the jOOQ OSS Edition. The commercial editions will continue supporting Scala 2.10 - 2.12.

Adoption rates here: https://www.jetbrains.com/lp/devecosystem-2019/scala/ With still 13% using Scala 2.10 and 36% using Scala 2.11, we won't drop support for any of these versions in jOOQ 3.13 yet.

**Comment by lukaseder** [comment]
2.13.1 cannot be used yet: https://github.com/davidB/scala-maven-plugin/issues/363

**Comment by lukaseder** [comment]
Cannot build with 2.13 yet

- 2.13.0 has a compiler bug with JDK 13
- 2.13.1 has a compiler regession with the Maven plugin

**Comment by tovbinm** [comment]
What's the blocker? Is it JDK 13 & Scala 2.13?

**Comment by lukaseder** [comment]
@tovbinm See https://github.com/jOOQ/jOOQ/issues/8870#issuecomment-534535485

**Comment by lukaseder** [comment]
Trying again with `net.alchim31.maven:scala-maven-plugin:4.3.0`

**Comment by lukaseder** [comment]
Our tests work now with the upgraded Maven plugin and Scala 2.13.1
