### ISSUE TITLE
how to override qualify ?

### ISSUE THREAD

**Issue by hyhub** [jOOQ/jOOQ#8873]
### Your question:
hi,
sub-database and sub-table need to rewrite SQL, I don't want jooq SQL appened schema.
variables ”qualify“  defined in class "AbstractContext", and TableFieldImpl#accept(ctx) use it. there is no way to configure it or override method qualify(b);
<img width="419" alt="图片" src="https://user-images.githubusercontent.com/8871785/60394288-72609080-9b54-11e9-935c-4832b5612e56.png">

so: db.table.column,  i want column only, What should I do?

### Versions:

- jOOQ: 3.10.7
- Java: 1.8
- Database (include vendor): mysql 
- OS: macos
- JDBC Driver (include name if inofficial driver): 5

**Comment by lukaseder** [comment]
Thank you very much for your message.

You should not need to worry about that `Context.qualify()` flag, which is used internally for a variety of reasons. If you don't want any qualification in your generated SQL, you can either turn off schema qualification in the code generator (look for `outputSchemaToDefault`):
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-catalog-and-schema-mapping/

Or turn it off at runtime:
https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/settings-render-mapping/

or:
https://www.jooq.org/javadoc/latest/org/jooq/conf/Settings.html#renderSchema

**Comment by hyhub** [comment]
THX

**Comment by hyhub** [comment]
I'm bothering you again.
I tried it,but It doesn't work.
 the result is : select `t_order_0`.`order_id`, `t_order_0`.`user_id`, `t_order_0`.`status` from `t_order_0` limit ?

i hope it could be like select `order_id`, `user_id`, status` from `t_order_0` limit ?

here is my config
<img width="571" alt="图片" src="https://user-images.githubusercontent.com/8871785/60599088-6983ef00-9de0-11e9-8957-9b7d132d1f99.png">

**Comment by lukaseder** [comment]
Thanks for your message. Your original question was about schema qualification, not table qualification - although your original screenshot indeed hints at what you really meant.

You can manually unqualify jOOQ columns by using e.g. plain SQL templating:

```java
DSL.field("{0}", T_ORDER_0.STATUS.getDataType(), T_ORDER_0.STATUS.getUnqualifiedName());
```

You can then write a utility that does this automatically for you. In the future, we might provide an out of the box feature that allows for unqualifying arbitrary `Field` expressions, or a setting that would do that automatically for all columns if there is no ambiguity.

Right now, there's no such out of the box feature.

**Comment by lukaseder** [comment]
I've created an issue to add such a setting: https://github.com/jOOQ/jOOQ/issues/8893

**Comment by hyhub** [comment]
thank you so much
