### ISSUE TITLE
What is the reason for the difference in values when I use SQLite without setting it's memory? 

### ISSUE THREAD

**Issue by solangepaz** [jOOQ/jOOQ#8874]
I was doing some tests with JOOQ, using the TPC-H benchmark, SQLite and PostgreSQL.
I made the following query: `select count (*) from customer`.
With the following settings, I get the result of the query in ms:
JOOQ and SQLite in memory: **1.9ms**
JOOQ and SQLite without memory configuration: **1254.4ms**

JAVA JDBC and SQLite in memory: **1.9ms**
JAVA JDBC and SQLite without memory configuration: **549.8 ms**

What is the reason for the difference in values when I use SQLite without setting it's memory? Why is there such a big difference between 1254.4ms and 549.8ms?

**Comment by lukaseder** [comment]
Thank youv ery much for your message. There could be a lot of reasons, it's difficult to tell from your description what is the difference between your different settings.

For example: What is this memory configuration? How did you run the queries (in code). How to reproduce the results? Etc.

**Comment by solangepaz** [comment]
I ran this code ten times and figured out the average value for the runtime. The result of the query is **150000**.
The configuration without memory is:
```
Connection conn3 = DriverManager.getConnection("jdbc:sqlite:TPC-H.db");
Configuration configuration = new DefaultConfiguration().set(conn3);
Instant start2  = Instant.now();
int count =DSL.using(configuration)
                        .select(DSL.count())
                        .from(Customer.CUSTOMER)
                        .fetchOne(0, int.class);

System.out.println(count);
Instant end2  = Instant.now();
System.out.println("[JOOQ] Time taken without memory : " + Duration.between(start2,end2).toMillis());
```


The memory configuration is:

```
Connection conn1 = DriverManager.getConnection("jdbc:sqlite:file:memdb1mode=memory&cache=shared");
Statement stmt1 = conn1.createStatement();
stmt1.executeUpdate("restore from TPC-H.db");
Configuration configuration2 = new DefaultConfiguration().set(conn1);

Instant start3  = Instant.now();
int count2 =
                DSL.using(configuration2)
                        .select(DSL.count())
                        .from(Customer.CUSTOMER)
                        .fetchOne(0, int.class);

System.out.println(count2);
Instant end3 = Instant.now();
System.out.println("[JOOQ] Time taken with memory : " + Duration.between(start3,end3).toMillis());
```

**Comment by lukaseder** [comment]
Thank you very much for your update. Ideally, I'd love to see your entire benchmark in a reproducible way. Do note we have a template for this, which allows for easily reproducible bug reports: https://github.com/jOOQ/jOOQ-mcve

The code you posted now shows the difference between in-memory mode and file mode. With in-memory mode, there is a significant amount of I/O time that can be avoided in such embeddable databases like SQLite, H2, etc. I do think, however, that something must have gone wrong in your `1.9ms` benchmark, which is why I'd like to reproduce this on our side first.

What I can tell you now is that using jOOQ will have a significant initial overhead in the class loader, which you might be measuring as well. I recommend you use JMH for much better, reproducible results in your benchmarks: https://openjdk.java.net/projects/code-tools/jmh

If that's not possible, please do manually run a few warmup runs for both jOOQ and JDBC to get better results.

**Comment by solangepaz** [comment]
Thank you. I've been excluding the first executions of JOOQ and JDBC, which had much longer response times. I have already repeated the tests and the same value difference still exists.

**Comment by lukaseder** [comment]
I will be very happy to help you, but I *do* need to get the full benchmark code to reproduce this on my side. I cannot answer your question otherwise.

**Comment by solangepaz** [comment]
This is my code: https://github.com/solangepaz/jooqtest.git

**Comment by lukaseder** [comment]
Thanks a lot. I'll have a look and will update this issue with findings

**Comment by lukaseder** [comment]
A few questions:

- The example project contains the code you've pasted here, but what about the JDBC code to reproduce the comparison? 
- How did you implement *"I've been excluding the first executions of JOOQ and JDBC, which had much longer response times."* - I cannot see this from the example code.
- How can I create this TPC-H.db? Could you please include this db file in the example project, or reproduce a SQL script that can help create it?

Note again, I'd like to point out that we have an MCVE template (https://github.com/jOOQ/jOOQ-mcve), which helps produce MCVE's - part of what's essential about an MCVE is the "C" which stands for Complete. It will be much easier to discuss your findings, if I will be able to reproduce them on my side.

**Comment by solangepaz** [comment]
That's right now. I have run the several times and saved the values in an excel file, I did not delete it directly in the code.

**Comment by lukaseder** [comment]
Too bad. Surely, there's room for improvement in jOOQ, but there are also often inefficient benchmark setups, which produce results based on avoidable configuration. What I've often seen is that JDBC result sets are not really consumed, just iterated, which leads to an "unfair" advantage of JDBC logic.

Of course, jOOQ has overhead. For example, there is the part of SQL generation via internal `StringBuilder` instances, which does take some overhead in a benchmark (it's the biggest part). This can be mitigated by caching the SQL string in client code, but this is hardly ever useful or even necessary.

I would have loved to see the results on my own machine.

Closing this issue for now. Will be happy to reopen once I am able to reproduce your findings.
