### ISSUE TITLE
get timeStamp from record

### ISSUE THREAD

**Issue by Pro100Denysko** [jOOQ/jOOQ#8878]
### Your question:
I'm trying to get timestamp from table's row like this:
`dateAdd(timestampToDate(ORDER.SPECIMEN_DATE_RECEIVED), 14, DatePart.DAY)`

And I have util method to convert:
`public Date timestampToDate(Timestamp timestamp) {
    return new Date(timestamp.getTime());
  }`

But IDEA won't compile it. How can I do it easily?

### Versions:

- jOOQ: 3.10.0
- Java: 8.0
- Database (include vendor): MySQL
- OS: macOS
- JDBC Driver (include name if inofficial driver):com.mysql.cj.jdbc.Driver

**Comment by lukaseder** [comment]
Thank you very much for your message.

`ORDER.SPECIMEN_DATE_RECEIVED` is probably a `Field<Timestamp>` expression, not a `Timestamp` expression. So you cannot use your function to convert it. Do note that what you seem to want to achieve is conversion inside of your SQL statement, not in the client, so you probably just need a SQL cast:

```java
DSL.cast(ORDER_SPECIMEN_DATE_RECEIVED, SQLDataType.DATE)
```

I hope this helps

**Comment by Pro100Denysko** [comment]
Yes, Thanks!
