### ISSUE TITLE
Support ArrayRecord in DSL#all() and DSL#any()

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8890]
It would be nice if `ArrayRecord` (used by some DBs like Oracle) could be used with `DSL#all()` and `DSL#any()` to create quantified predicates.

**Comment by lukaseder** [comment]
Looking into this now. This is exclusively for Oracle usage. There isn't anything equivalent in Oracle, e.g. this doesn't work:

```sql
select 1
from dual
where 1 = any(ora_mining_number_nt(1, 2));
```

The Oracle way of doing this is:

```sql
select 1
from dual
where 1 in (select * from table(ora_mining_number_nt(1, 2)));
```

Granted, this looks like something PostgreSQL supports natively:

```sql
select 1
where 1 = any(array[1, 2])
```

But we cannot really overload the existing methods:

```java
public static <T> QuantifiedSelect<Record1<T>> all(Field<T[]> array) { ... }
public static <T> QuantifiedSelect<Record1<T>> any(Field<T[]> array) { ... }
```

And the existing other overloads are already confusing enough. Given how rarely this is useful (or requested by users), I'll reject this idea for now.
