### ISSUE TITLE
Did JOOQ support Predicates?

### ISSUE THREAD

**Issue by Pro100Denysko** [jOOQ/jOOQ#8896]
### Your question:
I have list of predicates. Can I append it to my SELECT using JOOQ?

**Comment by lukaseder** [comment]
Thank you very much for your message. Of course you can! Do note that *every* query you construct with jOOQ is a dynamic SQL query, even if it does not look this way. You're passing around expressions of different types, and nothing prevents you from assigning such expressions to local variables, or returning them from methods.

Here are two links to get you started with that way of thinking:

- https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql/
- https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq/

I hope this helps
