### ISSUE TITLE
Release 3.12: Make current master branch Java 6 compatible

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8900]
The current master branch is not quite Java 6 compatible yet. There are a few places in the code relying on newer JDK API.

**Comment by knutwannheden** [comment]
Trying to compile using an actual JDK 6, more problems came to light. There are for instance some dependencies like JPA which need to be downgraded.

The only problem I couldn't solve was that the JDK 6 looks like it might have a bug and fails to compile `FlashbackTable.java`:

```
/home/knut/ws/workspace-jooq-pro-java-6/jOOQ/jOOQ/src/main/java/org/jooq/impl/FlashbackTable.java:66: org.jooq.impl.FlashbackTable is not abstract and does not override abstract method declaresCTE() in org.jooq.QueryPartInternal
final class FlashbackTable<R extends Record, T>
      ^
```
We could probably remove this feature from the Java 6 build. Otherwise I suppose we will have to compile with a newer JDK, which might however not catch all problems.

**Comment by lukaseder** [comment]
> Trying to compile using an actual JDK 6, more problems came to light. There are for instance some dependencies like JPA which need to be downgraded.

Oh no, that's a bigger oversight on my part. Have I upgraded the JPA dependency recently? But it is optional / provided, so maybe that's not too big of an issue? Perhaps, we should have a separate issue for this...

> The only problem I couldn't solve was that the JDK 6 looks like it might have a bug and fails to compile FlashbackTable.java:

I will have a look at this on Monday

> We could probably remove this feature from the Java 6 build. Otherwise I suppose we will have to compile with a newer JDK, which might however not catch all problems.

The Java 6/7 build has been built with JDK 8 for years now, so if there are problems, they have not been affecting any customers yet.

It would obviously be better to build the Java 6/7 build with a JDK 6, but there might be even more compilation problems, which do not affect the runtime at all, so they're not very important for customers...

**Comment by knutwannheden** [comment]
> Oh no, that's a bigger oversight on my part. Have I upgraded the JPA dependency recently?

No, that was done nearly two years ago: d9fd8aa172c937e732b52a0d6ad9bec7bc334407.

> It would obviously be better to build the Java 6/7 build with a JDK 6, but there might be even more compilation problems, which do not affect the runtime at all, so they're not very important for customers...

The problem with `FlashbackTable.java` was the only one I encountered. But I agree that it probably makes more sense to build the Java 6 edition with a JDK 8 or even JDK 11.

**Comment by lukaseder** [comment]
> The problem with FlashbackTable.java was the only one I encountered. But I agree that it probably makes more sense to build the Java 6 edition with a JDK 8 or even JDK 11.

Could be that this is the only problem you've encountered during this compilation step/pass. Maybe, if you fix it, the next pass will produce new issues?

**Comment by lukaseder** [comment]
> with a JDK 8 or even JDK 11.

Not with JDK 11. The differences are too big already, e.g. with JAXB having been removed...
