### ISSUE TITLE
MiniJAXB should warn about unknown XML elements

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8918]
When `MiniJAXB` encounters an unknown XML element in the input (to `unmarshal()`) it should log a warning. At the moment the element is silently ignored.

**Comment by knutwannheden** [comment]
It would probably be best to implement this by "inverting" the unmarshaling logic of `MiniJAXB#unmarshal0()`. I.e. rather than looping over all JAXB-annotated fields of a class to find the corresponding XML element, the code should loop over the XML elements and find the corresponding Java field.

**Comment by lukaseder** [comment]
Yes, I agree. The main difference might be how we currently deal with absent source values (defaults). For example, we now always eagerly initialise lists, as opposed to what the classes do, themselves, which if I remember correctly, impacts how current implementations of `equals()` and `hashCode()` work, as well as how your new formatter / the previous `toString()` implementation works.

Perhaps we can mix both?

**Comment by knutwannheden** [comment]
I haven't really discovered any regressions here with our test suite. But of course we may be missing an important test.

Further, I now have more problems retrieving the line number to then report with the warning :-(

**Comment by lukaseder** [comment]
I don't know why I hadn't thought of this earlier, but we're still using a `DocumentBuilder` to parse the DOM, so maybe, we can use that to validate the input instead of doing it manually? This isn't really related to JAXB...

**Comment by knutwannheden** [comment]
Do you mean that we should use the `DocumentBuilder` to validate the XML against the XSD? That would then mean that the `MiniJAXB` interface would require additional methods where the schema can be specified (using `javax.xml.transform.Source`? :wink:), so that we know what schema to validate against.

**Comment by lukaseder** [comment]
Why do we need that? The namespace is in the annotations...

**Comment by knutwannheden** [comment]
> Why do we need that? The namespace is in the annotations...

Not sure what annotation you are referring to. We don't have any annotation regarding the schema in `Settings`, `Configuration`, or `InformationSchema` for instance.

**Comment by knutwannheden** [comment]
I see, the `@XmlSchema` annotation is on the Java package (`package-info.java` file). I will see if I can get that to work. Possibly we should attempt to load jOOQ's own schemas through the classloader.

**Comment by lukaseder** [comment]
> I see, the `@XmlSchema` annotation is on the Java package (package-info.java file).

Yes, that's what I meant.

> Possibly we should attempt to load jOOQ's own schemas through the classloader.

We had already done that previously, before this refactoring and removal of JAXB, in `GenerationTool`: https://github.com/jOOQ/jOOQ/blob/version-3.11.11/jOOQ-codegen/src/main/java/org/jooq/codegen/GenerationTool.java#L911

You can probably reuse some of that logic.

**Comment by knutwannheden** [comment]
Thanks for the pointer. Now `MiniJAXB` will of course have to do something similar to `GenerationTool`:

```java
        xml = xml.replace(
            "<configuration>",
            "<configuration xmlns=\"" + Constants.NS_CODEGEN + "\">");
```

Otherwise the XML won't validate :-(

**Comment by lukaseder** [comment]
Yes of course. Not just that, we also have to replace existing namespaces: https://github.com/jOOQ/jOOQ/blob/version-3.11.11/jOOQ-codegen/src/main/java/org/jooq/codegen/GenerationTool.java#L900

**Comment by knutwannheden** [comment]
This turned out to get a bit hairy... I wonder if we really should do it this way?
