### ISSUE TITLE
Consider using jaxb2-annotate-plugin in XJC compiler

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8923]
The [jaxb2-annotate-plugin](https://github.com/highsource/jaxb2-annotate-plugin) can be used to annotate the XSD schema and generate corresponding Java annotation in the JAXB classes. jOOQ could use this to generate @Deprecated annotations (e.g. on enum constants).

The plugin is [FreeBSD licensed](https://en.wikipedia.org/wiki/BSD_licenses#2-clause_license_(%22Simplified_BSD_License%22_or_%22FreeBSD_License%22)).

**Comment by lukaseder** [comment]
Very interesting indeed

**Comment by knutwannheden** [comment]
We apparently already use this plugin. All that is missing is some "annotations" in the XSD so that the plugin will generate the corresponding annotations in the generated Java classes.

In the scope of this issue we will add `@Deprecated` annotations everywhere where we already have an `@deprecated` tag in Javadoc.
