### ISSUE TITLE
DAOImpl should short circuit Result.map(RecordMapper) calls

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8929]
As a minor improvement, we could avoid allocating an intermediate `Result` instance in `DAOImpl` by passing the `mapper()` instance directly to the various `fetch()` methods.

The `AbstractResultQuery` implementation does not implement this optimisation yet, but once it does, we'll profit from it for free in `DAOImpl`

**Comment by JanecekPetr** [comment]
(I almost had a heart attack while reading this. I've been unsuccessfully pushing my colleagues to do the short-circuit for ages, and now you're saying it helps by not allocating the unnecessary `Record` in between!!! ... Except it doesn't, not yet. Uff.)

**Comment by lukaseder** [comment]
@JanecekPetr Well, you didn't have any performance problems, so this was a non-issue in your current application :-) But the good news is, you'll get around this allocation for free in the future.

In this particular case (when a `RecordMapper` is involved), there is no way around allocating a record, because the `RecordMapper` requires a `Record` to map to something else (obviously). There are other cases where the record allocation could be bypassed (only in the absence of `RecordListener` and possibly some other constraints).
