### ISSUE TITLE
Generate Sequence of Oracle Identity fields

### ISSUE THREAD

**Issue by jsauvain** [jOOQ/jOOQ#8941]
### Your question:
Hi there. Is there any possibility to retrieve the auto generated sequences of identity fields in jooq? Or even better, is it possible to generate them through codegen?

### Versions:

- jOOQ: 3.11.9
- Java: 8
- Database (include vendor): Oracle
- OS: -
- JDBC Driver (include name if inofficial driver): -

**Comment by lukaseder** [comment]
Thank you very much for your question. It probably is possible, but I'm not 100% sure what exactly you're trying to do :) Can you please elaborate?

**Comment by jsauvain** [comment]
Although it's possible to obtain the "currval" and "nextval" in another way it would be very handy to use the jooq provided method, which expects a Sequence.
Example: 

`dslContext.currval(table.getIdentity)`

instead of

`dslContext
			.select(max(table.getIdentity().getField()))
			.from(table)
			.fetchOneInto(Integer.class);`

**Comment by lukaseder** [comment]
Oh I see, thanks for the clarification. That could be useful indeed. I have created a feature request for this: #8946 

However, I'm not convinced there is a sound way to retrieve the current value of an identity in a database agnostic way in jOOQ. There are a lot of open questions like that of transactionality, caching, etc.

In Oracle, for examples, identities are sequence backed, and a sequence lives outside of your user transaction. It may have a set of cached values, such that the "current value" is not really a very reliable bit of information. If you retrieve it in your transaction, a different transaction (or even your own!) might still produce a lower *or* higher value than the current value you've fetched.

So, I'm curious what kind of use-case you're having that would lead to this requirement?

**Comment by jsauvain** [comment]
We are using a dockerized Oracle database for Unit Tests and due to performance issues we do not reset Identities after each test. For that case we do need to retrieve the last inserted Identity to cleanly assert the given data. In that case the Identity is promised not to generate lower value and there is clearly no race condition.
When using JOOQ codegen there is a method which returns all Sequences. (Public.PUBLIC.getSequences()). In my opinion the generated sequences of the identities should be in that list too.

**Comment by lukaseder** [comment]
I see. One workaround would be to run something like this:

```sql
with
  function current_value(p_table_name varchar2) return number is
    v_result number;
    v_default varchar2(4000);
  begin
    for rec in (
      select *
      from user_tab_cols
      where table_name = p_table_name
      and data_default is not null
      and identity_column = 'YES'
    )
    loop
      v_default := rec.data_default;
      
      for s in (
        select sequence_name
        from user_sequences
        where v_default like '%' || sequence_name || '%'
      )
      loop
        execute immediate 'select ' || s.sequence_name || '.currval from dual' into v_result;
        return v_result;
      end loop;
    end loop;
    
    return null;
  end;
select *
from (
  select table_name, current_value(table_name) c
  from user_tables
)
where c is not null;
/
```

This might produce `ORA-08002 sequence %s.CURRVAL is not yet defined in this session`, in case of which you might need to call `nextval` instead of `currval` - which should be OK for the sake of your use case as well.

The reason why the code generator does not generate any system generated sequences is because they're an implementation detail that most users do not want to be aware of, see #6523. We could, however, include some code generation flags that allow for including such system-generated artefacts (not just sequences)

I agree that in your case, it would have been useful if the sequences had been part of the code generation output: #8947 - but beware that you would probably still have to run a query like the above to associate generated sequence names with the respective table/identity.

**Comment by lukaseder** [comment]
I'm closing this as answered. I think your request will be addressed via #8947. Please let me know if you have any additional questions and I'll be very happy to assist.

**Comment by lukaseder** [comment]
A more robust query:

```sql
with
  function current_value(p_table_name varchar2) return number is
    v_current number;
  begin
    for rec in (
      select sequence_name
      from user_tab_identity_cols
      where table_name = p_table_name
    )
    loop
      execute immediate 
        'select ' || rec.sequence_name || '.currval from dual'
      into v_current;
      return v_current;
    end loop;
     
    return null;
  end;
select *
from (
  select table_name, current_value(table_name) current_value
  from user_tables
)
where current_value is not null
order by table_name;
/
```

**Comment by lukaseder** [comment]
In fact, you could use jOOQ's plain SQL templating API as well on `user_tab_identity_cols.sequence_name`, using `DSL.sequence()` and then call `Sequence.nextval()` on those sequences. But storing the above as a view might lead to better results
