### ISSUE TITLE
Java 8+ version of the code generator should generate diamond operator

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8953]
The code generator of the Java 8+ distributions should generate diamond operators where possible.

Known constructor calls without diamond operators include:

- [ ] `Queues.java` (Oracle)
- [ ] `Sequences.java`

**Comment by knutwannheden** [comment]
For `Sequences.java` we have refactored the code generation to call `Internal#createSequence()` rather than directly calling the `SequenceImpl` constructor. But we should be able to generate the call without a generic type parameter for Java 8+. I.e. instead of:
```java
    public static final Sequence<Integer> S_AUTHOR_ID = Internal.<Integer> createSequence("S_AUTHOR_ID", Test.TEST, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, 2000000000, false, null);
```
we can generate:
```java
    public static final Sequence<Integer> S_AUTHOR_ID = Internal.createSequence("S_AUTHOR_ID", Test.TEST, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, 2000000000, false, null);
```

**Comment by lukaseder** [comment]
> But we should be able to generate the call without a generic type parameter for Java 8+

Could it be that this would not have compiled in Java 6, e.g. in the presence of a data type binding?

**Comment by lukaseder** [comment]
I mean, there must have been a reason...

**Comment by knutwannheden** [comment]
Not necessarily. I may just have missed the opportunity to simplify the code a bit.

**Comment by lukaseder** [comment]
I see. I must have confused this with some other type witness I vaguely remembered.

**Comment by knutwannheden** [comment]
For `Queues.java` I wonder if it wouldn't make more sense to add an `@Pro` annotated factory method to the `Internal` class. That way we could avoid the generic type parameter also for the Java 6 edition. Thoughts?

**Comment by lukaseder** [comment]
Yeah, why not

**Comment by knutwannheden** [comment]
> Yeah, why not

Using the `[pre-java-8]` in the code generator would make the code a bit weird to read.
