### ISSUE TITLE
Generator outputs duplicate method (not compilable)

### ISSUE THREAD

**Issue by cdalexndr** [jOOQ/jOOQ#8967]
Using `org.jooq.codegen.DefaultGenerator` with `org.jooq.codegen.DefaultGeneratorStrategy`
input schema `pg_catalog` for a Postgres 10 DB, outputs duplicate method in class `PgStatGetSubscription`:

```
    /**
     * Get the <code>subid</code> parameter OUT value from the routine
     */
    public Long getSubid() {
        return get(SUBID);
    }

    /**
     * Get the <code>subid</code> parameter OUT value from the routine
     */
    public Long getSubid() {
        return get(SUBID);
    }
```
- jOOQ: 3.11.9
- Java: 8
- Database (include vendor): Postgres 10
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:9.4.1211

**Comment by lukaseder** [comment]
Thank you very much for your report. Curious why would that not be an `IN OUT` parameter, but two separate parameters instead?

```sql
CREATE OR REPLACE FUNCTION pg_catalog.pg_stat_get_subscription(subid oid, OUT subid oid, OUT relid oid, OUT pid integer, OUT received_lsn pg_lsn, OUT last_msg_send_time timestamp with time zone, OUT last_msg_receipt_time timestamp with time zone, OUT latest_end_lsn pg_lsn, OUT latest_end_time timestamp with time zone)
 RETURNS record
 LANGUAGE internal
 STABLE PARALLEL RESTRICTED
AS $function$pg_stat_get_subscription$function$
;

COMMENT ON FUNCTION pg_catalog.pg_stat_get_subscription(oid) IS 'statistics: information about subscription';
```

We'll investigate this soon.

**Comment by lukaseder** [comment]
The workaround is to exclude the function from being generated using the usual `<exclude>` tag.

**Comment by cdalexndr** [comment]
There are too many functions and objects in pg_catalog to search and use exclude. I disabled pg_catalog generation.
This issue is preventing me for using postgres default functions and return types (ex: TsStat), and I have to create manual templates and field names.

**Comment by lukaseder** [comment]
Thanks for the update, @cdalexndr. A quick search yields these 5 function names that seem to have the problem:

```sql
select 
  routine_name, 
  specific_name, 
  parameter_name, 
  array_agg(p.data_type order by ordinal_position), 
  array_agg(p.ordinal_position order by ordinal_position)
from information_schema.parameters p
left join information_schema.routines r 
  using (specific_catalog, specific_schema, specific_name)
where routine_schema = 'pg_catalog'
and parameter_name != ''
group by 
  routine_name, 
  specific_name, 
  parameter_name
having count(*) > 1
;
```

Result:

```
routine_name                       |specific_name                           |parameter_name|array_agg        |array_agg|
-----------------------------------|----------------------------------------|--------------|-----------------|---------|
pg_create_logical_replication_slot |pg_create_logical_replication_slot_3786 |slot_name     |{name,name}      |{1,4}    |
pg_create_physical_replication_slot|pg_create_physical_replication_slot_3779|slot_name     |{name,name}      |{1,4}    |
pg_replication_slot_advance        |pg_replication_slot_advance_3878        |slot_name     |{name,name}      |{1,3}    |
pg_stat_get_activity               |pg_stat_get_activity_2022               |pid           |{integer,integer}|{1,3}    |
pg_stat_get_subscription           |pg_stat_get_subscription_6118           |subid         |{oid,oid}        |{1,2}    |
```

All of these functions use the `OUT` parameter syntax to return a `record`. I wonder if we can work around this easily in the code generator, or possibly automatically exclude these functions from being generated until we know how to fix this.

**Comment by lukaseder** [comment]
We could run this query here to fetch parameters:

```sql
select 
  routine_name, 
  specific_name, 
  parameter_name,
  parameter_mode,
  count(*) over (partition by specific_name, parameter_name order by parameter_mode, ordinal_position)
from information_schema.parameters p
left join information_schema.routines r 
  using (specific_catalog, specific_schema, specific_name)
where routine_schema = 'pg_catalog'
and specific_name = 'pg_stat_get_subscription_6118'
and parameter_name != ''
;
```

It yields:

```
routine_name            |specific_name                |parameter_name       |parameter_mode|count|
------------------------|-----------------------------|---------------------|--------------|-----|
pg_stat_get_subscription|pg_stat_get_subscription_6118|last_msg_receipt_time|OUT           |    1|
pg_stat_get_subscription|pg_stat_get_subscription_6118|last_msg_send_time   |OUT           |    1|
pg_stat_get_subscription|pg_stat_get_subscription_6118|latest_end_lsn       |OUT           |    1|
pg_stat_get_subscription|pg_stat_get_subscription_6118|latest_end_time      |OUT           |    1|
pg_stat_get_subscription|pg_stat_get_subscription_6118|pid                  |OUT           |    1|
pg_stat_get_subscription|pg_stat_get_subscription_6118|received_lsn         |OUT           |    1|
pg_stat_get_subscription|pg_stat_get_subscription_6118|relid                |OUT           |    1|
pg_stat_get_subscription|pg_stat_get_subscription_6118|subid                |IN            |    1|
pg_stat_get_subscription|pg_stat_get_subscription_6118|subid                |OUT           |    2|
```

Whenever that `count` value is `count > 1`, we would log a warning and suffix the count value to the parameter value in generated output. That's not a solution, but a workaround for the compilation problem.

**Comment by lukaseder** [comment]
The window function needs a filter first `filter (where parameter_name != '')`. To prevent this functionality from applying to unnamed parameters

**Comment by lukaseder** [comment]
Hmm, no. That would produce the wrong parameter name in the model. Instead, we should use the `GeneratorStrategy` default implementations, to fix this only in generated code, not in the model.

**Comment by lukaseder** [comment]
Fixed in 3.13.0. I'm a bit reluctant of backporting this fix to 3.12.4 as this area of the code generator might introduce subtle regressions that I'm not seeing in integration tests right now.

The workaround is to use `<exclude>`, e.g. with a query like the above.

**Comment by cdalexndr** [comment]
Note that I see duplicate fields also in **TableImpl** generated implementor, not only in routines:
```
public class TsStat extends TableImpl<TsStatRecord> {
..............
    /**
     * The column <code>pg_catalog.ts_stat.word</code>.
     */
    public final TableField<TsStatRecord, String> WORD = createField("word", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>pg_catalog.ts_stat.word</code>.
     */
    public final TableField<TsStatRecord, String> WORD = createField("word", org.jooq.impl.SQLDataType.CLOB, this, "");
```

**Comment by cdalexndr** [comment]
For testing I suggest you generate "pg_catalog" schema, and also install some [extensions](https://www.postgresql.org/docs/current/contrib.html) with additional types and routines (ex: ltree), and check that the generated classes can be compiled.

**Comment by lukaseder** [comment]
Thanks for your additional comment. That's a different problem than this one here: https://github.com/jOOQ/jOOQ/issues/4055

I'll also look into whether we can work around it.

> For testing I suggest you generate "pg_catalog" schema, and also install some extensions with additional types and routines (ex: ltree), and check that the generated classes can be compiled.

We are aware of these problems and do test with `pg_catalog`. However, in the case of #4055, many more routines (including your own) might be affected, and a workaround is less obvious than here.
