### ISSUE TITLE
An exception in ExecuteListener#start is not routed to ExecuteListener#exception

### ISSUE THREAD

**Issue by JanecekPetr** [jOOQ/jOOQ#8968]
### Expected behavior and actual behavior:

An exception thrown by `ExecuteListener#start` is not routed to other (any) listeners via their `exception()` method. This is in contrast to all other ExecuteListener lifecycle methods which pass thrown exceptions down the lifecycle.

I'd expect exceptions thrown by `start()` to be routed to `exception()`, too. Mostly based on the `ExecuteListener#exception` method's JavaDoc:

> Called in the event of an exception at any moment of the execution lifecycle.

If this gets fixed, it will probably only fixed in 3.12. Instead of a fix in 3.11, I'd like to see an explicit mention in the JavaDocs, like this: "*3.11*: Note that unlike all other lifecycle methods, exceptions thrown from `start()` will not get passed to `exception()`."

### Steps to reproduce the problem:

Throw from `ExecuteListener#start`, try to react in `ExecuteListener#exception`. No luck.

### Implementation discussion

The reason is clear:

```java
ExecuteListener listener = ExecuteListeners.get(ctx);
```

which starts the lifecycle, is called before the all-seeing try-catch block. However, the naïve fix to just shove the call into the try-catch block might not be the best idea, either. What should happen if the listener instantiation (before the `start()` method) threw? We do not want to call `exception()` on uninitialized listeners / null. A nice fix might be to split the `ExecuteListeners` constructor and the `start()` method which currently is in the constructor.

Theoretically the creation of the listeners is before the lifecycle (and, therefore, before the try-catch), while `start()` should already be called in the lifecycle (and in the try-catch).

Oh, and make sure `CursorImpl`'s constructor and `fetch()` methods get treated, too.  
That surely won't lead to double/triple `start()` calls, will it? :)

### Versions:

- jOOQ: 3.11.11
- Java: 8u201
- Database: Postgres 9.5
- OS: Windows 10
- JDBC Driver: pgjdbc 42.2.2

**Comment by lukaseder** [comment]
Thank you very much for your report. This is interesting, indeed. I wonder if exceptions thrown from `end()` would make it there, too.

I agree that such exception events should be propagated (although, what's the motivation of throwing an exception from within a listener?), but it will not be a trivial fix.

We'll look into a few listener lifecycle problems soon.

**Comment by JanecekPetr** [comment]
> what's the motivation of throwing an exception from within a listener?

The listener can sometimes forbid the execution of the query, cancelling it by throwing a `PermissionDeniedDataAccessException`. This can be e.g. because of a manual admin intervention, or because the DB has reached a preconfigured threshold size.

The mechanism works nicely, I was simply surprised to see the exception show up in a different context than expected.

> it will not be a trivial fix ... We'll look into a few listener lifecycle problems soon.

Thanks, this is nothing critical. Looking forward to 3.12!

**Comment by lukaseder** [comment]
> The listener can sometimes forbid the execution of the query

Very interesting use case! Sounds like a good blog post :)

Actually, I've had a closer look while validating your use case. At first, it sounds like not exactly the perfect place to do this validation, because there's no *formal* guarantee that `start()` is the first thing jOOQ does with a `Query` when executing it. For example, we're currently calling `isExecutable()` first. You could have `settings.getExecuteDeleteWithoutWhere()` turned on, in case of which we'll also throw an exception (which also isn't passed to that handler).

We could argue that this is wrong, and that exception should also be passed to an execute listener...

In any case, after closer introspection, I think this issue is much simpler to fix than I initially thought. I'll review this again for 3.12

**Comment by lukaseder** [comment]
Reviewing again for inclusion in 3.13. We have new integration tests that trigger already during the `start()` event, and thus lead to unbalanced lifecycle statistics.

**Comment by lukaseder** [comment]
Done. This test now passes:

```java
public class ExecuteListenerTest {

    public DSLContext ctx(ExecuteListener listener) {
        return DSL.using(new DefaultConfiguration()
            .set(new MockConnection(Mock.of(1)))
            .set(listener)
        );
    }

    @Test
    public void testStartThrowing() {
        // [#8968] Exceptions from the execute listener lifecycle should be routed to ExecuteListener::exception

        StartThrowing l = new StartThrowing();
        E e = assertThrows(E.class, () -> ctx(l).delete(table("x")).execute());
        assertTrue(l.exceptionCalled);
        assertEquals("StartThrowing", e.getMessage());
    }

    static class E extends RuntimeException {
        public E(String message) {
            super(message);
        }
    }

    static class StartThrowing extends DefaultExecuteListener {
        boolean exceptionCalled = false;

        @Override
        public void start(ExecuteContext ctx) {
            throw new E("StartThrowing");
        }

        @Override
        public void exception(ExecuteContext ctx) {
            exceptionCalled = true;
            assertTrue(ctx.exception() instanceof E);
            assertEquals("StartThrowing", ctx.exception().getMessage());
        }
    }
}
```

**Comment by lukaseder** [comment]
I'm always a bit reluctant to backport such substantial changes of behaviour to previous patch releases, as the results may be quite surprising to users who have grown used to the current behaviour.

As such, I won't backport this fix. 3.13 is due very soon, though (within the next 1-2 weeks).
