### ISSUE TITLE
How to create a cross-database DSLContext when execute select ?

### ISSUE THREAD

**Issue by JamesZBL** [jOOQ/jOOQ#8969]
### Your question:
How to create a cross-database DSLContext when execute select ?

### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your message.

This would depend on the database product you're using. Most database products have a different understanding of what a "database" is, and whether "cross database" queries are possible.

I'm very happy to elaborate if you're willing to illustrate a bit more what you're trying to do (and please, do include the database product)

**Comment by JamesZBL** [comment]
I am using MySQL. There was two schemes, I need to create a query which contains a join step related to both that two schemes.

**Comment by lukaseder** [comment]
Well, can you show what you tried and where you failed?

Hint: The code generator allows you to generate code for several schemas, and then the cross-schema (or cross-database in MySQL speak) concern will become a non-issue, immediately. There isn't really anything special to querying multiple schemas in jOOQ.
