### ISSUE TITLE
jOOQ-meta should query dictionary views for column existence rather than the column itself

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8972]
In order to reliably detect the dialect version in the code generator, we query the database's dictionary views and check if there is an error in the query. For example, in PostgreSQL, to verify if we can use PostgreSQL 11 features, we run a query like this one:

```sql
select "pg_catalog"."pg_proc"."prokind" from "pg_catalog"."pg_proc" where 1 = 0
```

If this works, we're on PostgreSQL 11+. If it fails with an error, we're on PostgreSQL 10 or less. 

Unfortunately, this technique can lead to cosmetic side effects, as JDBC drivers (or other tooling) may decide to log an error message, see e.g. #8970. In order to avoid these error messages, we should better query the database's dictionary views for this column's existence. We already have the equivalent of `INFORMATION_SCHEMA.COLUMNS` in each dialect, so we can get the same effect without the potential side effect using a harmless query, such as:

```sql
select exists (
  select 1 
  from information_schema.columns
  where table_schema = 'pg_catalog'
  and table_name = 'pg_proc'
  and column_name = 'prokind'
);
```

Only these dialects are affected by this change:

- H2
- MySQL
- Oracle
- PostgreSQL
- SQL Server

Other dialects currently do not run version specific table/column existence checks.

**Comment by JanecekPetr** [comment]
You, sir, are a gentleman and a scholar! <3

**Comment by lukaseder** [comment]
Thanks ;)
