### ISSUE TITLE
Warnings in Generated Code: byte[] vs byte...

### ISSUE THREAD

**Issue by chriszwickerocteris** [jOOQ/jOOQ#8974]
#### Expected

No (unsuppressed) warnings in generated code

#### Actual

In code generated from the below table, there will be a method in `FileRecord` like the following

```java
@Override
public FileRecord value2(byte... value) {
    setContent(value);
    return this;
}
```

This raises the warning `Varargs methods should only override or be overridden by other varargs methods unlike FileRecord.value2(byte...) and Record2<String,byte[]>.value2(byte[])`

Interestingly, the method `#values` is generated as follows (with `byte[]` instead of `byte...`):

```java
@Override
public FileRecord values(String value1, byte[] value2) {
    value1(value1);
    value2(value2);
    return this;
}
```

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

Generate code for a table like

```sql
create table base.file (
  id              varchar(100) not null,
  content         bytea
 ,constraint file$c$p primary key (id)
);
```

### Versions:

- jOOQ: 3.11.11
- Java: openjdk version "11.0.1" 2018-10-16
- Database (include vendor): Postgres
- OS: MacOs Mojave
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.5

**Comment by lukaseder** [comment]
Thank you for your message. Please use the `<varargSetters>false</varargSetters>` configuration in your code generator configuration to turn off this feature.

**Comment by chriszwickerocteris** [comment]
Thanks for your quick answer - that works for me. Would be nice not having to manually (and globally) take that decision if it only affects certain fields, no?

**Comment by lukaseder** [comment]
> Would be nice not having to manually (and globally) take that decision if it only affects certain fields, no?

It affects all array fields, so in my opinion, this really is an all-or-nothing question...
