### ISSUE TITLE
How should I handle really big queries?

### ISSUE THREAD

**Issue by smedelyan** [jOOQ/jOOQ#8977]
### Your question:
I have a dynamically generated query that will most likely exceed the limit of 2 billion symbols (for PostgreSQL). Is  "divide it in pieces and batch-execute them together" the only option I can go for? Or I can safely execute it in one piece and jOOQ will perform some kind of magic automagically for me?

### Versions:
- jOOQ: 3.11.11
- Java: 8
- Database (include vendor): PostgreSQL 9.6
- OS: Ubuntu 18.04
- JDBC Driver (include name if inofficial driver): 42.2.6

**Comment by lukaseder** [comment]
Thank you very much for your question. That is a pretty interesting situation! By 2 billion symbols, you mean the SQL string will reach 2GB? This would eventually be a problem for any JVM based library, as a `String` cannot have more than 2^31 bytes, being backed by a `byte[]`. But long before reaching that size, you will probably run into memory issues.

Why does the SQL string get so big? I'm quite sure there are much better ways to express the same query, even in a single query, rather than separate ones. Would you mind shedding some light into what you're doing?

**Comment by smedelyan** [comment]
Thanks for responding that fast!

In my case I have an aggregated table like:

| field one | field two | field three | field four |
| ---------: | ---------: | -----------: | ---------- |
| null         |   "two"    |    null         | "four"       |
| "one"      |    null      |    null         | "four"       |

etc

This table may get really big: the least known size is about 500k rows and the averageI can imagine is about 10M rows.

User is allowed to pass a configuration file into a program that is used afterwards to delete or filter rows from that table, and filterings is applied like:
```yaml
keepOnly:
  - col: field1
    val: "one"
  - col: field2
    val: "two"
  - col: field1
    val: "one again"
```

So there may be quite lots of those "filters".

What I'm trying to do is to compose one big query with dynamically chaining conditions. Though, after your comments it does not seem right to me =)

**Comment by lukaseder** [comment]
Well, I'm not seeing a case here where you couldn't avoid 2GB of SQL text. I mean, your particular example would lead to:

```sql
SELECT *
FROM t
WHERE field1 IN ('one', 'one again')
AND field2 IN ('two')
```

Notice that you can probably combine several filters into one... This is definitely something jOOQ is very good at helping you with.

Some resources to get you started:

- https://www.jooq.org/doc/latest/manual/sql-building/dynamic-sql/
- https://blog.jooq.org/2017/01/16/a-functional-programming-approach-to-dynamic-sql-with-jooq/

**Comment by lukaseder** [comment]
... we'll be happy to help you with any specific questions you may have

**Comment by smedelyan** [comment]
That's a good point, @lukaseder .

But given this table can have arbitrary number of values and each of them is of arbitrary length, there's is still a case when the query length may get exceeded. 

It seems that I'd better issue jOOQ's batches to overcome this, what do you think?

**Comment by lukaseder** [comment]
Is this table just some random EAV store? Why? Is there no way you could normalise this schema?

I cannot give you any advice here without knowing more about your schema design. All I'm saying is that it is very unlikely you really *have to* write queries of 2GB length. There's *quite likely* a better approach, but this is out of scope for jOOQ to answer. Maybe, try asking a question on https://stackoverflow.com ?

**Comment by smedelyan** [comment]
> Is this table just some random EAV store? 

No, it isn't. Actually the database is normalized so the above table is composed of IDs to use in JOINs (I put the values just for convenience).

I have lots of objects in the database and user is allowed to select / filter these objects externally by providing configuration file like one above. 

As an example we can consider a some kind of "literature service" that allows user to download all wanted literature. 
Suppose we have for types of "objects" :
```yaml
giveMe:
- type: BOOK
  value: Book name or something

- type: MAGAZINE
  value: Magazine name, issue date, etc

- type: BOOK_SERIES
  value: Series name, author name, etc

- type: ARTICLE
  value: Science stuff goes here
```

I have a pre-aggregated table with all known "objects" that are eligible for user to "download" like:

| book_id | magazine_id | book_series_id | article_id |
|---------|-------------|----------------|------------|
|   null  |      1      |      null      |    null    |
|    2    |     null    |      null      |    null    |
|    3    |     null    |       10       |    null    |


If they want they can provide quite a long list of all needed objects (most likely automatically constructed with some tool), and then my application filters all known objects and performs all the work required to get needed objects for user.


I hope this example sheds some light on my case. At the moment I think I need to filter objects iteratively to avoid exceeding the SQL-query length limit. 

Thank you for the help, Lukas! I love jOOQ :heart_eyes: !!!
