### ISSUE TITLE
Modify a Record

### ISSUE THREAD

**Issue by lalithsuresh** [jOOQ/jOOQ#8983]
### Your question:

Given an instance of a Record, is there a way to modify the value of one of its fields?

For example, given a Record: ("C1" = 1, "C2 = 100), how do I produce a new Record ("C1" = 1, "C2" = 4) without involving the database? 

My goal is to transform an instance of Result<? extends Record> into another Result<? extends Record> where values for one of the columns are rewritten from Java. I cannot involve the database in this modification step.

### Versions:

- jOOQ: 3.11.11
- Java: 12.0.1

**Comment by lukaseder** [comment]
Use the `DSLContext.newRecord()` and `DSLContext.newResult()` methods. To copy content from one record to another, you can use `Record.from(...)`.

I hope this helps
