### ISSUE TITLE
Potential NumberFormatException in FilenameComparator

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8984]
In `FilenameComparator#compare()` we have this line: https://github.com/jOOQ/jOOQ/blob/df54d660f415045108b110d817de02ecc92ad6cc/jOOQ-meta/src/main/java/org/jooq/meta/tools/FilenameComparator.java#L85

`c2` is compared to `0` rather than `'0'` which could thus result in a `NumberFormatException` when called like this for example: `compare("0", new String(new byte[] { 0 }))`.

**Comment by lukaseder** [comment]
Nice catch!
