### ISSUE TITLE
Move DDLDatabase DDL simulation via H2 to jOOQ-extensions and implement it through org.jooq.Meta

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#8986]
The current DDL simulation using H2 in `DDLDatabase` is quite useful and works in 80%-90% of the cases where users do not use any fancy vendor specific features.

This simulation could be a quick win also for the jOOQ core module (via `jOOQ-extensions`, see #8985) and allow for simulating DDL via H2, providing access to the schema using `org.jooq.Meta` via the default `org.jooq.Meta` implementation `org.jooq.impl.MetaImpl`.

**Comment by knutwannheden** [comment]
Looking at the existing `DDLDatabase` code I was wondering a bit why it wasn't added to `jOOQ-meta` to begin with, since there aren't really any compile time dependencies. But I suppose the reason was that then a Maven dependency can be added for H2, so that it will always be available at runtime.

**Comment by knutwannheden** [comment]
Internally `DDLDatabase` uses `FilePattern` from `jOOQ-meta`. Since this class was added as part of 3.12 the most straight-forward approach would be to move `FilePattern` to the `jOOQ` module.

**Comment by knutwannheden** [comment]
For now I decided to leave the utility classes in `jOOQ-meta`.

**Comment by knutwannheden** [comment]
`DDLDatabase` new internally uses the (`@Internal` annotated) class `DDLDatabaseInitializer` in Maven module `jOOQ-extensions`. As a next step a `MetaProvider` will be built which loads the H2 database's schema into an in-memory `org.jooq.Meta`  representation.

**Comment by knutwannheden** [comment]
For the `DDLMetaProvider` we need to work out an API for supplying the list of DDL scripts. Here the `FilePattern` utility might again become useful.

**Comment by knutwannheden** [comment]
Implementing the caching of the `Meta` information in `DDLMetaProvider`, so that the in-memory H2 database can be discarded, proved to be more work than initially anticipated.

I also noticed that the `MetaImpl` implementation doesn't implement all API methods (presumably because the corresponding information cannot be extracted from JDBC metadata). Two examples being `Table#getKeys()` (only contains the primary key) and `Table#getIdentity()`.

**Comment by knutwannheden** [comment]
> For the `DDLMetaProvider` we need to work out an API for supplying the list of DDL scripts. Here the `FilePattern` utility might again become useful.

For now I dediced to use an `URL...` varargs parameter, as this works well both for classpath resources as well as files.

**Comment by lukaseder** [comment]
> Looking at the existing DDLDatabase code I was wondering a bit why it wasn't added to jOOQ-meta to begin with, since there aren't really any compile time dependencies. But I suppose the reason was that then a Maven dependency can be added for H2, so that it will always be available at runtime.

The implicit H2 dependency would then have to be documented rather than it working out of the box without any further configuration. From a UX perspective, that is quite better, especially as we can replace that internal dependency any time we want.

> Internally DDLDatabase uses FilePattern from jOOQ-meta. Since this class was added as part of 3.12 the most straight-forward approach would be to move FilePattern to the jOOQ module. 

The new DDL simulation in the jOOQ core library takes a pre-ordered List of files or SQL strings as input. Ordering those files is out of scope for what we need to move into the core. So indeed, these things should be kept in jOOQ-meta for now.

> For now I dediced to use an URL... varargs parameter, as this works well both for classpath resources as well as files.

A `String...` overload would definitely be desireable, probably others, too.

**Comment by lukaseder** [comment]
> A String... overload would definitely be desireable, probably others, too.

In fact, I wonder if we should implement a "Source" that can be created from:

- `String`
- `InputStream`
- `Reader`
- `URL`
- `URI`
- `File`
- `Path` (Java 7+)

The XML libraries have a similar `Source` type. Ours would obviously be more easy to use. This `Source` could then be used in other API as well, e.g. loading CSV files.

**Comment by knutwannheden** [comment]
> The XML libraries have a similar `Source` type. Ours would obviously be more easy to use. This `Source` could then be used in other API as well, e.g. loading CSV files.

`URL` seemed like a good lowest common denominator for the "descriptor-typed sources" (`URL`, `URI`, `File`, and `Path`), but to also support other "descriptor-less sources", a new `Source` type indeed sounds like a good idea.

**Comment by lukaseder** [comment]
I'd say the least common denominator for any string content in the JDK is a `Reader` (as `InputStream` also needs an encoding). My thinking is that `URL` has a lot of flaws and can probably not even represent all "descriptor typed sources" that we could think of. Besides, it's an awful default from a UX perspective, even if it might be convenient for us as maintainers.

In any case, I've done this too many times throughout jOOQ already, so we definitely need a concept of `Source` (something to read string content from) and `Target` (something to write string content to). Names might be different.

This is so generic, it could even be an independent library.

**Comment by lukaseder** [comment]
I don't think we should add this additional feature (source / target) in jOOQ 3.12 anymore. For now, I'd say that `String...` would be a good method parameter type. Most API that reads from some set of source types supports `String` as a convenience parameter type, and for this particular issue here, it is good enough to leave the whole file handling logic in `DDLDatabase`

**Comment by knutwannheden** [comment]
OK. The biggest problem I see with `String...` is that it will require loading the entire DDL files into memory, which isn't very nice. Another problem is that error messages can't refer to a "handle" for the DDL script (like the file path or URL). But I suppose for 3.12 we could live with these problems.

**Comment by lukaseder** [comment]
> OK. The biggest problem I see with String... is that it will require loading the entire DDL files into memory, which isn't very nice

Agreed, and `Iterable<String>` is not a good solution either, because it will prevent overloading later due to generic type erasure. Let's discuss this on Thursday. Perhaps we do need to design an incomplete `Source` prototype already now.

> Another problem is that error messages can't refer to a "handle" for the DDL script (like the file path or URL). But I suppose for 3.12 we could live with these problems.

Yes, we will think about these things more thoroughly in 3.13

**Comment by lukaseder** [comment]
> Agreed, and Iterable<String> is not a good solution either, because it will prevent overloading later due to generic type erasure. Let's discuss this on Thursday. Perhaps we do need to design an incomplete Source prototype already now.

Given that we're likely to have `String...`, `URL...` and other overloads, and also perhaps a generic `Source...` and `Collection<? extends Source>` overload, I think that `String...` is a safe choice for now

**Comment by lukaseder** [comment]
Added a new feature request for these `Source` and `Target` types: https://github.com/jOOQ/jOOQ/issues/9043

**Comment by lukaseder** [comment]
As discussed today, we've re-evaluated the pros and cons of:

1. Making the existing H2 dependency explicit in a new `jOOQ-extensions` module
2. Hiding the dependency and preventing an additional module

The price of 1) is the fact that we need an internal but public API to expose the implementation of `DDLDatabaseInitializer` to `DDLDatabase`. The price of 2) is nothing right now, as we're not documenting this feature yet, `DDLDatabase` can handle the implied dependency on H2 itself, and power users who want to work with this feature already can know about the current implementation details.
