### ISSUE TITLE
How to check if TIMESTAMP is in current month

### ISSUE THREAD

**Issue by raderio** [jOOQ/jOOQ#8992]
I have a column creation_time as TIMESTAMP, how to check if creation_time is in current month?

Database: PostgreSQL

**Comment by knutwannheden** [comment]
Thank you very much for your request.

This question is mostly a question about SQL and requires knowing which vendor specific built-in functions to use. In your case you want to produce an SQL predicate like `creation_time >= date_trunc('month', current_timestamp)`.

To achieve this with jOOQ you would write:

```java
MY_TABLE.CREATION_TIME.greaterOrEqual(trunc(currentTimestamp(), DatePart.MONTH))
```

(As a more concise alternative to `greaterOrEqual()` you can also use the equivalent `ge()`.)

Please reopen if this doesn't answer your question.
