### ISSUE TITLE
Add Javadoc to XJC generated with-methods

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8995]
The `with`-methods currently generated by XJC don't have any Javadoc. If possible I think it would make sense for them to have the same documentation as the corresponding `set`-method.

**Comment by knutwannheden** [comment]
I was just going to report an issue against https://github.com/javaee/jaxb2-commons, but it looks pretty dead to me :-(

**Comment by lukaseder** [comment]
That was a premature effort by someone, and I think some legal folks vetoed :) Besides, it's all Jakarta EE now, so maybe try there?

**Comment by knutwannheden** [comment]
I can't find the source code for this particular plugin anywhere else, so I don't even know where the proper place would be to report this.

**Comment by lukaseder** [comment]
Well, it was last released in 2011: https://search.maven.org/search?q=jaxb2-fluent-api
So, I'm not convinced we'll get some results here without rolling our own :)

**Comment by knutwannheden** [comment]
All `with`-methods now have the same Javadoc as the corresponding `set`-method.

**Comment by lukaseder** [comment]
Wonderful! This is definitely a backport candidate. However, I have never really liked the setter Javadoc, I mean, yes. It sets the property. Wow :) The getter Javadoc is the one we're interested in, as that is our user-provided documentation.

Is it possible to use the getter Javadoc on all 3 methods: Getter, Setter, With-Setter?

**Comment by knutwannheden** [comment]
Yes, using the same Javadoc for all 3 should not be a problem. Getting the `@return` and `@param` tags right makes it more difficult (the `com.sun.codemodel` API makes some things very difficult). I will create a new issue for this.
