### ISSUE TITLE
Consider using DatabaseMetaData.supportsGetGeneratedKeys()

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#8996]
Consider calling `DatabaseMetaData#supportsGetGeneratedKeys()` in order to avoid potential `SQLFeatureNotSupportedException`s before calling `Statement#getGeneratedKeys()`.

See #8993 for details.

**Comment by knutwannheden** [comment]
This would then affect code like `AbstractDMLQuery.prepare0(ExecuteContext)` where we call `Connection.prepareStatement(String, int)` with `Statement.RETURN_GENERATED_KEYS`.

**Comment by lukaseder** [comment]
Calling `DatabaseMetaData` methods is always a risk as they are often poorly supported by drivers. While such a call might work around an issue in one faulty driver, it might create an issue in another one...

**Comment by lukaseder** [comment]
Looking at the original issue that caused this one (#8993), I'd like to reject this enhancement request. This will only complicate things without knowing for sure whether the original issue is solved. I'm sure there's a better way.
