### ISSUE TITLE
MySQL enum type generated names inconsistent

### ISSUE THREAD

**Issue by stuppy** [jOOQ/jOOQ#9004]
### Expected behavior and actual behavior:

Background: We use PascalCase table names and snake_case column names w/ AS_IS matcher strategies to keep that casing and custom java identifiers to produce UPPER_CASE tables, fields, etc.

Problem 1: Currently no way to generate an enum class name as `DatabaseNameColumn {}` with matchers . Options are databasenameColumn or DatabasenameColumn.  I haven't tested with a two-word column name, but imagine it would either be Columnname or ColumnName.

Problem 2: The generator creates different names for enums (a) filename, (b) class name, and (c) reference name.  With PASCAL_CASE, we get `class DatabasenameColumn` in `databasenameColumn.java`, which Eclipse complains about.

Note: MatcherStrategy#getJavaIdentifier doesn't consider the enums in the definition for matching maybe?

### Versions:

- jOOQ: 3.11.5
- Java: 8
- Database (include vendor): MySQL 5.7
- OS:
- JDBC Driver (include name if inofficial driver): Google Cloud SQL

**Comment by knutwannheden** [comment]
Thank you very much for the detailed ticket. We will look into the various problems you reported and create separate tickets to track them individually.

**Comment by knutwannheden** [comment]
I would also like to mention that there is the `KeepNamesGeneratorStrategy`, which keeps the Java identifiers exactly as in the database. This strategy does however not support matchers. You configure it like so:

```xml
<generator>
  <strategy>
    <name>org.jooq.codegen.KeepNamesGeneratorStrategy</name>
  </strategy>
</generator>
```

**Comment by knutwannheden** [comment]
> Problem 2: The generator creates different names for enums (a) filename, (b) class name, and (c) reference name. With PASCAL_CASE, we get class DatabasenameColumn in databasenameColumn.java, which Eclipse complains about.

This seems very odd. The generator calls the same method `MatcherStrategy#getJavaClassName()` also when determining the class name. Could you please try to delete the files with the wrong case and regenerate again and see if the wrong file is generated again?

**Comment by knutwannheden** [comment]
> Problem 1: Currently no way to generate an enum class name as DatabaseNameColumn {} with matchers . Options are databasenameColumn or DatabasenameColumn. I haven't tested with a two-word column name, but imagine it would either be Columnname or ColumnName.

Can you elaborate a bit more on this? Assuming you have a table with an enum like this:

```sql
CREATE TABLE shirts (
    name VARCHAR(40),
    size ENUM('x-small', 'small', 'medium', 'large', 'x-large')
);
```

Then jOOQ will produce an enum definition with the name `shirts_size` and with applying `PASCAL` you should then get `ShirtsSize`. If you also want to have the database name as part of the Java class name, you should be able to configure the matcher like this:

```xml
<strategy>
  <matchers>
    <enums>
      <enum>
        <enumClass><expression>mydatabase_$0</expression><transform>PASCAL</transform></enumClass>
    <enums>
  </matchers>
</strategy>
```

If the name of your enum were `shirt_size` you would get `ShirtsShirtSize` and if it were `shirtSize` you would get `ShirtsShirtsize`.

Can you give a more concrete example of your input DDL and the exact Java class names you would like to map to?

**Comment by stuppy** [comment]
Thanks for the feedback.

I think you're on to something with the filenames... it does seem like my OS (OSX) and/or git don't seem to notice newness between helloWorld.java and HelloWorld.java when generated from jOOQ.  Reverting and re-generating uncommitted files picks up the changes at the right case.

Using table:
```
CREATE TABLE ShirtOrder (
    name VARCHAR(40),
    standard_size ENUM('x-small', 'small', 'medium', 'large', 'x-large')
);
```

Without any matchers:

`public enum ShirtorderStandardSize` in ShirtorderStandardSize.java
`public ShirtorderStandardSize getStandardSize();` in refs

So that looks right, though uses Shirtorder instead of ShirtOrder on the table name.

With `AS_IS`, I expectedly get: `ShirtOrder_standard_size`

My trouble seems to lie in my mixed use of PascalCase table names and snake_case column names when joined together on enum names. Is there any way to reference the table name MatcherTransformType in the enum matcher?  Otherwise I just overrode `#getJavaClassName` with a check for `if (mode == Mode.ENUM || definition instanceof EnumDefinition)` that seems to do the trick.  At the end of the day, it just seems to be a human readability thing with no impact on the eventual SQL, so I'm not too worried about it ;-)

Thanks again!

Unrelated, but unless I used <includes> ... | TableName.* </includes>, the generated code only used a string:
```
public final TableField<ShirtOrderRecord, String> STANDARD_SIZE =
    createField("standard_size", org.jooq.impl.SQLDataType.VARCHAR(7), this, "");
```

**Comment by lukaseder** [comment]
Reviewing this issue, I think it was more of a support request than a problem? I'm closing this now as all issues seem to have been addressed. Please let me know if there's still any open question.
