### ISSUE TITLE
Document logger name for SQL logging

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9006]
https://www.jooq.org/doc/3.11/manual/sql-execution/logging/ should document the name of the logger used for the SQL execution logging, so that the user knows for which specific logger to enable `DEBUG` logging.

Possibly also add a note here: https://www.jooq.org/doc/3.11/manual/sql-building/dsl-context/custom-settings/settings-execute-logging/

**Comment by knutwannheden** [comment]
In 3.12 the log4j sample configuration in the manual will look like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="INFO">
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{ABSOLUTE} %5p [%-50c{4}] - %m%n"/>
        </Console>
    </Appenders>

    <Loggers>
        <!-- SQL execution logging is logged to the LoggerListener logger at DEBUG level -->
        <Logger name="org.jooq.tools.LoggerListener" level="debug">
            <AppenderRef ref="Console"/>
        </Logger>

        <Root level="info">
            <AppenderRef ref="Console"/>
        </Root>
    </Loggers>
</Configuration>
```

**Comment by lukaseder** [comment]
I agree that this particular manual section could document the `LoggerListener`, but the change is misleading. There are a few other jOOQ debug log events that might be useful to someone who wants to get jOOQ's debug log output.

Maybe this in addition to your change?

```xml
        <!-- Other jOOQ related debug log output -->
        <Logger name="org.jooq" level="debug">
            <AppenderRef ref="Console"/>
        </Logger>
```

Reopening this issue for discussion.

**Comment by knutwannheden** [comment]
AFAICT the manual section in question is specific to the SQL execution logging and not jOOQ's logging in general. But I actually thought about adding a logger just like you propose, so maybe that would be a good idea.

**Comment by lukaseder** [comment]
> AFAICT the manual section in question is specific to the SQL execution logging and not jOOQ's logging in general.

Yes, that's the intent, but after reviewing about 3-4 support cases over the past two weeks, it seems like this distinction is not clear (or necessarily useful) to some users. While we cannot easily change the behaviour, we could at least document this.
