### ISSUE TITLE
Implement opt-out for caching in AbstractMeta

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9010]
`AbstractMeta` implements caching (see #7165 and #9009), but doesn't provide any opt-out mechanism for subclasses.

**Comment by lukaseder** [comment]
Opting out is probably only one additional, desired caching strategy. I guess this feature request is more about implementing actual caching strategies, possibly a caching strategy provider, and two simple defaults:

- Cache everything forever (status quo)
- Cache nothing (what you requested here)

**Comment by knutwannheden** [comment]
Note: I created this issue because of the description of #7165:
> This new cache will be active by default, but can be opted out of.

and a corresponding TODO in `AbstractMeta`:
> // [#7165] TODO: Allow for opting out of this cache

Also note that `AbstractMeta` only covers the caching at the `Meta` level (completed with #9009). The returned objects (e.g. `Catalog` or `Schema`) may or may not implement caching.

**Comment by lukaseder** [comment]
I haven't run into this limitation in the past minor releases. Might be worth addressing when investing more into the DDL interpretation and other `MetaProvider` features again, but the focus has simply been elsewhere, recently.

Might reopen, when/if appropriate.
