### ISSUE TITLE
Add support for unqualifiedSchema in JPADatabase to prevent generating the H2 PUBLIC schema

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9015]
As brought up in issue #9013 the `JPADatabase` generated Java code references the `PUBLIC` schema (from the internally used H2 database). If the user doesn't target H2, he might as a result be required to `Settings#withRenderMapping()` or `Settings#withRenderSchema()`.

Possibly the code generation could be configured to not generate the `PUBLIC` schema references.

**Comment by knutwannheden** [comment]
The generator already has a flag for this: `Database#outputSchemaToDefault`.

**Comment by lukaseder** [comment]
The `DDLDatabase` has an `unqualifiedSchema` flag that allows for specifying which schema should be used for unqualified table names. Maybe, we could reproduce this behaviour also in the `JPADatabase`?

I will review the discussion in https://github.com/jOOQ/jOOQ/issues/9013 later to see if there may be other missing features on our side. Sure, there are workarounds, but the default, out of the box experience can always be improved.
