### ISSUE TITLE
Errors encountered with translation

### ISSUE THREAD

**Issue by venkatkr** [jOOQ/jOOQ#9016]
I tried using the translate option in jOOQ to convert sql statements from oracle dialect to postgresql dialect. I am encountering some basic errors. As an example, rownum is retained in the translated query for postgres. The Oracle query is 

```sql
select count(*) from (select * from (select * from MyOraTable where ROWNUM<3) where ROWNUM<2) where ROWNUM=1; 
```

The translator does not recognize date formats of Oracle. The below query fails to parse

```sql
select to_char(sysdate + 1,'dd-mm-yyyy') from dual
union all
select to_char(sysdate,'dd-mm-yyyy') from dual
union
select to_char(sysdate - 1,'dd-mm-yyyy') from dual
minus
select to_char(sysdate - 1,'dd-mm-yyyy') from dual
intersect
select to_char(sysdate - 3,'dd-mm-yyyy') from dual
; 
```

**Comment by knutwannheden** [comment]
Thank you for your report.

For the `ROWNUM` problem I have filed a new feature request here: #9017.

The `TO_CHAR` function with two parameters is also not yet supported by the parser. See here: #8381.

I will close this issue now and you can subscribe to the other two issues, if you like. Thanks again for the report!
