### ISSUE TITLE
Add Settings.transformRownum

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9017]
A new SQL transformation flag `Settings.transformRownum` should be added to allow for transforming some Oracle `ROWNUM` filters to corresponding `LIMIT` expressions, for example:

```sql
-- Input
SELECT * FROM t WHERE col = 1 AND ROWNUM <= 10;

-- Output
SELECT * FROM t WHERE col = 1 LIMIT 10;
```

**The following cases will be supported (see caveats about `GROUP BY`):**

- [x] Filters on `ROWNUM` directly
- [x] Filters using `< N` and `<= M` will be translated directly to `LIMIT N + 1` and `LIMIT M` respectively (we might need to support expressions in `LIMIT` and `OFFSET`, first: https://github.com/jOOQ/jOOQ/issues/5695)
- [x] Filters using `= 1` translate to `LIMIT 1`. Any other filter using `=` translates to `FALSE`
- [x] Filters using `>= 1` translate to `TRUE`. Any other filter using `>=` translates to `FALSE`
- [x] Filters using `!= 0`, `> 0` translate to `TRUE`. Any other filter using `!=` or `>` translates to `FALSE`
- [x] `ROWNUM =, >=, <= ROWNUM` translates to `TRUE`
- [x] `ROWNUM !=, >, < ROWNUM` translates to `FALSE`
- [x] Filters may appear in `WHERE` or `AND`, not in `OR` or any other nested predicates
- [x] The flag is not supported for Oracle versions 10g, 11g, which emulate `LIMIT` using `ROWNUM`

**The following cases will be tried, but may be much more difficult to support:**

- [x] Projections of `ROWNUM` in `SELECT`, translated to `ROW_NUMBER() OVER (<ORDER BY clause>)`. The `<ORDER BY clause>` would have to be taken from the derived table that is paginated, which might be very difficult and ambiguous
- [x] Filters of such projections from derived tables (classic way to emulate `OFFSET` in Oracle)
- [ ] `ROWNUM` filtering in DML
- [x] There might already be a `LIMIT` clause in addition to the `ROWNUM` filter. In that case, the two filters must be combined
  - [x] The same is true for redundant `ROWNUM` filters. They must be merged, producing the `LEAST` filtered value.
- [ ] In the presence of `GROUP BY`, we cannot just use `LIMIT`. The `FROM` and `WHERE` clauses must be nested in a derived table: https://github.com/jOOQ/jOOQ/issues/9017#issuecomment-698174506

**Additional tasks:**

- [x] Just like when encountering `(+)` without the flag having been set to `true`, and the target dialect doesn't support `ROWNUM`, then we'll retro-actively enable the setting for the current query using a `ForceSettingsSignal`
- [x] `ParserCLI` support
- [x] https://www.jooq.org/translate support

----
See also: #9016

**Comment by lukaseder** [comment]
Heh, well, that will be a non-trivial challenge :-) Would definitely add value to people wanting to migrate off Oracle, but I'm not sure we can implement it with reasonable effort. But if we have the SQL transformation infrastructure to do this right (we currently don't), quite a few other issues could resolve themselves.

**Comment by lukaseder** [comment]
With some additional transformation capabilities in place for jOOQ 3.14, I'm now positive that we can transform *some* `ROWNUM` predicates to `LIMIT`, mainly those that:

- Filter on `ROWNUM` directly, not on some aliased version of it, calculated in a derived table
- Use `=`, `<`, or `<=` filtering (we can ignore `!=`, `>`, `>=`, which don't make sense in Oracle either)
- Are filtered from `WHERE` or `AND`, not `OR` or something else

Projections of `ROWNUM` are not supported yet. I'll update the issue description to reflect what's in and out of scope

**Comment by lukaseder** [comment]
A first working draft has been implemented. Now the yak shaving to handle all the edge cases starts.

**Comment by lukaseder** [comment]
The approach chosen for translating direct filters on `ROWNUM` to `LIMIT` is wrong. It works only in very simple cases, i.e. when there is no other operation between `WHERE` and `LIMIT` (ordered logically). E.g. in the presence of `GROUP BY`, the current emulation is incorrect:

```sql
-- Input
SELECT author_id, count(*)
FROM t_book
WHERE rownum < 3 AND id < 4
GROUP BY author_id;

-- Output
SELECT author_id, count(*)
FROM t_book
WHERE id < 4
GROUP BY author_id
FETCH FIRST 2 ROWS ONLY;
```

The above produces:

```
AUTHOR_ID|COUNT(*)|
---------|--------|
        1|       2|

AUTHOR_ID|COUNT(*)|
---------|--------|
        1|       2|
        2|       1|
```

Clearly not the same thing. The correct emulation would be to produce a derived table for the `FROM .. WHERE` clauses (assuming we won't support `ROWNUM` outside of `WHERE` yet, e.g. in `HAVING`):

```sql
-- Input
SELECT author_id, count(*)
FROM t_book
WHERE rownum < 3 AND id < 4
GROUP BY author_id;

-- Output 1, using LIMIT
SELECT author_id, count(*)
FROM (
  SELECT *
  FROM t_book
  WHERE id < 4
  FETCH FIRST 2 ROWS ONLY
) t_book
GROUP BY author_id;

-- Output 2, using ROW_NUMBER(), which we should support anyway, in case ROWNUM is projected
SELECT author_id, count(*)
FROM (
  SELECT t_book.*, ROW_NUMBER() OVER () rn
  FROM t_book
  WHERE id < 4
) t_book
WHERE rn < 3
GROUP BY author_id;
```

This obviously greatly complicates things:

- In some RDBMS, `ORDER BY` is now mandatory for `LIMIT` to be possible (this is already implemented)
- In the presence of `JOIN` there may be duplicate column names which aren't allowed in derived tables. We'd have to rename all the column names, and translate all references from the original query

Benefits of going this way would be synergies with the planned `QUALIFY` emulation: https://github.com/jOOQ/jOOQ/issues/5810

I think we'll keep the status quo for now, which is already better than nothing, and document the known issues, e.g. `ROWNUM` not being emulated correctly in the presence of `GROUP BY` and `HAVING`

**Comment by lukaseder** [comment]
With these caveats, and also the fact that `ROWNUM` should be projected as `ROW_NUMBER() OVER ()`, I'll rename the setting to `Settings.transformRownum`, simply

**Comment by lukaseder** [comment]
Another operation that is located between `WHERE` and `LIMIT` is `DISTINCT` or `UNION`. These are not the same:

```sql
SELECT DISTINCT author_id
FROM T_BOOK 
WHERE rownum <= 2;

SELECT DISTINCT author_id
FROM t_book
FETCH FIRST 2 ROWS ONLY;
```

**Comment by lukaseder** [comment]
Projection of `ROWNUM` has been implemented. Further work will be done via a new issue: #10716
