### ISSUE TITLE
SQLSERVER optimistic locking: Cannot update identity column

### ISSUE THREAD

**Issue by Vitekant** [jOOQ/jOOQ#9021]
### Expected behavior and actual behavior:
Trying to use optimistic locking just like described in the manual example:

```java
DSLContext optimistic = DSL.using(connection, SQLDialect.SQLSERVER2016,
  new Settings().withExecuteWithOptimisticLocking(true));
 
BookRecord book1 = optimistic.fetchOne(BOOK, BOOK.ID.eq(5);
book1.setTitle("Animal Farm");
book1.store();
```

Store is crashing with SqlServerException Cannot update identity column 'id'.
My understanding is that it's caused by

```
CursorImpl.java#1613
rs.updateObject(1, rs.getObject(1));
```

It's trying to update identity column value which is not allowed by SqlServer.

### Versions:

- jOOQ: 3.11.2
- Java: 11
- Database (include vendor): SQLSERVER 2016
- OS:
- JDBC Driver (include name if inofficial driver):mssql 7.2.2

**Comment by lukaseder** [comment]
Thank you very much for your report.

That call is made becausejOOQ applies pessimistic locking in some cases. A better way to implement pessimistic locking will be implemented in the future, which wouldn't cause the issue you've encountered: https://github.com/jOOQ/jOOQ/issues/8844

However, in this case, no pessimistic locking should be applied at all. We'll investigate why this happens.

**Comment by lukaseder** [comment]
This is probably caused by the default value for `Settings.executeWithOptimisticLockingExcludeUnversioned`, which is `false`. Setting this to `false` means that "unversioned" records will also be locked via an additional pessimistic lock, which is implemented inefficiently in SQL Server right now.

Could you try changing that flag to `true`?

**Comment by lukaseder** [comment]
I still think this is due to `Settings.executeWithOptimisticLockingExcludeUnversioned`. In case any additional information pops up, I'll be very happy to look at this again.
