### ISSUE TITLE
Mention fetch sizes on the topic of lazy fetching

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9022]
As mentioned in a comment (https://www.jooq.org/doc/3.2/manual/sql-execution/fetching/lazy-fetching/#comment-4571759911) it would be helpful if the manual pointed out that true lazy fetching will require setting the fetch size for some databases.

**Comment by lukaseder** [comment]
The Javadoc on `ResultQuery.fetchLazy()` already refers to the option of calling `fetchLazy(int)`, instead. Unfortunately, that reference is outdated, as `fetchLazy(int)` is deprecated. So, this task involves:

- [ ] Updating the manual (makes perfect sense)
- [ ] Fixing the Javadoc

I think we shouldn't document too many vendor specific behaviours, but instead, direct users to their relevant JDBC driver manuals.

**Comment by lukaseder** [comment]
I fixed the Javadoc

**Comment by lukaseder** [comment]
Added a section to the manual as well
