### ISSUE TITLE
includeExcludeColumns does not work to exclude columns qualified with a table name

### ISSUE THREAD

**Issue by myronmarston** [jOOQ/jOOQ#9023]
### Expected behavior and actual behavior:

I'm attempting to use the `includeExcludeColumns` to exclude specific columns from the jOOQ generator, using configuration like:

```
<database>
    <includes>.*</includes>
    <excludes>test2.some_other_value</excludes>
    <includeExcludeColumns>true</includeExcludeColumns>
</database>
```

When I use `<excludes>some_other_value</excludes>` it properly excludes the `some_other_value` column from all tables.  But if I want to exclude it from just one table using an expression like `test2.some_other_value` it doesn't work.  I'd expect it to exclude `test2.some_other_value`, but instead it doesn't exclude anything.

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

https://github.com/myronmarston/jOOQ-mcve/commit/87770e849109eac229042973deda306a65325e69

### Versions:

- jOOQ: 3.11.11
- Java: 10
- Database (include vendor): MySQL but the MVCE was created using H2 so it doesn't appear to be DB specific
- OS: OS X
- JDBC Driver (include name if inofficial driver): whatever the stock MVCE uses

**Comment by lukaseder** [comment]
Thank you very much for your message.

Do note that these expressions currently either match:

- Unqualified identifiers (e.g. `column_name`)
- Fully qualified identifiers (e.g. `schema_name.table_name.column_name`)

jOOQ 3.12 will also match partially qualified identifiers, like yours: https://github.com/jOOQ/jOOQ/issues/7947

The workaround here is to match the exact schema name, or any schema, such as:

```xml
    <excludes>(?:\w+\.)?test2\.some_other_value</excludes>
```

**Comment by myronmarston** [comment]
Thanks!  The `(?:\w+\.)?` trick works quite well.
