### ISSUE TITLE
docker : Caused by: java.sql.SQLRecoverableException: Closed Connection

### ISSUE THREAD

**Issue by jaganmohan310** [jOOQ/jOOQ#9027]
### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report, @jaganmohan310. Do you have perhaps a bit more information to share with us? :)

**Comment by lukaseder** [comment]
Without further feedback, I hope you're fine with me closing this issue for now. I will be very happy to help with additional information about the issue.
