### ISSUE TITLE
JDBCUtils.driver(String) returns deprecated "com.mysql.jdbc.Driver"

### ISSUE THREAD

**Issue by jonahzheng** [jOOQ/jOOQ#9034]
### Expected behavior and actual behavior:
[INFO] --- jooq-codegen-maven:3.11.11:generate (jooq) @ sw-jooq ---
[INFO] Database                 : Inferring driver com.mysql.jdbc.Driver from URL jdbc:mysql://114.11.......
Loading class **`com.mysql.jdbc.Driver'. This is deprecated.** The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

### Versions:

- jOOQ:3.11.11
- Java:8.0
- Database (include vendor):mysql
- OS:window
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report. We should update the driver class name, indeed. You can work around this issue by specifying it explicitly in the `<jdbc>` section of your code generation configuration:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-jdbc

**Comment by lukaseder** [comment]
In fact, that linked manual page also refers to the deprecated driver version. We'll fix that as well.

**Comment by jonahzheng** [comment]
@lukaseder thank a lot, good job!

**Comment by lukaseder** [comment]
I haven't done anything yet :-)
