### ISSUE TITLE
Add support for the PostgreSQL SPLIT_PART function

### ISSUE THREAD

**Issue by raphaelauv** [jOOQ/jOOQ#9038]
### SQL translator incorrectly translates this query:

```sql
SELECT event_date  from ad_view WHERE SPLIT_PART(user_agent,';',2)='iOS';
```

redshift -> postgreSQL

error : 
```Unknown function: [1:50] SELECT event_date  from ad_view WHERE SPLIT_PART([*]user_agent,';',2)='iOS';```

**Comment by knutwannheden** [comment]
Note: `SPLIT_PART()` is supported by some PostgreSQL derived and compatible dialects like PostgreSQL, Redshift, and Vertica.

**Comment by lukaseder** [comment]
It could probably be emulated in quite a few dialects, too, using regular expressions. For example, in PostgreSQL, these two should be the same:

```sql
split_part(user_agent,';',2)
regexp_replace(user_agent, '(.*;){1}(.*?)(;.*)', '\2') -- Where {1} is the third argument (2) - 1
```

We'd obviously need to implement some vendor-specific escaping of the second argument

**Comment by knutwannheden** [comment]
Yes, on Oracle we would probably use `REGEXP_SUBSTR()`, which already has an `occurrence` parameter. See also here: https://community.oracle.com/ideas/3122.

**Comment by lukaseder** [comment]
That would be much better, of course

**Comment by lukaseder** [comment]
Will do this for jOOQ 3.15.0. Emulations can be done separately: #11037
