### ISSUE TITLE
Clarify which interfaces are immutable/mutable

### ISSUE THREAD

**Issue by ivangreene** [jOOQ/jOOQ#9039]
### Your question:
[Im]mutability of different jOOQ query-building interfaces is hinted at in documentation, but is not consistently indicated by a marker annotation or otherwise. Consider a simple example of two interfaces with similar APIs but very different results:
```java
Condition condition = trueCondition();
condition.and(falseCondition()); // condition unchanged, a different Condition is returned here
SelectConditionStep<Record> selectConditionStep = select().where(trueCondition());
selectConditionStep.and(falseCondition()); // selectConditionStep changed, the same instance returned here
```

It will be useful in the (admittedly rare) situations where the use of `XYZ*Step` or other more 'internal' interfaces is warranted. Additionally, an annotation like findbugs' CheckReturnValue might be used on methods returning a new instance, where the method invocation has no effect if its return value is unused.
### Versions:

- jOOQ: 3.11.9
- Java: N/A
- Database (include vendor): N/A
- OS: N/A
- JDBC Driver (include name if inofficial driver): N/A

**Comment by lukaseder** [comment]
The simple rule of thumb is that any interface ending in `Step` is currently mutable. We could document this, but then we would set it in stone for jOOQ 3.x, which makes moving off mutability even more difficult.

I wonder if we should invest our time in the busywork of annotating the API, or push forward the actual goal of making everything immutable...

**Comment by lukaseder** [comment]
Our API is annotated with `@CheckReturnValue` since jOOQ 3.15:

- https://github.com/jOOQ/jOOQ/issues/11718

The annotation is present also on methods that mutate the underlying implementation, simplifying a possible migration towards a completely immutable DSL in the future, should we ever go forward with such a project.

As such, I'm closing this as a duplicate.
