### ISSUE TITLE
Illegal reflective access by org.jooq.tools.reflect.Reflect 

### ISSUE THREAD

**Issue by jonahzheng** [jOOQ/jOOQ#9040]
### Versions:

2019-08-15 09:31:11.211  INFO 44903 --- [p-nio-81-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 6 ms
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jooq.tools.reflect.Reflect (file:/Users/lvzx/.m2/repository/org/jooq/jooq/3.11.11/jooq-3.11.11.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class)
WARNING: Please consider reporting this to the maintainers of org.jooq.tools.reflect.Reflect
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-08-15 09:31:11.384  INFO 44903 --- [p-nio-81-exec-1] org.jooq.Constants     

- jOOQ:3.11.11
- Java:8
- Database (include vendor):mysql
- OS:mac
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your report. This will be addressed in jOOQ 3.12: #7950.
