### ISSUE TITLE
Support DSL#all(Object...) and DSL#any(Object...) for all dialects

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9046]
Based on the implementation of `QuantifiedSelectImpl` (specifically the `QuantifiedSelectImpl(Quantifier, Field<? extends Object[]>)` case), it looks like `DSL#all(Object...)` and `DSL#any(Object...)` could be supported for all dialects.

This would allow the developer to write `field.like(all("foo%", "%bar"))` without using any unsupported methods. Currently some dialects like SQLite would have to use `field.like(all(val("foo%"), val("%bar")))` if restricting to the supported dialects, even though the other expression also yields the correct result.

The `QuantifiedSelect` can then however not be used together with all comparison predicates (only `LIKE`, `NOT LIKE`, `ILIKE` and `NOT ILIKE`), but this could be stated in the Javadoc.

**Comment by lukaseder** [comment]
I feel this is a duplicate, as we're already supporting the method on (almost) all dialects. I don't remember if there was a case that still isn't supported yet...
