### ISSUE TITLE
Offer a SNAPSHOT repository

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9053]
Enterprise customers can request snapshot releases per the license document. We should automate building snapshot releases of the next major (if applicable) / minor releases, as well as of all the currently supported patch releases.

We would be offering this to Professional and Enterprise customers. Using the `versions-maven-plugin` might be a useful prerequisite: https://github.com/jOOQ/jOOQ/issues/9487

**Comment by lukaseder** [comment]
Possible synergies with #9329

**Comment by lukaseder** [comment]
The snapshots are now available from https://www.jooq.org/download/versions to paying customers. I'm not 100% convinced of the layout. Maybe some alternative layout seems reasonable (without resorting to a ton of JavaScript)...?

I was wondering if we should also upload the 3.12.4-SNAPSHOT builds, so customers can profit from bug fixes even before we release the next patch release. In the future, we might want to have such snapshot builds for a set of previous minor releases.

What do you think, @knutwannheden? Should probably work the same way?

**Comment by knutwannheden** [comment]
> The snapshots are now available from https://www.jooq.org/download/versions to paying customers. I'm not 100% convinced of the layout. Maybe some alternative layout seems reasonable (without resorting to a ton of JavaScript)...?

What will it look like once there are 20+ snapshot builds? I assume we don't want to show them all. It seems to me like we would typically only want to show the latest one and require the user to click on some "button" to see the archive of snapshot builds.

> I was wondering if we should also upload the 3.12.4-SNAPSHOT builds, so customers can profit from bug fixes even before we release the next patch release. In the future, we might want to have such snapshot builds for a set of previous minor releases.

Yes, I think that would be great. This would then probably also affect our workflow, as we would be cherry-picking the fixes "immediately" rather than postponing this until the day we prepare the patch release.

I would also have to make some adjustments to our build scripts to support patch snapshot builds.

**Comment by lukaseder** [comment]
> What will it look like once there are 20+ snapshot builds? I assume we don't want to show them all.

We're currently showing 5

> It seems to me like we would typically only want to show the latest one and require the user to click on some "button" to see the archive of snapshot builds.

Yes, that doesn't only apply to snapshot builds, though, also to minor releases. The entire set of "archive" downloads could be expandable/collapsable. But I couldn't bend my mind around a layout, today.

We'll think of something.

> Yes, I think that would be great. This would then probably also affect our workflow, as we would be cherry-picking the fixes "immediately" rather than postponing this until the day we prepare the patch release.

I knew you were going to say that :-)

**Comment by knutwannheden** [comment]
> I knew you were going to say that :-)

Otherwise the snapshot builds wouldn't offer much value either :wink:

**Comment by knutwannheden** [comment]
I propose to close this issue and open new issues for further work.

**Comment by lukaseder** [comment]
OK, why not: https://github.com/jOOQ/jOOQ/issues/9657
