### ISSUE TITLE
AlterTableImpl#dropColumn() should not use #dropColumns()

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9062]
`AlterTableImpl#dropColumn()` should internally not call `#dropColumns()`, since the `@Support` annotations are not identical. E.g. `#dropColumn()` supports HSQLDB, which the latter does not. This could lead to false positives when performing a runtime code analysis.

**Comment by lukaseder** [comment]
Good point. Perhaps, we should investigate all such usages? There are probably more, and this one isn't the first. It's easy to work around systematically, by introducing a `dropColumns0()` private method...

**Comment by knutwannheden** [comment]
I have done similar refactorings in the past already. I looked into all `drop...()` methods and couldn't find any further problems. This particular example was picked up by one of our HSQLDB tests.
