### ISSUE TITLE
How to use mediumtext,longtext in mysql with SQLDataType?

### ISSUE THREAD

**Issue by novicezk** [jOOQ/jOOQ#9076]
### Your question:
How to use mediumtext,longtext in mysql with SQLDataType? I see [JOOQ MySQL TEXT DataType](https://stackoverflow.com/questions/54931411/jooq-mysql-text-datatype?answertab=active#tab-top), but i try it:
```java
	@Test
	public void createTableWithLongText() {
		String sql = DSL.using(SQLDialect.MYSQL_5_7).createTable("test")
				.column("entityId", SQLDataType.VARCHAR(32).nullable(false))
				.column("value", SQLDataType.CLOB(16777215))
				.constraint(constraint("test_fk").primaryKey("entityId")).getSQL();
		System.out.println(sql);
	}
```
but result as: create table `test`(`entityId` varchar(32) not null, `value` text null, constraint `test_fk` primary key (`entityId`))
### Versions:

- jOOQ:3.11.12
- Java:1.8
- Database (include vendor):mysql5.7
- OS:ubuntu16
- JDBC Driver (include name if inofficial driver):com.mysql.jdbc.Driver

**Comment by lukaseder** [comment]
Thank you very much for your message. Unfortunately, we currently do not have a solution for this using public, non-deprecated API. The current workarounds are:

- Use the deprecated `MySQLDataType` types. We're not going to remove the class before we offer an alternative to these types
- Create your own (internal) `DefaultDataType` to create such a data type.

I hope this helps

**Comment by novicezk** [comment]
Thank you.
