### ISSUE TITLE
Implement some unknown syntax heuristics in parser to attempt to recognise unknown DDL clauses

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9084]
Starting with jOOQ 3.12, we have a set of additional tools to process unknown SQL syntax, mainly in the `DDLDatabase`, e.g. a special comment syntax that allows us to skip certain clauses: https://github.com/jOOQ/jOOQ/issues/8325

This is tedious for the user who has to manually pre process all their SQL scripts. Perhaps, a variety of SQL clauses can be recognised automatically with some heuristics. For example, we already parse and ignore most `SET a = b` statements. In DDL, there are a lot of common storage clauses at the end of a statement, e.g. 

```sql
CREATE TABLE x (
  i INT
)
TABLESPACE xyz;
```

The `TABLESPACE` clause needs to be parsed and ignored, as it is not relevant for us. Many clauses follow a simple pattern:

```
ignore ::= ignoreToken*;

ignoreToken ::=
  keyword
| identifier
| number
| '(' ignore ')'
| ...
```

In the discussion around parser input strictness (https://github.com/jOOQ/jOOQ/issues/8826), there are a number of possible `Settings` that could be specified to govern the lenience of the parser with respect to such clauses, as well as the error handling mechanism (ignore, log, throw), in case such syntax has been recognised.

For performance reasons, we'll have to be careful not to apply this lenience *always* and *everywhere*. We should not turn it on by default, only in the `DDLDatabase`

----

List of syntaxes that we should be able to ignore:

- [ ] `CREATE TABLE` trailing tokens: Any tokens at the end of a given statement (`CREATE TABLE` as in the example)
- [ ] Index storage specifications both for `CREATE INDEX` statements and for inline `INDEX` definitions in `CREATE TABLE`, often using `USING` syntax, e.g. https://github.com/jOOQ/jOOQ/issues/9132

----

As in #9138 the error message should also hint at changing the setting for this feature.

**Comment by knutwannheden** [comment]
List of syntaxes that we should be able to ignore:

1. Trailing tokens: Any tokens at the end of a given statement (`CREATE TABLE` as in the example)

**Comment by lukaseder** [comment]
@knutwannheden I've moved your comment in the issue description, which we can continue editing to add to the list. The comments will be much more difficult to manage...

**Comment by knutwannheden** [comment]
> @knutwannheden I've moved your comment in the issue description, which we can continue editing to add to the list. The comments will be much more difficult to manage...

Makes sense. I mostly added it as a comment, so that you would be notified about it.

**Comment by lukaseder** [comment]
Correct me if I'm wrong: This has been implemented on a branch and not merged yet, so nothing needs reverting.

I'd prefer not to implement this. I just don't have a good feeling with this experiment.

**Comment by knutwannheden** [comment]
> Correct me if I'm wrong: This has been implemented on a branch and not merged yet, so nothing needs reverting.

Correct. I will make sure the branch gets deleted.
