### ISSUE TITLE
Numeric columns returned by MetaImpl have a LENGTH

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9089]
When using `DefaultMetaProvider` to read a database's meta data through the JDBC `DatabaseMetaData` API, the returned numeric `DataType` objects will have both a precision and a length: https://github.com/jOOQ/jOOQ/blob/1ec32db4bc049b19d6475053574e09982e423a2d/jOOQ/src/main/java/org/jooq/impl/MetaImpl.java#L794-L798

It should be investigated if this can be improved. Possibly we could simply skip setting the length for any numeric types or even ignore the length for numeric types in `DefaultDataType`.

**Comment by lukaseder** [comment]
Yes, interesting.

We do have `DataType.hasLength()`, `DataType.hasPrecision()`, and `DataType.hasScale()`. These methods were probably not available yet, when the quoted code was written.

**Comment by lukaseder** [comment]
Notice the `C: Meta Data Navigation` label was originally meant for `jOOQ-meta` related issues, but I've stopped using it, as it doesn't really make much sense to distinguish between `jOOQ-meta` and `jOOQ-codegen` related issues...

**Comment by lukaseder** [comment]
This has been fixed in jOOQ 3.14 via https://github.com/jOOQ/jOOQ/issues/9958
