### ISSUE TITLE
CREATE TABLE fails with ParseWithMetaLookups.THROW_ON_FAILURE

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9090]
When parsing a `CREATE TABLE X ...` statement while using the `ParseWithMetaLookups.THROW_ON_FAILURE` setting the parser will fail with an exception like the following:

```java
org.jooq.impl.ParserException: Unknown table identifier: [1:16] create table x [*]as select a = 1
	at org.jooq.impl.ParserContext.exception(ParserImpl.java:10649)
	at org.jooq.impl.ParserContext.lookupTable(ParserImpl.java:10801)
	at org.jooq.impl.ParserImpl.parseTableName(ParserImpl.java:8751)
	at org.jooq.impl.ParserImpl.parseCreateTable(ParserImpl.java:3101)
	at org.jooq.impl.ParserImpl.parseCreate(ParserImpl.java:2137)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:842)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:542)
	at org.jooq.impl.ParserImpl.parse(ParserImpl.java:529)
```

This seems wrong as the table `X` is being created in this case and shouldn't have to exist already.

**Comment by lukaseder** [comment]
Huh, yes, interesting catch-22...

**Comment by lukaseder** [comment]
This raises an interesting question. The idea behind `ParseWithMetaLookups` is to be able to make sure that `SELECT` and other DML statements have

- column type information
- table type information
- constraint information

Etc. It was not designed (yet) with DDL in mind. We could of course just turn off looking up the table in `create table` statements. But then:

- Should we throw an exception when the table already exists?
- Should we modify the meta information with each DDL statement to make sure subsequent queries can use `x` (i.e. DDL simulation: #7034)

I'm inclined to ignore all such lookups in all DDL statements for now, and use them only in DML. We'll fix this with #7034, where we can introduce a new setting that indicates whether the parser should auto-simulate all DDL. The new feature request is: #9091

**Comment by lukaseder** [comment]
This fix needs no backport as the `ParseWithMetaLookups` feature has been added only in jOOQ 3.12

**Comment by knutwannheden** [comment]
Is maybe a CTAS a corner case, as the meta lookup for the table referenced from the `SELECT` should resolve?

**Comment by lukaseder** [comment]
Nope, not a corner case. My tests don't use CTAS, and the error you've reported refers to `X`, not to any tables referenced from the `SELECT`. Notice the `[*]` is placed after the `X` because the table name has been parsed correctly, syntactically.

**Comment by knutwannheden** [comment]
What I meant was that in the case of a CTAS like `CREATE TABLE T2 AS SELECT * FROM T1` the parser should throw an exception if `T1` doesn't exist.

**Comment by lukaseder** [comment]
I see, you're right
