### ISSUE TITLE
Optional limit / offset support?

### ISSUE THREAD

**Issue by fedotxxl** [jOOQ/jOOQ#9093]
Hello. Is there any simple way to make optional limit / offset? Here is code to illustrate the problem:

```java
private List<SpotPricePartDataHolderI.SpotData> findAllBy(Condition condition, Integer limit) {
        SelectConditionStep<Record8<Spot.Id, Integer, Integer, Boolean, MediaPlan.Item.Id, Integer, Double, Integer>> select = dsl
                .select(
                        SPOT.ID,
                        SPOT.AUCTION_STEP_CURRENT,
                        SPOT.AUCTION_STEP_PRICE,
                        SPOT.IS_PRIME,
                        SPOT.MP_ITEM_ID,
                        SPOT.POSITION,
                        SPOT.RATING_PULLED,
                        SPOT.SPOT_DATE
                )
                .from(SPOT)
                .where(condition);

        if (limit != null && limit > 0) {
            return select.limit(limit).fetch(mapper);
        } else {
            return select.fetch(mapper);
        }
    }
```

To make limit optional I have to create an ugly variable. Is it possible to make it inline? Something like:

```java
return dsl
                .select(
                        SPOT.ID,
                        SPOT.AUCTION_STEP_CURRENT,
                        SPOT.AUCTION_STEP_PRICE,
                        SPOT.IS_PRIME,
                        SPOT.MP_ITEM_ID,
                        SPOT.POSITION,
                        SPOT.RATING_PULLED,
                        SPOT.SPOT_DATE
                )
                .from(SPOT)
                .where(condition)
                .limit(Optional.ofNullable(is.t(limit) && limit > 0 ? limit : null))
                .fetch(mapper);
```

The same question is for offset.
If not I think it would be pretty useful feature

**Comment by JanecekPetr** [comment]
You could also consider using `var`:

```java
var select = dsl.select(...);
```

**Comment by lukaseder** [comment]
Thank you very much for your request. We do have a few feature requests in the pipeline where we would interpret `null` values as if there was no value passed to the API.

I personally don't like this, as the intention (however obscure) might have been to be able to pass a SQL `NULL` value to the `LIMIT` clause, and such an API design would prevent that.

"Overloading" the `limit()` method with an `limitOptional()` method is not an option here, as this would have to be done with pretty much every method of the DSL API, leading to a lot of overhead and cognitive load when learning the API for what is a relatively rare edge case.

Using type inference as indicated by @JanecekPetr already helps. If you're doing this more often, you could write utilities, such as:

```java
public class OptionalLimit {
    static DSLContext ctx = DSL.using(SQLDialect.H2);

    public static void main(String[] args) {
        System.out.println(optionalLimit(ctx.select(), null));
        System.out.println(optionalLimit(ctx.select(), 1));
    }

    public static <R extends Record> SelectForUpdateStep<R> optionalLimit(SelectLimitStep<R> step, Integer limit) {
        return limit == null ? step : step.limit(limit);
    }
}
```

Do note that in jOOQ 3.x, these `XYZStep` types are mutable, so you are modifying the input instance, not creating new instances of jOOQ queries.

**Comment by fedotxxl** [comment]
```
Thank you very much for your request. We do have a few feature requests in the pipeline where we would interpret null values as if there was no value passed to the API.
```

This is unexpected behavior, using null this way may lead to bugs in an application.

**Comment by lukaseder** [comment]
> This is unexpected behavior, using null this way may lead to bugs in an application.

Well, I invite you to review your own feature request then, which suggests precisely that :-)

**Comment by fedotxxl** [comment]
I suggest you use `Optional` or any other explicit way to notify about skipping limit / offset. Using `null` in this case makes it implicitly and may lead to potential problems

**Comment by lukaseder** [comment]
@fedotxxl I know that you're suggesting this, but your own code snippet included a nullable `Integer`:

```java
findAllBy(Condition condition, Integer limit) {
    // ...

    if (limit != null && limit > 0) {
        // ...
    }
```

Anyway, back on topic. While I recognise the trouble with this kind of interaction, I don't agree we should add more methods that accept `Optional<T>`  arguments everywhere we have `T` arguments, nor should we do this for `offset` and `limit` only.

The workarounds suggested here are viable for now, and a better solution for out of the box support might evolve in the future, but I can't see it yet.
