### ISSUE TITLE
Pro Oracle oracleTSTZ doesn't unwrap connection from pool prior to TZ constructor - Merge [#9088]

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9095]

**Comment by lukaseder** [comment]
My backport was incorrect, as it relied on jOOQ 3.12 internal API.

**Comment by knutwannheden** [comment]
This was in the meantime fixed on the 3.11 branch. Unfortunately the commit references the #9088 issue rather than this one. Closing as fixed.
