### ISSUE TITLE
Cannot build Javadoc in jOOQ-checker under Java 11

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9099]
When building jOOQ 3.12 with Java 11, the Javadoc for the `jOOQ-checker` module cannot be built:

![image](https://user-images.githubusercontent.com/734593/63930830-5d20b900-ca54-11e9-9c87-4f7b1d9129a7.png)

A workaround (to be able to release 3.12 now) is to skip Javadoc generation for this module. We'll find out later what the problem is, here.

**Comment by lukaseder** [comment]
I've had some weird compilation issues in the jOOQ Professional Edition that did not occur in the jOOQ Trial Edition with OpenJDK 11.0.1. Trying with 11.0.4, these went away. Perhaps this issue resolves itself with 11.0.4.

**Comment by lukaseder** [comment]
We cannot release jOOQ 3.12 without Javadoc in any given module, according to Maven Central requirements. Will re-build with Javadoc in the OSS Edition

**Comment by lukaseder** [comment]
Regrettably, the problem persists. Will try building with Java 8, as we're still supporting it anyway in the jOOQ OSS Edition.

**Comment by knutwannheden** [comment]
I hadn't noticed this problem :disappointed:

**Comment by lukaseder** [comment]
Why, of course not :)

Our CI doesn't always build the Javadoc, for good reasons (mainly because it's super slow). We'll get this right when we create nightly builds, and offer them to customers for download. In that case, the Javadoc must be built every night, and we'll notice this long before releasing.

**Comment by knutwannheden** [comment]
@lukaseder I am using OpenJDK 11.0.4 and can not reproduce the problem. I tried running `mvn javadoc:jar` in `jOOQ-checker`. Can you tell me what steps to reproduce this?

**Comment by lukaseder** [comment]
It happened when building the jOOQ Professional Edition with `mvn clean install -P release-pro -e`

**Comment by lukaseder** [comment]
I think it did not happen in the jOOQ Trial Edition, interestingly

**Comment by knutwannheden** [comment]
Thanks. I will try to reproduce it again.

**Comment by knutwannheden** [comment]
Looks like this problem was already discovered some time ago by someone: https://github.com/typetools/checker-framework/issues/2024 :wink:

**Comment by lukaseder** [comment]
Yes, but that shouldn't be related (in theory). At that time, I was trying to modularise jOOQ, and I gave up. I don't understand why the Javadoc processor tries to load dependencies onto the module path when generating classes for an "old" project that runs on the classpath, instead...

**Comment by knutwannheden** [comment]
Javadoc + Maven + Java 11 looks messy: https://bugs.openjdk.java.net/browse/JDK-8212233

**Comment by lukaseder** [comment]
This looks promising though:

```xml
  <plugin> 
    <groupId>org.apache.maven.plugins</groupId> 
    <artifactId>maven-javadoc-plugin</artifactId> 
    <configuration> 
      <source>8</source> 
    </configuration> 
     ... 
  </plugin> 
```

We could add this to the `jOOQ-checker` module only

**Comment by knutwannheden** [comment]
Yes, but:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (bundle-sources) on project jooq-checker: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses packages in the unnamed module, but the packages defined in https://docs.oracle.com/en/java/javase/11/docs/api/ are in named modules.
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-11-openjdk-amd64/bin/javadoc -J-Xmx1024m @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/knut/ws/workspace/jOOQ-pro/jOOQ-checker/target/apidocs' dir.
```

This seems to work:

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <additionalOptions>--limit-modules org.checkerframework.checker</additionalOptions>
                </configuration>
            </plugin>
```

But I have no idea if the produced Javadoc is any good.

**Comment by lukaseder** [comment]
We can live with it if we do this only for `jOOQ-checker`

**Comment by knutwannheden** [comment]
The workaround for `jOOQ-checker` worked, but for the trial edition there were still other problems building the Javadoc for other modules (because of a mix of unnamed and named modules defining the relevant Java classes). For now, the only way I could get this to work for all builds, was to downgrade the `maven-javadoc-plugin` to version 3.0.1.

**Comment by lukaseder** [comment]
Seems we need to apply this to one of our test modules too: `jOOQ-test-agent`

**Comment by lukaseder** [comment]
... And all the other test modules :(

**Comment by lukaseder** [comment]
It appears that `jOOQ-test` and `jOOQ-test-utils` are also needed, and then I can build the trial distribution...

**Comment by lukaseder** [comment]
Nope, not enough.

**Comment by lukaseder** [comment]
... This madness that is cross JDK releasing :). Looks like the release builds are running through now.
