### ISSUE TITLE
Emulate multi column COUNT (DISTINCT col1, col2) in H2 using arrays

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9109]
In H2, we could emulate MySQL's `COUNT(DISTINCT col1, col2)` using arrays / row value expressions, e.g. as `COUNT(DISTINCT (col1, col2))`

**Comment by knutwannheden** [comment]
Can we also emulate it using `GROUP BY`?

```sql
select count(*)
from (
  select col1, col2
  from ...
  group by col1, col2
)
```

**Comment by knutwannheden** [comment]
> In H2, we could emulate PostgreSQL's `COUNT(DISTINCT col1, col2)` using arrays / row value expressions, e.g. as `COUNT(DISTINCT (col1, col2))`

AFAICT PostgreSQL also requires the `COUNT(DISTINCT (col1, col2))` syntax. Our parser however only accepts `COUNT(DISTINCT col1, col2)`, while emitting `COUNT(DISTINCT (col1, col2))` for that input :laughing:

**Comment by lukaseder** [comment]
> Can we also emulate it using GROUP BY?

Heh, are you going to formally prove the correctness of this emulation? :-) What if there's already a `GROUP BY` (and `HAVING`) clause? What if we mix aggregation with window functions? What happens in the presence of nulls?

I remembered incorrectly. MySQL allows for this syntax, natively: https://dev.mysql.com/doc/refman/8.0/en/group-by-functions.html#function_count-distinct

**Comment by knutwannheden** [comment]
> Heh, are you going to formally prove the correctness of this emulation? :-) What if there's already a `GROUP BY` (and `HAVING`) clause? What if we mix aggregation with window functions? What happens in the presence of nulls?
> 

Better not...

> I remembered incorrectly. MySQL allows for this syntax, natively: https://dev.mysql.com/doc/refman/8.0/en/group-by-functions.html#function_count-distinct

Yes. Interestingly enough the proposed emulation is already implemented for PostgreSQL. Just not yet for H2.

**Comment by lukaseder** [comment]
> Better not...

Anyway. We could put it on the roadmap. With our new query object model, I have high hopes of being able to generate far more sophisticated emulations... It could be feasible, even if I expect it to be *very* difficult to do.
