### ISSUE TITLE
Nine parser bugs / missing features

### ISSUE THREAD

**Issue by codemonstur** [jOOQ/jOOQ#9120]
First; congratulations on the release of 3.12! I've been looking forward to seeing it :)

I've been using the `org.jooq.meta.extensions.ddl.DDLDatabase` generator to generate my code from SQL. So far I've had to manually keep two versions; one with the scripts that will be executed by Flyway on the mysql DB and another that is used by JOOQ to generate the code. This is an obvious potential source of bugs in addition to the extra work so I'd like to get rid of it.

I tried running the new 3.12 on my SQL migration scripts and ran into nine errors:
1. After clause in alter statement
```
 Error running jOOQ code generation tool: Unexpected token or missing query delimiter: [10:60] ...LE `example` ADD COLUMN `field3` varchar(32) NULL [*]AFTER `field2`;
```
My understanding is that the order of the fields can have an impact on the performance of the queries. But I don't really care that much. Removing the AFTER clause will make the parsing work.
EDIT: duplicate of #7241

2. Autoincrement in ALTER clause
```
Failed to execute goal org.jooq:jooq-codegen-maven:3.12.0:generate (default) on project jooq-test: Error running jOOQ code generation tool: Unexpected token or missing query delimiter: [7:73] ...ADD COLUMN `example_id` int(10) unsigned NOT NULL [*]AUTO_INCREMENT
```
I don't see a workaround, and this feature is needed in my DB.

EDIT: Reported as #9129.

3. Duplicate foreign key name in alter statement
```
Failed to execute goal org.jooq:jooq-codegen-maven:3.12.0:generate (default) on project jooq-test: Error running jOOQ code generation tool: Token '(' expected: [14:46] ...ink`
[ERROR] ADD CONSTRAINT `fk_example_link` FOREIGN KEY [*]`fk_example_link` (`example_id`) REFERENCES `example` (`example_id`) ON DELETE C...
```
Workaround is to remove the second occurrence of the name.

EDIT: Reported as #9130

4. Alter statement with first clause
```
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.12.0:generate (default) on project jooq-test: Error running jOOQ code generation tool: Unexpected token or missing query delimiter: [7:69] ...le` ADD COLUMN `field1` int(10) unsigned NOT NULL [*]FIRST;
```
Same as with AFTER clause.
EDIT: duplicate of #7241

5. Multiple statements in an ALTER statement
```
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.12.0:generate (default) on project jooq-test: Error running jOOQ code generation tool: Unexpected token or missing query delimiter: [9:46] ...ple`
[ERROR] ADD COLUMN `field2` int(10) unsigned NOT NULL[*],
[ERROR] ADD COLUMN `field3` int(10) unsigned NOT NULL;
```
Workaround is to manually split things into individual statements.

EDIT: Duplicate of #8846.

6. A BIT field with a default
```
org.jooq.impl.ParserException: Token ')' expected: [3:35] ...BLE `example` (
 `field` bit(1) NOT NULL DEFAULT b[*]'0'
);
```
Workaround is rewriting the SQL without the b and single quotes.

EDIT: Reported as #9131.

7. Creating an index
```
Error while exporting schema: SQL [create table "example"("example_id" bigint not null auto_increment, "index" bigint not null, primary key ("id"), index "index_idx" ("index"))]; Unknown data type: "index_idx"; SQL statement:
[ERROR] create table "example"("example_id" bigint not null auto_increment, "index" bigint not null, primary key ("id"), index "index_idx" ("index")) [50004-199]
```
I got the normal way of creating indexes to work with JOOQ. However I did run into an additional bug when the table name isn't quoted:
```
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.12.0:generate (default) on project jooq-test: Error running jOOQ code generation tool: Error while exporting schema: SQL [create index "index_idx" on example("index")]; Table "EXAMPLE" not found; SQL statement:
[ERROR] create index "index_idx" on example("index")
```

8. Disabling foreign-key-checks + foreign key to table further into the script
```
SET FOREIGN_KEY_CHECKS = 0;
...
```
The obvious workaround is to re-arrange the statements so that the needed tables and fields are available in the right order.

9. Using btree statement
```
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.12.0:generate (default) on project jooq-test: Error running jOOQ code generation tool: Unexpected token or missing query delimiter: [6:54] ...ER TABLE `example` ADD PRIMARY KEY (`example_id`) [*]USING BTREE;
```
The workaround is simple here; just remove the USING BTREE part.

EDIT: Reported as #9132.

There is a strange tenth issue that I ran into where I think MySQL actually erroneously succeeds when it should fail. It has to do with deleting a primary key when it no longer exists, but because the clause is contained in a single ALTER statement MySQL allows it. 

I created an example project here: https://github.com/codemonstur/jooq-generate-errors. Also looked through issue #8452 and couldn't find these. All SQL was generated using Schemasync.

**Comment by knutwannheden** [comment]
Thank you very much for your detailed report. I have started going through the individual problems and created or linked existing issues to them, so that we in the end can close this issue. Although we would appreciate if you could still keep your GitHub repo around for a while.

Regarding "7. Creating an index": The problem here is that H2's `CREATE TABLE` (in non-MySQL mode) doesn't allow for inline index definitions and jOOQ cannot emulate it either. We will have to think what to do about this one, but our plan for 3.13 is to change `DDLDatabase` to "simulate" all DDL rather than execute it against an H2 database.

**Comment by knutwannheden** [comment]
Regarding "8. Disabling foreign-key-checks + foreign key to table further into the script": Many databases have some kind of `SET` command and even the syntax is often quite similar (with some options like `GLOBAL` etc.). But we will also here have to discuss what the parser should do when it encounters these commands. In a first step the parser will probably be changed to ignore (log) any such statements (see #9084).

**Comment by knutwannheden** [comment]
> Regarding "8. Disabling foreign-key-checks + foreign key to table further into the script": Many databases have some kind of `SET` command and even the syntax is often quite similar (with some options like `GLOBAL` etc.). But we will also here have to discuss what the parser should do when it encounters these commands. In a first step the parser will probably be changed to ignore (log) any such statements (see #9084).

Note that the parser already ignores `SET` statements, like yours, where it doesn't yet know what to do about.

**Comment by lukaseder** [comment]
> Regarding "7. Creating an index": The problem here is that H2's CREATE TABLE (in non-MySQL mode) doesn't allow for inline index definitions and jOOQ cannot emulate it either

We'll definitely have to model this somehow, not just for foreign key constraints, but for all constraints. See also my comment here: https://github.com/jOOQ/jOOQ/issues/9130#issuecomment-527391553

@codemonstur: Do note that starting with jOOQ 3.12, we now have a special comment syntax, which you can use to delimit SQL syntax that should be executed in your production database, but ignored by the jOOQ parser, see: https://github.com/jOOQ/jOOQ/issues/8325

I wonder if we should include a hint about this feature in any parser error that arises from `DDLDatabase` to make this feature more widely known. I've created a feature request for this: https://github.com/jOOQ/jOOQ/issues/9138

**Comment by codemonstur** [comment]
I'll leave the example project up for you at least until you've had the chance to fix the issues.

@lukaseder the comment feature is definitely worth a look. But I'm also considering writing a preprocessor that will automatically do what I'm now doing manually.

**Comment by lukaseder** [comment]
@knutwannheden Do we have a dedicated issue for each of the nine original feature requests / comments, so this can be closed?

**Comment by knutwannheden** [comment]
Yes, I think so. Except for number 8 maybe, which would require emulating `SET FOREIGN_KEY_CHECKS = 0` (other dialects may have something similar). I can create an issue for this, but I don't know when we will get to implementing this.

@codemonstur I have forked your Git repo, so you can delete it again if you like.

**Comment by lukaseder** [comment]
> I can create an issue for this, but I don't know when we will get to implementing this.

Oh, I've overlooked the semantics of this statement. Yes, it would be useful to eventually be able to emulate this, and/or simulate it in the DDL simulation. An issue would be useful so we won't forget, but we'll definitely not plan this for 3.13 anymore.

**Comment by lukaseder** [comment]
All issues have been addressed by dedicated, separate issues. Closing this as a duplicate
