### ISSUE TITLE
java 8+ distribution of 3.12.0 broken

### ISSUE THREAD

**Issue by oflege** [jOOQ/jOOQ#9122]
download of the 3.12.0 java 8+ distribution yields the same zip file as is returned for the java 11+ distribution and contains classes with class file version 55.0 which cannot be used with a java 8/9/10 runtime

**Comment by lukaseder** [comment]
Thank you very much for your report.

There was an error in the website's download logic that did not re-route 3.12 / Java 8 downloads for the commercial distribution to the appropriate directories on the server. All mirrors were affected.

This is now fixed. Thanks again for your report!
