### ISSUE TITLE
how can jooq sql without table name ?

### ISSUE THREAD

**Issue by benkris1** [jOOQ/jOOQ#9124]
the jooq generator sql like 

    select `user`.`id`, `user`.`city`, `user`.`name` from `user` where `user`.`id` = 0

but i wan't 

    select `id`, `city`,`name` from `user` where `id` = 0

without table name.

same plugin(like sharding-jdbc) can't parse the first sql.

**Comment by benkris1** [comment]
my versrion is 3.11.4

**Comment by lukaseder** [comment]
Thank you very much for your message. There are many reasons why it is more useful (and correct) *in general* to always qualify column names with at least their table names (if not also with their schema names). There are only few reasons to avoid such qualifications, e.g. better readability in simple cases. But as soon as you have at least one join or set operator, etc., the lack of qualification will start causing issues.

This is why jOOQ defaults to generating this syntax. What is the reason why you prefer the unqualified syntax?

**Comment by benkris1** [comment]
my project using [ShardingSphere](https://shardingsphere.apache.org/document/current/en/overview/),it can't parse the  generating this syntax。 if jooq has a switch like Settings().withRenderTableName(false) will be nice.

**Comment by lukaseder** [comment]
Oh interesting. I haven't heard of a parser yet, that couldn't handle qualified table names - but it definitely makes sense to keep that in mind. I've created a feature request for this:
https://github.com/jOOQ/jOOQ/issues/9128

Of course, you can work around this current limitation very easily, using plain SQL templating, for example: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

Or using a `VisitListener`:

```java
public class UnqualifyingListener extends DefaultVisitListener {
    @Override
    public void visitStart(VisitContext context) {
        if (context.queryPart() instanceof TableField) {
            TableField<?, ?> field = (TableField<?, ?>) context.queryPart();
            context.queryPart(DSL.field(field.getUnqualifiedName(), field.getDataType()));
        }
    }
}
```

**Comment by lukaseder** [comment]
This already had a feature request before: #8893
