### ISSUE TITLE
Support parsing ALTER TABLE ... ADD ... AUTO_INCREMENT

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9129]
`DSLContext#alterTable()` supports adding identity columns, but the parser cannot parse a corresponding statement correctly.

Parsing `alter table a add i varchar(10) not null auto_increment` will for instance result in the following error:

```java
org.jooq.impl.ParserException: Unexpected clause: [1:42] alter table a add i varchar(10) not null [*]auto_increment
	at org.jooq.impl.ParserContext.exception(ParserImpl.java:10693)
	at org.jooq.impl.ParserContext.done(ParserImpl.java:10813)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:599)
	at org.jooq.impl.ParserImpl.parseQuery(ParserImpl.java:591)
```

Please note that the parser can parse a corresponding `CREATE TABLE` statement.

**Comment by lukaseder** [comment]
The syntax you've suggested doesn't work in MySQL; but this could work:

```sql
alter table a add i int not null primary key auto_increment;
```

**Comment by lukaseder** [comment]
Having said so, the `primary key` modifier is not yet supported either, and it is a requirement for the `auto_increment` flag. Otherwise, we're getting:

> SQL-Fehler [1075] [42000]: Incorrect table definition; there can be only one auto column and it must be defined as a key

**Comment by lukaseder** [comment]
This syntax is also possible:

```sql
alter table a add i int not null auto_increment, add primary key (i);
```

**Comment by lukaseder** [comment]
There are many subtle syntactic differences of various DDL statements. The one suggested in the issue is supported by now.
