### ISSUE TITLE
Support parsing MySQL BIT(1) value literals

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9131]
The parser currently doesn't support parsing MySQL's [bit value literals](https://dev.mysql.com/doc/refman/8.0/en/bit-value-literals.html), which could occur anywhere in a `SELECT` statement or for example as default value in a `CREATE TABLE` statement:

```sql
CREATE TABLE `example` (
 `field` bit(1) NOT NULL DEFAULT b'0'
);
```

**Comment by lukaseder** [comment]
In fact, I wonder if our understanding of MySQL's `BIT` type is wrong. We map it to `SQLDataType.BIT`, which is a boolean (as in SQL Server). But in fact, it's a numeric / binary type: https://dev.mysql.com/doc/refman/8.0/en/bit-type.html

**Comment by lukaseder** [comment]
... Meaning that in order to fix this in the parser, we'll first need more thorough thoughts about our type representation of MySQL `BIT`

**Comment by lukaseder** [comment]
Fixing the `BIT` type will be done separately: https://github.com/jOOQ/jOOQ/issues/10323. This issue will add support for bit value literals, and for now, continue to throw an exception for `BIT(N)` literals where `N > 1`
