### ISSUE TITLE
Support parsing MySQL's USING [ BTREE | HASH ] index type syntax everywhere where it is supported

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9132]
As MySQL's [`CREATE TABLE`](https://dev.mysql.com/doc/refman/8.0/en/create-table.html) allows for inline index creation, the statement also has the `USING [ BTREE | HASH ]` clause.

In MySQL BTREE is also the default for most storage engines, but for some it is also HASH.

Note that `CREATE INDEX ... USING BTREE` was already implemented in #7749.

**Comment by lukaseder** [comment]
I think we should focus on implementing your parser heuristics idea (#9084). We should collect a set of syntaxes that these heuristics should parse, and we can ignore them. That might scale a bit better in the future, than creating an issue on GitHub per syntax.

**Comment by knutwannheden** [comment]
> I think we should focus on implementing your parser heuristics idea (#9084). We should collect a set of syntaxes that these heuristics should parse, and we can ignore them. That might scale a bit better in the future, than creating an issue on GitHub per syntax.

Yes, I also like that idea. I will look into it.

**Comment by lukaseder** [comment]
Related #9217

**Comment by lukaseder** [comment]
I don't fully trust those heuristics yet, as discussed in that other issue. Meanwhile, supporting this relatively common clause in the parser seems not too difficult. I'll take this and implement it "classically".

In fact, we might want to support index types natively (see #9230) and translate them between dialects, in case of which this particular syntax needs to be parsed explicitly anyway.

**Comment by lukaseder** [comment]
Heh, there's some additional fun caveat in the syntax:

```
| {INDEX|KEY} [index_name] [index_type] (key_part,...)
      [index_option] ...
```

Where 

```
index_type:
    USING {BTREE | HASH}

index_option:
    KEY_BLOCK_SIZE [=] value
  | index_type
  | WITH PARSER parser_name
  | COMMENT 'string'
  | {VISIBLE | INVISIBLE}
```

So, this clause can be placed before or after the column list... :-)

**Comment by lukaseder** [comment]
Even this parses o_O

```sql
create table t (i int, index using btree (i) using hash);
```

**Comment by lukaseder** [comment]
And then, we can also use the syntax with constraints (which automatically create indexes, too)

**Comment by lukaseder** [comment]
It is, however, not possible with foreign key constraints

**Comment by lukaseder** [comment]
Notice, in issue #9120, the syntax exposing the problem was an `ALTER TABLE .. ADD PRIMARY KEY (..) USING BTREE` statement! See https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

**Comment by lukaseder** [comment]
It is not possible to specify these clauses on inline constraint definitions, such as:

```sql
create table t (i int primary key using btree);
```

**Comment by lukaseder** [comment]
These both work:

```sql
create table t (i int, primary key using btree (i));
create table t (i int, primary key (i) using btree);
```

**Comment by lukaseder** [comment]
Of course, this whole duality of supporting that index type before or after the column spec also exists in `create index` and are not yet supported by jOOQ. These both work:

```sql
create index i using btree on t (a);
create index i on t (a) using btree;
```
