### ISSUE TITLE
404s on /latest Javadoc

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9133]
The `/latest` Javadoc currently "404s" on most URLs. Probably, the `.htaccess` file was edited in a wrong way.

**Comment by lukaseder** [comment]
This is caused by the fix https://github.com/jOOQ/jOOQ/issues/9099

**Comment by lukaseder** [comment]
We should make sure that any Javadoc plugin backport is done only for `jOOQ-checker`, which exposes the problem worked around by #9099, not for the entirety of jOOQ. We don't publish the `jOOQ-checker` Javadoc on the website.

**Comment by knutwannheden** [comment]
Javadoc + JPMS drives me crazy!

**Comment by lukaseder** [comment]
Welcome to library development :-)

**Comment by lukaseder** [comment]
(I think the jOOQ code base has about 500 little tweaks working around bugs in gazillion dependencies. And we're an almost-no-dependency library, luckily)

**Comment by lukaseder** [comment]
This seems to work on 3.13: https://github.com/jOOQ/jOOQ/commit/2bcd6d5020c1009b91f2814680a124d7cc6beaa3

Will try backporting to 3.12, and re-publish the 3.12.1 Javadoc

**Comment by lukaseder** [comment]
The Javadoc in the published 3.12.1 artifacts (website, Maven Central) will not be updated. In the Maven Central case, that wouldn't be possible anyway, for the same version number. We'll just re-publish the one hosted on our website, under the same 3.12.1 version.

For the artifacts, the difference is cosmetic. (I was a bit scared by the sudden decrease of ZIP file size, though... 😉)

**Comment by lukaseder** [comment]
Seems to be fixed now. I can build the `jOOQ-checker` Javadoc with the older plugin version:

![image](https://user-images.githubusercontent.com/734593/64160528-64710980-ce3c-11e9-9535-c0e7495878e8.png)

And publish the modularised Javadoc for jOOQ, the core library, which fixes the 404.

**Comment by lukaseder** [comment]
Backport implemented on 3.12.2: #9137
