### ISSUE TITLE
Wrong rendering of [ FROM { FIRST | LAST } ] clause for NTH_VALUE()

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9134]
With #7440 support was added for the `FROM { FIRST | LAST }` clause supported by `NTH_VALUE()` in Oracle, DB2, and H2.

For H2 the SQL is rendered correctly, but for Oracle and DB2 the clause is being rendered inside the parenthesis of the `NTH_VALUE()` call rather than after it, which is incorrect. For reference see https://docs.oracle.com/cd/E11882_01/server.112/e25554/analysis.htm#DWHSG021 and https://www.ibm.com/support/knowledgecenter/SSCRJT_5.0.4/com.ibm.swg.im.bigsql.commsql.doc/doc/r0023461.html.

**Comment by lukaseder** [comment]
The Db2 link is incorrect (different product). Indeed, in LUW, the documented syntax is according to the standard to put those clauses between the `NTH_VALUE()` function call and the `OVER` clause:
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_11.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0023461.html

Notice that in DB2's `NTH_VALUE()`, also the `{ IGNORE | RESPECT } NULLS` syntax follows the SQL standard, whereas the `FIRST_VALUE()` / `LAST_VALUE()` syntax passes these flags as string arguments. We're currently not integration testing that.

**Comment by lukaseder** [comment]
Fixed in 3.13.0. Backport scheduled for 3.12.2 (#9135)

**Comment by lukaseder** [comment]
I've created a separate issue for this: https://github.com/jOOQ/jOOQ/issues/9136
