### ISSUE TITLE
Support disabling foreign key constraints in DDLDatabase

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9156]
Some dialects like MySQL allow to temporarily disable foreign key constraints using a command like e.g. `SET FOREIGN_KEY_CHECKS = 0`. That way `CREATE TABLE` statements presumably don't have to appear in the correct order in a DDL script.

See also #9120.

**Comment by JanecekPetr** [comment]
Looks like a duplicate of #8105.

**Comment by lukaseder** [comment]
And I did not even have a déjà vu! Thanks a lot for the feedback, @JanecekPetr
