### ISSUE TITLE
Prevent "Illegal reflective access operation" warning in jOOQ Open Source Edition

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9157]
#7950 has been fixed in the JDK 11 distribution of the commercial jOOQ editions. However, since we decided to continue supporting Java 8 in the jOOQ Open Source Edition, this issue persists there, with no viable workaround short of upgrading to a commercial distribution.

This issue should look into finding a workaround on the JDK 8 builds, including the commercial distributions, in case someone wants to run the JDK 8 build on Java 9 or 10.

If a workaround can be found, we'll backport the fix to 3.12.x

**Comment by lukaseder** [comment]
Fixed in 3.13.0. Backport scheduled for 3.12.2 (#9262)

**Comment by lukaseder** [comment]
There are regressions in the OSS edition

**Comment by lukaseder** [comment]
The main use case of using that `CACHED_LOOKUP_CONSTRUCTOR` was to use it for reflection on Java 8 default methods. A secondary use case is in-memory compilation.

**Comment by dmoebius** [comment]
> Fixed in 3.13.0. Backport scheduled for 3.12.2 (#9262)

To others who stumble upon this: the fix is backported in 3.12.4, not 3.12.2 or 3.12.3.

**Comment by lukaseder** [comment]
Thanks for the hint, @dmoebius. I updated my comment that claimed it was in 3.12.2 (I really wish Github had a way to attach an issue to more than 1 milestone!).
