### ISSUE TITLE
Parser missing type information for Enum fields

### ISSUE THREAD

**Issue by rsmckinney** [jOOQ/jOOQ#9162]
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

- Parse any schema having a table with an ENUM e.g., from the standard `employees` MySql sample db:
```sql
CREATE TABLE employees (
    emp_no      INT             NOT NULL,
    birth_date  DATE            NOT NULL,
    first_name  VARCHAR(14)     NOT NULL,
    last_name   VARCHAR(16)     NOT NULL,
    gender      ENUM ('M','F')  NOT NULL,
    hire_date   DATE            NOT NULL,
    PRIMARY KEY (emp_no)
);
```
- Parse the schema:
```java
...
DSLContext ctx = DSL.using(SQLDialect.MYSQL);
Meta meta = ctx.meta(Source.of(employees));
```
- Use a debugger to examine the `Table` object corresponding with `employees` table. Notice there is no type information available for the GENDER field other than the `Object` data type. I expected to see type info for the enum constants:
![image](https://user-images.githubusercontent.com/588843/64300729-d88dd900-cf32-11e9-974d-cc31de9228fa.png)
 
### Versions:

- jOOQ: 3.12.0
- Java: 8
- JDBC Driver (include name if inofficial driver): H2

**Comment by lukaseder** [comment]
Thank you very much for your report. I suspect this might not be a parser issue, but a DDL simulation issue. Will investigate right away

**Comment by lukaseder** [comment]
I can reproduce the issue with the following test:

```java
    @Test
    public void testMySQLEnumTypes() {
        String sql = "create table t(e enum('a', 'b'))";
        Meta meta = meta(sql);

        List<Table<?>> tables = meta.getTables("T");
        assertEquals(1, tables.size());

        Table<?> table = tables.get(0);
        assertEquals("T", table.getName());

        Field<?>[] fields = table.fields();
        assertEquals(1, fields.length);

        Field<?> field = fields[0];
        assertEquals("E", field.getName());
        assertTrue(field.getDataType().isEnum());
    }

    private static final Meta meta(String... sql) {
        Source[] sources = new Source[sql.length];

        for (int i = 0; i < sql.length; i++)
            sources[i] = Source.of(sql[i]);

        return DSL.using(new DefaultConfiguration()).meta(sources);
    }
```

**Comment by lukaseder** [comment]
The query is parsed correctly and translated correctly to H2:

```sql
create table t(
  e enum('a', 'b') null
)
```

But then, we're not correctly reading the meta information back from H2 again, via JDBC `DatabaseMetaData`. Which reminds me that we're still not doing quite a few things correctly, related to H2 enums, as they have been a bit of a moving target in recent releases, see e.g.:
https://github.com/jOOQ/jOOQ/issues/7917

H2 reports the following column information about the above table `T`:

```
+--------------------------------------------------+-----------+----------+-----------+---------+---------+-----------+-------------+--------------+--------------+--------+-------+----------+
|TABLE_CAT                                         |TABLE_SCHEM|TABLE_NAME|COLUMN_NAME|DATA_TYPE|TYPE_NAME|COLUMN_SIZE|BUFFER_LENGTH|DECIMAL_DIGITS|NUM_PREC_RADIX|NULLABLE|REMARKS|COLUMN_DEF|
+--------------------------------------------------+-----------+----------+-----------+---------+---------+-----------+-------------+--------------+--------------+--------+-------+----------+
|JOOQ-EXTENSIONS-FD17201D-22C5-4EBD-BBB6-FA2019E...|PUBLIC     |T         |E          |     1111|ENUM     |          1|1            |             0|            10|       1|       |{null}    |
+--------------------------------------------------+-----------+----------+-----------+---------+---------+-----------+-------------+--------------+--------------+--------+-------+----------+
```

I'm currently not sure what the best approach would be here for this edge case.

- Our DDL simulation would solve this: https://github.com/jOOQ/jOOQ/issues/7034 (high prio for 3.13)
- Merging `jOOQ-meta` (the meta data source for the code generator) into the core might help solve this (a lot of work, low prio)
- Running some additional meta data queries for this case would solve this (doesn't scale well)
- Enforcing the emulation of enum types using `CHECK` constraints would be a viable workaround (as is being done in other dialects than MySQL, PostgreSQL, and H2)

**Comment by lukaseder** [comment]
H2 2.0.202 has now been released and it cleaned up quite a bit on how it represents `ENUM` types in the `INFORMATION_SCHEMA`. Once we support that H2 version in jOOQ 3.16, there's probably room for fixing this issue here.

See also: https://github.com/jOOQ/jOOQ/issues/9609

**Comment by lukaseder** [comment]
With jOOQ 3.16 and H2 2.0.202, this now works as expected

There's now an in-memory compiled `enum` type to represent the database type:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/734593/144574164-6416cbad-7784-4f3d-87c4-2760cb8ded46.png">

And the `Meta.toString()` call correctly reproduces the `ENUM` declaration

<img width="567" alt="image" src="https://user-images.githubusercontent.com/734593/144574200-6c3f9c28-1528-4685-af9a-46178b6f9b9e.png">
