### ISSUE TITLE
Check @Support annotation on WithStep#mergeInto() methods

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9180]
Currently the `WithStep#mergeInto()` methods, corresponding to a `WITH ... MERGE INTO` CTE, only declare support for SQL Server. At least also H2 appears to support this syntax: http://www.h2database.com/html/commands.html#with.

Alternatively these methods should possibly also be `@Pro` annotated.

Please also note that in the OSS edition these methods are annotated as `@Supported({})`, which is wrong, as it means *all* dialects support this syntax.

**Comment by katzyn** [comment]
Please note that current BNF grammar on website is incomplete, actually both [non-standard](https://h2database.com/html/commands.html#merge) and [standard](https://h2database.com/html/commands.html#merge_using) `MERGE` statement are supported.

CTEs are still experimental in H2, however, and they have some known issues.

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/9318
