### ISSUE TITLE
Support various DUAL table aliases in parser

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9182]
Many dialects have some kind of `DUAL` table. Sometimes it is called `SYSIBM.DUAL` or `SYSIBM.DUMMY1`, `RDB$DATABASE`, etc. In some dialects it isn't necessary and in others there is no equivalent and it has to be emulated (see also #6023).

It would still be nice if the parser could handle a few more standard ones like those listed above. See also class `org.jooq.impl.Dual`.

**Comment by lukaseder** [comment]
This would definitely help. But is this really different from #6023? The linked issue doesn't explicitly specify whether configurability is meant to be done for the parser and/or the SQL renderer. There will obviously need to be configurability in both ways...

**Comment by knutwannheden** [comment]
We could close it as duplicate. I thought #6023 was mostly about configurability, which I wonder if we really need it...

**Comment by lukaseder** [comment]
> I thought #6023 was mostly about configurability, which I wonder if we really need it...

Well, in case of Oracle, the usage of `DUAL` is rather straightforward and standard. But in other RDBMS, our emulations might not be optimal / correct / etc, so, being able to override it in the SQL renderer might be a useful edge case use case.

In the parser, on the other hand, being able to configure these is definitely a must. We cannot just blindly assume that all sorts of table expressions that happen to be possible `DUAL` emulations are actual `DUAL` emulations. E.g. in Firebird, using `RDB$DATABASE` happens to work, but there might as well be a legit use case to actually query that table, not just to abuse it as `DUAL`.

So, I think the feature is really about this configuration, accompanied by reasonable defaults.

**Comment by knutwannheden** [comment]
OK. Let's close this issue.
