### ISSUE TITLE
Is DefaultDSLContext thread safe?

### ISSUE THREAD

**Issue by JamesZBL** [jOOQ/jOOQ#9185]
### Your question:
Is DefaultDSLContext object thread safe ?
I used it in a parallelStream body. There isn't any errors now, but I'm not sure if it's really thread-safe.

### Versions:
- jOOQ: 3.11.12
- Java: 1.8
- Database (include vendor): MySQL 5.7
- OS: Mac OS 10.14
- JDBC Driver (include name if inofficial driver): 8.0

**Comment by knutwannheden** [comment]
The `DefaultDSLContext` object itself is thread-safe. But please note that the associated `Configuration` object is not thread-safe when using the standard `DefaultConfiguration` implementation class. Although if you don't modify the `DSLContext`'s `Configuration` while queries are being rendered or executed within this `DSLContext` (which would be a bad practice), you are safe.

Hope this helps. Please reopen if this doesn't fully answer your question.
