### ISSUE TITLE
Cannot use DayToSecond intervals in Oracle, for intervals bigger than 99 days

### ISSUE THREAD

**Issue by nielsmeijer** [jOOQ/jOOQ#9188]
When using the jOOQ oracle dialect in combination with Interval types (```DayToSecond``` and ```YearToMonth```), precision errors occur when the used value is equal to or greater then 100. 

The queries then fail with ORA ```ORA-01873: the leading precision of the interval is too small```

The issue seems to be that jOOQ doesn't supply a precision in the generated SQL query; the default precision used by oracle  ```Day``` / ```Year``` is 2, limiting the max value to 99.

## Code sample:

```java
DSL.using(SQLDialect.ORACLE12C)
.select( now() )
.where( now().greaterOrEqual( now().minus( new DayToSecond(100, 0, 0, 0)) ) ) 
.execute();
```
The sample above is translated to the following SQL statement:

```sql
select current_timestamp
from dual
where current_timestamp >= (current_timestamp - cast('+100 00:00:00.000000000' as interval day to second))
```
This query fails with ```ORA-01873: the leading precision of the interval is too small``` 
(See also http://www.nazmulhuda.info/ora-01873-the-leading-precision-of-the-interval-is-too-small)

## Expected behaviour:

When the generated SQL Query contains an precision, the query executes as expected:

```sql
select current_timestamp
from dual
where current_timestamp >= (current_timestamp - cast('+100 00:00:00.000000000' as interval day(3) to second))
```

### Versions:

- jOOQ: tested on ```3.11.7 (pro)``` and ```3.11.11 (pro)```
- Database: ```Oracle Database 11g Enterprise Edition Release 11.2.0.1.0``` and ```Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 ```
- JDBC Driver: oracle ojdbc7

**Comment by lukaseder** [comment]
Thank you very much for your report. This seems straightforward to fix. We'll look into it ASAP and backport the fix to 3.12.2 and 3.11.13

**Comment by lukaseder** [comment]
This is now fixed in jOOQ 3.14.

While the fix was straightforward in 3.14, it depends on a variety of recent improvements to the `DataType` internals, which means a backport to older versions is too risky.

The workarounds on older versions include:

- An `ExecuteListener` to patch such interval expressions using regular expressions.
- Plain SQL templating to produce string-based versions of the interval expression: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

Thanks again for your report!

**Comment by lukaseder** [comment]
H2 is affected as well

**Comment by lukaseder** [comment]
HSQLDB is affected as well

**Comment by lukaseder** [comment]
HSQLDB implementation has been added via https://github.com/jOOQ/jOOQ/commit/971ed06be9000bb58761f79be0434f05af67d0d9
