### ISSUE TITLE
Implicit JOIN without prefix

### ISSUE THREAD

**Issue by raderio** [jOOQ/jOOQ#9189]
At the moment for implicit join we should use "prefix"
```
create.select(
          BOOK.author().FIRST_NAME,
          BOOK.author().LAST_NAME,
          BOOK.TITLE,
          BOOK.language().CD.as("language"))
      .from(BOOK)
      .fetch();
```

Is it possible to add implicit join just for the query
```
create.select(
          AUTHOR.FIRST_NAME,
          AUTHOR.LAST_NAME,
          BOOK.TITLE,
          BOOK.language().CD.as("language"))
      .from(BOOK)
      .fetch();
```
?

Or maybe by some flag
```
create.select(
          AUTHOR.FIRST_NAME,
          AUTHOR.LAST_NAME,
          BOOK.TITLE,
          BOOK.language().CD.as("language"))
      .from(BOOK)
      .autojoin()
      .fetch();
```

**Comment by lukaseder** [comment]
Thank you very much for your message.

We're still exploring further options to improve implicit joins in the jOOQ API, mostly through https://github.com/jOOQ/jOOQ/issues/7536

One of the biggest challenges of implicit joins is to be sufficiently implicit without being ambiguous.Both of your example improvements would actually be ambiguous very easily, once there are several foreign keys between book and author, or even a path that goes through an additional table, e.g. a relationship table.

While it might make sense to do such a join automatically, it may not in other cases.

However, do note that any jOOQ query is simply a dynamic SQL expression tree that just happens to look like an actual SQL statement. Nothing keeps you from using local variables and reusing those:

```java
Author author = BOOK.author();
create.select(
          author.FIRST_NAME,
          author.LAST_NAME,
          BOOK.TITLE,
          BOOK.language().CD.as("language"))
      .from(BOOK)
      .fetch();
```
