### ISSUE TITLE
Access query element for SQL manipulation before execution

### ISSUE THREAD

**Issue by luca91** [jOOQ/jOOQ#9198]
### Your question:
Is there a way to construct a query using DSL and then access the resulting Query object fields and methods to perform manipulation? Right now I'm using Java reflection which is very very dirty and also resource consuming. 
Thanks

### Versions:

- jOOQ: 3.11.11
- Java: OpenJDK 11.0.3
- Database (include vendor): PostgreSQL 9.4
- OS: Ubuntu 18.10
- JDBC Driver (include name if inofficial driver): JDBC4

**Comment by knutwannheden** [comment]
Thank you very much for your request.

At the moment the only official available SPI is the `VisitListener`. While this SPI is very powerful, it is also very low-level and difficult to get right. Further, it is still lacking in the area of querying the `Query` objects.

For the upcoming 3.13 release we have however [plans to deliver](https://github.com/jOOQ/jOOQ/projects/2) what you are requesting here. The current thinking is that the query object model will be immutable, but there will still be the possibility to replace entire query parts.

Thus, your reflection-based approach will almost certainly break with jOOQ 3.13. But hopefully it won't be too difficult to migrate to the new query object model API.

I hope this answers your question.
