### ISSUE TITLE
Avoid unnecessary warning when there are multiple nextval default values (not caused by serial types) in PostgreSQL

### ISSUE THREAD

**Issue by ssssteffff** [jOOQ/jOOQ#9200]
### Your question:

I wonder why jOOQ generator checks for identiy columns based on their default value, cf:
https://github.com/jOOQ/jOOQ/blob/d75ac1a799140ff9f554923a828f52642ad9408c/jOOQ-meta/src/main/java/org/jooq/meta/postgres/PostgresTableDefinition.java#L126

I have several tables with multiple sequence-based columns (ie `nextval` default values), and I get such warnings:

> Table mytable has multiple identity columns. Only the first one is considered.

Wouldn't it be possible to detect identity columns by other means?

### Versions:

- jOOQ: 3.11.10
- Java: 11
- Database (include vendor): PostgreSQL 10.10
- OS: Linux Mint 18
- JDBC Driver (include name if inofficial driver): org.postgresql.Driver 42.2.5

**Comment by lukaseder** [comment]
We don't formally support them yet, but we definitely should: https://github.com/jOOQ/jOOQ/issues/6659

However, the warnings shown here could be fixed even before fully supporting identities

**Comment by azell** [comment]
Quick testing with Postgres 9.4.24, 10.10 and 11.5 shows that adding `COLUMNS.IS_IDENTITY` to `PostgresTableDefinition.getElements0` works, and returns a useful value for 10.10 and 11.5.  Version 9 still needs the custom `nextval` check.

**Comment by knutwannheden** [comment]
For Postgres 10+ the code generator will now use the `COLUMNS.IS_IDENTITY` flag.

**Comment by lukaseder** [comment]
The current implementation will introduce major regressions. Please review my comment here: https://github.com/jOOQ/jOOQ/commit/19a61d2214cd3aeb0e2bde583f4e0a115eaaa3ea#r36882705

**Comment by knutwannheden** [comment]
> The current implementation will introduce major regressions. Please review my comment here: [19a61d2#r36882705](https://github.com/jOOQ/jOOQ/commit/19a61d2214cd3aeb0e2bde583f4e0a115eaaa3ea#r36882705)

Thanks for reviewing this. I have now updated the logic as discussed: The `IS_IDENTITY` value will now only be used for tables which have at least one column where `IS_IDENTITY = 'YES'` (yes, in PostgreSQL there can be more than one :nauseated_face:). For tables where this isn't the case the code generator will proceed as before: Any column where the default value starts with `nextval` will be regarded as an identity column.

**Comment by lukaseder** [comment]
Thanks for the fix. That rings a bell 😁 https://twitter.com/lukaseder/status/1205046981833482240
