### ISSUE TITLE
Negative intervals not rendered properly for PostgreSQL

### ISSUE THREAD

**Issue by bradnewman** [jOOQ/jOOQ#9201]
### Expected behavior and actual behavior:

A negated `DayToSecond` value with non-zero hours, seconds, and/or days is rendered in a way that does not produce the expected behavior for PostgreSQL.

              // (day, hour)
    new DayToSecond(0, 1).neg()
    
Produces:
    
    cast('-0 01:00:00.000000000' as interval day to second)
 
PostgreSQL appears to interpret the leading negative sign as only applying to the days, and not the hours/minutes/seconds.  Thus, I expect that this interval should instead be rendered for PostgreSQL as:

    cast('-0 -01:00:00.000000000' as interval day to second)

A few queries to show the behavior of PostgreSQL:

    dbuser=# select timestamp '1970-01-01 00:00:00' + cast('-1 01:01:01.000000000' as interval day to second);
            ?column?
    ------------------------
     1969-12-31 01:01:01
    (1 row)
    
    dbuser=# select timestamp '1970-01-01 00:00:00' + cast('-1 -01:01:01.000000000' as interval day to second);
            ?column?
    ------------------------
     1969-12-30 22:58:59
    (1 row)
    
    dbuser=# select timestamp '1970-01-01 00:00:00' + cast('1 -01:01:01.000000000' as interval day to second);
            ?column?
    ------------------------
     1970-01-01 22:58:59
    (1 row)

Trying to work around this by using negative values for the components of the `DayToSecond` instead of `DayToSecond.negative`, I ran into a second issue: #9202.

### Versions:

- jOOQ: 3.12.1
- Java: OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~19.04.1-b10)
- Database (include vendor): PostgreSQL 11.5-1.pgdg19.04+1 amd64
- OS: Ubuntu 19.04 amd64
- JDBC Driver (include name if inofficial driver): org.postgresql:postgresql:42.2.6

**Comment by knutwannheden** [comment]
Closer investigation reveals that this problem only pertains to inlined `YearToSecond` values. Using bind variables should thus be a workaround.

The problem has been fixed on master (3.13) and will be backported to 3.12.2.
