### ISSUE TITLE
Negative intervals not rendered properly for PostgreSQL - Merge [#9201]

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9208]

**Comment by as82359** [comment]
Still not working properly. An interval of -20 minutes is rendered as '+0 0:-20:0.000000000', but it should be '+0 -0:20:0.000000000' (mark the position of the minus sign).

**Comment by lukaseder** [comment]
@as82359 Thank you very much for your feedback. This might be a different case than the one that was fixed here. May I ask you to please open a new issue with details on how to reproduce your case?
