### ISSUE TITLE
Using VARBINARY type yields generated source with a Java compiler warning.

### ISSUE THREAD

**Issue by matthijs-oosterhoff** [jOOQ/jOOQ#9218]
### Expected behavior and actual behavior:

In my database I have some tables with fields like this:
```SQL
CREATE TABLE `foo`
(
    `bar` VARBINARY(256) NOT NULL
)
```

This yields generated Java code which contains methods like these:
```java
    @Override
    public FooRecord value1(byte... value) {
        setBar(value);
        return this;
    }
```

The parent has a signature with a generic `<T>` as method argument:
```java
    Record1<T1> value1(T1 value);
```

In recent Java versions this generates a compiler warning:
```
[WARNING] /home/matthijs/testproj/target/generated-sources/jooq/testproj/generated/db/tables/records/FooRecord.java
:[229,45] value1(byte...) in testproj.generated.db.tables.records.FooRecord implements value1(T1) in org.jooq.Record1
; overridden method has no '...'

```
I guess the generates code should just use `byte[]` as argument type instead of the `byte...` vararg.

### Steps to reproduce the problem:
See example code.

### Versions:

- jOOQ: 3.12.1
- Java: openjdk 11.0.4 2019-07-16
- Database (include vendor): MySQL 5.7.27-0ubuntu0.18.04.1
- OS: Ubuntu 18.04.3 LTS
- JDBC Driver (include name if inofficial driver): com.mysql.cj.jdbc.Driver

**Comment by lukaseder** [comment]
Thank you very much for your message. Historically, we have generated varargs for array arguments in generated code, which may occasionally be useful when working with arrays. It is obviously not useful with `byte[]`, which are also arrays even if no one uses them as arrays.

The workaround is to use a backwards compatibility configuration called `<varargSetters>`, introduced in jOOQ 3.10: https://github.com/jOOQ/jOOQ/issues/5733. We'll definitely change the default from `true` to `false` in a future version: https://github.com/jOOQ/jOOQ/issues/9241, as this has been an often recurring request.

I hope this helps.
