### ISSUE TITLE
Regression in Extract(QUARTER) on Postgres in 3.12.1

### ISSUE THREAD

**Issue by josephlbarnett** [jOOQ/jOOQ#9219]
### Expected behavior and actual behavior:
```
DSL.concat(
    DSL.extract(dayColumn, DatePart.YEAR),
    DSL.value("-Q"),
    DSL.extract(dayColumn, DatePart.QUARTER)
)
```

renders the following SQL in jOOQ 3.11.12 using `POSTGRES_10` dialect:
```
(cast(extract(year from "table"."day") as varchar) || '-Q' || cast(extract(quarter from "table"."day") as varchar))
```
which renders the string as desired as `2016-Q1`

but this SQL in jOOQ 3.12.1 using the `POSTGRES` dialect:
```
(cast(extract(year from "table"."day") as varchar) || '-Q' || cast(((extract(month from "table"."day") + 2) / 3) as varchar))
```
which renders the string as `2016-Q1.33333333333333326`

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

see https://github.com/josephlbarnett/jOOQ-mcve

### Versions:

- jOOQ: 3.12.1
- Java: 11
- Database (include vendor): postgres from https://github.com/opentable/otj-pg-embedded/
- OS: linux
- JDBC Driver (include name if inofficial driver): postgres driver

**Comment by knutwannheden** [comment]
Thank you very much for your report.

We can confirm this regression and will include a fix for this in the 3.12.2 patch release.
