### ISSUE TITLE
Set serialVersionUID to 1L everywhere

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9229]
In our internals, we have randomly generated `serialVersionUID` values. As we are not formally supporting any binary protocols, nor backwards compatibility in this area, this is not really needed. We might as well generate a default `serialVersionUID` of `1L` everywhere.

Dropping the `serialVersionUID` entirely is a less desireable option, as it would produce compiler warnings that might not be suppressable in the same way for all Java compilers.

Note we will review our usage of `Serializable` in general in the next major release, possibly removing serialisability: https://github.com/jOOQ/jOOQ/issues/2359

**Comment by knutwannheden** [comment]
Alternatively we could also remove all these fields. Can both be done with the Eclipse Java compiler and OpenJDK `javac` (using `-Xlint:-serial`):

![image](https://user-images.githubusercontent.com/408765/65117561-644f3d00-d9ea-11e9-92ed-a791a0d042de.png)

![image](https://user-images.githubusercontent.com/408765/65117691-8a74dd00-d9ea-11e9-9290-ccffe149a028.png)

**Comment by lukaseder** [comment]
Thanks for looking it up. Will the javac flag be picked up by IntelliJ as well?

**Comment by knutwannheden** [comment]
In IntelliJ it is also possible to specify the `-Xlint` parameter for `javac`. No idea about VS Code, but I think it should be possible somehow.

Still can't decide which way is better...

**Comment by lukaseder** [comment]
> In IntelliJ it is also possible to specify the -Xlint parameter for javac. No idea about VS Code, but I think it should be possible somehow.

The question is will this parameter be picked up from the Maven compiler plugin configuration, which should be the master here...

**Comment by ThoSap** [comment]
Is this already implemented in jOOQ 3.14.X?
The `serialVersionUID` changed to `1L` when starting the code generation with jOOQ 3.14.1 (which is not a problem).
I did not try jOOQ 3.14.0.


![image](https://user-images.githubusercontent.com/6555967/97536931-38a8cf80-19be-11eb-9732-71f1936d1988.png)

**Comment by lukaseder** [comment]
This is a duplicate of https://github.com/jOOQ/jOOQ/issues/10654, see that other issue for details, if you wish to revert to the previous hash code
