### ISSUE TITLE
It would be nice if update(table).set(Map) was typesafe

### ISSUE THREAD

**Issue by tkram01** [jOOQ/jOOQ#9234]
### Use case:

It would be nice if update(table).set(Map) was typesafe using a typesafe heterogeneous container instead of Map<?, ?>

### Possible solution you'd like to see:

Accept a typesafe heterogeneous map as another override with Map<?, ?>

### Possible workarounds:

Losing type safety

### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. We already have such a heterogeneous container, that's `set(Record)`. What additional features are you missing from this container?

**Comment by tkram01** [comment]
I don't see an easy way to construct a Record without reading it from a table. Using records generated from selects constrains how typesafe updates can be made.

**Comment by lukaseder** [comment]
There are various `DSLContext::newRecord` overloads. In your case, use `ctx.newRecord(table)`, and then, if you're using the code generator, you can use the generated setters on the record. Alternatively, use `record.set(TABLE.COLUMN, value)`.

Does this provide what you were looking for?

**Comment by lukaseder** [comment]
In fact, if you're using generated code, you can also just call `new MyTableRecord()` and take it from there.

**Comment by lukaseder** [comment]
Closing this as I think we already have all the requested tools in our API
