### ISSUE TITLE
jOOQ code generator outputs different data for MSSQL vs SQLite

### ISSUE THREAD

**Issue by rm5248** [jOOQ/jOOQ#9236]
### Expected behavior and actual behavior:
Expected behavior: Float column as defined in both SQLite and MSSQL should generate code that accepts a float value for the *Record.java
Actual behavior: Code generated using SQLite has a column that accepts a float, while the MSSQL generated code uses a double for the column type

The project that I am working on needs to support both SQLite and MSSQL, so this is not just for building code with([as pointed out in this Stackoverflow question](https://stackoverflow.com/a/47176587/624483)).

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

1. Create a simple table like the following:
```
CREATE TABLE ExampleData (
	DataKey INTEGER PRIMARY KEY NOT NULL,
        FloatData FLOAT NULL
);
```
2. Run the code generator on this table.  With SQLite, the following code compiles:
```
ExampledataRecord rec = new ExampledataRecord();
rec.setFloatdata( (float)1.0 );
```
However, when running the generator against MSSQL 2017, the code will fail to compile with the following error:
`incompatible types: float cannot be converted to java.lang.Double`

Minimum example(switch between SQLite generation and MSSQL generation using the ms-sql profile): https://github.com/rm5248/mssql-sqlite-jooq
Note: You will need to change the settings for SQLServer, and probably need to add the correct repository to use the jooq trial version.

### Versions:

- jOOQ: 3.12.1
- Java: openjdk version "11.0.4" 2019-07-16
- Database (include vendor): MS-SQL 2017 and SQLite 3.28
- OS: Linux
- JDBC Driver (include name if inofficial driver): SQLite Xerial / MSSQL

**Comment by rm5248** [comment]
Note: I have just figured out what exactly this is: SQL Server has a ['float' type](https://docs.microsoft.com/en-us/sql/t-sql/data-types/data-types-transact-sql?view=sql-server-2017), while SQLite recognizes both [DOUBLE and FLOAT](https://www.sqlite.org/datatype3.html).

Of course, SQLite being SQLite, you can totally store a text string in the column and it doesn't complain.

So, is this actually a bug in this case?  I'm unsure as to what the best way to handle this is(on my side, I simply need to make sure that float is used against MSSQL and double on the SQLite side).  SQLite stores the real values as 8-byte doubles anyway, so is there even a case where you would store a float in SQLite?

**Comment by lukaseder** [comment]
Thank you very much for your report.

Unfortunately floating point number types are poorly standardised across RDBMS, and it may well be that jOOQ got this wrong for some RDBMS in favour of being able to standardise as much as possible. jOOQ's understanding matches that of the SQL standard:

- `FLOAT` is a variable precision floating point type. As precisions can be higher than 32 bit, we mapped this to  `Double` in Java
- `DOUBLE PRECISION` corresponds to Java's `Double` type
- `REAL` corresponds to Java's `Float` type

The standard's definition:

```
<approximate numeric type> ::=
  FLOAT [ <left paren> <precision> <right paren> ]
| REAL
| DOUBLE PRECISION
```

Obviously, this may not match a specific RDBMS's implementation. Notice that also in SQL Server, `FLOAT` can contain more than 32 bits: https://docs.microsoft.com/en-us/sql/t-sql/data-types/float-and-real-transact-sql?view=sql-server-2017

So, perhaps you meant to use `REAL` as a type here in SQL Server?

**Comment by rm5248** [comment]
What I did was to setup flyway to use DOUBLE for SQLite, and FLOAT for MSSQL.  That ensures that the generated code will always use a `Double` for the column; it was very confusing to me that the databases will have different code for these cases.

If the following is true:

>FLOAT is a variable precision floating point type. As precisions can be higher than 32 bit, we mapped this to Double in Java 

Shouldn't the FLOAT column in SQLite map to a `Double` in Java then?  Currently it maps to a float.

**Comment by lukaseder** [comment]
> Shouldn't the FLOAT column in SQLite map to a Double in Java then? Currently it maps to a float.

You're probably right. I'll review that - there seems to be a wrong configuration in `SQLiteDataType`
