### ISSUE TITLE
Constraint with empty name rendered as CONSTRAINT ""

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9240]
When creating a constraint with the empty string as the name (i.e. using `DSL.constraint("")`) the SQL will be rendered as `CONSTRAINT "" ...`. Rendering the empty name here doesn't really make sense.

This can be improved by changing `ConstraintImpl` to compare its qualified name against `AbstractName.NO_NAME` using `Object#equals()` rather than `==`.

**Comment by lukaseder** [comment]
> This can be improved by changing ConstraintImpl to compare its qualified name against AbstractName.NO_NAME using Object#equals() rather than ==.

Or, alternatively, whenever wrapping a string in a name, making sure that the empty string produces `NO_NAME`

**Comment by lukaseder** [comment]
I.e. in `DSL.name(String)`

**Comment by knutwannheden** [comment]
> Or, alternatively, whenever wrapping a string in a name, making sure that the empty string produces `NO_NAME`

Do you think that is the better alternative? I figured always doing an additional `Object#equals()` in `DSL#name()` would be a higher price to pay. Also, in `QualifiedName#nonEmpty()` we also compare to `NO_NAME` using `Object#equals()`.

**Comment by katzyn** [comment]
In H2 `… CONSTRAINT "" …` is a valid definition and `""` can be used as an identifier in other places too.

**Comment by knutwannheden** [comment]
@katzyn Thanks for pointing this out. That is interesting. Is `""` also a valid name for other object types?

I think we might have to create a separate issue for this corner case.

**Comment by lukaseder** [comment]
> @knutwannheden Do you think that is the better alternative? I figured always doing an additional Object#equals() in DSL#name() would be a higher price to pay. Also, in QualifiedName#nonEmpty() we also compare to NO_NAME using Object#equals().

I don't know. Just wanted to point out the option.

> @katzyn In H2 … CONSTRAINT "" … is a valid definition and "" can be used as an identifier in other places too.

But why? :)

**Comment by katzyn** [comment]
I have no idea. Of course, such identifier is not valid according to the Standard, but H2 it its early days was far from any standards.

**Comment by katzyn** [comment]
Such identifier is also valid in HSQLDB, but it is not valid in Derby.

**Comment by lukaseder** [comment]
@knutwannheden Well, we can open an issue for this edge case, but I prefer to ignore it until someone actually runs into it. Supporting "empty" identifiers might change a lot of jOOQ's internals...

**Comment by katzyn** [comment]
> Is `""` also a valid name for other object types?

Yes, it's just an identifier without any special properties. A pretty weird identifier, I must say.
