### ISSUE TITLE
Regression: DSLContext#nextval() broken for H2

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9248]
`DSLContext#nextval()` is broken for H2 in jOOQ 3.12. This worked in jOOQ 3.11.

**Comment by katzyn** [comment]
The online translator generates `sequenceName.nextval` for H2 output dialect. Such construction is supported by H2 for compatibility and it isn't documented in grammar. The normal syntax for H2 is the `NEXT VALUE FOR sequenceName` and it should be used.

However, jOOQ can produce `sequenceName.currval` for H2 dialect for now.

**Comment by knutwannheden** [comment]
Thanks for pointing this out!

**Comment by katzyn** [comment]
H2 1.4.200 will also have documented and supported Ingres-style `CURRENT VALUE FOR sequenceName` and it will be the preferred way to query the current value. But 1.4.199 has only an Oracle-style `.CURRVAL` and weird, tricky, and possibly buggy `CURRVAL()` function that tries to guess how exactly the schema was passed. Function is documented, but undocumented Oracle-style expression is more reliable.

**Comment by knutwannheden** [comment]
We just recently changed from `CURRVAL()` to `.CURRVAL`: https://github.com/jOOQ/jOOQ/commit/e027518dbd8105a5324dfba00ef96f5b57bf8f01

**Comment by knutwannheden** [comment]
> We just recently changed from `CURRVAL()` to `.CURRVAL`: [e027518](https://github.com/jOOQ/jOOQ/commit/e027518dbd8105a5324dfba00ef96f5b57bf8f01)

Or, actually, that was the intent of the referenced commit. But in the OSS edition the code is broken.
