### ISSUE TITLE
H2: Omit OFFSET clause if offset is 0

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9252]
In the commercial editions the rendered `FETCH NEXT` clause is always preceded by an `OFFSET` clause, even if the offset is 0. See also #3577, where this was solved for Oracle.

Interesting note: In contrast to Oracle, H2 requires the `FETCH NEXT` clause to be used with an `ORDER BY` clause.

**Comment by knutwannheden** [comment]
SQL Server is the only dialect I am aware of where `FETCH NEXT` always requires the `OFFSET` clause.

**Comment by lukaseder** [comment]
> SQL Server is the only dialect I am aware of where FETCH NEXT always requires the OFFSET clause

Yes, that's how I remember it

**Comment by katzyn** [comment]
> In contrast to Oracle, H2 requires the FETCH NEXT clause to be used with an ORDER BY clause.

What exactly do you mean? `ORDER BY` isn't required for `FETCH … ONLY` in H2, it is only required for `FETCH … WITH TIES`. Such requirement also exists in the SQL Standard.

**Comment by knutwannheden** [comment]
> What exactly do you mean? `ORDER BY` isn't required for `FETCH … ONLY` in H2, it is only required for `FETCH … WITH TIES`. Such requirement also exists in the SQL Standard.

Yes, that makes sense. It was a little bit hard to read the railroad diagram here: http://www.h2database.com/html/commands.html#select.

And with `WITH TIES` it is of course a bit weird that Oracle *doesn't* require the `ORDER BY`.

**Comment by katzyn** [comment]
There is a textual description below the diagram:
> `WITH TIES` can be used only together with `ORDER BY` and means that all additional rows that have the same sorting position as the last row will be also returned.

You also can click on the section title (**SELECT**) to replace diagrams with BNF grammar.

**Comment by knutwannheden** [comment]
> You also can click on the section title (**SELECT**) to replace diagrams with BNF grammar.

Thanks for the tip!
