### ISSUE TITLE
Prevent "Illegal reflective access operation" warning in jOOQ Open Source Edition - Merge [#9157]

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9262]
Attention when backporting: First commit was reverted: https://github.com/jOOQ/jOOQ/issues/9157#issuecomment-534561003

**Comment by lukaseder** [comment]
This hasn't been fixed yet. Re-targeting to 3.12.3

**Comment by mkurz** [comment]
Looking forward to get rid of this warning in 3.12.4 :wink:

**Comment by mkurz** [comment]
@lukaseder :+1: Thanks!
