### ISSUE TITLE
Error running jOOQ code generation tool

### ISSUE THREAD

**Issue by liufangpu** [jOOQ/jOOQ#9267]
### Versions:

- jOOQ: 3.11.12
- Java: 11.0.3 
- Database (include vendor): mysql 8.0.17
- OS: windows10 64bit. ,intellij idea
- JDBC Driver (include name if inofficial driver): com.mysql.cj.jdbc.Driver

this is my maven pom:

<plugin>
               
                <groupId>org.jooq</groupId>
                <artifactId>jooq-codegen-maven</artifactId>
                <version>3.11.12</version>

                <executions>
                    <execution>
                        <id>default-cli</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>

                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>8.0.17</version>
                    </dependency>
                </dependencies>

                <configuration>
                    
                    <jdbc>
                        <driver>com.mysql.cj.jdbc.Driver</driver>
                        <url>jdbc:mysql://localhost:3306/test</url>
                        <user>root</user>
                        <password>***</password>
                    </jdbc>

                    <generator>
                        <name>org.jooq.codegen.JavaGenerator</name>
                        <database>
                           
                            <name>org.jooq.meta.mysql.MySQLDatabase</name>
                      
                            <inputSchema>test</inputSchema>
                           
                            <includes>.*</includes>
                            
                            <excludes>
                            </excludes>
                        </database>
                        <target>
                   
                            <packageName>com.example.demo</packageName>
                        
                            <directory>G:\workspace\demo\src\main\java</directory>
                        </target>
                    </generator>

                </configuration>

            </plugin>

**Comment by liufangpu** [comment]
i created a new project with  the newest version springboot2.1.8

**Comment by liufangpu** [comment]
error message is :"Failed to execute goal org.jooq:jooq-codegen-maven:3.11.12:generate (default-cli) on project demo: Error running jOOQ code generation tool"

**Comment by lukaseder** [comment]
Thank you very much for your report. How are you invoking Maven to produce this error message? Do you get any stack traces? Any additional information on how to reproduce this would be very helpful.

**Comment by liufangpu** [comment]
![image](https://user-images.githubusercontent.com/20319520/65671641-2d2bfc00-e07a-11e9-9e16-8b1480a7fcae.png)
i clicked jooq-codegen:generate

**Comment by lukaseder** [comment]
OK, thanks. We'll look into it. I think I've seen this before a few times, including:
https://stackoverflow.com/q/52498022/521799

**Comment by lukaseder** [comment]
Can you try to move your `<configuration>` element inside of `<execution>`? I think that should work.

**Comment by lukaseder** [comment]
I think this is a specific limitation of Maven, and it is not immediately obvious why it doesn't work, see e.g. https://stackoverflow.com/a/3780610/521799

**Comment by liufangpu** [comment]
> Can you try to move your `<configuration>` element inside of `<execution>`? I think that should work.



> Can you try to move your `<configuration>` element inside of `<execution>`? I think that should work.

i've tried to move it ,but it doesn't work, print the same error message as above

**Comment by liufangpu** [comment]
> I think this is a specific limitation of Maven, and it is not immediately obvious why it doesn't work, see e.g. https://stackoverflow.com/a/3780610/521799
I have read this article, but it is not the result I want, and my maven version is 3.6.1

**Comment by lukaseder** [comment]
When checking out our MCVE: https://github.com/jOOQ/jOOQ-mcve, I can successfully invoke the `jooq-codegen:generate` goal from IntelliJ.

I'm not sure how else I could help you... Can you produce an MCVE on your side, which I could check out completely?
