### ISSUE TITLE
Postgresql lacks enum version

### ISSUE THREAD

**Issue by SchweinchenFuntik** [jOOQ/jOOQ#9268]
in version 3.12.1 there is no  `SQLDialect.POSTGRES_9_3`, although according to the documentation there is: https://www.jooq.org/javadoc/3.12.x/org.jooq/org/jooq/SQLDialect.html
![JOOQ_SQLDIALECT](https://user-images.githubusercontent.com/22637705/65596058-ba018780-df9e-11e9-927a-a48062e65df5.png)

**Comment by lukaseder** [comment]
Thank you very much for your report. Starting from jOOQ 3.12, we're offering support for old SQL dialects only in our commercial distributions, similar to the support of old Java versions, which is reserved to our commercial distributions. The relevant change is here: https://github.com/jOOQ/jOOQ/issues/8551

As discussed in https://github.com/jOOQ/jOOQ/issues/8551, we definitely need some additional documentation explaining this change, which will be available soon.

The website Javadoc is for the jOOQ Professional / Enterprise Editions, as that is the most complete Javadoc. You will find a `@Pro` annotation on commercial-only dialects (and other API), and we will update the Javadoc to reflect that also in text.
