### ISSUE TITLE
Add support for ALTER TABLE ADD COLUMN ... AFTER

### ISSUE THREAD

**Issue by kixx** [jOOQ/jOOQ#9269]
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

Trying to do code generation from a Flyway setup, fails with error:

[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.11.9:generate (generate-ddl) on project test-app: Error running jOOQ code generation tool: Unexpected token or missing query delimiter: [2:59] ...BLE `event` ADD `last_seen` datetime DEFAULT NULL [*]AFTER `ended`;

### Versions:

- jOOQ: 3.11.9
- Java: 1.8
- Database (include vendor): MySQL 5.7.22
- OS: Windows
- JDBC Driver (include name if inofficial driver): com.mysql.jdbc.Driver v5.1.47

**Comment by lukaseder** [comment]
Thank you very much for your request. Yes, that would be a very useful feature addition indeed. We're already tracking it as #7241.
