### ISSUE TITLE
Slightly improved code generation pattern

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9272]
The generated code for a schema basically looks like this (some bits left out):

```java
public class DefaultSchema extends SchemaImpl {

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>ACTOR</code>.
     */
    public final Actor ACTOR = org.jooq.example.jpa.jooq.tables.Actor.ACTOR;

    /**
     * The table <code>FILM</code>.
     */
    public final Film FILM = org.jooq.example.jpa.jooq.tables.Film.FILM;

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Actor.ACTOR,
            Film.FILM);
    }
}
```

Some things we could simplify / improve:

1. I don't see any point in generating the separate `getTables0()` method.
1. Should the result returned by `getTables()` really be an instance of `ArrayList`? Or should we use a `Collections#unmodifiableList()`?
1. In `getTables()` we could refer to the tables using the local constants. I.e. `ACTOR` instead of `Actor.ACTOR`.
1. In the table constants (e.g. `ACTOR`) there is no need to use a fully qualified class name on the RHS of the assignment. We can use the simple name as on the declaration side.
1. Most of these comments also apply to generated `CatalogImpl` subclasses.

**Comment by lukaseder** [comment]
> I don't see any point in generating the separate getTables0() method.

See https://github.com/jOOQ/jOOQ/issues/1459, https://groups.google.com/forum/#!topic/jooq-user/2g96fI1Yrj8/discussion, and `JavaGenerator.INITIALISER_SIZE`

We could omit the auxiliary method if there is only one method.

> Should the result returned by getTables() really be an instance of ArrayList? Or should we use a Collections#unmodifiableList()?

Yes we could return an unmodifiable list, as an incompatible change in a minor release.

> In getTables() we could refer to the tables using the local constants. I.e. ACTOR instead of Actor.ACTOR.

But only if `AbstractGenerator.generateGlobalTableReferences()` is true.

> In the table constants (e.g. ACTOR) there is no need to use a fully qualified class name on the RHS of the assignment. We can use the simple name as on the declaration side.

I'm sure this would produce a compilation error in some cases (e.g. single letter table names, such as `T`), and I'm almost sure we already discussed this at some point, but I'm too lazy to look it up now. You can try it :)

> Most of these comments also apply to generated CatalogImpl subclasses.

Agreed, they're almost the same.

So, summarising:

1. I agree we can remove the single auxiliary method, which is useless in 95% of all generated schemas. We should make sure with a new codegen test that we're still generating these auxiliary methods on large schemas.
2. Agreed
3. Cost/benefit is not favourable, so I prefer not to do this
4. Agreed if this doesn't produce compilation errors, but I think it does
5. Agreed

**Comment by lukaseder** [comment]
Another suboptimal thing:

```java
    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();
```

**Comment by knutwannheden** [comment]
The discussed and agreed upon improvements have all been implemented now, except for the `CatalogImpl` subclasses where the fields for the schemas still uses the fully qualified class name in the initializer expression. I suppose we could fix that as well.

**Comment by lukaseder** [comment]
> The discussed and agreed upon improvements have all been implemented now

Excellent

> except for the `CatalogImpl` subclasses where the fields for the schemas still uses the fully qualified class name in the initializer expression. I suppose we could fix that as well.

Sure, why not? It's the same thing as for `SchemaImpl`. Could be useful especially for SQL Server users, where catalogs might be used in queries.
