### ISSUE TITLE
Use Settings.getQueryTimeout() consistently

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9295]
For `Query` there is a `queryTimeout(int)` method, but as documented by #3892 this is for instance missing for `Routine`. Everywhere, where we execute statements in an `ExecuteContext` the `Settings#getQueryTimeout()` setting should be respected.

**Comment by lukaseder** [comment]
While a per-batch timeout is useful as well, what I had meant here is that we should use the `Settings.getQueryTimeout()` value in all statements other than the existing implementation in `Query`. That could be done without any API change already.

**Comment by knutwannheden** [comment]
Yes, I forgot to mention that we should also always respect `Settings.getQueryTimeout()` if there is no dedicated API.

**Comment by lukaseder** [comment]
What I meant is that respecting `Settings.getQueryTimeout()` is much easier to implement (perhaps in a separate issue) because we don't have to design any API change.

**Comment by knutwannheden** [comment]
Makes sense. I have now updated the issue title and description. I think `Batch#queryTimeout(int)` can still wait.
