### ISSUE TITLE
Add parser support for array bind variables in IN lists

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9301]
A lot of ORMs (and Spring) support synthetic bind variables for arrays where `IN` lists are expected, e.g.:

```sql
select * from t where a in ?
```

Instead of the much more verbose:

```sql
select * from t where a in (?, ?, ?, ..., ?)
```

ORMs that parse their JPQL / HQL / whatever language probably understand the semantics of the "array bind variable" and restrict its usage to the `IN` predicate. Other APIs, like Spring, probably do not understand the semantics of the "array bind variable" and just assume usage with the `IN` predicate, replacing `?` by `(?, ?, ?, ..., ?)`

jOOQ's parser could allow array binds with the `IN` predicate, as well as with a few quantified comparison predicates, such as `= ANY ?`.

**Caveats**:

From a parser perspective, this is really easy to implement. But unless the parser is invoked directly, or from the `ParsingConnection`, if we do not have access to actual bind variables, the generated output is undefined. We don't know how many elements there are in the resulting `IN` list, hence the predicate might as well produce the empty `IN ()` list, resulting in `FALSE`. This is a problem with the `jooq.org/translate` website, where binds currently cannot be provided. This can be mitigated by supporting a bind variable form on the website: #9302

**Comment by katzyn** [comment]
Some databases support that feature with some syntax. For example, H2 accepts `= ANY(?)` (only with `=`) and `IN (UNNEST(?))` and provides an optimized implementation for them.

I guess PostgreSQL should accept quantified comparison predicates with array as parameter too.

**Comment by lukaseder** [comment]
Hmm, we already support `= ANY(?)` with arrays, but I think that's a slightly different case. Anyway, good input. We need to take this into broader consideration. Perhaps, we should have native support for this slightly different kind of predicate in jOOQ, and not see it as a parser only problem...

**Comment by katzyn** [comment]
I meant that you can emulate that feature with `= ANY(?)` or with something else in some databases.

**Comment by lukaseder** [comment]
That's what I meant, too :-) It was more a note to myself that this might not just be a parser issue.

**Comment by lukaseder** [comment]
I'll conclude that standard SQL already has sufficient support for arrays through other syntax than the `IN` predicate. Let's not invent weird things with tons of caveats here.
