### ISSUE TITLE
Add SQLDialect.supportedBy(SQLDialect...) to produce a set of supported dialects from an input

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9312]
A lot of times, we have to write code where we check if the `Scope.family()` is in a set (e.g. `EnumSet`) of dialect families, or, alternatively, if some dialect version precedes `Scope.dialect()`.

This logic is error prone and difficult to write. We need a new `org.jooq.SQLDialects` class that acts like an `EnumSet`, but implements the duality of `SQLDialect` as a family vs. as a versioned dialect.

The new class has methods like `SQLDialects.supportedBy(SQLDialect)`, which checks if the argument dialect is supported by one of the dialects in `SQLDialects`

**Comment by lukaseder** [comment]
We already have a perhaps slightly unintuitive `SQLDialect.supports(Collection)` for that purpose. See #8552

**Comment by lukaseder** [comment]
It would still be useful to have a constructor for an `EnumSet`, which already contains all the supported versioned dialects, so we can always call `Set.contains(dialect)` instead of inversing the call to `dialect.supports(set)`

**Comment by lukaseder** [comment]
Perhaps this is what you meant by https://github.com/jOOQ/jOOQ/issues/8662, @knutwannheden ?

**Comment by lukaseder** [comment]
This new method can now be used everywhere we're currently using `EnumSet.of()`. We can continue to use `Set.contains()` check to validate for dialect family compatibility, but now, we can also put minimum dialect versions in the list of supported versions, and use `Set.contains()` to validate a dialect version. Example in `org.jooq.impl.Alias`:

```java
private static final Set<SQLDialect> SUPPORT_DERIVED_COLUMN_NAMES_SPECIAL1 = SQLDialect.supported(
    ASE, CUBRID, FIREBIRD, INFORMIX, INGRES, MYSQL_8_0, // Version here
    SQLDATAWAREHOUSE, SQLSERVER, SYBASE, TERADATA);

// And then
if (... && SUPPORT_DERIVED_COLUMN_NAMES_SPECIAL1.contains(dialect) && ...)
```

**Comment by lukaseder** [comment]
This approach will cover most cases where we start supporting a new feature form a given dialect version. The above example *starts applying* to MySQL 8+.

Sometimes, we used `EnumSet<SQLDialect>` to specify the dialect versions where we had to do some emulation, which we *stopped applying* starting from a given dialect version. The refactoring needs to be careful when distinguishing between the two cases.

**Comment by knutwannheden** [comment]
> Perhaps this is what you meant by #8662, @knutwannheden ?

Yes, at least some parts are definitely in common.

> This approach will cover most cases where we start supporting a new feature form a given dialect version. The above example _starts applying_ to MySQL 8+.

Very nice.

> Sometimes, we used `EnumSet<SQLDialect>` to specify the dialect versions where we had to do some emulation, which we _stopped applying_ starting from a given dialect version. The refactoring needs to be careful when distinguishing between the two cases.

I think it would be nice if we added a utility method for this case as well. Possibly we would have to rename `supported()` so that we have two methods with names like `supportedAsOf()` and `supportedUntil()`. Or possibly the method name should be agnostic with regards to how the set is used. So maybe `allAsOf()` and `allUntil()` or `dialectsAsOf()` and `dialectsUntil()`. What do you think?

Further, since the new `SQLDialect#supported()` returns a set with all supported dialect versions for a given family, I think we should also change all code using these sets to check if the context dialect version is included rather than the family. That way we will be safe when changing one of these sets. If you, for instance, would have forgotten to change the usage of `Alias#SUPPORT_DERIVED_COLUMN_NAMES_SPECIAL1` to check against `dialect` rather than `family`, we might have introduced a regression for older MySQL versions.

**Comment by lukaseder** [comment]
> I think it would be nice if we added a utility method for this case as well. Possibly we would have to rename supported() so that we have two methods with names like supportedAsOf() and supportedUntil(). Or possibly the method name should be agnostic with regards to how the set is used. So maybe allAsOf() and allUntil() or dialectsAsOf() and dialectsUntil(). What do you think?

I agree with both assessments:

- We should have such a method
- These methods should not be called "supported". I'll think of names

> Further, since the new SQLDialect#supported() returns a set with all supported dialect versions for a given family, I think we should also change all code using these sets to check if the context dialect version is included rather than the family

Also agreed. Back to what this was, originally, many releases ago :-)

**Comment by lukaseder** [comment]
A reasonable name for `dialectsUntil` is `predecessors`. We already have that name, and it already means exactly that. Except htat we cannot call the method easily for multiple dialects, e.g.

```java
Set<SQLDialect> dialects = SQLDialect.predecessors(H2, POSTGRES_9_4, MYSQL);
```

The above will contain `(H2, POSTGRES_9_3, POSTGRES_9_4, MYSQL_5_7, MYSQL_8, MYSQL)`

**Comment by lukaseder** [comment]
I cannot think of a better name than `SQLDialect::supported`. I'll leave it as it is for now.

**Comment by lukaseder** [comment]
Reopening this as a reminder to implement: 

> If you, for instance, would have forgotten to change the usage of Alias#SUPPORT_DERIVED_COLUMN_NAMES_SPECIAL1 to check against dialect rather than family, we might have introduced a regression for older MySQL versions.

**Comment by knutwannheden** [comment]
Unfortunately, as I just realized, the static `SQLDialect#supported(SQLDialect...)` cannot be called without arguments (i.e. `SQLDialect.supported()`) as there is already a non-static method with that signature. As a result `SQLDialect#supported(SQLDialect...)` has the same limitation as `EnumSet#of()` in the context of our source preprocessor.

**Comment by lukaseder** [comment]
Yes, we shouldn't call the new method `supported()`

**Comment by lukaseder** [comment]
I'll call it `supportedBy()`
