### ISSUE TITLE
DDLDatabase cannot handle indexes on TEXT columns in PostgreSQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9336]
This is a valid table definition in PostgreSQL:

```sql
create table t (t text not null unique);
```

However, when running this through the `DDLDatabase` (the current one that is implemented by H2), we get this error:

```
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.12.1:generate (default-cli) on project jooq-mcve: Error running jOOQ code generation tool: Error while exporting schema: SQL [create table t(t clob not null, unique (t))]; Dieses Feature wird nicht unterstützt: "Index on BLOB or CLOB column: ""T"" CLOB NOT NULL"
[ERROR] Feature not supported: "Index on BLOB or CLOB column: ""T"" CLOB NOT NULL"; SQL statement:
[ERROR] create table t(t clob not null, unique (t)) [50100-199]
```

This is because of jOOQ's `TEXT -> CLOB` mapping, which has been causing various issues in the past. The workaround is to adapt the PostgreSQL schema as well, or with our new DDL interpretation (#8528), we won't have this problem anymore.

Perhaps, however, there's already a possible workaround for this when using the classic `DDLDatabase`, and H2.

----
See also: https://github.com/jOOQ/jOOQ/issues/9323

**Comment by lukaseder** [comment]
We won't work around this for H2. This will be fixed implicitly when the `DDLDatabase` uses our interpreter, instead of H2 behind the scenes.

**Comment by frevib** [comment]
Use `VARCHAR` instead of `TEXT`. They are the same in Postgresql, and `DDLDatabase` understands it. https://stackoverflow.com/a/4849030/3952065
