### ISSUE TITLE
DDLDatabase does not support JSON or JSONB columns

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9337]
When using PostgreSQL's `JSON[B]` data types:

```sql
create table t (t json);
```

The `DDLDatabase` fails because H2, behind the scenes, does not support this data type (yet). The error being produced is this:

```
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.12.1:generate (default-cli) on project jooq-mcve: Error running jOOQ code generation tool: Error while exporting schema: SQL [create table t(t json null)]; Unbekannter Datentyp: "JSON"
[ERROR] Unknown data type: "JSON"; SQL statement:
[ERROR] create table t(t json null) [50004-199]
```

With our new DDL interpretation (#8528), we won't have this problem anymore, but it might be possible to fix this already for the existing `DDLDatabase`.

**Comment by katzyn** [comment]
Hypothetically you can build H2 from its current sources (H2 has non-standard JSON data type), but all related functions and other operators aren't compatible between these databases.

I guess you can create domains with mappings to `VARCHAR` or `VARBINARY` for such data types.

**Comment by lukaseder** [comment]
Thanks a lot for that domain hint. That sounds like a promising hack. We won't need any operators in this case, as we're just using H2 to simulate DDL in-memory, so it might be sufficient if we can create a pseudo-json/jsonb type that will be reported back by the `information_schema`

**Comment by lukaseder** [comment]
This would work if we implement #3486 first (support for matching domains in the code generator's data type rewriting feature)

**Comment by katzyn** [comment]
Note that H2 has own [`JSON`](https://h2database.com/html/datatypes.html#json_type) data type now, but doesn't have a `JSONB` that can be mapped to `JSON` with domain.

**Comment by lukaseder** [comment]
Oh cool, that might be good enough.

**Comment by lukaseder** [comment]
Can confirm, the `JSON` data type works out of the box now with H2 and/or `DDLDatabase`, but not the `JSONB` data type yet. We should map it to `JSON` as well for now

**Comment by lukaseder** [comment]
H2 is currently being used behind the scenes by the `DDLDatabase`, which means we can only use the `JSON` data type in generated code right now, despite being able to recognise `JSONB`. If such generated code is being used on PostgreSQL, there might be unwanted side effects of getting the wrong (i.e. possibly less efficient) binding.

We can address that, if users find specific issues in this area.

**Comment by jdimeo** [comment]
@lukaseder your ability to predict the future is amazing :-) I'm using `DDLDatabase` and I'm hoping to get it to generate fields with type `JSONB`. The reason why is because I want to use Postgres' ability to merge JSON via the concat operator.

I found https://github.com/t9t/jooq-postgresql-json which defines a `JsonbDSL` class with the correctly typed `contact()` function. However, this:
```
sql.update(table)
   .set(payloadField, sql.select(JsonbDSL.concat(jsonbField, DSL.val(toMerge))))
   .where(...
```

Doesn't work because `jsonbField` is typed as `JSON`, not `JSONB`. Can I use `<forcedTypes>` to rewrite this somehow?

**Comment by lukaseder** [comment]
Well, the `DDLDatabase` is *never* going to implement all the vendor specific stuff. It's likely good enough for 80% of all use-cases, but power users will always run into limitations. Yes, you can use `<forcedTypes>` to replace `JSON` by `JSONB`, or, just switch to using a testcontainers based approach to code generation?
https://blog.jooq.org/using-testcontainers-to-generate-jooq-code/

**Comment by lukaseder** [comment]
> I'm struggling to get `<forcedTypes>` working though so if you have time for a hint I would appreciate it but I'll keep plugging away on my own.

Here's a hint: https://www.jooq.org/doc/latest/manual/code-generation/data-type-rewrites/

I'm not sure what you're struggling with, but I'm guessing you're not using forced types as data type rewrites?

**Comment by jdimeo** [comment]
Ha- I had it backwards. Was easier than I was trying to do :-)
```
<forcedTypes>
	<forcedType>
		<name>JSONB</name>
		<includeTypes>JSON</includeTypes>
	</forcedType>
</forcedTypes>
```

With the above config, this works (deep JSON upsert) for Postgres and `DDLDatabase`! sweet!
```
sql.update(table)
   .set(payloadField, sql.select(
		JsonbDSL.concat(payloadField, DSL.val(payloadField.get(row)))
	).from(table).asField())
   .where(idField.eq(idField.get(row)))
   .execute();
```

**Comment by lukaseder** [comment]
Great to see this works!
