### ISSUE TITLE
<outputSchemaDefault></outputSchemaDefault> not compatible with jooq version 3.12

### ISSUE THREAD

**Issue by shreyabaid007** [jOOQ/jOOQ#9341]
### Versions:

- jOOQ:
- Java:
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by knutwannheden** [comment]
Thanks for your report. Would you be able to add a little bit more details? I am assuming you are having  problems with `<outputSchemaToDefault>true</outputSchemaToDefault>` and in #3018 you mention:

> ... jooq codegen is unable to convert enums

Would you be able to expand a little bit on that to help us reproduce the problem?

**Comment by lukaseder** [comment]
Closing this as "works for me". The issue description does not explain what problem we're seeing here.
