### ISSUE TITLE
Remove PackageImpl from OSS edition

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9342]
Since support for packages is currently limited to Oracle, it would probably make sense to exclude the `PackageImpl` class from the OSS edition for the time being.

Possibly even the `Package` interface type could be excluded from the OSS edition. Although that would require some minor changes to `UDTImpl` (possibly also in a few other places, although I couldn't find any).

**Comment by lukaseder** [comment]
I'd rather not, as I will soon look into MariaDB's package support. See: https://github.com/jOOQ/jOOQ/issues/8273

The regression risk is significant, the value not too much.
