### ISSUE TITLE
Only render CREATE SEQUENCE ... NO CYCLE clause where supported

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9352]
Some of the dialects enumerated in the `@Support` annotation on `CreateSequenceFlagsStep#noCycle()` are only included because that corresponds to the implementation of sequences in that dialect. The statement may not actually support that clause. One such example is Firebird.

Thus, for dialects like Firebird, the implementation must not render the `NO CYCLE` clause.

**Comment by lukaseder** [comment]
Yes, interesting. This is implemented for `NO CACHE` (see `CreateSequenceImpl.OMIT_NO_CACHE` and/or `CreateSequenceImpl.NO_SUPPORT_CACHE`)

Other flags that should be fixed include:

- `NO MINVALUE`
- `NO MAXVALUE`

**Comment by lukaseder** [comment]
I have implemented this via https://github.com/jOOQ/jOOQ/issues/9410

**Comment by lukaseder** [comment]
... Some dialects might still be missing in the relevant flags. We'll add them as we discover them.
