### ISSUE TITLE
Order of fields returned from Row#fields()

### ISSUE THREAD

**Issue by sebastian-raubach** [jOOQ/jOOQ#9363]
### Your question:
I've got a number of views that I'm using to get the data into the format I need. One of my methods needs to write the result from a SELECT on those views into a text file.
I'm using the `fields()` method of `Row` and even `AbstractTable` to get the fields and that works fine, but the order is not the same as the order of fields defined in the view.

If it helps, I'm selecting like this without explicitly specifying the columns:

```
context.select().from(table)...
```

My question is, how do I get them in the order that they're defined in?

### Versions:

- jOOQ: 3.11.10
- Java: 1.8.0_121
- Database (include vendor): Oracle MySQL Community Edition 5.7.17
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): MySQL Connector 8.0.16

**Comment by lukaseder** [comment]
> but the order is not the same as the order of fields defined in the view.

That doesn't sound like anything we're doing explicitly. Can you provide an example with a bit more details that shows how you get the wrong column order from any of our methods? Perhaps and MCVE could help here: https://github.com/jOOQ/jOOQ-mcve

jOOQ always produces the columns in the definition order...

**Comment by sebastian-raubach** [comment]
Ok, I looked into it some more and while trying to create the MCVE, I realized that something during the code generation must have happened to cause the wrong order of fields. Rerunning the codegen in my project put them back in the correct order.
I've tried this about a dozen times now and I cannot get it to generate the code in the wrong order again, so I really don't know how this happened.

**Comment by sebastian-raubach** [comment]
Looking back through the Git history shows that every now and then fields do change position in the resulting files...

**Comment by lukaseder** [comment]
Interesting - we do order the columns by their `ORDINAL_POSITION` in the code generator, when fetching them from `INFORMATION_SCHEMA.COLUMNS`, so I think it's not us... Perhaps, different people in the team use different database setups, where the columns have been added to the tables in a different order by different migration paths? Maybe, you can track the relevant commits to individual developers and/or environments?

For the record, there's a workaround in the code generator - you can override the column order explicitly by using the `database/orderProvider` element:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-database/codegen-database-order-provider. I'm not convinced this will be helpful in your case, but maybe someone will find this issue in the future and may find this helpful.

**Comment by sebastian-raubach** [comment]
Thanks, I'll look into it. Feel free to close this. If I do find more information, I'll be back.
