### ISSUE TITLE
Add DDLFlag.INDEX to allow for exporting CREATE INDEX statements

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9364]
Currently, index definitions are not being exported from `DSLContext.ddl()`. This is an important feature for the DDL interpretation (#8528), but also in general

**Comment by lukaseder** [comment]
While researching for this post:
https://blog.jooq.org/2019/10/16/how-to-simulate-a-liquibase-migration-using-h2/

I've noticed this beauty here:

```sql
create unique index "PUBLIC"."PRIMARY_KEY_D" on "MY_SCHEMA"."DATABASECHANGELOGLOCK"("ID" asc)
where ()
```

We obviously shouldn't produce this empty `where` clause for non-partial indexes.

**Comment by knutwannheden** [comment]
Interesting is also the fact that the index is in the `PUBLIC` schema whereas the table is in `MY_SCHEMA`.

**Comment by lukaseder** [comment]
Hmm, nope. #9386 doesn't fix it. It's a different problem: https://github.com/jOOQ/jOOQ/issues/9391

**Comment by lukaseder** [comment]
... of course, the index shouldn't be exported in the first place, because it is generated by H2 from the primary key. We had already discussed that recently. The actual bug is in Meta. Will check back on that tomorrow.

**Comment by lukaseder** [comment]
These Liquibase experiments do help discover quite a few subtle bugs! :-)
