### ISSUE TITLE
"No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse"

### ISSUE THREAD

**Issue by ghost** [jOOQ/jOOQ#9366]
### Your question:
每次批量更新的时候，会报错"No bind variables have been provided with a single statement batch execution. This may be due to accidental API misuse"，绑定了值就不报错了，但是另一个服务同样的用法在没绑定值的情况下就不报这个错，就单纯的这个服务会报这个错
### Versions:

- jOOQ:3.9.6
- Java:1.8
- Database (include vendor):mysql 5.7
- OS:生产本地都是这样的
- JDBC Driver (include name if inofficial driver):com.mysql.jdbc.Driver

**Comment by lukaseder** [comment]
Thank you very much for your message.

Unfortunately, we do not have any Chinese speakers on the team. Would you mind asking your question in English?
