### ISSUE TITLE
Outdated comment in manual about H2 supporting window functions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9368]
See @katzyn's comment here https://github.com/jOOQ/jOOQ/issues/9361#issuecomment-541750425

This section is no longer true:

![image](https://user-images.githubusercontent.com/734593/66806638-55e03c80-ef28-11e9-88bf-d5343899d824.png)

**Comment by katzyn** [comment]
https://www.jooq.org/doc/latest/manual/sql-building/column-expressions/window-functions/
> jOOQ knows of implementations in DB2, Oracle, Postgres, SQL Server, and Sybase SQL Anywhere

I think that list isn't complete, I'm not sure, but I guess you also support window functions in MySQL, SQLite, H2, and possibly some others.

**Comment by lukaseder** [comment]
You're right. I'll just delete the paragraph

**Comment by lukaseder** [comment]
Even the HSQLDB bit isn't worth mentioning in the first paragraph of this chapter.
