### ISSUE TITLE
H2: DSL#currentTime() should render as CURRENT_TIME

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9371]
The SQL rendered for `DSL#currentTime()` should be `CURRENT_TIME` and not `CURRENT_TIME()`.

**Comment by katzyn** [comment]
@knutwannheden
`CURRENT_DATE` is also rendered incorrectly. H2 accepts incorrect variant with parentheses to, but there is no reason to generate such SQL.

**Comment by knutwannheden** [comment]
Thanks. Somehow I missed that.
