### ISSUE TITLE
Support various H2 ALTER .. IF EXISTS statements

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9374]
More recent versions of H2 support a variety of `ALTER .. IF EXISTS` statements, which we currently do not formally support. These include:

- [x] `ALTER SEQUENCE IF EXISTS`
- [x] `ALTER VIEW IF EXISTS`

----
See also comment here: https://github.com/jOOQ/jOOQ/issues/5087#issuecomment-542012828

**Comment by katzyn** [comment]
I don't see a change for `alterSequenceIfExists()` methods.

**Comment by lukaseder** [comment]
Thanks ;-)
