### ISSUE TITLE
Oracle: Emulate IF [ NOT ] EXISTS using SQLCODE instead of SQLERRM

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9378]
Would it be cleaner to emulate the `IF [ NOT ] EXISTS` DDL clauses using `SQLCODE` instead of `SQLERRM`? E.g.

```pgsql
BEGIN
  EXECUTE IMMEDIATE '
    DROP SEQUENCE s
  ';
EXCEPTION
  WHEN others THEN
    IF SQLCODE = -02289 THEN NULL;
    ELSE RAISE;
    END IF;
END;
```

instead of:

```pgsql
BEGIN
  EXECUTE IMMEDIATE '
    DROP SEQUENCE s
  ';
EXCEPTION
  WHEN others THEN
    IF sqlerrm LIKE 'ORA-02289%' THEN NULL;
    ELSE RAISE;
    END IF;
END;
```

**Comment by lukaseder** [comment]
I vaguely remember having run into issues with `SQLCODE` in the past, e.g. it not being always available. Could that be?

**Comment by knutwannheden** [comment]
Possibly. And I suppose there could be a problem with conflicting codes from different "applications". E.g. `PLS` and `ORA` codes.

**Comment by lukaseder** [comment]
Ah yes, perhaps that was part of it.

**Comment by knutwannheden** [comment]
Well, at least we have it documented now.
