### ISSUE TITLE
Code generation DDLDatabase fails to parse Flyway table definition

### ISSUE THREAD

**Issue by voorth** [jOOQ/jOOQ#9397]
```
create table outlet
(
    id integer not null
        constraint outlet_pk
            primary key,
    last_name varchar,
    location varchar,
    outlet_name varchar,
    outlet_type varchar
);

alter table outlet owner to postgres;
```
fails with:
```
org.jooq.impl.ParserException: Token ')' expected: [4:9] ...te table outlet
(
     id integer not null
         [*]constraint outlet_pk
             primary key,
     last_name varchar,
     locatio...
```

**Comment by lukaseder** [comment]
Thanks a lot for your report. Indeed, we currently do not support this syntax, but we should. The workaround is to use the following syntax instead:

```sql
create table outlet
(
    id integer not null,
    last_name varchar,
    location varchar,
    outlet_name varchar,
    outlet_type varchar,
    constraint outlet_pk primary key (id)
);
```

**Comment by lukaseder** [comment]
Checking again, we actually do support the syntax. What jOOQ version are you using?

**Comment by lukaseder** [comment]
See documentation here:

- jOOQ 3.12 supporting this syntax: https://www.jooq.org/doc/3.12/manual/sql-building/sql-parser/sql-parser-grammar/#column
- jOOQ 3.11 not supporting this syntax: https://www.jooq.org/doc/3.11/manual/sql-building/sql-parser/sql-parser-grammar/#column

**Comment by lukaseder** [comment]
Duplicate of #8386

**Comment by voorth** [comment]
Well, on 3.12.1 I'm still getting  a ')' expected error. Your workaround works well, though...

**Comment by lukaseder** [comment]
Are you sure you're using 3.12.1? Perhaps you have an older version on your classpath, possibly because of some transitive dependency (e.g. Spring Boot, or the third party gradle plugin)

**Comment by voorth** [comment]
Hmm, could be... is a bit difficult to find out though...

**Comment by voorth** [comment]
yeah, you're right. Spring boot is still using 3.11.9

**Comment by lukaseder** [comment]
So, if you're using Maven, this would be one option to fix this problem: https://blog.jooq.org/2019/06/26/how-to-use-jooqs-commercial-distributions-with-spring-boot/
