### ISSUE TITLE
forcedType's includeTypes not work for tinyint on mysql

### ISSUE THREAD

**Issue by alex-lx** [jOOQ/jOOQ#9405]
### Expected behavior and actual behavior:
By default, `jOOQ` generates `byte` for `tinyint`, however, our team prefer `int` to avoid type casting in java, so we configure the `forcedType`. It's expected to generate `int` for `tinyint` field, but actual still byte.
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
I'd like to create a MCVE, but it can't reproduce in H2 database, so I'll just describe it.
config:
```groovy
        forcedTypes {
            forcedType {
                name = 'integer'
                includeExpression = '.*'
                includeTypes = 'tinyint'
            }
        }
```
NOTE: if we change includeTypes from `tinyint` to `tinyint.*` or `tinyint\\(4\\)`, it works.
NOTE2: it works with jOOQ 3.11.11 after modifying the config property to the old type.
```groovy
        forcedTypes {
            forcedType {
                name = 'integer'
                expression = '.*'
                types = 'tinyint'
            }
        }
```

I'm not sure it's a bug or a new feature if this behaviour is expected for you, feel free to close this issue.

### Versions:

- jOOQ: 3.12.1
- Java: 1.8
- Database (include vendor): Tidb(mysql compatible)
- OS: mac os x
- JDBC Driver (include name if inofficial driver): mysql

**Comment by lukaseder** [comment]
This works as designed. Closing.
