### ISSUE TITLE
SQL Translation Error

### ISSUE THREAD

**Issue by nampn** [jOOQ/jOOQ#9417]
### SQL translator incorrectly translates this query:

```sql
if (new.sl is null) then
        new.sl=0

**Comment by lukaseder** [comment]
Thank you very much for your report.

We're going to be looking into supporting `TRIGGER` DDL statements in the near future, but we currently don't support their syntax yet. See: https://github.com/jOOQ/jOOQ/issues/6956

I will keep this issue open to verify your syntax will be parsed correctly, once we support triggers.
