### ISSUE TITLE
Add code generation support for sequence flags

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9442]
Now that we can represent the various sequence flags in our meta model (https://github.com/jOOQ/jOOQ/issues/7752), we should also support them via code generation.

Supported so far in:

- [x] CockroachDB
- [x] DB2
- [x] Derby
- [x] Firebird
- [x] H2
- [x] Hana
- [x] HSQLDB
- [x] Informix
- [x] Ingres
- [x] MariaDB
- [x] Oracle
- [x] PostgreSQL
- [x] SQL Server
- [x] Sybase SQL Anywhere
- [x] Vertica

Also in:

- [x] DDLDatabase
- [x] XMLDatabase (requires https://github.com/jOOQ/jOOQ/issues/9603 first)

**Comment by knutwannheden** [comment]
For MariaDB the code generator needs to run a `SELECT` query against the table with the name of the sequence to query the sequence flags. I suppose we could do a single big `UNION ALL` query or use batching, but I doubt it is worth the extra effort.

**Comment by lukaseder** [comment]
> but I doubt it is worth the extra effort.

Not sure, until I see the SQL...

**Comment by katzyn** [comment]
@knutwannheden
9c1ea8ab227f2b27e0adc6e3497f31bb548a2e92
> H2 only supports the `START WITH` clause in `CREATE SEQUENCE` (not in
`ALTER SEQUENCE`) and thus only controls the first value ever returned
by the sequence.

https://h2database.com/html/grammar.html#sequence_options
> `START WITH` and `RESTART WITH` are used to set the first generated value of the sequence. `START WITH` may only be used in `CREATE SEQUENCE` command and in column definition, `RESTART WITH` may only be used in `ALTER SEQUENCE` command.

The SQL Standard also defines `START WITH` for `<sequence generator definition>` and `RESTART WITH` for `<alter sequence generator statement>`.

The old code also looks suspicious, in H2 the default start value is determined in the following way:
> The default is `MINVALUE` for incrementing sequences and `MAXVALUE` for decrementing sequences.

**Comment by knutwannheden** [comment]
@katzyn Thanks for your input. The `ALTER SEQUENCE ... START WITH` appears to be a somewhat strange PostgreSQL-specific feature. But I noticed that H2 doesn't support the T177 feature ("Sequence generator support: simple restart option"), which I suppose to some extent explains why the initially specified `START WITH` value isn't accessible from the information schema.

**Comment by katzyn** [comment]
H2 does not preserve `START WITH` value, it is only used to set a current value of a sequence.

`RESTART WITH` is supported.

Simple `RESTART` will be supported by H2 1.4.201, but with current sources it uses the `MINVALUE` / `MAXVALUE` semantics. I'm not sure what the following definition from the SQL Standard means:

>  Otherwise (`<alter sequence generator restart option>` is specified but does not contain a `<sequence generator restart value>`), let `NEWVAL` be the start value of `SEQ`.

The “start value” really means the `START` value from “Creation of a sequence generator” definitions or not?

**Comment by katzyn** [comment]
Also thank you for explanation, I didn't know that PostgreSQL has both `START WITH` and `RESTART` in `ALTER SEQUENCE` command with different meaning.

But if `RESTART` should really use the original `START WITH` value, such additional clause is reasonable.

**Comment by katzyn** [comment]
I found the answer.

> c) The start value, set to START.
…
h) The current base value, set to START.

So the original start value must be preserved and current implementation of simple `RESTART` in H2 is not correct.

**Comment by knutwannheden** [comment]
AFAIK `ALTER SEQUENCE ... RESTART` will use the value supplied by the last `ALTER SEQUENCE ... START WITH` command or `CREATE SEQUENCE ... START WITH`, if none.

**Comment by lukaseder** [comment]
Follow up task to add a new `<sequenceFlags/>` flag to turn off this feature: https://github.com/jOOQ/jOOQ/issues/9629

**Comment by knutwannheden** [comment]
SQL Server's official documentation doesn't document the `INFORMATION_SCHEMA.SEQUENCES` view. Reported here: https://github.com/MicrosoftDocs/sql-docs/issues/3783.
