### ISSUE TITLE
DSLContext.fetchCount return int , why not long

### ISSUE THREAD

**Issue by lichangshu** [jOOQ/jOOQ#9450]
when is use the api : `DSLContext.fetchCount(Select<?> query);` ,the return is `int` why not `long`?

I use mysql,Some tables have more than 10^32 rows of data, Is there any way to deal with this situation?

thank you

**Comment by lukaseder** [comment]
Thanks for your message. We made the same mistake as JDBC did, originally, by using `int` wherever we're counting row counts. `fetchCount()` returns the same type as `DSL.count()`. It would be better to return `long`, but we cannot change this API incompatibly, see also: https://github.com/jOOQ/jOOQ/issues/3714

It's easy to roll your own, though. You can, for example, create a plain SQL function like this:

```java
static Field<Long> bigCount() {
  return DSL.field("count(*)", SQLDataType.BIGINT);
}
```

... and use that in your queries.
