### ISSUE TITLE
Support additional Settings.interpreterDialects and add an InterpreterConnectionProvider SPI

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9460]
We've introduced a new `Settings.interpreterDialect` flag (https://github.com/jOOQ/jOOQ/issues/9362), which can be used to specify how we're interpreting DDL statements. Currently supported options are:

- `H2` (what was available prior to 3.13)
- `DEFAULT` (our new DDL interpretation)

We also want to support:

- [x] Other in-memory database dialects, such as Derby, HSQLDB, SQLite, which can be made available simply by having the relevant JDBC driver on the classpath
  - [x] `DERBY`
  - [x] `HSQLDB`
  - [x] `SQLITE`
- [x] All other dialects, by either looking for test containers on the classpath, or using some new `InterpreterConnectionProvider` JDBC connection that users can provide through an SPI

**Comment by lukaseder** [comment]
First implementation draft only uses `DefaultConfiguration.setInterpreterConnectionProvider()` and does not yet expose this setter in the `Configuration` API. This is workable and allows for postponing the naming discussion.

**Comment by knutwannheden** [comment]
Yes, very unfortunate. I suppose you already dismissed the idea of having a nested `InterpreterConfiguration`?

**Comment by knutwannheden** [comment]
No, it would be owned by the `Configuration` object and only contain interpreter-related configuration. But that doesn't fit in with the current API.

**Comment by lukaseder** [comment]
Oh, I see. That's indeed an option I wouldn't dismiss right away, although it seems to be more difficult to design correctly (at least in the short term) than the alternatives I'm hoping for.

**Comment by lukaseder** [comment]
I think your suggestion might not be the best for the current `Configuration` design, but it might be a good option in the future, when we want to re-design `Settings` as well, see: https://github.com/jOOQ/jOOQ/issues/9167

When we re-design `Settings`, we might as well re-design `Configuration`

**Comment by lukaseder** [comment]
It's now possible to interpret DDL using the in-memory mode of any of:

- Derby
- H2
- HSQLDB
- SQLite

**Comment by lukaseder** [comment]
We're now ready to tackle https://github.com/jOOQ/jOOQ/issues/6551
