### ISSUE TITLE
Make CreateSequenceFlagStep<T extends Number> generic

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9465]
Consistent with `AlterSequenceStep<T>`, inferring the `<T>` type from the `DSL.createSequence(Sequence<T>)` method

**Comment by knutwannheden** [comment]
One problem with this is that a Java expression like the following won't compile anymore:

```java
ctx.createSequence("s").startWith(2)
```

since `2` is not a `BigInteger`.

So the methods like `CreateSequenceFlagsStep#startWith(T)` should probably stay as `CreateSequenceFlagsStep#startWith(Number)`. And then probably also the `Field<T>` overloads. But then nothing would be using the generic type parameter anymore...

**Comment by lukaseder** [comment]
Yes, perhaps that's already wrong on `DSLContext.alterSequence(String)` as well, which should probably return `AlterSequenceStep<Number>` and not `AlterSequenceStep<BigInteger>`

**Comment by knutwannheden** [comment]
I will look into what other changes this requires. At least the `DSL#sequence(String)` and `DSL#sequence(Name)` methods must also be changed to return something other than `Sequence<BigInteger>`.

**Comment by lukaseder** [comment]
Hmm, yes. Too bad. I'm not sure about what should be done here.

**Comment by knutwannheden** [comment]
Also `DSLContext#currval(Name)` and `DSLContext#nextval(Name)` currently return `BigInteger` and would require changing to `<T extends Number>`.

**Comment by knutwannheden** [comment]
> Also `DSLContext#currval(Name)` and `DSLContext#nextval(Name)` currently return `BigInteger` and would require changing to `<T extends Number>`.

No, of course these could be kept the same by changing the implementation in `DefaultDSLContext`.

**Comment by lukaseder** [comment]
Hmm, I think that producing `Sequence<Number>` instead of `Sequence<BigInteger>` is incorrect as there will be some way generic variance will bite us here. A correct type is `Sequence<? extends Number>` or `Sequence<?>` (since the type is already bounded in the `Sequence` declaration), but that makes the DDL APIs unusable.

A better choice would have been to use `Long` instead of `BigInteger`, as there is at least a way to use primitive types with `Long`, for convenience. Maybe, we should fix this in a larger context in the next major release 4.0, when we fix other non optimal numeric types in the API, such as `count()` producing a `Field<Integer>` instead of `Field<Long>`...

**Comment by lukaseder** [comment]
In this light, perhaps we should refrain from making `AlterSequence` types generic, for consistency, and then fix both in jOOQ 4.0

**Comment by knutwannheden** [comment]
The only other option I see is using a generic type parameter on all methods in `DSL` and `DSLContext` and thus have methods like `<T extends Number> AlterSequenceStep<T> alterSequence(String)`. That would probably work, but would in our code require a raw cast from `Sequence<BigInteger>` to `Sequence`.

**Comment by lukaseder** [comment]
No, we don't do that:

1) Type inference gets hairy with these methods
2) We never lie about types. What if the user writes code where `T` is inferred to be `Integer`, but we still deliver a `BigInteger`?

**Comment by knutwannheden** [comment]
> 2\. We never lie about types. What if the user writes code where `T` is inferred to be `Integer`, but we still deliver a `BigInteger`?

Not sure what would happen, really. But since the generic type is kind of a lie anyway (ultimately it will be defined by the sequence's `MAXVALUE` or the upper bound given by the database (e.g. `2^63` in H2 and `10^38` in Oracle)), I initially also thought it might be best to not have these types as generic at all.

**Comment by lukaseder** [comment]
> Not sure what would happen, really

There's some risk as we might evolve this API. The risk is slim in this case, indeed, but I think this is very poor practice.

> But since the generic type is kind of a lie anyway (ultimately it will be defined by the sequence's MAXVALUE or the upper bound given by the database (e.g. 2^63 in H2 and 10^38 in Oracle))

That's not the same thing. A server side runtime exception is acceptable. A client side `ClassCastException` is not.

> I initially also thought it might be best to not have these types as generic at all.

Yes, given the flaws you have discovered in `DSL.sequence()`, I agree.

**Comment by knutwannheden** [comment]
As discussed above, we will leave `CreateSequenceFlagStep` as a type without generic type parameter.
