### ISSUE TITLE
AlterSequenceStep#restart() should consider Sequence#getStartWith()

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9466]
The `ALTER SEQUENCE ... RESTART` clause (see `AlterSequenceStep#restart()`) is currently being emulated for some commercial editions, by translating it to a `ALTER SEQUENCE ... RESTART WITH 1`. This is however not correct if the sequence was created with a `START WITH` clause with a value different from `1`.

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/9438
