### ISSUE TITLE
Add support for UUID generator functions, such as NEWID() or GEN_RANDOM_UUID()

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9472]
The parser supports SQL Server's `UNIQUEIDENTIFIER` type, but not the `NEWID()` and `NEWSEQUENTIALID()` functions of this type, which commonly get referenced as `DEFAULT` value in DDL.

Emulations include:

- [x] PostgreSQL 13: `GEN_RANDOM_UUID()`
- [x] SQL Server: `NEWID()`

**Comment by lukaseder** [comment]
A complete list of planned emulations:

- [ ] Access: `GenGUID()`
- [ ] BigQuery: `GENERATE_UUID()`
- [ ] CockroachDB: `GEN_RANDOM_UUID()`
- [ ] Db2: `GENERATE_UNIQUE()` (generates a `CHAR(13) FOR BIT DATA` string)
- [ ] Firebird: `UUID_TO_CHAR(GEN_UUID())`
- [ ] HANA: `SYSUUID`
- [ ] H2: `RANDOM_UUID()`
- [ ] HSQLDB: `UUID()`
- [ ] Ignite: `RANDOM_UUID()` or `UUID()`
- [ ] MariaDB: `UUID()`
- [ ] MySQL: `UUID()`
- [ ] Oracle: `SYS_GUID()`
- [ ] PostgreSQL 13: `GEN_RANDOM_UUID()`
- [ ] Snowflake: `UUID_STRING()`
- [ ] SQL Server: `NEWID()`
- [ ] SQLite: https://stackoverflow.com/a/22725697/521799 (😁)
- [ ] Sybase ASE: `NEWID(-1)`
- [ ] Vertica: `UUID_GENERATE()`

**Comment by lukaseder** [comment]
There isn't really any pattern to the naming of these functions, so let's just keep it simple and call it `DSL.uuid()`. There is no value to the words "new" or "sys" or "generate" or "random".

**Comment by lukaseder** [comment]
For emulations, it would be useful to have a `HEX()` function available: https://github.com/jOOQ/jOOQ/issues/11656

**Comment by lukaseder** [comment]
Some SQL dialects encourage storing UUID values as `BINARY(16)` or similar, such as Oracle's `SYS_GUID()`. We could offer native support for binary UUID types: https://github.com/jOOQ/jOOQ/issues/11807. Currently, our `UUID` type is always in the human readable `CHAR(36)` format.
