### ISSUE TITLE
Support parsing number literals with exponent

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9475]
The parser currently doesn't recognize number literals with an exponent, like `1e1`. This can lead to very subtle errors. For example the parser interprets `SELECT 1E1` as `SELECT 1 E1`; i.e. `E1` is taken as the alias.

**Comment by lukaseder** [comment]
I would say these are two bugs. Yes, we should support IEEE 754 floats, but even before that, we should definitely not think of `1E1` as an aliased column.

**Comment by lukaseder** [comment]
Will be implemented in the context of https://github.com/jOOQ/jOOQ/issues/11711

**Comment by lukaseder** [comment]
Fixed with https://github.com/jOOQ/jOOQ/commit/9923e22bb598a37042ff46a044b940914d8513e9
