### ISSUE TITLE
Add parser support for MySQL [ INNER ] JOIN without ON clause

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9476]
MySQL (and possibly also MySQL derivatives) support `[ INNER ] JOIN` without `ON` clause, in which case it is the same as `CROSS JOIN` and the comma operator. The parser currently doesn't support this.

Here some relevant extracts from the [documentation](https://dev.mysql.com/doc/refman/8.0/en/join.html):

> In MySQL, JOIN, CROSS JOIN, and INNER JOIN are syntactic equivalents (they can replace each other). In standard SQL, they are not equivalent. INNER JOIN is used with an ON clause, CROSS JOIN is used otherwise.

> INNER JOIN and , (comma) are semantically equivalent in the absence of a join condition: both produce a Cartesian product between the specified tables (that is, each and every row in the first table is joined to each and every row in the second table).

> However, the precedence of the comma operator is less than that of INNER JOIN, CROSS JOIN, LEFT JOIN, and so on. If you mix comma joins with the other join types when there is a join condition, an error of the form Unknown column 'col_name' in 'on clause' may occur. Information about dealing with this problem is given later in this section.

**Comment by lukaseder** [comment]
We support parsing `CROSS JOIN .. ON`, without API support: https://github.com/jOOQ/jOOQ/issues/5875

**Comment by lukaseder** [comment]
If this doesn't lead to weird ambiguities in the parser, I don't see why we shouldn't support this (translating it to `CROSS JOIN`)
