### ISSUE TITLE
Mysql `substring_index` function support

### ISSUE THREAD

**Issue by mataoqun** [jOOQ/jOOQ#9484]
### Your question:
How to use the substring_index function with jooq？
### Versions:

- jOOQ: 3.9.6
- Java: 1.8
- Database (include vendor): Mysql
- OS: winAll
- JDBC Driver (include name if inofficial driver): inofficial driver

**Comment by lukaseder** [comment]
Whenever you're missing support for some vendor specific function, please use plain SQL templating:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating/

E.g.

```java
DSL.field("substring_index({0}, {1}, {2})", String.class, arg1, arg2, arg3);
```

I hope this helps

**Comment by lukaseder** [comment]
See also: https://github.com/jOOQ/jOOQ/issues/7832

**Comment by mataoqun** [comment]
Thank you for your reply, I know how to do it.
