### ISSUE TITLE
For table with two timestamp fields with and without time zone, `Table.field(<name>, Class)` returns Coerce field with incorrect DataType

### ISSUE THREAD

**Issue by vryzhuk** [jOOQ/jOOQ#9485]
### Expected behavior and actual behavior:
**Generic issue**: for table, in which there are two fields with `Converters` that have same `toType` class, call `table.field(secondFieldName, Class)` returns field with incorrect `DataType`, which provides wrong cast in statements.

Our specific case: we have table with **2 timestamp fields: with and without time zone**. We create them with different converters, which returns same `toType` = `Instant.class`.  We discovered, that **statements have wrong cast for the second field** (which was created second) and it casts to the first field data type. This problem does not exist by using actual fields, and only exist if `coerce` is executed, which is the case for `Table.field(secondFieldName, Class)`.

**Expected behavior**: returning actual field will solve this problem, but `Field.coerce` will still incorrectly returns dataType for such cases.

**Workaround**: use `(Class)Table.field(secondFieldName)` instead (it does not use `coerce`)

**Investigation**:  `Table.createField` method creates `ConvertedDataType`, which trigger super `DefaultDataType` constructor and puts to `SQL_DATATYPES_BY_TYPE` an entry (`Instant.class` : `Timestamp`) for the first field (https://github.com/jOOQ/jOOQ/blob/3560efe0d49f925ac72c14627c1eae8930a19bae/jOOQ/src/main/java/org/jooq/impl/DefaultDataType.java#L331). For the second field, it will use `DataType` value in this map by key `Instant.class`, which is wrong. So it looks like `DefaultDataType` do not support mapping of the same type to several data types and `ConvertedDataType` do not override this behavior.

### Steps to reproduce the problem:
```java
import org.jooq.Converter;
import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.junit.Test;

import java.sql.Timestamp;
import java.time.Instant;
import java.time.OffsetDateTime;

import static org.junit.Assert.assertEquals;

public class TableFieldTest {

    @Test
    public void test() {
        var table = new SampleTable("TEST_TABLE");
        var withoutTimezone = table.field("without_timezone", Instant.class);
        assertEquals("Without time zone like actual field", "timestamp", withoutTimezone.getDataType().getCastTypeName()); // not failing as it was instantiated the first
        var withTimezone = table.field("with_timezone", Instant.class);
        assertEquals("With time zone like actual field", "timestamp with time zone", withTimezone.getDataType().getCastTypeName()); // fails
    }

    static class SampleTable extends TableImpl<Record> {
        SampleTable(String name) { super(name);}

        final TableField withoutTimezone = createField("without_timezone", SQLDataType.TIMESTAMP.nullable(false), this, "", new InstantConverter());

        final TableField withTimezone = createField("with_timezone", SQLDataType.TIMESTAMPWITHTIMEZONE.nullable(false), this, "", new OffsetDateTimeInstantConverter());
    }

    static class InstantConverter implements Converter<Timestamp, Instant> {
        @Override
        public Instant from(Timestamp timestamp) { return null;}
        @Override
        public Timestamp to(Instant instant) {return null;}
        @Override
        public Class<Timestamp> fromType() {return Timestamp.class;}
        @Override
        public Class<Instant> toType() { return Instant.class;}
    }

    static class OffsetDateTimeInstantConverter implements Converter<OffsetDateTime, Instant> {
        @Override
        public Instant from(OffsetDateTime offsetDateTime) { return null;}
        @Override
        public OffsetDateTime to(Instant instant) {return null;}
        @Override
        public Class<OffsetDateTime> fromType() {return OffsetDateTime.class;}
        @Override
        public Class<Instant> toType() {return Instant.class;}
    }
}

```
### Versions:

- jOOQ: 3.11.11
- Java: OpenJDK 11.0.4 
- Database (include vendor): not needed to reproduce the issue
- OS: Mac
- JDBC Driver (include name if inofficial driver): not needed to reproduce the issue

**Comment by lukaseder** [comment]
Thank you very much for your report. Since jOOQ 3.12.0, jOOQ has a `SQLDataType.INSTANT`, which is the type you're getting when you coerce a `Field` to `Instant.class`. The fact that you have a converter somewhere, which links any data type to `INSTANT` explicitly does not matter here.

There is a historic undocumented "feature" where such type lookups may produce your own converted data types because of an internal, static data type registry in `DefaultDataType`. This is why your code may have worked as "expected" prior to jOOQ 3.12. What should happen instead is an exception should have been thrown because jOOQ, before 3.12, did not know what to do with your `Table.field(..., Instant.class)` call.

We should probably think about deprecating that undocumented "feature" by logging warnings prior to introducing new built in data types, such as `INSTANT`.

**Comment by lukaseder** [comment]
I have created an issue for this deprecation of looking up user-defined data types in the `DefaultDataType`'s static data type registry: https://github.com/jOOQ/jOOQ/issues/9492

**Comment by vryzhuk** [comment]
Hi @lukaseder . Thanks a lot for your reply! 
Are there any correct way of getting field from table by name and, maybe, class, which could have a `Converter`? All `Table.field(*)` methods do not say anything about such differentiation and from this perspective they should work for user defined converters and types too. 

I will try to use 3.12 version to check if it produce correct cast for fields with and without TZ. But I think, such test won't work either as it won't take into account different Converters.

Thanks
