### ISSUE TITLE
Use a single place to define the jOOQ version in all pom.xml files

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9487]
Perhaps, one solution is to use the `versions-maven-plugin` in the `jooq-parent` pom.xml file to define the jOOQ version for all of the module hierarchy:
https://www.mojohaus.org/versions-maven-plugin/

This could be a useful prerequisite for the creation of snapshot repositories: https://github.com/jOOQ/jOOQ/issues/9053

**Comment by knutwannheden** [comment]
What would be the advantage over doing a search/replace in all files?

Also, for snapshot releases I would have expected that the version remains at something like `3.13.0-SNAPSHOT`, which is what we already have in the `pom.xml` files. The zip archive would then probably include some timestamp in the file name.

**Comment by lukaseder** [comment]
> What would be the advantage over doing a search/replace in all files?

Every time I run such a search / replace, I'm terrified I might accidentally upgrade some third party dependency and introduce a regression.

> Also, for snapshot releases I would have expected that the version remains at something like 3.13.0-SNAPSHOT

**Comment by lukaseder** [comment]
> Also, for snapshot releases I would have expected that the version remains at something like 3.13.0-SNAPSHOT

I would like to append a timestamp after `SNAPSHOT`, so we can version the different builds. How else would early adopting customers be able to report an issue on a specific build?

**Comment by lukaseder** [comment]
> The zip archive would then probably include some timestamp in the file name.

Yes, but I'm positive, customers want to be *sure* to reference the right snapshot version in their local maven repositories when they keep trying things with newer versions, too. Not just have the timestamp in the ZIP file.

It is never a good idea to overwrite a version's content. Once published, a version ID should be immutable.

**Comment by knutwannheden** [comment]
The `versions-maven-plugin` has a few goals. The `set` goal can be used to update the Maven project version. It will however update the Maven `pom.xml` files "in-place".

Another alternative may be to define a `revision` property and reference that from the `<version>` element. See here: https://maven.apache.org/maven-ci-friendly.html. As a consequence the [flatten-maven-plugin](https://www.mojohaus.org/flatten-maven-plugin/) must be used to install / deploy the artifacts.

**Comment by lukaseder** [comment]
After our discussion, I'm not so convinced we should be patching the `pom.xml` files during the Maven build. I prefer doing these updates from outside the build, e.g. using shell scripts.

**Comment by knutwannheden** [comment]
In addition to the `versions:set` goal there are also goals like `versions:lock-snapshots` and `versions:unlock-snapshots`, which could all be of interest (see https://www.mojohaus.org/versions-maven-plugin/).

**Comment by lukaseder** [comment]
I haven't found a better solution yet. Can still live with the status quo.
