### ISSUE TITLE
JoinStep#crossApply() throws IllegalArgumentException

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9493]
In the OSS edition the `JoinStep#crossApply()` (i.e. SQL `CROSS APPLY`) feature throws an `IllegalArgumentException`. This only applies to PostgreSQL, as that is currently the only open source dialect supporting this feature. In the commercial editions this works properly.

Here is the code throwing the exception:

https://github.com/jOOQ/jOOQ/blob/a0b74c22032b679d9e268ed9b00ebec13aa00201/jOOQ/src/main/java/org/jooq/impl/SelectQueryImpl.java#L2681-L2693

**Comment by lukaseder** [comment]
Oh interesting, nice catch. Fix seems obvious: Uncomment those `CROSS_APPLY` and `OUTER_APPLY` cases.

**Comment by knutwannheden** [comment]
Yes. Should this fix be backported to 3.12?

**Comment by lukaseder** [comment]
Sure, why not

**Comment by knutwannheden** [comment]
Fixed in 3.13. Backport scheduled for 3.12.4: #9494.
