### ISSUE TITLE
DDLDatabase: Flyway's repatable migrations are executed to early

### ISSUE THREAD

**Issue by jbarop** [jOOQ/jOOQ#9498]
#### Expected:
When using `org.jooq.meta.extensions.ddl.DDLDatabase` with the property `sort=flyway` I expect that the SQL scripts are applied in the same order as Flyway would execute them.

From https://flywaydb.org/documentation/migrations#overview:

> Within a single migration run, repeatable migrations are always applied last, after all pending versioned migrations have been executed. Repeatable migrations are applied in the order of their description.

This is useful for view etc.

#### Actual:
The repeatable scripts are applied before the versioned ones.

### Steps to reproduce the problem:
https://github.com/jbarop/jOOQ-mcve-9498

Flyway successfully executes all migrations but the jOOQ code generation fails because the repeatable migration is applied first.

### Versions:

- jOOQ: 3.12.1
- Java: 1.8.0_161
- Database (include vendor): PostgreSQL 11.5
- OS: macOS 10.15
- JDBC Driver: org.postgresql:postgresql-42.2.5
- Flyway: 5.2.4

**Comment by lukaseder** [comment]
Thanks a lot for the report and MCVE. Agreed, we should mimick that behaviour. Will look into that right away.

**Comment by lukaseder** [comment]
This seems to fix it in unit tests, but not yet in integration tests.

**Comment by lukaseder** [comment]
Never mind, it works. Some other test was failing, because it picked up your two test files in alphabetic order...

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.13.0. Backport scheduled for 3.12.4 (#9556).

The fix was relatively simple. If you're interested in applying a patch to your version to verify if this thoroughly fixes the problem in your complete migration, then your feedback would be greatly appreciated!

Thanks again for reporting.

**Comment by jbarop** [comment]
Thanks. It worked like a charm.
