### ISSUE TITLE
Oracle: PIVOT ... FOR always rendered as quoted

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9513]
In a query using `PIVOT`, as for example:

```sql
select * from (
   select times_purchased, state_code
   from customers t
)
pivot 
(
   count(state_code)
   for state_code in ('NY','CT','NJ','FL','MO')
)
order by times_purchased
```

jOOQ always renders the `FOR` variable as quoted:

```sql
SELECT *
FROM (
  SELECT 
    times_purchased, 
    state_code
  FROM customers t
) alias_40187326
PIVOT (count(state_code)
  FOR "state_code"
  IN (
    'NY', 
    'CT', 
    'NJ', 
    'FL', 
    'MO'
  )
)
ORDER BY times_purchased
```

Thus if the original query gets parsed, rendered, and executed by jOOQ it will in fact result in a DB runtime error, since the case of the identifier in the `SELECT` clause doesn't match (`ORA-00904: "product_id": invalid identifier`).

**Comment by lukaseder** [comment]
Nice catch. That thing probably has a few additional bugs. I wonder if anyone has *ever* used it :)
