### ISSUE TITLE
LiquibaseDatabase should allow for passing parameters to the Liquibase

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9514]
In Liquibase, it is possible to ignore certain types of migration statements, such as insert statements. When generating jOOQ code, it makes perfect sense to avoid this step, so we should probably ignore DML by default, allowing users to enable DML optionally.

While we're at it, we should also integration test if we can run Liquibase's YAML and JSON formats.

----
See also:
https://www.reddit.com/r/java/comments/dpqal7/how_to_simulate_a_liquibase_migration_using_h2/f6lpv4z/

**Comment by lukaseder** [comment]
It appears that Liquibase supports reading environment variables and system properties in `ChangeLogParameters` as "external parameters". This can be used also out of the box with our `LiquibaseDatabase`

**Comment by Fadelis** [comment]
The `contexts` parameters is still not passed to the liquibase, as it it not a `database` parameter. It needs to be passed directly to the `database.update(String)` method.
Also the exclusion of the `changeLog` tables uses static table names, but those might be overridden by the configuration setters. 
I can submit a PR fix for this.

**Comment by lukaseder** [comment]
Thanks for your suggestions, @Fadelis. We can certainly improve things in this area. I'd prefer doing this under new issues, so we can properly announce the changes in the release notes. From your commits, I can see that you're already improving more than just the `contexts` parameters.

Would you mind creating individual issues with a short explanation about what this is for?

**Comment by Fadelis** [comment]
Yes, of course.

**Comment by lukaseder** [comment]
Thanks a lot!

For the reference, new issues here: https://github.com/jOOQ/jOOQ/issues/9872, https://github.com/jOOQ/jOOQ/issues/9873
