### ISSUE TITLE
Force type of postgres enum array in jOOQ codegen

### ISSUE THREAD

**Issue by napstr** [jOOQ/jOOQ#9523]
### Your question:

Ahoy, I've been trying to force the type of a postgres enum array when using jOOQ codegen.

Something like this migrations script:

```sql
CREATE TYPE ExampleEnum AS ENUM ('A', 'B', 'C');

CREATE TABLE example_table
(
    id    serial PRIMARY KEY,
    enum  ExampleEnum   NOT NULL,
    enums ExampleEnum[] NOT NULL
);
```

and then this config in gradle:
```groovy
forcedType {
	userType = 'org.example.db.type.ExampleEnum'
	enumConverter = true
	includeExpression = '.*'
	includeTypes = 'ExampleEnum'
}
```

That works successfully on the `enum` column and returns the user type `org.example.db.type.ExampleEnum`, but on the `enums` array colums, the generated `ExampleTableRecord` returns a `org.example.db.generated.enums.Exampleenum[]`.

What is the correct way to get jooq to generate the `ExampleTableRecord` so that it returns an array of the user type enum?

To reproduce this and play around, I have created an example project here: https://github.com/napstr/jooq-postgres-enum-array-forced-type

### Versions:

- jOOQ: 3.12.3
- Java: adoptopenjdk 11.0.5
- Database (include vendor): PostgreSQL 12
- OS: macOS 10.13.6
- JDBC Driver (include name if inofficial driver): 42.2.8
- Gradle: 5.6.4

**Comment by lukaseder** [comment]
Thank you very much for your message.

In PostgreSQL `ExampleEnum` and `ExampleEnum[]` are two distinct types. As such, your forced type doesn't match both of these. You have to create a new forced type for the array types. And with that, unfortunately, you have to make use of some "internal workings" knowledge, as PostgreSQL doesn't report the array type as `ExampleEnum[]`, but as `_ExampleEnum`, so you have to match that. You're going to have to write your own converter for that case.

There have been related feature requests and PRs in the past, e.g. https://github.com/jOOQ/jOOQ/pull/5229

There's clearly room for improvement as right now, this edge case is poorly handled by jOOQ's code generator.

I hope this helps

**Comment by napstr** [comment]
Thank you for the detailed answer, it works now with
```groovy
forcedType {
	userType = 'org.example.db.type.ExampleEnum[]'
	converter = 'org.example.db.converter.ExampleEnumArrayConverter'
	includeExpression = '.*'
	includeTypes = '_ExampleEnum'
}
```
and a converter of the following signature:
```public class ExampleEnumArrayConverter implements Converter<Exampleenum[], ExampleEnum[]> {...}```

The leading `_` was the main information I didn't manage to dig up by myself.

**Comment by lukaseder** [comment]
> The leading _ was the main information I didn't manage to dig up by myself previously.

Yes, that's really obscure. And fixing it may be difficult, as people have started to rely on it...
