### ISSUE TITLE
Parent pom.xml in commercial editions includes some unwanted elements

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9543]
The parent `pom.xml` of the commercial editions, which the customer downloads from jooq.org, contains some elements which don't belong there. For instance some test modules in the `<modules>` section or some test-related dependencies in the `<dependencies>`. These should be removed, as they could cause problems for the user.

**Comment by lukaseder** [comment]
> For instance some test modules in the `<modules>` section 

This has been addressed in the meantime

> or some test-related dependencies in the `<dependencies>`.

All dependencies are part of `<dependencyManagement>` in the current version.

Not sure if there are still any remaining problems.
