### ISSUE TITLE
Add org.jooq.Context method to prefix String to rendered SQL?

### ISSUE THREAD

**Issue by vdzhuvinov** [jOOQ/jOOQ#9548]
### Use case:

We created a custom Binding<String,String> to add an `N` prefix to NVARCHAR values with i18n chars (MS SQL Server).

```
public void sql(final BindingSQLContext<String> ctx) {
	if (ctx.render().paramType() == ParamType.INLINED) {
		// Prefix with 'N' for UTF16
		ctx.render().sql("N" + DSL.inline(ctx.value(), SQLDataType.NVARCHAR).toString());
	} else {
		ctx.render().sql("?");
	}
}
```
### Possible solution you'd like to see:

We're not entirely sure how safe or proper the above is. Perhaps a `ctx.render().visit(DSL.inline(ctx.value())).prefixSQL("N");` or similar would make better sense.

### Versions:

- jOOQ: 3.12.3
- Database (include vendor): SQL Server 2016

**Comment by lukaseder** [comment]
Thank you very much for your request.

In a library like jOOQ, there are often many ways to do the same thing. Your string concatenation approach is one way, another one would be this:

```java
ctx.render().sql("N").visit(DSL.inline(ctx.value()));
```

I think this better reflects the "prefixing" idea you've had, without requiring new API. Another approach would be to use plain SQL templating, although I don't think that's the best approach here:

```java
ctx.render.visit(DSL.field("N{0}", DSL.inline(ctx.value()));
```

**Comment by lukaseder** [comment]
Related issue: https://github.com/jOOQ/jOOQ/issues/9540

**Comment by vdzhuvinov** [comment]
Thanks for the response, much appreciated!

We'll take the 1st suggestion. I find it more appropriate, the `toString` contract is not so clear and I've had situations in projects when it changed.

**Comment by vdzhuvinov** [comment]
For the record, with null handling it becomes:

```
ctx.render().sql((ctx.value() != null ? "N" : "")).visit(DSL.inline(ctx.value()));
```

**Comment by lukaseder** [comment]
> the toString contract is not so clear and I've had situations in projects when it changed.

Indeed, there is actually no contract. It is useful for debugging only (with all types, not just jOOQ's).
