### ISSUE TITLE
not(unique(c)) / notUnique(c) and not(exists(c)) / notExists(c) should generate the same SQL

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9554]
I found a rather surprising comment in our parser tests, claiming:

```
// not(unique()) is logically equivalent to notUnique()
```

I'm not convinced that's a good idea as it would also be surprising to most other users. Indeed, in SQL, things like `NOT (X IS NULL)` and `X IS NOT NULL` are not the same thing. But I doubt there's ever a case where `NOT <some predicate>` and `NOT (<some predicate>)` are different. The parentheses shouldn't matter.

**Comment by lukaseder** [comment]
What are your thoughts on this, @knutwannheden?

**Comment by knutwannheden** [comment]
I believe the argument should be the same as for `EXISTS`, where I also think that the parenthesis doesn't matter.

**Comment by lukaseder** [comment]
Yes, but with `EXISTS`, I'm not aware of a problem. Does your comment mean that the two expressions do not produce the same jOOQ expression tree (but the same semantics)? Or does it mean that the semantics is different?

**Comment by knutwannheden** [comment]
I think the semantics should definitely be the same. I will have to look at the parser code to figure out what it currently does. Although I suppose it would be best if `NOT (UNIQUE (...))` is parsed as `not(unique(...))` and `NOT UNIQUE (...)` as `notUnique(...)`, even if they are currently rendered the same.

I will also check how this currently works for `EXISTS`.

**Comment by lukaseder** [comment]
Oh I see. So I was jumping to conclusions then.

> Although I suppose it would be best if NOT (UNIQUE (...)) is parsed as not(unique(...)) and NOT UNIQUE (...) as notUnique(...), even if they are currently rendered the same.

Yes, perhaps we should do it like that. And the same for `EXISTS`.

**Comment by knutwannheden** [comment]
You can also select some text before clicking "Quote reply":

![image](https://user-images.githubusercontent.com/408765/68954689-cea31480-07c4-11ea-9d64-1158b76113ff.png)

which results in:

> Yes, perhaps we should do it like that. And the same for `EXISTS`.

I.e. with the formatting preserved. But you probably already knew that. Now, if there only were a keyboard shortcut for this!

**Comment by lukaseder** [comment]
> I.e. with the formatting preserved. But you probably already knew that

I did

**Comment by knutwannheden** [comment]
> Now, if there only were a keyboard shortcut for this!

I just discovered there is! Just select the text and press `R` on the keyboard. :rocket:

**Comment by lukaseder** [comment]
What a time to be alive

**Comment by lukaseder** [comment]
Looking into this now. I think the distinction in semantics and syntax does not make sense. `notExists(...)` is sugar for `not(exists(...))`, so the implementation is "wrong".

`not(exists(...))` currently produces unnecessary parentheses, which might be removed in a future version of jOOQ: https://github.com/jOOQ/jOOQ/issues/10304

**Comment by lukaseder** [comment]
I've reverted this fix for now in 3.16.0-SNAPSHOT because it prevents a few tasks in the context of the new query object model: https://github.com/jOOQ/jOOQ/issues/12425 (`AbstractCondition.not()` should be final)

A more thorough fix will be implemented via #7362 and #10304, which should also ship in jOOQ 3.16
