### ISSUE TITLE
JDBC DatabaseMetaData backed Meta implementation should read DECIMAL_DIGITS for timestamp precision, not COLUMN_SIZE

### ISSUE THREAD

**Issue by nbrugger-tgm** [jOOQ/jOOQ#9590]
## Expected behavior and actual behavior:
I have a Database[MySQL] (running in docker)
In it i have a schema, this schema has a table containing a column with the `datetime(1)` type. When i use meta and ddl jOOQ converts it to `datetime(21)`

### more detailed

I obtain the schema by the `meta()` method. Then i use `dll()` method to generate a "script" to deploy the schema on another DB

the but the `create` statment for tables containing a `datetime(1)` type are wrong.<br>
Expected :  ``create table \`myschema`.`t1`(`time` datetime(1) not null, `user_mail` varchar(200) not null, constraint `PRIMARY` primary key (`time`, `user_mail`))``
> also `datetime` without brackets would be ok as it is a valid alias

actual : ``create table `myschema`.`t1`( `time` datetime(21) not null, `user_mail` varchar(200) not null, constraint `PRIMARY` primary key (`time`, `user_mail`))``

I use this code to transfer it to the other database
```java
DSLContext source = DSL.using(source_connection, SQLDialect.MYSQL);
Schema transfer = source.meta().getSchemas("myschema").get(0);
System.out.println(transfer.ddl(transfer).toString()); //used this to see if the script or execution is wrong by copy paste it into mysql CLI
//source.dropSchema("local_admin");
//source.ddl(transfer).executeBatch(); // for something like deploying it on a different DB
``` 

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
> I cannot provide a MCVE as this problem is (I guess) mysql specific and does not works with H2 DB

- Create a Schema in a DB
- Create a table in the schema
- Add a column with type `datetime(1)` (PK)
Use following java code
```java
DSLContext create = /*Building a MySQL connection; You use this name(create) in your tutorials*/
Schema schema = create.meta().getSchemas("schemaname").get(0);
System.out.println(create.ddl(transfer).toString()); //Here you will get a wrog DDL
```
### Versions:

- jOOQ: 3.12.1 (Open Source)
- Java: 1.8 (also tried 11)
- Database (include vendor): MySQL 5.7 (oracle i guess? used in *docker*) 
- OS: Ubuntu 18.4
- JDBC Driver (include name if inofficial driver): [MAVEN] 
```xml
<dependency>
	<groupId>mysql</groupId>
	<artifactId>mysql-connector-java</artifactId>
	<version>8.0.17</version>
</dependency>
```

**Comment by nbrugger-tgm** [comment]
## Additional Information
When i use autogen from the source DB and then use the schema constant to generate the DDL it just works fine and it creates `datetime` without any argument (which is also completely ok)

But the autogen script gives an interesting message:
`Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.`
Maybe this is a key to this problem?

I use maven autogen pluggin; and i did not attatched any additional information which driver to use except of the mysql dependency

**Comment by lukaseder** [comment]
Thank you very much for your report. We'll have a look. There are a few open timestamp precision related issues, currently, which we are going to be addressing soon. This one might be related.

**Comment by lukaseder** [comment]
Looking into this now. Regarding:

> But the autogen script gives an interesting message:
> `Loading class 'com.mysql.jdbc.Driver'. This is deprecated. The new driver class is 'com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.`
> Maybe this is a key to this problem?

That seems quite unrelated. If you think that's a problem caused by jOOQ rather than your project setup, please feel free to create a new issue

**Comment by lukaseder** [comment]
I can reproduce this with the following snippet:

```java
try {
    ctx.createTable("x").column("ts", TIMESTAMP(1)).execute();
    ctx.meta()
        .filterTables(t -> t.getName().equalsIgnoreCase("x"))
        .getTables()
        .stream()
        .flatMap(t -> Stream.of(t.fields()))
        .map(f -> f.getDataType())
        .forEach(System.out::println);
}
finally {
    ctx.dropTable("x").execute();
}
```

This prints:

```
datetime(26) (java.sql.Timestamp)
```

**Comment by lukaseder** [comment]
This is what's being returned from JDBC's `DatabaseMetaData::getColumns`:

```
+---------+-----------+----------+-----------+---------+---------+-----------+-------------+--------------+--------------+--------+-------+----------+-------------+----------------+-----------------+----------------+-----------+-------------+------------+-----------+----------------+----------------+
|TABLE_CAT|TABLE_SCHEM|TABLE_NAME|COLUMN_NAME|DATA_TYPE|TYPE_NAME|COLUMN_SIZE|BUFFER_LENGTH|DECIMAL_DIGITS|NUM_PREC_RADIX|NULLABLE|REMARKS|COLUMN_DEF|SQL_DATA_TYPE|SQL_DATETIME_SUB|CHAR_OCTET_LENGTH|ORDINAL_POSITION|IS_NULLABLE|SCOPE_CATALOG|SCOPE_SCHEMA|SCOPE_TABLE|SOURCE_DATA_TYPE|IS_AUTOINCREMENT|
+---------+-----------+----------+-----------+---------+---------+-----------+-------------+--------------+--------------+--------+-------+----------+-------------+----------------+-----------------+----------------+-----------+-------------+------------+-----------+----------------+----------------+
|s        |{null}     |x         |ts         |       93|TIMESTAMP|         26|65535        |        {null}|            10|       1|       |{null}    |            0|               0|           {null}|               1|YES        |{null}       |{null}      |{null}     |{null}          |NO              |
+---------+-----------+----------+-----------+---------+---------+-----------+-------------+--------------+--------------+--------+-------+----------+-------------+----------------+-----------------+----------------+-----------+-------------+------------+-----------+----------------+----------------+
```

**Comment by lukaseder** [comment]
The JDBC driver's `COLUMN_SIZE` information is not very useful:

```java
        sqlBuf.append(" WHEN UPPER(DATA_TYPE)='DATETIME' THEN 26"); // supported range is '1000-01-01 00:00:00.000000' to '9999-12-31 23:59:59.999999'
        sqlBuf.append(" WHEN UPPER(DATA_TYPE)='TIMESTAMP' THEN 26"); // supported range is '1970-01-01 00:00:01.000000' UTC to '2038-01-19 03:14:07.999999' UTC
```

There are numerous problems with the existing JDBC `DatabaseMetaData` backed `Meta` implementation that could be solved thoroughly by moving `jOOQ-meta` queries into the core: https://github.com/jOOQ/jOOQ/issues/8655.

Prior to a thorough fix, I suspect that ignoring the `COLUMN_SIZE` for MySQL temporal data types would be best, as that would at least produce `DATETIME` as a type, not the invalid `DATETIME(26)`

**Comment by lukaseder** [comment]
It is also wrong for H2, which produces:

```
+---------+-----------+----------+-----------+---------+---------+-----------+-------------+--------------+--------------+--------+-------+----------+-------------+----------------+-----------------+----------------+-----------+-------------+------------+-----------+----------------+----------------+
|TABLE_CAT|TABLE_SCHEM|TABLE_NAME|COLUMN_NAME|DATA_TYPE|TYPE_NAME|COLUMN_SIZE|BUFFER_LENGTH|DECIMAL_DIGITS|NUM_PREC_RADIX|NULLABLE|REMARKS|COLUMN_DEF|SQL_DATA_TYPE|SQL_DATETIME_SUB|CHAR_OCTET_LENGTH|ORDINAL_POSITION|IS_NULLABLE|SCOPE_CATALOG|SCOPE_SCHEMA|SCOPE_TABLE|SOURCE_DATA_TYPE|IS_AUTOINCREMENT|
+---------+-----------+----------+-----------+---------+---------+-----------+-------------+--------------+--------------+--------+-------+----------+-------------+----------------+-----------------+----------------+-----------+-------------+------------+-----------+----------------+----------------+
|TEST     |S          |X         |TS         |       93|TIMESTAMP|         21|21           |             1|            10|       1|       |{null}    |           93|               0|               21|               1|YES        |{null}       |{null}      |{null}     |{null}          |NO              |
+---------+-----------+----------+-----------+---------+---------+-----------+-------------+--------------+--------------+--------+-------+----------+-------------+----------------+-----------------+----------------+-----------+-------------+------------+-----------+----------------+----------------+
```

I.e. the `DECIMAL_DIGITS` seems to be what's being used here by H2. This could be a better column to use in general, and it would still be OK in MySQL, where the value is `null`, i.e. unavailable.

**Comment by lukaseder** [comment]
Let's find out in the integration tests. I'll update the following list:

- [x] H2 reports the precision in `DECIMAL_DIGITS`
- [x] MySQL doesn't report the precision

**Comment by lukaseder** [comment]
This has been verified for the dialects listed in https://github.com/jOOQ/jOOQ/issues/9590#issuecomment-655566830. Other dialects may not support timestamp precision, or have not yet been verified

**Comment by lukaseder** [comment]
The fix depends on a variety of improvements made in jOOQ 3.14 around data types. This makes backporting the fix too complex.
