### ISSUE TITLE
FULLTEXT support to use match/against cluases

### ISSUE THREAD

**Issue by shojaedin** [jOOQ/jOOQ#9593]
Hi there,
I am trying to make a FULLTEXT index for a column:
`create fulltext index a on test(`x`);`

And then use it for match/against cluases:
`select * from test where match(`x`) against ('abc');`

Based on the comments here https://github.com/jOOQ/jOOQ/issues/9161, it seems that Jooq recognizes this syntax: `create fulltext key a on t(x)`. However I could not find any related release https://www.jooq.org/notes. Could you please let me if any Jooq version supports FULLTEXT index and match/against clauses?

### Versions:

-jOOQ: 3.11.9
Java: 8
JDBC Driver: H2

**Comment by lukaseder** [comment]
Thank you very much for your message.

Issue https://github.com/jOOQ/jOOQ/issues/9161 was backported to 3.12.2 via https://github.com/jOOQ/jOOQ/issues/9173

However, those issues only discuss what the jOOQ parser can recognise. It will simply ignore the `FULLTEXT` keyword and create an ordinary index behind the scenes.

If you want to actually create and use such an index, you will need to resort to plain SQL templating in both cases:
https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

I hope this helps
