### ISSUE TITLE
Regenerate MySQL information schema against 8.0.18

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9596]
Regenerate MySQL information schema code in module `jooq-meta` for MySQL version 8.0.18.

**Comment by knutwannheden** [comment]
@lukaseder The regenerated code yields some new fields in Java, but also some fields with a different type, so I added the `T: Incompatible change` label.

**Comment by lukaseder** [comment]
> The regenerated code yields some new fields in Java, but also some fields with a different type, so I added the `T: Incompatible change` label.

Agreed
