### ISSUE TITLE
DefaultRelations#getCheckConstraints() returns all checks on first call

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9597]
A bug in the implementation of `org.jooq.meta.DefaultRelations.getCheckConstraints(TableDefinition)` (of module `jooq-meta`) has the effect of declaring the first table for which the method gets called as the owner of all constraints.

**Comment by knutwannheden** [comment]
@lukaseder Not sure where this method is used in earlier versions of jOOQ. Should we backport the fix to 3.12?

**Comment by lukaseder** [comment]
> @lukaseder Not sure where this method is used in earlier versions of jOOQ. Should we backport the fix to 3.12?

No need to backport. While `CheckConstraintDefinition` support was added quite a few releases ago, it was never really used. At some point, check constraints generated Javadoc (I think?), but I had removed that again, as it wasn't really useful.

**Comment by lukaseder** [comment]
We only really need it starting with jOOQ 3.13

**Comment by lukaseder** [comment]
I think this is fixed, no? Please reopen if there's still something missing...
