### ISSUE TITLE
Add code generation flag <includeSystemIndexes/>

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9601]
Similar to system generated `CHECK` constraints, we want to be able to exclude system generated indexes from code generation output, as there is no value in reproducing those indexes in `Meta.ddl()`

The default for `<includeSystemIndexes/>` will be `false`.

System generated indexes include:

### Primary and unique keys

- [x] CockroachDB (check if index name contains `_auto_index_` (foreign key) or whether it is contained in `TableDefinition.getUniqueKeys()`)
- [x] DB2 (use `SYSCAT.INDEXES.SYSTEMREQUIRED`)
- [x] H2 (use `IS.INDEXES.IS_GENERATED`)
- [x] HSQLDB (name starts with `SYS_IDX_`)
- [x] MariaDB (same as MySQL)
- [x] MemSQL
- [x] MySQL (exclude the indexes which are contained in `IS.TABLE_CONSTRAINTS`)
- [x] Oracle (exclude the indexes which are contained in `ALL_CONSTRAINTS`)
- [x] PostgreSQL (exclude the indexes which are contained in `IS.TABLE_CONSTRAINTS`)
- [x] SQLite (`pragma_index_list.origin not in ('pk', 'u')`)
- [x] SQL Server (use `sys.indexes.is_primary_key` and `is_unique_constraint`)

### Foreign keys

- [x] H2
- [x] MariaDB (same as MySQL)
- [x] MemSQL doesn't support foreign keys yet, although it supports the syntax and creates an index :)
- [x] MySQL

### Databases which have no index generation support yet:

- [x] Derby: #9610
- [x]  Informix: #9611

----

This change is marked "incompatible" as the default behaviour changes between minor releases.

**Comment by lukaseder** [comment]
The generation of system indexes is especially annoying in HSQLDB, where they might change their names when the schema is re-generated from scratch, or on different developer machines. This might happen in other dialects as well...

**Comment by knutwannheden** [comment]
With the default for this new flag being `false`, should this be considered an "incompatible change", since user code might refer to the corresponding generated fields? Or should there be some upgrade instructions documenting this?

**Comment by lukaseder** [comment]
Good questions. In my opinion, the fact that these were being generated could be seen as a bug. When using `Meta.ddl()`, it is undesireable to get both constraint definitions and index definitions in the resulting DDL.

However, we could definitely have "upgrade instructions". The default would be to mark this as an incompatible change as that already leads to this issue being documented separately in the release notes.

We could have another category of "notable changes", which aren't strictly incompatible. But I tend to think that's overkill.

I'll mark this as incompatible.

**Comment by lukaseder** [comment]
Adding missing documentation...
