### ISSUE TITLE
Use DDLInterpreter in DDLMetaProvider

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9634]
The `DDLMetaProvider` should use the `DDLInterpreter` in case the `Settings.interpreterDialect` is set to `DEFAULT`. Currently I think it would execute the DDL against an in-memory H2 database.

**Comment by lukaseder** [comment]
I'm not sure if there's still anything missing in the core library. Check out `SourceMetaProvider`, which I have added because of #9426, and which already implements what you're suggesting here as of #9362.

What's still missing:

- #6551 (support other dialects than the embedded ones via testcontainers or some other mechanism)
- #7034 Adapt `DDLDatabase` to use this logic

**Comment by lukaseder** [comment]
I closed this as a duplicate. Feel free to reopen if you think I've missed something.

**Comment by knutwannheden** [comment]
I see. Should possibly the `DDLMetaProvider` also delegate to `DDLInterpreterMetaProvider` if the `Settings.interpreterDialect` is `DEFAULT`, just like the `SourceMetaProvider` does?

**Comment by lukaseder** [comment]
> I see. Should possibly the `DDLMetaProvider` also delegate to `DDLInterpreterMetaProvider` if the `Settings.interpreterDialect` is `DEFAULT`, just like the `SourceMetaProvider` does?

But why? Would it help, if we just renamed the class?

**Comment by lukaseder** [comment]
I guess I will rename that `DDLMetaProvider` class. I'm not sure what you had in mind with your original design, and where you were going to take this implementation. But the way it is now:

- `DDLMetaProvider` is a `MetaProvider` that translates SQL to some dialect and runs the statements on an actual `Connection`. It is used *only* by `SourceMetaProvider`. This could be renamed to something else.
- `SourceMetaProvider` is a `MetaProvider` that can read sources and interpret them in a meaningful way.
