### ISSUE TITLE
Apply Database::getOrderProvider to Keys.java content as well

### ISSUE THREAD

**Issue by a-derevyanko** [jOOQ/jOOQ#9639]
### Use case:

Generated constants of our project are stored under version control.

Due to the fact that many people work on the project, we often have conflicts in the generated class `Keys.java`, since when adding a new table these classes are able to completely rebuild, and the new order of constants is not logical.

The problem is that the `JavaGenerator#generateRelations()` method computes the identifier of the next subclass for a class with constants as follows:
`final int block = allIdentities.size () / INITIALISER_SIZE;`

The  allIdentities list is filled dynamically during the generation of constants, respectively, when a new Identitiy appears in the middle of the list, all subsequent Identities change the block identifier and the file with constants is completely rebuilt.

Exactly the same problem occurs with the class `%SchemaName% .java` and its `getSequencesXXX()` methods.

### Possible workarounds:

I redefined block identifier calculation as follows:
`Math.abs(keyId.hashCode()) % 500;`

Obviously, instead of computing the hashcode, any other function with uniform distribution can be used, but we are happy with this option.
But, since the `org.jooq.codegen.JavaGenerator#database` property has private access and `org.jooq.codegen.JavaGenerator#generate(org.jooq.meta.Database) `has final modifier, I have to use reflection (in addition to almost completely overriding the `generateRelations `method) to get it value and it all looks monstrous.

### Versions:

- jOOQ: 3.12.2
- Java: 1.7
- Database (include vendor): Oracle

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. That's a very interesting problem - I must admit, I've not yet thought about these block sizes getting in the way of a reasonably predictable ordering of objects in generated code. It is an arbitrary cut, indeed.

Generating sparse buckets with a suggestion like yours seems to solve your problem, but it will make the generated code *very ugly* for small schemas, where a lot of such buckets would be generated for no apparent reason. After all, the buckets are needed to avoid the 64kb byte code per method limit, which is not a problem for small schemas.

Perhaps, we could add a configuration flag to choose between the two approaches. I'm not too eager to implement this, as it adds much complexity to an already complex area of the code generator for mostly cosmetic reasons. We'll keep this issue open to see if it collects traction with the community, though.

Thanks again for your suggestion!

**Comment by a-derevyanko** [comment]
I completely agree that the code looks ugly, therefore reduced the number of buckets to 50 :)

Although I can’t say that in these classes this is important, we rarely look inside them.

**Comment by lukaseder** [comment]
> I completely agree that the code looks ugly, therefore reduced the number of buckets to 50 :)

And then, you have to trust your hash function not to produce too many collisions, or you'll run again into the original issue this feature was solving: > 64kb method bodies... :)

**Comment by lukaseder** [comment]
Starting from jOOQ 3.14, we're no longer generating identity constants in `Keys.java`, see #10283, #10397. But the issue appears also with unique keys and foreign keys.

The way we produce predictable ordering in generated code is by using the `Database::getOrderProvider`, configured in `<orderProvider>`, defaulting to `org.jooq.meta.DefaultOrderProvider`. This is currently not being used, which is a bug. The order provider should be applied to `Keys.java` content as well.

**Comment by lukaseder** [comment]
While this fix doesn't solve your problem out of the box, it will at least allow you to implement your workaround by providing your own order provider that sorts keys e.g. by the date of addition to the schema if that is available to you.

I don't think the solution here should be to evenly distribute elements across buckets, let alone offer user configuration for this technical workaround for the 64kb initialiser bytecode limit. But by allowing to sort objects in a user-defined manner, it would be possible to work around this problem in a custom way.

**Comment by lukaseder** [comment]
In addition to this improvement, let's make the default value for `JavaGenerator.INITIALISER_SIZE` higher and configurable: https://github.com/jOOQ/jOOQ/issues/10653
