### ISSUE TITLE
Migrate Java EE dependencies to Jakarta EE

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9641]
The Java EE `javax.*` namespace has not been donated to Jakarta EE, which means that future implementations of Jakarta EE APIs will be published under a new namespace.

We mainly depend on two of these APIs:

- [x] JAXB
- [x] JPA
  - [x] Log warnings in `DefaultRecordMapper` if we encounter `javax.persistence` annotations
- [x] Validation (code generation only)
- [x] Update the code generation options
- [x] Update the manual

----
See also: 
- https://github.com/jOOQ/jOOQ/pull/9640
- https://stackoverflow.com/q/69327738/521799

**Comment by MirkoTeran** [comment]
Is there any update on this?

I have tried converting project from javax.* to jakarta.* artifacts and after a bit of messing around how different libraries work managed to make it work. One issue I currently have is with jOOQ records using javax.validation. I can run replace each time I generate them, but a option in <generatedAnnotationType> of generator to switch to jakarta would be real nice.

**Comment by lukaseder** [comment]
> One issue I currently have is with jOOQ records using javax.validation

Since we have to touch this anyway, this might be a good opportunity to drop support for those validation annotations :) What do you need them for?

**Comment by MirkoTeran** [comment]
Good point. I'll disable them in generator and see if it breaks anything.

**Comment by lukaseder** [comment]
Spring Framework 6 / Spring Boot 3 will use the Jakarta package namespace for their baseline in Q4 2022. That seems to be a good opportunity to review this task here: 
https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6

Whenever we *consume* these annotations (e.g. in the `DefaultRecordMapper`), it seems important we support both the old and the new ones for compatibility reasons, defaulting to the new ones when we generate the annotations ourselves.

I'll make this a priority for jOOQ 3.16, as this is something an increasing number of users run into.

**Comment by lukaseder** [comment]
Looks like there's some additional pressure here: https://github.com/spring-projects/spring-boot/issues/28821

**Comment by lukaseder** [comment]
While there were various options of supporting both APIs in parallel, given the very minor usefulness of these features, the decision was made to drop support for the `javax` APIs in jOOQ 3.16

**Comment by lukaseder** [comment]
Hmm, there's room for continued support of the `javax` namespace, at least for the JPA dependency, if we extract that dependency through a new SPI: https://github.com/jOOQ/jOOQ/issues/8599
