### ISSUE TITLE
Add support for the Snowflake database

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9650]
Snowflake is another vendor that has seen some traction in recent past:
https://www.snowflake.com

This integration will ship in jOOQ 3.15.

**Comment by effiban** [comment]
@lukaseder - First of all - I am very interested in this. 
Second - for the time being I am working around the lack of support with custom DSLs. 
I'm having trouble with the Snowflake "COPY INTO" statement for loading data, which is somewhat similar to INSERT but has some significant differences. 
It seems the only sensible way to handle this is by extending _package-private_ classes such as `AbstractDelegatingQuery` and `AbstractStoreQuery` so I can achieve the SQL rendering I want while still enjoying those parts of the DSL that works out of the box - but obviously I would like to avoid using the **org.jooq** namespace in my code (and it's difficult to extend these classes).
If you have any thoughts on this, would be great.
Thanks

**Comment by lukaseder** [comment]
@effiban Thanks for your message. 

> First of all - I am very interested in this.

This feature has a very high chance of adoption in jOOQ 3.15 early next year, given the number of upvotes it got recently.

> Second - for the time being I am working around the lack of support with custom DSLs.

There's a pending feature request for `COPY` support: https://github.com/jOOQ/jOOQ/issues/2747. I'm not convinced this is something we should rush to support. All RDBMS have various vendor specific means of loading data into the database. We offer our own using the loader API: https://www.jooq.org/doc/latest/manual/sql-execution/importing.

> It seems the only sensible way to handle this is by extending package-private classes such as AbstractDelegatingQuery and AbstractStoreQuery so I can achieve the SQL rendering I want while still enjoying those parts of the DSL that work out of the box - but obviously I would like to avoid using the org.jooq namespace in my code (and it's difficult to extend these classes).
If you have any thoughts on this, would be great.

Yes, I don't think you should really extend any jOOQ internals. Just implement some API on top of our plain SQL templating capabilities to generate the right syntax: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating

I hope this helps

**Comment by effiban** [comment]
> @effiban Thanks for your message.
> 
> > First of all - I am very interested in this.
> 
> This feature has a very high chance of adoption in jOOQ 3.15 early next year, given the number of upvotes it got recently.
> 
> > Second - for the time being I am working around the lack of support with custom DSLs.
> 
> There's a pending feature request for `COPY` support: #2747. I'm not convinced this is something we should rush to support. All RDBMS have various vendor specific means of loading data into the database. We offer our own using the loader API: https://www.jooq.org/doc/latest/manual/sql-execution/importing.
> 
> > It seems the only sensible way to handle this is by extending package-private classes such as AbstractDelegatingQuery and AbstractStoreQuery so I can achieve the SQL rendering I want while still enjoying those parts of the DSL that work out of the box - but obviously I would like to avoid using the org.jooq namespace in my code (and it's difficult to extend these classes).
> > If you have any thoughts on this, would be great.
> 
> Yes, I don't think you should really extend any jOOQ internals. Just implement some API on top of our plain SQL templating capabilities to generate the right syntax: https://www.jooq.org/doc/latest/manual/sql-building/plain-sql-templating
> 
> I hope this helps

Thanks! It did help but was still tricky to implement. The main issue was how to handle the Snowflake 'Stage' which is similar to a table but rendered differently (with a prefix '@') so I couldn't extend `CustomTable` or `TableImpl`. Anyway I figured it out eventually...

**Comment by lukaseder** [comment]
I've started working on this integration. This is definitely part of jOOQ 3.15

**Comment by lukaseder** [comment]
Support has been integrated for jOOQ 3.15.

**Comment by rloeffel** [comment]
nice, thank you for providing snowflake support in jooq.

I wonder why there is no support for codegeneration on snowflake table functions. At least I could not find a way to generate those and when analysing the SnowflakeDatabase class I could not find any code that would do that. Will this feature be added at some point or are there any reasons why this is not possible?

Additionally the corresponding FunctionTable class does not wrap the "table(" syntax before the function call for snowflake. 

I'm stuck. Or is there another way how jooq should call snowflake functions?

**Comment by lukaseder** [comment]
Thanks for your message, @rloeffel. The relevant feature request is:

- https://github.com/jOOQ/jOOQ/issues/13530

It will be added at some point, along with a few other things that are worth supporting in Snowflake. The main reason is simply that we tend to add support for the most important features of a dialect first, and the more remote features and use-cases upon community request. It's hard to foresee what parts of jOOQ the community will need.

In this particular case, the procedural language support didn't seem to be one of the primary use-cases for jOOQ, but if this adds value to your work, then there's no reason not to push this.



> Additionally the corresponding FunctionTable class does not wrap the "table(" syntax before the function call for snowflake.

I'm not sure what you mean by this. Could you please open up a new support request with some details? I'll be happy to help

**Comment by rloeffel** [comment]
Thanks for your quick reply. The mentioned feature would fulfill our requirements
