### ISSUE TITLE
Support parsing // as a single line comment token

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9651]
Snowflake (and possibly others?) support the `//` token for c-style single line comments, see #9648. We should support this token in:

- [x] The parser
- [x] The plain SQL parser (#9648 fixes an AIOOBE in that parser)

Some additional research is required prior to implementing this, to be sure that we're not creating a regression with potential dialects that already use `//` as an operator. PostgreSQL would be a candidate, althought a vanilla PG 12 installation doesn't list the operator in `pg_operator`.

**Comment by katzyn** [comment]
H2 historically supports `//` line comments too. But they are quite exotic in SQL.

**Comment by lukaseder** [comment]
Interesting, thanks for sharing, @katzyn. That increases the likelihood of this being supported also in jOOQ.

Do you know the historic reason for this feature? Was it an independent idea someone working on H2 had, or an emulation of some other database dialect?

**Comment by katzyn** [comment]
Hypersonic SQL also had C++-style `//` comments, it could be the reason, but only Thomas can confirm. Its successor HSQLDB, however, doesn't support them, at least in 2.5.0.
