### ISSUE TITLE
Publish 3.12 snapshots on website

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9657]
We're now offering "next minor release" snapshots on our website:
https://github.com/jOOQ/jOOQ/issues/9053

We should also offer a snapshot for 3.12 on the website, so customers can already get access to fixes immediately.

Only the last snapshot is offered from the website, and we won't upload a new ZIP file when there's no difference in content

**Comment by knutwannheden** [comment]
By backporting the changes we made for SNAPSHOT releases on the master branch to the 3.12 branch, we should be well prepared for this now.

After releasing a new patch version I think that we should probably update all Maven module versions so that we can start making SNAPSHOT releases of the next patch version. So for 3.12.4 we will set the Maven versions to `3.12.4` and after that we should set it to `3.12.5-SNAPSHOT`.

**Comment by lukaseder** [comment]
> After releasing a new patch version I think that we should probably update all Maven module versions so that we can start making SNAPSHOT releases of the next patch version. So for 3.12.4 we will set the Maven versions to `3.12.4` and after that we should set it to `3.12.5-SNAPSHOT`.

Yes, I've noticed this as well, yesterday. Currently, the version is still 3.12.3 on the branch.

The release process should be:

- Set the version to what's going to be released (e.g. 3.12.3)
- Release
- Set the version to the next snapshot (e.g. 3.12.4-SNAPSHOT)
- Iterate

I'll set the verison to 3.12.4-SNAPSHOT right away

**Comment by lukaseder** [comment]
(We'll probably automate this eventually, but for the time being, we can also do it manually)

**Comment by lukaseder** [comment]
Updated also manual steps: https://github.com/jOOQ/jOOQ-pro/wiki/Instructions:-Release-Guide

**Comment by lukaseder** [comment]
The website now displays 3.12 snapshots as well:
https://www.jooq.org/download/versions

However, it seems that only the Java 11 distribution is uploaded right now, not Java 8 and 6?

**Comment by knutwannheden** [comment]
> However, it seems that only the Java 11 distribution is uploaded right now, not Java 8 and 6?

I will look into it.

**Comment by knutwannheden** [comment]
For some reason the Jenkins pipeline was not automatically triggered, as it should have been.

**Comment by lukaseder** [comment]
OK, so it will upload after the next build-all?

**Comment by knutwannheden** [comment]
> OK, so it will upload after the next build-all?

Yes, the deployment job is running now.

**Comment by lukaseder** [comment]
Cool, thanks! I'll close this once the files are uploaded.

**Comment by lukaseder** [comment]
The Java 6 build was uploaded, waiting for the Java 8 build: https://www.jooq.org/download/versions

**Comment by knutwannheden** [comment]
Should all be there now.

**Comment by lukaseder** [comment]
Yep, very cool!
