### ISSUE TITLE
Parser should reject duplicate identities

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9664]
In SQL, tables can only have a single identity. This (and alternative syntaxes) should be rejected by the parser, but currently isn't:

```sql
create table a (
  i int auto_increment,
  b int auto_increment
);
```

**Comment by katzyn** [comment]
Such definition with MySQL-specific syntax is perfectly valid in H2 (but not in MySQL).

**Comment by katzyn** [comment]
PostgreSQL also accepts
```SQL
create table a (
  i int generated by default as identity,
  b int generated by default as identity
);
```

**Comment by katzyn** [comment]
I also don't see such requirement in the Standard.

**Comment by lukaseder** [comment]
> I also don't see such requirement in the Standard.

In SQL-2016:

> ```
> 11.3 <table definition>
> Syntax Rules
> 9) b) iv) 1) 1) <identity option> shall not be specified more than once, <column default option> shall not be specified more than once, and <generation option> shall not be specified more than
once.
> ...
> 11.11 <add column definition>
> Syntax Rules
> 3) If <column definition> contains <identity column specification>, then the table descriptor of T shall not include a column descriptor of an identity column.
> 15) At most one <table element> shall be a <column definition> that contains an <identity column specification>.
> ```

Additional reasoning:

1. What would be the meaning of having more than one "identity"? The concept of "identity" usually means that a row can be *identified* by it (I know there's unfortunately no implied uniqueness criteria, that is enforced by an additional, independent constraint)
2. Most dialects support fetching the previously inserted identity. E.g. in SQL Server, you can `select @@identity`. In H2, there's `IDENTITY()`. So, which one of the two would you expect to be fetched?
3. In the standard, there are commands like `TRUNCATE TABLE .. [ CONTINUE IDENTITY | RESTART IDENTITY ]` with `IDENTITY` in singular. It would be surprising to expect this to apply to *identities*

Now, why on earth does PostgreSQL allow it? Probably because it was possible, before, to have more than one `serial` column, and it is obviously possible to have more than one sequence generated column, but that should not be called "identity".

In any case, jOOQ's meta model doesn't allow for multiple identities, so we will reject that syntax, which probably hardly anyone is using even if it is possible.

**Comment by katzyn** [comment]
Thanks for the reference!

Some tables may have generated numeric and generated natural key and natural key may use an expression with a sequence. But such key is not described as identity.

`IDENTITY()` will be deprecated in H2 1.4.201 in favor of more reliable `CURRENT VALUE FOR sequence` or standard data change delta table.

**Comment by katzyn** [comment]
Actually H2 does not track identity columns yet, they are converted to columns with sequence-based default expressions. Therefore H2 can't detect presence of identity columns in existing tables.

**Comment by lukaseder** [comment]
> Some tables may have generated numeric primary key and generated unique natural key and natural key may use an expression with a sequence. But such key is not described as identity.

Yes, absolutely nothing wrong with having several sequence generated default values.

> `IDENTITY()` will be deprecated in H2 1.4.201 in favor of more reliable `CURRENT VALUE FOR sequence` or standard data change delta table.

Good to know. The data change delta table is really my favourite approach to fetching these values.

**Comment by katzyn** [comment]
Data change delta tables are available in 1.4.200, but I guess you still support older versions too.

---

BTW, the first quote from the Standard is about `<like options>`, so that restriction is not related with simple table definitions in any way.

But there is also
> 15) At most one `<table element>` shall be a `<column definition>` that contains an `<identity column specification>`.

So simple definitions may not have multiple identity columns anyway.

**Comment by lukaseder** [comment]
> BTW, the first quote from the Standard is about `<like options>`, so that restriction is not related with simple table definitions in any way.

I know I just quoted all the relevant content, including 15. I do think it is very much related. Why would that restriction be mentioned for `<like options>`, if it wasn't also included for the original table definition...

**Comment by katzyn** [comment]
> Why would that restriction be mentioned for `<like options>`, if it wasn't also included for the original table definition...

Because they aren't related with each other. `<identity option>` is not a part of `<identity column specification>`.

Anyway, it doesn't matter. Standard clearly forbids multiple columns.
