### ISSUE TITLE
Offer Java 11 and 6 trial downloads from website

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9668]
The current free trial download on the jOOQ website (https://www.jooq.org/download) has been built with Java 8. It would be great if we could offer free trials for Java 6 and Java 11 as well. Currently, customers have to request an extended trial per e-mail to get access to those builds from here: https://www.jooq.org/download/versions

They shouldn't have to.

**Comment by knutwannheden** [comment]
We could easily set up the splitter to create these new editions. IMHO we don't need to additionally also test these two editions. I think that should be covered by the corresponding pro-editions already.

**Comment by lukaseder** [comment]
Hmm, would running the tests be too much effort? The trial editions are updated only with new releases. Using the sha checksums, perhaps, we wouldn't have to build these all the time...?

**Comment by lukaseder** [comment]
Egh, the checksum is calculated after building, so the decision of running the tests would have had to be made before...

**Comment by knutwannheden** [comment]
We would have to set up some dedicated build, which only runs when we make a new release, I suppose.

Related is also the task of always packaging a new trial edition with an updated expiry date.

**Comment by lukaseder** [comment]
> We would have to set up some dedicated build, which only runs when we make a new release, I suppose.

Yes, we could. But for now, I guess to get quick results, just skipping the tests might be good enough.

**Comment by knutwannheden** [comment]
The required changes have been integrated so that when we release jOOQ 3.12.4 we will be able to build and release a trial edition for Java 6, 8, and 11.

**Comment by lukaseder** [comment]
Very cool, thank you! I'm assuming, I will (for now) just have to look for the zip files on the CI/CD server?

**Comment by lukaseder** [comment]
Or are they uploaded automatically, already?

**Comment by knutwannheden** [comment]
No, I think we said we would for now not offer any SNAPSHOT trial builds and we don't yet have any release tags where we could run the corresponding builds.

**Comment by lukaseder** [comment]
So, how will I proceed to

> be able to build and release a trial edition for Java 6, 8, and 11.

**Comment by knutwannheden** [comment]
That is still to be defined. I assume we would first update the Maven versions on the 3.12 branch from `3.12.4-SNAPSHOT` to `3.12.4` , update the `RELEASENOTES.txt`, etc. and then create a Git tag.

Then I suppose we should create a Jenkins job we can run on a given Git commit to build and deploy the trial ZIP files.

**Comment by knutwannheden** [comment]
There is a new Jenkins `jooq-deploy-trial` build which can be used to build and deploy the trial editions.

**Comment by lukaseder** [comment]
I'm trying to fix the broken trial edition on the website, which has again been built with Java 11 instead of Java 8 (see customer complaints by email). Notice, we switched to using Java 8 for the free trial about 2-3 months ago.

I tried the splitter to generate `workspace-jooq-trial-java-8`, but the parent `pom.xml` does not have any release profiles, nor is the `jOOQ-release` project available to build the zip file in this workspace.

Luckily, I still have an older 3.12.3 build on my local machine, which I'm building and uploading again now.

**Comment by lukaseder** [comment]
The current state of the 3.12.3 branch doesn't make it easy to release trial releases right now. I'll fix things tomorrow and release 3.12.4, which includes a few changes that are prerequisites to the correct release.

**Comment by lukaseder** [comment]
The build is working now. All that's left to do is:

- [ ] Add links to https://www.jooq.org/download/versions
- [ ] Change the link from https://www.jooq.org/download/ to the `trial-java-8` distribution

**Comment by lukaseder** [comment]
That seems to be because of the following logic added by https://github.com/jOOQ/jOOQ/issues/9543

```
    def static EnumSet<Token> tokens(Token... tokens) {
        val result = EnumSet.copyOf(tokens);
        // [#9543] for release builds exclude all INTERNAL and TEST tagged code
        if (Boolean.getBoolean("release")) {
            result.add(INTERNAL);
            result.add(TEST);
        }
        // ... otherwise add the RELEASE token
        else {
            result.add(RELEASE);
        }
        return result;
    }
```

I can't say I like this mechanism. Things are complicated enough without tweaking these token configurations like that, using system properties.

Since this logic is used only when calling `Splitter.main()` from `master-build.sh`, my suggestion would be to at least move it into `Splitter.main()`, such that the `BuildOssEdition.main(args)` logic (can be used for manual execution) remains untouched. But I still don't think this is clean.

**Comment by lukaseder** [comment]
This now works. By default, the Java 8 Trial Edition is downloaded. Java 11 and 6 downloads are available from here:
https://www.jooq.org/download/versions#trial
