### ISSUE TITLE
Make slf4j-api version backwards compatible

### ISSUE THREAD

**Issue by davsclaus** [jOOQ/jOOQ#9670]
jooq 3.12.3 release is using slf4j-api v1.8 (beta4). As many of us are using stable releases such as the slf4j 1.7 api, then this fails, especially on OSGi where you get this kind of error

I wonder if can make the OSGi version range be [1.7,2)" or maybe go back to using a stable 1.7 version. You marked it as optional and provided by it can hardly be optional if you have java imports on this API in jooq.

> RROR] Message: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=camel-jooq; type=karaf.feature; version=3.1.0.SNAPSHOT; filter:="(&(osgi.identity=camel-jooq)(type=karaf.feature)(version>=3.1.0.SNAPSHOT))" [caused by: Unable to resolve camel-jooq/3.1.0.SNAPSHOT: missing requirement [camel-jooq/3.1.0.SNAPSHOT] osgi.identity; osgi.identity=org.apache.camel.camel-jooq; type=osgi.bundle; version="[3.1.0.SNAPSHOT,3.1.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.apache.camel.camel-jooq/3.1.0.SNAPSHOT: missing requirement [org.apache.camel.camel-jooq/3.1.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.jooq.impl)(version>=3.12.0)(!(version>=4.0.0)))" [caused by: Unable to resolve jooq/3.12.3: missing requirement [jooq/3.12.3] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.slf4j)(version>=1.8.0)(!(version>=2.0.0)))"]]]

**Comment by lukaseder** [comment]
Thank you very much for your suggestion

> I wonder if can make the OSGi version range be [1.7,2)" 

That can probably be done. What change to the `maven-bundle-plugin` are you suggesting, specifically?

https://github.com/jOOQ/jOOQ/blob/485afa0551f9f21010b390d36fb6514d53f03d03/jOOQ/pom.xml#L33-L60

> or maybe go back to using a stable 1.7 version.

Unfortunately, I don't remember why we added the 1.8 dependency anymore. It would take some time to figure out whether we can revert to 1.7 - it doesn't seem unreasonable, though.

> You marked it as optional and provided by it can hardly be optional if you have java imports on this API in jooq.

It definitely is optional in terms of how vanilla Java resolves classpath dependencies. Have a look at how `JooqLogger` works. We catch `NoClassDefFoundError` and similar exceptions in case Java doesn't find the dependency.

My OSGi-fu is insufficient to know whether that approach is idiomatic, or even legal, in OSGi. But from a Maven perspective, there seems to be nothing wrong with it. We obviously need the dependency to compile our own code, but users don't need it to run our code.

**Comment by lukaseder** [comment]
I wonder if `<version>[1.7.0,)</version>` would do the trick

**Comment by davsclaus** [comment]
Oh we got a bunch of osgi tricks at Apache Camel. Let me try to grab something and do a PR if possible

**Comment by lukaseder** [comment]
Thanks for the offer. However, if a Maven based solution works for you, I'd prefer that. I'm not sure if we'll be able to manage maintaining a purely OSGi-based solution in the long run

**Comment by lukaseder** [comment]
Our own integration tests don't seem to suffer from the downgrade to `[1.7.0,)`. If OSGi will pick that up automatically, then I think we got a solution.

**Comment by davsclaus** [comment]
Did a PR. I can now install and use this in Apache Karaf.

**Comment by lukaseder** [comment]
Fixed in 3.13.0. Backport scheduled for 3.12.4 (#9678)
