### ISSUE TITLE
Bad SQL generated from implicit join from within subqueries

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9674]
The integration test `org.jooq.test.H2Test.testH2ImplicitJoinFromWithinNestedScopes()` has a query with an implicit join which looks like this:

```java
create().select(T_A.A)
        .from(T_A)
        .whereExists(
            selectOne()
            .from(T_B1)
            .where(T_B1.B1.eq(T_A.tB1().B1))
        )
        .orderBy(T_A.A)
        .fetch();
```

The SQL that gets rendered for H2 looks like this:

```sql
select "PUBLIC"."T_A"."A"
from (
  "PUBLIC"."T_A"
    left outer join "PUBLIC"."T_B1" "alias_19730471"
      on "PUBLIC"."T_A"."B1" = "alias_19730471"."B1"
  )T_A"
    left outer join "PUBLIC"."T_B1" "alias_19730471"
      on "PUBLIC"."T_A"."B1" = "alias_19730471"."B1"
  )
where exists (
  select 1 "one"
  from "PUBLIC"."T_B1"
  where "PUBLIC"."T_B1"."B1" = "alias_19730471"."B1"
)
order by "PUBLIC"."T_A"."A"
```

Apart from the schema qualifier in the `SELECT` clause there is also this weird fragment `)T_A"` which is a syntax error.

**Comment by lukaseder** [comment]
Regression was introduced with https://github.com/jOOQ/jOOQ/issues/8315, specifically, reverting https://github.com/jOOQ/jOOQ-pro/commit/1c37b19ee25c4eded842dbf9e444436cb2b7481c fixes the issue.

Will analyse in detail.

**Comment by lukaseder** [comment]
On the other hand, reverting will fail `ScopeStackTest.testIterator()`

**Comment by lukaseder** [comment]
The problem is that we're now replacing SQL strings recursively for some reason. I.e. in the failing test query:

```java
create().select(T_A.A)
        .from(T_A)
        .whereExists(
            selectOne()
            .from(T_B1)
            .where(T_B1.B1.eq(T_A.tB1().B1))
        )
        .orderBy(T_A.A)
        .fetch();
```

`T_A` is replaced by `("PUBLIC"."T_A" left outer join "PUBLIC"."T_B1" "alias_19730471" on "PUBLIC"."T_A"."B1" = "alias_19730471"."B1")` twice

**Comment by lukaseder** [comment]
The problem is that `ScopeStack.iterator()` behaviour has changed. The current behaviour is correct (we iterate everything that's visible in the current scope), but the implicit join algorithm depended on the previous behaviour (we iterate only what's on the same scope level).

The fact that we're iterating all scope levels leads to the `T_A` reference being patched:

1. When we leave the nested select scope level (this should not be done)
2. When we leave the outer select scope level (this is correct)

**Comment by lukaseder** [comment]
It seems to suffice to remember the `ScopeStack.scopeLevel` when creating the `ScopeStackElement`, and to then check if the `subqueryLevel() == ScopeStackElement.scopeLevel` prior to replacing any SQL

**Comment by lukaseder** [comment]
So, not strictly a regression caused by #8315, just a pre-existing bug that was cancelled by the iteration bug.

**Comment by lukaseder** [comment]
Since we will not backport #8315, this bug only manifests in the not yet released version 3.13, no backport needed.

**Comment by knutwannheden** [comment]
The commits which were integrated in the scope of #8315 are also part of 3.12, so I believe we should backport this fix to the 3.12 branch. See #9745 for example.

**Comment by lukaseder** [comment]
You're right. I'll check how easy this will be... It looks like this fix doesn't really depend much on the `ScopeStack` refactorings...

**Comment by lukaseder** [comment]
Backport scheduled for 3.12.4 (#9749)
