### ISSUE TITLE
Add SQLDialect.SQLITE_3_30

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9682]
On 2019-10-04 SQLite 3.30 was released. Some useful features:

- [x] #9778 Native `NULLS [ FIRST | LAST ]` support
- [x] #9779 Native `FILTER` clause on aggregate functions. 

For details see https://www.sqlite.org/releaselog/3_30_1.html.

**Comment by lukaseder** [comment]
There's a version 3.30.1 of the `org.xerial:sqlite-jdbc` driver, which we could use: https://search.maven.org/artifact/org.xerial/sqlite-jdbc/3.30.1/jar

I'll check if we can integration test this functionality already.
