### ISSUE TITLE
Generate.globalTableReferences should not impact what is returned by Schema#getTables()

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9685]
If the generator is run with `Generate.globalTableReferences = false` the generated `Schema#getTables()` method currently returns an empty list.

The documentation on this setting isn't very clear, but I would only have expected it to control whether the generated `Schema` and or `Tables` class declare Java fields corresponding to the tables, but `Schema#getTables()` to remain unaffected.

**Comment by lukaseder** [comment]
Good discovery! The flags `Generate.globalXYZ` should prevent the generation of auxiliary files like `Tables.java`, which are not strictly necessary. `Tables.java`, for example, references a pre-existing singleton table reference from each table for the schema. The `Schema::getTables` method could reference those instances directly in generated code, without any side-effect.

**Comment by lukaseder** [comment]
Not all `globalXYZ` flags are the same (currently). In some cases, the global reference is all there is, e.g. with sequences, queues, links.

**Comment by lukaseder** [comment]
Interestingly, the generated code is already working this way, so this is merely a matter of removing a check for `globalXYZ`. Tables and UDTs are affected.

**Comment by lukaseder** [comment]
Fixed in jOOQ 3.13.0. Backport scheduled for 3.12.4 (#9691)
