### ISSUE TITLE
Issue in alter table column with postgreSQL

### ISSUE THREAD

**Issue by Nhoutain** [jOOQ/jOOQ#9688]
### Your question:

Is there anyway to hack JOOQ when there is an column update from TEXT to NUMBER for example.

The issue is: 
```
Caused by: org.postgresql.util.PSQLException: ERROR: column "b" cannot be cast automatically to type numeric
  Hint: You might need to specify "USING b::numeric(19,5)".
  Where: SQL statement "alter table "flows"."flow_d3e382c085db40b4a2fb7972a11c85ed" alter "b" type numeric(19, 5)"
PL/pgSQL function inline_code_block line 1 at SQL statement
```

Indeed, in postgreSQL you need to add `USING column_name::numeric(19, 5)`

Is there any way to perform this in an elegant way? I miss something or there is current limitation on postgreSQL? 

If there is limitation, do you have any idea to hack it or may be a work around? 

### Versions:

- jOOQ: 3.11	
- Java: 8
- Database (include vendor): postgreSQL
- OS: Linux mint 19
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your message.

Currently, we do not support this PostgreSQL specific `USING` clause (see #issues). We'll implement this in the near future in the context of supporting such commands on more dialects that have issues with altering column types.

For the time being, you could generate the clause using an `ExecuteListener`, using regular expression search replace. E.g.:

```
-- search
alter ("?\w+"?) type ([a-zA-Z0-9, ()]+)

-- replace
$0 using $1::$2
```

I'm probably overlooking a few edge cases, but you get the idea
