### ISSUE TITLE
Updating from 3.9.X to 3.12.X breaks

### ISSUE THREAD

**Issue by SElab2019** [jOOQ/jOOQ#9699]
When I try to upgrade jooq from 3.9.X to version after 3.10.X. The following code breaks.

```
public class Demo extends UpdatableRecordImpl<AuthorRecord> implements Record3<Integer, String, String> {

	public Demo(Table<AuthorRecord> table) {
		super(table);
		// TODO Auto-generated constructor stub
	}

	@Override
	public Row3<Integer, String, String> fieldsRow() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Row3<Integer, String, String> valuesRow() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Field<Integer> field1() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Field<String> field2() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Field<String> field3() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Integer value1() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String value2() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public String value3() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Record3<Integer, String, String> value1(Integer value) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Record3<Integer, String, String> value2(String value) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Record3<Integer, String, String> value3(String value) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Record3<Integer, String, String> values(Integer t1, String t2, String t3) {
		// TODO Auto-generated method stub
		return null;
	}

}
```

The code should pass, but it throws an error:
```
[ERROR] /Demo.java:[10,8] jooq.generated.tables.records.Demo is not abstract and does not override abstract method component3() in org.jooq.Record3
```

**Comment by lukaseder** [comment]
Thank you very much for your report. Please re-generate your code every time you upgrade to the next minor release.

I hope this helps

**Comment by SElab2019** [comment]
> Thank you very much for your report. Please re-generate your code every time you upgrade to the next minor release.
> 
> I hope this helps

Thanks for your helping. Do you think this is a backwards incompatibility issue?

**Comment by lukaseder** [comment]
> Do you think this is a backwards incompatibility issue?

Our general stance on backwards compatibility is documented here:
https://www.jooq.org/doc/latest/manual/getting-started/semantic-versioning

We'll add a paragraph explaining the expectation of matching versions of the library and generated code.

Generated code depends on internal API, which we want to be able to change incompatibly between minor releases. Since we've chosen an inheritance based approach to generating code (as opposed to an annotation based approach), it would be very difficult to proceed in a more backwards compatible fashion in this area.
