### ISSUE TITLE
Generated DAO not respecting DEFAULT value from schema when inserting a POJO

### ISSUE THREAD

**Issue by mbayealioune** [jOOQ/jOOQ#9704]
### Your question:

Hi Guys,

I am running into this issue that is normally solved already... https://github.com/jOOQ/jOOQ/issues/2700

I am using the generated DAO to make an insertion into the DB, the generated SQL is : 

`insert into "internal_schema"."address" ("address", "city", "state", "postalcode", "country", "visibility", "removal_date", "address_id") values ('Eco Space, bellandur', 'Bangalore', null, '560103', 'IN', null, null, 2) returning "internal_schema"."address"."address_id"`

The generated code source is : 

```
/**
     * The column <code>internal_schema.address.state</code>.
     */
    public final TableField<AddressRecord, String> STATE = createField(DSL.name("state"), org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");
```

in the schema I have:

```
CREATE TABLE internal_schema.address (
	address varchar DEFAULT '',
	city varchar DEFAULT '',
	state varchar DEFAULT '',
	postalcode varchar DEFAULT '',
	country varchar DEFAULT '',
	visibility internal_schema.visibility_type NULL DEFAULT 'VISIBLE'::visibility_type,
	removal_date date NULL,
	address_id serial NOT NULL,
	inserted_at timestamp NOT NULL DEFAULT now(),
	CONSTRAINT address_pkey PRIMARY KEY (address_id)
);
```
My problem is the DAO is not respecting the default value, instead it is inserting a NULL value.
Did I miss something ?

### Versions:

- jOOQ: 3.12
- Java: 11
- Database (include vendor): Postgres 12
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): jdbc.postgresql.version 42.2.6
- Using spring boot 2.1.8.RELEASE with jooq starter

**Comment by mbayealioune** [comment]
According to this https://www.jooq.org/doc/3.12/manual/sql-execution/crud-with-updatablerecords/simple-crud/ : 

> jOOQ sets only modified values in INSERT statements or UPDATE statements. This allows for default values to be applied to inserted records, as specified in CREATE TABLE DDL statements.

I tried this : 
`        AddressRecord addressRecord =  dslContext.newRecord(AddressTable.ADDRESS, addressPojo);
        addressRecord.store();`

And it is still the same result

**Comment by lukaseder** [comment]
Thank you very much for your message. Your case differs subtly from #2700, which you have linked. In #2700, we fixed the behaviour of inserting `NULL` through a `DAO` when the defaulted column is `NOT NULL`. In your case, however, the defaulted column is nullable. Unfortunately, in a Java POJO, there is no way to distinguish between:

- `null` meaning you want the value to be `null`
- `null` meaning you did not initialise the value explicitly

The `org.jooq.Record` type can distinguish between the two semantics of `null` through its `Record.changed()` flags. The POJO cannot, and DAOs are POJO based, meaning that a `null` value in a POJO will translate to an explicit, "desired" `null` value in the `Record`.

The same is true for `DSLContext.newRecord(Table, Object)`. There is no way to distinuish between the two ways of interpreting the POJO's `null` values, if the column is nullable.

If `NULL` is an undesired value in your table, why not make the columns `NOT NULL`?

**Comment by lukaseder** [comment]
Notice, a workaround can be implemented easily using a `RecordListener`, which overrides the `null` values again by using `Record.reset(Field)` on all changed fields whose value is `null`.

**Comment by mbayealioune** [comment]
That makes sense! 
The only way to fall back to the default value from a POJO perspective is by telling that the column cannot be null.
I will consider making my column not nullable.
Thank you for the detailed answer.
