### ISSUE TITLE
Wrong VERSION in maven-install.[sh|bat] of jOOQ 3.11.12

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9713]
The `VERSION` variable in the `maven-install.sh` and `maven-install.bat` scripts of the jOOQ 3.11.12 release ZIP archive has the wrong value of `3.11.11` (rather than `3.11.12`). As a result the scripts cannot be executed correctly.

As a workaround the scripts need to be edited manually:

* For `maven-install.sh` replace the second line `VERSION=3.11.11` with `VERSION=3.11.12`.
* For `maven-install.bat` replace the second line `set VERSION=3.11.11` with `set VERSION=3.11.12`.

**Comment by knutwannheden** [comment]
Note: This bug cannot really be fixed. All we can do is to release 3.11.13 as a replacement.

**Comment by lukaseder** [comment]
> Note: This bug cannot really be fixed. All we can do is to release 3.11.13 as a replacement.

Since this only affects the ZIP file, which is published on our website, and not on Maven Central, we could fix this for 3.11.12, too.

I do agree we should eventually release 3.11.13 as well, though.

**Comment by knutwannheden** [comment]
> Since this only affects the ZIP file, which is published on our website, and not on Maven Central, we could fix this for 3.11.12, too.

Yes, I didn't even think of that!

**Comment by lukaseder** [comment]
> Yes, I didn't even think of that!

Which is good, because this is monkey patching :) Possible only in very exceptional cases.

**Comment by knutwannheden** [comment]
I've fixed the jar files (pro, pro-java-6, and trial) and uploaded them to all mirrors.
