### ISSUE TITLE
Render DSL.currentDate() as TRUNC(CURRENT_DATE) in Oracle

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9715]
For Oracle it would probably make more sense to render `DSL#currentDate()` as `TRUNC(CURRENT_DATE)` rather than `TRUNC(SYSDATE)`, as the latter is based on the server time zone and not the session time zone. For comparison `DSL#currentTimestamp()` uses `CURRENT_TIMESTAMP` (and not `SYSTIMESTAMP`).

**Comment by lukaseder** [comment]
This might turn out to be a quite significant, possibly backwards incompatible change for existing users. I prefer not to tackle this in isolation.

I agree there is room for fixing things in this area, especially to make standard looking API also standard compliant. But for Oracle-only users, the regression risk seems higher in this area.

**Comment by lukaseder** [comment]
There's now a related issue #10668, via which I'm revisiting this issue here again. It's still a breaking change, so I won't backport it. But after looking at things again, I don't think any other dialect exposes the behaviour of the current Oracle implementation

**Comment by lukaseder** [comment]
Implemented for jOOQ 3.15.0.

The fact that no one has mentioned this so far may hint at most people either:

- Not using this function
- Having set the session time zone to be the same as the server time zone (which isn't unreasonable)
