### ISSUE TITLE
Wrong type returned by LoaderCSVStep#fields(LoaderFieldMapper)

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9718]
The DSL API method `LoaderCSVStep#fields(LoaderFieldMapper)` should return `LoaderCSVOptionsStep` rather than `LoaderListenerStep` so that CSV specific options can be specified.

Technically the same applies to `LoaderJSONStep#fields(LoaderFieldMapper)`, but there it doesn't make much of a difference, since `LoaderJSONOptionsStep` only declares a single method, which is deprecated.

**Comment by lukaseder** [comment]
Great catch
