### ISSUE TITLE
Support MySQL ISNULL() function

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9719]
MySQL (and derived dialects) support an `ISNULL()` function (https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#function_isnull) which effectively is a synonym for the standard `IS NULL` comparison. Thus jOOQ only really has to support `ISNULL()` in the parser (in addition to SQL Server's `ISNULL()` with two-arguments).

Related issue: #9029 

According to this discussion `IS NULL` has better performance than `ISNULL()`: https://stackoverflow.com/questions/3530124/differences-between-is-null-and-isnull-in-mysql

**Comment by knutwannheden** [comment]
Next time the https://www.jooq.org/translate gets deployed the `ISNULL()` function will be supported.

**Comment by lukaseder** [comment]
I vaguely remember having considered support for this function in the API. I have not implemented it yet, as it raises a few questions, namely, should the return type of the function be `Field<Boolean>` (which it would be if MySQL supported booleans) or `Field<Integer>` (which is what MySQL currently implements).

There is no clear winner as another dialect might support a similar function with a slightly different semantics, here's one example where the semantics could differ subtly: https://github.com/jOOQ/jOOQ/issues/9029

Before we introduce support for this in the parser and/or in the API, I'd like to be sure we won't have any conflicts in the future. I'm still afraid that an implementation might not be forward compatible.

**Comment by knutwannheden** [comment]
> Before we introduce support for this in the parser and/or in the API, I'd like to be sure we won't have any conflicts in the future. I'm still afraid that an implementation might not be forward compatible.

I did already introduce the parser support, but we can of course easily revert that again.

**Comment by lukaseder** [comment]
> I did already introduce the parser support, but we can of course easily revert that again.

I now you did. I didn't mean for this to be reverted, necessarily, but since this is already being worked on, I'd like to see an analysis of similar functionality in most dialects, such as MS Access, to be *sure* this isn't causing any weird conflicts if some dialect exists that behaves slightly differently.

This is just me being cautious as `ISNULL` seems like a rather generic identifier, which could easily have overloaded, conflicting meaning.

**Comment by knutwannheden** [comment]
PostgreSQL has a non-standard `ISNULL` (and `NOTNULL`) [comparison operator](https://www.postgresql.org/docs/current/functions-comparison.html), which can be used as equivalent alternatives to `IS NULL` and `IS NOT NULL`. E.g. `a ISNULL` or `a NOTNULL`.

**Comment by lukaseder** [comment]
> PostgreSQL has a non-standard `ISNULL` (and `NOTNULL`) [comparison operator](https://www.postgresql.org/docs/current/functions-comparison.html), which can be used as equivalent alternatives to `IS NULL` and `IS NOT NULL`. E.g. `a ISNULL` or `a NOTNULL`. See #9722.

That doesn't look like something we should support very urgently...
