### ISSUE TITLE
Emulate ALTER TABLE .. RENAME COLUMN in MySQL 5.7

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9724]
MySQL 5.7 does not yet have the `ALTER TABLE ... RENAME COLUMN` clause and this must instead be done using `ALTER TABLE ... CHANGE COLUMN` (which then also requires the full column definition :cry:).

**Comment by lukaseder** [comment]
We can emulate this eventually as we'll have the column definition available in the case where we manage the entire schema through DDL interpretation.

I was actually thinking of including this particular feature as a nice show case for 3.13 DDL interpretation.

**Comment by lukaseder** [comment]
We can't really assume we know the correct definition of the entire column in an `ALTER TABLE` statement. Given that MySQL 8 supports `RENAME COLUMN` natively, and that no one has asked for this feature yet, let's reject it.
