### ISSUE TITLE
Change default value of <generatedAnnotation/> to "false"

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9732]
Generated code, by default, contains a `javax.annotation.Generated` (Java 8 and less) or `javax.annotation.processing.Generated` (Java 9+) annotation, which contains a bit of information about:

- The fact that jOOQ generated the class
- The jOOQ version that generated the class
- The catalog and schema version if provided by relevant SPIs
- The timestamp of code generation

While the catalog and schema versions can be useful to prevent re-generation of generated code when the underlying schema version has not changed (e.g. provided by Flyway), the code generation timestamp in particular is quite annoying when generated code is being checked in. It also prevents incremental compilation for no good reason, as file content will always have changed because of this timestamp, even if the rest of the file remains untouched.

The presence of schema version provider or catalog version provider configurations will continue to enforce the generated annotation, so user code will probably not break, unless users wrote their own annotation processing.

**Comment by lukaseder** [comment]
See the example from the manual:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-annotations/

```xml
<configuration xmlns="http://www.jooq.org/xsd/jooq-codegen-3.16.5.xsd">
  <generator>
    <generate>
      <generatedAnnotation>true</generatedAnnotation>
      <generatedAnnotationType>DETECT_FROM_JDK</generatedAnnotationType>
      <!-- This: -->
      <generatedAnnotationDate>true</generatedAnnotationDate>
      ...
```

**Comment by ZhorzhWins** [comment]
I see it is being set to true? 

I'm trying to understand better the problem with timestamps that led to the default being changed

**Comment by ZhorzhWins** [comment]
Ahh maybe that's the reason:
> generatedAnnotationDate = true
