### ISSUE TITLE
Support qualified asterisk on unaliased JoinTables

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9743]
The following example:
```java
Table<?> joined = A.join(B).on(A.ID.eq(B.ID));
ctx.select(joined.asterisk()).from(joined);
```
will currently be rendered as:
```sql
select a
  join b
    on "a"."a_id" = "b"."a_id".*
from a
  join b
    on "a"."a_id" = "b"."a_id"
```
This of course doesn't make any sense. Correct would be:
```sql 
select a.*, b.*
from a
  join b
    on "a"."a_id" = "b"."a_id"
```

**Comment by katzyn** [comment]
In the SQL Standard `SELECT * FROM A JOIN B USING(A_ID)` includes `COALESCE(A.A_ID, B.A_ID)` and all other columns from the both tables. Non-standard `A.*, B.*` includes `A_ID` twice as `A.A_ID` and `B.A_ID`, so it doesn't look like a correct implementation.

**Comment by lukaseder** [comment]
> In the SQL Standard `SELECT * FROM A JOIN B USING(A_ID)` includes `COALESCE(A.A_ID, B.A_ID)` and all other columns from the both tables. Non-standard `A.*, B.*` includes `A_ID` twice as `A.A_ID` and `B.A_ID`, so it doesn't look like a correct implementation.

Sure, that's a caveat, but I think it's not strictly related to this. It already has an issue: https://github.com/jOOQ/jOOQ/issues/2808

**Comment by lukaseder** [comment]
I've updated the issue description to avoid using `using()`, which distracts from the actual goal here.

**Comment by lukaseder** [comment]
Looking into this now. The syntax used in this issue here is about unaliased `JoinTables`, in case of which the nested correlation names are still defined, and can be dereferenced.

Another case would be when the `JoinTable` was aliased as follows:

```java
Table<?> joined = A.join(B).on(A.ID.eq(B.ID)).as("joined");
ctx.select(joined.asterisk()).from(joined);
```

This should produce 

```sql
select joined.*
from (a join b on a.id = b.id) as joined
```

I'll treat this separately: https://github.com/jOOQ/jOOQ/issues/14308
