### ISSUE TITLE
Field.contains uses || operator instead of concat function in condition generation 

### ISSUE THREAD

**Issue by susaiarul** [jOOQ/jOOQ#9746]
The method Field#contains(T value) escapes % and _ using replace function and concatenates the result with % using || operator. This is not working in MySQL database.

E.g: 
`(
  priority like ('%' || replace(
    replace(
      replace(
        'High', 
        '!', 
        '!!'
      ), 
      '%', 
      '!%'
    ), 
    '_', 
    '!_'
  ) || '%') escape '!'
)`

This is applicable for startsWith, endsWith, notContains method also. 

I have configured the SqlDialect in the properties file as shown below, verified the dialect in the configuration by inspecting DSLContext. 
spring.jooq.sql-dialect = MYSQL

### Versions:

- jOOQ: 3.12.3
- Java: 1.8
- Database (include vendor): MySQL 8.0.18
- OS: Ubuntu 16.4
- JDBC Driver (include name if inofficial driver): com.mysql.cj.jdbc.Driver

**Comment by knutwannheden** [comment]
For MySQL jOOQ correctly renders the string concatenation operation as `CONCAT()`. Thus to me it looks like your `spring.jooq.sql-dialect = MYSQL` configuration doesn't end up getting "propagated" correctly. Please verify this by setting a breakpoint where your query gets executed and inspect the value of the `DSLContext` object's `configuration.dialect` field. So somehow your Spring configuration isn't getting loaded / applied correctly.

Please reopen if I missed something.

**Comment by susaiarul** [comment]
@knutwannheden  @lukaseder  Thanks for the reply. MYSQL jOOQ generates the condition correctly with concat function when it is built like below:
`@Autowired private lateinit var jooqDsl: DSLContext
jooqDsl.select(field("id")).from(table("test_table"))
                    .where(field("test_column").startsWith("test_value"))`

But my use case is different. I have to construct the condition and persist it for later execution. So i am creating the condition as below, || operator is used instead of concat function here.

`val condition = DSL.field("test_column").startsWith("test_value")`

**Comment by knutwannheden** [comment]
I see. In this case you shouldn't really be using `Object#toString()` but instead `DSLContext#render(QueryPart)`:
```kotlin
val condition = field("test_column").contains(value)
val s1 = jooqDsl.select(field("id")).from("test_table").where(condition)
val s2 = jooqDsl.select(field("id")).from("test_table").where(jooqDsl.render(condition))
```

**Comment by susaiarul** [comment]
@knutwannheden Thank you very much for the answer. In my case, the condition will be persisted for later execution, so I use `DSLContext#renderInlined(QueryPart part)`.

**Comment by lukaseder** [comment]
@susaiarul I'm very curious to learn about this particular use-case of yours. If you have some time, I'd love to hear why you're storing SQL string fragments in the database. Also, I have a feeling that you may be interested in using the parser when you restore those fragments, i.e. via `DSLContext.parser()`.

**Comment by susaiarul** [comment]
@lukaseder The use case is to implement the rule engine. A rule can be defined as perform some action when a condition is matches on an entity. The rule can be executed in future at some point in time say after 7 days since the entity is created. The condition will be evaluated and action will be performed if the condition matches during that event. So, the condition given by the user will be persisted in the database for future use.
In my case, i form the condition using jOOQ and store it in the database. When the event occurs, the condition (as string) will be retrieved then Condition instance will be constructed as below which will be provided to Select.
```kotlin
val conditionStr = ... //fetched from DB
val condition = field("created_time").lessOrEqual(x)
condition = condition.and(conditionStr)`

**Comment by lukaseder** [comment]
Very interesting, thanks for sharing, @susaiarul. Definitely something to keep in mind for a future project, where we re-design the internal query object model. I've always been thinking if we should provide a non SQL string way to serialise our object model in a SQL and dialect agnostic way, for purposes like these.
