### ISSUE TITLE
How to persist Condition for later execution.

### ISSUE THREAD

**Issue by susaiarul** [jOOQ/jOOQ#9750]
The use case is to construct the Condition and persist it in the database for later execution. I have constructed the condition and store it as string. 

When execute it later, generated condition using below listed methods uses || instead of concat function in MySQL since the condition given as string to SelectSelectStep#where method. But it works when Condition instance is given to SelectSelectStep#where method.

Field#contains
Field#notContains
Field#startsWith
Field#endsWith

Before asking your question, please check out the FAQ too: https://www.jooq.org/faq

### Versions:

- jOOQ: 3.12.3
- Java: 1.8
- Database (include vendor): MYSQL 8.0.18
- OS: 16.4
- JDBC Driver (include name if inofficial driver): com.mysql.cj.jdbc.Driver

**Comment by lukaseder** [comment]
Thank you very much for your message.

I believe this already has an answer here: https://github.com/jOOQ/jOOQ/issues/9746#issuecomment-576278465
