### ISSUE TITLE
Change DEFAULT rendering of CURRENT_DATE, CURRENT_TIME, and CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9753]
In the SQL standard the built-in functions `CURRENT_DATE`, `CURRENT_TIME`, and `CURRENT_TIMESTAMP` are used without a trailing parenthesis pair (i.e. not like e.g. `CURRENT_DATE()`). jOOQ should use this syntax from the SQL standard for the `DEFAULT` dialect.

**Comment by lukaseder** [comment]
I'm fine with that.

**Comment by lukaseder** [comment]
Doing this in a broader context of changing the behaviour of `SQLDialect.DEFAULT`: https://github.com/jOOQ/jOOQ/issues/9085
