### ISSUE TITLE
SQLite onConflict() issues.

### ISSUE THREAD

**Issue by xXkguyXx** [jOOQ/jOOQ#9759]
### Expected behaviour and actual behaviour:

For the following methods:

.onConflict().doUpdate()
.onConflict().doNothing()
.onDuplicateKeyUpdate()
.onDuplicateKeyIgnore()

The actual behaviour is

> jooq.exception.DataAccessException: SQL [insert into testing (name, age) values (?, ?) on conflict ([unknown primary key]) do update set age = ?]; [SQLITE_ERROR] SQL error or missing database (near "on": syntax error)

but the expected behaviour should be that is updates if there is a conflict and all that.

### Versions:

- jOOQ: 3.12.3
- Java: 1.8
- Database (include vendor): SQLite (JDBC)
- OS: Debian
- JDBC Driver (include name if inofficial driver): SQLite

**Comment by xXkguyXx** [comment]
Please note that I am using this as a builder (not using the class generation system).

**Comment by lukaseder** [comment]
Thank you very much for your report. Can you please show the exact jOOQ client code you were using to produce any issues you've encountered?

**Comment by xXkguyXx** [comment]
https://hastebin.com/ejesacaqub.cs

**Comment by lukaseder** [comment]
Thank you. I'll try reproducing this soon.

**Comment by lukaseder** [comment]
I've removed one of the two primary keys in your test table and could then reproduce the case.

The easiest fix is to pass the primary key column to the `onConflict` clause:

```java
create.insertInto(
        table,
        nameField, DSL.field("age"))
        .values("kguy", 5)
        .onConflict(nameField).doUpdate().set(DSL.field("age"), 6)
        .execute();
```

Notice the documentation:
https://www.sqlite.org/lang_UPSERT.html

> The conflict target is required for DO UPDATE upserts, but is optional for DO NOTHING

This works well, for example:

```java
create.insertInto(
        table,
        nameField, DSL.field("age"))
        .values("kguy", 5)
        .onConflict().doNothing()
        .execute();
```

I hope this helps!
