### ISSUE TITLE
Data not viewable in transaction after store and refresh called

### ISSUE THREAD

**Issue by demichej** [jOOQ/jOOQ#9763]
### Your question:

Hi, I'm having an issue where i am thinking I'm doing something wrong, but could use some help. We are utilizing ThreadLocalTransactionProvider for transactions (with nested=false). 

I have some code that is all wrapped in a transaction. I am setting a deleted date on a Record, storing it, refreshing it, and then I am querying for it after that in the same transaction; however the record is being returned with a null deleted date. If I do the update in a transaction, and then do the query in a different transaction, then it sees the deleted date correctly set. 

Here are the commands I am attempting:

```
        foo.setDeletedDate(OffsetDateTime.now());
        foo.store();
        foo.refresh();

        create.selectFrom(FOO)
                .where(FOO.DELETED_DATE.isNull().and(FOO.BAR_ID.in(ids));

// The above incorrectly returns the foo that just had its deletedDate set
```
Now, I can get around this by doing the delete in a transaction, and then doing the query in a transaction after that....... but isn't there a way to 'flush' (yes, a Hibernate term :( ) during the transaction to have subsequent queries recognize that data change?

Thanks for your time.

### Versions:

- jOOQ: 3.12
- Java: 1.8.0_231
- Database (include vendor): Postgres 10.7
- OS: Linux
- JDBC Driver (include name if inofficial driver):42.1.1

**Comment by lukaseder** [comment]
Thank you very much for your message. Can you please show a bit more code? In particular, I'm curious to see how you're using the transaction APIs. Perhaps your `create` produces a different transaction than your `store()` call...

**Comment by demichej** [comment]
Oh man, you're dead on. Thanks @lukaseder. I was selecting + updating the object with a write context, and then selecting with a readonly context :man_facepalming: 

Thanks!

**Comment by lukaseder** [comment]
Great to hear you've been able to resolve it! Thanks for the feedback.
