### ISSUE TITLE
Migrating oracle 19c, which JOOQ version should be chosen?

### ISSUE THREAD

**Issue by yigongge** [jOOQ/jOOQ#9766]
### Your question:
Hello,
I can not find any information about JOOQ version and supported Oracle version.

We are now migrating to oracle 19c and which JOOQ version should be chosen?

thanks in advance!
Yi  

### Versions:

- jOOQ: ?
- Java: 1.8
- Database (include vendor): oracle 19c
- OS: windows 2016 server
- JDBC Driver (include name if inofficial driver): 1.8

**Comment by lukaseder** [comment]
Thank you very much for your message.

In general, please always use the latest jOOQ version, which currently is jOOQ 3.12.3. Most RDBMS vendors are both very forward and backward compatible. As such, we usually support all RDBMS version from all currently supported jOOQ versions. If for some reason you have to stay e.g. on jOOQ 3.10 and run into an issue on Oracle 19c, which did not exist on Oracle 12c yet, we'll fix that for you on 3.10, if possible.

You can find the supported Oracle versions on this page here:
https://www.jooq.org/legal/licensing#databases

I hope this helps.
