### ISSUE TITLE
Standardise behaviour of jOOQ-meta when a table reports two identities

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9770]
PostgreSQL (and possibly other dialects) support multiple identities per table, which should be an edge case and not best practice, but we need to be able to handle this in our code generator.

While we might not officially support this, nor allow for configuration outside of `syntheticIdentities` or similar, it should be the same, predictable behaviour in all dialects. My suggestion would be:

- [ ] To always take the first declared identity in column declaration order (column ordinal number, etc.) and ignore subsequent identities
- [ ] To log a warning when there is more than one identity

**Comment by MirkoTeran** [comment]
Is there a way to disable logging in case of multiple identities?

We also use jOOQ to get structure of user-defined databases and some of them have a lot of this and logs are flooded by 
'jOOQ does not support tables with multiple identities. Identity is ignored on column: <name>'.

While this is great for code generator, it is a bit annoying for runtime usage.

**Comment by lukaseder** [comment]
Thanks for your message, @MirkoTeran. It's always a good idea to create new issues for not strictly related topics, because then we can track your feature request instead of accidentally forgetting about it. Think of it this way. When (if) this feature is implemented, your comment is likely overlooked and we have no other way to track it, currently.

As a matter of fact, this issue here seems to be a duplicate of #5335, which has already been implemented.

To answer your specific feature request, I'm not sure if anything really needs to be done. We try logging with slf4j if it's on the classpath, otherwise with `java.util.logging`. In both APIs, you can fine-tune the log output based on the logger name being used. In this case, it's `AbstractElementContainerDefinition`

**Comment by lukaseder** [comment]
Duplicate of #5335
