### ISSUE TITLE
Generated annotation should produce HTTPS link to jOOQ website

### ISSUE THREAD

**Issue by MirkoTeran** [jOOQ/jOOQ#9796]
### Use case:

Currently code generated adds links to http version of the site. They should point to https version.

### Possible solution you'd like to see:

Replace http://www.jooq.org links with https://www.jooq.org

### Possible workarounds:

Add flag to generator to use secure or normal links.

### Versions:

- jOOQ: 3.12
- Java: -
- Database (include vendor): -
- OS: -
- JDBC Driver (include name if inofficial driver): -

**Comment by lukaseder** [comment]
Thanks for your suggestion. Agreed.

**Comment by lukaseder** [comment]
Another workaround is to turn off the `<generatedAnnotation/>` flag
