### ISSUE TITLE
Add missing @Support annotation to DSLContext#fetch*() methods

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9833]
Many of the `DSLContext#fetch*()` methods currently don't have an `@Support` annotation.

**Comment by lukaseder** [comment]
Indeed, whether or not we have the annotation is quite arbitrary. I'll add them everywhere.

**Comment by lukaseder** [comment]
N.B: They're completely absent from all `ResultQuery::fetchXYZ` methods. It's a bit unclear whethere these methods should have the annotation or not. But at least, we can have a uniform user experience per class.

**Comment by lukaseder** [comment]
Fixed in 3.14.0. Backport scheduled for 3.13.2 (#9867)
