### ISSUE TITLE
SQL exception

### ISSUE THREAD

**Issue by dumindarw** [jOOQ/jOOQ#9846]
Exception while executing meta query: (conn=93) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'where exists (select 1 as one from information_schema.TABLES where (information_' at line 1

```sql
select 1 as one
where exists (
  select 1 as one
  from information_schema.TABLES
  where (
    information_schema.TABLES.TABLE_NAME = 'proc'
    and information_schema.TABLES.TABLE_SCHEMA = 'mysql'
  )
)```

**Comment by lukaseder** [comment]
Thank you very much for your report. This is a known regression of jOOQ 3.13.0. A fix is on the way and will be released soon: https://github.com/jOOQ/jOOQ/issues/9832
