### ISSUE TITLE
Compilation error in generated code for check constraints containing bad escape sequences

### ISSUE THREAD

**Issue by arlampin** [jOOQ/jOOQ#9849]
### Expected behavior and actual behavior:
Expected jOOQ to generate valid, properly escaped Java string literals for check constraint definitions, but doesn't.

### Steps to reproduce the problem

Using Postgres table definition like
```sql
CREATE TABLE check_error (
    example TEXT PRIMARY KEY CHECK ( example ~ 'example-\d+'::TEXT )
);
```
generates invalid Java code in the table class:
```java
    @Override
    public List<Check<CheckErrorRecord>> getChecks() {
        return Arrays.<Check<CheckErrorRecord>>asList(
              Internal.createCheck(this, DSL.name("check_error_example_check"), "((example ~ 'example-\d+'::text))", true)
        );
    }
```

```
error: illegal escape character
Internal.createCheck(this, DSL.name("check_error_example_check"), "((example ~ 'example-\d+'::text))", true)
                                                                                         ^
```

### Versions:

- jOOQ: 3.13.0
- Java: OpenJDK 13
- Database (include vendor): PostgreSQL 11
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by TigiHof** [comment]
### Another example for invalid Java code generation:
Using Postgres table definition

```sql
CREATE TABLE check_error (
  a INTEGER,
  b INTEGER,
  CONSTRAINT CHK_check_error CHECK (a IS NULL OR b IS NULL)
);
```
generates invalid Java code in the table class:
```java
    @Override
    public List<Check<CheckErrorRecord>getChecks() {
        return Arrays.<Check<CheckErrorRecord>>asList(
              Internal.createCheck(this, DSL.name("CHK_CHECK_ERROR"), "((\"A\" IS NULL)
    OR (\"B\" IS NULL))", true)
        );
    }
```
```
[ERROR] CheckError.java: illegal character: '\'
```

### Versions:
* jOOQ: 3.13.0
* Java: Amazon Corretto 11.0.6
* Database: PostgreSQL 11

**Comment by lukaseder** [comment]
Thanks a lot for your report. This needs to be fixed ASAP.

You can work around the problem by excluding check constraints from code generation using

```xml
<configuration>
  <generator>
    <database>
      <includeCheckConstraints>false</includeCheckConstraints>
    </database>
  </generator>
</configuration>
```

**Comment by lukaseder** [comment]
@TigiHof Hmm, the code in your example seems to be correct. Maybe, the illegal `\` character stems from elsewhere?

**Comment by lukaseder** [comment]
This is a similar case as #3450. There are a few other locations where backslashes are not properly escaped. We'll fix them all in one go.

**Comment by lukaseder** [comment]
Fixed for jOOQ 3.14.0. Backport scheduled for 3.13.1 (#9859)

**Comment by TigiHof** [comment]
> @TigiHof Hmm, the code in your example seems to be correct. Maybe, the illegal `\` character stems from elsewhere?

No, unfortunately the code is not correct! I posted it exactly as the code generator created it, including the line break within the check condition. Of course this does not compile.

**Comment by lukaseder** [comment]
I see, thanks. I thought the line break was a github artefact.

**Comment by lukaseder** [comment]
3.13.1 has been released to Maven Central and should show up there soon. Release notes and announcement will follow later today.
