### ISSUE TITLE
How to prevent automatic casting

### ISSUE THREAD

**Issue by BrandonKowalski** [jOOQ/jOOQ#9853]
### Versions:

- jOOQ: 3.13.0
- Java: AdoptOpenJDK13
- Database: PostgreSQL 12.1
- OS: Java Application macOS 10.15.3 / PostgreSQL 12.1 Official Docker Container
- JDBC Driver: org.postgresql.postgresql:42.2.10

This question is very similar to #1659.

I have a field with the type int4range[]. On insert, I receive the following exception: 

`org.postgresql.util.PSQLException: ERROR: syntax error at or near "any"`

I set my logger to debug to examine the generated SQL. Like #1659, JOOQ is attempting to cast this `"field_name" = ?::any[]`

#1659 referenced `Factory.field(String)` as a means to stop this casting. This has been deprecated. What is the correct way in which to stop this casting?

**Comment by lukaseder** [comment]
Thank you very much for your message.

Currently, you cannot stop our automatic casting for arbitrary data types. In PostgreSQL, explicit casts are required in a variety of cases, so by default, jOOQ often generates these.

You can, however, implement a data type binding for your `int4range[]` type, and usea that in your generated code:
https://www.jooq.org/doc/latest/manual/sql-building/queryparts/custom-bindings

I hope this helps

**Comment by BrandonKowalski** [comment]
Thanks! I’ll give that a shot!
