### ISSUE TITLE
Add support for DB2 DIGITS() function

### ISSUE THREAD

**Issue by bestdnd** [jOOQ/jOOQ#9854]
Source:

```sql
select digits(column1) from mytable
```

Tells me that "digits" is not a known function, but AS400 does recognize it.
The function formats a numeric value with leading and trailing zeros according to the column type and without decimal point. It's useful for converting to string while keeping the ability to sort lexicographicaly.

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. That seems like a useful function, indeed. Documentation for reference:
https://www.ibm.com/support/knowledgecenter/SSEPGG_11.1.0/com.ibm.db2.luw.sql.ref.doc/doc/r0000795.html

We could certainly emulate this function, too.
