### ISSUE TITLE
Row#ge(), Row#lt(), and Row#le() broken

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9855]
Due to the implementation of `RowSubqueryCondition` all of `Row#gt()`, `Row#ge()`, `Row#lt()`, and `Row#le()` end up rendering the same SQL corresponding to the `gt()` case.

**Comment by lukaseder** [comment]
It's already fixed: https://github.com/jOOQ/jOOQ/commit/a0cbf450ba2bf8b88794a7e9a352646d25c64aa7

**Comment by lukaseder** [comment]
Marked as "worksforme". I think this is not release notes worthy.
