### ISSUE TITLE
Liquibase imports should use ClassLoaderResourceAccessor 

### ISSUE THREAD

**Issue by paulius-p** [jOOQ/jOOQ#9866]
### Use case:

I've been looking forward to Liquibase support in jOOQ! That's a great addition!

Just noticed that by default it uses `FileSystemResourceAccessor`, which needs you to define all the migrations in absolute paths (or use `relativeToChangelogFile` flag everywhere, but even then in some cases it won't suffice). And that's not desirable, as usually you don't want to have absolute paths in you migrations file.

The default behaviour in Liquibase is to use `ClassLoaderResourceAccessor`:

https://github.com/liquibase/liquibase/blob/01b3899923e0dbd3d52e14f0bf145732c3c18a68/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseMojo.java#L433
https://github.com/liquibase/liquibase/blob/01b3899923e0dbd3d52e14f0bf145732c3c18a68/liquibase-core/src/main/java/liquibase/Scope.java#L99

And in `liquibase-maven-plugin` plugin (which is what I'm using now for generating jOOQ files) it uses `CompositeResourceAccessor`:

https://github.com/liquibase/liquibase/blob/01b3899923e0dbd3d52e14f0bf145732c3c18a68/liquibase-maven-plugin/src/main/java/org/liquibase/maven/plugins/AbstractLiquibaseChangeLogMojo.java#L91-L103

Improving this would definitely ease the effort to adopt this new Liquibase feature.

### Test case:

Configuration (in this case it doesn't even find the changelog if `${project.basedir}/` is not prefixed):
```xml
  <database>
    <name>org.jooq.meta.extensions.liquibase.LiquibaseDatabase</name>
    <properties>
      <property>
        <key>scripts</key>
        <value>${project.basedir}/src/main/resources/db/changelog/db.changelog-master.yaml</value>
      </property>
      <property>
        <key>includeLiquibaseTables</key>
        <value>false</value>
      </property>
      <property>
        <key>database.contexts</key>
        <value>default</value>
      </property>
    </properties>
    ...
  </database>
```

Migrations file:
```yaml
databaseChangeLog:
  - context: default
  - include:
      - file: db/changelog/v1-0-0/db.changelog.yaml
  - include:
      - file: db/changelog/v1-1-0/change-some-columns.yaml
```

### Versions:

- jOOQ: 3.13.1
- Java: 11
- Database (include vendor): H2
- OS: Linux
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. Uniform path descriptors do seem to be an unsolved problem in the Java ecosystem...

There's probably room for improvement here, but I personally don't find the `${basedir}` prefix such a bad approach.

Notice the `LiquibaseDatabase` is in the `jOOQ-meta-extensions` module, which does not know anything about it possibly being used in Maven. Since Maven already supports resolving relative paths to absolute ones very cleanly using these properties, I think this is the cleanest approach.

But we might consider an improvement through a more generic approach, which affects all of our utilities, not just the `LiquibaseDatabase`

**Comment by paulius-p** [comment]
Yes, but the `${basedir}` only solves the root `changeLog` file discovery all the other referenced migrations will error out as not found, and you cannot prefix them with the `${basedir}` as it won't be substituted.

**Comment by lukaseder** [comment]
I see, thanks for clarifying.

**Comment by lukaseder** [comment]
Hmm, I'm getting the expected results using this:

```java
new CompositeResourceAccessor(
    new FileSystemResourceAccessor(),
    new ClassLoaderResourceAccessor(),
    new ClassLoaderResourceAccessor(Thread.currentThread().getContextClassLoader())
),
```

The first `ClassLoaderResourceAccessor` is used for standalone code generator usage (via `GenerationTool::main`), and the second one uses our jOOQ Maven Plugin classloader, which is placed in the current thread's context class loader.

I'll commit soon. Would be happy to get early feedback, if you have time.

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.14.0. Backport scheduled for 3.13.2 (#9878)

**Comment by Fadelis** [comment]
Thanks for the quick look! Just compiled it and tested it and yes, it works now as expected.
Just note that for the scripts property you need to prefix it with `${project.basedir}/`, so would need to make sure to update documentation and examples, since it not used there.

**Comment by lukaseder** [comment]
That would be confusing to non-maven users. As mentioned before, it's not the only place in the manual where we use paths, relative or not, so I'm not sure we should have this `${basedir}` variable in our XMLs

**Comment by lukaseder** [comment]
This stuff regresses again, it seems, see https://github.com/jOOQ/jOOQ/issues/12872, https://github.com/jOOQ/jOOQ/issues/13021
