### ISSUE TITLE
LiquibaseDatabase should use configured changeLogParameters.contexts when updating

### ISSUE THREAD

**Issue by Fadelis** [jOOQ/jOOQ#9872]
### Use case:

Currently liquibase `contexts` parameter is not applied correctly as it is not a database property and needs to be passed to the `database.update(String)` method to work correctly.

### Possible solution you'd like to see:

Include explicit `contexts` property and pass it to the `update` method

### Versions:

- jOOQ: 3.13.1
- Java: 11
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your suggestion. I agree that this `contexts` string would be a useful property to pass along.

I will comment on your commit

**Comment by lukaseder** [comment]
Implemented in jOOQ 3.14.0. Backport scheduled for 3.13.2 (#9876).

Thanks again!
