### ISSUE TITLE
LiquibaseDatabase should use actual changeLog database table names

### ISSUE THREAD

**Issue by Fadelis** [jOOQ/jOOQ#9873]
### Expected behavior and actual behavior:

Currently when excluding liquibase `changeLog` tables, static table name values are used, but those might be overridden by the configuration setters.

### Versions:

- jOOQ: 3.13.1
- Java: 11
- Database (include vendor):
- OS:
- JDBC Driver (include name if inofficial driver):

**Comment by lukaseder** [comment]
Thanks a lot for your suggestion. Agreed, that currently doesn't work correctly for non-out-of-the-box configurations.

**Comment by lukaseder** [comment]
Integrated in jOOQ 3.14.0. Backport scheduled for 3.13.2 (#9877).

Thanks again!
