### ISSUE TITLE
Deprecate SQLDialect#supports(Collection<SQLDialect>) method

### ISSUE THREAD

**Issue by knutwannheden** [jOOQ/jOOQ#9882]
The `SQLDialect#supports(Collection<SQLDialect>)` method will be deprecated in favor of the newer alternatives `supportedBy()` and `supportedUntil()`, which have names and Javadoc with clearer semantics and can be used for the same purposes.

**Comment by lukaseder** [comment]
Is this something worth adding to the refaster templates?

**Comment by knutwannheden** [comment]
> Is this something worth adding to the refaster templates?

I also thought about this. Somehow I doubt anybody is using this method, but we could of course offer a migration anyway.

**Comment by lukaseder** [comment]
Yes please.

Am Donnerstag, 27. Februar 2020 schrieb Knut Wannheden <
notifications@github.com>:
