### ISSUE TITLE
Custom generator does not work with programmatic configuration

### ISSUE THREAD

**Issue by fabianskii** [jOOQ/jOOQ#9883]
Heya!
While refactoring a generator configuration from schematic to programmatic, I came across the following question/issue.

My custom generator works fine when using a schematic configuration in the .pom xml. The generators skeleton looks like this:
``` 
import org.jooq.codegen.JavaGenerator;
[..]
public class CustomGenerator extends JavaGenerator { [..] }
```

> (from https://www.jooq.org/doc/3.13/manual/code-generation/codegen-custom-code/ )

To my understanding, when using a programmatic configuration, it should be done like this:
```
import com.company.product.common.sql.CustomGenerator;
testConfig = new Configuration()
                .withJdbc(new Jdbc()
                        .withDriver("org.postgresql.Driver")
                        .withUrl("jdbc:postgresql://localhost:5432/testdb")
                        .withUser("test")
                        .withPassword("test"))
                .withGenerator(new CustomGenerator());
``` 

> (from https://www.jooq.org/doc/3.13/manual/code-generation/codegen-programmatic/ )

As explained in the documentation, our custom generator extends the org.jooq.codegen.JavaGenerator. However, that clashes with the signature of .withGenerator() which expects an org.jooq.meta.jaxb.Generator. 

Can you help me with this or clarify in case I understood something wrong, please?

- jOOQ: 13.0.1
- Java: 11.0.6
- Database (include vendor): Postgres
- OS: Ubuntu 18.04
- JDBC Driver: org.postgresql.Driver

**Comment by knutwannheden** [comment]
You are almost there! You should in fact use the `org.jooq.meta.jaxb.Generator` and call `withName("fully.qualified.name.of.CustomGenerator")`.

Please reopen if I missed something.
