### ISSUE TITLE
Generate code based on greenplum schema

### ISSUE THREAD

**Issue by varsanyid** [jOOQ/jOOQ#9884]
Hey,

Is it possible to use the existing postgres support to connect to GP and generate classes?

**Comment by lukaseder** [comment]
Thank you very much for your message. We currently do not support Greenplum officially (see https://github.com/jOOQ/jOOQ/issues/4700).

It might be possible to work with the existing PostgreSQL support, but as we have seen with a lot of users who had been using e.g. Redshift or CockroachDB with the PostgreSQL, the devil is in the details, when some code generator query doesn't work on the respective "PostgreSQL compatible" product.

There are a few more vendor agnostic options in the code generator, such as the `JDBCDatabase`, which uses JDBC `DatabaseMetaData` behind the scenes to reverse engineer your schema. There are also:

- `XMLDatabase`, which reverse engineers an XML representation of your schema: https://www.jooq.org/doc/latest/manual/code-generation/codegen-xml/
- `DDLDatabase`, which parses your DDL scripts and interprets them without an actual DB connection: https://www.jooq.org/doc/latest/manual/code-generation/codegen-ddl/
- `LiquibaseDatabase`, which interprets your Liquibase migration files and produces code from that: https://www.jooq.org/doc/latest/manual/code-generation/codegen-liquibase/

I hope this helps
