### ISSUE TITLE
Compilation error in generated DAOs

### ISSUE THREAD

**Issue by callain** [jOOQ/jOOQ#9887]
Hello I am trying to upgrade our jOOQ version from 3.11.11 to 3.12.3 and I get an issue at compilation time.

I have seen some similar issues like this one: https://github.com/jOOQ/jOOQ/issues/7068
But the primary key is not a composite type

Here is a sample of a table with generates a wrong DAO: 

```
 CREATE TABLE "SCHEMA"."CONTRAT" (
    "ID" NUMBER(19,0) NOT NULL ENABLE,
    ...,
    PRIMARY KEY ("ID")
) 
```

### Expected behavior and actual behavior:

Maven code generation generates a protected method inside a DAO
```
   /**
     * {@inheritDoc}
     */
    @Override
    protected BigInteger getId(mypackages.jooq.tables.pojos.Contrat object) {
        return object.getId();
    }
```

Thus it does not compile, the error is `"attempting to assign weaker access privileges ('protected'); was 'public"`

Expected behavior is: the method should be public I guess

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

I am actually trying, but little time at the moment

### Versions:

- jOOQ: Pro 3.12.3
- Java: 11
- Database (include vendor): Oracle 12c
- JDBC Driver (include name if inofficial driver): Oracle OJDBC 19.3

**Comment by lukaseder** [comment]
Thank you very much for your report. It seems that you're using an older code generator version than the runtime library version.

In jOOQ 3.12, we pulled up the `DAOImpl.getId()` method (which was protected) to `DAO`: https://github.com/jOOQ/jOOQ/issues/7874. This means that older code needs to be re-generated with a code generator of version 3.12 as well.

I hope this helps

**Comment by callain** [comment]
Thank you for pointing the problem :)

To add a bit of feedback:

I was trying to use the maven codegen plugin from the pro version, without installing manually the dependency (in a spring boot project)

Using dependency with <scope>system</scope> and <systemPath>../lib/jooq-xx-.jar</systemPath> for both jooq and jooq-codegen-maven jars

Turned out that it messes the plugin execution. I did not find a way to specify a plugin without having it installed in my local repository

I wanted to avoid manual installation of jooq pro because its a step in our project installation for every new developer, its also necessary to manually install it in our jenkins maven repository
And doing this is necessary for each upgrade

Installing a nexus repository or equivalent just for jooq is overkill

It would be nice to have a smoother way of using jooq pro

**Comment by lukaseder** [comment]
Thank you very much for your explanations. We do have offering the commercial distributions via a Maven repository on our roadmap, but it has not been requested too many times. While it does seem convenient at first, most customers do not want to rely on external repositories for their mission critical builds, and will have local caches for Maven Central and many other repositories anyway.

I have created a new issue to collect feedback from customers to see whether this is a more popular request than we would have estimated so far: https://github.com/jOOQ/jOOQ/issues/9906

System dependencies seem like a nice workaround in Maven, but they have a few unfortunate (IMO) limitations. One such limitation is that they cannot be referenced transitively, meaning you have to add the dependency both in your project and in your code generation plugin usage. But it's totally possible to do what you were trying to do. Just be sure to use the correct Maven group ids (Open Source Edition is `org.jooq` and pro edition is `org.jooq.pro`, for example).

Also, you may want to exclude the Spring Boot transitive jOOQ dependency when you're using the jOOQ Pro Edition:
https://blog.jooq.org/2019/06/26/how-to-use-jooqs-commercial-distributions-with-spring-boot/

**Comment by callain** [comment]
`it's totally possible to do what you were trying to do`

I would love to !
But when I try something like this, (skipping the configuration part)

```
<plugin>
    <!-- Specify the maven code generator plugin -->
    <groupId>org.jooq.pro</groupId>
    <artifactId>jooq-codegen-maven</artifactId>
    <version>3.12.3</version>
    <dependencies>
        <dependency>
            <groupId>org.jooq.pro</groupId>
            <artifactId>jooq</artifactId>
            <version>3.12.3</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/jooq-3.12.3.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.jooq.pro</groupId>
            <artifactId>jooq-codegen</artifactId>
            <version>3.12.3</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/jooq-codegen-3.12.3.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.jooq.pro</groupId>
            <artifactId>jooq-codegen-maven</artifactId>
            <version>3.12.3</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/lib/jooq-codegen-maven-3.12.3.jar</systemPath>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.reactivestreams</groupId>
            <artifactId>reactive-streams</artifactId>
            <version>1.0.2</version>
        </dependency>
    </dependencies>
    <!-- The plugin should hook into the generate goal -->
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

It generates the following errror 

```
[ERROR] Plugin org.jooq.pro:jooq-codegen-maven:3.12.3 or one of its dependencies could not be resolved: Failure to find org.jooq.pro:jooq-codegen-maven:jar:3.12.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin org.jooq.pro:jooq-codegen-maven:3.12.3 or one of its dependencies could not be resolved: Failure to find org.jooq.pro:jooq-codegen-maven:jar:3.12.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
```

I believe, in theory that this should do the trick

```
<plugin>
    <!-- Specify the maven code generator plugin -->
    <groupId>org.jooq.pro</groupId>
    <artifactId>jooq-codegen-maven</artifactId>
    <version>3.12.3</version>
    <scope>system</scope>
    <systemPath>${project.basedir}/lib/jooq-codegen-maven-3.12.3.jar</systemPath>
    <dependencies>
</plugin>
```

Unfortunately, scope and systemPath are not supported in `<plugin>`, so if I don't miss something, I am stuck with manual installation

**Comment by lukaseder** [comment]
Ah yes, I forgot. This approach doesn't work well for plugins. Does specifying a local repository work for you?

https://stackoverflow.com/a/5597277/521799

**Comment by lukaseder** [comment]
Also, this solution here using the `maven-install-plugin` worked well for me, although it is a bit more laborious:
https://stackoverflow.com/a/45854379/521799
