### ISSUE TITLE
Add support for native ILIKE in H2

### ISSUE THREAD

**Issue by katzyn** [jOOQ/jOOQ#9889]
H2 supports `… [ NOT ] ILIKE … [ ESCAPE … ]` condition since version 1.4.194:
https://h2database.com/html/grammar.html#condition_right_hand_side
For older versions cast of the **left** operand to `VARCHAR_IGNORECASE` can be used (if such versions are still supported by jOOQ).

jOOQ currently generates an inefficient and not fully compatible replacement code with the `LOWER` function. Such code that can't properly handle some national letters.
```SQL
CREATE TABLE TEST(A VARCHAR(1), B VARCHAR(1)) AS VALUES ('I', 'ı');
SELECT A ILIKE B, LOWER(A) LIKE LOWER(B) FROM TEST;
> TRUE FALSE
```

**Comment by lukaseder** [comment]
Thanks a lot for your feature request. Great to know, we hadn't noticed this improvement in 1.4.194. Definitely makes sense to generate native support

> (if such versions are still supported by jOOQ)

We're currently not supporting old versions of H2. We might, in the future.

> jOOQ currently generates an inefficient and not fully compatible replacement code with the `LOWER` function. Such code that can't properly handle some national letters.

Yes, that's a known limitation of the current approach. It could be worked around using collations explicitly, but we're not doing that yet.
