### ISSUE TITLE
Add Settings to apply native JSR 310 data type binding

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOQ#9902]
When using JSR 310 data types, such as `java.time.OffsetDateTime`, jOOQ currently converts the type to a string prior to binding them to a JDBC statement using `setString()`. In many cases, `setObject()` is better, because:

- There are no implicit type conversions in the database, which may lead to parse errors (see e.g. #9886)
- There is no costly conversion to strings, which can cost a lot when may queries are executed, or many JSR 310 types are fetched

Starting from jOOQ 3.14, we should introduce a `Settings` that allows for governing how these values are sent to the JDBC driver:

- Native (assuming the driver is up to date)
- "old" (the current behaviour)

Going forward, the default should be native. The settings are:

- `Settings.bindOffsetDateTimeType`
- `Settings.bindOffsetTimeType`

The other types, like `LocalDateTime` will continue to be translated to the JDBC types like `java.sql.Timestamp`

**Comment by lukaseder** [comment]
Marking this as an incompatible change, because the new default behaviour could be cause of regressions that are not covered by our integration tests.

**Comment by lukaseder** [comment]
We could attempt to bind an `OffsetDateTime` on a system check query, and if this fails, we'll revert to the old behaviour logging a warning... I really don't feel like we should risk too many regressions in this area...

**Comment by lukaseder** [comment]
One example:

```
Caused by: org.postgresql.util.PSQLException: conversion to class java.time.OffsetTime from timetz not supported
	at org.postgresql.jdbc.PgResultSet.getObject(PgResultSet.java:3607)
	at org.jooq.tools.jdbc.DefaultResultSet.getObject(DefaultResultSet.java:1044)
	at org.jooq.tools.jdbc.DefaultResultSet.getObject(DefaultResultSet.java:1044)
	at org.jooq.tools.jdbc.DefaultResultSet.getObject(DefaultResultSet.java:1044)
	at org.jooq.impl.CursorImpl$CursorResultSet.getObject(CursorImpl.java:958)
	at org.jooq.impl.DefaultBinding$DefaultOffsetTimeBinding.get0(DefaultBinding.java:3062)
	at org.jooq.impl.DefaultBinding$DefaultOffsetTimeBinding.get0(DefaultBinding.java:1)
	at org.jooq.impl.DefaultBinding$AbstractBinding.get(DefaultBinding.java:863)
	at org.jooq.impl.CursorImpl$CursorIterator$CursorRecordInitialiser.setValue(CursorImpl.java:1715)
	... 43 more
```

It doesn't seem like pgjdbc supports `OffsetTime` for the `timetz` type.

Well then. I guess that settles it for now. I'll postpone this change. I want to release 3.14 some time soon, and this looks like it would produce a ton of new regressions.

**Comment by lukaseder** [comment]
Alternative approach, make the feature opt-in. Existing users will not get the regressions, and bleeding-edge users can report problems they experience.

**Comment by monosoul** [comment]
Yeah, pgjdbc doesn't support `OffsetDateTime` out of the box, only `java.sql.Timestamp` or `java.sql.Timestamp` + `java.util.Calendar`

**Comment by lukaseder** [comment]
`OffsetDateTime` is supported in `org.postgresql:postgresql:42.2.16`, but not `OffsetTime`

**Comment by monosoul** [comment]
yeah, sorry, just confused it :)

**Comment by lukaseder** [comment]
Anyway. Offering the functionality as opt-in features is totally possible. I just don't want to change the defaults yet.

**Comment by monosoul** [comment]
yeah, I believe opt-in is totally fine here

**Comment by laszlovandenhoek** [comment]
Perhaps this setting is worth mentioning at https://www.jooq.org/doc/latest/manual/code-generation/codegen-advanced/codegen-config-generate/codegen-generate-java-time-types/ because that's often used in conjunction? For now, I'll describe how I ran into the issue, and how `bindOffsetDateTimeType` fixed it.

When you have a `TIMESTAMP WITH TIME ZONE` column in Postgres:

```
CREATE TABLE "foo" ( "bar" TIMESTAMP WITH TIME ZONE);
-- insert some records too
```

...which is mapped to an `OffsetDateTime` field, and then try to query it using the jOOQ DSL:

```
DSL.select(FOO.BAR).from(FOO).fetch();
```

...but forget to set `bindOffsetDateTimeType` to `true`, **then you get this error**:

```
java.lang.IllegalArgumentException: Cannot decode value of type java.lang.String with OID 1184
```

To eliminate this problem, set `bindOffsetDateTimeType` to `true`. One way is by adding it to your `DSLContext` (see https://www.jooq.org/doc/latest/manual/sql-building/dsl-context/custom-settings/):

```
final Settings settings = new Settings().withBindOffsetDateTimeType(true);

DSLContext dsl = DSL.using(cfi)
        .configuration()
        .derive(settings)
        .dsl();

dsl.select(FOO.BAR).from(FOO).fetch();
```
