### ISSUE TITLE
listAgg throws exception on SQLite

### ISSUE THREAD

**Issue by A1Liu** [jOOQ/jOOQ#9918]
### Expected behavior and actual behavior:

Expected: listAgg should generate `group_concat(tbl.name, ';')` in SQLite  
Actual: listAgg generates `group_concat(tbl.name order by tbl.name, ';')`

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):
SQL:
```
CREATE TABLE tbl (
  id integer,
  value1 varchar(5),
  value2 varchar(1),
  primary key (id)
);
```
Java:
```
DSLContext context = DSL.using(conn, SQLDialect.SQLITE);
context
  .select(listAgg(Tables.TBL.VALUE1).withinGroupOrderBy(Tables.TBL.VALUE1))
  .from(Tables.TBL)
  .groupBy(Tables.TBL.VALUE2)
  .execute();
```

### Versions:

- jOOQ: 3.13.1
- Java: 12
- Database (include vendor): SQLite (Xerial)
- OS: Mac/Linux
- JDBC Driver (include name if inofficial driver): "org.xerial:sqlite-jdbc:3.30.1"

**Comment by lukaseder** [comment]
Thanks a lot for your message. We currently do not emulate `LISTAGG` (which has a mandatory `WITHIN GROUP (ORDER BY ..)` clause in SQLite. Do note, however, that we have native support for `DSL.groupConcat()`

I hope this helps.

**Comment by A1Liu** [comment]
groupConcat is deprecated; will there ever be a non-deprecated way to acheive this behavior in JOOQ?

**Comment by lukaseder** [comment]
@A1Liu Only one of the overloads is deprecated: The one that is not really necessary. The other ones are still available, also for SQLite.
