### ISSUE TITLE
getJavaClassExtends not being called during code generation?

### ISSUE THREAD

**Issue by demichej** [jOOQ/jOOQ#9929]
### Expected behavior and actual behavior:
I have a `DefaultGeneratorStrategy` that overrides both the getJavaClassImplements and the getJavaClassExtends methods. However, only the interfaces method appears to ever be called. Am I missing something, does the getJavaClassExtends get called only in certain situations (e.g. making pojos or something?). My assumption/expectation was that I could add say an AbstractRecord to some records, but is that not the case?

### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

Create a DefaultGeneratorStrategy, and override getJavaClassExtends. Notice that it's never called.

### Versions:

- jOOQ: 3.13.1
- Java: 1.8.0_231
- Database (include vendor): Postgres
- OS: Linux
- JDBC Driver (include name if inofficial driver):

**Comment by demichej** [comment]
Nevermind, I see. It is only for pojos....

**Comment by lukaseder** [comment]
Thank you very much for your report.

Historically, we've supported class extension in generated code only for POJOs where there are no internal API contracts that need to be fulfilled (and such restrictions needing to be documented). But this might change in the future, as it would definitely be convenient to do this: https://github.com/jOOQ/jOOQ/issues/9844

In the meantime, you can mix in behaviour using interfaces (that may contain default methods), and by generating custom code sections:
https://www.jooq.org/doc/latest/manual/code-generation/codegen-custom-code/

I hope this helps.

**Comment by lukaseder** [comment]
Duplicate of https://github.com/jOOQ/jOOQ/issues/9844
