### ISSUE TITLE
Optimistic locking does not work when recordTimestamp column has precision less than TIMESTAMP(3)

### ISSUE THREAD

**Issue by chrisawad** [jOOQ/jOOQ#9933]
### Expected behavior and actual behavior:
Inserting a new record using record.store() then selecting the same record based on id should produce similar record timestamps. In actual behavior, the selected record's timestamp is rounded.
 
### Steps to reproduce the problem (if possible, create an MCVE: https://github.com/jOOQ/jOOQ-mcve):

1. With jooq-config.xml configured with recordTimestampFields set to TimeUpdated
2. Insert then select the same record via:
```java
UserRecord insert = db.newRecord(User.USER);
insert.setUsername("TestUser");
if (insert.store() == 1) 
{
    UserRecord select = db.selectFrom(User.USER)
              .where(User.USER.ID.equals(insert.getID()))
              .fetchOne();

   System.out.println(insert);
   System.out.println(select);
}
```
3. Notice TimeUpdated field for the selected item is not the same as the inserted item. In my case, the inserted item's TimeUpdated field contains 2020-03-10 17:08:26**.449** and the selected one contains 2020-03-10 17:08:26**.0**

### Versions:

- jOOQ: 3.12.1
- Java: 11
- Database (include vendor): MySQL 8.0
- OS: Fedora 30
- JDBC Driver (include name if inofficial driver): com.mysql.jdbc.Driver

**Comment by lukaseder** [comment]
There's nothing much fancy that jOOQ does here. The timestamp precision prior to insertion is that of `java.sql.Timestamp`, the JDBC driver's `Timestamp` type. That is milliseconds.

If you're storing that to a datetime or timestamp column without any fractional seconds precision, then you're losing that information. Example:

```sql
create table t (
  t1 timestamp,
  t2 timestamp(6)
)

insert into t values ('2000-01-01 00:00:00.123', '2000-01-01 00:00:00.123');

select date_format(t1, '%T.%f'), date_format(t2, '%T.%f') from t;
```

Yields:

```
|date_format(t1, '%T.%f')|date_format(t2, '%T.%f')|
|------------------------|------------------------|
|00:00:00.000000         |00:00:00.123000         |
```

I hope this helps

**Comment by chrisawad** [comment]
Are you saying this isn't a defect? It is affecting assertEquals(insert.getTimeUpdated(), select.getTimeUpdate()) in my junit test. 

Why is precision kept with the automatic fetch of TimeSorted after store() and lost when fetched manually using a select? Shouldn't they be the same?

**Comment by lukaseder** [comment]
> Are you saying this isn't a defect? It is affecting assertEquals(insert.getTimeUpdated(), select.getTimeUpdate()) in my junit test.

Well, then your test assumption might be wrong :)

> Why is precision kept with the automatic fetch of TimeUpdated after store() and lost when fetched manually using a select? Shouldn't they be the same?

The value is not re-fetched from the database, unless you specify `Settings.returnAllOnUpdatableRecord`. It's still the value you set in the record yourself (via the record timestamp feature).

There could be other reasons why your record is stale despite your just saving it a moment before. Think of triggers...

**Comment by chrisawad** [comment]
> The value is not re-fetched from the database, unless you specify `Settings.returnAllOnUpdatableRecord`.

So, if jooq-config.xml specifies the field name in `<recordTimestampFields>TimeUpdated</recordTimestmapFields>` during code-gen, jOOQ just carries the fractional seconds timestamp from memory (the one generated before the insert), into the returned object then?

If that's the case, it deserves more noting in the docs that the returned record timestamp may be more precise than than what is actually stored in the database. That or, precision should be figured out from the codegen meta-data and made to match before returning.

That being said, `Settings.returnAllOnUpdatableRecord ` indirectly does solves the problem by ensuring the precision in the db is presented in the stored record. It's just a bit more work on the server side.

**Comment by chrisawad** [comment]
I see what you mean that my test assumption might be wrong though :). I do appreciate the clarification. It definitely helps me understand jooq a bit more.

**Comment by lukaseder** [comment]
> jOOQ just carries the fractional seconds timestamp from memory (the one generated before the insert), into the returned object then?

There is no "returned object". The object sends its contents to the server, and *maybe* updates some of its attributes, as requested by the relevant `Settings` (by default, the identity on insert, optionally other fields on insert/update).

> If that's the case, it deserves more noting in the docs that the returned record timestamp may be more precise than than what is actually stored in the database

I'll definitely add a remark here about making sure the DB column has sufficient precision:
https://www.jooq.org/doc/3.13/manual/sql-building/dsl-context/custom-settings/settings-optimistic-locking/

Where else would that be documented? I'm asking, because I wonder where such documentation would have lead to your better understanding. We have a ton of documentation, but it's not always obvious where to look for something.

> That or, precision should be figured out from the codegen meta-data and made to match before returning.

I'll think about it. Perhaps there's a possibility to improve this, indeed. While I don't think the problem is with the `INSERT` behaviour, optimistic locking itself will break if the client and server side timestamps don't match.

Which is a good reminder that number-based versioning works better than a timestamp based one...

**Comment by lukaseder** [comment]
Turned this back to a defect. While I don't think the problem is with the data precision mismatch before / after the insert as in your code example (it can happen with any column, not just with the ones that jOOQ generates for you), in this case, optimistic locking might not work if the truncation that happens on the insertion does not also apply when producing an update or delete predicate.

**Comment by lukaseder** [comment]
I can produce the optimistic locking problem on H2 using this schema:

```sql
CREATE TABLE precision_ts_1 (
  id int not null,
  value int not null,
  ts timestamp(1) not null,
  
  constraint pk_precision_ts_1 primary key (id)
); 
```

And this test:


```java
private <R extends UpdatableRecord<R>> void testPrecision(
    Table<R> t,
    TableField<R, Integer> id,
    TableField<R, Integer> value,
    TableField<R, ?> ts
) {
    ctx.settings().setExecuteWithOptimisticLocking(true);
    R r1 = ctx.newRecord(t);

    r1.set(id, 1);
    r1.set(value, 1);
    assertEquals(1, r1.store());

    r1.set(value, 2);
    assertEquals(1, r1.store()); // This call fails

    R r2 = ctx.selectFrom(t).where(id.eq(1)).fetchSingle();

    assertEquals(r1.get(ts), r2.get(ts));
}
```

The failing stacktrace is:

```
org.jooq.exception.DataChangedException: Database record has been changed or doesn't exist any longer
	at org.jooq.impl.UpdatableRecordImpl.checkIfChanged(UpdatableRecordImpl.java:443)
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate0(UpdatableRecordImpl.java:252)
	at org.jooq.impl.UpdatableRecordImpl$2.operate(UpdatableRecordImpl.java:209)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:130)
	at org.jooq.impl.UpdatableRecordImpl.storeUpdate(UpdatableRecordImpl.java:205)
	at org.jooq.impl.UpdatableRecordImpl.store0(UpdatableRecordImpl.java:192)
	at org.jooq.impl.UpdatableRecordImpl$1.operate(UpdatableRecordImpl.java:135)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:130)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:131)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:123)
	at org.jooq.codegen.test.recordtimestamp.RecordTimestamp.testPrecision(RecordTimestamp.java:94)
	at org.jooq.codegen.test.recordtimestamp.RecordTimestamp.testPrecisionTs1(RecordTimestamp.java:67)
```

The failing update query doesn't update anything, because of the wrong precision:

```
update "PRECISION_TS_1"
set 
  "PRECISION_TS_1"."VALUE" = 2,
  "PRECISION_TS_1"."TS" = timestamp '2020-03-12 09:55:03.147' 
where "PRECISION_TS_1"."ID" = 1 
and "PRECISION_TS_1"."TS" = timestamp '2020-03-12 09:55:03.106'
```

**Comment by lukaseder** [comment]
It could be tempting to hi-jack this issue to also support higher precision timestamps using `Timestamp.setNanos()`. This could lead to subtle regressions in systems that so far did not use nano second precision with optimistic locking. We'll currently limit ourselves to a precision of 3, max.

**Comment by lukaseder** [comment]
Another interesting question is when people decide to use a `DATE` column for the `Table.getRecordTimestamp()`, in case of which time zones need to be considered for truncation.

**Comment by lukaseder** [comment]
Fixing this introduces a regression risk for code bases where no precision information is being generated on timestamps. The default precision in jOOQ being `0`

It seems the generated timestamp meta data is not yet reliable enough for this fix to be correct in all dialects. I'll push the fix nonetheless and increase prioritisation of fixing code generation through other issues.

Given the regression risk, this fix will not be backported. The workaround is to provide sufficient precision in the database schema.

**Comment by lukaseder** [comment]
Code generation issue: https://github.com/jOOQ/jOOQ/issues/9945

**Comment by lukaseder** [comment]
More thorough introspection shows that we currently do not really generate correct `TIMESTAMP` precision information in almost all dialects, see further analysis in #9945.

**Comment by lukaseder** [comment]
Fixed for 3.14.0. No backport scheduled for the reasons mentioned.

**Comment by lukaseder** [comment]
To prevent regressions, we'll introduce a new notion of undefined precision (and scale, length) in `DataType`, which will apply e.g. when we write `SQLDataType.TIMESTAMP`. Only when the timestamp precision is set to zero (or some other value) *explicitly* will we use this information for optimistic locking. See #9958 

This, and implementing #9945 (better code generation support for `TIMESTAMP` precision) are important prerequisites for this fix here.

**Comment by lukaseder** [comment]
The issue still persists with `LOCALDATETIME(p)` timestamps: #10192

**Comment by chrisawad** [comment]
It's quite beautiful to see your progression here. Looking forward to testing the next scheduled release.
