### ISSUE TITLE
CreateIndexStep is not a Query

### ISSUE THREAD

**Issue by perceptron8** [jOOQ/jOOQ#9974]
Despite what [javasdoc](https://www.jooq.org/javadoc/latest/org.jooq/org/jooq/CreateIndexStep.html) says, `CreateIndexStep` is not a `Query`. Conrtary, `DropIndexOnStep` _does_ (indirectly) extend `Query`. Why is it different? Is it by design or by mistake?

I know that "It is usually not recommended to reference any `XYZ*Step` types directly", but I've got a very specific use case where I have to drop all public and foreign keys, deactivate all indexes and then recreate / reactivate them later. I was hoping to use `List<Query>` as a carrier type within some of my classes, but because of `CreateIndexStep` not being `Query` I'm forced to use `List<String>`.

I really wish statement like `Query createIndex = DSL.createIndex(index);` was valid.

**Comment by lukaseder** [comment]
So far, all dialects supported by jOOQ require an `ON` clause on the `CREATE INDEX` statement. While it would be possible to qualify an index with its table name to make that part superfluous, it is not possible to omit any column names for index creation. So, the `ON` clause is mandatory, and the `CreateIndexStep` does not directly extend `Query`.

This is different with dropping indexes. Some dialects require an `ON` clause (e.g. SQL Server), whereas others don't. The distinction is usually made based on whether the index namespace is per schema (no `ON` clause required), or per table (`ON` clause required).

This article explains jOOQ's fluent API design in general: https://blog.jooq.org/2012/01/05/the-java-fluent-api-designer-crash-course

Regarding your *actual* issue here, while at first it seems reasonable to expect to be able to use the DSL API for "partially complete" statements like the one you suggested (`DSL.createIndex(index)`), that's not a good idea. The DSL API mimicks the SQL language and as such, expects users to be as explicit as possible with what objects they're passing to the DSL API.

It is much better, for *specific* use cases like yours, to offer dedicated APIs. For example: `Meta.ddl()` or `DSLContext.ddl()` seem more suitable in your case. I think those latter APIs already cover all your needs.

**Comment by perceptron8** [comment]
@lukaseder I'll stick to `DSL.createIndex(index).on(index.getTable(), index.getFields())` then as I want activation phase be symmetrical to deactivation. Thank you very much for your time and detailed answer!

**Comment by lukaseder** [comment]
Makes sense. Notice that in the future, we'll want to support some synthetic DDL statements including dropping / disabling / enabling all of a table's or schema's indexes / constraints:
https://github.com/jOOQ/jOOQ/issues/9526
