### ISSUE TITLE
Customizing the JavaGenerator to prepend annotations to generated POJOs

### ISSUE THREAD

**Issue by ChristianIvicevic** [jOOQ/jOOQ#9983]
### Your question:

Just wanted to quickly ask what you suggest on how to prepend custom annotations to generated POJOs. The `generatePojo0` method is currently private and the associated `printClassAnnotations` method would be most likely the candidate of choice to hook into. However it offer no way to distinguish what class the annotations are currently generated for. In my case I want to add the `lombok.With` annotation that only makes sense for POJOs.

My current hack is to hook into the `generatePojoClassJavadoc` method as follows:

```java
import lombok.With;
import lombok.extern.slf4j.Slf4j;
import org.jooq.codegen.JavaGenerator;
import org.jooq.codegen.JavaWriter;
import org.jooq.meta.TableDefinition;

@Slf4j
public class LombokedGenerator extends JavaGenerator {
  @Override
  protected void generatePojoClassJavadoc(final TableDefinition table, final JavaWriter out) {
    super.generatePojoClassJavadoc(table, out);
    log.info("Adding '@With' annotation to POJO for the table '{}'", table.getName());
    out.println("@%s", out.ref(With.class));
  }
}
```

However this isn't really reasonable since this isn't actually JavaDoc I am generating and I'd like to nitpick and append the custom annotation after the other generated annotations.

Do you have any suggestion on how to achieve this without such a hack?

### Versions:

- jOOQ: 3.12
- Java: 11

**Comment by lukaseder** [comment]
We don't have a good answer for this yet. My suggestion would have been to extend `generatePojoClassJavadoc` as well, or to re-implement the entire POJO generation.

We never designed the existing `JavaGenerator` for extension. All the current extension points were added as quick fixes for *some* cases, without designing for very generic extension. For example, you can't attach annotations to attributes or to any kind of method that is being generated.

We might think abou timproving this in the future, but it is currently not the highest priority.

> I'd like to nitpick and append the custom annotation after the other generated annotations.

Even when we re-design code generation, I somewhat doubt that we'll consider such fine grained customisability. There are generally two strategies to code generation:

- Using an object model of the target language, such as XJC for JAXB. The benefits are much higher customisability, but writing code generation code is *much* more laborious, and it only works for one target language.
- Using string based templating. The benefits are *much* simpler code generation code, and a very easy possibility to generate code in other languages, including Scala (which we already support), and possibly Kotlin, in the future.

If you feel that the order of annotations is important in your generated code, I think rolling your own from scratch will be inevitable. However, I don't recommend that, as I don't see the cost / benefit ratio is in favour of such an approach.
