### ISSUE TITLE
Converter should not applied to an unused column

### ISSUE THREAD

**Issue by Ray-Eldath** [jOOQ/jOOQ#9987]
#### Expected behavior and actual behavior:

when mapping rows from database with `.fetch`, `Converter`s will be applied *before* the data is mapped into the given `Table`. this may leads to some problem, if you get data:

```
+----+------+---------------+------------+
|  id    | state  |      email          | username    |
+----+------+---------------+------------+
|1175|Normal|omega@alpha.com| <null> |
+----+------+---------------+------------+
```

then mapped this data into a POJO, or `Record` like `User(id, state,email)` (note that `username` is not required here), the `Converter` of column `username` is still applied, this may causes performance issue or in Kotlin, will cause a NPE.

#### Versions:

- jOOQ: 3.12.3
- Java: JVM 11, Kotlin 1.3.71
- Database (include vendor): MySQL 8.0.19
- OS: Windows 10
- JDBC Driver (include name if inofficial driver): `mysql:mysql-connector-java:8.0.19`

**Comment by lukaseder** [comment]
Thanks for your report. I take that it has resolved itself?

**Comment by Ray-Eldath** [comment]
It still exist, but I just found you can narrow the selected rows with parameters of `selectDistinct` method manually... sorry for the false positive.

maybe there's still somewhat necessary to investigate this, under some cases elsewhere.
