### ISSUE TITLE
INSERT ... RETURNING documentation in chapter 4.3.4.6 is lacking further explanation about returningResult

### ISSUE THREAD

**Issue by ChristianIvicevic** [jOOQ/jOOQ#9996]
### Use case:

Using `returning(TABLE.ID).fetchOne().into(int.class)` in a `INSERT ... RETURNING` statement to return the newly auto generated id. However this results in an issue wherein jOOQ attempts to map a bigger `Record` into the `int` causing an exception.

### Possible workarounds:

After some research I found a Stackoverflow post of @lukaseder explaning that `returning` has a design-flaw and thus one has to use `returningResult(TABLE.ID).fetchOne().into(int.class)` to make it work properly.

This, however, isn't mentioned in the documentation as of now, which would be useful for the future.

### Versions:

- jOOQ: 3.12.4
- Java: 11
- Database (include vendor): Postgres 11

**Comment by lukaseder** [comment]
Thank you very much for your report. I agree we should rather document `returningResult()` than `returning()` in the manual, for all versions of jOOQ that had the method, i.e. starting from jOOQ 3.11
